#
# Wiadomosci uzywane w gdialog.c do niestandardowego sterowania walka NPC.
#
{0} {} {Seria}
{1} {} {Ucieczka}
{2} {} {Ulubiona broñ}
{3} {} {Odleg³oœæ}
{4} {} {Kogo zaatakowaæ}
{5} {} {Leczenie}

{10} {} {Gotowe}
{11} {} {Anuluj}

#
# Opcje serii.
#
{99} {} {Nie dotyczy.}
{100} {} {Zawsze!}
{101} {} {Czasami. Nie martw siê, ¿e mnie trafisz}
{102} {} {Nie krzywdŸ mnie w ¿aden sposób}
{103} {} {Uwa¿aj, aby mnie nie trafiæ}
{104} {} {Nie rañ mnie pod ¿adnym pozorem}

#
# Opcje ucieczki.
#
{200} {} {Za³osny tchórz}
{201} {} {Boli mnie palec}
{202} {} {Lekko krwawiê}
{203} {} {Zle siê czujê}
{204} {} {Potrzebujê opaski uciskowej}
{205} {} {Nigdy!}

#
# Opcje ustawien broni.
#
{300} {} {Brak}
{301} {} {Wrêcz}
{302} {} {Wrêcz potem Dystansowa}
{303} {} {Dystansowa, potem Wrêcz}
{304} {} {Dystansowa}
{305} {} {Nieuzbrojony}

#
# Opcje odleglosci.
#
{400} {} {Zostañ przy mnie}
{401} {} {Naprzód!}
{402} {} {Zostañ z ty³u}
{403} {} {Gdzie chcesz}
{404} {} {Zostañ tam, gdzie jesteœ}

#
# Atakuj kto opcje.
#
{500} {} {Tego kto mnie atakuje}
{501} {} {Najsilniejszego}
{502} {} {Najs³abszego}
{503} {} {Kogokolwiek chcesz}
{504} {} {Najbli¿szego}

#
# Opcje uzycia chemicznego.
#
{600} {} {Nie u¿ywam leków}
{601} {} {Stymulanty na drobne rany}
{602} {} {Stymulanty do powa¿nych urazów}
{603} {} {Jakiekolwiek leki od czasu do czasu}
{604} {} {Jakiekolwiek leki w dowolnym momencie}