### ------- AMUNICJA
{100} {} {Bateria j¹drowa}
{101} {} {Ma³a autonomiczna jednostka magazynuj¹ca energiê.}
{200} {} {Bateria mikro-j¹drowa}
{201} {} {Sredniej wielkoœci autonomiczna jednostka magazynuj¹ca energiê.}
{300} {} {Nabój .22}
{301} {} {Ma³y jednolity nabój Bore Rimfire.}
{400} {} {Nabój 9 mm}
{401} {} {Staro¿ytny nabój pistoletowy.}
{500} {} {Nabój 10 mm}
{501} {} {Nabój do pistoletu zwyk³ego kalibru.}
{600} {} {Nabój 10 mm NSP}
{601} {} {Nabój pistoletowy z podzielonym nanostrukturalnym metalowym pociskiem.}
{700} {} {Nabój .44}
{701} {} {Obrotowy nabój du¿ej mocy.}
{800} {} {Nabój .50}
{801} {} {Nabój o du¿ej œrednicy do szczególnie wytrzyma³ych pistoletów i rewolwerów.}
{900} {} {Nabój 5 mm}
{901} {} {Nabój do broni automatycznej.}
{1000} {} {Nabój .308}
{1001} {} {Nabój do karabinu starego, ale niezawodnego kalibru.}
{1100} {} {Nabój 12 Gauge}
{1101} {} {Nabój do strzelby za³adowany œrutem.}
{1200} {} {Nabój 12 kal.}
{1201} {} {Typowy nabój do strzelby z du¿ym rozrzutem.}
{1300} {} {Granat 40 mm}
{1301} {} {Amunicja do granatników rêcznych.}
{1400} {} {Signal Cartridge}
{1401} {} {4-calowy nabój do pistoletu sygna³owego.}
{1500} {} {Flara sygna³owa}
{1501} {} {Zmodyfikowany nabój do pistoletu sygna³owego.}
{1600} {} {Flara sygna³owa}
{1601} {} {Wzmocniony nabój do pistoletu sygna³owego.}
{1700} {} {Kontener ogólnego przeznaczenia}
{1701} {} {Pojemnik do przechowywania na ka¿d¹ okazjê.}
### ------- RZUT BRONIA
{1800} {} {Kamieñ}
{1801} {} {To zwyk³y kamieñ, który wygl¹da jak granit. Jednak przez jego kszta³t jest doœæ wygodny w u¿yciu bojowym (wzmocnienie ciosu lub rzutu). Min. moc: 1.}
{1900} {} {Nó¿ do rzucania}
{1901} {} {Przedwojenny nó¿, specjalnie wywa¿ony do rzucania. Wykonany z tytanu, wycinany laserowo. Min. moc: 2.}
{2000} {} {Granat od³amkowy}
{2001} {} {Zwyk³y granat od³amkowy. Zawiera niewielk¹ iloœæ materia³ów wybuchowych. Wiêkszoœæ niebezpiecznych fragmentów powstaje bezpoœrednio z materia³u granatu. Min. moc: 3.}
{2100} {} {Granat plazmowy}
{2101} {} {Granat zawieraj¹cy magnetycznie skondensowan¹ plazmê. Detonuje ³adunek wybuchowy, wywo³uj¹c eksplozjê przegrzanej plazmy. Min. moc: 4.}
{2200} {} {Granat pulsacyjny}
{2201} {} {Elektromagnetyczny granat impulsowy, który po eksplozji generuje silne pole elektromagnetyczne. Zwykle nie wp³ywa na ¿ywe istoty. Min. moc: 3.}
{2300} {} {Granat nuklearny}
{2301} {} {Prowizoryczny granat rêczny wykonany z potê¿nego pocisku nuklearnego. Kiedy eksploduje, uwalnia tyle energii, ¿e mo¿e zniszczyæ dom. Min. moc: 5.}
### ------- AMUNIKACJA
{2400} {} {Kombinezon}
{2401} {} {Stylowy, obcis³y kombinezon z Krypty. T¹ rzecz mo¿na z zyskiem sprzedaæ na rynku. Efekty: +2 do inicjatywy.}
{2500} {} {Skórzana kurtka}
{2501} {} {Przedwojenna ciê¿ka skórzana kurtka.}
{2600} {} {Wzmocniona kurtka}
{2601} {} {Ciê¿ka skórzana kurtka wzmocniona grubsz¹ skór¹, stalowymi p³ytami i naramiennikami.}
{2700} {} {Skórzana zbroja}
{2701} {} {Rodzaj zbroi wykonanej ze skóry bramina. Technikê produkcji znaj¹ tylko mistrzowie San Brahmin.}
{2800} {} {Szata}
{2801} {} {Szata wyznawców ognia. Wykonana tajn¹ technologi¹ przy u¿yciu specjalnych materia³ów. Zapewnia dodatkow¹ ochronê przed promieniowaniem.}
{2900} {} {Wzmocniony p³aszcz}
{2901} {} {Szata wyznawców ognia. Wykonana tajn¹ technologi¹ ze specjalnych materia³ów z dodatkow¹ ochron¹ przed promieniowaniem. Pod p³aszczem ukryta jest lekka policyjna kamizelka kuloodporna.}
{3000} {} {Metalowa zbroja}
{3001} {} {Domowa zbroja, prymitywnie wykonana z polerowanych metalowych p³yt. Zapewnia doskona³¹ ochronê przed pociskami i uderzeniami, ale jest obci¹¿ona du¿¹ mas¹ i niewygodnym kszta³tem.}
{3100} {} {Tesla Armor}
{3101} {} {Ta lœni¹ca zbroja zapewnia doskona³¹ ochronê przed atakami energetycznymi. Trzy cewki elektromagnetyczne Tesli czêœciowo rozpraszaj¹ kierunkowe wstrz¹sy energetyczne.}
{3200} {} {Zbroja bojowa}
{3201} {} {Zaawansowana technologicznie zbroja wykonana z zaawansowanych polimerów ochronnych.}
{3300} {} {Zbroja bojowa Bractwa}
{3301} {} {Ulepszona wersja zbroi bojowej. Bractwo Stali dokona³o w niej wielu ulepszeñ w stosunku do wersji standardowej.}
{3400} {} {Pancerz wspomagany}
{3401} {} {Model T51b - zaawansowana technologicznie autonomiczna zbroja. Ten egzemplarz jest czêœciowo uszkodzony.}
{3500} {} {Pancerz wspomagany}
{3501} {} {Model T51b - zaawansowana technologicznie autonomiczna zbroja. Jest zasilana przez mikroreaktor j¹drowy ze stuletni¹ rezerw¹ mocy.}
{3600} {} {Pancerz drogowy}
{3601} {} {Stara skórzana kurtka mocno wzmocniona znakami drogowymi. Takie kurtki nosz¹ tylko najwiêksi skurwiele z autostrad Arizony.}
{3700} {} {Prochowiec Rangerów}
{3701} {} {Rodzaj zbroi wykonanej ze skór braminów dla Rangerów. Technikê jej produkcji znaj¹ tylko mistrzowie San Brahmin.}
###------- ROZNE RZECZY
{3800} {} {Atomowa ogniwo}
{3801} {} {Nie j¹drowa tylko atomowa i nie bateria tylko ogniwo... Atomowa ogniwo, tak czy srak jest to typowe zród³o zasilania do ma³ych pojazdów i niektórych urz¹dzeñ.}
{3900} {} {! Nie uzywaj}
{3901} {} {Oryginal - bateria mikro-rdzeniowa.}
{4000} {} {Stimpak}
{4001} {} {Lek, który by³ szeroko stosowany przed wojn¹. Po wstrzykniêciu zapewnia szybkie gojenie siê ma³ych ran. Efekty: + (20-30) zdrowia.}
{4100} {} {Kapsle do butelek}
{4101} {} {Ta torba zawiera kapsle do butelek. Ostatnio by³y u¿ywane w du¿ych osadach do wymiany w zamian za inne towary.}
{4200} {} {Przedwojenne pieni¹dze}
{4201} {} {Srodek p³atniczy, od dawna nieu¿ywany. Jednak niektórzy mieszkañcy Pustkowi nadal mog¹ byæ tym zainteresowani.}
{4300} {} {Zetony z kasyna}
{4301} {} {Te ¿etony s¹ u¿ywane w kasynach jako lokalna waluta. Gdybyœ o tym nie wiedzia³, uzna³byœ je za przedwojenne zabawki dla dzieci.}
{4400} {} {Nieœmiertelnik}
{4401} {} {Zniszczony przedmiot z wypisanym na sobie nazwiskiem ¿o³nierza i numerem identyfikacyjnym.}
{4500} {} {Smieci z kieszeni}
{4501} {} {Bezu¿yteczne œmieci z kieszeni. Wszystkie siê ró¿ni¹, ale ka¿dy ma swoje.}
{4600} {} {Token}
{4601} {} {Token u¿ywany zgodnie z ¿yczeniem w³aœciciela.}
{4700} {} {! Nie uzywaj}
{4701} {} {Oryginal - Apteczka.}
{4800} {} {Antyrad}
{4801} {} {Roztwór chemiczny, którego cz¹steczki wi¹¿¹ cz¹steczki radioaktywne i usuwaj¹ je z organizmu. Mo¿e uzale¿niaæ. Efekty: - (100-150) prom.}
{4900} {} {Antidotum}
{4901} {} {Kilka fiolek z wojskowej apteczki zawieraj¹cej ró¿ne silne antytoksyny. Leki te s¹ u¿ywane do neutralizowania trucizny zwierzêcej i jej skutków. W zestawie opaska uciskowa. Efekty: - (45-60) zatrucia.}
{5000} {} {Walizka doktora}
{5001} {} {Walizka zawieraj¹ca materia³y i narzêdzia do chirurgii polowej.}
{5100} {} {! Nie uzywaj}
{5101} {} {Oryginal - Dynamite.}
{5200} {} {Licznik Geigera}
{5201} {} {Licznik Geigera firmy Watts Electronics. Rejestruje obecnoœæ i moc pól promieniowania.}
{5300} {} {Mentaty}
{5301} {} {Tabletki rozszerzaj¹ce umys³. Poprawiaj¹ funkcje mózgu zwi¹zane z pamiêci¹, a tak¿e przyœpieszaj¹ niektóre procesy umys³owe. Mo¿e uzale¿niaæ. Efekty: +2 IN, +2 PE, +1 CH.}
{5400} {} {Stealth Boy}
{5401} {} {Osobiste urz¹dzenie maskuj¹ce „Invisible 3001” firmy RobCo. Generuje pole moduluj¹ce, które przesy³a odbite œwiat³o z jednej strony obiektu na drug¹. Efekty: Skradanie +20.}
{5500} {} {Walkie-Talkie}
{5501} {} {Wa¿ny model 2043B krótkofalówki od doskona³ej firmy Watts Electronics. Niezawodny, trwa³y i zakamuflowany.}
{5600} {} {Pu³apka na iguany}
{5601} {} {Domowa pu³apka na pustynne jaszczurki.}
{5700} {} {Udawana zbroja}
{5701} {} {Parê metalowych czêœci na ramiê ze starymi paskami. W przypadku braku normalnej zbroi nawet to mo¿e uratowaæ ¿ycie. Albo i nie.}
{5800} {} {Ciernie}
{5801} {} {Kolczasty bicz jest broni¹ prawdziwie miêso¿ernych roœlin.}
{5900} {} {Czujnik ruchu}
{5901} {} {Czujnik ruchu firmy Watts Electronics, model „V-DOK”. Za pomoc¹ ma³ego radaru rejestruje ruch du¿ych obiektów w promieniu kilku metrów.}
### ------- PROVIANT
{6000} {} {Iguana-on-a-stick}
{6001} {} {Pustynna jaszczurka pieczona ze skór¹ w ogniu. Bez smaku i ma³o po¿ywna. Poza tym nie masz pewnoœci, czy ¿y³a w czystym ekologicznie œrodowisku. Efekty: +2 do zdrowia.}
{6100} {} {Mutoowoc}
{6101} {} {Niezwyk³y owoc. Bez konserwantów i barwników. Efekty: +3 zdrowia.}
{6200} {} {Miêso}
{6201} {} {Te suszone i wêdzone kawa³ki miêsa pozostaj¹ jadalne, a nawet trochê po¿ywne przez wiele, wiele, wiele lat... Efekty: +4 zdrowia.}
{6300} {} {Makaron Antebellum}
{6301} {} {Makaron w puszkach znanej przed wojn¹ marki. Co dziwne, nadal mo¿na go jeœæ. Efekty: +7 zdrowia.}
{6400} {} {Mro¿one danie}
{6401} {} {Mro¿one przedwojenne danie z napisem "instant". Nie mo¿esz z ca³¹ pewnoœci¹ stwierdziæ, co to oznacza, ale nie wygl¹da to tak atrakcyjnie, jak kiedyœ. Efekty: +10 zdrowia, +5 Temp.Zdr..}
{6500} {} {Larwy}
{6501} {} {Ogromne larwy owadów przypominaj¹ce muchy rozmna¿aj¹ce siê wewn¹trz zw³ok. Dla zwyk³ego mieszkañca pustkowi to prawdziwa uczta bogata w bia³ko. Efekty: +2 do zdrowia.}
{6600} {} {Potrawka z bramina}
{6601} {} {Potrawka wed³ug specjalnego przepisu. Oprócz oczywistego udzia³u bramina, mo¿e tu te¿ byæ... wszystko. Efekty: +5 zdrowia, +5 inicjatywy.}
{6700} {} {Zupa ze szczurów}
{6701} {} {Wspania³e danie ze szczura kanalizacyjnego i nierozpoznawalnych dodatków. Trochê wszystkiego. Efekty: +6 zdrowia.}
{6800} {} {RPI}
{6801} {} {Indywidualna racja ¿ywnoœciowa dla ¿o³nierza Bractwa Stali. Inni mieszkañcy Sonory mog¹ tylko pomarzyæ o czymœ takim. Efekty: +12 Zdrowia, +10 temp.zdr..}
{6900} {} {Zepsute jedzenie}
{6901} {} {Talerz z dziwnym miêsem. Nie ma z tego ¿adnego po¿ytku, ale mo¿esz spróbowaæ. Efekty: + (5-15) zatrucia.}
{7000} {} {Pieczony karaluch}
{7001} {} {Pieczony karaluch ze szczypt¹ soli morskiej. Mmm, palce lizaæ! Efekty: +2 do zdrowia.}
{7100} {} {Chipsy}
{7101} {} {Pude³ko z napisem „Frito Bandito”. Ku twojemu zaskoczeniu, w œrodku oprócz powietrza wci¹¿ s¹ stare chipsy ziemniaczane. Efekty: +5 zdrowia.}
{7200}{}{Kurtka Czarnego Poszukiwacza}
{7201}{}{Ciê¿ka przedwojenna skórzana kurtka, wzmocniona na potrzeby eksploracji Ruin Blasku. Wnêtrze wykonane jest z folii i tkaniny syntetycznej chroni¹cej przed promieniowaniem.}
### ------- INSTRUMENTY
{7300} {} {! Rezerwacja ksi¹¿ek}
{7301} {} {Nie uzywaj (Wielka Ksiega Nauki).}
{7400} {} {Wytrych}
{7401} {} {Prowizoryczny klucz do otwierania klasycznych zamków mechanicznych. Niezbyt trwa³y.}
{7500} {} {Dekoder}
{7501} {} {Potê¿ny kalkulator do hakowania systemów elektronicznych. Ledwo wystarcza do otwarcia nawet jednego.}
{7600} {} {! Rezerwacja ksi¹¿ek}
{7601} {} {Nie uzywaj (elektronika).}
{7700} {} {Maska gazowa}
{7701} {} {Stara podniszczona cywilna maska gazowa. Mo¿e ci jeszcze przez jakiœ czas s³u¿yæ.}
{7800} {} {Blacharskie Okulary}
{7801} {} {Elektroniczne okulary wykonane przez blacharzy Tu-San. Wyposa¿one w noktowizor, wymienne soczewki i ró¿ne czujniki. Bateria wystarcza na 10 minut.}
{7900} {} {Flara}
{7901} {} {Flara ostrzegawcza, œwieci przez krótki czas po jej u¿yciu. Papier jest nieco postrzêpiony, ale poza tym wszystko jest w porz¹dku. Obróæ górê, aby w³¹czyæ.}
{8000} {} {! Rezerwacja ksi¹¿ek}
{8001} {} {Nie u¿ywaæ (pierwsza pomoc, ksiazka pierwszej pomocy).}
{8100} {} {Buty}
{8101} {} {Para starych, ale mocnych gumowych butów. Wydaje siê, ¿e s¹ w stanie wytrzymaæ dzia³anie substancji ¿r¹cych, przynajmniej przez chwilê.}
{8200} {} {Lopata}
{8201} {} {Zwyk³a ³opata do wykopywania niezwyk³ych skarbów. Opiekuj siê ni¹ dobrze.}
{8300} {} {Lina}
{8301} {} {Mocna, gruba lina. Oko³o 40 stóp d³ugoœci.}
{8400} {} {Zapalniczka}
{8401} {} {Srebrna zapalniczka gazowa. W dobrym stanie.}
{8500} {} {Materia³y wybuchowe}
{8501} {} {Cordexowe plastikowe materia³y wybuchowe klasy wojskowej. Bardzo stabilne, bardzo mocne. Wyposa¿one w minutnik.}
{8600} {} {! Rezerwacja ksi¹¿ek}
{8601} {} {Nie uzywaj (Podrecznik skauta).}
{8700} {} {Wygrzew}
{8701} {} {Potê¿ne sterydy. Ich efektem jest zwiêkszenie si³y i wyostrzenie refleksu. Silnie uzale¿niaj¹ce. Efekty: +2 SI, +2 ZR, +3 WT.}
{8800} {} {Z³om}
{8801} {} {Cenne czêœci sprzetów mechanicznych i nie tylko. Mog¹ byæ przydatne do napraw lub do zyskownej wymiany.}
{8900} {} {Czêœci elektroniczne}
{8901} {} {Ró¿ne czêœci elektroniczne: kondensatory, lampy katodowe, cewki i inne. Wszystko to mo¿e siê przydaæ przy naprawach lub zyskownej wymianie.}
{9000} {} {Mieszanina palna}
{9001} {} {Butelka zawieraj¹ca mieszaninê ró¿nych ³atwopalnych substancji. Stosunkowo cenny zasób w warunkach poatomowych.}
{9100} {} {! Nie uzywaj}
{9101} {} {Original - Doctor's Case.}
{9200} {} {Truj¹cy gruczo³}
{9201} {} {Fragment ogona Radskorpiona, który zawiera trochê miêsa... i ¿elazo z silnym jadem.}
{9300} {} {Trinitite}
{9301} {} {Minera³ utworzony z piasku w epicentrum wybuchu j¹drowego. Na pierwszy rzut oka nic niezwyk³ego, ale zabójczy w swojej radioaktywnoœci obiekt.}
{9400} {} {Ocala³a ksi¹¿ka}
{9401} {} {Jedna z nielicznych zachowanych ksi¹¿ek z okresu przedwojennego. Wiêkszoœæ uzna to za sposób na rozpalenie ognia, a tylko nieliczni zobacz¹ najcenniejsze Ÿród³o staro¿ytnej wiedzy.}
{9500} {} {M¹ka kukurydziana}
{9501} {} {Cenny produkt dietetyczny nowoczesnej produkcji. Zawiera drobne zanieczyszczenia.}
{9600} {} {Srodek czyszcz¹cy}
{9601} {} {Skamienia³y proszek do usuwania zanieczyszczeñ. Zmywa nawet stuletni brud.}
{9700} {} {Chusteczki nawil¿ane}
{9701} {} {Zapieczêtowane opakowanie z chusteczkami higienicznymi. Zastêpuj¹ wannê podczas wêdrowki po pustkowiu.}
{9800} {} {Wasteland Gum}
{9801} {} {Dojrza³e liœcie rzadkiej roœliny nieu¿ytkowej. Wielu podró¿ników ceni je jako bogate Ÿród³o mikroelementów, a mieszkañcy miast ceni¹ je jako sposób na dobr¹ zabawê.}
{9900} {} {Kawa}
{9901} {} {Ten s³oik zawiera trochê „ziaren kawy”. NajwyraŸniej jest to ledwo zachowany produkt Starego Swiata.}
{10000} {} {Sanda³y z opon}
{10001} {} {Para sanda³ów ze starych opon domowej roboty. Lepsze ni¿ nic.}
{10100} {} {Ceramika}
{10101} {} {Proste naczynie wykonane z gliny. Takie rzeczy s¹ cenione w wielu osadach.}
{10200} {} {! Rezerwacja ksi¹¿ek}
{10201} {} {Nie uzywaj (broni i amunicji).}
{10300} {} {Strój wojenny hodowców}
{10301} {} {Ubiór miejscowych plemion. Zestaw zawiera drewnian¹ tarczê i skórzan¹ pelerynê.}
{10400}{}{Pancerz bojowy HMP}
{10401}{}{Zaawansowana technologicznie przedwojenna zbroja z insygniami Republiki Nowego Meksyku.}
{10500} {} {Manierka podró¿na}
{10501} {} {Ta flaszka to prezent od mieszkañców Krypty. U³atwi ci to podró¿owanie po ja³owej pustyni.}
{10600} {} {Nuka Cola}
{10601} {} {Butelka przedwojennego napoju o smaku bezalkoholowym. Ciep³y i suchy. Efekty: + (3-5) zdrowia.}
{10700} {} {Napromieniowana Nuclear Cola}
{10701} {} {Wspania³y przedwojenny napój w lekko brudnej butelce. Ma wspania³y smak i œlicznie œwieci w ciemnoœci. Efekty: + (3-5) zdrowia, +3 rad.}
{10800} {} {Woda oczyszczona}
{10801} {} {To naczynie zawiera ¿yciodajn¹ wodê pitn¹, oczyszczon¹ z zanieczyszczeñ i promieniowania. Powinna byæ u¿ywana bardzo oszczêdnie, zw³aszcza podczas podró¿y. Efekty: + (7-10) zdrowia.}
{10900} {} {Rad-X}
{10901} {} {Lek przeciw promieniowaniu do za¿ywania PRZED ekspozycj¹. Nie powoduje skutków ubocznych. Efekty: +25 Odp. na prom.}
{11000} {} {Psycho}
{11001} {} {Paczka niezwyk³ych i nieznanych narkotyków, najprawdopodobniej pochodzenia wojskowego. Zamierzonym dzia³aniem jest zwiêkszenie potencja³u bojowego ¿o³nierza. Prawdopodobnie silnie uzale¿niaj¹ca. Efekty: +3 ZR, -3 IN, +25 odpornoœci na obra¿enia.}
{11100} {} {Toksyczna mieszanka}
{11101} {} {Toksyczny skoncentrowany popió³ z wybuchu j¹drowego. Rzucaj¹c te œmieci w twarz wroga, mo¿esz spokojnie obserwowaæ, jak jego oczy sp³ywaj¹ po policzkach do ust. Efekty: -2 Slonce, -5 Inicjatywa, -3 AP.}
{11200} {} {Pusta strzykawka}
{11201} {} {Sterylna, pusta strzykawka podskórna. Rzadki i cenny przedmiot dla wspó³czesnej medycyny.}
{11300} {} {Nieœmiertelnik Rycerza}
{11301} {} {Mo¿esz rozró¿niæ nazwisko od numeru identyfikacyjnego na tej przywieszce, i tyle.}
{11400} {} {Nieœmiertelnik Giermka}
{11401} {} {Mo¿esz rozró¿niæ nazwisko od numeru identyfikacyjnego na tej przywieszce, i tyle.}
{11500}{}{Meksykañski pancerz wspomagany}
{11501}{}{Autonomiczny pancerz zmodyfikowany dla meksykañskiej marynarki wojennej. Ró¿ni siê od oryginalnego modelu mniejsz¹ wydajnoœci¹ i mniejsz¹ mas¹.}
{11600}{}{Kwas}
{11601}{}{Zastrzyk mocnego kwasu.}
{11700}{}{Pancerz Bojowy Ghuli}
{11701}{}{Zepsuty pancerz bojowy. Niektóre jego czêœci zosta³y zast¹pione przydatnymi przedmiotami.}
{11800}{}{Karabin maszynowy Dixona}
{11801}{}{Ciê¿ki karabin maszynowy przeznaczony do strzelania z burty okrêtu.}
{11900}{}{Lanca uderzeniowa}
{11901}{}{Improwizowana broñ, która w kontakcie z ofiar¹ emituje pr¹d elektryczny. Min. si³a: 3.}
### ------- ALKOHOL
{12000}{}{Przedwojenne piwo}
{12001}{}{Puszka przedwojennego piwa lokalnej produkcji.}
{12100} {} {Syrop}
{12101} {} {Syrop zrobiony z soku z „ognistej agawy”. Pomimo okropnego smrodu i ostrego smaku jest bogaty w fruktozê i cukier.}
{12200} {} {Spiew}
{12201} {} {Rozcieñczony napój alkoholowy o niskiej jakoœci. Nie mo¿na ju¿ okreœliæ jego sk³adu i pochodzenia. Efekty: -1 VS, -1 IN.}
{12300} {} {Przedwojenna whisky}
{12301} {} {Mocny napój alkoholowy marki Atomic Whiskey. Jest wysoko ceniony we wspó³czesnym œwiecie na tle innych alkoholi. Efekty: -1 VS, +1 XP.}
{12400} {} {Domowy napar}
{12401} {} {Jedno z niewielu powojennych piw. Efekty: -1 niedz.}
{12500} {} {Wasteland Tequila}
{12501} {} {Bimber z Phoenix o w¹tpliwej jakoœci. Wydaje ci siê, ¿e w butelce unosi siê ma³y robak. Efekty: -1 VS.}
### ------- BRON
{12600} {} {Kastety}
{12601} {} {Solidny mosiê¿ny kastet. Chroni d³oñ i wzmacnia cios w walce wrêcz. Min. moc: 1.}
{12700} {} {Kolczaste kastety}
{12701} {} {Odmiana klasycznych kastetów. Zadaje wiêksze obra¿enia dziêki cierniom, które podczas uderzenia przebijaj¹ cia³o wroga. Min. moc: 1.}
{12800} {} {Pazury}
{12801} {} {Domowa broñ do walki wrêcz. Sk³ada siê z dwóch starych ostrzy przykrêconych do ramy opaski. Min. moc: 1.}
{12900} {} {Pneumatyczna Piêœæ}
{12901} {} {Domowe mechaniczne kastety z mosi¹dzu. Podczas ciosu mocno wyrzuca do przodu ostre kolce, które przebijaj¹ cia³o ofiary. Min. moc: 1.}
{13000} {} {Shock Glove}
{13001} {} {Zmodyfikowany sprzêt policyjny. W kontakcie z cia³em ofiary broñ ta przekazuje mu potê¿ny ³adunek elektryczny, a stara gumowa rêkawica chroni nosz¹cego przed pora¿eniem pr¹dem. Min. moc: 1.}
{13100} {} {Power Fist}
{13101} {} {Mocne kastety „Big Ram” od BitCo. Wiêkszoœæ uwa¿a, ¿e jest to najlepsza broñ do walki wrêcz. Reszta po prostu siê ich boi. Min. moc: 1.}
{13200} {} {Nó¿}
{13201} {} {Ostra broñ do przek³uwania i ciêcia. Min. moc: 1.}
{13300} {} {Nó¿ bojowy}
{13301} {} {Wysokiej jakoœci nó¿ bojowy Stallon firmy Wits Corporation. Jego producent gwarantuje, ¿e ostrze pozostanie tak samo ostre nawet po dziesiêciu latach u¿ytkowania! Min. moc: 1.}
{13400} {} {Nó¿ obosieczny}
{13401} {} {Du¿y nó¿ z obosiecznym ostrzem. Wci¹¿ zaskakuj¹co ostry. Min. moc: 1.}
{13500} {} {Rozpruwacz}
{13501} {} {The Ripper Brand Vibroknife. Zasilany akumulatorem, z¹bkowane ostrze z ³atwoœci¹ rozdziera cia³o ofiary. Min. moc: 1.}
{13600} {} {Srubokrêt elektryczny}
{13601} {} {Narzêdzie robocze do ciêcia pe³nego materia³u. Zrywa wi¹zania molekularne silnym promieniowaniem. Zasilany bateri¹ na pasku. Min. moc: 1.}
{13700} {} {W³ócznia}
{13701} {} {Zaimprowizowana spiczasta broñ. Ostrze ze starego no¿a osadzone jest na drewnianym trzonku. Min. moc: 4.}
{13800} {} {Air Lance}
{13801} {} {Osobliwy wynalazek lokalnych in¿ynierów. Przy uderzeniu uk³ad pneumatyczny gwa³townie wyrzuca ostry metalowy kolec w ofiarê, a nastêpnie za pomoc¹ sprê¿yny przywraca go na swoje miejsce. Min. moc: 4.}
{13900} {} {Lanca elektryczna}
{13901} {} {Ulubiony przedmiot policji rozpraszaj¹cej uczestników zamieszek. By³ u¿ywany wiele razy przed Wielk¹ Wojn¹. Min. moc: 4.}
{14000} {} {Pa³ka}
{14001} {} {Nieœmiercionoœna broñ do walki wrêcz wykonana z gumy i stali, wczeœniej u¿ywana przez organy œcigania. Min. moc: 3.}
{14100} {} {Lom}
{14101} {} {Solidne, ciê¿kie narzêdzie przeznaczone do demonta¿u konstrukcji. Albo do uderzania w g³owê wrogów. Min. moc: 3.}
{14200} {} {Zawodnik}
{14201} {} {Electrocap wyprodukowany przez Watts Electronics. Model najlepszego przyjaciela rolnika. Energia jest dostarczana przez baterie j¹drowe. Min. moc: 3.}
{14300} {} {Wzmocniony zawodnik}
{14301} {} {Electrocap wyprodukowany przez Watts Electronics. Model najlepszego przyjaciela rolnika. Dziêki modyfikacjom ten egzemplarz sta³ siê znacznie potê¿niejszy. Min. moc: 3.}
{14400} {} {Super Stimpak}
{14401} {} {Silny stymulant. Przez krótki czas powoduje powa¿ne os³abienie z powodu aktywnych chemikaliów w sk³adzie leku, a po pewnym czasie powoduje niewielkie uszkodzenia naczyñ krwionoœnych. Efekty: +75 Zdrowia, -1 Si³a.}
{14500} {} {M³ot}
{14501} {} {Du¿y m³ot z masywn¹ rêkojeœci¹. Popularna broñ wœród umiêœnionych typów. Min. moc: 6.}
{14600} {} {M³ot}
{14601} {} {Wywa¿ony, lekki m³otek o zwiêkszonej zwrotnoœci. I choæ kiedyœ jego celem by³o kruszenie cegie³, teraz znajdzie bardziej odpowiednie zastosowanie. Min. moc: 5.}
{14700} {} {Super Squelch}
{14701} {} {Broñ wyprodukowana przez Bractwo Stali przy u¿yciu najnowoczesniejszej technologii. Wyposa¿ony w urz¹dzenie do magazynowania energii kinetycznej, aby zwiêkszyæ si³ê uderzenia. Min. moc: 5.}
{14800} {} {Stary rewolwer}
{14801} {} {Staro¿ytna broñ cywilna. Jak wszystkie rewolwery ceniony jest za prostotê i niezawodnoœæ. Min. moc: 4.}
{14900} {} {Rewolwer policyjny}
{14901} {} {Niezawodny rewolwer firmy S&W, popularny w swoim czasie wœród policjantów i patroli drogowych. Min. moc: 4.}
{15000} {} {Bojowy rewolwer}
{15001} {} {Doskona³y rewolwer. Ulubiona broñ kolekcjonerów i pretensjonalnych typów. Teraz jest twoja. Min. moc: 5.}
{15100} {} {Wyrzutnia flar}
{15101} {} {Pistolet sygna³owy. Choæ trudno nazwaæ to broni¹, w odpowiednim momencie mo¿e przekonaæ przeciwnika do ucieczki (szczególnie w obecnoœci umiejêtnie zmodyfikowanych nabojów). Min. moc: 3.}
{15200} {} {.22 Pistolet maszynowy}
{15201} {} {Zabytkowa broñ minionej epoki. Teraz jej g³ównym celem jest strzelanie do iguan i odstraszanie chuliganów. Min. moc: 3.}
{15300} {} {Pistolet 10 mm}
{15301} {} {10mm pistolet samoza³adowczy Colt 6520. Za ka¿dym razem, gdy poci¹gniesz za spust, broñ automatycznie prze³adowuje siê, a¿ magazynek bêdzie pusty. Min. moc: 3.}
{15400} {} {10mm Pistolet maszynowy}
{15401} {} {Pistolet maszynowy H&K MP9, model 10 mm. Kompaktowa broñ z mo¿liwoœci¹ pojedyñczego strza³u i strzelania seriami. Min. moc: 4.}
{15500} {} {Meksykañski PP}
{15501} {} {Pistolet maszynowy HM-23 opracowany przez Mendoza CA. Zosta³ przyjêty przez meksykañsk¹ policjê i doskonale sprawdzi³ siê podczas zamieszek granicznych przed Wielk¹ Wojn¹. Min. moc: 4.}
{15600} {} {Pistolet .50}
{15601} {} {Automatyczny pistolet SIG-Sauer. Wymaga specjalnych umiejêtnoœci obs³ugi ze wzglêdu na ogromn¹ si³ê wystrza³u i wysoki poziom ha³asu. Min. moc: 5.}
{15700} {} {Karabin myœliwski}
{15701} {} {Pó³automatyczny karabin Colt Rangemaster. Ciê¿ki, ale niezawodny. Min. moc: 5.}
{15800} {} {Karabin bojowy}
{15801} {} {Amerykañski karabin samopowtarzalny z serii AR, wczeœniej u¿ywany w Stanach Zjednoczonych i Meksyku. Wygodny i niezawodny. Min. moc: 5.}
{15900} {} {Bomba ogniowa}
{15901} {} {Butelka z ³atwopaln¹ ciecz¹. Nie jest to czêsto widziana broñ we wspó³czesnym œwiecie. Min. moc: 4.}
{16000} {} {Karabin snajperski}
{16001} {} {Karabin DKS-501 przerobiony na kaliber 0,308. Doskona³a broñ palna dalekiego zasiêgu. Min. moc: 6.}
{16100} {} {Karabin szturmowy}
{16101} {} {AK-112 karabin szturmowy. Stary model armii, który wyszed³ z u¿ytku w okresie ostatniej wojny. Mo¿e strzelaæ pojedyñczymi strza³ami i strzelaæ seriami. Min. moc: 6.}
{16200} {} {Lekki karabin maszynowy}
{16201} {} {Karabin maszynowy Mendoza C-2075, model 5 mm. Po zaostrzeniu stosunków ze Stanami Zjednoczonymi Meksyk wznowi³ rozwój w³asnej broni, a to jest jedna z nich. Min. moc: 7.}
{16300} {} {Minigun}
{16301} {} {Przenoœny minigun Rockwell CZ53. Wielolufowy karabin maszynowy, który strzela pociskami 5 mm z niesamowit¹ prêdkoœci¹. Min. moc: 9.}
{16400} {} {Shotgun}
{16401} {} {Winchester Viewmaker to dwulufowa strzelba kal. 12. Krótka lufa z przyciêtym mahoniem. Min. moc: 6.}
{16500} {} {Strzelba bojowa}
{16501} {} {Strzelba bojowa Winchester City Killer, stan dobry. Dostarczany z uszczelniaczem Desert War dla zwiêkszenia niezawodnoœci broni. Min. moc: 6.}
{16600} {} {Strzelba szturmowa}
{16601} {} {Broñ do walki wrêcz. Konstrukcja typu bullpup jest ma³a i ³atwa w obs³udze. Min. moc: 6.}
{16700} {} {40mm Granatnik}
{16701} {} {Rêczny granatnik na pociski 40 mm. Opracowany przez Rockwell. Min. moc: 6.}
{16800} {} {Broñ laserowa}
{16801} {} {Prowizoryczna broñ wykonana z czêœci robotów przemys³owych. Emituje wi¹zkê lasera o ma³ej mocy na niewielk¹ odleg³oœæ. Min. moc: 3.}
{16900} {} {Pistolet laserowy}
{16901} {} {Pistolet laserowy Watts 1000, model cywilny. Zmniejszona moc w porównaniu do modeli wojskowych i policyjnych. Min. moc: 3.}
{17000} {} {Karabin laserowy}
{17001} {} {Karabin laserowy Watts 2000. U¿ycie kryszta³ów pozwolilo zwiêkszyæ moc tej broni. Min. moc: 4.}
{17100} {} {Pistolet plazmowy}
{17101} {} {Pistolet plazmowy Glock 86, zaprojektowany przez AI Gastona Glock. Wystrzeliwuje niewielki ³adunek plazmy rozgrzanej do granic mo¿liwoœci. Min. moc: 3.}
{17200} {} {Karabin plazmowy}
{17201} {} {Karabin plazmowy Winchester P94. Broñ energetyczna ery przemys³owej, która wystrzeliwuje rozgrzan¹ plazmê przez zahartowany mechanizm. Min. moc: 4.}
{17300} {} {Emiter}
{17301} {} {Unikalna broñ oparta na promieniowaniu mikrofalowym. Niektóre elementy zaczerpniêto z technologii przemys³owej. Min. moc: 4.}
{17400} {} {Koa}
{17401} {} {Profesjonalne narzêdzie do ciêcia i obróbki agawy ogniowej. Wykonane ca³kiem niedawno. Min. moc: 4.}
{17500} {} {Pugach}
{17501} {} {Domowy pistolet z miejscem na jeden nabój. Co dziwne, mo¿e powa¿nie zraniæ wroga, jeœli wczeœniej nie wybuchnie w rêkach. Min. moc: 3.}
{17600} {} {Karabin myœliwski z lunet¹}
{17601} {} {Pó³automatyczny karabin Colt Rangemaster wyposa¿ony w 10-krotn¹ lunetê snajpersk¹. Min. moc: 5.}
{17700} {} {.22 pistolet maszynowy}
{17701} {} {Zabytkowa broñ minionej epoki. Teraz jej g³ównym celem jest strzelanie do iguan i odstraszanie chuliganów. Min. moc: 3.}
{17800} {} {40mm granatnik}
{17801} {} {Rêczny granatnik na pociski 40 mm. Opracowany przez Rockwell. Min. moc: 6.}
{17900} {} {Winchester}
{17901} {} {Winchester model 2073, karabin z prze³adowaniem dŸwigni i cylindrycznym magazynkiem. Jeden z najnowszych modeli. Min. moc: 5.}
{18000} {} {Mop}
{18001} {} {To mop linowy. Mop. Min. moc: 1.}
{18100} {} {Pistolet .22}
{18101} {} {Prosty i bardzo niezawodny ma³y pistolet. Opracowany przez meksykañsk¹ firmê „Armas Trejo”. Min. moc: 2.}
{18200} {} {Karabin szturmowy}
{18201} {} {Karabin szturmowy AK-112. Stary model armii, który wyszed³ z u¿ytku w okresie ostatniej wojny. Wyposa¿ony w doœæ pojemny magazynek. Min. moc: 6.}
{18300} {} {Railgun}
{18301} {} {Ta broñ wykorzystuje moc elektromagnetyzmu do wystrzeliwania metalowych przedmiotów. Min. moc: 7.}
{18400} {} {Miotacz ognia}
{18401} {} {Egzeplarz miotacza ognia Torch-450. Strzela krótkimi strumieniami p³on¹cego paliwa. Min. moc: 6.}
{18500} {} {Paliwo do miotacza ognia}
{18501} {} {Pojemnik z ³atwopalnym paliwem p³ynnym.}
{18600} {} {Tehada Machine Gun}
{18601} {} {Dok³adnie obejrzyj tê star¹ broñ, a potem krzycz "Viva Tejada!" pêdz¹c do ataku. Min. moc: 6.}
{18700} {} {Blaster}
{18701} {} {Ta broñ wygl¹da jak ze starego filmu science fiction. Wystrzeliwuje wi¹zkê cz¹stek przyœpieszonych do prêdkoœci bliskiej œwiat³u. Min. moc: 3.}
{18800} {} {Laser Gatlinga}
{18801} {} {Laser Gatlinga H&K L30. Na pocz¹tku wojny by³ to tylko prototyp. Dziêki kilku prostym rozwi¹zaniom na jakiœ czas unika siê przegrzania. Zasilany mikroreaktorami j¹drowymi. Min. moc: 7.}
{18900} {} {Dzia³ko wie¿owe}
{18901} {} {Dzia³o plazmowe z podwójn¹ wie¿yczk¹.}
{19000} {} {Topór bojowy}
{19001} {} {Stary toporek kempingowy. Mo¿e byæ u¿yty w walce. Min. moc: 3.}
{19100}{}{Karabin turboj¹drowy}
{19101}{}{Karabin plazmowy Winchester P94. Broñ energetyczna epoki industrialnej, która wystrzeliwuje niezwykle gor¹c¹ plazmê. Dziêki ulepszeniu ogrzewanie jest szybsze. min. si³a: 4.}
### ------- KONTENERY
{19200} {} {Skrzynia wojskowa}
{19201} {} {Metalowa skrzynka na amunicjê o du¿ej sile uderzenia.}
{19300} {} {Pude³ko z towarami}
{19301} {} {Takie pude³ka s¹ powszechnie u¿ywane przez kupców do przechowywania ich towarów.}
{19400} {} {Pu³apka na iguany}
{19401} {} {Domowej roboty pu³apka na iguany.}
{19500} {} {Grób psa}
{19501} {} {Ta ziemia zosta³a poœpiesznie rozkopana. Wystaje z niej kilka koœci i skrawków futra.}
{19600} {} {Swie¿o wykopana ziemia}
{19601} {} {Ta ziemia zosta³a niedawno rozkopana. Byc mo¿e zosta³ tam zakopany skarb. Albo zw³oki.}
{19700} {} {Stos œmieci}
{19701} {} {Ma³y stos ró¿nych œmieci.}
{19800} {} {Odbiór paczek}
{19801} {} {Tutaj s¹ przechowywane paczki z innych miast.}
{19900} {} {Wysy³ka paczkek}
{19901} {} {Paczki przeznaczone do innych miast s¹ przechowywane tutaj.}
{20000} {} {Paczki do Flagpool}
{20001} {} {Pude³ko z rzeczami do wys³ania do innego miasta.}
{20100} {} {Paczki to Phoenix}
{20101} {} {Pude³ko z rzeczami do wys³ania do innego miasta.}
{20200} {} {Przesy³ki do Tu-San}
{20201} {} {Pude³ko z rzeczami do wys³ania do innego miasta.}
{20300} {} {Swie¿o wykopana ziemia}
{20301} {} {Ta ziemia zosta³a niedawno rozkopana. Byc mo¿e zosta³ tam zakopany skarb. Albo zw³oki.}
{20400} {} {Pude³ko}
{20401} {} {Powalone drewniane pude³ko. Aby zajrzeæ do œrodka, bêdzie trzeba rozebraæ deski.}
{20500} {} {Flara}
{20501} {} {Flara ostrzegawcza daj¹ca œwiat³o na krótki czas. Papier jest nieco postrzêpiony, ale poza tym wszystko jest w porz¹dku.}
{20600} {} {! Nie uzywaj}
{20601} {} {Oryginal - Dynamite.}
{20700} {} {licznik Geigera}
{20701} {} {Licznik Geigera firmy Watts Electronics. Rejestruje obecnoœæ i moc pól promieniowania. Obecnie w³¹czony.}
{20800} {} {Czujnik ruchu}
{20801} {} {Czujnik ruchu Watts Electronics, model „Wee-DOK”. Za pomoc¹ ma³ego radaru rejestruje ruch du¿ych obiektów w odleg³oœci kilku metrów. Obecnie w³¹czony.}
{20900} {} {Materia³y wybuchowe}
{20901} {} {Cordexowe plastikowe materia³y wybuchowe klasy wojskowej. Bardzo stabilne, bardzo mocne. Wyposa¿one w licznik czasu, który jest aktualnie aktywny.}
{21000} {} {Stealth Boy}
{21001} {} {Osobiste urz¹dzenie maskuj¹ce „Invisible 3001” firmy RobCo. Generuje pole moduluj¹ce, które przesy³a odbite œwiat³o z jednej strony obiektu na drug¹. W³¹czone.}
{21100} {} {grób}
{21101} {} {}
{21200} {} {grób}
{21201} {} {}
{21300} {} {grób}
{21301} {} {}
{21400} {} {grób}
{21401} {} {}
{21500} {} {grób}
{21501} {} {}
{21600} {} {grób}
{21601} {} {}
{21700} {} {grób}
{21701} {} {}
{21800} {} {koœci}
{21801} {} {Kilka ludzkich koœci.}
{21900} {} {wagon}
{21901} {} {Wagon karawany przerobiony z kad³uba staro¿ytnego pojazdu.}
{22000} {} {wagon}
{22001} {} {Wagon karawany przerobiony z wraku staro¿ytnego pojazdu.}
{22100} {} {du¿y dzban}
{22101} {} {Du¿y dzban do przechowywania plonów lub wody.}
{22200} {} {garnek}
{22201} {} {wyszukany gliniany garnek.}
{22300} {} {garnek}
{22301} {} {Wyszukany gliniany garnek.}
{22400} {} {pude³ko}
{22401} {} {Drewniane pude³ko wype³nione ró¿nymi rzeczami.}
{22500} {} {przedmioty}
{22501} {} {Ró¿ne rzeczy, które mo¿na podsumowaæ jednym s³owem jako „przedmioty”.}
{22600} {} {rzeczy}
{22601} {} {Ró¿ne elementy, które mo¿na podsumowaæ jednym s³owem jako „rzeczy”.}
{22700} {} {rzeczy}
{22701} {} {Ró¿norodne elementy, które mo¿na podsumowaæ jednym s³owem jako „rzeczy”.}
{22800} {} {rzeczy}
{22801} {} {Ró¿norodne elementy, które mo¿na podsumowaæ jednym s³owem jako „rzeczy”.}
{22900} {} {sejf}
{22901} {} {Ma³y sejf przykrêcony do metalowego sto³u.}
{23000} {} {skrzynia}
{23001} {} {Domowa drewniana skrzynia.}
{23100} {} {skrzynia}
{23101} {} {Domowa drewniana skrzynia.}
{23200} {} {pó³ki}
{23201} {} {Drewniana pó³ka z ró¿nymi przedmiotami.}
{23300} {} {pó³ki}
{23301} {} {Drewniana pó³ka z ró¿nymi przedmiotami.}
{23400} {} {pó³ka}
{23401} {} {Du¿a drewniana szafa z zakurzonymi przedmiotami na pó³kach.}
{23500} {} {pó³ki}
{23501} {} {Du¿a drewniana szafa z zakurzonymi przedmiotami na pó³kach.}
{23600} {} {szafa}
{23601} {} {Du¿a drewniana szafa z zakurzonymi przedmiotami na pó³kach.}
{23700} {} {stojak}
{23701} {} {Du¿a drewniana szafa z zakurzonymi przedmiotami na pó³kach.}
{23800} {} {pó³ka}
{23801} {} {Du¿a drewniana szafa z zakurzonymi przedmiotami na pó³kach.}
{23900} {} {pó³ka}
{23901} {} {Du¿a drewniana szafa z zakurzonymi przedmiotami na pó³kach.}
{24000} {} {kosz na œmieci}
{24001} {} {To kosz na œmieci. Ledwo mo¿na rozpoznaæ napis: „Utrzymuj ulicê swojego miasta w czystoœci!”}
{24100} {} {lodówka}
{24101} {} {To lodówka. Uk³ad ch³odzenia nie dzia³a.}
{24200} {} {lodówka}
{24201} {} {Antyczna przenoœna lodówka. Mechanizm nadal dzia³a.}
{24300} {} {lodówka}
{24301} {} {Zabytkowa przenoœna lodówka. Mechanizm nadal dzia³a.}
{24400} {} {stó³}
{24401} {} {Zwyk³y drewniany stó³ z wieloma szufladami.}
{24500} {} {stó³}
{24501} {} {Zwyk³y drewniany stó³ z wieloma szufladami.}
{24600} {} {stó³}
{24601} {} {Drewniany stó³ z wieloma szufladami. Praca przy takim stole to du¿e ryzyko.}
{24700} {} {stó³}
{24701} {} {Stolik kawowy z kusz¹cymi resztkami.}
{24800} {} {sejf}
{24801} {} {Bardzo wytrzyma³y sejf œcienny.}
{24900} {} {sejf}
{24901} {} {Bardzo mocny stacjonarny sejf.}
{25000} {} {stos pude³}
{25001} {} {Kilka bezpiecznych skrzyñ transportowych.}
{25100} {} {stos pude³}
{25101} {} {Kilka bezpiecznych skrzyñ transportowych.}
{25200} {} {pude³ko}
{25201} {} {Bardzo bezpieczna skrzynia transportowa.}
{25300} {} {pude³ko}
{25301} {} {Bardzo bezpieczna skrzynia transportowa.}
{25400} {} {skrzynia butelek}
{25401} {} {Drewniane pude³ko do przechowywania butelek.}
{25500} {} {kredens}
{25501} {} {Zwyk³a komoda pachn¹ca czyimœ praniem.}
{25600} {} {kredens}
{25601} {} {Zwyk³a komoda pachn¹ca czyimœ praniem.}
{25700} {} {kredens}
{25701} {} {Zwyk³a komoda pachn¹ca czyimœ praniem.}
{25800} {} {kredens}
{25801} {} {Zwyk³a komoda pachn¹ca czyimœ praniem.}
{25900} {} {! Nie uzywaj}
{25901} {} {Original - Screw.}
{26000} {} {! Nie uzywaj}
{26001} {} {Oryginal - Antidotum na smiglo.}
{26100} {} {szafa}
{26101} {} {Drewniana szafka w doskona³ym stanie.}
{26200} {} {szafa}
{26201} {} {Drewniana szafka w z³ym stanie.}
{26300} {} {szafa}
{26301} {} {Drewniana szafka. Dok³adniej, to co z niej zosta³o.}
{26400} {} {szafa}
{26401} {} {Drewniana szafka w doskona³ym stanie.}
{26500} {} {szafa}
{26501} {} {Drewniana szafka w z³ym stanie.}
{26600} {} {szafa}
{26601} {} {Drewniana szafka. Dok³adniej, to co z niej zosta³o.}
{26700} {} {zlew}
{26701} {} {Porcelanowy zlew, który ju¿ dawno straci³ swoj¹ zdolnoœæ do dzia³ania.}
{26800} {} {zlew}
{26801} {} {Porcelanowy zlew, który ju¿ dawno straci³ swoj¹ zdolnoœæ do dzia³ania.}
{26900} {} {warsztat}
{26901} {} {Tak, to jest standardowy, stary, ca³kowicie normalny stó³ warsztatowy.}
{27000} {} {tablica na narzêdzia}
{27001} {} {Na tej tablicy przechowywane s¹ ró¿ne narzêdzia.}
{27100} {} {lodówka}
{27101} {} {Lodówka na kó³kach u³atwiaj¹c¹cych transport.}
{27200} {} {stó³}
{27201} {} {Zwyk³y stó³. Jeœli kiedykolwiek widzia³eœ jeden stó³, pomyœl, ¿e widzia³eœ je wszystkie.}
{27300} {} {stó³}
{27301} {} {Zwyk³y stó³.}
{27400} {} {stó³}
{27401} {} {Zwyk³y stó³.}
{27500} {} {stó³}
{27501} {} {Zwyk³y stó³.}
{27600} {} {stó³}
{27601} {} {Zwyk³y stó³.}
{27700} {} {stó³}
{27701} {} {Zwyk³y stó³.}
{27800} {} {stó³}
{27801} {} {Zwyk³y stó³.}
{27900} {} {szafka}
{27901} {} {Metalowy schowek naœcienny.}
{28000} {} {szafka}
{28001} {} {Metalowy schowek naœcienny.}
{28100} {} {szafka}
{28101} {} {Metalowy schowek naœcienny.}
{28200} {} {szafka}
{28201} {} {Metalowy schowek naœcienny.}
{28300} {} {skrzynia}
{28301} {} {Osobista skrzynia. Przeznaczona do przechowywania rzeczy, wygodnie umieszczona przy ³ó¿ku, zamykana na klucz.}
{28400} {} {skrzynia}
{28401} {} {Osobista skrzynia. Przeznaczona do przechowywania rzeczy, wygodnie umieszczona przy ³ó¿ku, zamykana na klucz.}
{28500} {} {skrzynia}
{28501} {} {Osobista skrzynia. Przeznaczona do przechowywania rzeczy, wygodnie umieszczona przy ³ó¿ku, zamykana na klucz.}
{28600} {} {skrzynia}
{28601} {} {Osobista skrzynia. Przeznaczona do przechowywania rzeczy, wygodnie umieszczona przy ³ó¿ku, zamykana na klucz.}
{28700} {} {skrzynia}
{28701} {} {Osobista skrzynia. Przeznaczona do przechowywania rzeczy, wygodnie umieszczona przy ³ó¿ku, zamykana na klucz.}
{28800} {} {skrzynia}
{28801} {} {Osobista skrzynia. Przeznaczona do przechowywania rzeczy, wygodnie umieszczona przy ³ó¿ku, zamykana na klucz.}
{28900} {} {szafka}
{28901} {} {Osobisty pojemnik do przechowywania rzeczy.}
{29000} {} {szafka}
{29001} {} {Osobisty pojemnik do przechowywania rzeczy.}
{29100} {} {szafka}
{29101} {} {osobisty pojemnik do przechowywania rzeczy.}
{29200} {} {szafka}
{29201} {} {Osobisty pojemnik do przechowywania rzeczy.}
{29300} {} {szafka}
{29301} {} {osobisty pojemnik do przechowywania rzeczy.}
{29400} {} {szafka}
{29401} {} {Osobisty pojemnik do przechowywania rzeczy.}
{29500} {} {rzeczy}
{29501} {} {Ró¿ne rzeczy, które mo¿na podsumowaæ jednym s³owem jako „rzeczy”.}
{29600} {} {rzeczy}
{29601} {} {Ró¿ne przedmioty, które mo¿na podsumowaæ jednym s³owem jako „rzeczy”.}
{29700} {} {rzeczy}
{29701} {} {Ró¿ne œmieci, które mo¿na podsumowaæ jednym s³owem jako „rzeczy”.}
{29800} {} {rzeczy}
{29801} {} {Ró¿ne elementy, które mo¿na podsumowaæ jednym s³owem jako „rzeczy”.}
{29900} {} {skrzynia}
{29901} {} {Skrzynia wojskowa do przechowywania i transportu broni.}
{30000} {} {skrzynia}
{30001} {} {Skrzynia wojskowa do przechowywania i transportu broni.}
{30100} {} {skrzynia}
{30101} {} {Skrzynia do przechowywania i transportu amunicji wojskowej.}
{30200} {} {skrzynia}
{30201} {} {Skrzynia do przechowywania i transportu amunicji wojskowej.}
{30300} {} {stos skrzyñ}
{30301} {} {Kilka bezpiecznych skrzyñ transportowych.}
{30400} {} {stos skrzyñ}
{30401} {} {Kilka bezpiecznych skrzyñ transportowych.}
{30500} {} {skrzynia}
{30501} {} {Bardzo bezpieczna skrzynia transportowa.}
{30600} {} {skrzynia}
{30601} {} {Bardzo bezpieczna skrzynia transportowa.}
{30700} {} {szafka}
{30701} {} {Osobisty pojemnik do przechowywania rzeczy.}
{30800} {} {szafka}
{30801} {} {Osobisty pojemnik do przechowywania rzeczy.}
{30900} {} {szafka}
{30901} {} {Osobisty pojemnik do przechowywania rzeczy.}
{31000} {} {szafka}
{31001} {} {Osobisty pojemnik do przechowywania rzeczy.}
{31100} {} {kontener}
{31101} {} {Skrzynia transportowa armii chroniona przed promieniowaniem.}
{31200} {} {kontener}
{31201} {} {Skrzynia transportowa armii chroniona przed promieniowaniem.}
{31300} {} {destylatornia bimbru}
{31301} {} {To wydaje siê byæ destylatornia bimbru opalana drewnem.}
{31400} {} {plecak}
{31401} {} {Ktoœ zostawi³ tutaj ten plecak z ca³ym swoim dobytkiem.}
{31500} {} {automat sprzedaj¹cy Nuka-Colê}
{31501} {} {Reklama z boku tego automatu przedstawia popularny napój.}
{31600} {} {zw³oki wiêŸnia}
{31601} {} {Zamarzniête zw³oki zbieg³ego wiêŸnia.}
{31700} {} {brudny garnek}
{31701} {} {Naprawdê nie chcesz zag³êbiaæ siê w ten stos brudnych rzeczy.}
{31800} {} {zniszczony totem}
{31801} {} {Kupa œmieci, które kiedyœ s³u¿y³y jako totem dla Szakali.}
{31900} {} {cia³o najemnika}
{31901} {} {Zamarzniête zw³oki jednego ze stra¿ników ekspedycji. Zmar³ z powodu utraty krwi.}
{32000} {} {Stanowisko nadzorcy}
{32001} {} {Widzisz stanowisko nadzorcy. Nie by³o u¿ywane przez d³ugi czas.}
{32100} {} {metalowa szafka}
{32101} {} {Antyczna szafka pancerna. Bardzo wytrzyma³a.}
{32200} {} {zbiornik na odpady biologiczne}
{32201} {} {Szcz¹tki ludzkich cia³ po operacji zosta³y zwyczajnie wrzucone do tego zbiornika. NajwyraŸniej chirurg mia³ du¿o pracy.}
{32300} {} {resztki sier¿anta}
{32301} {} {Wysuszone do koœci zw³oki sier¿anta. NajwyraŸniej zosta³ zabity przez roboty bezpieczeñstwa.}
{32400} {} {gazeta}
{32401} {} {Ta gazeta jest prawdopodobnie pusta... albo nie.}
{32500} {} {rzeczy bandytów}
{32501} {} {Na szczêœcie porywacze zapomnieli o tych rzeczach przed wyjazdem.}
{32600} {} {œwiec¹ce grzyby}
{32601} {} {Takie œwiec¹ce w ciemnoœci grzyby rosn¹ raczej tylko w œrodku toksycznych ka³u¿.}
{32700} {} {pude³ko na dary}
{32701} {} {To pude³eczko s³u¿y do zbierania darowizn.}
{32800} {} {stó³}
{32801} {} {Elegancki, zabytkowy stó³ dla ludzi o wysokich wymaganiach. W zestawie luksusowy fotel.}
{32900} {} {szafka przeciwpozarowa}
{32901} {} {Z jakiegoœ powodu ta szafka nazywana jest "stra¿akiem". Nikt nie pamiêta, sk¹d wziê³a siê ta nazwa.}
{33000} {} {Szafka przeciwpozarowa}
{33001} {} {Z jakiegoœ powodu ta szafka nazywana jest „stra¿akiem”. Nikt nie pamiêta, sk¹d wziê³a siê ta nazwa.}
{33100} {} {Book of Beamis}
{33101} {} {Jedna z najlepszych ksi¹¿ek ery przedwojennej. Zawiera wiele ekskluzywnych informacji z tamtych czasów.}
{33200} {} {stó³ bilardowy}
{33201} {} {To stary stó³ bilardowy. Nie zagra tu jednak ¿aden szanuj¹cy siê koneser bilarda.}
{33300} {} {stó³ do ciêcia}
{33301} {} {Ten stó³ jest u¿ywany do ciêcia miêsa. Ludzkiego miêsa.}
{33400} {} {kratka wentylacyjna}
{33401} {} {Stary system wentylacji. Przez lata zebra³o siê w nim du¿o kurzu.}
{33500} {} {totem}
{33501} {} {Upiorny totem postawiony przez Rozpruwaczy z ró¿nych œmieci.}
{33600} {} {kasa}
{33601} {} {To jest kasa. A na niej stoi kasa fiskalna.}
{33700} {} {mutant}
{33701} {} {Cia³o nikczemnego mutanta.}
{33800} {} {totem}
{33801} {} {Upiorny totem stworzony przez Rozpruwaczy z ró¿nych œmieci.}
{33900} {} {totem}
{33901} {} {Upiorny totem stworzony przez Rozpruwaczy z ró¿nych œmieci.}
{34000} {} {totem}
{34001} {} {Upiorny totem stworzony przez Rozpruwaczy z ró¿nych œmieci.}
{34100} {} {totem}
{34101} {} {Upiorny totem stworzony przez Rozpruwaczy z ró¿nych œmieci.}
{34200} {} {strach na wróble}
{34201} {} {Smiesznie wygl¹daj¹cy œrodek odstraszaj¹cy szkodniki.}
{34300} {} {cia³o marudera}
{34301} {} {Cia³o m³odego mê¿czyzny rozdarte na strzêpy. Podobno wpad³ w szpony miejscowej fauny.}
{34400} {} {sarkofag}
{34401} {} {Tu spoczywa cia³o twojego przodka.}
{34500} {} {stos lodu}
{34501} {} {Dostrzegasz w tej kupie lodu ró¿ne zamro¿one rzeczy.}
{34600} {} {szafka}
{34601} {} {Osobisty pojemnik do przechowywania rzeczy.}
{34700} {} {koœci Eda}
{34701} {} {Widzisz koœci Eda. Widaæ na nich resztki kombinezonu z numerem 13.}
{34800} {} {automat z mentatami}
{34801} {} {S¹dz¹c po reklamach, ta maszyna wydaje mentaty.}
{34900}{}{Resztki robota}
{34901}{}{Ten robot zosta³ wessany przez toksyczne bagno. Co za okropna œmieræ!}
### ------- OLBRZYMI
{35000} {} {Notatki za³o¿yciela}
{35001} {} {Stary i bardzo zniszczony holodysk Za³o¿yciela Villi. Wygl¹da na to, ¿e mo¿na go w³o¿yæ do Pip-Boya.}
{35100} {} {Pamiêtnik z Krypty}
{35101} {} {Wpisy z dziennika jednego z mieszkañców Krypty 27.}
{35200} {} {Raport ekspedycji}
{35201} {} {Holodysk zabarwiony ziemi¹. Zgodnie z inskrypcj¹ zawiera on relacjê z wyprawy do Krypty 27.}
{35300} {} {Misja Quartz}
{35301} {} {Stary holodysk, pozbawiony zewnêtrznych napisów i oznaczeñ.}
{35400} {} {Nagranie McBaina}
{35401} {} {Umieraj¹ce nagranie audio Sier¿anta McBaina.}
{35500} {} {Holodysk burmistrza}
{35501} {} {Holotaœma z instrukcjami dla burmistrza Casa Grande. Twórca instrukcji nie patrzy³ w przysz³oœæ.}
{35600} {} {Notatki George'a Crooka}
{35601} {} {Holotaœma z notatkami terenowymi sporz¹dzonymi przez dowódcê wyprawy do San Brahmin.}
{35700} {} {List od Vault-Tec}
{35701} {} {Nagranie g³osowe oficjalnego listu Vault-Tec.}
{35800} {} {Wiadomoœæ z Platformy}
{35801} {} {Holotaœma listu z platformy wiertniczej Petro-Chico.}
{35900}{}{Dziennik}
{35901}{}{Dziennik Nadzorcy Krypty 24.}
{36000} {} {Swi¹teczne fajerwerki}
{36001} {} {Du¿e pude³ko z pirotechnik¹ wykonan¹ w Meksyku.}
{36100} {} {Uroczysty wieniec}
{36101} {} {Wieniec wykonany z drutów i ¿arówek. Dziwnie wygl¹da na g³owie.}
{36200} {} {Bramin}
{36201} {} {Targujesz siê o tego bramina.}
{36300} {} {Klucz magnetyczny}
{36301} {} {Ten magnetyczny klucz otwiera drzwi do mobilnej fortecy supermuntantów.}
{36400} {} {Radio}
{36401} {} {Staro¿ytne, ale wci¹¿ dzia³aj¹ce radio firmy Watts Electronics.}
{36500} {} {Przedmioty osobiste Pani Brandley}
{36501} {} {Notatnik Ann Brandley i inne jej rzeczy.}
{36600} {} {Zagubiony pakiet}
{36601} {} {Najprawdopodniej tê paczkê z wieloma dokumentami i listami niós³ kurier do Phoenix. Zawiera równie¿ notatkê: „W przypadku zagubienia paczki nale¿y j¹ zwróciæ do biura Sonora Express za op³at¹”.}
{36700} {} {Wisiorek Madre}
{36701} {} {Ten wisiorek jest pami¹tk¹ przechodz¹c¹ przez ¿eñsk¹ liniê twojej rodziny.}
{36800} {} {Zielona materia}
{36801} {} {Jakaœ substancja chemiczna z laboratorium Obserwatorów.}
{36900} {} {Purpurowa materia}
{36901} {} {Jakaœ substancja chemiczna z laboratorium Obserwatorów.}
{37000} {} {Czerwona materia}
{37001} {} {Jakaœ substancja chemiczna z laboratorium Obserwatorów.}
{37100} {} {Holodysk z biblioteki}
{37101} {} {Ten holodysk zosta³ ci podarowany przez twojego nauczyciela ze szko³y w Casa Nueva za nagranie ksi¹¿ek z Bractwa Stali.}
{37200} {} {Bia³a materia}
{37201} {} {Substancja krystaliczna, bezwonna. Trudno powiedzieæ, z czego siê sk³ada.}
{37300} {} {Notatki z labolatorium}
{37301} {} {Ten holodysk zawiera najnowsze raporty z laboratorium Greenway Hydroponics.}
{37400} {} {Insektycyd}
{37401} {} {Pojemnik zawieraj¹cy mieszaninê truj¹cych substancji.}
{37500} {} {Mapa bandytów}
{37501} {} {Ta mapa pokazuje ró¿ne lokalizacje, które s¹ pod kontrol¹ najeŸdŸców. W szczególnoœci odnotowano ich g³ówn¹ bazê w górach na wschodzie.}
{37600} {} {Cenna relikwia}
{37601} {} {Przedmiot staro¿ytnej technologii, urz¹dzenie o niejasnym przeznaczeniu z tarcz¹ i prze³¹cznikami.}
{37700} {} {Mutagen}
{37701} {} {Opryskiwacz mutagenny. Dzia³a za pomoc¹ prymitywnego mechanizmu sprê¿ynowego.}
{37800} {} {Zestaw chemika}
{37801} {} {Du¿y zestaw narzêdzi i substancji chemicznych.}
{37900} {} {He³m Pancerza wspomaganego}
{37901} {} {To jest he³m Pancerza wspomaganego T51b.}
{38000} {} {Procesor Pancerza wspomaganego}
{38001} {} {To jest procesor pancerza wspomaganego T51b.}
{38100} {} {Pude³ko z kapslami}
{38101} {} {Pude³ko wype³nione po brzegi najcenniejszymi kapslami Nuka-Coli. Prawdziwa fortuna dla zwyk³ego obywatela.}
{38200} {} {Drewniana Figurka}
{38201} {} {Figurka dawno wymar³ego zwierzêcia. Z grubsza wyrzeŸbiona z prawdziwego drewna.}
{38300} {} {! Nie uzywaj}
{38301} {} {pierwotnie Shiloh.}
{38400} {} {Zgubiony pistolet}
{38401} {} {Ten sam pistolet, który zgubiono w magazynie Rangerów.}
{38500} {} {Gogle Beamisa}
{38501} {} {To s¹ okulary do czytania Henry'ego Beamisa. S¹ po prostu ogromne.}
{38600} {} {Neurochip}
{38601} {} {Implant usuniêty z cia³a zmar³ego Blacharza.}
{38700} {} {Gwiazda Rangera}
{38701} {} {Ta odznaka trafi³a w rêce niew³aœciwych ludzi.}
{38800} {} {W¹tpliwy pakiet}
{38801} {} {Chemikalia dilera z Phoenix.}
{38900} {} {W¹tpliwy pakiet}
{38901} {} {Torba na chemikalia Niebieskich Tarczy.}
{39000} {} {! Nie uzywaj}
{39001} {} {Oryginal - Sunny Scorcher.}
{39100} {} {Has³a Fabera}
{39101} {} {Jest tu zapisanych kilka hase³. Mog¹ siê przydaæ w Kolonii Flagpool.}
{39200} {} {Umowa Eugene'a}
{39201} {} {Umowa miêdzy Rangerami, a Eugene Simonem na zatrudnienie tego drugiego.}
{39300} {} {List Hirama}
{39301} {} {List polecaj¹cy z twoim imieniem od kaznodziei Flagpool. Adresowane do Aarona, Pana Phoenix i Pana Swi¹tyni Swiêtego Ognia.}
{39400} {} {Raport doradcy}
{39401} {} {Ten holodysk da³ ci Ulysses Grant. Nale¿y go zabraæ do bazy wojskowej w Puerto Penasco.}
{39500} {} {Utracone listy}
{39501} {} {Ró¿ne listy dla adresatów w Phoenix.}
{39600} {} {G³owa Bena}
{39601} {} {Ta g³owa by³a kiedyœ na ramionach przywódcy Niebieskich Tarcz.}
{39700} {} {G³owa Hernando}
{39701} {} {Ta g³owa by³a kiedyœ na ramionach wodza Los Panchos.}
{39800} {} {G³owa Chucho}
{39801} {} {Ta g³owa by³a kiedyœ na ramionach wodza Los Panchos.}
{39900} {} {G³owa Addie}
{39901} {} {Ta g³owa by³a kiedyœ na ramionach wodza Los Panchos.}
{40000} {} {G³owa Gila McCord}
{40001} {} {Ta g³owa nale¿a³a kiedyœ do legendarnego rewolwerowca z gildii najemników.}
{40100} {} {Kawa³ek w³óczni}
{40101} {} {Od³amek w³óczni zabrany prosto z pancerza gigantycznego radskorpiona.}
{40200} {} {Swiec¹cy grzyb}
{40201} {} {Niezwyk³y grzyb, który utworzy³ siê w ka³u¿ach toksycznego paliwa. Niejadalny dla ludzi.}
{40300} {} {Czêœæ}
{40301} {} {Kartel zbieraczy prawdopodobnie zainteresuje siê t¹ staro¿ytn¹ technologi¹.}
{40400} {} {Uchwyt wci¹garki}
{40401} {} {Zardzewia³y, ale nadal u¿yteczny uchwyt. Kiedyœ umieli robiæ takie rzeczy.}
{40500} {} {Wzmacniacz sygna³u}
{40501} {} {Elektryczny wzmacniacz fal do nadajnika radiowego. Wykorzystuje najnowsz¹ generacjê zaawansowanej technologii elektronicznej lampy pró¿niowej.}
{40600} {} {Spawarka}
{40601} {} {Bardzo stara, ale nadal dzia³aj¹ca spawarka.}
{40700} {} {Aktualizacja ZAX}
{40701} {} {Aktualizacja jednej z procedur ZAX 1.1.}
{40800} {} {! Nie uzywaj}
{40801} {} {Oryginal - Wojskowa apteczka.}
{40900} {} {! Nie uzywaj}
{40901} {} {Oryginal - Torba ratownika medycznego.}
{41000} {} {Ogniwo zasilaj¹ce do generatora}
{41001} {} {Standardowy element z materia³em j¹drowym. Zaprojektowany do wytwarzania energii w generatorach Watts Electronics.}
{41100} {} {Bezpieczniki}
{41101} {} {Detonatory j¹drowe. Bez nich nie mo¿na aktywowaæ bomby atomowej.}
{41200} {} {Karta dostêpu}
{41201} {} {Karta dostêpu do niektórych pokoi niszczyciela Bractwa Stali.}
{41300} {} {Klucz torpedowy}
{41301} {} {Karta dostêpu do terminala kontrolnego przedzia³u torpedowego.}
{41400} {} {Klucz pakietu}
{41401} {} {Klucz do pakietu w Atomic Rush Casino.}
{41500} {} {Kody ze stacji}
{41501} {} {Kody dostêpu ze stacji radiowej w katedrze.}
{41600} {} {Karta dostêpu}
{41601} {} {Elektroniczna karta dostêpu do stacji kontroli zapór.}
{41700} {} {Karta dostêpu ZAX}
{41701} {} {Elektroniczna karta dostêpu najwy¿szego poziomu do terminala awaryjnego ZAX.}
{41800} {} {Karta dostêpu}
{41801} {} {Elektroniczna karta dostêpu Krypty 25. Poœwiadczenie bezpieczeñstwa - zastrze¿one.}
{41900} {} {Karta dostêpu}
{41901} {} {Elektroniczna karta dostêpu z Krypty 25. Poziom dostêpu - najwy¿szy.}
{42000} {} {Karta dostêpu}
{42001} {} {Elektroniczna karta dostêpu Krypty 27.}
{42100} {} {Klucz Aarona}
{42101} {} {Ten klucz nale¿a³ kiedyœ do Aarona, W³adcy Phoenix. Wygl¹da na to, ¿e musi istnieæ do niego jakiœ specjalny zamek.}
{42200} {} {Klucz Shabby}
{42201} {} {Zu¿yty klucz do pokoju w Starym Motelu.}
{42300} {} {Klucze Szakali}
{42301} {} {Ten zestaw brudnych kluczy otwiera drzwi w norach Plemienia Szakali.}
{42400} {} {Napromieniowany klucz}
{42401} {} {Ma³y klucz, który uda³o ci siê znaleŸæ w Quartz. Prawdopodobnie otwiera jakiœ ma³y zamek.}
{42500} {} {Zardzewia³y klucz}
{42501} {} {Ten klucz otwiera magazyn w kopalni uranu we Flagpool.}
{42600} {} {Zêby Króla Kretoszczurów}
{42601} {} {Dolne siekacze wielkiego zmutowanego gryzonia znalezionego w kopalniach Flagpool. Mog¹ s³u¿yæ jako dowód œmierci potwora.}
{42700} {} {Klucz do hangaru}
{42701} {} {Ten klucz otwiera bramy hangaru na plantacjach Villi.}
{42800} {} {Pami¹tki}
{42801} {} {Niebieski kombinezon, komputer w rêkawie i manierka podró¿na. Te rzeczy by³y przekazywane z pokolenia na pokolenie w waszej dynastii i teraz s³usznie nale¿¹ do Ciebie.}
{42900} {} {Czaszka potwora}
{42901} {} {G³owa potwora. Nawet martwy wygl¹da przera¿aj¹co.}
{43000} {} {Klucz do motoru}
{43001} {} {Klucz dostêpu do komputera pok³adowego motocykla. Bez tego bardzo trudno bêdzie w³amaæ siê do systemu bezpieczeñstwa, aby uruchomiæ motor.}
{43100} {} {Naszyjnik}
{43101} {} {Ozdoba na szyjê sk³adaj¹ca siê z kilku nadal nadaj¹cych siê do u¿ytku kul, zwi¹zanych star¹ lin¹. Byc mo¿e poprzedni w³aœciciel nie rozumia³ znaczenia tych przedmiotów.}
{43200} {} {Zarówka halogenowa}
{43201} {} {Zaskakuj¹co dobrze zachowana 65-watowa lampa. Wczeœniej by³y one czêsto u¿ywane w reflektorach samochodowych.}
{43300} {} {Stylowe okulary}
{43301} {} {To para bardzo stylowych lustrzanych okularów. Ju¿ sama ich obecnoœæ dodaje pewnoœci siebie. Efekty: +1 CH bed¹c w rêku.}
{43400} {} {Staro¿ytny relikt}
{43401} {} {Wygl¹da na to, ¿e jest to mechanizm pozytywki. P³ynnym przekrêceniem ma³ej dŸwigni zwijasz sprê¿ynê i s³uchasz dawno zapomnianej melodii.}
{43500} {} {Staro¿ytny relikt}
{43501} {} {Stary zegar atomowy. SpóŸnia piêæ minut do ty³u, ale nadal dzia³a.}
{43600} {} {Staro¿ytny relikt}
{43601} {} {Zamkniêta szklana kula z bia³ymi ziarenkami piasku unosz¹cymi siê w œrodku. Byc mo¿e tak wygl¹da œnieg, o którym mówiono ci jako dziecko i którego nigdy nie dane by³o Ci zobaczyæ.}
{43700} {} {Staro¿ytny relikt}
{43701} {} {Medal of Honor za udzia³ w bitwie o Anchorage, 2077. NajwyraŸniej by³o to wielkie wydarzenie.}
{43800} {} {Staro¿ytny relikt}
{43801} {} {Oryginalny symbol organów œcigania. S¹dz¹c po oznaczeniach, jest bardzo stara.}
{43900} {} {Staro¿ytny relikt}
{43901} {} {Swiêta ksiêga z Sanktuarium Boskiego Bramina. W¹tpliwe jest, aby którekolwiek z plemion rozumia³o jej znaczenie.}
{44000} {} {Staro¿ytny relikt}
{44001} {} {Zdjêcie przedstawia chmurê w kszta³cie grzyba za dymi¹cymi zrujnowanymi domami. Na odwrocie napis: Mexicali, 2077.}
{44100} {} {Staro¿ytny relikt}
{44101} {} {Bardzo stary. Bardzo tajemniczy.}
{44200} {} {Staro¿ytny relikt}
{44201} {} {Zakurzona, ale zaskakuj¹co dobrze zachowana flaga Arizony.}
{44300} {} {Staro¿ytny relikt}
{44301} {} {Holodysk z gr¹ na bardzo szybkie komputery.}
{44400} {} {Mapa Phoenix}
{44401} {} {Mapa miasta i jego okolic. Cenne znalezisko dla pocz¹tkuj¹cego padlino¿ercy.}
{44500} {} {Przedmiot pescadora}
{44501} {} {Na tym przedmiocie jest wygrawerowane imiê rybaka - Ferrino.}
{44600} {} {Karta dostêpu}
{44601} {} {Elektroniczna karta dostêpu do drzwi na platformie naftowej Petro Chico.}
{44700} {} {fragment mapy}
{44701}{}{Czêœæ jakiejœ podrêcznej mapy.}
{44800}{}{Struny do gitary}
{44801}{}{Struny do gitary piêciostrunowej.}
{44900}{}{Miedziana rura}
{44901}{}{Staro¿ytny instrument muzyczny.}
{45000}{}{Cia³o Donovana}
{45001}{}{Widzisz cia³o Donovana. Donovan nie ¿yje.}
{45100}{}{Staro¿ytna Odznaka}
{45101}{}{Odznaka Stra¿y Granicznej. Jest pokryta strasznie grub¹ warstw¹ popio³u i ziemi.}
{45200}{}{Staro¿ytna Odznaka}
{45201}{}{Odznaka Stra¿y Granicznej. B³yszczy dumnie w s³oñcu, zupe³nie jak dawniej za czasów Starego Swiata.}
{45300}{}{Kryszta³ Watts 3000}
{45301}{}{Wysoce precyzyjny sztuczny kryszta³ do wojskowego pistoletu laserowego.}
{45400}{}{Pistolet laserowy}
{45401}{}{Pistolet laserowy Watts 1000, ulepszony model cywilny. Moc zosta³a podniesiona do poziomu modeli wojskowych dziêki bardzo precyzyjej soczewce. Min. si³a: 3.}
{45500}{}{baga¿nik}
{45501}{}{Stary pojemnik przywi¹zany do ramy motoru. Nadaje siê do przechowywania i transportu ma³ych przedmiotów.}
{45600}{}{torba motoru}
{45601}{}{Wytrzyma³e skórzane torby. Specjalnie zrobione do Twojego motocykla.}
{45700}{}{Karta dostêpu Bonita}
{45701}{}{Karta dostêpu z elektrowni Bonita. Poziom dostêpu - ograniczony.}
{45800}{}{Karta dostêpu Bonita}
{45801}{}{Karta dostêpu z elektrowni Bonita. Poziom dostêpu - najwy¿szy.}
{45900}{}{Stolik kawowy}
{45901}{}{Stolik zaœmiecony ró¿nymi œmieciami.}
{46000}{}{Generator impulsów}
{46001}{}{Narzêdzie zaprojektowane specjalnie do awaryjnego wy³¹czania sprzêtu elektrycznego i niczego wiêcej.}
{46100}{}{Podk³adka do nagrywania}
{46101}{}{Notatnik Staruszka Izaaka. Opisuje tutaj ³añcuch dzia³añ maj¹cych na celu naprawienie tamy Bonita.}
{46200}{}{Holodysk Gustavo}
{46201}{}{Señor Gustavo poprosi³, aby ten holodysk zosta³ potajemnie zabrany do burmistrza Starego Miasta.}
{46300}{}{Lampa katodowa}
{46301}{}{Elektroniczna lampa pró¿niowa du¿ej mocy. Wiêkszoœæ tych lamp dawno uleg³a awarii, ale ta nadal dzia³a. Dlatego jest taka cenna.}
{46400}{}{Jednostka steruj¹ca}
{46401}{}{Modu³ ten jest niezbêdny do normalnej pracy linii jednoszynowej. Jednak nie dzia³a i trzeba go naprawiæ.}
{46500}{}{Jednostka steruj¹ca}
{46501}{}{Modu³ ten jest niezbêdny do normalnej pracy linii jednoszynowej. Nale¿y go od³o¿yæ na miejsce.}
{46600}{}{Kody graniczne}
{46601}{}{Zosta³y tu zapisane kody i polecenia umo¿liwiaj¹ce zdalne sterowanie botami granicznymi obszaru San Ysidro drog¹ radiow¹.}
{46700}{}{!Nie uzywaj}
{46701}{}{Oryginalnie byl to Pojemnik Jessie. Uzywany przez silnik w systemie barterowym.}
{46800}{}{Emiter holograficzny}
{46801}{}{Czêœæ do generowania obrazu holograficznego.}
{46900}{}{Chip wodny}
{46901}{}{Uk³ad komputerowy steruj¹cy uzdatnianiem wody. U¿ywany w Kryptach Vault-Tec.}
{47000}{}{P³ytka drukuj¹ca}
{47001}{}{Czêœæ z prasy drukarskiej.}
{47100}{}{Tablica diagnostyczna}
{47101}{}{Komponent autodoktora zapewniaj¹cy szybk¹ i dok³adn¹ analizê danych medycznych.}
{47200}{}{Kontroler paliwa}
{47201}{}{Ten chip steruje rozdzia³em mocy w silniku elektrycznym samochodu. Chipy te jednak szybko sie psuj¹ i dlatego tak trudno je znaleŸæ.}
{47300}{}{Plany Latacza}
{47301}{}{Plany jakiegoœ sprzêtu wojskowego. Arkusze s¹ oznaczone jako „Model eksperymentalny”.}
{47400}{}{Automat z bateriami}
{47401}{}{Automat z bateriami nuklearnymi. Wybór jednak jest niewielki.}
{47500}{}{Dane z Hermosillo}
{47501}{}{Dane wywiadowcze, które zdobyto w forcie armii meksykañskiej. Niektórzy ludzie na pustkowiach s¹ gotowi zap³aciæ za nie ³adne pieni¹dze.}
{47600}{}{Ksi¹¿ka o San Diego}
{47601}{}{Ksiêga wspomnieñ z San Diego wydana tu¿ przed Wielk¹ Wojn¹. Byæ mo¿e bêdziesz jednym z pierwszych czytelników.}
{47700}{}{Automat z lekarstwami}
{47701}{}{Automat z lekami i artyku³ami medycznymi. Wybór jednak jest niewielki.}
{47800}{}{Automat z napojami}
{47801}{}{Automat z ró¿nymi napojami. Wybór jednak jest niewielki.}
{47900}{}{Dozownik oleju silnikowego}
{47901}{}{Automat z rop¹. Zosta³o w nim bardzo ma³o oleju.}
{48000}{}{Bio¿el}
{48001}{}{Szczelny s³ój ze specjalnego szk³a. Na etykiecie widnieje napis „Medical Biogel”.}
{48100}{}{Mikrouk³ady}
{48101}{}{Chipy lotnicze. Dla wiêkszoœci ludzi to bezu¿yteczny œmieci, ale dla niektórych to cenne znalezisko.}
{48200}{}{Kody bezpieczeñstwa Coronado}
{48201}{}{Kody bezpieczeñstwa bazy wojskowej Coronado. U¿ywane przez radio. Rzecz niezbêdna w obecnych realiach.}
{48300}{}{Wzmocniona w³ócznia uderzeniowa}
{48301}{}{Improwizowana broñ, która w kontakcie z ofiar¹ emituje pr¹d elektryczny. Min. si³a: 3.}
{48400}{}{Taser}
{48401}{}{Policyjny paralizator. Pora¿a cel pr¹dem. Min. si³a: 4.}
{48500}{}{Program administratora}
{48501}{}{P³yta zawiera oprogramowanie dla Pana R¹czki. Dziêki niemu robot bêdzie pe³ni³ funkcje administratora hotelu.}
{48600}{}{"G³êbokie gard³o"}
{48601}{}{Klasyczny film ciesz¹cy sie popularnoœci¹. Oczywiœcie, ty tego nie obejrzysz.}
{48700}{}{Robot kuchenny}
{48701}{}{Czêœæ robota kuchennego. W za³¹czeniu znajduje sie notatka: „W³asnoœæ prywatna. W przypadku zagubienia proszê zwróciæ do Edwarda z San Ysidro.”}
{48800}{}{Pocisk haubicy}
{48801}{}{Pocisk do haubicy 75mm. Chocia¿ obudowa jest mocno zardzewia³a, nadal zawiera proch. Wiêc teoretycznie ten pocisk nadal mo¿e zostaæ wystrzelony.}
{48900}{}{Czêœci haubicy}
{48901}{}{Te czêœci mo¿na wykorzystaæ do naprawy jednej z uszkodzonych haubic.}
{49000}{}{Przepustka Koronado}
{49001}{}{Przepustka wojskowa Bazy Marynarki Wojennej Coronado. Kolor niebieski.}
{49100}{}{Przepustka Koronado}
{49101}{}{Przepustka wojskowa Bazy Marynarki Wojennej Coronado. Kolor czerwony.}
{49200} {} {}
{49201} {} {}
{49300} {} {}
{49301} {} {}
{49400} {} {}
{49401} {} {}
{49500} {} {}
{49501} {} {}
{49600} {} {}
{49601} {} {}
{49700} {} {}
{49701} {} {}
{49800} {} {}
{49801} {} {}
{49900} {} {"Viva, Villa!"}
{49901} {} {Stary, patriotyczny magazyn komiksowy. To zabawne, ¿e nawet teraz jego treœæ nie traci na aktualnoœci.}
{50000} {} {}
{50001} {} {}
{50100} {} {}
{50101} {} {}
{50200} {} {}
{50201} {} {}
{50300} {} {}
{50301} {} {}
{50400} {} {}
{50401} {} {}
{50500} {} {}
{50501} {} {}
{50600} {} {}
{50601} {} {}
{50700} {} {}
{50701} {} {}
{50800} {} {}
{50801} {} {}
{50900} {} {}
{50901} {} {}
{51000} {} {}
{51001} {} {}
{51100} {} {}
{51101} {} {}
{51200} {} {}
{51201} {} {}
{51300} {} {}
{51301} {} {}
{51400} {} {}
{51401} {} {}
{51500} {} {}
{51501} {} {}
{51600} {} {Wzmacniacz Pip-Boya}
{51601} {} {Wzmacniacz przeznaczony do szybkiej analizy otoczenia. Zaprojektowany przez skrybów Bractwa Stali, model standardowy.}
{51700}{}{"Pu³apki i inne sztuczki"}
{51701}{}{Popularne eseje weteranów grup sabota¿owych i rozpoznawczych. Autor zdradza metody prowadzenia operacji sabota¿owych, opowiada o pu³apkach i urz¹dzeniach masowego ra¿enia. Pu³apki: +4, Skradanie: +2}
{51800}{}{"Nauka dla wszystkich"}
{51801}{}{Przewodnik po œwiecie wspó³czesnej nauki zawieraj¹cy informacje o ró¿nych dziedzinach naukowych. Nauki œcis³e: +4}
{51900}{}{"Nikola Tesla"}
{51901}{}{Przedwojenny magazyn skoncentrowany wy³¹cznie na broni energetycznej. W przesz³oœci czytelnicy bili siê o nie ja jak ciep³e bu³eczki. Broñ energetyczna: +4}
{52000}{}{"Handel"}
{52001}{}{Przedwojenny tygodnik dla ludzi biznesu. I chocia¿ wydany dawno temu, informacje w nim zawarte nadal s¹ aktualne. Handel: +4, Retoryka: +2}
{52100}{}{"Broñ i kule"}
{52101}{}{Pismo poœwiêcone praktycznemu u¿yciu lekkiej i ciê¿kiej broni palnej, z okazjonalnymi stronniczymi recenzjami. Broñ lekka: +4, Broñ ciê¿ka: +4}
{52200}{}{"Medycyna"}
{52201}{}{Podrêcznik teorii i praktyki opieki medycznej. Pierwsza pomoc: +4, Leczenie: +4}
{52300}{}{"Naprawa"}
{52301}{}{Samouczek dotycz¹cy elektroniki i naprawy. Napis na ok³adce g³osi, ¿e bêdzie w stanie „w ka¿dym wydobyæ m³odego elektryka”. Naprawa: +4}
{52400}{}{"Przetrwanie"}
{52401}{}{Ksi¹¿ka o metodach i sposobach zwiadu. Zawiera bardzo przydatne informacje o ¿yciu poza miastem. Survival: +4}
{52500}{}{"Walka"}
{52501}{}{Przedwojenny ilustrowany samouczek walki wrêcz. Walka wrêcz: +4, Broñ bia³a: +4}
{52600}{}{"Nowoczesne zamki"}
{52601}{}{Ta ksi¹¿ka wyjaœnia, jak otworzyæ ró¿ne zamki. Diagramy i ilustracje w podrêczniku pomog¹ zrozumieæ podstawy nawet niedoœwiadczonym czytelnikom. Otwieranie zamków: +4}
{52700}{}{}
{52701}{}{}
{52800}{}{}
{52801}{}{}
{52900}{}{}
{52901}{}{}