################################################ # #######
#
# OPISY ZADAN W PIP-BOY
# (ka¿da nowa sekcja zaczyna siê od 100 i jej wielokrotnosci)
#
################################################ # #######

# ------------------------------------------------- --------
#Villa
# ------------------------------------------------- --------

{100} {} {Zapytaj o najeŸdŸców w s¹siednim mieœcie}
{101} {} {Uwolnij swoich wspó³plemieñców we Flagpool}
{102} {} {Uwolnij swoich wspó³plemieñców w Tu-San}
{103} {} {PrzyjdŸ na naradê spo³ecznoœci}
{104} {} {ZnajdŸ rodzinne pami¹tki w piwnicach}
{105} {} {Jeden z wieœniaków potrzebuje pomocy medycznej}
{106} {} {Zatrzymaj inwazjê szczurów}
{107} {} {ZnajdŸ i zwróæ zagubione dziecko}
{108} {} {WypêdŸ maruderów z plantacji}
{109} {} {Napraw stacjê pogodow¹}
{110} {} {Eliminacja kultu Phoenix}
{111} {} {ZnajdŸ Chrisa, prawdopodobnie gdzieœ siê ukrywa}
{112} {} {Rada postanowi³a wysadziæ kopalniê we Flagpool}
{113} {} {Rada postanowi³a zniszczyæ fabrykê w Garage City}
{114} {} {Rada uwa¿a, ¿e Villa potrzebuje sojuszników}

# ------------------------------------------------- --------
# Flagstaff
# ------------------------------------------------- --------

{200} {} {ZnajdŸ ludzi z Villi w wiêziennej zagrodzie}
{201} {} {Uwolnij cz³onków plemienia z wiêzienia w jakikolwiek sposób}
{202} {} {Uratuj wspó³plemieñców z pu³apki w kopalni}
{203} {} {Napraw robota wiertniczego}
{204} {} {Wyeliminuj króla szczurów w kopalni}
{205} {} {Ktoœ atakuje patrole w opuszczonym obszarze}
{206} {} {Zanieœ obiad do administratora kopalni}
{207} {} {Najemnik Davis jest winien sto kapsli w barze}
{208} {} {Wyeliminuj niewiernych w imiê Swiêtego Ognia}
{209} {} {Wylecz dziecko z choroby popromiennej}
{210} {} {WypêdŸ najeŸdŸców z farmy Randy'ego}
{211} {} {ZnajdŸ przedmioty osobiste panny Brandley}
{212} {} {Usuñ nadzorcê Knuta ze stanowiska}
{213} {} {SprawdŸ, co siê dzieje w Camp Winon}

# ------------------------------------------------- --------
#Garage City
# ------------------------------------------------- --------

{300} {} {Powstrzymaj padlino¿erców}
{301} {} {Zdob¹dŸ czêœci fabryczne pana Kogana}
{302} {} {WeŸ udzia³ w spotkaniu z karawan¹}
{303} {} {Lucas potrzebuje danych z komputera w gara¿u Kogana}
{304} {} {WeŸ udzia³ w spotkaniu z karawan¹}
{305} {} {WeŸ udzia³ w schwytaniu bramina}
{306} {} {Przywróæ szlak handlowy do San Brahmin}
{307} {} {Ustanów szlak handlowy na ziemie Rangerów}
{308} {} {Zorganizuj dostawê alkoholu z Flagpool}
{309} {} {Zatrzymaj fa³szyw¹ produkcjê kapsli}
{310} {} {ZnajdŸ i oddaj spawarkê}

# ------------------------------------------------- --------
# San Brahmin
# ------------------------------------------------- --------

{400} {} {Pomó¿ wodzowi zawrzeæ sojusz}
{401} {} {Misjonarze oferuj¹ sojusz Plemieniu}
{402} {} {Pomó¿ Rangerowi przepêdziæ misjonarzy}
{403} {} {Zatrzymaj produkcjê tequili w Phoenix}
{404} {} {Usuñ odchody braminów z zagrody}
{405} {} {Odkryj tajemnice Pogrzebanego Miasta}
{406} {} {Oczyœæ oazê z radskorpionów}
{407} {} {Chroñ karawanê w drodze do Phoenix}
{408} {} {}
{409} {} {}

# ------------------------------------------------- --------
# Tu-San
# ------------------------------------------------- --------

{500} {} {ZnajdŸ sposób na wy³¹czenie bariery}
{501} {} {ZnajdŸ swojego ojca w Zakazanej Strefie}
{502} {} {WyprowadŸ ludzi z Villi z Zakazanej Strefy}
{503} {} {Padre prosi o przekonanie Carlosa (a w przypadku niepowodzenia - o wyeliminowanie)}
{504} {} {Blacharze chc¹ dezaktywowaæ Zakazan¹ Strefê}
{505} {} {Dowiedz siê, kto zaatakowa³ karawanê i powstrzymaj to zagro¿enie}
{506} {} {ZnajdŸ zaginionego Blacharza w Casa Grande}
{507} {} {Cody ma konflikt to¿samoœci i prosi o znalezienie swojej rodziny w Casa Grande}
{508} {} {Zdob¹dŸ ogniwo dla przybysza}
{509} {} {}

# ------------------------------------------------- --------
#Puerto Penasco
# ------------------------------------------------- --------

{600} {} {Zabierz holotaœmê Ulysses Granta do Puerto Penasco}
{601} {} {ZnajdŸ zaginiony oddzia³ Bractwa w Inferno}
{602} {} {Paladyn Bell cierpi na chorobê psychiczn¹}
{603} {} {PrzeprowadŸ zwiad na po³udnie}
{604} {} {Wyeliminuj Rangerów}
{605} {} {WeŸ udzia³ w nalotach na obozy bandytów}
{606} {} {Zwiad w San Felipe}
{607} {} {}
{608} {} {}
{609} {} {}

# ------------------------------------------------- --------
#Rangers
# ------------------------------------------------- --------

{700} {} {Napraw zbiornik na wodê w gospodarstwie}
{701} {} {Szpieg potrzebuje szyfru radiowego Rangerów}
{702} {} {Naprawa sprzêtu w elektrowni}
{703} {} {Eskortuj m³odego mechanika z Garage City do s³u¿by w elektrowni}
{704} {} {Rozszerz obszar nadawania stacji radiowej}
{705} {} {Dostarcz raport Rangerowi w San Brahmin}
{706} {} {Eskortuj rodzinê do promu}
{707} {} {ZnajdŸ zaginiony oddzia³ zwiadowczy na pustyni pó³nocnej}
{708} {} {Dowiedz siê, co sta³o siê z mieszkañcami Quartz}
{709} {} {Zbierz dane geograficzne w Quartz}
{710} {} {Dowiedz siê, co sta³o siê z uchodŸcami w Garage City}
{711} {} {Pomó¿ Kadetowi Presley'owi}
{712} {} {Zbadaj przyczynê epidemii w akwedukcie}
{713} {} {ZnajdŸ i zabij legendarnego Radskorpiona}
{714} {} {ZnajdŸ brakuj¹cy sprzêt}
{715} {} {Pomó¿ rebeliantom w Phoenix}
{716} {} {ZnajdŸ zaginionych mieszkañców akweduktu}
{717} {} {Zinfiltruj Puerto Penasco}
{718} {} {}
{719} {} {}

# ------------------------------------------------- --------
#Feniks
# ------------------------------------------------- --------

{800} {} {Zapytaj w Phoenix o niewolników z Villi}
{801} {} {ZnajdŸ swojego wujka Miguela w Phoenix}
{802} {} {Zdob¹dŸ g³owy wodzów Los Panchos}
{803} {} {Zabij legendarnego rewolwerowca Gila McCorda}
{804} {} {Zbadaj niedawne ataki na mnichów}
{805} {} {Zinfiltruj szeregi Rebeliantów}
{806} {} {Pomó¿ George'owi Crookowi w San Brahmin}
{807} {} {Wyeliminuj Georga Crooka}
{808} {} {ZnajdŸ w ruinach agenta Partii Wyzwolenia}
{809} {} {Sabota¿ zlecony przez Partiê Wyzwolenia}
{810} {} {Klient kasyna jest winien du¿¹ iloœæ kapsli}
{811} {} {Zwróæ skradzione listy}
{812} {} {Gang Czerwonych Kardyna³ów ma k³opoty}
{813} {} {Wypadek w elektrowni atomowej}
{814} {} {Zelazny Mike chce sprawiedliwoœci}
{815} {} {Pomó¿ mieszkañcom slumsów w ich trudnym po³o¿eniu}
{816} {} {}
{817} {} {}
{818} {} {}
{819} {} {}

# ------------------------------------------------- --------
# Wioska rybacka (platforma wiertnicza)
# ------------------------------------------------- --------

{900} {} {Zatrzymaj wyciek oleju z platformy wiertniczej}
{901} {} {Ulecz chorych z zatrucia olejem}
{902} {} {Thelma prosi o znalezienie pami¹tek po swoim wujku}
{903} {} {Przynieœ sprzedawcy licznik Geigera}
{904} {} {Ruiz szuka skarbu}
{905} {} {Dorwij stworzenie, które kradnie ryby}
{906} {} {Zbadaj sprawê zabójstwa}

# ------------------------------------------------- --------
#Casa Grande
# ------------------------------------------------- --------

{1000} {} {Steve twierdzi, ¿e ³aŸnia jest jego}
{1001} {} {Sullivan zap³aci za naprawê pompy wodnej}
{1002} {} {W opuszczonym barze by³ ba³agan}
{1003} {} {Rabusie pojawili siê w Casa Grande}
{1004} {} {Uratuj wieœniaka na stacji kolejowej}
{1005} {} {Zniszcz bazê paliwow¹ przy autostradzie}
{1006} {} {Burmistrz p³aci za g³owê przywódcy Niebieskich Tarcz}
{1007} {} {}
{1008} {} {}
{1009} {} {}

# ------------------------------------------------- --------
#Hermosillo
# ------------------------------------------------- --------

{1100} {} {Zwróæ radio na ranczo Domingueza}
{1101} {} {Eskortuj wiêŸnia do Puerto Penasco}

# ------------------------------------------------- --------
# San Felipe (stara latarnia morska)
# ------------------------------------------------- --------

{1200} {} {SprawdŸ plotki o potworach z wraku statku}
{1201} {} {Pozb¹dŸ siê potworów}
{1202} {} {Napraw latarniê morsk¹}
{1203} {} {ZnajdŸ i uratuj Gloriê}

# ------------------------------------------------- --------
#Pieklo
# ------------------------------------------------- --------

{1300} {} {ZnajdŸ ca³¹ dru¿ynê Paladyna Barkleya}
{1301} {} {Levi próbuje stworzyæ mutagen, aby uratowac swoj¹ trzodê}
{1302} {} {Eskortuj Dianê do Casa Nueva}
{1303} {} {}
{1304} {} {}
{1305} {} {}
{1306} {} {}
{1307} {} {}
{1308} {} {}
{1309} {} {}

# ------------------------------------------------- --------
#Casa Nueva
# ------------------------------------------------- --------

{1400} {} {}
{1401} {} {ZnajdŸ zaginionego ch³opa}
{1402} {} {Obserwatorzy próbuj¹ powstrzymaæ epidemiê}
{1403} {} {W betoniarni znikaj¹ ludzie}
{1404} {} {Chipo prosi o uzdrowienie swojego zwierzaka pomimo niezadowolenia wieœniaków}
{1405} {} {Lokalna szko³a potrzebuje wiêcej ksi¹¿ek}
{1406} {} {}
{1407} {} {}
{1408} {} {}
{1409} {} {}

# ------------------------------------------------- --------
#! Wolne miejsce
# ------------------------------------------------- --------

{1500} {} {}

# ------------------------------------------------- --------
#Stary motel
# ------------------------------------------------- --------

{1600}{}{}

#---------------------------------------------------------------- --------------- --------
# !DLC BlaskDnia / San Diego
#---------------------------------------------------------------- --------------- --------

{1700}{}{OdwiedŸ tajemnicze miasto umar³ych}
{1701}{}{ZnajdŸ Kryptê 24}
{1702}{}{Pokonaj robota wojskowego w ruinach Tijuana}
{1703}{}{Zneutralizuj szalonego Gonzo}
{1704}{}{Przywróæ zasilanie miasta}
{1705}{}{Przywróæ transmisjê radiow¹}
{1706}{}{Zabierz holodysk na Stare Miasto}
{1707}{}{Spotkaj karawanê z Hub}
{1708}{}{Skarby wyspy Coronado}
{1709}{}{Przywróæ komunikacjê jednoszynow¹}
{1710}{}{Zorganizuj wystêpy mariachi}
{1711}{}{ZnajdŸ Donovana}
{1712}{}{Zdob¹dŸ chipy od Poszukiwaczy w fabryce}
{1713}{}{Babcia Judy szuka mê¿a Ruperta}
{1714}{}{Praca dla pana DeSanti}
{1715}{}{}
{1716}{}{Umowa na poszukiwanie relikwi}
{1717}{}{Umowa na dostawê alkoholi}
{1718}{}{Umowa na dostawê kawy}
{1719}{}{Umowa na dostawê obiadu}
{1720}{}{Umowa na odnalezienie nowej ksi¹¿ki Mortimera}

#---------------------------------------------------------------- --------------- --------
#! wolne miejsce
#---------------------------------------------------------------- --------------- --------

{1800}{}{}

# ------------------------------------------------- --------
#Swieta Anna
# ------------------------------------------------- --------

{1900} {} {Porozmawiaj z wieœniakami o przyjêciu}
{1901} {} {ZnajdŸ brakuj¹cy wieniec ceremonialny}
{1902} {} {ZnajdŸ i uratuj Luciê}
{1903} {} {Powstrzymaj Hilario}
{1904} {} {Zawrzyj sojusz handlowy z Casa Nueva}

# ------------------------------------------------- --------
#! Wolne miejsce
# ------------------------------------------------- --------

{2000} {} {}

# ------------------------------------------------- --------
#Jackals
# ------------------------------------------------- --------

{2100} {} {Ocal Rangersów}
{2101} {} {Wœciek³a Suka jest gotowa do zawarcia sojuszu z obcymi, aby rozwi¹zaæ problem g³odu}
{2102} {} {Czarny Kie³ zamierza opuœciæ dolinê, aby zaj¹æ siê g³odem}
{2103} {} {Wyeliminuj plemiê Szakali}
{2104} {} {Napadnij nory Szakali z bandytami z Garage City}

# ------------------------------------------------- --------
# Car outta Gas Quests
# ------------------------------------------------- --------

{2200} {} {}

# ------------------------------------------------- --------
#! Wolne miejsce
# ------------------------------------------------- --------

{2300} {} {}

# ------------------------------------------------- --------
# Krypta 27
# ------------------------------------------------- --------

{2400} {} {ZnajdŸ Kryptê 27}
{2401} {} {ZnajdŸ podstawowe informacje na temat Krypty 27}
{2402} {} {Uruchom generator w trybie gotowoœci}
{2403} {} {Uruchom generator rezerwowy i przywróæ wentylacjê}
{2404} {} {Poznaj ocalalego cz³onka ekspedycji}
{2405} {} {Eskortuj Arthura Carringtona w bezpieczne miejsce}

# ------------------------------------------------- --------
# Oboz Bractwa Stali
# ------------------------------------------------- --------

{2500} {} {}

# ------------------------------------------------- --------
# Poszukiwacze (kregoslupy)
# ------------------------------------------------- --------

{2600} {} {Zajmij siê bandyt¹ w wiêzieniu Casa Grande}
{2601} {} {Zawrzyj rozejm miêdzy Niebieskimi Tarczami i Blacharzami}
{2602} {} {Zawrzyj rozejm miêdzy Niebieskimi Tarczami i Casa Grande}
{2603} {} {Zanieœ w¹tpliw¹ paczkê do Gonzaleza w Phoenix}
{2604} {} {Przygotuj Chucka do inicjacji}
{2605} {} {}
{2606} {} {}
{2607} {} {}
{2608} {} {}
{2609} {} {}

# ------------------------------------------------- --------
#Camp Winon
# ------------------------------------------------- --------
{4900} {} {}