#
{0}{}{Preferencje gry}
{1}{}{Ustawienia ekranu}



{50}{}{Ustawienia ekranu}
{51}{}{Ustawienia u¿ytkownika}
{52}{}{Szerokoœæ}
{53}{}{Wysokoœæ}
{54}{}{Gotowe}
{55}{}{Anuluj}
{56}{}{Fallout musi zostaæ ponownie uruchomiony, aby zapisaæ ustawienia.}
{57}{}{Czy chcesz teraz ponownie uruchomiæ Fallouta?}
{58}{}{Prawda}
{59}{}{Fa³sz}
{60}{}{}

{100}{}{Wysoka rozdzielczoœæ}
{101}{}{ROZDZIELCZOŒÆ}
{102}{}{Kolory}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Zmieñ pasek boczny}
{107}{}{Odwrócenie listy}
{108}{}{Tryb okienkowy}
{109}{}{Ustaw przycisk Scroll}
{110}{}{Skalowanie X2}
{111}{}{Odœwie¿anie}

{130}{}{Klawisz Windowsa}
{131}{}{Wybierz}
{132}{}{Nazwa}

{140}{}{Tryb graficzny:}
{141}{}{Podstawowy}
{142}{}{Sfall DirectX 9 Tryb:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}

{150}{}{Panel skalowania}
{151}{}{Nic}
{152}{}{Dop.}
{153}{}{Wyp.}

{154}{}{Filmy}
{155}{}{Splash}
{156}{}{Pomoc}
{157}{}{Œmieræ}
{158}{}{Napisy koñcowe}
{159}{}{Menu g³ówne}


{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX-9 MODE}
{203}{}{Wy³.}
{204}{}{Pe³ny ekran}
{205}{}{Okno}
{206}{}{GPU Blitting}
{207}{}{Te ustawienia nie dzia³aj¹ w podstawowym trybie grafiki.}

{250}{}{Zignoruj PC Scroll Limit}
{253}{}{Wyszukiwanie œcie¿ek}
{254}{}{Normalne}
{255}{}{Maksymalne}
{256}{}{W³¹cz Mg³ê Wojny}
{257}{}{Widocznoœæ Mg³y}
{258}{}{Ciemna}
{259}{}{Jasna}

{300}{}{NACIŒNIJ DOWOLNY KLAWISZ lub ESC, aby anulowaæ.}

{500}{}{Ustawienia patcha w wysokiej rozdzielczoœci}
{501}{}{Ustaw rozdzielczoœæ ekranu, tryb koloru i czêstotliwoœæ odœwie¿ania dla trybu pe³noekranowego.}
{502}{}{Skonfiguruj kolor wyjœciowy trybu pe³noekranowego.}
{503}{}{Ustaw szybkoœæ odœwie¿ania w trybie pe³noekranowym. Ustawienie wartoœci "0" powoduje przywrócenie domyœlnych ustawieñ sterownika.}
{504}{}{Dostosuj szerokoœæ dla trybu pe³noekranowego klikaj¹c pole liczbowe.}
{505}{}{Dostosuj wysokoœæ dla trybu pe³noekranowego klikaj¹c pole liczbowe.}
{506}{}{W³¹cz lub wy³¹cz tryb Okna.}
{507}{}{W trybie Okna, jest to klawisz, który nale¿y wcisn¹æ podczas u¿ywania myszki do przewijania mapy gry i œwiata.}
{508}{}{Naciœnij czerwony przycisk, aby wybraæ inny klawisz lub kliknij pole numeryczne, aby edytowaæ kod klucza wirtualnego systemu Windows.}
{509}{}{Nazwa aktualnie u¿ywanego klawisza.}
{510}{}{W³¹cz skalowanie X2. Minimalna rozdzielczoœæ bêdzie wynosiæ wtedy 1280x960. Tryb Okna wymaga wiêcej miejsca na ramy.}
{511}{}{W³¹cz lub wy³¹cz Mg³a Wojny. Aby uzyskaæ najlepsze rezultaty, nale¿y w³¹czyæ tê funkcjê przed pierwszym u¿yciem mapy.}
{512}{}{Dostosuj poziom jasnoœci oraz widocznoœæ obiektów po klikniêciu mysz¹ "obejrzyj" na pod³o¿e, œciany i sceneriê za Mg³¹.}
{513}{}{Pod³o¿e, œciany i scenaria bêd¹ zawsze widoczne, a "obejrzyj" na myszy bêdzie dzia³aæ normalnie.}
{514}{}{Pod³o¿e, œciany i sceneria bêd¹ przyciemnione i nie wyka¿¹ ¿adnej interakcji z trybem "obejrzyj" myszy, dopóki nie zostan¹ odkryte.}
{515}{}{Po w³¹czeniu przewijanie od postaci gracza jest nieograniczone. Zaleca siê w³¹czenie funkcji Mg³a wojny.}
{516}{}{Zwiêksz liczbê wêz³ów wyszukiwania, aby zwiêkszyæ odleg³oœæ znajdowania œcie¿ki. 20 poziomów w 2000 punktach wêz³a.}
{517}{}{2000 wêz³ów wyszukiwania œcie¿ki (wartoœæ domyœlna). Uwaga: Ka¿dy poziom wymaga dodatkowych 156,25 KB pamiêci.}
{518}{}{40 000 wêz³ów wyszukiwania œcie¿ek. Uwaga: wymaga 3200000 bajtów (3125 KB) pamiêci.}
{519}{}{Dostosuj sposób wyœwietlania niektórych ekranów.}
{520}{}{Rozmiar domyœlny.}
{521}{}{Rozci¹gnij, aby dopasowaæ rozmiar ekranu przy zachowaniu oryginalnego wspó³czynnika proporcji.}
{522}{}{Rozci¹gnij, aby dopasowaæ do ca³ego ekranu. Uwaga: U do³u ekranu zostanie dodatkowa przestrzeñ, jeœli w³¹czone s¹ napisy.}
{523}{}{Kliknij poni¿ej, aby w³¹czyæ opcje paska bocznego interfejsu w grze.}
{524}{}{Zapisz zmiany i WyjdŸ}
{525}{}{WyjdŸ bez Zapisu}
