{100} {} {Widzisz Jana.}
{101} {} {Widzisz rozczochranego Meksykanina z gêst¹, postrzêpion¹ brod¹.}

{110} {} {One istniej¹!}
{111} {} {Mówiê prawdê. Dlaczego mi nie wierzysz?}
{112} {} {Kiedyœ tu przybêd¹.}
{113} {} {Musimy dzia³aæ teraz!}

# Pierwszy dialog
{200} {} {Och, amigo! Jaki wiatr przygna³ ciê na te ziemie?}
{201} {} {Có¿, ja...}
{202} {} {Cicho! Nie mów ani s³owa! Tutejsi nie lubi¹ obcych. Patrz¹ nawet na mnie z no¿em w kieszeni.}
{203} {} {Dlaczego? Czy coœ siê miêdzy wami wydarzy³o?}
{204} {} {(rozgl¹da siê) Potwory!}
{205} {} {Potwory?}
{206} {} {Gigantyczne pijawki! Przera¿aj¹ce, obrzydliwe i okropnie œmierdz¹ce stworzenia. Pojawiaj¹ siê na wybrze¿u, gdzie zbieram skorupiaki. Ale ci g³upcy mnie nie s³uchaja, myœl¹, ¿e zwariowa³em! Ale stary Jan taki nie jest. Nadal nie zwariowa³em!}
{207} {} {Pope³niaj¹ du¿y b³¹d, ignoruj¹c twoje s³owa.}
{208} {} {Wygl¹dasz mi na ob³¹kanego, staruszku.}
{209} {} {Nie zostawiaj mnie samego, amigo. Potrzebujê pomocy!}
{210} {} {OK. Jak myœlisz, gdzie maj¹ swoje legowisko?}
{211} {} {Tam, w pobli¿u wraku szkunera, dalej wzd³u¿ wybrze¿a. Ale b¹dŸ ostro¿ny.}
{212} {} {Rozumiem. Do zobaczenia.}

# Powtarzajacy siê dialog
{220} {} {Ola, amigo.}
{221} {} {Adios, Jan.}

{230} {} {Kto tu rz¹dzi?}
{231} {} {Hector. Nasz stary kapitan.}
{232} {} {Dlaczego nazywasz go kapitanem?}
{233} {} {P³ywaliœmy tutaj szkunerem, a Hector by³ tam kapitanem. Od tego czasu zwyczajem sta³o siê nazywanie go w ten sposób.}
{234} {} {Ciekawa historia. Powiedz mi wiêcej.}
{235} {} {Teraz rozumiem. Do zobaczenia.}
{236} {} {Kim jesteœ?}
{237} {} {Nazywam siê Jan. Mieszkam w pobli¿u i zbieram skorupiaki na wybrze¿u.}
{238} {} {Sk¹d znasz angielski Jan?}
{239} {} {Moja rodzina zawsze mówi³a dwoma jêzykami. Tak by³o od czasów staro¿ytnych.}
{240} {} {Ciekawa historia. Powiedz mi wiêcej.}
{241} {} {Teraz rozumiem. Do zobaczenia.}
{242} {} {Dlaczego Twoi rodacy nie chc¹ Ci pomóc?}
{243} {} {Bo mi nie wierz¹! Myœl¹, ¿e jestem g³upcem i zwariowa³em!}
{244} {} {Nie drzyj siê tak. Chcê tylko dowiedzieæ siê wiêcej o tobie i tej sprawie.}
{245} {} {Niezbyt m¹drze z ich strony. Mo¿e porozmawiamy o tym póŸniej.}
