{100} {} {Widzisz Gloriê.}
{101} {} {Widzisz dziewczynê o meksykañskiej urodzie.}
{102} {} {Uzdrowi³eœ swojego pacjenta.}
{103} {} {¡Madre de Dios! ¿Que pasƒ?}

{110} {} {Ahhhh...}
{111} {} {Dziewczyna jest nieprzytomna. Potrzebuje pilnej pomocy lekarskiej.}
{112} {} {Dziekujê za uratowanie mi ¿ycia. Muszê z³apaæ oddech i dojœæ do siebie. W miêdzyczasie udaj siê do wioski i opowiedz, co siê sta³o.}
{113} {} {Tu eres mi salvador. Le estoy muy reconocido.}
{114} {} {OK, opowiem w osadzie co siê tu sta³o.}
{115} {} {Le estoy muy reconocido.}
{116} {} {Jeszcze raz dziêkujê.}
{117} {} {Le estoy muy reconocido. Habla con Hektor.}
{118} {} {Jeszcze raz dziêkujê. Porozmawiaj z Hektorem o tym, co siê sta³o.}

# Pierwszy dialog
{200} {} {Ahhhh... (niezrozumiale po hiszpañsku)}
{201} {} {Przepraszam, nie rozumiem.}
{202} {} {O czym ty do cholery mówisz?}
{203} {} {Monstruos! ¡Estn en todos lados!}
{204} {} {Uspokój siê, nie jesteœ ju¿ w niebezpieczeñstwie.}
{205} {} {Z twoj¹ g³ow¹ nie wszystko jest w porz¹dku, co?}
{206} {} {(rozgl¹da siê nerwowo)}
{207} {} {Chcesz siê st¹d wydostaæ? Znam wyjœcie. ChodŸ, chodŸ...}
{208} {} {Nie, nie potrzebujê teraz takiego g³oœnego towarzystwa. Zostañ tu!}
{209} {} {No te preocupes. Todo bueno.}
{210} {} {Monstruos! ¡Estn en todos lados! (Potwory! S¹ wszêdzie!)}
{211} {} {Uspokój siê, nie jesteœ ju¿ w niebezpieczeñstwie.}
{212} {} {Chcesz, ¿eby nas znalaz³y? Nie? Wiêc b¹dŸ cicho, g³upia.}
{213} {} {Och, przepraszam, s¹ takie straszne! Chcê iœæ do domu. Wyci¹gniesz mnie st¹d?}
{214} {} {Oczywiœcie, nie mogê cie tu zostawiæ. WyjdŸmy na œwie¿e powietrze...}
{215} {} {Nie, nie potrzebujê teraz takiego g³oœnego towarzystwa. Zostañ tu!}
{216} {} {Estar tan callado como un ratƒn.}
{217} {} {Bêdê cicho jak mysz.}
{218} {} {Zostañ z ty³u...}
{219} {} {}

# Powtarzajacy siê dialog
{220} {} {¡Por favor no me dejes aquš!}
{221} {} {Proszê, nie zostawiaj mnie tutaj!}
{222} {} {Nie mo¿esz tu zostaæ. ChodŸ ze mn¹...}
{223} {} {Usi¹dŸ tutaj i b¹dŸ cicho.}
{224} {} {Wkrótce wyjdziemy z jaskini. Bez obaw.}

{230} {} {Muszê zadaæ ci kilka pytañ.}
{231} {} {¿Qu estas diciendo? No te entiendo.}
{232} {} {No tak, oczywista odpowiedŸ. Lepiej b¹dŸmy cicho.}
{233} {} {Co, teraz?}
{234} {} {Nie, porozmawiamy póŸniej.}
{235} {} {Kim jesteœ?}
{236} {} {Nazywam siê Gloria.}
{237} {} {Sk¹d jesteœ?}
{238} {} {Pochodzê z rybackiej wioski na wybrze¿u. Nazywa siê San Felipe.}
{239} {} {Jak trafi³aœ do jaskini?}
{240} {} {Myœlê, ¿e sz³am wzd³u¿ brzegu morza, kiedy nagle ten potwór wyskoczy³ ze starej ³odzi. Wygl¹da na to, ¿e straci³am przytomnoœæ i obudzi³am siê ju¿ w tej jaskini. Myœlê, ¿e te potwory mnie tu zaci¹gnê³y... Bo¿e, co za koszmar!}
{241} {} {Co wiesz o tych potworach?}
{242} {} {Straszne istoty. A¿ mam gêsi¹ skórkê. Jak natura mog³a stworzyæ takie potwory? Nie, nie, to s¹ monstra z samego piek³a. Nie bez powodu pachn¹ siark¹ i rozk³adem!}
{243} {} {Tak, pachn¹ naprawdê niezdrowo.}
{244} {} {Myœlê, ¿e to paskudne powietrze wydobywa siê z ich skórzanych toreb na ich cia³ach. Mo¿e w ten sposób unosz¹ siê nad ziemi¹? Och, gdyby tak rzuciæ w nie ogniem i zobaczyæ, co siê stanie!}
{245} {} {Dobry pomys³, potê¿ny miotacz ognia dobrze by siê tutaj spisa³.}
{246} {} {Pachnie metanem.}
{247} {} {Wow, znasz takie trudne s³owa? Nie wiem, co to znaczy. Ale myœlê, ¿e u¿ywaj¹ powietrza w skórzanych torbach na swoich cia³ach, aby unosiæ siê w powietrzu. Och, chcia³abym móc rzuciæ w nie ogniem i zobaczyæ, co siê stanie!}
{248} {} {Dok³adnie, przyda³by mi siê miotacz ognia.}
{249} {} {Sk¹d jesteœ, Gloria?}
{250} {} {To wszystko, co mnie interesowa³o.}
{251} {} {Myœlê, ¿e sz³am wzd³u¿ brzegu morza, kiedy nagle ten potwór wyskoczy³ ze starej ³odzi. Wygl¹da na to, ¿e straci³am przytomnoœæ i obudzi³am siê ju¿ w tej jaskini. Myœlê, ¿e te potwory mnie tu zaci¹gnê³y... Bo¿e, widzia³am te¿ inne cia³a! Czy te potwory nadal ¿yj¹? Nie, nie wrócê tam...}
