{100}{}{Widzisz przed sob¹ kupca.}
{101}{}{Widzisz sprzedawcê ryb.}
{102}{}{Schowaj siê za lad¹. Nie s¹dzê, ¿eby te upiory nas tu znalaz³y.}

{200}{}{Witaj, Señor. Jak mogê ci pomóc?}
{1200}{}{Witaj Senora. Jak mogê ci pomóc?}
{201}{}{Nie potrzebujê teraz niczego. Przyjdê innym razem.}
{202}{}{Muszê uzupe³niæ zapasy na podró¿.}
{203}{}{Czy to wszystko? No to bezpiecznej podró¿y.}
{204}{}{Pa.}
{205}{}{Jeszcze raz dziêkujê za licznik Geigera.}
{206}{}{Po po¿arze na platformie rybo³ówstwo tutaj stopniowo wraca do ¿ycia. Dziêki amigo.}

{210}{}{Gdzie mogê kupiæ tutaj baterie do ³odzi?}
{211}{}{Zaden z peskadorów nie sprzeda ci swoich zapasów - sami nie maj¹ doœæ. Najbli¿sze miejsce, z którego otrzymujemy baterie do ³odzi i generatora to Puerto Peñasco. Spróbuj tam kupiæ.}
{212}{}{Dziêkujê.}
{213}{}{S³uchaj, jeœli tam jedziesz, czy mo¿esz wyœwiadczyæ mi przys³ugê?}
{214}{}{Jak¹?}
{215}{}{Od dawna prosi³em rycerzy z Puerto o przys³anie mi nowego licznika Geigera. Ale jeœli chodzi o technologie, s¹ okropnymi sknerami. W czasie, gdy bêdê czekaæ na nowy licznik od nich, wszyscy zd¹¿ymy umrzeæ od promieniowania. Zart. Ale jeœli przyniesiesz mi nowy miernik, wymieniê go na baterie. Lub zap³acê czystymi kapslami.}
{216}{}{Bêdê o tym pamiêtaæ.}
{217}{}{Masz szczêœcie. Mam akurat jeden taki licznik i nie potrzebujê go.}
{218}{}{Mam dla ciebie licznik Geigera.}
{219}{}{Gdzie mogê kupiæ baterie do mojego motoru?}
{220}{}{Nareszcie! Teraz sprawdzê... hmm... wydaje siê dzia³aæ. Co chcesz w zamian? Kapsle czy potrzebn¹ bateriê?}
{221}{}{Bateriê j¹drow¹.}
{222}{}{Kapsle.}
{223}{}{WeŸ to za darmo. To prezent, który sprawi, ¿e œwiat stanie siê czystszy i bezpieczniejszy.}
{224}{}{Masz. W pe³ni na³adowana.}
{225}{}{Dok³adnie to, czego potrzebujê.}
{226}{}{Oto kapsle,}
{227}{}{ sztuk}
{228}{}{Swietnie.}
{229}{}{Och, dziêki, amigo!}
{230}{}{Proszê.}

{240}{}{Hilberto mówi, ¿e by³eœ w Inferno, to prawda?}
{241}{}{Tak, to straszne miejsce. S¹ tam tylko spalone ruiny i... ludzkie KOSCI.}
{242}{}{Wow, mo¿esz rozwin¹æ? Jadê tam z misj¹.}
{243}{}{To przera¿aj¹ce. Nie mów nic wiêcej, nie chcê tego s³yszeæ.}
{244}{}{Naprawdê chcesz wiedzieæ? Szczerze mówi¹c, nie lubiê o tym mówiæ. Ale zrobiê dla ciebie wyj¹tek.}
{245}{}{Wiêc jakie czekaj¹ tam mnie niebezpieczeñstwa?}
{246}{}{Naprawdê chcesz wiedzieæ? Szczerze mówi¹c, nie lubiê o tym mówiæ. Zamierzasz coœ zamówiæ, czy nie?}
{247}{}{Oto 20 kapsli. Chcê us³yszeæ twoj¹ historiê.}
{248}{}{Nie mam teraz kapsli. Mo¿e innym razem.}
{249}{}{Szuka³em tam przydatnych rzeczy. Ruiny te nie zosta³y jeszcze spl¹drowane przez maruderów, jak w Phoenix, wiêc jest tam du¿o starych reliktów. Ale ich zdobycie jest niezwykle niebezpieczne z powodu promieniowania i osuwisk. Po³owê drogi przeszed³em przez podziemne przejœcia. Tam, przy okazji, mo¿esz na chwilê ukryæ siê przed promieniowaniem.}
{250}{}{Kontynuuj.}
{251}{}{Ale najgorsze s¹ demony.}
{252}{}{Demony?}
{253}{}{Dusze zmar³ych w ogniu nuklearnym. Chodz¹cy martwi, którzy stracili rozum i ludzk¹ postaæ. Na szczêœcie rzadko udaj¹ siê na obrze¿a ruin.}
{254}{}{Powiedz mi wiêcej.}
{255}{}{Wielu poszukiwaczy zginê³o z r¹k demonów lub promieniowania. Dlatego powinieneœ byæ ostro¿ny - zaopatrz siê w leki i dobr¹ broñ, jeœli nadal masz ochotê tam pojechaæ.}
{256}{}{Dobrze. Dziêki za wskazówki.}
{257}{}{Nie dam siê tym zastraszyæ.}
{258}{}{Wygl¹da na to, ¿e wiem ju¿ wszystko.}
{259}{}{Rozumiem. OK, zmieñmy temat.}

{260}{}{Hej, co wiesz o skarbie, którego szuka Ruiz?}
{261}{}{Nie zadzieraj z tym typem. To przebieg³y i niebezpieczny cz³owiek. Tak, a ten skarb jest w¹tpliwy. Nikt nawet nie wie, czy naprawdê istnieje.}
{262}{}{Próbowa³eœ go szukaæ?}
{263}{}{Mam tylko jeden fragment mapy skarbów. Ruiz nigdy nie zrezygnuje ze swojej czêœci mapy. Gdzie s¹ inne, nie wiem.}
{264}{}{Mo¿e móg³byœ mi sprzedaæ swój kawa³ek?}
{265}{}{Hmm, z drugiej strony, wci¹¿ jest szansa na znalezienie skarbu. Wiêc sprzedam, ale za bardzo dobr¹ cenê. Powiedzmy... za }
{266}{}{ kapsle.}
{267}{}{Zap³acê. Oto kapsle.}
{268}{}{Ile? Nie staæ mnie. Zachowaj ten papierek dla siebie.}
{269}{}{Nie, to nie wystarczy. Wróæ, kiedy bêdziesz przy kasie. Te¿ chcê zyskaæ na chciwoœci innych.}
{270}{}{Uch, dobrze. Wrócê z kapslami...}
{271}{}{(licz¹c kapsle z podnieceniem) Wygl¹da na to, ¿e dzisiaj koñczy mi siê ca³oroczny zapas szczêœcia! Trudno! Oto moja czêœæ mapy. Powodzenia w znalezieniu skarbu. Bêdziesz go potrzebowaæ.}
{272}{}{Pa.}

{280}{}{Hej, wiesz, co siê sta³o z Johnnym?}
{281}{}{Wszyscy ju¿ wiedz¹. Plotki szybko siê rozesz³y. To straszne. Nigdy nie s¹dzi³em, ¿e w naszej wiosce ktoœ podniesie rêkê na kogoœ.}
{282}{}{Jak myœlisz, kto to móg³ byæ?}
{283}{}{Nie wiem. Johnny by³ ulubieñcem wszystkich. Tylko Ruiz traktowa³ go ch³odno. Ale on nienawidzi wszystkich. Jeszcze jest ten komiczny wujek... chyba nazywa siê Ting-Tan. Myœlê, ¿e Johnny go unika³. Co jest dziwne, poniewa¿ Johnny by³ bardzo szczêœliwy, ¿e jego wujek nied³ugo przyjedzie z Phoenix. A po jego przybyciu ch³opiec wydawa³ siê byæ wycofany.}
{284}{}{Czy on naprawdê jest z Phoenix?}
{285}{}{Tak. Nawet ma swoje papiery i s¹ w porz¹dku. Wszystkie dokumenty zosta³y sporz¹dzone w „Sonora Express”. To prawda, ¿e na naszej pustyni nie jest bezpiecznie. Dlatego karawany z poczt¹ odwiedzaj¹ Casa Nueva, a nie nas, gdy chcemy coœ wys³aæ do Phoenix.}
{286}{}{Casa Nueva i Phoenix? Có¿, dziêki, zapytam tam przy okazji.}
{287}{}{Hej, niczego nie zamówi³eœ!}
{1287}{}{Hej, niczego nie zamówi³aœ!}
{288}{}{Poradzisz sobie.}
{289}{}{Przepraszam, oto 5 kapsli.}