{110} {} {Widzisz cia³o, lepiej je dok³adniej zbadaæ.}
{111} {} {To za trudne do zrobienia podczas walki.}

{200} {} {Widzisz cia³o nastolatka. Le¿y tu od niedawna. Na piasku widaæ œlady walki.}
{201} {} {Biedak. Kto by siê odwa¿y³ zaatakowaæ dziecko?}
{202} {} {Masz pecha, ch³opcze.}
{203} {} {Ten nastolatek zmar³ z powodu uduszenia. Na jego szyi widaæ odciski d³oni i chyba liny.}
{204} {} {Ktoœ musia³ go zabiæ. Musisz o tym poinformowac innych pescadores.}
{205} {} {Zostaw cia³o w spokoju.}
