{110} {} {Ta ³ódŸ jest obecnie przystosowana tylko do p³ywania po dnie morskim. Jej kad³ub wymaga naprawy, a silnik potrzebuje energii.}
{111} {} {Silnik siê nie uruchamia. WskaŸnik informuje, ¿e bateria j¹drowa siê wyczerpa³a.}
{112} {} {LódŸ jest gotowa do wyp³yniêcia. U¿yj swej wiedzy naukowej do nawigacji.}
{113} {} {Naprawi³eœ pêkniêcia i dziury w kad³ubie.}
{114} {} {Bateria na³adowana. Wystarczy na jeden d³u¿szy rejs.}
{115} {} {Bateria jest ju¿ w pe³ni na³adowana.}
{116} {} {Nie masz teraz dok¹d wyruszyæ.}
{117} {} {LódŸ nie wytrzyma takiego ciê¿aru. Usuñ wszystkie niepotrzebne przedmioty z plecaka.}
{118} {} {T¹ ³odzi¹ mo¿esz wróciæ na brzeg. U¿yj metod naukowych do nawigacji.}
{119} {} {Ta ³ódŸ ma doœæ paliwa, aby wróciæ na brzeg.}
