{100}{}{Widzisz Gilberto.}
{101}{}{Widzisz mê¿czyznê z du¿ymi w¹sami. Ma na sobie czapkê kapitana.}
{102}{}{Proszê, pomó¿! Rozpruwacze zaatakowali wioskê!}
{103}{}{Rozpruwacze! Ukryj siê!}
{104}{}{To rozpruwacze! Uciekaj!}
{105}{}{Rozpruwacze zaatakowali wioskê!}
{106}{}{Ratuj siê kto mo¿e! Rozpruwacze s¹ wszêdzie!}
{107}{}{Hej, zejdŸ ze sto³u! To nie jest zabawne.}

{200}{}{Witaj. Nazywam siê Gilberto. Prowadzê ten przybytek. Co ciê sprowadza do naszego portu?}
{201}{}{Czeœæ Gilberto. Tylko przechodzê i potrzebujê miejsca do spania.}
{202}{}{Przechodzisz? Dziwna sprawa. Powiesz mi póŸniej. W miêdzyczasie mo¿esz zostaæ w wiosce, ale uwa¿aj - ostatnio mamy ciê¿ki okres.}
{203}{}{W takim razie rozejrzê siê, jeœli nie masz nic przeciwko. Do zobaczenia.}
{204}{}{Co siê sta³o?}
{205}{}{Co tu siê dzieje?}
{206}{}{Wykonujê misjê dla Bractwa Stali. To nie dotyczy Ciebie.}
{207}{}{Wiêc witaj! Ale b¹dŸ ostro¿ny – ostatnio mieliœmy ciê¿ki okres.}
{208}{}{Rozejrzê siê, jeœli nie masz nic przeciwko. Do zobaczenia.}
{209}{}{Przed czym mnie ostrzega³eœ?}

{210}{}{Co mogê dla ciebie zrobiæ?}
{211}{}{Dobrze ciê widzieæ.}
{212}{}{Jak d³ugo zamierzasz siê tu krêciæ?}
{213}{}{Do zobaczenia póŸniej, Gilberto.}

{220}{}{Mo¿esz mi opowiedzieæ o tym miejscu?}
{221}{}{To wioska rybacka. Zajêliœmy stare molo i naprawiliœmy kilka ³odzi na ryby. To wszystko.}
{222}{}{Tak po prostu przyszliœcie i naprawiliœcie to wszystko? A¿ trudno uwierzyæ, ¿e grupa rybaków rozumie stare technologie.}
{223}{}{Rozumiem.}
{224}{}{Có¿, niezupe³nie. Patronuje nam zakon znajduj¹cy siê w Puerto Peñasco. W zamian za owoce morza zapewnia nam wszystko, czego potrzebujemy.}
{225}{}{Czy mo¿esz mi powiedzieæ wiêcej o platformie?}
{226}{}{Jest to struktura stworzona przez cz³owieka na œrodku morza. I stoi tam od niepamiêtnych czasów.}
{227}{}{Po co zosta³a zbudowana?}
{228}{}{Wygl¹da na to, ¿e wydobywali na niej ropê z dna morskiego. Ale nie wiem, do czego jest to potrzebne. Chocia¿ pali siê ca³kiem nieŸle.}
{229}{}{Rozumiem. Tylko to mnie interesowa³o.}
{230}{}{Jak mogê siê tam dostaæ?}
{231}{}{Oczywiœcie ³odzi¹. Zapytaj peskadores na molo.}
{232}{}{Gdzie jest Puerto Peñasco?}
{233}{}{Jakieœ 50 mil na po³udnie. IdŸ wzd³u¿ brzegu, nie przegapisz.}

{250}{}{Mamy tu katastrofê ekologiczn¹. Jakby samo morze karze rybaków i ch³opów za b³êdy naszych przodków!}
{251}{}{O czym ty mówisz?}
{252}{}{Uwa¿aj na morze. Widzisz platformê na horyzoncie? Wydaje siê, ¿e czarne t³uste œmieci ³¹cz¹ siê z ni¹. W ogóle nie pachn¹ zdrowo, a ¿ycie morskie umiera od nich w zastraszaj¹cym tempie. Zdarza³o siê to ju¿ wczeœniej, ale ostatnio sta³o siê to nie do zniesienia.}
{253}{}{Czy serio jest tak Ÿle?}
{254}{}{Na pocz¹tku nawet cieszyliœmy siê, ¿e wybrze¿e jest pe³ne martwych ryb - wystarczy³o przyjœæ i wzi¹æ sobie coœ do jedzenia. Ale okaza³o siê, ¿e ka¿de morskie stworzenie by³o zatrute. Niektórzy z naszych ludzi wci¹¿ cierpi¹ z powodu trucizny. I nie jestem pewien, czy kiedykolwiek wyzdrowiej¹.}
{255}{}{Co to za trucizna?}
{256}{}{Wydaje mi siê, ¿e jest to coœ, co kiedyœ nazywano „rop¹” i by³o wydobywane z dna morza. Ale nie wiem, co to jest. Tak czy inaczej, wyciek musi zostaæ zatrzymany. Zap³acimy 1000 kapsli œmia³kowi, który odwa¿y siê wejœæ na platformê i to zrobiæ.}
{257}{}{Wiêc w czym problem?}
{258}{}{Od d³u¿szego czasu unikamy platformy. Dziwne zwierzêta urz¹dzi³y tam swoje gniazdo i nie pozwalaj¹ nikomu siê zbli¿yæ. Kilku rybaków próbowa³o ju¿ tam przebiæ siê si³¹. Niektórzy wrócili, inni zginêli. Jeœli nie powstrzymamy zanieczyszczania morza, nie bêdziemy mieli wkrótce nic do jedzenia.}
{259}{}{Pomyœlê o twojej ofercie. Ale potrzebujê ³odzi.}
{260}{}{Zwariowa³eœ! Nie umiem nawet p³ywaæ. Mam nadziejê, ¿e znajdziesz kogoœ do tego zadania.}
{261}{}{Dziêkujê. Przynosisz mi nadziejê. Jeœli chodzi o ³ódŸ, porozmawiaj z peskadores na molo.}
{262}{}{OK.}
{263}{}{A co z Bractwem Stali? Dlaczego nie poprosiæ ich o pomoc?}
{264}{}{Bractwo? Ha! Wol¹ ju¿ straciæ cokolwiek innego ni¿ trochê starej technologii. Myœlê, ¿e maj¹ nadziejê na naprawienie tej platformy. Ale dopóki nie rozwi¹¿¹ problemów na wschodzie, nie bêd¹ mieli doœæ si³ ¿eby j¹ zaj¹æ. Oznacza to, ¿e na ich pomoc bêdziemy musieli d³ugo czekaæ.}
{265}{}{Rozumiem.}

{270}{}{Wszyscy pacjenci wrócili do zdrowia. Trucizna ju¿ ich nie drêczy.}
{271}{}{W imieniu ca³ej wioski, dziêkujê!}
{272}{}{Proszê bardzo.}
{273}{}{Nie myœlisz chyba, ¿e zrobi³em to za darmo, prawda?}
{274}{}{Czy omawialiœmy nagrodê? Jednak na pewno wyda³eœ na jakieœ lekarstwa. Masz, weŸ 40 kapsli za ka¿dego pacjenta. Dziêki raz jeszcze.}
{1274}{}{Czy omawialiœmy nagrodê? Jednak na pewno wyda³aœ na jakieœ lekarstwa. Masz, weŸ 40 kapsli za ka¿dego pacjenta. Dziêki raz jeszcze.}
{275}{}{Có¿, to co innego.}

{280}{}{Tak! Zrobi³eœ to! Ca³a wioska obserwowa³a ciê z brzegu. Teraz morze bêdzie dla nas bardziej mi³osierne. Dziêki amigo. Jesteœmy Ci d³u¿nikami na zawsze. Oto 1000 kapsli. Obiecaliœmy tê nagrodê temu, który poradzi sobie z naszym problemem. Jest teraz twoja.}
{281}{}{Zachowaj kasê. Zrobi³em to nie dla kapsli, ale dla zwyk³ych ludzi w tarapatach. Tak mnie nauczono w Villi.}
{282}{}{Jesteœ naprawdê niesamowit¹ osob¹.}
{283}{}{Zegnaj, Gilberto. Muszê ju¿ iœæ.}
{284}{}{Có¿, skoro nalegasz, bêdê musia³ wzi¹æ te kapsle.}
{285}{}{Wpadnij do nas, jeœli bêdziesz w pobli¿u. Zawsze jesteœ tu mile widziany.}
{286}{}{Zegnaj, Gilberto. Muszê ju¿ iœæ.}

{290}{}{S³uchaj, przybywasz z Puerto, prawda? Wiemy, ¿e dosz³o tam do wybuchu, a potem komunikacja zosta³a przerwana.}
{291}{}{Zakon poszed³ na dno, by nakarmiæ szeœciook¹ rybê.}
{292}{}{Rozumiem... Nie lubisz ich, prawda? Szczerze mówi¹c, te¿ nie byliœmy skorzy do rzucania im siê na szyje. Ale pomogli nam w zamian za ryby. Bez nich, wiesz, bêdzie ciê¿ko. Có¿, przez jakiœ czas ¿yliœmy dobrze, teraz wrócimy do przetrwania.}
{293}{}{Wolnoœæ jest mi dro¿sza ni¿ ¿ycie pod czyimœ uciskiem. Mam nadziejê, ¿e teraz to zrozumiesz. Zyczê spokoju.}
{294}{}{Nie pomyœla³em o tym. Przykro mi, ¿e tak siê sta³o.}
{1294}{}{Nie pomyœla³am o tym. Przykro mi, ¿e tak siê sta³o.}
{295}{}{Ja? Nie, nie by³em tam i nic nie wiem o wybuchu.}
{1295}{}{Ja? Nie, nie by³am tam i nic nie wiem o wybuchu.}
{296}{}{Naprawdê? Dobra, nie bêdê pyta³, jak uda³o ci siê tu dotrzeæ, omijaj¹c jedyn¹ po drodze osadê. Chcê tylko powiedzieæ, ¿e jeœli nie bêdzie ju¿ Bractwa, bêdzie nam tu ciê¿ko. Pomogli nam w zamian za ryby.}
{297}{}{Myœlê, ¿e teraz poczujesz piêkno wolnoœci. Spodoba Ci siê.}
{298}{}{Przykro mi, ¿e tak siê sta³o.}
{299}{}{}

{300}{}{Idê do Inferno w imieniu Bractwa. Co wiesz o tym miejscu?}
{301}{}{Z³e miejsce. Dlatego nazywa siê Inferno.}
{302}{}{By³eœ tam?}
{303}{}{Sam tam nie by³em. Ale niektórzy œmia³kowie wyruszyli na poszukiwanie przydatnych rzeczy. Bractwo Stali sowicie p³aci za przedwojenne relikwie. Ale ¿ycie jest cenniejsze, wiesz. Jedynym, który tam by³ i wróci³, jest barman, powinien byæ teraz w klubie. Porozmawiaj z nim.}
{304}{}{Porozmawiam z nim, kiedy z tob¹ skoñczê.}
{305}{}{Dobra, dziêki.}

{310}{}{Bractwo Stali mówi o osadzie po drugiej stronie. Co o tym wiesz?}
{311}{}{Nie p³ywamy tak daleko. Ale mo¿e to byæ prawda. Niektórzy widzieli œwiat³a po drugiej stronie przez lornetkê. Jeœli faktycznie mieszkaj¹ tam ludzie, musz¹ cierpieæ z powodu samotnoœci.}
{312}{}{Wygl¹da na to, ¿e bêdê musia³ sam tam pojechaæ, ¿eby siê czegoœ dowiedzieæ.}
{1312}{}{Wygl¹da na to, ¿e bêdê musia³a sama tam pojechaæ, ¿eby siê czegoœ dowiedzieæ.}

{320}{}{Oprócz platformy, co jeszcze mo¿na tu robiæ?}
{321}{}{Có¿, ktoœ kradnie skrzynki na ryby i sieci wzd³u¿ brzegu. Myœlê, ¿e to jakaœ bestia z pustkowi. Ale jak dot¹d nie uda³o nam siê jej z³apaæ. Jeœli dowiesz siê, kto to robi, zap³acê 50 kapsli.}
{322}{}{Zgoda. Znajdê tego z³odzieja.}
{323}{}{To za ma³o. Sam poszukaj tego mi³oœnika ryb.}
{324}{}{Wiem, kto pustoszy³ twoje sieci.}
{325}{}{Naprawdê? Kto?}
{326}{}{To by³ upiór. W dzieñ ukrywa³ siê w cieniu latarni morskiej, a noc¹ chodzi³ na pla¿e w poszukiwaniu ryb. Teraz jest bardziej martwy ni¿ ¿ywy.}
{327}{}{Czy to by³ rozpruwacz z Inferno? O, Maryjo, tylko nie to!}
{328}{}{Inferno? Co to jest?}
{329}{}{Spalone ruiny na pó³nocnym zachodzie. Kto tam by³, opowiada o okolicznych mieszkañcach, okaleczonych przez promieniowanie nie do poznania. To miejsce zamienia ludzi w potwory i odbiera im zdrowie psychiczne. Wystrzegamy siê Inferno. Ale Rozpruwacze dot¹d nigdy tu nie zagl¹da³y. Prawdopodobnie nie lubi¹ œwie¿ego morskiego powietrza.}
{330}{}{Jednak ten jakoœ siê tu dosta³.}
{331}{}{Coœ musia³o sprawiæ, ¿e opuœci³ swoje rodzinne ruiny. Mam nadziejê, ¿e inne nie pójd¹ w jego œlady. A tak, oto twoje 50 kapsli. Dziêkujê.}
{332}{}{Powodzenia Gilberto.}
{333}{}{Inferno? Tak, najprawdopodobniej stamt¹d pochodzi³.}
{334}{}{Masz jakieœ drobne prace?}
{335}{}{To by³ upiór. W dzieñ ukrywa³ siê w cieniu latarni morskiej, a noc¹ chodzi³ na pla¿e w poszukiwaniu ryb. Uda³o mi siê wypêdziæ go z Czarnej Laguny.}
{336}{}{Coœ musia³o spowodowaæ, ¿e opuœci³ swoje rodzinne ruiny. Mam nadziejê, ¿e inne nie pójd¹ w jego œlady. Ale jak¹ mam pewnoœæ ¿e to nie jest tylko mistyfikacja? Nie jestem gotów zap³aciæ 50 kapsli za puste s³owa, przepraszam. Oto 10 kapsli, ¿eby nikt siê nie obrazi³.}
{337}{}{Rozumiem. Dziêki za 10 kapsli.}
{338}{}{Szumowino, zap³acisz za swoje oszustwo!}

{340}{}{Co nowego w wiosce?}
{341}{}{Z³a wiadomoœæ. Bractwa Stali nie ma ju¿ z nami. Coœ eksplodowa³o na ich statku i teraz jesteœmy zdani na siebie. Nie wiem, jak sobie bez nich poradzimy z ca³¹ t¹ star¹ technologi¹.}
{342}{}{Rozumiem. Coœ jeszcze?}
{343}{}{Mamy problem z platform¹ wiertnicz¹. Wielki problem. I nikomu jeszcze nie uda³o siê go rozwi¹zaæ.}
{344}{}{Sprawy siê poprawiaj¹! Platforma wiertnicza nie zanieczyszcza ju¿ wody. Myœlê, ¿e za kilka tygodni wody morskie znów zachwyc¹ nas œwie¿ymi rybami.}
{345}{}{Na morzu jest znacznie lepiej. }
{346}{}{Jose ma obsesjê na punkcie znalezienia skarbu, który nie istnieje. Hehe. Nie wpadnij w jego pu³apkê, kolego.}
{347}{}{Jose zagin¹³. I nikt nie chce go szukaæ.}
{348}{}{Wygl¹da na to, ¿e José w koñcu znalaz³ skarb, którego tyle szuka³. Kto by pomyœla³, ¿e skarb naprawdê istnieje?}
{349}{}{Czasami morze pokazuje nam dziwne rzeczy. Albo z wody wy³oni siê potwór, albo drugi brzeg zostanie oœwietlony œwiat³em. Ale my zwykle nie p³ywamy tak daleko. Nie ma tam co robiæ.}
{350}{}{Okazuje siê, ¿e po drugiej stronie by³a ca³a osada, a my nawet o tym nie wiedzieliœmy! Chocia¿ ch³opaki tam nie wygl¹daj¹ za dobrze.}
{351}{}{Niektórzy widzieli dziwny zielonkawy blask od strony zniszczonej latarni. Ale przecie¿ jest zniszczona. To sk¹d pochodzi to œwiat³o?}
{352}{}{Po tym, jak znalezliœmy ghula w pobli¿u latarni, ludzie zaczêli siê baæ chodziæ w tê stronê. Co jeœli inne trupy przybêd¹ tu z Inferno?}
{353}{}{Nie ma wiêcej historii. Nasze miasteczko jest ma³e i nudne.}
{354}{}{Rozumiem. Zmieñmy wiêc temat.}
{355}{}{Rozumiem. Wiêc b¹dŸ szczêœliwy.}
{356}{}{Jose by³ ostatnio doœæ wredny. Nie wiem, co siê sta³o.}

{360}{}{Z³a wiadomoœæ. Ktoœ udusi³ nastolatka w latarni.}
{361}{}{To BARDZO z³a wiadomoœæ! ChodŸmy tam natychmiast...}
{362}{}{OK.}
{363}{}{Hej, po prostu zgódŸmy siê, ¿e nie jestem w to zamieszany. Czy to jasne?}
{364}{}{Bo¿e, biedny Johnny! Kto móg³ to zrobiæ?}
{365}{}{Opowiedz mi o Johnnym.}
{366}{}{Przeprowadzi³ siê tu z rodzicami trzy lata temu. Rodzice zginêli na morzu, gdy ich ³ódŸ siê wywróci³a. Ale Johnny siê nie podda³. By³ takim dobrym ch³opcem! Pracowa³ niestrudzenie, aby siê utrzymaæ.}
{367}{}{Czy mia³ jakichœ krewnych?}
{368}{}{Tylko wujka Ting. Niedawno przeniós³ siê na zaproszenie, które Johnny wys³a³ do Phoenix po œmierci jego rodziców. Jest trochê dziwny. Czêsto spêdza czas na brzegu, próbuj¹c z³owiæ ryby, choæ p³ywaj¹ tu tylko œmieci. Nie wiem, jak mu powiedzieæ, co siê sta³o. Tak blisko by³o, aby krewni ponownie siê zjednoczyli, ale los ponownie ich rozwiód³. To takie smutne.}
{369}{}{Masz pomys³, dlaczego móg³ zostaæ zabity?}
{370}{}{Có¿, Johnny nie mia³ wrogów. I nie by³o sensu go okradaæ.}
{371}{}{A co z kawa³kiem liny, którym go uduszono?}
{372}{}{Hmm, to dok³adnie ta sama lina, której Jose u¿ywa w swoim fachu. Ale ten kawa³ek wygl¹da ca³kiem œwie¿o, jakby w³aœnie wyszed³ z magazynu.}
{373}{}{Có¿, to wymaga dok³adnego dochodzenia. Nie rzucaj jeszcze oskar¿eñ, aby nie wystraszyæ winowajcy.}
{374}{}{Chcê z tob¹ porozmawiaæ o zabójstwie Johnny'ego.}
{375}{}{Biedny Johnny! Czy uda³o Ci siê znalezæ zabójcê?}
{376}{}{Nie mam jeszcze nowych tropów. Do zobaczenia póŸniej.}
{377}{}{Gdzie by³eœ w momencie morderstwa?}
{378}{}{Spa³em w moim klubie!}
{379}{}{Opowiedz mi o nim.}
{380}{}{Rozmawia³em z wujkiem Johnnego. Mówi, ¿e tylko José ma tak¹ linê.}
{381}{}{To jeszcze niczego nie dowodzi. Chocia¿ José jest zawsze z³y, nadal nie mia³ motywu do zabicia ch³opca. Spróbuj jakoœ z nim porozmawiaæ.}
{382}{}{OK.}
{383}{}{Z notatek Jose René Ruiza wynika, ¿e Tin-Tan by³ ostatni¹ osob¹, która kupi³a od niego linê.}
{384}{}{To jeszcze niczego nie dowodzi. Tin-Tan jest dziwny, ale wci¹¿ jest wujem Johnny'ego. Nie mia³ motywu do zabicia ch³opca. Spróbuj z nim te¿ porozmawiaæ.}
{385}{}{OK.}
{386}{}{Mo¿e to byæ José René Ruiz. Ma tak¹ sam¹ linê. Albo Tin-tan. Kupi³ j¹ w niedawnej przesz³oœci.}
{387}{}{Có¿, to jeszcze niczego nie dowodzi. W koñcu oboje nie maj¹ motywu. Ale to ju¿ jest coœ. Myœlê, ¿e warto popytaæ w klubie. Mo¿e ktoœ wie coœ o ich zwi¹zku z Johnnym?}
{388}{}{OK.}
{389}{}{Prawdziwym zabójc¹ jest Tin-Tan.}
{390}{}{Pamietam nasz¹ rozmowê. Ale jaki mia³ ku temu powód?}
{391}{}{Szczerze mówi¹c, nie wiem, jaki by³ jego motyw. Powinienem chyba jeszcze raz o tym pomyœleæ.}
{392}{}{Nie jest tym, za kogo siê podaje. Prawdziwy wujek Johnny'ego zmar³ podczas podró¿y, a on przyw³aszczy³ sobie jego dokumenty. Jest zwyk³ym rabusiem.}
{393}{}{Wiêc dlatego zachowywa³ siê jak idiota! Udawa³ g³upca, aby nikt nie rozpozna³ w nim niebezpiecznej osoby. Chytry sukinsyn!}
{394}{}{Dosta³ ju¿ to, na co zas³u¿y³, gdy zdecydowa³ siê mnie zaatakowaæ.}
{395}{}{Wow! Tak, masz nerwy ze stali. Dziêki za pomoc. Nie potrzebujemy tu ¿adnych œmieci. Zycie bez nich i tak jest wystarczaj¹co trudne.}
{396}{}{Mam nadziejê, ¿e teraz czujesz siê lepiej. Powodzenia.}
{397}{}{To nie jest najbardziej brutalna rzecz, jak¹ kiedykolwiek widzia³eœ, kapitanie. Daj spokój.}
{398}{}{To prawda. Musisz go jak najszybciej schwytaæ i postawiæ przed wymiarem sprawiedliwoœci.}
{399}{}{Dziêkujê za pomoc. Nie potrzebujemy tu ¿adnych œmieci. Zycie bez nich i tak jest wystarczaj¹co trudne.}
