{100} {} {Widzisz komputer bezpieczeñstwa.}
{101} {} {Widzisz komputer z dostêpem do systemu bezpieczeñstwa.}

#Dialog
{200} {} {Otrzymano dostêp do systemu bezpieczeñstwa. WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Dalej.}
{204} {} {Wróæ do menu g³ównego.}
{205} {} {Anuluj.}

{210} {} {Dezaktywuj wie¿yczki stra¿nicze.}
{211} {} {Wy³¹czenie wie¿yczek zagra¿a bezpieczeñstwu platformy wiertniczej. Czy na pewno chcesz wy³aczyæ wie¿yczki stra¿nicze?}
{212} {} {Tak. Wy³¹cz te przeklête wie¿yczki!}
{213} {} {Gotowe. Wie¿e stra¿nicze s¹ wy³¹czone.}
{214} {} {Aktywuj wie¿yczki stra¿nicze.}
{215} {} {Gotowe. Wie¿e stra¿nicze s¹ aktywowane.}

{220} {} {Dodaj now¹ to¿samoœæ do bazy danych.}
{221} {} {Proszê wype³niæ formularz przyjêcia.}
{222} {} {Imiê:}
{223} {} {. Wiek:}
{224} {} {. Miejsce urodzenia: Villa w Arizonie. Dostêp: pe³ny.}
{225} {} {Gotowe. Do bazy danych zosta³a dodana nowa osoba.}

