{100} {} {Widzisz komputer.}
{101} {} {Widzisz komputer z dostêpem do wspó³dzielonej sieci.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Dalej.}
{204} {} {Wróæ do menu g³ównego.}

{210} {} {23 paŸdziernika 2077 12:00}
{211} {} {Platforma do Operatora. Odbiór? (cisza) Powtarzam. Platforma do Operatora. Odbiór?}
{212} {} {23 paŸdziernika 2077 12:10}
{213} {} {Tu platforma! Wzywam Operatora. Czy mnie s³yszysz? (cisza) Co tam siê sta³o...}
{214} {} {23 paŸdziernika 2077 13:00}
{215} {} {Tu platforma. Nie mamy po³¹czenia z brzegiem. Jeœli ktoœ mnie s³yszy, daj mi sygna³.}
{216} {} {23 paŸdziernika 2077 21:00}
{217} {} {Nadal brak komunikacji z brzegiem. Sprawdziliœmy sprzêt radiowy, nie znaleziono ¿adnych usterek. Dlaczego nie ma po³¹czenia? Dlaczego stra¿ przybrze¿na milczy? Jeœli ktoœ mnie s³yszy, daj mi jakiœ znak!}
{218} {} {24 paŸdziernika 2077 12:00}
{219} {} {Przejœcie na czêstotliwoœci alarmowe. Czy ktoœ mnie s³yszy? Halo! Co tam siê dzieje? Nasz technolog mówi, ¿e przedwczoraj widaæ by³o b³ysk z Mexicali. Podejrzewamy, ¿e móg³ to byæ chiñski sabota¿ elektrowni. Proszê o pomoc stra¿ przybrze¿n¹! Niech ktoœ mi odpowie!}
{220} {} {30 paŸdziernika 2077 12:00}
{221} {} {Nie mamy kontaktu od tygodnia. Platforma dzia³a normalnie, pracownicy te¿ maj¹ siê dobrze. Ale nie rozumiemy, co dzieje siê na brzegu. Administracja nie kontaktuje siê z nami, cywilne stacje radiowe milcz¹. Napotykaliœmy wczeœniej problemy z komunikacj¹, ale ca³y tydzieñ ca³kowitej ciszy to za du¿o. Nie mo¿emy jeszcze opuœciæ platformy, aby nie naruszyæ umowy o pracê. Mamy nadziejê, ¿e sytuacja zostanie rozwi¹zana w najbli¿szej przysz³oœci.}
{222} {} {6 listopada 2077 08:02}
{223} {} {Dzisiaj zgodnie z harmonogramem musimy za³atwiæ dostawê artyku³ów spo¿ywczych i drug¹ zmianê. Gdzie oni do cholery s¹? Jeœli nikt siê nie skontaktuje, bêdziemy zmuszeni opuœciæ platformê.}
{224} {} {20 listopada 2077 5:48 rano}
{225} {} {Uwaga! Do ka¿dego, kto mnie s³yszy! Opuszczamy stacjê w jednej ³odzi ratunkowej. Na stacji pozostaje jedna osoba. Wszystkich, którzy mnie s³ysz¹, proszê o przybycie do punktu ewakuacji.}
{226} {} {21 listopada 2077 12:33}
{227} {} {Tu platforma! Kto mówi?! - To my, kolego. I mamy bardzo z³e wieœci... Mexicali jest zniszczone przez eksplozjê nuklearn¹... - Co... O mój Bo¿e! - ...I wygl¹da na to, ¿e podczas podró¿y z³apaliœmy cholernie du¿o promieniowania. Tylko mi uda³o siê dotrzeæ do brzegu, by przekazaæ ci tê wiadomoœæ... Proszê... Nie rób tam nic g³upiego... Oszczêdzaj jedzenie i wodê, nie zwrócê ³odzi. Zegnaj, amigo. Mi³o by³o z tob¹ pracowaæ...}
{228} {} {29 listopada 2077 15:00}
{229} {} {Mówiê... Ale kogo to obchodzi, prawda? Ta stacja nie jest ju¿ nikomu potrzebna. Jak ja. Jestem tu sam i nigdzie nie mogê iœæ. Kiedy stacja zosta³a zautomatyzowana, ci sk¹pcy z administracji zostawili tylko jedn¹ ³ódŸ, aby zrobiæ miejsce na nowy sprzêt. LódŸ stoi teraz gdzieœ na brzegu. Z trudem bêdê móg³ tam dop³yn¹æ samodzielnie. Czy kiedykolwiek nadejdzie pomoc? Nie wiem. Mam doœæ jedzenia i wody na miesi¹c, nie wiêcej. W miêdzyczasie upewniê siê, ¿e nie bêdzie tu ¿adnej katastrofy. Jednak wybrze¿e Corteza sta³o siê ju¿ stref¹ ekologicznej katastrofy, nawet bez naszej stacji. To wszystko z powodu ludzkiej chciwoœci...}
{230} {} {25 grudnia 2077 23:14}
{231} {} {Hik, hej wy na pla¿y! Prawdopodobnie ju¿ œwiêtujecie Bo¿e Narodzenie, co? * Hik! * W³aœnie przypomnia³em sobie o jednej butelce, któr¹ mia³ w zanadrzu jeden z pracowników. * Hik! * Chcê siê przywitaæ ze wszystkimi. Zartowali, prawda? Nie by³o wojny, prawda? A Mexicali jest ca³e, prawda? Wkrótce do³¹czê do was, za³o¿ê tylko kamizelkê ratunkow¹... wiêc... czekajcie na mnie dzieciaki! Tatuœ nied³ugo wróci do domu!}