{100} {} {Widzisz komputer.}
{101} {} {Widzisz komputer z dostêpem do wspo³dzielonej sieci.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Dalej.}
{204} {} {Wróæ do menu g³ównego.}

{210} {} {Wiadomoœæ ogólna.}
{211} {} {Uwaga dla wszystkich pracowników! Kierownictwo firmy zdecydowa³o siê na pe³n¹ automatyzacjê stacji. Na platformie pozostanie tylko kilka osób do sterowania systemami, reszta pracowników zostanie zwolniona. Jest to konieczne, aby poprawiæ wydajnoœæ operacyjn¹, obni¿yæ koszty finansowe i zwiêkszyæ ochronê przed programami typu spyware.}
{212} {} {Kierownictwo przeprasza za utratê pracy i zap³aci odszkodowanie zgodnie z umow¹ o pracê. Proces zastêpowania ludzi robotami bêdzie etapowy i potrwa trzy miesi¹ce.}
{213} {} {Informujemy równie¿, ¿e w tym czasie na platformie bêdzie obowi¹zywa³ nowy system bezpieczeñstwa. Dowody osobiste zostan¹ wydane wszystkim pracownikom na koniec zmiany.}
{214} {} {Lista platform wiertniczych na Morzu Korteza.}
{215} {} {(Znajdujesz d³ug¹ listê platform. Prawie wszystkie s¹ oznaczone jako zamkniête. NajwyraŸniej ropa na morzu by³a na skraju wyczerpania przed Wielk¹ Wojn¹. Liczne szkielety tych konstrukcji s¹ nadal widoczne na horyzoncie.)}