{100} {} {Widzisz terminal bezpieczeñstwa.}
{101} {} {Widzisz terminal z dostêpem do sieci publicznej.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Dalej.}
{204} {} {Wróæ do menu g³ownego.}

{210} {} {Aktywuj wie¿yczkê bezpieczeñstwa.}
{211} {} {Nieznany u¿ytkownik. Dostêp zablokowany. Skontaktuj siê z ochron¹.}
{212} {} {Dostêp przyznany. Uwaga: wie¿yczka ochronna chroni platformê przed wrogimi celami. Czy chcesz aktywowaæ wie¿yczkê?}
{213} {} {Tak.}
{214} {} {Nie.}
{215} {} {Dzia³ko stra¿nicze w³aczone.}
{216} {} {OK.}
{217} {} {Wy³¹cz wie¿yczkê bezpieczeñstwa.}
{218} {} {Wie¿yczka stra¿nicza wy³¹czona.}
