{100} {} {Widzisz rybaka.}
{101} {} {Widzisz lokalnego rybaka.}

{110} {} {Czeœæ.}
{111} {} {Wynoœ siê st¹d.}
{112} {} {Nie jesteœ tutaj mile widziany.}
{113} {} {Wiesz, powinieneœ wzi¹æ nieszczeln¹ ³ódŸ i wyp³yn¹æ daleko w morze.}

{120} {} {Czeœæ.}
{121} {} {Mi³o widzieæ now¹ twarz.}
{122} {} {Mi³o ciê poznaæ.}
{123} {} {Po³ów by³ ostatnio sk¹py.}
{124} {} {Jeœli masz doœæ rozumu, nie wyp³ywaj daleko w morze.}
{125} {} {W morzu ¿yje prawdziwy potwór!}
{126} {} {Za ma³o by ¿yæ, za du¿o by umrzeæ.}
{127} {} {Nie spaceruj noc¹ po pla¿y.}
{128} {} {}
{129} {} {}

{130} {} {Moje pozdrowienia.}
{131} {} {Tutaj jesteœ zawsze mile widziany.}
{132} {} {Dziêki za wszystko, co dla nas robisz.}
{133} {} {Po³ów by³ dziœ doskona³y.}
{134} {} {Za ma³o by ¿yæ, za du¿o by umrzeæ.}
{135} {} {W morzu ¿yje prawdziwy potwór!}
{136} {} {Zanosi siê na burzê.}
{137} {} {Nie spaceruj noc¹ po pla¿y.}
{138} {} {}
{139} {} {}

{140} {} {Nie wiesz dok³adnie, co siê sta³o w Puerto?}
{141} {} {Puerto zniszczone! Bez nich bêdzie trudno ¿yæ w tych odludnych regionach.}
{142} {} {Bractwo Stali nas opuœci³o. Bezpieczeñstwo opuœci³o nas z razem nimi.}
{143} {} {Do diab³a, gdyby Bractwo mia³o takie materia³y wybuchowe, ile dobra mogliby nam daæ?}
{144} {} {Oczywiœcie mo¿emy ¿yæ dalej bez Bractwa. Chocia¿ dostarczali nam wszystko, czego potrzebowaliœmy.}

{150} {} {Och, jak to p³onie!}
{151} {} {To niesamowite, ca³e morze PALI SIE.}
{152} {} {Ropa pali siê na ca³ej d³ugoœci horyzontu. Niesamowity widok.}
{153} {} {Dziêki za pomoc zwi¹zan¹ z rop¹. Naprawdê tego potrzebowaliœmy...}

{159} {} {Hej, to Ty ratujesz ¿ycie chorym? Dziêkujê Ci.}

{160} {} {Ktoœ za³atwi³ Jose. Nie bêdê za nim têskniæ.}
{161} {} {Jose zosta³ zabity. Ktoœ taki jak on musia³ tak skoñczyæ pewnego dnia.}
{162} {} {Chcia³bym us³yszeæ, jak Jose klnie na rybaków rano.}
{163} {} {Jestem bardzo zainteresowany tym, jaki skarb znalaz³ Jose.}
{164} {} {Jose chodzi wœciek³y, jakby ktoœ go ogra³ w karty.}
{165} {} {Wiêc duch latarni morskiej naprawdê istnieje?}
{166} {} {Teraz nie zrobiê ani kroku w stronê ruin latarni morskiej.}
{167} {} {Demony Inferno podesz³y zbyt blisko nas.}
{168} {} {O mój Bo¿e, demony Inferno mieszkaj¹ teraz w pobli¿u nas? Koszmar!}
{169} {} {A jeœli ghule z Inferno przenios¹ siê tutaj?}
