{100} {} {Widzisz stwora z Czarnej Laguny.}
{101} {} {Strasznie wygl¹daj¹ce stworzenie czo³ga siê z ruin latarni morskiej!}
{102} {} {Ooh!}

{200} {} {Oooh!}
{201} {} {Ach, potworze! Giñ! Giñ!}
{202} {} {Stop! Jestem taki sam jak ty. Nie chcê ciê zabiæ. Rozumiesz mnie?}
{203} {} {Uh?}
{204} {} {Nie, nie. Bêdzie lepiej, jeœli zginiesz, kreaturo!}
{205} {} {Hej, musisz st¹d odejœæ.}
{206} {} {Ooh?}
{207} {} {Rybacy ciê szukaj¹. A jeœli znajd¹, zabij¹. Rozumiesz?}
{208} {} {Ry? Baki? Arr! Jedzenie! Moje jedzenie!}
{209} {} {Tak, tak. Rozumiem, ¿e jesteœ g³odny. Ale to jest ich dom. I s¹ gotowi zabiæ za niego. OdejdŸ st¹d albo zginiesz!}
{210} {} {Wygl¹da na to, ¿e nie rozumiesz jak przemawiam JA. Dlatego niech przemówi moja BRON!}
{211} {} {Wiêc nie zostawiasz mi wyboru. Bêdziesz musia³ umrzeæ.}
{212} {} {(rozgl¹da siê w panice i szybko ucieka)}
{213} {} {No dalej, okropna istoto, wróæ do piek³a, z którego wype³z³aœ.}
