{100} {} {Widzisz Thelmê.}
{101} {} {Widzisz dziewczynê ze smutnym wyrazem twarzy.}
{102} {} {Mi³o ciê widzieæ.}
{103} {} {Zombie! Czy to jakaœ apokalipsa?}

# Pierwszy dialog
{200} {} {Hej, witaj wêdrowcze. Mi³o jest zobaczyæ now¹ twarz w mieœcie. Nazywam siê Thelma Ferrino. Jak siê masz?}
{1200} {} {Hej, witaj wêdrowcze. Mi³o jest zobaczyæ now¹ twarz w mieœcie. Nazywam siê Thelma Ferrino. Jak siê masz?}
{201} {} {Po prostu œwietnie. A ty jak siê masz?}
{202} {} {By³y lepsze dni. Ale dziêkujê, ¿e pytasz.}
{1202} {} {By³y lepsze dni. Ale dziêkujê, ¿e pytasz.}
{203} {} {Dlaczego pytasz?}
{204} {} {Có¿, chcê ciê tylko poznaæ. Rzadko miewamy goœci. Zw³aszcza teraz. Kiedyœ miasto by³o ¿ywsze.}
{205} {} {Co siê sta³o?}
{206} {} {Có¿, mogê opowiedzieæ, jednak czy mo¿esz najpierw przynieœæ mi coœ do picia z baru?}
{207} {} {OK, zaraz Ci coœ przyniosê.}
{208} {} {Zadnych drinków, senorita. Adios.}
{209} {} {Oto 5 kapsli dla ciebie, weŸ sobie sama.}
{210} {} {Muchas gracias!}
{211} {} {A teraz powiedz mi, co siê tutaj dzieje.}
{212} {} {Có¿, skoro ju¿ podzieli³eœ siê drinkiem. Myœlê, ¿e jestem ci to winna.}
{1212} {} {Có¿, skoro ju¿ podzieli³aœ siê drinkiem. Myœlê, ¿e jestem ci to winna.}
{213} {} {Nie odchodzisz. Wiêc pewnie podoba ci siê tutaj. Dotrzymasz mi towarzystwa?}
{214} {} {Opowiesz mi o tym miejscu?}
{215} {} {Co tu siê dzieje i dlaczego jesteœ taka smutna?}

{220} {} {Chodzi o tê cholern¹ platformê na Morzu Corteza. Stoi tam od niepamiêtnych czasów. Wczeœniej nie by³o z ni¹ ¿adnych problemów. Pescadores u¿ywali jej nawet do odpoczynku, dopóki nie wprowadzi³y siê tam potwory o dziwnej nazwie. Niedawno z tej platformy zacz¹³ wyp³ywaæ jakiœ truj¹cy brud. Prawdopodobnie z tego powodu po³owa morza jest ju¿ martwa.}
{221} {} {Czy ktoœ zgin¹³ w osadzie przez to? Czy to dlatego jesteœ taka smutna?}
{222} {} {Kiedy to wszystko sta³o siê nie do zniesienia, mój wujek poszed³ na platformê z innymi pescadores. Wiedzieli, ¿e to niebezpieczne, ale musieli coœ zrobiæ.}
{223} {} {Co tam siê sta³o?}
{224} {} {Zobaczy³am przez lornetkê, jak weszli do œrodka. Od tego czasu nic o nich nie s³yszano. Pewnie wszyscy zginêli. (bierze spory ³yk prosto z butelki)}
{225} {} {Przepraszam. Musia³aœ kochaæ swojego wujka.}
{226} {} {Kiedy spêdzacie razem tyle czasu na tej samej ³odzi, wszyscy staj¹ siê rodzin¹, nawet jeœli pochodz¹ z ró¿nych czêœci pustkowia. Wiesz, by³abym szczêœliwsza, gdyby ktoœ zwróci³ mi jego rzeczy na pami¹tkê.}
{227} {} {Chyba nigdy nie znajdê siê na tej platformie. Przepraszam, ale nie pomogê.}
{228} {} {Bêdê pamietaæ. Rozchmurz siê, Thelma.}
{229} {} {}

{230} {} {Hej, witaj wêdrowcze. Wiêc to ty podpali³eœ platformê na œrodku morza? }
{1230} {} {Hej, witaj wêdrowcze. Wiêc to ty podpali³aœ platformê na œrodku morza? }
{231} {} {Tak jakby. Ani wyciek, ani potwory nie s¹ ju¿ zagro¿eniem.}
{232} {} {Dziêkujê z ca³ego serca. Widzia³eœ szcz¹tki naszych pescadores na platformie? By³ wœród nich mój wujek.}
{233} {} {Nie, przepraszam. Potwory musia³y je po¿reæ.}
{234} {} {Tak myœla³am. Dobrze. Czas opamiêtaæ siê i zabraæ siê do pracy. Teraz znów mamy du¿o pracy!}
{235} {} {Bywaj.}
{236} {} {Natkn¹³em siê tylko na ten przedmiot wœród stosu koœci.}
{237} {} {Tak, to nale¿a³o do mojego wujka! Dziêkujê bardzo, zaopiekujê siê tym.}
{238} {} {Oczywiœcie.}
{239} {} {Nie tak szybko. Za takie czyny zwykle przyznawana jest nagroda.}
{240} {} {Nigdy bym nie pomyœla³a, ¿e to powiesz. Czy to dlatego pomog³eœ nam z platform¹ - aby siê wzbogaciæ? Ok, oto moje ostatnie sto kapsli. Czy to wystarczy?}
{1240} {} {Nigdy bym nie pomyœla³a, ¿e to powiesz. Czy to dlatego pomog³aœ nam z platform¹ - aby siê wzbogaciæ? Ok, oto moje ostatnie sto kapsli. Czy to wystarczy?}
{241} {} {Wystarczy. Do zobaczenia.}
{242} {} {Na platformie natkn¹³em siê na ten przedmiot wœród stosu koœci. Musia³ nale¿eæ do twojego wuja.}
{243} {} {Przypadkowo w³aœnie odwiedzi³em platformê i znalaz³em tam ten przedmiot. Jest na nim Twoje nazwisko.}

{250} {} {Czeœæ.}
{251} {} {Do widzenia.}
{252} {} {Czeœæ. Dobrze ciê widzieæ.}
