{100} {} {Widzisz Ruiza.}
{101} {} {Widzisz lokalnego. Ma na sobie chustê i dziwn¹ pelerynê.}
{102} {} {Kopaæ, kopaæ, nie przestawaæ.}
{103} {} {Lepiej nie testuj mojej cierpliwoœci.}
{104} {} {Jeœli napotkam jak¹kolwiek inn¹ mapê skarbów, na pewno dam ci znaæ.}
{105} {} {Jak siê masz, companiero?}
{106} {} {Jak siê masz, companiero?}
{1106} {} {Jak siê masz, companiera?}

{200} {} {No có¿, co my tu mamy?}
{201} {} {To nie jest twoje. IdŸ st¹d.}
{202} {} {Odwal siê, dziwaku. Nikt nie mo¿e Ci tutaj pomóc. Poza tym to ja znalaz³em ten skarb. I nale¿y teraz do mnie. A teraz b¹dŸ mi³y - przesuñ siê i KURWA!}
{1202} {} {Odwal siê, dziwaku. Nikt nie mo¿e Ci tutaj pomóc. Poza tym to ja znalaz³em ten skarb. I nale¿y teraz do mnie. A teraz b¹dŸ mi³a - przesuñ siê i KURWA!}
{203} {} {Zmuœ mnie, maluchu.}
{204} {} {Och, proszê. To naprawdê twój skarb.}
{205} {} {Pomyœl, gringo. Nikt nie mo¿e Ci tutaj pomóc. Znalaz³em ten skarb. I nale¿y teraz do mnie. A teraz b¹dŸ mi³y - przesuñ siê i KURWA!}
{1205} {} {Pomyœl, senora. Nikt nie mo¿e Ci tutaj pomóc. Znalaz³em ten skarb. I nale¿y teraz do mnie. A teraz b¹dŸ grzeczn¹ dziewczynk¹ - przesuñ siê i KURWA!}
{206} {} {Och, proszê, spójrz.}
{207} {} {Czy to wszystko? Niewiele. Stary cz³owiek by³ zrzêd¹, móg³ chocia¿ zostawiæ coœ cenniejszego. Chcia³bym móc zabraæ wszystko, ale niestety musze siê podzieliæ. Co wybierasz z tego?}
{208} {} {50 przedwojennych dolarów.}
{209} {} {Rewolwer bojowy.}
{210} {} {Antyrad, 3 szt.}
{211} {} {Wybieram wszystko. OdejdŸ od moich rzeczy!}
{212} {} {Hmmm, czy mam ciê wykoñczyæ? W porz¹dku.}
{213} {} {Tylko spróbuj!}
{214} {} {Wszyscy s¹ na plusie. Ale jakoœ nie czujê siê komfortowo na myœl o utraconych zyskach. Ok, czeœæ.}
{215} {} {Do widzenia.}