{100}{}{Widzisz Jose Ruiza.}
{101}{}{Widzisz miejscowego. Nosi bandanê i dziwn¹ pelerynê.}
{102}{}{Spotkaj siê ze mn¹ w pobli¿u skarbu.}
{103}{}{Nie testuj mojej cierpliwoœci.}
{104}{}{Jeœli natrafiê na kolejn¹ mapê skarbów, na pewno Ci powiem.}
{105}{}{Szukasz skarbu? Tu go nie ma.}
{106}{}{Nawet nie myœl o ukrywaniu siê tutaj. Upiory na pewno ciê wywêsz¹.}

{200}{}{Hej, nowy! Nazywam siê Jose Rene Ruiz. Co Cie tutaj sprowadza?}
{1200}{}{Hej, nowa! Nazywam siê Jose Rene Ruiz. Co Cie tutaj sprowadza?}
{201}{}{Szukam czegoœ.}
{202}{}{Szukam kogoœ.}
{203}{}{Zrozumia³em. Wiesz, ja te¿ czegoœ szukam. Jeœli mi pomo¿esz, ja pomogê tobie.}
{204}{}{Naprawdê? O co chodzi?}
{205}{}{Có¿, pewien stary cz³owiek ukry³ skarb gdzieœ na wybrze¿u. A potem siê ulotni³. Gdzie jest skarb, nikt nie wie dok³adnie. Jest mapa, ale podar³ j¹ na cztery czêœci i ukry³ w ró¿nych miejscach.}
{206}{}{Przebiegle.}
{207}{}{Mam jeden fragment. Jeœli znajdziesz resztê, przynieœ je do mnie, a skarbem podzielimy siê na pó³.}
{208}{}{Sk¹d mam wiedzieæ, ¿e mnie nie oszukasz?}
{209}{}{OK. Jeœli je znajdê, przyjdê prosto do Ciebie.}
{210}{}{Sk¹d masz wiedzieæ, ¿e ciê nie oszukam? To tylko umowa. Jeœli ci siê nie podoba, zapomnij o tym i idŸ dalej swoj¹ drog¹.}
{211}{}{Pomyœlê o tym.}
{212}{}{Jesteœ szalony! Kto ciê tu wpuœci³? A jednak mo¿e mi siê przydasz... S³uchaj, nowy, nazywam siê Jose Rene Ruiz. Najpierw powiedz mi, dlaczego tu jesteœ?}
{1212}{}{Jesteœ szalona! Kto ciê tu wpuœci³? A jednak mo¿e mi siê przydasz... S³uchaj, nowa, nazywam siê Jose Rene Ruiz. Najpierw powiedz mi, dlaczego tu jesteœ?}

{220}{}{Jakieœ nowe wiadomoœci?}
{221}{}{Jeszcze nic.}
{222}{}{Znalaz³eœ coœ?}
{223}{}{Jeszcze nie.}

{230}{}{Czy by³eœ na platformie?}
{231}{}{Nie. I nie ma tam nic do roboty. Gdyby by³a tam maszyna do produkcji kapsli, by³bym tam jako pierwszy.}
{232}{}{Czy wiesz, sk¹d wzi¹æ baterie do ³odzi?}
{233}{}{Wszystkie baterie s¹ rozprowadzane przez kapitanów. Jednak na pewno nie oddadz¹ swoich baterii. Szukaj g³upich wœród reszty miejscowych, zwykle gromadz¹ siê przy barze.}
{234}{}{Rozumiem.}

{240}{}{Mam brakuj¹ce fragmenty mapy.}
{241}{}{No to chodŸ tutaj!}
{242}{}{Uch, dobrze...}
{243}{}{Cholera! Sam znajdê ten skarb.}
{244}{}{Tak... (Wyci¹ga swój fragment, sk³ada wszystko w ca³oœæ i d³ugo nimi krêci) Oto jest...}
{245}{}{Jesteœ pewien?}
{246}{}{Dok³adnie! Pozostaje tylko pójœæ i zabraæ to co tam jest. Teraz znajdŸ ³opatê i idŸ na miejsce. Skarb zosta³ zakopany obok starej latarni morskiej na wybrze¿u na pó³noc od miasta.}
{247}{}{Ju¿ dzia³am!}

{250}{}{Daj spokój, zabi³eœ Johnny'ego?}
{251}{}{O czym ty do diab³a mówisz?!}
{252}{}{Zosta³ uduszony twoj¹ lin¹. Jak to wyt³umaczysz?}
{253}{}{Ha! Sprzeda³em tê linê kilku rybakom. Dlaczego niby to ja mia³bym kogoœ zabiæ? Kim ty w ogóle jesteœ idioto?}
{254}{}{Komu j¹ sprzeda³eœ?}
{255}{}{Mam to nawet w swoich notatkach, spójrzmy... Tylko Ting Tan ostatnio tu by³. Hej, to ten wujek Johnny'ego, prawda? Nic dziwnego, ¿e mia³ moj¹ linê, jest tu nowy.}
{256}{}{OK. Porozmawiam z tym wujem.}
{257}{}{Ja tutaj zadajê pytania, koleœ. Kto by³ ostatni¹ osob¹, która kupi³a od Ciebie linê?}