{100} {} {Widzisz kapitana statku.}
{101} {} {Widzisz miejscowego zajêtego zwyk³ymi sprawami.}

{110} {} {Czeœæ.}

{200} {} {Hej dzieciaku. Jak mogê ci pomóc?}
{1200} {} {Moje uszanowanie, pani. Jak mogê pomóc?}
{201} {} {Niewa¿ne.}
{202} {} {To by³ po¿ar! Ca³e niebo by³o czarne od dymu!}
{203} {} {Muszê iœæ. Bywaj.}

{210} {} {Zastanawiam siê tylko, co robisz.}
{211} {} {Teraz odpoczywam i podziwiam morze. Mo¿e powinienem rzuciæ okiem na sieci?}
{212} {} {Teraz odpoczywam i podziwiam morze. Mo¿e powinienem zbieraæ ma³¿e?}
{213} {} {Teraz odpoczywam i podziwiam morze. Mo¿e powinienem iœæ do baru?}
{214} {} {Niez³y pomys³. Do zobaczenia.}

{220} {} {Próbujê teraz naprawiæ tê star¹ ³ódŸ. Ale pewnie d³ugo jeszcze bêdzie le¿eæ bezczynnie na molo.}
{221} {} {Co z ni¹ nie tak?}
{222} {} {Kilka dziur, pêkniêæ, rdza. A tak¿e nie ma czym zasiliæ silnika. Krótko mówi¹c, wszystko jest nie tak, a bez ³odzi zginie ca³a wioska. Wiêc ktoœ musi to naprawiæ.}
{223} {} {Dziury, mówisz? Daj mi zobaczyæ...}
{224} {} {Rozumiem. Czy mogê zadaæ kilka pytañ?}

{230} {} {Czy mogê zadaæ kilka pytañ?}
{231} {} {O co chodzi?}
{232} {} {Gdzie s¹ inne ³odzie?}
{233} {} {Mamy, wiesz, problemy z ³odziami. Jedna du¿a ³ódŸ wyp³ywa w morze, aby ³owiæ ryby. Jest te¿ kilka ma³ych ³odzi, ale daleko na nich nie mo¿na wyp³ywaæ. Straciliœmy ju¿ trzy ³odzie z ró¿nych powodów - jedna wci¹¿ stoi na platformie jak widzisz, druga wywróci³a siê podczas burzy, a trzecia, jak mówi¹, zosta³a wci¹gniêta na dno przez morskiego potwora. Chocia¿ nie jestem pewien co do tego drugiego.}
{234} {} {Sk¹d bierzecie zasilanie do ³odzi?}
{235} {} {Baterie pochodz¹ z Puerto. A jeœli jest ich za ma³o, wios³ujemy rêkoma.}
{236} {} {Co wiesz o platformie wiertniczej?}
{237} {} {Dziwne miejsce. Najpierw zadomowi³o siê tam kilka zwierz¹t morskich. A teraz wyp³ywa stamt¹d czarna trucizna. By³oby mi³o siê tego pozbyæ, ale jak?}
{238} {} {No có¿, niewa¿ne.}
{239} {} {Dziêki za rozmowê. Do zobaczenia.}
{240} {} {Opowiedz mi o sobie kapitanie.}
{241} {} {Jakie zwierzêta?}
{242} {} {Ohydne, tyle Ci powiem. Zrobi³y sobie gniazdo na platformie wiertniczej i nie pozwalaj¹ rybakom podejœæ do niego. Ledwo siê stamt¹d wydostaliœmy, gdy wyruszyliœmy na rekonesans. Mieliœmy szczêœcie - podobno zwierzêta te nie s¹ tak aktywne w ci¹gu dnia co w nocy.}
