{100} {} {Widzisz rybaka.}
{101} {} {Widzisz opalonego rybaka.}
{102} {} {Przed tob¹ le¿y chory cz³owiek.}
{103} {} {Widzisz rybaka. Wygl¹da na wychudzonego po d³ugiej chorobie.}
{104} {} {Twoje umiejêtnoœci nie wystarcz¹, aby wyleczyæ pacjenta bez specjalnych leków.}
{105} {} {(}
{106} {} {/ 3) Pacjent dochodzi do siebie.}
{107} {} {Czujê siê ju¿ lepiej. Dziêki doktorze.}

{110} {} {* Khe-khe *}
{111} {} {Och...}

{120} {} {* Khe-khe *}
{121} {} {Nie czujê siê dobrze. Mo¿esz mi pomóc?}
{122} {} {Wyzdrowia³em i czujê siê œwietnie. Czynisz cuda, doktorze!}
{123} {} {Po co mnie leczysz, skoro tak bardzo nienawidzisz tego miejsca?}
