{100}{}{Widzisz Tin-Tana.}
{101}{}{Widzisz sk¹po odzianego, chudego pescadora z postrzêpionymi w¹sami i krzywymi zêbami.}
{102}{}{Trzymaj siê ode mnie z daleka! Ty, hm, brzydko pachniesz.}
{103}{}{Cholera, to wszystko przez tego frajera...}

{200}{}{Ai-yay-yay, co za ma³a rybka! Dlaczego jesteœ sama? Wróæ z powrotem do morza, stañ siê du¿a, a potem wróæ. P³yñ! Do zobaczenia póŸniej, rybko!}
{201}{}{Uch, wygl¹da na to, ¿e przeszkadzam.}
{202}{}{Fale przyprawiaj¹ mnie o md³oœci, a potem zasypiam. Czasami marzê o czymœ fajnym, na przyk³ad jak tañczê w otoczeniu piêknych dziewczyn!}
{203}{}{Uch, rozumiem.}
{204}{}{Wygl¹da na to, ¿e nale¿y ci podziêkowaæ za tê sprawê z rop¹. Bardzo dziêkujê! Brawo!}
{205}{}{De nada.}
{206}{}{Proszê.}

{210}{}{Czeœæ. Jestem Ting Tan. Jak siê masz?}
{211}{}{Pa.}

{220}{}{Czy by³eœ na platformie?}
{221}{}{W moich snach jestem wszêdzie i w czyichœ ramionach!}
{222}{}{Um, rozumiem.}
{223}{}{Tin-Tan – co to za dziwne imiê?}
{224}{}{Kiedyœ by³em... perkusist¹... Topillo! A potem zosta³em Tin-Tan. W³aœciwie nazywam siê... bum-bum-bum... Germán Genaro Cipriano Gomez Valdes y Castillo! Ale to trochê... niewygodne, wiesz?}
{225}{}{Ach, teraz wszystko jest jasne.}
{226}{}{Powiedzia³bym, ¿e to przezwisko, idioto.}

{230}{}{Mam z³e wieœci. Johnny, twój krewny, nie ¿yje.}
{231}{}{Och, jak to siê sta³o?!}
{232}{}{Ktoœ go zabi³. Uduszono go lin¹.}
{233}{}{Co to jest? Hej, taka lina jest sprzedawana przez José! Och, czy Jose to zrobi³? Nie mo¿e byæ!}
{234}{}{Có¿, w takim razie powinienem zapytaæ o to José.}
{235}{}{Ale ta lina jest nowa i kupi³eœ tak¹ jako ostatni.}
{236}{}{Dlaczego mia³bym to zrobiæ? Jestem jego wujem! Och, lepiej zejdŸ mi z oczu i pozwól mi p³akaæ w samotnoœci! Och, biedny Johnny!}
{237}{}{Zgadza siê - dlaczego? Muszê poszukaæ wiêcej wskazówek.}
{238}{}{Germán Genaro Cipriano Gomez Valdes y Castillo nie ¿yje. Kim jesteœ?}
{239}{}{Nie wiem, o czym mówisz!}
{240}{}{Prawdziwy Herman Valdez zgin¹³ w drodze dyli¿ansem. Zabra³eœ jego papiery i teraz podszywasz siê pod niego. Co ty na to?}
{241}{}{(rozgl¹da siê) Hej, ty, ¿arty siê skoñczy³y. Pos³uchaj mnie, skurwysynu. Zamknij siê i siedŸ cicho. Albo skoñczyæ jak ten dzieciak. Lapiesz?}
{242}{}{To brzmi jak wyznanie. Czas na karê, suko!}
{243}{}{Nie powiem nikomu ani s³owa. Obiecujê.}
{244}{}{Naprawdê? Có¿, prawdopodobnie masz racjê. Przepraszam, ¿e przeszkadzam.}
