{100} {} {Widzisz Chatto.}
{101} {} {Widzisz m³odego mê¿czyznê o zmartwionym spojrzeniu.}
{102} {} {Wow, czy to jedna z tych rzeczy, które wymyœli³o Miasto? Niesamowite!}
{103} {} {Stary cz³owiek zupe³nie zwariowa³!}
{104} {} {Zmieniê siê. Obiecujê, ¿e bêdê broniæ swojego plemienia przed obcymi z Phoenix do samego koñca.}

{200} {} {Ugh, Mangas w koñcu stan¹³ za mn¹. Prawdopodobnie wydaje ci siê to szalone. Nie myœl, ¿e wszyscy tacy jesteœmy. Ten stary cz³owiek zwariowa³.}
{201} {} {Kim jesteœ?}
{202} {} {Nazywam siê Chatto. Jestem wojownikiem swojego plemienia.}
{203} {} {Czeœæ Chatto. Dlaczego ten starzec siê tak na ciebie wœciek³?}
{204} {} {Mangas zdecydowa³, ¿e jako szaman mo¿e mówiæ ka¿demu, co jest dobre, a co z³e. Dlaczego nie mogê sam o tym decydowaæ? Ja te¿ jestem przysz³ym liderem!}
{205} {} {Przysz³ym? A kto jest nim teraz?}
{206} {} {Mój ojciec, naczelny Geronimo. Prawdopodobnie s³ysza³eœ o nim, jest legend¹. To on zebra³ plemiê i za³o¿y³ San Brahmin. Pozostali przywódcy czasami zazdroszcz¹, ¿e nie zajêli jego miejsca.}
{1206} {} {Mój ojciec, naczelny Geronimo. Prawdopodobnie s³ysza³aœ o nim, jest legend¹. To on zebra³ plemiê i za³o¿y³ San Brahmin. Pozostali przywódcy czasami zazdroszcz¹, ¿e nie zajêli jego miejsca.}
{207} {} {Wiêc co zamierzasz zrobiæ, gdy zostaniesz g³ow¹ plemienia?}
{208} {} {Do diab³a ze starymi tradycjami i t¹ niekoñcz¹c¹ siê wojn¹! Musimy zawrzeæ pokój z Phoenix - dla naszego bezpieczeñstwa i dla naszej przysz³oœci. Taki sojusz da³by nam wiele mo¿liwoœci. Spójrz na broñ obcych, na nowe przedmioty do pracy, sama komunikacja radiowa jest wiele warta...}
{209} {} {Rozwiñ tê myœl...}
{210} {} {Co daj¹ nam Rangersi? Chroni¹ nas tylko przed bandytami i niebezpiecznymi bestiami. Wspiera mnie wielu m³odych ludzi. Jesteœmy zmêczeni starymi ludzmi i ich radami. Prowadz¹ nas na wojnê. Nadszed³ czas, aby plemiê siê zmieni³o.}
{211} {} {Masz wielkie ambicje, ch³opcze. Mam nadziejê, ¿e wiesz, co robisz. Do zobaczenia.}

{220} {} {Witaj wêdrowcze. Czy poczu³eœ siê ura¿ony przez miejscowych? Powiedz mi, jeœli ktoœ nie toleruje Twojej obecnoœci.}
{1220} {} {Witaj wêdrowcze. Czy poczu³aœ siê ura¿ona przez miejscowych? Powiedz mi, jeœli ktoœ nie toleruje Twojej obecnoœci.}
{221} {} {Witaj wêdrowcze.}
{1221} {} {Witaj wêdrowcze.}
{222} {} {W porz¹dku. Chcê siê tylko przywitaæ. Do zobaczenia.}
{223} {} {Zrobisz w³aœciw¹ rzecz. Do zobaczenia.}
{224} {} {Moim zdaniem zbyt delikatne, ale wystarczy.}
{225} {} {Rebelianci przejêli katedrê w Phoenix. Aaron zosta³ zabity. Teraz nic nie przeszkadza Rangersom.}

{230} {} {Chatto, nie s¹dzisz, ¿e czas wzi¹æ plemiê w swoje rêce?}
{231} {} {Myœla³em o tym przez d³ugi czas. Starzy ludzie nie daj¹ mi prawa g³osu. Uwa¿aj¹, ¿e m³odzi ludzie powinni walczyæ i postêpowaæ zgodnie ze wskazówkami starszych.}
{232} {} {Ale nie zgadzasz siê z nimi, prawda?}
{233} {} {Oni nie rozumiej¹! Zycie w Phoenix nie jest ju¿ tak chore i s³abe, jak kiedyœ. Straciliœmy nasz¹ przewagê. Teraz mieszkañcy miasta posiadaj¹ potê¿n¹ broñ i technologie.}
{234} {} {Phoenix zmiecie plemiê w tym tempie.}
{235} {} {Tak! Jedyne, co pozwoli nam prze¿yæ, to nawi¹zanie kontaktu z Phoenix w celu przechytrzenia jego mieszkañców. Moglibyœmy równie¿ zdobyæ broñ i ich technologie.}
{236} {} {Dobrze. Wiêc na co czekasz?}
{237} {} {Starzy ludzie nie chc¹ zmieniæ zdania. S¹ przyzwyczajeni do pogl¹du, ¿e technologia jest z³a i musz¹ ¿yæ zgodnie z przykazaniami natury.}
{238} {} {Ach, rozumiem. W takim razie nie mam nic do powiedzenia. Do zobaczenia.}
{239} {} {Musisz zmusiæ ich do zmiany zdania, Chatto.}
{240} {} {Co mogê zrobiæ? Starcy nie daj¹ mi prawa g³osu, dopóki ¿yje mój ojciec.}
{241} {} {Có¿, zosta³o ci kilka opcji. Powodzenia.}
{242} {} {Kiedy bêdziesz u w³adzy, bêdzie ju¿ za póŸno. Wyeliminuj swojego ojca teraz, Chatto.}
{243} {} {Co? Mam zabiæ swojego ojca? Zamknij siê! Nie zrobiê tego.}
{244} {} {Przepraszam. Zapomnij o tym, co us³ysza³eœ.}
{245} {} {OK. Zrobiê to. Ktoœ musi pokazaæ ci hart ducha.}
{246} {} {Czekaj... Nie zamierzasz tak po prostu w³amaæ siê do sanktuarium, prawda? Nie, potem na pewno nie zasi¹dê na tronie.}
{247} {} {Masz jakieœ lepsze sugestie? Mo¿e trucizna?}
{248} {} {Jad skorpiona nie zadzia³a. Ca³e plemiê od najm³odszych lat przyzwyczaja siê do tej trucizny. Ale przedwojenne narkotyki i leki zwykle prowadzi³y do smutnych konsekwencji, gdy ktoœ decydowa³ siê na ich za¿ywanie. Dlatego plemiê ju¿ dawno porzuci³o stare medykamenty.}
{249} {} {Myœlê, ¿e mogê znaleŸæ jakieœ stare chemikalia w Phoenix. Czeœæ, Chatto.}
{250} {} {Ryzykujesz, ¿e przegapisz swoj¹ szansê. Twój ojciec musi odejœæ. Dalej, zrób to, Chatto.}
{251} {} {Zabiæ w³asnego ojca? Proponujesz coœ nie do pomyœlenia...}
{252} {} {Przepraszam. Zapomnij o tym, co us³ysza³eœ.}
{253} {} {Zrób to dla przysz³oœci swojego plemienia. Twój ojciec i reszta starszych prowadz¹ plemiê prosto do otch³ani.}
{254} {} {(Patrzy na swoje d³onie, d³ugo kiwa g³ow¹ na twoje s³owa, a potem cicho patrzy w góre i idzie w stronê sanktuarium.)}
{255} {} {Nie martw siê, Chatto. Ta rozmowa nie mia³a miejsca.}
{256} {} {Phoenix aktywnie promuje niewolnictwo w ca³ej po³udniowej Arizonie. Villa ju¿ sta³a siê jedn¹ z ofiar.}
{257} {} {Phoenix wspó³pracuje z Blacharzami, którzy zniewalaj¹ plemiona. Nikomu z nich nie mo¿na ufaæ.}
{258} {} {Jest jeszcze jedna osoba, która przeszkadza tobie i twojemu plemieniu. Co zamierzasz zrobiæ z Rangersem?}
{259} {} {Bêdê musia³ go wyrzuciæ z pueblo. Niech odejdzie w spokoju.}

{260} {} {Co tam siê dzieje? Widzia³em szamanów biegn¹cych do sanktuarium...}
{261} {} {Twój ojciec zmar³. Teraz to Ty musisz przewodziæ plemieniu.}
{262} {} {Czy on... nie ¿yje? Ale... Poczekaj, pozwól, ¿e och³onê.}
{263} {} {Oczywiœcie. Zastanów siê dobrze, co robiæ dalej.}
{264} {} {Jeœli siê poœpieszysz przejmiesz w³adzê w plemieniu. Dalej, zawrzyj sojusz z Phoenix, tak jak chcia³eœ.}
{265} {} {Dobrze! To moja szansa. I ju¿ nigdy nie pozwolê, ¿eby ci g³upi starcy wszystko rujnowali. (ucieka do sanktuarium)}
{266} {} {Hej, Chatto!}
{267} {} {Byæ mo¿e s³ysza³eœ o eksplozji Phoenix. Naprawdê chcesz takich sojuszników?}
{268} {} {W takim razie bêdziesz zainteresowany histori¹ Quartz. S³uchaj uwa¿nie...}
{269} {} {Kolonia Flagpool wykorzystuje niewolnicz¹ si³ê robocz¹ z Phoenix.}

{270} {} {Teraz poprowadzê plemiê w innym kierunku. Starzy ludzie ju¿ nie mog¹ mnie powstrzymaæ.}
{271} {} {Myœlê, ¿e wiesz, co robiæ. Do zobaczenia.}
{272} {} {Czy jesteœcie gotowi zawrzeæ sojusz z misjonarzami z Phoenix?}
{273} {} {To w³aœnie zamierzam zrobiæ. Powiedz Crookowi, ¿e jestem gotów zapaliæ z nim fajkê pokoju... Albo usi¹œæ przy stole negocjacyjnym. Czy tak siê teraz mówi w mieœcie?}
{274} {} {Pokój i dobrobyt, wodzu.}
{275} {} {OK. Do zobaczenia.}
{276} {} {Nawiasem mówi¹c, by³oby mi³o ponownie otworzyæ trasê karawan z Garage City. Co myœlisz?}
{277} {} {Mówisz o kolonii Phoenix na pó³nocy, sprzedaj¹c¹ stare przedmioty z ruin? Myœlê, ¿e plemieniu przyda siê zdobyæ kilka nowych rzeczy. Powiedz Ronniemu, ¿eby przyjrza³ siê tej sprawie.}

{278} {} {Potrafisz czytaæ, prawda? Wiêc przeczytaj te dzienniki dowódcy misyjnego. Uda³o mi siê je ukraœæ z obozu.}
{279} {} {...Co? Co on pisze? Co to znaczy? „Brudne dzikusy”... „wyje¿dzaj¹ do rezerwatu”... „zabierzcie broñ”... I taki plan zamierza zaproponowaæ swojemu cesarzowi? Cholera, sam Czarny Bramin musia³ przys³oniæ mi umys³.}
{280} {} {Chatto, wodzowie i stra¿nicy nie s¹ zadowoleni z ciebie i twojego ludu.}
{281} {} {Wiem. W przeciwnym razie nie musia³bym walczyæ w tej wojnie. Wodzowie siê myl¹, plemiê MUSI siê zmieniæ. Poniewa¿ œwiat siê zmieni³. W przeciwnym razie plemiê nie przetrwa.}
{282} {} {OK, nie bêdê siê z tob¹ k³óci³.}
{283} {} {Mo¿e po prostu nie s¹ gotowi na zmianê?}
{284} {} {A kiedy bêd¹? Kiedy wszyscy starzy ludzie skoñcz¹ na Niebiañskich Pastwiskach? W tym czasie Imperium Phoenix zmia¿d¿y nas swoj¹ broni¹ i technologi¹.}
{285} {} {Co trzeba zrobiæ, aby w koñcu wszyscy otworzyli oczy?}
{286} {} {Udowodnij mi, ¿e Rangersi to najlepszy wybór. Mo¿e wykazali siê ju¿ gdzieœ na pustkowiu? Albo powiedz mi, czemu sojusz z Phoenix niby jest taki z³y? Czy masz jakieœ dowody, które zmieni¹ moje nastawienie? Mo¿e i obóz misjonarzy ma z³e zamiary zniewolenia San Brahmin, ale dopóki nie otrzymam potwierdzenia, nie zmieniê zdania.}
{287} {} {OK. Pomyœlê o tym.}
{288} {} {Wyprzedzasz wszystkich, Chatto. Jak bramin odchodz¹cy od trzody. Nie wiesz, dok¹d siê wybierasz.}
{289} {} {Nie s¹dzê...}
{290} {} {Braminy to zwierzêta stadne. Tylko w ten sposób mog¹ chroniæ siê przed zagro¿eniem. Samotny bramin jest skazany na zag³adê.}
{291} {} {(wzdycha) Wiêc co mam zrobiæ? DoradŸ, bo ty i ja jesteœmy do siebie podobni, ch³opie. Pozostaæ w obozie i chroniæ jego przestarza³y tryb ¿ycia? A mo¿e dalej walczyæ ze spleœnia³ymi starymi ludzmi ¿yj¹cymi w przesz³oœci?}
{1291} {} {(wzdycha) Wiêc co mam zrobiæ? DoradŸ, bo ty i ja jesteœmy do siebie podobni, dziewczyno. Pozostaæ w obozie i chroniæ jego przestarza³y tryb ¿ycia? A mo¿e dalej walczyæ ze spleœnia³ymi starymi ludzmi ¿yj¹cymi w przesz³oœci?}
{292} {} {Nie wiem, Chatto. Sam sobie zadajê to pytanie. Od³ó¿my na razie tê rozmowê, dobrze?}
{293} {} {Zag³osuj na sojusz z Rangersami. Ty i twoi towarzysze musicie wróciæ do plemienia jako czêœæ ca³oœci.}
{294} {} {Mo¿esz mieæ racjê. Ju¿ nie znam siebie... Dobra, porozmawiam z innymi i spróbujê ich uspokoiæ.}
{1294} {} {mo¿esz mieæ racjê. Ju¿ nie znam siebie... Dobra, porozmawiam z innymi i spróbujê ich uspokoiæ.}
{295} {} {IdŸ, Chatto.}
{296} {} {Tak siê z³o¿y³o, ¿e by³em we Flagpool. Phoenix stworzy³o tê koloniê na ziemiach plemienia, które zosta³o w przesz³oœci przez nich wytêpione.}
{297} {} {Czy to prawda? Phoenix zniszczy³o ca³e plemiê ze wzglêdu na swoj¹ koloniê? Hmm... musia³em widzieæ tylko to, co chcia³em zobaczyæ. Na wojnie ka¿dy szuka w³asnej korzyœci.}
{298} {} {Teraz nie zamierzasz opowiadaæ siê za sojuszem z Phoenix, prawda?}
{299} {} {Szczerze, to jakaœ mêtna historia. Niewa¿ne.}
{300}{}{Jeœli masz w¹tpiwoœci, mo¿e losujmy? Niech zdecyduje Duch Pustkowi.}
{301}{}{Nie pozostawiê tego przypadkowi.}
{302}{}{Jak chcesz.}
{303}{}{Ok, losujmy... I jak? Czy los faworyzuje Rangersów?}
{304}{}{Ok, losujmy... I jak? Czy los faworyzuje Phoenix?}
{305}{}{Szczerze, nie podoba mi siê podejmowanie decyzji tym sposobem. Zapomnij o tym.}
{306}{}{Losujmy. Pozwól, aby Duch Pustkowi decydowa³ za Ciebie.}