{100} {} {Widzisz Geronimo.}
{101} {} {Widzisz starego mê¿czyznê w sutannie ze skóry bramina.}
{102} {} {Chroñ mnie, braminie Zbawienia! Niech rozpadn¹ siê stawy mego wroga!}
{103} {} {Och, Czarny Braminie... Dlaczego tak intensywnie siê na mnie gapisz?}
{104} {} {Naprawdê... czas... nadszed³...}

#Pierwsze spotkanie
{200} {} {Ch³op z Villi... Wiem, kim jesteœ. Usi¹dŸ. Skoro siê tu pojawi³eœ, to s¹ ku temu powody, prawda?}
{1200} {} {Ch³opka z Villi... Wiem, kim jesteœ. Usi¹dŸ. Skoro siê tu pojawi³aœ, to s¹ ku temu powody, prawda?}
{201} {} {Moja wioska zosta³a zniewolona. Czy wiesz coœ na ten temat?}
{202} {} {Zmierzch zakry³ Sonorê przed oczami Boskiego Bramina. Lowcy niewolników s¹ teraz wszêdzie. U¿ywaj¹ naszych braci w kopalniach, wyrêbie, budowie miast. Nie wiem, gdzie dok³adnie s¹ twoi wspó³plemieñcy. Ale na pewno dowiesz siê tego w Phoenix.}
{203} {} {Dziêki. Poszukam dalej.}
{204} {} {My te¿ cierpimy z powodu handlarzy niewolników i bia³ych misjonarzy z Phoenix. Po¿¹daj¹ naszych stad i ziem. Nadchodz¹ ciê¿kie czasy, ch³opie z Villi.}
{1204} {} {My te¿ cierpimy z powodu handlarzy niewolników i bia³ych misjonarzy z Phoenix. Po¿¹daj¹ naszych stad i ziem. Nadchodz¹ ciê¿kie czasy, dziewczyno z Villi.}
{205} {} {Mo¿e moi ludzie s¹ tutaj, sk¹d mam wiedzieæ?}
{206} {} {Nie gadaj bzdur! Sami cierpimy przez handlarzy niewolników i misjonarzy o bia³ej skórze z Phoenix. Po¿¹daj¹ naszych stad i ziem. Nadchodz¹ ciê¿kie czasy, ch³opie z Villi.}
{1206} {} {Nie gadaj bzdur! My sami cierpimy z powodu handlarzy niewolników i misjonarzy o bia³ej skórze z Phoenix. Po¿¹daj¹ naszych stad i ziem. Nadchodz¹ ciê¿kie czasy, dziewczyno z Villi.}
{207} {} {Có¿, mam nadziejê, ¿e sobie z nimi poradzisz.}
{208} {} {Mam nadziejê, ¿e Villa jakoœ sobie z tym poradzi.}
{209} {} {Twoja Villa nie mo¿e wiecznie unikaæ nieuniknionego. Wszyscy jesteœmy przeklêci przez tego samego Mrocznego Bramina. Czy myœlisz, ¿e mo¿esz trzymaæ siê z daleka, jak wczeœniej? Nie ma szans!}
{210} {} {Co zamierzasz zrobiæ?}
{211} {} {Chcê zawrzeæ sojusz z Rangersami. Nie by³a to ³atwa decyzja, ale do obrony naszej wolnoœci potrzebujemy sojusznika. W koñcu nasi wrogowie maj¹ broñ i metalowe zbroje. My mamy tylko braminy i patyki.}
{212} {} {Musimy sobie pomagaæ w obliczu wszechobecnego zagro¿enia. Co mogê zrobiæ?}
{213} {} {Villa musi stan¹æ po stronie naszej i Rangersów. To jedyna opcja. ZnajdŸ Rangersa Oscara, pomaga nam w walce z misjonarzami. Mo¿e mu siê przydasz.}
{214} {} {Porozmawiam z nim.}
{215} {} {Zarówno ja, jak i reszta mieszkañców wioski - nie bêdziemy uczestniczyæ w tej wojnie.}
{216} {} {W takim razie powinieneœ wiedzieæ, ¿e jesteœ tylko intruzem na naszych ziemiach. Nie wchodŸ nam w drogê, jeœli nie zamierzasz nam pomóc.}
{217} {} {OK. Wkrótce i tak wychodzê.}
{218} {} {Tak d³ugo jak chcesz mo¿esz zostaæ w obozie.}
{219} {} {Dzieñ dobry, wodzu.}
{220} {} {Do widzenia.}
{221} {} {Jestem tutaj, aby pomóc z zagro¿eniem z Phoenix. Przys³ali mnie Rangersi.}
{222} {} {Rangersi od dawna szanuj¹ nasz¹ wolnoœæ. Doceniam twoj¹ pomoc.}
{223} {} {Od czego mam zacz¹æ?}
{224} {} {Porozmawiaj z Rangersem Oscarem, mieszka w chatce przy wyjœciu z sanktuarium.}
{225} {} {Do zobaczenia wkrótce, wodzu.}

# Powtarzajacy siê dialog
{230} {} {Niepotrzebnie testujesz nasz¹ cierpliwoœæ. Uwa¿aj na jêzyk lub staniesz siê wrogiem naszego plemienia.}
{231} {} {Czego od nas chcesz?}
{232} {} {Okaza³eœ siê bardzo przydatny.}
{233} {} {Pomo¿esz nam czy przeszkodzisz nam tym razem?}
{234} {} {Och, to znowu ten wieœniak. Czego jeszcze potrzebujesz?}
{1234} {} {Och, to znowu ta wieœniaczka. Czego jeszcze potrzebujesz?}
{235} {} {Nied³ugo wychodzê, wodzu.}
{236} {} {Nie myœl ¿e zapomnia³em, pamiêtam wszystkie twoje dobre uczynki. Jak mogê pomóc?}
{237} {} {Mi³o nam ciê widzieæ w naszym obozie.}
{238} {} {Nie powinieneœ wracaæ do obozu. Ale skoro tu jesteœ, bêdziemy musieli z tob¹ wytrzymaæ.}

# Glowne zadanie
{240} {} {Proszê ciê o zerwanie sojuszu z Rangersami i zawarcie sojuszu z misjonarzami z Phoenix.}
{241} {} {Hmm. Na zwyk³ego ch³opa jesteœ zbyt odwa¿ny, to na pewno. Ale dlaczego mam siê zgodziæ?}
{1241} {} {Hmm. Jesteœ za odwa¿na na typow¹ wieœniaczkê, to na pewno. Ale dlaczego mam siê zgodziæ?}
{242} {} {Hmm. Na podstawie plotek nap³ywaj¹cych z zachodu w¹tpiê, ¿eby ten sojusz by³ dobrym pomys³em. Ale czy sojusz z drug¹ stron¹ by³by lepszy?}
{243} {} {Rangersi u¿ywaj¹ ciê tylko do walki z Imperium Phoenix. Nie obchodzi ich twoje plemiê.}
{244} {} {To wielkie s³owa. Ale jednoczeœnie to tylko s³owa ch³opa przeciwko s³owom armii Rangersów.}
{1244} {} {To wielkie s³owa. Ale jednoczeœnie to tylko s³owa wieœniaczki przeciw s³owom ca³ej armii Rangersów.}
{245} {} {Kiedy bêdzie za póŸno, przypomnisz sobie moje s³owa.}
{246} {} {Ale nawet jeœli masz racjê, nie mogê sam podj¹æ decyzji. Reszta szamanów nadal podziela swój punkt widzenia. Nie zmieniê decyzji, dopóki oni nie zmieni¹ swojego zdania.}
{247} {} {W takim razie powinienem porozmawiaæ z reszt¹ liderów. Do zobaczenia, Geronimo.}
{248} {} {Imperium Phoenix zniszczy ciê, jeœli nie zostanie pokonane. Chcesz tak haniebnego koñca?}
{249} {} {Znalezienie pokoju w walce o swoj¹ wolnoœæ to wspania³y koniec. Wolê umrzeæ, ni¿ do³aczyæ do imperium.}
{250} {} {Wiêc jesteœ g³upcem. I pewnego dnia po¿a³ujesz swojej decyzji.}
{251} {} {Rozumiem. Przepraszam za moje s³owa, wodzu.}
{252} {} {To Ty jednoczy³eœ plemiê, wielki wodzu. Do Ciebie nale¿y decyzja, co dalej. Ale zawieraj¹c sojusz ze Stra¿nikami, skazujesz plemiê na niekoñcz¹c¹ siê wojnê.}
{253} {} {Byæ mo¿e masz racjê. Imperium Phoenix jest wielkie, silne i wspania³e. Nie bêdziemy w stanie siê wiecznie opieraæ i pewnego dnia siê poddamy. Jeœli staniemy siê czêœci¹ imperium, zachowamy pewn¹ niezale¿noœæ.}
{254} {} {Czyli zgadzasz siê?}
{255} {} {Chyba powinienem pos³uchaæ tego, co mówisz. Jednak Rangersom siê to nie spodoba. Nie ka¿ mi ¿a³owaæ tej decyzji.}
{256} {} {Dziêki. Przeka¿ê twoje s³owa dowódcy misjonarzy.}
{257} {} {Wszyscy moi doradcy mówi¹ to samo. Sojusz z Rangersami obiecuje tylko jedn¹ krwaw¹ wojnê. A sojusz z Phoenix zapewnia spokój, ale odbiera wolnoœæ.}
{258} {} {Wiesz, ¿e ¿ycie twoich wspó³plemienców jest wa¿niejsze.}
{259} {} {Niektórzy z moich doradców opuœcili ten œwiat, podczas gdy inni zwrócili siê przeciwko mnie. Sojusz z Rangersami obiecuje tylko jedn¹ krwaw¹ wojnê. A sojusz z Phoenix zapewnia spokój, ale odbiera wolnoœæ. W walce or³a z wê¿em pozostaje tylko schowanie g³owy w piasek.}

{260} {} {Misjonarze opuœcili wasze ziemie. Ranger Oscar i ja zmusiliœmy ich do odejœcia.}
{261} {} {Misjonarze opuœcili wasze ziemie. Uda³o mi siê zmusiæ ich do odejœcia.}
{262} {} {To dobra wiadomoœæ dla ca³ego plemienia. Po raz kolejny udowodniliœmy nasz¹ niezale¿noœæ i obroniliœmy nasz¹ wolnoœæ. Oczywiœcie nasza walka siê nie koñczy i za chwilê ponownie bêdziemy walczyæ z bladymi obcymi z Phoenix. Ale ich te¿ prze¿yjemy.}
{263} {} {[Pos³uchaj]}
{264} {} {Jakby sam Boski Bramin wys³a³ ciê do nas w tej trudnej godzinie! Dziêkujê Ci. Mo¿esz pozostaæ w obozie tak d³ugo, jak chcesz. Opowiem wszystkim o twoich wyczynach, aby ka¿dy móg³ bez obaw dzieliæ siê z tob¹ schronieniem i jedzeniem.}
{265} {} {Dziêki.}
{266} {} {Mam nadziejê, ¿e odnajdziesz utracon¹ rodzinê. Nawiasem mówi¹c, nasi zwiadowcy donieœli, ¿e w drodze do Flagpool widziano grupê niewolników z Villi. SprawdŸ tam.}
{267} {} {Dziêki, wodzu.}

{270} {} {Proszê o ponowne otwarcie trasy karawany do Garage City.}
{271} {} {Wszystkie drogi i szlaki handlowe z koloniami Phoenix s¹ zamkniête. Tak zdecydowa³a rada starszych.}
{272} {} {Prawdopodobnie nie zmienisz zdania, dopóki twój stosunek do Phoenix bêdzie... nieprzyjazny, szkoda.}
{273} {} {Ju¿ otworzyliœmy trasy karawan Phoenix. Niech wszystkie jego koloniê wróc¹ do pokojowego handlu.}
{274} {} {Swietnie. }
{275} {} {Garage City równie¿ ucierpia³o z powodu imperium Aarona. Ale teraz Katedra Ognia jest zniszczona, Aaron nie ¿yje. Phoenix nie jest ju¿ dla Was zagro¿eniem.}
{276} {} {Niech tak bêdzie. Przeka¿ zgodê Ronnie'emu, on zajmuje siê karawanami w tym pueblo.}
{277} {} {Dziêki.}
{278} {} {Jestem gotowy, aby otworzyæ trasy karawany dla Phoenix. Ale dok³adnie na œrodku tej œcie¿ki w¹¿ i orze³ rozpoczêli walkê. Dopóki siê nie pogodz¹ lub nie po¿r¹, trudno bêdzie negocjowaæ z kupcami.}
{279} {} {Garage City równie¿ ucierpia³o z powodu imperium Aarona. Ale Katedra Ognia zosta³a zdobyta przez rebeliantów, Aaron zgin¹³. Phoenix nie jest ju¿ dla Was zagro¿eniem.}

# Drobne przemowienia
{300} {} {Kim jesteœ?}
{301} {} {Przechodzisz przez dolinê, mijasz ca³e pueblo i nie wiesz, kto stoi przed tob¹? W takim razie uœwiadomiê Ciê - nazywam siê Geronimo. Jestem najwy¿szym przywódc¹ ca³ego mojego plemienia.}
{302} {} {Opowiedz mi o sobie.}
{303} {} {Czy naprawdê masz tak¹ kiepsk¹ pamiêæ? W takim razie mogê Ci przypomnieæ - nazywam siê Geronimo. Jestem najwy¿szym wodzem plemienia.}
{304} {} {Najwy¿szym? Wiêc s¹ inni?}
{305} {} {Plemiê sk³ada siê z klanów, ka¿dy klan ma swojego przywódcê lub przedstawiciela. Razem jednoczymy siê na czas trudnych prób. Przez resztê czasu rozpraszamy siê po Sonorze w poszukiwaniu po¿ywienia.}
{306} {} {Teraz wszystko jasne.}

{310} {} {Opowiedz mi o swoich ludziach.}
{311} {} {Chcesz poznaæ historiê plemienia? Wiele wycierpieliœmy, ale pozostaliœmy wierni naszym korzeniom.}
{312} {} {Przepraszam, ale nie mam teraz czasu na s³uchanie d³ugich historii.}
{313} {} {Oczywiœcie, m³odzi ludzie nie chc¹ ju¿ znaæ historii i szanowaæ swoich przodków. I to mnie martwi.}
{314} {} {Innym razem.}
{315} {} {Powiedz mi wiêcej.}
{316} {} {Mieszkamy na ziemiach Sonory od pokoleñ. Zyli tu nasi przodkowie, zanim œwiat upad³ od gniewu Ognistego Bramina.}
{317} {} {A¿ trudno uwierzyæ, ¿e uda³o Wam siê przetrwaæ tak d³ugo na pustyni.}
{318} {} {To cud, ¿e prze¿yliœcie wojnê.}
{319} {} {Przez d³ugi czas plemiê sk³ada³o siê z wielu ma³ych rodzin rozsianych po ca³ej pustyni. Ka¿dy prze¿y³ najlepiej, jak móg³. S³abi i chorzy wymarli, ale silni i zdrowi kontynuowali swoj¹ podró¿. Kiedy rodziny siê rozmno¿y³y, a ziemi nie wystarcza³o ju¿ dla wszystkich, zaczê³y siê wojny klanów.}
{320} {} {Co siê sta³o, ¿e nasta³ pokój miêdzy klanami?}
{321} {} {Zagro¿enie ze strony Imperium Phoenix zmusi³o nas do zjednoczenia. Mieszkañcy zaczêli kraœæ nasze byd³o, kupcy zaczêli nas oszukiwaæ, na naszych ziemiach pojawili siê handlarze niewolników. Nie mogliœmy tego d³u¿ej znieœæ.}
{322} {} {Co zrobiliœcie?}
{323} {} {Starsi zebrali siê wokó³ wspólnego ogniska i postanowili siê zjednoczyæ. By³em jednym z tych, którzy pojednali i zgromadzili plemiê. Sta³o siê to tutaj, w obrêbie murów starozytnego pueblo.}
{324} {} {Dziêki za historiê. Do zobaczenia, Geronimo.}
{325} {} {Inspiruj¹ca historia. Pozwól, ¿e zapytam o inne rzeczy.}
{326} {} {Nie, chcê tylko porozmawiaæ o czymœ innym.}

{330} {} {Powiedzia³eœ, ¿e mnie znasz. Jak to? }
{331} {} {Nie Ciebie, ale twojego ojca. Pozna³em go. Silny mê¿czyzna. Uparty, ale m¹dry. Taka osoba, któr¹ wszyscy szanuj¹.}
{332} {} {O tak, to prawda.}
{333} {} {Mój ojciec nie jest wart wspominania. Nie móg³ oprzeæ siê najeŸdŸcom i podda³ siê.}
{334} {} {Ale da³ jasno do zrozumienia, ¿e nie chce, aby ktoœ obcy ingerowa³ w Villê. Zawarliœmy z nim umowê o izolacji. Nasze plemiê i tak nie mog³oby tam przetrwaæ. Jest tam za ma³o trawy dla naszych braminów.}
{335} {} {Tak, wokó³ jest tylko pustynia.}
{336} {} {Tym bardziej zdumiewaj¹ce, ¿e uprawiacie plony na œrodku ja³owej pustynii. Jakby sam Boski Bramin dba³ o wasze ziemie... do niedawna. Mo¿e czymœ go rozgniewaliœcie?}
{337} {} {Te¿ siê zastanawiam jak to mo¿liwe. Ale doœæ o mojej wiosce. Porozmawiajmy o Twojej.}
{338} {} {Nie s¹dzê. A tak przy okazji, czas na mnie, musze siê czymœ zaj¹æ. Do zobaczenia.}

{340} {} {Wiem, ¿e masz staro¿ytn¹ ksi¹¿kê. Oddaj mi j¹ po dobroci.}
{341} {} {Ksi¹¿ka? O czym ty mówisz? Nie czytamy tu ¿adnych ksi¹¿ek.}
{342} {} {K³amiesz. Ksiêgowy Katedry nie móg³ siê myliæ.}
{343} {} {Proszê, ludzie spoza twojego plemienia potrzebuj¹ tej ksi¹¿ki.}
{344} {} {Hmm, pewnie mówisz o jednej z tych starych rzeczy, które trzymane s¹ w podziemiach.}
{345} {} {Podziemia? O czym mówisz?}
{346} {} {Widzisz, ten staro¿ytny budynek ma kilka piêter zakopanych w piasku. Na dole wci¹¿ s¹ stare rzeczy, ale ich nie potrzebujemy. Dlatego nikt tam nie schodzi i nikt nie pamiêta, co tam jest, a czego nie ma. Nie jest to jedyne zakopane miejsce w okolicy - ca³a okolica zapad³a siê w piasek na przestrzeni kilku pokoleñ.}
{347} {} {Wiêc mogê zejœæ na dó³ i j¹ po prostu zabraæ?}
{348} {} {Mo¿esz spróbowaæ. Ale przygotuj siê na najgorsze. Poni¿ej czeka na Ciebie Próba Ducha. Sam s³ysza³em tam g³osy dawno zmar³ych ludzi. Mo¿esz nigdy nie wydostaæ siê z tych staro¿ytnych komnat, jak inni poszukiwacze skarbów, którzy zeszli tam w poszukiwaniu relikwii.}
{349} {} {I tak zaryzykujê. Do zobaczenia.}