{101} {} {Widzisz plemienne dziecko, jest ca³e brudne od ziemi.}

{200} {} {Kto tam? Cz³owiek? Hej, to cz³owiek! Hej, uratuj nas! Jesteœmy tutaj!}
{201} {} {Czy starsi nie zabronili wam zbli¿aæ siê do Pogrzebanego Miasta?}
{202} {} {Jak siê tu dosta³eœ?}
{203} {} {Có¿... zwiedzaliœmy jaskiniê, gdy nagle rozleg³ siê straszny ryk i ziemia pod nami siê osunê³a. Nie mogliœmy znaleŸæ wyjœcia.}
{204} {} {Ryk?}
{205} {} {Cœœ! Wêdruje tu z³y duch! Jest bardzo du¿y i bardzo przera¿aj¹cy! Przez niego nie mo¿emy siê st¹d wydostaæ. Pomó¿ nam siê st¹d wydostaæ! Pomó¿!}
{206} {} {OK, wynoœmy siê st¹d.}
{207} {} {Gdy tylko st¹d wyjdziemy osobiœcie dopilnujê ¿eby was ukarano.}

{210} {} {Jesteœ z³y! Jesteœ okropn¹ osob¹! Pozwól temu potworowi ciê po¿reæ!}
{211} {} {Lepiej siê zamknij...}

{220} {} {Nie umrzemy, prawda?}
{221} {} {Umrzemy? Umrzemy?}
{222} {} {Prosimy, chroñ nas przed z³ym duchem!}
{223} {} {ChodŸcie za mn¹. Trzymajcie siê blisko!}
{224} {} {Zostañcie tutaj i nigdzie nie odchodŸcie. Zobaczê, co nas czeka.}

{230} {} {Hurra! Jesteœmy wolni! Jesteœmy uratowani!}
{231} {} {Jesteœcie teraz bezpieczni.}
{232} {} {Jesteœ naszym wybawc¹! Prawdopodobnie przys³a³ ciê do nas sam Boski Bramin. Kto by pomyœla³, ¿e obcy nas uratuje? Prawdopodobnie twoje plemiê jest dobre. Proszê, weŸ te rzeczy, znaleŸliœmy je pod ziemi¹. (przekazuje naboje 10mm, naboje do strzelby, granat i zapalniczkê) Chwa³a naszemu wybawcy!}
{1232} {} {Jesteœ nasz¹ wybawicielk¹! Prawdopodobnie przys³a³ ciê do nas sam Boski Bramin. Kto by pomyœla³, ¿e obcy nas uratuje? Prawdopodobnie twoje plemiê jest dobre. Proszê, weŸ te rzeczy, znaleŸliœmy je pod ziemi¹. (przekazuje naboje 10mm, naboje do strzelby, granat i zapalniczkê) Chwa³a naszemu wybawcy!}
{233} {} {Nie czekajcie na mnie. IdŸcie prosto do pueblo.}
