{101} {} {Widzisz plemienne dziecko z czarnymi i d³ugimi w³osami.}

{110} {} {Zostaniesz tu na zawsze?}
{111} {} {Opowiesz mi o swoim plemieniu?}
{112} {} {Czy twoje plemiê jest tak du¿e jak nasze?}
{113} {} {Opowiedz mi jak¹œ historiê.}
{114} {} {Szamani mówi¹, ¿e jesteœ dobrym cz³owiekiem.}

{120} {} {Wynoœ siê z pueblo, jesteœ z³ym cz³owiekiem!}
{121} {} {Twoje plemiê jest s³abe.}
{122} {} {Czy ca³e twoje plemiê jest tak gówniane jak ty?}
{123} {} {Powiedz to g³upcom w mieœcie.}
{124} {} {Szamani mówi¹, ¿e masz w sobie z³ego ducha.}

{130} {} {Jakie jest twoje plemiê?}
{131} {} {Nasze plemiê jest lepsze ni¿ twoje.}
{132} {} {Co siê sta³o z twoim plemieniem?}
{133} {} {Chcê us³yszeæ historie o innych miejscach.}
{134} {} {Szamani mówi¹, ¿e nie mo¿na ciê s³uchaæ.}
