{101} {} {Widzisz plemienne dziecko z czarnymi i d³ugimi w³osami.}
{102} {} {Nie ruszaj!}
{103} {} {Ratuj siê! To z³y duch ¿elaza!}
{104} {} {Nie jesteœ taki z³y jak inni ludzie z zewn¹trz. Dziêkujê Ci.}

{110} {} {Css!}
{111} {} {Cicho! Bo nas us³ysz¹...}
{112} {} {Lepiej b¹dŸ cicho.}
{113} {} {Mów cicho.}
{114} {} {Mangas nie powinien wiedzieæ.}
{115} {} {Moze wezwiemy pomoc?}
{116} {} {Nie mo¿emy tego zrobiæ sami.}
{117} {} {Co powinniœmy zrobiæ?}
{118} {} {Nie wrócê tam.}
{119} {} {}

{200} {} {"...Nie, nie mo¿esz tego nikomu powiedzieæ, w przeciwnym razie ca³e plemiê nas znienawidzi!" - "Tak, a masz lepszy pomys³? Oni tam zgin¹!" - "Oni ju¿ nie ¿yj¹, idioto!" - "Nie pójdê tam ponownie, musimy wracaæ..."}
{201} {} {Hej, pods³ucha³em wasz¹ rozmowê. Co siê sta³o?}
{1201} {} {Hej, pods³ucha³am wasz¹ rozmowê. Co siê sta³o?}
{202} {} {(jeden dzieciak nerwowo podskakuje do przodu) "Co ci do tego? Jesteœ obcy!" - (pozostali go uspokajaj¹) "Uspokój siê, kretynie, mo¿e on nam pomo¿e? A mo¿e wolisz iœæ do szamana?" - "Nie, szaman na pewno nas ukarze." }
{1202} {} {(jeden dzieciak nerwowo podskakuje do przodu) "Co ci do tego? Jesteœ obca!" - (pozostali go uspokojaj¹) „Uspokoj siê, kretynie, mo¿e ona nam pomo¿e? A mo¿e wolisz iœæ do szamana?” - "Nie, szaman na pewno nas ukarze." }
{203} {} {Opowiedz mi, co siê sta³o.}
{204} {} {Pos³uchaj, nieznajomy, obiecaj nikomu nie mówiæ, ok? Spacerowaliœmy po Pogrzebanym Mieœcie. To jest na zachód st¹d, gdzie wydmy pokry³y stare pueblo. Wtedy us³yszeliœmy warczenie w lochu i zaczêliœmy biec!}
{205} {} {Normalna ludzka reakcja. Dobrze zrobiliœcie.}
{206} {} {Hmm, co za tchórze... }
{207} {} {Dwóch naszych nie wróci³o.}
{208} {} {Wy idioci!}
{209} {} {Biedne dzieci, spokojnie, to ju¿ koniec.}
{210} {} {To powa¿na sprawa, ch³opaki.}
{211} {} {Wiêc, czy mo¿esz ich uratowaæ?}
{212} {} {Dlaczego to ukrywacie? Dlaczego nie powiedziecie o tym komuœ z plemienia?}
{213} {} {Nam... zakazano tam chodziæ... mówi¹, ¿e mieszka tam z³y duch, zdarzaj¹ siê osuwiska i tak dalej. Ale by³o to tak interesuj¹ce miejsce, ¿e nie mogliœmy siê oprzeæ.}
{214} {} {Muszê siê przygotowaæ do podró¿y. Zabraæ najlepsz¹ broñ jak¹ mam i porz¹dne buty. Poczekajcie tutaj na mnie ch³opaki.}
{215} {} {Dobra, zabierzcie mnie do tych lochów.}

{220} {} {Dziêkujê. Bêdziemy teraz bardziej s³uchaæ starszych.}
{221} {} {Dobrze. Zostaliœcie ostrze¿eni, ale nie pos³uchaliœcie. To bêdzie dla was lekcja na ca³e ¿ycie.}
{222} {} {Nie musicie s³uchaæ wszystkiego, co mówi¹. Powodzenia ch³opaki.}
