{100} {} {Widzisz miejscowego.}
{101} {} {Widzisz opalonego cz³owieka w skórze bramina.}

{110} {} {Nadchodzi burza piaskowa.}
{111} {} {Nastêpny sezon bêdzie gor¹cy.}
{112} {} {Moje braminy s¹ strasznie wychudzone.}
{113} {} {Musimy zdobyæ wiêcej wody nastêpnym razem, gdy bêdziemy poza pueblo.}
{114} {} {Pozostawanie w domu staje siê coraz bardziej niebezpieczne.}
{115} {} {To pueblo zawsze by³o nasze.}
{116} {} {Musimy chroniæ nasze rodziny przed bandytami.}
{117} {} {Boski Braminie, chroñ nas przed obcymi!}
{118} {} {Musimy byæ pos³uszni naszym przywódcom.}

{130} {} {Staruszek Mangas ju¿ wszystkich przekonuje.}
{131} {} {A stary Mangas ostrzega³ nas...}
{132} {} {Genaro z pewnoœci¹ poprze sojusz z Phoenix.}
{133} {} {Genaro zosta³ zabity, a by³ najlepszym negocjatorem dla obcych.}
{134} {} {Nana dba o plemiê zarówno jako kobieta, jak i przywódczyni.}
{135} {} {Nana zosta³a zabita przez misjonarzy. Kto inny móg³by to zrobiæ?}
{136} {} {Martwiê siê o przysz³oœæ Chatto i jego m³odych przyjació³.}
{137} {} {Coœ, czego Chatto nie widzia³ od dawna...}
{138} {} {Chatto jest bardzo m³ody, a ju¿ zosta³ wodzem. Tak, nasta³y dziwne czasy.}
{139} {} {Wódz Geronimo wie, co jest dobre, a co z³e dla plemienia.}
{140} {} {Geronimo... Niech s³oñce oœwietla twoje niebiañskie œcie¿ki.}

{150} {} {Ten dzieñ nadszed³. Phoenix podbi³o nasze plemiê.}
{151} {} {Misjonarze z Phoenix wykonali swoje zadanie.}
{152} {} {Najwy¿szy wódz podj¹³ decyzjê. Pozostaje nam byæ pos³usznymi.}
{153} {} {A co z pueblo? Czy musimy st¹d odejœæ?}
{154} {} {No có¿, czas, ¿eby przepiórki opuœci³y grzêdê.}
{155} {} {Tak czy inaczej, cieszê siê, s³ysz¹c o koñcu wojny.}
{156} {} {Mam nadziejê, ¿e Stra¿nicy dotrzymaj¹ s³owa.}
{157} {} {Modlê siê do duchów Pustkowi o zakoñczenie tej wojny.}
{158} {} {O Boski Braminie, poka¿ nam drogê!}
{159} {} {Gry Mrocznego Bramina wprowadzi³y nasze plemiê we mg³ê.}

{170} {} {Nie powinieneœ ruszaæ sam do Podziemnego Miasta.}
{171} {} {Czy to dlatego starsi zabronili nam schodziæ do katakumb?}
{172} {} {W katakumbach mieszka³ prawdziwy potwór.}
{173} {} {Chwa³a Boskiemu Braminowi! Opuœci³ nas z³y duch z lochu.}
{174} {} {Nic dziwnego, ¿e tak du¿o ostrzegali o Podziemnym Mieœcie.}
{175} {} {Wci¹¿ bojê siê zbli¿yæ do Podziemnego Miasta.}
