{100} {} {Widzisz Sida.}
{101} {} {Widzisz biznesmena w polowym ubraniu.}
{102} {} {Powodzenia w spotkaniu. Dziêkujê za pomoc w drodze.}
{103} {} {Droga wolna.}
{104} {} {Nie ma nikogo, kto móg³by zap³aciæ za pilnowanie karawany.}
{105} {} {Paskudny zdrajca!}
{106} {} {Dziêki rekonesansowi mog³eœ przejœæ niezauwa¿ony.}
{107} {} {Zmar³. Teraz nie ma nikogo, kto móg³by ci zap³aciæ za pilnowanie karawany.}

# Przed otrzymaniem zadania
{200} {} {Witaj wêdrowcze. Jestem Sid, kupiec. Wygl¹da na to, ¿e oboje utknêliœmy w tej dziurze, prawda?}
{1200} {} {Witam wêdrowcze. Jestem Sid, kupiec. Wygl¹da na to, ¿e oboje utknêliœmy w tej dziurze, prawda?}
{201} {} {Mia³em tutaj interesy. Ale wkrótce mnie tu nie bêdzie.}
{202} {} {Interesy, mówisz? W porz¹dku. Ale nawet jeœli masz dobre stosunki z ludem pueblo, plemiona na pustkowiach nie s¹ tak przyjazne. Czy myœlisz, ¿e mo¿esz bezpiecznie chodziæ po ich ziemiach?}
{203} {} {Czy masz jak¹œ propozycjê?}
{204} {} {Zgadza siê. Chcê odwiedziæ normalne, du¿e miasto, o którym tyle siê mówi.}
{205} {} {Dotarcie do Phoenix zajmuje tylko kilka dni. Ale to niebezpieczna droga. Powinieneœ pomyœleæ o eskorcie.}
{206} {} {Czy masz coœ na myœli?}
{207} {} {O tak. Przygotowujê karawanê do powrotu do Phoenix. Mam niewielu ludzi, a droga sta³a siê wyboista z powodu sprzeczek z misjonarzami. Obawiam siê, ¿e jak tylko wyjdziemy z pueblo, dzicy bêd¹ chcieli nas powstrzymaæ. Potrzebujê wiêkszego wsparcia. P³acê 500 kapsli za podró¿ do Phoenix. Pojedziesz z nami?}
{208} {} {Przemyœlê twoj¹ propozycjê.}
{209} {} {Wchodzê w to.}
{210} {} {Co wiezie Twoja karawana?}
{211} {} {Ró¿ne dzikie przybory, galanteriê skórzan¹, suszone miêso. Mia³em te¿ szczêœcie, ¿e mog³em targowaæ siê z Genaro o kilku braminów. Za ¿ywego bramina w mieœcie p³ac¹ fortunê.}
{212} {} {Czy bêdziemy musieli walczyæ po drodze?}
{213} {} {Mo¿liwe.}

{220} {} {Có¿, idziesz z nami?}
{221} {} {Nadal siê nie zdecydowa³em. Na razie - nie.}
{1221} {} {Nadal siê nie zdecydowa³am. Na razie -  nie.}
{222} {} {Tak, idê z wami.}

{230} {} {Mi³o ciê widzieæ w zespole. Przygotuj siê do drogi i wróæ do mnie.}
{231} {} {Dobrze.}
{232} {} {Mogê ju¿ ruszaæ.}

# Po otrzymaniu zadania
{250} {} {Cholera, ci dzicy nam nie odpuszcz¹! Musimy siê ich jakoœ pozbyæ.}
{251} {} {Te Radskorpiony zabij¹ wszystkie nasze zwierzêta! Musisz coœ zrobiæ!}
{252} {} {Zasadzka! Ca³a grupa! Chroñ moje towary!}
{253} {} {Rozumiem.}
{254} {} {Droga wydaje siê wolna. Czy jest ju¿ bezpiecznie? W takim razie jedŸmy dalej.}
{255} {} {Daj mi jeszcze minutê i mo¿emy ruszaæ.}
{256} {} {Ok, mogê iœæ.}
{257} {} {Cholera! Nie mamy ju¿ braminów. Bêdziemy musieli zrzuciæ czêœæ ³adunku, a resztê przenieœæ rêcznie. Wygl¹da na to, ¿e nic nie zarobiê na tej wyprawie. Albo co gorsza wyjdê na minus.}
{258} {} {Ale MY nadal ¿yjemy. JedŸmy dalej.}
{259} {} {Poczekaj chwilê, musze siê przygotowaæ do podró¿y.}

{260} {} {Dziêkujê za wspó³pracê. Mi³o mi siê z tob¹ robi interesy. Oto 500 kapsli, zgodnie z obietnic¹. I prawdopodobnie nie wrócê do San Brahmin przez kilka lat, dopóki nie opadnie tam kurz. Có¿, rozumiesz.}
{261} {} {Powodzenia Sid.}
{262} {} {Dziêkujê za wspó³pracê. Ale z powodu utraty braminów i ³adunku nie bêdê w stanie zap³aciæ pe³nej kwoty. Tutaj, }
{263} {} {kapsli za pracê. I prawdopodobnie nie wrócê do San Brahmin przez kilka lat, dopóki nie opadnie tam kurz. Có¿, rozumiesz.}
{264} {} {Hej, czy mo¿emy zrobiæ po drodze rekonesans?}
{265} {} {Jedziemy za wolno. Nie mamy wystarczaj¹cych zapasów i cierpliwoœci. Musimy siê poœpieszyæ.}
{266} {} {Hej, czy mo¿emy zbadaæ ruiny przed nami? Wyprawa zajmie nam wiêcej czasu, ale mamy wiêksze szanse na przetrwanie.}
{267} {} {Mia³em nadziejê, ¿e dotrê do miasta przed zachodem s³oñca, ale masz racjê. Smia³o, póŸniej nadrobimy zaleg³oœci.}
{268} {} {Dobrze.}
{269} {} {Nie, jeszcze nie mogê nigdzie iœæ.}
{270} {} {To te¿ mo¿e byæ niebezpieczne. Mogê iœæ na zwiad.}
{271} {} {Chcesz iœæ samemu i umrzeæ? Nie wyg³upiaj siê. Razem bêdzie nam ³atwiej przetrwaæ.}
{272} {} {To te¿ mo¿e byæ niebezpieczne. Pójdê dalej i oceniê sytuacjê.}
{273} {} {Uwa¿aj. Straci³em ju¿ kilka osób. Nie chcê straciæ i ciebie.}
{274} {} {Zróbmy to. Czekaj na mój sygna³...}
{275} {} {Hmm. Sami jesteœmy ³atwym celem. Poruszajmy siê razem.}
{276} {} {Muszê siê przygotowaæ. Poczekaj minutê.}