{100} {} {Widzisz wojownika plemiennego.}
{101} {} {Widzisz smag³ego mê¿czyznê z barwami wojennymi na ca³ym ciele.}

{120} {} {Walczê za swoje plemiê. A ty?}
{121} {} {Jeœli umrê, skoñczê na Wielkich Niebiañskich Pastwiskach.}
{122} {} {Boski Bramin bêdzie mnie strzeg³ w bitwie.}
{123} {} {Wygramy, jeœli bêdziemy walczyæ ramiê w ramiê.}
{124} {} {Po której jesteœ stronie?}
{125} {} {Plemiê zapamiêta nasze zwyciêstwa.}
{126} {} {Bêdê broni³ pueblo przed najeŸdŸcami do koñca.}
{127} {} {Niech wrogowie dr¿¹ przed moj¹ w³óczni¹.}
{128} {} {Swiêty amulet z koœci braminów bêdzie mnie chroni³.}
{129} {} {Szaman mówi, ¿e zaczarowa³ moje amulety.}
