{100} {} {Widzisz kobietê.}
{101} {} {Widzisz jedn¹ z kobiet z plemienia. Jest zajêta przygotowywaniem jedzenia.}

{210} {} {Czego chcesz?}
{211} {} {Czuj siê jak w domu, bohaterze.}
{212} {} {Zaproszono ciê tutaj?}
{213} {} {Do widzenia.}

{220} {} {Co tu tak pachnie?}
{221} {} {Przygotowywujê podroby braminów. Rêce przy sobie! Nie pozwolê ci nawet wylizaæ talerza. Spadaj st¹d!}
{222} {} {OK, ok.}
{223} {} {Przygotowywujê podroby braminów. Moje ulubione, ale przyprawy s¹ trudne do zdobycia.}
{224} {} {Pachnie niesamowicie! Mogê spróbowaæ?}
{225} {} {Co to za zapach? Czy to w ogóle jest jadalne?}
{226} {} {Dla naszego bohatera wszystko. Proszê, czêstuj siê.}
{227} {} {Dziêki.}
