{100} {} {Widzisz Lozennê.}
{101} {} {Widzisz staruszkê w nietypowym dla swojego plemienia stroju. Mamrocze coœ pod nosem, prawdopodobnie jakieœ zaklêcie.}

{200} {} {Wiedzia³am, ¿e kiedyœ tu przyjdziesz. Masz smutn¹ historiê.}
{201} {} {Sk¹d wiesz?}
{202} {} {Widzê du¿o, mówi mi o tym krew œwiêtego zwierzêcia. Nazywam siê Lozen.}
{203} {} {Wiêc czytasz krew braminów czy coœ?}
{204} {} {Widzê przysz³oœæ i przesz³oœæ. Nazywaj to jak chcesz. Poka¿ mi rêce, spojrzê te¿ i na twoj¹ przysz³oœæ.}
{205} {} {Nie, nie.}
{206} {} {OK, spójrz.}
{207} {} {Hmm... Nadchodz¹ du¿e zmiany. I widzê, ¿e bêdziesz w samym ich centrum. Ale muszê wykonaæ pe³ny rytua³, aby poznaæ szczegó³y.}
{208} {} {Mo¿e innym razem.}
{209} {} {OK, ³apiê. Co jest do tego potrzebne?}
{210} {} {Musisz rozstaæ siê z czymœ, co jest dla ciebie cenne. Mo¿esz nawet oddaæ mi swoje kapsle. Jedynie w obliczu straty ods³aniaj¹ siê najg³êbsze linie ¿ycia.}
{211} {} {Oto 100 kapsli. Powiedz mi co widzisz, chcê wiedzieæ wszystko!}
{212} {} {Mo¿e innym razem.}
{213} {} {(wykonuje skomplikowany rytua³ na krwi œwiêtego zwierzêcia) Um-um... Om-um... Zaczynam widzieæ... Tak...}
{214} {} {Co widzisz?}
{215} {} {Widzê ludzi z gwiazdami na czo³ach... I ludzi, którzy tworz¹ ogieñ moc¹ myœli naprzeciw nich... Chc¹ siê zniszczyæ, a ty jesteœ miêdzy nimi. Na linii ognia...}
{216} {} {Nie brzmi to dobrze.}
{217} {} {Ale Boski Bramin nie pozwoli ci umrzeæ w tej bitwie. Masz swój w³asny cel! Nie daj siê zwieœæ! Czeka na Ciebie Wielka Misja! Wspania³a!!!}
{218} {} {Ugh, to by³o doœæ interesuj¹ce. Ale jak mam to wszystko rozumieæ?}
{219} {} {Zartujesz sobie! To nie jest wizja przysz³oœci.}
{220} {} {Pomyœl o tym, co mówiê! Boski Bramin nie udziela bezpoœrednich instrukcji, wskazuje jedynie obrazy, które trzeba umieæ czytaæ. Ten czas mo¿e jeszcze nie nadszed³. Kiedy twoje serce i umys³ siê otworz¹, zrozumiesz to.}
{221} {} {Wszystko jest dla mnie jasne. Po prostu zmarnowa³em kapsle. Narazie.}
{1221} {} {Wszystko jest dla mnie jasne. Po prostu zmarnowa³am kapsle. Narazie.}
{222} {} {Dziêkujê, Lozen. Twoje s³owa inspiruj¹ na dalszej œcie¿ce.}
{223} {} {Wróci³eœ. Widzê, ¿e los ciê niepokoi. Mogê dowiedzieæ siê, co Ciê czeka, jeœli chcesz.}
{1223} {} {Wróci³aœ. Widzê, ¿e los ciê niepokoi. Mogê dowiedzieæ siê, co Ciê czeka, jeœli chcesz.}
{224} {} {Nie, dziêkujê, nie.}

{240} {} {Nie mam ci nic wiêcej do powiedzenia.}
{241} {} {OK. Do widzenia.}
{242} {} {Mimo to, jak rozumiesz swoj¹ wizjê?}
{243} {} {Co siê sta³o z braminem, którego krwi u¿ywasz?}
{244} {} {Swiête zwierzê. Genaro przygotowuje je do obchodów Dnia S³oñca. W tym dniu zwierzê zostaje z³o¿one w ofierze, a pech i wstyd s¹ zmywane jego œwiêt¹ krwi¹. U¿ywam krwi do przepowiadania przysz³oœci, aby zobaczyæ nasz¹ mo¿liw¹ przysz³oœæ i przekazaæ to pozosta³ym mieszkañcom.}
{245} {} {Co to za œwiêto?}
{246} {} {Kiedy burze piaskowe pokrywaj¹ pustyniê Sonora, pasterze nie mog¹ wyjœæ, by paœæ braminy. W pueblo przeczekuj¹ sezon burz. W te dni, kiedy mamy wystarczaj¹co du¿o po¿ywienia, dziêkujemy Boskiemu Braminowi za nasze zbawienie.}
{247} {} {Co to za œwiête zwierzê? Czy ró¿ni siê w jakiœ sposób od reszty?}
{248} {} {To bramin z najwiêkszym hartem ducha. Genaro trzyma go na oddzielnym wybiegu, aby unikn¹æ niepotrzebnego ryzyka i pozwoliæ braminowi ¿yæ do Dnia S³oñca. Smieræ lub kalectwo takiego zwierzêcia by³aby dla nas tragedi¹.}
{249} {} {Nie szkoda Ci tego œwiêtego zwierzêcia?}
{250} {} {Nie gadaj bzdur! Braminy poœwiêcaj¹ siê za nas, ludzi. Genaro wybiera jednego z Braminów i karmi go szczególnie dobrze przez ca³y rok. Ca³y rok czystego, dobrze od¿ywionego, szczêœliwego ¿ycia, aby w jeden dzieñ umrzeæ i zapewniæ odkupienie ca³emu plemieniu. Godny los dla zwierzêcia.}
{251} {} {Jak¹ przysz³oœæ widzisz dla swojego plemienia?}
{252} {} {Stoimy miêdzy urwiskiem a przepaœci¹ we mgle. Trudno to zobaczyæ.}
{253} {} {Ciekawe.}
