{101} {} {Widzisz pasterza.}
{102} {} {To jeden z lokalnych pasterzy. Jego twarz wygl¹da znajomo.}

{200} {} {Hej, popatrzcie, kto nas odwiedza! Znam tego nieznajomego. Próbowa³ nam zabraæ Braminy w pobli¿u Garage City.}
{201} {} {Tak. Ale wszystko siê dobrze skoñczy³o, prawda? Przynajmniej nadal ¿yjesz.}
{202} {} {Hmm... Czyli uda³o ci siê odnalezæ najeŸdŸców? Mimo wszystko - nie lubiê ciê. Nie oczekuj zbyt wiele. Miejmy nadziejê, ¿e wkrótce zostaniesz wyrzucony z pueblo.}
{203} {} {No co ty...}
{204} {} {Nie miej nadziei.}
{205} {} {Nie wiem, o czym mówisz.}
{206} {} {Naprawdê? Dobra... Sam nie pamiêtam twarzy najeŸdŸców. W porz¹dku. Ale bêdê Ciê mia³ na oku, nieznajomy.}
{207} {} {Dziêki. Zaufaj mi, nie mamy powodu byæ wrogami.}
{208} {} {Nie myœl, ¿e bojê siê twoich gróŸb.}
{209} {} {Co ty, to pomy³ka, wcale mnie tam nie by³o...}
{210} {} {No dalej, wymyœlaj bajki. Dok³adnie pamiêtam twoj¹ twarz, draniu!}
{211} {} {OK, to by³ b³¹d. Myœla³em, ¿e braminy by³y dzikie...}
{212} {} {Tak. Dzikie. Na pewno. Mangas i inni sprzeciwiaj¹ siê takim zachowaniom. Mam nadziejê, ¿e wkrótce wylecisz z pueblo, z³odzieju. W przeciwnym razie nie mogê rêczyæ za siebie!}
{213} {} {Co zamierzasz teraz zrobiæ?}
{214} {} {Powiem innym, kim naprawdê jesteœ. Nie myœl, ¿e ujdzie ci to na sucho, z³odzieju. Mam nadziejê, ¿e wkrótce zostaniesz wyrzucony z pueblo. W przeciwnym razie nie mogê rêczyæ za siebie!}
{215} {} {Do widzenia, przyjacielu.}

{220} {} {No dalej, idŸ sobie gdzieœ indziej, chwaœcie.}
{221} {} {Czeœæ. Okazuje siê, ¿e robisz wiele dobrego dla plemienia. Przepraszam, myli³em siê co do ciebie.}
{222} {} {Do widzenia.}
