{100} {} {Widzisz Kap³ana Genaro.}
{101} {} {Widzisz szamana w stroju ludowym.}
{102} {} {IdŸ w pokoju, dziwny ¿elazny duchu.}

{200} {} {Pozdrowienia dla ciebie i twojego plemienia. Czy to o tobie szepcz¹ ludzie w San Brahmin? Nie wiem, jak ciê traktowaæ, ale nie sprzeciwiam siê twojej obecnoœci.}
{201} {} {Naprawdê?}
{202} {} {Uszczêœliwi³eœ mnie, staruszku.}
{203} {} {Czêsto robiê interesy z obcymi ze wschodu, w przeciwieñstwie do reszty klanów w plemieniu. Czas poka¿e, czy mo¿na Ci zaufaæ.}
{204} {} {Dziêki za goœcinê.}
{205} {} {Niemi³e to pierwsze powitanie.}

{210} {} {Ta rzecz, na której jeŸdzisz, przerazi³a wszystkie moje braminy! Nastêpnym razem wybierz inn¹ drogê, g³upcze.}
{1210} {} {Ta rzecz, na której jeŸdzisz, przerazi³a wszystkie moje braminy! Nastêpnym razem wybierz inn¹ drogê.}
{211} {} {Przepraszam. Nie chcia³em sprawiaæ Ci ¿adnych k³opotów.}
{1211} {} {Przepraszam. Nie chcia³am sprawiaæ Ci ¿adnych k³opotów.}
{212} {} {No to masz problem. To nie moja wina, ¿e twoje braminy s¹ takie p³ochliwe.}

{220} {} {Widzê, ¿e nie zamierzasz jeszcze opuœciæ pueblo. Co ciê tu trzyma, przyjacielu?}
{221} {} {Widzê, ¿e nie zamierzasz jeszcze opuœciæ pueblo. Czego chcesz?}
{222} {} {Pozdrowienia, przyjacielu wschodniego plemienia. Jak mogê ci pomóc?}
{223} {} {Do zobaczenia Genaro.}

{230} {} {Proszê ciê, abyœ popar³ sojusz z misjonarzami z Phoenix.}
{231} {} {W przeciwieñstwie do reszty starszych, nie mam uprzedzeñ do ludzi z Phoenix. Mój klan spêdza³ z nimi sporo czasu handluj¹c. Ale nie jestem gotowy, by walczyæ z reszt¹ plemienia. Mo¿e jeszcze nie nadszed³ czas.}
{232} {} {Jeœli starsi siê nie dogadaj¹ to ta wojna dobrze siê nie skoñczy.}
{233} {} {Nie doceniasz plemienia. Mamy bogate doœwiadczenie bojowe i dobrze znamy Pustkowia Sonory. Armia Phoenix ugrzêŸnie w tej walce przez d³ugi czas, jeœli kiedykolwiek odwa¿y siê przejœæ na drogê wojny.}
{234} {} {Twoje s³owa brzmi¹ przekonuj¹co. Zapomnij o tym, co ci powiedzia³em.}
{1234} {} {Twoje s³owa brzmi¹ przekonuj¹co. Zapomnij o tym, co ci powiedzia³am.}
{235} {} {Skazujesz swoje plemiê na wojnê. Zapamiêtaj moje s³owa.}
{236} {} {Byæ mo¿e twój g³os nie wystarczy, ¿eby coœ zmieniæ. Ale nie chcesz wojny z Phoenix, prawda?}
{237} {} {Plemiê mo¿e stan¹æ w obronie siebie, ale ta wojna nie bêdzie mia³a koñca. I któregoœ dnia zakoñczy siê pora¿k¹ rozwijaj¹cej siê technologii misjonarzy.}
{238} {} {Czy zgadzasz siê ze mn¹?}
{239} {} {Nie mam nic przeciwko handlowaniu z Phoenix. Reszta starszych nie rozumie, ¿e œwiat siê zmieni³. Lepiej jest teraz wejœæ w now¹ erê z pe³n¹ si³¹, ni¿ skazaæ nasz naród na wieczn¹ wojnê. Mo¿esz liczyæ na moje wsparcie w radzie starszych.}
{240} {} {Dokonujesz w³asciwego wyboru, szamanie Genaro.}
{241} {} {Có¿, rozumiem ciê...}
{242} {} {Uratowa³eœ dzieci i byd³o przed z³ym duchem. Jak mogê pomóc?}
{1242} {} {Uratowa³aœ dzieci i byd³o przed z³ym duchem. Jak mogê pomóc?}
{243} {} {Wiêc mogê na ciebie liczyæ?}
{244} {} {Boski Bramin musia³ mnie ukaraæ, odbieraj¹c ¿ycie Swiêtemu Braminowi tu¿ przed Dniem S³oñca. To znak. W ten sposób wskazuje mi, ¿e wybra³em z³¹ œcie¿kê.}
{245} {} {Teraz wiesz, co robiæ, prawda?}
{246} {} {Swietnie. Ale nie œpieszmy siê. Do zobaczenia.}
{247} {} {To smutne. Ale nie œpieszmy siê, dobrze?}

{250} {} {Opowiedz mi o sobie.}
{251} {} {Jestem starszym z zachodnich klanów naszego plemienia. Mam na imiê Genaro.}
{252} {} {Witaj Starszy Genaro.}
{253} {} {Kto kieruje pozosta³ymi?}
{254} {} {Najwy¿szym przywódc¹ plemienia jest Geronimo. Jest m¹drym i utalentowanym strategiem, wielkim zjednoczycielem plemienia. Znajdziesz go w du¿ym domu z filarami.}
{255} {} {Co tutaj robisz?}
{256} {} {Spêdzam du¿o czasu w San Brahmin. Konieczne jest pilnowanie Braminów przy ich wypasie, przygotowanie ich na przysz³y los, na koniec organizujê œwiêta w Dzieñ Wielkiego S³oñca. Ale pracy jest coraz wiêcej, z trudem sobie radzê.}
{257} {} {Rozumiem.}
{258} {} {Mo¿e mogê ci pomóc?}
{259} {} {Wygl¹da na to, ¿e musia³eœ ju¿ wczeœniej uprawiaæ kukurydzê, prawda? Oznacza to, ¿e praca z ziemi¹ nie powinna byæ dla Ciebie ciê¿arem. WeŸ ³opatê do zagrody i wyczyœæ j¹ z... brudu braminów. Braminy w niewoli musz¹ byæ czyste. Zw³aszcza te, które wybra³em na obchody Dnia S³oñca.}
{260} {} {Ok. Zrobiê to. Mam nadziejê, ¿e przynajmniej nakarmisz mnie œwie¿ym miêsem bramina.}
{261} {} {Co? Mam sprz¹taæ gówna braminów?}
{262} {} {Czy to dla ciebie taki problem? Có¿, nie mogê zaoferowaæ ci innej pracy. Z trudem poradzi³byœ sobie z wypasem lub opiek¹ nad braminami. Szczerze mówi¹c, staram siê w ogóle nie wpuszczaæ obcych do zagrody. Szkoda, ¿e nie doceniasz pok³adanego w tobie zaufania.}
{263} {} {Myœlê, ¿e sobie ze mnie ¿artujesz. Szukaj g³upców gdziœ indziej.}
{264} {} {Wszystko wyczyszczone.}
{265} {} {Rozumiem. Wykona³eœ dobr¹ robotê.}
{1265} {} {Rozumiem. Wykona³aœ dobr¹ robotê.}
{266} {} {Zartujesz sobie ze mnie? Jestem po uszy w gównie braminów!}
{267} {} {Och, dziêki, uwielbiam wykonywaæ swoj¹ pracê bez zarzutu.}
{268} {} {Po tego rodzaju pracy nie wachaj siê karmiæ i spaæ w moim namiocie. WeŸ to jedzenie. Dobrze zaspokaja g³ód w drodze i nie psuje siê przez bardzo d³ugi czas.}
{269} {} {Dziêki.}
{270} {} {Mhm... lepiej nie œmiej siê za moimi plecami.}

{280} {} {W Villi kr¹¿y³y plotki o pas¹cych siê byd³ach Vaqueros.}
{281} {} {Hmm?}
{282} {} {Te historie spowodowa³y wiele zamieszania. Jak oswoi³eœ te wœciek³e Braminy?}
{283} {} {Niewa¿ne, zapomnij.}
{284} {} {Nie zawsze takie by³y. Kilka pokoleñ temu braminy by³y zwyk³ymi zwierzêtami domowymi. Legendy mówi¹, ¿e Niebo ukara³o ludzi za ich przewinienia, doprowadzaj¹c zwierzêta do szaleñstwa.}
{285} {} {Kontynuuj, szamanie Genaro.}
{286} {} {Braminy rozproszone po pustyni odmówi³y powrotu do swoich domów i ukrywa³y siê przed ludŸmi. Ich temperament sta³ siê dziki. Ale nasi przodkowie zachowali kilka Braminów poprzez modlitwy i ofiary sk³adane Boskiemu Braminowi.}
{287} {} {Dziêki za historie.}
{288} {} {Dlaczego bramin potrzebuje drugiej g³owy?}
{289} {} {(wzrusza ramionami ze zdziwieniem) Drogi Boskiego Bramina s¹ nieodgadnione. Ale wierzê, ¿e w ten sposób dwa Braminy po³aczy³y siê w jedno cia³o, aby zapewniæ sobie lepsz¹ ochronê przed ludŸmi i zwierzêtami.}
{290} {} {Ma to sens. Za pomoc¹ dwóch g³ów ³atwiej jest œledziæ sytuacjê.}
{291} {} {Znajdujesz nawet boskie wyjaœnienie dla zwyk³ej brzydoty. Jest w tym coœ niezdrowego...}

{300} {} {Czy mogê kupiæ bramina?}
{301} {} {Rozejrzyj siê. Z powodu wojny czasowo zawiesiliœmy handel Braminami oraz ich miêsem i skórami.}
{302} {} {Szkoda. Czy mo¿emy porozmawiaæ o czymœ innym?}
{303} {} {Wojna siê skoñczy³a i wznowiono handel. Czyli chcesz kupiæ ca³ego bramina? To bêdzie Ciê bardzo drogo kosztowaæ.}
{304} {} {Tak, potrzebujê ca³ego ¿yj¹cego bramina.}
{305} {} {W zagrodzie s¹ tylko trzy na sprzeda¿ - Breezy, River i Sierra. Ale najpierw poka¿, ¿e masz czym zap³aciæ. Nastêpnie weŸ ten owoc i daj Braminowi, którego chcesz.}
{306} {} {Dziêki, Genaro.}

{310} {} {Powiedz mi, czym jest to Pogrzebane Miasto, o którym mówi¹ dzieciaki?}
{311} {} {Nie idŸ tam sam. To miejsce jest nam nieznane. Czasami znajdujemy tam koœci zwierz¹t, a czasem nawet szcz¹tki ludzkie. Nawet Duchy nie chc¹ mi zdradziæ sekretu tego miejsca.}
{312} {} {Czy to dlatego zabraniasz dzieciom tam chodziæ?}
{313} {} {Kto wie, jakie staro¿ytne z³o czai siê w mrocznych i zagmatwanych lochach starego pueblo?}
{314} {} {Rozumiem. Dziêki za wyt³umaczenie.}
{315} {} {Oto nasz bohater. Wiem o twoich wyczynach w Pogrzebanym Mieœcie. Dzieci siê przyzna³y. Co tam znalaz³eœ?}
{1315} {} {Oto nasza bohaterka. Wiem o twoich wyczynach w Pogrzebanym Mieœcie. Dzieci siê przyzna³y. Co tam znalaz³aœ?}
{316} {} {Wiem, co czai³o siê w Pogrzebanym Mieœcie. Ludzie i Braminy byli porywani przez potwora.}
{317} {} {To straszne! Od dawna próbowaliœmy zrozumieæ, kto porywa nasze byd³o, ale ten mroczny duch umiejêtnie ukrywa³ siê przed oczami mojego or³a. A jednak istnieje.}
{318} {} {Ciemny duch odszed³. Nie bêdzie wam ju¿ przeszkadza³.}
{319} {} {Chwa³a niebu! Sam Boski Bramin musia³ ciê do nas wys³aæ. Dziêkujê przyjacielu. Twoje czyny bêdziemy pamietaæ przez pokolenia.}
{320} {} {O tak, ju¿ widzê dzieci zebrane wokó³ ognia. I szamana w centrum, który opowiada im o mnie... Niestety, ale ja muszê ju¿ iœæ. Istnieje jeszcze wiele istnieñ do uratowania.}