{100} {} {Widzisz Kap³ana Mangasa.}
{101} {} {Widzisz szamana w stroju ludowym.}
{102} {} {Patrzcie! To ten z³y duch ¿elaza! Wierzycie mi teraz?}
{103} {} {Stary Mangas zupe³nie zwariowa³!}

# Plywajace frazy w kwadracie
{110} {} {Wypêdziæ obcych!}
{111} {} {Obcy rozdzieraj¹ nasze plemiê!}
{112} {} {Zobacz, co ci ludzie z zewn¹trz robi¹ dla naszej spo³ecznoœci!}
{113} {} {Od tylu pokoleñ dbamy o nasze tradycje, aby nikt z zewn¹trz nie móg³ ich zniszczyæ!}
{114} {} {Teraz s¹ wœród nas dysydenci. Dok¹d to prowadzi?}
{115} {} {Plemiê wróci³o na œcie¿kê wojny. A to wszystko z powodu Phoenix.}
{116} {} {Byliœmy jednoœci¹, ale Phoenix nauczy³o nas spieraæ siê o drobiazgi!}
{117} {} {Spójrzcie na Chatto i jego towarzyszy. Nie mo¿na ich ju¿ naprawiæ!}
{118} {} {Chatto nauczy³ siê czytaæ od ludzi z karawany. A co bêdzie dalej?}
{119} {} {Gorzej! Phoenix nie da nam ani kawa³ka pustkowi. Aaron potrzebuje wszystkiego!}
{120} {} {Z powodu misjonarzy nie mo¿emy nawet wyjœæ na pustkowia, aby wypasaæ Braminy.}
{121} {} {Przynieœcie tutaj wszystkie pogañskie rzeczy! Spalcie je! Spalcie je!}
{122} {} {Spójrz na te ksi¹¿ki i technologie - czy naprawdê tego potrzebujemy?}
{123} {} {Phoenix obiecuje same k³amstwa!}
{124} {} {Nie daj siê zwieœæ misjonarzom!}
{125} {} {Zakryj uszy, kiedy misjonarze ci coœ wyjaœniaj¹.}
{126} {} {Mieszkamy tu od pokoleñ! Nie oddamy naszej ziemi obcym!}

# Przestan rozmawiaæ o rowerze
{200} {} {Tutaj! O tym w³aœnie mówi³em! Obcy ujarzmili ¿elazo! Bawi¹c siê w Boga, wskrzesili stare technologie i poddali je swojej woli. Co dalej? Czy teraz podbij¹ nasze cia³a i dusze?}
{201} {} {Nie martw siê. To tylko mój motor. Nie gryzie!}
{202} {} {Nie wierzcie s³owom obcego! Kto wie, co myœli ktoœ, kto sprzeciwia siê naturze.}
{203} {} {Nie przesadzaj, jesteœ za mocno do przodu.}
{204} {} {Myœlê, ¿e przesadzi³eœ z zio³em, szamanie.}
{205} {} {Spokojnie, staruszku. Nie zrobi³em ci nic z³ego. JESZCZE NIE.}
{1205} {} {Spokojnie, staruszku. Nie zrobi³am ci nic z³ego. JESZCZE NIE.}

#Pierwsze spotkanie
{210} {} {...Zobaczcie, co ci *rozwiniêci* ludzie przynieœli nam razem ze swoim postêpem!}
{211} {} {[Pos³uchaj mowy]}
{212} {} {[Przewij mu.]}
{213} {} {Byliœmy zwart¹ spo³ecznoœci¹, ale czciciele ognia przynieœli nam egoizm! Wierzyliœmy w jednego Boga, ale nauczyli nas spieraæ siê o religie! Chcieliœmy dobra dla naszych wspó³plemieñców, ale klany ponownie wkroczy³y na œcie¿kê wrogoœci...}
{214} {} {Phoenix nauczy³o nas handlowaæ Braminami jak przedmiotami, chocia¿ te zwierzêta s¹ œwiête. Jak d³ugo jeszcze obcy bêd¹ niszczyæ nasze fundamenty? Ile wiêcej konfliktów w plemieniu wywo³aj¹ przez samo pojawienie siê na naszych ziemiach?}
{215} {} {Teraz spójrzcie na Chatto. Nauczy³ siê od karawan czytaæ pogañskie teksty. Czytaæ! Wzywa do wymiany Braminów na bezduszne obce technologie. On i jego przyjaciele chc¹ zamieniæ nasz¹ wolnoœæ na sojusz z Phoenix. Chc¹ oddaæ pueblo w rêce misjonarzy!}
{216} {} {Spójrzcie na te pogañskie rzeczy - ksi¹¿ki, technologie, w¹tpliwe i niebezpieczne substancje... Zawsze je odrzucaliœmy, poniewa¿ s¹ niebezpieczne, a nie ma nic cenniejszego ni¿ ¿ycie plemienia i Braminów. A teraz Chatto wraz ze swoimi towarzyszami zbiera pogañskie talizmany i próbuje je czytaæ. Mroczny Bramin zaw³adn¹³ umys³ami naszych dzieci!}
{217} {} {To jest nasza przysz³oœæ? Kiedy upadliœmy tak nisko, ¿e nawet m³odzie¿ wyst¹pi³a przeciwko plemieniu? To wina misjonarzy! WypêdŸmy ich! Pueblo musi pozostaæ nasze...}
{218} {} {Och, widzê nieznajomego w pueblo. Kim jesteœ? Co robisz w obcym plemieniu?}
{219} {} {Och, widzê czciciela ognia w pueblo. Czego chcesz? Zabraæ nasze dzieci i Braminy? Odpowiedzieliœmy ju¿ waszym poprzednikom, ¿e plemienia San Brahmin nie mo¿na kupiæ, tak jak to zrobiliœcie z innymi. Wracaj do swojego cuchn¹cego Phoenix, szarlatanie!}
{220} {} {Idê do wodza w imieniu Villi. Nana porêczy³a za mnie.}
{221} {} {Ach, Braminie Boskiego Odpoczynku! Jeœli Nana wpuszcza nieznajomego, musi byæ ku temu jakiœ powód. OK, wejdŸ. Ale pamiêtaj, ¿e nic nie ukryje siê przed moim orlim okiem. Bêdê obserwowa³ ka¿dy Twój krok w pueblo.}
{222} {} {Dziêki, Mangas. Proszê, nie z³oœæ siê na mnie za moje wtargniecie.}
{223} {} {Chyba oszala³eœ na staroœæ. Zostaw mnie w spokoju i daj mi przejœæ.}
{224} {} {Do zobaczenia, Mangas.}
{225} {} {[Dalej.]}

# Powtarzajacy siê dialog
{230} {} {Pozdrowienia, przybyszu z Villi.}
{1230} {} {Pozdrowienia, kobieto z Villi.}
{231} {} {Jestem zaniepokojony twoim mrocznym duchem w krainie mojego plemienia.}
{232} {} {Do zobaczenia, szamanie.}

{240} {} {Kim jesteœ?}
{241} {} {Nazywam siê Mangas. Jestem wodzem klanu wschodniego.}
{242} {} {Mi³o ciê poznaæ, Mangas, wodzu wschodniego plemienia.}
{1242} {} {Mi³o ciê poznaæ, Mangas, wodzu wschodniego plemienia.}
{243} {} {Ktoœ tu musi rz¹dziæ tym wszystkim, prawda?}
{244} {} {Mówisz o Najwy¿szym Wodzu Geronimo. Jest w Sanktuarium. Wodzowie ka¿dego klanu zebrali siê w San Brahmin i wybrali go na naszego przedstawiciela.}
{245} {} {Wiêc dlaczego jesteœ tutaj, a nie na wschodzie?}
{246} {} {Walka z obcymi z Phoenix zmusi³a ca³e plemiê do zebrania siê w San Brahmin, aby broniæ naszej wolnoœci i naszych wartoœci. Poza tym to pueblo zawsze by³o nasz¹ sezonow¹ przystani¹ podczas burz piaskowych i susz.}
{247} {} {Czy sami zbudowaliœcie to pueblo? Wygl¹da bardzo staro.}
{248} {} {Te ruiny by³y tu od zawsze odk¹d pamiêtam. Piasek przykrywa³ je od pokoleñ i nikt nie wie, jak wygl¹da³o to miejsce wczeœniej. Teraz jest to nasz g³ówny obóz.}
{249} {} {OK, ale zajmiemy siê tym póŸniej.}

{250} {} {Co siê tu dzieje?}
{251} {} {Chatto i inni ch³opcy zbierali zakazane przedmioty. Znalaz³em je i zamierzam je spaliæ, aby inni nie poszli w ich œlady. I nie próbuj przynosiæ nam nowych. To nie twoja sprawa, obcy z Villi.}
{1251} {} {Chatto i inni ch³opcy zbierali zakazane rzeczy. Znalaz³em je i zamierzam je spaliæ, aby inni nie poszli w ich œlady. I nie próbuj przynosiæ nam nowych. To nie twoja sprawa, kobieto z Villi.}
{252} {} {Rozumiem.}
{253} {} {Ale co jest nie tak z tymi starymi rzeczami?}
{254} {} {Wêdrujemy po pustyni i ¿yjemy z tego, co daje nam pustynia. Jedyn¹ cenn¹ rzecz¹ s¹ nasi ludzie i nasze stada. Nie ma potrzeby, aby m³odzi ludzie przywi¹zywali siê do rzeczy starego œwiata. S¹ one bezu¿yteczne i niepewne.}
{255} {} {Cokolwiek powiesz. Czy mogê zabraæ te rzeczy?}
{256} {} {Gadasz bzdury. To tylko stare rzeczy, pe³no ich w ruinach.}
{257} {} {Ale my nie mieszkamy w tych ruinach! Wêdrujemy po pustyni Sonora. Tylko nasi ludzie i nasze stada s¹ dla nas cenne. Nie ma potrzeby, aby m³odzi ludzie przywi¹zywali siê do rzeczy starego œwiata. To bardzo niebezpieczne.}
{258} {} {Cokolwiek powiesz. Co powiesz na wymianê? Mogê je st¹d wynieœæ z powrotem do ruin.}
{259} {} {Masz racjê. Szkoda, ¿e nie mamy wiêcej ludzi w Villi, takich jak ty, szamanie Mangas. Masz mój szacunek.}
{260} {} {Hmm. Jeœli naprawdê jesteœ z Villi, o której s³ysza³em, powinienem traktowaæ ciê bardziej przychylnie. Byæ mo¿e nasze plemiona s¹ nieco podobne.}
{261} {} {Nie pal tych rzeczy. Mo¿e mogê je wymieniæ na coœ i zabraæ?}
{262} {} {Nie obchodzi mnie, co siê stanie z tymi pogañskimi talizmanami. O wiele wa¿niejsze jest nauczenie apostatów lekcji i pokazanie innym prawdy. Ale w sumie chcia³bym skorzystaæ z wymiany, jeœli naprawdê masz coœ do zaoferowania.}
{263} {} {Myœlê, ¿e mo¿emy siê dogadaæ.}
{264} {} {Te rzeczy naprawdê s¹ niebezpieczne.}
{265} {} {Wiem! Mówiê o tym samym! Rzeczy nieznajomych przynosz¹ choroby, niezgodê, a nawet œmieræ.}
{266} {} {Spal je! Spal je wszystkie! Natychmiast! Zw³aszcza t¹. [Pokazujesz na granat]}
{267} {} {Wykonujesz œwietn¹ robotê dla swojego plemienia.}
{268} {} {Czy chcia³byœ wymieniæ je na coœ po¿ytecznego?}
{269} {} {Spójrz, ta rzecz ma demoniczne moce! Spal j¹ natychmiast! [Wrzuæ granat do ognia]}

{270} {} {O co chodzi z tym konfliktem z obcymi?}
{271} {} {Przynosz¹ zamieszanie i niezgodê plemieniu. Ich bezduszne technologie s¹ sprzeczne z naszymi przymierzami, a swoj¹ broni¹ obcy próbuj¹ nas podbiæ i zmusiæ do pracy. Nawet ognista woda sta³a siê przedmiotem sporu.}
{272} {} {Rozumiem. Pozwól, ¿e zapytam Ciê o coœ innego.}
{273} {} {Zamieszanie i niezgoda? Kto jest przeciwko komu?}
{274} {} {Misjonarze z Phoenix chc¹ sojuszu i miejsca w pobli¿u pueblo. M³odzie¿ powtarza ich s³owa, reszta odpêdza.}
{275} {} {Jak¹ broñ maj¹ osoby postronne?}
{276} {} {Obcy maj¹ broñ paln¹ i ciê¿kie metalowe zbroje. Nie mo¿emy stawiæ czo³a takiej armii w otwartej walce za pomoc¹ naszych w³óczni. Tylko spryt i znajomoœæ pustkowi pomagaj¹ nam walczyæ z tak potê¿nym wrogiem.}
{277} {} {O jakiej bezdusznej technologii mówisz?}
{278} {} {Stare rzeczy, których moc pochodzi z innych starych rzeczy. Nazywacie to „zasilaniem” i „promieniowaniem”. Przez d³ugi czas ¿adne z plemienia nie odwa¿y³o siê nawet dotykaæ tych rzeczy. A teraz w Phoenix i Tu-San robi¹ je równie ³atwo i zrêcznie, jak my robimy torby ze skóry braminów.}
{279} {} {O co chodzi z t¹ wod¹ ognist¹?}
{280} {} {Ten gorzki, œmierdz¹cy p³yn dotar³ do nas z Phoenix. Og³upia twoj¹ g³owê jak Mroczny Bramin. Ci, którzy pij¹ tê wodê, robi¹ dziwne rzeczy. Próbujê spaliæ wszystkie znalezione materia³y, ale na pró¿no. Dopóki Phoenix nie przestanie produkowaæ i sprzedawaæ tego napoju plemieniu, bêdziemy mieli tu ci¹g³y problem z t¹ wod¹.}
{281} {} {W Phoenix musi byæ zród³o bimbru.}
{282} {} {Szuka³em kogoœ, kto by znalaz³ i zniszczy³ tê aparaturê przez d³ugi czas. Bez tej "tequili" naszemu plemieniu bêdzie ³atwiej stawiæ opór obcym. Zrób to, a hojnie ciê wynagrodzê.}
{283} {} {Ok. Zrobiê to.}
{284} {} {Z³o¿ê ofiary Boskiemu Braminowi, aby ciê prowadzi³ i chroni³ po drodze. Powodzenia przyjacielu.}
{285} {} {Do zobaczenia, Mangas.}
{286} {} {Czekaj, chcê wiedzieæ wiêcej.}
{287} {} {Tam musi byæ du¿o ró¿nych zabezpieczeñ. I nawet nie wiem, gdzie dok³adnie mo¿e byæ ta aparatura. Nie, nie bêdê biegaæ po ca³ym mieœcie jak kretyn.}
{288} {} {Wiêc odejdŸ. Marnujesz nasz czas.}

{290} {} {Raduj siê, Mangas! Destylarnia bimbru z Phoenix zosta³a ca³kowicie zniszczona.}
{291} {} {Sam Boski Bramin musia³ ci pomóc w tym trudnym zadaniu. Teraz widzê, ¿e myli³em siê w moim stosunku do ciebie. Nie wszyscy ludzie z zewn¹trz próbuj¹ nas ujarzmiæ lub okraœæ. Dziêkujê przyjacielu z Villi.}
{292} {} {Nie ma za co.}
{293} {} {Czy powiedzia³eœ coœ o nagrodzie?}
{294} {} {Zas³ugujesz na szacunek i nagrodê. WeŸ te stare rzeczy, które niedawno odebra³em moim wspó³plemieñcom. Z pewnoœci¹ Ci siê przydadz¹.}
{295} {} {No proszê, baterie nuklearne, u¿ywki, antyrady i kilka kapsli... NieŸle.}

{300} {} {...To jest nasza przysz³oœæ? Kiedy upadliœmy tak nisko, ¿e nawet m³odzie¿ wyst¹pi³a przeciwko plemieniu? Winni s¹ misjonarze z Phoenix...}
{301} {} {Jest za póŸno, by walczyæ o wolnoœæ, Mangas. Wódz zawar³ sojusz z Phoenix. PogódŸ siê z tym.}
{302} {} {Za³ujê przysz³oœci plemienia. Jest pokryta mg³¹. Jesteœmy jak zagubiony bramin, który odszed³ od trzody. To smutne. Bardzo smutne.}
{303} {} {Tak. Zdarza siê.}

{310} {} {Proszê ciê, abyœ popiera³ sojusz z misjonarzami z Phoenix.}
{311} {} {Masz urojenia, przyjacielu. Próbujê wypêdziæ obcych z naszej ziemi zaklêciami i oœwieceniem umys³ów moich wspó³plemieñców. A ty prosisz mnie, abym przesta³ i podda³ siê woli Bramiñskiego Losu.}
{312} {} {Dok³adnie.}
{313} {} {Brzmi to naprawdê szalenie, jeœli siê nad tym zastanowiæ.}
{314} {} {Co siê z tob¹ dzieje, obcy z Villi? Myœla³em, ¿e twoja wioska i nasze plemiê s¹ po tej samej stronie na wojennej œcie¿ce. Czy¿ nie?}
{1314} {} {Co siê z tob¹ dzieje, kobieto Villi? Myœla³em, ¿e twoja wioska i nasze plemiê s¹ po tej samej stronie na wojennej œcie¿ce. Czy¿ nie?}
{315} {} {Przepraszam, Mangas, nie masz racji. Swiat siê zmienia i nie mo¿na ¿yæ tak jak dawniej.}
{316} {} {Teraz pokazujesz swoje prawdziwe oblicze. Jeœli twoje plemiê jest tak s³abe, niech tak bêdzie. Ale MY nie ugniemy siê pod obcymi z Phoenix!}
{317} {} {Na pró¿no. Przypomnisz sobie moje s³owa.}
{318} {} {Oczywiœcie wiesz lepiej... Wychodzê.}
{319} {} {Przepraszam Mangas, ale nie masz racji. Swiat domaga siê zmian. W przeciwnym razie plemiê zostanie zmiecione z powierzchni ziemi.}
{320} {} {To wielkie s³owa. A¿ zaczynam siê chyba... baæ? Ale uk³adaj¹c siê pod Nowy Swiat, wszyscy tak samo znikniemy. Czy¿ nie?}
{321} {} {Zawrzyj sojusz z Phoenix, a zachowasz swoje tradycje. Pozostawiony z Rangersami, skazujesz siê tylko na wojnê i ca³kowit¹ klêskê.}
{322} {} {Nie wiem. Zdecyduj sam. Do zobaczenia.}
{323} {} {Plemiê jak dot¹d zdo³a³o stawiæ opór i misjonarzom i bandytom. Ale ich rosn¹ca si³a naciska na nas coraz bardziej. Nawet zjednoczone plemiê ledwo utrzymuje siê w San Brahmin.}
{324} {} {Niech tak bêdzie. Aby ocaliæ mój klan, bêdê opowiada³ siê za sojuszem. Ale utrzymam te¿ sojusz z Rangersami. A przy pierwszych oznakach zagro¿enia z³amiemy wszelkie umowy.}
{325} {} {M¹dra decyzja.}
{326} {} {Nie masz wyboru. Phoenix i tak wygra.}
{327} {} {Zaufaj mi. Stra¿nicy nie s¹ twoimi przyjació³mi, a Phoenix i tak wygra. Nie masz wyboru, inaczej zginiesz w piaskach.}
{328} {} {S³ucham twoich s³ów i czujê siê coraz bardziej zaniepokojony... Czy jest naprawdê tak Ÿle, ¿e nawet Villa jest gotowa ugi¹æ siê pod Phoenix? Chyba naprawdê nie mamy wyboru.}
{329} {} {Ju¿ sam nie wiem, Mangas... Muszê zebraæ myœli.}
{330} {} {Oczywiœcie. Dopóki nie przekonasz mnie, ¿e jest inaczej, bêdê przemawia³ w radzie za sojuszem z Rangersami. To oni ¿ycz¹ nam powodzenia.}
{331} {} {Ok. Zegnaj.}
{332} {} {A jeœli przedstawiê ci dowody ich zdrady?}
{333} {} {Có¿, to mo¿e ciê pos³ucham. Ale nie wa¿ siê mnie ok³amywaæ.}
{334} {} {Ok. Do zobaczenia.}
{335} {} {Rangersi zostali pokonani. Ich tama zosta³a zniszczona.}
{336} {} {Och, dlaczego Boski Bramin Przeznaczenia jest dla nas taki okrutny!}
{337} {} {S¹ teraz zajêci w³asnym przetrwaniem. Nie warto liczyæ na ich pomoc.}
{338} {} {Rangersi ju¿ zniszczyli Plemiê Szakali. Mo¿ecie byæ nastêpni.}
{339} {} {Czy naprawdê ca³e ich plemiê zosta³o zniszczone? Och, dlaczego Boski Bramin Przeznaczenia jest dla nas taki okrutny!}
{340} {} {Dla nich wszyscy jesteœcie tylko dzikusami.}
{341} {} {Konwój zwyk³ych cywilów przechodzi³ przez wasze ziemie w Garage City. Stra¿nicy zdradziecko ich okradli.}
{342} {} {Jakie jeszcze dziwactwa ma w zanadrzu Boski Bramin Przeznaczenia?}
{343} {} {Migranci tylko odmówili spe³nienia ich chorych ¿¹dañ. Traktuj¹ tak ka¿dego, kto ich nie s³ucha.}