{100} {} {Widzisz Kap³ankê Nanê.}
{101} {} {Widzisz kap³ankê w stroju ludowym.}
{102} {} {OdejdŸ. Nie boimy siê Ciebie i Twoich ¿elaznych zabawek.}

#Pierwsze spotkanie
{200} {} {Stój. Nie wpuszczamy ju¿ obcych do obozu.}
{201} {} {Czekaj, nieznajomy. Ostrzegaliœmy, ¿e wasza eskadra powinna opuœciæ nasze ziemie. Dlaczego ci¹gle nam przeszkadzasz?}
{202} {} {Nie wiem co masz na myœli. Scigam konwój niewolników z Villi. Mogli odwiedziæ to miejsce.}
{203} {} {Wiêc jesteœ z Villi? S³ysza³am o twojej wiosce! Nigdy nie byliœmy wrogami. Ale nigdy te¿ nie byliœmy przyjació³mi.}
{204} {} {A ja nic o was nie wiedzia³em.}
{1204} {} {A ja nic o was nie wiedzia³am.}
{205} {} {Wiêc powinniœmy siê lepiej poznaæ.}
{206} {} {Wiêc spotka³ was ten sam los co wielu? Przykro mi. Ale tutaj nie znajdziesz swoich wspó³plemieñców.}
{207} {} {Te¿ masz problem z handlarzami niewolników?}
{208} {} {Mog¹ tu byæ ludzie z Villi. Nawet nie myœl o utrudnianiu moich poszukiwañ.}
{209} {} {Wiêc jesteœ z Villi? S³ysza³am o twojej wiosce. Nigdy nie byliœmy wrogami i niech tak zostanie.}
{210} {} {Jeœli wiesz, gdzie handlarze niewolników trzymaj¹ moich ludzi, to mów.}
{211} {} {Wiêc handlarze niewolników i twoja wioska starli siê? Przykro mi. Nie jesteœ pierwszym, który cierpi z ich powodu. Ale nie znajdziesz tu swoich ludzi.}
{212} {} {Te¿ masz problem z handlarzami niewolników?}
{213} {} {Madre... Padre... Chcê ich uratowaæ i wróciæ do domu!}
{214} {} {Och, biedne dziecko. Prawdopodobnie Bramin Mrocznego Promieniowania przekl¹³ nasienie twojego gatunku. Szkoda mi Ciebie.}
{215} {} {Bra-Min? Nie, nie...}
{216} {} {IdŸ do naszego przywódcy, Geronimo. Porozmawiaj z nim. Jest m¹dry i mo¿e ci pomóc.}
{217} {} {Pójdê do starszego.}

{220} {} {Nazywaj¹ siebie misjonarzami. Przybyli na nasze ziemie i narzucili nam swoje zasady. Plemiê stawia opór, ale cena za nasz¹ wolnoœæ jest coraz wy¿sza. Jesteœmy na skraju wojny z bia³oskórymi mieszkañcami Phoenix.}
{221} {} {Na pustkowiu jest du¿o miejsca. Nie mo¿ecie siê dogadaæ?}
{222} {} {Chc¹ nas nagi¹æ do swojej woli dla braminów i taniej si³y roboczej. Ale my nie jesteœmy jednymi z tych Braminów, które s¹ pos³uszne ka¿demu mê¿czyŸnie z biczem.}
{223} {} {Ty i ja jesteœmy podobni. Villa równie¿ ceni swoj¹ wolnoœæ. Ale zosta³a odebrana nam si³¹.}
{224} {} {W takim razie powinniœmy siê nawzajem s³uchaæ. Porozmawiaj z naszym przywódc¹, Geronimo. Nie chce rozmawiaæ z nieznajomymi, ale ty jesteœ z s¹siedniego plemienia. S¹siedzi powinni ¿yæ w pokoju i sobie pomagaæ.}
{225} {} {OK. Gdzie mogê znaleŸæ tego przywódcê?}
{226} {} {IdŸ do du¿ego domu z filarami. Zg³oszê twoje przybycie. Ale nie zawracaj sobie g³owy reszt¹ osadników, dopóki nie zdobêdziesz naszego zaufania.}
{227} {} {OK. Do zobaczenia.}
{228} {} {Szukam Rangersa Oscara. Wys³ano mnie, by mu pomóc.}
{229} {} {Doceniamy to, co Rangersi robi¹ dla naszej wolnoœci. Ostatnio jesteœmy na krawêdzi wojny z misjonarzami. Porozmawiaj o tym z naszym przywódc¹, Geronimo.}

{230} {} {Co powiedzia³ Geronimo?}
{231} {} {Jeszcze z nim nie rozmawia³em.}
{1231} {} {Jeszcze z nim nie rozmawia³am.}
{232} {} {IdŸ do Geronimo. Nie bêdê z tob¹ o niczym rozmawiaæ, dopóki nie pozwoli ci zostaæ.}
{233} {} {Ok.}
{234} {} {Czy mogê porozmawiaæ z tob¹ od pocz¹tku?}
{235} {} {Nie. IdŸ do Geronimo. Nie bêdê z tob¹ o niczym rozmawiaæ, dopóki nie pozwoli ci zostaæ.}
{236} {} {Ok.}
{237} {} {Gdzie jest wódz?}
{238} {} {W du¿ym, jasnym budynku z filarami. Smia³o, na pewno go nie przegapisz.}
{239} {} {Rozumiem.}
{240} {} {Oferujê wsparcie przeciwko Phoenix.}
{241} {} {Ciekawa propozycja. Ten problem dotyczy nas wszystkich - zarówno naszego plemienia, jak i Twojej Villi. Mam nadziejê, ¿e faktycznie mo¿esz nam pomóc.}
{242} {} {Tak. Zobaczê, co mogê zrobiæ.}

# Powtarzajacy siê dialog
{250} {} {S³ucham ciê, ch³opie z Villi.}
{1250} {} {S³ucham ciê, ch³opko z Villi.}
{251} {} {Mów, ch³opie z Villi.}
{1251} {} {Mów, ch³opko z Villi.}
{252} {} {Muszê iœæ. Do zobaczenia, Nana.}

{260} {} {Proszê ciê, abyœ popar³a sojusz z misjonarzami z Phoenix.}
{261} {} {Nie spodziewa³am siê, ¿e bêdziesz po ich stronie. I nie widzê powodu, by przytulaæ wê¿a. Phoenix zdradzi nasze plemiê, gdy tylko mu siê to op³aci.}
{262} {} {Nie wiem, co powiedzieæ. Mo¿esz nawet mieæ racjê.}
{263} {} {Otwórz oczy - Phoenix jest bardziej op³acalne ni¿ Rangersi dla ca³ego plemienia.}
{264} {} {Tak jak wczeœniej ¿yliœmy bez Phoenix, tak bêdziemy ¿yæ dalej. Jestem przeciwna temu uk³adowi.}
{265} {} {Kiedyœ tego po¿a³ujesz. Zapamiêtaj moje s³owa.}
{266} {} {Ok. Nie k³óæmy siê.}
{267} {} {Rangersi s¹ strasznie zdradzieccy. U¿ywaj¹ was do w³asnych celów wojennych. A Phoenix oferuje wsparcie i rozwi¹zanie wielu problemów.}
{268} {} {Hmm. Nie myœla³am o tym wczeœniej. Dobrze, mo¿esz liczyæ na mój g³os podczas narady starszych.}
{269} {} {Nie po¿a³ujesz swojego wyboru.}
{270} {} {Swietnie, to wszystko, czego potrzebujê.}
{271} {} {Sojusz rozwi¹za³by wiele twoich problemów.}
{272} {} {Mo¿e tak. Ale staj¹c siê czêœci¹ imperium, zatracimy siê. Co wa¿niejsze, bêdziemy bezbronni wobec obcych. Co zrobimy, jeœli zostaniemy zdradzeni? Jak siê ochronimy?}
{273} {} {Potrzebujesz si³y. Potrzebujesz broni.}
{274} {} {Tak. Potrzebujemy broni, której Phoenix nam nie da. Gdybyœmy mieli te ogniste karabiny, które zabijaj¹ zdrowego cz³owieka jednym strza³em, nie balibyœmy siê ¿adnych sojuszy.}
{275} {} {Przyniosê ci trzy karabiny myœliwskie. W zamian bêdziesz opowiadaæ siê za zjednoczeniem w radzie starszych.}
{276} {} {Niech tak bêdzie. Zdob¹dŸ broñ obcych, a stanê po twojej stronie.}
{277} {} {Zgoda.}
{278} {} {Ok. Do zobaczenia.}
{1278} {} {Ok. Do zobaczenia.}
{279} {} {Ok. I tak zawsze mam wiele ró¿nych broni przy sobie.}

{280} {} {Mam dla ciebie broñ.}
{281} {} {Poka¿ mi, co przynios³eœ?}
{1281} {} {Poka¿ mi, co przynios³aœ?}
{282} {} {Nie teraz.}
{283} {} {.}
{290} {} {Ok. Ale to nie wystarczy.}
{291} {} {Przyniosê wiêcej.}
{292} {} {OK. To wystarczy. Mo¿esz liczyæ na mój g³os podczas narady starszych.}
{293} {} {Mimo to Geronimo zawar³ sojusz z Rangersami. Nie powininnam by³a ciê s³uchaæ i sprzeciwiaæ siê temu uk³adowi.}
{294} {} {Oboje siê myliliœmy. Sta³o siê.}
{295} {} {Ten b³¹d mo¿e kogoœ kosztowac ¿ycie. Pomyœl o tym.}
{296} {} {Tak. Do zobaczenia.}
{297} {} {Ach, przepraszam. Zapomnia³em, ¿e wy, dzikusy, jesteœcie tacy g³upi. Czy jesteœ przyzwyczajona do tego, ¿e liderzy decyduj¹ o wszystkim za Ciebie?}
{298} {} {Poproszê Boskiego Bramina, aby po drodze wys³a³ wê¿e do twoich stóp.}
{299} {} {Jasne. Do zobaczenia.}

#Zapytania
{310} {} {Kim jesteœ?}
{311} {} {Jestem Nana, kap³anka po³udniowego klanu mojego plemienia.}
{312} {} {Mi³o ciê poznaæ, Nana.}
{313} {} {Czy s¹ jakieœ inne kap³anki? Albo kap³ani?}
{314} {} {Ja, Genaro, Mangas i Najwy¿szy Wódz Geronimo, s¹ teraz w obozie.}
{315} {} {Opowiedz mi o Genaro.}
{316} {} {Jest odpowiedzialny za zagrody braminów i prawie najczêœciej wychodzi na pustkowia. Dlatego wie lepiej ni¿ reszta o obcych z Phoenix i ich zwyczajach.}
{317} {} {Opowiedz mi o Mangasie.}
{318} {} {Uwa¿aj na Mangasa. Nie toleruje wszystkiego, co narusza nasze tradycje.}
{319} {} {Opowiedz mi o Wodzu Geronimo.}
{320} {} {To œwietny przywódca. Zjednoczy³ rozproszone plemiê w obliczu nowego wroga. Przed nim plemiê by³o wrogo nastawione do redystrybucji ziemi. Teraz ¿yjemy jako jedna rodzina.}
{321} {} {Spotka³em tutaj Chatto. Co mo¿esz mi o nim powiedzieæ?}
{322} {} {To syn wodza, jest wa¿n¹ osob¹ w obozie. To za nim stoj¹ m³odzi ludzie. Razem chc¹ zmiany. I naprawdê mi siê to nie podoba.}
{323} {} {Rozumiem.}