{100} {} {Widzisz Zwiadowcê.}
{101} {} {Widzisz jednego z mê¿czyzn z plemienia. Ubrany jest w bardzo lekkie ubranie.}
{102} {} {Dziêkujê, przyjacielu naszego plemienia. Zaskakuj¹ce jest, ¿e s¹ jakieœ osoby z zewn¹trz, którym mo¿esz zaufaæ.}
{103} {} {Dziêkujê za pomoc w oazie. NajwyraŸniej gdzieœ w tobie wci¹¿ jest trochê dobroci.}

# Przed otrzymaniem zadania
{200} {} {Pozdrowienia, nieznajomy. Chocia¿ obóz jest dla Ciebie otwarty, nadal w¹tpiê, czy skorzystamy na tobie.}
{1200} {} {Pozdrowienia, nieznajoma. Chocia¿ obóz jest dla Ciebie otwarty, nadal w¹tpiê, czy skorzystamy na tobie.}
{201} {} {Dlaczego?}
{202} {} {Z powodu misjonarzy i z³odziei byd³a nie ufamy obcym.}
{203} {} {Rozumiem to. Uwierz mi, nie mam na myœli nic z³ego i nie chcê ¿adnych problemów.}
{204} {} {Ju¿ zapomnieliœmy, jak wierzyæ s³owom. Ale mi³o mi to s³yszeæ.}
{205} {} {Mam nadziejê, ¿e mimo wszystko znajdziemy wspólny jêzyk.}
{206} {} {Jeszcze nic nie zrobi³em, a ty ju¿ mnie obwiniasz!}
{1206} {} {Jeszcze nic nie zrobi³am, a ty ju¿ mnie obwiniasz!}
{207} {} {Niezbyt m¹drze z twojej strony. Nie bêdziesz móg³ tu zbyt d³ugo zostaæ z takim zachowaniem.}
{208} {} {Nie obchodzi mnie to. Jestem tu mimochodem.}
{209} {} {Przepraszam, nie o to mi chodzi³o.}

{220} {} {Czego chcesz, obcy?}
{221} {} {Czego chcesz, przybyszu z Villi?}
{222} {} {Mi³o ciê widzieæ przyjacielu.}
{223} {} {Niczego nie potrzebujê. Do zobaczenia.}

{230} {} {Co robisz?}
{231} {} {Wodzowie zebrali nas w pueblo, ¿ebyœmy razem walczyli z obcymi. Moim zdaniem to by³ b³¹d.}
{232} {} {Dlaczego?}
{233} {} {Niewielu zwiadowców œledzi obecnie pustyniê dooko³a. Niedawno wróci³em z jednego z wodopojów. Widzia³em tam wiele ogromnych pustynnych skorpionów. Uniemo¿liwiaj¹ pasterzom zbli¿aæ siê do wody.}
{234} {} {Co za horror! I nic nie mo¿na z tym zrobiæ?}
{235} {} {Rozmawia³eœ z kimœ na ten temat?}
{236} {} {Chcia³em zebraæ dru¿ynê, ¿eby pozbyæ siê potworów. Ale wódz zabroni³ wycofywania wojowników z pueblo, chyba ze jest to absolutnie konieczne.}
{237} {} {Myœlê, ¿e kiedyœ skorpiony opuszcz¹ to miejsce. Na mnie ju¿ czas. Pa.}
{238} {} {Szkoda. Mogê ci pomóc.}
{239} {} {Naprawdê poradzisz sobie samemu z gromad¹ skorpionów? To bêdzie za¿arta bitwa.}
{240} {} {Wiesz, w sumie to nie poradzê sobie nawet z jednym skorpionem. Bêdziesz musia³ sobie z nimi poradziæ beze mnie.}
{241} {} {Coœ wymyœlê. Poka¿ mi drogê do tego wodopoju.}

{250} {} {Zabi³em wszystkie Radskorpiony przy wodopoju.}
{1250} {} {Zabi³am wszystkie Radskorpiony przy wodopoju.}
{251} {} {Chwa³a Niebiosom! Twoja pomoc jest nieoceniona dla naszych pasterzy, dla których oaza by³a wa¿nym miejscem odpoczynku. Dziêkujê, przyjacielu naszego plemienia.}
{252} {} {Nie ma za co.}
