{100} {} {Widzisz Ronniego.}
{101} {} {Widzisz kaletnika. Profesjonalnym ruchem rêki czyœci kawa³ek skóry.}
{102} {} {S³uchaj, ¿elazny duchu, zostaw nasz¹ spokojn¹ wioskê w spokoju.}

{200} {} {Pozdrowienia, nieznajomy. Mam nadziejê, ¿e przybywasz do nas w dobrych intencjach.}
{1200} {} {Pozdrowienia, nieznajoma. Mam nadziejê, ¿e przybywasz do nas w dobrych intencjach.}
{201} {} {Kim jesteœ? I co to za miejsce?}
{202} {} {Chcê ciê tylko poznaæ.}
{203} {} {Jestem Ronnie, a to moja garbarnia.}
{204} {} {Wygl¹da na to, ¿e siê tu osiedli³eœ, Ronnie.}
{205} {} {Masz racjê. Wczeœniej równie¿ podró¿owa³em po pustyni Sonora i zagania³em braminy, jak reszta. A teraz siedzê tutaj i przygotowujê skóry dla moich wspó³plemieñców i na sprzeda¿.}
{206} {} {Masz wa¿n¹ pracê, Ronnie.}
{207} {} {Niez³y interes, musi byæ.}
{208} {} {Rozumiem. Ale teraz nie potrzebujê galanterii skórzanej. Narazie.}

{210} {} {Pozdrowienia.}
{211} {} {Do zobaczenia.}
{212} {} {Och, znam swoj¹ pracê. Oznaczam ka¿d¹ tak¹ zbrojê specjalnym znakiem.}
{213} {} {Witaj Stra¿niku. Jak mogê pomóc, przyjacielu mojego plemienia?}
{214} {} {Ach, kolejny ambasador dziwnej religii. Czego twój koœció³ chce tym razem od mojego plemienia?}

{220} {} {Dlaczego przesta³eœ handlowaæ z Garage City?}
{221} {} {Tak zdecydowali nasi kap³ani. Nie podoba im siê, ¿e nieznajomi wprowadzaj¹ niezgodê do naszego ¿ycia, oszukuj¹ i kradn¹ nasze Braminy. Dlatego zamknêliœmy szlaki handlowe z Phoenix i wszystkimi jego koloniami.}
{222} {} {W takim razie dlaczego to dotyczy te¿ Garage City?}
{223} {} {Kap³ani wiedz¹ lepiej. Porozmawiaj z nimi. Dopóki siê nie zgodz¹, nie bêdê móg³ handlowaæ z tym miastem.}
{224} {} {Rozumiem. Spróbujê ich przekonaæ.}
{225} {} {Wódz Geronimo zgodzi³ siê na handel z Garage City.}
{226} {} {Wódz Chatto zgodzi³ siê na handel z Garage City.}
{227} {} {Nie wybrano jeszcze najwy¿szego przywódcy. Nie przegap tej szansy.}
{228} {} {Mam nadziejê, ¿e to tylko dyspensa Boskiego Bramina. Powiedz mieszkañcom Garage City, aby wys³ali osobê do negocjacji.}
{229} {} {To dobrze.}

{230} {} {Czy mo¿esz zrobiæ skórzane torby na mój motor?}
{231} {} {Nie ma problemu. Zrobiê to najlepiej jak potrafiê, Twój motor na tym skorzysta. Ale to nie s¹ tanie rzeczy. Co mo¿esz mi zaoferowaæ w zamian?}
{232} {} {Zobaczmy...}
{233} {} {Garbarnia jest zamkniêta dla obcych. Pracujê tylko dla cz³onków plemienia i osób z zewn¹trz, którym ufaj¹ szamani.}
{234} {} {Wiêc najpierw muszê uporaæ siê z lokalnym gównem? No jasne.}
{235} {} {Porozmawiam z nimi póŸniej.}

{240} {} {Chcia³em zobaczyæ twoje towary. Mogê?}
{241} {} {Nie handlujê ju¿ z obcymi dopóki wojna siê nie skoñczy. Tak zdecydowa³ lider Geronimo.}
{242} {} {OK, poradzê sobie bez twojej pomocy.}
{243} {} {Wojna siê skoñczy³a. Mo¿esz znów handlowaæ z obcymi, przyjacielu.}
{244} {} {Wódz jest prawdopodobnie zbyt zajêty, ¿eby mi o tym powiedzieæ. Dobra, zobacz co mam. Mo¿e potrzebujesz czegoœ na zamówienie?}
{245} {} {Dziêki, daj mi czas na przemyœlenie.}
{246} {} {Daj spokój, jesteœmy s¹siadami, a nie obcymi.}
{247} {} {Przepraszam, ale wódz wie lepiej.}
{248} {} {Na pewno? W porz¹dku.}
{249} {} {S¹siedzi musz¹ ¿yæ w pokoju i sobie pomagaæ. Twoje plemiê i nasza Villa - oboje zyskamy.}
{250} {} {Zgadzam siê z tob¹, podró¿niku. Przywódca mówi³ tylko o Phoenix i jego koloniach. Zak³adam, ¿e Villa do nich nie nale¿y. Zobacz co mam. Mo¿e potrzebujesz czegoœ na zamówienie?}
{251} {} {Dziêki, daj mi czas do namys³u.}
{252} {} {Czy nie jestem godny zaufania, Ronnie?}
{253} {} {Przepraszam, nie chcia³em ciê uraziæ. Nie jesteœ jednym z tych, którzy oszukali i skrzywdzili nasze plemiê. Spójrz na moje towary. Mo¿e potrzebujesz czegoœ na zamówienie?}
{254} {} {Dziêki, pozwól mi zobaczyæ co masz.}

{260} {} {Witaj bohaterze. Wszyscy jesteœmy Ci niezmiernie wdziêczni za twoje czyny. Proszê, weŸ tê broñ jako dowód naszej wdziêcznoœci. Szamani obdarzyli j¹ cz¹stk¹ mocy Boskiego Bramina.}
{1260} {} {Witaj bohaterko. Wszyscy jesteœmy Ci niezmiernie wdziêczni za twoje czyny. Proszê, weŸ tê broñ jako dowód naszej wdziêcznoœci. Szamani obdarzyli j¹ cz¹stk¹ mocy Boskiego Bramina.}
{261} {} {Ciekawy egzemplarz.}
{262} {} {Niestety moc tej broni nie jest nieograniczona. Kiedy boska energia siê wyczerpie, nale¿y coœ tam wymieniæ, ale nie pamiêtam co.}
{263} {} {Mimo to dziêki, Ronnie.}

{270} {} {Wojna siê skoñczy³a - dziêki twojej interwencji. San Brahmin ponownie otwiera szlaki handlowe do Phoenix. Dlatego mogê ponownie otworzyæ drzwi warsztatu dla wszystkich.}
{271} {} {Wojna siê skoñczy³a - dziêki twojej interwencji. San Brahmin nie wierzy ju¿ w Imperium Phoenix i jego wasali. Ale nadal jesteœmy otwarci dla naszych przyjació³ i Stra¿ników.}
{272} {} {[Dalej.]}
{273} {} {Jeœli potrzebujesz artyku³ów skórzanych, skontaktuj siê bezpoœrednio ze mn¹.}
{274} {} {Bêdê pamietaæ.}

{280} {} {Hmm. Jesteœ podejrzanie podobny do jednego z bandytów, którzy zaatakowali naszych pasterzy poza Garage City.}
{281} {} {Nie wiem, co masz na myœli. Nic takiego nie mia³o miejsca.}
{282} {} {Ha! Nawet dzieci Ciê rozpoznaj¹. IdŸ w pokoju.}
{283} {} {Ok...}
{284} {} {Tak, tak by³o. Myœleliœmy, ¿e to dzikie braminy.}
{285} {} {Powinienem by³ siê domyœliæ. Twoje szczêœcie, ¿e siê przyznajesz. W przeciwnym razie ca³e pueblo by³oby wrogo nastawione co do Ciebie. Tak jak mówi³em, dobrze, ¿e przyznajesz siê do b³êdu. Przynajmniej wiem, ¿e muszê z tob¹ uwa¿aæ.}
{286} {} {No dobrze...}
{287} {} {Pomyœlê o twoich s³owach, m¹dry cz³owieku.}
{288} {} {Zachowaj swoje nauki dla ma³ych dzieci, g³upku.}

{290} {} {Wiesz, Mangas poprosi³ mnie o zniszczenie destylarni bimbru w Phoenix.}
{291} {} {Co on o sobie myœli? Szaman nie mo¿e tak po prostu pozbawiæ nas wszystkich przyjemnoœci. Nikomu siê to nie spodoba. Mangas nie mo¿e decydowaæ za wszystkie klany naraz, nie jest najwy¿szym wodzem.}
{292} {} {Wiêc sprzeciwiasz siê propozycji Mangasa?}
{293} {} {To sprawa ka¿dego, nie tylko lidera. Zamiast spe³niaæ kaprysy tego zrzêdliwego starca, lepiej przynieœ mi pude³ko alkoholu z Phoenix. Znajdê dla niego zastosowanie podczas obchodów Dnia S³oñca.}
{294} {} {Co to za problem samemu zdobyæ alkohol?}
{295} {} {Nie wiesz? Zerwaliœmy wszystkie umowy z Phoenix z powodu wojny. Oczywiœcie wiemy te¿, jak zrobiæ bimber z kaktusów, ale do prawdziwej tequili z miasta nie da siê tego porównaæ.}
{296} {} {Ile butelek potrzebujesz?}
{297} {} {Dziesiêæ butelek tequili i tak¹ sam¹ liczbê butelek piwa.}
{298} {} {OK, pomyœlê, którego z was poprzeæ w tej sprawie.}
{299} {} {Przypomnij mi, ile butelek alkoholu potrzebujesz?}
{300} {} {Mam przy sobie tyle alkoholu, ile potrzebujesz.}
{301} {} {Niech twoje imiê bêdzie s³awne dziêki Braminowi O Twarzy S³oñca! Z takimi rezerwami nasze œwiêta nie zostan¹ zaciemnione nawet przez tocz¹c¹ siê wokó³ nas wojnê. Dziêkujê Ci. Jeœli potrzebujesz us³ug garbarza, pamiêtaj o mnie. Zrobiê dla Ciebie wszystko za ni¿sz¹ op³at¹.}
{302} {} {Bêdê o tym pamietaæ. Czeœæ, Ronnie.}

{310} {} {Czym handlujesz? }
{311} {} {Wykonujê ró¿ne przedmioty ze skóry braminów. Ale s¹ u¿ywane g³ównie przez cz³onków plemienia. Nie robiê ju¿ interesów z Phoenix i jego koloniami. Z obcych tylko Stra¿nicy mog¹ liczyæ na wyj¹tki.}
{312} {} {Rozumiem.}
{313} {} {Jakie przedmioty produkujesz?}
{314} {} {Ubrania, paski, torby i nie tylko. Robiê te¿ zbroje dla Rangersów.}
{315} {} {Jaki jest problem z Phoenix?}
{316} {} {Przez jakiœ czas pokojowo koegzystowaliœmy. Ale w ci¹gu ostatnich kilku lat biali ludzie z broni¹ przybyli z wielkiego miasta, aby nas ujarzmiæ lub odebraæ nam to, co nale¿y do nas. Plemiê nie zamierza tego tolerowaæ.}
{317} {} {Mówisz, ¿e masz dobre stosunki z Rangersami, jak to?}
{318} {} {Pomagaj¹ nam stawiaæ opór najeŸdŸcom z Phoenix. I zawsze byli dobrymi klientami w mojej garbarni.}
{319} {} {Kogo popierasz w tej sprawie?}
{320} {} {Trudno mi powiedzieæ. Do tej pory Rangersi dobrze nas traktowali, ale podejrzewam, ¿e nie maj¹ czystych intencji. W koñcu maj¹ w³asne interesy w tym konflikcie.}
{321} {} {[Dalej.]}
{322} {} {W tym samym czasie ¿yliœmy w pokoju z Phoenix przez d³ugi czas i aktywnie handlowaliœmy z nim, dopóki nasze stosunki siê nie zepsu³y. Phoenix da³oby nam wiêcej mo¿liwoœci, gdyby nie chciwy tyran, który nim rz¹dzi.}
{323} {} {Rozumiem.}