{100} {} {Widzisz Georga Crooka.}
{101} {} {Widzisz mê¿czyznê z wielkimi w¹sami i zdecydowanym spojrzeniem.}
{102} {} {Dobrze. Teraz idŸ i zabij wszystkich dzikusów. Zrozumia³eœ rozkazy, typie?}
{103} {} {Uwa¿aj na siebie. Mo¿e jeszcze siê spotkamy.}
{104} {} {Muszê wracaæ do Phoenix. Bóg œwiadkiem, ¿e zrobi³em, co mog³em.}

#Pierwsze spotkanie
{200} {} {Stój. Co Ty tutaj robisz?}
{201} {} {Nie wiem. Po prostu siê w³óczê.}
{202} {} {Nie ¿artuj sobie ze mnie. Potrafiê ciê przejrzeæ, redneck. NajwyraŸniej nie jesteœ z Phoenix, co oznacza, ¿e pochodzisz sk¹dœ indziej, gdzieœ na pustkowiu. Sk¹d siê tu wzi¹³eœ? Odpowiedz.}
{203} {} {Nie muszê ci nic mówiæ.}
{1203} {} {Nie muszê ci nic mówiæ.}
{204} {} {No proszê. Dumny i nieugiêty ch³op. Czy ty naprawdê uwa¿asz, ¿e jesteœ tutaj niepokonany? Wkrótce ca³e pustkowie znajdzie siê pod butem Aarona i jego armii! A potem zobaczymy, na jak d³ugo zda siê Twoja duma.}
{1204} {} {No proszê. Dumna i nieugiêta ch³opka. Czy ty naprawdê uwa¿asz, ¿e jesteœ tutaj niepokonana? Wkrótce ca³e pustkowie znajdzie siê pod butem Aarona i jego armii! A potem zobaczymy, na jak d³ugo zda siê Twoja duma.}
{205} {} {Naprawdê?}
{206} {} {Ty, wieœniaku nie bêdziesz mia³ innego wyjœcia, jak tylko ugi¹æ kolana. Wkrótce siê przekonasz. Do tego czasu dam ci szansê na poprawê. Wróæ na pustkowia i opowiedz wszystkim o wielkoœci regularnej armii Phoenix.}
{1206} {} {Ty, wieœniaczko nie bêdziesz mia³a innego wyjœcia, jak tylko ugi¹æ kolana. Wkrótce siê przekonasz. Do tego czasu dam ci szansê na poprawê. Wróæ na pustkowia i opowiedz wszystkim o wielkoœci regularnej armii Phoenix.}
{207} {} {Dobra, znikam.}
{208} {} {Nie wyjdê st¹d bez odpowiedzi na moje pytania.}
{209} {} {Aaron wys³a³ mnie z pomoc¹. Oto pieczêæ.}
{210} {} {Moja wioska zosta³a spustoszona. Wiêc idê tam, gdzie patrz¹ moje oczy.}
{211} {} {Dobrze, dzieciaku. IdŸ do Phoenix. Na pustyni nie ma nic do roboty, ale w du¿ym mieœcie bêdzie dla Ciebie wiele mo¿liwoœci. Tylko nie pomyl drogi. Jeœli wiesz co mam na myœli.}
{212} {} {Tak, rozumiem.}
{213} {} {Swietnie. W takim razie narazie zak³adam, ¿e jesteœmy po tej samej stronie.}
{214} {} {Ok. Co tu siê dzieje?}
{215} {} {Niezupe³nie.}
{216} {} {Reprezentujê w³adzê Aarona na tych ziemiach. Aaron ceni tych, którzy go szanuj¹. I jest bardzo surowy dla tych, którzy wchodz¹ mu w drogê. Lepiej jest wybraæ m¹drze.}
{217} {} {Rozumiem.}
{218} {} {Co tu siê dzieje?}

{220} {} {Czekaj... Hmm? Znajoma szata. Czy przys³a³ ciê Aaron?}
{221} {} {Nie wiem, o czym mówisz. To tylko stara szmata.}
{222} {} {Wiêc zapomnij o tym. Co tu robisz?}
{223} {} {Tak, przys³a³ mnie Aaron. Chce poznaæ sytuacjê.}
{224} {} {Nie rozumiem co on robi. Wkrótce nie bêdê mia³ czym wykarmiæ mojej dru¿yny, a on wysy³a kolejnego cz³owieka... Powiedz mi, jaki bêdê mia³ z ciebie po¿ytek?}
{225} {} {Mam specjalne zadanie. Aaron jest zmêczony czekaniem na wyniki.}
{226} {} {Myœlê, ¿e on chce tylko jednego, szybkiego rozwi¹zania problemu.}
{227} {} {Hmm. Jestem ciekawy, jak zdoby³eœ tyle zaufania od samego Aarona. Mo¿e powinienem pos³uchaæ twojej rady. Pamiêtaj jednak, ¿e nadal to ja jestem dowódc¹ oddzia³u.}
{228} {} {Zaden problem.}
{229} {} {Nie obchodzi mnie twoja dru¿yna.}

{230} {} {Reprezentujê Stra¿ników. Dotar³y do nas pog³oski, ¿e ktoœ próbuje rozbiæ plemiê pasterzy.}
{231} {} {Jesteœmy tylko pokojowymi kolonizatorami. Przybyliœmy na tê pust¹ ziemiê, aby za³o¿yæ tu now¹ osadê. Robimy coœ z³ego?}
{232} {} {Próbujecie przepêdziæ lokalne plemiê.}
{233} {} {Powiem ci coœ. Pos³uchaj uwa¿nie, Stra¿niku. Te ziemie nie nale¿¹ do ciebie. I nie nale¿¹ te¿ do tych dzikusów. Ca³a dolina jest w³asnoœci¹ Aarona z Phoenix. Wracaj do swoich. I nie wa¿ siê wchodziæ nam w drogê.}
{234} {} {Powiedzia³eœ wystarczaj¹co du¿o. Nie potrzebujê wiedzieæ nic wiêcej.}
{235} {} {Nie wyjdê, dopóki nie odpowiesz na moje pytania. Co tu siê dzieje?}

# Powtarzajacy siê dialog
{250} {} {Tak? Mów, s³ucham.}
{251} {} {Puœæ mnie.}
{252} {} {Co tu wszyscy robicie?}

{260} {} {Ta ziemia nale¿y do Jego Wysokoœci Aarona, Pana Swiêtego Ognia i Pana Phoenix. Postanowi³ za³o¿yæ tutaj koloniê. Ale nasza misja jest utrudniana przez miejscowych dzikusów.}
{261} {} {Co jest nie tak z tymi dzikusami?}
{262} {} {Nie okazywali wczeœniej ¿adnej wrogoœci. Ale teraz próbuj¹ odstraszyæ nas groŸbami i brutaln¹ si³¹. Nie chcemy niepotrzebnej krwi i oferujemy im sojusz korzystny dla obu stron.}
{263} {} {Dlaczego nie zostawiæ ich plemienia w spokoju?}
{264} {} {Ich braminy s¹ bardzo cenne w Phoenix. Bez nich nast¹pi kryzys. Poza tym pozostawienie wroga pod nosem jest niewybaczalne.}
{265} {} {[Dalej.]}
{266} {} {W ka¿dym razie jestem podw³adnym. Wykonujê rozkaz naczelnego dowództwa. Rozkaz wprowadzenia siê jest dla mnie jasny. A zadania wêdrownych niepismiennych dzikusów s¹ poza moj¹ kontrol¹.}
{267} {} {Rozumiem.}
{268} {} {Pos³uchaj. Plemiê nie chce ju¿ ze mn¹ rozmawiaæ. Ale ty bêdziesz dobrym zwiadowc¹. Porozmawiaj z ich liderem, spróbuj przekonaæ go do zawarcia sojuszu.}
{269} {} {Nie bêdê siê anga¿owaæ w czyj¹œ wojnê. Moje problemy s¹ wa¿niejsze.}
{270} {} {Co to za problemy w porównaniu z wojn¹ miêdzy dwoma narodami? Lepiej módl siê, aby nie dotknê³a i ciebie i twojej rodziny.}
{271} {} {Muszê iœæ.}
{272} {} {Spróbuje. Opowiem ci co uda³o mi siê ustaliæ.}

{280} {} {Uda³o mi siê porozmawiaæ z ich wodzem. Ale stanowczo odmawia zawarcia sojuszu.}
{281} {} {Geronimo jest zbyt uparty. Wygl¹da na to, ¿e marnuje z nim czas. Musimy dzia³aæ bardziej zdecydowanie.}
{282} {} {Jaki masz plan?}
{283} {} {Wiem, ¿e nie wszystkie dzikusy nami gardz¹. M³odzi ludzie nawet próbuj¹ pomóc. Wœród nich jest syn wodza, Chatto. Porozmawiaj z nim, dowiedz siê, czego chce. Jeœli zajmie miejsce swojego ojca, mo¿emy siê dogadaæ.}
{284} {} {Warto spróbowaæ.}
{285} {} {Zabi³em Geronimo i jego nastêpcê Chatto.}
{1285} {} {Zabi³am Geronimo i jego nastêpcê Chatto.}
{286} {} {To by³o bardzo pochopne dzia³anie! Geronimo opiera³ siê sojuszowi. Ale Chatto móg³ zostaæ mediatorem na jego miejscu. Teraz nie mamy z kim negocjowaæ. Plemiê rozproszy siê po pustyni, ponownie rozpadaj¹c siê na ma³e stada.}
{287} {} {Trudno by³o to przewidzieæ...}
{288} {} {Ale sam chcia³eœ pozbyæ siê wodza.}
{289} {} {I tak sta³o siê ³atwiej. Wprowadzimy siê do pueblo i zmusimy dzikich do zaakceptowania naszych regu³ si³¹. Nie bêd¹ w stanie oprzeæ siê ca³ej kolonii.}
{290} {} {Có¿, czy w takim razie mogê pogratulowaæ ci zwyciêstwa?}
{291} {} {Jeszcze nie. Zwiadowcy zorientowali siê, kto jeszcze wznosi³ kurz w tym pueblo. Okaza³o siê, ¿e by³ to cz³owiek o imieniu Oscar. Ranger! Teraz rozumiem, sk¹d miejscowi znaj¹ podstawy taktyki i sztuczek partyzanckich.}
{292} {} {[Dalej.]}
{293} {} {Stra¿nika trzeba wypêdziæ z pueblo! Aby nawet jego imiê nie zosta³o tutaj zapamiêtane. A jeœli nie zechce odejœæ, bêdziemy musieli go potraktowaæ biczem, jak upartego bramina.}
{294} {} {OK. Zobaczê co da siê zrobiæ.}
{295} {} {Chatto jest teraz wodzem plemienia. I zgadza siê na zawarcie sojuszu.}
{296} {} {Wspania³a wiadomoœæ! Chatto ma w³adzê w oczach reszty plemienia, jego autorytet nie pozwoli plemieniu rozproszyæ siê po pustyni. Bardzo dobra robota. Jesteœ doskona³ym dyplomat¹. }
{297} {} {Wódz zgadza siê na sojusz. Uda³o mi siê go przekonaæ, choæ nie by³o to ³atwe.}
{298} {} {Wspania³a wiadomoœæ. Nie s¹dzê jednak, ¿eby tak bardzo zmieni³ swoje pogl¹dy. Najprawdopodobniej reszta starszych, którzy boj¹ siê wojny, wywieraj¹ na niego presjê. Ale to i tak dobra robota. Jesteœ doskona³ym dyplomat¹.}

{300} {} {Oscar nie ¿yje. Jego sojusznicy te¿ klêkaj¹ przed tob¹, dowódco.}
{301} {} {Zwyciêstwo! Na oczach plemienia zadaliœmy ogromny cios reputacji Stra¿ników. Teraz zrozumiej¹, z kim maj¹ do czynienia.}
{302} {} {Oscar uciek³ z pueblo i nie bêdzie ju¿ przeszkadza³ w twoich planach.}
{303} {} {Zwyciêstwo! Rangersi uciekli i stracili w oczach dzikusów do poziomu tchórzliwej iguany. Teraz nawet te dzikusy zrozumiej¹, z kim warto siê brataæ.}
{304} {} {Mi³o by³o Ci pomóc, dowódco!}
{1304} {} {Mi³o by³o Ci pomóc, dowódco!}
{305} {} {Ahem. W³aœciwie to sam wiesz, KTO rozwi¹za³ ten problem.}
{306} {} {Dobrze s³u¿y³eœ imperium. Chcia³bym ¿eby reszta mia³a tak¹ sam¹ si³ê woli i odpornoœæ bojow¹ co ty. Cieszê siê, ¿e jesteœmy po tej samej stronie.}
{1306} {} {Dobrze s³u¿y³aœ imperium. Chcia³bym ¿eby reszta mia³a tak¹ sam¹ si³ê woli i wytrzyma³oœæ bojow¹ co ty. Cieszê siê, ¿e jesteœmy po tej samej stronie.}
{307} {} {Myœlisz, ¿e Imperium Aarona nadal potrzebuje bohaterów?}
{308} {} {Oczywiœcie. Wyœlê list polecaj¹cy na twoje imiê do Phoenix. IdŸ prosto do Aarona, on ceni moje s³owo.}
{309} {} {Dziêki.}
{310} {} {Nie, nie dziêkuj. Mamy wspóln¹ sprawê. Powodzenia na drodze, towarzyszu.}
{311} {} {Powodzenia.}

{320} {} {Kim jesteœ? I kim s¹ ci wszyscy ludzie?}
{321} {} {Opowiedz mi o sobie i swojej dru¿ynie.}
{322} {} {George Crook, dowódca polowy Jego Wysokoœci Aarona z Phoenix. A to jest moja lojalna dru¿yna. Kiedy oczyœcimy terytorium z wrogów, przyjdzie za nami grupa prostych osadników.}
{323} {} {Mi³o by³o rozmawiaæ. Ale muszê iœæ.}
{324} {} {Czy ten tytu³ nie jest zbyt d³ugi dla w³adcy jednego miasta?}
{325} {} {Uwa¿aj na jêzyk. Imperium Aarona jest wystarczaj¹co du¿e i stale siê rozwija. Wkrótce ca³a Arizona bêdzie w jego mocy.}
{326} {} {Jeszcze raz - kim jesteœ?}
{327} {} {Sk¹d siê tu wszyscy wzieliœcie?}
{328} {} {Przyjechaliœmy z Phoenix, ¿eby za³o¿yæ tu koloniê. Ale niestety to miejsce zosta³o ju¿ zajête przez dzikusów.}
{329} {} {Gdzie jest to Phoenix?}
{330} {} {To miasto na po³udniowy wschód st¹d. Dziwne, ¿e tego nie wiesz. Przecie¿ to najwiêksze miasto w promieniu wielu kilometrów.}
{331} {} {Nie wiem. Generalnie pochodzê z wioski po przeciwnej stronie.}
{332} {} {W takim razie rozumiem. Tamte tereny to kraina Stra¿ników. Nic dziwnego, ¿e na twoim obszarze s¹ tylko wioski i nie ma cywilizacji. Spójrz na Phoenix, zobacz, czym jest normalne miasto.}
{333} {} {Tak zrobiê. Dziêki za radê.}
{334} {} {Nie obchodzi mnie ta twoja "cywilizacja".}
{335} {} {Opowiedz mi o plemieniu.}
{336} {} {To plemiê dzikusów i koczowników. Mieszkañcy Phoenix maj¹ z nimi d³ug¹ historiê.}
{337} {} {Swoj¹ drog¹, co wiesz o miejscowych?}
{338} {} {Chyba ich nie lubisz, co?}
{339} {} {To zwyk³e dzikusy! Pe³zaj¹ jak pch³y po pustyni. I nie mo¿na siê nawet osiedliæ w tych starych ruinach, bo od razu maj¹ problem.}
{340} {} {Kontynuuj.}
{341} {} {Niektóre radykalne klany atakuj¹ nawet cywilów. Phoenix od kilku lat próbuje wynegocjowaæ pokój. Niektóre klany przesz³y nawet na nasz¹ stronê. Ale nie wszystkie. Teraz mój oddzia³ odczu³ na w³asnej skórze upór dzikusów. }
{342} {} {Teraz rozumiem, dlaczego naje¿asz siê tak¹ iloœci¹ broni. Pokój z tob¹. Muszê iœæ.}
{343} {} {Czy ty te¿ jesteœ z Phoenix?}

{350} {} {Musisz opuœciæ San Brahmin. Ty i ca³a Twoja dru¿yna.}
{351} {} {O czym ty mówisz?}
{352} {} {Chyba nie chcesz wkurzyæ plemienia jeszcze bardziej, prawda?}
{353} {} {Przede wszystkim chcê ustawiæ tych dzikusów do pionu. Ciebie te¿ nie zaszkodzi³oby, gdybyœ siê stawia³.}
{354} {} {Ok. Nie zamierzam siê k³óciæ.}
{355} {} {Poleje siê krew, jeœli nie odejdziesz.}
{356} {} {Ktokolwiek ciê wys³a³, powiedz mu, ¿e George Crook nie zna strachu. Nie zastraszysz mnie s³owami.}
{357} {} {Có¿, ostrzega³em ciê. Teraz krew pop³ynie niczym rzeka!}
{1357} {} {Có¿, ostrzega³am ciê. Teraz krew pop³ynie niczym rzeka!}
{358} {} {Ok. S³ysza³em ciê.}
{1358} {} {Ok. S³ysza³am ciê.}
{359} {} {Plemiê jest gotowe do zdecydowanych dzia³añ. Twoja obecnoœæ daje im tylko powód.}
{360} {} {Wiem, ¿e dzikusy nie poddadz¹ siê tak ³atwo. S¹ zbyt daleko od idea³u Nowego Swiata, który buduje mój mistrz. Ale w³aœnie dlatego moja misja jest tak wa¿na - muszê pokazaæ dzikusom, ¿e ¿yj¹ przestarzale i Ÿle. Pokazaæ, ¿e istnieje lepszy œwiat.}
{361} {} {Ok. Nie zamierzam siê z tym k³óciæ.}
{362} {} {Ale doprowadzanie ich do gniewu tylko odsunie plemiê od twoich idea³ów. Daj im czas na przemyœlenie. W koñcu Twoja misja spe³znie na niczym, jeœli zaatakuj¹.}
{363} {} {A przecie¿ s¹ ich tysi¹ce! Sam ju¿ myœla³em o powrocie do Phoenix. Moi ludzie s¹ zmêczeni, nie mamy zapasów dla wszystkich, a tu ju¿ dzicy patrz¹ zza wydmy.}
{364} {} {Wiêc co zdecydowa³eœ?}
{365} {} {Ok. Odejdziemy. Ale tylko po to, aby powróciæ z now¹ energi¹ i zapasami.}
{366} {} {M¹dra decyzja, dowódco. Powodzenia po drodze.}