{100} {} {Widzisz misjonarza.}
{101} {} {Widzisz jednego z ¿o³nierzy Phoenix. Ma na sobie pe³ny pancerz bojowy.}

{110} {} {Powinieneœ porozmawiaæ z dowódc¹.}
{111} {} {Masz szczêœcie, ¿e nie jesteœ z plemienia pasterzy.}
{112} {} {Powinieneœ spotkaæ siê z dowódc¹. Porozmawiaj z nim.}
{113} {} {Jesteœ g³odny? Nie zamierzam dzieliæ siê swoj¹ porcj¹.}
{114} {} {Nie wiem, jak inni, ale zamierzam przetrwaæ tej nocy.}
{115} {} {Wygl¹da na to, ¿e zostaniemy tu przez d³ugi czas.}

{150} {} {*Spiewa star¹ piosenkê i zazdroœnie przygl¹da siê twojemu karabinowi*}
{151} {} {i Carabina Treinta Treinta I}
{152} {} {I Que los rebeldes portaban I}
{153} {} {Y decúan los maderistas I}
{154} {} {I Que con ellas no mataban. I}
{155} {} {I Con mi 30/30 me voy a pelear I}
{156} {} {I Ingrese a las filas de la rebeliƒn I}
{157} {} {I Si mi sangre piden, mi sangre les doy I}
{158} {} {I Por los habitantes de nuestra naciƒn. I}
{159} {} {I}

{160} {} {Co, to ju¿ koniec.}
{161} {} {Wygraliœmy! Hura!}
{162} {} {Porobiliœmy tych tubylców jak dzieci!}
{163} {} {Teraz dzicy nie odwa¿¹ siê stan¹æ przeciwko nam.}
{164} {} {Stra¿nicy uciekaj¹ na zachód z podkulonymi ogonami.}
{165} {} {Ach! Teraz to my jesteœmy tutaj gospodarzami.}

{170} {} {Przeklête dzikusy!}
{171} {} {Nie chcê wracaæ do Phoenix, taki wstyd...}
{172} {} {Te dzikusy bêd¹ teraz œwiêtowaæ ¿e nas odparli.}
{173} {} {W koñcu wracamy do domu.}
{174} {} {Jeœli dowództwo siê wacha, to nie mamy tu nic do roboty.}
{175} {} {A mówili mi, ¿e nie powinienem anga¿owaæ siê w tê wojnê...}
