{100} {} {Widzisz Rangersa Oscara.}
{101} {} {Widzisz mê¿czyznê w œrednim wieku. Nosi rêkawice i rewolwer u pasa.}
{102} {} {Chcia³bym, ¿eby twoja technologia przepêdzi³a misjonarzy.}
{103} {} {Nied³ugo opuszczê pueblo. Stra¿nicy nie s¹ ju¿ tutaj mile widziani. To przykre.}
{104} {} {Dziêkujê za pomoc. Twoje oddanie przejdzie do historii.}
{105} {} {Spotkamy siê ponownie, amigo.}
{106} {} {Lepiej niech los ju¿ nie krzy¿uje naszych œcie¿ek.}
{107} {} {Muszê siê przygotowaæ do bitwy. Spotkaj siê ze mn¹ w pobli¿u obozu misyjnego.}

# Przed otrzymaniem zadania
{200} {} {Hello}
{201} {} {Do widzenia}
{202} {} {[Cheat: Wynocha z pueblo, stra¿niku]}
{203} {} {[Cheat: You Win]}
{204} {} {[Cheat: Give Missionary Assassination Quest]}

{210} {} {Ok. Poczekaj minutê. Kim jesteœ? Misjonarzem?}
{211} {} {Nie, zwyk³ym podró¿nikiem. I ju¿ wychodzê.}
{212} {} {Nie, nie, pochodzê ze zniszczonej wioski na pó³nocnym zachodzie.}
{213} {} {Tak? Jest tam kilka osad powi¹zanych z misjonarzami. Wygl¹da na to, ¿e po prostu k³amiesz.}
{214} {} {Mówiê ci... To nie ma znaczenia. Sk¹d pochodzisz?}
{215} {} {Zachowaj to w tajemnicy. Lepiej martw siê o siebie.}
{216} {} {Do zobaczenia nieznajomy.}
{217} {} {Jeœli tak, to co?}
{218} {} {Nie lubiê ciê. Jak wszystkich, którzy przybyli ze wschodu. Dowiem siê, ¿e jesteœ misjonarzem - od razu dostaniesz kulkê.}
{219} {} {Wodzowie mnie wpuœcili.}
{220} {} {Twoje szczêœcie. Ja nie zrobi³bym tego na ich miejscu.}
{221} {} {Nie jestem ze wschodu. Tylko z pó³nocnego zachodu.}
{222} {} {Do zobaczenia nieznajomy.}
{223} {} {A jak ty zosta³eœ wpuszczony? Czy sam nie jesteœ obcy?}
{224} {} {Wódz Geronimo wys³a³ mnie do ciebie. Jak mogê Ci pomóc?}
{225} {} {Có¿, dodatkowa para nóg i r¹k zawsze siê przyda.}
{226} {} {Na jego miejscu nie œpieszy³bym siê tak bardzo. Ale dodatkowa para nóg i r¹k naprawdê mi siê przyda.}
{227} {} {Raport, Komandosie.}
{228} {} {Czy to ty jesteœ Ranger Oscar? Przys³a³ mnie genera³ Mossman. Potrzebuje raportu.}
{229} {} {Dziwna sprawa. Nie rozumiem, dlaczego wys³a³ akurat ciebie, a nie jednego ze Stra¿ników... Ale genera³ wie lepiej.}

{230} {} {Wys³ano mnie do San Brahmin, ¿eby przywróciæ tu porz¹dek. Plemiê próbuje broniæ swojej wolnoœci i niezale¿noœci przed imperium Phoenix. Sytuacja jest trudna i w ka¿dej chwili mo¿e zmieniæ siê z lokalnych potyczek w stan prawdziwej wojny.}
{231} {} {Kontynuuj.}
{232} {} {Powiedz mi wiêcej na ten temat, proszê.}
{233} {} {Kompania Phoenix przyby³a ze wschodu. Rozbili obóz w pobli¿u pueblo i próbuj¹ przepêdziæ plemiê. Mówi¹, ¿e chc¹ zawrzeæ z nimi umowê handlow¹. Ale to kompletny nonsens.}
{234} {} {Co siê sta³o?}
{235} {} {Zadne imperium w historii nie by³o uprzejme wobec tubylców podczas swojej ekspansji. Jak tylko sojusz zostanie zawarty, plemiê zostanie rozbrojone, a braminy zostan¹ rozdzielone miêdzy tych, którzy bêd¹ pos³uszni woli cesarza.}
{236} {} {[Pos³uchaj]}
{237} {} {Phoenix nie mo¿na ufaæ. To banda poszukiwaczy przygód i bandytów. Mieszkañcy po prostu nie znaj¹ innego ¿ycia. Plemiê pasterzy od pokoleñ tworzy w³asn¹ kulturê i tradycje. Nie mo¿e ich zniszczyæ jakiœ chciwy bogacz z miasta.}
{238} {} {Rozumiem. Czyli chcesz pozbyæ siê misjonarzy, ¿eby wrócili do miasta?}
{239} {} {Nasze si³y s¹ nierówne, jeœli chodzi o przyst¹pienie do otwartej bitwy. W obrêbie plemienia dojrzewa roz³am, który Phoenix wywo³a³o wœród m³odzie¿y. Pomó¿ mi przygotowaæ dru¿ynê do wypêdzenia misjonarzy. Musimy opatrzeæ rannych i doprowadziæ syna wodza Chatto do zmiany jego myœlenia.}
{240} {} {OK. Zobaczê co da siê zrobiæ.}
{241} {} {W¹tpie, ¿eby twój oddzia³ sobie z tym poradzi³. Spróbuje znaleŸæ inny sposób.}

{242} {} {Witaj kultysto. Na co liczysz? Och, wiem - na kulê w ³eb.}
{243} {} {Zaczekaj chwilê...}
{244} {} {Kim jesteœ...}
{245} {} {Wynoœ siê! Zeby twoja noga wiêcej nie posta³a w kraju pasterzy. Nikt ciê tu nie zaprasza³, popleczniku Aarona.}
{246} {} {Ok... uspokój siê... wychodzê.}
{247} {} {Komandos? Co za mi³a niespodzianka. Sztab Generalny nie powiadomi³ mnie o twojej osobie. Czy jesteœ tu z w³asnej inicjatywy?}
{248} {} {Nie, tylko przechodzê obok. Co tu siê dzieje? Potrzebujesz pomocy?}
{249} {} {Jestem w drodze. Przepraszam, muszê wkrótce ruszaæ dalej. Mo¿e jeszcze siê spotkamy.}

{250} {} {Nie kazano ci czasem wyjœæ z pueblo? Jeœli nadal bêdziesz siê opieraæ, bêdê musia³ u¿yæ si³y, aby wypêdziæ ciê z tej œwiêtej ziemi.}
{251} {} {To by³ b³¹d. Daj mi szansê, naprawiê to!}
{252} {} {Nie masz tu czego szukaæ. Jesteœ tak samo obcy jak ja. Wiêc usi¹dŸ wygodnie i siê nie odzywaj.}
{253} {} {Mogê robiæ i byæ gdzie mi siê podoba. O co chodzi, g³upku? Swêdz¹ ciê palce? No to dawaj! Siêgaj po swój rewolwer, sukinsynu!}
{254} {} {Omówmy ponownie plan dzia³ania. Co powinno zostaæ zrobione?}

{260} {} {Natychmiast wynoœ siê z pueblo. Dowódca Crook daje ci ostatni¹ szansê na unikniêcie œmierci.}
{261} {} {Nie dam siê zastraszyæ œmierci¹. Wyruszy³em na tê misjê w pe³ni œwiadom zagro¿eñ. Mój cel jest wa¿niejszy ni¿ moje ¿ycie. Próbujê ocaliæ plemiê przed eksterminacj¹ lub zniewoleniem przez si³y cesarskie.}
{262} {} {To koniec. Starsi opowiadaj¹ siê za rozejmem z misjonarzami.}
{263} {} {Rozumiem. Misjonarze ca³kowicie zaciemnili ich umys³y. Nie ma smutniejszego widoku ni¿ bezsilnoœæ w³adzy.}
{264} {} {Wiêkszoœæ jest przeciwko tobie. Zamierzasz teraz odejœæ?}
{265} {} {Muszê wracaæ do bazy bez niczego. Ale nie myœl, ¿e Rangersi tak po prostu to zostawi¹. Nie mo¿na pozwoliæ, aby Imperium Phoenix zmiot³o ca³e narody na swojej drodze w poszukiwaniu w³adzy i zasobów.}
{266} {} {Rozchmurz siê. Nadal bêdziesz mia³ szansê siê zemœciæ. Prawdopodobnie.}
{267} {} {Dobrze. Wynoœ siê st¹d.}
{268} {} {Wiêc nie zamierzasz wyjœæ?}
{269} {} {Nie. Zostanê, by chroniæ plemiê podczas oblê¿enia. I nie bêdê sam. W plemieniu s¹ ludzie, którzy tak jak ja s¹ gotowi stan¹æ w obronie samych siebie i innych.}
{270} {} {Jak sobie ¿yczysz. Ale zosta³eœ oficjalnie ostrze¿ony.}
{271} {} {Rób, co chcesz. Moim zadaniem by³o tylko przekazaæ ci ostrze¿enie.}
{272} {} {Pustynia uczy ciê ukrywania siê wœród piasków i czekania na odpowiedni moment do ataku. U¿yj tej taktyki albo przegrasz.}
{273} {} {Czasami lepiej jest siê wycofaæ, aby zebraæ si³y. Czy tak nie jest w i tym przypadku?}
{274} {} {Tama zosta³a zniszczona i zalana. Twoje dowództwo nie bêdzie ju¿ w stanie wspieraæ walki w San Brahmin.}
{275} {} {To koniec. Wielki Wódz odwróci³ siê od Rangersów.}

# Po otrzymaniu zadania
{300} {} {Raport. Wszelkie informacje o naszym wrogu bêd¹ cenne.}
{301} {} {Nie mam jeszcze nic do zg³oszenia.}
{302} {} {Mi³o ciê widzieæ, Rangerze.}
{303} {} {Mi³o ciê widzieæ, amigo.}

{310} {} {Chcê ciê zapytaæ o Rangersów Arizony.}
{311} {} {Reprezentujemy prawo i porz¹dek w tych krajach.}
{312} {} {Czy Rangersi maj¹ w ogóle bazê?}
{313} {} {Sztab generalny jest na zachodzie i mamy wiele mniejszych placówek w ca³ej po³udniowej Arizonie. Jednak podanie ich dok³adnej lokalizacji by³oby g³upot¹. }
{314} {} {Sztab generalny jest na zachodzie i mamy wiele mniejszych placówek w ca³ej po³udniowej Arizonie. Ale ty ju¿ wiesz, gdzie to jest.}
{315} {} {Gdzie jest twoja odznaka, Stra¿niku?}
{316} {} {Schowa³em j¹ tylko po to, ¿eby nie pogarszaæ sytuacji. Gdy sytuacja w pueblo siê poprawi, odznaka znów bêdzie b³yszczeæ na mojej piersi.}
{317} {} {Nie rozumiem, dlaczego Stra¿nicy bior¹ udzia³ w tej wojnie?}
{318} {} {Mamy dwa cele - zaprzyjaŸniæ siê z plemieniem i powstrzymaæ ekspansjê Phoenix.}
{319} {} {Czy egzekwowanie prawa na plemieniu nie jest tym samym czego chce Phoenix?}
{320} {} {Proste zasady s¹ takie same dla wszystkich - nie zabijaj bez powodu, nie kradnij cudzych rzeczy. Jeœli chodzi o lokalne konwencje, Stra¿nicy musz¹ je zaakceptowaæ i ewentualnie proponowaæ pewne ma³e poprawki.}
{321} {} {Rozumiem.}

{330} {} {Misjonarze uciekli z powrotem do Phoenix.}
{331} {} {Masz niesamowite umiejêtnoœci dyplomatyczne. Nie wiem, jak uda³o ci siê to zrobiæ, ale jestem Ci za to bardzo wdziêczny.}
{332} {} {Drobnostka. Okazali siê raczej niezdecydowani i nieprzygotowani.}
{333} {} {To nie by³o ³atwe. Ale nasza wielka misja wymaga poœwiêcenia.}
{334} {} {Genera³ Mossman nie na darmo powierzy³ ci tak powa¿n¹ misjê. Ma nosa do dobrych ludzi. Teraz mogê wróciæ do bazy po d³ugiej i ¿mudnej misji.}
{335} {} {Powodzenia Oscar.}
{336} {} {Rangersi potrzebuj¹ ludzi takich jak ty. Wpadnij do naszej bazy w Tamie Parkera. Przeka¿ê twoj¹ rekomendacjê genera³owi.}
{337} {} {Dziêki, Stra¿niku. Gdy bêdê w tych stronach, na pewno wpadnê do genera³a.}

{340} {} {Chatto nie wspiera ju¿ Phoenix.}
{341} {} {To dobra wiadomoœæ. Jeœli Chatto nie bêdzie stanowiæ problemu, nasze szanse na wygran¹ wzrosn¹ niebotycznie.}
{342} {} {Co jeszcze nale¿y zrobiæ?}
{343} {} {Pozostaje zebraæ wojowników i ruszyæ do bitwy. Ale niektórzy le¿¹ ranni. To powa¿ny problem, ale niektórzy z nich mogliby zacz¹æ dzia³aæ, gdyby zostali opatrzeni.}
{344} {} {Opatrzê ich.}
{345} {} {Dziêki. Godna pochwa³y inicjatywa. Ale jeœli nie wiesz, jak leczyæ ludzi, przynieœ im przynajmniej leki. Z pewnoœci¹ coœ mo¿na ukraœæ misjonarzom.}
{346} {} {Robi siê.}
{347} {} {Jest jeden problem. Ja nie jestem lekarzem.}
{348} {} {Wiêc u¿yj lekarstw. Z pewnoœci¹ coœ mo¿na ukraœæ misjonarzom.}
{349} {} {Robi siê.}
{350} {} {Wszyscy ranni wrócili do szeregów. Mo¿emy dzia³aæ.}
{351} {} {Swietnie. Pozostaje zebraæ oddzia³ i wszystko zaplanowaæ. Spotkajmy siê na pó³noc od obozu misjonarzy. Przygotuj siê na ciê¿k¹ bitwê.}
{352} {} {Jestem w drodze.}
{353} {} {Chatto odszed³, nie mo¿e ju¿ ingerowaæ w twoje plany.}
{354} {} {To nie jest dobra wiadomoœæ. Chatto by³ liderem wœród m³odych ludzi i móg³ wp³ywaæ na zdanie swoich wspó³plemieñców. Mo¿emy tylko mieæ nadziejê, ¿e ¿aden z tych, którzy siê nie zgadzaj¹ z nami, nie stanie nam na drodze.}
{355} {} {Dobra, nie ma wyboru. Crook czeka na twój atak. No dalej, poka¿, do czego jesteœ zdolny, Stra¿niku!}
{356} {} {Wróæ do Crooka i daj mu znaæ, ¿e przyjmujê jego wyzwanie. Jeœli chce walki, to j¹ dostanie.}
{357} {} {Do widzenia.}
{358} {} {Dobra robota. Ale co z Chatto? Czy uda³o ci siê go przekonaæ?}
{359} {} {Jeszcze nie, zajmê siê tym.}

# podczas potyczki
{360} {} {Hmm. Wydaje siê, ¿e misjonarze nie s¹ gotowi do bitwy. Ich zbytnia pewnoœæ siebie dzia³a na nasz¹ korzyœæ. To dobry czas na rozpoczêcie walki.}
{361} {} {Rangerze Oscar, czy mogê najpierw wykonaæ zwiad? Nied³ugo wrócê.}
{362} {} {Niech rozpocznie siê bitwa!}
{363} {} {Raport: misjonarze uciekli!}
{364} {} {Zwyciêstwo jest nasze! (Wojownicy plemienni radoœnie wiwatuj¹) Nadal potrzebujê czasu, ¿eby siê rozejrzeæ. Wróæ do pueblo, tam podsumujemy wszystko.}
{365} {} {Do zobaczenia.}
{366} {} {Wiêc umrzesz jak pies. Na pró¿no p³acz¹c i b³agaj¹c o litoœæ.}
{367} {} {Wystarczy! Twój czas siê skoñczy³, zwiadowco...}
{368} {} {Wypedziæ st¹d Phoenix!}
{369} {} {Smia³o!}
{370} {} {Jeœli Crook i jego sfora nie poddadz¹ siê natychmiast, bêdziemy musieli go zmusiæ.}
{371} {} {Dam mu znaæ o twoich warunkach.}
{372} {} {Walka siê skoñczy³a. Wygraliœmy!}