{100} {} {Widzisz Stra¿nika.}
{101} {} {Widzisz Stra¿nika w sprzêcie bojowym. Uwa¿nie przygl¹da siê pueblo.}

{110} {} {Wiêc to tobie zawdziêczamy sojusz z plemieniem? Dobra robota, naprawdê dobra robota.}
{111} {} {Wykonujesz dobr¹ robotê, przyjacielu.}
{112} {} {Genera³ wys³a³ nas, ¿ebyœmy pilnowali wodza.}
{113} {} {Jesteœ po naszej stronie, prawda?}
{114} {} {Wielki Wódz czeka na ciebie. WejdŸ.}
{115} {} {Mo¿esz przejœæ.}
{116} {} {* Pozdrawia Ciê *}

{120} {} {Nie powinieneœ by³ tu przychodziæ.}
