{100} {} {Widzisz koczownika.}
{101} {} {Widzisz mê¿czyznê z d³ugimi czarnymi w³osami.}
{102} {} {Och, te grzyby s¹ mocniejsze ni¿ myœla³em...}

{200} {} {Czego chcesz, nieznajomy?}
{1200} {} {Czego chcesz, nieznajoma?}
{201} {} {Zostaw mnie, nieznajomy.}
{1201} {} {Zostaw mnie, nieznajoma.}
{202} {} {Whoa, sk¹d w tobie tyle nieufnoœci?}
{203} {} {Udawaj, ¿e nie wiesz. Zreszt¹ i tak niczego od ciebie nie potrzebujê. A teraz daj mi spokój, czas p³ynie jak piasek miêdzy palcami. Muszê siê œpieszyæ.}
{204} {} {Gdzie siê tak œpieszysz?}
{205} {} {Moja rodzina przygotowuje siê do wyjœcia na pustyniê. Powinniœmy zd¹¿yæ przed pocz¹tkiem sezonu burz piaskowych. Ale nadal nie mogê naprawiæ tego wozu.}
{206} {} {Czy to serio taki problem?}
{207} {} {Kiedyœ mogliœmy wymieniæ czêœci lub poprosiæ o pomoc kogoœ z bladych twarzy. Ale teraz prowadz¹ wojnê przeciwko nam. Nikt nie mo¿e naprawiæ tego oprócz mnie. A ja nie potrafie tego zrobiæ.}
{208} {} {Mogê pomóc.}
{209} {} {Nie potrzebujê niczego od obcych.}
{210} {} {Pozwól, ¿e pomogê. Chcê wam pokazaæ, ¿e nie wszyscy ludzie z zewn¹trz s¹ tacy sami.}
{211} {} {Zrobisz to? Hmm, dobrze. Ale nic za to nie dostaniesz.}
{212} {} {Nie ma problemu. Mo¿esz na mnie polegaæ.}
{213} {} {W ogóle nic? Có¿, wiêc nie bêdê siê z tym œpieszy³.}
{214} {} {Naprawiê wózek, ale nie za darmo. Wiesz, czêœci s¹ warte trochê kapsli.}
{215} {} {Wygl¹da na to, ¿e wszyscy biali ludzie maj¹ obsesjê na punkcie stukotu wszelkiego rodzaju œmieci. Nie mam nic takiego. Ale jeœli naprawdê naprawisz wózek, dam ci trochê jedzenia.}
{216} {} {Przemyœlê tê propozycjê.}
{217} {} {Prawdopodobnie dasz mi trochê zepsutego miêsa. Sam zajmij siê tym wozem.}

{220} {} {Czego chcesz, nieznajomy?}
{1220} {} {Czego chcesz, nieznajoma?}
{221} {} {Zostaw mnie, nieznajomy.}
{1221} {} {Zostaw mnie, nieznajoma.}
{222} {} {Spokój w Twoim domu.}
{223} {} {Do zobaczenia ponownie.}

{230} {} {Twój wóz jest jak nowy.}
{231} {} {Naprawdê to zrobi³eœ! Doznaliœmy tak wielu krzywd ze strony bladych twarzy, ¿e nie mia³em nadziei. Szkoda, ¿e nie mo¿emy ¿yæ w pokoju.}
{1231} {} {Naprawdê to zrobi³aœ! Doznaliœmy tak wielu krzywd ze strony bladych twarzy, ¿e nie mia³em nadziei. Szkoda, ¿e nie mo¿emy ¿yæ w pokoju.}
{232} {} {Serio, nie dasz mi nic za tê us³ugê?}
{233} {} {(wzdycha) Wiedzia³em, ¿e nie mogê ci ufaæ. Jesteœ taki sam jak reszta bladych twarzy, myœlisz tylko o sobie. Tym siê od Ciebie ró¿nimy.}
{234} {} {Nawet nie zaczynaj.}
{235} {} {Czy za dobrze wykonan¹ pracê nie powinno otrzymywaæ siê nagrody? Przecie¿ tak jest sprawiedliwie.}
{236} {} {OK, oto nagroda. Ale nie proœ o nic wiêcej. Muszê siê przygotowaæ do podró¿y.}
{237} {} {No i super.}
{238} {} {Nie potrzebujê niczego w zamian. Pomagam w imiê pokoju.}
{239} {} {Po raz pierwszy widzê bezinteresownego nieznajomego. Dziêkujê Ci. Niech Bramin Pustkowi wska¿e ci drogê w trudnych czasach.}

{250} {} {Jaki jest problem z naprawieniem wozu?}
{251} {} {Nasze plemiê wie, jak oprawiaæ skóry, ale nie zna siê na naprawach takich rzeczy. Prosiliœmy o to bladych w zamian za miêso i skóry. A teraz nie ma nikogo, kogo mo¿na by o to poprosiæ.}
{252} {} {Rozumiem.}
{253} {} {Dlaczego wybierasz siê na pustkowia ze swoj¹ rodzin¹?}
{254} {} {Wêdrujemy po pustyni Sonora, ale w z³ych porach roku gromadzi siê tu ca³e plemiê. Stoj¹c w miejscu, nie zdobêdziemy jedzenia. Braminy potrzebuj¹ trawy, a trawa potrzebujê czasu, aby rosn¹æ. Nie ma te¿ wystarczaj¹cej iloœci lokalnej wody dla wszystkich.}
{255} {} {Rozumiem.}

{260} {} {Co s¹dzisz o sojuszu z obcymi?}
{261} {} {Jeœli gonisz dwa kretoszczury, rozedrzesz sobie spodnie. Nie mo¿esz jednoczeœnie patrzeæ na zachód i wschód.}
{262} {} {Myœlê, ¿e rozumiem, co masz na myœli.}
{263} {} {Musimy byæ sob¹, dopóki mamy wystarczaj¹co du¿o si³y. A jeœli nie bêdziemy mieæ wystarczaj¹cej si³y, nie bêdziemy ju¿ decydowaæ, z kim zawieraæ sojusze. Ten, kto jest silniejszy, zostanie naszym pasterzem.}
{264} {} {Przepraszam za tak bolesne pytanie.}