{100}{}{Widzisz dziewczynê.}
{102}{}{Wygl¹da jakby patrzy³a na wszystkich z góry.}
{103}{}{Widzisz Ashley.}

{200}{}{Najpierw od³ó¿ broñ, wtedy porozmawiamy.}
{201}{}{Dobrze.}
{202}{}{Pieprz siê!}
{203}{}{Lepiej pójdê.}
{204}{}{Mam wiêcej pytañ.}

{300}{}{Mhm... Kolejne niewykszta³cone dziecko z pustkowi. Nazywam siê Ashley i sprzedajê papierowe czasopisma i ksi¹¿ki, ale prawdopodobnie nawet nie wiesz, co to jest. Jak moge pomóc tumanowi takiemu jak ty?}
{301}{}{Jak moge pomóc komuœ takiemu jak ty?}
{302}{}{Poka¿ mi swoje towary.}
{303}{}{Zamknij mordê, zaraz poka¿ê ci "tumana"!}
{304}{}{Sk¹d bierzesz ksi¹¿ki?}
{305}{}{Fajny pies.}
{306}{}{Ale jesteœ ciekawski. Jak ci powiem, to ca³y biznes przepadnie i bêdê musia³a sprzedawaæ zwyk³e drobiazgi jak inni. Powiem ci jedno, mam ludzi, którzy znaleŸli pewne miejsce bogate w takie cuda i od czasu do czasu mnie w nie zaopatruj¹. Wystarczy? To jak, kupujesz coœ?}
{3006}{}{Ale jesteœ ciekawska. Jak ci powiem, to ca³y biznes przepadnie i bêdê musia³a sprzedawaæ zwyk³e drobiazgi jak inni. Powiem ci jedno, mam ludzi, którzy znaleŸli pewne miejsce bogate w takie cuda i od czasu do czasu mnie w nie zaopatruj¹. Wystarczy? To jak, kupujesz coœ?}

{307}{}{To moja duma, Bestia. Niejednokrotnie ratowa³ mnie przed ró¿nymi idiotami i mutantami, wiêc nie radzê go denerwowaæ, bo mo¿esz zostaæ bez rêki. Coœ jeszcze?}

{400}{}{Rozumiem, niczego nie dotykaj, dopóki tego nie kupisz.}
{401}{}{Poprzez czytanie mo¿na siê wiele nauczyæ.}
{402}{}{Ten, który myœli ¿e nigdy nie by³ g³upi, nie mo¿e byæ m¹dry.}
{403}{}{Trudniej jest os¹dzaæ siebie ni¿ innych. Jeœli potrafisz szczerze os¹dziæ siebie, jesteœ m¹drzejszy od wielu istnieñ.}
{404}{}{Jeœli chcesz ukryæ drzewo, ukryj je w lesie.}
{405}{}{Trochê zdrowego rozs¹dku, trochê tolerancji, trochê poczucia humoru i mo¿esz nawet poczuæ siê bardzo komfortowo na tej planecie.}
{406}{}{Najm¹drzejsze osoby najbardziej denerwuje marnowanie czasu.}
{407}{}{Niewa¿ne, ile m¹drych s³ów przeczytasz, niewa¿ne, ile powiesz, co ci przynios¹, jeœli nie zastosujesz ich w praktyce?}

{700}{}{Ksi¹¿ki nale¿y uzyæ na postaci, aby j¹ przeczytaæ.}
{701}{}{Nie nauczy³eœ siê niczego nowego i zmarnowa³eœ swój czas.}
{702}{}{Zdobywasz now¹ wiedzê na temat pu³apek i ukrywania siê.}
{703}{}{Zdobywasz now¹ wiedzê naukow¹.}
{704}{}{Uczysz siê wielu przydatnych informacji o broni energetycznej.}
{705}{}{Poznajesz nowe sztuczki podczas handlowania.}
{706}{}{Uda³o ci siê wiele nauczyæ o praktycznym u¿yciu broni palnej.}
{707}{}{Sta³eœ siê bardziej bieg³y w leczeniu ró¿nych obra¿eñ.}
{708}{}{Zdobywasz now¹ wiedzê o naprawach.}
{709}{}{Zdobywasz now¹ wiedzê na temat przetrwania na pustkowiach.}
{710}{}{Uda³o ci siê wiele nauczyæ o praktycznym zastosowaniu walki wrêcz.}
{711}{}{Zdobywasz now¹ wiedzê na temat projektowania i zawi³oœci zamków.}

{800}{}{Widzisz skrzyniê.}
{801}{}{Widzisz solidn¹ stalow¹ skrzyniê.}
{802}{}{Skrzynia jest zamkniêta i nie mo¿na jej otworzyæ.}
{803}{}{Nie mo¿esz tego otworzyæ, nawet nie próbuj.}
{804}{}{Co za g³upi z³odziej.}
{805}{}{Ta skrzynia nie nale¿y do ciebie.}

{998}{}{Bestia!!! Bierz go!}