{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz mê¿czyznê o wygl¹dzie Meksykanina.}
{102} {} {Dziêkujê bardzo, sir.}
{1102} {} {Dziêkujê bardzo, madame.}
{103} {} {Stra¿nik siê uœmiecha. Wygl¹da na to, ¿e nie ma teraz wielu obowi¹zków.}

{110} {} {OdejdŸ zdrajco!}
{111} {} {Wypad!}
{112} {} {Nawet nie pukaj do naszych drzwi.}

{120} {} {Wynoœ siê!}
{121} {} {Wypad!}
{122} {} {Nie dotykaj tych drzwi.}
{123} {} {Nie mo¿esz tam wejœæ.}
