{100} {} {Widzisz Hilario.}
{101} {} {Widzisz starca w bogacie zdobionym religijnym stroju wed³ug lokalnych standardów.}
{102} {} {Nie masz pojêcia, co zrobi³eœ.}
{1102} {} {Nie masz pojêcia, co zrobi³aœ.}
{103} {} {(}
{104} {} {/ 3) Rozmawia³eœ z mieszkañcami o wakacjach.}

{110} {} {}

# Frazy z otwierajacej sceny przerywnikowej
{120} {} {Bracia i siostry! Dziœ jest dla nas wa¿ny dzieñ! To dzieñ ¿ycia!}
{121} {} {W dniu, w którym mo¿emy powiedzieæ "tak, nadal ¿yjemy. Prze¿yliœmy jeszcze jeden dzieñ. Wielu mia³o pecha, ale nam siê uda³o."}
{122} {} {Podziêkujmy naszym œwiêtym za to b³ogos³awieñstwo, które chroni nas od dzikich bestii i z³odziei...}
{123} {} {I po prostu... Po prostu... Och, uh...}
{124} {} {Lucia, dzisiaj jest twój wspania³y dzieñ.}
{125} {} {IdŸ do koœcio³a i zakoñcz ceremoniê. Wiesz co robiæ. Bêdziemy siê za ciebie modliæ.}

# Pierwszy dialog
{200} {} {(na twój widok t³um cichnie i rozprasza siê; nastêpuje pe³na napiêcia pauza) Uh-uh... Wygl¹da na to, ¿e mamy goœcia... Co za niespodzianka!}
{201} {} {W³aœnie przechodzi³em obok i us³ysza³em œmiechy. Co tu siê dzieje?}
{1201} {} {W³aœnie przechodzi³am obok i us³ysza³am œmiechy. Co tu siê dzieje?}
{202} {} {Co siê tu dzieje? Och, gringo, obchodzimy dzieñ naszych œwietych. Jesteœ na celebracji ¿ycia! Pomó¿ sobie i zostañ z nami. Cieszymy siê z wizyty ka¿dego... kto nie bêdzie nam przeszkadza³.}
{203} {} {To pierwszy raz, kiedy widzê tak szczêœliwe spo³eczeñstwo podczas mojej podró¿y. Z przyjemnoœci¹ zostanê na Waszym œwiêcie.}
{1203} {} {To pierwszy raz, kiedy widzê tak szczêœliwe spo³eczeñstwo podczas mojej podró¿y. Z przyjemnoœci¹ zostanê na Waszym œwiêcie.}
{204} {} {Wszyscy przyjaŸni ludzie na mej drodze do tej pory próbowali mnie oszukaæ. Mam nadziejê, ¿e jesteœcie wyj¹tkiem.}
{205} {} {Có¿. Bienvenido, gringo. W razie jakichkolwiek pytañ proszê o natychmiastowy kontakt ze mn¹. Nazywam siê Hilario Lopez Andrade. Jestem g³ow¹ wioski, a tak¿e kap³anem. Hej! Dlaczego wszyscy umilkli? Kontynuujmy, bracia i siostry!}
{206} {} {Dziêki za goœcinê.}
{207} {} {OK, bêdê tu jeszcze przez chwilê.}
{208} {} {}
{209} {} {}
{210} {} {Wiêc amigo, musisz mieæ du¿o pytañ. Chcia³bym te¿ dowiedzieæ siê wiêcej o tobie, ale nie mam teraz na to czasu. Ktoœ zabra³ koronê na nasz¹ uroczystoœæ. I nie mo¿emy jej znaleŸæ. Koronacja bez korony jest niemo¿liwa. By³oby to pogwa³ceniem naszej tradycji.}
{211} {} {Widzê, ¿e nie masz teraz czasu na rozmowê. Wrócê póŸniej.}
{212} {} {W takim razie spróbujê j¹ znaleŸæ.}
{213} {} {Tego szukasz?}
{214} {} {Tak, to ona! Jak j¹ znalaz³eœ?}
{215} {} {Có¿, le¿a³a sobie na ziemi w pobli¿u.}
{216} {} {To znaczy, ¿e zniknê³a przez przypadek? Uff, ju¿ siê martwi³em, ¿e jeden z mieszkañców zgrzeszy³. Teraz jestem spokojny. Wiesz, jesteœmy najbardziej pokojow¹ osad¹ na ca³ym œwiecie Boga. Od lat nikt tu nie pope³ni³ przestêpstwa.}
{217} {} {To brzmi naprawdê œwietnie.}
{218} {} {Naprawdê?}
{219} {} {To by³a sprawka nastolatka. Nie wiem czemu to zrobi³.}
{220} {} {Ach, tak... Zwyk³a g³upota, gor¹ca krew w m³odym ciele. Nie zwracaj na to uwagi.}
{221} {} {Có¿, jeœli tak.}
{222} {} {Naprawdê?}
{223} {} {Teraz mogê zakoñczyæ ceremoniê. To nasza wspania³a stara tradycja. Co kilka miesiêcy organizujemy koronacjê jednego z mieszkañców, aby przypomnieæ wszystkim o równoœci i o tym, ¿e ka¿dy ma szansê staæ siê u¿ytecznym dla spo³ecznoœci. Tym razem to Lucja zosta³a uhonorowana. Lucia, podejdŸ bli¿ej...}
{224} {} {[Obejrzyj ceremoniê]}
{225} {} {Uff... Ta ceremonia jest taka wyczerpuj¹ca. A ja nie jestem ju¿ taki m³ody. Muszê siê po³o¿yæ, ¿eby odpocz¹æ.}
{226} {} {[Zostaw ceremoniê w spokoju]}
{227} {} {Dlaczego koœció³ jest zamkniêty?}
{228} {} {Nie powinieneœ tam iœæ. Do zakoñczenia uroczystoœci zwyk³ym mieszkañcom równie¿ nie wolno wchodziæ do koœcio³a. To dla nas œwiête miejsce. Proszê, nie kalaj go.}
{229} {} {Ok.}

{230} {} {Co ty tu robisz, przeklêty gringo?! Jak œmiesz bezczeœciæ nasze sanktuarium?!}
{231} {} {Nie martw siê, staruszku. Potwór z piwnicy nie ¿yje. Nie masz siê ju¿ czego baæ.}
{232} {} {M-martwy?! Ty... CO ty zrobi³eœ!!!}
{1232} {} {N-nie ¿yje?! (zdenerwowany) Ty... CO ty zrobi³aœ!!!}
{233} {} {No co, zabi³em potwora. Umar³. Nie ¿yje. Wróci³ do piek³a. Rozumiesz?}
{1233} {} {No co, zabi³am potwora. Umar³. Nie ¿yje. Wróci³ do piek³a. Rozumiesz?}
{234} {} {Dlaczego nam to robisz?! Czy masz pojêcie, ¿e El Diablo by³ naszym patronem?}
{235} {} {Wielbi³eœ tego potwora? Powa¿nie?}
{236} {} {Chroni³ nas przed obcymi i dzikimi bestiami, oczyœci³ spo³ecznoœæ z trêdowatych i s³abych, ludzi zabranych dziêki El Diablo. Przez wiele lat wœród naszych ludzi nie by³o nawet jednego przypadku kradzie¿y. Bez niego upadnie ca³y nasz d³ugofalowy styl ¿ycia. Czy mo¿esz sobie wyobraziæ, co nas teraz czeka?}
{237} {} {Có¿, myœlê, ¿e potrafisz coœ wymyœliæ. Któregoœ dnia ten Twój „patron” i tak by umar³.}
{238} {} {Ach, martwisz siê o swoj¹ pozycjê, kap³anie? Teraz bêdzie ci trudniej og³upiaæ ludzi i rz¹dziæ nimi. To pewne.}
{239} {} {To wszystko twoja wina, gringo. Jeœli umrzesz, œwiat stanie siê lepszy. Dlatego nie pozwolê ci opuœciæ tego koœcio³a.}
{240} {} {Spróbuj mnie powstrzymaæ, staruszku.}
{241} {} {Pope³niasz du¿y b³¹d...}
{242} {} {Oto co siê stanie, gringo. OdejdŸ i nigdy nie wracaj.}
{243} {} {Nie wa¿ siê mi groziæ, staruszku. Zaufaj mi, nie le¿y to w twoim najlepszym interesie.}
{244} {} {Zrobi³em co mia³em do zrobienia. Do widzenia, kap³anie.}
{245} {} {Po tym wszystkim, co s³ysza³em i widzia³em, nie wystarczy ciê tylko straciæ.}
{246} {} {Nie próbuj tu wracaæ! S³yszysz? IdŸ st¹d!}
{247} {} {Tak, tak, cokolwiek powiesz, g³upi staruchu.}
{248} {} {Dlaczego jeszcze tu jesteœ?}
{249} {} {Wychodzê, spokojnie. Po prostu zapomnia³em swocih rzeczy. Do widzenia.}
{1249} {} {Wychodzê, spokojnie. Po prostu zapomnia³am swoich rzeczy. Do widzenia.}
{250} {} {Nie nale¿ysz do Santa Ana. Ca³a tutejsza populacja jest przeciwko tobie. IdŸ st¹d.}
{251} {} {Przez piêtnaœcie lat chroni³em ludzi. I tak mi siê odwdziêczyli! Teraz, gdy El Diablo nie ma z nami, ka¿dy mo¿e mnie winiæ za wszystko. Czy wiesz, jak ciê¿ko by³o mi sk³adaæ te ofiary? Jak cierpia³em w pierwszych latach? Ale zrobi³em to bo musia³em, po to zosta³em wybrany na wodza - uratowa³em mieszkañców. A teraz mówisz, ¿e to by³o z³e? Pieprzyæ twoj¹ opiniê, gringo!}
{252} {} {Wygl¹da na to, ¿e nie da siê ciê przekonaæ. Bêdzie lepiej, jeœli po prostu umrzesz!}
{253} {} {Cokolwiek powiesz. To ju¿ s¹ twoje osobiste sprawy. Pa, kap³anie.}
{254} {} {Nie nale¿ysz do Santa Ana. Teraz ca³a populacja jest przeciwko tobie. IdŸ st¹d.}
{255} {} {Przez piêtnaœcie lat chroni³em mieszkañców tego miejsca. I tak mi siê odwdziêczyli! Teraz, gdy El Diablo nie ma z nami, ka¿dy mo¿e mnie winiæ za wszystko. Czy wiesz, jak ciê¿ko by³o mi sk³adaæ te ofiary? Jak cierpia³em w pierwszych latach? Ale zrobi³em to bo musia³em, po to zosta³em wybrany na wodza - uratowa³em mieszkañców. To koñczy moj¹ misjê. Jestem czysty. Jeœli konieczne jest wygnanie, aby daæ ludziom pokój, niech tak bêdzie. Odchodzê.}
{256} {} {Niespodziewanie dobra decyzja. Jesteœ jednak bardzo m¹dry, staruszku Hilario. Do widzenia.}
{257} {} {Pomoge ci znaleŸæ nowe miejsce do ¿ycia... to miejsce jest w piekle!}