{100} {} {Widzisz kupca.}
{101} {} {Widzisz handlarza w zakurzonej odzie¿y.}

{200} {} {Czeœæ! Dziêki Tobie mamy now¹ trasê karawany. Nigdy bym sobie nawet nie wyobrazi³, ¿e w tych stronach jest jakaœ wioska.}
{201} {} {Jak doszliœcie do porozumienia?}
{202} {} {Nadal prowadzimy negocjacje. Ale Casa Nueva nie ma si³y roboczej. Zwolennicy maj¹ równie¿ nadziejê, ¿e wyhoduj¹ tutaj niektóre roœliny, które s¹ trudne w uprawie w Casa Nueva. Zobaczymy, co mo¿emy tutaj zrobiæ.}
{203} {} {Wszystko wygl¹da coraz lepiej. Muszê iœæ.}

{210} {} {Tak?}
{211} {} {Do widzenia.}
{212} {} {Muszê iœæ.}

{220} {} {Czym handlujesz?}
{221} {} {Przyszed³em raczej na negocjacje, ¿eby siê rozejrzeæ i zapytaæ o potrzeby miejscowej ludnoœci. Ale jeœli masz coœ po¿ytecznego, to jestem gotów pohandlowaæ.}
{222} {} {Bêdê pamietaæ. Narazie.}
{223} {} {Czy wiesz, co siê tutaj sta³o?}
{224} {} {Nie, nikt mi nic nie mówi¹. I nie chcê wiedzieæ. Ka¿dy ma swoje sekrety. Dla mnie liczy siê tylko to, ¿eby nikt nie strzelal nikomu w plecy i dobry interes.}
{225} {} {Dok¹d siê wybierasz po zakoñczeniu negocjacji?}
{226} {} {Oczywiœcie wrócê do Casa Nueva.}
{227} {} {Ok. Narazie.}
{228} {} {Czy mo¿esz mnie zabraæ ze sob¹?}
{229} {} {Oczywiœcie jestem wdziêczny za otwarcie nowej trasy karawany. Ale nie zamierzam ciê chroniæ i nosiæ twoich rzeczy za darmo. Zabranie siê z nami bêdzie ciê kosztowaæ 300 kapsli.}
{230} {} {Oto kapsle. Mogê ruszaæ.}
{231} {} {No to nie. Dotrê tam sam.}
{232} {} {Zabierz mnie ze sob¹ do Casa Nueva.}
