{100} {} {Widzisz Antonio.}
{101} {} {Widzisz miejscowego ch³opca w pomiêtych i brudnych ubraniach.}
{102} {} {Ten wieniec zosta³ zebrany dla Lucii.}

# Pierwszy dialog
{200} {} {Czego chcesz, gringo?}
{201} {} {Och, mówisz po angielsku?}
{202} {} {Trochê. Jestem Antonio. Moi rodzice pochodzili z pó³nocy. Dlatego trochê rozumiem jêzyk obcy.}
{203} {} {Wiêc mam szczêœcie. Ale chyba nie jesteœ zbyt rozmowny. Dlaczego nie bawisz siê ze wszystkimi?}
{204} {} {Nie lubiê tych œwi¹t. I chcê, ¿eby to wszystko siê skoñczy³o.}
{205} {} {Dlaczego?}
{206} {} {Jak mo¿esz œwiêtowaæ dzieñ ¿ycia, w którym zginê³o tak wielu ludzi? Ten staruszek i wszyscy inni s¹ szczêœliwi tylko dlatego, ¿e ¿yj¹. G³upcy.}
{207} {} {Nie mo¿na siê z tym k³óciæ. Tylko g³upiec dziêkuje œwiêtym, którzy wymagali ofiar.}
{208} {} {Dobrze! Lubie ciê, gringo.}
{209} {} {Ok, jeszcze siê tu porozgl¹dam. Do zobaczenia.}
{1209} {} {Ok, jeszcze siê tu porozgl¹dam Do zobaczenia.}
{210} {} {Hej, nie zniechêcaj innych i nie psuj im zabawy. Ka¿dy zas³uguje na odrobinê szczêœcia.}
{211} {} {Jasne...}
{212} {} {Hmm. Krótko mówi¹c, ja zamierzam siê dobrze bawiæ. Do zobaczenia.}

# Powtarzajacy siê dialog
{220} {} {Hej czeœæ!}
{221} {} {Witaj gringo.}
{222} {} {Czego chcesz, gringo?}
{223} {} {Do zobaczenia.}

{230} {} {Wiesz, ¿e ktoœ ukrad³ koronê?}
{231} {} {Nie, nic o tym nie wiem.}
{232} {} {Ok. Wierzê Ci.}
{233} {} {Przecie¿ to twoja sprawka, chcia³eœ zepsuæ wszystkim zabawê?}
{234} {} {(cicho spogl¹da w dó³)}
{235} {} {Czyli mogê potraktowaæ twoje milczenie jako przyznanie siê?}
{236} {} {Nie chcia³em, ¿eby Lucia zosta³a ukoronowana.}
{237} {} {Czy to coœ z³ego?}
{238} {} {Gringo, ty nic nie rozumiesz! Jeœli za³o¿y koronê, to ju¿ nigdy nie bêdê móg³ siê do niej zbli¿yæ. A ja... ja j¹...}
{239} {} {Ch³opie, myœlê, ¿e jesteœ strasznie samolubny.}
{240} {} {Mo¿e tak. Nie obchodzi mnie to!}
{241} {} {Wiêc gdzie jest ta korona ch³opcze?}
{242} {} {Schowa³em j¹ przy pomniku, ¿eby nikt nie móg³ jej znaleŸæ.}
{243} {} {Co to za pomnik?}
{244} {} {Jakiœ ze staro¿ytnych czasów. Lucia i ja spotykaliœmy siê tam potajemnie, a nawet zapisaliœmy nasze imiona na postaciach. Wiêc od razu pomyœla³em o tym miejscu.}
{245} {} {Dobrze, ¿e siê przyzna³eœ. Bêdziesz mia³ mniej k³opotów. Do zobaczenia.}
{246} {} {Nikogo nie obchodzi co chcia³eœ. Powiedz mi, gdzie ukry³eœ koronê!}
{247} {} {Przypomnij mi, gdzie jest ta korona.}

{250} {} {Lucia jest ju¿ bezpieczna. By³em ju¿ naprawdê zdesperowany i myœla³em, ¿e straci³em j¹ na zawsze. Dziêkujê Ci.}
{251} {} {Cieszê siê, ¿e mog³em pomóc.}
{1251} {} {Cieszê siê, ¿e mog³am pomóc.}
{252} {} {Wiêc to dlatego nie uczestniczy³eœ w przyjêciu? Chcia³eœ j¹ uratowaæ przed jej losem?}
{253} {} {Tak. Chcia³em nawet pójœæ do El Diablo zamiast Lucii, ale kap³an mi nie pozwoli³. Powiedzia³, ¿e w osadzie potrzeba wiêcej mê¿czyzn, bo inaczej nie bêdzie nikogo do pracy.}
{254} {} {Los nie do pozazdroszczenia.}
{255} {} {Ale teraz to koniec. Proszê, weŸ to czasopismo. Nie wiem, jak inaczej mogê ci siê odwdziêczyæ.}
{256} {} {Dziêki, ch³opcze. Myœlê, ¿e rzucê na nie okiem.}
{257} {} {Ciekawe. Przekartkujê to kiedyœ po drodze.}

{260} {} {Widzia³em, jak Lucia ucieka z koœcio³a! Co tam siê sta³o? Czy naprawdê zabi³eœ El Diablo?}
{1260} {} {Widzia³em, jak Lucia ucieka z koœcio³a! Co tam siê sta³o? Czy naprawdê zabi³aœ El Diablo?}
{261} {} {Nie martw siê, wszystko jest pod kontrol¹.}
{262} {} {PrzyprowadŸ Luciê z powrotem!}
{263} {} {Spróbujê.}
{264} {} {Nie licz na mnie ch³opcze.}
