{100} {} {Widzisz Luciê.}
{101} {} {Widzisz dziewczynkê w ceremonialnym stroju.}
{102} {} {Dziêki za wszystko.}
{103} {} {Muchas gracias.}
{104} {} {Wianek zosta³ zwrócony prawowitemu w³aœcicielowi.}
{105} {} {Wygl¹da na to, ¿e jest twój. WeŸ to i rób z nim, co chcesz.}
{106} {} {Jest za wczeœnie, ¿eby ci to daæ.}
{107} {} {Lucia wróci³a do osady Santa Ana.}
{108} {} {Antonio i ja czêsto spotykaliœmy siê tutaj w tajemnicy. Zabronili mi utrzymywania relacji z kimkolwiek.}
{109} {} {Ciche, spokojne miejsce. Uwielbia³am siedzieæ tutaj i myœleæ o swoim przeznaczeniu.}

{110} {} {}

{200} {} {¿TŸ otra vez?}
{201} {} {Tutaj jesteœ. Szukam ciê wszêdzie.}
{202} {} {(odwraca siê)}
{203} {} {...I nie jestem sam. Antonio te¿ ciê szuka.}
{204} {} {(zatrzymuje siê w po³owie drogi) Antonio?}
{205} {} {Si, seœora. Szuka³ ciê.}
{206} {} {(wstaje i szlocha) El Diablo... * jêk-jêk * Tu no entiende, gringo. Vivš para esto.}
{207} {} {Nie wiem, co mówisz w swoim jêzyku, ale nie ma potrzeby siê denerwowaæ. ChodŸmy do innych.}
{208} {} {(³apie ciê za rêkaw) Este es mi destino! He perdido el sentido de la vida!}
{209} {} {Chcesz powiedzieæ, ¿e przez ca³e ¿ycie by³aœ przygotowywana na poœwiêcenie? W takim razie rozumiem, dlaczego nie potrafisz zaakceptowaæ wolnoœci.}
{210} {} {(wyczerpana) Bueno. Voy a ir a casa. Dejalo ser.}
{211} {} {Ju¿ dobrze. Upewnie siê, ¿e wrócisz do domu.}
{212} {} {Zostañ tutaj, sprawdzê teren na zewn¹trz.}

{220} {} {Znowu, gringo?}
{221} {} {Tu jesteœ. Szukam ciê wszêdzie.}
{222} {} {(odwraca siê)}
{223} {} {...I nie jestem sam. Antonio te¿ ciê szuka.}
{224} {} {(obraca siê) Antonio?}
{225} {} {Tak, senora. Ukrad³ wieniec z ceremonii, aby uratowaæ ciê przed ni¹.}
{226} {} {(pada na kolana i szlocha) Ale El Diablo... * jêk-jêk * Nie rozumiesz, gringo. By³am na to przygotowana przez ca³e ¿ycie. Wiedzia³am, ¿e ten dzieñ nadejdzie.}
{227} {} {Czy to Ÿle, ¿e jesteœ teraz wolna? }
{228} {} {(³apie ciê za rêkaw) To by³o moje przeznaczenie! Mia³am udaæ siê do El Diablo, aby uratowaæ resztê mieszkañców!}
{229} {} {Rozumiem, dlaczego jesteœ teraz taka zrozpaczona. Ale gdziekolwiek by³em, nigdzie nie ma takiej chorej tradycji. Nikt nie poswiêca krewnych potworom.}
{230} {} {(wyczerpana) OK... ok... wrócê. Niech bêdzie.}
{231} {} {Dobrze. Upewnie siê, ¿e wrócisz do domu.}
{232} {} {Zostañ tutaj, sprawdzê teren na zewn¹trz.}

{240} {} {Voy.}
{241} {} {ChodŸ za mn¹. Upewnie siê, ¿e wrócisz do domu.}
{242} {} {Poczekaj tutaj i nigdzie nie odchodŸ.}
{243} {} {ChodŸmy dalej.}
{244} {} {Estoy cansada.}
{245} {} {No to w drogê.}
{246} {} {Jestem zmêczony.}
