{100} {} {Widzisz Luciê.}
{101} {} {Widzisz dziewczynkê w ceremonialnym stroju.}
{102} {} {Dziêki za wszystko.}
{103} {} {Muchas gracias.}
{104} {} {Wianek zosta³ zwrócony prawowitemu w³aœcicielowi.}
{105} {} {Wygl¹da na to, ¿e jest twój. WeŸ to i rób z nim, co chcesz.}
{106} {} {Jest za wczeœnie, ¿eby ci to daæ.}

{110} {} {}

# Dialog przed ceremonia
{200} {} {Buenas noches.}
{201} {} {Buenos dias.}
{202} {} {Nie przejmuj siê mn¹.}
{203} {} {Czeœæ. Kim jesteœ? Jak masz na imiê?}
{204} {} {Mi nombre es Lucša.}
{205} {} {Lucia. Masz piêkny strój. Czy to œwiêto na twoj¹ czeœæ? }
{206} {} {Hoy ser reina. Este es un gran honor para mš... (chowa podekscytowane oczy) Dime honestamente, ¿te gusta nuestra ciudad?}
{207} {} {Nie rozumiem, cieszysz siê czy p³aczesz?}
{208} {} {(zakrywa twarz) Estoy bien.}
{209} {} {OK, pójdê siê bawiæ.}
{210} {} {Czeœæ. Te¿ mówiê po hiszpañsku. Czy mogê z tob¹ porozmawiaæ?}
{211} {} {Nazywam siê Lucia.}
{212} {} {Wydajesz siê byæ taka wa¿na tutaj, a twój strój jest taki œliczny. Czy to œwiêto na twoj¹ czeœæ?}
{213} {} {Bêdê dzisiaj królow¹. To taka tradycja. I jest to dla mnie wielki zaszczyt... (chowa podekscytowana oczy) Powiedz mi, czy podoba ci siê nasze miasto i te œwiêto?}
{214} {} {Tak, to najpiêkniejsze i najbardziej przyjazne miejsce, w jakim kiedykolwiek by³em!}
{1214} {} {Tak, to najpiêkniejsze i najbardziej przyjazne miejsce, w jakim kiedykolwiek by³am!}
{215} {} {Naprawdê? Och, tak siê cieszê. Zrobiê wszystko, aby tak pozosta³o.}
{216} {} {Oczywiœcie, ¿e jesteœ królow¹... Nie rozumiem, jesteœ szczêœliwa czy p³aczesz?}
{217} {} {(zakrywa twarz) Nic mi nie jest... Porozmawiaj z kimœ innym.}
{218} {} {OK, pójdê siê zabawiæ.}
{219} {} {Nie ma nic lepszego ni¿ moja piêkna Villa. Nie masz pojêcia, o ile jest lepsza.}
{220} {} {Naprawdê? Ach, chcia³abym j¹ zobaczyæ. Ale nigdy nie opuszczê swoich krewnych.}
{221} {} {Nie rozumiem, cieszysz siê czy p³aczesz?}
{222} {} {Czy wiesz, gdzie mog³a siê podziaæ twoja korona?}
{223} {} {A zgubi³a siê? Och, to Ÿle... znajdŸ j¹, proszê! Muszê przejœæ przez ceremoniê, inaczej œwiêci bêd¹ Ÿli!}
{224} {} {Ok, Ok. Spróbujê porozmawiaæ z kimœ innym. Mo¿e ktoœ coœ widzia³.}

# Dialog po ceremonii
{230} {} {(siada ze skruch¹ na pod³odze i spogl¹da w dó³)}
{231} {} {[odejdŸ]}
{232} {} {Hej, jak siê masz?}
{233} {} {(k³adzie g³owê na kolana)}
{234} {} {Wszystko w porz¹dku?}
{235} {} {(cofa rêkê i odpycha ciê) IdŸ hom, gringo! El Diablo ya est aquš!}
{236} {} {El Diablo? Kto to jest? O czym ty w ogóle mówisz? Nie rozumiem...}
{237} {} {El Diablo nie ¿yje. Rozumiesz? (gestykuluje) Martwy!}
{238} {} {(patrzy ze zdumieniem) ¿El Diablo est muerto? ...Nie... ¡Nie! ¡Nie! ¡Nie! (ucieka z koœcio³a)}
{239} {} {Spokojnie, zaczerpnij œwie¿ego powietrza. Teraz mo¿esz sobie na to pozwoliæ.}