{100} {} {Widzisz Enrique.}
{101} {} {Widzisz surowo wygl¹daj¹cego Meksykanina.}

{110} {} {}

# Pierwszy dialog
{200} {} {Hola. Mam na imiê Enrique. Co Ciê sprowadza do naszej osady?}
{201} {} {Skrêci³em w nie to lewo. Jestem tu przez przypadek.}
{202} {} {Minê³o du¿o czasu, odk¹d mieliœmy tu ostatnio obcego z odleg³ych krain. By³oby dobrze ciê o coœ zapytaæ, ale teraz, jak widzisz, mamy œwiêto. Wa¿ny dzieñ - moja córka Lucia ma zaszczyt zostaæ ukoronowana.}
{203} {} {Co to za tradycja?}
{204} {} {Trwa ca³y dzieñ. Dzieñ, w którym dziêkujemy œwiêtym, ¿e jeszcze ¿yjemy. Koñcem ceremonii bêdzie koronacja. Ukoronowany mo¿e byæ ka¿dy mieszkaniec. To pozwala nam siê nawzajem ceniæ i nie zapominaæ, ¿e wszyscy stanowimy zgrany zespó³ poœrodku pustyni, ¿e jesteœmy wszyscy równi.}
{205} {} {Piêkna tradycja. Có¿, bêdê kontynuowaæ zabawê.}
{206} {} {Dziwna tradycja. Ale to ju¿ nie moja sprawa.}

# Powtarzajacy siê dialog
{220} {} {Hola, gringo.}
{221} {} {Hola, amigo.}
{1221} {} {Hola, amiga.}
{222} {} {Adios, Enrique.}

{230} {} {Czy wiesz, ¿e korona ceremonialna siê gdzieœ zapodzia³a?}
{231} {} {Niemo¿liwe! To siê jeszcze nigdy nie zdarzy³o. Ale nie mog³a przecie¿ sama znikn¹æ, prawda? Nie mogê sobie nawet wyobraziæ, jak mog³o do tego dojœæ. Wokó³ sto³u by³o wielu ró¿nych ludzi, zw³aszcza dzieci.}
{232} {} {Rozumiem.}
{233} {} {Dobrze mówisz po angielsku.}
{234} {} {Du¿o podró¿owaliœmy po Sonorze. Dlatego niektórzy z nas trochê rozumiej¹ jêzyk pó³nocny.}
{235} {} {Swoj¹ drog¹, masz niezwykle du¿¹ liczbê dzieci.}
{236} {} {Có¿, to prawda. Dlaczego mia³oby byæ inaczej? Dzieci s¹ naszym szczêœciem i nasz¹ przysz³oœci¹. Chocia¿ wiele z nich nie do¿ywa staroœci.}
{237} {} {A co z Hilario? Ile on ma lat?}
{238} {} {Jest naszym odwiecznym zwierzchnikiem. Nic dziwnego, ¿e jest tak dobrze strze¿ony. Chocia¿ starzec staje siê coraz bardziej paskudny z wiekiem, to z jego pomoc¹ wci¹¿ ¿yjemy.}
{239} {} {Jakie ciekawe miejsca znasz w Sonorze?}
{240} {} {Naprawdê? Czy mo¿esz pokazaæ mi jakiœ ciekawe miejsca na mapie?}
{241} {} {Najbli¿sze miasto to Casa Nueva. Dalej na wschód znajduj¹ siê ruiny Puerto Penasco, a daleko na po³udniu jest fort wojskowy Hermosillo. Mieszkamy w tym miejscu od dziesiêciu lat, wiêc nie wiem, jak siê tam sprawy maj¹.}
{242} {} {Nie wiem, co powiedzieæ, Enrique. Jestem w szoku.}

{250} {} {Hej amigo! Znasz ju¿ nasz sekret, prawda? Co o tym myœlisz?}
{251} {} {Nie wiem, co powiedzieæ. Jestem w szoku.}
{252} {} {Wszyscy tutaj jesteœcie kultystami, którzy oszaleli.}
{253} {} {Nie mam zamiaru was oceniaæ. NajwyraŸniej nie mieliœcie innego wyboru.}
{254} {} {Domyœla³em siê, ¿e tak powiesz. Sam sobie myœlê - kiedy upadliœmy tak nisko, ¿e sprzedaliœmy nasze dusze diab³u? Ale wczeœniej tak nie by³o. Pamiêtam dni bez El Diablo. Jasne, piêkne dni...}
{255} {} {Có¿, to teraz masz szansê zacz¹æ wszystko od nowa.}
{256} {} {Wiêc w koñcu umar³, co? Co za ulga! Ale Hilario tego tak nie zostawi. Bêdzie opiera³ siê zmianom i k³ama³, jakby El Diablo wcale nie umar³. Przez piêtnaœcie lat zbyt przyzwyczai³ siê do w³adzy. Chcê wypêdziæ tego szaleñca z miasta. Pomó¿ mi. Nie wszyscy tutaj s¹ mu tak przeciwni jak ja.}
{257} {} {Chêtnie. Fajnie bêdzie patrzeæ, jak toczy siê po ulicy. IdŸ do koœcio³a, pójdê za tob¹.}
{258} {} {Pozwól mi z nim porozmawiaæ. Spróbujê sam go przekonaæ.}
{259} {} {Moja misja tutaj zakoñczy³a siê œmierci¹ potwora. Teraz sami zajmijcie siê swoimi problemami.}

{260} {} {Wiêc, czy mo¿esz pomóc mi przepêdziæ starca?}
{261} {} {Przepraszam, ale to jest twój problem. RadŸ sobie sam.}
{262} {} {Przysiêgam, jeszcze trochê, a to ja go wykoñczê!}
{263} {} {Pozwól mi z nim porozmawiaæ.}
{264} {} {Hilario nie ¿yje. Nie bêdzie ci ju¿ przeszkadza³.}
{265} {} {Hilario uciek³. Ju¿ nigdy tu nie wróci.}
{266} {} {Tak! Jak cudownie tu bêdzie bez niego. Ju¿ mogê sobie wyobraziæ, jak zmieni siê Santa Ana bez tego staruszka i bez potwora. Nikogo wiêcej ju¿ nie trzeba poœwiêcaæ. Nie ma ju¿ potrzeby k³amaæ i udawaæ, ¿e nic siê nie dzieje. Dziêkujê przyjacielu. Proszê, weŸ mój pistolet jako dowód uznania. Jesteœ teraz naszym Anio³em Stró¿em.}
{267} {} {Zawsze mi³o jest pomagaæ ludziom. Do widzenia, Enrique.}
{268} {} {Czy jest coœ jeszcze, co mogê zrobiæ, aby pomóc ci ostatni raz?}
{269} {} {Wiesz, jestem teraz g³ow¹ wioski. I chcê nawi¹zaæ handel z s¹siednim miastem Casa Nueva. Nie mamy nic specjalnego do zaoferowania, ale postaramy siê negocjowaæ. Czy mo¿esz z³o¿yæ im ofertê? Niech przyœl¹ tu karawanê do negocjacji.}
{270} {} {Ok, zrobiê to.}
{271} {} {Rzadko kiedy tam bywam. Ale bêdê o tym pamietaæ.}
{272} {} {Czy nie pad³o ju¿ zbyt wiele ofiar? Mo¿e nie powinniœmy?}
{273} {} {Jeœli go teraz nie powstrzymamy, w przysz³oœci bêdziemy nadal poœwiêcaæ siê jego pró¿noœci. A im dalej, tym trudniej bêdzie naprawiæ sytuacjê.}
{274} {} {Wiêc nie traæ czasu. ChodŸmy do koœcio³a!}
{275} {} {Kiedyœ istnia³ koœció³, w którym Szatan nie by³ czczony. Czy jesteœ gotowy przyj¹æ na siebie kolejny grzech w tym œwiêtym miejscu?}
{276} {} {Masz racjê. Ale jeœli Hilario zajmie siê tym, co robi³ do tej pory, bêdzie to wina nas wszystkich.}
{277} {} {Dobrze, ¿e siê opamiêta³eœ. Zostawmy starca w spokoju.}
{278} {} {Nie wiem. Mówiê tylko, ¿e lepiej raz zgrzeszyæ, ni¿ znosiæ to co siê tu dzieje. ChodŸmy do koœcio³a i zakoñczmy to!}
{279} {} {Nie œpiesz siê. Chcê tylko porozmawiaæ z Hilario bez u¿ycia brutalnej si³y. Zaczekaj tutaj.}
{280} {} {A jednak mia³eœ racjê - powinieneœ by³ pozbyæ siê Hilario.}
{1280} {} {A jednak mia³eœ racjê - powinieneœ by³ pozbyæ siê Hilario.}
{281} {} {Nie wiem. Mówiê tylko, ¿e lepiej raz zgrzeszyæ, ni¿ znosiæ to co siê tu dzieje. Skoñczmy z tym tu i teraz!}
{282} {} {Niestety, Casa Nueva prze¿ywa ciê¿ki okres. Powinieneœ zapomnieæ o handlu z tym miastem.}
{283} {} {Przykro mi to s³yszeæ. Nic, jakoœ bez nich prze¿yjemy. Dziêkujê za ostrze¿enie.}
{1283} {} {Przykro mi to s³yszeæ. Nic, jakoœ bez nich prze¿yjemy. Dziêki za ostrze¿enie.}
{284} {} {Proszê.}
{285} {} {Hola, amigo. Niedawno przyjecha³a do nas karawana z Casa Nueva. Dziêki za pomoc.}
{286} {} {Jest sprawa... Hilario odszed³ do innego œwiata. Nie pytaj, jak to siê sta³o.}
{287} {} {Hilario uciek³ z wioski, gdy zda³ sobie sprawê, ¿e jego w³adza tutaj dobieg³a koñca. W¹tpiê czy wróci.}

{290} {} {Jak doszliœcie do tego wszystkiego?}
{291} {} {To d³uga historia. Wszystko zaczê³o siê ponad piêtnaœcie lat temu.}
{292} {} {Nie chcê nawet tego s³uchaæ. Zmieñmy temat.}
{293} {} {Powiedz mi wiêcej.}
{294} {} {Byliœmy ludem koczowniczym i przemierzaliœmy pustyniê Sonora w poszukiwaniu odpowiedniego miejsca do ¿ycia. I kiedyœ ten potwór przylgn¹³ do nas. Sciga³ nasz¹ karawanê i od czasu do czasu zabiera³ jedn¹ osobê lub jedno zwierzê. Nie mogliœmy siê przed nim broniæ ani uciec - by³ za silny i za szybki.}
{295} {} {Kontynuuj.}
{296} {} {To przera¿aj¹ce! Lepiej zakryjê uszy i pójdê ju¿ sobie.}
{297} {} {Wtedy Hilario wpad³ na pomys³ sk³adania w ofierze zwierz¹t, aby unikn¹æ ofiar w ludziach. Wkrótce jednak byd³o siê skoñczy³o. Dlatego potem zaczêliœmy oddawaæ starszych i chorych. Z biegiem czasu oni te¿ siê skoñczyli. Na szczêœcie El Diablo by³ ju¿ spokojniejszy i wymaga³ coraz mniej ofiar. Uda³o nam siê odnaleŸæ równowagê w tym wszystkim.}
{298} {} {Teraz wszystko jasne.}
{299} {} {Plusem jest to, ¿e El Diablo atakowa³ dzikie bestie i bandytów, którzy nam grozili. W pewnym sensie staliœmy siê jego stadem, pas³ nas i zjada³ w czasie g³odu.}
{300} {} {I nadal sk³adaliæcie mu ofiary?}
{301} {} {Raz na kilka miesiêcy sk³adaliœmy mu ofiarê, któr¹ specjalnie w tym celu przygotowywaliœmy. Aby nikogo nie straszyæ, Hilario zrobi³ z tego ceremoniê, a nawet zacz¹³ g³osiæ ideê Boskiego Oczyszczenia. Wiêc ¿yliœmy tak ramiê w ramiê z prawdziwym diab³em. Dopóki siê nie pojawi³eœ, gringo.}
{302} {} {Mam nadziejê, ¿e wrócicie do normalnoœci. Ja muszê ju¿ iœæ. Bywaj.}
{303} {} {WstydŸ siê. W Villi zawsze trzymaliœmy siê razem. A tak przy okazji, po tej historii zachcia³o mi siê wróciæ do mojego domu. Do widzenia.}