{100} {} {Widzisz goœcia.}
{101} {} {Widzisz mê¿czyznê w zakurzonym ubraniu. Wygl¹da na to, ¿e przeszed³ w nim wiele mil.}
{102} {} {Wow. Wiedzia³em, ¿e Blacharze s¹ zdolni, ale nawet bym o tym nie pomyœla³...}
{103} {} {Co jest nie tak z tym cholernym miastem?}
{104} {} {...}

#Pierwsze spotkanie
{200} {} {Hej, to ty? Co za niespodzianka. Nie s¹dzi³em, ¿e ciê tu spotkam.}
{201} {} {A ty...}
{202} {} {Pamiêtasz jak przynios³eœ mi list w Phoenix? By³em wtedy bardzo zdziwiony i myœla³em, ¿e to jakieœ oszustwo. Jak siê okazuje, myli³em siê.}
{1202} {} {Pamiêtasz jak przynios³aœ mi list w Phoenix? By³em wtedy bardzo zdziwiony i myœla³em, ¿e to jakieœ oszustwo. Jak siê okazuje, myli³em siê.}
{203} {} {Ok, ale co ciê sprowadza do tego zapomnianego miasta?}
{204} {} {}
{205} {} {}
{206} {} {W centrum miasta jest opuszczona ³aŸnia. Szukam w³aœciciela tego lokalu.}
{207} {} {LaŸnia? Tutaj, na œrodku pustyni?}
{208} {} {No tak. W mieœcie jest du¿o wody, wiêc przyje¿dzaj¹ tu karawany z ca³ej okolicy. To prawda, ¿e woda nie jest sprzedawana ka¿demu.}
{209} {} {Dlaczego szukasz w³aœciciela?}
{210} {} {Jest moim krewnym. Otrzyma³em od niego list z propozycj¹ przyjazdu i pracy w ³aŸni. I oto jestem. Ale nigdzie go nie ma.}
{211} {} {Czy ty serio odebra³eœ list i od razu przyjecha³eœ do obcego miasta?}
{212} {} {Dlaczego nie? Po tej potwornej eksplozji w Phoenix sytuacja siê pogorszy³a.}
{213} {} {Eksplozji? Jakiej eksplozji?}
{214} {} {Nie wiesz? Koœció³ Swiêtego Ognia eksplodowa³, wylecia³ w powietrze. Poof-f! Dos³ownie.}
{215} {} {Wow. Czy miejscowi wiedz¹ coœ o twoim krewnym?}
{216} {} {Miejscowi nic nie wiedz¹. LaŸnia jest zamkniêta, a w³aœciciela dawno nie widziano. Rozmawia³em z burmistrzem, ale nazwa³ mnie kolejnym oszustem i wyrzuci³ na ulicê.}
{217} {} {Co zamierzasz teraz zrobiæ?}
{218} {} {Jeszcze nie wiem. Zostanê tu trochê d³u¿ej, mo¿e w koñcu pojawi siê mój wujek. Jeœli siê czegoœ dowiesz, daj mi znaæ, dobrze? Nie pozostanê d³u¿ny.}
{219} {} {Có¿, powodzenia w szukaniu.}
{220} {} {Tak. Zobaczê.}
{221} {} {Do widzenia.}
{222} {} {To musi byæ jakiœ b³¹d.}
{223} {} {Nie s¹dzê.}
{224} {} {No có¿. Tkwij dalej w tym z³udzeniu.}
{225} {} {Hmm. A mo¿e po prostu udajesz, ¿e jesteœ jego krewnym, aby zaj¹æ jego miejsce?}
{226} {} {Bzdury. To prawda, dawno siê nie widzieliœmy. Ale mój wujek sam wys³a³ list za poœrednictwem kuriera, mo¿na to sprawdziæ. Poza sam da³eœ mi jego list.}
{1226} {} {Bzdury. To prawda, dawno siê nie widzieliœmy. Ale mój wujek sam wys³a³ list za poœrednictwem kuriera, mo¿na to sprawdziæ. Poza sama da³aœ mi jego list.}

# Powtarzajacy siê dialog na parkingu
{250} {} {Och, to ty. W³aœnie o tobie myœla³em. Dwóch nieznajomych w tym samym mieœcie. Powinniœmy siê trzymaæ razem, co?}
{251} {} {Brzmi bardzo podejrzanie. Do zobaczenia.}
{252} {} {Oczywiœcie. Do zobaczenia.}
{253} {} {Swoj¹ drog¹, jak masz na imiê?}
{254} {} {Po prostu mów mi Steve.}
{255} {} {Ok, Steve. Mo¿e powiesz mi jeszcze raz, co tu robisz?}
{256} {} {Do zobaczenia, Steve.}
{257} {} {Powiedz mi jeszcze raz, kogo szukasz?}

# scena 1
{260} {} {Czy by³eœ na miejscowym cmentarzu? Wygl¹da na to, ¿e le¿y tam ten twój wujek.}
{261} {} {Co? Wiêc nie ¿yje? Teraz wszystko jasne, dlaczego burmistrz próbuje mnie wyrzuciæ. Ale jak to siê sta³o?}
{262} {} {S¹dz¹c po masowych grobach, zginê³o tu wielu ludzi. Czy wiesz coœ na ten temat?}
{263} {} {Hmm. O ile wiem, niedawno toczy³y siê tu wojny klanów. Dlatego miejscowi denerwuj¹ siê, gdy próbujesz zapytaæ ich o przesz³oœæ. Jeœli mój wujek pad³ ofiar¹ tej wojny, pozostaje to tylko zaakceptowaæ.}
{264} {} {Czyli zostajesz z niczym?}
{265} {} {Nie, nie. LaŸnia nale¿a³a do mojego wuja. A ja jestem jego krewnym. Czy nie powinienem jej odziedziczyæ?}
{266} {} {Zartujesz sobie ze mnie? Serio mimo tych wszystkich zagro¿eñ zamierzasz tu zostaæ?}
{267} {} {Widzisz... Szczerze, sprawy w Phoenix te¿ nie uk³ada³y siê dobrze. By³em kompletnie zdesperowany, próbuj¹c zdobyæ tyle kasy ile siê da³o na walkach. Ale tutaj mogê o¿ywiæ biznes mojego wuja i wzbogaciæ siê. Dlaczego, do diab³a, mam przegapiæ tak¹ szansê?}
{268} {} {Och, czyli to tak. Smieræ twojego krewnego by³a bardzo pomocna, prawda?}
{269} {} {O czym ty mówisz? Mogê o¿ywiæ biznes mojego wuja i wzbogaciæ siê. By³oby g³upot¹ przegapiæ tak¹ szansê od losu.}
{270} {} {Swietny pomys³. Warto spróbowaæ. Potrzebujesz pomocy?}
{271} {} {Musisz byæ serio zdesperowany, aby podejmowaæ takie ryzyko.}
{272} {} {Có¿, teraz najwa¿niejsze jest uzyskanie przychylnoœci burmistrza. Nie chce siê ze mn¹ kontaktowaæ, stra¿nicy mnie do niego nie wpuszcz¹. Mo¿esz z nim porozmawiaæ?}
{273} {} {Co otrzymam za t¹ przys³ugê?}
{274} {} {Oczywiœcie ka¿dy chce zarobiæ. Nie martw siê, zap³acê, gdy siê wzbogace. Jesteœmy partnerami. Musisz tylko trochê poczekaæ.}
{275} {} {Spróbujê go przekonaæ.}
{276} {} {Dziêkujê partnerze. Co ja bym bez ciebie zrobi³?}
{277} {} {Do zobaczenia póŸniej.}
{278} {} {Myœl o rozmowie z tym tyranem przera¿a mnie. ZnajdŸ kogoœ innego.}
{279} {} {Rozumiem. No nic, jakoœ coœ wymyœlê. Mimo wszystko dziêki za pomoc.}
{280} {} {Do widzenia, kolego.}
{281} {} {Tylko têdy przeje¿dzam, nie mam czasu czekaæ na pierwszych klientów.}

# etap 2
{300} {} {No i co powiedzia³ burmistrz? Uda³o ci siê z nim porozmawiaæ?}
{301} {} {Nie, nie mia³em na to czasu. Poczekaj chwilê.}
{302} {} {Burmistrz miasta nie ¿yje. Teraz nic nie stoi na przeszkodzie, aby rozpocz¹æ w³asn¹ dzia³alnoœæ.}
{303} {} {Martwy? Cholera, co jest nie tak z tym miastem? Ok, nie chcê znaæ szczegó³ów. Ale prawda jest taka, ¿e muszê wzi¹æ k¹piel, zanim zrobi to ktoœ inny.}
{304} {} {Ok, spotkamy siê tam...}
{305} {} {Burmistrz uzna³ twoje prawo do ³aŸni. Mo¿esz za³o¿yæ w³asn¹ firmê.}
{306} {} {Wow, wiesz, jak negocjowaæ z ludŸmi. Teraz muszê wzi¹æ k¹piel, zanim burmistrz zmieni zdanie.}
{307} {} {Ok, spotkamy siê tam...}
{308} {} {Burmistrz ¿¹da, ¿ebyœ opuœci³ miasto. Natychmiast.}
{309} {} {Co ci siê sta³o? Czy nie widzisz, ¿e to niesprawiedliwe? Prawnie posiadam tê ³aŸniê.}
{310} {} {Przepraszam, spróbujê przekazaæ tê wiadomoœæ burmistrzowi.}
{311} {} {Jeœli ¿ycie jest ci drogie, odejdziesz teraz.}
{312} {} {Ach, wszystko jasne. Myœla³em, ¿e jesteœmy partnerami. Okaza³o siê, ¿e jesteœ zwyk³ym skorumpowanym psem.}
{1312} {} {Ach, wszystko jasne. Myœla³em, ¿e jesteœmy partnerami. Okaza³o siê, ¿e jesteœ zwyk³¹ skorumpowan¹ suk¹.}
{313} {} {Omówimy to póŸniej. Du¿o póŸniej.}
{314} {} {Nie ¿artujê. Wynoœ siê z miasta.}
{315} {} {Nie odejdê. To mój rodzinny biznes. I nie zostawiê go.}
{316} {} {Nie zostawiasz mi wyboru. Jeœli nie chcesz samemu odejœæ, pomogê ci.}
{317} {} {W ka¿dym razie rób, co chcesz.}
{318} {} {Pos³uchaj mnie. Policzê do piêciu, a potem dobêdê broni. Jeden, dwa...}
{319} {} {Hej, hej, czekaj...}
{320} {} {...trzy.}
{321} {} {Daj spokój, to ¿art. Oczywiœcie zostañ tu jak chcesz, to twój problem.}
{322} {} {OK, wychodzê, patrz.}
{323} {} {I nie wracaj.}

{330} {} {Zobacz, co zrobili miejscowi z tym niegdyœ piêknym lokalem. Ohydni barbarzyñcy.}
{331} {} {Rozejrzê siê, jeœli nie masz nic przeciwko.}
{332} {} {Co siê sta³o?}
{333} {} {Oprócz najcenniejszych rzeczy, które zabrali st¹d, prawdziwy problem tkwi w systemie ciep³ej wody.}
{334} {} {Niech zgadnê, nie dzia³a?}
{335} {} {Ktoœ próbowa³ ukraœæ boiler, ale przewróci³ go i uszkodzi³. Nie wiem jeszcze jak to naprawiæ.}
{336} {} {Có¿, powodzenia. Na pewno ja tego nie zrobiê.}
{337} {} {Poka¿. Na pewno naprawiê tego potwora kawa³kiem z³omu.}
{338} {} {Boiler ju¿ dzia³a. Mo¿esz podgrzaæ wodê i siê umyæ.}
{339} {} {Uda³o Ci siê go naprawiæ? Cholera! Teraz biznes na pewno siê rozkrêci. Dziêkujê, du¿o dla mnie zrobi³eœ. Zatrzymaj siê u mnie, jeœli chcesz siê odœwie¿yæ.}
{1339} {} {Uda³o Ci siê go naprawiæ? Cholera! Teraz biznes na pewno siê rozkrêci. Dziêkujê, du¿o dla mnie zrobi³aœ. Zatrzymaj siê u mnie, jeœli chcesz siê odœwie¿yæ.}
{340} {} {Bêdê pamietaæ. Bywaj.}

{350} {} {Jak siê masz?}
{351} {} {Jak siê masz? Chcesz siê umyæ?}
{352} {} {Chcesz siê umyæ? ChodŸ, w³aœnie znalaz³em trochê starej soli morskiej.}
{353} {} {Chcesz siê umyæ? Najwy¿szy czas, na zewn¹trz jest tak strasznie gor¹co.}
{354} {} {Zdecydowanie muszê siê umyæ. Nie bój siê, nie bêdê ciê zbytnio obci¹¿a³.}
{355} {} {Lazienka jest ju¿ dostêpna. WchodŸ, czas zmyæ z siebie brud po tych wszystkich podró¿ach.}
{356} {} {Bywaj, Steve.}

#Reszta
{400} {} {Muszê siê umyæ. Ile to kosztuje?}
{401} {} {Policzê ci tylko za drewno na opa³ i wodê. To bêdzie kosztowaæ }
{402} {} { kapsli.}
{403} {} {Nie staæ mnie na taki luksus. Nastêpnym razem.}
{404} {} {Brzmi fair. Proszê bardzo...}

{410} {} {Twój biznes powinien ju¿ przynosiæ ³adne zyski.}
{411} {} {Wiesz, niezupe³nie. Karawany podró¿uj¹ sezonowo, wiêc zdarzaj¹ siê sytuacje, gdy w mieœcie w ogóle nie ma goœci. Do tego nie ka¿dy jest sk³onny zap³aciæ mi za tak¹ us³ugê. Ale wystarczy na spokojne ¿ycie.}
{412} {} {Zapomnia³eœ o naszej umowie?}
{413} {} {Moja cierpliwoœæ siê koñczy. Gdzie jest mój udzia³ z tego biznesu?}
{414} {} {O czym ty mówisz? Nic ci nie jestem winien. Dalej, wynoœ siê st¹d, muszê jeszcze wyczyœciæ wannê.}
{415} {} {O czym?}
{416} {} {Ty draniu.}
{417} {} {Oczywiœcie, partnerze. Oszczêdza³em dla ciebie kapsle. Masz, 200 sztuk. A teraz przepraszam, ale wanna wymaga czyszczenia.}
{418} {} {Dziêki, robienie interesów z tob¹ to *czysta* przyjemnoœæ. Powodzenia, Steve.}
{419} {} {To wszystko? Niewiele tego, spodziewa³em siê wiêcej. Wygl¹da to kiepsko.}
{420} {} {Jeœli nie chcesz oddaæ kapsli, wezmê je si³¹. Stój spokojnie, draniu...}

{430} {} {Blacharze wys³ali tutaj swojego ambasadora. Wiesz cokolwiek o tym?}
{431} {} {Widzia³em tego Blacharza, ale z nikim nie rozmawia³ i poszed³ prosto do burmistrza. Nigdy wiêcej go nie widzia³em.}
{432} {} {To zawsze trochê informacji. Bywaj.}
{433} {} {Jesteœ bezu¿yteczny. Bywaj.}