{100} {} {Widzisz Christinê.}
{101} {} {Widzisz córkê hrabiego Bustosa.}
{102} {} {Jeœli z³odzieje nas zobacz¹, prawdopodobnie nas zastrzel¹.}
{103} {} {Tak siê cieszê, ¿e to koniec.}
{104} {} {* p³acze *}

# Pierwszy dialog
{200} {} {Nie dotykaj mnie, brudny rozbójniku!}
{201} {} {Uspokój siê. Twój ojciec mnie przys³a³.}
{202} {} {Mój... tato? Tatusiu... Wynoœmy siê st¹d szybko.}
{203} {} {Rozwi¹¿ê ciê... ChodŸ, ale b¹dŸ cicho.}
{204} {} {Nie mog¹ nas zobaczyæ. Jeœli z³odzieje nas zobacz¹ to z pewnoœci¹ nas zastrzel¹.}
{205} {} {Ok, chodŸmy.}
{206} {} {Teraz nie czas na to. Bêdziesz musia³a trochê poczekaæ.}
{207} {} {Co? Opuszczasz mnie? Uwolnij mnie natychmiast!}
{208} {} {B¹dŸ cicho, wkrótce wrócê.}
{209} {} {Naprawdê, naprawdê nie powinno nas tu byæ.}

# Powtarzajacy siê dialog
{210} {} {Czeœæ.}
{211} {} {Do widzenia.}
{212} {} {Jesteœ ju¿ bezpieczna. Bandyci zwracaj¹ ci wolnoœæ.}
{213} {} {Naprawdê? Wiêc wynoœmy siê st¹d natychmiast, bo jeszcze zmieni¹ zdanie.}
{214} {} {Oczywiœcie, chodŸmy.}
