{100} {} {Widzisz barmana.}
{101} {} {Widzisz zwyk³ego barmana.}
{102} {} {Przepraszam, ale TEGO tu nie mo¿na wnosiæ.}

{110} {} {Hej, chcesz zalaæ gard³o?}
{111} {} {Chcesz drinka?}
{112} {} {Myœla³em, ¿e bêdzie tu wiêcej klientów.}
{113} {} {Nie martw siê, wszyscy tu s¹.}
{114} {} {Och, w koñcu widzê klienta.}

{200} {} {Hej, czeœæ! Dziêki za zatrzymanie siê.}
{1200} {} {Och, pani. Moje pozdrowienia. Dziêki, ¿e wpad³aœ.}
{201} {} {Czy to miejsce nie zosta³o opuszczone?}
{202} {} {Tak, tak by³o. Ale teraz sprawy w mieœcie id¹ ku lepszemu i postanowi³em odnowiæ to miejsce.}
{203} {} {A burmistrz nie mia³ nic przeciwko?}
{204} {} {Kiedyœ nawet nie chcia³ s³yszeæ o tym miejscu, ale teraz jest trochê inaczej. Nie wiem, co go spotka³o, dlatego lepiej zajmijmy siê tym miejscem, zanim bêdzie za póŸno.}
{205} {} {Rozumiem. Czy mogê prosiæ o drinka?}

{210} {} {Siadaj. Wybór jest niewielki, ale lepszy ni¿ nic.}
{211} {} {Muszê iœæ.}
