{100} {} {Widzisz Hrabiego Bustosa.}
{101} {} {Widzisz mê¿czyznê w dopasowanym, ale zniszczonym garniturze. Jego siwow³ose skronie wydaj¹ siê wskazywaæ na trudn¹ przesz³oœæ.}
{102} {} {Dziêkujê za pomoc. Do zobaczenia w mojej rezydencji.}
{103} {} {Wróæ do rezydencji. Tam porozmawiamy.}

# Pierwszy dialog
{200} {} {(Zbli¿aj¹c siê do budynku baru, zauwa¿asz t³um uzbrojonych ludzi; burmistrz aktywnie z nimi dyskutuje).}
{201} {} {Ehem.}
{202} {} {Och, to ty... PodejdŸ bli¿ej. Potrzebujemy pomocy.}
{203} {} {Co tu siê dzieje?}
{204} {} {W barze s¹ bandyci. Z³apali moj¹ córkê i ¿¹daj¹ okupu. Raczej nie da siê dojœæ z nimi porozumienia. Zap³acê górê kapsli temu, kto uratuje Christinê.}
{205} {} {Tak, wygl¹da to na trudny przypadek.}
{206} {} {I co ja mam z tym zrobiæ?}

# Powtarzajacy siê dialog
{210} {} {Jakieœ sugestie?}
{211} {} {Hej, moje ¿ycie jest mi bardzo cenne, na mnie nie licz.}
{212} {} {Wiêc odsuñ siê na bok i nie wchodŸ w drogê. Byæ mo¿e widok wielkiego t³umu przestraszy bandytów i sami zrezygnuj¹.}
{213} {} {To ma sens. Popatrzê sobie z boku.}
{214} {} {Pozwól, ¿e z nimi porozmawiam. Mo¿e uda mi siê ich przekonaæ, ¿eby sami odeszli.}
{215} {} {Przekonaæ bandytów? To niemo¿liwe. Dobra, ale pamiêtaj ¿e nie uratujê twojego ty³ka, jeœli ciebie te¿ wezm¹ jako zak³adnika.}
{216} {} {Jednak poczekam z boku i zobaczê jak to siê skoñczy. Powodzenia.}
{217} {} {Nie martw siê o mnie. Potrafiê negocjowaæ.}
{218} {} {Proponujê frontalny atak. Nie ma sensu z nimi rozmawiaæ.}
{219} {} {Wygl¹da na to, ¿e nie mam wyboru... Kto chce wzi¹æ udzia³? Zap³acê ka¿demu, kto mo¿e pomóc uratowaæ moj¹ córkê.}
{220} {} {Czekaj, nie œpieszmy siê. Pozwól mi oceniæ sytuacjê.}
{221} {} {Wychodzê w to. Rozwalmy tych sukinsynów!}
{222} {} {Smia³o!}
{223} {} {Tak!}
{224} {} {Dlaczego nie zap³aciæ im okupu?}
{225} {} {Z¹daj¹ za du¿o. Miasto jest biedne. I dalej...}
{226} {} {Coœ wiêcej?}
{227} {} {Chc¹ wymieniæ Christinê na mnie, aby utorowaæ sobie drogê na pustkowia. Nie mo¿na im ufaæ.}
{228} {} {Zakraœæ siê tam w TYM? Niez³y pomys³, ale bardzo szybko zostajesz zauwa¿ony. Masz wiêcej pomys³ów?}
{229} {} {Rozumiem...}

{250} {} {Jak widzisz, twoja córka jest bezpieczna.}
{251} {} {Ach, Christina... Jak siê masz? Sprawiê, ¿e ci dranie zap³ac¹ za to, co zrobili!}
{252} {} {Zamierzasz zaatakowaæ bar?}
{253} {} {Oczywiœcie. Jeœli inni im podobni dowiedz¹ siê o tej historii, moja córka bêdzie codziennie porywana. Musimy siê ich pozbyæ i to teraz.}
{254} {} {Nie mo¿na siê z tym k³óciæ. Przestêpcy musz¹ zostaæ ukarani. Kiedy zaczynamy atak?}
{255} {} {Nie licz na mnie. Nie wezmê udzia³u w tej masakrze.}
{256} {} {Twoja córka nie ¿yje. Widzia³em to na w³asne oczy.}
{1256} {} {Twoja córka nie ¿yje. Widzia³am to na w³asne oczy.}
{257} {} {Nie! Nie? Nie!}
{258} {} {Przykro mi.}
{259} {} {(oszalaly) Ci dranie s³ono za to zap³ac¹. Zabiæ KAZDEGO! Zap³acê za g³owê ka¿dego sukinsyna, który jest w barze!}
{260} {} {Swietnie, wchodzê w to.}
{261} {} {Na mnie nie licz. Nie chcê braæ udzia³u w ¿adnych strzelaninach.}
{262} {} {PrzyprowadŸ moj¹ córkê. Natychmiast.}
{263} {} {Nie teraz. Te zbiry nie poddadz¹ siê tak ³atwo.}
{264} {} {Zas³uguj¹ na karê. Ale atakowanie ich, gdy s¹ w barze, jest zbyt ryzykowne. Pozwól im odejœæ, ¿eby unikn¹æ niepotrzebnych ofiar w ludziach.}
{265} {} {Te¿ nie chcê kolejnej rzezi w moim mieœcie. I tak mamy ju¿ cholernie z³¹ reputacjê. Pozwalam im odejœæ. Wracamy do posiad³oœci.}
{266} {} {Prawid³owa decyzja, panie burmistrzu...}
{267} {} {To nie ma wiêkszego sensu. Ju¿ opuszczaj¹ miasto.}
{268} {} {Masz niesamowite umiejêtnoœci perswazji. To nawet trochê podejrzane. Có¿, pozwolê im siê st¹d wydostaæ. Wracamy do posiad³oœci.}
{269} {} {Prawid³owa decyzja, panie burmistrzu...}
{270} {} {Cel jest jasny...}
{271} {} {Nie licz na mnie. Wyj¹tkowo nie przelejê dziœ niczyjej krwi.}
{272} {} {Bandyci nie wyjd¹, dopóki nie spe³nisz ich ¿¹dañ.}
{273} {} {Wiêc nie mam wyboru. Wszyscy bêd¹ musieli zostaæ rozstrzelani. Czy mo¿esz wyci¹gn¹æ moj¹ córkê z baru niezauwa¿on¹?}
{274} {} {Daj mi czas, spróbujê j¹ niepostrze¿enie wyci¹gn¹æ.}
{275} {} {To niemo¿liwe. Proponujê frontalny atak i to teraz!}
{276} {} {Spokojnie, hrabio. Wszyscy najeŸdŸcy w barze ju¿ nie ¿yj¹.}
{277} {} {Niesamowite! Nigdy wczeœniej nie mia³em takich pomocników jak ty.}
{278} {} {Wiêc masz szczêœcie, tym razem.}

{280} {} {}
{281} {} {[Pods³uchaj rozmowy]}
{282} {} {Bustos: Jakieœ wiadomoœci, John?}
{283} {} {[Pos³uchaj]}
{284} {} {Sullivan: Mówi¹, ¿e jest ich oko³o czterech. Twoja córka jest zak³adnikiem. Nie postawili jeszcze ¿adnych ¿¹dañ. Musisz wys³aæ kogoœ do negocjacji.}
{285} {} {[Pos³uchaj]}
{286} {} {Bustos: Gr-rm... Wiedzieli, kogo z³apaæ i do kogo celowaæ... Cholera, jeœli inni z³odzieje siê o tym dowiedz¹, ta historia bêdzie siê powtarzaæ dzieñ po dniu.}
{287} {} {[Pos³uchaj]}
{288} {} {Sullivan: Powinieneœ siê ni¹ lepiej opiekowaæ. Burmistrz ca³ego miasta, a nie potrafi zaj¹æ siê jedn¹ dziewczyn¹.}
{289} {} {[Pos³uchaj]}
{290} {} {Bustos: Zamknij siê, John! Lepiej znajdŸ sposób na uwolnienie mojej córki.}
{291} {} {[Pos³uchaj]}
{292} {} {Sullivan: Nie wa¿ siê mi rozkazywaæ, Bustos. To nie jest czas, na wywy¿szanie siê. Lepiej przygotuj wszystkie kapsle. Im szybciej... (zauwa¿a ciê) He? Czego chcesz?}
{293} {} {Co tu siê dzieje?}