{100} {} {Widzisz bandytê.}
{101} {} {Widzisz jednego ze zbirów autostrady. Typ nie wygl¹da na przyjemniaczka.}

{110} {} {Jeœli nie otrzymamy zap³aty, ktoœ umrze.}
{111} {} {Nie mamy tu dobrego ¿ycia.}
{112} {} {Niech hrabia policzy kapsle, jeœli chce zobaczyæ swoj¹ córkê ¿yw¹.}
{113} {} {Nie chcê brudziæ sobie r¹k przez t¹ dziewczynê, ale ktoœ musi to zrobiæ.}
{114} {} {Co zdecydowa³ Bustos?}
{115} {} {Koñczy mi siê cierpliwoœæ.}
{116} {} {Palce mnie swêdz¹, ¿eby kogoœ zastrzeliæ.}
{117} {} {}
{118} {} {Nawet nie myœl o œledzeniu nas.}
{119} {} {Wynoœ siê st¹d.}
