{100} {} {Widzisz przywódcê gangu.}
{101} {} {Widzisz jednego ze z³odziei autostrad. Wygl¹da na to, ¿e on tu wszystkim kieruje.}
{102} {} {Ju¿ wychodzimy. Prosimy o przekazanie burmistrzowi naszych „najg³êbszych przeprosin”.}

{200} {} {Czo³gasz siê tu¿ pod kulami i nie boisz siê? Jesteœ odwa¿ny lub po prostu g³upi. Kim jesteœ?}
{1200} {} {Hrabia jest tak ¿a³osny, ¿e wysy³a kobietê na negocjacje. W porz¹dku, niech bêdzie. Kim jesteœ?}
{201} {} {Jestem ostatni¹ rzecz¹, jak¹ zobaczysz.}
{202} {} {Nie ma znaczenia, kim jestem. Burmistrz wys³a³ mnie do negocjacji.}
{203} {} {Oczywiœcie. On siê nie zmienia. Gotów jest poœwiêciæ ka¿de ¿ycie oprócz w³asnego. Zobaczmy, czy ceni ¿ycie swojej córki.}
{204} {} {Burmistrz ¿¹da uwolnienia zak³adnika. W przeciwnym razie nie wyjdziesz st¹d ¿ywy.}
{205} {} {Burmistrzowi nie mo¿na ufaæ. Jest bardziej pod³y ni¿ w¹¿ z pustkowi. Powiedz mu, ¿e jeœli nie spe³ni naszych warunków, zabijemy jego córkê.}
{206} {} {Czego chcesz?}
{207} {} {Kurwa gadanie. Nie zas³ugujesz na nic prócz œmierci.}
{208} {} {Dziesiêæ tysiêcy kapsli.}
{209} {} {Dziesiêæ tysiêcy? Nie ma tyle w ca³ym mieœcie.}
{210} {} {To nie jest nasz problem. Pozosta³a wiêc tylko jedna rzecz - ¿ycie burmistrza. Pozwól mu zaj¹æ miejsce córki.}
{211} {} {Dam mu znaæ o twoich warunkach.}
{212} {} {Co siê z tob¹ dzieje?}
{213} {} {Hmm. Nie jesteœ miejscowy, prawda? W przeciwnym razie pozna³bym ciê.}
{214} {} {Jakie to ma znaczenie?}
{215} {} {Kapsle nie s¹ dla mnie wa¿ne. We wschodniej czêœci miasta znajduje siê stary cmentarz. Masowy grób. W tym miejscu, gdzie roœnie tylko sucha trawa, spoczywaj¹ mieszkañcy Casa Grande. Moi rodzice s¹ wœród nich.}
{216} {} {[Pos³uchaj]}
{217} {} {Próbowali zapewniæ sobie spokojne ¿ycie w tym mieœcie. Niestrudzenie pracowaliœmy nad uruchomieniem stacji pomp i wyposa¿eniem miasta. Ale potem przyszed³ Bustos, przerwa³ im i zaj¹³ miasto dla siebie. Nie zostawi³ przy ¿yciu nikogo, kto stan¹³by mu na drodze.}
{218} {} {A teraz mœcisz siê? A mo¿e k³amiesz?}
{219} {} {Dlaczego mia³bym k³amaæ? Mówiê prawdê. Przeka¿ moje s³owa burmistrzowi. Chocia¿ jest ma³o prawdopodobne, ¿e bêdzie chcia³ Ciê s³uchaæ.}
{220} {} {Przeka¿ê burmistrzowi twoj¹ proœbê.}
{221} {} {K³amiesz. I zabije ciê, ¿eby zniechêciæ innych do podobnych dzia³añ...}
{222} {} {Serio chcesz jeszcze wiêcej krwi na ziemi swoich przodków?}
{223} {} {Nie bêdê siê z tob¹ k³óciæ. PrzyprowadŸ mi burmistrza. Porozmawiam tylko z nim.}
{224} {} {To miasto jest ju¿ po kolana we krwi. Dopiero teraz uda³o nam siê osi¹gn¹æ przynajmniej trochê spokoju.}
{225} {} {Nie bêdzie wiêcej ¿adnych rozmów. Umrzesz tu i teraz...}
{226} {} {Myœlisz, ¿e jestem samolubny? Jak myœlisz, jak powinienem ¿yæ po tym, jak burmistrz wyrzuci³ mnie z mojej ziemi? Zywiê siê padlin¹ i rabujê karawany na autostradach, ¿eby prze¿yæ. A to wszystko przez jednego chciwego skurwiela.}
{227} {} {Wiêc zejdŸ z tej drogi. Mo¿esz mieszkaæ w Phoenix lub w innym mieœcie.}
{228} {} {Nie s¹dzê, ¿ebym by³ gotowy, aby zacz¹æ od nowa. Za póŸno, ¿eby cokolwiek zmieniæ. A jednak Twoje s³owa dotar³y do mojej duszy. Dziewczyna mo¿e wyjœæ. Ona nie jest niczemu winna. Ale jeœli burmistrzowi pozosta³a choæby kropla godnoœci, niech przyjdzie do mnie sam. Umówiê siê z nim na pojedynek, jak za dawnych dobrych czasów.}
{229} {} {Cieszê siê, ¿e pos³ucha³eœ swojego rozs¹dku.}
{1229} {} {Cieszê siê, ¿e pos³ucha³eœ swojego rozs¹dku.}
{230} {} {Co powiedzia³ burmistrz?}
{231} {} {Jak¹ nagrodê za twoj¹ g³owê mo¿na dostaæ. I dostanê j¹.}
{232} {} {Sytuacja siê nie zmieni³a. Pozwoli ci odejœæ, jeœli uwolnisz zak³adnika.}
{233} {} {Co to za sztuczki? Czy naprawdê masz nadziejê, ¿e po tych znakach nie rozpoznajê Ciê jako obcego?}
{234} {} {Có¿...}
{235} {} {Dostajesz tylko tysi¹c kapsli i opuszczasz miasto. W przeciwnym razie nie wyjdziesz st¹d ¿ywy.}
{236} {} {Niesamowite. Myœla³em, ¿e Bustos nie da³by nikomu nawet z³amanego kapsla w takiej sytuacji...}
{237} {} {[Dalej.]}
{238} {} {(Jeden ze wspólników podchodzi do przywódcy, zabiera go do rogu i zaczyna z nim aktywnie dyskutowaæ) Ach... tak... masz racjê kolego, uspokój siê... (wraca do Ciebie) Akceptujemy Twoje warunki. Oddaj kapsle i mo¿esz zabraæ dziewczynê.}
{239} {} {Dlaczego hrabia mia³by byæ tak wielkoduszny dla z³odziei? Po prostu ciê zabijê i wezmê te kapsle dla siebie...}
{240} {} {Bêdziemy musieli trochê poczekaæ. Pójdê po kapsle.}
{241} {} {Oto ca³a kwota.}
{242} {} {Powiedz hrabiemu, ¿e wychodzimy, i niech nie wa¿y siê wysy³aæ za nami kogokolwiek.}
{243} {} {By³oby g³upio straciæ tyle kapsli. Jednak ciê zabijê i je zabiorê.}
{244} {} {Hrabia zawsze dotrzymuje s³owa.}