{100} {} {Widzisz kupca.}
{101} {} {Widzisz kierownika karawany.}
{102} {} {S³ysza³em o tej zbroi, ale myœla³em, ¿e to fikcja.}

{200} {} {Pozdrowienia, podró¿niku. Od kilku miesiêcy je¿dzê do tego miasta swoj¹ karawan¹. Dlatego jestem trochê œwiadomy tego, co tu jest. Czy mogê ci w czymœ pomóc?}
{1200} {} {Pozdrowienia, podró¿niku. Od kilku miesiêcy je¿dzê do tego miasta swoj¹ karawan¹. Dlatego jestem trochê œwiadomy tego, co tu jest. Czy mogê ci w czymœ pomóc?}
{201} {} {Jakie rady dla mnie mo¿e mieæ w³óczêga taki jak ty? Tracê tylko tu z tob¹ czas.}
{202} {} {Tak. Zdecydowanie przyda³oby mi siê kilka porad.}

{210} {} {Chcesz wiedzieæ wiêcej?}
{211} {} {Niewa¿ne. Narazie.}

#Zapytania
{220} {} {Opowiedz mi o tym miejscu.}
{221} {} {Casa Grande to jedyna oaza na drodze z Tu-San do Phoenix. Wiele karawan zatrzymuje siê tutaj, aby odpocz¹æ po drodze i zdobyæ czyst¹ wodê. Reszta miasta nie ma obcym niczego do zaoferowania.}
{222} {} {Dlaczego to miasto jest takie biedne?}
{223} {} {Szczerze? Nie mam pojêcia. Miejscowi zarabiaj¹ du¿o kapsli na naszych karawanach. A mimo to ich samych nie staæ na podstawowe rzeczy. Czêœciowo pewnie dlatego, ¿e z³odzieje z autostrad pustosz¹ okolice, ale to oczywiœcie nie wszystkie powody.}
{224} {} {To widaæ. Miasto wygl¹da bardziej jak wysypisko œmieci.}
{225} {} {Lepiej nie traktuj tak miejscowych. Po prostu próbuj¹ przetrwaæ w tych trudnych warunkach.}
{226} {} {Chcê wiedzieæ wiêcej.}
{227} {} {Co to za ogromne zbiorniki za p³otem?}
{228} {} {Stacja wodna. Obecnie g³ówna i chyba jedyna atrakcja Casa Grande. Bez niej te ruiny by³yby tylko ruinami.}
{229} {} {}

{230} {} {Kto tu rz¹dzi?}
{231} {} {Formalnie burmistrzem miasta jest hrabia Bustos. Szczerze mówi¹c, nie do koñca rozumiem, co robi, ale bez niego nikt tutaj nie odwa¿y siê zrobiæ kroku.}
{232} {} {Po œmierci hrabiego Bustosa, John Sullivan zosta³ mianowany g³ow¹ miasta. A mo¿e sam siê wyznaczy³, trudno powiedzieæ.}
{233} {} {Trudno powiedzieæ. Po œmierci burmistrza i w³aœciciela stacji nikt nie chce zostaæ nowym szefem miasta.}
{234} {} {Rozumiem. Mam inne pytanie.}
{235} {} {Gdzie mogê znaleŸæ burmistrza?}
{236} {} {Jego rezydencja jest przy g³ównej ulicy. Jeœli znajdziesz siê w œrodku, trzymaj broñ w kaburze i nie wykonuj gwa³townych ruchów. Jego ochroniarze tego nie lubi¹.}
{237} {} {Hmm... Muszê tam wpaœæ, ale zrobiê to póŸniej. Na razie kontynuujmy nasz¹ rozmowê.}
{238} {} {W takim razie idê siê z nim zobaczyæ. Czeœæ.}
{239} {} {}

{240} {} {Co nowego?}
{241} {} {Nic specjalnego.}
{242} {} {Rozumiem.}
{243} {} {Ktoœ zbezczeœci³ lokalny cmentarz. Burmistrz by³ bardzo z³y i obieca³ nagrodê za z³apanie sprawcy. Ale kto by móg³ to zrobiæ?}
{244} {} {Czy to wszystko?}
{245} {} {W pobli¿u widziano stado Radskorpionów. B¹dŸ ostro¿ny i weŸ ze sob¹ antidotum, jeœli wybierasz siê na pustkowie.}
{246} {} {Czy to wszystko?}
{247} {} {Hrabia Bustos zosta³ za³atwiony przez z³odziei, mówi¹. Nie wiem, jak to siê sta³o. Miejscowi nie chc¹ wchodziæ w szczegó³y.}
{248} {} {Co jeszcze?}
{249} {} {Podobno hrabia Bustos pije po cichu w swojej rezydencji. Tak, stara bestia zaczyna traciæ przyczepnoœæ. Tequila jeszcze nigdy nikogo nie wzmocni³a.}
{250} {} {Coœ jeszcze?}
{251} {} {LaŸnia w mieœcie zosta³a ponownie otwarta. Mi³o jest móc siê umyæ w tych czasach.}
{252} {} {To... interesuj¹ce. Coœ innego?}
{253} {} {W mieœcie by³a ³aŸnia, ale teraz jest zamkniêta. I nikt nie wie, gdzie jest jej w³aœciciel. Mia³em nadziejê, ¿e siê umyjê.}
{254} {} {Ciekawe. Jakieœ inne wiadomoœci?}
{255} {} {Wszyscy w okolicy mówi¹ teraz o wziêciu zak³adnika w barze. Ale wydaje mi siê, ¿e znasz tê historiê lepiej ni¿ ja.}
{256} {} {Ceny w przepompowni wzros³y po upadku Blacharzy. Wygl¹da na to, ¿e ta trasa przesta³a siê op³acaæ karawanom.}
{257} {} {To przydatne informacje. Co jeszcze mo¿esz mi powiedzieæ?}
{258} {} {Gang Niebieskich Tarcz przesta³ atakowaæ karawany. Nie jest jeszcze jasne, co siê tam wydarzy³o, ludzie ró¿nie gadaj¹. Ale fakt, ¿e szlaki sta³y siê bezpieczniejsze cieszy ka¿dego.}
{259} {} {Zgadza siê.}

{260} {} {Jak mo¿na tu zarobiæ na szklankê wody?}
{261} {} {Hmm, dla nowego nie ma tu innej opcji jak handel. Jednak ka¿dy burmistrz ma pracê, o ile oczywiœcie mo¿na znaleŸæ z nim wspólny jêzyk.}
{262} {} {Zwrócê na to uwagê.}
{263} {} {W przeciwnym razie nic nowego.}
{264} {} {Rozumiem.}

# Wysylanie do Phoenix
{300} {} {Dok¹d zmierza Twoja karawana?}
{301} {} {Wkrótce wracamy do Phoenix.}
{302} {} {Mi³ej podró¿y. Dopóki nie wyjdziesz, czy mogê zadaæ ci kilka pytañ?}
{303} {} {Zabierz mnie ze sob¹. Muszê siê dostaæ do du¿ego miasta.}
{304} {} {Przepraszam, wszystkie miejsca s¹ zajête. Nie potrzebujemy dodatkowego ogona.}
{305} {} {Zap³acê.}
{306} {} {Rozumiem. To mo¿e mo¿esz odpowiedzieæ na moje pytania?}
{307} {} {Nie chcê ciê uraziæ, ale nie potrzebujemy w¹tpliwych towarzyszy podró¿y. Szlak jest zbyt niebezpieczny, aby podejmowaæ takie ryzyko.}
{308} {} {Rozumiem, nie ma problemu.}
{309} {} {Wiêc wolisz daæ siê z³apaæ bez obstawy na szlaku bandytom i umrzeæ, ok.}
{310} {} {OK. Za }
{311} {} { kapsli jestem gotów zrobiæ dodatkowe miejsce. Ale nie bierz ze sob¹ zbyt wielu rzeczy, nie mamy dodatkowego bramina do ich noszenia.}
{312} {} {Nie mam tylu kapsli. Bêdziecie musieli iœæ sami. Do zobaczenia.}
{313} {} {Jednak teraz potrzebujê wiêcej odpowiedzi na pytania.}
{314} {} {Oto kapsle. Jestem gotowy do wyjœcia.}
{1314} {} {Oto kapsle. Jestem gotowa do wyjœcia.}
{315} {} {I kto niby bêdzie nosi³ te rzeczy? Ten twój sprzêt za du¿o wa¿y. Zostaw nie wiêcej ni¿ piêædziesi¹t funtów.}
{316} {} {Ok.}
{317} {} {Nie pracujê za darmo.}
{318} {} {Oczywiœcie...}
{319} {} {Nie martw siê, w mojej karawanie jesteœ bezpieczny.}
{320} {} {[Poczekaj na wyjœcie karawany]}
{321} {} {Obiecujê, ¿e to pozostanie mój problem.}
{322} {} {Tak teraz mówisz. Ale po drodze wszystko mo¿e siê zdarzyæ.}
{323} {} {Có¿, tak...}
{324} {} {Jeœli to taki problem to mo¿esz zostawiæ mnie na œrodku szlaku z tymi wszystkimi rzeczami.}
{325} {} {Ok. Rozwa¿ymy to jako czêœæ umowy. Ale nie pracujê za darmo.}
{326} {} {Oczywiœcie...}
{327} {} {OK. Potraktujemy to jako czêœæ umowy.}
{328} {} {Swietnie.}
{329} {} {Zap³acê wiêcej, }
{330} {} { kapsli na baga¿.}
