{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz stra¿nika karawany. Odpoczywa po mêcz¹cej podró¿y.}

{110} {} {Czeœæ. Jak tam trasa?}
{111} {} {Przepraszam, ale muszê odpocz¹æ.}
{112} {} {Jest tu co prawda woda, ale poza tym to kiepskie miejsce.}
{113} {} {Casa Grande ma kiepsk¹ opiniê.}
{114} {} {Zadnych ¿artów z lokalnym burmistrzem.}
{115} {} {Musisz porozmawiaæ z szefem.}
{116} {} {Droga miêdzy Phoenix i Tu-San jest gor¹ca.}
{117} {} {Na autostradzie jest niebezpiecznie z powodu zbirów.}
{118} {} {Lepiej nie wpadaæ na bandytów po drodze.}
{119} {} {Jesteœmy jedynym Ÿród³em dochodu dla miejscowych.}
