{100} {} {Widzisz osadnika.}
{101} {} {Widzisz zwyk³ego obywatela Casa Grande.}
{102} {} {Opowiem innym mieszkañcom, kto mnie uratowa³. Dziêkujê Ci.}
{103} {} {Te stawonogi pojawiaj¹ siê tak nagle. Trzeba siê rozgl¹daæ na wszystkie strony.}
{104} {} {Ci bandyci musz¹ siê ukrywaæ gdzieœ w pobli¿u. Lepiej mieæ siê na bacznoœci.}

{110} {} {Pomocy!}
{111} {} {Hej, ktokolwiek!}
{112} {} {Shoo, cholerne radskorpiony!}
{113} {} {Wynoœcie siê, radskorpiony!}
{114} {} {Tak ³atwo mnie nie dostaniecie, bydlaki!}
{115} {} {Zostanê tutaj, dopóki sobie nie pójd¹.}
{116} {} {Czy ktoœ w ogóle mnie szuka?}
{117} {} {Hej, czy ktoœ mnie s³yszy?}
{118} {} {Pomocy, jestem w pu³apce!}
{119} {} {Niech mi ktoœ pomo¿e!}

{120} {} {Pomocy!}
{121} {} {Hej, ktokolwiek!}
{122} {} {Tutaj!}
{123} {} {Cholerni bandyci.}
{124} {} {Jestem g³odny.}
{125} {} {Czy w ogóle zamierzaj¹ mnie uratowaæ?}
{126} {} {Czy ktoœ mnie szuka?}
{127} {} {Hej, czy ktoœ mnie s³yszy?}
{128} {} {Pomocy, jestem uwiêziony!}
{129} {} {Niech mi ktoœ pomo¿e!}

{200} {} {Ugh, w koñcu. Ba³em siê, ¿e nikt mnie nie uratuje.}
{201} {} {Co tutaj robisz?}
{202} {} {Ukrywam siê przed radskorpionami. Te stworzenia zaskoczy³y mnie, gdy ³apa³em iguany w trawie. Mia³em szczêœcie, ¿e uda³o mi siê ukryæ w tej chacie.}
{203} {} {Jak d³ugo czeka³eœ na pomoc?}
{204} {} {Bardzo d³ugo. Te stawonogi s¹ strasznie cierpliwe. Mog¹ ca³ymi dniami le¿eæ pod s³oñcem bez jedzenia i wody. Myœla³em, ¿e umrê z g³odu zanim odejd¹.}
{205} {} {Chcesz wróciæ do miasta?}
{206} {} {Oczywiœcie. Czy droga jest ju¿ wolna? Zobacz, czy wszystko w porz¹dku, jestem z tob¹.}
{207} {} {Poczekaj tutaj, zajmê siê tym.}
{208} {} {W takim razie chodŸmy do miasta. Prawdopodobnie ju¿ ciê szukaj¹.}
{209} {} {Tak, racja... (wygl¹da spod drzwi) Uh, ty pierwszy...}
{210} {} {Oczywiœcie.}
{211} {} {Smia³o.}
{212} {} {Ty g³upcze. Nie jestem twoim zbawicielem, jestem rabusiem. Dawaj wszystko, co cenne.}
{213} {} {OszczêdŸ mnie! Nie mam niczego cennego!}
{214} {} {No có¿.}
{215} {} {Cholera. Nie chcê brudziæ sobie r¹k.}
{216} {} {Co tam jest? Mogê wyjœæ?}
{217} {} {Nie, wci¹¿ s¹ tam skorpiony. Usi¹dŸ tutaj i nie wychylaj g³owy.}

{300} {} {Ugh, w koñcu. Ju¿ myœla³em, ¿e nikt mnie nie uratuje.}
{301} {} {Kto ciê tu zamkn¹³?}
{302} {} {Byli rabusiami. Zobaczyli mnie na pustyni i zdecydowali, ¿e mogê o nich opowiedzieæ w mieœcie. Wiêc z³apali mnie i tu uwiêzili.}
{303} {} {S³ysza³eœ ich rozmowê? Gdzie poszli lub dlaczego tu byli?}
{304} {} {Och, ten atak by³ chyba tylko odwróceniem uwagi. Zamierzali wzi¹æ kogoœ jako zak³adnika, aby szanta¿owaæ burmistrza. To wszystko, co zrozumia³em.}
{305} {} {Musimy go jak najszybciej ostrzec. ChodŸmy do miasta.}
{306} {} {Bandyci pewnie wci¹¿ s¹ w pobli¿u. Usi¹dŸ tutaj i poczekaj na odpowiedni moment.}
{307} {} {Co jest? Mogê wyjœæ?}
{308} {} {ChodŸmy. Musimy powiedzieæ hrabiemu Bustosowi o tym, co siê sta³o.}
{309} {} {Wyjœæ na otwarty teren i daæ siê postrzeliæ w plecy. Swietny pomys³, lepiej usi¹dŸ tu i odpocznij.}