{100} {} {Widzisz przed sob¹ Starca Gallegosa.}
{101} {} {Widzisz chudego osadnika z kud³at¹ brod¹ i zniszczonym ubraniem. Chodzi po ulicy, opieraj¹c siê na patyku.}
{102} {} {Nie dotykaj mnie, kawa³ku ¿elaza, wci¹¿ mogê siê broniæ. Spadaj, no ju¿.}

{200} {} {¿Qu quieres de mš?}
{201} {} {Chcê tylko porozmawiaæ. Rozumiesz mnie?}
{202} {} {Djame en paz. No te entiendo.}
{203} {} {Uh, niewa¿ne.}
{204} {} {Nie wyg³upiaj siê. Nie mo¿e byæ tak, ¿e nie znasz angielskiego.}
{205} {} {Yo no hablo ingls. Djame en paz!}
{206} {} {Jeœli nie przerwiesz tych wyg³upów, wybijê ci zêby.}
{207} {} {Stop! Czekaæ! Morza Maldito, czego chcesz?}
{208} {} {Todo est bien, amigo. Quiero hablar contigo.}
{209} {} {¡Ah! ¿Entonces hablas espaœol? ¡Qu gusto escuchar mi lengua materna! (Och, wiêc mówisz po hiszpañsku? Jak siê cieszê, s³ysz¹c mój jêzyk ojczysty!)}
{210} {} {¿Todo ... est ... bien?}
{211} {} {¿Eh? ¿Qu quieres decir? No entiendo nada, habla ms claro.}
{212} {} {To dla mnie zbyt trudne, poddajê siê. Zegnaj staruszku.}
{213} {} {Och, teraz mnie rozumiesz, prawda?}
{214} {} {Tak jest lepiej. Jaki jest sens tego ca³ego wystêpu?}
{215} {} {Nie mo¿e byæ tak, ¿e nie rozumiesz nawet odrobiny angielskiego.}
{216} {} {Miej litoœæ nad starym cz³owiekiem, senor. Obcy przychodz¹ i odchodz¹. A ja muszê szukaæ jedzenia. Jestem strasznie g³odny.}
{1216} {} {Miej litoœæ nad starym cz³owiekiem, senora. Obcy przychodz¹ i odchodz¹. A ja muszê szukaæ jedzenia. Jestem strasznie g³odny.}
{217} {} {OK, poszukam dla ciebie czegoœ do jedzenia.}
{218} {} {Wygl¹da na to, ¿e siê nie dogadamy. Pierdol siê.}
{219} {} {Wygl¹da na to, ¿e siê nie dogadamy. Pierdol siê, el decpito viejo.}

{240} {} {(podnosz¹c rêce b³aga o litoœæ) Ach, bandyto! Nie dotykaj mnie! Nie mam nic!}
{1240} {} {(podnosz¹c rêce b³aga o litoœæ) Ach, bandyto! Nie dotykaj mnie! Nie mam nic!}
{241} {} {Hej, nie jestem bandyt¹.}
{1241} {} {Hej, nie jestem bandyt¹.}
{242} {} {Jeœli bêdziesz krzyczeæ, to zaraz serio zrobiê ci krzywdê.}
{243} {} {(podnosz¹c rêce do góry b³aga o litoœæ) ¡Nie ja, kumple! ¡No tengo nada!}

{250} {} {(Gestami pokazuje chyba jedzenie?)}
{251} {} {Do widzenia, staruszku.}
{252} {} {Ach, jedzenie! Dziêkujê, seniorze.}
{1252} {} {Ach, jedzenie! Dziêkujê, senorita.}
{253} {} {¡Ah, comida! Gracias, Seœor.}
{1253} {} {¡Ah, comida! Gracias, Seœorita.}
{254} {} {Proszê. Czy mo¿esz teraz opowiedzieæ trochê o sobie i mieœcie?}
{255} {} {Po prostu to zjedz. Nie ma za co.}

{260} {} {Kim jesteœ, staruszku?}
{261} {} {Ja? Có¿, nazywam siê Fernando Gallegos. Mieszkam tu.}
{262} {} {¿Moje hablas a mš? Mi nombre es Fernando Gallegos. Yo vivo aquš.}
{263} {} {Mi³o ciê poznaæ, Gallegos. Porozmawiamy?}
{264} {} {To wszystko, co chcia³em wiedzieæ. Czeœæ, Gallegos.}
{265} {} {Ile masz lat, Gallegos?}
{266} {} {Wygl¹dasz gorzej ni¿ pomarszczony kretoszczur. Ile ty masz lat?}
{267} {} {Nie wiem dok³adnie. Myœlê, ¿e prze¿y³em ju¿ ze czterdzieœci zim.}
{268} {} {No los he contado. Creo que por lo menos cuarenta primaveras, eso creo.}
{269} {} {D³ugo. Wielu nie prze¿y³o nawet po³owy tego. Nie jesteœ miejscowy, co?}
{270} {} {Masz niezwyk³y akcent. Chyba nie jesteœ z tych krajów, co?}
{271} {} {Ju¿ rozumiem, dlaczego wygl¹dasz jak trup. To dziwne, ¿e w ogóle prze¿y³eœ w tym miejscu.}
{272} {} {Wiêc pewnie du¿o wiesz. Porozmawiajmy o czymœ innym.}
{273} {} {To imponuj¹ce. Muszê iœæ. Do zobaczenia.}
{274} {} {Prawda. Na po³udniu mówi siê tylko po hiszpañsku. Nadal nie znam dobrze Twojego jêzyka.}
{275} {} {Efectivamente. En el sur hablan espaœol, y no hablo bien tu idioma.}
{276} {} {Wiêc przyjecha³eœ z po³udnia? To musia³a byæ ciê¿ka droga.}
{277} {} {Masz urojenia, staruszku. Na po³udniu jest tylko ja³owa pustynia, nie da siê jej przejœæ.}
{278} {} {To prawdziwy cud, ¿e prze¿y³eœ.}
{279} {} {Przejœcie przez pustyniê by³o niesamowicie trudne. Ale zrobiliœmy to, poniewa¿ nie mieliœmy wyboru. Najpierw dotarliœmy do miasta Tucson, sk¹d zostaliœmy wyrzuceni. Nastêpnie przyjechaliœmy do Casa Grande i zatrzymaliœmy siê tutaj na sta³e.}
{280} {} {Fue muy difšcil cruzar el desierto. Pero lo logramos, porque no tenšamos otra opciƒn. Primero llegamos a la ciudad de Tucson, y de ahš nos echaron. Luego nos quedamos en Casa Grande.}
{281} {} {Mówisz „my”. Kto jeszcze by³ z tob¹?}
{282} {} {Kilku ch³opów. Tylko ja prze¿y³em.}
{283} {} {Varios campesinos. Pero yo soy el Ÿnico que aŸn est vivo.}
{284} {} {Smutna historia. Przykro mi.}
{285} {} {Ciekawe. Chcia³bym ciê zapytaæ o wiêcej.}
{286} {} {Przestañ wciskaæ mi to k³amstwo.}
{287} {} {Bardzo interesuj¹ce. Ale muszê ju¿ iœæ. Czeœæ.}
{288} {} {}
{289} {} {}

{290} {} {Co tu robisz?}
{291} {} {Trochê tego, trochê tamtego. Robiê to, czego potrzebuj¹ mieszkañcy. Wczoraj na przyk³ad szuka³em drewna na opa³ do ³aŸni. Dobrze, ¿e znowu dzia³a.}
{292} {} {Trochê tego, trochê tamtego. Robiê to, czego potrzebuj¹ mieszkañcy. Wczoraj na przyk³ad szuka³em drewna na opa³ dla burmistrza. Lubi siê k¹paæ dla relaksu.}
{293} {} {Trochê tego, trochê tamtego. Robiê to, czego potrzebuj¹ mieszkañcy.}
{294} {} {Chambitas.}
{295} {} {Hmm, to by³o bezcelowe pytanie. O co jeszcze mogê ciê zapytaæ?}
{296} {} {Bêdê pamietaæ. Na razie wystarczy.}
{297} {} {Dlaczego kulejesz?}
{298} {} {Stara rana. Czemu pytasz? Lubisz ¿artowaæ z innych?}
{299} {} {Es por una vieja herida.}
{300} {} {Przepraszam, nie powinienem by³ o tym wspominaæ. Porozmawiamy o czymœ innym?}
{301} {} {Jeœli nie chcesz rozmawiaæ, decyzja nale¿y do Ciebie. Znajdê innych, z którymi mogê porozmawiaæ. Czeœæ.}
{302} {} {Kustykasz jak ciê¿arny bramin. Wiesz o tym?}
{303} {} {Kulejesz jak stary kret po okruchach uranu. Wiesz o tym?}
{304} {} {Nawet wujek Jose pracowa³ na plantacjach ze swoj¹ chor¹ nog¹. Jesteœ zwyk³ym balastem i pora¿k¹.}
{305} {} {Smiej siê, tak. Z przyjemnoœci¹ bêdê patrzeæ, jak zab³akana kula w koñcu ciê znajduje.}
{306} {} {Callate, sinverguenza. Era una bala perdida.}
{307} {} {Zab³¹kana kula? Chyba lepiej tu na siebie uwa¿aæ.}
{308} {} {Wygl¹da na to, ¿e to miejsce nie jest zbyt bezpieczne. Myœlê, ¿e powinienem siê st¹d wydostaæ tak szybko, jak to tylko mo¿liwe.}
{309} {} {No, powiedz mi, jak to siê sta³o? Obiecujê, ¿e zostanie to miêdzy nami.}
{310} {} {Zostaw mnie w spokoju.}
{311} {} {Dejame, canalla.}
{312} {} {Nie, dopóki nie us³yszê wszystkiego, co wiesz.}
{313} {} {Ok, cokolwiek powiesz.}
{314} {} {Przykro mi, ¿e tak siê sta³o. Jak do tego dosz³o? Obiecujê, ¿e pozostanie to miêdzy nami.}
{315} {} {Zab³¹kana kula. Widzia³eœ opuszczony bar na pó³nocy? By³em tam, kiedy dosz³o do strzelaniny. Kula trafila mnie w noge. Zwyk³y wypadek.}
{316} {} {Fue un accidente durante un tiroteo en el antiguo bar. Una bala me hiriƒ la pierna.}
{317} {} {Zab³¹kana kula? Chyba lepiej tu na siebie uwa¿aæ.}
{318} {} {Wygl¹da na to, ¿e to miejsce nie jest zbyt bezpieczne. Myœlê, ¿e lepiej siê st¹d wydostaæ tak szybko, jak to tylko mo¿liwe.}
{319} {} {}

{320} {} {Opowiedz mi o mieœcie.}
{321} {} {Co tu powiedzieæ? Istniejemy tylko dziêki stacji wodnej. Daje nam wodê i z daleka przyci¹ga kupców.}
{322} {} {La ciudad sobrevive gracias a la bomba de agua. El agua da vida a este desierto y atrae a comerciantes lejanos.}
{323} {} {To dlaczego ulice s¹ takie puste?}
{324} {} {Woda przyci¹ga nie tylko kupców. Boimy siê z³odziei, zbirów i wszelkiego rodzaju marginesu.}
{325} {} {El agua no solo atrae a los comerciantes. Tenemos miedo a los bandidos ya los ladrones.}
{326} {} {Ugh, myœla³em, ¿e to tylko kolejne miasto duchów.}
{327} {} {Opowiedz mi o burmistrzu tego miasta.}
{328} {} {Jest nim Hrabia Bustos. Kieruje miastem z tej ogromnej rezydencji.}
{329} {} {El conde Bustos gobierna la ciudad desde esa gran mansiƒn.}
{330} {} {Dziêki, niesamowicie mi to pomog³o.}
{331} {} {Z tej rezydencji, prawda? Mo¿e powinienem go teraz odwiedziæ.}
{332} {} {Nie, chodzi mi o to, jak¹ on jest osob¹. Co o nim myœlisz?}
{333} {} {Niebezpiecznie jest rozmawiaæ o tych, którzy siedz¹ nad tob¹. Wybacz, ale nie znamy siê na tyle dobrze.}
{334} {} {No quiero hablar de l.}
{335} {} {Racja, pewnie twoje obawy nie s¹ daremne. Mo¿e inny temat bêdzie przyjemniejszy?}
{336} {} {Boisz siê Bustosa, to mi wiele o nim mówi. Ju¿ nie chcê o nic pytaæ.}
{337} {} {Mam na myœli, jak¹ on jest osob¹. Czy ludzie go podziwiaj¹, czy siê go boj¹?}
{338} {} {Okropna osoba. Okrutny, chciwy, trzyma wszystkich w garœci. Nikt nie zrobi tu niczego bez jego pozwolenia.}
{339} {} {Es una persona terrible, es un tirano. Aquš, nadie dir nada malo de l.}
{340} {} {Wiêc taki jest naprawdê... Dziêkujê za twoj¹ szczeroœæ.}
{341} {} {Hrabia Bustos nie ¿yje. Czy myœlisz, ¿e miastu bêdzie lepiej bez niego?}
{342} {} {By³ okropn¹ osob¹. Chciwy i okrutny, rz¹dzi³ wszystkim ¿elazn¹ rêk¹. Wszyscy bali siê powiedzieæ o nim coœ z³ego. Ale bez niego jesteœmy ³atwym celem dla bandytów.}
{343} {} {l era un tirano. Pero sin l, nos convertimos en un blanco fcil para los ladrones.}
{344} {} {Tak, nawet jego tyrania mia³a jakieœ znaczenie.}

{350} {} {Wybieram siê na po³udnie. Pójdziesz ¿e mn¹?}
{351} {} {Chyba zwariowa³eœ. Ta wyprawa to œmieræ.}
{352} {} {Ests Complete loco. Es un camino mortal.}
{353} {} {Przepraszam. Przyda³by mi siê przewodnik po nieznanych krainach.}
{354} {} {Jeœli dotrzesz na ranczo Domingueza, powiedz mu, ¿e ¿yjê i ¿e na pó³nocy te¿ s¹ osady.}
{355} {} {Cuando encuentres el rancho de Dominguez, cuentale sobre mi. Di que estoy vivo. Di que hay asentamientos en el norte.}
{356} {} {Rancho Domingueza? Dziêkujê, pozdrowiê go. Ale pewnie szybko to nie nast¹pi, na razie kontynuujmy rozmowê.}
{357} {} {Opowiem o tobie Dominguezowi, jeœli go spotkam. Bywaj.}
{358} {} {Nigdzie z tob¹ nie idê.}
{359} {} {No voy a ninguna parte contigo.}
{360} {} {Oczywiœcie. Mo¿e mo¿esz przynajmniej odpowiedzieæ na moje pytania?}
{361} {} {Jak sobie chcesz. Zegnaj el viejo.}