{100} {} {Widzisz osadnika.}
{101} {} {Widzisz jednego z miejscowych.}
{102} {} {}

{110} {} {Zzz}
{111} {} {Hr-r-r}
{112} {} {. ... .}

{120} {} {Bandyci okradli ju¿ drug¹ karawanê w ci¹gu tygodnia.}
{121} {} {Ci rozbójnicy nie znaj¹ litoœci.}
{122} {} {Mówi¹, ¿e widziano w pobli¿u zbirów.}
{123} {} {Zbiry nic nie kosztuj¹, aby przej¹æ ca³e miasto.}
{124} {} {Przez Niebieskie Tarcze niewiele karawan chce siê tu zapuszczaæ.}

{125} {} {Jak d³ugo potrwa rozejm z Niebieskimi Tarczami?}
{126} {} {Co? Niebieskie Tarcze s¹ teraz naszymi przyjació³mi? Nie mo¿e byæ.}
{127} {} {Po tym, co zrobi³y Niebieskie Tarcze, nawet siê do nich nie zbli¿ê.}
{128} {} {Niebieskie Tarcze zajmuj¹ siê handlem. Wydaje siê, ¿e œwiat oszala³.}
{129} {} {Nie mo¿esz ufaæ Niebieskim Tarczom. Nadejdzie czas, kiedy wbij¹ ci nó¿ w plecy.}

{130} {} {Niebieskie Tarcze dosta³y to, na co zas³u¿y³y.}
{131} {} {Ben i jego gang nie s¹ ju¿ tacy straszni, co?}
{132} {} {Gang Bena nie zostanie d³ugo zapamiêtany.}
{133} {} {Miejmy nadziejê, ¿e teraz wiêkszoœæ problemów to przesz³oœæ.}
{134} {} {Bez gangu Bena bêdzie tu wiêcej karawan.}

{135} {} {Bez Bena mo¿esz zapomnieæ o jego gangu.}
{136} {} {Ben dosta³ to, na co zas³u¿y³.}
{137} {} {Pamiêtam czasy, kiedy Ben by³ dobrym facetem.}
{138} {} {Nadal nie rozumiem, dlaczego Ben zwróci³ siê przeciw nam.}
{139} {} {Ben wcale nie jest ju¿ taki straszny. Jest brzydki i œmierdz¹cy.}

{140} {} {Ci Blacharze przera¿aj¹ mnie samym swoim wygl¹dem.}
{141} {} {Jaka rozs¹dna osoba po³¹czy³aby si³y z maszyn¹?}
{142} {} {Blacharze gardz¹ ludŸmi takimi jak my.}
{143} {} {Gdyby nie Blacharze, nie by³oby tak wielu karawan.}
{144} {} {Dziêki Blacharzom za bezpieczn¹ autostradê.}

{145} {} {Teraz handel podupadnie, a miasto stanie siê jeszcze bardziej zubo¿one.}
{146} {} {Bez Blacharzy bêdzie mniej karawan, to pewne.}
{147} {} {Chocia¿ nie lubi³em Blacharzy, byli przydatni.}
{148} {} {Wreszcie ktoœ wyci¹gn¹³ wtyczkê z gniazdka w Tu-San.}
{149} {} {S³oñce ju¿ nigdy nie wzejdzie nad Tu-San. Nigdy.}

{150} {} {Wielkie miasto kusi... jak œwiat³o kusi æmy.}
{151} {} {Chcia³bym móc zobaczyæ Phoenix.}
{152} {} {Ostatnio tyle s³ysza³em o Phoenix.}
{153} {} {Mówi¹, ¿e w Phoenix jest kasyno. Ale co to jest, w ¿aden sposób nie rozumiem.}
{154} {} {Pomys³ na handel kapslami pochodzi z Phoenix. Wczeœniej tak nie by³o.}

{155} {} {}
{156} {} {Wreszcie ³aŸnia znowu dzia³a.}
{157} {} {Po zamkniêciu ³aŸni mam na sobie spor¹ warstwê b³ota.}
{158} {} {Ktoœ rozkopuje groby na cmentarzu. Trochê siê bojê.}
{159} {} {Karawana pocztowa trochê siê spóŸni, ktoœ zabi³ stewarda w Phoenix.}

{160} {} {Te œwiry z kultu czasami mnie przera¿aj¹.}
{162} {} {Nie rozumiem tych czcicieli ognia.}
{163} {} {Kult, Blacharze, Niebieskie Tarcze... Czy tylko my tu jesteœmy normalni?}
{161} {} {Ten kultysta zaproponowa³ mi lekcje pisania. G³upiec, hehe.}
{164} {} {Ci czciciele ognia wydaj¹ siê byæ pobo¿ni, ale w rzeczywistoœci nosz¹ broñ pod szatami.}

{165} {} {Ludzie z karawany mówi¹ o wielkim wybuchu w Phoenix.}
{166} {} {Mówiê wam, katedra czcz¹ca ogieñ zosta³a rzeczywiscie zniszczona.}
{167} {} {Teraz w Phoenix zamiast katedry jest jedna wielka czarna dziura w ziemi.}
{168} {} {Bêdziesz w Phoenix, nie zadzieraj z kultystami.}
{169} {} {Nigdy nie lubi³em kultystów. Ale bez nich handel podupadnie.}

{170} {} {Wielkie radskorpiony znowu grasuj¹ na szlakach.}
{171} {} {Mam doœæ jedzenia samych iguan.}
{172} {} {Kiedy karawany przywioz¹ coœ jadalnego?}
{173} {} {Brakuje tu rozrywki.}
{174} {} {Têskniê za naszym barem. Nikt nie zast¹pi jego w³aœciciela.}
{175} {} {Ludzie przychodz¹ i odchodz¹. I tak zostanie.}
{176} {} {Musimy trzymaæ siê razem. W przeciwnym razie skoñczymy tak jak inni przed nami.}
{177} {} {Widzia³eœ takiego nieznajomego? Jak go znajdê...}
{178} {} {Nie rozmawiaj o tym. Kogo to obchodzi?}
{179} {} {}

{180} {} {Sprawy siê pogorszy³y, odk¹d pojawi³ siê ten nieznajomy.}
{181} {} {Wszyscy musimy siê zebraæ i wyrzuciæ nieznajomego z miasta.}
{182} {} {Na co ten obcy sobie pozwala?}
{183} {} {Zaraz kolejny chwast trafi do piachu.}
{184} {} {Có¿, miejmy nadziejê, ¿e miasto poci¹gnie trochê d³u¿ej.}
{185} {} {Nie rozmawiajcie z tym nieznajomym.}
{186} {} {Nie lubiê tego nowego. Ogólnie rzecz bior¹c, ka¿dego nowego nie lubiê.}
{187} {} {Sprawy siê poprawi³y, odk¹d pojawi³ siê ten nieznajomy.}
{188} {} {Musimy podziêkowaæ nieznajomemu za wszystko.}
{189} {} {Nie mogê uwierzyæ, ¿e nieznajomy zrobi³ dla nas tyle dobrego.}

{1180} {} {Sprawy siê pogorszy³y, odk¹d pojawi³a siê ta nieznajoma.}
{1181} {} {Wszyscy musimy siê zebraæ i wyrzuciæ nieznajom¹ z miasta.}
{1182} {} {Na co ta obca sobie pozwala?}
{1183} {} {Zaraz kolejny chwast trafi do piachu.}
{1184} {} {Có¿, miejmy nadziejê, ¿e miasto poci¹gnie trochê d³u¿ej.}
{1185} {} {Nie rozmawiajcie z t¹ nieznajom¹.}
{1186} {} {Nie lubiê tej nowej. Generalnie ka¿dego nowego nie lubiê.}
{1187} {} {Odk¹d pojawi³a siê ta nieznajoma, sprawy siê poprawi³y.}
{1188} {} {Musimy podziêkowaæ nieznajomej za wszystko.}
{1189} {} {Nie mogê uwierzyæ, ¿e nieznajoma zrobi³a dla nas tyle dobrego.}

{190} {} {Bustos by³ tyranem, ale bez niego miasto jest s³abe.}
{191} {} {Wszyscy wokó³ niego bali siê hrabiego Bustosa.}
{192} {} {Bustos nie ¿yje. Wkrótce rozpocznie siê tu nowa wojna o jego tron.}
{193} {} {Sullivan i Bustos znowu siê pok³ócili?}
{194} {} {Podatki znowu posz³y w górê, nikogo nie obchodzi, ¿e ¿yjemy w biedzie.}
{195} {} {Nie mów nic z³ego o Hrabim Bustosie. Po prostu tego nie rób.}
{196} {} {Wszyscy, którzy sprzeciwiali siê hrabiemu znikli.}
{197} {} {Tylko John Sullivan wiedzia³, jak rozwi¹zywaæ problemy w przepompowni.}
{198} {} {Kto teraz bêdzie obs³ugiwa³ przepompowniê?}
{199} {} {Szef przepompowni by³ twardym cz³owiekiem.}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Czeœæ. Sk¹d pochodzisz?}
{201} {} {Przepraszam, nie mam nastroju na rozmowê.}
{202} {} {Przepraszam, uh, œpieszê siê.}
{203} {} {Pomêcz kogoœ innego.}
{204} {} {Mamy tu ma³e miasteczko. Ka¿dy zna ka¿dego.}
{205} {} {Opowiedz mi o sobie. Albo nie, nie rób tego.}
{206} {} {Nie zostaniesz tutaj, prawda?}
{207} {} {Powodzenia na drodze.}
{208} {} {Nie, nie pytaj mnie o nic.}
{209} {} {Nie opuszczê tego miejsca tak jak ty, tu jest mój dom.}

{210} {} {Wynoœ siê st¹d, póki masz jeszcze mo¿liwoœæ.}
{211} {} {Nie zapraszaliœmy ciê.}
{212} {} {Wynoœ siê z miasta.}
{213} {} {Nie potrzebujemy tu takich ludzi jak ty.}
{214} {} {Jeszcze jeden krok i bêdê siê broniæ.}
{215} {} {OdejdŸ. Natychmiast.}
{216} {} {Jeœli nie odejdziesz, wezwê pomoc.}
{217} {} {Kiedy znajdzie ciê zab³¹kana kula, co?}
{218} {} {Nie rozumiem jak inni nadal ciê tutaj toleruj¹.}
{219} {} {OdejdŸ. Moja cierpliwoœæ nie jest nieograniczona.}

{220} {} {Czeœæ, jak siê masz?}
{221} {} {Przykro mi, ¿e na pocz¹tku tak Ÿle ciê przyjêto.}
{222} {} {Jesteœ teraz dla nas prawdziwym bohaterem.}
{223} {} {Pozwól, ¿e uœcisnê ci d³oñ.}
{224} {} {Mój dom to teraz tak¿e Twój dom.}
{225} {} {Och, to ty! Mi³o ciê widzieæ.}
{226} {} {D³ugo tu zostaniesz?}
{227} {} {Nie mam pojêcia, co byœmy bez ciebie zrobili.}
{228} {} {Cieszymy siê, ¿e jesteœ po naszej stronie.}
{229} {} {Dziêkujê za wszystko.}

{1220} {} {Czeœæ, jak siê masz?}
{1221} {} {Przykro mi, ¿e na pocz¹tku tak Ÿle ciê przyjêto.}
{1222} {} {Jesteœ teraz dla nas prawdziw¹ bohaterk¹.}
{1223} {} {Pozwól, ¿e ciê przytulê.}
{1224} {} {Mój dom to teraz tak¿e Twój dom.}
{1225} {} {Och, to ty! Mi³o ciê widzieæ.}
{1226} {} {D³ugo tu zostaniesz?}
{1227} {} {Nie mam pojêcia, co byœmy bez ciebie zrobili.}
{1228} {} {Cieszymy siê, ¿e jesteœ po naszej stronie.}
{1229} {} {Dziêkujê za wszystko.}