{100} {} {Widzisz osadnika.}
{101} {} {Widzisz jednego z mieszkañców Casa Grande. Trzêsie siê i chyba jest mu gor¹co.}
{102} {} {Widzisz jednego z mieszkañców Casa Grande.}
{103} {} {Pomyœlnie wyleczono pacjenta.}
{104} {} {Ten cz³owiek cierpi przez truciznê radskorpiona. Twoje umiejêtnoœci na nic siê zdadz¹ bez opowiedniego leku.}

{110} {} {* Uff-f-f *}
{111} {} {Uhh, trzêsê siê przez jad Skurwola.}
{112} {} {Zosta³em uk¹szony przez radskorpiona na obrze¿ach miasta.}

{115} {} {Dziêki, czujê siê ju¿ du¿o lepiej.}
{116} {} {Zosta³em uk¹szony przez radskorpiona na obrze¿ach miasta.}
{117} {} {Nie ma odpowiednio godnej nagrody dla uzdrowicieli takich jak ty.}
{118} {} {Dziêki doktorku. Ostatnio w okolicy pojawi³o siê du¿o radskorpionów. B¹dŸ ostro¿ny. Proszê, weŸ coœ do ochrony. (Daje ci amunicje)}

{120} {} {Och...}
{121} {} {* Khe-khe *}
{122} {} {* Hack *}
{123} {} {Ughh...}
{124} {} {* jêk *}
{125} {} {Hrr...}
