{100} {} {Widzisz osadnika.}
{101} {} {Widzisz nieco odra¿aj¹co wygl¹daj¹cego miejscowego mê¿czyznê. Wygl¹da na to, ¿e lokalne ¿ycie nie by³o dla niego ³askawe.}

{200} {} {Czego chcesz?}
{201} {} {Chcê tylko wiedzieæ jak wygl¹da ¿ycie w tym ma³ym miasteczku.}
{202} {} {Nie za dobrze. Jak wszêdzie indziej w naszych czasach. Ale mamy du¿o czystej wody. ChodŸby dlatego warto wybraæ Casa Grande.}
{203} {} {Dlaczego ulice s¹ tak wyludnione?}
{204} {} {Powiem ci coœ, nieznajomy. Casa Grande ma trudn¹ historiê. Z tej historii dowiedzieliœmy siê, ¿e lepiej nie zadawaæ pytañ o przesz³oœæ. Rozumiesz mnie? To wspaniale.}
{205} {} {Wygl¹da na to, ¿e bardzo czegoœ ¿a³ujesz.}
{206} {} {Wszyscy w tym mieœcie coœ stracili. I nie jestem wyj¹tkiem. Straci³em nasz stary dom i mojego syna. Ka¿dy ma podobn¹ historiê i nie chce siê ni¹ dzieliæ z obcymi.}
{207} {} {Tak, rozumiem. Mam nadziejê, ¿e wybaczysz moj¹ ciekawoœæ. PA.}
{208} {} {Mówi¹ te¿, ¿e ka¿dy ma to na co zas³u¿y³, narazie.}
{209} {} {Niewa¿ne.}

{210} {} {Znowu?}
{211} {} {Zapomnij o tym, tylko przechodzê.}

{220} {} {Szukam krewnych ch³opca o imieniu Cody.}
{221} {} {Cody? Tak nazywa³ siê nasz syn... Nie s³ysza³em o nim od kilku lat - odk¹d zabrali go Blacharze.}
{222} {} {NajwyraŸniej mówimy o tej samej osobie.}
{223} {} {Wiêc on ¿yje? To cud, ju¿ od dawna nie mieliœmy nawet nadziei... To znaczy, chcê powiedzieæ, ¿e kr¹¿¹ straszne plotki o Blacharzach. Jak on siê czuje?}
{224} {} {Zosta³ poddany praniu mózgu i zmuszony do pracy, ale na zewn¹trz wygl¹da dobrze.}
{225} {} {Tak, oczywiœcie. To ju¿ inna osoba... Wychowa³ siê jako Blacharz, zajmuje siê swoimi kawa³kami ¿elaza i chyba nawet o nas nie pamiêta. Bêdzie lepiej, jeœli tak pozostanie. Mam tylko nadziejê, ¿e nie ¿ywi do nas urazy.}
{226} {} {Hmm. Myœlê, ¿e powinienem wyjaœniæ mu tê kwestiê. Zegnam.}

{230} {} {Mam dowody, ¿e Cody nie zosta³ po prostu zabrany. *Sprzeda³eœ* go.}
{231} {} {Zamknij siê! Kim jesteœ, aby wtr¹caæ siê w nasze sprawy?}
{232} {} {Zaczekaj chwilê...}
{233} {} {Byliœmy na krawêdzi! Osada by³a bez wody, *musieliœmy* oddaæ wszystko, aby naprawiæ przepompowniê. W tym nasze dzieci. A teraz przychodzisz po tylu latach i poruszasz przesz³oœæ. Lepiej nas zostaw. Po prostu zostaw nas w spokoju.}
{234} {} {A teraz jesteœ tu gdzie jesteœ - nie mnie to os¹dzaæ. Zegnaj.}
{235} {} {Mam nadziejê, ¿e Cody jest w dobrych rêkach i ma lepsze ¿ycie ni¿ my.}
