{100} {} {Widzisz sierotê.}
{101} {} {Widzisz rozczochranego ch³opca o dziecinnym wygl¹dzie.}
{102} {} {Hrrrr ..}
{1102} {} {Ma... ma... hrr...}
{103} {} {Mam buty!}
{104} {} {Wow, wielkie dziêki!}
{105} {} {Zmiana butów uszczêœliwia dziecko.}

{200} {} {(Z boku ulicy dostrzegasz ch³opca o dzikim spojrzeniu. Jego w³osy s¹ strasznie potargane, ubranie brudne, a on sam ostro¿nie podrzuca w d³oni ma³y metalowy przedmiot, uwa¿nie obserwuj¹c twoje ruchy. )}
{201} {} {Hej ch³opcze. Nie wiesz, ¿e to niebezpieczne?}
{202} {} {(Przestaje podrzucaæ granatem i bacznie ci siê przygl¹da) Ja. Nie. Ch³opiec.}
{203} {} {Ok, uh, ja wiem. Ale ta rzecz nadal jest niebezpieczna. Nie rób tego co robi³eœ.}
{204} {} {Nie. Jesteœ ch³opcem. Dzieckiem. Niedojrza³ym dzieckiem cz³owieka. Trzymasz w rêku rzecz, która jest wyj¹tkowo niebezpieczna dla innych.}
{205} {} {(ch³opak wk³ada granat do kieszeni) I co z tego?}
{206} {} {No có¿, nic.}

{210} {} {Czego chcesz?}
{211} {} {Nic. Niewa¿ne.}

{212} {} {Um, ³adne ciuchy. Chcê je. Albo nie, s¹ zbyt rzucaj¹ce siê w oczy. Aby wtopiæ siê w piasek, potrzeba innego koloru. W przeciwnym razie wrogowie mnie znajd¹ i zabij¹.}
{213} {} {Tak, ten strój nie s³u¿y do chowania siê, wiesz.}
{214} {} {Za du¿o chcesz.}
{215} {} {Trzymaj siê ode mnie z daleka.}
{216} {} {Uwa¿aj! Trzymasz granat.}
{217} {} {Nie, nie...}
{218} {} {Hej, ty...}

{220} {} {Kiedy Stra¿nik mówi, ¿eby od³o¿yæ broñ, lepiej tak zrobiæ, ch³opcze.}
{221} {} {(patrzy na ciebie zdziwiony, potem na granat, potem znowu na ciebie i krêci g³ow¹)}
{222} {} {Tak, ch³opcze. Widzia³em jak koñcz¹ ludzie tacy jak ty bezmyœlnie bawi¹cy siê broni¹.}
{223} {} {Niewa¿ne, wspomnisz moje s³owa.}
{224} {} {Co siê z nimi sta³o?}
{225} {} {To smutny widok. Eksplozja odrywa im rêce, oczy pêkaj¹ i wyp³ywaj¹ z oczodo³ów. Ocalali wij¹ siê z bólu godzinami...}
{226} {} {Nic specjalnego. Kontynuuj dobr¹ zabawê, a sam siê przekonasz.}
{227} {} {(Ch³opiec rzuca granatem jak rozgrzanym ziemniakiem i ucieka.)}
{228} {} {Hej, nie poda³em jeszcze kilku innych przyk³adów dydaktycznych...}
{1228} {} {Hej, nie poda³am jeszcze kilku innych przyk³adów dydaktycznych...}

{230} {} {Chcê ten granat. Mo¿e siê wymienimy?}
{231} {} {Co masz?}
{232} {} {Zobaczmy...}
{233} {} {(Czeka na Twoje sugestie.)}
{234} {} {[Gotowe]}

{240} {} {Czy wiesz, co siê stanie, jeœli wyjmiesz zawleczkê?}
{241} {} {Wiem.}
{242} {} {Có¿, to cieszê siê z tego. Bywaj.}
{1242} {} {Có¿, to cieszê siê z tego. Bywaj.}
{243} {} {Nie. Ta rzecz zagra ³adn¹ melodyjkê. Dawaj, spróbuj.}
{244} {} {(chwilê siê zastanawia, a potem siêga po zawleczkê)}
{245} {} {Nie, nie, nie jestem tego pewien. Nie œpiesz siê z tym.}
{1245} {} {Nie, nie, nie jestem tego pewna. Nie œpiesz siê z tym.}
{246} {} {[pozwól mu wyci¹gn¹æ zawleczkê]}

{250} {} {Czy wiesz, co siê stanie, jeœli wyjmiesz zawleczkê?}
{251} {} {Wiem.}
{252} {} {Nie, nie wiesz. Po pierwsze, si³a eksplozji urwie ci oba ramiona. Rozrzuci je we wszystkie strony i nie bêdzie czego zbieraæ.}
{253} {} {(s³ucha z szeroko otwartymi oczami)}
{254} {} {Nastêpnie od³amki granatu przebij¹ ci klatkê piersiow¹ i ¿o³¹dek. Twoje wnêtrznoœci zwyczajnie wypadn¹ i zaczniesz krztusiæ siê krwi¹.}
{255} {} {(dyszy)}
{256} {} {Od³amki równie¿ uszkodz¹ ci oczy i te wyciekn¹ z orbit. Oœlepniesz i zemdlejesz. A kiedy siê obudzisz, doœwiadczysz kilku godzin nieznoœnego bólu w ka³u¿y w³asnej krwi, a¿...}
{257} {} {(ch³opiec rzuca granatem jak rozgrzanym ziemniakiem i ucieka)}
{258} {} {Hej, nie doszliœmy jeszcze do krwotoków wewnêtrznych...}

{260} {} {Daj mi teraz ten granat.}
{261} {} {(drwi, kiedy dostrzega twój blef)}
{262} {} {Och, taki jesteœ...}
{263} {} {}
{264} {} {Daj mi granat, a nikt nie zostanie ranny.}
{265} {} {(Szczerzy zêby jak wilk w obliczu niebezpieczeñstwa)}
{266} {} {S³yszysz? Daj mi granat. TERAZ.}
{267} {} {Nie martw siê, nie chcê ciê skrzywdziæ.}
{268} {} {(Odrêtwia³y, daje granat, ale szybko trzeŸwieje i ucieka przera¿ony.)}
{269} {} {To wszystko na nic.}
{270} {} {Dobry ch³opiec.}

{271} {} {Zagramy w grê? Jeœli przegram, dam ci 5 kapsli, w przeciwnym razie oddasz granat.}
{272} {} {(W oczach ch³opca pojawia siê podniecenie) OK!}
{273} {} {Ok, zacznijmy wiêc...}
{274} {} {Zrobimy to póŸniej, mam teraz coœ do zrobienia.}
{275} {} {Zagramy w grê? Jeœli przegrasz, zrezygnujesz z granatu.}
{276} {} {Nie, nie jestem taki g³upi.}
{277} {} {Ok, cokolwiek powiesz.}
{278} {} {Tak, widzisz. Chao.}
{279} {} {Nie masz 5 kapsli, aby rozpocz¹æ grê.}
{280} {} {Nie!}
{281} {} {O tak. Teraz granat jest mój. Ju¿ w porz¹dku, dzieciaku.}
{282} {} {Lepiej siê zamknij. Granat jest mój.}
{283} {} {Ha! Nie mo¿esz mnie pokonaæ.}
{284} {} {No có¿, zobaczymy.}
{285} {} {Jeœli bêdziesz dalej szydziæ, wezmê i kapsle i granat.}

{290} {} {Gdzie s¹ twoi rodzice, dzieciaku?}
{291} {} {Nie mam ich. Co ciê to obchodzi?}
{292} {} {Och, przepraszam, nie to mia³em na myœli.}
{1292} {} {Przepraszam, nie to mia³am na myœli.}
{293} {} {Nie musia³eœ od razu byæ niegrzeczny, ma³y bachorze.}

{300} {} {[U¿yj pozytywki i uruchom mechanizm]}
{301} {} {(Dziecko jest zahipnotyzowane melodi¹; nagle zaskoczenie pojawia siê na jego dzikiej twarzy, która od dawna nie zazna³a dzieciêcych uczuæ.)}
{302} {} {Co jest? Chcesz to?}
{303} {} {(Ch³opiec radoœnie kiwa g³ow¹, wyra¿aj¹c swoje pragnienie otrzymania niezwyk³ego przedmiotu w ka¿dy mo¿liwy sposób.)}
{304} {} {Proszê bardzo.}
{305} {} {[Wyci¹gnij rêkê, ale potem cofnij]}
{306} {} {(Ch³opiec uœmiecha siê nerwowo, wyra¿aj¹c chêæ dostania niezwyk³ego przedmiotu na ka¿dy mo¿liwy sposób.)}
{307} {} {Huh? [powtórz proces]}
{308} {} {(ch³opak przestaje ci ufaæ)}
{309} {} {Dobra, weŸ to.}
{310} {} {(Ch³opiec chwyta przedmiot, na jego twarzy po raz pierwszy w ¿yciu pojawia siê zwyk³a dzieciêca radoœæ.)}
{311} {} {A teraz powiedz mi, gdzie znalaz³eœ swój granat?}
{312} {} {O tam, w starej opuszczonej szkole. Ale czasami s¹ tam bandyci, to niebezpieczne.}
{313} {} {Nie obchodz¹ mnie zbiry. Zabierz mnie tam.}
{314} {} {To mój problem. I nie zamierzam zrezygnowaæ.}