{100} {} {Widzisz Gila McCord.}
{101} {} {Widzisz ¿ylastego, nieogolonego mê¿czyznê z bystrym okiem. Spogl¹da na ciebie z pow¹tpiewaniem spod kowbojskiego kapelusza.}
{102} {} {Nadal tu jesteœ? Nie boisz siê?}

{200} {} {Oto nadchodzi kat na kata. Ani drgnij, wiem o tobie wszystko. Powinienem by³ ciê wykoñczyæ zaraz po zabiciu pierwszego Los Panchos. NajwyraŸniej nie doceni³em twojej si³y.}
{201} {} {Nadal jestem pe³en niespodzianek, Gil McCord.}
{1201} {} {Nadal jestem pe³na niespodzianek, Gil McCord.}
{202} {} {Lepiej dobierz WSZYSTKIE swoje karty, bo stawk¹ jest czyjeœ ¿ycie. Moje lub twoje.}
{203} {} {Nie chcê z tob¹ walczyæ.}
{204} {} {Przekonajmy siê...}
{205} {} {Wiêc jesteœ jednym z tych g³upców, których ¿ycie niczego nie uczy. Na œwiecie nie ma ani dobra, ani z³a. Jeœli zlitujesz siê nad kimœ, przy pierwszej okazji strzeli ci w plecy. Takie jest prawo tego œwiata.}
{206} {} {Co za rozdzieraj¹ca serce przemowa. A teraz siê zamknij. Zabiorê twoj¹ g³owê do Bruca Turnera...}
{207} {} {RozejdŸmy siê w pokoju. Nie musimy walczyæ.}
{208} {} {Aby daæ ci lepszy moment na atak? Nie. Ten numer ze mn¹ nie zadzia³a.}
{209} {} {[Atak!]}
{210} {} {W takim razie walcz jak prawdziwy rewolwerowiec - stoczmy pojedynek.}
{211} {} {Zas³ugujesz na szacunek. Zgadzam siê.}
{212} {} {[WyjdŸ na drogê do czasu wymiany ognia]}
{213} {} {Naprawdê nie chcê mieæ wiêcej krwi na rêkach.}
{214} {} {O czym ty mówisz? Z zimn¹ krwi¹ odci¹³eœ g³owy trójce dzieci suko i kto wie, ilu wiêcej. A potem nios³eœ je przez kilka mil, rozkoszuj¹c siê smrodem rozk³adaj¹cego siê miêsa. A teraz mówisz, ¿e nie chcesz kolejnej œmierci? Nie oszukasz mnie.}
{1214} {} {O czym ty mówisz? Z zimn¹ krwi¹ odciê³aœ g³owy trójce dzieci suko i kto wie, ilu wiêcej. A potem nios³aœ je przez kilka mil, rozkoszuj¹c siê smrodem rozk³adaj¹cego siê miêsa. A teraz mówisz, ¿e nie chcesz kolejnej œmierci? Nie oszukasz mnie.}
{215} {} {To nie by³o do koñca tak. Ca³a brudna robota zosta³a wykonana za mnie.}
{216} {} {(Zatrzymuje siê z niedowierzaniem, a potem rozp³ywa siê w zadowolonym uœmiechu). Ha! Tak myœla³em. Jesteœ zwyk³ym szarlatanem. A teraz zniknij mi z oczu, nie jesteœ wart mojej uwagi.}
{1216} {} {(Zatrzymuje siê z niedowierzaniem, a potem rozp³ywa siê w zadowolonym uœmiechu). Ha! Tak myœla³em. Jesteœ zwyk³ym szarlatanem. A teraz zniknij mi z oczu, nie jesteœ warta mojej uwagi.}
{217} {} {To wszystko na nic. Tak ³atwo siê mnie nie pozbêdziesz, draniu...}
{218} {} {Cokolwiek powiesz, koleœ.}
