{100} {} {Widzisz Hrabiego Bustosa.}
{101} {} {Widzisz mê¿czyznê w dopasowanym, ale zniszczonym garniturze. Jego siwow³ose skronie wydaj¹ siê wskazywaæ na trudna przesz³oœæ.}
{102} {} {S³ysza³em o tej zbroi, ale myœla³em, ¿e to fikcja.}
{103} {} {Nie bêdê tolerowaæ zbirów w moim mieœcie.}
{104} {} {Radzê wam obojgu natychmiast opuœciæ miasto.}

#Pierwsze spotkanie
{200} {} {(Kiedy wchodzisz do biura lokalnego burmistrza, od razu czujesz zapach alkoholu. Rozgl¹daj¹c siê dooko³a, w koñcu zauwa¿asz mê¿czyznê na krzeœle, który patrzy na ciebie ze znu¿eniem przez palce. "M?" .)}
{201} {} {Gdzie jest burmistrz? Chcê z nim porozmawiaæ.}
{202} {} {(Z ciê¿kim westchnieniem osoba na krzeœle wyrywa siê z pochylonej pozycji i odchyla siê ze znu¿eniem). Jest przed tob¹. Kim jesteœ?}
{203} {} {Czy to ty jesteœ tu burmistrzem? Wygl¹dasz raczej jak zwyk³y urzêdnik, który przepija ca³¹ kasê w barze.}
{204} {} {Wyjaœnijmy sobie coœ. Niektórzy mówi¹, ¿e nie mo¿na chlaæ jak siê jest burmistrzem, ale to nieprawda. Mo¿na. Tylko trzeba wstawaæ rano. Na tym polega odpowiedzialnoœæ. A ja jestem prawnym i odpowiedzialnym burmistrzem tego miasta. Jeœli nie zamierzasz akceptowaæ lokalnych w³adz i lokalnych przepisów, natychmiast opuœæ Casa Grande. Moje miasto nie potrzebuje k³opotliwych osób z zewn¹trz. Czy to jasne?}
{205} {} {Brzmi sensownie, ok.}
{206} {} {Przepraszam, panie burmistrzu. Nie zamierzam stwarzaæ problemów.}
{207} {} {Dobrze. Wiêc sk¹d siê tu wzi¹³eœ?}
{1207} {} {To dobrze. Wiêc sk¹d siê tu wziê³aœ?}
{208} {} {Nazywam siê }
{209} {} {, podró¿ujê.}
{210} {} {Ok }
{211} {} {. Sk¹d jesteœ?}
{212} {} {Dlaczego to takie wa¿ne?}
{213} {} {Poniewa¿ w takim ma³ym mieœcie ka¿dy chce wiedzieæ, z kim ma do czynienia i jak bardzo mo¿e mu zaufaæ. A ciebie nikt tu w ogóle nie zna.}
{214} {} {Nikogo nie powinno obchodziæ moje pochodzenie.}
{215} {} {Ok, nie chcesz zaakceptowaæ zasad? Idziesz niebezpieczn¹ œcie¿k¹, nieznajomy. W takim razie wyjaœnij mi, co do cholery tutaj robisz?}
{1215} {} {Ok, nie chcesz zaakceptowaæ zasad? Idziesz niebezpieczn¹ œcie¿k¹, nieznajoma. W takim razie wyjaœnij mi, co do cholery tutaj robisz?}
{216} {} {Jestem z ma³ej wioski daleko st¹d. Nazywamy j¹ Villa.}
{217} {} {Nigdy o czymœ takim nie s³ysza³em. Za³ó¿my, ¿e to prawda. Co robisz w moim mieœcie tak daleko od domu?}
{218} {} {Tylko podró¿ujê. Mogê siê tu zatrzymaæ?}
{219} {} {Nie mam nic przeciwko. Zwykle odwiedzaj¹cy nas spêdzaj¹ noc w pobli¿u przepompowni wody, w barakach z karawanami.}
{220} {} {Dziêkujê panie burmistrzu.}
{221} {} {Co to za miasto, skoro nie ma tu nawet motelu? Ok, barak te¿ siê nada. Do widzenia, burmistrzu.}
{222} {} {Bustos. Nazywam siê Alfred Bustos. Teraz idŸ. Zmarnowa³em na ciebie zbyt du¿o czasu.}
{223} {} {[wyjdŸ]}

{224} {} {Szukam moich ludzi. Zostali schwytani przez handlarzy niewolników.}
{225} {} {(unosi brew) Niewolnicy? Liczysz na coœ jeszcze?}
{226} {} {S³ysza³eœ o nich?}
{227} {} {W³aœciciele niewolników czasami prowadz¹ swoich niewolników przez moje miasto. Ale nie pytam, sk¹d ich bior¹.}
{228} {} {Gdzie s¹ zabierani?}
{229} {} {Niektórych prowadzi siê na po³udnie do pracy. Innych po prostu sprzedaj¹... Pos³uchaj, nieznajomy... jak masz na imiê?}
{1229} {} {Niektórych prowadzi siê na po³udnie do pracy. Innych po prostu sprzedaj¹... S³uchaj, kobieto... jak masz na imiê?}
{230} {} {To nie ma znaczenia.}
{231} {} {.}
{232} {} {W³aœciciele niewolników to powa¿na si³a. Jeœli zabrali twoich krewnych, nie ma szans na odzyskanie ich wolnoœci. Poza tym moje miasto ¿yje z karawan. Nie wa¿ siê niszczyæ tego porz¹dku.}
{233} {} {Nie bojê siê ani handlarzy niewolników ani ciebie. Zegnaj burmistrzu.}
{234} {} {Chcê tylko odzyskaæ z powrotem moj¹ rodzinê. Musi pan to zrozumieæ, panie burmistrzu.}

{235} {} {W mieœcie nie ma wolnych miejsc pracy. Mo¿esz spêdziæ noc w baraku z karawanami w pobli¿u stacji wodnej.}
{236} {} {Bustos. Nazywam siê Alfred Bustos. Witaj w moim mieœcie.}
{237} {} {Potrzebujê burmistrza tego miasta. Pochodzê z Koœcio³a Swiêtego Ognia.}
{238} {} {Co za niespodzianka. Zwykle ostrzega siê mnie przed pojawieniem siê ambasadora waszego koœcio³a.}
{239} {} {WejdŸ. Rozgoœæ siê.}
{240} {} {Co teraz?}
{241} {} {Znowu? O co chodzi tym razem?}
{242} {} {Znowu? Mówi³em ci, ¿ebyœ wyjecha³ z mojego miasta.}
{243} {} {Do widzenia, hrabio Bustos.}
{244} {} {(Wchodz¹c do biura, zastajesz miejscowego burmistrza opieraj¹cego siê ze znu¿eniem o stó³. W drugiej rêce trzyma butelke alkoholu. „Och...” - mówi, widz¹c twoje kolorowe szaty.) To niespodzianka. Zwykle ostrzega siê mnie przed pojawieniem siê ambasadora waszego koœcio³a.}
{245} {} {Tylko przechodzê.}
{246} {} {Oczywiœcie. Rozgoœæ siê. Jedziesz do Tu-San? Czy jest coœ, co mogê zrobiæ, aby pomóc?}
{247} {} {Jestem zainteresowany konwojem niewolników. Byæ mo¿e by³ tu niedawno.}
{248} {} {Ostatnio Blacharze kupuj¹ niewolników do wa¿nych spraw. Przez moje miasto przeje¿dza³o kilka takich karawan. Ale nie pytam, sk¹d wziêli niewolników.}
{249} {} {Wiêc Tu-San... Dziêkujê, panie burmistrzu. Do zobaczenia.}

#Lazienka
{250} {} {Muszê z tob¹ porozmawiaæ o ³aŸni.}
{251} {} {To ten stary opuszczony budynek po drugiej stronie ulicy? Co ci na nim zale¿y?}
{252} {} {Pytam z czystej ciekawoœci. Nie œmiem ju¿ wiêcej pana rozpraszaæ, panie burmistrzu.}
{253} {} {No có¿, jest pewna osoba interesuj¹ca siê tym budynkiem.}
{254} {} {Ju¿ z ni¹ rozmawia³em. W naszym ma³ym miasteczku wszyscy siê znaj¹. Ludzie buduj¹ tu relacje od lat i wielu nie lubi pojawiaj¹cych siê znik¹d w s¹siedztwie nieznajomych z w¹tpliw¹ przesz³oœci¹. Nie bêdê tolerowaæ oszustów w moim mieœcie.}
{255} {} {Hmm. Gdzie zatem jest prawdziwy w³aœciciel ³aŸni?}
{256} {} {Musia³ zostaæ zjedzony przez radskorpiony. Te stworzenia s¹ prawdziw¹ plag¹ w naszym regionie.}
{257} {} {To okropne. Bêdê musia³ mu przekazaæ Twoj¹ odmowê.}
{258} {} {A poza tym pamiêtaj, ¿e nie lubiê, gdy ludzie wtykaj¹ nos w sprawy innych ludzi.}
{259} {} {Uch, dobrze, zapamiêtam.}
{260} {} {Rozumiem. Mogê ciê od niego uwolniæ raz na zawsze.}
{261} {} {Brzmi dobrze. Zap³acê 100 kapsli, ale nigdzie nie wspominaj mojego imienia. Nie chcê, ¿eby ucierpia³a moja reputacja.}
{262} {} {Mo¿esz na mnie polegaæ, panie burmistrzu.}
{263} {} {W takim razie chcê odkupiæ prawa do ³aŸni za 250 kapsli.}
{264} {} {Có¿, niech bêdzie. Przynieœ kapsle, wystawiê akt zakupu na k¹pielisko.}
{265} {} {Ok, do zobaczenia póŸniej.}
{266} {} {Oto kapsle, panie burmistrzu.}
{267} {} {Mam nadziejê, ¿e rozumiesz, po co siê rejestrujesz.}
{268} {} {Dziêkujê panie burmistrzu.}
{269} {} {Ma dokument w³asnoœci budynku.}
{270} {} {I nikt nie wie, sk¹d go wzi¹³. Przestañ testowaæ moj¹ cierpliwoœæ.}
{271} {} {Przepraszam panie burmistrzu.}
{272} {} {To dosyæ niemi³e z twojej strony.}
{273} {} {Ma dokument potwierdzaj¹cy prawa do ³aŸni. Potwierdzam jego to¿samoœæ.}
{274} {} {Ok, uda³o ci siê mnie przekonaæ. Ale niech ten ³otr wie, ¿e nikt tu na niego tu nie czeka³.}
{275} {} {Jak pan powiedzia³, panie burmistrzu.}
{276} {} {To niezbyt mi³e z twojej strony.}
{277} {} {To ma coœ wspólnego z niedawn¹ wojn¹ w Casa Grande, prawda? Boisz siê zemsty?}
{278} {} {(wzdycha) Chocia¿ nie zabi³em w³aœciciela ³aŸni, inni to zrobili... w tle wojny, któr¹ ja rozpocz¹³em.}
{279} {} {Myœlê, ¿e facet ju¿ o tym wie. Ale wygl¹da na to, ¿e interesuje go tylko biznes.}
{280} {} {To dla ciebie du¿e ryzyko, rozumiem. Przeka¿ê facetowi twoj¹ odmowê.}
{281} {} {Naprawdê? W takim razie mo¿e warto z nim porozmawiaæ. Chocia¿ jest ma³o prawdopodobne, aby to odpokutowa³o za moje grzechy.}
{282} {} {Swietnie. Pójdê do niego.}
{283} {} {Znamy siê dobrze. Gwarantujê, ¿e mo¿na mu zaufaæ.}
{284} {} {Wiêc porozmawiaj z nim. Chocia¿ jest ma³o prawdopodobne, aby to odpokutowa³o za moje grzechy.}
{285} {} {Swietnie. Pójdê do niego.}
{286} {} {? Nic dziwnego, ¿e osoba o takim imieniu nie mo¿e usiedzieæ spokojnie. }
{287} {} {Jeœli to ¿art, to nieœmieszny. Jeœli coœ ci siê stanie, pomyœl¹ o mnie, bo nikt nie zda sobie sprawy, ¿e w mieœcie s¹ dwie osoby o tym samym imieniu. To bêdzie bardzo nieprzyjemne...}

{290} {} {Osoba z zewn¹trz ju¿ ci nie przeszkadza.}
{291} {} {Bardzo dobrze. Nie lubiê brudziæ sobie r¹k.}
{292} {} {[Dalej.]}
{293} {} {Ka¿da praca powinna byæ godnie op³acona. Oto Twoje 100 kapsli. Ale nie zapominaj - nie mam nic wspólnego z tym incydentem.}
{294} {} {Nikt siê niczego nie dowie, panie burmistrzu.}
{295} {} {Nie le¿y w moim interesie niszczenie relacji z potencjalnymi klientami.}

# Zatrzymaj dialog
{300} {} {Nie wiem, co chcesz osi¹gn¹æ, ale jesteœ od teraz wrogiem na mojej liœcie. Wynoœ siê z mojego miasta. Nie chcê tu takich idiotów jak ty.}
{301} {} {[Opuœæ budynek]}
{302} {} {Stra¿nicy wyprowadzaj¹ ciê na zewn¹trz.}

{308} {} {Witam. WyobraŸ sobie, ¿e jakiœ g³upiec kopie groby na naszym cmentarzu. Mo¿e wiesz, kto to robi?}
{309} {} {Ktoœ kopie groby? Nic o tym nie wiem.}
{310} {} {Pamiêtam ciê. Po twoim pojawieniu siê na cmentarzu znaleziono wykopane groby.}
{311} {} {Dziwny zbieg okolicznoœci, prawda?}
{312} {} {I co z tego? Zarzucasz mi coœ?}
{313} {} {Nie wierzê w zbiegi okolicznoœci. Jeœli chocia¿ jeden dowód pojawi siê przeciwko tobie w tym przypadku, czeka ciê okrutna kara.}
{314} {} {Ooh, jakie to straszne.}
{315} {} {Wygl¹da na to, ¿e zwariowa³eœ, jeœli zachowujesz siê w ten sposób wobec urzêdnika pañstwowego. Zwykle jest du¿o pob³a¿liwoœci dla g³upców, ale nie w tym mieœcie. Jesteœmy zmêczeni niekoñcz¹cymi siê problemami. Wiêc nie testuj mojej cierpliwoœci. Czy to jasne?}
{316} {} {Rozumiem.}
{317} {} {Nie mam z tym nic wspólnego, panie burmistrzu.}
{318} {} {Ok. Na razie zajmijmy siê swoimi sprawami. Nie zawiedŸ mnie.}
{319} {} {Oczywiœcie, hrabio Bustos. Nie ma problemu.}

{320} {} {Ochrona mówi, ¿e naprawi³eœ latarniê.}
{1320} {} {Ochrona mówi, ¿e naprawi³aœ latarniê.}
{321} {} {Dok³adnie.}
{322} {} {Nie wiem, dlaczego chcia³eœ to zrobiæ. Ale jeœli chcia³eœ zaimponowaæ, to ci siê uda³o. Dziêkujê Ci.}
{1322} {} {Nie wiem, dlaczego chcia³aœ to zrobiæ. Ale jeœli chcia³aœ zrobiæ dobre wra¿enie, uda³o ci siê. Dziêkujê Ci.}
{323} {} {Niczego za to nie dostanê?}
{324} {} {Nie prosi³em ciê o naprawianie latarni. Ale w nagrodê mo¿esz wzi¹æ czyst¹ wodê.}
{325} {} {Dziêkujê panie burmistrzu.}
{326} {} {Czy to wszystko na co Ciê staæ? Niech bêdzie...}
{327} {} {Po prostu lubiê zag³êbiaæ siê w stare technologie. Nie ma za co.}
{328} {} {Zwiêkszasz swój status w oczach burmistrza, a tym samym reszty miasta.}
{329} {} {Tak.}

{330} {} {Twoja osoba to jeden wielki problem.}
{331} {} {Naprawdê?}
{332} {} {O czym ty mówisz?}
{333} {} {Cia³o jednego z mieszkañców zosta³o znalezione w pobli¿u stacji kolejowej. Wiesz coœ o tym?}
{334} {} {Nie, nic nie wiem.}
{335} {} {Ok. Nie dowiedzieliœmy siê jeszcze, co siê tam wydarzy³o. Jeœli coœ wiesz to lepiej siê przyznaj. A teraz idŸ, mam du¿o pracy.}
{336} {} {[Zostaw burmistrza w spokoju]}
{337} {} {Brakuje jednego z mieszkañców. Ostatnio widziano go w pobli¿u stacji kolejowej, gdzie ³apie siê iguany. Wiesz coœ o tym?}
{338} {} {Radskorpiony musia³y go po¿reæ. Jest ich tu strasznie du¿o.}
{339} {} {Najprawdopodobniej. A jednak sk¹dœ wiesz, ¿e pojawi³y siê tam radskorpiony. Jeœli siê dowiesz wiêcej, daj mi znaæ. A teraz idŸ, mam du¿o pracy.}
{340} {} {Nie by³o mu przeznaczone wróciæ do miasta. Winne temu s¹ radskorpiony.}
{341} {} {To wszystko. Có¿, brzmi to wiarygodnie. Mo¿esz odejœæ.}
{342} {} {[wyjdŸ]}

#Zapytania
{350} {} {Szukam Blacharza, który zosta³ wys³any tu do ciebie jako ambasador.}
{351} {} {Nie wróci³ do Tu-San? W takim razie nie wiem gdzie mo¿e byæ.}
{352} {} {A by³ tutaj?}
{353} {} {Tak, ale znikn¹³ bez s³owa. Myœla³em, ¿e sobie poszed³.}
{354} {} {I nie widzia³eœ w tym nic dziwnego?}
{355} {} {Blacharze uwa¿aj¹ nas, zwyk³ych œmiertelników, za rodzaj dzikusów. To dziwni ludzie, mo¿na siê po nich spodziewaæ wszystkiego. Wiêc nie zawraca³em sobie g³owy cichym wyjazdem naszego goœcia. Z pewnoœci¹ jest ju¿ wœród swoich.}
{356} {} {Nie, nie wróci³ do Tu-San. Mistrz Hard poprosi³ mnie o znalezienie go.}
{357} {} {Och, rozumiem. Có¿, powiedzia³em wszystko, co wiem. Mo¿esz zapytaæ gdzie indziej.}
{358} {} {Tak zrobiê. PA.}
{359} {} {Myœlê, ¿e coœ tu nie gra. Twoje szczêœcie, burmistrzu, jeœli jego znikniêcie nie ma z tob¹ nic wspólnego.}
{360} {} {Wydaje siê, ¿e miejscowi nie lubi¹ Blacharzy. Kto móg³by ¿yczyæ mu krzywdy?}
{361} {} {Uwa¿aj na jêzyk, najemniku. Jesteœmy wdziêczni Blacharzom za naprawê pompy wodnej i trasy zwyk³ych karawan. Zaden z miejscowych nie chcia³by ich skrzywdziæ.}
{1361} {} {Uwa¿aj na jêzyk, najemniku. Blacharzom zawdziêczamy naprawê pompy wodnej i trasy zwyk³ych karawan. Zaden z miejscowych nie chcia³by ich skrzywdziæ.}
{362} {} {I tak sprawdzê tê wersjê. PA.}
{363} {} {Taki rodzaj zaufania budzi wiêcej w¹tpiwoœci, burmistrzu. Mam nadziejê, ¿e ciê nie zawiedzie.}
{364} {} {Czy nie wydaje Ci siê dziwne, ¿e znikn¹³?}
{365} {} {Czy dotar³ do Casa Grande?}
{366} {} {Nigdy nie wróci³ do Tu-San. Poproszono mnie, ¿eby go znaleŸæ.}
{367} {} {Wygl¹da na to, ¿e marnujê z tob¹ czas. Poszukam Blacharza gdzie indziej.}
{368} {} {Z pewnoœci¹ tak. Przepraszam, ¿e rozpraszam ciê w interesach.}
{1368} {} {Z pewnoœci¹ tak. Przepraszam, ¿e przeszkadzam.}
{369} {} {Gdzie przebywa³ podczas wizyty?}

{370} {} {Chcê zapytaæ o miasto, jeszcze niewiele o nim wiem.}
{371} {} {Casa Grande to mój skarb. Co chcesz wiedzieæ?}
{372} {} {Wszystko, co musisz wiedzieæ, to kierunek wyjazdu z miasta.}
{373} {} {Nikt nie zna Casa Grande lepiej ni¿ ja. Co chcesz wiedzieæ?}
{374} {} {Wiem wystarczaj¹co du¿o. PA.}
{375} {} {Pozwól mi poœwiêciæ trochê wiêcej twojego czasu.}
{376} {} {W dawnej chacie bimbrownika na wschodzie. Blacharze nie lubi¹ przebywaæ w pobli¿u... „zwyk³ych” ludzi.}

{380} {} {Co mogê robiæ w tym mieœcie?}
{381} {} {Casa Grande to ma³e miasteczko. Mieliœmy kiedyœ salon, który by³ znany w ca³ym regionie z w³asnej gorza³ki i starej muzyki. Ale teraz bar jest zamkniêty, a szafa graj¹ca zepsuta.}
{382} {} {Co siê sta³o?}
{383} {} {Strzelanina w barze siê sta³a. Ale to ju¿ przesz³oœæ. Niestety tak samo jak bar.}
{384} {} {Oboje wiemy, ¿e to nie by³a do koñca strzelanina.}
{385} {} {Za du¿o wiesz. W barze moi ludzie przygotowali zasadzkê na wrogi klan. Barman dosta³ zab³¹kan¹ kulê. Przykro mi, bo by³ cz³owiekiem o serdecznym sercu.}
{386} {} {Dziêkujê za szczer¹ odpowiedŸ. Myœlê, ¿e lepiej by³oby zmieniæ temat.}
{387} {} {Wow, w³asny alkohol?}
{388} {} {Tak, produkcja lokalna. Prawdopodobnie próbowa³eœ kiedyœ tego wspania³ego napoju. Bimber by³ wymieniany na inne towary w Phoenix. Ech, gdyby nie te przeklête radskorpiony, nadal przynosi³by niez³e dochody do skarbca.}
{389} {} {Widzia³em ju¿ wczeœniej produkcjê tequili w Phoenix.}
{390} {} {Naprawdê? Czasami karawany nios¹ sok z ognistej agawy dla Phoenix z po³udnia. Dla naszego piwowara ta konkurencja by³a jak gula w gardle. A teraz sami kupujemy ten alkohol z Phoenix.}
{391} {} {Doœæ o smutnych rzeczach. Musimy zmieniæ temat rozmowy.}
{392} {} {Czy jest tu jakiœ sklep?}
{393} {} {Jeœli potrzebujesz wody, idŸ do stacji wodnej. Resztê towaru odbieramy z karawan na pobliskim parkingu.}
{394} {} {Dlaczego jest tu tak wiele karawan?}
{395} {} {Poniewa¿ mamy du¿o wody i jesteœmy w po³owie drogi miêdzy Phoenix a osad¹ Tu-San. Ca³kiem niez³a lokalizacja, tak¿e dla bandytów z okolic do ataku.}
{396} {} {Plotka g³osi, ¿e Blacharze ju¿ nie maj¹ tu czego szukaæ. Jak to wp³ynie na Casa Grande?}
{397} {} {Oprócz Blacharzy s¹ te¿ inne osady na po³udniu. Nadal mo¿emy handlowaæ wod¹. Ponadto, po us³yszeniu tej historii, wielu maruderów rzuci³o siê na po³udnie. Na razie wiêc utrzymamy siê na powierzchni, ale co bêdzie dalej?}
{398} {} {Mówi¹, ¿e Koœció³ Ognia w Phoenix zosta³ zniszczony.}
{399} {} {Tak, i to jest problem. W pewnym sensie Koœció³ aktywnie wspiera³ ten szlak karawan. Bez niego bêdzie mniej karawan. Ale z czasem ktoœ z pewnoœci¹ zajmie ich miejsce.}
{400} {} {Jakie niebezpieczeñstwa na mnie czekaj¹ w okolicy?}
{401} {} {Na trasie 10 mo¿na znaleŸæ wszelkiego rodzaju mot³och. Ci bandyci rabuj¹ karawany i innych podró¿ników, przez co ponosimy straty.}
{402} {} {Czy próbowa³eœ ich z³apaæ?}
{403} {} {Kogo? Dwa tuziny rozproszonych i ci¹gle zmieniaj¹cych siê gangów? Ta walka nigdy siê nie skoñczy. Jednych zabijesz to inni zajm¹ ich miejsce. Wa¿niejsze jest skupienie siê na bezpieczeñstwie w mieœcie.}
{404} {} {Na razie zapomnijmy o sprawach miejskich, mam inne pytania.}
{405} {} {Jestem zainteresowany t¹ stacj¹ wodn¹.}
{406} {} {Porozmawiaj o tym z Sullivanem na stacji. Zna j¹ jak w³asn¹ kieszeñ.}
{407} {} {Porozmawiaj o tym z kimœ na stacji.}
{408} {} {Ok, sprawdzê to póŸniej.}
{409} {} {Swietny pomys³, zaraz tam pójdê.}
{410} {} {Opowiedz mi o tym Sullivanie. Kim on jest?}
{411} {} {Nie rozmawiam o moich ludziach z nieznajomymi. Jeœli chcesz poznaæ Sullivana, poznaj go osobiœcie.}
{412} {} {Mam jeszcze jedno pytanie przed wyjazdem.}
{413} {} {W takim razie pójdê prosto do niego. PA.}
{414} {} {Opowiedz o tym Sullivanie. Jest dobrym cz³owiekiem?}
{415} {} {Jest dla mnie jak brat. Zaczêliœmy to wszystko razem. Wiedzia³em, jak negocjowaæ z ludŸmi, a on wiedzia³, jak rozwi¹zywaæ problemy. By³oby ciê¿ko bez Johna.}
{416} {} {Wygl¹da na to, ¿e naprawdê jesteœcie jak bracia. Ale bardziej interesuje mnie miasto.}
{417} {} {Zwykle s³owo „brat” traci wszelkie znaczenie, jeœli chodzi o interesy.}
{418} {} {Zignorujê to. Mo¿liwe, ¿e w du¿ym mieœcie kapsle s¹ najwa¿niejsze, ale nie tutaj. Ceniê Johna jako osobê godn¹ zaufania. Jest najbardziej godnym zaufania cz³owiekiem w ca³ym Casa Grande.}
{419} {} {Sullivan by³ twoim przyjacielem?}
{420} {} {Nie wymieniaj jego imienia. Zaczêliœmy to wszystko razem i nie mog³em spodziewaæ siê takiej zdrady. Nawet nie chcê o nim s³yszeæ.}
{421} {} {Czy nie nazwa³eœ go wczeœniej „najbardziej godnym zaufania cz³owiekiem w Casa Grande”?}
{422} {} {Wygl¹da na to, ¿e to dra¿liwy temat. Nie rozmawiajmy ju¿ o tym.}
{423} {} {(uderza w stó³) Sullivan... Dosta³ to, na co zas³u¿y³ za swoj¹ pod³oœæ. Mogê tylko wymazaæ tego zdrajcê z mojego ¿ycia. Lepiej zamknij siê, zanim nasze relacje ca³kiem siê popsuj¹.}
{424} {} {Przepraszam, nie bêdziemy wiêcej o tym rozmawiaæ.}
{425} {} {Jeœli chcesz zamkn¹æ oczy na b³êdy z przesz³oœci, decyzja nale¿y do Ciebie. Zmieñmy temat.}
{426} {} {Naprawdê sprowadzasz jedynie œmieræ do swojego miasta. Mam doœæ tych przera¿aj¹cych historii.}
{427} {} {}
{428} {} {W ogóle nie powinienem wchodziæ w to gówno. Zegnaj burmistrzu.}
{429} {} {S³aba argumentacja, burmistrzu. Bardzo s³aba.}

{430} {} {Masz niezwykle du¿y cmentarz jak na tak ma³¹ populacjê.}
{431} {} {Nie powinieneœ tam wchodziæ. I pytaæ o rzeczy, które w ¿aden sposób Ciê nie dotycz¹.}
{432} {} {Przepraszam, ju¿ nie bêdê.}
{433} {} {Mimo wszystko. Co tu siê sta³o?}
{434} {} {Po trochu wszystkiego - rabusie, skorpiony... i to wystarczy. Ludziom nie podoba siê, gdy ich przesz³oœæ jest wspominana.}
{435} {} {Wiem, co siê tu wydarzy³o w przesz³oœci. Si³¹ przej¹³eœ w³adzê w Casa Grande.}
{436} {} {Ten rabus twierdzi³, ¿e zabi³eœ po³owê populacji, aby dojœæ do w³adzy.}
{437} {} {Trudne czasy wymagaj¹ trudnych decyzji. Gdybym wtedy nie rozpocz¹³ walki, rozpocz¹³by j¹ ktoœ inny. To jest naturalny stan rzeczy.}
{438} {} {Czy to serio by³o konieczne?}
{439} {} {By³o za du¿o ludzi i za ma³o zasobów. To miasto przetrwa tylko dziêki pompie wodnej i jako obóz dla karawan. Na tej pustyni nie ma nic innego, co da³oby mu i nam ¿ycie. W rezultacie wielu nie znalaz³o dla siebie miejsca, zaczê³y siê rabunki i wojny klanów.}
{440} {} {Teraz rozumiem, dlaczego ci¹gle jesteœ pijany.}
{441} {} {Wiêc to dlatego masz tak wielu ochroniarzy.}
{442} {} {Nie mo¿esz uciec przed przesz³oœci¹. To twój krzy¿.}
{443} {} {Zdarzy³o mi siê odwiedziæ miejsce, w którym przywrócono staro¿ytn¹ fabrykê. Tam te¿ w walce o ni¹ zginê³o wiele osób.}
{444} {} {Naprawdê? Heh, ma³a pociecha. Ale cieszê siê, ¿e pustkowia w koñcu siê zmieniaj¹. Mam nadziejê, ¿e za mojego ¿ycia zobaczê Corwegê w ruchu, jak w starych filmach.}
{445} {} {Jesteœ potworem. Jak mog³eœ zabiæ dziesi¹tki ludzi dla w³asnej korzyœci?}
{446} {} {Jeœli ta rozmowa jest dla Ciebie zbyt trudna, porozmawiajmy o czymœ innym.}
{447} {} {Teraz wiem, co zrobiæ w najbli¿szej przysz³oœci. Do widzenia.}
{448} {} {Zamknij siê i s³uchaj. JESTEM BURMISTREM TEGO MIASTA. Jestem za nie odpowiedzialny. I nie pozwolê nikomu bezczeœciæ jego dobrego imienia. Kim jesteœ, ¿eby mnie os¹dzaæ? Zwyk³ym nieznajomym, który akurat przechodzi³ w pobli¿u. Wiêc idŸ w³asn¹ drog¹.}
{449} {} {Racja. Jestem tylko podró¿nikiem, który wpad³ po wodê. Zegnaj burmistrzu.}
{1449} {} {Racja. Jestem tylko podró¿nikiem, który wpad³ po wodê. Zegnaj burmistrzu.}

# Pierwsze zadanie
{450} {} {Czy jest dla mnie jakaœ praca w mieœcie? Przyda³oby mi siê trochê pieniêdzy.}
{451} {} {Nie mam dla ciebie ¿adnej pracy, niestety.}
{452} {} {Rozumiem. Ale mo¿e mo¿esz odpowiedzieæ mi na kilka pytañ?}
{453} {} {Ok, popytam innych w osadzie.}
{454} {} {Nie mam dla ciebie ¿adnej pracy... mo¿esz jednak rozwi¹zaæ jeden problem.}
{455} {} {O jakim problemie mowa?}
{456} {} {Bandyci okradli jedn¹ z karawan w pobli¿u stacji kolejowej i zamknêli siê z towarem w œrodku. Wygl¹da na to, ¿e nie zamierzaj¹ odejœæ, jakby nas prowokowali lub testowali. IdŸ tam i dowiedz siê, czego chc¹.}
{457} {} {Czy twoi ludzie stoj¹ tu na poka¿?}
{458} {} {Czy w tym mieœcie nie ma ¿adnego szeryfa?}
{459} {} {Nikt nie chce ryzykowaæ ¿ycia dla pude³ka starych szmat, które ukradli. Mamy nadziejê, ¿e bandyci zmêcz¹ siê siedzeniem w zamkniêciu i sami wyjd¹.}
{460} {} {Potrzebujê kapsli, ale nie zamierzam ryzykowaæ. Poszukaj kogoœ innego.}
{461} {} {Ok, uwolniê ciê od tych z³odziei.}
{462} {} {Swietnie. Stacja znajduje siê na po³udnie st¹d.}
{463} {} {Przygotuj swoj¹ nagrodê. Wkrótce te szumowiny po¿a³uj¹ ¿e siê tu pokaza³y.}

{470} {} {Tu jesteœ. WejdŸ, usi¹dŸ. Po tym ba³aganie w barze chcia³em trochê odpocz¹æ i napiæ siê drinka. Sobie te¿ coœ nalej. W koñcu to dziêki Tobie moja córka i ja nadal cieszymy siê nasz¹ wolnoœci¹.}
{471} {} {Dziwna historia. Hrabio, dlaczego rabusie zbli¿yli siê do miasta?}
{472} {} {Zbiry zwykle okradaj¹ podró¿nych na autostradzie i boj¹ siê zbli¿yæ do miasta. Ale ci wiedzieli, co robiæ, poniewa¿ ich przywódca mieszka³ kiedyœ w Casa Grande... Jednak to d³uga historia i nadal nie zap³ci³em ci za twoj¹ pomoc.}
{473} {} {[Dalej.]}
{474} {} {Oto 250 kapsli. Mo¿esz zarobiæ wiêcej.}
{475} {} {Wiêcej? O ile wiêcej?}
{476} {} {S³ucham. Kto jest problemem tym razem?}
{477} {} {Twoja wolnoœæ kosztowa³a kogoœ ¿ycie, prawda?}
{478} {} {Twój jêzyk jest zbyt d³ugi jak na najemnika. Jak wiesz, zbiry z autostrady okradaj¹ podró¿nych na autostradzie i szlakach karawan. Ale z³odzieje w barze mieli osobiste porachunki. To jednak d³uga historia, a ja nadal ci nie zap³ci³em.}
{479} {} {[Dalej.]}
{480} {} {Tutaj jesteœ... WejdŸ. Potrzebujê drinka po tym ba³aganie w barze.}
{481} {} {Przykro mi, ¿e twoja córka zmar³a.}
{482} {} {Do diab³a z ¿alem! Kiedyœ pope³ni³em b³¹d, wypêdzaj¹c niektórych mieszkañców z miasta, zamiast ich rozstrzelaæ. I wrócili. Teraz muszê siê okrutnie zemœciæ na tym ca³ym marginesie z autostrad...}
{483} {} {[Dalej.]}
{484} {} {Próbujesz utopiæ smutki? To nie wypali.}
{485} {} {Co ty wiesz... (uspokaja siê) Masz racjê. Kiedyœ pope³ni³em b³¹d, wypêdzaj¹c niektórych mieszkañców z miasta, zamiast ich rozstrzelaæ. I wrócili. Muszê siê teraz zemœciæ na nich...}
{486} {} {[Dalej.]}
{487} {} {Wygl¹da na to, ¿e potrzebujesz kapsli? Nie zap³acê za starcie w barze. Ale zap³acê za now¹ robotê.}
{488} {} {Co mam zrobiæ?}
{489} {} {Ci bandyci w barze nale¿eli do najwiêkszego klanu autostrad, Niebieskich Tarczy. Jest znany w ca³ej okolicy ze swoich bezlitosnych zbrodni. Okradawszy ostatnie karawany, te szumowiny zdoby³y dobry sprzêt. Dlatego teraz ca³e miasto jest w niebezpieczeñstwie.}
{490} {} {Sugerujesz, abyœmy ich powstrzymali? Ale jak?}
{491} {} {Zabij ich przywódcê, Bena. Zap³acê 500 kapsli za jego g³owê.}
{492} {} {Szuka³em m¹drych ludzi, takich jak ty, aby znaleŸæ ich legowisko i wykoñczyæ ich przywódcê Bena przez d³ugi czas. Bez niego klan siê rozpadnie i przynajmniej na chwilê zostawi¹ nas w spokoju.}
{493} {} {Nie musisz mi wyjaœniaæ ca³ej historii. Jaka jest cena?}

# Drugie zadanie
{500} {} {Lokalni bandyci s¹ jak padlino¿ercy - zbieraj¹ siê w stada i poluj¹ na ³atw¹ zdobycz na autostradach. Ma³e klany nie stanowi¹ zagro¿enia dla miasta. Ale jest jeden du¿y.}
{501} {} {Niech zgadnê - to st¹d przyszli rabusie i z³apali twoj¹ córkê?}
{502} {} {Tak. I to nie jest ich pierwszy powa¿ny atak. Klan Niebieskich Tarcz jest znany w ca³ym regionie ze swych bezlitosnych zbrodni. Sk³ada siê z najbardziej zdesperowanych i lekkomyœlnych drani, dla których nie ma miejsca w cywilizowanym spo³eczeñstwie.}
{503} {} {Brzmi okropnie. Ale czy mo¿na powstrzymaæ ca³y gang za pomoc¹ najemników?}
{504} {} {Pieprzyæ historie. Po prostu powiedz mi, jak ich znaleŸæ.}
{505} {} {Nie ma potrzeby zabijania ca³ego t³umu. Zap³acê 500 kapsli za g³owê ich przywódcy, Bena. Tê sam¹ kwotê otrzymasz, jeœli zniszczysz ich sk³ad paliwa.}
{506} {} {Wszystkie te œmierci bêd¹ moimi koszmarami na wiêcej ni¿ jedn¹ noc. Tym razem umywam rêce.}
{507} {} {Có¿, szkoda. Mia³em ju¿ nadziejê, ¿e przede mn¹ stoi naprawdê prawdziwy wojownik. Ale nie œpiesz siê z decyzj¹. Problem nie rozwi¹¿e siê sam, a ja zawsze jestem gotów zap³aciæ za dobr¹ robotê.}
{508} {} {Do widzenia.}
{509} {} {Dobrze, czuj siê jakby czaszka Bena by³a ju¿ w twoich rêkach.}
{510} {} {To proste. Przynieœ g³owê - a otrzymasz nagrodê. Powodzenia.}
{511} {} {Do widzenia.}
{512} {} {Muszê dowiedzieæ siê wiêcej o tych typach.}

{520} {} {O robocie.}
{521} {} {Jakieœ wiadomoœci?}
{522} {} {Jeszcze nie. Chcê tylko powiedzieæ, ¿e pracujê nad tym problemem. PA.}
{523} {} {Dlaczego ten klan jest taki silny?}
{524} {} {Po atakach na ostatnie karawany rabusie ci otrzymali dobry sprzêt, który Blacharze zrobili na swoich maszynach. Ponadto maj¹ ogromne rezerwy paliwa. Jeœli taka akcja siê powtórzy, wkrótce ca³e miasto bêdzie w powa¿nych tarapatach.}
{525} {} {Sk¹d wziêli tyle paliwa?}
{526} {} {Mówi¹, ¿e przejêli stary sk³ad benzyny i u¿ywaj¹ go jako fortecy. A ich broni¹ jest owo paliwo.}
{527} {} {Opowiedz mi o ich przywódcy.}
{528} {} {Nazywa siê Ben. Kiedyœ mieszka³ wœród nas, ale wyrzuci³em go z miasta. Dlatego tak dobrze go znam.}
{529} {} {Dlaczego zabicie przywódcy jest takie wa¿ne?}
{530} {} {Bez przywódcy klan siê rozpadnie i zostawi nas w spokoju, przynajmniej na chwilê.}
{531} {} {Jaki jest sens niszczenia sk³adu paliwa?}
{532} {} {Paliwo s³u¿y im jako broñ i pomaga przetrwaæ. A w przysz³oœci mo¿e byæ u¿ywane do handlu. Dodatkowo przy zniszczonym sk³adzie korzystanie z cytadeli bêdzie trudniejsze. W ka¿dym razie taki sabota¿ mocno wstrz¹œnie gangiem.}
{533} {} {Jak siê dowiesz, ¿e wysadzi³em te magazyny?}
{534} {} {Zobaczê dym przez lornetkê. Takie wydarzenie przed nikim siê nie ukryje.}
{535} {} {Gdzie jest g³ówna baza Niebieskich Tarcz?}
{536} {} {Wed³ug karawan jest gdzieœ na pó³nocny wschód od nas.}
{537} {} {Jak to siê sta³o, ¿e mieszkañcy Casa Grande zostali lokalnymi bandytami?}
{538} {} {To stara i d³uga historia. Kiedy zosta³em burmistrzem, pierwsz¹ rzecz¹, jak¹ zrobi³em, by³o wyrzucenie wszystkich szumowin z miasta. Jak siê okaza³o, czêœæ z nich prze¿y³a i zaczê³a terroryzowaæ pobliskie autostrady.}
{539} {} {Dowiedzia³em siê wystarczaj¹co du¿o. Do zobaczenia, hrabio.}
{1539} {} {Dowiedzia³am siê wystarczaj¹co du¿o. Do zobaczenia, hrabio.}
{540} {} {To g³owa twojego wroga. Rozpoznajesz go?}
{541} {} {(przez chwilê patrzy na g³owê z pogard¹ i nienawiœci¹, po czym macha rêk¹) Wyrzuæ to na pustkowiê. Niech radskorpiony zjedz¹ ostatnie co zosta³o z tego gangu.}
{542} {} {Cokolwiek powiesz, hrabio.}
{543} {} {Nie, nie dotykaj. Trzeba zawiesiæ tê g³owê na s³upie przy wjeŸdzie do miasta. Da znaæ ludziom, co ich czeka w przypadku niepos³uszeñstwa w³adzom.}
{544} {} {Dobry pomys³. }
{545} {} {Nie zapomnij podpisaæ, kto go zabi³.}
{546} {} {Doceniam ludzi, którzy bezb³êdnie wykonuj¹ swoj¹ robotê. Zas³ugujesz na nagrodê... (wyci¹ga kapsle z sejfu) Oto 500 kapsli, zgodnie z umow¹. Teraz zostaw mnie w spokoju. Chcê odpocz¹æ.}
{547} {} {Zegnaj, hrabio.}
{548} {} {Hej, gdzie moja nagroda? Nie po to nara¿a³em w³asne ¿ycie ¿eby mnie poklepaæ po plecach.}
{549} {} {Oczywiœcie. Zas³ugujesz na nagrodê... (wyci¹ga kapsle z sejfu) Oto 500 kapsli, tak jak ustaliliœmy. Teraz zostaw mnie w spokoju.}

{550} {} {Zniszczy³em magazyny paliwa Niebieskich Tarcz. To z pewnoœci¹ os³abi gang.}
{1550} {} {Zniszczy³am magazyny paliwa Niebieskich Tarcz. To z pewnoœci¹ os³abi gang.}
{551} {} {Wiêc plotki nie k³ami¹. Ludzie z karawany zauwa¿yli dym z boku szlaku handlowego. Teraz bandytom bêdzie zdecydowanie ciê¿ej.}
{552} {} {Um. Nie pracujê za darmo, wiesz?}
{553} {} {Oczywiœcie, oto nagroda - 500 kapsli. I dziêki. Twoje us³ugi s¹ nieocenione dla miasta.}
{554} {} {Nie ma za co, hrabio. Dopóki miasto zapewnia mi zarobek, ma przysz³oœæ.}
{555} {} {W mojej spo³ecznoœci dobrze wiemy, jak radziæ sobie z szumowinami. Dlatego uwa¿am za swój obowi¹zek rozprawienie siê z nimi nawet tutaj.}
{556} {} {Tak jest? No to jasne, sk¹d masz w sobie tyle si³y do walki z nimi. Naprawdê mam nadziejê, ¿e uratujesz swój lud z niewoli. Przyjmij te 500 kapsli jako nagrodê. I dziêki. Twoje us³ugi s¹ nieocenione dla miasta.}
{557} {} {Zegnaj, Hrabio Bustos.}
{558} {} {Dobra robota. Przez chwilê najeŸdŸcy bêd¹ os³abieni, a mo¿e nawet zaczn¹ walczyæ miêdzy sob¹.}
{559} {} {Dobra robota. Nawet mi nie szkoda p³aciæ za to wszystko 500 kapsli. I dziêki. Twoje us³ugi s¹ nieocenione dla miasta.}
{560} {} {Nie ma za co, hrabio Bustos.}

{569} {} {Twoje miasto ju¿ cierpi z powodu rabusiów. Ale teraz przynajmniej bêdzie ich mniej.}
{570} {} {Mówi¹, ¿e z³apa³eœ jednego z nich?}
{571} {} {To prawda. Trzymamy go w zamkniêciu. Najpierw musimy wydobyæ od niego wszystkie informacje o gangu, a potem publicznie go stracimy.}
{572} {} {Czy na pewno jest przestepc¹?}
{573} {} {Niektórzy mieszkañcy zidentyfikowali go jako jednego ze zbirów z autostrady. Ja im wierzê. Ponadto posiada³ przy sobie znaki drogowe, których ci czêsto u¿ywaj¹ jako zbroi podczas ataków.}
{574} {} {Có¿, gratulacje, burmistrzu. Czas na mnie.}
{575} {} {Muszê siê z nim zobaczyæ. Mo¿e uda mi siê czegoœ od niego dowiedzieæ.}
{576} {} {Jest na dole, zamkniêty. Powiedz stra¿nikom, ¿eby ciê przepuœcili.}
{577} {} {Masz nie tego faceta. Odpuœæ sobie.}
{578} {} {Powinienem pozwoliæ mu odejœæ, wierz¹c ci na s³owo? Trochê naiwnie z mojej strony, nie s¹dzisz? Ale chcê us³yszeæ twoje argumenty.}
{579} {} {Moim zadaniem jest raportowanie, reszta nale¿y do ciebie.}
{580} {} {Czy moje zeznanie ci nie wystarczy?}
{581} {} {Nie. Ufam moim ludziom, ale nie tobie.}
{582} {} {W takim razie bêdziesz mia³ go na sumieniu. Zegnaj.}
{583} {} {Có¿, pracowaliœmy w tej samej karawanie. Gwarantujê, ¿e nie jest dla Ciebie zagro¿eniem.}
{584} {} {Hmm. Szczerze mówi¹c, ja sam nie wiem, kim on jest i sk¹d pochodzi, a mieszkañcy zawsze widz¹ wroga w ka¿dym nieznajomym. Okej, pozwolê mu odejœæ, ale pod warunkiem, ¿e wydostanie siê z mojego miasta w ci¹gu godziny.}
{585} {} {Dziêkujê panie burmistrzu.}
{586} {} {A mo¿e go wykupiê? Zap³acê 100 kapsli za jego wolnoœæ.}
{587} {} {Brzmi nieŸle. Ale powiedz mu, ¿eby wyjecha³ z miasta w ci¹gu godziny.}
{588} {} {Dziêkujê panie burmistrzu.}
{589} {} {Brzmi dobrze.}
{590} {} {Wkrótce przyniosê kapsle.}
{591} {} {Niebieskie Tarcze proponuj¹ sojusz. Dogadali siê ju¿ nawet z Blacharzami.}
{592} {} {Co? Ci bandyci s¹ teraz chronieni przez Blacharzy? Co za niesprawiedliwoœæ!}
{593} {} {Blacharze uznali ich za pokojow¹, niezale¿n¹ osadê.}
{594} {} {Powinienem by³ dzia³aæ szybciej. Dobrze chocia¿, ¿e gang przez jakiœ czas da nam spokój, nam i karawanom. Ale bandytom nie mo¿na ufaæ. Ponadto wielu z nich chce zemsty na mnie osobiœcie lub na ca³ym Casa Grande.}
{595} {} {Nie masz wyboru. Blacharze nie zaakceptuj¹ odmowy.}
{596} {} {Oczywiœcie. Podpiszê tê umowê. Ale zrobiê wszystko, ¿eby Tarcze drogo za to zap³ci³y.}
{597} {} {Przeka¿ê Benowi twoje s³owa. Do widzenia.}
{598} {} {Bêdê przeklêty, jeœli podpiszê ten sojusz. WyjdŸ i powiedz Benowi, ¿e Blacharze nie ochroni¹ go i jego bandy przed sprawiedliwym os¹dem.}
{599} {} {Przeka¿ê Benowi twoje s³owa. Do widzenia.}