{100} {} {Widzisz ochroniarza.}
{101} {} {Widzisz mê¿czyznê w ekwipunku bojowym. Uwa¿nie ciê obserwuje.}
{102} {} {Hej kawa³ku ¿elaza, wracaj do Blacharzy, nie potrzebujemy ciê tutaj.}

{110} {} {Hrabia nie ma czasu dla takich szumowin jak ty.}
{111} {} {Na co siê gapisz?}
{112} {} {Potrzebujesz czegoœ?}
{113} {} {Nawet nie myœl ¿eby coœ ukraœæ w tym miejscu.}
{114} {} {Wygl¹da na to, ¿e ktoœ szuka k³opotów.}
{115} {} {Musisz byæ zdesperowany, ¿eby tu przychodziæ.}
{116} {} {Szukasz problemów?}

{120} {} {Hrabia Bustos jest u siebie.}
{121} {} {Masz umówion¹ wizytê u burmistrza? Ok, wejdŸ.}
{122} {} {OK, wejdŸ. Ale uwa¿aj, bez kombinowania.}
{123} {} {Nie wa¿ siê zawieœæ hrabiego.}
{124} {} {Mo¿esz iœæ. Ale bêdê mieæ ciê na oku.}

{130} {} {Cholera, muszê teraz znaleŸæ now¹ pracê.}
{131} {} {Miasto bez burmistrza stanie siê niebezpieczniejsze.}
{132} {} {Cholera, hrabia p³aci³ ³adne kapsle. I mieliœmy wodê - œwie¿¹, czyst¹ wodê.}
{133} {} {Chocia¿ Bustos by³ uzurpatorem, regularnie p³aci³ za wykonywan¹ pracê.}
{134} {} {Ok. No to jestes teraz bez pracy.}

{140} {} {Trafi³eœ do z³ego miasta, najeŸdŸco.}
{141} {} {Hej, czy ty nie jesteœ czasem z Niebieskich Tarcz?}
{142} {} {NajeŸdŸcy stali siê ca³kowicie bezczelni, spaceruj¹ ju¿ nawet sobie swobodnie po naszym mieœcie.}
{143} {} {Co? Bandyci zamierzaj¹ negocjowaæ? Co za dziwne czasy...}
