{100} {} {Widzisz ochroniarza.}
{101} {} {Widzisz mê¿czyznê w ekwipunku bojowym. Uwa¿nie ciê obserwuje.}
{102} {} {Hej kawa³ku ¿elaza, wracaj do Blacharzy, nie potrzebujemy ciê tutaj.}
{103} {} {T-ty... czego chcesz? Wynoœ siê st¹d!}

{200} {} {Hrabia i pozostali s¹ teraz w opuszczonym barze. Coœ siê tam dzieje, ale nie wiem co dok³adnie.}
{201} {} {Wiêc jest przy barze. Dziêki, pa.}
{202} {} {To dlaczego ciê tam nie ma?}
{203} {} {Strzegê rezydencji. Nie mo¿na zostawiæ tego luksusu bez opieki.}
{204} {} {No tak. A wiêc do starego baru...}

{210} {} {Burmistrz nie ¿yje. Jest martwy. Rozumiesz? Rozumiesz, co? Tak, to koniec tego miasta!}
{211} {} {Jedna osoba nie sprawi, ¿e ca³e miasto zniknie z powierzchni ziemi. Spokojnie.}
{212} {} {Jestem spokojny. Tak, jestem spokojny. W³aœnie znalaz³em pieprzon¹ normaln¹ pracê. A teraz, z powodu jednego wypadku, jestem z powrotem na ulicy. Bez pracy, bez kapsli i bez domu. Co mam teraz zrobiæ?}
{213} {} {Miasto jest teraz wolne od uzurpatora i tyrana. Nie cieszysz siê?}
{214} {} {Cieszê siê. Tak, oczywiœcie. W koñcu znalaz³em sobie normaln¹ pieprzon¹ pracê. I znowu jestem na ulicy z powodu jednego wypadku. I co mam teraz zrobiæ?}
{215} {} {Rzeczywiœcie. Jakieœ pomys³y?}
{216} {} {Có¿, mo¿esz pracowaæ jako karawaniarz. Dlaczego nie? Jest wiele karawan. Da siê z tego wy¿yæ.}
{217} {} {Jesteœ zagro¿eniem dla spo³eczeñstwa. Musisz zostaæ stracony, natychmiast.}
{218} {} {Uch, nie mogê siê z tob¹ zgodziæ. Mam nadziejê, ¿e znajdziesz pracê. Czeœæ.}
{219} {} {Czego chcesz?}
{220} {} {Chyba nic.}
{221} {} {Twojej œmierci.}

{230} {} {Ach, czeœæ. Hrabia jest w domu.}
{231} {} {Ach, czeœæ. Hrabia w³aœnie ciê szuka³. Chce z tob¹ porozmawiaæ.}
{232} {} {Muszê siê z nim zobaczyæ.}

{250} {} {Uch, czekaj. Gdzie idziesz?}
{251} {} {Zwiedzam miasto.}
{252} {} {To wygl¹da na dosyæ podejrzane, wiesz? Ale tym razem Ci darujê.}
{253} {} {Przepraszam? Co?}
{254} {} {Có¿... S³uchaj, to jest dom hrabiego Bustosa. BARDZO nienawidzi, gdy ktoœ wokó³ w³óczy siê bezczynnie. Rozumiesz? Wiêc wynoœ siê st¹d. Dalej, nie sprawiaj mi k³opotów.}
{255} {} {Ok, do zobaczenia.}
{256} {} {Przy okazji, opowiedz mi o tym miejscu. Kto tu rz¹dzi i czym siê zajmuje?}
{257} {} {Jestem po prostu ciekawy, kto mieszka w tak eleganckiej rezydencji?}
{258} {} {Hrabia Bustos. Jest g³ow¹ miasta.}
{259} {} {Wiêc powinienem siê z nim zobaczyæ. Czy przyjmuje teraz goœci?}
{260} {} {Prawdopodobnie. Ale BARDZO nie lubi, gdy mu siê przeszkadza bez powodu.}
{261} {} {I tak muszê z nim porozmawiaæ. Czeœæ.}
{262} {} {Powiedz mi wiêcej o nim. Mówisz, ¿e jest burmistrzem miasta?}
{263} {} {Dziêki. To wszystko, co chcia³em wiedzieæ.}

{300} {} {Opowiedz mi o hrabim.}
{301} {} {Hrabia Alfred Bustos. Jest burmistrzem miasta i przewodnicz¹cym izby handlowej. Jest tak¿e moim szefem. Co prawda, na razie jestem tylko na okresie próbnym.}
{302} {} {Dlaczego nazywa siê go hrabi¹?}
{303} {} {Có¿, bo on jest hrabi¹. To trochê jak tytu³. Nie wiem, szczerze mówi¹c, co to znaczy. Ale brzmi fajnie.}
{304} {} {Myœlisz, ¿e potrzebuje kolejnego stra¿nika?}
{305} {} {Nie wiem. Porozmawiaj z nim.}
{306} {} {Kim w³aœciwie jesteœ?}
{307} {} {Powiedz mi wiêcej o hrabim Bustosie.}

{310} {} {Kim jesteœ?}
{311} {} {Jestem tylko stra¿nikiem.}
{312} {} {Jesteœ st¹d?}
{313} {} {Nie, pochodzê z ma³ej spo³ecznoœci niedaleko Phoenix. Niestety spo³ecznoœæ ta zosta³a rozbita, wiêc pojecha³em do du¿ego miasta. Tam te¿ siê nie uda³o, wiêc do³¹czy³em do karawany, aby zarabiaæ kapsle. Ale po drodze zosta³em tutaj. Od tego czasu nie widzia³em swojej karawany. Do diab³a, nawet nie zap³acili mi pe³nej kwoty.}
{314} {} {Od tamtej pory jesteœ tu ochroniarzem?}
{315} {} {Nie, tylko kilka miesiêcy. Hrabia potrzebowa³ ludzi, a wœród miejscowych nie by³o ju¿ nikogo, kto by chcia³ tê pracê. Inaczej nawet by na mnie nie spojrza³.}
{316} {} {Zgadza siê. Nikt nie potrzebuje bezu¿ytecznego pracownika.}
{317} {} {Nie jestem bezu¿yteczny! Lepiej idŸ w³asn¹ drog¹, koleœ. W ogóle nie muszê z tob¹ rozmawiaæ.}
{1317} {} {Nie jestem bezu¿yteczny! Lepiej idŸ w³asn¹ drog¹. W ogóle nie muszê siê z tob¹ rozmawiaæ.}
{318} {} {No có¿.}
{319} {} {Muszê iœæ.}
{320} {} {Swoj¹ drog¹, dlaczego te ulice s¹ takie puste?}
{321} {} {Bo to nie jest Phoenix, to ma³e miasteczko. Ale ja te¿ tego nie rozumiem. W koñcu s¹ gorsze miejsca ni¿ to, a do nas dodatkowo przyje¿dzaj¹ karawany i to dosyæ czêsto.}
{322} {} {Ju¿ zaczyna³em myœleæ, ¿e to kolejne miasto duchów. Ok, pójdê ju¿.}
{323} {} {Wiêc jesteœ kolejnym desperatem? Tylko tracê z tob¹ czas.}
{324} {} {Z pewnoœci¹ hrabia wiedzia³, kogo zatrudnia. Muszê siê z nim spotkaæ.}
{325} {} {Co za niesprawiedliwoœæ. Na pewno na to nie zas³ugujesz.}
{326} {} {Dobrze. Mam nadziejê, ¿e zostali po¿arci przez radskorpiony. Teraz przynajmniej pracujê na normalnym stanowisku z normaln¹ pensj¹. Swietnie, prawda?}
{327} {} {Masz po prostu szczêœcie. Nie pochlebiaj sobie.}
{328} {} {No tak. Swoj¹ drog¹, czas bym zobaczy³ siê z twoim pracodawc¹. Czeœæ.}