{100} {} {Widzisz Christinê.}
{101} {} {Widzisz dziewczynê z weso³ym wyrazem twarzy. Wygl¹da na to, ¿e jej ³atwe ¿ycie niczego jej jeszcze nie nauczy³o.}
{102} {} {Widzisz dziewczynê o smutnym spojrzeniu. Wygl¹da na to, ¿e ostatnie wydarzenia da³y jej do myœlenia.}
{103} {} {Wow, chodzisz w tym do ³azienki?}
{104} {} {Tatusiu... Tatusiu...}
{105} {} {Sk¹d TO masz? Ukryj to natychmiast, zanim ktoœ to zobaczy. Ochroniarze taty natychmiast strzelaj¹ do ka¿dego zbira.}
{106} {} {Co siê dzieje? Gdzie jest mój tatuœ?}

{110} {} {Zzz...}
{111} {} {Hrr...}
{112} {} {...Tatusiu, jest za wczeœnie...}
{113} {} {...To nie jest sen...}
{114} {} {Ja... œniê...}
{115} {} {...To...sen...}
{116} {} {Czy wiesz, która jest godzina?}
{117} {} {Chcê spaæ.}
{118} {} {Nie przeszkadzaj mi w spaniu.}
{119} {} {Daj mi spaæ.}

{120} {} {* buczenie *}
{121} {} {Swietny dzieñ na ¿arty.}
{122} {} {Czy powinnam proponowaæ obcemu grê w pokera?}
{123} {} {Muszê poprosiæ tatusia o wiêcej kapsli.}
{124} {} {Niewa¿ne, tatuœ mi wybaczy.}
{125} {} {Och, jakie to nudne...}
{126} {} {Co robisz?}
{127} {} {Woda, kapsle. Kapsle, woda. Czy nie mog¹ wymyœliæ nic innego?}
{128} {} {Chcia³abym móc znowu zobaczyæ nowoczesne Phoenix.}
{129} {} {Zrobi³o siê tu naprawdê nudno bez baru.}

{130} {} {Ach...}
{131} {} {* wzdycha *}
{132} {} {Nie mogê nawet graæ w karty.}
{133} {} {Dlaczego tak jest?}
{134} {} {Straszna historia.}
{135} {} {Nie bêdê mog³a ¿yæ jak wczeœniej.}
{136} {} {Nie rozumiem, jak to wszystko mog³o potoczyæ siê  w ten sposób?}
{137} {} {Dlaczego ludzie s¹ tacy Ÿli?}
{138} {} {}
{139} {} {}

# Znajomosc
{200} {} {Och, czeœæ. Nowe twarze s¹ zawsze tak interesuj¹ce. Mam na imiê Christina. Jak d³ugo tu jesteœ?}
{201} {} {Có¿, ja...}
{202} {} {No weŸ, zostañ, bêdzie fajnie. Chocia¿ miasto jest oczywiœcie nudne. Po prostu umieram bez hazardu.}
{203} {} {Niez³y pomys³, ale muszê porozmawiaæ z burmistrzem.}
{204} {} {Jak zwykle. Dobrze idŸ. Prawdopodobnie jest w swoim biurze. Pamiêtaj, aby zapukaæ przed wejœciem.}
{205} {} {Dobrze.}
{206} {} {Nie mam teraz czasu na gry. Muszê siê rozejrzeæ.}
{207} {} {Ach, co za rozczarowanie. Dobrze idŸ. Mam nadziejê, ¿e zmienisz zdanie. Tylko nie szwêdaj siê po naszym domu bezczynnie. Mój tata tego nie lubi.}
{208} {} {Dobrze.}
{209} {} {Powinien byæ milszy.}

{210} {} {O, czeœæ.}
{211} {} {Do widzenia.}
{212} {} {Chcê ciê zapytaæ o miasto.}
{213} {} {Uch, s³uchaj, nie chcê z tob¹ rozmawiaæ, dobrze? A jeœli bêdziesz nalegaæ, wezwê ochroniarzy.}
{214} {} {SiedŸ tu sobie sama, suko. Teraz jest dla mnie jasne, dlaczego nikt Ciê nie wykorzysta³.}
{215} {} {Dlaczego ca³e miasto jest na mnie takie wœciek³e? Niewa¿ne.}

#Gra
{220} {} {Och, czeœæ. Chcesz zagraæ w karty?}
{221} {} {Zagrajmy. O 10 kapsli.}
{222} {} {Och, czeœæ. Chcesz zagraæ w karty? Nie bawi³am siê z nikim tak d³ugo, ¿e umieram z nudów.}
{223} {} {Przepraszam, ale nie uprawiam hazardu.}
{224} {} {Myœlê, ¿e siê za ³atwo wkurzasz.}
{225} {} {Uch, nie s¹dzê. Czeœæ.}
{226} {} {Grasz tylko dla zabawy?}
{227} {} {Jeszcze czego! Bez zak³adów to gra nie ma sensu. Ale kiedy wiesz, ¿e mo¿esz straciæ coœ cennego - wtedy pojawia siê prawdziwa zabawa.}
{228} {} {Hm, czy naprawdê masz kapsle na zak³ad?}
{229} {} {Oczywiœcie! Mój tata jest g³ow¹ miasta. Nawet jeœli przegram to da mi wiêcej kapsli, ca³y jego sejf jest ich pe³en.}
{230} {} {Przepraszam, ale nie mogê teraz traciæ czasu na granie w gry. Mo¿e nastêpnym razem.}
{231} {} {Co za szkoda. Ok, idŸ i rozwi¹zuj swoje * wa¿ne sprawy *.}
{232} {} {Wiesz, czas bym siê zrelaksowa³. Dodam 10 kapsli.}
{233} {} {Uch, pa.}
{234} {} {Ok, zagrajmy. Zak³adam 10 kapsli.}
{235} {} {Swietnie. Robi siê ciekawie...}
{236} {} {I s³usznie. Pora przestaæ marnowaæ swój kapita³.}
{237} {} {Do zobaczenia ponownie. Tylko siê tu nie zanudŸ.}
{238} {} {Ups. Gdzie s¹ moje kapsle...}
{239} {} {[Rozpocznij grê]}
{240} {} {Hurra! Karta mi sprzyja!}
{241} {} {Co? Nie, chcê odzyskaæ swoje kapsle!}
{242} {} {Zostawie ciê.}
{243} {} {A co z gr¹? Dlaczego tak wczeœnie? Dopiero zaczynamy. Dobrze. I tak siê zaczyna³am nudziæ.}
{244} {} {Do widzenia.}
{245} {} {Co? Przegra³am? O nie, tatuœ mnie zabije... Ale w sumie to tylko 10 kapsli. By³y warte straty byle siê nie nudziæ.}
{246} {} {Chcesz pograæ jeszcze trochê?}
{247} {} {Zostawie ciê.}
{248} {} {Nie, obawiam siê, ¿e tata nie da mi wiêcej kapsli.}
{249} {} {Pf. To takie nudne!}

#Zapytania
{300} {} {Kim jesteœ?}
{301} {} {Christina. Straci³eœ pamiêæ?}
{302} {} {Czy jesteœ córk¹ burmistrza?}
{303} {} {No tak. Czy nie jesteœmy tacy podobni? Spójrz - mamy ten sam nos i oczy.}
{304} {} {Dobrze. Mam wra¿enie, ¿e pilnie potrzebujê spotkania z twoim ojcem. Teraz.}
{305} {} {To super. Na pewno du¿o wiesz o tym mieœcie?}
{306} {} {Co mo¿esz mi powiedzieæ o mieœcie?}
{307} {} {Tylko to, ¿e jest tu œmiertelnie nudno. Chocia¿ s¹ pory roku, kiedy do miasta przybywaj¹ karawany. Wtedy dzieje siê tu wiele interesuj¹cych rzeczy.}
{308} {} {Ciekawe. Ale kim ty w³aœciwie jesteœ?}
{309} {} {Chyba nie jesteœ w stanie mi jednak pomóc. Poszukam kogoœ innyego.}
{310} {} {Dlaczego macie taki du¿y cmentarz na wschodzie?}
{311} {} {Dlaczego nie? Przecie¿ ludzie umieraj¹, trzeba ich gdzieœ pochowaæ. Czy w innych miejscach tak nie jest?}
{312} {} {Ale nie ma tam a¿ tak du¿ych cmentarzy.}
{313} {} {Nie wiem. Mieszkam tu przez ca³e ¿ycie, a w Phoenix by³am tylko raz.}
{314} {} {Muszê iœæ.}

{320} {} {Czeœæ. Jak siê masz?}
{321} {} {Chcia³em zobaczyæ, jak siê masz. Widzê, ¿e dobrze. Czeœæ.}
{322} {} {Chcesz graæ w karty?}
{323} {} {Nie, ju¿ nie gram w karty. I ¿adnych wiêcej gier.}
{324} {} {Rozumiem. Pa.}
{325} {} {Wiêc czego chcieli od ciebie ci rabusie?}
{326} {} {Zemsty na moim ojcu za przesz³e okrucieñstwa. Nie wiedzia³am, jakie okropnoœci zrobi³ wczeœniej w tym mieœcie.}
{327} {} {Rozumiem. Nie traæ nadziei.}

{330} {} {Ach, to ty... Zabili mojego tatê, wiesz?}
{331} {} {Tak, widzia³em to na w³asne oczy. Jak siê masz?}
{1331} {} {Tak, widzia³am to na w³asne oczy. Jak siê masz?}
{332} {} {Nic mi nie jest. Serio. Kiedy by³am zak³adnikiem, bandyci rozmawiali o moim ojcu. Powiedzieli, ¿e przej¹³ w³adzê od ostatniego burmistrza, ¿e bezlitoœnie eksterminowa³ po³owê mieszkañców, którzy sprzeciwiali siê jego w³adzy. By³am za m³oda, ¿eby pamietaæ te dni. Czy to naprawdê prawda?}
{333} {} {Przestañ byæ naiwnym g³upcem, otwórz oczy - ka¿da w³adza pos³uguje siê przemoc¹. Twój tatuœ to tylko przyk³ad.}
{334} {} {Rozumiem... móg³ byæ tyranem i pope³ni³ straszne okrucieñstwa. Ale dla mnie by³ kochaj¹cym tat¹. Zawsze znosi³ moje zachcianki i dawa³ mi to, co najlepsze. Jak to siê mog³o staæ?}
{335} {} {Witaj w rzeczywistoœci, kochanie. Tak teraz dzi³a ten œwiat.}
{336} {} {Tak. Teraz rozumiem. Zrobiê wszystko, aby to siê wiêcej nie powtórzy³o.}
{337} {} {Jak sobie chcesz. Moje sprawy w tym mieœcie dobieg³y koñca. Czas ruszaæ w drogê.}
{338} {} {Na to wygl¹da. Przykro mi.}
{339} {} {Przynajmniej ciê kocha³. Wiêc w g³êbi duszy nie by³ takim tyranem.}
{340} {} {Czekaj. Prawdopodobnie potrzebujesz kapsli na podró¿. Proszê, weŸ to. Tobie przydadz¹ siê bardziej ni¿ mi.}
{341} {} {Dziêki. I ¿egnaj.}
{342} {} {Czekaj. Prawdopodobnie potrzebujesz kapsli na podró¿. Proszê, weŸ to. S¹ tu te¿ te przegrane w karty. Tobie przydadz¹ siê bardziej ni¿ mi.}
{1342} {} {Czekaj. Prawdopodobnie potrzebujesz kapsli na podró¿. Proszê, weŸ to. S¹ tu te¿ te przegrane w karty. Tobie przydadz¹ siê bardziej ni¿ mi.}
{343} {} {Powodzenia. Muszê wyruszyæ w d³ug¹ podró¿.}
{344} {} {Do widzenia, nieznajomy.}
{345} {} {Do widzenia.}
{346} {} {Ach, to ty... Jestem Ci na wieki wdziêczna za twoj¹ pomoc.}
{347} {} {Wiêc dlaczego wydajesz siê byæ taka smutna?}
{348} {} {Hej, gdzie siê podzia³a ta naiwna dziewczyna lubi¹ca hazard?}
{349} {} {Przynajmniej ciê kocha. Tak wiêc w g³êbi duszy nie jest takim tyranem.}