{100} {} {Widzisz Rangersa.}
{101} {} {Widzisz mê¿czyznê w skórzanej zbroi.}
{102} {} {Nie mamy o czym rozmawiaæ.}

{200} {} {No có¿. Wygl¹da na to, ¿e mamy tu wichrzyciela porz¹dku publicznego. }
{201} {} {Ups...}
{202} {} {Co tu robisz, g³upcze?}
{1202} {} {Co pani robi na cmentarzu?}
{203} {} {To nie twoja sprawa. Nic Ci nie powiem.}
{204} {} {Przepraszam. Szkoda, ¿e ludzie tacy jak ty przeszkadzaj¹ normalnym ludziom w ¿yciu.}
{205} {} {[Dalej.]}
{206} {} {(wyci¹ga broñ) Z upowa¿nienia nadanego mi przez Departament Stra¿ników Arizony i Konstytucji skazujê ciê... na œmieræ. Wyrok zostanie wykonany natychmiastowo.}
{207} {} {Co...}
{208} {} {IdŸ do diab³a.}
{209} {} {Czekaj! Przys³ali mnie Blacharze. Szukaj¹ swojego towarzysza, to ten co le¿y w tym grobie.}

{210} {} {Szukam kosztownoœci, sir.}
{211} {} {Kosztownoœci w grobie? Czy kiedykolwiek przysz³o Ci do g³owy, ¿e jest niew³aœciwym okradanie umar³ych?}
{212} {} {Nie obchodzi mnie to. I co teraz? Spróbujesz mnie powstrzymaæ?}
{213} {} {Umarli nie maj¹ z tym nic wspólnego.}
{214} {} {Mo¿e tak. Ale to nie Ty decydujesz. I w mojej mocy mogê ciê ukaraæ za takie przestêpstwo.}
{215} {} {Kim jesteœ?}
{216} {} {Tak, proszê pana. Przyznajê siê do winy, sir.}
{217} {} {Te sztuczki na mnie nie zadzia³aj¹, kolego. Mam oko do ludzi takich jak Ty.}
{1217} {} {Te sztuczki na mnie nie zadzia³aj¹, panienko. Mam oko do ludzi takich jak Ty.}
{218} {} {Kim jesteœ?}
{219} {} {O nie, rodzina tego cz³owieka nie mia³aby nic przeciwko. A wiesz dlaczego?}

{220} {} {Jestem Stra¿nikiem. A ty kim jesteœ? Dlaczego przyje¿dzasz do tego miasta i zachowujesz siê, jakbyœ móg³ wszystko?}
{221} {} {Blacharze szukaj¹ swojego towarzysza. Zosta³ zabity. Wygl¹da na to, ¿e coœ o tym wiesz.}
{222} {} {Kim w³aœciwie jesteœ?}
{223} {} {Nie twoja sprawa.}

{230} {} {O nie, nie, Ÿle mnie zrozumia³eœ, zaraz wszystko wyjaœniê.}
{231} {} {Ok, uwa¿nie s³ucham.}
{232} {} {Widzisz, szukam... [WeŸ broñ i zaatakuj]}
{233} {} {To nie twoja sprawa. Nic Ci nie powiem.}
{234} {} {Blacharze pytali o kogoœ. Szukaj¹ swojego brata. Jest w tym mieœcie.}

{240} {} {Wiem. Zabi³em go.}
{241} {} {Ale dlaczego? Coœ ci zrobi³?}
{242} {} {Szumowiny takie jak Blacharze powinny le¿eæ 5 metrów pod ziemi¹. Uwa¿aj¹ siê za Bogów, jakby wszystko im by³o wolno. Uciskaj¹ mieszkañców, odbieraj¹ im najnowsze technologie i zmuszaj¹ do pracy. Ich autorytet podwa¿a jak¹kolwiek nadziejê na sprawiedliwoœæ na ziemiach po³udniowej Arizony. A samo ich istnienie, po³¹czone (pogardliwie) z technologi¹, jest nieludzkie. Jeœli chodzi o mnie, to wystarczy.}
{243} {} {[Dalej.]}
{244} {} {Co przywiod³o ciê do Blacharzy? Przekupili ciê kapslami jak innych?}
{245} {} {Mo¿e tak. Jestem zwyk³ym najemnikiem, nie obchodzi mnie twoja Arizona i sprawiedliwoœæ.}
{1245} {} {Mo¿e tak. Jestem zwyk³ym najemnikiem, nie obchodzi mnie twoja Arizona i sprawiedliwoœæ.}
{246} {} {Có¿. Praca dla wrogów pustkowi oznacza, ¿e sam jesteœ wrogiem.}
{1246} {} {Có¿. Praca dla wrogów pustkowi oznacza, ¿e sam jesteœ wrogiem.}
{247} {} {[Dalej.]}
{248} {} {Nie. Przepraszam.}
{249} {} {O cholera...}
{250} {} {Ok, przyzna³eœ siê. Podaj mi powód, dla którego powinieneœ pozostaæ przy ¿yciu.}
{251} {} {(wyci¹gasz broñ) Mam kilka powodów, g³upcze. S³uchaj uwa¿nie...}
{1251} {} {(wyci¹gasz broñ) Mam kilka powodów, g³upcze. S³uchaj uwa¿nie...}
{252} {} {O cholera...}
{253} {} {Och, nie...}
{254} {} {Ja te¿ jestem Stra¿nikiem. Ale mam inn¹ misjê. Rozkazano mi infiltrowaæ szeregi Blacharzy, aby znaleŸæ ich s³aboœci.}
{255} {} {Hmm. Co za niespodziewane spotkanie, kompanie. Cieszê siê, ¿e ciê widzê. Có¿, nie mam wiêcej pytañ. Ustalmy, ¿e to spotkanie nie mia³o miejsca, ok?}
{256} {} {Oczywiœcie. Nikt nic nie widzia³.}
{257} {} {Pozwól mi zabraæ szcz¹tki. Blacharze zas³uguj¹ chocia¿ na tyle.}
{258} {} {Nie mogê pozwoliæ ci dalej pracowaæ dla tych drani.}
{259} {} {[Dalej.]}
{260} {} {Mo¿esz ich nienawidziæ. Ale jako cz³owiek musisz mieæ jakieœ zasady. Pozwól, ¿e zabiorê te szcz¹tki.}
{261} {} {Hmm. Te s³owa sprawiaj¹... Dobra, odwal swoj¹ brudn¹ robotê, najemniku. I powiedz Blacharzom, ¿eby lepiej ogl¹dali siê za siebie.}
{1261} {} {Hmm. Te s³owa sprawiaj¹... Dobra, odwal swoj¹ brudn¹ robotê, najemniku. I powiedz Blacharzom, ¿eby lepiej ogl¹dali siê za siebie.}
{262} {} {Uh, oczywiœcie proszê pana. Bêdzie jak pan powiedzia³, sir.}
{263} {} {Dobra, po prostu mnie zostaw.}
{264} {} {Sir, nic do pana nie mam. Tylko wype³niam kontrakt.}
{265} {} {(szyderczo) Ok, odwal swoj¹ brudn¹ robotê, najemniku. I powiedz Blacharzom, ¿eby lepiej ogl¹dali siê za siebie.}
{1265} {} {(szyderczo) Ok, odwal swoj¹ brudn¹ robotê, najemniku. I powiedz Blacharzom, ¿eby lepiej ogl¹dali siê za siebie.}
{266} {} {Ja tylko wype³niam kontrakt. Czy to jakiœ problem?}