{100} {} {Widzisz faceta.}
{101} {} {Widzisz opalonego mê¿czyznê w pancerzu.}
{102} {} {IdŸ swoj¹ drog¹.}

{200} {} {Hej, ty. Co Ty tutaj robisz?}
{201} {} {Zwiedzam okolicê. Jakieœ problemy?}
{202} {} {Tak. Problemy. Przez Ciebie. Jesteœ na naszej ziemi i grzebiesz w naszym magazynie.}
{203} {} {A sk¹d mia³em to wiedzieæ? Powinieneœ wywiesiæ jakieœ ostrze¿enie.}
{204} {} {Serio jesteœ takim kretynem? Nie potrafiê pisaœ... Czekaj, ¿artujesz sobie ze mnie, co? Nie ujdzie ci to p³azem.}

{210} {} {To nie twoja sprawa.}
{211} {} {Nie, to mój magazyn, mój teren, wiêc i moja sprawa.}
{212} {} {Naprawdê? Powinieneœ by³ umieœciæ tabliczkê na drzwiach.}
{213} {} {Nie masz szczêœcia stary.}
{214} {} {Musisz odejœæ. Nie potrzebujemy tu przyb³êd.}
{215} {} {Spokojnie...}
{216} {} {Masz chyba problemy ze wzrokiem. I jedziesz, jakbyœ siê nie my³ od lat.}

{220} {} {Wygl¹da na to, ¿e ty i ja jesteœmy z tego samego klanu. Nie ma sensu walczyæ, bracie.}
{221} {} {Jesteœ z cytadeli? Dawno tam nie by³em. Jakieœ nowiny?}
{222} {} {Wszystko dobrze. Klan jest chroniony, udowodniliœmy, ¿e mamy prawo do niepodleg³oœci.}
{223} {} {Tak, s³ysza³em. Powinienem tam zajrzeæ. Powodzenia bracie. Niech kurz zakryje Twoje œlady na drodze.}
{1223} {} {Tak, s³ysza³em. Powinienem tam zajrzeæ. Mi³ej podró¿y, siostro. Niech kurz zakryje Twoje œlady na drodze.}
{224} {} {Mi³ej podró¿y, nawzajem.}

{230} {} {Jestem zwyk³ym zbieraczem. Nie zabijaj mnie, dobry cz³owieku.}
{231} {} {Wiêc jesteœ miejscowy? Prawdopodobnie powoli ³apiesz. Wszyscy wiedz¹, ¿e nie nale¿y przechodziæ przez nasz¹ ulicê. Wypad. Jeszcze raz ciê tu zobaczê - i nie ¿yjesz.}
{232} {} {Cokolwiek pan powie...}
{233} {} {Tylko siê rozgl¹dam. Co w tym z³ego?}
{234} {} {Fakt, ¿e nam siê to nie podoba. Jesteœ na naszym terytorium. Bêdziemy musieli ciê wykoñczyæ, aby unikn¹æ niepotrzebnych plotek.}
{235} {} {Waszym? Jasne...}
