{100} {} {Widzisz handlarza wod¹.}
{101} {} {Widzisz niezwykle czyst¹ osobê.}
{102} {} {Jesteœ od Blacharzy? Nie strasz mi ludzi t¹ puszk¹.}
{103} {} {Bandyci nie maj¹ czego szukaæ w tym mieœcie. Wynoœ siê, zanim ciê zastrzelê.}
{104} {} {Oto zap³ata za twoj¹ chciwoœæ, suko.}
{105} {} {Pamiêtasz moje s³owa? Oto zap³ata za twoj¹ chciwoœæ.}
{106} {} {Asortyment sprzedawcy wody zosta³ dla ciebie rozszerzony.}
{107} {} {Nie mogê rozmawiaæ z dwoma jednoczeœnie.}

# Pierwszy dialog
{200} {} {(mru¿y siê na ciebie, pocieraj¹c rêce o rêcznik) Nie pamiêtam ciê. Nowy w mieœcie?}
{201} {} {Tak, jestem . Co to za miejsce?}
{202} {} {Nie, urodzi³em i wychowa³em siê tu. Rozumiesz?}
{1202} {} {Nie, urodzi³am i wychowa³am siê tu. Rozumiesz?}
{203} {} {Rozumiem. Ale pamiêtaj, ¿e nie lubi¹ tutaj ¿artownisiów. To nie jest dobry czas na ¿arty.}
{204} {} {Och, przepraszam. To by³o g³upie z mojej strony. Co to za miejsce?}
{205} {} {Spokojnie, stary. Swoj¹ drog¹, gdzie siê znalaz³em?}
{1205} {} {Spokojnie, stary. Swoj¹ drog¹, gdzie siê znalaz³am?}
{206} {} {To jest stacja wodna. Wydobywamy wodê z ziemi i sprzedajemy potrzebuj¹cym. A to jest punkt sprzeda¿y. Potrzebujesz wody?}
{207} {} {Nie, szukam czegoœ innego.}
{208} {} {Jestem zbyt zajêty. Nie zawracaj mi g³owy.}
{209} {} {Ugh, jaki nieprzyjazny...}
{210} {} {Tak, pilnie potrzebujê wody.}
{211} {} {Oczywiœcie. Ka¿dy potrzebuje wody. Ale jeœli chcesz piæ, zap³aæ. Nie ma tu nic za darmo.}
{212} {} {Rozumiem. Wpadnê, kiedy bêdê musia³ uzupe³niæ zapasy. Czeœæ.}
{213} {} {Proszê, daj trochê wody zmêczonemu Stra¿nikowi. Zrobisz dobry uczynek.}
{214} {} {(marszcz¹c brwi) Stra¿nik... Nie pamiêtam, co Stra¿nicy dla nas zrobili. Ale ludzie z karawany ostatnio du¿o o tobie mówi¹.}
{215} {} {[Dalej.]}
{216} {} {Ok. Mam dla ciebie trochê wody. Ale nie proœ o wiêcej. Mamy tu punkt sprzeda¿y, a nie dzia³alnoœæ charytatywn¹.}
{217} {} {Dziêkujê uprzejmie.}
{218} {} {Woda! Woda! Umieram z pragnienia...}
{219} {} {I spodziewasz siê, ¿e to kupiê?}
{220} {} {Zapamiêtam ten dzieñ. I pewnego razu s³ono zap³acisz za swoj¹ chciwoœæ.}
{221} {} {Wynoœ siê st¹d.}
{222} {} {[wyjdŸ]}
{223} {} {Warto by³o spróbowaæ. Do zobaczenia.}
{224} {} {Odmówisz Stra¿nikowi kubka wody? Nie proszê o wiele.}
{225} {} {Woda! Woda! Umieram z pragnienia...}
{226} {} {Mój Bo¿e, ile mil musia³eœ przejœæ pod s³oñcem? Dobra, weŸ trochê wody. Tylko nie umieraj na mojej pod³odze.}
{227} {} {Dziêkujê bardzo...}
{1227} {} {Dziêkujê bardzo...}

{230} {} {Hej, nie tak szybko. Poka¿ mi swoj¹ szyjê. ChodŸ, poka¿ j¹.}
{231} {} {O co Ci chodzi?}
{232} {} {Przepraszam za to. Ale po upadku Blacharzy wielu niewolników uciek³o z Tu-San. Nie mo¿na spodziewaæ siê po nich niczego dobrego. Chcê siê tylko upewniæ, ¿e rozmawiam z przyzwoit¹ osob¹.}
{233} {} {Masz z³e maniery.}
{234} {} {Nie chcê tu ¿adnych konfliktów.}
{235} {} {Ok, brak œladów po ko³nierzu. To dobrze... dla nas obojga.}
{236} {} {Dok³adnie. W innych okolicznosciach drogo by ciê to kosztowa³o.}
{237} {} {No nic, rozumiem. Wszystko w porz¹dku.}
{238} {} {Nie zamierzam z tob¹ ¿artowaæ.}
{239} {} {Hej, mo¿e po prostu siê rozejdŸmy, dobrze? Pomyœl, ¿e mnie tu nie ma...}
{240} {} {No có¿, oto nasz zbieg³y wiêzieñ. Co mam z tob¹ zrobiæ?}
{241} {} {Chyba nic. Mam po prostu wyjœæ?}
{242} {} {Tak. WyjdŸ. WyjdŸ z miasta i nie wracaj.}
{243} {} {[wyjdŸ]}
{244} {} {Kim jesteœ, ¿eby mi to mówiæ? Nie wtykaj nosa w nieswoje sprawy.}
{245} {} {No có¿. Oto nasz zbieg³y wiêzieñ. Chcesz zrujnowaæ moj¹ reputacjê, œmieciu?}
{246} {} {Coœ jeszcze? Chcê od razu Ciê ostrzec - podnieœliœmy ceny wody.}
{247} {} {Dlaczego?}
{248} {} {Musimy siê ratowaæ. Nie ma ju¿ Blacharzy, a wraz z nimi ca³a trasa karawan kurczy siê. Musimy zaopatrzyæ siê w kapsle, w przeciwnym razie d³ugo tu nie poci¹gniemy.}
{249} {} {Rozumiem.}

# Powtarzajacy siê dialog
{250} {} {Potrzebujesz wody?}
{251} {} {Do widzenia.}
{252} {} {Tak, oczywiœcie.}
{253} {} {Wiesz, chcê tylko uzupe³niæ zapasy wody.}
{254} {} {Tak, muszê uzupe³niæ zapasy wody.}
{255} {} {Dziêki. U¿ywaj tej wody m¹drze.}
{256} {} {Do widzenia.}

{257} {} {Nie, potrzebujê odpowiedzi na pytania.}
{258} {} {S³uchaj, nie odpowiem na ¿adne twoje pytanie. Sprzedajê tylko wodê. Jeœli potrzebujesz odpowiedzi, porozmawiaj z moim szefem lub kimœ innym.}
{259} {} {OK. Czeœæ.}
{260} {} {Scigam konwój niewolników...}
{261} {} {Czekaj, szukam takiego Blacharza...}
{262} {} {Nic nie wiem. Potrzebujesz wody czy nie?}
{263} {} {Nie.}
{264} {} {Kto jest w³aœcicielem tego interesu?}
{265} {} {John Sullivan. Jest teraz w pomieszczeniu z generatorem i bawi siê z kolejn¹ awari¹.}
{266} {} {Rozumiem.}
{267} {} {Jak sobie radzisz bez szefa?}
{268} {} {Teraz zajmujê siê tu wszystkim za niego. W pewnym sensie wyœwiadczy³ mi przys³ugê „rezygnuj¹c” ze swojego stanowiska.}
{269} {} {Rozumiem.}

{270} {} {Dziêki za pomoc z tym wariatem. Zas³ugiwa³ na taki los od dawna. Jednoczeœnie pos³u¿y jako przyk³ad dla innych.}
{271} {} {Nie ma za co.}
{272} {} {To nie by³a ³atwa sytuacja.}
{273} {} {Masz, weŸ trochê czystej wody.}
{274} {} {OK, rozumiem.}
{1274} {} {OK, rozumiem ciê.}
{275} {} {Nie przejmuj siê tym szalonym facetem. Zas³ugiwa³ na taki los od dawna. Jednoczeœnie pos³u¿y jako przyk³ad dla innych.}
{276} {} {Tak, masz tutaj prawie zak³ad dla ob³¹kanych.}
{277} {} {Nawet nie wiem, co o tym myœleæ.}
{278} {} {Uwa¿aj na siebie. I nie rozpowiadaj tej historii, jeœli nie chcesz problemów.}
{279} {} {Dziêkujê za pomoc z tym szaleñcem. Ju¿ mi siê wydawa³o, ¿e jest gotów rzuciæ siê na mnie. Proszê, weŸ trochê wody. I nie rozpowiadaj tej historii.}
{280} {} {Dlaczego ten typ ciê zaatakowa³?}
{281} {} {Zaufaj mi, wolisz nie wiedzieæ. W przesz³oœci na stacji toczy³y siê walki miêdzy ró¿nymi klanami. A ten g³upiec uwa¿a³, ¿e nale¿y dzieliæ siê wod¹.}
{282} {} {W¹tpiê, ¿eby to by³ jedyny powód.}
{283} {} {Masz racjê. Ktoœ z jego bliskich zgin¹³ w tych walkach... Ale jak powiedzia³em, to nie twoja sprawa. I nawet nie moja. To ju¿ przesz³oœæ.}
{284} {} {Ta przesz³oœæ prawie odebra³a ci ¿ycie. Zostawiê ciê teraz z t¹ myœl¹.}
{285} {} {Rzeczywiœcie, nie ma sensu wywo³ywaæ czyichœ b³êdów z przesz³oœci. Czas zmierzyæ siê z nasz¹ przysz³oœci¹. Do zobaczenia.}

#Obrot handlowy
{300} {} {Potrzebujê naprawdê du¿ej dostawy wody.}
{301} {} {Nie handlujemy du¿ymi iloœciami z byle kim.}
{302} {} {W takim razie zapomnij.}
{303} {} {Co to za œmieszna zasada?}
{304} {} {Musimy oszczêdzaæ wodê dla innych zwyk³ych kupuj¹cych. Zw³aszcza podczas tak gor¹cego sezonu.}
{305} {} {Prowadzê w³asny biznes. Czy teraz dodasz mnie do listy zaufanych partnerów?}
{306} {} {Co to u diab³a za "biznes" przypadkowej osoby? Te kilka butelek oczywiœcie Ci wystarczy.}
{307} {} {Co to za g³upia zasada?}
{308} {} {Ok, teraz w ogóle nic nie kupiê. Z zasady. Czeœæ.}
{309} {} {Ok, ok, wiesz lepiej.}
{310} {} {Szukam nowych kontaktów handlowych. Mogê dostaæ trochê wody na próbê?}
{311} {} {Hmm. W porz¹dku. Chyba nic siê stanie.}
{312} {} {Nie po¿a³ujesz, partnerze.}
{313} {} {O ciemnoœci rozszczepienia j¹dra atomowego! Nie odmówisz chyba proœbie duchownego, prawda?}
{314} {} {Och, wiêc jesteœ z tego koœcio³a? Twoi ludzie dobrze p³ac¹ za kontrakty. Niech wiêc tak bêdzie, za³ó¿my, ¿e ty równie¿ znajdujesz siê na liœcie zaufanych osób.}
{315} {} {Dziêkujê uprzejmie.}
{316} {} {No dalej, kolego. Przecie¿ tutaj ka¿dy jest swój, tak? Po co te formalnoœci?}
{317} {} {Nie znam ciê zbyt dobrze.}
{318} {} {W takim razie czas porozmawiaæ z miejscow¹ ludnoœci¹.}
{319} {} {Hehe, oczywiœcie. Dla pana wszystko, proszê pana.}
{1319} {} {Hehe, oczywiœcie. Dla pani wszystko, proszê pani.}
{320} {} {Dziêkujê uprzejmie.}
{321} {} {Sprzedajesz wodê Tu-San. Panu Hard nie spodoba siê taki stosunek do mnie.}
{322} {} {Czy to o tobie mówi¹ ludzie z karawany? Jedyny nieznajomy, który zapuœci³ korzenie wœród Blacharzy. Tak, warto siê z tob¹ dogadaæ.}
{323} {} {Nie po¿a³ujesz tego, partnerze.}
{324} {} {Uda³o mi siê naprawiæ usterkê w przepompowni. Czy nie zas³ugujê na lepsze traktowanie?}
{325} {} {Wiêc to twoja zas³uga? Dobra robota. To wszystko zmienia.}
{326} {} {Chyba nic na to nie poradzê. Daj tyle, ile mo¿esz.}

{330} {} {Hej, czeœæ. Podobno zabi³eœ przywódcê bandytów. To prawda?}
{1330} {} {Hej, czeœæ. Podobno zabi³aœ przywódcê bandytów. To prawda?}
{331} {} {Hej, czeœæ. Podobno uda³o ci siê wysadziæ zbiorniki w bazie bandytów. To prawda?}
{332} {} {Tak, to prawda.}
{333} {} {Tak. Jakiœ problem?}
{334} {} {Cholera, jesteœ teraz naszym bohaterem. Dziêkujê Ci. Jeœli potrzebujesz czystej wody, mo¿esz liczyæ na ³adny rabat.}
{1334} {} {Cholera, jesteœ teraz nasz¹ bohaterk¹. Dziêkujê Ci. Jeœli potrzebujesz czystej wody, mo¿esz liczyæ na ³adny rabat.}
{335} {} {Dziêkujê, to bardzo mi³o z twojej strony.}
{336} {} {Od tego powinniœmy byli zacz¹æ.}
{337} {} {Sprzedawca wody obni¿y³ dla ciebie ceny o po³owê.}