{100} {} {Widzisz lokalnego mieszkañca.}
{101} {} {Widzisz wychudzonego osadnika. Wygl¹da doœæ nieprzyjaŸnie.}

{110} {} {Nie obchodzisz mnie.}
{111} {} {Dosta³ to, na co zas³u¿y³.}
{112} {} {* Ignoruje Ciê *}
{113} {} {Cholera.}
{114} {} {Przepraszam. Nie wiem, co mn¹ kierowa³o.}

{120} {} {Znowu ty? Powiedzia³em - nie ma wody bez...}
{121} {} {Zamknij siê. Zabra³eœ ca³¹ wodê mieszkañcom.}
{122} {} {O czym ty mówisz?}
{123} {} {Daj mi trochê wody. Natychmiast.}
{124} {} {Wynoœ siê z mojego hangaru!}
{125} {} {Ty draniu, rozwalê ci za to ³eb!}
{126} {} {Hej, co ty robisz? Zabierz to idioto!}
{127} {} {. ... .}
{128} {} {}

{200} {} {Przysiêgam, ¿e rozwalê g³owê temu grubasowi, jeœli nie da mi wody!}
{201} {} {Nie zrobisz tego, prawda?}
{202} {} {Nie wtr¹caj siê, obcy. Nie masz pojêcia, ile krwi przelano ze wzglêdu na tê przepompowniê. Zabrali j¹ prostym ludziom! A teraz ¿¹daj¹ od nas zap³aty. To jest nasza woda! Daj mi trochê wody, skurwysynu!}
{203} {} {Nie obchodzi mnie to. Rób co chcesz.}
{204} {} {Przestañ kurwa machaæ tu tym m³otem. IdŸ st¹d.}
{205} {} {Spokojnie, trochê wody nie jest warte ofiar.}
{206} {} {Ofiar? Co Ty wiesz o ofiarach? T³umy ludzi zginê³y przez tê przeklêt¹ wodê. Nie mam nic do stracenia. Po¿egnaj siê z ¿yciem, draniu!}
{207} {} {Oddaj mi m³ot. Natychmiast.}
{208} {} {Dobrze. Skop mu dupê.}
{209} {} {Uspokój siê, kolego, trochê wody nie jest warte ofiar.}
{210} {} {Ofiar? Co Ty wiesz o ofiarach? T³umy ludzi zginê³y przez tê przeklêt¹ wodê. Nie mam nic do stracenia...}
{211} {} {Ok, skoro tak mówisz. Dawaj, skop mu dupê.}
{212} {} {To wszystko to przesz³oœæ. Zadne nowe ofiary tego nie zmieni¹, ani nie naprawi¹.}
{213} {} {(rozgl¹da siê zmieszany, a potem patrzy na swój m³ot kowalski) Bo¿e... Wygl¹da na to, ¿e ca³kowicie straci³em g³owê. Muszê... muszê zebraæ myœli.}
{214} {} {Zgadza siê.}
