{100} {} {Widzisz Johnego Sullivana.}
{101} {} {Widzisz kogoœ, kto wzbudza szacunek. Wygl¹da na bardzo czystego i zadbanego.}
{102} {} {Nie zamierzasz chyba b³³kaæ siê tu w tym, prawda?}
{103} {} {Masz doœæ ¿ycia? Wynoœ siê z miasta, cholerny bandyto.}

# Przed naprawa
{200} {} {Hej, nieznajomy. Nie podoba mi siê, gdy na moim terytorium pokazuj¹ siê obce osoby z zewn¹trz.}
{1200} {} {Co za niespodzianka, ¿e spotykam tu kobietê. Chocia¿ zwykle nie lubiê, gdy ktoœ z zewn¹trz wêdruje po moim terytorium.}
{201} {} {Czy to twoja przepompownia? Jesteœ jej w³aœcicielem?}
{202} {} {Dok³adnie. Jestem John Sullivan. Jestem w³aœcicielem ca³ej tej stacji. Masz jakiœ interes? Jeœli nie, wyjdŸ na zewn¹trz. Muszê naprawiæ ten filtr, nie mam czasu na rozmowê z nieznajomymi.}
{203} {} {Przepraszam, ¿e przeszkadzam. Ju¿ wychodzê.}
{204} {} {Jestem tu od niedawna. Czy mogê zadaæ kilka pytañ dotycz¹cych miasta?}
{205} {} {Czy ja mówiê niewyraŸnie? NIE MAM czasu.}
{206} {} {Och, w takim razie natychmiast zostawiê ciê samego.}
{207} {} {Z kim mogê porozmawiaæ o mieœcie?}
{208} {} {Ze starym Bustosem, ma posiad³oœæ przy drodze.}
{209} {} {Dziêki. PA.}
{210} {} {Dlaczego nie mo¿esz tego naprawiæ?}
{211} {} {Czy naprawdê nie ma nikogo innego, kto móg³by to naprawiæ?}
{212} {} {Blacharze chc¹ fortuny za jak¹kolwiek przys³ugê. Wiedz¹, ¿e woda to dochodowy biznes, ale nie mo¿emy oddaæ im wszystkiego. Ale poza Blacharzami nikt nie wie jak sobie poradziæ z tym wszystkim. Tylko oni maj¹ dzia³aj¹ce maszyny i niezbêdne umiejêtnoœci.}
{213} {} {Och, przepraszam, ju¿ siê nie wtr¹cam.}
{214} {} {I masz nadziejê, ¿e sam to naprawisz?}
{215} {} {Czasami dzia³a. Patrz, to jeden z filtrów, w³aœnie zosta³ zatkany brudem... Albo nie.}
{216} {} {Mogê to naprawiæ.}
{217} {} {Naprawdê? Jeœli naprawisz filtr, zap³acê. Oczywiœcie mniej ni¿ Blacharzom. Ale wszyscy na tym skorzystaj¹.}
{218} {} {Poczekaj chwilê. To zajmie trochê czasu.}
{219} {} {Hmm, to dla mnie zbyt skomplikowana technologia. Obawiam siê, ¿e nie mogê tego naprawiæ.}
{220} {} {Znowu ty? O co chodzi tym razem?}
{221} {} {Nie, nic.}
{222} {} {O pompê. Dlaczego jej nie naprawiæ?}
{223} {} {Filtr jest w porz¹dku. Brud i piasek zniszczy³y niektóre czêœci, ale uda³o mi siê je przywróciæ do dzia³ania.}
{224} {} {Uwielbiam jak ktoœ odwala za mnie robotê i robi to dobrze. Masz, 200 kapsli.}
{225} {} {Dziêki.}
{226} {} {To za ma³o.}
{227} {} {W sam raz. Za wiêksz¹ sumê w ogóle nie zaoferowa³bym ci tej pracy.}
{228} {} {Ale z ciebie zrzêda.}
{229} {} {Mimo wszystko dziêki.}
{230} {} {Ta kwota ledwo pokrywa koszt dodatkowych czêœci.}
{231} {} {Wiêc masz tutaj jeszcze 50 kapsli. I ani kapsla wiêcej.}
{232} {} {Ale z ciebie zrzêda.}
{233} {} {Wystarczy, dziêki.}

{234} {} {Szukam Blacharza. By³ tutaj?}
{235} {} {Tak, by³. Po cichu obejrza³ stacjê, omówi³ drobne naprawy i uda³ siê do burmistrza. Od tamtej pory go nie widzia³em.}
{236} {} {Dziêki, pójdê zapytaæ burmistrza.}
{237} {} {W³aœciwie to œcigam konwój niewolników. Zabrano ich do Tu-San.}
{238} {} {Có¿, to jedŸ do Tu-San? Po co mi to mówisz? Nasza mieœcina jest ma³a - obs³ugujemy karawany i pozwalamy im zaopatrzeæ siê tu na dalsz¹ drogê. Nie interesuj¹ nas niewolnicy.}
{239} {} {Masz wymówkê, co?}
{240} {} {To dobry pomys³.}

{241} {} {Co to za problem mia³eœ z burmistrzem?}
{242} {} {Czas i dziecko zmieni³y starego tyrana. Zwi¹tcza³ i straci³ prawo do kierowania mn¹. Wczeœniej przez niego musia³em zadowoliæ siê rol¹ menad¿era. Teraz jest mój czas, by ¿yæ piêknie.}
{243} {} {Nie mo¿na temu zaprzeczyæ. Przynajmniej teraz.}
{244} {} {ZnajdŸ kogoœ innego do rozmowy. Nie mam na to czasu ani ochoty.}
{245} {} {Có¿, wiêc nie bêdê siê wtr¹caæ.}

# Po naprawiê
{250} {} {Mo¿emy teraz trochê porozmawiaæ. Co tam?}
{251} {} {Nic specjalnego. Czeœæ.}

{260} {} {Czy to wszystko to stacja wodna? Imponuj¹ca.}
{261} {} {Ta stacja ma ponad sto lat. Ciê¿ko j¹ utrzymaæ na chodzie.}
{262} {} {Dlaczego potrzebujecie tyle wody?}
{263} {} {Muszê iœæ. Do zobaczenia.}
{264} {} {Kolejne pytanie.}
{265} {} {Dlaczego nie? Ka¿dy potrzebuje wody. Jak mówi¹, nie ma ¿ycia na pustyni bez niej. Dla mnie to przede wszystkim Ÿród³o dochodu. Dla reszty miasta, g³ówny powód istnienia.}
{266} {} {Czy nie trzymasz stacji w swoich rêkach?}
{267} {} {Woda przyci¹ga karawany i zapewnia mieszkañcom dochód. Poza tym muszê oddawaæ czêœæ kapsli do skarbca. Burmistrz te¿ potrzebuje kasy.}
{268} {} {I oczywiœcie nie jesteœ z tego zadowolony?}
{269} {} {Ktoœ musi za³atwiaæ papierkow¹ robotê i negocjowaæ. Ja jestem lepszy w sprawach technicznych. Jedyne, czego chcia³bym od Alfreda, to ¿eby by³ twardszy w kontaktach z klientami. Mam doœæ przechodzenia z wody do wody.}
{270} {} {Tak to jest. Cofnijmy siê trochê.}
{271} {} {Sk¹d masz tyle wiedzy o przedwojennej technologii?}
{272} {} {Prawde mówi¹c, g³ównie Blacharze to naprawiali. Ja dziêki doœwiadczeniu mogê naprawiæ kilka mniejszych rzeczy, reszta ch³opaków wie tylko, które przyciski wciskaæ.}
{273} {} {Wydaje siê, ¿e im nie ufasz?}
{274} {} {}
{275} {} {Blacharzom? Dlaczego jesteœ tym taki zdziwiony?}
{276} {} {Musia³em du¿o zap³aciæ za pomoc. Ale nikt inny by tego nie zrobi³. Ponadto sami Blacharze s¹ zainteresowani rozwojem szlaku handlowego.}
{277} {} {Wiesz, ¿e ci technokraci wypadli z w³asnej technologii?}
{278} {} {S³ysza³em. Nie obchodz¹ mnie Blacharze. Ale co zrobiê, gdy stacja znów bêdzie wymaga³a powa¿nych napraw? Bojê siê nawet to sobie wyobraziæ.}
{279} {} {Cofnijmy siê trochê.}
{280} {} {Kto zarz¹dza miastem?}
{281} {} {Ja tu dowodzê.}
{282} {} {Co za zwrot akcji. Wiêc muszê z tob¹ porozmawiaæ.}
{283} {} {Ja i burmistrz razem. Burmistrz ma na imiê Bustos i mieszka w rezydencji przy tej samej ulicy.}
{284} {} {Opowiedz mi o burmistrzu. Co to za cz³owiek?}
{285} {} {Znamy siê od dawna i dobrze siê dogadujemy. Chocia¿ zdarzaj¹ siê nam nieporozumienia, na przyk³ad przez jego córkê. Za du¿o jej pozwala.}
{286} {} {To on ma córkê?}
{287} {} {Ladna, ale g³upiutka dziewczyna. Nigdy nie rozumia³em, dlaczego Bustos wszystko jej wybacza. Na jego miejscu ju¿ dawno chwyci³bym za pas.}
{288} {} {Rozumiem. Ale wróæmy trochê.}
{289} {} {Co myœlisz o burmistrzu?}
{290} {} {Swietny goœæ. Ale chyba nie spodziewasz siê, ¿e omówiê z tob¹ mojego najlepszego przyjaciela? Masz inne pytania?}
{291} {} {Niewa¿ne. I tak jestem przejazdem.}
{292} {} {Czy jest dla mnie jakaœ praca w mieœcie?}
{293} {} {Spróbuj zapytaæ burmistrza. Na mojej stacji nie ma ju¿ dla ciebie pracy.}
{294} {} {Nie s¹dzê. W ka¿dym razie, na tej stacji nie ma ju¿ dla Ciebie pracy.}
{295} {} {OK. Zmieñmy temat.}
{296} {} {W takim razie nic tu po mnie. Do widzenia.}
{297} {} {Poza naprawieniem tego przeklêtego filtra nie mam nic do zaoferowania. Znasz siê coœ na technologii?}
{298} {} {Nie, to nie dla mnie. Zmieñmy temat.}
{299} {} {Zobaczê, mo¿e znajdê rozwi¹zanie.}

{300} {} {Wiem, co siê sta³o u kupca. Bieda doprowadza ludzi do szaleñstwa.}
{301} {} {Jak widaæ. Co w zwi¹zku z tym?}
{302} {} {Nic. Jeœli masz zdrowy rozs¹dek, nie zrobisz nic g³upiego. Nie rozpowiadaj tej historii. Musimy dbaæ o nasz¹ reputacjê.}
{303} {} {Nie ma problemu. Nic nie widzia³em i nic nie s³ysza³em.}
{1303} {} {Nie ma problemu. Nic nie widzia³am i nic nie s³ysza³am.}
{304} {} {Poprawna odpowiedŸ. Mo¿e nawet siê dogadamy.}
{305} {} {Tak... oczywiœcie.}
{306} {} {Cisza ma swoj¹ cenê.}
{307} {} {Nie otwieraj niepotrzebnie ust, a nie bêdziesz mieæ niepotrzebnych problemów. Taka ma³a rada.}
{308} {} {Och, no jasne...}
{309} {} {Cisza ma swoj¹ cenê. Chyba nie spodziewasz siê, ¿e ta historia sama siê pogrzebie, prawda?}
{310} {} {Skoro tak mówisz. (odlicza 10 kapsli) Ale uwa¿aj na jêzyk. W przeciwnym razie bêdziesz mieæ du¿e k³opoty w tym mieœcie.}
{311} {} {Och, doskonale ciê rozumiem...}