{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz stra¿nika stacji wodnej. Nie wie, co ze sob¹ zrobiæ.}

{110} {} {Czego chcesz?}
{111} {} {Lepiej wynoœ siê z naszego terytorium.}
{112} {} {Jeœli potrzebujesz wody, skontaktuj siê ze sprzedawc¹ przy wejœciu.}
{113} {} {Porozmawiaj z moim szefem.}
{114} {} {Znasz naszego burmistrza?}
{115} {} {Mamy najczystsz¹ wodê w ca³ej Sonorze.}
{116} {} {Po prostu wiedz, ¿e za kradzie¿ ucinamy tu rêce.}
{117} {} {Zawsze jesteœmy czujni.}
{118} {} {Pilnowanie tej stacji jest takie mêcz¹ce.}
{119} {} {Bandyci daj¹ siê nam we znaki.}
{120} {} {Najlepiej unikaæ bandytów poza miastem.}