{100} {} {Widzisz wojownika szos.}
{101} {} {Widzisz jednego z miejscowych bandytów.}
{102} {} {Powodzenia na szlaku.}

{200} {} {Hej, dziêki za pomoc, brachu. Ci gliniarze œcigali mnie ju¿ od kilku dni. Ale w sumie to dlaczego mnie uratowa³eœ?}
{1200} {} {Hej, dziêki za pomoc, ma³a. Ci gliniarze œcigali mnie ju¿ od kilku dni. Ale w sumie to dlaczego mnie uratowa³aœ?}
{201} {} {Zawsze pomagam potrzebuj¹cym.}
{202} {} {Bzdury! Nie uwierzê w coœ takiego. Ka¿demu zale¿y tylko na w³asnej skórze. Ale jeœli faktycznie nie masz nic przeciwko daniu w mordê za kogoœ nieznajomego, nie mam nic przeciwko. Przy okazji, czy masz ochotê poznaæ mój gang? Szef prawdopodobnie bêdzie tob¹ zainteresowany.}
{203} {} {Co to za gang?}
{204} {} {Niebieskie Tarcze. Nazywamy siê tak z powodu tych znaków drogowych. Nie wiesz? W takim razie odwiedŸ nasz¹ bazê, jest tam. Powiem o tobie innym, dziêki czemu bêdziesz mieæ mo¿liwoœæ zobaczyæ siê z Benem.}
{205} {} {Ok. Powodzenia na drodze.}
{206} {} {Chcê do³aczyæ do twojego gangu.}
{207} {} {Ha! Niezbyt dobry pomys³. Tylko ci, którzy naprawdê nie maj¹ nic do stracenia w „cywilizowanym œwiecie”, mog¹ do nas do³aczyæ. W ka¿dym razie Ben, nasz lider, osobiœcie siê tym zajmuje. Musisz z nim porozmawiaæ.}
{208} {} {Ok. Tak zrobiê.}
{209} {} {Tam jest baza. Powiem moim o tobie, dziêki czemu bêdziesz mieæ mo¿liwoœæ zobaczyæ siê z Benem. Mi³ej drogi.}
{210} {} {Ok. Powodzenia na drodze.}
{211} {} {Hej, dziêki za pomoc, brachu. Ci gliniarze œcigali mnie ju¿ od kilku dni.}
{1211} {} {Hej, dziêki za pomoc, ma³a. Ci gliniarze œcigali mnie ju¿ od kilku dni.}
{212} {} {Czego od ciebie chcieli?}
{213} {} {Byli ³owcami nagród. Czasami s¹ zatrudniani w Casa Grande lub Phoenix, aby przepêdziæ nasz gang z okolicy. Ale to s¹ nasze tereny! Nie uda im siê.}
{214} {} {Rozumiem.}
{215} {} {Opowiem Benowi i innym tê historiê. Do zobaczenia w bazie.}
{216} {} {Mi³ej podró¿y.}
