{100} {} {Widzisz Don Reevesa.}
{101} {} {Widzisz mê¿czyznê z przystojn¹ czarn¹ brod¹ i szlachetnym wygl¹dem.}

{200} {} {Dziêki za pomoc z buntownikami, przyjacielu. Któregoœ dnia dosiêgnie wszystkich ich surowa kara.}
{1200} {} {Dziêkujê, ¿e pomog³aœ mi rozprawiæ siê z buntownikami, piêkna damo. Któregoœ dnia dosiêgnie wszystkich ich surowa kara.}
{201} {} {Kim w³aœciwie jesteœ?}
{202} {} {Zawsze wyci¹gam pomocn¹ d³oñ do potrzebuj¹cych. Ale kim ty jesteœ i jak rozgniewa³eœ tych ch³opów?}
{203} {} {Stoi przed tob¹ Don James Reeves. Jestem w³aœcicielem ca³ego obszaru Arizony. Stanu, który zosta³ brutalnie odebrany moim przodkom.}
{204} {} {Mówisz powa¿nie?}
{205} {} {Jak to udowodnisz?}
{206} {} {Mogê pokazaæ dokumenty i stary nagrobek z nazwiskami moich przodków, ale czy to kogoœ przekona? Dlatego nie zamierzam niczego udowadniaæ, tylko po prostu zwrócê ziemie prawowitemu spadkobiercy. Jestem baronem Arizony. To powinno wystarczyæ.}
{207} {} {I naprawdê myœlisz, ¿e mo¿esz nagi¹æ przed sob¹ wolnych ch³opów?}
{208} {} {Tak. Jak widaæ, wielu ju¿ to zrobi³o. Ci, którzy bêd¹ siê opieraæ do koñca, spotka haniebny los. Pochyl siê i ty. Jeœli z³o¿ysz przysiêge, nie zapomnê Twojej lojalnoœci do koñca ¿ycia.}
{209} {} {Przepraszam, baronie, ale mam zobowi¹zania tylko wobec mojego domu.}
{210} {} {Có¿, za twoj¹ pomoc, uznajê niezale¿noœæ twojego domu. IdŸ w pokoju, przyjacielu.}
{211} {} {Do widzenia.}
{212} {} {Jesteœ tylko kolejnym oszustem. Nie powinienem by³ przerywaæ tej walki.}
{213} {} {To przykre us³yszeæ tak obraŸliwe s³owa od kogoœ, komu zawdziêczam ¿ycie. Có¿, prawdopodobnie nie jest nam ze sob¹ po drodze. Ale jeœli kiedykolwiek jeszcze siê spotkamy, liczê na poprawê.}
{214} {} {By³oby lepiej, gdyby ch³opi ciê zlinczowali. Do widzenia.}
{215} {} {Skoñczê to, czego ch³opi nie potrafili dokoñczyæ. Giñ draniu!}
{216} {} {Z³o¿ê przysiêge, O Don Reeves, baronie piêknej Arizony.}
{217} {} {Naprawdê w to uwierzy³eœ? Idioto, wola³bym ciê zabiæ, ni¿ stan¹æ po twojej stronie!}
{218} {} {[Inne opcje]}

{220} {} {Cieszê siê, ¿e mam ciê w swoich szeregach, szlachetny cz³owieku. Zegnij kolano i wypowiedz s³owa przysiêgi...}
{221} {} {Przysiêgam chroniæ Ciebie i Twoj¹ krainê. [+1 Si³a]}
{222} {} {Przysiêgam, ¿e bêdê twoim lojalnym poddanym. [+1 Percepcja]}
{1222} {} {Przysiêgam, ¿e bêdê twoim lojalnym poddanym. [+1 Percepcja]}
{223} {} {Przysiêgam, ¿e nigdy nie zostawiê ciê w tarapatach. [+1 Wytrzyma³oœæ]}
{224} {} {Przysiêgam, ¿e zawsze bêdê twoim przyjacielem, Rhysis. [+1 Charyzma]}
{225} {} {Przysiêgam byæ twoim lojalnym zwolennikiem. [+1 Intelekt]}
{1225} {} {Przysiêgam byæ twoim lojalnym zwolennikiem. [+1 Intelekt]}
{226} {} {Przysiêgam znaleŸæ lepsze ¿ycie dla twojej Arizony. [+1 Zrêcznoœæ]}
{227} {} {Przysiêgam przynieœæ szczêœcie tobie i twojej krainie. [+1 Szczêœcie]}
{228} {} {Wstañ, przyjacielu. Od teraz twoja pieczêæ jest równa mojej. Broñ Arizony, rz¹dzisz ni¹ w moim imieniu.}
{229} {} {Moje podziêkowania, baronie Reeves.}

{230} {} {Niech Ciê Bóg b³ogos³awi.}
{231} {} {Do widzenia.}

