{100} {} {Widzisz Henrego Beamisa.}
{101} {} {Widzisz Henrego Beamisa. W jego pobli¿u widzisz zniszczony krajobraz. Fragment tego, co ludzkoœæ sama sobie zrobi³a.}
{102} {} {Có¿, na pewno zostanie mi to wybaczone.}
{103} {} {* Hmuck * Mia³em wiecznoœæ na czytanie. Ale zgubi³em gdzieœ okulary. To takie niesprawiedliwe.}
{104} {} {Ach, ksi¹¿ki! Mam ich doœæ na resztê ¿ycia.}
{105} {} {Ach! Znowu widzê! Mogê czytaæ! Ratujesz mnie od wiecznej têsknoty... Proszê, weŸ j¹, i przeczytaj razem ze mn¹, to bardzo interesuj¹ca ksi¹¿ka.}
{106} {} {Potrzebujê okularów do czytania. Rozumiesz?}

{110} {} {W porz¹dku, uh, w porz¹dku.}
{111} {} {Nie mia³em wczeœniej okazji ¿yæ w odosobnieniu.}
{112} {} {Co mam teraz zrobiæ?}
{113} {} {* krzyk *}
{114} {} {* p³acz *}
{115} {} {Tak, uh, mam szczêœcie... Bardzo du¿o szczêœcia... Pomocy! Ktokolwiek!}
{116} {} {Czy jestem tu sam?}
{117} {} {Gdyby nie ta samotnoœæ...}
{118} {} {Gdybym móg³ coœ zrobiæ...}
{119} {} {Zajêcie... potrzebujê zajêcia...}
{120} {} {To niesprawiedliwe. To tak strasznie niesprawiedliwe.}

{150} {} {Och, ile tam jest ksi¹¿ek!}
{151} {} {Zebrane dzie³a Dickensa!}
{152} {} {Zebrane prace George'a Bernarda Shawa!}
{153} {} {Wiersze Browninga, Shelleya i Keatsa!}
{154} {} {"David Copperfield", "Wielki Gatsby", "Chata Wuja Toma"...}
{155} {} {Ksi¹¿ki... Wielkie Skarby Swiata...}
{156} {} {Ksi¹¿ki, ksi¹¿ki, ksi¹¿ki... Ach!}
{157} {} {styczeñ... luty... marzec... ten rok... przysz³y rok...}
{158} {} {Najwa¿niejsze jest to, ¿e mam teraz du¿o wolnego czasu tylko dla siebie.}
{159} {} {* œmiech *}
{160} {} {Mam szczêœcie... naprawdê...}
{161} {} {Wszystko, czego chcia³em, jest tutaj.}
{162} {} {Teraz mam coœ wspólnego z moimi myœlami.}
