{100} {} {Widzisz farmera.}
{101} {} {Widzisz farmera zgorzknia³ego przez ca³y œwiat.}

{110} {} {Giñcie, dranie!}
{111} {} {Nie oddam wam tego tak ³atwo!}
{112} {} {Odbiorê swoj¹ ziemiê si³³!}
{113} {} {Zabrali moj¹ farmê, a ja zabiorê resztê.}
{114} {} {Stra¿nicy mi za wszystko zap³ac¹!}
{115} {} {Myœlisz, ¿e tracê rozum? Nie, ja chcê tylko sprawiedliwoœci.}
{116} {} {Dlaczego mam komuœ p³aciæ za swoj¹ ziemiê?}
{117} {} {Nie obchodz¹ mnie przepisy i regulacje!}
{118} {} {Stra¿nicy próbowali mnie oszukaæ i teraz ich za to dorwê.}
{119} {} {Wszyscy zap³acicie!}
