{100} {} {Widzisz osadnika.}
{101} {} {Widzisz jednego z mieszkañców kawiarni.}
{102} {} {Wynoœ siê, zanim zmieniê zdanie.}
{103} {} {Fuj, ta rodzina na pewno ma coœ do ukrycia.}
{104} {} {Wygl¹da przepysznie. Kochanie, odetnij mi kawa³ek udka.}
{105} {} {Nikczemnoœæ tego miejsca dobieg³a koñca.}
{106} {} {Powinieneœ byæ dla mnie milszy.}

{200} {} {Ach, podró¿nik prosto z pustkowi! Mi³o jest zobaczyæ now¹ twarz w tych s³abo zaludnionych obszarach. Sk¹d pochodzisz?}
{201} {} {Z ma³ej wioski daleko st¹d.}
{202} {} {Lepiej mnie o to nie pytaj. Jasne?}
{203} {} {Ok, cokolwiek powiesz. My mieszkamy tu od wielu lat. Chcesz spêdziæ tu noc? Proszê - mamy du¿o wolnego miejsca. Poza tym posi³ek bêdzie wkrótce gotowy. Powinieneœ zostaæ, uwierz mi, bêdzie przepyszny.}
{204} {} {Uch, pomyœlê o twojej propozycji.}

{210} {} {Mogê w czymœ pomóc?}
{211} {} {Tylko siê rozgl¹dam.}
{212} {} {Czy mogê siê tu rozejrzeæ?}
{213} {} {Oczywiœcie. Ale nie wchodŸ na zaplecze. To nasz w³asny prywatny k¹t w tym miejscu.}
{214} {} {Oczywiœcie, nie ma problemu.}
{215} {} {Brzmi jak coœ co warto zapamiêtaæ. Bêdê o tym pamietaæ.}
{216} {} {Jak przetrwaliœcie na tej spalonej pustyni?}
{217} {} {Jeœli naprawdê chcesz ¿yæ, znajdziesz sposób. Zywimy siê jaszczurkami, skorpionami i wszelkiego rodzaju ma³ymi zwierzêtami. Zbieramy wodê z tylko znam znanych Ÿróde³. Zdarza siê nawet, ¿e podró¿nicy zostawiaj¹ po sobie takie rzeczy, jak naboje. To nam w zupe³noœci wystarcza.}
{218} {} {Czy mieszkacie tu sami?}
{219} {} {No tak. Nasi rodzice mieszkali z nami, ale pustkowia ich nam odebra³y. Od czasu do czasu zatrzymuj¹ siê tu podró¿nicy i karawany.}
{220} {} {Wiesz, w dzisiejszych czasach trudno jest znaleŸæ prawdziw¹ ¿yczliwoœæ.}
{221} {} {O tak, rozumiem. Mieszkañcy wiosek nie ufaj¹ sobie nawzajem, brakuje jedzenia i wody dla wszystkich. Nie martw siê, my staramy siê byæ w porz¹dku. Nikogo nie oceniamy i nie chcemy sami byæ oceniani.}
{222} {} {Ta kawiarnia wygl¹da na bardzo star¹. Jak d³ugo tu mieszkacie?}
{223} {} {Dostaliœmy tê kawiarniê od naszych rodziców. A oni - od swoich rodziców. I tak dalej i tak dalej. To bardzo stare miejsce.}
{224} {} {Co jest na Waszym zapleczu?}
{225} {} {Tylko rzeczy osobiste i miejsce do spania. Zrozum, to nasza osobista przestrzeñ. Nikt z zewn¹trz nie mo¿e tam wejœæ. I to jedyna rzecz, o któr¹ prosimy osoby postronne.}
{226} {} {Czy masz czym handlowaæ?}
{227} {} {Jeœli masz coœ przydatnego, nie mam nic przeciwko handlowaniu. Rozejrzyj siê, czego potrzebujesz?}
{228} {} {Czy akceptujecie kapsle do butelek?}
{229} {} {O czym ty mówisz? Po co nam te kapsle? Zostaw ten nonsens. Nigdy bym nie uwierzy³, ¿e ludzie w miastach wymieniaj¹ siê za te bezu¿yteczne rzeczy. Zawsze wyrzucaliœmy je jak œmieci.}
{230} {} {Czy mo¿emy porozmawiaæ o czymœ innym?}
{231} {} {Coœ jeszcze?}
{232} {} {Nic, pójdê odpocz¹æ.}

{250} {} {Powinienem by³ ciê natychmiast zastrzeliæ. Zawsze mówi³em mojej siostrze, ¿eby nie rozmawia³a zbyt czêsto z obcymi.}
{251} {} {Pamiêtasz, jak powiedzia³em, ¿e ciê¿ko o prawdziw¹ ¿yczliwoœæ na pustkowiu? Mia³em racjê.}
{1251} {} {Pamiêtasz, jak powiedzia³am, ¿e ciê¿ko o prawdziw¹ ¿yczliwoœæ na pustkowiu? Mia³am racjê.}
{252} {} {Jak¹ racjê? Zyjemy na œrodku pustyni, gdzie nie ma nic - ¿adnych upraw, ¿adnych zwierz¹t, ¿adnych osad. Rzadcy podró¿nicy to jedyny sposób na przetrwanie w tak trudnych warunkach.}
{253} {} {Wiêc dlaczego nie wydostaæ siê z tego piek³a? Gdzieœ w oddali s¹ ca³e miasta...}
{254} {} {Bzdury! Wszyscy opowiadacie te historie, ale wszystkie s¹ ró¿ne. Nie ufam ju¿ obcym. Opuszczenie tej kawiarni, w której spêdziliœmy ca³e ¿ycie, dla w¹tpliwych historii to pewna œmieræ. Chcemy ¿yæ.}
{255} {} {Wiêc jesteœ po prostu g³upcem.}
{256} {} {Tak... mo¿e. Ale ten g³upiec w³aœnie przechytrzy³ nieznajomego. I prze¿yje. Ty nie.}
{257} {} {Hej...}
{258} {} {Dok³adnie. Kiedyœ mia³eœ szansê. A teraz jest póŸno, idioto...}
{1258} {} {Dok³adnie. Kiedyœ mia³eœ szansê. A teraz jest póŸno, durniu...}
{259} {} {Wiêc tak trwasz na tej ja³owej pustyni - zabijaj¹c podró¿ników i robi¹c z nich... jedzenie?}
{260} {} {Wiêc ta rozmowa bêdzie mia³a tylko jeden wynik. Twoj¹ œmieræ.}
{261} {} {Zamknij siê. Oczyszczê pustkowia ¿e œcierwa, takiego jak twoja rodzina.}
{262} {} {Czekaj, robisz du¿y b³¹d...}
{263} {} {Czekaj. Mówiê prawdê. Na pustkowiach s¹ du¿e miasta. Jest wystarczaj¹co du¿o miejsca nawet dla Twojej rodziny. Zyj¹c na pustyni, skazujecie siê jedynie na powoln¹ œmieræ.}
{264} {} {Hmm... To dziwne, ¿e ludzie z zewn¹trz tak czêsto mówi¹ o miastach. Mo¿e ich istnienie to jednak prawda... Wiesz, gdzie mo¿emy pójœæ? Poka¿ mi. Chcê wiedzieæ.}
{265} {} {Ok, ale potem pozwolisz mi odejœæ. W porz¹dku?}
{266} {} {Kurwa. W cywilizowanym spo³eczeñstwie nie ma miejsca dla ludzi takich jak Ty.}
{267} {} {Huh? Kogo my tu mamy? Z³odzieja? Powiedziano mi, ¿e w miastach ucina siê rêce z³odziejom. Zrobiê tak samo. Nie ruszaj siê.}
{268} {} {IdŸ do diab³a, ohydny kanibalu.}