{100} {} {Widzisz osadnika.}
{101} {} {Widzisz jednego z mieszkañców kawiarni.}
{102} {} {Wynoœ siê!}

{110} {} {Ju¿ odchodzisz?}
{111} {} {Nie œpiesz siê z wyjœciem, posi³ek zaraz bêdzie gotowy.}
{112} {} {Chcesz kawy?}
{113} {} {Ach, twoje zapadniête policzki sugeruj¹ brak bia³ka.}
{114} {} {Musisz koniecznie spróbowaæ naszego jedzenia.}
{115} {} {Uspokój siê.}
{116} {} {Zawsze chêtnie witamy podró¿nych.}
{117} {} {Chcesz trochê odpocz¹æ?}
{118} {} {Co powiesz na relaksuj¹cy masa¿?}
{119} {} {Wygl¹dasz tak... atrakcyjnie.}
{120} {} {Musisz byæ spragniony przez podró¿.}
{121} {} {Och, zawsze chêtnie witamy nowe twarze.}
{122} {} {ChodŸ, usi¹dŸ, od³ó¿ na bok wszystkie te bzdury.}
{123} {} {Tutaj mo¿esz siê ca³kowicie rozluŸniæ.}
{124} {} {Nie martw siê, tutaj jest ca³kowicie bezpiecznie.}