{100} {} {Widzisz uciekiniera.}
{101} {} {Widzisz mê¿czyznê w garniturze. Krwawi.}
{102} {} {Proszê uratuj mnie... Mam z³oto... du¿o z³ota...}

{200} {} {(mê¿czyzna w garniturze wychodzi ci na spotkanie; jego g³owa krwawi, a on sam ledwo stoi.)}
{201} {} {Kiepsko wygl¹dasz, kolego.}
{202} {} {O Bo¿e, jesteœ ranny!}
{203} {} {P-proszê... pomó¿... (pada u twoich stóp, czepiaj¹c siê twoich ubrañ ostatkiem si³) Dam Ci wszystko... Mam z³oto... (upada na ziemiê) Du¿o... z³ota...}
{204} {} {Sorry stary. Z³oto ju¿ dawno straci³o na wartoœci. S³yszysz?}
{205} {} {Wszystko bêdzie dobrze, poczekaj...}

