{100} {} {Widzisz Arviego.}

{110} {} {Arvi nienawidzi ludzi!}
{111} {} {Spójrz, ty nieistotny owadzie!}
{112} {} {Ludzie nienawidz¹ ludzi takich jak ty.}
{113} {} {Dlaczego nie zostawisz nas samych?!}
{114} {} {Ludzie œledz¹ nas wszêdzie!}
{115} {} {Ludzie zawsze strzelali do nas pierwsi!}
{116} {} {Stwórco, daj mi si³ê do obrony tego miejsca przed innymi!}
{117} {} {Nebius nie chcia³ widzieæ ludzi w naszym mieœcie.}
{118} {} {Arvi tylko chroni miasto przed innymi!}
{119} {} {Arvi jest dobry. Arvi próbuje ze wzglêdu na Levi.}

{120} {} {Nebius rozkaza³ chroniæ miasto przed ludŸmi.}
{121} {} {Przepraszam, ale nie mo¿esz tu zostaæ.}
{122} {} {Arvi pamiêta, kto pomóg³ Leviemu. Arvi jest wdziêczny.}
{123} {} {Arvi jest dobry. Arvi chroni miasto przed ludŸmi.}
{124} {} {Czy ty s³uchasz Arvi?}
{125} {} {Czy s³uchasz Stwórco?}
{126} {} {Têskniê... Stwórco...}
{127} {} {Arvi!}
{128} {} {}
{129} {} {}