{100} {} {Widzisz robota administracyjnego.}

{200} {} {Witamy na Dzikim Zachodzie i przygodach!}
{201} {} {Witamy w Legend City!}
{202} {} {Witamy w najwiêkszym parku rozrywki w Arizonie!}
{203} {} {Wow, to brzmi œwietnie.}
{204} {} {Nie przeszkadzaj, partnerze.}

{210} {} {Jak mogê pomóc, proszê pana?}
{1210} {} {Jak mogê pani pomóc?}
{211} {} {Nie chcê niczego wiêcej.}
{212} {} {To wszystko, co mnie interesowa³o. Teraz pozwól mi siê bawiæ.}

{220} {} {Co to za miejsce?}
{221} {} {Jesteœ w Legend City - najwiêkszym parku rozrywki w ca³ej Arizonie!}
{222} {} {Powiedz mi, co mogê tutaj robiæ?}
{223} {} {Polecam przeja¿d¿ki, wirtualny plac zabaw, strzelnicê, sto³ówkê - co Ciê interesuje?}
{224} {} {Najlepiej by³oby, gdybym sam siê rozejrza³.}
{225} {} {Ale co to za miejsce?}
{226} {} {Interesuj¹ mnie przeja¿d¿ki.}
{227} {} {Przykro mi, przeja¿d¿ki s¹ obecnie zamkniête z przyczyn technicznych. Przepraszam.}
{1227} {} {Przykro mi, ale przeja¿d¿ki s¹ obecnie zamkniête z przyczyn technicznych. Przepraszam.}
{228} {} {Czy mogê postrzelaæ na strzelnicy?}
{229} {} {Przepraszam pana, ale aktualnie brakuje amunicji.}
{1229} {} {Przepraszam pani¹, ale aktualnie brakuje amunicji.}
{230} {} {A czy kawiarnia jest otwarta?}
{231} {} {Przepraszam, ale kawiarnia jest chwilowo nieczynna.}
{1231} {} {Przepraszam, ale kawiarnia jest chwilowo nieczynna.}
{232} {} {Czy coœ tu w ogóle dzia³a?}
{233} {} {Mo¿na wypróbowaæ wirtualne gry w naszej nowej sali gier. Mi³ego pobytu, s-i-ir.}
{1233} {} {Mo¿na wypróbowaæ wirtualne gry w naszej nowej sali gier. Mi³ego pobytu, ma-ada-me.}
{234} {} {Ok, zobaczmy to w akcji.}
{235} {} {Wiêc zrób przejœcie, pora na moje do gry wejœcie!}
{236} {} {Czy sto³ówka w ogóle dzia³a?}
