{100} {} {Widzisz Lamonta.}
{101} {} {Widzisz wychudzonego mê¿czyznê. Jego spojrzenie wydaje siê takie puste.}
{102} {} {Biegnij, zanim bêdzie za póŸno. Nadal masz szansê...}

{200} {} {Kto tu jest? Odpowiedz mi! Bo¿e, mam nadziejê, ¿e nie jesteœ wytworem mojej wyobraŸni... N-nie dotykaj chwastów! S¹ niebezpieczne!}
{201} {} {Ok, uspokój siê.}
{202} {} {Jestem Lamont. Mam farmê w kanionie. No, kiedyœ by³a to farma.}
{203} {} {Dlaczego? Czy s¹ tam te *chwasty*?}
{204} {} {S¹ gorsze ni¿ modliszki... (rozgl¹da siê w panice) Chwasty! S¹ wszêdzie! Wszêdzie!}
{205} {} {Daj spokój, to tylko chwasty...}

{210} {} {Mam farmê w kanionie.}
{211} {} {Tak, powiedzia³eœ mi to ju¿.}
{212} {} {Czy powiedzia³em, ¿e nic z niej nie zosta³o? Przynajmniej - nic dobrego. Lepiej siê tam nie pojawiaæ. Ale ja nie mam gdzie pójœæ.}
{213} {} {Zaczekaj chwilê. Jeœli faktycznie te chwasty to taki problem, to dlaczego zosta³eœ?}
{214} {} {Dlaczego... Có¿, z ciekawoœci. Nie zachowuj¹ siê jak zwyk³e chwasty. Wiêc je obserwujê. Ale robiê to ju¿ zbyt d³ugo.}
{215} {} {Wiêc nie chcesz czy nie mo¿esz siê st¹d teraz wydostaæ?}
{216} {} {Ani ja, ani ty. Nikt st¹d nie wyjdzie!}
{217} {} {Co ty gadasz...}

{220} {} {Nie ma wyjœcia. To przez nich. NIE MA.}
{221} {} {Kim s¹ „oni”?}
{222} {} {O ile sobie przypominam, ta inwazja rozpoczê³a siê kilka tygodni temu, kiedy to „coœ” wyl¹dowa³o na ziemi.}
{223} {} {Coœ?}
{224} {} {Nie wiem. Prawdopodobnie meteoryt. Widzia³em b³ysk na niebie. Wtedy us³ysza³em trzask.}
{225} {} {Czy próbowa³eœ dowiedzieæ siê, co to by³o?}
{226} {} {Nastêpnego dnia poszed³em to zobaczyæ. Ale nie znalaz³em nawet dziury w ziemi. I wtedy zaczê³y siê dziaæ te rzeczy.}
{227} {} {Kontynuuj.}
{228} {} {Na pocz¹tku niczego nie zauwa¿y³em. Po prostu wydawa³o mi siê, ¿e chwasty by³y nieco wiêksze ni¿ zwykle. Ale potem zaczê³y zachowywaæ siê tak, jakby ¿y³y. Nie pozwala³y mi nawet opuœciæ kanionu - zablokowa³y mi drogê i ³apa³y mnie za nogi, gdy próbowa³em uciec. Od tego czasu nie próbowa³em...}
{229} {} {Hmm.}
{230} {} {OdejdŸ! Nadal masz szansê siê st¹d wydostaæ. Uciekaj póki mo¿esz!}
{231} {} {Och...}
