{100} {} {Widzisz Paula.}
{101} {} {Widzisz bardzo wychudzonego mê¿czyznê.}

{200} {} {Cz³owieku! Jak siê masz... S³uchaj, nie pasujesz tutaj. Mutanty nie pozwol¹ ci ¿yæ, jeœli ciê znajd¹.}
{201} {} {Ale ciebie zostawili. Kim jesteœ?}
{202} {} {Wiem. Wiêc siedŸ spokojnie i nie rób zamieszania.}

{210} {} {Grozi ci wielkie niebezpieczeñstwo.}
{211} {} {Jeœli zostaniesz z³apany, nie bêdê móg³ ci pomóc.}
{212} {} {Dlaczego nadal tu jesteœ?}
{213} {} {Co myœlisz?}
{214} {} {Nadal masz szansê st¹d uciec.}
{219} {} {Do zobaczenia.}

{220} {} {Kim jesteœ?}
{221} {} {Nazywam siê Paul. Nadzorujê pracê tej platformy.}
{222} {} {To niesamowite. Sk¹d wiesz, jak radziæ sobie z t¹ technik¹?}
{223} {} {Mylisz siê. Nikt ¿yj¹cy w dzisiejszych czasach nie potrafi zarz¹dzaæ starymi technologiami.}
{224} {} {Có¿, jestem in¿ynierem, przez ca³e ¿ycie by³em do tego szkolony.}
{225} {} {Naprawdê? Sk¹d masz wiedzê?}
{226} {} {Czy nazwa Bractwo Stali coœ ci mówi? Jestem rycerzem tego staro¿ytnego zakonu. A g³ównym zadaniem rycerzy jest radzenie sobie ze staro¿ytnymi technologiami. To prawda, jestem specjalist¹ od broni energetycznej. Musia³em zrobiæ wszystko, co w mojej mocy, aby ta platforma dzia³a³a.}
{227} {} {Ostatnio tak¿e zosta³em cz³onkiem Bractwa Stali. Mi³o ciê poznaæ, bracie.}
{1227} {} {Ostatnio tak¿e zosta³am cz³onkiem Bractwa Stali. Mi³o ciê poznaæ, bracie.}
{228} {} {Ok, wierzê ci. Czy mam jakiœ wybór? Jednak w ca³ej historii Bractwa tylko jednej osobie z Pustkowia uda³o siê wejœæ w nasze szeregi w tak krótkim czasie. Ale jego zas³ugi by³y ogromne.}

{230} {} {Jak siê tu znalaz³eœ?}
{231} {} {Super mutanci z³apali mnie gdzieœ pod Nekropolis. Na pocz¹tku chcieli mnie wykoñczyæ. Ale potem dowiedzieli siê, ¿e jestem in¿ynierem i postanowili zostawiæ mnie przy ¿yciu abym im ogarn¹³ to cudo. Od tego czasu przebywam w niewoli.}
{232} {} {Nekropolis? Gdzie to jest?}
{233} {} {W Kalifornii. Nic dziwnego, ¿e nie wiesz, poniewa¿ jesteœmy daleko od tego miejsca.}
{234} {} {Opowiedz mi o Bractwie Stali.}
{235} {} {Przez d³ugi czas mieszkaliœmy w bunkrze i nie dawaliœmy o sobie za bardzo znaæ, dopóki ca³a Kalifornia nie znalaz³a siê pod groŸb¹ podboju przez super mutanty. Ale dziêki odwadze naszych braci ich armia zosta³a pokonana, a jej resztki wci¹¿ s¹ eliminowane.}
{236} {} {Jeœli byliœcie schowani w bunkrze, sk¹d wiedzieliœcie o armii?}
{237} {} {Szczerze, ca³ego zwiadu dokona³a jedna osoba z pustkowi. Wkrótce potem zosta³a inicjowana. To ona zdo³a³a sabotowaæ g³ówn¹ bazê wroga w Mariposie. Ale mówimy wszystkim, ¿e to my powstrzymaliœmy jego armiê. I jest to prawda, bior¹c pod uwagê zaciête bitwy, które nast¹pi³y wkrótce potem z resztkami super mutantów.}
{238} {} {Nienawidzê twojego Bractwa. Jesteœcie zwyk³ymi najeŸdŸcami.}
{239} {} {Nie jesteœ pierwsz¹ ani ostatni¹ osob¹, która tak myœli. Ale w obliczu zagro¿eñ, takich jak super mutanty czy szpony œmierci, ogólna populacja jest bezsilna. Pustkowia potrzebuj¹ Bractwa, czy ci siê to podoba, czy nie.}

{240} {} {Wiesz dok¹d zmierzaj¹ super mutanci?}
{241} {} {Oni sami tego nie wiedz¹. Kapitan obieca³ im, ¿e przejmie jak¹œ bogat¹ ziemiê i stworzy tam pañstwo super mutantów.}
{242} {} {Próbowa³eœ st¹d uciec?}
{243} {} {Ju¿ straci³em swoj¹ szansê. Dooko³a pustynia, wiêc mutanci z ³atwoœci¹ mnie dogoni¹. A nawet jeœli uda³oby mi siê opuœciæ fortecê, nie wiem czy trafi³bym do Lost Hills. Nawet nie wiem, gdzie jesteœmy.}
{244} {} {Jesteœmy na pustyni Sonora.}
{245} {} {Serio? Czyli nie wszystko stracone. O ile wiem, w Rocky Point jest placówka, mog¹ mnie tam przyj¹æ.}
{246} {} {Wiêc na co czekasz?}
{247} {} {Platforma musi zostaæ najpierw unieruchomiona. Na najni¿szym poziomie znajduje siê reaktor, który zasila ca³y system. Jeœli go wy³¹czysz, platforma nie bêdzie mog³a siê ruszyæ.}
{248} {} {Zajmê siê tym.}
{249} {} {Reaktor zniszczony.}

{250} {} {Reaktor zniszczony. Czas wysiadaæ.}
{251} {} {Jako in¿ynier mam ochotê p³akaæ, gdy taki sprzêt jest ten jest niszczony. Ale inaczej byæ nie mo¿e. Jest ma³o prawdopodobne, aby mutanci byli w stanie naprawiæ platformê. A na œrodku pustyni nie stanowi¹ dla nikogo zagro¿enia.}
{252} {} {ChodŸmy.}
{253} {} {Kluczem jest teraz nie zwracaæ na siebie uwagi.}
{254} {} {ChodŸmy.}
{255} {} {Jesteœ wolny.}
{256} {} {Nie wiem, jak dotrê do moich braci w Rocky Point. Czas przypomnieæ sobie wszystko, czego nauczy³em siê w Lost Hills. Dziêkujê Ci. Jeœli prze¿yjê, poinformuje o Tobie zakon.}
{257} {} {Mi³ej podró¿y.}
{258} {} {Przepraszam kolego, ale nie mogê pozwoliæ ci odejœæ. W koñcu wy, Bractwo Stali, jesteœcie z³em wcielonym. Zabijê ciê, tak jak zabi³em wszystkich twoich towarzyszy w Puerto Penasco!}
{1258} {} {Przepraszam kolego, ale nie mogê pozwoliæ ci odejœæ. W koñcu wy, Bractwo Stali, jesteœcie z³em wcielonym. Zabijê ciê, tak jak zabi³em wszystkich twoich towarzyszy w Puerto Penasco!}
{259} {} {Wszyscy mutanci nie ¿yj¹. Jesteœ wolny.}
{260} {} {To by³o mocne. Ta rzecz nie zajdzie daleko bez mutantów. I dobrze. Ech, chcielibyœmy mieæ wiêcej ¿o³nierzy takich jak ty podczas Wielkiej Wojny z mutantami.}
{261} {} {ChodŸmy.}