{100} {} {Widzisz Meksykanina.}
{101} {} {Widzisz Meksykanina. Znik¹d pojawi³ siê na œrodku pustyni.}
{102} {} {Muchas gracias.}

{200} {} {Muchas gracias. (W nagrodê daje ci czyst¹ wodê) Aquí tiene, amigo.}
{1200} {} {Muchas gracias. (W nagrodê daje ci czyst¹ wodê) Aquí tiene, amiga.}
{201} {} {Nie mówisz po angielsku?}
{202} {} {Iigls? No.}
{203} {} {Rozumiem. W takim razie powodzenia.}
{204} {} {De nada. Swoj¹ drog¹ sk¹d jesteœ?}
{205} {} {Jestem z Hermosillo. Tutaj w pobli¿u nie ma innych miast. Chocia¿ nie mo¿na tego nazwaæ miastem.}
{206} {} {Co robisz na œrodku pustyni?}
{207} {} {Zwiad. Armia musi wiedzieæ, gdzie s¹ Ÿród³a wody lub coœ innego. Niestety, nie ma tu nic wartoœciowego - tylko pustynia i gigantyczne owady. Myœla³em, ¿e jestem skoñczony. Spotkanie z tob¹ jest wielkim sukcesem.}
{208} {} {Rozumiem. W takim razie powodzenia.}
