{100} {} {Widzisz super mutanta.}
{101} {} {Widzisz wielkiego super mutanta.}
{102} {} {}

{120} {} {Za Stwórcê!}
{121} {} {Nienawidzê, kiedy jakiœ cz³owiek siê na mnie gapi.}

{150} {} {Czy jesteœmy ju¿ w Teksasie?}
{151} {} {Nie, Kapitan mówi, ¿e nadal jesteœmy w Arizonie.}
{152} {} {kwi! Czo³gamy siê jak beznogi ghul z pi³¹ ³añcuchow¹ w ty³ku.}
{153} {} {Nie mo¿emy jechaæ szybciej, to niebezpieczne dla fortecy.}
{154} {} {Nie chcê czekaæ! Kapitan obieca³ nam wspania³¹ bitwê i przejêcie ziemi.}
{155} {} {Przypomnij mi, dlaczego opuœciliœmy Mariposê?}
{156} {} {Pamiêtam. Nie jestem g³upi. Ale Mistrz nie zgodzi³ siê.}
{157} {} {Tak. Ale Mistrza ju¿ nie ma...}
{158} {} {Arrrr! Nie musieliœmy wyje¿d¿aæ, mogliœmy walczyæ!}
{159} {} {Ponieœliœmy zbyt wiele ofiar. Kapitan wie, co robi.}
{160} {} {Tak, Kapitan teraz dowodzi. Ale ja te¿ mogê byæ kapitanem!}
{161} {} {I co byœ zrobi³?}
{162} {} {Wróci³bym i przej¹³ twierdzê Lost Hills. I zburzy³bym po drodze wszystkie miasta.}
{163} {} {Dlatego nie jesteœ kapitanem. Kapitan jest m¹dry. Ty jesteœ g³upi.}
{164} {} {Cisza! Nie jestem g³upi!}
{165} {} {Niewa¿ne, i tak Kapitan tu dowodzi.}
{166} {} {kwi!}
