{100} {} {Widzisz super mutanta.}
{101} {} {Widzisz wielkiego super mutanta.}

{110} {} {Chcê jeœæ.}
{111} {} {Czy ty te¿ jesteœ g³odny?}
{112} {} {Jeœli zaraz czegoœ nie zjem, zabijê kogoœ.}
{113} {} {Mo¿e sprawdzimy nasz¹ si³ê?}
{114} {} {Za³oœni ludzie wymr¹. Przetrwam ich wszystkich.}
{115} {} {Mistrz s³yszy moje modlitwy.}
{116} {} {Kto przekrêci³ gaz?}
{117} {} {Nienawidzê, kiedy ludzie siê na mnie gapi¹.}
{118} {} {Który mamy teraz rok?}
{119} {} {Kiedy opuœcimy tê pustyniê?}

{120} {} {Za Stwórcê!}
