{100} {} {Widzisz Freda Stadtmallera.}
{101} {} {Widzisz ojca w prostym i ascetycznym stroju.}
{102} {} {Do widzenia, moje dziecko.}

{200} {} {Pozdrowienia, mój synu. Nie s¹dzi³em, ¿e spotkam mê¿czyznê na œrodku pustyni. Zgubi³eœ siê? Potrzebujesz pomocy?}
{1200} {} {Witaj, moje dzieciê. Nie s¹dzi³em, ¿e spotkam kobietê na œrodku pustyni. Zgubi³aœ siê? Potrzebujesz pomocy?}
{201} {} {Kim jesteœ?}
{202} {} {Jestem Ojciec Fred Stadtmaller. I podró¿ujê po Arizonie w poszukiwaniu tych, których dusza potrzebuje mojej pomocy - rannych, chorych, na wpó³ martwych.}
{203} {} {Mi³o ciê poznaæ, ojcze.}
{1203} {} {Mi³o ciê poznaæ, ojcze.}
{204} {} {Nie jesteœ moim ojcem.}
{205} {} {O nie, nie. Oczywiœcie, nie jestem twoim ojcem. Ojcze Swiêty - tak od czasów staro¿ytnych nazywano ludzi mojej profesji. Przepraszam, jeœli w jakikolwiek sposób ci to przeszkadza.}
{206} {} {Ok.}

{210} {} {Czy jest coœ, co mogê dla ciebie zrobiæ, moje dziecko?}
{211} {} {Nie, jakoœ to rozwi¹¿ê bez boskiej interwencji. Do zobaczenia, ojcze.}

{220} {} {Chcia³bym na razie z tob¹ porozmawiaæ.}
{221} {} {Oczywiœcie. Co chcesz wiedzieæ?}
{222} {} {Wrócimy trochê?}
{223} {} {Kim jesteœ?}
{224} {} {Nazywam siê Fred Stadtmaller. Jestem zaanga¿owany w g³oszenie S³owa Bo¿ego na tych ziemiach. Tak jak kap³ani Koœcio³a katolickiego robili to przed Wielk¹ Wojn¹... Niestety wielu ju¿ o tym zapomnia³o i widzi we mnie po prostu dziwaka.}
{225} {} {Jeœli masz pytanie, proszê.}
{226} {} {Kto nada³ ci tê rangê, kap³anie?}
{227} {} {To by³o w zakonie klasztornym na przedmieœciach Phoenix. Jeszcze zanim Phoenix ugrzêz³o w otch³ani niezgody, a zakon osiad³ w Katedrze Swiêtego Ognia i zacz¹³ ingerowaæ w œwiatowe ¿ycie.}
{228} {} {Wiêc jesteœ z koœcio³a Ognia? Dlaczego opuœci³eœ swoj¹ katedrê?}
{229} {} {Nie zgadzamy siê z obecnym w³adc¹ katedry. Wczeœniej nasz ma³y koœció³ nie zabiega³ o w³adzê ani bogactwo. Nie anga¿owaliœmy siê w sprawy wielkich miast. Pomagaliœmy tylko cierpi¹cym i zbieraliœmy staro¿ytne relikwie.}
{230} {} {Kontynuuj.}
{231} {} {Ale w katedrze zasz³y wielkie zmiany, nie mogê d³u¿ej nieœæ Mszy w tej masie z³a i wystêpku. Teraz odprawiam Msze tak, jak wczeœniej by j¹ prowadzili mnisi z zakonu. Oznacza to, ¿e kontynuujê stare tradycje.}
{232} {} {Zaprawdê, twoje czyny s¹ godne podziwu, Ojcze.}
{233} {} {Nie s¹dzê, ¿eby zakon tolerowa³ szalonych fanatyków.}

{240} {} {Jak nauczy³eœ siê kontrolowaæ tego ¿elaznego ptaka?}
{241} {} {Staro¿ytne ksiêgi przechowuj¹ wiedzê nawet o lotnictwie... Ale o czym ja mówiê, jeœli Phoenix i inne osady ¿y³y przy œwiecach kilka lat temu.}

{250} {} {Tak, potrzebujê twojej pomocy.}
{251} {} {Pomyœl najlepiej, jak potrafisz, czekaj¹ na mnie. Nied³ugo opuszczê to miejsce i mo¿emy ju¿ nigdy siê nie zobaczyæ.}
{252} {} {W³aœciwie to chcia³bym z tob¹ porozmawiaæ.}
{253} {} {Wiêc nie bêdê ciê zatrzymywaæ, ojcze.}
{254} {} {Potrzebujê leczenia.}
{255} {} {Twoje cia³o jest teraz w idealnym porz¹dku. Nie jestem pewien co do duszy. Ale bêdziesz musia³ sobie z tym poradziæ samodzielnie. Czas siê œpieszyæ - w kaplicy Mariackiej czekaj¹ na mnie chore dzieci.}
{256} {} {Adios, Santo Padre.}
{257} {} {Chcê pokutowaæ, ojcze. W mojej przesz³oœci pope³ni³em wiele grzechów.}
{258} {} {Nie uwolniê ciê od ich ciê¿aru. Ale mogê to u³atwiæ. Padnij na kolana, moje dziecko...}
{259} {} {Dziêki, ojcze.}
{260} {} {Potrzebujê wszystkich twoich rzeczy. No, zdejmij wszystko, co masz. Zdejmij te¿ ubranie.}
{261} {} {Niech Swiêty Józef ci wybaczy...}
{262} {} {Zamknij siê.}
{263} {} {Jestem zmêczony towarzystwem kaktusów i chcê wróciæ do ludzi. Czy mo¿esz mnie przenieœæ na swoim ¿elaznym ptaku?}
{1263} {} {Jestem zmêczona towarzystwem kaktusów i chcê wróciæ do ludzi. Czy mo¿esz mnie przenieœæ na swoim ¿elaznym ptaku?}
{264} {} {Oczywiœcie. To nie zajmie du¿o czasu.}
{265} {} {Gdzie mogê siê udaæ?}
{266} {} {Hmm. Wszystko zale¿y od tego, czego pragnie twoja dusza.}
{267} {} {Daj mi trochê czasu do namys³u.}
{268} {} {Ona chce zemsty za moj¹ rodzinê. Zabrano ich na wschód od Villi.}
{269} {} {Niech tak bêdzie. Myœlê, ¿e musisz dostaæ siê do Garage City lub Flagpool.}
{270} {} {Leæmy to Garage City.}
{271} {} {Poleæmy do Flagpool.}
{272} {} {Nie, nie teraz.}
{273} {} {Teraz potrzebujê tylko dobrej broni i amunicji. Zarobiê dziêki temu dodatkowe pieni¹dze na mój chleb powszedni.}
{274} {} {Wiêc droga z pewnoœci¹ zaprowadzi ciê do Phoenix. To najwiêksze i najbardziej rozwiniête miasto w promieniu wielu kilometrów.}
{275} {} {Leæmy do Phoenix.}
{276} {} {Chcê tylko osiedliæ siê w jakims cichym miejscu.}
{277} {} {Znam takie na œrodku pustyni Sonora. Nie bez powodu nazywa siê go Casa Nueva. To prawdziwa oaza poœrodku pustyni.}
{278} {} {Poleæmy do Casa Nueva.}
{279} {} {Marzê o odkrywaniu nowych œwiatów.}
{280} {} {W takim razie mo¿esz udaæ siê na po³udnie, w g³¹b Meksyku.}
{281} {} {Poleæmy na po³udnie, do najbli¿szego meksykañskiego miasta.}