{100} {} {Widzisz skrybê.}
{101} {} {Widzisz jednego z urzêdników Bractwa Stali.}
{102} {} {Jeszcze raz dziêkujê.}

{200} {} {Hej, dziêki za pomoc. Bandyci mieli nadziejê, ¿e wyci¹gn¹ ze mnie informacje o Bractwie. Ale dziêki Tobie nic z tego.}
{201} {} {Co to za Bractwo?}
{202} {} {Och, nie wiesz? Jest to staro¿ytny zakon poœwiêcony zachowywaniu i badaniu staro¿ytnych technologii. Nasza forteca znajduje siê w starym porcie na ruinach Puerto Penasco.}
{203} {} {Rozumiem.}
{204} {} {Jeszcze raz dziêkujê za uratowanie mnie. Kiedy wrócê do twierdzy, na pewno opowiem tam o Tobie. Zajrzyj tam, jeœli znajdziesz siê w pobli¿u.}
{205} {} {Ok. Do zobaczenia.}
{206} {} {Nie mogê przejœæ obojêtnie bez pomocnej d³oni dla mojego brata.}
{207} {} {Nienawidzê Bractwa! Byœcie wszyscy zdechli!}