{100} {} {Widzisz niewolnika.}
{101} {} {Widzisz wyczerpanego niewolnika. Jego rêce pokryte s¹ krwawymi ranami, a ramiona sine od lin.}
{102} {} {Ta osoba nie mo¿e mówiæ.}

{110} {} {Ooh...}
{111} {} {Fuj...}
{112} {} {Ech...}
{113} {} {Uff...}
{114} {} {Co?}
{115} {} {Wynoœ siê st¹d.}
{116} {} {Nie rozmawiaj ze mn¹.}
{117} {} {Wola³bym ¿eby mnie zastrzelili.}
{118} {} {}
{119} {} {}
