{100} {} {Widzisz kuratora.}
{101} {} {Widzisz mê¿czyznê w szacie o wyzywaj¹cym kolorze. Rozgl¹daj¹c siê po konwoju, wydaje siê, ¿e wznosi siê on ponad ca³y œwiat.}
{102} {} {Ta osoba nie chce z tob¹ rozmawiaæ.}

{200} {} {Spokojny podró¿nik w tych stronach? Co za niespodzianka. Ale nie potrzebujemy dodatkowego towarzystwa. I nie przeszkadzaj nam ani naszym niewolnikom. Czy to dla ciebie jasne? No to idŸ w³asn¹ drog¹.}
{201} {} {Czy mogê zadaæ pytanie?}
{202} {} {Dlaczego bracia nie udzielaj¹ informacji?}
{203} {} {Nie wyjdê st¹d bez odpowiedzi.}
{204} {} {Rozumiem. Wychodzê.}

{205} {} {Szkoda, ¿e twoje myœlenie jest tak nieistotne jak pojedyñczy atom w j¹drowym ³onie. Bêdziemy musieli ciê dzieliæ, a¿ ca³kowicie znikniesz!}
{206} {} {Co niesiecie...}
{207} {} {Jeœli naprawdê jesteœ bratem Ognia, powinieneœ wiedzieæ, ¿e jeœli nie jesteœ wtajemniczony w najwa¿niejsze sprawy, to nie jesteœ godzien.}
{208} {} {Wiêc mogê zadaæ pytanie?}
{209} {} {Wydajesz siê byæ osob¹ dobrze oczytan¹. Mimo to nie chcesz dzieliæ siê swoj¹ wiedz¹.}

{210} {} {Tylko jedno.}
{211} {} {Co niesiecie?}
{212} {} {Staro¿ytny... artefakt. To zbyt wa¿ne, aby rozmawiaæ o tym z niewtajemniczonymi.}
{213} {} {Kim jesteœcie?}
{214} {} {Ze wszystkich pytañ wybierasz najbardziej bezsensowne. To moi najemnicy. To s¹ moi niewolnicy. A ja kierujê ca³ym tym konwojem.}
{215} {} {Czy nie jest Ci gor¹co w tej sutannie na œrodku pustyni?}
{216} {} {(szczerz¹c siê) Nie. Syntetyczne w³ókno i kompresor p³ynu kapilarnego sprawiaj¹, ¿e sutanna jest idealna na pustyniê.}
{217} {} {Chcia³bym dostaæ siê do najbli¿szego miasta. Wska¿esz mi drogê?}
{218} {} {Hmm? (unosi tajemniczo brew)}
{219} {} {Uch, dziêkujê za odpowiedŸ.}
{220} {} {To wszystko? Spodziewa³em siê wiêcej.}
{221} {} {(pokazuje miasto Flagpool na twojej mapie)}
{222} {} {(pokazuje Phoenix na twojej mapie)}
{223} {} {(pokazuje miasto Tu-San na twojej mapie)}
{224} {} {Koniec z pytaniami. OdejdŸ, jeœli twoje nêdzne ¿ycie jest dla ciebie coœ warte.}
{225} {} {Umieram z pragnienia! Daj mi ³yk wody!}
{226} {} {Ratowanie bezwartoœciowego ¿ycia nie jest moim celem. Ale z drugiej strony ka¿da konwencja jest cenna dla odrodzenia œwiata. Wypij ³yk tej najczystszej wody. I powiedz wszystkim, których spotkasz, ¿e Wyznawcy Ognia daj¹ wodê ka¿demu potrzebuj¹cemu... ka¿demu, kto na ni¹ zas³uguje.}
{227} {} {Nie bêdê traciæ czasu na ludzi, którzy chc¹ rozmawiaæ, ale nie chc¹ s³uchaæ. IdŸ st¹d.}