{100} {} {Widzisz Cyberpsychola.}
{101} {} {Widzisz oszala³ego Blacharza, którego umys³ przejê³a technologia.}

{110} {} {Co za ból g³owy!}
{111} {} {Zatrzymaj te liczby! Nie zniosê tego d³u¿ej!}
{112} {} {Dlaczego? Dlaczego? Dlaczego?}
{113} {} {Liczby! Wszêdzie dooko³a liczby!}
{114} {} {Program ka¿e mi zabiæ.}
{115} {} {Jestem maszyn¹, jestem maszyn¹, NIE jestem cz³owiekiem...}
{116} {} {Ten g³os w mojej g³owie... uniemo¿liwia mi uruchomienie programu!}
{117} {} {Jestem tylko zmienn¹ w du¿ym programie. Nie przeszkadzaj mu w pracy!}
{118} {} {Ingerowa³eœ w mój program!}
{119} {} {Musisz zostaæ usuniêty z bazy danych!}