{100} {} {Widzisz Franka.}
{101} {} {Widzisz mieszkañca Krypty. Wygl¹da doœæ czysto i schludnie w porównaniu z jakimkolwiek innym cz³owiekiem z zewn¹trz.}

{200} {} {P-Proszê, nie bij nas! Jesteœmy pokojowymi ludŸmi i nie chcemy problemów.}
{201} {} {Dlaczego siê mnie boisz? Nie zrobi³em nic z³ego.}
{1201} {} {Dlaczego siê mnie boisz? Nie zrobi³am nic z³ego.}
{202} {} {Wiêc przestañ beczeæ, to mnie denerwuje.}
{203} {} {Wiêc... nie jesteœ bandyt¹?}
{204} {} {Nie, jestem }
{205} {} {. A ty kim jesteœ?}
{206} {} {Jestem Frank. Odk¹d zmar³ dozorca, wszystkim tu kierujê. Ale jest Ÿle.}
{207} {} {Dlaczego tak mówisz?}
{208} {} {Ta stara Krypta rozpada siê przy najmniejszym dotkniêciu. System podtrzymywania ¿ycia nie dzia³a, generator nie dzia³a z pe³n¹ wydajnoœci¹. I nie wiemy, jak to naprawiæ.}
{209} {} {Tak, niez³a katastrofa.}
{210} {} {I to twój problem? Ugh!}
{211} {} {Poza tym na zewn¹trz czeka kilku bandytów. W ci¹gu ostatnich kilku miesiêcy przeprowadzili kilkanaœcie nalotów, aby zaj¹æ Kryptê. Na razie powstrzymuj¹ ich du¿e drzwi, ale z takimi problemami sami wkrótce wyjdziemy na zewn¹trz, aby siê tu nie udusiæ. Nawet bojê siê wyobraziæ sobie, co nam zrobi¹. Z³apali ju¿ Freda i prawdopodobnie go torturuj¹.}
{212} {} {Mo¿e mogê pomóc?}
{213} {} {Có¿, jestem w trakcie rozwi¹zywania wszelkiego rodzaju problemów. Oczywiœcie nie na darmo.}
{214} {} {Naprawdê chcesz nam pomóc? To dla nas wielkie szczêœcie. Musimy naprawiæ generator i sprawiæ, by komputer w³¹czy³ system podtrzymywania ¿ycia.}
{215} {} {Ok, zajmê siê tym.}
{216} {} {To teraz zatrzymaj siê i obserwuj profesjonalistê w pracy.}

{220} {} {Czy przywróci³eœ ju¿ obs³ugê Krypty? Coœ na to nie wygl¹da. Musimy naprawiæ generator i sprawiæ, by komputer w³¹czy³ system podtrzymywania ¿ycia.}
{1220} {} {Czy przywróci³aœ ju¿ obs³ugê Krypty? Coœ na to nie wygl¹da. Musimy naprawiæ generator i sprawiæ, by komputer w³¹czy³ system podtrzymywania ¿ycia.}
{221} {} {Czas siê tym zaj¹æ. Do zobaczenia.}

{230} {} {Gdzie jest pomieszczenie z generatorem?}
{231} {} {Pomieszczenie z generatorem jest na koñcu korytarza, po naszej lewej stronie. Ale nie ma sensu siê tam pchaæ bez narzêdzi. Drzwi s¹ tam zamkniête.}
{232} {} {Do widzenia.}
{233} {} {Gdzie jest sala komputerowa?}
{234} {} {Sala komputerowa jest dalej w korytarzu po prawej stronie. Ale komputer nie dzia³a z powodu braku zasilania.}
{235} {} {Jak przywróciæ system podtrzymuj¹cy ¿ycie?}
{236} {} {Po uruchomieniu generatora u¿yj komputera, aby w³¹czyæ system podtrzymywania ¿ycia. Pozosta³o nam tylko naprawiæ oko robota, aby mog³o patrolowaæ Kryptê i odstraszaæ naszych wrogów.}
{237} {} {Opowiedz mi o tej Krypcie.}
{238} {} {Krypta zosta³a zbudowana sto lat temu. Nasi przodkowie prze¿yli tutaj wojnê nuklearn¹. Ale dalsze trwanie w Krypcie nie jest ju¿ mo¿liwe. Zamykamy siê tutaj tylko wtedy, gdy pojawia siê zagro¿enie.}

{240} {} {Dziêki za system podtrzymywania ¿ycia. Ju¿ czujemy siê lepiej!}
{241} {} {Zaden problem.}
{242} {} {Happy noises.}
{243} {} {Coœ jeszcze chcesz powiedzieæ?}
{244} {} {Mamy kilka przydatnych rzeczy. Masz, weŸ ten kombinezon. Jest trochê odrapany, ale nadal dobrze radzi sobie z si³ami natury.}
{245} {} {Mamy kilka przydatnych rzeczy. Masz, weŸ tê manierkê. Dozorca powiedzia³, ¿e przynosi³a mu szczêœcie, kiedy podró¿owa³ przez pustyniê. Z ni¹ nigdy nie zabrak³o mu wody, nawet w najgorêtszych i najbardziej suchych miejscach.}
{246} {} {Dziêki za to.}
{247} {} {Zartujesz sobie ze mnie? Za³osna manierka po tak ciê¿kiej pracy? Zdejmuj kombinezon!}
{248} {} {Ok! W porz¹dku! Nie wiem, jak bêdê dalej ¿yæ bez niego... Proszê, weŸ go.}
{249} {} {I nie patrz tak na mnie. To uczciwa zap³ata za tê pracê.}

