{100} {} {Widzisz mieszkañca Krypty.}
{101} {} {Widzisz mieszkañca Krypty. Wygl¹da niezwykle czysto i œwie¿o.}

{110} {} {Dzieñ dobry... a mo¿e mamy noc? Co siê dzieje na zewn¹trz?}
{111} {} {Proszê, nie krzywdŸ nas, jesteœmy pokojowymi ludŸmi!}
{112} {} {Mieszkamy w tej Krypcie od dawna. Sk¹d siê tu wzi¹³eœ?}
{113} {} {NajeŸdŸcy od miesiêcy próbuj¹ siê tu dostaæ.}
{114} {} {Jak dosta³eœ siê do œrodka?}
{115} {} {To nasz dom. Nie mamy dok¹d pójœæ.}
{116} {} {Nie prze¿yjemy na pustyni. Proszê, nie przeganiaj nas!}

{120} {} {Dziêki, ratujesz nas przed strasznym œwiatem zewnêtrznym!}
{121} {} {Dziêki za naprawienie systemu podtrzymywania ¿ycia.}
{122} {} {Ach, œwie¿e powietrze w Krypcie!}
{123} {} {Gdyby nie ty, musielibyœmy opuœciæ Kryptê.}
{124} {} {Jesteœ dobr¹ osob¹. Nie tak jak ci najeŸdŸcy.}
{125} {} {Wiesz, pierwszym stra¿nikiem Krypty by³ mê¿czyzna imieniem Van Buren.}
{126} {} {Dziêki za pomoc.}
{127} {} {Nie prze¿ylibyœmy pustyni.}
