{100} {} {Widzisz administratora.}
{101} {} {Widzisz porywczego goœcia. Mamrocze coœ pod nosem.}
{102} {} {Kopalnia jest tymczasowo zamkniêta. Miasto oszala³o bez Fabera!}
{103} {} {Oto, co siê dzieje, gdy podniesiesz na mnie g³os.}
{104} {} {Och, wreszcie moje ukochane jedzenie z bramina! Jedyna radoœæ w tym szalonym miejscu.}

# Losowe repliki
{110} {} {Debile! Idioci! Znowu, wszystkie terminy zawalone!}
{111} {} {Ile mam wam powtarzaæ g³upcy?!}
{112} {} {Beze mnie kopalnia siê po prostu zatrzyma.}
{113} {} {Mam najtrudniejsz¹ pracê.}
{114} {} {Szef nie rozumie, jak bardzo siê staram.}
{115} {} {Pracowa³bym jeszcze lepiej, ale ta p³aca zabija wszelkie ambicje.}
{116} {} {Ruda, ruda... Po co ja ¿yjê?}
{117} {} {Przepiszê kilka wpisów. Nikt siê nawet nie skapnie.}
{118} {} {Hmm... Ten raport wymaga poprawy.}
{119} {} {Nikt nie potrafi wykonaæ tej pracy lepiej ni¿ ja.}

{120} {} {Cholera, cholera, cholera! Kopalnia wysadzona, brakuje pracowników i co ja mam teraz zrobiæ?}
{121} {} {Co, szalony psychopata chce wysadziæ kopalniê?!}
{122} {} {Beze mnie te kopalnie przestan¹ dzia³aæ.}
{123} {} {Wszystko przepad³o...}
{124} {} {W porz¹dku... Teraz na pewno dostanê lanie.}
{125} {} {Mo¿e powinienem spakowaæ swoje rzeczy i uciec?}
{126} {} {Ruda, ruda... Znowu ruda. Zmêczony ju¿ tym jestem.}
{127} {} {Moje kapsle... Wkrótce miasto zubo¿eje.}
{128} {} {Kopalnia siê zawali³a, a raporty nigdzie nie dotar³y.}
{129} {} {Jeszcze trochê, a oszalejê.}

#Dialog
{200} {} {To jest administracja, a nie burdel! Czego?!}
{201} {} {Podnieœ na mnie swój g³os jeszcze raz, a wybijê ci wszystkie zêby.}
{202} {} {Nie denerwuj siê. Chcê tylko zadaæ kilka pytañ.}
{203} {} {Czy ty w ogóle wiesz, kim jestem?! Jestem administratorem tego miejsca! Mo¿na powiedzieæ, ¿e praw¹ rêk¹ samego Roya Fabera. Wa¿ysz siê mówiæ do mnie tym tonem? Wynoœ siê, zanim naprawdê siê wkurzê!}
{204} {} {Wystarczy. To bêdzie * naprawdê * boleæ, panie Wielki Szefie.}
{205} {} {(zmienia g³os) Ok, dobrze, trzymaj rêce przy sobie! Jest ma³o prawdopodobne, ¿e ludzie z karawany bêd¹ mnie szanowaæ, jeœli bêdê ca³y w sianiakach... (do siebie) Cholera, sk¹d siê bior¹ ludzie tacy jak ten...}
{206} {} {Wiêc jesteœ gotowy do rozmowy?}
{207} {} {Kilka pytañ?! Nie p³ac¹ mi za bezczynne gadanie. Robiê tu interesy. Rozumiesz? INTERESY! Wiêc miejmy to ju¿ za sob¹.}
{208} {} {Wiêc jesteœ gotowy, aby teraz porozmawiaæ?}

{209} {} {Rozumiem. Wychodzê.}
{210} {} {O co chodzi?}
{211} {} {Nic. Szczêœcia.}

#O mnie
{212} {} {Kim jesteœ i co tutaj robisz?}
{213} {} {Jestem administratorem! Powtarzam: ad-mi-ni-stra-to-rem! To znaczy, ¿e praca ca³ej tej kopalni spoczywa na moich barkach. Innymi s³owy, jestem g³ow¹ i twarz¹ tej firmy... no, oczywiœcie po Royu Faberze.}
{214} {} {Musisz mieæ ciê¿k¹ pracê, prawda?}
{215} {} {Oczywiœcie. A jak myœlisz, redneck? Zarz¹dzanie produkcj¹ rudy i uprawa zbó¿ to nie to samo.}
{216} {} {Wygl¹da na to, ¿e masz bardzo nerwow¹ pracê. I nikt tego nie rozumie oprócz Ciebie.}
{217} {} {(pauza) Nie masz pojêcia, jak bliskie jest to prawdy. W³o¿y³em w tê pracê wszystkie si³y i co mam w zamian? Za³osne kapsle, za które nie ma tu nawet co kupiæ. I stare mieszkanie bez udogodnieñ.}
{218} {} {[Pos³uchaj]}
{219} {} {Roy chyba mnie nie s³yszy. Po prostu nie rozumie mojej wagi i rozmiaru mojego wk³adu. Dla niego jestem takim samym pracownikiem jak reszta. (do siebie) Cholera, nie powinienem by³ zostawiaæ Phoenix dla tej dziury...}
{220} {} {To okropne. Ale pozwól mi zmieniæ temat.}
{221} {} {To... to nie twoja sprawa. I ani s³owa wiêcej na ten temat!}
{222} {} {Ok. Porozmawiajmy o czymœ innym.}
{223} {} {A kim jest ten Roy Faber?}
{224} {} {Naprawdê nie wiesz, czy tylko ¿artujesz? On * posiada * tê kopalniê. Jak ca³¹ koloniê.}

{230} {} {Czy odje¿dzaj¹ st¹d karawany do Phoenix?}
{231} {} {Tylko specjalna karawana towarowa. Tego szukasz, a mo¿e chcesz dowiedzieæ siê wiêcej? No to poszukaj lidera karawany w budynku naprzeciwko, jak chcesz.}
{232} {} {Ok.}
{233} {} {Niedawno zniknêli tu niewolnicy. Co o tym wiesz?}
{234} {} {Pracownicy od czasu do czasu gin¹. Niektórych przygniataj¹ osuwiska, innych po¿eraj¹ ogromne szczury. Nie ma nikogo, kto by bada³ ka¿d¹ sprawê. Poszukaj odpowiedzi w g³êbi kopalni, ale nie zawracaj mi ju¿ g³owy tym pytaniem.}
{235} {} {Co za szkoda.}
{236} {} {Dlaczego kopalnia jest zamkniêta?}
{237} {} {To koniec! Kopalnia jest zamkniêta. Poniewa¿ jakiœ kretyn wysadzi³ wejœcie. Bêdziemy usuwaæ to osuwisko przez co najmniej miesi¹c. A nie mamy na to ani œrodków, ani czasu - kopalnia zbankrutowa³a.}
{238} {} {Wygl¹da na to, ¿e ten "kretyn" przyprawi³ ciê o ból g³owy. Z przyjemnoœci¹ zostanê.}
{239} {} {A co z moim zadaniem?}
{240} {} {Zapomnij o tym. Kopalnia zosta³a zniszczona i nie mo¿na ju¿ dostaæ siê do œrodka.}
{241} {} {Có¿, bêdzie trzeba znaleŸæ inne Ÿród³o dochodu. Czeœæ.}
{242} {} {Barman poprosi³ mnie, ¿ebym ci to da³.}
{243} {} {Och, w koñcu moja ukochana potrawka z bramina! Jedyna radoœæ w tym szalonym miejscu. Mam nadziejê, ¿e niczego tu nie rusza³eœ. W przeciwnym razie bêdê BARDZO z³y. Na co siê gapisz? IdŸ, zrób coœ po¿ytecznego.}
{1243} {} {Och, w koñcu moja ukochana potrawka z bramina! Jedyna radoœæ w tym szalonym miejscu. Mam nadziejê, ¿e niczego tu nie rusza³aœ. W przeciwnym razie bêdê BARDZO z³y. Na co siê gapisz? IdŸ, zrób coœ po¿ytecznego.}
{244} {} {Ok.}
{245} {} {Wiesz, ¿e naczelnik bije wiêŸniów?}
{246} {} {Nie bêdê z tob¹ o tym rozmawiaæ!}
{247} {} {Wow, nie denerwuj siê tak...}

# Zadania w kopalniach
{250} {} {Faber powiedzia³ mi, ¿ebym poradzi³ sobie z problemami.}
{251} {} {Nie dotrzymujemy terminów, a ci idioci garnizonowi nie mog¹ znaleŸæ nowych pracowników. Robiê, co w mojej mocy, ale to nie wystarcza!}
{252} {} {Serio jest tak Ÿle? Co mo¿e pomóc zmieniæ sytuacjê?}
{253} {} {Wiert³o w kopalni siê zepsu³o. Naprawa go znacznie zmniejszy zapotrzebowanie na pracowników. Ktoœ musi znaleŸæ czêœci i naprawiæ ten kawa³ek ¿elaza.}
{254} {} {Co jeszcze?}
{255} {} {W kopalniach s¹ ogromne gryzonie. Rzucaj¹ siê na pracowników i gryz¹ sprzêt. Pierwszym krokiem do ich wytêpienia jest zabicie króla szczurów, to kurewsko niebezpieczne stworzenie.}
{256} {} {Rozumiem. Dam Ci znaæ, gdy coœ wymyœlê.}
{257} {} {Niewa¿ne.}
{258} {} {To by³o do przewidzenia.}

{260} {} {Odnoœnie robota wiertniczego.}
{261} {} {Czy zosta³ ju¿ naprawiony? Jeœli nie, to zejdŸ mi z oczu.}
{262} {} {Gdzie mogê znaleŸæ czêœci do tak niezwyk³ej maszyny?}
{263} {} {Oczywiœcie, wiem gdzie one s¹. Wiem? Nie wiem! SprawdŸ wszystkie wysypiska z³omu, które zdarzy³o Ci siê spotkaæ po drodze.}
{264} {} {Z maszyn¹ jest ju¿ wszystko w porz¹dku i jest gotowa do pracy.}
{265} {} {Nigdy bym siê nie spodziewa³, ¿e zwyk³y wieœniak poradzi sobie z tak delikatnym problemem. Có¿, oto twoja nagroda, 200 kapsli. Dobra robota.}
{266} {} {Ok.}
{267} {} {Poinformujê Fabera o twoich zas³ugach. Porozmawiaj z nim.}
{268} {} {Na pewno tam wpadnê.}
{269} {} {Jak tylko znajdê woln¹ chwilê.}

{270} {} {O królu szczurów.}
{271} {} {Co, jest martwy?}
{272} {} {No raczej. Bardziej martwy ju¿ nie bêdzie.}
{273} {} {Naprawdê? Powiedz mi teraz, dlaczego powinienem ci zaufaæ?}
{274} {} {Oto zêby potwora jako dowód.}
{275} {} {Jeœli chcesz siê pozbyæ tego stworzenia, daj mi materia³y wybuchowe do pomocy.}
{276} {} {Cholera, czy ty w ogóle wiesz, jak ciê¿k¹ mamy tu sytuacjê? Hmm... Ale szczur jest teraz wa¿niejszy. Oto klucz do magazynu w kopalni. M¹drze korzystaj z tych zapasów.}
{277} {} {Ok.}
{278} {} {To œmieszne. Nic ci nie dam.}
{279} {} {Móg³bym daæ ci materia³y wybuchowe, ale gdzieœ zgubi³em mój klucz. (œciszaj¹c g³os) Myœlê, ¿e zosta³ mi skradziony.}
{280} {} {Och, co za niespodzianka.}
{281} {} {Swietnie! Kocham odpowiednich ludzi na odpowiednich stanowiskach. Za zabicie tego stworzenia zosta³a przydzielona nagroda. Oto Twoje 200 kapsli. Polecam wszystkie wydaæ w lokalnym barze.}
{282} {} {Zdecydowanie.}
{283} {} {Z³odziej? Tutaj? Niech go szlag!}

{290} {} {Jak tam kopalnia?}
{291} {} {Kolejne pytanie.}
{292} {} {Rozumiem.}
{293} {} {Po sabota¿u ca³¹ energiê przeznaczamy na rêczne sprz¹tanie gruzu. To zajmie strasznie du¿o czasu i wysi³ku. Nie wiem, czy mamy wystarczaj¹co du¿o œrodków i cierpliwoœci.}
{294} {} {Po œmierci naszego szefa miasto sta³o siê niebezpieczne. A los kopalni nadal jest niejasny. Mo¿emy mieæ tylko nadziejê na lepsze.}
{295} {} {Po ucieczce wiêŸniów nie ma nikogo, kto móg³by wydobywaæ rudê. Terminy zosta³y ju¿ dawno przekroczone, a teraz jeszcze to...}
{296} {} {Dziêki twoim wysi³kom kopalnia jest na szczycie! Nawet nie wiem czy w tym sezonie sprzedamy ca³y uran. Tak trzymaj! Teraz mogê przywróciæ swój geniusz na w³aœciwe tory.}
{297} {} {Z³e czasy nasta³y. Terminy zawalone, brakuje pracowników, szef nie ufa podw³adnym. To nie najlepsze czasy dla kopalni - to na pewno.}
{298} {} {Czy jest coœ, w czym mogê ci pomóc?}
{299} {} {Produkcja zosta³a zatrzymana z powodu za³amania. Jeœli chcesz pomóc, to po prostu nie zadawaj g³upich pytañ.}
{300} {} {Kopalnia jest tymczasowo zamkniêta. Miasto oszala³o bez Fabera!}
{301} {} {Och, wygl¹da na to, ¿e macie tu powa¿ne k³opoty. Có¿, ja ju¿ nie mam tu nic do roboty. Czeœæ.}
{302} {} {A co z problemami z robotem wiertniczym i królem szczurów?}
{303} {} {Zapomnij o tym. Wychodzê st¹d.}
{304} {} {OK.}