{100} {} {Widzisz goœcia baru.}
{101} {} {Widzisz nerwowego kolonistê. Jest trochê pijany.}
{102} {} {Trzymaj siê ode mnie z dala.}
{103} {} {Czekaj, wystarczy! Jestem winny, przyznajê siê!}
{104} {} {Ach, teraz widzê w tobie potencja³.}
{105} {} {Ok, za³ó¿my, ¿e jesteœmy zmyœleni.}
{106} {} {Ok, mam ju¿ doœæ. A teraz idŸ i przynieœ mi drinka.}
{107} {} {Uh, s¹ tu tacy, którzy zak³adaj¹ lœni¹ce zbroje.}

{200} {} {Hej, ty! Ja ciê nie znam. Nowy w mieœcie? Wiêc postaw mi drinka. Teraz.}
{201} {} {Dlaczego mam ci postawiæ drinka?}
{1201} {} {Dlaczego mam ci postawiæ drinka?}
{202} {} {S³uchaj, nie chcê mieæ k³opotów, po prostu mi nie przeszkadzaj, dobrze?}
{1202} {} {S³uchaj, nie chcê mieæ k³opotów, po prostu mnie nie dotykaj, dobrze?}
{203} {} {Cholera.}

{204} {} {Poniewa¿ przed tob¹ stoi ¿ywe ucieleœnienie w³adzy i prawa w tym mieœcie! Pracujê dla samego Roya Fabera. Rozumiesz? Przynieœ mi wiêc drinka, albo wdasz siê w bójkê.}
{205} {} {Nie chcê k³opotów, nie dotykaj mnie.}
{206} {} {Wszystko, co mo¿esz zrobiæ, to sobie krzyczeæ. Nie dosta³eœ w ¿ebra przez d³ugi czas?}

{207} {} {Ha! Za³osny wioskowy. WyjdŸ z baru, dobrze Ci radzê. W tym mieœcie nie ma miejsca dla s³abeuszy takich jak Ty.}
{1207} {} {Ha! Za³osny wioskowy. WyjdŸ z baru na ulicê, dobrze Ci radzê. Tylko tam siê nadajesz.}
{208} {} {Dobra, dobra, cokolwiek powiesz. Ty tu jesteœ szefem.}
{209} {} {To by³o niemi³e. Chcia³eœ walki? Wiêc bêdziesz j¹ mia³!}

{210} {} {Coo? Jak ty do mnie mówisz, œmieciu! Zaraz bêdziesz mnie b³agaæ o litoœæ...}
{211} {} {Tylko nie w twarz...}
{212} {} {Swietnie, poka¿ mi, co potrafisz.}

{213} {} {Ja te¿ dla niego pracujê. Wiêc zamknij siê.}
{214} {} {(przez zaciœniête zêby) Cholera... (wraca do swojej butelki i spogl¹da na stó³ z przygnêbieniem)}
{215} {} {Tak i tak.}

{216} {} {Faber nie ¿yje! S³yszysz? Jest martwy!}
{217} {} {Tak, uh, s³yszê, uspokój siê...}
{218} {} {Zrobi³em coœ z czego mo¿na byæ dumnym. A ty upijasz siê w barze tylko dlatego, bo to jedyne co Ci zosta³o, prawda?}
{219} {} {Có¿, nie. Ja tylko... Ja... IdŸ do diab³a!}

{220} {} {Czego chcesz?}
{221} {} {Nic ju¿.}
{222} {} {Jak mo¿na siê by³o spodziewaæ.}
{223} {} {Spierdalaj.}
{224} {} {Chêtnie.}
{225} {} {Trzymaj siê ode mnie z dala!}
{226} {} {Nie zamierzam.}
{227} {} {Ch³opi z Villi s¹ przetrzymywani w wiêzieniu. Musz¹ zostaæ uwolnieni.}
{228} {} {Co?! Nigdy nie s³ysza³em bardziej szalonego pomys³u. Faber nie rozstanie siê tak po prostu ze swoimi wiêŸniami. I nawet nie myœl o ucieczce - tylko podpisa³byœ w ten sposób ich i swój w³asny wyrok œmierci.}
{229} {} {Powiedz mi o tym coœ wiêcej.}
{230} {} {Có¿, nawet jeœli wiêŸniowie uciekn¹, to obro¿e i tak ich zabij¹. Zaledwie kilka mil wolnoœci, a potem bum! - i nie ma g³owy.}
{231} {} {Jakie to okrutne.}
{232} {} {Co prawda obro¿e mog¹ zostaæ wy³¹czone. Ale tylko dwie osoby wiedz¹, jak to zrobiæ, Faber i Bystr. Wiêc nie masz prawie ¿adnych szans.}
{233} {} {Zobaczymy.}