{100} {} {Widzisz Joe.}
{101} {} {Widzisz barmana.}
{102} {} {Bar jest zamkniêty, wróæ rano.}
{103} {} {Zzz...}
{104} {} {Fajna zbroja. Ale do baru za³ó¿ coœ prostszego.}
{105} {} {Przepraszam, ale zakaz broni na widoku w barze. Taka zasada.}

# Plywajace repliki
{109} {} {S³ysza³eœ co siê dzieje na œwiecie?}

{110} {} {Wygl¹da to na ca³kiem niez³¹ umowê z Garage City.}
{111} {} {Cisza zapad³a na ulicach Garage City. Jakby nikt tam nigdy nie mieszka³.}
{112} {} {Faber i Garage City podpisali umowê. Myœlê, ¿e ka¿dy na tym dobrze wyjdzie.}

{113} {} {San Brahmin ma najlepsze miêso, ale przestali je sprzedawaæ.}
{114} {} {Mówi¹, ¿e w San Brahmin by³o du¿e zamieszanie. Ale chyba ju¿ wszystko jest w porz¹dku.}
{115} {} {Ci g³upi pasterze zamknêli wszystkie swoje szlaki handlowe z Phoenix.}

{116} {} {Ci kultyœci z po³udnia maj¹ coœ z g³ow¹.}
{117} {} {Koœció³ Swiêtego Ognia sp³on¹³. Co za ironia.}
{118} {} {Ci kultyœci z po³udnia maj¹ coœ z g³ow¹.}

{119} {} {Jest tu coraz wiêcej ludzi z po³udnia, a towarów mniej.}
{120} {} {Mówi¹, ¿e w Phoenix nie jest teraz spokojnie.}
{121} {} {Ech, chcia³bym jeszcze raz spojrzeæ na Wielkie Miasto.}

{122} {} {Ktoœ atakuje patrole na starym mieœcie.}
{123} {} {Nie mia³em pojêcia, ¿e za atakami na patrole stoj¹ Rangersi.}
{124} {} {Za kogo uwa¿aj¹ siê ci Rangersi?}

{125} {} {Faber wie, co robiæ, odbuduje miasto.}
{126} {} {Miastu bêdzie ciê¿ko bez Roya Fabera.}
{127} {} {Kopalnia znów dzia³a na pe³nych obrotach.}

{128} {} {Stra¿nicy zajêli siê handlem niewolnikami. To trochê niepokoj¹ce.}
{129} {} {WiêŸniowie uciekaj¹ przed stra¿nikami. Musisz byæ ostro¿ny.}
{130} {} {To pierwszy raz, kiedy widzê stra¿ników zwalniaj¹cych wiêŸniów.}

{131} {} {Ugh, czasami po prostu brakuje ci wystarczaj¹cej liczby cycatych s³u¿¹cych, ¿eby byæ szczêœliwym.}
{132} {} {To jest bar, a nie sklep.}
{133} {} {Chcesz coœ mocniejszego?}
{134} {} {Kolejna dostawa siê spóŸnia.}
{135} {} {To najlepszy alkohol na pó³noc od Phoenix.}
{136} {} {Nalaæ wiêcej?}

# Pierwszy dialog
{200} {} {Czeœæ.}
{201} {} {Czy mogê zadaæ kilka pytañ?}
{202} {} {Do widzenia.}
{203} {} {WejdŸ, zawsze jesteœ tu mile widziany.}
{204} {} {WejdŸ. Ale nie stwarzaj problemów.}

#Zapytania
{210} {} {Co chcesz wiedzieæ?}
{211} {} {Powiedz mi wiêcej.}
{212} {} {Powróæmy do baru.}
{213} {} {Czy mogê zadaæ kilka pytañ na inny temat?}
{214} {} {Cofnijmy siê trochê.}
{215} {} {Có¿, wybór jest ma³y. Kopalnia stale potrzebuje pracowników. A w garnizonie szukaj¹ ludzi do zadañ specjalnych.}

{220} {} {Gdzie mogê tutaj zarobiæ dodatkowe pieni¹dze?}
{221} {} {Có¿, wybór jest ma³y. Kopalnia stale potrzebuje pracowników. Garnizon szuka³ ludzi do zadañ specjalnych. Mogê te¿ daæ ci kilka drobnych zleceñ. Wybierz to, co Ci bardziej pasuje.}

{222} {} {Jestem tu od niedawna. Opowiedz mi o Flagpool.}
{223} {} {W takim razie musisz wiedzieæ, ¿e jest to kolonia pracy wed³ug œcis³ego re¿imu. G³ówne miejsca to garnizon na wschodzie i kopalnia uranu na pó³nocy.}
{224} {} {Opowiedz mi o kopalni.}
{225} {} {Ca³e miasto jest tu z jej powodu. Kolonia zosta³a stworzona od samego pocz¹tku do produkcji uranu. Kopalnia przynosi dobre dochody, ale ostatnio sprawy id¹ ciê¿ko z powodu braku pracowników.}
{226} {} {Opowiedz mi o wiêzieniu.}
{227} {} {Najemnicy Fabera za³o¿yli t¹ "zagrodê" wœród ruin i trzymaj¹ tam przestêpców. Zwo¿ono ich zewsz¹d, z ca³ego pustkowia. Teraz wiêŸniowie odpracowuj¹ tam swoje przestêpstwa, a kolonia rozwija siê dziêki ich pracy.}
{228} {} {Opowiedz mi o us³udze pocztowej.}
{229} {} {G³ówny oddzia³ jest w Phoenix. Zajmuj¹ siê dorêczaniem ma³ych paczek miêdzy osadami.}
{230} {} {Kr¹¿¹ pog³oski, ¿e szerzy siê tutaj niewolnictwo.}
{231} {} {Dam ci darmow¹ radê: nie mów wiêcej tego s³owa na g³os. Robotnicy sk³adaj¹ siê z przestêpców i peonów. Niektórzy odsiaduj¹ wyroki, a inni sp³acaj¹ swoje d³ugi. S¹ oczywiœcie te¿ zniewolone dzikusy, ale oni s¹ s³ugami, a nie niewolnikami.}
{232} {} {Po co trzymaæ by³ych przestêpców w areszcie?}
{233} {} {Do ciê¿kiej pracy. Wiele zosta³o wybudowane rêkoma wiêŸniów w tym miejscu. Bez nich budowa Flagpool by³aby znacznie trudniejsza.}
{234} {} {Czy uwa¿asz, ¿e tak mo¿na?}
{235} {} {Dlaczego nie! Wybudowaliœmy to miasto i dziêki tym wiêŸniom rozpoczeliœmy produkcjê. Czy w okolicy jest wiêcej takich piêknych miejsc jak to? Nie s¹dzê.}
{236} {} {Sk¹d masz ca³y ten alkohol?}
{237} {} {Och, te napoje s¹ robione w Phoenix i s¹ przywo¿one tu raz w miesi¹cu karawanami. Oczywiœcie tego napoju nie mo¿na porównaæ z przedwojennym, ale jest tani i ca³kiem niez³y.}
{238} {} {Chcê postawiæ kolejkê wszystkim obecnym.}
{239} {} {Taki gest bêdzie ciê kosztowaæ 50 kapsli.}
{240} {} {Cena nie ma znaczenia - nalej wszystkim!}
{241} {} {Ile? Obawiam siê, ¿e nie staæ mnie dzisiaj na tak¹ hojnoœæ.}
{242} {} {Nie, czekaj, najpierw muszê coœ wiedzieæ.}
{243} {} {To za drogo. Innym razem, gdzieœ w przysz³oœci, kiedyœ, za jakiœ czas.}
{244} {} {Niez³y pocz¹tek. Ludzie to doceni¹. Ale dam ci kilka rad - samo picie nie wystarczy, aby zdobyæ tutaj reputacjê.}
{245} {} {Zanim skoñczy siê mój drink, porozmawiajmy.}
{246} {} {Bêdê pamietaæ. Dobra, nadszed³ czas, abym zaj¹³ siê wa¿niejszymi rzeczami.}
{247} {} {Co s¹dzisz o Royu Faberze?}
{248} {} {Jest naszym liderem. Bez niego to miasto by nie istnia³o. (pochylaj¹c siê do ciebie i œciszaj¹c g³os) S³uchaj, to nie jest osoba o której chcesz rozmawiaæ za jej plecami. Jeœli chcesz ¿yæ, nie wymawiaj jego imienia bez powodu. Mam nadziejê, ¿e mnie rozumiesz.}
{249} {} {Jest naszym liderem. Bez niego to miasto by nie istnia³o.}

# Zeby króla szczurów z kopalni
{250} {} {Spójrz, to z¹b tego króla szczurów z kopalni.}
{251} {} {Powa¿nie? Niech mnie diabli, jeœli ten mutant nie jest wielkoœci bramina! Du¿o o nim rozmawiali... Pos³uchaj, sprzedaj mi go. Zap³acê 100 kapsli.}
{252} {} {Dlaczego potrzebujesz tych zêbów?}
{253} {} {Ok, weŸ to.}
{254} {} {Nie, zrobiê z tego amulet, aby przestraszyæ moich wrogów.}
{255} {} {Przemyœlê twoj¹ propozycjê.}
{256} {} {Taka atrakcja z pewnoœci¹ przyci¹gnie klientów.}
{257} {} {Ech, te twoje wiejskie przes¹dy... Nie powinieneœ rezygnowaæ z kapsli. Przemyœl to.}
{258} {} {(z³owieszczo siê uœmiecha) Teraz zamierzam zrobiæ na tym czymœ interes... A tak - twoje 100 kapsli.}
{259} {} {To dobra oferta.}
{260} {} {Zegnaj.}
{261} {} {Wygl¹da na to, ¿e nie jestem gotowy, aby o tym rozmawiaæ. Opowiedz mi o czymœ innym.}
{262} {} {Nie bojê siê nikogo. Ale jeœli tak, zmieñmy temat.}
{263} {} {WeŸ to za darmo. Ale nie zapomnij wspomnieæ o mnie w swoich opowieœciach.}
{264} {} {Oh-ho-ho, teraz siê zacznie. Na pewno nie chcesz nagrody? WeŸ przynajmniej butelkê piwa.}
{265} {} {Joe wygl¹da na szczêœliwego.}
{266} {} {Proszê, naprawdê potrzebujê lekarstw. Czy nie jesteœmy przyjació³mi?}
{267} {} {No dalej. Nie chcesz, ¿ebym siê wykrwawi³, prawda?}

# O handlu
{270} {} {Czym handlujesz?}
{271} {} {Alkoholem i przek¹skami. Czym jeszcze mo¿na handlowaæ w barze? Chocia¿ czasami muszê robiæ za ca³y sklep.}
{272} {} {Czy akceptujesz tylko kapsle?}
{273} {} {Tak. Sprzedawcy z po³udnia akceptuj¹ teraz tylko kapsle do butelek. Przedwojenne pieni¹dze zosta³y ca³kowicie wycofane z obiegu.}
{274} {} {Czy mo¿esz mi powiedzieæ, gdzie kupiæ lekarstwa?}
{275} {} {No có¿, tylko u karawany. Ale ja jestem pierwszym nabywc¹ wiêc wiesz...}
{276} {} {Nie mam ju¿ lekarstw.}
{277} {} {I tak prawdopodobnie nie bêdziesz ich potrzebowaæ. Lepiej sprzedaj mi je, zanim siê zepsuj¹.}
{278} {} {Hmm. W tych s³owach jest trochê prawdy. Oto, co mogê ci zaoferowaæ. (stawia na ladzie skromny zapas lekarstw)}
{279} {} {Uch, nie. Nawet w bezpiecznym miejscu, takim jak Flagpool, warto mieæ w pogotowiu kilka u¿ywek.}

{280} {} {Klient z moj¹ reputacj¹ zas³uguje na specjalne ceny. Nie s¹dzisz?}
{281} {} {Myœlê, ¿e siê zgadzam. Zarówno ja, jak i inni klienci z przyjemnoœci¹ ciê zobacz¹ w tym barze. Mo¿esz liczyæ na 20% rabatu.}
{282} {} {Swietnie. Co masz na dziœ?}
{283} {} {Mówi¹, ¿e jakiœ nieznajomy spowodowa³ wiele k³opotów w tym mieœcie. Mam nadziejê, ¿e d³ugo tu nie zostanie.}
{284} {} {Podnios³eœ ceny? Dlaczego?}
{285} {} {Tak, mamy „kryzys” handlowy. Jeœli nie podobaj¹ Ci siê ceny, poszukaj innego baru w tym mieœcie. Nawiasem mówi¹c, tutaj nie ma innego baru.}
{286} {} {Rozumiem.}

# Demontaz przy barze
{287} {} {Od dawna marzy³em, ¿e ktoœ poka¿e temu bezczelnemu najemnikowi jego miejsce. Proszê, weŸ piwo na mój koszt. Ale nie opuszczaj gardy. Garnizon na d³ugo zapamiêta tê historiê.}
{288} {} {Jakoœ sobie z tym poradzê. Dziêki za piwo.}
{289} {} {Tak, specjalne ceny... podwojone ceny.}

# O swoich krewnych w mieœcie
{290} {} {Szukam moich krewnych z wioski na zachodzie.}
{291} {} {Czy s¹ tutaj z w³asnej woli? Nie? Wiêc mog¹ byæ tylko w jednym miejscu - w zagrodzie dla wiêŸniów. IdŸ prosto g³ówn¹ ulic¹ na wschód.}
{292} {} {Dlaczego mówisz, ¿e mog¹ tylko tam byæ?}
{293} {} {Poniewa¿ nie pamiêtam nowych w mieœcie, ale ostatnio nast¹pi³o du¿e uzupe³nienie dzikich ciê¿ko pracuj¹cych w kopalni.}
{294} {} {Po co trzymaæ ludzi w zagrodzie?}
{295} {} {By pracowali w kopalni i zarabiali na miasto. Ca³a kolonia jest zmuszona do ciê¿kiej pracy.}
{296} {} {W takim razie powinienem iœæ do naczelnego dozorcy.}
{297} {} {Jak chcesz. Uwa¿aj na siebie i nie wpadaj w sza³. Faber ma kiepskie poczucie humoru, wielu siê go boi.}
{298} {} {Dziêkujê za pomoc. Muszê iœæ.}

# Tequila nie jest ju¿ sprzedawana
{300} {} {Gdzie jest normalny alkohol?}
{301} {} {Mówi¹, ¿e bimbrownik w Phoenix jest niedysponowany. Teraz muszê braæ ka¿dy alkohol, jaki mogê od karawan. Nawiasem mówi¹c, dlatego ceny musia³y zostaæ podniesione.}
{302} {} {Myœlê, ¿e znam tê historiê. Um, pa.}
{303} {} {Hmm, okropna historia. Muszê iœæ.}
{304} {} {Poka¿ mi, co masz.}
{305} {} {Swietnie, zobaczmy teraz, co mogê ci zaoferowaæ...}

# Quest - zwroc d³ug
{310} {} {Masz inne zlecenie?}
{311} {} {Jest jedno. Najemnik imieniem Davis jest mi winien sto kapsli. Przesta³em wpuszczaæ go do baru, ale szkodzi to interesom.}
{312} {} {Co sugerujesz?}
{313} {} {Jeœli zmusisz go do sp³aty d³ugu, oddam ci po³owê z tego.}
{314} {} {Ok. Za³atwiê to.}
{315} {} {To ryzykowna sprawa, sam siê tym zajmij.}
{316} {} {Pomyœlê o tym.}
{317} {} {Ok. Pamiêtaj, ¿e Davis ma 100 kapsli d³ugu, a Ty dostaniesz z tego 50.}
{318} {} {Bêdê pamietaæ.}
{319} {} {Oczywiœcie, nie ma problemu. Ale moja oferta jest nadal aktualna.}
{320} {} {Rozumiem.}
{321} {} {Myœl. Masz du¿o czasu, bo Davis nie œpieszy siê ze sp³at¹ d³ugu.}
{322} {} {Rozumiem.}
{323} {} {Chcê sp³aciæ d³ug.}
{324} {} {Naprawdê? Myœla³em, ¿e nie bêdziesz w stanie nic zrobiæ. Dziêkujê Ci. Daj mi 50 kapsli, reszta jest twoja, zgodnie z ustaleniami.}
{325} {} {Coraz bardziej lubiê brzdêk kapsli. Do zobaczenia póŸniej.}

#Automat
{330} {} {Ten automat nie dzia³a.}
{331} {} {Tak, wiem. Szkoda, by³a to dobra rzecz, przyci³ga³a klientów.}
{332} {} {Dlaczego nie dzia³a?}
{333} {} {Wygl¹da na to, ¿e coœ siê wypalilo. Nie ma co wymieniaæ, w tym mieœcie nie ma odpowiednich czêœci. Wydajesz siê du¿o podró¿owaæ, co? Jeœli znajdziesz coœ, co naprawi StarBall, zap³acê 50 kapsli.}
{334} {} {Zgoda.}

{335} {} {Swietnie.}
{336} {} {Najpierw chcê zapytaæ ciê o tê maszynê.}
{337} {} {Zmieñmy temat.}
{338} {} {Bywaj.}

{339} {} {To nie jest moja sprawa.}
{340} {} {Jak sobie ¿yczysz. Znajdê kogoœ innego.}
{341} {} {Wiesz, czego brakuje w Twoim barze?}
{342} {} {Nie, nie wiem, czego?}
{343} {} {Ja te¿ nie wiem. Dam ci znaæ, jak coœ wymyœlê.}
{344} {} {Patriotycznej flagi na œcianie. Mam akurat jedn¹.}
{345} {} {Dobry Bo¿e, te stare flagi ju¿ dawno przepad³y. Myœla³em, ¿e nie znajdê ¿adnej. I oto jesteœ. Oferujê wymianê. Dam ten karabinek za flagê Arizony. Jest w dobrym stanie, ale amunicja jest trudna do znalezienia, przynajmniej w tych okolicach. Umowa stoi?}
{346} {} {Flaga i tak mi siê nie przyda. Zamieñmy siê.}
{347} {} {Jeden œmieæ za to cacko? Nie, dziêkujê.}
{348} {} {Po zamkniêciu powieszê flagê na œcianie. Dziêkujê Ci.}
{349} {} {Powodzenia.}

{350} {} {O automacie.}
{351} {} {Co jest?}
{352} {} {Nie, nic.}
{353} {} {Sk¹d siê wziê³a tu ta maszyna?}
{354} {} {Stala w szafie na pocz¹tku. Wyci¹gn¹³em j¹, a wujek Tom wyczyœci³ j¹ z kurzu kilkoma ruchami i uruchomi³.}
{355} {} {Jakie s¹ zasady gry?}
{356} {} {U¿yj bocznych przycisków, aby odbiæ pi³eczkê, musisz zaliczyæ wszystkie szczeliny na punkty. Im d³u¿ej pi³ka pozostaje na boisku, a¿ trafi w „czarn¹ dziurê”, tym wiêcej punktów zdobywasz. Tylko b¹dŸ ostro¿ny, czasami cewki elektromagnetyczne mog¹ poraziæ pr¹dem.}
{357} {} {Czy s¹ jakieœ nagrody?}
{358} {} {To fajna gra. Obieca³em postawiæ darmowego drinka ka¿demu, kto zdobedzie 1000 punktów.}
{359} {} {Czy to w ogóle mo¿liwe?}
{360} {} {Jednemu z nich prawie siê uda³o. Zmar³ z wycieñczenia, brak³o mu kilka punktów.}
{361} {} {Uda³o mi siê naprawiæ StarBall.}
{362} {} {Rozumiem. Dobra robota. Oto twoje 50 kapsli i wiêcej piwa ode mnie.}
{363} {} {Czy mogê w to zagraæ?}
{364} {} {Spróbuj. Tylko tego nie zniszcz.}
{365} {} {Zaden problem.}
{366} {} {Rozumiem. Dobra robota. Oto Twoje 50 kapsli.}
{367} {} {Wow! Pokonanie tej maszyny to jest coœ. Proszê, weŸ tego drinka na mój koszt. Po tym wysi³ku powinieneœ odci¹¿yæ g³owê.}
{368} {} {Dziêki.}
{369} {} {Mog³oby byæ coœ wiêcej.}
{370} {} {Chyba ju¿ pójdê.}

{380} {} {Czy to jakiœ wisiorek?}
{381} {} {Tak. Jeden z mieszkañców sprzeda³ go, aby sp³aciæ d³ug. Wygl¹da na to, ¿e to czyste z³oto.}
{382} {} {Znam kobietê, która kiedyœ by³a jego w³aœcicielem. A ona mówi, ¿e odebrano jej ten wisiorek.}
{383} {} {Có¿... S³uchaj, to nie jest mój problem. Szczerze to rozumiem. Jeœli chcesz go, daj coœ w zamian.}
{384} {} {Daj mi wisiorek. Natychmiast!}
{385} {} {Jesteœ w z³ym mieœcie, kochanie. Zap³aæ lub wyjdŸ na ulicê.}
{386} {} {Ok. Jak sobie ¿yczysz.}
{387} {} {Nie interesuje mnie to.}
{388} {} {Teraz tego po¿a³ujesz!}

{390} {} {Barman w Garage City potrzebuje drinków.}
{391} {} {Wydawa³o mi siê, ¿e to miasto chyli siê ku upadkowi. Chwileczkê... Och, tak, to prawdopodobnie z powodu plemienia dzikusów. Zbuntowali siê i nie pozwalaj¹ ju¿ karawanom przemierzaæ ich ziemi.}
{392} {} {Poza alkoholem w Garage City nie ma nic relaksuj¹cego.}
{393} {} {Có¿, mogê podzieliæ siê nadwy¿k¹. Ale w¹tpiê, ¿eby barman utrzyma³ siê tam d³ugo. Przecie¿ dostawa kurierem jest droga.}
{394} {} {Nie s¹dzê, ¿eby Garage City by³o stracone. Powiem barmanowi o Twojej zgodzie.}
{395} {} {Swietnie. Ale porozmawiajmy trochê wiêcej o gorza³ce, zanim wrócê do Garage City.}

{400} {} {Czy dostarczy³eœ ju¿ lunch administratorowi kopalni?}
{1400} {} {Czy dostarczy³aœ ju¿ lunch administratorowi kopalni?}
{401} {} {Jeszcze nie, proszê pana.}
{402} {} {Poœpiesz siê, zanim skoñczy Ci siê czas.}
{403} {} {Dobrze.}
{404} {} {Nie, proszê pana.}
{405} {} {Od razu podejrzewa³em, ¿e nie mo¿na ci ufaæ. Wynoœ siê z mojego baru.}
{406} {} {. ... .}
{407} {} {Straszna sprawa. Okaza³o siê, ¿e administrator zosta³ zabity. Ca³a kopalnia p³onie z tego powodu.}
{408} {} {Och... a wiêc to prawda... Przykro mi to s³yszeæ. Szkoda, dobrze p³aci³ za obiady. Miejmy nadziejê, ¿e nowy administrator bêdzie kontynuowa³ t¹ wspania³¹ tradycjê. Jeœli chodzi o Ciebie, mo¿esz wzi¹æ obiad jako zap³atê.}
{409} {} {Nie tego chcia³em. Chocia¿ z drugiej strony nie umrê z g³odu.}
{410} {} {Lunch zamiast obiecanych kapsli? Módl siê, aby garnizon nie dowiedzia³ siê o twojej chciwoœci, draniu.}
{411} {} {Tak, zamówienie zosta³o dostarczone na czas.}
{412} {} {Dobra robota. Oto twoje kapsle. Znalaz³em ju¿ nowego kuriera, wiêc Twoje us³ugi nie s¹ ju¿ potrzebne. Ale i tak mo¿esz tu zostaæ.}
{413} {} {Do widzenia, Joe.}

{420} {} {Opowiedz mi o moim pierwszym zleceniu.}
{421} {} {Musisz zanieœæ obiad do administratora w kopalni. Czasami sk³ada zamówienie i dobrze za to p³aci, ale mój kurier akurat zachorowa³. Za dostarczenie zap³acê, ale trzeba to zrobiæ w ci¹gu najbli¿szych szeœciu godzin.}
{422} {} {Nie, mam pilniejsze sprawy.}
{423} {} {Ok, zrobiê to.}
{424} {} {Wiêc poœpiesz siê. Lunch jest w tym pude³ku na kolacjê. S³uchaj, nie jedz tego po drodze.}
{425} {} {Spoko.}
{426} {} {Kto jest Twoim kurierem?}
{427} {} {To m³ody ch³opiec. Nie wiem, co siê z nim sta³o, ale jego ojciec nie pozwala nikomu go zobaczyæ.}
{428} {} {Co siê sta³o z Twoim kurierem?}

{430} {} {Masz jakieœ inne zajêcie?}
{431} {} {Tak. Czekam na przesy³kê miêsa z obozu myœliwych. Ale spóŸniaj¹ siê i nie odpowiadaj¹ przez radio. Nie wiem, co mog³o siê tam wydarzyæ. Musisz udaæ siê do obozu i ustaliæ przyczynê opóŸnieñ. A jeœli potrzebuj¹ pomocy?}
{432} {} {Ok, zrobiê to.}
{433} {} {Przepraszam, ale nie mogê teraz traciæ zbyt wiele czasu. Myœlê, ¿e poradz¹ sobie beze mnie.}
{434} {} {Obóz Winon le¿y 60 mil na wschód w zalesionych górach. Uwa¿aj, s¹ tam dzikie bestie.}
{435} {} {Zycz mi szczêœcia.}
{436} {} {Mam nadziejê, ¿e ci ³owcy nie postanowili siê po prostu nawaliæ. W przeciwnym razie urz¹dzê ich gorzej ni¿ wœciek³y kretoszczur.}
{437} {} {Porozmawiajmy o tym obozie myœliwych.}
{438} {} {Jakieœ wiadomoœci?}
{439} {} {Jeszcze nie. Nie mia³em czasu przejœæ siê do obozu.}
{440} {} {Przypomnij mi, o jakim obozie mówi³eœ?}
{441} {} {Obóz nazywa siê Winon i znajduje siê na pó³nocnym wschodzie.}
{442} {} {Teraz rozumiem. Có¿, od razu tam pójdê.}
{443} {} {By³em w Obozie Winon. Myœliwi zostali zabici przez dzikusów.}
{1443} {} {By³am w Obozie Winon. Myœliwi zostali zabici przez dzikusów.}
{444} {} {Co za horror! Ten obóz dostarcza³ ¿ywnoœæ do miasta. Nie mo¿emy pozwoliæ ¿eby te dzikusy zajmowa³y nasze tereny ³owieckie.}
{445} {} {Co mam zrobiæ?}
{446} {} {Mo¿e Faber coœ poradzi? Te szuje z garnizonu pewnie nie maj¹ nic do roboty, wiêc pozwólmy im zarobiæ na siebie. A jeœli nie, to w ka¿dym razie konieczne jest wypêdzenie dzikusów z tego miejsca.}
{447} {} {Muszê siê wydostaæ z tego miejsca! Szkoda, ¿e nie ma z nami Fabera. Dzieje siê tak, bo rozpaczliwie potrzebujemy funkcjonuj¹cego garnizonu.}
{448} {} {Ok. Czeœæ.}
{449} {} {Nie martw siê - dzicy nie s¹ ju¿ przeszkod¹.}
{450} {} {Naprawdê? Jak sobie z nimi poradzi³eœ?}
{451} {} {Co dziki t³um mo¿e zrobiæ przeciwko nowoczesnej broni? Zgadza siê - nic.}
{452} {} {Uda³o mi siê wykorzystaæ przeciwko nim ich w³asne przes¹dy. Wystarczy³a ma³a sztuczka z totemami.}
{453} {} {Wow, nie zazdroszczê tym, którzy stan¹ ci na drodze. Ten obóz by³ jednym z najwa¿niejszych Ÿróde³ miêsa dla mnie i dla ca³ego miasta. Bez niego bardzo cierpielibyœmy. Okazuje siê, ¿e teraz wszyscy mamy wobec Ciebie d³ug. Dziêkujê Ci.}
{454} {} {Zwykli ludzie nie powinni cierpieæ z powodu b³êdów naszych przywódców.}
{455} {} {Podziêkowaniami cz³owiek siê nie nasyci, wiesz?}
{456} {} {Myœla³em, ¿e zap³acê ci 20 kapsli jak za kuriera. Ale bior¹c pod uwagê, jak to zadanie siê skoñczy³o, to nie wystarczy. Wiesz, dam ci 50% rabatu na wszystkie moje produkty. Tak bêdzie sprawiedliwe.}
{457} {} {Jesteœ zbyt hojny, stary. Ale czas ju¿ na mnie - muszê iœæ, dalej przywracaæ sprawiedliwoœæ.}
{458} {} {Nie martw siê, zajmê siê nimi.}