{100} {} {Widzisz goœcia baru.}
{101} {} {Widzisz klienta baru. Ta osoba wygl¹da jakby chcia³a pogadaæ przy kubku czegoœ mocniejszego.}

{200} {} {Hej, czeœæ.}
{201} {} {Do widzenia.}
{202} {} {Hej, kolego. Czy chcia³byœ mi postawiæ coœ do picia? A mo¿e po prostu idziesz do baru, ¿eby posiedzieæ?}
{1202} {} {Hej dziewczyno. Czy chcia³abyæ mi postawiæ coœ do picia? A mo¿e po prostu idziesz do baru, ¿eby posiedzieæ?}
{203} {} {Hej, to by³a ciê¿ka walka. Czy chcia³byœ mi postawic coœ do picia? A mo¿e chodzisz do barów tylko na walki?}

{204} {} {Nie mam zbyt wielu kapsli.}
{205} {} {Ha! Sk¹piec...}
{206} {} {Co co? Nazwa³aœ mnie sk¹pcem? Tak? Mnie?}
{207} {} {Uch, pa.}
{208} {} {Tak. I co?}
{209} {} {Wygl¹da na to, ¿e robisz siê niegrzeczna. Chcesz chyba wyjœæ st¹d nogami do przodu.}
{210} {} {Uch, nic.}
{211} {} {Dobra, wyluzuj kowboju. Lepiej nie robiæ zamieszania o jakieœ drobiazgi w tym mieœcie.}
{1211} {} {Dobra panienko, uspokój siê. Lepiej nie robiæ zamieszania o jakieœ drobiazgi w tym mieœcie.}
{212} {} {To jest to samo.}

{220} {} {Jasne, pozwól mi tylko podejœæ do lady.}
{221} {} {Nie mogê siê doczekaæ, kowboju.}
{1221} {} {Nie mogê siê doczekaæ, panienko.}
{222} {} {Uch, pa.}
{223} {} {Oto piwo. Tani, ale pewny sposób na podtrzymanie rozmowy, prawda?}
{224} {} {Otwórzmy tê butelkê tequili z pustkowi. Jak myœlisz, to œwietny sposób na relaks, prawda?}
{225} {} {Dziêki za drinka. (nalewa szklankê i milknie)}
{226} {} {Co jest? Coœ siê sta³o?}
{227} {} {Wiesz... (bierze szorstki ³yk) Bywa³o lepiej.}
{228} {} {Uh, pos³uchaj, mo¿esz mi opowiedzieæ o mieœcie?}

{229} {} {Jestem tu dopiero od miesi¹ca. I w tym czasie nauczy³am siê jednego: lepiej nie zatrzymywaæ siê w tym mieœcie.}
{230} {} {To mo¿na powiedzieæ o ka¿dym obcym mieœcie.}
{231} {} {Brzmisz, jakbyœ du¿o widzia³a.}
{232} {} {Nie pyta³am o twoj¹ opiniê. Ale... masz racjê.}
{233} {} {Wiêc mo¿e opowiesz mi swoj¹ historiê?}
{234} {} {Heh, wola³abym, ¿eby tak nie by³o.}
{235} {} {Proszê, opowiedz mi swoj¹ historiê.}
{236} {} {Przyby³am tutaj z moim ch³opakiem. Wszystko sz³o dobrze. Zbieraliœmy rzeczy z ruin i p³aciliœmy za to „podatek”.}
{237} {} {[Dalej.]}

{238} {} {Ale kiedy skoñczy³y siê kapsle, Karl popad³ w d³ugi. I to spore. I w koñcu Faber wyda³ rozkaz wsadzenia Karla za kratki. Teraz on jest tam, a ja jestem tutaj. I nie wiem, co robiæ.}
{239} {} {Czy spêdzi tam teraz ca³e ¿ycie?}
{240} {} {Faber nakaza³ mu rok ciê¿kiej pracy. Ale Karl nie wytrzyma tego. I ja te¿ nie.}
{241} {} {Czy mogê jakoœ wyci¹gn¹æ go z tego wiêzienia?}
{242} {} {Tylko jeœli sp³acisz czêœæ jego d³ugów. A szczerze w¹tpiê czy masz tyle kapsli.}
{243} {} {Smutna historia.}
{244} {} {Tak. Niestety.}
{245} {} {[Zostaw dziewczynê sam¹ z butelk¹]}
{246} {} {Co zamierzasz teraz zrobiæ?}
{247} {} {Po tej historii nie bêdê mog³a tu mieszkaæ. Muszê zmieniæ otoczenie. Mo¿e wrócê na po³udnie.}
{248} {} {Przypomnij mi, co siê sta³o z twoim ch³opakiem?}