{100} {} {Widzisz Kaznodziejê Hirama.}
{101} {} {Widzisz mê¿czyznê w podartej sutannie.}
{102} {} {Co... co robisz...}
{103} {} {...hhh... hrrr...}
{104} {} {Heretyk! Staro¿ytna technologia nie jest dla prostego ludu. Ta zbroja nale¿y do naszej g³ównej œwi¹tyni w Phoenix.}

# Pierwszy dialog
{200} {} {Witaj podró¿niku. To wielka odwaga z twojej strony, ¿e przybywasz do tego miasta.}
{1200} {} {Witaj podró¿niku. To wielka odwaga z twojej strony, ¿e przybywasz do tego miasta.}
{201} {} {Dlaczego?}
{202} {} {Flagpool to jedno z niewielu miejsc na pustkowiu, gdzie porz¹dek jest... tego rodzaju. Niektórzy ludzie z zewn¹trz w tym mieœcie s¹ skazani na prace przymusowe, a niektórzy na œmieræ, aby staæ siê paliwem dla Swiêtego Ognia. Ale ostatecznie wszystko zale¿y od Ciebie.}
{203} {} {Rozumiem. Chcê o coœ zapytaæ.}
{204} {} {Ok, wezmê to pod uwagê. PA.}
{205} {} {Witaj podró¿niku. Có¿ za b³ogos³awieñstwo, ¿e promienie Swiêtego Ognia pos³a³y ciê do tego miasta. Mam nadziejê, ¿e nie potêpiasz lokalnego porz¹dku?}
{206} {} {Jakie inne zamówienia?}
{207} {} {Witaj podró¿niku. Czy jest coœ, w czym mogê Ci pomóc?}
{208} {} {Mo¿e. Jestem tu od niedawna, przyda³aby mi siê rada.}
{209} {} {Có¿, nie jest to dobre miejsce na pocz¹tek. Naucz siê akceptowaæ wiarê tak¹, jaka jest. S³owa s¹ tylko pow³ok¹ znaczenia.}

# Powtarzajacy siê dialog
{210} {} {Jak mogê pomóc?}
{211} {} {Do widzenia.}
{212} {} {Kim jesteœ i co to za miejsce?}
{213} {} {To jest œwi¹tynia Wielkiego Swiêtego Ognia. A ja jestem Hiram, jego kap³an. Witamy w Jego promiennej siedzibie.}
{214} {} {Sk¹d tyle pretensjonalnych s³ów?}
{215} {} {Có¿... Szczerze mówi¹c, ju¿ zapomnia³em dni, kiedy mówi³em inaczej. Nauka o Swiêtym Ogniu zmieni³a ca³e moje ¿ycie.}

# O wiedzy
{216} {} {Czy twoja œwi¹tynia ma jakiekolwiek znaczenie dla Flagpool?}
{217} {} {O tak! Po pierwsze, Flagpool jest zbudowane dziêki naszemu koœcio³owi... a raczej g³ównej œwi¹tyni w Phoenix.}
{218} {} {Naprawdê? Dlaczego?}
{219} {} {Uran jest jednym ze œwietych zasobów, które odziedziczyliœmy po naszych przodkach. Zbieramy tutaj jego promienist¹ energiê i u¿ywamy jej na chwa³ê Swiêtego Ognia...}
{220} {} {Powiesz coœ wiêcej?}
{221} {} {Uczymy umiejêtnoœci czytania i pisania oraz przedwojennej wiedzy wszystkich, którzy wyra¿aj¹ takie pragnienie. A ja, pokorny s³uga Swiêtego Ognia, mam dar uzdrawiania.}
{222} {} {Nie s¹dzê, ¿e robisz to za darmo.}
{223} {} {Sceptycy! Wszêdzie sceptycy! Jednak muszê przyznaæ - tak. Aby zbli¿yæ siê do staro¿ytnej m¹droœci, musisz zap³aciæ kapslami lub zostaæ cz³onkiem naszego koœcio³a. W koñcu nie wszyscy ludzie s¹ gotowi zaakceptowaæ wiedzê Starego Swiata.}
{224} {} {Rozumiem. Powiedz mi wiêcej.}
{225} {} {Skoñczylismy tê rozmowê. PA.}
{226} {} {Chcia³bym podzieliæ siê Twoj¹ wiedz¹.}
{227} {} {Och, zdecydowanie. Ale obawiam siê, ¿e nie mogê przyj¹æ ciê jako brata w wierze, dopóki nie otrzymam zgody g³ównej œwi¹tyni. Oznacza to, ¿e musisz zap³aciæ. Umiesz czytaæ?}
{1227} {} {Och, zdecydowanie. Ale obawiam siê, ¿e nie mogê przyj¹æ ciê jako siostry w wierze, dopóki nie otrzymam zgody g³ównej œwi¹tyni. Oznacza to, ¿e musisz zap³aciæ. Umiesz czytaæ?}
{228} {} {Tak.}
{229} {} {Ledwo potrafiê sk³adaæ sylaby.}
{230} {} {Wiêc sekrety Swiêtego Ognia nie dotr¹ do twojego umys³u! Zaczniemy od podstaw - umiejêtnoœci czytania i pisania. Jedna lekcja kosztuje sto kapsli.}
{231} {} {Oto kapsle. Chcê byæ m¹drzejszy!}
{232} {} {Nie teraz. Najpierw odpowiedz na inne pytania.}
{233} {} {Nie staæ mnie jeszcze na takie marnotrawstwo.}
{234} {} {Wystarczy na dziœ. Odt¹d bêdziesz móg³ samodzielnie przyswajaæ przedwojenn¹ wiedzê, jeœli bêdziesz wiêcej æwiczyæ w czytaniu i pisaniu. I nie zapominaj, kto ci objawi³ ten sakrament!}
{235} {} {Wiedza... du¿o... informacji. Ju¿ boli mnie g³owa. Zróbmy przerwê.}
{236} {} {Ka¿dy, kogo spotykasz, powinien byæ trzymany z dala od sakramentów Swiêtego Ognia. W koñcu tê wiedzê mo¿na wykorzystaæ zarówno dla dobra, jak i z³a. Udowodnij swoje oddanie naszej wierze, dokonuj¹c znacznej darowizny. 300 kapsli to dobry pocz¹tek.}
{237} {} {Myœlê, ¿e i tak masz wystarczaj¹co du¿o datków dla twojego koœcio³a.}
{238} {} {W takim razie chcê przekazaæ darowiznê.}
{239} {} {O tak. Naprawdê. Có¿, muszê dotrzymaæ s³owa. Witam w mojej siedzibie. Przechowywane s¹ tu staro¿ytne pisma. Traktuj je z trosk¹ i szacunkiem.}
{240} {} {Swietnie, poczytam je przed snem.}
{241} {} {Dziêkujê, twoja dobroæ nie zna granic!}
{242} {} {Doœæ o œwi¹tyni, ju¿ wiem wystarczaj¹co du¿o.}

# O wierzê
{245} {} {Opowiedz mi o swojej wierze.}
{246} {} {Mogê o tym mówiæ w nieskoñczonoœæ. Swiat zosta³ zrodzony przez Swiêty Ogieñ, który spad³ na ziemiê sto lat temu. Spala³ ludzi pogr¹¿onych w grzechach i pozostawi³ tylko ma³e rodziny, aby rasa ludzka mog³a dalej istnieæ.}
{247} {} {[Dalej.]}
{248} {} {Teraz my, potomkowie ocala³ych, próbujemy zbudowaæ Nowy Swiat, wolny od b³êdów i wad przesz³oœci.}
{249} {} {Potomkowie ocala³ych? Czyli my wszyscy?}
{250} {} {I tak i nie. G³ównie to nasz koœció³ i jego wyznawcy. Reszta ludzi zapomnia³a niestety lekcji z przesz³oœci. Jesteœmy tu, aby przywieœæ ich do zmys³ów.}
{251} {} {Myœla³em, ¿e to wojna jest wszystkiemu winna.}
{252} {} {To jest bajka dla wielu ¿yj¹cych dzisiaj. Straci³eœ wiarê w dusze i zni¿y³eœ siê do prostych prawd materialnych. Wielka Wojna jest tylko mask¹ tego, czym by³ Swiêty Ogieñ. To nie bomby atomowe ukara³y ludzkoœæ, ale ludzka g³upota i chciwoœæ. O to chodzi.}
{253} {} {Jak daleko rozprzestrzeni³a siê wasza wiara?}
{254} {} {Nasza g³ówna œwi¹tynia znajduje siê w Phoenix, ale to nie jest takie wa¿ne. W koñcu wiele plemion wierzy w Swiêty Ogieñ, nazywaj¹c go innymi imionami i inaczej interpretuj¹c staro¿ytne wydarzenia. Dlatego nasz koœció³ tak ³atwo siê rozwija. Nasze nauki s¹ znane w ca³ej Sonorze.}
{255} {} {Czy ludzie naprawdê w to wierz¹?}
{256} {} {Wiêkszoœæ mieszkañców wierzy w Swiêty Ogieñ lub udaje, ¿e wierzy. Ale niestety najemnicy Fabera s¹ w wiêkszoœci bezbo¿ni, a wœród ludnoœci s¹ sceptycy. Nie martw siê, Swiêty Ogieñ prêdzej czy póŸniej otworzy im oczy. Bardziej martwiê siê o tych, którzy ukrywaj¹ siê przed jego wzrokiem.}
{257} {} {}
{258} {} {Pozwól mi zostaæ z tob¹ jeszcze trochê, ojcze.}
{259} {} {Uch, do widzenia.}

#Darowizna
{260} {} {Chcia³bym pomóc Twojemu koœcio³owi.}
{261} {} {Ka¿da darowizna zbli¿y nas do ducha Swiêtego Ognia. Co mo¿esz zaoferowaæ?}
{262} {} {Przepraszam, nic wartoœciowego. Ale mam kilka pytañ.}
{263} {} {Dzisiaj nic. PA.}
{264} {} {Tylko 10 kapsli.}
{265} {} {Oto 50 kapsli.}
{266} {} {A¿ 100 kapsli.}
{267} {} {(szybko chowa garœæ kapsli w kieszeniach swojej szaty) Dziêki.}
{268} {} {(W poœpiechu wk³ada kapsle do skórzanej sakiewki) Naprawdê, twoja hojnoœæ nie zna granic!}
{269} {} {(wsuwa kapsle do skórzanej sakiewki u pasa) Niech Swiêty Ogieñ bêdzie z tob¹!}

#Leczenie
{270} {} {Potrzebujê leczenia.}
{271} {} {W imiê Swiêtego Ognia, co siê sta³o?}
{272} {} {Popatrz na te rany.}
{273} {} {Mam kontuzjê.}
{274} {} {To napromienianie.}
{275} {} {To chyba zatrucie.}
{276} {} {Jednak to nic takiego.}
{277} {} {Oczywiœcie koœció³ ci pomo¿e, ale czy chcia³byœ go wesprzeæ niewielk¹ darowizn¹? Chodzi o sumê w wysokoœci }
{278} {} { kapsli.}
{279} {} {Oto kapsle.}
{280} {} {Nie mam tylu kapsli!}
{281} {} {Przepraszam. W takim razie nie mogê Ci pomóc.}
{282} {} {Jak to...}
{283} {} {Dobra, mo¿e samo siê uleczy.}
{284} {} {Chwa³a Swiêtemu Ogniu za to, ¿e da³ ci trochê wiêcej czasu!}
{285} {} {Wow, czujê siê du¿o lepiej.}
{286} {} {}
{287} {} {Ch³op siê przebra³ za babê! HAHA!}
{288} {} {Mówisz o mojej sutannie? (krêci g³ow¹) Och, biedne dziecko Atomu, ¿al mi ciê. Chcia³bym pomóc ci przywróciæ atomy m¹droœci, które utraci³eœ, ale tutaj jestem bezsilny. WyjdŸ na zewn¹trz, na ulice radiacyjne dziecko.}
{289} {} {Ulica? Uwielbiam ulice.}

# Otrzymanie listu polecaj¹cego
{290} {} {Mogê znacznie bardziej pomóc koœcio³owi, jeœli zbli¿ê siê do jego wy¿szego kierownictwa.}
{291} {} {Mo¿e. W mojej mocy jest napisanie w swoim imieniu listu polecaj¹cego do g³ównej œwi¹tyni. Ale wygl¹da na to, ¿e nie masz jeszcze w sobie doœæ naszej wiary.}
{1291} {} {Mo¿liwe. W mojej mocy jest napisanie w swoim imieniu listu polecaj¹cego do g³ównej œwi¹tyni. Ale wygl¹da na to, ¿e nie masz jeszcze w sobie doœæ naszej wiary.}
{292} {} {Cokolwiek powiesz.}
{293} {} {Mo¿e. W mojej mocy jest napisanie w swoim imieniu listu polecaj¹cego do g³ównej œwi¹tyni w Phoenix. To bêdzie pocz¹tek twojej ciernistej œcie¿ki. Czy na pewno jesteœ gotowy, aby przyj¹æ ten ciê¿ar?}
{1293} {} {Prawdopodobnie. W mojej mocy jest napisanie w swoim imieniu listu polecaj¹cego do g³ównej œwi¹tyni w Phoenix. To bêdzie pocz¹tek twojej ciernistej œcie¿ki. Czy na pewno jesteœ gotowa, aby wzi¹æ na siebie ten ciê¿ar?}
{294} {} {Zdecydowanie!}
{295} {} {Muszê to pomyœleæ.}
{296} {} {Bardzo dobrze. Chwilkê. Oto list. Opiekuj siê nim, a¿ dojdziesz do g³ównej œwi¹tyni. To bêdzie twój pierwszy test.}
{297} {} {Niosê ten list w imiê Swiêtego Ognia! Có¿, czy coœ w tym stylu.}
{298} {} {Bior¹c pod uwagê twoj¹ reputacjê we Flagpool, w¹tpiê, by by³ z ciebie jakiœ po¿ytek.}
{299} {} {}

# Quest - start:
{300} {} {Czy kapsle s¹ jedynym problemem?}
{301} {} {Wielu gardzi nasz¹ wiar¹, ale zwykle zachowuj¹ to dla siebie. Niektórzy jednak nie s¹ tak powœci¹gliwi.}
{302} {} {Czy ktoœ ci grozi?}
{303} {} {Ktoœ nieznany pope³nia w nocy nikczemne czyny - rysuje krzy¿e na œcianach, podpala œmieci, drzwi brudzi b³otem. Oczywiœcie próbuje mnie zastraszyæ i przekonaæ do ucieczki z kolonii. Nie uda³o mi siê jeszcze stan¹æ twarz¹ w twarz z t¹ niewiern¹ osob¹.}
{304} {} {Mo¿e bêdê móg³ go znaleŸæ. Ciekawe dlaczego tak bardzo ciê nie lubi.}
{305} {} {Nie chcê anga¿owaæ siê w takie mroczne sprawy. Zmieñmy temat.}
{306} {} {By³bym bardzo wdziêczny.}
{307} {} {Ok.}
{308} {} {Nie zamierzam nikogo "zaciemniaæ".}

# Quest - wykrywanie sabotazysty:
{310} {} {Porozmawiajmy o tym sabota¿yœcie.}
{311} {} {Coœ nowego?}
{312} {} {Jeszcze nie, ale chcê ciê o coœ zapytaæ.}
{313} {} {Nic. Wrócê, gdy dowiem siê wiêcej.}
{314} {} {Uda³o mi siê z³apaæ tego wandala z zaskoczenia. Okaza³o siê, ¿e to ³ysiej¹cy mieszkaniec z domu po³o¿onego dalej na po³udnie.}
{315} {} {Festus... Beznadziejna ofiara rozszczepienia atomu.}
{316} {} {Znacie siê?}
{317} {} {Przychodzi³ na kazania, ale nie potrafi³ siê nasyciæ promieniuj¹cymi prawdami ognia. Kiedy nadszed³ czas, Festus zosta³ zaœlepiony gniewem i dum¹. I wtedy zamkn¹³em dla niego drzwi œwi¹tyni.}
{318} {} {Co siê sta³o?}
{319} {} {Dziecko Festusa sta³o siê Ÿród³em niezgody. B³aga³em, aby ten utalentowany m³odzieniec móg³ studiowaæ w œwi¹tyni, ale Festus z wœciek³oœci odmówi³. Niestety, nawet we Flagpool wielu nie rozumie wartoœci wiedzy i polega tylko na brutalnej sile.}
{320} {} {[Dalej.]}
{321} {} {Kiedy ch³opca ogarnê³a choroba popromienna, obieca³em bezp³atne leczenie, jeœli ojciec zmieni zdanie i wyœle syna do œwi¹tyni. Ale nienawiœæ Festusa by³a nie do odparcia. Pewnie dlatego teraz siê mœci.}
{322} {} {Co mogê zrobiæ?}
{323} {} {Powiedz Festusowi, ¿eby zaprzesta³ gróŸb i odda³ dziecko do œwi¹tyni. To bêdzie niezwykle trudne.}
{324} {} {Pozostaje... morderstwo?}
{325} {} {Uh, spróbujê pierwszej opcji.}
{326} {} {Potrzebujê czasu do namys³u.}
{327} {} {Kiedy paliwo j¹drowe staje siê szkodliwe, zostaje odciête i schowane w ciemnoœci. W przeciwnym razie stanowi niebezpieczeñstwo dla innych.}
{328} {} {Có¿, niech Swiêty Ogieñ ci pomo¿e.}
{329} {} {Uch, dobrze.}

# Quest - wykonanie zadania:
{330} {} {Porozmawiajmy o problemie z Festusem.}
{331} {} {S³ucham.}
{332} {} {Mam pytania dotycz¹ce czegoœ innego.}
{333} {} {Wrócê, gdy rozwi¹¿ê problem.}
{334} {} {Uda³o mi siê przekonaæ Festusa. Wyœle swojego syna na szkolenie i zaprzestanie przeœladowañ.}
{335} {} {Moc atomu jest naprawdê wielka! Festusa czeka publiczna skrucha, ale jego syn bêdzie mia³ przed sob¹ wspania³¹ przysz³oœæ jako skryba i uczony w Swi¹tyni Ognia. Cudowna praca.}
{336} {} {Festus mia³... wypadek. Ju¿ nie stanowi problemu.}
{337} {} {Niech Swiêty Ogieñ spali jego dusze! Festusa nie mo¿na by³o reedukowaæ, a jego nawrócenie na nasz¹ wiarê przynios³oby tylko szkodê. Ale jego syn bêdzie mia³ przed sob¹ wspania³¹ przysz³oœæ jako skryba i uczony w Swi¹tyni Ognia. Dobra robota.}
{338} {} {Jak mogê nagrodziæ twoje wysi³ki?}
{339} {} {Nie trzeba, dziêkujê. Wszystko to zrobi³em ze wzglêdu na wiarê.}
{340} {} {Potrzebujê lekarstw - antyrada i ze dwa stymulanty.}
{341} {} {Czy mogê otrzymaæ 20% zni¿ki na leczenie?}
{342} {} {Potrzebujê kapsli, aby uwolniæ moich wspó³plemieñców z wiêzienia.}
{343} {} {Mam wielkie marzenie - udaæ siê do g³ównej œwi¹tyni ognia i porozmawiaæ z jej przywódc¹.}
{344} {} {Potrzebujê dostêpu do Twojej biblioteki.}
{345} {} {[Dalej.]}
{346} {} {}
{347} {} {Ale jak to zrobiæ, nie wywo³uj¹c gniewu pozosta³ych kolonistów?}
{348} {} {Hmm. Festus cierpi na skutki promieniowania. Wystarczy rzuciæ w niego czymœ silnie radioaktywnym, aby przyœpieszyæ proces rozpadu jego duszy na atomy. Z pewnoœci¹ gdzieœ w kopalni uranu jest taki przedmiot.}
{349} {} {Wypadek? Smiertelna dawka promieniowania? Zatrucie? Nie jestem ekspertem w takich sprawach.}

{350} {} {Dziêki.}
{351} {} {Niech P³omieñ Niebios ciê strze¿e. Na nastêpnym kazaniu opowiem o twojej dobroczynnoœci. Jestem pewien, ¿e to podniesie twoj¹ reputacjê w oczach zwyk³ych kolonistów.}
{352} {} {Zas³ugujesz na to. WeŸ to.}
{353} {} {Zas³ugujesz na to. Mo¿esz liczyæ na... „rabat”.}
{354} {} {Mogê zaoferowaæ tylko 100 kapsli, poniewa¿ parafianie oszczêdzaj¹ na darowiznach. Jednak to wystarczy, aby Faber z tob¹ chocia¿ porozmawia³.}
{355} {} {Hmm. Mogê napisaæ list polecaj¹cy do g³ównej Swi¹tyni Ognia w Phoenix. Ale mimo wszystko twoje zas³ugi nie s¹ tak wielkie. Musisz przekazaæ wiêcej darowizn.}
{356} {} {Ten zbiór bezcennej przedwojennej wiedzy wymaga specjalnego traktowania. Traktuj go z szacunkiem.}
{357} {} {Zapomnij o Festusie i jego dziecku. Jest za póŸno.}
{358} {} {Wyzdrowia³? Wydawa³o mi siê, ¿e ten problem nigdy nie zostanie rozwi¹zany bez mojej interwencji. Có¿, z wielkim ¿alem muszê zrezygnowaæ z moich zadañ.}
{359} {} {To ciê czegoœ nauczy.}

# Leczenie syna Festusa
{360} {} {Syn Festusa wymaga leczenia.}
{361} {} {I chêtnie mu pomogê, jeœli zgodzi siê chodziæ do œwi¹tyni.}
{362} {} {Ok.}
{363} {} {Problem z Festusem to przesz³oœæ. Czas dotrzymaæ obietnicy.}
{364} {} {OpóŸnienie w procesie nie zadowoli g³ównej œwi¹tyni ognia.}
{365} {} {Twoja uczciwoœæ tylko zwróci ludzi przeciwko nam.}
{366} {} {Swi¹tynia zwiêkszy swoj¹ reputacjê, jeœli ust¹pi w tej sytuacji.}
{367} {} {Zajmê siê leczeniem, gdy tylko bêdê gotowy.}
{368} {} {To dobrze.}
{369} {} {Zostanê na swoim.}
{370} {} {Oczekiwano...}
{371} {} {Jaki jest sens bycia tak pozbawionym skrupu³ów?}
{372} {} {Doroœli s¹ trudni do zmiany. I czêsto nie ma to wiêkszego sensu. To przez dzieci trzeba zapuœciæ korzenie wiary. A leczenie zostanie szybko zapomniane. W koñcu ludzie nie s¹ teraz zbyt wdziêczni.}
{373} {} {Rozumiem.}

# Poprawki dialogow po wydarzeniach w Swi¹tyni Phoenix
{400} {} {Zostaw mnie w... Och, to ty. Niewa¿ne.}
{401} {} {Czy ktoœ ci przeszkadza?}
{402} {} {Koloniœci nie toleruj¹ mojej wiary, odk¹d dowiedzieli siê o wydarzeniach na po³udniu. Niektórzy chc¹ mnie wypêdziæ z miasta. Ale ja nie mam dok¹d iœæ.}
{403} {} {Wygl¹da na to, ¿e masz du¿e k³opoty. Lepiej siê st¹d wyniosê.}
{404} {} {Pozdrowienia. Cieszê siê, ¿e widzê w moim klasztorze brata w wierze. Witamy we Flagpool!}
{1404} {} {Pozdrowienia. Cieszê siê, ¿e w moim klasztorze widzê siostrê w wierze. Witamy we Flagpool!}
{405} {} {Sk¹d wiesz o moim awansie?}
{406} {} {Odleg³oœæ jest nieznaczn¹ przeszkod¹ dla naszej wiary. Poinformowali mnie o tobie pos³añcy.}
{407} {} {A tak, poczta...}
{408} {} {}
{409} {} {}
{410} {} {Wiêc jak mogê pomóc, bracie?}
{1410} {} {Wiêc jak mogê pomóc, siostro?}
{411} {} {Stop! Co ty, bracie wiary, wiesz o tym, co wydarzy³o siê w Phoenix?}
{1411} {} {Stop! Co ty, siostro wiary, wiesz o tym, co wydarzy³o siê w Phoenix?}
{412} {} {Uch, tyle samo co ty.}
{413} {} {Wysadzi³em Swi¹tyniê Ognia. Z jej powodu Villê dotknê³a tragedia, wiêc lepiej nie próbuj ¿adnych numerów.}
{1413} {} {Wysadzi³am Swi¹tyniê Ognia. Z jej powodu Villê dotknê³a tragedia, wiêc lepiej nie próbuj ¿adnych numerów.}
{414} {} {Hmm. Bardzo przepraszam.}
{415} {} {Uch, chyba ju¿ pójdê.}
{416} {} {A wiêc to tak. To by³a zemsta... Co za barbarzyñski motyw! Ale jeœli nie jestem ju¿ cz³onkiem kultu, pozostaje tylko zrzuciæ szatê kaznodziei i uciec z Flagpool. Twój czyn daje mi prawo do rozpoczêcia wszystkiego od nowa. Mo¿e jednak nie jest tak Ÿle.}
{417} {} {Có¿, bywaj.}
{418} {} {Dotar³y do mnie wieœci o twoim wyrzuceniu z Bractwa Ognia. Muszê znaæ powody.}
{419} {} {Nie, nie musisz. A teraz wal siê!}
{420} {} {Nie bêdê tolerowaæ nadu¿ywania mojej wiary! Swiêty Ogieñ nie jest fikcj¹. To mia³o miejsce sto lat temu! Jeœli nawet po wszystkich moich kazaniach nie wierzysz w to, co oczywiste, pozostaje tylko mieæ nadziejê na twój wczesny rozpad na atomy.}
{421} {} {No có¿.}
{422} {} {Twoja wiara g³osi z³e pogl¹dy.}
{423} {} {Masz na myœli, ¿e nie by³o Swiêtego Ognia? I ¿e nie powinniœmy przywracaæ œwiatu jego dawnej œwietnoœci, poprawiaj¹c dawne aroganckie b³êdy? Co w takim razie powinniœmy zrobiæ? Nadal przeci¹gaæ ¿a³osne ¿ycie wœród ruin i ja³owych pustkowi? Zyæ nieœwiadomi naszych b³êdów?}
{424} {} {No có¿.}
{425} {} {Nadal wierzê w Ogieñ i wci¹¿ têskniê za Odrodzeniem, bracie.}
{426} {} {Twoje k³amstwa s¹ niczym wiêcej ni¿ nadu¿yciem wiary. Opuœæ Flagpool, zanim Ogieñ otworzy ci oczy na prawdê.}
{427} {} {No có¿.}
{428} {} {Czy mogê ci ufaæ... bracie? Byæ mo¿e nie zgubi³eœ siê jeszcze podczas naszej misji. Trwaj. I oka¿ swoje oddanie wierze prawdziwymi czynami. Z flag¹ œwi¹tyni lub bez.}
{1428} {} {Czy mogê ci ufaæ... siostro? Byæ mo¿e nie zgubi³aœ siê jeszcze podczas naszej misji. Trwaj. I oka¿ swoje oddanie wierze prawdziwymi czynami. Z flag¹ œwi¹tyni lub bez.}
{429} {} {Ok.}
{430} {} {Ju¿ samym swoim istnieniem pomagasz koœcio³owi. Ale zawsze potrzebujemy kapsli ze wszystkich r¹k.}
{431} {} {Ka¿dy, kogo spotykasz, powinien byæ trzymany z dala od sakramentów Swiêtego Ognia. W koñcu tê wiedzê mo¿na wykorzystaæ zarówno w dobrych, jak i z³ych celach...}
{432} {} {Oczywiœcie. I udowodni³em ju¿ swoje oddanie wierze.}
{1432} {} {Oczywiœcie. I udowodni³am ju¿ swoje oddanie wierze.}
{433} {} {Dziwne pytanie dla brata w wierze. Jestem Hiram, kap³an tej œwi¹tyni.}
{1433} {} {Dziwne pytanie dla siostry w wierze. Jestem Hiram, kap³an tej œwi¹tyni.}
{434} {} {Och, zdecydowanie. Ale czy potrafisz czytaæ?}