{100} {} {Widzisz Roya Fabera.}
{101} {} {Widzisz zarz¹dcê kolonii. Trudno ci znieœæ jego ciê¿kie spojrzenie.}
{102} {} {Twoje panowanie w³aœnie siê skoñczy³o, draniu.}
{103} {} {Twoje panowanie w³aœnie siê skoñczy³o.}

# Pierwszy dialog
{200} {} {(patrzy na ciebie oceniaj¹co, jakby chcia³ wiedzieæ, ile jesteœ wart) Nie widzia³em ciê wczeœniej. Kim jesteœ?}
{1200} {} {Przepraszam za swoj¹ ignorancjê, ale panie nie powinny wêdrowaæ po takich miejscach bez opieki. Nie widzia³em ciê wczeœniej. Sk¹d pochodzisz?}
{201} {} {Nie przedstawiê siê w³aœcicielowi niewolników.}
{202} {} {Hmm? Nikt obcy nie wa¿y³ siê mnie przez d³ugi czas odwiedzaæ. Niektórzy próbowali, ale nie ¿yli na tyle d³ugo. Za twoj¹ odwagê dam ci minutê przewagi. Chcê pos³uchaæ co masz do powiedzenia.}
{203} {} {Dosyæ gadania. Teraz widzê, ¿e musisz umrzeæ!}
{204} {} {Naprawdê?}
{205} {} {Szukam swojego ludu, ch³opów z Villi. Mówi¹, ¿e s¹ w twojej zagrodzie.}
{206} {} {(wymawiaj¹c s³owa obojêtnie) Tak, ci brudni ch³opi s¹ tutaj.}
{207} {} {Dlaczego trzymasz ich w niewoli?}
{208} {} {Ju¿ chcia³em ciê zastrzeliæ. Ale w porê przypomnia³em sobie, ¿e spotka³em kilku kap³anów Phoenix. Jesteœ jednym z nich? Wiêc co, do diab³a, robisz tutaj we Flagpool?}
{1208} {} {Ju¿ chcia³em ciê zastrzeliæ. Ale w porê przypomnia³em sobie, ¿e spotka³em kilku kap³anów w Phoenix. Czy jesteœ jednym z nich? Wiêc co, do diab³a, robisz tutaj we Flagpool?}
{209} {} {Chcê tylko porozmawiaæ.}

{210} {} {Co powiesz?}
{211} {} {Pozwól mi porozmawiaæ z rodzin¹.}
{212} {} {Z¹dam uwolnienia ch³opów.}
{213} {} {Dlaczego potrzebujesz tylu wiêŸniów?}
{214} {} {Czy jest tu dla mnie praca?}
{215} {} {}
{216} {} {Wróæmy trochê.}
{217} {} {Porozmawiajmy o czymœ innym.}
{218} {} {Zmieñmy temat.}
{219} {} {To wszystko, pójdê ju¿.}

# Wstep do zagrody
{220} {} {Czy to wszystko? Minuta rozmowy kosztuje 100 kapsli.}
{221} {} {Oto kapsle. Czy mogê teraz z nimi porozmawiaæ?}
{222} {} {Zaczekaj, opowiedz mi najpierw o czymœ innym.}
{223} {} {Nie mam tylu kapsli. Wrócê, kiedy je zbiorê.}
{224} {} {Nie ma problemu. Gwarantujê, ¿e zostaniesz wpuszczony i wypuszczony... jeœli bêdziesz siê zachowywaæ.}
{225} {} {Spróbujê.}
{226} {} {Nie mam tylu kapsli. Daj mi chwilê!}
{227} {} {Poda³em swoj¹ cenê. Jeœli nie mo¿esz zap³aciæ, wyjdŸ.}
{228} {} {Fuj...}
{229} {} {Wy, ch³opi, macie niesamowicie mocn¹ potrzebê przebywania razem... Dobra, idŸ. Ale jeœli Ÿle siê zachowasz, zostaniesz tam na zawsze.}

# Motyw Slave
{230} {} {Tutaj, przy ciê¿kiej pracy, te bezu¿yteczne œmieci spo³eczne mog¹ przynieœæ przynajmniej jak¹œ korzyœæ.}
{231} {} {O jakim rodzaju ciê¿kiej pracy mówisz?}
{232} {} {Kopalnie uranu na pó³nocy, karawany na po³udniu, odnowienie Flagpool, czasami zamówienia przychodz¹ z Phoenix... Nie pamiêtam wszystkiego.}
{233} {} {Wiêc to nie jest zagroda dla niewolników, ale wiêzienie?}
{234} {} {Do niedawna tak by³o. Po³owa œmieci w naszej kolonii pochodzi z po³udniowych ziem. Przywieziono ich tutaj. Bandyci, gwa³ciciele, d³u¿nicy - znajdziemy zastosowanie dla ka¿dego.}
{235} {} {Nazywaj to, jak chcesz, ale trzymasz ludzi wbrew ich woli.}
{236} {} {Rozejrzyj siê - Flagpool kwitnie dziêki naszemu wiêzieniu. Jesteœmy jedyn¹ si³¹, która mo¿e tu zaprowadziæ porz¹dek. Ponadto sama wzmianka o nas odstrasza ludzi od przestêpstw. Wci¹¿ mi nie ufasz? Wiêc idŸ do diab³a.}
{237} {} {Ale wieœniacy nie s¹ przestêpcami.}
{238} {} {Tak siê z³o¿y³o, ¿e nie by³o wystarczaj¹cej liczby skazañców, a najszybszym sposobem na ich pozyskanie by³a rekrutacja miejscowych dzikusów. Villa by³a po drodze. Swietna okazja, której trudno by³o siê oprzeæ.}
{239} {} {Dlaczego niedobór skazanych to taki problem?}
{240} {} {Taki redneck jak ty ma w¹ski pogl¹d na sprawy. Czy znasz miasta na po³udniu? Odradza siê tam prawdziwa cywilizacja. Jak kiedyœ.}
{241} {} {I?}
{242} {} {Flagpool dostarcza uran, a nasi skazani s¹ g³ównym ogniwem roboczym w tym ³añcuchu. Bez nas nie bêdzie postêpu na po³udniu. Tworzymy historiê, a teraz twoja nêdzna wioska mo¿e staæ siê jej czêœci¹. Zrób coœ po¿ytecznego dla reszty œwiata.}
{243} {} {Sam nie wygl¹dasz na stró¿a prawa.}
{244} {} {Czy myœlisz, ¿e w dzisiejszych czasach jest jakaœ ró¿nica? Stró¿e prawa ¿yj¹ z przestêpców. Pobieraj¹ podatki z osad w zamian za ochronê przed rebeliantami. Dlaczego niby jesteœmy gorsi? (podnosi kastet i przygl¹da siê mu z uczuciem) W³adza dodaje mocy. A to, jak siê ich pozbêdziesz, zale¿y tylko od Ciebie.}
{245} {} {Dlaczego potrzebujesz rudy uranu?}
{246} {} {A tak, kretyni zapomnieli o Starym Swiecie. Kilka pokoleñ temu ludzie otrzymywali energiê z radioaktywnej rudy. Z jej pomoc¹ dzia³a³a stara technika - od zwyk³ej ¿arówki po najbardziej zaawansowan¹ elektronikê. Pozosta³oœci tych technologii nadal s¹ u¿ywane w du¿ych miastach.}
{247} {} {Kto to kupuje?}
{248} {} {Na po³udniu jest kilku kupców, z których g³ównym jest kult czcicieli ognia.}
{249} {} {Jest kilku kupców na po³udniu. Wczeœniej wiêkszoœæ towarów kupowali czciciele ognia. Klienci s¹ teraz trochê z innych miejsc.}

# Wyzwolenie
{250} {} {Nie widzê powodu, aby to robiæ.}
{251} {} {Uda³o mi siê rozwi¹zaæ twoje problemy w kopalni.}
{252} {} {O tak, zosta³em ju¿ o tym poinformowany. A¿ trudno uwierzyæ, ¿e jakiœ ch³op by³ w stanie rozwi¹zaæ nasze problemy. Okej, dotrzymujê s³owa. IdŸ do zagrody i zabierz swoich wspó³plemieñców. S¹ wolni.}
{1252} {} {O tak, zosta³em ju¿ o tym poinformowany. A¿ trudno uwierzyæ, ¿e jakaœ ch³opka potrafi³a rozwi¹zaæ nasze problemy. Okej, dotrzymujê s³owa. IdŸ do zagrody i zabierz wspó³plemieñców. S¹ wolni.}
{253} {} {Zdecydowanie.}
{254} {} {Wiêc musi byæ taki powód.}
{255} {} {Ok, zawrzyjmy umowê. Istnieje kilka problemów, które nale¿y rozwi¹zaæ. Jeœli sobie z tym poradzisz, uwolniê tych kilku ch³opów, którzy pozostali w zagrodzie.}
{256} {} {Czego chcesz?}
{257} {} {Muszê przywróciæ kopalniê na w³aœciwe tory. Porozmawiaj z administratorem, on poinformuje Ciê o reszcie.}
{258} {} {Pomyœlê o tym, ale najpierw muszê zadaæ kilka pytañ.}
{259} {} {Swietnie, porozmawiam z nim i wrócê póŸniej.}
{260} {} {O czym ty mówisz?! Kopalnia jest zniszczona, a jej oczyszczenie zajmie miesi¹ce! Czy to brzmi jak rozwi¹zanie problemu? Nie. A teraz wynoœ siê!}
{261} {} {Tak to jest...}
{262} {} {Przypomnij mi o naszej umowie.}
{263} {} {Nie rozumiesz za pierwszym razem? IdŸ do administratora w kopalni. Powie ci, co masz robiæ.}
{264} {} {Za tydzieñ zobaczysz, jak ch³opi zainfekuj¹ ca³¹ koloniê.}
{265} {} {O czym ty do diab³a mówisz?}
{266} {} {O wirusie FEV. Wieœniacy s¹ na to odporni, ale koloniœci ma³o prawdopodobne. Nie s³ysza³eœ?}
{267} {} {Cholera, ca³e osady na po³udniu wymar³y z powodu jakiejœ zarazy... Jak mo¿esz to udowodniæ?}
{268} {} {Kiedy choroba siê ujawni, sam siê o tym przekonasz. Sam zdecyduj, czy warto ryzykowaæ.}
{269} {} {Cholera... Dobra, pozwolê twoim ch³opom odejœæ, ale wynoœcie siê z kolonii! Natychmiast!}
{270} {} {Dobra decyzja.}
{271} {} {Có¿... ch³opi s¹ chorzy. Nie widzisz?}
{272} {} {Jeœli bêdziesz dalej naciskaæ, skoñczysz gorzej ni¿ twoi wspó³plemieñcy.}
{273} {} {Hej, spokojnie...}

{274} {} {Mówi¹, ¿e ktoœ szuka informacji wœród moich ludzi. Nie lubiê tego. Jeœli jeszcze raz to siê powtórzy, pójdziesz prosto na szubienicê.}
{275} {} {To jakiœ b³¹d! Twoi informatorzy k³ami¹!}
{276} {} {Uch... ok.}
{277} {} {Zamknij siê! Ta kolonia opiera siê na surowych zasadach. Naruszysz jedn¹ z nich - i zostaniesz ukarany. Naruszysz drug¹ - i masz pêtlê na szyi. A zasady tutaj s¹ ustalane przeze mnie.}

{278} {} {(krzyczy) Ty szczurze, czy zdajesz sobie sprawê, ¿e garstka brudnych ch³opów zagra¿a ca³emu Flagpool! Lata pracy nad wyposa¿eniem i kontrolowaniem ca³ego miasta, nadzieje ca³ego po³udnia na pomyœlnoœæ - wszystko zagro¿one! ChodŸ, poka¿ CALA wolê ¿ycia!}
{279} {} {Jak sobie ¿yczysz...}

#Quests
{280} {} {Mo¿e mogê zarobiæ parê kapsli?}
{281} {} {Mo¿e. Jest jeden irytuj¹cy problem, który drêczy mnie od d³u¿szego czasu.}
{282} {} {Powiedz mi wiêcej.}
{283} {} {W ruinach miasta na wschodzie znik³o kilka patroli. Mówi¹, ¿e s³yszano strzelaninê. ZnajdŸ przyczynê i napraw to - zap³acê za to 300 kapsli.}
{284} {} {W porz¹dku. Wrócê, kiedy to naprawiê.}
{285} {} {Przemyœlê twoj¹ propozycjê.}
{286} {} {Ok, ale jeœli bêdê musia³ kogoœ zabiæ, to zrobiê to.}
{287} {} {Dlaczego twoi najemnicy tego nie zrobi¹?}
{288} {} {Ruiny starego miasta s¹ zbyt zagmatwane i niebezpieczne. Stracê wiêcej ludzi, jeœli wyœlê ich na rekonesans. Ale teraz mam ciebie... Co jest? Ju¿ odmawiasz?}
{289} {} {Wiêc nie mam wyboru. Umrzesz!}
{290} {} {Ranger? Zwyk³y przestêpca, który wyobra¿a sobie, ¿e jest bohaterem. Dobra robota. Oto Twoje 300 kapsli.}
{291} {} {Tak po prostu? Dla ciebie ¿ycie ludzkie jest naprawdê bezwartoœciowe.}
{292} {} {Swietnie.}
{293} {} {Dok³adnie. W tym * twoje * nieszczêœliwe, bezwartoœciowe ¿ycie. Do tej pory okoliczne dzikusy dba³y jedynie o w³asne przetrwanie. Mam koloniê - jedyne miejsce w Sonorze, gdzie cz³owiek ¿yje dla czegoœ *wiêcej*... Jednak ty tego nie zrozumiesz.}
{294} {} {Tak. Bywaj.}
{295} {} {Ranger? Zwyk³y przestêpca, który wyobra¿a sobie, ¿e jest bohaterem. Dobra robota. Oto Twoje 200 kapsli.}
{296} {} {Hej, wynegocjowaliœmy 300!}
{297} {} {Twoja pamiêæ Ciê zawodzi. Nie dostaniesz wiêcej.}
{298} {} {A wiêc to tak... Ok, pa.}
{299} {} {Jakieœ sugestie, co to mo¿e byæ?}
{300} {} {Najprawdopodobniej w ruinach pojawi³a siê jakaœ istota lub osiad³ gang. Dowiesz siê dok³adnie, kiedy znajdziesz zaginione patrole.}

{301} {} {Jeden z twoich podw³adnych jest winien 100 kapsli w barze.}
{302} {} {S³ysza³em te plotki, ale nie zamierzam wtr¹caæ siê przy tak ma³ej kwocie.}
{303} {} {Wiêc bêdê interweniowaæ.}
{304} {} {Hmm. Jak chcesz. Wydam moim ludziom rozkaz, aby was nie tykali podczas walki.}

{305} {} {Chcê mojej nagrody. W ruinach osiad³ Ranger, ale ju¿ nie ¿yje.}
{306} {} {W ruinach osiad³ Ranger, ale ju¿ opuœci³ Flagpool.}
{307} {} {Ranger? Nieoczekiwane, ale przewidywalne wydarzenie. Domyœla³em siê, ¿e prêdzej czy póŸniej bêdziemy mieli problemy z tymi typami.}
{308} {} {A co z kas¹?}
{309} {} {Za ma³o zrobi³eœ, aby otrzymaæ ca³¹ kwotê. Ale zap³acê ci 50 kapsli za informacje.}
{310} {} {Hej, dogadaliœmy siê na 300!}
{311} {} {Lepsze to ni¿ nic.}
{312} {} {Nasza umowa mia³a na celu *naprawienie* problemu, a nie oddalenie go. Lepiej wyjdŸ, zanim zmieniê zdanie.}
{313} {} {Grrrr!}
{314} {} {Ok, wyjdê.}
{315} {} {Jeœli to ¿art, mo¿e ciê kosztowaæ ¿ycie. Wynoœ siê st¹d, zanim zmieniê zdanie.}
{316} {} {Ok, wyjdê.}
{317} {} {Trudno uwierzyæ, ¿e ch³op by³ w stanie rozwi¹zaæ wszystkie te problemy. Jeszcze bardziej dziwi mnie twój zapa³. W koñcu twoi wspó³plemieñcy przebywaj¹ na wolnoœci ju¿ od dawna.}
{1317} {} {Trudno uwierzyæ, ¿e ch³opka by³a w stanie rozwi¹zaæ wszystkie te problemy. Jeszcze bardziej dziwi mnie twój zapa³. W koñcu twoi wspó³plemieñcy przebywaj¹ na wolnoœci ju¿ od dawna.}
{318} {} {Po prostu ludzie w Villi dotrzymuj¹ s³owa. Jeœli obiecujê, ¿e wykonam pracê, to j¹ wykonujê. Adios, nadzorco.}
{319} {} {Zycie na wsi jest nudne. Chcia³em tylko przygody. No i mam, szefie.}
{320} {} {To s¹ twoje problemy. Interesuj¹ mnie inne pytania.}
{321} {} {Jesteœ tylko powodem bólu g³owy. Trzeba z tob¹ skoñczyæ!}
{322} {} {W twoich s³owach mo¿e byæ trochê prawdy. Muszê o nich pomyœleæ.}
{323} {} {Niewolnictwo to nadal niewolnictwo, nie ukryjecie tego. I muszê ciê powstrzymaæ, zanim bêdzie za póŸno.}
{324} {} {Twoje s³owa daj¹ do myœlenia. Czy mo¿esz mi powiedzieæ coœ jeszcze?}
{325} {} {Obóz Winon jest opanowany przez dzikusów. Potrzebujê pomocy!}
{326} {} {Cholerne dzikusy! Znowu przeszkadzaj¹ w najbardziej nieodpowiednim momencie. Tereny ³owieckie s¹ zbyt wa¿ne dla miasta. Bêdziemy musieli przydzieliæ ludzi do oczyszczenia obozu.}
{327} {} {Swietny pomys³. Ja te¿ do³¹czê na miejscu. Do zobaczenia.}
{328} {} {Jeszcze nie warto. Mo¿e uda mi siê to rozgryŸæ bez brutalnej si³y twoich najemników.}

{330} {} {Kto? JA? Uh... có¿...}
{331} {} {Nie potrzebujê tu idiotów. WyjdŸ.}
{332} {} {Whoa... Ach! Tak, tak, idê do domu. Villa to mój dom, tak.}
{333} {} {Czekaj... Co ty mówisz? Niedawno otrzymaliœmy transport niewolników z Villi. Te¿ jesteœ stamt¹d? Nic dziwnego, ¿e zosta³eœ w domu - takim idiotom nie mo¿na nawet ufaæ daj¹c ³opatê.}
{334} {} {Co to jest ³op-pata?}
{335} {} {Myœlê, ¿e szukasz swoich przyjació³. S¹ tutaj, w zagrodzie. Ale jeœli chcesz siê z nimi zobaczyæ, bêdziesz musia³ spe³niæ dla mnie ma³¹ proœbê. Rozumiesz?}
{336} {} {Och! Tak! Przyjaciele!}
{337} {} {Tak, twoi przyjaciele... Pos³uchaj mnie, kretynie. IdŸ do kopalni i zejdŸ na dó³. Tam jest du¿y szczur. Zabij szczura, a zabiorê ciê do twoich przyjació³. Jasne?}
{338} {} {Nie, chcê teraz zobaczyæ moich przyjació³!}
{339} {} {Szczur! Zabij szczura! Zabij to!}
{340} {} {Nie zobaczysz ich, dopóki nie zabijesz wielkiego szczura w kopalni. I nie denerwuj mnie ju¿ wiêcej.}
{341} {} {Ooh, z³y wujek.}
{342} {} {Szczur! Zabij szczura! Zabij to!}
{343} {} {Mój... to jest... w porz¹dku. Tak nie ma problemu.}

{344} {} {Jestem honorowym cz³onkiem Bractwa Stali. I ¿¹dam: uwolnijcie tych ludzi, bo inaczej zakon wy³aduje na was swój gniew.}
{345} {} {P-fu. Czy wszyscy w twoim Bractwie s¹ tacy? W porz¹dku. Ale sk¹d taka zmiana? W koñcu sami za¿¹daliœcie wykonania planu wszelkimi dostêpnymi œrodkami.}
{346} {} {Nie twoja sprawa. Taka jest decyzja z góry.}
{347} {} {Ok, nie chcê problemów. Wypuszczê ch³opów.}
{348} {} {Swietnie. Za³atwmy papierkow¹ robotê.}
{349} {} {Uwa¿aj, aby nie zrobiæ tego ponownie.}

{350} {} {Nadzorca Knut bije wiêŸniów.}
{351} {} {Wiem. Doceniam go za mocn¹ rêkê. Nie cofa siê, kiedy trzeba zmotywowaæ innych.}
{352} {} {Có¿, nie bêdê siê z tym k³óciæ.}
{353} {} {Ale on ich nie tylko bije, on ich zwyczajnie katuje. I to bez powodu.}
{354} {} {Zwolnij. O czym ty mówisz?}
{355} {} {Nadzorca zmusza administratora do fa³szowania raportów i zwalania ich obra¿eñ na wypadki.}
{356} {} {W ogóle mi siê to nie podoba. Da³em Knutowi woln¹ rêkê licz¹c na jego doœwiadczenie. Ale jeœli naprawdê pozwoli³ sobie na zbyt wiele, to nie zostawiê tak tego. Pracownicy s¹ zbyt kosztowni, aby ich tak traktowaæ.}
{357} {} {Mo¿e móg³bym to za³atwiæ i go odpaliæ?}
{358} {} {Nie pytam ciê o opiniê, co robiæ. Ale jeœli nie k³amiesz, zast¹pienie Knuta nie bêdzie ³atwe. Bêdê szuka³ zamiennika, ale nie s¹dzê, ¿e znajdê go w najblizszym czasie... Proszê, weŸ piêæ kapsli za informacje.}
{359} {} {Dziêkujê sir.}
{360} {} {[OdejdŸ cicho]}
{361} {} {O Knucie. Znam jednego odpowiedniego kandydata...}
{362} {} {...Ok. Nie mam nic przeciwko rezygnacji Knuta ze stanowiska. Fajnie bêdzie patrzeæ, jak jeden nadzorca zajmuje siê innym. Chocia¿ nadal nie rozumiem, co ci tak na tym zale¿y.}
{363} {} {Niewa¿ne.}
{364} {} {Po prostu nienawidzê niesprawiedliwoœci.}