{100} {} {Widzisz dziecko.}
{101} {} {Widzisz dziecko z rodziny kolonistów.}
{102} {} {Powiem wszystkim, ¿e œmierdzisz!}
{103} {} {Zzz...}
{104} {} {Jest tam, w ruinach, przy wejœciu do miasta.}

# Uwagi dotycz¹ce odpowiedzi
{110} {} {Czeœæ!}
{111} {} {Pobawisz siê ze mn¹?}
{112} {} {Wcale nie jesteœ przera¿aj¹cy.}
{113} {} {Nie mam nic do roboty.}
{114} {} {Nie wolno mi iœæ do ruin.}

{115} {} {Trzymaj siê ode mnie z dala!}
{116} {} {Powiedziano mi, ¿ebym z tob¹ nie rozmawia³.}
{117} {} {Jesteœ z³y!}
{118} {} {Zostaw mnie w spokoju albo bêdê krzyczeæ.}
{119} {} {Czy naprawdê jesz dzieci?}

{120} {} {Czeœæ.}
{121} {} {Czeœæ.}
{122} {} {Czeœæ.}
{123} {} {Czeœæ.}
{124} {} {Czeœæ.}

{200} {} {Uh, czeœæ. Szukasz kogoœ?}
{201} {} {Nie, nikogo, uspokój siê.}
{202} {} {Tak. Szukam ma³ych z³odziei.}
{203} {} {Niczego nie ukrad³em! To nie by³em ja!}
{204} {} {Naprawdê?}
{205} {} {Tak... naprawdê...}
{206} {} {Wiem, ¿e ukrad³eœ rzeczy osobiste panny Brandley. Ale nie martw siê - nikomu nie powiem.}
{207} {} {Có¿... Chcia³em tylko pomóc tacie. Nie ma ¿adnych kapsli, którymi móg³by zap³aciæ za dom, wiêc mogliœmy zostaæ st¹d wyrzuceni. A ta paskudna ciocia zawsze mia³a kapsle. Ale w portfelu nie by³o zbyt wiele.}
{208} {} {Gdzie zabra³eœ resztê rzeczy?}
{209} {} {Przestañ k³amaæ, bo inaczej bêdzie gorzej.}
{210} {} {Wyrzuci³em je na z³omowisku niedaleko wejœcia do miasta. By³o tam kilka mi³osnych notatek i wiadomoœci... Ale nikomu nie powiesz, prawda? Chcia³em tylko pomóc tacie, wiêcej tego nie zrobiê!}
{211} {} {Mo¿ecie spaæ spokojnie. Rozumiem to.}
{212} {} {Ile kapsli mia³a w portfelu? Daj mi wszystko, a zapomnê o Twojej winie.}
{213} {} {Cokolwiek pan powie... Oto piêæ kapsli.}
{1213} {} {Cokolwiek pani powie... Oto piêæ kapsli.}
{214} {} {Mhm.}
