{100} {} {Widzisz kolonistê.}
{101} {} {Widzisz obywatela kolonii.}
{102} {} {Chcê spaæ, zostaw mnie w spokoju.}
{103} {} {Zzz...}
{104} {} {...}
{105} {} {}
{106} {} {* ziewa *}
{107} {} {Sk¹d siê tu wzi¹³eœ?}
{108} {} {Chcê spaæ, zostaw mnie w spokoju.}

# Plywajace repliki (s¹ to odpowiedzi podczas proby mowienia)
{110} {} {S³ysza³eœ o godzinie policyjnej? Nie mo¿na wtedy wychodziæ na zewn¹trz.}
{111} {} {Jak dot¹d to najbezpieczniejsze miasto w Arizonie.}
{112} {} {Czasami brakuje mi nocnych œwiate³ Phoenix.}
{113} {} {Moje ¿y³y dr¿¹, kiedy widzê Fabera.}
{114} {} {Podobno w opuszczonych ruinach pojawili siê bandyci.}
{115} {} {Kiedy przyjedzie nowy dyli¿ans?}
{116} {} {Nigdy nie ufaj s³u¿¹cemu.}
{117} {} {Trochê siê bojê wchodziæ na teren garnizonu.}
{118} {} {Nie przegap wieczornego kazania.}
{119} {} {Podatki s¹ wysokie, ale warto.}
{120} {} {Ze szczytu Humphreys Peak rozci¹gaj¹ siê wspania³e widoki.}

{150} {} {Teraz bojê siê wyjœæ na zewn¹trz nawet w dzieñ.}
{151} {} {Nawet legowisko skorpionów jest bezpieczniejsze ni¿ to miasto.}
{152} {} {Nie powinniœmy byli siê tu przeprowadzaæ.}
{153} {} {Jak mogliœmy siê myliæ co do Roya Fabera?}
{154} {} {Mówi¹, ¿e na przedmieœciach s¹ bandyci.}
{155} {} {Jest coraz mniej karawan.}
{156} {} {Zatrudniæ pokojówkê? Teraz nie ma na to szans.}
{157} {} {Nie ma teraz szans na bezpieczne dostanie siê do garnizonu.}
{158} {} {Niech ten kaznodzieja najpierw nauczy bandytów.}
{159} {} {I za co my p³acimy te podatki?}
{160} {} {Jak tylko poczujê zapach sma¿onego miêsa, pobiegnê na Humphreys Peak.}