{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz stra¿nika. Wygl¹da na zmêczonego po d³ugiej podró¿y.}

{110} {} {Co by tu porobiæ przed wyruszeniem w trasê?}
{111} {} {Chcesz czegoœ?}
{112} {} {ObudŸ mnie, gdy zaczniemy siê pakowaæ.}
{113} {} {Ta ruda jest strasznie po¿¹dana na po³udniu.}
{114} {} {Ka¿da podró¿ mo¿e byæ twoj¹ ostatni¹.}
{115} {} {Nie wiem, co bym zrobi³, gdyby nie by³o tu kolonii.}
{116} {} {Porozmawiaj z szefem, jestem tylko stra¿nikiem.}
{117} {} {Zwykle nie bierzemy dodatkowych osób.}
{118} {} {Raz burze piaskowe zatrzyma³y nas w San Brahmin na ca³y tydzieñ.}
{119} {} {Ta wyprawa bêdzie trudna.}