{100} {} {Widzisz Kupca Joshuê.}
{101} {} {Widzisz zarz¹dcê karawany. Na jego skórze widaæ br¹zow¹ opaleniznê po niezliczonych dniach na s³oñcu.}
{102} {} {Mi³ej podró¿y.}
{103} {} {Oto Phoenix, najwiêksze miasto na pustkowiu. Tutaj zawsze powinieneœ mieæ siê na bacznoœci.}

{200} {} {Co teraz?}
{201} {} {Do widzenia.}

# Pierwszy dialog
{210} {} {Szukasz kogoœ?}
{211} {} {Mo¿e. Kim jesteœ?}
{212} {} {Nie ma go tutaj. Czeœæ.}
{213} {} {Nie s¹dzê, ¿ebyœmy mogli robiæ z tob¹ interesy. Pracujemy tylko z administracj¹ tej kopalni.}
{214} {} {Co robisz?}
{215} {} {Zwykle przewozimy ciê¿kie ³adunki. A co?}
{216} {} {Hmm, mam tylko pytania na ten temat.}
{217} {} {Nic. Bywaj.}
{218} {} {Masz chwilê? Chcê dowiedzieæ siê wiêcej o twojej pracy.}

#Zapytania
{220} {} {Smia³o. Co masz na myœli?}

{221} {} {Gdzie prowadzi trasa Twojej karawany?}
{222} {} {Naszym celem jest miasto Phoenix na po³udniu. Po drodze mamy ma³e postoje przy trasie 17 i mijamy San Brahmin.}
{223} {} {Opowiedz mi o San Brahmin.}
{224} {} {Du¿e miasto w drodze do Phoenix. Miejscowi zajmuj¹ siê g³ównie hodowl¹ byd³a i dlatego widz¹ w nas, nieznajomych, jedynie kupuj¹cych braminy.}
{225} {} {Opowiedz mi o Phoenix.}
{226} {} {To najwiêksze miasto, jakie znam. Wszystko, co mo¿na znaleŸæ, znajdziesz w Phoenix, ale musisz byæ ostro¿ny. Miasto nie jest bezpieczne, nawet po przejêciu w³adzy przez wyznawców ognia.}
{227} {} {Kierujê siê na po³udnie. Ale dlaczego mia³bym dzieliæ siê z tob¹ zawi³oœciami mojego rzemios³a?}
{228} {} {Czciciele ognia?}
{229} {} {Dziwni ludzie. Czcz¹ przedwojenn¹ energiê atomow¹ - to wszystko, co rozumiem. Jest zbyt wiele s³ów, by siê w nie zag³êbiaæ. Ale te¿ nie siedz¹ bezczynnie - to dziêki nim Phoenix sta³o siê prawdziwym miastem.}

{230} {} {Jaki rodzaj ³adunku przewozisz?}
{231} {} {Uran wydobywany tutaj, w tej kopalni.}
{232} {} {Kto tego potrzebuje?}
{233} {} {Ka¿dy, kto ma dobre, stare technologie j¹drowe. Ale to czciciele ognia w Phoenix jako pierwsi kupuj¹ uran, a nastêpnie jest on sprzedawany mniejszym nabywcom za piêæ razy wy¿sz¹ cenê.}
{234} {} {Czy uran nie powoduje choroby popromiennej?}
{235} {} {Powoduje... jeœli masz z nim kontakt przez ca³y dzieñ. Ta ruda jest s³abo radioaktywna i nieszkodliwa, dopóki nie znajdzie siê w reaktorze. Wtedy najlepiej trzymaæ siê jak najdalej.}

{236} {} {Czy zdajesz sobie sprawê, ¿e pomagasz niezupe³nie... uczciwym ludziom?}
{237} {} {Masz na myœli najemników Fabera? Nie obchodzi mnie to. Ja i moi ludzie potrzebujemy pracy. A kolonia zapewnia nam i miejsca pracy i stabilne zarobki. To mi wystarczy.}
{238} {} {Zap³acê 30 kapsli.}
{239} {} {To wiele zmienia.}
{240} {} {I co z tego?}
{241} {} {Nie mo¿na nawet polegaæ na kurzu drogowym w nieszczelnych kieszeniach.}
{242} {} {Ups, gdzie to jest...}
{243} {} {Lokalna sekta czc¹ca energiê atomow¹. To prawda, ¿e po zniszczeniu ich g³ównej œwi¹tyni niewiele z nich pozosta³o. Tak czy inaczej, to w³aœnie z nimi Phoenix sta³o siê prawdziwym miastem.}

# Nadzwyczajne poprawki
{250} {} {...Mówiê ci - nigdzie siê nie wybieramy... Czekaj, nie jesteœ z administracji, prawda? Wiêc zapomnij.}
{251} {} {O co chodzi z karawan¹?}
{252} {} {Znasz najnowsze wieœci? Kopalnia nied³ugo zostanie zamkniêta, co oznacza równie¿ nasz¹ dzia³alnoœæ.}
{253} {} {Co jest nie tak z kopalni¹?}
{254} {} {Do widzenia.}
{255} {} {Kopalnia jest zniszczona, a jej oczyszczenie zajmie du¿o czasu i wysi³ku. W¹tpiê, czy to miejsce bêdzie mia³o przysz³oœæ.}
{256} {} {Po zatomizowaniu czcicieli ognia w Phoenix kopalnia straci³a swojego g³ównego klienta. Oczywiœcie dalej jest popyt na rudê i inne osady s¹ gotowe do jej zakupu, ale raczej nie op³aci siê to pracy kopalni.}
{257} {} {Garnizon Flagpool zmia¿d¿ony, wiêŸniowie uciekli, zarz¹dca nie ¿yje. Teraz nawet nie wiemy, dla kogo pracujemy. Wygl¹da na to, ¿e nie jesteœmy ju¿ tu potrzebni.}
{258} {} {Jesteœcie karawaniarzami. Nie obchodzi Ciê, dla kogo pracujesz?}
{259} {} {Mamy bardzo wyj¹tkow¹ reputacjê. Ze wzglêdu na powi¹zania z czcicielami ognia i najemnikami Fabera nie ka¿dy bêdzie chcia³ z nami pracowaæ. Konkurenci nie lubi¹ nas tym bardziej z powodu zazdroœci. Po ostatnich wydarzeniach zmiana pracodawców bêdzie bardzo trudna. Jeœli to w ogóle mo¿liwe.}
{260} {} {Wiêc anulowaliœcie wszystkie trasy?}
{261} {} {Dok³adnie. Dopóki sytuacja siê nie poprawi, bêdziemy musieli pozostaæ w Flagpool. Nie wiem jeszcze, co bêdziemy robiæ, ale coœ wymyœlimy.}

# Podrozuj na po³udnie
{300} {} {Hej, zabierzesz mnie do Phoenix?}
{301} {} {Nie zabieramy ¿adnych dodatkowych towarzyszy. Klient siê denerwuje, gdy do konwoju do³¹czaj¹ niezweryfikowane osoby.}
{302} {} {Mo¿e móg³byœ w takim razie przynajmniej odpowiedzieæ na kilka pytañ?}
{303} {} {W takim razie do widzenia.}
{304} {} {W Phoenix czekaj¹ na nas tylko szubienice na latarniach. Nie wiemy jeszcze, co mamy zrobiæ.}
{305} {} {Trudny przypadek.}
{306} {} {W Phoenix ucina siê jêzyki za oszustwa. Masz szczêœcie, ¿e nie jesteœmy w Phoenix.}
{307} {} {Uch, zapamiêtam to...}

{310} {} {500 kapsli pozwala mnie zweryfikowaæ?}
{311} {} {Ok. Dobra, znajdê dla ciebie miejsce. Zabiorê ciê do eskorty, ale na zasadach ogólnych.}
{312} {} {Oto kapsle. Jakie s¹ warunki?}
{313} {} {Innym razem.}
{314} {} {}
{315} {} {Hmm. Masz coœ w sobie, wiêc zabiorê ciê do eskorty. Ale pod pewnymi warunkami.}
{316} {} {Jakie to warunki?}
{317} {} {Zróbmy to innym razem.}
{318} {} {Z doœwiadczenia nauczyliœmy siê, aby nie ufaæ niezweryfikowanym osobom.}
{319} {} {W takim razie do widzenia.}

{320} {} {Przede wszystkim baga¿ nie przekracza 50 funtów. Po drugie, zatrzymamy siê w San Brahmin na noc przed wyruszeniem do Phoenix. Pasuje? To przyjdŸ, kiedy bêdziesz gotowy.}
{321} {} {Swietnie, daj mi czas na spakowanie siê.}
{322} {} {Mogê siê przydaæ w drodze. Nie potrzebujesz darmowego pracownika?}
{323} {} {Nie powinieneœ odmawiaæ.}

{330} {} {Chcê jechaæ z karawan¹.}
{331} {} {Za du¿o niesiesz! Nie zamierzam straciæ ca³ej karawany przez Ciebie!}
{332} {} {Czy te rzeczy te¿ zamierzasz ze sob¹ zabraæ? To nie przejdzie. Nie zamierzam spowalniaæ ca³ej karawany przez ciebie. Zabierz ze sob¹ tylko najpotrzebniejsze rzeczy i nie wiêcej ni¿ 50 funtów.}
{333} {} {Ok, spróbujê zmniejszyæ mój baga¿.}
{334} {} {Zajmij siê swoimi sprawami. Nie wp³ynie to w ¿aden sposób na Twoj¹ karawanê.}
{335} {} {Lepiej porozmawiajmy o twojej pracy.}
{336} {} {Ok. Ale nikt nie bêdzie nosi³ twoich rzeczy za ciebie i nie bêdzie czeka³, jeœli zostaniesz w tyle. Jeœli zostaniesz w tyle, obwiniaj siebie.}
{337} {} {Zaden problem.}
{338} {} {(Po nocy ze stra¿nikami udajesz siê w koñcu na po³udnie)}
{339} {} {[Wyrusz w podró¿]}

# Inne lokalizacje
{400} {} {Bêdziemy tu jeden dzieñ. Mo¿esz siê rozejrzeæ, jeœli chcesz. Pamiêtaj jednak, ¿e karawana nie bêdzie na ciebie czekaæ, jeœli siê spóŸnisz.}
{401} {} {Opowiedz mi o San Brahmin.}
{402} {} {Miasto San Brahmin. To trochê zamkniêta spo³ecznoœæ, nie lubi¹ tu obcych, ale zawsze s¹ gotowi do handlu z nimi. Nie mieszaj siê do lokalnego ba³aganu, jeœli chcesz znaleŸæ z nimi wspólny jêzyk.}
{403} {} {Postaram siê nie spóŸniæ.}
{404} {} {[Poczekaj, a¿ karawana pojedzie do Phoenix]}
{405} {} {WyjdŸcie beze mnie, spóŸniê siê.}
{406} {} {Cokolwiek powiesz.}
{407} {} {Ok.}