{100} {} {Widzisz kolonistê.}
{101} {} {Widzisz obywatela kolonii.}
{102} {} {Jest godzina policyjna. Natychmiast st¹d wyjdŸ.}

#Dialog
{200} {} {Hej, nie widzisz? Ten dom jest zajêty. Czego chcesz?}
{201} {} {Niemi³o tak witaæ goœcia.}
{202} {} {Kto powiedzia³, ¿e jesteœ goœciem? Wszyscy znaj¹ tu wszystkich, to ma³e miasto. A twoja twarz jest mi obca.}
{203} {} {Wzajemnie.}
{204} {} {Pomó¿ mi.}
{205} {} {Masz coœ przeciwko kilku pytaniom?}
{206} {} {Bêdê o tym pamietaæ.}
{207} {} {Dobrze, ¿e siê rozumiemy.}
{208} {} {Dziêki za radê. Przepraszam za k³opoty.}
{209} {} {Dobre maniery? To coœ nowego.}

{210} {} {Czego chcesz?}
{211} {} {Do widzenia.}

{212} {} {Sk¹d taka niechêæ do obcych?}
{213} {} {Tylko dzikusy mieszkaj¹ na pó³noc od Phoenix. Czy nie mam racji? Jesteœ stamt¹d?}
{214} {} {Nie. Pochodzê z ma³ej wioski na zachodzie.}
{215} {} {Wiêc jesteœ ch³opem? Kopanie w ziemi i tak dalej, co?}
{1215} {} {Wiêc jesteœ ch³opk¹? Kopanie w ziemi i tak dalej, co?}
{216} {} {Dok³adnie. W przeciwieñstwie do miejskich robaków jestem przynajmniej zajêty wa¿n¹ prac¹.}
{1216} {} {Dok³adnie. W przeciwieñstwie do miejskich robaków jestem przynajmniej zajêta wa¿nymi sprawami.}
{217} {} {W³aœciwie to nie. Dlaczego to takie wa¿ne?}
{218} {} {W pewnym sensie. Aby zebraæ plony, trzeba pracowaæ od œwitu do zmierzchu.}
{219} {} {Có¿, ludziom takim jak ty trudno jest zrozumieæ uroki ¿ycia na po³udniu - gdzie odradza siê *prawdziwa* cywilizacja. Czy to wszystkie pytania?}
{220} {} {Niezupe³nie.}
{221} {} {Do widzenia.}
{222} {} {Jestem z Phoenix.}
{223} {} {Och, naprawdê? ... Mam nadziejê, ¿e podoba ci siê nasza ma³a kolonia. Jakieœ pytania?}
{224} {} {W³aœciwie tak.}
{225} {} {Nie twoja sprawa.}
{226} {} {W takim razie nie zadawaj mi g³upich pytañ.}
{227} {} {Tak.}
{228} {} {}
{229} {} {Mi³o ciê widzieæ.}

{230} {} {Co robisz w tej kolonii?}
{231} {} {Kiedy mój m¹¿ jest zajêty s³u¿b¹ w garnizonie, ja pilnujê jego domu. Kiedyœ nazywano to „gospodarstwem domowym”. Powtórzyæ?}
{232} {} {Myœlê, ¿e wiem, co to znaczy.}
{233} {} {Podoba ci siê tutaj?}
{234} {} {Có¿... Jest tu trochê nudno. Gdyby nie mój m¹¿, wola³abym zostaæ w Phoenix. Niemniej jednak mo¿na tu mieszkaæ i pracowaæ, a garnizon chroni przed wszelkiego rodzaju mot³ochem. Mo¿esz tu nawet zatrudniæ s³u¿¹cego, jeœli nie szkoda ci kapsli. Niewiele jest miejsc na œwiecie, w których mo¿esz to zrobiæ.}
{235} {} {Zartujesz sobie ze mnie? Po ucieczce wiêŸniów nie mogê nawet wyjœæ na ulicê bez no¿a! Nie znajdziesz gorszego miejsca w ca³ej Arizonie. Nawet Phoenix by³o spokojniejsze.}
{236} {} {Czy w takim razie mogê zadaæ inne pytanie?}
{237} {} {Rozumiem. Có¿, z przyjemnoœci¹ tu zostanê.}
{238} {} {Od zawsze tu mieszkasz?}
{239} {} {Nie, przyjecha³am z drug¹ fal¹ kolonistów z du¿ego miasta na po³udniu.}
{240} {} {Dlaczego to zrobi³aœ?}
{241} {} {Chcia³am zacz¹æ od nowa. Myœla³am, ¿e bêdzie tu wiêcej wolnoœci i mo¿liwoœci.}