{100} {} {Widzisz kolonistê.}
{101} {} {Widzisz obywatela kolonii.}
{102} {} {Co robisz tutaj o godzinie policyjnej?}
{103} {} {Mam lepsze rzeczy do roboty ni¿ rozmawianie z nieznajomymi.}
{104} {} {Nie denerwuj mnie. Po œmierci syna nie jestem sob¹.}
{105} {} {Och, nie...}
{106} {} {...nie mogê... oddychaæ...}

#Dialog
{200} {} {Czekaj, nie zbli¿aj siê do mnie! Co tu robisz o godzinie policyjnej?}
{201} {} {Szukam wichrzyciela, który psuje ¿ycie miejscowemu kaznodziei.}
{202} {} {Wiêc jesteœ z tym kultyst¹? Nie chcê ciê widzieæ! Idê do domu. I nie wa¿ siê za mn¹ pod¹¿aæ.}
{203} {} {Myœlê, ¿e nie ma takiej potrzeby.}
{204} {} {Poczekaj, wróæmy trochê.}

{210} {} {Czego ode mnie chcesz?}
{211} {} {Nie przejmuj siê mn¹.}
{212} {} {Co s¹dzisz o kulcie Swiêtego Ognia?}
{213} {} {Nigdy nie lubi³em tego kultu. Co to za szalony pomys³ - czciæ stare rzeczy i jakiœ mityczny ogieñ? Ka¿da normalna osoba ma lepsze rzeczy do roboty.}
{214} {} {Czy kaznodzieja nie uzdrawia i nie naucza?}
{215} {} {Tak... jeœli dobrze go op³acisz kilkoma kapslami, a potem pos³uchasz jakichœ idiotycznych bzdur. Ci¹gle tylko gada o tych bzdurach o blasku, genach dzier¿awionych i innych atomach. Ca³y Koœció³ Swiêtego Ognia sk³ada siê z takich szarlatanów, którzy pomagaj¹ jedynie za ogromne datki.}
{216} {} {Ca³kowicie podzielam twoj¹ nienawiœæ do tego g³upiego kultu. Co mo¿emy zrobiæ?}
{217} {} {Muszê ciê zostawiæ z twoim sceptycyzmem. Czeœæ.}
{218} {} {Hmm. Nie wiem, czy ci wierzê. Ale jeœli naprawdê chcesz oczyœciæ miasto z tego brudu, to s¹ 2 wyjœcia - albo zabijemy tego sekciarza, albo samo miasto go wypêdzi.}
{219} {} {Jak to zrobiæ?}
{220} {} {Nie mam pojêcia. Jeœli zaatakujemy go otwarcie, miasto nie zostawi tego tak ³atwo. Zbyt wielu ludzi w kolonii wierzy w jego bzdury. Musimy go wyeliminowaæ po cichu.}
{221} {} {Jeœli dobrze mi siê to op³aci, uwolniê miasto od kaznodziei.}
{222} {} {Problem wymaga czasu do namys³u. Wrócê póŸniej.}
{223} {} {Mówi¹, ¿e twoi krewni byli niewolnikami. W takim razie powinieneœ wiedzieæ, ¿e sekciarz pob³ogos³awi³ najemników za to „pobo¿ne” przedsiêwziêcie. Niektórzy z twoich krewnych zostali zabrani przez innych czcicieli ognia i wywiezieni gdzieœ poza miasto. Jeœli to nie wystarczy, pomyœl o lekarstwach, które kultysta otrzymuje z po³udnia. Tam dopiero jest prawdziwa „¿y³a uranu”, co?}
{224} {} {Jak siê cieszê, ¿e ciê widzê!}
{225} {} {Mi³o ciê widzieæ.}
{226} {} {Hiram opowiada historiê mojego syna w niedzielnych kazaniach. Teraz nic nie zale¿y ode mnie.}

{230} {} {Chcê, ¿ebyœ przyszed³ do œwi¹tyni i publicznie wyzna³, co zrobi³eœ.}
{231} {} {Odbi³o ci? To zwróci przeciwko mnie ca³e miasto.}
{232} {} {Nie, jeœli równie¿ przyznasz, ¿e sympatyzujesz z sekt¹.}
{233} {} {To naprawdê g³upi pomys³. Zapomnij.}
{234} {} {Bzdury! Dlaczego mia³bym to zrobiæ?}
{235} {} {Twój syn zostanie uratowany. Poza tym Hiram ju¿ wie, kto stoi za nocnymi sabota¿ami i nie odpuœci tego tak ³atwo.}
{236} {} {Cholera... Có¿, masz racjê, nie mam innego wyboru.}
{237} {} {Kultysta musia³ naprowieniowaæ twój mózg. Zostaw mnie.}
{238} {} {Ok. Ale jak coœ to obwiniaj siebie.}
{239} {} {Cholera, nawet daleko od Phoenix, ci szaleni czciciele ognia nie mog¹ odpuœciæ... Dobra, porozmawiam z Hiramem. Spróbujê znaleŸæ z nim wspólny jêzyk, ale tylko po to, aby unikn¹æ konfliktu.}
{240} {} {Swietnie, tak trzymaj.}
{241} {} {Za³atwione - Hiram odszed³.}
{242} {} {Ach, wspania³e wieœci. Teraz, gdy ten fanatyk odszed³, miastu bêdzie lepiej. WeŸ sto kapsli, zas³ugujesz na nie.}
{243} {} {A co z leczeniem twojego syna?}
{244} {} {Hiram uratowa³ twojego syna.}
{245} {} {NieŸle. Bywaj.}

{250} {} {Dlaczego próbujesz przepêdziæ tego kultystê?}
{251} {} {Idiotyczny kult prania mózgu ludziom i wyci¹gania od nich kapsli jest *ju¿* dobrym powodem. Ale jest jeszcze jeden - to mój syn, który cierpi na skutki promieniowania.}
{252} {} {Smutna historia, zmieñmy temat.}
{253} {} {Hiram odmówi³ swojej pomocy?}
{254} {} {Domaga³ siê konwersji. Oczywiœcie nie chodzi³o o mnie, ale mojego syna. Powinien zostaæ s³ug¹ w œwi¹tyni, chodziæ na zajêcia i poranne modlitwy. Cholera. Odeszliœmy od tych przeklêtych fanatyków, ale oni wci¹¿ wkradaj¹ siê do naszego ¿ycia osobistego.}
{255} {} {Nawet kapsle nie pomagaj¹?}
{256} {} {Lokalna œwi¹tynia to tylko ga³¹Ÿ g³ównej œwi¹tyni Phoenix. Posiadaj¹ kapsli pod dostatkiem. Dlatego Hiram ma wystarczaj¹ce œrodki na utrzymanie. Najwa¿niejsze jest, aby narzuci³ kolonistom swoj¹ g³upi¹ wiarê. I na niczym siê nie zatrzyma.}
{257} {} {Mogê pomóc w leczeniu, skoro tak mówisz.}
{258} {} {Naprawdê? Bêdê zadowolony z ka¿dej pomocy i zap³acê, ¿eby tylko nie anga¿owaæ siê w tê sektê.}
{259} {} {Uda³o mi siê wyleczyæ twojego syna. Bez uciekania siê do us³ug koœcio³a.}
{260} {} {Hiram uzdrowi³ twojego syna na znak pojednania.}
{261} {} {Jak siê cieszê! Dziêkujê Ci! Masz 100 kapsli za swe us³ugi.}
{262} {} {Nie leczê z powodu kapsli. Zatrzymaj je dla siebie i b¹dŸ szczêœliwy.}
{263} {} {Jesteœ niesamowit¹ osob¹. Opowiem wszystkim o twoich zas³ugach. Dziêki jeszcze raz.}
{264} {} {Proszê.}
{265} {} {Swietnie, pokryj¹ koszty leków.}
{266} {} {Jeszcze raz dziêkujê.}
{267} {} {Nie ma za co.}
{268} {} {Zobaczê, co mogê zrobiæ.}
{269} {} {Przeklêci kultyœci! Nie myœl, ¿e teraz jestem ci coœ winien. Ale postaram siê ju¿ wiêcej nie przeszkadzaæ kaznodziei.}
{270} {} {No to mamy umowê.}
{271} {} {Co to za problem kupiæ lekarstwo na chorobê popromienn¹?}
{272} {} {Hiram otrzymuje zapasy medyczne z g³ównej œwi¹tyni na po³udniu. Nie ma tu innego Ÿród³a lekarstw. No, od czasu do czasu jeszcze karawany przywo¿¹ ma³a zapasy, ale po zawy¿onych cenach i mnie po prostu nie staæ.}