{100} {} {Widzisz najeŸdŸcê.}
{101} {} {Widzisz wytatuowanego mê¿czyznê z wypuk³ymi rysami czaszki. Nie jest ani trochê podobny do innych mieszkañców Flagpool.}
{102} {} {Opuszczamy te ziemie.}
{103} {} {To nasza ziemia!}

{200} {} {Stój. Bezczeœcisz te ziemie. Powstrzymanie ciê le¿y w naszej mocy.}
{201} {} {Uch...}
{202} {} {Nie ma tu miejsca dla kogoœ takiego jak ty.}
{203} {} {[Broñ siê]}
{204} {} {Przybywam w pokoju. Rolnik mówi, ¿e zabra³eœ jego dom i ziemie.}
{1204} {} {Przybywam w pokoju. Rolnik mówi, ¿e zabra³eœ jego dom i ziemie.}
{205} {} {Obcy jest tak samo wype³niony hipokryzj¹ jak wszyscy inni. Przybyliœcie na te ziemie, zabiliœcie naszych ludzi i zajeliœcie nasze ziemie. Odbieramy co nasze z powrotem.}
{206} {} {Jesteœcie zwyk³ymi z³odziejami.}
{207} {} {Nie znam tej historii. O czym ty mówisz?}
{208} {} {Nie wiesz. Nasi przodkowie mieszkali tu od trzech pokoleñ. Potem przyszli ludzie Fabera i zabrali wszystkich do pracy, a ci, którzy siê nie zgadzali, zostali zabici. Byliœmy jedynymi, którzy zostali, bo byliœmy dzieæmi. Teraz chcemy siê zemœciæ. Krew za krew jak ka¿e zwyczaj.}
{209} {} {Ale farmer jest niewinny. Zostaw go w spokoju.}
{210} {} {Pozwoliliœmy mu zachowaæ ¿ycie. Pozwoliliœmy mu odejœæ. W ka¿dym razie, my siê nigdzie nie wybieramy.}
{211} {} {[Poka¿ œrodkowy palec]}
{212} {} {Hej, nie chcê z wami walczyæ...}
{213} {} {Przykro mi to s³yszeæ. Ale rolnik nie jest niczemu winny. Jest cywilem, a nie najemnikiem, zostaw go w spokoju.}
{214} {} {Wiemy. Dlatego ¿yje i mo¿e odejœæ.}
{215} {} {W³o¿y³ du¿o pracy w tê skromn¹ ziemiê. Powinniœcie doceniæ jego wysi³ki.}
{216} {} {Mo¿e. Nikt z nas nie chcia³ wojny, dopóki koloniœci nie przekroczyli granicy. Ale nie mo¿emy walczyæ z ca³ym garnizonem.}
{217} {} {To jest teraz kraina kolonistów. I nic nie mo¿esz na to poradziæ. Wszystko, co mo¿esz zrobiæ, to opuœciæ Flagpool i zacz¹æ od nowa.}
{218} {} {Jeœli jesteœ taki g³odny zemsty, bêdê musia³ ciê powstrzymaæ. Zatrzymam ciê si³a.}
{219} {} {Wy, ludzie z zewn¹trz, jesteœcie zbyt pewni siebie. Ale Ty mówisz m¹drze. Myœleliœmy o tym od dawna. W walce po prostu zginiemy, a udaj¹c siê w góry, bêdziemy mieli szanse na przetrwanie naszego ludu. Niech tak bêdzie. Musimy zebraæ resztki klanu i rozwi¹zaæ ten problem. (patrzy na resztê wspó³plemieñców) Nie jesteœmy zainteresowani farm¹.}
{220} {} {M¹dra decyzja. Powodzenia.}
{221} {} {Tak, wynoœ siê st¹d... mam na myœli powodzenia i takie tam.}

{250} {} {Arrh! Cz³owiek w zbroi! Przeklêci koloniœci, co jeszcze mamy zrobiæ, by trzymaæ was z dala od naszych ziem?}
{251} {} {O czym ty mówisz?}
{252} {} {To nie s¹ moje problemy.}
{253} {} {Nie chcê z tob¹ walczyæ, cz³owieku w zbroi. Wyjdziemy. Nie œcigaj nas.}
{254} {} {Tak, wynoœ siê st¹d.}
{255} {} {O nie, najpierw musisz zap³aciæ za to co zrobi³eœ. P³acœc w³asn¹ krwi¹.}

{260} {} {Obcy... Dlaczego wygl¹dasz jak skóra mutaowoca, który by³ na s³oñcu przez ca³y dzieñ?}
{261} {} {A jak myœlisz? Ech, dooko³a sami rasiœci...}
{262} {} {Cierpisz, prawda? Cierpisz z powodu innych, którzy nie s¹ tacy jak ty. Jesteœmy tacy sami, rozumiemy Ciê.}
{263} {} {Nie wa¿ siê œmiaæ z mojego wygl¹du.}
{264} {} {W³aœciwie to jestem tu dla mojego znajomego rolnika. On te¿ jest bardzo samotny.}
{265} {} {Rolnik? Uratowaliœmy mu ¿ycie. Pozwoliliœmy mu odejœæ.}
{266} {} {Nie udawaj, w³aœnie przej¹³eœ jego ziemie. To bardzo z³a decyzja.}