{100} {} {Widzisz Randego.}
{101} {} {Widzisz brudnego rolnika. Okropnie cuchnie.}
{102} {} {S¹ tam. B¹dŸ ostro¿ny.}
{103} {} {Mi³o ciê widzieæ. Ale teraz muszê pracowaæ na mojej farmie.}

# Dialog - na mapie miasta
{200} {} {(patrzy na ciebie rozczochrany mê¿czyzna, na jego twarzy widaæ smutek) Czeœæ, nieznajomy. Chcê od razu powiedzieæ, ¿e nie mam nic wartoœciowego.}
{1200} {} {(patrzy na ciebie rozczochrany mê¿czyzna, na jego twarzy widaæ smutek) Czeœæ, nieznajoma. Chcê od razu powiedzieæ, ¿e nie mam nic wartoœciowego.}
{201} {} {Tak mówi¹ wszyscy. Poka¿, co ukrywasz.}
{202} {} {Nic nie mam. NajeŸdŸcy wyrzucili mnie z mojego domu. Jestem ¿ebrakiem i bezdomnym.}
{203} {} {Ugh, nawet patrzenie na ciebie mnie brzydzi.}
{204} {} {Przykro mi to s³yszeæ. Ale muszê z tob¹ porozmawiaæ.}
{205} {} {Widzê, ¿e jesteœ na krawêdzi. Uspokój siê, nie zamierzam ciê okraœæ.}
{206} {} {Przepraszam. Straci³em zaufanie do ludzi po tym, jak najeŸdŸcy wyrzucili mnie z farmy. Teraz jestem ¿ebrakiem i bezdomnym, jak widzisz.}
{207} {} {Przykro mi to s³yszeæ. Czy mogê do Ciebie do³aczyæ?}
{208} {} {Wiêc nie potrzebujê ciê. SiedŸ tu dalej ze swoimi smutkami, œmieciu.}
{209} {} {Nie widzê wiêcej pytañ.}
{210} {} {Tak?}
{211} {} {Na razie nic.}
{212} {} {Kim jesteœ?}
{213} {} {Jestem Randy. Przyby³em tu z kolonistami kilka lat temu i za³o¿y³em swoj¹ ma³¹ farmê z dala od wszystkich. Reszta mojej biografii raczej ciê nie zainteresuje.}
{214} {} {Czyli bandyci wywalili ciê z domu?}
{215} {} {Tak, te dupki s¹ w tym nieŸli. By³em w ich rêkach szybciej, ni¿ móg³bym powiedzieæ „kretoszczur”. W poszukiwaniu jedzenia przewrócili ca³y dom. A potem wyrzucili mnie pod go³e niebo. I powiedzieli, ¿e ju¿ tu nie mieszkam.}
{216} {} {Czy próbowa³eœ ich wyrzuciæ?}
{217} {} {Jeden kontra trzech uzbrojonych najeŸdŸców to przesada. Lepiej straciæ dom ni¿ ¿ycie.}
{218} {} {Dlaczego nie poprosiæ garnizonu o pomoc?}
{219} {} {Poniewa¿ wtedy musia³bym oddaæ im prawie wszystkie moje zbiory przez dziesiêæ nastêpnych lat. Takie s¹ warunki. A moja farma mo¿e wy¿ywiæ tylko kilka osób, nie wiêcej.}
{220} {} {Rozwi¹¿ê problem bandytów, jeœli dasz mi za to jedzenie.}
{221} {} {Nasze problemy s¹ nieco podobne. Chcê ci pomóc.}
{222} {} {Opowiedz mi o sobie.}
{223} {} {Czyli bandyci wywalili ciê z domu?}
{224} {} {Tak, oczywiœcie. Gospodarstwo dysponuje niewielkimi zapasami ¿ywnoœci. W ka¿dym razie pójd¹ do kogoœ innego. Ale nie do mnie.}
{225} {} {Poka¿ drogê.}
{226} {} {Kusz¹ca oferta, ale nie chcê zadzieraæ z najeŸdŸcami.}
{227} {} {Naprawdê ich przegonisz? By³oby super. Mam nadziejê, ¿e umiesz walczyæ, bo z nimi trudno negocjowaæ.}
{228} {} {Znajdê sposób. Po prostu wska¿ mi drogê.}
{229} {} {Rzeczywiœcie, to zbyt niebezpieczne dla jednej osoby. Przepraszam, nie mogê pomóc.}

# Dialog - na mapie farmy
{300} {} {S¹ tam. B¹dŸ ostro¿ny.}
{301} {} {Zaczekaj tutaj.}

{310} {} {To twoja farma?}
{311} {} {Oczywiœcie. To jest mój dom i moje ³ó¿ka.}
{312} {} {Mieszkasz tu sam?}
{313} {} {Tak. Na pocz¹tku by³o nas wiêcej i wszyscy pracowali na farmie. Jeden zosta³ zabity przez z³odziei przy ¿niwach, drugi zmar³ na skutek jakiejœ infekcji. Stopniowo zosta³em sam. Ale nadal nie chcê st¹d wyje¿d¿aæ.}
{314} {} {Dlaczego ta farma jest dla ciebie taka wa¿na? Okolica jest pe³na opuszczonych ziem i domów.}
{315} {} {Ta ziemia zaczê³a przynosiæ owoce dopiero z powodu naszego potu i naszej krwi! W³o¿y³em w to za du¿o pracy, ¿eby teraz oddaæ to z³odziejom.}
{316} {} {Dlaczego przy wejœciu jest znak Morrison Brothers?}
{317} {} {(zmieszany) Morrison... Niewa¿ne. Ten znak ma prawdopodobnie sto lat. Teraz *ja* jestem w³aœcicielem tej ziemi!}
{318} {} {Co wiesz o najeŸdŸcach?}
{319} {} {Mieszkali tu przed nami. To znaczy, dzikusy. Nie przystosowali siê do nowego ¿ycia, ale nauczyli siê rabowaæ. Garnizon z³apa³ prawie wszystkich, ale ta grupa okaza³a siê zbyt sprytna.}
{320} {} {Nie wspomina³eœ o tym.}
{321} {} {I? Spójrz, to tylko rabusie. Przychodz¹ i zabieraj¹ to, co do nich nie nale¿y. Nie ma siê czym przejmowaæ.}

{350} {} {NajeŸdŸcy nie ¿yj¹, Randy, mo¿esz wróciæ do swojego s³odkiego domu.}
{351} {} {Nie mogê uwierzyæ, ¿e to zrobi³eœ. Ech, twoje umiejêtnoœci bardzo by mi siê tu przyda³y... Mo¿e móg³byœ przenieœæ siê do mnie na sta³e, co?}
{352} {} {Nie mogê. Mam ju¿ dom. I jest w niebezpieczeñstwie.}
{353} {} {Do tej dziury? Nie, dziêki. W mojej rodzinnej wiosce s¹ takie plantacje, o jakich ci siê nawet nie œni³o.}
{354} {} {Có¿, skoro tak... Rozumiem. Dziêkujê za pomoc i powodzenia.}
{355} {} {Nie tak szybko. Daj mi ca³e jedzenie, jakie masz.}
{356} {} {Cieszê siê, ¿e mog³em pomóc.}
{1356} {} {Mi³o by³o Ci pomóc.}
{357} {} {Och, oczywiœcie. Jedni bandyci zastêpuj¹ innych. Nic siê nie zmienia, prawda? Mo¿esz wzi¹æ wszystko, co zosta³o w lodówce.}
{358} {} {To takie proste.}
{359} {} {Dzikusy ju¿ ci nie bêd¹ przeszkadzaæ, mo¿esz wróciæ do swojego domu.}