{100} {} {Widzisz wartownika.}
{101} {} {Widzisz jednego z lokalnych najemników. Spokojnie patroluje ulice.}
{102} {} {Cholera, mog³em ciê zastrzeliæ. Nie krêæ siê tu o godzinie policyjnej.}

{110} {} {Czeœæ.}
{111} {} {Witamy w Flagpool.}
{112} {} {PrzechodŸ dalej.}
{113} {} {Jakiœ problem?}
{114} {} {Jak mogê pomóc?}
{115} {} {Masz broñ? Jeœli tak, trzymaj j¹ w kaburze.}
{116} {} {Ciesz siê swoim czasem.}
{117} {} {W Galactic Dinner maj¹ kilka dobrych drinków, koniecznie tam wpadnij.}
{118} {} {Jeœli zobaczysz coœ podejrzanego, daj mi znaæ.}