{100} {} {Widzisz Graya.}
{101} {} {Widzisz obywatela kolonii.}
{102} {} {Chcê spaæ, zostaw mnie w spokoju.}
{103} {} {* ziewa *}
{104} {} {Zzz...}
{105} {} {Teraz bêdzie lepiej.}
{106} {} {Nie wyjdê, dopóki ten g³upi bramin nie oderwie siê od ziemi.}

# Na mapie miasta
{200} {} {Czego chcesz?}
{201} {} {Och, niczego. Tylko sobie wêdrujê, rozgl¹daj¹c siê po mieœcie.}
{202} {} {Twoje dzieci mówi¹, ¿e próbuj¹ ciê wyrzuciæ z miasta, to prawda?}
{203} {} {Tak, po utracie pracy nie mogê zap³aciæ podatku.}
{204} {} {Gdzie pracowa³eœ?}
{205} {} {By³em szefem patrolu garnizonu.}
{206} {} {Wow. Praca w garnizonie to coœ w tym mieœcie, prawda? I co siê sta³o?}
{207} {} {Tak, odebrano mi rangê po niew³aœciwym zachowaniu... mówi¹c proœciej, upi³em siê jak œwinia i pozwoli³em sobie na zbyt wiele.}
{208} {} {I nie ma tu pracy dla by³ego dowódcy?}
{209} {} {Jeœli jesteœ zmuszony zrezygnowaæ, to nie - wszyscy s¹ wobec ciebie ostro¿ni i nieprzyjaŸni.}
{210} {} {[Dalej.]}
{211} {} {Co mi zosta³o? Có¿, praca w kopalni. Ale nie, nie zrobiê tego. Mam du¿¹ rodzinê i muszê j¹ wspieraæ. Najprawdopodobniej bêdê musia³ pracowaæ jako stra¿nik karawany. A tam, niedaleko od powrotu do Phoenix.}
{212} {} {Czy to Ÿle?}
{213} {} {Przeprowadziliœmy siê tutaj w³aœnie dlatego, ¿e by³y mo¿liwoœci rozwoju i zarabiania pieniêdzy. Zrezygnowa³em ze wszystkiego, co mia³em w du¿ym mieœcie. Tam nikt na nas nie czeka. Ale jest za póŸno, ¿eby coœ zdecydowaæ. Moja kariera w Flagpool dobieg³a koñca. Szkoda. Wszystko zaczê³o siê tak dobrze.}
{214} {} {Jeœli dowiem siê o wolnych miejscach pracy na miejscu, dam ci znaæ. Czeœæ.}
{215} {} {Smutna historia. Có¿, muszê iœæ.}
{216} {} {Nowy nadzorca w kopalni nie wype³nia swoich obowi¹zków jak nale¿y. Móg³byœ zaj¹æ jego miejsce.}

{220} {} {Kopalnia potrzebuje nowego nadzorcy. Móg³byœ zaj¹æ miejsce tego tyrana.}
{221} {} {Nadzorca? Znam go, to z³y cz³owiek. I wydaje mi siê, ¿e z jego g³ow¹ nie wszystko jest w porz¹dku.}
{222} {} {Okalecza niewolników, a potem obwinia o to wypadki. Pracownicy chc¹ nowego nadzorcy.}
{223} {} {Jest ma³o prawdopodobne, aby dobrowolnie odszed³ ze stanowiska. Jak mam to obejœæ?}
{224} {} {Zostaw to mnie. Za³atwiê to.}
{225} {} {Ja mam siê zaj¹æ nadzorc¹? Myœlê, ¿e jednak chcesz mnie oszukaæ.}
{226} {} {Teraz zarabiam œwietne kapsle, sprawy id¹ ku lepszemu. A to wszystko dziêki Tobie.}

{230} {} {Faber zgodzi³ siê przekazaæ ci stanowisko nadzorcy.}
{231} {} {Nie mam pojêcia, jak go przekona³eœ. Ale dziêkujê Ci.}
{232} {} {Jest jeden problem - musisz sam rozmówiæ siê z Knutem.}
{233} {} {Nie ma problemu, ale Knut prawdopodobnie nie bêdzie chcia³ odejœæ dobrowolnie. Potrzebujê kogoœ, kto pójdzie ze mn¹. Po prostu trzymaj siê blisko, podczas gdy ja z nim bêdê negocjowa³, dobrze?}
{234} {} {Ok. Spotkajmy siê w kopalni...}
{235} {} {Powodzenia. Czeœæ.}

# Na mapie kopalni (uzywanej przez skrypt FCMinPap)
{240} {} {Ugh, co za twardy sukinsyn! Gdyby nie ty, nie zrobi³bym tego. Dziêkujê Ci.}
{241} {} {W porz¹dku. To by³o ca³kiem przyjemne.}
{242} {} {Prawie nas zabi³!}
{243} {} {Nie wiem, dlaczego mi pomagasz, ale zapamiêtam ciê i nie bêdê taki jak Knut. Pod moim kierownictwem sprawiedliwoœæ i prawo bêd¹ wa¿niejsze ni¿ osobiste ambicje.}
{244} {} {Powodzenia. Bywaj.}
{245} {} {Gdyby nie ty, rozmowa zakoñczy³aby siê walk¹. Dziêkujê Ci.}
{246} {} {Jak widaæ, z ka¿dym da siê dogadaæ.}
{247} {} {Wiesz, moje piêœci lubi¹ walkê.}
{248} {} {To twoje dzie³o, co? Nie martw siê, cieszê siê, ¿e jest o jeden problem mniej. Knut móg³by sprawiæ mi wiele k³opotów.}
{249} {} {Zas³ugiwa³ na to.}