{100} {} {Widzisz swoj¹ Madre.}
{101} {} {Widzisz kobietê, któr¹ dobrze znasz. To twoja matka.}
{102} {} {Do widzenia Madre. Teraz sam zajmê siê sob¹.}
{103} {} {Otrzymujesz }
{104} {} { doœwiadczenia za uwolnienie wspó³plemieñców.}
{105} {} {Twoja Madre nie ¿yje. Pozostaje znaleŸæ innych cz³onków Villi.}
{106} {} {Twoja Madre nie ¿yje. Nie ma tu nic innego do roboty.}
{107} {} {Porozmawiamy, kiedy wyjdziemy z garnizonu.}

# Pierwszy dialog
{200} {} {? Jak siê masz... Na litoœæ bosk¹, nie powinieneœ by³ podejmowaæ takiego ryzyka! Mog³eœ zgin¹æ... Ale oczywiœcie cieszê siê, ¿e ciê widzê. I jak dumny by³by twój ojciec, gdyby dowiedzia³ siê o wyczynie swojego dziecka! Dobrze Ci idzie.}
{201} {} {To obrzydliwe ciê s³uchaæ, madre. Jestem wystarczaj¹co doros³y, ¿eby samemu podejmowaæ decyzje.}
{1201} {} {To obrzydliwe ciê s³uchaæ, madre. Jestem wystarczaj¹co doros³a, ¿eby samej podejmowaæ decyzje.}
{202} {} {Nie wybaczy³bym sobie, gdyby coœ ci siê sta³o z powodu mojej bezczynnoœci.}
{1202} {} {Nie wybaczy³abym sobie, gdyby coœ ci siê sta³o z powodu mojej bezczynnoœci.}
{203} {} {Och, tak, oczywiœcie... Rozumiem. Mo¿e ca³a ta sytuacja ciê zmieni³a. Zmieni³a coœ w nas wszystkich. Widzê zmiany w twoich oczach, widzê trochê inn¹ osobê. Nie wiem, czy to dobrze, czy Ÿle.}
{204} {} {Tak, to jest w³aœnie si³a naszej Villi - wszyscy jesteœmy jak jedna wielka rodzina. Ka¿dy jest za ka¿dego odpowiedzialny. I cieszê siê, ¿e ta podró¿ nie zmieni³a tych idea³ów w tobie.}
{205} {} {Teraz zastanówmy siê, jak wyjœæ z tego ba³aganu ca³o.}

{206} {} {Obawiam siê, ¿e to nie bêdzie ³atwe. Jak widaæ, w zagrodzie jest tylko trzech naszych ludzi. Dwóch kolejnych zgubi³o siê w kopalniach. Pozostali, ³¹cznie z twoim ojcem, zostali zabrani na po³udnie, do du¿ego miasta Phoenix.}
{207} {} {Co ci najemnicy ci robili?}
{208} {} {Jak dotrê do Phoenix?}
{209} {} {Co wiesz o zagubionej grupie?}
{210} {} {Jak mogê ciê wyci¹gn¹æ z tego miejsca?}
{211} {} {Spróbujê rozwi¹zaæ te problemy. Poczekaj na mnie.}
{212} {} {Mi³o ciê widzieæ.}
{213} {} {Nadal pracujê nad twoim uwolnieniem. Czekaj na mój znak.}
{214} {} {Tak?}
{215} {} {Do widzenia.}
{216} {} {Rozumiem.}
{217} {} {Nic specjalnego, nie martw siê. Zasadniczo wykonywa³am te same prace, które wykonywa³am w Villi. Tylko trochê wiêcej i ciê¿ej. Ci koloniœci s¹ tacy niegrzeczni. Ale mê¿czyŸni s¹ zmuszani do pracy w kopalni. To dla nich naprawdê trudne.}
{218} {} {Mówi¹, ¿e to du¿e miasto na po³udniu, ale nigdy tam nie by³am. Miêdzy Flagpool i Phoenix kursuj¹ karawany handlowe i towarowe. Zapytaj miejscowych, powinni coœ o tym wiedzieæ.}
{219} {} {Do kopalni weszli Hugo i Sancho, mieli znaleŸæ tajne wyjœcie. Ale od pewnego czasu nie ma od nich ¿adnych wieœci.}
{220} {} {Koloniœci nie pozwol¹ nam odejœæ dobrowolnie. Mo¿esz porozmawiaæ z ich szefem, ale raczej nie pójdzie na ustêpstwa bez powa¿nych korzyœci dla siebie.}
{221} {} {Co powiesz na ucieczkê?}
{222} {} {Ucieklibyœmy dawno temu, gdyby nie te obro¿e. Zabij¹ nas jak tylko za bardzo oddalimy siê od obozu. Plotka g³osi, ¿e s¹ kontrolowane przez tê du¿¹ antenê naprzeciw zagrody, ale ¿aden z wiêŸniów nie wie jak to do koñca dzia³a.}
{223} {} {Nie chcesz mnie tam puœciæ, prawda?}
{224} {} {Nie chodzi nawet o niebezpieczeñstwa zwi¹zane z podró¿owaniem, ale samo miasto. Du¿o o nim mówi¹, ale nic dobrego. A tak poza tym twój wujek Miguel wyjecha³ kiedyœ z karawan¹ do Phoenix i nigdy nie wróci³. Spróbuj go tam znaleŸæ, mo¿e to ci jakoœ pomo¿e.}
{225} {} {Faber zwróci³ wam wolnoœæ. Mo¿ecie wracaæ do Villi.}
{226} {} {Jesteœmy wolni! Nie martw siê o nas, sami dojdziemy do Villi. Ale musisz szybko pomóc swojemu Padre, zosta³ wys³any na po³udnie. Powodzenia.}
{227} {} {Do zobaczenia w Villi.}
{228} {} {Stra¿nicy nie ¿yj¹, mo¿ecie wyjœæ.}
{229} {} {Obro¿e nie s¹ ju¿ niebezpieczne. Zdejmijcie je i wynoœcie siê st¹d.}
{230} {} {To dobrze, ale jak mamy omin¹æ stra¿ników?}
{231} {} {Ta kwestia wymaga jeszcze przemyœlenia.}
{232} {} {Zostaw ochronê mnie. Wyci¹gnê was st¹d.}
{233} {} {Czy napewno wiesz, co robisz? Gdy tylko wyjdziemy z zagrody, zaatakuj¹ nas stra¿nicy. Nie bêdziemy w stanie oprzeæ siê tak wielu uzbrojonym ludziom.}
{234} {} {Zignoruj stra¿ników, wiem co robiê.}
{235} {} {Zostañ w zagrodzie, dopóki nie wydam polecenia.}
{236} {} {Ok. ProwadŸ nas. Jak wydostaniemy siê z garnizonu, porozmawiamy.}
{237} {} {ChodŸmy.}
{238} {} {Nie wiem... Nie potrafiê ciê samemu wydostaæ. Kto móg³by nam pomóc?}
{239} {} {Jedynymi, którzy mog¹ nam pomóc, s¹ Rangersi. Mieszkaj¹ na po³udnie od Villi nad rzek¹ Kolorado. Ale nie wiadomo czy na pewno nam pomog¹. Rangersi nie oferuj¹ swojej ochrony za darmo.}
{240} {} {Co powiesz na ucieczkê?}