{100} {} {Widzisz operatora.}
{101} {} {Widzisz operatora maszyny.}

#Dialog
{200} {} {(nie podnosz¹c wzroku znad swojej pracy) He? Co tam?}
{201} {} {Nic.}
{202} {} {(kontynuuje pracê) Poœpiesz siê.}
{203} {} {Do widzenia.}
{204} {} {Czekaj, powiedz mi wiêcej.}

{210} {} {Opowiedz mi o swojej pracy.}
{211} {} {Co tu powiedzieæ? Biorê rudê, ³adujê j¹ do maszyny, a ta j¹ mieli i czyœci. Rafinowana ruda trafia do maszyny wzbogacaj¹cej, reszta jest wyrzucana. To wszystko.}
{212} {} {Po co uszlachetniaæ rudê?}
{213} {} {Poniewa¿ uran musi byæ wolny od zanieczyszczeñ, w przeciwnym razie nie zapewni wymaganej energii. To prawda, chocia¿ ja sam nie rozumiem ca³ej technologii do koñca.}
{214} {} {Czy praca z uranem jest bezpieczna?}
{215} {} {Jeœli mówisz o promieniowaniu, to nie jest straszne, dopóki ruda nie zostanie oczyszczona. Ale zranienie przez tê przeklêt¹ staro¿ytn¹ maszynê jest ca³kiem mo¿liwe.}

{220} {} {Sk¹d pochodzi ten sprzêt?}
{221} {} {Pochodzi z dawnych czasów. Chocia¿ s¹ to ma³e rzeczy w porównaniu z tym, co by³o wczeœniej.}
{222} {} {Wiêc przed wojn¹ wydobywano tu i rafinowano uran?}
{223} {} {Tak. Podziemne tunele s¹ dobrze zachowane, ale czêœæ wyposa¿enia i budynków popad³a w ruinê.}
{224} {} {To nie wszystko, prawda?}
{225} {} {Huh? O czym mówisz?}
{226} {} {A nic, wydawa³o mi siê.}
{227} {} {Nie mo¿e byæ tak, ¿e ludzie tak po prostu przyszli tu i zaczêli obs³ugiwaæ te staro¿ytne maszyny. Sk¹d wiecie jak tego w ogóle u¿ywaæ?}
{228} {} {Trafna uwaga. Mówi siê, ¿e przed za³o¿eniem kolonii Faber zatrudni³ kilku typów, którzy naprawili i przygotowali sprzêt. Dopiero potem sprowadzi³ tutaj ludzi i rozpocz¹³ produkcjê. Ale ¿aden z miejscowych nie móg³ tego zrobiæ.}
{229} {} {Ciekawe. Powiedz mi wiêcej.}

{230} {} {Jesteœ tu z w³asnej woli?}
{231} {} {Formalnie tak. Nie mam dok¹d pójœæ, wiêc jestem tu jako chêtny niewolnik.}
{232} {} {Co myœlisz o niewolnictwie?}
{233} {} {Nie wiem. Prawdopodobnie nie jest to dobre, gdy inni pracuj¹ dla Ciebie bo musz¹. Ale oto, co myœlê - wszyscy jesteœmy w tej samej sytuacji czy to w kajdanach czy nie.}

{240} {} {Kopalnia zosta³a wysadzona w powietrze. Co zamierzasz teraz zrobiæ?}
{241} {} {Nie wiem. Zrobiê co zosta³o jeszcze zamówione. I tak nie mam dok¹d pójœæ.}
{242} {} {Nadzorca ju¿ nikomu nie przeszkadza. Spójrz na zewn¹trz.}

{250} {} {Czy nadzorca czêsto bije pracowników?}
{251} {} {(wzdycha) Ten goœæ... to prawdziwy wariat, bije ka¿dego. Ja te¿ od niego dostajê, ale nie tak czêsto. Chcia³bym siê go pozbyæ, ale sam Faber wyznacza nadzorców.}
{252} {} {A co z administratorem? Czy on nie mo¿e nic z tym zrobiæ?}
{253} {} {Nie wiem, dlaczego ci to mówiê. Jednak Knut zmusza go do przepisania raportów, ¿e niby robotnicy nie zostali przez niego okaleczeni tylko mieli wypadek w pracy. Nie chcê zepsuæ swojej reputacji, dlatego ode mnie tego nie wiesz. Ale on trzyma administratora w ryzach.}
{254} {} {Jaki jest sens kaleczyæ niewolników?}
{255} {} {Mówiê ci - Knut jest po prostu z³ym cz³owiekiem. Myœlê, ¿e Faber specjalnie wybra³ takiego twardego nadzorcê, aby wzmocniæ kontrolê nad wiêŸniami, poniewa¿ ostatnio by³o z nimi wiele problemów. Poza tym Roy i Knut s¹ w dobrych stosunkach. Ale nie zdziwi³bym siê, gdyby Faber nie zna³ ca³ej prawdy.}
{256} {} {Mogê go wykoñczyæ dla ciebie i reszty wiêŸniów.}
{257} {} {Co to za bzdury? Mówisz powa¿nie? Zamierzasz zabiæ cz³owieka dla garstki wiêŸniów? Nawet najemnicy w garnizonie nie s¹ tak krwio¿erczy. Poza tym mo¿e to nie mieæ sensu, gdyby inny tyran przej¹³ w³adzê od Knuta. W ka¿dym razie nie próbuj mnie w to mieszaæ. Nie mam z tym nic wspólnego!}
{258} {} {W porz¹dku. Sumienie i tak mnie nie ruszy z jego powodu.}
{259} {} {Mo¿esz mieæ racjê. Wymaga to delikatnej i legalnej metody.}
{260} {} {Powiem Faberowi, co tu siê naprawdê dzieje. Prawdopodobnie go to zaciekawi.}
{261} {} {W¹tpiê, ¿eby ciê wys³ucha³. I nawet nie próbuj mnie w to wci¹gaæ. Nie mam z tym nic wspólnego!}
{262} {} {Wci¹¿ warto spróbowaæ. Czeœæ.}
{263} {} {W takim razie za³atwiê nadzorcê. Zaczekaj na zw³oki przy wejœciu.}
{264} {} {Jak ci siê podoba nowy nadzorca?}
{265} {} {Lepszy ni¿ kiedykolwiek. Nie odwala nic z³ego i zachowuje kontrolê. Cieszê siê, ¿e uda³o ci siê pozbyæ Knuta.}
{266} {} {To by³o ³atwe.}
{267} {} {Ten nadzorca ju¿ nie bêdzie przeszkadza³ ani Tobie, ani nikomu innemu.}
{268} {} {Ty... zabi³eœ go? Tak, zabi³eœ! W ka¿dym razie to tak naprawdê nie rozwi¹zuje problemu, poniewa¿ zamiast Knua mo¿na postawiæ jeszcze wiêkszego tyrana. Nie pomyœla³eœ o tym? Okej, nic nie s³ysza³em i nie mam z tym nic wspólnego.}
{1268} {} {Ty... zabi³aœ go? Tak, zabi³aœ! W ka¿dym razie to tak naprawdê nie rozwi¹zuje problemu, poniewa¿ zamiast Knuta mo¿na postawiæ jeszcze wiêkszego tyrana. Nie pomyœla³aœ o tym? Okej, nic nie s³ysza³em i nie mam z tym nic wspólnego.}
{269} {} {I tak mi dziêkujesz? Nawet siê nie postara³eœ.}