{100} {} {Widzisz nadzorcê Knuta.}
{101} {} {Widzisz wœciek³ego, wrzeszcz¹cego mê¿czyznê.}
{102} {} {Gdzie twoja ³opata, niewolniku? Och, nie jesteœ jednym z naszych... Twoje szczêœcie, inaczej bym ciê pobi³ do nieprzytomnoœci.}
{1102} {} {Nie powinno ciê tu byæ, panienko. To miejsce jest przeznaczone tylko dla przestêpców i niewolników.}
{103} {} {Wynoœ siê st¹d!}
{104} {} {Nie wchodŸ mi w drogê, szczurku.}

{110} {} {Pracujcie, diab³y, budujecie Amerykê!}
{111} {} {Pracuj szybciej!}
{112} {} {Przenieœ tam swoj¹ matkê!}
{113} {} {Jeœli zobaczê jakiegoœ lenia, skasujê gnoja!}
{114} {} {Dostaniesz œwiñskie gówno na obiad.}
{115} {} {Kto dobrze pracuje, dostaje prawdziwe miêso.}
{116} {} {Hej, gdzie idziesz? Tam! No, mówiê!}
{117} {} {}
{118} {} {}
{119} {} {}

{200} {} {Szukasz problemu?}
{1200} {} {Tak, kochanie, co za niespodzianka. Bêdzie mi bardzo przykro, ¿e zabrudzi³aœ swoje piêkne rêce t¹ rud¹.}
{201} {} {Ty je zapewniasz, co?}
{1201} {} {Tak ci przykro jak temu niewolnikowi, którego pobi³eœ na œmieræ?}
{202} {} {Tak. Uwielbiam kopaæ dupy wszelkiego rodzaju szumowinom, które nie maj¹ prawa do g³osu.}
{203} {} {Mówisz teraz o mnie, kretynie?}
{204} {} {Czy chcia³byœ, ¿ebym te¿ ni¹ by³, kretynie?}
{205} {} {Cisza! Na co sobie pozwalasz, œmieciu? Chcesz iœæ do ciê¿kiej pracy? Da siê za³atwiæ! Bêdziesz ¿ar³ tê ziemiê! Zamiast wody bêdziesz piæ w³asny mocz! Czy to dla ciebie jasne?}
{206} {} {Tak, proszê pana. Przepraszam pana.}
{207} {} {Nie zastraszysz mnie. Pierdol siê, kretynie.}
{208} {} {ZAJEBIE CIE KURWO!!!}
{1208} {} {ZAJEBIE CIE KURWO!!!}
{209} {} {Och, jak wspaniale...}
{210} {} {Ten niewolnik nie zas³ugiwa³ na takie traktowanie.}
{211} {} {Sk¹d to wiesz? W tej kopalni pracuj¹ tylko przestêpcy i szarlatani. Bêdziesz siê rzuca³ - od razu zajmiesz wolne stanowisko. Czy to dla ciebie jasne?}
{212} {} {Tylko spróbuj, a poka¿e ci sprawiedliwoœæ, szumowino.}
{213} {} {Tak, proszê pana. Przepraszam pana.}
{214} {} {Nie ma mowy, sir.}

{220} {} {Wszyscy siê zgadali przeciw mnie! To jakiœ spisek! Wszyscy jesteœcie aresztowani! Bedziecie kruszyæ rudê zêbami!}
{221} {} {Nie jesteœ zdrowy na umyœle. Teraz pora wszystko naprawiæ, ka¿dy bêdzie zadowolony...}
{222} {} {Hej, nie mam z tym nic wspólnego. Oto twój zastêpca.}
{223} {} {Porozmawiajmy o tym spokojnie, co?}
{224} {} {Nie kupujê tych sztuczek! Jeœli chcia³eœ pozbyæ siê nadzorcy, czekaj¹ ciê konsekwencje.}
{225} {} {Faber osobiœcie wyda³ rozkaz. Poddaj siê teraz, zanim bêdzie za póŸno.}
{226} {} {Gr-rm... Nie myœl, ¿e zostawiê to w ten sposób. Wszyscy mi zap³acicie! Przysiêgam!}
{227} {} {No có¿.}