{100} {} {Widzisz pani¹ Brandley.}
{101} {} {Widzisz zwyczajn¹ kobietê w eleganckim stroju.}
{102} {} {Zzz}
{103} {} {Przepraszam, zamkniête. Nikt nie potrzebuje naszych us³ug w tych okolicach...}

# Repliki zaatakowane przez wieznia
{120} {} {Proszê, uspokój siê!}
{121} {} {Naprawdê mam pust¹ kasê!}
{122} {} {Nie dotykaj niczego!}
{123} {} {S³uchaj, naprawdê ci wspó³czujê...}
{124} {} {Naprawdê nie mogê ci pomóc!}
{125} {} {Proszê, nic nie mam!}
{126} {} {Zostaw mnie!}
{127} {} {}
{128} {} {}
{129} {} {Pomocy! Zosta³am okradziona!}

#Dialog
{200} {} {(widzisz kobietê w niezwykle przyzwoitym stroju; wygl¹da, jakby patrzy³a na ciebie z góry)}
{201} {} {Witam pani¹, pani...}
{202} {} {Hej, czeœæ.}
{203} {} {Ann Brandley. I mów do mnie panno.}
{204} {} {Cokolwiek powiesz, panno Brandley.}
{205} {} {(patrzy z pogard¹) Hmm. Dzieñ dobry. Gdzie ciê uczono rozmawiaæ z damami? W lesie?}
# Cytat z filmu „Skala wiezienna”: „Gdzie uczono ciê tak rozmawiaæ z damami? W lesie?”
{206} {} {W ogóle mnie tego nie nauczono.}

{210} {} {Jak mogê pomóc?}
{211} {} {Do widzenia.}
{212} {} {Wróæmy do pocz¹tku rozmowy.}
{213} {} {Cofnijmy siê trochê.}

{218} {} {Dziêki za ocalenie! To by³a niebezpieczna sytuacja. W dowód wdziêcznoœci udzielê Wam du¿ej zni¿ki, jeœli bêd¹ Pañstwo potrzebowaæ naszych us³ug transportowych.}
{219} {} {Brzmi dobrze.}

# Wysylanie paczki
{220} {} {Muszê wys³aæ paczkê do Phoenix.}
{221} {} {Muszê wys³aæ paczkê do Tu-San.}
{222} {} {Swietnie. Koszt wysy³ki wyniesie }
{223} {} { kapsli. Umieœæ paczkê w tym pude³ku obok œciany i zg³oœ, ¿e jest gotowa. Po dokonaniu p³atnoœci zabierzemy j¹ do miasta docelowego.}
{224} {} {Ok, paczka mo¿e zostaæ wys³ana.}
{225} {} {Pakiet bêdzie czeka³. Porozmawiamy o czymœ innym?}
{226} {} {Nie mam ze sob¹ tylu kapsli. Przyjdê póŸniej.}
{227} {} {(uwa¿a na ka¿de s³owo, sporz¹dza umowê i rejestruje twoje imiê) Dziekujemy za wybranie naszej firmy. Pakiet bêdzie czeka³ w miejscu odbioru.}
{228} {} {}
{229} {} {Swietnie. PA.}
{230} {} {Przepraszam, ale to nie wystarczy.}
{231} {} {Mo¿emy wiêc o czymœ porozmawiaæ?}
{232} {} {Có¿, pójdê po kapsle.}

{240} {} {Czy akceptujesz stare pieni¹dze?}
{241} {} {Masz na myœli przedwojenne dolary i centy? Nie, nie, od dawna nie s¹ u¿ywane. Jednak w Phoenix lokalne kasyno mo¿e wymieniæ je na kapsle, ale tylko dla swoich klientów.}
{242} {} {Wróæmy do tematu mojej paczki.}
{243} {} {Hmm. To wszystko zmienia. Poczekam chwilê z przesy³k¹.}
{244} {} {Mam aktywne dostawy na po³udniu. Powinniœmy wspó³pracowaæ.}
{245} {} {Obawiam siê, ¿e nie mo¿emy skorzystaæ ze zni¿ek. Nie pokryje to naszych kosztów wysy³ki.}
{246} {} {Przepraszam.}
{247} {} {Brzmi kusz¹co. Byæ mo¿e uda nam siê obni¿yæ cenê o 50 kapsli.}
{248} {} {Nie po¿a³ujesz.}
{249} {} {Jak wiarygodna jest ta umowa?}

{250} {} {Czy ty na pewno potrafisz... pisaœ?}
{251} {} {Lepiej ni¿ wiêkszoœæ wykszta³conych mieszkañców miast. Wynawcy Ognia mnie tego nauczyli na swoich kursach... tylko nie mam jeszcze wystarczaj¹cej praktyki.}
{252} {} {Uch, tak, oczywiœcie.}
{253} {} {Wysy³amy paczki raz w miesi¹cu. A przypadki ich utraty mo¿na policzyæ na palcach jednej rêki, niezmutowanej oczywiœcie. Mamy doœwiadczonych kurierów. Dobrze znaj¹ ukszta³towanie terenu i sposoby przetrwania. W przypadku zagubienia przesy³ki mo¿na domagaæ siê odszkodowania.}
{254} {} {PEWNIE, ¿e potrafiê pisaœ! W przeciwnym razie nie mog³abym tu pracowaæ.}
{255} {} {No tak, tak.}

#Zadanie
{270} {} {Szukam pracy. Czy macie jakieœ wolne miejsca?}
{271} {} {Przepraszam, nie. Szczerze mówi¹c, do pilnowania karawan jest ca³a kolejka.}
{272} {} {Przepraszam. Ale naprawdê muszê zarobiæ dodatkowe pieni¹dze.}
{273} {} {Czy w tej dziurze nie ma ¿adnej pracy?}
{274} {} {Mo¿e mo¿esz mi pomóc w drobnej sprawie? Niedawno zgubi³am portfel. By³o w nim kilka drobiazgów, ale najwa¿niejszy by³ zeszyt. Najprawdopodobniej zosta³ skradziony. Jeœli go znajdziesz, przynieœ mi go, zap³acê.}
{275} {} {Nie ma problemu. Mam nosa do z³odziei.}
{276} {} {Och, wiêc twój nos bêdzie musia³ sprawdziæ setki zapachów w tym mieœcie. Powodzenia.}
{277} {} {Nie martw siê, panno. Znajdê go bez wiêkszych trudnoœci.}
{278} {} {Jeszcze nie.}
{279} {} {Cholera! Gdzie s¹ ¿o³nierze z garnizonu? Dlaczego p³acimy podatki tym w³óczêgom skoro nic nie robi¹?}

{280} {} {O zgubionych przedmiotach. }
{281} {} {I jak? Znalaz³eœ je?}
{282} {} {Zastanawiam siê gdzie zacz¹æ poszukiwania, masz jakieœ pomys³y?}
{283} {} {Nie wiem. Rano jeszcze mia³am swoje rzeczy, a po spacerze po mieœcie ju¿ nie. Mo¿e ktoœ coœ widzia³ wœród przechodniów?}
{284} {} {Dobry pomys³, powinnienem popytaæ.}
{285} {} {O tak. Oto Twoje rzeczy.}
{286} {} {Och, to naprawdê one! Ba³am siê, ¿e straci³em je na zawsze. Wiesz, jest tu wiele wa¿nych dla mnie informacji. Ale kim by³ ten zuchwa³y z³odziej?}
{287} {} {To by³y dzieci z s¹siedztwa.}
{288} {} {Dzieci? Nie mogê w to uwierzyæ! Mieszkañcy zawsze cenili Flagpool za bezpieczeñstwo, poniewa¿ w pobli¿u znajduje siê garnizon, a wokó³ œciana z barykad. A tu proszê - z³odzieje s¹ w œrodku, a nie na zewn¹trz. I to dzieci!}
{289} {} {Tak, to po prostu okropne. Dziœ nie mo¿na ju¿ nikomu ufaæ.}
{290} {} {Oczywiœcie nie napiszê donosu do garnizonu, ale nie wybaczê te¿ s¹siadom tak ³atwo. Ktoœ musi tu zachowaæ porz¹dek.}
{291} {} {To dzieci. To nie by³a kradzie¿, ale zwyk³y ¿art.}
{292} {} {Ludzie z takimi ¿artami w koñcu wykonuj¹ prace poprawcze. Oczywiœcie nie napiszê donosu do garnizonu, ale nie wybaczê te¿ tego s¹siadom tak ³atwo.}
{293} {} {Wygl¹da na to, ¿e sama upuœci³aœ swoje rzeczy, znalaz³em je na ulicy.}
{1293} {} {Wygl¹da na to, ¿e sama upuœci³aœ swoje rzeczy, znalaz³am je na ulicy.}
{294} {} {Naprawdê? Nie chce mi siê w to wierzyæ. Z reszt¹ to i tak nie ma teraz znaczenia.}
{295} {} {Dobrze, ¿e problem zosta³ rozwi¹zany.}
{296} {} {Um. Robota wykonana, ale nie widzê nagrody.}
{297} {} {Wielkie dziêki. Oto 20 kapsli za znalezisko.}
{298} {} {Niez³y pocz¹tek.}
{299} {} {Lepsze ni¿ nic.}

#Pytania
{300} {} {Co to za miejsce?}
{301} {} {To jest biuro Sonora Express, jedynej firmy kuriersko-pocztowej w ca³ej Arizonie.}
{302} {} {Co przewozicie?}
{303} {} {Wszelkie ma³e paczki, stosy kapsli i listy. W przypadku wiêkszych przesy³ek istnieje inna firma, która wspó³pracuje z kopalni¹ uranu.}
{304} {} {Nietypowy biznes w tych czasach.}
{305} {} {Zgadza siê. Wczeœniej paczki i listy nie by³y potrzebne, a wielu nie wiedzia³o nawet jak pisaœ. Ale po rewolucji na po³udniu wiele siê zmieni³o. Jednym z przyk³adów jest Sonora Express.}
{306} {} {Wiêc co to za miejsce?}
{307} {} {Jesteœ tu sama, bez ochrony?}
{308} {} {W kolonii jest bezpiecznie, bandyci nie przychodz¹ tu z powodu garnizonu i patrolów. Ale poza dolin¹, zw³aszcza wzd³u¿ autostrad, jest coraz wiêcej bandytów.}
{309} {} {Dlaczego?}
{310} {} {Wczeœniej na trasie by³y tylko wilki i rzadkie plemiona, a bandyci nie mieli czego tam szukaæ. Teraz rozwijaj¹ce siê Flagpool przyci¹ga ludzi do pracy i karawany.}

{320} {} {Opowiedz mi o sobie.}
{321} {} {Nazywam siê Ann Brandley i jestem w³aœcicielk¹ tego biura.}
{322} {} {Sk¹d jesteœ?}
{323} {} {Zy³am na po³udnie od Phoenix. Tam spêdzi³am ca³e swoje dzieciñstwo i m³odoœæ. Potem dostarcza³am paczki i handlowa³am, a¿ dotar³am do Sonora Express.}
{324} {} {Co sprawi³o, ¿e opuœci³as Phoenix?}
{325} {} {To du¿e, ale duszne miasto, w którym konkurencja powstrzymuje wszystkich przed rozwojem. Brakowa³o mi wolnoœci i bezpieczeñstwa.}
{326} {} {Czy trudno by³o siê tu dostaæ?}
{327} {} {Przyjecha³am tu karawan¹ na fali pierwszych osadników. Droga by³a trudna - szliœmy powoli ze wzglêdu na baga¿, mieliœmy za ma³o czystej wody, kilkakrotnie napada³y na nas wrogie plemiona. Ale w tamtych czasach nie by³o po drodze tylu bandytów, co teraz.}
{328} {} {Nie przeszkadzaj¹ ci najemnicy?}
{329} {} {Zo³nierze z garnizonu? Ani trochê. Dopóki mój m¹¿ jest jednym z nich, nie mam siê czym martwiæ.}
{330} {} {Dlaczego nazywasz ich ¿o³nierzami?}
{331} {} {Có¿, wyroœli z bandy handlarzy niewolników dawno temu. Teraz to prawdziwa ma³a armia broni¹ca miasta. Ze swoim genera³em na czele, jak w tych opowieœciach z okresu przedwojennego. Jednak pewnie nawet o tym nie czyta³eœ.}
{332} {} {Jak siê ¿yje w tym mieœcie?}
{333} {} {NieŸle, jeœli akceptujesz twarde zasady. Mozna tu dobrze zarobiæ.}

{350} {} {Jak dojœæ do Phoenix?}
{351} {} {To du¿e miasto na po³udniu, w³aœnie tutaj. (pokazuje na mapie) IdŸ wzd³u¿ Trasy 17 bez postojów.}
{352} {} {Czy mogê do³aczyæ do twoich pos³añców?}
{353} {} {Nie œwiadczymy us³ug dyli¿ansowych, jest to niezgodne z polityk¹ firmy. Ale warto porozmawiaæ z przewoŸnikami rudy uranu, czasem potrzebuj¹ kogoœ do pomocy.}
{354} {} {Dobrze, wpadnê do nich, gdy znajdê czas.}
{355} {} {Dziêki, pójdê ich zobaczyæ.}