{100} {} {Widzisz z³odzieja.}
{101} {} {Widzisz zbieg³ego wiêŸnia. Jest uzbrojony i bardzo niebezpieczny.}
{102} {} {Krok bli¿ej i nie ¿yjesz!}
{103} {} {Wygl¹da na to, ¿e miasto sta³o siê niebezpieczne.}
{104} {} {Od³ó¿ broñ, albo zabijê tu wszystkich!}

# Plywajace repliki
{110} {} {Kapsle na stó³! Szybko!}
{111} {} {Jeœli nie chcesz, ¿eby by³o dobrze, bêdzie Ÿle.}
{112} {} {Dawaj kapsle, powiedzia³em!}
{113} {} {Tracê panowanie nad sob¹.}
{114} {} {Umrzesz suko, jeœli nie oddasz mi wszystkich kapsli.}
{115} {} {Twarz¹ w dó³! Ju¿!}

#Dialog
{200} {} {Hej, ty. Dawaj wszystkie kapsle. Zwawo!}
{201} {} {Ok, ok, oto 50 kapsli dla ciebie, nie chcê k³opotów...}
{202} {} {To wszystko? Cholera, daleko nie zajdê... Teraz stañ przy œcianie i policz do tysi¹ca. Jasne?}
{203} {} {Uch, cokolwiek powiesz...}
{204} {} {Ok, wystarczy. Pora spuœciæ ci lanie!}
{205} {} {Uspokój siê, nie musisz przelewaæ krwi. Nadal masz wyjœcie.}
{206} {} {Powiedzia³em „wszystkie-twoje-kapsle”. Natychmiast!}
{207} {} {Ok, okej, oto wszystkie moje kapsle, tylko nie rób mi krzywdy...}
{208} {} {O czym ty do cholery mówisz ?! Po ucieczce pozosta³o mi tylko udaæ siê do innego miasta i co ja tam bêdê niby robi³ bez kapsli?}
{209} {} {Ale kapsle nie pomog¹ ci po drodze.}
{210} {} {Cholera, prawda... Wiêc, to jest... Odwróæ siê do œciany i policz do tysi¹ca! Jasne?}
{211} {} {Nic nie dostaniesz.}
{212} {} {Naprawdê? Zobaczymy!}
{213} {} {Hej, uwa¿aj!}
{214} {} {Ok, zacznijmy zabawê!}
{215} {} {Nie masz jaj!}
{216} {} {KLAMIESZ!}
