{100} {} {Widzisz dziecko.}
{101} {} {Widzisz dziecko jednego z kolonistów.}
{102} {} {Powiem wszystkim co zrobi³eœ!}

{104} {} {Potrzebny jest prawdziwy lekarz. Lub kilka porcji antyradów.}

# Uwagi dotycz¹ce odpowiedzi
{110} {} {Czeœæ.}
{111} {} {Z-z-z}
{112} {} {Oto moje wrzody. Tu i tutaj. I tutaj te¿.}
{113} {} {Czujê siê teraz znacznie lepiej!}

{116} {} {Sytuacja zaczê³a siê robiæ powa¿na.}
{117} {} {Gdy tylko znajdujesz ledwie widoczn¹ ¿y³ê, wstrzykujesz roztwór antyradu. To znacznie u³atwia proces leczenia.}
{118} {} {Mo¿esz teraz rozpocz¹æ leczenie.}
{119} {} {Pacjent dochodzi do siebie. Dobra robota!}
{120} {} {Tak trzymaj.}