{100} {} {Widzisz Rangersa.}
{101} {} {Widzisz Rangersa. Jego spojrzenie wyra¿a pe³n¹ determinacjê.}
{102} {} {Wyruszê w drogê gdy tylko spakujê swoje rzeczy.}

# Pierwszy dialog
{200} {} {Stop, nie ruszaj siê! Jeszcze jeden krok i strzelê ci w g³owê.}
{201} {} {Ok, nie ruszam siê. Nie strzelaj.}
{202} {} {Swietnie. Nie bêdê ryzykowa³, wiêc ¿adnych sztuczek.}
{203} {} {[Dalej.]}
{204} {} {Grozisz? Mi? Pierdol siê!}
{205} {} {(szybko kieruje broñ na ciebie)}
{206} {} {Stop! Nie strzelaj!}
{207} {} {Giñ!}
{208} {} {Huh? Co siê dzieje?}
{209} {} {Z twoj¹ g³ow¹ nie jest w porz¹dku, prawda? To jest broñ. I strzela. Jeœli drgniesz, umrzesz. Czy to jasne?}
{210} {} {Cokolwiek powiesz, nie chcê k³opotów.}

{211} {} {Hmm. (opuszcza lufê pistoletu) Nie wygl¹dasz na jednego z najemników. Kim jesteœ i co tu robisz?}
{212} {} {Wiêc mów, zanim rozmazê twój mózg na œcianie.}
{213} {} {Ktoœ tu zaraz umrze. I to nie bêdê ja. Rozumiesz, kowboju?}

{214} {} {Huh? Co siê dzieje?}
{215} {} {(opuszcza broñ) Hmm. Nie rozumiesz, prawda? Jest mi niesamowicie ¿al ludzi takich jak ty. Mo¿e powinienem ciê zastrzeliæ, ¿eby ukruciæ twe mêki?}
{216} {} {Strzelaæ? Mnie? Czemu?}
{217} {} {Albo nie. Bêdziesz s³u¿yæ jako przynêta dla najemników. WyjdŸ na zewn¹trz, tam siê przejdŸ. To jest moje miejsce. Rozumiesz? IdŸ, no idŸ!}
{218} {} {Ooh, idŸ na spacer. Spacerowaæ!}

{220} {} {Jestem zwyk³ym podró¿nikiem szukaj¹cym przydatnych œmieci w tych ruinach.}
{1220} {} {Jestem zwyk³ym podró¿nikiem szukaj¹cym przydatnych œmieci w tych ruinach.}
{221} {} {Nie przekona³o mnie to. Albo nie jesteœ tutaj z w³asnej woli, albo pracujesz dla najemników z garnizonu.}
{222} {} {Nie mog³em prosiæ ju¿ o jedzenie w garnizonie. Musia³em zajrzeæ do tych ruin.}
{223} {} {Potrzebujê tylko trochê z³omu.}
{224} {} {To jest Muzeum Pó³nocnej Arizony. W przesz³oœci jedna z atrakcji miasta.}
{225} {} {Mówiê prawdê.}
{226} {} {Masz racjê. Nie jestem tu przypadkiem.}
{227} {} {Dok³adnie. I przyniosê im twoj¹ g³owê.}

{230} {} {(znów podnosi broñ) Wygl¹da na to, i¿ myœlisz, ¿e jestem idiot¹.}
{231} {} {Widzê, ¿e nie mo¿na ciê oszukaæ. Jestem tutaj z innego powodu.}
{232} {} {D³ugo by wyjaœniaæ. Lepiej od razu z tob¹ skoñczê.}

{233} {} {Ok. Przyznajmy. Jak wiêc uda³o ci siê omin¹æ moje pu³apki?}
{234} {} {Kogo chcia³eœ nimi powstrzymaæ, dzieciaki? Mo¿e na nie by to zadzia³a³o, ale ja jestem doœwiadczonym traperem.}
{235} {} {Jestem po prostu bardzo czujny.}
{236} {} {Pu³apki? Powa¿nie? Chinga tu madre! Powinieneœ by³ umieœciæ znak przy wejœciu.}
{237} {} {(poka¿ rany) W³aœciwie to nie uda³o mi siê.}
{238} {} {Nie wiem, szczêœcie.}

{240} {} {Cholera, powinienem by³ byæ ostro¿niejszy.}
{241} {} {Wiêc nie bêdziesz strzelaæ?}
{242} {} {Co za idiotyczna odpowiedŸ... (przygotowuje siê do strza³u)}
{243} {} {Stop-stop-stop! Naprawdê to jestem tu z innego powodu.}
{244} {} {[Powstrzymuje siê]}
{250} {} {Jeszcze nie. Mo¿esz iœæ. Uwa¿aj jednak, aby nie mieæ za sob¹ ogona.}
{251} {} {Zaden problem.}
{252} {} {Muszê z tob¹ porozmawiaæ.}

{260} {} {Lowc¹ g³ów. Mówi¹, ¿e twoja ma dobr¹ nagrodê.}
{261} {} {To prawda. Fabera drêczy fakt, ¿e czeka na niego prawdziwa sprawiedliwoœæ. Twoja œmieræ bêdzie dla niego przypomnieniem...}
{262} {} {W takim razie zacznijmy zabawê.}
{263} {} {Czekaj, nie chcê z tob¹ walczyæ.}
{264} {} {Oczywiœcie. W koñcu jesteœ w pu³apce.}
{265} {} {Potrzebujê du¿o bardziej g³owy Fabera. Moglibyœmy po³¹czyæ si³y.}
{266} {} {Kurwa, walczmy!}
{267} {} {O czym ty mówisz?}
{268} {} {Moi ludzie s¹ przetrzymywani w garnizonie, muszê ich uwolniæ.}
{1268} {} {Moi ludzie s¹ przetrzymywani w garnizonie, muszê ich uwolniæ.}
{269} {} {Czy w³aœnie to sk³oni³o ciê do polowania? Jesteœ tu z polecenia Fabera.}
{270} {} {Wiêc nie bêdziesz strzelaæ?}
{271} {} {Nie powinieneœ. Zdobyæ!}

{280} {} {Próbujê uwolniæ moich krewnych z wiêzienia.}
{281} {} {Czy oni te¿ s¹ zniewoleni? Ludzie Fabera z ka¿dym dniem staj¹ siê coraz bardziej bezczelni. Wczeœniej zmuszali tylko przestêpców do pracy, ale teraz zniewalaj¹ nawet niewinnych obywateli.}
{282} {} {A co z broni¹? Nie zamierzasz strzelaæ, prawda?}

{283} {} {Jestem Stra¿nikiem. Jestem tutaj, aby przywróciæ sprawiedliwoœæ.}
{284} {} {Mi³o ciê poznaæ. Ale nie pamiêtam, ¿ebym prosi³ o wsparcie. To mo¿e zagroziæ mojej sprawie.}
{285} {} {Jestem tutaj bardziej z w³asnej woli.}
{286} {} {Spokojnie, na pewno znajdziemy wspólny jêzyk. Ale upewnij siê, ¿e nie masz ogona.}
{287} {} {Oczywiœcie.}

# Powtarzajacy siê dialog
{300} {} {Mów.}
{301} {} {Do zobaczenia Rangerze.}

#Majdan
{310} {} {Poka¿ mi swoje pu³apki albo st¹d nie wyjdê.}
{311} {} {Prosz¹ o to tylko g³upcy lub zdrajcy. Dziêki tej tajemnicy ¿yjê, a Ty mnie prosisz mnie o jej ujawnienie.}
{312} {} {Rozumiem. Wiêc bêdziesz mieæ na sumieniu moj¹ œmieræ. Czeœæ.}

{313} {} {Ja te¿ jestem Stra¿nikiem, mo¿esz mi zaufaæ.}
{314} {} {Heh, rekruci... zawsze kapryœni. Ostro¿nie przejdŸ przez drzwi i nie dotykaj tylnych drzwi muzeum.}
{315} {} {Dziêki.}

{316} {} {Potrzebujesz szpiega w mieœcie, prawda?}
{317} {} {Hmm, mo¿e... Ostro¿nie przejdŸ przez drzwi i nie dotykaj tylnych drzwi muzeum.}
{318} {} {Dziêki.}
{319} {} {Nie.}
{320} {} {Stra¿nik ujawni³ wszystkie swoje pu³apki w budynku.}
{321} {} {Chcesz mojej œmierci?}
{322} {} {Nie... Ok, poka¿ê ci. Ostro¿nie przejdŸ drzwi i nie dotykaj tylnych drzwi muzeum.}
{323} {} {Dziêki.}

#Zapytania
{330} {} {Opowiedz mi o sobie.}
{331} {} {Ranger Keruk, Arizona Ranger East Branch.}
{332} {} {Chcê dowiedzieæ siê wiêcej o tobie.}
{333} {} {Teraz wiem o tobie wystarczaj¹co du¿o.}
{334} {} {Jak zosta³eœ Stra¿nikiem?}
{335} {} {Rangersi zabrali mnie, gdy by³em m³ody. Moja wioska zosta³a spalona przez handlarzy niewolników, a mieszkañcy zostali pojmani. Od tamtej pory ciê¿ko trenowa³em, aby zapobiec podobnym sytuacjom w przysz³oœci.}
{336} {} {Jesteœ tutaj sam?}
{337} {} {Bardziej op³aca mi siê dzia³aæ w pojedynkê w Flagpool. W ten sposób ³atwiej jest unikn¹æ najemników.}
{338} {} {Nie s¹dzê, ¿eby faktycznie tylko jeden Stra¿nik zosta³ wys³any do wyeliminowania ca³ego gangu handlarzy niewolników.}
{339} {} {Cholera, masz racjê. Nasi dowódcy nie chc¹ ingerowaæ w lokalne sprawy. Musia³em wiêc wzi¹æ sprawy w swoje rêce. Ale nikt mnie nie zatrzymywa³, kiedy wychodzi³em.}
{340} {} {Myœlisz, ¿e Stra¿nicy przyjm¹ ciê po tym wszystkim z powrotem?}
{341} {} {Nadal jestem Stra¿nikiem! Odznaka i stopieñ nadal s¹ ze mn¹. Otrzymam pewnie reprymendê za przekonanie o w³asnej nieomylnoœci, ale to s¹ drobiazgi.}
{342} {} {Masz nietypowe imiê.}
{343} {} {Nie zosta³o wielu z mojego plemienia. Pewnie nawet o nas nie s³ysza³eœ.}
{344} {} {Brzmi jak indyjskie imiê. Mojave, hopi... navajo?}
{345} {} {Hmm. Jestem zaskoczony. Zazwyczaj nasze plemiona ukrywa³y siê przed bia³ymi ludŸmi po Ognistym Deszczu. Opuœci³em rezerwat, gdy przybyli handlarze niewolników.}
{346} {} {Nasze historie maj¹ coœ wspólnego. Moja wioska równie¿ zosta³a zniewolona i spalona.}
{347} {} {Przykro mi... (wk³ada w twoje rêce naboje do karabinu) powinieneœ siê zemœciæ.}
{348} {} {Uch, dziêki.}
{349} {} {Zdecydowanie.}

{370} {} {Opowiedz mi o Rangersach.}
{371} {} {Na przyk³ad?}
{372} {} {Powiedz mi wiêcej o Rangersach.}
{373} {} {Doœæ o Rangersach.}
{374} {} {Kim w³aœciwie jesteœcie?}
{375} {} {Jesteœmy obroñcami prawa i porz¹dku. Lapiemy przestêpców, chronimy osadników, pomagamy w przywróceniu normalnego spokojnego ¿ycia.}
{376} {} {[Dalej.]}
{377} {} {Dlatego przeciêtny Stra¿nik jest przede wszystkim elitarnym wojownikiem i mistrzem przetrwania na pustyni.}
{378} {} {Dlaczego tak ma³o o was s³ysza³em?}
{1378} {} {Dlaczego tak ma³o o was s³ysza³am?}
{379} {} {Poniewa¿ nie chwalimy siê z naszych osi¹gniêæ. Albo dlatego, ¿e reszta œwiata postrzega nas tylko jako ³owców nagród.}
{380} {} {Co trzeba zrobiæ, aby zostaæ Stra¿nikiem?}
{381} {} {Ukoñczyæ 5 lat szkolenia bojowego, a nastêpnie sprawdziæ siê na misji. Ale wielu kadetów nie mo¿e znieœæ szkolenia i trudnoœci ¿ycia codziennego.}
{382} {} {Uch, i co siê dzieje z tymi, którzy ponios¹ pora¿kê?}
{383} {} {Niektórzy gin¹ podczas wykonywania zadañ, podczas gdy inni wyje¿dzaj¹ na pustkowia, aby zostaæ zwyk³ymi stra¿nikami, najemnikami lub karawaniarzami. Niektórzy maj¹ szczêœcie znaleŸæ swoje miejsce w bazie jako zwykli pracownicy.}
{384} {} {Gdzie jest twoja baza?}
{385} {} {Dlaczego mia³bym ujawniæ Ci tê informacjê?}
{386} {} {Nie mam z³ych zamiarów.}
{387} {} {Chcê do³aczyæ do Rangersów.}
{388} {} {Wojownicy mog¹ pomóc mi uratowaæ niewolników.}
{389} {} {}
{390} {} {Mo¿esz podaæ te wspó³rzêdne moim wrogom. Nie mogê na to pozwoliæ.}
{391} {} {Twoje w¹tpiwoœci s¹ zrozumia³e. Zapomnij o tym pytaniu.}
{392} {} {Ok, niech bêdzie. Zapomnij o tym.}
{393} {} {Ok, poka¿ê ci to na twojej mapie. Baza znajduje siê na rzece Kolorado, tu¿ za murami starej tamy.}
{394} {} {Dziêki.}

{400} {} {Porozmawiamy o Twojej misji?}
{401} {} {Jestem Stra¿nikiem. Moim obowi¹zkiem jest ochrona prawa i sprawiedliwoœci na tych ziemiach. Koloniœci z³amali zasady, wkraczaj¹c na œcie¿kê niewolnictwa. Moje kule ich ukarz¹.}
{402} {} {Co powiesz o swojej misji?}
{403} {} {Zmieñmy temat.}
{404} {} {Wróæmy do tematu twojej misji.}
{405} {} {Przez twoje czyny cierpi¹ inni, nie tylko przestêpcy.}
{406} {} {Aby wykorzeniæ wiêcej z³a, musisz czasami coœ poœwiêciæ. To s¹ uzasadnione straty.}
{407} {} {Czy nie przeszkadza Ci sumienie?}
{408} {} {Nie.}
{409} {} {Koloniœci równie¿ dbaj¹ o prawo i porz¹dek.}
{410} {} {Tak, ale tylko w ramach ich odra¿aj¹cego spo³eczeñstwa kolonialnego ze szkod¹ dla reszty mieszkañców. Nie mo¿na tego robiæ w ten sposób. Nikt ich tu nie zaprosi³, nie proszono ich o budowê miasta i odnawianie kopalni przy pomocy niewolników.}
{411} {} {Co próbujesz osi¹gn¹æ?}
{412} {} {Nie spocznê, póki Roy Faber oddycha powietrzem Arizony. Ale nie mogê z tym nic zrobiæ póki ma wokó³ siebie ludzi.}
{413} {} {Smieræ Fabera i ucieczka wiêŸniów? Masz wielkie ambicje...}
{414} {} {Wiêc to ty zastrzeli³eœ ludzi patroluj¹cych garnizon?}
{415} {} {Tak. Dostali to, na co zas³u¿yli.}
{416} {} {O jakich „zas³ugach” mówisz?}
{417} {} {Zaanga¿owanie w przestêpcze czyny Roya Fabera: tyrania, niewolnictwo, bandytyzm.}
{418} {} {Czy Stra¿nicy zachêcaj¹ do zabijania?}
{419} {} {Tylko w dobrych celach lub w samoobronie.}
{420} {} {Czy wiesz, ¿e Faber wyznaczy³ nagrodê za twoj¹ g³owê?}
{421} {} {Powinien potroiæ cenê.}
{422} {} {Co wiesz o Faberze?}
{423} {} {To tyran z ambicjami. Sni o w³asnym imperium. Ale w rzeczywistoœci jest tylko przestêpc¹, który uciska innych przestêpców.}

{450} {} {Proszê Ciê o opuszczenie Flagpool.}
{451} {} {Mimo to zostanê tutaj.}
{452} {} {Ok, zostañ, nie mam nic przeciwko.}
{453} {} {Po¿a³ujesz. Zobaczysz.}
{454} {} {Co mog³oby spowodowaæ, ¿e zmienisz zdanie?}
{455} {} {Nie pozwolê na niewolnictwo w tym miejscu.}
{456} {} {Twoja baza jest zalana. Nie musisz siê œpieszyæ, aby pomóc swoim?}
{457} {} {O czym ty mówisz?}
{458} {} {Nie wiem. To tylko plotki. Zapomnij.}
{459} {} {Widzisz, utrzymywa³eœ ciszê radiow¹, wiêc nie wiesz jeszcze, ¿e tama zosta³a zniszczona.}
{460} {} {To bardzo z³a wiadomoœæ... Muszê skontaktowaæ siê z placówk¹. Jeœli twoje s³owa siê potwierdz¹, wrócê do bazy.}
{461} {} {Ok.}
{462} {} {Genera³ ¿¹da powrotu do bazy. To rozkaz.}
{463} {} {Cholera, dlaczego nie mo¿e mnie zostawiæ w spokoju?! Moja misja jest zbyt wa¿na, ¿eby siê teraz poddawaæ.}
{464} {} {Zapomnia³eœ o reszcie œwiata. Twoja pomoc w bazie mo¿e byæ wa¿niejsza i u¿yteczniejsza.}
{465} {} {Hmm. Mo¿e tak. Musia³em zostaæ zaœlepiony pragnieniem zemsty. W porz¹dku. Przerwê ciszê radiow¹ i wrócê do bazy.}
{466} {} {To dobrze.}
{467} {} {Nie jesteœ ze sob¹ szczery. Pomyœl o swoich motywach.}
{468} {} {Moje motywy to wykorzenienie niesprawiedliwoœci na tych ziemiach.}
{469} {} {Có¿, trudno z tym dyskutowaæ. Zostañ, jeœli tak bardzo chcesz.}
{470} {} {Wygl¹da na to, ¿e nie da siê ciê przekonaæ. Wychodzê.}
{471} {} {Nie. Masz obsesjê na punkcie swojej przesz³oœci.}
{472} {} {Co ty wiesz o mojej przesz³oœci? Walczylem tyle, ¿e zapomnia³em o œwiecie... Dom, rodzina... Odeszli z powodu szumowin takich jak Faber!}
{473} {} {Przestañ zabijaæ. Wróæ do swoich. Oni ciê potrzebuj¹.}
{474} {} {Có¿, jeœli faktycznie tak jest, to nie mogê ciê przekonaæ. Walcz dalej.}
{475} {} {Zostajê.}
{476} {} {Wygl¹da na to, ¿e by³em naprawdê opêtany. A genera³ ostrzega³... Dobra. Opuszczê Flagpool i wrócê do bazy. Dziêki stary.}
{1476} {} {Wygl¹da na to, ¿e by³em naprawdê opêtany. A genera³ ostrzega³... Dobra. Opuszczê Flagpool i wrócê do bazy. Dziêkujê przyjacielu.}
{477} {} {Powodzenia.}
{478} {} {Lepiej siê poœpiesz.}

{480} {} {Faber nie ¿yje. Czy to ci wystarczy?}
{481} {} {Wiêc to prawda? (poci¹ga nosem i przerywa) Wiesz, nic nie czujê. Wydawa³o mi siê, ¿e wykorzeniaj¹c tu z³o, znajdê spokój. Ale teraz w koñcu rozumiem. Jeden Faber zostanie zast¹piony nowym. I to bêdzie siê powtarza³o... Poniewa¿ ludzie siê nie zmieniaj¹. Genera³ mia³ racjê, mówi¹c, ¿e jestem opêtany. Dziêki za pomoc. Czas wracaæ do bazy.}
{482} {} {Uff, dobrze, ¿e uda³o nam siê rozwi¹zaæ ten problem.}
{483} {} {Smia³o.}