{100} {} {Widzisz stra¿nik Davisa.}
{101} {} {Widzisz prywatnego najemnika pilnuj¹cego porz¹dku w garnizonie.}
{102} {} {Wystarczy! Dam kapsle, jeœli siê uspokoisz!}

{200} {} {Stop! Czego szukasz w garnizonie?}
{201} {} {Nie twoja sprawa.}
{202} {} {O ile wiem, moi ludzie s¹ tu przetrzymywani.}
{203} {} {Prawdopodobnie.}
{204} {} {Ok, wejdŸ. Nie obchodzi mnie to, ale szef kaza³ mi pytaæ.}
{205} {} {Rozumiem.}
{206} {} {Zabrania siê wychodzenia na zewn¹trz w nocy. Wróæ do domu, zanim zrobiê ci dziurê w g³owie.}

{210} {} {Czego chcesz?}
{211} {} {Chodzi o d³ug w barze. Jestem tu po nale¿ne kapsle.}
{1211} {} {Chodzi o d³ug w barze. Jestem tu po nale¿ne kapsle.}
{212} {} {Niczego.}
{213} {} {Ha! Nigdy ich nie dostaniesz.}
{214} {} {Dlaczego nie mo¿esz po prostu oddaæ kapsli?}
{215} {} {To jest przestêpstwo. A za przestêpstwa pracuj¹ tutaj, w kopalni.}
{216} {} {W takim razie odbiorê je si³¹.}
{217} {} {Zobaczymy.}

{218} {} {Dlaczego mia³bym to zrobiæ? Pracujê na stanowisku, na którym mam realn¹ w³adzê w tym mieœcie. Chcesz tego doœwiadczyæ?}
{219} {} {Ty te¿ masz nad sob¹ w³adzê. Jeœli nie zwrócisz kapsli, te¿ skoñczysz w kopalni.}
{220} {} {Nie ma sensu z tob¹ rozmawiaæ. Po prostu wezmê kapsle si³¹.}
{221} {} {Chyba nie chcê. Czeœæ.}

{222} {} {Blefujesz. Oprócz mnie jest tu ca³a rzesza najemników.}
{223} {} {No có¿.}
{224} {} {Lepiej zniknij. Dopóki jeszcze siê nie wœciek³em.}
{225} {} {Uspokój siê, nie gor¹czkuj siê ju¿ tak... Tu s¹ kapsle. Czy teraz zostawisz mnie w spokoju?}
{226} {} {Tak, czeœæ.}
{227} {} {Masz, weŸ wszystkie kapsle, tylko mnie nie dotykaj!}
{228} {} {Jasne, czeœæ.}
{229} {} {Ok. Nie chcê nikogo denerwowaæ.}
