{100} {} {Widzisz wiêŸnia.}
{101} {} {Widzisz nieprzyjaŸnie wygl¹daj¹cego mê¿czyznê. Jest przygnêbiony i wyczerpany.}

# Uwagi dotycz¹ce odpowiedzi
{110} {} {Jeœli tu trafisz, nie bêdzie wyjœcia.}
{111} {} {Nawet nie marzê o ucieczce.}
{112} {} {Hej! Nie wiesz, jak pozbyæ siê obro¿y?}
{113} {} {Moi krewni nie wiedz¹, ¿e tu jestem.}
{114} {} {Kiedy dostaniemy coœ do jedzenia?}
{115} {} {Masz coœ do jedzenia?}
{116} {} {Hej, jak to jest byæ wolnym?}
{117} {} {Nadzorca ma ciê¿k¹ rêkê.}
{118} {} {Jestem tak zmêczony, ¿e chcê umrzeæ!}
{119} {} {Czeœæ.}
