{100} {} {Widzisz górnika.}
{101} {} {Widzisz brudnego, wychudzonego mê¿czyznê.}
{102} {} {Ratujesz mnie przed torturami.}
{103} {} {Wow, jesteœ naprawdê odwa¿n¹ osob¹. Nie powiem nikomu, kto zabi³ Knuta.}

{110} {} {Ups! Oh oh!}
{111} {} {Zlituj siê, mistrzu!}
{112} {} {To bardzo boli!}
{113} {} {Pomó¿ mi! B³agam Ciê!}
{114} {} {Ach! Pomocy, umieram!}

{120} {} {Jesteœ najlepszy.}
{121} {} {Chcê byæ prawy. Jak siê masz.}
{122} {} {S³owa nie wystarcz¹, aby wyraziæ moj¹ wdziêcznoœæ.}
{123} {} {Nowy nadzorca jest lepszy ni¿ stary.}
{124} {} {Knut by³ okropn¹ osob¹.}
{125} {} {Jak uda³o ci siê zwolniæ Knuta?}

#Dialog
{200} {} {Dziêki, przyjacielu. Myœla³em, ¿e jestem skoñczony. Chocia¿ nie wiem ju¿, co lepsze - dalej mêczyæ siê w tej ciê¿kiej pracy, czy od razu udaæ siê do lepszego œwiata?}
{1200} {} {Dziêki pani. Myœla³em, ¿e jestem skoñczony. Chocia¿ nie wiem ju¿, co lepsze - dalej mêczyæ siê w tej ciê¿kiej pracy, czy od razu udaæ siê do lepszego œwiata?}
{201} {} {Kto ciê tak pobi³?}
{202} {} {To by³ tamten naczelnik. Wszyscy wiêŸniowie go tu nienawidz¹, nadali mu nawet przydomek - Knut. Jest tak z³y jak sam diabe³. Daj mu byle jaki powód - i natychmiast chwyta za kij.}
{203} {} {Co go rozgniewa³o tym razem?}
{204} {} {Nie mam si³y do pracy. Wiêc upad³em na ziemiê z wózkiem i rozsypa³em ca³¹ rudê.}
{205} {} {I to go wkurzy³o? Macie tu nerwow¹ sytuacjê...}
{206} {} {Ma³o powiedziane. Nie nad¹¿amy z harmonogramem i jeszcze pojawi³y siê plotki o gigantycznych gryzoniach w kopalni. Przez to szefowie siê denerwuj¹ i wy¿ywaj¹ siê przy ka¿dej okazji.}
{207} {} {Rozumiem.}
{208} {} {Hej, nie wydajesz siê byæ jednym z nadzorców. Karawaniarz, co?}
{209} {} {Nie. Szukam swojej rodziny. Ch³opi z Villi. Wiesz coœ o nich?}
{210} {} {Przecie¿ wszyscy ich tu znaj¹! Ale muszê ciê zmartwiæ - Sancho i Hugo zeszli do podziemia i jeszcze nie wrócili.}
{211} {} {Dziêki za informacje. Odpocznij, jeœli mo¿esz.}
{212} {} {Nie twoja sprawa.}
{213} {} {Ok, Ok. Moja sprawa polega na pos³uszeñstwie, mistrzu. Ale i tak dziêkujê za pomoc. Jestem na zawsze twoim d³u¿nikiem.}
{1213} {} {Ok, Ok. Moja sprawa polega na pos³uszeñstwie, pani. Ale i tak dziêkujê za pomoc. Jestem na zawsze twoim d³u¿nikiem.}
{214} {} {Dok³adnie. ZejdŸ mi z drogi.}
{215} {} {Cieszê siê, ¿e mog³em pomóc. Do widzenia.}
{1215} {} {Cieszê siê, ¿e mog³am pomóc. Do widzenia.}
{216} {} {W³aœciwie to szukam swojej rodziny. Ch³opi z Villi. Wiesz coœ o nich?}

{220} {} {Hej, to mój wybawca!}
{1220} {} {Hej, to moja wybawczyni!}
{221} {} {Do widzenia.}
{222} {} {Cicho, g³upcze.}
