{100} {} {Widzisz dzikusa.}
{101} {} {Widzisz jednego z wiêŸniów w kolonii. Wyró¿nia siê od innych przetrzymywanych.}

#Dialog
{200} {} {Nie mów do mnie, nieznajomy. Nie chce mi siê gadaæ.}
{1200} {} {Nie mów do mnie, kobieto. Nie chce mi siê gadaæ.}
{201} {} {Do widzenia.}
{202} {} {Jak siê nazywasz?}
{203} {} {Ludzie tutaj nazywaj¹ mnie Wyjcem. Ale moje prawdziwe imiê jest znacznie bardziej skomplikowane.}
{204} {} {Nie jesteœ st¹d, prawda?}
{205} {} {Wrêcz przeciwnie. Moje plemiê ¿y³o w tych górach od trzech pokoleñ. Teraz jestem jedynym, który pozosta³.}
{206} {} {Co siê sta³o z twoim plemieniem?}
{207} {} {Przyszli Ÿli ludzie z broni¹. Zabrali nam wszystko i zmusili do pracy w kopalni. Od tego czasu pozosta³em tylko ja z ca³ego plemienia.}
{208} {} {Czy chcia³byœ st¹d uciec?}
{209} {} {Nie mam dok¹d uciekaæ. Mój dom zosta³ zniszczony, a moi krewni zginêli. Mogê tylko czekaæ na Dzieñ Ostatniego Oddechu.}

{210} {} {Jeœli zacznie siê ucieczka z wiêzienia, pomo¿esz mi?}
{211} {} {Ta walka nie bêdzie mia³a dla mnie ¿adnego znaczenia.}
{212} {} {Hmm. Smieræ w bitwie to œmieræ godna prawdziwego wojownika. Zgadzam siê.}
{213} {} {Swietnie. Poczekaj na sygna³ do ataku.}
{214} {} {Jak sobie ¿yczysz, ale póŸniej mo¿e byæ za póŸno.}