{100} {} {Widzisz kolonistê.}
{101} {} {Widzisz obywatela kolonii.}
{102} {} {Lepiej mi nie przeszkadzaj.}
{103} {} {Cholera, dlaczego zabi³eœ mojego s³ugê?! Kto zwróci mi za niego kapsle?}

# Losowe repliki
{110} {} {Jesteœ niczym.}
{111} {} {Cholerny kretoszczur!}
{112} {} {Do niczego siê nie nadajesz.}
{113} {} {Wstawaj i wytrzyj swoje gluty!}
{114} {} {Nie chcê nawet brudziæ sobie butów tob¹.}
{115} {} {Czy *za to* zap³ci³em moje kapsle?}
{116} {} {Wygl¹da na to, ¿e stra¿nicy ciê przecenili, brudasie.}
{117} {} {* kopie s³u¿¹cego *}
{118} {} {Czy ty pokazujesz swoje zêby?!}
{119} {} {Jesteœ œpi¹cy? Co powiesz na but w zêby?}
{120} {} {Pamiêtaj, kto jest twoim panem.}

# Pierwszy dialog
{200} {} {(widzisz przed sob¹ niecodzienny widok, jak chudy ch³op ze z³oœci¹ uderza piêœci¹ i kopie nieustannie prosz¹cego o wybaczenie s³u¿¹cego)}
{201} {} {Hej! Dlaczego bijesz tego mê¿czyznê?}
{202} {} {To nie jest mê¿czyzna, ale moja w³asnoœæ. Wykupi³em go z zagrody jako s³ugê. A jako s³uga jest tandetny. Poza tym bêdê musia³ dok³adnie go umyæ! Ale co Ciê to obchodzi? PrzechodŸ obok i nie anga¿uj siê w sprawy innych ludzi.}
{203} {} {Masz racjê, to nie moja sprawa.}
{204} {} {Dobrze, ¿e znaleŸliœmy porozumienie. Wstañ! Wieczorem bêdziesz spaæ na ulicy. Do tego czasu wyczyœæ pod³ogê w kuchni. I ma b³yszczeæ!}
{205} {} {[Dalej.]}
{206} {} {Pobity i wyczerpany s³uga psuje tylko reputacjê swojego pana.}
{207} {} {Nikogo nie obchodzi twoje zdanie!}
{208} {} {Hmm, te s³owa daj¹ do myœlenia. Okej, bêdê dzisiaj wyrozumia³y. Ale tylko dzisiaj.}
{209} {} {[Dalej.]}
{210} {} {Zap³acê 5 kapsli, jeœli zostawisz go w spokoju.}
{211} {} {Och, s³yszysz, œmieciu? Dla Twojego spokoju p³ac¹ mi a¿ piêæ kapsli! Kto by pomyœla³, ¿e w ten sposób mo¿na zarabiaæ, co?}
{212} {} {Oto 5 kapsli.}
{213} {} {NieŸle. S³ugo! Na dziœ jesteœ wolny.}
{214} {} {[Dalej.]}
{215} {} {Jeœli znowu go skrzywdzisz, po¿a³ujesz.}
{216} {} {NAPRAWDE? Wiêc pos³uchaj mnie, redneck. To miasto rz¹dzi siê swoimi prawami. A jeœli zamierzasz je z³amaæ, to ktoœ wezwie stra¿nika. A potem zobaczymy, który z nas bêdzie „¿a³owa³”.}
{217} {} {Dobra, dobra, uszkodzony mi siê nie przyda... Ale odwa¿ siê tylko mnie dotkn¹æ, a zawo³am stra¿ników. I na pewno ci siê to nie spodoba.}
{218} {} {[Dalej.]}
{219} {} {}
{220} {} {Dam ci radê. Nie wiem, co ty sobie myœlisz, ale s³u¿¹cy w tej kolonii musz¹ byæ trzymani na smyczy. W przeciwnym razie Ÿle koñcz¹...}
{221} {} {Do widzenia.}
