{100} {} {Widzisz górnika.}
{101} {} {Widzisz okropnie brudn¹ osobê. Jej zachowanie wcale nie jest lepsze.}

# Uwagi dotycz¹ce odpowiedzi
{110} {} {* D³awi siê kaszlem *}
{111} {} {Przetrwamy tylko dziêki samozaparciu.}
{112} {} {Ka¿da podziemna zmiana mo¿e byæ ostatni¹.}
{113} {} {Ta zmiana bêdzie d³uga.}
{114} {} {Te kretoszczury s¹ olbrzymie.}
{115} {} {Kretoszczury zjadaj¹ cia³o, ale nie dotykaj¹ g³owy ani ubrania.}
{116} {} {Mówiê ci - król szczurów istnieje!}
{117} {} {Chcê jeœæ.}
{118} {} {Hej, ty! Wiesz, jak pozbyæ siê obro¿y?}
{119} {} {Jeœli tu trafisz, mo¿esz zapomnieæ o wolnoœci.}