{100} {} {Widzisz s³ugê.}
{101} {} {Widzisz s³ugê z siniakami na ca³ym wychudzonym ciele.}
{102} {} {Czy naprawdê mogê iœæ?}
{103} {} {Pomocy! W³aœciciel mnie zabije!}

# Pierwszy dialog
{200} {} {(rozgl¹da siê zmieszany) Mistrz... nie ¿yje?}
{201} {} {Nie cieszysz siê?}
{202} {} {Co mam robiæ bez mistrza?! Mistrzu... Tak! Muszê znaleŸæ nowego w³aœciciela! Muszê wróciæ do zagrody. Nie ma innego wyjœcia...}
{203} {} {Wygl¹da na to, ¿e nie umiesz nic innego w swoim ¿yciu jak tylko byæ s³ug¹.}
{204} {} {(s³uga upada ci do nóg i pochyla siê ¿arliwie z ³ysym czo³em) Dziêkujê ci, mój senorze! Jestem ci bardzo wdziêczny, senor! Dziêkujê Ci!}
{1204} {} {(s³uga upada ci do nóg i pochyla siê ¿arliwie z ³ysym czo³em) Dziêkujê, moja senora! Jestem ci bardzo wdzieczny, senora! Dziêkujê Ci!}
{205} {} {Wstawaj, uspokój siê. Swoj¹ drog¹, chcê ciê o coœ zapytaæ.}
{206} {} {Wygl¹da na to, ¿e nie jesteœ przyzwyczajony do dobrego traktowania. Wrócê, gdy odzyskasz zmys³y.}
{207} {} {Hej, nie dotykaj mnie swoimi brudnymi ³apami! Trzymaj siê z dala ode mnie!}

{210} {} {Si, mi senor?}
{1210} {} {Si, mi senora?}
{211} {} {Nic.}
{212} {} {Kolejne pytanie.}

{220} {} {Powiedz mi, dlaczego twój mistrz ciê bi³.}
{221} {} {Za kapsla, senor. Ja, nic niewarty brudas, musia³em go upuœciæ, kiedy poszed³em na zakupy dla w³aœciciela.}
{1221} {} {Za kapsla, senora. Ja, nic niewarty brudas, musia³em go upuœciæ, kiedy poszed³em na zakupy dla w³aœciciela.}
{222} {} {Pobi³ Ciê za JEDNEGO kapsla?}
{223} {} {Kapsel to du¿o, sir. Mo¿esz tu kupiæ... pó³ iguany za kapsla. Ale... (postanawia na ciebie spojrzeæ i natychmiast odwraca wzrok) Tak, to ma³a iloœæ, senor. W³aœciciel jest z³y z powodu d³ugów, bo miasto jest niespokojne.}
{1223} {} {Kapsel to du¿o, senora. Mo¿esz tu kupiæ... pó³ iguany za kapsla. Ale... (postanawia na ciebie spojrzeæ i natychmiast odwraca wzrok) Tak, to jest ma³a iloœæ, senora. W³aœciciel jest z³y z powodu d³ugów, bo miasto jest niespokojne.}
{224} {} {Widzê, ¿e sprawy tu nie uk³adaj¹ siê za dobrze.}

{230} {} {Szukam moich krewnych. S¹ tak samo zniewoleni jak ty.}
{231} {} {Wszyscy niewolnicy s¹ trzymani w zagrodzie, kiedy s¹ bez pracy. To trochê dalej id¹c g³ówn¹ ulic¹.}
{232} {} {Czy wiesz, jak pomóc im uciec?}
{233} {} {Uciec? To niemo¿liwe, panie. W ca³ym mieœcie s¹ stra¿nicy, dzia³a syrena, a wiêŸniowie nosz¹ obro¿e. Ale mo¿esz pogadaæ z dowódc¹ garnizonu. Szuka³ ludzi do jakiejœ specjalnej pracy.}
{1233} {} {Uciec? To niemo¿liwe, senora. W ca³ym mieœcie s¹ stra¿nicy, dzia³a syrena, a wiêŸniowie nosz¹ obro¿e. Ale mo¿esz pogadaæ z dowódc¹ garnizonu. Szuka³ ludzi do jakiejœ specjalnej pracy.}
{234} {} {Wiêc nadal jest szansa na pokojowe rozwi¹zanie problemu? To dobrze.}

{240} {} {Jak dosta³eœ siê do niewoli?}
{241} {} {By³em sprzedawany z r¹k do r¹k, dopóki tu nie dotar³em.}
{242} {} {Wiêc ca³e ¿ycie spedzi³eœ w niewoli?}
{243} {} {Si, senor. Oprócz moich wczesnych lat... kiedy sam dba³em o siebie.}
{1243} {} {Si, senora. Poza moimi wczesnymi latami... kiedy sam dba³em o siebie.}
{244} {} {Los nie do pozazdroszczenia.}
