{100} {} {Widzisz wiêŸnia.}
{101} {} {Widzisz jednego z wiêŸniów w kolonii. Jego wygl¹d nie budzi zaufania.}

#Dialog
{200} {} {Czego chcesz?}
{201} {} {Do widzenia.}
{202} {} {Za co siedzisz?}
{203} {} {(uœmiecha siê) Za morderstwo.}
{204} {} {Tylko jedno mordestwo?}
{205} {} {Straci³em rachubê. Autostrada jest zas³ana koœæmi podró¿ników, których obrabowaliœmy z braæmi. Ech, to by³y czasy.}
{206} {} {Blefujesz.}
{207} {} {Cholera, no mo¿e trochê sk³ama³em. A mo¿e w ogóle nikogo nie zabi³em. Ale w ostatnich latach szlaki s¹ naprawdê niebezpieczne. Ludzi jest wiêcej, a miejsca w miastach jest za ma³o dla wszystkich. Wiêc wedruj¹ wzd³u¿ szlaków we wszystkich kierunkach i czêsto s¹ ³atwym celem.}
{208} {} {Wiêc jak siê tu znalaz³eœ?}
{209} {} {Ukradliœmy byd³o przewoŸnikom. Niestety okaza³o siê, ¿e byd³o by³o przeznaczone dla potê¿nych ludzi w Phoenix. Wiêc wynajêli ³owców nagród. Dopadli nasz gang w starych ruinach. Mieli prawdziwe maszyny bojowe, sami wyszkoleni ludzie w sprzêcie za du¿e kapsle, wszystko. Musieliœmy siê poddaæ. Teraz zosta³o mi ¿a³owaæ, ¿e wybra³em ciê¿k¹ pracê zamiast egzekucji.}
{210} {} {Jeœli zacznie siê masowa ucieczka, pomo¿esz mi?}
{211} {} {Dwóch przeciwko t³umowi stra¿ników? Masz urojenia!}
{212} {} {Dwóch przeciwko t³umowi stra¿ników? Có¿, jeœli siê nad tym zastanowiæ, jest szansa, a jeœli umrê, to jeszcze lepiej. Okej, okej. Masz jak¹œ broñ dla mnie?}
{213} {} {Mo¿e. Zakryj to szmatami, ¿eby nikt nie widzia³...}
