{100} {} {Widzisz najemnika.}
{101} {} {Widzisz prywatnego najemnika pilnuj¹cego porz¹dku w kolonii.}
{102} {} {* Mamrocze do siebie *}

# Odpowiedzi - dobre nastawienie
{110} {} {Patrzê na ciebie.}
{111} {} {Chcesz zostaæ naczelnikiem?}
{112} {} {Co tutaj robisz?}
{113} {} {Nasza kolonia jest otwarta dla wszystkich... Có¿, rozumiesz.}
{114} {} {Tutaj mo¿esz dobrze zarobiæ.}
{115} {} {Mówi¹, ¿e nalot na Villê przyniós³ œwietne ³upy.}
{116} {} {Nie krêæ siê tutaj.}
{117} {} {Nie rozmawiaj z wiêŸniami.}
{118} {} {Najlepiej nie przeszkadzaæ szefowi, kiedy jest wœciek³y.}
{119} {} {Porozmawiaj z moim szefem, nie ze mn¹.}

# Odpowiedzi - Ÿle nastawienie
{120} {} {Patrzê na ciebie.}
{121} {} {Nienawidzê ludzi takich jak ty.}
{122} {} {Szybko biegasz?}
{123} {} {To jest kolonia, idŸ na spacer gdzie indziej.}
{124} {} {Nie przeszkadzaj mi.}
{125} {} {OdejdŸ, to jest obszar zamkniêty.}
{126} {} {Nie zosta³eœ tutaj zaproszony.}
{127} {} {Chcesz iœæ do zagrody? Zaraz to za³atwimy...}
{128} {} {Lepiej mnie nie wkurzaj.}
{129} {} {Ruszaj siê.}
