{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz prywatnego najemnika patroluj¹cego wejœcie do kolonii.}
{102} {} {Hmm.}
{103} {} {Zanim ten stra¿nik odzyska przytomnoœæ, mo¿esz zakraœæ siê do œrodka.}
{104} {} {Hrrr... He? WejdŸ...}
{105} {} {Stop, to obszar zamkniêty, tylko za zgod¹ szefa.}
{106} {} {Ostrzega³em!}
{107} {} {To jest obszar o wysokim poziomie bezpieczeñstwa. Nie próbuj stwarzaæ problemów.}

# Odpowiedzi - dobre nastawienie
{110} {} {Patrzê na ciebie.}
{111} {} {Nie wchodŸ do œrodka bez pozwolenia.}
{112} {} {Co jest za tymi drzwiami? Twoja œmieræ, jeœli tam pozostaniesz.}
{113} {} {Tylko za zgod¹ szefa.}
{114} {} {Nie mo¿esz tam iœæ.}

{120} {} {Zgadza siê, masz pozwolenie.}
{121} {} {Mo¿esz wejœæ do œrodka.}
{122} {} {WejdŸ, drzwi s¹ otwarte.}
{123} {} {Masz pozwolenie? To w³aŸ.}
