{100} {} {Widzisz Bystra.}
{101} {} {Widzisz chudego mê¿czyznê w okularach. Jest zajêty pewnymi obliczeniami.}
{102} {} {Nareszcie... spokój...}

# Plywajace repliki
{110} {} {Wiêc ile to osiem na szeœæ?}
{111} {} {Naprawdê nie wiem, co oznaczaj¹ te liczby.}
{112} {} {Jeœli skoñczê wczeœniej, dadz¹ mi kolejnego pieczonego szczura?}
{113} {} {Znowu awaria zasilania.}
{114} {} {To ¿elazo nie wytrzyma d³u¿ej ni¿ rok.}
{115} {} {Wygl¹da na to, ¿e to nie tylko bia³y szum.}
{116} {} {Czasami przy niskich czêstotliwoœciach s³ychaæ dziwne dŸwiêki.}
{117} {} {Trzeba zaktualizowaæ znaki wywo³awcze patrolów.}
{118} {} {Ostatni patrol nigdy siê nie skontaktowa³.}
{119} {} {Mo¿emy byæ pods³uchiwani.}

#Dialog
{200} {} {(poprawia okulary, spogl¹da w twoj¹ stronê) Och, mamo, co ty tu robisz?}
{201} {} {Szukam moich krewnych. S³ysza³eœ o ch³opach z Villi?}
{202} {} {To jest to... Ok, Ok, wiem o nich. Najemnicy zaci¹gneli tu ca³y t³um ch³opów i zamknêli ich razem z reszt¹ wiêŸniów. Nawet nie myœl o udaniu siê im na ratunek - Ÿle to siê dla ciebie skoñczy.}
{203} {} {Czy jest sposób na w³amanie siê do zagrody?}
{204} {} {Có¿, jeœli masz du¿o kapsli, Faber ciê tam po prostu wpuœci. Ale nie wiem, czy *wypuœci* ... Powiem ci jedn¹ rzecz - stra¿nicy w wiêzieniu maj¹ leniwe zajêcia, wiêc spróbuj siê dogadaæ z jakimœ.}
{205} {} {Poczekaj chwilê, muszê wiedzieæ wiêcej.}
{206} {} {Sam sobie z tym poradzê.}
{1206} {} {Sama sobie z tym poradzê.}
{207} {} {Czego chcesz?}

{208} {} {Co to za miejsce?}
{209} {} {To jest stacja radiowa. S³u¿y do komunikacji z najemnikami na odleg³oœæ. I powinieneœ siê st¹d wydostaæ tak szybko, jak to mo¿liwe, w przeciwnym razie mo¿esz Ÿle skoñczyæ.}
{210} {} {Sk¹d tu siê wzi¹³ ca³y ten sprzêt?}
{211} {} {Nie wiem. By³ tu ju¿, kiedy mnie przywieziono.}
{212} {} {Ciekawe. A na jakiej czêstotliwoœci mówi¹ najemnicy?}
{213} {} {To jest coœ, czego naprawdê nie powinienem nikomu ujawniaæ. Jeœli chcesz siê tego dowiedzieæ, idŸ do szefa i zapytaj go o to.}
{214} {} {Zmuszasz mnie do u¿ycia si³y. Podaj czêstotliwoœæ, ju¿!}
{215} {} {Cicho! Bo nas us³ysz¹... Dobra, s³uchaj, to jest czêstotliwoœæ dla patroli, a to dla stra¿ników. Tylko nie mów nikomu!}
{216} {} {Jasne.}
{217} {} {Bêdê krzyczeæ! Bêdê krzyczeæ, a oni ciê z³api¹!}
{218} {} {Nie rób tego. Uspokój siê.}

{219} {} {Tyle sprzetu do samej komunikacji?}
{220} {} {No tak... Z wyj¹tkiem kontroli obro¿y.}
{221} {} {Czy wiesz, jak zdj¹æ obro¿e wiêŸniów?}
{222} {} {Wymagany jest kod dostêpu do terminala. Mam go tylko ja i Faber. Nie, nie podam Ci go.}
{223} {} {No dalej, zrób coœ po¿ytecznego dla uciskanych takich jak ty. To Twoja szansa na rozgrzeszenie.}
{224} {} {Oszala³eœ! Jeœli z³apie ciê jeden z najemników, czeka ciê coœ gorszego ni¿ szubienica! Lepiej wyjdŸ st¹d, zanim zobacz¹ nas razem. Nie chcê problemów.}
{225} {} {Có¿... Mo¿e masz racjê. Nie wiem, czy mogê ci zaufaæ, ale pamiêtaj, ¿e mo¿emy zap³aciæ ¿yciem za taki sabota¿. Oto has³o, ale uwa¿aj!}
{226} {} {M¹dry wybór.}
{227} {} {Wygl¹da na to, ¿e sprzêt nie pochodzi st¹d.}
{228} {} {Sk¹d mam to wiedzieæ? Ja tylko wciskam przyciski.}
{229} {} {Có¿, mo¿e tak jest. Budynek jest zrujnowany, ale sprzêt jest nowszy. Antena jest wyraŸnie z innych stron.}
{230} {} {Zobaczymy.}
{231} {} {Do widzenia.}

{250} {} {Kim jesteœ?}
{251} {} {Nazywaj¹ mnie tu Bystr. Nie nadawa³em siê do pracy w kopalni, wiêc dali mnie tu, ¿eby monitorowaæ komunikacjê radiow¹.}
{252} {} {Chcesz siê st¹d wyrwaæ?}
{253} {} {Ja? Na wolnoœci? Ale... co ja tam bêdê robi³? Zarz¹dca, choæ z³y, przynajmniej karmi mnie i chroni przed rabusiami. Gdzie mia³bym pójœæ bez niego? Nie wiem...}
{254} {} {Suko, sprzeda³eœ mnie na rzecz Fabera!}
{255} {} {C-czekaj! Zlituj siê! Nie bij mnie! Jestem zwyk³ym wiêŸniem! Co powinienem by³ zrobiæ? W koñcu nie masz ¿adnych szans w starciu z najemnikami, a ja muszê tu mieszkaæ do koñca swoich dni. Gdyby Faber sam siê dowiedzia³, po prostu by mnie zabi³!}
{256} {} {Lepiej siê zamknij, zanim wepchnê ci okulary do gard³a.}
{1256} {} {Lepiej siê zamknij, zanim wepchnê ci okulary do gard³a.}
{257} {} {Ok, ¿yj, do widzenia. Naprawdê nie powinienem by³ ufaæ pierwszej lepszej osobie na swojej drodze.}
{258} {} {Kiedy sprzêt by³ sprawny, by³a to stacja radiowa. Teraz to tylko magazyn wszelkiego rodzaju œmieci. Ale osoby z zewn¹trz i tak nie maj¹ tu wstêpu.}

{260} {} {Faber nie ¿yje. Jesteœ wolny.}
{261} {} {Bo¿e, dlaczego?! Bez Fabera ca³e Flagpool jest skoñczone! Najemnicy bêd¹ teraz walczyæ o jego miejsce, a w mieœcie zaczn¹ siê pogromy i rabunki! Czy masz pojêcie, ile pracy w³o¿ono w aran¿acjê tego miejsca? Dziêkujê oczywiœcie za wolnoœæ, ale ju¿ jej nie potrzebujê.}
{262} {} {Hmm...}
{263} {} {Dlaczego nie uciek³eœ z reszt¹ wiêŸniów?}
{264} {} {Gdzie mam uciekaæ? Na pustkowia? Zagryzie mnie tam pierwszy lepszy kretoszczur. A w mieœcie nawet na mnie nie spojrz¹. Wiêzienie to jedyne miejsce, w którym doceniono moje talenty, zapewniono jedzenie i ochronê. Myœl, co chcesz, ale mnie to nie przeszkadza³o.}
{265} {} {Co za ironia. Ok, zostañ skoro tak wolisz.}