{100} {} {Widzisz górnika.}
{101} {} {Widzisz strasznie brudn¹ osobê o wyj¹tkowo napiêtym spojrzeniu.}
{102} {} {To mój koniec, przyjacielu.}
{1102} {} {To dla mnie koniec.}

{200} {} {(przed tob¹ stoi wychudzony mê¿czyzna w brudnym, podartym ubraniu; mocno trzyma nó¿ w pobli¿u obro¿y niewolnika, a krople zimnego potu sp³ywaj¹ mu po czole)}
{201} {} {Co robisz?}
{202} {} {Uch...}
{203} {} {Nie zbli¿aj siê! Zrobiê to! Lepiej umrzeæ, ni¿ znosiæ tê ciê¿k¹ pracê!}
{204} {} {Nie zrobisz tego. Spójrz na siebie - jesteœ za s³aby.}
{205} {} {Nie mów tak! Wsadzili mnie tu si³¹. Co mog³em zrobiæ?}
{206} {} {To wszystko to tylko kolejne wymówki...}
{207} {} {Zamknij siê! Zamknij siê!}
{208} {} {Co? Musisz odwróciæ wzrok, frajerze?}
{209} {} {Wiêc pewnie chcia³byœ uciec. Ale czy ko³nierz ciê nie zabije?}
{210} {} {Nie rób tego. Ta obro¿a ciê zabije!}
{211} {} {Przepraszam, nie mogê ci pomóc. Musisz to zrobiæ. No dalej - na co czekasz?}
{212} {} {WIEM! Ale moje ¿ycie ju¿ siê skoñczy³o. Jeœli umrê, to przynajmniej pozbede siê mêki. A jeœli nie? Jeœli ok³amuj¹ nas w sprawie obro¿y, mo¿e mogê siê st¹d wydostaæ.}
{213} {} {Byæ mo¿e to dobry pomys³. Mo¿e siê uda, zrób to! Smia³o!}
{214} {} {Lepiej powiem o tym nadzorcy.}
{215} {} {Powinieneœ to dok³adnie przemyœleæ. Nie poddawaj siê emocjom.}
{216} {} {Co ty mo¿esz wiedzieæ? Jestem tu zmuszany do ciê¿kiej pracy! Dlaczego mam znosiæ upokorzenie i bicie ze strony stra¿ników? To niesprawiedliwe!}
{217} {} {Cokolwiek robisz, to twoja wina. Nikt nie bêdzie wspó³czu³ istocie takiej jak ty.}
{218} {} {Wiêc idŸ i zrób to. Na co czekasz?}
{219} {} {Ok. Spróbujê ci pomóc. W koñcu nadal muszê wyci¹gn¹æ st¹d moj¹ rodzinê.}
{220} {} {Naprawdê? W takim razie przepraszam, ponios³o mnie. S³uchaj, mówi¹, ¿e obro¿e s¹ kontrolowane przez antenê radiow¹ na terenie garnizonu. Wystarczy j¹ wy³¹czyæ lub zniszczyæ. Dasz sobie z tym radê?}
{221} {} {Ok. Spróbujê. Poczekaj na sygna³.}