{100} {} {Widzisz wujka Toma.}
{101} {} {Widzisz starszego i pogodnego obywatela kolonii. Wygl¹da na to, ¿e wiele przeszed³.}

{200} {} {Czeœæ. Mam na imiê Tom. Mieszkam w tej szopie. Daj mi znaæ, co ciê do mnie sprowadza?}
{201} {} {Jestem tu od niedawna. Po prostu chcê ciê poznaæ.}
{202} {} {Och, wiêc ty te¿ próbujesz znaleŸæ swoj¹ „¿y³ê uranu”? Zapomnij. To miasto nie jest ju¿ tym, czym by³o kiedyœ na plakatach. Jeœli chcesz zarobiaæ, bêdziesz ora³ jak cholera.}
{203} {} {Nie jestem tutaj, aby zarabiaæ pieni¹dze. Szukam moich krewnych.}
{204} {} {No to powodzenia. Bêdziesz go potrzebowa³.}
{205} {} {Czy mogê zadaæ kilka pytañ?}
{206} {} {Ok. Czeœæ.}

{210} {} {Jak mogê ci pomóc?}
{211} {} {Nie dzisiaj. PA.}

{220} {} {Kim jesteœ?}
{221} {} {Nazywali mnie wujem Tomem.}
{222} {} {Coœ jeszcze chcesz powiedzieæ?}
{223} {} {Nie.}
{224} {} {Ok, zapomnij.}
{225} {} {No, opowiedz swoj¹ historiê, nikomu nie powiem.}
{226} {} {Rzecz w tym, ¿e po prostu nie chcê.}
{227} {} {Ok, zapomnij.}
{228} {} {Wygl¹da na to, ¿e by³o ci ciê¿ko, skoro wolisz trzymaæ buziê na k³ódkê.}
{229} {} {Cholera, to prawda. Byæ mo¿e jestem jedynym, który by³ w stanie przetrwaæ ciê¿k¹ pracê i osi¹gn¹æ coœ w tym mieœcie. Ale koloniœci wci¹¿ patrz¹ na mnie z góry.}
{230} {} {Dlaczego, co siê sta³o?}
{231} {} {Wiêc jesteœ by³ym kryminalist¹?}
{232} {} {Przy³apano mnie na kradzie¿y mutaowoców. Swoje w kopalni odpracowa³em i teraz jestem czysty jak ³za.}
{233} {} {To dlaczego twój dom jest taki brudny?}
{234} {} {Masz na myœli te graffiti? Lokalni ludzie nie wiedz¹, gdzie sobie ul¿yæ. Dlatego znaleŸli sobie we mnie cel. W koñcu wy dranie wiecie, ¿e nie chcê stwarzaæ sobie problemów wiêc to wykorzystujecie.}
{235} {} {Dziêki za szczeroœæ, Tom.}
{236} {} {Na twoim miejscu po³ama³bym im rêce. Ale rób jak chcesz.}
{1236} {} {Na twoim miejscu po³ama³abym im rêce. Ale rób jak chcesz.}

{240} {} {Co robisz we Flagpool?}
{241} {} {Pracujê tu i tam, a w wolnym czasie przekopujê siê przez ruiny w poszukiwaniu przydatnych rupieci. Jak dot¹d wystarcza mi na ¿ycie.}
{242} {} {Rozumiem.}
{243} {} {Jak d³ugo jesteœ w tej kolonii?}
{244} {} {Chyba kilka lat. Nie wiem dok³adnie, przepraszam.}
{245} {} {Rozumiem.}
{246} {} {Roy Faber nie ¿yje. Powinieneœ byæ zadowolony.}
{247} {} {Zadowolony? Nie wiem... Kolonia nauczy³a mnie pos³uszeñstwa i ¿ycia zgodnie z prawami innych ludzi. To okrutne, ale s³uszne. Zobacz, jaki porz¹dek tu osi¹gn¹³ Faber podczas swojej dyktatury. A teraz inni zajm¹ jego miejsce. I nikt nie wie, jak to siê skoñczy. Dlatego nie wiem, czy mam byæ szczêœliwy, czy nie.}
{248} {} {Hmm, warto siê nad tym zastanowiæ.}
{249} {} {Jesteœ ju¿ tylko zwyk³ym miêczakiem, Tom. Wiesz o tym.}
{250} {} {Czy wiesz, sk¹d wzi¹æ z³om, aby naprawiæ maszynê w kopalni?}
{251} {} {Mo¿esz kupiæ ode mnie kilka czêœci, ale to moje ostatnie zapasy, wiêcej nie mam.}
{252} {} {To nie wystarczy, Tom. Gdzie mogê uzyskaæ wiêcej przydatnych czêœci?}
{253} {} {Zartujesz sobie ze mnie? Jak mogê cokolwiek naprawiæ za pomoc¹ tych œmieci?}
{254} {} {Niech pomyœlê. Na starym mieœcie wci¹¿ s¹ nieodkryte obszary, ale s¹ to niebezpieczne miejsca. Naj³atwiej by³oby dostaæ z³om od padline¿erców w Garage City. To ma³e miasteczko na zachód st¹d.}
{255} {} {Dziêki.}
{256} {} {Rozumiem.}

{260} {} {Wiesz kto okrad³ Sonora Express?}
{261} {} {S³ysza³em o tym. Ale nie mam z tym nic wspólnego.}
{262} {} {Jeœli wiesz, kto to zrobi³, lepiej mi powiedz.}
{263} {} {Hmm... S³uchaj, kolego, nie chcê, ¿eby ktoœ mia³ przez to k³opoty, ok? Poza tym ta arogancka pani z poczty zas³u¿y³a sobie na ten los.}
{264} {} {To wszystko wyjaœnia. Ok, z przyjemnoœci¹ tak to zostawiê.}
{265} {} {Zap³acê 10 kapsli, jeœli mi powiesz, kto to zrobi³.}
{266} {} {Mogê du¿o powiedzieæ za 10 kapsli. Ale czy na pewno je masz?}
{267} {} {Nie mam ich przy sobie. Ale przyniosê je, gdy nadarzy siê okazja. Czeœæ.}
{268} {} {Oto 10 kapsli.}
{269} {} {Poczekaj chwilê, sprawdzê, czy ktoœ nie stoi za oknem... Tak, wszystko widzia³em. Zrobi³y to dzieci s¹siadów. Pamiêtaj jednak, ¿e ta rozmowa nie mia³a miejsca. I nie wa¿ siê skrzywdziæ tych dzieci.}
{270} {} {Dziêki za szczeroœæ, wujku Tom. Obiecujê, ¿e nikomu nic siê nie stanie.}
{271} {} {Nie rozkazuj mi. I ogólnie - módl siê, abym ciê nie przedstawi³ jako pomocnika m³odych z³odziei.}
{1271} {} {Nie rozkazuj mi. I ogólnie - módl siê, abym ciê nie przedstawi³a jako pomocnika m³odych z³odziei.}
{272} {} {Powiedz mi, co wiesz. Chcê pomóc.}
{273} {} {Pomóc komu? Chyba sobie zarabiaj¹c na czyjejœ krzywdzie. Nie, nie pomogê.}
{274} {} {Stawiasz siê w nieciekawej sytuacji. Bywaj.}
{275} {} {Chyba naprawdê nic nie wiesz. Do widzenia, wujku Tom.}
{276} {} {Obiecujê, ¿e nie zdradzê prawdziwego z³odzieja. Chcê tylko zwróciæ skradzione rzeczy.}
{277} {} {Obiecujesz? (wzdycha) S¹siedzi to zrobili. Dok³adniej to ich dzieci. Widzia³em wszystko przez okno. Pamiêtaj jednak, ¿e ta rozmowa nie mia³a miejsca.}