{100} {} {Widzisz najemnika.}
{101} {} {Widzisz jednego z najemników Fabera. Jest gotów pomóc ci wypêdziæ dzikusów.}

{110} {} {Nie martw siê, pomogê ci z tymi kretynami.}
{111} {} {Wkrótce nie zostanie tu ani jeden dzikus.}
{112} {} {Po prostu poka¿ mi, do kogo strzelaæ. Reszta nale¿y do mnie.}
{113} {} {Razem mamy wiêksze szanse.}
{114} {} {Patrz jaka by³a Arizona przed przybyciem Fabera.}
{115} {} {Cholerne dzikusy...}
{116} {} {To plemiê nieustannie atakuje te ziemie.}
{117} {} {Jeœli zobaczysz dzikusa, daj mi znaæ.}
{118} {} {}
{119} {} {}