{100} {} {Widzisz myœliwego.}
{101} {} {Mê¿czyzna wygl¹da na wyczerpanego.}
{102} {} {Pts! Otwórz bramê. Tylko nie pokazuj siê dzikim.}
{103} {} {Myœliwy pomyœlnie opuœci³ swój obóz.}

{200} {} {Hej! Przybywasz w sam¹ porê. Tylko b¹dŸ cicho! Ci dzicy maj¹ doskona³y s³uch. Przybywasz z Flagpool?}
{201} {} {Tak. Barman chce wiedzieæ, co siê tutaj dzieje.}
{202} {} {Dzieje siê tu gówno, tyle ci powiem. Dzicy zabili innych ³owców i zamknêli mnie tutaj.}
{203} {} {Niezupe³nie. Zgubi³em siê i mia³em nadziejê, ¿e znajdê tu miejsce do spania.}
{1203} {} {Niezupe³nie. Zgubi³am siê i mia³am nadziejê, ¿e znajdê tu miejsce do spania.}
{204} {} {Có¿, witamy w Winon. Przepraszam, ¿e nie proponujê herbatki zio³owej, ale dzicy zabili innych ³owców, a mnie zamknêli w tej klatce.}
{205} {} {To okropne.}
{206} {} {}
{207} {} {Pomo¿esz mi siê st¹d wydostaæ? Czekaj, b¹dŸ cicho! Nie poradzimy sobie z takim t³umem bez broni.}
{208} {} {To nie jest odpowiedni moment na to. Powiem ci, kiedy bêdziesz mog³ wyjœæ.}
{209} {} {Przepraszam, ale bêdziesz musia³ posiedzieæ w tej klatce trochê d³u¿ej.}
{210} {} {Ok. Wyci¹gnê ciê st¹d.}
{211} {} {Pomó¿ mi wydostaæ siê z lasu, potem sam znajdê drogê.}
{212} {} {Ok.}

{220} {} {Dlaczego te dzikusy ciê zaatakowa³y?}
{221} {} {Czy to nie jest oczywiste? Chcieli zabraæ wszystko co mamy, a jednoczeœnie - pokazaæ, kto tu rz¹dzi. To plemiê od dawna ostrzy³o sobie zêby nasz obóz.}
{222} {} {Przestañ mówiæ.}
{223} {} {Czemu tak jest?}
{224} {} {Kiedy Faber za³o¿y³ koloniê Flagpool, pierwsz¹ rzecz¹, jak¹ zrobi³, by³o wyrzucenie miejscowego plemienia z ich ziemi. Jednych zabi³, innych wywieziono do odleg³ych krain, ale ta grupa zdo³a³a przetrwaæ tylko po to, by okradaæ mieszkañców kolonii. Jednym s³owem, s¹ dzikusami.}
{225} {} {Jak pokona³y was zwyk³e dzikusy?}
{226} {} {Zaskoczy³y nas w nocy, kiedy wszyscy spali, podstêpne œmiecie. S¹ bardziej biegli w takich sprawach ni¿ my, mieszkañcy miast.}
{227} {} {Opowiedz mi o okolicy.}
{228} {} {To dzikie ziemie. Prawie nie ma tu ludzi, ale s¹ pe³ne ró¿nych zwierz¹t. W promieniu wielu kilometrów rozci¹gaj¹ siê lasy i góry. Nawiasem mówi¹c, zastawiliœmy pu³apki na zwierzêta wokó³ obozu, lepiej patrz pod nogi.}
{229} {} {Czy mo¿esz mi pokazaæ, gdzie s¹ twoje pu³apki?}
{230} {} {Pu³apki zosta³y rozstawione tam, w gêstwinie przed obozem. Patrz uwa¿nie pod nogi.}
{231} {} {Dziêki.}
{232} {} {Co wiesz o tych dzikusach?}
{233} {} {Jest to czêœæ plemienia, które kiedyœ mieszka³o na tych ziemiach. Garstka ludzi. Wiêkszoœæ z nich Faber wytêpi³, resztê wypêdzi³. Ale z jakiegoœ powodu ci wrócili. Prawdopodobnie nie mogli znaleŸæ miejsca tak bogatego w zwierzynê jak to.}
{234} {} {Jakieœ pomys³y, jak siê ich pozbyæ?}
{235} {} {Przyda³aby siê stara, dobra strzelba lub oddzia³ najemników z garnizonu. Nie mam innego pomys³u jak by ich odstraszyæ. Wydaj¹ siê byæ tak¿e bardzo przes¹dni. Popatrz tylko na te ich totemy.}
{236} {} {Jakie jest najbli¿sze miasto w okolicy?}
{237} {} {Flagpool. To kolonia górnicza na po³udniowy zachód st¹d.}
{238} {} {Dziêki.}

{240} {} {Jesteœ ju¿ bezpieczny.}
{241} {} {Kiedy dowiedz¹ siê, ¿e uciek³em, podnios¹ alarm. Ale do tego czasu bêdê ju¿ daleko. Dziêki za pomoc. Ca³e Flagpool dowie siê o twojej pomocy, kiedy tam dotrê.}
{242} {} {Powodzenia.}
