{100} {} {Widzisz Hugo.}
{101} {} {Widzisz niewolnika. Jeœli przyjrzysz siê uwa¿nie, rozpoznasz w nim swojego wspó³plemieñca po jego brudnej, wychudzonej twarzy.}
{102} {} {Ups, mam nadziejê, ¿e nikt w Villi siê o tym nie dowie...}
{103} {} {Zdrajca! Diablo ciê opêta³!}
{104} {} {Teraz Hugo nie mo¿e wróciæ do Villi.}
{105} {} {Hugo wraca do Villi.}
{106} {} {Oczywiœcie przyjacielu, jak sobie ¿yczysz.}
{107} {} {Do zobaczenia w Villi, amigo.}

# Pierwszy dialog
{200} {} {Swiête nieba, to ty! Jesteœmy ju¿ ca³kowicie zdesperowani.}
{201} {} {Jestem tutaj, aby was uwolniæ.}
{202} {} {Przybywasz w sam¹ porê! Musimy tylko dotrzeæ do wyjœcia, a potem jakoœ sobie poradzimy.}
{203} {} {Powiedz mi najpierw, co siê sta³o.}
{204} {} {To wszystko przez Sancho! Wpad³ na ten g³upi, wybuchowy pomys³. Nikt z nas nie wiedzia³, jak sobie radziæ z materia³ami wybuchowymi, ale i tak postanowi³ spróbowaæ. Zapytaj go! Sancho tu rz¹dzi.}
{205} {} {Zostañ tutaj. Porozmawiam z nim.}
{206} {} {Jesteœmy przy wyjœciu. Wolnoœæ jest tu¿ za rogiem.}

{207} {} {Si?}
{208} {} {To by³ szczur! Nigdy nie widzia³em tak wielkiego i okrutnego! Ech, chcia³bym go móc teraz usma¿yæ...}
{209} {} {Ok, chodŸmy.}

{210} {} {Hej Hugo, pamiêtasz, jak raz na mnie nakablowa³eœ?}
{211} {} {Co... czekaj...}
{212} {} {Wzi¹³em rzeczy ojca bez pytania, a ty mu o tym powiedzia³eœ. I zosta³em ukarany. Pamiêtasz?}
{1212} {} {Wziê³em rzeczy ojca bez pytania, a ty mu o tym powiedzia³eœ. I zosta³am ukarana. Pamiêtasz?}
{213} {} {(uœmiecha siê) Tak, hehe, by³o... (zmieszany) to...}
{214} {} {A teraz jestem tutaj. Ratujê twoj¹ skórê. Jak siê masz, Hugo?}
{215} {} {(mamrocze pod nosem) P-przepraszam... przepraszam za wszystko! (ociera ³zy)}
{216} {} {Jasne... Pamiêtaj o tym dniu... „przyjacielu”.}
{217} {} {Daj spokój, nie mam ci ju¿ tego za z³e, uspokój siê. ChodŸmy st¹d.}
{218} {} {No, zapomnij.}
{219} {} {W porz¹dku, Hugo, nie martw siê.}

{222} {} {Ugh, dziêki za pomoc! Teraz znajdziemy w³asn¹ drogê. Ale musisz uratowaæ resztê ch³opów. My po tym doœwiadczeniu jesteœmy teraz ma³o przydatni. Powodzenia.}
{223} {} {Ok. Do zobaczenia w Villi.}
{224} {} {Tak, pos³uchaj, Sancho mówi, ¿e musimy wysadziæ kopalnie. W przeciwnym razie tragedia siê powtórzy. W przypadku wysadzenia przedsiêbiorstwo najpewniej zbankrutuje i przestanie szukaæ nowych niewolników.}
{225} {} {Wysadziæ kopalnie? Podoba mi siê ten pomys³.}
{226} {} {Sancho gada bzdury. Eksplozja tylko doda wiêcej pracy niewolnikom.}
{227} {} {Naprawdê, zrobisz to? No to znajdŸ materia³y wybuchowe w magazynie wewn¹trz kopalni, administrator trzyma przy sobie klucz do magazynu. Powodzenia.}
{228} {} {Ale kopalnia bêdzie nadal szukaæ i wykorzystywaæ niewolników. Nasza ucieczka niczego nie zmieni, nie rozumiesz? Dobra, pomyœl o tym, my musimy iœæ. Powodzenia.}
{229} {} {Pomyœlê o tym. A teraz wynoœ siê st¹d.}