{100} {} {Widzisz Sancho.}
{101} {} {Widzisz niewolnika. Jeœli przyjrzysz siê uwa¿nie, rozpoznasz w nim swojego wspó³plemieñca po jego brudnej, wychudzonej twarzy.}
{102} {} {Ups, mam nadziejê, ¿e nikt w Villi siê o tym nie dowie...}
{103} {} {Zdrajca! Diablo ciê opêta³!}
{104} {} {Sancho nie bêdzie ju¿ móg³ wróciæ do Villi.}
{105} {} {Sancho wraca do Villi.}
{106} {} {Ok, poniewa¿ jest to konieczne.}
{107} {} {Do zobaczenia w Villi, amigo.}

# Pierwszy dialog
{200} {} {To ty? Co za niespodzianka! Myœleliœmy, ¿e ju¿ siê nie zobaczymy.}
{201} {} {Jestem tutaj, aby was uwolniæ.}
{202} {} {Swietnie, jesteœ w sam¹ porê. Pomó¿ nam dotrzeæ do wyjœcia. Potem znajdziemy w³asn¹ drogê.}
{203} {} {Jesteœmy przy wyjœciu. Wolnoœæ jest tu¿ za rogiem.}
{204} {} {Gdzie s¹ inni?}
{205} {} {Jak znalaz³eœ siê w tej pu³apce?}
{206} {} {Jak zdj¹³eœ obro¿ê?}
{207} {} {Co mo¿esz mi powiedzieæ o tych kopalniach?}
{208} {} {Sancho, pamiêtam, ¿e w Villi nie lubi³eœ mnie i nazywa³eœ mnie „jednonog¹ modliszk¹”.}
{209} {} {Ok, chodŸmy.}

{210} {} {Rozstaliœmy siê, kiedy przywieŸli nas do tego miasta. Niektórzy zostali w zagrodzie, w tym Senora Maria, twoja Madre. Resztê gdzieœ zabrali, od tamtej pory ich nie widzia³em.}
{211} {} {To by³ z³y plan. Chcieliœmy wykopaæ tunel prosto na pustkowia i uciec przez niego, ale do tego musieliœmy wykorzystaæ materia³y wybuchowe. Wszystko posz³o nie tak. Eksplozja wywo³a³a ³añcuch osuwisk i zostaliœmy odciêci od œwiata.}
{212} {} {Jeden z niewolników powiedzia³ mi, ¿e obro¿e nie dzia³aj¹ w kopalniach. }
{213} {} {To tylko g³êboka, wilgotna nora. Pe³no tu dooko³a tych gigantycznych gryzoni. W naszej Villi takich nie znajdziesz. Mówi¹, ¿e jest ich jeszcze wiêcej i s¹ nawet wiêksze od tych. Mieliœmy szczêœcie, ¿e ich nie spotkaliœmy.}
{214} {} {Po co najemnicy ciê tu zabrali?}
{215} {} {Kazali mi wydobywaæ tê cholern¹ rudê. Powy¿ej oczyszczaj¹ j¹ i zabieraj¹ do innego miasta. Mówi¹, ¿e dodaje energii i wszystko dziêki niej œwieci, ale jak to siê dzieje - nadal nie rozumiem. W Villi mamy do tego drewno na opa³ i olej, ale kamieni nie da siê podpaliæ! Prawdopodobnie zostaliœmy oszukani.}
{216} {} {Ok, okej, myli³em siê! Zapomnijmy, co siê sta³o, jesteœmy z tej samej wioski! Nie powiem wiêcej o tobie ani jednego z³ego s³owa. Serio.}
{217} {} {Czekaj, powiedz mi najpierw co siê sta³o.}

{220} {} {Co?}
{221} {} {Ten szczur by³ cholernie wielki!}
{222} {} {Ugh, dziêki za pomoc! Teraz znajdziemy w³asn¹ drogê. Ma³ej grupie bêdzie ³atwiej uciec przed najemnikami. W miêdzyczasie zajmij siê ratowaniem reszty mieszkañców wioski. Pomoglibyœmy, ale rozumiesz, ¿e po tym doœwiadczeniu nie jesteœmy w stanie. Powodzenia.}
{223} {} {Ok. Do zobaczenia w Villi.}
{224} {} {Tak, wiesz, nie chcia³bym, ¿eby ta tragedia siê powtórzy³a. Mo¿e warto wysadziæ to wszystko? Mo¿e wtedy ten biznes zbankrutuje i przestan¹ szukaæ nowych niewolników.}
{225} {} {Wysadziæ kopalnie? Podoba mi siê ten pomys³!}
{226} {} {Bardzo w¹tpliwe. To tylko doda wiêcej pracy niewolnikom.}
{227} {} {To dobrze. Materia³y wybuchowe znajduj¹ siê w magazynie wewn¹trz kopalni, a administrator ma przy sobie klucz do magazynu. Powodzenia.}
{228} {} {Opuszczenie tych kopalni w takim stanie to jak karmienie króla szczurów! Kopalnia po prostu znajdzie nowych niewolników i bêdzie kontynuowaæ swoj¹ nieludzk¹ pracê. Nie rozumiesz? A mo¿e nadal siê trzêsiesz po tym doœwiadczeniu? Dobra, pomyœl o tym, my musimy iœæ. Powodzenia.}
{229} {} {Pomyœlê o tym. A teraz wynoœ siê st¹d.}
