{100} {} {Widzisz komputer Fabera.}
{101} {} {Widzisz stary komputer. O dziwo, nadal dzia³a.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}

{210} {} {Proœby o nowych wiêŸniów.}
{211} {} {Raport z administracji kopalni: „Z powodu braku si³y roboczej terminy ponownie zosta³y zawalone. Kopalnia zbyt szybko zabija wiêŸniów. Bêdziemy musieli szukaæ nowej krwi w okolicznych osadach. Kr¹¿¹ plotki o dzikich plemionach na zachodzie.}
{212} {} {Raport z ekpedycji na zachód.}
{213} {} {Najemnicy wrócili z now¹ krwi¹. Mieszkañcy Villi okazali siê zaskakuj¹co doskona³ym materia³em - mocnym, zdrowym, odpornym. Dzicy s¹ gorsi, ale damy te¿ szansê wiêŸniom z po³udnia. Oprócz w ch³opów, Villa okaza³a siê byæ zaopatrzona w prowiant i inne przydatne rzeczy. Po drodze odkryliœmy miasto Garage City; miejscowi zaproponowali wspó³pracê, musimy to rozwa¿yæ.}
{214} {} {Incydent w kopalni.}
{215} {} {Grupa skazañców znowu zniknê³a w kopalni, okaza³o siê, ¿e to ci sami wieœniacy z Villi. Albo nie doceni³em ich, albo nasz system obronny nie jest wystarczaj¹co niezawodny. Bêdziemy musieli wprowadziæ wœród wiêŸniów profilaktykê karn¹.}
{216} {} {Wysy³ka wiêŸniów do Phoenix.}
{217} {} {Zgodnie z oczekiwaniami, czciciele ognia szybko wykupili najsilniejszych ch³opów z Villi i niektórych dzikusów. W porównaniu z reszt¹ wiêŸniów by³ to produkt najwy¿szej jakoœci. W zamian otrzymaliœmy now¹ broñ i amunicjê, której tak nam brakowa³o. Swietna okazja.}
{218} {} {Zmniejszona poda¿ miêsa.}
{219} {} {Problemy w San Brahmin ograniczy³y nasze zapasy miêsa. Bêdziemy musieli zacz¹æ polowaæ na kretoszczury i za³o¿yæ obóz traperów w górach. Cholera, znowu niespodziewane wydatki! Z drugiej strony to kolejny bodziec do rozwoju miasta.}
{220} {} {Zakoñczenie wykopalisk w Navajo.}
{221} {} {Obóz wojskowy Navajo by³ prawie bezu¿yteczny. Prawie wszystkie lokalne zasoby zosta³y zniszczone przez eksplozje w magazynach. Pozosta³y tylko zwêglone filary starych budynków. Wydobywanie ocala³ych zasobów z powodu utraty si³y roboczej jest nieop³acalne. Obóz bêdzie musia³ zostaæ zamkniêty. A zapowiada³ siê taki jackpot...}
{222} {} {Notatka osobista.}
{223} {} {Kiedy tworzy³em tê koloniê, liczy³em na zrozumienie idei Nowego Swiata. Ale wszystkich interesuj¹ tylko kapsle. Brudne ma³e rzeczy... sprawiê, ¿e uchwal¹ nowe prawa i wszystko siê zmieni!}