{101} {} {Spopielone zw³oki wiêŸnia. Przyczyna œmierci pozostaje nieznana.}
{102} {} {Spopielone zw³oki wiêŸnia. Zmar³, próbuj¹c pozbyæ siê ko³nierza.}
{103} {} {Pochowano zw³oki wiêŸnia. Ktoœ musia³ to zrobiæ.}
{104} {} {Kopanie podczas walki nie jest najlepszym pomys³em.}
{105} {} {Wiêzieñ zmar³ w wyniku silnego pora¿enia pr¹dem podczas próby pozbycia siê obro¿y.}
{106} {} {Los nie do pozazdroszczenia.}
{107} {} {Ha! Za³osny frajer.}