{110} {} {Napis na szybie mówi: „Automat do gry jest chwilowo nieczynny”.}
{111} {} {"Hej, tu statek kosmiczny! Wrzuæ monetê do tego miejsca i znajdŸ siê w niesamowitym œwiecie kosmosu!"}
{112} {} {Uda³o ci siê naprawiæ wypalone czêœci automatu. Musisz o tym powiedzieæ barmanowi.}

{120} {} {Z jakiegoœ powodu nie lubisz ju¿ tej gry.}
{121} {} {Ju¿ od samego widoku tej maszyny robi ci siê niedobrze.}
{122} {} {Aby zagraæ, u¿yj specjalnych ¿etonów na tym komputerze.}
{123} {} {Mmm! Wygl¹da fantastycznie.}
{124} {} {"Hej, tu statek kosmiczny! Obejmij ster! Jesteœ najbardziej doœwiadczonym pilotem."}
{125} {} {Nie mam *¿adnych* szans z t¹ maszyn¹.}
{126} {} {"Hej, tu statek kosmiczny! Medyk w powietrzu nie mo¿e ciê wpuœciæ w tym stanie!"}
{127} {} {Nie mogê teraz graæ.}

# Zwroty podczas gry
{130} {} {Dobra robota, pilocie! Zarobi³eœ }
{131} {} { punktów!}
{132} {} {L¹czny wynik:}
{133} {} {.}
{134} {} {}
{135} {} {Od sruby!}
{136} {} {Popisuj siê akrobacj¹!}
{137} {} {Leæ, balonie!}
{138} {} {Chcê wygraæ!}
{139} {} {No dalej! Daj spokój!}
{140} {} {To by³ z³y lot! Stracono }
{141} {} { punktów!}
{142} {} {.}
{145} {} {Zle!}
{146} {} {Cholerny gracz!}
{147} {} {Zawiod³eœ mnie, kawa³ku ¿elaza!}
{148} {} {I tak ciê podbijê!}
{149} {} {Nie!}
{150} {} {"To by³y akrobacje, kapitanie! Podbi³eœ Kosmos i mo¿esz byæ z siebie dumny!"}
{151} {} {Ugh, to ju¿ koniec... Dziwne, czujê siê trochê... pusto po wygranej.}
{152} {} {Mia³eœ napad podczas gry!}
