{110} {} {Awaria sprzêtu.}
{111} {} {Uda³o ci siê wy³¹czyæ nadajnik radiowy. Ca³a kolonia zosta³a pozbawiona ³¹cznoœci radiowej.}
{112} {} {Nie masz pojêcia, jak to dzia³a.}
{113} {} {Nie mo¿na tego naprawiæ.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Koniec sesji.}
{202} {} {Wstecz.}
{203} {} {Nadajnik radiowy nie odpowiada.}

{210} {} {Wy³¹cz monitorowanie obro¿y.}
{211} {} {Uwaga! Wy³¹czenie monitorowania obro¿y zmniejszy kontrolê nad wiêŸniami. Czy na pewno chcesz u¿yæ tej opcji?}
{212} {} {Tak, wy³¹cz obro¿e.}
{213} {} {Monitorowanie obro¿y jest wy³¹czone.}

{214} {} {Kopiuj czêstotliwoœci najemników. Dziêki temu bêdzie mo¿na pods³uchiwaæ ich rozmowy radiowe.}
{215} {} {Czêstotliwoœci radiowe skopiowane.}

{216} {} {Komentarz serwisanta.}
{217} {} {Ten œwiêty sprzêt zosta³ przywieziony z obozu Navajo, 11 mil od Flagpool i zamontowany w kolonii na chwa³ê Swiêtego Ognia w roku 2*** przez Jego pokornego s³ugê *** na rozkaz Aarona, W³adcy Phoenix. Niech niebo spadnie na tego, kto splami ten dar.}