{200} {} {"Witamy we Flagpool, najwiêkszym mieœcie na pó³noc od Phoenix! Kolonia zosta³a za³o¿ona w 2163r."}
{201} {} {Mam doœæ tych informacji.}
{202} {} {Wiêksze miasto, co? Warto siê tutaj rozejrzeæ.}

{210} {} {Co tu jest napisane?}
{211} {} {"Godzina policyjna od 00:00 do 06:00. W mieœcie obowi¹zuje zakaz noszenia broni pod go³ym niebem."}

{220} {} {Interesuje mnie mapa kolonii.}
{221} {} {Na krzywym diagramie widzisz podpisane 4 dzielnice: blok A (ta dzielnica mieszkalna), blok B (garnizon i wiêzienie) na wschodzie, blok C (kopalnia uranu) na pó³nocy oraz niezamieszkane ruiny starego miasta na wschodzie.}
{222} {} {Coœ o starym mieœcie.}
{223} {} {"Ostrze¿enie! Uwa¿a siê, ¿e w opuszczonych dzielnicach grasuje grupa z³odziei. Uwa¿aj!"}
{224} {} {Tekst zamazany. NajwyraŸniej ta informacja jest nieaktualna.}

{230} {} {Sprawdzanie tekstu.}
{231} {} {(Znajdujesz tu wiele b³êdów gramatycznych i ortograficznych, niby nic w tych czasach, ale jednak przeszkadza ci to.)}
{232} {} {Bo¿e, ile tu jest b³êdów! To nieporozumienie wymaga poprawienia...}
{233} {} {(Tekst jest w porz¹dku.)}
{234} {} {Tak. Zdecydowanie lepiej.}
{235} {} {(Nie znajdujesz b³êdów.)}
{236} {} {Tekst wydaje siê byæ w porz¹dku. No có¿, zawsze mog³o byæ gorzej...}