{110} {} {Wydaje ci siê, ¿e ten cud staro¿ytnej technologii móg³ lataæ wysoko na niebie. Bardzo wysoko.}
{111} {} {Kolejna kupa z³omu w kolejnym starym budynku.}
{112} {} {Pozyskano wszystkie przydatne czêœci z tego reliktu.}

{113} {} {To nie pomo¿e.}
{114} {} {Chocia¿ to nie wydaje siê mieæ sensu, wk³adasz czêœci z powrotem na miejsce.}
{115} {} {Uch, nigdy wczeœniej nie robi³em dziwniejszych rzeczy.}
{116} {} {Wow, nasi przodkowie byli sprytni.}