{100} {} {Widzisz barmana.}
{101} {} {Widzisz krzepkiego mê¿czyznê w fartuchu. NajwyraŸniej jest w³aœcicielem tego miejsca.}
{102} {} {Nie bêdê ciê obs³ugiwaæ, dopóki ta zbroja bêdzie w barze. Jasne?}
{103} {} {Przepraszam, ale ¿adnej broni w barze.}

# Pierwszy dialog
{200} {} {(Podchodz¹c do baru, zauwa¿asz czujnoœæ w oczach barmana i osób wokó³ ciebie). Coœ podaæ?}
{201} {} {Poproszê trochê kawy i bochenek s³odkiego chleba.}
{202} {} {(czujnoœæ innych ustêpuje miejsca oszo³omieniu i œmiechom) Nie mam nic takiego. Czy ty naprawdê nie wiesz, gdzie jesteœ?}
{203} {} {W takim razie chcê dowiedzieæ siê wiêcej o tym miejscu.}
{204} {} {Chcia³em tylko wpaœæ na chwilê. Ciekawe to miejsce, które tu masz.}
{205} {} {(unosi brew, potem wraca do swoich codziennych zajêæ, usuwaj¹c wszelkie plamy z baru) To jest bar. Mam nadziejê, ¿e wiesz, co oznacza „bar alkoholowy”.}
{206} {} {Wiêc nie mia³bym nic przeciwko odpoczynkowi tutaj.}
{207} {} {Scigam konwój niewolników.}
{208} {} {(goœcie wstaj¹ i zmierzaj¹ w twoim kierunku) Konwój niewolników? Nie. Nikogo tu nie by³o.}
{209} {} {Hmm. Myœlê, ¿e zostanê tu trochê d³u¿ej.}

# Powtarzajacy siê dialog
{210} {} {Tak?}
{211} {} {Bywaj.}

# Kieszonkowe œmieci
{220} {} {Nie ma nic prostszego. Ale czy masz czym zap³aciæ?}
{221} {} {S³uchaj, mam du¿o œmieci w kieszeniach. Zobacz, które z nich mog¹ siê przydaæ?}
{222} {} {Zaczekaj chwilê, pogrzebiê w kieszeniach...}
{223} {} {(wyrzucasz swoje œmieci z kieszeni na ladê, barman bawi siê tymi œmieciami w oszo³omieniu) Gdybym mia³ takie kieszenie, ju¿ dawno by³bym bogaty. Spójrz, jest tu przedwojenny rachunek, kilka kapsli i nabój. Za to wszystko mo¿esz kupiæ... ca³y ogon ze sma¿onej iguany, ha ha!}
{224} {} {Ugh, zawsze jakiœ po¿ytek z tych œmieci.}

# Chris z Villa
{230} {} {Czy przyszed³ tu taki facet z moich stron? Ma na imiê Chris.}
{231} {} {Swoj¹ drog¹. Facet, który przechodzi³ têdy niedawno, czy on nie jest z twojego miasta? Nazywa³ siê Chris.}
{232} {} {Tak. Gdzie poszed³?}
{233} {} {Wyszed³ z karawan¹, ale nie wiem, gdzie jest.}
{234} {} {Swietnie. Wygl¹da na to, ¿e wiêcej siê nie dowiem.}
{235} {} {Chris? Tego nie wiem.}
{236} {} {Och, w takim razie przepraszam.}

{240} {} {Hmm. Wygl¹dasz na zagorza³ego awanturnika.}
{1240} {} {Hmm. Wygl¹dasz na zagorza³ego awanturnika.}
{241} {} {Naprawdê?}
{242} {} {Jestem pewien. Mam nadziejê, ¿e nie bêdziesz sprawiaæ mi tu problemów?}
{243} {} {Nie, ¿adnych problemów, sir. Jestem cichym, spokojnym goœciem.}
{1243}{}{Nie, ¿adnych problemów, sir. Jestem raczej spokojn¹ osob¹, bez obaw.}
{244} {} {Myœlê, ¿e bary zosta³y wymyœlone specjalnie do walk.}
{245} {} {W takim razie pamiêtaj o jednej zasadzie. Jeœli zaczniesz siê awanturowaæ, od razu znajdziesz siê na ulicy i ju¿ tu nie wrócisz.}
{246} {} {Rozumiem. Nie ma problemu, proszê pana.}
{247} {} {Nie mów tak do mnie. W przeciwnym razie mogê siê zez³oœciæ.}

# O barze
{250} {} {Jakie napoje tu sprzedajesz?}
{251} {} {Spójrz i wybierz coœ sobie. W naszej okolicy to najlepszy alkohol, jaki mo¿esz znaleŸæ.}
{252} {} {Niech pomyœlê.}

{253} {} {Wiêc to wszystko to woda ognista? Powinieneœ by³ mnie od razu ostrzec!}
{254} {} {Wydajesz siê pochodziæ z miejsca, w którym nikt nigdy nawet nie s³ysza³ o barach. Trudno sobie wyobraziæ, co stanie siê z tob¹ po kilku ³ykach. Nadal chcesz spróbowaæ?}
{255} {} {Wow, nigdy wczeœniej nie widzia³em tylu mocnych trunków!}
{1255} {} {Wow, nigdy wczeœniej nie widzia³am tylu mocnych trunków!}
{256} {} {W takim razie gratulujê i witam w cywilizacji. Zamierzasz coœ zamówiæ?}
{257} {} {Sk¹d masz ten alkohol?}
{258} {} {Czêœæ pochodzi z karawan, a czêœæ od padline¿erców. I tak wszystkiego brakuje. Myœla³em o rozpoczêciu w³asnej produkcji, ale biznes przesta³ zapewniaæ dochód niezbêdny do pozyskania surowców.}
{259} {} {Rozumiem.}

{260} {} {Ka¿dy mocny napój, jaki mo¿esz dostaæ w tej okolicy.}
{261} {} {Dlaczego p³acicie tutaj kapslami? Zwykle handluje siê czymœ przydatnym.}
{262} {} {Och, jesteœ z pustkowi, prawda? Ja sam nie znam ca³ej historii, ale w du¿ych miastach wpadli na pomys³ wykorzystania kapsli jako waluty. To jak pieni¹dze przed Wielk¹ Wojn¹... Nie wiesz te¿ nic o pieni¹dzach? Có¿... w ka¿dym razie tym teraz siê wymienia.}
{263} {} {[Dalej.]}
{264} {} {Jednak kapsle zapuœci³y korzenie tylko w du¿ych miastach i rzadko s¹ u¿ywane na pustkowiach.}
{265} {} {Ciekawy pomys³.}
{266} {} {Kim s¹ idioci, którzy na to wpadli?}

{270} {} {Hej, sk¹d masz t¹ m¹kê?}
{271} {} {Kilku nieznajomych mi to sprzeda³o. Chcesz kupiæ?}
{272} {} {Ta m¹ka zosta³a skradziona z Villi przez rabusiów. Sprzedajesz skradzione towary!}
{273} {} {Mo¿e tak, ale uczciwie kupi³em ten przedmiot.}
{274} {} {[Dalej.]}
{275} {} {Teraz pos³uchaj mnie. Jesteœ tu now¹ osob¹ i jeszcze nie zas³ugujesz na szacunek. Jeœli zaczniesz rozrabiaæ, znajdziesz siê za drzwiami. Obiecujê. To jak, uspokoisz siê?}
{276} {} {Nie z³oœæ siê. Nie jestem tu niczemu winny.}
{277} {} {Jesteœ teraz na mojej czarnej liœcie, handlarzu.}
{278} {} {Ok. Tym razem ci wybaczam.}

{280} {} {Nalej wszystkim drinka. Jestem }
{281} {} { z Villi. I mam dziœ dobry dzieñ.}
{282} {} {Chcesz zdobyæ dobr¹ reputacjê wœród padline¿erców? Sprytnie. Ale bêdzie ciê to kosztowaæ 50 kapsli.}
{283} {} {Nie ma problemu, oto kapsle.}
{284} {} {Tyle kapsli za drinka dla tych kilku ludzi?! Jednak wychodzê.}
{285} {} {Chwilo mnie nie staæ. Nastêpnym razem.}
{286} {} {Masz problemy z liczeniem gotówki, prawda?}
{287} {} {...}
{288} {} {Hej wszyscy! Nieznajomy z pustkowii chce siê przedstawiæ. To dla was na jego koszt.}
{1288}{}{Hej wszyscy! Nieznajoma z pustkowii chce siê przedstawiæ. To dla was na jej koszt.}
{289} {} {Pora rozweseliæ goœci!}

{290} {} {Czeœæ. Swiêtujemy tutaj eksterminacjê Szakali. Te dzikusy sprawia³y spore k³opoty padlino¿ercom i podró¿nikom, teraz bez nich bêdzie o wiele ³atwiej.}
{291} {} {Tak, walczyli jak dzikie psy.}
{292} {} {Czy chcesz powiedzieæ, ¿e by³eœ w to zamieszany?}
{1292} {} {Czy chcesz powiedzieæ, ¿e by³aœ w to zamieszana?}
{293} {} {Poszliœmy na ich obóz z twoimi ludŸmi. Stra¿nik wie o tym.}
{294} {} {Cholera, czyli to prawda? W takim razie dam ci napój na mój koszt. Wielkie dziêki.}
{295} {} {Proszê.}
{296} {} {Powiedzia³em Stra¿nikom, a oni zlikwidowali plemiê.}
{1296} {} {Powiedzia³am Stra¿nikom, a oni zlikwidowali plemiê.}
{297} {} {No có¿. Ogólnie rzecz bior¹c, ktokolwiek to zrobi³, wyœwiadczy³ nam wielk¹ przys³ugê.}
{298} {} {Uh, wiêc œwiêtujcie dalej. Ja muszê iœæ, czekaj¹ na mnie w innych miejscach.}
{299} {} {To tylko plotki.}

{300} {} {Czy mo¿esz mi opowiedzieæ o tym mieœcie?}
{301} {} {Co chcesz wiedzieæ?}
{302} {} {Nic wiêcej.}
{303} {} {Albo coœ zamawiasz, albo nie marnuj mojego czasu.}
{304} {} {Dlaczego wszyscy tak na mnie patrz¹?}
{305} {} {Uch, dobrze. PodpowiedŸ zrozumiana.}
{306} {} {Nie b¹dŸ dla mnie niemi³y, barmanie.}
{307} {} {Dlaczego sam ich o to nie zapytasz?}
{308} {} {Co tu siê dzieje?}
{309} {} {Nic specjalnego. Miasto ostatnio podupada i nikt nie wie, co z tym zrobiæ.}
{310} {} {Dobra wiadomoœæ jest taka, ¿e kartel w koñcu uruchomi³ jedn¹ z fabryk. Tchnie ¿ycie w to umieraj¹ce miasto.}
{311} {} {Dlaczego mieszkacie w takich okropnych chatach?}
{312} {} {ZnajdŸ nam lepsze domy wœród lokalnych ruin.}
{313} {} {Nie mam dalszych pytañ na temat miasta.}

{320} {} {Jeœli masz zamiar siê tu awanturowaæ, to lepiej od razu wyjdŸ na zewn¹trz. Nie potrzebujê tu pijackich awantur.}
{321} {} {Sam bym wpad³ na to.}
{322} {} {Nie obchodzi mnie, który z was zacz¹³ walkê. Po prostu uwa¿aj na siebie i trzymaj rêce na widoku, gdy tu jesteœ.}
{323} {} {Nie martw siê, to siê wiêcej nie powtórzy.}
{324} {} {W tej dziurze pijackie bójki to wszystko na co mo¿na liczyæ.}

Konwój niewolników
{330} {} {Scigam konwój niewolników. Co o tym wiesz?}
{331} {} {Nic nie wiem. A mo¿e szklankê czegoœ mocnego?}
{332} {} {Ok, zapomnij, zapytam kogoœ innego.}
{333} {} {Powinieneœ coœ wiedzieæ.}
{334} {} {S³uchaj, nie chcê mieæ problemów z panem Koganem. Prowadzi³ interesy z w³aœcicielami niewolników. Porozmawiaj z nim.}
{335} {} {Mo¿e póŸniej. Chcê tu posiedzieæ trochê d³u¿ej.}
{336} {} {Ok, pójdê siê z nim zobaczyæ.}
{337} {} {Nie martw siê, Kogan i ja nie mamy ¿adnych problemów.}
{338} {} {Powiedz to komuœ innemu. Ale mnie w to nie anga¿uj.}
{339} {} {Wygl¹da na to, ¿e wszyscy jesteœcie tu powi¹zani.}
{340} {} {Naprawdê? Wiesz, kr¹¿¹ o tobie plotki... niezbyt pochlebne.}
{341} {} {Powa¿nie? Coœ nie zauwa¿y³em.}
{1341} {} {Powa¿nie? Coœ nie zauwa¿y³am.}
{342} {} {Jeœli mi nie powiesz, wysadzê ten bar w powietrze.}
{343} {} {Ok, dobrze. Nie ma potrzeby niczego niszczyæ. W porz¹dku?}
{344} {} {Wiêc b¹dŸ m¹dry i powiedz mi wszystko, co wiesz.}

{350} {} {Tak, wrócili do miasta w drodze powrotnej. Dawno nie mia³em takiego nap³ywu klientów.}
{351} {} {Dobrze, ¿e Twój interes siê rozwija. Ale muszê wiedzieæ, dok¹d zmierza konwój.}
{352} {} {Nie obchodzi mnie twój bar. Powiedz mi, dok¹d poszli.}
{353} {} {Chwileczkê, masz na myœli, ¿e miasto skorzysta³o na tej akcji z niewolnikami?}
{354} {} {Lokal i ja zarobiliœmy niez³e pieni¹dze, a pan Kogan podpisa³ nawet kilka nowych kontraktów. Nawet zwykli padlino¿ercy na tym zyskali. Ci handlarze niewolników tchnêli ¿ycie w nasze wysypisko. Chocia¿ na chwilê.}
{355} {} {Konwój skierowa³ siê na wschód do Flagpool City. Nawiasem mówi¹c, pan Kogan robi³ interesy z w³aœcicielami niewolników. Teraz, gdy nie ¿yje, mo¿esz przejrzeæ jego notatki, jeœli jest to dla Ciebie takie wa¿ne.}
{356} {} {Konwój skierowa³ siê na wschód do Flagpool City. IdŸ wzd³u¿ 40 autostrady federalnej, nie przegapisz. Dotarcie na miejsce powinno zaj¹æ oko³o tygodnia.}
{357} {} {Dziêki za informacje. Muszê iœæ.}
{358} {} {Teraz wiem, ¿e ty te¿ jesteœ winien nalotu. I bêdê o tym pamietaæ.}

{360} {} {Jest jakiœ problem z alkoholem?}
{361} {} {Tequila i piwo pochodzi³y z po³udnia. Ale teraz ta trasa jest zamkniêta. Nie mam nic przeciwko kupowaniu drinków z Flagpool po wy¿szej cenie, ale obecnie nie mamy sta³ej karawany nawet w tym s¹siednim mieœcie. Przyda³by mi siê chocia¿ kurier do negocjacji.}
{362} {} {Pewnie bêdê w tamtych stronach. Mogê tam z kimœ porozmawiaæ o dostawach alkoholu.}
{363} {} {Sprawy wygl¹daj¹ dla ciebie naprawdê Ÿle. Mam nadziejê, ¿e jakoœ to rozwi¹¿esz.}
{364} {} {Spróbuj. Inaczej nie mogê tam nawet wys³aæ listu. ZnajdŸ lokalnego barmana i przekonaj go, ¿eby przys³a³ tutaj drinki.}
{365} {} {Ok. Znajdê go i wrócê z odpowiedzi¹.}
{366} {} {Do widzenia.}
{367} {} {Barman z Flagpool zgadza siê dostarczaæ alkohol.}
{368} {} {Dobra robota! Mo¿e i ceny wzrosn¹, ale przynajmniej moje pó³ki nie bêd¹ ju¿ tak puste.}
{369} {} {Um. Nie myœlisz o pozostawieniu mojej pracy bez wynagrodzenia, prawda?}
{370} {} {Cieszê siê. Mam nadziejê, ¿e teraz ca³emu miastu bêdzie lepiej.}
{371} {} {Oto 100 kapsli i moja stara broñ. Wiem, ¿e to niewiele, ale spodziewam siê du¿ych wydatków!}
{372} {} {Jeszcze nigdy nikt mnie tak nie oszuka³. Zegnam.}
{373} {} {Dziêki, to mi wystarczy. I tak sprzedam tê broñ w s¹siednim mieœcie. Szczêœcia.}
{374} {} {Ok. Ale na razie zostanê tu trochê d³u¿ej.}

# Quest na szlaku handlowym
{400} {} {Czy macie tu coœ jadalnego?}
{401} {} {Coœ takiego jak miêso? To jest aktualnie problem.}
{402} {} {Dlaczego?}
{403} {} {Obroty ostatnio spad³y. Coraz mniej karawan z jedzeniem wje¿dza do miasta, poniewa¿ nie mamy czym handlowaæ. Musimy sami przetrwaæ. Ktoœ poluje na kojoty, ktoœ ³apie jaszczurki, a ktoœ bezskutecznie próbuje uprawiaæ plony.}
{404} {} {Polowanie? Wzi¹³bym udzia³.}
{1404} {} {Polowanie? Wziê³abym udzia³.}
{405} {} {Nie mo¿esz nic z tym zrobiæ?}
{406} {} {Czy to wszystko, co mo¿esz zrobiæ?}
{407} {} {Có¿, stra¿nik przy bramie powiedzia³, ¿e na pustyni zauwa¿ono dzikiego bramina. Szukaj¹ go ju¿ niektórzy padlino¿ercy. Ty te¿ mo¿esz do³aczyæ do polowania.}
{408} {} {Ciekawe. Porozmawiam najpierw z tym stra¿nikiem. Do zobaczenia.}
{409} {} {To nie moja sprawa. Bywaj.}

{410} {} {Stra¿nik mówi, ¿e by³eœ zaanga¿owany w poszukiwanie braminów.}
{1410} {} {Stra¿nik mówi, ¿e by³aœ zaanga¿owana w poszukiwanie braminów.}
{411} {} {Tak, tak.}
{412} {} {Mo¿e tak. Czy masz coœ przeciwko temu?}
{413} {} {To wyjaœnij mi, co siê tam do cholery wydarzy³o i gdzie s¹ nasi ludzie?!}
{414} {} {Twój lud pad³ ofiar¹ dzikiego bramina. Okaza³ siê silniejszy, ni¿ mo¿na by³o to sobie wyobraziæ.}
{415} {} {Cholera. Bez miêsa, bez ludzi. Ech, wygl¹da na to, ¿e znów czeka nas sezon g³odu...}
{416} {} {Serio jest a¿ tak Ÿle?}
{417} {} {Wiêc wiesz, co naprawdê siê tam wydarzy³o. Nie zamierzasz o tym rozmawiaæ, prawda?}
{418} {} {Ja? Nie? Nie. Nie zamierzam.}
{419} {} {Odetnij mi jêzyk, jeœli powiem ci, ¿e ukrad³eœ oswojonego bramina.}
{420} {} {Ok. Oto Twój udzia³. Dziêkujê, ratujesz nas od g³odu.}
{421} {} {Wiêc masz sezon g³odu?}
{422} {} {Wiêc po prostu uciek³eœ, zostawiaj¹c innych samych z problemem. Czy ty wiesz w ogóle, ile nasi ludzie musieli spêdziæ czasu na tropieniu tego bramina?}
{1422} {} {Wiêc po prostu uciek³aœ, zostawiaj¹c innych samych z problemem. Czy ty wiesz w ogóle, ile nasi ludzie musieli spêdziæ czasu na tropieniu tego bramina?}
{423} {} {Nawet nie pytaj.}
{424} {} {Zgad³eœ. Nie myœl, ¿e szybko o wszystkim zapomnimy. Zw³aszcza w sezonie g³odu.}
{425} {} {Wiêc masz sezon g³odu?}
{426} {} {Straciliœmy przez ciebie ca³¹ górê czystego miêsa! Mog³aby wykarmiæ jedn¹ osobê przez ca³y rok!}
{427} {} {Mam kilka pomys³ów.}
{428} {} {Naprawdê? Bardzo dobrze. Bo inaczej bêdziemy musieli usma¿yæ ciebie zamiast bramina. Mamy tu sezon g³odu, jest za ma³o jedzenia dla wszystkich.}
{429} {} {Serio jest a¿ tak Ÿle?}

{430} {} {Dok³adnie. Handlowaliœmy z po³udniowymi miastami, wymieniaj¹c czêœci na ¿ywnoœæ. Ale to nie wszystko, niedoœæ ¿e teraz nie mamy prawie czym handlowaæ, to jeszcze w San Brahmin og³osili bojkot. Nie sprzedaj¹ ju¿ nikomu swojego miêsa.}
{431} {} {I nic nie mo¿na z tym zrobiæ?}
{432} {} {Nie wiem. Nie mamy wiêcej karawan. Nie mogê nawet skontaktowaæ siê z ich sprzedawcami.}
{433} {} {Wygl¹da na to, ¿e masz tutaj problem.}
{434} {} {I co jeszcze. S³uchaj, tak jakby jedziesz w te strony, prawda? Jeœli bêdziesz w pobli¿u, daj znaæ kupcowi na placu o naszym problemie, mo¿e otworzy nam nasz szlak handlowy.}
{435} {} {W¹tpiê, ¿ebym kiedykolwiek by³ w tamtych stronach.}
{436} {} {Ok, porozmawiam z nim, jeœli bêdê w pobli¿u.}
{437} {} {Mogê to zrobiæ.}
{438} {} {Wyœwiadczasz nam wielk¹ przys³ugê. ZnajdŸ kupca na placu w San Brahmin i przekonaj go, by ponownie otworzy³ szlak handlowy.}

{440} {} {I jak? Dotar³y ju¿ jakieœ karawany z po³udnia?}
{441} {} {Biznes znowu siê krêci. Dziêki tobie znów otrzymujemy miêso od San Brahmin, wiêc miastu nie grozi ju¿ g³ód. Zwiêkszy³a siê równie¿ rotacja kapsli w barze. Dziêkujê Ci! Tutaj, weŸ sto kapsli za pomoc.}
{442} {} {Nie ma za co.}
{443} {} {Wznowienie handlu zwiêkszy iloœæ obrotów i kapsli w barze.}
{444} {} {Nie bêdzie karawan. San Brahmin zawar³o sojusz z Rangersami.}
{445} {} {To Ÿle... Miasto nie przetrwa d³ugo na kojotach i iguanach.}
{446} {} {Co mam teraz zrobiæ?}
{447} {} {Wiêc mo¿e kup miêso od Stra¿ników?}
{448} {} {Mogê kupiæ miêso od Stra¿ników. Ale na pewno bêdzie znacznie dro¿sze. I wcale mnie nie cieszy perspektywa bycia na ³asce tych ludzi. Wiesz, mamy z nimi doœæ napiête stosunki w Garage City. Ale wygl¹da na to, ¿e nie ma ju¿ innego wyboru.}
{449} {} {Lepsze to ni¿ nic. Porozmawiam z kimœ od nich.}
{450} {} {Lepsze to ni¿ nic. Powodzenia.}
{451} {} {Niestety ¿aden miejscowy mnie nie s³ucha. To ju¿ przesz³oœæ.}
{452} {} {Mam z³e wieœci. Nikt na terytorium Rangersów nie chce handlowaæ z tob¹ ¿ywnoœci¹.}
{453} {} {Rozumiem. Dziêki za próbê.}
{454} {} {Powodzenia. Trzymaj siê.}
{455} {} {Ktoœ na terytorium Rangersów zgodzi³ siê handlowaæ z tob¹ jedzeniem.}
{456} {} {Biznes budzi siê do ¿ycia. Dziêki tobie znowu dostajemy jedzenie, wiêc miastu nie grozi ju¿ g³ód. Ale buty Stra¿ników zdepta³y ju¿ wejœcie do mojego baru. A mo¿e tak bêdzie najlepiej? Nie wiem. W ka¿dym razie dziêki. Masz tu sto kapsli za pomoc.}
{457} {} {Nie ma za co.}
{458} {} {Nie bêdzie karawan. Plemiê rozgniewa³o siê na wszystkich obcych po serii morderstw.}
