{100} {} {Widzisz goœcia baru.}
{101} {} {Widzisz klienta baru. Ewidentnie przekroczy³ ju¿ swoj¹ dzienn¹ dawkê i aktywnie mówi o czymœ pod nosem.}

{110} {} {Nie wiem, nic nie wiem.}
{111} {} {Przepraszam, zajête.}
{112} {} {* Ik *}
{113} {} {Nie mam dla ciebie drinka. Rozumiesz?}
{114} {} {Dalej, wynoœ siê st¹d.}
{115} {} {Jeœli chcesz siê przedstawiæ, zamów wszystkim drinka.}
{116} {} {Nie dasz przyjacielowi kilku kapsli?}
{117} {} {Nie, nie dotykaj.}
{118} {} {Nie zosta³eœ tu zaproszony, znajdŸ inny stolik.}
{119} {} {Nie pijê z nieznajomymi.}

{120} {} {Hej, dziêki za drinka.}
{121} {} {Lubiê ciê.}
{122} {} {Jesteœ w porz¹dku... jak na wieœniaka.}
{123} {} {Jak siê nazywasz? Mi³o ciê poznaæ.}
{124} {} {Picie to najlepszy sposób na zapoznanie siê.}

{130} {} {Lepiej opuœæ to miasto. Mówiê powa¿nie.}
{131} {} {WyjdŸ z tego miasta.}
{132} {} {Szukasz k³opotów?}
{133} {} {Nie jesteœ tu ju¿ mile widziany.}
{134} {} {Trzymaj siê ode mnie z dala!}
{135} {} {Nie potrafisz samemu trafiæ do wyjœcia? Mogê pomóc ci kopniakiem w dupê.}

{140} {} {Siadaj, zawsze jesteœ tu mile widziany.}
{141} {} {Jak siê masz, kolego?}
{142} {} {U nas wszystko po staremu. A Ty jak siê masz?}
{143} {} {Och, nawet nie pytaj. Jak siê masz?}
{144} {} {Tak, ¿ycie jest puste jak puszka.}