{100} {} {Widzisz goœcia baru.}
{101} {} {Widzisz zrelaksowanego klienta po ciê¿kim dniu.}
{102} {} {Hej amigo, czy chcia³byœ postawiæ mi drinka na znak naszej przyjaŸni?}
{103} {} {Dziêki za drinka, amigo.}
{104} {} {Nie mam nic wiêcej do postawienia. Nastêpnym razem.}

{200} {} {Hej, zobacz, co mam. Dzia³a pobudzaj¹co. Prawdziwe lekarstwo na wszystkie problemy - wstrzykujesz i wszystkie rany magicznie siê goj¹. Chcesz?}
{201} {} {Co to jest?}
{202} {} {Mówiê ci, ¿e to przedwojenna medycyna. Nie wiem, z czego zosta³a zrobiona, ale nadal dzia³a.}
{203} {} {Mo¿e siê przyda. Co chcesz w zamian?}
{204} {} {Tak. Co chcesz w zamian?}
{205} {} {Nie wiem. W mieœcie trudno jest zdobyæ coœ wartoœciowego, nawet jeœli masz kapsle. Co powiesz na partyjkê w karty? Ty zak³adasz 10 kapsli, a ja stawiam œrodek pobudzaj¹cy. Przynajmniej nie bêdê siê nudzi³.}
{206} {} {Nie uprawiam hazardu, przykro mi.}
{207} {} {Nie interesuje mnie to. Bywaj.}
{208} {} {Swietnie, akceptujê warunki. Kto rozdaje karty?}
{209} {} {Najpierw kapsle na stó³.}
{210} {} {Jak tylko je zdobêdê, bêdziemy kontynuowaæ. Czeœæ.}
{211} {} {O tak, kochanie. To nie jest takie proste, jak siê wydaje. Myœlisz, ¿e wszystko zale¿y od szczêœcia, ale równie wa¿na jest znajomoœæ zasad i umiejêtnoœæ liczenia... Zobaczmy wiêc, kto jest dziœ lepszy...}
{212} {} {Po³ó¿ karty na stole.}
{213} {} {Za du¿o mówisz.}
{214} {} {Sam widzisz, mam asa. Czy mówi³em ju¿, ¿e nie wszystko zale¿y od szczêœcia? Haha, te kapsle nale¿¹ teraz do mnie.}
{215} {} {Cholera, nie zapomnê tej pora¿ki. Nawet nie miej nadziei.}
{216} {} {Có¿, wygra³eœ. I chyba nawet uczciwie.}
{217} {} {Wiêc widzisz, mam króla... Och, sk¹d masz asa? Cholera, oszukujesz!}
{218} {} {Gra by³a w stu procentach fair. Wszyscy to potwierdz¹.}
{219} {} {Dobra, w porz¹dku. Wygra³eœ. Ale nie myœl, ¿e po tym bêdê zadowolony, gdy znów zobaczê twoj¹ twarz w tym barze.}
{220} {} {Haha, a teraz oddaj œrodek pobudzaj¹cy i kapsle. Do zobaczenia, amigo.}
{221} {} {Uwa¿aj na jêzyk. Wezmê to.}
