{100} {} {Widzisz Larrego.}
{101} {} {Widzisz klienta o wrogim spojrzeniu i z³ych manierach.}
{102} {} {Inna sprawa. Teraz tañcz. Albo nie, idŸ do diab³a.}
{103} {} {Hej! Postaw nam drinka.}

{200} {} {Hej! Poobijane os³y zwykle nie zatrzymuj¹ siê w Garage City.}
{201} {} {[Ignoruj]}
{202} {} {Zycie tutaj wydaje siê dla nich zbyt szybkie. Prawdopodobnie myœla³eœ, ¿e uda ci siê nad¹¿yæ, co?}
{1202} {} {Zycie tutaj wydaje siê dla nich zbyt szybkie. Prawdopodobnie myœla³aœ, ¿e uda ci siê nad¹¿yæ, co?}
{203} {} {Jestem szybszy ni¿ myœlisz.}
{204} {} {(Twarz drêczyciela zmienia siê i po krótkiej przerwie wraca do sto³u) Ok, skoro tak mówisz. Ale zazwyczaj ci, którym bardzo siê œpieszy, du¿o zapominaj¹. Na przyk³ad o postawieniu obcym drinka.}
{205} {} {Nie mam zamiaru stawiaæ nikomu drinka za darmo.}
{206} {} {Zapamiêtam to.}
{207} {} {Pos³uchaj, zostaw mnie w spokoju. Próbujê tylko znaleŸæ swoj¹ rodzinê.}
{208} {} {Widzê, ¿e chyba mnie nie lubisz, co? A jeœli tak, to mi i reszcie miasta siê to nie spodoba. Na twoim miejscu postawi³bym ka¿demu drinka, ¿eby zrobiæ dobre wra¿enie.}
{209} {} {Spierdalaj, nie mam czasu na takie rzeczy.}
{210} {} {(wydyma wargê z pogard¹ i nienawiœci¹) Mo¿esz dostaæ kulkê w g³owê za to, ¿e jesteœ takim dupkiem w tym mieœcie. Zapomnê o tym, co us³ysza³em przed chwil¹, jeœli postawisz mi drinka.}
{211} {} {Kogo nazwa³eœ dupkiem, g³upku?}
{212} {} {Co jest nie tak z moj¹ przemow¹? Zycie tutaj jest zbyt szybkie dla ludzi z pustyni. Prawdopodobnie myœlisz, ¿e mo¿esz za tym nad¹¿yæ, co?}
{213} {} {Dobra, pozwól mi odejœæ. Teraz, bez zbêdnych ceregieli.}
{214} {} {Wiêc wpadasz sobie do naszego uroczego miasteczka, zak³ócasz spokój tego baru i myœlisz, ¿e mo¿esz tak po prostu wyjœæ?}
{215} {} {Uch, tak.}
{216} {} {Za³atw sprawê drinka. I idŸ do diab³a.}

{220} {} {Czego chcesz?}
{221} {} {Nic.}
{222} {} {Nic? Wiêc dlaczego, do diab³a, mnie drêczysz?}
{223} {} {Po prostu zapomnij.}

{230} {} {Kim jesteœ?}
{231} {} {Kim jestem? Jestem tym, który zna ca³e to cholerne miasto jak w³asn¹ kieszeñ. Jestem kimœ, z kim zwykle siê dzieli i rozmawia, starannie dobieraj¹c s³owa.}
{232} {} {Czy masz w ogóle imiê?}
{233} {} {Nazywam siê Larry. Powtórzyæ? A mo¿e zapamiêtasz to za pierwszym razem?}
{234} {} {Cokolwiek powiesz, Larry.}
{235} {} {Mam doœæ twoich drwin. Czas ci obiæ mordê!}
{236} {} {Nazywam siê Larry. Jestem tutaj... robiê ró¿ne rzeczy. Na przyk³ad strzegê miasta, gdy jest to konieczne. Oczywiœcie nie za darmo.}
{237} {} {Wiêc nie jesteœ padlino¿erc¹?}
{238} {} {Nie, durniu. Pochodzê z elitarnego oddzia³u wojowników, którym nie podoba siê, gdy w ich mieœcie pojawiaj¹ siê podejrzane typy.}
{239} {} {I wygl¹da na to, ¿e jestem na ich liœcie.}
{240} {} {I co zamierzasz zrobiæ? Poka¿ mi, co potrafisz, frajerze!}
{241} {} {Nie, ju¿ nic nie zbieram. Dopóki pan Kogan p³aci kapsle, nie potrzebujê tego.}
{242} {} {Nie, ju¿ nic nie zbieram. To brudna sprawa.}
{243} {} {Rozumiem.}

{250} {} {Wygl¹da na to, ¿e nie wychodzisz z tego baru?}
{251} {} {Mam du¿o do zrobienia. Jestem tu tylko po to, ¿eby zwil¿yæ gard³o. Wiêcej pytañ?}
{252} {} {Niezupe³nie.}
{253} {} {Barman serwuje tu strasznie gówniane napitki. A w nocy jest tu strasznie gor¹co. Ca³y rok czekam na coœ orzeŸwiaj¹cego. A on ma tylko to gówniane piwo. Ca³y rok.}
{254} {} {Przykro mi to s³yszeæ.}
{255} {} {Któregoœ dnia twój ty³ek bêdzie musia³ wyjœæ na zewn¹trz.}
{256} {} {Czy widzia³eœ tu konwój niewolników?}
{257} {} {Widzia³em. Ale nic ci o tym nie powiem. WyjdŸ.}
{258} {} {Ok. Jeœli nie ty, to ktoœ inny mi powie.}
{259} {} {Zaraz tego po¿a³ujesz.}

{300} {} {Co siê z tob¹ dzieje? Nie lubisz naszego spo³eczeñstwa?}
{301} {} {Spierdalaj, kretynie.}
{302} {} {Szukasz k³opotów? Bêdziemy musieli nauczyæ Ciê dobrych manier!}
{303} {} {[Broñ siê]}
{304} {} {S³uchaj, naprawdê muszê ju¿ iœæ. To bardzo wa¿ne.}
{305} {} {Wa¿ne? Hej, s³yszycie, ktoœ ma tu wa¿n¹ sprawê!}
{306} {} {Mam zamiar uratowaæ swój lud...}
{307} {} {Ooh! Szlachetny ch³op idzie ratowaæ swoich ludzi! Zróbcie miejsce wszyscy!}
{1307} {} {Ooh! Szlachetna ch³opka idzie ratowaæ swoich ludzi! Zróbcie miejsce wszyscy!}
{308} {} {Wystarczy! Wyrwê ci teraz twój pieprzony jêzyk, draniu!}
{309} {} {Naprawdê muszê iœæ.}
{310} {} {Dam ci 10 kapsli i o wszystkim zapomnimy, ok?}
{311} {} {Dobra decyzja, amigo. A teraz wynoœ siê z baru.}
{312} {} {Zmieni³em zdanie. Daj mi moje kapsle, suko!}
{313} {} {Uch huh...}