{100} {} {Widzisz pana Kogana.}
{101} {} {Widzisz pana Kogana. Nadal jest ubrany w swój brudny garnitur.}
{102} {} {Wszystko posz³o zgodnie z planem.}

{110} {} {Uwa¿aj na okolice. Nikt nie mo¿e nam przeszkodziæ tej transakcji.}
{111} {} {Rozpraw siê z tymi idiotami, podczas gdy ja zajmê siê karawan¹.}
{112} {} {Wróæ do Garage City, tam porozmawiamy.}
{113} {} {Wynoœ siê, nie chcê ciê wiêcej widzieæ.}
{114} {} {Wrócê do Garage City, ale Lucas bêdzie musia³ s³ono zap³aciæ za swoj¹ bezczelnoœæ.}
{115} {} {Ta karawana by³a nasz¹ jedyn¹ nadziej¹ na lepsz¹ przysz³oœæ...}

{120} {} {Wszystko wydaje siê byæ w porz¹dku.}
{121} {} {Cholera, to ludzie Lucasa. Rozpraw siê z nimi.}
{122} {} {Gotowe, mo¿esz wróciæ do Garage City.}

{200} {} {Nie obchodzisz mnie. Po prostu opuœæ miasto, a nic ci siê nie stanie.}
{201} {} {Lucas oferuje uk³ad. Daj mu kontrolê nad fabryk¹.}
{202} {} {Lucas straci³ moje zaufanie. Okrad³ innych padline¿erców i przej¹³ terytorium Trayvon. Powiedz mu, ¿e jeœli nie zniknie z mojego miasta, bêdzie to ostatni dzieñ jego pracowitego, ale krótkiego ¿ycia.}
{203} {} {Lucas nigdzie siê nie wybiera. Wiêc podejmij decyzjê teraz.}
{204} {} {Ok, opowiem mu o tym.}
{205} {} {Ok, musisz przegoniæ ludzi Lucasa, zanim zagrozi transakcji. Rób, co mówiê!}
{206} {} {Wygl¹da na to, ¿e siê zaczê³o...}
{207} {} {Tylko Lucas i jego ludzie mog¹ w pe³ni przywróciæ fabryce dawn¹ œwietnoœæ. Powinieneœ z nim wspó³pracowaæ.}
{208} {} {Hmmm... w sumie Treyvon i jego zespó³ niewiele wiedz¹ na te tematy. S¹ dobrzy w kopaniu w ruinach, ale fabryka potrzebuje innych umiejêtnoœci, które posiada Lucas.}
{209} {} {Wiêc co mam mu przekazaæ?}
{210} {} {O nie, nie wyjdzie z pustymi rêkoma.}
{211} {} {Ok. Niech zabierze siê do pracy. Ale niech nie liczy na niskie podatki. Nie zapomnê co zrobi³.}
{212} {} {Dziêki, panie Kogan.}
