{100} {} {Widzisz pana Kogana.}
{101} {} {Widzisz niechlujnego grubasa w brudnym garniturze. Wygl¹da na to, ¿e to on tu rz¹dzi.}
{102} {} {Zdob¹dŸ trop, gruby œwiniaku!}
{103} {} {Jak siê czuje padlino¿erca, kiedy jego los zale¿y od œmieci?}
{104} {} {Hej! To nie moja wina. Ma atak serca!}
{105} {} {Nie jestem przeciwny rozmowie z obcymi, ale najpierw wyjdŸ z tej puszki.}
{106} {} {Wynoœ siê z mojego miasta.}
{107} {} {Wynoœ siê z mojego Garage City.}

# Plywajace repliki (nie usuwaj pustych wierszy!)
{110} {} {* Khe-khe *}
{111} {} {* Uff *}
{112} {} {* Urp *}
{113} {} {* Burp *}
{114} {} {Cholerna zgaga...}
{115} {} {}
{116} {} {}
{117} {} {}
{118} {} {}
{119} {} {}

# Scena przerywana
{120} {} {}
{121} {} {Panie Kogan! Panie Kogan!}
{122} {} {Pieprzony Larry! Dlaczego, do diab³a, wpadasz tak do mojego biura?}
{123} {} {Co siê sta³o? Nikt nie wa¿y siê tak wpadaæ do mojego biura...}
{124} {} {Panie Kogan! Tam w baraku zbieraczy dosz³o do powa¿nej awantury!}
{125} {} {Co niby mog³oby siê wydarzyæ w tej dziurze? Prawdopodobnie to tylko kolejna pijacka bijatyka.}
{126} {} {Nie, nie tym razem. Nie zrozumia³em o co posz³o, od razu tu pobieg³em...}
{127} {} {Wiêc idŸ i to sprawdŸ, idioto!}

#Dialog
{170} {} {Widzia³em ju¿ ten strój. Co masz wspólnego z Wyznawcami Ognia?}
{171} {} {To proste. Jestem czêœci¹ tego koœcio³a.}
{172} {} {Hmm... Co za ciekawy zbieg okolicznoœci. Zwykle staram siê omijaæ wszelkie religie. Ale Zwolennicy napêdzaj¹ postêp w Arizonie, a co za tym idzie, w moim kartelu. Mo¿esz czuæ siê tu bezpiecznie.}
{173} {} {Có¿, to wspania³a wiadomoœæ.}
{174} {} {Czy mogê liczyæ na pe³n¹ obs³ugê warsztatu?}
{175} {} {Oczywiœcie. Dam znaæ Pete'owi.}
{176} {} {Dziêki.}
{177} {} {Po raz pierwszy s³yszê o tych "wyznawcach". Zdj¹³em ten p³aszcz ze zw³ok na pustyni.}
{1177} {} {Po raz pierwszy s³yszê o tych "wyznawcach". Zdjê³am ten p³aszcz ze zw³ok na pustyni.}
{178} {} {To prawda? W takim razie zapomnij o naszej rozmowie.}
{179} {} {Jasne.}

{180} {} {Mówi¹, ¿e mia³eœ spotkanie z Larrym?}
{181} {} {Nic specjalnego. Typowe k³opoty w barze.}
{182} {} {Musisz mieæ nerwy ze stali, jeœli myœlisz, ¿e mo¿esz ot tak zabijaæ moich ludzi. Ale z drugiej strony od dawna chcia³em siê pozbyæ tego diab³a. Robi³ za du¿o ha³asu.}
{183} {} {Wiêc nie wyœlesz za mn¹ nikogo?}
{184} {} {Bêdziesz musia³ bardzo siê postaraæ, ¿eby zdobyæ mój szacunek. Wszystko zale¿y od Ciebie.}
{185} {} {A wiêc to tak...}
{186} {} {Zacz¹³ pierwszy! Tylko siê broni³em.}
{1186} {} {Zacz¹³ pierwszy! Tylko siê broni³am.}
{187} {} {To s¹ nasze sprawy. One ciê nie dotycz¹.}

{190} {} {Znowu... (wzdycha) Czy wiesz coœ o Rangersach? Nienawidzê tych ludzi. Zawsze wtr¹caj¹ siê w nieswoje sprawy, jakby ca³e pustkowiê nale¿a³o do nich. Nie zrobisz tego samego w *moim* mieœcie, prawda?}
{191} {} {Nie, panie Kogan. Jestem tu tylko w interesach.}
{192} {} {Ok. Myœlê, ¿e siê zrozumieliœmy. Nie zapomnij, kto jest w³aœcicielem tego miejsca.}
{193} {} {Zaden problem.}
{194} {} {Lepiej mów o Rangersach z szacunkiem. Pewnego dnia ca³a Arizona znajdzie siê pod nasz¹ kontrol¹.}
{195} {} {Bardzo w to w¹tpiê. Stra¿nicy maj¹ wiele wrogów, a ich liczba jest zbyt ma³a, aby samodzielnie zarz¹dzaæ populacj¹. I na pewno nigdy nie zdobêd¹ kontroli nad tym miastem, dopóki ja ¿yjê.}
{196} {} {Jaki masz problem z Rangersami?}
{197} {} {Ja * nie * mam z nimi problemu. Ale nie zamierzam dzieliæ siê w³adz¹ z nikim. W³o¿y³em zbyt du¿o pracy w to miejsce i stworzy³em ca³e to miasto od zera.}
{198} {} {Tak, mo¿esz tak sobie myœleæ.}
{199} {} {Rangersi s¹ zajêci w³asnymi interesami. Nie s¹ w stanie stworzyæ nowych miejsc pracy. A w³aœnie tego ludzie teraz potrzebuj¹.}

{200} {} {(Widzisz bardzo dobrze od¿ywionego mê¿czyznê w znoszonym garniturze, który wygl¹da nie na miejscu na tle otaczaj¹cego wysypiska œmieci. Kiedy ciê zauwa¿a, odwraca uwagê od jakiegoœ urz¹dzenia i zdejmuje pod³¹czone do niego s³uchawki.)}
{201} {} {Um. Czy to Ty tu rz¹dzisz?}
{202} {} {(odk³ada s³uchawki i naciska kilka przycisków na urz¹dzeniu, a nastêpnie wskazuje na samo urz¹dzenie) To jest stary gramofon. Zosta³y one wyprodukowane przez s³ynn¹ firmê Watts Electronics przed Wielk¹ Wojn¹. Model nie jest najdro¿szy, ale bardzo niezawodny, poniewa¿ jak widzisz przetrwa³ do dziœ.}
{203} {} {[Pos³uchaj]}
{204} {} {Dlatego uwielbiam stare rzeczy. Nasi przodkowie pope³nili wiele b³êdów, ale wiedzieli, jak tworzyæ rzeczy. W tamtym czasie w Arizonie dzia³a³o wiele fabryk ró¿nych specjalnoœci. A teraz ¿adna z nich nie dzia³a.}
{205} {} {To ju¿ przesz³oœæ, kto dziœ potrzebuje tych œmieci?}
{206} {} {Wiedzia³em, ¿e tego nie docenisz. Wiêc, czego tu szukasz, ch³opcze?}
{1206} {} {Wiedzia³em, ¿e tego nie docenisz. Wiêc, czego tu szukasz, pani?}
{207} {} {Tak... Swiat zdecydowanie du¿o na tym straci³.}
{208} {} {M? Myœla³em, ¿e masz inne zdanie. W ka¿dym razie mamy bardzo niewiele mo¿liwoœci, aby to naprawiæ. Wiêc, czego tu szukasz, ch³opcze?}
{1208} {} {M? Myœla³em, ¿e masz inne zdanie. W ka¿dym razie mamy bardzo niewiele mo¿liwoœci, aby to naprawiæ. Wiêc, czego tu szukasz, pani?}
{209} {} {Przestañ z tym nonsensem. Nie przyby³em tutaj po to, aby tego s³uchaæ.}
{1209} {} {Przestañ z tym nonsensem. Nie przyby³am tu po to, aby tego s³uchaæ.}
{210} {} {Nie lubisz zbyt du¿o mówiæ, prawda? Wiêc, czego tu szukasz, ch³opcze?}
{1210} {} {Nie lubisz zbyt du¿o mówiæ, prawda? Wiêc, czego tu szukasz, pani?}

{211} {} {Jestem tutaj, poniewa¿ ktoœ zniewoli³ ch³opów z Villi i poprowadzi³ ich w tym kierunku.}
{212} {} {Nikt nie lubi, gdy siê mu przeszkadza. Nie podoba mi siê, ¿e w ruinach mo¿e zabrakn¹æ surowców, w wyniku czego muszê szukaæ nowych miejsc dla kopalni. A mam pod swoj¹ komend¹ dziesi¹tki padline¿erców i kilka kontraktów.}
{213} {} {[Dalej.]}
{214} {} {Villa ma szczêœcie. Ale ludziom tego typu trudno jest to zrozumieæ. Kiedy ty jesteœ zajêty swoimi wewnêtrznymi zmartwieniami, my, padlino¿ercy, zapewniamy sprzêt dla ca³ej po³udniowej Arizony. Nie s¹dzê, ¿eby ktokolwiek inny przejmowa³ siê losem Villi, z wyj¹tkiem miejscowych ch³opów.}
{215} {} {Ty draniu, to ty rozkaza³eœ schwytaæ ch³opów?}
{216} {} {Wiêc nie zaprzeczasz ¿e mia³eœ swój udzia³ w nalocie?}
{217} {} {Ja? Oczywiœcie, ¿e nie. By³ to pomys³ innej, bardziej wp³ywowej organizacji. My znaleŸliœmy siê po drodze. Ja na twoim miejscu zapomnia³bym o tej historii i wróci³ do mojego pustego domu, aby zacz¹æ wszystko od nowa.}
{218} {} {Myœlisz, ¿e to takie proste?}
{219} {} {Nie masz innego wyjœcia. Mo¿esz jednak zostaæ tutaj i pracowaæ jako padlino¿erca, jeœli chcesz. Co ty na to?}
{220} {} {Ja...}
{221} {} {Wydajesz siê byæ zachwycony nasz¹ tragedi¹.}
{222} {} {Zachwycony? Nie. Ale kiedy MY potrzebowaliœmy pomocy w czasie g³odu, WY w miêdzyczasie wykorzystaliœcie to i za¿¹daliœcie od nas podwójnych cen za swoje towary. Mi³o jest tym razem samemu poczuæ siê jak œmieæ?}
{223} {} {Nie o to pytam.}

{230} {} {Ci padlino¿ercy potrafi¹ staæ siê nie do zniesienia, kiedy siê upij¹... S³uchaj, jeœli zamierzasz zostaæ w mieœcie, bêdziesz potrzebowaæ mojej ochrony. A teraz nadarzy³a siê doskona³a okazja, by na ni¹ zas³u¿yæ.}
{231} {} {Prosisz mnie o uspokojenie swoich pracowników?}
{232} {} {IdŸ do baraku i zobacz, co siê tam sta³o. Nie potrzebujê dodatkowych problemów w mieœcie.}
{233} {} {Zobaczê, co bêdê móg³ zrobiæ.}
{234} {} {Chyba nie chcê dla ciebie pracowaæ.}
{235} {} {Swietnie. A tak, nie przedstawi³em siê. Karl Kogan. A teraz przejdŸmy do rzeczy.}
{236} {} {. ... .}
{237} {} {Wiêc nie nale¿ysz do Garage City. Wynoœ siê z mojego miasta.}
{238} {} {. ... .}
{239} {} {Dlaczego mia³bym mieszaæ siê w lokalne sprawy?}
{240} {} {Czy moja przychylnoœæ to za ma³o? Pamiêtaj, wiem wszystko o twoich wrogach - wiêcej ni¿ ktokolwiek inny w Garage City.}
{241} {} {Czego dowiedzia³eœ siê o bójce w baraku?}
{1241} {} {Czego dowiedzia³aœ siê o bójce w baraku?}
{242} {} {Niczego. Zajmê siê tym teraz.}
{243} {} {Czy mogê zadaæ kilka pytañ?}
{244} {} {Najpierw udowodnij, ¿e zas³ugujesz na moj¹ uwagê. A mo¿e ju¿ chcesz wyjechaæ z miasta?}
{1244} {} {Po pierwsze, udowodnij, ¿e jesteœ godna mojej uwagi. A mo¿e ju¿ chcesz wyjechaæ z miasta?}
{245} {} {Ok, post¹piê zgodnie z twoimi instrukcjami.}
{246} {} {To w³aœnie zamierzam zrobiæ.}
{247} {} {Ludzie Lucasa okradli ludzi Trayvona i opuœcili miasto. Rozmawiali o jakimœ dekoderze.}
{248} {} {Idioto! Ile czasu minê³o, odk¹d da³em ci to zadanie? Twoje szanse na udowodnienie swojej przydatnoœci szybko malej¹.}
{1248} {} {Wiem, do cholery! Ile czasu minê³o, odk¹d da³em ci to zadanie? Twoje szanse na udowodnienie swojej przydatnoœci szybko malej¹.}
{249} {} {Co siê dzieje?}
{250} {} {Nie spodziewa³em siê tego po Lucasie. Jego klan ma reputacjê ma³ego, ale mocnego zespo³u. Jeœli zdecyduje siê wyst¹piæ przeciwko mnie, bêdzie musia³ s³ono za to zap³aciæ.}
{251} {} {Mam pytania dotycz¹ce tej historii z Lucasem.}
{252} {} {Czy jest coœ jeszcze, co mogê dla pana zrobiæ, panie Kogan?}
{1252} {} {Czy jest coœ jeszcze, co mogê dla pana zrobiæ, panie Kogan?}

{253} {} {Mam odpowiedzi.}
{254} {} {Dlaczego klany s¹ tak zaciek³e wobec siebie?}
{255} {} {Dochody kopalni ostatnio spad³y, co utrudnia zbieraczom przetrwanie. Wczeœniej klany dobrze siê dogadywa³y - pracy wystarcza³o dla wszystkich. Teraz wszyscy stali siê zaciek³ymi konkurentami.}
{256} {} {O co chodzi z tym dekoderem?}
{257} {} {To rzadkie urz¹dzenie do hakowania systemów elektronicznych. Zamówi³em taki dekoder za du¿¹ sumê kapsli przez po³udniowe karawany i przekaza³em go klanowi Trayvon, aby otworzy³ star¹ fabrykê. To jedyne miejsce, do którego jeszcze nie zajrzeliœmy z powodu cholernego systemu bezpieczeñstwa. Wygl¹da na to, ¿e Lucas postanowi³ omin¹æ nas wszystkich w tej operacji.}
{258} {} {Po co dzieliæ padline¿erców na klany?}
{259} {} {Oni sami tego chcieli. Ludzie potrzebuj¹ autorytetu, tak dzia³a ich myœlenie. Nie obchodzi mnie, komu dajê instrukcje. Najwa¿niejsze, ¿e s¹ pos³uszni i nie stwarzaj¹ problemów.}
{260} {} {Doœæ o padlino¿ercach.}
{261} {} {Przestañ mówiæ o kartelu.}
{262} {} {Mam doœæ tych mrocznych historii. PA.}

{270} {} {Czy jesteœ lokalnym naczelnikiem?}
{271} {} {Naczelnikiem... Czy tak ch³opi nazywaj¹ burmistrza? Nie, miasto nie potrzebuje naczelnika. Przynajmniej na razie. Jestem szefem kartelu œmieciarzy. Ale poniewa¿ ca³e miasto jest zwi¹zane z tym biznesem, ¿adna wa¿na decyzja nie obejdzie siê beze mnie. W tym sensie mo¿esz mnie uwa¿aæ za „naczelnika”.}
{272} {} {Wiêc jesteœ burmistrzem tego miasta?}
{273} {} {Mówiê ci, ¿e miasto nie potrzebuje burmistrza. Przynajmniej na razie. Jestem szefem kartelu œmieciarzy. Ale poniewa¿ ca³e miasto jest zwi¹zane z tym biznesem, ¿adna wa¿na decyzja nie obejdzie siê beze mnie. W tym sensie mo¿esz mnie uwa¿aæ za burmistrza.}
{274} {} {Jak przej¹³eœ kontrolê nad miastem? Z pewnoœci¹ po trupach?}
{275} {} {G³upie stereotypy. Zaczyna³em jako zwyk³y œmieciarz w Wielkim Mieœcie. Kartel ju¿ istnia³, ja tylko obj¹³em wolne stanowisko w administracji. A potem otworzyliœmy filiê w tych ruinach i postanowi³em przenieœæ siê tutaj, aby osobiœcie nadzorowaæ prace.}
{276} {} {Wygl¹da na to, ¿e nie chcesz wracaæ.}
{277} {} {Obawiam siê, ¿e mamy... odmienne cele z g³ównym biurem.}
{278} {} {Co robi twój kartel?}
{279} {} {G³ównie wydobywa sprzêt w starych ruinach. Ponad sto lat po Wielkiej Wojnie wiele rzeczy uleg³o zniszczeniu, ale niektóre przetrwa³y i wci¹¿ mog¹ byæ przydatne dla spo³eczeñstwa. Próbujemy te¿ naprawiaæ niektóre rzeczy, ale jest to znacznie bardziej skomplikowane.}

{280} {} {Moja wioska nie ¿yczy sobie dzia³aj¹cej fabryki w s¹siedztwie.}
{281} {} {Dlaczego nie? A tak, wiele s³ysza³em o twoich przes¹dach i strachu przed star¹ technologi¹. Có¿, nie masz wyboru. Musisz siê z tym pogodziæ.}
{282} {} {Naprawdê?}
{283} {} {Teraz nikt nie pozwoli twojej spokojnej wiosce rozkwitaæ sobie dziêki pracy fizycznej i ¿yæ zgodnie z prawami sumienia. Miasta odradzaj¹ siê na nowo. Jeœli nie teraz, to póŸniej przyjedzie tu ktoœ, by przywróciæ fabrykê do stanu sprzed wojny. To nieuniknione.}
{284} {} {Wygl¹da na to, ¿e faktycznie nie da siê z tym nic zrobiæ. PA.}
{285} {} {Starsi chc¹ izolacji. Nie podoba im siê fakt, ¿e nieznajomi znów przyjd¹ do doliny.}
{286} {} {Jak powiedzia³em, jest to nieuniknione. Wszystko, co mo¿ecie zrobiæ, to siê na to przygotowaæ. Mo¿na by³o kupowaæ broñ, budowaæ ogrodzenia, przywracaæ utracone mienie, a nawet stworzyæ wydajniejszy system nawadniania. A do tego, co dziwne, potrzebujecie tylko us³ug mojego przedsiêbiorstwa.}
{287} {} {To oferta?}
{288} {} {Bior¹c pod uwagê, ¿e ca³e miasto jest ci wdziêczne i ¿e fabryka zosta³a otwarta przez twoje rêce, oferujê swoje us³ugi dla twojej Villi po bardzo niskich kosztach. To da prace miastu i pozwoli twoim ludziom przygotowaæ siê na nieuniknione. Wszyscy na tym skorzytaj¹.}
{289} {} {Brzmi interesuj¹co. Ale jest problem z przekonaniem starszych do czegokolwiek. Pomyœlê o tym.}

{300} {} {Co myœlisz?}
{301} {} {Nic specjalnego. Pójdê coœ zrobiæ.}

# Zadanie 2
{310} {} {Stary Lucas pope³ni³ niewybaczalny b³¹d. Uderzy³ w moj¹ reputacjê. A co gorsze, zrujnowa³ moje plany.}
{311} {} {[Pos³uchaj]}
{312} {} {Ale nie o to teraz chodzi, zajmê siê tym póŸniej. O wiele wa¿niejsze jest zdobycie elementów radiowych z zak³adu. Potrzebujê ich jak najszybciej. Mo¿esz to zrobiæ?}
{313} {} {A jeœli zabijê Lucasa?}
{314} {} {W¹tpiê, czy masz ducha i umiejêtnoœci. A jeœli ciê zabij¹, nic na tym nie zyskam. Po prostu daj mi to, o co proszê.}
{315} {} {Rozumiem. Zrobiê to.}
{316} {} {Nie, nie. Poszukaj innego g³upca do tej roboty.}
{317} {} {Oczywiœcie. Zrobiê to.}
{318} {} {Co za to dostanê?}
{319} {} {Oczywiœcie zap³acê ci za tê pracê. Ale mój szacunek jest wart znacznie wiêcej.}
{320} {} {Czy jest coœ jeszcze, co mogê dla pana zrobiæ, panie Kogan?}
{1320} {} {Czy jest coœ jeszcze, co mogê dla pana zrobiæ, panie Kogan?}

{330} {} {Oto czêœci z opuszczonej fabryki.}
{331} {} {Swietnie. Zaczynam ciê lubiæ. Teraz wszystko zale¿y od drobiazgu - daæ to klientowi.}
{332} {} {A co z moj¹ nagrod¹?}
{333} {} {Otrzymasz j¹ po pomyœlnym zakoñczeniu transakcji.}
{334} {} {O co chodzi?}
{335} {} {Czekam na jedn¹ bardzo wa¿n¹ karawanê, która rozpocznie nowy kamieñ milowy w historii tego miasta. Karawana pod¹¿a za tym kawa³kiem. Potrzebujê niezawodnych ludzi, którzy bêd¹ wszystkiego pilnowaæ podczas transakcji. Jesteœ z nami?}
{336} {} {A jeœli odmówiê?}
{337} {} {Wtedy bardzo mnie zdenerwujesz. Lepiej mnie nie denerwowaæ.}
{338} {} {W takim razie muszê ciê zdenerwowaæ, grubasie.}
{1338} {} {W takim razie muszê ciê zdenerwowaæ, grubasie.}
{339} {} {Có¿, to by³o doœæ g³upie z twojej strony. Wynoœ siê z mojego miasta. I nie dostaniesz ¿adnej nagrody.}
{340} {} {...}
{341} {} {Tak. Jestem z tob¹.}
{342} {} {Bardzo dobrze. Przygotuj siê na spotkanie, weŸ wszystko, czego potrzebujesz. Nastêpnie wróæ do mnie.}
{343} {} {Ok.}
{344} {} {Ok, co mam zrobiæ?}

# Quest 3
{350} {} {}
{351} {} {Jesteœ gotowy?}
{1351} {} {Jesteœ gotowa?}
{352} {} {Tak, jestem gotowy.}
{1352} {} {Tak, jestem gotowa.}
{353} {} {Nie, mam coœ innego do zrobienia. To nie zajmie du¿o czasu.}
{354} {} {Uwa¿aj. Nikt nie wie o tej transakcji, ale wszystko mo¿e siê zdarzyæ. Ja porozmawiam z karawan¹, Twoim zadaniem jest upewnienie siê, ¿e wszystko idzie tak, jak powinno. Klient powinien wyjœæ zadowolony.}
{355} {} {Cel jest jasny.}
{356} {} {Muszê siê odlaæ przed t¹ wa¿n¹ spraw¹. Nied³ugo wrócê.}

{360} {} {Wszystko posz³o dobrze, prawda?}
{361} {} {To by³a œwietna okazja. Nie masz pojêcia, jak bardzo. Nie tylko zarobiliœmy kapsle. Daliœmy miastu szansê na przetrwanie.}
{362} {} {Co masz na myœli?}
{363} {} {To miasto siê degeneruje. Przetrwaliœmy wydobywaj¹c zasoby z ruin, ale ich rezerwy sta³y siê niewystarczaj¹ce. Aby przetrwaæ, miasto potrzebuje nie tylko nowych zamówieñ, ale zupe³nie nowej produkcji.}
{364} {} {Wiêc zamierzasz odbudowaæ tê fabrykê?}
{365} {} {Tak. By³oby to jednak bezcelowe bez potê¿nego Ÿród³a energii. A mo¿na je zdobyæ tylko we Flagpool - mieœcie, z którego przyby³a ta karawana.}
{366} {} {Swietny pomys³. W³aœnie tego brakuje spustoszonemu œwiatu.}
{367} {} {Cieszê siê, ¿e osi¹gnêliœmy porozumienie. Któregoœ dnia zobaczysz Garage City jak za dawnych dobrych czasów - ze œwiec¹cymi lampami pró¿niowymi z energicznym be-bopem i motocyklistami na prawdziwych motorach.}
{368} {} {A co z nasz¹ umow¹?}
{369} {} {Dzia³aj¹ca fabryka to szaleñstwo!}
{370} {} {Wielu ludzi myœli podobnie. Ale jestem pewien swoich umiejêtnoœci. Pewnego dnia zobaczysz Garage City jak za dawnych dobrych czasów - ze œwiec¹cymi lampami pró¿niowymi z energicznym be-bopem i motocyklistami na prawdziwych motorach.}
{371} {} {A co z nasz¹ umow¹?}
{372} {} {Tak, to œwietnie. A co z nagrod¹?}
{373} {} {Nie obchodzi mnie to. Interesuje mnie tylko nasza umowa.}

{380} {} {Szanujê moich partnerów biznesowych. Oto twoja zap³ata za robotê - masz tu 200 kapsli. Powiem te¿ Pete'owi, ¿eby ci s³u¿y³ najlepiej, jak potrafi. Rozgoœæ siê.}
{381} {} {Pójdê wydaæ kapsle.}
{382} {} {A co z Vill¹ i najeŸdŸcami?}
{383} {} {A ty znowu swoje... Konwój niewolników wyruszy³ do Flagpool na wschodzie, tydzieñ st¹d. IdŸ wzd³u¿ 40. autostrady federalnej, nie przegapisz.}
{384} {} {Dobrze, to teraz zajmê siê tymi cholernymi najeŸdŸcami.}
{385} {} {Mam nadziejê, ¿e znajdê coœ, na co warto wydaæ te zarobione kapsle.}
{386} {} {Jak mog³eœ zaakceptowaæ handlarzy niewolników? Czy nie przeszkadza Ci sumienie?}
{387} {} {Wiesz, grubasie. Gdybym mia³ bombê atomow¹, po tym, co us³ysza³em, wysadzi³bym ca³e to miasto w powietrze. Ale jej nie mam. Niestety.}
{1387} {} {Wiesz, grubasie. Gdybym mia³a bombê atomow¹, po tym, co us³ysza³am, wysadzi³abym ca³e to miasto w powietrze. Ale jej nie mam. Niestety.}
{388} {} {Aha. W porz¹dku. Bywaj.}

{390} {} {Mo¿e ciê ucieszyæ wiadomoœæ, ¿e Lucas nie ¿yje.}
{391} {} {Dobra robota. Oto twoja nagroda, 100 kapsli. Mo¿esz je wydaæ w lokalnym barze, choæ nie s¹dzê, ¿ebyœ zosta³ tam mile przywitany.}
{392} {} {Dziêki za kapsle, panie Kogan.}
{393} {} {Liczy³em na inn¹ kwotê za tak¹ brudn¹ robotê. Ale ta wystarczy.}
{1393} {} {Liczy³am na inn¹ kwotê za tak¹ brudn¹ robotê. Ale ta wystarczy.}
{394} {} {Czy mogê zadaæ pytanie? Jak to jest pozbyæ siê konkurenta?}
{395} {} {Jak siê czuje osoba, która pozbywa siê œmieci? Przypuszczam, ¿e czuje ulgê. Chocia¿, przyznajê, mam te¿ pewne poczucie straty.}
{396} {} {Kontynuuj.}
{397} {} {Naprawdê?}
{398} {} {Lucas by³ jednym z najlepszych padline¿erców. Kiedyœ byliœmy nawet przyjació³mi. Ale nawet tak doœwiadczona i wartoœciowa osoba okaza³a siê w koñcu zdrajc¹ i da³a z³y przyk³ad innym. I dlatego na pewno nie bêdzie mi go brakowaæ.}
{399} {} {Oryginalny punkt widzenia.}