{100} {} {Widzisz przed sob¹ bramina.}
{101} {} {Widzisz bramina szukaj¹cego rzadkiej roœlinnoœci na suchym l¹dzie.}
{102} {} {Mooo!}
{103} {} {Moo?}
{104} {} {Jesteœ za daleko. Bramin straci³ ciê z oczu.}
{105} {} {?}

{200} {} {Moo?}
{201} {} {Nie martw siê. Tylko przechodzê.}
{202} {} {ChodŸ za mn¹, zwierzaku, dam ci coœ smacznego.}
{203} {} {Moo!}
{204} {} {Nie, nie idŸ za mn¹. Pasterzom siê to nie spodoba.}
{205} {} {ChodŸ, chodŸmy, zanim dzikusy zobacz¹...}