{100} {} {Widzisz padlino¿ercê.}
{101} {} {Widzisz padlinozercê gotowego zapolowaæ na bramina.}
{102} {} {Cholera! Ten bramin jest czyjœ. Ale nadal musimy go zabraæ. Jasne?}

{110} {} {Nie ka¿ nam tego ¿a³owaæ.}
{111} {} {Bramin jest nasz. Wracaj do miasta i powiedz barmanowi.}
{112} {} {Nie s¹dziliœmy, ¿e to siê tak skoñczy!}

{200} {} {Okazuje siê, ¿e ten bramin wcale nie jest dziki, co? Pos³uchaj, musimy go zdobyæ mimo to.}
{201} {} {Zamierzasz zaatakowaæ pasterzy?}

{202} {} {Miasto umrze bez jedzenia, handel prawie nie istnieje, POTRZEBUJEMY tego bramina! Masz wiêc jakieœ lepsze pomys³y?}
{203} {} {Wchodzê w to. Zaczynamy!}
{204} {} {Nie œpieszmy siê z przestêpstwem, mo¿e uda mi siê negocjowaæ z tymi ludŸmi.}
{205} {} {Ale musi byæ jakiœ sposób na unikniêcie rozlewu krwi!}
{206} {} {Jesteœ zwyk³ym g³upcem. Jeœli nie chcesz uczestniczyæ w ataku, to po prostu siê odsuñ. A mo¿e spróbujesz niezauwa¿enie odci¹gn¹æ bramina od pasterzy?}
{1206} {} {Jesteœ zwyk³ym g³upcem. Jeœli nie chcesz uczestniczyæ w ataku, to po prostu siê odsuñ. A mo¿e spróbujesz niezauwa¿enie odci¹gn¹æ bramina od pasterzy?}
{207} {} {Ok, zróbmy to. Naprzód!}
{208} {} {Nie pozwolê ci tego zrobiæ.}
{209} {} {Naprawdê? Co zamierzasz zrobiæ?}
{210} {} {Mogê walczyæ, w przeciwieñstwie do tych pasterzy. ChodŸmy!}
{211} {} {Pozwólcie mi tylko porozmawiaæ z pasterzami. Znajdê z nimi wspólny jêzyk.}
{212} {} {Po¿a³ujesz. (pluje do twoich stóp) No dalej.}
{213} {} {Zmieni³em zdanie. Umrzesz tu i teraz!}
{1213} {} {Zmieni³am zdanie. Umrzesz tu i teraz!}
{214} {} {Tak, wynoœ siê st¹d.}
{215} {} {Jakoœ rozwi¹¿ê twój problem z jedzeniem.}
{216} {} {Twoje s³owo nic dla nas nie znaczy.}
{217} {} {Wiêc nie zosta³o nic oprócz ataku na pasterzy. Jestem z tob¹.}
{218} {} {Czekaj, daj mi kilka minut. Mo¿e jednak siê zgodzê.}
{219} {} {Tak? Za³atwisz nam karawany z kupcami albo jedzeniem? Hmm, ale niby mo¿na ci ufaæ. Ale mo¿emy tego potem ¿a³owaæ... No dobra.}
{220} {} {Prawid³owe rozwi¹zanie.}
{221} {} {Swietny pomys³. Spróbujê przyprowadziæ do ciebie tego bramina.}
{222} {} {Rozwi¹¿ê twój problem z jedzeniem. Dajê s³owo.}

{250} {} {Nie œpiesz siê, pozwól mi negocjowaæ z pasterzami. Byæ mo¿e uda mi siê ich przekonaæ, by pokojowo oddali bramina.}
{251} {} {Ha! Ci pasterze nie tylko pas¹ stada, ale tak¿e ubóstwiaj¹ te swoje braminy. Dlatego przekonanie ich, by zrezygnowali z bramina, jest jak przekonanie ich, by odciêli sobie rêkê.}
{252} {} {I tak spróbujê.}
{253} {} {Wiêc nie mamy innego wyboru. Ch³opaki, otoczyæ ich ze wszystkich stron!}
{254} {} {Czy naprawdê zamierzasz zaatakowaæ pokojowych pasterzy?}
{255} {} {Oto wasz bramin. Zabierzcie go, zanim pasterze siê zorientuj¹.}
{256} {} {Bramin jest nasz. Dzikusy nie bêd¹ ryzykowaæ swojego ¿ycia i szukaæ go w mieœcie.}
{257} {} {To wielkie szczêœcie! Potrafisz wyobraziæ sobie, jak¹ ucztê zrobimy z tego cia³a? Dziêkujê Ci.}
{258} {} {Do zobaczenia w Garage City.}
{259} {} {Bramin jest prawie w naszych rêkach. Poczekaj, a¿ przyprowadzê go jeszcze bli¿ej...}