{100} {} {Widzisz pasterza.}
{101} {} {Widzisz pasterza w znoszonych pustynnych ubraniach.}

{111} {} {Dobra, obcy, weŸ bramina. I niech nasze œcie¿ki siê rozejd¹.}
{1111} {} {Dobra, obca, weŸ bramina. I niech nasze œcie¿ki siê rozejd¹.}
{112} {} {Mam nadziejê, ¿e nasze œcie¿ki nigdy wiêcej siê nie zbiegn¹.}

{200} {} {Hej obcy, nie zbli¿aj siê zbytnio do bramina. Czego chcesz od naszego spokojnego obozu?}
{1200} {} {Hej kobieto, nie zbli¿aj siê zbytnio do bramina. Czego chcesz od naszego spokojnego obozu?}
{201} {} {Potrzebujê twojego bramina... Nie, ca³e Garage City potrzebuje twojego bramina.}
{202} {} {Nie dzielimy swiêtych zwierz¹t z ¿adnym mot³ochem. Zostaw nas w spokoju.}
{203} {} {Ok, odchodzê.}
{204} {} {My jesteœmy w gorszej sytuacji. No dalej!}

{220} {} {Jak oswoi³eœ to zwierzê?}
{221} {} {Narodzi³ siê wœród ludzi. Z innego bramina, który równie¿ ¿y³ wœród ludzi.}
{222} {} {Wiêc jesteœ z San Brahmin?}
{223} {} {Klan Pó³nocnego Rogu. Nasi ludzie nie lubi¹ ha³aœliwego miasta, San Brahmin staramy siê odwiedzaæ tylko w interesach.}
{224} {} {Rozumiem. Có¿, nie bêdê ci przeszkadzaæ.}
{225} {} {Po raz pierwszy s³yszê, ¿eby komuœ uda³o siê oswoiæ te zwierzêta.}
{226} {} {Od pokoleñ ukrywaliœmy nasze sekrety przed osobami postronnymi. Jeœli znajdziesz siê w naszym mieœcie, które ludzie z zewn¹trz nazywaj¹ San Brahmin, zobaczysz wszystko na w³asne oczy.}
{227} {} {Rozumiem. Có¿, nie bêdê ci przeszkadzaæ.}

{230} {} {Patrz, stoj¹ tam jacyœ padlino¿ercy. Jeœli nie dasz im tego bramina, wezm¹ go si³¹.}
{231} {} {GroŸby to powszechna broñ w przypadku bladych twarzy. Powiedz im, ¿e bêdziemy siê broniæ. Nie mog¹ pokonaæ tych, którym patronuje Duch Pustkowia.}
{232} {} {Zostaw bramina, jeœli cenisz swoje ¿ycie.}
{233} {} {Nie damy siê zastraszyæ. Powiedzia³em ju¿ wszystko co mia³em do powiedzenia.}
{234} {} {Cholerne blade twarze! Odejdziemy. Ale niech miêso tego œwiêtego zwierzêcia stanie siê dla was trucizn¹. Ap-r!}
{235} {} {Rozs¹dna decyzja.}
{236} {} {Zaufaj mi, próbujê ocaliæ twoj¹ skórê. Pochodzê z Villi, jesteœmy przyjació³mi plemion San Brahmin.}
{237} {} {S³ysza³em o was. Jeœli mówisz, ¿e zostaniemy zabici, nale¿y w to uwierzyæ. Powiedz tym dzikusom, ¿eby nas nie dotykali.}
{238} {} {Nie bêdziecie w stanie oprzeæ siê ich broni. Oddaj bramina, albo zginiesz.}
{239} {} {Próbujê unikn¹æ rozlewu krwi. }

{240} {} {Mo¿e mogê odkupiæ od was tego bramina?}
{241} {} {(wymieniaj¹c spojrzenia) Co mo¿esz nam zaoferowaæ w zamian?}
{242} {} {Zobaczmy...}
{243} {} {Szczerze, nie mam nic. Przepraszam, ¿e przeszkadzam.}
{244} {} {Oferujê ci wid³y w brzuchu. Giñ, g³upi kretynie!}
{245} {} {Pasterze nie przeszkadzaj¹ ju¿ w twoich planach.}
{246} {} {Pora siê rozstaæ, obcy.}
{1246} {} {Pora siê rozstaæ, nieznajoma.}
{247} {} {[wyjdŸ]}