{100} {} {Widzisz Treyvona.}
{101} {} {Widzisz opalonego mê¿czyznê w brudnych ubraniach.}
{110} {} {WyprowadŸ kogoœ innego.}

# Plywajace repliki podczas demontazu
{111} {} {Powiedz, co zamierzasz.}
{112} {} {Czy naprawdê myœla³eœ, ze mo¿esz uciec?}
{113} {} {Cholerne szczury, nigdy ciê nie lubi³em!}
{114} {} {Co do diab³a to wszystko ma znaczyæ?}
{115} {} {Trzymaj ich mocno, bo uciekn¹.}
{116} {} {Siedzisz teraz w tym po uszy.}
{117} {} {Co powiesz na swoj¹ obronê?}
{118} {} {Nie ujdzie ci to na sucho.}
{119} {} {To by³ twój ostatni b³¹d.}

# Dialog podczas potyczki
{200} {} {(widzisz przed sob¹ napiêt¹ scenê - t³um padline¿erców otoczy³ kilku innych padline¿erców i zamierza ich pobiæ; ale twoja obecnoœæ wszystko przerywa) Kim jesteœ?}
{201} {} {Pan Kogan mnie przys³a³. Co siê tu wyprawia do diab³a ?}
{202} {} {Ju¿ wyjaœniam, zamierzamy zetrzeæ twarze ludzi Lucasa papierem œciernym. Te œmieci pozwalaj¹ sobie na zbyt wiele, kradn¹ nasz sprzêt i poluj¹ na naszych terenach.}
{203} {} {Czy nie jesteœcie wszyscy czasem padlino¿ercami?}
{204} {} {Wszyscy jesteœmy w kartelu pana Kogana. Ale ka¿dy klan ma swoj¹ w³asn¹ sekcjê w kopalni. Jak dot¹d siê dogadywaliœmy, dopóki ludzie Lucasa nie przekroczyli granicy.}
{205} {} {Co dok³adnie zrobili?}
{206} {} {Mówiê ci - ludzie Lucasa ukradli dekoder, który powierzy³ nam pan Kogan. A potem uciekli z miasta. Uda³o nam siê zatrzymaæ tych dwóch. A teraz zostan¹ surowo ukarani.}

{207} {} {Wiem ju¿ wystarczaj¹co. Mo¿esz kontynuowaæ to, co tam robi³eœ.}
{208} {} {Teraz idŸ do szefa i opowiedz mu tê historiê. Nie zostawimy tego tak ³atwo... Stój suko! Dok¹d?! (wykorzystuj¹c moment, zatrzymani próbowali uciec)}
{209} {} {Uch...}

{210} {} {Jesteœ pewny, ze lincz jest tego wart? Jesteœcie jednym miastem i jedn¹ firm¹.}
{211} {} {Tak, wszyscy chwycili za broñ. Nasze miasto umiera. Jedynym sposobem na ocalenie pozosta³ych jest fabryka na pó³nocy. Ale Lucas nie podzieli siê swoimi odkryciami. Po prostu weŸmie to wszystko dla siebie. Musimy coœ z tym zrobiæ!}
{212} {} {Masz racjê, rób co musisz.}

{213} {} {Puœæ ich. Po co przelewaæ krew zwyk³ych ludzi?}
{214} {} {Nie mogê pozwoliæ Lucasowi dostaæ siê do moich kopalni.}
{215} {} {Chcia³bym móc ciê jakoœ przekonaæ.}
{216} {} {Masz racjê, rób co musisz.}

{217} {} {Sugerujesz, ¿eby pozwoliæ im odejœæ, ¿eby Lucas mia³ wiêcej ludzi? To g³upie!}
{218} {} {Masz racjê, to g³upie. Rób co chcesz.}
{219} {} {Uspokój siê, staruszku. Bêdziesz mia³ przez to dwa ¿ycia na swoim sumieniu, ale to nie zmieni sytuacji z Lucasem.}
{220} {} {Mo¿e. Mo¿e móg³byœ coœ zrobiæ, aby przywróciæ nam fabrykê? Nie s¹dzê. (pauza) Puœæ ich.}
{221} {} {W³aœciwa decyzja. W miêdzyczasie powiem o tym panu Koganowi.}
{222} {} {Dobra decyzja.}

{230} {} {Kim ty jesteœ?}
{231} {} {Pan Kogan mnie przys³a³. Co siê tu dzieje?}
{232} {} {Lucas okaza³ siê wrednym szczurem. Ukrad³ dekoder, który da³ nam pan Kogan i poszed³ do fabryki. Ale ta fabryka to nasze terytorium!}
{233} {} {Rozumiem. Powiem o tym szefowi.}

# Normalny dialog
{300} {} {Hej, czego chcesz?}
{301} {} {Do widzenia.}
{302} {} {Cholera, jak Kogan móg³ nas wymieniæ na Lucasa?! Pracujemy z nim od tylu lat, a on nas po prostu sprzeda³! Nie mam zamiaru tego tolerowaæ. Któregoœ dnia wyrzucimy te nieuczciwe œmieci z terenu naszej fabryki!}
{303} {} {Swietny pomys³. Jestem z tob¹.}
{304} {} {Lucas tu teraz rz¹dzi. Musisz siê z tym pogodziæ.}
{305} {} {Cholera! Moi ludzie i ja pracujemy z Koganem od wielu lat. Chocia¿ nic nam nie obiecywa³, byliœmy pewni jego nieugiêtoœci i si³y. A teraz przyszed³ Lucas i po prostu odebra³ mu firmê! Hmm, nadchodz¹ ciê¿kie czasy.}