{100} {} {Widzisz kupca.}
{101} {} {Widzisz kupca. Wygl¹da na to, ¿e by³ w drodze od kilku dni.}

{110} {} {Gdzie jest twój szef? Niech siê poœpieszy. Nie zamierzam zatrzymywaæ siê w tej dziurze.}
{111} {} {Kupiec nie chce z tob¹ rozmawiaæ.}
{112} {} {Swietna okazja jak na tak zapomnian¹ dziurê.}
{113} {} {Taka dziura musia³a byæ rozczarowaniem. Bêdê musia³ odejœæ z niczym.}
{114} {} {Bêdê przeklêty! Co robi Wyznawca Ognia w takiej dziurze?}
{115} {} {Hmm. Nigdy nie myœla³em, ¿e zobaczê zbrojê wspomagan¹ w takiej dziurze. Ciekawe.}