{100} {} {Widzisz chorego padlino¿ercê.}
{101} {} {Widzisz jednego z padline¿erców Trayvona. Cierpi na skutki jakiejœ choroby.}
{102} {} {Pomyœlnie wyleczono chorobê padlino¿ercy.}
{103} {} {Nie jesteœ w stanie rozpoznaæ choroby, a tym bardziej wyleczyæ cz³owieka bez leków.}
{104} {} {Ten padlino¿erca cierpi z powodu choroby popromiennej. Twoje umiejêtnoœci nie pozwalaj¹ ci go wyleczyæ bez specjalnych lekarstw.}

{110} {} {* Khe-khe *}
{111} {} {Przepraszam, nie czujê siê za dobrze.}
{112} {} {Zachorowa³em po kolejnej wycieczce do ruin.}
{113} {} {* hack * ...Jestem chory, jak widzisz.}
{114} {} {...To nie jest zaraŸliwe, nie martw siê.}

{115} {} {Dziêki za pomoc, ju¿ ¿egna³em siê z ¿yciem.}
{116} {} {Gdyby nie ty, cierpia³bym a¿ do koñca.}
{117} {} {Nie wiem jak mam Ci dziêkowaæ.}
{118} {} {Zachorowa³em po kolejnej wycieczce do ruin.}
{119} {} {Szukasz swoich ludzi? Zabrano ich na wschód, to wszystko, co wiem.}

{120} {} {Och...}
{121} {} {* Khe-khe *}
{122} {} {* Hack *}
{123} {} {Fuj...}
{124} {} {* Jêk *}
{125} {} {Hrr...}