{100} {} {Widzisz osadnika.}
{101} {} {Widzisz jednego z nielicznych mieszkañców Garage City.}

{110} {} {Wiêc jesteœ tu mimochodem? Dobra.}
{111} {} {Lepiej odejdŸ. Nie ma tu miejsca dla nowych osadników.}
{112} {} {Nowy w du¿ym mieœcie?}
{113} {} {Garage City to œwietne miejsce, pokochasz je.}
{114} {} {Zamierzasz tu zostaæ?}
{115} {} {Mamy tu w³asne zasady.}
{116} {} {Nie rozumiem, dlaczego ludzie wci¹¿ przyje¿dzaj¹ do tego zapomnianego miasta.}

{120} {} {Czeœæ! Jak siê masz?}
{121} {} {Wow, co za ludzie. Jak d³ugo tu jesteœ?}
{122} {} {Jak id¹ ¿niwa, amigo?}
{123} {} {Witaj amigo.}
{124} {} {Przepraszam, nie poznaliœmy ciê zbyt dobrze.}
{125} {} {Nie wiedzieliœmy, ¿e ludzie z Villi s¹ tak przyjaŸni.}
{126} {} {Potrzebujesz pomocy?}

{130} {} {Trzymaj siê z dala ode mnie.}
{131} {} {IdŸ pokopaæ w swoich do³kach, nie przeszkadzaj mi.}
{132} {} {Powiedz swojemu przywódcy, ¿e jest chciwym i aroganckim draniem.}
{133} {} {Twoja Villa nigdy nie by³a dobr¹ osad¹.}
{134} {} {Czy wszyscy wieœniacy w twojej Villi s¹ tak samo przebiegli i chciwi?}
{135} {} {Teraz jest jasne, dlaczego Villa nalicza³a tak wysokie ceny.}
{136} {} {Powiem ci tak, jak jest. Cieszy³em siê, widz¹c twoich krewnych na kolanach.}
{137} {} {Kiedy my byliœmy g³odni, wy podnieœliœcie ceny.}
{138} {} {Odpierdol siê, brudny wieœniaku.}
{139} {} {Villa dosta³a to, na co zas³u¿y³a.}