{100} {} {Widzisz Franka.}
{101} {} {Widzisz jednego z nielicznych mieszkañców Garage City.}
{102} {} {Ups, muszê pilnie iœæ do toalety...}
{103} {} {Frank nie mo¿e teraz rozmawiaæ.}
{104} {} {Boo-uh-uh...}
{105} {} {Hrrrr...}
{106} {} {Po dobrym drinku Frank mdleje na swoim zniszczonym krzeœle.}
{107} {} {Oooh...}
{108} {} {Coœ mi nie pasuje...}

# Przed misja
{200} {} {Hej hej, to jest mój dom. Czego tu szukasz?}
{201} {} {Jestem z³odziejem.}
{202} {} {O tak. Doskonale. Wspaniale. Magicznie. Wynoœ siê st¹d, g³upcze!}
{1202} {} {O tak. Doskonale. Wspaniale. Magicznie. Wynoœ siê st¹d, bezczelna!}
{203} {} {Do widzenia.}
{204} {} {Hej, to tylko ¿art. Jestem twoim nowym s¹siadem.}
{1204} {} {Hej, to tylko ¿art. Jestem twoj¹ now¹ s¹siadk¹.}
{205} {} {Hej, kogo ty chcesz oszukaæ? Od dawna nikt nie przyje¿dza do naszego miasta z w³asnej woli. Tu nie ma pracy! Ale jeœli naprawdê chcesz osiedliæ siê w okolicy, nie wpadaj tak do mnie.}
{206} {} {Ok. Skoro tak mówisz.}
{207} {} {Chcê poznaæ nowych s¹siadów.}
{208} {} {Sk¹d tyle nieufnoœci do s¹siadów?}
{209} {} {}
{210} {} {Litoœci - trzymaj siê z daleka ode mnie.}
{211} {} {Sk¹d tyle nieufnoœci wobec s¹siadów?}
{212} {} {Ok. Skoro tak mówisz.}
{213} {} {Nie mo¿esz ufaæ nikomu w tym mieœcie. Nawet swoim s¹siadom, którzy tylko patrz¹ na twoje dobro. Gdy tylko wyjdziesz za drzwi, ktoœ od razu próbuje otworzyæ zamek.}
{214} {} {Czy coœ ci zosta³o skradzione?}
{215} {} {Ka¿demu od czasu do czasu coœ ginie. Wszystko zaczê³o siê, gdy tylko biznes w kopalni zacz¹³ podupadaæ, a wielu pracowników zosta³o bez pracy.}
{216} {} {Co dok³adnie zosta³o ci skradzione?}
{217} {} {Spawarka. To bardzo cenny przedmiot. W ca³ym mieœcie jest tylko kilka sprawnych takich urz¹dzeñ. Jak dot¹d zapewnia³a mi doskona³e dochody. I co mam teraz bez niej zrobiæ?}
{218} {} {Rozumiem. Mogê poszukaæ tego zagubionego sprzêtu.}
{219} {} {Naprawdê? A mo¿e to jakiœ przebieg³y plan - najpierw ukraœæ, a potem odsprzedaæ? Chocia¿, co ja mówiê? Ostatnio ciê tu nie by³o, a sprzêt znikn¹³ du¿o wczeœniej. Dobra, jeœli znajdziesz moje rzeczy, spróbujê je odkupiæ.}
{220} {} {Ok, tak zrobimy.}
{221} {} {Nie martw siê o to. Z³odziej zostanie ukarany. Poniewa¿ ja, jako Stra¿nik, przysiêga³em strzec prawa na tych ziemiach.}
{1221} {} {Nie martw siê o to. Z³odziej zostanie ukarany. Poniewa¿ ja, jako Stra¿nik, przysiêga³am strzec prawa na tych ziemiach.}
{222} {} {Hej, hej, jesteœ Stra¿nikiem? Dlaczego, do diab³a, mówisz mi o tym dopiero teraz? Nie potrzebujê twojej pomocy, jestem wolnym rezydentem i nie zamierzam klêkaæ przed tob¹!}
{223} {} {To ju¿ nie twoja sprawa. Poradzê sobie ze z³odziejem, czy ci siê to podoba, czy nie. Czekaj na wyniki.}

# Po otrzymaniu zadania
{230} {} {Znowu? Czego potrzebujesz?}
{231} {} {Czy to o tobie ostatnio tyle siê mówi? Có¿ zawdziêczam twojej wizycie?}
{232} {} {Witaj s¹siedzie. Co nowego?}
{233} {} {Tak, chcia³em siê przywitaæ przed wyjœciem.}

{240} {} {Co robisz, Frank?}
{241} {} {Robiê pos¹gi, kochany. Dobrze siê sprzedaj¹ na ca³ym pustkowiu.}
{242} {} {Czy ten biznes jest wystarczaj¹co dochodowy?}
{243} {} {Naprawdê?}
{244} {} {Co jeszcze mo¿na robiæ w tej dziurze? Kiedyœ pracowa³em w kartelu, jak reszta. Dostawa³em i naprawia³em stare rzeczy. Ale to nieaktualne, w mieœcie prawie nie ma ju¿ pracy, ledwo mogê zwi¹zaæ koniec z koñcem.}
{245} {} {Przepraszam. Czy mogê zadaæ inne pytanie?}
{246} {} {Smutna historia. Bywaj.}

{250} {} {O tym skradzionym sprzêcie.}
{251} {} {Jakieœ nowoœci?}
{252} {} {Nie, ale wci¹¿ mam nadziejê, ¿e go znajdê.}
{253} {} {Masz pomys³, kto móg³by to zrobiæ?}
{254} {} {Gdybym mia³ pomys³, znalaz³bym i odzyska³bym swoj¹ zgubê dawno temu. Oczywiœcie, ¿e z³odziej nie bêdzie siê chwali³ tym co ukrad³ przez bardzo d³ugi czas. Tutaj musisz dzia³aæ sprytnie, aby z³odziej siê zdradzi³.}
{255} {} {Rozumiem.}
{256} {} {Oto twój sprzêt.}
{257} {} {To naprawdê on. Myœla³em, ¿e go straci³em na zawsze. Kto by³ z³odziejem?}
{258} {} {Le¿a³ na z³omowisku. Nie wiem, kto to tam zostawi³.}
{259} {} {Hmm, albo masz niesamowity instynkt, albo po prostu kryjesz z³odzieja. W ka¿dym razie dziêki. Oto twoje }
{260} {} { kapsli.}
{261} {} {Proszê.}
{262} {} {To by³ Todd, ten z przyczepy.}
{263} {} {Ha! Todd uwa¿a, ¿e jest tu najm¹drzejszy. Ale prêdzej czy póŸniej sprawiedliwoœæ znajdzie ka¿dego i wszêdzie. Teraz daj mi mój sprzêt. Oto twoje }
{264} {} { kapsli. Ale nikomu ani s³owa.}
{265} {} {Zaden problem.}