{100} {} {Widzisz osadnika.}
{101} {} {Widzisz jednego z nielicznych mieszkañców Garage City.}

{110} {} {Trzymaj siê z dala ode mnie.}
{111} {} {Czego chcesz?}
{112} {} {Czeœæ. Jak siê masz?}

{200} {} {Czy zawsze w³amujesz siê do cudzych domów bez zaproszenia? Ok, to nie ma znaczenia. I tak nic na to nie poradzê.}
{201} {} {Chcê tylko zapytaæ o miasto.}
{202} {} {Niczego od ciebie nie potrzebujê.}
{210} {} {Znowu? Doskonale. O co chodzi tym razem?}
{211} {} {Chcê zapytaæ o to miasto.}
{212} {} {Nic.}
{213} {} {Dlaczego mia³bym z tob¹ rozmawiaæ? Nie widzê w tym ¿adnego sensu. Nie op³aca mi siê.}
{214} {} {Pomyœlê o tym, jak mogê siê odwdziêczyæ.}
{215} {} {Naprawdê zawsze prosisz osoby z zewn¹trz o zap³atê za odpowiedzi? Chyba nie zostanê tutaj po tym zbyt d³ugo.}

{220} {} {Có¿, Garage City to miasto œmieciarzy. Tutaj wszyscy ¿yj¹ z kopalni prowadzonej przez kartel pana Kogana.}
{221} {} {Dziêki, to by³a ostateczna odpowiedŸ.}
{222} {} {Smieciarze?}
{223} {} {To pracownicy, którzy znajduj¹ stare rzeczy i zabieraj¹ je do warsztatu w celu naprawy.}
{224} {} {Kim jest ten Kogan?}
{225} {} {Kieruje kartelem œmieciarzy i praktycznie ca³ym miastem. W przypadku takiej osoby musisz z szacunkiem i ostro¿noœci¹ dobieraæ s³owa.}
{226} {} {Co to jest kopalnia?}
{227} {} {To miejsce, w którym mo¿na znaleŸæ stare rzeczy. IdŸ do gara¿u po drugiej stronie ulicy i porozmawiaj z Pete'em, jeœli jesteœ zainteresowany.}
{228} {} {Jak tam twoje ¿ycie?}
{229} {} {Gorzej byæ nie mog³o. Kartel zarabia³ kiedyœ œwietne pieni¹dze, ale nie teraz. A nawet jeœli masz jakieœ kapsle to nie ma na co ich tu wydaæ, poniewa¿ handel z innymi miastami prawie siê zatrzyma³. Jeszcze trochê, a miasto upadnie, chyba ze ktoœ coœ wymyœli.}
{230} {} {Gorzej byæ nie mog³o. Kartel zarabia³ kiedyœ œwietne pieni¹dze, ale nie teraz. Jednak po renowacji fabryki odnotowano pewien postêp. Wydaje mi siê, ¿e miasto wci¹¿ ma szanse na œwietlan¹ przysz³oœæ.}
{231} {} {Kiedyœ kierowa³ kartelem œmieciarzy. Ale to ju¿ historia.}