{100} {} {Widzisz Todda.}
{101} {} {Widzisz jednego z nielicznych mieszkañców Garage City.}
{102} {} {Czeœæ. Dziêki za pomoc przy kojotach.}

{200} {} {Hej, ty. Nie pamiêtam, ¿ebym ciê widzia³ w naszym mieœcie. Sk¹d pochodzisz?}
{201} {} {Tylko przechodzê. A co?}
{202} {} {Tak. Obcy stali siê w naszym mieœcie rzadkoœci¹... A tak, nazywam siê Todd.}
{203} {} {Mi³o ciê poznaæ.}
{204} {} {Jeœli stracisz tu zaufanie, pamiêtaj, ¿eby na mnie nie liczyæ.}

{210} {} {Czeœæ. O co chodzi tym razem?}
{211} {} {Czeœæ. Jak mogê ci pomóc?}
{212} {} {Nic. Bywaj.}

{220} {} {Co tutaj robisz Todd?}
{221} {} {Có¿, jestem raczej specjalist¹ od zbierania i uszlachetniania ¿elaza. Przez lata doskonali³em swoje rzemios³o.}
{222} {} {To musi byæ dochodowy biznes?}
{223} {} {Rozumiem.}
{224} {} {Niezupe³nie. Kopalnia siê kurczy, jest tu ma³o pracy. A w pobli¿u mojej przyczepy pojawi³y siê bestie.}
{225} {} {Bestie?}
{226} {} {Krwawe kojoty. Nie wiem, co tam zwêszy³y, ale jest ich ca³e stado. Bojê siê podejœæ zbyt blisko. Wszystkie moje rzeczy zosta³y w domu. Czy mo¿esz mi pomóc pozbyæ siê tych kojotów? Zap³acê po piêæ kapsli za ka¿dego, jeœli dotrê do siebie.}
{227} {} {Ok, ok.}
{228} {} {Nie jestem myœliwym, ale pomyœlê o propozycji.}
{229} {} {Niezupe³nie. Kopalnia siê kurczy, jest tu ma³o pracy. Poza tym to brudna i trudna sprawa.}
{230} {} {Rozumiem.}
{231} {} {Pozbêdê siê kojotów. Ale najpierw odpowiedz na pytania.}
{232} {} {Gdzie jest twoja przyczepa?}
{233} {} {IdŸ do fabryki Watts Electronics. Nastêpnie skrêæ w lewo i idŸ wzd³u¿ drogi.}
{234} {} {Rozumiem. Inne pytanie.}
{235} {} {Pójdê tam natychmiast.}
{236} {} {Kojoty to przesz³oœæ.}
{237} {} {Och, to œwietnie. Wygl¹da na to, ¿e czas ci zap³aciæ, prawda? W przeciwnym razie nie odczepisz siê ode mnie...}
{238} {} {Niezwykle czyste kapsle. Sk¹d je masz?}
{239} {} {Dziêki.}
{240} {} {S¹ po prostu w dobrym stanie. Co siê czepiasz? WeŸ je po prostu i wydaj na coœ.}
{241} {} {W takim razie nie mam pytañ.}
{242} {} {Myœlê, ¿e zrobi³eœ je samemu ze z³omu, który zebra³eœ w pobli¿u fabryki. Co na to powiesz?}
{243} {} {Cicho! Nie mów nikomu. Czy serio obchodzi Ciê, gdzie i jak powsta³y te kapsle? Przedwojenne kapsle s¹ ju¿ porz¹dnie skorodowane, a te przynajmniej nie rozpadaj¹ siê w rêkach. WeŸ je i b¹dŸ cicho. I tak nikt ci nie uwierzy.}
{244} {} {Nie oceniam ciê. Tylko uwa¿aj nastêpnym razem. Szczêœcia.}
{245} {} {Cisza jest droga. Za 100 kapsli zamknê oczy na tê sprawê.}
{246} {} {Cholera, czy masz pojêcie, ile pracy wymaga zrobienie jednego kapsla? Okay, niech bêdzie. Ale nikomu nic nie mów!}
{247} {} {Cokolwiek powiesz. Szczêœcia.}

{250} {} {Opowiedz mi o Garage City.}
{251} {} {To miasto padline¿erców. W pobli¿u znajduj¹ siê ruiny starego miasta, z których wyci¹gamy przydatne rzeczy, naprawiamy je i sprzedajemy na po³udnie.}
{252} {} {Brzmi dobrze.}
{253} {} {Ale kopalnia jest prawie ca³kowicie wyczerpana. Wygl¹da na to, ¿e wkrótce trzeba bêdzie zebraæ swoje rzeczy i szukaæ nowych ruin, jeœli miasto nagle nie odkryje dodatkowego Ÿród³a dochodu.}
{254} {} {Co otrzymujecie w zamian za swoj¹ pracê? Kolby kukurydzy?}
{255} {} {Kapsle, redneck! Kapsle! U¿ywamy ich tak, jak u¿ywali pieniêdzy w staro¿ytnoœci. Hmm. Pamiêtaj - bez kapsli w du¿ych miastach nie masz czego szukaæ.}
{256} {} {Du¿o wiesz. Czy mogê zadaæ jeszcze kilka pytañ?}
{257} {} {Dziêki za radê. Muszê iœæ.}
{258} {} {Rozumiem. Czy mogê zadaæ jeszcze jedno pytanie?}