{100} {} {Widzisz starca.}
{101} {} {Widzisz brudnego starca z krzaczast¹ brod¹.}
{102} {} {Widzisz Starego Carmelo.}

# Znajomosc
{200} {} {Czekaj, nie zbli¿aj siê! Wszyscy tutaj wiedz¹, ¿e lepiej z tob¹ nie zadzieraæ.}
{201} {} {I maj¹ racje. Wiêc zamknij usta, cz³owieku.}
{202} {} {Dobra, dobra, ale wiedz, ¿e nadal mogê siê broniæ.}
{203} {} {Zachowaj tê nieufnoœæ dla siebie. Interesuje mnie coœ innego.}
{204} {} {Nie skrzywdzê ciê. Nie wierz we wszystkie plotki.}
{205} {} {Mam nadziejê, ¿e mówisz prawdê. Pamiêtaj jednak, ¿e nadal mogê siê broniæ.}
{206} {} {Twoje groŸby s¹ nieuzasadnione. Porozmawiajmy.}
{207} {} {Och, to nasza nowa celebrytka. Co masz do zrobienia?}
{208} {} {Co mo¿e mi zaoferowaæ taki stary cz³owiek jak ty?}
{209} {} {No có¿, chyba nic. Dlaczego mia³bym Ci coœ oferowaæ?}
{210} {} {W takim razie porozmawiajmy.}
{211} {} {Wiêc nie jestem tob¹ zainteresowany. Do widzenia.}
{212} {} {Patrzê na ciebie i myœlê, ¿e powinniœmy siê poznaæ.}
{213} {} {Zwykle ludzie tylko siê narzucaj¹. Ale jakoœ ci wierzê.}
{214} {} {Po prostu œwietnie. Porozmawiamy?}
{215} {} {Masz racjê, nie powinienem wymuszaæ rozmowy na kimœ takim jak ty. Bywaj.}
{216} {} {Czego chcesz? Jeœli iguany, to nic z tego. Nie mam nic do jedzenia.}
{217} {} {No dalej, nie zamierzam wyrywaæ tego z twoich ust.}
{218} {} {Dobrze. A potem zostaniesz bez rêki. Co chcesz?}
{219} {} {Po prostu porozmawiaæ.}
{220} {} {Patrz¹c na ciebie, rozumiem, ¿e nic.}
{221} {} {WeŸ iguanê tutaj! Szybko!}
{222} {} {Tak! WeŸ to! Nie ma potrzeby machania rêkoma. Sk¹d pochodzisz, z jakiej pustyni...}
{223} {} {Jeszcze z tob¹ nie skoñczy³em. Potrzebujê odpowiedzi na pytania.}
{1223} {} {Jeszcze z tob¹ nie skoñczy³am. Potrzebujê odpowiedzi na pytania.}
{224} {} {Na razie wystarczy. Ale wrócê.}
{225} {} {Rêce precz! To moja zdobycz! Jeœli potrzebujesz jeœæ, idŸ na pustyniê i z³ap sobie coœ.}
{226} {} {Nie z³oœæ siê, staruszku. To tylko ¿art.}
{227} {} {Bywaj. Nie chcê ju¿ rozmawiaæ z tak chciw¹ osob¹.}
{228} {} {Nie mam z³ych zamiarów. Proszê, weŸ kapsla jako dowód moich dobrych zamiarów.}
{229} {} {Czy to ¿art?}

# Powtarzajacy siê dialog
{230} {} {Naprawdê?}
{231} {} {Znowu Ty?}
{232} {} {}
{233} {} {Do widzenia, staruszku.}
{234} {} {Gdyby tylko w tym mieœcie by³o coœ do kupienia... Ale dziêki za kapsla.}

{239} {} {Có¿, nie ma potrzeby ci¹gniêcia iguany za ogon. Powiedz mi bez ogródek, czego chcesz?}
{240} {} {Kim jesteœ?}
{241} {} {Nazywam siê Carmelo. Mieszkam tu.}
{242} {} {Masz problemy z pamiêci¹? Nazywam siê Carmelo.}
{243} {} {W³aœciwie to chcê zapytaæ o coœ innego.}
{244} {} {Do widzenia, staruszku Carmelo.}
{245} {} {Co tutaj robisz?}
{246} {} {Lapiê jaszczurki i sprzedajê je reszcie mieszkañców. Z³apanie ich nie jest wcale takie ³atwe.}
{247} {} {Pracowa³eœ jako padlino¿erca?}
{248} {} {Tak. Mia³em œwietny nos do przydatnych rzeczy. W koñcu mo¿na wykorzystaæ nawet garœæ œmieci. (wzdycha) Ale kopalni ju¿ nie ma, teraz szukam jaszczurek zamiast starych rupieci.}
{249} {} {Rozumiem. W³aœciwie to chcê zapytaæ o coœ innego.}
{250} {} {Muszê iœæ, staruszku. Do zobaczenia.}
{251} {} {Czy pracowa³eœ jako padlino¿erca?}
{252} {} {Dlaczego jesteœ taki nieufny, staruszku Carmelo?}
{253} {} {Mieszkam tu tak d³ugo, jak ¿yjê, ty te¿ z czasem zaczniesz byæ nieufny.}
{254} {} {Czy zawsze jesteœ taki nieufny?}
{255} {} {Przypomnij mi, co tu robisz?}
{256} {} {Ty te¿ pracowa³eœ w kopalni?}
{257} {} {Rzeczywiœcie, rzadko mo¿na w tych czasach spotkaæ starca.}
{258} {} {Mówi¹, ¿e kiedyœ do¿ywali stu lat, ale teraz, nawet do mojego wieku, rzadko siê udaje. Prawdopodobnie uratowa³ mnie fakt, ¿e nie mia³em ¿adnych k³opotów.}
{259} {} {Swoj¹ drog¹, co tu robisz?}

{260} {} {Powa¿nie? Mam trochê œmieci w kieszeni. Popatrz...}
{261} {} {Có¿... (z zainteresowaniem patrzy na œmieci z kieszeni) Gdybym mia³ takie kieszenie, ju¿ dawno by³bym bogaty.}
{262} {} {Czy jest tu coœ przydatnego?}
{263} {} {Spójrz, jest tu przedwojenny rachunek, kilka kapsli i nabój ma³ego kalibru. Za to wszystko w najlepszym razie mo¿esz kupiæ iguanê. To lepsze ni¿ nic, prawda?}
{264} {} {Ugh, szczerze nie s¹dzi³em, ¿e te œmieci bêd¹ przydatne.}
{265} {} {Wiêc wci¹¿ mam przysz³oœæ przed sob¹. Poszukam inwestora.}

{266} {} {Hej staruszku, czy znasz kogoœ ze spawark¹?}
{267} {} {Na pewno jest jedna w Garage City. Frank równie¿ by³ w³aœcicielem takiej maszyny, ale nie wiem czy nadal jest. A tak, ostatnio czu³em zapach spawania z chaty Todda. Mo¿e tylko sobie to wyobrazi³em, ale zapytaj go na wszelki wypadek.}
{268} {} {Dziêki.}
{269} {} {Nie mo¿na tu wiele zdzia³aæ bez spawarki. Dlatego pan Kogan kiedyœ wykupi³ wiêkszoœæ spawarek. I tak nie by³o ich wiele.}

{270} {} {Powiedz mi, czy przeje¿dza³ têdy konwój niewolników?}
{271} {} {Tak, by³ tu. Ale odrazu poszed³em na pustkowia, aby nie spotkaæ siê z tak niebezpiecznymi ludŸmi.}
{272} {} {Czy wiesz, dok¹d zmierza ten konwój?}
{273} {} {Gdzieœ na wschód. Ale nigdy nie by³em w tamtych stronach.}
{274} {} {Dziêki. Ale wci¹¿ mam pytania.}
{275} {} {To wszystko, pójdê w tym kierunku. Czeœæ.}
{276} {} {Pytanie o konwój niewolników jest podejrzane.}

{280} {} {Opowiedz mi o tej kopalni.}
{281} {} {Co tu powiedzieæ? Wczeœniej nikt nie mieszka³ w tych stronach. Ale kiedy kartel otworzy³ swoj¹ dzia³alnoœæ, nap³ynê³y tu t³umy padlino¿erców.}
{282} {} {Nie mam dalszych pytañ na temat kopalni.}
{283} {} {Chyba powinienem iœæ.}
{284} {} {Co robi kartel?}
{285} {} {Kupuje znaleziska od padlino¿erców, a nastêpnie naprawia je i zabiera do innych miast na aukcje.}
{286} {} {Kim s¹ padlino¿ercy?}
{287} {} {Poszukiwacze, œmieciarze, padlino¿ercy, nazywajcie ich, jak chcecie. Zbieraj¹ w ruinach przydatne rzeczy i przynosz¹ je do pana Kogana w celu ich dalszego u¿ytku.}
{288} {} {Czy ta praca przyci¹ga ludzi?}
{289} {} {No pewnie! Wielu przyje¿dza tutaj, maj¹c nadziejê na zdobycie góry kapsli i udania siê do bardziej rozwiniêtych osad. Ale ostatnimi czasy czêœciej ten przystanek jest dla nich ostatnim.}
{290} {} {Brzmi to jak koniec miasta.}
{291} {} {Jeszcze nie. Ale niewiele brakuje. Zasoby w ruinach s¹ na wyczerpaniu, a ludzie nie maj¹ ju¿ tu nic do roboty. Dlatego miasto wymiera. I zniknie, jeœli ktoœ czegoœ nie wymyœli.}
{292} {} {Ten zrzut na pewno nie pomo¿e.}
{293} {} {Smutna historia. Zmienimy temat?}
{294} {} {Nie mo¿na nic z tym zrobiæ?}
{295} {} {Có¿, jeœli Garage City zdecyduje siê odbudowaæ star¹ fabrykê, mo¿e ona uratowaæ osadê i zapewniæ prace ludziom. Ale jakoœ nie wierzê, ¿e to siê uda.}
{296} {} {O co chodzi z t¹ fabryk¹?}
{297} {} {Jest szalony pomys³, aby odbudowaæ star¹ fabrykê. Takie przedsiêwziêcie wymaga jednak du¿o energii i wielu pracowników. A co wa¿niejsze - wiedzy, której obecnie nikt nie ma. Ludzie mog¹ mieæ tylko nadziejê na cud.}
{298} {} {Kogo obchodzi ta stara fabryka? W Villi obywamy siê bez niej, pracujemy w³asnymi rêkoma.}
{299} {} {Zaufaj mi, s¹ miejsca na po³udniu czekaj¹ce na te wszystkie przedwojenne cuda. Samymi rêkoma nie wszystko mo¿na zrobiæ.}

{300} {} {Jeœli nikt tu wczeœniej nie mieszka³, to sk¹d pochodz¹ te ruiny?}
{301} {} {Tak by³o przed nadejœciem kartelu. Nie przekrêcaj s³ów. Oczywiœcie przed wojn¹ istnia³o tu ca³e miasto zwane Kingman. Ale to by³o prawie sto lat temu.}
{302} {} {O czym ty mówisz? Co za wojna?}
{303} {} {Nic nie wiesz? To stara historia. Jest o niej wiele legend. Mówi siê, ¿e sto lat temu istnia³y du¿e kraje, które nie mog³y siê dogadaæ i podzieliæ resztkami „œmieci”. Tak jak teraz w naszym gara¿owym mieœcie.}
{304} {} {Wiêc zniszczyli siê nawzajem?}
{305} {} {Wymyœlili bardzo potê¿n¹ broñ, która zmiot³a ca³e miasta. Niewielu prze¿y³o. A my jesteœmy ich potomkami. Od tamtej pory zmieni³o siê ju¿ piêæ lub szeœæ pokoleñ.}
{306} {} {Nie ma przecie¿ a¿ tak potê¿nej broni. To wszystko to tylko historie wyssane z palca!}
{307} {} {Kiedyœ odwiedzisz miasta na po³udniu i zobaczysz wszystko na w³asne oczy. Chocia¿ co ja siê z tob¹ k³ócê - sam s³ysza³em te historie tylko z opowieœci.}
{308} {} {Dok³adnie. Zostaw swoje straszne historie dla dzieci.}
{309} {} {W tej smutnej historii musi byæ trochê prawdy.}
{310} {} {Masz strasznie d³ugi jêzyk. To mo¿e sprowadziæ na ciebie k³opoty.}

{320} {} {Opowiedz mi co to i jak ³apaæ iguany.}
{321} {} {Nie wiesz co to iguana? To zwyk³a jaszczurka pustynna. Lapanie ich wci¹¿ jest problemem. Ale nie ma na œwiecie lepszej przek¹ski. Chcesz kawa³ek? Nic za darmo.}
{322} {} {Doœæ o jaszczurach. Ju¿ dudni mi w ¿o³¹dku.}
{323} {} {Swietnie. W przeciwnym razie, jeœli wszyscy wokó³ zaczn¹ ³apaæ jaszczurki, nic mi nie zostanie.}
{324} {} {Czy nie ma tu innego jedzenia?}
{325} {} {A niby sk¹d? Wokó³ tylko pustynia i góry. Wczeœniej jedzenie przywozili kupcy z po³udnia. Ale ostatnio karawan jest mniej, a jedzenie staje siê coraz gorsze. Musimy ³apaæ jaszczurki, przynajmniej tak mo¿emy zdobyæ trochê jedzenia.}
{326} {} {A co z kojotami i skorpionami?}
{327} {} {S¹ z nimi za du¿e k³opoty. Kojot mo¿e odgryŸæ ci nogê. A skorpiony s¹ truj¹ce i zawieraj¹ mniej miêsa.}
{328} {} {Czy próbowa³eœ uprawiaæ roœliny?}
{329} {} {Gdzie, tutaj? Poza such¹ traw¹ i pleœni¹ w starych piwnicach nic tu nie roœnie. W pobli¿u znajduje siê farma hydroponiczna, ale wystarcza tylko dla kilku osób.}
{330} {} {Jak je ³apiesz?}
{331} {} {Nie oczekuj, ¿e ci to powiem. Nie potrzebujê tu ¿adnej konkurencji.}
{332} {} {Zastanawiam siê, sk¹d masz te pytania? To tak, jakbyœ wiedzia³, jak uprawiaæ kukurydzê na pustyni.}
{333} {} {No dalej, staruszku, wszyscy mnie tu znaj¹.}
{334} {} {Dobrzy ludzie powinni dzieliæ siê swoimi doœwiadczeniami.}
{335} {} {A jeœli zap³acê 25 kapsli?}
{336} {} {W¹tpiê, ¿e je masz. A jeœli nawet to na pewno kogoœ okrad³eœ lub zabra³eœ ze zw³ok. Nie potrzebujê ich.}
{337} {} {No có¿.}
{338} {} {Najpierw zdob¹dŸ zaufanie, potem porozmawiamy.}
{339} {} {Czy ty próbujesz mnie teraz upokorzyæ, poszarpany staruszku?}
{340} {} {Nie pozwoli³em ci byæ niegrzecznym.}
{341} {} {Oczywiœcie nie ma problemu.}
{342} {} {A jeœli zap³acê?}
{343} {} {Czym zap³acisz? Kapslami? W tym mieœcie nie ma nic do kupienia za nie.}
{344} {} {Pomyœl o tym, kapsle zyskuj¹ na wartoœci po tych wszystkich wydarzeniach w fabryce. Dam ci 50 kapsli.}
{345} {} {Nie zamierzasz ju¿ mnie oszukiwaæ, prawda?}
{346} {} {Hmm... Ok. Ale najpierw spe³nij jedn¹ z moich ma³ych próœb.}
{347} {} {Po prostu powiedz mi, jak ³apiesz jaszczurki.}
{348} {} {Nie, to nie zadzia³a.}
{349} {} {Tak?}
{350} {} {Wiêc czego chcesz?}
{351} {} {Grzyby. Te bardzo dziwne zielone grzyby, które rosn¹ w toksycznych ka³u¿ach w pobli¿u fabryki. Przynieœ mi ich trochê, a opowiem ci o jaszczurkach.}
{352} {} {Ok, spróbujê je zdobyæ.}
{353} {} {Dobrze. ChodŸ, ruszaj siê.}
{354} {} {Toksyczne grzyby? Po co?}
{355} {} {To moja sprawa. Po prostu je znajdŸ i mi przynieœ.}
{356} {} {Ok. Ale nie próbuj mnie oszukiwaæ, staruszku.}
{357} {} {Zaden problem.}
{358} {} {Jeœli zatrujesz siê przez nie, to to naprawdê nie bedzie mój problem. Do zobaczenia.}

{360} {} {Podziel siê swoj¹ m¹droœci¹, jak zdobyæ te cholerne grzyby?}
{361} {} {Toksyczne ka³u¿e s¹ gor¹ce i strasznie ¿r¹ce, potrzebne s¹ tu ciê¿kie buty. Gumowe buty powinny siê sprawdziæ, ale pewnie nie wytrzymaj¹ zbyt d³ugo.}
{362} {} {Rozumiem.}
{363} {} {Dlaczego sam nie wejdziesz do tego szamba?}
{364} {} {Poniewa¿ mam ciebie.}
{365} {} {Nie martw siê. Po prostu zbierz grzyby i uciekaj.}
{366} {} {Czy to wszystko? Niewiele. Przynieœ mi wiêcej.}
{367} {} {Zaczyna mnie to denerwowaæ.}
{368} {} {Ok, nie ma problemu.}

{370} {} {Oto twoje grzyby. Mam nadziejê, ¿e wiesz, co robisz.}
{371} {} {Ughh... Czujê zapach tych grzybów na milê.}
{372} {} {Gdzie one s¹? By³y tu...}
{373} {} {O tak, to wystarczy na d³ugi czas.}
{374} {} {Jak wiêc ³apiesz te iguany?}
{375} {} {Grzyby.}
{376} {} {Ech, grzyby?}
{377} {} {Tak. Te grzyby przyci¹gaj¹ niektóre owady, a owady z kolei przyci¹gaj¹ jaszczurki. Niewiele osób wie o tej sztuczce.}
{378} {} {Wszystko jasne! Ale jestem pewien ¿e wiesz du¿o wiêcej.}
{379} {} {Ciekawy schemat. Z pewnoœci¹ nie jedyny w twoim rzemioœle.}
{380} {} {Oczywiœcie. Ale powiedz mi, co dok³adnie chcesz wiedzieæ?}
{381} {} {Opowiedz mi o iguanach, ich zwyczajach, siedliskach. [Przetrwanie +3]}
{382} {} {Opowiedz mi o sztuczkach trapera. To mo¿e uratowaæ mi kiedyœ ¿ycie. [Pu³apki +3]}
{383} {} {Lepiej podziel siê ze mn¹ swoimi umiejêtnoœciami w zakresie naprawy. Kiedyœ pracowa³eœ dla kartelu. [Naprawa +3]}
{384} {} {Pos³uchaj uwa¿nie, nie zamierzam powtarzaæ tego dwa razy.}
{385} {} {Gadaj, staruszku. Chcê siê czegoœ w koñcu od Ciebie nauczyæ...}