{100} {} {Widzisz Eugene.}
{101} {} {Widzisz nastolatka. Jego rêce s¹ poplamione brudem i rdz¹, najwyraŸniej uwielbia majstrowaæ przy wszelakim sprzêcie.}
{102} {} {Szukasz szczêœliwego ¿ycia, ch³opcze? To najlepsze, co mogê zaoferowaæ.}
{103} {} {Przepraszam ch³opcze, ale w tym ¿yciu czeka ciê tylko ból i cierpienie.}
{104} {} {Eugene dotar³ do celu.}
{105} {} {Wow!}
{106} {} {Dopóki Eugene jest w twoim zespole, otrzymujesz 20-punktowy bonus do naprawy zepsutego sprzêtu.}

# Plywajace uwagi podczas odwiedzania lokalizacji:
{120} {} {}
{121} {} {Wow! Nigdy czegoœ takiego nie widzia³em!}
{122} {} {Czy to prawdziwa dzia³aj¹ca stacja radiowa? Niemo¿liwe!}
{123} {} {}
{124} {} {Wynoœmy siê st¹d, to miejsce mnie przera¿a.}
{125} {} {Masz szczêœcie, ¿e masz taki dom. Ja muszê mieszkaæ w baraku na œmieci.}
{126} {} {S³ysza³em o tym mieœcie, ale nawet nie mia³em nadziei, ¿e tu kiedyœ bêdê!}
{127} {} {Nie wiem dlaczego, ale nie lubiê tego miejsca.}
{128} {} {To nie wygl¹da na bazê Stra¿ników. Nie s¹dzisz, ¿e zgubiliœmy drogê?}
{129} {} {Co robi¹ ci wszyscy ludzie?}
{130} {} {Co... co siê tutaj sta³o?!}

# Ostateczny dialog
{190} {} {Dziêki za wszystko. Ci Stra¿nicy to twardziele, a ich tama to prawdziwa forteca. Jestem taki szczêœliwy!}
{191} {} {Dobrze, ¿e ci siê tutaj podoba. Z przyjemnoœci¹ ciê tu zostawiê.}
{192} {} {Podci¹gnij spodnie, frajerze. Nadal musisz siê wiele nauczyæ.}
{193} {} {Czeœæ.}
{194} {} {Do widzenia.}

{195} {} {Na pustkowiach mówi¹ o tobie wiele z³ych rzeczy. Chcesz to wyjaœniæ?}
{196} {} {Szczerze, jesteœ dla mnie tylko Ÿród³em dochodu. Niewa¿ne.}
{197} {} {To plotki moich wrogów. Nie zwracaj uwagi.}
{198} {} {Tak myœla³em...}
{199} {} {M?}

# Pierwszy dialog
{200} {} {Kim jesteœ? Hej, nie jesteœ miejscowym!}
{201} {} {Uch, tak.}
{202} {} {Wiêc sk¹d jesteœ? Czy ty te¿ zniewalasz ch³opów?}
{203} {} {W³aœciwie... TAK!}
{204} {} {OdejdŸ ode mnie!}
{205} {} {Hej, nie denerwuj siê...}
{206} {} {Wrêcz przeciwnie, uwalniam ich. Co wiesz o ataku na Villê?}
{207} {} {Nic. Lepiej wyjdŸ, zanim inni Ciê „ciep³o” powitaj¹.}
{208} {} {Dlaczego mieliby to zrobiæ?}
{209} {} {Dobra, dobra, i tak ledwo mogê tu wytrzymaæ.}
{210} {} {To miejsce umiera. Wkrótce w ruinach nie bêdzie ju¿ surowców. Wtedy kartel zostanie zamkniêty, a mieszkañcy bêd¹ mieli tylko kontakt z bandytami. Jak¿e bym chcia³ siê wydostaæ z tego przeklêtego miejsca!}
{211} {} {Gdzie na przyk³ad?}
{212} {} {Do Rangersów. Albo na po³udnie, gdzie jest przynajmniej trochê cywilizacji.}
{213} {} {Masz ambitne plany. Adios, muchacho.}
{214} {} {Co wiesz o niewoli ch³opów z Villi?}
{215} {} {Czeœæ.}
{216} {} {Do widzenia.}
{217} {} {Todd tu mieszka. Nie lubi nieproszonych goœci.}

#W zespole
{220} {} {Dlaczego nadal tu jesteœmy?}

{221} {} {Kiedy bêdziemy u Rangersów?}
{222} {} {Daleko jeszcze?}
{223} {} {Jestem zmêczony...}
{224} {} {Zróbmy sobiê przerwê, co?}
{225} {} {Nie mogê siê doczekaæ, a¿ zobaczê tamê Stra¿ników.}
{226} {} {Czy dok³adnie wiesz, dok¹d siê udaæ?}
{227} {} {To musi byæ œwietne podró¿owaæ ze Stra¿nikami.}
{228} {} {Czy to prawda, ¿e Stra¿nicy pij¹ mocz podczas podró¿y?}
{229} {} {Chcia³bym móc zobaczyæ samego Genera³a Stra¿ników!}

{230} {} {Poczekaj tutaj, wkrótce wrócê.}
{231} {} {ChodŸmy.}
{232} {} {Wyrzuæ to z rêki.}
{233} {} {Ale bêdziesz mnie chroniæ, prawda?}
{234} {} {Zdejmij to co masz na sobie.}
{235} {} {Cokolwiek powiesz.}

{236} {} {Chcê jak najszybciej wróciæ do domu... Albo ju¿ nie wiem, czego chcê.}
{237} {} {Nie podoba mi siê twój zespó³. Czy oni te¿ id¹ z nami? Wiêc ja zostajê.}
{238} {} {To z³y pomys³, dzieciaku.}
{239} {} {Eugene nie ufa twojej ha³aœliwej za³odze, pójdzie tylko z tob¹.}

# do³aczyæ do dru¿yny
{300} {} {Hej m³ody, Stra¿nicy s¹ zainteresowani twoimi umiejêtnoœciami. Jestem tu, ¿eby zabraæ ciê do ich bazy.}
{301} {} {Co?! To prawda?! Jestem w szoku! Tak, marzy³em o tym od dnia, kiedy po raz pierwszy zobaczy³em Stra¿nika. Ale...}
{302} {} {Ale?}
{303} {} {Ojciec nie pozwoli mi odejœæ. Nie chce nawet s³yszeæ o Rangersach i myœli, ¿e powinienem byæ jak on, padlino¿erc¹. Ale nie jestem zainteresowany kopaniem w z³omie, chcê naprawiaæ ten z³om!}
{304} {} {Dok³adnie. Twoje talenty nie bêd¹ mog³y siê rozwijaæ w tym miejscu. Idziemy do Stra¿ników.}
{305} {} {Nie mogê uciec. A jeœli ucieknê, miejscowi zwróc¹ siê gwa³townie przeciwko Stra¿nikom. I tak traktuj¹ ich ju¿ z pogard¹. Proszê, porozmawiaj z moim ojcem! Mo¿e ciê wys³ucha?}
{306} {} {Ok, porozmawiam z nim.}
{307} {} {Propozycja Stra¿ników nadal jest aktualna.}
{308} {} {To moja wielka szansa... Ale nie mogê odejœæ, dopóki mój ojciec siê nie zgodzi.}
{309} {} {Ok, porozmawiam z nim.}
{310} {} {Twój ojciec siê zgodzi³. Jestes wolny.}
{311} {} {Naprawdê?! Nie mia³em nawet nadziei. Myœla³em, ¿e nigdy nie pozwoli... No to kiedy wyje¿dzamy?}
{312} {} {W tej chwili. ChodŸmy.}
{313} {} {Twój ojciec nie ¿yje. Jesteœ teraz wolny.}
{314} {} {Jak to?! Ale... nie s¹dzi³em, ¿e to siê tak potoczy. (szlocha) Kimkolwiek by³, chcia³ dla mnie tylko tego, co najlepsze... (uspokaja siê) Có¿, teraz zdecydowanie nie mam nic do stracenia. Kiedy wychodzimy?}
{315} {} {W tej chwili. ChodŸmy.}
{316} {} {Co powiesz na dyskretn¹ dawkê jadu skorpiona?}
{317} {} {Nie mówisz powa¿nie, prawda? Wtedy nigdy ci nie wybaczê!}
{318} {} {Mo¿e chcia³byœ po prostu uciec?}
{319} {} {Wtedy Rangersi bêd¹ tu traktowani jeszcze gorzej ni¿ teraz. I nie ucieknê daleko.}

# Jeœli tama zostanie zniszczona
{320} {} {Mam dla ciebie z³¹ wiadomoœæ: baza Stra¿ników zosta³a zniszczona.}
{321} {} {To niemo¿liwe! Mia³em tak¹ nadziejê, ¿e wszystko siê u³o¿y... ¿e nie bêdê ju¿ musia³ grzebaæ w œmieciach, szukaj¹c kilku kapsli... Ale wracaæ do domu te¿ nie chcê. Co powinienem zrobiæ?}
{322} {} {Nie przetrwasz samotnie na pustyni, a Stra¿nicy nie maj¹ dla ciebie czasu. IdŸ do domu.}
{323} {} {Teraz nikt nie zap³aci mi za pilnowanie twojego ty³ka. Wiêc zostajesz sam. Ja znikam.}
{324} {} {Mój ojciec ostrzeg³ mnie, ¿ebym ci nie ufa³. Sam odnajdê drogê!}
{325} {} {Swietnie.}
{326} {} {Tak, oczywiœcie... Nie mogê uwierzyæ, ¿e to wszystko posz³o na marne!}
{327} {} {Có¿, mo¿e ¿ycie na z³omowisku nie jest takie z³e. ChodŸmy.}
{328} {} {Tu jesteœ. O co chodzi?}
{329} {} {Wiesz... Ta podró¿ z tob¹ nie posz³a na marne. Widzia³em tyle rzeczy, odkry³em inny œwiat, o którym nic nie wiedzia³em. Po tym wszystkim nie bêdê móg³ ¿yæ po staremu. Pewnego dnia na pewno pojadê na po³udnie.}
{330} {} {Brzmi pochlebiaj¹co, choæ smutno. Do widzenia.}
{331} {} {Có¿, teraz masz prawo samemu o sobie decydowaæ. Moja praca dobieg³a koñca. Z przyjemnoœci¹ siê oddalê.}