{100} {} {Widzisz padlino¿ercê.}
{101} {} {Widzisz mê¿czyznê wypalonego prac¹ i czasem.}
{102} {} {* Konwulsyjnie chwyta siê za klatkê piersiow¹ *}
{103} {} {Arch...}
{104} {} {Doszliœcie do porozumienia. Czas uszczêœliwiæ Eugena t¹ wiadomoœci¹.}
{105} {} {Lepiej mi nie przeszkadzaj.}

# Pierwszy dialog
{200} {} {Czego chcesz, nieznajomy?}
{1200} {} {Czego chcesz, nieznajoma?}
{201} {} {Dlaczego jesteœ taki niemi³y?}
{202} {} {(pluje od niechcenia) Nie przywykliœmy tu do maminsynków, przepraszam.}
{203} {} {Uch, niewa¿ne...}
{204} {} {Nie jestem przyzwyczajony do rozmowy z dupkami. Bywaj.}

# Powtarzajacy siê dialog
{210} {} {Wiêc czego chcesz?}
{211} {} {Niczego.}
{212} {} {Czy mo¿esz mi opowiedzieæ o tym miejscu?}
{213} {} {Nie mam czasu na takiego œmiecia jak ty.}
{214} {} {Dlaczego na drzwiach jest przekreœlona gwiazdka?}
{215} {} {Rangersi. Ci cholerni stra¿nicy sprawiedliwoœci i dobra chc¹ mi odebraæ najcenniejsz¹ rzecz - mojego syna. Próbujê go odizolowaæ od nich.}
{216} {} {Dlaczego chcieliby zabraæ twojego syna?}
{217} {} {Rekrutuj¹ m³odych ludzi, a nastêpnie szkol¹ ich na wojowników i zwiadowców. Nie pracowa³em w tej kopalni, ¿eby mój syn zosta³ morderc¹ w imiê cudzego pomys³u. Niech orze, tak jak ja, po gruzach i przyniesie po¿ytek swoim, a nie komuœ innemu.}
{218} {} {Co to za Stra¿nicy?}
{219} {} {Grupa uzbrojonych ludzi próbuj¹cych zdobyæ ca³¹ okolicê. Obiecuj¹ bezpieczeñstwo i porz¹dek w zamian za zasoby i rekrutów.}
{220} {} {Jest jakiœ haczyk?}
{221} {} {Brzmi jak najbardziej do przyjêcia.}
{222} {} {Tak, tylko ¿ycie nauczy³o mnie, ¿e nie mo¿esz w to wierzyæ. Po prostu dbaj¹ g³ównie o siebie i dziel¹ siê tylko nadwy¿kami. S¹ takimi samymi najeŸdŸcami co bandyci, tylko ¿e mówi¹ mi³ymi s³owami.}
{223} {} {Rozumiem.}
{224} {} {Ok.}

#Zadanie
{250} {} {Jestem tutaj, aby zabraæ twojego syna do Rangersów.}
{251} {} {Wynoœ siê, przydupasie Stra¿ników! Nie dostajesz tu nic oprócz kulki miêdzy oczy.}
{252} {} {Wiêc tego go uczysz - u¿ywania si³y do czynienia krzywdy, a nie dobrego?}
{253} {} {Powiedzia³em wynoœ siê!}
{254} {} {...On mo¿e wiêcej. Mo¿e wykonywaæ skomplikowane technicznie operacje, zamiast zbieraæ brudne œmieci.}
{255} {} {Wiem lepiej, czego on chce!}
{256} {} {To miasto prêdzej czy póŸniej umrze, a Eugene zostanie z niczym poza œmieciami.}
{257} {} {Tak, to prawda... I co z tego? Sk¹d mam wiedzieæ, ¿e ci Stra¿nicy naprawdê chc¹ dobra dla Eugene? Nie wierzê im!}
{258} {} {Zaufaj Eugene. Patrz, jak marnuje siê na tym z³omowisku. Chcesz tego? Tam zdobêdzie przynajmniej trochê przysz³oœci od Stra¿ników.}
{259} {} {Mówisz s³owami Smieciowego Diab³a... Zabierz Eugena i zaprowadŸ go w lepsze miejsce. Ale pamiêtaj - jeœli coœ mu siê stanie, osobiœcie odetnê ci g³owê!}
{260} {} {Nie musisz siê o nic martwiæ. Eugene jest w dobrych rêkach.}
{261} {} {Chyba jednak nie zmienisz swojego zdania.}
{262} {} {Jeszcze jedno s³owo i zap³acisz za to!}
{263} {} {Pos³uchaj moich s³ów - tak bêdzie lepiej.}

{270} {} {Mogê odkupiæ Eugena. Ile chcesz za niego?}
{271} {} {Nawet przez ca³e swoje ¿ycie nie zbierzesz tylu wartoœciowych œmieci, ¿eby ciê by³o staæ.}
{272} {} {Najpierw spójrz na moj¹ propozycjê...}
{273} {} {W takim razie zapomnij.}
{274} {} {H-ha! Wynoœ siê st¹d.}
{275} {} {[wyjdŸ]}
{276} {} {Wreszcie ten drañ na coœ siê przydaje. A co to jest? Kontrakt? Nie umiem pisaœ! Okej, postawiê krzy¿yk, jeœli chcesz. A teraz zabierz mojego syna. Ale jeœli coœ mu siê stanie po drodze, osobiœcie odetnê ci g³owê! Jasne?}
{277} {} {Rozumiem.}
{278} {} {(drapie nieogolony policzek w zamyœleniu)}
{279} {} {[Dalej.]}