{100} {} {Widzisz stra¿nika bramy.}
{101} {} {Widzisz mocno opalonego i dobrze ogolonego stra¿nika. Jego spokojne spojrzenie przenika ciê na wylot.}
{102} {} {Cholera! Ten motor naprawdê dzia³a?!}
{103} {} {To ju¿ inna historia! Witamy w Garage City.}
{104} {} {Witamy w Garage City. Ale ¿eby dostaæ siê do miasta, musisz odpowiedzieæ na kilka pytañ.}

# Pierwszy dialog
{200} {} {Czekaj, nieznajomy. Czego szukasz w mieœcie?}
{201} {} {Szukam moich wspó³plemieñców. Zostali zniewoleni i zabrani w tym kierunku.}
{202} {} {Potrzebujê noclegu.}
{203} {} {Prawdopodobnie niczego.}

{204} {} {Nic o tym nie wiem.}
{205} {} {Czy mogê siê przy³¹czyæ?}
{206} {} {Wiem na pewno, ¿e tu byli.}
{207} {} {Mo¿e tak. Musisz porozmawiaæ z ch³opakami przy barze lub szefem kartelu.}
{208} {} {Ok. Wiêc mogê wejœæ?}
{209} {} {Powiedzia³em, ¿e nie wiem.}
{210} {} {Chcê zapytaæ innych osadników. Mogê wejœæ?}

{211} {} {Mamy hotel, ale nie jestem pewien, czy s¹ wolne miejsca.}
{212} {} {Mo¿e powinienem tam iœæ i zapytaæ?}
{213} {} {Brzmi to ma³o prawdopodobnie. Jeœli naprawdê jesteœ tu przypadkiem, nie powinieneœ niepokoiæ mieszkañców.}
{214} {} {Nadal chcê siê rozejrzeæ po okolicy.}

{215} {} {Ju¿ wychodzisz? I s³usznie... Po œmierci pana Kogana ludzie w mieœcie zrobili siê niespokojni.}
{216} {} {Przykro mi to s³yszeæ.}
{217} {} {I dobrze. By³o nie zaprzyjaŸniaæ siê z handlarzami niewolników.}
{218} {} {Masz na myœli konwój Flagpool? Tak, umowa nie by³a najczystsza, ale przynios³a miastu niez³e dochody. W¹tpiê jednak, ¿eby te dwa przypadki by³y ze sob¹ powi¹zane... A mo¿e?}
{219} {} {Pomyœl o tym. Ja nie mam ju¿ tutaj czego szukaæ.}

{220} {} {Stop! Poka¿ rêce.}
{221} {} {Rêce? Po co?}
{222} {} {(podnosi broñ) Po prostu poka¿ rêce!}
{223} {} {Najpierw poka¿ê ci w³aœciw¹ odpowiedŸ!}
{224} {} {Ok, uspokój siê. Nie chcê wdawaæ siê w zadymê o jak¹œ ma³¹ rzecz. Pamiêtaj jednak, ¿e nie lubimy tu ¿adnych awanturników.}
{225} {} {Po co do cholery sprawdzasz mi rêce?}
{226} {} {Ok, spójrz.}
{227} {} {Hmm? Wygl¹da na to, ¿e wszystko w porz¹dku. WejdŸ.}
{228} {} {Co to do diab³a by³o?}
{229} {} {To normalny test. Wszyscy Szakale maj¹ pewien symbol, ale tu go nie widzê.}
{230} {} {Pewnie szukasz znaków charakterystycznych dla kanibali.}
{231} {} {Skoro tak mówisz... Nigdy o tym nie myœla³em, ale w sumie podobne plotki o Szakalach kr¹¿¹ ju¿ od dawna.}
{232} {} {Nastêpnym razem wezmê to jako osobist¹ zniewagê. A teraz siê odsuñ.}
{233} {} {Czy mo¿esz wyjaœniæ, co to by³o?}
{234} {} {Mam nadziejê, ¿e to nieporozumienie zostanie prêdko wyjaœnione. A teraz pozwól mi wejœæ do miasta.}
{235} {} {Spokojnie, nie jestem jednym z nich.}
{236} {} {Czekaj. Nie zrozum mnie Ÿle, poka¿ rêce przed wejœciem do miasta.}
{237} {} {Myœlisz, ¿e to ich naturalne znamie?}
{238} {} {Sk¹d mam wiedzieæ? Nawet z nimi nie rozmawiam - po prostu strzelam i na tym koniec.}

# Powtarzajacy siê dialog
{240} {} {Witamy na z³omowisku. Rozgoœæ siê.}
{241} {} {Witamy w Garage City. Spodoba ci siê tutaj... jeœli trochê tu pobêdziesz.}
{242} {} {Nie chcesz tak bardzo odejœæ, co?}
{243} {} {To z³omowisko to nasz dom. Nasz uroczy, przytulny dom.}
{244} {} {Ciekawa ta rzecz na twojej rêce. Czy to jest komputer? Nigdy takiego nie widzia³em.}
{245} {} {Czekaj, kto tam? A to ty...}

{246} {} {Och, nadal tu jesteœ. Dziwne, myœla³em, ¿e ci siê tu nie podoba³o.}
{247} {} {S³uchaj, ludzie tutaj s¹ trudni do zrozumienia, lepiej nie szwêdaj siê po ulicy.}
{248} {} {Przybywasz w interesach? Tak by³oby lepiej, w przeciwnym razie miejscowi mogliby siê pomyliæ i zrobiæ coœ g³upiego.}
{249} {} {Hej, idŸ przeszkadzaj komuœ innemu, i tak ju¿ mogê mieæ przez ciebie k³opoty.}

{250} {} {Czy znasz goœcia, o którego pytali Rangersi?}
{251} {} {Mo¿e tak. Dlaczego mia³bym pomóc Rangersom?}
{252} {} {Tak tylko pytam.}
{253} {} {Ok. Eugene Simon jest tym, kogo szukasz. Jego chata znajduje siê w pobli¿u baraku.}
{254} {} {Dziêki.}
{255} {} {To nie ma nic wspólnego z tob¹. Po prostu cofnij siê i nie wchodŸ mi w drogê.}
{256} {} {O nie, wszystko, co przechodzi przez tê bramê, mnie dotyczy.}
{257} {} {Przepraszam, ¿e jestem niemi³y. Po prostu niezwykle trudno mi mówiæ bêd¹c na celowniku. Wpuszczasz ludzi chocia¿ na noc?}
{258} {} {Chcê zostaæ na noc. Jutro mnie tu nie bêdzie.}
{259} {} {Do widzenia.}

{260} {} {Wspomnia³eœ o jakichœ Szakalach. Kto to jest?}
{261} {} {To plemiê dzikusów, które ¿yje na pustyni, ale prawie nic o nich nie wiemy. Wiemy tylko, ¿e s¹ przebieg³ymi sukinsynami, wabi¹cymi innych w pu³apki lub atakuj¹cymi s³abych podró¿ników.}
{262} {} {Rozumiem.}
{263} {} {Dlaczego nie zabiæ ich ca³ym t³umem?}
{264} {} {Chcielibyœmy ich za³atwiæ nasz¹ broni¹ raz na zawsze, ale nie wiemy, gdzie te cholerne Szakale siê ukrywaj¹. Znasz po³o¿enie ich g³ównego obozu?}
{265} {} {Niezupe³nie.}
{266} {} {Tak myœla³em.}
{267} {} {Przestañ mówiæ o tych Szakalach.}
{268} {} {W³aœciwie to tak.}
{269} {} {Naprawdê? To wszystko zmienia! Pos³uchaj, mamy tutaj kilku ludzi, którzy od dawna myœl¹ o napadniêciu na Szakale. Jeœli poka¿esz im ich legowisko, wspólnie ³atwiej bêdzie wam poradziæ sobie z tym problemem.}
{270} {} {Swietnie, dobrze. Bêdê na nich czeka³ w ich norach.}
{271} {} {Wiesz, to jest zbyt ryzykowne. Pójdê tam bez towarzystwa.}
{272} {} {S³ysza³eœ wiadomoœci o Szakalach?}
{273} {} {Tak, s³ysza³em. Okazuje siê, ¿e nie s¹ tacy mocni, jak myœleli. Po tych wszystkich wydarzeniach bêdziesz mieæ wiêcej przyjació³ w Garage City.}
{1273} {} {Tak, s³ysza³em. Okazuje siê, ¿e nie s¹ tacy mocni, jak myœleli. Po tych wszystkich wydarzeniach bêdziesz mieæ wiêcej przyjació³ w Garage City.}
{274} {} {To dobrze.}
{275} {} {Pozbycie siê Plemienia Szakali zwiêkszy³o twoj¹ reputacjê w Garage City.}
{276} {} {Tak, s³ysza³em. Rangersi s¹ kompletnie szaleni. Po tym droga do Garage City bêdzie dla nich zamkniêta. Powiedz im to, jeœli spotkasz ich na swojej drodze.}
{277} {} {Ok.}
{278} {} {Czeœæ. Nawiasem mówi¹c, fajna zbroja.}

# Uchodzcy
{280} {} {Mówi¹, ¿e przybyli tu jacyœ uchodŸcy, prawda to?}
{281} {} {Tak. Osiedlili siê w opuszczonej chacie w dzielnicy mieszkalnej. Ale nie s¹dzê, ¿e zostan¹ tu d³ugo.}
{282} {} {Dlaczego?}
{283} {} {Nie ma tu dla nich pracy. I nie ka¿dy jest gotów osiedliæ siê w tak specyficznym miejscu jak to.}
{284} {} {Rozumiem. Mówisz, ¿e s¹ w dzielnicy mieszkalnej? Muszê do nich pójœæ.}
{285} {} {Masz racjê - lepiej nie pozostawaæ w takiej dziurze zbyt d³ugo. Myœlê, ¿e na mnie te¿ czas.}

#Brahmins
{287} {} {Mogê zapolowaæ na bramina.}
{288} {} {Swietnie. Poczekajmy na innych...}
{289} {} {[Podró¿ na pustkowia]}
{290} {} {Mówi¹, ¿e polujecie na braminy, to prawda?}
{291} {} {Tak. Widzieliœmy dzikiego bramina na pustyni, nasi ludzie pokroj¹ go na kawa³ki jak tylko go z³api¹. Ale tak potê¿n¹ bestiê wcale nie jest ³atwo dorwaæ. Potrzebujemy ludzi do ataku. Chcesz do³aczyæ?}
{292} {} {Najpierw wyjaœnij mi, czym jest to zwierzê.}
{293} {} {Bramin to... no... wielka dwug³owa i czworono¿na bestia. Mieszka na pustyni, ¿ywi siê traw¹. Czy teraz wszystko jasne?}
{294} {} {Potrzebujê trochê czasu, ¿eby siê przygotowaæ. Nie odchodŸ beze mnie.}
{295} {} {Nie interesuje mnie polowanie. Porozmawiamy o czymœ innym?}
{296} {} {Swietnie, wchodzê w to. Kiedy ruszamy?}
{297} {} {Kiedy wszyscy bêd¹ gotowi. SprawdŸ swój sprzêt i wróæ do mnie.}
{298} {} {Ok.}
{299} {} {O nie, poczekaj jeszcze trochê, wkrótce wrócê.}

#Zapytania
{300} {} {To mój pierwszy raz tak daleko od domu. Czy mo¿esz mi opowiedzieæ o tym miejscu?}
{301} {} {Porozmawiamy o Garage City?}
{302} {} {WeŸ trochê alkoholu w lokalnym barze i u¿yj go bezpoœrednio na stra¿niku, aby zachêciæ go do rozmowy.}
{303} {} {Chcia³bym pogadaæ, ale mam sucho w gardle.}
{304} {} {Poczekaj, przyniosê ci coœ do picia.}
{305} {} {Brzmi to jak jakiœ tani numer, przecie¿ mo¿esz za³atwiæ sobie drinka beze mnie.}
{306} {} {Co chcesz wiedzieæ?}
{307} {} {Kolejne pytanie.}
{308} {} {Przestañ mówiæ, muszê ju¿ iœæ.}

{310} {} {Jakim sposobem to miasto ¿yje? Wygl¹da na to, ¿e nie uprawia siê tu kukurydzy.}
{311} {} {Zartujesz? Ca³e miasto istnieje dziêki kopalni. Smieciarze zdobywaj¹ tam stare rzeczy, a nastêpnie kartel sprzedaje je karawanom z po³udnia.}
{312} {} {Kto tu wszystko prowadzi?}
{313} {} {Nie mamy burmistrza ani szeryfa. Padlino¿ercy s¹ podzieleni na klany, a ka¿dy klan ma swojego przywódcê. Ale wszyscy s¹ pos³uszni panu Koganowi. To prawda, ¿e interesuje go tylko praca kopalni.}
{314} {} {Opowiedz mi o Koganie.}
{315} {} {Pan Kogan kieruje kartelem œmieciarzy i prowadzi interesy z kupcami. Nie pytaj mnie wiêcej o niego. Szef nie lubi, gdy siê o nim mówi.}
{316} {} {Nie mamy burmistrza ani szeryfa. Padlino¿ercy s¹ podzieleni na klany, a ka¿dy klan ma swojego przywódcê. Wczeœniej byli pos³uszni panu Koganowi, ale po jego œmierci w mieœcie rozpoczê³a siê powa¿na walka o jego krzes³o.}
{317} {} {Opowiedz mi o sobie.}
{318} {} {Nie mam nic do powiedzenia. Przyjecha³em tu z reszt¹ w nadziei, ¿e zarobiê w kopalni. Na szczêœcie pan Kogan da³ mi pracê odŸwiernego. Teraz upewniam siê, ¿e niew³aœciwi ludzie nie maj¹ wstêpu do miasta i odstraszam bestie.}
{319} {} {Jakie ¿yj¹ tu bestie w okolicy?}
{320} {} {G³ównie kojoty i ma³e radskorpiony. W ruinach widziano jeszcze du¿e szczury. Ogólnie to miejsce rozczaruje ka¿dego trapera. Mówi siê za to, ¿e w górach na wschodzie polowanie wrêcz kwitnie. Zastanawiam siê czy tam nie pojechaæ, gdy w mieœcie bêdzie naprawdê Ÿle.}
{321} {} {Ile lat maj¹ te ruiny?}
{322} {} {Wiêcej ni¿ ty i ja. Mówi¹, ¿e Wielka Wojna mia³a miejsce 90 lat temu. Od tego czasu to miejsce dos³ownie zardzewia³o i zapad³o siê w piasek.}
{323} {} {Co tu by³o * przed * Wielk¹ Wojn¹?}
{324} {} {Jakieœ miasto zwane Kingman. Ale jakie to ma znaczenie? To staro¿ytna historia. Nikogo to ju¿ nie obchodzi.}
{325} {} {Pytam z ciekawoœci. Porozmawiajmy o czymœ wa¿niejszym.}
{326} {} {Dlaczego ¿yjecie wsród tych wszystkich œmieci?}
{327} {} {Czy masz jakiœ lepszy pomys³? Stare budynki ju¿ nie nadaj¹ siê do u¿ytku, dlatego musieliœmy zbudowaæ nowe, ze œmieci.}

# O konwoju niewolników
{330} {} {By³ tu konwój niewolników. Powinieneœ coœ o tym wiedzieæ.}
{331} {} {Nie wiem, co masz na myœli. Nie by³o tu ¿adnego konwoju niewolników. Porozmawiaj z ch³opakami przy barze lub szefem kartelu. Mo¿e padlino¿ercy coœ wiedz¹.}
{332} {} {Powiedz mi, jeœli coœ wiesz. Byli wœród nich moi krewni. Czy kiedykolwiek straci³eœ kogoœ bliskiego?}
{333} {} {Ok, porozmawiam z nimi.}
{334} {} {(wzdycha) Nie powiedzia³em ci tego. Konwój wyruszy³ do miasta Flagpool. Kieruj siê na wschód 40. autostrad¹ miêdzystanow¹. Podobno dotarcie tam zajmuje tydzieñ.}
{335} {} {Wiêc Flagpool. Dziêkujê, amigo, jesteœ dobrym cz³owiekiem.}
{336} {} {Wiêc dlaczego, do diab³a, po prostu mi tego nie powiedzia³eœ?! Jose mia³ racjê, mówi¹c mi o tej dziurze.}
{337} {} {Wspó³czujê ci, ale nie mogê ci pomóc.}
{338} {} {Jeœli mnie ok³amiesz, drogo za to zap³acisz.}
{339} {} {Ok, porozmawiam z innymi.}
{340} {} {I pamiêtaj, ¿e konwój jest dobrze uzbrojony i dobrze zorganizowany. To nie s¹ jakieœ tam kanibalistyczne dzikusy z pustkowi.}
{341} {} {Dziêki za informacje.}
{342} {} {Do widzenia, muszê ju¿ iœæ.}

#Bronie
{350} {} {Masz œwietn¹ broñ.}
{351} {} {Tak.}
{352} {} {Uch, nie rozmawiajmy o tym.}
{353} {} {No to porozmawialiœmy. Czeœæ.}

{354} {} {Sk¹d to masz?}
{355} {} {Dosta³em od d³u¿nika zamiast kapsli.}
{356} {} {Gdyby to by³a naprawdê dobra broñ, nie zastanawia³ byœ siê nad odpowiedzi¹. NajwyraŸniej czegoœ mi nie mówisz.}
{357} {} {Czy strzela?}
{358} {} {Ta broñ niejeden raz uratowa³a mi ¿ycie na warcie.}
{359} {} {S¹dz¹c po zabrudzeniu na wylocie, nie strzelano z niej od bardzo dawna.}
{360} {} {Chcesz j¹ sprzedawaæ?}
{361} {} {Hmm... nie.}
{362} {} {Przerwa w odpowiedzi sugeruje, ¿e twoja broñ nie jest tak dobra jak mówisz. Nie strzela, prawda?}

{363} {} {Cholera, jak ty do tego doszed³eœ? (wzdycha) Masz racjê, nie strzela. Z reszt¹ i tak nie ma tu za wiele amunicji. No dalej, œmiej siê.}
{1363} {} {Cholera, jak ty do tego dosz³aœ? (wzdycha) Masz racjê, nie strzela. Z reszt¹ i tak nie ma tu za wiele amunicji. No dalej, œmiej siê.}
{364} {} {Dlaczego potrzebujesz niestrzelaj¹cej broni?}
{365} {} {Do zastraszania, g³upku! A kiedy jest to konieczne - mogê i kastetem za³atwiæ kogo trzeba. Czy to jasne?}
{366} {} {Czy nie ma tu nikogo, kto naprawi³by tê broñ?}
{367} {} {Nasz mechanik nie ma czêœci, których potrzebuje do jej naprawy. W tych stronach trudno znaleŸæ dzia³aj¹c¹ broñ paln¹. A nawet jeœli ktoœ naprawi tê broñ, nadal nie ma tu z czego strzelaæ.}
{368} {} {Mogê to naprawiæ.}
{369} {} {Powa¿nie? By³oby mi³o. Zap³acê 25 kapsli, jeœli ci siê uda.}
{370} {} {Nie mogê poradziæ sobie z twoj¹ broni¹. Porozmawiajmy o tym póŸniej.}
{371} {} {Tak, nie dzia³a. I nie ma nawet amunicji. Coœ jeszcze?}
{372} {} {Chcê odkupiæ tê broñ.}
{373} {} {No có¿, nic.}
{374} {} {Rozumiem. To jasne, ¿e lepiej ciê zostawiæ.}
{375} {} {Wygl¹da na to, ¿e masz k³opoty, stary. Có¿, pójdê ju¿.}
{376} {} {Zobaczmy...}
{377} {} {Cholera, uda³o ci siê! A wydawa³o mi siê, ¿e ch³opi nigdy nie trzymali broni w rêkach. To znaczy, jestem ci wdziêczny. Oto 25 kapsli zgodnie z umow¹. Ech, teraz muszê znaleŸæ trochê amunicji...}
{378} {} {Masz szczêœcie, ¿e tu jestem.}
{379} {} {Nie, nie mogê tego naprawiæ.}
{380} {} {Tak myœla³em.}
{381} {} {To znaczy, nie mogê tego teraz naprawiæ. Mo¿e póŸniej.}
{382} {} {Teraz na pewno nawet nie dotknê twojej broni.}
{383} {} {Za tyle kapsli to mogê co najwy¿ej umieœciæ ten karabin w koszu na œmieci. Poszukaj kogoœ innego.}