{100} {} {Widzisz uchodŸcê.}
{101} {} {Widzisz jednego z nowo przyby³ych.}
{102} {} {U¿yj na nim jedzenia, by nakarmiæ uchodŸcê.}

# Pierwszy dialog
{200} {} {(przeszywaj¹cy dziki typ patrzy na ciebie spod brudnych loków) Czego chcesz? Tak, ty. Co?}
{201} {} {Nie martw siê. Nie zrobiê ci krzywdy.}
{202} {} {Nie ufasz obcym, prawda?}
{203} {} {Czego chcesz? Nie jem ju¿ drugi dzieñ i chc¹ mnie wyrzuciæ z tego miasta. Daj mi coœ do jedzenia lub zostaw mnie w spokoju.}
{204} {} {Ok, poszukam czegoœ jadalnego w moim plecaku.}
{205} {} {Nakarmiæ ciê? IdŸ do diab³a, ¿ebraku!}
{206} {} {Nakarmiê ciê moj¹ piêœci¹, ¿ebraku!}
{207} {} {Zbli¿ siê do mnie jeszcze trochê, a zjesz w³asn¹ rêkê.}
{208} {} {Nie! Nie dotykaj mnie!}
{209} {} {Ok, uspokój siê. Chcê tylko zadaæ pytanie.}
{210} {} {Nie zrobiê tego, jeœli odpowiesz na moje pytania.}
{211} {} {Zostaw mnie w spokoju.}
{212} {} {Ok.}
{213} {} {Wiêc to wasza grupa sz³a do Rangersów i zjecha³a z trasy?}

# Powtarzajacy siê dialog
{220} {} {Czego chcesz?}
{221} {} {Do widzenia.}
{222} {} {Dziêki za jedzenie. Jak mogê ci podziêkowaæ?}
{223} {} {Nic dzisiaj. Bywaj.}
{224} {} {Rozumiem.}

{230} {} {Co robicie w tym mieœcie?}
{231} {} {Mamy k³opoty. Na po³udniowym wschodzie dziej¹ siê straszne rzeczy: zmienia siê tam w³adza w miastach, ludzie s¹ zniewalani, rolnicy s¹ wypêdzani ze swych krajów. Mieliœmy nadziejê znaleŸæ ratunek w krainach Stra¿ników, ale tutaj wcale nie jest lepiej.}
{232} {} {Jak przedostaliœcie siê przez pustyniê?}
{233} {} {To by³a prawdziwa mêka. W nocy pizga³o, w dzieñ parówa, by³o tak gor¹co, ze piekliœmy jaszczurki na kamieniach. G³ówn¹ trasê pokonywaliœmy wieczorem i wczesnym rankiem. Czasami wydawa³o nam siê, ¿e nie prze¿yjemy tej wyprawy. A na pewno nie prze¿yjemy drugiej takiej wyprawy.}
{234} {} {Tak, to naprawdê nie brzmi dobrze.}
{235} {} {Powiedz mi jeszcze raz, jak siê tu dostaliœcie?}

{240} {} {Co sprawi³o, ¿e opuœciliœcie ziemie Rangersów?}
{241} {} {Rangersi. Ha! Powiedziano nam, ¿e chroni¹ prawo i porz¹dek. Ale w rzeczywistoœci to zwykli bandyci.}
{242} {} {Dlaczego tak uwa¿asz?}
{243} {} {Jak œmiesz mówiæ tak o Stra¿nikach?}
{244} {} {Najpierw zabrali nam wszystko, co mia³o jak¹kolwiek wartoœæ, a potem kazali nam opuœciæ ich ziemie.}
{245} {} {Dlaczego mieliby wam kazaæ odejœæ?}
{246} {} {Spójrz na te ³achmany - nie mamy ju¿ nic co mo¿na by nam odebraæ, jesteœmy zubo¿a³ymi uchodŸcami. I nie mamy ani si³y, ani ochoty pracowaæ dla nich jako wolni niewolnicy. Ju¿ nas nie potrzebowali, wiêc wyrzucili nas jak bezu¿yteczne œmieci.}
{247} {} {Dlaczego uzna³eœ, ¿e to Rangersi?}
{248} {} {Jeden z nich pokaza³ nam swoj¹ odznakê. Co wiêcej, zwykli bandyci nie chcieliby nas przegoniæ, tylko po prostu okraœæ lub zabiæ.}
{249} {} {Dziwna historia... Muszê poznaæ szczegó³y, nie opuszczajcie jeszcze miasta.}

{250} {} {Muszê znaleŸæ tych *Stra¿ników*.}
{251} {} {ZnaleŸæ? Po co? Nie kuœ losu. Okradn¹ ciê lub zabij¹.}
{252} {} {Zajmê siê nimi. Po prostu poka¿ mi miejsce ich pobytu.}
{253} {} {Rzeczywiœcie, to zbyt niebezpieczne. Zapomnij.}
{254} {} {Uh nie, jestem za s³aby, ¿eby podró¿owaæ. Chcia³bym odpocz¹æ i coœ zjeœæ przed podró¿¹.}
{255} {} {Wrócê, gdy bêdziesz silniejszy. Bywaj.}
{256} {} {Bêdziesz gryŸæ w³asne zêby, jeœli nie poka¿esz mi miejsca ich pobytu.}
{257} {} {W porz¹dku. Oto 20 kapsli, których mo¿esz u¿yæ, aby kupiæ jedzenie w lokalnym barze.}
{258} {} {(wygl¹da na zniecierpliwionego, gdy grzebiesz w kieszeniach)}
{259} {} {Uch, myœlê, ¿e zostawi³em gotówkê w motelu.}
{1259} {} {Uch, myœlê, ¿e zostawi³am gotówkê w motelu.}