{100} {} {Widzisz padlino¿ercê.}
{101} {} {Widzisz bandytê nosz¹cego ochronn¹ maskê spawalnicz¹.}

{110} {} {Co tutaj robisz?}
{111} {} {Szpiegujesz nas?}
{112} {} {Kogan ciê przys³a³?}

{120} {} {Lucas wie, co robi.}
{121} {} {Lucas i ja du¿o razem przeszliœmy.}
{122} {} {Mogê sobie wyobraziæ, jak z³y musi byæ teraz Treyvon.}
{123} {} {Ta fabryka jest nasz¹ ostatni¹ nadziej¹.}
{124} {} {To my otworzyliœmy fabrykê, wiêc teraz jest nasza.}
{125} {} {Kogan bêdzie musia³ pójœæ na ustêpstwa.}

{130} {} {Jesteœmy bardzo szczêœliwi, ¿e ciê mamy.}
{131} {} {Dziêki za pomoc.}
{132} {} {Tutaj jesteœ zawsze mile widziany.}
{133} {} {Teraz my tu rz¹dzimy. Dziêkujê Ci.}
{134} {} {Nie wiem, jak by siê to wszystko skoñczy³o, gdyby nie ty.}
