{100} {} {Widzisz Lucasa.}
{101} {} {Widzisz doœwiadczonego padlinozercê w he³mie ochronnym.}
{102} {} {Wynoœ siê z mojej fabryki!}

# Pierwsze zadanie
{150} {} {(widzisz doœwiadczonego padlinozercê; marszczy brwi, siedz¹c w swobodnej pozie) Nie spodziewa³em siê, ¿e Kogan pos³u¿y siê do nieznajomym. Kim jesteœ?}
{1150} {} {(widzisz doœwiadczonego padlinozercê; marszczy brwi, siedz¹c w swobodnej pozie) Nie spodziewa³em siê, ¿e Kogan pos³u¿y siê do nieznajom¹. Kim jesteœ?}
{151} {} {Nie mam pojêcia, kim jest Kogan. Scigam konwój niewolników.}
{152} {} {Hmm. Czy jesteœ z tej wioski, któr¹ przejêli koloniœci? Znam tê historiê. Kogan próbowa³ dogadaæ siê z porywaczami w nadziei na przysz³e kontrakty. Opowiedzia³ im o Villi, bo ci ludzie szukali dzikusów do pracy, okaza³o siê, ¿e nawet o tobie nie s³yszeli.}
{153} {} {Kogan ¿¹da wyjaœnieñ.}
{154} {} {Dostanie je. Ale chcê wiedzieæ, dlaczego TY pracujesz dla tego chciwego bogacza? Co ci obieca³ za twoj¹ pracê?}
{155} {} {W³aœciwie to szukam ludzi, którzy zabrali moich krewnych wbrew ich woli. Kogan coœ o tym wie.}
{156} {} {Czy wiesz, gdzie zabrano niewolników?}
{157} {} {Tak, wiem. Powiem ci wszystko, jeœli wyœwiadczysz mi przys³ugê. Po tym wszystkim, co s³ysza³eœ, nie zamierzasz pracowaæ dla Kogana, prawda?}
{158} {} {Po prostu mi powiedz. I nic ci siê nie stanie.}
{159} {} {Czy ty masz mózg? Lepiej zadbaj o w³asne bezpieczeñstwo, ³atwo tu straciæ ¿ycie.}
{160} {} {Co mam zrobiæ?}
{161} {} {Ok, wys³ucham twoich "zadañ".}
{162} {} {Potrzebujê wszystkich najnowszych kontraktów Kogana. Musz¹ byæ zapisane na komputerze w jego gara¿u. Po prostu skopiuj i przynieœ mi je. Wtedy porozmawiamy.}
{163} {} {Ok, zrobiê, o co poprosisz. Do zobaczenia wkrótce.}
{164} {} {Cholera, to spore ryzyko. Za du¿o wymagasz.}
{165} {} {Chcesz dowiedzieæ siê czegoœ o najeŸdŸcach? Wiêc idŸ i nie wracaj bez informacji.}
{166} {} {Tak, oczywiœcie.}
{167} {} {Pomyœlê i * mo¿e * siê zgodzê.}
{168} {} {Mam pytania.}
{169} {} {Hej, widzê ciê! WyjdŸ z cienia, suko. Szpiegujesz dla Kogana?}
{170} {} {Masz te kontrakty?}
{171} {} {Jeszcze nie.}
{172} {} {Kto powiedzia³, ¿e w ogóle zamierzam to zrobiæ?}
{173} {} {Prawdopodobnie nie wiesz, ale Kogan nie ¿yje.}
{174} {} {To znacznie u³atwi ci to zdobycie kontraktów. Nadal potrzebujê tych danych.}
{175} {} {Wiêc lepiej pójdê i siê tym zajmê.}
{176} {} {Wiesz, nie znam siê zbyt na komputerach. Dlatego wykonanie zadania bêdzie bardzo trudne.}
{177} {} {Cholera, nie pomyœla³em o tym. Najprawdopodobniej Kogan przechowuje dane pod has³em. Nie chcê tego robiæ, ale muszê ci daæ dekoder. On sam zhakuje system, musisz tylko trochê poczekaæ.}
{178} {} {To wszystko zmienia. Teraz mogê spróbowaæ.}
{179} {} {}
{180} {} {To s¹ dane z komputera.}
{181} {} {Ok, zobaczmy... tak... ok...}
{182} {} {By³o tam coœ ciekawego?}
{183} {} {Du¿o do siebie mówisz, co?}
{184} {} {Kogan zgodzi³ siê z s¹siednim miastem na dostawê czêœci z tej fabryki. Karawana jest w drodze. Wystarczy, ¿e wyprzedzimy go i wczeœniej spotkamy karawanê.}
{185} {} {Dlaczego to takie interesuj¹ce?}
{186} {} {Ta fabryka to niewyczerpana ¿y³a! Wystarczy j¹ uruchomiæ i znaleŸæ klientów. Nie ma ich wielu, ale istniej¹.}
{187} {} {Hej, a co z nasz¹ umow¹?}
{188} {} {Lepiej trzymaj siê nas. Porozmawiamy o tym, kiedy to wszystko siê skoñczy.}
{189} {} {Ale ja nie chcê w tym braæ udzia³u!}
{190} {} {Jeœli wszystko pójdzie g³adko, nie bêdziesz musia³. Po prostu spotkamy siê z karawan¹, wymienimy siê rzeczami i rozejdziemy siê w pokoju.}
{191} {} {Rób, co chcesz. Nie obchodzi mnie to.}
{192} {} {Swietny pomys³. Kiedy ruszamy?}
{193} {} {W pierwszej kolejnoœci nale¿y zebraæ te czêœci. PrzejdŸ siê po fabryce i przynieœ to, co jest zapisane w umowie. Wszystko, czego potrzebujesz, powinno tu byæ.}
{194} {} {Ok.}
{195} {} {Muszê ciê o coœ zapytaæ.}
{196} {} {Nie rozmawiam, dopóki nie dostanê kontraktów.}
{197} {} {Ok, masz kontrakty...}
{198} {} {O tak!}

# Po pierwszym zadaniu
{210} {} {Mów.}
{211} {} {Chyba ju¿ pójdê.}

{220} {} {Co to za miejsce?}
{221} {} {Naprawdê nie wiesz, co to jest fabryka? Widaæ - masz mocno opalon¹ skórê. Prawdopodobnie mieszkasz na pustyni... Fabryki u¿ywane s¹ do produkcji sprzêtu i ró¿nych przyborów. Ale w tej chwili s¹ uœpione i czekaj¹, a¿ ktoœ znowu je uruchomi.}
{222} {} {Nie interesuje mnie ju¿ temat fabryki. Porozmawiamy o czymœ innym?}
{223} {} {Dlaczego?}
{224} {} {Powiedzia³eœ, ¿e fabryki s¹ teraz uœpione. Dlaczego?}
{225} {} {W dzisiejszych czasach nie ma sk¹d wzi¹æ tyle energii aby je zasiliæ. A nawet jeœli istnieje Ÿród³o, to tylko nieliczni maj¹ niezbêdne umiejêtnoœci i wiedzê, aby z niego korzystaæ. Od czasu Wielkiej Wojny ludzie tylko trwonili swoje osi¹gniêcia...}
{226} {} {Co tu produkowano?}
{227} {} {To jest fabryka Watts Electronics. Tu wytwarzano czêœci do sprzêtu elektronicznego i baterii j¹drowych.}
{228} {} {Sk¹d tu tak du¿o œwiat³a?}
{229} {} {To przez te stare lampy. Zasilane s¹ energi¹ elektryczn¹, wytwarzaj¹ j¹ generatory rezerwowe, poniewa¿ lokalny reaktor by³ bezczynny od czasu „wielkiego boom”. Nadal mo¿na go uruchomiæ. Ale to wymaga paliwa j¹drowego, a nie ma sk¹d go braæ.}
{230} {} {Sk¹d tyle wiesz o przedwojennej technologii?}
{231} {} {Jestem padlino¿erc¹, pracujê ze starymi przedmiotami od lat.}
{232} {} {Wiesz, te kawa³ki ¿elaza nie budz¹ zaufania.}
{233} {} {Roboty? Nie pozwala³y nam wejœæ do fabryki. Tylko dziêki dekoderowi uda³o nam siê zhakowaæ system i wy³¹czyæ alarm. Roboty s¹ teraz bezpieczne. A dodatkowo mo¿na u¿ywaæ ich zamiast pracowników.}

{240} {} {Czy wiesz, ¿e Kogan nie ¿yje?}
{241} {} {Tak, plotki szybko siê rozesz³y w Garage City. Szczerze mówi¹c, nawet trochê mi przykro.}
{242} {} {[Dalej.]}
{243} {} {Kogan by³ chciwym draniem, ale by³ dobrym przedsiêbiorc¹. I mo¿na by³o siê z nim dogadaæ. Bez tego padlino¿ercy pewnie wszystko tutaj zniszcz¹.}
{244} {} {Wygl¹da na to, ¿e masz tutaj problemy. Porozmawiajmy o czymœ innym.}
{245} {} {Wygl¹da na to, ¿e bardzo zdenerwowa³eœ swojego szefa.}
{246} {} {Nie obchodzi mnie to. Szef potrzebuje nowych inwestycji w biznesie i tylko ja mogê je zapewniæ wœród wszystkich padlino¿erców w mieœcie. Bêdzie musia³ pójœæ na ustêpstwa.}
{247} {} {Twoje stanowisko jest jasne.}
{248} {} {A co z innymi padlino¿ercami? Czy myœla³eœ o nich?}
{249} {} {Przejrzyj na oczy - Garage City umiera. Nie ma tu ju¿ miejsca dla tylu pracowników. Pozwól im udaæ siê w inne miejsca.}

{250} {} {Oto czêœci wymienione w umowie.}
{251} {} {(dok³adnie analizuje temat staro¿ytnej technologii) Tak, wszystko siê zgadza. Przygotuj siê na spotkanie z karawan¹. Spotykamy siê w pobli¿u starej przepompowni wody. Nie wiem, co mo¿e siê tam staæ, wiêc weŸ lepsz¹ broñ i mocniejsze ubranie.}
{252} {} {Mogê ju¿ tam iœæ.}
{253} {} {Potrzebujê czasu, aby siê przygotowaæ.}
{254} {} {Spokojnie, to trochê potrwa...}
{255} {} {[IdŸ z padlino¿ercami]}
{256} {} {Nie, czekaj, potrzebujê trochê czasu.}
{257} {} {Ok. Spotkamy siê na stacji pomp.}

{260} {} {Uda³o siê! Bez Twojej pomocy by³oby to dla nas znacznie trudniejsze, teraz jesteœmy ci winni d³ug. Tutaj, weŸ 200 kapsli. To jest za Twój udzia³ w transakcji.}
{261} {} {Co zamierzasz teraz zrobiæ?}
{262} {} {Mam zamiar odbudowaæ fabrykê. Obiecano nam dostarczyæ paliwo do reaktora, a nastêpnie mo¿emy uruchomiæ maszyny i rozpocz¹æ produkcjê nowych czêœci.}
{263} {} {W takim razie powodzenia.}
{264} {} {No có¿, przyjrzê siê twoim wysi³kom w przysz³oœci. Zegnaj, marzycielu-padlino¿erco.}
{265} {} {Uda³o siê! Bez Twojej pomocy by³oby nam trochê trudniej. Skonsultowaliœmy siê i zdecydowaliœmy, ¿e zas³ugujesz na swój udzia³.}
{266} {} {Kapsle s¹ zawsze mile widziane. Co zamierzasz teraz zrobiæ?}
{267} {} {Twoja broñ by³aby dla mnie bardziej u¿yteczna ni¿ te kapsle.}
{268} {} {Oczywiœcie, weŸ j¹. To jest emiter laserowy. Z³o¿y³em go z miejscowych czêœci. I tak z³o¿ê ich prawdopodobnie wiêcej.}

{270} {} {Obieca³eœ opowiedzieæ mi o najeŸdŸcach.}
{271} {} {Tak, nie jest to ³atwa historia. Widzisz, w rzeczywistoœci byli najemnikami zebranymi ze wszystkich pobliskich osad. Prowadzili ich kolesie z Flagpool. To miasto na wschodzie, tydzieñ st¹d.}
{272} {} {Dlaczego potrzebuj¹ ch³opów?}
{273} {} {Najpierw szukali legowiska Szakali, ¿eby zmusiæ ich do pracy w swoich kopalniach. Ale wtedy Kogan wyczu³ zysk i zaproponowa³ atak na Villê. Wie, gdzie mo¿na zarobiæ kapsle. Flagpool wyda³o siê byæ obiecuj¹cym klientem kartelu.}
{274} {} {Wiêc jesteœcie tu wszyscy powi¹zani z atakiem na Villê, co?}
{275} {} {Rozumiesz, ta umowa da³a Garage City niez³¹ okazjê na krok do przodu. A nasze spotkanie z karawan¹ by³o czêœci¹ tego procesu. Mo¿e ci siê to nie podobaæ, ale my, padlino¿ercy, musimy jakoœ przetrwaæ sami.}
{276} {} {Wybaczam ci. A teraz muszê iœæ do tego... Flagpool.}
{277} {} {Nie myœl, ¿e kiedykolwiek zapomnê o tej historii. Ludzie z Villi maj¹ dobr¹ pamiêæ.}

{280} {} {Czeœæ Lucas. Chodzi o fabrykê. Moja spo³ecznoœæ obawia siê, ¿e zaszkodzi Villi.}
{281} {} {Bzdury. Przybêd¹ tu nowi pracownicy, a obroty miasta wzrosn¹. Poczujecie siê lepiej, poniewa¿ bêdziecie mogli handlowaæ swoimi uprawami i ceramik¹ z du¿ymi miastami.}
{282} {} {Mo¿e. Jednak nasi starsi chc¹ izolacji.}
{283} {} {Starzy ludzie nie chc¹ zmian? Wiêc przekonaj ich do nich! Swiat siê zmienia, oni te¿ bêd¹ musieli.}
{284} {} {Pomyœlê o tym.}
{285} {} {Byæ mo¿e po wszystkich moich wêdrowkach zgadzam siê z tob¹. Ale jak mogê przekonaæ starszych ludzi? Potrzebuj¹ gwarancji immunitetu.}
{286} {} {Ha, w jakim œwiecie ty ¿yjesz? Nie ma ¿adnych gwarancji, s¹ tylko umowy. Ale wiesz co - * mo¿emy * siê dogadaæ.}
{287} {} {Naprawdê?}
{288} {} {W mieœcie zosta³o wielu bezrobotnych. Moja fabryka nie zapewni im pracy w najbli¿szej przysz³oœci. Mo¿emy zaoferowaæ Twojej Villi ró¿ne us³ugi po bardzo niskich kosztach. Odbudujesz wioske, wzmocnisz swoje ziemie, a my zarobimy trochê pieniêdzy. A co wa¿niejsze, unikniemy konfliktów w s¹siedztwie.}
{289} {} {Przeka¿ê twoj¹ propozycjê spo³ecznoœci. Byæ mo¿e siê zgodz¹.}
{290} {} {Obawiam siê, ¿e starszym siê to nie spodoba. Do zobaczenia.}