{100} {} {Widzisz Lucasa.}
{101} {} {Widzisz Lucasa.}
{102} {} {Umowa powiod³a siê.}

{110} {} {Miej oczy szeroko otwarte. Nie mo¿esz pozwoliæ, aby ogary Kogana lub Trayvona przeszkodzi³y w umowie.}
{111} {} {Rozpraw siê z ludŸmi Kogana, podczas gdy ja zajmê siê karawan¹.}
{112} {} {Wróæ do fabryki, tam porozmawiamy.}
{113} {} {Lepiej siê st¹d wynoœ. I to tak szybko, jak to mo¿liwe.}
{114} {} {Wychodzimy, Kogan wiêcej nie otrzyma od nas ¿adnych wiadomoœci.}

{120} {} {Wszystko wydaje siê byæ w porz¹dku.}
{121} {} {Cholera, to ludzie Kogana. Powiedz im, ¿eby odeszli.}
{122} {} {Gotowe, wracaj do fabryki i czekaj tam na mnie.}

{200} {} {Nie mamy z tob¹ problemu. Po prostu wyjdŸ st¹d, a nic ci siê nie stanie.}
{201} {} {Kogan ostrzega, abyœ nie ingerowa³ w umowê.}
{202} {} {Powiedz grubemu, ¿e jego panowanie siê skoñczy³o. Teraz my jesteœmy u steru tego miasta.}
{203} {} {Pope³ni³eœ najwiêkszy b³¹d w swoim ¿yciu, staj¹c przeciwko Koganowi. I zap³acisz za to. Teraz!}
{204} {} {Ok, powiem mu o tym.}
{205} {} {Hej ludzie, zabierzcie swoje ty³ki z ziemi. Wychodzimy!}
{206} {} {Wygl¹da na to, ¿e siê zaczê³o...}
{207} {} {Lepiej nie wystêpuj przeciwko temu cz³owiekowi. Nigdy nie dojdziesz do jego pozycji.}
{208} {} {Nie mieliœmy wyboru. Nie by³o pracy, a miasto sta³o siê dla nas wszystkich za ciasne. Wygl¹da na to, ¿e teraz zosta³o nam po prostu wyjœæ i siê po³o¿yæ. W tym celu na pustkowiach jest du¿o miejsca.}
{209} {} {Dobra decyzja.}
{210} {} {Tylko g³upiec wystêpuje przeciwko samemu Koganowi.}
