{100} {} {Widzisz Blacharza.}
{101} {} {Widzisz, ¿e facet jest ca³y czerwony ze stresu.}

{110} {} {Nie rozmawiaj o tym.}
{111} {} {Proszê, nie bij mnie! Naprawiê to, serio!}

{200} {} {Co... Kim ty w ogóle jesteœ? Czego chcesz?}
{201} {} {Tylko patrzê, jak siê bawicie.}
{202} {} {Tak. Jakieœ problemy?}
{203} {} {Hej, co robisz?}
{204} {} {Tañczymy tutaj. Na materacu. Rozumiesz?}
{205} {} {Chcê do³aczyæ.}
{206} {} {Z twoj¹ g³ow¹ chyba nie wszystko jest w porz¹dku. Wynoœ siê, kretynie!}
{1206} {} {Z twoj¹ g³ow¹ chyba nie wszystko jest w porz¹dku. I nie mamy ochoty na takie akcje. WyjdŸ!}
{207} {} {Spokojnie ch³opcze, wychodzê...}
{208} {} {Nie pozwolê ci kontynuowaæ.}
{209} {} {Ooh, mamy tu bohatera. Co zamierzasz zrobiæ? CO? Powiedz mi, suko?}
{210} {} {Po prostu wyjdê i nie bêdê ci przeszkadzaæ. Bawcie siê dobrze.}
{211} {} {Zabijê ciê. Umierajcie, gnidy!}
{212} {} {Wyci¹gnê pistolet i poczekam dok³adnie trzy sekundy. Jeden, dwa...}
{213} {} {}
{214} {} {Dobra, dobra! Uspokój siê koleœ! Trzymaj pistolet w kaburze. Nie jesteœmy takimi zwierzêtami, uh, mo¿emy to spokojnie rozwi¹zaæ.}
{1214} {} {Ok, ok! Uspokój siê kole¿anko! Trzymaj pistolet w kaburze. Nie jesteœmy takimi zwierzêtami, uh, mo¿emy to spokojnie rozwi¹zaæ.}
{215} {} {Wynoœ siê st¹d.}
{216} {} {Drzwi s¹ otwarte.}
{217} {} {Przeszkadzasz mi w spaniu.}
{218} {} {Hej, zap³aciliœmy za pokój i mo¿emy robiæ, co chcemy. Rozumiesz?}
{219} {} {Jeœli nie przestaniesz, bêdziesz mia³ problemy z ca³ym miastem.}
{220} {} {Wiemy, kim jesteœ, g³upi wieœniaku. Nikt Ciê nie zaprosi³ do naszego miasta. Nie zastraszysz nas.}
{221} {} {Ok. Ale i tak bêdziesz o mnie pamietaæ.}
{222} {} {Znaj swoje miejsce, œmieciu. Jeœli siê nie uspokoisz, bêdziesz mia³ k³opoty.}
{223} {} {Uh, ok... Nie potrzebujê problemów. Odejdê, jak coœ to mnie tu nie by³o...}