{100} {} {Widzisz dziewczynê.}
{101} {} {Widzisz pó³nag¹ dziewczynê.}

{110} {} {Nie chcia³am! Sami mnie rozebrali!}

{200} {} {(niepewnie siada na ³ó¿ku i powoli prostuje szmaty) D... dziêki...}
{201} {} {Jak wpakowa³aœ siê w tê sytuacjê?}
{202} {} {Nie wiem... Nie s¹dzi³am, ¿e to siê tak skoñczy...}
{203} {} {Jesteœ po prostu g³upia. To wszystko.}
{204} {} {Od teraz bêdziesz m¹drzejsza.}
{205} {} {Bydlaku! Dlaczego musia³eœ ich zabiæ? Nie byli tak okrutni jak ty! Czy rozumiesz, ¿e teraz wszyscy bêd¹ mnie unikaæ?}
{206} {} {Czy to ciê niczego nie nauczy³o?}
{207} {} {Jak inaczej mogê zarabiaæ w tym umieraj¹cym mieœcie? Nie mogê nawet st¹d wyjechaæ... by³oby lepiej, gdyby ciê tu nie by³o... by³oby lepiej, gdyby to miasto w ogóle nie istnia³o! Ja...}
{208} {} {Um, nie przejmuj siê. Do widzenia...}
{209} {} {Opamiêtaj siê, g³upia. Zrobi³em to, co musia³em zrobiæ.}
{1209} {} {Opamiêtaj siê, g³upia. Zrobi³am to, co musia³am zrobiæ.}
{210} {} {Nie chcia³am tego. Ale jak inaczej mogê zarabiaæ w tym umieraj¹cym mieœcie? Nie mogê nawet st¹d wyjechaæ... by³oby lepiej, gdyby nie by³o tego ca³ego miasta! Ja...}
{211} {} {Hum... hum... Och, to ty... Czeœæ.}
{212} {} {Hum... hum... Och, to ty... OdejdŸ, nie chcê ciê widzieæ.}
{213} {} {Do widzenia.}
