{100} {} {Widzisz administratora.}
{101} {} {Widzisz ³ysego niewymiarowego mê¿czyznê w bardzo znoszonych ubraniach.}
{102} {} {Jesteœ wypoczêty.}

# Reakcja na zbrojê
{160} {} {Masz niez³y kombinezon. Nawet za du¿y. Sprzedasz go?}
{161} {} {To nie jest na sprzeda¿. To pami¹tka rodzinna.}
{162} {} {(znacz¹co zaciska usta) Hmm. Przywi¹zanie do staroci prawdopodobnie masz we krwi.}
{163} {} {Nikt ciê nie pyta³ o zdanie.}
{164} {} {Nie wiem, te rzeczy s¹ po prostu dziedziczone. I to wszystko.}
{165} {} {(patrzy na gwiazdê na twojej nowej zbroi z pogard¹) Wiêc jesteœ Rangersem? Co ty tu do cholery robisz? Zamierzasz wpajaæ nam swoj¹ moralnoœæ i narzucaæ zasady swojego * gangu *? Tak czy inaczej, nie potrzebujemy tego. Jesteœmy samowystarczalni, rozwi¹zujemy swoje problemy bez Was.}
{166} {} {Uwa¿aj na jêzyk, g³upcze. Któregoœ dnia to miasto uklêknie przed Prawem.}
{167} {} {Nie wiem, co masz na myœli. Ta zbroja le¿a³a po prostu na pustyni, a teraz jest moja.}
{168} {} {Hej, czy nie jesteœ jednym z tych kultystów z po³udnia? S³ysza³em, ¿e nosz¹ takie œmieszne ubrania i czcz¹ bombê atomow¹. Jeœli tak, nie chcê nawet s³yszeæ nic o twojej wierze.}
{169} {} {Niech Swiêty Ogieñ ciê ukarze, g³upcze.}
{170} {} {Ja i jakaœ sekta? Ja? Nigdy!}
{171} {} {T-ty... j-jesteœ... Nie bêdziesz spaæ w tej puszce, prawda? I dlaczego potrzebujesz motelu z takim wyposa¿eniem?}
{172} {} {Najpierw kup sobie zbrojê wspomagan¹, ¿eby mówic mi, co mam robiæ.}
{173} {} {Nie martw siê, nie zrobiê ci krzywdy.}
{174} {} {Hmm. Nigdy bym nie pomyœla³ o zrobieniu zbroi ze znaków drogowych.}
{175} {} {Jeœli szydzisz z mojej zbroi, bêdziesz mia³ k³opoty. Rozumiesz?}
{176} {} {Ja te¿. To tylko trofeum.}

# Zatrzymaj dialog
{180} {} {Wiem, ¿e przez ciebie w barze dosz³o do rozróby. Czy tutaj te¿ bêdziesz stwarzaæ problemy?}
{181} {} {Nie, nie, to by³ wypadek. Miejscowy pijak stan¹³ mi na stopê. W codziennym ¿yciu jestem ciszej ni¿ k³os kukurydzy!}
{182} {} {„Uwierzê” ci. Ale jeœli zarezerwujesz pokój, zap³acisz podwójn¹ cenê.}
{183} {} {Nie obchodzi mnie twój pieprzony motel.}
{184} {} {Ale to jest motel. Jeœli nie zamierzasz zarezerwowaæ pokoju, to po co tu jesteœ?}
{185} {} {Zadajê sobie to samo pytanie. Chyba powinienem ju¿ iœæ.}
{186} {} {Musia³em z kimœ porozmawiaæ.}
{187} {} {Dziêki, ¿e mnie nie wyrzuci³eœ.}
{188} {} {Poradzê sobie bez motelu. Wychodzê.}
{189} {} {Czego do diab³a chcesz? Usi¹dŸ cicho na swoim krzeœle i tam siedŸ.}
{190} {} {Ok. Tak jak mówisz. Ale jeœli zarezerwujesz pokój, zap³acisz podwójn¹ cenê.}
{191} {} {Za du¿o sobie pozwalasz, cholera!}
{192} {} {Jesteœ w z³ym mieœcie, ¿eby stawiaæ warunki, kochanie. IdŸ i zaczerpnij œwie¿ego powietrza.}
{193} {} {Pierdol siê!}
{194} {} {Reszta tego miasta myœli o mnie lepiej.}
{195} {} {Ok, przepraszam. Nie potrzebujê dodatkowych k³opotów, rozumiesz?}
{196} {} {Oczywiœcie.}
{197} {} {Zapytaj o mnie swoich rodaków. Pewnie powiedz¹ coœ mi³ego.}
{198} {} {Bardzo w to w¹tpiê.}
{199} {} {Nie walczmy. Jestem tu w celach pokojowych.}

# Pierwszy dialog
{200} {} {(przed sob¹ widzisz ³ysiej¹cego mê¿czyznê w zniszczonej kurtce; patrzy na ciebie z niedowierzaniem przez ciemnoœæ dusznych baraków)}
{201} {} {Czeœæ.}
{202} {} {Hej, hej! Ci goœcie byli tylko prostymi chuliganami. Nie chcia³em problemów i zamkn¹³em oczy na ich wybryki. Co mi innego zosta³o? Ja jestem tylko ofiar¹ okolicznoœci. Ale ¿eby zabijaæ od razu ludzi... Powiem ci, ¿e nic nie widzia³em, ale po prostu odejdŸ, dobrze?}
{203} {} {Nie martw siê, nie bêdê ju¿ ci przeszkadza³.}
{204} {} {Usi¹dŸ cicho i nie wychylaj siê. Nie myœl, ¿e mo¿esz siê mnie tak ³atwo pozbyæ.}

# Powtarzajacy siê dialog
{210} {} {Jak mogê pomóc?}
{211} {} {Do widzenia.}

{219} {} {Zapomnij, nie mam teraz tylu kapsli.}
{220} {} {Szukam konwoju niewolników, który mija³ to miasto. Wiesz cokolwiek o tym?}
{221} {} {Mo¿e. Ale czasami mam luki w pamiêci. I tylko dzwonienie stu kapsli mo¿e to naprawiæ.}
{222} {} {To jest rozbój w bia³y dzieñ! Zapytam kogoœ innego.}
{223} {} {Mów! Koñczy mi siê cierpliwoœæ!}
{224} {} {To nie jest zbyt m¹dre posuniêcie z twojej strony. Ka¿dy padlino¿erca w tym mieœcie mnie zna, a ty jesteœ po prostu obcym z pustkowia. Wiêc wyjdŸ z motelu, zanim wezwê pomoc.}
{225} {} {Niech tak bêdzie, oto sto kapsli. A teraz powiedz mi wszystko, co wiesz.}
{226} {} {Ok, spokojnie, wychodzê.}
{227} {} {Oto kapsle. A teraz powiedz mi wszystko, co wiesz.}
{228} {} {Wiem, ¿e z tymi ludŸmi musisz uwa¿aæ. Po co pytasz?}
{229} {} {Scigam ten konwój. Czy wiesz, dok¹d zmierza?}

{230} {} {(ze zdumieniem chowa kapsle pod sto³em) Nie s¹dzi³em, ¿e mówisz powa¿nie... Tak, ci goœcie zrobili niez³e zamieszanie w naszym cichym mieœcie. Dawno nic takiego siê tu nie dzia³o. Ale z drugiej strony ca³e miasto otrzyma³o dziêki nim trochê ¿ycia.}
{231} {} {O czym ty mówisz? Jaki rodzaj ¿ycia?}
{232} {} {Prawie ka¿de miejsce w mieœcie na tym zyska³o. Na przyk³ad w moim motelu nie zosta³o ani jedno wolne miejsce. W barze prawie wszystko sprzedano. A pan Kogan dosta³ nawet jakieœ kontrakty. Miasto ¿y³o z ca³ego tego niewolniczego ba³aganu przez tydzieñ.}
{233} {} {Kim s¹ ci w³aœciciele niewolników?}
{234} {} {Dru¿yna zosta³a z³o¿ona z ró¿nych najemników, ale kto by³ klientem, nie wiem. Oczywiœcie nie chcia³ siê osobiœcie wybieraæ tak daleko.}
{235} {} {Wiêc gdzie posz³a ta dru¿yna?}
{236} {} {Do miasta zwanego Flagpool. IdŸ tras¹ 40 na wschód. Podobno podró¿ trwa oko³o tygodnia.}
{237} {} {Cholera...}
{238} {} {Co powiedzia³eœ?}
{239} {} {Chyba powinienem ju¿ byæ w drodze.}

#Pokój
{250} {} {Wygl¹da na to, ¿e wynajmujesz pokoje na noc?}
{251} {} {Czy s³owo "motel" coœ dla ciebie znaczy? Tak. Wynajmujê pokoje.}
{252} {} {Opowiedz mi o szczegó³ach.}
{253} {} {Pokój dla jednej osoby. Srednio * niezawodny * zamek. Ló¿ko i meble s¹ wliczone w cenê, ale nie przyjmujê roszczeñ dotycz¹cych czystoœci. Swiat³a w korytarzu zapalaj¹ siê w nocy. Najwa¿niejszym atutem jest ochrona. Zaden bandyta nie mo¿e siê tu tak ³atwo przedostaæ. Oznacza to, ¿e mo¿esz spaæ spokojnie.}
{254} {} {Czy jest popyt na te pokoje?}
{255} {} {Wczeœniej miasto aktywnie handlowa³o z po³udniowymi miastami, gromadzi³y siê tu t³umy poszukiwaczy i karawan. Ostatnio bywa tu niewielu goœci. (wzdycha) Ledwo wi¹¿emy koniec z koñcem.}
{256} {} {Od jak dawna prowadzisz ten motel?}
{257} {} {Przyjecha³em tu kilka lat temu, jak wielu innych, z nadziej¹, ¿e zarobiê kapsle. Miasto potrzebowa³o wtedy motelu i pomyœla³em, ¿e mo¿na na tym zyskaæ wiêcej ni¿ na brudnej i niebezpiecznej kopalni.}
{258} {} {Dziwnie nazywacie to miasto, Garage City.}
{259} {} {Nie wiem. Tak wysz³o. Stare Miasto jest pe³ne gara¿y i warsztatów samochodowych. A karawany korzystaj¹ z tych potê¿nych przyczep samochodowych.}
{260} {} {Ok, to by³o nawet zabawne.}
{261} {} {Kusz¹ce. Przemyœlê tê ofertê.}
{262} {} {Doœæ historii. Wróæmy do bardziej teraŸniejszych pytañ.}
{263} {} {Jakkolwiek to nazwiesz, chcia³bym teraz zmieniæ temat.}
{264} {} {Wow, p³aciæ za d³ugi, spokojny sen. Ile kosztuje jedna noc? }
{265} {} {Ech, czy s³ysza³eœ o wspania³ych domach z gliny w mojej wiosce... Ile kosztuje noc w tej norze?}
{266} {} {To bêdzie kosztowaæ }
{267} {} { kapsli.}
{268} {} {Chcê wynaj¹æ pokój.}
{269} {} {Oto kapsle.}
{270} {} {Przemyœlê tê propozycjê.}
{271} {} {To zdecydowanie za drogo. Idê spaæ pod go³ym niebem.}

{280} {} {Hej, ktoœ zosta³ zgwa³cony w s¹siednim pokoju!}
{281} {} {To nie twoja sprawa. Jeœli nie chcesz problemów, przejdŸ obok i b¹dŸ cicho.}
{282} {} {I nic nie zrobisz?}
{283} {} {Wiêc jesteœ z nimi w zmowie, czy co?}
{284} {} {Dziewczyna sama prosi³a siê o takie ¿ycie. Gdyby nie chcia³a, nie zadawa³aby siê z tymi facetami. Nie wspó³czuj jej. I nic strasznego siê jej nie dzieje. Ch³opaki pobawi¹ siê i pozwol¹ jej odejœæ... Mówiê ci - to nie twoja sprawa!}
{285} {} {Cholera, nie mogê tego tak po prostu zostawiæ.}
{286} {} {No có¿, to chyba naprawdê nie moja sprawa.}