{100} {} {Widzisz mechanika.}
{101} {} {Widzisz prostego pracownika. Jest pilnie zajêty naprawianiem starych œmieci.}
{102} {} {Oferta mechanika zawiera teraz wiêcej przydatnych przedmiotów i kapsli.}
{103} {} {W ofercie mechanika znajduje siê teraz jeszcze wiêcej przydatnych przedmiotów i kapsli.}
{104} {} {No creo en mis ojos! Czy to naprawdê zbroja wspomagana?!}

{200} {} {Och! Fajerwerki, towarzysze! Nowy w mieœcie?}
{201} {} {Czy to serio jest miasto?}
{202} {} {Dlaczego nie, senor? Ma wszystko, co ma mieæ miasto - bar, hotel, zakwaterowanie, prace. Po¿yj tu trochê, to zobaczysz wszystko na w³asne oczy.}
{1202} {} {Czemu nie, senorita? Ma wszystko, co ma mieæ miasto - bar, hotel, zakwaterowanie, prace. Po¿yj tu trochê, to zobaczysz wszystko na w³asne oczy.}
{203} {} {Uch, pomyœlê o tym. Kim jesteœ?}
{204} {} {Nazywam siê Pedro Fuerte... albo po prostu Pete.}
{205} {} {Nazwê ciê Pete.}
{206} {} {Cokolwiek najbardziej panu odpowiada, sir. Tak bêdzie wygodniej.}
{1206} {} {Cokolwiek ci najbardziej odpowiada, senora. Tak bêdzie wygodniej.}
{207} {} {Mi³o ciê poznaæ, Pedro.}
{208} {} {(uœmiecha siê) Mnie równie¿, drzwi do Garage City s¹ zawsze otwarte. Jak mogê pomóc?}
{209} {} {Chyba wrócê póŸniej.}

{210} {} {Fajerwerki!}
{211} {} {Adios.}
{212} {} {Czy mo¿esz odpowiedzieæ na kilka pytañ?}
{213} {} {Przestañ mówiæ. Chce siê tylko rozejrzeæ.}
{214} {} {Powiedz mi wiêcej.}
{215} {} {Nazywasz tê garœæ brudnych ruder miastem?}

#Pytania
{220} {} {Si, senor?}
{1220} {} {Si, senora?}
{221} {} {Co to za miejsce?}
{222} {} {To jest Garage City pana Kogana - siedziba kartelu œmieciarzy. Tutaj utylizujemy œmieci z ruin. Przydatne id¹ do karawan, a reszta - na handel lokalny. Potrzebujesz czêœci lub przewodów? Mo¿emy siê wymieniæ.}
{223} {} {Opowiedz mi o swojej pracy.}
{224} {} {Jestem mechanikiem, senor. Sprawdzam to, co przynosz¹ padlino¿ercy. W razie potrzeby naprawiam i przygotowujê wszystko do wysy³ki.}
{1224} {} {Jestem mechanikiem, senora. Sprawdzam to, co przynosz¹ padlino¿ercy. W razie potrzeby naprawiam i przygotowujê wszystko do wysy³ki.}
{225} {} {Co myœli o tobie szef?}
{226} {} {Docenia moj¹ pracê! Jestem jego g³ównym asystentem w pracy z padlino¿ercami.}
{227} {} {Wygl¹da bardziej na to, ¿e ciê wykorzystuje.}
{228} {} {O nie... Chocia¿ myœlê, ¿e powinienem dostaæ kilka kapsli wiêcej za to co robiê.}
{229} {} {On ciê wykorzystuje... Ok, pójdê ju¿.}
{230} {} {Nie, nie, pan Kogan - on jest szefem, nie mogê bez niego ¿yæ.}
{231} {} {Pytanie nie dotyczy³o tego, ale niewa¿ne.}
{232} {} {Dok¹d id¹ te œmieci?}
{233} {} {Gdy przyje¿dza karawana to handlujemy z nimi. W dzisiejszych czasach ka¿dy potrzebuje czêœci zamiennych.}
{234} {} {Kim s¹ padlino¿ercy?}
{235} {} {Poszukiwacze, scavengers, œmieciarze - czy po prostu padlino¿ercy, to jedno i to samo. Wydobywaj¹ po¿yteczne surowce w lokalnych ruinach - pozosta³oœciach Starego Swiata. Nastêpnie przenosz¹ te zasoby do przetwarzania i otrzymuj¹ za to kapsle. S¹ oni podzieleni na klany i wszyscy pracuj¹ na podstawie umowy z kartelem.}
{236} {} {Czy ktoœ mo¿e siê targowaæ tu na boku?}
{237} {} {Och, pan Kogan tego nie lubi. A jeœli nie on, to reszta padlino¿erców nie przebaczy. Ci co ³ami¹ tê zasadê nie zostaj¹ tu d³ugo.}
{238} {} {Padlino¿ercy tego nie wybaczaj¹, nie ma mowy. W obrêbie klanu ca³y wydobyty surowiec jest przekazywany przywódcy, a dochód jest dzielony miêdzy wszystkich. Jeœli ktoœ z³amie zasady, nie zostanie tu d³ugo.}

{240} {} {Twój szef nie ¿yje. Co zamierzasz teraz zrobiæ?}
{241} {} {Jest Ÿle, sir. Szef mnie upokarza³, p³aci³ po³owê kapsli za ciê¿k¹ pracê, ale bez niego... bez niego ca³e Garage City upadnie!}
{1241} {} {Jest Ÿle, senora. Szef mnie upokarza³, p³aci³ po³owê kapsli za ciê¿k¹ pracê, ale bez niego... bez niego ca³e Garage City upadnie!}
{242} {} {Na pewno?}
{243} {} {Tylko on wiedzia³, jak robiæ interesy. Teraz wœród padlino¿erców rozpocznie siê teraz wojna o kopalnie. Nie wiem, co robiæ... Mo¿e czas opuœciæ to miejsce. Ale gdzie ja pójdê?}
{244} {} {Wygl¹da na to, ¿e masz ma³o opcji. Porozmawiajmy o czymœ innym.}

# O produkcie
{250} {} {Czym handlujesz?}
{251} {} {Tym co znaleŸli padlino¿ercy i co naprawi³em.}
{252} {} {Tym co znaleŸli padlino¿ercy i co naprawi³em. Tylko pan Kogan przechowuje najlepsze towary dla najwa¿niejszych handlarzy. Wiêc nie mogê zaoferowaæ Ci wszystkiego.}
{253} {} {Uch, nie, szef wie, o czym mówi.}
{254} {} {Wiesz, nie musisz zawsze tak trzymaæ siê regu³.}
{255} {} {Swietnie. Wiêc co mówisz, ¿e handlujesz?}
{256} {} {Spójrz tylko na te œmieci. Nie bêdziesz w stanie ich sprzedaæ przez wieki! A ja mogê je ju¿ kupiæ.}
{257} {} {Racja, sir. (ods³ania czêœæ towaru)}
{1257} {} {Racja, senora. (ods³ania czêœæ towaru)}
{258} {} {Jeœli odmówisz mi pe³nego asortymentu, stracisz cennego klienta.}
{259} {} {Racja, sir. (ujawnia wszystkie swoje towary)}
{1259} {} {Racja, senora. (ujawnia wszystkie swoje towary)}
{260} {} {Pan Kogan od dawna nie ¿yje. Czy mogê teraz liczyæ na pe³n¹ obs³ugê?}
{261} {} {Si, senor. (ujawnia wszystkie swoje towary)}
{1261} {} {Si, senora. (ujawnia wszystkie swoje towary)}
{262} {} {Pan Kogan przyzna³ mi prawo do dobrego towaru. Poka¿ wszystko co masz.}
{263} {} {Si, senor. (ujawnia wszystkie swoje towary)}
{1263} {} {Si, senora. (ujawnia wszystkie swoje towary)}
{264} {} {Co to jest za urz¹dzenie?}
{265} {} {Licznik Geigera? (bierze urz¹dzenie i trzyma je przy przy ciele) Uh, senor, powinieneœ to kupiæ! Miernik pokazuje poziom napromieniowania, wielu padlino¿erców chcia³oby go otrzymaæ. Ale to dla nich za drogie.}
{1265} {} {Licznik Geigera? (bierze urz¹dzenie i trzyma je przy swoim ciele) Ou, senora, powinnaœ to kupiæ! Miernik pokazuje poziom napromieniowania, wielu padlino¿erców chcia³oby go otrzymaæ. Ale to dla nich za drogie.}
{266} {} {Pomyœlê o tym.}
{267} {} {Potrzebujê czêœci do naprawy radia.}
{268} {} {Naprawdê? Musisz mieæ wielkie plany. Niewielu u¿ywa obecnie radia. Na przyk³ad Stra¿nicy. Czy to oni Ciê wys³ali?}
{269} {} {Nie wiem, co masz na myœli. Wiêc masz wzmacniacz? A mo¿e powinienem pojechaæ do innego miasta?}
{270} {} {Hej, nie œpiesz siê, amigo! Tak, mam kilka modu³ów, mo¿e bêd¹ dzia³aæ, mo¿e nie.}
{271} {} {Wiêc zobaczmy to.}

{276} {} {W przyczepie Todda by³a maszyna do produkcji kapsli. Jest ju¿ zniszczona.}
{277} {} {Dobra robota, amigo. Oto kapsle, jak obieca³em. Najwa¿niejsze, ¿eby nie rozwodziæ siê nad t¹ sytuacj¹. Nie chcê, aby ktoœ zosta³ zlinczowany przeze mnie.}
{278} {} {Zegnaj Pete.}
{279} {} {Zap³acê PRAWDZIWYMI kapslami.}

{280} {} {Co to jest, kapsle do butelek?}
{281} {} {No tak, u¿ywamy ich jak pieniêdzy przed Wielk¹ Wojn¹. Nie wiesz o tym?}
{282} {} {To wygl¹da trochê... dziwnie.}
{283} {} {Wszyscy s¹ do tego przyzwyczajeni. To bardzo wygodne. Tylko uwa¿aj, ktoœ zacz¹³ wybijaæ w³asne kapsle. To Ÿle, bo jeœli bêdzie za du¿o kapsli, stan¹ siê bezwartoœciowe. A najbogatszy bêdzie ten, który je tworzy.}
{284} {} {Tak, to trochê niesprawiedliwe.}
{285} {} {Próbowaliœmy wyœledziæ tego pendejo przez d³ugi czas. Jeœli dowiesz siê, kto wybija fa³szywe kapsle, powiedz mi.}
{286} {} {Koniecznie.}
{287} {} {Ok.}
{288} {} {O maszynie do kapsli.}
{289} {} {Tak? Jakieœ nowoœci?}
{290} {} {Nie, jeszcze nie.}
{291} {} {Wygl¹da na to, ¿e to Todd. Zap³aci³ mi nowymi kapslami.}
{292} {} {On sam móg³ byæ ofiar¹ oszusta. Nie wiñmy go z góry. Ale nie zaszkodzi tego sprawdziæ.}
{293} {} {Co sugerujesz?}
{294} {} {Co o tym myœlisz, amigo? Przyczepa... narzêdzia... bom! Ktoœ to musi zrobiæ, wiesz? Skontaktowa³bym siê z innymi mieszkañcami, ale obawiam siê, ¿e Todd zostanie zlinczowany. Nie chcê nikogo skrzywdziæ.}
{295} {} {Teraz rozumiem. WejdŸ do przyczepy i poszukaj narzêdzi do robienia kapsli. A jeœli tam s¹, to trzeba je zniszczyæ.}
{296} {} {Wiêc zrobisz to?}
{297} {} {Ok. Ale wejœcie do czyjegoœ domu jest powa¿nym wykroczeniem. Oby mnie nikt nie zauwa¿y³.}
{298} {} {Ok. Zrobiê to.}
{299} {} {Nie, poszukaj innego g³upca.}

# Uslugi naprawcze
{300} {} {Jakie us³ugi œwiadczy warsztat?}
{301} {} {Naprawiam wszystko, co wymaga naprawy - bronie, zbroje, twoj¹ ulubion¹ kosiarkê. Pytanie tylko, ile kapsli mo¿esz zap³aciæ.}
{302} {} {Czy naprawiasz samochody czy coœ w tym rodzaju?}
{303} {} {Och, gdybym tylko móg³! Zasadniczo rozk³adam stare technologie na u¿yteczne czêœci. Moim marzeniem jest naprawienie czegoœ naprawdê samobie¿nego.}
{304} {} {Spójrz na mój motor.}
{305} {} {W takim razie spójrz na mój motor.}
{306} {} {Rozumiem. W takim razie co naprawiasz?}
{307} {} {Prawdziwy motor i to sprawny?! Przysiêgam na wszystkie biegi, z przyjemnoœci¹ przy nim pomajstrujê!}
{308} {} {Nie, myœlê, ¿e jednak nie mogê ci pozwoliæ siê do niego zbli¿aæ.}
{309} {} {Ten motor potrzebuje lepszych opon, masz jakiœ pomys³?}
{310} {} {Och, znalezienie dobrych opon w dzisiejszych czasach to wielka sprawa. Ale mam to, czego potrzebuje. Do tego s³u¿y Garage City!}
{311} {} {Potrzebujê wiêkszego pojemnika na moim motocyklu.}
{312} {} {Poka¿. Hmm, mogê zrobiæ nowy pojemnik, dooko³a jest du¿o ¿elaza i mam sprawarkê.}
{313} {} {SprawdŸ uk³ad napêdowy.}
{314} {} {Tak, jest tu praca do wykonania! Ten motor nie by³ czyszczony od stu lat. Poza tym mogê znaleŸæ zamienniki zu¿ytych czêœci silnika. Mo¿e to zmniejszyæ zu¿ycie energii o oko³o 50%.}
{315} {} {Ile chcesz za tê robotê?}
{316} {} { kapsli. I bez barteru!}
{317} {} {Ok, oto kapsle.}
{318} {} {Pomyœlê o tym, ale na razie zobaczê coœ innego.}
{319} {} {To zbyt drogo, nie staæ mnie na to.}

{320} {} {(krêci g³ow¹) To nie wystarczy.}
{321} {} {Och, naprawdê...}
{322} {} {Zmiana opon zwiêksza prêdkoœæ motocykla o oko³o 15%.}
{323} {} {Twój motocykl ma teraz baga¿nik o pojemnosci 100 funtów.}
{324} {} {Mechanik Pete wykona³ œwietn¹ robotê - motocykl bêdzie teraz zu¿ywa³ o 50% mniej mocy.}
{325} {} {Gotowe!}
{326} {} {Swietnie. Zobaczmy, co jeszcze mo¿esz zrobiæ.}
{327} {} {Dziêki. Pójdê teraz sprawdziæ, jak to dzia³a.}