{100} {} {Widzisz komputer pana Kogana.}
{101} {} {Widzisz stary komputer, fachowo przebudowany przez mechaników warsztatowych.}
{102} {} {Maszyna zniszczona!}
{103} {} {[test: jest uszkodzenie]}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Koniec sesji.}
{202} {} {Wstecz.}

{210} {} {Wyœwietl raporty kartelu za ca³y okres.}
{211} {} {(Od 2160 r. Padlino¿ercy aktywnie wydobywaj¹ surowce z ruin Kingman. Przez pierwsze szeœæ lat kopalnia zapewnia³a ogromne zyski, ale po tym harmonogram wydobycia i handlu zacz¹³ siê stopniowo pogarszaæ.)}
{212} {} {Umowy z Flagpool.}
{213} {} {(Pan Kogan ma kilka kontraktów z Koloni¹ Flagpool na wymianê z³omu i us³ug naprawczych na ¿ywnoœæ, lekarstwa i paliwo j¹drowe. NajwyraŸniej oczekuje równie¿ nowych kontraktów, jeszcze bardziej znacz¹cych.)}
{214} {} {Umowa pomocy technicznej.}
{215} {} {(Pan Kogan aktywnie wspiera³ oddzia³ najeŸdŸców przed i po zniewoleniu Villi. W ramach kontraktu zapewni³ im miejsca noclegowe, czyst¹ wodê i us³ugi naprawy sprzêtu. I chocia¿ zysk by³ niski, perspektywy na przysz³oœæ s¹ obiecuj¹ce.)}
{216} {} {Dalej.}
{217} {} {(Z danych wynika, ¿e najeŸdŸcy byli grup¹ najemników z kolonii o nazwie Flagpool. NajwyraŸniej to tam zosta³a zabrana zniewolona populacja Villi.)}

{220} {} {Kopiuj umowy dla Lucasa.}
{221} {} {Dane skopiowane pomyœlnie.}
{222} {} {Swietnie.}
