{102} {} {Intruz! Alarm!}

{200} {} {Dios mio, kim jesteœ?}
{201} {} {Jestem œmierci¹ dla tyranów takich jak ty.}
{202} {} {Zastanawiam siê, czy powinienem do³aczyæ do twojego oddzia³u.}
{203} {} {O czym ty mówisz? Schwytaæ tego szpiega!}
{204} {} {Ok...}
{205} {} {Pope³niasz b³¹d, generale.}
{206} {} {Cywil. Chcê do³aczyæ do twojej armii, generale!}
{207} {} {To godne pochwa³y. Ale bior¹c pod uwagê, w jaki sposób dosta³eœ siê do fortu, nie ma tu dla ciebie ¿adnej pracy. Komisarz odprowadzi ciê do wyjœcia. Jeœli wrócisz, bêdzie gorzej. Jasne? A teraz wynoœ siê.}
{1207} {} {To godne pochwa³y. Ale bior¹c pod uwagê, w jaki sposób dosta³aœ siê do fortu, nie ma tu dla ciebie ¿adnej pracy. Komisarz odprowadzi ciê do wyjœcia. Jeœli wrócisz, bêdzie gorzej. I nie bêdê patrzeæ na to, ¿e jesteœ kobiet¹. Jasne?}
{208} {} {Cokolwiek powiesz, generale.}
{209} {} {Nigdzie nie idê.}

{210} {} {Ostrzega³em ciê. Do celi karnej! Niech cierpi razem z reszt¹ jeñców wojennych.}
{1210} {} {Ostrzega³em ciê. Do celi karnej! Niech cierpi razem z reszt¹ jeñców wojennych.}
{211} {} {Nie, nie, nie mogê iœæ do celi karnej, mam klaustrofobiê...}
{212} {} {Nikt mnie tam nie zaci¹gnie, nie ma szans.}
