{100} {} {Widzisz wartownika.}
{101} {} {To szeregowy w typowej wojskowej zbroi z charakterystycznym symbolem. Dba o to, by do garnizonu nie wchodzili ¿adni ludzie z zewn¹trz.}
{102} {} {¡El intruso!}

{110} {} {* Ziewa *}
{111} {} {Estoy aburrido...}
{112} {} {¿Alguien viene?}
{113} {} {¿Dƒnde estž el cambio de guardia?}
{114} {} {Hoy es un dša caluroso.}
{115} {} {Tengo que informar sobre esto.}
{116} {} {Malditos insectos.}
{117} {} {Necesito zapatos nuevo.}
{118} {} {}
{119} {} {}

{120} {} {* Ziewa *}
{121} {} {Nudno...}
{122} {} {Czy ktoœ tu kiedyœ przyjdzie?}
{123} {} {Gdzie jest stra¿nik zmiany?}
{124} {} {Strasznie dziœ gor¹co.}
{125} {} {To bêdzie musia³o zostaæ zg³oszone.}
{126} {} {Przeklête owady...}
{127} {} {Potrzebujê nowych butów.}
{128} {} {}
{129} {} {}

{200} {} {¡Alto ahš! No te muevas.}
{201} {} {Co?}
{202} {} {Eres un gringo, ¿No? ¿Hablas espaœol?}
{203} {} {Moje mówi¹ jezykiem piêœci. Patrz i ucz siê, ojcze...}
{204} {} {Przepraszam, nie mówiê po hiszpañsku.}
{205} {} {Americano - droga - przystanek. Czy rozumiesz? Wróæ. Szybki.}
{206} {} {Wypêdzasz mnie? Ale dlaczego?}
{207} {} {Jak œmiesz mówiæ mi, gdzie mam iœæ? ZejdŸ mi z drogi!}
{208} {} {Cywil - brak wpisu. IdŸ - albo strzelê. ChodŸmy! ChodŸmy!}
{209} {} {Mówisz powa¿nie. Ok, pójdê.}
{210} {} {Pierdol siê!}
{211} {} {Hablo un poco de espaœol.}
{212} {} {Grozisz mi?}

{220} {} {Intruz! Alarm!}
{221} {} {¡El intruso! ¡Alerta!}
{222} {} {Nie powinienem by³ tego robiæ...}
{223} {} {Hej, chyba Ÿle mnie zrozumia³eœ ...}

{230} {} {Me alegro de escucharlo. Hm. ¿De dƒnde vienes?}
{231} {} {[po hiszpañsku] Pochodzê z ma³ej wioski na pó³nocy. Musia³em przebyæ d³ug¹ drogê w poszukiwaniu mojej rodziny.}
{232} {} {Przekroczy³eœ pustyniê Sonora? Trudno mi w to uwierzyæ. W ka¿dym razie zawróæ i wróæ do siebie.}
{1232} {} {Przekroczy³aœ pustyniê Sonora? Trudno mi w to uwierzyæ. W ka¿dym razie zawróæ i wróæ do siebie.}
{233} {} {Ale dlaczego mnie odpêdzasz?}
{234} {} {Przed tob¹ jest fort Zjednoczonej Armii Meksykañskiej. Cywile nie maj¹ tu wstêpu. Mam rozkaz strzelaæ do ka¿dego, kto przekroczy garnizon bez pozwolenia.}
{235} {} {Rozumiem. Ok, pójdê sobie.}
{236} {} {Czy mogê do³aczyæ do waszych szeregów?}
{237} {} {I jeszcze czego? Zeby gringo z pó³nocy by³ jednym z nas? Po prostu odejdŸ st¹d.}
{238} {} {Och...}
{239} {} {Cholera. Nigdzie nie idê.}

{240}{}{Nie rozumiesz za pierwszym razem? Wejdziesz do garnizonu - dostaniesz kulê w ³eb. Rozumiesz?}
{241}{}{Dobra, dobrze, wychodzê...}
{242}{}{Znowu to robisz, a ja nie mogê na to pozwalaæ.}
{243}{}{?Eres T? otra vez? (podnosi groŸnie broñ) Vete! ?Voy (krzyczy po hiszpañsku)!}
{244}{}{Wiem, ¿e jeden z was wzi¹³ nadajnik radiowy od rodziny Dominguez.}
{245}{}{Naprawdê? Nie wiedzia³em tego. Szkoda, ¿e zostali w ten sposób potraktowani.}
{246}{}{Mo¿esz oddaæ radio?}
{247}{}{Szczerze, nie wierzê, ¿e po prostu troszczysz siê o tych farmerów. Musisz mieæ w tym jakiœ interes.}
{248}{}{Dobrze ich rozumiem. Te¿ doœwiadczy³em niesprawiedliwoœci ze strony ludzi z broni¹.}
{249}{}{Po prostu próbujê pomóc.}
{250}{}{Zapomnij, naprawdê nie warto.}
{251}{}{[Grozi broni¹] Radio czy ¿ycie?}
{252}{}{Gringo nie jest godny zaufania.}
{253}{}{Wspania³a mowa. Prawie uroni³em ³zê. Dobra, porozmawiam z dowódc¹...}
{254}{}{Poczekam...}
{255}{}{Znalez³em to radio w koszarach. Daj to rodzinie Dominguez. Nie chcemy byæ tacy za jakich nas bior¹.}
{256}{}{Super. Mo¿na by³o tak od razu.}
{257}{}{Gracias.}
{258}{}{A jeœli dam ci te butelkê orzeŸwiaj¹cego napitku? Hmm?}
{259}{}{Dobra, porozmawiam z dowódc¹...}
{260}{}{Oddaj to.}
{261}{}{Proszê je zwróciæ. To strasznie niesprawiedliwe.}