{100} {} {Widzisz jeñca wojennego.}
{101} {} {Widzisz mê¿czyznê ze œladami pobicia.}
{102} {} {Widzisz Jacka.}
{103} {} {Czy to twój dom? Trochê staroœwiecki, ale spokojny. Lubiê to miejsce.}
{104} {} {Dobrze sobie radzisz! Widzia³em tyle roœlin tylko w Casa Nueva.}
{105} {} {Nie mów mi, ¿e znowu musimy wejœæ do jakiejœ dziury.}
{106} {} {Phoenix... Chocia¿ tam dorasta³em, jakoœ nie chcê wracaæ.}

{200} {} {Kim jesteœ? Czego chcesz?}
{201} {} {To nie ma znaczenia. Po prostu usi¹dŸ i milcz.}
{202} {} {Nie rób ha³asu, nie jestem tu zupe³nie „legalnie”. Dlaczego jesteœ zamkniêty?}
{203} {} {Czy to jakaœ sztuczka maj¹ca na celu rozwi¹zanie mi jêzyka? Wszystko ju¿ powiedzia³em podczas przes³uchania! Zosta³em wynajêty przez kupców do zbadania tych ziem. Mieli nadziejê, ¿e otworz¹ tu nowe trasy karawan. To wszystko. Zostaw mnie w spokoju!}
{204} {} {Brzmisz nieprzekonuj¹co.}
{205} {} {Czego jeszcze mo¿na siê spodziewaæ na tych pustkowiach? Na pó³nocy nikt nie ma pojêcia, ¿e jest tu ca³y fort wojskowy.}
{206} {} {Wierzê ci. Chcesz st¹d uciec? Przyda³by mi siê partner.}
{207} {} {No có¿. Na twoim miejscu mówi³bym prawdê. Zostañ tutaj i nie rób zbyt wiele ha³asu.}
{208} {} {Nie wiem, czy mogê ci zaufaæ, ale nie mam nic do stracenia. Jeœli tu zostanê, to i tak mnie powiesz¹. Chocia¿ bez broni i zbroi, niewiele ci siê przydam. Czy wiesz, gdzie jest ich magazyn?}
{209} {} {Rozwi¹¿emy to po drodze. ChodŸmy.}

{210} {} {Ju¿ wam wszystko powiedzia³em. Zostaw mnie w spokoju!}
{211} {} {Twoje s³owa nie brzmi¹ przekonuj¹co.}
{212} {} {W porz¹dku, ty i ja jesteœmy w tym razem. Chcesz st¹d uciec?}
{213} {} {Usi¹dŸ tutaj i nie rób du¿o ha³asu.}
{214} {} {Jest za wczeœnie na wyjazd. Poczekaj na mój sygna³.}

{220} {} {Hej, gdzie idziemy?}
{221} {} {Nie rób ha³asu. Wkrótce siê przekonasz.}
{222} {} {Chwila. Bêdziesz musia³ tu na mnie zaczekaæ.}
{223} {} {Myœla³em, ¿e nie wrócisz. Idziemy dalej?}
{224} {} {Tak, musimy iœæ.}
{225} {} {Nie, jeszcze nie czas.}
{226} {} {Poka¿ drogê, amigo.}
{227} {} {ChodŸmy.}
{228} {} {Ok. Ale nie zapominaj o mnie.}
{229} {} {Nigdzie nie idŸ.}

{230} {} {Powinieneœ ukryæ swoj¹ broñ.}
{231} {} {Brzmi jak bardzo z³y pomys³. Okej, zrobiê to. Ale do pierwszej okazji.}
{232} {} {Nie okazuj teraz swojej wrogoœci.}
{233} {} {Bêdziemy musieli zdj¹æ teraz nasze zbroje.}
{234} {} {Ok. I tak jest mi w niej strasznie duszno.}
{235} {} {To dobrze.}
{236} {} {Czekaj. Zamierzasz podnieœæ alarm w ca³ej okolicy przez ten t³um? To ja odpadam, wola³bym spróbowaæ uciec sam.}
{237} {} {Na pewno? Twoja sprawa.}
{238} {} {Ok, zostawiê zespó³ w bezpiecznym miejscu i wrócê po ciebie.}

{250} {} {Co wiesz o tym miejscu?}
{251} {} {To miejsce jest mi nieznane. Ale myœlê, ¿e nie powinieneœ tu mieszkaæ.}
{252} {} {Rozumiem.}
{253} {} {Hermosillo to ruiny bardzo starego miasta. Nie by³o tu ¿adnych mieszkañców, dopóki wojska meksykañskie nie za³o¿y³y fortu. Oprócz starych ruin, wojska i kilku cywilów nie ma tu nic niezwyk³ego.}
{254} {} {To jest Phoenix - najwiêksze miasto, jakie znam. Ale nie myœl, ¿e mo¿esz siê tutaj rozluŸniæ. To miasto jest nieprzyjaznym miejscem do ¿ycia.}
{255} {} {Biedne obszary Phoenix. Nie zatrzymywa³ bym siê tutaj. W ka¿dym razie trzymaj broñ blisko r¹k.}
{256} {} {Kana³y? Có¿... S³uchaj, co my tu w ogóle robimy?}
{257} {} {By³em tu kilka razy, ale nigdy nie by³em w bazie Blacharzy. Nie lubi¹ nowoprzyby³ych i uwa¿aj¹ ich za ludzi drugiej kategorii. Jeœli jednak du¿o obcujesz z technologi¹, szybko znajdziesz z nimi wspólny jêzyk.}
{258} {} {Ma³a oaza na szlaku handlowym. Dos³ownie. Nadal pracuje tu pompa wodna, wiêc karawany chêtnie zatrzymuj¹ siê tu na noc. Nie bêdzie ¿adnych specjalnych problemów z lokalnymi mieszkañcami, jeœli nie zaanga¿ujesz siê w ich sprawy.}
{259} {} {To spokojne, ale na wpó³ zamkniête miasto. Uprawia siê tu g³ównie agawê i kukurydzê... Spójrz, dalej na zachód znajduje siê Puerto Penasco. By³oby mi³o tam teraz pojechaæ. To nie zajmie du¿o czasu.}
{260} {} {Nigdy nie by³em w tej okolicy. Jesteœmy strasznie daleko od znanych mi miejsc. Hej, tak nigdy nie dotrzemy do Puerto Penasco!}
{261} {} {Koœció³ kultu ognia to ju¿ lokalna atrakcja. Chocia¿ ci ludzie s¹ pobo¿ni, wiedz¹ te¿, jak trzymaæ broñ w rêkach.}
{262} {} {To miejsce jest przera¿aj¹ce. Wygl¹da na to, ¿e jakaœ para oczu wpatruje siê w nas przez szczeliny.}
{263} {} {Zartujesz sobie ze mnie? Bractwo ju¿ nie istnieje!}
{264} {} {Wszystkim tu kieruje Bractwo Stali. Wspaniali ludzie, jeœli ich nie wkurzysz. Trzymaj broñ w kaburze i uwa¿aj na jêzyk, nie lubi¹ nowicjuszy i prowokatorów.}
{265} {} {Niektórzy nazywaj¹ to miasto Piek³em. Mówi¹, ¿e ¿ywe trupy lub coœ takiego wêdruje tu po ulicach. S³uchaj, czy musimy tam iœæ?}
{266} {} {Wiêc mnisi przez lata ukrywali tê kryjówkê przed reszt¹ miasta? Cholera, jakie jeszcze sekrety trzymaj¹ w swoich ciemnych magazynach?}

{300} {} {Opowiesz mi o sobie?}
{301} {} {Niewiele mam do powiedzenia. Mów mi Jack, jeœli chcesz. Jestem tu na rozkaz karawan z pó³nocy. Potrzebowali ludzi do zbadania po³udniowych ziem. Mieli nadziejê, ¿e znajd¹ tu osady nadaj¹ce siê do handlu. Ale wygl¹da na to, ¿e pomys³ jest skazany na niepowodzenie.}
{302} {} {Dlaczego zosta³eœ zamkniêty w wiêzieniu?}
{303} {} {Wojsko nie uwierzy³o w moje wyjaœnienia i uzna³o, ¿e jestem szpiegiem. Ich zdaniem najwyraŸniej wszêdzie s¹ sami wrogowie.}
{304} {} {Jakie masz teraz plany?}
{305} {} {Wyjœæ najpierw z Hermosillo, z dala od garnizonu. A potem zobaczymy.}
{306} {} {W takim razie wynoœmy siê st¹d.}
{307} {} {Chyba muszê Ci zaufaæ. S³uchaj, muszê dostaæ siê do Puerto Penasco. Jest to ma³y stary port nad brzegiem Zatoki Kalifornijskiej. Nie dostanê siê tam sam, mo¿e uda nam siê tam dotrzeæ razem? Myœlê, ¿e tam i ty znajdziesz pracê.}
{308} {} {Co jest w tym porcie?}
{309} {} {Moi klienci. W koñcu muszê zdaæ raport z mojej pracy.}
{310} {} {Brzmi jak niez³e pieni¹dze. Swietnie, zgadzam siê.}
{311} {} {Mi³o to s³yszeæ, partnerze. Nie po¿a³ujesz.}
{312} {} {Wiêc jedziemy do Puerto Penasco...}
{313} {} {Zabiorê ciê do portu, ale jeœli to pu³apka, s³ono za to zap³acisz.}
{314} {} {Mówiê o biznesie. Nie martw siê, odpalê ci coœ z kapsli, które dostanê.}
{315} {} {Ok, jedziemy do Puerto Penasco...}
{316} {} {Przepraszam, ale nie jest mi po drodze.}
{317} {} {Ok, cokolwiek powiesz. W takim razie proponujê wspólnie dojechaæ do najbli¿szej osady, a wtedy rozstaniemy siê w pokoju.}
{318} {} {Ok.}
{319} {} {Wygl¹da na to, ¿e czas siê rozstaæ. Co zamierzasz teraz zrobiæ?}

{320} {} {Przypomnij mi, gdzie chcesz siê dostaæ?}
{321} {} {Do Puerto Penasco, to miasto portowe nad brzegiem Zatoki Kalifornijskiej.}
{322} {} {W takim razie nie tracmy czasu.}
{323} {} {Nie mogê tam teraz iœæ, przepraszam.}
{324} {} {Muszê ciê rozczarowaæ - jeden ze statków w Puerto zosta³ wysadzony w powietrze. To miejsce nie jest ju¿ przez nikogo zamieszkiwane.}
{325} {} {Zartujesz sobie ze mnie? Nie uwierzê, dopóki nie zobaczê tego na w³asne oczy.}
{326} {} {Ok, w takim razie chodŸmy do Puerto.}
{327} {} {Moim zadaniem jest ostrze¿enie ciê.}

{330} {} {Co... Co siê tutaj sta³o?}
{331} {} {Wiêc to tutaj mia³eœ spotkaæ siê z klientem?}
{332} {} {Tak, ale... Jaka si³a mo¿e zniszczyæ ca³y port?}
{333} {} {Wygl¹da na to, ¿e miejscowe „karawany” sprzedawa³y coœ naprawdê wybuchowego, prawda?}
{334} {} {Czekaj... ok... pozwól mi wyjaœniæ. Tak naprawdê to trochê sk³ama³em. Nie zosta³em zatrudniony przez karawany, ale przez Bractwo Stali. Mia³em badaæ nie szlaki handlowe, ale potencja³ militarny armii meksykañskiej. Ale co to teraz za ró¿nica? W koñcu placówka Bractwa zosta³a zniszczona!}
{335} {} {O tak, chyba nam nie zap³ac¹.}
{336} {} {Smieszy ciê to? Zostaliœmy bez kapsli. Có¿, ca³a ta podró¿ okaza³a siê bezcelowa.}
{337} {} {Co zamierzasz teraz zrobiæ?}
{338} {} {Nie wiem. Bez Bractwa te okolice podupadn¹, a bez kapsli nie ma sensu wracaæ do Phoenix. Bêdê musia³ teraz znowu wêdrowaæ po pustkowiach w poszukiwaniu pracy.}
{339} {} {Wiesz, powinniœmy trzymaæ siê razem. Potrzebujê asystenta w drodze, a i na pewno znajdziesz miejsce w Villi, gdy wszystko siê uspokoi.}
{340} {} {Myœlisz, ¿e twoi krewni mnie zaakceptuj¹? Warto spróbowaæ. Prawdopodobnie wspaniale jest mieæ w³asny dom i rodzinê. Dobra, chodŸ, partnerze.}
{341} {} {No dalej, Jack.}
{342} {} {Masz racjê. Jesteœ w kompletnej dupie. Myœlê, ¿e od teraz nasze œcie¿ki siê rozchodz¹.}
{343} {} {Zostawisz mnie w takim stanie? Po tym wszystkim, przez co razem przeszliœmy?}
{344} {} {Tak. Udowodni³eœ, ¿e nie mo¿na ci ufaæ. Daj mi moje rzeczy i idŸ w³asn¹ drog¹.}
{345} {} {Wiesz, œwietnie by³o wychodziæ z tob¹ z p³on¹cego Hermosillo. Myœlê, ¿e znajdziesz miejsce w naszej Villi, kiedy wszystko siê uspokoi.}

{350} {} {Jesteœmy. Bêdziesz musia³ trochê poczekaæ, a¿ porozmawiam z klientem.}
{351} {} {Czekaj, twoi klienci to Bractwo Stali? Ale powiedzia³eœ, ¿e...}
{352} {} {Tak, tak, k³ama³em na temat ludzi z karawany. Bractwo Stali p³aci sporo kapsli za eksploracjê po³udniowych ziem... A teraz poczekaj, zajmie to trochê czasu.}
{353} {} {[Dalej.]}
{354} {} {(Jack wraca trzy godziny póŸniej z kiepskim wyrazem twarzy)}
{355} {} {Jak posz³y negocjacje?}
{356} {} {Ci dranie nie chc¹ p³aciæ! Ich zdaniem nie uzyska³em ¿adnych wartoœciowych informacji. Musia³em im opowiedzieæ o tobie i moim ocaleniu z niewoli. I z jakiegoœ powodu byli zainteresowani twoj¹ osob¹. IdŸ porozmawiaj z Paladynem Lathamem, chce ciê widzieæ. Ja tu na razie odpocznê.}
{357} {} {Ok Jack. Do zobaczenia.}
{358} {} {Szef patrolu chcia³ siê z tob¹ widzieæ. Zapamiêtasz?}
{359} {} {Coœ siê zmieni³o. Teraz nie jesteœmy tu mile widziani. Lepiej siê st¹d wydostaæ, póki mam ca³e i zdrowe nogi.}
{360} {} {I jak z tymi kapslami? Czy otrzyma³eœ ju¿ zap³atê?}
{361} {} {Nie, zerwali mój kontrakt. Przepraszam.}
{362} {} {S-suki... I po co tak du¿o przeszed³em? Wygl¹da na to, ¿e ta podró¿ okaza³a siê bezcelowa.}
{363} {} {Co teraz zrobisz, Jack?}
{364} {} {Nie wiem. Poniewa¿ kontrakt z Bractwem zosta³ zerwany, a ja nie mam kapsli, znowu bêdê musia³ wêdrowaæ po pustkowiach w poszukiwaniu pracy.}
{365} {} {Porozmawiamy o tym póŸniej.}
{366} {} {Nie, nie mog³em znaleŸæ wspólnego jêzyka z Lathamem.}
{367} {} {Jack tymczasowo ciê opuœci³.}
{368} {} {Nie uda³o Ci siê zdobyæ ¿adnych przydatnych informacji o Hermosillo. Musisz tam wróciæ, aby zebraæ wiêcej danych o armii meksykañskiej.}