{100} {} {Widzisz Domingueza.}
{101} {} {Widzisz typowego ch³opa.}
{102} {} {Cholerne wojsko, zawsze jesteœcie zwarci i gotowi, co?}
{103} {} {Wynoœ siê, zanim rozwalê ci mózg.}
{104} {} {Stare buty jeszcze siê nie zu¿y³y.}
{105} {} {Stare gumowe sanda³y? Jak mog³em siê wczeœniej nie domyœleæ!}
{106} {} {Wygl¹da na to, ¿e uda³o ci siê rozwi¹zaæ stary problem z butami Domingueza. Dominguez bardzo siê z tego cieszy.}

{200} {} {Stój. Czego potrzebujesz?}
{201} {} {Chcê tylko porozmawiaæ. Sk¹d taka wrogoœæ?}
{202} {} {W pobli¿u jest wojsko, a ja ciê nie znam. Jeœli jesteœ tu przypadkiem, to lepiej odejdŸ.}
{203} {} {Pójdê sobie. Nie chcê spotkaæ siê z jeszcze wiêkszym oporem ze strony mieszkañców...}
{204} {} {Naprawdê odmówisz pomocy podró¿nemu z pó³nocy? Chcê tylko zapytaæ o to miasto.}
{205} {} {(podnosi groŸnie broñ) Wynoœ siê z mojego rancza.}
{206} {} {Ok, cokolwiek powiesz...}
{207} {} {Po¿a³ujesz ...}
{208} {} {To znowu ty. Mówi³em ci, ¿ebyœ opuœci³ moje ranczo.}
{209} {} {Oczywiœcie stary, nie ma problemu.}

{210} {} {Ok, pytaj. Ale potem odejdziesz.}
{211} {} {Wychodzê, spokojnie.}
{212} {} {Czy mieszkasz tu sam?}
{213} {} {Nie, w okolicy jest kilka innych spokojnych rodzin. Wojsko nie lubi cywili pod nosem.}
{214} {} {Wojsko? O kim mówisz?}
{215} {} {Nie wiesz? Dalej wzd³u¿ g³ównej autostrady znajduje siê garnizon Republiki Nowego Meksyku. Te ziemie s¹ teraz pod ochron¹ genera³a Sarabiya.}
{216} {} {Wiêc nie mogê liczyæ na schronienie w tym okolicach?}
{217} {} {Naprawdê nic nie wiesz? Pos³uchaj, kraj jest w powa¿nych tarapatach. Armia prezydenta próbuje zjednoczyæ rozproszone ziemie, a my, zwykli pokojowo nastawieni ch³opi, p³acimy za to cenê. Nawet nas o nic nie zapytali. Dlatego mieszkanie obok fortu nie jest najlepszym pomys³em. Wojsko nie toleruje samoosiedlaj¹cych siê.}
{218} {} {Jak siê tu znalaz³eœ?}
{219} {} {Mia³em znajomoœci. Fort potrzebuje jedzenia. Moje ranczo jest pod ochron¹ garnizonu, chocia¿ w zamian muszê oddawaæ prawie ca³e swoje miêso.}
{220} {} {Tak to jest. Dziêkujê za wyjaœnienie. Chyba powinienem ju¿ iœæ.}
{221} {} {Och, to bardzo wiele zmienia. Chyba powinienem siê st¹d wydostaæ. Pilnie.}
{222} {} {Genera³ Sarabiya - co o nim wiesz?}
{223} {} {Manuel Sarabiya. Widzia³em go kilka razy w konwoju i na zgrupowaniu ogólnym. Zwykle jest w Sztabie Generalnym na szczycie tej góry.}
{224} {} {Myœlê, ¿e powinienem siê z nim zobaczyæ. Mam nadziejê, ¿e ma chwilê i mo¿na go oderwaæ od pracy.}
{225} {} {Czy wolno z nim rozmawiaæ?}
{226} {} {Cywilom? Nie. I naprawdê nie chcesz stawiaæ czo³a takiej osobie. Podobno je chleb, maczaj¹c go we krwi zabitych wrogów.}
{227} {} {Ten genera³ jest godny podziwu. Muszê go koniecznie poznaæ. Bywaj.}
{228} {} {To trochê zmienia sytuacjê. Mo¿e lepiej pójdê gdzie indziej. Do widzenia.}
{229} {} {Co powiedzia³eœ o generale?}
{230} {} {Czy znasz plany tej armii dotycz¹ce Arizony?}
{231} {} {W¹tpiê, ¿eby garnizon w najbli¿szym czasie wyrusza³ do Arizony. Aby to zrobiæ, konieczne jest pokonanie ogromnej ja³owej pustyni, a przez d³ugi czas nawet wierzyliœmy, ¿e na pó³nocy nie ma ¿ycia. Ale jeœli rz¹d rozka¿e, armia rozkaz wykona.}
{232} {} {Dziêki, to by³y cenne informacje. Mam coœ do zrobienia. Bywaj.}
{233} {} {S³ysza³eœ o planach jego armii w Arizonie?}
{234} {} {Czy znasz plany genera³a Sarabiyi dotycz¹ce Arizony?}
{235} {} {Ok, pytaj.}
{236} {} {Oczywiœcie, pytaj.}
{237} {} {Jestem spokojnym wêdrowcem i nie ¿yczê ci krzywdy. Porozmawiamy, amigo?}

{238} {} {Dziêki za radio. Przynajmniej trochê upiekszy nasze szare codzienne ¿ycie.}
{239} {} {Czy mogê z tob¹ porozmawiaæ?}

{240} {} {Czy znasz starego Gallegosa? Przyby³ na pó³noc z tych stron.}
{241} {} {Czy znam Gallegosa? Co za niespodzianka. Wiêc uda³o mu siê przejœæ przez pustyniê. Myœla³em, ¿e ten szalony pomys³ jest równoznaczny z samobójstwem.}
{242} {} {Z ca³ej grupy tylko on prze¿y³. Wiêc prawie mia³eœ racjê.}
{243} {} {Gallegos i pozostali byli w rozpaczliwej sytuacji. Nowy rz¹d i wojska uciska³y ch³opów. Ludzie tacy jak ja nadal maj¹ szczêœcie, ale wielu pracuje jak niewolnicy. Ucieczka na pó³noc wydawa³a siê jedynym rozwi¹zaniem.}
{244} {} {Jednak s¹dz¹c po jego stanie, zmarnowa³ ca³e swoje zdrowie po drodze.}
{245} {} {Mogê sobie wyobraziæ, przez co przeszed³ na tej gor¹cej pustyni. Chocia¿ starzec by³ zdrajc¹ kraju, pokaza³ nam przyk³ad woli i wytrwa³oœci. Dziêkujê, ucieszy³em siê z wiadomoœci o starym przyjacielu. A przyjaciele moich przyjació³ s¹ moimi przyjació³mi.}
{246} {} {Proszê.}
{247} {} {Stary Gallegos mówi³ o ranczu Domingueza. Powiedzia³, ¿e jest dobrym i uczciwym cz³owiekiem, który nie odmówi³by podró¿nemu szklanki wody.}

{250} {} {Sk¹d masz braminy?}
{251} {} {Braminy? Co to jest?}
{252} {} {Twoje zwierzêta na ranczo.}
{253} {} {Nie wiesz, jak nazywa siê twój inwentarz? To niedorzeczne.}
{254} {} {Aaa, waki. Wy, mieszkañcy pó³nocy, zawsze wszystko komplikujecie. Kupi³em to m³ode byd³o od wojska po ich nalocie na bandytów. W ten sposób zdobywali miêso, teraz bior¹ je ode mnie. W pewnym sensie jest to po¿yczka, za któr¹ sp³acam tylko prowizjê.}
{255} {} {Czy mogê zadaæ inne pytanie?}
{256} {} {By³em po prostu ciekawy. Czeœæ.}
{257} {} {By³em w San Brahmin. Miejscowi czcili te zwierzêta jako œwiête.}
{258} {} {San Brahmin? Nigdy nie s³ysza³em. Moim zdaniem to g³upie.}
{259} {} {Mo¿e. Ale dla nich by³a to kwestia przetrwania.}
{260} {} {Do rzeczy. Nigdy nie widzia³em nic g³upszego.}
{261} {} {Twoje pytania s¹ nudne. Muszê pilnowaæ w³asnych spraw.}
{262} {} {Ju¿ wychodzê, nie martw siê.}

{270} {} {Mówi³eœ o trudnej sytuacji w Meksyku. O co chodzi?}
{271} {} {Tak. Widzisz, podczas La Gran Guerra nasza stolica zosta³a zniszczona, w wyniku czego wiele prowincji uzyska³o niepodleg³oœæ. Wiêkszoœæ z nich stworzy³a ma³e armie i broni³a swoich granic.}
{272} {} {Kontynuuj.}
{273} {} {Nie potrzebujê wiêcej szczegó³ów. Pe³ny obraz sytuacji jest ju¿ dla mnie jasny.}
{274} {} {Sam nie wiem zbyt wiele. Ale mówi siê, ¿e pó³nocne stany przeje³y kartele, które w przesz³oœci handlowa³y broni¹, narkotykami i ludŸmi. Straciwszy interes, objeli ochron¹ tamtejsze terytoria. Teraz wszystko tam jest prywatn¹ w³asnoœci¹ ich potomków.}
{275} {} {A pozosta³a czêœæ kraju?}
{276} {} {Na po³udniu kraju by³o szczególnie trudno, bo ró¿ne grupy nacjonalistów podzielily tamte terytoria na oddzielne ma³e pañstwa. Yucatan, Chiapas, Tabasco, a nawet Guerrero wci¹¿ spieraj¹ siê o to, kto tu rz¹dzi.}
{277} {} {To ciekawe. A jak maj¹ siê sprawy w pozosta³ych czêœciach kraju?}
{278} {} {Na szczêœcie wszystko siê zmieni³o wraz z nadejœciem nowego prezydenta. Zebra³ siln¹ armiê i podbi³ wszystkie œrodkowe stany od Durango po Veracruz. Obecnie toczy zaciête bitwy o terytoria na wschód od przesmyku Tehuantepec. Miejscowe plemiona s¹ zbyt dumne, aby ust¹piæ, wiêc ta wojna potrwa jeszcze z kilka lat. A pó³nocne stany tylko czekaj¹ na skrzyd³ach.}
{279} {} {Dziêki za historie.}
{280} {} {De nada. Cieszê siê, ¿e mogê podzieliæ siê histori¹ mojego ludu z ludŸmi takimi jak Ty. Kto wie, mo¿e twoi przodkowie te¿ kiedyœ pochodzili ze œrodkowego Meksyku.}
{281} {} {S³uchaj, masz wiele interesuj¹cych historii do opowiedzenia. Poœwiêcisz mi trochê czasu?}
{282} {} {Ok, Dominguez. Czeœæ.}
