{100} {} {Widzisz dziecko Domingueza.}
{101} {} {Widzisz typowego ma³ego ch³opa. I tak specyficznie pachnie.}
{102} {} {Hrrrr...}
{103} {} {Stare buty jeszcze siê nie zu¿y³y.}
{104} {} {Dzieciak jest bardzo zadowolony z nowych butów.}
{105} {} {Dziêki!}

{110} {} {Czeœæ. Czy naprawdê przyby³eœ z pó³nocy?}
{111} {} {Dziwne. Nie wygl¹dasz na dzikiego kanibala.}
{112} {} {Zawsze mówiono nam, ¿e na pó³nocy s¹ tylko dzikusy.}
{113} {} {Czy naprawdê tam na pó³nocy jecie ludzi?}
{114} {} {Genera³ Sarabiya pewnego dnia przejmie ca³¹ Arizonê.}
{115} {} {Jak czegoœ chcesz to porozmawiaj z moim padre.}
{116} {} {Lepiej trzymaj siê z daleka od naszego waka. Nie tolerujemy tu obcych.}
{117} {} {Chcesz pojeŸdziæ na wakach? To zap³aæ podwójne pesos.}
{118} {} {Naprawdê p³acisz kapslami? Pf-ha-ha-ha!}
{119} {} {G³upi mieszkaniec pó³nocy! G³upiutki z pó³nocy! Be-be-be!}
{120} {} {Mam zniszczone buty. Czy mo¿esz coœ z tym zrobiæ?}

{1110} {} {Czeœæ. Czy naprawdê przyby³aœ z pó³nocy?}
{1111} {} {Dziwne. Nie wygl¹dasz na dzikiego kanibala.}
{1112} {} {Zawsze mówiono nam, ¿e na pó³nocy s¹ tylko dzikusy.}
{1113} {} {Czy naprawdê tam na pó³nocy jecie ludzi?}
{1114} {} {Genera³ Sarabiya pewnego dnia przejmie ca³¹ Arizonê.}
{1115} {} {Jak czegoœ chcesz to porozmawiaj z moim padre.}
{1116} {} {Lepiej trzymaj siê z daleka od naszego waka. Nie tolerujemy tu obcych.}
{1117} {} {Chcesz pojeŸdziæ na wakach? To zap³aæ podwójne pesos.}
{1118} {} {Naprawdê p³acisz kapslami? Pf-ha-ha-ha!}
{1119} {} {G³upia mieszkanka pó³nocy! G³upiutka z pó³nocy! Be-be-be!}
