{100} {} {Widzisz ¿onê Domingueza.}
{101} {} {Widzisz typow¹ ¿onê rolnika.}
{102} {} {Ostro¿nie, proszê! Rozbijesz w tym wszystkie moje naczynia!}
{103} {} {Stare buty jeszcze siê nie zu¿y³y.}
{104} {} {Kobieta ma bzika na punkcie nowych butów.}
{105} {} {Wielkie dziêki! Tak trudno jest znaleŸæ dobre buty w tych odludnych regionach...}

{110} {} {Ach... co... kochanie, sprawdŸ... * ziewa * drzwi...}
{111} {} {Ech... que... Querido, mira... * ziewa * la puerta.}
{112} {} {Wynoœ siê, cholerny gringo!}
{113} {} {Vete, sucio gringo!}
{114} {} {Jestem zbyt zajêta. Porozmawiaj z moim mê¿em.}
{115} {} {Jestem zbyt zajêta, ¿eby rozmawiaæ. Porozmawiaj z moim mê¿em.}
{116} {} {Lepiej wyjdŸ. Nie lubimy obcych, którzy bezczelnie wpadaj¹ do domów z pytaniami.}

{200} {} {Ach, przepraszam za mê¿a. Nadal jest niespokojny po nocy, gdy patrol wojskowy w³ama³ siê do naszego domu i spêdzi³ tu noc.}
{201} {} {Czy wojsko nie powinno was chroniæ?}
{202} {} {O tak, przez wiêkszoœæ czasu nam nie przeszkadzaj¹, poniewa¿ dostarczamy miêso garnizonowi. Sam genera³ podpisa³ dekret o naszej ochronie. Ale ci ¿o³nierze byli nadêci poœcigiem jakiegoœ szpiega, wiêc pozwolili sobie na zbyt wiele. W koñcu nawet go z³apali, ale skoñczyli brudni po szyjê w b³ocie.}
{203} {} {Czego od was chcieli?}
{204} {} {Myœleli, ¿e szpieg mo¿e siê ukrywaæ gdzieœ u nas, ale w koñcu dogonili go na pustyni. W drodze powrotnej zatrzymali siê, ¿eby odpocz¹æ, zjeœæ i napiæ siê wody. To po prostu bardzo nieprzyjemna historia.}
{205} {} {[Dalej.]}
{206} {} {Dodatkowo, jeden z nich ukradkiem wzi¹³ nasze radio. Ze niby z jego pomoc¹ mo¿emy pods³uchiwaæ transmisje wojskowe. Co za bzdury!}
{207} {} {To naprawdê straszne co siê tu dzieje. Myœlê, ¿e czas st¹d uciec tak szybko, jak tylko potrafiê. Do widzenia, senora.}
{208} {} {Co siê sta³o z tym szpiegiem?}
{209} {} {Dlaczego potrzebujesz radia?}

{210} {} {Jestem zbyt zajêta, ¿eby rozmawiaæ. Porozmawiaj z moim mê¿em.}
{211} {} {Do widzenia.}

{220} {} {Co siê sta³o z tym szpiegiem?}
{221} {} {No có¿, zosta³ zabrany do wiêzienia w garnizonie. To wszystko, co wiem.}
{222} {} {Rozumiem.}
{223} {} {Dlaczego potrzebujesz radia?}
{224} {} {Czasami, gdy pogoda jest szczególnie dobra, mo¿emy z³apaæ wiadomoœci z Los Mochis. Powstaje tam ma³a osada pod nowym rz¹dem. Poza tym chcemy wiedzieæ, co siê dzieje w kraju.}
{225} {} {Rozumiem.}
{226} {} {Czy to twoje radio?}
{227} {} {To naprawdê ono! Sk¹d je masz?}
{228} {} {Nic skomplikowanego. Po prostu wchodzisz do fortu i bierzesz wszystko, co chcesz.}
{229} {} {Có¿, trzeba by³o trochê pokombinowaæ, ale siê uda³o.}
{230} {} {Niesamowite! Próbowaliœmy porozmawiaæ z kimœ z garnizonu, ale nawet nas nie wpuœcili. Chcieliœmy nawet zapomnieæ o tej historii. Bardzo dziêkujê!}
{231} {} {De nada, seœora.}
{232} {} {Nie ma za co.}