{100}{}{Widzisz komputer.}
{101}{}{Widzisz stary komputer. Jego klawiatura jest po hiszpañsku.}

#Dialog
{200}{}{WprowadŸ polecenie.}
{201}{}{Zakoñcz sesjê.}
{202}{}{Powrót.}

{210}{}{Raport kwaterunkowy Fortu.}
{211}{}{(Raport 2162 do Sztabu Generalnego w Monterrey. Oddzia³ genera³a Sarabiyi wkroczy³ do opuszczonego Hermosillo i za³o¿y³ tymczasow¹ bazê. Tydzien póŸniej nadszed³ rozkaz sta³ego zakwaterowania.)}
{212}{}{Fort w El Paso.}
{213}{}{(Znajdujesz dane transportów i kody komunikacyjne do innego podobnego fortu w El Paso. Wygl¹da na to, ¿e toczy siê tam teraz prawdziwa wojna.)}
{214}{}{Cele i zadania.}
{215}{}{(G³ównym zadaniem jest utrzymanie pozycji dla ekspansji nowego pañstwa.)}
{216}{}{Ocena sytuacji.}
{217}{}{(Wed³ug ostatnich doniesieñ, g³ównym zagro¿eniem dla fortu jest Bractwo Stali w ruinach Puerto Peñasco i osada Blacharzy w pobli¿u przedwojennego Tucson. W forcie szkoli siê zwiadowców do zbadania jak silni s¹ potencjalni wrogowie.)}
{218}{}{Skopiuj dane z komputera na holodysk.}
{219}{}{Archiwum danych skopiowane.}
{220}{}{(Wszystko jest po hiszpañsku. Nic z tego nie rozumiesz.)}