{100} {} {Widzisz Dianê.}
{101} {} {Widzisz ³ys¹ kobietê o bardzo zamyœlonym spojrzeniu.}
{102} {} {Och, oczywiœcie, proszê.}
{103} {} {Mi³o ciê widzieæ.}

{110} {} {Hej, czy ju¿ jesteœmy?}
{111} {} {Du¿e miasto. Prawie jak Hub. Ech, wracaj¹ wspomnienia...}
{112} {} {To miasto jest jak wiêzienie. Ciekawe, czy miejscowi s¹ z tego zadowoleni?}
{113} {} {Miasto koczowniczych pasterzy. Co za niespodzianka.}
{114} {} {Dostajê gêsiej skórki od tego miejsca.}
{115} {} {Nie podoba mi siê to miejsce. B¹dŸ ostro¿ny.}
{116} {} {Czy to Twoja rodzinna wioska? Twoja ciê¿ka praca jest niesamowita.}
{117} {} {Nie wierzê w³asnym oczom. To legendarni Desert Rangers!}
{118} {} {Nie s¹dzisz, ¿e poszlismy za daleko na po³udnie?}
{119} {} {Wreszcie wyszliœmy z tego piek³a.}
{120} {} {Hmm. Wydaje siê, ¿e miejscowi nie lubi¹ tu obcych.}

# Pierwszy dialog
{200} {} {Na szczêœcie jest tu ktoœ z ludzk¹ twarz¹!}
{201} {} {Kim jesteœ?}
{202} {} {Jestem Diana. Pochodzê od Wyznawców Apokalipsy i by³am w drodze do osady Casa Nueva. Ale mój konwój zosta³ zaatakowany przez rozpruwaczy. Z³apali mnie i zabrali tutaj. Nie wiem nawet, czy ktokolwiek z mojej grupy prze¿y³.}
{203} {} {Przykro mi, Diana.}
{204} {} {Rozumiem.}
{205} {} {Co tu robisz? Czy ciebie te¿ z³apali rozpruwacze?}
{206} {} {W³aœciwie to jestem tu przez przypadek. Mieszkañcy mojej wioski zostali zabrani przez handlarzy niewolników i ich szukam.}
{207} {} {Hmm. S³ysza³am, ¿e na wschodzie rozwija siê handel niewolnikami. Ale nie s¹dzê, ¿e znajdziesz tu kogokolwiek poza mutantami.}
{208} {} {Wiêc zamierzasz siê st¹d wydostaæ?}
{209} {} {To nie ma znaczenia. Czy zamierzasz st¹d uciec?}
{210} {} {Bractwo Stali wys³a³o mnie do pomocy.}
{211} {} {Tak, Bractwo nigdy nie opuszcza swoich braci i sióstr. Tego mo¿esz byæ pewien.}
{212} {} {Wiêc zamierzasz siê st¹d wydostaæ?}
{213} {} {Obawiam siê, ¿e nie bêdzie ³atwo siê st¹d wydostaæ. Jeœli spróbujemy opuœciæ katedrê, zostaniemy od razu z³apani przez stra¿ników. A nawet jeœli znajdziemy siê na zewn¹trz, rozpruwacze nas rozerw¹ na strzêpy.}
{214} {} {Tutaj trzeba byæ bardziej przebieg³ym.}
{215} {} {Dobrze. Nie chcê rozlewu krwi. Wydaje siê, ¿e Levi te¿ nie chce. Obieca³, ¿e pozwoli nam odejœæ, jeœli pomogê mu w jego badaniach.}
{216} {} {Czy jest jakiœ sposób, aby z nimi walczyæ?}
{217} {} {Nie jestem fank¹ rozlewu krwi. Levi obieca³, ¿e nas wypuœci, jeœli pomogê mu w jego badaniach. Ale jeœli naprawdê jesteœ g³odny bitwy, pancerz wspomagany bedzie tu niezbêdny.}
{218} {} {Muszê oceniæ sytuacjê i pomyœleæ.}
{219} {} {}
{220} {} {Oczywiœcie. Ale nie zostawiaj mnie tutaj. Dzieci z Casa Nueva czekaj¹ na moje lekcje biologii.}
{221} {} {Ok...}

# Powtarzajacy siê dialog
{250} {} {I co z tego? Jaki jest Twój plan?}
{251} {} {Poczekaj na moje instrukcje.}
{252} {} {Co mówi Levi?}

{260} {} {Powiedz mi, co siê tutaj dzieje.}
{261} {} {Ok. Co dok³adnie chcia³byœ wiedzieæ?}
{262} {} {Myœlê, ¿e to wszystko.}

# - o twojej misji
{270} {} {Interesuje mnie twoja misja.}
{271} {} {By³am w drodze do Casa Nueva. Ta osada potrzebuje naukowców i nauczycieli. Kilku Obserwatorów ju¿ prowadzi tam badania.}
{272} {} {To prawdopodobnie wszystko.}
{273} {} {Czy mo¿esz mi pokazaæ, gdzie to jest?}
{274} {} {Oczywiœcie. Otwórz mapê, poka¿ê ci...}
{275} {} {Dziêki.}
{276} {} {Tak siê z³o¿y³o, ¿e by³em w tym mieœcie. Ladne miejsce.}
{277} {} {Naprawdê? Wspaniale. Tym szybciej siê tam dostaniemy po wszystkim.}
{278} {} {Wrócimy do tego... jeœli st¹d wyjdziemy.}
{279} {} {Casa Nueva zosta³a zbudowana przez niewolników, a na plantacjach pracuj¹ peoni. Naukowcy paso¿ytuj¹ na pracy innych ludzi.}
{280} {} {Tak, trudno jest po³¹czyæ naukê z prac¹ fizyczn¹. I zdecydowanie niew³aœciwe jest uciskanie kogoœ. Ale staramy siê uczyniæ œwiat lepszym miejscem. Poza tym niewolnicy s¹ wykorzystywani nie przez nas, ale przez najemników Bractwa Stali.}
{281} {} {Ok, to brzmi sensownie.}
{282} {} {Tak jakby to coœ zmienia³o.}

{290} {} {Kim s¹ ci Wyznawcy Apokalipsy?}
{291} {} {Có¿, jesteœmy czymœ w rodzaju fundacji charytatywnej. Uczymy ludzi czytaæ i pisaœ, leczymy choroby i edukujemy ich przedwojenn¹ wiedz¹.}
{292} {} {Wiêc chcecie przywróciæ Stary Swiat?}
{293} {} {Niezupe³nie. Mówi¹, ¿e historia lubi siê powtarzaæ, ale nie naœladuje na ka¿dym kroku. Innymi s³owy, Starego Swiata nie mo¿na przywróciæ takim, jakim by³. I nie potrzebujemy go.}
{294} {} {Ugh, myœla³em, ¿e zwariowa³aœ.}
{295} {} {Rozumiem.}
{296} {} {Oszala³aœ! Stary Swiat upad³ z powodu tej wiedzy.}
{297} {} {Nie s¹dzê. Nie chodzi o sam¹ wiedzê, chodzi o jej wykorzystanie. Dbamy o to, aby nikt nie powtórzy³ b³êdów Starego Swiata.}
{298} {} {No có¿. Tak jakbyœ mog³a œledziæ ka¿dego.}
{299} {} {Twoje cele s¹ szlachetne i czyste. Mam nadziejê, ¿e inni rozumiej¹ je w ten sam sposób.}
{300} {} {Jak wpad³aœ w zasadzkê?}
{301} {} {Rozpruwacze nas zaatakowa³y. Przygotowa³y sprytn¹ zasadzkê, stworzy³y zas³onê dymn¹ i wyci¹gnê³y mnie z grupy. Uratowali mnie ludzie Leviego, którzy akurat byli blisko, a potem zabrali tutaj.}
{302} {} {I nadal mu za to dziêkujesz?}
{303} {} {Nie wierzê, ¿e ci ludzie maj¹ z³e serca. Levi po prostu pod¹¿a œcie¿k¹, która wydaje mu siê w³aœciwa.}
{304} {} {A co z twoimi towarzyszami?}
{305} {} {Wiêc Rozpruwacze dzia³a³y na rozkaz Leviego?}
{306} {} {Prawdopodobnie tak. Levi to dla nich rodzaj Boga... lub Diab³a. Próbuj¹ go zadowoliæ i wykonuj¹ proste polecenia. Ale to tylko moje przypuszczenia.}
{307} {} {Co siê sta³o z twoimi towarzyszami?}
{308} {} {Dru¿yna sk³ada³a siê z kilku cz³onków Bractwa Stali. Na czele dru¿yny sta³ paladyn Barkley. Po porwaniu nic o nich nie s³ysza³am. Nie wiem nawet, czy ¿yj¹, czy nie ¿yj¹.}
{309} {} {Rozumiem.}

{310} {} {Wspomina³aœ o Bractwie Stali. Opowiedz o nim.}
{311} {} {Có¿, jest to zamkniêta organizacja wojskowa w Kalifornii. Miejscowi maj¹ z nimi napiête stosunki, wiêc zabrali mnie do dru¿yny z wielkim niezadowoleniem.}
{312} {} {Co oni robi¹?}
{313} {} {W wiêkszoœci nic. Ostatnio Bractwu wyraŸnie brakuje energii. Zaczeli wykupywaæ wszystkie baterie atomowe w regionie. To tak¿e najlepsi specjaliœci w dziedzinie broni energetycznej i zaawansowanych przedwojennych technologii. Ale praktycznie wszystko zachowuj¹ dla siebie i nie chc¹ siê tym dzieliæ ze œwiatem zewnêtrznym.}
{314} {} {Rozumiem. Doœæ o tym Bractwie.}
{315} {} {Wiêc co robi¹ w Arizonie?}
{316} {} {Myœlê, ¿e zbieraj¹ równie¿ i tu technologie i Ÿród³a energii. Wiele przedwojennych miejsc pozostaje wci¹¿ nieodkrytych w Arizonie.}
{317} {} {Czy wiesz, gdzie jest ich baza?}
{318} {} {Ich jedyna placówka znajduje siê na starym okrêcie wojennym w Puerto Penasco, na wybrze¿u Zatoki Kalifornijskiej.}
{319} {} {Co robi¹ w Arizonie?}
{320} {} {Dziêki. To jest to, czego potrzebowa³em.}

#o tym mieœcie
{330} {} {Co wiesz o tym mieœcie?}
{331} {} {Przed wojn¹ nazywa³o siê Mexicali. Du¿e miasto graniczne. Czerwoni zniszczyli je, bombarduj¹c wiele lokalnych fabryk.}
{332} {} {Ok, niewa¿ne.}
{333} {} {Ci rozpruwacze. Kim oni s¹?}
{334} {} {To s¹ mieszkañcy Mexicali, którzy prze¿yli bombardowanie atomowe w 2077 roku. Dusze tych, którzy kiedyœ byli ludŸmi. Jest mi niezmiernie przykro z powodu tych nieszczêœników. Dla nich ruiny sta³y siê wiecznym piek³em.}
{335} {} {Rozumiem. Nie mówmy ju¿ o tak smutnych rzeczach.}
{336} {} {Dlaczego buduj¹ totemy z koœci?}
{337} {} {Rozpruwacze zbieraj¹ siê jak stada bestii. Ka¿da grupa ma swoje terytorium, a totemy s¹ swego rodzaju znakiem.}
{338} {} {Rozumiem. Doœæ o rozpruwaczach.}
{339} {} {Czy maj¹ jakieœ s³abe punkty? Muszê wiedzieæ, gdzie celowaæ, jeœli znów siê na nich natknê.}
{340} {} {Có¿, s¹ doœæ szybkie, wytrwa³e i czêsto siê regeneruj¹. Lepiej bêdzie trzymaæ siê od nich z daleka. Ale przeciwko t³umowi broñ masowego ra¿enia zawsze by³a najskuteczniejsza. Jednak nie zapominaj, ¿e kiedyœ te¿ byli ludŸmi.}
{341} {} {Nie martw siê, to tylko notatki na wypadek zasadzki.}
{342} {} {Czy ty chronisz te bestie? Jesteœ g³upia, Diano.}
{343} {} {Zastanawiam siê, po co im totemy z koœci?}
{344} {} {Maj¹ prawie sto lat?! Jak to?}
{345} {} {Czy ty twierdzisz, ¿e maj¹ prawie sto lat?}
{346} {} {To stara historia. Chcesz j¹ w ca³oœci us³yszeæ?}
{347} {} {Nie. Zastanawiam siê tylko, kim oni s¹.}
{348} {} {Tak. To tylko historia, ale chcê wiedzieæ wiêcej.}
{349} {} {Niedaleko st¹d by³o laboratorium, w którym przeprowadzano eksperymenty z bardzo niebezpiecznym wirusem. Eksplozja j¹drowa uszkodzi³a kompleks, powoduj¹c, ¿e wirus uwolni³ siê i lata³ po po³owie œwiata.}
{350} {} {Kontynuuj.}
{351} {} {To miasto zosta³o szybko pokryte truj¹c¹ chmur¹. Wirus, w po³¹czeniu z promieniowaniem, mia³ dziwny efekt, daj¹c mieszkañcom swego rodzaju nieœmiertelnoœæ. To prawda, nie s¹dzê, ¿e s¹ z tego powodu szczêœliwi. A tak przy okazji, nie tylko ghule by³y wynikiem mutacji, ale tak¿e wszystkie dzikie zwierzêta w okolicy.}
{352} {} {Jaki to by³ rodzaj wirusa?}
{353} {} {Wirus Wymuszonej Ewolucji zwany FEV stworzony przez cz³owieka. Tajny projekt wojskowy. Ju¿ w naszych czasach Mistrz u¿y³ FEV do stworzenia armii super mutantów. Ludnoœæ Leviego jest wynikiem tych nieludzkich eksperymentów.}
{354} {} {S¹dz¹c po jego oddziale, wirus mia³ wiele skutków ubocznych.}
{355} {} {Mistrz przeprowadzi³ wiele eksperymentów z ró¿nymi wynikami. Wielu zmar³o, zanim doszed³ do równowagi. Ale nawet jego najlepsi mutanci musz¹ okresowo przyjmowaæ pewne substancje, aby ustabilizowaæ mutagen. Ponadto wiele mutantów ma swoje unikalne cechy. Ogólnie wszystko jest bardzo skomplikowane.}
{356} {} {Rozumiem. Dziêki za historie.}

{360} {} {Opowiedz mi o tym pancerzu wspomaganym.}
{361} {} {Mia³ zostaæ zabrany do bazy wojskowej w Puerto Penasco. Kiedy rozpruwacze zaatakowali konwój, nikt nie zd¹¿y³ skorzystaæ z tego cudu przedwojennej technologii.}
{362} {} {Czy on w ogóle dzia³a?}
{363} {} {Prawie. Podczas transportu zosta³ trochê poobijany, ale g³ówne systemy dzia³aj¹ normalnie. Problem w tym, ¿e niektóre czêœci zosta³y rozebrane.}
{364} {} {Czego dok³adnie brakuje w tej zbroi?}
{365} {} {Reaktor j¹drowy zosta³ zdemontowany w celu badañ. NajwyraŸniej Levi rozwa¿a alternatywne sposoby wykorzystania tego Ÿród³a energii.}
{366} {} {Coœ jeszcze?}
{367} {} {Levi trzyma przy sobie g³ówny procesor, ¿eby nikt nie móg³ nieautoryzowanie odpaliæ zbroi.}
{368} {} {Czy ten pancerz ma he³m?}
{369} {} {Tak, ale zgubi³ siê gdzieœ podczas transportu. Najprawdopodobniej w miejscu, w którym zaatakowa³y nas rozpruwacze.}
{370} {} {Teraz jest dla mnie jasne, czego mam szukaæ.}
{371} {} {Ok, pomyœlê o tym.}
{372} {} {Znalaz³em ten he³m w pobli¿u pomnika. Czy to ten?}
{1372} {} {Znalaz³am ten he³m w pobli¿u pomnika. Czy to ten?}
{373} {} {Tak, to on. Po prostu pod³¹cz go do zbroi.}
{374} {} {Dobrze.}

{380} {} {Co wiesz o Levim i jego kulcie?}
{381} {} {Niewiele. Ale to wystarczy, by go szanowaæ i nienawidziæ.}
{382} {} {Doœæ o kulcie.}
{383} {} {Kim on jest?}
{384} {} {Levi by³ jednym ze s³ugusów Mistrza, jak Morfeusz i inni. Szed³ za swoim przywódc¹ do koñca, a¿ kult zosta³ zniszczony w 2161 roku.}
{385} {} {Czy on te¿ jest mutantem?}
{386} {} {Levi wzi¹³ mutagen jako czêœæ inicjacji. A teraz cierpi na skutki uboczne. Dlatego nosi maskê, aby zmniejszyæ szkodliwe dzia³anie truj¹cego powietrza. Chocia¿ jego podw³adni tego nie potrzebuj¹.}
{387} {} {Co sprowadza go do tych ruin?}
{388} {} {Widzisz, Kalifornijczycy wypêdzali ostatnio takich jak on. Myœlê, ¿e te ruiny wyda³y siê Leviemu bezpieczn¹ przystani¹ od reszty œwiata. W koñcu ani jedna normalna osoba nie wejdzie sama w takie radioaktywne b³oto. Có¿, z wyj¹tkiem ciebie i mnie.}
{389} {} {Czego chce od ciebie Levi?}
{390} {} {Potrzebuje moich umiejêtnoœci naukowych do „projektu uzupe³niaj¹cego”. Tak to nazywa.}
{391} {} {Projekt czego?}
{392} {} {Projekt uzupe³niaj¹cy - co to znaczy?}
{393} {} {To trudne do wyjaœnienia, a i tak nie powiedziano mi wszystkiego. Widzisz, spo³ecznoœæ Leviego jest owocem starego eksperymentu. Chcesz poznaæ szczegó³y?}
{394} {} {Nie mam teraz czasu na historie. Muszê pomyœleæ o tym, jak wydostaæ siê z tego piek³a.}
{395} {} {Nie, pomiñmy tê historiê. Czego dok³adnie chce Levi?}
{396} {} {Tak, powiedz mi, jakiego rodzaju eksperymentu?}
{397} {} {Kilka lat temu na zachodzie rozkwit³ kult Mistrza. U¿y³ przedwojennego wirusa do stworzenia w³asnej armii super mutantów. Stwórca zosta³ zabity, a jego armia uciek³a w ró¿nych kierunkach.}
{398} {} {Czy lud Leviego jest pozosta³oœci¹ tego kultu?}
{399} {} {Tak. Ale eksperymenty Mistrza mia³y bardzo szeroki zakres konsekwencji. Zarówno udane, jak i œmiertelne. Wszystkie te mutanty cierpi¹ na takie czy inne wady.}
{400} {} {A Levi próbuje ich uleczyæ?}
{401} {} {Najpierw musimy ustabilizowaæ wirusa we krwi tych ludzi. Niektóre z tych istot marniej¹ z powodu braku wirusa, inne z powodu jego nadmiaru, a wszystkie maj¹ swoje indywidualne patologie.}
{402} {} {Kontynuuj.}
{403} {} {Ciekawe jest równie¿ to, ¿e Levi próbuje oswoiæ dzikie rozpruwacze, uczyniæ je swoimi s³ugami, chocia¿ ich natura znacznie ró¿ni siê od ghuli Leviego.}
{404} {} {Co siê stanie na koñcu?}
{405} {} {Coœ jak ma³e imperium mutantów. Radioaktywny raj dla elity. Scie¿ka tutaj bêdzie zamkniêta dla zwyk³ego smiertelnika.}
{406} {} {Ciekawe. Ale wróæmy. Czego dok³adnie chce od ciebie Levi?}
{407} {} {Levi domaga siê stabilizatora wirusa dla swojego stada. Faktem jest, ¿e niektórzy jego ludzie nie maj¹ mutagenu, wiêc musz¹ przyjmowaæ leki stymuluj¹ce lub znosiæ ból. Inni natomiast szukaj¹ sposobu na st³umienie wirusa, aby w koñcu nie zamieniæ siê w marchewkê.}
{408} {} {Brzmi zbyt skomplikowanie, bior¹c pod uwagê ba³agan wokó³ niego.}
{409} {} {Um, zapomnij o tym.}
{410} {} {Dobrze. Na szczêœcie Levi przywióz³ ze sob¹ ma³e laboratorium. G³ównym problemem jest brak syntetyzowanych substancji, zw³aszcza benzenu i pestycydów. Gdybym mia³a wiêcej surowców, znalaz³abym rozwi¹zanie problemu mutagenów.}
{411} {} {To szaleñstwo! Chcesz wyleczyæ tych mutantów? Co powiesz na rozpylenie mutagennej trucizny w ca³ym tym diabelskim koœciele?}
{412} {} {Rozumiem twoje niezadowolenie. Jednak tych ludzi równie¿ mo¿na zrozumieæ. Wiele przeszli. Mo¿e moja pomoc zmieni je na lepsze.}
{413} {} {No có¿. Ja jednak nalegam na truciznê. Jeœli to mo¿liwe.}
{414} {} {Mo¿e. Naprawdê mam nadziejê, ¿e nie pomylisz siê w swoich obliczeniach.}
{415} {} {Jeœli Ci siê uda, Levi nas puœci. Warto spróbowac. Gorzej nie bêdzie.}
{416} {} {Dobrze. Moje serce zamiera, gdy próbujê sobie wyobraziæ, przez co przeszli ci ludzie.}
{417} {} {Jednak by³oby ³atwiej ich wszystkich zastrzeliæ. W ka¿dym razie, co jest potrzebne do mutagenu?}
{418} {} {Ok. Ale gdzie mo¿na zdobyæ te wszystkie substancje?}
{419} {} {Nosi³am ze sob¹ torbê z chemikaliami. Wszystko tam by³o. Ale lud Leviego nie móg³ jej znaleŸæ. Rozpruwacze musia³y zaci¹gn¹æ moj¹ torbe do ruin.}
{420} {} {Có¿, i tak zawsze szukam kogoœ lub czegoœ.}
{421} {} {Proszê, musisz znaleŸæ t¹ torbê. Zasadzka by³a w pobli¿u pomnika na pi¹tej ulicy. To niedaleko st¹d na zachód.}
{422} {} {Poczekaj na mój powrót.}
{423} {} {Ok. Ale nie ¿a³uj tego póŸniej.}
{424} {} {Przypomnij mi, co mam znaleŸæ?}

{430} {} {Oto twoja torba.}
{431} {} {Dziêki Bogu! Ju¿ siê ba³am, ¿e ghule j¹ wypatroszy³y. Chwila... Tak, coœ tu jest. Najpierw muszê przeprowadziæ kilka eksperymentów. Po³ó¿ zestaw na tym stole laboratoryjnym...}
{432} {} {[Dalej.]}
{433} {} {... Wiêc... Hmm... Podaj mi tê probówkê... Spójrz, zmienia kolor na zielony. Teraz sprawa jest prosta - trzeba przeprowadziæ badania kliniczne. Na szczêœcie mamy ochotników.}
{434} {} {Chcesz u¿yæ tych rozpruwaczy? Wygl¹da na to, ¿e nie mamy innego wyboru.}
{435} {} {Jesteœ prawdziw¹ sadiug¹, Diano. Zaczynam ciê lubiæ.}
{436} {} {Hmm... Jakie to interesuj¹ce. Zwróæ uwagê, ¿e osoby badane s¹ spokojniejsze. Teraz przyjrzê siê ich komórkom krwi pod mikroskopem... Tak... Hej, zrobiliœmy to! Myœlê, ¿e w³aœnie tego chcia³ Levi.}
{437} {} {Dobra wiadomoœæ. Porozmawiam z Levim.}
{438} {} {Tak siê sk³ada, ¿e mam ju¿ twoje rzeczy.}
{439} {} {Nie mo¿esz nikogo zabijaæ. Nie mogê przetestowaæ mutagenu na martwych. }

{450} {} {Przygotuj siê. Wychodzimy.}
{451} {} {Na pewno? Nie chcê ponownie zostaæ z³apana w ogieñ krzy¿owy.}
{1451} {} {Na pewno? Nie chcê ponownie zostaæ z³apana w ogieñ krzy¿owy.}
{452} {} {Masz racjê, najpierw muszê zrobiæ zwiad. Nied³ugo wrócê.}
{453} {} {Levi nie ¿yje. W¹tpiê, aby reszta mutantów nas tu tolerowa³a.}
{454} {} {Serio Levi nie ¿yje? Jakie to smutne... Có¿, teraz w œwi¹tyni naprawdê nie jest bezpiecznie. W¹tpiê, ¿ebym siê tutaj przyda³a.}
{455} {} {Dok³adnie. Musimy siê st¹d wydostaæ. I to tak szybko, jak to mo¿liwe.}
{456} {} {W³aœciwie to nie s¹ dok³adne informacje. Poczekaj, a¿ sprawdzê.}
{457} {} {To niebezpieczne. Ale z ka¿d¹ godzin¹ staje siê to jeszcze bardziej niebezpieczne. Musimy siê œpieszyæ, jeœli chcemy prze¿yæ. ChodŸmy.}
{458} {} {Naprawdê mam nadziejê, ¿e wiesz, co robisz.}
{459} {} {Zaufaj mi. Wyprowadzê ciê z tego piek³a.}
{460} {} {Hmm. Twoje s³owa sprawiaj¹, ¿e myœlê. Poczekaj chwilê. Sprawdzê teren.}
{461} {} {Levi odda³ nam wolnoœæ. Mo¿emy odejœæ.}
{462} {} {Dziêki Bogu! Wierzy³am, ¿e Levi jest dobrym cz³owiekiem i dotrzyma s³owa.}
{463} {} {Wiêc spakuj swoje rzeczy. Ju¿ czas.}
{464} {} {Bêdziemy musieli trochê poczekaæ z odejœciem. Muszê siê przygotowaæ do podró¿y.}

# Przesylka
{500} {} {Dok¹d idziemy, dowódco?}
{501} {} {Po prostu idŸ za mn¹.}
{502} {} {Gdzie chcesz iœæ?}
{503} {} {Do Casa Nueva.}
{504} {} {Dlaczego?}
{505} {} {Jest tam placówka moich braci i sióstr. Muszê im pomóc w miejscowej szkole.}
{506} {} {Czy mo¿esz pokazaæ mi tê lokalizacjê na mapie?}
{507} {} {Oczywiœcie. Otwórz mapê... Och, masz Pip-Boya. Co za niespodzianka. Mówisz, ¿e to relikwia? Dobrze, dobrze. To w³aœnie tutaj, na pustyni Sonora na po³udniowym wschodzie.}
{508} {} {Rozumiem. ChodŸmy.}
{509} {} {Ale dlaczego chcesz tam iœæ?}

{510} {} {Diano, musimy siê rozstaæ.}
{511} {} {Tak szybko? Ech, zawsze mia³am pecha z d³ugotrwa³ymi zwi¹zkami.}
{512} {} {Nic nie mo¿na na to poradziæ. Zwróæ moje rzeczy i idŸ, dok¹d chcesz.}
{513} {} {Masz racjê. Lepiej trzymajmy siê razem.}
{514} {} {Przestañ ju¿ odpoczywaæ. Czas iœæ dalej.}
{515} {} {Cokolwiek powiesz, dowódco.}
{516} {} {ChodŸmy.}
{517} {} {Muszê ciê zostawiæ na chwilê. Poczekaj tu.}
{518} {} {Nie zostawisz mnie, kochanie? Ok, rób jak chcesz.}
{519} {} {Poczekaj tutaj.}
{520} {} {Przepraszam, teraz rozumiem, ¿e jednak ciê potrzebujê. Pójdziesz ze mn¹?}
{521} {} {Chodzi o broñ. Lepiej j¹ ukryæ.}
{522} {} {Och, martwisz siê, ¿e komuœ mo¿e staæ siê krzywda. To mi³e z twojej strony.}
{523} {} {Czy nie mo¿esz przestaæ byæ tak sarkastyczna?}
{524} {} {Nie, g³upcze, nie chcê po prostu problemów.}
{525} {} {Zdejmij swoj¹ zbrojê.}
{526} {} {Nie rozbierzesz mnie do naga, prawda? Chocia¿ czasami chcia³abym poczuæ siê wolna.}
{527} {} {Um, nie mia³em tego na myœli.}
{528} {} {Wróci³eœ po mnie? To takie romantyczne.}
{1528} {} {Wróci³aœ po mnie? To takie romantyczne.}

{530} {} {Zosta³em ranny. Zrób coœ!}
{531} {} {Przepraszam, ale musisz uzbroiæ siê w cierpliwoœæ. Twoje rany nie s¹ na tyle powa¿ne, aby zmarnowaæ nasze ostatnie lekarstwa.}
{532} {} {Czy w ten sposób Obserwatorzy traktuj¹ swoich pacjentów? Bêdê o tym pamietaæ na przysz³oœæ.}
{533} {} {Tak, masz racjê. Zachowaj leki na nag³e wypadki.}
{534} {} {Twoje obrazenia nie s¹ œmiertelne, ale bêd¹ Ci bardzo przeszkadzaæ w drodze. Bêdziemy musieli przeprowadziæ ma³¹ operacjê. Tylko, ¿e ja mam ma³o praktyki...}
{535} {} {Zrób coœ, ju¿!}
{536} {} {Ufam ci, doktorze.}
{537} {} {Mój Bo¿e, jesteœ ca³y pokryty krwi¹! To bardzo Ÿle. Po³ó¿ siê, bêdê musia³a u¿yæ na tobie ostatnich lekarstw...}
{1537} {} {Mój Bo¿e, jesteœ ca³a pokryta krwi¹! To bardzo Ÿle. Po³ó¿ siê, bêdê musia³a u¿yæ na tobie ostatnich lekarstw...}
{538} {} {Nie pozwól mi zasn¹æ, doktorze...}
{539} {} {Bêdziemy musieli uzbroiæ siê w cierpliwoœæ. Nie przejmowa³eœ siê ranami innych, prawda? Poczuj, jak to jest. Mo¿e w ten sposób nauczysz siê ¿yczliwoœci.}
{540} {} {Podoba Ci siê to? Zdecydowa³aœ siê mnie opuœciæ z powodu z³ej reputacji? Dobrze, zapamiêtam to, suko.}
{541} {} {Ok. Ale jeœli umrê, bêdzie to twoja wina.}
{542} {} {S³uchaj, nie chcê nikogo uraziæ, ale twoje ha³aœliwe towarzystwo tylko nas spowolni. A ja muszê jak najszybciej dostaæ siê do Casa Nueva.}
{543} {} {Wiêc obejdziesz siê bez mojej pomocy. Bywaj.}
{544} {} {Porozmawiam z nimi. Poczekaj chwilê.}

{550} {} {Porozmawiajmy.}
{551} {} {Co chcesz wiedzieæ?}
{552} {} {Niewa¿ne, zapomnij.}

{560} {} {Dlaczego jesteœ taka podekscytowana moim Pip-Boyem?}
{561} {} {Có¿, to stara technologia. Takie komputery rozdawano tylko mieszkañcom specjalnych schronów. Nie spodziewa³am siê, ¿e znajdê coœ takiego z dala od du¿ych miast.}
{562} {} {Tak, to urz¹dzenie pochodzi z Krypty 27. S¹ tam teraz tylko duchy.}
{563} {} {Haha, dobry ¿art.}
{564} {} {Kontynuujmy.}
{565} {} {Czekaj. Chcesz powiedzieæ, ¿e ta Krypta jest gdzieœ w Arizonie?}
{566} {} {Poka¿ mi oznaczenia na odwrocie... Ok. Tak, pochodzi z Krypty 27. Nie wiem na pewno, ale wydaje mi siê, ¿e bunkier znajduje siê prawdopodobnie gdzieœ w pobli¿u Phoenix.}
{567} {} {Dziêki, Diana. To cenne informacje.}

{570} {} {W jakiej broni siê specjalizujesz?}
{571} {} {Wola³abym w ogóle nie braæ udzia³u w ¿adnych walkach. Jeœli mi oczywiœcie na to pozwolisz.}
{572} {} {Czy wiesz w ogóle, dlaczego pistolet potrzebuje spustu?}
{573} {} {O mój Bo¿e... Có¿, jestem dobra w u¿ywaniu broni laserowej i plazmowej, ale jestem bardzo kiepska w strzelaniu z broni palnej, nie mówi¹c ju¿ o walce rêkoma. Czy to dla Ciebie nie problem?}
{574} {} {Wystarczy.}
{575} {} {To jak podró¿owanie z kaktusem. Wszystko jasne.}

{580} {} {Co myœlisz o tym miejscu?}
{581} {} {Rozumiem.}
{582} {} {Nic specjalnego. Typowy krajobraz w tych okolicach.}
{583} {} {To musi byæ miasto, do którego mam siê udaæ. Zapytamy miejscowych o Obserwatorów?}
{584} {} {Du¿e miasto. Pewnie maj¹ tu jakieœ centrum handlowe. Pójdziemy na zakupy?}
{585} {} {Du¿e miasto. Ale okolica wygl¹da niegoœcinnie. Uwa¿aj, nie daj siê zwieœæ miejscowym.}
{586} {} {Du¿y koœció³? Coœ mi to przypomina. S³uchaj, nie czujê siê tu dobrze. OdejdŸmy st¹d, dobrze?}
{587} {} {Wow, dobrze zadomowili siê w tym bunkrze. A ta technika, jest w doskona³ym stanie! Niesamowite. Ach, gdyby moi bracia i siostry tu byli, ilu ludziom moglibysmy wtedy pomóc!}
{588} {} {Zartujesz sobie ze mnie? Pozwól mi tylko otrzeæ p³aszcz przeciwdeszczowy z odchodów szczurów - spróbujê Ci odpowiedzieæ...}
{589} {} {Miasto wygl¹da ponuro. W takich miejscach miejscowi czêsto skrywaj¹ straszne sekrety.}
{590} {} {Niesamowite! Ci ludzie nauczyli siê nawet tworzyæ mikroprocesory. Potrzebujê pilnie porozmawiaæ z ich naukowcami... Jednak w¹tpiê, czy bêd¹ chcieli ze mn¹ rozmawiaæ.}
{591} {} {Muszê st¹d wyjœæ. I to tak szybko, jak to mo¿liwe.}
{592} {} {To posterunek Bractwa Stali. Ten, do którego zmierza³ mój konwój. Pójdziemy do kwatermistrza, ¿eby uzupe³niæ zapasy?}
{593} {} {Przed wojn¹ by³o to du¿e przygraniczne miasto Mexicali. Czerwoni zniszczyli je, bombarduj¹c lokalne fabryki. By³o ich tutaj naprawdê wiele.}
{594} {} {W koñcu znaleŸliœmy coœ ¿ywego na tej pustyni! Ale pos³uchaj, wygl¹da na to, ¿e nie jesteœmy tutaj mile widziani.}
{595} {} {Niepokoi mnie to miejsce.}
{596} {} {Czy nie s¹dzisz, ¿e posuneliœmy siê za daleko od naszego zamierzonego celu? Przypomne Ci, ¿e muszê dostaæ siê do Casa Nueva.}
{597} {} {Jaka jest Twoja misja?}

# Jadac do Casa Nueva
{600} {} {Jesteœmy. Wygl¹da na to, ¿e czas siê po¿egnaæ.}
{601} {} {Tak. To jest teraz mój nowy dom. Niesamowite miejsce - tyle zieleni i niekoñcz¹cej siê pustyni dooko³a. Z pewnoœci¹ jest to owoc wielkiego wysi³ku. Ju¿ nie mogê siê doczekaæ, aby dowiedzieæ siê jak to zrobili.}
{602} {} {W³aœnie zaczyna siê nowy etap w twoim ¿yciu, Diano.}
{603} {} {Dziêkujê Ci bardzo. Ratujesz nie tylko mnie, ale tak¿e ludzi, którzy tu mieszkaj¹. Wspólnie postaramy siê, aby Nowy Dom sta³ siê oaz¹, w której ludzie bêd¹ ¿yæ w pokoju i harmonii.}
{604} {} {Tak, proszê. Natychmiast sta³o siê dla mnie jasne, ¿e tak w³aœnie post¹pi³em.}
{605} {} {Opowiem o tobie moim towarzyszom. Dziêki raz jeszcze.}
{606} {} {Do widzenia Diano.}
{607} {} {Czy pozwolisz mi tak odejœæ bez niczego?}
{608} {} {Przepraszam, nie mam wiele do zaoferowania. Postaram siê zdobyæ lokalnie produkowane lekarstwa i ¿ywnoœæ na wyjazd. Dziêki raz jeszcze.}
{609} {} {Có¿, zawsze coœ. Zegnaj Diano.}

{610} {} {Mi³o ciê widzieæ.}
{611} {} {Czeœæ. Hmm. Czy tylko mi siê wydaje, czy miejscowi naprawdê stroni¹ od ciebie?}
{612} {} {Nie wiedzia³am. Okazuje siê, ¿e jesteœ tu bohaterem.}
{1612} {} {Nie wiedzia³am. Okazuje siê, ¿e jesteœ tu uwa¿ana za bohaterkê.}
{613} {} {Jestem tu tylko po to, aby siê przywitaæ. Muszê ju¿ biec.}
{614} {} {Dobry Bo¿e, co siê tutaj dzieje? Miejscowi oszaleli. Wygl¹da na to, ¿e mam tu du¿o pracy.}