{100} {} {Widzisz... jakieœ usch³e stworzenie.}
{101} {} {To zwiêd³e stworzenie patrzy na ciebie swoimi oszala³ymi oczami.}
{102} {} {Zjem ciê i stanê siê silniejszy ... ale jestem z tego powodu zniesmaczony.}
{103} {} {Usch³y zaatakowa³ ciê, kiedy tylko siê od niego odwróci³eœ plecami!}
{104} {} {Mój róg zaczyna boleæ. Lepiej odejdŸ!}

{110} {} {Boli... Jak to boli...}
{111}{}{Ból znikn¹³... Teraz czujê siê s³aby...}

{200} {} {(Przed sob¹ widzisz dziwne stworzenie, które nawet trochê przypomina cz³owieka. Jego szalone oczy s¹ przestraszone i jednoczeœnie z uwag¹ ciê obserwuj¹)}
{201} {} {Ach, demon! Giñ! Giñ!}
{202} {} {Czekaj, nie skrzywdzê ciê. Kim jesteœ?}
{203} {} {Stój, dziwaku. Powiedz mi kim jesteœ.}
{204} {} {(chwyta siê za g³owê; zauwa¿asz kilka rogowych wyrostków na jego g³owie)}
{205} {} {Czy jesteœ st¹d?}
{206} {} {Mów, kiedy z tob¹ rozmawiam.}
{207} {} {(wstaje i rozgl¹da siê) Dobrze. Sk¹d pochodzisz? Dawno nie widzia³em normalnej osoby. I te ubrania... Pamiêtam. Tak. Otrzymali ja mieszkañcy Krypt. (chodzi dooko³a, badaj¹c ciê wzrokiem) Nie by³em w Krypcie. Dlatego jestem tutaj.}
{208} {} {Poczekaj chwilê, stary. Mam do Ciebie kilka pytañ.}
{209} {} {Usi¹dŸ, dziwaku. I nic nie kombinuj - inaczej ciê zastrzelê.}

{220} {} {(zakrywa twarz rêkoma) Czego chcesz? Miasto jest zniszczone. Nikt nie jest tutaj normalny. IdŸ st¹d.}
{221} {} {Ok, wychodzê. Nie próbuj mnie œledziæ.}
{222} {} {(wstaje i rozgl¹da siê) Dobrze. Sk¹d pochodzisz? Dawno nie widzia³em normalnej osoby. Od tamtej pory... (chodzi dooko³a, badaj¹c ciê wzrokiem) Od tamtej pory gdy ludzie schronili siê w Kryptach. Nie mieli tam wystarczaj¹co du¿o miejsca dla wszystkich, wiêc jestem teraz tutaj.}

#O mnie
{230} {} {Kim jesteœ? Demonem?}
{231} {} {Demonem? (odwraca wzrok) Mo¿e tak... by³em kiedyœ cz³owiekiem... by³em rolnikiem. Pracowa³em w polu, zeby mieæ za co ¿yæ. Zakopywa³em ziemniaki i inne warzywa w ziemi... Jakie to g³upie.}
{232} {} {Czy jest tu jeszcze ktoœ oprócz Ciebie?}
{233} {} {Czy to by³a twoja farma tutaj, wœród tych ruin?}
{234} {} {Jak prze¿y³eœ?}
{235} {} {Prze¿y³em? Nie. To nie jest ¿ycie. To jest piek³o. Wszyscy ¿yjemy w piekle. Nie mo¿emy umrzeæ. Takimi nas uczyni³o promieniowanie. To jest nasza kara. Ktoœ mia³ szczêœcie byæ w epicentrum wybuchów nuklearnych. Ale nie my.}
{236} {} {Co siê sta³o z innymi ocala³ymi?}
{237} {} {By³o tu du¿e miasto, prawda?}
{238} {} {Co teraz robisz? Wydaje siê, ¿e nie ma tu zbyt wielu zbiorów.}
{239} {} {Nie ma tu jedzenia! Jedliœmy to, co znaleŸliœmy w ruinach. A teraz jemy siê nawzajem. Ale rzadko. Przyzwyczailiœmy siê do g³odu.}
{240} {} {Wiêc s¹ inni... tacy jak ty?}
{241} {} {Nic dziwnego - wszêdzie wokó³ ruiny miasta.}
{242} {} {Farma, mówisz? Czekaj, kiedy to by³o?}
{243} {} {To by³o dawno temu. Kiedy bomby spad³y na miasto. Jeszcze ciê wtedy nie by³o.}
{244} {} {Czy widzia³eœ Wielk¹ Wojnê na w³asne oczy?}
{245} {} {Czy ktoœ oprócz ciebie prze¿y³ to piek³o?}
{246} {} {Swoj¹ drog¹, w jakim mieœcie by³eœ tu wczeœniej?}
{247} {} {W ogóle tego nie chcia³em s³yszeæ. Porozmawiajmy o czymœ innym.}

#O stadach
{250} {} {Nie zosta³o nas wielu. Ale nawet teraz mamy podzia³ na bogate demony i biedne, takie jak ja. Bogaci œwiec¹ w ciemnoœci. Trzymaj¹ wszystkich w ryzach i wybieraj¹ to, co najlepsze.}
{251} {} {[Pos³uchaj]}
{252} {} {Kiedyœ byli wa¿ni i wp³ywowi. A teraz, kiedy stali siê demonami, mia¿dz¹ tak¿e resztê. (œmieje siê) Ok, niech bêdzie tak, jak tego chc¹. Niech œwiec¹, niech ¿yj¹ wiecznie w mêkach.}
{253} {} {[Dalej.]}
{254} {} {To piek³o jest gorsze ni¿ œmieræ. Nie mog¹ umrzeæ. Nawet jeœli naprawdê tego chc¹. To jest ich kara - nieœmiertelnoœæ. Udrêczeni swoimi grzechami, musz¹ cierpieæ wiecznie.}
{255} {} {Czy ty te¿ jesteœ demonem? Jak te œwiec¹ce?}
{256} {} {Ale co to za cholerne miejsce, które tak niszczy ludzi?}
{257} {} {Wiêc zosta³eœ wyrzucony ze stada? Czy to dlatego jesteœ taki chudy?}
{258} {} {Stado dzieli siê jedzeniem. Nie mo¿esz tu przetrwaæ sam. A œwiec¹cy bior¹ dla siebie wszystko, co najlepsze. A kiedy w ogóle nie ma jedzenia, jedz¹ najs³abszych... takich jak ja. Zostanê po¿arty i uwolniê siê od agonii. Ale ja nie chcê byæ zjedzony. Dlatego siê chowam.}
{259} {} {Coœ staje siê dla mnie powoli jasne. Ale zmieñmy temat.}
{260} {} {Wiêc nie ma tu normalnych ludzi, prawda?}
{261} {} {Och, wiem, wiem! Ktoœ mieszka w rezydencji. Wieczorem pali siê tam œwiat³o. Ale nie widzia³em, kto to by³. Wielu chce siê tam dostaæ, ale nie mo¿e.}
{262} {} {Czy znasz bezpieczn¹ drogê do tej posiad³oœci?}
{263} {} {Móg³bym pokazaæ. Ale tam mnie zjedz¹. Ty te¿ zostaniesz zjedzony. Ale jeœli chcesz... jeœli chcesz, idŸ kana³ami. To najbezpieczniejszy sposób.}
{264} {} {Ciekawe. Ale prawdopodobnie wiesz coœ jeszcze.}
{265} {} {Kto oprócz ciebie mieszka w tych ruinach?}
{266} {} {Co to za miasto?}

# O mieœcie
{270} {} {(d³ugo siê rozgl¹da) Dawno temu by³o tu du¿e miasto. Nazywa³o siê Mexicali. Piêkne miasto. Potem spad³y bomby atomowe...}
{271} {} {[Pos³uchaj]}
{272} {} {Zamienili je w pole spalonych œmieci i z³omu. Czerwoni to zrobili. Celowali w fabryki samolotów, ale... wszystko inne te¿ zniszczyli. Teraz, z powodu opadu radioaktywnego, nie ma tu ¿ycia. Nawet trawa nie roœnie.}
{273} {} {[Dalej.]}
{274} {} {Wszystko tutaj jest ska¿one promieniowaniem. To przez to jestem jaki jestem.}
{275} {} {Ale jak uda³o ci siê prze¿yæ w tym piekle?}
{276} {} {Wiêc nie jesteœ tutaj sam? Czy w ruinach mieszkaj¹ inni ocaleni?}
{277} {} {Dlaczego to miasto zosta³o zniszczone? Czy by³a jakaœ wojna?}

#O wojnie
{280} {} {G³upi ludzie to zrobili. Zamienili planete w wysypisko œmieci, zu¿yli ca³¹ ropê i zaczeli zabieraæ sobie nawzajem ostatnie okruchy. Miasta i przyroda, które tak bardzo kochaliœmy, zniknê³y z powierzchni Ziemi.}
{281} {} {[Pos³uchaj]}
{282} {} {Widzia³em ostatnio wielk¹ mrówkê. Takich mrówek nigdy nie by³o. To nie jest normalne. Mrówki powinny byæ... trochê szkar³atne. I mniejsze od paznokci. Ale te nie s¹ takie.}
{283} {} {[Dalej.]}
{284} {} {To z powodu opadu... Cœœ! S³yszysz to? To demony wyj¹ z bólu. Kiedy zapada noc, wszystkie demony tak robi¹.}
{285} {} {Czy te demony to reszta ocala³ych?}
{286} {} {Jakie by³o to miasto przed bombardowaniem?}
{287} {} {Wiêc zatrzymajmy siê na tym, aby ta informacja osiad³a w mojej g³owie.}
{288} {} {A ty? Czy ty te¿ jesteœ demonem?}
{289} {} {Czy tylko ty prze¿y³eœ? Czy jest tu ktoœ jeszcze?}

{300} {} {Czy widzia³eœ oddzia³ Bractwa Stali? Musia³ iœæ t¹ drog¹.}
{301} {} {Och, och, boli mnie g³owa! Jak boli...}
{302} {} {Nie oszukuj mnie. Powiedz mi, co siê sta³o z konwojem!}
{1302} {} {Twoje sztuczki na mnie nie dzia³aj¹. Powiedz mi, co siê sta³o z konwojem!}
{303} {} {Przepraszam, ale to bardzo wa¿ne. Spróbuj sobie przypomnieæ.}
{304} {} {Ach, ci bladzi ludzie nie mogli wydostaæ siê z naszego piekielnego œwiata. Ojej, tak jak reszta, bêd¹ musieli tu zostaæ na zawsze.}
{305} {} {Wiêc oni ¿yj¹?}
{306} {} {S¹ trzymani w starym koœciele. Ale nie mo¿esz tam iœæ, hehe. Nie, nie, nie mo¿esz! Wokó³ s¹ t³umy demonów i nikt nie wie, co siê dzieje w œrodku. To przeklête miejsce, legowisko samego Lucyfera. Nikt stamt¹d nie wróci³.}
{307} {} {Wygl¹da na to, ¿e nie bêdzie ³atwo siê tam dostaæ...}