{100} {} {Widzisz Garretta.}
{105} {} {Lajdaku! Zap³acisz za œmieræ moich towarzyszy!}

{200} {} {Co? Kolejny normalny? I sam przyszed³ do nas? Oh-ho-ho, mamy dziœ szczêœcie.}
{201} {} {Gdzie ja jestem? I kim ty jesteœ?}
{202} {} {Czy nosisz gruby zielony kostium trolla?}
{203} {} {Po³ó¿ broñ i chodŸ za mn¹. Levi z tob¹ porozmawia.}
{204} {} {Ok. Zabierz mnie do Leviego. Chcê zadaæ mu kilka pytañ.}
{205} {} {Nie, g³upi wielki facecie, porozmawiam tylko z tob¹.}
{206} {} {Mówiê ci, idŸ do Leviego. A jeœli bêdziesz siê opiera³, z³amie ci nogi, zabiorê ciê do niego i rzucê na pod³ogê jak star¹ szmatê.}
{207} {} {Ok, idê, tylko mnie nie bij.}
{208} {} {Tylko spróbuj mnie dotkn¹æ, gruby dziwaku.}
{209} {} {Najpierw mnie wys³uchaj. Przybywam w pokoju.}
{1209} {} {Najpierw mnie wys³uchaj. Przybywam w pokoju.}

{210} {} {Czego chcesz, normiku?}
{211} {} {Na razie nic.}
{212} {} {Tak, proszê pana.}

{220} {} {Porozmawiajmy. Jak masz na imiê?}
{221} {} {Nazywam siê Garrett. I nie rozmawiam z normalnymi.}
{222} {} {Nazywam siê Garrett. I nie ufam normalnym.}
{223} {} {}
{224} {} {Ok. Dobrze, ¿e mogliœmy siê poznaæ. Bywaj.}
{225} {} {Dlaczego? Czy coœ siê wydarzy³o w przesz³oœci?}
{226} {} {Lepiej siê zamknij, zanim stracê panowanie nad sob¹.}
{227} {} {Twoi podw³adni te¿ nie s¹ zbyt rozmowni. Sk¹d tyle z³oœci na ludzi?}
{228} {} {Z³oœci? Nie. Stwórca nauczy³ nas szacunku do wszystkich ¿ywych istot. A ludzie tacy jak ty wypêdzili nas z zachodnich krajów. Wiêc jeœli siê nie zamkniesz, z przyjemnoœci¹ siê rozerwê.}
{229} {} {Ok...}
{230} {} {Czy zawsze by³eœ taki... taki niezwyk³y?}
{231} {} {By³em kiedyœ osob¹ tak¹ jak ty. Pamiêtam swoje uczucia - strach, nienawiœæ i zazdroœæ. Ale Mistrz da³ mi nowe ¿ycie i pozby³em siê ludzkich wad. A potem ludzie odebrali mi Mistrza.}
{232} {} {Przepraszam, to pytanie wydaje siê ciê irytowaæ. Lepiej odejdê.}
{233} {} {Przez s³owa „da³ nowe ¿ycie” masz na myœli przyjêcie mutagenu?}
{234} {} {Mutagen jest czêœci¹ du¿ej ceremonii. Trwa prawie rok. Przygotowywa³em siê - poœci³em, medytowa³em na ruinach, æwiczy³em swoje cia³o i wole. Mutagen nie zostanie podany komuœ, kto na to nie zas³uguje.}
{235} {} {Wygl¹da na to, ¿e du¿o przeszed³eœ. Czas, ¿ebym zaj¹³ siê moimi problemami. Bywaj.}
{236} {} {Mistrz - kto to jest?}
{237} {} {Kim jest twój Mistrz?}
{238} {} {To mój Bóg.}
{239} {} {To... trochê wyjaœnia.}
{240} {} {Haha, g³upi cz³owieku. I tak nigdy nie zobaczysz Boga. Zabili go ludzie tacy jak ty.}
{241} {} {Zabili Boga? To mo¿liwe?}
{242} {} {Nie ma Boga. Jesteœmy zdani na siebie. I to wszystko.}
{243} {} {Ok. Zatrzymajmy siê na razie nad tym.}
{244} {} {Wiêc Levi tu rz¹dzi?}
{245} {} {On jest rêk¹ mojego Boga, oddam za niego ¿ycie.}
{246} {} {Myœla³em, ¿e jesteœ tutaj wa¿niejszy.}
{247} {} {Twoje mêstwo inspiruje.}
{248} {} {Levi ratuje nasze dusze. Bez niego nie mamy przysz³oœci. Dlatego s³u¿ê mu tak, jak s³u¿y³em mojemu Mistrzowi. Ale ty, normiku, nie jesteœ w stanie zrozumieæ naszego cierpienia.}
{249} {} {Ok, za³ó¿my, ¿e jest tak jak mówisz.}

{250} {} {Czeœæ Garrett. Jak wygl¹da praca?}
{251} {} {W porz¹dku. Moi ludzie bêd¹ ciê chroniæ, jeœli zajdzie taka potrzeba.}
{252} {} {Wygl¹da na to, ¿e chyba nie do koñca.}
{253} {} {Haha, masz racjê, cz³owieku. Nadal potrzebujesz w³asnej ochrony. Proszê, weŸ tê broñ.}
{254} {} {Broñ energetyczna? To jeden z projektów Leviego. Czy nauczysz mnie, jak tego u¿ywaæ?}
{255} {} {Ach wy, normalni, musicie siê wszystkiego uczyæ. Ok, poka¿ê ci... Jeœli przyniesiesz mi normalne jedzenie.}
{256} {} {Ok, poszukam czegoœ do jedzenia.}
{257} {} {Jedzenie? Tutaj? Za du¿o chcesz, zielony.}

{260} {} {Obieca³eœ nauczyæ mnie, jak u¿ywaæ broni energetycznej.}
{261} {} {Chcê jeœæ!}
{262} {} {Ok. Poka¿ê ci co i jak. To nie jest wcale takie trudne.}
{263} {} {Wiêc nie traæmy czasu. Nie chcê byæ w sytuacji, gdy w po³owie treningu znowu zg³odniejesz...}
{264} {} {Swietnie, ale do tego dojdziemy póŸniej.}
{265} {} {W³aœciwie nie interesuje mnie broñ energetyczna. Wolê du¿e giwery. Poka¿ mi, jak obchodziæ siê z ciê¿k¹ broni¹!}