{100} {} {Widzisz super mutanta.}
{105} {} {Cz³owieku! Zap³acisz za œmieræ moich towarzyszy!}

{110} {} {Porozmawiaj z Levim.}
{111} {} {Nieszczêœnik.}
{112} {} {Nie wa¿ siê na mnie gapiæ.}
{113} {} {Nienawidzê, kiedy ludzie siê na mnie gapi¹.}
{114} {} {Hmmmm...}
{115} {} {Grasz w koœci?}
{116} {} {Nie jestem besti¹.}
{117} {} {Levi odpowie na wszystkie pytania. Jeœli zechce.}
{118} {} {Nie mów do mnie, normiku.}
{119} {} {Jeœli mi bêdziesz przeszkadzaæ, rozerwê ciê na strzêpy i rzucê rozpruwaczom.}

{120} {} {Czeœæ.}
{121} {} {Levi mówi, ¿e jesteœ przyjacielem.}
{122} {} {Dobrze, ¿e jeszcze ¿yjesz.}
{123} {} {Mo¿e uda nam siê sprawdziæ nasz¹ si³ê?}
{124} {} {Nudzi mi siê...}
{125} {} {Levi mówi, ¿e wkrótce bêdzie lekarstwo.}
{126} {} {Czy chcesz byæ taki jak ja?}
{127} {} {A-ha-ha, moje cierpienie dobiega koñca!}
{128} {} {Lubiê wkurzaæ rozpruwacze. Nic mi nie mog¹ zrobiæ.}
{129} {} {Rozpruwacze s¹ g³upie. Ja jestem m¹dry.}