{100} {} {Widzisz asystenta.}
{101} {} {Widzisz oszpeconego mê¿czyznê. Jego twarz topi siê jak wosk.}

{110} {} {Dziwne, ¿e ciê tu wpuszczono.}
{111} {} {Nie mam czasu rozmawiaæ z poganami.}
{112} {} {Nie mam nic dla ciebie.}
{113} {} {Zostaw mnie w spokoju albo wezwê moich zielonych braci.}
{114} {} {Co z twoj¹ skór¹? Wygl¹dasz okropnie.}
{115} {} {Nie rozumiem, jak wy, zwykli ludzie, potraficie przetrwaæ we wspó³czesnym œwiecie.}
{116} {} {Ludzie na pustyni s¹ g³upi.}
{117} {} {S³uchaj Leviego.}
{118} {} {Nie ufam tobie ani nieznajomym takim jak ty.}
{119} {} {Nasi ludzie tak wiele wycierpieli z powodu zwyk³ych ludzi...}

{120} {} {Och, wejdŸ przyjacielu, usi¹dŸ.}
{121} {} {Chocia¿ jesteœ poganinem, jesteœ przynajmniej nieszkodliwy.}
{122} {} {Czy chcia³byœ ¿eby ci zrobiæ radioaktywn¹ kawê?}
{123} {} {Przepraszam za moich zielonych braci, nie s¹ przyzwyczajeni do zwyk³ych ludzi.}
{124} {} {Co z twoj¹ skór¹? Jak uda³o Ci siê j¹ uratowaæ?}
{125} {} {Wy, normalni, radzicie sobie œwietnie w tym nowym œwiecie.}
{126} {} {Ludzie zadziwiaj¹ mnie swoj¹ witalnoœci¹.}
{127} {} {S³uchaj Leviego, by³ blisko samego Boga!}
{128} {} {Ufam ci. Ale nie tym rasistom z Bractwa Stali.}
{129} {} {Nasi ludzie wiele przeszli. Nie zrozumiesz.}
