{100} {} {Widzisz Leviego.}
{105} {} {Rasisto! Zap³acisz za œmieræ moich towarzyszy!}

{110} {} {W imieniu Mistrza...}
{111} {} {W imiê Jego Ducha Swiêtego...}
{112} {} {Przyjmij grzeszn¹ duszê swojego niewolnika...}
{113} {} {S³ugo Bo¿y, uklêknij i pokutuj za swoje grzechy przed obliczem Mistrza.}
{114} {} {Wypij œwiêtego wirusa z tego œwiêtego kielicha.}
{115} {} {Niech Duch Swiêty bêdzie z tob¹.}
{116} {} {Amen.}

{200} {} {Witaj nieznajomy. Jestem Levi, przewodnik mojej ma³ej trzódki.}
{1200} {} {Witaj nieznajoma. Jestem Levi, przewodnik mojej ma³ej trzódki.}
{201} {} {Ja jestem }
{202} {} {. Tylko podró¿ujê.}
{203} {} {Koœció³ i œwiêty cz³owiek poœrodku zwêglonych ruin wygl¹daj¹ bardzo dziwnie.}
{204} {} {Jesteœ w naszej œwiêtej siedzibie i twoja obecnoœæ tu jest niepokoj¹ca. Zawrzyjmy od razu uk³ad - bêdziesz tu bezpieczny, o ile bêdziesz przestrzegaæ naszych zasad i zachowywaæ siê przyjaŸnie.}
{205} {} {Nie chce walczyæ. Szczególnie w tej sytuacji.}
{206} {} {Cokolwiek powiesz.}
{207} {} {Bardzo dobrze. To niecodzienny widok zobaczyæ tutaj normaln¹ osobê. Powiedz mi, co ciê przynios³o.}
{208} {} {Jesteœ uprzejmy wobec szeœciolufowego miniguna? Jak na ksiedza nie jesteœ zbyt mi³y.}
{209} {} {Jeœli zrozumiesz nasze stanowisko, pomyœlisz inaczej. A teraz powiedz mi, co przywiod³o ciê do tych ruin? I nie próbuj k³amaæ - wyczujê ka¿de k³amstwo.}
{210} {} {Szukam przydatnych przedmiotów w ruinach. Musi tu byæ wiele przedwojennych skarbów.}
{211} {} {Twoje pragnienie zysku zaprowadzi³o ciê prosto do piek³a. Czego mo¿na by³o siê spodziewaæ.}
{212} {} {Co robisz w tym piekle?}
{213} {} {Szukam swojego gatunku. Zostali porwani przez handlarzy niewolników.}
{214} {} {Oczywistym jest, ¿e ich tu nie ma. Masz têpy umys³, szukaj¹c konwoju niewolników w tak pozbawionym ¿ycia miejscu.}
{215} {} {Mimo to musia³em to sprawdziæ. Co Ty tutaj robisz?}
{216} {} {Szukam konwoju Bractwa Stali. Zagin¹³ gdzieœ w tych ruinach.}
{217} {} {Rozumiem. Wiêc Bractwo wys³a³o najemnika zamiast ryzykowaæ ¿yciem swoich ludzi. Tak jak siê spodziewa³em, w tym regionie nie maj¹ wystarczaj¹cej si³y do przeprowadzania prawdziwych akcji ratowniczych. Tym lepiej dla nas.}
{218} {} {Dlaczego? Coœ planujesz?}
{219} {} {To d³uga historia. Niektórzy myœl¹, ¿e jestem Diab³em i próbujê stworzyæ tu w³asne piek³o. Ale tak naprawdê staram siê stworzyæ niebo dla moich ludzi w œrodku piek³a.}
{220} {} {Brzmi jak diabelski plan.}
{221} {} {Kontynuuj.}
{222} {} {To bardzo szlachetne z twojej strony.}
{223} {} {Nie mo¿emy d³u¿ej ¿yæ w normalnym œwiecie. Poganie pal¹ naszych braci na zachodzie, a wschodzie nikt nie akceptuje ani naszej wiary, ani nas samych. Pó³noc i po³udnie s¹ puste. Dlatego musimy stworzyæ w³asny œwiat.}
{224} {} {[Dalej.]}
{225} {} {Teraz zdajesz sobie sprawê, ¿e twoja obecnoœæ tutaj jest wysoce niepo¿¹dana. Szczególnie bior¹c pod uwagê nasze ostatnie spotkanie z innymi „normalnymi” osobami.}
{226} {} {Czekaj, s¹ tu inni „normalni” tacy jak ja?}
{227} {} {Przez nasze ruiny maszerowa³a na po³udnie spora grupa pogan. Nie by³o im jednak przeznaczone opuszczenie tych ziem. Zostan¹ tu na zawsze, tak jak Ty.}
{228} {} {Jeœli pomogê Ci „znaleŸæ niebo”, uwolnisz mnie?}
{229} {} {Jedna nazwa dla dwojga? Dziwne losy... Ale to nie ma znaczenia. }
{230} {} {Co jest do diab³a? Puœæ mnie natychmiast!}
{231} {} {Nie ma dla ciebie wyjœcia. Garrett, wyjaœnij to naszemu goœciowi...}
{232} {} {I tak st¹d wyjdê. Nawet nie myœl o zatrzymaniu mnie.}
{233} {} {Czekaj! A jeœli ci pomogê? Czy wtedy mnie uwolnisz?}
{234} {} {Chcesz zawrzeæ uk³ad z diab³em? W porz¹dku.}
{235} {} {[Dalej.]}
{236} {} {ZejdŸ do piwnicy i porozmawiaj z Dian¹. Powie Ci, jakie badania prowadzimy i co jest jej potrzebne, aby je ukoñczyæ. Wszyscy otrzymaj¹ nagrodê za jej sukces.}
{237} {} {Ok. Idê.}
{238} {} {Nie, nie. Nie zawieram umów z diab³ami.}
{239} {} {Przykro mi, ¿e s³yszê odmowê po tak szczerej rozmowie. Garrett, zostawiam to cia³o twojemu uznaniu...}
{240} {} {Co?}
{241} {} {Trzymaj siê ode mnie z daleka, wielkoludzie!}

{242} {} {Batwas? Pra… Co?}
{243} {} {(wzdycha) Biedne dziecko... To niesamowite, ¿e uda³o ci siê prze¿yæ i dostaæ tutaj. Ale nie martw siê. Jesteœmy twoimi przyjació³mi. Pomo¿emy Ci. Nie skrzywdzisz swoich przyjació³, prawda?}
{244} {} {Och, przyjaciele! Przyjaciele!}
{245} {} {K³amiesz. Jesteœ z³y. Nie mam przyjació³.}
{246} {} {Có¿, rozumiem. Jesteœ samotny, jak my wszyscy. Ale teraz jesteœmy twoimi przyjació³mi. Dajê ci s³owo, ¿e bêdzie ci z nami dobrze.}
{247} {} {Nie! Nie wierzê! Oszukujesz!}
{248} {} {To cia³o bêdzie zbyt wielkim problemem. Garrett, zakoñcz jego cierpienie...}
{249} {} {Aha!}

{250} {} {Co mo¿esz mi powiedzieæ?}
{251} {} {Muszê byæ zajêty.}
{252} {} {Uspokój siê, moje dziecko. Jesteœ w koœciele, jesteœ tu bezpieczny. Nikt ciê tutaj nie tknie. Mo¿e mo¿esz zrobiæ coœ dla swoich nowych przyjació³? Diana mieszka w piwnicy. Znajdziesz z ni¹ wiele wspólnego. Porozmawiaj z ni¹. Udaj siê...}
{253} {} {Uch, dziewczyna w piwnicy. Tak idê.}
{254} {} {Wci¹¿ tutaj? Czy naprawdê chcesz pozostaæ w tym œwiêtym miejscu?}

{255} {} {Masz czêœæ pancerza wspomaganego. Dasz mi j¹?}
{256} {} {WeŸ to. Wierzê, ¿e u¿yjesz tej zbroi w dobrym celu. Poza tym i tak nie mo¿emy jej u¿ywaæ.}
{257} {} {Dziêki. Dobrze j¹ wykorzystam.}
{258} {} {Dziêki, ale chcê zapytaæ o coœ jeszcze.}
{259} {} {Pozdrowienia, bracie.}
{1259} {} {Pozdrowienia, siostro.}

{260} {} {Kim jesteœ?}
{261} {} {Jestem Levi, pasterz tych nieszczêsnych dusz.}
{262} {} {S³ysza³em to ju¿ wczeœniej. Spróbujmy czegoœ innego.}
{1262} {} {S³ysza³am to ju¿ wczeœniej. Spróbujmy czegoœ innego.}
{263} {} {Pasterzem? Jesteœ ksiêdzem czy coœ?}
{264} {} {Nasz koœció³ zosta³ zniszczony przez pogan takich jak ty. Nasz Bóg zgin¹³ w p³omieniu atomowym, wiêc teraz ja prowadzê t¹ trzode zgodnie z jego przykazaniami. Ale daleko od tych krajów, gdzie nasza wiara obróci³a siê we wstyd.}
{265} {} {Jaka wiara i co to jest?}
{266} {} {Nie zrozumiesz podstaw nawet po ca³ej mszy. Powiem tylko, ¿e nasz Bóg, Mistrz, chcia³ uwolniæ ludzi od ich wad i niedoci¹gniêæ, sugeruj¹c inn¹ drogê.}
{267} {} {Czy ta inna œcie¿ka to œcie¿ka mutacji i brzydoty?}
{268} {} {Twój wzrok jest ograniczony. Dziêki Mistrzowi jesteœmy pozbawieni ludzkich przywar i jesteœmy w stanie przetrwaæ nawet w tak zgubnym miejscu, jak te ruiny. A ty?}
{269} {} {Nie s¹dzê, ¿ebym chcia³ tu mieszkaæ. Ale dlaczego ty przyby³eœ do tych ruin?}
{1269} {} {Nie s¹dzê, ¿ebym chcia³a tu mieszkaæ. Ale dlaczego ty przyby³eœ do tych ruin?}
{270} {} {Dlaczego wybra³eœ to szczególne miejsce dla swojej trzody?}
{271} {} {To proste. Tutaj jesteœmy bezpieczni przed poganami i heretykami. Zbieramy si³y na Drugie Przyjœcie, kiedy Mistrz ponownie powstanie z popio³ów.}
{272} {} {Twoja historia jest bardzo interesuj¹ca. Ale mam wa¿niejsze rzeczy do zrobienia.}
{273} {} {Wiêc co to za wiara, której tak mocno siê trzymasz?}
{274} {} {Wygl¹da na to, ¿e ten Mistrz by³ dla ciebie naprawdê wa¿ny.}
{275} {} {Jesteœmy dzieæmi katedry. Zostaliœmy ukrzy¿owani za nasz¹ wiarê, ale bêdziemy kontynuowaæ nasze modlitwy do koñca œwiata. To jest nasz ciê¿ar.}
{276} {} {Myœlê, ¿e jesteœcie po prostu kolejn¹ sekt¹. Nie wierzê ci.}
{277} {} {Wydajesz siê naprawdê wierzyæ w to, co mówisz.}
{278} {} {Twoje oddanie wierze zas³uguje na szacunek.}

{280} {} {Jak ty i inni staliœcie siê tacy...?}
{281} {} {Brzydcy? Na szczêœcie ju¿ dawno przestaliœmy przyjmowaæ to s³owo z uraz¹. Dla nas wygl¹d ju¿ dawno straci³ znaczenie. Co nas takimi ukszta³towa³o? Nasze grzechy i brudne myœli, kiedy byliœmy ludŸmi.}
{282} {} {Mówi¹c o Bogu, kogo masz na myœli?}
{283} {} {Bóg ju¿ nie istnieje. Bóg pad³ z r¹k g³upców. Jesteœmy jedynymi, którzy wnosz¹ œwiat³o do tego piek³a po jego œmierci.}
{284} {} {Hmm. Widzia³em ju¿ taki p³aszcz. Wyznawcy ognia w Phoenix nosz¹ coœ podobnego.}
{285} {} {Napotkaliœmy ju¿ tych naœladowców, którzy paso¿ytuj¹ w ma³ych osadach pod naszym sztandarem. Nie ufaj tym bluŸniercom, ich wiara jest fa³szywa.}
{286} {} {Kogo masz na myœli, mówi¹c o Bogu?}
{287} {} {Nie, dopóki nie wykonasz zadania.}
{288} {} {Ok.}

{290} {} {Co wiesz o Dianie?}
{291} {} {Wyznawcy Apokalipsy to mili, ale g³upi ludzie. Staraj¹ siê pomagaæ innym, najlepiej jak rozumiej¹ tê pomoc. Traktuj¹ ludzi takich jak ja z protekcjonalnoœci¹, jakbyœmy potrzebowali ich opieki. Ale jest odwrotnie.}
{292} {} {Dlaczego potrzebujesz Diany?}
{293} {} {Jest lekarzem i naukowcem. Dok³adnie tym, czego potrzebujê, aby ukoñczyæ swoj¹ misjê.}
{294} {} {Co to za misja?}
{295} {} {Niebo w œrodku piek³a.}
{296} {} {Rozumiem.}
{297} {} {Co wiesz o Wyznawcach Apokalipsy?}

{300} {} {Co wiesz o Bractwie Stali?}
{301} {} {To heretycy, którzy stracili wszelk¹ wiarê w Boga. Wierz¹ tylko w si³ê technologii. Biedni ludzie.}
{302} {} {Masz z nimi z³e relacje, prawda?}
{303} {} {To Bractwo jest odpowiedzialne za zamordowanie naszego Boga. Ich przebaczenie nadejdzie dopiero w epicentrum rozszczepienia atomu.}
{304} {} {Rozumiem.}

{310} {} {Diana opracowa³a mutagen.}
{311} {} {Jej praca jest nieoceniona. Ale na razie nie mogê ryzykowaæ podania leków mojemu ludowi.}
{312} {} {Chcesz je najpierw sprawdziæ? Ale jak?}
{313} {} {Zobaczmy, jak dzia³a ten mutagen na naszych szalonych braciach mieszkaj¹cych w ruinach. WeŸ te opryskiwacze i umieœæ je w najbardziej ruchliwych miejscach. Tam, gdzie rozpruwacze wykonuj¹ swoje demoniczne rytua³y.}
{314} {} {Rozumiesz, ¿e mogê umrzeæ podczas tej misji?}
{315} {} {Czy masz na myœli ich totemy? Okay, bêdê musia³ byæ dyskretny, ¿eby nie ha³asowaæ i umrzeæ.}
{316} {} {Ju¿ prawie nie ¿yjesz. Ale wierzê, ¿e odniesiesz sukces, jeœli nie bêdziesz anga¿owaæ siê w walkê. Uwierz w nasz¹ misjê, uwierz w siebie.}
{317} {} {Tak, oczywiœcie, nie ma problemu. Przekradnij siê do t³umu upiorów i rzuæ sprayem. Nic prostszego. Uh, pa.}
{318} {} {Wysy³asz mnie na œmieræ. Jeœli nie prze¿yjê, bêdziesz za wszystko odpowiedzialny.}
{319} {} {Chwalcie niebiosa za swój wygl¹d. Teraz idŸ.}
{320} {} {Spróbujê nie umrzeæ.}
{321} {} {Jeœli prze¿yjê, s³ono za to zap³acisz.}
{322} {} {To jest zbyt niebezpieczne. Mo¿e jest inna opcja?}

{330} {} {Twoja praca jest nieoceniona. Ale jak dot¹d nie mogê tego zaakceptowaæ.}
{331} {} {Zakoñczyliœmy nasz¹ misjê. Coœ nie tak? Potrzebujesz porêczycieli?}
{332} {} {Zycie moich ludzi zale¿y od tego leku. Udowodnij, ¿e jest naprawdê bezpieczny.}
{333} {} {Zrobi³em, co chcia³eœ. Jeœli nie zamierzasz dotrzymaæ s³owa, idŸ do diab³a.}
{334} {} {To bardzo niegrzeczne. Garrett, poka¿ naszemu goœciowi, ¿e nie jest tu ju¿ mile widziany...}
{335} {} {Giñ!}
{336} {} {Nie, czekaj! Mogê wzi¹æ ten mutagen, aby udowodniæ jego skutecznoœæ. Mo¿e byæ?}
{337} {} {Czekaj. A jeœli zainstalujê dozowniki mutagenów w ruinach? Czy to ciê zadowoli?}
{338} {} {Mogê wzi¹æ ten mutagen. W ka¿dym razie i tak czujê, ¿e inaczej nie przetrwam w tym œwiecie.}
{339} {} {Godne pochwa³y poœwiêcenie. Jeœli weŸmiesz mutagen, staniesz siê inn¹ osob¹, jednym z nas. Znajdziesz tu przyjació³ i nowy dom, ale stracisz ludzk¹ postaæ.}
{340} {} {Idioto, powa¿nie kupujesz ten blef? Nie zamierzam zamieniæ siê w zielonego dziwaka i wierzyæ w ró¿nego rodzaju bzdury.}
{341} {} {Wszystko bêdzie dobrze. Nie bojê siê mutacji.}
{342} {} {Czy jest inna alternatywa? Na przyk³ad mogê przetestowaæ mutagen na rozpruwaczach.}
{343} {} {Ok. Mogê zainstalowaæ spraye mutagenne w miejscach, w których koncentruj¹ siê rozpruwacze.}
{344} {} {Tak, to wiele wyjaœni. Zobaczmy, jak mutagen wp³ywa na mieszkañców ruin.}
{345} {} {Dobrze.}
{346} {} {Sami zrobimy opryskiwacze. Twoim zadaniem jest zainstalowanie ich w najbardziej ruchliwych miejscach na ruinach. Teraz idŸ i nie rozpraszaj mnie, dopóki nie wykonasz zadania.}
{347} {} {Jestem w drodze.}
{348} {} {Przygotuj siê do ceremonii. Osobiœcie przeprowadzê wszystko zgodnie z kanonami naszego koœcio³a.}
{349} {} {[Poczekaj na ceremoniê]}

{350} {} {Zainstalowa³em rozpylacze. I mia³o to pewien wp³yw na rozpruwacze.}
{1350} {} {Zainstalowa³am opryskiwacze. I mia³o to pewien wp³yw na rozpruwacze.}
{351} {} {Tak by³o? Co siê im sta³o?}
{352} {} {Stali siê... m¹drzejsi i spokojniejsi.}
{353} {} {Myœlê, ¿e mutagen obni¿y³ ich próg agresywnoœci i wyeliminowa³ chroniczny ból.}
{354} {} {Ok. Wszystko jest tak, jak powiedzia³a Diana. Wykona³eœ œwietn¹ robotê. Szczerze mówi¹c, nie spodziewa³em siê tego.}
{355} {} {Wiêc mogê ju¿ iœæ?}
{356} {} {Zas³ugujesz na wolnoœæ i nasze podziêkowania. Mo¿esz przygotowaæ siê do drogi i wyjechaæ, nikt nie bêdzie ci w tym przeszkadza³. Jednak wejœcie tutaj dla wszystkich „normalnych” bêdzie od teraz zamkniête.}
{357} {} {Nie przeszkadza mi to. Do widzenia, Levi.}
{358} {} {I tak nie zamierzam robiæ kolejnego kroku w kierunku tej dziury. Do widzenia.}

{360} {} {Udowodni³eœ swoj¹ lojalnoœæ wobec naszego œwiêtego sojuszu. Wyrzek³eœ siê cz³owieczeñstwa dla ducha. Cieszymy siê, ¿e ciê widzimy, bracie.}
{1360} {} {Udowodni³aœ swoj¹ lojalnoœæ wobec naszego œwiêtego sojuszu. Wyrzek³aœ siê cz³owieczeñstwa dla ducha. Cieszymy siê, ¿e ciê widzimy, siostro.}
{361} {} {Ugh, dziwnie siê czujê. Tak jakbym... siê odrodzi³.}
{1361} {} {Ugh, dziwnie siê czujê. Tak jakbym... siê odrodzi³a.}
{362} {} {Zgadza siê, bracie. Teraz jesteœ now¹ osob¹. Zapomnij o przesz³oœci i ¿yj teraŸniejszoœci¹. Rozwa¿ ostatni¹ ukoñczon¹ misjê.}
{1362} {} {Zgadza siê, siostro. Jesteœ teraz now¹ osob¹. Zapomnij o przesz³oœci i ¿yj teraŸniejszoœci¹. Rozwa¿ ostatni¹ ukoñczon¹ misjê.}
{363} {} {Czy pozwolisz teraz odejœæ Dianie?}
{364} {} {Oczywiœcie. Wypelni³a swoj¹ misjê i zas³u¿y³a na przebaczenie. Ale niech pamiêta, ¿e teraz Inferno jest pod moj¹ kontrol¹. Wszystkie „normalne” osoby nie bed¹ tu mile widziane. Pozwolê jej odejœæ i zabraæ jej rzeczy, ale nie pozwolê jej wróciæ do nas.}
{365} {} {Pozwól mi odejœæ, bracie Levi.}
{366} {} {Wiêc co ty i ja zdecydowaliœmy o mutagenie?}
{367} {} {Twoim zadaniem jest ustawienie dozowników mutagenów w najbardziej ruchliwych miejscach, w których gromadzi siê najwiêcej rozpruwaczy.}
{368} {} {Ok, spróbujê.}
{369} {} {Czyli bêdê musia³ szybko biec, ¿eby nie daæ siê z³apaæ tym ghulom.}
{370} {} {Nie przetrwam na zewn¹trz bez tej zbroi wspomaganej.}
{371} {} {Ale czy nie udawa³o ci siê to ju¿ wczeœniej? W ka¿dym razie nie mogê ufaæ, ¿e tak niebezpieczny przedmiot nie zostanie obrócony przeciwko mojej trzodzie.}
{372} {} {Chcia³bym móc u¿yæ tej zbroi.}
{373} {} {Levi, proszê o zwrot czêœci pancerza wspomaganego. Z jego pomoc¹ moje szanse wzrosn¹ dziesiêciokrotnie.}
{374} {} {Niech tak bêdzie. Oto czêœci. U¿ywaj tej zbroi tylko w dobrych celach.}
{375} {} {Dziêki.}
{376} {} {Badania naukowe wymagaj¹ inwestycji, wiesz o tym?}
{377} {} {Nie mogê ufaæ, ¿e tak niebezpieczny przedmiot nie zostanie obrócony przeciwko mojej trzodzie.}
{378} {} {Diana i ja jesteœmy naukowcami, a nie wojownikami. Potrzebujemy przynajmniej jakiejœ ochrony.}