{100} {} {Widzisz Paladyna Barkleya.}
{101} {} {Widzisz doœwiadczonego wojownika. Jego niezachwiana twarz prezentuje ca³kowit¹ gotowoœæ do walki.}
{102} {} {Build change.}
{103} {} {Dziêki Doc.}
{104} {} {Zdrajca! Umrzesz jak pies!}
{105} {} {Draniu! Zap³acisz za œmieræ moich towarzyszy!}
{106} {} {Pieprzyæ mutantów! Jeszcze trochê, a ich zastrzelê. Trzymasz z nimi?}

{110} {} {Nie wierzê w³asnym oczom! Jak to siê sta³o?}
{111} {} {Witamy w Bractwie.}
{112} {} {Nie dlatego s³u¿ê jako paladyn.}
{113} {} {Hmm, wygl¹da na to, ¿e zespó³ wywiadowczy ma kilka zer w liczbie wroga.}
{114} {} {Ech, przypominaj¹ mi siê dawne czasy...}

# Dialog licznika
{200} {} {Ach, cholera... Prawie ciê zastrzeli³em. Myœla³em, ¿e jesteœ kolejnym mutantem. Czy jesteœ z grupy wsparcia?}
{201} {} {Jakiego wsparcia? O czym ty mówisz?}
{202} {} {Cholera. Wiêc Bractwo nie wys³a³o ciê do pomocy? To Ÿle. Co wiêc robisz w tym cholernym miejscu?}
{203} {} {Jak zawsze szukam przydatnych rzeczy. Zwykle jest ich pe³no w tego typu opuszczonych ruinach.}
{204} {} {Ugh. Wiêc jesteœ padlino¿erc¹? (wzdycha) Wygl¹da na to, ¿e ca³e moje szczêœcie opuœci³o mnie w zesz³ym roku.}
{205} {} {Co to jest?}
{206} {} {Szukam kogoœ. Ale to sprawa osobista.}
{207} {} {Ok... Za³ó¿my, ¿e to prawda. Czy chcia³byœ poszukaæ dla mnie kogoœ innego?}
{208} {} {Straci³eœ kogoœ?}
{209} {} {To ja odpowiedzia³em na proœbê o pomoc przez radio.}
{1209} {} {To ja odpowiedzia³am na proœbê o pomoc przez radio.}
{210} {} {Przynajmniej jedna dobra wiadomoœæ przez ca³y dzieñ.}
{211} {} {Powiedz mi, co siê sta³o.}
{212} {} {Powinieneœ by³ strzeliæ, idioto. Teraz moja kolej...}
{213} {} {Wiêc jesteœ z Bractwa Stali? Nienawidzê was wszystkich. Giñ, szumowino!}

{220} {} {Tak, Bractwo Stali wys³a³o mnie na misjê ratunkow¹.}
{221} {} {Hmm. Nie pamiêtam Ciê. Poka¿ mi swój nieœmiertelnik.}
{222} {} {Nieœmiertelnik? Ale ja nie s³u¿ê Bractwu. Pracujê jako najemnik.}
{223} {} {Aha. Ostrze¿ono mnie, ¿e Bractwo w Arizonie nie jest w najlepszym stanie. To smutne. Gdzie s¹ inni?}
{224} {} {O kim ty mówisz? Jestem sam.}
{1224} {} {O kim ty mówisz? Jestem sama.}
{225} {} {Cholera! O czym oni myœl¹? Z jakim najemnikiem poradzê sobie w takiej sytuacji? Jednak z drugiej strony ma³a grupa ma taktyczn¹ przewagê wœród ruin... Dobra, naprawdê mam nadziejê, ¿e przynajmniej siê nie zgubisz.}
{226} {} {Wiêc co siê sta³o?}
{227} {} {Um... Tutaj, mam nieœmiertelnik Bractwa. Czy teraz mi wierzysz?}
{228} {} {Znam imiê i nazwisko na tym nieœmiertelniku. Masz jedn¹ próbê usprawiedliwienia swoich k³amstw.}
{229} {} {Um... Cholera. Giñ!}
{230} {} {Tak, nie jestem z Bractwa. Po prostu wydawa³o mi siê, ¿e zamierzasz mnie zastrzeliæ...}
{231} {} {Ugh, g³upcze, jak mam ci teraz zaufaæ?}
{232} {} {Mo¿e mo¿esz mi powiedzieæ, co siê sta³o, a ja spróbujê Ci pomóc?}
{233} {} {S³uchaj, wiem, ¿e masz k³opoty. Teraz nie ma znaczenia, kto gdzie s³u¿y. Wa¿ne jest, aby pomagaæ sobie nawzajem.}
{234} {} {Ok. Nie próbuj wiêcej mnie oszukiwaæ. Nienawidzê k³amstw.}
{235} {} {Uch, dobrze. Mo¿e wiêc powiedz prawdê, co tu robisz?}

{240} {} {Mój oddzia³ wpad³ w zasadzkê zastawion¹ przez lokalne stworzenia. W ca³ym tym zamieszaniu straci³em resztê zespo³u i nie mogê do nich dotrzeæ. Podczas walki kontuzjowa³em te¿ nogê.}
{241} {} {Jesteœ z wojska, prawda? Masz spore uzbrojenie.}
{242} {} {Rozumiem. Operacja nie powiod³a siê, zanim jeszcze siê rozpoczê³a.}
{243} {} {Nikt nie spodziewa³ siê napotkaæ oporu w tych ruinach. Myœleliœmy, ¿e nie ma tu ¿ycia, wiêc szliœmy przez miasto, aby nie napotkaæ mutantów na pustyni.}
{244} {} {Ok. Wiêc jaki masz plan?}
{245} {} {Muszê zebraæ dru¿ynê, jeœli jest jeszcze ktoœ do zebrania. I jakoœ ogarn¹æ siê, aby kontynuowaæ podró¿ do celu... Hej, spe³nisz swój obywatelski obowi¹zek - wyœwiadczysz mi przys³ugê?}
{246} {} {Oczywiœcie. Nie mogê zostawiæ ¿adnej osoby w tarapatach.}
{247} {} {Wiedzia³em, ¿e mo¿na na tobie polegaæ. Jeœli ukoñczê swoj¹ misjê, nie pozostanê d³u¿ny.}
{248} {} {Zgadza siê.}
{249} {} {Nie masz szczêœcia, ¿o³nierzu. Nie nale¿ê do tych, którzy przejmuj¹ siê problemami innych ludzi. Oddaj ca³¹ swoj¹ amunicjê w sposób polubowny...}
{250} {} {To wszystko jest strasznie niebezpieczne. Dlaczego mia³bym ryzykowaæ?}
{251} {} {Nie martw siê o nagrodê. Kiedy dotrzemy do bazy, zostaniesz hojnie wynagrodzony.}
{252} {} {Naprawdê mam tak¹ nadziejê.}
{253} {} {A tak przy okazji. Nazywam siê Paladyn Barkley. Na razie mo¿esz siê tu rozejrzeæ. Ale uwa¿aj przy wyjœciu, zastawi³em tam kilka pu³apek.}
{254} {} {Ok.}
{255} {} {Nie interesuj¹ mnie nagrody. Moja wioska potrzebuje ochrony.}
{256} {} {Jeœli dotrzemy do bazy, porozmawiam ze starszymi o twoim problemie. Do tego czasu pomó¿ mi.}
{257} {} {Ok.}

{260} {} {Poka¿ mi, jak siê st¹d bezpiecznie wydostaæ.}
{261} {} {W korytarzu s¹ pu³apki. Uwa¿nie obserwuj swoje kroki.}
{262} {} {Dziêki.}
{263} {} {S³uchaj, mam kilka pytañ.}

# Powtarzajacy siê dialog
{300} {} {Zg³oœ sytuacjê.}
{301} {} {W porz¹dku.}
{302} {} {Tak?}
{303} {} {Musimy porozmawiaæ.}
{304} {} {Co chcesz wiedzieæ?}
{305} {} {Przestañ mówiæ.}
{306} {} {Przestañ mówiæ. Nie mamy teraz na to czasu.}
{307} {} {Tak, prawdopodobnie masz racjê.}
{308} {} {Jeszcze trochê, a zastrzelê wszystkich tych mutantów!}
{309} {} {Dalej, chodŸmy.}

{310} {} {Wiêc co powinienem zrobiæ?}
{311} {} {Wylecz moj¹ kontuzjê i znajdŸ resztê mojej dru¿yny. Nastêpnie omówimy dalszy plan.}
{312} {} {Zadanie jest jasne.}
{313} {} {To powa¿na rana. Mogê nie byæ w stanie sobie z tym poradziæ.}
{314} {} {Po prostu u¿yj jakiegoœ lekarstwa. By³o w rzeczach w naszym konwoju. Poœpiesz siê, zanim ghule wszystko zniszcz¹.}
{315} {} {Jak ci siê to sta³o?}
{316} {} {Wszed³em w pu³apkê. Te stworzenia zastawi³y ich pe³no na naszej drodze i stworzy³y zas³onê dymn¹. Skurwysyny, daliœmy siê porobiæ jak nowicjusze...}
{317} {} {Rozumiem. Powtórzmy nasz plan.}
{318} {} {Zaczynam swoje zadanie.}
{319} {} {Wyruszam na poszukiwania.}

{320} {} {Kto jeszcze by³ w twojej dru¿ynie?}
{321} {} {Kilka osób. Po³owa z nich na pewno nie ¿yje, o reszcie nic nie wiem.}
{322} {} {Kontynuuj.}
{323} {} {Wyruszam na poszukiwania.}
{324} {} {Ostatnio skontaktowa³ siê ze mn¹ giermek w okolicy supermarketu, ale od tamtej pory nic nowego.}
{325} {} {Jeden z rycerzy zaj¹³ pozycjê obronn¹ w miejscu zasadzki, tu¿ obok pomnika.}
{326} {} {By³a z nami równie¿ Diana, pochodzi z Wyznawców Apokalipsy. S³ysza³em jej krzyki w oddali, najwyraŸniej ghule j¹ gdzieœ zaci¹gnê³y.}
{327} {} {Kto jeszcze by³ w zespole?}
{328} {} {A jeœli wszyscy nie ¿yj¹?}
{329} {} {W takim razie muszê zebraæ ich nieœmiertelniki z nazwiskami, aby z³o¿yæ raport dowództwu i uczciæ ich pamiêæ.}
{330} {} {Gdzie mia³ miejsce atak na konwój?}
{331} {} {To by³o na pó³nocnym zachodzie, przy drodze numer piêæ. Tuz obok jakiegoœ pomnika.}
{332} {} {Rozumiem.}
{333} {} {Nie rozumiem, jak ghule by³y w stanie pokonaæ konwój zbrojny?}
{334} {} {Te stworzenia, choæ dzikie, s¹ wystarczaj¹co inteligentne, by skutecznie walczyæ. NajwyraŸniej d³ugie ¿ycie w ruinach wiele je nauczy³o.}
{335} {} {Co zrobili?}
{336} {} {Wpadliœmy w zasadzkê. Upiory zastawi³y pu³apki na drodze i zwabi³y nas w najbardziej niewygodne miejsce do obrony. Otoczyli nas i zaczeli rzucaæ workami z kurzem. Przez to wokó³ unosi³a siê jakby zas³ona dymna, z której wszyscy byli wyci¹gani jeden po drugim.}
{337} {} {Kontynuuj.}
{338} {} {Mieliœmy do czynienia z tymi stworzeniami wczeœniej, ale tym razem by³o ich zbyt wiele. A kiedy zacz¹³ siê frontalny atak, tylko ja sobie poradzi³em. Musia³em siê wycofaæ... Cholera, jaka szkoda, ¿e nie mia³em czasu u¿yæ zbroi wspomaganej!}
{339} {} {Przykro mi.}
{340} {} {Wszyscy pope³niamy b³êdy, paladynie. Nie jesteœ wyj¹tkiem.}
{341} {} {Ktoœ jeszcze?}
{342} {} {Ok. Zobaczmy, co tam zosta³o.}
{343} {} {Masz powa¿n¹ ranê. Co mogê zrobiæ?}
{344} {} {Prawie wróci³em do normalnoœci. Pozostaje znaleŸæ zaginionych cz³onków dru¿yny. Nastêpnie omówimy dalszy plan.}
{345} {} {Musimy znaleŸæ Dianê. Mo¿e nadal ¿yje i potrzebuje pomocy.}
{346} {} {Musimy znaleŸæ Dianê. Mo¿e nadal ¿yje i potrzebuje pomocy. Przyda³aby mi siê te¿ pomoc medyczna.}
{347} {} {Uda³o mi siê znaleŸæ cia³o rycerza. Bêdê kontynuowaæ poszukiwania.}
{348} {} {Uda³o mi siê znaleŸæ cia³o giermka. Bêdê kontynuowaæ poszukiwania.}

{350} {} {Twoi bracia nie ¿yj¹. Oto ich nieœmiertelniki. Przykro mi.}
{351} {} {Zgineli walcz¹c jak prawdziwi wojownicy. B³ogos³awiona pamiêæ o nich... A co z dziewczyn¹? Mieliœmy ¿e sob¹ cywila, nauczyciela z Wyznawców Apokalipsy.}
{352} {} {Nic o niej nie wiem.}
{353} {} {Muszê wiedzieæ na pewno. Komenda wyda³a wyraŸny rozkaz - eskortowaæ j¹ do celu. Zosta³a mi powierzona pod ochronê. Nie mogê sprzeciwiæ siê rozkazom, pozostawiaj¹c j¹ samej sobie.}
{354} {} {Spróbujê dowiedzieæ siê, co siê z ni¹ sta³o.}
{355} {} {Diana jest przymusowo przetrzymywana w starym budynku koœcio³a.}
{356} {} {Przetrzymywana? Przez kogo?! Te mutanty nawet nie potrafi¹ elokwentnie mówiæ.}
{357} {} {Nie, nie ci, inni. Maj¹ tam jakiœ kult.}
{358} {} {Nie rozumiem. Mo¿e ten kult kieruje ghulami? Potrzebujê wiêcej informacji. Ale jeszcze wa¿niejsze jest uratowanie Diany z niewoli.}
{359} {} {Wymyœlê, jak to zrobiæ.}
{360} {} {Diana nie ¿yje. Na pewno.}
{361} {} {To Ÿle. Czeka mnie nagana, a mo¿e nawet s¹d wojskowy z powodu tej dziewczyny. Nie chcia³bym wracaæ do dusznego bunkra w Kalifornii. Ok, dziêki za pomoc, towarzyszu.}
{362} {} {Czy to wszyscy, których szuka³eœ?}
{363} {} {Diana czeka na nas przy wyjœciu. Mo¿esz z ni¹ porozmawiaæ.}
{364} {} {Niez³a robota towarzyszu. Jestem ci bardzo wdziêczny.}
{365} {} {Czy to wszyscy, których szuka³eœ?}
{366} {} {Diana opuœci³a ju¿ miasto. Nie chcia³a zostaæ w tym piekle ani chwili d³u¿ej.}
{367} {} {Posz³a bez eskorty? To suka. Ryzykowa³em tutaj swoje ¿ycie, próbuj¹c j¹ znaleŸæ... Dobra, niech idzie gdzie chce. Teraz to ju¿ nie mój problem.}
{368} {} {Czy to wszyscy, których szuka³eœ?}
{369} {} {Uda³o mi siê znaleŸæ Dianê.}
{370} {} {Co siê z ni¹ dzieje? Czy ona ¿yje?}
{371} {} {Pójdê poszukaæ pozosta³ych.}
{372} {} {Zgineli walcz¹c jak prawdziwi wojownicy. B³ogos³awiona pamiêæ o nich...}
{373} {} {Dobrze. Ale nadal nie mogê wróciæ do bazy bez wykonania g³ównego zadania.}
{374} {} {Co to za zadanie?}
{375} {} {Dostawa pancerza wspomaganego. To by³ g³ówny ³adunek, który przewoziliœmy do bazy w Puerto. Teraz zbroja ta jest w rêkach rozpruwaczy. To ogromna strata.}
{376} {} {Pancerza wspomaganego nie ma ju¿ w miejscu, w którym zosta³eœ zaatakowany. Mutanci zaci¹gneli j¹ wraz z innymi rzeczami do starego koœcio³a.}
{377} {} {Wiêc musimy j¹ odzyskaæ. NajwyraŸniej ju¿ wiesz, jak tam wchodziæ i wychodziæ bez wiêkszego ryzyka. Liczê na ciebie, towarzyszu.}
{378} {} {Nie bêdzie ³atwo odzyskaæ ten sprzêt. Ale tak naprawdê - kto inny, jeœli nie ja? Idê na t¹ misjê.}
{379} {} {Mam na sobie t¹ zbrojê. Gdyby nie ona, nie wyszed³bym stamt¹d ¿ywy.}
{1379} {} {Mam na sobie t¹ zbrojê. Gdyby nie ona, nie wysz³abym stamt¹d ¿ywa.}
{380} {} {Dostawa pancerza wspomaganego. WieŸliœmy ten pancerz do bazy w Puerto. Bêdziesz musia³ zwróciæ j¹ do naszej bazy.}
{381} {} {Dobra robota. Ale bêdziesz musia³ zwróciæ j¹ do naszej bazy.}
{382} {} {Co, mam oddaæ tê zbrojê? Nie chcesz za wiele?}
{383} {} {To jest w³asnoœæ Bractwa Stali. Masz jakiœ problem, cywilu?}
{384} {} {Tak. Problem. Przez Ciebie. Zbroja jest teraz moja!}
{385} {} {Nie, nie mam problemu. Chêtnie siê jej pozbêdê. Tylko mi wadzi.}
{386} {} {Oczywiœcie, ¿e chcia³bym pozbyæ siê niepotrzebnego ³adunku.}
{387} {} {Dziêkujê za pomoc. Bêdziesz œwietnym wojownikiem. Kiedy dotrê do bazy, powiadomiê o Tobie ca³¹ bazê. Do tego czasu zanies zbrojê kwatermistrzowi. Nadal muszê zregenerowaæ si³y przed podróz¹.}
{388} {} {Do zobaczenia w bazie, Paladynie Barkley.}
{389} {} {Przepraszam, ale ju¿ zabra³em zbrojê do kwatermistrza w Puerto.}
{1389} {} {Przepraszam, ale ju¿ zabra³am zbrojê do kwatermistrza w Puerto.}
{390} {} {Dziêkujê za pomoc. Bêdziesz œwietnym wojownikiem. Kiedy dotrê do bazy, powiadomiê o Tobie ca³¹ bazê. Do tego czasu muszê odzyskaæ si³y przed podróz¹.}
{391} {} {Do zobaczenia w bazie, Paladynie Barkley.}
{392} {} {Dziêkujê za pomoc. Przypominasz mi jednego mieszkañca Krypty, który pomóg³ nam kiedyœ uporaæ siê z super mutantami w Kalifornii. Zaden cywil nie by³ nigdy wczeœniej tak przydatny dla Bractwa. Tak trzymaj, wojowniku.}
{393} {} {Ze wzglêdu na Bractwo warto spróbowaæ. Czy nie masz nic przeciwko, jeœli bêdziemy kontynuowaæ nasz¹ podró¿?}
{394} {} {Dobrze. Teraz mogê z czystym sumieniem udaæ siê do bazy. Chocia¿ ju¿ wyobra¿am sobie, jaki wstyd mnie tam czeka. Ca³y oddzia³ zgin¹³, a ³adunek zagin¹³. Zostanie to na d³ugo zapamiêtane, nawet jeœli trybuna³ przyzna, ¿e zrobi³em wszystko dobrze.}
{395} {} {Twoi bracia prawdopodobnie ciê zrozumiej¹.}
{396} {} {Na pewno masz k³opoty. Nie ma co do tego w¹tpliwoœci.}
{397} {} {Dziêkujê za pomoc. Bêdziesz œwietnym wojownikiem. Kiedy dotrê do bazy, powiadomiê o Tobie ca³¹ bazê. Do tego czasu muszê zregenerowaæ si³y przed podróz¹.}
{398} {} {Mo¿e kiedyœ znów siê zobaczymy. Powodzenia.}
{399} {} {W takim razie mo¿e chodŸ ze mn¹? Potrzebujê wsparcia bojowego.}

#Zespol
{400} {} {Chcesz do mnie do³¹czyæ? Przyda mi siê ochrona doœwiadczonego wojownika.}
{401} {} {Nie ma co do tego w¹tpliwoœci. Ale jak widzisz, nie jestem teraz w odpowiedniej formie. Z tak¹ kontuzj¹ ledwo mogê siê broniæ.}
{402} {} {Rozumiem. Ale mo¿e chocia¿ mo¿emy porozmawiaæ?}
{403} {} {Ok, poradzê sobie sam.}
{404} {} {Nie ma co do tego w¹tpliwoœci. Razem ³atwiej obroniæ siê przed rozpruwaczami. Ale to nie jest obecnie najlepsza taktyka.}
{405} {} {Gdybyœ by³ ¿o³nierzem, pewnie bym tob¹ dowodzi³. Ale przy takim t³umie stracimy jak¹kolwiek przewagê taktyczn¹. Pozb¹dŸ siê balastu, jeœli chcesz mojej ochrony.}
{406} {} {Wiêc wycofujê swoj¹ ofertê.}
{407} {} {Ok, porozmawiam z innymi.}
{408} {} {Mam u Ciebie d³ug. Jeœli wybierasz siê do naszej bazy w Puerto, mogê Ci towarzyszyæ.}
{409} {} {Tak. W³aœnie tam idê. ChodŸmy razem.}
{410} {} {Nie. Mam inny cel. Mo¿e innym razem nasze œcie¿ki siê zbiegn¹.}
{411} {} {Musimy teraz schowaæ nasz¹ broñ.}
{412} {} {Zwariowa³eœ? Chcesz naszej zguby?}
{413} {} {To naprawdê g³upie. Zapomnij.}
{414} {} {Nie, musimy okazaæ nasze pokojowe zamiary, aby nie powodowaæ konfliktów.}
{415} {} {Hmm. W porz¹dku. Ale pamiêtaj - wyci¹gam pistolet w 0,75 sekundy.}
{416} {} {Swietnie.}
{417} {} {Za³ó¿ swoj¹ star¹ zbrojê.}
{418} {} {Bardzo chêtnie. Stara by³a mojego rozmiaru.}
{419} {} {Swietnie.}
{420} {} {Broñ tego stanowiska. Muszê siê zbli¿yæ samemu.}
{421} {} {Dobry pomys³. IdŸ na rekonesans, podczas gdy ja wyczyszczê amunicjê.}
{422} {} {Uch, dobrze.}
{423} {} {Przygotuj siê. Mo¿emy iœæ dalej.}
{424} {} {Wska¿ drogê. Mam nadziejê, ¿e znasz bezpieczn¹ trasê.}
{425} {} {Uch, oczywiœcie. ChodŸmy.}
{426} {} {Czas siê po¿egnaæ. Dalej nasze œcie¿ki siê rozchodz¹.}
{427} {} {Na pewno? W porz¹dku. Ale nie zapomnij o starym Barkleyu, bracie.}
{1427} {} {Na pewno? W porz¹dku. Ale nie zapomnij o starym Barkleyu, siostro.}
{428} {} {Nie zapomnê. Do zobaczenia, Paladynie Barkley.}
{429} {} {Co ja robiê? Chcê, ¿ebyœ nie sta³ siê œniadaniem œwiec¹cych mrówek.}
{430} {} {ChodŸ ze mn¹. Potrzebujê ochrony doœwiadczonego wojownika.}
{431} {} {Ale bez twojej ochrony móg³bym umrzeæ.}
{432} {} {Zaufaj mi, bardziej prawdopodobne jest to, ¿e samemu d³u¿ej pozostaniesz w cieniu. Ja tylko zwrócê niepotrzebnie uwagê ghuli.}
{433} {} {Rozumiem.}
{434} {} {Na pewno nie dam sobie rady bez ciebie. Jeœli odmówisz udzia³u, opuszczê miasto.}
{435} {} {Wiedzia³em, ¿e nie mogê na tobie polegaæ... Ok, noga nie boli tak bardzo, mogê siê ruszaæ.}
{436} {} {To dobrze.}
{437} {} {Wiesz, jednak bêdziesz tylko ciê¿arem. Wolê zostaæ solo. Bywaj.}
{438} {} {Mam u Ciebie d³ug. Jeœli potrzebujesz ochrony i eskorty, jestem do Twojej dyspozycji.}
{439} {} {Daj spokój, przed nami d³uga i niebezpieczna droga.}

{450} {} {Co myœlisz o tym miejscu?}
{451} {} {Nic specjalnego. Nie ma sensu tu siedzieæ.}
{452} {} {Rozumiem.}
{453} {} {To jest placówka Bractwa. Witamy. Nale¿y jednak pamietaæ, ¿e jest to obiekt wojskowy. Dowódcom nie spodoba siê, jeœli bêdziesz tu biegaæ bez pozwolenia.}
{454} {} {Nadal nie mogê uwierzyæ, ¿e nasz fort zosta³ zniszczony. S³u¿yli w nim najlepsi z najlepszych.}
{455} {} {Kolejne ruiny jakiegoœ starego miasta. Ca³a Kalifornia le¿y w takich ruinach.}
{456} {} {Po Inferno to miejsce wygl¹da jak raj. I wygl¹da na to, ¿e jest w to zaanga¿owane Bractwo Stali.}
{457} {} {Wydaje mi siê, ¿e to tu mieszkaj¹ Blacharze. Bractwo mia³o z nimi kontrakt na utrzymanie placówki.}
{458} {} {Du¿e rozwijaj¹ce siê miasto. W Kalifornii mo¿na z nim porównaæ tylko Hub. Mi³o widzieæ, jak cywilizacja podnosi siê na nogi.}
{459} {} {Czyta³em o tym koœciele w zapisach skrybów. Lokalny przywódca wydaje siê mieæ dobre stosunki z Bractwem.}
{460} {} {Przepraszam, to s¹ tajne informacje, nie mogê z tob¹ o tym rozmawiaæ.}
{461} {} {Dobra organizacja. Chocia¿ w naszym Bractwie daleko im do porz¹dku.}
{462} {} {To nie jest jakaœ tam zwyk³a kryjówka. To Krypta.}
{463} {} {To jest w³aœnie nasza placówka. Oczywiœcie nie mo¿e równaæ siê z g³ówn¹ baz¹. Ale lepsze to ni¿ nic.}
{464} {} {Powiedzia³bym ci coœ o tym miejscu, ale ju¿ doskonale wszystko wiesz, bracie.}
{1464} {} {Powiedzia³bym ci coœ o tym miejscu, ale ju¿ doskonale wszystko wiesz, siostro.}
{465} {} {Nie mam nic innego do roboty. Bez Bractwa mogê pomagaæ tylko ludziom takim jak Ty.}
{466} {} {Oto fort, do którego zmierza³eœ. Nie jesteœ szczêœliwy?}
{467} {} {Jestem ca³kowicie rozczarowany. Sztab generalny w Kalifornii bêdzie z³y, jeœli dowiedz¹ siê, jak siê tu sprawy maj¹. Wiesz, nie mam nic przeciwko eskortowaniu ciê do najbli¿szych osad. Chcia³bym zaczerpn¹æ jeszcze trochê œwie¿ego powietrza przed powrotem do s³u¿by.}
{468} {} {Inferno wci¹¿ nie daje o sobie zapomnieæ, co? Rozumiem.}

{470} {} {Opowiedz mi o swoim Bractwie.}
{471} {} {Nie mogê ci zbyt wiele powiedzieæ. Niektóre informacje mog¹ mieæ wartoœæ strategiczn¹.}
{472} {} {No to chodŸmy.}
{473} {} {Gdzie jest g³ówna baza Bractwa?}
{474} {} {Rozumiem. To wszystko, co mnie interesowa³o o Bractwie.}
{475} {} {Gdzie jest twoja lokalna baza?}
{476} {} {Na wybrze¿u zatoki w Rocky Point. Miejscowi nazywaj¹ to po prostu Puerto.}
{477} {} {To jest pytanie, które nale¿y zadaæ dowódcy. Ja jestem tylko ¿o³nierzem wykonuj¹cym rozkazy.}
{478} {} {Co robisz na pustyni Sonora?}
{479} {} {Sztab generalny jest daleko w Kalifornii. A tutaj, na pustyni Sonora, mamy ma³y fort.}
{480} {} {Nie chce o tym rozmawiaæ. Taka œmieszna pora¿ka w Puerto nape³nia mnie tylko z³oœci¹.}
{481} {} {Nie mogê uwierzyæ...}
{482} {} {Wszystko w porz¹dku?}
{483} {} {Moi bracia i siostry... Taka absurdalna œmieræ... Co tu siê sta³o?}
{484} {} {Z pewnoœci¹ by³o to zaniedbanie jakiegoœ intendenta lub jakiœ wyciek.}
{485} {} {Bzdury! Zawsze byliœmy ostro¿ni z broni¹ i wyposa¿eniem! Nie wierzê, ¿e by³ to b³¹d kogoœ z personelu. To móg³ byæ tylko sabota¿.}
{486} {} {Có¿, macie wielu wrogów...}
{487} {} {Ok, przepraszam, ¿e krzycza³em. Po wydarzeniach w Inferno zadanie Bractwu takiego ciosu to za du¿o.}
{488} {} {Rozumiem. Ale teraz jesteœ ca³kowicie wolny od przepisów i nakazów, prawda?}
{489} {} {Nie s¹dzê, ¿ebym móg³ znieœæ ¿ycie na jakiejœ wsi na tych dzikich ziemiach. Powinniœmy iœæ dalej. ProwadŸ, wci¹¿ jestem z tob¹, towarzyszu.}
{490} {} {ChodŸmy.}
{491} {} {NajwyraŸniej ktoœ bardzo nie lubi Twojego Bractwa.}
{492} {} {Tak! To móg³ byæ tylko sabota¿.}
{493} {} {Wysadzi³em kilka torped w ³adowni. Masz z tym problem?}
{1493} {} {Wysadzi³am kilka torped w ³adowni. Masz z tym problem?}
{494} {} {Dlaczego?! Co Bractwo ci takiego zrobi³o?!}
{495} {} {Spowodowaliœcie zbyt wiele problemów w Sonorze. Nie nale¿ycie tutaj.}
{496} {} {Nie wiem. Chcia³em tylko zobaczyæ wielki wybuch.}
{497} {} {Myœlê, ¿e po prostu nacisn¹³em z³y przycisk. Nie wiem, jak to siê sta³o.}
{1497} {} {Myœlê, ¿e po prostu nacisnê³am z³y przycisk. Nie wiem, jak to siê sta³o.}
{498} {} {Jesteœ diab³em w ludzkiej skórze! Powinieneœ umrzeæ w ³onie matki!}
{499} {} {No có¿.}