{100}{}{Widzisz przed sob¹ Przewodnika.}
{101}{}{Widzisz mê¿czyznê w starej plemiennej szacie. G³owê i rece ma owiniête banda¿ami.}
{102}{}{Tutaj nasze drogi siê rozchodz¹. Aby wróciæ do Sonory, poczekaj na nastêpn¹ karawanê w pobli¿u tej flagi.}
{103}{}{Mi³o ciê widzieæ, istoto o g³adkiej skórze.}

{200}{}{Cz³owieku, to miejsce jest niebezpieczne dla ludzi takich jak ty.}
{201}{}{Co Ty tutaj robisz?}
{202}{}{Hm. Widzia³eœ jakiegoœ GHULA? Znaczy, ludzi z dziuraw¹ skór¹, którzy ¿yj¹ wiecznie? Szukam ich, ¿eby wys³aæ ich do ruin San Diego.}
{203}{}{Dlaczego ghule gromadz¹ siê w ruinach San Diego?}
{204}{}{Kiedyœ naszym domem by³o Nekropolis. Z powodu armii supermutantów miasto zosta³o spustoszone, a ghule rozproszy³y siê po pustkowiach. Zewsz¹d nas wypêdzano. A¿ wreszcie stworzyliœmy nowe miasto - Blask Dnia. Jest otwarte dla wszystkich ghuli i mutantów, którzy chc¹ dzieliæ wspólnie nasze brzemiê.}
{205}{}{Chcê do ciebie do³¹czyæ.}
{206}{}{Wiêc jesteœ na z³ej drodze. Poœpiesz siê.}
{207}{}{W Blasku mo¿esz umrzeæ od napromieniowania, istota o g³adkiej skórze. A jeœli nie, to same ghule raczej ciê nie zaakceptuj¹. W koñcu ludzie zawsze nas wypêdzali. Pomyœl o tym, czy jesteœ gotowy na takie wyzwanie?}
{1207}{}{W Blasku mo¿esz umrzeæ od napromieniowania, istota o g³adkiej skórze. A jeœli nie, to same ghule raczej ciê nie zaakceptuj¹. W koñcu ludzie zawsze nas wypêdzali. Pomyœl o tym, czy jesteœ gotowa na takie wyzwanie?}
{208}{}{Ja te¿ nie pasujê do tego œwiata. Myœlê, ¿e odwiedziny nowego miejsca dobrze mi zrobi¹.}
{209}{}{Jakiœ tajemniczy nieznajomy wezwa³ mnie do Blasku Dnia. Nie mogê tego tak po prostu zignorowaæ.}
{210}{}{To wszystko brzmi raczej odpychaj¹co. OpóŸni to moj¹ podró¿. Do widzenia.}
{211}{}{No có¿, decyzja nale¿y do ciebie.}
{212}{}{Opowiedz mi o œcie¿ce.}
{213}{}{Dlaczego ghule jad¹ do San Diego?}

{220}{}{Nasze drogi ponownie siê skrzy¿owa³y. Czy to nie przeznaczenie?}
{221}{}{Nie, to tylko przypadek. Do widzenia.}
{222}{}{Chcê iœæ z tob¹ do Blasku Dnia.}

{230}{}{Swietny zestaw! Przypominasz mi upiory z Nekropolis we wczesnym stadium choroby. Ale jakoœ ciê nie pamiêtam. Czy jesteœ nowym dzieckiem Mistrza?}
{231}{}{Nie pochodzê z Nekropolis, ani nie jestem dzieckiem Mistrza. Stworzy³ mnie ktoœ o imieniu Levi.}
{232}{}{Levi? Znam go. Jest jednym z najwiêkszych dzie³ Mistrza. Ale on patrzy z góry na ludzi takich jak my. Wiêc jesteœ ofiar¹ jego eksperymentów? Szkoda mi Ciebie. Teraz poznasz gorycz ¿ycia ghula.}
{233}{}{Czujê siê dobrze tak jak jest. Nie wiem w czym widzisz problem.}
{234}{}{To prawda, wszyscy mnie unikaj¹. Nawet krewni.}
{235}{}{}
{236}{}{}
{237}{}{Wiêc chodŸ z nami. Budujemy dom dla ludzi takich jak Ty i ja.}
{238}{}{Dom dla mutantów? Gdzie to jest?}
{239}{}{Ghule buduj¹ nowe miasto na ruinach San Diego. Swój w³asny œwiat. Szukam i kierujê tam wszystkie ghule, które jeszcze nie straci³y resztek œwiadomoœci. Mamy tam dla ciebie miejsce.}
{240}{}{Dobrze. Pójdê z tob¹ do San Diego.}
{241}{}{Nie mogê jeszcze opuœciæ tych krain. Ale bêdê pamiêtaæ, ¿e czeka na mnie inne miejsce na pustkowiach.}

{250}{}{Bêdziemy musieli tu zostawiæ naszych przyjació³. I mo¿esz zabraæ tylko najpotrzebniejsze rzeczy, nie wiêcej ni¿ 20 funtów. Podró¿ujemy lekko przez spalone krainy, szybko jak wiatr.}
{251}{}{Nie ma mowy. Nie zostawiê swoich rzeczy!}
{252}{}{Czy mogê wróciæ, jeœli mi siê tam nie spodoba?}
{253}{}{Wróciæ, tak. Ale na moj¹ eskortê mo¿esz liczyæ tylko raz.}
{254}{}{Wiêc musze pomyœleæ. Znajdê ciê, jeœli siê zdecydujê.}
{255}{}{Jestem gotowy.}
{1255}{}{Jestem gotowa.}
{256}{}{Wkrótce znajdziesz siê w innym œwiecie, przyjacielu.}
{1256}{}{Wkrótce znajdziesz siê w innym œwiecie, przyjació³ko.}
{257}{}{[DALEJ]}
{258}{}{Masz za du¿o rzeczy.}
{259}{}{Mam za du¿o rzeczy. Wrócê, gdy je gdzieœ schowam.}