{102} {} {otrzymuje jednego kapsla.}
{103} {} {Ten element tutaj nie pomo¿e.}
{104} {} {To nie pomo¿e.}
{105} {} {Ta umiejêtnoœæ tutaj nie pomo¿e.}
{106} {} {Ta osoba odmawia posuniêcia siê dalej.}
{107} {} {To stworzenie nie chce iœæ dalej.}
{108} {} {Ta wroga osoba odmawia pos³uszeñstwa.}
{109} {} {To wrogie stworzenie odmawia pos³uszeñstwa.}

# ---------------------------------------------
# Nazwy umiejêtnoœci i podstawowe parametry
# ---------------------------------------------
{110} {} {Ma³a broñ}
{111} {} {Wielka broñ}
{112} {} {Broñ energetyczna}
{113} {} {Walka wrêcz}
{114} {} {Broñ bia³a}
{115} {} {Rzucanie}
{116} {} {Pierwsza pomoc}
{117} {} {Leczenie}
{118} {} {Skradanie}
{119} {} {Otwieranie zamków}
{120} {} {Kradzie¿}
{121} {} {Pu³apki}
{122} {} {Nauki œcis³e}
{123} {} {Naprawa}
{124} {} {Retoryka}
{125} {} {Handel}
{126} {} {Hazard}
{127} {} {Przetrwanie}

{130} {} {Umiejêtnoœæ "}
{131} {} {" zosta³a podniesiona o }
{132} {} {.}

{133} {} {[}
{134} {} {]}

{135} {} {Reputacja}
{136} {} {Reputacja}
{137} {} {Karma}
{138} {} {Level}

{140} {} {}
{141} {} {Z twoimi umiejêtnoœciami jest to niemo¿liwe.}
{142} {} {Ta istota nie mo¿e zostaæ okradziona.}
{143} {} {Ofiara niczego nie zauwa¿y³a. Wychodzisz z sytuacji bez konsekwencji.}
{144} {} {Tym razem uda³o Ci siê przekonaæ ofiarê, ¿e zasz³o nieporozumienie.}
{145} {} {Robota nie mo¿na okraœæ w trybie aktywnym.}
{146} {} {jest zbyt czujny.}
{147} {} {Twoje umiejêtnoœci nie pozwalaj¹ na opatrzenie tych ran bez leków.}
{148} {} {Podczas korzystania z pancerza wspomaganego kradzie¿ kieszonkowa nie jest mo¿liwa.}
{149} {} {Nie mo¿na tego zrobiæ.}

{150} {} {Si³a}
{151} {} {Percepcja}
{152} {} {Wytrzyma³oœæ}
{153} {} {Charyzma}
{154} {} {Inteligencja}
{155} {} {Zrêcznoœæ}
{156} {} {Szczêœcie}

# ---------------------------------------------
# Zdobywanie doœwiadczenia
# ---------------------------------------------

{200} {} {Otrzymano }
{201} {} { punktów doœwiadczenia.}
{202} {} { punktów doœwiadczenia za udany dialog.}
{203} {} { punktów doœwiadczenia i wzrost reputacji.}

# ---------------------------------------------
# Kontuzje
# ---------------------------------------------

{300} {} {Twoja lewa noga zosta³a okaleczona! Czujesz okropny ból.}
{301} {} {Twoja prawa noga zosta³a okaleczona! Czujesz okropny ból.}
{302} {} {Twoja lewa rêka zosta³a okaleczona! Czujesz ostry ból.}
{303} {} {Twoja prawa rêka zosta³a okaleczona! Czujesz ostry ból.}
{304} {} {Twój wzrok zosta³ uszkodzony! Czujesz straszliwy ból.}
{305} {} {Ugh, to zajmie bardzo du¿o czasu, zanim samo siê zagoi...}

# ---------------------------------------------
# Wiadomosci w bitwie
# ---------------------------------------------

{320} {} { waha siê przed atakiem.}
{321} {} { regeneruje siê i przywraca trochê zdrowia.}
{322} {} {!!!}
{323} {} { panikuje na widok ognia.}
{324} {} {leci.}
{325} {} {Cholera!}
{326} {} { traci si³ê i percepcjê, gdy impuls E / M wy³¹cza czêœæ jego elektroniki.}
{327} {} {!}
{328} {} {Nie mo¿na tego zrobiæ podczas walki.}
{329} {} {Pi!}

# ---------------------------------------------
# Odpowiedzi na temat nieskutecznosci (zastosowano niewlasciwy przedmiot, umiejêtnoœæ itp.)
# ---------------------------------------------

{330} {} {Brak u¿ycia}
{331} {} {Ÿle}
{332} {} {Coœ jest nie tak}
{333} {} {Brak efektu}
{334} {} {Nie dzia³a}
{335} {} {Hmm?}
{336} {} {Zbyt trudne}
{337} {} {Brak u¿ycia}
{338} {} {Brak u¿ycia}
{339} {} {Brak u¿ycia}

# ---------------------------------------------
# Repliki po zakoñczeniu spraw (rozminowywanie, naprawy, tankowanie roweru itp.)
# ---------------------------------------------

{340} {} {Gotowe.}
{341} {} {Ok.}
{342} {} {Doskonale.}
{343} {} {Gotowe.}
{344} {} {Dzia³a.}
{345} {} {Sukces.}
{346} {} {Tak!}
{347} {} {Gotowe.}
{348} {} {Gotowe.}
{349} {} {Gotowe.}

# ---------------------------------------------
# Uzywanie ró¿nych przedmiotów na NPC
# ---------------------------------------------

#Consumables
{400} {} {odmawia jedzenia.}
{401} {} {To doœwiadczenie da³o ci pomyslowosc.}
{402} {} {nie bêdzie karmiæ podczas walki.}
{403} {} {odmawia odebrania tego z twoich r¹k.}
{404} {} {Nie dotyczy to robotów.}
{405} {} {Podzielenie siê ¿ywnoœci¹ przynios³o ci doœwiadczenie i pozytywn¹ karmê.}
{406} {} {To nie dotyczy roœlin.}
{407} {} {odmawia przyjêcia tego.}
{408} {} {To stworzenie staje siê dla ciebie bardziej ³askawe.}
{409} {} {Stymulanty dzia³aja tylko na ludzi.}
{410} {} {Zwierzêta i mutanty nie pij¹ alkoholu.}
{411} {} {To nie zadzia³a na tym stworzeniu.}
{412} {} {ulega szkodliwemu dzia³aniu substancji chemicznej i wpada w sza³.}
{413} {} {Alkohol? Nie jestem zainteresowany...}
{414} {} {To jest to, czego tak bardzo mi brakowa³o!}
{415} {} {Nie dra¿nij cz³onków Bractwa w³asnymi racjami ¿ywnoœciowymi, mo¿esz zostaæ wziêty za z³odzieja.}
{416} {} {Wow, to nagroda!}
{417} {} {Czy ty naprawdê chcesz mi to daæ?}
{418} {} {Ten przedmiot nie bêdzie dzia³a³ przez ochronny he³m pancerza wspomaganego.}
{419} {} {Darmowa dawka cennego p³ynu przynios³a Ci doœwiadczenie i pozytywn¹ karmê.}

# Elementy sciolki
{420} {} {Myœlê, ¿e siê przyda.}
{421} {} {Wow! Dziêkujê Ci!}
{422} {} {Dziecko chêtnie przyjmuje twój prezent. Na pewno opowie swoim przyjacio³om o twoim dzia³aniu.}
{423} {} {Dziecko nie chce przyj¹æ Twojego prezentu. Wygl¹da, jakby wyczuwa³o w tobie ukryte zagro¿enie.}
{424} {} {Lopata na pewno tu nie pomo¿e.}
{425} {} {Potrzebujesz umiejêtnoœci hakowania robota, dekoder tu nie pomo¿e.}
{426} {} {Zatrute!}
{427} {} { umiera w strasznych konwulsjach.}
{428} {} { pada martwy.}
{429} {} { traci przytomnoœæ i wkrótce potem umiera.}
{430} {} { przestaje oddychaæ.}
{431} {} {Tego nie mo¿na zrobiæ podczas walki.}
{432} {} {Twój partner wie, dok¹d to zmierza.}
{433} {} {Ooh!}
{434} {} {Niepotrzebnie straszysz dziecko. Prawdopodobnie istnieje bardziej wartoœciowe zastosowanie tego ruchu.}
{435} {} {U¿ycie starej pirotechniki pozwoli³o stworzyæ 20 amunicji sygna³owej.}

# Amunicja
{440} {} {}
{441} {} {}
{442} {} {}
{443} {} {}
{444} {} {}
{445} {} {}
{446} {} {}
{447} {} {}
{448} {} {}
{449} {} {}
{450} {} {}
{451} {} {}
{452} {} {}
{453} {} {}
{454} {} {}
{455} {} {}
{456} {} {}
{457} {} {}
{458} {} {}
{459} {} {}

# Amunicja przedmiotów
{460} {} {}
{461} {} {}
{462} {} {}
{463} {} {}
{464} {} {}
{465} {} {}
{466} {} {}
{467} {} {}
{468} {} {}
{469} {} {}
{470} {} {}
{471} {} {}
{472} {} {}
{473} {} {}
{474} {} {}
{475} {} {}
{476} {} {}
{477} {} {}
{478} {} {}
{479} {} {}

# Inne przedmioty
{480} {} {Zwykle do zamków u¿ywa siê kluczy.}
{481} {} {Niesamowite. A gdy tylko przysz³o Ci do g³owy...}
{482} {} {Broñ powinna byæ u¿ywana w trybie walki, gdy trzymasz j¹ przy sobie.}
{483} {} {Wyleczono wszystkie rany za pomoc¹ zestawu chirurgicznego.}
{484} {} {Wszystkie rany pacjenta zosta³y wyleczone za pomoc¹ zestawu chirurgicznego.}
{485} {} {Ten przedmiot ma byæ u¿ywany z rêki.}
{486} {} {To prawie nie pomaga w naprawianiu robota.}
{487} {} {Odmawia leczenia.}
{488} {} {Nie potrzebujesz leczenia chirurgicznego.}
{489} {} {Ten przedmiot powinien byæ u¿ywany na motocyklu.}
{490} {} {To nie pomo¿e.}
{491} {} {U¿yto staro¿ytnego reliktu.}
{492} {} {Twoja ³opata nie nadaje siê ju¿ do u¿ytku.}
{493} {} {Zestaw chirurgiczny tu nie pomo¿e.}

# ---------------------------------------------
# Opcje dialogowe
# ---------------------------------------------

#Zwierzak
{500} {} {Ta wroga osoba nie chce z tob¹ rozmawiaæ.}
{501} {} {Ten robot zosta³ ju¿ przeprogramowany, aby ciê chroniæ.}
{502} {} {Przeprogramowano robota, ¿eby siê chroni³.}
{503} {} {}
{504} {} {Nie mo¿esz zmieniæ konfiguracji robota, aby siê broniæ.}
{505} {} {Co jest? Grozisz mi?}
{506} {} {Ta osoba nie zamierza siê z tob¹ komunikowaæ, gdy bêdziesz trzymaæ broñ.}
{507} {} {Ta osoba umiera i nie mo¿e teraz mówiæ.}
{508} {} {. ... .}
{509} {} {Negocjacje nie powiod³y siê.}
{510} {} {?}
{511} {} {Widzisz Szaleñca.}
{512} {} {Brak œwie¿ego powietrza}
{513} {} {wstrzymuje oddech w zamrazarce.}
{514} {} {Co jest? Grozisz mi?}
{515} {} {Od³ó¿ broñ, dobrze ci radzê.}
{516} {} {Pancerz wspomagany tylko denerwuje twojego rozmówcê.}
{517} {} {...}
{518} {} {Ten robot nie wydaje siê byæ w stanie mówiæ.}
{519} {} {Ta osoba odmawia pos³uszeñstwa.}

#Computers
{550} {} {Odmowa dostêpu.}
{551} {} {Nie mo¿na tego zrobiæ podczas walki.}
{552} {} {System bezpieczeñstwa zosta³ ju¿ zhakowany.}
{553} {} {W³amanie do systemu bezpieczeñstwa!}
{554} {} {Dostêp przyznany.}
{555} {} {Gra by³a ca³kiem fajna.}
{556} {} {Nie mo¿esz znaleŸæ odpowiedniego has³a.}
{557} {} {Zainstalowano dekoder. To znacznie u³atwi w³amanie siê do komputera.}
{558} {} {Kolejny dekoder ju¿ tu nie pomo¿e. Czas wykazaæ siê umiejêtnoœciami.}
{559} {} {}

# Napraw sprzêt
{570} {} {nie wymaga naprawy.}
{571} {} {Nie mo¿na tego zrobiæ podczas walki.}
{572} {} {}
{573} {} {Nie masz pojêcia, jak mo¿na to naprawiæ. Byæ mo¿e prosta wymiana czêœci rozwi¹¿e problem braku umiejêtnoœci.}
{574} {} {Nie masz pojêcia, jak to naprawiæ.}
{575} {} {Pech! Nie masz szczêœcia i zosta³eœ porazony pr¹dem.}
{576} {} {Czêœci zamienne trochê u³atwiaj¹ naprawê.}
{577} {} {Czêœci zamienne znacznie u³atwiaj¹ naprawê.}
{578} {} {Wiêcej czêœci ju¿ tutaj nie pomo¿e. Czas wykazaæ siê umiejêtnoœciami.}
{579} {} {Widzisz zrywacza.}

# ---------------------------------------------
# Pseudonimy na pierscionek
# ---------------------------------------------

# Wa¿ne: pseudonimy meskie i zenskie s¹ antypodami i pokrywaj¹ siê w liczbach z ró¿nica 50.
# - meski
{600} {} {Crusader}
{601} {} {Scorpio}
{602} {} {Cannibal}
{603} {} {King}
{604} {} {Cezar}
{605} {} {Hidalgo}
{606} {} {Sierzant}
{607} {} {Fang}
{608} {} {Sledgehammer}
{609} {} {Dynamite}
{610} {} {palacz}
{611} {} {Hulk}
{612} {} {Snajper}
{613} {} {Macho}
{614} {} {Pan X}
{615} {} {Wielki Brat}
{616} {} {Wsciekly pies}
{617} {} {Rag}
{618} {} {Rozpruwacz}
{619} {} {Rzeznik}
{620} {} {Leprechaun}
{621} {} {Whisperer}

# - kobiety
{650} {} {Czarna Wdowa}
{651} {} {Scolopendra}
{652} {} {Brain Eater}
{653} {} {Queen}
{654} {} {Kleopatra}
{655} {} {ksiezna}
{656} {} {Sierzant}
{657} {} {Pazury}
{658} {} {Machete}
{659} {} {Magnum}
{660} {} {Napalm}
{661} {} {Ross}
{662} {} {Marine}
{663} {} {Muchacho}
{664} {} {Pani X}
{665} {} {du¿a mama}
{666} {} {Mad Bitch}
{667} {} {Bad Girl}
{668} {} {Aniol}
{669} {} {Wild Jane}
{670} {} {Królewna Sniezka}
{671} {} {Ruby}

# ---------------------------------------------
# Kartografia
# ---------------------------------------------

{1400} {} {Dodano now¹ lokalizacjê do mapy œwiata}
{1401} {} {:}
{1402} {} {.}
{1403} {} {S³yszysz jakieœ podejrzane dŸwiêki. Dochodz¹ z jaskini.}

#Uwaga! Liste nale¿y skopiowac bez zmian z pliku ... / game / MAP.MSG
{1500} {} {Villa}
{1501} {} {Flagpool}
{1502} {} {Garage City}
{1503} {} {San Brahmin}
{1504} {} {Tu-San}
{1505} {} {Puerto}
{1506} {} {Rangers}
{1507} {} {Phoenix City}
{1508} {} {Platforma}
{1509} {} {Casa Grande}
{1510} {} {Hermosillo}
{1511} {} {San Felipe}
{1512} {} {Inferno}
{1513} {} {Casa Nueva}
{1514}{}{-}
{1515} {} {Motel}
{1516} {} {Blask Dnia}
{1517}{}{-}
{1518} {} {Santa Ana}
{1519}{}{-}
{1520} {} {Szakale}
{1521} {} {Pit stop}
{1522} {} {Villa}
{1523} {} {Krypta 27}
{1524} {} {Obóz Bractwa}
{1525} {} {Raiders}
{1526} {} {Pustos}
{1527} {} {Highlands}
{1528} {} {Ruiny}
{1529} {} {Wybrzeze}
{1530} {} {Puerto Penasco}
{1531} {} {Z³oto!}
{1532} {} {Henry Beamis}
{1533} {} {Przydrozna kafejka}
{1534} {} {Bomber}
{1535} {} {Ciezarowka Petro-Chico}
{1536} {} {Krzyk ciszy}
{1537} {} {Kino plenerowe}
{1538} {} {Padre}
{1539} {} {Baron Arizony}
{1540} {} {Opady sniegu}
{1541} {} {Lost Hideout}
{1542} {} {Mobilna forteca}
{1543} {} {Legend-City}
{1544}{}{-}
{1545}{}{-}
{1546} {} {Quartz}
{1547} {} {Przypadkowe spotkanie}
{1548} {} {Camp Winon}