{100} {} {Widzisz komputer.}
{101} {} {Widzisz stary komputer. O dziwo, nadal dzia³a.}

#Dialog
{200} {} {System uruchomiony.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Witamy w elektronicznych aktach Departamentu Policji w Mexicali.}
{204} {} {Ladowanie bazy danych...}

{210} {} {Napad w supermarkecie.}
{211} {} {"... Znasz go od dawna. Jak myœlisz, co spowodowa³o ten akt?"}
{212} {} {Dalej.}
{213} {} {"Co mogê powiedzieæ? Jest weteranem wojennym. Wiesz, ca³y ten horror w Anchorage. I chocia¿ zosta³ nagrodzony za doskona³¹ s³u¿bê, to uraz g³owy pozosta³."}
{214} {} {Dalej.}
{215} {} {"Uraz g³owy? Zosta³ ranny?"}
{216} {} {Dalej.}
{217} {} {"Nie, straci³ rozum! To pewnie przez to wzi¹³ pistolet maszynowy i strzela³ do ludzi w supermarkecie. Dla niego wojna wci¹¿ trwa. Myœla³, ¿e strzela do Czerwonych... ”}
{218} {} {Zatrzymaj nagrywanie.}

{220} {} {Skargi dotycz¹ce prac budowlanych.}
{221} {} {"... Jak mówiê, mój plan jest w pe³ni skoordynowany! Wszystko jest zgodne z prawem! Poza tym jak s¹siedzi udowodni¹, ¿e dosta³em siê do ich trzewi podczas wykopalisk?"}
{222} {} {Dalej.}
{223} {} {„Przypuœæmy, ¿e mówi Pan prawdê. A co z drganiami z prac budowlanych, które uniemo¿liwiaj¹ im odpoczynek? I kurzem, pot³uczonym szk³em i niekoñcz¹cymi siê ciê¿arówkami?}
{224} {} {Dalej.}
{225} {} {"To drogi projekt... Ar-rh, musisz zrozumieæ! Kiedy zacznie siê wojna œwiatowa, a na pewno siê zacznie, nikogo nie bêd¹ obchodziæ wibracje i ciê¿arówki! Budujê schron przeciwbombowy, ¿eby ratowaæ siebie i moj¹ rodzinê. A co zrobi¹ s¹siedzi? Och, przybiegn¹ do mnie z proœb¹ o schronienie. Zobaczysz, oficerze. Zobaczysz... "}
{226} {} {Zatrzymaj nagrywanie.}

{230} {} {Zarzut rasizmu.}
{231} {} {"... Proszê pani, proszê siê uspokoiæ..."}
{232} {} {Dalej.}
{233} {} {"Uspokoiæ siê? Ci barbarzyñcy chc¹ mnie zabiæ! S¹siedzi od dawna próbuj¹ wyrzuciæ mnie z miasta. Tolerowa³am ich wybryki od lat. Ale oni ju¿ przekroczyli wszelkie granice! P³acê drogo za dom i nie pozwolê nikomu oskar¿aæ mnie o powi¹zania z Czerwonymi tylko dlatego, ¿e p³ynie we mnie Chiñska krew. Zrób coœ z tym, jesteœ policjantem! "}
{234} {} {Dalej.}
{235} {} {"Oczywiœcie proszê pani... uh, my te¿ nie tolerujemy rasizmu... Ale proszê zrozumieæ - Pañskie dowody nie wystarcz¹, by udowodniæ, ¿e to s¹siedzi. Martwy kot, napisy na œcianach i anonimowe notatki nie oznaczaj¹ realnego zagro¿enia... Nie mo¿emy... ”}
{236} {} {Dalej.}
{237} {} {"Dlaczego marnujê tutaj swój czas?! Wszystko jasne - wszyscy jesteœcie tutaj rasistami! Rasistami! Daj mi ten papier, wychodzê..."}
{238} {} {Dalej.}
{239} {} {"Ugh... To suka. To jej trzecia wizyta w tym miesi¹cu. Myœlisz, ¿e naprawdê jest jedn¹ z nich, Rodrigo? }
{240} {} {Dalej.}
{241} {} {"Puœæ j¹, Nick. Lepiej pozwoliæ s¹siadom robiæ to co robi¹ ni¿ ¿eby nagle siê okaza³o ¿e faktycznie jest jedn¹ z Czerwonych... O cholera, nie wy³¹czy³em magnetofonu." .. ”}
{242} {} {Zatrzymaj nagrywanie.}

{250} {} {Sprawa Kaktusa.}
{251} {} {"Wiêc cz³owieku. Opowiedz mi, jak * to * naprawdê siê wydarzy³o."}
{252} {} {Dalej.}
{253} {} {"No, my tylko spacerowaliœmy po pustyni i usiedliœmy obok kaktusa. A potem to coœ spad³o na Paco! Nie zrobiliœmy nic z³ego, szczerze, senor!"}
{254} {} {Dalej.}
{255} {} {"Tak. W takim razie jak wyjaœnisz zwêglone œlady lasera na pniu kaktusa? [Cisza] Ch³opaku, nie chcê na ciebie naciskaæ. Chcê ci pomóc. Powiedz mi prawdê, a dostaniesz tylko zawiasy. [Cisza] No dobra. Pomogê ci sobie przypomnieæ. "}
{256} {} {Dalej.}
{257} {} {"Paco wzi¹³ pistolet laserowy swojego ojca bez pozwolenia, a potem zdecydowaliœcie siê przetestowaæ go na kaktusie. Czy tak by³o? [Cisza] Ale kaktus by³ twardy, a ³adunek wyczerpa³ siê zbyt szybko, i zdecydowaliœcie siê wykoñczyæ kaktusa rêcznie? [cisza] Ch³opaki, wiecie, ¿e strzelanie do kaktusów jest nielegalne, nie wspominaj¹c ju¿ o nielegalnym u¿yciu broni... "}
{258} {} {Dalej.}
{259} {} {"Senor! Senor! Tylko nie mów moim rodzicom!"}
{260} {} {Zatrzymaj nagrywanie.}

{270} {} {Sprawa robota.}
{271} {} {"... Wiêc twierdzisz, ¿e robot nie mia³ wad i dzia³a³ samodzielnie?"}
{272} {} {Dalej.}
{273} {} {"Obawiam siê, ¿e to nie do koñca tak... Robot Mister Assistant tylko wykonywa³ swoj¹ pracê. Ale spójrz na akta rodziny Wilsonów! Myœlê, ¿e mieli... pewne problemy w zwi¹zku ”.}
{274} {} {Dalej.}
{275} {} {"Problemy w zwi¹zku? Tak, wiemy, ¿e w ich rodzinie regularnie dochodzi³o do k³ótni. Ale jak to mo¿e wp³yn¹æ na robota, który "tylko wykonywa³ swoj¹ pracê" ?"}
{276} {} {Dalej.}
{277} {} {"No có¿... Robot jest zaprogramowany do pomagania w pracach domowych, a nie do odczytywania prawdziwyh intencji wypowiedzi. Kiedy matka Wilsonów grozi³a, ¿e "zrobi kotlety" ze swojego syna, a syn prosi robota o "uciszenie rodziców"... sk¹d mia³em wiedzieæ, ¿e powiedz¹ coœ takiego w stronê robota... "}
{278} {} {Dalej.}
{279} {} {„OK. Czy ty s³yszysz, co mówisz? Twoje centrum serwisowe obs³uguje roboty, które zosta³y zaprogramowane tak, aby nie krzywdziæ ludzi. A ten robot, widzisz, "tylko wykonywa³ swoj¹ pracê". Przestañ wprowadzaæ w b³¹d œledztwo! Przyznaj siê do wady produktu, a dostaniesz ³agodniejsz¹ karê! ”}
{280} {} {Zatrzymaj nagrywanie.}

{290} {} {Protest antyamerykañski.}
{291} {} {"Wiêc przyznajesz siê do winy za udzia³ w nielegalnym wiecu maj¹cym na celu obalenie obecnego rz¹du?"}
{292} {} {Dalej.}
{293} {} {"Winy? O nie! Ci Amerykanie zniewolili ca³¹ Sonorê! To przestêpcy! To nasz skorumpowany rz¹d! Jak mo¿esz nazwaæ prostest nielegalnym? ..."}
{294} {} {Dalej.}
{295} {} {"Ok. Powtórzê moje pytanie trochê póŸniej..."}
{296} {} {Dalej.}
{297} {} {"Meksyk dla Meksykanów! Meksyk dla Meksykanów!"}
{298} {} {Dalej.}
{299} {} {"Stop! Cisza! Milcz!"}
{300} {} {Dalej.}
{301} {} {"Dlaczego mnie tu trzymasz?" - "Chcê prawnika!" - „Jesteœ zadowolony ¿e swojej pensji?” - "Kiedy Madera by³ u w³adzy, Amerykanie do nas nie przyszli..." - "Zapomnia³eœ ju¿ o rzezi na granicy?" - „Meksyk dla Meksykanów!”}
{302} {} {Zatrzymaj nagrywanie.}