{100} {} {Widzisz automat do gry. Naprawdê WARTO wygraæ.}

{110} {} {Automat do gry nie dzia³a.}
{111} {} {Aby rozpocz¹æ grê, proszê w³o¿yæ monety do automatu.}
{112} {} {Zagrawszy prost¹ melodiê w ca³ej sali, automat o¿y³!}

{120} {} {Znowu chcesz poczuæ ten stres? W automacie nie ma ju¿ kuponów na nagrody.}
{121} {} {Mam doœæ hazardu.}
{122} {} {Jesteœ teraz zbyt s³aby, aby uprawiaæ hazard.}
{123} {} {Pierwsz¹ rzecz¹, któr¹ musisz zrobiæ, jest uleczenie.}
{124} {} {Z powodu zniszczenia maszyna ma problemy z odpowiedzi¹. Z twoimi umiejêtnoœciami nie da siê tego obejœæ.}
{125} {} {To bêdzie bardzo trudne.}

{130} {} {Uda³o ci siê pokonaæ maszynê.}
{131} {} {punkty.}
{132} {} {Wszystko, co zarobiono}
{133} {} {wskazuje na 1000 mo¿liwych.}
{134} {} {Tak!}
{135} {} {Tak!}
{136} {} {W ten sposób!}
{137} {} {Ha!}
{138} {} {Zdob¹dŸ!}
{139} {} {Kto tu jest najlepszy?}
{140} {} {Przegrana. Maszyna wystartowala}
{141} {} {punkty z Twojego konta.}
{142} {} {Hej!}
{143} {} {Nie!}
{144} {} {Cholera!}
{145} {} {Cholerna puszka!}
{146} {} {Cholera!}
{147} {} {Hm!}
{148} {} {JAK?!}
{149} {} {Ale mnie to denerwuje.}

{200} {} {Gratulujemy zwyciêstwa! Jesteœ naszym pierwszym zwyciezc¹! WeŸ kupon na nagrodê.}
{201} {} {Wezmê kupon super si³y.}
{202} {} {Wezmê kupon super percepcji.}
{203} {} {Wezmê kupon na super wytrzyma³oœæ.}
{204} {} {Skorzystam z wyj¹tkowo atrakcyjnego kuponu.}
{205} {} {Wezmê kupon super inteligencji.}
{206} {} {Wezmê kupon super zrêcznoœci.}
{207} {} {Dostane kupon na wiele szczêœcia.}
{208} {} {Nie potrzebuje tego.}
