{110} {} {Ta szafa graj¹ca jest zepsuta.}
{111} {} {Szafa graj¹ca zosta³a naprawiona i jest gotowa wydawaæ strasznie g³oœne dŸwiêki zwane muzyk¹.}
{112} {} {Maszyna zosta³a pomyœlnie naprawiona. Och, co za ha³as!}
{113} {} {Szafa graj¹ca nie dzia³a.}

{120} {} {* um-boom *}
{121} {} {* shhhhh *}
{122} {} {* tss-tss-tss *}
{123} {} {* i-boom, shee-boom *}
{124} {} {* a-la-la *}
{125} {} {* room-pum-pum *}
