{100} {} {Widzisz szczeniaka.}
{101} {} {Widzisz m³odego dzikusa z plemienia Szakali.}
{102} {} {* Syczy *}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {* Zgrzyta zêbami *}
{201} {} {* Syczy *}
{202} {} {Hau!}
{203} {} {Nie zbli¿aj siê albo ugryzê.}
{204} {} {* skomle i kuli siê z dala od Ciebie *}
{205} {} {Rrr!}

{210} {} {* Prycha *}
{211} {} {* W¹cha ciê *}
{212} {} {Hau!}
{213} {} {Hau wow!}
{214} {} {Moje zêby s¹ ostrzejsze ni¿ twoje.}

{220} {} {* Szczeka na powitanie *}
{221} {} {* Przeskakuje, aby siê pokazaæ *}
{222} {} {Zagraj ze mn¹ w grê.}
{223} {} {Pobawimy siê?}
