{100} {} {Widzisz Slisk¹ Czaszkê.}
{101} {} {Widzisz jednego z dzikusów plemienia Szakali.}
{102} {} {Trzymaj siê ode mnie z dala.}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Trzymaj siê ode mnie z daleka, nieznajomy.}
{201} {} {Ok.}
{202} {} {Opowiedz mi o Czarnym Kle.}
{203} {} {Najlepszy wojownik ze wszystkich. Bój siê go, nieznajomy. Oka¿ mu szacunek. Dziêki swoim pu³apkom przynosi wiêcej jedzenia ni¿ ktokolwiek inny. Warto mu wybaczyæ jego z³y humor.}
{204} {} {Opowiedz mi o Szalonej Suce.}
{205} {} {Nie mów Ÿle o Suce. Jest nasz¹ przywódczyni¹, ka¿dy powinien j¹ szanowaæ i dzieliæ siê z ni¹ jedzeniem. Ale w czasach g³odu nawet takiemu przywódcy trudno jest podarowaæ choæby kawa³ek starego ubrania.}
{206} {} {Które z nich jest bardziej godne bycia przywódc¹ plemienia?}
{207} {} {Kie³ chce poprowadziæ plemiê w góry, z dala od tych ja³owych ziem. Szalona Suka chce sojuszu z obcymi. Co lepsze? Niech zdecyduje stado. Bêdê pod¹¿aæ za wszystkimi.}
{208} {} {Do widzenia.}
