{100} {} {Widzisz samice Szakali.}
{101} {} {Widzisz dzikusa z plemienia Szakali. Mia³a „szczêœcie”, ¿e prze¿y³a nalot Rangersów.}
{102} {} {Co mam teraz zrobiæ?}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Czekaj! Miej litoœæ! Nie zabijaj!}
{201} {} {Niech tak bêdzie. Zyj, do widzenia.}
{202} {} {Opowiedz mi, co siê tutaj wydarzy³o.}
{203} {} {To wszystko przez Rangersów! Zaatakowali swoimi ognistymi patykami i zabili wszystkich samców... a potem wszystkie samice... i wszystkie szczeniêta...}
{204} {} {Jak prze¿y³aœ?}
{205} {} {Na pustkowiach ³apa³am iguany dla moich szczeni¹t. Kiedy przybyli nieznajomi, sta³am w cieniu... Przeklêci Stra¿nicy!}
{206} {} {I zostawi³aœ swoje szczeniêta samym sobie?}
{207} {} {Ja... (pada na kolana) Nie mog³am... Zaw³adnê³y mn¹ przera¿enie i g³ód...}
{208} {} {To teraz z tym ¿yj. Ja wychodzê.}