{100} {} {Widzisz sukê.}
{101} {} {Widzisz jedn¹ z suk plemienia Szakali.}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {(obna¿a zêby) Cœœ! Nie zbli¿aj siê do mnie, nieznajomy!}
{201} {} {Do widzenia.}
{202} {} {Chcê tylko porozmawiaæ z tob¹ o plemieniu.}
{203} {} {Puste szczekanie tylko dra¿ni mój ¿o³¹dek. Przynieœ jedzenie albo daj mi spokój.}
{204} {} {Ok.}
{205} {} {Jedzenie by³o pyszne. Co chcesz wiedzieæ?}
{206} {} {Doœæ gadania. Do widzenia.}
{207} {} {Sk¹d siê wszyscy wzieliœcie?}
{208} {} {Pamiêtam czasy, kiedy by³am szczeniakiem. Wrogie plemiona wypêdzi³y nas z naszych dawnych ziem. Dlatego d³ugo b³¹dziliœmy po pustyni w poszukiwaniu odpowiedniego miejsca. Ale tylko to zosta³o znalezione. Tutaj przeczekaliœmy sezon burz piaskowych. To by³ bardzo g³odny czas. Prze¿yli tylko najbardziej wytrwali. Od tego czasu w tych norach wychowywa³y siê dwa pokolenia szczeni¹t.}
{209} {} {Co jecie?}
{210} {} {Cokolwiek. Wszystko, co znajdziemy lub z³apiemy na pustkowiu.}
{211} {} {Czy mo¿na jeœæ ludzkie miêso?}
{212} {} {A co jeszcze mo¿na jeœæ, jeœli nie ma nic innego? Na pustyni nie roœnie nawet trawa. Nawet woda w rzece puchnie i rani ¿o³¹dki... Hmm. Masz jedzenie.}
{213} {} {Czy oprócz mnie s¹ tu jeszcze inni ludzie z zewn¹trz?}
{214} {} {Tak... nasz lunch. Krzepki nieznajomy. Bardzo dobre miêso. (szczerzy siê) Nie mo¿esz jednak siê do niego dostaæ, Nocna Bestia dobrze chroni magazyny. Tylko Szalona Suka mo¿e z nim rozmawiaæ.}
{215} {} {Co myœlisz o Szalonej Suce?}
{216} {} {(z nut¹ strachu i podziwu) To ona tu rz¹dzi, mówi w imieniu nas wszystkich. Nie pytaj mnie wiêcej o Sukê!}
{217} {} {Co s¹dzisz o Czarnym Kle?}
{218} {} {Kie³... (warczy z dezaprobat¹) Bezczelny pies. Bije kobiety, zabiera jedzenie. Pokonaj K³a, jeœli chcesz zaj¹æ jego miejsce.}
{219} {} {Co to za sprzêt z czaszk¹ w g³ównej sali?}
{220} {} {To tylko znak z przesz³oœci. Zapytaj o niego Wœciek³¹ Sukê.}
{221} {} {Powiedz mi wiêcej.}
{222} {} {Nie. Nasz ostatni obiad nam uciek³. Zostawi³ nas g³odnych... (pluje ze z³oœci¹)}


