{100} {} {Widzisz Nocn¹ Bestiê.}
{101} {} {Widzisz Szakala stoj¹cego na stra¿y. Lojalnie strze¿e magazynów swojego plemienia.}
{102} {} {C-co za ¿art?!}

# Repliki plywajace
{120} {} {Nikt nie odwa¿y siê zaj¹æ mojego miejsca.}
{121} {} {Tylko ja mogê strzec tych dziur, tylko ja!}
{122} {} {Zabijê ka¿dego, kto spróbuje w³amaæ siê do magazynów!}
{123} {} {Plemiê mnie potrzebuje.}
{124} {} {Szalona Suka chce, ¿ebym pilnowa³ magazynów. Wiêc pilnujê.}
{125} {} {Mówi¹, ¿e w dziurach jest obcy.}
{126} {} {Rrr! Czujê i-inwigilacje!}
{127} {} {* W¹cha *}
{128} {} {Czujê nieznajomego.}
{129} {} {W tych norach brakuje rozdzieraj¹cych serca jêków nieznajomych.}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Wynoœ siê st¹d! W tych magazynach nie ma miejsca dla obcego!}
{201} {} {Ok.}
