{100} {} {Widzisz dzikusa.}
{101} {} {Widzisz jednego z samców Szakali. Spojrzeniem bli¿ej mu do wilka ni¿ cz³owieka.}
{102} {} {}

# Repliki plywajace
{120} {} {Kiedy mój ¿o³¹dek jest pusty, wyje do ksiê¿yca.}
{121} {} {Piêkny dzieñ na ofiarê.}
{122} {} {Twoja skóra jest zupe³nie ³ysa.}
{123} {} {Cœœ, przestañ szczekaæ! Bo jeszcze nieznajomy us³yszy...}
{124} {} {Paso¿yty na moim ciele nie pozwalaj¹ mi zasn¹æ.}
{125} {} {Ta suka bêdzie moja!}
{126} {} {* W¹cha *}
{127} {} {* Drapie siê za uchem *}
{128} {} {Pu³apki wymagaj¹ przynêty.}
{129} {} {Czas naostrzyæ k³y.}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {* Zgrzyta zêbami *}
{201} {} {Kiedy umrzesz, bêdê pierwszym, który oderwie ci miêso od koœci.}
{202} {} {Moje k³y chc¹ twojej krwi.}
{203} {} {Twój mózg bêdzie mój, kiedy umrzesz.}
{204} {} {}

{205} {} {Zabicie ciê przyniesie mi s³awê i szacunek.}
{206} {} {Chcesz umrzeæ, nieznajomy?}
{207} {} {Um, co za soczysty obcy.}
{208} {} {}
{209} {} {}

{210} {} {Moje pieprzone ¿ycie jest teraz twoje, nieznajomy.}
{211} {} {* Za³osny jêk *}
{212} {} {}
{213} {} {}
{214} {} {}
