{100} {} {Widzisz najeŸdŸcê.}
{101} {} {Widzisz swojego towarzysza z nory.}
{102} {} {To by³a wielka bitwa, prawda?}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Czas na atak. Nadal jesteœ z nami?}
{201} {} {Masz jakieœ rady dotycz¹ce skutecznej walki?}
{202} {} {Szakale s¹ doœæ s³abe, wiêc nie bêdziemy potrzebowaæ ¿adnej powa¿nej broni. Ale s¹ liczni i gromadz¹ siê w ciasnych korytarzach. Fajnie by³oby wrzuciæ tam granat lub potraktowaæ ich seri¹.}
{203} {} {Oczywiœcie. ChodŸmy.}
{204} {} {ChodŸmy.}
{205} {} {Coœ wiêcej?}
{206} {} {Uwa¿aj na ich zatrute ostrza i pazury. I musisz coœ zrobiæ z t¹ nieprzeniknion¹ ciemnoœci¹. Z pewnoœci¹ w otworach s¹ pochodnie, nale¿y je znaleŸæ i podpaliæ.}
{207} {} {To nie jest dobry moment na rozmowê.}
{208} {} {Nie spodziewa³em siê tu zobaczyæ Stra¿nika. Do tego zwi¹zanego. Nie wydajesz siê byæ tak mocny, jak wszyscy myœl¹.}
{209} {} {Myœlisz, ¿e byli ostatnimi?}
{210} {} {Na to wygl¹da. Nareszcie te przeklête nory zosta³y oczyszczone z paso¿ytów. Pozostaje zebraæ kosztownoœci i wróciæ do domu.}
{211} {} {Ok.}
{212} {} {[Dalej.]}