{100} {} {Widzisz delegata.}
{101} {} {Widzisz negocjatora Stra¿ników.}
{102} {} {Ambasador zosta³ zabity... przez Szakale. Nie mam z tym nic wspólnego.}
{103} {} {Jaki kretyn dokona³ tej rzezi? Ca³a moja praca na nic!}
{104} {} {Coœ siê sta³o. Teraz Szakale mnie wypêdzaj¹.}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Oto nasz bohater. Pozostaje mi pozazdroœciæ twoich umiejêtnoœci dyplomacji. Tylko nielicznym uda³o siê dotrzeæ do umys³u tak dzikiego plemienia. Dobra robota! Tak trzymaj.}
{1200} {} {Oto nasza bohaterka. Pozostaje mi pozazdroœciæ twoich umiejêtnoœci dyplomacji. Tylko nielicznym uda³o siê dotrzeæ do umys³u tak dzikiego plemienia. Dobra robota! Tak trzymaj.}
{201} {} {Próbuje. Jak id¹ negocjacje?}
{202} {} {Tak, tak?}
{203} {} {Spróbujmy innego tematu.}
{204} {} {Do widzenia ambasadorze.}

{210} {} {Jak id¹ negocjacje?}
{211} {} {Ciê¿ko, ale postêp jest zauwa¿alny. Pierwsz¹ rzecz¹ do zrobienia jest uspokojenie Szakali niewielkim prezentem w postaci po¿ywienia. A potem nauczymy je prowadziæ cywilizowany styl ¿ycia.}
{212} {} {A jak s¹dzisz? Ktoœ pokrzy¿owa³ wszystkie plany, szkodz¹c Szakalom. Mo¿emy mieæ tylko nadziejê, ¿e te dzikusy nie rozprosz¹ siê teraz po Sonorze i Mojave w poszukiwaniu nowych ofiar.}
{213} {} {Czy Szakale w ogóle mog¹ na coœ siê przydaæ?}
{214} {} {Stra¿nicy mog¹ nauczyæ siê od nich taktyki i przetrwania. Mog¹ równie¿ s³u¿yæ do monitorowania terenu. To ju¿ jest du¿o warte. Martwiê siê jednak o ich g³upie fundamenty - kanibalizm, wiarê w Ducha Schronienia, podziemny styl ¿ycia i inne bzdury. Pozbycie siê tego zajmie du¿o czasu.}
{215} {} {Co s¹dzisz o sojuszu z Szakalami?}
{216} {} {Trudne pytanie. Wielu jest niezadowolonych z ustêpstw i uwa¿a, ¿e Szakale powinny zostaæ po prostu zlikwidowane. Z tego powodu reputacja Stra¿ników zosta³a lekko nadszarpniêta. Ale po rozmowie z plemieniem zda³em sobie sprawê, ¿e to nie jest opcja. Ich „stado” jest rozproszone po ca³ej pustyni Mojave i dalej na zachód. Eliminuj¹c tê kryjówkê, tylko zdenerwujemy resztê klanów. To jak wrzucenie kamienia do rzeki, aby zmieniæ jej bieg.}
{217} {} {Dlaczego * naprawdê * Stra¿nicy zgodzili siê na sojusz?}
{218} {} {Oczywiœcie oprócz twojej dyplomacji s¹ inne motywy. Szakale terroryzuj¹ te tereny od wielu lat. Ale nie ma innych tras na pó³noc. Stra¿nicy s¹ szczególnie zainteresowani ziemiami pó³nocnymi, to d³uga historia. Ponadto plemiê mo¿e staæ siê œrodkiem nacisku na okoliczne osady.}
{219} {} {Jeszcze nie mog³em spotkaæ siê z *wodzem*. Myœlê, ¿e te negocjacje nie zakoñcz¹ siê bez Twojej pomocy.}