{100} {} {Widzisz Rangersa.}
{101} {} {Widzisz wiêŸnia. Szakale da³y temu biedakowi nieŸle popaliæ.}
{102} {} {Swietnie. W ten sposób bêdê móg³ po¿yæ trochê d³u¿ej.}
{103} {} {Czy to wszystko, czego siê nauczy³eœ, zwiadowco?}
{104} {} {Stra¿nikowi uda³o siê opuœciæ Dolinê Szakali.}

# Dialog PRZED ucieczka
{200} {} {Zostaw mnie, brudny dzikusie... Cholera, nie jesteœ dzikusem, prawda? Czy ciebie te¿ z³apa³y te cholerne Szakale?}
{201} {} {W pewnym sensie.}
{202} {} {Nie, idioto, opalam siê tutaj.}
{203} {} {Ugh, myœla³em, ¿e nigdy ju¿ nie zobaczê normalnej osoby...}
{204} {} {Wiêc masz szczêœcie, kolego.}
{205} {} {Serio jest tu tak Ÿle?}

{210} {} {S³uchaj, muszê siê st¹d wydostaæ. Pomó¿ mi! Moi przyjaciele Stra¿nicy nie zapomn¹ tej pomocy.}
{211} {} {Jest za wczeœnie na wyjazd. Zaczekaj tutaj.}

{220} {} {Mo¿esz chodziæ?}
{221} {} {Ledwo. Szakale porani³y mi nogi, ¿ebym nie uciek³. Czy mo¿esz uleczyæ te rany? Jeœli nie, znajdŸ mój stymulant. Któryœ z dzikusów musia³ go wzi¹æ.}
{222} {} {Co to jest „stymulant”?}
{223} {} {Naprawdê nie wiesz? Cholera, nie ¿yje! Spójrz, to taka staro¿ytna rzecz z ig³¹ i czerwonym p³ynem. ZnajdŸ to szybko!}
{224} {} {Ok, spróbujê go znaleŸæ.}
{225} {} {Mo¿e znajdê inny sposób, byœ stan¹³ na nogi.}
{226} {} {Myœlê, ¿e tak. Przynajmniej mogê siê wydostaæ.}
{227} {} {Swietnie. ChodŸmy st¹d.}
{228} {} {Jest za wczeœnie na wyjazd. Zaczekaj tutaj.}

{230} {} {Mo¿esz walczyæ?}
{231} {} {Tylko jeœli dasz mi broñ. Szakale zabra³y ca³y mój dobytek, ³¹cznie z karabinem. Mo¿e byæ wszêdzie.}
{232} {} {Rozumiem. Zanotujê to sobie.}
{233} {} {Powiedz mi, jak siê tu dosta³eœ.}
{234} {} {Mój zespó³ bada³ te okolice. Ale te przebieg³e sukinsyny zastawi³y na nas w pu³apkê. Tylko ja prze¿y³em.}
{235} {} {Rozumiem.}
{236} {} {Szakale nie odwa¿y³y siê walczyæ?}
{237} {} {To nie jest w ich stylu. Osobno s¹ tchórzliwi, atakuj¹ tylko ca³¹ gromad¹... Uhh, moje nogi p³on¹... Przeklête dzikusy!}
{238} {} {Czego szuka³eœ w takiej dziczy?}
{239} {} {Dostaliœmy rozkaz. A rozkazy s¹ tajne. To jest sprawa Stra¿ników.}
{240} {} {Ok, wierzê na s³owo.}
{241} {} {Te ziemie s¹ zbyt opuszczone i dzikie, by Stra¿nicy byli nimi zainteresowani.}
{242} {} {Masz oko na k³amstwa... Dowódcy myœleli, ¿e Szakale bêd¹ dobrym powodem do zawarcia umowy z s¹siednim miastem.}
{243} {} {Jakiej umowy?}
{244} {} {Czy jako Rangersi zawsze coœ przegapiacie?}
{245} {} {Lokalne osady cierpi¹ z powodu Szakali. Gdybyœmy siê ich pozbyli, podnieœli byœmy nasz¹ reputacjê w s¹siednich osadach. Co wiêcej, moglibyœmy narzuciæ im lukratywny kontrakt. Ale najpierw musimy zebraæ strategiczne informacje o wrogu i terenie... Ale co powiesz na to, ¿e przestaniesz gadaæ i wydostaniesz nas st¹d najszybciej jak siê da?}
{246} {} {Nie, dopóki nie uzyskam wiêcej informacji.}
{247} {} {Dobry pomys³.}
{248} {} {Co wiesz o tych norach?}
{249} {} {Prawie nic nie widzia³em. Ale uwa¿aj na powierzchni - wokó³ chaty jest mnóstwo pu³apek.}
{250} {} {Rozumiem.}

# Dialog podczas i po ucieczce
{260} {} {Zajmê siê ty³em. Najwa¿niejsze, ¿eby nie zwracaæ na siebie uwagi.}
{261} {} {ChodŸmy.}
{262} {} {Musimy siê st¹d szybko wydostaæ. Porozmawiamy na powierzchni.}
{263} {} {Uwa¿aj. Ten budynek jest pe³en pu³apek. Musimy pójœæ trochê dalej.}
{264} {} {Nie widaæ poœcigu. Wygl¹da na to, ¿e odpuœcili!}
{265} {} {ChodŸmy.}
{266} {} {Nie martw siê o mnie, znajdê swoj¹ drogê}
{267} {} {Bon voyage.}

{270} {} {Nie widaæ poœcigu. Wygl¹da na to, ¿e odpuœcili!}
{271} {} {Spokojnie, jesteœmy bezpieczni.}
{272} {} {To nie potrwa d³ugo. Poza tym bêdê musia³ utykaæ na obola³ych nogach do najbli¿szej placówki i wezwaæ pomoc. Ale dam sobie radê.}
{273} {} {Czy na pewno nie potrzebujesz pomocy?}
{274} {} {Dobrze. Znam tu kilka miejsc, w których mo¿na odpocz¹æ i nabraæ si³.}
{275} {} {Có¿, wiesz lepiej.}
{276} {} {Radzê iœæ wzd³u¿ rzeki krótkimi trasami. Pozwoli to zaoszczêdziæ energiê.}
{277} {} {Tak, to dobry pomys³, chocia¿ droga bêdzie trochê d³u¿sza.}
{278} {} {[Dalej.]}
{279} {} {W takim razie powodzenia, Stra¿niku.}
{280} {} {Dziêki za pomoc, podzielê siê twoim wyczynem z moimi towarzyszami w bazie. Jeœli kiedykolwiek siê tam znajdziesz, zapytaj o Jasona, to ja. Teraz muszê iœæ.}
{281} {} {Do zobaczenia, Stra¿niku.}

{290} {} {Zostañ tutaj. Idê na zwiad.}
{291} {} {ChodŸ za mn¹.}
{292} {} {Od³ó¿ broñ, jesteœ z ni¹ zbyt ha³aœliwy.}
{293} {} {Zdejmij tê zbrojê. Zdradza ciê w ciemnoœci.}
