{100} {} {Widzisz Czarnegp K³a.}
{101} {} {Widzisz silnego wojownika z plemienia Szakali.}
{102} {} {}
{103} {} {Nie powinieneœ by³ mnie wkurzaæ, maniaku.}
{104} {} {C-co to za ¿art?!}
{105} {} {Zabijê ciê!}

# Plywajace repliki
{120} {} {Wszyscy powinni siê mnie baæ!}
{121} {} {Nie wybaczê, nie wybaczê, nie wybaczê!}
{122} {} {Szalona Suka bêdzie czo³ga³a siê u moich stóp.}
{123} {} {Pewnego dnia zostanê przywódc¹ plemienia.}
{124} {} {Nikt nie odwa¿y siê zaj¹æ mojego miejsca!}
{125} {} {Pewnego dnia rzucê Szalon¹ Sukê na kolana.}
{126} {} {}
{127} {} {}
{128} {} {}
{129} {} {}

# Dialog na pierwszym spotkaniu
{200} {} {Jesteœ w pu³apce! Nawet nie próbuj siê opieraæ. Jesteœ teraz moj¹ zdobycz¹. Sha-a-a!}
{201} {} {Nie zamierzam nikogo skrzywdziæ.}
{202} {} {Wytrzyj brudne oczy, psie. Za du¿o myœlisz o sobie.}
{203} {} {Umrzesz w agonii za swoje s³owa!}
{204} {} {Ok, muszê ciê uspokoiæ...}
{205} {} {Tak... Tak lepiej. A teraz œmia³o. Chcê ciê pokazaæ Szalonej Suce. Jesteœ moj¹ zdobycz¹. Ka¿dy powinien to wiedzieæ!}
{206} {} {Ok, prowadŸ.}
{207} {} {Szalona Suka oszala³a, wpuszczaj¹c nieznajomego do naszych nor. Daj mi tylko powód, a wyrwê ci serce moimi pazurami!}
{208} {} {Raczej do tego nie dojdzie.}
{209} {} {Ty! Ju¿ mi nie uciekniesz, kawa³ku miêsa!}
{210} {} {Zobaczymy...}
{211} {} {Czego chcesz?}
{212} {} {Nic. Bywaj.}
{213} {} {Czekaj, nie chcê nikogo skrzywdziæ!}
{214} {} {Jesteœ uwiêziony, obcy... Arrr! Cz³owiek o ¿elaznej skórze! Kim jesteœ? Czego potrzebujesz?}
{215} {} {Potrzebujê twojej œmierci. Zdejmij ubranie i oddaj w³óczniê.}
{216} {} {Wszyscy do mnie! W naszych norach jest z³y duch ¿elaza!}
{217} {} {Nie powinieneœ by³ tego robiæ...}
{218} {} {Kto tu rz¹dzi?}
{219} {} {Chcesz porozmawiaæ z wodzem? Jest nim Szalona Suka. Jeden z³y ruch i cie przebije.}

#Naszyjnik
{220} {} {Ten naszyjnik z amunicj¹ ci nie odpowiada.}
{221} {} {C-o czym ty mówisz? Nie zalewaj moich uszu swoj¹ nikczemn¹ mow¹. Zdoby³em to trofeum z cia³ stra¿ników. Mówi wszystkim o moich zas³ugach dla stada.}
{222} {} {Mówi te¿, ¿e jesteœ g³upi, chwal¹c siê amunicj¹ wroga.}
{223} {} {Gr-rm! (ze z³oœci¹ zrywa naszyjnik i rzuca ci go pod nogi) Nie potrzebujê rzeczy moich wrogów!}
{224} {} {Dok³adnie.}
{225} {} {Mo¿e powinniœmy o to zagraæ?}
{226} {} {W takim razie zapomnij.}
{227} {} {UgryŸ siê w jêzyk, szczeniaku, albo wyrwê ci go z ust!}
{228} {} {Grajmy wed³ug moich zasad. Jeœli przegrasz, wezmê miskê twojej krwi. Wygraj - a trofeum bêdzie Twoje.}
{229} {} {Zagrajmy.}
{230} {} {Ta stawka mi nie odpowiada. Odpadam.}
{231} {} {Gr-rm! (ze z³oœci¹ zrywa naszyjnik i rzuca nim pod twoje nogi) Wygra³eœ, nieznajomy!}
{1231} {} {Gr-rm! (ze z³oœci¹ zrywa naszyjnik i rzuca nim pod twoje nogi) Wygra³aœ, suko!}
{232} {} {Chyba zostawiê ciê samego, dopóki siê nie uspokoisz...}
{233} {} {H-ha! Czarny Kie³ znów zwyciê¿a! Jestem zwyciêzc¹!}
{234} {} {Hej, czekaj, co robisz...}
{235} {} {Gry nie s¹ dla wojowników. I dla szczeni¹t takich jak Ty.}
{236} {} {Nie bêdê siê k³óciæ.}
{237} {} {Nie wa¿ne. Po prostu zabijê was wszystkich jednego po drugim. Zacznê od ciebie, kretynie.}

# Uslugi pielegnacyjne
{240} {} {Nie wygl¹dasz najlepiej. Czy ochrona przy wejœciu jest a¿ tak wyczerpuj¹ca?}
{241} {} {Chroniê stado przed obcymi i zdobywam jedzenie! Inni patrz¹ na mnie i siê ucz¹. Ta walka jest wyczerpuj¹ca, ale muszê. Bêdê musia³ stan¹æ na czele stada, kiedy Szalona Suka opuœci swoje stanowisko.}
{242} {} {Jesteœ zbyt spiêty. Pomogê Ci siê zrelaksowaæ.}
{243} {} {Ach, wiêc rozumiem.}
{244} {} {Zeby nieznajomy krêci³ siê wokó³ mnie? Okej, wzniosê siê jeszcze wy¿ej w oczach stada.}
{1244} {} {Zeby nieznajoma krêci³a siê wokó³ mnie? Okej, wzniosê siê jeszcze wy¿ej w oczach stada.}
{245} {} {Oczywiœcie, ¿e jesteœ liderem, usi¹dŸ, bêdê ci masowaæ plecy...}
{246} {} {Nie chce czegoœ.}
{247} {} {Nie ufam obcym. Jesteœ obcy.}
{248} {} {Wzajemnie.}
{249} {} {Masowanie podnios³o twoj¹ reputacjê w oczach Szakali. Ale nie rób tego wœród innych plemion.}

#Pytania
{250} {} {Kim jesteœ?}
{251} {} {Jestem wojownikiem. Stado nazywa mnie Czarnym K³em.}
{252} {} {Co myœlisz o Szalonej Suce?}
{253} {} {Suka jest bezczelna. Czasami jestem gotów rzuciæ siê na ni¹ i udusiæ pazurami. Ale jest oddana stadu, a ono jej. Chocia¿ prowadzi je w niew³aœciwe miejsce.}
{254} {} {}
{255} {} {}
{256} {} {Rozumiem.}