{103} {} {Jedna suka mniej.}
{104} {} {G³upcze, ta trucizna nie dzia³a na Szakale!}

# Dialog licznika
{200} {} {Z³apaæ nieznajomego! Rozerwaæ na strzêpy! Przynieœcie mi jego g³owê!}
{1200} {} {Z³apaæ nieznajom¹! Rozerwaæ na strzêpy! Przynieœcie mi jej g³owê!}
{201} {} {Z³apaæ nieznajomego! Wyrwac mu serce! Przynieœæ mi jego g³owê!}
{1201} {} {Z³apaæ nieznajoma! Wyrwac jej serce! Przynieœæ mi jej g³owê!}
{202} {} {Nie denerwuj siê...}
{203} {} {Do ty³u, zwierzêta, cofn¹æ siê!}

{210} {} {Z-zobaczcie, kto tu jest. Nieznajomy z obcego plemienia. Jakie to szczeœciê, ¿e nie musimy go œcigaæ przez pustkowia.}
{1210} {} {Z-zobaczcie, kto tu jest. Suka z obcego plemienia. Co za szczêœcie, ¿e nie musimy jej œcigaæ przez pustkowia.}
{211} {} {Do czego mnie potrzebujesz?}
{1211} {} {Do czego mnie potrzebujesz?}
{212} {} {Tak, naprawdê nie mam ochoty biegaæ po pustyni.}
{213} {} {Nie zamierzam tolerowaæ tych drwin. Wychodzê.}
{214} {} {(œmieje siê) Obcy nie rozumie. Nieznajomy wci¹¿ ma nadziejê, ¿e wyjdzie st¹d ¿ywy. Lubiê to.}
{1214} {} {(œmieje siê) S-suka nie rozumie. Ta suka wci¹¿ ma iskierkê nadziei, ¿e wyjdzie st¹d ¿ywa. Lubiê to.}
{215} {} {Wiêc zamierzasz mnie zabiæ?}
{216} {} {Uch, nie zamierzasz mnie zjeœæ, prawda?}
{217} {} {(gwa³townie zmienia wyraz twarzy) Jesteœmy g³odni! Zabijamy, by prze¿yæ. Umieramy z g³odu, dlatego obcy stanie siê naszym po¿ywieniem. Bedziemy karmiæ nasze dzieci jego cia³em! (przez otwory s³ychaæ aprobuj¹ce wycie kilkunastu ust)}
{218} {} {W³aœciwie to mam inne plany...}
{219} {} {Nie mówisz powa¿nie, prawda?}

{220} {} {Podaj swoje imiê, obcy, a zaczniemy.}
{1220} {} {Podaj swoje imiê, nieznajoma, a zaczniemy.}
{221} {} {Nazywam siê Poca³uj-Mnie-W-Dupê!}
{222} {} {Czy musisz to wiedzieæ?}
{223} {} {(prycha jak pies) Twój jêzyk jest tak podstêpny, ¿e dam go szczurom do jedzenia.}
{224} {} {To niezbyt mi³e z twojej strony.}
{225} {} {Nie dojdzie do tego.}
{226} {} {Niech tak bêdzie. Nory s¹ dla ciebie otwarte. Ale nie idŸ do magazynów. Nocna Bestia strze¿e ich zbyt gorliwie.}
{227} {} {Ok, bêdê o tym pamiêtaæ. A teraz siê tu trochê rozejrzê, jeœli nie masz nic przeciwko.}
{228} {} {Co to jest? Cz³owiek w ¿elaznej skorupie? Co za niespodzianka. Wielu tym przestraszy³eœ, cz³owieku z pancerza. Ale mnie nie oszukasz. Daj sobie spokój, i tak wyci¹gniemy ciê z tej brzydkiej rzeczy.}

{230} {} {Jestem pos³añcem Ducha Schronienia. Mój kombinezon jest tego dowodem.}
{1230} {} {Jestem pos³añcem Ducha Schronienia. Mój kombinezon jest tego dowodem.}
{231} {} {Swiêty Szakal, teraz pamiêtam! Nasi przodkowie nosili takie same niebieskie szaty jak ty. Wiêc wszyscy wyszliœmy z tej samej nory, jesteœmy cz³onkami tego samego plemienia?}
{232} {} {Dok³adniej, Krypty.}
{233} {} {Wiêc powiedz mi, dlaczego Duch Krypty nas opuœci³? Dlaczego zostaliœmy ukarani zaraz¹ i g³odem? Wo³aliœmy Go w nocy, z³o¿yliœmy Mu wiele ofiar. Czy w koñcu us³ysza³ nasze szczekanie, wyjaœnij, co powinniœmy zrobiæ?}
{234} {} {Daj mi czas na poznanie stada i przeanalizowanie waszego ¿ycia. Byæ mo¿e mogê ci pomóc.}
{235} {} {Nie bez powodu nazywaj¹ mnie ghulem. Skosztowawszy mojego martwego cia³a, sami umrzecie.}
{236} {} {Zywy trup! Duchy ponownie karz¹ nas zaraz¹. (przez dziury rozchodzi siê p³aczliwe wycie) Ale mo¿e TY mo¿esz nas nauczyæ, jak przetrwaæ na tym œwiecie? Jeœli udaje ci siê utrzymaæ oddech w martwym ciele, to mo¿e moglibyœmy siê czegoœ nauczyæ od ciebie, zanim udamy siê do Wielkiej Psiarni.}
{237} {} {Daj mi czas na poznanie stada i przeanalizowanie waszego ¿ycia. Byæ mo¿e mogê ci pomóc.}
{238} {} {Chcê ci pomóc.}
{239} {} {Jestem ambasadorem ze œwiata zewnêtrznego. S¹siednie miasta s¹ zmêczone waœniami i chc¹ rozwi¹zaæ wasz problem g³odu.}
{240} {} {Nasi wrogowie dadz¹ nam jedzenie w zamian za pokój? To mo¿e byæ pu³apka. A mo¿e to zwi¹zek, który uchroni nas od problemów.}
{241} {} {Jeœli mnie zabijesz, nadal niewiele zyskasz. Wiêc co powiesz?}
{242} {} {Zabicie mnie zez³oœci Swiêtego Szakala.}
{243} {} {Przysy³a mnie Duch Swiêtego Szakala. Wys³a³ mnie, bym rozwi¹za³ problem g³odu.}
{244} {} {Modliliœmy siê do Ducha i sk³adaliœmy Mu ofiary. Ale On nigdy nam nie pomóg³. Z pokolenia na pokolenie, wyleg po wylegu - tylko stawaliœmy siê mniejsi i powoli wymieraliœmy. Teraz zlitowa³ siê nad swoimi s³ugami? W takim razie powiedz nam, co powinniœmy zrobiæ?}
{245} {} {Najpierw muszê poznaæ stado.}
{246} {} {Nie, g³upcze, nikt ci nie pomoze. Ka¿dy chce tylko Waszej œmierci!}

# Powtarzajacy siê dialog
{250} {} {Nory s¹ dla ciebie otwarte.}
{251} {} {Nory s¹ dla ciebie otwarte. Ale nie próbuj nas oszukiwaæ.}
{252} {} {Chyba ju¿ pójdê.}
{253} {} {Stra¿nicy karmili nas zgodnie z obietnic¹. Chocia¿ nie lubimy pokarmów roœlinnych, g³ód nie zagra¿a ju¿ naszym ¿o³¹dkom. Ca³e stado jest ci wdziêczne, pos³añcze Swiêtego Szakala.}

{260} {} {Porozmawiajmy o g³odzie.}
{261} {} {Wokó³ pustynia, ma³o jedzenia i wody. G³ód zmusza nas do atakowania obcych.}
{262} {} {Daj mi czas, spróbujê znaleŸæ rozwi¹zanie tego problemu.}
{263} {} {I jeœæ ich miêso, aby zaspokoiæ wlasne? Dlatego ka¿dy, kto o was s³ysza³, unika was.}
{264} {} {Obcy zawsze nas przeganiali. Dlaczego ktoœ mia³by dzieliæ siê z nami jedzeniem? Oczywiscie ¿e musimy to robic wbrew ich woli.}
{265} {} {Innymi s³owy, bierz lub kradnij. Nie macie nic do wymiany?}
{266} {} {Wymieniaæ coœ na jedzenie? Nie mamy nic do zaoferowania.}
{267} {} {Nie bêdzie ³atwo znaleŸæ wam sojuszników. Ale spróbujê.}
{268} {} {Czekam, nieznajomy. Da³eœ s³owo, ¿e znajdziesz dla nas po¿ywienie.}
{1268} {} {Czekam, nieznajoma. Da³aœ s³owo, ¿e znajdziesz dla nas po¿ywienie.}
{269} {} {Pracujê nad tym.}
{270} {} {Stra¿nicy s¹ gotowi zawrzeæ z wami sojusz.}
{271} {} {(syczy) Cœœ! Stra¿nicy s¹ wrogami! Zawsze pierwsi nas atakowali. Chcesz ich przyprowadziæ do doliny?}
{272} {} {Oni te¿ s¹ zmêczeni ju¿ t¹ wojn¹. Na razie tylko ich wys³uchaj. Wyœl¹ delegata do negocjacji.}
{273} {} {Rozmowa... Nie zaspokoja g³odu. Ale te¿ nie pogarsza. Powiedz tym... nieznajomym, ¿e bêdê s³uchaæ.}
{274} {} {Na znak pojednania uwolnij Stra¿nika, którego tu trzymasz. W przeciwnym razie stracisz jedyn¹ szansê na znalezienie sojusznika.}
{275} {} {Udzielê im twojej zgody.}
{276} {} {Takie soczyste miêso... Mogê nim nakarmiæ ca³e stado... Jeœli to oszustwo, zap³acisz wysok¹ cenê.}
{277} {} {Teraz zniknij. Nie zamierzam czekaæ do koñca moich dni.}
{278} {} {Ok.}

{300} {} {Opowiedz mi o swoim plemieniu.}
{301} {} {Wszyscy jesteœmy tej samej krwi. Zyjemy w tych norach ju¿ od trzeciego pokolenia. Wczeœniej stado by³o wiêksze, ale g³ód zmniejsza³ liczbê, a miot rodzi³ siê coraz bardziej chory i niezdolny do ¿ycia. Co jeszcze chcesz wiedzie?}
{302} {} {Nie rozmawiajmy ju¿ o tym.}
{303} {} {Wiêc nie zawsze mieszkaliœcie w tej dolinie?}
{304} {} {Nasi przodkowie du¿o wêdrowali. Przybyli z miejsca, które nazwali Krypta 15. Nie wiem, co to znaczy. Ale wtedy wszystko wygl¹da³o inaczej ni¿ teraz.}
{305} {} {Rozumiem.}
{306} {} {Ta struktura w kszta³cie ko³a zêbatego przypomina o tamtych czasach, prawda?}
{307} {} {Tak... dobrze.}
{308} {} {Nie wiesz, co to oznacza, prawda?}
{309} {} {Duchy nie rozmawiaj¹ ze mn¹ o tym. A przodkowie nic nie powiedzieli. A wraz z nadejœciem okresów g³odu opowieœæ straci³a wszelki sens.}
{310} {} {Nic zaskakuj¹cego. Czy mogê prosiæ o wiêcej?}
{311} {} {To jest zdjêcie pancernych drzwi. Twoi przodkowie wy³onili siê z Krypty Vault-Tec.}
{312} {} {(w zamyœleniu) Vault-Tec... Naprawdê du¿o wiesz. W takim razie powiedz nam, jak walczyæ g³odem! Za du¿o Szakali i za ma³o jedzenia. To naprawdê wa¿ne.}
{313} {} {Nie mo¿na siê z tym k³óciæ. Ale zanim zaczniemy walkê o garœæ larw, czy mogê zadaæ jeszcze jedno pytanie?}
{314} {} {Dlaczego nie mogê wejœæ do magazynów?}
{315} {} {Magazyny przechowuj¹ zapasy ¿ywnoœci i wody. Moje wierne Szakale s¹ wyszkolone, by strzec tego miejsca. Rozerw¹ ciê na strzêpy, jeœli wejdziesz tam bez pozwolenia.}
{316} {} {Wygl¹da na to, ¿e dobrze wyszkoli³aœ tutaj wszystkich. Czy mogê o coœ jeszcze zapytaæ?}
{317} {} {Co s¹dzisz o Czarnym Kle?}
{318} {} {Jest najlepszym wojownikiem w plemieniu. Najsilniejszy, najbardziej wytrwa³y, najlepiej kontroluje w³óczniê i najlepiej przebija swoje ofiary. }
{319} {} {Wydawa³o mi siê, ¿e nie ¿yjecie w dobrych stosunkach.}
{320} {} {Jednoczeœnie jest najbardziej aroganckim, upartym i g³upim samcem ze wszystkich, jakich widzia³am. Kiedy stanie siê s³aby, bêdê pierwsz¹, która wyrwie mu oczy i otworzy mu klatkê piersiow¹.}
{321} {} {Macie tutaj strasznie surowe maniery. Mam nadziejê, ¿e mnie taki los nie czeka.}