{100} {} {Widzisz dzik¹ kobietê.}
{101} {} {Widzisz jedn¹ z samic Szakali. Jej ma³e czerwone oczy patrz¹ na ciebie z ciemnoœci.}

# Repliki plywajace
{120} {} {Znowu kilka robaków na obiad.}
{121} {} {Cœœœ, nie szczekaj na pró¿no!}
{122} {} {Mówi¹, ¿e w norach jest obcy.}
{123} {} {Potomstwo wymrze, jeœli nie znajdziemy po¿ywienia.}
{124} {} {Czas naostrzyæ pazury.}
{125} {} {Osoby z zewn¹trz nie znaj¹ litoœci.}
{126} {} {}
{127} {} {}
{128} {} {}
{129} {} {}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Daj mi powód, a oderwê ci miêso od koœci!}
{201} {} {Nakarmiê moje szczeniêta twoim miêsem.}
{202} {} {Moje pazury têskni¹ za twoim cia³em.}
{203} {} {}
{204} {} {}

{205} {} {Moje dzieci chc¹ twojej krwi.}
{206} {} {Moje dzieci s¹ g³odne i chc¹ twojego miêsa.}
{207} {} {Chcesz umrzeæ, nieznajomy?}
{208} {} {Um, ³adnie pachniesz.}
{209} {} {* Oblizuje usta, badaj¹c twoje cia³o *}

{210} {} {Uderz mnie!}
{211} {} {Chcê byæ twoj¹ suk¹!}
{212} {} {Mo¿esz ugryŸæ mnie w szyjê.}
{213} {} {}
{214} {} {}