{100} {} {Widzisz bandytê.}
{101} {} {Widzisz znajomego bandytê. Nie zmieni³ siê od czasu spotkania w barze Casa Grande.}
{102} {} {Nie mo¿esz tu byæ. IdŸ st¹d. Za³ó¿my, ¿e ciê nie widzia³em.}

{200} {} {Wiêc jesteœ tutaj. Co za niespodzianka. Jak tam burmistrz i jego rozpieszczona córka?}
{201} {} {Myœlê, ¿e maj¹ du¿o do przemyœlenia. Wiêc po tej historii w barze nadal bêdziesz rabowaæ i braæ zak³adników?}
{202} {} {Hmm, niez³y pomys³. Ale to nie jest takie proste. Ben ma plan. Zobaczymy co siê stanie. Porozmawiaj z nim, mo¿e siê mu przydasz.}
{203} {} {Pójdê ju¿.}
{204} {} {Czekaj. Ci¹gle myœla³em o tej historii w barze. Nie wiem, dlaczego nam pomog³eœ, ale pozostawanie tego bez odpowiedzi by³oby niesprawiedliwe. Powiedzia³em o tobie innym, ¿eby traktowali ciê lepiej. A tak¿e weŸ tê broñ i paczkê nabojów. Mo¿esz nie chcieæ krzywdziæ, ale nadal warto zastanowiæ siê nad w³asn¹ ochron¹.}
{205} {} {Dziêki.}
{206} {} {Prawdziwi w³adcy autostrad nie dziêkuj¹ i nie prosz¹. Zapamiêtaj to.}
{207} {} {Do widzenia.}
{208} {} {Niez³y zestaw do przetrwania.}
{209} {} {Powodzenia na szlakach. Niech py³ drogowy wieje ci w plecy i zakryje oczy wrogów.}

{210} {} {Czeœæ. Jak tam?}
{211} {} {Na razie nic.}
