{100} {} {Widzisz bandytê.}
{101} {} {Widzisz jednego ze z³odziei.}

{110} {} {Hej, jak tam biznes?}
{111} {} {Powodzenia na szlaku.}
{112} {} {Jesteœ fajniejszy ni¿ myœleliœmy.}
{113} {} {Nie mogê uwierzyæ, ¿e teraz tropimy obroñców.}
{114} {} {Szlaki s¹ teraz pod nasz¹ kontrol¹.}
{115} {} {Przynosisz nam szczêœcie.}
{116} {} {Ben ci ufa.}

{120} {} {Jeœli nie przestaniesz siê na mnie gapiæ, po¿a³ujesz.}
{121} {} {Czego chcesz, œmieciu?}
{122} {} {* Pluje w ty³ *}
{123} {} {Mimo ze Ben ciê wpuœci³, nie jesteœ jeszcze cz³onkiem gangu.}
{124} {} {Nudzê siê. Zabaw mnie.}
{125} {} {Bêd¹c tu sporo ryzykujesz.}

{130} {} {Kim ty do cholery jesteœ?}
{131} {} {Ty, b¹dŸ cicho. }
{132} {} {Przyda³a by mi siê zbroja taka jak twoja.}
{133} {} {Czy jesteœ jakimœ wynalazkiem Blacharzy?}
