{100} {} {Widzisz Bena.}
{101} {} {Przez maskê na twarzy ten cz³owiek wzbudza strach nawet u swoich podw³adnych.}
{102} {} {Nic osobistego. Ale za twoj¹ g³owê na pewno dostanê nagrodê.}
{103} {} {Napêdza³eœ to wszystko zdecydowanie zbyt d³ugo.}
{104} {} {Niez³e buty.}
{105} {} {Wypolerowana zbroja Bena odbija promieñ lasera bezpoœrednio w twoje oczy.}

{200} {} {Co za niespodzianka. Zwykle ludzie z zewn¹trz nas unikaj¹. (Daje znak innym). Braæ go!}
{201} {} {Nikt tutaj mnie nie dotknie, s³yszysz?}
{202} {} {[Nie opieraj siê]}
{203} {} {Nie, proszê, czy musisz to zrobiæ, jak mam przetrwaæ na pustyni?}
{204} {} {Jesteœ w mojej domenie, z³ó¿ ho³d, jeœli chcesz ¿yæ.}
{205} {} {Ok, rozumiem. WeŸ wszystkie moje rzeczy.}
{206} {} {Wiêc jesteœ zwyk³ym ³otrem. Zazwyczaj prowadzê krótk¹ rozmowê z takimi...}
{207} {} {Nienawidzê idiotów...}
{1207} {} {Nienawidzê idiotów...}
{208} {} {Hej, co przez to rozumiesz?}
{209} {} {Nie radzê nic robiæ ambasadorowi. W twoim najlepszym interesie jest utrzymanie mnie przy ¿yciu.}
{210} {} {O czym ty kurwa mówisz? Hm... NajwyraŸniej przys³a³ ciê Bustos. Ten g³upiec myœli, ¿e mo¿e siê nas pozbyæ za pomoc¹ kilku snajperów. Wiesz, zw³oki innego najemnika le¿¹ tu¿ za p³otem. Ale do tej pory nikt nie próbowa³ z nami rozmawiaæ.}
{211} {} {Dziêki, mam nadziejê, ¿e rozumiesz.}
{212} {} {To by³a op³ata. Teraz jestem gotów Ciê wys³uchaæ.}
{213} {} {Dziêki za zostawienie mnie przy ¿yciu.}
{214} {} {Jak mam teraz przetrwaæ bez tych rzeczy na pustyni?}
{215} {} {Oddaj mi moje rzeczy, sukinsynu.}
{216} {} {Wiêc uratowa³eœ mojego cz³owieka przed ³owcami nagród?}
{1216} {} {Wiêc uratowalas mojego cz³owieka przed ³owcami nagród?}
{217} {} {Dok³adnie. Chcê do³aczyæ do gangu.}
{218} {} {Tak. Powiedzia³, ¿e przyjmiesz mnie do gangu.}
{219} {} {Nie œpiesz siê. Nadal ci nie ufam, pomimo œwietnej rekomendacji. Jeœli chcesz do³aczyæ do gangu, musisz udowodniæ swoj¹ lojalnoœæ.}

{220} {} {To koñczy uprzejmoœci. Dlaczego tu jesteœ?}
{221} {} {W³aœciwie to jestem tu przez przypadek. Wygl¹da na to, ¿e lepiej jak sobie pójdê.}
{222} {} {Nie wiem, co masz na myœli. Mylisz mnie z kimœ innym.}
{223} {} {Zepsuæ sobie tak z³¹ reputacjê? Có¿, ja nie... Pomyli³eœ siê, kretynie.}

{230} {} {Szukam sojuszników, aby uwolniæ mój lud z niewoli.}
{231} {} {Co nas obchodz¹ Twoje problemy? Za handlem niewolnikami stoi zbyt wiele si³, aby im przeciwdzia³aæ.}
{232} {} {A co z wzajemn¹ pomoc¹? Prawdopodobnie potrzebujesz kogoœ, kto ma powi¹zania ze œwiatem zewnêtrznym.}
{233} {} {Wiêc mo¿esz mi pomóc?}
{234} {} {Nie. Idê st¹d.}
{235} {} {Ok...}
{236} {} {Nie wa¿ siê tak do mnie mówiæ, dziwaku.}
{237} {} {Hmm. Jest jedna rzecz. Moi ludzie zostali schwytani przez najemników i teraz s¹ torturowani w Casa Grande. Musimy rozwi¹zaæ ten problem.}
{238} {} {Sugerujesz ucieczkê?}
{239} {} {Zak³adnicy musz¹ siê zamkn¹æ. Nie obchodzi mnie jak. Jeœli nie mo¿na ich uratowaæ, nale¿y ich zabiæ.}
{240} {} {Odmawiam. Do diab³a z tob¹ i twoimi ch³opakami.}
{241} {} {Zadanie jest jasne. Zrobiê to.}
{242} {} {Daj mi czas na przemyœlenie rozwi¹zania. Nie chcia³bym zabijaæ nikogo w œrodku ca³ego miasta.}
{243} {} {Rób co uwa¿asz za stosowne. Burmistrz Casa Grande nie mo¿e wydobyæ informacji od moich ludzi.}
{244} {} {Ok. Wrócê, gdy rozwi¹¿ê problem.}

{250} {} {Aby powstrzymaæ ciebie i ca³y twój gang.}
{251} {} {Nigdy nie spotka³em nikogo g³upszego od ciebie. Fajnie bêdzie wspominaæ twoje s³owa po wszystkim.}
{252} {} {Uh, co robisz? O nie, nie to...}
{253} {} {Pierdol siê.}
{254} {} {}
{255} {} {Jestem tutaj w imieniu burmistrza Casa Grande. Uwa¿a ciê za winnego rabowania karawan.}
{256} {} {On doskonale wie, kto rabuje karawany i dlaczego. Jaki jest cel tej wizyty, najemniku?}
{1256} {} {On doskonale wie, kto rabuje karawany i dlaczego. Jaki jest cel tej wizyty, najemniku?}
{257} {} {Wiêc przyznajesz siê do winy. W imiê prawa wszyscy jesteœcie skazani na œmieræ.}
{258} {} {Ale dlaczego to robisz? Czy nie ma innych mo¿liwoœci?}
{259} {} {Mieszka³em w Casa Grande jako normalny i przestrzegaj¹cy prawa obywatel. Ale przyszed³ Bustos. Oglosi³ siê hrabi¹ i przej¹³ w³adzê w mieœcie. Tych, którzy siê nie zgadzali, nazwa³ przestêpcami i œciga³ swoimi ludŸmi.}
{260} {} {A teraz nie masz dok¹d pójœæ?}
{261} {} {Jesteœmy zajêci przetrwaniem tyrana i dyktatora. Rabuj¹c karawany, po prostu odbieramy to, co nam zabrano. Ponadto nie jesteœmy krwio¿erczy, litoœciwie puszczamy karawaniarzy, którzy nie chc¹ walki.}
{262} {} {Puszczacie, ¿eby znowu poprowadzili karawany do rabunku, prawda? Och, dranie...}
{263} {} {Nie obchodzi mnie, co o tym myœlisz.}
{264} {} {}
{265} {} {Nie obchodzi mnie, jak usprawiedliwiasz swoje zbrodnie. Zas³ugujesz na karê œmierci.}
{266} {} {Mo¿na ciê zrozumieæ. Ja musia³em znieœæ niewolê w Tu-San. Mogê ci pomóc.}
{267} {} {Szczerze mówi¹c, nie wiedzia³em o tej historii. Teraz zdecydowanie nie chcê pomagaæ Bustosowi.}

{270} {} {Chcê do³aczyæ do twojego gangu.}
{271} {} {Dlaczego?}
{272} {} {Poniewa¿ jesteœcie fajni, chcê byæ z wami.}
{273} {} {Myœlisz, ¿e wygl¹dam na idiotê? Jestem zmêczony s³uchaniem tych bzdur. Wykoñczyæ go...}
{1273} {} {Myœlisz, ¿e wygl¹dam na idiotê? Jestem zmêczony s³uchaniem tych bzdur. Wykoñczyæ j¹...}
{274} {} {Wow...}
{275} {} {Czekaj. Uratowa³em twoich ludzi w barze Casa Grande. Mo¿esz mi zaufaæ.}
{1275} {} {Czekaj. Uratowa³am twoich ludzi w barze Casa Grande. Mo¿esz mi zaufaæ.}
{276} {} {Chcê byæ czêœci¹ wielkiego stada, jak kiedyœ.}
{277} {} {Nastêpnie ustawiæ ogrzewanie (?). Mogê to zrobiæ.}
{278} {} {Lubiê star¹ dobr¹ przemoc. I tak nie nadajê siê do niczego innego.}

{280} {} {S³ysza³em te historie. Ale musisz udowodniæ swoj¹ lojalnoœæ.}
{281} {} {Oczywiœcie. Co mam zrobiæ?}
{282} {} {Brzmi przekonuj¹co. Ale musisz udowodniæ swoj¹ lojalnoœæ.}
{283} {} {Oczywiœcie. Co mam zrobiæ?}
{284} {} {Nie mam gdzie siê podziaæ na tym œwiecie. Handlarze niewolników spustoszyli moj¹ wioskê.}
{285} {} {Wiêc chcesz przetrwaæ, wchodz¹c do silnej grupy. Ale mo¿esz j¹ zdradziæ w ka¿dej chwili.}
{286} {} {Mogê udowodniæ swoj¹ lojalnoœæ. Przetestuj mnie.}
{287} {} {Jesteœ m¹drzejszy ni¿ siê wydajesz. Teraz zosta³o mi tylko jedno... Umrzyj, skurwysynu!}
{288} {} {Uratowa³em twoich ludzi w barze Casa Grande. Mo¿esz mi zaufaæ.}
{1288} {} {Uratowa³am twoich ludzi w barze Casa Grande. Mo¿esz mi zaufaæ.}

{290} {} {Uciek³em z niewoli Blacharzy. Nie mam teraz dok¹d pójœæ.}
{1290} {} {Uciek³am z niewoli Blacharzy. Nie mam teraz dok¹d pójœæ.}
{291} {} {Mo¿na ciê zrozumieæ. Wielu ludzi na tych ziemiach denerwuj¹ Blacharze. My sami staliœmy siê ofiar¹ ich ekspansji.}
{292} {} {Czy to znaczy, ¿e mnie akceptujesz?}
{293} {} {Musisz udowodniæ swoj¹ lojalnoœæ wobec gangu.}
{294} {} {Oczywiœcie. Co mam zrobiæ?}
{295} {} {Arena w Phoenix nauczy³a mnie tylko jednej rzeczy - biæ innych po mordzie.}

# Powtarzajacy siê dialog (po otrzymaniu zadañ)
{300} {} {Jakieœ nowe wiadomoœci?}
{301} {} {Czeœæ Ben.}

{310} {} {Opowiedz mi o gangu.}
{311} {} {Nie jesteœ wart mojego czasu. Najpierw poka¿ siê w akcji.}
{312} {} {Zrozumia³em wskazówkê.}
{313} {} {Co chcesz wiedzieæ?}
{314} {} {To wszystko. Mi³o siê rozmawia³o.}
{315} {} {Kolejne pytanie.}
{316} {} {Dlaczego nazywacie siê Niebieskie Tarcze?}
{317} {} {Popatrz na federalne znaki drogowe na naszych kurtkach. Wygl¹daj¹ jak tarcze. I s¹ niebieskie. Nad¹¿asz?}
{318} {} {Myœlê, ¿e tak.}
{319} {} {Jak mo¿ecie przetrwaæ na tych ziemiach?}
{320} {} {Rabowanie karawan, polowanie, zbieranie kosztownoœci z ruin to œwietne Ÿród³a wszystkiego czego nam trzeba. Baza paliwa te¿ jest bardzo przydatna. Ogieñ, podobnie jak woda, daje ¿ycie. Handlarze wod¹ w Casa Grande nie mog¹ zrozumieæ naszej zaciek³oœci.}
{321} {} {To wszystko. Ciekawe.}
{322} {} {Ale jak doszed³eœ do tego etapu ¿ycia? Sk¹d siê wziêli ci wszyscy ludzie?}
{323} {} {Ka¿dy tu ma swoj¹ historiê. Ale wszyscy jesteœmy wygnañcami. Niektórzy zostali wyrzuceni z Casa Grande, gdy do w³adzy doszed³ hrabia Bustos. Inni zostali wypêdzeni z domów przez Blacharzy. S¹ tacy, którzy uciekli przed problemami Phoenix. Nie mamy innego wyjœcia.}
{324} {} {To naprawdê burzliwy czas.}
{325} {} {W czym przeszkadzaj¹ Ci Blacharze?}
{326} {} {Ich moc siê rozszerza, a Pustkowia bior¹ to za coœ oczywistego. Bezczelnie przejmuj¹ technologie i zasoby, narzucaj¹ swój porz¹dek w innych osadach, zmuszaj¹ je do pracy na chwa³ê swoich pomys³ów. Teraz robimy to samo z ich karawanami.}
{327} {} {[Pos³uchaj]}
{328} {} {Wymyœlili w³asne rozumienie ¿ycia i zaczeli ustalaæ dla nas w³asne zasady. Kto ich o to prosi³? Kto da³ im prawo decydowania, co jest dobre, a co z³e? Kiedyœ by³o ³atwiej. Wczeœniej ka¿dy wiedzia³, ¿e ma racje, i by³ w stanie stan¹æ w obronie w³asnej prawdy.}
{329} {} {Wiêc walczysz z najeŸdŸcami ich w³asnymi metodami? Ciekawe.}
{330} {} {Opowiedz mi o Rio. Przede mn¹ nie chce siê otworzyæ.}
{331} {} {On i ja jesteœmy starymi przyjació³mi. Jest moj¹ praw¹ rêk¹, ufam Rio jak nikomu innemu. Wiem te¿, ¿e nie lubi ka¿dego, kto próbuje zas³u¿yæ na mój szacunek. Bêdziesz musia³ to zaakceptowaæ i znaleŸæ z nim wspólny jêzyk.}
{332} {} {Rozumiem.}
{333} {} {Co to w³aœciwie jest za miejsce?}
{334} {} {Stacja „Petro Chico”. Przed wojn¹ sk³adowano tu paliwo. Wydaje siê, ¿e by³o bardzo cenne, skoro dooko³a wzniesiono tak potê¿ne ogrodzenie. Teraz daje nam ogieñ.}
{335} {} {Rozumiem.}
{336} {} {Jaki masz problem z burmistrzem Casa Grande?}
{337} {} {Hrabia Bustos to tyran. Sprytnie przej¹³ w³adzê w mieœcie, uciszy³ lub wypêdzi³ wszystkich sprzeciwiaj¹cych mu siê. Teraz cieszy siê czyst¹ ³azienk¹ przy muzyce króla Cole'a, podczas gdy my ¿yjemy na ja³owej pustyni z jego winy.}
{338} {} {Wygl¹da na to, ¿e masz go prawie w garœci. Zmienimy motyw?}

{350} {} {Gotowe. Twój kolega nie ¿yje.}
{351} {} {Twój kolega zosta³ zabity przez miejscowych. Zorganizowali lincz w samym centrum miasta.}
{352} {} {Gotowe. Twój kolega uciek³ z wiêzienia w Casa Grande.}
{353} {} {On nie jest moim koleg¹. Jest tylko trybikiem w moim systemie. Zawdziêcza mi ¿ycie, nawet jeœli za to p³aci.}
{354} {} {Có¿, sam to rozwi¹¿esz.}
{355} {} {Niez³e przemówienie.}
{356} {} {Teraz widzê, ¿e mo¿esz sobie z tym poradziæ. Gang potrzebuje kontaktu z reszt¹ œwiata, bêdziesz naszym poœrednikiem.}
{357} {} {Gdzie mam iœæ tym razem?}
{358} {} {No, w koñcu zda³eœ sobie sprawê, ¿e jestem tutaj z jakiegoœ powodu.}
{359} {} {Nie bez powodu wys³a³em tego goœcia na misjê zwiadowcz¹. Blacharze powiêkszaj¹ swoj¹ moc, karawany rosn¹, a burmistrz Casa Grande zatrudnia coraz wiêcej z³ych najemników. Na tych ziemiach pojawia siê nowy porz¹dek i szykuj¹ siê Wielkie Wojny Drogowe. Mój gang musi zdobyæ przyczó³ek w tym nowym œwiecie.}
{360} {} {Co zrobisz?}
{361} {} {Jesteœmy teraz wyjêci spod prawa. Jesteœmy uwa¿ani za przestêpców. Chcê wynegocjowaæ rozejm z Blacharzami. Udaj siê do Tu San i przekonaj Mistrza Hard do podpisania traktatu - nasze paliwo w zamian za niepodleg³oœæ.}
{362} {} {A jeœli odmówi?}
{363} {} {Nie powinien odmówiæ. Ale jeœli, to zrób wszystko, aby go przekonaæ.}
{364} {} {Rozumiem. Idê na misjê.}
{365} {} {Co wiesz o Blacharzach?}
{366} {} {To zamkniêta spo³ecznoœæ. Czcz¹ technologie i nie lubi¹ obcych, uwa¿aj¹ nas za gorszych od siebie. Ale dziêki ich produkcji ziemie te odrodzi³y siê ponownie, zaczê³a dzia³aæ stacja wodna i pojawi³ siê handel.}
{367} {} {Rozumiem.}
{368} {} {O umowie. Czy poda¿ paliwa w zbiornikach nie jest ograniczona?}
{369} {} {Spójrz na te zapasy. Transport zajmie miesi¹ce. W tym czasie zdobêdziemy du¿o kapsli i bêdziemy mogli zdecydowaæ, co dalej. Zamierzam zamówiæ u Blacharzy trochê technologii, np. do produkcji nabojów. W ten sposób staniemy siê samowystarczalni i bêdziemy mogli przenieœæ siê do miejsc bogatych w inne dobra.}

{370} {} {Z³e wieœci - Blacharzy pokona³a sztuczna inteligencja. Nie ma ju¿ z kim negocjowaæ.}
{371} {} {Z³e wieœci - Mistrz Hard nie ¿yje, a pozostali Blacharze s¹ zbyt agresywni wobec obcych.}
{372} {} {Wiêc to prawda? Cholera, szlaki znów bêd¹ puste bez Blacharzy. Bêdzie mniej karawan, zaszkodzi to wszystkim mieszkañcom. Wygl¹da na to, ¿e nadchodz¹ ciê¿kie czasy.}
{373} {} {Jakie masz teraz plany?}
{374} {} {Musimy teraz nakraœæ tyle i tylko siê da. A kiedy szlaki bêd¹ zupe³nie puste, bêdzie trzeba udaæ siê w góry w poszukiwaniu zwierzyny.}
{375} {} {Rozumiem.}
{376} {} {Nie mam dla ciebie wiêcej zadañ. Mo¿esz iœæ.}
{377} {} {Do widzenia Ben.}

{380} {} {Dobra wiadomoœæ - Hard zgodzi³ siê na umowê handlow¹.}
{381} {} {Hmm, wygl¹da na to, ¿e nasza sytuacja siê poprawia. Chocia¿ by³em prawie pewien, ¿e pomys³ nie zadzia³a. Jednak dogadanie siê z Blacharzami nie wystarczy.}
{382} {} {Kto jeszcze ciê powstrzymuje?}
{383} {} {Hrabia Bustos, burmistrz Casa Grande. Jeœli odmówi uznania nas za pokojow¹ osadê, ludzie z karawany nadal nie bêd¹ z nami robiæ interesów. Musisz przekonaæ go do podpisania umowy... lub - pozbyæ siê go.}
{384} {} {Zabiæ Bustosa, ¿eby nie przeszkadza³? Wydaje siê to bardziej realistyczne ni¿ negocjacje.}
{385} {} {Najpierw spróbujê z nim negocjowaæ. Trudno powiedzieæ, co stanie siê z miastem bez niego.}
{386} {} {Zrób to dla gangu. Za nasz¹ d³ugo wyczekiwan¹ wolnoœæ.}
{387} {} {Mo¿esz na mnie liczyæ Ben.}

{390} {} {Hrabia Bustos nie chcia³ zawieraæ sojuszu. Trzeba go by³o „przekonaæ”.}
{391} {} {Hrabia Bustos zgodzi³ siê na sojusz. Przekonanie go nie by³o ³atwe.}
{392} {} {Dziêki tobie gang nabierze nowego ¿ycia. Nadchodzi nowy czas, kiedy Blacharze podziel¹ siê swoimi technologiami z reszt¹ œwiata. A my bêdziemy wœród wybranych. Nie bêdzie ju¿ potrzeby rabowania podró¿nych.}
{393} {} {[Dalej.]}
{394} {} {Nigdy nie przypuszcza³em, ¿e twoja pomoc bêdzie tak... pomocna. Udowodni³eœ swoj¹ lojalnoœæ wobec gangu i mo¿esz z dum¹ nosiæ tytu³ B³ekitnej Tarczy. W nagrodê weŸ tê kurtkê i miotacz ognia.}
{1394} {} {Nigdy nie przypuszcza³em, ¿e twoja pomoc bêdzie tak... pomocna. Udowodni³aœ swoj¹ lojalnoœæ wobec gangu i mo¿esz z dum¹ nosiæ tytu³ B³ekitnej Tarczy. W nagrodê weŸ tê kurtkê i miotacz ognia.}
{395} {} {[Dalej.]}
{396} {} {Wydaje siê, ¿e masz przed sob¹ jeszcze d³ug¹ drogê. Pamiêtam, ¿e potrzebowa³eœ sojuszników. Motor mo¿esz odebraæ u Rio. Dziêki niemu szybko dotrzesz do dowolnego miejsca na pustkowiach.}
{397} {} {Dziêkujê Ben. Jesteœ prawdziwym przyjacielem.}
{398} {} {Nie mów "dziêkujê". Nie znamy tego s³owa. Po prostu weŸ to, na co zas³ugujesz. To twoje prawo.}
{399} {} {Do widzenia, Ben.}