{100} {} {Widzisz zmutowanego Edmonda.}
{101} {} {Widzisz mocno oszpecon¹ osobê.}
{102} {} {Mutant nagle wy³ania siê z cienia.}

{110} {} {OdejdŸ i nie dotykaj nas.}
{111} {} {Zostaw mnie!}
{112} {} {Nie chcê z tob¹ rozmawiaæ.}
{113} {} {Nieznajomym nie mo¿na ufaæ.}

{120} {} {Ooh! Ooh!}
{121} {} {Ap-r!}
{122} {} {kwi!}
{123} {} {Bah! Kobieta!}

{200} {} {(Mutant blokuje ci drogê i wymachuje czymœ niebezpiecznym.) Ooo! Ooh!}

{201} {} {[Cofnij siê, by okazaæ swoj¹ ¿yczliwoœæ]}
{202} {} {kwi! (wyczuwaj¹c twoj¹ niepewnoœæ i niechêæ do walki mutant postanawia zaatakowaæ!)}
{203} {} {Nie, nie dotykaj mnie!}
{204} {} {Ty draniu!}
{205} {} {Stop! Ani kroku naprzód!}
{206} {} {(Twoje s³owa tylko rozgniewa³y mutanta, przez co decyduje siê on zaatakowaæ!)}

{210} {} {[Zrób prowokacyjny krok naprzód]}
{211} {} {Ap-r! (mutant cofa siê, a jego spojrzenie staje siê jeszcze bardziej szalone)}
{212} {} {S³uchaj, nie chcê walki. Uwierz mi.}
{213} {} {Giñ potworze!}
{214} {} {Stop! Ani kroku w bok!}

{220} {} {(Mutant gwa³townie staje i cofa siê o krok. Wygl¹da na to, ¿e twoja determinacja go przestraszy³a.)}
{221} {} {Co s³ychaæ przystojniaku? Nie chcesz walki, prawda?}
{222} {} {Tak lepiej. I nie próbuj ¿adnych numerów, œmieciu.}
{223} {} {(Mutant stoi ca³y odrêtwia³y i niezdecydowany. Patrzysz na jego oszpecon¹ twarz, na której widaæ przera¿enie i lata bólu. Jego stare cia³o jest chude i poskrêcane.)}
{224} {} {Ha, nic dziwnego, ¿e siedzisz w piwnicy, podczas gdy inni walcz¹ na górze. Jak uda³o ci siê przetrwaæ z takimi patologiami?}
{225} {} {Biedny ch³opie, by³eœ taki od pocz¹tku? To cud, ¿e wci¹¿ ¿yjesz.}
{226} {} {(Nagle za mutantem, z s¹siedniego pokoju, s³ychaæ czyjœ histeryczny p³acz. DŸwiêk o¿ywia mutanta przez co ten przyjmuje postawê obronn¹, blokuj¹c wejœcie do pokoju.)}
{227} {} {Kto tam jest? Kogo tam torturujesz?}
{228} {} {kwi! (pokazuje, ¿eby odejœæ)}
{229} {} {Odpowiedz!}
{230} {} {Ahh! Ah-r-r!}
{231} {} {Cholerny sukinsynu! Umieraj!}
{232} {} {Odsuñ siê i nie wchodŸ mi w drogê, œmieciu.}
{233} {} {Nie mo¿esz rozmawiaæ? Przyjdê potem i dowiem siê, co siê tam dzieje.}
{234} {} {(¿a³oœnie krêci g³ow¹)}
{235} {} {Wynoœ siê st¹d. Jeœli wrócisz, umrzesz. Jasne?}
{236} {} {Nie zabijê ciê, jeœli odejdziesz i nie bêdziesz siê wtr¹caæ. No dalej, zaczerpnij œwie¿ego powietrza.}