{100} {} {Widzisz pani¹ Bates.}
{101} {} {Widzisz bardzo oszpecon¹ kobietê.}
{102} {} {* P³acze *}
{103} {} {Moje dzieci ciê zabij¹ i zjedz¹.}

{200} {} {(W mroku koszar dostrzegasz na ³ó¿ku kobietê; cicho szlocha, odwracaj¹c siê od ciebie).}
{201} {} {Hej, proszê pani...}
{202} {} {Wynoœ siê! WyjdŸ!}
{203} {} {Uspokój siê, chcê ci pomóc.}
{204} {} {Przestañ krzyczeæ, albo wpadn¹ tu ci mutanci.}
{205} {} {Nie! Nie dotykaj mnie! A-ah-ah!}
{206} {} {W porz¹dku. Te potwory ju¿ ci nie zagra¿aj¹.}
{207} {} {Albo siê zamkniesz, albo ciê zakneblujê. Co wybierasz?}
{208} {} {(Kobieta przestaje krzyczeæ; w przerwie zauwa¿asz okropne blizny na ca³ym jej ciele.)}
{209} {} {Dobry Bo¿e, potrzebujesz lekarza. Pomogê ci siê st¹d wydostaæ.}
{210} {} {ChodŸ za mn¹, jeœli chcesz ¿yæ.}
{211} {} {Dlaczego?}
{212} {} {Co?}
{213} {} {Dlaczego mia³abym wyjœæ na zewn¹trz? To jest mój dom. Nie odejdê.}
{214} {} {Ale... Wiêc kim s¹ te potwory?}
{215} {} {Sherman, George, Edmond - to dobrzy ludzie, mogê byæ z nich dumna. Mam facetów ze z³ota.}
{216} {} {Czy te ogry i mordercy s¹ twoimi synami?}
{217} {} {Suko, masz na myœli te dziwol¹gi, to twoje dzieci?}
{218} {} {Ha, mo¿na od razu powiedzieæ, ¿e nie masz swoich dzieci. Moje s¹ dla mnie dum¹ i mi³oœci¹. Nikt nie z³amie rodziny Batesów. Zaden z obcych nie by³ w stanie.}
{219} {} {Jest ju¿ za póŸno, by chwaliæ siê osi¹gniêciami rodziny. Twoi maniacy nie ¿yj¹. Wszyscy trzej.}
{220} {} {Morderca! Moje dzieci tylko chcia³y ¿yæ. Wszyscy obcy próbowali ich zabiæ. Tak samo jak ty. Dlaczego jesteœ taki z³y? (kobieta gwa³townie odwraca swoj¹ oszpecon¹ twarz w Twoj¹ stronê) Od zawsze nikogo do siebie nie wpuszczamy. Obcy przynosz¹ nam tylko œmieræ!}
{221} {} {Nie...}
{222} {} {To brzmi trochê znajomo...}
{223} {} {Ale w porz¹dku. Wszyscy jesteœmy jedn¹ rodzin¹. Nikt nie z³amie Batesów. Bêd¹ nowi. Pewnego dnia. Ha! Ha ha! A-ha-ha! A-ha-ha-ha...}
{224} {} {[Zostaw mutanta w spokoju]}
{225} {} {Jesteœ po prostu szalona.}
{226} {} {Zabiliœcie wielu ludzi. Nale¿y to zakoñczyæ.}
{227} {} {Myœlisz, ¿e nie poradzê sobie z kilkoma dziwakami?}
{228} {} {Moi synowie ciê zabij¹! I ka¿dego innego obcego. Poniewa¿ jesteœmy rodzin¹. Nikt nie mo¿e z³amaæ Batesów. Ha! Ha ha! A-ha-ha! A-ha-ha-ha...}
{229} {} {W³aœciwie dobrze ciê rozumiem. Moj¹ wioskê te¿ próbowali rozbiæ obcy. Dlatego jeszcze siê trzymam.}
{230} {} {Moj¹ wioskê te¿ próbowali rozbiæ obcy. Nie pozwolê ci mnie powstrzymaæ. Twoi synowie próbowali i teraz nie ¿yj¹.}
