{100} {} {Widzisz ofiarê kanibala.}
{101} {} {Widzisz torturowanego mê¿czyznê.}
{102} {} {Tu jest zdecydowanie lepiej ni¿ w tym starym motelu. Ju¿ nigdy nie zostanê na noc w takiej dziurze.}

{200} {} {Ach! Nie dotykaj mnie!}
{201} {} {Nie zamierzam ciê dotykaæ. Spokojnie.}
{202} {} {Zamknij siê, idioto. Bo na us³ysz¹.}
{203} {} {Huh? Czyli nie jesteœ mutantem? Och... Jak siê cieszê, ¿e ciê widzê...}
{204} {} {Dlaczego mutanci ciê tu zamknêli?}
{205} {} {Nie widzisz tych wszystkich koœci? To kanibale! Wabi¹ ludzi w pu³apki, a potem morduj¹ ich jak byd³o.}
{206} {} {Co za horror.}

{210} {} {Muszê st¹d wyjœæ! Zabili wszystkich innych... Zabij¹ te¿ nas!}
{211} {} {Usi¹dŸ tu na razie, a ja zobaczê, czy przed nami jest jakieœ niebezpieczeñstwo.}
{212} {} {Dobra. Odprowadzê ciê do najbli¿szej osady. Spokojnie. Po prostu b¹dŸ cicho.}
{213} {} {Nadal trzêsê siê ze strachu. Musimy jak najszybciej opuœciæ to miejsce.}
{214} {} {Wiêc nie traæmy czasu. ChodŸmy.}
{215} {} {Usi¹dŸ tutaj i nie wychylaj siê. Przeprowadzê zwiad.}

{220} {} {Jesteœmy teraz zdecydowanie bezpieczni. Uf. Gdyby nie ty, zosta³bym pewnie ju¿ dawno po¿arty. Dziêkujê Ci. Powiem ka¿demu, kogo znam, kto mnie uratowa³.}
{221} {} {To œwietnie. Powodzenia.}
