{100} {} {Widzisz imigranta z Phoenix.}
{101} {} {Widzisz mê¿czyznê w zakurzonym ubraniu. Jego rêce s¹ pokryte b³otem.}
{102} {} {Czeœæ.}

{200} {} {Co za niespodzianka. Wiedzieliœmy, ¿e czasami przechodz¹ têdy podró¿nicy. Ale nie spodziewaliœmy siê, ¿e tak szybko spotkamy now¹ twarz.}
{201} {} {Czy jesteœ tu od niedawna?}
{202} {} {Tak, w³aœnie siê wprowadzi³em. Jeœli szukasz noclegu, to przepraszam - nie mamy wystarczaj¹co miejsca, wszystkie pokoje s¹ zajête.}
{203} {} {Nie, chcê tylko porozmawiaæ.}
{204} {} {Spaæ w tym motelu? Nie, dziêkujê. Wolê spêdziæ noc na pustyni pod go³ym niebem.}
{205} {} {Tak, w³aœnie siê wprowadzi³em. Jeœli szukasz noclegu, to przepraszam - nie ma wolnych pokoi. Ale nie mam nic przeciwko rozmowie z rzadkim podró¿nikiem.}

{210} {} {Niestety, brak ju¿ wolnych miejsc. Ale nie mam nic przeciwko podzieleniu siê kilkoma s³owami z rzadkim podró¿nikiem.}
{211} {} {Sk¹d siê wzi¹³eœ?}
{212} {} {Jesteœmy osadnikami z Phoenix. Jesteœmy tutaj, aby za³o¿yæ now¹ spo³ecznoœæ. Sam Aaron da³ nam akt sprzeda¿y tej ziemi.}
{213} {} {Za co?}
{214} {} {Pracowa³em dla chwa³y Jego idei. By³o to równie¿ ³atwe, poniewa¿ Aaron jest zainteresowany kolonizacj¹ okolicy pod w³asnym sztandarem.}
{215} {} {No có¿. Jak mo¿esz to udowodniæ?}
{216} {} {Mamy papier. Mamy to za prace nad honorowaniem pomys³ów Aarona. Czemu tak bardzo w to w¹tpisz?}
{217} {} {Jak mo¿na dostaæ prawo do takiego motelu?}
{218} {} {Tylko Aaron mo¿e kontrolowaæ ziemie wokó³ Phoenix. I nie próbuj mówiæ, ¿e tak nie jest.}
{219} {} {Nie jest.}
{220} {} {Jak œmiesz bezczeœciæ imiê œwiêtego mê¿a? Trzymaj gêbê na k³ódkê, albo stracê cierpliwoœæ. Wynoœ siê st¹d! Pro-och!}
{221} {} {Ok, ok...}
{222} {} {Hej, spokojnie...}
{223} {} {Wykonuje œwietn¹ robotê.}
{224} {} {Chwa³a niech bêdzie imieniu Aarona! Osobie, która daje ¿ycie pustyni.}
{225} {} {Aaron zosta³ zabity. Wiesz o tym?}
{226} {} {Aaron i jego katedra zostali zniszczeni. Wiesz o tym?}
{227} {} {Jak œmiesz o tym mówiæ? Oczywiœcie Aaron ¿yje, a jego katedra jest tam, gdzie sta³a. Zamknij swoje pod³e usta, zanim stracê panowanie nad sob¹.}
{228} {} {Ludzie zawsze obra¿aj¹ siê przez prawdê.}
{229} {} {Hej, spokojnie...}

{230} {} {Czy wiesz, ¿e kiedyœ tu mieszkali mutanci?}
{231} {} {To, co siê sta³o, minê³o. Musimy zacz¹æ od nowa, a nie grzebaæ w przesz³oœci.}
{232} {} {Czy jesteœ gotowy, aby siê tu wprowadziæ, wiedz¹c o okropnoœciach, jakie dzia³y siê w œcianach tego motelu?}
{233} {} {Chocia¿ ci mutanci byli kanibalami i sadystami, dbali o ten motel. Dlatego zatrzymaliœmy siê tutaj. Bo to jedyne miejsce w okolicy nadaj¹ce siê do ¿ycia!}
{234} {} {Co takiego zrobili mutanci, ¿e twoim zdaniem mo¿na tu ¿yæ?}
{235} {} {Naprawili dach i p³oty, zrobili ³ó¿ka, zainstalowali pustynne zbiorniki na wodê - to œwietne miejsce do rozpoczêcia wszystkiego od nowa.}
{236} {} {To znaczy, ¿e przyszed³eœ na gotowe.}
{237} {} {Myœlê, ¿e powinieneœ ju¿ iœæ.}
{238} {} {Tak, muszê iœæ. Zegnam.}
{239} {} {To by³o niegrzeczne z twojej strony. Teraz zdecydowanie nie chcê tu d³u¿ej byæ.}
{240} {} {Mogê tylko cieszyæ siê razem z tob¹. To cholerne miejsce siê przyda.}
{241} {} {Teraz bêdzie inaczej. Aaron da³ nam i motelowi drug¹ szansê. Obiecujê, ¿e uczynimy z tej pustyni ziemie obiecan¹.}
{242} {} {Amen.}
{243} {} {Powodzenia.}
