{100} {} {Widzisz przed sob¹ wartownika.}
{101} {} {Widzisz jednego ze z³odziei.}
{102} {} {Wygl¹da na to, ¿e zaczynam mieæ halucynacje ...}

{110} {} {Szukasz k³opotów, œmieciu?}
{1110} {} {Szukasz k³opotów, suko?}

{200} {} {(Uœpiony w s³oñcu wartownik podnosi g³owê, gdy podchodzisz; zaskoczony, upuszcza broñ, ale szybko odzyskuje przytomnoœæ).}
{201} {} {[Dalej.]}
{202} {} {Co... kim ty kurwa jesteœ? Czego tu szukasz?}
{203} {} {Co... Matko, dziwaku, nie mo¿esz podkradaæ siê tak do ludzi. Czego potrzebujesz?}
{204} {} {Przestañ, kim jesteœ... Hej, ch³opcy, mam tu szpiega!}
{205} {} {Nie powinieneœ by³ tego robiæ...}
{206} {} {Kto jest szpiegiem? JA?}

{210} {} {Dobre pytanie. Co to za miejsce?}
{211} {} {Swietne miejsce dla suki. Nie wiesz, kim s¹ Niebieskie Tarcze? Kontrolujemy wszystkie szlaki w okolicy. A to jest nasz obóz.}
{212} {} {Wiêc to wy okradacie podró¿ników na autostradach? Co za szczêœcie, ¿e nie muszê ju¿ was szukaæ. Nareszcie zniszczê was wszystkich.}
{213} {} {Ty? Nie bêdziesz nawet w stanie stawiæ oporu. Band¹ przegranych na starym z³omowisku - oto kim wszyscy jesteœcie.}
{214} {} {Zamknij swoje gówniane usta, padlino drogowa... (chwyta broñ z wœciek³ym uœmiechem)}
{215} {} {A potem co?}
{216} {} {Ups...}
{217} {} {Wow. Jesteœcie wspaniali. Czy macie wolne miejsca w gangu? Rozwa¿am do³¹czenie.}
{218} {} {Ha, nie ma u nas miejsca na œcieki takie jak ty. Wynoœ siê st¹d, póki jestem dobry.}
{219} {} {Ok, ok, ju¿ wychodzê.}
{220} {} {Zabierz mnie do lidera. Byæ mo¿e bêdzie mia³ inne zdanie.}
{221} {} {Tutaj * ja * decydujê, kogo wpuœciæ. Jasne? I nie dasz rady. WyjdŸ st¹d.}
{222} {} {Wpuœæ mnie albo sam wejdê.}
{1222} {} {Wpuœæ mnie albo wejdê sama.}
{223} {} {Spróbuj, suko.}
{224} {} {Wydajesz siê rozumieæ tylko brutaln¹ si³ê. W takim razie "porozmawiajmy"...}
{225} {} {Ok, ty tu jesteœ szefem, pozwól mi odejœæ.}
{226} {} {Zabierz mnie do lidera. Natychmiast.}
{227} {} {Ok, chodŸ za mn¹.}
{228} {} {[Obserwuj go]}
{229} {} {A jeœli ³adnie poproszê? Na przyk³ad dam ci 25 kapsli?}
{230} {} {(podnosi kapsle i rozgl¹da siê) Ok, chodŸ za mn¹.}
{231} {} {[Obserwuj go]}
{232} {} {(Przygl¹da siê uwa¿nie, gdy szukasz nieistniej¹cych kapsli w swoich kieszeniach).}
{233} {} {Uh, zaraz je przyniosê. Serio...}
{234} {} {Kurwa. Po prostu ciê zabiæ tu i teraz...}
{235} {} {Powinienem by³ zacz¹æ od tego. Po prostu odejdê.}
{236} {} {Nie tak szybko, suko. Oddaj wszystkie kapsle i mo¿esz iœæ.}

{240} {} {Podró¿ujê. Czy jest tu dla mnie miejsce do spania?}
{241} {} {(Opuszcza broñ i rozgl¹da siê uœmiechaj¹c). A wiêc to tak. Czy ty w ogóle wiesz, gdzie jesteœ, suko? To suko, to obóz Niebieskich Tarcz. Wieszamy ludzi takich jak ty na drogowych billboardach, wiesz? A teraz wynoœ siê, jeœli cenisz swoje ¿ycie.}
{242} {} {Phi, nie³adnie. Nie za wiele sobie pozwalasz?}
{243} {} {(uœmiech zsuwa siê z jego twarzy) Co mówisz, suko? Powiedz to jeszcze raz, mo¿e Ÿle us³ysza³em?}
{244} {} {Powtarzam: jesteœ gównem.}
{245} {} {Och, przepraszam! Jestem tu nowy. Nie zobaczysz mnie ponownie.}
{246} {} {Hej, padlino, posun¹³eœ siê za daleko. Teraz oddasz mi wszystkie swoje kapsle.}
{1246} {} {Hej, padlino, posunê³aœ siê za daleko. Teraz oddasz mi wszystkie swoje kapsle.}
{247} {} {Nic nie dostaniesz.}
{248} {} {Oczywiœcie, oczywiœcie, oto wszystkie moje kapsle, proszê...}
{249} {} {Gdzie jestem? Powiedz mi, co to za miejsce.}
{250} {} {Tym razem to zignorujê. A teraz zabierz mnie do swojego przywódcy.}
{251} {} {Zabierz mnie do swojego przywódcy. Muszê z nim porozmawiaæ.}
{252} {} {(drapie siê po brudnej szyi w zamyœleniu) Chcesz poznaæ Bena? Czy wiesz w ogóle, gdzie jesteœ?}
{253} {} {Wiem. Jestem w jakiejœ zgni³ej dziurze. A teraz oczyszczê to miejsce z brudu.}
{254} {} {Racja. Gdzie ja jestem?}
{255} {} {Jestem tutaj w imieniu burmistrza Casa Grande. Zabierz mnie natychmiast do swojego szefa.}
{256} {} {[Pos³uchaj i wróæ na pustyniê]}

{300} {} {Czy ty serio nadal tu jesteœ? Wygl¹da na to, ¿e masz k³opoty.}
{301} {} {Muszê porozmawiaæ z twoim przywódc¹.}
{302} {} {Nadal tu jesteœ? Nie wiem, co próbujesz osi¹gn¹æ, ale nie odmówiê jeszcze jednej butelki.}
{303} {} {Mogê napiæ siê alkoholu, jeœli pójdziesz do szefa.}
{304} {} {Kurwa. Wchodzê.}
{305} {} {Ok, ok, ju¿ wychodzê.}
{306} {} {Wpuœæ mnie.}
{307} {} {Natkn¹³em siê na jednego z twoich na pustyni. Powiedzia³, ¿e mogê porozmawiaæ z Benem.}
{308} {} {Ach, to wiele zmienia. Ben pewnie bêdzie chcia³ Ciê zobaczyæ. WejdŸ, ale uwa¿aj na swój jêzyk, lepiej nikogo nie prowokowaæ.}
{309} {} {Ok.}

{310} {} {Powodzenia na szlaku, bracie.}
{1310} {} {Powodzenia na szlaku, siostro.}
{311} {} {Czego chcesz, bracie?}
{1311} {} {Czego chcesz, siostro?}
{312} {} {Spierdalaj.}
{313} {} {Nie lubiê ciê. Wynoœ siê z gangu, œmieciu.}
{314} {} {Rêce mnie swedz¹, ¿eby obiæ ci pysk.}
{315} {} {Do widzenia.}

{320} {} {Jak d³ugo jesteœ w gangu?}
{321} {} {Tak. Czym jest dla Ciebie? Uwa¿aj na dupê.}
{322} {} {Rzeczywiœcie. A jednak jest tu ca³kiem ok.}
{323} {} {Umgu.}
{324} {} {Zawsze spotykasz takich nowicjuszy, kretynie?}
{325} {} {Masz szczêœcie, ¿e Ben pozwoli³ ci spacerowaæ po bazie. Ale nie rób tego.}
{326} {} {Dlaczego?}
{327} {} {Bo siê nam to nie podoba. Ponadto wokó³ bazy jest wiele pu³apek, lepiej uwa¿aj.}
{328} {} {Pu³apki? Czy mo¿esz mi je pokazaæ?}
{329} {} {Nie le¿¹ tam ¿eby je ogl¹dac, wiesz? Powiedzia³em ci ju¿ wszystko.}
{330} {} {Ok. Jasne. Czeœæ.}
{331} {} {Chodzi o pu³apki. Czy mo¿esz mi dok³adniej pokazaæ ich po³o¿enie?}
{332} {} {Zap³acê 50 kapsli. Nie martw siê, nikt siê o tym nie dowie.}
{333} {} {Nie. Dla takiego debila jak ty kosztowa³oby to 100 kapsli.}
{334} {} {To za drogo.}
{335} {} {Ok. Niech bêdzie 100 kapsli.}
{336} {} {Muszê wiedzieæ na pewno. Ben pozwoli³.}
{337} {} {Spójrz... Zaminowaliœmy zewnêtrzne mury na ca³ym obwodzie z wyj¹tkiem bramy i muru w pobli¿u zbiornika paliwa. Szczególnie niebezpiecznie jest przy zachodniej stronie. Skorpiony lubi¹ czasem tam wpaœæ i siê trochê rozerwaæ, dlatego lepiej uwa¿nie obserwuj swoje kroki.}
{338} {} {Swietnie, to mi bardzo pomo¿e.}