{100} {} {Widzisz przestêpcê.}
{101} {} {Widzisz przestêpcê. Wpad³ w rêce wymiaru sprawiedliwoœci.}
{102} {} {S-su-uka...}
{103} {} {* Khe-khe *}
{104} {} {Do zobaczenia w bazie. Jeœli prze¿yjemy.}

{200} {} {(przed sob¹ widzisz siedz¹cego na pod³odze pó³nagiego faceta; jego cia³o wymownie pokazuje siniaki) Czego chcesz? Ju¿ ci wszystko powiedzia³em.}

{210} {} {Czego chcesz?}
{211} {} {Ja tu zadajê pytania.}
{212} {} {To pytaj. Ale nadal Ci nie odpowiem.}
{213} {} {Ben mnie przys³a³. Chcê ci pomóc.}
{214} {} {Wiêc mnie ocal, poka¿ ile jesteœ wart. A mo¿e Ben wcale ciê nie przys³a³?}
{215} {} {Z przyjemnoœci¹ ciê tak zostawiê.}
{216} {} {Serio zostawisz mnie w takim stanie?}

{220} {} {Dlaczego jesteœ zamkniêty?}
{221} {} {Poniewa¿ jestem niebezpieczny, wiesz? Burmistrz chce siê czegoœ dowiedzieæ, ale pyta niew³aœciw¹ osobê.}
{222} {} {Czego burmistrz chce od ciebie?}
{223} {} {Wszystkiego, co wiem o jakimœ Benie i jego bazie. Nawet nie mam pojêcia, kto to jest.}
{224} {} {Jak zosta³eœ schwytany?}
{225} {} {Ch³opskie suki zobaczy³y mnie, gdy zbli¿a³em siê do miasta. Myœleli, ¿e jestem bandyt¹ i powiedzieli o tym burmistrzowi.}
{226} {} {Jakieœ pomys³y, jak ciê st¹d wydostaæ?}
{227} {} {Mo¿e mo¿esz przekonaæ burmistrza, ¿e wypad³em z interesu? Jeœli nie, to daj mi broñ, a po prostu sam st¹d wyjdê.}
{228} {} {Mam z³e wieœci, œmieciu. Ben powiedzia³, ¿eby ciê wykoñczyæ, jeœli nie ma innego wyjœcia.}
{229} {} {(pokazuje œrodkowy palec) Pieprz siê.}
{1229} {} {(pokazuje œrodkowy palec) Pieprz siê.}
{230} {} {Teraz na pewno nie mo¿esz siê st¹d wydostaæ.}
{231} {} {Ale mo¿esz pomyœleæ.}
{232} {} {Bêdziemy musieli walczyæ po swojemu. Nadal nie masz innego wyboru. ChodŸmy.}
{233} {} {Ok, rozwalmy tê dziurê. Ale daj spokój, bez heroizmu. Muszê tylko wydostaæ siê z miasta, w bezpieczne miejsce.}
{234} {} {ChodŸmy.}
{235} {} {Zostañ tutaj, sprawdzê teren.}

{250} {} {Jesteœ wolny. Burmistrz podpisa³ twoje zwolnienie.}
{251} {} {Tak po prostu? Pos³uchaj, potrzebujê eskorty albo ch³opi sami mnie rozerw¹.}
{252} {} {Ok, chodŸmy.}
{253} {} {Pójdê dalej sam. Samemu ³atwiej bêdzie mi zatrzeæ œlady.}
{254} {} {Jak sobie ¿yczysz. Nawiasem mówi¹c, Ben powiedzia³, ¿e jeœli ci siê nie uda, bêdziesz musia³ zostaæ zlikwidowany.}
{255} {} {(prze³yka œlinê) Gdyby nie Ben i jego zemsta, nie skoñczy³bym w tym wiêzieniu. Wys³a³ mnie, abym znalaz³ s³aby punkt w obronie miasta. Ale tutaj wszyscy siê znaj¹. Dlatego od razu znalaz³em siê w szponach ch³opów. Ech. Teraz muszê wróciæ do Bena z niczym.}
{256} {} {Myœlisz, ¿e bêdzie wkurzony?}
{257} {} {Tak. Ale jeœli nie wrócê, og³osi mnie zdrajc¹. A to jeszcze gorsze.}
{258} {} {Jestes chocia¿ w jednym kawa³ku. Powodzenia.}
{259} {} {Mo¿e wyka¿e siê zrozumieniem. Bywaj.}
{260} {} {Musimy wyjechaæ z miasta, zanim zostaniemy nadziani na wid³y.}
{261} {} {Dobrze. ChodŸmy.}
{262} {} {Wygl¹da na to, ¿e siê uda. Ju¿ myœla³em, ¿e bêdê musia³ ciê powaliæ i biec tak szybko, jak tylko potrafiê. Na pewno jesteœ od Bena? Nie widzia³em ciê wczeœniej.}
{263} {} {Tak, jestem w gangu od niedawna. Dlatego wys³a³ mnie, abym ciê odnalaz³.}