{100} {} {Widzisz wojownika szos.}
{101} {} {Widzisz jednego ze z³odziei.}
{102} {} {Bandyta nie chce negocjowaæ.}

{110} {} {Hej, jak tam biznes?}
{111} {} {Powodzenia na szlaku.}
{112} {} {Jesteœ fajniejszy ni¿ myœleliœmy.}
{113} {} {Nie mogê uwierzyæ, ¿e teraz tropimy obroñców.}
{114} {} {Szlaki s¹ teraz pod nasz¹ kontrol¹.}
{115} {} {Przynosisz nam szczêœcie.}
{116} {} {Ben ci ufa.}

{120} {} {Nie gap siê na mnie, bo po¿a³ujesz.}
{121} {} {Czego chcesz, œmieciu?}
{122} {} {* Pluje w ty³ *}
{123} {} {Mimo ¿e Ben ciê wpuœci³, nie jesteœ jeszcze cz³onkiem gangu.}
{124} {} {Nudzê siê. Zabaw mnie.}
{125} {} {Sporo ryzykujesz bêd¹c tu.}
{126} {} {Nie próbuj przekraczaæ naszej œcie¿ki.}

{130} {} {Kim ty kurwa jesteœ? Jednym z Blacharzy?}
{131} {} {Ty tam, b¹dŸ cicho.}
{132} {} {Przyda³a by mi siê zbroja taka jak twoja.}

{199} {} {}
{200} {} {Na co siê gapisz, kowboju?}
{201} {} {Na ciebie suko.}
{202} {} {Nie nazywaj mnie tak.}
{203} {} {Przyzwyczaj siê, suko.}
{204} {} {Uwa¿aj na jêzyk, œmieciu, inaczej...}
{205} {} {W przeciwnym razie co? Ooh, zdenerwujesz siê?}
{206} {} {Ok, jeszcze jedno s³owo i...}
{207} {} {Co zamierzasz zrobiæ, kochanie? Mam tu d³oñ. D³oñ, któr¹ ciê uderzê...}
{208} {} {Chcesz mnie, œmieciu?}
{209} {} {Chcesz, co?}
{210} {} {* Uff *}
{211} {} {Nie, w porz¹dku... Przepraszam, Ÿle zrozumia³em...}
{212} {} {Powiedz mi teraz i tutaj.}
{213} {} {. ... .}
