{100} {} {Widzisz Chucka.}
{101} {} {Widzisz jednego ze z³odziei.}
{102} {} {Hej, czeœæ, jak siê masz?}

{200} {} {Hej, czeœæ. Mam na imiê Chuck. Nie widzia³em ciê tu wczeœniej. Kim jesteœ?}
{201} {} {Nie musisz znaæ mojego imienia.}
{202} {} {Powa¿nie? Okej, cokolwiek powiesz. Chocia¿ nie rozumiem, dlaczego robisz tego tak¹ tajemnicê.}
{203} {} {Twoja ¿yczliwoœæ nie pasuje do ducha gangu. Musisz byæ tu od niedawna, prawda?}
{204} {} {Cholera, prawda. Jestem nowicjuszem. Nadal jest wiele rzeczy, których nie wiem, nawet nie przeszed³em inicjacji.}
{205} {} {Inicjacji?}
{206} {} {Jestem }
{207} {} { i jestem tu od niedawna.}
{208} {} {Och, ty te¿ jesteœ nowy? Wreszcie nie jestem tu jedyny. Mi³o ciê poznaæ. Zda³eœ ju¿ inicjacjê?}
{1208} {} {Och, ty te¿ jesteœ nowa? Wreszcie nie jestem tu jedyny. Mi³o ciê poznaæ. Zda³aœ ju¿ inicjacjê?}
{209} {} {Inicjacjê?}
{210} {} {Och, czeœæ. Ech, trenujê tutaj... Chcê byæ silniejszy i wytrzymalszy.}
{211} {} {Jeœli chcesz zaj¹æ moje miejsce z Benem, spóŸniasz siê.}
{212} {} {Nie, kim jesteœ, jestem daleko od ciebie. Dlatego ciê¿ko trenujê przed inicjacj¹.}
{213} {} {Inicjacj¹?}
{214} {} {Muszê przejœæ ceremoniê inicjacji, aby udowodniæ ¿e nadajê siê do gangu. Wszyscy tu mówi¹, ¿e pobij¹ mnie w t³umie i zobacz¹, jak to zniosê. I wygl¹da na to, ¿e na tym siê nie skoñczy.}
{215} {} {Nie przeszkadza Ci to?}
{216} {} {Oczywiœcie ¿e tak. Nie jestem pewien, czy mam wystarczaj¹co du¿o si³y i wytrzyma³oœci. Mog¹ mnie nawet zabiæ.}
{217} {} {W takim razie dlaczego nadal siê przygotowujesz?}
{218} {} {Nie mam wyboru. Nie wiem, dok¹d jeszcze mogê siê udaæ po tym, jak burmistrz Casa Grande zabi³ po³owê tamtejszej populacji, mnie uzna³ za zdrajcê i nawet wystawi³ nagrodê za schwytanie. Ben jest jedyn¹ osob¹, która poda³a mi rêkê.}
{219} {} {Có¿, powodzenia w æwiczeniach.}

{220} {} {Hej, czeœæ.}
{221} {} {Do widzenia.}
{222} {} {Mogê ci pomóc w teœcie.}
{223} {} {Naprawdê? W jaki sposób?}
{224} {} {Mówi¹, ¿e przedwojenna chemia mo¿e z³agodziæ ból.}
{225} {} {Tak, myœla³em o tym. Psycho podobno uodparnia na ból dziêki czemu bez problemu móg³bym przejœæ test. Ale to bardzo drogi i rzadki lek. Mo¿esz go dla mnie zdobyæ?}
{226} {} {Tak, ale potrzebujê na to czasu.}
{227} {} {Swietnie. Poczekam.}
{228} {} {Do widzenia.}
{229} {} {Nie, przepraszam, nie mam czasu.}
{230} {} {Przepraszam. W³aœciwie psycho mo¿na kupiæ w Phoenix. Droga jest dla mnie zamkniêta, poniewa¿ miejscowi ³owcy maj¹ nakaz, by mnie schwytaæ.}
{231} {} {Rozumiem. Jeœli znajdê psycho, przyniosê Ci. Czeœæ.}
{232} {} {Nie nale¿ysz jeszcze do gangu. Mogê uwolniæ ciê od piêtna przestêpcy.}
{233} {} {Czy myœla³eœ o pozbyciu siê piêtna przestêpcy? Z pewnoœci¹ mo¿na Ciê uwolniæ od ³owców nagród.}
{234} {} {Cholera, by³bym bardzo za to wdziêczny. Kontrakt na moje schwytanie jest przechowywany w Phoenix i wystawiony przez burmistrza Casa Grande.}
{235} {} {Jednak to dla mnie zbyt trudne. Latwiej bêdzie ci znaleŸæ jakiœ lek na ból.}
{236} {} {Czy myœla³eœ o pozbyciu siê piêtna przestêpcy i powrocie do normalnego ¿ycia w mieœcie?}
{237} {} {Mam dla ciebie psycho.}
{1237} {} {Mam dla ciebie psycho.}
{238} {} {To powinno wystarczyæ na ca³¹ ceremoniê. Dziêkujê przyjacielu, co ja bym bez ciebie zrobi³.}
{1238} {} {To powinno wystarczyæ na ca³¹ ceremoniê. Dziêkujê przyjacielu, co ja bym bez ciebie zrobi³.}
{239} {} {Tylko quid pro quo. Pamiêtaj, kim jest twój prawdziwy amigo.}
{240} {} {Wszystkie nagrody za Ciebie s¹ ju¿ niewa¿ne. Jesteœ wolny.}
{241} {} {Naprawdê? Wiêc teraz mogê pojechaæ do miasta i kontynuowaæ ¿ycie normalnej osoby?}
{242} {} {Zegnaj Chuck.}
{243} {} {Nie zadawaj siê ju¿ z w¹tpliwymi typami, kolego.}
{244} {} {Pomyœlê o tym, co mogê zrobiæ. Bywaj.}
{245} {} {Dlaczego wci¹¿ siê przygotowujesz, jeœli mo¿esz umrzeæ?}
{246} {} {Burmistrz Bustos nie ¿yje, co oznacza, ¿e jego kontrakt z ³owcami nagród jest nieaktualny.}
{247} {} {Naprawdê? Wow. Nie wiedzia³em. Czyli mogê teraz wróciæ do miasta i kontynuowaæ ¿ycie normalnej osoby?}
{248} {} {Jak id¹ przygotowania do inicjacji?}
{249} {} {Nie wiem, co mnie czeka. Ale mówi¹, ¿e ca³y t³um bêdzie mnie bi³, aby sprawdziæ moj¹ wytrzyma³oœæ. I to mnie przera¿a. A jeœli tego nie zniosê?}
{250} {} {Rozumiem.}
{251} {} {Opowiedz swoj¹ historiê.}
{252} {} {Mieszka³em z rodzicami w Casa Grande. Nale¿eli do klanu, który by³ w³aœcicielem stacji wodnej. Ale wtedy burmistrz Bustos przej¹³ w³adzê w mieœcie. Zabra³ stacjê i zabi³ wszystkich, którzy mu przeszkadzali.}
{253} {} {Jak prze¿y³eœ?}
{254} {} {Uciek³em z miasta w sam¹ porê, a potem dowiedzia³em siê, ¿e jestem œcigany pod jakimœ wymyœlonym pretekstem. Du¿o wêdrowa³em i by³em ju¿ kompletnie zdesperowany, ¿eby znaleŸæ sobie nowy dom. Na szczêœcie trafi³em na Bena, a ten przyj¹³ mnie do gangu.}
{255} {} {Smutna historia.}
{256} {} {Bior¹c pod uwagê okolicznoœci, ka¿da historia wydaje siê tutaj w¹tpliwa.}
{257} {} {Dok³adnie, Chuck.}
{258} {} {Dziêki! Masz, weŸ ten œrodek pobudzaj¹cy. Myœla³em, ¿e u¿yjê go podczas ceremonii, ale ju¿ go nie potrzebujê. (rozgl¹da siê i zni¿a g³os) Najwa¿niejsze, ¿e wszystko siê dobrze skoñczy³o.}
