{100} {} {Widzisz rabusia.}
{101} {} {Widzisz z³odzieja z autostrady. Zosta³ ranny w ramiê.}
{102} {} {Widzisz z³odzieja z autostrady. Wygl¹da o wiele lepiej od waszego ostatniego spotkania.}
{103} {} {By³bym martwy, gdyby nie ty, doktorze.}
{104} {} {S-suki z karawany postrzeli³y mnie w ramiê podczas nalotu... Jak to boli!}
{105} {} {Zosta³em postrzelony w ramiê podczas nalotu na karawanê. Ale i tak zabraliœmy wszystko, co mieli.}
{106} {} {Czy to naprawdê lekarstwo, doktorze? Coœ mi siê tylko pogarsza...}
{107} {} {Ups! By³ na zaawansowanym etapie...}
{108} {} {Kto ciê wpuœci³?}

{200} {} {By³bym martwy, gdyby nie ty, doktorze.}
{201} {} {Nie ma za co.}

{210} {} {Jak mogê pomóc, doktorze?}
{211} {} {Do widzenia.}

{220} {} {Powiedz mi, jak zosta³eœ zraniony?}
{221} {} {Zosta³em postrzelony w ramiê podczas nalotu na karawanê. Ale nadal zabraliœmy wszystko, co mieli. Ha!}
{222} {} {Jak do³¹czy³eœ do Niebieskich Tarczy?}
{223} {} {Nie mia³em dok¹d pójœæ, wiêc zdecydowa³em siê do³¹aczyæ do Bena, tak po prostu. Nie by³o ³atwo. Musia³em przejœæ przez trudn¹ ceremoniê inicjacji, wci¹¿ mam po niej blizny. Ale udowodni³em, ¿e pasujê do Niebieskich Tarczy. Dzieñ, z którego bêdê dumny przez ca³e ¿ycie.}
{224} {} {Co robisz w gangu?}
{225} {} {Có¿, cokolwiek powie Ben lub Ryo. Ostatnio by³em odpowiedzialny za dystrybucjê paliwa przed wyjœciami. Ben jest bardzo uczulony na punkcie naszych zapasów, wiêc stara siê kontrolowaæ ich zu¿ycie.}
{226} {} {Mo¿esz sprzedaæ mi litr lub dwa?}
{227} {} {Po moim uzdrowieniu? Pewnie! Zrobiê dla ciebie bomby lub zapas paliwa, ale nie nieograniczon¹ iloœæ, rozumiesz.}
{228} {} {Super.}
