{100} {} {Widzisz Rio.}
{101} {} {Widzisz jednego ze z³odziei.}
{102} {} {No có¿, mamy tu kretoszczura.}
{103} {} {Niez³a zbroja. Brakuje ci jednak najwa¿niejszej rzeczy - szybkoœci.}
{104} {} {Rel:}
{105} {} {+ 20}
{106} {} {- 20}
{107} {} {exit}

# Otrzymal tytu³ Warrior of the Road
{200} {} {(zaciska zêby, patrz¹c ci prosto w oczy niczym bestia) Wiêc teraz muszê siê ruszyæ. Robi siê trochê t³oczno wokó³ Bena, co?}
{201} {} {Tak, Ben i ja jesteœmy teraz w doskona³ych stosunkach...}
{202} {} {Jasne, dlatego zapamiêtaj, * ja * jestem tu pierwszy po Benie. Nie próbuj nawet na mnie krzywo spojrzeæ.}
{203} {} {Ok.}
{204} {} {}
{205} {} {(pokazuje uœmiech z jednej strony twarzy) Spójrzcie, kogo my tu mamy. To nowy ulubieniec Bena.}
{206} {} {Jesteœ zazdrosny, co? Co czujesz musz¹c usun¹æ siê  w bok?}
{207} {} {Co jest, suko, zamierzasz zaj¹æ moje miejsce? W takim razie pamiêtaj - NIKT nie zajmie mojego miejsca w pobli¿u Bena. Od dawna jesteœmy znajomymi, on mi ufa. A ty? Nikt tutaj ciê w ogóle nie zna.}
{208} {} {Nie denerwuj siê, Rio, nie zamierzam zajmowaæ twojego miejsca.}
{209} {} {PRAWIDLOWA odpowiedŸ, suko. Znaj swoje miejsce. Ben i ja znamy siê od dawna, ufa mi. A ty kim jesteœ? Widzia³em ciê tylko kilka razy.}
{210} {} {Powinieneœ uwa¿aæ na jêzyk.}
{211} {} {Ach, wiêc miejsce obok Bena nadal daje ci poczucie wy¿szoœci. Nie myœl, ¿e staniesz mi na œcie¿ce, padlino.}
{212} {} {Ok.}
{213} {} {Spokojnie, stary. Jesteœmy w tym samym gangu.}
{214} {} {Dok³adnie. Nie myœl o stawaniu mi na drodze.}
{215} {} {Ok.}

# Znajomosc
{220} {} {Co ty tu do cholery robisz, œmieciu?}
{221} {} {Tylko siê rozgl¹dam. I ty kim jesteœ?}
{222} {} {Chcê ciê poznaæ. Jestem tu nowy.}
{223} {} {Poznaæ mnie, co? Poznaæ, suko? Myœlisz, ¿e jestem prostytutk¹ do *poznania*? Na pustkowiu spotkasz zw³oki, a my mamy gang. Nie lubiê gadaæ bez powodu. Zrozum to.}
{224} {} {Gówniane maniery, brachu.}
{225} {} {Tak, zgadza siê, brachu. Widzê, ¿e zaczynasz siê czegoœ uczyæ. Mo¿e znów bêdziemy mogli razem pracowaæ.}
{226} {} {Swietnie, to pierwszy kontakt mamy ju¿ za sob¹.}
{227} {} {To nie jest dobry pocz¹tek.}
{228} {} {W takim razie wbij sobie swoje maniery w dupê i wypierdalaj, suko.}
{229} {} {Wow, spokojnie. Chcê tylko z tob¹ porozmawiaæ.}
{230} {} {Szukam kogoœ, z kim móg³bym poradziæ sobie w tej dziurze. I wygl¹da na to, ¿e moje poszukiwania dobiegaj¹ koñca.}
{231} {} {Ok, widzê, ¿e nie jesteœ a¿ tak¹ pierdo³¹. Ale nie licz na zaufanie tylko dlatego, ¿e Ben pozwala ci chodziæ po bazie. Poka¿ siê w akcji, a potem porozmawiamy.}
{232} {} {Ok. Kim jesteœ?}
{233} {} {Mam na imiê Rio, kochanie. I na tym koñczy siê nasza znajomoœæ, dopóki nie poka¿esz siê w akcji.}
{234} {} {Bêdziesz musia³ odpowiedzieæ na pytania.}
{235} {} {Ok.}

# Powtarzajacy siê dialog
{250} {} {Czego chcesz?}
{251} {} {Czego chcesz, padlino?}
{252} {} {Jak siê masz?}
{253} {} {Do widzenia Ryo.}

{260} {} {Ciekawe, jak ktoœ taki jak ty znalaz³ siê w gangu.}
{261} {} {To by³y czasy. Musia³em b³¹kaæ siê po szlakach z ró¿nymi gangami, a¿ trafi³em tutaj.}
{262} {} {Co, wyrzucili Ciê ze wszystkich normalnych miast?}
{263} {} {Coœ sugerujesz, suko? Myœlisz, ¿e gang tak po prostu siê pojawi³? Wszyscy jesteœmy ofiarami okolicznoœci, zrozum to.}
{264} {} {Tak, oczywiœcie, to brzmi o wiele lepiej.}
{265} {} {Co zrobi³eœ?}
{266} {} {Czy naprawdê jest tak Ÿle w miastach?}
{267} {} {Gang pojawi³ siê nie bez powodu. Wszyscy jesteœmy ofiarami okolicznoœci, wiesz?}
{268} {} {Rozumiem. Mnie te¿ zmuszono do opuszczenia domu.}
{269} {} {Dobrze. Tutaj wszyscy zostali wypêdzeni ze swoich domów.}
{270} {} {Wygl¹da na to, ¿e wszyscy tutaj s¹ sk³onni winiæ zewnêtrzne okolicznoœci za swoje problemy.}
{271} {} {Jaka jest twoja historia?}
{272} {} {W Phoenix gra³em w z³ej dru¿ynie, kiedy Aaron przej¹³ kontrolê. Musia³em wiêc uciec do Casa Grande, uciekaj¹c przed nimi.}
{273} {} {Tam te¿ nie podoba³y Ci siê lokalne w³adze?}
{274} {} {Co siê sta³o w Casa Grande?}
{275} {} {Aaron jest tyranem. Post¹pi³eœ s³usznie, uciekaj¹c z tego piek³a.}
{276} {} {W Casa Grande zosta³a naprawiona pompa wodna. Po czym wokó³ niej zaczê³y siê wojny klanów. Zgadnij, kto tym razem wygra³.}
{277} {} {Jesteœ urodzonym pechowcem.}
{278} {} {Znowu pech?}
{279} {} {Mam nadziejê, ¿e tych tyranów czeka okrutna kara.}
{280} {} {Ale gang Bena jest inny. Tutaj ka¿dy jest nasz, ka¿dy dostaje to, na co zas³u¿y³... Ale po co, do diab³a, ja z tob¹ o tym rozmawiam? Ta paplanina zaczyna mnie nudziæ. Spierdalaj, muszê zadbaæ o mój ulubiony sprzêt.}
{281} {} {Nie, dopóki nie dowiem siê wiêcej.}
{282} {} {Bardzo chêtnie. Czeœæ.}

{290} {} {Co robisz w gangu?}
{291} {} {Jestem drug¹ osob¹ w Niebieskich Tarczach. Oczywiœcie zaraz po Benie. Gdy go nie ma, to ja tu rz¹dzê - utrzymujê porz¹dek, rozdzielam racje ¿ywnoœciowe, uczê m³ode zwierzêta fachu, sprawiam, ¿e leniwe suki pracuj¹. }
{292} {} {[Dalej.]}
{293} {} {A kiedy Ben wraca, robiê wszystko, ¿eby poczu³ siê jak w domu - alkohol, dziewczyny, spluwy.}
{294} {} {Rozumiem.}
{295} {} {Czego mo¿esz mnie nauczyæ?}
{296} {} {Szkolisz innych? Ciekawe, powiedz mi wiêcej.}
{297} {} {Musimy byæ w formie. Uczê pos³ugiwania siê broni¹, prowadzenia walk i rytua³ów inicjacyjnych. Szczególnie wa¿ne jest dla nas obchodzenie siê z bombami zapalaj¹cymi i broni¹ bia³¹.}
{298} {} {Chcia³bym siê nauczyæ rzucaæ tymi bombami.}
{299} {} {Nie jestem tym zainteresowany.}
{300} {} {Uczyæ ciê? Powiem ci tak jak jest - nie lubiê ciê.}
{301} {} {Ok, wrócimy do tego póŸniej.}
{302} {} {WyobraŸ sobie - ja ciebie te¿.}
{303} {} {Có¿, jesteœ tu od niedawna. Jeœli wiêc chcesz siê uczyæ, przynieœ mi coœ wartoœciowego.}
{304} {} {Ok. Ale bêdziesz musia³ poczekaæ.}
{305} {} {Nie, nie. Myœla³em, ¿e gang powinien sobie pomagaæ.}
{306} {} {Ale ja ju¿ jestem w gangu. Dlaczego nie?}
{307} {} {Zap³aæ albo odpieprz siê.}
{308} {} {Ok...}
{309} {} {No dalej, brachu. Czy nie zas³ugujê na szacunek?}
{310} {} {Cholera.. Okay, przygotuj siê na walkê, bêdê dzisiaj wyj¹tkowo mi³y.}
{311} {} {Ok, zacznijmy zabawê...}
{312} {} {Nie teraz, muszê najpierw coœ zrobiæ.}
{313} {} {Mam 250 kapsli. Czy to wystarczy?}
{314} {} {Jasne. IdŸ, przygotuj siê do walki.}
{315} {} {Ok, zacznijmy zabawê...}
{316} {} {Czy mo¿esz mnie nauczyæ, jak walczyæ na no¿e?}

{320} {} {O tym motorze.}
{321} {} {Dla Bena to nie tylko zabawka, to czêœæ jego ¿ycia. Upewniam siê, ¿e niczego nie potrzebuje. Naprawiam motor, szukam alkoholu, szukam kobiet - robiê wszystko, czego Ben potrzebuje.}
{322} {} {Swietnie. Dobrze wiedzieæ.}
{323} {} {Wow, serio jest sprawny i jeŸdzi?}
{324} {} {Oczywiœcie. Myœlisz, ¿e kim jestem? Gdyby Ben powiedzia³, ¿e mam mieæ oko na motor, z motorem bêdzie wszystko w porz¹dku.}
{325} {} {Czy jest na sprzeda¿?}
{326} {} {Masz urojenia. Ben ceni to cudo bardziej ni¿ kogokolwiek z gangu. Nigdy go nie odda.}
{327} {} {Ben po¿yczy³ mi swój motor. Daj mi kluczyki.}
{328} {} {Co ty robisz, suko? Dba³em o motocykl Bena jak o mój w³asny. Teraz przychodzisz i chcesz go zabraæ? Chcê wiedzieæ, jak, kurwa, do tego dosz³o, ¿e Ci na to pozwala.}
{329} {} {Przepraszam, nie chcê z tob¹ walczyæ. Zatrzymaj kluczyki dla siebie. W porz¹dku, brachu.}
{330} {} {Ok, za³atwmy to raz na zawsze. Tutaj i teraz.}
{331} {} {Tak. Teraz zatañczysz dla mnie na gor¹cym asfalcie.}
{332} {} {. ... .}
{333} {} {Zamknij siê i daj mi kluczyki.}
{334} {} {Och, teraz jesteœmy Ÿli? Suko to * ja * jestem tutaj wkurzony!}
{335} {} {Rozumiem twoje uczucia. Pozwól mi zap³aciæ 250 kapsli jako zadoœæuczynienie.}
{336} {} {Chcesz mnie przekupiæ? MNIE? Wezmê te kapsle. Ale kiedy nadejdzie odpowiednia chwila, wepchnê ci je do gard³a i sprawiê, ¿e bêdziesz strzela³ nimi dup¹ w opony. Suko, popamiêtasz ten dzieñ.}
{337} {} {Mo¿e. A teraz daj mi kluczyki.}
{338} {} {Zamknij siê i dawaj kluczyki.}
{339} {} {Uspokój siê, Rio. Ben nadal jest ci lojalny. I ja te¿.}

{340} {} {Ben po¿yczy³ mi swój motocykl. Daj mi kluczyki.}
{341} {} {Gdybym by³ kimœ innym, wykoñczy³bym go. Wiesz dlaczego?}
{342} {} {Tak, w jakiœ sposób...}
{343} {} {Dlaczego?}
{344} {} {Dba³em o motocykl Bena jak o mój w³asny. Zdmuchiwa³em ka¿dy py³, by go zadowoliæ. Myœlisz, ¿e podoba mi siê to, ¿e Ben myœli w ten sposób o mojej pracy?}
{345} {} {Czekaj...}
{346} {} {Do diab³a czemu on mi to robi? Po co! By³em mu wierny, spe³nia³em wszystkie jego zachcianki, a on tak po prostu da³ ci motor. Nie mogê w to uwierzyæ.}
{347} {} {Rio, nie b¹dŸ taki zazdrosny. Tylko po¿yczy³ mi motor, to wszystko.}
{348} {} {Zazdrosny? Ha! Jesteœ wê¿em o miêkkim ciele, widzê, ile jesteœ wart.}
{349} {} {Daj mi kluczyki.}
{350} {} {Zamknij siê i dawaj te cholerne kluczyki.}
{351} {} {Czas uœwiadomiæ sobie, Rio, ¿e nie jesteœ sam w gangu. Czasami musisz podzieliæ siê z innymi.}
{352} {} {To wszystko przez ciebie! Jesteœ jak w¹¿ zakradaj¹cy siê do ³ó¿ka. Wszystko uk³ada³o siê dobrze miêdzy mn¹ a Benem, kiedy ciê nie by³o.}
{353} {} {Lepiej porozmawiaj o tym z Benem. A teraz daj mi kluczyki.}
{354} {} {Zamknij siê i dawaj kluczyki.}
{355} {} {Oto kluczyki. Mam nadziejê, ¿e wyœwiadczysz mi przys³ugê i rozbijesz siê w pierwszym kanionie.}
{356} {} {Spokojnie, stary.}
{357} {} {Nie zastraszysz mnie.}

# Dostawa narkotyków
{400} {} {Powiedzia³eœ coœ o biznesie w Phoenix. Mo¿e móg³bym jakoœ pomóc?}
{401} {} {Mo¿e. Ale o co ci chodzi?}
{402} {} {Chcê pomóc gangowi. }
{403} {} {Wow. Chcesz siê wykazaæ przed wszystkimi, co? Jesteœ naprawdê przebieg³ym sukinsynem.}
{1403} {} {Wow. Chcesz siê wykazaæ przed wszystkimi, co? Jesteœ naprawdê przebieg³¹ suk¹.}
{404} {} {Chcê zmieniæ twoje pieprzone nastawienie do mnie.}
{405} {} {Masz w³aœciwe myœlenie. Mój szacunek mo¿na tylko OTRZYMAC.}
{406} {} {To tylko biznes. Przys³uga za przys³ugê.}
{407} {} {Wiêc tak wyobra¿asz sobie cz³onkostwo w Niebieskich Tarczach? Przynajmniej to sprawiedliwe.}
{408} {} {Wiêc jaki masz problem?}
{409} {} {Nasz kurier z Wielkiego Miasta gdzieœ zagin¹³. Musia³ dostaæ od kogoœ kulkê czy coœ. Dlatego teraz zamiast niego to Ty musisz zanieœæ paczkê do klienta.}
{410} {} {Co takiego wysy³asz do Phoenix?}
{411} {} {Wêglowodory, cholera? Mamy ich ca³y zbiornik. A rzemieœlnicy w Phoenix robi¹ z tego ró¿nego rodzaju bzdury i inne przydatne p³yny.}
{412} {} {Do kogo mam zanieœæ paczkê?}
{413} {} {Zwykle to handlarz w slumsach kupuje surowce. Nie zapomnij odebraæ od niego nadchodz¹cej paczki.}
{414} {} {Ok, wezmê paczkê.}
{415} {} {Uwielbiam wystêpy. Ale pamiêtaj - handlarz nie powinien zostaæ ranny.}
{416} {} {Rozumiem.}
{417} {} {Zartujesz. Nie do³¹czy³em do gangu, ¿eby nosiæ paczki. Poszukaj innego frajera.}
{1417} {} {Zartujesz. Nie do³¹czy³am do gangu, ¿eby nosiæ paczki. Poszukaj innego frajera.}

{420} {} {Mam twoje *leki*.}
{421} {} {Hmm, naprawdê dotrzymujesz s³owa. Prawdopodobnie powinienem by³ ciê lepiej traktowaæ.}
{422} {} {[Dalej.]}
{423} {} {Oto twoja wyp³ata i trochê narkotyków. Teraz masz prawo siê zrelaksowaæ.}
{424} {} {Zgadza siê.}
{425} {} {Twój dealer nie ¿yje. Wygl¹da na to, ¿e nie masz szczêœcia.}
{426} {} {Jak to siê sta³o?}
{427} {} {Nie mam pojêcia.}
{428} {} {Rozumiem. Kurwa, zabijê tego kto to zrobi³, jeœli go znajdê. Ok, no to tyle jeœli chodzi o robotê.}
{429} {} {Do widzenia Rio.}