{100} {} {Widzisz wiêŸnia.}
{101} {} {Wygl¹da na to, ¿e bandyci zmuszaj¹ tego cz³owieka do ciê¿kiej pracy.}
{102} {} {Jestem wolny? Naprawdê?!}

{110} {} {Z³apali mnie i zmusili do pracy.}
{111} {} {Czy ty te¿ jesteœ w gangu?}
{112} {} {Nie zniosê tego d³u¿ej, nie mam si³y.}
{113} {} {Kiedy zostawi¹ mnie w spokoju?}
{114} {} {Uratuj mnie, jesteœ lepszy od tych potworów.}

{120} {} {Z³apali mnie i zmusili do pracy.}
{121} {} {Czy ty te¿ jesteœ w gangu?}
{122} {} {Zabij mnie, nie mogê ju¿ tego znieœæ.}
{123} {} {Kiedy zostawisz mnie w spokoju?}
{124} {} {Lepiej mnie zabij.}

{200} {} {Czeœæ.}
{201} {} {Czeœæ.}

{210} {} {Czeœæ.}
{211} {} {Czeœæ.}
