{100} {} {Widzisz kobietê.}
{101} {} {Widzisz kobietê. A na jej twarzy wymizerowane kszta³ty, s¹ straszne.}
{102} {} {Pomyœl o tym jak o przys³udze, suko.}
{103} {} {Mam nadziejê, ¿e teraz odnajdziesz spokój.}

{110} {} {Proszê, zabij mnie!}
{111} {} {Nie mogê ¿yæ po tym, co mi zrobili.}
{112} {} {Maltretowali mnie.}
{113} {} {Nie zniosê tego d³u¿ej.}
{114} {} {Musisz mnie zabiæ.}
{115} {} {Chcê tylko znaleŸæ spokój.}

{120} {} {Nie mogê uwierzyæ, ¿e wszyscy nie ¿yj¹! Dziêkujê Ci.}
