{100} {} {Widzisz przed sob¹ bramê.}

{110} {} {Brama jest zamkniêta od wewn¹trz.}
{111} {} {Brama jest zamkniêta.}
{112} {} {Usuwasz ciê¿ki rygiel z bramy. Wyjœcie jest teraz mo¿liwe.}
{113} {} {Brama jest zamkniêta od wewn¹trz. Nie mo¿na jej st¹d otworzyæ.}
{114} {} {Zasuwa z tej bramy zosta³a ju¿ usuniêta.}
{115} {} {Zasuwa zosta³a w³o¿ona z powrotem na miejsce. Brama jest ponownie zamkniêta.}
{116} {} {Ta brama bêdzie musia³a zostaæ najpierw zamkniêta.}
{117} {} {Zasuwê mo¿na zamkn¹æ tylko od wewn¹trz.}
{118} {} {Tu nie ma zamka. Ta brama jest zaryglowana.}
{119} {} {Ta brama jest zbyt mocna, aby j¹ otworzyæ w ten sposób.}
