{102} {} {Ten biedak zosta³ przywi¹zany do tego miejsca, aby wszyscy mogli go tu widzieæ. Z upa³u wariuje i mówi do siebie.}
{103} {} {Osoby nie mo¿na naprawiæ. Niestety.}

{200} {} {Hej, wody! Proszê, daj mi trochê wody!}
{201} {} {[przejdŸ obojêtnie]}
{202} {} {[napluj na ziemie] Oto trochê wody dla ciebie.}
{203} {} {Mercy, senor! Umieram z pragnienia!}
{1203} {} {Mercy, senora! Umieram z pragnienia!}
{204} {} {Powinieneœ by³ o tym pomyœleæ, zanim przywi¹zali ciê do s³upa. Do widzenia.}
{205} {} {Ok, przyniosê ci trochê wody.}
{206} {} {O mój Bo¿e, oczywiœcie przyniosê ci zaraz trochê wody.}

{210} {} {Urp, urp, ah, woda! Nigdy nie by³em tak zadowolony ze zwyk³ej wody. Dziêkujê, senor, ratujesz mnie przed œmierci¹.}
{1210} {} {Urp, urp, ah, woda! Nigdy nie by³em tak zadowolony ze zwyk³ej wody. Dziêkujê, senora, ratujesz mnie przed œmierci¹.}
{211} {} {Powiedz mi, dlaczego zosta³eœ przywi¹zany do s³upa?}
{212} {} {Kim jest wariat, który ciê zwi¹za³ i zostawi³ na tym s³oñcu?}
{213} {} {To by³ Frank. Karze ka¿dego, kto jest winny ka¿dej nawet ma³ej rzeczy.}
{214} {} {Co zrobi³eœ Ÿle?}
{215} {} {Czy ta kara nie jest zbyt ciê¿ka za twoje wykroczenie?}
{216} {} {Có¿, ja tylko poszed³em na tequile... i wda³em siê w awanturê. Przyznajê, ¿e to moja wina. I usz³oby mi to na sucho, gdybym nie wrzeszcza³ na samego Franka. To by³ b³¹d.}
{217} {} {A jednak Frank mia³ powód. Dobrze, ¿e to przyznajesz.}
{218} {} {Frank nie mo¿e tak robiæ. Nie zrobi³eœ nic z³ego.}
{219} {} {Zrozumia³em, ¿e siê myli³em. To siê wiêcej nie powtórzy. Gdyby tylko inni mi wybaczyli... Ach, pêka mi g³owa...}
{220} {} {Czy chcesz, ¿ebym Ciê rozwi¹za³?}
{221} {} {Ok, siedŸ tam.}
{222} {} {Nie, senor. Dziêki, ale Frankowi siê to nie spodoba. I znowu mnie zwi¹¿e na ca³y dzieñ. Albo nawet dwa. Nie ma potrzeby go prowokowaæ, senor. Zycie tu jest proste - albo przestrzegasz zasad, albo jesteœ zniewolony si³¹. Poczu³em to ju¿ na w³asnej skórze i wiêcej nie pope³niê tego b³êdu.}
{1222} {} {Nie, senora. Dziêki, ale Frankowi siê to nie spodoba. I znowu mnie zwi¹¿e na ca³y dzieñ. Albo nawet dwa. Nie ma potrzeby go prowokowaæ, senora. Zycie tu jest proste - albo przestrzegasz zasad, albo jesteœ zniewolony si³¹. Poczu³em to ju¿ na w³asnej skórze i wiêcej nie pope³niê tego b³êdu.}
{223} {} {Kim jest ten Frank?}
{224} {} {To jest nasz komendant. Byæ mo¿e to nawet najwa¿niejsza osoba w mieœcie. Jest w budynku niedaleko g³ównej bramy.}

{230} {} {Dziêkujê, senor, ratujesz mnie przed œmierci¹.}
{1230} {} {Dziêkujê, senora, ratujesz mnie przed œmierci¹.}
{231} {} {Bywaj.}
{232} {} {Mogê ciê rozwi¹zaæ.}
