{100} {} {Widzisz Alexandrê.}
{101} {} {Widzisz uœmiechniêt¹ dziewczynê. Wygl¹da na to, ¿e nadal nie do koñca rozumie, co siê dzieje.}
{102} {} {Przepraszam, nie mo¿esz tu przebywaæ z broni¹.}
{103} {} {Przepraszam, nie mo¿esz tu przebywaæ w tej zbroi.}
{104} {} {Ja... uhh... chcê spaæ. PrzyjdŸ rano...}

{200} {} {O, czeœæ! Widzê ciê tu pierwszy raz.}
{201} {} {Jestem }
{202} {} {. Jak masz na imiê?}
{203} {} {Ja ciebie te¿. Kim jesteœ?}
{204} {} {Alexandra Titova. Jestem asystentk¹ Nestora. Mi³o ciê poznaæ.}
{205} {} {Masz nietypowe nazwisko.}
{206} {} {Co to za œmieszne imiê?}
{207} {} {Moi przodkowie pochodzili z innej czêœci œwiata. Ale teraz to nie ma znaczenia. Nazwa jest tylko ho³dem dla pamiêci.}
{208} {} {Rozumiem.}
{209} {} {Myœlê, ¿e to ho³d dla szaleñstwa.}

{220} {} {Czy mogê w czymœ pomóc?}
{221} {} {Nie potrzebujê teraz ¿adnej pomocy. Do zobaczenia.}
{222} {} {Co siê dzieje? Dlaczego na placu jest tak wielu ludzi?}
{223} {} {Mieszkañcy s¹ poruszeni eksplozj¹ w Puerto. Nie wiemy jak teraz przetrwamy bez Bractwa Stali. Mam wielk¹ nadziejê, ¿e nie rozpocznie siê tu ¿adna rewolucja i wkrótce wszyscy siê uspokoj¹.}
{224} {} {Oto jest...}
{225} {} {Potrzebujê lekarstwa.}

{230} {} {Opowiedz mi o Nestorze.}
{231} {} {Có¿, jest on jedynym prawdziwym lekarzem w mieœcie. Jest te¿ nudny, ale fajny.}
{232} {} {A co z tob¹?}
{233} {} {W³aœnie siê od niego uczê. Daleko mi jeszcze do bycia lekarzem. Ale potrafiê ju¿ zaszyæ ranê... tak myœlê.}
{234} {} {Rozumiem.}
{235} {} {Co to za miejsce?}
{236} {} {Ambulatorium Apokalipsy w Saint Diego.}
{237} {} {Teraz rozumiem, dlaczego tak brzydko tu pachnie.}
{238} {} {Wow, prawdziwy szpital! Czy mogê tu leczyæ rany?}
{239} {} {Leczymy wszystkich w potrzebie, przeprowadzamy eksperymenty i produkujemy leki. Tak, przez to wszystko, czasami brzydko tu pachnie. Ale szybko siê do tego przyzwyczaisz.}
{240} {} {Czy mogê dostaæ tutaj trochê zapasów medycznych? Przyda³oby mi siê trochê antidotum na jak radskorpionów.}
{241} {} {Oczywiœcie. Po prostu powiedz mi, czego potrzebujesz. Mamy jednak nadziejê, ¿e w zamian masz coœ po¿ytecznego dla naszego szpitala.}
{242} {} {Swietnie. Bêdê pamiêtaæ.}
{243} {} {Hej, wróci³eœ! Wiesz, mamy tu teraz trudne czasy.}
{1243} {} {Hej, wróci³aœ! Wiesz, mamy tu teraz trudne czasy.}
{244} {} {Co masz na myœli?}
{245} {} {WyobraŸ sobie, ¿e fort Bractwa Stali eksplodowa³! Mówi¹, ¿e eksplozja by³a jak bomba atomowa. Có¿, bez nich handel w Casa Nueva spada. A na ochrone bêdzie trzeba wydaæ du¿o kapsli...}
{246} {} {I?}
{247} {} {W ka¿dym razie pamiêtaj, ¿e ceny wzros³y. W tym us³ugi naszej kliniki.}
{248} {} {Rozumiem. Bêdê o tym pamietaæ.}

{250} {} {Hej, czy jest coœ silniejszego ni¿ banda¿e i drobne u¿ywki?}
{251} {} {Na przyk³ad co?}
{252} {} {Nie, nic, zapomnij.}
{253} {} {Wiesz, przedwojenna medycyna by³a wyraŸnie lepsza ni¿ obecna.}
{254} {} {Tak, te¿ tak myœlê. Ale nie wolno nam sprzedawaæ niektórych starych narkotyków i substancji chemicznych, takich jak wygrzew i psycho. S¹ uwa¿ane za niebezpieczne.}
{255} {} {Dobra, niewa¿ne. Zmienimy temat?}
{256} {} {Tak, tego w³aœnie szukam. Czy naprawdê nie ma sposobu, aby dostaæ choæby szczypty? Nawet do celów naukowych?}
{257} {} {Nie wiem, jakie s¹ twoje cele naukowe, ale mam jasne instrukcje. Porozmawiaj z Nestorem, jeœli ci siê to nie podoba.}
{258} {} {Ok. Wydaje siê, ¿e kontynuowanie nie ma sensu. Czeœæ.}
{259} {} {No dalej - mam tu kupê kapsli!}
{260} {} {Um. Myœlê, ¿e pilnie potrzebujesz œwie¿ego powietrza. Tam s¹ drzwi.}
{261} {} {Nawet o tym nie myœl!}
{262} {} {Ok, nie chcê problemów. Wychodzê.}
{263} {} {Pomyœl, po co twojej klinice te starocie, których nikt nie kupuje ani nie u¿ywa?}
{264} {} {Tak... oczywiœcie... Hmm, mo¿e Nestor zrobi dla ciebie wyj¹tek. Naprawdê ostatnio zaczyna nam brakowaæ tutaj kapsli.}
{265} {} {Dziêki.}
{266} {} {Zrób dla mnie wyj¹tek. Nikomu nie powiem.}
{267} {} {Nestor ci pozwoli. Mo¿na powiedzieæ, ¿e jestem ju¿ cz³onkiem Twojego zespo³u.}
{268} {} {Potrzebujê dawki na... jak oni to... do eksperymentów, tak.}
{269} {} {Mam czysto naukowe zainteresowania. Oboje rozumiemy, jak wa¿ne jest, aby naukowcy wzajemnie siê wspierali.}
{270} {} {Zdziwi³abyœ siê, gdyby okaza³o siê, ¿e to naprawdê problem w Phoenix. Osobiœcie znam historiê jednego uzale¿nionego ze slumsów.}
{271} {} {Biedne istoty. Tak cierpi nauka z powodu czyjejœ g³upoty. Czy uzale¿nienie od narkotyków jest win¹ medycyny?}
{272} {} {Naprawdê nie ma sposobu, ¿eby dostaæ choæby szczypte narkotyku? Do celów naukowych?}
{273} {} {Nie rozmawiajmy o tym wiêcej. Zmieñmy temat.}
{274} {} {Ola wiesz, ¿e nie zrobiê nic g³upiego.}