{100} {} {Widzisz Wanga Chun.}
{101} {} {Widzisz du¿e, roz³o¿yste drzewo. Wzór na korze przypomina twarz mê¿czyzny. Chwila...}
{102} {} {* Khe-khe *}
{103} {} {Trudno rozmawiaæ w tym dymie. Musimy szybciej wyjœæ na œwie¿e powietrze.}

{110} {} {Hrrrr...}
{111} {} {Zzz...}
{112} {} {Masz, moje s³odkie mantysy, tak, w³ó¿ je do ust.}
{113} {} {Mniam, co za soczysta mantysa.}
{114} {} {Moje korzenie wyczuwaj¹ obcego.}
{115} {} {Hmm, czujê nieznany zapach.}
{116} {} {Co to jest? Co ty mówisz?}
{117} {} {Herbert, Bob, Nestor - ostatnio bardzo siê rozwineliœcie.}
{118} {} {Teraz rozumiem, jak bardzo têsknisz za s³oñcem.}
{119} {} {Potrzebujesz wiêcej nawozu z ludzkiego kompostu.}
{120} {} {Ooh...}
{121} {} {* Ciê¿kie westchnienie *}

{150} {} {Smia³o, moi mali zieloni przyjaciele!}
{151} {} {Chwyæ je i rozerwij na strzêpy!}
{152} {} {Poka¿ siê!}
{153} {} {Chwyæ ich ostrymi ³apami!}

{200} {} {Ach... Uh... Whoa. Jak d³ugo spa³em... Och, mamo. Dlaczego s³u¿ba mnie obudzi³a?}
{201} {} {Ech, kim jesteœ... czy czym jesteœ?}
{202} {} {Horror! Gadaj¹ca roœlina!}
{203} {} {Jestem Wang Chun, naukowiec, który stworzy³ te Ogrody Edenu. A ty kim jesteœ? Oh tak wiem. Ludzi takich jak ty ci¹gnie tu zapach przygody, ale jesteœcie jak g³upie robactwo, które wkrótce zostanie zjedzone przez drapie¿ne roœliny. Tak czy inaczej, przybycie tutaj jest z twojej strony du¿ym b³êdem.}
{204} {} {Dlaczego jesteœ... taki?}
{205} {} {Wiesz, gdybym nie mia³ obsesji na punkcie nauki i dobrobytu œwiata, uciek³bym st¹d dawno temu. Ale teraz nale¿ê tutaj. Tu bêdzie mój grób. I tak wszyscy trafimy do piachu.}
{206} {} {O czym ty mówisz?}
{207} {} {To naturalny obieg materii w przyrodzie. Wszyscy jesteœmy grud¹ lepkiego b³ota. Spójrz na mnie. Nie bêdê ju¿ móg³ chodziæ. Jestem zakorzeniony w ziemi, po której wêdrowa³em jak amarantus.}
{208} {} {Jesteœ bardzo rozmowny jak na roœlinê.}
{209} {} {Smieszne. Nie mogê ju¿ pracowaæ rêkoma i nogami, ale mój mózg nadal dzia³a. Trzymam siê ostatniej si³y, ¿eby nie zwariowaæ. Ale mia³em du¿o czasu, ¿eby pomyœleæ o sobie i otaczaj¹cym mnie œwiecie.}
{210} {} {Przepraszam. Czy coœ Pana boli?}
{211} {} {Ju¿ nie. Moje cia³o zosta³o zast¹pione przez zarodniki i komórki roœlinne. Nie mogê pracowaæ rêkoma i nogami, ale mój mózg wci¹¿ dzia³a. Trzymam siê ostatniej si³y, ¿eby nie zwariowaæ. Ale mia³em du¿o czasu, ¿eby pomyœleæ o sobie i otaczaj¹cym mnie œwiecie.}
{212} {} {Przykro ciê widzieæ w takim stanie. Ale mam tu interes. Bywaj.}
{213} {} {Nie! Czekaj! By³em równie g³upi i nieostro¿ny, kiedy przyszed³em do tej kopu³y, maj¹c nadziejê na spróbowanie owoców Staro¿ytnych. Za bardzo siê œpieszy³em i pope³ni³em kilka b³êdów. Teraz ca³a dolina jest rajem dla mutantów, i jeœli nikt nic nie zrobi, zmieni¹ siê ca³e pustkowia. Ludzie zobacz¹ narodziny nowego œwiata, ale nie bêdzie w nim dla nich miejsca.}
{214} {} {Jestem tutaj z misj¹ od Nestora. Potrzebujê dokumentów i œrodków chemicznych do walki z t¹ infekcja.}
{215} {} {Nie chcê dostaæ tej samej infekcji. Czy jest na ni¹ jakieœ lekarstwo?}
{216} {} {Co to jest „infekcja”? Ludzie paso¿ytuj¹cy na pozosta³oœciach starej cywilizacji? Och, jak¿e by³em œlepy, kiedy przyby³em do tej kopu³y z nadziej¹, ¿e skosztujê owoców Staro¿ytnych! Za bardzo siê œpieszy³em i pope³ni³em kilka b³êdów. Teraz ca³a dolina jest rajem dla mutantów, i jeœli nikt nic nie zrobi, zmieni¹ siê ca³e pustkowia. A ludzie... ludzie nie bêd¹ mieli miejsca w tym nowym œwiecie.}
{217} {} {Jak to? Nie mo¿na powstrzymaæ tej infekcji?}
{218} {} {Mo¿na. Ale jeœli Wyznawcy zdobêd¹ notatki laboratoryjne i inne materia³y z kompleksu, pewnego dnia bêd¹ kontynuowaæ swoje badania. I problem siê powtórzy.}
{219} {} {Wiêc co sugerujesz?}
{220} {} {Musimy zniszczyæ CALY kompleks! Ogieñ to najlepszy sposób na powstrzymanie rozprzestrzeniania siê infekcji poza dolinê. W koñcu to ta kopu³a jest jej g³ównym Ÿród³em.}
{221} {} {Najwa¿niejsze to powstrzymaæ mutacje. Zrobiê to.}
{222} {} {Och, bardzo dobrze, pielgrzymie. ZnajdŸ rury gazowe. Nie jest ³atwo je podpaliæ, ale niektórzy ju¿ próbowali. ZnajdŸ ich strawione szcz¹tki w szklarniach i zabierz materia³y wybuchowe.}
{223} {} {Ok. Spróbujê.}
{224} {} {Zbyt ryzykowne to wszystko. Czeœæ, Wang Chun.}
{225} {} {Zdecydowanie wariujesz. Nie ma na pustkowiach miejsca bardziej kolorowego i ¿ywego ni¿ ta kopu³a. Z pewnoœci¹ istnieje sposób na powstrzymanie infekcji bez ognia.}
{226} {} {G³upcze! Szuka³em sposobu na ograniczenie wzrostu szkodliwych zarodników. Ale nikt nie wie, czy to zadzia³a! A jeœli wzrost bêdzie siê utrzymywa³? ZnajdŸ rury gazowe i wysadŸ je w powietrze! To jedyny sposób!}

{230} {} {* Ciê¿kie westchnienie *}
{231} {} {Zzz...}
{232} {} {Hrrrr...}
{233} {} {Cokolwiek to jest, ta istota mocno œpi.}