{100} {} {Widzisz Teresê.}
{101} {} {Widzisz kobietê z krótkimi w³osami w szacie. Ma bardzo surowy wyraz twarzy.}
{102} {} {Przepraszam. Ale muszê siê trochê przespaæ przed zajêciami.}
{103} {} {Jak œmiesz straszyæ dzieci swoj¹ okropn¹ zbroj¹?}
{104} {} {Szko³a nie jest miejscem na broñ.}

{200} {} {Czeœæ. Czemu zawdziêczam tê wizytê?}
{201} {} {Co to za miejsce?}
{202} {} {Ach, jaka szkoda, ¿e wspó³czeœni ludzie zapomnieli, co znaczy „szko³a”. Tutaj uczymy dzieci najprostszych nauk œcis³ych, takich jak umiejêtnoœæ czytania i pisania oraz matematyki. Jesteœmy prawdopodobnie jedyn¹ obecnie szko³¹ w Sonorze i Arizonie.}
{203} {} {Dlaczego ktoœ mia³by jej potrzebowaæ?}
{204} {} {Aby œwiat nie wróci³ do epoki kamienia ³upanego. Ju¿ teraz na pustkowiu nie ma ani jednej szko³y, nie mówi¹c ju¿ o uniwersytecie. Zapomina siê o staro¿ytnej wiedzy i nie gromadzi siê nowej. W koñcu ludzie s¹ zajêci przetrwaniem, chocia¿ podejœcie naukowe rozwi¹za³oby równie¿ i ten problem.}
{205} {} {Za kogo mnie masz, kobieto? Wiem, co to jest „szko³a”!}
{206} {} {Có¿, mo¿liwe. Ale jest ma³o prawdopodobne, ¿e siê tam uczy³eœ, s¹dz¹c po tonie.}
{1206} {} {Có¿, mo¿liwe. Ale jest ma³o prawdopodobne, ¿e siê tam uczy³aœ, s¹dz¹c po tonie.}
{207} {} {Super! Prawdziwa szko³a! Myœla³em, ¿e wszystkie zosta³y zamkniête po Wielkiej Wojnie.}
{208} {} {Tak. Musieliœmy ciê¿ko pracowaæ, aby o¿ywiæ star¹ dobr¹ tradycjê. Wielu mieszkañców nie chcia³o nawet oddaæ tu swoich dzieci.}
{209} {} {Swoj¹ drog¹, kim jesteœ, ¿eby uczyæ dzieci pisaœ i liczyæ?}
{210} {} {Kim jesteœ, aby uczyæ dzieci pisaœ i liczyæ?}
{211} {} {Ciekawe. Kto stworzy³ tê szko³ê?}
{212} {} {Jesteœmy Wyznawcami Apokalipsy. Nasz¹ misj¹ jest nieœæ oœwiecenie na ziemiach Sonory.}
{213} {} {Rozumiem.}
{214} {} {Swoj¹ drog¹, natkn¹³em siê na Wyznawców Ognia. Te¿ maj¹ bibliotekê i ucz¹ dzieci.}
{215} {} {Ugh, ci szaleni ludzie nie wiedz¹, o czym mówi¹. Czego mog¹ nauczaæ swoj¹ wypaczon¹ wiar¹? Nie myl szko³y nauki i teologii. My, Wyznawcy Apokalipsy, jesteœmy bezpoœrednimi nosicielami przedwojennej nauki.}
{216} {} {Naprawdê?}
{217} {} {Nie ufaj fanatykom religijnym. Tylko Bóg wie, co naprawdê maj¹ na myœli.}
{218} {} {Dobrze.}

{220} {} {Wiêc co chcesz wiedzieæ?}
{221} {} {Wiem ju¿ wystarczaj¹co. PA.}
{222} {} {Zaczekaj chwilê. Wyjaœnijmy sobie jedno - uczy siê tu wiedzy, a nie sztuk walki... „sztuk”. Nie lubimy przemocy, a tym bardziej nie tolerujemy jej w szkole. Trzymaj wiêc swoje piêœci, no¿e i wszystko, co masz przy sobie. I nie ma potrzeby siê tak bezczelnie uœmiechaæ. Zosta³eœ ostrze¿ony.}
{223} {} {Ok. Moje umiejêtnoœci walki pozostan¹ poza drzwiami szko³y.}
{224} {} {Uwa¿aj te¿ na jêzyk, jeœli nie chcesz problemów.}

{230} {} {Opowiedz mi historiê Obserwatorów.}
{231} {} {Pierwotnie byliœmy ma³¹ grup¹ ludzi ¿yj¹cych w ruinach San Diego. Ale tam nie mo¿na by³o normalnie mieszkaæ, dlatego przenieœliœmy siê do ruin Los Angeles. Tam, w ledwo zachowanej bibliotece, za³o¿yliœmy siedzibê, która istnieje do dziœ.}
{232} {} {Kontynuuj.}
{233} {} {Spójrz na to zdjêcie. Zrobiono je sto lat temu w Inferno.}
{234} {} {Co to jest... O Bo¿e, niesamowite! Jeœli data siê zgadza, mamy tu prawdziwy kawa³ek staro¿ytnej historii!}
{235} {} {Widzê, ¿e jesteœ bardzo podekscytowana tym znaleziskiem.}
{236} {} {Nigdy nie widzieliœmy ani jednego takiego dokumentu z czasów Wielkiej Wojny. Widzisz, mówi¹, ¿e wojna skoñczy³a siê w ci¹gu zaledwie kilku godzin. W tak krótkim czasie na ca³ej planecie eksplodowa³y tysi¹ce bomb atomowych. Ponadto od tego wydarzenia minê³o du¿o czasu, wiele dokumentów po prostu nie przetrwa³o. Nie trzeba dodawaæ, ¿e nawet ksi¹¿ki sta³y siê bardzo rzadkie.}
{237} {} {Kontynuuj.}
{238} {} {Tutaj mamy bezpoœredni dowód na to, jak wygl¹da³a eksplozja j¹drowa w Mexicali... Có¿, tak nazywa³o siê to miasto przed wojn¹.}
{239} {} {Nazywaj¹ je teraz Inferno. Chcesz kupiæ ten przedmiot?}
{240} {} {Oczywiœcie! Daj nam to ze wzglêdu na naukê.}
{241} {} {Oczywiœcie, weŸ to. Potraktuj to jako moj¹ darowiznê dla szko³y.}
{242} {} {Wielkie dziêki. Dodamy Twoje imiê do listy dobroczyñców.}
{243} {} {Nie tak szybko. Zdobycie tego i przyniesienie tutaj wymaga³o wiele wysi³ku.}
{244} {} {Ok. Porozmawiam z innymi Wyznawcami. Postaramy siê zebraæ dla Ciebie komplet leków. To najcenniejsza rzecz w naszym mieœcie.}
{245} {} {Tutaj. Inna rzecz.}
{246} {} {Oddam to, ale w zamian chcê pos³uchaæ wyk³adów o tamtej epoce.}
{247} {} {Och, co za zaszczyt.}
{248} {} {Od tamtej pory do³¹czy³o do nas wiele osób. A niektórzy, jak ja, udaj¹ siê do odleg³ych krajów w celach misyjnych, aby za³o¿yæ tam now¹ œwi¹tyniê nauki.}
{249} {} {Swi¹tyniê nauki? Czy wy jesteœcie organizacj¹ religijn¹?}
{250} {} {Nie, nie, to tylko stare wyra¿enie. Nauka i religia w niewielkim stopniu siê pokrywaj¹. W ka¿dym razie nie chcemy koœcio³ów, poniewa¿ naucza nas spieraæ siê o Boga i umniejszaæ poganom.}
{251} {} {Dziêki za historie.}

{260} {} {Sk¹d pochodz¹ te stare ksi¹¿ki?}
{261} {} {Wiêkszoœæ z nich pochodzi z karawan. Zebraliœmy te¿ to, co dawno temu zachowa³o siê w okolicznych ruinach.}
{262} {} {Rozumiem.}
{263} {} {Niestety, te cztery ma³e szafy s¹ ¿a³osne w porównaniu z bibliotek¹ w Los Angeles. Wiêkszoœæ tych ksi¹¿ek jest ma³o przydatna w nauczaniu lub samej nauce.}
{264} {} {Mogê przynosiæ ksi¹¿ki, które znajduje podczas moich podró¿y.}
{265} {} {Och, by³oby wspaniale. Musimy doceniaæ ka¿de znalezisko. Oczywiœcie zap³acimy za pracê.}
{266} {} {Bêdê pamietaæ. PA.}
{267} {} {Mam star¹ ksi¹¿kê do Twojej biblioteki.}
{268} {} {W porz¹dku. Gdzie ona jest?}
{269} {} {Jest gdzie indziej. Nied³ugo j¹ przyniosê.}
{270} {} {Oto ksi¹¿ka dla Ciebie.}
{271} {} {Tu s¹ ca³e dwie ksi¹¿ki.}
{272} {} {W³aœciwie mam a¿ trzy. S¹ tutaj.}
{273} {} {WeŸ wszystkie ksi¹¿ki, które mam. Jest ich tutaj ca³a masa.}
{274} {} {Wielkie dziêki. Oto zap³ata - }
{275} {} { kapsle.}
{276} {} {Przyniosê wiêcej, jeœli coœ znajdê. PA.}
{277} {} {Zostaw kapsle dla swojej szko³y. To prezent ode mnie.}
{278} {} {Dziêki. To na pewno pomo¿e naszej szkole.}
{279} {} {Do widzenia.}

{280} {} {Gdzie mogê znaleŸæ stare ksi¹¿ki?}
{281} {} {My i nasi najemnicy ju¿ zbadaliœmy pobliskie ruiny. W¹tpiê, czy gdzieœ w pobli¿u s¹ jakieœ z³o¿a staro¿ytnych ksi¹g. Jest jednak jedno takie miejsce, ale dostêp do niego jest zamkniêty. To baza wojskowa w Puerto.}
{282} {} {Sk¹d ksi¹¿ki w bazie wojskowej?}
{283} {} {To nie s¹ tak naprawdê ksi¹¿ki, tylko ich wersje elektroniczne. Wiem o tym dziêki skrybom z Bractwa Stali. Ale jednoznacznie odmówili moim proœbom o podzielenie siê wiedz¹.}
{284} {} {Co za zrzêdy.}
{285} {} {Myœlê, ¿e maj¹ powód.}
{286} {} {Ale stare ksi¹¿ki s¹ w³asnoœci¹ ca³ej ludzkoœci, a nie tylko kilku wybranych. Mo¿e uda Ci siê dostaæ do bazy i skopiowaæ te teksty? Zap³acê i dam ci pusty holodysk do ich zgrania.}
{287} {} {W ogóle nie jestem tym zainteresowany. Przepraszam.}
{288} {} {Ok, zrobiê to. Daj mi ten holodysk.}
{289} {} {Dziêki. Oto holodysk. Skopiuj do niego przynajmniej najwa¿niejsze i niezbêdne informacje dla naszej szko³y. Powodzenia.}
{290} {} {Do widzenia.}
{291} {} {My i nasi najemnicy ju¿ zbadaliœmy pobliskie ruiny. W¹tpiê, czy gdzieœ w pobli¿u s¹ jakieœ z³o¿a staro¿ytnych ksi¹g.}
{292} {} {Rozumiem. Bêdê musia³ poszukaæ w bardziej odleg³ych miejscach.}
{293} {} {Uda³o mi siê zinfiltrowaæ bazê Bractwa i skopiowaæ ich ksi¹¿ki.}
{294} {} {Co za wspania³a wiadomoœæ! Potrzebujemy ksi¹¿ek w ka¿dej postaci. Bractwo nie ma prawa do ukrywania ich przed opini¹ publiczn¹.}
{295} {} {Oto holodysk.}
{296} {} {Zap³acê za to 100 kapsli. Wielkie dziêki.}
{297} {} {Proszê.}