{100} {} {Widzisz Nestora.}
{101} {} {Widzisz wysokiego blondyna w czystej sutannie. Ostro¿nie poprawia okulary na nosie.}
{102} {} {Proszê, od³ó¿ broñ. Nie bêdziesz jej tutaj potrzebowaæ.}
{103} {} {Proszê zostawiæ swoj¹ zbrojê gdzieœ poza klinik¹. Tutaj ma byæ czysto i sterylnie.}

#Pierwsze spotkanie
{200} {} {Witaj podró¿niku. Hmm. Myœlê, ¿e masz wiele pytañ i próœb. Pozwól, ¿e wyjaœniê od razu kilka spraw: to jest klinika, leczeni s¹ tu ludzie. A ja jestem jej zarz¹dc¹, Nestor. Jesteœ chory? A mo¿e chcesz o coœ zapytaæ?}
{1200} {} {Witaj podró¿niku. Hmm. Myœlê, ¿e masz wiele pytañ i próœb. Pozwól, ¿e wyjaœniê od razu kilka spraw: to jest klinika, leczeni s¹ tu ludzie. A ja jestem jej zarz¹dc¹, Nestor. Jesteœ chora? A mo¿e chcesz o coœ zapytaæ?}
{201} {} {Najpierw mam kilka pytañ.}

# Spotkanie ponownie
{210} {} {Ok. S³ucham.}
{211} {} {Porozmawialiœmy i wystarczy. Mam rzeczy do zrobienia.}
{212} {} {Mi³o ciê widzieæ.}
{213} {} {Dlaczego wróci³eœ?}
{1213} {} {Dlaczego wróci³aœ?}

#Lekarstwo
{220} {} {Potrzebujê leczenia.}
{221} {} {Dziwne. Nie wiem, jak mogê ci pomóc. Wielu mo¿e pozazdroœciæ Twojemu zdrowiu.}
{222} {} {Co za radoœæ, doktorze! Jakoœ tak nawet poczu³em siê lepiej.}
{223} {} {Och, przepraszam... Mogê ciê uleczyæ. Ale leki s¹ zbyt drogie. Wydamy na Twoje leczenie }
{224} {} { kapsli. Co mo¿esz zaoferowaæ jako rekompensatê?}
{225} {} { kapsli. Dok³adnie tyle, ile potrzeba.}
{226} {} {Nie mam nic wartoœciowego.}

{230} {} {Czekaj, wszystko w porz¹dku? Nie wygl¹dasz dobrze.}
{231} {} {Doktorze, jestem taki zmêczony. Chcê siê pozbyæ tego uzale¿nienia!}
{1231} {} {Doktorze, jestem taka zmêczona. Chcê siê pozbyæ tego uzale¿nienia!}
{232} {} {Moje serce œciska siê, kiedy widzê twoj¹ udrêkê. Jeœli naprawdê CHCESZ przestaæ, do³o¿ê wszelkich starañ, aby Ci pomóc.}
{233} {} {Tak! Co jest do tego potrzebne?}
{234} {} {Rehabilitacja to kosztowny i czasoch³onny proces. Obawiam siê, ¿e klinika nie bêdzie jeszcze w stanie w pe³ni pokryæ wszystkich kosztów.}
{235} {} {Twoja klinika to tylko sposób na pozbycie siê kapsli. Wychodzê st¹d!}
{236} {} {Nie mam nic. Zapytam dobrych ludzi.}
{237} {} {Rozumiem. Mam }
{238} {} { kapsle. Czy to wystarczy?}
{239} {} {Hmm. To niewiele, ale nic na to nie poradzê - trzeba ciê uratowaæ.}
{240} {} {Zanim zaczniemy, muszê wyjœæ. Wrócê trochê póŸniej.}
{241} {} {Oto kapsle. Kiedy zaczynamy?}
{242} {} {Im szybciej, tym lepiej. Najpierw nale¿y ciê wyk¹paæ...}
{243} {} {Prawdziwa k¹piel? Wow!}
{244} {} {Uzyskano zdolnoœæ rehabilitacji.}
{245} {} {Po tygodniu leczenia i treningu jesteœ wolny od na³ogu i jesteœ wzmocniony na wypadek nawrotu.}

{250} {} {Czy mówi³eœ coœ o przedwojennej medycynie i kilku eksperymentach?}
{251} {} {O tak. Mamy szczepionki na ró¿ne choroby, przedwojenny system promocji zdrowia i sprzêt Vault-Tec do specjalnego szkolenia w schronach przeciwbombowych. Ale nikt z nas jeszcze nie przeprowadzi³ tych eksperymentów na powa¿nie.}
{252} {} {Brzmi obiecuj¹co.}
{253} {} {Koszt równie¿ jest problemem. Takie procedury nie s¹ niezbêdne i poch³aniaj¹ du¿o zasobów i czasu. Dlatego klinika nie mo¿e œwiadczyæ takiej us³ugi na w³asny koszt.}
{254} {} {Ile to kosztuje?}
{255} {} {Hmm. Pozwól mi policzyæ... to bêdzie kosztowaæ }
{256} {} { kapsli i dziesiêæ dni, tak na wszelki wypadek. Drogo, ale tu chodzi o twoje ¿ycie.}
{257} {} {Ugh, nie. Dziêkujê za ofertê, ale nie mam tylu kapsli.}
{258} {} {Biorê to, doktorze. Oto kapsle za tê us³ugê.}
{259} {} {Bardzo dobrze. Najpierw przeprowadzimy ankietê...}
{260} {} {Hej, to ³askocze doktorze!}
{261} {} {Otrzymano dodatkowe punkty zdrowia.}
{262} {} {Po nudnej, ale satysfakcjonuj¹cej kuracji czujesz siê niesamowicie pobudzony!}
{263} {} {Czy mogê ponownie wzi¹æ udzia³ w kursie odnowy biologicznej?}
{264} {} {To mo¿liwe. Ale efekt nie bêdzie ju¿ tak zauwa¿alny. Tym razem bêdziesz musia³ poœwiêciæ wiêcej czasu i wysi³ku, aby osi¹gn¹æ te same wyniki.}
{265} {} {Ile to kosztuje?}
{266} {} { }
{267} {} { kapsli i zajmie to dwa tygodnie.}
{268} {} {O nie, to za drogo.}
{269} {} {Oto kapsle. Kiedy zaczynamy?}

{300} {} {Muszê z tob¹ porozmawiaæ o moim przyjacielu Carlosie.}
{301} {} {Oczywiœcie. Co siê z nim sta³o?}
{302} {} {Interesuje siê star¹ technologi¹. Znajdziesz tu dla niego miejsce?}
{303} {} {Intryguj¹ca propozycja. Ale gdzie on jest?}
{304} {} {Jest teraz w Tu San i czeka na twoj¹ odpowiedŸ.}
{305} {} {Co za niespodzianka. Wiêc on jest... Blacharzem?}
{306} {} {Nie, nie, on jest z mojej wioski. Ale Blacharze przyjeli Carlosa, doceniaj¹c jego talenty.}
{307} {} {Jednak nie jestem pewien, czy warto z kimkolwiek o tym rozmawiaæ. Przepraszam za k³opoty.}
{308} {} {Och, ciekawe. Opieram siê na twojej reputacji. Jeœli wierzysz w czystoœæ jego myœli, to mi to wystarczy. Powiedz mu, ¿e jesteœmy gotowi powitaæ go tu z ca³¹ nasz¹ goœcinnoœci¹.}
{309} {} {Dziêki!}
{310} {} {Och, ciekawe. Ale jednoczeœnie jest to wysoce w¹tpliwe. Obawiam siê, ¿e nie mo¿emy teraz ryzykowaæ z niezweryfikowanymi asystentami.}
{311} {} {Rozumiem. Szkoda, ¿e moja reputacja ciê nie przekonuje.}

# Wyprawa do czyszczenia plantacji
{320} {} {Wiem o zarazie, która zamienia ch³opów w potwory.}
{321} {} {Wiêc wiesz...}
{322} {} {Nie przewracaj oczami i nie wzdychaj. To twoja wina, prawda?}
{323} {} {Tak, to nasza wina. I coraz trudniej jest to ukryæ. Ale proszê o zrozumienie - nie mo¿esz wywo³aæ paniki. Ju¿ teraz trudno nam poradziæ sobie z tyloma zmartwieniami w mieœcie.}
{324} {} {Dlaczego nie poddasz miasta kwarantannie?}
{325} {} {To nie do pomyœlenia! Ludzie musz¹ dbaæ o plantacje, aby nie zniknê³y w piaskach. A jeœli ludnoœæ w ogóle ucieknie z miasta, przybêd¹ tu rabusie i rozprzestrzeni¹ infekcje jeszcze bardziej.}
{326} {} {Naprawdê?}
{327} {} {Ponadto ryzyko ogólnej epidemii jest nadal bardzo niskie. Wszystkie ofiary zosta³y zara¿one tylko dlatego, ¿e znajdowa³y siê blisko laboratorium, w którym nast¹pi³ wyciek. Chocia¿ owady zaczynaj¹ wszystko coraz bardziej rozprzestrzeniaæ.}
{328} {} {Czy to prawda?}
{329} {} {Trudno w to uwierzyæ.}
{330} {} {I tak nie ma sensu panikowaæ. Prawie wiemy, jak rozwi¹zaæ problem. W tym równaniu jest tylko kilka niewiadomych.}
{331} {} {Hmm. Nie wiem, czy ci wierzê.}
{332} {} {Jak w ogóle do tego dosz³o?}
{333} {} {Próbowaliœmy rozwi¹zaæ problem ¿ywnoœci, tworz¹c bardziej wytrwa³¹ i owocn¹ faune. Zaraza to efekt uboczny eksperymentów na roœlinach i owadach, który by³ trudny do przewidzenia.}
{334} {} {Hmm. Nie wiem, czy ci wierzê.}
{335} {} {Czy zamierzasz naprawiæ swój b³¹d?}
{336} {} {Oczywiœcie. Ca³y wolny czas zajmujemy siê obliczeniami i eksperymentami. Ale jak dot¹d brakuje nam niektórych danych.}
{337} {} {Mam nadziejê, ¿e mo¿esz to rozwi¹zaæ. W przeciwnym razie wszyscy bêdziemy mieæ problem.}
{338} {} {Czekaj. Nie wywo³asz paniki, prawda? Potrzebujemy teraz pomocy, a nie nowych problemów. Ponadto hojnie zap³acimy za pomoc.}
{339} {} {Czego ode mnie chcesz?}
{340} {} {Czy mogê jakoœ pomóc?}
{341} {} {Potrzebujemy pomocy bardziej ni¿ kiedykolwiek. Ponadto hojnie zap³acimy za przys³ugê.}
{342} {} {Co mogê dla was zrobiæ?}
{343} {} {Nasze laboratorium poza miastem sta³o siê wylêgarni¹ tej infekcji. Zawiera równie¿ ca³¹ dokumentacjê laboratoryjn¹, której nie uda³o nam siê wynieœæ przed kwarantann¹. Oraz niektóre chemikalia potrzebne do eksperymentów.}
{344} {} {Sugerujesz, ¿eby tam wróciæ?}
{345} {} {Laboratorium jest teraz poddane kwarantannie i mieszkañcom nie wolno nawet siê do niego zbli¿aæ. Bóg wie, czym siê teraz sta³o to miejsce, ale na pewno zaros³o roœlinnoœci¹. Jest tam wiele owadów i roœlin, prawdopodobnie niektóre z nich nadal ¿yj¹.}
{346} {} {Ale wtedy ryzykujê zara¿eniem, prawda?}
{347} {} {Tak. I to jest g³ówny problem. Podamy Ci antidotum na uk¹szenia owadów. Ale przeciwko oparom w powietrzu bêdziesz musia³ poszukaæ maski przeciwgazowej. Zaproponowaliœmy Blacharzom wykonanie masek przeciwgazowych, ale najwyraŸniej maj¹ oni inne priorytety.}
{348} {} {Ok. Pomogê Ci.}
{349} {} {Dziêki. Kiedy bêdziesz gotowy, przyjdŸ do mnie. Zabiorê ciê do laboratorium i nie zostanie to nawet zauwa¿one przez resztê mieszkañców.}
{350} {} {Do zobaczenia.}
{351} {} {Jesteœ naukowcem równie szalonym, jak ci, którzy stworzyli bombê atomow¹ przed wojn¹. Odmawiam wspó³pracy z tob¹.}
{352} {} {Rozumiem. Nie ufasz nam i nie chcesz ryzykowaæ. Ale teraz nie ma znaczenia, kto ponosi wine za to, co siê sta³o, wa¿niejsze jest rozwi¹zanie problemu. Pomyœl, jak¹ heroiczn¹ przys³ugê wyœwiadczysz miastu. Bêdziesz pamietany przez pokolenia. Wróæ, jeœli zmienisz zdanie.}
{353} {} {Do widzenia.}
{354} {} {Nie mogê wymyœliæ, jak w³aœciwie u¿yæ tej trucizny.}
{355} {} {IdŸ na plantacje i spryskaj j¹ gdzieœ w najbardziej zaroœniêtym miejscu.}
{356} {} {Ok.}
{357} {} {Có¿, to inna sprawa.}

{360} {} {Pomogê ci. Czas zakoñczyæ te infekcje!}
{361} {} {Mi³o to s³yszeæ. Mo¿emy nie byæ w stanie nic zrobiæ bez Ciebie.}
{362} {} {Jestem gotowy.}
{1362} {} {Jestem gotowa.}
{363} {} {Czekaj. Mam jeszcze kilka rzeczy do zrobienia. Nied³ugo wrócê.}
{364} {} {Twoim zadaniem jest znalezienie dokumentów laboratoryjnych i komponentów do stworzenia œrodka owadobójczego, który próbowaliœmy opracowaæ. Im szybciej to zrobisz, tym mniej szkód odniesie twoje cia³o. Tutaj, weŸ antidotum i œrodek pobudzaj¹cy. Powodzenia.}
{365} {} {[PrzejdŸ do laboratorium]}
{366} {} {Oto dane laboratoryjne i odczynniki.}
{367} {} {Wreszcie! Teraz jesteœmy o krok od zwyciêstwa. Potrzebujê czasu na przestudiowanie i sprawdzenie materia³ów tych...}
{368} {} {Proszê.}
{369} {} {...Czy to w³aœnie zasugerowa³ nasz kolega? Jak mog³em nie wpaœæ na to od razu! Tak, wp³yw na inn¹ specjalizacje. Nie jestem dobry w owadach, wiêc nie mog³em liczyæ siê z tak¹ symbioz¹ z zarodnikami grzybów... Ech, Wang Chun, jak bardzo mi teraz brakuje jego nudnych maksym.}
{370} {} {Co zamierzasz zrobiæ?}
{371} {} {Pierwsz¹ rzecz¹, jak¹ zrobiê, jest zrobienie œrodka owadobójczego, który powstrzyma rozprzestrzenianie siê infekcji. Myœlê, ¿e to nie potrwa d³ugo, bo odczynniki z laboratorium s¹ dobrze zakonserwowane. Poczekaj na korytarzu kilka godzin.}
{372} {} {Ok...}
{373} {} {Gotowe! Jest to mieszanina fungicydu przeciwko zarodnikom grzybów i insektycydu przeciwko paso¿ytniczym nosicielom. Trzeba to teraz rozpyliæ na plantacjach. Zrób to, podczas gdy my zajmiemy siê reszt¹ pracy.}
{374} {} {Ok.}
{375} {} {Rozpyli³em truciznê na plantacji. Na efekty nie trzeba by³o d³ugo czekaæ.}
{1375} {} {Rozpyli³am truciznê na plantacji. Na efekty nie trzeba by³o d³ugo czekaæ.}
{376} {} {Musisz mieæ poczucie obowi¹zku w swoich genach. Ca³a ta praca zwi¹zana ze zwalczaniem szkodników jest wzorem dla reszty Wyznawców. Pewnego dnia wyœlemy raport do Boneyard opisuj¹cy tê historiê.}
{377} {} {Przepraszam, ale robi³em to dla obiecanych kapsli, a nie nauki.}
{1377} {} {Przepraszam, ale robi³am to dla obiecanych kapsli , a nie nauki.}
{378} {} {Ca³a praca powinna byæ op³acona. Poprosi³em burmistrza o nagrodê - przys³uguje ci 350 kapsli. Wydaj je m¹drze. Dziêki jeszcze raz.}
{379} {} {Ja równie¿ cieszê siê z wykonanej pracy.}

{380} {} {Laboratorium zosta³o zniszczone. Sp³onê³o w ogniu.}
{381} {} {Widzieliœmy dym z ognia. To twoje dzie³o, prawda? (wzdycha) Co za g³upota...}
{1381} {} {Widzieliœmy dym z ognia. To twoje dzie³o, prawda? (wzdycha) Co za g³upota...}
{382} {} {Czy coœ nie tak? Czy wylêgarnia infekcji nie zosta³a zniszczona?}
{383} {} {Zród³o mog³o zostaæ zniszczone w inny sposób! A tak wraz z laboratorium zniszczono wszystkie prace naukowe, które mog³yby pomóc ludziom w przysz³oœci!}
{384} {} {Nie pomyœla³em o tym.}
{1384} {} {Nie pomyœla³am o tym.}
{385} {} {To by³ najskuteczniejszy sposób zatrzymania infekcji.}
{386} {} {Oczywiœcie! Na pewno! Kto oprócz ciebie wie, jak rozwi¹zaæ problem naukowy... Uff. Muszê siê uspokoiæ.}
{387} {} {?}
{388} {} {Przepraszam, oczywiœcie post¹pi³eœ w³aœciwie. Bezpieczeñstwo jest najwa¿niejsze. Ale co, jeœli infekcja ponownie wykie³kuje w innym miejscu? Bez danych naukowych z laboratorium bêdzie znacznie trudniej sobie z tym poradziæ. Z drugiej strony mamy teraz du¿o czasu na przygotowania. W ka¿dym razie dziêkujê.}
{389} {} {Co najwa¿niejsze, problem zosta³ rozwi¹zany. Powodzenia w twoich badaniach, Nestorze.}
{390} {} {Hej, hej! A kto mi zap³aci? To nie by³o takie proste.}
{391} {} {Technicznie rzecz bior¹c nie wykona³eœ swojego zadania. W koñcu poprosi³em o dokumenty i chemikalia. Ale ¿eby ciê nie uraziæ, zap³acê 100 kapsli. Tyle musi wystarczyæ.}
{1391} {} {Technicznie rzecz bior¹c nie wykona³aœ swojego zadania. W koñcu poprosi³em o dokumenty i chemikalia. Ale ¿eby ciê nie uraziæ, zap³acê 100 kapsli. Tyle musi wystarczyæ.}
{392} {} {Lepsze to ni¿ nic.}
{393} {} {Wszêdzie oszuœci! Ju¿ nigdy nie zaufam Obserwatorom.}
{394} {} {Przykro mi, ¿e tak siê sta³o. Do widzenia.}
{395} {} {Natkn¹³em siê na te chemikalia w laboratorium.}
{396} {} {Byæ mo¿e te chemikalia przydadz¹ siê przy tworzeniu trucizny. Przyjrzyj siê uwa¿nie laboratorium, powinna byæ tam jeszcze szczegó³owa dokumentacja i niezbêdny sprzêt.}
{397} {} {Ok, poszukam dalej.}
{398} {} {A ju¿ wydawa³o mi siê, ¿e zadanie zosta³o wykonane...}

#Zapytania
{400} {} {Opowiedz mi o Obserwatorach.}
{401} {} {Jest nas trzech, jeœli liczyæ mojego asystenta. Jestem kierownikiem kliniki i laboratorium chemicznego. Teresa uczy i zajmuje siê matematyk¹.}
{402} {} {Niedawno do³¹czy³a do nas Diana.}
{403} {} {Nie mam dalszych pytañ.}
{404} {} {Kto wœród was rz¹dzi?}
{405} {} {Nie mamy ¿adnych zleceniodawców czy zwierzchników. Ka¿dy Obserwator robi swoje i razem tworzymy kolegium, aby rozwi¹zywaæ typowe problemy. Tak, to ró¿ni siê od prymitywnej postawy, do której przywyk³eœ na pustkowiach.}
{406} {} {Jak ci siê podoba Diana?}
{407} {} {Ka¿dy pracownik jest dla nas cenny, szczególnie z tak bogatym doœwiadczeniem i motywacj¹. A dane, które zebra³a po drodze, s¹ nieocenione. Jestem pewien, ¿e bardzo nam pomo¿e.}
{408} {} {To dobrze.}
{409} {} {Niestety, nadal nie rozumie, ¿e w Casa Nueva wa¿ne jest przestrzeganie zasad i nie wystêpowanie przeciwko w³adzom. I tak, wiem, ¿e Diana prze¿y³a dziêki tobie. Dziêkujê Ci.}
{410} {} {Rozumiem. Przypomnij mi, kto jest kim?}
{411} {} {Dlaczego Teresa jest taka uparta?}
{412} {} {Przepraszam za ni¹. W koñcu praca z dzieæmi to trudne zajêcie i prawie nikt nie ma takiego doœwiadczenia w tym w naszych czasach. Wszystko, co mo¿e zrobiæ, to czytaæ stare ksi¹¿ki o psychologii dziecka i odkrywaæ je w biegu. I to pomimo faktu, ¿e wci¹¿ musi prowadziæ w³asne badania.}
{413} {} {Dlaczego potrzebujesz asystenta?}
{414} {} {Nie ogarnê tu wszystkiego sam. Prowadzê klinikê i laboratorium chemiczne, chocia¿ nie jestem chemikiem. Alexandra zdejmuje ze mnie ten ciê¿ar.}
{415} {} {Kto z was by³ pracownikiem plantacji?}
{416} {} {Tej osoby nie ma ju¿ z nami. Poœwiêci³a siê siê nauce. Proszê o ni¹ nie pytaæ, aby nie zraniæ czyichœ uczuæ.}
{417} {} {Ale by³ to inny Obserwator, prawda?}
{418} {} {Wang Chun... Nie mia³ szczêœcia. Przewa¿nie spêdza³ czas w szklarniach. Nie lubi³ komunikacji z ludŸmi, ale kocha³ roœliny i naukê. I to go zabi³o, gdy mutagenne zarodniki zaw³adnê³y jego cia³em. Wiesz, lepiej bêdzie, jeœli przestaniesz o niego pytaæ, to wci¹¿ dra¿liwy temat.}
{419} {} {Czy plantacje te¿ nale¿¹ do Ciebie?}
{420} {} {Dobrze.}
{421} {} {Czy to nie dziwne, ¿eby uprawiaæ roœliny na œrodku pustyni?}
{422} {} {Zaufaj nam, mieliœmy powody, ¿eby tu byæ. Ta decyzja jest wynikiem szeroko zakrojonych badañ naukowych.}

{430} {} {Opowiedz mi o klinice.}
{431} {} {Nawet nie wiem, co powiedzieæ. Otworzyliœmy j¹ g³ównie po to, by s³u¿yæ ¿o³nierzom Puerto. To by³a czêœæ ogólnego porozumienia z wojskiem, w przeciwnym razie nie mielibyœmy na to pozwolenia. A potem zaczeli przychodziæ tu lokalni pracownicy z proœbami o pomoc.}
{432} {} {Ok. Zmieñmy temat.}
{433} {} {Sk¹d siê wzi¹³ ca³y ten sprzêt?}
{434} {} {Czêœæ zrobili Blacharze na zamówienie. Czêœæ przywieziono karawanami z ró¿nych miejsc.}
{435} {} {Rozumiem.}
{436} {} {Interesuj¹ mnie twoje metody. W naszej Villi oprócz zió³ i grzybów trudno cokolwiek znaleŸæ.}
{437} {} {Nie mam szczególnych uprzedzeñ co do tradycyjnej medycyny. By³a przydatna w swoim czasie. Ale stopniowo powracaj¹ metody przedwojenne. W koñcu nawet uruchomiliœmy system szczepieñ przeciwko chorobom. Czy to nie cud?}
{438} {} {Sk¹d bierzecie lekarstwa?}
{439} {} {Oczywiœcie sami je robimy. Na przyk³ad etanol jest ³atwo wytwarzany z agawy ogniowej. A uzyskane leki s¹ sprzedawane lub wymieniane na inne œrodki chemiczne.}

{440} {} {Jak tam ¿ycie?}
{441} {} {W porz¹dku. Trudno jest dziœ znaleŸæ lepsze miasto.}
{442} {} {Dobrze, jesteœ dobry.}
{443} {} {Mimo tych wszystkich zakazów?}
{444} {} {Przeszkadzaj¹ Ci zakazy? By³y ju¿ przed wojn¹. W³adze maj¹ swoje powody, by ograniczaæ zwyk³ych mieszkañców. I trzeba siê z tym liczyæ.}
{445} {} {Czy brak wolnej woli i totalitaryzm uszczêœliwi³ kiedykolwiek ludzi?}
{446} {} {Czy zwykli ludzie byli kiedykolwiek ca³kowicie wolni? Taka historia mo¿liwa jest tylko w jaskini, w oderwaniu od reszty œwiata. I najprawdopodobniej ¿yj¹c tam samemu. Wniosek jest wiêc prosty - doceniajmy to, co mamy.}
{447} {} {Hmm. Warto to rozwa¿yæ.}
{448} {} {Co mo¿esz mi powiedzieæ o swoim burmistrzu?}
{449} {} {Na ramionach Alvaro spoczywa du¿y ciê¿ar. Musi odpowiadaæ za miasto tylko dlatego, ¿e nie ma nikogo innego, kto móg³by to robiæ. Nie sprawiaj mu dodatkowych k³opotów.}
{450} {} {Nawet o tym nie myœla³em.}

{451}{}{Czy wiesz coœ o Krypcie 24? }
{452}{}{Ta Krypta znajduje siê w ruinach San Diego. Z niej pochodzili za³o¿yciele naszej misji. Ale sam tam nigdy nie by³em, bo to miejsce jest przeklête promieniowaniem dla przysz³ych pokoleñ.}
{453}{}{Naprawdê ¿yli tam Wasi za³o¿yciele?}
{454}{}{Krypty zosta³y zbudowane tylko po to, by przetrwaæ ciê¿kie czasy po ataku nuklearnym. Wed³ug legendy za³o¿yciele opuœcili schron, aby pomóc œwiatu odrodziæ siê. Ich ofiara jest dziœ wspominana przez wszystkich Wyznawców.}
{455}{}{By³em tam. To miejsce jest naprawdê przeklête. Ukradli stamt¹d te¿ wszystko, co by³o jakkolwiek przydatne.}
{456}{}{Nic dziwnego. S³ysza³em o Wielkim Exodusie Ghuli na po³udnie do Blasku. Wygl¹da na to, ¿e znaleŸli dla siebie odpowiednie miejsce. Niech ta radioaktywna ziemia bêdzie wobec nich pob³a¿liwa.}
{457}{}{Tak, coœ w tym stylu. Czy mo¿emy porozmawiaæ o czymœ innym?}
{458}{}{Znalaz³em kawa³ek historii tej Krypty. Spójrz, to jest kopia pamiêtnika miejscowego nadzorcy.}
{459}{}{Naprawdê? Popatrzmy... Okazuje siê, ¿e sytuacja zmusi³a za³o¿ycieli do opuszczenia Krypty? Co za bana³. Legenda brzmia³a piêkniej, ale... Ale teraz widzê, ¿e byli tak samo prostymi ludŸmi jak wszyscy inni. Dziêkujê za ten tekst. Zachowam to dla naszej historii.}
{460}{}{Proszê. Czy mo¿emy porozmawiaæ o czymœ innym?}
{461}{}{Mo¿emy porozmawiaæ o czymœ innym?}