{100} {} {Widzisz Carlosa.}
{101} {} {Widzisz jednego z ch³opów Villi. Jednak sta³ siê w jakiœ sposób... inny.}
{102} {} {Czeœæ. Cieszê siê, ¿e ciê widzê.}
{103} {} {Nie rozmawiaj ze mn¹. Ca³e miasto ciê szuka.}

{200} {} {Co za niespodzianka! Cieszê siê, ¿e ciê widzê, }
{201} {} {.}
{202} {} {Jak Ciê przyjeli Obserwatorzy?}
{203} {} {Ca³kiem ¿yczliwie. To dobrzy ludzie, czego nie mo¿na powiedzieæ o Blacharzach.}
{204} {} {Znalaz³eœ ju¿ swoje miejsce w Casa Nueva?}
{205} {} {Jest tu du¿o pracy dla mnie. Poza tym podpisa³em kontrakt na kilka lat... No có¿, postawi³em krzy¿yk. Teraz mam dom i wszystko czego mi trzeba do prze¿ycia. Na pewno nie umrê tu z g³odu.}
{206} {} {Super. Czy chcesz mi coœ jeszcze powiedzieæ?}
{207} {} {Wiesz, dali mi apteczkê pierwszej pomocy, ale w¹tpiê, ¿eby mi siê tu przyda³a. Proszê, weŸ to, tobie przyda siê bardziej.}
{208} {} {Dziêki, Carlos. I ¿egnaj.}

{210} {} {Czeœæ }
{211} {} {. Cieszê siê, ¿e ciê widzê.}
{212} {} {Do widzenia Carlos.}
