{100} {} {Widzisz Chipa.}
{101} {} {Widzisz lokalnego dzieciaka.}
{102} {} {Wow, czy to prawdziwa broñ? Masz pozwolenie?}
{103} {} {Wow, czy to zbroja wspomagana? Myœla³em, ¿e to wynalazek Franka.}
{104} {} {Co robisz?}
{105} {} {Têskniê za Pinkym.}
{106} {} {Nie! Dlaczego to zrobi³eœ?}
{1106} {} {Nie! Dlaczego to zrobi³aœ?}

# Plywajace frazy
{110} {} {Hej Pinky!}
{111} {} {Siad, Pinky!}
{112} {} {Co za g³upie zwierzê.}
{113} {} {Nie, Pinky!}
{114} {} {Nie szoruj pod³ogi!}
{115} {} {Pinky, przestañ gryŸæ meble.}
{116} {} {Och, tata mnie za to skarci.}
{117} {} {Poczekaj, dam ci trochê wody.}
{118} {} {Czy jesteœ g³odny?}
{119} {} {Chcesz trochê pysznoœci?}
{120} {} {Spójrz, mam nogê modliszki.}
{121} {} {Dobra robota, Pinky. Grzeczny Pinky.}
{122} {} {Gotowe.}
{123} {} {Chcesz wiêcej?}
{124} {} {Daj ³apê!}

{130} {} {Hej Pinky!}
{131} {} {Przestañ marudziæ, Pinky.}
{132} {} {Podnios³eœ ca³y dom na nogi.}
{133} {} {Chcesz, ¿eby s¹siedzi us³yszeli?}
{134} {} {Przestañ mnie drapaæ!}
{135} {} {Martwiê siê o ciebie.}
{136} {} {Och, co siê z tob¹ dzieje?}
{137} {} {Czy mam ci przynieœæ wody?}
{138} {} {Zobacz, co zrobi³eœ!}
{139} {} {Co ciê boli?}

{200} {} {Czeœæ. Szukasz mojego taty? Powinien byæ w swoim biurze.}
{201} {} {Tak. Czy jesteœ jego synem?}
{202} {} {Tak. Jestem Chip.}
{203} {} {Rozumiem.}
{204} {} {Kto to jest?}
{205} {} {To... To jest Pinky. Idê za nim...}
{206} {} {Hmm. Ciekawe.}

#Dialog
{210} {} {Co robisz?}
{211} {} {Wow. Myœla³em, ¿e wyrzucono Ciê z miasta.}
{212} {} {Hej, czy to o Tobie tak du¿o mówi¹?}
{213} {} {Pinky by³ ostatnio trochê ospa³y. Wygl¹da na to, ¿e ca³kowicie wyzdrowia³.}
{214} {} {Opiekujê siê Pinkym.}

{219} {} {Do widzenia, Chip.}

{220} {} {Czy wiesz, gdzie jest twój tata?}
{221} {} {Chyba w biurze. Zazwyczaj siedzi tam ca³y czas nad swoimi papierami i wyrzuca mnie, abym mu nie przeszkadza³.}
{222} {} {Uh, uwierz mi, naprawdê nie powinieneœ mu „przeszkadzaæ”.}

{230} {} {Masz niezwyk³ego zwierzaka.}
{231} {} {To jest Pinky. Jest fajny, ale ludzie nie chc¹ go widzieæ w mieœcie.}
{232} {} {Dlaczego?}
{233} {} {Có¿, wymyœlaj¹ ró¿ne rzeczy. Ze jest niebezpieczny, ¿e przenosi infekcje lub szkodzi plantacjom. Jakieœ bzdury. Frank jest najbardziej niezadowolony. Krzyczy, ¿e zabije Pinky'ego, kiedy tylko bêdzie to mo¿liwe.}
{234} {} {Kretoszczury mog¹ byæ rzeczywiscie niebezpieczne.}
{235} {} {Ale Pinky nie jest taki! Nadal nie zrobi³ nic z³ego. Tylko nie œpi w nocy. Ostatnio te¿ chorowa³. Podczas gdy inni chc¹ jego œmierci, on naprawdê potrzebuje teraz pomocy.}
{236} {} {Mo¿e tak bêdzie najlepiej. Czeœæ.}
{237} {} {To smutna wiadomoœæ. Poczekaj, ch³opcze.}
{238} {} {Pozwól mi obejrzec tê bestiê. Mo¿e uda mi siê go wyleczyæ.}
{239} {} {Musia³em przeprowadziæ ca³¹ operacjê temu Pinkyemu. Ale teraz to ju¿ koniec.}
{240} {} {Wiêc naprawdê wyzdrowia³! Super! Dziêkujê bardzo. Wiesz, wydaje siê, ¿e ciê lubi. Mo¿esz siê z nim bawiæ, jeœli chcesz. Ale nie wychodŸ z nim poza plantacje, aby nie uciek³ na pustyniê.}
{241} {} {Cieszê siê, ¿e mog³em pomóc. Powodzenia Chip.}
{1241} {} {Mi³o by³o Ci pomóc. Powodzenia Chip.}
{242} {} {Co za niesprawiedliwoœæ!}
{243} {} {Chcia³bym spacerowaæ z Pinkym.}
{244} {} {Jeœli on chce iœæ z tob¹, to nie mam nic przeciwko. Tylko nie zabieraj go daleko od domu.}
{245} {} {Dziêki. Bêdê z nim spacerowa³ tylko po najbli¿szych dzielnicach.}