{100} {} {Widzisz dziecko.}
{101} {} {Widzisz bardzo czyste i schludne dziecko.}
{102} {} {Nie naciskaj!}

{110} {} {Witam dzikusie.}
{111} {} {Sk¹d jesteœ?}
{112} {} {Pobawisz siê ze mn¹?}
{113} {} {Mama i tata odeszli.}
{114} {} {Dlaczego muszê pracowaæ dla doros³ych?}
{115} {} {Na szczêœcie nie muszê pracowaæ.}
{116} {} {Chcê spaæ.}
{117} {} {Mi³ej nocy. W nocy trzeba spaæ.}
{118} {} {Czy ty te¿ uprawiasz roœliny?}
{119} {} {Chcê zobaczyæ inne miasta.}

{120} {} {Zzz}
{121} {} {* Hr-r-r *}

{130} {} {Tra-la-la, tra-la-la. Nie s³yszê Ciê.}
{131} {} {Wróæ na pustyniê.}
{132} {} {Zostaw mnie w spokoju.}
{133} {} {Mówi¹, ¿e jesteœ kryminalist¹.}
{134} {} {Czy jesteœ z³odziejem?}

{1130} {} {Tra-la-la, tra-la-la. Nie s³yszê Ciê.}
{1131} {} {Wróæ na pustyniê.}
{1132} {} {Zostaw mnie w spokoju.}
{1133} {} {Mówi¹, ¿e jesteœ kryminalist¹.}
{1134} {} {Czy jesteœ z³odziejem?}
