{100} {} {Widzisz mieszkañca Casa Nueva.}
{101} {} {Widzisz lokalnego. W porównaniu z mieszkañcami innych osad wygl¹da doœæ pulchnie i zdrowo.}

{110} {} {Czeœæ. Sk¹d pochodzisz?}
{111} {} {Nie chodŸ po plantacji, bo zostaniesz wziêty za z³odzieja.}
{112} {} {Przepraszam, mam za du¿o pracy, nie mam czasu na rozmowy.}
{113} {} {Z przyjemnosci¹ porozmawiam, ale teraz nie czas na to.}
{114} {} {Przestrzegaj zasad, jeœli nie chcesz problemów.}

{120} {} {Zawo³am pozosta³ych, jeœli nie zostawisz mnie w spokoju.}
{121} {} {Oszala³eœ? Jest noc!}
{122} {} {Nie budŸ we mnie bestii.}
{123} {} {OdejdŸ. Nie ka¿ mi krzyczeæ.}
{124} {} {Co za bezczelnoœæ. Nieznajomi s¹ tak Ÿle wychowani...}
{125} {} {To nie jest czas na rozmowê. IdŸ st¹d.}
{126} {} {S³uchaj, jest godzina policyjna. Bêdziemy mieæ problemy.}

{130} {} {Hola! Jak siê masz?}
{131} {} {Nasze miasta powinny siê zjednoczyæ.}
{132} {} {Cieszê siê, ¿e ciê widzê.}
{133} {} {Mój dom to teraz te¿ Twój dom.}
{134} {} {Ch³opi powinni trzymaæ siê razem.}

{140} {} {Jak mamy teraz przetrwaæ?}
{141} {} {Bez Bractwa jesteœmy ³atwym celem dla bandytów.}
{142} {} {Pozwól Alvaro powiedzieæ nam, co robiæ!}
{143} {} {Precz z zakazem broni!}
{144} {} {Pieprzyæ zakazy, czas na zmiany.}
{145} {} {Znosiliœmy ten ucisk przez bardzo d³ugi czas. Doœæ!}
{146} {} {Teraz my bêdziemy rz¹dziæ miastem!}
{147} {} {Karabin dla ka¿dej rodziny!}
