{100} {} {Widzisz Nicka.}
{101} {} {Widzisz jednego z mieszkañców Casa Nueva.}
{102} {} {W nocy œpimy i nie przeszkadzamy sobie nawzajem. Najlepiej nie ³amaæ tej zasady.}

{200} {} {Czeœæ, jestem Nick. Jak mogê ci pomóc?}
{201} {} {Mi³o ciê poznaæ, Nick. Czy mogê zadaæ kilka pytañ?}
{202} {} {Twoje imiê mnie nie interesuje. Ale muszê coœ wiedzieæ.}
{203} {} {Niewa¿ne. Pójdê ju¿.}

{210} {} {W czym mogê pomóc?}
{211} {} {Czego ode mnie chcesz?}
{212} {} {Pójdê ju¿.}
{213} {} {Czy mogê zadaæ kilka pytañ?}

{220} {} {Oczywiœcie.}
{221} {} {Dziêki Nick. PA.}
{222} {} {Przepraszam, lepiej najpierw porozmawiaj z burmistrzem. W przeciwnym razie bêdziemy mieli problemy.}
{223} {} {Mówisz powa¿nie? W porz¹dku...}

{230} {} {Kim jesteœ?}
{231} {} {Mam na imiê Nick, mówiê ci.}
{232} {} {Co tu robisz, Nick?}
{233} {} {Co osoba o takim imieniu mo¿e robiæ w takim miejscu?}
{234} {} {Wiesz, pracujê. Wczeœniej pracowa³em w betoniarni, ale zak³ad zosta³ niedawno zamkniêty.}
{235} {} {Twoja ciê¿ka praca jest godna pochwa³y. Niewielu jest sk³onnych zaanga¿owaæ siê w swoj¹ pracê. Ale chcê ciê zapytaæ o coœ innego.}
{236} {} {Czy to wszystko, co osi¹gn¹³eœ? Zrób coœ wartoœciowego - odpowiedz mi na kilka pytañ.}
{237} {} {Musisz mieæ du¿o wolnego czasu. Czy mo¿esz odpowiedzieæ na kilka dodatkowych pytañ?}

{240} {} {Jak trafi³eœ do tego miasta?}
{241} {} {Wiesz, nie ma tu zwyczaju pytaæ o przesz³oœæ. Budujemy nowe ¿ycie, aby zast¹piæ stare. Ale jeœli tak bardzo ci zale¿y, to pochodzê z Casa Grande. To ma³e miasteczko w drodze do Phoenix. Na pewno zdarzy³o ci siê przez nie przejœæ, co?}
{242} {} {Mówisz Casa Grande? Dziêki za informacje. Co jeszcze mo¿esz mi powiedzieæ?}
{243} {} {M¹drala, co? Oczywiœcie, ¿e wiem o tym miejscu. Lepiej powiedz mi coœ innego.}
{244} {} {Rozumiem. A co z reszt¹ pytañ?}
{245} {} {Jak bardzo jesteœ wolny? Mo¿esz odejœæ, jeœli chcesz?}
{246} {} {Po co mia³bym opuszczaæ ten raj? Wokó³ jest tylko pustynia, a w du¿ych osadach nie ma nic oprócz cierpienia. Tak, tutaj tracê czêœæ wolnoœci. Ale w zamian dostajê schronienie i jedzenie. Najpierw musimy przetrwaæ i zbudowaæ nowy œwiat, a dopiero potem mo¿emy mówiæ o wolnoœci. Takie czasy.}
{247} {} {M¹drze powiedziane, Nick. Tutaj naprawdê ¿yje siê lepiej ni¿ w pozosta³ej czêœci Arizony. Czy chcia³byœ powiedzieæ mi coœ jeszcze?}
{248} {} {Tylko s³abi ludzie nie id¹ pod wiatr. Mam nadziejê, ¿e masz si³ê, aby odpowiedzieæ przynajmniej na kilka pytañ.}
{249} {} {Rozumiem ciê. Pozwólisz, ¿e zadam Ci inne pytanie?}
{250} {} {Gdzie jest Casa Grande?}
{251} {} {W po³owie drogi nr 10 miêdzy Phoenix i Tu-San. Mogê pokazaæ Ci na mapie.}
{252} {} {Dziêki.}
