{100} {} {Widzisz Himadora Juan.}
{101} {} {Widzisz mocno opalonego mê¿czyznê w s³omkowym kapeluszu i czystej lnianej koszuli.}
{102} {} {Broñ jest zabroniona w mieœcie. Schowaj to szybko.}
{103} {} {O witam, sir... Muszê pracowaæ... jeœli mogê...}
{104} {} {Nie rozmawiaj ze mn¹, gdy w mieœcie jest godzina policyjna...}

#Pierwsze spotkanie
{200} {} {Ola, senor. Mam na imiê Juan. Nie widzia³em ciê tu wczeœniej.}
{1200} {} {Ola, senora. Mam na imiê Juan. Nie widzia³em ciê tu wczeœniej.}
{201} {} {Czy zawsze witacie tu nowych w tak nieprzyjazny sposób?}
{202} {} {Spójrz, mamy tutaj czêœciowo zamkniet¹ spo³ecznoœæ. Wszyscy siê znaj¹. Chcemy tylko zrozumieæ, czego mo¿emy siê po tobie spodziewaæ, to wszystko.}
{203} {} {Ok. Przepraszam.}
{204} {} {Ju¿ pokazaliœcie swoje nastawienie do obcych. Chyba nie spodoba mi siê tutaj.}
{205} {} {Mi³o ciê poznaæ, Juan. Jestem }
{206} {} { z odleg³ej wioski na pó³nocy.}
{207} {} {Och, ty te¿ jesteœ ch³opem! Witamy.}
{1207} {} {Ach, ty te¿ jesteœ ch³opk¹! Witamy.}
{208} {} {Dziêki. Widzê, ¿e mieszkaj¹ tu dobrzy ludzie.}
{209} {} {Inaczej przegoni³byœ mnie, co? Jesteœ taki „goœcinny”.}

# Spotkanie ponownie
{210} {} {Hola. Buenas noches.}
{211} {} {Hola. Buenos dias.}
{212} {} {Adios, hombre.}
{213} {} {Potrzebujê soku z ognistej agawy.}

{220} {} {Opowiedz mi o tym mieœcie. Kto tu rz¹dzi?}
{221} {} {Musisz zobaczyæ siê z burmistrzem Alvaro. Lubi rozmawiaæ z nieznajomymi.}
{222} {} {Dziêki, porozmawiam z nim póŸniej.}
{223} {} {Opowiedz mi o sobie.}
{224} {} {Jestem Himador Juan. Co jeszcze mogê ci powiedzieæ?}
{225} {} {Co tu robisz Himador Juan?}
{226} {} {Zajmujê siê agaw¹ ognist¹ i innymi uprawi. W miêdzyczasie jeszcze zajmujê siê wysy³k¹ towarów do karawan i innych gospodarstw domowych.}
{227} {} {Juan, powiedz mi... czy jesteœ tu dobrowolnie?}
{228} {} {Si, senor. Pracujê jako peon. Mogê wyjœæ w ka¿dej chwili, ale nie mam dok¹d pójœæ. Dlatego muszê ¿yæ tu wed³ug zasad i wypracowaæ kontrakt.}
{1228} {} {Si, senora. Pracujê jako peon. Mogê wyjœæ w ka¿dej chwili, ale nie mam dok¹d pójœæ. Dlatego muszê ¿yæ tu wed³ug zasad i wypracowaæ kontrakt.}
{229} {} {Rozumiem. Dziêkujê za odpowiedŸ.}

{230} {} {Chcê ciê zapytaæ o plantacje.}
{231} {} {Uprawiamy g³ównie kukurydzê i agawê ognist¹. Dlaczego ciê to interesuje?}
{232} {} {Po prostu mnie to ciekawi - co to za „agawa ognista”?}
{233} {} {Wiem o pospolitej agawie, ale po raz pierwszy s³yszê o ognistej. Co to jest?}
{234} {} {Zwolennicy mówi¹, ¿e to zmutowana agawa wyhodowana przed Wielk¹ Wojn¹. Od tego czasu roœlina sta³a siê wiêksza, bardziej truj¹ca i bardziej przypominaj¹ca ig³y ni¿ roœlinê. Ale w œrodku nadal jest zdrowa miazga. To jest to, co g³ównie z niej pozyskujemy.}
{235} {} {Jaki jest po¿ytek z tej roœliny?}
{236} {} {Uh, amigo, z tej roœliny to wszystko mo¿na wykorzystaæ. Miazga i sok - do jedzenia i picia. A ³odygi - na nawóz i s³omê. Zwolennicy nawet wytwarzaj¹ leki z wyt³oków z agawy!}
{237} {} {Gdzie s¹ plantacje?}
{238} {} {Na wschodzie... Ale nie polecam tam iœæ. Wielu z nas siê to nie spodoba.}
{239} {} {Ciekawe. Czy mogê kupiæ jakieœ plony?}
{240} {} {W³aœciwie ¿niwa nie s¹ wystarczaj¹ce dla wszystkich. Dlatego nie wolno mi handlowaæ ze wszystkimi.}
{241} {} {Rozumiem. Dziêkujê za odpowiedŸ.}
{242} {} {Naprawdê potrzebujê soku z agawy. Sprzedaj mi trochê, proszê.}
{243} {} {Przepraszam, amigo. Nie mogê. Jeœli burmistrz dowie siê o tym, na pewno bêdê mia³ problemy.}
{244} {} {Ok, zapomnij.}
{245} {} {Kto tu rz¹dzi?}
{246} {} {Prawdopodobnie i tak masz jakieœ nadwy¿ki, których znikniêcia nikt nie zauwa¿y. A ja mam akurat nadwy¿kê kapsli...}
{247} {} {Widzê, ¿e potrafisz siê targowaæ. Okay, jeœli potrzebujesz soku z agawy, skontaktuj siê ze mn¹. Chocia¿ nie rozumiem, dlaczego go potrzebujesz. Chcesz zrobiæ tequilê?}
{248} {} {Myœlê o tym.}
{249} {} {No dalej, Juan, to ja. Czy tak traktujesz swoich przyjació³?}

{250} {} {Dlaczego broñ jest tutaj zabroniona?}
{251} {} {Nie sprzeciwiaj siê zasadom, kochany viajero. Te zakazy s¹ wypisane krwi¹ przy g³ównej bramie.}
{252} {} {Przepraszam, to by³o niepotrzebne pytanie. Zapomnij o tym.}
{253} {} {Dlaczego nosisz tê dziwn¹ w³óczniê?}
{254} {} {Ahaha, to nie jest broñ, to koa. Podczas zbioru siekam ni¹ liœcie agawy. Mam na to pozwolenie od burmistrza. Bez pozwolenia nawet koa nie mo¿e byæ noszona otwarcie.}
{255} {} {Nigdy czegoœ takiego nie widzia³em.}
{1255} {} {Nigdy czegoœ takiego nie widzia³am.}
{256} {} {Burmistrz zleci³ to zrobiæ Blacharzom. Dostali za to zap³atê w ¿niwach. Bardzo to drogie, ale bez narzêdzi ciê¿ko by³oby nam pracowaæ. I poza Blacharzami nikt inny nie potrafi tego zrobiæ.}
{257} {} {Brzmi znajomo. W Villi te¿ wszystko robimy rêcznie.}
{258} {} {Naprawdê? Nigdy nie s³ysza³em o innych plantacjach. Nie k³amiesz?}
{259} {} {Jeœli mi nie wierzysz, to zmieñmy temat.}
{260} {} {Teraz rozumiem. Porozmawiamy o czymœ innym?}
{261} {} {Po raz pierwszy widzê takie narzêdzie.}
{262} {} {Czy to „wszystko”?}
{263} {} {Dlaczego?}
{264} {} {Czy chcia³byœ, ¿eby ktoœ chodzi³ po twoim domu bez pytania? Poza tym czasami ³apiemy z³odziei. Zwykle ich los jest godny ubolewania.}