{100} {} {Widzisz burmistrza Alvaro.}
{101} {} {Widzisz mizernego Meksykanina z cienkimi w¹sami i znudzonym spojrzeniem.}
{102} {} {Ukryj to natychmiast. Zadnej broni, gdy jesteœ w mieœcie.}
{103} {} {Mamy tu spokojn¹ osadê. Nie powinieneœ tu chodziæ w tym czymœ i straszyæ cywilów.}
{104} {} {Czy coœ siê sta³o? Lepiej natychmiast wracaj do ³ó¿ka! W mieœcie obowi¹zuje cisza nocna.}
{105} {} {Prosz¹ mnie o podjêcie decyzji. Co mogê zrobiæ? Ja tylko podpisywa³em papiery dla Bractwa!}

#Pierwsze spotkanie
{200} {} {Och, nowa twarz w mieœcie! Co za mi³a niespodzianka... Witamy. Mogê powiedzieæ, ¿e jestem burmistrzem tego miasta. Mam na imiê Alvaro.}
{201} {} {Witaj burmistrzu.}
{202} {} {Hmm. Mo¿e zechcesz powiedzieæ mi swoje imiê? Nie bêdê nalegaæ. Byæ mo¿e masz powód by tego nie robiæ.}
{203} {} {Tak, zgadza siê.}
{204} {} {Jestem }
{205} {} {. Bardzo mi mi³o, Senor Alvaro.}
{206} {} {Dobre maniery? Myœlê, ¿e siê dogadamy.}
{207} {} {Dziêki za ciep³e przyjêcie.}
{208} {} {Co to za ¿a³osny widok, burmistrzu? To jest Twoim zdaniem miasto?}
{209} {} {Uh, tak, zdajê sobie sprawê, ¿e nie jest tak du¿e jak Phoenix lub jego obrze¿a. Poza pustyni¹ Sonora nic w ¿yciu nie widzia³em. Ale spójrz - czy nie jest tu piêknie?}
{210} {} {Mo¿e.}
{211} {} {Tu jest okropnie - nie ma tu cywilizacji.}
{212} {} {Czy mogê wiedzieæ, dok¹d idziesz?}
{213} {} {Nie wiem. Idê tam, gdzie ponios¹ mnie nogi.}
{214} {} {Có¿, dobrze, wierzê na s³owo. To naprawdê nie moja sprawa.}
{215} {} {Dziêkujê za zrozumienie.}
{216} {} {Dok³adnie.}
{217} {} {Mo¿esz liczyæ na nocleg w naszym mieœcie. Ale musisz przestrzegaæ zasad. Nie bêdziesz nam sprawiaæ k³opotów, prawda?}
{218} {} {Oczywiœcie. Dziêki za propozycjê.}
{219} {} {Nie gryzê, chyba ¿e mi siê przeszkadza. Miej to na uwadze.}
{220} {} {S³u¿ê Bractwu Stali. Oto moja odznaka.}
{221} {} {Och, witaj! Nie zauwa¿y³em tego... Uh... Zawsze cieszymy siê z wizyt naszych obroñców. Rozgoœæ siê.}
{222} {} {Dziêki.}
{223} {} {Tak po prostu.}
{224} {} {Jadê do Puerto. Mam tam interesy.}
{225} {} {Co za niespodzianka. Zwykle je¿dz¹ w tam tylko karawany. No có¿, jeœli nie chcesz rozmawiaæ, nie bêdê nalegaæ.}
{226} {} {Dziêkujê za zrozumienie.}
{227} {} {To dobrze. Jak to siê mówi, cisza jest dro¿sza ni¿ worek kukurydzy.}
{228} {} {Nie twoja sprawa.}
{229} {} {Có¿, za³ó¿my, ¿e to naprawdê nie moja sprawa. Ale nie b¹dŸ dla nas niemi³y, poniewa¿ staramy siê tu ¿yæ w pokoju z ka¿dym.}
{230} {} {Przepraszam, to z nerwów - po prostu jestem zmêczony drog¹...}
{231} {} {Jeœli nie chcesz konfliktu, to sam go nie zaczynaj. Rozumiesz?}
{232} {} {Mi³o by³o rozmawiaæ. Ale teraz przepraszam, mam du¿o papierkowej roboty.}
{233} {} {Do zobaczenia ponownie.}
{234} {} {Czy my mamy to samo imiê? Zabawny zbieg okolicznoœci. W takim razie na pewno siê dogadamy.}

{239} {} {To koniec. Wynoœ siê st¹d, zanim t³um ciê obali, przegrany burmistrzu.}
{240} {} {(burmistrz siedzi przy stole z rêkoma na g³owie i nie zwraca uwagi na otaczaj¹cych go ludzi) Eh-eh...}
{241} {} {Kiepsko wygl¹dasz. Coœ siê sta³o?}
{242} {} {Wszystko przepad³o... Zwykliœmy przetrwaæ dziêki Bractwu Stali. Niedawno przyszed³ pos³aniec ze z³ymi wiadomoœciami...}
{243} {} {Tak, wiem - Bractwo zosta³o zniszczone. Prawdopodobnie wybuch w sk³adzie amunicji.}
{244} {} {Co teraz zrobimy? Kto nas ochroni? Kto udzieli nam wskazówek?}
{245} {} {A co z Obserwatorami?}
{246} {} {Oni nie s¹ wojownikami i bardzo niewielu z nich mo¿e rozwi¹zaæ tak wiele problemów. Ta sytuacja jest beznadziejna... Wszystko stracone... wszystko stracone...}
{247} {} {Hej Alvaro, weŸ siê w garœæ! Jesteœ burmistrzem. Teraz wszystko jest w twoich rêkach. Jesteœ wolny od ca³kowitej kontroli i ucisku. Czy to nie wspania³e?}
{248} {} {Tak... oczywiœcie... Ale co ze mnie za burmistrz? Robi³em tylko papierkow¹ robotê pod nadzorem ludzi z zakonu. Teraz musimy przetrwaæ sami. To nie bêdzie ³atwe.}
{249} {} {Dasz radê. Wierzê w Ciebie.}

# Spotkanie ponownie
{250} {} {Przepraszam, mam teraz du¿o papierkowej roboty.}
{251} {} {Do widzenia.}
{252} {} {Jak mogê pomóc, drogi przyjacielu?}
{253} {} {Witaj, nasz nowy bohaterze. Jak mogê ci pomóc?}
{1253} {} {Witaj, nasza nowa bohaterko. Jak mogê ci pomóc?}

{260} {} {Mówi¹, ¿e zagineli ludzie z twojego miasta. To prawda?}
{261} {} {Kto tak mówi?}
{262} {} {Nie powiem.}
{263} {} {Ach, oczywiœcie, ¿e nikogo nie brakuje! Z wyj¹tkiem niektórych przestêpców, którzy uciekli podczas budowy miasta.}
{264} {} {Rozumiem.}
{265} {} {Naprawdê mam nadziejê, ¿e nie bêdziesz dalej rozpowszechniaæ tych brudnych, fa³szywych plotek.}
{266} {} {Oczywiœcie. Nie chcê problemów.}
{267} {} {Dopóki siê nie oka¿e, ¿e k³amiesz. Adios, panie burmistrzu.}
{268} {} {Rosalia. Mówi, ¿e zabraniasz poszukiwañ jej mê¿a.}
{269} {} {Co za bzdury! Nie zabraniam poszukiwañ, niech szukaj¹. Ale nie da siê go znaleŸæ, poniewa¿ w³aœnie uciek³ z miasta. Z pewnoœci¹ nie mog³a tego przyj¹æ do wiadomoœci.}
{270} {} {Rozumiem.}
{271} {} {Niewa¿ne - stara wiedŸma pewnie wariuje.}

{280} {} {Opowiesz mi o mieœcie, proszê?}
{281} {} {Mamy tu pokojow¹ spo³ecznoœæ ch³opów. Po³owa ludzi pracuje na plantacjach, reszta - przy ró¿nych codziennych sprawach. Spójrz, Wyznawcy maj¹ nawet w³asn¹ szko³ê.}
{282} {} {Dziêkujê za odpowiedŸ.}
{283} {} {Co tu roœnie?}
{284} {} {G³ównie kukurydza i agawa ognista. Ca³e miasto ¿yje na tych plantacjach.}
{285} {} {Wiêc handlujesz z innymi miastami?}
{286} {} {Zniwa wystarczaj¹ tylko na nasze w³asne potrzeby i pobliskie osady. I jeszcze jest karawana z Phoenix, regularnie przyje¿dza do nas po sok z agawy.}
{287} {} {Swoj¹ drog¹, jakie miasta s¹ w pobli¿u?}
{288} {} {Rozumiem.}
{289} {} {Puerto na zachodzie i Tu-San na wschodzie. To wszystko, z wyj¹tkiem kilku ma³ych wiosek i placówek, ale s¹ one g³ównie sezonowe.}
{290} {} {Dziêki.}
{291} {} {Prawdziwa oaza na œrodku pustyni. Jak to siê sta³o?}
{292} {} {Dziêkujemy Wyznawcom Apokalipsy za ich inteligencjê i dobroæ. To oni opracowali w swoim laboratorium odmiany roœlin, które mog¹ zakorzeniæ siê na suchej pustyni.}
{293} {} {Czy inne miasta te¿ kupuj¹ Twoje plony?}
{294} {} {Kim s¹ Obserwatorzy?}
{295} {} {Swoj¹ drog¹, kim s¹ ci Obserwatorzy?}
{296} {} {Wyznawcy Apokalipsy - tak na siebie mówi¹... Dziwna nazwa, ale jesteœmy do niej przyzwyczajeni. Prowadz¹ badania naukowe, ucz¹ dzieci, lecz¹ choroby. Rzeczywiœcie, to dziêki ich eksperymentom ca³a ta plantacja pojawi³a siê na œrodku pustyni. Ale lepiej zapytaæ o to samych Obserwatorów.}
{297} {} {Znam innych wyznawców - Wyznawców Ognia w Phoenix.}
{298} {} {Coœ o nich s³ysza³em, ale nigdy siê nie spotkaliœmy. Z wyj¹tkiem karawan pochodz¹cych z Phoenix.}
{299} {} {Swoj¹ drog¹, dlaczego alkohol jest tu zabroniony?}
{300} {} {Dlaczego alkohol jest tu zabroniony?}
{301} {} {Formalnie tylko mocny alkohol jest zabroniony. Mamy za du¿o pracy, ¿eby traciæ czas na rozrywkê. Ale to prawda, ¿e po ¿niwach ch³opi maj¹ kilka dni ca³kowitego odpoczynku.}
{302} {} {To ciekawe, nie ma tu stra¿ników. Nie boisz siê handlarzy niewolników ani bandytów?}
{303} {} {O „pokojowej spo³ecznoœci”. Nie boisz siê handlarzy niewolników ani bandytów?}
{304} {} {Dlaczego powinniœmy siê ich baæ? Na tych ziemiach porz¹dku pilnuj¹ nasi patroni. Jesteœmy pokojowymi ludŸmi i zajmujemy siê tylko pokojowymi sprawami. Nie wolno nam nawet mieæ broni. Dlatego nie ma siê tu czego baæ.}
{305} {} {Tak, masz tutaj prawdziw¹ oaze. Jak to siê sta³o?}
{306} {} {Patroni? Kto to jest?}
{307} {} {Jak to, nie wiesz o bazie wojskowej w Puerto? Wiêc nie powinienem z tob¹ o tym rozmawiaæ. Po prostu wiedz, ¿e jest ktoœ, kto stanie w naszej obronie w razie koniecznoœci.}
{308} {} {Wiesz, o kim mówiê - o Bractwie Stali. S¹ teraz w³aœcicielami tych ziem.}

{310} {} {Co s¹dzisz o Bractwie Stali?}
{311} {} {To nasi patroni. Bez nich nie przetrwalibyœmy.}
{312} {} {Rozumiem.}
{313} {} {Szczerze?}
{314} {} {To jest uczciwa odpowiedŸ.}
{315} {} {To dobrze.}
{316} {} {Niech tak bêdzie - tak zrobiê.}
{317} {} {Nie s³yszê w twoich s³owach radoœci i podziwu.}
{318} {} {Mogê z tob¹ szczerze porozmawiaæ, prawda? Staramy siê o tym nie mówiæ, ale wszyscy tutaj ¿yj¹ w zasadzie na prawach peonów. To znaczy jak niewolnicy na ca³e ¿ycie. W istocie, aby uzyskaæ ochronê i miejsce do ¿ycia, trzeba p³aciæ nieprzystêpne podatki.}
{319} {} {Dalej.}
{320} {} {Ze wzglêdu na brak funduszy mieszkañcy zawieraj¹ umowê, wynajmuj¹c siê na resztê ¿ycia.}
{321} {} {Przykro to s³yszeæ.}
{322} {} {Zgodnie z wymaganiami.}
{323} {} {Ale nie jest tak Ÿle. Mamy woln¹ rêkê we wszystkim, co nie jest sprzeczne z prawami i interesami Bractwa Stali. I naprawdê otrzymujemy niezawodn¹ ochronê i pomoc. W koñcu Bractwo potrzebuje po¿ywienia i szlaku handlowego. A bez nas nic z tego nie jest mo¿liwe do osi¹gniêcia.}
{324} {} {Zamierzasz pogodziæ siê z t¹ sytuacj¹?}
{325} {} {Nie mamy wyboru! To dziêki Bractwu i Blacharzom zbudowaliœmy tak piêkne miasto i uprawiamy nasze plony. Bez nich wiedlibyœmy ¿a³osne ¿ycie padlino¿erców na pustyni.}
{326} {} {Naprawdê trudna sprawa. Nie wiem, co wola³bym wybraæ w takiej sytuacji.}
{327} {} {Trudno mi zrozumieæ, jak wolnoœæ mo¿na zamieniæ na ¿ycie w stajni. WyraŸnie popelni³eœ b³¹d. Do widzenia.}
{328} {} {Znam twój sekret na temat zarazy i jej t³umienia. A tak¿e - presja na mieszkañców i ci¹g³e zakazy. Czy to nie jest twoja tyrania, jeœli Bractwo nie ma z tym nic wspólnego?}
{329} {} {Jeœli nie mo¿esz zostaæ szponem œmierci, udawaj œlepego szczura. Czy to masz na myœli, s³abeuszku?}

{330} {} {Czy wiesz, ¿e zwierzak twojego syna umiera?}
{331} {} {Tak... Ten kretoszczur ju¿ od dawna mi przeszkadza tym swoim skomleniem i nocnymi akcjami. Powiedzia³em Chipowi, ¿e nie powinieneœ trzymaæ *zwierzaka* w domu, ale on mnie nie s³ucha. Teraz musimy znosiæ i odpieraæ ataki naszych s¹siadów.}
{332} {} {Co Pinky wam wszystkim zrobi³?}
{333} {} {No có¿, szczerze mówi¹c, nic szczególnego, poza tym ¿e ha³asuje. Ale on dodatkowo przera¿a samym swoim wygl¹dem. I to wystarczy. Gdyby by³ chocia¿ u¿yteczny, byæ mo¿e ogólny stosunek do Pinky'ego by siê zmieni³.}
{334} {} {Ciekawe spostrze¿enie.}

{340} {} {Osada Santa Ana chce zacz¹æ z wami handlowaæ.}
{341} {} {Santa Ana? Nie s³ysza³em o tej wiosce od lat. Jej mieszkañcy unikali z nami kontaktu. Co siê tam zmieni³o?}
{342} {} {Có¿, powiedzmy, ¿e w³adza siê tam zmieni³a.}
{343} {} {Och, to brzmi intryguj¹co. W takim razie przygotujê karawanê. Byæ mo¿e wœród mieszkañców Santa Ana pozyskamy nowe rêce do pracy, których czasami tak nam brakuje. Dziêkujê za Twoj¹ wiadomoœæ.}
{344} {} {Proszê.}