{100} {} {Widzisz Pinkyego.}
{101} {} {Widzisz... kretoszczura. Co za niespodzianka!}
{102} {} {Pi!}
{103} {} {Phi!}
{104} {} {Pinky nagle zmar≥.}
{105} {} {Pi-i-i...}
{106} {} {Frrr...}
{107} {} {Phi!}

{200} {} {Pi!}
{201} {} {Tak, tak, pi.}
{202} {} {Chodü tutaj.}
{203} {} {Hej Pinky, za mnπ.}
{204} {} {Pi! Pi!}
{205} {} {Grzeczny Pinky.}
{206} {} {Zaczekaj tutaj, Pinky.}
{207} {} {Wracaj do domu, Pinky.}