{100} {} {Widzisz ch³opkê.}
{101} {} {Widzisz ch³opkê w œrednim wieku ze zniszczonymi rêkoma.}
{102} {} {Zawo³am po pomoc, jeœli nie odejdziesz w tej chwili.}

{210} {} {Czego chcesz?}
{211} {} {Czego chcesz?}
{212} {} {Kim jesteœ?}
{213} {} {Niczym nie handlujê, przepraszam.}
{214} {} {Lepiej porozmawiaj z burmistrzem. Jesteœmy tylko pracownikami.}
{215} {} {Wygl¹da na to, ¿e wybra³eœ z³e drzwi.}

{220} {} {Mi³o ciê widzieæ.}
{221} {} {Có¿, czy osiedli³eœ siê w nowym miejscu?}
{222} {} {O czym chcesz porozmawiaæ?}
{223} {} {Ola! Swietnie, ¿e wci¹¿ tu jesteœ.}
{224} {} {Jesteœmy wdziêczni za pomoc.}

{229} {} {Do widzenia.}

{230} {} {Kim jesteœ?}
{231} {} {Nazywam siê Lo.}
{232} {} {Co robisz, Lo?}
{233} {} {Pracujê. Na przyk³ad na plantacjach.}
{234} {} {Wymagaj¹ce zajêcie, jak s¹dzê?}
{235} {} {Praca jest zawsze trudniejsza ni¿ zasadzki na trasach karawan. Czy¿ nie? Och, przepraszam, myœla³am, ¿e jesteœ jednym z „tych”...}
{236} {} {Nastêpnym razem siê obra¿ê.}
{237} {} {Nie ma problemu. Rozumiem twoj¹ nieufnoœæ do nieznajomych.}

{240} {} {Jak tam twoje ¿ycie?}
{241} {} {Swietnie! To najlepsze miejsce na pustkowiu. Oczywiœcie w zamian za ochronê i po¿ywienie trzeba ciê¿ko pracowaæ. Ale to prawda. Podziêkowania dla zwolennikow i burmistrza Alvaro!}
{242} {} {Dobrze, ¿e dobrze sobie radzisz.}
{243} {} {Szczerze?}
{244} {} {Mówiê, ¿e nie ma lepszego miejsca ni¿ Casa Nueva. A kto go nie lubi - nie zostaje tu d³ugo.}
{245} {} {Ok. Tym razem w to uwierzê.}
{246} {} {To dobrze. Powodzenia.}
{247} {} {Myœlê, ¿e przesadzasz. Po tym wszystkim, co zobaczy³em, mam wra¿enie, ¿e jesteœ tutaj niewolnikiem.}
{248} {} {Czekaj... (rozgl¹da siê) Nie powinieneœ tak mówiæ... Jest tu naprawdê wiele zakazów i nakazów. Niektórzy nie mog¹ tego znieœæ. Nie wolno nam nawet rozmawiaæ o ustalonym porz¹dku.}
{249} {} {Dlaczego nie walczycie o swoje prawa?}
{250} {} {Poniewa¿ ich nie mamy. Jesteœmy prostymi ch³opami, prawie niewolnikami... Ka¿da zuchwa³oœæ jest tu surowo karana, a zamieszki s¹ bezpoœredni¹ drog¹ do grobu. Skoñczmy to. Nie prowokuj bestii, gdy œpi.}
{251} {} {No i wszystko jasne...}
{252} {} {Czekaj... Hmm. Czy mogê szczerze porozmawiaæ z naszym bohaterem?}
{1252} {} {Czekaj... Hmm. Czy mogê szczerze porozmawiaæ z nasz¹ bohaterk¹?}
{253} {} {Oczywiœcie. O czym myœlisz?}
{254} {} {Có¿, to zale¿y.}
{255} {} {Przez ca³y ten czas w g³êbi serca mia³am w¹tpliwoœci co do tego miejsca i jak d³ugo to potrwa. Wiêc trzyma³am ze sob¹ kilka kul na wypadek, gdybym zmieni³a zdanie i chcia³a st¹d uciec.}
{256} {} {Kontynuuj.}
{257} {} {I?}
{258} {} {Powininnam chyba zapomnieæ o przesz³oœci, poniewa¿ przysz³oœæ jest o wiele lepsza. Proszê, weŸ te naboje, potrzebujesz ich bardziej.}
{259} {} {Dziêki. To naprawdê mo¿e siê przydaæ.}
{260} {} {Jeœli to dla ciebie takie wa¿ne, to je wezmê.}