{100} {} {Widzisz Rosaliê.}
{101} {} {Widzisz kobietê w zadbanym ch³opskim ubraniu.}
{102} {} {Witaj nieznajomy. Coœ nowego na pustkowiach?}
{1102} {} {Witaj nieznajoma. Coœ nowego na pustkowiach?}
{103} {} {Lajdaki! Trzymaj¹ mnie w zamkniêciu, abym zwariowa³a, a inni przestali mi ufaæ.}

#Pierwsze spotkanie
{200} {} {Hej nieznajomy... Hej, czeœæ. To twój pierwszy raz tutaj, prawda?}
{1200} {} {Hej, nieznajoma... Hej, czeœæ. To twój pierwszy raz tutaj, prawda?}
{201} {} {Dlaczego pytasz?}
{202} {} {Có¿, chcia³abym z tob¹ porozmawiaæ... sam na sam, jeœli nie masz nic przeciwko.}
{203} {} {Oczywiœcie. Dlaczego nie?}
{204} {} {Brzmi podejrzanie. Czego odemnie chcesz?}
{205} {} {To bardzo wa¿ne. Spotkajmy siê poza bramami miasta, gdzie nikt nas nie us³yszy, dobrze?}
{206} {} {Ok. Bêdê tam.}
{207} {} {Ok, ale nawet nie myœl, ¿eby mnie oszukaæ.}
{208} {} {Spierdalaj.}

{210} {} {Dziêki za przybycie. Czy ktoœ ciê œledzi³?}
{1210} {} {Dziêki za przybycie. Czy ktoœ ciê œledzi³?}
{211} {} {Czego ode mnie chcesz?}
{212} {} {Widzisz... niedawno zagin¹³ mój m¹¿. Poszed³ na plantacje i nigdy nie wróci³. Szuka³am go, ale nie mog³am go znaleŸæ. Potrzebujê twojej pomocy!}
{213} {} {Ale czemu robisz z tego tak¹ tajemnicê?}
{214} {} {Nie wolno mi o tym mówiæ! Aby nie wzbudzaæ paniki - tak mówi burmistrz. To zdecydowanie spisek! WyraŸnie coœ ukrywaj¹.}
{215} {} {A co z innymi? Dlaczego nie poszukasz go w ca³ej wiosce?}
{216} {} {To miejsce nie jest tak piêkne, na jakie wygl¹da. Jesteœmy zmuszani aby siedzieæ cicho, wierz mi, to nie pierwszy raz, kiedy znikaj¹ tu ludzie.}
{217} {} {Zmuszani? Jak to?}
{218} {} {Zasady s¹ tutaj bardzo surowe. Z zewn¹trz miasto wygl¹da wiarygodnie, ale tak naprawdê p³acimy za nie nasz¹ wolnoœci¹. Ka¿dy, kto siê z nimi nie zgadza, zostaje ukarany lub wyrzucony za bramê.}
{219} {} {Ok. Poszukam go. Jak on wygl¹da?}
{220} {} {Sniady, niski, z w¹sami... O tak, mia³ ze sob¹ œlubny wisiorek. Te s¹ wrêczane przez burmistrza wszystkim, którzy zawarli zwi¹zek ma³¿eñski w naszym mieœcie.}
{221} {} {Nie martw siê, spróbujê go znaleŸæ.}
{222} {} {Nic nie obiecujê.}
{223} {} {Sprawa jest niejasna i wygl¹da niebezpiecznie. Wiêc poszukam, ale za op³at¹.}
{224} {} {Oczywiœcie. Przyniosê ci trochê jedzenia i oddam wszystkie kapsle - i tak nie mam nic innego.}
{225} {} {Proszê, znajdŸ mojego mê¿a! Nie mam do kogo siê zwróciæ!}
{226} {} {Ok, uspokój siê.}

{230} {} {Jak siê masz? Niedobrze, jak widaæ.}
{231} {} {I co z tego? Znalaz³eœ coœ?}
{232} {} {Jeszcze nie.}
{233} {} {Rozumiem. Czeœæ.}

{240} {} {Nigdy siê nie przedstawiliœmy. Kim jesteœ?}
{241} {} {Ach, przepraszam. Jestem Rosalia, zajmujê siê przetwarzaniem roœlin.}
{242} {} {Muszê iœæ, Rosalio.}
{243} {} {Mówi¹, ¿e k³óci³aœ siê ze swoim mê¿em.}
{244} {} {Oczywiœcie ¿e siê k³óciliœmy! To nie jest ma³¿eñstwo z mi³oœci. Urz¹d Miasta interesuje siê ma³¿eñstwami i daje nam pewne korzyœci za nie. Ale od kilku lat mój m¹¿ i ja jakoœ siê do siebie przyzwyczailiœmy...}
{245} {} {Rozumiem...}
{246} {} {Czekaj, kto ci to powiedzia³? Mam nadziejê, ¿e nie rozmawia³eœ o tym z burmistrzem Alvaro? Nie mo¿esz mu ufaæ! S³yszysz co mówiê? Nie próbuj nawet z nim rozmawiaæ o zaginionych osobach.}
{1246} {} {Czekaj, kto ci to powiedzia³? Mam nadziejê, ¿e nie rozmawia³aœ o tym z burmistrzem Alvaro? Nie mo¿esz mu ufaæ! S³yszysz co mówiê? Nie próbuj nawet z nim rozmawiaæ o zaginionych osobach.}
{247} {} {Ok, uspokój siê...}

{250} {} {Twój m¹¿ nie ¿yje. Przykro mi.}
{251} {} {Czy twój m¹¿ by³ zielonym dziwakiem? W takim razie wiedz, ¿e jest ca³kowicie uschniêty i le¿y w stodole na plantacji.}
{252} {} {Nie mia³am w¹tpliwoœci. Czy zosta³ zabity? Czy nie? Powiedz mi prawdê!}
{253} {} {Przydarzy³a mu siê dziwna rzecz. Wygl¹da to na chorobê. Lepiej idŸ i sama zobacz.}
{254} {} {Co to jest... Wiedzieliœmy, ¿e niektóre owady rozprzestrzeniaj¹ infekcje, ale ¿eby infekcja mog³a rozprzestrzeniæ siê po ca³ym organizmie?}
{255} {} {Wiêc to nie pierwszy raz?}
{256} {} {Winni s¹ Obserwatorzy. Zrobili mu to swoimi eksperymentami! I nie tylko jemu! Diab³y!}
{257} {} {Wyznawcy Apokalipsy? Jakie eksperymenty?}
{258} {} {Maj¹ laboratorium na pustyni. Ale nie wolno nam nawet siê tam zbli¿aæ... Ach, przeklêci naukowcy! Dali nam plony, ale zabrali dusze.}
{259} {} {[Cisza]}
{260} {} {Masz dobre serce, senor. Na zdrowie. I trzymaj siê z dala od tych naukowców.}
{1260} {} {Masz dobre serce, senora. Na zdrowie. I trzymaj siê z dala od tych naukowców.}
{261} {} {Nie zniechêcaj siê, Rosalio. Do widzenia.}
{262} {} {Myœlê, ¿e i tak powinienem z nimi porozmawiaæ. Do widzenia.}
{263} {} {Moja praca dobieg³a koñca. Co z zap³at¹?}
{264} {} {Czego chcesz? Kapsli? Masz! WeŸ wszystko i zostaw mnie w spokoju! Wy, nieznajomi, myœlicie tylko o sobie...}
{265} {} {Nie denerwuj siê tak, kobieto.}