{100} {} {Widzisz Arthura Carringtona.}
{101} {} {Widzisz znajomego odkrywcê z Krypty 27.}

# Pierwszy dialog
{200} {} {Mi³o ciê znowu widzieæ, bohaterze.}
{1200} {} {Mi³o ciê znowu widzieæ, bohaterko.}
{201} {} {Widzê, ¿e ju¿ zadomowi³eœ siê w nowym miejscu. Czy mo¿esz mi poœwiêciæ chwilê?}
{202} {} {Tak?}
{203} {} {Do widzenia.}
{204} {} {Kolejne pytanie.}

{220} {} {Co tutaj robisz?}
{221} {} {Zaproponowano mi nauczanie dzieci czytania i pisania. To niezwyk³e prze¿ycie. I lepsze ni¿ wyg³upianie siê na plantacji. Nie pozwolono mi jednak jeszcze na bardziej powa¿ne badania. I strasznie mnie to denerwuje, poniewa¿ prowadzi³em ju¿ kilka powa¿nych projektów.}
{222} {} {Myœlê, ¿e z czasem siê dogadacie. Na razie zrelaksuj siê.}
{223} {} {Co myœlisz o Obserwatorach?}
{224} {} {Na pocz¹tku fascynowa³o mnie ich pragnienie wiedzy. Ale ich dobroæ jest po prostu szokuj¹ca. Nie mo¿esz pomoc ka¿demu z rzêdu i bezkrytycznie dzieliæ siê wiedz¹. Wiele osób po prostu na to nie zas³uguje. A jeœli na to zas³uguj¹, to z powodu w³asnej g³upoty nie s¹ w stanie odpowiednio rozporz¹dzaæ otrzyman¹ wiedz¹.}
{225} {} {Macie ró¿ne pogl¹dy na ten sam temat. To normalne.}