{100}{}{Widzisz Franka.}
{101}{}{Widzisz zrzêdliwego mê¿czyznê w stroju bojowym.}
{102}{}{Natychmiast od³ó¿ broñ.}
{103}{}{Natychmiast zdejmij tê zbrojê.}
{104}{}{Broñ! Od³ó¿ j¹!}
{105}{}{W mieœcie jest wrogo nastawiona osoba. Niech ka¿dy znajdzie os³onê!}

{200}{}{Czy coœ siê sta³o?}
{201}{}{Nie. A mia³o?}
{202}{}{Nie bêdê traciæ na ciebie czasu. Umiesz czytaæ? Wiêc zapamiêtaj zasady zapisane przy g³ównej bramie, a nic ci siê nie stanie.}
{203}{}{O tak, zasady...}
{204}{}{Mi³o ciê poznaæ, bracie! Gratulacje z powodu twojego awansu.}
{1204}{}{Mi³o ciê poznaæ, siostro! Gratulacje z powodu twojego awansu.}
{205}{}{Ty te¿ jesteœ z Bractwa?}
{206}{}{Zgadza siê. Zakon utrzymuje porz¹dek w tym mieœcie. Od czasu do czasu zatrzymuj¹ siê tu nasze patrole. Nie martw siê, to miejsce jest spokojne i bezpieczne. Niektórzy nasi wojownicy s¹ tu nawet wysy³ani na odpoczynek i leczenie. Na statku jak wiadomo warunki nie s¹ najprzyjemniejsze.}
{207}{}{Tak. Nie masz nic przeciwko, jeœli tu zostanê? Doskonale.}

{210}{}{S³ucham.}
{211}{}{S³ucham ciê uwa¿nie.}
{212}{}{Nadal tu jesteœ?}
{213}{}{Nie bêdê ju¿ przeszkadzaæ. Do widzenia.}

{220}{}{Mówi¹, ¿e na plantacjach gin¹ ludzie, a ty nic z tym nie robisz.}
{221}{}{Musi istnieæ dobry powód do takich twierdzeñ.}
{222}{}{Tak mówi¹ ludzie...}
{223}{}{Zapamiêtaj, nieznajomy, nie lubiê paniki i plotek szerz¹cych siê w moim mieœcie. Jeœli nie chcesz problemów, nie pogarszaj sprawy. To proste.}
{224}{}{Tak, rzeczywiscie. Nie chcê problemów.}
{225}{}{To samo dotyczy ciebie. Pamiêtaj – prêdzej czy póŸniej sprawiedliwoœæ dosiêgnie wszystkich.}

{230}{}{Czy noszenie broni jest tu nielegalne?}
{231}{}{Zgadza siê, jest to zabronione. I powinieneœ szanowaæ nasze prawa jak w³asn¹ matkê.}
{232}{}{To dlaczego Ty chodzisz z broni¹?}
{233}{}{Bo to ja ustalam tu zasady.}
{234}{}{Teraz rozumiem. Przepraszam za zadawanie g³upich pytañ. Mogê ju¿ iœæ?}
{235}{}{Jasne. To takie wygodne...}
{236}{}{Nie lubiê ciê. Idziesz tam, gdzie ciê nie zaproszono, i dodatkowo oœmielasz siê w¹tpiæ w nasze zasady. Ale dam ci wybór. Jeden z dwóch.}
{237}{}{Co to za wybór?}
{238}{}{Albo zaakceptujesz zasady i przestaniesz przeszkadzaæ innym. Albo wyœlê ciê do diab³a. Zastanów siê dobrze nad swoj¹ odpowiedzi¹.}
{239}{}{Jedyn¹ osob¹, która tu wszystkim przeszkadza, jesteœ ty. I zrobiê wszystko, by to zmieniæ.}
{240}{}{Dobrze. Dokonam wyboru. Najw³aœciwszego wyboru.}
{241}{}{Tak - zabronione. Ch³opi musz¹ wiedzieæ, kto jest ich panem. Tak, ty te¿ powinieneœ przestrzegaæ tych zasad.}
{242}{}{Oczywiœcie.}

{250}{}{Jakiœ problem? Dlaczego zak³ócasz spokój?}
{251}{}{Po prostu nie mogê spaæ. To sprawi³o, ¿e chcia³em pooddychaæ nocnym powietrzem.}
{252}{}{Nie mów do mnie. W czasie godziny policyjnej ka¿dy powinien spaæ we w³asnej norze. Dajê ci dwie minuty, ¿eby po³o¿yæ siê do ³ó¿ka i wyczo³gaæ siê z niego dopiero o szóstej rano.}
{253}{}{Tak zrobiê, sir. Nie ma problemu...}
{254}{}{Masz problem?}
{255}{}{Nie, nie mam.}
{256}{}{Jestem na patrolu. Jeœli nie masz dobrych powodów, lepiej w tym czasie nie wychodziæ na zewn¹trz. Mogê wzi¹æ ciê za z³odzieja lub pustynn¹ bestiê.}
{257}{}{Przepraszam, nied³ugo wyje¿d¿am.}
{258}{}{Znasz zasady. Nie wkurzaj mnie, to najwa¿niejsza.}
{259}{}{Przepraszam, nied³ugo wyje¿d¿am.}
{260}{}{To znowu ty. Omówiliœmy ju¿, czego nie robiæ w nocy. Wiêc w czym problem?}
{261}{}{Uch, to przez bezsennoœæ, sir. Przepraszam...}
{262}{}{Tak, stara³em siê byæ mi³y. Teraz czas ciê czegoœ nauczyæ. Bêdziesz siedzieæ w celi przez nastêpne dziesiêæ godzin i zastanowisz siê nad swoim zachowaniem. Ruszaj siê. I nie wa¿ siê ode mnie uciekaæ.}
{263}{}{W porz¹dku, proszê pana, nie bêdê siê opieraæ...}
{264}{}{Odwal siê!}
{265}{}{Mam tego doœæ!}
{266}{}{Ups...}
{267}{}{Odwal siê!}

{270}{}{No i jesteœ, szumowino. Dobrze - nie muszê ciê szukaæ. Myœlisz, ¿e tak po prostu uciekniesz przed prawem?}
{271}{}{Oczywiœcie. I nie jesteœ dla mnie przeszkod¹.}
{272}{}{Nic nie mo¿na ukryæ przed Zakonem. Jesteœ przestepc¹. Bractwo Stali domaga siê natychmiastowego postawienia ciê przed s¹dem. Masz jakieœ ostatnie s³owo? Nie, do diab³a. Nie masz do tego prawa...}
{273}{}{Ups...}
{274}{}{Nie wiem, co masz na myœli. Musisz mnie z kimœ myliæ...}
{275}{}{Mylisz mnie z kimœ innym. Jestem niewinny.}
{276}{}{Hmm, mo¿e. Chocia¿ opis trochê pasuje do ciebie. Dobra, na razie potraktujê ciê jako podejrzanego.}
{277}{}{Uch, uda³o siê...}

{280}{}{Mo¿esz mi opowiedzieæ o mieœcie?}
{281}{}{Powiem ci coœ o mieœcie, nieznajomy. Przestrzegaj zasad i nie denerwuj mieszkañców. Wtedy mo¿esz siê ustatkowaæ, jeœli chcesz. Ogólnie rzecz bior¹c, poza burmistrzem i wyznawcami lepiej nie komunikowaæ siê z nikim.}
{1281}{}{Powiem ci coœ o mieœcie, nieznajoma. Przestrzegaj zasad i nie denerwuj mieszkañców. Wtedy mo¿esz siê ustatkowaæ, jeœli chcesz. Ogólnie rzecz bior¹c, poza burmistrzem i wyznawcami lepiej nie komunikowaæ siê z nikim.}
{282}{}{Rozumiem.}
{283}{}{Kto tu rz¹dzi?}
{284}{}{Miastem rz¹dzi burmistrz Alvaro. Jest dalej w dó³ ulicy, w du¿ym budynku z ³ukiem.}
{285}{}{Rozumiem.}
{286}{}{Co robisz?}
{287}{}{Jestem komendantem tego miasta. Odpowiadam za bezpieczeñstwo i egzekwowanie prawa.}
{288}{}{Rozumiem. Zyczê dobrej s³u¿by.}
{289}{}{Wiêc jak tu siê ma ochrona?}
{290}{}{W porz¹dku.}
{291}{}{Naprawdê?}
{292}{}{Chêtnie wierzê.}
{293}{}{Prawo. Bezpieczeñstwo. Nudy. Chcê siê biæ!}
{294}{}{Hmm... Jest jedno cholerne miejsce, do którego nie chcesz iœæ. Chcê Ciê od razu ostrzec, ¿ebym nie musia³ Ciê póŸniej stamt¹d wyci¹gaæ.}
{295}{}{Powiedz mi o tym miejscu.}
{296}{}{To betoniarnia poza miastem i kamienio³om obok niej. Zak³ad zosta³ zamkniêty po tym, jak zaczeli tam znikaæ ludzie. Kr¹¿¹ ró¿ne plotki, ale nadal nikt nie jest pewny, co siê tam wydarzy³o.}
{297}{}{Rozumiem. Dziêki za ostrze¿enie.}

#El Gigante
{300}{}{O betoniarni.}
{301}{}{Tak?}
{302}{}{Proszê, nie mów mi wiêcej o tym przera¿aj¹cym miejscu.}
{303}{}{Rozwi¹¿ê ten problem za 300 kapsli.}
{304}{}{S³ysza³em ju¿ te s³owa od innych najemników. Jeœli ¿ycie jest ci cenne, trzymaj siê z dala od tego miejsca.}
{305}{}{Jednak spróbujê. Zabierz mnie teraz do tego miejsca.}
{306}{}{Byæ mo¿e pos³ucham twoich s³ów.}
{307}{}{W fabryce by³ potwór. Szpon œmierci. Uda³o mi siê go wykoñczyæ. By³ cholernie twardy...}
{308}{}{...Niech mnie diabli! Szpon œmierci? Tutaj? Jak daleko zasz³y te stworzenia.}
{309}{}{Ju¿ ci nie grozi.}
{310}{}{Dobra robota. Ca³e miasto jest twoim d³u¿nikiem. W porz¹dku, pójdê teraz po nagrodê ze skarbca miasta.}
{311}{}{Dziêkujê.}
{312}{}{Sk¹d wiesz o szponach?}
{313}{}{S³ysza³em o nich na treningu, ale sam nigdy takiego nie spotka³em. Weterani mówili, ¿e szpony ¿yj¹ w górach na zachodzie, gdzie prawie nikt nie mieszka.}
{314}{}{Ciekawe.}
{315}{}{Znam tylko jeden przypadek, w którym szpony znajdowa³y siê w œrodku miasta i robi³y du¿o ha³asu. To by³o w Gruzowisku. Tam, w opuszczonej piwnicy, mieszka³a ich matka. Z³o¿y³a nawet jaja. Ale jeden dzielny najemnik znalaz³ je, zastrzeli³ i rozbi³ jaja. A¿ strach pomyœleæ, co by siê sta³o, gdyby te stwory siê wyklu³y.}
{316}{}{Co za horror.}
{317}{}{Dobra robota, wojowniku. Powinienes s³u¿yæ w naszych szeregach.}
{318}{}{Pa.}
{319}{}{Nie po drodze mi ze szko³¹. Gdzie to by³o?}
{320}{}{Jestem paladynem Bractwa Stali. Nasza lokalna baza znajduje siê w Puerto Peñasco, a nasza siedziba znajduje siê daleko w Kalifornii. To tam zapozna³em siê z podstawami, dopóki nie zg³osi³em siê na ochotnika do misji na tej pustynii.}
{321}{}{Wow. Bêdê wiedzia³.}
{322}{}{Chcê ci pomóc z tym problemem. Poka¿esz mi to miejsce?}

#Maly palec
{330}{}{Chodzi o Pinkyego. Mówi¹, ¿e chcesz go zabiæ.}
{331}{}{Chip powinien uwa¿aæ na jêzyk i nie rozmawiaæ z obcymi. Nie jestem krwio¿erczy. Ale mam misjê - zapewniæ bezpieczeñstwo w mieœcie. Formalnie nie ma jeszcze powodu do eksterminacji tej ma³ej œwini. Ale niech znajdzie siê chocia¿ jeden powód, a rozpocznie swoj¹ wielk¹ szczurz¹ podró¿ do nieba.}
{332}{}{Dlaczego tak bardzo go nie lubisz?}
{333}{}{Teraz to tylko nieszkodliwe piskle, ale co siê stanie, kiedy doroœnie i poczuje krew? Kretoszczury s¹ agresywnymi drapie¿nikami i nie ma dla nich miejsca wsród ludzi.}
{334}{}{Hmm.}
{335}{}{Twoje stanowisko jest jasne. Nie mog³o byæ jaœniej.}
{336}{}{Co ciê obchodzi ta œwinia? Oczywiœcie tak tylko pytam. Mam sugestie. Zap³acê 30 kapsli, jeœli skoñczysz z t¹ besti¹. Co na to powiesz?}
{337}{}{Nie ma mowy. Nie chcê skrzywdziæ nastolatka.}
{338}{}{Wina Chipo! Do domu nie by³o nic, co mog³oby wprowadziæ kociaka. Alvaro brakowa³o te¿ ducha i odwagi, by wszystko umieœciæ na swoim miejscu. Szkoda. Szkoda, ¿e wokó³ s¹ tylko s³abeusze.}
{339}{}{Do widzenia, komendancie.}
{340}{}{To nie potrwa d³ugo. Policz kapsle, kolego.}
{341}{}{Liczê na ciebie.}
{342}{}{Do zobaczenia, komendancie.}
{343}{}{Ten œwiniak to ju¿ przesz³oœæ.}
{344}{}{Chip musia³ bardzo to prze¿yæ. Szkoda, ale to jego wina. Ta strata wyjdzie mu na dobre.}
{345}{}{Tak jak mówisz.}
{346}{}{Upewnij siê, ¿e wnioski z lekcji s¹ prawid³owe.}
{347}{}{Masz dobry chwyt. Nadal mo¿esz siê przydaæ. Oto 30 kapsli, tak jak obieca³em.}
{348}{}{Do zobaczenia póŸniej, komendancie.}

{350}{}{S³uchaj, naprawdê muszê wiedzieæ, czy by³ tu niejaki Tin-Tan?}
{351}{}{Tin-Tan? Wygl¹da mi to na pseudonim. Czy znasz jego prawdziwe imiê?}
{352}{}{German Genaro Cipriano Gomez Valdez y Castillo. Jecha³ dyli¿ansem z Phoenix.}
{353}{}{Przejrzê dziennik migracji... Poczekaj chwilê. Nie mam ¿adnych zapisów, ¿eby odwiedza³ Casa Nueva.}
{354}{}{A co z dyli¿ansem Sonora Express?}
{355}{}{Chwileczkê... Tak, mam to imiê, ale... Mam zapis, ¿e ca³y dyli¿ans zgin¹³ z r¹k bandytów, zanim do nas dotar³.}
{356}{}{Có¿, niefortunny los. Dziêki, Kapitanie.}
