{100} {} {Widzisz pracownika.}
{101} {} {Widzisz mê¿czyznê w roboczym ubraniu. Wygl¹da na zmêczonego.}

{110} {} {Wiêc to z twojego powodu jestem zmuszony tutaj pracowaæ?}
{111} {} {Gdyby nie ty, nie zosta³bym wys³any do tej ciê¿kiej pracy.}
{112} {} {Administrator jest w tym budynku.}
{113} {} {Czy wiesz, jak uciec od tej ciê¿kiej pracy?}
{114} {} {Wielu ludzi tutaj pracuje wbrew swojej woli. Reszta - za ¿ebracz¹ pensjê.}
{115} {} {Te¿ chcesz zepsuæ to gówno?}
{116} {} {Podobno mieszka³ tu potwór. Módlcie siê, aby by³ jedynym.}
{117} {} {Jeœli ten potwór pojawi siê tu ponownie, na pewno natychmiast mnie zabije.}
{118} {} {Zapotrzebowanie na beton i ceg³y jest ogromne.}
{119} {} {Mamy tu du¿o pracy. Pracujemy przez to na trzy zmiany.}
