{100} {} {Widzisz kierownika.}
{101} {} {Widzisz mê¿czyznê w ubraniu roboczym.}

{200} {} {Ach, oto nasz bohater. Wiem, wiem, to twoje dzie³o, prawda? Ca³e miasto jest Ci wdziêczne.}
{1200} {} {Och, oto nasza bohaterka. Wiem, wiem, to twoje dzie³o, prawda? Ca³e miasto jest Ci wdziêczne.}
{201} {} {Widzê, ¿e nie marnowaliœcie czasu.}
{202} {} {Robiliœmy tu beton i ceg³y, dopóki nie pojawi³ siê El Gigante. Zabi³ wielu pracowników, wiêc zak³ad musia³ zostaæ zamkniêty. Có¿, teraz potwora nie ma - wracamy do pracy.}
{203} {} {Rozumiem.}
{204} {} {WejdŸ, zawsze dobrze mieæ w pobli¿u tak pracowitych ludzi.}
{205} {} {Muszê ju¿ iœæ.}
{206} {} {Rozumiem.}

{210} {} {Ile p³acisz pracownikom?}
{211} {} {To s¹ g³ównie skazañcy i niewolnicy. Maj¹ wystarczaj¹co du¿o wody, jedzenia i odzie¿y roboczej. S¹ tu te¿ wolni najemnicy, ale jest ich niewielu.}
{212} {} {Dlaczego komuœ mia³oby zale¿eæ na tym miejscu?}
{213} {} {Nie znam ¿adnych innych dzia³ajacych zak³adów betoniarskich. Zadnych! Kiedy ktoœ chce zbudowaæ dom, wyci¹ga ceg³y ze starych ruin. Tylko my w Casa Nueva budujemy domy od podstaw.}
{214} {} {Sprzedajesz cement i ceg³y?}
{215} {} {Pocz¹tkowo zak³ad obs³ugiwa³ tylko kolonie Casa Nueva, ale teraz transportujemy te¿ materia³y na place budowy w Puerto i Tu-San. Wkrótce zorganizujemy te¿ dostawê do Phoenix, jeœli wszystko pójdzie dobrze z lokalnymi w³adzami. Najpierw jednak musimy przywróciæ normalny tryb pracy.}