{100} {} {Widzisz system gazu.}
{101} {} {Widzisz system butli gazowych i rur z wylotem do wentylacji. Wygl¹da na to, ¿e jest to czêœæ lokalnego zarz¹dzania klimatem.}
{102} {} {To jest czêœæ lokalnego systemu klimatycznego. Obok znajduje siê tabliczka z napisem „Uwaga! Materia³ wybuchowy”.}
{103} {} {System nie dzia³a prawid³owo i ma zamiar spaliæ wszystko dooko³a.}
{104} {} {To nic nie da. System nie dzia³a prawid³owo i ma zamiar spaliæ wszystko dooko³a.}
{105} {} {P³oñ! P³oñññ!}
{106} {} {Awaria systemu. Jeszcze trochê, a wybuchnie po¿ar...}
