{100} {} {Widzisz panel kontroli.}
{101} {} {Widzisz panel sterowania wentylacj¹ w szklarni.}
{102} {} {Nie dzia³a.}

{110} {} {System klimatyczny nie dzia³a. Prawdopodobnie jest pozbawiony energii.}
{111} {} {System klimatyczny dobrze spe³nia swoje zadanie.}
{112} {} {W³¹czasz wentylacjê w œrodkowej kopule.}
{113} {} {W³¹czasz wentylacjê we wschodnich szklarniach.}
{114} {} {W³¹czasz wentylacjê w zachodnich szklarniach.}
