{100} {} {Widzisz komputer laboratoryjny.}
{101} {} {To jest komputer laboratoryjny.}
{102} {} {Komputer nie uruchamia siê z powodu przerwy w zasilaniu.}
{103} {} {Nie w³¹cza siê.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Dalej.}
{204} {} {Wróæ do menu g³ównego.}

{210} {} {notatki badawcze Wang Chuna.}
{211} {} {"Cel badañ na najbli¿sze piêæ lat: Stworzenie suchych, a jednoczeœnie owocnych upraw nadaj¹cych siê do masowej uprawy. To rozwi¹¿e problem ¿ywnoœciowy w Arizonie i Kalifornii, z którym boryka siê dzisiejsza rosn¹ca populacja."}
{212} {} {Podstawa materia³owa eksperymentu.}
{213} {} {„Prace s¹ prowadzone na bazie dobrze zachowanego laboratorium Greenway Hydroponics, w którym prowadzono ró¿ne eksperymenty, aby stworzyæ roœliny odporne na susze i promieniowanie przed Wielk¹ Wojn¹. Tutaj przygotowano materia³y, które by³y zawarte w standardowym zestawie schronienia Vault-Tec dla przetrwania populacji po wojnie nuklearnej. "}
{214} {} {Dalej.}
{215} {} {"Laboratorium zachowa³o: sprzêt roboczy, automatyczny sprzêt hydroponiczny, nasiona ró¿nych roœlin i grzybów nie zepsute przez promieniowanie, bogat¹ dokumentacjê laboratoryjn¹ i przedwojenn¹ literaturê, a tak¿e ró¿norodn¹ gamê chemikaliów, dodatków biologicznych i wirusy. ”}
{216} {} {Zadania projektowe.}
{217} {} {"Pierwszym zadaniem jest zbadanie bazy naukowej i materia³owej Greenway Hydroponics w celu przywrócenia dzia³ania kompleksu i laboratorium. Wœród lokalnych opracowañ znajduj¹ siê gotowe rozwi¹zania, które mo¿na wykorzystaæ na potrzeby Casa Nueva. ”}
{218} {} {Dalej.}
{219} {} {"Drugim zadaniem jest hodowla roœlin wy³¹cznie w celu zwiêkszenia zapasów nasion. Prace powinny byæ wykonywane w izolowanych szklarniach kompleksu, aby stworzyæ najbardziej czyste i komfortowe œrodowisko."}
{220} {} {Dalej.}
{221} {} {"Trzecie zadanie to wyhodowanie nowych odmian nadaj¹cych siê do przetrwania na piaskach pustyni Sonora i na radioaktywnych pustkowiach Kalifornii."}
{222} {} {Wa¿na uwaga.}
{223} {} {"Jednym z wa¿nych warunków eksperymentu jest stymulacja wzrostu roœlin, zw³aszcza ich systemu korzeniowego. Proponowane s¹ ró¿ne metody tej stymulacji: dodatki biologiczne, napromienianie, zarodniki grzybów, a nawet wirusy z zasobów Greenway Hydroponika. W celu zwiêkszenia bezpieczeñstwa dostêp do laboratorium powinien byæ œciœle ograniczony. "}
{224} {} {Kopiuj dane badawcze.}
{225} {} {Archiwa zosta³y pomyœlnie skopiowane na holodysk.}
