{110} {} {Nie wymaga naprawy.}
{111} {} {Brak w magazynie.}
{112} {} {Nie masz pojêcia, jak to dzia³a.}
{113} {} {Ta jednostka jest dostrojona tylko do dojrza³ych liœci agawy.}
{114} {} {Ta maszyna s³u¿y do robienia soku z agawy, a nie na odwrót.}

{120} {} {Przygotowano jedn¹ butelkê soku z agawy.}
{121} {} {Przygotowano dwie butelki soku z agawy.}
{122} {} {Przygotowano trzy butelki soku z agawy.}
{123} {} {Przygotowano cztery butelki soku z agawy.}
{124} {} {Przygotowano piêæ butelek soku z agawy.}
{125} {} {Przygotowano szeœæ butelek soku z agawy.}
{126} {} {Przygotowano siedem butelek soku z agawy.}
{127} {} {Przygotowano osiem butelek soku z agawy.}
{128} {} {Przygotowano dziewiêæ butelek soku z agawy.}
{129} {} {Przygotowano dziesiêæ butelek soku z agawy.}