{100} {} {Widzisz laboratorium.}
{101} {} {Widzisz laboratorium chemiczne. Mo¿e uda siê coœ tutaj zrobiæ.}
{102} {} {Widzisz laboratorium chemiczne. Praca z nim wymaga nauk œcis³ych.}
{103} {} {Komponent jest przygotowywany do procesu chemicznego i ³adowany do specjalnego naczynia.}
{104} {} {Do zakoñczenia procesu chemicznego s¹ wymagane komponenty.}
{105} {} {Stworzono truciznê. W³aœnie tego potrzebuj¹ Obserwatorzy.}
{106} {} {Aby prawid³owo przygotowaæ truciznê potrzeba danych laboratoryjnych.}
{107} {} {Nie ma tu nic innego do roboty.}
{108} {} {Wymagane s¹ czêœci i instrukcje.}
{109} {} {Potrzebujê instrukcji.}
{110} {} {Gotowe.}
