{100} {} {+}
{101} {} {-}

# Uzywajac rêcznie
{110} {} {Bez zasilania motor nigdzie nie pojedzie.}
{111} {} {Cholera, zasilacz wymaga na³adowania.}
{112} {} {Motor siê nie uruchamia. Komputer pok³adowy jest zablokowany i wymaga klucza dostêpu.}
{113} {} {Hmm, myœlê, ze potrzebujê tutaj klucza.}
{114} {} {To nie jest dobry czas na podró¿owanie.}
{115} {} {Mam niedokoñczone sprawy.}
{116} {} {Kradniesz motor bandytom! Raczej im siê to nie spodoba.}
{117} {} {Motocykl mo¿e pomieœciæ tylko dwóch pasa¿erów.}

# Korzystanie z przedmiotów
{200} {} {Dostêp przyznany. Motocykl jest teraz gotowy do jazdy.}
{201} {} {To nie ma sensu.}
{202} {} {Ten pojazd jest ³adowany przez coœ innego.}
{203} {} {Motocykl nie potrzebuje jeszcze smarowania.}
{204} {} {Motocykl nie wymaga jeszcze wymiany.}
{205} {} {Komputer pok³adowy nie wymaga jeszcze naprawy.}
{206} {} {Ta czaszka bêdzie wspania³¹ ozdob¹ twojej kierownicy. I da znaæ innym, ¿e nie warto z tob¹ zadzieraæ.}
{207} {} {Nie mo¿esz tego zrobiæ, dopóki motocykl nie bêdzie twój.}
{208} {} {Kierownica jest ju¿ ozdobiona jedn¹ czaszk¹.}
{209} {} {Naprawiono zepsuty reflektor. Teraz oœwietli Ci on drogê.}
{210} {} {Ten motocykl ma sprawne wszystkie reflektory.}
{211} {} {To dotyczy bardziej baga¿nika.}

# Korzystanie z umiejêtnoœci
{300} {} {Nie ma tu nic do zhakowania.}
{301} {} {Komputer pok³adowy jest ju¿ pod Twoj¹ kontrol¹.}
{302} {} {To dla ciebie za trudne. Spróbuj znaleŸæ klucz.}
{303} {} {Nie ma tu nic do naprawienia.}
{304} {} {Nie ma tu nic do naprawienia. Jednak jeszcze nie spojrza³eœ na baga¿nik.}
{305} {} {Nie mo¿esz naprawiæ tego motoru, dopóki nie jest twój.}
