# Korzystanie z przedmiotów
{200} {} {To nie dotyczy tego. Wybróbuj tego na motocyklu.}
{201} {} {Wymieniaj¹c stary uchwyt, uda³o siê zwiêkszyæ pojemnoœæ baga¿nika o 5 jednostek.}
{202} {} {Lina mocuj¹ca zosta³a ju¿ wymieniona. Nie ma sensu robiæ tego ponownie.}
{203} {} {To jest prawie niemo¿liwe podczas walki.}
{204} {} {Zainstalowano nowy sprzêt. Motor ma teraz wiêksz¹ ³adownoœæ.}
{205} {} {Na motocyklu nie ma ju¿ miejsca na dodatkowe schowki.}
{206} {} {Ten motor nie nale¿y do ciebie.}

# Korzystanie z umiejêtnoœci
{300} {} {Nie ma tu nic do zhakowania.}
{301} {} {Po dok³adnym zmierzeniu pnia dochodzisz do wniosku, ze jego objêtoœæ jest równa }
{302} {} { jednostki.}
{303} {} {Ta skrzynia baga¿owa nie bêdzie lepsza dziêki tej umiejêtnoœci.}
{304} {} {Nie ma tu nic do naprawienia.}
{305} {} {Nie mo¿esz naprawiæ tego motoru, dopóki nie jest twój.}
{306} {} {Po naprawach pojemnoœæ baga¿nika wzros³a o 5 jednostek.}
