{100} {} {}
{101} {} {}
{102} {} {! Cheat: Voluminous Heads On.}
{103} {} {! Cheat: Voluminous Heads Disabled.}

# Stosowanie elementów na GG
{110} {} {Interesuj¹ca rzecz. Warto poszukaæ dla niej zastosowania.}
{111} {} {Tych rzeczy najlepiej u¿ywaæ, gdy wychodzisz na zewn¹trz.}
{112} {} {Mi³o by³oby zap³aciæ sobie. Ale to bezcelowe.}
{113} {} {Otrzymano jednego kapsla.}
{114} {} {Lepiej by³oby sprzedaæ to pocz¹tkuj¹cym z miasta.}
{118} {} {U¿yj tego przedmiotu z rêki.}
{119} {} {U¿yj tego przez swój plecak lub z rêki.}

{120} {} {Na widok tych bezu¿ytecznych œmieci, mimowolnie masz pomys³... pomys³ spalenia tego œwiata w nowej wojnie atomowej.}
{121} {} {Ta aktualizacja dotyczy tylko jednostki LUN ZAX.}
{122} {} {Nie wygl¹da na to, ¿ebyœ by³ bomb¹ atomow¹.}
{123} {} {Te has³a powinny byæ u¿ywane na komputerach i innych systemach elektronicznych.}
{124} {} {Podar³eœ ten list, próbuj¹c zapomnieæ o wszystkim, co ³¹czy³o ciê z sekt¹ czcz¹c¹ ogieñ.}
{125} {} {Ten list ma byæ pokazany Straznikom Ognia w Phoenix.}
{126} {} {Przeklêci kultyœci...}
{127} {} {Nie chce wiêcej o nich nawet myœleæ.}
{128} {} {Picie tego czystego p³ynu doprowadzi tylko do rozstroju ¿o³¹dka.}
{129} {} {Hej, uwa¿aj! Prawie odr¹ba³eœ sobie g³owê.}
{1129} {} {Hej, uwa¿aj! Prawie odr¹ba³aœ sobie g³owê.}

{130} {} {Podpalanie w³osów to nie jest dobry pomys³.}
{131} {} {Zmieniono buty. Mo¿esz teraz bezpiecznie chodziæ po pal¹cych siê i ¿r¹cych substancjach. Co prawda, tylko kilka minut.}
{132} {} {Nie jest to jeszcze konieczne, poniewa¿ stare buty s¹ w doskona³ym stanie.}
{133} {} {Nie jest to jeszcze konieczne, poniewa¿ stare okulary nadal dzia³aj¹.}
{134} {} {Noszenie tych dziwnych okularów sprawia, ¿e czujesz siê, jakbyœ wkracza³ w inny wymiar.}
{135} {} {Bateria okularów elektronicznych jest wyczerpana. Noktowizor jest wy³¹czony.}
{136} {} {WeŸ okulary do rêki, aby poczuæ siê atrakcyjniejszym.}
{1136} {} {WeŸ okulary do rêki, aby poczuæ siê jak prawdziwa fashionistka.}
{137} {} {To nie jest jeszcze konieczne, poniewa¿ noszenie maski gazowej za³atwia sprawê.}
{138} {} {Zmieniono maskê przeciwgazow¹. Przez chwilê ochroni Ciê ona przed szkodliwym gazem i py³em.}
{139} {} {Tak, za³ó¿ to na g³owê i przestrasz dzieciaki z okolicy. Bêdzie fajnie.}

# Resetowanie elementów
{140} {} {Cz³onkowie Twojej rodziny nie byliby zadowoleni, s³ysz¹c, ¿e rzucasz rodzinnymi pami¹tkami.}
{141} {} {Zebracy bêd¹ zachwyceni, gdy znajd¹ twoje kapsle.}
{142} {} {Myœl¹c o sobie jako filantropie, hojnie rzucasz pieni¹dze na wiatr.}
{143} {} {Te sanda³y pomog¹ ci przetrwaæ podró¿ po ¿r¹cych substancjach, ale tylko przez krótki czas.}
{144} {} {Wabik zainstalowany.}

# Ró¿ne repliki
{150} {} {Czujesz lekkie ciep³o pochodz¹ce z jakiegoœ radioaktywnego przedmiotu w twoim plecaku.}
{151} {} {Twój Pip-Boy jest nara¿ony na promieniowanie:}
{152} {} {Nie mo¿na tego zrobiæ podczas walki.}
{153} {} {Raz, dwa, radio dzia³a.}
{154} {} {Twoje nogi nie wytrzymaj¹ ogromnego ciê¿aru plecaka.}
{155} {} {Co za ból!}
{156} {} {Nie rób tego.}
{157} {} {To mo¿e byæ niebezpieczne! Twoja lekkomyœlnoœæ prawie zabi³a twoj¹ postaæ. I jak zdenerwowana by³aby babcia Adonsia...}
{158} {} {Powinieneœ poszukaæ bardziej niezawodnych butów. Te mo¿na ju¿ sprzedaæ na najbli¿szym targu.}
{159} {} {Bêdziesz potrzebowa³ sto³u warsztatowego, aby zdemontowaæ ten element.}
{160} {} {Musisz zebraæ WSZYSTKIE fragmenty mapy.}
{161} {} {Zebrano wszystkie fragmenty mapy skarbów. Wygl¹da na to, ¿e jest pochowany w pobli¿u ruin miejscowej latarni morskiej.}

# Osiagniecia
{200} {} {Twoja reputacja roœnie.}
{201} {} {Twój rozg³os roœnie.}
{202} {} {Wysoka dawka promieniowania trwale obni¿a twoje zdrowie.}
{203} {} {Wysoka dawka promieniowania trwale obni¿a twoje zdrowie. Znowu.}
{204} {} {Coraz gorzej.}
{205} {} {ZNACZNIE gorzej.}
{206} {} {Za du¿¹ liczbê odniesionych obra¿eñ w walce otrzymujesz tytu³ „Zahartowany Bojownik”.}
{207} {} {Wydaje mi siê, ³e przyzwyczajam siê ju¿ do tego bólu.}
{208} {} {Za twoj¹ nikczemn¹ zdradê zosta³eœ pozbawiony wszystkich tytu³ów w Bractwie Stali.}
{209} {} {Zosta³eœ wyrzucony z Rangersów za swoj¹ nikczemn¹ zdradê.}
{210} {} {Za twoj¹ nikczemn¹ zdradê zosta³eœ wyrzucony ze sk³adu.}
{211} {} {Za swoj¹ nikczemn¹ zdradê zosta³eœ wyrzucony z Kultu Ognia.}
{212} {} {Zas³u¿y³eœ na tytu³ Pokojowego Wêdrowca po tak d³ugiej podró¿y.}
{213} {} {Tytu³ Pokojowego Wêdrowca przepad³. Ale mo¿e jeszcze nie jest za póŸno, aby powróciæ na praw¹ œcie¿kê.}