{100} {} {Widzisz ostry cieñ mg³y.}
{101} {} {Widzisz oszpeconego mê¿czyznê o bladej skórze. Wydaje siê szalony i agresywny.}
{102} {} {?}
{103} {} {Nie chcê ciê zabijaæ. Nie zmuszaj mnie do tego.}

#Dialog
{200} {} {(id¹c wzd³u¿ pla¿y, czujesz, ¿e ktoœ na ciebie patrzy; patrz¹c wstecz, od razu zauwa¿asz blady cieñ z par¹ œwiec¹cych oczu; po chwili cieñ zaczyna siê niebezpiecznie poruszaæ)}
{201} {} {Stop! Nie skrzywdzê ciê...}
{202} {} {Kim do diab³a jesteœ?}
{203} {} {Stop! Nie odejdziesz, suko!}

{210} {} {(Wszystko, co s³yszysz w odpowiedzi, to krótkie, z³owieszcze drwiny; nagle cieñ rzuca siê ostro...)}
{211} {} {Ach...}
{212} {} {(s³yszysz krótki, z³owieszczy œmiech; zaraz potem pojawia siê mê¿czyzna ze zniekszta³conym cia³em i blad¹ skór¹; jego g³odne oczy wydaj¹ siê patrzeæ na ciebie) Z-¿a³osny cz³owiek.}
{213} {} {Spójrz, ty i ja jesteœmy do siebie podobni. Spójrz na mnie, na moj¹ twarz... Ludzie na górze œmiej¹ siê z mojego wygl¹du.}
{214} {} {O czym ty mówisz?}
{215} {} {(szyderczo) G³upi cz³owieku. Nie opieraj siê.}
{216} {} {Uch...}
{217} {} {Smiej¹ siê, co? To prawda. Pamiêtam. Ludzie. S³oñce. Wiele z³ych s³ów...}
{218} {} {Tak, tam jest okropnie. Wszyscy s¹ tacy Ÿli.}
{219} {} {Wygl¹da na to, ¿e dobrze to zrozumia³eœ.}
{220} {} {Myœleli, ¿e nie prze¿yjê. Ale nie, nie. (œmiech) G³upi ludzie.}
{221} {} {Wiêc ludzie z góry przywieŸli ciê tutaj?}
{222} {} {(zmienia twarz z gorzkimi wspomnieniami) Wojna... Bomby... (obna¿a zêby, œciskaj¹c g³owê) Pamiêtam! Domy w ogniu. Ludzie p³on¹. Jêki. Krzyki. Jestem tutaj, aby przetrwaæ...}
{223} {} {S³uchaj, to by³o dawno temu, prawda?}
{224} {} {Teraz rozumiem, dlaczego tak wygl¹dasz.}
{225} {} {(gwa³townie siê rozgl¹da) Lily! Zgubi³a siê... (³apie siê za g³owê, ale nagle coœ sobie przypomina) Nie, nie, ona nie ¿yje. Zabi³em j¹... Tak. Cierpia³a... Zrobi³em, co musia³em. Lily! Lily! (ucieka z krzykiem „Lily!”)}
{226} {} {Uh, czeœæ, panie *ocala³y*.}
{227} {} {Dobra, wynoœ siê st¹d idioto.}