{100} {} {Widzisz naukowca atomowego.}
{101} {} {Widzisz mê¿czyznê ze spalon¹ skór¹. Ma na sobie znoszone ubranie robocze z przedwojennym symbolem.}
{102} {} {No có¿, oto nasz g³ówny szkodnik. Wynoœ siê st¹d, póki masz nietkniête nogi.}

{110} {} {Cœœ, bo ktoœ z zewn¹trz us³yszy.}

{200} {} {Hej hej w³óczêgo. Nieznajomi s¹ tu rzadko wpuszczani, dlatego pilnuj siê.}
{201} {} {Masz przepustkê? Zreszt¹, niewa¿ne.}
{202} {} {Tak, rozejrzyj siê. To miejsce jest bardzo interesuj¹ce.}
{203} {} {Co tak wêszysz?}
{204} {} {Huh? Mów g³oœniej, jestem g³uchy.}
{205} {} {Brak wjazdu na stacje. Ale Ty mo¿esz przejœæ.}
{206} {} {Dziwne, ¿e pozwolono ci wejœæ. Wiesz, wszyscy ci rasiœci...}
{207} {} {Przed wojn¹ tak nie wygl¹daliœmy, kochanie.}
