{100} {} {Widzisz mnicha.}
{101} {} {Widzisz mê¿czyznê w sutannie. To oczywiœcie nie przypadek, ¿e tu jest.}
{102} {} {Twoje miejsce jest na pustyni, dzikusie.}
{1102} {} {Twoje miejsce jest na pustyni, dzikusie.}
{103} {} {Swiêty ogieñ Ciê b³ogos³awi.}
{104} {} {Przebywaj¹c tutaj, ryzykujesz ¿ycie.}

{200} {} {Pozdrowienia, mi³a osobo. Czy mogê wiedzieæ, jak to siê sta³o, ¿e natrafi³eœ na atomowych lobbystów?}
{201} {} {Nawet nie wiem. Chyba przypadek. A co Ty tutaj robisz?}
{202} {} {Och, jestem tylko spokojnym pielgrzymem z koœcio³a Swiêtego Ognia. Nasza religia czci star¹ wiedzê i stara siê o¿ywiæ œwiat. Ta elektrownia j¹drowa jest bardzo wa¿na dla naszej misji. Szkoda, ¿e wpad³a w niepowo³ane rêce.}
{203} {} {Myœlê, ¿e nie masz siê czego baæ. Teraz Ralph jest na czele stacji. Zamierza renegocjowaæ kontrakt z koœcio³em. Bêdziesz szczêœliwy.}
{204} {} {Chwa³a atomowi! Czy to tobie nale¿y za to dziêkowaæ? Z twoj¹ pomoc¹ œwiat staje siê coraz lepszy. Dziêkujê, nieznajomy. OdwiedŸ nasz koœció³ w odpowiednim czasie.}
{1204} {} {Chwa³a atomowi! Czy to tobie nale¿y za to dziêkowaæ? Z twoj¹ pomoc¹ œwiat staje siê coraz lepszy. Dziêkujê, nieznajoma. OdwiedŸ nasz koœció³ w odpowiednim czasie.}
{205} {} {Jasne. PA.}

{250} {} {Wiêc to przez ciebie zawali³y siê nasze plany, tak jak Stary Swiat? Dlaczego to robisz?}
{251} {} {Nie lubiê was.}
{252} {} {Nie podoba ci siê pomys³ Odrodzenia? A mo¿e nie podoba ci siê nasz koœció³ z jego symbolami? W obu przypadkach jesteœ po prostu egoist¹. Atomow¹ nieistotnoœci¹ z przesadn¹ zarozumia³oœci¹. Koœció³ da³ œwiatu Wiedzê. Z jego pomoc¹ zapaliliœmy œwiat³a w domach i nauczyliœmy niektórych czytaæ i pisaœ. A ty? Co starasz siê osi¹gn¹æ?}
{253} {} {Z powodu twojego "odrodzenia" mój dom zosta³ zaatakowany. Wystarczy.}
{254} {} {Och, wiêc mamy do czynienia z zemst¹, jakie to zwierzêce. W takim razie nie mamy ju¿ o czym rozmawiaæ. Zwierzêta nie rozumiej¹ mowy, rozumiej¹ tylko bicz. Wracaj na pustyniê i ¿yj dzikim ¿yciem jak dziki. W Nowym Swiecie nie ma miejsca dla ludzi takich jak Ty.}
{255} {} {Nie zanim nie zrobiê z ciebie mielonki, œwiêty.}
{256} {} {Bardzo chêtnie. Nie chcê ju¿ wiêcej widzieæ na oczy tej ca³ej twierdzy grzechu.}
{257} {} {Ralph p³aci³ za ma³o.}
{258} {} {Czyli to kapsle by³y dla ciebie doradc¹? W takim wypadku jesteœ zwyk³ym egoist¹. Koœció³ da³ œwiatu Wiedzê. Z jego pomoc¹ zapaliliœmy œwiat³a w domach i nauczyliœmy niektórych czytaæ i pisaœ. A co da garœæ kapsli w twojej kieszeni temu miastu?}
{259} {} {Po prostu interesuje mnie dobry interes. To uczciwa umowa.}
{260} {} {Mo¿e. Byæ mo¿e Stary Swiat upad³ z powodu waszej chciwoœci. Dlatego w Nowym Swiecie nie ma miejsca dla ludzi takich jak ty. Od teraz Twoja obecnoœæ w mieœcie nie podoba siê Koœcio³owi Ognia. Dla ka¿dego bêdzie lepiej, jeœli odejdziesz.}
{261} {} {Nie zanim Ciê nie za³atwiê.}
{262} {} {Bardzo chêtnie. I tak nie chcê ju¿ d³u¿ej przebywaæ w tak niesprawiedliwym mieœcie.}
{263} {} {Ju¿ jesteœ trupem.}
