{100} {} {Widzisz Ralpha.}
{101} {} {Widzisz mê¿czyznê ze spalon¹ skór¹. Ma na sobie znoszone ubranie robocze z przedwojennym symbolem.}
{102} {} {Nie robiê interesów ze zdrajcami.}
{103} {} {Dziêkujê za pomoc. By³a bardzo przydatna.}

{200} {} {Czekaj, obcy nie mog¹ iœæ dalej. Czego potrzebujesz?}
{201} {} {Myœla³em, ¿e to miejsce zosta³o opuszczone dawno temu. Co Ty tutaj robisz?}
{202} {} {Jesteœmy tu od lat. I ca³e miasto o tym wie. Wiêc nie polecam ju¿ k³amaæ.}
{203} {} {Ale ja nie jestem miejscowy. Pochodzê z wioski na pó³nocny wschód st¹d.}
{1203} {} {Ale ja nie jestem miejscowa. Pochodzê z wioski na pó³nocny wschód st¹d.}
{204} {} {Och, to niespodzianka. Naprawdê, nie wygl¹dasz na zwyk³ego mieszkañca miasta - masz opalon¹ skórê, niezwyk³y akcent. Ciekawe...}
{1204} {} {Och, to niespodzianka. Naprawdê, nie wygl¹dasz na zwyk³ego mieszkañca miasta - masz opalon¹ skórê, niecodzienny akcent. Ciekawe...}
{205} {} {Hmm. Po prostu odejdê.}
{206} {} {Co tu siê dzieje?}
{207} {} {Dobra, s³uchaj, mamy tu nag³y wypadek. Mo¿e mo¿esz nam pomóc. IdŸ do menad¿era, a nastêpnie - postêpuj zgodnie z ustaleniami.}
{208} {} {Dobrze.}

{210} {} {Czekaj, co... Czy to makija¿?}
{211} {} {To prawdziwa skóra. Trochê zielona, ale mo¿na ¿yæ.}
{212} {} {Zartujesz sobie?}
{213} {} {Mówiê prawdê. To wszystko za spraw¹ eksperymentów w Inferno. To prawdziwi szaleñcy.}
{214} {} {Cholera, to prawda. Ju¿ nie pamiêtam, jak wygl¹da³em przed Przemienieniem. Musi byæ tak, ¿e po prostu ciebie to ominê³o. W ka¿dym razie, mi³o ciê poznaæ.}
{215} {} {Ach, w porz¹dku. Chyba ju¿ pójdê.}
{216} {} {Wzajemnie. Wiêc mieszkasz tutaj?}
{217} {} {Nigdy siê nie przedstawi³em. Mam na imiê Ralph. Mo¿na powiedzieæ, prawa rêka Theodore. Przepraszam za ch³odne powitanie, ale ostatnio nie mieliœmy zbyt wiele czasu na uprzejmoœci.}
{218} {} {Czy mogê zadaæ ci kilka pytañ, Ralph?}

{220} {} {Witam ponownie.}
{221} {} {Do zobaczenia ponownie.}

{230} {} {Czy ta stacja dzia³a od czasów przedwojennych?}
{231} {} {Przez d³ugi czas by³a zablokowana. Dopiero niedawno uruchomiono g³ówny reaktor.}
{232} {} {Jak to zrobiliœcie?}
{233} {} {Podziekuj czcicielom ognia i ich kolonii we Flagpool za to. Tam wydobywa siê uran na kapslach koœcio³a. I czêœæ tego uranu dociera do nas. To lukratywny kontrakt dla ca³ego miasta.}
{234} {} {Wow, okazuje siê, ¿e ludzie w koœciele nie tylko siê modl¹.}
{235} {} {By³oby lepiej nakarmiæ ludzi ni¿ zmuszac niewolników do wydobywania rudy.}
{236} {} {Jak siê tu wszyscy znalezliœcie?}
{237} {} {Przybywamy z zachodu, z Kalifornii. Ale to ju¿ inna historia. Przypadkowo zaproponowano nam przywrócenie stacji. W koñcu wy, wspó³czesne pokolenie, nie wiecie nic o starej technice.}
{238} {} {Chwileczkê, czy ty chcesz powiedzieæ, ¿e ¿yjesz sto lat?}
{239} {} {NieŸle siê trzymam, prawda? Haha, to mój ulubiony ¿art. Mówi¹, ¿e przyczyn¹ naszej mutacji by³ jakiœ wirus, który przypadkowo dosta³ siê do powietrza podczas bombardowania starego laboratorium. Ale to tylko plotki.}
{240} {} {Powiedz mi, jaki by³ œwiat przed wojn¹?}
{241} {} {Hmm... Minê³o sto lat, widzê wszystko jak przez mg³ê. Pamiêtam samochody, drapacze chmur i wojskowe punkty kontrolne. Pamiêtam wojnê, kiedy bomby spad³y na miasto. Ale jak mo¿na to wszystko wyt³umaczyæ osobie takiej jak ty? Dla Ciebie to tylko historia.}
{242} {} {Widzê, ¿e trudno ci to opisaæ. Zmieñmy motyw.}
{243} {} {Czy próbujesz mnie teraz upokorzyæ? Ani s³owa, panie ghul.}
{244} {} {Twój szef mówi, ¿e rurociag zosta³ wysadzony w powietrze. Co o tym wiesz?}
{245} {} {Wow, to du¿o powiedziane. Mniejsza o s³owa starego cz³owieka. Trochê traci zmys³y.}
{246} {} {Ale on musi mi zap³aciæ za pracê.}
{247} {} {Wiêc zrób, co mówi. Potrzebuje winowajców - to znajdŸ ich. Jak to zrobiæ? Dobre pytanie... Wiesz, najprawdopodobniej sprawcy przedostali siê kana³ami. Wydawa³o mi siê jednak, ¿e odpowiednio uszczelniliœmy wszystkie wejœcia.}
{248} {} {Dobry pomys³. Nale¿y to sprawdziæ.}
{249} {} {Najprawdopodobniej sprawcy weszli kana³ami. Ale wydawa³o mi siê, ¿e odpowiednio zapieczêtowaliœmy wszystkie wejœcia.}

{250} {} {Czarcie z Piek³a, przepadnij! Wszystko sz³o dobrze, póki siê nie zjawi³eœ!}
{251} {} {Koniec zabawy, Ralph. Przegra³eœ. }
{252} {} {O nie, JA dopiero zaczynam zabawê. Teraz zobaczysz prawdziw¹ moc Starego Swiata!}
{253} {} {Nie rób tego...}
{254} {} {Jesteœ trupem, kretynie.}
{255} {} {Pos³uchaj mnie, Ralph. Od samego pocz¹tku wszystko by³o ustawione. Zosta³eœ wykorzystany.}
{256} {} {To jest umowa korzystna dla obu stron. Tylko czciciele ognia mogli daæ stacji nowe ¿ycie i o¿ywiæ kawa³ek Starego Swiata. Nikt inny nie mia³ wiedzy i zasobów, aby to zrobiæ. A stary Theodore w³aœnie zwariowa³. A¿ strach pomyœleæ, jak skoñczy siê ta historia pod jego kierownictwem.}
{257} {} {Mimo to nie mo¿esz wyjœæ st¹d ¿ywy.}
{258} {} {Koœció³ nie dba ani o was wszystkich, ani o œwiat wokó³ was. Nie widzisz?}
{259} {} {Przestañ gadaæ! Teraz zobaczysz prawdziw¹ moc Starego Swiata.}
{260} {} {Rozumiem ciê. Chcesz przywróciæ stary œwiat, który zna³eœ i w którym by³o ci dobrze. Ale rozejrzyj siê - czciciele ognia tworz¹ INNY œwiat.}
{261} {} {Inny... Tak. Aaron u¿ywa nas tylko do budowy imperium. Nie myœla³em o tym. Ale jeœli masz racjê... Cholera, co powinienem zrobiæ? Iœæ z ch³opakami na wschód? Kto wie, mo¿e uda nam siê znaleŸæ ropê w Teksasie lub odnowiæ stare zak³ady Chryslus Motors.}
{262} {} {Zaufaj mi, nie pozwol¹ ci tu mieszkaæ. Staniesz siê tylko broni¹ w rêkach cesarza.}
{263} {} {Kurwa. Nie mogê puœciæ wolno schizola takiego jak ty. Umrzesz tu i teraz.}
{264} {} {M¹drze powiedziane. Pójdê na wschód. Spokojnie. Powiedz Theodore'owi, ¿eby usun¹³ stra¿ników z pod drzwi.}
{265} {} {M¹dra decyzja, Ralph.}
{266} {} {Twój szef poprosi³ mnie o naprawê uk³adu ch³odzenia. Czy mo¿esz mi powiedzieæ, od czego zacz¹æ?}
{267} {} {O czym myœli ten starzec, wpuszczaj¹c nieznajomego do serca stacji? Ok, zobaczmy. Najpierw obejrzyj uszkodzenia na dolnym poziomie. Do naprawy potrzebne bêd¹ materia³y i sprzêt. Naj³atwiej je zdobyæ w fabryce Blacharzy. To jest gdzieœ na po³udnie od miasta, karawaniarze powinni wiedzieæ gdzie dok³adnie.}
{268} {} {Dziêki.}

{270} {} {Wiem, ¿e Wyznawcy Ognia dzia³ali przez ciebie. By³y o tym informacje w katedrze.}
{271} {} {Cicho, nie musisz byæ taki g³oœno. ChodŸmy w ustronne miejsce...}
{272} {} {[Dalej.]}
{273} {} {Rozumiem, ¿e masz powi¹zania z czcicielami ognia, w przeciwnym razie sk¹d masz informacje o naszym tajnym pakcie?}
{274} {} {Mam wiele kontaktów. Ale co próbujesz osi¹gn¹æ? Chcesz zaj¹æ miejsce swojego szefa?}
{275} {} {To nie tak. Nie zapominaj, ¿e mam sto lat. Gdybyœmy byli w Starym Swiecie, pragn¹³bym rozwoju kariery. Ale co mamy teraz? Zniszczenia, brak transportu i dróg, nawet oœwietlenie ulic ludzie widzieli tylko dziêki nam i Koœcio³owi Ognia.}
{276} {} {Czy koœció³ nie sponsoruje ciê uranem?}
{277} {} {To nie wystarczy. Theodore nie pozwala im wejœæ na stacje, a bez nich biznes toczy siê zbyt wolno. Na pocz¹tku wydawa³o siê to kwesti¹ czysto techniczn¹ - brali uran i czerpali z niego energiê. Nadszed³ czas na ekonomie, biznes i podatki. Theodore nic z tego nie rozumie i uwa¿a, ¿e wystarczy sprzedawaæ energiê na lewo i prawo.}
{278} {} {Wiêc chcesz renegocjowaæ umowê. A co z Theodorem?}
{279} {} {Problem w tym, ¿e ten stary cz³owiek oszala³, ale stoj¹ za nim pracownicy. Muszê byæ u steru stacji, ¿eby coœ siê tu zmieni³o. Pomó¿ mi. Pozb¹dŸ siê Theodora, a zostaniesz nagrodzony i szanowany. Ponadto zrobisz coœ po¿ytecznego dla ca³ego miasta.}
{280} {} {Pomyœlê o tym.}
{281} {} {Mój plan ju¿ czêœciowo siê nie powiód³, poniewa¿ naprawi³eœ sprzêt. Nie zawiedŸ mnie i tym razem.}
{1281} {} {Mój plan ju¿ czêœciowo siê nie powiód³, poniewa¿ naprawi³aœ sprzêt. Nie zawiedŸ mnie i tym razem.}
{282} {} {Do widzenia.}
{283} {} {Ju¿ wszystko omówiliœmy. Nie zawiedŸ mnie raz jeszcze.}
{284} {} {Do widzenia.}
{285} {} {Jak mam pozbyæ siê Theodora? To niebezpieczna misja.}
{286} {} {Myœla³em o tym. Otwarte morderstwo wywo³a zbyt wiele kontrowersji i podejrzeñ. Spróbuj zmieszaæ truciznê z twardych narkotyków. Serce starego ghula z pewnoœci¹ zawiedzie.}
{287} {} {Dobry pomys³. Gdzieœ w slumsach by³ handlarz.}
{288} {} {Gotowe. Stanowisko kierownika stacji jest teraz Twoje.}
{289} {} {Musia³es zostaæ wys³any do nas przez anio³a Pulsu Elektromagnetycznego. Dziêkujê Ci. Post¹pi³eœ w³aœciwie. Udaj siê teraz do magazynu i poproœ o nagrodê. Pracownik znajdzie coœ, czym mo¿na ci podziêkowaæ.}
{1289} {} {Musia³aœ zostaæ wys³ana do nas przez anio³a Pulsu Elektromagnetycznego. Dziêkujê Ci. Post¹pi³aœ w³aœciwie. Udaj siê teraz do magazynu i poproœ o nagrodê. Pracownik znajdzie coœ, czym mo¿na ci podziêkowaæ.}
{290} {} {Do widzenia Ralph.}

{291} {} {S³ysza³em, ¿e otrzymujesz uran z Flagpool.}
{1291} {} {S³ysza³am, ¿e otrzymujesz uran z Flagpool.}
{292} {} {Niezupe³nie. Otrzymujemy elementy paliwowe z wype³nieniem uranowym, które s¹ produkowane na po³udniu. Transportowana jest tam równie¿ ruda uranu.}
{293} {} {Czy nie przeszkadza ci, ¿e ta ruda jest wydobywana niewolnicz¹ prac¹?}
{294} {} {Nie obchodzi mnie, kto to wydobywa ani w jaki sposób. Potrzebujemy uranu, a reszta nie jest naszym problemem.}
{295} {} {Hmm. To ma sens. Ale nadal jesteœ poœrednio winny.}
{296} {} {Rozumiem. To tylko biznes.}