{100} {} {Widzisz Theodore.}
{101} {} {Widzisz mê¿czyznê ze spalon¹ skór¹. Ma na sobie znoszone ubranie robocze z przedwojennym symbolem.}
{102} {} {Niebezpieczeñstwo! Outsider!}
{103} {} {Porozmawiamy, gdy ju¿ Odwet Elektromagnetyczny uderzy Ralpha.}
{104} {} {Mam du¿o do zrobienia. Ale dziêki za odwiedzenie dziadka. A tak przy okazji, kim jesteœ?}
{105} {} {Och, coœ mi tu nie pasuje...}

{110} {} {}
{111} {} {Szefie! Theodore! K³opot!}
{112} {} {Co siê sta³o? Próbuje tu spaæ...}
{113} {} {Ralph i pozostali zamknêli siê w pokoju kontrolnym. I nie ¿artuj¹!}
{114} {} {Ralph? Poprosi³em o przyprowadzenie go do mnie. DO MNIE. Powtórzyæ?}
{115} {} {Nie, szefie, zamkn¹³ siê i nikogo nie wpuœci. Musisz coœ zrobiæ!}

{200} {} {No có¿. A oto pierwszy pos³aniec z³a. A mo¿e i nie? Coœ ostatnio zacz¹³em siê myliæ, nawet jeœli chodzi o dni tygodnia, muszê nakrêciæ swój zegar.}
{201} {} {Um, nie wiem, co masz na myœli. Od niedawno jestem w mieœcie i szukam swoich bliskich.}
{202} {} {Hmm, naprawdê? Có¿, tak, widzia³em ich wielu w ci¹gu stu lat. Przepraszam za sceptycyzm, ale teraz bardzo wa¿ne jest, aby zachowaæ ostro¿noœæ.}
{203} {} {Czy coœ siê sta³o?}
{204} {} {Ruroci¹g z uk³adu ch³odzenia reaktora eksplodowa³. Pêk³ jak wstrêtny robak. Odcieliœmy dop³yw p³ynów, ale rezerwy nie wystarcz¹ na d³ugo. Reaktor bêdzie siê przegrzewa³ z miesi¹ca na miesi¹c i prêdzej czy póŸniej bêdzie musia³ zostaæ wy³¹czony.}
{205} {} {Nie brzmi to dobrze. Czy mo¿na to naprawiæ?}
{206} {} {Oczywiœcie. Ale nie naszymi si³ami. To jest elektrownia j¹drowa, a nie jakaœ fabryka. Potrzebujemy czêœci i wyposa¿enia i bêdziemy musieli bardzo siê postaraæ, aby je znaleŸæ. Mo¿esz nam pomóc? Zap³acimy.}
{207} {} {Nie rozumiem tego.}
{208} {} {Ja te¿, hehe. Po prostu przynieœ nam materia³y do naprawy. Wydaje mi siê, ¿e gdzieœ na po³udniu jest dzia³aj¹ca fabryka. Zapytaj miejscowych.}
{209} {} {Pomyœlê o tym.}
{210} {} {To za daleko i na uboczu. Przepraszam.}
{211} {} {Oczywiœcie. Nie mam nic przeciwko zarabianiu pieniêdzy.}
{212} {} {Dobra, liczê na ciebie. IdŸ, ale nie mów nikomu o naszej umowie... Hmm. Paskudne robaki morskie. Ci¹gle staraj¹ siê rzuciæ na ciebie ze swoimi paskudnymi zêbami.}
{213} {} {Uch... Do widzenia.}
{214} {} {Ale nie mów nikomu o naszej umowie. Zw³aszcza tym szalonym czcicielom ognia.}

{220} {} {Tak, tak, s³ucham.}
{221} {} {Do widzenia.}
{222} {} {Czekam na wyniki. Nie zapominaj, ¿e ta praca bardzo ci siê op³aci.}

{230} {} {Czy mogê zadaæ kilka pytañ na temat tej stacji?}
{231} {} {Nie marnuj mojego czasu. Wyœwiadczy³em ci ju¿ przys³ugê, wpuszczaj¹c ciê tutaj.}
{232} {} {Ok.}
{233} {} {Uda³o mi siê naprawiæ system ch³odzenia.}
{234} {} {Dziêki, zrobi³eœ to! Nie mogê w to uwierzyæ, jak ty to zrobi³eœ?}
{235} {} {Có¿, ca³y dzieñ musia³em bawiæ siê tym sprzêtem.}
{236} {} {Hej, g³adkoskóry. Nie mo¿e byæ tak, ¿e twoje pojawienie siê przypadkowo zbiega siê z sabota¿em.}
{237} {} {Uch, sabota¿em?}
{238} {} {Zbadaliœmy wrak. I co? Uk³ad zosta³ celowo wysadzony w powietrze dynamitem. Jak to wyjaœnisz, mój œliski przyjacielu o bladej skórze?}
{239} {} {Uh, nie mam z tym nic wspólnego. Sam mnie wpuœci³eœ, a potem...}
{240} {} {Przestañ siê wykrêcaæ, kochanie. Powiem ci coœ - znajdŸ sprawcê ataku. Dopiero wtedy zdecydujê, czy ci zap³aciæ, czy nie.}
{241} {} {Daj mi moje kapsle teraz, staruszku, albo wyœlê ciê do twoich przodków.}
{242} {} {Jak mam to zrobiæ? Ta stacja prawdopodobnie ma wiele przejœæ, intruz spokojnie móg³ przejœæ niezauwa¿ony.}
{243} {} {Sprytnie kombinujesz. Teraz idŸ i nie wracaj bez informacji. U-ha-ha, a ja bêdê radoœnie tupaæ na jednej nodze!}
{244} {} {Ok... uh, lepiej ju¿ pójdê. PA.}
{245} {} {Znam prawa! A ty? Dlatego funkcjonariusz nie przekracza granicy.}
{246} {} {Uch... Co?}
{247} {} {ChodŸ tutaj, zgrzybia³a laleczko, od³o¿ê teraz twój mózg na miejsce.}

{250} {} {Wiem, kto wysadzi³ uk³ad.}
{251} {} {Wow, to ciekawe. Jak prawdziwy detektyw... Kto to by³?}
{252} {} {Nie wiem. Jestem po prostu zdesperowany. Lepiej pójdê na drinka.}
{253} {} {Czerwoni kardyna³owie podjêli siê sabota¿u na proœbê czcicieli ognia. Twój wierny asystent, Ralph, pomóg³ im w tym.}
{254} {} {Co? Ale jak to? Dlaczego mia³by w tym braæ udzia³?}
{255} {} {Nie mam pojêcia, ale to fakt.}
{256} {} {Koœció³ próbowa³ wci¹gn¹æ ciê w niekorzystny kontrakt. A Ralph... myœli, ¿e nadszed³ czas, aby to on obj¹³ stanowisko kierownika stacji.}
{257} {} {Ochrona! Przyprowadziæ do mnie Ralpha. I nie spuszczajcie z niego oczu, ¿eby nie by³o wiêcej k³opotów... On jest szalony. Jak przejrza³a wiœnia. Czy wiesz, ile pracy zajê³o naprawienie i uruchomienie tej stacji?}
{258} {} {Nie obchodzi mnie to...}
{259} {} {Có¿, to musia³o byæ cholernie trudne.}
{260} {} {O tak. Ci¹gle jakieœ zmartwienia. Ralph uwa¿a, ¿e kultyœci poradz¹ sobie lepiej, jeœli przejm¹ tu dowodzenie. Ale jako by³y oficer wiem, ¿e ludzie tacy jak oni nie powinni byæ u w³adzy.}
{261} {} {C-có¿...}
{262} {} {O czym ty mówisz?}

{270} {} {Co zamierza ten stary libertyn? Pos³uchaj, za³atw sprawê z Ralphem. Ten biznes staje siê zbyt niebezpieczny.}
{271} {} {Bêdê. Jak dwa palce na asfalcie.}
{272} {} {Warto najpierw z nim porozmawiaæ.}

{280} {} {Oto nasz bohater. Prawdziwy pracoholik elektrowni atomowej. Szkoda, ¿e zabrak³o mi nagród. Ale nie martw siê. Wiem, jak ciê nagrodziæ. IdŸ do magazyniera i poproœ go o cokolwiek chcesz.}
{1280} {} {Oto nasza bohaterka. Prawdziwy pracoholik elektrowni atomowej. Szkoda, ¿e zabrak³o mi nagród. Ale nie martw siê. Wiem, jak ciê nagrodziæ. IdŸ do magazyniera i poproœ go o cokolwiek chcesz.}
{281} {} {Mi³o by³o.}
{1281} {} {Mi³o by³o.}
{282} {} {Nie wiem, jak mimo takiego smrodu mo¿esz zarz¹dzaæ t¹ stacj¹.}
{283} {} {Co ty mówisz? Smród? A tak, to kolejny problem. Próbowa³em siê umyæ, ale zapach tylko siê nasila. Lepiej martw siê o siebie.}
{284} {} {Zegnaj staruszku.}
{285} {} {Mam nadziejê, ¿e ju¿ nigdy siê nie spotkamy.}