{100} {} {Widzisz Herberta.}
{101} {} {Widzisz mê¿czyznê ze spalon¹ skór¹. Ma na sobie znoszone ubranie robocze z przedwojennym symbolem.}

{200} {} {Swiêty Omie! Nie strasz mnie tak. Ze swoj¹ blad¹ skór¹ wygl¹dasz na tej stacji jak duch...}
{201} {} {Na pewno s¹ tu ludzie, którzy wygl¹daj¹ jakby byli martwi. Ale to nie ja.}
{202} {} {Przepraszam, nie mia³em zamiaru nikogo przestraszyæ.}
{203} {} {Haha. Niewa¿ne, mo¿emy siê ju¿ tylko œmiaæ ze œmierci... Jestem Herbert, kierownik magazynu.}
{204} {} {Magazynu? Wiêc prawdopodobnie masz coœ po¿ytecznego.}

{210} {} {Czego chcesz, w³óczêgo?}
{211} {} {Niewa¿ne. Czeœæ, Herbert.}
{212} {} {Czy masz coœ do sprzedania? Kupi³bym kilka na³adowanych baterii.}
{213} {} {Przepraszam, handlujemy tylko z karawanami. Nie mamy prawie nic oprócz energii.}
{214} {} {Rozumiem. Czeœæ, Herbert.}

{220} {} {Twój szef obieca³ mi zap³aciæ za pracê.}
{221} {} {Tak, wiem. Mo¿esz wybraæ swoj¹ nagrodê.}
{222} {} {Pozwól mi trochê pomyœleæ. Nied³ugo wrócê.}
{223} {} {Dobra, podpisz tutaj i tutaj. Tylko ¿artujê. Prawdopodobnie nawet nie wiesz, jak pisaœ. Przy okazji, jeœli potrzebujesz baterii, proszê. Szef mówi, ¿e mo¿esz z nami handlowaæ.}
{224} {} {Zapamiêtam to. Czeœæ, Herbert.}
{225} {} {250 kapsli.}
{226} {} {Pistolet laserowy.}
{227} {} {Antyrad, 3 szt.}
