{100} {} {Widzisz atomistê.}
{101} {} {Widzisz mê¿czyznê z poparzon¹ skór¹. Ma na sobie raczej znoszone ubranie robocze z przedwojennym symbolem.}
{102} {} {Dziêki, doktorze. Dziêkujê Ci bardzo.}
{103} {} {Mam tu problem, wiesz. Nie znasz mo¿e jakiegoœ lekarza?}

{200}{}{Hej, bardzo dziêkujê. Nie s¹dzi³em, ¿e w dzisiejszych czasach s¹ jeszcze lekarze.}
{201}{}{Jak to siê sta³o?}
{202}{}{W czasie, gdy naprawialiœmy pêkniête rury, dosz³o do ma³ej eksplozji. Dobrze, ¿e mnie nie wyrzuci³o na ni¿szy poziom. P³ywa³bym wtedy w radioaktywnej mazi, jak kaczka w lodowatej wodzie.}
{203}{}{Na pewno masz szczêœcie. No chodŸ.}
{204}{}{Jesteœ urodzonym nieudacznikiem. Do widzenia.}
{205}{}{Kaczka?}
{206}{}{No wiesz, by³ taki ptak. Jeszcze przed wojn¹ nuklearn¹. Od tego czasu nie widzia³em ani jednej ¿ywej kaczki. Prawdopodobnie wyginê³y jak dinozaury...}
{207}{}{Dinozaury?}
{208}{}{Och, niewa¿ne, chodŸmy.}

{210}{}{Czeœæ doktorze. Dziêki raz jeszcze.}
{211}{}{Trzymaj siê.}