{100} {} {Widzisz mieszkañca slumsów.}
{101} {} {Widzisz mieszkañca slumsów. Drapie siê po g³owie.}
{102} {} {Widzisz mieszkañca slumsów. D³ubie w uchu.}
{103} {} {Widzisz mieszkañca slumsów. Czesze brud z w³osów.}
{104} {} {Widzisz mieszkañca slumsów. Z uczuciem prostuje swoje jedyne szmaty.}
{105} {} {Widzisz mieszkañca slumsów. Jego ³yse œlady na g³owie œwiadcz¹ o niezdrowej sytuacji w slumsach.}

{110} {} {Chcê jeœæ.}
{111} {} {Chcia³bym móc z³apaæ szczura i upiec go na obiad.}
{112} {} {Nie mogê uwierzyæ, ¿e * czysta * woda by³a kiedyœ spuszczana do toalety.}
{113} {} {Pusta rozmowa tylko potêguje mój g³ód.}
{114} {} {Potrzebujemy jedzenia.}
{115} {} {Mówi¹, ¿e od czasów Wielkiej Wojny w kana³ach ¿yj¹ zmutowani ludzie.}
{116} {} {Znowu znaleziono jakieœ cia³o w dzielnicy.}
{117} {} {Nie graj w kasynie, jeœli nie chcesz zostacæ jego niewolnikiem.}
{118} {} {Kult ognia ma wszêdzie oczy i uszy.}
{119} {} {Nie chcia³bym byæ wœród tych kultystów.}
{120} {} {Czeœæ.}
{121} {} {Do zobaczenia.}
{122} {} {Muszê iœæ.}
{123} {} {Nie rób mi k³opotów.}
{124} {} {Czy zdejmujesz to kiedyœ z nadgarstka?}
{125} {} {Co to jest telewizja?}
{126} {} {Czy „skrzynka pocztowa” nie jest koszem na œmieci?}
{127} {} {Przepraszam, ale muszê wróciæ do swojego lenistwa.}
{128} {} {T¹ brudn¹ wod¹ nie warto nawet gasiæ po¿arów.}
{129} {} {Czy to prawda, ¿e w górach jest bia³a woda?}
{130} {} {Niebo tutaj zawsze jest zas³oniête smogiem.}
{131} {} {Ani jednego deszczu od lat.}
{132} {} {Dzieñ min¹³, a ja nadal ¿yjê. To jakiœ sukces.}
{133} {} {Padlino¿ercy nie pozostawiaj¹ niczego wartoœciowego w ruinach.}