{100} {} {Widzisz mieszkañca slumsów.}
{101} {} {Widzisz mieszkañca lokalnych slumsów.}
{102} {} {Zabi³ j¹ jakiœ drañ!}
{103} {} {Nie mam nic przeciwko rozmowie, ale burczy mi w ¿o³¹dku. Có¿, rozumiesz.}
{104} {} {Dziêki za jedzenie, senor.}
{1104} {} {Dziêki za jedzenie, senora.}

{110} {} {Wszystko w porz¹dku?}
{111} {} {Jak siê masz?}
{112} {} {Wszystko wci¹¿ tu jest.}
{113} {} {Wróæ, jeœli chcesz.}

{200} {} {Czeœæ. Jak mogê pomóc?}
{201} {} {Ty? Niewa¿ne.}

{210} {} {Kim jesteœ?}
{211} {} {Jestem Fred. Moja ¿ona i ja niedawno przeprowadziliœmy siê z pustyni, gdzie hodowaliœmy ma³e stado braminów. A raczej próbowaliœmy. W koñcu nasze ranczo upad³o z powodu suszy i napadów bandytów. Postanowiliœmy wiêc spróbowaæ szczêœcia w du¿ym mieœcie.}
{212} {} {Do widzenia, Fred.}

{220} {} {Dlaczego mieszkasz w tym starym budynku?}
{221} {} {Nie jest tu tak Ÿle. Lepsze to ni¿ ¿ycie na ulicy. Vernon zaaran¿owa³ z jednym gangiem obronê okolicy. Ale ¿eby tu mieszkaæ, musisz zap³aciæ lub w inny sposób wypracowaæ swoje miejsce.}
{222} {} {Kim jest Vernon?}
{223} {} {Zarz¹dc¹ tego domu. Jego pokój znajduje siê po prawej stronie korytarza.}
{224} {} {Co to za gang?}
{225} {} {Jakieœ œliskie typy ze skórzanymi kurtkami i paskudnymi fryzurami. Osiedlili siê w starym budynku w pobli¿u. Ale lepiej nie wtr¹caæ siê w ich sprawy.}
{226} {} {Rozumiem. Czeœæ.}
{227} {} {Przypomnij mi swoje imiê?}
{228} {} {Kim jesteœ?}

{230} {} {Co mo¿esz mi powiedzieæ o tym obszarze?}
{231} {} {Wielu uwa¿a to za najgorsz¹ dzielnicê mieszkaniow¹ w mieœcie. Ale dla biednych ludzi, takich jak my, nawet to wydaje siê wielkim osi¹gniêciem.}
