{100} {} {Widzisz mieszkañca slumsów.}
{101} {} {Widzisz kobietê z zagubionym wyrazem twarzy. Czuje siê tu wyraŸnie nieswojo.}
{102} {} {Zabi³ go jakiœ drañ!}
{103} {} {Huh? Co? Hej... masz jedzenie?}
{104} {} {Dziêki za jedzenie, senor.}
{1104} {} {Dziêki za jedzenie, senora.}

{200} {} {Czeœæ. Czy mogê ci w czymœ pomóc?}
{201} {} {Prawdopodobnie nie.}

{210} {} {Kim jesteœ?}
{211} {} {Nazywam siê Susie. Przeprowadziliœmy siê z mê¿em z ma³ego rancza na pustyni, ¿ycie by³o tam zbyt ciê¿kie. Postanowiliœmy spróbowaæ szczêœcia w du¿ym mieœcie.}
{212} {} {Do widzenia, Susie.}

{220} {} {Dlaczego mieszkasz w tak okropnym budynku?}
{221} {} {Nie mamy kapsli do ¿ycia w bardziej zamo¿nych obszarach. A ¿ycie na ulicy jest zbyt niebezpieczne. Tutaj przynajmniej Vernon i jego gang obserwuj¹ nas.}
{222} {} {Kim jest Vernon?}
{223} {} {Zarz¹dc¹ tego domu. Jego pokój znajduje siê po prawej stronie korytarza.}
{224} {} {Co to za gang?}
{225} {} {Jacyœ ludzie o przera¿aj¹cych spojrzeniach. Staramy siê trzymaæ od nich z daleka. Ich obóz znajduje siê w opuszczonym budynku w pobli¿u.}
{226} {} {Rozumiem. Czeœæ.}
{227} {} {Przypomnij mi swoje imiê?}
{228} {} {Kim jesteœ?}

{230} {} {Co mo¿esz mi powiedzieæ o tym obszarze?}
{231} {} {To najgorsza dzielnica mieszkaniowa w mieœcie.}
