{100} {} {Widzisz Steva.}
{101} {} {Widzisz jednego z fanów na ringu.}
{102} {} {Wow. Wiedzia³em, ¿e Blacharze s¹ dobrymi rzemieœlnikami, ale nawet bym o tym nie pomyœla³...}
{103} {} {Ten list by³ bardzo ciekawy. Dziêkujê za dostarczenie go.}
{104} {} {Ty te¿ lubisz zaryzykowaæ na zak³adach?}

{200} {} {Co? Ty te¿ bierzesz udzia³ w walkach?}
{201} {} {Nie. Szukam mê¿czyzny o imieniu Steve. Mieszka w domu naprzeciwko.}
{202} {} {Czekaj, to ty! Wow, s³uchaj, ostatnie walki by³y naprawdê osza³amiaj¹ce. Ale dlaczego ju¿ nie walczysz? Postawi³bym na ciebie kilka kapsli.}
{203} {} {To nie zale¿y ode mnie.}
{204} {} {Och, rozumiem. Ten maluch jest chciwy na kapsle, prawda? Niewa¿ne.}
{205} {} {Szukam mê¿czyzny imieniem Steve. Mieszka w domu naprzeciwko.}
{206} {} {Ju¿ nie walczê. I kropka.}
{207} {} {Dobra, dobra, dobra hak-cz³owieku, pewnie nie musisz ju¿ tak ciê¿ko pracowaæ.}
{208} {} {Nie obchodzi mnie to. Po prostu powiedz mi, kim jest Steve, który mieszka po drugiej stronie ulicy.}
{209} {} {To ja. Czego chcesz?}
{210} {} {Jestem z firmy kurierskiej. Mam list do Ciebie. Podpisz i bierz.}
{211} {} {Czy to jakiœ ¿art? Ledwo potrafiê czytaæ. Kto móg³by do mnie napisaæ?}
{212} {} {Wiêc nie jesteœ tym Stevem, którego szukam. Do widzenia.}
{213} {} {Hej, czekaj. Oczywiœcie, ¿e podpiszê. Ok, wystarczy odcisk palca? Okej, podejdŸ tutaj...}
{214} {} {[Dalej.]}
{215} {} {Nie wiem, kto do ciebie pisze. Ale masz zap³aciæ piêæ kapsli za wysy³kê.}
{216} {} {Wiêc jeszcze muszê za to p³aciæ? Nie ma opcji. To z pewnoœci¹ jakieœ oszustwo. Nie oczekuj, ¿e do tego dojdzie.}
{217} {} {Ok. WeŸ ten list. I tak mi tylko przeszkadza w plecaku.}
{218} {} {Powa¿nie? Ok, oto piêæ kapsli. Naprawdê mam nadziejê, ¿e by³o warto.}
{219} {} {Proszê bardzo.}
{220} {} {W porz¹dku. Po prostu podpisz i weŸ list.}
{221} {} {Co? Ty te¿ bierzesz udzia³ w walkach?}
{222} {} {Nie, szukam kogoœ, komu przeka¿ê list. Ale chwila... list gdzieœ znikn¹³.}
{223} {} {Tak, problem.}
{224} {} {Uh, pójdê zobaczyæ. Bywaj.}

{227} {} {Czeœæ. Nadal próbujê zarobiæ kapsle na ringu. Ale coœ mi nie wychodzi. Wygl¹da na to, ¿e czas wyjœæ z tego dusznego miasta.}
{228} {} {Mów za siebie. Mam doœæ ¿ycia na wsi na plantacjach. Czeœæ.}
{229} {} {Tak. Z dala od zgie³ku miasta ¿ycie jest ³atwiejsze i spokojniejsze. Czeœæ.}

{230} {} {(bierze list, rozk³ada go i czyta powoli) Wiêc... wiêc...}
{231} {} {Czy to naprawdê list do Ciebie?}
{232} {} {Jest napisany przez mojego wujka z Casa Grande. Wygl¹da na to, ¿e mam siê z nim spotkaæ. Dziêkujê, to by³ bardzo cenny list. Naprawdê.}
{233} {} {Co pisze?}
{234} {} {Wiêc mogê ju¿ odejœæ. Wszystkiego najlepszego.}
