{100} {} {Widzisz Vernona.}
{101} {} {Widzisz mê¿czyznê w znoszonym garniturze. Krêgi pod oczami i nerwowy tik wskazuj¹ na przepracowanie.}
{102} {} {Mamy oczywiœcie niebezpieczny obszar, ale...}
{103} {} {Proszê, zatrzymaj ich! Zaraz wszystko tu rozwal¹!}

# Pierwszy dialog
{200} {} {(zauwa¿aj¹c ciê, mê¿czyzna marszczy brwi i nerwowo mruga prawym okiem) Nie s¹dzê, ¿ebym ciê wczeœniej widzia³. Czego tu szukasz?}
{201} {} {Potrzebujê noclegu. Czy s¹ tu pokoje do wynajêcia?}
{202} {} {Przepraszam, ale wszystkie pokoje s¹ zajête. I bez Ciebie nie mamy czym oddychaæ.}
{203} {} {Co to za miejsce?}
{204} {} {Coœ w rodzaju domu spo³ecznego. Jeœli to wszystko, lepiej odejdŸ.}
{205} {} {Dlaczego?}
{206} {} {Surowe lokalne zwyczaje. Wszyscy najemcy znaj¹ siê z widzenia i s¹ nieufni do nowoprzyby³ych.}
{207} {} {Rozumiem. W takim razie naprawdê lepiej odejdê.}
{208} {} {Nic dziwnego, i tak mi siê tu nie podoba. Bywaj.}
{209} {} {Nie wyjdê, dopóki nie odpowiesz na moje pytania.}

{210} {} {Nawet nie wiem. Co to za miejsce?}
{211} {} {To jest dom wspólnotowy. Prowadzisz tu interesy albo masz przyjació³? Jeœli nie, to lepiej odejdŸ.}
{212} {} {Dlaczego mnie wyrzucasz?}
{213} {} {(niezadowolony i zaspany) Ku... kuu... kurwa, czy w ogóle wiesz, która jest godzina...}
{214} {} {Przepraszam, ¿e nie dajê Ci spaæ.}
{215} {} {Nie obchodzi mnie to.}

{220} {} {(twoje pojawienie siê sprawia, ¿e mê¿czyzna zastyga ze zdumienia, a potem nerwowo wykrzywia prawe oko) Co za niespodzianka, zobaczyæ tak szanowan¹ osobê w naszej wspólnocie. Szukasz czegoœ?}
{221} {} {W³aœciwie to szukam noclegu. Czy s¹ tutaj jakieœ wolne pokoje?}
{222} {} {Obawiam siê, ¿e wszystkie pokoje s¹ zajête. Poza tym prawdopodobnie nie spodoba ci siê tutaj.}
{223} {} {Dlaczego?}
{224} {} {Jakby to uj¹æ... nie pasujesz do tych slumsów. Mamy z³e warunki ¿ycia i surowych lokatorów. Mo¿esz nawet zostaæ okradziony.}
{225} {} {W sumie to miejsce nie wygl¹da na przyjazne. Bywaj.}
{226} {} {Wygl¹da na to, ¿e naprawdê lepiej odejœæ.}
{227} {} {Zanim wyjdê, chcê zadaæ kilka pytañ.}
{228} {} {By³em ciekawy, co to za miejsce?}
{229} {} {Coœ w rodzaju domu spo³ecznego. Jeœli jesteœ tu przypadkiem, to wogólê nie powinieneœ tu byæ.}
{230} {} {Dlaczego nie?}

{240} {} {Hej mistrzu! To by³a wspania³a walka. Jak mogê pomóc tak szanowanej osobie?}
{241} {} {Nawet nie wiem. Co to za miejsce?}
{242} {} {To jest dom komunalny, a ja jestem jego zarz¹dc¹. Nie s¹dze jednak, ¿eby osoby o twojej randze by³y tym miejscem zainteresowane. W naszym getcie mieszkaj¹... mniej odnosz¹cy sukcesy mieszczanie.}
{243} {} {W takim razie odpowiedz mi na kilka pytañ.}
{244} {} {Od pocz¹tku by³o jasne, ¿e to dziura. Ju¿ mnie tu nie zobacz¹.}
{245} {} {Masz coœ przeciwko, jeœli siê rozejrzê? Do zobaczenia.}
{246} {} {Hej mistrzu! To by³a wspania³a walka. Jak mogê pomóc tak szanowanej osobie?}
{247} {} {Chcê z tob¹ porozmawiaæ.}

# Smieræ popychacza
{250} {} {(Vernon siedzi przy stole z g³ow¹ w d³oniach; ko³ysze siê trochê, wydaj¹c cichy jêk)}
{251} {} {Co siê z tob¹ dzieje?}
{252} {} {Huh? Och, to ty... Ten cholerny ból g³owy... Bra³em narkotyki, które sprzedawa³ Gonzalez. Ale teraz nie ¿yje i nie wiem, sk¹d je wzi¹æ... Um...}
{253} {} {Szkoda, czeœæ.}
{254} {} {Och, przepraszam, myœla³em, ¿e œmieræ tego handlarza wyjdzie wszystkim na dobre.}
{255} {} {Naprawdê? Idiota! Tak, Gonzalez dawa³ niektórym mieszkañcom narkotyki, które sprawia³y, ¿e by³o z nimi gorzej. Ale innym dostarcza³ leki na choroby i œrodki przeciwbólowe. Dlaczego, do diab³a, chcia³eœ go zabiæ?}
{256} {} {To ju¿ nie twoja sprawa.}
{257} {} {No tak... oczywiœcie... Wiêc wyjdŸ do diab³a z mojego biura.}
{258} {} {Uwa¿aj na jêzyk, bo skoñczysz jak on.}
{259} {} {Tak.}
{260} {} {Jego towary nie by³y wysokiej jakoœci.}
{261} {} {Czy to jedyny powód? Cholera, zwiarowa³eœ! Natychmiast opuœæ ten obszar.}
{262} {} {}
{263} {} {Nawet nie wiem. Czy musi byæ jakiœ powód?}
{264} {} {Zwariowa³eœ! Lepiej wyjdŸ z tego obszaru i nigdy tu nie wracaj.}

# Reket po zakoñczeniu gry
{270} {} {Och, dziêki, amigo. Gdyby nie ty, ci chuligani rozwaliliby tu wszystko, a mo¿e nawet kogoœ zranili.}
{271} {} {Czego od ciebie chcieli?}
{272} {} {To tylko zbieracze haraczu. Po rozpadzie gangu kardyna³ów Bóg jeden wie, co zaczê³o siê w slumsach. Teraz wszyscy bandyci, którzy bali siê nawet wychyliæ na ulicê, mog¹ bezkarnie okradaæ i biæ ludzi.}
{273} {} {Czy sami kardyna³owie nie byli bandytami?}
{274} {} {Tak, ale obserwowali okolice i nie pozwalali, ¿eby tak siê dzia³o. Naprawdê mam nadziejê, ¿e wkrótce ta fala rabunku siê uspokoi. Ktoœ na pewno weŸmie w³adzê nad terenem w swoje rêce. I wszystko zacznie siê od nowa.}
{275} {} {Mhm... Baw siê dobrze. Czeœæ.}
{276} {} {Tego nie mo¿na by³o przewidzieæ. Powodzenia.}

# Powtarzajacy siê dialog
{300} {} {Wiêc czego chcesz?}
{301} {} {Jak mogê pomóc?}
{302} {} {Lepiej odejdŸ.}
{303} {} {Do widzenia.}
{304} {} {Z czym siê tu pieprzysz?}

{310} {} {Prowadzê œledztwo w sprawie ataku na Obserwatorów. Co o tym wiesz?}
{311} {} {Sytuacja trochê siê wyjaœni³a.}
{312} {} {Sytuacja trochê siê wyjaœni³a. Czas porozmawiaæ o tym z Aaronem.}
{313} {} {(marszczy brwi, robi nerwowe tiki) Wiêc jesteœ kolejnym tropicielem Obserwatorów? Wszystko ju¿ powiedzia³em mnichom. Zostaw nas w spokoju.}
{314} {} {(marszczy brwi, robi nerwowy tik) Nie spodziewa³em siê, ¿e ciebie te¿ zwerbuj¹. Ale ju¿ powiedzia³em mnichom wszystko, co wiem.}
{315} {} {Musisz mi powiedzieæ jeszcze raz.}
{316} {} {Nikogo nie zabiliœmy. Mnisi chodzili po mieszkañcach w poszukiwaniu ja³mu¿ny i oczywiœcie wychodzili z niczym. Ju¿ na ulicy zostali schwytani przez ludzi w maskach i powieszeni na latarniach. Nie wiemy, kto to by³. Ale najwyraŸniej byli dobrze przygotowani do ataku.}
{317} {} {Czy któryœ z mieszkañców jest w to zamieszany?}
{318} {} {Miejscowi boj¹ siê koœcio³a. Nikt nie pope³ni³by takiej zbrodni obok w³asnego domu.}
{319} {} {Kr¹¿¹ pog³oski, ¿e miejscowi nie lubi¹ mnichów.}
{320} {} {Dlaczego powinniœmy ich lubieæ? Kiedy my ¿yjemy w biedzie, mnisi k¹pi¹ siê w luksusie. Zabieraj¹ nam broñ i zakazuj¹ Gonzalezowi sprzeda¿y leków. Ale spójrz na miejscowych. Czy którykolwiek z tych biednych ludzi móg³ przeprowadziæ tak dobrze zaplanowany atak?}
{321} {} {Kto jest zdolny do tak œmia³ego ataku?}
{322} {} {Tylko atomiœci i gang Orrisa. Ale ci pierwsi zawsze trzymali siê z dala od miasta. A ci drudzy nie potrzebuj¹ problemów z koœcio³em.}
{323} {} {Zadnych wiêcej pytañ.}
{324} {} {Nie wierzê ci. Prawdopodobnie coœ ukrywasz.}
{325} {} {Wiem, o czym mówiê. Jeœli w to nie wierzysz, udowodnij mi to.}
{326} {} {Dzisiaj bêdê mi³y i z³amie ci tylko dwa palce, dopóki nie dowiem siê czego chcê.}
{1326} {} {Dzisiaj bêdê mi³a i z³amie ci tylko dwa palce, dopóki nie dowiem siê czego chcê.}
{327} {} {Grm...}
{328} {} {Stop! Pomyœl, czy zaatakowalibyœmy mnichów w pobli¿u naszego domu? To zbyt lekkomyœlne. Ale kr¹¿¹ plotki o jakiejœ tajnej grupie partyzantów. Rzeczywiœcie, w przesz³oœci Aaron z pomoc¹ Koœcio³a Ognia przeprowadzi³ rewolucje i zrujnowa³ ca³e miasto. Z pewnoœci¹ wielu od tego czasu chce siê na nim zemœciæ.}
{329} {} {Ciekawa myœl. Mo¿e jednak zas³ugujesz dziœ na moj¹ litoœæ.}
{330} {} {Doœæ k³amstw! Zabijê ciê.}
{331} {} {Nie œpiesz siê, by u¿yæ swojego ognistego kija, kultysto. W razie potrzeby my te¿ mo¿emy walczyæ.}
{332} {} {Grr!}
{333} {} {Opowiedz mi jeszcze raz o ataku na mnichów.}

#Zapytania
{350} {} {Kim jesteœ i co to za miejsce?}
{351} {} {Mówiê ci, to jest dom komunalny. A ja jestem Vernon, jego menad¿er.}
{352} {} {To wszystko, co chcia³em wiedzieæ.}
{353} {} {Dlaczego powiedzia³eœ, ¿e ten obszar jest niebezpieczny?}
{354} {} {Biedni ludzie i bandyci nie s¹ najlepszymi wspó³lokatorami w ¿adnym mieœcie.}
{355} {} {O jakich bandytach mówimy?}
{356} {} {Nie powinienem by³ tego mówiæ. W pobli¿u jest kilka gangów. Atomiœci na wschodzie, ludzie od Orrisa na pó³nocy i kilka innych ma³ych gangów w ka¿dym bloku.}
{357} {} {Co mo¿esz mi powiedzieæ o tych Atomowych goœciach?}
{358} {} {To tajemniczy ludzie, s¹ neutralni i staraj¹ siê nie ingerowaæ w sprawy miasta. Ale i tak trzeba na nich uwa¿aæ.}
{359} {} {Kim jest Orris i z czego s³ynie jego gang?}
{360} {} {Orris jest praktycznie w³aœcicielem ca³ego naszego bloku. Nie próbuj stawiaæ siê jego ch³opakom, bo inaczej nie po¿yjesz tutaj zbyt d³ugo.}
{361} {} {Szukam Steve'a. Podobno tu mieszka.}
{362} {} {Nie wiem czego chcesz od tego ³obuza i nie chcê wiedzieæ. Ostatnio by³ gdzie w pobli¿u ringu, maj¹c nadziejê na zarobienie pieniêdzy na zak³adach. G³upi oszust.}
{363} {} {Wiêc poszukam go w okolicy ringu.}

#Quests
{370} {} {Wygl¹da na to, ¿e masz k³opoty. Mogê pomóc.}
{371} {} {Naprawdê? Wiesz, miasto nauczy³o mnie nie ufaæ nikomu, kto oferuje pomoc z uœmiechem na ustach. Co tak naprawdê chcesz osi¹gn¹æ?}
{372} {} {Chcê tylko pomóc. To prawda.}
{373} {} {Powiedz to komuœ innemu. I tak nie dostaniesz tutaj ¿adnych kapsli.}
{374} {} {Có¿, masz racjê. Muszê zdobyæ szacunek w mieœcie.}
{375} {} {Ha. Wiedzia³em. Ale tutaj nie dostaniesz kapsli. Chocia¿ warto zadbaæ o dobr¹ reputacjê.}
{376} {} {Jeœli nie chcesz, dobrze. Nic na si³ê.}
{377} {} {Nadal - jaki jest twój problem?}
{378} {} {Có¿. Jest tu kilku irytuj¹cych najemców, z którymi ci¹gle s¹ problemy. Czy mo¿esz ich wypêdziæ?}
{379} {} {Mo¿liwe. Kim oni s¹?}
{380} {} {Uch, nie. Nie robiê takich rzeczy.}
{381} {} {Jeden nazywa siê Larry. Jest uzale¿niony od narkotyków i wydaje na nie wszystkie kapsle. Jest m¹drym cz³owiekiem, ale chemia ca³kowicie zachmurzy³a mu g³owê. Nie mogê go otwarcie wyrzuciæ, poniewa¿ jego sprzedawca najwyraŸniej nie lubi traciæ klientów.}
{382} {} {Rozumiem. Kto jest drugi?}
{383} {} {Badi. Mieszka w pokoju naprzeciwko. Nie by³o z nim problemów, dopóki nie uzale¿ni³ siê od hazardu. Teraz ma taki d³ug, ¿e bramkarze gro¿¹ nawet mnie.}
{384} {} {Nikt ju¿ nie chce siê z nim zadawaæ. Oczywistym jest, ¿e mi te¿ nie jest w stanie zap³aciæ. Pomó¿ mu zap³aciæ czynsz albo wywal go na ulicê. Jestem tym zmêczony.}
{385} {} {Przypomnij mi, o jakim na³ogowcu mówi³eœ?}
{386} {} {Larry. Z pewnoœci¹ jest teraz w swoim brudnym pokoju, marnuj¹c ¿ycie.}
{387} {} {Rozumiem. Czeœæ.}
{388} {} {Przypomnij mi, który najemca jest winien czynsz.}
{389} {} {Wszyscy s¹ zad³u¿eni. Ale najwiêcej wisi Badi. Poza tym ma problemy z kasynem, a ja tego nie potrzebujê.}
{390} {} {Cholera, to powa¿na sprawa.}
{391} {} {Larry nie bêdzie ju¿ niepokoiæ lokatorów. Jest martwy.}
{392} {} {CO? Mój Bo¿e, dlaczego musia³eœ do tego doprowadziæ?}
{393} {} {Có¿, chcia³eœ siê go pozbyæ.}
{394} {} {Ale nie o to mi chodzi³o! Slumsy ju¿ i tak maj¹ z³¹ reputacjê, a teraz ludzie bêd¹ mówiæ i o mnie z³e rzeczy.}
{395} {} {Zadanie powinno by³o zostaæ lepiej wyjaœnione. Teraz ju¿ za póŸno.}
{396} {} {No tak. Pewnie. Naprawdê mam nadziejê, ¿e zostanie to szybko zapomniane. Poza tym bez Larry'ego bêdzie tu du¿o spokojniej.}
{397} {} {Dok³adnie. Czeœæ, Vernon.}
{398} {} {Larry nie bêdzie ju¿ niepokoiæ lokatorów. Uda³o mu siê przezwyciê¿yæ uzale¿nienie.}
{399} {} {Niesamowite! Jak uda³o ci siê go zainspirowaæ? Nikt ju¿ nie wierzy³ w Larry'ego. Wszyscy uwa¿ali go za straconego.}
{400} {} {Mam swoje w³asne metody. Potrzebowa³ tylko motywacji.}
{401} {} {Nawet nie wiem, co powiedzieæ. Dziêkujê Ci.}
{402} {} {Nie ma za co, Vernon.}
{403} {} {Ok. Porozmawiam z nimi.}

{404} {} {Badi ma zamiar sp³aciæ d³ug z tytu³u czynszu.}
{405} {} {Dobra robota! Ju¿ myœla³em, ¿e nic go nie uchroni przed krwawym rozrachunkiem. Jak uda³o ci siê naprawiæ jego mózg?}
{406} {} {Najwa¿niejsze jest, aby znaleŸæ w³aœciwe podejœcie do ka¿dego klienta. Czeœæ, Vernon.}
{407} {} {Badi ju¿ tu nie mieszka, teraz ¿yje na ulicy jak wstrêtny bezpañski pies.}
{408} {} {I dobrze. Nie potrzebujemy tutaj zbêdnych problemów. Dziêki za pomoc.}
{409} {} {Proszê.}
{410} {} {Badi ju¿ tu nie mieszka. Nie ¿yje.}
{411} {} {Czy zosta³... zabity? Mój Bo¿e, ci bramkarze to prawdziwe bestie.}
{412} {} {Nie by³o innego wyjœcia.}
{413} {} {Nie podawaj mi szczegó³ów. Naprawdê mam nadziejê, ¿e jego d³ug wobec kasyna nie wp³ynie na mnie i resztê mieszkañców. By³oby lepiej, gdyby poszed³ gdzie indziej.}
{414} {} {Hmm, nie wysz³o w najczystszy sposób. Ale ten problem to ju¿ przesz³oœæ. Bywaj.}
{415} {} {Badi splaci³ swoje d³ugi w kasynie. Wkrótce zap³aci czynsz.}
{416} {} {Brzmi œwietnie! Jak uda³o ci siê naprawiæ jego mózg?}
{417} {} {Najwa¿niejsze jest, aby znaleŸæ w³aœciwe podejœcie do ka¿dego klienta.}
{418} {} {Dobra robota. A ju¿ myœla³em, ¿e nic go nie uchroni przed krwawym rozrachunkiem. Wiesz, ci bramkarze w kasynie to prawdziwe bestie. Dziêki za pomoc.}
{419} {} {Nie ma za co, Vernon.}

{420} {} {Wszystkie Twoje problemy zosta³y rozwi¹zane. Jak jeszcze mogê pomóc?}
{421} {} {Nie mogê uwierzyæ, ¿e pomagasz nam, biednym ludziom za darmo. Jesteœ niezwyk³¹ osob¹. Ale to by³y ma³e rzeczy w porównaniu z tym, co musimy znosiæ dzieñ w dzieñ.}
{422} {} {O czym ty mówisz?}
{423} {} {Naszym g³ównym problemem jest gang Czerwonych Kardyna³ów. W rzeczywistoœci s¹ w³aœcicielami ca³ego obszaru i wszystkich jego mieszkañców. Nikt tu nie oœmiela siê im przeciwstawiaæ. Nawet najemnicy z gildii nie chc¹ siê w to mieszaæ. Nikt o nas nie dba, a gang stale siê powiêksza i wywiera na nas presjê.}
{424} {} {Jesteœ szalony. Czy ty w ogóle rozumiesz, o co prosisz?}
{425} {} {Proszê? Nie, tylko narzekam. Eliminacja takiego gangu brzmi fantastycznie. Ale ty ju¿ tyle dla nas zrobi³eœ. A mo¿e masz jakiœ pomys³? W³aœciwie to zrzucilibyœmy wszystkie nasze ostatnie kapsle za g³owê Orrisa. Bez niego gang siê rozpadnie. To da przynajmniej trochê wytchnienia nam, zwyk³ym mieszkañcom.}
{426} {} {To zadanie wymaga przemyœlenia. Do zobaczenia póŸniej, Vernon.}
{427} {} {Ok, pomogê ci. Mam nadziejê, ¿e otrzymam za to sowit¹ zap³atê.}
{428} {} {Chcesz siê pozbyæ gangu? Jasne, spoko. Te uliczne psy nie widzia³y jeszcze prawdziwej walki.}
{429} {} {Och! Oddamy wszystkie kapsle, które mamy, jeœli zabijesz ich przywódcê, Orrisa. Bez niego gang os³abnie. To da przynajmniej trochê wytchnienia nam, zwyk³ym mieszkañcom.}
{430} {} {Nie martw siê. Zajmê siê tym problemem.}
{431} {} {Przygotuj kapsle, bo wezmê WSZYSTKO, co masz za jego g³owê.}
{432} {} {Powiedz mi wiêcej o Czerwonych Kardyna³ach i ich gangu.}
{433} {} {Gang jest w³aœcicielem ca³ego tego obszaru. S¹ w nim dziesi¹tki ludzi. S¹ dobrzy w walce i maj¹ broñ. Ich przywódc¹ jest Orris. Okropny typ, nikomu nie odpuszcza. Ani nam, ani samym bandytom. Proszê, oszczêdŸ nas od jego chaosu. Oprócz Ciebie nikt inny nie zechce nam pomóc.}
{434} {} {Orris ju¿ nie ma tu interesu. Jego gang traci w³adze.}
{435} {} {Jesteœ prawdziwym bohaterem! Od tak dawna liczyliœmy na cud, a teraz TY dajesz nam nadziejê na nowe ¿ycie. Dziêkujê bardzo.}
{1435} {} {Jesteœ prawdziw¹ bohaterk¹! Od tak dawna liczyliœmy na cud, a teraz TY dajesz nam nadziejê na nowe ¿ycie. Dziêkujê bardzo.}
{436} {} {Dobrze. Najwa¿niejsze, ¿e teraz nikt ci nie grozi.}
{437} {} {Pieprzyæ te ³zawe s³owa. Dawaj kapsle. Myœlisz, ¿e podejmujê takie ryzyko z dobroci serca?}
{438} {} {Uh, tak, weŸ te kapsle, jest ich tutaj 217. To wszystko, co uda³o nam siê zebraæ.}
{439} {} {Idioto! Gdybym wiedzia³, ¿e tak ma³o mi zap³acisz to nawet bym nie ryzykowa³. Có¿, muszê wzi¹æ to, co masz.}
{1439} {} {Idioto! Gdybym wiedzia³a, ¿e tak ma³o mi zap³acisz to nawet bym nie ryzykowa³a. Có¿, muszê wzi¹æ to, co masz.}
{440} {} {Lepsze to ni¿ nic.}
{441} {} {Przepraszam za tak ma³¹ kwotê. Mo¿esz spêdziæ noc w naszym domu tak d³ugo, jak chcesz.}
{442} {} {Do widzenia Vernon.}
{443} {} {Kapsle oddaj ka¿demu, od kogo je masz. Sprawiedliwoœæ by³a dla mnie najwa¿niejsza.}
{444} {} {Jesteœ niezwyk³¹ osob¹. Wiedz, ¿e w naszym domu zawsze jesteœ mile widzianym goœciem.}
{445} {} {Do widzenia Vernon.}
{446} {} {Dziêki za pomoc Larry'emu i Badiemu, oczywiœcie, ale lepiej odejdŸ. Przepraszam, ale nie chcê mieæ z tob¹ nic wspólnego.}
{447} {} {To bardzo niemi³o z twojej strony.}
{448} {} {Mog³o byæ gorzej, kolego.}