{100} {} {Widzisz æpuna.}
{101} {} {Widzisz rozczochranego faceta. Wygl¹da na to, ¿e kiepsko sobie radzi.}
{102} {} {Ach... Nie mogê oddychaæ...}

# Odpowiedzi po wyleczeniu
{110} {} {Zostaw mnie w spokoju.}
{111} {} {Muszê spaæ.}
{112} {} {Jutro zacznê nowe ¿ycie.}
{113} {} {Masz jakieœ prochy?}
{114} {} {Nikomu nie powiesz, prawda?}

{115} {} {(rozgl¹da siê) Mo¿emy byæ œledzeni.}
{116} {} {Dlaczego zabili Gonzaleza?}
{117} {} {Gonzalez coœ dosta³, ale nie mam nic do wymiany.}
{118} {} {Obserwatorzy musieli zabiæ Gonzaleza.}
{119} {} {Jeœli dotr¹ do Gonzaleza, to te¿ bêdê w niebezpieczeñstwie.}

# Pierwszy dialog
{200} {} {(wzdrygaj¹c siê, jakby mia³ gor¹czkê) C-co ty?}
{201} {} {Nie wygl¹dasz dobrze. Coœ ci jest?}
{202} {} {Czujê siê d-doskonale o-ok.}
{203} {} {Nie mogê w to uwierzyæ.}
{204} {} {S-s³uchaj, nic mi nie jest. Zostaw mnie.}
{205} {} {Cokolwiek powiesz.}
{206} {} {Bardzo chêtnie. Jeszcze siê zara¿ê.}
{207} {} {Nie tak szybko. Proszê najpierw odpowiedzieæ na moje pytania.}

# Powtarzajacy siê dialog
{210} {} {Och, dajcie m-mi.}
{211} {} {Do widzenia.}

{212} {} {Znowu?}
{213} {} {Widzê, ¿e wszystko w porz¹dku. Wygl¹dasz lepiej ni¿ wtedy, gdy siê ostatnio spotkaliœmy.}
{214} {} {Jest gorzej ni¿ kiedykolwiek! Nie ma Gonzaleza i teraz nie ma gdzie dostaæ leków, które przygotowywa³. Gdzie otrzymam now¹ dawkê?}
{215} {} {Kiedy to siê skoñczy, nie bêdziesz chcia³ do tego wracaæ. O to chodzi. Bywaj.}
{216} {} {Dok³adnie. I dziêkujê, ¿e nie pod¹¿y³eœ za swoim dilerem.}

{220} {} {Kim ty w³aœciwie jesteœ?}
{221} {} {Ja? Jestem Larry. Co?}
{222} {} {Co robisz, Larry?}
{223} {} {Dlaczego mi przeszkadzasz? Po prostu tu mieszkam i zarabiam tyle, ile muszê.}
{1223} {} {Dlaczego mi przeszkadzasz? Po prostu tu mieszkam i zarabiam tyle, ile muszê.}
{224} {} {Wygl¹da na to, ¿e w ogóle nic nie robisz. Bywaj.}
{225} {} {Przykro mi, ¿e jest jest jest. Nie rozpaczaj.}

{230} {} {Nie wygl¹dasz dobrze. Potrzebujesz lekarza.}
{231} {} {Nie potrzebujê lekarza! Wszystko ze mn¹ w porz¹dku! Zostaw mnie!}
{232} {} {Wow, nie denerwuj siê tak...}
{233} {} {Pozwól, ¿e ciê zbadam, jestem lekarzem.}
{234} {} {Nie potrzebujê lekarza, tylko lekarstwa. I znowu bêdzie dobrze.}
{235} {} {W¹tpiê. S¹dz¹c po rozszerzonych Ÿrenicach i innych objawach, jesteœ uzale¿niony od jakiegoœ rodzaju œmieci.}
{236} {} {Mo¿e tak. Czego chcesz?}
{237} {} {Kto ciê zaopatruje?}
{238} {} {Gonzalez. Wszyscy wiedz¹, ¿e to on ma LEKI na ró¿ne dolegliwoœci. Ma zajebiste te leki, ale nie mam wystarczaj¹cej iloœci kapsli na now¹ dawkê. Pozwól mi odpocz¹c w pokoju, jutro bêdê jak nowy.}
{239} {} {Dobrze. To Twój problem.}

{240} {} {Wiêc wszyscy miejscowi ciê przeklinaj¹?}
{241} {} {IdŸ do diab³a! To moja sprawa, jakie dragi, znaczy leki biorê i kiedy je biorê.}
{242} {} {Jakie narkotyki bierzesz?}
{243} {} {Mieszanka œrodków psycho, œrodków przeciwbolówych i mentatów. Bior¹c to, zaczynasz widzieæ krasnoludki i lataj¹ce samochody. Tak, tak¿e krasnoludki. Maluchy. Takie maluchy... Przynajmniej mam trochê radoœci w tych pieprzonych slumsach.}
{244} {} {Dlaczego w ogóle to robisz?}
{245} {} {No wiesz, pierwotnie by³o to lekarstwo na gor¹czkê. I to naprawdê mnie z niej wyleczylo, ale potem zda³em sobie sprawê, ¿e nie mogê przestaæ tego braæ. Nie jest ³atwo zrezygnowaæ.}
{246} {} {Kto ciê zaopatruje?}
{247} {} {Wszystkie chemikalia w slumsach ma Gonzalez i padlino¿ercy.}
{248} {} {Hmm. Pójdê porozmawiaæ z tym Gonzalezem.}

{250} {} {Larry, musisz z tego zrezygnowaæ.}
{251} {} {IdŸ do diab³a. Czujê siê dobrze. Nie potrzebujê pomocy. Wiem co robiê.}
{252} {} {No có¿.}
{253} {} {Twój sprzedawca nie sprzeda ci kolejnej dawki.}
{254} {} {Co?! Ale dlaczego?}
{255} {} {Poniewa¿ musisz rzuciæ.}
{256} {} {Umrê bez lekarstw! Gdzie teraz otrzymam now¹ dawkê?}
{257} {} {Pomyœl o przysz³oœci. To nie jest opcja, Larry.}
{258} {} {Czy ty rozumiesz? Mam wszystko pod kontrol¹. Wiem, kiedy przestaæ.}
{259} {} {No có¿.}
{260} {} {Przestañ zatruwaê swoje ¿ycie. Twoja ¿ona i dzieci ciê potrzebuj¹, Larry.}
{261} {} {Tak... Zapomnia³em o nich... Co za g³upiec... Dziêki, spróbujê zacz¹æ od nowa.}
{262} {} {Mam nadziejê. Zegnaj Larry.}
{263} {} {Jeœli bêdziesz kontynuowaæ w ten sposób, umrzesz.}
{264} {} {Twoje cia³o jest ju¿ na krawêdzi wytrzyma³oœci, Larry. Wkrótce umrzesz.}
{265} {} {Jesteœ lekarzem? Dlaczego, do diab³a, mnie tak straszysz?}
{266} {} {Tak, jestem lekarzem. I mówiê prawdê.}
{267} {} {Cholera... Wiem, ¿e nie zosta³o mi du¿o czasu. Ale nie mogê przestaæ. Co powinienem zrobiæ?}
{268} {} {Có¿, mo¿esz zneutralizowaæ na³óg innym na³ogiem. Wybróbuj ten przepis.}
{269} {} {Wow, czy to pomaga? Wygl¹da na to, ¿e nie mam wyboru. Dziêki doktorze.}
{270} {} {B¹dŸ zdrów, Larry.}
{271} {} {Nie, przepraszam, nie jestem lekarzem.}
{272} {} {Te rzeczy kiedyœ ciê zabij¹. Mam mentaty. Spróbuj, mo¿e to rozjaœni ci g³owê.}