{100}{}{Widzisz przed sob¹ Boba.}
{101}{}{Widzisz œniadego mê¿czyznê z brod¹, ubranego w strój marszowy.}
{102}{}{Widzisz starego Boba. Jak zwykle oddaje siê pijañstwu.}

#Pierwszy dialog
{200}{}{Hej kolego, zagubiony?}
{1200}{}{Hej kole¿anko, zagubiona?}
{201}{}{Tak jakby. Naprawdê tu mieszkasz?}
{202}{}{(jêczy z niezadowolenia) No tak. To jest dom wspólnoty, a to mój pokój.}
{203}{}{A ty...}
{204}{}{Jestem Bob, padlino¿erca i z³ota r¹czka. Kim jesteœ i kogo tutaj szukasz?}
{205}{}{To nie twoja sprawa.}
{206}{}{Wow. Czy ty jesteœ dupkiem w moim pokoju? Nie wiem kim jesteœ, ale lepiej siê st¹d wynoœ.}
{207}{}{Nie wa¿ siê mi rozkazywaæ.}
{208}{}{Przepraszam, natychmiast opuszczê ten pokój.}
{209}{}{Nazywam siê }
{210}{}{, przychodzê z Phoenix w poszukiwaniu miejsca do spania.}
{211}{}{Zapytaj Vernona, on tu prowadzi interesy.}
{212}{}{Dziêkujê.}
{213}{}{Ok.}
{214}{}{Znowu? Mam nadziejê, ¿e nie zaczniesz tu walczyæ.}
{215}{}{Jasne, w³asœnie tego teraz najbardziej pragnê.}
{216}{}{Nie, nie zamierzam. Do widzenia.}
{217}{}{Przepraszam za ostatni raz. Jestem }
{218}{}{i szukam tu miejsca do spania.}
{219}{}{Zdecydowanie. Ale najpierw chcê z tob¹ porozmawiaæ.}

#Powtarzany dialog
{220}{}{Czeœæ.}
{221}{}{Czego chcesz?}
{222}{}{Szukasz czegoœ?}
{223}{}{Tak?}

{225}{}{Trzymaj siê ode mnie z daleka. Nie chcê byæ widziany obok ciebie.}
{226}{}{Nie powinieneœ samotnie wêdrowaæ po tym niebezpiecznym obszarze.}
{227}{}{Nie wiem, czego chcesz, ale lepiej odejdŸ.}
{228}{}{}
{229}{}{Do zobaczenia Bob.}

{230}{}{Hej, œwietna walka, }
{231}{}{. Walczysz jak Zelazny Mike. Szkoda, ¿e siê nie za³o¿y³em, by³bym bogaty.}
{232}{}{Wiem. Zamknij siê.}
{233}{}{Dziêkujê za wsparcie, Bob.}
{234}{}{Wiesz, to by³a zwyk³a walka. Nic specjalnego.}
{235}{}{Tak jak mówisz, mistrzu. Tak jak mówisz.}
{236}{}{Hmm.}

#pytania - o padlino¿erców
{250}{}{Powiedzia³eœ, ¿e pracowa³eœ jako padlino¿erca.}
{251}{}{(z niedowierzaniem) T-tak. I co?}
{252}{}{Tylko pytam. Czy mo¿esz mi przekazaæ najnowsze wiadomoœci?}
{253}{}{Ech, nic.}
{254}{}{Tak, to by³ z³oty wiek, kiedy padlino¿ercy zalewali ruiny Phoenix. Teraz tylko naprawdê niebezpieczne obszary z wysokim promieniowaniem pozosta³y nietkniête... Coœ jeszcze?}
{255}{}{Opowiedz mi o padlino¿ercach.}
{256}{}{Naprawdê nie wiesz o nas? Hmm, w³aœciwie jesteœmy doœæ niepozorni.}
{257}{}{By³em w Garage City, gdzie mieszkaj¹ te¿ inni padlino¿ercy.}
{258}{}{Ach, stary Kogan musia³ ju¿ zwariowaæ, prawda? Och, wielu posz³o tam do pracy, kiedy powsta³ ca³y ten szum z oddzia³em. Ba³em siê jechaæ w tak d³ug¹ podró¿. A teraz nie ma sensu iœæ - mówi¹, ¿e oddzia³ nie ¿yje.}
{259}{}{Wiêc co robisz?}
{260}{}{Pierwszy raz o tym s³ysza³em. Co robisz?}
{261}{}{}
{262}{}{Och, to ty... uh, padlino¿ercy... prawda. Porozmawiamy o czymœ innym?}
{263}{}{Przeszukujemy ruiny w poszukiwaniu kosztownoœci, a nastêpnie sprzedajemy je na rynku lub klientom. To niebezpieczna i ciê¿ka praca. Dlatego do pracy na du¿¹ skalê padlino¿ercy zjednoczyli siê w ca³¹ gildiê.}
{264}{}{W ogóle op³aca³a siê ta praca?}
{265}{}{Oczywiœcie. Miasto ros³o i wymaga³o coraz wiêcej rzeczy. Teraz jednak niewiele pozosta³o w ruinach. W ostatnich latach szuka³em g³ównie czêœci elektronicznych oraz ksi¹¿ek dla czcicieli ognia.}
{266}{}{Przy okazji, czy mo¿esz mi opowiedzieæ o najnowszych wiadomoœciach w mieœcie?}
{267}{}{Czêœci i ksi¹¿ki? Zyczê Ci sukcesów. I chyba ju¿ czas na mnie.}

{270}{}{Czy wiesz coœ o Kryptach?}
{271}{}{Kryptach? O czym ty mówisz? Ka¿da piwnica mo¿e Ci robiæ za kryptê.}
{272}{}{Nie, nie, mówiê o Wielkich Kryptach.}
{273}{}{Ach, projekt Vault-Tec. Natkn¹³em siê na jedn¹ z nich, numer 26.}
{274}{}{Naprawdê? A gdzie to by³o?}
{275}{}{W zachodnich ruinach, na skraju krateru. Gildia Smieciarzy wys³a³a tam kiedyœ wyprawê, ale kryjówka by³a tak zniszczona, ¿e wróciliœmy z pustymi rêkoma.}
{276}{}{Przykro mi to s³yszeæ. A co z innymi Kryptami?}
{277}{}{Nie mo¿esz siê doczekaæ znalezienia prawdziwego skarbu, co? Wielu próbowa³o, ale znaleŸli tylko raka mózgu. Albo kulkê od jakiegoœ bandyty. Jeœli ktoœ coœ wie o tych schronach, to na pewno s¹ to czciciele ognia. Ale niechêtnie dziel¹ siê informacjami.}
{278}{}{Dziêki, mo¿e mi pomog¹.}
{279}{}{Niewiele mi to pomaga, stary pierdzielu.}
{280}{}{Zrozumiano. Czy mo¿emy porozmawiaæ o czymœ innym?}

{290}{}{Czy mo¿esz nauczyæ mnie kilku sztuczek?}
{291}{}{Nie chcê ciê niczego uczyæ. Nie lubiê ciê. Spacerujesz po mieœcie i sprawiasz k³opoty. Jakiœ cazador u¿¹dli³ ciê w dupê?}
{292}{}{Uch, zmieñmy temat.}
{293}{}{Zapomnij o tym.}
{294}{}{Zaufaj mi, to niebezpieczna i niewdziêczna praca.}
{295}{}{Wygl¹da na to, ¿e po prostu nie chcesz ze mn¹ zadzieraæ.}
{296}{}{Niestety. Nie lubiê ciê.}
{297}{}{Rozumiem. Mam nadziejê, ¿e kiedyœ zmienisz zdanie.}
{298}{}{Jasne, Bob. Te¿ ciê nie lubiê.}
{299}{}{Du¿o podró¿ujê. Przyda³aby mi siê twoja wiedza.}
{300}{}{Oczywiœcie. Ja co prawda ju¿ nie podró¿ujê tyle co kiedyœ, ale mogê opowiedzieæ ci o ró¿nych miejscach w mieœcie tylko wtedy, gdy ci to pomo¿e.}
{301}{}{Swietnie. Pozwól mi rozwin¹æ mapê...}
{302}{}{Najtrudniejsz¹ czêœci¹ jest unikanie niepotrzebnych spotkañ.}
{303}{}{Dziêki, Bob. To mi bardzo pomo¿e.}

#pytania - co nowego
{350}{}{Hej Bob, co nowego?}
{351}{}{(mru¿y oczy) Nie pamiêtam, ¿ebyœmy siê tak dobrze dogadywali, ¿ebym opowiada³ Ci lokalne wiadomoœci.}
{352}{}{Powiedzia³eœ, ¿e jesteœ padlinozerc¹?}
{353}{}{Rozumiem, w takim razie zatrzymajmy siê.}
{354}{}{Nasze getto jest nadal takie samo jak ostatnim razem. Gangi, kultyœci i bieda.}
{355}{}{Rozumiem. Nie rozmawiajmy o z³ych rzeczach.}
{356}{}{Co powiesz mi o tutejszych gangach?}
{357}{}{Ca³y teren kontroluje gang Czerwonych Kardyna³ów. Jest kilka innych ma³ych gangów, ale boj¹ siê tu wejœæ.}
{358}{}{Co wyznawcy ognia troszcz¹ siê o twoj¹ okolice?}
{359}{}{Co wyznawcy ognia troszcz¹ siê o twoj¹ okolice?}
{360}{}{Chc¹ przej¹æ ca³e miasto. Slumsy s¹ dla nich tylko Ÿród³em taniej si³y roboczej. Wszystko to jest przykryte dobroczynnymi misjami zbierania ja³mu¿ny dla potrzebuj¹cych, ale my sami potrzebujemy wiêcej ni¿ ktokolwiek w mieœcie.}
{361}{}{Nie wierzysz im?}
{362}{}{(rozgl¹da siê) Ups! Lepiej nie pytaj o kultystów, jeœli nie chcesz mieæ z nimi k³opotów.}
{363}{}{Co mówi³eœ o tutejszych gangach?}
{364}{}{Czy wszystko jest takie powa¿ne? Naucze siê tego.}
{365}{}{}
{366}{}{No dalej, powiedz mi, wszyscy tu s¹ przyjació³mi.}
{367}{}{(potrz¹sa g³ow¹ z bólu) Powa¿nie w to w¹tpiê.}
{368}{}{Masz racjê.}
{369}{}{Z³a suka.}
{370}{}{Potrafiê o siebie zadbaæ. I o Ciebie te¿. Powiedz mi, co jest nie tak z tymi ludŸmi?}
{371}{}{Ci z Koœcio³a nie s¹ tym, czym siê wydaj¹. Na zewn¹trz wygl¹daj¹ jak dobroduszne prostaczki i mówi¹ o korzyœciach p³yn¹cych z czytania i pisania. Ale za murami Katedry staj¹ siê cichymi samotnikami. Co siê dzieje na ich tajnych spotkaniach, wiedz¹ tylko oni.}
{372}{}{Kontynuuj.}
{373}{}{Wiem, ¿e gromadz¹ przedwojenn¹ wiedzê i technologie. Mówi¹, ¿e w ten sposób staraj¹ siê o¿ywiæ œwiat. Ale zwykli œmiertelnicy nie mog¹ tego wszystkiego zrobiæ. A bior¹c pod uwagê, ¿e Aaron doszed³ do w³adzy poprzez rewolucjê pod sztandarem Swiêtego Ognia, nietrudno wyci¹gn¹æ pewne wnioski na temat ich prawdziwych intencji.}
{374}{}{O¿ywiæ œwiat?}
{375}{}{Tak, ale wiesz, wojna nigdy siê nie zmienia. Tutaj ju¿ jest tak samo jak przed Wielk¹ Wojn¹. Nikt nie dba o zwyk³ych ludzi. Ci, którzy próbowali sprzeciwiæ siê Koœcio³owi, koñczyli w ciê¿kich robotach lub w ogniu karnym. A jeœli uda ci siê do³¹czyæ do szeregów Wyznawców, mo¿esz stamt¹d wyjœæ tylko jako trup.}
{376}{}{Brzmi z³owieszczo.}
{377}{}{Nawiasem mówi¹c, niektórzy zauwa¿yli, ¿e wiêcej ludzi wchodzi do Katedry ni¿ wychodzi. Nie wiem z czym to siê wi¹¿ê. Ale kr¹¿¹ plotki, ¿e budynek jest w rzeczywistoœci wiêkszy ni¿ siê wydaje i ma po³¹czenie z podziemnymi korytarzami. Pewnie tak jest. Ale trzymaj gêbê na k³ódkê. Niektórzy z bardziej wygadanych lubi¹ znikaæ.}
{378}{}{W takim razie nie poruszajmy tego ponownie.}
{379}{}{Nie mogê uwierzyæ w twoje historie, smieciarzu Bob. Do widzenia.}
{380}{}{K³amali, ¿e katedra by³a u¿ywana wy³¹cznie do celów pokojowych. Pod budynkiem znajdowa³ siê ca³y kompleks z broni¹ j¹drow¹. A po eksplozji wielu mieszkañców nabra³o odwagi i zaczê³o mówiæ o tym, jak zastraszali ich sekciarze. Oczywiœcie im nie wierzê. Nikt im teraz nie wierzy.}
{381}{}{Rozumiem. Mo¿e jeszcze kilka pytañ?}
{382}{}{Szkoda, ¿e nie znasz ca³ej historii. Do widzenia, Bob.}