{100} {} {Widzisz bandytê.}
{101} {} {Widzisz zawadiackiego m³odego mê¿czyznê.}
{102} {} {To Twój motor? Oh przepraszam. Wydawa³o mi siê, ¿e jest niczyj. Oczywiœcie, weŸ go sobie, nie mam nic przeciwko.}
{103} {} {Spierdalaj.}
{104} {} {Hej, to twój motor?}

{200} {} {Hej, to Twój motor?}
{201} {} {Dok³adnie.}
{202} {} {Mo¿e tak. Co chcesz?}
{203} {} {Mylisz siê. To jest mój motor. Jakieœ problemy? Och, prawdopodobnie chcesz go KUPIC. Dobry wybór. Cena to 500 kapsli. Poœpiesz siê, zanim zmieniê zdanie.}
{204} {} {Dlaczego go potrzebujesz? I tak pewnie nie potrafisz go u¿yæ.}
{205} {} {Czy bierzesz mnie za idiotê? Ka¿dy szef w mieœcie bêdzie zainteresowany tym motorem. Jeœli nie zap³acisz, zap³aci ktoœ inny.}
{206} {} {Daj mi mój motocykl. Teraz proszê grzecznie, ale za drugim razem zrobi siê nieprzyjemnie.}
{207} {} {Daj mi czas na zebranie kapsli.}

{210} {} {Masz te 500 kapsli?}
{1210} {} {Masz te 500 kapsli?}
{211} {} {Masz te 700 kapsli?}
{1211} {} {Masz te 700 kapsli?}
{212} {} {Daj mi czas na zebranie kapsli.}

{220} {} {To mój motocykl. Daj mi kluczyk do stacyjki. Natychmiast.}
{221} {} {I co potem? Odjedziesz sobie? Masz pecha, nasz gang * posiada * ca³y ten obszar. Masz problem ze mn¹ - masz problem z ca³ym gangiem. Rozumiesz?}
{222} {} {Nie obchodzisz mnie ani ty, ani twój gang. Daj mi klucz albo umrzesz.}
{223} {} {Przepraszam, nie chcê problemów z tob¹ i twoimi ch³opakami.}
{224} {} {Swoj¹ drog¹, zmieni³em zdanie. Cena wzros³a do 700 kapsli.}
{225} {} {Gr-rm...}
{226} {} {Jebaæ to. Po prostu ciê zabijê.}

{230} {} {Oto kapsle. Teraz oddaj kluczyk.}
{231} {} {(od niechcenia rzuca klucz na ziemie) WeŸ to. I tak nie wiem jak z tego korzystaæ. (z uœmiechem idzie w g³¹b dzielnicy, podrzucaj¹c sakiewk¹ z kapslami)}
{232} {} {Dziêki, hm, dobry zakup.}
{233} {} {Pewnego razu bêdê czeka³ na ciebie w nocy i poder¿nê ci gard³o. I bêdê siê œmiaæ. Tak, œmiaæ siê.}
{234} {} {Nie tak szybko, draniu. A teraz oddaj mi wszystkie moje kapsle.}

{240} {} {Jesteœ g³upcem, staj¹c na drodze mistrza. Chcesz siê o tym przekonaæ?}
{241} {} {Jesteœ g³upcem, staj¹c naprzeciw Wyznawcy. Moi bracia nie zostawi¹ tak tego.}
{242} {} {S³ysza³eœ o bandytach z autostrad? Jestem jednym z nich. Lepiej nas nie lekcewa¿.}
{243} {} {Zachowuje siê jak osaczony pies) Cholera, nie wiedzia³em... Przepraszam, oto klucz... Czy teraz wszystko w porz¹dku? Lepiej ju¿ sobie pójdê.}
{244} {} {Wynoœ siê.}
{245} {} {Nie ma problemu. Zapomnijmy o tym nieporozumieniu.}
