{100}{}{Widzisz dziecko ze slumsów.}
{101}{}{Widzisz dziecko z lokalnych slumsów. Zycie wiele je nauczy³o.}

{110}{}{Czeœæ.}
{111}{}{Masz broñ?}
{112}{}{Tata obieca³, ¿e nied³ugo dostanie broñ. Wtedy zabije wszystkich, którzy Ÿle mnie traktowali.}
{113}{}{Kiedy dorosnê, zostanê alfonsem.}
{114}{}{Jak siê masz?}
{115}{}{Nie znam ciê.}
{116}{}{Czego chcesz?}
{117}{}{Nie dotykaj mnie.}
{118}{}{Nie wolno mi rozmawiaæ z nieznajomymi.}
{119}{}{Dasz mi coœ?}