{100} {} {Widzisz Badiego.}
{101} {} {Widzisz zwyk³ego ¿ebraka, który jest niezdolny do czegokolwiek. Zaskakuj¹ce, ¿e wci¹¿ ¿yje.}
{102} {} {Witaj partnerze. Jak siê masz?}

{200} {} {Jest tutaj. Uwa¿aj, w œrodku musz¹ byæ roboty. Jeœli siê ich pozbêdziesz, wszystkie kapsle bêd¹ nasze.}
{201} {} {Wiêc nie traæmy czasu. Zaczekaj tutaj.}
{202} {} {Wiem to i bez ciebie.}
{203} {} {Najpierw muszê wiedzieæ wiêcej o tym miejscu.}

{210} {} {Nie stój tutaj zbyt d³ugo.}
{211} {} {Zaczekaj tutaj.}
{212} {} {Nadchodzi noc. Poœpieszmy siê, dobrze?}

{220} {} {Co to w³aœciwie za miejsce?}
{221} {} {Przedwojenna atomowa hurtownia coli. Podobno trunek by³ tu przechowywany, a nastêpnie transportowany do sklepów. Sama fabryka, w której by³a butelkowana, zosta³a zniszczona przez wybuch j¹drowy.}
{222} {} {Zastanawiam siê, dlaczego to miejsce nie zosta³o jeszcze spl¹drowane przez padlino¿erców?}
{223} {} {Trudno siê tu dostaæ ze wzglêdu na otaczaj¹ce ruiny, wiêc wielu ludzi po prostu o tym nie wie. Ponadto w pobli¿u znajduje siê strefa zniszczenia wybuchu j¹drowego, wielu jest przestraszonych tym faktem. No i oczywiœcie te cholerne roboty.}
{224} {} {Jakieœ pomys³y, jak wy³¹czyæ te roboty?}
{225} {} {Myœla³em, ¿e to ty siê tym zajmiesz. Gdzieœ w œrodku musi byæ prze³¹cznik lub coœ w tym rodzaju. Nie rozumiem technologii. Tym bardziej przedwojennej. Nikt w ogóle tego nie rozumie, z wyj¹tkiem ludzi z Katedry.}
{226} {} {Przypomnij mi, czego szukamy?}
{227} {} {Kapsli! Wielu, wielu kapsli do butelek.}
{228} {} {Rozumiem.}
{229} {} {Wkrótce wrócê.}

{250} {} {Oto wszystkie kapsle z magazynu.}
{251} {} {Pe³ne pude³ko? Cholera, ale fortuna! Mamy szczêœcie! Jesteœmy teraz bogatsi ni¿ wiêkszoœæ mieszkañców miasta, czy mo¿esz to sobie wyobraziæ?}
{252} {} {Nie tak szybko. Najpierw sp³aæ d³ug z kasyna.}
{253} {} {O tak. Uh, dok³adnie. Z radoœci zupe³nie o tym zapomnia³em. Proszê.}
{254} {} {Swietnie. Teraz daj mi moj¹ czêœæ - po³owê tego, co zosta³o.}
{255} {} {Ugh, okazuje siê, ¿e zostanie mi mniej ni¿ siê spodziewa³em. Pozosta³e kapsle ledwo wystarcz¹ na op³acenie czynszu i innych d³ugów. I znowu znajdê siê bez niczego.}
{256} {} {Trudno, d³ugi nale¿y sp³acaæ. Przynajmniej wyjdziesz na zero. Teraz czas wracaæ do miasta. Czeœæ.}
{257} {} {Wiesz, zmieni³em zdanie. Biorê WSZYSTKIE kapsle dla siebie.}
{1257} {} {Wiesz, zmieni³am zdanie. Biorê WSZYSTKIE kapsle dla siebie.}
{258} {} {Nie! Nie mo¿esz tego zrobiæ! Jesteœmy partnerami, pokaza³em ci to miejsce... Cholera, kiedyœ... pewnego dnia zarobiê du¿o kapsli i zatrudniê najemników na twoj¹ g³owê. A potem zagram ni¹ w pi³kê. Zobaczysz.}
{259} {} {Niesamowite. Zegnaj frajerze.}
{260} {} {W takim razie nie pozostawiasz mi wyboru - muszê ciê za³atwiæ.}
