{100} {} {Widzisz Badiego.}
{101} {} {Widzisz zwyk³ego ¿ebraka, który jest niezdolny do czegokolwiek. Zaskakuj¹ce, ¿e wci¹¿ ¿yje.}
{102} {} {Witaj partnerze. Jak siê masz?}
{103} {} {Któregoœ dnia zemszczê siê na tobie.}

{110} {} {Jestem beznadziejny.}
{111} {} {Mam doœæ.}
{112} {} {Zosta³ mi tylko jeden kapsel.}
{113} {} {Straci³em ostatniego kapsla w kasynie.}
{114} {} {Nie wiem, jak wyjdê z d³ugów.}
{115} {} {Zubo¿a³em w ci¹gu kilku dni.}
{116} {} {To mo¿e byæ ostatni dzieñ mojego ¿ycia.}
{117} {} {Po¿yczysz mi tysi¹c kapsli? Oddam to, stary, s³owo.}
{118} {} {Wygl¹da na to, ¿e wkrótce zostanê niewolnikiem.}
{119} {} {Wkrótce wylecê na ulicê.}

{200} {} {Huh, nie strasz mnie tak. Ostatnio unikam obcych.}
{201} {} {Kim jesteœ?}
{202} {} {Nazywam siê Badi, mieszkam tutaj. Ale ciebie nie kojarzê.}
{203} {} {Nie b¹dŸ dla mnie niegrzeczny, œmieciu.}
{204} {} {Có¿, czeœæ Badi. Jestem }
{205} {} {.}

{210} {} {Czego ode mnie chcesz?}
{211} {} {Od Ciebie? Niczego. Na razie.}

{220} {} {Vernon jest zmêczony twoimi niekoñcz¹cymi siê d³ugami. Zap³aæ lub opuœæ to miejsce.}
{221} {} {Nie, proszê, nie wyrzucaj mnie! Zap³acê Vernonowi, potrzebujê tylko trochê czasu, aby sp³aciæ kasyno.}
{222} {} {Jesteœ zad³u¿ony w kasynie?}
{223} {} {No tak. Przyznajê, ¿e to by³o g³upie. Nie powinienem liczyæ na szczêœcie. Ale tego dnia mia³em takiego farta, ¿e nie mog³em przestaæ.}
{224} {} {Nie obchodzi mnie, co tam masz. ChodŸ, zaczerpnij œwie¿ego powietrza.}
{225} {} {Mieszkam tu od lat! Czy tak Vernon traktuje swoich goœci? Ok, zobaczmy, kto wygra.}
{226} {} {WyprowadŸ siê st¹d.}
{227} {} {Rozumiem. Ile jesteœ winien Vernonowi?}
{228} {} {37 kapsli z ostatniego kwarta³u.}
{229} {} {Wiem, jak to jest straciæ dom. Nie martw siê o kapsle, zap³acê za czynsz.}
{230} {} {Naprawdê? Niech ciê Bóg b³ogos³awi! Dziêkujê Ci! Dziêkujê Ci!}
{231} {} {To dla mnie ma³a rzecz. Nazywam siê }
{232} {} {. Zapamiêtaj moje imiê.}
{233} {} {Do widzenia.}
{234} {} {Ok, dam ci trochê wiêcej czasu.}
{235} {} {Naprawdê? Dziêkujê Ci! Nied³ugo przygotujê kapsle, obiecujê.}
{236} {} {Postaraj siê jak najlepiej.}

{250} {} {Jesteœ winien kasê w kasynie. Czas zap³aciæ rachunki.}
{251} {} {Da³em wszystko, co mia³em! Nic mi nie zosta³o! Proszê, daj mi trochê wiêcej czasu. Zarobiê te kapsle!}
{252} {} {Mia³eœ wystarczaj¹co du¿o czasu. Masz taki problem z za³atwieniem kapsli?}
{253} {} {W mieœcie jest bezrobocie, moja reputacja równie¿ zosta³a nadszarpniêta przez d³ugi. Przetrwaæ mogê tylko zbieraj¹c œmieci z ruin.}
{254} {} {Wygl¹da na to, ¿e naprawdê nie masz nic do oddania. Tkwij dalej w swoim gównie.}
{255} {} {Jeœli chcesz powstrzymaæ moj¹ piêœæ, powiedz mi coœ co zmieni moje zamiary.}
{256} {} {Czekaj, nie idŸ tak daleko. Jeœli Don Diego chce odzyskaæ swoje kapsle, potrzebuje mnie ca³ego i zdrowego. Prawda? A jeœli nie, to ju¿ dawno wys³a³by mnie do niewoli. Czy mo¿esz dowiedzieæ siê, o co chodzi?}
{257} {} {Cholera, marnujê z tob¹ tylko czas.}
{258} {} {Jak zamierzasz sp³aciæ swoje d³ugi?}
{259} {} {Mam plan. Potrzebujê tylko trochê czasu na przygotowanie.}
{260} {} {Co, to kolejne twoje k³amstwo?}
{261} {} {Co planujesz? No weŸ, powiedz mi.}
{262} {} {Przestañ mnie oszukiwaæ. Dawaj kapsle albo po³amiê ci koœci.}
{263} {} {Um, s³uchaj, ty te¿ mo¿esz zarobiæ przy tym pieni¹dze. Jak widaæ, Don Diego nie zatrudnia byle kogo.}
{264} {} {Zaciekawi³eœ mnie. Powiedz mi wiêcej.}
{265} {} {Twoja bezczelnoœæ nie zna granic. Ale pos³ucham, co wymyœli³eœ tym razem.}
{266} {} {Jest takie miejsce, w którym s¹ GORY kapsli. Nie k³amiê, to prawda. Nikt o nim nie wie oprócz mnie. Pójdziemy tam, otworzymy magazyn i zabierzemy wszystko, co ocala³o, a potem podzielimy kapsle pó³ na pó³. Co ty na to?}
{267} {} {Coœ tu jest nie tak. Dlaczego nie zrobi³eœ tego wczeœniej?}
{268} {} {Brzmi zbyt dobrze. Powiedz mi od razu - jaki jest haczyk?}
{269} {} {Jest jedna przeszkoda. Wygl¹da na to, ¿e magazynu pilnuje kilka starych robotów. Niektórzy ju¿ próbowali przejœæ obok nich i nie prze¿yli. Ale Ty na pewno dasz im radê. Najwa¿niejsze to wzi¹æ odpowiedni¹ broñ.}
{270} {} {Wow, to brzmi naprawdê obiecuj¹co. Gdzie to jest?}
{271} {} {Pewnie znowu mnie ok³amujesz. Lepiej najpierw poka¿ mi to miejsce.}
{272} {} {Uh, nie, a co jeœli mnie oszukasz? Dla mnie to jedyny sposób na sp³atê d³ugu. Dlatego potrzebujê wiarygodnych partnerów do takiej sprawy, kogoœ takiego jak ty. To co Ty na to? Pójdziesz ze mn¹?}
{273} {} {Potrzebujê trochê czasu, ¿eby siê przygotowaæ.}
{274} {} {Oczywiœcie. WeŸ broñ przeciwko robotom, ale nie bierz nic wiêcej. Tak, nawiasem mówi¹c, to miejsce jest w strefie zniszczenia nuklearnego. Wci¹¿ istniej¹ tam strefy radioaktywne, ale wiem, jak je omin¹æ.}
{275} {} {Rozumiem. Do zobaczenia.}
{276} {} {Potrafiê przejrzeæ ludzi takich jak ty. Dzisiaj wyjdê spokojnie, ale nastêpnym razem wrócê z kijem baseballowym.}
{277} {} {Hej, ja tylko oferujê biznes. To zwyk³a umowa partnerska, wiesz? Nie chcesz to nie, ale mo¿e przemyœl moj¹ propozycjê raz jeszcze.}
{278} {} {Wrócê.}

{280} {} {O Twojej propozycji. Mogê sprawdziæ ten magazyn.}
{281} {} {Tak, œwietnie! Na pewno nie po¿a³ujesz. ChodŸ, chcê jak najszybciej sp³aciæ ten d³ug.}
{282} {} {Smia³o.}