{100} {} {Widzisz sprzedawcê.}
{101} {} {Widzisz czarnego faceta z t³ustymi w³osami i brudnym fartuchem.}

# Plywajace repliki
{110} {} {Coœ p³ywa w zupie? No... to zjedz to.}
{111} {} {Wytnij tê pleœñ i w³ó¿ do zupy.}
{112} {} {Miêso kretoszczura d³ugo siê trawi.}
{113} {} {ChodŸ, zanim najlepsze co mam przepadnie.}
{114} {} {Wiêcej dodatków? Wspaniale.}
{115} {} {Swie¿e szczury! Jeszcze rano biega³y kana³ami!}
{116} {} {Cholera, ca³e cia³o mnie swêdzi.}
{117} {} {Ci pasterze w San Brahmin maj¹ strasznie wygórowane ceny.}
{118} {} {To miêso jest trochê dziwne. Ale pokochasz je.}
{119} {} {Miêso od najlepszych traperów w mieœcie!}

# Rozpocznij dialog
{200} {} {(widz¹c ciê kupiec zdezorientowany przestaje odganiaæ muchy i udaje, ¿e wcale nie lataj¹ jak chmury dooko³a restauracji) Hej, co zamierzasz zamówiæ?}
{201} {} {Co masz?}
{202} {} {Mam tylko najœwie¿sze rzeczy, prosto z pustkowi. Chcesz zupê ze szczurów? Mmm, pysznoœci! Jeszcze rano biega³y kana³ami.}
{203} {} {Uch, pozwól mi zobaczyæ...}
{204} {} {Nawiasem mówi¹c, musia³em podnieœæ ceny po ca³ym tym szumie w katedrze.}
{205} {} {Có¿, masz do tego prawo.}

{210} {} {Wiêc co zamawiasz?}
{211} {} {Nic.}
{220} {} {Bojê siê zapytaæ, ale sk¹d siê bierze to ca³e miêso?}
{221} {} {Hej, czy serio obchodzi ciê, do którego kana³u wpad³ ka¿dy szczur? S¹ do mnie sprowadzane z ca³ego miasta. Nie zamierzam za ka¿dym razem o tym mówic i ka¿demu wyjaœniaæ, ok?}
{222} {} {Nie powinienem by³ o to pytaæ...}
{223} {} {Czy masz coœ mniej obrzydliwego?}
{224} {} {Czasami padlino¿ercy przynosz¹ mi te dziwne przedwojenne dania w pude³kach. Hmm! Ale zachowujê je dla specjalnych klientów.}
{225} {} {Sprzedaj mi to zanim siê zepsuje.}
{226} {} {Sam sobie jedz t¹ przedwojenn¹ padlinê. Ja potrzebujê œwie¿ego jedzenia.}
{227} {} {Przedwojenne? W takim razie nie tego chcê.}
{228} {} {Hmm. W porz¹dku. (wyjmuje z lodówki stare pude³ka)}
{229} {} {[Dalej.]}
{230} {} {Obserwatorzy Ognia musz¹ znajdowaæ siê na liœcie „klientów specjalnych”.}
{231} {} {Myœlê, ¿e nie bêdziesz mia³ nic przeciwko hojnemu napiwkowi. Oto 10 kapsli.}
{232} {} {(uœmiecha siê pokazuj¹c swoje krzywe zêby) Dziêkujê.}
{233} {} {A co z tymi przedwojennymi daniami?}
{234} {} {Po³owa miasta mnie zna. Czy nie zas³ugujê na szacunek?}
{235} {} {Czy nie zas³uguje na szacunek?}
{236} {} {Nie wkurzaj mnie, bo rozwalê twój pieprzony zak³ad. Mogê to zrobiæ.}
{237} {} {Wiesz, jest kilku renomowanych klientów, którzy prosz¹ o od³o¿enie dla nich kilku pude³ek. Bardziej op³aca mi siê trzymaæ towary dla sta³ego klienta ni¿ sprzedawaæ je pierwszemu lepszemu.}
{238} {} {Tak naprawdê to nie chcia³em niczego.}
{239} {} {(podnosi rêce) To ¿art? Jeœli nie masz kapsli, wynoœ siê st¹d! Nie karmiê ¿ebraków.}
{240} {} {[WyjdŸ]}
{241} {} {Sk¹d tu tyle œwie¿ego miêsa, kolego?}
{242} {} {Och, pochodzi z plemienia pasterzy na zachodzie. W koñcu podjêli decyzjê i zaczêli handlowaæ z Phoenix.}
{243} {} {Myœlê, ¿e znam tê historiê.}
{244} {} {Naprawdê? W takim razie wiesz, ¿e nie k³amiê. Czyste i œwie¿e miêso! Wo³owina najwy¿szej jakoœci. Drogo, ale warto. S³uchaj, ja po jednym steku czujê siê jak ciê¿arny szczur. A-ha-ha!}
{245} {} {Tak, cieszê siê. Naprawdê mam nadziejê, ¿e wszystko bêdzie w porz¹dku.}

{250} {} {Co siê sta³o z Lloydem?}
{251} {} {Jakiœ uliczny rabuœ dŸgn¹³ go jak psa. W tym nowym garniturze wygl¹da³ na dobry cel do rabunku.}
{252} {} {Kupi³ go z moich kapsli.}
{253} {} {Có¿, to w pewnym sensie jesteœ za to odpowiedzialny, hehe... Ups.}
{1253} {} {Có¿, to w pewnym sensie jesteœ za to odpowiedzialna, hehe... Ups.}
{254} {} {Hmm. Ciekawa myœl.}
{255} {} {Uwa¿aj na jêzyk, albo pójdziesz w jego œlady.}

# Atak na obserwujacych
{300} {} {Opowiedz mi o ataku na Obserwatorów.}
{301} {} {Hej, muszê tu gotowaæ. Chcesz trochê szczurzej zupy? WeŸ porcjê, nie po¿a³ujesz.}
{302} {} {Nie mam ¿adnych kapsli do zap³aty.}
{303} {} {Nie mam czasu na rozmowê. Przepraszam.}
{304} {} {Ok, do widzenia.}
{305} {} {Swietnie, oto 10 kapsli, a teraz kiedy ja jem twoj¹ zupê, ty mo¿esz mi powiedzieæ, jak by³o. DOBRZE?}
{306} {} {Przepraszam, ale za tyle kapsli nie dostaniesz nawet ³y¿ki zupy.}
{307} {} {Uch, chyba trochê siê przeliczy³em.}
{1307} {} {Uch, chyba trochê siê przeliczy³am.}
{308} {} {Có¿, to inna historia. Jedz i nie ubrudŸ siê. O co wiêc chodzi³o?}
{309} {} {O ataku poza kasynem.}
{310} {} {Ty ¿a³osny robaku, w³ó¿ sobie w dupê tego szczura i powiedz mi jak siê czujesz.}
{311} {} {Hej, hej! Spokojnie. Przepraszam, nie przyzna³em siê.}
{312} {} {Powiedz mi co wiesz.}
{313} {} {To by³a straszna rzecz. Mnisi szli sobie ulic¹, a tu nagle ci ludzie w kominiarkach wyskoczyli zza rogów, zupe³nie jak szczury z kana³ów. Otoczyli ich i zaczêli strzelaæ z karabinów maszynowych. Nigdy nie s³ysza³em tylu strza³ów na raz. A potem uciekli, jakby to siê nigdy nie wydarzy³o. Wszystko wydarzy³o siê bardzo szybko.}
{314} {} {Rozumiem. Ale nie powinieneœ mnie ok³amywaæ, przyjacielu. Nastêpnym razem bêdziesz rozmawiaæ z moj¹ piêœci¹.}
{315} {} {Sytuacja trochê siê wyjaœni³a.}
{316} {} {Sytuacja jest dla mnie jasna. Czas porozmawiaæ o tym z Aaronem.}
{317} {} {Dziêki, bardzo pomog³eœ.}