{100} {} {Widzisz Barta Thur.}
{101} {} {Widzisz w³aœciciela sklepu z broni¹. Wydaje siê, ¿e ma obsesjê na punkcie broni.}
{102} {} {Och, to zbroja wspomagana! Tyle o niej s³ysza³em, ale nigdy jej nie widzia³em...}
{103} {} {Nie dotykaj tego. Nie obs³ugujê narkomanów. Kto wie, o czym myœlisz?}

# Rozpocznij dialog
{200} {} {(przygl¹da ci siê uwa¿nie i sceptycznie, oceniaj¹c perspektywy handlu) Jakiego rodzaju broni pan potrzebuje, sir? Do polowania czy zastraszania bandytów? Mam du¿y wybór do dowolnego celu.}
{1200} {} {(przygl¹da ci siê uwa¿nie i sceptycznie, oceniaj¹c perspektywy handlu) Czego pani szuka? Mam tu mnóstwo broni do dowolnego celu i na ka¿dym poziomie zamo¿noœci.}
{201} {} {Poka¿ mi...}
{202} {} {Pozwól, ¿e przyjrzê siê bli¿ej twojej ofercie broni.}

{210} {} {(czeka w milczeniu na twoje uwagi, czule czyszcz¹c broñ)}
{211} {} {Chyba ju¿ pójdê.}
{212} {} {Rozumiem.}

{213} {} {Ktoœ w³ama³ siê do gildii najemników i zabi³ Bruce'a Turnera.}
{214} {} {Tak, wiem.}
{215} {} {Mam nadziejê, ¿e ten sukinsyn dostanie to, na co zas³uguje. Poniewa¿ przez niego straci³em dobry zysk z gildii.}
{216} {} {Pocieszê ciê, prawdopodobnie pojawi siê nowa gildia.}
{217} {} {Wiêc sponsorowa³eœ ich broni¹? Nie powinieneœ tego robiæ.}

#Pytania
{220} {} {Sk¹d masz te broñ?}
{221} {} {Tutaj ka¿da ma swoj¹ historiê. Na przyk³ad ten rewolwer zosta³ sprzedany przez jednego pechowego gracza z kasyna. A ta broñ zosta³a odebrana miejscowym bandytom podczas szturmu na ich obóz. Coœ przywieziono karawanami z po³udnia. Ale czy serio ciê to obchodzi? Najwa¿niejsze jest to ¿eby nie zawiod³y Ciê w bitwie.}
{222} {} {Co mówi³eœ o karawanach z po³udnia?}
{223} {} {Na po³udniu jest osada Blacharzy. Ci ludzie du¿o wiedz¹ o starych technologiach i prawie siê do nich modl¹. Przebudowali maszyny, a teraz zajmuj¹ siê naprawami i produkcj¹. Na przyk³ad, oto ich dzie³o... (wyci¹ga i pokazuje)}
{224} {} {[Dalej.]}
{225} {} {Pneumatyczna w³ócznia. Napêdzana mechanizmem sprê¿ynowo-t³okowym. Zadnej elektroniki i w¹tpliwego prochu. (pompatycznie pokazuje pracê w³óczni) Naciskasz na cia³o wroga i - bum! - z w³óczni wylatuje cierñ i przebija cia³o. Nie martw siê, sam wróci na swoje miejsce za pomoc¹ sprê¿yny. Niezawodny sprzêt, ale wszystko zale¿y przede wszystkim od twoich umiejêtnoœci.}
{226} {} {Czy nadal dostajesz broñ z po³udnia?}
{227} {} {Niektórzy poszukiwacze przygód udali siê tam w poszukiwaniu cennych znalezisk. Ale prêdzej czy póŸniej ten przep³yw siê zatrzyma. Co wa¿niejsze, Blacharze nie produkuj¹ ju¿ nowej broni ani nie naprawiaj¹ starej technologii. Byli bardzo przydatni dla ca³ego Phoenix.}

# Ujawnienie produktu
{230} {} {Co masz na tych zakrytych pó³kach?}
{231} {} {Najlepsze bronie, jakie mam. Ale ten produkt czeka na wyj¹tkowych klientów. Nie jesteœ jednym z nich.}
{232} {} {Dlaczego jesteœ taki ostro¿ny?}
{233} {} {Wyznawcy ognia nie lubi¹, gdy sprzedajê dobr¹ broñ niesprawdzonym typom. Myœl¹, ¿e prêdzej czy póŸniej zostanie obrócona ona przeciwko koœcio³owi. Dlatego wszystko, co najlepsze, kupuj¹ sami wyznawcy, a tak¿e ochrona kasyna, gildia ³owców nagród i inni szanowani ludzie w mieœcie, którym mo¿na zaufaæ.}
{234} {} {Dlaczego przykry³eœ czêœæ towaru?}
{235} {} {Chcê zobaczyæ te specjalne spluwy.}
{236} {} {Przepraszam, ale najlepsze, co mam, jest przeznaczone dla specjalnych klientów. Nie jesteœ jeszcze jednym z nich.}
{237} {} {Dlaczego jesteœ tak ostro¿ny?}
{238} {} {NajwyraŸniej nie mam tu ju¿ nic innego do roboty.}
{239} {} {Dobra, zobaczê, co masz dla zwyk³ego cz³owieka takiego jak ja.}

{240} {} {Hmm... Brzmi przekonuj¹co. (ods³ania towar i rozk³ada rêce z zadowolonym spojrzeniem) Oto wszystko, co najlepsze w Phoenix...}
{241} {} {Cholera, to wystarczy, aby przej¹æ ca³e miasto.}
{242} {} {I zachowujesz to dla najwa¿niejszych klientów? Co za ¿a³osny widok.}

{243} {} {Koœció³ p³onie, a sekta nied³ugo przestanie istnieæ. Czas zapomnieæ o Twojej umowie.}
{244} {} {Niedawno zosta³em inicjowany w katedrze.}
{1244} {} {Niedawno zosta³am inicjowana w katedrze.}
{245} {} {Czy nie jestem godny zaufania po tylu zwyciêstwach na ringu?}
{246} {} {Jestem jednym z Rangersów Arizony. I potrzebujê naprawdê niezawodnej spluwy.}
{247} {} {Don Diego poradzi³ mi, abym sobie kupi³ tu broñ. Nie zawiedŸ go.}
{248} {} {Masz bardzo zró¿nicowanych klientów, prawda? [Has³o State Rebel]}
{249} {} {Bêdziesz zadowolony z tej umowy.}
{250} {} {Brzmi nieprzekonuj¹co.}
{251} {} {Ok, a co z reszt¹ broni?}
{252} {} {W takim razie wychodzê st¹d.}
{253} {} {Mam kontakty w ca³ej Arizonie. Taka umowa bêdzie korzystna dla nas obojga.}
{254} {} {Mogê rêczyæ za swoj¹ reputacjê.}
{255} {} {Nie bêdziesz mia³ ze mn¹ problemu. Mogê rêczyæ za swoj¹ reputacjê.}
{256} {} {Jeœli nie bêdziesz ze mn¹ wspó³pracowaæ, zabijê ciê.}
{257} {} {Czy mam zawo³aæ moich potê¿nych przyjació³ z gangu?}
{258} {} {Rozumiem. Zobaczmy, co masz dla zwyk³ych obywateli.}
{259} {} {Zaufaj mi. „Nie ma ludzi bardziej wiernych cesarzowi ni¿ garstka ch³opów”.}

{260} {} {Coœ jeszcze?}
{261} {} {Tak, chcê ciê o coœ zapytaæ.}
{262} {} {To wszystko, czego potrzebujê. Czeœæ.}

# Rabaty i kary
{280} {} {(rozpoznaj¹c twoj¹ osobê sprzedawca nagle o¿ywia siê) Och, to ty. Mi³o ciê widzieæ w moim sklepie.}
{281} {} {Brzmi jak okazja.}
{282} {} {Zobaczmy... Drodzy ludzie, robiê ma³y rabat. Przecie¿ trzeba wspieraæ rozwój miasta, a nawet prowadziæ biznes.}
{283} {} {Rabat? Swietnie, przyda siê.}
{284} {} {(Po rozpoznaniu twojej osoby sprzedawca ostro¿nie zmienia swoj¹ pozycjê, jakby spodziewa³ siê podstêpu) Hej. Potrzebujesz czegoœ?}
{285} {} {Myœlê o zakupie broni...}
{286} {} {Wybierz szybko co chcesz i wyjdŸ. To nie jest jaskinia bandytów. I pamiêtaj, os³om takim jak ty, nie sprzedam niczego po normalnej cenie.}
{287} {} {Cokolwiek powiesz, stary. Wci¹¿ potrzebujê broni, nawet po cenie z³ota.}
{288} {} {Ka¿dy klient powinien byæ ceniony. Wiesz, œwiat zmienia siê zbyt szybko.}

{290} {} {Hej, myœlisz, ¿e mo¿esz siê tu tak po prostu pokazaæ po zamachu bombowym w katedrze? Mieszkañcy miasta bêd¹ niezadowoleni, jeœli bêdê nadal handlowaæ broni¹ z wami sekciarzami...}
{291} {} {Dlatego potrzebujê broni, ¿eby siê broniæ.}
{292} {} {Hmm, w porz¹dku. Coœ ci sprzedam. Ale bez rabatów, jasne?}
{293} {} {Kapsle nie s¹ problemem. Po prostu poka¿ mi swoje towary.}
{294} {} {Nie potrzebujê twojej pob³a¿liwoœci, idioto.}
{295} {} {Wygl¹da na to, ¿e nie jestem tu mile widziany. Lepiej odejdê.}

#Trening
{300} {} {Czy mogê po prostu postrzelaæ z broni bez kupowania jej?}
{301} {} {Zap³aæ za amunicjê i wypo¿yczenie broni, a bêdziesz móg³ trenowaæ swoje umiejêtnoœci na strzelnicy ile tylko zechcesz.}
{302} {} {Oto 500 kapsli za trening strzelania z broni lekkiej.}
{303} {} {Oto 1000 kapsli za trening strzelania z ciê¿kiej broni.}
{304} {} {Oto 2000 kapsli, jeœli pozwolisz mi strzelaæ z twojej broni energetycznej.}
{305} {} {Oto 250 kapsli za trening w rzucaniu.}
{306} {} {Bêdzie mi ³atwiej po prostu kupiæ sobie broñ.}
{307} {} {To rozbój w bia³y dzieñ! Wychodzê st¹d.}
{308} {} {Dawaj kapsle, jeœli chcesz nauczyæ siê strzelaæ.}
{309} {} {Ok.}

# Amunicja do wyposa¿enia
{330} {} {Muszê prze³adowaæ amunicjê.}
{331} {} {Mogê prze³adowaæ naboje sygna³owe i œrutowe. I nie ma sensu majstrowaæ przy pistoletach i karabinach.}
{332} {} {[Wzmocnij wk³ad sygna³owy]}
{333} {} {[Wzmocnij zmodyfikowany wk³ad sygna³owy]}
{334} {} {[Zamien œrut na pocisk kalibru .12]}
{335} {} {Ka¿dy wk³ad za 1 kapsel. To jak?}
{336} {} {Ka¿dy wk³ad za 2 kapsle. To jak?}
{337} {} {Jeszcze nie. Chcia³em tylko poznaæ stawki.}
{338} {} {Za s³aby, prawda? Nie s¹ przeznaczone do atakowania ¿ywego celu. Ale mo¿na je wzmocniæ i dodaæ coœ zabójczego.}
{339} {} {Nie potrzebujê tego.}

{340} {} {Gotowe. Coœ jeszcze?}
{341} {} {Mam wiêcej amunicji do prze³adowania.}
{342} {} {Mogê byæ zainteresowany czymœ innym ni¿ amunicj¹.}
{343} {} {Nie, do widzenia.}
{344} {} {Czegoœ brakuje, prawda? Rozejrzyj siê, mam du¿o innych towarów.}
{345} {} {Jedna runda.}
{346} {} {Dwie rundy.}
{347} {} {Trzy rundy.}
{348} {} {Cztery rundy.}
{349} {} {Piêæ rund.}

# Ulepszenie broni
{350} {} {Czy naprawiasz tu broñ?}
{351} {} {Poka¿ mi swoje zabawki, zobaczê, co mogê z nimi zrobiæ.}
{352} {} {Wygl¹da na to, ¿e ju¿ nic nie mo¿na na to poradziæ.}
{353} {} {Prawdopodobnie nie tym razem.}
{354} {} {}
{355} {} {Masz lunetê do strzelby myœliwskiej?}
{356} {} {Mam tu lunetê snajpersk¹ 10x Unertl. Swietnie nadaje siê do strzelania z * du¿ego * dystansu.}
{357} {} {Ile to kosztuje?}
{358} {} { kapsli. Kapsle z góry.}
{359} {} {Potrzebujê tego. Oto kapsle i karabin.}
{360} {} {Czego brakuje?}
{361} {} {Tak, bêdziemy musieli to od³o¿yæ.}
{362} {} {(wygl¹da na zadowolonego ze swojej pracy i daje ci gotowy produkt) Coœ jeszcze?}
{363} {} {Tak, nie œpiesz siê z zamykaniem sklepu.}
{364} {} {Nie, nie potrzebujê niczego wiêcej.}
{365} {} {Potrzebujê wiêkszego magazynku na 0,22 PP.}
{366} {} {Tak, taki ma³y kaliber nie wystarczy. Ale masz szczêœcie, mam bêbenek tylko dla 0,22.}
{367} {} {Chcê ten bêbenek. Oto kapsle i broñ.}
{368} {} {Czy jest coœ, co mo¿esz zrobiæ, aby ulepszyæ ten poganiacz byd³a?}
{369} {} {Tak, chyba.}
{370} {} {Warto. Zrób to.}
{371} {} {Czy masz coœ dla mojego AK-112?}
{372} {} {Tak, mam tu magazynek na czterdzieœci nabojów zamiast zwyk³ych dwudziestu czterech. Zosta³ ostatni.}
{373} {} {ChodŸ tutaj.}
{374} {} {Dziesiêæ rund.}
{375} {} {Mam jakakolwiek amunicjê.}

#Quests
{400} {} {Czy to z twojej broni strzelano do mnichów przed kasynem?}
{401} {} {Kim jesteœ, ¿eby zadawaæ mi pytania?}
{402} {} {Przepraszam. Prowadzê dochodzenie w sprawie ataku, przysy³a mnie Aaron. Czy mogê wiêc zadaæ kilka pytañ?}
{403} {} {Wiem o ataku nie wiêcej ni¿ ty. I w¹tpiê, ¿eby strzelali z pistoletu zakupionego w moim sklepie.}
{404} {} {Dlaczego tak myœlisz?}
{405} {} {Ja tutaj zadajê pytania, a ty odpowiadasz. Chcesz mieæ problemy z Obserwatorami?}
{406} {} {By³em przes³uchiwany przez czterech przed tob¹. Powiedzia³em im ju¿ wszystko, co wiem. I nie wiem wiêcej ni¿ ty. I w¹tpiê, ¿eby strzelali z pistoletu zakupionego w moim sklepie.}
{407} {} {W¹tpiê. To jedyny sklep z broni¹, prawda?}
{408} {} {Chocia¿ mój sklep jest jedynym w mieœcie, broñ mo¿esz kupiæ wszêdzie. Najbardziej uzbrojonymi ludŸmi w mieœcie s¹ byæ mo¿e sami Wyznawcy Ognia. Kiedyœ wszystkie bronie zosta³y przez nich zebrane, aby dokonaæ rewolucji. Poza tym najlepsz¹ broñ, jak¹ mam kupuj¹ tylko oni, taka umowa.}
{409} {} {Wiêc kto móg³by zaatakowaæ mnichów?}
{410} {} {Czemu ty * mnie * o to pytasz? Co za gówniany detektyw. Radzê Ci porozmawiaæ z ludŸmi na rynku, oni widzieli wszystko na w³asne oczy.}
{411} {} {Ok, porozmawiam z nimi. Pamiêtaj jednak, ¿e nikt nie atakuje Obserwatorów bezkarnie.}
{412} {} {Dziêki, bardzo mi pomog³eœ. Wszystkiego najlepszego.}