{100} {} {Widzisz z³omiarza.}
{101} {} {Widzisz niskiego mê¿czyznê w œmiesznych ubraniach. Na g³owie ma niezdarnie za³o¿ony he³m z wieloma instrumentami.}

# Plywajace repliki
{110} {} {Smieci najlepszej jakoœci!}
{111} {} {ZnajdŸ czêœci do wszelkich przyborów.}
{112} {} {Staro¿ytne rzeczy by³y piêkne.}
{113} {} {Kup pa³eczki, przydaj siê.}
{114} {} {Jeœli toster nie dzia³a, przynieœ go do mnie.}
{115} {} {Ca³e ¿arówki s¹ najtrudniejsze do znalezienia.}
{116} {} {Zardzewia³y, ale dzia³a.}
{117} {} {Mam nawet instrukcje do Pana R¹czki.}
{118} {} {Kup u mnie, ¿ebyœ nie musia³ grzebaæ w ruinach.}
{119} {} {Jak tylko odwracasz wzrok, coœ znika z lady.}

# Pierwszy dialog
{200} {} {No dalej, proszê pana! Rupiecie i œmieci - tego potrzebujesz. A wszystko to znajdziesz w moim sklepie.}
{1200} {} {No dalej, senorita! Rupiecie i œmieci - tego potrzebujesz. A wszystko to znajdziesz w moim sklepie.}
{201} {} {Wow, jest tu ca³y wóz œmieci.}
{202} {} {}
{203} {} {To nie s¹ zwyk³e œmieci, nie, nie! Wszystko, czego potrzebujesz, jest tutaj. Przyjrzyj siê bli¿ej. Mo¿e potrzebujesz tych zardzewia³ych ³y¿ek? A mo¿e wolisz jeœæ brudnymi rêkoma? W takim razie na pewno zainteresuje Ciê ten toster. Jego przycisk jest lekko zablokowany, ale na pewno dzia³a. A mo¿e potrzebujesz...}
{204} {} {Hej, zwolnij, stary. Pozwól, ¿e sam sprawdzê co masz.}
{205} {} {Zamknij siê, g³upi kretoszczurze. Robisz za du¿o ha³asu.}
{206} {} {A tak przy okazji. Chcê ciê ostrzec, ¿e podnios³em ceny po tym ca³ym szumie w katedrze. Ca³y rynek podniós³ ceny.}
{207} {} {Dlaczego?}
{208} {} {Kapsle by³y pomys³em Aarona. Jego koœció³ utrzymywa³ ich kurs. A teraz koœcio³a ju¿ nie ma, a kapsle trac¹ na wartoœci. Byæ mo¿e bêdziemy musieli ca³kowicie je porzuciæ.}
{209} {} {Rozumiem. Czas wiêc kupiæ wszystkie niezbêdne rzeczy.}

{210} {} {I co? Wybra³eœ ju¿ coœ?}
{1210} {} {I co? Wybra³aœ ju¿ coœ?}
{211} {} {Nie, innym razem.}
{212} {} {Czy mogê przyjrzeæ siê bli¿ej?}

#Pytania
{220} {} {Sk¹d masz te rzeczy?}
{221} {} {Zwykle od padlino¿erców, czasem karawan. Ale nie pytam, sk¹d je bior¹.}
{222} {} {Oczywiœcie nie wszystkie Twoje towary s¹ po uczciwej cenie.}
{223} {} {Ok, to pytanie by³o zbêdne.}

{224} {} {Kogo obchodz¹ te œmieci, skoro ruiny s¹ nimy przepe³nione?}
{225} {} {Chcesz poszperaæ w ruinach i poszukaæ sobie? Zapraszam! Tylko nie zapomnij o promieniowaniu, zwierzêtach, bandytach, osuwiskach i wielu innych problemach, które mog¹ zostawiæ Ci po sobie œlad. A ja nie tylko sprzedajê, ale te¿ naprawiam wszystkie te rzeczy, ¿eby choæ trochê pos³u¿y³y nowym w³aœcicielom.}
{226} {} {Nie mów mi nic wiêcej na ten temat.}
{227} {} {Myœlê, ¿e powinienem przyjrzeæ siê bli¿ej Twojemu asortymentowi.}

{228} {} {Jesteœ szalony. Te rzeczy by³y ostatnio sprawne 90 lat temu.}
{229} {} {Masz lepsze Ÿród³a? Ostatnio czêsto przybywaj¹ do nas karawany z po³udnia. Przynosz¹ naprawdê nowe rzeczy.}
{230} {} {W takim razie przestañ marnowaæ mój czas na bezczynne rozmowy.}
{231} {} {Dziêki, bêdê pamietaæ.}

# Poszukiwanie schronienia 27
{240} {} {Czy natrafi³eœ na przedmioty z Krypt?}
{241} {} {Krypt? O czym ty mówisz... Ach, rozumiem! Krypty Vault-Tec s¹ legendarne. Mówi siê, ¿e niektórzy z naszych przodków mieszkali tam po Wielkiej Wojnie. Ale minê³o tyle czasu, ¿e ju¿ prawie nikt nie zna lokalizacji tych skarbców.}
{242} {} {Kto mo¿e coœ wiedzieæ?}
{243} {} {Musisz iœæ do Wyznawców Ognia. W ich bibliotece jest tyle wiedzy, ¿e sami nie wiedz¹ ju¿, co z ni¹ zrobiæ. Mo¿e s¹ tam wspó³rzêdne tych schronów. Ale nie bêd¹ chcieli udostêpniaæ niczego bez dobrego powodu.}
{244} {} {A co z padlino¿ercami?}
{245} {} {Heh, myœlisz, ¿e normalny padlino¿erca ujawni³by komuœ lokalizacjê Krypty? W koñcu, wed³ug legendy, jest tam cholernie du¿o relikwii! Ale jeœli masz rozgadany jêzyk, odwiedŸ Boba w slumsach. Jest jednym z najstarszych padlino¿erców w Phoenix.}
{246} {} {Rozumiem.}

#Konsultacje na tematy
{250} {} {Potrzebujê porady na temat starych rzeczy.}
{251} {} {Po to ¿yjê - dla rzeczy Starego Swiata. Ale moja wiedza te¿ jest coœ warta. Wystarczy mi kilka kapsli.}
{252} {} {[}
{253} {} {]}
{254} {} {Nie powinieneœ. Mo¿e innym razem.}
{255} {} {Spójrz teraz na inny przedmiot.}
{256} {} {Przestañ mówiæ o starych rzeczach. Czas zrobiæ coœ bardziej odpowiedniego.}
{257} {} {Happy.}
{258} {} {Opowiedz mi o swoich towarach.}
{259} {} {Oczywiœcie, ¿e zap³acê.}

{260} {} {Czym dok³adnie siê interesujesz?}
{261} {} {[Graj¹ce pude³eczko]}
{262} {} {Co zaskakuj¹ce, mechanizm nadal dzia³a. Dzieci na pewno to pokochaj¹.}
{263} {} {[Zegarek atomowy]}
{264} {} {Wow, rzadko zdarza siê zobaczyæ sprawny zegarek kieszonkowy. A ta marka zawsze wyró¿nia³a siê jakosci¹. Ponadto jego bateria atomowa wystarcza na dziesiêciolecia. Gdyby tu byli Blacharze, wyrwaliby ci tê rzecz w³asnymi rêkoma.}
{265} {} {[Kula œnie¿na]}
{266} {} {Snieg! Nigdy nie widzia³em prawdziwego œniegu, z wyj¹tkiem kilku górskich szczytów w oddali. Ka¿dy bogacz po³asi siê na coœ takiego. Wiesz, mogê znaleŸæ zastosowanie dla tego bibelotu.}
{267} {} {[Medal of Honor]}
{268} {} {Operacja Anchorage... Czyta³em o tej masakrze gdzieœ w starych gazetach. Wygl¹da na to, ¿e Stany Zjednoczone by³y wówczas dumne ze swojego zwyciêstwa. Ale nie wiem, kto mo¿e byæ teraz zainteresowany takim znaleziskiem. Znasz jakichœ patriotów „tego kraju”? Ja nie.}
{269} {} {[Gwiazda Rangersa]}
{270} {} {Wygl¹da bardzo staro... Arizona Ranger? S³ysza³em, ¿e baza Rangersów jest na zachodzie. Ale nie wiem, gdzie dok³adnie.}
{271} {} {[Swiêta Ksiêga]}
{272} {} {Myœlê, ¿e to jakaœ ksi¹¿ka religijna. Z pewnoœci¹ bêd¹ tym zainteresowani sami Wyznawcy Ognia.}
{273} {} {[Zdjêcie]}
{274} {} {Zdjêcie wielkiego wybuchu? Wiêc tak to by³o... Straszne. Nie pokazuj tego zwyk³ym œmiertelnikom. Jeœli chcesz porozmawiaæ o Wielkiej Wojnie, lepiej znajdŸ jakiegoœ ³ysego konesera historii staro¿ytnej.}
{275} {} {[Koronowany z¹b]}
{276} {} {To tylko koronowany z¹b. Pozwól, ¿e obejrzê go pod lup¹... Nic... Nie, coœ tu jest. Potrzebujê mikroskopu... Chwila... Wow. To nie tylko korona, to rodzaj chipa. Albo klucz magnetyczny. A mo¿e urz¹dzenie magazynuj¹ce? To dla mnie za trudne. Tylko Blacharze rozumiej¹ takie zaawansowane technologie.}
{277} {} {[Flaga Arizony]}
{278} {} {Jedna z flag Starego Swiata. Wiêkszoœæ z tych flag zgni³a, ale ta jest zaskakuj¹co dobrze zachowana. Powinieneœ w odpowiednim czasie przejœæ siê do kolonistów na pó³nocy. W naszym mieœcie pozosta³o niewielu konserwatystów.}
{279} {} {[Dysk z gr¹]}
{280} {} {Wygl¹da jak zwyk³y holodysk. Ale wygl¹da na to, ¿e nie zawiera informacji, ale jakiœ program. Spróbuj pod³¹czyæ go do dzia³aj¹cego komputera, tylko nie wiem którego. Twój Pip-Boy mo¿e nie byæ tutaj wystarczaj¹co potê¿ny.}
{281} {} {[Mój osobisty Pip-Boy]}
{282} {} {Hmm, pierwszy raz widzê taki kompaktowy komputer... Czekaj, powinna byæ sekcja ze specyfikacj¹... Ok, Pip-Boy, model 2000, numer seryjny... Wow, jest tu droga prosto do Krypty 27! To jedna z tych legendarnych kryjówek Vault-Tec. O ile wci¹¿ istnieje.}
{283} {} {[Ksi¹¿ka przetrwania]}
{284} {} {Rzadkie znalezisko. Cenne Ÿród³o przedwojennej m¹droœci - tak mówi¹ o nich Wyznawcy Ognia. Zasadniczo kupuj¹ je. W koñcu w Phoenix niewielu potrafi czytaæ. Wiedza zawarta w tych ksi¹¿kach tak naprawdê nie pomaga zwyk³ym ludziom.}
{285} {} {[Puszka kawy]}
{286} {} {Masz szczêœcie. W koñcu to ziarna kawy. By³y u¿ywane do robienia popularnego napoju w Starym Swiecie. Ale teraz kawa sta³a siê tak rzadka, ¿e podaje siê j¹ tylko zamo¿nym klientom w kasynie po drugiej stronie ulicy.}

{289} {} {Kupiec obni¿y³ ceny o 5%.}
{290} {} {Prawdopodobnie bêdziesz tym zainteresowany. Spójrz, jeœli tym potrz¹œniesz, w œrodku zacznie padaæ œnieg...}
{291} {} {Snieg! Nigdy nie widzia³em prawdziwego œniegu, z wyj¹tkiem kilku górskich szczytów w oddali. Ka¿dy bogacz po³asi siê na coœ takiego... Hej, s³uchaj, sprzedasz mi t¹ b³yskotkê? Na pewno nie bêdziesz jej potrzebowaæ.}
{292} {} {Oszala³eœ? Chcia³em tylko wiedzieæ, co to by³o. Na tym siê rozejdziemy, czeœæ.}
{293} {} {Niech pomyœlê. Na razie zróbmy inne rzeczy...}
{294} {} {WeŸ to za darmo. Z przyjemnoœci¹ pozbêdê siê dodatkowych œmieci z mojego plecaka.}
{1294} {} {WeŸ to za darmo. Z przyjemnoœci¹ pozbêdê siê dodatkowych œmieci z mojego plecaka.}
{295} {} {Powa¿nie? Chcesz mi to po prostu daæ? Dziêkujê Ci. Jeœli potrzebujesz starych rzeczy, od razu do mnie przyjdŸ. Sprzedam ci wszystko co najlepsze i po najlepszych cenach.}
{296} {} {Warto o tym pamietaæ. Do zobaczenia.}
{297} {} {Wiesz, zajê³o mi to du¿o pracy, aby to zdobyæ. Oddam ten przedmiot za 350 kapsli. I ani kapsla mniej!}
{298} {} {Tak drogo? Uff... Trudno bêdzie znaleŸæ kupca, ale mo¿e mi siê op³aciæ. Ok, oto 350 kapsli. A teraz oddaj mi tê œniezn¹ kulê. (bierze kulê i przygl¹da siê jej z fascynacj¹ w oczach) Oooh...}
{299} {} {Hej, uwa¿aj... Och, dobrze. Czeœæ.}

# Atak na obserwujacych
{300} {} {Czy widzia³eœ atak na mnichów poza kasynem?}
{301} {} {Tak. Kilku bandytów zaatakowa³o mnichów. Zdesperowani ludzie. Ale co ci do tego?}
{302} {} {Aaron poprosi³ mnie o zbadanie tej sprawy.}
{303} {} {Aaron, mówisz? Chyba œmierci szukasz. Przychodzisz na targ, pytasz ludzi, k³amiesz o naszym wielkim mistrzu. Ale ju¿ powiedzia³em Wyznawcom wszystko co wiem i to kilka razy. Wynoœ siê st¹d, nic ci nie powiem.}
{304} {} {Przepraszam, ¿e przeszkadzam.}
{305} {} {Nie obchodzi mnie, komu zeznawa³eœ ani ile razy. TERAZ powiesz mi.}
{306} {} {Ok, ok... wiêc ty...}
{307} {} {Jak by³o?}
{308} {} {Spokojnie, mo¿esz mi zaufaæ.}
{309} {} {Nie jesteœ dla mnie zbyt mi³y, a niby jesteœ tak¹ szanowan¹ osob¹ w mieœcie.}
{310} {} {Nie pochlebiaj sobie, w³óczêgo.}
{311} {} {Któregoœ dnia zap³acisz za swoje s³owa.}
{312} {} {Przepraszam. Ani s³owa wiêcej na ten temat.}
{313} {} {ALBO opowiadasz tê historiê, ALBO z³amiê ci rêkê.}
{314} {} {Ogólnie rzecz bior¹c, mnisi szli spokojnie ulic¹. Nagle z kilku bocznych ulic wylecieli ludzie w kominiarkach. By³o ich oko³o piêciu. Strzelali g³ównie z pistoletów maszynowych. Zabili mnichów i natychmiast zniknêli. Ci bandyci dobrze zaplanowali swój atak.}
{315} {} {Rozumiem. Ale jeœli coœ ukrywasz, bêdzie ciê to drogo kosztowaæ.}
{316} {} {Dziêki, bardzo mi pomog³eœ.}
{317} {} {Sytuacja trochê siê wyjaœni³a.}
{318} {} {Sytuacja jest dla mnie jasna. Czas porozmawiaæ o tym z Aaronem.}