{100} {} {Widzisz sprzedawcê ubrañ.}
{101} {} {Widzisz kobietê z irokezem w skórzanej kurtce. Du¿o wie o nowoczesnej modzie.}

# Plywajace repliki
{110} {} {Wyrzuæ swoje szmaty, mam tu normalne ubranie.}
{111} {} {Zdecydowanie musisz zmieniæ swój styl.}
{112} {} {Mogê zaszyæ podarte kieszenie.}
{113} {} {Ta kurtka pêka w szwach.}
{114} {} {Potrzebujesz butów?}
{115} {} {Czyste œciereczki!}
{116} {} {Te ciuszki ukryj¹ wiele twoich wad.}
{117} {} {Ubrania prosto z przedwojennych magazynów.}
{118} {} {Filcowe kapelusze i garnitury nie s¹ ju¿ modne.}
{119} {} {Czciciele ognia du¿o wiedz¹ o odzie¿y.}

{200} {} {Czeœæ. Mam ró¿ne ubrania codzienne i ubrania robocze. Popatrz, nie wstydŸ siê.}
{201} {} {Wow. To lepsze ni¿ p³ótno, które nosi ca³a moja wioska.}
{202} {} {Bo¿e, te ubrania maj¹ prawdopodobnie sto lat. Nic dziwnego, ¿e miejscowi wygl¹daj¹ tak onieœmielaj¹co.}

{210} {} {I jak, spodoba³o ci siê coœ?}
{211} {} {Jeszcze nie.}
{212} {} {Spróbujmy tego...}

#Pytania
{220} {} {Sk¹d bierzesz te wszystkie ubrania?}
{221} {} {Po³owa produktów jest wykonana rêcznie. A drug¹ po³owê przynosz¹ padlino¿ercy. Czasami kilka razy dziennie znajdowali ocala³e magazyny z przedwojennymi ubraniami, ale obecnie jest o to trudniej.}
{222} {} {Rozumiem.}
{223} {} {Sk¹d Wyznawcy Ognia bior¹ swoje szaty?}
{224} {} {NajwyraŸniej sami je robi¹. I nie œpiesz¹ siê z udostêpnieniem tej technologii zwyk³ym œmiertelnikom.}
{225} {} {Przed wojn¹ uwa¿ano to za dobre ubranie.}
{226} {} {NajwyraŸniej tak. W koñcu nikt nie spodziewa³ siê, ¿e przejdzie siê w nich przez ruiny Phoenix. Teraz ludzie potrzebuj¹ innych ubrañ - bardziej praktycznych lub czegoœ takiego.}
{227} {} {Aha.}
{228} {} {Nie chcê nosiæ tych starych rzeczy.}
{229} {} {Hmm. Wydaje mi siê, ¿e przodkowie uwa¿ali te kostiumy za coœ przyzwoitego. Ech, dawne czasy... Dobra, zapomnij.}

#Okulary
{230} {} {Czy to wszystkie Twoje towary?}
{231} {} {Mogê zrobiæ coœ na zamówienie.}
{232} {} {S³uchaj, potrzebujê czegoœ specjalnego, ¿eby zaimponowaæ ludziom.}
{233} {} {Pomyœlê o tym.}
{234} {} {Powa¿nie? W dzisiejszych czasach ludzie nie maj¹ gustu w ubraniach. Ale masz szczêœcie. Mam okulary przeciws³oneczne w doskona³ym stanie. S¹ teraz rzadko spotykane.}
{235} {} {Na pewno ciê to nie skrzywdzi. Spróbuj zakryæ oczy tymi ciemnymi okularami. Przynajmniej na odleg³oœæ nie powinieneœ wystraszyæ ludzi.}
{236} {} {Tak, to na pewno ciê nie skrzywdzi. Mam œwietne stylowe okulary. Dobrze jest ukryæ pod nimi oczy, aby nikt nie domyœli³ siê, ¿e czujesz siê niepewnie.}
{237} {} {Od³ó¿ to na razie na bok, pomyœlê o tym.}
{238} {} {Zobaczmy wiêc, co mogê zaoferowaæ w zamian...}
{239} {} {Poka¿ mi, co masz.}

#Metalowa zbroja
{240} {} {Co powiesz na rezerwacje metalowej zbroi?}
{241} {} {To jest trochê poza moim profilem. Zwykli mieszczanie nie potrzebuj¹ zbroi i niewielu mo¿e sobie na to pozwoliæ. Jeœli ktoœ tego potrzebuje, przyjmujê zamówienie z przedp³at¹.}
{242} {} {Zap³acê 50 kapsli.}
{243} {} {Daj spokój, prawdopodobnie masz coœ w swojej tajnej szufladzie dla specjalnego klienta.}
{244} {} {Hej, po co ci zbroja? Lepiej weŸ kurtkê, przecie¿ nie idziesz na wojnê.}
{245} {} {Mo¿e tak. Niewa¿ne.}
{246} {} {Ok, chodŸmy.}
{247} {} {Ok. Ale uwaga - nie ma zwrotów. I nie dajê gwarancji.}
{248} {} {Twoje zamówienie jest na sprzeda¿. Decyzja nale¿y do mnie.}
{249} {} {Dziêki za ostrze¿enie.}
{250} {} {Czy wiesz w ogóle, jak wygl¹da ta kwota?}
{251} {} {Czekaj, na pewno tu by³y!}

#Mantle of the Followers
{260} {} {Potrzebujê szaty Kap³ana Ognia.}
{261} {} {(rozgl¹da siê ostro¿nie) S³uchaj, nie bêdê pytaæ, dlaczego tego potrzebujesz, ale nie potrzebujê problemów.}
{262} {} {Zap³acê, ilekolwiek powiesz. I nikt nie bêdzie wiedzia³ o naszej tajnej umowie.}
{263} {} {Nie martw siê, przys³ali mnie do ciebie nasi wspólni przyjaciele.}
{264} {} {Zwariowa³eœ? Zabij¹ mnie za to!}
{265} {} {W³aœnie straci³aœ górê kapsli. Gratulacje.}
{266} {} {Przepraszam, ¿e pytam.}
{267} {} {Och, to bardzo wiele zmienia. Ale mam nadziejê, ¿e wiesz, co robisz.}
{268} {} {Nie ma problemu. Po prostu pójdê dalej.}
{269} {} {Ok, oto co mam. Ale nie proœ o wiêcej - to zbyt niebezpieczne.}
{270} {} {Ok.}

#Kombinezon
{280} {} {Hej, czy to ten sam kombinezon jak te z tych legendarnych Krypt? Sk¹d to masz?}
{281} {} {Znalaz³em.}
{1281} {} {Znalaz³am.}
{282} {} {Mam swoje Ÿród³a.}
{283} {} {To szczêœcie. I na pewno nie wiesz, gdzie dostaæ wiêcej, prawda? Po prostu wiedz, ¿e te kombinezony to prawdziwy dar niebios. Jeœli znajdziesz wiêcej, przynieœ je do mnie, kupiê je za prawdziwe kapsle po wy¿szej cenie.}
{284} {} {Ok. Ale zanim to nast¹pi, chcê przyjrzeæ siê Twoim produktom.}
{285} {} {No to idê teraz poszukaæ ich wiêcej.}
{286} {} {Oto kombinezon z Krypty, który chcia³aœ.}
{287} {} {Super! W koñcu! Zamierzam zmieniæ tê œmierdz¹c¹ kurtkê. Hej, nie zapomnij o kapslach. I dziêkujê.}
{288} {} {Proszê.}
{289} {} {Kapsle s¹ najwa¿niejsze. Zachowaj wdziêcznoœæ dla siebie.}
{290} {} {Jaka kryje siê historia za tymi kombinezonami?}
{291} {} {Có¿, to stara legenda. Mówi siê, ¿e przed Wielk¹ Wojn¹ wokó³ Phoenix zbudowano kilka schronów. Niektórzy ludzie prze¿yli tam wojnê, a potem wyszli, by o¿ywiæ miasto. I nosili w³aœnie takie kombinezony. To prawda, plotki s¹ sprzeczne.}
{292} {} {[Dalej.]}
{293} {} {Poza tym moi rodzice mieli taki kombinezon. To dla mnie szczególne wspomnienie. Niestety, ten kombinezon ju¿ dawno siê rozpad³.}
{294} {} {Ciekawa historia.}
{295} {} {Mam dla ciebie kombinezon z Krypty.}
{296} {} {Wiêcej? Wow, wiesz, jak czyniæ dobre rzeczy. Oto kapsle.}
{297} {} {Nie ma za co.}
{298} {} {Swietnie. Ale nadal potrzebujê czegoœ innego.}

#Atak na mnichów
{300} {} {Co widzia³aœ podczas ataku na mnichów?}
{301} {} {Hej! Nie mieszaj mnie do tej sprawy. Ja tylko sprzedajê ubrania. I nic nie widzia³am.}
{302} {} {W takim razie przepraszam, nie mam wiêcej pytañ.}
{303} {} {Gadaj, suko, albo rozwalê twój cholerny sklep.}
{304} {} {Czego ode mnie chcesz? Jacyœ ludzie w maskach wybiegli z zau³ków i zaczeli strzelaæ do mnichów. Po czym natychmiast zniknêli. Nikomu innemu nie przeszkadzali. To wszystko, co wiem!}
{305} {} {Przepraszam za sklep - oczywiœcie nie zamierzam go zepsuæ.}
{306} {} {Wierzê ci. Tym razem.}
{307} {} {Spokojnie, mo¿esz mi zaufaæ.}
{308} {} {Nie mam co do tego w¹tpliwoœci. Ale ja naprawdê nie wiem nic o ataku. Zostaw mnie w spokoju.}
{309} {} {Obiecujê, ¿e bêdziesz bezpieczna.}
{310} {} {Jasne. Tutaj albo podpadasz zakonowi, albo wrogom, którzy ich przeœladuj¹.}
{311} {} {To jest coœ interesuj¹cego. Powiedz mi, jak by³o.}
{312} {} {No có¿, jacyœ zamaskowani ludzie wybiegli z alejek i zaczeli strzelaæ do mnichów. A potem szybko zniknêli. Nikomu innemu nie przeszkadzali. To wszystko, co wiem!}
{313} {} {Hmm, ciekawa historia. Dziêkujê Ci.}
{314} {} {Wierzê ci. Tym razem.}
{315} {} {Sytuacja trochê siê wyjaœni³a.}
{316} {} {Sytuacja jest dla mnie jasna. Czas porozmawiaæ o tym z Aaronem.}