{100} {} {Widzisz klienta.}
{101} {} {Widzisz klienta. Przekroczy³ ju¿ swoj¹ dzienn¹ dietê i aktywnie mówi o czymœ innym.}

# Przed uzyciem alkoholu
{200} {} {(Widzisz uœmiechniêtego mê¿czyznê z eleganckim w¹sem. Jego opalona skóra i kowbojski kapelusz wskazuj¹ na ¿¹dze wêdrówki, a jego trzeŸwy wygl¹d wskazuje na ostry brak alkoholu we krwi.)}
{201} {} {[Usi¹dŸ przy ladzie]}
{202} {} {(odwraca siê z chytrym uœmiechem) Hej przyjacielu, mo¿esz postawiæ mi drinka? Ten jednorêki bandyta zabra³ mi ca³¹ gotówkê.}
{1202} {} {(odwraca siê z chytrym uœmiechem) Hej przyjació³ko, czy mog³abyœ postawiæ mi drinka? Ten jednorêki bandyta zabra³ mi ca³¹ gotówkê.}
{203} {} {Daæ komuœ drinka za darmo? Jeszcze nie zwariowa³em.}
{1203} {} {Prosisz damê o drinka? Nie wstyd Ci?}
{204} {} {Cokolwiek powiesz, kolego. Ale jeœli siadasz z kimœ do baru, stawia siê mu drinka.}
{1204} {} {Dobrze. Wygra³aœ. Przepraszam za starego podró¿nika i za jego nietakt. Ale ten cholerny automat naprawdê zabra³ moj¹ ostatni¹ gotówkê. Inaczej to ja postawi³bym pani drinka, piêkna damo.}
{205} {} {Nastêpnym razem, kowboju.}
{1205} {} {Wszystko jasne. Zegnaj.}
{206} {} {Oczywiœcie kolego, kupiê ci zaraz coœ z baru...}
{207} {} {Przepraszam, nie mogê. Nastêpnym razem.}
{208} {} {Rozumiem. Bywaj.}
{209} {} {[Wróæ do waznej firmy]}
{210} {} {Ok, zamówiê Ci drinka...}
{211} {} {Ktoœ tu musi mieæ nerwy ze stali. Swoj¹ drog¹, moja proœba jest nadal aktualna.}
{1211} {} {Ktoœ tu musi mieæ nerwy ze stali. Swoj¹ drog¹, moja proœba jest nadal aktualna.}

# Po wypiciu alkoholu
{220} {} {(bierze ³yk) Och, czujê jakby anio³y tañczy³y na czubku jêzyka. Taki burbon nawet szkoda po³ykaæ. }
# Cytat z filmu „Prison Rock” 1957: „Jakby anio³y tañczy³y na czubku ich jêzyka. Taki burbon nawet szkoda polykac”.
{221} {} {Mówisz, jakbyœ mia³ du¿e doœwiadczenie.}
{222} {} {Och, te stopy przesz³y niejedn¹ milê wokó³ Phoenix i wzd³u¿ tras karawan. Chcesz o tym pos³uchaæ?}
{223} {} {W³aœciwie nie, ale kontynuuj.}
{224} {} {Zdecydowanie. Opowiedz mi o swoich podró¿ach.}
{225} {} {Dziêki za drinka.}
{226} {} {Baw siê i zaczerpnij œwie¿ego powietrza.}
{227} {} {Mi³ej zabawy, kolego.}
{228} {} {Tylko po to, ¿eby ciê zostawiæ.}
{229} {} {Dziêki. Rzadko mo¿na spotkaæ osoby, które chc¹ podzieliæ siê czymœ z nieznajomym.}

#Fabula
{230} {} {Pracujê dla karawan jako niezale¿ny najemnik. Czasami podró¿ujê samotnie w poszukiwaniu bogactwa. Wszyscy znaj¹ mnie jako œwietnego strzelca i ocala³ego z pustyni. Dlatego ofert nie ma koñca. Ale podró¿e staj¹ siê coraz bardziej niebezpieczne.}
{231} {} {Co masz na myœli?}
{232} {} {Mo¿na by pomyœleæ, ¿e kiedyœ by³y bezpieczne.}
{233} {} {Burze piaskowe s¹ coraz intensywniejsze. Mówi¹, ¿e kiedyœ by³o znacznie gorzej. Ale nawet teraz, w z³ym sezonie, niszcz¹ ca³e osady, a jeœli zostaniesz z³apany przez tak¹ pustynn¹ burzê na otwartym terenie, szanse na prze¿ycie s¹ bliskie zeru. Ju¿ nie wspomnê o gigantycznych tornadach lub chmurach truj¹cego, œwiec¹cego py³u z zachodu. NajwyraŸniej natura nie chce oddaæ œwiata cz³owiekowi.}
{234} {} {Tak, nie mog³o byæ gorzej po drodze.}
{235} {} {Ha, taki doœwiadczony survivalista, a przera¿ony wiatrem i piaskiem.}

{236} {} {Burze piaskowe nie s¹ najgroŸniejszymi przeciwnikami po drodze. Mo¿esz je zobaczyæ z daleka i mo¿esz je obejœæ. Ale ludzie s¹ znacznie bardziej podstêpni. Na trasach karawan czêsto spotykaliœmy zw³oki pozostawione przez rabusiów. Nieraz zbieraj¹c z nich œmieci widzia³em czêœciowo zjedzone cia³a.}
{237} {} {Ja te¿ uciek³bym siê do kanibalizmu. Na bezludnej pustyni ka¿de jedzenie jest dobre, prawda?}
{1237} {} {Ja te¿ uciek³abym siê do kanibalizmu. Na bezludnej pustyni ka¿de jedzenie jest dobre, prawda?}
{238} {} {Powa¿nie? Ja bym tak nie móg³. Miêso ludzkie mo¿e byæ bardziej szkodliwe ni¿ suche porcje liœci i owadów. Ale na pewno nie potêpiê takiego aktu w warunkach g³odu.}
{239} {} {Dlaczego w ogóle o tym wspomnia³eœ?}
{240} {} {To straszne. Nawet w warunkach g³odu. Jakie zwierzêta s¹ do tego zdolne?}
{241} {} {Jest mnóstwo mot³ochu poza miastem. Najgorsi s¹ ci na trasie 10. Zachowuj¹ siê jak jacyæ w³adcy tras. Zap³aæ im myto albo umrzesz. Chocia¿ wielu nawet nie pyta, po prostu bior¹ wszystko si³¹.}
{242} {} {Dlaczego w ogóle o tym mówisz?}
{243} {} {Tylko mieszasz mi w g³owie. Nie wierzê, ¿e pustynia jest tak zat³oczona.}
{244} {} {Och, wierz mi, s¹ tam osiedla, chocia¿ kilka. Zwykle s¹ doœæ zamkniête i nie bez powodu. Ludzie trzymaj¹ siê ¿ycia nawet w najbardziej suchych regionach.}
{245} {} {Dlaczego w ogóle o tym mówisz?}

{250} {} {(wzdycha i bierze ³yk po krótkiej przerwie) Mia³em jeden przypadek...}
{251} {} {No dalej, powiedz mi, o czym myœlisz, kolego. Do tego s³u¿y bar.}
{1251} {} {No, powiedz mi, co myœli ten wielki survivalista. Do tego s³u¿y bar.}
{252} {} {Dobrze siê zaczê³o. Myœla³em, ¿e rozmowa dobiega koñca.}
{253} {} {...Poszliœmy handlowaæ w Gila Bend. Okaza³o siê, ¿e miejscowi ju¿ dawno opuœcili ten ja³owy region i do Phoenix musieliœmy wracaæ z niczym. W drodze powrotnej skoñczy³y siê nam zapasy. Niestety w okolicy nie by³o nic jadalnego - ¿adnej bestii, ¿adnej roœlinnoœci. A upa³ i zmieniaj¹cy siê piaszczysty krajobraz nieustannie sprowadza³y nas na manowce.}
{254} {} {Jak prze¿y³eœ?}
{255} {} {Spotkaliœmy na naszej drodze mê¿czyznê. NajwyraŸniej by³ uchodŸc¹ z Phoenix, szukaj¹cym nowego miejsca do ¿ycia. W przeciwieñstwie do nas nadal mia³ zapasy.}
{256} {} {Wiêc go okrad³eœ?}
{257} {} {Jeden ze stra¿ników straci³ g³owê z g³odu. Nawet nie zadaliœmy sobie trudu, ¿eby go powstrzymaæ, po prostu tam staliœmy. Wbi³ nó¿ w cia³o podró¿nika dwadzieœcia siedem razy, a¿ siê uspokoi³.}
{258} {} {Ale prze¿y³eœ. Nie mo¿na ciê winiæ za tê sytuacjê.}
{259} {} {Naprawdê tak myœlisz? Có¿, to znaczy, ¿e nie pomyli³em siê w wyborze rozmówcy. Poczu³em siê trochê lepiej. A jednak mog³em powstrzymaæ tego szaleñca. Poza tym brak rezerw to po czêœci moja wina. Ta historia bêdzie teraz przez dobr¹ chwilê drêczyæ moj¹ duszê.}
{260} {} {W naturze nie ma moralnoœci, ani etyki. W naturze ludzie prze¿ywaj¹ lub gin¹. Po prostu zapomnij o tej historii.}
{261} {} {Zartujesz? Tak, po takiej historii nie chcê ciê widzieæ. ZejdŸ mi z oczu, bandyto.}
{262} {} {Sk¹d wiesz, ile razy wbi³ nó¿?}
{263} {} {Liczy³em.}
{264} {} {Nie ma dla ciebie wymówki. Nic dziwnego, ¿e teraz szukasz komfortu w barze. Mam nadziejê, ¿e go nie znajdziesz.}
{265} {} {Ech... Masz racjê. Ale po to jest bar, w którym mo¿na rozmawiaæ o bolesnych rzeczach, prawda? Przynajmniej czujê siê trochê lepiej.}
{266} {} {No nic, idê. Zagram w ruletkê. Lece.}
{267} {} {Zdarza siê. Miejmy nadziejê, ¿e nasze œcie¿ki ju¿ nigdy siê nie skrzy¿uj¹.}

{268} {} {Po drodze natknêliœmy siê na stary motel. Nie wygl¹da³ na ca³kowicie opuszczony. Wrêcz przeciwnie, drzwi restauracji by³y otwarte i wywieszone reklamami ¿yciodajnej Nuka Coli.}
{269} {} {Ktoœ by³ w œrodku?}
{270} {} {W œrodku by³o jedzenie i woda. W rezultacie wszyscy straciliœmy g³owy. Woda by³a zatruta, a teren motelu usiany by³ œmiertelnymi pu³apkami. Tylko ja zdo³a³em wyjœæ stamt¹d ¿ywy.}
{271} {} {Kto móg³ to zrobiæ?}
{272} {} {Bandyci? Kanibale? Dusze zmar³ych podczas Wielkiej Wojny? Nie wiem. Ale ten upiorny motel by³ ju¿ wczeœniej wspominany w opowieœciach.}
{273} {} {Super. Kontrolowa³eœ swój umys³ nawet w krytycznej sytuacji.}
{274} {} {Naprawdê myœlisz, ¿e powinienem byæ z tego dumny? Có¿, to znaczy, ¿e nie pomyli³em siê w wyborze rozmówcy. Poczu³em siê trochê lepiej. Szkoda, ¿e nie mog³em porozmawiaæ z koleg¹ z karawany.}
{275} {} {Wow, jest du¿o do przemyœlenia. Rozchmurz siê, kolego.}
{276} {} {No có¿, chyba nie s¹dzisz, ¿e uwierzê ci na s³owo?}
{277} {} {Piêknie œpiewasz. W takiej sytuacji sam mog³eœ zastawiæ tê pu³apkê.}
{278} {} {Wiesz, nie jesteœ pierwszym, który to powiedzia³. Ludzie szepcz¹ za moimi plecami. Mówi¹, ¿e porzuci³em lub nawet zabi³em moich towarzyszy. Ale uwierz mi - trudniej jest przetrwaæ w samotnoœci na pustyni ni¿ w ha³aœliwym towarzystwie.}
{1278} {} {Wiesz, nie jesteœ pierwsz¹, która to powiedzia³a. Ludzie szepcz¹ za moimi plecami. Mówi¹, ¿e porzuci³em lub nawet zabi³em moich towarzyszy. Ale uwierz mi - trudniej jest przetrwaæ w samotnoœci na pustyni ni¿ w ha³aœliwym towarzystwie.}

{280} {} {Nie mogê uwierzyæ w t¹ historiê o motelu i o duchach. Gdzie on siê znajduje?}
{281} {} {Có¿, tak, te¿ nie chcê w to wierzyæ. Ale widzisz, to miejsce istnieje naprawdê, ale jest zagubione gdzieœ na pustyni. Nie uda³o mi siê okreœliæ jego dok³adnego po³o¿enia na mapie. Wiem tylko, ¿e znajduje siê na po³udniowy zachód od Phoenix.}
{282} {} {Po prostu chcê wiedzieæ z wyprzedzeniem o niebezpieczeñstwie. Bywaj.}
{283} {} {Czy poczujesz siê lepiej, jeœli poszukam tego miejsca?}
{284} {} {Umar³ych nie mo¿na zwróciæ, ale mo¿esz pomóc innym podró¿nikom. W ka¿dym razie b¹dŸ ostro¿ny. Nie ma potrzeby ¿eby i twoja dusza zosta³a w tym przeklêtym miejscu.}
{285} {} {Bywaj.}
{286} {} {Przypomnij mi, w którym kierunku by³ ten straszny motel?}
{287} {} {To miejsce jest zagubione gdzieœ na pustyni. Nie uda³o mi siê okreœliæ jego po³o¿enia na mapie. Wiem tylko, ¿e znajduje siê na po³udniowy zachód od Phoenix.}
{288} {} {Bywaj.}
{289} {} {Ten straszny motel, o którym mówi³eœ, okaza³ siê piek³em. Do diab³a, wci¹¿ mam gêsi¹ skórkê.}
{290} {} {Och! Czyli uda³o ci siê go znaleŸæ?}
{291} {} {No tak. Okaza³o siê, ¿e wszystkim tam rz¹dzi diabelska rodzina potworów-kanibali. Chytre skurwysyny. Ale teraz ich motel jest bezpiecznie zamkniêty.}
{292} {} {To wszystko... Od razu wyczu³em, ¿e ktoœ nas œledzi. Tak, wszyscy prze¿ywaj¹ najlepiej, jak potrafi¹. Ale to nie powinno mieæ miejsca nawet w naszych czasach. Cieszê siê, ¿e poradzi³eœ sobie z nimi i pomœci³eœ moich towarzyszy. Dziêkujê Ci. Proszê, napij siê na mój koszt.}
{293} {} {Bywaj.}
