{100} {} {Widzisz ochroniarza.}
{101} {} {Widzisz bramkarza w kasynie. Dba o porz¹dek.}
{102} {} {Widzisz bramkarza w kasynie. Wypatruje z³odziei.}
{103} {} {Widzisz bramkarza w kasynie. Patrzy na frontowe drzwi.}
{104} {} {Widzisz bramkarza w kasynie. Ma na oku kilku w¹tpliwych goœci.}
{105} {} {Widzisz bramkarza w kasynie. Rozgl¹da siê ze znudzeniem.}
{106} {} {Widzisz bramkarza kasyna z udawanym surowym spojrzeniem.}
{107} {} {Widzisz mê¿czyznê w garniturze i z broni¹. Wydaje siê byæ nazywany stra¿nikiem.}

{110} {} {Natychmiast schowaj broñ.}
{111} {} {Powtarzam, schowaj broñ.}
{112} {} {Zosta³eœ ostrze¿ony.}
{113} {} {Za tymi drzwiami s¹ pomieszczenia s³u¿bowe. Nie mo¿esz tam iœæ.}
{114} {} {Hej, zejdŸ ze sceny.}
{115} {} {Musisz to schowaæ. Otwarte noszenie broni w kasynie jest zabronione.}

# Próbuje mówiæ
{200} {} {Przepraszam, to nie dla mnie.}
{201} {} {Potrzebujesz administratora.}
{202} {} {Nie wolno mi komunikowaæ siê z klientami.}
{203} {} {Administratorowi nie podoba siê, kiedy przeszkadzamy klientom.}
{204} {} {Mi³ej zabawy, personel zajmie siê reszt¹.}
{205} {} {Jesteœ tutaj ca³kowicie bezpieczny.}
{206} {} {To uczciwe kasyno, nie ma siê czym martwiæ.}
{207} {} {Nie tolerujemy tutaj kradzie¿y.}
{208} {} {Mam nadziejê, ¿e dobrze siê bawisz.}
{209} {} {Czy próbowa³eœ ju¿ naszej tequili?}
{210} {} {Spróbuj Atomic Cocktail, pali do koœci.}
{211} {} {Bar jest po tej stronie.}
{212} {} {Bar ma du¿o œwietnych drinków.}
{213} {} {Nie lubimy przemocy, ale jak trzeba to trzeba.}
{214} {} {Jakiœ problem?}
{215} {} {}
{216} {} {}
{217} {} {}
{218} {} {}
{219} {} {}

{250} {} {Nie przeszkadzaj mi, bo Ÿle siê to skoñczy dla ciebie.}
{251} {} {Nie pogarszaj swojej sytuacji.}
{252} {} {Jeœli chcesz graæ, graj. Ale nie podchodŸ do stra¿ników.}
{253} {} {Jeœli zaczniesz sprawiaæ k³opoty, wylecisz na ulicê. Jasne?}
{254} {} {Lepiej odejdŸ, g³upi wieœniaku.}
{255} {} {Nie robiê tu za ozdobê.}
{256} {} {Szukasz problemów? To nie jest do tego najlepsze miejsce.}
{257} {} {Cz³owiek o twojej reputacji najlepiej zrobi³by uciekaj¹c z miasta.}
{258} {} {Nie ma ograniczeñ co do twojej bezczelnoœci.}
{259} {} {* ignoruje Ciê *}

{280} {} {Musisz zdj¹æ ten *garnitur*.}
{281} {} {Nie mo¿emy ciê w tym wpuœciæ... Uch, okej, wejdŸ.}
{282} {} {Nie sprawisz nam k³opotów, prawda?}
{283} {} {Nie mam pojêcia, jak bêdziesz w tym graæ.}
{284} {} {Nie mam nic przeciwko, ale nie mo¿esz tu chodziæ w tej zbroi.}
{285} {} {Czy mo¿esz zostawiæ swoj¹ zbrojê gdzieœ... gdzieœ indziej?}
{286} {} {Tak, oczywiœcie, uh, zawsze cieszymy siê, ¿e ciê widzimy, sir... lub madame...}
{287} {} {Proszê opuœciæ lokal. Zniszczysz nasze meble.}
{288} {} {Nie mogê pozwoliæ ci chodziæ w tej... rzeczy.}
{289} {} {Wygl¹dasz, hm, wyzywaj¹co w tej zbroi.}

{290} {} {Schowaj broñ.}
{291} {} {Radzê natychmiast schowaæ broñ.}
{292} {} {Nie tolerujemy broni palnej w kasynie.}
{293} {} {Jeœli swêdz¹ ciê palce na spuœcie, to wyjdŸ na zewn¹trz.}
{294} {} {Nie ma tu ¿adnego zagro¿enia, od³ó¿ broñ.}
{295} {} {Grozisz mi?}
{296} {} {Noszenie broni w kasynie jest zabronione.}
{297} {} {Hej, od³ó¿ broñ. Nie potrzebujemy tutaj problemów.}
{298} {} {Zabierz broñ, a nikt nie zostanie ranny.}
{299} {} {Mamy spokojne kasyno, nie wa¿ siê nikomu groziæ.}