{100}{}{Widzisz kasjerkê.}
{101}{}{Widzisz zaskakuj¹co pracowit¹ i sumienn¹ kasjerkê. Wygl¹da na to, ¿e zosta³a dobrze wyszkolona do tej pracy.}
{102}{}{P-przepraszam, ale musisz to zdj¹æ... A-albo zawo³am ochronê...}

{105}{}{Ochrona! Z³odziej!}
{106}{}{Ochrona! W³amywacz!}
{107}{}{Natychmiast opuœæ ten pokój.}
{108}{}{WyjdŸ natychmiast. To jest przestrzeñ dla personelu.}
{109}{}{}

#Pierwszy dialog
{200}{}{Witam pana. Pierwszy raz w naszym kasynie?}
{1200}{}{Witam pani¹. Pierwszy raz w naszym kasynie?}
{201}{}{Zgadza siê. Mam nadziejê, ¿e mo¿esz mi wyjaœniæ lokalne zasady.}
{202}{}{Kierownik wyjaœni ci zasady gry. Moim zadaniem jest wymiana ¿etonów do gry. W kasynie zastêpuj¹ ka¿d¹ walutê, ale zawsze mo¿esz je wymieniæ z powrotem tutaj przy kasie.}
{203}{}{Zrozumia³em.}
{204}{}{Niezupe³nie. Jesteœmy dobrymi przyjació³mi z Don Diego, pamiêtaj o tym.}
{205}{}{Och, przepraszam, nie ostrze¿ono mnie przed tob¹. Pamiêtaj jednak, ¿e w kasynie zasady s¹ takie same dla wszystkich. L¹cznie z przyjació³mi Don Diego.}
{206}{}{Zrozumia³em.}
{209}{}{Jako honorowy cz³onek powinienem byæ godny zaufania, prawda?}

#Powtarzany dialog
{210}{}{Jak mogê pomóc?}
{211}{}{Dziêki, to wszystko.}
{212}{}{Uch... tak, tak?}
{213}{}{Czy kasyno jest nadal otwarte?}
{214}{}{O tak. Wci¹¿ odbudowujemy wnêtrze po wybuchu w katedrze, ale mo¿na ju¿ korzystaæ ze wszystkich standardowych rozrywek... jeœli czujesz siê komfortowo w tym ba³aganie.}
{215}{}{Ba³aganie? Czy wiesz w jakim œwiecie ¿yjemy? Jestem przyzwyczajony do ba³aganu.}
{216}{}{Wiêc kasyno jest w ruinie? Wystarczy, wychodzê st¹d.}
{217}{}{Przepraszam, ale nie wolno mi ciê obs³ugiwaæ. Mogê tylko wymieniæ wszystkie twoje ¿etony jeœli jakieœ ci zosta³y. W sprawie roszczeñ prosimy o kontakt z administratorem.}
{218}{}{Obs³uga tutaj jest okropna.}
{219}{}{W takim razie znajdê inne kasyno. Do widzenia.}

#Ujawnienie towarów do zabezpieczenia
{220}{}{Czy mogê zastawiæ sprzêt lub czêœæ moich rzeczy?}
{221}{}{Obawiam siê, ¿e nie le¿y to w najlepszym interesie kasyna. Wolimy kapsle do butelek. Czasami jednak robimy takie wyj¹tki.}
{222}{}{Ok, niewa¿ne.}
{223}{}{Przyjaciele Don Diego te¿ mog¹ spodziewaæ siê takiego wyj¹tkowego traktowania?}
{224}{}{Oczywiœcie, zrobimy dla ciebie wyj¹tek. Ale mamy ograniczone kapsle do takich celów.}
{225}{}{Dziêkujê. Zapamiêtam, ¿e masz teraz tak¿e kapsle w swojej ofercie.}
{226}{}{Tak, ale przepraszam, nic mi o tobie nie wiadomo.}
{227}{}{Nie ma problemu.}
{228}{}{Jestem handlarzem, to siê mo¿e wam op³aciæ.}
{229}{}{Wierzê. Myœlê, ¿e zrobimy dla ciebie wyj¹tek. Ale mamy ograniczone kapsle do takich celów.}
{230}{}{Dziêkujê. PZapamiêtam, ¿e masz teraz tak¿e kapsle w swojej ofercie.}
{231}{}{Wierzê. Ale w przypadku kasyna preferowane s¹ kapsle. Mo¿esz wymieniæ swoje przedmioty na lokalnym rynku.}
{232}{}{Nie ma powodu do odmowy.}
{233}{}{Powiedz mi, czy moje imiê nic nie znaczy w tym miescie?}
{234}{}{Przepraszam, masz ca³kowit¹ racjê. Od teraz mo¿esz liczyæ na lepsze traktowanie.}
{235}{}{Dziêkujê. Zapamiêtam, ¿e masz teraz tak¿e kapsle w swojej ofercie.}
{236}{}{Przepraszam, ale sam znasz swoj¹ reputacjê w *tym* miescie.}
{237}{}{Suko, sugerujesz, ¿e gardz¹ tu mn¹?}
{238}{}{Przepraszam, ale nie mogê ci pomóc.}
{239}{}{W porz¹dku.}

#Odrzucenie gry
{240}{}{Wstyd mi to powiedzieæ, ale powiedziano mi, ¿ebym ciê wiêcej nie obs³ugiwa³a.}
{241}{}{Jak to? Nie mogê ju¿ graæ w kasynie?}
{242}{}{Chyba wszyscy oszaleliœcie. Co to do cholery znaczy?}
{243}{}{Przepraszam, takie mam polecenie! Wszelkie roszczenia nale¿y kierowaæ do administratora. Mogê tylko wymieniæ wszystkie twoje ¿etony do gry, ale nie ju¿ mogê wydawaæ nowych.}
{244}{}{W takim razie muszê porozmawiaæ z administratorem. Wszystkiego najlepszego.}
{245}{}{Oczywiœcie, to wszystko jest jakieœ ustawione. Pieprzone kasyno...}
{246}{}{Czekaj! Uh, przepraszam... pana...}
{1246}{}{Czekaj! Uh, przepraszam... pani¹...}
{247}{}{Tak? Coœ nie tak?}

#Wymieniac siê
{250}{}{Chcê wymieniæ kapsle na ¿etony w kasynie.}
{251}{}{Ile kapsli chcesz wymieniæ?}
{252}{}{10 kapsli.}
{253}{}{50 kapsli.}
{254}{}{100 kapsli.}
{255}{}{500 kapsli.}
{256}{}{1000 kapsli.}
{257}{}{Jednak nie chcê niczego wymieniaæ.}
{258}{}{Proszê. (otrzymano ¿etony z kasyna w zamian za kapsle)}
{259}{}{Dziêkujê.}
{260}{}{Nie masz wystarczaj¹cej liczby kapsli.}
{261}{}{Ok.}
{262}{}{Proszê. (otrzymano kapsle w zamian za ¿etony z kasyna)}
{263}{}{Dziêkujê.}
{264}{}{Nie masz wystarczaj¹co ¿etonów.}
{265}{}{Ok.}
{266}{}{Nie masz doœæ pieniêdzy.}
{267}{}{Wszystkie kapsle, które mam.}
{268}{}{Proszê. (otrzymano kapsle w zamian za przedwojenne pieni¹dze)}
{269}{}{Dziêki.}

{270}{}{Chcê wymieniæ ¿etony do gry na kapsle.}
{271}{}{Ile ¿etonów chcesz wymieniæ?}
{272}{}{10 ¿etonów.}
{273}{}{50 ¿etonów.}
{274}{}{100 ¿etonów.}
{275}{}{500 ¿etonów.}
{276}{}{1000 ¿etonów.}
{277}{}{Jednak nie chcê niczego wymieniaæ.}
{278}{}{Wszystkie ¿etony, które mam.}

{280}{}{Dlaczego kapsle s¹ tak wa¿ne?}
{281}{}{Kapsle to waluta. Jak przedwojenne pieni¹dze. S³u¿¹ do wymiany na towary. Ale w przeciwieñstwie do przestarza³ych dolarów, stopa kapitalizacji jest teraz ustalana przez zwolenników ognia. To jeden z tych m¹drych pomys³ów, którymi Wyznawcy obdarzyli Phoenix.}
{282}{}{Czy przyjmujecie tu przedwojenne pieni¹dze?}
{283}{}{Tak, to mo¿liwe. Przedwojenne dolary, choæ deprecjonowane, wci¹¿ wprowadzaj¹ zamieszanie w kursie kapsli. Chcesz je wymieniæ?}
{284}{}{Nie, dziêkujê. Ale bêdê o tym pamiêtaæ.}
{285}{}{}
{286}{}{Tak, bêdê tego potrzebowaæ.}
{287}{}{To mo¿liwe. Nale¿y jednak pamiêtaæ, ¿e wartoœæ dolarów spad³a o po³owê. Kiedyœ kurs kontrolowali Wyznawcy Ognia, ale z powodu kryzysu nie mog¹ ju¿ pe³niæ tej funkcji.}
{288}{}{Rozumiem.}
{289}{}{Wszystkie przedwojenne dolary, jakie mam.}

{290}{}{Chcê wymieniæ przedwojenne pieni¹dze.}
{291}{}{Ile dolarów chcesz wymieniæ?}
{292}{}{1 dolar.}
{293}{}{2 dolary.}
{294}{}{3 dolary.}
{295}{}{4 dolary.}
{296}{}{5 dolarów.}
{297}{}{10 dolarów.}
{298}{}{50 dolarów.}
{299}{}{Jednak nie chcê niczego wymieniaæ.}