{100} {} {Widzisz naganiacza z kasyna.}
{101} {} {Widzisz mê¿czyznê. Nêka przechodniów, zapraszaj¹c ich do œrodka kasyna.}
{102} {} {Ktoœ zabi³ naganiacza z kasyna. Wygl¹da na to, ¿e œmieræ Don Diego rozwi¹za³a rêce ulicznym bandytom.}
{103} {} {Chwileczkê, czy to ciebie szuka ochrona? O tak, lepiej trzymaj siê z dala od kasyna.}

{110} {} {Hej, musisz szybko wydaæ kapsle?}
{111} {} {Przestañ kopaæ w ruinach! Tutaj zarobisz na miejscu!}
{112} {} {Jedyne kasyno w ca³ej Arizonie!}
{113} {} {Otwórz swoj¹ ¿y³ê uranu prosto w Phoenix!}
{114} {} {Uran i kapsle! Kapsle i uran!}
{115} {} {Nigdy wczeœniej znak promieniowania nie oznacza³ góry kapsli!}
{116} {} {WejdŸ, fortuna na pewno Ci dziœ sprzyja.}
{117} {} {Idziesz dalej? Mo¿esz przegapiæ swoj¹ ostatni¹ szansê na wzbogacenie siê!}
{118} {} {Nie przechodŸ obojêtnie!}
{119} {} {Kasyno jest otwarte dla wszystkich, w tym dla niemowl¹t i mutantów.}
