{100} {} {Widzisz krupiera.}
{101} {} {Widzisz osobê o bystrym oku i rzeczowym zachowaniu.}
{102} {} {Przepraszam, nie mo¿esz siedzieæ przy ruletce w TYM...}
{103} {} {Jeœli nie wyjdziesz, zawo³am ochronê.}

{200} {} {(To jest ko³o ruletki we wzorze wybuchu j¹drowego. Stó³ obstawiania jest podzielony na czarne i czerwone pola, a dwie komórki oznaczone „0” i „00” s¹ podœwietlone eksplozj¹ j¹drow¹. Krupier bierze jasno¿ó³lt¹ pi³kê, to coœ nazywa siê „bomba”. Zwyk³ym ruchem rêki rzuca ni¹ po kole pod intensywnym spojrzeniem graczy.)}
{201} {} {Ugh, nie wiem jak to rozegraæ.}
{202} {} {Warto spróbowaæ.}
{203} {} {Tylko patrzê, niewa¿ne.}
{204} {} {Oczywiœcie, proszê pana. Przyst¹p.}
{1204} {} {Oczywiœcie, proszê pani. Przyst¹p.}
{205} {} {Wiêc co tu mamy...}

{210} {} {Postaw zak³ady.}
{211} {} {Ju¿ nie gram.}
{212} {} {Obstawiam 5 ¿etonów na czerwone.}
{213} {} {Obstawiam 5 ¿etonów na czarne.}
{214} {} {Stawiam 5 ¿etonów na zero.}
{215} {} {Nie mam ¿adnych ¿etonów. Bêdziesz musia³ przyjœæ innym razem.}

{220} {} {Zak³ady postawione.}
{221} {} {No dalej, balonie, nie zawiedŸ mnie.}
{222} {} {Zobaczmy, komu siê poszczêœci.}
{223} {} {Graj dalej.}
{224} {} {Grajmy dalej.}
{225} {} {Smia³o!}
{226} {} {Stop. Podwajam swój zak³ad.}
{227} {} {Przepraszam. Potroi³em swoj¹ stawkê.}
{228} {} {Uch, proszê pana.}
{1228} {} {Uh, proszê pani.}
{229} {} {Myœlê, ze nie mam ¿etonów. Ok, graj dalej.}

{230} {} {Zadnych wiêcej ofert.}
{231} {} {[Czekaj]}
{232} {} {Bomba na czerwone. Przegrana.}
{233} {} {Bomba na czarne. Przegrana.}
{234} {} {Bomba na zero! Przegrana.}
{235} {} {Bomba na podwójne zero! Wszystkie zak³ady trafiaj¹ do kasyna.}
{236} {} {Chcê graæ dalej.}
{237} {} {Myœlê, ze mam doœæ na dzisiaj.}
{238} {} {Bomba na czerwone. Wygrywasz.}
{239} {} {Bomba na czarne. Wygrywasz.}
{240} {} {Bomba na zero. Wygrywasz! Wyp³ata wynosi od 1 do 8.}
{241} {} {Ok, grajmy dalej.}
{242} {} {Ju¿ nie gram. Muszê odpocz¹æ.}
