{100} {} {Widzisz menad¿era kasyna.}
{101} {} {Widzisz dobrze ubranego mê¿czyznê. Rozgl¹da siê po kasynie.}
{102} {} {Nie powinieneœ wchodziæ do tego kasyna.}

# Pierwszy dialog
{200} {} {Witamy w naszym kasynie. Uwaga - to * jedyne * dzia³aj¹ce kasyno w ca³ej Arizonie.}
{201} {} {Niezbyt imponuj¹ce. Myœla³em, ¿e bêdzie tu bardziej... ¿ywio³owo.}
{202} {} {Masz racjê. Mieszkañcy Phoenix prze¿ywaj¹ ostatnio trudny okres, co wp³ywa równie¿ na nasz¹ dzia³alnoœæ. Ale i tak nie ma wyboru, prawda?}
{203} {} {Nie mo¿na siê z tym k³óciæ.}
{204} {} {To kasyno jest niesamowite. Nie wiem jak uda³o Wam siê przywróciæ je do dzia³ania.}
{205} {} {Doszliœmy do tego d³ug¹ i ciê¿k¹ prac¹. Wszystko dziêki Don Diego.}
{206} {} {Ciekawe.}

# Powtarzajacy siê dialog
{210} {} {Czy mogê siê przydaæ?}
{211} {} {Na razie nic.}

# Zakaz gier kasynowych
{220} {} {Na co sobie pozwalasz? Dlaczego nie wolno mi graæ w kasynie?}
{221} {} {}
{222} {} {Nie zabraniamy ci graæ. Ale mo¿esz ju¿ tylko u¿ywaæ tych ¿etonów, które ci zosta³y. Nie bêdziemy wydawaæ ju¿ nowych ¿etonów.}
{223} {} {Dlaczego nie?}
{224} {} {Spróbuj mi to wyjaœniæ.}
{225} {} {Nietrudno zgadn¹æ, ¿e wygrane innych ludzi szkodz¹ naszemu kasynu. Zdoby³eœ ju¿ wystarczaj¹c¹ liczbê kapsli na wygodn¹ staroœæ. Czas ust¹piæ miejsca nowym graczom. Nie mo¿esz tego zrozumieæ?}
{226} {} {Ty nieszczêsny spekulatorze, nie mo¿esz mnie oszukaæ.}
{227} {} {Rozumiem twoj¹ logikê, ale i tak szkoda.}
{228} {} {Nie denerwuj siê. Przecie¿ zawsze cieszymy siê z bogatych klientów. Pozwól, ¿e zrobiê Ci ma³y prezent na koszt naszego kasyna, aby utrzymaæ przyjazne stosunki. Ta butelka zawiera * prawdziw¹ * przedwojenn¹ whisky. Nie jest zatruta, ani napromieniowana. To kosztowna i rzadka przyjemnoœæ w naszych czasach.}
{229} {} {To wszystko? To nie wystarczy, aby uleczyæ rany w mojej duszy.}
{230} {} {Dziêki za prezent.}
{231} {} {Proponujê równie¿, abyœ zatrzyma³ siê na chwilê w apartamencie i cieszy³ siê wszystkimi urokami ¿ycia w luksusie. Ten pokój i tak jest rzadko u¿ywany. Oto klucz.}
{232} {} {To ju¿ coœ.}
{233} {} {Jesteœ... a z reszt¹.}
{234} {} {Mi³o spedzony czas... A tak przy okazji. Don Diego jest zainteresowany twoj¹ osob¹ i chcia³by omówiæ kilka wspólnych spraw. Powiedzia³em ju¿ stra¿nikom, ¿eby ciê przepuœcili.}
{235} {} {Powiedz mu, ¿e wpadnê, gdy bêdê mia³ trochê wolnego czasu. Czeœæ.}
{236} {} {Zdecydowanie. Te¿ chcia³bym porozmawiaæ z Don Diego.}
{237} {} {Mi³o.}
{238} {} {Tak.}
{239} {} {Do zobaczenia.}

#Zapytania
{250} {} {Czy to ty prowadzisz to kasyno?}
{251} {} {W pewnym sensie. Nazywam siê Bill Gatsby. Jestem tutejszym administratorem, ale to Don Diego jest w³aœcicielem tego miejsca.}
{252} {} {Don Diego - kto to jest?}
{253} {} {Rozumiem.}
{254} {} {Jak, nigdy o nim nie s³ysza³eœ? To wielka osoba. Jedna z najbardziej szanowanych osób w mieœcie. Ale zazwyczaj niechêtnie pokazuje siê klientom i prowadzi interesy ze swojego biura.}
{1254} {} {Jak, nigdy o nim nie s³ysza³aœ? To wielka osoba. Jedna z najbardziej szanowanych osób w mieœcie. Ale zazwyczaj niechêtnie pokazuje siê klientom i prowadzi interesy ze swojego biura.}
{255} {} {Dlaczego nazywa siê Don?}
{256} {} {Prawdopodobnie to tytu³ z szacunku. Ja sam nie wiem, jak i dlaczego zaczêli go tak nazywaæ.}
{257} {} {Czy mogê go poznaæ?}
{258} {} {W¹tpiê. Zaprasza do siebie innych tylko w szczególnie wa¿nych sprawach.}
{259} {} {W pewnym sensie. Nazywam siê Bill Gatsby i jestem administratorem.}

{270} {} {Jak siê tu masz od œmierci Don Diego?}
{271} {} {Wczeœniej mogliœmy pracowaæ samodzielnie. Oczywiœcie teraz muszê pracowaæ za dwóch. Ale to s¹ tymczasowe problemy. W koñcu Diego po prostu siedzia³ na swoim krzeœle, a to ja wykonywa³em prawdziw¹ pracê.}
{272} {} {Rozumiem.}
{273} {} {Myœlê, ¿e nie doceniasz jego wk³adu w biznes... Zmienimy temat?}

{275} {} {Widzê, ¿e kasyno nadal dzia³a po tej eksplozji?}
{276} {} {Tak, okropna historia. Mieliœmy szczêœcie, ¿e wybuch by³ pod ziemi¹ i wystarczaj¹co daleko. Niemniej jednak budynek uleg³ powa¿nym zniszczeniom. Przywrócimy go do pierwotnej postaci za rok... Có¿, przynajmniej na to liczê.}
{277} {} {Rozumiem.}
{278} {} {Trudno mi w to uwierzyæ.}

{280} {} {Mówi¹, ¿e niedaleko poza kasynem zostali zabici Obserwatorzy z zakonu Ognia, to prawda?}
{281} {} {Tak, okropna historia. Osobiœcie niczego nie widzia³em. A opowiadanie plotek to nie moja praca. Porozmawiaj z tymi, którzy byli na zewn¹trz tego dnia.}
{282} {} {Tak, oczywiœcie ¿e tak.}
{283} {} {Na pewno dobrze chronicie swoje kasyno? W koñcu do ataku dosz³o w pobli¿u.}
{284} {} {(Twarz Administratora wykrzywia siê w napiêciu) Nie zas³ugujemy na tego rodzaju nieufnoœæ. Masz jakieœ mocne dowody przeciwko nam? Wiedzia³em. Wiêc lepiej zakoñczmy tê rozmowê. Dziêkujê za zrozumienie.}
{285} {} {Jasne. Masz szczêœcie, jeœli kasyno naprawdê nie jest w to zamieszane.}
{286} {} {Oczywiœcie, ¿e ci wierzê. Zapomnij o moim pytaniu.}

# YY to Twoja w³asn¹ osoba
{290} {} {WejdŸ, amigo. Witamy w rodzinie Don Diego. Teraz jesteœ swoj¹ osob¹, a rodzina ceni swoich ludzi i nie pozostawia ich w k³opotach. Ale ty te¿ musisz przestrzegaæ pewnych zasad. Nie denerwuj szefa - to pierwsza z nich.}
{291} {} {Oczywiœcie, Bill, rozumiem.}
{292} {} {Swietnie, teraz mogê ci powiedzieæ wprost - jesteœ gównianym administratorem. Wiesz o tym?}
{293} {} {Wiesz, w twoich bolesnych s³owach jest trochê prawdy. Ale Don Diego nie znalaz³ nikogo lepszego na to stanowisko. Przynajmniej on i ja mamy pe³ne zaufanie do siebie i dzia³ania kasyna.}
{294} {} {Tak, oczywiœcie.}
{295} {} {WejdŸ, usi¹dŸ. Teraz jesteœ swoj¹ osob¹, a rodzina ceni swoich ludzi i nie pozostawia ich w k³opotach. Ale pamiêtaj, ¿e nie toleruje zdrajców. Nie denerwuj Don Diego - a uratujesz nie tylko swoj¹ skórê, ale ca³¹ rodzinê. Miejmy nadziejê, ¿e nie bêdê musia³ tego powtarzaæ dwa razy.}
{296} {} {Oczywiœcie Bill, rozumiem.}
{297} {} {Wiem, ¿e mnie nie lubisz. Ale musimy wspó³pracowaæ.}
{298} {} {Jako administrator jestem ponad tym. Jeœli szef ci ufa, muszê po prostu zamkn¹æ oczy na swoje osobiste uprzedzenia co do ciebie.}
{299} {} {W³aœciwe myœlenie, Bill.}
{300} {} {Dobrze, ¿e siê rozumiemy. (wyci¹ga klucz z przywieszk¹) Szef kaza³ mi umieœciæ ciê w apartamencie. Nawet ja nie dost¹pi³em takiego zaszczytu. Doceñ tê hojnoœæ.}
{301} {} {Wow. Wreszcie mogê ¿yæ w ludzkich warunkach.}
{302} {} {Nawiasem mówi¹c, jeœli zdecydujesz siê zrelaksowaæ w kasynie, pamiêtaj - zasady gry s¹ takie same dla wszystkich. Jeœli chcesz graæ w ruletkê, kup ¿etony i graj jak zwyk³y gracz. Jeœli wpadniesz w d³ugi, kasyno Ci nie odpuœci. Czy to jasne? Dobrze.}
{303} {} {Uczciwe zasady. Có¿, pójdê ju¿.}
{304} {} {To mnie nie powstrzyma.}

# Praca i przyjêcie do szefa
{320} {} {Czy masz jakieœ zlecenia? Szukam pracy.}
{321} {} {O nie, mamy wystarczaj¹co du¿o ludzi. Don Diego poprosi³, abym wiêcej nie zawraca³ mu g³owy takimi pytaniami.}
{322} {} {Przez chwilê moja oferta pozostanie wa¿na. PA.}
{323} {} {Daj mi szansê, wykonam ka¿de zadanie.}
{324} {} {Ok, w porz¹dku. Poka¿ siê w akcji, a zobaczymy, czy warto siê z tob¹ kontaktowaæ.}
{325} {} {S³ucham.}
{326} {} {Mimo wszystko powiedz swojemu szefowi. A jeœli bêdzie zainteresowany nasz¹ wspó³prac¹?}
{327} {} {To nie ma sensu. Twoja kandydatura... nie jest na poziomie, aby mówiæ o partnerstwie. Rozumiesz?}
{328} {} {Tak. Rozumiem. Ktoœ tutaj jest doœæ arogancki.}
{329} {} {Zaden problem. Rozumiem.}
{330} {} {Dwie szanowane osoby w mieœcie powinny siê nawzajem wys³uchaæ. Nie mo¿esz tego zrozumieæ?}
{331} {} {Och, oczywiœcie to ty jesteœ t¹ s³awn¹ osob¹ w mieœcie. Don Diego mo¿e byæ naprawdê zainteresowany rozmow¹ z tob¹.}
{332} {} {Swietnie. Kiedy mogê go poznaæ?}
{333} {} {Z pewnoœci¹ twój szef ma dla mnie prace. Jestem mistrzem ringu.}
{334} {} {Hmm, czasami naprawdê têsknimy za twardzielami. Tym bardziej TAK silnymi.}
{335} {} {Swietnie. Czy mogê poznaæ twojego szefa?}
{336} {} {Don Diego wys³a³ mnie do pracy. Jaki masz problem?}
{337} {} {Och, a wiêc to jest nasz nowy pracownik. Jak mi³o jest pozbyæ siê tego ciê¿aru odpowiedzialnoœci, przynajmniej trochê.}
{338} {} {Kontynuuj.}
{339} {} {Po œmierci Don Diego weszliœmy do piek³a. Naprawdê przyda mi siê m¹dry wspó³pracownik.}

{340} {} {Powiem stra¿nikom, ¿eby ciê przepuœcili. Biuro Don Diego znajduje siê na drugim piêtrze. Zachowuj siê tam grzecznie, nie wykonuj gwa³townych ruchów, broñ trzymaj w kaburze. Wszystko jasne? Mo¿esz iœæ.}
{341} {} {Tak, nie musia³eœ wyjaœniaæ mi tego co oczywiste.}
{342} {} {Och, nie martw siê, bêdê mi³y.}

{350} {} {Jeden z naszych sta³ych klientów zupe³nie zapomnia³ o sp³acie d³ugów. Musisz mu przypomnieæ. Ale tak, ¿eby d³ug zosta³ sp³acony.}
{351} {} {Brzmi niesamowicie banalnie. Jaki jest haczyk?}
{352} {} {Nie s¹dzê, ¿eby w ogóle mia³ jakieœ kapsle. Mówi¹, ¿e kompletnie siê upi³ i jest na krawêdzi. Jeœli tak, to stracimy klienta, a wraz z nim nasze kapsle. A tak przy okazji wisi nam }
{353} {} { kapsli... Zapisz to sobie.}
{354} {} {Znajdziesz tego sukinsyna w slumsach. IdŸ, wci¹¿ mam du¿o do zrobienia.}
{355} {} {Jasne, do zobaczenia.}
{356} {} {O tym d³u¿niku i jego d³ugu.}
{357} {} {Jakieœ postêpy w tej sprawie?}
{358} {} {Przepraszam, nijakie. Ale pracujê nad tym.}
{359} {} {Przypomnij mi, gdzie mieszka ten typ?}
{360} {} {Mieszka we wschodnich slumsach. Nazywa siê Badi.}
{361} {} {Rozumiem. Dziêkujê Ci.}
{362} {} {Ile ten klient jest winien kasynu?}
{363} {} { kapsli. Tylko gotówka. Nie pozwól temu spekulantowi oszukiwaæ barterem lub jak¹œ us³ug¹. Musisz mieæ siê na bacznoœci z ludŸmi takimi jak on.}
{364} {} {Ha³aœliwe inwestycje w banku.}
{365} {} {Klient nie ¿yje. Nie mogê zrobiæ nic wiêcej.}
{366} {} {Nie ¿yje? Obawiam siê, ¿e ta nieprzyjemna wiadomoœæ strasznie zdenerwuje mojego szefa. Có¿, okazuje siê, ¿e wszyscy straciliœmy swoje prawne kapsle. WyjdŸ. Nie potrzebujemy najemników, którzy nie wiedz¹, jak pracowaæ.}
{367} {} {Hej!}
{368} {} {Oto jego d³ug, }
{369} {} { kapsli. Nie pytaj mnie, jak to zrobi³em.}
{370} {} {I bardzo dobrze. Dziêkujê za pomoc. Oto Twoja zap³ata - jedna pi¹ta nale¿nej kwoty.}
{371} {} {Dzieñ dobry.}
{372} {} {Jeœli moje pierwsze zlecenie posz³o tak dobrze, to mo¿e twój szef ma dla mnie jeszcze inne?}