{100}{}{Widzisz boya hotelowego.}
{101}{}{Widzisz bardzo uprzejmego m³odego mê¿czyznê o przymilnym spojrzeniu.}
{102}{}{N-nie zameldujesz siê w swoim pokoju w tym... w tym...}
{103}{}{Przepraszam kolego, ale nie wolno mi pomagaæ takiemu dupkowi jak ty.}
{1103}{}{Przepraszam, ale zakazano mi pomagania takiej suce jak ty.}

{200}{}{Co mogê zrobiæ, proszê pana?}
{1200}{}{Co mogê zrobiæ, proszê pani?}
{201}{}{Kim jesteœ?}
{202}{}{Jestem boyem hotelowym. Za³atwiam drobne sprawy za niewielk¹ op³at¹.}
{203}{}{Rozumiem.}
{204}{}{To jakiœ postêp? Ja - na pewno mam... Hehe.}

{210}{}{Dobranoc, sir.}
{1210}{}{Dobranoc, proszê pani.}
{211}{}{Dzieñ dobry panu.}
{1211}{}{Dzieñ dobry pani.}
{212}{}{Dzieñ dobry panu.}
{1212}{}{Dzieñ dobry pani.}
{213} {} {Dobry wieczór panu.}
{1213} {} {Dobry wieczór pani.}
{214} {} {Moje uszanowanie, sir.}
{1214} {} {Moje uszanowanie, proszê pani.}
{218} {} {Rozumiem.}
{219} {} {Do widzenia.}

{220} {} {Co to za miejsce?}
{221} {} {Mamy tu kasyno i ma³y hotelik na drugim piêtrze. Tutaj mo¿esz siê zrelaksowaæ i zagraæ.}
{222} {} {Przypomnij mi, co tu robisz?}
{223} {} {Za³atwiam drobne sprawy, sir. Jestem boyem hotelowym.}
{1223} {} {Za³atwiam drobne sprawy, pani. Jestem boyem hotelowym.}
{224} {} {Co tutaj robisz?}
{225} {} {Wiêc to jest hotel?}
{226} {} {Chcê wynaj¹æ pokój w hotelu.}
{227} {} {Jest jeden wolny pokój. Cena to tylko }
{228} {} {kapsli na noc.}
{229} {} {Albo nie, zmieni³em zdanie.}
{1229} {} {Albo nie, zmieni³am zdanie.}
{230} {} {Przepraszam, nie mam tylu kapsli.}
{231} {} {Ok. Oto kapsle.}
{232} {} {Jesteœ wypoczêty i gotowy do drogi.}

# Aranzacja apartamentu
{250} {} {Zameldowa³em siê w apartamencie. Czy mo¿esz wnieœæ tam jakieœ meble?}
{1250} {} {Zameldowa³am siê w apartamencie. Czy mo¿esz wnieœæ tam jakieœ meble?}
{251} {} {Oczywiœcie, sir. Czego potrzebujesz?}
{1251} {} {Oczywiœcie, proszê pani. Czego potrzebujesz?}
{252} {} {W sumie mo¿e zostaæ jak jest.}
{253} {} {Jakiegoœ dzbanu. [5 kapsli]}
{254} {} {Ma³ych pó³ek na rzeczy. [20 kapsli]}
{255} {} {Du¿¹ szafê. [50 kapsli]}
{256} {} {Lodówki. [50 kapsli]}
{257} {} {Niewa¿ne.}
{258} {} {Um. Kapsle z góry.}
{259} {} {Tak, tak, oczywiœcie...}
{260} {} {Wszystko gotowe, sir.}
{1260} {} {Wszystko gotowe, proszê pani.}
{261} {} {Swietnie.}
{262} {} {Hmm. Obs³uga jest okropna, gdy nie ma ¿adnej konkurencji.}

# Wzrost umiejêtnoœci
{300} {} {Powiedz mi, czy to kasyno jest naprawdê uczciwe?}
{301} {} {Szczerze... Tak, tak myœlê.}
{302} {} {Dlaczego siê wahasz?}
{303} {} {Có¿, to zale¿y w du¿ej mierze od prawdopodobieñstwa. I generalnie jest ono nieco wy¿sze dla kasyna ni¿ dla gracza. Ale to nie znaczy, ¿e nie mo¿esz wygraæ i staæ siê bogatym.}
{304} {} {Powiedz mi, jak to zrobiæ. Z pewnoœci¹ istniej¹ ró¿ne sztuczki, prawda?}
{305} {} {Uch, nie. (rozgl¹da siê na stra¿nika i scisza g³os) Szefowi siê to nie spodoba.}
{306} {} {Nikt siê o tym nie dowie. [kusisz pokazuj¹c kapsle]}
{307} {} {W takim razie zapomnij.}
{308} {} {Huh, dla naszych klientów wszystko. Za 300 kapsli dam ma³¹... lekcjê, tak. Jej tytu³ to: „Jak mo¿esz zwiêkszyæ swoje szanse o piêæ procent i dlaczego to du¿o”. Coœ w tym stylu.}
{309} {} {Mogê ³atwo odzyskaæ te kapsle. Kiedy zaczynamy?}
{310} {} {Nie staæ mnie na to. Do zobaczenia.}
{311} {} {Spotkajmy siê przy stole bilardowym na drugim piêtrze. I ten... nie zapomnij o kapslach.}
{312} {} {Zaden problem.}

{320} {} {Mogê zacz¹æ w ka¿dej chwili.}
{321} {} {Oto 300 kapsli. }
{322} {} {Poczekaj trochê d³u¿ej. Muszê iœæ po kapsle.}
{323} {} {Dziêki. (chowa kapsle rozgl¹daj¹c siê) Zacznijmy od ogólnych zasad...}
{324} {} {[Kontynuuj]}
{325} {} {...I nigdy nie dzielcie siê na pi¹tki, wtedy w sumie bêdzie dziesiêæ.}
{326} {} {Wow, ale to trudne. Ale teraz wiem dok³adnie, czego NIE robiæ.}
{327} {} {To wszystko, co wiem. Ostatecznie to piêæ procent szczêœcia zadecyduje o Twoim losie w grze. Dobrze, pójdê ju¿, zanim szef nabierze podejrzeñ.}
{328} {} {Dziêki za radê, ch³opcze.}
{329} {} {Wynoœ siê, ju¿ ciê nie potrzebujê.}