{100} {} {Widzisz cz³owieka Diego.}
{101} {} {Widzisz jednego z ludzi Don Diego.}

{110} {} {Moje uszanowanie. Jak siê miewa Don Diego?}
{111} {} {Nie wiem, jak sobie radzi³em z szefem.}
{112} {} {Mogê w czymœ pomóc?}
{113} {} {Przeka¿ mój najg³êbszy szacunek Don Diego.}
{114} {} {Mo¿esz poprosiæ Dona podwy¿kê dla mnie?}

{115} {} {Moje uszanowanie.}
{116} {} {Jak siê masz?}
{117} {} {Wróæ do kasyna.}
{118} {} {Szef ciê tu nie lubi.}
{119} {} {Moim zadaniem jest byæ po bezpiecznej stronie.}

{120} {} {Lepiej tu nie zostawaj.}
{121} {} {To jest przestrzeñ biurowa, co tu robisz?}
{122} {} {Masz interes do szefa? To idŸ do niego.}
{123} {} {Szefowi nie spodoba siê, ¿e z tob¹ rozmawiam.}
{124} {} {Jeœli dowiem siê, ¿e jesteœ szpiegiem...}

{125} {} {Co ty tutaj robisz?}
{126} {} {Szpiegujesz?}
{127} {} {Hej, wracaj natychmiast do kasyna.}
{128} {} {To s¹ pomieszczenia s³u¿bowe.}
{129} {} {Nie masz tu wstêpu.}
