{100} {} {Widzisz barmana.}
{101} {} {Widzisz barmana. Nie jesteœ wcale zaskoczony, widz¹c go tutaj.}
{102} {} {Nie, nie, w tym „garniturze” zniszczysz wszystkie naczynia...}
{103} {} {To jest obszar dla personelu. Proszê usi¹œæ przy ladzie.}
{104} {} {Muszê wróciæ do baru.}

# Plywajace repliki
{110} {} {Vegas Lights and Brahmin Steak.}
{111} {} {Przepraszam, Nuka-Rum siê skoñczy³.}
{112} {} {Ash Los Angeles gotowe.}
{113} {} {Oto twoja Nuclear Mary.}
{114} {} {Kto zamawia³ Atomic Cocktail?}
{115} {} {Ty ju¿ masz doœæ, kolego.}
{116} {} {Nie po³ykaj wszystkiego naraz.}
{117} {} {Uwierz mi, ten koktajl postawi Ci kutasa.}
{118} {} {Twoi rodzice nie maj¹ nic przeciwko? Spokojnie, tylko ¿artujê.}
{119} {} {Kawa? Ooh, jesteœ prawdziwym koneserem.}

#Dialog
{200} {} {Pierwszy raz w naszym kasynie? Mam nadziejê, ¿e Ci siê spodoba.}
{201} {} {Mo¿e.}
{202} {} {Och, sk¹d taki sceptycyzm? Spokojnie, to jedyne miejsce w mieœcie, w którym mo¿esz siê zrelaksowaæ.}
{203} {} {Nie potrzebujê twojego wsparcia, barmanie.}
{204} {} {Naprawdê? W takim razie powinienem tu zostaæ.}
{205} {} {Nalej mi coœ mocniejszego, kolego. Poniewa¿ mam zamiar rozwaliæ bank.}
{206} {} {I to jest dobre podejœcie. Powodzenia.}
{207} {} {Twój zak³ad bêdzie tego potrzebowa³.}
{208} {} {Dziêki.}

{210} {} {Chcesz siê czegoœ napiæ?}
{211} {} {Na razie siê powstrzymam.}

{212} {} {Hej, oto nowy mistrz areny! To niespodzianka. Och, czekaj, wiem, ¿e to niezupe³nie zgodnie z zasadami, ale we w³asnym imieniu chcê postawiæ ci butelkê piwa. (do siebie) Teraz powiem wszystkim...}
{213} {} {Dziêki stary. To bardzo mi³e z twojej strony.}
{214} {} {Ten napój to szczyny. Ale podoba mi siê twoje nastawienie.}

{215} {} {Och, to ty. Jak siê miewa Don Diego? Widzê, ¿e trafi³eœ w dziesi¹tkê.}
{216} {} {Zamknij siê i daj mi drinka.}
{217} {} {Tak, w porz¹dku. Jaki rodzaj alkoholu tak bardzo chwali³ w tym barze?}
{218} {} {Proponujê spróbowaæ naszej tequili. Najlepsze, co mo¿esz dziœ znaleŸæ. (pochyla siê i zni¿a g³os) Swoj¹ drog¹ w kasynie mamy specjalne ceny dla swoich.}
{219} {} {Specjalne? To super.}

{220} {} {Jaka jest historia tej strzelaniny na ulicy?}
{221} {} {Ciemna sprawa. Ktoœ zaatakowa³ spokojnie spaceruj¹cych mnichów. Ja sam niczego nie widzia³em, ale s³ysza³em wiele wersji. Nie ufaj tym wszystkim plotkom.}
{222} {} {A jeœli zap³acê dobr¹ cenê?}
{223} {} {S³uchaj, nie lubimy o tym rozmawiaæ. Zakoñczmy tê rozmowê.}
{224} {} {Jeœli dowiem siê, ¿e coœ ukrywasz, jesteœ skoñczony.}
{225} {} {Oczywiœcie, wierzê Ci. Zapomnij o moim pytaniu, kolego.}

{230} {} {Kto tu wszystko prowadzi?}
{231} {} {Nasz administrator przej¹³ interes. Wszystkie tutejsze sprawy przesz³y na niego, potraktuj to jako prezent. Ktoœ wyœwiadczy³ mu wielk¹ przys³ugê, zabijaj¹c Don Diego. (w zamyœleniu) Có¿, przynajmniej ja nadal tutaj pracujê.}
{232} {} {Rozumiem.}
{233} {} {Potrzebujesz administratora? Jest w tym pokoju w pobli¿u sceny.}
{234} {} {Nie, mówiê o w³aœcicielu kasyna.}
{235} {} {Don Diego jest w³aœcicielem ca³ej tej posiad³oœci. To on zebra³ ludzi i odbudowa³ kasyno. Dlaczego pytasz?}
{236} {} {Z ciekawoœci. Nie zwracaj uwagi.}
{237} {} {Chcê go poznaæ.}
{238} {} {To nie bêdzie ³atwe. Porozmawiaj z administratorem. On decyduje, kto mo¿e zobaczyæ siê z szefem.}
{239} {} {Dobrze.}

{240} {} {Czy widzia³eœ Georga Crooka?}
{241} {} {(przewraca oczami do góry z niezadowoleniem)}
{242} {} {Co? Trafi³ ju¿ do nieba? O nie, co za szkoda... Aaa, jest na drugim piêtrze, rozumiem.}
{243} {} {Pokój na drugim piêtrze? Jasne.}

{250} {} {Wiesz o wszystkim, co siê tutaj dzieje, prawda?}
{251} {} {Przepraszam, ale nie rozpowiadam plotek i informacji. Szefowi siê to nie podoba.}
{252} {} {Nie mam tu nic innego do roboty.}
{253} {} {Rozumiem, nie ma problemu.}
{254} {} {Myœla³em, ¿e barmani wiedz¹ wszystko.}
{255} {} {To nie jest dalekie od prawdy. Ale jestem te¿ wyszkolony w przestrzeganiu zasad.}
{256} {} {Dam ci napiwek.}
{257} {} {To niczego nie zmieni, sir.}
{1257} {} {To niczego nie zmieni, proszê pani.}
{258} {} {Hmm. Zróbmy inaczej - zap³acê, jeœli bêdziesz rozpowszechniaæ o mnie dobre plotki.}
{259} {} {Nie rozumiem, czy to jakiœ ¿art? Masz w mieœcie œwietn¹ reputacjê. Nie mogê uwierzyæ, ¿e naprawdê potrzebujesz byæ heroiczn¹ legend¹.}
{260} {} {Masz racjê... Ok, zapomnij.}
{261} {} {Có¿, to wydam kapsle na coœ bardziej znacz¹cego.}
{262} {} {Och, rozumiem, potrzebujesz trochê dobrej reputacji, ¿eby rozpocz¹æ tu karierê, tak? Tak, mogê coœ wymyœliæ.}
{263} {} {Nie œpiesz siê. Wrócimy do tego tematu póŸniej.}
{264} {} {Muszê iœæ po gotówkê. Do zobaczenia.}
{265} {} {Zap³acê 100 kapsli. Chcê tylko dobrych plotek.}
{266} {} {Krótka historia o twojej wiarygodnoœci? To nie bêdzie trudne.}
{267} {} {Zap³acê 200 kapsli. Wymyœl coœ wspania³ego, ale bez fanatyzmu.}
{268} {} {Imponuj¹ca historia z ulicy? A mo¿e zabawna bijatyka na pustyni? Znajdê coœ, o czym mogê opowiedzieæ innym.}
{269} {} {Zap³acê 300 kapsli. Ale musisz daæ z siebie wszystko.}
{270} {} {Heroiczna Legenda? (pstryka palcami) MAM! Wiem co robiæ, mo¿esz na mnie liczyæ.}
{271} {} {Oto kapsle. Czekam na wyniki, partnerze.}
{272} {} {Zrobiê co w mojej mocy, sir.}
{1272} {} {Zrobiê co w mojej mocy, proszê pani.}
{273} {} {Do zobaczenia.}
{274} {} {Jakiœ problem? Nic, poczekam.}
{275} {} {Ech, musimy liczyæ...}

{280} {} {Czy masz tu tylko napoje alkoholowe?}
{281} {} {Zasadniczo tak. Jeœli chcesz, mogê te¿ zaoferowaæ czyst¹ wodê. Ale niewielu jest gotowych pozwoliæ sobie na ten luksus.}
{282} {} {Sk¹d bierzesz swoje drinki?}
{283} {} {Mamy wiele Ÿróde³. Piwo produkuje kilka bimbrowni. Czasami w starych ruinach mo¿na znaleŸæ coœ wyj¹tkowego, na przyk³ad przedwojenn¹ whisky. Tequilê robimy sami.}
{284} {} {Sami? Zartujesz?}
{285} {} {To nasza duma. Surowiec zamawiamy z po³udniowych plantacji. Nastêpnie tutaj przygotowujemy z niego drinki i alkohole lecznicze. O ile wiem, jesteœmy jedynymi w tej bran¿y.}
{286} {} {W³asna produkcja w dzisiejszych czasach? To imponuj¹ce.}
{287} {} {Hmm, domowy alkohol? To zawsze wzbudza moj¹ czujnoœæ.}
{288} {} {Woda, piwo, whisky i oczywiœcie tequila domowej roboty.}
{289} {} {Tak, oczywiœcie.}
{290} {} {Gdzie jest twoja s³ynna tequila? Chcia³em zamówiæ kilka butelek, ale pó³ki s¹ puste.}
{291} {} {Przepraszam. Ma³a si³a wy¿sza w produkcji. Rozwi¹zujemy w³aœnie ten problem, ale zajmie to trochê czasu.}
{292} {} {Szkoda. Mam nadziejê, ¿e szybko znajdziecie rozwi¹zanie.}
{293} {} {Co to za kasyno, jeœli nie mo¿na siê tu nawet napiæ drinka? Nie mog³em znaleŸæ najgorszego miejsca.}
{294} {} {Mamy wiele Ÿróde³. Piwo produkuje kilka bimbrowni. Czasami w starych ruinach mo¿na znaleŸæ coœ wyj¹tkowego, na przyk³ad przedwojenn¹ whisky. Sami produkowaliœmy tequilê, ale bimber popad³ w ruinê. Jednak pracujemy nad tym problemem.}
{295} {} {Sami produkujecie tequilê? Có¿, oby tak dalej.}
{296} {} {W³asna produkcja? Szkoda, ¿e to przesz³oœæ.}