{100} {} {Widzisz krupiera.}
{101} {} {Widzisz schludnego mê¿czyznê w garniturze. Przez chwilê patrzysz z fascynacj¹, jak sprytnie tasuje karty.}
{102} {} {Uh, obawiam siê, ze nie mo¿esz trzymaæ kart w TYM...}
{103} {} {Przepraszam, proszê pana, nie mogê ci pomóc.}
{1103} {} {Przepraszam pani, ale nie mogê ci pomóc.}

# Znajomosc
{200} {} {(Przed sob¹ widzisz stó³ do gry w karty, a przy nim schludny mê¿czyzna o powa¿nym wygl¹dzie zrêcznie tasuje talie kart.) Grasz w atomowego Jack'a?}
{201} {} {Nie dzisiaj.}
{202} {} {Nie, nie znam zasad.}
{203} {} {Ok. Najpierw jednak wyjaœnij mi zasady.}
{204} {} {To jest g³ównie odmiana blackjacka. Musisz zebraæ 21 punktów przy minimalnej liczbie kart z bombami atomowymi. Po zebraniu wymaganej liczby mo¿esz „zbombardowaæ” taliê. Ta gra wymaga trochê wiêcej inteligencji ni¿ ruletka czy automat do gry. Ale tutaj te¿ stawki s¹ wy¿sze. Jeœli oczywiœcie jesteœ gotów zaryzykowaæ.}
{205} {} {Zdecydowanie.}
{206} {} {Grasz?}
{207} {} {Tak.}
{208} {} {Nie.}

#Bets
{210} {} {Nowa partia. Obstawiaj zak³ady.}
{211} {} {chipy)}
{212} {} {Nie gram.}
{213} {} {Chcia³bym do³aczyæ, ale nie mam ¿etonów.}
{1213} {} {Chcia³abym do³aczyæ, ale nie mam ¿etonów.}
{214} {} {Mój zak³ad to 10 ¿etonów.}
{215} {} {Mój zak³ad to 20 ¿etonów.}
{216} {} {Mój zak³ad to 30 ¿etonów.}
{217} {} {Mój zak³ad to 40 ¿etonów.}
{218} {} {Zak³ady s¹ akceptowane. Rozpoczynam dystrybucjê.}
{219} {} {Zacznijmy.}

{220} {} {Przypomnij mi, jaki by³ ostatni rachunek?}
{221} {} {Account}
{222} {} {k}
{223} {} {na twoj¹ korzyœæ.}
{224} {} {na korzyœæ kasyna.}
{225} {} {Ok. Kontynuujmy.}
{226} {} {Mój zak³ad to 50 ¿etonów.}

{230} {} {(Krupier dobiera dwie karty i k³adzie je zakryte. Nastêpnie odwraca jedn¹ z nich, pokazuj¹c nomina³ }
{231} {} {punkty)}
{232} {} {Ja.}
{233} {} {(Otrzymano dwie karty o wartoœci nominalnej }
{234} {} {punkty)}
{235} {} {[Dalej.]}
{236} {} {(Twoja rêka ma karty o wartoœci }
{237} {} {punktów. Krupier ma otwarte karty o wartoœci }
{238} {} {punktów.) Jakie podejmujesz dzia³ania?}

{240} {} {Poddaje siê.}
{241} {} {Pierwszy gracz opuszcza grê. Po³owa zak³adu wygasa.}
{242} {} {Panowie, zostawiê was.}
{243} {} {Podwój swój zak³ad.}
{244} {} {Stawka zostaje podwojona. Przypominam, ¿e zak³ad mo¿na podbiæ tylko raz na mecz.}
{245} {} {Stawka podwoi³a siê.}
{246} {} {[Kontynuuj grê]}
{247} {} {Pass}
{248} {} {Pierwszy gracz pomija kartê. Kontynuujemy dystrybucjê...}
{249} {} {[Kontynuuj grê]}
{250} {} {Wiêcej.}
{251} {} {Pierwszy gracz dobiera kartê...}
{252} {} {[Kontynuuj grê]}

{260} {} {Gracz pierwszy: Nuclearjack! Czy chcia³byœ jeszcze pograæ?}
{261} {} {Nie, dziêkujê.}
{262} {} {O tak, chce jeszcze trochê pograæ.}
{263} {} {Kasyno: atomówka. Twój zak³ad wygasa. Chcesz dalej graæ?}
{264} {} {Tak, muszê siê odkuæ.}
{265} {} {Nie, nie.}
{266} {} {Gracz pierwszy: przegrana. Twój zak³ad wygasa. Chcesz graæ?}
{267} {} {Kasyno: pora¿ka. Czy chcesz kontynuowaæ?}
{268} {} {Remis. Gracze pozostaj¹ ze swoimi zak³adami. Czy chcesz kontynuowaæ?}
{269} {} {Limit karty zosta³ osi¹gniêty.}