{100} {} {Widzisz bywalca kasyna.}

{101} {} {Wygl¹da na to, ¿e ten gracz ma dzisiaj du¿o szczêœcia.}
{102} {} {Widzisz klienta kasyna. Wpada w sza³ spowodowany ci¹giem zwyciêstw.}
{103} {} {Ten gracz wygl¹da na znudzonego. Wygl¹da na to, ¿e nie wygrywa, ale te¿ nie przegrywa.}
{104} {} {Widzisz klienta kasyna. Jest z³y przez szereg strat.}
{105} {} {Widzisz bywalca kasyna, strasznie boli go g³owa. NajwyraŸniej straci³ ca³¹ swoj¹ fortunê.}

{109} {} {Jak sobie radzisz w tej zbroi?}

# Uwagi dotycz¹ce odpowiedzi
#- DOBRZE
{110} {} {Fajne miejsce, prawda?}
{111} {} {U mnie œwietnie, a u ciebie?}
{112} {} {Mam dzisiaj szczêœcie.}
{113} {} {To kasyno to najlepsze miejsce w historii.}
{114} {} {Wiem, jak wygraæ, serio.}
{115} {} {Podoba ci siê ta gra? Czysta przyjemnoœæ.}
{116} {} {Kapsle! Kapsle! Kapsle!}
{117} {} {Nie odstraszaj ode mnie szczêœcia.}
{118} {} {Dlaczego to zawsze przytrafia siê mnie?}
{119} {} {W³aœnie mia³em prze³om.}
{120} {} {OdejdŸ.}
{121} {} {Nie stój tutaj.}
{122} {} {Dzisiaj wszystkie ¿etony bêd¹ moje!}
{123} {} {Ju¿ czujê siê czêœci¹ karabinu maszynowego.}
# Cytat z odcinka 2 sezonu 1 Star Track: ju¿ czujê siê czêœci¹ konsoli.
{124} {} {Znamy siê od dawna.}
{125} {} {Nie licz na alkohol.}
{126} {} {Odwa¿ysz siê graæ przeciwko mnie?}
{127} {} {Ci cholerni biedni turyœci...}
{128} {} {Nie daj siê z³apaæ w sid³a hazardu, kiedy grasz.}
{129} {} {Chcesz siê ze mn¹ podzieliæ swoim szczêœciem?}

# - zle
{150} {} {Co za okropne miejsce, nic nie mogê tu wygraæ.}
{151} {} {Radzê sobie gorzej ni¿ ty? Serio?}
{152} {} {Mam dzisiaj du¿o pecha.}
{153} {} {To nie jest kasyno, tylko miejsce spotkañ jednorêkich bandytów.}
{154} {} {Tutaj nigdy nie wygram.}
{155} {} {Nie powinienem nawet graæ w tê grê. Co za beznadzieja.}
{156} {} {Hej, po¿ycz kilka kapsli.}
{157} {} {Jeœli wygram, postawiê ka¿demu drinka.}
{158} {} {Mam nadziejê, ¿e masz wiêcej szczêœcia ni¿ ja.}
{159} {} {Ta passa pecha chyba nigdy siê nie skoñczy.}
{160} {} {Naprawdê muszê wygraæ.}
{161} {} {Có¿, to tylko gra.}
{162} {} {Koœci coœ mi dziœ nie podchodz¹.}
{163} {} {Oni wyraŸnie oszukuj¹.}
{164} {} {Fortuna odwróci³a siê ode mnie.}
{165} {} {Wszêdzie s¹ oszuœci.}
{166} {} {Ju¿ nie mam wszystkich ¿etonów.}
{167} {} {Szczêœcie to dziwka.}
{168} {} {Uda³o mi siê wygraæ a¿ 60 ¿etonów! Ale wtedy...}
{169} {} {Stawk¹ jest ca³e moje ¿ycie!}
{170} {} {Ostro¿nie, oszukuj¹ tutaj.}
{171} {} {Musieli ulepszyæ maszyny.}

# Losowe repliki
# - zle
{200} {} {No dalej!}
{201} {} {Dlaczego ta gra jest dla mnie taka okrutna?}
{202} {} {Nie mam dzisiaj szczêœcia.}
{203} {} {Durna gra!}
{204} {} {Nienawidzê tej gry.}
{205} {} {Chyba mam gor¹czkê!}
{206} {} {Zaczê³o siê tak dobrze...}
{207} {} {Albo wygram, albo nie ¿yjê.}
{208} {} {Jeœli znowu przegram, zniszczê to miejsce.}
{209} {} {Nigdzie siê nie wybieram bez wygranej.}
{210} {} {Nie mogê wygraæ.}
{211} {} {Wyszed³em prawie na zero!}
{212} {} {Jeszcze trochê i jestem bankrutem.}
{213} {} {Jestem zmêczony tym ci¹g³ym przegrywaniem.}
{214} {} {Czy to naprawdê by³ mój ostatni ¿eton?}
{215} {} {Cholera!}
{216} {} {Jeœli bêdê teraz mia³ pecha, odejdê.}
{217} {} {Moje kieszenie s¹ ju¿ zupe³nie puste.}
{218} {} {Prawie siê uda³o...}
{219} {} {Nie to!}
{220} {} {Nienajlepiej sobie radzê.}
{221} {} {Ech, jeszcze raz?}
{222} {} {Nie, nie. Zatrzymajcie to!}
{223} {} {Ups.}
{224} {} {Prawie!}
{225} {} {Cholera!}
{226} {} {Jak to siê sta³o?}
{227} {} {Dlaczego ja?}
{228} {} {Jeszcze co?!}
{229} {} {Niezbyt szczêœliwie...}
{230} {} {Potrzebujê drinka.}
{231} {} {Wszystko by³o przeciwko mnie.}
{232} {} {Tak blisko!}
{233} {} {Zobacz, jak rozbijam bank.}
{234} {} {Dobra, jeszcze jeden raz.}
{235} {} {Ugh, czas siê odlaæ.}
{236} {} {Mogê siê odkuæ sprzedaj¹c œledzionê...}
{237} {} {Nie w tym ¿yciu.}
{238} {} {Przestañ ze mnie kpiæ!}
{239} {} {Dziœ nie jest mój dzieñ.}
{240} {} {Twoja matka!}
{241} {} {O nie!}

#- DOBRZE
{300} {} {Tak!}
{301} {} {Nie zawiedŸ mnie tym razem.}
{302} {} {Mam dzisiaj szczêœcie.}
{303} {} {Swietna gra!}
{304} {} {Uwielbiam tê grê.}
{305} {} {To prawda czy ja tylko œniê?}
{306} {} {Ok, kontynuujmy.}
{307} {} {Mogê dziœ piêknie ¿yæ.}
{308} {} {Jeœli wygram, postawiê wszystkim drinka.}
{309} {} {Nie mogê przestaæ, póki mam szczêœcie.}
{310} {} {Nie mogê przegraæ, nie teraz.}
{311} {} {Cooo? JACKPOT?!}
{312} {} {W tym tempie bêdê najbogatszy w mieœcie.}
{313} {} {By³o lepiej.}
{314} {} {Kapsle! Kapsle! Kapsle!}
{315} {} {Tak!}
{316} {} {Teraz bêdê mia³ szczêœcie.}
{317} {} {Zetony! Do mnie!}
{318} {} {Niech zawsze tak bêdzie.}
{319} {} {Hurra! Wygra³em!}
{320} {} {Jeszcze raz!}
{321} {} {No pewnie!}
{322} {} {No dalej! Daj spokój!}
{323} {} {Swietnie!}
{324} {} {Dobrze!}
{325} {} {Kelner, kolejny drink!}
{326} {} {Szczêœciarzu, nie zawiedŸ mnie.}
{327} {} {Kto jest dziœ zwyciêzc¹? Ja!}
{328} {} {Haha!}
{329} {} {Najwy¿ej bêdê spa³ w swojej trumnie.}

# - Przed scena
{350} {} {Veronica dobrze œpiewa.}
{351} {} {Veronica jest cudowna.}
{352} {} {Brakuje jej ruchów.}
{353} {} {Piosenkarka wydawa³a siê byæ torturowana przed wystêpem.}
{354} {} {Jej piosenki s¹ takie smutne.}
{355} {} {O czym ona œpiewa?}
{356} {} {Zmieñ repertuar.}
{357} {} {Chyba tym razem tylko pos³ucham.}
{358} {} {Mieszkam tylko tutaj.}
{359} {} {To jedyne miejsce, w którym jest piosenkarka.}
{360} {} {Uwielbiam kasyno za tê scenê.}
{361} {} {W mieœcie nie ma innej aktywnej sceny.}
{362} {} {Barman, kolejny koktajl.}
{363} {} {Ile p³acê, barmanie?}
{364} {} {Barman, rachunek!}
{365} {} {Wygl¹da na to, ¿e nie mam czym zap³aciæ.}
{366} {} {To najlepszy bar w mieœcie.}
{367} {} {Serwuj¹ tu œwietne steki.}
{368} {} {Przepraszam, ale po tym wychodzê.}
{369} {} {}