{100} {} {Widzisz uchodŸcê.}
{101} {} {Widzisz bardzo wzburzon¹ osobê.}
{102} {} {Wychodzimy. Nasze stopy nie bêd¹ ju¿ d³u¿ej chodziæ po tym okrutnym mieœcie.}

{110} {} {Musimy wyjœæ.}
{111} {} {Nie ma innego wyjœcia.}
{112} {} {Lepiej kieruj siê na po³udnie.}
{113} {} {Gdzie s¹ inni?}
{114} {} {Nie przejdziemy przez pustyniê.}
{115} {} {Przejœcie przez pustyniê to pewna œmieræ.}
{116} {} {Jeœli nie na po³udniu, to gdzie?}
{117} {} {Mo¿e pójdziemy w góry na zachodzie?}
{118} {} {Kr¹¿y³y pog³oski o Krypcie, ale gdzie ona jest?}
{119} {} {Czas wyjœæ.}

{200} {} {(kilka osób aktywnie dyskutuje przed tob¹)}
{201} {} {Hej, co s³ychaæ?}
{202} {} {(uwaga przenosi siê gwa³townie na ciebie; dostrzegasz pewien strach i napiêcie w wielu oczach) Myœlê, ¿e wiesz, co siê sta³o. Dosz³o do wielkiej tragedii, która zakoñczy³a rozwój duszy i cia³a w tym mieœcie.}
{203} {} {Masz na myœli wysadzenie katedry?}
{204} {} {Oczywiœcie. Co siê teraz stanie z Phoenix? W koñcu po³owa miasta trzyma³a siê katedry! Chcemy siê st¹d wydostaæ, znaleŸæ spokojniejsze miejsce do ¿ycia.}
{205} {} {Dobra decyzja. Có¿, powodzenia w poszukiwaniu.}
{206} {} {No có¿, znajdŸcie coœ lepszego i dajcie mi znaæ.}
{207} {} {Serio, sama eksplozja was tak przerazi³a? A mo¿e byliœcie uzale¿nieni od kultu?}
{208} {} {(wymieniaj¹c spojrzenia) To ju¿ nie ma znaczenia... Nasi bliscy krewni byli cz³onkami kultu, dlatego zajmowaliœmy specjalne miejsca w tym mieœcie. Inni patrzyli na nas z zazdroœci¹. Ale teraz nie ma nikogo, kto by nas chroni³, mieszkañcy miasta walcz¹ z kultem. Jeœli zostaniemy, miasto nam nie odpuœci.}
{209} {} {Wygl¹da na to, ¿e naprawdê nie macie wyboru. Powodzenia na drodze.}
{210} {} {Zgadza siê. Wynoœcie siê z Phoenix, aroganckie dranie.}