{100} {} {Widzisz sygnalistê.}
{101} {} {Widzisz jednego z Obserwatorów.}
{102} {} {Co jest? Zagubiony? Wyjœcie jest tam, osoby postronne nie maj¹ tu wstêpu.}
{1102} {} {Co jest? Zagubiona? Wyjœcie jest tam, osoby postronne nie maj¹ tu wstêpu.}
{103} {} {Pozdrowienia, bracie. Niech Swiêty Ogieñ ciê oœwieci.}
{1103} {} {Pozdrowienia siostro. Niech Swiêty Ogieñ ciê oœwieci.}
{104} {} {Gracious Atom... co jest ze mn¹ nie tak?}
{105} {} {...Rozumiem... Swiêty Ogieñ...}
{106} {} {Myœlê, ¿e mam doœæ... Nie kuœ mnie wiêcej, proszê...}
