{100} {} {Widzisz zwolennika ognia.}
{101} {} {Widzisz jednego z Obserwatorów. Szepcze do siebie albo modlitwê, albo jakieœ bzdury.}

{200} {} {Pozdrowienia, nieznajomy.}
{1200} {} {Pozdrowienia, nieznajoma.}
{201} {} {Pozdrowienia, bracie.}
{1201} {} {Pozdrowienia siostro.}
{202} {} {Do widzenia.}
{203} {} {Niech Swiêty Ogieñ ciê oœwieci.}
{204} {} {Uch, tak, oczywiœcie.}

{210} {} {Jak zosta³eœ Obserwatorem?}
{211} {} {By³em tak samo bezwartoœciowy jak ludzie z pustkowi - dba³em tylko o przetrwanie i nie mia³em pojêcia o Swiêtym Ogniu. Zatopiwszy siê na dno i przeœladowany, szuka³em pocieszenia i pewnego dnia trafi³em na tê œwi¹tyniê. Tutaj chroniono mnie i dano mi cel w ¿yciu.}
{212} {} {Co da³a ci wiara?}
{213} {} {Koœció³ dba o swoich wyznawców. Otrzymujemy opiekê medyczn¹, edukacjê i oczywiœcie ochronê przed wrogami.}
{214} {} {A co z innymi? Tymi, którzy s¹ poza koœcio³em?}
{215} {} {Nie mamy zasobów, aby wspieraæ obcych. Dlatego przy wyborze przyjació³ musisz byæ czujny i ostro¿ny.}
{216} {} {Co robisz w katedrze?}
{217} {} {Studiujê nasz¹ doktrynê i modlê siê do Swiêtego Ognia. Ale kiedy bêdê gotowy, czeka mnie wspania³a podró¿ do innych krajów. Bêdê g³osi³ nauki Swiêtego Ognia, aby nasza wiara wzrasta³a na tych upad³ych ziemiach.}
{218} {} {Kto tu rz¹dzi?}
{219} {} {Tu nie ma szefów czy wodzów. Ale naszym przewodnikiem jest Aaron, Pan Phoenix. Znajduje siê w sali tronowej na najwy¿szym piêtrze Katedry.}
{220} {} {Mówi¹, ze niektórzy mnisi s¹ blisko zwi¹zani z czerwonymi kardyna³ami. Co o tym wiesz?}
{221} {} {To mo¿liwe. Jesteœmy gotowi nieœæ S³owo Atomu nawet najbardziej upad³ym duszom.}
{222} {} {Jak znaleŸæ agenta?}
{223} {} {Myœlisz, ¿e wymieniê jego imiê? Nie, nie znam go. Ale ca³a „tajna” korespondencja jest prowadzona przez radiooperatora. Niewielu ma dostêp do takich informacji.}
{224} {} {Rozumiem. Dziêkujê Ci.}
{225} {} {Orris zaraz wszystkiego siê dowie! Jeœli nie pomo¿esz, umrze twój brat.}
{226} {} {Nie mogê w to ingerowaæ. Przepraszam.}
{227} {} {Rozumiem...}
{228} {} {Naprawdê jest tak Ÿle? W takim razie powiedz o tym Murphy'emu. Wie, co robiæ.}
{229} {} {Wiêc to by³ Murphy? Dziêki, to wszystko, czego potrzebowa³em.}
