{100} {} {Widzisz kaznodziejê.}
{101} {} {Widzisz jednego z Wyznawców Ognia. Pilnie odprawia swoj¹ nastêpn¹ Mszê.}
{102} {} {Kaznodzieja jest zbyt zajêty Msz¹ Sw., aby go teraz rozpraszaæ.}

{110} {} {To test Wielkiego Atomu. Zachowajcie spokój.}
{111} {} {Jestem przekonany, ¿e Swiêty Ogieñ wkrótce ponownie rozœwietli nasz¹ katedrê.}
{112} {} {Skoncentrujcie siê na pracy. Ciemnoœæ nie jest dla nas przeszkod¹.}
{113} {} {Spójrz, boisz siê jakiejœ ciemnoœci. I wy nazywacie siebie wierz¹cymi!}

#Prayer (patrz „Hymn to Leibowitz” W. Millera, str. 22)
{120} {} {...Zacznijmy nasz¹ modlitwê, bracia i siostry!}
{121} {} {Chwalcie Swiêty Ogieñ, który oczyœci³ œwiat, aby przywróciæ go do pierwotnej formy.}
{122} {} {Od b³yskawic i burzy, Swiêty Ogniu, wybaw nas.}
{123} {} {Trzêsienia ziemi, Swiêty Ogniu, wybaw nas.}
{124} {} {Od zarazy, g³odu i wojny, Swiêty Ogniu, wybaw nas.}
{125} {} {Z epicentrum i hipocentrum, Swiêty Ogniu, wybaw nas.}
{126} {} {Od deszczu kobaltu, Swiêty Ogniu, wybaw nas.}
{127} {} {Od deszczu strontu, Swiêty Ogniu, wybaw nas.}
{128} {} {Wybaw nas od wytracenia cezu, Swiêtego Ognia.}
{129} {} {Uwolnij nas od kl¹twy promieniowania, Swiêty Ogniu.}
{130} {} {Z koncepcji potworów, Swiêty Ogniu, wybaw nas.}
{131} {} {Uwolnij nas od przekleñstwa mutacji, Swiêty Ogniu.}
{132} {} {My, grzesznicy, b³agamy, wys³uchaj nas.}
{133} {} {Zmi³uj siê nad nami, b³agamy.}
{134} {} {Wybacz nam, b³agamy.}
{135} {} {Pomó¿ nam pokutowaæ, te rogamus, audi nos.}
{136} {} {...Teraz chwila ciszy.}
{137} {} {. ... .}
