{100} {} {Widzisz starego przyjaciela.}
{101} {} {Widzisz jednego z Wyznawców Ognia....}

{200} {} {(To twój stary znajomy, który szpiegowa³ Stra¿ników; wydaje siê przygnêbiony i s³aby, jego oczy wyblak³y, a dawne maniery gangstera wydaj¹ siê nale¿eæ do przesz³oœci)}
{201} {} {Có¿, co za spotkanie...}
{202} {} {(jego matowe oczy podnosz¹ siê ciê¿ko i ledwo ciê rozpoznaj¹) Ty... Pamiêtam ciê. Swiêty Ogieñ musia³ nas zjednoczyæ tamtego dnia. Dziêki tobie jestem wœród Wyznawców. Dziêkujê Ci.}
{203} {} {Uch, proszê. Mi³o jest uczestniczyæ w czyimœ rozwoju osobistym.}
{204} {} {Myœla³em, ¿e nie mo¿esz tego zrobiæ w ten sposób. Tak czy inaczej.}

{210} {} {Muszê siê modliæ. Proszê, zostaw mnie w spokoju.}
{211} {} {Do widzenia.}

{220} {} {Jak wydosta³eœ siê z Tamy?}
{221} {} {Nie pytaj mnie o takie bzdury. Teraz jestem ponad tym.}
{222} {} {Wiêc b¹dŸ sam ze swoimi... modlitwami.}
{223} {} {Jak to jest byæ akolit¹ w Swi¹tyni Ognia?}
{224} {} {Praca i modlitwa. To wszystko, czego potrzebujê. Dopóki nie dojdê do czegoœ wa¿niejszego. Tylko mój mentor mo¿e to ustaliæ.}
{225} {} {Hmm, poka¿ mi swoich uczniów.}
{226} {} {Co to jest? G³upie ¿arty o ch³opach?}
{227} {} {Tak, uh, takie rzeczy.}
{228} {} {Wygl¹da na to, ¿e ciê tu odurzaj¹, co?}
{229} {} {Có¿... Dosta³em kilka tabletek relaksacyjnych na lunch, to czêœæ poœwiêcenia. Musimy oczyœciæ nasze umys³y z arogancji, wiêc mnisi mówi¹... Uff... myœlê, ¿e muszê iœæ do toalety...}
{230} {} {Uch, lepiej ciê zostawiê.}
