{100} {} {Widzisz Matthiasa.}
{101} {} {Widzisz jednego z Obserwatorów. Wygl¹da, jakby zag³êbi³ siê w siebie.}
{102} {} {Podejmij dzia³anie, akolito.}
{103} {} {Ten cz³owiek gorliwie modli siê o zbawienie ca³ej ludzkoœci.}
{104} {} {. ... .}
{105} {} {Koœció³ powróci teraz do swojej pierwotnej misji. Jestem ci na zawsze wdziêczny.}
{106} {} {Wiêc operacja siê nie powiod³a? Ale to jeszcze nie koniec. Dla dobra ca³ego miasta trzeba zabiæ Aarona i jego doradcê.}
{107} {} {Wiêc operacja siê nie powiod³a? Ale to jeszcze nie koniec. Aaron musi zostaæ zabity dla dobra ca³ego miasta.}
{108} {} {Wiêc operacja siê nie powiod³a? Ale to jeszcze nie koniec. Dla dobra ca³ego miasta nale¿y zabiæ doradcê.}

{200} {} {Jak œmiesz odwracaæ moj¹ uwagê od mojej modlitwy? IdŸ st¹d.}
{201} {} {Uch...}

#Zapytania
{210} {} {Proszê, nie odrywaj mnie od mojej modlitwy.}
{211} {} {Cokolwiek powiesz.}
{212} {} {Kim jesteœ?}
{213} {} {Jestem Mathias. Teraz wyjdŸ i zamknij drzwi.}
{214} {} {Ale...}
{215} {} {Co tu robisz Matthias?}
{216} {} {Rozmawiam z tob¹. Robi¹c to, marnujê swój czas. WyjdŸ.}
{217} {} {Czekaj...}
{218} {} {Wydaje mi siê, ¿e nie potrafisz skoncentrowaæ siê na swojej modlitwie.}
{219} {} {Urh... Gdyby tylko ktoœ nie powstrzymywa³ mnie od medytacji, by³oby ³atwiej.}
{220} {} {To w koñcu modlitwy czy medytacji? Wydajesz siê rozkojarzony.}
{221} {} {Hmm. Twoja wytrwa³oœæ jest jak wytrwa³oœæ wszy w starej sutannie. Czego potrzebujesz?}
{222} {} {Chcê porozmawiaæ.}
{223} {} {Nic, nic.}

{230} {} {To g³upie. Jeœli potrzebujesz odpowiedzi, porozmawiaj z kaznodziejami w audytorium na parterze.}
{231} {} {Pójdê ju¿. PA.}
{232} {} {Jasne, bracie Matthias. Przepraszam, ¿e przeszkadzam.}
{233} {} {Gdzie mam siê udaæ, aby znaleŸæ mentora?}
{234} {} {Oczywiœcie nie potrzebujesz tego.}
{235} {} {Zanim zadasz to pytanie, zastanów siê, czy tego potrzebujesz.}

# Rebel Quest
{250} {} {Przychodzê w imieniu Marcosa.}
{1250} {} {Przychodzê w imieniu Marcosa.}
{251} {} {Marcos... Kto to jest?}
{252} {} {Dlaczego powinien by³ siê z tob¹ skontaktowaæ?}
{253} {} {Twoja niepewnoœæ jest jak atomowy jêk w brzuchu grzybowej chmury. WyjdŸ i wróæ tylko wtedy, gdy twoje myœli bêd¹ uporz¹dkowane.}
{254} {} {No dobrze...}
{255} {} {Wiesz, kogo mam na myœli. Ten, który siedzi w metrze i chce siê z tob¹ zemœciæ.}
{256} {} {Tak, oczywiœcie... Zemsta... Pierwotne uczucie istot atomowych, przeci¹gaj¹cych swe nêdzne ¿ycie. Nie wa¿cie siê porównywaæ mnie do was, mieszkañców cuchn¹cych kana³ów. Ca³a moja istota jest uciskana tylko myœl¹ o tym, co Aaron zrobi³ Koœcio³owi Swiêtego Ognia.}
{257} {} {Wiêc jesteœ przeciwko jego zasadom?}
{258} {} {Nie obchodz¹ nas Twoje motywy. Najwa¿niejsze jest to, ¿e mamy jeden cel.}
{259} {} {Wczeœniej koœció³ niós³ œwiat³o przedwojennej m¹droœci do tego zrujnowanego œwiata. Nie braliœmy udzia³u w rozlewie krwi, nasz sztandar nie by³ symbolem tyranii. Ale Aaron sprzeda³ swoj¹ duszê diab³u. Nie mogê ju¿ tego znieœæ.}
{260} {} {Ok. Co mo¿emy zrobiæ, aby to naprawiæ?}
{261} {} {Nie chodzi o pozbycie siê Aarona. W koñcu koœció³ jest teraz znacznie wiêkszy, ni¿ siê wydaje. Jesteœmy po³¹czeni z innymi si³ami w Arizonie, a nasz sztandar kieruje ca³e osady na now¹ œcie¿kê. Nie mo¿esz po prostu wyeliminowaæ jednej osoby, aby zatrzymaæ ca³y proces.}
{262} {} {Co pan proponuje, przeorze Matthias?}
{263} {} {Musimy zniszczyæ ca³y koœció³. Brzmi to szalenie, wiem. Ale jest taka mo¿liwoœæ. Pod katedr¹ znajduj¹ siê podziemne kondygnacje, w których naukowcy od kilku lat tworz¹ now¹ broñ. Mo¿e ona zniszczyæ ca³¹ katedrê.}
{264} {} {Taka potê¿na broñ brzmi niesamowicie. Ale czy nie zaszkodzi to reszcie miasta?}
{265} {} {Koœció³ wyrz¹dzi³ ju¿ zbyt wiele szkód temu delikatnemu œwiatu. Nie martw siê, miasto pozostanie nienaruszone.}
{266} {} {Dlaczego sam tego nie zrobisz?}
{267} {} {Nie wolno mi zejœæ na dó³ bez dobrego powodu po tym, jak raz spróbowa³em. Ale ty masz tê przewagê, ¿e jesteœ nieoczekiwany.}
{268} {} {Prawdopodobnie to niez³y pomys³, ale chcê prze¿yæ.}
{269} {} {ZnajdŸ bezpieczniki w gabinecie profesora. Po aktywacji bêdziesz mieæ kilka minut na ucieczkê z katedry.}
{270} {} {Ok. Ale jak mogê siê tam dostaæ? To obszar zamkniêty.}
{271} {} {Dam ci klucz i szatê Wyznawcy. Przedstaw siê stra¿nikom jako przybysz wys³any w celu z³o¿enia raportu profesorowi.}
{272} {} {Daj mi klucz i szatê. Idê tam w tej chwili.}
{273} {} {Niech Swiêty Ogieñ nam wybaczy. Amen.}
{274} {} {Uh, tak jak mówisz, Przeorze. Zegnam.}

{275} {} {Aaron i jego doradca s¹ dobrze chronieni, ale bêdziesz wystarczaj¹co silny, jeœli bêdziesz dzia³aæ szybko i zdecydowanie. Musisz ich zaskoczyæ w ró¿nych czêœciach katedry, aby nie mogli siê zjednoczyæ. Upewniê siê, ¿e spokojni mnisi nie bêd¹ przeszkadzaæ w twojej walce.}
{276} {} {Swietnie. Dam sygna³ do przodu. W miêdzyczasie ostrze¿ mnichów.}
{277} {} {Ale czy mo¿na obejœæ siê bez rozlewu krwi?}
{278} {} {Niestety, Aaron i jego sojusznicy nie poddadz¹ siê bez walki. Ale jest inna opcja. Pod katedr¹ znajduj¹ siê podziemne kondygnacje, w których Radca od kilku lat tworzy now¹ broñ. Mo¿e zniszczyæ ca³¹ katedrê.}
{279} {} {Co za g³upota. Po prostu przejmiemy koœció³. Dam sygna³ do przodu. W miêdzyczasie ostrze¿ mnichów.}
{280} {} {To szalony plan. Ale to w³aœnie w nim lubiê.}
{281} {} {Jesteœ ostatni¹ nadziej¹ na pokój. Dam ci klucz do piwnicy, w której przebywa Doradca, i dam sygna³ moim podobnie myœl¹cym ludziom, ¿eby ci nie przeszkadzali. Smia³o.}
{282} {} {Swietnie.}

# Wyprawa Aarona
{300} {} {Myœlê, ¿e mamy coœ do omówienia. Dotyczy to niedawnych ataków na mnichów.}
{301} {} {Oczywiœcie zgadujê, ¿e twoje poszukiwania s¹ w impasie, jeœli rozmawiasz o tym z pierwsz¹ osob¹, któr¹ spotykasz.}
{302} {} {Szczerze, tak. Czy mo¿esz mi doradziæ?}
{303} {} {Nie zniechêcaj siê. I uwa¿aj na siebie. Nowicjusze nie s¹ jedynymi ofiarami. Ale tak¿e ci, którzy przeszkadzaj¹ naszym wrogom.}
{304} {} {To ¿adna pomoc.}
{305} {} {Uch, dziêki za "wskazówkê".}

{310} {} {Wrêcz przeciwnie. Z zapisów w bibliotece jasno wynika, ¿e sprawdza³eœ zajêcia nowicjuszy.}
{311} {} {Oczywiœcie. Jako jeden ze stra¿ników œwi¹tyni mam dostêp do tych informacji. A jeœli nie chcesz spaliæ siê na heretyckim stosie, radzê znaleŸæ coœ powa¿niejszego. Teraz zniknij.}
{312} {} {Nie tak szybko. Wiem te¿, ¿e wysy³a³eœ zaszyfrowane wiadomoœci przez radiostacjê.}
{313} {} {Ale...}
{314} {} {W³aœciwie to jest pewien trop. Wys³a³eœ zaszyfrowane wiadomoœci przez radio. Do kogo i dlaczego?}
{315} {} {Jako dozorca œwi¹tyni nie mogê pozwoliæ, aby osoby postronne s³ysza³y moje rozmowy. Ale sk¹d TY masz dostêp do stacji radiowej? To bardzo podejrzane.}
{316} {} {Powinieneœ teraz zaj¹æ siê zapisami bibliotecznymi, z których wynika, ¿e szpiegowa³eœ zaatakowanych nowicjuszy.}
{317} {} {To nie jest to, co myœlisz...}
{318} {} {Mogê przekonaæ Aarona do pe³nego przeszukania twoich rzeczy i kontaktów. Co ty na to?}
{319} {} {Testujesz moj¹ cierpliwoœæ, robaku nuklearny. WyjdŸ.}
{320} {} {Nie pogarszaj sytuacji.}
{321} {} {Ach, œwiête niebiosa! Jesteœ tu od niedawna, a ju¿ badasz to dok³adniej ni¿ naukowcy Vault-Tec.}
{322} {} {Vault... Co?}
{323} {} {Wiêc przyznajesz, ¿e ujawni³eœ informacje wrogom koœcio³a?}
{324} {} {Nie tutaj. Jeœli potrzebujesz odpowiedzi na swoje pytania, udzielê ich w bardziej wygodnym do tego miejscu. Spotkaj siê ze mn¹ w konfesjonale na pierwszym piêtrze. Nie martw siê, moje nogi ju¿ od dawna nie s¹ zdolne do ucieczek.}
{325} {} {Ok. Ale nie próbuj ¿adnych numerów.}
{326} {} {Oczywiœcie, œciany mog¹ mieæ tu uszy.}

# Dialog w konfesjonale
{330} {} {Muszê przyznaæ, ¿e nie spodziewa³em siê, ¿e nowicjusz z pustkowi bêdzie w stanie rozwik³aæ tê sprawê. Uda³o mi siê ukryæ swoje czyny nawet przed Aaronem. Uwa¿aj...}
{331} {} {Ale dlaczego ty, s³uga Aarona, pomagasz jego wrogom?}
{332} {} {Pod przywództwem Aarona koœció³ zmieni³ swoje przekonania. Bastion œwiêtoœci i m¹droœci sta³ siê sk³adnic¹ grzechu. Nie mogê d³u¿ej na to patrzeæ.}
{333} {} {Opowiedz mi tê historiê.}
{334} {} {Dziesiêæ lat temu byliœmy spokojnym koœcio³em z dala od ludzi. Zachowaliœmy przedwojenne relikwie i wiedzê, aby przekazaæ je tym, którzy byliby godni ich otrzymania.}
{335} {} {NajwyraŸniej trafi³a siê taka osoba, tak?}
{336} {} {Przybyli ludzie z po³udnia. Zwabili naszych przeorów na swoj¹ stronê i z pomoc¹ koœcio³a zorganizowali rewolucjê w mieœcie. Aaron zosta³ Lordem Phoenix, chocia¿ wczeœniej by³ tylko kap³anem œredniego stopnia.}
{337} {} {I nie jesteœ z tego zadowolony?}
{338} {} {Nasz¹ misj¹ by³a ochrona staro¿ytnej wiedzy. Powinniœmy byli bardziej uwa¿aæ z kim siê ni¹ dzielimy. Zrobiliœmy straszny b³¹d, który doprowadzi nas wszystkich do piekie³ atomowych.}
{339} {} {Kim s¹ ludzie, którzy atakuj¹ akolitów?}
{340} {} {Kim s¹ osoby, którym pomagasz?}
{341} {} {To d³uga historia. Od czasu rewolucji w Phoenix istnieje oddzia³ buntowników, którzy nazywaj¹ siebie „Parti¹ Wyzwolenia”. Do tej pory starali siê nie wychylaæ, aby zebraæ si³y i nieoczekiwanie obaliæ Aarona. Chocia¿ nie zgadzam siê z nimi we wszystkim, mieliœmy porozumienie co do wycofania koœcio³a z miasta.}
{342} {} {A teraz wyjaœnij, dlaczego nie powinienem niweczyæ twoich planów?}
{1342} {} {A teraz wyjaœnij, dlaczego nie powinnam niweczyæ twoich planów?}
{343} {} {Ale dlaczego ty, przeorze katedry, pomagasz jego wrogom?}
{344} {} {Nie obchodzi mnie, co ciê napêdza. Po prostu powiedz mi, dlaczego mia³bym zostawiæ sprawê otwart¹?}
{345} {} {Wczeœniej czy póŸniej Aaron odkryje Ÿród³o wycieku informacji. Martwi mnie jednak nie moja cielesna forma, ale misja koœcio³a.}
{346} {} {Czy chcesz mnie zwabiæ na swoj¹ stronê?}
{347} {} {Najpierw proponujê spotkaæ siê z rebeliantami i omówiæ wszystko twarz¹ w twarz.}
{348} {} {To g³upie. Powiem wszystko Aaronowi.}
{349} {} {Wiêc nie zostawiasz mi wyboru. Niech Swiêty Ogieñ nam wybaczy...}
{350} {} {Uch...}
{351} {} {Ok, zgadzam siê. Ciekawie bêdzie us³yszeæ drug¹ stronê konfliktu.}
{1351} {} {Ok, zgadzam siê. Ciekawie bêdzie us³yszeæ drug¹ stronê konfliktu.}
{352} {} {Niech tak bêdzie. ZnajdŸ Sztab Generalny Partii pod posterunkiem Unii. Mo¿esz siê tam dostaæ tylko przez kana³y. Powiedz, ¿e jesteœ ode mnie, a ja tymczasem spróbujê ich ostrzec. Powodzenia.}
{353} {} {Do zobaczenia przeorze Matthias.}
{354} {} {Zmieni³em zdanie. Powiem wszystko Aaronowi.}
{1354} {} {Zmieni³am zdanie. Powiem wszystko Aaronowi.}
{355} {} {Podejmij dzia³anie, akolito.}
{356} {} {Dobrze.}
{357} {} {Muszê wiedzieæ, którzy kardyna³owie ujawniaj¹ ci informacje o gangu.}
{358} {} {Co za wynios³e pytanie? Gdybym wiedzia³, i tak nie powiedzia³bym ci.}
{359} {} {Ale zaprzeczasz ¿e tak siê dzieje, prawda? }
{360} {} {Mamy szpiegów w ca³ym mieœcie. A informacje otrzymujemy od nich na najró¿niejsze sposoby. Nie jest to nic zaskakuj¹cego.}
{361} {} {Nie mam dalszych pytañ.}
{362} {} {Mogê ci ufaæ, prawda? Murphy jest jednym z nas. Zinfiltrowa³ szeregi gangu, aby skierowaæ tych nieszczêsnych g³upców we w³aœciwym kierunku.}
{363} {} {Dobrze, ¿e mnie ostrzeg³eœ. Dziêkujê Ci.}