{100} {} {Widzisz delegata.}
{101} {} {Widziesz obcego kultystê. Wœród murów katedry wygl¹da jak prawdziwy dzikus.}

{200} {} {Hej, ty. Przynieœ mi swoje owoce, jestem g³odny.}
{201} {} {Dlaczego mia³bym przynosiæ ci jedzenie?}
{202} {} {Och, nie jesteœ Obserwatorem? Wiêc odsuñ siê, nie obchodzisz mnie. Tylko Koœció³ Ognia zas³uguje na moj¹ czeœæ. S¹ przysz³oœci¹ tych ziem, reszta to zwyk³e œmiecie.}
{203} {} {Kim jesteœ?}
{204} {} {Jestem wodzem wschodniego plemienia. Zawieramy sojusz z Wyznawcami i chcemy staæ siê czêœci¹ tego wielkiego narodu.}
{205} {} {Sojusz miêdzy sekt¹ a dzikusami? Dlaczego niby koœció³ tego potrzebuje?}
{206} {} {Koœció³ dba o ludzi z pustkowi. Pierwszy raz w tym mieœcie? Zobacz, ile korzyœci przyniós³ tym ziemiom Koœció³ Swiêtego Ognia. Wyznawcy podbili S³oñce i uwiêzili je w patykach i lampach, czy nie jest to wyznacznikiem ich wielkoœci, ich boskiej mocy?}
{207} {} {Czy rozumiesz cokolwiek z ich nauk?}
{208} {} {Szczerze mówi¹c, niewiele. Ale Wyznawcy obiecali nas nauczaæ. Otworz¹ swoj¹ œwi¹tyniê w naszej dolinie, naucz¹ nas rozumieæ jêzyk Staro¿ytnych, a nawet podbijaæ S³oñce. Có¿, to w³aœnie nam obiecali.}
{209} {} {I w zamian?}
{210} {} {Zostaniemy ministrami - to zaszczytny tytu³ dla plemienia! Bêdziemy pracowaæ dla dobra koœcio³a, a koœció³ nam pomo¿e. W ten sposób nie tylko siê uratujemy, ale tak¿e staniemy siê lepsi, m¹drzejsi i silniejsi.}
{211} {} {Rozumiem. A wiêc do zobaczenia.}
{212} {} {Znowu ty? OdejdŸ, rozmawiam tylko z Aaronem.}
