{100} {} {Widzisz Marcosa.}
{101} {} {Widzisz Marcosa.}
{102} {} {Ten dzieñ przejdzie do historii.}

{200} {} {Co mówi Matthias? Pomo¿e nam?}
{201} {} {Nie mog³em jeszcze z nim porozmawiaæ. Poczekaj chwilê.}
{202} {} {Matthias obieca³ pomóc. Mo¿esz rozpocz¹æ operacjê.}
{203} {} {Wiêc zaczynajmy! Naszym celem jest Aaron i jego doradca. Reszta nie powinna byæ rozpraszana.}
{204} {} {Tak!}
{205} {} {On, uh, nie pomo¿e nam. Bêdziemy musieli to zrobiæ sami.}
{206} {} {Cholera. Myœla³em, ze jest z nami.}
{207} {} {Wiesz, ja te¿ mam to uczucie. Spróbujê go ponownie przekonaæ...}
{208} {} {Myœlê, ze nie powinieneœ mu ufaæ. Dzia³aj bez niego.}
{209} {} {Matthias nie ¿yje. Raczej nam nie pomo¿e.}

{210} {} {Wróæ do innych w katedrze. Naszym celem jest Aaron i jego doradca. Reszta nie powinna byæ rozpraszana.}
{211} {} {Dobrze.}
{212} {} {Aaron i doradca nie ¿yj¹.}
{213} {} {Wspania³a wiadomoœæ! Ten dzieñ przejdzie do historii jako dzieñ wyzwolenia Phoenix. Dziêkujê, guerrero.}
{214} {} {Mam nadziejê, ¿e wy bêdziecie sprawiedliwsi. Do widzenia, Marcos.}
