{100} {} {Widzisz zwolennika ognia.}
{101} {} {Widzisz jednego z Obserwatorów. Ca³kowicie zamkn¹³ siê w sobie poprzez gor¹czkow¹ modlitwê.}

{200} {} {...Niebo stanie siê ziemi¹... Ogieñ jest Bogiem... I powiedzia³, ¿e by³ ¿a³osny przed Swoj¹ twarz¹... Ogieñ... Niewierni upadn¹... S³oñce jest w naszych rêkach... Kwiaty...}
{201} {} {Hej, co tam mamroczesz?}
{202} {} {...Ogieñ to potêga...}
{203} {} {Twój ogieñ to tylko mityczny obraz.}
{204} {} {(odrywa siê od modlitwy i bezmyœlnie wpatruje siê w ciebie) Ogieñ... Jest... Prawd¹...}
{205} {} {No có¿, to wszystko wyjaœnia, pa.}
{206} {} {Uch, lepiej mu nie przeszkadzaæ...}
