{100} {} {Widzisz dziecko.}
{101} {} {Widzisz zwyk³ego dzieciaka z miasta w ³achmanach.}
{102} {} {Uch, muszê iœæ.}

{200} {} {Przepraszam pana!}
{1200} {} {Przepraszam pani¹!}
{201} {} {Nie mam czasu dla ¿ebraków. OdejdŸ.}
{202} {} {Czego chcesz, dzieciaku?}
{203} {} {Poproszono mnie, ¿eby ci to daæ. (wyci¹ga notatkê)}
{204} {} {Jeœli to jakieœ oszustwo, s³ono za to zap³acisz.}
{205} {} {Dziêki m³ody, to bardzo mi³o z twojej strony.}
{206} {} {ChodŸ tutaj.}
{207} {} {(Po przekazaniu notatki dziecko natychmiast ucieka. Po roz³o¿eniu kartki, czytasz: „Kultyœci dostali to, na co zas³u¿yli. Przerwij œledztwo, inaczej czeka ciê ten sam los.”)}
{208} {} {Jeœli napisa³ to ten m³odzieniec, to pozostaje mi dr¿eæ ze strachu.}
{209} {} {Wygl¹da na to, ¿e za atakami nie stoj¹ zwykli bandyci.}
