{100} {} {Widzisz zwolennika ognia.}
{101} {} {Widzisz jednego z Obserwatorów. Szepcze do siebie albo modlitwê, albo jakieœ bzdury.}
{102} {} {Jego Wysokoœæ Aaron czeka na ciebie.}
{103} {} {W³adca Phoenix czeka na ciebie.}

{110} {} {* Nies³yszalne mamrotanie *}
{111} {} {Czy chcia³byœ do³aczyæ do Koœcio³a Ognia?}
{112} {} {Ignorant, który nie zna ognia, zginie w jego p³omieniu.}
{113} {} {Swiêty Ogieñ ukara³ przodków za ich grzechy.}
{114} {} {Wiara w ogieñ to jedyny sposób na ocalenie cia³a i duszy.}
{115} {} {Pozdrowienia, bracie.}
{116} {} {Ciebie te¿ oœwieci³ Swiêty Ogieñ?}
{117} {} {Wkrótce Swiêty Ogieñ oœwieci ca³¹ Sonorê.}
{118} {} {Wszyscy wyszliœmy z tego samego protop³omienia.}
{119} {} {Byæ oœwieconym to oœwiecaæ innych.}

{1114} {} {Wiara w ogieñ to jedyny sposób na ocalenie cia³a i duszy.}
{1115} {} {Pozdrowienia siostro.}
{1116} {} {Ciebie te¿ oœwieci³ Swiêty Ogieñ?}
{1117} {} {Wkrótce Swiêty Ogieñ oœwieci ca³¹ Sonorê.}
{1118} {} {Wszyscy wyszliœmy z tego samego protop³omienia.}
{1119} {} {Byæ oœwieconym to oœwiecaæ innych.}
