{100} {} {Widzisz w³óczêge.}
{101} {} {Widzisz w³óczêgê, b³¹ka siê bez celu po placu.}
{102} {} {Widzisz niedo¿ywionego w³óczêgê, aktywnie intonuje coœ na czeœæ koœcio³a.}
{103} {} {Widzisz w³óczêgê, ledwo mo¿e poruszaæ siê po placu.}
{104} {} {Widzisz uchodŸcê, b³¹ka siê bez celu po placu.}

# Plywajace repliki
# - zebrak
{110} {} {Zostaw mnie.}
{111} {} {Nie wiem, co robiæ.}
{112} {} {Nic tak nie b³yszczy w mieœcie jak ja.}
{113} {} {Po³o¿ê siê tutaj... masz coœ przeciwko?}
{114} {} {Chcê rzuciæ to uliczne ¿ycie, ale nie mogê.}
{115} {} {Phoenix kwitnie, a ja spadam dalej.}
{116} {} {Masz coœ do jedzenia dla biednego brata z ulicy?}
{117} {} {Po¿ycz kilka kapsli, dam ci spokój, serio.}
{118} {} {Naprawdê potrzebujê lekarstwa dla dziecka. Pomó¿ mi, co?}
{119} {} {Umieram z g³odu, daj mi chocia¿ szczurzy ogon.}
{120} {} {Chcesz do nas do³aczyæ? Przykro mi, ale ta dzielnica nie pomieœci nas tak wielu.}
{121} {} {Czekam, a¿ fanatycy przynios¹ nam darmowe jedzenie.}
{122} {} {Katedra czasami rozdaje resztki po obiedzie.}
{123} {} {Kiedy dadz¹ nam jeœæ, poca³uj ksiêdza w stopy.}
{124} {} {Chwalcie ogieñ! Wszyscy ludzie s¹ braæmi! Widzisz, ja te¿ jestem wierz¹cy.}

# - biegly
{130} {} {Chcê zostaæ nowicjuszem, ale nie jestem jeszcze godny.}
{131} {} {Mówiê ci, zostanê nowicjuszem!}
{132} {} {Bêdziesz musia³ du¿o siê modliæ, aby zostaæ przyjêty do zakonu.}
{133} {} {Pokój! Mi³oœæ! Swiêty ogieñ!}
{134} {} {Czy ty te¿ w coœ wierzysz?}
{135} {} {W co wierzysz?}
{136} {} {Witaj Swiêty Ogniu!}
{137} {} {Hail Phoenix! Hail, Aaron!}
{138} {} {Kocham Aarona! Witaj Aaronie, W³adco Phoenix!}
{139} {} {Moje ¿ycie nale¿y do Swiêtego Aarona.}

# - chory lub niepelnosprawny
{150} {} {Jestem tutaj, aby prosiæ o uzdrowienie z choroby.}
{151} {} {Nie ma ucieczki od mojej choroby, ale mimo to mnisi obiecali pomóc.}
{152} {} {Mówi siê, ¿e mnisi znaj¹ staro¿ytny obrzêd uzdrawiania.}
{153} {} {Codziennie modlê siê do Aarona, aby wyleczy³ moje wrzody.}
{154} {} {Da³em wszystkie swoje oszczêdnoœci na koœció³, a mimo to moja dolegliwoœæ nigdy nie zosta³a wyleczona.}
{155} {} {Mnisi lecz¹ mnie modlitwami. Ju¿ czujê przyp³yw energii! O tak...}
{156} {} {Mnisi mówi¹, ¿e muszê oczyœciæ swoj¹ duszê. I w tym celu muszê oddaæ wszystko koœcio³owi.}
{157} {} {Jestem taki bezwartoœciowy, co?}
{158} {} {Proszê Obserwatorów o pomoc.}
{159} {} {Tylko Wyznawcy Ognia potrafi¹ leczyæ tak jak przed Wielk¹ Wojn¹.}

# - uchodŸca
{170} {} {Jestem tutaj, aby znaleŸæ schronienie u Wyznawców Ognia.}
{171} {} {Powiedziano mi, ¿e koœció³ przyjmuje uchodŸców, ale tak nie jest.}
{172} {} {Uciekliœmy przed bandytami, ale koœció³ nas nie chce przyj¹æ.}
{173} {} {Wyznawcy ognia pomagaj¹ uchodŸcom.}
{174} {} {Mnisi tutaj s¹ niezwykle pulchni. Prawdopodobnie s¹ na coœ chorzy.}
{175} {} {Tylko w pobli¿u œwi¹tyni czujê siê bezpiecznie.}
{176} {} {Oni s¹ dziwni - ci czciciele ognia.}
{177} {} {Ci fanatycy obiecuj¹ raj na ziemi.}
{178} {} {Mówi¹, ¿e powinniœmy siê baæ, ale nie rozumiem, czego ani kogo.}
{179} {} {Lepiej dawaj jedzenie, ka¿dy powinien siê dzieliæ.}