{100} {} {Widzisz adepta.}
{101} {} {Widzisz jednego z Wyznawców Ognia. Skanduje coœ szalonego, aby zwróciæ na siebie uwagê.}

# Plywajace repliki
{110} {} {Bój siê œwiêtego ognia!}
{111} {} {Bój siê kary Ognistych Niebios!}
{112} {} {Pan jest potêg¹ rozszczepienia j¹drowego!}
{113} {} {Wszyscy, wszyscy, musimy pokutowaæ!}
{114} {} {Kto? Kto odwa¿y siê sprzeciwiæ g³osu naszego Pana?}
{115} {} {Sceptycy! Sceptycy upadn¹ jako pierwsi!}
{116} {} {Ci ludzie oddali swoje dusze Nuklearnemu Diab³u!}
{117} {} {S³uchajcie, s³uchajcie miesz.. ofiary promieniowania i spustoszenia!}
{118} {} {Upadli przez swoje brudne myœli!}
{119} {} {Czcij swojego ojca Aarona, Pana Phoenix, bo to On daje ¿ycie tej pustyni!}
{120} {} {Nadchodzi nowa era!}
{121} {} {Tylko g³upiec oprze siê postêpowi!}

# Pierwszy dialog
{200} {} {PodejdŸ bli¿ej, dziecko Promieniowania i Spustoszenia. Ka¿dy powinien zobaczyæ, ¿e zwyciê¿a sprawiedliwoœæ. Nikt nie uniknie kary nieba!}
{201} {} {Chwileczkê, proszê pana, co siê tu dzieje?}
{202} {} {My, wierni Swiêtego Ognia, od lat ukrywaliœmy siê przed zwyk³ymi ludŸmi. Poniewa¿ ich serca i umys³y nie mog³y przyswoiæ prostych prawd. Wypêdzali nas, bili i zabijali! Ale cierpliwie czekaliœmy na odpowiedni¹ godzinê.}
{203} {} {[Dalej.]}
{204} {} {Hej, wariacie w ³achmanach, dlaczego to robisz?}
{205} {} {To jest to! Nietolerancja! Wulgarny jêzyk! My, s³udzy Swiêtego Ognia, przez lata ukrywaliœmy siê przed zwyk³ymi ludŸmi. Poniewa¿ ich serca i umys³y nie mog³y przyswoiæ prostych prawd. Wypêdzali nas, bili i zabijali! Ale cierpliwie czekaliœmy na odpowiedni¹ godzinê.}
{206} {} {Godzinê, w której Pan znudzi siê ludzk¹ g³upot¹ i da nam pokój. Ci ludzie, których cia³a sta³y siê repozytoriami diab³a nuklearnego, s¹ tego dowodem. Przez wiele lat stosowali swoje okrucieñstwa wobec koœcio³a. Okradali i zabijali naszych mnichów, którzy nios¹ jasn¹ prawdê ca³emu œwiatu. Niewdziêczni! Sp³on¹ w piekielnym p³omieniu nuklearnym!}
{207} {} {Co za horror. Te dranie z pewnoœci¹ dosta³y to, na co zas³u¿y³y.}
{208} {} {Niech Swiêty Ogieñ bêdzie z tob¹! IdŸ w pokoju i powiedz zwyk³ym ludziom o przeœladowaniach pokojowego koœcio³a.}
{209} {} {Niewa¿ne. Po tym, co us³ysza³em, nie da siê pogodziæ z tak¹ niesprawiedliwoœci¹.}
{210} {} {Nie musisz od razu robiæ ze mnie agitatora. Po prostu zajmê siê swoimi sprawami.}
{211} {} {Jak dot¹d s³yszê tylko jedn¹ stronê konfliktu. Drugiej oczywiœcie nie us³yszê.}
{212} {} {Sceptycy! Czy zrobiliœmy tak ma³o dla miasta? Zobacz, jak rozkwit³o Phoenix, gdy otrzyma³o m¹droœæ w³adcy Aarona. IdŸ i pomyœl o tym. I bój siê Swiêtego Ognia! Bój siê ognia!}
{213} {} {Przepraszam, to mój pierwszy raz tutaj i niewiele jeszcze wiem. Na pewno przyjrzê siê bli¿ej Twojemu koœcio³owi.}
{214} {} {Cz³owieku, po tym, co widzia³em, twoja mowa wygl¹da na bardzo w¹tpliw¹. Sam zdecydujê, jak bêdê traktowaæ Twój koœció³.}

{220} {} {Pozdrowienia bracie. Cieszê siê, ¿e widzê Twoje objawienie z naszego ostatniego spotkania. Pamiêtam, ¿e by³eœ sceptykiem i spojrza³eœ na mnie z wrogoœci¹. Teraz wyci¹gnê do ciebie rêkê i powiem crede firmiter et pecca fortiter.}
{1220} {} {Pozdrowienia siostro. Cieszê siê, ¿e widzê Twoje objawienie z naszego ostatniego spotkania. Pamiêtam, ¿e by³aœ sceptykiem i spojrza³aœ na mnie z wrogoœci¹. Teraz wyci¹gnê do ciebie rêkê i powiem crede firmiter et pecca fortiter.}
{221} {} {Pozdrowienia bracie. Cieszê siê, ¿e ty te¿ jesteœ w naszych szeregach. To wielki zaszczyt i odpowiedzialnoœæ. Crede firmiter et pecca fortiter.}
{1221} {} {Pozdrowienia siostro. Cieszê siê, ¿e ty te¿ jesteœ w naszych szeregach. To wielki zaszczyt i odpowiedzialnoœæ. Crede firmiter et pecca fortiter.}
{222} {} {Teraz, jeœli nie masz nic przeciwko, chcia³bym z tob¹ porozmawiaæ.}
{223} {} {Crede firi... Co? Wci¹¿ daleko mi do tych œwietych tekstów. Do zobaczenia.}

# Powtarzajacy siê dialog
{250} {} {Widzê, ¿e przeœladuje ciê rozmowa o Swiêtym Ogniu, tak? Wiêc co chcesz wiedzieæ tym razem?}
{251} {} {Jeszcze raz ty, s³ugo Nuklearnego Diab³a, przyjdŸ mnie przetestowaæ.}
{252} {} {Pozdrowienia bracie. Czy wszystko z tob¹ w porz¹dku? Czy zwykli ludzie ci nie przeszkadzaj¹?}
{1252} {} {Pozdrowienia siostro. Czy wszystko z tob¹ w porz¹dku? Czy zwykli ludzie ci nie przeszkadzaj¹?}
{253} {} {Chyba ju¿ pójdê.}

{260} {} {Kim jesteœ?}
{261} {} {Chcia³bym ciê lepiej poznaæ.}
{262} {} {Jestem duchownym i pokornym s³ug¹ Aarona, Pana Phoenix. Mam na imiê Gabriel.}
{263} {} {W¹tpiê, ¿eby to by³o twoje prawdziwe imiê.}
{264} {} {Wiêc porozmawialiœmy. Do zobaczenia.}
{265} {} {Jaki rodzaj religii reprezentujesz, Gabriel?}
{266} {} {Prawda. Po rekrutacji zmieniamy nasze imiona, tym samym k³ad¹c kres dotychczasowemu ¿yciu.}
{267} {} {}
{268} {} {Swoj¹ drog¹, czy mo¿esz mi pomóc zrozumieæ nasz¹ wiarê?}
{269} {} {Po tym, co us³ysza³em, chcia³em lepiej poznaæ twoj¹ wiarê.}
{270} {} {Opowiedz mi o religii, któr¹ reprezentujesz.}
{271} {} {Czy mogê omówiæ z tob¹ nasz¹ wiarê?}
{272} {} {Koœció³ Swiêtego Ognia znajduje siê na pó³noc od miasta. IdŸ g³ówn¹ ulic¹, sama droga zaprowadzi Ciê do katedry. Lepiej jest uczyæ siê wiary z kazañ ni¿ ode mnie.}
{273} {} {Kim jesteœ?}
{274} {} {Tania sztuczka, kultysto. Nie uda ci siê mnie tak ³atwo oszukaæ.}
{275} {} {Dobrze, pójdê tam.}
{276} {} {Czy twój koœció³ jest tak potê¿ny, ¿e a¿ organizujecie publiczne egzekucje?}
{277} {} {Nie, nie, egzekucje przeprowadzi³y inne osoby, ale pod naszym nadzorem. A jednak ca³e miasto ma d³ug wobec koœcio³a. Obowi¹zkowy za wodê, pr¹d, spokój i porz¹dek. Wkrótce zobaczysz to wszystko na w³asne oczy, dziecko Promieniowania i Spustoszenia.}
{278} {} {Jasne, jasne, pójdê i zobaczê, czy aby nie k³amiesz.}
{279} {} {W takim razie muszê koniecznie zwiedziæ miasto. Bywaj.}
{280} {} {Wybacz mi z³y humor, ale takie kwestie nie s¹ omawiane na ulicy. I nie nape³niajcie g³owy sceptycyzmem, aby Diabe³ J¹drowy nie wnika³ w dusze m³odych mnichów. Bój siê Swiêtego Ognia, nowicjuszu, bój siê Ognia!}
{281} {} {NajwyraŸniej bêdê musia³ porozmawiaæ z wyznawcami w katedrze. Do zobaczenia.}
{282} {} {Co wtedy robisz?}
{283} {} {Swoj¹ drog¹, za co zostali ukarani ci nieszczêœnicy?}
{284} {} {Ci ludzie za tob¹ siê nie bali. Dlaczego zostali straceni?}
{285} {} {Za co ukarani s¹ ci ludzie?}
{286} {} {G³upcy, ulegli pokusom Diab³a Nuklearnego. Niektórzy z nich rozpowszechniali fa³szywe pog³oski o naszym koœciele i jego przywódcy Aaronie, niech bêdzie On s³awny po wieki wieków. Inni zostali ukarani za okradanie naszych mnichów lub samego koœcio³a. Odt¹d ich dusze nie spoczn¹ nawet w nuklearnym piekle.}
{287} {} {Nie s¹dzisz, ¿e to zbyt... surowa kara?}
{288} {} {Dostali to, na co zas³u¿yli. Teraz bêdê bardziej ostro¿ny. Bywaj.}
{289} {} {Religijna egzekucja? Lepiej wydostanê siê st¹d, zanim mnie te¿ tak za³atwi¹.}
{290} {} {Kim jesteœ, aby nadzorowaæ te egzekucje?}
{291} {} {Co wiesz o buntownikach walcz¹cych z koœcio³em?}
{292} {} {Heretycy i tchórze! Ach, JESLI znajdziemy po³o¿enie ich kwatery g³ównej, wszyscy sp³on¹ w ogniu kary.}
{293} {} {Rozumiem. Nie wiem nic na ten temat. Zapytam innych.}

#Zadanie
{300} {} {Prowadzê œledztwo w sprawie ataku na mnichów na proœbê Aarona. Co mo¿esz mi o tym powiedzieæ?}
{301} {} {Opowiedz mi jeszcze raz o ataku na Obserwatorów.}
{302} {} {Obserwatorzy czêsto byli celem grabie¿y lub oœmieszania. Kiedy Aaron doszed³ do w³adzy, niech Jego imiê bêdzie s³awne, ka¿dy bandyta w mieœcie zacz¹³ nas omijaæ. Jednak ostatnio ataki zosta³y wznowione.}
{303} {} {[Dalej.]}
{304} {} {Strzelanina podczas egzekucji, morderstwa w slumsach i napady na kasyno to jedne z najbardziej odwa¿nych przestêpstw pope³nionych na naszych braciach w ostatnim czasie.}
{305} {} {Dziêki, wystarczy.}

{310} {} {Opowiedz mi o strzelaninie podczas egzekucji.}
{311} {} {Strzelali z dachu tych ruin, kiedy przeprowadzalismy egzekucje. Strzelców by³o kilku, strzelali krzy¿owo i wyraŸnie celowali we mnie. Byæ mo¿e w ten sposób zwolennicy przestêpców próbowali ratowaæ swoich wspólników, ale z woli Oka Phoenix zawiedli.}
{312} {} {W pobli¿u kasyna tak¿e dosz³o do strzelaniny?}
{313} {} {Ignoranccy bandyci strzelali do naszych braci przed kasynem jak do kretoszczurów na ranczo. Trudno powiedzieæ, co siê naprawdê wydarzy³o, bo wszyscy ludzie mówi¹ co innego.}
{314} {} {A co z incydentem w slumsach?}
{315} {} {Bardzo mroczna sprawa. Nasi nowicjusze przybyli do slumsów, aby chwaliæ Aarona i poprosiæ o darowizny dla œwi¹tyni. Wkrótce potem znaleziono ich wisz¹cych na latarniach. Oczywiœcie miejscowi nie chc¹ nic powiedzieæ, nikt niczego nie widzia³. Módlmy siê wiêc za dusze naszych braci.}
{316} {} {Czy masz jakieœ wskazówki dotycz¹ce tych ataków?}
{317} {} {Myœlisz, ¿e sam Aaron powierzy³by ci tê sprawê, gdyby nie by³o tak ciemno? Zapytaj ludzi w kasynach i slumsach, mo¿e bêd¹ ci bardziej ufaæ. W koñcu wielu Obserwatorów jest znanych z widzenia, a ty jesteœ tu now¹ osob¹.}