{100} {} {Widzisz brata Franciszka.}
{101} {} {Widzisz jednego z Obserwatorów. Jest zajêty kopiowaniem staro¿ytnych planów.}
{102} {} {Jak mam skopiowaæ plany w takich ciemnosciach?}

{200} {} {Pozdrowienia, nieznajomy. Czy mogê Ci w czymœ pomóc?}
{1200} {} {Pozdrowienia, nieznajoma. Czy mogê Ci w czymœ pomóc?}
{201} {} {Najpierw opowiedz mi o tym miejscu.}
{202} {} {Bardzo w to w¹tpiê. Co mo¿esz dla mnie zrobiæ?}
{203} {} {Proszê. Nie ma tu miejsca na chamstwo.}
{204} {} {Przepraszam, jestem dzisiaj nie w nastroju. Wiêc co to za miejsce?}
{205} {} {Wychodzê. Ale nadal bêdziesz o mnie s³yszeæ.}

{210} {} {Czego chcesz, nieznajomy?}
{1210} {} {Czego chcesz, nieznajoma?}
{211} {} {Jak mogê ci pomóc, akolito?}
{1211} {} {Jak mogê ci pomóc, nowicjuszu?}
{212} {} {Do widzenia.}
{213} {} {Du¿o wiesz. Powiesz mi coœ innego?}

#Zapytania
{220} {} {Opowiedz mi o sobie.}
{221} {} {Nazywam siê Franciszek i jestem ksiêgowym.}
{222} {} {Jak zosta³eœ Obserwatorem?}
{223} {} {Jestem zwolennikiem odk¹d by³em nastolatkiem. Wtedy koœció³ by³ ma³o znany i nie uczestniczy³ w losach miasta.}
{224} {} {I œlepo wierzysz w wiarê twojego koœcio³a?}
{225} {} {"Nisi videro, non credam. Non credam, nisi videro". Nie ma sensu o tym dyskutowaæ.}
{226} {} {Co dok³adnie robisz, ksiêgowy?}
{227} {} {Przywracam do ¿ycia stare ksiêgi, kopiujê stare pisma œwiêtych, robiê listy. Na przyk³ad jestem obecnie zajêty tym wspania³ym rysunkiem.}
{228} {} {Po co kopiowaæ stare pisma?}
{229} {} {Musimy zachowaæ wiedzê naszych nieskoñczenie m¹drych przodków dla potomnoœci. Ale papier dawnych pism jest zazwyczaj prawie ca³kowicie zniszczony, takie teksty nie przetrwaj¹ d³ugo, zw³aszcza na œwie¿ym powietrzu. Dlatego przywracamy, kopiujemy, a nastêpnie zachowujemy stare pisma œwiête.}
{230} {} {Ale jeœli zostan¹ zniszczone, stan¹ siê niedostêpne, prawda?}
{231} {} {Tak. Dlatego robimy kopie, które s¹ przechowywane w naszej bibliotece. To prawda, ¿e czêsto s¹ gorszej jakoœci od orygina³u, ale trzeba to robiæ.}

{240} {} {Co to za miejsce?}
{241} {} {To jest biblioteka. Miejsce, w którym przechowywane s¹ papierowe Ÿród³a wiedzy... g³ównie przedwojenne. Rozumiem, ¿e wygl¹da to trochê dziwnie, poniewa¿ na œwiecie nie ma ani jednej biblioteki. Ale tym cenniejsza jest nasza praca.}
{242} {} {Sk¹d siê tu wziê³y te wszystkie ksi¹¿ki?}
{243} {} {Zewsz¹d. Sami kupujemy wszystkie przedwojenne ksi¹¿ki i rêkopisy. Czêœæ tej kolekcji przysz³a do nas od poprzedników, którzy zakopali je na pustyni.}
{244} {} {Ale po co nam te stare ksi¹¿ki?}
{245} {} {Posiadaj¹ wiedzê naszych przodków. Niestety wiêkszoœci z nich nie jesteœmy w stanie zrozumieæ. Ale pewnego dnia nadejdzie czas, kiedy te ksi¹¿ki ujawni¹ nam swoje sekrety.}
{246} {} {Uwa¿asz, ¿e ta wiedza jest bezpieczna? Czy aby nasi przodkowie nie zniszczyli siê przy jej pomocy?}
{247} {} {Tak. Ale ludzie ucz¹ siê na starych b³êdach. Ponadto dzielimy siê wiedz¹ tylko z tymi, którzy na to zas³uguj¹.}
{248} {} {Pochowane na pustyni? Jak to?}
{249} {} {Po Wielkiej Wojnie naukowcy byli traktowani z wielkim brakiem szacunku. Uznano ich nawet za sprawców Apokalipsy, a na stosie palono ksi¹¿ki naukowe. Tak przynajmniej mówi¹ kroniki. Dlatego nasi poprzednicy schowali ksi¹¿ki w beczkach i zakopali na pustyni. Nadal nie znaleŸliœmy wielu z nich.}

{250} {} {O planie. Powiedz mi, co oznacza „blok transformatora 6-B”?}
{251} {} {To jest... có¿... tytu³ dokumentu, oczywiœcie.}
{252} {} {Wiem to. Ale co to oznacza?}
{253} {} {To jest * nazwa * obrazu, na który patrzysz. Co oznacza twoje imiê?}
{254} {} {Chyba nic.}
{255} {} {To wszystko.}
{256} {} {Rozumiem. Brzmi to jak bezcelowa rozmowa.}
{257} {} {Myœlê, ¿e prawie nic. Ale co przedstawia ten rysunek, bracie Franciszku?}
{258} {} {On... symbolizuje... (odwraca rysunek i czyta napis) Jednostka transformatorowa 6-B.}
{259} {} {Jasne, bracie Franciszku. Nagle wszystko sta³o siê dla mnie jasne.}

# Przegladaj ksi¹¿ki
{260} {} {Masz tu naprawdê ogromn¹ kolekcjê. Mogê przestudiowaæ te ksi¹¿ki?}
{261} {} {Przepraszam, ale bardzo uwa¿amy na dostêp do naszej biblioteki. Te ksi¹¿ki s¹ zbyt cenne, a ich wiedza mo¿e byæ niebezpieczna dla zwyk³ych ludzi.}
{262} {} {Ok, zapomnij.}
{263} {} {Myœlê, ¿e jesteœcie po prostu idiotami. Zegnam.}
{264} {} {Odmówisz mi, bratu w wierze?}
{1264} {} {Odmówisz mi, siostrze w wierze?}
{265} {} {Och, nie wiedzia³em, ¿e zosta³eœ wyœwiêcony na nowicjusza. Oczywiœcie, przejrzyj wszystkie ksi¹¿ki, ale b¹dŸ ostro¿ny, s¹ bardzo delikatne.}
{266} {} {Dziêkujê, bracie Franciszku. Bêdê bardzo ostro¿ny.}
{1266} {} {Dziêkujê, bracie Franciszku. Bêdê bardzo ostro¿na.}
{267} {} {Nie mogê niczego obiecaæ.}
{268} {} {Mogê przekazaæ bibliotece 300 kapsli.}
{269} {} {Có¿, to wszystko zmienia. Mo¿esz studiowaæ nasze ksi¹¿ki, ale b¹dŸ ostro¿ny, s¹ bardzo delikatne.}
{270} {} {}
{271} {} {Có¿, to wszystko zmienia.}
{272} {} {Nie mam teraz tylu kapsli. Przyjdê póŸniej.}
{273} {} {Nawet po pomocy nie mogê liczyæ na zaufanie?}
{274} {} {Och, oczywiœcie masz racjê. IdŸ, obejrzyj ksi¹¿ki, ale uwa¿aj, s¹ bardzo delikatne.}

# Wyprawa Aarona
{280} {} {Bracie Franciszku, czy przetrzymujesz tu harmonogram misji akolitów?}
{281} {} {Tak. Ale oczywiœcie nie poka¿ê ci tych zwojów. Dostêp do nich ma tylko kilku ministrów. Dlaczego ich potrzebujesz?}
{282} {} {Nie mogê o tym rozmawiaæ. Czy mo¿esz mi powiedzieæ, kto ostatnio je przegl¹da³?}
{283} {} {Hmm. Te dokumenty s¹ rzadko u¿ywane. Myœlê, ¿e mogê porównaæ z piecz¹tkami goœci. Ale podaj mi daty, których potrzebujesz.}
{284} {} {Interesuj¹ mnie te dni...}
{285} {} {...Có¿, najwyraŸniej w tamtych czasach tylko przeor Matthias móg³ sprawdzaæ te dokumenty.}
{286} {} {Gdzie mogê go znaleŸæ?}
{287} {} {Jego kwatery s¹ na korytarzu. Ale b¹dŸ cicho, brat Matthias bardzo siê denerwuje, kiedy nagle zabiera siê go od medytacji.}
{288} {} {Dziêki, bracie Franciszku, bardzo mi pomog³eœ.}
{289} {} {Rozumiem. Zostawiam ciê samego z tymi kawa³kami papieru.}

#Books
{300} {} {Mówi³eœ o kupowaniu ksi¹¿ek. Du¿o podró¿ujê.}
{301} {} {Oczywiœcie. Jeœli znajdziesz stare ksi¹¿ki, przynieœ je do mnie. Koœció³ sowicie zap³aci za twoje trudy.}
{302} {} {Bêdê pamietaæ.}
{303} {} {Potrzebujesz nowych ksi¹¿ek, prawda?}
{304} {} {Mam kilka zachowanych ksi¹¿ek.}
{305} {} {Bardzo dobrze. Ile ksi¹¿ek mo¿esz przekazaæ bibliotece?}
{306} {} {To nie wydaje siê byæ dok³adnie tym, czego chcesz. Przepraszam, ¿e przeszkadzam.}
{307} {} {Mam na myœli, ¿e mam zamiar szukaæ ksi¹¿ek. PA.}
{308} {} {Wszystkie ksi¹¿ki, które posiadam.}
{309} {} {Tylko jedn¹.}
{310} {} {Dwie ksi¹¿ki.}
{311} {} {Trzy ksi¹¿ki.}
{312} {} {Niez³e uzupe³nienie. Pomagasz w postêpie ca³ej ludzkoœci. Wielkie dziêki.}
{313} {} {WeŸ to za darmo. To moja darowizna dla koœcio³a.}
{314} {} {Naprawdê, twoja hojnoœæ nie zna granic. Dziêkujê Ci.}
{315} {} {Ale chcia³bym ciê o coœ zapytaæ.}
{316} {} {Proszê. PA.}
{317} {} {Chcê za to kapsle.}
{318} {} {Oczywiœcie. Brzmi sprawiedliwie. Oto twoja nagroda - }
{319} {} {kapsli.}
{320} {} {Czy biblioteka potrzebuje jakichœ konkretnych ksi¹¿ek?}
{321} {} {O tak. Niektórzy ludzie niechêtnie dziel¹ siê star¹ wiedz¹. Mo¿e dasz radê przebiæ siê przez ich g³upotê?}
{322} {} {Powiedz mi wiêcej. Kim jest ten chciwy zrzêda?}
{323} {} {Potrafiê rozmawiaæ z ka¿dym, nie tylko za pomoc¹ s³ów.}
{324} {} {Niedawno poinformowano mnie, ¿e w mieœcie San Brahmin jest bardzo stara ksiêga. I jest znacznie starsza ni¿ dzieñ Wielkiej Wojny. Czy mo¿esz to sobie wyobraziæ? Niestety, miejscowi nie potrafi¹ jej przeczytaæ, ale te¿ nie pozwol¹ nam siê do niej zbli¿yæ z powodu niedawnej wojny handlowej.}
{325} {} {Proponujesz j¹ ukraœæ?}
{326} {} {Myœlê, ¿e to brzmi trochê zbyt szorstko. Ale nie zrozum mnie Ÿle. Miejscowi dzicy nie rozumiej¹ prawdziwego znaczenia tej ksi¹¿ki i nie mog¹ zapewniæ jej odpowiednich warunków. W naszych rêkach ta relikwia zrobi wiêcej dobrego. Wiêc, zdobêdziesz dla nas tê ksi¹¿kê? Zap³acê za to.}
{327} {} {Moja odpowiedŸ brzmi: nie. Nie chcê uczestniczyæ w grabie¿y jakichkolwiek koœcio³ów.}
{328} {} {Có¿, rozumiem. Zapomnij o wszystkim, co tu s³ysza³eœ.}
{329} {} {Oczywiœcie.}
{330} {} {Myœlê, ¿e wiesz lepiej, co zrobiæ z tymi starymi rzeczami. Przyniosê ci tê œwiêt¹ ksiêgê.}
{331} {} {Bardzo dobrze. Nie mogê siê doczekaæ.}
{332} {} {Pewnie siê ucieszysz. Mam œwiêt¹ ksiêgê.}
{333} {} {Och, te strony s¹ piêkne! Bo¿e, jest tu nawet ³acina. Uff, a¿ mi zapar³o dech w piersiach...}
{334} {} {Jeœli jest to rzeczywiscie takie wa¿ne dla koœcio³a, weŸ to za darmo. Chcê tylko zrobiæ coœ dobrego.}
{335} {} {Bêdê siê za ciebie modliæ, mój bracie. Na œwiecie brakuje ludzi takich jak Ty.}
{1335} {} {Bêdê siê za ciebie modliæ, siostro. Na œwiecie brakuje ludzi takich jak Ty.}
{336} {} {Powodzenia, bracie Franciszku.}
{337} {} {Ten przedmiot by³ bardzo trudny do zdobycia. Chcê w zamian 300 kapsli.}
{338} {} {Oczywiœcie, tutaj s¹ kapsle. Kapsli nam nie szkoda dla tej relikwii.}
{339} {} {Powodzenia, bracie Franciszku.}
{340} {} {Czekaj, bracie. Myœlê, ¿e powinieneœ porozmawiaæ z samym Aaronem. Poinformujê go o pomocy, jakiej udzieli³eœ naszemu koœcio³owi. A jeœli potrzebujesz mojej rekomendacji, mo¿esz na ni¹ liczyæ.}
{1340} {} {Czekaj, siostro. Myœlê, ¿e powinieneœ porozmawiaæ z samym Aaronem. Poinformujê go o pomocy, jakiej udzieli³aœ naszemu koœcio³owi. A jeœli potrzebujesz mojej rekomendacji, mo¿esz na ni¹ liczyæ.}
{341} {} {Dobrze.}
{342} {} {Do zobaczenia ponownie.}
{343} {} {Tak siê sk³ada, ¿e mam ju¿ tê ksi¹¿kê.}