{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz stra¿nika karawany. Przygotowuje siê do dalszej podró¿y.}

{110} {} {Swietnie.}
{111} {} {Daj mi trochê odpocz¹æ.}
{112} {} {Jestem trochê spragniony.}
{113} {} {Czas wyjœæ.}
{114} {} {Có¿, jest gor¹co.}

{115} {} {Porozmawiaj z szefem, ja tu tylko strzegê ³adunku.}
{116} {} {Mamy zajête wszystkie miejsca, jeœli jesteœ zainteresowany.}
{117} {} {Musimy sprzedaæ wszystkie towary, albo zbankrutujemy.}
{118} {} {Podró¿ujemy do prawie ka¿dego zak¹tka pustkowi.}
{119} {} {Musisz sprawdziæ Atomic Fever, czêsto tam spêdzamy czas.}

{120} {} {Dzisiaj bêdzie d³ugi dzieñ.}
{121} {} {Nie mogê siê doczekaæ koñca.}
{122} {} {Jaki dziœ dzieñ?}
{123} {} {Jestem taki zmêczony.}
{124} {} {Chyba czas iœæ do ³ó¿ka.}

{125} {} {Mamy niebezpieczn¹ pracê.}
{126} {} {Burze piaskowe s¹ czasami bardziej niebezpieczne ni¿ bandyci na drogach.}
{127} {} {Podró¿owanie po autostradzie jest teraz jak szukanie œmierci.}
{128} {} {Tak, odwróci³em siê od tych bandytów i rabusi na zawsze.}
{129} {} {Jeœli ten wózek rozpadnie siê po drodze, nie naprawiê go.}
