{100} {} {Widzisz kupca Marco.}
{101} {} {Widzisz menad¿era karawany. Jego ciemna skóra œwiadczy o niezliczonych przejechanych milach.}
{102} {} {Mi³ej podró¿y.}
{103} {} {Ta osada nazywa siê Tu-San. Miejscowi nie ufaj¹ obcym, wiêc uwa¿aj na siebie.}

{200} {} {Czeœæ. Co tam?}
{201} {} {Jesteœ mened¿erem tej karawany?}
{202} {} {Tak. Jeœli potrzebujesz us³ug transportowych, skontaktuj siê z kimœ innym. Staram siê nie rozpraszaæ ma³ymi zamówieniami.}
{203} {} {Wygl¹da na to, ¿e Twoja firma ma siê dobrze.}

{210} {} {Czego chcesz?}
{211} {} {Nic.}
{212} {} {Doœæ o tym.}
{213} {} {Rozumiem.}

#Zapytania
{220} {} {Co robisz?}
{221} {} {Przygotowujê siê do wyjazdu i czekam na resztê ³adunku. Moi klienci nie lubi¹ siê œpieszyæ, staraj¹ siê prowadziæ szczegó³owy zapis ka¿dego cholernego towaru, który musimy przewieŸæ.}
{222} {} {D³ugo zajmujesz siê karawaniarstwem?}
{223} {} {Oko³o szeœciu lat. Mam talent do „¿y³y uranowej”, wiesz? Nikt wtedy nie wierzy³, ¿e umowa z Blacharzami stanie siê kopalni¹ kapsli. Mia³em szczêœcie zajmuj¹c wolne miejsce.}
{224} {} {Co przewozisz?}
{225} {} {Blacharze interesuj¹ siê g³ównie rud¹ uranu, ¿ywnoœci¹ i lekarstwami. Wymieniaj¹ je na przedmioty technologiczne, które zbieraj¹ lub naprawiaj¹ w swoich warsztatach.}
{226} {} {A niewolnicy?}
{227} {} {To nie moja sprawa, niewolnicy s¹ zbyt k³opotliwi. Do takiego zadania zwykle organizuj¹ specjalny konwój w gildii najemników lub rekrutuj¹ ludzi ze zwyk³ej populacji.}
{228} {} {Kim s¹ ci Blacharze?}
{229} {} {Dziwni, zamkniêci ludzie maj¹cy obsesjê na punkcie technologii. Odnowili staro¿ytne maszyny i teraz naprawiaj¹ ca³y zepsuty sprzêt z okolicy. Nikt w ca³ej Arizonie nie przebije ich umiejêtnoœci w tej dziedzinie.}
{230} {} {Gdzie jest ich osada?}
{231} {} {Tu-San. Tak nazywaj¹ swoje miasto. Kieruj siê na po³udnie autostrad¹ nr 10, nie mo¿esz tego przegapiæ.}
{232} {} {Dziêki.}
{233} {} {Kim s¹ Twoi klienci?}
{234} {} {Zosta³em zatrudniony przez Wyznawców Ognia. Na tym koniec z pytaniami. Mam zasadê, aby nie rozmawiaæ o klientach z pierwsz¹ lepsz¹ osob¹, któr¹ spotykam.}
{235} {} {Ok, zapomnij.}
{236} {} {Kim s¹ Blacharze?}

{240} {} {Cholera! Dlaczego teraz, kiedy biznes kwit³, Wyznawcy zdecydowali siê opuœciæ ten œwiat?}
{241} {} {Byli a¿ tak wa¿ni dla twojej karawany?}
{242} {} {Po odejœciu Obserwatorów nikt nie chce robiæ ze mn¹ interesów. Pracowaliœmy tylko z nimi. Poza tym bez Obserwatorów sami Blacharze prawdopodobnie zmniejsz¹ obroty. Do diab³a, ca³a gospodarka Phoenix koñczy siê z t¹ niedorzeczn¹ eksplozj¹. Co siê tam do diab³a sta³o?}
{243} {} {Sk¹d mam wiedzieæ? Generalnie zajmujê siê swoimi sprawami. Bywaj.}
{244} {} {Nie mam z tym nic wspólnego! To na pewno nie przeze mnie.}
{245} {} {Oczywiœcie. Jakby Wyznawcy wpuszczali do swoich komnat zwyk³ych ch³opów. No có¿.}
{246} {} {Ugh, przez chwilê myœla³em, ¿e mnie podejrzewasz. PA.}
{247} {} {Myœlisz, ¿e wysadzili siê w powietrze?}
{248} {} {Có¿, tak mawiaj¹. W koñcu przesadzili z ca³¹ t¹ technologi¹ nuklearn¹. Plotka g³osi, ¿e w piwnicy katedry z³o¿yli bombê atomow¹. Coœ posz³o nie tak - i oto wynik.}
{249} {} {Ale dlaczego tak bardzo ci to przeszkadza? Czy twoja karawana by³a zale¿na od œwi¹tyni?}

{250} {} {Szukam niewolników. Zostali przywiezieni z Kolonii Flagpoll.}
{251} {} {Prosto z kolonii? Och... Có¿, je¿dzê karawanami, ale nie mam nic wspólnego z transportowaniem niewolników. Lepiej porozmawiaj z kimœ z miasta.}
{252} {} {Na przyk³ad? Kto tu to móg³ robiæ?}
{253} {} {W gildii najemników mo¿na znaleŸæ ka¿dego. Znajduje siê w centrum biznesowym, na lewo od bramy miejskiej.}
{254} {} {Jesteœ bezu¿yteczny. Do widzenia.}
{255} {} {Dziêki, pa.}

# Escort
{300} {} {Muszê dostaæ siê do Tu-San.}
{301} {} {Dlaczego mielibyœmy ciê zabraæ do grupy? Dodatkowa osoba tylko nas spowolni.}
{302} {} {Karawaniarze musz¹ sobie pomagaæ.}
{303} {} {Czy wiesz, jak dostaæ siê do Puerto Penasco?}
{304} {} {Jako wyznawca ognia bêdê przydatny w twoich kontraktach w przysz³oœci.}
{305} {} {Przepraszam. Ale mo¿e wiesz o innych rzeczach.}
{306} {} {Wiêc jesteœ kolejnym poszukiwaczem przygód, który szuka pozosta³oœci po tych wspania³ych ludziach? Twoja sprawa, ale na razie od³o¿yliœmy wszelkie wyjazdy do Tu-San.}
{1306} {} {Wiêc jesteœ kolejnym poszukiwaczem przygód, który szuka pozosta³oœci po tych wspania³ych ludziach? Twoja sprawa, ale na razie od³o¿yliœmy wszelkie wyjazdy do Tu-San.}
{307} {} {Rozumiem. Wiêc mi nie pomo¿esz.}
{308} {} {Mo¿e. Ale nie w twoim przypadku.}
{309} {} {Myœlê, ¿e s³ysza³em o tym mieœcie od Blacharzy z Tu-San. Handluj¹ z tym miastem, ale nie wiem nic wiêcej.}

{310} {} {Ok. Wygl¹da na to, ¿e mo¿na robiæ z tob¹ interesy. Mo¿esz iœæ z nami. Pamiêtaj jednak, ¿e Blacharze dok³adnie strzeg¹ swojej osady i nie toleruj¹ bezczynnych obcych. Musisz znaleŸæ dobry powód, jeœli chcesz wejœæ do œrodka.}
{311} {} {Kiedy siê pakujesz?}
{312} {} {6:00 rano zebranie. Zabierz ze sob¹ nie wiêcej ni¿ 150 funtów ³adunku. Pamiêtaj te¿, ¿e zatrzymamy siê w Casa Grande, czy ci siê to podoba, czy nie.}
{313} {} {Mogê iœæ.}
{314} {} {Bêdê o wyznaczonej godzinie.}
{315} {} {Nikt nie bêdzie nosi³ twoich rzeczy. Zabierz nie wiêcej ni¿ 150 funtów albo odjedziemy bez Ciebie.}
{316} {} {To bêd¹ moje problemy.}
{317} {} {Cokolwiek powiesz.}
{318} {} {Ruszcie swoje ty³ki, mamy przed sob¹ d³ug¹ drogê!}
{319} {} {[Udaj siê w podró¿]}
{320} {} {Mo¿e tak. Albo mo¿e nie.}
{321} {} {Ok, jeszcze raz spojrzê na mój plecak.}
{322} {} {Zap³acê 1000 kapsli za eskortê.}
{323} {} {Spora kwota. Na pewno masz tyle kapsli?}
{324} {} {Pozwól mi policzyæ...}
{325} {} {Mam wa¿ne zadanie dla Koœcio³a Ognia.}
{326} {} {Rozumiem. Czeœæ.}

# Inne lokalizacje
{400} {} {To œwietne miejsce na odpoczynek w drodze do Tu-San. Uzupe³nimy tu zapasy wody, spêdzimy noc i ruszymy dalej. Jeœli spóŸnisz siê na wyjazd, nie bêdziemy na Ciebie czekaæ.}
{401} {} {Co mo¿esz mi powiedzieæ o tym miejscu?}
{402} {} {Casa Grande to ma³e miasteczko. Zwykle zatrzymujemy siê tutaj po drodze miêdzy Tu-San a Phoenix. Jego g³ówn¹ atrakcj¹ jest znajduj¹ca siê na tej ulicy przepompownia. Nieczêsto na tym pustkowiu mo¿na znaleŸæ Ÿród³o tak œwie¿ej i czystej wody.}
{403} {} {Do zobaczenia.}
{404} {} {[Poczekaj, a¿ karawana wyruszy do Tu-San]}
{405} {} {WyjdŸ beze mnie, spóŸniê siê.}
{406} {} {Jak sobie ¿yczysz. Nie bêdziemy czekaæ.}
{407} {} {Rozumiem, bywaj.}