{100} {} {Widzisz obywatela.}
{101} {} {Widzisz obywatela Phoenix.}
{102} {} {Widzisz obywatela Phoenix.}
{103} {} {}

{110} {} {Widzisz zwyk³ego mieszkañca Phoenix. Nic wyj¹tkowego.}
{111} {} {Widzisz niepozornego mê¿czyznê. Chodzi po ulicy bez celu.}
{112} {} {Widzisz mê¿czyznê w brudnym ubraniu. Wydaje siê, ¿e ma kaca.}
{113} {} {Widzisz tutejszego. Wygl¹da nieprzyjaŸnie.}
{114} {} {Widzisz tutejszego. Szybko odwraca wzrok, jakby nie chcia³ nic widzieæ.}

{120} {} {Widzisz zwyk³ego mieszkañca Phoenix. Nic wyj¹tkowego.}
{121} {} {Widzisz niepozorn¹ kobietê. Idzie têpo ulic¹.}
{122} {} {Widzisz kobietê w zniszczonym ubraniu. Przyda³aby siê jej zmiana garderoby.}
{123} {} {Widzisz kobietê z Phoenix. Jej spojrzenie wyra¿a irytacje.}
{124} {} {Widzisz kobietê z Phoenix. Prycha, kiedy zauwa¿a twój wzrok.}

########################################
# Uwagi dotycz¹ce odpowiedzi
########################################

# - reputacja
{200} {} {Dzieñ dobry.}
{201} {} {Hej!}
{202} {} {* Macha do Ciebie uprzejmie *}
{203} {} {Oczywiœcie, oczywiœcie, nie œmiem zwlekaæ.}
{204} {} {Jest coœ, w czym mogê ci pomóc?}
{205} {} {Chcia³bym postawiæ Ci drinka, ale jestem bankrutem.}
{206} {} {Czeœæ. Jak siê masz?}
{207} {} {Muszê trzymaæ siê ludzi takich jak ty.}
{208} {} {Nie wiem dlaczego, ale mówi siê o tobie wiele dobrych rzeczy.}
{209} {} {Moje uszanowanie.}

{210} {} {Czeœæ.}
{211} {} {Uwa¿aj, gdzie idziesz.}
{212} {} {Cholerni turyœci...}
{213} {} {Nie przeszkadzaj przechodniom, bo dostaniesz miêdzy oczy.}
{214} {} {Nie jesteœ miejscowy, to widaæ.}
{215} {} {Pierwszy raz w Phoenix, co?}
{216} {} {* Odpycha ciê *}
{217} {} {Nic nie mam... kolejny ¿ebrak.}
{218} {} {Przestañ mnie drêczyæ.}
{219} {} {Czego chcesz?}

{220} {} {Spierdalaj.}
{221} {} {ZejdŸ z ulicy.}
{222} {} {ZejdŸ z drogi.}
{223} {} {Kiedy ciê powiesz¹, bêdê siê œmiaæ. SMIAC!}
{224} {} {Swietnie, jeszcze jeden ch³op. Dlaczego tu jesteœ, co?}
{225} {} {Masz za ma³o miejsca na pustkowiu?}
{226} {} {Trzymaj siê z dala ode mnie.}
{227} {} {Nie ma miejsca w Phoenix dla takich jak ty.}
{228} {} {Z czasem wszystko zrozumiesz.}
{229} {} {Miasto by³oby lepszym miejscem bez ciebie.}

# - pancerz wspomagany
{230} {} {Nie dotykaj mnie, Iron Manie!}
{231} {} {Hej, uh, proszê pana... proszê pani... czy ktokolwiek tam jest.}
{232} {} {Mo¿esz mnie podwieŸæ?}
{233} {} {Ten, czy mo¿esz zabiæ kilku moich wrogów?}
{234} {} {Szukasz innych robotów? Takich samych co ty?}
{235} {} {Jeœli szukasz innych robotów, nie zosta³o ich wielu.}
{236} {} {Zal mi ciê, robocie, jesteœ taki samotny w œwiecie ludzi.}
{237} {} {* Puk puk * Hej, jest kto?}
{238} {} {Przepraszam, ale Stracha na Wróble tu nie ma.}
{239} {} {Nie ka¿ mi ciê naoliwiaæ.}

# - obserwujacy YY
{240} {} {Modlê siê do Swiêtego Ognia ka¿dego dnia... naprawdê, naprawdê.}
{241} {} {Przepraszam, natychmiast zejdê Ci z drogi...}
{242} {} {Obiecujê, ¿e bêdê dobry.}
{243} {} {Niech Swiêty Ogieñ bêdzie s³awny... Co dalej?}
{244} {} {Przepraszam, nie bêdê ju¿ oddychaæ TWOIM powietrzem.}
{245} {} {Czczê Aarona, naszego wyzwoliciela.}
{246} {} {Jak zostaæ nowicjuszem?}
{247} {} {Nie potrzebujê k³opotów.}
{248} {} {Naprawdê nie wolno ci siê pieprzyæ?}
{249} {} {Nawet mnie nie proœ o datki dla œwi¹tyni, nic nie mam.}

# - Mistrz GG Arena
{250} {} {Postawi³bym ci drinka, ale mój zak³ad na ostatni¹ walkê nie wypali³.}
{251} {} {Cholera, gdybyœ przegra³, mój zak³ad by wygra³.}
{252} {} {Przepraszam, natychmiast zejdê Ci z drogi... i opuszczê miasto.}
{253} {} {Nie mo¿esz jeszcze powiedzieæ, ¿e jesteœ mistrzem.}
{254} {} {Jak d³ugo musia³eœ trenowaæ?}
{255} {} {Jeœli przegrasz nastêpn¹ walkê, NAPRAWDE siê zez³oszczê.}
{256} {} {Zabiorê swoje dzieci na nastêpn¹ walkê.}
{257} {} {To by³a œwietna walka, mistrzu.}
{258} {} {Dlaczego ju¿ nie walczysz na ringu?}
{259} {} {Walki na arenie sta³y siê bez ciebie nudne.}

{1250} {} {Postawi³bym ci drinka, ale mój zak³ad na ostatni¹ walkê nie wypali³.}
{1251} {} {Cholera, gdybyœ przegra³a, mój zak³ad by wygra³.}
{1252} {} {Przepraszam, natychmiast zejdê Ci z drogi... i opuszczê miasto.}
{1253} {} {Nie mo¿esz jeszcze powiedzieæ, ¿e jesteœ mistrzem.}
{1254} {} {Jak d³ugo musia³aœ trenowaæ?}
{1255} {} {Jeœli przegrasz nastêpn¹ walkê, NAPRAWDE siê zez³oszczê.}
{1256} {} {Zabiorê swoje dzieci na nastêpn¹ walkê.}
{1257} {} {To by³a œwietna walka, mistrzu.}
{1258} {} {Dlaczego ju¿ nie walczysz na ringu?}
{1259} {} {Walki na arenie sta³y siê bez ciebie nudne.}

# - YY ukamienowany
{260} {} {Tak, uh, skrzaty tam za rogiem.}
{261} {} {Czy jesteœ na haju?}
{262} {} {Ja te¿ mia³em z tym problemy.}
{263} {} {Nie mam dla ciebie ¿adnych narkotyków.}
{264} {} {OdejdŸ, cholerny æpunie.}
{265} {} {Przykro mi z powodu ludzi takich jak ty.}
{266} {} {Wszystko w porz¹dku?}
{267} {} {Wygl¹da na to, ¿e nie wszystko z tob¹ w porz¹dku... s¹dz¹c po rozszerzonych Ÿrenicach.}
{268} {} {To nic nie da.}
{269} {} {Potrzebujesz narkotyków? Poszukaj ich w slumsach, frajerze.}

# - o mieœcie
{270} {} {To niebo ju¿ nigdy nie bêdzie czyste.}
{271} {} {Ta noc bêdzie gor¹ca.}
{272} {} {Wschodnie wiatry przynosz¹ tylko py³ i popió³.}
{273} {} {Zawsze to robi³em tutaj.}
{274} {} {Nadchodzi sezon burz py³owych.}

{275} {} {Nienawidzê tego cholernego miasta.}
{276} {} {Mieszkam tu zdecydowanie zbyt d³ugo.}
{277} {} {Miasto robi siê ostatnio trochê zat³oczone.}
{278} {} {Czas wyrwaæ siê z tego miasta.}
{279} {} {Phoenix jest pe³ne ludzi... i problemów.}

{280} {} {Fortuna odwróci³a siê ode mnie.}
{281} {} {Mam zamiar rozbiæ bank w kasynie.}
{282} {} {Próbujê wi¹zaæ koniec z koñcem, ale...}
{283} {} {Czas siê zabawiæ!}
{284} {} {Chcê spróbowaæ szczêœcia w kasynie.}

{285} {} {Nie mogê siê doczekaæ, a¿ Veronica znowu zaœpiewa.}
{286} {} {Veronica ma godn¹ pozazdroszczenia postaæ.}
{287} {} {Kolejny bezwartoœciowy dzieñ.}
{288} {} {WejdŸ na ring, jeœli nie masz nic do roboty.}
{289} {} {Ani jednego deszczu od lat...}

{290} {} {Mówi¹, ¿e najemnicy przygotowuj¹ now¹ grupê niewolników.}
{291} {} {W kasynie jest kilku oszustów.}
{292} {} {Uliczni bandyci zupe³nie wymknêli siê im z r¹k.}
{293} {} {W slumsach czeka na ciebie œmieræ.}
{294} {} {Karawany, dooko³a same karawany...}

{295} {} {}
{296} {} {}
{297} {} {}
{298} {} {}
{299} {} {}

########################################
# Plywajace repliki
########################################

# - reputacja
{300} {} {}

# - pancerz wspomagany
{330} {} {O nie, nie, to patrzy w moj¹ stronê!}
{331} {} {Myœlicie, ¿e chce kogoœ zaatakowaæ?}
{332} {} {Po prostu to zignoruj, po prostu to zignoruj...}
{333} {} {Widok tej... RZECZY sprawia, ¿e czujê siê nieswojo.}
{334} {} {To nie wygl¹da na robota.}
{335} {} {Wiêc to jest ta legendarna zbroja wspomagana?}
{336} {} {Mam nadziejê, ¿e nie jest to radioaktywne.}
{337} {} {Czy to jakaœ samobie¿na pralka?}
{338} {} {Mówi¹, ¿e ten kawa³ek ¿elaza zabi³ wczoraj piêciu z nich.}
{339} {} {Ups, lepiej zejdê z drogi.}

# - obserwujacy YY
{340} {} {Trzymajcie siê z dala od tego goœcia.}
{341} {} {Wygl¹da z³owrogo.}
{342} {} {Ci kultyœci rozwiedli siê ... Ups, lepiej milcz.}
{343} {} {Nie mów Ÿle o Obserwatorach.}
{344} {} {Nie gap siê na Obserwatorów, to z³y omen.}
{345} {} {To Obserwator? Muszê powiedzieæ coœ pochlebnego...}
{346} {} {Ci Obserwatorzy wszêdzie maj¹ szpiegów.}
{347} {} {Tak po prostu spacerujesz sobie po mieœcie? Ci sekciarze stali siê doœæ aroganccy.}
{348} {} {Ci wyznawcy czuj¹ siê jak w³aœciciele Phoenix.}
{349} {} {Mam nadziejê, ¿e ten kultysta nie poprosi mnie o darowizny.}

# - mistrz GG Arena - m¹¿
{350} {} {To ten szaleniec z ringu!}
{351} {} {Myœlisz, ¿e uderzy mnie, jeœli podejdê?}
{352} {} {Ten wojownik jest przyk³adem dla wszystkich wojowników.}
{353} {} {Nie patrz na niego, nie patrz...}
{354} {} {Hej, wspania³a walka, mistrzu!}
{355} {} {* gwizdy * Hej! Mistrzu!}
{356} {} {Zastanawiam siê, czy ten brutal zwróci na mnie uwagê.}
{357} {} {Ludzie zarabiaj¹ na walce. Dok¹d zmierza ten œwiat...}
{358} {} {Dlaczego ju¿ nie walczysz?}
{359} {} {No dalej, brutalu, poka¿ mi swój lewy hak!}

# - Mistrz GG Arena - zony
{360} {} {To ta wariatka z ringu.}
{361} {} {Myœlisz, ¿e uderzy mnie, jeœli podejdê?}
{362} {} {To ta suka co roz³o¿y ka¿dego na ³opatki.}
{363} {} {Nie patrz na ni¹, nie patrz...}
{364} {} {Hej, to wspania³a mistrzyni walk!}
{365} {} {* gwizdy * Hej! Mistrzyni!}
{366} {} {Ciekawe, czy taka gwiazda zwróci na mnie uwagê.}
{367} {} {Kobieta i mistrz areny? Do czego to dosz³o...}
{368} {} {Dlaczego ju¿ nie walczysz?}
{369} {} {Dawaj kobieto, poka¿ mi swój prawy hak!}

# - o mieœcie
{370} {} {* Apchi! *}
{371} {} {Trudno tu oddychaæ.}
{372} {} {Z powodu smogu miasta nie widaæ nawet z góry.}
{373} {} {Ktoœ musi posprz¹taæ te wszystkie œmieci.}
{374} {} {Ta noc bêdzie gor¹ca.}

{375} {} {Miasto robi siê trochê zat³oczone.}
{376} {} {Dobrze, ¿e ten facet zosta³ powieszony...}
{377} {} {Wszêdzie wokó³ sami w³óczêdzy i menele...}
{378} {} {Nie mogê ju¿ tak ¿yæ.}
{379} {} {Czas wyjechaæ z miasta.}

{380} {} {Bank kasyna zlitowa³ siê nade mn¹.}
{381} {} {Nigdy wiêcej stopy w kasynie.}
{382} {} {Pójdê do kasyna na godzinê... lub d³u¿ej.}
{383} {} {Fortuna odwróci³a siê ode mnie.}
{384} {} {Wszystko by³o przeciwko mnie. WSZYSTKO.}

{385} {} {Jeœli Obserwatorzy zaczn¹ prawiæ mi kolejny mora³...}
{386} {} {W slumsach jest niebezpiecznie nawet w ci¹gu dnia.}
{387} {} {Wiêcej karawan, super.}
{388} {} {Czy poza miastem jest ¿ycie?}
{389} {} {Tylko zdesperowani mog¹ podró¿owaæ po pustyni.}

# - Wybuch w katedrze
{390} {} {Ci kultyœci dostaj¹ to, na co zas³uguj¹.}
{391} {} {Phoenix bêdzie mia³o trudnoœci bez Wyznawców.}
{392} {} {Katedra zniszczona, a wyznawcy uciekli. Czas na zmiany...}
{393} {} {Nie wiem, jak jest lepiej - z wyznawcami czy bez.}
{394} {} {Nie mogê uwierzyæ, ¿e to by³a bomba atomowa.}
{395} {} {Wiêc ci idioci budowali tam bombê atomow¹?}
{396} {} {Bomba atomowa? Tak, zdecydowanie byli szaleni.}
{397} {} {Po eksplozji katedry kapsle zaczê³y traciæ na wartoœci.}
{398} {} {Kto bêdzie teraz kontrolowa³ przep³yw kapsli?}
{399} {} {Wygl¹da na to, ¿e kapsle znowu bêd¹ bezu¿ytecznymi œmieciami.}