{100} {} {Widzisz ¿ebraka.}
{101} {} {Widzisz zwyk³ego mieszkañca ulicy.}
{102} {} {By³eœ œwiadkiem przestêpstwa.}
{103} {} {Ile jestem wart? Musimy usun¹æ œwiadków!}

{110} {} {Czy ja jestem... morderc¹?}
{111} {} {Nie chcia³em!}
{112} {} {Zmusi³a mnie.}
{113} {} {Gdyby nie pokaza³a kapsli...}
{114} {} {Dlaczego to zrobi³em?}
{115} {} {Myœlê, ¿e j¹ zabi³em.}
{116} {} {Mój Bo¿e, zabi³em cz³owieka!}
{117} {} {Teraz nie mo¿na ju¿ nic na to poradziæ.}
{118} {} {Nikomu nie powiesz, prawda?}
{119} {} {Wygl¹da na to, ¿e bêdê musia³ wyjechaæ z miasta.}