{102} {} {Nie bêdê tego tolerowa³ w moim kasynie. Zostaw swoje zabawki na zewn¹trz.}
{103} {} {Grozisz mi?}

# Znajomosc
{200} {} {Potrzeba stalowych jaj, ¿eby siê do mnie w ten sposób dostaæ. Kim jesteœ? Czego potrzebujesz?}
{1200} {} {Potrzeba stalowych jaj, ¿eby siê do mnie w ten sposób w³amaæ. Kim jesteœ? Czego potrzebujesz?}
{201} {} {Jestem }
{202} {} { z Villi. Chcê dla ciebie pracowaæ, Don Diego.}
{203} {} {Wielu mówi to samo, a potem ucieka przy najmniejszym teœcie odpowiedzialnoœci. Widzisz, to kasyno to nie tylko miejsce do zarabiania dla mnie pieniêdzy. To rodzina. Potrzebujê dobrego powodu, by zaakceptowaæ ka¿d¹ osobê, któr¹ spotkam.}
{204} {} {Jeœli potrzebujesz fundamentów, znajdê coœ, co je wzmocni. Do zobaczenia, Don Diego.}
{205} {} {Bill ostrzeg³ mnie, ¿e przyjdziesz. Kim jesteœ? Czego potrzebujesz?}
{206} {} {Don Diego, pos³uchaj mnie. Spo³ecznoœæ, z której pochodzê, pad³a ofiar¹ handlarzy niewolników. Próbujê ich uwolniæ.}
{207} {} {Wiêc dlaczego nie poprosisz samego Aarona o pomoc? O ile wiem, to jego kult dostarcza kapsle handlarzom niewolników w ró¿nych koloniach. Nie mogê i nie chcê Ci pomóc.}
{208} {} {Przykro mi to s³yszeæ. Zegnaj Don Diego.}
{209} {} {Ciekawe. Czy prosisz mnie o pomoc?}
{210} {} {Wola³bym zaproponowaæ wspó³pracê. Wygl¹da na to, ¿e mamy wspólnego wroga - wyznawców ognia.}
{211} {} {Mówisz o prostych sprawach. Jak powiedzia³em, to kasyno to dla mnie rodzina, a nie tylko biznes. Nie chcê nara¿aæ siebie i moich „bliskich” w bezpoœredniej walce z sekciarzami i dzia³aæ jako agresor. Ale presja Aarona staje siê coraz silniejsza i pewnego dnia bêdê musia³ podj¹æ drastyczne dzia³ania.}
{212} {} {Przykro mi to s³yszeæ. Zegnaj Don Diego.}
{213} {} {Daj mi szansê. Nie bêdziesz ¿a³owaæ.}
{214} {} {Nie proszê o pomoc. Proszê o sprawiedliwoœæ, Don Diego.}
{215} {} {Wiesz, ja te¿ by³em taki jak ty, zwyk³y ch³op. Kopany w b³ocie, zajêty bawi¹cymi siê myszami w starej stodole. Wydostanie siê z tej dziury i zdobycie przyczó³ka w mieœcie wymaga³o wiele wysi³ku.}
{216} {} {Cieszê siê, ¿e mnie rozumiesz.}
{217} {} {Od tamtej pory minê³o bardzo du¿o czasu. Sprawiasz jednak, ¿e wspó³czujê. Ale potrzebujê dobrego powodu, ¿eby ci zaufaæ.}
{218} {} {Wystaw mnie na próbê. Udowodniê, ¿e twoja nieufnoœæ wobec mnie jest daremna.}
{219} {} {Przykro mi to s³yszeæ. Zegnaj Don Diego.}
{220} {} {Porozmawiaj z Garcia. Na pocz¹tek da ci kilka ³atwych zadañ. Zobaczmy, jak sobie z tym poradzisz.}
{221} {} {Nie bêdê ciê ju¿ niepokoiæ, Don Diego.}
{222} {} {Ok. Tak jak mówisz.}
{223} {} {Przepraszam, nie mam teraz ¿adnej pracy dla ciebie.}
{224} {} {Przykro mi to s³yszeæ.}

{250} {} {Czego chcesz?}
{251} {} {Co, powiedz mi?}
{252} {} {Czy coœ siê sta³o?}
{253} {} {Moje uszanowanie, Don Diego.}

{260} {} {Don Diego, zastanawiam siê, co zamierzasz zrobiæ teraz, gdy katedra zosta³a zniszczona?}
{261} {} {Pozwalasz sobie na pytania wykraczaj¹ce poza status.}
{262} {} {Przepraszam, Don Diego.}
{263} {} {Ok, jestem po prostu ciekawy.}
{264} {} {Tak jak poprzednio. Zarabiaæ, zwiêkszaæ swoje wp³ywy. Teraz jest to ³atwiejsze ni¿ kiedykolwiek wczeœniej.}
{265} {} {Kult ognia stawa³ ci na drodze, prawda?}
{266} {} {Opuszczenie sceny przez czcicieli ognia w Phoenix stwarza nowe miejsca pracy, ale jednoczeœnie jest ciosem dla wielu obszarów dzia³alnoœci w mieœcie. Bez katedry trudno bêdzie utrzymaæ kurs waluty kapsli, czêœæ karawan straci pracê, czêœæ ludzi ju¿ ucieka z miasta. Nie trzeba nawet wspominaæ o zwiêkszonej przestêpczoœci. W takich warunkach trzeba zrewidowaæ ca³y biznes. Ale tak, pasuje mi to.}
{267} {} {Dziêki za odpowiedŸ, Don Diego.}

# Atak na obserwujacych
{300} {} {Prowadzê œledztwo w sprawie ataku na mnichów. Co o tym wiesz?}
{301} {} {Nie pozwolê ci tak tu wpadaæ i mnie przes³uchaæ. Ochrona, wyrzuciæ tego irytuj¹cego cz³owieka z kasyna.}
{302} {} {Nie dotykajcie mnie!}
{303} {} {Ok, pójdê.}
{304} {} {Czy dla Obserwatorów sta³o siê ju¿ norm¹ w³amywanie siê i przes³uchanie innych? Okay, odpowiem z szacunku dla koœcio³a, który zasila to miasto.}
{305} {} {Swietnie, pozwól mi otworzyæ notatnik... Zacznijmy.}
{306} {} {Ja. Nic. Nie wiem.}
{307} {} {Ech, co?}
{308} {} {Ktoœ otoczy³ mnichów na ulicy i strzela³ do nich z bliska. Mnie tam nie by³o, kr¹¿¹ ró¿ne plotki, moi ludzie zapewniaj¹, ¿e to nie ich sprawka. Nie mam nic wiêcej do powiedzenia.}
{309} {} {Och, przepraszam Don Diego. Teraz widzê, ¿e marnujê tylko Twój czas.}
{310} {} {Sukcesu w dochodzeniu. I nie zawracaj mi tym g³owy.}
{311} {} {Do widzenia.}
{312} {} {Jakie masz alibi, ty i twoi podw³adni?}
{313} {} {Co to kurwa jest alibi? Nasze kasyno jest zobowi¹zane Koœcio³owi Swiêtego Ognia za to, co zrobi³ dla miasta. Koœció³ reguluje rotacje kapsli i daje ludziom pracê. Nie ma sensu siekaæ bramina, którego doimy, rozumiesz? Co wiêcej, sta³o siê to tu¿ pod naszymi drzwiami.}
{314} {} {Hmm, mimo wszystko wygl¹da to w¹tpliwe. Odejdê, ale nadal Ci nie wierzê.}
{315} {} {Teraz rozumiem. Wszystkiego najlepszego.}
{316} {} {W porz¹dku, Don Diego, porozmawiajmy nieformalnie.}
{317} {} {Hej Garcia, co robi tu ten wieœniak? Myœli, ¿e mo¿e rozmawiaæ ze mn¹ na równych prawach? Ta osoba jest zdecydowanie za g³upia. Wyrzuæ to na ulicê.}
{1317} {} {Hej Garcia, co robi tu ta wieœniaczka? Czy uwa¿a, ¿e mo¿e rozmawiaæ ze mn¹ na równych prawach? Ta kobieta jest zdecydowanie za g³upia. Wyrzuæ to na ulicê.}
{318} {} {W takim razie pamiêtaj, m³ody adepcie w¹tpliwego kultu, ¿e w tym mieœcie wielu ma urazê do wyznawców.}
{319} {} {Dlaczego?}
{320} {} {Przez pierwsz¹ rewolucjê, która doprowadzi³a Aarona do w³adzy. A potem ta masowa inkwizycja, zorganizowana przez tego w³adcê w celu wzmocnienia jego w³adzy. Ludzie którzy tu ¿yj¹ szybko nie zapominaj¹. Ci, których szukasz, s¹ dobrze zorganizowani i wyposa¿eni w dobr¹ broñ. Nie szczêdz¹ kapsli i nie boj¹ siê wystêpowaæ przeciwko w³adzy. Nie s¹ zwyk³ymi rabusiami ani najemnikami.}
{321} {} {Rozs¹dna uwaga. Powinienem o tym pomyœleæ.}
{322} {} {Dobrze zorganizowani i uzbrojeni. Tak jak twoje kasyno... Nie, nie, o nic Ciê nie oskar¿am. Zegnaj Don Diego.}