{100} {} {Widzisz kobietê Diego.}
{101} {} {Widzisz jedn¹ z ¿on Don Diego.}

{110} {} {Na co sobie pozwalasz?}
{111} {} {Nie mamy tu dla ciebie miejsca.}
{112} {} {Jeœli m¹¿ siê dowie, wszyscy bêdziemy mieli problemy.}
{113} {} {Lepiej siê st¹d wynoœ.}
{114} {} {Diego nie ucieszy siê z twojej obecnoœci.}
{115} {} {Jeœli masz interes z Diego, to idŸ do niego.}

{1110} {} {Nawet nie licz na bycie jedn¹ z nas.}
{1111} {} {Kochanie, to miejsce jest zajête.}
{1112} {} {Ty te¿ jesteœ w naszej rodzinie?}
{1113} {} {Lepiej siê st¹d wynoœ.}
{1114} {} {Nie bêdziemy tolerowaæ nowych konkurentek.}
{1115} {} {Diego jest mój. Nawet nie marz o tym, ¿eby dzieliæ z nim ³ó¿ko.}

{120} {} {Nie wiemy, co teraz zrobiæ.}
{121} {} {Diego by³ naszym patronem.}
{122} {} {Bez mê¿a wokó³ nas rozpoczê³a siê prawdziwa wojna.}
{123} {} {Po œmierci Diego wszyscy wydawali siê byæ wolni.}
{124} {} {Och, Diego... Kto œmia³ podnieœæ na Ciebie rêkê?}