{100} {} {Widzisz Gonzaleza.}
{101} {} {Widzisz handlarza narkotyków.}
{102} {} {Diler podniós³ ceny swoich towarów.}
{103} {} {Otrzymujesz zni¿kê na artyku³y sprzedawcy.}
{104} {} {Uwa¿aj na to dziecko. Masz powa¿ne k³opoty.}

#Pierwsze spotkanie
{200} {} {Hej stary, wygl¹dasz jak milion. Chcesz spêdziæ czas w tym mieœcie, zanim Fortuna siê odwróci?}
{1200} {} {Hej kochanie, wygl¹dasz jak milion. Chcesz spêdziæ czas w tym mieœcie, zanim Fortuna siê odwróci?}
{201} {} {Co dok³adnie sugerujesz?}
{202} {} {Ró¿nego rodzaje przyjemnoœci. Po prostu weŸ tê pigu³kê, a poczujesz dreszczyk emocji, jakiego nie daje ¿adna gra hazardowa. Wiem o czym mówiê. Sprawdzi³em to na sobie.}
{203} {} {Wiêc sprzedajesz narkotyki czy coœ?}
{204} {} {W¹tpiê, czy mo¿esz mi zaoferowaæ coœ wartoœciowego.}
{205} {} {Oczywiœcie, oczywiœcie, cokolwiek powiesz, ch³opcze. Ale zaufaj mi, rezygnujesz z ostatniej przyjemnoœci w tym kiepskim œwiecie.}
{206} {} {Przyjemnoœæ? No có¿, od tego powinniœmy byli zacz¹æ.}
{207} {} {Co próbujesz mi sprzedaæ?}
{208} {} {Nie wiem, co masz na myœli. Mam doskona³e czyste stymulanty i mentaty. Kto by nazywa³ to narkotykiem? Pytanie brzmi, jak dobrze to wykorzystasz. Ale to (mruga) nie jest ju¿ moj¹ spraw¹.}
{209} {} {Wszystko jest dla mnie jasne.}

# Powtarzajacy siê dialog
{210} {} {Czeœæ. Potrzebujesz czegoœ?}
{211} {} {Ach, mój sta³y klient. Jestem do twoich us³ug.}
{212} {} {Chcesz wiêcej?}
{213} {} {Szukasz kolejnej dawki?}
{214} {} {Jesteœ zadowolony z ostatniej partii? Zrobiê dla Ciebie wiêcej.}
{215} {} {Wiedzia³em, ¿e wrócisz. Jak wysoko zamierzasz dzisiaj polecieæ?}

{216} {} {Do zobaczenia.}
{217} {} {Do widzenia.}
{218} {} {Nie mów za du¿o. Do zobaczenia.}
{219} {} {Nie widzieliœmy siê. Czeœæ.}

# Szorstka odpowiedŸ i walka
{220} {} {Pos³uchaj uwa¿nie, estupida. Za mn¹ s¹ ludzie, którzy * s¹ w³aœcicielami * tego obszaru. Kim jesteœ, aby ustalaæ tutaj w³asne zasady? Myœlisz, ¿e tak po prostu to zostawi¹? Nie rób ha³asu, w przeciwnym razie wyst¹pi¹ problemy.}
{221} {} {Nie obchodzi mnie to, i tak umrzesz.}
{222} {} {Przepraszam, to by³o g³upie. Nie ma problemu, brachu.}
{223} {} {Koleœ, denerwujesz siê. Uspokój siê, w przeciwnym razie zawo³am moich ludzi.}
{1223} {} {Panienko, denerwujesz siê. Uspokój siê, w przeciwnym razie zawo³am moich ludzi.}
{224} {} {No dalej, suko! Daj spokój!}
{225} {} {Przepraszam, nie musisz nikogo wo³aæ. Ju¿ siê uspokajam.}
{226} {} {Wypad! Die pendejo!}
{1226} {} {Wypad! Die pendeja!}
{227} {} {Zgiñ, pedale!}
{228} {} {Musisz siê uspokoiæ.}

#Zapytania
{230} {} {Wiêc jaki rodzaj leków sprzedajesz?}
{231} {} {Czego chcesz? Powiedz, mogê dostaæ œrodek pobudzaj¹cy, antyrady lub... (mruga) coœ powa¿niejszego. To jak?}
{232} {} {Bêdê pamietaæ. Do zobaczenia.}
{233} {} {A sk¹d masz ca³¹ t¹ chemie?}
{234} {} {Powa¿nie? A masz wygrzew i psycho?}
{235} {} {Przepraszam, ale czciciele ognia zabronili mi handlu takim produktem. Sami kupuj¹ wszystkie wojskowe narkotyki.}
{236} {} {Ale dlaczego mieliby chcieæ starych wojskowych narkotyków?}
{237} {} {Chowaj¹ siê za opiek¹ nad mieszkañcami miasta... S³uchaj, naprawdê nie wiem, dlaczego tego potrzebuj¹, ale nie chcê ³amaæ zasad. Jednak... (zwraca siê szeptem)}
{238} {} {Tak?}
{239} {} {Mam wiele po³¹czeñ. Za skromn¹ op³at¹ w wysokoœci 100 kapsli mogê zostaæ twoim osobistym sprzedawc¹. Ale to musi pozostaæ miêdzy nami. Kapujesz?}
{240} {} {Przemyœlê Twoj¹ propozycjê.}
{241} {} {Jesteœ zagro¿eniem dla spo³eczeñstwa. Musisz zostaæ pilnie zlikwidowany.}
{242} {} {Nie tak szybko. Najpierw powiedz mi, sk¹d masz ca³¹ t¹ chemie?}
{243} {} {Oto kapsle. Teraz poka¿ wszystko, co ukrywasz przed zwyk³ymi klientami.}
{244} {} {Ju¿ to przerabialiœmy. Wiêc potrzebujesz trochê gówna, czy nie?}
{245} {} {Nie, nie dzisiaj.}
{246} {} {Swoj¹ drog¹, sk¹d bierzesz t¹ chemie?}
{247} {} {Jestem zwolennikiem. Czy chcesz, aby Katedra dowiedzia³a siê o twoich oszustwach? Mogê to za³atwiæ.}
{248} {} {Czekaj, nie œpiesz siê! Dlaczego tak ostro? Zawsze mo¿emy siê dogadaæ.}
{249} {} {W takim razie nie mogê siê doczekaæ pe³nej obs³ugi.}
{250} {} {S-s³uchaj, potrz¹œnij mn¹. Nie przerywaj i dawaj mi towar!}
{251} {} {Potrzebujê jakiegoœ gówna, ¿eby wygrywaæ walki na arenie.}
{252} {} {Zapomnij o tym. Kultyœci maj¹ teraz du¿e problemy, nie maj¹ czasu na twoje pierdo³y.}
{253} {} {Szczerze, zainteresowa³ mnie twój produkt.}
{254} {} {Trzymaj siê z dala ode mnie.}
{255} {} {Orris radzi³ mi siê z tob¹ skontaktowaæ.}
{256} {} {Poka¿ mi, co masz.}

{260} {} {Cholera, mam to, czego potrzebujesz. Nie martw siê, teraz poczujesz siê dobrze...}
{261} {} {Ugh, oczy mi wariuj¹. Teraz bêdê wiedzia³, gdzie kupiæ coœ czego potrzebujê.}
{262} {} {Inna sprawa. Ale nie mów nikomu. To bêdzie nasz ma³y sekret.}
{263} {} {Nie widzê sensu. Nie potrzebujê stron trzecich do sprzeda¿y.}
{264} {} {Wrócê póŸniej.}
{265} {} {Jesteœ po prostu g³upcem. Bywaj.}
{266} {} {Wiêc z³amiê ci palce.}

{270} {} {Sk¹d masz ca³¹ t¹ chemie?}
{271} {} {Oczywiœcie z ró¿nych miejsc. Kupujê coœ od padlino¿erców, coœ od karawan z po³udnia, a niektóre przygotowujê sam na piecu. Nie martw siê, wszystko jest sterylne.}
{272} {} {To nie brzmi zbyt wiarygodnie, wiesz?}
{273} {} {Uspokój siê. Chemia jest prawie wolna od zanieczyszczeñ. Nie znajdziesz lepszego towaru w mieœcie... Z wyj¹tkiem byæ mo¿e u Wyznawców Ognia. Ale oni nie udostêpniaj¹ nikomu swoich zapasów.}
{274} {} {Jakie bzdury sprzedajesz?}
{275} {} {Prawie? Potrzebujê * naprawdê * wysokiej jakoœci leków.}
{276} {} {Mówiê ci, mam najlepsz¹ chemie. Jeœli mi nie ufasz, wynoœ siê st¹d.}
{277} {} {Ok, ok, wychodzê...}
{278} {} {Spróbuj byæ dla mnie niemi³y jeszcze raz - a zostaniesz bez zêbów.}
{279} {} {Potrzebujê * naprawdê * dobrego towaru. Od tego zale¿y ¿ycie moich pacjentów.}
{280} {} {Wiêc jesteœ lekarzem? By³o tak od razu. Lekarzy w naszych czasach mo¿na policzyæ na jednej rêce, cieszê siê z ka¿dego takiego spotkania. Nie martw siê, dam ci wszystko, co najlepsze. A tak¿e ze zni¿k¹.}
{281} {} {Dziêki kolego, to mi bardzo pomo¿e.}
{282} {} {Inna sprawa.}
{283} {} {To i tak jest zbyt w¹tpliwe. Wychodzê.}
{284} {} {Jestem od Murphy'ego. Potrzebujê lekarstwa na wieczny sen.}
{285} {} {Nie wiem, dlaczego tego chcesz i nie chcê wiedzieæ. Ale mam truciznê z ogona radskorpiona i ró¿ne leki do przedawkowania. Wybierz, na co masz wystarczaj¹co du¿o kapsli.}
{286} {} {Zobaczmy...}
{287} {} {Ale jeœli ktoœ zapyta, nie mam z tym nic wspólnego.}
{288} {} {Ok.}

{290} {} {Jak siê nazywasz?}
{291} {} {Mów mi Gonzalez.}
{292} {} {W¹tpiê, ¿eby to by³o twoje prawdziwe imiê.}
{293} {} {Ha. Jaki wgl¹d. Ale co to za ró¿nica?}
{294} {} {Ale po co robiæ z tego tak¹ tajemnicê?}
{295} {} {S¹ tacy, którzy nie lubi¹ mojej dzia³alnoœci. Na przyk³ad menad¿erzy zawodników. Albo ci sekciarze z Katedry. Chc¹ oczyœciæ ca³¹ poda¿ narkotyków dla siebie, a dealerzy tacy jak ja zarabiaj¹ grosze. Bardziej op³aca mi siê pracowaæ dla siebie, ale nie da siê im tego wyt³umaczyæ.}
{296} {} {Jeœli nie od Obserwujacych, to sk¹d bierzesz narkotyki?}
{297} {} {Praca dla siebie w takim miejscu jak to jest ryzykowna.}
{298} {} {Cholera. Czy znasz Czerwonych Kardyna³ów? Zwykle przesiaduj¹ w starym budynku klubu sportowego. Orris jest ich liderem. Dba o to, zeby nic nie przeszkadza³o mi w biznesie. Oczywiœcie nie za darmo.}
{299} {} {Cholera. Kiedyœ by³em ochraniany przez ch³opaków Orrisa. Ale jego œmieræ mocno uderzyla w moj¹ dzialalnosc. Nie wiem, jak teraz prze¿yjê.}

# Uzalezniony zgin¹³ z r¹k GG
{300} {} {Mówi¹, ¿e zabi³eœ Larry'ego. Dlaczego, do diab³a, zabijasz moich klientów?}
{301} {} {Pozbywam siê ze œwiata œmieci. Jakieœ problemy?}
{302} {} {Wiêc rób to gdzie indziej! Larry by³ szumowin¹, ale mia³ okresy objawienia. W takich momentach udawa³o mu siê zarobiæ kapsle, a nastêpnie wydaæ je na now¹ partiê narkotyków. Mia³em z niego niez³e dochody, wiesz? A co bêdê mia³ z zimnych zw³ok?}
{303} {} {Uch, co?}
{304} {} {Nie obchodzi mnie to.}
{305} {} {Um... Pamiêtaj, to bêdzie drogo ciê kosztowaæ. Odbiorê utracone zyski z naszych transakcji.}
{306} {} {Wiêc teraz nie mogê liczyæ na rabat? Przykro mi to s³yszeæ.}
{307} {} {I tak nie zamierzam robiæ zakupów w twoim w¹tpliwym sklepie. Bywaj.}
{308} {} {Przepraszam, to siê sta³o przez przypadek.}
{309} {} {Przepraszam? Zabi³eœ mojego klienta i mówisz PRZEPRASZAM?! Ty draniu, myœlisz, ¿e zostawiê to tak ³atwo?}
{1309} {} {Przepraszam? Zabi³aœ mojego klienta i mówisz PRZEPRASZAM?! Ty draniu, myœlisz, ¿e zostawiê to tak ³atwo?}
{310} {} {Uch, tak.}
{311} {} {O co chodzi, chcesz siê biæ?}
{312} {} {To nasza sprawa.}
{313} {} {(mru¿¹c oczy) Jaki interes móg³byœ mieæ z Larrym?}
{314} {} {To nie twoja sprawa.}
{315} {} {Jeœli ci powiem, te¿ bêdê musia³ ciê zabiæ.}
{316} {} {Cholera, nienawidzê, gdy ktoœ odbiera mi klientów.}
{317} {} {Masz na myœli tego æpuna... jak on siê ma... Larry?}
{318} {} {Larry. Chocia¿ by³ szumowin¹, mia³ okresy objawienia. W takich momentach udawa³o mi siê zarobiæ na nim ³adne kapsle. Co bêdê mia³ teraz?}
{319} {} {Nie mo¿na d³ugo zarabiaæ na czyimœ problemie. Pomyœl o tym.}

{320} {} {Ludzie, którzy zabrali twój motocykl pochodz¹ z gangu Czerwonych Kardyna³ów i ten gang jest praktycznie w³aœcicielem tego obszaru. Jeœli zdenerwujesz jednego z nich, nie po¿yjesz d³ugo. Ale wszystko zale¿y oczywiœcie do Ciebie.}
{321} {} {Bêdê o tym pamietaæ.}
{322} {} {Mam dla ciebie paczkê od Niebieskich Tarcz.}
{323} {} {Wreszcie. ChodŸ tu. Ju¿ chwilê czekam. Czy wiesz, jak trudno jest zdobyæ wêglowodory?}
{324} {} {Ech, jak?}
{325} {} {Niewa¿ne. Tutaj, weŸ gotowy produkt. I powiedz swoim przyjacio³om, ¿e czciciele ognia patroluj¹ teren i utrudniaj¹ robienie interesów.}
{326} {} {Do widzenia.}
{327} {} {By³ problem z ostatnim kurierem. Sam wiesz, jak trudno jest przekroczyæ dziesi¹t¹ autostradê.}
{328} {} {No tak. Ale jak mo¿emy robiæ interesy bez surowców, durniu? Ok, oto gotowy produkt. Oddaj Ryo, niech zajmie siê kurierem, zanim czciciele ognia zamkn¹ mój sklep.}
{329} {} {Do widzenia.}

{330} {} {Czy to ty dostarczasz Larry'emu narkotyki?}
{331} {} {Jeœli nie ja, to ktoœ inny. Co z tym zrobisz?}
{332} {} {Masz racjê. Nic.}
{333} {} {Wiêc nie wtykaj nosa w sprawy innych ludzi.}
{334} {} {No dobrze...}
{335} {} {Mieszkañcy domu s¹ z tego niezadowoleni.}
{336} {} {Pozwól im zrozumieæ, ¿e to nie mój problem, to problem Larry'ego. Sprzedajê mu tylko lekarstwa.}
{337} {} {Lekarstwa? Naprawdê?}
{338} {} {Wiesz, mia³ gor¹czkê z choroby pustkowi. Wiêc zwróci³ siê do mnie o leki. Jak mo¿na odmówiæ pilnej pomocy potrzebuj¹cemu?}
{339} {} {Jak mi³o z twojej strony. Pa, doktorze.}
{340} {} {Jeœli sprzedasz mu jeszcze jedn¹ dawkê, masz du¿e k³opoty.}
{341} {} {Co powiedzia³eœ? Powtórz, kretynie, mo¿e siê przes³ysza³em?}
{1341} {} {Co powiedzia³aœ? Powtórz, suko, mo¿e Ÿle us³ysza³em?}
{342} {} {Uh, musimy siê trochê uspokoiæ. Do widzenia mój przyjacielu.}
{343} {} {Powtórzê to tylko raz. Przestañ drêczyæ Larry'ego. Albo umrzesz.}
{344} {} {Przepraszam, Ÿle zrozumia³em. Oczywiœcie Larry nie dostanie ode mnie ani jednej dawki. Nie ma problemu.}
{345} {} {Dopilnujê tego.}
{346} {} {Niem¹drze. K³óciæ siê ze mn¹ to to samo, co k³óciæ siê z Orrisem.}
{347} {} {Och, jesteœ jednym z kardyna³ów? Teraz, uh, bêdê wiedzia³. Po prostu, uh, nie nadwerê¿aj siê, przyjacielu.}
{348} {} {Zgadza siê.}
{349} {} {Larry jest teraz pod moj¹ ochron¹. A wiêc pod auspicjami samego Don Diego.}
{350} {} {W ka¿dej chwili mogê powiedzieæ Aaronowi o twojej dzia³alnoœci. Masz szczêœcie, ¿e jeszcze tego nie zrobi³em.}
{1350} {} {W ka¿dej chwili mogê powiedzieæ Aaronowi o twojej dzia³alnoœci. Masz szczêœcie, ¿e jeszcze tego nie zrobi³am.}