{100} {} {Widzisz mieszkañca Phoenix.}
{101} {} {Widzisz zwyk³ego mieszkañca Phoenix. Wydaje siê spiêty i wyraŸnie na kogoœ czeka.}
{102} {} {IdŸ swoj¹ drog¹.}

{200} {} {Gdzie siê œpieszysz, kultysto? Zdecydowa³eœ siê uciec z miasta? Dobra decyzja. Pomogê Ci.}
{201} {} {Naprawdê? To takie mi³e...}
{202} {} {Mylisz mnie z kimœ innym.}
{203} {} {Wiem, ¿e czcisz ogieñ. I wiesz co? Nie bêdziemy d³u¿ej tolerowaæ tej waszej "nuklearnej magii" tutaj. Wynoœ siê z miasta, szumowino.}
{204} {} {Nie, nie, nie nale¿ê ju¿ do tej sekty.}
{205} {} {Zamknij siê! Po eksplozji w katedrze po³owa miasta zosta³a zniszczona, a wœród ludzi wybuch³a prawdziwa wojna. Nie spoczniemy, dopóki w mieœcie nie pozostanie ani jeden sekciarz, ani czynny ani dawny. Czy to dla ciebie jasne?}
{206} {} {Tak, rozumiem.}
{207} {} {A teraz wynoœ siê z miasta. Jeszcze raz siê spotkamy i jesteœ trupem.}
{208} {} {Uch...}
{209} {} {Nie, nie rozumiem. Wyjaœnij jeszcze raz, g³upku.}
{210} {} {Wyjaœniê wszystko raz jeszcze, szumowino...}
{211} {} {Co robisz... przestañ...}
{212} {} {Atakujcie pojedyñczo, ch³opaki.}
{213} {} {Czekajcie. Jestem z wami. To dziêki mnie koœció³ wylecia³ w powietrze.}
{214} {} {Co... Robisz ze mnie g³upka? Nikt w to nie uwierzy.}
{215} {} {Naprawdê. Ci kultyœci sponsorowali handlarzy niewolników, którzy porwali moj¹ rodzinê. Eksplozja by³a odwetem.}
{216} {} {Tak... Bo uwierzê. Jeœli to prawda, to na twoim sumieniu jest zniszczenie ca³ego Phoenix. Myœlisz, ¿e to powinno nas zadowoliæ? Wynoœ siê z miasta. Wrócisz - i jesteœ trupem. Czy to dla ciebie jasne?}
{217} {} {Nie ma problemu. Nie zobaczysz mnie ponownie.}
{218} {} {Nie musisz mi groziæ. W przeciwnym razie bêdzie o jednego trupa wiêcej.}
{219} {} {Nie obchodzi mnie, w co wierzysz.}
{220} {} {Ten debil nie wydaje siê rozumieæ ludzkiego jêzyka. Musimy mu to wyjaœniæ piêœciami...}
{1220} {} {Ta suka nie wydaje siê rozumieæ ludzkiego jêzyka. Bêdziemy musieli jej to wyjaœniæ brutaln¹ si³¹...}
{221} {} {Tylko b¹dŸcie delikatni...}
{222} {} {To twój ostatni b³¹d.}
{223} {} {Grozisz mi. A ci, którzy mi grozili, bardzo szybko koñczyli swoje ¿ycie.}

{230} {} {Hej, ty. Twoja spalona skóra.}
{231} {} {Tak? Co z ni¹?}
{232} {} {Kto ciê takiego stworzy³? S³ysza³em, ¿e pod katedr¹ przeprowadzane s¹ eksperymenty maj¹ce na celu stworzenie elitarnych wojowników. I w³aœnie widziano ciê w katedrze.}
{233} {} {To jakieœ nieporozumienie. Jestem tylko ofiar¹ promieniowania i szuka³em lekarstwa w katedrze.}
{1233} {} {To jakieœ nieporozumienie. Jestem tylko ofiar¹ promieniowania i szuka³am lekarstwa w katedrze.}
{234} {} {Mo¿e... Szukamy resztek kultystów, aby wypêdziæ ich z miasta. Dlatego nie krêæ siê przy nich.}
{235} {} {Oczywiœcie, teraz bêdê uwa¿aæ.}
{236} {} {Hmm... (patrzy w górê i w dó³, wyra¿aj¹c nieskrywan¹ odrazê) mo¿esz iœæ.}
{237} {} {...}
{238} {} {Trudno jest siê ukryæ osobie z moj¹ twarz¹. Co masz przeciwko czcicielom ognia?}
{239} {} {Eksterminujemy wszystkich kultystów w mieœcie. Po eksplozji w katedrze nie maj¹ tu miejsca. Ty te¿.}
{240} {} {Dlaczego jesteœ taki niemi³y? Czy czciciele ognia nie nauczyli ciê cierpliwoœci i mi³oœci?}
{241} {} {Mo¿e s³owami. Ale oni sami przygotowywali bombê atomow¹ w swoim ciemnym lochu. Nie ma ju¿ takiej wiary... W ka¿dym razie nie jesteœ tutaj mile widziany. Wynoœ siê z miasta, atomowy œmieciu.}
{242} {} {Nie mogê siê z tob¹ k³óciæ. Powodzenia ch³opaki.}
{243} {} {Mówi¹c to, wyrwê ci oczy i wyssê mózg z twojej stygn¹cej czaszki.}
{244} {} {Ta biedna istota nie wydaje siê rozumieæ ludzkiego jêzyka. Ch³opaki...}
{245} {} {Och, bez przemocy...}
{246} {} {Wszyscy nienawidzicie ghuli, wszyscy jesteœcie tacy sami.}
{247} {} {Dok³adnie. Jestem ofiar¹, a nie sekciarzem.}
{248} {} {Nie wierzê ci. Ch³opaki, nie pozwólcie mu uciec...}
{1248} {} {Nie wierzê ci. Ch³opaki, nie pozwólcie jej uciec...}
{249} {} {Tylko nie w twarz...}
{250} {} {Mo¿e tak... Dobra, idŸ. Ale jeœli dowiemy siê, ¿e jesteœ czcicielem ognia, razem z reszt¹ spalisz siê na stosie.}

{260} {} {Stop. Nie chcê wdawaæ siê w bójkê, ale muszê to powiedzieæ. Wiemy, ¿e jesteœ jednym z by³ych czcicieli ognia. W tym mieœcie nie s¹ oni ju¿ mile widziani. OdejdŸ i nie wracaj. Jeœli wrócisz, ca³a ta amunicja nie uchroni ciê przed nasz¹ zemst¹.}
{261} {} {Rozumiem. Ju¿ mnie nie zobaczysz. Do widzenia.}
{262} {} {Nigdzie nie idê. Kto odwa¿y siê mnie powstrzymaæ?}
{263} {} {(patrzycie na siebie nerwowo) Nie chcemy rozlewu krwi. Nie ma jeszcze koniecznoœci siêgaæ po broñ. Ale jeœli zajdzie taka potrzeba, za³atwimy to. Zeby ciê tu jutro nie by³o.}
{264} {} {Nie tak szybko. Czy ci siê to podoba, czy nie, walka odbedzie siê teraz.}
{265} {} {Mylisz mnie z kimœ innym.}
{266} {} {Naprawdê? Nie s¹dze. Wynoœ siê z miasta. Nie chcemy walczyæ, ale w razie potrzeby bêdziemy.}
{267} {} {Nie obchodzi mnie to. Walczmy.}
{268} {} {Pomyœlê o twoich s³owach.}