{100} {} {Widzisz oszusta.}
{101} {} {Widzisz zwyk³ego bandytê. Jest bardzo zdeterminowany.}
{102} {} {Ok! Wychodzimy! W porz¹dku, nie rozgrzewaj siê!}

{110} {} {Gdzie idziesz? Wynoœ siê, to jest teraz nasze terytorium.}
{111} {} {Wiesz tylko, jak przestraszyæ. Udowodnij, ¿e masz prawo do posiadania tego miejsca, œmieciu.}
{112} {} {Och, przepraszam...}
{113} {} {Proszê odejdŸ, miejscowi nie chc¹ k³opotów...}
{114} {} {W takim razie ich unikaj! Rozumiesz? Wynoœ siê, kretynie, póki twoje nogi s¹ ca³e i zdrowe!}
{115} {} {Jesteœ na terytorium kardyna³ów. Nie toleruj¹ tu konkurentów. OdejdŸ.}
{116} {} {Kardyna³owie robili to ju¿ od d³u¿szego czasu. Rozumiesz?}
{117} {} {Niewa¿ne. Teraz ja uporz¹dkujê wszystko tutaj. Radzê odejœæ!}
{118} {} {Kardyna³owie nadal rz¹dz¹ tym obszarem. OdejdŸ.}
{119} {} {kwi! (uœmiecha siê, macha piêœciami i cofa siê do wyjœcia)}
{120} {} {Tak, wypad na zewn¹trz. I nie wracajcie, kretyni...}
{121} {} {Ch³opaki, tu jest 100 kapsli. Tylko mnie nie dotykajcie, dobrze?}
{122} {} {Widzisz. Potrzebna by³a tylko MOTYWACJA. Do zobaczenia w przysz³ym miesi¹cu, kretynie.}
{123} {} {Tak, do widzenia...}
