{100} {} {Widzisz uchodŸcê z Flagpool.}
{101} {} {Widzisz uchodŸcê w zakurzonym ubraniu. Wygl¹da na to, ¿e pokona³ w nim du¿e odleg³oœci, zanim tu dotar³.}
{102} {} {* Wracam *}
{103} {} {Dziêki, ratujesz mnie przed œmierci¹ g³odow¹.}
{104} {} {Nawet nie wa¿ siê do mnie zbli¿aæ, zboczeñcu.}
{1104} {} {Nie wa¿ siê do mnie zbli¿aæ, zboczeñcu.}
{105} {} {Co tu siê dzieje?!}

{110} {} {Dlaczego nam to robisz?}
{111} {} {Znamy siê od dzieciñstwa.}
{112} {} {Obiecujê, ¿e znajdê kapsle, poczekaj chwilê.}
{113} {} {Wiem, jak zarobiæ na czynsz.}
{114} {} {Nie mam teraz czym p³aciæ, ale to nie potrwa d³ugo.}
{115} {} {Daj mi szansê, zarobiê kapsle.}
{116} {} {Mówiê ci - ZNAJDE pracê.}
{117} {} {S³uchaj, nie chcê z tob¹ walczyæ.}
{118} {} {To jest to, niektórzy ludzie nadal maj¹ pretensje, co?}
{119} {} {Pozwól mi zostaæ przynajmniej na jedn¹ noc.}

{200} {} {...Jak mo¿esz? Kiedyœ by³eœ dla nas mi³y. A teraz jesteœmy dla ciebie ludŸmi z ulicy, co?}
{201} {} {Co tu siê dzieje?}
{202} {} {Ten arogancki dupek eksmituje nas, starych przyjació³. Nie mamy wystarczaj¹cej liczby kapsli na czynsz. Ale to jest tymczasowy problem, dopóki nie znajdziemy pracy.}
{203} {} {Wiêc przybyliœcie z daleka?}
{204} {} {W³aœciwie jesteœmy lokalnymi mieszkañcami, ale pracujemy w Flagpool od kilku lat. Po zamkniêciu tam kopalni uranu wielu straci³o pracê, a w mieœcie wybuch³y zamieszki. Musieliœmy wracaæ. Podró¿ by³a trudna, a kapsle szybko siê skoñczy³y.}
{205} {} {Wszystko kiedyœ siê koñczy.}
{206} {} {Smutna historia.}

{210} {} {Hej, mo¿esz po¿yczyæ nam dziesiêæ kapsli? Szczerze mówi¹c, zwrócê to, gdy tylko je zarobiê.}
{211} {} {Te¿ mam problemy z kapslami, przepraszam.}
{212} {} {Tak, oczywiœcie ka¿dy ma swoje problemy. Nic, jakoœ to rozgryzê.}
{213} {} {Do widzenia.}
{214} {} {Wygl¹da na to, ¿e naprawdê potrzebujecie kapsli. Proszê, weŸcie to.}
{215} {} {Ok, proszê bardzo.}
{216} {} {Naprawdê? (szybko chowa kapsle) Och, dziêkujê, dobry cz³owieku. Jak masz na imiê?}
{217} {} {To nie ma znaczenia. W ten sposób staram siê odpokutowaæ za grzechy z przesz³oœci. Do widzenia.}
{218} {} {Nazywam siê }
{219} {} {. Zapamiêtaj to imiê. I opowiedz o mnie swoim dzieciom.}

{220} {} {Dam ci 35 kapsli za ma³¹ przys³ugê. Widzisz, potrzebujê trochê „odpoczynku w ³ó¿ku”.}
{221} {} {(Z przygnêbieniem patrzy na partnera)}
{222} {} {Co powiesz?}
{223} {} {Ok, zapomnij. Tylko ¿artowa³em.}
{224} {} {Zosta³o mi jeszcze trochê dumy. Nawet nie wa¿ siê tego proponowaæ, kretynie!}
{225} {} {Hej, spokojnie.}
{226} {} {Mieszkaj¹c w kolonii, nigdy bym nie pomyœla³a, ¿e bêdê musia³a zarabiaæ w ten sposób.}
{227} {} {Kiedyœ musi byæ ten pierwszy raz. Porusz biodrami, teraz znajdziemy ustronne miejsce.}
{228} {} {Przepraszam, to by³ z³y pomys³. Zapomnij o tym, po prostu odejdê...}
{229} {} {(po godzinie brudnej przemocy wstajesz z ³ó¿ka z satysfakcj¹ i patrzysz na bezw³adne cia³o poni¿ej; podnosisz ko³drê i po cichu rzucasz je na brudne przeœcierad³o; kobieta odwraca siê i zaczyna cicho szlochaæ)}
{230} {} {[wyjdŸ]}