{100} {} {Przed sob¹ widzisz ducha!}
{101} {} {Widzisz... duszê mê¿czyzny spalonego w p³omieniu nuklearnym.}

{102} {} {Co to do cholery jest?}
{103} {} {To nie by³o prawdziwe, prawda?}
{104} {} {Chyba tracê rozum... czy nie?}
{105} {} {Te dusze s¹ wszêdzie!}

{110} {} {Zobacz, co zrobi³eœ!}
{111} {} {To twoja wina!}
{112} {} {Dlaczego nam to zrobi³eœ?}
{113} {} {Dlaczego nas zabi³eœ?}
{114} {} {Bêdziemy ciê przeœladowaæ przez ca³e ¿ycie.}
{115} {} {Morderca!}

{1110} {} {Zobacz, co zrobi³aœ!}
{1111} {} {To twoja wina!}
{1112} {} {Dlaczego nam to zrobi³aœ?}
{1113} {} {Dlaczego nas zabi³aœ?}
{1114} {} {Bêdziemy ciê przeœladowaæ przez ca³e ¿ycie.}
{1115} {} {Morderca!}
