{100} {} {Przed sob¹ widzisz ulicznego z³odzieja.}
{101} {} {Widzisz z³odzieja.}
{102} {} {Widzisz przechodnia w zwyk³ym ubraniu. NajwyraŸniej nie chce zwracaæ na siebie uwagi.}
{103} {} {Widzisz ulicznego z³odzieja. Lepiej nie wchodziæ mu w drogê.}
{104} {} {Czy ty mnie œledzisz?}
{105} {} {Z³odziej tchórzliwie uciek³.}

#Dialog
{200} {} {(Id¹c ulic¹, zauwa¿asz, ¿e jesteœ obserwowany. Przez chwilê m³ody mê¿czyzna w skrytym ubraniu pod¹¿a za tob¹ niepewnie. Kiedy wchodzisz w opuszczon¹ uliczkê, podbiega i wyci¹ga coœ co wygl¹da jak pistolet.)}
{201} {} {[Dalej.]}
{202} {} {Stój! Dawaj mi swoje kapsle albo strzelê.}
{203} {} {Hej, spokojnie...}
{204} {} {Kapsle! Zwawo! Albo przysiêgam, ¿e strzelê! (patrz¹c przez ramiê, badasz przeciwnika: jego twarz jest zakryta chustk¹...)}
{205} {} {Kapsle! Ju¿!}
{206} {} {Spróbuj je zdobyæ, suko.}
{207} {} {Co... Mam broñ. I jest za³adowana. Rozumiesz? Nie ka¿ mi strzelaæ.}
{208} {} {Wiêc strzelaj. Atakujê!}

{210} {} {Oto 30 kapsli, tylko nie strzelaj.}
{211} {} {ChodŸ tutaj. (podnosi kasê i rozgl¹da siê) Teraz idŸ dalej ulic¹. Jeœli siê odwrócisz, jesteœ trupem.}
{212} {} {Cokolwiek powiesz...}
{213} {} {[Odwróæ siê i zaatakuj z³odzieja]}
{214} {} {Mam tylko jednego kapsla. Proszê, weŸ go, nie mam wiêcej.}
{215} {} {Oto dwa kapsle. Ju¿ wiêcej nie mam. Naprawdê.}
{216} {} {Oto trzy kapsle. Ju¿ wiêcej nie mam. Naprawdê.}
{217} {} {Cholera, chodŸ tutaj... Ok. Teraz idŸ dalej ulic¹. Odwrócisz siê - i jesteœ trupem.}
{218} {} {Nie strzelaj. Oto wszystkie kapsle, które mam.}

{220} {} {Nie mam kapsli. Naprawdê.}
{221} {} {Nie wkurzaj mnie suko!}
{222} {} {Naprawdê nie mam kapsli. SprawdŸ moje kieszenie.}
{223} {} {Cholera... (rozgl¹da siê z trudem) Wiêc... IdŸ dalej ulic¹ i nie odwracaj siê.}
{224} {} {Nie zbli¿aj siê albo strzelê!}
{225} {} {Wow, spokojnie.}
{226} {} {Wiêc strzelaj, suko.}
{227} {} {Zmuszasz mnie do skrajnoœci, draniu.}

{230} {} {Hej, jesteœ ch³opcem czy dziewczynk¹?}
{231} {} {Co... Nie wkurzaj mnie, bo strzelê!}
{232} {} {Powa¿nie. Nie mogê do tego dojœæ z powodu tych szmat...}
{233} {} {Jeszcze jedno s³owo i nie ¿yjesz. ZAMKNIJ SIE!}
{234} {} {Uh, mo¿emy porozmawiaæ?}
{235} {} {W takim razie celuj w g³owê. Nie bêdziesz mieæ drugiej szansy.}
{236} {} {Cholera, kim ty jesteœ... (z³odziej denerwuje siê i rozgl¹da siê z trudem) Wiêc... Nie odwracaj siê. Albo strzelê. Powa¿nie, strzelê!}
{237} {} {Oczywiœcie, wierzê ci...}
{238} {} {Wiêc strzelaj, suko, strzelaj!}
{239} {} {Podejmujesz du¿e ryzyko, kochanie. Czy wiesz kim jestem? Niezwyciê¿ony Mario wypad³ mi z r¹k na ringu.}
{240} {} {Cholera... Nie chcê ciê zastrzeliæ... Ok. OdejdŸ i nie ogl¹daj siê za siebie. Jasne?}
{241} {} {Oczywiœcie, ty tu jesteœ szefem.}
{242} {} {Nie tak szybko. Bêdziesz musia³ odpowiedzieæ za swoje s³owa...}
{243} {} {Jak œmiesz atakowaæ spokojnego mnicha? Nuklearny Ogieñ Spustosenia ukarze ciê za to, robaku!}
{244} {} {Jesteœ ¿a³osny. My, w³adcy autostrad, wieszamy ludzi takich jak Ty na znakach drogowych i patrzymy jak zdychaj¹.}
{245} {} {Wiedz, ¿e celujesz do Rangersa. Nawet nie wiesz jak du¿y b³¹d pope³niasz.}
{246} {} {Jeszcze nie teraz, ale staniesz siê trupem.}