{100} {} {Widzisz Lloyda.}
{101} {} {Widzisz ¿ebraka biegn¹cego ulic¹ w poszukiwaniu jedzenia.}
{102} {} {Tacy ludzie tylko zaœmiecaj¹ œwiat.}
{103} {} {Uh, mówisz do mnie, kawa³ku ¿elaza? W tej butelce musia³o byæ coœ jeszcze...}
{104} {} {Oh Lloyd...}

{200} {} {Hej, widaæ, ¿e jesteœ tu nowy. A przybyszom w mieœcie jest ciê¿ko. Chcesz darmowej porady? Pomagaj przyjacio³om, op³aci Ci siê.}
{201} {} {Jak siê nazywasz, kolego?}
{202} {} {Dziwnie jest to us³yszeæ od bezdomnego ¿ebraka.}
{203} {} {Jestem Lloyd. Prosty mieszkaniec ulicy. Ale nie wahaj siê, znam ca³e miasto jak moje cztery palce.}
{204} {} {Przyda³by mi siê znawca Phoenix. Czy mo¿esz odpowiedzieæ mi na kilka pytañ?}
{205} {} {Myœlê, ¿e jesteœ po prostu frajerem. Nie chcê mieæ do czynienia z kimœ takim jak ty. Do widzenia.}
{206} {} {Hej, widzê, ¿e masz du¿o kapsli. Mogê Ci udzieliæ bezp³atnej porady. Podziel siê drobiazgiem, a zyskasz wdziêcznych i lojalnych przyjació³ w tym mieœcie.}
{207} {} {Do widzenia, Lloyd.}
{208} {} {Do zobaczenia, Lloyd.}
{209} {} {Wiesz, nie œpieszy mi siê.}

{210} {} {Podziel siê tym, nie po¿a³ujesz.}
{211} {} {To mój ulubiony klient. Jak mogê pomóc tym razem?}
{212} {} {Innym razem.}

{213} {} {Cholera, to by³o prawdziwe trzêsienie ziemi! Jednak plotki nie k³ama³y, ¿e sekciarze robi¹ bombê atomow¹. Oni s¹ naprawdê szaleni. Teraz ca³e miasto ich znienawidzi³o i mam o jeden sposób mniej na zarabianie pieniêdzy. Ehh...}
{214} {} {Dostali to, na co zas³u¿yli, Lloyd.}
{215} {} {Tak.}

{220} {} {Oto kapsel.}
{221} {} {Tu jest kapsel od butelki. Pocz¹tkuj¹cy potrzebuje porady.}
{222} {} {Tu jest kapsel od butelki. Co mi powiesz tym razem?}
{223} {} {Tu jest kapsel od butelki. Podziel siê interesuj¹cymi plotkami.}
{224} {} {[Dalej.]}
{225} {} {Dziêkujê, senor.}
{1225} {} {Dziêkujê, senora.}
{226} {} {Dziêkujê, senor. Ale rady starego Lloyda ju¿ siê skoñczy³y.}
{1226} {} {Dziêkujê, senora. Ale rady starego Lloyda ju¿ siê skoñczy³y.}
{227} {} {Nic, rozumiem. Teraz jestem tak biedny jak ty. Do zobaczenia.}
{228} {} {Uch, tak, pa.}
{229} {} {Nie dzisiaj. Czeœæ.}

{230} {} {Ach, plotki. Oto jak ¿yjê.}
{231} {} {(rozgl¹da siê) C-có¿...}
{232} {} {Lloyd widzi wszystko z tej ulicy. Zgadza siê.}
{233} {} {Wiesz, du¿o tu s³yszê.}
{234} {} {Swie¿e wiadomoœci? Coœ tam us³ysza³em.}
{235} {} {Tak. Mam dla ciebie kilka rad.}
{236} {} {Hmm... (g³aska niemyty zarost)}
{237} {} {Wiesz, ludzie mówi¹ o...}
{238} {} {(z uœmiechem na ustach) Ach, kapsle, kapsle...}
{239} {} {Dziêkujê bardzo.}

{240} {} {Có¿?}
{241} {} {Kontynuuj.}
{242} {} {Mów.}
{243} {} {[Pos³uchaj]}
{244} {} {[Dalej.]}
{245} {} {Co powiesz?}

{250} {} {Czeœæ. Jak ci siê podobaj¹ moje nowe ubrania? Kupi³em je za twoje kapsle, wiêc dziêki. Czasami wydaje mi siê, ¿e mogê wydostaæ siê z tej dziury i rozpocz¹æ nowe ¿ycie. Chocia¿ kogo ja oszukujê...}
{251} {} {Nie wszystko stracone, Lloyd. Ju¿ nie bêdziesz móg³ upaœæ ni¿ej.}
{252} {} {Ludzie tacy jak ty nie maj¹ przysz³oœci. Nie poradzisz sobie.}
{253} {} {S³uchaj, teraz zarabiam tyle pieniêdzy, ¿e staæ mnie nawet na tak¹ ma³¹ radoœæ. W takim garniturze wszystkie drzwi s¹ dla mnie otwarte. A to dziêki tobie.}
{254} {} {S³uchaj, teraz zarabiam tyle pieniêdzy, ¿e staæ mnie nawet na tak¹ ma³¹ radoœæ. Maj¹c taki garnitur, mogê nawet wprowadziæ siê do apartamentu. Przepraszam, jestem zajêty.}
{255} {} {Cieszê siê, Lloyd.}
{256} {} {Nie mogê w to uwierzyæ. Po prostu masz szczêœcie, nic wiêcej.}

# O schronisku
{260} {} {Czy wiesz coœ o Krypcie 27?}
{261} {} {Niewiele. Za 10 kapsli powiem ci, co wiem.}
{262} {} {W takim razie zapomnij.}
{263} {} {Oto 10 kapsli. Powiedziedz mi co wiesz.}
{264} {} {S³ysza³em ró¿ne legendy o tej kryjówce. Ktoœ powiedzia³, ¿e w³adcy Phoenix za³o¿yli tam tajne laboratorium. A ktoœ - ¿e w Krypcie od dnia wojny nuklearnej mieszkaj¹ prawdziwe duchy. Mo¿e te¿ w ogóle nie istnieæ.}
{265} {} {Przykro mi to s³yszeæ.}
{266} {} {Jeœli masz zamiar sprawdziæ tê legendê, polecam zacz¹æ od Boba-zbieracza. Mieszka w slumsach na wschód st¹d i zna okolice Phoenix jak nikt inny.}
{267} {} {Dziêki, bardzo mi pomog³eœ.}
{268} {} {Jesteœ bezu¿yteczny. Mo¿e przynajmniej ten Bob coœ wie.}

{270} {} {Skala tego miasta jest niesamowita. Ale muszê znaleŸæ swojego krewnego.}
{271} {} {Tak, znalezienie osoby w tak du¿ym mieœcie nie jest ³atwe. Poza tym nie ka¿dy chce byæ znaleziony. Ale jest jedna mo¿liwoœæ. Opowiem ci za 5 kapsli.}
{272} {} {Oto 5 kapsli. Co to za mo¿liwoœæ?}
{273} {} {Mo¿e póŸniej.}
{274} {} {W pobli¿u jest agencja rekrutacyjna. Ka¿dy znajdzie siê za kapsle, nawet sam El Diablo zostanie wyjêty z pod ziemi.}
{275} {} {Dziêki przyjacielu, bardzo mi pomog³eœ.}
{276} {} {I za to poprosi³eœ mnie o piêæ kapsli? Serio, jesteœ oszustem.}
{277} {} {Osobiœcie znam tuzin Miguelów. A jeden z nich to tak naprawdê kobieta. Ale jeœli twój krewny przyjecha³ z daleka, móg³ zmieniæ imiê. Obawiam siê, ¿e nie bêdzie ³atwo go znaleŸæ. Zapytaj gildiê najemników. Tam te¿ szukaj¹ ludzi.}

{280} {} {Co wiesz o ataku na mnichów?}
{281} {} {Ta informacja nie jest tania. Bêdzie ciê to kosztowaæ 20 kapsli.}
{282} {} {W porz¹dku. Trzymaj i powiedz co wiesz.}
{283} {} {Nie, spróbujê znaleŸæ mniej wymagaj¹ce Ÿród³o.}
{284} {} {Przepraszam pana, ale nie handlujê tak niebezpiecznymi informacjami. Porozmawiaj z kimœ na rynku.}
{1284} {} {Przepraszam, senora, ale nie handlujê takimi niebezpiecznymi informacjami. Porozmawiaj z kimœ na rynku.}
{285} {} {Rozumiem.}

# Porady i plotki
{300} {} {Waluta kapsli dzia³a w mieœcie ju¿ od kilku lat. To jak dolary przed Wielk¹ Wojn¹, a Katedra Ognia jest jej gwarantem. To prawda, wielu nadal nie ufa tej idei.}
{301} {} {A propos kapsli. Oto kolejny. A co z przedwojennymi dolarami?}
{302} {} {To jest problem. Zwykle nikt ich nie u¿ywa, ale z jakiegoœ powodu kasyno wykupuje ca³¹ star¹ walutê. Jeœli znajdziesz jakiegoœ, zanieœ go do kasjera, mo¿e da Ci za niego kilka kapsli.}
{303} {} {Czy by³eœ kiedyœ w kasynie Atomic Fever? Warto siê tam zatrzymaæ i wydaæ kilka kapsli, aby oceniæ swoje szanse. Ale nie daj siê zwieœæ szczêœciu. W koñcu, bez wzglêdu na to, jak bardzo siê starasz, kasyno zawsze wygrywa.}
{304} {} {Nawet bez powodzenia w kasynie mogê daæ ci kapsla. A tak przy okazji, kto tam wszystkim kieruje? Mo¿e uda mi siê tam zarobiæ.}
{305} {} {W¹tpiê, czy kasyno przyjmie osobê z ulicy. Maj¹ tam coœ w rodzaju rodziny. A g³owa tej rodziny, Don Diego, jest bardzo wybredna w doborze pracowników. Jeœli chcesz dla niego pracowaæ, musisz najpierw zdobyæ zaufanie jednego z jego popleczników. Lub cieszyæ siê dobr¹ opini¹ w mieœcie.}
{306} {} {Uwa¿aj, gdy znajdziesz siê we wschodnich slumsach. Gang Orrisa rz¹dzi tam wszystkim i wszystkimi, najlepiej z nim nie zadzieraæ.}
{307} {} {Oto kolejny kapsel. Opowiedz mi o tym gangu.}
{308} {} {Orris zebra³ gang Czerwonych Kardyna³ów i u¿ywa ich do ustalania zasad w slumsach. Ale nie jest tak z³ym facetem jak jego ludzie. Jeœli znajdziesz siê na muszce, spróbuj negocjowaæ.}
{309} {} {Pracownicy elektrowni j¹drowej ponownie podnieœli ceny i postawili Aaronowi ultimatum. Nie wiem, kto wygra tê bitwê, ale miastu i tak bêdzie ciê¿ko.}
{310} {} {Dam ci kolejnego kapsla, jeœli bêdziesz móg³ opowiedzieæ mi o okolicy.}
{311} {} {Có¿, wokó³ stacji jest fosa na odpady toksyczne, pu³apki i drut kolczasty. Wiem te¿, ¿e kana³y prowadz¹ bezpoœrednio do stacji. Najprawdopodobniej ona sama te¿ jest usiana pu³apkami na nieproszonych goœci.}
{312} {} {Coœ siê dzieje w Katedrze Ognia. JeŸdzi tam coraz wiêcej karawan, a Aaron staje siê bardziej asertywny i wywiera presjê na mieszkañców miasta.}
{313} {} {Oto kolejny kapsel. Co wiesz o tym Aaronie?}
{314} {} {Niewiele. Mówi¹ o nim inaczej, ale widaæ wyraŸnie, ¿e jest to cz³owiek dominuj¹cy i ma obsesjê na punkcie swoich pomys³ów. Mówi¹ te¿, ¿e siedzi na jakichœ tabletkach, bez których nie mo¿e ¿yæ.}
{315} {} {Ostatnio w kana³ach znajduje siê coraz wiêcej ludzi. Wczeœniej nikt tam nie chodzi³, z wyj¹tkiem squatterów. Ale do tej pory byli nieszkodliwi.}
{316} {} {Oto kolejny kapsel. Opowiedz mi o tych squatterach.}
{317} {} {Dziwni ludzie mieszkaj¹cy w kana³ach. Nie lubi¹ œwiata zewnêtrznego i tylko od czasu do czasu wychodz¹ na powierzchniê, aby wymieniæ zw³oki szczurów na kapsle. Jeœli zdarzy ci siê rozmawiaæ z nimi, radzê po prostu daæ im coœ, czego potrzebuj¹, a to natychmiast rozwi¹¿e ich jêzyki.}
{318} {} {Jeden nieznajomy opowiada³ legendy o jakiejœ kryjówce pe³nej jedzenia i technologii. Ci, którzy zakochali siê w jego opowieœciach i wyszli w poszukiwaniu tego schronienia zniknêli bez œladu.}
{319} {} {Oto kolejny kapsel, jeœli mo¿esz mi powiedzieæ, jak znaleŸæ tego faceta.}
{320} {} {Po prostu znikn¹³. Jeœli interesuje Ciê okolica Phoenix, porozmawiaj z Bobem Zbieraczem we wschodnich slumsach. Ma du¿e doœwiadczenie w grzebieniu w lokalnych ruinach.}
{321} {} {Karawana pocztowa regularnie kursuje do Flagpool. Ta nowa kolonia szybko siê rozwija dziêki patronatowi Katedry Ognia.}
{322} {} {Mówi¹, ¿e w San Brahmin dosz³o do walki. Mówi¹ te¿, ¿e Czciciele Ognia s¹ z tym w jakiœ sposób powi¹zani. Nikt nie wie dok³adnie, co siê tam dzieje.}
{323} {} {Plotki z Casa Grande s¹ prawdziwe - miasto jest rozdzierane ci¹g³¹ walk¹ o w³adzê. Jeden burmistrz zastêpuje drugiego, gdy tylko wzejdzie s³oñcê. Jak bêdziesz w tych stronach, przygotuj siê, ¿e mo¿esz zostaæ oszukany lub wpl¹tany w lokalne k³opoty.}
{324} {} {Kr¹¿y wiele plotek o Blacharzach mieszkaj¹cych na po³udniu. Udaj¹ siê tam karawany, ale niewiele z nich mo¿e handlowaæ z tym tajemniczym ludem.}
{325} {} {Kiedy tylko karawany zaczê³y podró¿owaæ na po³udnie, bandyci natychmiast ustawili siê wzd³u¿ autostrad. Mistrzowie czy w³adcy autostrad, jak sami siebie nazywaj¹, rabuj¹ i zabijaj¹ nieostro¿nych podró¿nych.}
{326} {} {Oto kolejny kapsel. Jak mogê siê ochroniæ po drodze?}
{327} {} {Jeœli boisz siê podró¿owaæ autostradami, masz dwie mo¿liwoœci. Pierwsz¹ jest objazd przez duszn¹ pustyniê. Druga to do³¹czenie do jednej z dobrze bronionych karawan.}