{100} {} {Widzisz W³adcê Phoenix.}
{101} {} {Widzisz powa¿nie wygl¹daj¹cego mê¿czyznê w piêknych szatach. Jego dominuj¹ce spojrzenie sprawia, ¿e czujesz siê nieswojo.}
{102} {} {To spokojny koœció³. Sk¹d takie drastyczne œrodki bezpieczeñstwa?}
{103} {} {Oficjalnie porzuci³eœ Odznakê Rangersa.}
{104} {} {Oficjalnie do³¹czy³eœ do Koœcio³a Ognia.}

# Pierwszy dialog (znajomy)
{200} {} {Nie pamiêtam, ¿eby ostrzegano mnie przed twoj¹ wizyt¹. Kim jesteœ i czego potrzebujesz? Odpowiedz natychmiast w imiê Swiêtego Ognia.}
{201} {} {Nie s¹dzi³em, ¿e jeszcze ciê zobaczê. O co chodzi tym razem?}
{202} {} {Chcê tylko z tob¹ porozmawiaæ.}
{203} {} {Chcê z tob¹ porozmawiaæ.}
{204} {} {Nazywam siê }
{205} {} {. Reprezentujê spo³ecznoœæ Villi.}
{206} {} {Chcê do³aczyæ do koœcio³a, œwiêty ojcze.}

{210} {} {Myœlê, ¿e siê zgubi³em. Powiedz mi, gdzie jest wyjœcie?}
{1210} {} {Myœlê, ¿e siê zgubi³am. Powiedz mi, gdzie jest wyjœcie?}
{211} {} {Co za absurd. Spróbujê jeszcze raz. Czego potrzebujesz?}
{212} {} {Mówiê ci, szukam wyjœcia.}
{213} {} {Jesteœ albo bardzo g³upi, albo specjalnie szukasz problemów. Ochrona! Z³apaæ szpiega!}
{1213} {} {Jesteœ albo bardzo g³upia, albo specjalnie szukasz problemów. Ochrona! Z³apaæ szpiega!}
{214} {} {Kto jest szpiegiem? JA?}
{215} {} {Spróbuj mnie z³apaæ!}
{216} {} {Czekaj! Nie mam zamiaru walczyæ. Mo¿e uda nam siê za³atwiæ sprawê pokojowo?}
{217} {} {Biedna ofiara promieniowania. IdŸ w pokoju. Przepraszam, widzê twoje cierpienie. Mam nadziejê, ¿e jakiœ uliczny bandyta wkrótce zakoñczy twoje cierpienie.}
{218} {} {Nie mogê czekaæ.}
{219} {} {Niewa¿ne, znajdê swoj¹ drogê.}

{220} {} {Bardzo dobrze. Nie lubimy tu k³ótliwych goœci. Wiêc co próbujesz osi¹gn¹æ?}
{221} {} {Interesuje mnie tylko spotkanie z tob¹. Mam pare pytañ.}
{222} {} {Zadam pytania. A ty usi¹dziesz i odpowiesz.}
{223} {} {Jestem ambasadorem Bractwa Stali.}
{224} {} {Zmuszasz mnie... (jeden z radnych przerywa mu i szepcze mu coœ do ucha) Hmm. W porz¹dku. Nie zatrzymam ciê. Ale nie próbuj mnie ju¿ wiêcej rozpraszaæ. Wyjœæ!}
{225} {} {Oczywiœcie, panie Aaron. Przepraszam, ¿e przeszkadzam.}
{226} {} {Tak.}
{227} {} {Villa? To miejsce jest mi obce. Czego chcesz, }
{228} {} { z Villi?}
{229} {} {To bardzo wa¿ne. Muszê z panem porozmawiaæ, panie Aaron.}

{230} {} {Wystarczy! Zostaniesz pobity i powieszona publicznie! Schwytaæ heretyka!}
{1230} {} {Wystarczy! Zostaniesz pobita i powieszona publicznie! Schwytaæ heretyka!}
{231} {} {To jest absurd! Precz z tyranem!}
{232} {} {Tak, poszed³eœ...}
{233} {} {To zabójca! W imiê ognia, powstrzymajcie go!}
{234} {} {Spokojnie, teraz ja tu dowodzê.}
{235} {} {Oni ci nie pomog¹.}
{236} {} {Bracia, w imiê ognia, wyrzuciæ te œmieci na ulicê.}
{237} {} {Ochrona! Zabiæ szpiega! Natychmiast!}
{238} {} {Nie zatrzymaj¹ mnie...}
{239} {} {Chcê ciê zabiæ. Jesteœ nikczemnym ciemiê¿c¹ i tyranem!}

{240} {} {Nie jesteœ dla mnie zbyt mi³y, kochany.}
{241} {} {Kontynuujcie dobr¹ robotê - i bierzcie siê do ciê¿kiej pracy, jak wielu przed wami.}
{242} {} {Wiêc w ten sposób rozwiazuj¹ swoje problemy w koœciele? Wydawa³o mi siê, ¿e panuje tu atmosfera pokoju i braterstwa.}
{243} {} {Panuje. Dopóki taka atomowa nikczemnoœæ jak ty nie przyjdzie do nas i nie rozpocznie zamieszek. Swiat dooko³a sta³ siê tak dziki, ¿e nawet pokojowy koœció³ musi chwyciæ za broñ. Wy, dzikusy z pustkowi, musicie siê wiele nauczyæ.}
{244} {} {[Dalej.]}
{245} {} {Ostatni raz pytam, czego chcesz?}
{246} {} {Chcê tylko z tob¹ porozmawiaæ.}
{247} {} {Po naszej krótkiej rozmowie nie widzê sensu kontynuowania. IdŸ st¹d.}
{248} {} {Któregoœ dnia zap³acisz za takie gadanie! Przysiêgam!}
{249} {} {Ok, spokojnie opuszczê katedrê.}

{250} {} {Przepraszam, nie mam czasu na bezczynn¹ rozmowê. Czy masz ze mn¹ coœ wspólnego?}
{251} {} {Có¿, jeœli siê nad tym zastanowiæ, to tak. Moj¹ wioskê.}
{252} {} {Niezupe³nie. Przepraszam.}
{1252} {} {Niezupe³nie. Przepraszam.}
{253} {} {Nie, po prostu siê tu krêcê. Jeœli mnie tu nie pos³uchaj¹, pójdê gdzie indziej.}
{254} {} {Proszê, wa¿ne jest, abym us³ysza³ to co chcê wiedzieæ z pierwszej rêki.}

{255} {} {Swietnie. Bracia wska¿¹ ci drogê na ulicê.}
{256} {} {Nie, nie, znajdê drogê bez przewodnika.}
{257} {} {Ohh.. Jesteœ taki mi³y.}

{260} {} {To ju¿ robi siê ciekawe. Jaki masz do mnie interes?}
{261} {} {Chcê twojej œmierci. Pozostawienie przy ¿yciu takiego tyrana, jak ty, by³oby nierozs¹dne.}
{262} {} {Tu chodzi o Villê. Nazywam siê }
{263} {} {, cz³onek tej kwitn¹cej niegdyœ spo³ecznoœci.}

{264} {} {Jestem ambasadorem Bractwa Stali. Nie mogê siê doczekaæ waszego ciep³ego powitania i pomocy.}
{1264} {} {Jestem ambasadorem Bractwa Stali. Nie mogê siê doczekaæ waszego ciep³ego powitania i pomocy.}
{265} {} {Bractwo Stali jest naszym lojalnym przyjacielem i naszym niezawodnym wsparciem. Mi³o mi ciê poznaæ. Otrzymasz wszelk¹ potrzebn¹ pomoc.}
{266} {} {Nie wiedzia³em, ¿e Bractwo przyjmuje tak aroganckich rekrutów w swoje szeregi. Ale Bractwo jest naszym lojalnym przyjacielem i naszym niezawodnym wsparciem. Zostañ w katedrze. Otrzymasz wszelk¹ potrzebn¹ pomoc.}
{267} {} {Dziêkujê, panie Aaron. Jesteœ bardzo mi³y.}
{268} {} {Skoñczmy z uprzejmoœciami, Aaron. Jestem tu w interesach.}

{270} {} {Ulisses ostrzeg³ mnie przed twoj¹ wizyt¹. Wed³ug niego przyniesiesz wielk¹ korzyœæ dla naszej sprawy. Có¿, nie zawiedŸ mnie, }
{271} {} { z Villi.}
{272} {} {Zrobiê co w mojej mocy, panie Aaron.}
{273} {} {Jestem najlepszy w tym, co robiê. B¹dŸ pewny.}
{1273} {} {Jestem najlepsza w tym, co robiê. B¹dŸ pewny.}
{274} {} {Ulysses Grant mnie przysy³a.}

# Po wyslaniu do TuSan
{280} {} {Swiêty Atomie! Wys³a³em ciê na ciê¿kie roboty do Tu-San. Dlaczego jesteœ wolny?}
{281} {} {Uda³o mi siê uciec. A teraz za wszystko odpowiesz!}
{282} {} {Bracia, powstrzymajcie go! Zatrzymajcie!}
{283} {} {Nie mog¹ mnie powstrzymaæ!}
{284} {} {Uda³o mi siê negocjowaæ z Blacharzami.}
{285} {} {To wygl¹da wyj¹tkowo podejrzanie. Ale dopóki nie otrzymam odpowiedzi, mo¿esz oddychaæ powietrzem wolnoœci. Doceñ ten czas dany ci przez Swiêty Ogieñ.}
{286} {} {Podejrzanie? Masz racjê. Poniewa¿ jestem tutaj, aby siê zemœciæ.}
{287} {} {Próbujê.}
{288} {} {Przejrzyj na oczy, nie jesteœ wszechmocny.}
{289} {} {Grmm. Mo¿esz oddychaæ powietrzem wolnoœci, dopóki nie dowiem siê wiêcej. Doceñ ten czas ofiarowany ci przez Swiêty Ogieñ. A teraz zejdŸ mi z oczu!}
{290} {} {Nie tak szybko, panie tyran. Nie odejdê, dopóki bêdziesz oddychaæ tym samym powietrzem co ja.}
{291} {} {To m¹dra decyzja.}

# Powtarzajacy siê dialog
{300} {} {Wiêc czego chcesz?}
{301} {} {Ponownie, ch³opie, oœmielasz siê odci¹gaæ mnie od wa¿nych spraw.}
{1301} {} {Ponownie, ch³opko, oœmielasz siê odci¹gaæ mnie od wa¿nych spraw.}
{302} {} {Si. Co mo¿esz mi powiedzieæ?}
{303} {} {Mi³o ciê widzieæ, ambasadorze Bractwa Stali.}
{1303} {} {Mi³o ciê widzieæ, ambasadorze Bractwa Stali.}
{304} {} {Mi³o ciê widzieæ.}
{305} {} {Mi³o ciê widzieæ, akolito.}
{1305} {} {Mi³o ciê widzieæ, nowicjuszu.}
{306} {} {Nie s¹dzi³em, ¿e jeszcze ciê zobaczê. O co chodzi tym razem?}
{307} {} {Niech b³ogos³awi Ciê Swiêty Ogieñ.}
{308} {} {Do widzenia.}
{309} {} {Pójdê, jeœli zechcesz.}

# Pytania dotycz¹ce koœcio³a i wiary
{310} {} {Czy mogê dowiedzieæ siê wiêcej o Twojej wierze?}
{311} {} {Chcia³bym lepiej poznaæ twoj¹ religiê.}
{312} {} {W sali na parterze jest kazanie. Nie mam na to czasu.}
{313} {} {Chcia³bym us³yszeæ wszystko od najbardziej wiarygodnego Ÿród³a.}
{314} {} {W auli na parterze jest kazanie. Nie mam czasu, aby wyjaœniaæ podstaw prostemu ch³opowi.}
{315} {} {W takim razie zapytam kogoœ innego.}
{316} {} {Prostemu ch³opowi? Teraz wszystko jasne.}
{317} {} {}
{318} {} {Bój siê Swiêtego Ognia, moje dziecko.}
{319} {} {Tak, oczywiœcie.}

{320} {} {Jeœli interesuje ciê nasza wiara, przyjdŸ na mszê do audytorium na pierwszym piêtrze. Nie mam czasu odpowiadaæ wszystkim. Mo¿e masz coœ wspólnego ze mn¹?}
{321} {} {Có¿, jeœli siê nad tym zastanowiæ, to mam. Moj¹ wioskê.}
{322} {} {Niezupe³nie. Przepraszam.}
{1322} {} {W³aœciwie to nie. Przepraszam.}
{323} {} {Nie, po prostu siê tu krêcê. Jeœli mnie tu nie pos³uchaj¹, pójdê gdzie indziej.}
{324} {} {Proszê, wa¿ne jest, abym us³ysza³ z pierwszej rêki to co chcê wiedzieæ.}

{330} {} {To ju¿ robi siê ciekawe. Jaki masz ze mn¹ interes?}
{331} {} {Tu chodzi o Villê.}
{332} {} {Oczywiœcie o twoj¹ œmieræ. Pozostawienie przy ¿yciu takiego tyrana, jak ty, by³oby nierozs¹dne.}
{333} {} {Swietnie. Bracia wska¿¹ ci drogê na ulicê.}
{334} {} {Nie, nie, znajdê drogê bez przewodnika.}
{335} {} {Jesteœ taki mi³y.}
{336} {} {To zabójca! W imiê Ognia, powstrzymaæ go!}
{337} {} {Spokojnie, teraz ja tu dowodzê.}
{338} {} {Oni ci nie pomog¹.}
{339} {} {B³ogos³awieñstwa za ucieczkê.}

{340} {} {Oczywiœcie. Proszê.}
{341} {} {Porozmawiamy o Villi?}
{342} {} {Wiêc jaka jest istota twojej wiary?}
{343} {} {Jesteœ liderem tego koœcio³a, prawda?}
{344} {} {Us³ysza³em ju¿ dzisiaj doœæ. Dziêki za rozmowê.}
{345} {} {Powtarzam - nie mam na to czasu.}
{346} {} {Ok, porozmawiam z innymi.}
{347} {} {Po prostu próbujesz siê mnie pozbyæ.}

{350} {} {Wiesz ju¿ wszystko, co trzeba.}
{351} {} {Szanujê twoje zainteresowanie naszymi naukami. Ale nie ka¿dy mo¿e to poj¹æ.}
{352} {} {[Dalej.]}
{353} {} {Nasz koœció³ wzywa do przyjêcia Swiêtego Ognia jako aktu uzdrowienia, jako szansy na rozpoczêcie ¿ycia na nowo. W koñcu zamiast odradzaæ siê, ludzie nadal tocz¹ miêdzy sob¹ bezsensown¹ walkê.}
{354} {} {Co to jest Swiêty Ogieñ?}
{355} {} {Teraz wszystko jest dla mnie jasne, nie ma potrzeby kontynuowania.}
{356} {} {Ogieñ, który spali³ œwiat sto lat temu. Nazywamy go œwiêtym, poniewa¿ ukara³ upad³¹ ludzkoœæ i oczyœci³ ziemiê z brudu, daj¹c w ten sposób potomkom mo¿liwoœæ ¿ycia nowym ¿yciem.}
{357} {} {Czy to nie by³a jakaœ potê¿na broñ?}
{358} {} {Technicznie tak. Ale to nie jest wa¿ne. Pan bowiem kara³ ludzi w³asnymi rêkoma. Zwyk³y cz³owiek widzi bombê atomow¹ w bombie atomowej, ale my widzimy w niej Bo¿y Plan.}
{359} {} {Powiedzia³eœ „¿ycia na nowo”. Wiêc koœció³ próbuje zmieniæ œwiat?}
{360} {} {Poprzez podbicie i zjednoczenie ziem dla wspólnego celu, jakim jest przetrwanie. Wymaga to przywrócenia i ponownego przemyœlenia staro¿ytnych technologii, o¿ywienia energii j¹drowej i nauczenia ludzi czytania i pisania.}
{361} {} {Wiêc zmuszasz innych do wiary?}
{362} {} {Nie, nie. Tacy nowicjusze byliby szkodliwi dla koœcio³a. Wejœcie do koœcio³a musi byæ dobrowolne. Ponadto jesteœmy bardzo ostro¿ni w rekrutowaniu ludzi do s³u¿by; ka¿dy cz³onek koœcio³a potrzebuje porêczyciela.}
{363} {} {Co oznacza „zjednoczenie ziem”?}
{364} {} {Jeden sztandar, jeden kraj, jeden naród... jedna wiara. Ludzie musz¹ porzuciæ wszystkie wewnêtrzne konflikty i w pe³ni oddaæ siê zjednoczeniu.}
{365} {} {Jak daleko rozprzestrzeni³ siê koœció³?}
{366} {} {Mamy kaplice w okolicach Phoenix i kilku okolicznych miasteczkach. Wed³ug wspó³czesnych standardów jest to ogromne terytorium. Ale wci¹¿ mamy miejsce na rozwój.}
{367} {} {Teraz rozumiem, jak koœció³ jest powi¹zany z handlarzami niewolników.}
{368} {} {Walczysz z ka¿dym kto siê sprzeciwia. Czy nie jesteœ uwa¿any za tyrana, który si³¹ zdoby³ w³adzê?}

{370} {} {Ogólna populacja upad³a do poziomu zwierz¹t i nie jest w stanie dobrowolnie uczestniczyæ w wielkim dziele odrodzenia. Niewolnictwo jest tylko niezbêdnym i tymczasowym œrodkiem naszej misji. Co wiêcej, my sami nigdy nikogo nie zniewalaliœmy, a jedynie p³aciliœmy najemnikom za ich pracê, przymykaj¹c oczy na ich dzikie posuniêcia.}
{371} {} {Brzmi inspiruj¹co. Czy mogê do³aczyæ do twojego kultu?}
{372} {} {Wystarczy! Na tak¹ religiê nie ma miejsca w naszym œwiecie. Zniszcze was wszystkich.}
{373} {} {Dziêki za rozmowê, teraz du¿o wiêcej rozumiem.}
{374} {} {Swoj¹ drog¹, czy nie stoisz za porwaniem ch³opów z Villi?}
{375} {} {A propos porwania ch³opów z Villi.}

{380} {} {Czy to Ty prowadzisz ca³y ten koœció³?}
{381} {} {Oczywiœcie.}
{382} {} {Wiêc mo¿esz mi wyjaœniæ swoj¹ religiê lepiej ni¿ ktokolwiek inny.}
{383} {} {Mi³o ciê poznaæ. Nic innego mnie nie interesowa³o.}
{384} {} {Jesteœ powszechnie uwa¿any za tyrana. Wiesz o tym?}
{385} {} {To nie tak. NajwyraŸniej taka reputacja zosta³a zakorzeniona w Koœciele po rewolucji. Tak, doszliœmy do w³adzy si³¹. To by³ konieczny œrodek. Ale w naszych sercach zawsze by³ pokój.}
{386} {} {Mam wra¿enie, ¿e kult jest w³aœcicielem tego miasta...}
{387} {} {Koœció³ naprawdê sta³ siê dla Phoenix czymœ wiêcej. Z nasz¹ pomoc¹ do miasta wróci³y nauka, edukacja i medycyna. Wprowadziliœmy walutê kapsli i nawi¹zujemy stosunki handlowe z wa¿nymi stronami. Dziêki nam w mieœcie zmniejszy³a siê przestêpczoœæ. Ale wiêkszoœæ mieszkañców miasteczka ¿yje poza nasz¹ uwag¹.}
{388} {} {Wow, co za zwrot akcji. Chcê dowiedzieæ siê wiêcej o Twojej religii.}
{389} {} {Niewa¿ne, chowasz siê za ³adnymi s³owami, ale jesteœ zwyk³ym tyranem. I zabije ciê, ¿eby zniechêciæ innych do podobnych dzia³añ.}
{390} {} {Obawiam siê, ¿e muszê iœæ. Moje uszanowanie, panie Aaron.}
{391} {} {Wygl¹dasz bardziej na tyrana ni¿ na opata.}
{392} {} {Koœció³ musia³ wzi¹æ na siebie ciê¿ar rz¹dzenia tym miastem. Jest to œrodek konieczny, dopóki spo³eczeñstwo nie dojrzeje do stworzenia pe³noprawnego ratusza i policji.}

#Villa
{400} {} {Chcê porozmawiaæ z tob¹ o Villi.}
{401} {} {}
{402} {} {Villa... Tak, pamiêtam nasz¹ rozmowê o tej wiosce.}
{403} {} {Myœlê, ¿e ju¿ o tym rozmawialiœmy. Do widzenia, panie Aaron.}
{404} {} {Hmm... Villa... Czy to jakaœ wioska? Nigdy o niej nie s³ysza³em.}
{405} {} {W³aœciwie to szukam moich krewnych. Zostali zniewoleni.}
{406} {} {Och, biedni ludzie. Bez koñca wspó³czujê wam i bêdê siê modliæ o zbawienie waszych dusz. Ale dlaczego poszukiwania doprowadzi³y Ciê do nas?}
{407} {} {Twoja sekta jest w to wyraŸnie zaanga¿owana! Uwolnij moich krewnych!}
{408} {} {To nie by³o zbyt mi³e z twojej strony. Jesteœmy po prostu spokojnym koœcio³em, nikogo nie zniewalamy.}
{409} {} {K³amiesz.}
{410} {} {Có¿, przykro mi widzieæ tak¹ dzik¹ ignorancjê. Muszê... (jeden z doradców przerywa Zwierzchnikowi i szepcze mu coœ do ucha) To wszystko. Wiêc chcesz ponownie po³¹czyæ siê z rodzin¹? Mo¿emy to zapewniæ.}
{411} {} {Naprawdê? W jaki sposób?}
{412} {} {Od³ó¿ broñ i podnieœ rêce. Nie próbuj siê opieraæ. Zostaniesz wys³any na ciê¿kie prace do reszty twoich wspó³plemieñców.}
{413} {} {Có¿, jeœli pomo¿e mi to znaleŸæ rodzinê, dobrowolnie oddam siê jako niewolnik.}
{414} {} {Nie zastraszysz mnie. Wyjdê st¹d tak jak wszed³em.}
{1414} {} {Nie zastraszysz mnie. Wyjdê st¹d tak jak wszed³am.}
{415} {} {Szkoda, ¿e do tego dosz³o. Z³apaæ go!}
{1415} {} {Szkoda, ¿e do tego dosz³o. Z³apaæ j¹!}
{416} {} {Twoje s³owa brzmi¹ mniej istotnie ni¿ jêk atomu w chmurze ognia. Wyœlijcie go do naszych braci w Tu-San, niech s³u¿y Swiêtemu Ogniu.}
{1416} {} {Twoje s³owa brzmi¹ mniej istotnie ni¿ jêk atomu w chmurze ognia. Wyœlijcie j¹ do naszych braci w Tu-San, niech s³u¿y Swiêtemu Ogniu.}
{417} {} {(jeden z doradców przerywa Aaronowi i szepcze mu coœ do ucha) Hmm. Wygl¹da na to, ¿e bêdê musia³ ciê puœciæ. Ale na przysz³oœæ pamiêtaj, ¿e nikt nie ujdzie bezkarnie, jeœli wyst¹pi przeciwko Koœcio³owi Swiêtego Ognia.}
{418} {} {Ok, zapamiêtam to.}
{419} {} {Po prostu powiedz mi, co mam robiæ.}
{420} {} {Myœla³em, ¿e wiesz wszystko.}
{421} {} {Niestety, tak nie jest.}
{422} {} {Có¿, przepraszam. Prawdopodobnie muszê szukaæ dalej...}
{423} {} {Czekaj, nie zamierzam siê opieraæ.}
{424} {} {Jako cz³onek Bractwa Stali nie mogê siê doczekaæ, kiedy pomogê Ci znaleŸæ zaginionych ch³opów.}
{425} {} {Dziwne, ¿e Bractwo Stali jest zainteresowane tymi ch³opami. Oczywiœcie pomo¿emy Ci.}
{426} {} {Wiêc co wiesz o tej sprawie?}
{427} {} {K³amiesz. Nie wyjdê, dopóki nie poznam ca³ej prawdy.}
{428} {} {Wszyscy staæ! Nie podchodziæ! Bêdê siê broniæ!}
{429} {} {Nikt tu mnie nie tknie. Rozumiecie?}

{430} {} {Doœæ tych podchodów. WIEM, ¿e ten koœció³ sponsorowa³ konwój niewolników.}
{431} {} {Twoja zuchwa³oœæ nie zna granic.}
{432} {} {Nie wyjdê, dopóki nie dowiem siê, co siê dzieje.}
{433} {} {IdŸ w pokoju, ambasadorze Bractwa Stali.}
{434} {} {Moje uszanowanie.}
{435} {} {Tylko udajesz mi³¹ osobê? Bêdê o tym pamietaæ.}

{436} {} {Kto odwa¿y³ siê po³o¿yæ rêce na twojej rodzinie? Nie bêdê tolerowaæ takiego stosunku do mojego biskupa!}
{437} {} {To jest to, co chcê wiedzieæ. Pomo¿esz mi?}
{438} {} {(daje znak skrybie, ten szuka czegoœ w komputerze, a potem szeptem podaje wynik) Przykro mi, ale twoi krewni ju¿ poszli do pracy w œwietych kopalniach na po³udniu.}

{450} {} {Hmm. Przypomnij mi, jak nazywa siê ta wioska? (jeden z doradców podchodzi do W³adcy i szepcze mu coœ do ucha) Umm... Tak, wiemy, gdzie s¹ twoi wspó³plemieñcy. Dostali drug¹ szansê i teraz odpracowuj¹ swoj¹ karmê na po³udniu.}
{452} {} {Pamiêtam nasz¹ rozmowê. Ch³opi dostali drug¹ szansê i odpracowuj¹ swoj¹ karmê na po³udniu.}
{453} {} {Po³udniu? Ale gdzie dok³adnie?}
{454} {} {Niektórzy z nich zostali w Flagpool do pracy w kopalniach. Reszta zosta³a wys³ana do Tu-San, aby s³u¿yæ na rzecz Postêpu. Miejscowi, Blacharze nie maj¹ doœæ r¹k do pracy na terenach chronionych. Taki los jest jednak prawdziwym zaszczytem, bo niewolnicy sw¹ ofiar¹ pomog¹ ca³emu œwiatu.}
{459} {} {Po co te niepotrzebne pytania? Podczas podró¿y mia³eœ okazje lepiej poznaæ Blacharzy. To plemiê szanuje staro¿ytne technologie, chocia¿ widz¹ je w bardzo w¹skim œwietle.}
{460} {} {Kim s¹ ci Blacharze?}
{461} {} {Okultystyczne plemiê mi³oœników staro¿ytnych technologii. Podobnie jak my, opowiadaj¹ siê za odrodzeniem staro¿ytnego œwiata, ale widz¹ to wy³¹cznie w duchu technologicznym. Teraz mamy z nimi wspólne cele, ale któregoœ dnia nieporozumienia przerodz¹ siê w konflikt.}
{462} {} {A co z ich technologi¹?}
{463} {} {Bez bazy produkcyjnej Blacharzy nie mo¿emy nawet uruchomiæ elektrycznoœci w tej katedrze. Potrzebujemy ich maszyn i umiejêtnoœci.}
{464} {} {Tak, oboje musicie zostaæ wyeliminowani. Trzeba zacz¹æ od tej ¿a³osnej bezbo¿nej katedry.}
{465} {} {To wszystko wyjaœnia. Nie mam wiêcej pytañ.}
{466} {} {Czy wiêzienie w Flagpool te¿ jest twoje?}
{467} {} {Kolonia Flagpool powsta³a na naszych kapslach. Ale z czasem sta³a siê bardziej wolna i niezale¿na.}
{468} {} {Dlaczego potrzebujesz tej kolonii?}
{469} {} {Oczywiœcie do wydobywania uranu w lokalnych kopalniach.}
{470} {} {Ale dlaczego koœció³ potrzebuje rudy uranu?}
{471} {} {Uran jest potrzebny do wytwarzania energii j¹drowej. W koñcu bez tego nie da siê korzystaæ ze starych technologii. A bez nich nie ma mowy o odrodzeniu cywilizacji.}
{472} {} {Czy Faber sprawia Ci k³opoty?}
{473} {} {Czy Faber czasem nie zaczyna deptaæ Ci po piêtach?}
{474} {} {W pewnym sensie. Zdarza siê, ¿e jesz kretoszczura i zdarza siê, ¿e tylko jesz. Faber podziela wiele naszych pogl¹dów, ale widzi je inaczej. Czasami tworzy to ma³e konflikty.}
# - Cytat z filmu „The Big Lebowski”: Zdarza siê, ¿e jesz niedzwiedzia i dzieje siê to dla Ciebie.
{475} {} {Swietnie. Wiêc pójdê za jego przyk³adem i zdobêdê w³adze nad t¹ bezbronn¹ katedr¹.}
{476} {} {Myœlê, ¿e powinienem pojechaæ do Flagpool i dowiedzieæ siê wszystkiego w pierwszej osobie. PA.}
{477} {} {W pewnym sensie. Dopuszczaj¹c ludzi do w³adzy, zawsze ryzykujesz zrobieniem z przyjaciela wroga. Okaza³o siê jednak, ¿e Faber to przesz³oœæ. Nie jest jasne, czy zgin¹³ przypadkowo, czy by³ to przebieg³y plan lokalnej rewolucji. Nadal badamy ten problem.}
{478} {} {Co powiedzia³eœ o Blacharzach?}

{480} {} {Mam doœæ tego k³amstwa. Wyje¿dzam st¹d.}
{481} {} {Wygl¹da na to, ¿e masz jakieœ wielkie plany. Teraz mogê st¹d wyjœæ ze spokojem.}
{482} {} {Ale dlaczego protekcjonujesz niewolnictwo?}
{483} {} {Czy dlatego protekcjonujesz niewolnictwo?}
{484} {} {Spo³eczeñstwo nie jest gotowe na niezale¿noœæ. Ci ludzie nigdy sami nie podnios¹ siê z kolan. Potrzebuj¹ opiekunów i przewodników.}
{485} {} {Wiêc jesteœ odpowiedzialny za zniewolenie Villi?}
{486} {} {Nie œpiesz siê z oskar¿eniami. Sponsorujemy tylko nasze kolonie i ró¿ne projekty. A jeœli do ich realizacji potrzebna jest moc niewolników, kapsle zostan¹ wykorzystane i na zakup niewolników.}
{487} {} {To wstyd dla koœcio³a. Powinieneœ znikn¹æ.}
{488} {} {Ciekawy punkt widzenia. Chocia¿ z trudem zakorzeni siê w naszym kraju.}
{489} {} {Przymus jest najgorsz¹ form¹ rozwoju spo³ecznego.}
{490} {} {Och, mylisz siê. Spo³eczeñstwo nie jest gotowe do niezale¿noœci. Potrzebuje opiekunów i przewodników.}
{491} {} {Co to ma wspólnego z Blacharzami z Tu-San?}
{492} {} {Teraz rozumiem, co mam zrobiæ z nadzorcami Flagpool.}

# Zostañ obserwatorem
{500} {} {Rozwa¿am przy³¹czenie siê do twojego koœcio³a.}
{501} {} {To nie jest takie proste, jak myœlisz. Aby zostaæ przyjêtym, potrzebujesz porêczyciela lub jakiejkolwiek zas³ugi, która ma znaczenie dla naszej misji. Co mo¿esz na to odpowiedzieæ?}
{502} {} {Nie mam porêczyciela.}
{503} {} {Nasz koœció³ jest nieustannie atakowany. Udowodnij, ¿e mo¿emy Ci zaufaæ - a wtedy porozmawiamy o Twoim wst¹pieniu do niego.}
{504} {} {Spróbujê znaleŸæ porêczyciela.}
{505} {} {Jak mogê udowodniæ swoj¹ lojalnoœæ?}
{506} {} {. ... ... [zadanie testowe]}
{507} {} {Wrócê, gdy problem zostanie rozwi¹zany.}
{508} {} {Zrobiê wszystko dla lœnienia Swiêtego Ognia.}
{509} {} {Zbyt pompatyczne s³owa jak na ³otra.}
{510} {} {Ok, pójdê po porêczyciela.}
{511} {} {Ale ja naprawdê chcê do³aczyæ do twojego koœcio³a.}
{512} {} {Do rekrutacji potrzebny jest porêczyciel... Ale w¹tpiê w czystoœæ twoich intencji, ch³opie z Villi.}
{1512} {} {Do rekrutacji potrzebny jest porêczyciel... Ale w¹tpiê w czystoœæ twoich intencji, ch³opko z Villi.}
{513} {} {Ulysses Grant poradzi³ mi, ¿ebym z tob¹ porozmawia³.}
{514} {} {Czy cz³onkostwo w Bractwie Stali to wystarczaj¹cy powód?}
{515} {} {Oto list polecaj¹cy od kaznodziei z Flagpool.}
{516} {} {(s³ucha szeptu doradcy) Ten list nic nie znaczy. Wyjœæ.}
{517} {} {Hm, ale mimo wszystko...}
{518} {} {Otrzyma³em list polecaj¹cy z Flagpool. Ale gdzieœ mi znikn¹³.}
{519} {} {Ju¿ nie chcê przy³¹czaæ siê do twojej religii. Szczêœcia.}
{520} {} {Arthur Carrington mo¿e za mnie porêczyæ.}
{521} {} {Ksiêgowy Franciszek bêdzie moim porêczycielem.}
{522} {} {Daj mi szansê.}
{523} {} {Oto list polecaj¹cy od George'a Crooka.}

{530} {} {W takim razie cieszê siê, ¿e ciê widzê w siedzibie m¹droœci i postêpu. Nasz koœció³ próbuje uleczyæ œwiat z ran Wielkiej Wojny. Pomo¿esz nam w tej trudnej misji.}
{531} {} {Swietnie. Co mogê zrobiæ dla koœcio³a?}
{532} {} {Mam nadziejê, ¿e nie ma sensu wyjaœniaæ, ¿e koœció³ ma wielu wrogów. Wrogoœæ ta ostatnio bardzo siê nasili³a. Kilku naszych nowicjuszy zosta³o zabitych na ulicach miasta i to na pe³nym widoku. Proszê o zbadanie tych zbrodni.}
{533} {} {Atakuj¹cy wybrali z³y cel. Ale od czego mam zacz¹æ?}
{534} {} {ZnajdŸ Gabriela, g³osi on nasze s³owa u bram miasta i ma spor¹ wiedzê o mieœcie. Ale b¹dŸ... ostro¿ny. Jego fanatyzm czasami przera¿a nawet cz³onków naszego koœcio³a.}
{535} {} {Wrócê, gdy problem zostanie rozwi¹zany.}
{536} {} {Zrobiê co w mojej mocy.}

# Pierwsze zadanie
{550} {} {O tych zbrodniach przeciwko koœcio³owi.}
{551} {} {Czy dowiedzia³eœ siê czegoœ nowego?}
{552} {} {Przepraszam, nic. Ta sprawa jest zbyt ciemna.}
{553} {} {Przykro mi to s³yszeæ. Ale nie tracê nadziei. Porozmawiaj z Gabrielem przy bramach miasta, aby poznaæ szczegó³y ataków.}
{554} {} {Ok, pójdê ju¿.}
{555} {} {Wygl¹da na to, ¿e masz powa¿nych wrogów. S¹ dobrze zorganizowani i dobrze wyposa¿eni. Co wa¿niejsze, obserwuj¹ ciê.}
{556} {} {Czyli twierdzisz, ¿e te ataki nie by³y spontaniczne? Ze ktoœ obserwowa³ nowicjuszy i z góry przygotowywa³ siê do ataku?}
{557} {} {Dok³adnie.}
{558} {} {(wydyma usta w zamyœleniu, podchodzi do o³tarza) Prawdopodobnie tak. Ale poza katedr¹ nikt nie zna naszych zwyczajów. Zajêcia nowicjuszy s¹ zaplanowane na ca³y tydzieñ do przodu. Jeœli napastnicy, jak powiedzia³eœ, przygotowywali siê do ataku, sk¹d wiedzieli o tych planach?}
{559} {} {Kto ma dostêp do harmonogramu?}
{560} {} {Ka¿dy opat sporz¹dza plan zajêæ dla swoich akolitów i przekazuje go do biblioteki. Tylko kilka osób ma dostêp do udostêpnionej listy.}
{561} {} {Wygl¹da na to, ¿e nadszed³ czas, abym odwiedzi³ tê skarbnicê starych ksi¹¿ek. Pozwól mi odejœæ.}
{562} {} {Dobra, niech tak bêdzie, pójdê tam i mo¿e dowiem siê czegoœ wiêcej.}
{563} {} {Có¿, nie wiem. To mo¿e byæ prawda...}

{570} {} {Szpiegiem by³ Matthias. Zna³ polecenia nowicjuszy i przekazywa³ te dane drog¹ radiow¹ do wrogów koœcio³a.}
{571} {} {(usta Aarona robi¹ siê czerwone z gniewu) Matthias... Powinienem by³ domyœliæ siê wczeœniej. Jak jeden z moich najbli¿szych doradców móg³ mnie zdradziæ? Stra¿! Matthias jest aresztowany.}
{572} {} {B¹dŸ mi³y dla tego szanowanego mê¿czyzny.}
{573} {} {Racja. I usma¿yæ jego jaja pastuchem.}
{574} {} {(b³¹ka siê po sali w zamyœleniu) Wokó³ sami oszuœci... Nie mogê ufaæ nawet moim najbli¿szym podw³adnym. Nigdy bym nie pomyœla³, ¿e Matthias tak bardzo nienawidzi³ stanu rzeczy w koœciele.}
{575} {} {By³ przeciwny twojej polityce, prawda?}
{576} {} {Matthias opowiada³ siê za izolacj¹ katedry od œwiata i pe³n¹ konserwacj¹ naszych relikwii. Nie chcia³ siê nimi dzieliæ z nieznajomymi i nie widzia³ nikogo, kto by³by ich godny. Nie zgodzi³em siê. Nadszed³ czas, kiedy tê wiedzê nale¿y oczyœciæ z prochu i pleœni w imiê Swiêtego Ognia.}
{577} {} {NajwyraŸniej nie wszystkim siê to podoba³o.}
{578} {} {(robi wdzieczn¹ minê) Dobrze siê spisa³eœ, bracie. A co wa¿niejsze, zachowa³eœ swoj¹ lojalnoœæ. Potrzebujê twojej dalszej pomocy, aby oczyœciæ ziemie Phoenix z brudu.}
{1578} {} {(robi wdzieczn¹ minê) Dobrze siê spisa³aœ, siostro. A co wa¿niejsze, zachowa³aœ swoj¹ lojalnoœæ. Potrzebujê twojej dalszej pomocy, aby oczyœciæ ziemie Phoenix z brudu.}
{579} {} {Wszystko dla Swiêtego Ognia, Wasza Swiêtobliwoœæ.}
{580} {} {Co jest ode mnie wymagane tym razem?}
{581} {} {NajwyraŸniej w mieœcie jest gang nienawidz¹cy wyznawców ognia. Dobrze zorganizowany i uzbrojony. Wszystkie informacje na ich temat wyci¹gniemy od Matthiasa, ale to nie wystarczy. Musisz znaleŸæ ich bazê i zinfiltrowaæ ich szeregi. Czy dasz sobie z tym radê?}
{582} {} {Mo¿e. Ale dlaczego ja?}
{583} {} {Nadal jesteœ nowy w naszym koœciele. Rebelianci jeszcze nie rozpoznaj¹ ciê jako jednego z nas.}
{584} {} {Jeœli znajdê ich bazê, co powinienem zrobiæ?}
{585} {} {Daj mi znaæ. Zdecydujemy, co dalej.}
{586} {} {Jak to zrobiæ?}
{587} {} {Matthias u¿ywa³ radia do komunikacji z rebeliantami. Ponadto prawdopodobnie wielu mieszkañców miasta jest jakoœ powi¹zanych z tym gangiem. Spróbuj na wszystkie mo¿liwe sposoby.}
{588} {} {Zrobiê co w mojej mocy. Pozwól mi odejœæ.}
{589} {} {Ale dlaczego ja?}
{590} {} {By³eœ doœæ wybredny, jeœli chodzi o „godnych”, prawda?}

# Drugie zadanie
{600} {} {Sytuacja z rebeliantami siê wyjaœni³a.}
{601} {} {Naprawdê? Powiedz co wiesz.}
{602} {} {Szczerze, to wszystko to tylko podejrzane plotki. Nie wyci¹gajmy pochopnych wniosków.}
{603} {} {Rebelianci ukrywali siê w kana³ach. Ale ich przywódca ju¿ nie ¿yje, a partia jest podzielona i st³umiona...}
{604} {} {...Bardzo dobrze. Wyœlê ludzi, ¿eby posprz¹tali legowisko tych przestêpców, a ty powinieneœ otrzymaæ nagrodê. Wygl¹da na to, ¿e sam Swiêty Ogieñ zes³a³ nam oœwiecenie w twojej postaci.}
{605} {} {Mogê nadal s³u¿yæ koœcio³owi, jeœli jest taka potrzeba.}
{606} {} {Nie w¹tpiê, moje dziecko. Co wiêcej, w tej chwili potrzebujemy przyjació³ bardziej ni¿ kiedykolwiek.}
{607} {} {Jak mogê pomóc, panie Aaron?}
{608} {} {Wiem, gdzie jest sztab generalny Partii Wyzwolenia.}
{609} {} {Byæ mo¿e ju¿ widzia³eœ naszych kaznodziejów poza Phoenix. Koœció³ roœnie i otwiera swoje kaplice, w których ludzie s¹ gotowi nas s³uchaæ. Ale wioska San Brahmin sta³a siê przeszkod¹ dla naszej wiary.}
{610} {} {[Dalej.]}
{611} {} {Miejscowi, którzy na pocz¹tku byli przyjaŸni, z jakiegoœ powodu zez³oœcili siê na koœció³. Nasze próby rozmowy z nimi tylko pogorszy³y sytuacjê. Nie wiemy dok³adnie, co siê dzieje. Teraz na obrze¿ach wioski znajduje siê oddzia³ Georga Crooka. ZnajdŸ go i zaoferuj swoj¹ pomoc. Musimy odnowiæ nasze umowy handlowe z t¹ wiosk¹.}
{612} {} {[Dalej.]}
{613} {} {Oto 350 kapsli na drogê i wszystko, co musisz kupiæ. Trwaj. Swiêty Ognien b³ogos³awi ciê.}
{614} {} {Idê, panie Aaron. San Brahmin uwierzy w moc Swiêtego Ognia.}
{615} {} {Zrobiê co w mojej mocy.}
{616} {} {Ju¿ bardzo pomog³eœ, Atomowy Wys³anniku. George Crook opowiedzia³ mi o twoim wyczynie. Myœla³em, ¿e mogê ciê wys³aæ, ¿ebyœ mu pomóg³, ale uda³o ci siê mnie wyprzedziæ. Teraz chcê dowiedzieæ siê wszystkiego z twoich ust: jak rozwija siê nasza sprawa w San Brahmin?}
{1616} {} {Ju¿ bardzo pomog³aœ, Atomowa Wys³anniczko. George Crook opowiedzia³ mi o twoim wyczynie. Myœla³em, ¿e mogê ciê wys³aæ, ¿ebyœ mu pomog³a, ale uda³o ci siê mnie wyprzedziæ. Teraz chcê dowiedzieæ siê wszystkiego z twoich ust: jak rozwija siê nasza sprawa w San Brahmin?}
{617} {} {Rzeczywiœcie, mam ci do opowiedzenia historiê.}

# Trzecie zadanie
{630} {} {Muszê z tob¹ porozmawiaæ o sytuacji w San Brahmin.}
{631} {} {Oczywiœcie. Jak sytuacja, moje dziecko?}
{632} {} {Wkrótce odwiedzê to miejsce, aby uzyskaæ wiêcej informacji. PA.}
{633} {} {[CHIT: Deed zrobiony z najlepszym wynikiem dla Overlorda]}
{634} {} {[Bla, bla, chwa³a ogniu - bla, bla, porozmawiaj z doradc¹ w kryjówce, oto klucz i dostêp - bla, bla, zabij George'a Crooka]}
{635} {} {[CHIT: wykonywanie zadañ - zdobywanie tytu³u + wysylanie do kryjowki + nagroda + czêstotliwoœæ radiowa katedry]}
{636} {} {Przynoszê wieœæ o zwyciêstwie, mistrzu Aaron. Wódz plemienia podpisa³ sojusz i oddzia³ Crooka bez problemu stacjonuje w pobli¿u wioski.}
{1636} {} {Przynoszê wieœæ o zwyciêstwie, mistrzu Aaron. Wódz plemienia podpisa³ sojusz i oddzia³ Crooka bez problemu stacjonuje w pobli¿u wioski.}
{637} {} {Chwa³a Swiêtemu Ogniu! Czy sam Bóg wys³a³ ciê do nas w tym trudnym momencie? To cud. Zas³ugujesz na najwy¿sz¹ nagrodê.}
{638} {} {To by³ dla mnie œwiêty obowi¹zek.}
{639} {} {Nie wiem, czy to Swiêty Ogieñ tu pomóg³, ale tak siê sta³o.}
{640} {} {Hmm, w swoim raporcie George Crook chwali twoj¹ osobowoœæ i lojalnoœæ wobec Imperium. Bior¹c pod uwagê twoje przesz³e zas³ugi dla koœcio³a, nie mogê przejœæ obok i nie wynagrodziæ Ciê.}
{641} {} {Czeœæ, Wasza Swiêtobliwoœæ.}
{642} {} {Jak?}
{643} {} {Za Twoje zas³ugi dla Imperium Phoenix uroczyœcie mianujê Ciê moim biskupem. WeŸ t¹ swiêt¹ szatê jako dowód uznania. Niech ochroni Ciê przed wrogimi kulami i k³amstwami.}
{644} {} {Dziêki.}
{645} {} {Czas równie¿ wprowadziæ ciê do naszego tajnego kregu. Oto klucz do piwnicy. Znajdziesz tam staro¿ytne sanktuarium. Powiedz stra¿nikom, aby odprowadzili ciê do Ulyssesa Grant. Uprzedzê go o Twojej wizycie.}
{646} {} {[Dalej.]}
{647} {} {IdŸ, przyjacielu. Ogieñ ciê b³ogos³awi.}
{648} {} {Dziêkujê za zaszczyt, panie Aaron.}

{650} {} {Panie, mam niepokoj¹ce wieœci - George Crook zgin¹³ podczas swojej misji.}
{651} {} {(wzdycha i krzy¿uje palce) Niech Swiêty Ogieñ uspokoi jego duszê. By³ to najlepszy wojownik, jakiego kiedykolwiek zna³em. A jeœli nawet on nie zdo³a³ oprzeæ siê dzikusom, to kto mo¿e wype³niæ jego misjê?}
{652} {} {Nie s¹dzê, ¿ebym sobie z tym poradzi³.}
{653} {} {Ja mogê to zrobiæ.}
{654} {} {Wróæ do San Brahmin i podbij plemiê w imiê ognia! To jest twój œwiêty obowi¹zek. A jeœli nie mo¿esz, siej niezgodê w plemieniu. Zabij Wielkiego Wodza, aby dzikusy walczy³y o jego tron. Spraw, by Stra¿nicy uciekli z pueblo. Trwaj. I udaj siê tam!}
{655} {} {Tak, panie...}
{656} {} {Z³e wieœci. Plemiê zawar³o sojusz ze Stra¿nikami, którzy wypêdzili misjonarzy z Pueblo i okolicznych ziem.}
{657} {} {(bierze g³êboki oddech i krzy¿uje palce) Jesteœmy spóŸnieni. Tyle wysi³ku poœwiêcono na podbój plemienia, ale na pró¿no!}
{658} {} {Czy na pewno wszystko stracone?}
{659} {} {Mo¿e uda mi siê jeszcze przekonaæ wodza.}
{660} {} {Wódz nie ¿yje. Plemiê jest podzielone. Teraz Stra¿nikom trudno bêdzie wykorzystaæ tê sytuacjê.}
{661} {} {Trudno poznaæ pora¿kê. Ale ile przeœladowañ znosiliœmy wczeœniej? Nic, poczekamy. Dzicy spadali do swojego poziomu od pokoleñ. Byæ mo¿e nie mniej zajmie im podci¹gniêcie siê do cywilizowanego stanu.}
{662} {} {[Pos³uchaj]}
{663} {} {Sam wiesz co zrobi³eœ dla koœcio³a. Chocia¿ bardzo chcia³bym wyrzuciæ ciê z katedry po tylu niepowodzeniach, moi doradcy doszli do innego wniosku. Pozwolê ci spotkaæ siê z moim najlepszym doradc¹, Ulissesem Grantem. WeŸ ten klucz i zejdŸ do piwnicy. Stra¿nicy zaprowadz¹ ciê do Ulissesa. Nie mo¿e siê doczekaæ spotkania z tob¹.}
{664} {} {Dziêkujê, panie.}