{100} {} {Widzisz przed sob¹ stra¿nika.}
{101} {} {Widzisz jednego z najemników gildii. Uwa¿nie ciê obserwuje.}

{110} {} {Bruce ma twardy temperament.}
{111} {} {Bruce to twardziel.}
{112} {} {Niewa¿ne jak bardzo siê stara³em, Bruce nigdy siê nie uœmiech¹³.}
{113} {} {Bruce denerwuje siê, gdy klienci nosz¹ broñ.}
{114} {} {Patrzê na ciebie.}
{115} {} {Ty. Stañ pod œcian¹ i zdejmij spodnie... tylko ¿artujê.}
{116} {} {Rêce na g³owê. Twarz¹ w pod³ogê... Zartuje, nie martw siê.}
{117} {} {Uœmiechnij siê, jesteœ w najbezpieczniejszym miejscu w Phoenix.}
{118} {} {Prosto z pustkowia, co? Nadal jesteœ niewinnym dzieckiem w du¿ym mieœcie.}
{119} {} {O mój Bo¿e, jak siê tu dosta³eœ?}
{120} {} {Powiedz to g³oœno, dlaczego szepczesz?}
{121} {} {Masz papierosa?}
{122} {} {Czy to pierwszy raz, kiedy widzisz tego rodzaju zbrojê? Mo¿esz jej dotkn¹æ.}
{123} {} {Kapsle i artefakty! Tylko ¿artujê...}