{100} {} {Widzisz najemnika.}
{101} {} {Widzisz krzepkiego mê¿czyznê ubranego w ciê¿k¹ zbrojê.}
{102} {} {Straci³eœ swojego osobistego ochroniarza.}
{103} {} {Czas siê skoñczy³, twój ochroniarz wróci³ na przystanek karawan.}

{110} {} {Ten obóz karawan jest prawdopodobnie najbezpieczniejszym miejscem w mieœcie.}
{111} {} {To centrum handlowe w mieœcie. Nie zabij¹ ciê tutaj, ale wyczyszcz¹ twoje kieszenie, ¿ebyœ nie mia³ z czego ¿yæ.}
{112} {} {Uwa¿aj. Te slumsy s¹ rz¹dzone przez gang Czerwonych Kardyna³ów. Jeœli wpadniesz z nimi w k³opoty, nie bêdê móg³ Ci pomóc.}
{113} {} {Przed nami staro¿ytna elektrownia. Nadal zapewnia moc od lokalnych ghuli.}
{114} {} {Oto Katedra Swiêtego Ognia. Przepraszam, ale nie wejdê do œrodka.}

# Dialog poza eskorta
{200} {} {Hej, jesteœ w mieœcie od niedawna, prawda?}
{201} {} {Zgadza siê. Zastanawiam siê czy miasto ma do zaoferowania coœ nowicjuszowi, takiemu jak ja.}
{202} {} {Dlaczego, Phoenix jest ogromne! To najwiêksze miasto jakie znam.}
{203} {} {Wygl¹da na to, ¿e chcesz dodaæ jakieœ „ale”.}
{204} {} {Swietnie, nie mogê siê doczekaæ, ¿eby siê tu rozejrzeæ.}
{205} {} {Ale powiem - uwa¿aj, to nie jest najlepsza pora na zwiedzanie.}
{206} {} {Dlaczego nie?}
{207} {} {Naprawdê? Nie mówisz po moich zêbach?}
{208} {} {Jaki masz w tym interes?}
{209} {} {Wow, nie powinieneœ byæ taki spiêty. Ja jestem tym, który bierze na siebie ca³e napiêcie. Prawdopodobnie chcesz zobaczyæ zabytki wielkiego Phoenix?}
{210} {} {Za³ó¿my, ¿e tak.}
{211} {} {Oczywiœcie!}
{212} {} {W takim razie powiem ci coœ - uwa¿aj, to nie jest najlepszy sezon na to.}
{213} {} {Miasto jest niespokojne od kilku lat. S¹ tutaj obszary, w których bandyci prowadz¹ swoje przedstawienia, a na rynku dochodzi do w³amañ. Lepiej nie pojawiaæ siê samotnie na ulicach.}
{214} {} {Co sugerujesz?}
{215} {} {I oczywiœcie wiesz, jak zapewniæ sobie bezpieczeñstwo?}
{216} {} {Eskortujê VIP-ów po ca³ym mieœcie. Jeden uzbrojony stra¿nik wystarczy, aby wszystkie œmieci omija³y ciê szerokim ³ukiem. Ale jak widzê, masz ju¿ ochronê. Jeœli zostaniesz bez ochrony, skontaktuj siê ze mn¹. Jestem profesjonalist¹ w tej bran¿y.}
{217} {} {Bêdê pamietaæ. Czeœæ.}
{218} {} {Eskortujê VIP-ów po ca³ym mieœcie. Jeden uzbrojony stra¿nik wystarczy, aby wszystkie œmieci omija³y ciê szerokim ³ukiem. Jeœli zdecydujesz siê na stra¿nika - skontaktuj siê ze mn¹, jestem profesjonalist¹ w tej bran¿y.}
{219} {} {Pomyœlê o tym. A teraz mam piln¹ sprawê. Bywaj.}
{220} {} {Potrafiê siê broniæ.}
{221} {} {Nie w¹tpiê! Ale jeœli zmienisz zdanie, wiesz, gdzie mnie znaleŸæ.}
{1221} {} {Och, nie w¹tpiê! Ale jeœli zmienisz zdanie, wiesz, gdzie mnie znaleŸæ.}
{222} {} {Pomyœlê o tym. Bywaj.}
{223} {} {Wygl¹da na to, ¿e ka¿de du¿e miasto wita oszustwem. Wychodzê.}
{224} {} {Za³ó¿my, ¿e jestem tob¹ zainteresowany. Ile kosztuj¹ Twoje us³ugi?}
{225} {} {To bêdzie kosztowaæ }
{226} {} { kapsli na godzinê. Ale bez barteru.}
{227} {} {Nie staæ mnie na to. Do widzenia.}
{228} {} {Przekona³eœ mnie. Oto kapsle.}

{230} {} {Phoenix jest w twoich rêkach, kochanie, kiedy to ja kryjê twoje plecy.}
{231} {} {Jestem do twojej dyspozycji.}
{232} {} {Nie bêdziesz potrzebowaæ lekarza ani ksiêdza, kiedy ja jestem w pobli¿u.}
{233} {} {Bêdê przeklêty, jeœli coœ ci siê stanie.}
{234} {} {Nie martw siê, ka¿dy pies mnie tu zna.}
{235} {} {Nie martw siê, znam ka¿dy zak¹tek tej metropolii.}
{236} {} {Teraz mo¿esz zrelaksowaæ siê i dobrze bawiæ.}

{239} {} {Super. Mam teraz osobistego ochroniarza.}

{240} {} {Potrzebujesz ochroniarza? Radzê zaopatrzyæ siê w jednego lub mocny granatnik.}
{241} {} {Jasne. Bywaj.}
{242} {} {Czy nadal zajmujesz siê ochranianiem?}

# Dialog podczas akompaniamentu
{250} {} {Och, proszê.}
{251} {} {Jasne.}
{252} {} {Droga wolna.}
{253} {} {Nie sikaj w spodnie. Nie ma siê czego baæ.}
{254} {} {Spokojnie, wyci¹gnê ciê z wszelkiego ba³aganu.}
{255} {} {Co?}
{256} {} {Jakiœ problem?}
{257} {} {Tak?}
{258} {} {Ten obszar jest kontrolowany przez gang Czerwonych Kardyna³ów. Jeœli ¿ycie jest ci mi³e, radzê natychmiast odejœæ.}
{259} {} {Ok, chodŸmy.}

{260} {} {Poczekaj tutaj, a¿ wrócê.}
{261} {} {Cokolwiek powiesz. Ale jeœli skoñczy siê czas, wrócê na przystanek karawan.}
{262} {} {Nigdzie nie idŸ.}
{263} {} {Za mn¹.}
{264} {} {Cokolwiek powiesz, szefie.}
{265} {} {Smia³o.}
{266} {} {Nie potrzebujê ju¿ twoich us³ug.}
{267} {} {Na pewno? Nie zwróce kapsli za resztê czasu.}
{1267} {} {Na pewno? Nie zwróce kapsli za resztê czasu.}
{268} {} {Tak, jesteœ wolny. Jeœli jeszcze bêdê ciê potrzebowaæ, to wiem gdzie Ciê znaleŸæ.}
{269} {} {Ok, bêdê tolerowaæ twoj¹ obecnoœæ jeszcze przez chwilê.}