{100} {} {Widzisz Bruca.}
{101} {} {Widzisz mê¿czyznê w pancerzu. Jego spokojne spojrzenie wyra¿a obojêtnoœæ na ludzkie ¿ycie.}
{102} {} {To jest zbroja wspomagana, prawda? Imponuj¹ca. Ale w razie czego i tak Ci nie pomo¿e.}
{103} {} {No có¿, kolejny æpun z ulicy. PrzyjdŸ, kiedy siê ogarniesz.}

# Galezie wprowadzajace
{200} {} {Witamy. Nazywam siê Bruce Turner, a to jest agencja rekrutacyjna. Szukasz twardzieli do ochrony, czy mo¿e szukasz kogoœ wœród zbieg³ych przestêpców?}
{201} {} {Prawdopodobnie.}
{202} {} {...}

{210} {} {Niech ciê cholera, co to za skóra?}
{211} {} {Trochê wirusów i promieniowania. Nic z³ego.}
{212} {} {Hmm. W twojej sytuacji nie mia³bym czasu na ¿arty.}
{213} {} {W mojej sytuacji ju¿ byœ nie ¿y³.}
{214} {} {To kwestia przyzwyczajenia, panie.}
{215} {} {Smiejesz siê ze mnie, g³adkoskóry?}
{216} {} {(unosi brew) Nie. Zaden problem, zielony.}
{217} {} {To dobrze.}
{218} {} {Nastêpnym razem mogê siê powa¿nie obraziæ.}

{220} {} {Dzieñ dobry, sir. Mi³o ciê poznaæ. Czy ktoœ Ci przeszkadza?}
{1220} {} {Dzieñ dobry, pani. Mi³o ciê poznaæ. Czy ktoœ Ci przeszkadza?}
{221} {} {Dlaczego nagle sta³eœ siê taki mi³y?}
{222} {} {Poniewa¿ zas³ugujesz na dobre traktowanie... sir.}
{1222} {} {Poniewa¿ zas³ugujesz na dobre traktowanie... proszê pani.}
{223} {} {No có¿, oto nasza nowa gwiazda. W tym mieœcie pozwalasz sobie na zbyt wiele. Myœlisz, ¿e ujdzie ci to na sucho?}
{224} {} {Mieszkañcy miasta s¹ tacy podstêpni i podli. My, ch³opi, jesteœmy znacznie lepsi.}
{225} {} {Nie powinieneœ by³ wype³zaæ ze swojej dziczy. Zwrócê twoje cia³o pustyni... martwe cia³o.}
{226} {} {Czym jesteœ...}
{227} {} {Bêdê siê broniæ.}
{228} {} {Ka¿dy radzi sobie najlepiej jak potrafi. Nie musisz mnie oceniaæ.}
{229} {} {O nie. Miasto p³aci mi za ³apanie przestêpców. A ty jesteœ jednym z nich. Ch³opaki... (daje znak)}
{230} {} {Nie rób tego Bruce...}
{231} {} {Bêdê siê broniæ.}
{232} {} {Nie chcê walki. Mo¿e siê dogadamy?}
{233} {} {Wszyscy prze¿ywaj¹ najlepiej jak tylko potrafi¹. Ty te¿ tu jesteœ, wykonuj¹c niezupe³nie uczciw¹ prace. Czy¿ nie?}
{234} {} {Hmm. Ciekawe. Nie wiem, komu ufaæ. Ale wiem na pewno, ¿e jeœli nie opuœcisz miasta, zostaniesz powieszony na latarni. Czy to jasne?}
{235} {} {Rozumiem.}
{236} {} {IdŸ do diab³a, Bruce. Ty i ca³a Twoja agencja.}
{237} {} {Dobrze to s³yszeæ.}
{238} {} {Pochlebstwa nie pasuj¹ do szefa najemników. Ale doceniam to.}

{240} {} {Nie ruszaj siê. Po pierwsze, chcê wiedzieæ, co wydarzy³o siê miêdzy tob¹ a wyznawcami ognia.}
{241} {} {To nasza w³asn¹ sprawa. To ciê nie dotyczy.}
{242} {} {O nie. To gildia najemników, a nie burdel. Od lat wspó³pracujemy z czcicielami ognia, przewo¿¹c niewolników i skazañców przez pustyniê. I nagle przychodzisz i przerywasz mi kilka cholernych kontraktów. Co za cholera?}
{243} {} {Mówiê, ¿e to sprawa osobista.}
{244} {} {Och, czyli chodzi o zemstê? Rozumiem. Twoje szczêœcie, ¿e wyznawcy nie mog¹ jeszcze zap³aciæ za twoj¹ g³owê. Ale jeœli tak siê stanie, obiecujê ci, ¿e twoja g³owa bêdzie na moim biurku.}
{245} {} {Przera¿asz mnie. Bêdzie lepiej, jeœli st¹d wyjdê.}
{246} {} {W¹tpiê, ¿eby do tego dosz³o, Bruce. Do zobaczenia.}

{247} {} {Adios, bandidos.}
{248} {} {[Poka¿ œrodkowy palec]}
{249} {} {Jak mówisz, ty tu jesteœ szefem.}
{250} {} {Co za niespodzianka. Zwykle to my œcigamy przestêpców, a nie na odwrót.}
{251} {} {Kto tu jest przestêpc¹?}
{252} {} {Ale ja nie jestem kryminalist¹.}
{253} {} {Wiesz, ¿e Flagpool og³osi³o ciê najgorszym przestêpc¹? Twoje szczêœcie, ¿e miasto nie mo¿e zap³aciæ za ciebie nagrody. Jednak teraz wiem, kim jesteœ i gdzie Ciê szukaæ. Pamiêtaj o tym i b¹dŸ cicho.}
{254} {} {Nie ma problemu, szeryfie.}
{255} {} {Nie jestem szeryfem, idioto. Ale jeœli zajdzie taka potrzeba, bêdê gorszy ni¿ jakikolwiek szeryf.}
{1255} {} {Nie jestem szeryfem, idioto. Ale jeœli zajdzie taka potrzeba, bêdê gorszy ni¿ jakikolwiek szeryf.}
{256} {} {Nie ma potrzeby mi groziæ, wierzê.}
{257} {} {Nie podoba mi siê ten ton. Wrócê, kiedy siê uspokoisz.}
{258} {} {Wiêc zaopatrz siê w amunicjê. Poniewa¿ nie dorwiesz mnie tak ³atwo.}
{259} {} {(powoli k³adzie rêkê na karabinie maszynowym, patrz¹c ci w oczy) Wynoœ siê z mojego biura.}

{260} {} {Witamy... Czekaj. Poka¿ mi swoj¹ szyjê. To œlady ko³nierza. To dziwne, ¿e zbieg³y niewolnik tu przychodzi. Czego chcesz, niewolniku?}
{261} {} {Nie nazywaj mnie tak. Albo bêdziesz tego ¿a³owaæ.}
{262} {} {Wygl¹da na to, ¿e nie rozumiesz swojej niepewnej pozycji. Ch³opaki... (daje znak)}
{263} {} {Nie w twarz...}
{264} {} {Zabijê wszystkich handlarzy niewolnikami w Arizonie.}
{265} {} {Chcê odzyskaæ wolnoœæ. Blacharze Ÿle mnie potraktowali.}
{266} {} {Hmm. Blacharze nie bêd¹ chcieli odkupiæ zbieg³ego niewolnika za tê sam¹ cenê. Rozczarowujesz mnie. Có¿, jestem gotów oddaæ Ci wolnoœæ. Ale bêdzie Ciê to kosztowaæ 1000 kapsli. W¹tpiê, czy masz tak¹ kwotê.}
{267} {} {Znajdzie siê.}
{268} {} {Wiêc nie mam wyboru... zabije ciê.}
{269} {} {Hmm. Dobrze, dobrze. Czekam na 1000 kapsli.}

{270} {} {(mru¿y oczy) Hmm. Niedawno otrzyma³em informacje o jednym z bandytów. I pasujesz do jego opisu.}
{271} {} {To zwyk³y zbieg okolicznoœci. Masz jakieœ dowody?}
{272} {} {Nie. Ale bêdê mieæ ciê na oku.}
{273} {} {Oczywiœcie.}
{274} {} {Nawet o tym nie myœl.}
{275} {} {Bandyci zrobili ze mnie negocjatora.}
{276} {} {To niespodzianka. A jeœli to prawda, to mo¿esz byæ przydatny. Có¿, kiedy jesteœ w tym mieœcie, uwa¿aj na siebie. W koñcu miejscowi was nie lubi¹.}
{277} {} {Mamy wielu wrogów, zgadza siê.}
{278} {} {Za du¿o wiesz, Bruce. Przepraszam, ale muszê ciê uciszyæ...}

{280} {} {To specyficzny pancerz widywany tylko w tych okolicach. Sk¹d to masz?}
{281} {} {Trofeum bojowe.}
{282} {} {Hmm. Okej, mogê w to uwierzyæ. Ale w tym mieœcie lepiej w nim nie b³yszczeæ. Wiele osób tu s³ysza³o o bandytach z g³ównej linii i mog¹ wzi¹æ ciê za jednego z nich.}
{283} {} {Dziêki za ostrze¿enie.}
{284} {} {Nie obchodz¹ mnie miejscowi.}
{285} {} {Prezent od dobrego znajomego.}
{286} {} {Masz niebezpiecznych przyjació³. Radzê ci to schowaæ, gdy bêdziesz w mieœcie. Miejscowi du¿o s³yszeli o bandytach z autostrad. Mo¿esz przypadkowo dostaæ z automatu.}

{290} {} {No có¿, oto kolejna ofiara pustyni. Podobno narobi³eœ du¿o ha³asu w Casa Grande. To prawda?}
{1290} {} {No có¿, oto kolejna ofiara pustyni. Podobno narobi³aœ du¿o ha³asu w Casa Grande. To prawda?}
{291} {} {O czym ty mówisz? Mam œwietne relacje z miejscowymi.}
{292} {} {Nie ok³amuj mnie, kolego. Moje Ÿród³a nie mog¹ siê myliæ.}
{1292} {} {Nie ok³amuj mnie, kochana. Moje Ÿród³a nie mog¹ siê myliæ.}
{293} {} {Co ciê to obchodzi?}
{294} {} {Tak, trzeba by³o uciszyæ kilku ludzi. Miejscowi s¹ zbyt podejrzliwi.}
{295} {} {(unosi brew) Szczere wyznanie? To upraszcza sprawê.}
{296} {} {O co chodzi?}
{297} {} {Masz szczêœcie, ¿e miejscowi nie mog¹ zap³aciæ za twoja g³owê. Pamiêtaj jednak, ¿e w ka¿dej chwili mo¿e siê to zmieniæ.}
{298} {} {Oczywiœcie. Bêdê cicho.}
{299} {} {Bardzo w to w¹tpiê.}

# Glowny dialog
{300} {} {Witamy. Jak mogê pomóc?}
{301} {} {Nie radzê ci wykonywaæ ¿adnych gwa³townych ruchów. Czego potrzebujesz?}
{302} {} {Reprezentujê Chucka z gangu Niebieskich Tarcz.}
{303} {} {Ok, chwileczkê... Tak, to jakiœ z³odziejaszek, za którego burmistrz Casa Grande przyzna³ nagrodê. Chcesz go usprawiedliwiæ czy zap³aciæ za jego g³owê? Cena to 250 kapsli.}
{304} {} {Zap³aciæ. Oto kapsle.}
{305} {} {Ten przestêpca jest teraz oficjalnie wolny. Przeka¿ê t¹ informacjê równie¿ do Casa Grande.}
{306} {} {Dziêki.}
{307} {} {Nie staæ mnie na to. PA.}
{308} {} {}
{309} {} {Do zobaczenia.}

# Tytul niewolnika
{310} {} {Chcê wykupiæ wolnoœæ.}
{311} {} {Ju¿ o tym rozmawialiœmy. Czy masz 1000 kapsli?}
{312} {} {Nie.}
{313} {} {To wypad.}
{314} {} {Cholera...}
{315} {} {Oto kapsle.}
{316} {} {Szczerze mówi¹c, jestem zaskoczony. W¹tpiê, czy te kapsle zosta³y zarobione uczciwie, ale nie chcê tego wiedzieæ.}
{317} {} {A mo¿e bezp³atnie?}
{318} {} {To zajmie trochê czasu...}
{319} {} {Poczekam...}
{320} {} {Gotowe. Jesteœ teraz oficjalnie wolny. Gratulacje. Doceñ swoj¹ drug¹ szansê.}
{1320} {} {Gotowe. Jesteœ teraz oficjalnie wolna. Gratulacje. Doceñ swoj¹ drug¹ szansê.}
{321} {} {Super. Zegnam.}
{322} {} {Hej, nie udawaj, ¿e uwalniasz swojego by³ego przestêpcê. Wrêcz przeciwnie.}

# Wyprawa kardyna³ów
{323} {} {Po¿a³ujesz.}
{324} {} {Bruce, puœæ goœcia. To mój stary przyjaciel. Nie odrzucisz mojej proœby, prawda?}
{325} {} {Jesteœ szanowan¹ osob¹. Oczywiœcie, ¿e ci ufam. Ale nie wpadaj w k³opoty z tymi kardyna³ami. Latwo jest w ten sposób zepsuæ swoj¹ reputacjê.}
{326} {} {Wymyœlê coœ. Dziêkujê za wyrozumia³oœæ Bruce.}
{327} {} {To mój stary przyjaciel. I nie jest nic winny. Daj mu odejœæ.}
{328} {} {Nie znam ciê, a twoje s³owo w tym mieœcie nic nie znaczy. A jeœli przeszkodzisz mi w pracy, trafisz do tej samej celi co on, gdzie bêdziesz gniæ przez d³ugi czas.}
{329} {} {Ok.}
{330} {} {Wiem, ¿e zatrzyma³eœ Czerwonego Kardyna³a.}
{331} {} {Tak, pozwalam mu siedzieæ w niewoli i myœleæ o swojej przysz³oœci. Ale sk¹d TY o tym wiesz? Nikt poza grup¹ przechwytuj¹c¹ nie by³ tego œwiadomy.}
{332} {} {Mam swoje Ÿród³a. O co jest oskar¿ony?}
{333} {} {Ta sprawa nie jest warta rozg³osu. Klient za¿¹da³ zaprzestania transakcji, a ja sam nie wiem wiêcej.}
{334} {} {Rozumiem. Mi³ej pracy.}
{335} {} {Muszê siê z nim zobaczyæ. Zap³acê 10 kapsli za spotkanie.}
{336} {} {Ok. Masz dziesiêæ minut.}
{337} {} {Oto kapsle.}
{338} {} {Nie teraz.}
{339} {} {Ile zap³acono ci za schwytanie go? Zap³acê wiêcej za uwolnienie go.}
{340} {} {Hmm. Jeœli siê nad tym zastanowiæ, to ¿a³osna ma³a rzecz. Zwolniê go za kaucj¹ w wysokoœci 100 kapsli.}
{341} {} {Ok. Oto 100 kapsli.}
{342} {} {To za du¿o. To nie jest tego warte.}
{343} {} {Mogê z nim porozmawiaæ? Zap³acê za to 10 kapsli.}
{344} {} {Jednak to nie gwarantuje, ¿e nie zostanie ponownie z³apany. Znasz tych kardyna³ów? Zwykli chuligani i buntownicy. S¹ zagro¿eniem dla spo³eczeñstwa.}
{345} {} {Nie bêdê siê z tym k³óci³.}
{346} {} {Katedra Ognia jest zaniepokojona tym, co siê sta³o. Ten facet by³ czêœci¹ naszego wywiadu. Daj mu odejœæ. Natychmiast.}
{347} {} {A wiêc to tak. Domyœli³em siê, ¿e ta sprawa œmierdzi szpiegostwem. Ok, nie chcê problemów z twoim koœcio³em. Dam mu odejœæ. Ale jeœli coœ pójdzie nie tak...}
{348} {} {Dziêkujê za zrozumienie Bruce.}
{349} {} {Ok.}

# Pytania dotycz¹ce niewolników
{350} {} {Powiedz mi, czym siê tutaj zajmujesz.}
{351} {} {To jest agencja rekrutacyjna, albo agencja najemników jak wolisz. Szukamy twardzieli do wykonywania niebezpiecznych misji. Zwykle jest to ochranianie kogoœ lub poszukiwanie przestêpców. Czy potrzebujesz czegoœ z tego?}
{352} {} {Nie, nic takiego.}
{353} {} {Có¿, jeœli zajdzie taka potrzeba, chêtnie pomogê. Oczywiœcie za odpowiedni¹ cenê.}
{354} {} {Oczywiœcie.}

{360} {} {Czy handlujecie te¿ niewolnikami?}
{361} {} {Handel niewolnikami? Niewielu mo¿e sobie pozwoliæ na taki luksus.}
{362} {} {Na przyk³ad kto?}
{363} {} {G³ówni klienci to Kolonia Flagpool i Blacharze. Ale nie nazwa³bym takiego produktu niewolnikiem. Zwykle s¹ to przestêpcy odsiaduj¹cy wyroki. Czemu Ciê to interesuje?}
{364} {} {Ze zwyk³ej ciekawoœci.}
{365} {} {Zwyk³a ciekawoœæ jest podejrzana. Mam nadziejê, ¿e rozumiesz, co to oznacza.}
{366} {} {Uch, tak myœlê.}
{367} {} {Rozwa¿am zakup kilku niewolników.}
{368} {} {To g³upie. Nie damy ci ani jednego wiêŸnia.}
{369} {} {W takim razie zapomnij.}
{370} {} {Szukam niewolników z Villi.}
{371} {} {Villa... To nic dla mnie nie znaczy.}
{372} {} {Szukam niewolników z Villi. Przywieziono ich tutaj z Flagpool.}
{373} {} {Villa... To nic dla mnie nie znaczy. Jeœli ci niewolnicy byli w Flagpool, nie bêdzie ³atwo ich znaleŸæ.}
{374} {} {Rozumiem. Przepraszam, ¿e przeszkadzam.}
{375} {} {Ech, znowu muszê sam to rozgryŸæ. Do widzenia.}
{376} {} {Zap³acê 100 kapsli za informacje.}
{377} {} {Brzmi ok. Mogê przejrzeæ najnowsze rachunki za wysy³kê i skontaktowaæ siê z naszymi agentami. P³atnoœæ z góry.}
{378} {} {Oto kapsle. Poczekam.}
{379} {} {Nie, spróbujê samemu to rozgryŸæ.}
{380} {} {Coœ siê wyjaœni³o. Kilku niewolników z Villi trafi³o do kolonii Flagpool. Zostali wykupieni przez czcicieli ognia i przewiezieni do ich w³asnej katedry. NajwyraŸniej byli cholernie dobrymi niewolnikami, skoro trzeba ich by³o przewoziæ na takie odleg³oœci. To, co siê z nimi sta³o, jest znane tylko mnichom. }
{381} {} {Dziêki Bruce. Czas odwiedziæ tê Katedrê Ognia. Czy cokolwiek to jest.}
{382} {} {Ehh. Rozgryz³bym to i bez ciebie.}
{1382} {} {Ehh. Rozgryz³abym to i bez ciebie.}
{383} {} {Coœ siê wyjaœni³o. Kilku niewolników z Villi trafi³o do kolonii Flagpool. Zostali wykupieni przez czcicieli ognia i wywiezieni na ciê¿kie roboty do Tu-San. NajwyraŸniej byli cholernie dobrymi niewolnikami, skoro trzeba by³o ich przewoziæ na takie odleg³oœci.}
{384} {} {Dziêki Bruce. Czas odwiedziæ to w¹tpliwe miasto. Mam nadziejê, ¿e je¿dz¹ tam karawany.}
{385} {} {Wiesz Bruce, twoja pomoc nie by³a zbyt pomocna. Do widzenia.}
{386} {} {Wrócê póŸniej. Teraz nie mam a¿ tylu kapsli.}

{390} {} {Jeden awanturnik musi zostaæ wyeliminowany. Nazywa siê George Crook.}
{391} {} {Ten sam dowódca Crook, który podbi³ zachodnie plemiê? Dlaczego chcesz go usun¹æ?}
{392} {} {Reprezentujê tylko klienta.}
{393} {} {Rozumiem. Ten stary ¿o³nierz zd¹¿y³ ju¿ zdenerwowaæ wiele osób w mieœcie. Co wiêcej, moi najlepsi ludzie kiedyœ przeszli do jego dru¿yny. A teraz Crook po prostu rzuca siê, nie wiedz¹c, co ze sob¹ zrobiæ. Nie rozumiem, jak kasyno toleruje jego pijackie wybryki.}
{394} {} {Wiêc podejmiesz siê tej misji?}
{395} {} {Có¿, tego nie powiedzia³em, ale za 500 kapsli œwiat o nim zapomni.}
{396} {} {Muszê pomyœleæ. Widzisz, to odpowiedzialny biznes.}
{397} {} {Ok. Oto kapsle. I tak, tej rozmowy nie by³o.}
{398} {} {Nie martw siê, zajmê siê wszystkim.}
{399} {} {Licze na was.}

#Polowanie na g³owê
{400} {} {Interesuje mnie szukanie przestepców. Za kogo i ile p³ac¹?}
{401} {} {(wzdycha) Kolejny ³owca nagród...}
{1401} {} {Lowca nagród w koronkowym fartuchu? Dok¹d zmierzamy...}
{402} {} {Czy coœ nie tak?}
{1402} {} {Ehem. Przypomnij mi, czy Twoim stra¿nikiem nie jest kobieta?}
{403} {} {Och, to o tobie ca³e miasto œpiewa podczas ostatnich walk na arenie? To wszystko zmienia.}
{404} {} {Potrafiê siê broniæ. Spokojnie.}
{405} {} {}
{406} {} {}
{407} {} {Masz przynajmniej karabin? To niebezpieczna praca, nie dla nowicjuszy. Ale jeœli chcesz zaryzykowaæ swoj¹ szyjê, decyzja nale¿y do Ciebie.}
{408} {} {Poradzê sobie.}
{409} {} {Na ulicy jest tablica og³oszeñ. Zawiera najnowsze informacje. System jest prosty. Znajdujesz przestêpcê wed³ug opisu, przynosisz mi jego g³owê i otrzymujesz za to nagrodê. Jakieœ pytania? Wiêc idŸ przed siebie. Powodzenia.}
{410} {} {Do zobaczenia Bruce Turner.}
{411} {} {Chcê porozmawiaæ o polowaniu na przestepców.}
{412} {} {Czy z³apa³eœ ju¿ kogoœ?}
{413} {} {Nie. Jeszcze nie.}
{414} {} {Tak myœla³em. PrzyjdŸ, kiedy z³apiesz przynajmniej jednego.}
{415} {} {Ok.}
{416} {} {Jestem Rangersem. Jestem zainteresowany prac¹.}
{417} {} {Rangersi zwykle nie lubi¹ naszej agencji. To dziwne, ¿e poci¹ga Ciê ta perspektywa.}
{418} {} {Jestem samotnym Stra¿nikiem.}
{419} {} {Ok...}

{420} {} {Oto g³owa Hernando Avilesa.}
{421} {} {Ach, to nasz stary przyjaciel, Hernando. Có¿, koniec z ¿artami o mnie, cholerny draniu?}
{422} {} {Oto g³owa Chucho Navarro.}
{423} {} {Suko, narobi³eœ strasznie du¿o ha³asu. Cieszê siê, ¿e jego g³oœne usta ju¿ nigdy wiêcej nie wydadz¹ ¿adnego dŸwiêku.}
{424} {} {Oto g³owa Adie Gorme.}
{425} {} {Ech, kiedyœ by³a piêkna i nawet wystêpowa³a w kasynach. Dziwny los. Nie rozumiem, co strzeli³o jej do g³owy.}
{426} {} {[Dalej.]}
{427} {} {Hernando Aviles nie ¿yje. Ale nie mog³em odzyskaæ jego g³owy.}
{428} {} {Chucho Navarro nie ¿yje. Ale nie mog³em odzyskaæ jego g³owy.}
{429} {} {Adie Gorme nie ¿yje. Niestety, jej g³owa le¿y na pustyni.}
{430} {} {Nie ma g³owy, nie ma nagrody. Ale cieszê siê, ¿e s³yszê tê wiadomoœæ. Do czasu otrzymania odpowiedzi zak³adam, ¿e mówisz prawdê.}
{431} {} {Uch, dobrze.}
{432} {} {Nie dostanê kapsli? To bardzo Ÿle.}
{433} {} {Dobra robota. Oto Twoje 500 kapsli. Mam nadziejê, ¿e nie zamierzasz jeszcze rezygnowaæ z tej aktywnoæci? Potrzebujemy ludzi takich jak ty.}
{434} {} {Pomyœlê o tym.}
{435} {} {Nie wiem, ta aktywnoœæ jest zbyt niebezpieczna.}

{440} {} {Czekaj. Okazuje siê, ¿e by³ to ostatni wódz Los Panchos. Ten cholerny gang w koñcu upad³. WyobraŸ sobie, jak ta wiadomoœæ rozchodzi siê po ca³ym Phoenix. Och, to bêdzie prawdziwa uczta dla mieszkañców miasta.}
{441} {} {Na pewno. Ale czy nie ma innych wodzów?}
{442} {} {Tych trzech posiada³o najwiêksze i najniebezpieczniejsze klany w Los Panchos. Reszta nie stanowi wiêkszego zagro¿enia. Teraz, bez ich wodzów, ca³e ich imperium siê rozpadnie, a zwykli rabusie zostan¹ znacznie os³abieni. Z pewnoœci¹ klany wypowiedzia³y ju¿ sobie wojny, rozpoczynaj¹c redystrybucje wp³ywów.}
{443} {} {To trochê dziwne. Ale jeszcze dziwniejsze jest to, ¿e wodzowie mieli takie samo piêtno jak ty i twoi najemnicy.}
{444} {} {Hmm. Któregoœ dnia musia³o to zostaæ ujawnione... Trochê upiêkszyliœmy ich legendê. W rzeczywistoœci ci trzej pracowali jako najemnicy w naszej gildii. Wiele siê tutaj nauczyli. Ale kiedy poczuli mo¿liwoœci i w³adzê nad ludŸmi, przestali interesowaæ siê uczciw¹ prac¹.}
{445} {} {Powinieneœ by³ mnie o tym ostrzec.}
{446} {} {Ci ludzie to wstyd dla gildii. Nasza reputacja nie mo¿e ucierpieæ.}
{447} {} {To rozs¹dne.}
{448} {} {Nie obchodzi mnie to.}
{449} {} {Masz wystarczaj¹co du¿o ukoñczonych kontraktów. Odpocznij i na razie baw siê dobrze. Zastanowie siê, jak¹ inn¹ prace mo¿esz dostaæ.}
{450} {} {Czyli to nie koniec? Swietnie, nie mogê siê doczekaæ.}
{451} {} {W¹tpiê, ¿e po tym, co us³ysza³em, bêdê chcia³ dla ciebie pracowaæ. Zegnaj Bruce.}
{452} {} {Có¿, to wspania³a wiadomoœæ.}
{453} {} {Kapsle s¹ dla mnie wa¿niejsze. Resztê mo¿esz wymyœliæ.}
{454} {} {Dobrze. Odpocznij i na razie baw siê dobrze. Zastanowie siê, jak¹ inn¹ prace mo¿esz dostaæ.}
{455} {} {Wiêcej pracy? Swietnie, nie mogê siê doczekaæ.}
{456} {} {Mam wystarczaj¹co du¿o kapsli, ¿eby wyjœæ z tego biznesu. Zegnaj Bruce.}
{457} {} {A co z now¹ prac¹?}

{460} {} {Przybywasz w sam¹ porê. Ju¿ chcia³em po ciebie wys³aæ. Jest nowy cel. I tym razem p³acê extra.}
{461} {} {Nietrudno zgadn¹æ, ¿e nowy cel jest wart tyle pieniêdzy. Czemu jest winny?}
{462} {} {(podnosi portret) To jest Gil McCord. Znany jako jeden z najlepszych strzelców i tropicieli. Zna dobrze swoj¹ pracê i potrafi wyjœæ z wszelkich k³opotów. Dlatego nie mo¿na go pozostawiæ przy ¿yciu.}
{463} {} {Hmm. To dziwne. To tak, jakbyœ mi czegoœ nie mówi³. Dlaczego najemnicy œcigaj¹ najemników?}
{464} {} {(wzdycha) Widzisz, trochê upiêkszy³em nasze osi¹gniêcia. W rzeczywistoœci wodzowie Los Panchos byli kiedyœ tak¿e naszymi najemnikami. Du¿o siê tu nauczyli i dlatego uda³o im siê zdobyæ przyczó³ek poza miastem.}
{465} {} {A Gil McCord?}
{466} {} {By³ ich agentem i szpiegiem. To wysz³o na jaw po tym, jak opró¿niliœmy bazy Los Panchos. Wygl¹da na to, ¿e Gil by³ zbyt chciwy i nieufny, wiêc pracowa³ dla obu stron, aby zawsze mieæ asa w rêkawie.}
{467} {} {Powinieneœ by³ powiedzieæ mi prawdê o gangu na samym pocz¹tku.}
{468} {} {Ci ludzie to wstyd dla gildii. Nasza reputacja nie mo¿e ucierpieæ.}
{469} {} {Nie obchodzi mnie to.}
{470} {} {To rozs¹dne.}
{471} {} {Zabij Gila McCorda i przynieœ mi jego g³owê.}
{472} {} {Zrobiê to, mo¿esz na mnie liczyæ.}
{473} {} {W¹tpiê, ¿e po tym, co us³ysza³em, bêdê chcia³ dla ciebie pracowaæ. Zegnaj Bruce.}

{474} {} {Wykona³em twoj¹ brudn¹ robotê. Oto jego g³owa.}
{1474} {} {Wykona³am twoj¹ brudn¹ robotê. Oto jego g³owa.}
{475} {} {(przytakuje smutno) Gil McCord. By³eœ jednym z nas. I popatrz do czego doprowadzi³a ciê chciwoœæ. Jego historia bêdzie przyk³adem dla innych. Zgodnie z ustaleniami masz prawo do 750 kapsli. Naprawdê mam nadziejê, ¿e ta kwota nie zryje Ci g³owy tak, jak w przypadku Gila. I odt¹d staraj siê nie rozpowiadaæ naszego ma³ego sekretu.}
{476} {} {Nie ma problemu, szefie. Zegnam.}
{477} {} {Po wszystkim, co widzia³em? Nie zrobiê tu nawet kroku.}

{480} {} {O Gil McCord.}
{481} {} {Jakieœ wiadomoœci?}
{482} {} {Jeszcze nie.}
{483} {} {Jak go znaleŸæ?}
{484} {} {W¹tpiê, ¿eby by³ w mieœcie. Ponadto nasi agenci donosz¹, ¿e podobn¹ w opisie osobê widzia³a karawana jad¹ca na po³udnie. Osiedli jest tam niewiele, mo¿esz je wszystkie sprawdziæ.}
{485} {} {Wiêc móg³by byæ wszêdzie. Nie traæ czasu.}
{486} {} {Dasz mi coœ na tê wycieczkê?}
{487} {} {I tak p³acê ju¿ wysok¹ cenê za tê pracê.}
{488} {} {Oczywiœcie.}
{489} {} {Potrzebujê dodatkowych kapsli na drogê i trochê amunicji.}
{490} {} {Ale jak mam znaleŸæ tego strzelca?}
{491} {} {W porz¹dku. Oto 100 kapsli na drogê. Jakiej amunicji potrzebujesz?}
{492} {} {Do pistoletu.}
{493} {} {Obrotowej.}
{494} {} {Do karabinu.}
{495} {} {Do automatu.}
{496} {} {Czy masz jakieœ pociski do wyrzutni?}
{497} {} {U¿ywam tylko broni energetycznej.}
{498} {} {A teraz idŸ znajdŸ tego sukinsyna. Dopóki nie zdobêdziesz jego g³owy, nie masz po co tu wracaæ.}
{499} {} {Zrozumiano, szefie.}
{1499} {} {Rozumiem, szefie.}

{500} {} {Jak godni zaufania s¹ twoi ludzie? Znasz ich umiejêtnoœci?}
{501} {} {Moi ludzie s¹ regularnie szkoleni. Znaj¹ swoj¹ wartoœæ. I wiem, kto lepiej nadaje siê do konkretnej pracy. Nie martw siê, to profesjonaliœci.}
{502} {} {Profesjonaliœci?}
{503} {} {Dok³adnie. Ka¿dy z nich to prawdziwy *Slayer*. Szybki i precyzyjny.}
{504} {} {Brzmi œwietnie. Ja te¿ mogê staæ siê takim prawdziwym *Slayer*? Mogê przejœæ szkolenie, aby nauczyæ siê tej umiejêtnoœci?}
{505} {} {Och, nie chcê o tym s³uchaæ. Zmieñmy temat, dobrze?}
{506} {} {Wiesz, to bardzo kosztowny biznes. I nie jesteœ jeszcze w naszej gildii. Bior¹c wszystko pod uwagê, bêdzie to kosztowaæ 50 000 kapsli. Ale po kursie mo¿esz dobrze zarabiaæ na wszelkiego rodzaju œmieciach.}
{507} {} {Nie mam przy sobie takich pieniêdzy i nigdy nie mia³em. I jest ma³o prawdopodobne, ¿e zdobêdê je nawet wyprzedaj¹c siê. Zegnaj.}
{508} {} {Nie przeszkadza mi to.}
{509} {} {Kapsle z góry i gotowe.}
{510} {} {Nie teraz, muszê siê przygotowaæ.}
{511} {} {[Po kryjomu podaj kapsle]}
{512} {} {Jesteœ silny psychicznie, sukinsynu. Bêdziesz doskona³ym ³owc¹ nagród.}
{1512} {} {Jesteœ silna psychicznie, suko. Bêdziesz doskona³ym ³owc¹ nagród.}
{513} {} {Uzyskano perk Slayer.}
{514} {} {Nawet jeœli jesteœ ju¿ w naszej gildii, musisz pokryæ wydatki. Nie jest to tanie, kosztuje 35 000 kapsli.}
{515} {} {Po ostatnim kontrakcie jesteœ gotów samemu szkoliæ rekrutów. Có¿, dlatego zrobiê wyj¹tek tylko dla Ciebie i samemu pokryjê wszystkie koszty.}
{516} {} {[Po cichu postêpuj zgodnie z instrukcjami Bruce'a]}
{517} {} {Jest za wczeœnie, byœ myœla³ o takich rzeczach. Podroœnij trochê.}
{518} {} {Ok.}