{100} {} {Widzisz cz³owieka Diego.}
{101} {} {Widzisz Miguela.}
{102} {} {Widzisz czaruj¹cego mê¿czyznê z w¹sami. Kogoœ ci przypomina.}
{103} {} {Widzisz Miguela, swojego wujka, który kiedyœ uciek³ z Villi.}

{110} {} {Zaczekaj chwilê, kim jesteœ?}
{111} {} {Kim jesteœ?}
{112} {} {Kto ciê tu wpuœci³?}
{113} {} {Co tutaj robisz?}
{114} {} {Jeszcze trochê, a zawo³am po ochronê.}
{115} {} {Nie mów mi, ¿e ukrywasz siê przed stra¿nikami.}
{116} {} {Twoja twarz jest mi z jakiegoœ powodu znana.}
{117} {} {Czy my siê znamy?}
{118} {} {Hej, czy my siê znamy?}
{119} {} {}

{120} {} {Jestem zajêty, hm, wa¿nymi badaniami. Tak, dok³adnie.}
{121} {} {Zajmujê siê tu nauk¹, kochanie.}
{122} {} {Co wiesz o akceleratorach plazmy? Tak myœla³em...}
{123} {} {Zrób coœ po¿ytecznego, przynieœ mi tequilê.}
{124} {} {Jeœli siê nudzisz, wróæ z powrotem do kasyna.}
{125} {} {Robiê du¿o badañ. Nie zrozumiesz.}
{126} {} {Dzisiaj bêdê pi³, a¿ stracê przytomnoœæ!}
{127} {} {}
{128} {} {}
{129} {} {}

#Pierwsze spotkanie
{200} {} {Hej, kto ciê tu wpuœci³? Zamkniête...}
{201} {} {?! A niech mnie }
{202} {} { co...}
{203} {} {Wujku Miguel, czy to ty? Dawno siê nie widzieliœmy!}
{204} {} {Och, jak uros³eœ! Nie pozna³em ciê od razu. Chocia¿ rysy twarzy nadal przypominaj¹ te u twojego ojca... Ale s³uchaj, to takie nieoczekiwane. Co Ty tutaj robisz?}
{1204} {} {Och, jak uros³aœ! Nie pozna³em ciê od razu. Chocia¿ rysy twarzy nadal przypominaj¹ te u twojego ojca... Ale s³uchaj, to takie nieoczekiwane. Co Ty tutaj robisz?}
{205} {} {Szukam mojego ojca. To d³uga historia. Krótko mówi¹c, on i inni wieœniacy zostali zabrani przez handlarzy niewolników.}
{206} {} {A wiêc to tak... Przykro mi. Ale ja nic o tym nie wiem. W ka¿dym razie najlepiej bêdzie, jeœli jak najszybciej opuœcisz to miasto.}
{207} {} {Dlaczego mnie wyganiasz? Wujku Miguel, przesz³em tyle mil, ¿eby ciê znaleŸæ!}
{1207} {} {Dlaczego mnie wyganiasz? Wujku Miguel, przesz³am tyle mil, ¿eby ciê znaleŸæ!}
{208} {} {Czy masz pojêcie, co siê wokó³ ciebie dzieje? Phoenix to nie Villa dla Ciebie, tutaj s¹ zupe³nie inne zwyczaje. Nie chcê nara¿aæ ciê na niebezpieczeñstwo. Jeœli szef siê dowie, oboje bedziemy mieæ k³opoty.}
{209} {} {Nie martw siê o to. Don Diego znikn¹³. Mia³ wypadek".}
{210} {} {Czy to Twoja zas³uga? Idiota! Diego by³ moim jedynym sposobem na przetrwanie w tym mieœcie. Co mam teraz zrobiæ?}
{1210} {} {Czy to twoja zas³uga? Ty g³upcze! Diego by³ moim jedynym sposobem na przetrwanie w tym mieœcie. Co mam teraz zrobiæ?}
{211} {} {Myœla³em, ¿e by³eœ jego prawie niewolnikiem.}
{212} {} {Nie powinieneœ by³ tu przychodziæ. Wszystko jest zbyt kruche. Diego by³ typem przestêpcy, to prawda. Ale to on rozwin¹³ to miasto. Co teraz? Czciciele ognia z pewnoœci¹ przejm¹ kontrolê nad kasynem. Czy wiesz co to znaczy? Widzê po oczach, ¿e nie.}
{213} {} {Wiêc mo¿esz mi pomóc znaleŸæ ojca?}
{214} {} {S³uchaj, jestem dobrze osadzony w tym mieœcie i nie chce mieæ k³opotów. Poszukaj pomocy gdzie indziej. Na przyk³ad... Wyznawcy ognia. To oni p³ac¹ najemnikom w ca³ej Arizonie za ich misyjne projekty.}
{215} {} {Ok. Do widzenia, wujku Miguel.}
{216} {} {Nie martw siê o to. Nied³ugo opuszczê Phoenix, moja sprawy siê tu skoñczy³y.}
{217} {} {Myœlisz? Obawiam siê, ¿e w Villi wszystko siê w³aœnie zaczê³o. Ta historia o zniewoleniu nie pozostanie niezauwa¿ona. Ciekawe, jak ty i twój ojciec poradzicie sobie dalej.}
{218} {} {Spróbujê. Do widzenia, wujku Miguel.}
{219} {} {Nie martw siê o to. Don Diego i ja jesteœmy w doskona³ych stosunkach.}
{220} {} {Jestem zaskoczony. Jesteœ o wiele bardziej zwinny i m¹drzejszy ni¿ twój padre. On nie chcia³ nawet s³yszeæ o nowych mo¿liwoœciach, jakie reszta œwiata mo¿e daæ Villi. A teraz ty jesteœ tutaj i ju¿ zaprzyjaŸniasz siê z jednym z najbardziej wp³ywowych ludzi w mieœcie. Dobra robota.}
{221} {} {Wiêc mo¿esz mi pomóc znaleŸæ ojca?}
{222} {} {Muszê wracaæ do Villi. Do widzenia, wujku Miguel.}
{223} {} {Czy jesteœ niewolnikiem Don Diego?}
{224} {} {Niewolnikiem? Nie... Nie, nie s¹dzê. Ale jeœli zechce, sprzeda ka¿dego w niewolê. Jest tutaj VIP-em, który prowadzi ca³e centrum biznesowe.}
{225} {} {Jeszcze coœ. Mo¿e on pomo¿e ci znaleŸæ ojca?}
{226} {} {Wiêc dobrze sobie radzisz. Ja muszê jechaæ do Villi, moje sprawy tutaj dobieg³y koñca.}

{230} {} {Hej, kto ciê tu wpuœci³? Zamkniête...}
{1230} {} {Hej, kto ciê tu wpuœci³? Zamkniête...}
{231} {} {?! Cholera, to mój ukochany siostrzeniec! Mi³o ciê widzieæ, zw³aszcza po tych wszystkich wydarzeniach.}
{1231} {} {?! Cholera, to moja ukochana siostrzenica! Mi³o ciê widzieæ, zw³aszcza po tych wszystkich wydarzeniach.}
{232} {} {Dawno siê nie widzieliœmy, wujku Miguel.}
{233} {} {Ale roœniesz. Pamiêtam ciê na poziomie sto³u. Tak wiele siê zmieni³o od tamtego czasu.}
{234} {} {O tak. Mam ci coœ do powiedzenia. O Villi, o ojcu, o rabusiach...}
{235} {} {Czekaj, szczerze mówi¹c, wiedzia³em o tobie i twojej misji. Chcia³em nawet wyjœæ z cienia i pomóc ci, gdy by³eœ w Phoenix. Ale czegoœ mi brakowa³o. Wydawa³o mi siê, ¿e Villa sta³a siê moj¹ przesz³oœci¹ i teraz ¿a³ujê, ¿e tak myœla³em.}
{236} {} {Tak, Villa jest teraz inna.}
{237} {} {Cieszê siê. I jestem zdumiony, jak uda³o Ci siê uratowaæ Villê w tak trudnych warunkach. Wiesz, wydawa³o mi siê, ¿e ci stêchli starzy ludzie prêdzej czy póŸniej doprowadz¹ Villê do zag³ady. I prawie im siê to uda³o, gdyby nie ty. Nie wiem, jak d³ugo bêd¹ jeszcze tak trwaæ.}
{238} {} {Cieszê siê. Ale wydaje siê, ¿e nie uda³o siê równie¿ przekonaæ tych zatêch³ych starych ludzi o potrzebie zmiany, prawda? Tak, widzê to w moich oczach. Villa potrzebuje ludzi takich jak ty i ja.}
{239} {} {Czujê, ¿e nie wierzysz w przysz³oœæ Villi?}
{240} {} {Dlatego opuœci³em ojczyznê. Sta³em siê cz³owiekiem bez domu, zerwa³em wszelkie wiêzi z przesz³oœci¹. Kiedy jesteœ zajêty odwiecznym zamieszaniem wokó³ myszy, nie myœlisz o niczym innym. Aby to zrozumieæ, musisz wyjœæ z pude³ka i spojrzeæ na œwiat wokó³. I zrobi³eœ to. Dobrze Ci idzie.}
{241} {} {Dziêki, wujku Miguel.}
{242} {} {Wcale nie. Ale nadszed³ czas, abyœ uratowaæ œwiat. Nie chcê, aby ktokolwiek w kasynie dowiedzia³ siê o naszej przesz³oœci.}
{243} {} {Do widzenia.}
{244} {} {To brzmi bluŸnierczo z twoich ust. W koñcu opuœci³eœ rodzinê, kiedy mog³eœ pomóc.}
{245} {} {Masz racjê. I nie bêdê ciê przekonywa³ ze jest inaczej. Ale wygl¹da na to, ¿e nadszed³ czas, abyœ uratowaæ œwiat. Nie chcê, aby ktokolwiek w kasynie dowiedzia³ siê o naszej przesz³oœci.}
{246} {} {Do widzenia.}

# Powtarzajacy siê dialog
{300} {} {Nawet nie zbli¿aj siê do mnie, kiedy jesteœmy w kasynie.}
{301} {} {Do widzenia.}

{310} {} {Czy wiesz, co wydarzy³o siê w Villi?}
{311} {} {Wiadomoœæ dotar³a do mnie k¹tem ucha.}
{312} {} {Czy wiesz, gdzie s¹ przetrzymywani nasi ludzie?}
{313} {} {Nie wiem dok³adnie. Te informacje mog¹ mieæ Obserwatorzy w katedrze.}
{314} {} {Co maj¹ z tym wspólnego Obserwatorzy?}
{315} {} {Niewolnicy s¹ wykorzystywani przez najemników, a najemnicy wykonuj¹ zadania dla wyznawców. W pewnym sensie dzia³aj¹ jako klienci lub patroni handlu niewolnikami, chocia¿ nie wszyscy to rozumiej¹. Kolonia Flagpool jest zbudowana za pieni¹dze Katedry lub Blacharzy, którzy zawarli wiele kontraktów z wyznawcami - niewolnicy s¹ teraz potrzebni wszêdzie.}
{316} {} {Twoja rodzina jest zmuszana do niewolniczej pracy, a ty jesteœ taki spokojny?}
{317} {} {Mój brat jest temu winien. Gdyby mnie pos³ucha³, ta tragedia w ogóle by siê nie wydarzy³a.}
{318} {} {To jasne, wujku. Zmieñmy motyw.}

{320} {} {Opowiesz mi o swojej ucieczce z Villi?}
{321} {} {Ucieczce? Czy tak nazywa to mój brat? Wiedzia³em, ¿e jest gotowy na ka¿d¹ pod³oœæ, ¿eby o mnie zapomnieli... Wiedz, drogi siostrzeñcu, ¿e nie chcia³em stamt¹d wyje¿d¿aæ, zosta³em ZMUSZONY. Chocia¿ nawet siê z tego cieszê.}
{1321} {} {Ucieczka? Czy tak to nazywa mój brat? Wiedzia³em, ¿e jest gotowy na ka¿d¹ pod³oœæ, ¿eby o mnie zapomnieli... Wiedz, droga siostrzenico, ¿e nie chcia³em stamt¹d wyje¿d¿aæ, zosta³em ZMUSZONY. Chocia¿ nawet siê z tego cieszê.}
{322} {} {Dlaczego zosta³eœ zmuszony?}
{323} {} {Po œmierci naszego ojca, twojego dziadka, Andreas, jako starszy brat, zacz¹³ rz¹dziæ Vill¹. Pod¹¿a³ za tradycj¹, ale ja stara³em siê wymyœlaæ nowe rozwi¹zania. Ju¿ wtedy zrozumia³em, ¿e Villa musi siê zmieniæ.}
{324} {} {Dlaczego?}
{325} {} {Ju¿ wtedy napotykaliœmy ³otrów z pustkowi, Stra¿ników i karawany z pobliskiego miasta. Wiedzieliœmy, ¿e poza dolin¹ istnieje ¿ycie. Ale starszy starannie ukrywa³ to przed reszt¹ mieszkañców. Tak jak inni starsi przed nim.}
{326} {} {I spiera³eœ siê z nim o to?}
{327} {} {Nie zgadzaliœmy siê co do losu Villi. Zaproponowa³em nawi¹zanie kontaktów z s¹siednimi miastami, u¿ycie starego sprzêtu do uprawy ziemi, ale nie pozwoli³ mi nawet otworzyæ ust. Powiedzia³ tylko ¿e opêta³ mnie Diablo... W koñcu powiedzia³em, ¿e ujawniê ludziom prawdê, wiêc po prostu wyrzuci³ mnie z osady.}
{328} {} {Co sta³o siê póŸniej?}
{329} {} {Dotar³em do pobliskiego miasta. W tamtym czasie dzia³a³a tam kopalnia i uda³o mi siê tam dobrze zarobiæ. Jednoczeœnie zapozna³em siê ze starymi technologiami. Potem kopalnia zosta³a zamkniêta i uda³em siê prosto do Phoenix.}
{330} {} {Kontynuuj.}
{331} {} {Tutaj ujrza³em piêkno cywilizacji w ca³ej jej okaza³oœci! Ale nawet tutaj mieszkañcy nie rozumiej¹ dobrze lub nie doceniaj¹ starych rzeczy. Mia³em szczêœcie, ¿e Don Diego przyj¹³ mnie do pracy. Do za³o¿enia kasyna potrzebowa³ koneserów starej technologii. Od tamtej pory jestem tu.}
{332} {} {Wiêc to w³aœnie tutaj robisz - pijesz i oddajesz siê przyjemnoœciom?}
{333} {} {Nie œpiesz siê, drogi siostrzeñcu. Pracowa³em wystarczaj¹co ciê¿ko, ¿eby teraz piêknie ¿yæ. Poza tym moja maszyna jest zawsze gotowa do pracy.}
{1333} {} {Nie œpiesz siê, droga siostrzenico. Pracowa³em wystarczaj¹co ciê¿ko, ¿eby teraz piêknie ¿yæ. Poza tym moja maszyna jest zawsze gotowa do pracy.}
{334} {} {Czym jest ta maszyna?}
{335} {} {Masz na myœli maszynê w twoich spodniach?}
{336} {} {Jakby to powiedzieæ... Wykonujê prace techniczne dla Don Diego.}
{337} {} {Na przyk³ad?}
{338} {} {Przepraszam, ale szef nie chce, ¿ebym o tym mówi³.}
{339} {} {Ok, zmieñmy temat.}
{340} {} {Czy ta historia kiedykolwiek siê skoñczy?}
{341} {} {„Stare technologie” to nie tylko automaty do gier, prawda?}
{342} {} {Hej, wiesz, siostrzeñcu. Powiem ci to - Diego chce byæ œwiadomy wszystkiego, co przynosi kapsle, si³ê i moc. By³em dla niego niezwykle wa¿nym znaleziskiem.}
{1342} {} {Hej, wiesz, siostrzeñcu. Powiem ci to - Diego chce byæ œwiadomy wszystkiego, co przynosi kapsle, si³ê i moc. By³em dla niego niezwykle wa¿nym znaleziskiem.}
{343} {} {Jaki rodzaj pracy dla niego wykonywa³eœ?}
