{100} {} {Widzisz Georga Crooka.}
{101} {} {Widzisz swojego starego przyjaciela, Georga Crooka, wróci³ z San Brahmin. Jest pijany.}
{102} {} {Hej kolego, jak sobie z tym poradzi³eœ? Bar-r-duck!}
{103} {} {Twoja matka...}

{200} {} {Zostaw mnie w spokoju - boli mnie g³owa.}
{201} {} {Zostaw mnie samego z tym piêknym ³ó¿zkiem.}
{202} {} {Muszê siê przespaæ po tylu litrach tequili.}
{203} {} {Ja. Chcê. Spaæ!}
{204} {} {* Ik *}
{205} {} {Daj mi trochê wody. Albo rewolwer.}
{206} {} {Muszê siê tylko zdrzemn¹æ.}
{207} {} {Pozwól mi odpocz¹æ, a potem kontynuuj.}
{208} {} {}
{209} {} {}

{210} {} {Och, to ty! Nalej sobie drinka.}
{211} {} {Hej, ale porobiliœmy tych dzikusów!}
{212} {} {Pamiêtasz, jak umieœciliœmy go na miejscu wodza?}
{213} {} {Teraz ca³a okolica boi siê ciebie i mnie, amigo.}
{214} {} {Czy Aaron wrêczy³ ci ju¿ nagrodê?}
{215} {} {Hej, upijemy siê i skopiemy ty³ek temu barmanowi?}
{216} {} {Hej, daj mi te dziewczynê ze sceny.}
{217} {} {Cholera, po prostu wypijê wszystko z butelki tequili.}
{218} {} {Uwa¿aj na ty³y, amigo.}
{219} {} {Walczmy! Zacznijmy rozróbê!}
