{100} {} {Widzisz ¿ebraka.}
{101} {} {Widzisz dziewczynê z dwoma marakasami. Za ich pomoc¹ tworzy muzykê.}
{102} {} {Dziêkujê panu.}
{1102} {} {Dziêkujê, panienko.}
{103} {} {Trzymaj siê ode mnie z dala!}
{104} {} {* Ziewa i przeciera oczy w ciszy *}

{200} {} {(Dziewczyna widz¹c ciê, zaczyna potrz¹saæ marakasami i nuciæ jak¹œ ledwie zrozumia³¹ piosenkê). "Rad-karakan-chik, rad-karakan-chik. On nie mo¿e ju¿ biegaæ..."}
{201} {} {[Pos³uchaj]}
{202} {} {[PrzejdŸ obok]}
{203} {} {"Wszystko przez to, wszystko przez... Ze pozbawiono go tylnych nóg w bitwie."}
{204} {} {[S³uchaj dalej]}
{205} {} {"Trudno bez ³apy, ciê¿ko bez ³apy. Ale on biegnie, biegnie, biegnie."}
{206} {} {[S³uchaj dalej]}
{207} {} {"Stale i bez ogl¹dania siê za siebie. On chce ¿yæ, chce ¿yæ."}
{208} {} {}
{209} {} {(cicho zabierz s³oik ¿ebraczki)}
{210} {} {Ja te¿ nie mam nic wartoœciowego. Mo¿e innym razem.}
{211} {} {Oto jeden kapsel, niczego sobie nie odmawiaj.}
{212} {} {Trzymaj dwia kapsle, zas³ugujesz.}
{213} {} {WeŸ te trzy kapsle i wydaj na jedzenie.}
{214} {} {Jestem dzisiaj hojny. Oto cztery kapsle.}
{1214} {} {Jestem dzisiaj hojna. Oto cztery kapsle.}
{215} {} {Nie chcê, ¿ebyœ cierpia³a na ulicy. WeŸ te piêæ kapsli.}
{216} {} {Co za okropny jazgot dla moich uszu! Nie rób ju¿ tego ha³asu.}
{217} {} {Brawo! Swietnie sobie radzisz, m³oda damo.}
{218} {} {Ciekawa piosenka. Ale nad wykonaniem warto popracowaæ.}

{220} {} {Dziêkujê panu...}
{1220} {} {Dziêkujê pani...}
{221} {} {Hmm. Mog³aœ powiedzieæ to z wiêkszym szacunkiem. Ale czego mo¿na siê spodziewaæ po takim kundlu...}
{222} {} {Proszê. Mam nadziejê, ¿e to pomo¿e.}

{230} {} {Koniec zabawy, oddasz mi teraz wszystkie swoje kapsle!}
{231} {} {(cicho i z przera¿eniem krêci g³ow¹, cofaj¹c siê o krok)}
{232} {} {Przepraszam, mój b³¹d. Oczywiœcie niczego od Ciebie nie wezmê.}
{233} {} {Przestañ, daj wszystkie kapsle!}
{234} {} {(Dziewczyna zwinnie wyrywa ci siê z r¹k, wykorzystuj¹c twoj¹ opiesza³oœæ.)}
{235} {} {Biegnij, ma³a suko, i tak ciê dorwê!}
{236} {} {Tym razem masz szczêœcie.}
{237} {} {Puœæ! (Trzymaj¹c dziewczynê za ³okieæ, znajdujesz w jej rzeczach dziesiêæ kapsli i bierzesz je dla siebie.) Ratunku! Pomocy!}
{238} {} {Nie próbuj siê mœciæ, jasne? A teraz wynoœ siê.}
{239} {} {Mo¿esz iœæ. Interesowa³y mnie tylko kapsle.}
