{100} {} {Widzisz administratora.}
{101} {} {Widzisz kobietê w œrednim wieku. Ma przyzwoity poziom dochodów, s¹dz¹c po ubraniu.}
{102} {} {* Patrzy na twoj¹ zbrojê z zaciekawieniem, a potem ze strachem *}
{103} {} {Jesteœmy zamkniêci. PrzyjdŸ w godzinach pracy.}

#Dialog
{200} {} {Tak?}
{201} {} {Do widzenia.}
{202} {} {Muszê wys³aæ paczkê do Flagpool.}
{203} {} {Muszê wys³aæ paczkê do Tu-San.}
{204} {} {Mo¿emy tylko porozmawiaæ?}
{205} {} {Nie mam czasu na bezczynne gadki. Czy zamierzasz wys³aæ paczkê?}
{206} {} {Prawdopodobnie.}

# Wysy³anie paczki
{210} {} {Koszty wysy³ki to }
{211} {} { kapsli. Mo¿esz u¿yæ tego pude³ka na œcianie. Po dokonaniu p³atnoœci zabierzemy Twoje rzeczy na miejsce.}
{212} {} {Oto nale¿noœæ, paczka mo¿e zostaæ wys³ana.}
{213} {} {Nie teraz.}

{214} {} {Poda³am ju¿ cenê. Czy mam wezwaæ ochronê?}
{215} {} {}
{216} {} {To tylko nieporozumienie. Wrócê.}

{217} {} {Poczekaj, a¿ wype³niê dziennik. Dobra. Mo¿esz odebraæ paczkê w tym samym biurze Sonora Express.}
{218} {} {Dobrze.}

{220} {} {Jako wyznawca Ognia, czy mogê spodziewaæ siê specjalnych cen?}
{1220} {} {Czy jako wyznawca Ognia mogê spodziewaæ siê specjalnych cen?}
{221} {} {Tak, oczywiœcie. Mamy specjalne umowy ze œwi¹tyni¹.}
{222} {} {To dobrze.}
{223} {} {Dobrze, ¿e wpad³eœ. Ale nie oczekuj zni¿ki. Otrzyma³am wytyczne z góry, wiêc nawet nie myœl o wniesieniu skargi na mnie.}
{224} {} {Rozumiem. Nie ma problemu.}
{225} {} {Co ty do cholery robisz, dziwko!}
{226} {} {Nie. Mam zamiar siê st¹d wydostaæ. Absolutnie.}

{230} {} {Witamy. Jak mogê pomóc?}
{231} {} {Przepraszam, co to za miejsce?}
{232} {} {To jest punkt us³ug kuriersko pocztowych. Czy znak na zewn¹trz coœ ci mówi?}
{233} {} {Ta us³uga jest trochê... niezwyk³a, bior¹c pod uwagê spalon¹ pustyniê dooko³a. Co przesy³acie?}
{234} {} {Jesteœmy gotowi przes³aæ wszystko, nawet martw¹ pch³ê, jeœli cena jest odpowiednia. Jesteœ po prostu ciekawy czy chcesz z³o¿yæ zamówienie?}
{235} {} {Mo¿e. Chcê wiedzieæ wiêcej.}
{236} {} {Nie, nie, po prostu przyci¹gn¹³ mnie znak. PA.}
{237} {} {Myœlê, ¿e jesteœ dla mnie niemi³a. Z tak¹ obs³ug¹ ju¿ tu nie zrobiê wiêcej ani kroku.}

{280}{}{Muszê wiedzieæ, czy twoje karawany towarzyszy³y pewnej osobie.}
{281}{}{Prowadzimy dziennik. Ale za darmo niczego nie mogê zrobiæ.}
{282}{}{Dobrze. Zap³acê 10 kapsli.}
{283}{}{Wiêc nie rób nic. Do widzenia.}
{284}{}{Ok. Kogo szukasz?}
{285}{}{German Genaro Cipriano Gomez Valdez y Castillo. Kierowa³ siê do osady zwanej Platform¹ przez Casa Nueva.}
{286}{}{Dziennik mówi, ¿e ten cz³owiek jecha³ dyli¿ansem. Ale jest te¿ zapis, ¿e dyli¿ans nie dotar³ do celu. Zosta³ obrabowany przez rabusiów z autostrad.}
{287}{}{Rozumiem. Dziêkujê.}

# Zagubiona paczka z mapy œwiata
{290} {} {Podczas podró¿y natkn¹³em siê na tê paczkê.}
{291} {} {Co to jest?}
{292} {} {NajwyraŸniej listy ze wschodnich kolonii. Kurier zosta³ napadniêty przez bandytów i nie móg³ ich tu przywieŸæ.}
{293} {} {Och, teraz rozumiem. Wiele osób czeka na wieœci z nowych kolonii. Ale z powodu bandytów tracimy jedn¹ karawanê po drugiej. Có¿, bêdê musia³a odebraæ te listy od Ciebie za po³owê op³aty kuriera.}
{294} {} {Lepsze ni¿ nic.}
{295} {} {Proszê. Dziêkujemy za dostawê.}
{296} {} {Powodzenia.}
{297} {} {Zachowaj kapsle dla siebie. Wystarczy, ¿e na te listy czekaj¹ zwykli ludzie.}
{298} {} {To pierwszy raz, kiedy widzê, jak ktoœ odrzuca kapsle. Jesteœ wspania³¹ osob¹. I dziêkujê za dostawê.}
{299} {} {Cieszê siê, ¿e mogê pomóc. Szczêœcia.}
{1299} {} {Mi³o by³o Ci pomóc. Szczêœcia.}

#Zadanie
{300} {} {Potrzebujê legalnej pracy. Czy masz wolne miejsca pracy?}
{301} {} {Mamy wystarczaj¹c¹ liczbê pracowników.}
{302} {} {Rozumiem.}
{303} {} {Jednak... jest jeden "delikatny" przypadek, z którego wszyscy rezygnuj¹.}
{304} {} {S³ucham.}
{305} {} {We wschodnich slumsach rabusie zaatakowali naszego kuriera i zabrali ca³y jego dobytek, w tym œwie¿e listy. Musimy je znaleŸæ i zwróciæ. Czy jesteœ gotowy, aby siê tym zaj¹æ? To ryzykowna sprawa, ale firma zap³aci 50 kapsli za zwrot listów.}
{306} {} {Wygl¹da mi to na jeden z lokalnych gangów. Nie s¹dzê, ¿eby ich znalezienie by³o du¿ym problemem. Jestem za.}
{307} {} {Bardzo dobrze. P³atnoœæ przy zwrocie. Powodzenia.}
{308} {} {Do widzenia.}
{309} {} {Rabusie, slumsy... Nie, nie zaryzykujê dla kilku kapsli.}
{310} {} {Oczywiœcie, ¿e rozumiem. Wszystkiego najlepszego.}
{311} {} {Do widzenia.}
{312} {} {Przypomnij mi, gdzie skradziono te listy?}
{313} {} {Obszar wschodnich slumsów, w którym mieszkaj¹ biedni. Jest te¿ tam ta nieludzka arena, na której tocz¹ siê walki na œmieræ i ¿ycie.}
{314} {} {Dziêki. Proszê o inne pytanie.}
{315} {} {Ok, do widzenia.}
{316} {} {Natkn¹³em siê na kilka listów. Wygl¹da na to, ¿e nie dotar³y do swoich adresatów.}
{317} {} {Zobaczmy... Ach, nareszcie! Listy te uznano za zaginione, gdy nasz kurier zosta³ napadniêty w slumsach. Nie masz pojêcia, jak¹ przys³ugê nam oddajesz.}
{318} {} {Nie ma za co. Czy za znalezisko nie nale¿y siê zap³ata?}

{320} {} {Czy to s¹ te listy? Zosta³y zabrane przez cz³owieka z gangu Czerwonych Kardyna³ów.}
{321} {} {Ach, wreszcie! Nie masz pojêcia, jak¹ przys³ugê nam wyœwiadczasz. Pozwól mi zobaczyæ... Tak, to s¹ te.}
{322} {} {A moje kapsle?}
{323} {} {Oczywiœcie, tutaj jest 50 kapsli. Wiesz co, zap³acê ci o 25 wiêcej kapsli za ich wys³anie. Dok³adniej, za dostarczenie jednego z tych listów. Adresowany jest do pewnego Steve'a mieszkaj¹cego w tych najniebezpieczniejszych slumsach. Wygl¹da na to, ¿e potrafisz siê tam poruszaæ bez strachu, a my potrzebujemy tylko * gwarantowanej * dostawy.}
{324} {} {Oczywiœcie, wiêcej kapsli mnie nie skrzywdzi.}
{325} {} {Zawsze tak jest. Jeœli raz pomo¿esz, wszyscy bêd¹ czegoœ od ciebie chcieli. Ok, chodŸ tutaj.}
{326} {} {Podpiszmy krótk¹ umowê. I... Swietnie. Udaj siê teraz do slumsów i przeka¿ list za pokwitowaniem. Powodzenia.}
{327} {} {[Opuœæ biuro]}

{330} {} {List zosta³ dostarczony pod wskazany adres. Oto pokwitowanie odbiorcy.}
{331} {} {Swietnie. Oto twoje uczciwie zarobione 25 kapsli. Mam nadziejê, ¿e nie ma potrzeby wyjaœniania, ¿e nie bêdziemy tolerowaæ oszustwa.}
{332} {} {Oczywiœcie.}
{333} {} {Dziêkujemy za wspó³pracê, praca z tob¹ by³a przyjemnoœci¹. Ale obawiam siê, ¿e w najbli¿szej przysz³oœci nie bêdziemy mieli dla Ciebie ¿adnych nowych zleceñ.}
{334} {} {Do widzenia.}
{335} {} {O tym liœcie. Nie ma nikogo, kto by móg³ go odebraæ. Adresat zmar³.}
{336} {} {Co za szkoda. Có¿, to siê zdarza. Umowa uwzglêdnia podobne przypadki. Otrzymasz tylko po³owê kapsli. Oto Twoje 12 kapsli.}
{337} {} {To oburzaj¹ce! Z¹dam pe³nej zap³aty!}
{338} {} {Przeczytaj umowê. Podpisa³eœ j¹ w³asnorêcznie. Nie ma sensu krzyczeæ.}
{339} {} {Co... Jak... Ur-rh.}
{340} {} {Có¿, to sprawiedliwe. Nie mam ¿adnych zarzutów.}
{341} {} {[WyjdŸ z biura w dobrym nastroju]}
{342} {} {Przypomnij mi, gdzie ten list powinien zostaæ dostarczony?}
{343} {} {(wzdycha ze smutkiem) List jest zaadresowany do pewnego Steve'a, który mieszka w slumsach niedaleko areny. Powtarzam: w slumsach niedaleko areny. Jasne? Zapisz sobie, ¿eby nie zapomnieæ.}
{344} {} {S³yszê ciê kobieto.}
{345} {} {Dziêki, teraz zrozumia³em.}