{100} {} {Widzisz buntownika.}
{101} {} {Widzisz mê¿czyznê w kominiarce. Wydaje siê, ¿e siê przed kimœ ukrywa.}
{102} {} {Wydaje siê, ¿e to koniec. Sam znajdê swoj¹ drogê. Do zobaczenia w bazie.}
{103} {} {Dziêkujê za pomoc. Razem odzyskamy wolnoœæ dla Phoenix.}
{104} {} {Oto ruiny niegdyœ du¿ego miasta. Na pewno poziom promieniowania jest tu zwiêkszony.}

# Pierwszy dialog
{200} {} {Ach... kim jesteœ?}
{201} {} {Alicja i Marcos mnie przys³ali. Stracili z tob¹ kontakt.}
{202} {} {Wreszcie... Ale b¹dŸ cicho! Nie mo¿emy byæ g³oœno. Nie wiem, jak ci mnisi mnie zaskoczyli. S¹ sprytniejsi, ni¿ siê wydaj¹. Czy mo¿esz mi pomóc wróciæ do bazy?}
{203} {} {A co z twoim zadaniem?}
{204} {} {Kurwa. Teraz musimy wydostaæ siê ze szponów tych sekciarzy. Dodatkowo wzmacniacz pozosta³ w budynku naprzeciwko, teraz nie mo¿emy siê nawet do niego zbli¿yæ.}
{205} {} {Musimy wyjœæ.}
{206} {} {Nie bêdziesz móg³ przejœæ obok kultystów niezauwa¿ony... Hmm, jak to zrobi³eœ?}
{207} {} {Bêdziemy musieli wywalczyæ sobie drogê do wyjœcia. Jesteœ gotowy? ChodŸmy zatem.}
{208} {} {Twoja misja musi zostaæ zakoñczona jako pierwsza. Zaczekaj tutaj.}

# Powtarzajacy siê dialog
{210} {} {Musimy wracaæ do centrali. I uwa¿aj ¿eby go dostaæ ogona.}
{211} {} {Oczywiœcie. ChodŸmy st¹d.}
{212} {} {Poczekaj tutaj, idê na zwiad.}
{213} {} {ChodŸmy. Czekaj¹ na nas w Sztabie Generalnym.}
{214} {} {Poczekaj tutaj, zbadam sytuacjê.}
{215} {} {Przypomnij mi, jakie masz zadanie?}
{216} {} {Mia³em zainstalowaæ wzmacniacz w tym starym budynku, on wci¹¿ tam jest. Musia³em jednak porzuciæ ca³y sprzêt, ¿eby nie daæ siê z³apaæ. I nie wrócê tam, to zbyt ryzykowne. A jeœli wpadnê w zasadzkê?}
{217} {} {Wygl¹da na to, ¿e to koniec. Sam znajdê drogê. Do zobaczenia w bazie.}
{218} {} {Ok, do zobaczenia.}
{219} {} {Wygl¹da na to, ¿e to koniec. Gdyby nie ty, czeka³by mnie smutny los. Dziêki za pomoc.}
