{100} {} {Widzisz Alicjê.}
{101} {} {Widzisz kobietê o pewnym siebie spojrzeniu. Gdybyœ chcia³ j¹ do czegoœ przekonaæ, by³byœ kompletnie bezradny.}
{102} {} {Jesteœ na muszce. Ale pozwolê Marcosowi zdecydowaæ, co z tob¹ zrobiæ.}
{103} {} {To z twojego powodu zawiedliœmy nasz¹ misjê!}
{104} {} {Wygraliœmy dziêki tobie. Dziêkujê Ci.}

#Dialog
{200} {} {Marcos da³ ci pozwolenie na przebywanie w siedzibie g³ównej. Ale nie myœl, ¿e to od razu czyni ciê godnego zaufania. Zas³u¿ na to swoimi czynami i uwa¿aj na jêzyk.}
{201} {} {Oczywiœcie, rozumiem.}
{202} {} {Bior¹c pod uwagê twój odbiór, nie ma potrzeby mówiæ o zaufaniu.}

{210} {} {Witaj bracie. Jak mogê ci pomóc?}
{1210} {} {Pozdrowienia siostro. Jak mogê ci pomóc?}
{211} {} {Do zobaczenia siostro.}

{220} {} {Opowiedz mi o sobie.}
{221} {} {Nie rozmawiamy o naszej przesz³oœci. Zebraliœmy siê tutaj nie po to, by sobie rozmawiaæ, ale we wspólnej sprawie.}
{222} {} {Jak dosta³aœ siê do tego ruchu?}
{223} {} {Oczywiœcie, przepraszam.}
{224} {} {Mówiê, ¿e to nie ma znaczenia. Mogê tylko powiedzieæ, ¿e pocz¹tkowo mia³am osobiste motywy. Teraz walczê o wspólny cel, jest znacznie wy¿szy.}
{225} {} {Smutna historia. Nie masz nic przeciwko, jeœli zapytam ciê o coœ innego?}
{226} {} {Opowiedz mi o Marcosie.}
{227} {} {To wspania³y cz³owiek.}
{228} {} {Um, czy to wszystko?}
{229} {} {Có¿, ma mroczn¹ przesz³oœæ. Wiem tylko, ¿e przed powstaniem partii prze¿y³ jak¹œ tragediê.}
{230} {} {Kochasz go?}
{231} {} {Co... jak... S³uchaj, oczywiœcie, ¿e podziwiam go jako przywódcê. W koñcu zgromadzi³ tak wielu ludzi pod wspólnym szczytnym celem. Ale nawet nie znam jego twarzy, nigdy przede mn¹ nie zdejmowa³ kominiarki.}
{232} {} {Dziêki za wyczerpuj¹c¹ odpowiedŸ.}
{233} {} {Rozumiem. Dziêkujê za odpowiedŸ.}
{234} {} {Co tu robisz?}
{235} {} {To jest nasz sztab generalny. Oczywiœcie omawiamy tutaj plany, przechowujemy i przygotowujemy sprzêt.}
{236} {} {Czy mogê korzystaæ z twoich warsztatów?}
{237} {} {Nie mam nic przeciwko, jeœli pomaga to ci w naszej wspólnej walce.}
{238} {} {Dziêki.}
{239} {} {Co to za miejsce?}
{240} {} {To by³a kiedyœ stacja metra. Przejœcia zawali³y siê podczas bombardowania nuklearnego, pozostawiaj¹c tylko wyjœcie do kana³ów. Dlatego niewielu mo¿e znaleŸæ to miejsce.}

# Wydawanie sprzêtu
{250} {} {Potrzebujê sprzêtu, aby ukoñczyæ tê misjê.}
{251} {} {Ok. Marcos mówi, ¿e nale¿y ci ufaæ. Zapraszamy do zapoznania siê z naszymi dostawami. Czego potrzebujesz do zadania?}
{252} {} {Nic. Wrócimy do tego trochê póŸniej.}
{253} {} {Jeœli to nie wystarczy, mo¿esz iœæ do sklepu z broni¹ w centrum miasta. W³aœciciel sprzedaje nam towar w tajemnicy przed sekt¹. Po prostu powiedz mu has³o: „Nie ma ludzi bardziej wiernych cesarzowi ni¿ garstka ch³opów”.}
{254} {} {Swietnie. Idê na misjê. Czeœæ, Alicjo.}
{255} {} {}
{256} {} {Czego potrzebujesz.}
{257} {} {Sprzêt snajperski.}
{258} {} {Oto strzelba myœliwska i pude³ko nabojów. To ci wystarczy.}
{259} {} {Sprzêt szturmowy.}
{260} {} {Czy to nie zbyt ryzykowne? Okej, ty i Marcos wiecie lepiej. Oto pistolet maszynowy i pude³ko nabojów kalibru 10 mm. WeŸ te¿ kilka granatów i œrodek pobudzaj¹cy na wypadek kontuzji.}
{261} {} {Sprzêt szpiegowski.}
{262} {} {Zobaczmy. Flara w przypadku ciemnoœci, stealth boy w celu ukrycia siê i materia³y wybuchowe w nag³ych przypadkach. WeŸ te¿ œrodek pobudzaj¹cy gdyby coœ posz³o nie tak.}

{270} {} {Czy znasz siê na materia³ach wybuchowych? Przyda³aby mi siê taka umiejêtnoœæ.}
{271} {} {Przepraszam, ale nie mam czasu na wyk³ady.}
{272} {} {Mogê zap³aciæ kapslami. To zrównowa¿y twój wysi³ek.}
{273} {} {Te kapsle mog¹ nam bardzo pomóc w naszej walce. Jeœli zdobêdziesz 350 kapsli, naucze ciê sztuczek, które znam.}
{274} {} {Ok. wrócê z kapslami.}
{275} {} {Rozumiem, zapomnij.}
{276} {} {Bior¹c pod uwagê, ¿e uratowa³em agenta Partii, mo¿esz mi zaufaæ, nie s¹dzisz?}
{277} {} {Racja. Przepraszam, zbyt wiele siê teraz dzieje. Mimo to uczciwe by³oby przekazanie na nasz¹ rzecz stu kapsli.}
{278} {} {Oto sto kapsli...}
{279} {} {Oto 350 kapsli...}

#Tasks
{300} {} {Marcos wys³a³ mnie na powierzchniê. Co powinno zostaæ tam zrobione?}
{301} {} {Ok, s³uchaj uwa¿nie. Jeden z naszych agentów poszed³ do ruin na powierzchni, aby ustawiæ wzmacniacz radiowy. Od tego czasu komunikacja z nim zosta³a utracona. Nie wiemy, co siê sta³o. ZnajdŸ go i dokoñcz jego zadanie.}
{302} {} {Dlaczego potrzebujesz wzmacniacza radiowego w ruinach?}
{303} {} {U¿ywamy komunikacji radiowej do w³asnej komunikacji i pods³uchiwania kultystów. Ale pod ziemi¹ sygna³ jest zag³uszony. Dlatego potrzebujemy wzmacniacza powierzchniowego.}
{304} {} {Rozumiem. Kierujê siê na powierzchniê.}
{305} {} {Czy dasz mi sprzêt do tego zadania?}
{306} {} {Czeka ciê prosta wycieczka do ruin. Jeœli nie potrafisz sobie poradziæ nawet z tak¹ sytuacj¹, jak siê tu dosta³eœ? W ka¿dym razie Marcos nie pozwoli³ wydaæ ci sprzêtu.}
{307} {} {Rzeczywiœcie. Do zobaczenia póŸniej.}
{308} {} {Jeœli umrê, bêdzie to twoja wina.}

{310} {} {Gdzie dok³adnie mogê znaleŸæ tego agenta?}
{311} {} {IdŸ do du¿ego kana³u i kieruj siê na zachód. Musisz przedostaæ siê do ruin starego miasta w pobli¿u stacji Union. Mam nadziejê, ¿e siê nie zgubisz.}
{312} {} {Porozmawiajmy o moim zadaniu.}
{313} {} {Jak postêpy?}
{314} {} {Na razie brak. Zajmê siê tym teraz.}
{315} {} {Mam wieœci o tym agencie. Jest martwy.}
{316} {} {Cholera... To Ÿle. A co ze wzmacniaczem sygna³u?}
{317} {} {Jeszcze nie wiem.}
{318} {} {Wzmacniacz jest zainstalowany, mo¿esz sprawdziæ si³ê sygna³u.}
{319} {} {W takim razie nie traæmy czasu...}
{320} {} {[Dalej.]}
{321} {} {To jest o wiele wa¿niejsze. ZnajdŸ wzmacniacz i umieœæ go na powierzchni. Nie mamy innych takich.}
{322} {} {Zajmê siê t¹ spraw¹.}
{323} {} {Zaginiony agent wpad³ w zasadzkê mnichów. Ale uda³o mi siê go uratowaæ.}
{324} {} {Dziêki, doceniamy uratowanie agenta. Ale ktoœ nadal musi zainstalowaæ wzmacniacz na powierzchni.}
{325} {} {}
{326} {} {Zajmê siê tym.}
{327} {} {Uda³o mi siê znaleŸæ i uruchomiæ wzmacniacz fal radiowych.}
{328} {} {Bardzo dobrze. Poczekaj chwilê, muszê sprawdziæ si³ê sygna³u...}
{329} {} {[Dalej.]}
{330} {} {Dobra robota. A co z naszym agentem?}
{331} {} {Twój agent nie ¿yje.}
{332} {} {To Ÿle... Bardzo Ÿle. Poczekaj chwilê, muszê sprawdziæ sprzêt...}
{333} {} {[Dalej.]}
{334} {} {Nie mog³em go znaleŸæ. Mo¿e uciek³?}
{335} {} {Bardziej prawdopodobne, ¿e zosta³ schwytany przez kultystów. Spróbuj dowiedzieæ siê, co siê z nim sta³o, kiedy ja sprawdzam sprzêt.}
{336} {} {Ok, zajmê siê t¹ spraw¹.}
{337} {} {Dobra robota. Teraz bêdzie nam ³atwiej s³uchaæ audycji czcicieli ognia. Powiedz Marcosowi o swoim sukcesie.}
{338} {} {Ok. Czeœæ, Alicjo.}