{100} {} {Widzisz Inkwizytora.}
{101} {} {Widzisz mê¿czyznê w sutannie. WyraŸnie szuka kogoœ wœród tych ruin.}
{102} {} {Umrzesz w imiê ognia.}
{103} {} {Bój siê Swietego Ognia, obcy!}
{104} {} {Chwalcie Swiêty Ogieñ.}

# Pierwszy dialog
{200} {} {Stop. W imiê Swiêtego Ognia odpowiedz, co tu robisz.}
{201} {} {Ta sprawa ciê nie dotyczy. Odsuñ siê.}
{202} {} {S³owa godne heretyka i bluŸniercy. Módl siê do Swiêtego Ognia, aby nie ukara³ ciê za wulgarny jêzyk.}
{203} {} {Twoje s³owa nie robi¹ na mnie wra¿enia. Wszystko, co mo¿esz zrobiæ, to wymachiwaæ tym swoim kijem i pustymi groŸbami, prawda?}
{204} {} {Widzê, ¿e jesteœ w powa¿nym nastroju. Proszê, ju¿ mnie tu nie ma.}
{205} {} {Szukam przydatnych rzeczy.}
{206} {} {Szukaj gdzie indziej, padlino¿erco. Twoja brudna robota przeszkadza nam w jasnych sprawach Atomu.}
{207} {} {Sk¹d tyle z³a?}
{208} {} {Wynoœ siê. W przeciwnym razie poznasz gniew Atomu z mojej w³óczni.}
{209} {} {Grozisz mi kawa³kiem zardzewia³ej rury? ZejdŸ mi z drogi.}
{210} {} {Ok, ok...}
{211} {} {Znowu ty? OdejdŸ w imiê Swiêtego Ognia.}
{212} {} {Ok, ok...}

{220} {} {Mam tu umówione spotkanie z pewnym facetem. Widzia³eœ go?}
{221} {} {Och, mo¿e. Co ³¹czy ciê z tym szpiegiem?}
{222} {} {Zle zrozumia³eœ. Sprzedajê tylko œmieci z ruin. A tak przy okazji, co on zrobi³?}
{223} {} {Unikaj k³opotów, padlino¿erco. IdŸ dalej ze swoim brudem.}
{224} {} {No dobrze...}
{225} {} {S³ono zap³acisz teraz za swoje zniewagi, klaunie w przebraniu.}
{226} {} {Nie wierzê w twoje k³amstwa. Padnij na kolana, atomowa istoto...}
{227} {} {Hej, zabieraj rêce...}
{228} {} {Szpieg? Nie, szukam po prostu przydatnych rzeczy w ruinach.}
{229} {} {Szpieg? Nie, mylisz siê.}
{230} {} {To prawda? Có¿, nie mamy nic oprócz plotek. Bêdziemy musieli pozwoliæ ci odejœæ.}
{231} {} {Ugh, dziêki.}
{232} {} {Nie wa¿ siê mówiæ o tym, co siê tutaj wydarzy³o. I bój siê Swiêtego Ognia.}
{233} {} {Tak, tak, oczywiœcie...}
{234} {} {Ups...}

{250} {} {Kolejny Inkwizytor? Co Ty tutaj robisz?}
{251} {} {Myœlê, ¿e szukamy tej samej osoby. I powinieneœ odejœæ, jeœli nie chcesz poznaæ gniewu Aarona.}
{252} {} {Aaron ciê wys³a³? Có¿, to wiele zmienia. Nie bêdê ingerowaæ w Twoj¹ misjê.}
{253} {} {Dziêkujê za zrozumienie.}
{254} {} {Szukam tylko staro¿ytnych relikwii. Do zobaczenia bracie.}

{260} {} {Kolejny Inkwizytor? Hmm, nie widzia³em ciê wczeœniej. Co Ty tutaj robisz?}
{261} {} {Mylisz siê, g³upcze. Nie jestem Inkwizytorem. Ten b³¹d bêdzie Ciê kosztowa³ ¿ycie!}
{262} {} {Szukam tylko staro¿ytnych relikwii. Do zobaczenia bracie.}
{263} {} {Inkwizytor? Gdzie, nawet nie wiem co...}
{264} {} {To szpieg! Chwyææie go, bracia!}
{265} {} {Ups...}