{100} {} {Widzisz Marcosa.}
{101} {} {Widzisz mê¿czyznê w kominiarce. Jego spojrzenie zdradza wolê walki.}
{102} {} {Smia³o, towarzyszu. Ca³e Phoenix czeka na Twój wyczyn.}
{103} {} {Teraz bêdzie inaczej. Zadnej inkwizycji, ¿adnej tyranii, ¿adnych wojen z s¹siadami. Dziêkujê towarzyszu.}

#Dialog
{200} {} {Jestem zaskoczony twoj¹ wizyt¹. Niewiele osób wie o tym miejscu, a pu³apki odstraszaj¹ nawet najbardziej doœwiadczonych. Ale ty tu jesteœ. I to jest cholernie interesuj¹ce. Co ciê do nas przywiod³o?}
{201} {} {Hmm? Jestem tu przez przypadek. Co robisz?}
{202} {} {Czyli przez przypadek znalaz³eœ to miejsce i omin¹³eœ nasze pu³apki, tak? Brzmi bardzo w¹tpliwie. Ale teraz nie ma sensu siê ukrywaæ - walczymy z Wyznawcami Ognia i ich przywódc¹ Aaronem. Co o tym myœlisz?}
{203} {} {Jestem tutaj, aby wyeliminowaæ ca³y twój gang.}
{204} {} {Och, bardzo dobrze. Z³apaæ szpiega!}
{205} {} {Tylko spróbuj...}
{206} {} {Hej, niezrozumia³eœ...}

{210} {} {Twoja sprawa jest godna szacunku. Nienawidzê tych wszystkich kultystów, tak jak ty.}
{211} {} {Jesteœcie zwyk³ymi przestêpcami. Musisz zostaæ zatrzymany.}
{212} {} {Hmm, chyba ciê polubiê. Poniewa¿ mamy wspólne zainteresowania, liczê na twoj¹ pomoc. Pomo¿esz nam w naszej walce?}
{213} {} {Mo¿esz na mnie liczyæ.}
{214} {} {To zale¿y od tego, co muszê zrobiæ?}
{215} {} {Hej, nie anga¿uj mnie w to!}
{216} {} {Przykro mi to s³yszeæ. Pierwsze wra¿enie zawsze jest mylne.}
{217} {} {Nikomu nie powiem. Obiecujê.}
{218} {} {Jesteœ bardziej podejrzany ni¿ na to wygl¹dasz. Bêdziemy musieli ciê zlikwidowaæ.}
{219} {} {Obawiam siê, ¿e ta odpowiedŸ mi nie odpowiada. Z³apaæ szpiega!}
{220} {} {Och...}
{221} {} {To na pró¿no...}
{222} {} {Pozwolisz mi wyjœæ i zapomnieæ o wszystkim, co siê tutaj wydarzy³o?}
{223} {} {Nie spodziewasz siê, ¿e opuœcisz to miejsce bez konsekwencji, prawda? Zobaczmy co siê stanie.}
{224} {} {Uch, myœlê, ¿e po prostu wyjdê. Zegnam.}
{225} {} {Chcê do³aczyæ do twojej bandy.}
{226} {} {Bardzo dobrze. Ale nie mo¿emy ryzykowaæ zaufania pierwszej spotkanej osobie. Opowiedz mi o sobie. Kim jesteœ i sk¹d wiesz o Partii Wyzwolenia?}
{227} {} {Szukam mojej rodziny. Zostali zniewoleni i sprowadzeni do tego miasta. Potrzebujê pomocy w ich znalezieniu.}
{228} {} {W³aœciwie to szukam w¹tpliwych i niebezpiecznych typów, których nale¿y wyeliminowaæ. Wygl¹da na to, ¿e ich znalaz³em.}
{1228} {} {W³aœciwie to szukam w¹tpliwych i niebezpiecznych typów, których nale¿y wyeliminowaæ. Wygl¹da na to, ¿e ich znalaz³am.}
{229} {} {(przytakuje) Rozumiem ciê. Ka¿dy tutaj kogoœ straci³. NajwyraŸniej nasze œcie¿ki zbieg³y siê nie przez przypadek. W koñcu niewielu wie, ¿e g³ównym odbiorc¹ niewolniczej pracy jest sekta czcicieli ognia. Walczymy z tymi draniami. Powinniœmy po³¹czyæ si³y.}
{230} {} {Hmm. Rozejrzyj siê i poznaj zespó³, a ja pomyœlê o planie.}
{231} {} {Dobrze.}
{232} {} {Jeœli pomo¿e to odzyskaæ moich ludzi, to wchodzê w to.}
{233} {} {Jak mogê pomóc w twoim ruchu?}
{1233} {} {Jak mogê pomóc w twoim ruchu?}
{234} {} {Przys³ali mnie Stra¿nicy. Oferuj¹ pomoc w walce z Aaronem.}
{235} {} {Rangersi. Liczy³em na ich pomoc, ale liczy³em na bardziej... imponuj¹ce posi³ki. Tak czy inaczej - cieszymy siê, ¿e mo¿emy otrzymaæ pomoc.}
{236} {} {Nasza sprawa jest s³uszna.}
{237} {} {Oczekuj¹ce instrukcje.}
{238} {} {Przeor Matthias wys³a³ mnie z katedry. Znam Twój biznes i chcê Ci pomóc.}
{239} {} {Matthias nie rzuca s³owami bez powodu. NajwyraŸniej mamy coraz mniej czasu, musimy dzia³aæ bardziej zdecydowanie.}

{250} {} {Pozdrowienia, bracie.}
{1250} {} {Pozdrowienia siostro.}
{251} {} {Do zobaczenia.}

{260} {} {Opowiedz mi o swojej organizacji.}
{261} {} {Jesteœmy Parti¹ Wyzwolenia Phoenix. Naszym celem jest uwolnienie miasta spod rz¹dów Aarona i os³abienie fa³szywego koœcio³a.}
{262} {} {Dlaczego nazwa³eœ koœció³ fa³szywym?}
{263} {} {Czciciele ognia b³êdnie interpretuj¹ star¹ religiê, próbuj¹c usprawiedliwiæ nieludzkie dzia³ania swojego przywódcy. Zapomnieli o przedwojennych przymierzach.}
{264} {} {Dlaczego obalenie Aarona jest dla ciebie takie wa¿ne?}
{265} {} {Bez przywódcy koœció³ upadnie w oczach miasta.}
{266} {} {Co zamierzasz zrobiæ gdy dotrzesz do celu?}
{267} {} {Zbudujemy nowe spo³eczeñstwo. Spo³eczeñstwo oparte na wspólnocie i równoœci, a nie na podzia³ach i podporz¹dkowaniu.}
{268} {} {Dziêki. Teraz wiem wystarczaj¹co du¿o.}

{270} {} {Opowiedz mi o swojej przesz³oœci.}
{271} {} {To nie ma znaczenia.}
{272} {} {Cokolwiek powiesz.}
{273} {} {Powinniœmy sobie ufaæ, prawda?}
{274} {} {Jasne, ale pamiêtaj, nie jesteœmy tu na przyjêciu zapoznawczym.}
{275} {} {Tak, uh, to koniec.}
{276} {} {Urodzi³em siê kilka lat temu, kiedy Aaron doszed³ do w³adzy w mieœcie. Osoba, któr¹ by³em wczeœniej, nie ¿yje.}
{277} {} {Musia³ byæ ku temu osobisty powód. Straci³eœ kogoœ bliskiego?}
{278} {} {Jesteœ bardziej wymagaj¹cy ni¿ na to wygl¹dasz. Po dojœciu do w³adzy Aaron zniszczy³ wszystkich niechcianych, którzy mogli go powstrzymaæ i do których móg³ dotrzeæ. Ognie kary oœwietli³y ca³e miasto.}
{279} {} {[Dalej.]}
{280} {} {Wielu straci³o wtedy swoich bliskich. Ale, jak powiedzia³em, przesz³oœæ nie ma znaczenia.}
{281} {} {Dlaczego by³o to tolerowane?}
{282} {} {Wtedy w Phoenix panowa³ g³ód. Pozbycie siê niepotrzebnych ust i uciskanie s³abych by³o zamierzeniem wielu. Sam Aaron próbowa³ tylko zdobyæ przyczó³ek u w³adzy, ale ca³y ten koœcielny nonsens nada³ znaczenie jego s³owom.}
{283} {} {Ugh, to musia³a byæ tragedia dla miasta. Porozmawiajmy o dzisiejszym dniu.}

#Quests
{300} {} {Jakieœ zadania?}
{301} {} {Mam dla ciebie zadanie. Brakuje jednego z naszych na zewn¹trz. Alicja opowie szczegó³y misji.}
{302} {} {Ok, porozmawiam z ni¹.}
{303} {} {Potrzebujê sprzêtu do naszej walki.}
{304} {} {Porozmawiaj o tym z Alicj¹, ona jest odpowiedzialna za magazyn, ja jestem zajêty wa¿niejszymi sprawami.}
{305} {} {Dobrze.}

{310} {} {Alicja opowiada³a o twoich sukcesach. Dobra robota. Z Twoj¹ pomoc¹ nasza sprawa rozwija siê szybciej.}
{311} {} {Có¿, jeœli tak mówisz.}
{312} {} {Och, jestem naprawdê najlepszym ze wszystkich twoich wojowników. Nie w¹tp w to.}
{313} {} {Szkoda, ¿e nie mogliœmy uratowaæ naszego agenta. Ale mo¿e tak bêdzie lepiej, poniewa¿ nikt nie wie, jakie informacje móg³by przekazaæ sekciarzom.}
{314} {} {Pozostawienie go w rêkach mnichów by³oby zbyt ryzykowne. To by³o jedyne wyjœcie.}
{315} {} {W³aœciwie nie mam z tym nic wspólnego, po prostu sta³o siê.}
{316} {} {Zo³nierz, którego uratowa³eœ, powiedzia³ mi, co siê sta³o. Wydostanie siê z takiej pu³apki jest imponuj¹ce.}
{317} {} {O tak. Ogieñ krzy¿owy, eksplozje... powinieneœ by³ zobaczyæ, jaka to by³a strzelanina. Nasze ¿ycia wisia³y na w³osku.}
{318} {} {To nie by³o takie trudne.}

{320} {} {Có¿, potrzebujemy twoich umiejêtnoœci. Uwa¿am, ¿e warto zaj¹æ siê wielkim biznesem i pomo¿esz nam w tym.}
{321} {} {Co tam?}
{322} {} {Dziêki wzmacniaczowi sygna³u dowiedzieliœmy siê du¿o o kultystach. Potwierdzi³a siê plotka, ¿e pod katedr¹ znajduj¹ siê tajne poziomy. Nie wiemy, co robi¹ tam mnisi. Ale plotka g³osi, ¿e tworz¹ potê¿n¹ broñ. To niedopuszczalne.}
{323} {} {Sugerujesz, wejœæ tam i zniszczyæ broñ? Ale jak?}
{324} {} {W katedrze jest cz³owiek, który sympatyzuje z naszymi ideami. Nazywa siê Matthias. Jednak ma swoje w³asne zadania u Aarona i nie mo¿esz go nazywaæ naszym agentem. Twoim zadaniem jest skontaktowanie siê z Matthiasem i uzyskanie od niego dalszych instrukcji.}
{325} {} {Zadanie jest jasne.}
{326} {} {Powodzenia. Miasto nie mo¿e ju¿ d³u¿ej tolerowaæ nieograniczonej mocy Aarona.}
{327} {} {Skontaktuj siê z Matthiasem, zinfiltruj laboratorium i zniszcz broñ. Jasne.}
{328} {} {W katedrze jest cz³owiek, który sympatyzuje z naszymi ideami. Nazywa siê Matthias. Jednak ma swoje w³asne zadania u Aarona, wiêc nie mo¿esz go nazywaæ naszym agentem. Twoim zadaniem jest skontaktowanie siê z Matthiasem, abyœmy mogli przygotowaæ siê do zdobycia katedry. Udzieli ci dalszych instrukcji.}
{329} {} {Do zobaczenia, Marcos.}

{330} {} {Aaron zosta³ pokonany.}
{331} {} {Wspania³a wiadomoœæ! Ale to nie wystarczy. Musimy zniszczyæ CALY kult. Dopóki ¿yj¹ wyznawcy Aarona, ta walka siê nie skoñczy. Ponadto nie wiadomo, jakie decyzje podejm¹ nowi przywódcy koœcio³a.}
{332} {} {Co mam zrobiæ?}
{333} {} {Ta wiadomoœæ nie zmienia twojej g³ównej misji - zinfiltruj tajn¹ kryjówkê pod katedr¹ i zniszcz j¹ lokaln¹ broni¹. Nasz agent, Mathias, pomo¿e ci w tym. Powodzenia, towarzyszu.}
{334} {} {Teraz bêdzie dobrze.}
