{100} {} {Widzisz buntownika.}
{101} {} {Widzisz cz³owieka w kominiarce. Jest zajêty sprawdzaniem swojego sprzêtu.}
{102} {} {Widzisz cz³owieka w kominiarce. Jest zdecydowanie gotowy do obrony swoich idei.}
{103} {} {Widzisz cz³owieka w kominiarce. Wygl¹da na gotowego do bitwy.}
{104} {} {Widzisz cz³owieka w kominiarce. Gdy ciê widzi, zaciska piêœci.}

{110} {} {Hmm...}
{111} {} {Nawet w centrali nie jest bezpiecznie.}
{112} {} {Wygramy.}
{113} {} {Cholerni fanatycy.}
{114} {} {Ci fanatycy dostan¹ to, na co zas³uguj¹.}
{115} {} {Nie podoba mi siê to, co robi¹.}
{116} {} {Kiedy dojdziemy do w³adzy, Phoenix bêdzie inne.}
{117} {} {Czas wyjœæ z cienia.}
{118} {} {Zrobiliœmy miejsce do ¿ycia z tego metra.}
{119} {} {To obecnie najlepsza lokalizacja dla Sztabu Generalnego.}
