{100} {} {Widzisz kardyna³a.}
{101} {} {Widzisz bandytê ze stylow¹ fryzur¹ i logo gangu na plecach.}
{102} {} {Gdybym mia³ zbrojê tak¹ jak twoja, ca³e miasto by³oby u moich stóp.}

{110} {} {Masz k³opoty?}
{111} {} {Kim w³aœciwie jesteœ?}
{112} {} {Nasze terytorium to nasze zasady.}
{113} {} {Wszyscy w tej okolicy siê nas s³uchaj¹.}
{114} {} {Uwa¿aj na swoje s³owa.}
{115} {} {Zamknij siê, jeœli nie chcesz w pysk.}
{116} {} {Czy ty w ogóle wiesz, kim my jesteœmy?}
{117} {} {Masz jakieœ zdanie? WsadŸ je sobie w dupê.}
{118} {} {Co tam naciskasz?}
{119} {} {Szukasz czegoœ w naszej okolicy?}

{120} {} {Cholera, nie powinniœmy w ciebie w¹tpiæ.}
{121} {} {Jesteœ wporz¹dku.}
{122} {} {Hej, jak siê masz?}
{123} {} {Chcesz piwo?}
{124} {} {Czy mo¿emy robiæ interesy? Jestem za.}
{125} {} {Jeœli ju¿, jestem z tob¹.}
{126} {} {Wszyscy tu s¹ razem. Rozgoœæ siê.}
{127} {} {}
{128} {} {}
{129} {} {}
