{100} {} {Widzisz Orrisa.}
{101} {} {Widzisz lidera Czerwonych Kardyna³ów.}
{102} {} {Potrzebujê tej zbroi. Oddaj j¹.}
{103} {} {...Uff, to sma¿y siê jak diabli...}
{104} {} {Nie robiê ju¿ interesów z kultystami.}

# Znajomosc
{200} {} {[Murphy] Ups, mamy tu szczura. Czy wiesz, gdzie jesteœ, kretynie? Hej Orris, pozwól mi spêdziæ z nim czas...}
{1200} {} {[Murphy] Ups, mamy tu szczura. Czy wiesz, gdzie jesteœ, g³upcze? Hej Orris, pozwól mi siê z ni¹ zabawiæ...}
{201} {} {[Dalej.]}
{202} {} {[Orris] Czekaj, Murphy. Nie b¹dŸ taki narwany, jeœli chodzi o naszych goœci. Ty. Czego potrzebujesz?}
{203} {} {Chcê tylko, ¿eby takie szumowiny jak ty zniknê³y z powierzchni ziemi.}
{204} {} {Jeœli szukasz k³opotów, jesteœ we w³aœciwym miejscu.}
{205} {} {Swietnie. Kto pierwszy?}
{206} {} {Mówi¹, ¿e jesteœ si³¹, z któr¹ musz¹ siê liczyæ nawet w³adze lokalne. Chcê byæ z tob¹.}
{207} {} {[Murphy] Chwytamy naszych ludzi za gard³a. Myœlisz, ¿e Ciê potrzebujemy? Wynoœ siê, kretynie.}
{1207} {} {[Murphy] Chwytamy naszych ludzi za gard³a. Myœlisz, ¿e Ciê potrzebujemy? Uciekaj, g³upcze, póki mo¿esz.}
{208} {} {[Dalej.]}
{209} {} {Murphy, kolego, uspokój siê. Potrzebujê kontaktu. Zapomnia³eœ? Wiêc ty. ChodŸ tu.}
{210} {} {Nie, nie. Nie chcê mieæ nic wspólnego z bandytami.}
{211} {} {Nie potrzebujemy idiotów. Ch³opaki, skoñczcie z nim.}
{1211} {} {Nie potrzebujemy idiotów. Ch³opaki, skoñczcie z ni¹.}
{212} {} {Nie. Nie rób mi krzywdy. B³agam Ciê...}
{213} {} {Zosta³eœ pobity i wyrzucony na ulicê, a twoje kieszenie zosta³y opró¿nione.}
{214} {} {Zosta³aœ zgwa³cona i wyrzucona na ulicê, a twoje kieszenie zosta³y opró¿nione.}
{215} {} {Zobaczmy, co mo¿esz mi zrobiæ. Kto pierwszy?}
{216} {} {Czego ode mnie chcesz?}
{217} {} {Szczerze, jestem tu przez przypadek. Pozwól mi odejœæ. Przepraszam.}
{218} {} {[Murphy] To znaczy kolejny szaleniec z ulicy. Opró¿nij kieszenie i dawaj co masz.}
{1218} {} {[Murphy] Mówiê ci - kobieta nie wszystko ma w porz¹dku z g³ow¹. Opró¿nij kieszenie, dawaj co masz i to wszystko.}
{219} {} {[Dalej.]}
{220} {} {Nie, Murphy. Potrzebujemy kontaktu. Zapomnia³eœ? Wiêc. Ty. ChodŸ tu.}
{221} {} {Czego ode mnie chcesz?}
{222} {} {Nie, nie. Nie negocjujê z bandytami.}
{223} {} {Znowu? Czego chcesz?}
{224} {} {Hej mistrzu, dobrze ciê widzieæ. To by³a wspania³a walka. Szkoda, ¿e ju¿ nie ma Ciê na ringu.}
{1224} {} {Hej mistrzyni, dobrze ciê widzieæ. To by³a wspania³a walka. Szkoda, ¿e ju¿ nie ma Ciê na ringu.}
{225} {} {Zgadza siê. Poza tym nie mogê ju¿ liczyæ na tantiemy.}
{226} {} {Potrzebujesz kapsli? Ja potrzebujê tylko twardzieli... Cholera, Murphy, zamknij siê! Wiem, komu mogê zaufaæ, a komu nie. Wiêc... S³uchaj, jest jedna praca i to tylko dla ciebie.}
{227} {} {S³ucham.}
{228} {} {Nie, nie. Nie chcê zadzieraæ z bandytami.}
{229} {} {Nic specjalnego. Mój przyjaciel mia³ spotkaæ siê z kurierem, ale znikn¹³. IdŸ na parking karawan i zejdŸ do lokalnego kana³u. To jest ich miejsce spotkañ. Dowiedz siê, co siê z nimi sta³o i wróæ do mnie. Jeœli zrobisz wszystko dobrze, otrzymasz nagrodê.}

# Pierwsze zadanie
{230} {} {Nic specjalnego. Muszê tylko znaleŸæ mojego starego przyjaciela. Widzisz, zagubi³ siê gdzieœ w du¿ym mieœcie.}
{231} {} {Nie bêdê siê anga¿owaæ w ¿adne niejasne interesy.}
{232} {} {Masz wielu ludzi. Dlaczego ja?}
{233} {} {Znaj¹ moich ludzi z widzenia. Nie powinni zbytnio œwieciæ w centrum miasta.}
{234} {} {Ok, zrobiê to.}
{235} {} {Widzisz, Murphy, z ka¿dym mo¿na negocjowaæ. Chocia¿ ciê rozumiem...}
{236} {} {[Dalej.]}
{237} {} {Teraz pos³uchaj uwa¿nie. IdŸ na parking karawan i zejdŸ do lokalnego kana³u. Tam mój cz³owiek mia³ siê spotkaæ z kurierem. Dowiedz siê, co siê z nimi sta³o i wróæ do mnie. Jeœli zrobisz wszystko dobrze, otrzymasz nagrodê.}
{238} {} {Ok, rozumiem.}
{239} {} {Jestem w drodze.}
{240} {} {Jeœli to zrobiê, zap³acisz mi?}
{241} {} {Obiecujê.}
{242} {} {Przypomnij mi, gdzie mia³o siê odbyæ to spotkanie?}
{243} {} {IdŸ na parking karawan i zejdŸ do lokalnego kana³u. Tam mój cz³owiek mia³ siê spotkaæ z kurierem. Dowiedz siê, co siê z nimi sta³o i wróæ do mnie.}
{244} {} {Rozumiem. Pójdê to sprawdziæ.}
{245} {} {Lepiej, ¿eby moi ludzie nie pl¹tali siê w œrodku miasta. Nie maj¹ tak dobrej reputacji jak Twoja.}
{246} {} {Mam doœæ! Zabijê ciê OSOBISCIE.}
{247} {} {Twoje nerwy s¹ trochê s³abe...}
{248} {} {No, stary, uspokój siê...}

{250} {} {Czy znalaz³eœ tych, o których mówi³em?}
{1250} {} {Czy znalaz³aœ tych, o których mówi³em?}
{251} {} {Nie. Jeszcze nie.}
{252} {} {Twój kumpel i kontakt zostali zaatakowani przez najemników Bruce'a.}
{253} {} {Co do... Hej Murphy, s³ysza³eœ to? Jest Ÿle. Za du¿o wiedzia³. Jeœli go przycisn¹, poznaj¹ wszystkie nasze plany. Musimy dzia³aæ szybko.}
{254} {} {Co siê sta³o?}
{255} {} {S³uchaj, nie jesteœ miejscowy, prawda? Powiem ci coœ. W tym mieœcie prze¿ywaj¹ tylko najsilniejsi. Nie mo¿e byæ inaczej. A my wci¹¿ ¿yjemy tylko dlatego, ¿e nie pozwalamy, by ¿adne œmieci ostrzy³y przeciwko nam no¿e. Jeœli chcesz zdobyæ przyczó³ek w Phoenix, trzymaj siê blisko w³aœciwych ludzi.}
{256} {} {To jest... jasne.}
{257} {} {I chcê zaoferowaæ ci kontrakt. Nie obchodzi mnie jak, ale muszê wyci¹gn¹æ mojego cz³owieka z wiêzienia lub zamkn¹æ go na dobre. Rozumiesz? Pojawienie siê w centrum jest dla nas zbyt ryzykowne, ale nie dla Ciebie. Pomyœl, jak to zrobiæ, a wtedy zap³acê 200 kapsli.}
{258} {} {Zobaczê, co mogê zrobiæ.}
{259} {} {To zbyt trudna misja dla mnie. Nie uda mi siê.}

{260} {} {Jakieœ wiadomoœci?}
{261} {} {Na razie brak. Twój cz³owiek nadal przebywa w wiêzieniu.}
{262} {} {Cholera, jeœli pêknie podczas przes³uchania, ty te¿ bêdziesz mieæ problemy. Zrozum to.}
{263} {} {Wskazówka jest jasna...}
{264} {} {Nie strasz mnie.}
{265} {} {Mam tego doœæ. Nie tylko nie bêdê dla ciebie pracowaæ, ale wydam te¿ ca³y twój cholerny gang najemnikom. Zegnaj, sukinsynu.}
{266} {} {Twój kumpel nie ¿yje. Nie by³o to ³atwe, ale uda³o mi siê.}
{267} {} {Twój kumpel jest wolny. Nie by³o to ³atwe, ale uda³o mi siê.}
{268} {} {No i zajebiœcie. Jestem bardzo szczêœliwy, ¿e mam ciê w pobli¿u. Oto kapsle za pracê i œrodek pobudzaj¹cy. Baw siê dobrze tym gównem.}
{1268} {} {No i zajebiœcie. Jestem bardzo szczêœliwy, ¿e mam ciê przy sobie. Oto kapsle za pracê i œrodek pobudzaj¹cy. Baw siê dobrze tym gównem.}
{269} {} {Ok, wrócê póŸniej.}

{270} {} {Wygl¹da na to, ¿e twoi ludzie maj¹ problemy. Co zamierzasz teraz zrobiæ?}
{271} {} {Tylko kultyœci Swi¹tyni Ognia mogli to zrobiæ. Wygl¹da na to, ¿e postanowili siê nas pozbyæ po wykorzystaniu nas do w³asnych celów. Ale po eksplozji katedry nie maj¹ dla nas czasu.}
{272} {} {Wiêc jesteœcie teraz wolni?}
{273} {} {Czas przej¹æ wolne obszary, zanim zrobi to ktoœ inny. Nawiasem mówi¹c, ju¿ ciê nie potrzebujê. Ale nie zapominam o tych, którzy byli pomocni. Porozmawiaj z handlarzem ze slumsów. Mamy z nim szczególne stosunki.}
{1273} {} {Czas zaj¹æ wolne obszary, zanim zrobi to ktoœ inny. Nawiasem mówi¹c, ju¿ ciê nie potrzebujê. Ale nie zapominam o tych, którzy byli pomocni. Porozmawiaj z handlarzem ze slumsów. Mamy z nim szczególne stosunki.}
{274} {} {Swietnie, bêdê o tym pamietaæ. Czeœæ, Orris.}
{275} {} {Tylko kultyœci Swi¹tyni Ognia mogli to zrobiæ. Wygl¹da na to, ¿e postanowili siê nas pozbyæ po wykorzystaniu nas do w³asnych celów. Ale nie rozumiem, w jaki sposób dowiedzieli siê o naszej tajnej umowie.}
{276} {} {Czy ktoœ móg³ im to powiedzieæ?}
{277} {} {Ktoœ z nas? A¿ trudno w to uwierzyæ. Jesteœmy tylko bandytami sekciarzy...}
{278} {} {[Dalej.]}
{279} {} {S³uchaj, potrzebujê cz³owieka w katedrze. Jeœli dowiesz siê, kto nas wyda³, zap³acê dobre kapsle. W porz¹dku?}
{280} {} {Jasne. Znajdê tego szczura w Twoim gangu.}
{281} {} {Zinfiltrowaæ katedrê? Jesteœ szalony. Nie mogê tego zrobiæ.}
{282} {} {Czy dowiedzia³eœ siê, kto nas sprzeda³?}
{1282} {} {Czy dowiedzia³aœ siê, kto nas sprzeda³?}
{283} {} {To by³ Murphy. Jest agentem Aarona.}
{284} {} {Murphy? Nie mog³em nawet o tym pomyœleæ, jest najlepszy z najlepszych... Ale jeœli siê nad tym zastanowic... On wiedzia³ najwiêcej o moich planach.}
{285} {} {To zdecydowanie Murphy. Mog³em s³uchaæ jego rozmowy w radiu z sygnalist¹ Katedry. Aaron chcia³ kontrolowaæ twój gang, powierzaj¹c dowództwo swojemu cz³owiekowi.}
{286} {} {Plany Aarona nigdy siê nie spe³ni¹. Pozbêdê siê Murphy'ego. Powinnieneœ zostaæ nagrodzony za swoje wysi³ki. Nie chcê straciæ tak u¿ytecznego agenta. Oto kapsle. Porozmawiaj te¿ z handlarzem ze slumsów, mam z nim specjalne porozumienie.}
{287} {} {Do widzenia, Orris.}
{288} {} {Murphy ju¿ nie pasuje do ciebie. Czeœæ, Orris.}
{289} {} {Myœlê, ¿e twoi ludzie byli œledzeni przez kultystów. Ale po eksplozji katedry nie dowiemy siê prawdy.}
{290} {} {Jaka jest historia z czcicielami ognia?}
{291} {} {Ci kultyœci uwa¿aj¹ nas za bandytów i nie uznaj¹ naszego autorytetu nad slumsami. Ale w razie potrzeby s¹ gotowi do negocjacji.}
{292} {} {Wspomina³eœ coœ o pracy.}
{293} {} {Zap³acili za sabota¿ przemys³u nuklearnego. Podkopaliœmy system ch³odzenia stacji, ale potem sekciarze ju¿ nas nie potrzebowali. Zwyczajnie nas wyrzucili.}
{294} {} {Rozumiem.}
{295} {} {Ale jak mam to zrobiæ?}
{296} {} {Sam nie wiem. Ale mnisi z pewnoœci¹ maj¹ wszystko zapisane w jakiejœ dokumentacji.}
{297} {} {Ci¹gle siê zastanawiam, jak znaleŸæ szczura w katedrze?}

# Dialog poza zadaniem
{300} {} {Powiedz, czego potrzebujesz.}
{301} {} {Jak siê masz, w³óczêgo?}
{302} {} {Chcia³em ciê tylko zobaczyæ. Wychodzê.}

{310} {} {Czy twoi ludzie wziêli pocztê od kuriera?}
{311} {} {Nie mam pojêcia, o czym mówisz. Zapytaj moich ludzi. Jeœli ktoœ siê przyzna, zobaczymy.}
{312} {} {Tak zrobiê. Bywaj.}
{313} {} {Znajdê winowajcê, nie bój siê.}

{320} {} {Mówi¹, ¿e zabi³eœ moich ludzi w slumsach. A teraz wa¿ysz siê przychodziæ do mnie. Dam Ci tylko jedn¹ szansê, aby przekonaæ mnie, ¿ebym utrzyma³ Ciê przy ¿yciu.}
{1320} {} {Mówi¹, ¿e zabi³aœ moich ludzi w slumsach. A teraz wa¿ysz siê przychodziæ do mnie. Dam Ci tylko jedn¹ szansê, aby przekonaæ mnie, ¿ebym utrzyma³ Ciê przy ¿yciu.}
{321} {} {To ich wina.}
{322} {} {Moja okolica - moje zasady. Ludzie musz¹ zobaczyæ, ¿e trzeba siê liczyæ z moj¹ si³¹. Ch³opaki, uporajcie siê z tym œmieciem...}
{1322} {} {Moja okolica - moje zasady. Ludzie musz¹ zobaczyæ, ¿e trzeba siê liczyæ z moj¹ si³¹. Ch³opaki, zajmijcie siê ni¹...}
{323} {} {Och, nie w twarz...}
{324} {} {IdŸ do diab³a z ca³ym tym swoim gangiem.}
{325} {} {To ich wina. Potraktuj to jako moj¹ osobist¹ sprawê z nimi.}
{326} {} {Tak. Twoja. Osobista. I nie wa¿ siê nikomu mówiæ inaczej. Ludzie musz¹ wiedzieæ, ¿e trzeba siê liczyæ z moj¹ moc¹.}
{327} {} {Nie mam z tym nic wspólnego.}
{328} {} {Pomyli³eœ mnie z kimœ. To nie ja.}
{1328} {} {Pomyli³eœ mnie z kimœ. To nie by³am ja.}
{329} {} {K³amiesz. Ch³opaki, uporajcie siê z tym œmieciem...}
{330} {} {O nie, nie w twarz...}
{331} {} {IdŸ do diab³a.}
{332} {} {Musia³es mnie z kimœ pomyliæ. Spójrz na mnie, czy ja wygl¹dam jakbym by³ w stanie to zrobiæ?}
{333} {} {To ciê¿ki biznes. Na razie pozwolê ci odejœæ. Ale jeœli k³amiesz, czeka ciê okrutna kara. Ludzie musz¹ zobaczyæ, ¿e trzeba siê liczyæ z moj¹ moc¹.}
{334} {} {Oczywiœcie...}
{335} {} {Po tym, co siê sta³o, nie bojê siê ciebie. Ty i Twój gang zas³u¿yliœcie tylko na œmieræ.}

{340} {} {Czy to Ty zaatakowa³eœ mnichów?}
{341} {} {Nie, to nie ja. Dajê s³owo.}
{342} {} {Jeœli nie ty, to kto?}
{343} {} {Powiem ci, ¿e s³ysza³em o innym gangu. Ci goœcie chc¹ obaliæ Aarona i skierowaæ ludzi przeciwko Koœcio³owi Ognia. Ale s¹ zbyt przebiegli, by pokazywaæ twarze.}
{344} {} {Nie dogadujesz siê z nimi, prawda?}
{345} {} {Nie podoba mi siê, jak siê ukrywaj¹. Kochamy bezpoœrednioœæ. Jeœli chcesz okraœæ przechodnia, spójrz mu w oczy.}
{346} {} {Rozumiem. Przeka¿ê twoje s³owa Aaronowi.}

{350} {} {Mówi¹, ¿e zaatakowa³eœ Gonzaleza. Dlaczego, do diab³a, to zrobi³eœ? Czy konieczne by³o doprowadzenie go do takiego stanu?}
{1350} {} {Mówi¹, ¿e zaatakowalas Gonzaleza. Wiem, ¿e mia³ problem z kobietami, ale czemu musia³o do tego dojœæ?}
{351} {} {Nie ma dla takiego elementu miejsca w zdrowym spo³eczeñstwie.}
{352} {} {Dosta³ to, na co zas³u¿y³. Ty te¿ to dostaniesz.}
{353} {} {Nikt nie odwa¿y siê tak ze mn¹ rozmawiaæ. NIKT.}
{354} {} {To pierwszy raz, kiedy siê tak sta³o. Czy mo¿esz tylko krzyczeæ?}
{355} {} {Przepraszam, zdenerwowa³em siê z powodu Gonzaleza.}
{356} {} {Czu³em siê jak bandyta, jakbym nie docenia³ czyjegoœ ¿ycia.}
{357} {} {Gonzalez by³ dla nas szczególnie pomocny. Dostarcza³ chemie i leki. Sk¹d teraz je weŸmiemy, co?}
{358} {} {Wiesz, to DOBRZE, ¿e ludzie tacy jak ty nie maj¹ teraz sprzedawcy.}
{359} {} {Zas³u¿y³ na œmieræ.}
{360} {} {Gdybyœ nie by³a kobiet¹, powiesi³bym ciê publicznie na latarni w slumsach. Zniknij, zanim zmieniê zdanie.}
{361} {} {Tak...}
{362} {} {To moja osobista sprawa. Moja i jego.}
{363} {} {Ju¿ nie. Z twojego powodu straciliœmy œwietnego dostawcê. Nie ujdzie ci to na sucho.}
{364} {} {Jesteœ typowym bandyt¹...}
{365} {} {To moja osobista sprawa z nim. Sk¹d mia³em wiedzieæ, ¿e Gonzalez z tob¹ pracowa³?}
{366} {} {W takim razie jesteœ mi winien przys³ugê. Nie myœl, ¿e mo¿esz tak ³atwo siê z tego wymigaæ.}
{367} {} {Oczywiœcie. Mo¿esz na mnie liczyæ.}
{368} {} {Proszê, wybacz mi, to siê sta³o przez przypadek.}
{369} {} {To nie wystarczy. Krew za krew, to prawo ulicy. Zdejmij ubranie, jeœli chcesz, ¿eby to siê szybko skoñczy³o.}
{370} {} {Nie, nie...}
{371} {} {Dosta³ to, na co zas³u¿y³. Ale jest za póŸno, ¿eby to naprawiæ. Czy mogê zadoœæuczyniæ?}
{372} {} {Jesteœ mi winien przys³ugê. Przynieœ dziesiêæ stymulantów, a MOZE ci wybaczê.}
{373} {} {Ok.}
{374} {} {Nie b¹dŸ bezczelny. Nie mam z tym nic wspólnego.}
{375} {} {Oto 10 stymulantów. Czy teraz jest ok?}
{376} {} {Tak. Powiedzmy, ale lepiej na siebie uwa¿aj.}
{377} {} {Swietnie.}
{378} {} {Zrobiê wszystko, tylko mnie nie zabijaj!}
{379} {} {}

{380} {} {Prowadzê œledztwo w sprawie sabota¿u w elektrowni atomowej. Zrobi³eœ to?}
{381} {} {O czym ty mówisz? Testujesz moj¹ cierpliwoœæ?}
{382} {} {Nie, nie mam na to czasu. Jestem po prostu ciekawy.}
{383} {} {K³amiesz. Kana³ prowadzi od Ciebie bezpoœrednio do elektrowni j¹drowej.}
{384} {} {Powiedz tym atomowym lobbystom, ¿e mój gang nie chce mieæ z nimi nic wspólnego. A teraz wynoœ siê, œmieciu.}
{385} {} {Ok...}
{386} {} {Powiedz prawdê, Orris. Jesteœmy partnerami w interesach. Czy jesteœ w to zamieszany?}
{387} {} {Po naszej wspólnej pracy mo¿esz mi zaufaæ. Czy jesteœ w to zamieszany?}
{388} {} {Po prostu robimy co trzeba by przetrwaæ. Kapsle nigdy nie s¹ zbyteczne, szczególnie tak ³atwe.}
{389} {} {Co masz na myœli? Czy otrzyma³eœ je za pomoc?}
{390} {} {Pieprzyæ kultystów. Mieli powi¹zania z kimœ na stacji. Z kimœ, kto by³ zainteresowany sabota¿em. Moi ludzie tylko poszli do otwartej piwnicy i wysadzili rury. Czy mog³o byæ ³atwiej? Ale uwaga - ja tego ci nie powiedzia³em.}
{391} {} {Ok, Orris. Nie chcê problemów.}
{392} {} {Ju¿ wszystko powiedzia³eœ. A teraz po¿egnaj siê z ¿yciem, idioto.}
{393} {} {Jesteœ dziœ zbyt rozmowny. Ciesz siê, ¿e nie jestem twoim wrogiem.}