{100} {} {Widzisz kardyna³a.}
{101} {} {Widzisz bandytê ze stylow¹ fryzur¹ i logo gangu na plecach.}

{200} {} {Hej, co tu robisz? Nie wiesz czyj to obszar?}
{201} {} {Nie wiem. Czyj?}
{202} {} {Nigdy nie s³ysza³eœ o czerwonych kardyna³ach? Zastanawiam siê, sk¹d przyjecha³eœ?}
{1202} {} {S³ysza³aœ kiedyœ o czerwonych kardyna³ach? Zastanawiam siê, sk¹d przyjecha³aœ?}
{203} {} {Z daleka.}
{204} {} {Tak. Jasne. Odwróæ siê, jeœli ¿ycie jest ci drogie. Na razie tylko ostrzegam.}
{205} {} {Ok.}
{206} {} {Przejdê mimo to.}
{207} {} {Jak sobie ¿yczysz. Ale Orrisowi i pozosta³ym siê to nie spodoba. A mo¿e szukasz Orrisa? Jest w domu, ale lepiej miej powód, ¿eby go poznaæ.}
{208} {} {Pomyœlê o tym. Szczêœcia.}
{209} {} {To nonsens. Ziemia jest wspólna i nie mo¿e nale¿eæ do nikogo.}
{210} {} {Nigdy nie s³ysza³em wiêkszej bzdury. WyjdŸ.}
{211} {} {Lepiej siê st¹d wynoœ.}
{212} {} {Ju¿ wychodzê.}
{213} {} {Czeœæ. Jak siê masz?}

{214} {} {Czy zdajesz sobie sprawê, ¿e ktoœ ujawni³ wasze interesy czcicielom ognia?}
{215} {} {Co? Czyli jest wœród nas agent kultu? Tak, to mo¿liwe. Nie mogê sobie nawet wyobraziæ, kto to mo¿e byæ.}
{216} {} {Jeœli oka¿e siê, ¿e to zrobi³eœ, masz du¿e k³opoty.}
{217} {} {Nie martw siê, dowiem siê, kto to zrobi³.}

# Poszukiwanie listów
{220} {} {Niektórzy z twoich ludzi okradli kuriera i zabrali od niego listy.}
{221} {} {I?}
{222} {} {Czy wiesz kto to by³?}
{223} {} {Tak.}
{224} {} {Hm, kto?}
{225} {} {To by³em ja.}
{226} {} {Wiêc jesteœ na celowniku. Oddaj te listy.}
{227} {} {Haha, rozkazujesz mi? MI? ZnajdŸ przynajmniej jeden powód, by ciê s³uchaæ. Taki, który brzmi równie dobrze, jak kapsle do butelek.}
{228} {} {Wiêc chodzi o kapsle?}
{229} {} {Czego oczekujesz za te listy?}
{230} {} {Coœ, co brzmi równie dobrze jak kapsle do butelek, kochanie. Wiesz, o czym mówiê?}
{231} {} {Wiêc chodzi o kapsle?}
{232} {} {Myœlisz, ¿e robiê to z dobrego serca? Ka¿dy potrzebuje kapsli. Ale ludzie tacy jak ja nie mog¹ liczyæ na legaln¹ pracê w tym mieœcie. Dlatego zarabiam tyle ile siê da i jak siê da.}
{233} {} {Ok. Zap³acê 30 kapsli.}
{234} {} {}
{235} {} {O listach Sonora Express. Nadal je masz?}
{236} {} {Nigdzie nie pójd¹, dopóki nie dostanê tego, czego chcê.}
{237} {} {Potrzebujesz kapsli, prawda?}
{238} {} {Pamiêtam. Ale potrzebujê wiêcej czasu, aby zebraæ wymagan¹ kwotê.}
{239} {} {Co jest? Wygl¹da na to, ¿e potrzebujesz kapsli nawet bardziej ni¿ ja.}
{240} {} {Zbiorê wymagan¹ kwotê. Daj mi trochê czasu.}
{241} {} {Wiesz, to nie ma sensu. Po prostu ciê zabije i wezmê te listy...}
{242} {} {NieŸle. Kapsli bêdzie wiêcej - przynieœ je.}
{243} {} {Tak, do widzenia.}
{244} {} {Pieprzyæ negocjacje. Po prostu ciê zabijê i wezmê te listy...}
{245} {} {Wiesz, nie chcê wiêcej anga¿owaæ siê w ten problem. Czeœæ.}
{246} {} {Atomowy robaku. Twoje dzia³ania zas³uguj¹ na ogieñ karny.}
{247} {} {Argh. By³o tak od razu. Nie chcê problemów z twoj¹ sekt¹. Przejeliœcie ju¿ ca³e miasto. WeŸ te cholerne listy.}
{248} {} {Niech Swiêty Ogieñ zmi³uje siê nad tob¹, ofiaro promieniowania i spustoszenia.}
{249} {} {Jestem od Don Diego. Nie z³oœæ mojego szefa.}
{250} {} {(ze skruch¹) Ach, przepraszam, senor. Mog³eœ tak od razu. Kto by pomyœla³, ¿e tak szanowana osoba odwiedzi nasz¹ dziurê. (przekazuje listy) Pozdrów szefa. Adio-os.}
{1250} {} {(ze skruch¹) Ach, przepraszam, senora. Mog³aœ tak od razu. Kto by pomyœla³, ¿e tak szanowana osoba odwiedzi nasz¹ dziurê. (przekazuje listy) Pozdrów szefa. Adio-os.}
{251} {} {Znaj swoje miejsce, kardynale. W mieœcie s¹ si³y wiêksze ni¿ twój gang.}
{252} {} {Orris ostrzega³ mnie przed twoim uporem. Chcesz wylecieæ z gangu? Da siê to za³atwiæ.}
{253} {} {Jesteœ zbyt gwa³towny nawet jak na nasz gang. WeŸ te listy i zostaw mnie w spokoju. I tak mnie nudzi³y.}
{1253} {} {Jesteœ zbyt gwa³towna nawet jak na nasz gang. WeŸ te listy i zostaw mnie w spokoju. I tak mnie nudzi³y.}
{254} {} {Tak.}
{255} {} {Ja te¿ zarabiam „najlepiej, jak potrafiê”. Wiesz jak? Angelo powie ci na ringu.}
{256} {} {Ahh.. Jesteœ jednym z tych sportowców, na których mo¿na dobrze zarobiæ. Szanujê Ciê. Mo¿esz mi pokazaæ kilka sztuczek?}
{257} {} {Pomyœlê o tym. Ale teraz muszê zanieœæ listy do biura.}