{100} {} {Widzisz Murphego.}
{101} {} {Widzisz jednego z czerwonych kardyna³ów.}
{102} {} {Przyda³a by mi siê twoja zbroja.}
{103} {} {Wêszysz? ChodŸ tutaj, jest sprawa.}
{104} {} {Trzymaj siê ode mnie z daleka, szczurze.}
{1104} {} {Trzymaj siê ode mnie z daleka, szczurze.}
{105} {} {Mi³o ciê widzieæ.}
{106} {} {Murphy czeka na ciebie na arenie.}

{200} {} {Hej, szczurze. B¹dŸ ostro¿ny. Nie chcê siê przez ciebie ubrudziæ.}
{201} {} {No dalej, Murphy. Zrobimy razem wiele rzeczy.}
{202} {} {Nie licz na to. W przeciwieñstwie do Orrisa nie jestem taki ³atwowierny.}
{203} {} {Tak. Czeœæ, Murphy.}
{204} {} {Wzajemnie. Powinieneœ siê umyæ, œlimaku.}
{205} {} {Orris teraz ciê potrzebuje. Ale daj mi tylko powód - a ciê za³atwiê. Zrozum to.}
{206} {} {Tak. Czeœæ, Murphy.}
{207} {} {Nie musisz mnie straszyæ.}
{208} {} {Tak. Znaj swoje miejsce.}
{209} {} {Do widzenia, Murphy.}

{210} {} {Czego chcesz?}
{1210} {} {Czego chcesz, suko?}
{211} {} {Wow, spokojnie, ju¿ wychodzê.}
{212} {} {Czego chcesz?}
{213} {} {Niczego. Bywaj.}
{214} {} {Czeœæ. Co tam? Nikt ciê nie zaczepia z miejscowych?}
{215} {} {Wszystko w porz¹dku. Bywaj.}
{216} {} {Mi³o ciê widzieæ.}
{217} {} {Do widzenia.}

{220} {} {Mówi¹, ¿e ktoœ zdradzi³. Jak myœlisz, kto to mo¿e byæ?}
{221} {} {Masz urojenia. Nie tolerujemy czcicieli ognia w duchu. Nikt z nas nie mo¿e nawet zbli¿yæ siê do katedry. Jesteœmy tam uwa¿ani za przestêpców.}
{222} {} {Brzmi ca³kiem przekonuj¹co.}
{223} {} {Udowodniê, ¿e jest wœród was zdrajca.}
{224} {} {Wiem, kim jesteœ, Murphy. W katedrze jest info na twój temat. Chcesz o tym porozmawiaæ?}
{225} {} {O czym ty do cholery mówisz? Jakie do cholery info? Nie mam nic wspólnego z sekciarzami. Jasne?}
{226} {} {Oczywiœcie, oczywiœcie. Ale jeœli chcesz o tym porozmawiaæ, przyjdŸ wieczorem na arenê. Porozmawiamy sobie.}
{227} {} {Pomyœlê o tym, w ca³ym mieœcie jest wiêcej Murphych. Niewa¿ne.}

{230} {} {Powiedzia³em ju¿ wszystko. Przemyœl dok³adnie swoje nastêpne dzia³anie.}
{231} {} {Ok.}
{232} {} {Wiêc co to do cholery znaczy? Zosta³eœ wys³any z katedry?}
{233} {} {Wiem, ¿e jesteœ agentem Obserwatorów. Mia³eœ ju¿ doœæ Orrisa?}
{234} {} {Aaron potrzebuje agentów w ca³ym mieœcie. To jest moja misja, myœlisz ze ³atwo by³o siê tak ustawiæ? Ju¿ ciê spotykaj¹c, podejmujê du¿e ryzyko. A tak przy okazji, kim jesteœ?}
{235} {} {Mo¿na powiedzieæ, ¿e gram w swoj¹ grê.}
{236} {} {Taka odpowiedŸ niewiele mi mówi. Ale przynajmniej oznacza to, ¿e mo¿emy siê dogadaæ. Chodzi o to, ¿e chcê zaj¹æ miejsce Orrisa i reedukowaæ gang dla dobra koœcio³a. Jeœli ci faceci potrafi¹ tylko biæ innych, to niech bij¹ tych co trzeba.}
{237} {} {Masz ambitne plany.}
{238} {} {Wiêc pomo¿esz mi? Koœció³ Ognia bêdzie wdziêczny za twoje czyny. Nie mogê samodzielnie zdetronizowaæ Orrisa bez konsekwencji.}
{239} {} {Jesteœ zdrajc¹. A ja nie wierzê zdrajcom.}
{240} {} {Hmm, lepiej nie wchodŸ mi w drogê.}
{241} {} {No có¿.}
{242} {} {Orris i jego gang musz¹ zostaæ powstrzymani. Ale jak to zrobiæ?}
{243} {} {Sledzê Orrisa przez d³ugi czas. Trudno bêdzie go niezauwa¿enie zastrzeliæ, poniewa¿ jest stale w centrum uwagi. Pomyœl, jak mo¿esz to zrobiæ po cichu, bez robienia zamieszania. Mo¿e rusznikarz lub handlarz ma coœ odpowiedniego?}
{244} {} {Pomyœlê o tym.}
{245} {} {Wiem, ¿e Orris nie ¿yje. Dziêki tobie miasto uspokoi siê, a dzie³o Swiêtego Ognia ponownie zajmie ruiny.}
{246} {} {To musia³o byæ zrobione.}
{247} {} {Opowiem katedrze o twoim wyczynie, aby unikn¹æ nieporozumieñ w przysz³oœci. Do widzenia mój przyjacielu.}
{1247} {} {Opowiem o twoim wyczynie w katedrze, aby unikn¹æ nieporozumieñ w przysz³oœci. Zegnaj siostro.}
{248} {} {Do widzenia Murphy.}
{249} {} {Mimo, ¿e katedra jest zniszczona, dziêki tobie jest nadzieja. Byæ mo¿e nie wszystko jeszcze stracone.}

{250} {} {Co robisz, Murphy?}
{251} {} {Wszystko, co powinna robiæ prawa rêka Orrisa. Ufa mi w najtrudniejszych problemach.}
{252} {} {Jesteœ zastêpc¹ Orrisa? Rozumiem.}
{253} {} {Jak do³¹czy³eœ do gangu?}
{254} {} {Na pewno nie poprzez nieróbstwo. Eliminowa³em niepotrzebnych ludzi dla Orris, dopóki nie zobaczy³ mojego prawdziwego potencja³u.}
{255} {} {Jesteœ niebezpiecznym facetem. Muszê z tob¹ uwa¿aæ.}
{256} {} {Dlaczego twój gang jest nielegalny? Podobno czciciele ognia was akceptuj¹.}
{257} {} {Przeklêci kultyœci, nienawidzê ich. Mówi¹ nam, co jest dobre, a co z³e. Prawo na ziemi? Na ulicach obowi¹zuje tylko jedno prawo - kto jest silniejszy ten ma racjê. Udowodniliœmy to czynami. Tylko my mamy prawo rz¹dziæ tym terytorium.}
{258} {} {Brzmi rozs¹dnie.}
{259} {} {Jestem po twojej stronie, Murphy. Ale jak dotrê do Orrisa?}

{260} {} {Hej, czy wiesz, kto sabotowa³ elektrowniê?}
{261} {} {Mo¿e. Po co pytasz?}
{262} {} {Prowadzê œledztwo dla Theodora.}
{263} {} {Nie lubiê tych ghuli. Ale nie chcê te¿ wydawaæ ich wrogów.}
{264} {} {W takim razie zapomnij. Spróbujê zapytaæ kogoœ innego.}
{265} {} {No, powiedz mi, mo¿esz mi zaufaæ.}
{266} {} {Nie wiem.}
{267} {} {Przykro mi, ¿e mi nie ufasz.}
{268} {} {Nie masz siê czego baæ. Nawet jeœli jesteœ w to zamieszany, nie sprzedam ciê.}
{269} {} {Baæ? Ja? Ha! Szczerze mówi¹c, sam jestem w tym gównie. Czêœæ Katedry prosi³a o sabota¿, aby przekonaæ ghule do wspó³pracy, poniewa¿ sami nie byliby w stanie niczego naprawiæ. Okaza³o siê to ³atwe, poniewa¿ jeden z ghuli chcia³ siê nawet dogadaæ z czcicieli ognia.}
{270} {} {Wow, co za historia! Teraz bêdê wiedzia³, kto jest jest za to odpowiedzialny. Czeœæ, Murphy.}
{271} {} {Dlaczego mia³byœ coœ ukrywaæ? Jesteœ fajnym goœciem, daj spokój, powiedz mi.}
{272} {} {Boisz siê czegoœ? A ja myœla³em, ¿e kardyna³owie to twardzi faceci...}