{100} {} {Widzisz wiêŸnia.}
{101} {} {Widzisz jednego z czerwonych kardyna³ów.}
{102} {} {* Uff *}
{103} {} {...Dziwne dzieci...}

{110} {} {Hej, pomó¿ mi siê st¹d wydostaæ. Nie pozostanê d³u¿ny.}
{111} {} {Znasz Orrisa? Powiedz mu, ¿e jestem w wiêzieniu.}
{112} {} {Najemnicy nie pozwol¹ mi odejœæ. Powiedz Orrisowi, ¿e przetrzymuj¹ mnie tu.}

{115} {} {Orris ciê przys³a³? Nie spodoba mu siê ta historia.}
{116} {} {Do zobaczenia w bazie. Orrisowi nie spodoba siê to, co powiem.}
{117} {} {Powa¿nie, ktoœ nas wystawi³!}
