{100} {} {Widzisz kontakt.}
{101} {} {Widzisz mê¿czyznê z no¿em w boku. Nie po¿yje d³ugo.}
{102} {} {Widzisz rannego mê¿czyznê. Ledwo siê trzyma, uciskaj¹c zraniony bok.}
{103} {} {...najemnicy Bruce'a... zaatakowali...}
{104} {} {By³em ju¿ zdesperowany, myœla³em, ¿e umrê. Dziêki doktorze.}

{110} {} {...jestem ranny...}
{111} {} {...Ahh...to boli...}
{112} {} {...O-ocal...}
{113} {} {...Powiem ci wszystko, tylko pomó¿...}
{114} {} {...O-oni zaatakowali... czekali na nas...}
{115} {} {Tak, pomó¿ mi!}
{116} {} {Ok... ok... powiem ci...}
{117} {} {...Byli najemnikami Bruce'a...}
{118} {} {...Z³apali...kardyna³a...i...}
{119} {} {...Ap-rh...}
{120} {} {Przepraszam kolego, ale pomoc nie nadejdzie na czas.}

{200} {} {Dziêki doktorze. Jestem Ci na zawsze wdziêczny.}
{201} {} {Kto ciê zaatakowa³?}
{202} {} {Byli najemnikami z gildii Bruce'a. Myœlê, ¿e czekali na nas. Z³apali osobê, z któr¹ mia³em siê spotkaæ, i po prostu dŸgnêli mnie no¿em. NajwyraŸniej nie wykoñczyli, bo uznali, ¿e ju¿ i tak nie ¿yjê.}
{203} {} {Jak w ogóle znalaz³eœ siê do w tej historii?}
{204} {} {S³uchaj, jestem tylko bezrobotnym mieszkañcem miasta. Poproszono mnie o wziêcie notatki i przekazanie jej za kilka kapsli. I to wszystko. Nie wiem nic wiêcej.}
{205} {} {Nie ma ³atwych kapsli. Zapamiêtaj to. Teraz czas na wizytê w gildii najemników.}
{206} {} {Przykro mi kolego. Po prostu nie masz szczêœcia. Bywaj.}
{207} {} {Do widzenia.}