{100} {} {Widzisz przed sob¹ wojownika.}
{101} {} {Widzisz wojownika na arenie. Wygl¹da na to, ¿e przesadzi³ podczas treningu.}
{102} {} {Widzisz wojownika na arenie. Wygl¹da na ostro wyczerpanego.}
{103} {} {Dziêki, o wiele lepiej.}

{110} {} {* Jêk *}
{111} {} {Boli.}
{112} {} {Fuj...}
{113} {} {* Khe-khe *}
{114} {} {Um...}
{115} {} {Obrzydliwe...}
{116} {} {Nigdy wiêcej wchodzenia na ring.}
{117} {} {Gdzie jest ten cholerny lekarz?}
{118} {} {Potrzebujê znieczulenia.}
{119} {} {Gorzej z ka¿d¹ godzin¹...}

{150} {} {Za³atwi³ mnie.}
{151} {} {Jak widzisz, umieram tutaj.}
{152} {} {Ostatnia walka by³a ciê¿ka.}
{153} {} {Myœlê, ¿e dosta³em wstrz¹su mózgu.}
{154} {} {Potrzebujê lekarza...}
{155} {} {Czy masz jakieœ leki przeciwbólowe?}
{156} {} {Diler nie mo¿e znaleŸæ ¿adnego œrodka pobudzaj¹cego.}
{157} {} {Te walki s¹ wyczerpuj¹ce.}
{158} {} {* jêczy z bólu, sciskaj¹c g³owê *}
{159} {} {Um... Boli mnie g³owa!}

{170} {} {Dziêki za uratowanie mnie.}
{171} {} {Gdyby nie ty, móg³bym umrzeæ.}
{172} {} {Kto nauczy³ ciê pierwszej pomocy?}
{173} {} {Jakie szczêœcie, ¿e jesteœ w pobli¿u.}
{174} {} {Wiele osób, które zna³em, mog³oby prze¿yæ, gdybyœ by³ w pobli¿u.}
{175} {} {Mam nadziejê, ¿e nie idziesz na ring?}
{176} {} {Opatrzysz mnie po nastepnej walce, co?}
{177} {} {Kolejna walka? Dlaczego nie!}
{178} {} {Twoja pomoc bardzo siê przyda³a.}
{179} {} {Teraz wrócê na ring.}
