{100} {} {Widzisz fana.}
{101} {} {Widzisz cz³owieka, bezmyœlnie czekaj¹cego na kolejn¹ walkê.}
{102} {} {Widzisz dziko wygl¹daj¹cego cz³owieka. Krzyczy z wœciek³osci¹ na ca³e gard³o.}

# Uwagi dotycz¹ce odpowiedzi
{110} {} {Czekamy na now¹ walkê.}
{111} {} {Jak ci siê podoba³a ostatnia walka?}
{112} {} {Zelazny Mike nie szkoli ju¿ nowych wojowników.}
{113} {} {Ani jednej dobrej walki od czasów Zelaznego Mike'a.}
{114} {} {Nudy. Kiedy bêdzie nowa walka?}
{115} {} {Zak³adam wszystkie moje kapsle na tego wojownika.}
{116} {} {Obstawiasz czy bierzesz udzia³?}
{117} {} {Ten zak³ad bêdzie moim ostatnim.}
{118} {} {}
{119} {} {}

{150} {} {Witaj mistrzu.}
{151} {} {Jak siê masz, mistrzu?}
{152} {} {Czy chcia³byœ mnie o coœ spytaœ?}
{153} {} {O mój Bo¿e, mistrz mówi do mnie!}
{154} {} {Dlaczego ju¿ nie walczysz?}
{155} {} {Uderz mnie! Powiem dzieciom.}
{156} {} {Hej, pozwól mi dotkn¹æ twoich bicepsów!}
{157} {} {Dziêki tobie ja te¿ jestem zwyciêzc¹.}
{158} {} {}
{159} {} {}

{160} {} {Czeœæ. }
{161} {} {Cieszysz siê ze zwyciêstwa?}
{162} {} {Hej, hej, spokojnie!}
{163} {} {Postawi³em na twojego przeciwnika i wiesz co? Teraz jestem bankrutem...}
{164} {} {Dlaczego ju¿ nie walczysz?}
{165} {} {Tylko spróbuj mnie uderzyæ.}
{166} {} {Nie masz bicepsów?}
{167} {} {Przez ciebie przegra³em mój zak³ad.}
{168} {} {}
{169} {} {}

# Losowe frazy poza walka
{170} {} {Kiedy jest nastêpna walka?}
{171} {} {Nudyyyy.}
{172} {} {W ringu czegoœ brakuje.}
{173} {} {}
{174} {} {}
{175} {} {}
{176} {} {}
{177} {} {}
{178} {} {}
{179} {} {}

# Losowe frazy podczas bitwy
{180} {} {Postawi³em na ciebie!}
{181} {} {Smia³o!}
{182} {} {Wykoñcz go!}
{183} {} {Kocham ciê!}
{184} {} {Dobrze! WejdŸ po prawej!}
{185} {} {Broñ siê!}
{186} {} {Geralt! Geralt!}
{187} {} {Nigdy nie zapomnê tej walki.}
{188} {} {Nie mogê znieœæ tego upa³u.}
{189} {} {* Gwizd *}
{190} {} {* Krzyki *}
{191} {} {Uderz go! Uderz!}
{192} {} {No dalej!}
{193} {} {Nie zwalniaj!}

{194} {} {!}
{195} {} {No dalej }
{196} {} {Jesteœ najlepszy }
{197} {} {Wykoñcz go, }
{198} {} {Stawiam na ciebie }
{199} {} {Zrób to, }