{100} {} {Widzisz ma³ego kupca.}
{101} {} {Widzisz lokalnego sprzedawcê. Przygotowuje drinki dla widzów na arenie.}

{110} {} {Ok, to koniec mojej dzia³alnoœci.}
{111} {} {Jaki dupek musia³ zabiæ Angelo?}
{112} {} {Przepraszam, ale nie ma wiêcej drinków.}
{113} {} {Arena ju¿ nie dzia³a. Moja firma te¿.}
{114} {} {Mam szczêœcie, jeœli wyjdê st¹d ¿ywy.}

{200} {} {Potrzebujesz drinka przed walk¹? Mam akurat kilka, niedrogo.}
{201} {} {Nie, dziœ nie pijê.}
{202} {} {Czeœæ. Nigdy nie myœla³em, ¿e po takich zwyciêstwach bêdziesz chcia³ siê napiæ w takim miejscu.}
{203} {} {Niez³a walka }
{204} {} {. Tak trzymaj.}

{210} {} {Potrzebujesz drinka przed walk¹? Mam kilka, niedrogo.}
{211} {} {Do widzenia.}
{212} {} {Czy mogê obstawiaæ zak³ady na arenie?}
{213} {} {Nie wiem, kiedy jest nastêpna walka. Porozmawiaj z ludŸmi poni¿ej. Potrzebujesz drinka czy nie?}
{214} {} {Nie, dziœ nie pijê.}
{215} {} {Pomyœlê o tym.}
