{100} {} {Widzisz Angelo.}
{101} {} {Widzisz ma³ego szefa lokalnego biznesu. Uwa¿nie ciê bada.}
{102} {} {Nie bêdzie ¿adnej rozmowy, dopóki nie zobaczê ciê bez twojej zbroi.}
{103} {} {UMIERAJ!}
{104} {} {DO ZOBACZENIA W PIEKLE!}
{105} {} {PRZYGOTUJ SIE NA SMIERC!}
{106} {} {AR-RHH!}
{107} {} {SMIERC DLA LUDZI!}

# Przed wzieciem udzia³u w bitwach
{200} {} {(Przed tob¹ stoi niski mê¿czyzna w dzieciêcym garniturze, ale z biznesowymi manierami) Czego chcesz? Chcesz postawiæ zak³ad czy wzi¹æ udzia³ w walce?}
{201} {} {Ani jedno, ani drugie. Zastanawiam siê tylko, jak ktoœ taki jak Ty mo¿e zarz¹dzaæ ringiem?}
{202} {} {(szarpie naje¿onego ochroniarza) Przestañ, Rico! Uspokój siê, bracie, w porz¹dku. Te dzikusy z pustkowi nie rozumiej¹, jak wygl¹da ¿ycie w mieœcie. Zrelaksuj siê...}
{203} {} {[Dalej.]}
{204} {} {Dam ci bezp³atn¹ radê - uwa¿aj na swój brudny jêzyk. (nalewa sobie tequilê do brudnej szklanki, jak urodzony mafioso) Widzisz, miasto ceni sobie MOZG, a nie MIESNIE. Jestem mózgiem tego obszaru. Za³o¿y³em ten biznes i zgarn¹³em najwiêkszy jackpot. Lepiej rozmawiaj ze mn¹ z szacunkiem, albo Rico ciê za³atwi. Rozumiesz?}
{205} {} {Tak... proszê pana.}
{206} {} {Swietnie. Wiêc czego chcesz?}
{207} {} {Chcê siê za³o¿yæ.}
{208} {} {Chcê walczyæ.}
{209} {} {Wygl¹da na to, ¿e marnujê swój czas. Zegnaj panie Mózgu.}

{210} {} {Nie obchodzi mnie twój Rico. Nie zastraszysz mnie.}
{211} {} {Rico, bierz tê sukê...}
{212} {} {Tylko spróbuj...}
{213} {} {Dobra, dobra, nie naciskaj...}
{214} {} {Znowu? Zaczynasz dzia³aæ mi na nerwy.}
{215} {} {Domagam siê odszkodowania za leczenie. Natychmiast.}
{216} {} {Przepraszam. Teraz widzê, ¿e rozmawiam z bardzo szanowan¹ osob¹.}
{217} {} {Rico, wyrzuæ to gówno na ulicê. Jeœli znowu tu wejdzie, mo¿esz mu skrêciæ kark.}
{1217} {} {Rico, wyrzuæ tê sukê na ulicê. Jeœli znowu tu wejdzie, mo¿esz skrêciæ jej kark.}
{218} {} {W ogóle nie masz mózgu? Rico!}
{219} {} {Nawet nie próbuj...}

{220} {} {Chcê siê za³o¿yæ.}
{221} {} {Có¿, to nie najlepszy moment. Nie sporz¹dziliœmy jeszcze listy walk, brakuje nowej krwi.}
{222} {} {A co ze mn¹? Czy mogê wzi¹æ udzia³?}
{223} {} {Przepraszam. Zg³oszê siê, gdy zacznie siê sezon.}
{224} {} {Kto prowadzi ten klub?}
{225} {} {Jestem menad¿erem tego miejsca. Nazywam siê Angelo Rossitto. Coœ jeszcze?}
{226} {} {Ty? Jasne! Nie mo¿e byæ.}
{227} {} {To wszystko. Szczêœcia.}
{228} {} {W takim razie mam propozycjê - chcê braæ udzia³ w walkach.}
{229} {} {Czy mogê wzi¹æ udzia³?}
{230} {} {(patrzy na ciebie od góry do do³u, potem daje znak ochroniarzowi) Rico, spójrz na ten towar.}
{1230} {} {Kobieta i boks? Dok¹d zmierza ten œwiat... Jednak mo¿e z tego wyjœæ dobry chwyt reklamowy. Rico, sprawdŸ towar.}
{231} {} {Hej, hej, co robisz?}
{232} {} {B¹dŸ delikatny, kochany.}
{233} {} {(Rico bada twoje miêœnie i ocenia refleks, a potem potrz¹sa g³ow¹ w kierunku szefa)}
{234} {} {Co to znaczy?}
{235} {} {To znaczy, ¿e takie gówno jak ty jest do niczego. Najpierw przypakuj, a potem porozmawiamy.}
{236} {} {W¹tpiê, czy wrócê tu po takim przyjêciu. Do widzenia.}
{237} {} {W takim razie rozumiem.}
{238} {} {(Rico bada twoje miêœnie i ocenia refleks, a potem kiwa g³ow¹ do szefa)}
{239} {} {Co to znaczy?}
{240} {} {Masz potencja³. Mo¿emy znaleŸæ przeciwnika dla ciebie, ale szczerze mówi¹c, w¹tpiê w twoje umiejêtnoœci. Przed walk¹ warto poæwiczyæ. Jeœli nadal o tym myœlisz, wróæ i zaaran¿uj walkê w najlepszy mo¿liwy sposób.}
{241} {} {Swietnie, zgadzam siê.}
{242} {} {Masz potencja³. Ale to ryzykowny biznes. Pomyœl o sobie i swoich dzieciach. A jeœli * naprawdê * chcesz walczyæ, wróæ i walcz w najlepszym wydaniu.}
{243} {} {Daj mi czas na przemyœlenie.}

{250} {} {Wiêc czego chcesz?}
{251} {} {Chcê siê tylko przywitaæ. Wychodzê. Czeœæ.}
{252} {} {Czy mogê postawiæ na walkê?}
{253} {} {Chcê walczyæ na ringu. Powa¿nie.}
{254} {} {Daj mi kierownika.}

{260} {} {Jak siê masz, mistrzu? Publicznoœæ têskni za tob¹. Ale przepraszam, czas zrobiæ miejsce m³odym.}
{261} {} {W porz¹dku. Czeœæ, Angelo.}
{262} {} {Wyjdê st¹d, ¿eby tylko nie s³uchaæ tych wymówek.}
{263} {} {Jak tam ¿ycie}
{264} {} {? Publicznoœæ têskni za tob¹. Ale przepraszam, czas zrobiæ miejsce m³odym.}

{270} {} {Co chcesz wiedzieæ?}
{271} {} {Do widzenia.}
{272} {} {Jak zosta³eœ menad¿erem ringu?}
{273} {} {Zapytaj, o co chcesz }
{274} {} {.}
{275} {} {Rozumiem. To wszystko, co mnie interesowa³o.}

{280} {} {Gdzie mogê poæwiczyæ?}
{281} {} {Si³ownia jest przy schodach. Ale jeœli potrzebujesz trenera, to jest problem. Wczeœniej Zelazny Mike bra³ wojowników na trening, ale teraz upi³ siê i przeszed³ na emeryturê.}
{282} {} {Gdzie mogê go znaleŸæ?}
{283} {} {Mieszka w domu naprzeciwko areny, wystarczy przejœæ przez ulicê. Ale mo¿e nie chcieæ otwieraæ drzwi, musisz próbowaæ do skutku.}
{284} {} {Jak zosta³eœ menad¿erem ringu?}
{285} {} {Jeœli doœwiadczony zawodnik zosta³ trenerem, to jak ty zosta³eœ menad¿erem?}
{286} {} {Musisz ruszyæ mózgiem. Ja jestem mózgiem. Rozumiesz? Rico to moje miêœnie. To proste.}
{287} {} {Rozumiem. Jeœli jesteœ taki bystry, powiedz mi, gdzie mogê tutaj poæwiczyæ?}
{288} {} {W twojej recepturze na sukces wci¹¿ czegoœ brakuje. Nie jest ³atwo zdobyæ przyczó³ek w tym mieœcie.}
{289} {} {Policz to........}
{290} {} {Co siê sta³o z Mikiem?}
{291} {} {Nie wiem, czy mogê ci to powiedzieæ, ale uczniowie Mike'a zabili kiedyœ jego dziewczynê podczas napadu. Od tego wydarzenia jest rozczarowany ludŸmi.}

# Udzial w bitwach
{300} {} {(przygl¹da Ci siê i przytakuje z aprobat¹) Dobrze, mamy dla ciebie kogoœ. Bêdziesz walczyæ?}
{301} {} {Czekaj. Najpierw muszê ciê o coœ zapytaæ.}
{302} {} {Oczywiœcie. Kto jest moim przeciwnikiem?}
{303} {} {Nie jestem jeszcze w formie. Daj mi trochê czasu.}
{304} {} {Wasteland Drifter. Tak szary i nieznany jak Ty.}
{305} {} {Ile zarobiê, jeœli powalê go na ringu?}
{306} {} {Kapsle? Nie licz na szybki start, kochanie. Najpierw poka¿ swoje mo¿liwoœci. Za pierwsz¹ walkê p³acê 100 kapsli. Nikt w Phoenix nie zap³aci ci tyle za zwyk³¹ walkê.}
{307} {} {Ostatnie pytanie - czy powinien zgin¹æ podczas walki?}
{308} {} {To zale¿y od twojego pragnienia i twoich mo¿liwoœci. Ale kiedy ktoœ umiera na ringu, zachwyca to publicznoœæ i zwiêksza twoj¹ s³awê. Wiêc co powiesz?}
{309} {} {To wszystko brzmi w porz¹dku, ale mam teraz bardzo ró¿ne obawy.}
{310} {} {Mogê wejœæ na ring. Kiedy zaczynamy?}
{311} {} {Daj mi czas na przygotowanie siê.}
{312} {} {PrzyjdŸ o 20:00. Tak, jeszcze jedno. Jeœli zdecydujesz siê regularnie walczyæ, potrzebujesz dŸwiêcznego pseudonimu. Coœ potê¿nego lub niebezpiecznego, aby by³o niezapomniane i fajne na ulicach. Dobrze? Jakieœ pomys³y?}
{313} {} {[Dalej.]}
{314} {} {[Poprzedni]}
{315} {} {? Nie jest z³y. Nie zapomnij o czasie. Czekamy na Ciebie do godziny 20:00. Jeœli siê spóŸnisz, bêdê musia³ zatrudniæ innych wojowników. Wiêc nie zawiedŸ mnie }
{316} {} {Ok. Bêdê na czas.}
{317} {} {Jesteœ za wczeœnie. PrzyjdŸ o 20:00.}
{318} {} {Ok.}
{319} {} {Oto nasza wschodz¹ca gwiazda. Ju¿ zaczyna³em myœleæ, ¿e nie masz odwagi, ¿eby wejœæ na ring. Ale wydaje siê, ¿e masz jednak trochê odwagi.}
{320} {} {Jest jej wiêcej, ni¿ myœlisz. ZaprowadŸ mnie na ring.}
{321} {} {Stop, stop, muszê iœæ do toalety. Nied³ugo wrócê.}
{322} {} {Wiem. Chcia³em tylko porozmawiaæ przed rozpoczêciem.}
{323} {} {Przyby³eœ w sam¹ porê. Publicznoœæ jest ju¿ rozgrzana, czas zacz¹æ przedstawienie.}
{324} {} {Jestem gotowy skopaæ komuœ dupê. Zabierz mnie na ring!}
{1324} {} {Jestem gotowa skopaæ komuœ dupê. Zabierz mnie na ring!}
{325} {} {Daj mi trochê czasu na dostrojenie siê przed walk¹.}
{326} {} {Big Mario czeka na ciebie. I nie tylko on, ale tak¿e prawdziwa s³awa... jeœli oczywiœcie uda ci siê go pokonaæ. Wiêc co, }
{327} {} {? Czy jesteœ gotowy na decyduj¹c¹ bitwê?}
{328} {} {Big Mario Albright zobaczy dzisiaj swoj¹ pora¿kê. ZaprowadŸ mnie na ring, Angelo. ProwadŸ jak przysz³ego mistrza.}
{329} {} {Big Mario jeszcze trochê poczeka. Nied³ugo wrócê.}

# - pierwsza bitwa
{330} {} {Ca³kiem nieŸle jak na pocz¹tkuj¹cego. Chocia¿ ca³kiem nieŸle ciê poklepa³. A jednak potencja³ jest widoczny. Nie powinieneœ przestawaæ.}
{331} {} {Ca³kiem nieŸle jak na pocz¹tkuj¹cego. Masz niez³e umiejêtnoœci, warto je rozwijaæ.}
{332} {} {Naprawdê? Wow, to super.}
{333} {} {Nie jestem tutaj, ¿eby siê popisywaæ. Tylko dla kapsli.}
{334} {} {Oto twoja zap³ata, 100 kapsli. Szczera wygrana. Jeœli masz tak¹ chêæ, wróæ, zorganizujmy kolejn¹ walkê.}
{335} {} {Nie bojê siê nowej walki. Przygotuj mojego przeciwnika.}
{336} {} {Wiesz, Angelo, ring pokaza³ mi dzisiaj coœ strasznego. Smieræ. Nie chcê ju¿ tego ogl¹daæ. Do widzenia.}
{337} {} {Nie bêdzie nastepnego razu.}
{338} {} {.}

# - druga walka
{340} {} {Dobrze sobie radzisz }
{341} {} {. Bardzo dobrze. Bardzo. Mam nadziejê, ¿e nie zatrzymasz siê w po³owie podró¿y, co?}
{342} {} {Och, bardzo dobrze. Publicznoœæ zaczyna ciê lubiæ, a co wa¿niejsze, MNIE.}
{343} {} {A co z moimi kapslami?}
{344} {} {Jestem uczciwy. Oto Twoje 200 kapsli. Nie przepij wszystkiego od razu. Lepiej przygotuj siê na now¹ walkê.}
{345} {} {Kogo nastêpnym razem postawisz przeciwko mnie?}
{346} {} {Niech pomyœlê. Teraz widzê, ¿e potrzebujesz wiêkszego przeciwnika. A co z Canelo? Wygra³ dziesiêæ walk z rzêdu. Powa¿ny przeciwnik. Masz szanse, a publicznoœæ uwielbia dobre walki.}
{347} {} {Dobrze, za³atwiê tego Canelo. Nie bêdzie mia³ szans.}
{348} {} {Przemyœlê twoj¹ propozycjê. Czeœæ, Angelo.}

# - trzecia bitwa
{350} {} {Niez³a walka }
{351} {} {. Minê³o du¿o czasu, odk¹d by³y tu tak potê¿ne walki. Jesteœ prawie na szczycie. PRAWIE.}
{352} {} {Chcesz kolejnej walki?}
{353} {} {Tak, JESLI nadal masz chêæ do walki. Ale najpierw weŸ kasê, tutaj masz 400 kapsli.}
{354} {} {Z twoich s³ów wynika, ¿e nastêpna walka bêdzie z jakimœ powa¿nym zawodowcem.}
{355} {} {To nie jest tylko zawodowiec. To sam niezwyciê¿ony Big Mario Albright! On sam marzy o walce z tob¹. Dlatego dobrze przygotuj siê do bitwy. Nikomu jeszcze nie uda³o siê zwaliæ tego kolosa z nóg.}
{356} {} {Zaczyna siê we mnie budziæ bestia. Nie mogê siê powstrzymaæ od podjêcia tego wyzwania.}
{357} {} {Nie s¹dzê, ¿ebym móg³ podj¹æ kolejn¹ tak¹ walkê. Do widzenia, Angelo.}
{358} {} {Prawie? Wiêc bêdê musia³ rozmazaæ jeszcze jedn¹ twarz na ringu, ¿eby byæ najlepszym?}
{1358} {} {Prawie? Wiêc bêdê musia³a rozmazaæ kolejn¹ twarz na ringu, ¿eby byæ najlepsza?}

#- Ostatnia walka
{360} {} {To by³a wspania³a walka }
{361} {} {! Publicznoœæ jest zachwycona, dawno nie by³o takiego podniecenia. Zebraliœmy ogromne zak³ady, poniewa¿ wielu uwa¿a³o, ¿e Big Mario jest niepokonany. Ale uda³o Ci siê to zrobiæ! Dobra robota. Oto twoje 800 kapsli. Ale teraz porozmawiajmy o z³ych rzeczach.}
{362} {} {Czy coœ nie tak?}
{363} {} {Widzisz, jesteœ teraz kimœ w rodzaju mistrza. Niezwyciê¿ony. Rozumiesz? Nie mamy wojowników, którzy mogliby ci siê przeciwstawiæ. I nie s¹dzê, ¿e pojawi siê ktoœ taki w najbli¿szym czasie. A jeœli publicznoœæ zacznie na ciebie stawiaæ i wygrywaæ, to nic z tego nie uzyskamy. Przecie¿ zarabiamy g³ównie na kursach PRZEGRANYCH. Rozumiesz?}
{364} {} {Czy to oznacza, ¿e nie bêdê móg³ wiêcej walczyæ?}
{365} {} {Co do cholery, wyrzucasz mnie z ringu?}
{366} {} {Dok³adnie. Przepraszam, amigo, ale ka¿dy mia³ swój z³oty czas. Wspó³praca z tob¹ by³a przyjemnosci¹, ale nadszed³ czas, abyœmy siê po¿egnali.}
{367} {} {Cholera, Angelo, czy nie interesuje ciê nic oprócz kapsli? Wygl¹da na to, ¿e nie mam nic wiêcej do roboty w tym ringu.}
{368} {} {Pierdol siê!}

{370} {} {Opowiedz mi o moim przeciwniku.}
{371} {} {Opowiedz mi o moim nowym przeciwniku.}
{372} {} {Opowiedz mi o moim nastêpnym przeciwniku.}
{373} {} {Opowiedz mi o moim przeciwniku.}
{374} {} {Wasteland Drifter. To typowy nowy na ringu.}
{375} {} {By³y pustynny bandyta o imieniu Savage. Po upadku gangu przyby³ do Phoenix i próbuje zarobiæ na walkach, bo nic wiêcej nie potrafi robiæ. Uwielbia walczyæ, ale sam nie jest w najlepszej formie. Nic dziwnego dla w³óczêgi z autostrady.}
{376} {} {Canelo to jeden z najlepszych zawodników na ringu. Jesteœcie siebie warci. Ciê¿ko przygotowywa³ siê do walki, uwa¿aj na niego, jest silniejszy i szybszy ni¿ twoi dawni rywale.}
{377} {} {Tym razem musisz walczyæ z prawdziw¹ besti¹ w ludzkiej skórze. Jego pseudonim to Big Mario. Wygra³ tyle razy, ¿e straci³em rachubê. Nikt nie chce mu siê przeciwstawiæ, jesteœ jedyn¹ osob¹, która jest w stanie z nim walczyæ. To bêdzie ciê¿ka walka, ale zastanów siê, ile z tego wpadnie kapsli.}
{1377} {} {Tym razem musisz walczyæ z prawdziw¹ besti¹ w ludzkiej skórze. Jego pseudonim to Big Mario. Wygra³ tyle razy, ¿e straci³em rachubê. Nikt nie chce mu siê przeciwstawiæ, tylko ty mo¿esz go pokonaæ. To bêdzie ciê¿ka walka, ale zastanów siê, ile z tego wpadnie kapsli.}
{378} {} {Rozumiem. Muszê siê przygotowaæ do bitwy.}

{380} {} {Jak tam ¿ycie }
{381} {} {? Publicznoœæ têskni za tob¹. I wiesz co, nagle pojawi³ siê rywal dla ciebie. Wydaje siê, ¿e jesteœcie dla siebie stworzeni. Zainteresowany?}
{382} {} {Nie. Zrezygnowa³em z walk.}
{1382} {} {Nie. Zrezygnowa³am z walk.}
{383} {} {Przykro mi to s³yszeæ. Có¿, jeœli zmienisz zdanie, daj mi znaæ.}
{384} {} {Ok.}
{385} {} {Dlaczego nie? Opowiedz mi o moim przeciwniku.}
{386} {} {Oczywiœcie!}
{387} {} {Co za gorliwoœæ! Nie po¿a³ujesz.}
{388} {} {Opowiedz mi o moim przeciwniku.}
{389} {} {Do miasta przyby³ pewien g³upi zielonoskóry du¿y facet. Prawdziwy kurwa mutant. Jego biceps wygl¹da jak podpora mostu. Nikt nie mo¿e go pokonaæ. Ale ty masz szansê.}
{390} {} {W takim razie przygotuj ring. Bêdê jak zwykle o 20:00.}
{391} {} {O nie, widzia³em ich. Odpadam.}
{392} {} {Big Green Son of a Bitch czeka na ciebie na ringu,}
{393} {} {}
{394} {} {Tam czeka go tylko œmieræ.}
{395} {} {Muszê siê napiæ wody. Daj mi kilka minut.}
{396} {} {To jeszcze nigdy siê nie zdarzy³o w Phoenix! Widok by³ niezapomniany. O tej bitwie powstan¹ legendy. Jak siê czujesz? Wygl¹da na to, ¿e ta walka bardzo ciê wyczerpa³a. Oto 1500 kapsli, przydadz¹ ci siê ¿eby dojœæ do siebie.}
{397} {} {Jesteœ dzisiaj szczególnie troskliwy, Angelo. Doceniam to. Dziêkujê Ci.}
{398} {} {Prawie mnie zabi³, a ty siê tu radujesz jak dziecko. Moja stopa ju¿ tu wiêcej nie postanie.}