{100} {} {Widzisz Rico.}
{101} {} {Widzisz wielkiego faceta z g³upim wyrazem twarzy, ale jednoczeœnie bardzo imponuj¹cym.}

{110} {} {Czy s³ucham?}
{111} {} {Nie mów sh krasnoludzie.}
{112} {} {Angelo tu rz¹dzi.}
{113} {} {Czego chcesz?}
{114} {} {SpóŸni³em siê.}
{115} {} {Jestem g³odny.}
{116} {} {Trzymaj rêce tam, gdzie mogê je zobaczyæ.}
{117} {} {Wbiegasz, co?}
{118} {} {Siad. Mówiê SIAD!}
{119} {} {Wyjmij to!}
{120} {} {* Beka *}
{121} {} {* Wyci¹ga rêce w odpowiedzi *}
{122} {} {Pachniesz jak dziecko.}
{123} {} {Nie patrz na mnie.}
{124} {} {Przestañ mówiæ.}
{125} {} {Muszê siê przespaæ.}
{126} {} {Potrzebujesz trenera?}
{127} {} {Aha.}
{128} {} {WyjdŸ st¹d.}
{129} {} {Nie stój obok mnie.}
{130} {} {* Patrzy na Ciebie têpo *}
{131} {} {Czego chcesz?}

{150} {} {(zazdroœnie) Swietna walka.}
{151} {} {Walcz jak wœciek³y pies.}
{152} {} {Kto ciê nauczy³ walczyæ?}
{153} {} {Nie bij mnie!}
{154} {} {Jesteœ m¹dry. Jestem s³aby.}
{155} {} {Daleko mi do ciebie.}
{156} {} {Nie bêdê z tob¹ walczy³.}
{157} {} {Nie jesteœ cz³owiekiem. Jesteœ besti¹.}
{158} {} {Potrzebujê trenera.}
{159} {} {Trenuj mnie.}
{160} {} {* Beka *}
{161} {} {* Uœmiecha siê bezzêbnymi ustami *}
{162} {} {* G³upio kiwa g³ow¹ *}

{200} {} {* P³acze jak dziecko *}
{201} {} {Andje-e-eats!}
{202} {} {Andje-ate! Andje-ate!}
{203} {} {* Szlocha *}
{204} {} {Ooh...}
{205} {} {* Jêk *}
{206} {} {Nie patrz! Nie patrz!}
{207} {} {Zabijê! Zabijê wszystkich!}
{208} {} {Suki! Suki!}
{209} {} {Angelo by³ m¹dry, ja jestem g³upi.}
{210} {} {Kto to zrobi³?!}
{211} {} {Poka¿ mi, kto to zrobi³!}
{212} {} {Kto zabi³ mojego Angelo?}
{213} {} {* Bierze g³êboki oddech *}