{100} {} {Widzisz swojego przeciwnika.}
{101} {} {Widzisz Savage.}
{102} {} {Widzisz Canelo.}
{103} {} {Widzisz Big Mario.}
{104} {} {Widzisz Super mutanta.}

{105} {} {Widzisz swojego przeciwnika. W pewnym sensie sugeruje, ¿e postawi³ na ciebie swoje kapsle.}
{106} {} {Widzisz swojego przeciwnika. W pewnym sensie sugeruje, ¿e nie mo¿esz siê z nim równaæ.}
{107} {} {Widzisz swojego przeciwnika. Widzi w tobie tylko cel.}
{108} {} {Widzisz swojego przeciwnika. A w jego oczach - niewypowiedzian¹ wœciek³oœæ.}
{109} {} {Widzisz swojego przeciwnika. Ale lepiej go nie widzieæ.}

{110} {} {UMIERAJ!}
