{100} {} {Widzisz Arthura Carrington.}
{101} {} {Widzisz znajomego z Krypty 27.}
{102} {} {Dziêki za wszystko! Do zobaczenia w Casa Nueva.}
{103} {} {Dziêki za wszystko! Do zobaczenia w Villi.}

# Pierwszy dialog
{200} {} {Oto mój wybawca. Cieszê siê, ¿e ciê widzê.}
{201} {} {Co tu robisz? Wydawa³o mi siê, ¿e po przygodzie w Krypcie pójdziesz do Swi¹tyni Ognia i zajmiesz siê nauk¹.}
{202} {} {To w³aœnie zrobi³em. Ale Swi¹tynia Ognia zosta³a zniszczona. Nie wiem, co siê tam sta³o, ale czciciele ognia s¹ teraz na wygnaniu i nikt nie potrzebuje ju¿ naukowca takiego jak ja.}
{203} {} {Na pewno?}
{204} {} {Oto wskazówka. W Swi¹tyni natkn¹³em siê na sk¹pe doniesienia o kulcie z naukowym nastawieniem, zwanym Wyznawcami Apokalipsy. Ich baza znajduje siê gdzieœ na po³udniu, ale brakuje informacji. Jeœli spotkasz tych ludzi, daj mi znaæ. W porz¹dku?}
{205} {} {Nic nie obiecujê. Dziêki za wskazówkê.}

{210} {} {I co teraz?}
{211} {} {Nic. Czeœæ.}
{212} {} {Do widzenia.}

{220} {} {Jak myœlisz, dlaczego Swi¹tynia Ognia upad³a?}
{221} {} {Wiem, ¿e w sanktuarium pod swi¹tyni¹ robiono bombê atomow¹. Ale spontaniczna eksplozja jest prawie niemo¿liwa. To bardziej przypomina sabota¿. Czciciele ognia mieli wielu wrogów, jedyn¹ zaskakuj¹c¹ rzecz¹ jest to, ¿e byli oni w stanie przenikn¹æ tak g³êboko. Hmm, najwyraŸniej by³ to ktoœ, komu ufali...}
{222} {} {To by³em ja.}
{1222} {} {To by³am ja.}
{223} {} {Nie mów takich rzeczy. Nadal nie wierzê ci na s³owo, a nie potrzebujesz dodatkowych plotek w mieœcie, uwierz mi.}
{224} {} {Po co im bomba?}
{225} {} {Wiem tylko, ¿e by³a wykonywana na zamówienie.}
{226} {} {Co zamierzasz teraz zrobiæ?}
{227} {} {Poszukam miejsca, w którym potrzebni s¹ tacy naukowcy jak ja. Poza w¹tpliwymi plotkami o Wyznawcach Apokalipsy nie mam innych pomys³ów.}
{228} {} {Przenieœ siê do Villi. Potrzebujemy r¹k do pracy, aby dojœæ do siebie po nalocie. I œwie¿ych umys³ów, które nie bêd¹ ograniczone naszymi podstawami.}
{229} {} {Villa, o której mówi³eœ w Krypcie, prawda? Poszuka³em informacji i dowiedzia³em siê, ¿e jest to zamkniêta spo³ecznoœæ wiejska. Kult Ognia zebra³ o tobie ca³kiem sporo informacji. Myœlê, ¿e to œwietne miejsce do badañ i wprowadzania nowych technologii.}
{1229} {} {Villa, o której mówi³aœ w Krypcie, prawda? Poszuka³em informacji i dowiedzia³em siê, ¿e jest to zamkniêta spo³ecznoœæ wiejska. Kult Ognia zebra³ o tobie ca³kiem sporo informacji. Myœlê, ¿e to œwietne miejsce do badañ i wprowadzania nowych technologii.}
{230} {} {Ok. Kiedy tam dotrzesz, powiedz, ¿e jesteœ ode mnie. Do zobaczenia w Villi.}
{231} {} {Nie œpiesz siê, nadal spróbujê dowiedzieæ siê czegoœ o Wyznawcach Apokalipsy.}
{232} {} {Uda³o mi siê znaleŸæ Obserwatorów w Casa Nueva. Chêtnie zaakceptuj¹ kogoœ takiego jak ty. Wiêc ruszaj w drogê.}
{233} {} {Jak na mieszkañca farmy masz niesamowit¹ liczbê kontaktów. Dziêkujê, jesteœ prawdziwym bohaterem.}
{234} {} {Do zobaczenia w Casa Nueva.}

{240} {} {Poszukam miejsca, w którym potrzebni s¹ tacy naukowcy jak ja. Na razie wiem tylko o bazie naukowej w Casa Nueva. Ale moja reputacja... nie pasuje do tego miejsca. Czy znasz inne miejsca?}
{241} {} {Przenieœ siê do Villi. Potrzebujemy r¹k do pracy, aby dojœæ do siebie po nalocie. I œwie¿ych umys³ów, które nie bêd¹ ograniczone naszymi podstawami.}
{242} {} {Villa, o której mówi³eœ w Krypcie, prawda? Poszuka³em informacji i dowiedzia³em siê, ¿e jest to zamkniêta spo³ecznoœæ wiejska. Kult Ognia zebra³ o tobie ca³kiem sporo informacji. Myœlê, ¿e to œwietne miejsce do badañ i wprowadzania nowych technologii.}
{1242} {} {Villa, o której mówi³eœ w Krypcie, prawda? Poszuka³em informacji i dowiedzia³em siê, ¿e jest to zamkniêta spo³ecznoœæ wiejska. Kult Ognia zebra³ o tobie ca³kiem sporo informacji. Myœlê, ¿e to œwietne miejsce do badañ i wprowadzania nowych technologii.}
{243} {} {Ok. Kiedy tam dotrzesz, powiedz, ¿e jesteœ ode mnie. Do zobaczenia w Villi.}
{244} {} {Wiesz, to z³y pomys³. Nie zostaniesz tam dobrze przyjêty, ogólnie mamy tam z³y stosunek do naukowców. Lepiej idŸ do Casa Nueva. Albo dok¹d siê tam wybierasz.}
{245} {} {Casa Nueva na pewno dobrze powita innego naukowca. Mo¿e kiedyœ tam zajrzê.}
{246} {} {Zgadza siê. Chocia¿ droga przez pustyniê nie jest ³atwa. Mo¿e jeszcze kiedyœ ciê zobaczê.}
{247} {} {Dobrze. Do zobaczenia w Casa Nueva.}
{248} {} {Ma³o prawdopodobne. Zegnaj Arturze.}