{100} {} {Widzisz Kishka.}
{101} {} {Widzisz chudego mê¿czyznê w brudnych ubraniach.}
{102} {} {* Hrum-hrum * Vku-sleep. Teraz mo¿esz rozmawiaæ.}
{103} {} {Uh, jak to siê sta³o? Jest taka cholernie du¿a.}

{110} {} {Squatter jest zbyt g³odny, ¿eby rozmawiaæ.}
{111} {} {Masz jakieœ jedzenie?}
{112} {} {Czy chcia³byœ siê podzieliæ czymœ jadalnym?}
{113} {} {Podzielisz siê swoimi zapasami?}
{114} {} {Wszyscy s¹ tutaj jak rodzina. Wiêc wszyscy dziel¹ siê swoj¹ zdobycz¹.}
{115} {} {Nowicjusze maj¹ za³atwiæ coœ do jedzenia innym. Taka panuje tu zasada.}

#Dialog
{200} {} {Dziêki za jedzenie. Nie czêsto mamy tu turystów. Zwykle, jeœli ktoœ siê pojawi, nie znaczy to nic dobrego. Nie masz zamiaru stwarzaæ nam problemów, prawda?}
{201} {} {Zale¿y od tego, jakie odpowiedzi otrzymam od ciebie.}
{202} {} {Nie, ¿adnych problemów, kolego.}

{210} {} {Wiêc co ciê sprowadza do tego lochu, czysta skóro?}
{1210} {} {Wiêc co ciê sprowadza do tego lochu, czysta skóro?}
{211} {} {Do widzenia.}
{212} {} {Myœlê, ¿e masz doœæ. Do widzenia.}
{213} {} {Bardzo interesuj¹ce. Czy chcesz mi powiedzieæ wiêcej?}

{220} {} {Kim jesteœcie?}
{221} {} {Ludzie na powierzchni nazywaj¹ nas squatersami. Nie mamy domu, pracy, przyjació³ na powierzchni. Mieszkamy w tych kana³ach.}
{222} {} {Czy macie lidera?}
{223} {} {Nie, tutaj wszyscy s¹ równi.}
{224} {} {Kim jesteœ?}
{225} {} {Wœród moich jestem Kishka. Ale mo¿esz mówiæ do mnie Senor Hidalgo. Hihi. To jest ¿art. Niejasny? Có¿... Ok, zapomnij o tym.}
{226} {} {Od jak dawna mieszkasz w kana³ach?}
{227} {} {Jak d³ugo jesteœ w kana³ach, Kishka?}
{228} {} {Lapa³em tu szczury, odk¹d by³em m³ody. A w niespokojnych czasach moja rodzina ukrywa³a siê w metrze przed problemami. Teraz ju¿ nawet nie chcê wracaæ na górê.}

{230} {} {Dlaczego mieszkasz w kanale?}
{231} {} {Jest tu ca³kiem mi³o, jeœli siê do tego przyzwyczaisz. Na górze ludzie strzelaj¹ do siebie, ale tutaj wszyscy jesteœmy równi. Rozumiesz? Pomagamy sobie, dzielimy siê jedzeniem jeœli jakieœ mamy. Tak w³aœnie ¿yjemy.}
{232} {} {Jak tu przetrwaliœcie?}
{233} {} {Lapiemy szczury i zbieramy œwiec¹ce grzyby. Czasami wychodzimy na powierzchniê, aby wymieniæ je na coœ, czego potrzebujemy.}
{234} {} {Hmm. A wiêc sprzedawca na targu bierze szczury od was?}
{235} {} {Jesteœmy w tym najlepsi. Nikt nie wie, jak ³apaæ szczury tak jak my.}
{236} {} {Niesamowite. Chcê dowiedzieæ siê wiêcej o twoich ludziach.}
{237} {} {Ok, to mi wystarczy. Ju¿ st¹d wychodzê.}

{240} {} {Czy zauwa¿y³eœ coœ interesuj¹cego w tych katakumbach?}
{241} {} {Tak jakby. Ostatnio coraz czêœciej widaæ tu obcych i s³ychaæ niezwyk³e dŸwiêki.}
{242} {} {DŸwiêki?}
{243} {} {Nie wiem. Zwykle jest tu doœæ cicho. Ale zdarza siê, ¿e ha³as narasta, jakby wiele g³osów na raz szepta³o do jakiejœ rury. Niektórzy myœl¹, ¿e to duch, hehe. Ale ja im nie wierzê.}
{244} {} {Opowiedz mi o tej legendzie o duchach.}
{245} {} {Mówi¹, ¿e podczas wojny w metrze ukrywa³ siê szlachcic razem ze swoj¹ rodzin¹. Ale g³ód z³ama³ mu ducha. Najpierw zjad³ ¿onê, a potem dziecko. A kiedy nadszed³ czas, aby umrzeæ, jego duch zosta³ tu i wêdruje po kana³ach w poszukiwaniu dawno zaginionej rodziny. (rozgl¹da siê) S³yszysz? Czasami wydaje mi siê, ¿e w tej historii jest trochê prawdy.}
{246} {} {Smutna historia. Ale wci¹¿ mam wiele pytañ.}
{247} {} {Nie ma nic g³upszego ni¿ opowieœci o wêdruj¹cych duszach. Nie chcê ju¿ nic wiêcej od Ciebie s³yszeæ.}
{248} {} {Wierzysz w duchy? Powa¿nie?}

{250} {} {Wiesz, jak dostaæ siê g³êbiej do kana³ów?}
{251} {} {St¹d nie ma szans. Bêdziesz musia³ wyjœæ na powierzchniê i znaleŸæ inny w³az. Ale zaufaj mi, lepiej nie iœæ tam samemu.}
{252} {} {Co tam jest?}
{253} {} {Hordy potworów, osuwiska, do³y z trucizn¹ - o wiele wiêcej ni¿ tutaj. Ale nawet my, lokatorzy, nie znamy wszystkich sekretów kana³ów. Ostatnio coraz czêœciej znajdujemy zw³oki ludzi o czystej skórze. Nie wiem, czego tutaj szukaj¹.}
{254} {} {Wow, sporo wiesz o tym kanale. Czy chcesz mi powiedzieæ wiêcej?}
{255} {} {Ok, wracam na powierzchniê. Teraz.}