{100} {} {Widzisz squattera.}
{101} {} {Widzisz brudnego cz³owieka w ³achmanach. Brzydko pachnie.}

# Plywajace repliki
{110} {} {Huh? Co?}
{111} {} {S³yszysz?}
{112} {} {Czujê czyst¹ skórê. Mamy goœci?}
{113} {} {Wygl¹da na to, ¿e mamy nowych turystów.}
{114} {} {To jeszcze nie sezon szczurów.}
{115} {} {Muszê sprawdziæ pu³apki na szczury.}
{116} {} {Znowu schodzi mi skóra.}
{117} {} {Uff. Muszê nape³niæ ¿o³¹dek...}
{118} {} {* Drapie siê *}
{119} {} {* Khe-khe-khe *}

# Uwagi dotycz¹ce odpowiedzi

# - YG w szklach blacharskich
{130} {} {Sprytnie. Miej oczy szeroko otwarte w tych okularach.}
{131} {} {Jeœli mia³bym takie okulary co ty - nie z³ama³bym nogi dwa razy w zesz³ym tygodniu.}
{132} {} {Jeœli mieszkasz w kana³ach tak jak my, nie bêdziesz potrzebowaæ okularów.}
{133} {} {Zostañ tu jeœli chcesz - do ciemnoœci te¿ siê przyzwyczaisz.}
{134} {} {Czy w tych okularach mo¿esz przejrzeæ moje ubrania?}

# - GG zakrada siê
{135} {} {Dlaczego siê tak skradasz?}
{136} {} {Czy ty siê przed kimœ ukrywasz?}
{137} {} {Tak, stañ siê jednoœci¹ ze scian¹. Ale i tak ciê widzê.}
{138} {} {Czy zawsze siê tak ruszasz?}
{139} {} {Pieprzeni pijani turyœci.}

# - Popularne zwroty
{150} {} {Czeœæ.}
{151} {} {Czego szukasz w tym lochu, przystojniaku?}
{152} {} {Nowy? Ok, nie mam nic przeciwko.}
{153} {} {Zgubi³eœ siê? Miasto jest wy¿ej.}
{154} {} {Turyœci nie odwiedzaj¹ nas zbyt czêsto.}

{155} {} {Fajnie jest tutaj. Prawda, prawda.}
{156} {} {Podziel siê jedzeniem.}
{157} {} {Cii! Mów ciszej.}
{158} {} {S³yszysz? To oddech miasta powy¿ej.}
{159} {} {Zwykle jest tu cicho i spokojnie... dopóki ktoœ tu nie przyjdzie.}

{160} {} {Czeœæ.}
{161} {} {Czego szukasz w lochu, piêkna?}
{162} {} {Nowa dziewczyna? Ok, nie mam nic przeciwko.}
{163} {} {Zgubiona? Miasto jest wy¿ej.}
{164} {} {Turyœci nie odwiedzaj¹ nas zbyt czêsto.}