{100} {} {Widzisz lokatora.}
{101} {} {Widzisz chudego mê¿czyznê w brudnych ubraniach.}
{102} {} {* Hrum-Hrum *}
{103} {} {Byli kardyna³ami! Wysadzili stacjê!}

#Dialog
{200} {} {Och, mamo, nie strasz mnie tak! Ludzie rzadko tu przychodz¹.}
{201} {} {Przepraszam, nie chcia³em. Co Ty tutaj robisz?}
{1201} {} {Przepraszam, nie chcia³am. Co Ty tutaj robisz?}
{202} {} {Idiota! Serce prawie mi stanê³o. Co ty tu w ogóle robisz?}
{203} {} {Lapiê szczury. S¹ szybkie i przebieg³e, wiêc nie wpadaj¹ tak ³atwo w pu³apki. Czasami muszê czekaæ w zasadzce godzinami.}
{204} {} {Có¿, powodzenia w twoich trudnych przedsiêwziêciach. Bywaj.}
{205} {} {Jeœli jesteœ tu od d³u¿szego czasu, to na pewno wiesz, kto wszed³ do wschodnich kana³ów?}
{206} {} {Tak. Co siê ze mn¹ stanie, jeœli ci powiem?}
{207} {} {Dam ci jedzenie. Zaczekaj, zaraz coœ przyniosê...}
{208} {} {Masz tu jedzenie. Powiedz mi teraz co wiesz.}
{209} {} {Oto dziesiêæ kapsli na jedzenie.}
{210} {} {Och, dziêkujê bardzo.}
{211} {} {A teraz powiedz mi co wiesz.}
{212} {} {Przepraszam, ale mój portfel jest pusty.}
{213} {} {Zostawiê ciê przy ¿yciu, œmieciu.}
{214} {} {OdejdŸ! Albo wyœlê na ciebie stado szczurów. Shoo! Spadaj!}
{215} {} {No có¿. }
{216} {} {Nadal musisz brudziæ sobie rêce. Powiedz, co widzia³eœ!}
{217} {} {Zostawiê ciê przy ¿yciu, œmieciu.}
{218} {} {Miej litoœæ! Powiem ci wszystko!}
{219} {} {No dalej, powiedz mi co wiesz.}
{220} {} {Byli kardyna³ami. Mieli te¿ ze sob¹ mnicha i ghula. Powiedzieli, ¿e chc¹ wysadziæ kilka rur, ¿eby oszukaæ szefa stacji. To skomplikowana historia, ja sam nic z tego nie rozumiem.}
{221} {} {Dobra robota, do widzenia.}
{222} {} {Dziêki kolego. Bardzo mi pomog³eœ.}

{250} {} {Czeœæ. Coœ ostatnio czêsto widzê tu ludzi.}
{251} {} {Dziêki za jedzenie. Masz tego wiêcej?}
{252} {} {Co tu robisz?}
{253} {} {Do widzenia.}
