{100} {} {Widzisz gracza.}
{101} {} {Widzisz goœcia kasyna. W ka¿dy mo¿liwy sposób przedstawia niezadowolenie z obs³ugi, a jednoczeœnie z ca³ego œwiata.}
{102} {} {Zostaw mnie, chcê siê upiæ i rozwaliæ ca³e miasto.}

{110} {} {Jak œmiesz wyrzucaæ mnie na ulicê?}
{111} {} {Domagam siê przeprosin.}
{112} {} {Gdyby nie ja, ca³e miasto by³oby bez energii.}
{113} {} {Czy wiesz, kim jestem?}
{114} {} {Smiejesz siê, co? Smiejecie siê wszyscy ze mnie?}

{200} {} {(krzyczy w stronê kasyna) ...Hej, wy! Popamiêtacie mnie, brudne zdziry...}
{201} {} {Co tu siê dzieje?}
{202} {} {Och, kim jesteœ? Ty te¿ chcesz trafiæ jackpota w kasynie? Nie, nic z tego nie wyjdzie. S¹ tam sami oszuœci...}
{203} {} {Czy jest pan pijany?}
{204} {} {Pijany? Trochê siê napi³em. Tak jak po³owa miasta. W³¹cznie z kobietami i dzieæmi.}
{205} {} {Uch, rozumiem.}
{206} {} {Co tam rozumiesz? Ach... (macha rêk¹) Nie rozumiesz. Pracowa³em w najlepszej karawanie, a teraz nie chc¹ mi daæ nawet najmniejszej zni¿ki w tym brudnym, zadymionym barze. Wielkie dziêki...}
{207} {} {Karawanie? Jakiego rodzaju karawanie?}
{208} {} {Tej która zabiera³a rudê do Tu-San. Teraz Blacharze rdzewiej¹ na s³oñcu, a ja nie mam pracy. Wszystko dziêki idiocie, który do tego doprowadzi³.}
{209} {} {Wiesz, nie s¹dzê, ¿e chcia³ takich konsekwencji...}
{210} {} {Pierdol siê! (macha rêk¹ i odchodzi)}
{1210} {} {Pierdol siê! (macha rêk¹ i odchodzi)}
{211} {} {Uch...}
{212} {} {To twoja wina, ¿e wspó³pracowa³eœ siê z tymi podejrzanymi typami.}
{213} {} {Blacharzami? Tak, zaopatrzyli ca³e miasto w energiê... Ech, nie rozumiesz. (macha rêk¹ i odchodzi, mamrocz¹c coœ pod nosem)}
{214} {} {Uch, cokolwiek powiesz, stary.}