{100} {} {Widzisz Zelaznego Mika.}
{101} {} {Widzisz wci¹¿ twardego, ale zgrzybia³ego wojownika.}
{102} {} {Co... Nie rozmawiam z tchórzami, którzy chowaj¹ siê w zbroi wspomaganej przed bezbronn¹ osob¹.}
{103} {} {Ktoœ zabi³ Angelo. Znajdê tego sukinsyna i osobiœcie skrêcê mu kark.}
{104} {} {Kolejny æpun... WyjdŸ. Mówiê WYJDZ.}
{105} {} {Uh nie kolego, nie chcê mieæ do czynienia z kardyna³ami.}

# Pierwszy dialog 1
{200} {} {(Wchodz¹c w mrok dusznego pokoju, spêdzasz trochê czasu próbuj¹c przyzwyczaiæ siê do obrzydliwego zapachu alkoholu i dymu. Wkrótce coœ na starym poszarpanym krzeœle wykonuje niebezpieczny ruch i krzyczy „Hej, wynoœ siê z mojego pokoju! ” Rzuca w ciebie butelk¹.)}
{201} {} {Co robisz, draniu?!}
{202} {} {Przepraszam, nie chcia³em ci przeszkadzaæ...}
{1202} {} {Przepraszam, nie chcia³am ci przeszkadzaæ...}
{203} {} {(Mo¿esz zobaczyæ mê¿czyznê na krzeœle o bardzo silnej budowie cia³a; jego rêce i ³ysa g³owa pokryte s¹ mglistymi tatua¿ami bojowymi). Nie chcê nikogo widzieæ. WyjdŸ!}
{204} {} {Ok, cokolwiek powiesz...}
{205} {} {Nie myœl, ¿e ujdzie ci to na sucho.}
{206} {} {OdejdŸ. Nie chcê nikogo widzieæ.}
{207} {} {Porozmawiamy?}
{208} {} {Nie rozumiesz za pierwszym razem? WyjdŸ!}
{209} {} {Tylko...}

# Pierwszy dialog 2
{210} {} {Przepraszam za krzyk. Czasami nic na to nie poradzê, zw³aszcza po drugiej butelce tequili.}
{211} {} {Rozumiem.}
{212} {} {Nastêpnym razem bêdê móg³ zrobiæ to samo.}
{213} {} {Nazywam siê Mike. Nazywa siê mnie te¿ czasem Zelaznym, bo nikomu nie uda³o siê mnie pokonaæ na ringu. Ale wiesz co? Pieprzyæ ich! Jestem zmêczony tymi walkami. Ludzie walcz¹ tylko o kapsle, a ja walczy³em o prawo do bycia najlepszym. To nie jest to samo.}
{214} {} {Jeœli ju¿ nie walczysz, to co robisz?}
{215} {} {(wypija resztê butelki i wzdycha) Pijê! I wspominam o dawnych czasach. Powa¿nie, nie by³oby mi trudno zarobiæ dodatkowe pieni¹dze na „pokazach si³y”. Ale ja nie chcê. Miasto jest pogr¹¿one w grzechu... s³uchasz?}
{216} {} {Tak, uh, w grzechu. Co masz na myœli?}
{217} {} {Hej, zostaw mi kilka kropli.}
{218} {} {Uczy³em m³odych wojowników podstaw walki ulicznej. Ale potem weszli w podejrzane interesy, zostali bandytami lub pomocnikami szefów gangów. Nikogo innego ju¿ nie uczê. Teraz tylko pijê - i wszyscy dobrze siê z tym czuj¹.}
{219} {} {To nie brzmi fajnie.}
{220} {} {Jasne, jesteœ kompletn¹ pora¿k¹.}
{221} {} {Wszyscy ci rewolucjoniœci, sekciarze, bandyci, naci¹gacze z czarnego rynku - nikt nie dba o ciebie ani o miasto. Ka¿demu zale¿y na w³asnej korzyœci... A tak przy okazji, co tu robisz?}
{222} {} {Chcê tylko poznaæ nowych ludzi. Od niedawna jestem w mieœcie.}
{223} {} {(drapie zarost i robi obojêtny grymas) Nie jesteœ do tego w najlepszym miejscu, dzieciaku. Jednak walka na ringu prawdopodobnie zwróci na ciebie uwagê.}
{224} {} {Czy tak w³aœnie jest? Swietnie, pomyœlê o tym, ¿eby tam pójœæ.}
{225} {} {W³aœciwie to szukam mojej rodziny. Zostali porwani przez handlarzy niewolników.}
{226} {} {Przepraszam, nie anga¿ujê siê w to. Ale wiem, ¿e czciciele ognia s¹ w jakiœ sposób powi¹zani z handlarzami niewolników. Uwa¿aj na nich - to ryzykowna gra.}
{227} {} {Dziêki, Mike. Wygl¹da na to, ¿e pora porozmawiaæ z tymi czcicielami ognia.}
{228} {} {Chcê nauczyæ siê sztuk walki.}
{229} {} {Powiedzia³em wczeœniej, ¿e nie zamierzam nikogo szkoliæ.}
{230} {} {Przykro mi to s³yszeæ.}

{240} {} {Opowiedz mi o arenie.}
{241} {} {Angelo Rossitto prowadzi tam interes. To mi³y facet, wie, jak zachowaæ przenikliwoœæ biznesow¹. Chocia¿ ze wzglêdu na jego naturê czasami chce siê go spakowaæ do muszli klozetowej, wciskaj¹c i wciskaj¹c sp³uczkê.}
{242} {} {Opowiedz mi o swoich zwyciêstwach na ringu.}
{243} {} {Wygra³em wszystkie swoje walki. Ulica nauczy³a mnie biæ siê, a ci¹g³e treningi pozwoli³y mi utrwaliæ moje umiejêtnoœci. Przyjrza³em siê nawet niektórym technikom ze starych ksi¹¿ek i filmów.}
{244} {} {Filmów?}
{245} {} {Mia³em szczêœcie. W tym czasie padlino¿ercy znaleŸli ocala³y projektor i stare taœmy filmowe. Ktoœ u¿y³ ich do pokazów filmowych. Wtedy by³a to jedyna normalna rozrywka w mieœcie. Ale teatr nie istnia³ d³ugo. W³aœciciel zosta³ zabity przez rabusiów, a projektor zosta³ skradziony. Nie wiem, co siê z tym wszystkim sta³o.}

{250} {} {Ach, oto nasz nowy mistrz. (patrzy oceniaj¹co od stóp do g³ów z min¹ konesera) Oczywiœcie ja nie wpuœci³bym ciê na ring, ale Angelo nadal nie ma wyboru. Ciesz siê swoim zwyciêstwem. I wynoœ siê z mojego pokoju.}
{251} {} {Ju¿ mnie nie zobaczysz.}
{252} {} {Prawdopodobnie jesteœ po prostu zazdrosny. Zostañ w swoim gównie, alkoholiku.}
{253} {} {Ach, to nasz nowy mistrz. Widzê, ¿e nasze szkolenie nie posz³o na marne. Mam nadziejê, ¿e nadal bêdziesz u¿ywaæ swoich umiejêtnoœci w celach pokojowych.}
{254} {} {Nie w¹tp w to, Mike. Czeœæ.}
{255} {} {Ach, to nasz nowy mistrz. (patrzy oceniaj¹co od stóp do g³ów z min¹ konesera) Nie rozumiem, dlaczego w ogóle uczestniczysz w bitwach. Ale cieszê siê, ¿e wœród wojowników jest przynajmniej jedna normalna osoba. (podnosi butelkê piwa) Twoje zdrowie.}
{256} {} {Do widzenia.}

{260} {} {Angelo opowiedzia³ mi o twojej tragedii. Porozmawiamy o tym?}
{261} {} {Nie jestem taki, Mike. Nie krzywdzê bez powodu.}
{1261} {} {Nie jestem taka, Mike. Nie krzywdzê bez powodu.}
{262} {} {Pokusa jest wielka. Nie zrozumiesz tego, dopóki nie znajdziesz siê na rozdro¿u. Dobrze zapamiêta³em t¹ lekcjê.}
{263} {} {Coœ siê sta³o?}
{264} {} {Mówisz, jakby coœ nieodwracalnego ju¿ siê wydarzy³o. Powiesz mi co?}
{265} {} {Zap³acê, Mike. Ile mam zap³aciæ za jedn¹ lekcjê?}
{266} {} {Kapsle. Pewnie. Teraz o wszystkim decyduj¹ te grzechotki, które kilka lat temu by³y nic nie warte. Ale nie sprzedajê ju¿ prawa do przemocy, jeœli wiesz, o co mi chodzi.}
{267} {} {Powinienem ci powiedzieæ? (wzdycha) Wiêc pos³uchaj. Kiedyœ przygotowywa³em wszystkich do walki, bezkrytycznie. Nie obchodzi³o mnie to, dopóki regularnie p³acili. I wiedzia³em, ¿e niektórzy z moich uczniów nale¿¹ do ulicznych gangów lub s¹ zaanga¿owani w napady, ale przymyka³em na to oczy... A¿ do tragedii.}
{268} {} {Kontynuuj.}
{269} {} {No tak, jak zwykle, o konsekwencjach myœli siê dopiero w ostatniej chwili.}
{270} {} {PóŸnym wieczorem odprowadza³em moj¹ dziewczynê Sabrinê. Zostaliœmy zaatakowani przez rabusiów. Uda³o mi siê ich obezw³adniæ, ale nie mia³em czasu, aby uratowaæ Sabrinê. W miare postêpu walki rozpozna³em moich uczniów wœród napastników.}
{271} {} {Co siê z nimi sta³o?}
{272} {} {Mam nadziejê, ¿e wysmarowa³es nimi wszystkimi asfalt.}
{273} {} {Po ataku zeszli na dno i robili za wsparcie gangów. Nie mog³em do nich ju¿ podejœæ. Ale bandyci nie ¿yj¹ d³ugo. Teraz ¿yje ju¿ tylko jeden z napastników. Pracuje jako ochroniarz w kasynie. Jeœli go dotknê, ca³a rodzina Don Diego powstanie przeciwko mnie. Wszystko, co mogê zrobiæ, to zapomnieæ o sobie z butelk¹ tequili, któr¹ przygotowuje siê w tym samym kasynie.}
{274} {} {Smutna historia. Teraz rozumiem, dlaczego nie chcesz mnie uczyæ. Do widzenia Mike.}
{275} {} {Pomszczê ciê, Mike. Wymierzê sprawiedliwoœæ.}
{276} {} {Myœlisz, ¿e to mnie pocieszy? Nie. Chcê tylko spojrzeæ temu draniowi w oczy na osobnoœci.}
{277} {} {Wiêc stali siê z³odziejami?}
{278} {} {A co myœla³eœ o nauczaniu tych cycuszków?}
{279} {} {Myœlê, ¿e wiem, co masz na myœli. Czy to z powodu twojej dziewczyny?}
{280} {} {Porozmawiamy o tym ataku?}
{281} {} {Nie chcê o tym rozmawiaæ. Tylko jeden z napastników wci¹¿ ¿yje. Pracuje w kasynie.}
{282} {} {Ok, zapomnij.}
{283} {} {Myœlê, ¿e powinieneœ wiedzieæ, ¿e mia³ „wypadek”. Jesteœ zadowolony?}
{284} {} {W pewnym sensie. Chocia¿ sam nie wiem, co bym zrobi³...}
{285} {} {Na szczêœcie bandyci nie ¿yj¹ d³ugo. I nie zamierzam uzupe³niaæ ich szeregów o nowe si³y. Wystarczy, ¿e zapomnê o sobie z butelk¹ tequili. Pijê i nikomu nie przeszkadzam. Wszystkim siê to podoba.}
{286} {} {To smutna historia, Mike. Teraz rozumiem, dlaczego nie chcesz mnie uczyæ.}
{287} {} {PrzyjdŸ, kiedy zostaniesz œwiêtym i zaczniesz emanowaæ falami dobroci i pokoju. Wtedy nauczê Ciê wszystkiego, co wiem.}
{288} {} {Ok. Udowodniê ci, ¿e mo¿esz mi zaufaæ.}
{289} {} {W¹tpiê, czy mogê zmieniæ to miasto choæby trochê na lepsze. Do widzenia Mike.}
{290} {} {Czy nadal nie zgadzasz siê mnie trenowaæ?}
{291} {} {S³ysza³em, jak wiele dobrego robisz dla ludzi w slumsach. Ale dlaczego? Co ci zale¿y na tych biednych ludziach?}
{292} {} {Po prostu nienawidzê niesprawiedliwoœci.}
{293} {} {S³ysza³em, jak wiele dobrego robisz dla zwyk³ych ludzi tego upad³ego miasta. Ale dlaczego? Dlaczego to robisz?}
{294} {} {Mówi¹, ¿e jesteœ prawdziwym bohaterem, nawet jeœli nie w tym mieœcie. Pomagasz mieszkañcom pustkowi. Ale dlaczego? Dlaczego tego potrzebujesz?}
{1294} {} {Mówi¹, ¿e jesteœ zbawicielem biednych i uciskanych, nawet jeœli nie w tym mieœcie. Pomagasz mieszkañcom pustkowi. Ale dlaczego? Dlaczego tego potrzebujesz?}
{295} {} {Wiesz, lubiê ciê. Nie wiem dlaczego, ale twoja obecnoœæ sprawia, ¿e jestem szczêœliwszy. Nie chcê widzieæ tego co spotka³o Sabrinê.}
{296} {} {Czy teraz mnie nauczysz?}

#Trening
{300} {} {WejdŸ. Ale jeœli coœ mi siê nie spodoba, wylecisz st¹d na ulicê.}
{301} {} {WejdŸ, przyjacielu. Masz wiêcej drinków?}
{1301} {} {WejdŸ kochana. Przynios³aœ wiêcej drinków?}
{302} {} {Usi¹dŸ.}
{303} {} {Nie mam ju¿ nic wiêcej do nauczenia. Trenuj. Wierzê w Ciebie.}
{309} {} {Do zobaczenia Mike.}

{310} {} {Naucz mnie walczyæ, mistrzu.}
{311} {} {Uczyæ kobietê? Tego jeszcze nie robi³em. Mówi¹ jednak, ¿e kobiety bra³y udzia³ w Wielkiej Wojnie. Przynajmniej stare plakaty na to wskazuj¹.}
{312} {} {Dok³adnie.}
{313} {} {Powiedzia³em wczeœniej, ¿e nie zamierzam nikogo szkoliæ.}
{314} {} {Ale dlaczego?}
{315} {} {Mo¿esz okradaæ ludzi na ulicach. Wielu któych uczy³em to robi³o. Nie chcê powtarzaæ tego b³êdu.}
{316} {} {Nie ma sensu siê z tob¹ k³óciæ. Czeœæ, Mike.}
{317} {} {Zap³acê.}
{318} {} {Kapsle. Pewnie. Teraz wszystko zale¿y od kapsli. Ale najpierw, jak zamierzasz wykorzystaæ nabyte umiejêtnoœci? Do samoobrony? Zarabiaæ na ringu? Okay, obiecaj mi, teraz i tutaj... Nie, PRZYSIEGNIJ, ¿e u¿yjesz swoich umiejêtnoœci, aby przynieœæ korzyœci zwyk³ym ludziom.}
{319} {} {Nie mogê z³o¿yæ takiej przysiêgi.}
{320} {} {Wow. Wiedzia³em. OdejdŸ. Nie mamy o czym rozmawiaæ.}
{321} {} {Ok.}
{322} {} {Przysiêgam, Mike. Nie zawiodê Twoich oczekiwañ.}
{323} {} {Kapsle. Pewnie. Teraz wszystko zale¿y od tych œmieci. Ale ja po prostu nie chcê marnowaæ czasu i energii na takiego dupka jak ty. IdŸ st¹d.}
{324} {} {Ok.}
{325} {} {Hmm... nie wiem... Daj mi czas na przemyœlenie. I przynieœ wiêcej drinków.}
{326} {} {Ok.}
{327} {} {Wiêc co zdecydowa³eœ? Bêdziesz mnie szkoliæ?}
{328} {} {Mog³em siê myliæ przez te wszystkie lata... Ok. Ale za ka¿dy trening wezmê 500 kapsli. Gdy bêdzie ciê staæ, przyjdŸ.}
{329} {} {Do zobaczenia Mike.}
{330} {} {Mog³em siê myliæ przez te wszystkie lata... Ok. Przygotuj siê na szkolenie i przyjdŸ jutro rano.}
{331} {} {Na pewno przyjdê, Mike.}

{332} {} {(pogardliwie) Wiedzia³em, ¿e nie mo¿na ci ufaæ. Z³o¿y³eœ przysiêgê, ¿e dobrze wykorzystasz swoje umiejêtnoœci. Teraz nie wierzê w ¿adne s³owo, które wypowiadasz. WyjdŸ i nie wracaj.}
{333} {} {Uch...}
{334} {} {Spadaj, nie chcê ciê widzieæ. Jesteœ dla mnie hañb¹.}
{335} {} {Ok, zapomnij.}

{340} {} {Jestem tutaj, aby nauczyæ siê sztuk walki w zwarciu.}
{341} {} {Brzmi trochê pompatycznie, ale to nie ma znaczenia. Masz 500 kapsli?}
{1341} {} {Brzmi trochê pompatycznie, ale to nie ma znaczenia. Masz 500 kapsli?}
{342} {} {Nie, nie pomyœla³em o tym, przepraszam.}
{1342} {} {Nie, nie pomyœla³am o tym, przepraszam.}
{343} {} {Mogê ciê uczyæ za darmo, ale kiedy p³acisz za trening, doceniasz go znacznie bardziej.}
{344} {} {Tak, oczywiœcie.}
{345} {} {Oto kapsle. Co bêdziemy dzisiaj robiæ?}
{346} {} {Brzmi inspiruj¹co. Mo¿esz zatrzymaæ kapsle dla siebie. Dziœ trenujê Ciê za darmo. Tylko dlatego, ¿e ciê lubiê.}
{347} {} {Super. Co bêdziemy dzisiaj robiæ?}
{348} {} {S³ysza³em plotki, ¿e jesteœ zamieszany w morderstwo niektórych dzieci. Nie wiem, czy to prawda, ale ufam swojemu Ÿród³u. Od dziœ nie jesteœ ju¿ moim uczniem. IdŸ st¹d.}
{1348} {} {S³ysza³em plotki, ¿e bierzesz udzia³ w mordowaniu dzieci. Nie wiem, czy to prawda, ale ufam swojego Ÿród³u. Od dziœ nie chcê ciê widzieæ. WyjdŸ.}
{349} {} {...}

{350} {} {Zacznijmy od podstaw. Prawid³owa postawa, oddech i koncentracja.}
{351} {} {Czas przejœæ do dzia³ania. Poæwiczmy ciosy i chwyty.}
{352} {} {Myœlê, ¿e du¿o siê ju¿ nauczy³eœ. Od tego dnia zaczn¹ siê najtrudniejsze treningi. Bêdziemy pracowaæ nad wytrzyma³oœci¹ i walczyæ z uzbrojonym wrogiem.}
{1352} {} {Myœlê, ¿e du¿o siê ju¿ nauczy³aœ. Od tego dnia zaczn¹ siê najtrudniejsze treningi. Bêdziemy pracowaæ nad wytrzyma³oœci¹ i walczyæ z uzbrojonym wrogiem.}
{353} {} {Wiele ciê nauczy³em. Najwa¿niejsza jednak pozostaje umiejêtnoœæ dbania o siebie. Jest to wa¿ne dla prawid³owej regeneracji si³ i kontroli w krytycznej sytuacji. Pewnego dnia mo¿e Ci to nawet uratowaæ ¿ycie.}
{354} {} {[Rozpocznij trening]}
{355} {} {Oboje jesteœmy zbyt zmêczeni. PrzyjdŸ jutro.}
{356} {} {Ok, mistrzu.}