{102} {} {Uzyskano zezwolenie.}
{103} {} {Tylko cisza odpowiada na twoje znaki wywo³awcze.}
{104} {} {Naciskasz przyciski, ale nic siê nie dzieje. Wygl¹da na to, ¿e ten sprzêt nie dzia³a.}
{105} {} {To nie pomo¿e.}
{106} {} {Nikt nie odpowiada na twoje znaki wywo³awcze.}

{200} {} {Naciskasz przyciski, ale nic siê nie dzieje.}
{201} {} {Hej, czy ktoœ jest w domu?}
{202} {} {Tylko cisza odpowiada na twoje wezwanie.}
{203} {} {WyjdŸ.}
{204} {} {[CZYTAJ: otwórz]}
{205} {} {(S³ychaæ klikniêcie, po chwili drzwi siê otwieraj¹)}
{206} {} {Wygl¹da na to, ¿e siedz¹ tam jacyœ ma³omówni ludzie...}
{207} {} {Jestem wsparciem. Oto moje znaki wywo³awcze.}
{208} {} {Przeor Matthias wys³a³ mnie na pomoc Partii Wyzwolenia.}