{100} {} {Widzisz komputer.}
{101} {} {Widzisz komputer z dostêpem do wspó³dzielonej sieci.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}

{210} {} {Aktywuj system alarmowy i zamknij sterowniê.}
{211} {} {Uwaga! Ca³y personel musi natychmiast opuœciæ sterowniê.}
{212} {} {Wy³¹cz system alarmowy.}
{213} {} {System jest wy³¹czony.}

{220} {} {Wpis z Station Mothballing.}
{221} {} {23 paŸdziernika 2077. Na stacji wprowadzono stan wyj¹tkowy. Aktywowano automatyczne protoko³y ochrony. Rozpoczêto awaryjne wy³¹czenie reaktora.}
{222} {} {Dalej.}
{223} {} {16 sierpnia 2163. Anulowanie stanu wyj¹tkowego na stacji. Protoko³y automatycznej ochrony zosta³y wy³¹czone. Rozpoczêto uruchamianie reaktora.}
{224} {} {Hmm. Te ghule wiedzia³y, co robiæ.}

{230} {} {Umowa z Koœcio³em Swiêtego Ognia.}
{231} {} {Umowa na dostawê ogniw paliwowych do reaktora elektrowni j¹drowej Theodore'a Roosevelta, Phoenix, Arizona, 17 sierpnia 2163.}
{232} {} {Ogólne informacje o stacji.}
{233} {} {..dzone...ane.}
{234} {} {Umowa na czêœci z... Garage City?}
{235} {} {(Jak siê okazuje, Blacharze otrzymali od Wyznawców ognia tê sam¹ czêœæ, któr¹ da³eœ karawanom w Garage City. Zosta³a wys³ana tutaj, aby zast¹piæ star¹, uszkodzon¹.)}
{236} {} {Hej, pamiêtam tê historiê!}