{110} {} {Przechowywana jest tutaj cenna wiedza przedwojenna. Warto to przestudiowaæ.}
{111} {} {Przechowywana jest tutaj cenna wiedza przedwojenna. Ale ju¿ j¹ znasz.}
{112} {} {Przestudiowano ju¿ tê garœæ przedwojennej wiedzy.}
{113} {} {Spêdzasz ca³y dzieñ na eksplorowaniu magazynu przedwojennej wiedzy. Teraz wiele sta³o siê dla Ciebie jaœniejsze.}
{114} {} {Stra¿nik nie pozwoli ci na studiowanie tych ksi¹¿ek bez zezwolenia.}