{100} {} {Widzisz plakat z poszukiwan¹ osob¹.}
{101} {} {Widzisz plakat przedstawiaj¹cy osobê podejrzanie podobn¹ do Ciebie.}
{102} {} {Widzisz plakat z Twoim portretem i napisem: „Poszukiwany za zbrodnie przeciwko Koœcio³owi Swiêtego Ognia”.}
{103} {} {Widzisz plakat ze swoim portretem i podpisem: „Poszukiwany za zbrodnie przeciwko miastu. Nagroda 500 kapsli”}
{104} {} {Widzisz plakat z Twoim portretem i napisem: „Poszukiwany za zbrodnie przeciwko miastu. Nagroda 1000 kapsli”}
{105} {} {Widzisz plakat z Twoim portretem i napisem: „Poszukiwany za zbrodnie przeciwko miastu. Nagroda 2000 kapsli”}
{106} {} {Plakat zosta³ zdarty i zniszczony.}