{100} {} {Widzisz lokalne og³oszenia.}
{101} {} {Widzisz tablicê z og³oszeniami.}
{102} {} {Widzisz tablicê og³oszeñ. Warto przyjrzeæ siê jej bli¿ej.}

{200} {} {(Widzisz ³adnie nabazgran¹ tablicê og³oszeñ)}
{201} {} {WyjdŸ.}
{202} {} {Rozumiem.}
{203} {} {Wstecz.}

{210} {} {Niebezpieczne obszary.}
{211} {} {(Patrzysz na mapê Phoenix, na której zaznaczono najbardziej niebezpieczne obszary. Najwiêksze z nich s¹ oznaczone jako: „Terytorium Orrisa”, „Atomiœci”, „Czerwoni Kardyna³owie”.)}

{220} {} {Uwa¿aj na autostradzie!}
{221} {} {Uwa¿aj na z³odziei z autostrad na trasach 10 i 17. Wiêkszoœæ z nich jest s³abo uzbrojona i nieliczna, ale s¹ te¿ szczególnie niebezpieczne klany. Ci bandyci bez litoœci i ¿alu atakuj¹ podró¿ników i karawany. Nawet nie próbuj z nimi negocjowaæ.}

{230} {} {Gang Los Panchos.}
{231} {} {Uwaga! Poszukiwani s¹ najgroŸniejsi przestêpcy - wodzowie gangu Los Panchos. (ich portrety s¹ do³¹czone) Nagroda w wysokoœci 500 kapsli za ka¿d¹ g³owê.}
{232} {} {Hernando Aviles.}
{233} {} {[przekreœlone] Hernando Aviles.}
{234} {} {By³y ochroniarz. Podczas napadu zabi³ swojego pana i ca³¹ swoj¹ rodzinê. Potem zacz¹³ wêdrowaæ po pustyni, gdzie wst¹pi³ w szeregi gangu Los Panchos. Z natury spokojny i zimnokrwisty. Uwielbia rozmawiaæ ze swoimi ofiarami przed zabiciem.}
{235} {} {Chucho Navarro.}
{236} {} {[przekreœlone] Chucho Navarro.}
{237} {} {Dawniej zwyk³y majsterkowicz. Uciek³ z niewoli przez d³ugi. Znany z tortur. Mentalnie niezrównowa¿ony.}
{238} {} {Adie Gorme.}
{239} {} {[przekreœlone] Adie Gorme.}
{240} {} {By³a piosenkarka. Okrad³a kasyno, w którym pracowa³a. Potem zniknê³a ze swoimi wspólnikami na pustyni, gdzie do³¹czy³a do gangu Los Panchos. Zdobywszy szacunek gangu, ostatecznie awansowa³a do rangi wodza. Znana ze swojego szczególnego okrucieñstwa, niestabilnoœci emocjonalnej i sk³onnoœci do kanibalizmu.}

{250} {} {Poszukiwany - Gil McCord.}
{251} {} {Poszukiwany by³y rewolwerowiec Gil McCord za napaœæ na cz³onków Gildii Najemników. Nagroda 750 kapsli za ¿ywego lub martwego.}
{252} {} {[przekreœlone] Poszukiwany Gil McCord.}

{260} {} {Poszukiwany }
{261} {} { z Villi... Co?}
{262} {} {Poszukiwany za liczne zbrodnie przeciwko mieszkañcom Phoenix. Ka¿dy kontakt z t¹ osob¹ mo¿e kosztowaæ Ciê ¿ycie.}
{263} {} {Poszukiwany za liczne przestêpstwa przeciwko Koœcio³owi Swiêtego Ognia. Ka¿dy kontakt z tym heretykiem mo¿e kosztowaæ ciê reputacjê i zdrowie.}