{110} {} {Awaria sprzêtu.}
{111} {} {Uda³o ci siê wy³¹czyæ nadajnik radiowy. Czciciele ognia zostali pozbawieni ³¹cznoœci radiowej.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Nadajnik radiowy nie odpowiada.}
{204} {} {Stacja radiowa nie dzia³a, poniewa¿ katedra jest pozbawiona zasilania.}

{210} {} {Kopiuj czêstotliwoœci i szyfry. W ten sposób mogê pods³uchiwaæ rozmowy czcicieli ognia przez radio.}
{211} {} {Czêstotliwoœci radiowe skopiowane.}
{212} {} {SprawdŸ historiê zadañ. Zastanawiam siê, czy ktoœ móg³by podzieliæ siê informacjami w celu zorganizowania ataków na mnichów?}
{213} {} {Znajdujesz pozosta³oœci zaszyfrowanej transmisji. Kod dostêpu do terminala nale¿a³ do przeora M..}
{214} {} {Co wiesz, œwiêty?}

{220} {} {Pos³uchaj transmisji radiowej z agentem Czerwonych Kardyna³ów.}
{221} {} {"...Mam informacje dla Aarona. Czerwoni Kardyna³owie s¹ w akcji."}
{222} {} {[Dalej.]}
{223} {} {"SprawdŸ informacje, proszê. Ka¿da najmniejsza rzecz jest dla nas wa¿na."}
{224} {} {[Dalej.]}
{225} {} {"Orris wys³a³ cz³owieka do negocjowania kontraktu zbrojeniowego. Ma tym wzmocniæ swoj¹ pozycjê w slumsach. Powiedzia³em to wczeœniej, ale nie pos³ucha³eœ."}
{226} {} {[Dalej.]}
{227} {} {"Gdzie dojdzie do spotkania?"}
{228} {} {[Dalej.]}
{229} {} {"W kanale w pobli¿u g³ównej bramy miasta. Najprawdopodobniej podejdzie do nich fa³szywy kurier, ale to nie ma znaczenia. Jeœli tego nie zrobimy, musimy zapobiec umowie w ka¿dy mo¿liwy sposób, nie chcê wojny domowej w slumsach. "}
{230} {} {[Dalej.]}
{231} {} {"Potwierdzam. Wysy³amy agenta. Uwa¿aj, Murphy. Orris nie powinien nawet podejrzewaæ, ¿e pracujesz dla nas. Koniec komunikacji."}
{232} {} {Co? Czyli Murphy jest agentem Katedry? Co za niespodzianka...}
{233} {} {Co? To jakieœ ¿arty? Najpierw naukowcy nuklearni, a teraz Murphy. To staje siê norm¹.}

{250} {} {Pos³uchaj transmisji radiowej na temat sabota¿u w elektrowni j¹drowej.}
{251} {} {"...Raport, nasz drogi obserwatorze. Jak przebiega operacja?"}
{252} {} {[Dalej.]}
{253} {} {"Dziêki Atomowi, wszystko posz³o dobrze. Kardyna³owie bezb³êdnie wype³nili swoj¹ czêœæ umowy. Weszli do piwnicy stacji i wysadzili system ch³odzenia, tak jak im kazano. Nie ma niebezpieczeñstwa dla miasta. "}
{254} {} {[Dalej.]}
{255} {} {"Teraz wszystko zale¿y od Ralpha i twoich dyplomatów. Nie przegap okazji, mówi¹, ¿e znaleŸli najemnika, który naprawi system ch³odzenia. Nie s¹dzê, ¿eby by³ w stanie to zrobiæ, ale nie powinien siê w to mieszaæ. "}
{256} {} {[Dalej.]}
{257} {} {"Potwierdzam. Informuj nas na bie¿¹co i niech ogieñ bêdzie z tob¹."}
{258} {} {Co? Ralph sprzeda³ siê na rzecz Koœcio³a? Co za historia...}
{259} {} {Co? To jakieœ ¿arty? Najpierw Murphy, a teraz naukowcy nuklearni. To staje siê norm¹.}
