{100} {} {Widzisz Louisa.}
{101} {} {Widzisz Mieszkañca Krypty 25.}
{102} {} {Cokolwiek powiesz...}
{103} {} {Zrób to, b³agam!}
{104} {} {Jak sobie ¿yczysz, sir...}
{1104} {} {Jak sobie ¿yczysz, madame...}

{200} {} {(Widzisz mê¿czyznê ze skrzynk¹ z narzêdziami. Kiedy ciê widzi, cofa siê z wahaniem i patrz¹c pod nogi, mówi: „Moje uszanowanie”)}
{201} {} {Czekaj, kim jesteœ?}
{202} {} {N-nazywam siê Louis... za twoim pozwoleniem.}
{203} {} {Co tu robisz, Louis?}
{204} {} {Sprawdzam r-rury... za twoj¹ zgod¹.}
{205} {} {Mo¿e przestañ siê powtarzaæ?}
{206} {} {P-przepraszam, panie. Wyjdê natychmiast, sir.}
{1206} {} {P-przepraszam, pani. Wyjdê natychmiast, pani.}
{207} {} {Nie œpiesz siê. Chcê Ciê zapytaæ o coœ.}
{208} {} {Uch, dobrze.}
{209} {} {Pytam, kim jesteœ, a nie jak siê nazywasz.}

{210} {} {Jak mogê pomóc?}
{211} {} {Na razie nic.}
{212} {} {Doœæ o tym.}

{220} {} {Opowiedz mi o sobie.}
{221} {} {(zmieszany) M-mam na imiê Louis... Urodzi³em siê tutaj... i wychowa³em.}
{222} {} {Czy to wszystko?}
{223} {} {P-przepraszam, panie. Naprawia³em tu sprzêt przez ca³e ¿ycie. Nie mam nic wiêcej do powiedzenia o sobie.}
{1223} {} {P-przepraszam, pani. Naprawia³em tu sprzêt przez ca³e ¿ycie. Nie mam nic wiêcej do powiedzenia o sobie.}
{224} {} {Czy kiedykolwiek opuœci³eœ Kryptê?}
{225} {} {Czasami chodzê do katedry... ale nigdy nie by³em w mieœcie.}
{226} {} {Wydajesz siê byæ przywi¹zany do tej Krypty.}
{227} {} {Modlê siê do naszego W³adcy, aby zostawi³ mnie z moim ¿yciem i da³ mi pracê. Chwa³a Panu!}
{228} {} {Wiêc jesteœ tutaj niewolnikiem. Ale mo¿e potrafisz odpowiedzieæ na kilka dodatkowych pytañ.}

{230} {} {Czy chcia³byœ st¹d uciec?}
{231} {} {Nie ma mowy, sir! Bez schronienia zginê. Tak mówi Mistrz, a ja mu wierzê.}
{1231} {} {Nie ma mowy, pani! Bez schronienia zginê. Tak mówi Mistrz, a ja mu wierzê.}
{232} {} {Widzê, ¿e to pytanie bardzo ciê przera¿a.}
{233} {} {Przepraszam pana! By³em tu ca³e ¿ycie... nie wiem, jak siê zachowywaæ na zewn¹trz. Obawiam siê, panie!}
{1233} {} {Przepraszam pani! By³em tu ca³e ¿ycie... nie wiem, jak siê zachowywaæ na zewn¹trz. Obawiam siê, proszê pani!}
{234} {} {Rozumiem. Czy mo¿esz przynajmniej odpowiedzieæ mi na pytania?}
{235} {} {Co tutaj robisz?}
{236} {} {Pokornie s³u¿ê Panu Phoenix i jego Doradcy dla dobra Swiêtego Ognia. Mia³em za zadanie naprawiæ sprzêt, to jest mój œwiêty obowi¹zek.}
{237} {} {Rozumiem.}
{238} {} {Nie jesteœ tu dobrowolnie, prawda?}
{239} {} {(Patrzy w dó³, nie wiedz¹c, co powiedzieæ; wygl¹da na to, ¿e zosta³ powa¿nie pobity przez czcicieli ognia.)}

{240} {} {Opowiedz mi o Krypcie.}
{241} {} {Krypta nr 25, zbudowana przez Vault-Tec, aby chroniæ ludzi przed wojn¹ nuklearn¹ i jej nastêpstwami...}
{242} {} {Czekaj, jak wyl¹dowali tutaj czciciele ognia?}
{243} {} {(z wahaniem) ...Weszli z zewn¹trz i... osiedlili siê tutaj.}
{244} {} {Serio?}
{245} {} {Mo¿esz poznaæ historiê za pomoc¹ sieci komputerowej, to prawda.}
{246} {} {Spróbujê. Na razie opowiedz mi wiêcej o Krypcie.}
{247} {} {Nie rozmawiaj¹ o tym tutaj... Kult przej¹³ Kryptê... A ja zosta³em do naprawy sprzêtu.}
{248} {} {Smutna historia. Porozmawiajmy o czymœ innym.}

{250} {} {Znasz Kryptê jak w³asn¹ kieszeñ, prawda?}
{251} {} {(uœmiechaj¹c siê krzywo) Tak, proszê pana. Znam, proszê pana.}
{1251} {} {(uœmiechaj¹c siê krzywo) Tak, pani. Znam, proszê pani.}
{252} {} {Niektóre drzwi s¹ zamkniête. Czy wiesz, jak je otworzyæ?}
{253} {} {P-Potrzebujesz karty dostêpu. Ka¿dy ma swoj¹, najwy¿szego poziomu chyba dalej ma ochroniarz.}
{254} {} {Czy by³y jakieœ inne Krypty?}
{255} {} {Tak, i du¿o! Wiedz¹ o nich naukowcy w laboratorium.}
{256} {} {Opowiedz mi o dniach, kiedy Krypta by³a wolna.}
{257} {} {Tutaj... by³o œwietnie. Zyliœmy spokojnie i przyjaŸnie. Mieliœmy doœæ jedzenia i energii. Nikt nie wychodzi³ na zewn¹trz. Potem przyszli ludzie z zewn¹trz. U¿yli specjalnego sygna³u, aby otworzyæ pancerne drzwi, a nastêpnie wpadli do œrodka. PóŸniej pojawi³ siê kult Swiêtego Ognia, a to schronienie sta³o siê jego baz¹.}

{260} {} {Przynieœ mi trochê czystej wody.}
{261} {} {(odchodzi i zaraz wraca) Twoja woda, sir.}
{1261} {} {(odchodzi i wkrótce wraca) Twoja woda, pani.}
{262} {} {Teraz skacz na jednej nodze i wynoœ siê st¹d!}
{263} {} {Dziêkujê, uprzejmie.}
{264} {} {Jak sobie ¿yczysz...}
{265} {} {Czy zawsze spe³niasz proœby nieznajomych?}
{266} {} {(patrzy przez chwilê oszo³omionym wzrokiem, ale potem go z powrotem opuszcza)}
{267} {} {Czy zawsze spe³niasz proœby nieznajomych?}
{268} {} {W kryjówce nie ma obcych, tylko Wyznawcy Ognia. A moj¹ swiêt¹ misj¹ jest przydaæ siê im...}
{269} {} {Czy sam o tym zdecydowa³eœ?}
{270} {} {Doradca udziela mi instrukcji.}
{271} {} {Czyli jesteœ pos³uszny W³adcy Phoenix?}
{272} {} {O ile nie zaprzecza s³owom Radcy.}
{273} {} {Twój zwierzchnik nie widzi, porozmawiajmy o czymœ innym.}
{274} {} {Rozumiem. Bywaj.}

{280} {} {Louis... czy chcesz zakoñczyæ to ¿ycie?}
{281} {} {Myœla³em o tym. Z moich bliskich nikogo ju¿ tu nie ma. Nie mogê wyjœæ z Krypty, nawet jeœli drzwi s¹ otwarte. Co mi zosta³o? S³u¿yæ doradcy...}
{282} {} {Ale w g³êbi duszy tego te¿ nie chcesz, prawda?}
{283} {} {Czekaj, ten dialog jest myl¹cy. Wracajmy.}
{284} {} {Có¿, okazuje siê, ¿e jesteœ wielkim przegranym. Z przyjemnoœci¹ tak to zostawiê.}
{285} {} {Jestem bezwartoœciowy... bezwartoœciowy! Ci ludzie nigdy o mnie nie dbali, jestem ich niewolnikiem i zawsze tak bêdzie!}
{286} {} {Czas zakoñczyæ swoje cierpienie. Pomó¿ mi - razem zniszczymy Kryptê.}
{287} {} {Ja... Proszê, pozwól mi zaj¹æ siê moimi sprawami dla dobra Swiêtego Ognia!}
{288} {} {Wiêc zostañ tutaj, frajerze.}
{289} {} {Zniszczyæ? To wszystko... Jak mog³em siê wczeœniej nie domyœliæ!}
{290} {} {Masz pomys³?}
{291} {} {Tam jest bomba atomowa. Jest prawie ukoñczona, naukowcy czekaj¹ tylko na drobne szczegó³y, ale mo¿na ju¿ zacz¹æ i... (j¹ka siê i oblewa go zimny pot)}
{292} {} {I co z tego? Wysadziæ w powietrze? Tego w³aœnie potrzebujemy, Louis. Powiedz mi, jak zacz¹æ.}
{293} {} {Profesor ma potrzebne czêœci w swoim gabinecie, bez nich nie mo¿na zdetonowaæ bomby...}
{294} {} {Potrzebujê karty dostêpu, aby wejœæ do jego biura.}
{295} {} {Tak... Ta karta ma wysoki poziom dostêpu. Bêdê siê modliæ, abyœ odniós³ sukces...}
{296} {} {Dziêkujê Louis, wyœwiadczy³eœ przys³ugê nie tylko mnie, ale ca³ej Sonorze. Teraz muszê iœæ.}
{297} {} {Latwo jest zdobyæ twoje zaufanie, Louis. A teraz powiem o tym doradcy. Pa, idioto.}
{298} {} {Dlaczego kult potrzebuje bomby atomowej?}
{299} {} {Nie wiem, ale po ca³kowitym zmontowaniu mia³a zostaæ przetransportowana na po³udniowy zachód przez pustyniê.}