{100} {} {Widzisz chirurga.}
{101} {} {Widzisz chirurga w poplamionej krwi¹ szacie.}
{102} {} {Jeœli siê nie poœpieszê, ¿adne lekarstwo mi nie pomo¿e...}

# Pierwszy dialog
{200} {} {W czym problem?}
{201} {} {Czy zawsze jesteœ taki niegrzeczny wobec pacjentów?}
{202} {} {(zak³ada rêkawiczki i pociera rêce) Jestem sam i mam wielu pacjentów. Czy jesteœ wyj¹tkowy?}
{1202} {} {(zak³ada rêkawiczki i pociera rêce) Jestem sam i mam wielu pacjentów. Czy jesteœ wyj¹tkowa?}
{203} {} {Nie wiem... Co uczyni mnie wyj¹tkowym?}
{1203} {} {Nie wiem... Co uczyni mnie wyj¹tkow¹?}
{204} {} {Specjalny tytu³ wyznawcy ognia... Albo du¿a liczba kapsli. Wiêc potrzebujesz czegoœ?}
{205} {} {Prawdopodobnie.}
{206} {} {Nie, nic. To z ciekawoœci.}

# Powtarzajacy siê dialog
{210} {} {W czym problem?}
{211} {} {Nic.}

#Leczenie
{220} {} {Potrzebujê leczenia.}
{221} {} {Zobaczmy. Co bêdziemy leczyæ?}
{222} {} {Kontuzjowany.}
{223} {} {Kontuzja.}
{224} {} {Napromieniowanie.}
{225} {} {Zatrucie.}
{226} {} {ChodŸ, przejdzie samo.}
{227} {} {Typowy przypadek. Wyleczê ciê. Ale poniewa¿ nie jesteœ jednym z Obserwatorów, bêdziesz musia³ przekazaæ darowiznê - }
{228} {} { kapsli.}
{229} {} {Oto kapsle.}
{230} {} {Typowy przypadek. Wyleczy siê.}
{231} {} {Przepraszam. W takim razie nie mogê Ci pomóc.}
{232} {} {Jak to...}
{233} {} {Nie ma potrzeby, zagoi siê samo.}
{234} {} {Chwalcie Swiêty Ogieñ. A teraz wynoœ siê z gabinetu, w kolejce s¹ inni pacjenci.}
{235} {} {To nie wszystko, doktorze.}
{236} {} {Zrób to, doktorze.}
{237} {} {Bardzo bym chcia³.}

{240} {} {Czy widzia³eœ jakichœ ch³opów z Villi?}
{241} {} {Hmm, jeden z niewolników wspomnia³ o Villi podczas egzaminu.}
{242} {} {Co siê z nim sta³o?}
{243} {} {Nie wiem. Raporty o dostawach niewolników s¹ przechowywane w katedrze. Ja zajmujê siê wy³¹cznie przeprowadzaniem badañ lekarskich.}
{244} {} {Rozumiem.}
