{102} {} {W tych warunkach potajemna kradzie¿ jest po prostu niemo¿liwa.}
{103} {} {Nie... nie mo¿emy... zostaæ zatrzymani...}
{104} {} {}
{105} {} {Wynoœ siê!}

# Pierwszy dialog
{200} {} {Imponuj¹ce. Uda³o ci siê zakraœæ do schronu bez wszczynania alarmu, min¹æ stra¿ników i dostaæ siê do samego centrum dowodzenia. Takie umiejêtnoœci szpiegowskie s¹ niezwykle rzadkie. Wiêc dlaczego tu jesteœ?}
{201} {} {Imponuj¹ce. Nawet podnosz¹c alarm w ca³ej Krypcie, uda³o ci siê dostaæ do samego centrum dowodzenia. Niewielu jest do tego zdolnych. Czego chcesz?}
{202} {} {Hmm. Obcy w kryjówce zawsze budzi podejrzenia. Dlaczego tu jesteœ?}
{203} {} {Aaron mnie przys³a³. Chcê s³u¿yæ Swiêtemu Ogniu.}
{204} {} {Jestem tu w jednym celu - ¿eby ciê zabiæ.}
{205} {} {W takim razie nie traæmy czasu...}
{206} {} {Umrzyj za wolnoœæ Villi!}
{207} {} {Nie odpowiem, dopóki nie dowiem siê z kim rozmawiam.}
{208} {} {NajwyraŸniej nie rozumiesz dobrze swojego po³o¿enia. Nazywam siê Ulysses Grant i jestem pierwszym doradc¹ Lorda Phoenix Aarona. To powinno ci wystarczyæ.}
{209} {} {Jesteœ dok³adnie tym, kogo szukam. D¹¿ê do zakoñczenia pewnego problemu.}

# Pierwszy dialog, jeœli GG jest ch³opem
{210} {} {Szukam moich wspó³plemieñców. Mówi¹, ¿e Wyznawcy Ognia ich zniewolili.}
{211} {} {Villa... Pamiêtam. Jedna z prymitywnych wiosek na pó³nocnym zachodzie. Stamt¹d niewolnicy zostali przetransportowani do Tu-San i teraz stan¹ siê paliwem dla maszyny postêpu. To zaszczyt, nawet jeœli ci siê to nie podoba.}
{212} {} {Dlaczego potrzebujesz niewolników?}
{213} {} {Och, jest wiele powodów - odbudowa infrastruktury, praca w kopalniach, transport miêdzy miastami i wiele wiêcej, co by³oby znacznie trudniejsze dla niezale¿nych najemników. Rozwój cywilizacji wymaga du¿ych zasobów ludzi i pracy. Niewolnictwo to najbardziej wydatny sposób na ich zdobycie.}
{214} {} {Jak mo¿esz zniewalaæ niewinnych ludzi?}
{215} {} {Wiêkszoœæ miejscowej ludnoœci zajmuje siê przetrwaniem i nie przyczynia siê w ¿aden sposób do rozwoju regionu. Wrêcz przeciwnie, s¹ gotowi do wrogoœci i nie s¹ gotowi do wspó³pracy. Plemiona takie jak twoja Villa ¿yj¹ z zawê¿onego egoizmu. Przekszta³cenie potêgi tych dzikusów na korzyœæ ca³ego regionu jest godnym celem wartym poœwiêcenia etycznej strony sprawy.}
{216} {} {O jakim postêpie mówisz?}
{217} {} {Masz za sob¹ d³ug¹ drogê, prawda? Dzisiejszy krajobraz to ja³owe pustkowiê lub ruiny staro¿ytnych miast, ¿ycie w takich warunkach jest trudne i niebezpieczne. Ale s¹ miejsca, w których cywilizacja powraca. Pr¹d, medycyna, edukacja - to wszystko dziêki nam wróci³o do krainy Sonory. W porównaniu z tym drobne codzienne zmartwienia Villi to nic innego jak zamieszanie zwi¹zane z myszami.}
{218} {} {Co dalej - zamierzasz zniewoliæ ca³¹ Sonorê?}
{219} {} {To by³oby zbyt marnotrawne. Znacznie ³atwiej jest stworzyæ wygodne do ¿ycia centra cywilizacji. Same te kolonie bêd¹ przyk³adem - modelem, do którego d¹¿yæ bêdzie reszta dzikich.}
{220} {} {Villa nie potrzebowa³a twojej „cywilizacji”. W spo³ecznoœci mieliœmy du¿o jedzenia i porz¹dku.}
{221} {} {Mylisz siê. Twoja spo³ecznoœæ prze¿ywa ostatnie pokolenia. Wyczerpanie siê p³odnoœci, nagromadzenie mutacji, wysoka œmiertelnoœæ, niepewnoœæ ze strony zewnêtrznych wrogów i zwyk³e ograniczenie umys³u - wszystko to ogranicza twoj¹ spo³ecznoœæ i prowadzi do nieuchronnej œmierci. Nie wierzysz? To uwierz. Widzieliœmy ca³e osady oszala³e tylko dlatego, ¿e zepsu³a im siê jedyna pompa wodna.}
{222} {} {Co oferuje twój kult?}
{223} {} {Oczywiœcie powrót do cywilizacji. Wiele ju¿ osi¹gnêliœmy.}
{224} {} {Bzdury. Po prostu paso¿ytujesz na innych ludziach.}
{225} {} {Brzmi rozs¹dnie. Sonora najwyraŸniej nie ma silnej rêki, by zjednoczyæ upad³¹ populacjê.}
{226} {} {Przykro nam, ¿e nie doceniasz naszych pomys³ów. Jednak to nic nowego. Jesteœ zwyk³¹ przeszkod¹ w naszych planach. Bêdziemy musieli ciê wyeliminowaæ...}
{227} {} {Czekaj, nie...}
{228} {} {Aby to zrobiæ, musisz porzuciæ przesz³oœæ - zrezygnowaæ z przes¹dów, tradycji, a nawet wiêzów rodzinnych. Czy jesteœ na to gotowy?}
{1228} {} {Aby to zrobiæ, musisz porzuciæ przesz³oœæ - zrezygnowaæ z przes¹dów, tradycji, a nawet wiêzów rodzinnych. Czy jesteœ na to gotowa?}
{229} {} {Ca³kowicie. Chcê, ¿eby Villa wkroczy³a na œcie¿kê postêpu i cywilizacji.}
{230} {} {Oferujesz niemo¿liwe. IdŸ do diab³a!}
{231} {} {W takim razie udowodnij swoje zamiary - zostañ czêœci¹ kultu Swiêtego Ognia. W ten sposób dasz przyk³ad swoim wspó³plemieñcom.}
{232} {} {Zostaæ Obserwatorem? Najpierw muszê porozmawiaæ z Aaronem. Co dalej?}
{233} {} {Villa musi byæ nasz¹ now¹ koloni¹, inaczej czas zetrze j¹ z powierzchni ziemi. Spróbuj to wyt³umaczyæ pozosta³ym ch³opom. A jeœli ci siê uda, dam wolnoœæ wszystkim niewolnikom z Villi.}
{234} {} {Zgoda.}
{235} {} {Oferujesz niemo¿liwe. IdŸ do diab³a!}
{236} {} {Porozmawiaj z Aaronem. Udzieli dalszych instrukcji.}
{237} {} {Ok.}
{238} {} {To nie do pomyœlenia. Takich jak Ty trzeba pilnie zniszczyæ!}
{239} {} {Po prostu tuszujesz zwyk³e z³o ³adnymi s³owami. Nie zmylisz mnie.}

# Pierwszy dialog, jeœli GG zostanie cz³onkiem BS
{240} {} {Mi³o ciê poznaæ, bracie. Agenci Bractwa przekazali mi ju¿ informacje o Tobie i Twojej s³u¿bie. Sztab generalny uwa¿a, ¿e jesteœ obiecuj¹cy, ale moi agenci maj¹ nieco inne zdanie.}
{1240} {} {Mi³o ciê poznaæ, siostro. Agenci Bractwa przekazali mi ju¿ informacje o Tobie i Twojej s³u¿bie. Sztab generalny uwa¿a, ¿e jesteœ obiecuj¹ca, ale moi agenci maj¹ nieco inne zdanie.}
{241} {} {Mi³o ciê poznaæ, bracie. Agenci Bractwa przekazali mi ju¿ informacje o Tobie i Twojej s³u¿bie. Muszê powiedzieæ, ¿e jesteœ bardzo obiecuj¹cy.}
{1241} {} {Mi³o ciê poznaæ, siostro. Agenci Bractwa przekazali mi ju¿ informacje o Tobie i Twojej s³u¿bie. Muszê powiedzieæ, ¿e jesteœ bardzo obiecuj¹ca.}
{242} {} {Ty tak¿e jesteœ cz³onkiem Bractwa Stali?}
{243} {} {Paladyn Ulysses Grant. Ale w katedrze nazywam siê Doradc¹. Staram siê pozostaæ incognito w tym mieœcie.}
{244} {} {Co paladyn Bractwa robi w sercu obcego kultu?}
{245} {} {W³aœciwie to prowadzê ten kult, chocia¿ niewiele osób o tym wie. Faktem jest, ¿e Koœció³ Swiêtego Ognia zosta³ zorganizowany przez Bractwo Stali kilka lat temu. Potem by³ czas k³opotów w Phoenix, pomogliœmy jednemu z klanów przej¹æ w³adzê nad miastem, a nastêpnie umieœciliœmy ludzi, których potrzebowaliœmy na jego czele. Nadal zarz¹dzam t¹ elit¹ ze wzglêdu na interesy Bractwa.}
{246} {} {Innymi s³owy, Aaron i inni kultyœci s¹ tylko marionetkami w rêkach Bractwa?}
{247} {} {Tak. Bractwo potrzebuje ró¿norodnych zasobów i w³adzy nad regionem. Ale jest nas za ma³o, by samodzielnie kontrolowaæ sytuacjê. Idealnym rozwi¹zaniem by³ pomys³ rewolucji i stworzenie kultu pomocniczego. Teraz mo¿emy wydawaæ tylko polecenia, a prawdziw¹ pracê wykonuj¹ osoby przed nami odpowiedzialne.}
{248} {} {To bardzo wygodne. A co z niewolnictwem, które widziano w kulcie?}
{249} {} {Starsi zakonu nie lubi¹ niewolnictwa. Ale w tej chwili jest to nieunikniona ofiara na rzecz rozwoju regionu. Zajmie nam kilka pokoleñ, zanim bêdziemy mogli zaprzestaæ pracy przymusowej. Niestety, lokalni dzicy nie s¹ jeszcze gotowi do podjêcia samodzielnego kroku w kierunku postêpu.}
{250} {} {A co z Vill¹?}
{251} {} {O tak, Villa... Jedna z prymitywnych wiosek na pó³nocnym zachodzie. Raport mówi, ¿e jesteœ stamt¹d. Przepraszam, ¿e sta³o siê jak siê sta³o. W ka¿dym razie twoi wspó³plemieñcy stali siê paliwem dla machiny postêpu i jest to wielki zaszczyt. Jako cz³onek Bractwa Stali powinieneœ to zrozumieæ i zaakceptowaæ.}
{252} {} {Czy Villê mo¿na uwolniæ z niewoli?}
{253} {} {Oczywiœcie. Ale Villa musi staæ siê jedn¹ z naszych kolonii. Niestety, mam teraz zbyt wiele do zrobienia, aby poradziæ sobie z tym problemem. Musisz mi pomóc. Porozmawiaj z Aaronem, aby uzyskaæ dalsze wskazówki.}
{254} {} {Ok, porozmawiam z nim.}
{255} {} {Oczywiœcie. Ale Villa musi staæ siê jedn¹ z naszych kolonii. To zadanie zajmie trochê czasu.}
{256} {} {W takim razie porozmawiamy o tym trochê póŸniej.}
{257} {} {Mi³o ciê poznaæ, bracie. Agenci Bractwa przekazali mi ju¿ informacje o Tobie i Twojej s³u¿bie. Muszê powiedzieæ, ¿e jesteœ obiecuj¹cy. Jednak podniesienie alarmu po drodze tutaj by³o bardzo niem¹dre.}
{1257} {} {Mi³o ciê poznaæ, siostro. Agenci Bractwa przekazali mi ju¿ informacje o Tobie i Twojej s³u¿bie. Muszê powiedzieæ, ¿e jesteœ obiecuj¹ca. Jednak podniesienie alarmu po drodze tutaj by³o bardzo niem¹dre.}
{258} {} {}
{259} {} {Bractwo poinformowa³o mnie o twoim awansie. Mi³o ciê widzieæ, bracie.}
{1259} {} {Bractwo poinformowa³o mnie o twoim awansie. Mi³o ciê widzieæ, siostro.}

# Po zniszczeniu Puerto
{260} {} {Wiedzia³em, ¿e przyjdziesz... dzikusie! Nawet po zniszczeniu naszej bazy w Puerto nie mo¿esz powstrzymaæ pragnienia zemsty? Taki jest problem wszystkich lokalnych plemion - trzymasz siê przesz³oœci, chocia¿ przed tob¹ ukazuje siê œwietlana przysz³oœæ. Musisz tylko zaakceptowaæ postêp i porzuciæ stare uprzedzenia. Ale nie, to dla ciebie za trudne!}
{261} {} {Innymi s³owy, Bractwo upad³o na ziemiach Sonory. Skorzystaj z tego, kretynie.}
{262} {} {To tylko ucieczka od nieuniknionego. Starsi w Kalifornii prêdzej czy póŸniej otworz¹ nowy fort w Sonorze. Do tego czasu bêdê mia³ czas na przygotowanie Phoenix. To dopiero pocz¹tek.}
{263} {} {Hej, po co ci te karabiny maszynowe... czekaj, nie zamierzasz chyba...}
{264} {} {Mylisz siê. Bractwo upad³o z powodu b³êdów w ideologii, a nie z powodu zacofania regionu.}
{265} {} {Bzdury!}
{266} {} {Wcale nie. Narzuciliœcie ludnoœci ideê, których nie byli gotowi zaakceptowaæ. Wiêc dostaliœcie odrzucenie.}
{267} {} {Próbowaliœmy ciê zmieniæ, uczyniæ lepszym! I zamiast wdziêcznoœci otrzymaliœmy nó¿ w plecy. Zobacz, ile Bractwo dla Ciebie zrobi³o - elektrycznoœæ, edukacja, ekonomia. Czy to wszystko nic nie znaczy?}
{268} {} {Nie, nie próbowa³eœ nas ulepszyæ. Próbowa³eœ uczyniæ nas swoimi poddanymi. Jesteœmy dla Ciebie drugorzêdni. I zawsze bêdziemy tacy.}
{269} {} {Mo¿e tak. Ale pokojowe œrodki nie zadzia³a³y. Wszystko, co mogliœmy zrobiæ, to narzuciæ nasze pomys³y si³¹.}
{270} {} {Ale kto zdecydowa³, ¿e twój pomys³ na œwiat jest poprawny? Poniewa¿ pochodz¹ z okresu przedwojennego? Wiesz jak ta historia siê skoñczy³a.}
{271} {} {Wojna... wojna nigdy siê nie zmienia. Chcieliœmy przywróciæ tym ziemiom dawn¹ œwietnoœæ.}
{272} {} {W rezultacie staliœcie siê zwyk³ymi najeŸdŸcami.}
{273} {} {Wystarczy! Wracaj do siebie, dzikusie. Te ziemie nie s¹ warte naszej uwagi...}
{274} {} {Hmm...}
{275} {} {Wygl¹da na to, ¿e nie mogê ciê przekonaæ.}

# Powtarzajacy siê dialog
{300} {} {Raport.}
{301} {} {Nie mam jeszcze nic do zg³oszenia. Có¿, pójdê ju¿.}
{302} {} {Czy mogê uzyskaæ swobodny dostêp do Krypty?}
{303} {} {Nie widzê potrzeby.}
{304} {} {Cz³onkowie Bractwa Stali musz¹ sobie ufaæ.}
{305} {} {Jako cz³onek Koœcio³a Swiêtego Ognia przysiêgam byæ ostro¿ny.}
{306} {} {Trudno jest wykonaæ misjê bez podstawowego wsparcia.}
{307} {} {Ok, zrobiê to.}
{308} {} {To rozs¹dne. Oto karta magnetyczna. Dajê ci œredni poziom uprawnieñ, to ci wystarczy.}
{309} {} {Lepsze to ni¿ nic.}
{310} {} {Nie mogê jeszcze daæ ci pozwolenia.}
{311} {} {Dziêki.}

#Zapytania
{320} {} {Czy mogê o coœ zapytaæ?}
{321} {} {O co chodzi?}
{322} {} {Myœlê, ¿e pójdê ju¿. Za twoj¹ zgod¹, doradco.}
{323} {} {Czy mogê zadaæ jeszcze jedno pytanie?}
{324} {} {Czy mo¿emy porozmawiaæ o Koœciele Swiêtego Ognia?}
{325} {} {Kult, który inspiruje postêp i wiedzê.}
{326} {} {Czy ten kult jest równie¿ stworzony przez Bractwo Stali?}
{327} {} {W pewnym sensie. Szczerze mówi¹c, skorzystaliœmy z doœwiadczenia innego kultu, który niedawno dzia³a³ w Kalifornii. Okaza³o siê, ¿e to dobry pomys³.}
{328} {} {Co to za kryjówka?}
{329} {} {Przed Wielk¹ Wojn¹ podobne schrony budowano w ca³ych Stanach Zjednoczonych. Mia³y one chroniæ ludnoœæ przed atakami nuklearnymi i ich konsekwencjami. Ta kryjówka, a dok³adniej Krypta zosta³a oznaczona numerem 25.}
{330} {} {Co wiesz o Wielkiej Wojnie?}
{331} {} {Wiele krajów eksterminowa³o siê nawzajem za garœæ zasobów naturalnych i dominacjê nad œwiatem. Pisma mówi¹, ¿e wojny nigdy nie mia³y tak niszczycielskich konsekwencji na tak wielk¹ skalê.}
{332} {} {Co s¹dzisz o Aaronie?}
{333} {} {Nie bêdê z tob¹ rozmawiaæ o tej osobie.}
{334} {} {Doœæ niezawodna lalka z dominuj¹cymi ambicjami i niedorozwiniêtym umys³em. Dok³adnie ktoœ taki kogo potrzebujemy.}
{335} {} {Któregoœ dnia oprze siê swojej pozycji.}
{336} {} {Bez wsparcia Bractwa ten cz³owiek ma niewielkie szanse na zdobycie przyczó³ka w regionie. Na szczêœcie dobrze to rozumie.}
{337} {} {A mo¿e inne pytanie?}
{338} {} {Dlaczego potrzebujesz bomby atomowej?}
{339} {} {Nie bêdê z tob¹ o tym rozmawiaæ.}
{340} {} {Bractwo Stali ma wiele powodów, by trzymaæ tak¹ broñ w swoich rêkach. Zw³aszcza po ostatnich wydarzeniach w Kalifornii. Jednak nic ci nie powiem.}
{341} {} {Czy mo¿emy porozmawiaæ o Bractwie Stali?}
{342} {} {Bractwo Stali to organizacja, która we wszystkim przewy¿sza miejscowych... We wszystkim oprócz liczebnoœci.}
{343} {} {Jak to jest, ¿e Bractwo prowadzi kult?}
{344} {} {Bractwo potrzebuje kontroli nad okolicznymi ziemiami. Nie mo¿emy tego zapewniæ samodzielnie. Dlatego postanowiono ustanowiæ marionetkow¹ moc w Phoenix i za jej poœrednictwem rz¹dziæ regionem. Stworzyliœmy ten kult i pod jego sztandarem dokonaliœmy rewolucji.}
{345} {} {Jakie plany ma Bractwo w tym regionie?}
{346} {} {Zbieramy przedwojenne technologie i niektóre zasoby. G³ówny sztab generalny w Kalifornii potrzebuje paliwa j¹drowego. Potrzebujemy si³y roboczej do zabezpieczenia dostaw. A do tego - mocy w ca³ej Arizonie. Ustanowienie, wzmocnienie i rozszerzenie tej mocy jest naszym bezpoœrednim zadaniem.}

{350} {} {Bêdê przez chwilê w Phoenix. Mo¿e jest dla mnie zadanie w tym mieœcie?}
{351} {} {Nie. JedŸ do Puerto, teraz nie ma dla ciebie nic wa¿niejszego.}
{352} {} {Zadanie jest jasne.}
{353} {} {Chyba tak. Po powrocie do Phoenix George Crook zacz¹³ stwarzaæ problemy. Stary ¿o³nierz za du¿o mówi i za du¿o ¿¹da. Musisz go uciszyæ.}
{354} {} {Jaki jest haczyk?}
{355} {} {Crook i Aaron to starzy przyjaciele. Nie chcê, ¿eby Aaron wiedzia³, kto nakaza³ to morderstwo. Crook nie wychodzi z kasyna, wiêc musisz go wyeliminowaæ po cichu.}
{356} {} {Jak wiêc mogê pozostaæ tam niezauwa¿ony?}
{357} {} {Pomyœl. Zap³acê 500 kapsli za zabicie dowódcy.}
{358} {} {Ok. Zajmê siê t¹ spraw¹. Opowiem ci o wyniku.}
{359} {} {Zbyt ryzykowne. Lepiej zajmij siê holodyskiem.}
{360} {} {Crook mia³ „wypadek”.}
{361} {} {S³ysza³em ju¿ plotki. Dobra robota.}
{362} {} {Mi³o pomóc.}
{1362} {} {Mi³o pomóc.}
{363} {} {Oto twoja zap³ata. Nie próbuj nikomu mówiæ o naszej umowie. I tak nikt ci nie uwierzy.}
{364} {} {Tylko jedno pytanie - po co zabijaæ Crooka? Czy nie s³u¿y³ chwale imperium?}
{365} {} {Zrozumiano, sir. Mogê iœæ?}
{1365} {} {Rozumiem, sir. Mogê iœæ?}
{366} {} {S¹ ku temu dwa powody. Po pierwsze, Komandor Crook by³ ¿o³nierzem, teraz bêdzie tylko ciê¿arem. Imperium nie ma ju¿ silnych wrogów, a stare wilki bojowe nie lubi¹ siedzieæ bezczynnie.}
{367} {} {A co z drugim powodem?}
{368} {} {Aaron zas³uguje na ma³¹ karê. Dziêki swoim niedawnym zwyciêstwom zacz¹³ za du¿o o sobie myœleæ, zacz¹³ du¿o wymagaæ. Musimy mu przypomnieæ, gdzie zacz¹³ i kto tu jest prawdziwym szefem.}
{369} {} {Rozumiem.}
{370} {} {Dla ciebie, rekrutcie, to niczego nie zmienia. Znasz swoje zadanie - czekaj¹ na Ciebie w Puerto. Udaj siê tam.}
{371} {} {Mam zaszczyt.}

# Twoje zadanie
{400} {} {Uda³o ci siê przechytrzyæ Aarona i zdobyæ jego zaufanie. Ale ze mn¹ ci siê nie uda. Po ca³ej tej historii w Villi powinieneœ mieæ zupe³nie inne ambicje.}
{401} {} {Co... jak siê masz...}
{402} {} {Wiem wszystko, co dzieje siê w tym mieœcie. Wszêdzie mam oczy i uszy. Oczywiœcie raporty o Villi tak¿e tu dotar³y. Wiêc co próbujesz osi¹gn¹æ dziêki tej ca³ej konspiracji?}
{403} {} {Chcê tylko wolnoœci dla moich ludzi.}
{404} {} {Godny cel dla kogoœ, kto nic nie wie o wolnoœci. Jak powiedzieli staro¿ytni, wolnoœæ ma swoj¹ cenê. Twoi mali ludzie nie s¹ w stanie przetrwaæ, nie mówi¹c ju¿ o zachowaniu wolnoœci na tym œwiecie. Jedynym wyjœciem jest przy³¹czenie siê do postêpu i stanie siê czêœci¹ tego œwiata.}
{405} {} {Wiêc... mamy zostaæ koloni¹?}
{406} {} {Po tak d³ugiej podró¿y zdajê sobie sprawê, ¿e Villa musi siê zmieniæ.}
{407} {} {Hmm, ciekawe. W takim razie jedynym wyjœciem dla twojego ludu jest zostanie nasz¹ koloni¹.}
{408} {} {Koloni¹?}
{409} {} {Dok³adnie. Czêœciowo stracisz niezale¿noœæ, ale w zamian otrzymasz korzystn¹ wymianê wiedzy, technologii i produktów. Wszyscy bêd¹ na plusie, ale jest jeden problem - wasze spo³eczeñstwo musi siê zmieniæ. Musisz wyjaœniæ swoim wspó³plemieñcom potrzebê zniszczenia przestarza³ych tradycji i przejœcia na nowy styl ¿ycia.}
{410} {} {To nie bêdzie ³atwe. Ale zrobiê wszystko, co trzeba. Bêd¹ mnie s³uchaæ.}
{411} {} {Ok. W takim wypadku bêdziesz musia³ odbyæ ma³¹ i niebezpieczn¹ podró¿. WeŸ ten holodysk z wa¿nym raportem. Musi zostaæ zabrany do bazy wojskowej w Porcie. Najbezpieczniejszym sposobem dotarcia do celu s¹ karawany.}
{412} {} {A co ze zniewolonymi ch³opami?}
{413} {} {Nie musisz siê tym martwiæ, wydam rozkazy, aby zapewniæ im bezpieczeñstwo. Ale kwestia kolonizacji musi zostaæ rozstrzygniêta przez Sztab Generalny. Udaj siê do Puerto Penasco i poka¿ mój raport g³ównemu dowódcy.}
{414} {} {Wychodzê.}
{415} {} {Wykona³em zadania Aarona. Teraz proszê, aby ch³opi Villi zostali uwolnieni z niewoli.}
{1415} {} {Wykona³am zadania Aarona. Teraz proszê, aby ch³opi Villi zostali uwolnieni z niewoli.}
{416} {} {Twoje mêstwo uderza w ludzi takich jak Aaron. Ale ja mam wiêcej informacji. Czego naprawdê chcesz dla swoich ma³ych i dumnych ludzi?}
{417} {} {Do jakiej bazy nale¿y zabraæ ten holodysk?}
{418} {} {Bazy wojskowej w porcie Puerto Penasco nad brzegiem Zatoki Kalifornijskiej. Niewielu wie o tym miejscu. Po dotarciu na miejsce dowiesz siê wszystkiego od razu.}
{419} {} {Rozumiem. Czy mogê zadaæ inne pytania?}
{420} {} {Pójdê tam natychmiast.}
{421} {} {Móg³byœ mi wyjaœniæ to trochê bardziej. Okay, pójdê i zobaczê.}
{422} {} {Co jest na holodysku?}
{423} {} {Tajny raport dla Sztabu Generalnego, miêdzy innymi dotyczy sytuacji Villi. Nie pokazuj nikomu dysku i nie próbuj go czytaæ, i tak jest zaszyfrowany.}
{424} {} {Wygl¹da na to, ¿e odkry³eœ mój plan. Bêdê musia³ ciê wykoñczyæ!}
{425} {} {Wystarczy! To siê nigdy nie wydarzy. Jesteœcie tylko rabusiami i szanta¿ystami.}
{426} {} {Co za... Wygl¹da na to, ¿e ju¿ siê nam nie przydasz.}
{1426} {} {Co za... Wygl¹da na to, ¿e ju¿ siê nam nie przydasz.}
{427} {} {Hej, czy to broñ?}