{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz jednego ze stra¿ników. Wygl¹da na nie do odró¿nienia od reszty stra¿ników.}

{104} {} {Ktoœ podniós³ alarm. Wygl¹da na to, ¿e bêdê musia³ ciê zatrzymaæ...}
{105} {} {Ju¿ wychodzisz? Dobrze.}
{106} {} {Staæ! Kto idzie?}
{107} {} {Intruz! Podnieœæ alarm!}
{108} {} {Stop! Kto tam... Ugh, myœlê, ¿e widzia³em ducha.}

{200} {} {Stop! Podaj swoje imiê i cel wizyty.}
{201} {} {Przepraszam bracie, jestem tu od niedawna i chcia³em siê tylko rozejrzeæ.}
{1201} {} {Przepraszam bracie, jestem tu od niedawna i chcia³am siê tylko rozejrzeæ.}
{202} {} {Przepraszam bracie, jestem nowy i chcê siê tylko rozejrzeæ.}
{203} {} {Sk¹d te pytania, bracie? Czy moja sutanna nie budzi twojego zaufania?}
{204} {} {Uch, lepiej siê st¹d wyniosê...}
{205} {} {Powiedz szefowi, ¿e mam dla niego informacje.}
{206} {} {Idê do Ulyssesa Granta. Przys³a³ mnie sam Aaron.}
{207} {} {Pozwólcie, ¿e wyra¿ê mój najg³êbszy szacunek, doradco. ZejdŸ na ni¿szy poziom, Ulisses jest u siebie.}

{210} {} {Intruz! Podnieœæ alarm!}
{211} {} {Cholera, muszê ciê zlikwidowaæ!}
{212} {} {Ale ja nic nie zrobi³em!}
{213} {} {W porz¹dku, wejdŸ, bracie.}
{1213} {} {Ok, wejdŸ siostro.}
{214} {} {Chwalcie Swiêty Ogieñ, bracie.}
{215} {} {Dziêkujê... bracie.}

{220} {} {Ju¿ odchodzisz?}
{221} {} {Tak, do zobaczenia.}
{222} {} {WejdŸ. Sam znajdziesz drogê.}
{223} {} {Ok.}
{224} {} {Idê do doradcy. Wys³a³ mnie Jego Swiêtobliwoœæ Aaron, Pan Phoenix.}