{100} {} {Widzisz profesora Zimmera.}
{101} {} {Widzisz lidera grupy badawczej. Dziwnie wygl¹da.}
{102} {} {Teraz nie czas na naukowe kontrowersje...}

# Pierwszy dialog
{200} {} {(przed sob¹ widzisz naukowca w fartuchu laboratoryjnym z szalonym wygl¹dem i rozczochranymi w³osami; mówi, nie podnosz¹c wzroku znad tabletu) Jestem zajêty, wynoœ siê.}
{201} {} {Jestem tu od niedawna, czy mogê zadaæ kilka pytañ?}
{202} {} {Jak œmiesz tak do mnie mówiæ?!}
{203} {} {Przepraszam, ¿e przeszkadzam.}

{207} {} {To w³aœnie próbujê wyjaœniæ - jestem tutaj nowy i...}
{208} {} {Ochrona! Mamy outsidera!}
{209} {} {Nie powinienem by³ tego robiæ...}

{210} {} {(zirytowany) Powiedzia³em, ¿e nie mam czasu dla wszystkich... Przestañ. Kim ty jesteœ?}
{1210} {} {(zirytowany) Mówi³em ci, ¿e nie mam czasu dla wszystkich... Przestañ. Kim ty jesteœ?}

{211} {} {Jestem Obserwatorem.}
{212} {} {Wystarczy. (stopniowo podnosi g³os) I myœlisz, ¿e mo¿esz w³amaæ siê do laboratorium i odci¹gn¹æ MNIE od pracy?! (znów podnosi g³os) Wyjaœnijmy sobie coœ, praca tego laboratorium to przede wszystkim nie twoja sprawa w tej katedrze! I bez wzglêdu na to, jaki wysoki tytu³ posiadasz w swojej „sekcie”, tutaj nie ma to znaczenia! Rozumiesz to? Teraz zniknij.}
{1212} {} {Wystarczy. (stopniowo podnosi g³os) I myœlisz, ¿e mo¿esz w³amaæ siê do laboratorium i odci¹gn¹æ MNIE od pracy?! (znowu podnosi g³os) Wyjaœnijmy sobie coœ, praca tego laboratorium to przede wszystkim nie twoja sprawa w tej katedrze! I bez wzglêdu na to, jaki wysoki tytu³ posiadasz w swojej „sekcie”, tutaj nie ma to znaczenia! Rozumiesz to? Teraz zniknij.}
{213} {} {Rozumiem.}
{214} {} {Tak.}

{215} {} {Pozwolono mi siê rozejrzeæ.}
{216} {} {W takim razie nie mo¿esz liczyæ ju¿ na dalsz¹ wycieczkê. Wynoœ siê, zanim wezwê ochronê!}
{217} {} {Zaden problem.}

{219} {} {Wys³ano mnie, ¿eby coœ naprawiæ.}
{220} {} {To rusz siê i napraw to, idioto!}
{1220} {} {To rusz siê i napraw to, idioto!}
{221} {} {Tak, oczywiœcie.}

{223} {} {Ja te¿ jestem naukowcem i skierowano mnie do ciebie.}
{224} {} {Naprawdê? (odk³ada tablet) Bardzo ciekawe... ca³kiem... Ale nikt nie doniós³ mi o nowym asystencie laboratoryjnym. Zg³oœ siê gdzie trzeba, a potem porozmawiamy.}
{225} {} {Ok.}

{227} {} {Pozwolono mi siê rozejrzeæ.}

# Powtarzajacy siê dialog
{300} {} {Ok. Czego teraz chcesz?}
{301} {} {Nic wiêcej.}
{302} {} {Do widzenia.}
{303} {} {Czy mo¿emy zmieniæ temat?}
{304} {} {Pozwól, ¿e zadam ci inne pytanie.}
{305} {} {Z ca³ym szacunkiem kolego, * ja * tu rz¹dzê. I mam prawo wyrzuciæ ka¿dego z laboratorium, nawet samego Aarona. Wyjœæ!}
{306} {} {Ok, ok...}

# Pytania o sobie
{310} {} {Przepraszam, ale kim jesteœ?}
{311} {} {(macha rêk¹ z frustracj¹) To w³aœnie znaczy byæ w cieniu... Nazywam siê Zach Zimmer. Profesor Zach Zimmer. I to ja kierujê tym dzia³em naukowym. W praktyce jestem trzeci¹ osob¹ w ca³ym koœciele, po Aaronie i Doradcy. Nie musisz klêkaæ.}

{312} {} {Naukowcy s¹ obecnie bardzo rzadkim widokiem.}
{313} {} {Dlatego siedzê w Krypcie pod ochron¹ najwiêkszej organizacji. Naukowcy bez ochrony nie mog¹ przetrwaæ w naszych czasach.}
{314} {} {Czy profesor to imiê?}
{315} {} {(wzdycha) Nigdy nie s³ysza³em g³upszego pytania.}
{316} {} {Profesor to tytu³. I jest nadawany kolegialnie.}
{317} {} {Jaki wgl¹d! Pozwól, ¿e zdradzê ci sekret - kiedyœ bra³em udzia³ w kursach w jednej ma³o znanej organizacji w tych stronach. To tam otrzyma³em ten tytu³.}
{318} {} {Jak siê tu znalaz³eœ, profesorze?}
{319} {} {Musisz mieæ bardzo interesuj¹c¹ historiê.}
{320} {} {To d³uga historia i nie dla twoich uszu. Powiedzmy tylko, ¿e na Zachodzie skoñczy³o siê miejsce na moje ambicje.}
{321} {} {Zachodnia Kalifornia. Nie s¹dzê, ¿ebyœ by³ w stanie przejœæ przez pustyniê, która nas dzieli.}
{322} {} {Ahem. Zadajesz zbyt wiele pytañ.}
{323} {} {Jestem cz³onkiem Bractwa Stali. Z pewnoœci¹ baza zawiera szczegó³ow¹ dokumentacjê na Twój temat.}
{324} {} {To bardzo wiele zmienia. Tak, przyby³em tutaj z Bractwem Stali. I otrzyma³em tytu³ od Wyznawców Apokalipsy w dalekim miejscu. Ale rozstaliœmy siê z kolegami i musia³em wyjechaæ do Arizony.}
{325} {} {Ró¿nica zdañ?}
{326} {} {Powiedzmy, ¿e... Wyznawcy Apokalipsy s¹ zbyt miêkcy. Sprzeciwiaj¹ siê eksperymentom na ¿ywych ludziach. Spowolni³o to wiele moich projektów medycznych.}
{327} {} {Co to za dalekie miejsce?}
{328} {} {Ruiny na zachodzie, za pustyni¹ Sonora. Jest to bardzo daleko, nie mo¿esz siê tam tak po prostu dostaæ, nawet za pomoc¹ karawany.}

{330} {} {Wiêc te¿ jesteœ zwolennikiem ognia?}
{331} {} {Co to za bzdury? Jestem naukowcem, a nie kaznodziej¹! Poza tym wiele rzeczy w ich nauczaniu wydaje mi siê po prostu œmiesznych.}
{332} {} {Czy mo¿esz mi opowiedzieæ o Aaronie?}
{333} {} {Rozmowy o liderach by³y zawsze niebezpieczne. Nawet wœród cz³onków kultu.}
{334} {} {Nie jestem cz³onkiem kultu.}
{335} {} {Wiêc nie mamy ju¿ o czym rozmawiaæ.}
{336} {} {Jestem cz³onkiem Bractwa Stali.}
{337} {} {Och... To bardzo wiele zmienia... W takim razie lepiej porozmawiaj z doradc¹ zamiast ze mn¹.}
{338} {} {To zostanie miêdzy nami.}
{339} {} {Aaron by³by nikim, gdyby nie powierzono mu w³adzy nad miastem i koœcio³em. Nadal czuje, ¿e jest marionetk¹, czasem strasznie go to wkurza... Coœ dziœ za du¿o mówiê.}
{340} {} {Nie mo¿esz tu nikomu ufaæ.}
{341} {} {Na przyk³ad?}
{342} {} {Mam doœæ wyjaœniania prostych rzeczy wszystkim tym mnichom. Lepiej poczytaj literaturê naukow¹.}
{343} {} {Na przyk³ad deifikacja cz¹stek elementarnych?}
{344} {} {Tak! Co to za absurdalny pomys³, ¿e jakieœ Bóstwo ukara³o ludzi ognistym potopem za ich grzechy? To by³a wojna nuklearna! To znaczy zwyk³a wojna z bardzo potê¿nymi bombami.}
{345} {} {Czy oni tego nie wiedz¹?}
{346} {} {Obawiam siê, ¿e minê³o za du¿o czasu. Wydarzenia minionej epoki obfituj¹ w mity i legendy. Z drugiej strony wiara wyznawców jest dobra dla spo³eczeñstwa... o ile nie sprzeciwia siê postêpowi.}

{350} {} {Dlaczego zajmujesz siê podw³adnymi?}
{351} {} {Poniewa¿ mam doœæ idiotów i ma³p-ignorantów.}
{352} {} {Czy to wszystko?}
{353} {} {Nie bêdê o tym rozmawiaæ.}
{354} {} {Myœlê, ¿e jest to projekcja niespe³nionych nadziei. Czy nie masz wolnoœci, na któr¹ zas³ugujesz?}

{355} {} {(poprawia okulary z niedowierzaniem) Wow! Spójrzcie, pierwszy psycholog cywilizacji postnuklearnej! Zostaw te s³odkie, pocieszaj¹ce przemówienia dla tych na górze. Gdyby bardziej szanowali moj¹ sprawê, nie musia³bym podnosiæ g³osu na wszystkich, których spotykam.}
{356} {} {Oczywiœcie, cokolwiek powiesz.}
{357} {} {Co to jest „ma³pa”?}
{358} {} {(wzdycha) To ty.}
{359} {} {[Science 20] Mówi¹, ¿e praca zrobi³a z ma³p ludzi.}
{360} {} {Bzdura! Uda³o mi siê znaleŸæ stare teksty, w których jest jasno powiedziane, ¿e s¹ to dwie ró¿ne ga³êzie ewolucji o wspólnych przodkach. Jednak... o wiele wa¿niejsze jest, ¿ebym us³ysza³ to z ust zwyk³ego cz³owieka.}

# Pytania dotycz¹ce bomby
{378} {} {Czy sam zaprojektowa³eœ to wszystko?}
{379} {} {Oczywiœcie. Wiele lat ¿mudnej pracy garstki naukowców.}
{380} {} {Czy to twoja bomba atomowa? Imponuj¹ca.}
{381} {} {To prawdopodobnie najtrudniejsza rzecz, jak¹ kiedykolwiek zrobiliœmy. Nikt, a¿ do Kalifornii i Teksasu, nie móg³ tego zrobiæ. Jesteœmy na skraju ukoñczenia! Pozostaje tylko poczekaæ na szczegó³y techniczne z Tu-San.}
{382} {} {Kalifornia i... Texas?}
{383} {} {(rozczarowany) Texas! To ziemie minionego kraju, durniu. Mo¿e teraz nazywaj¹ siê inaczej, ale przed wojn¹ tak siê w³aœnie nazywa³y.}
{384} {} {Ale nie mog³eœ jej zbudowaæ bez instrukcji.}
{385} {} {Hmm, geniusz! Bez instrukcji moglibyœmy dostaæ tylko raka i bia³aczki. Instrukcje zosta³y przyniesione na zamówienie ze starej bazy wojskowej, bardzo daleko st¹d.}
{386} {} {Sk¹d bierzesz materia³ j¹drowy?}
{387} {} {W Flagpool jest dzia³aj¹ca kopalnia uranu i zak³ad wzbogacania. Jakoœæ jest niska, a produkcja powolna, ale nie mamy innych Ÿróde³.}
{388} {} {Dlaczego potrzebujesz tak potê¿nej broni?}
{389} {} {Dobre pytanie. Powiedzmy, ¿e jest wiele powodów. I wszystkie s¹ znane tylko jednej osobie w ca³ym Phoenix - samemu Doradcy.}

# Pytania badawcze
{400} {} {Jakie badania prowadzi laboratorium?}
{401} {} {Oczywiœcie ró¿ne. (wraca do swoich myœli) Nasz¹ misj¹ jest... najpierw zapewniæ Wyznawcom Ognia wszystko, czego potrzebuj¹... Tak. A potem zajmiemy siê odbudow¹ miasta i jego obiektów przemys³owych. W koñcu potrzebujemy sprawnych r¹k... A to dopiero pierwsza czêœæ planu. Najwa¿niejsze jest teraz wyeliminowanie niedoboru ¿ywnoœci i czystej wody w Phoenix.}
{402} {} {Jak siê masz?}
{403} {} {Postep jest, ale za wolny. Miasto jest mocno zniszczone, stary sprzêt jest zniszczony lub zu¿yty, a baza produkcyjna tego schronu wystarcza tylko na utrzymanie Katedry. Dodajmy do tego spory miêdzy poszczególnymi klanami w mieœcie, analfabetyzm i ca³¹ listê innych problemów. Jeœli nie masz g³upszych pytañ, wrócê do szukania rozwi¹zañ.}
{404} {} {Czu³em, ¿e Wyznawcy nie byli w stanie rozdawaæ jedzenia potrzebuj¹cym.}
{405} {} {O czym ty mówisz? Nikt nie bêdzie karmi³ tego mot³ochu na ulicach! Jedzenie i woda to bezwarunkowa w³adza nad ca³ym miastem. W zamian za jedzenie miejscowi s¹ gotowi wykonaæ ka¿d¹ pracê, a my potrzebujemy taniej si³y roboczej.}
{406} {} {Si³a robocza? Co za bana³.}
{407} {} {Co za kretyn! W³adza to tylko mechanizm. Kiedy stworzyliœmy kult Ognia, w tym mieœcie nie by³o ¿adnej si³y roboczej. By³y tylko nieszczêœliwe naczelne, walcz¹ce miêdzy sob¹ o martwego szczura. A teraz spójrz na miasto. Wraz z naszym pojawieniem siê wróci³y pr¹d i waluta, narodzi³ siê przemys³ i edukacja, pojawi³ siê nawet hazard! A wszystko to za spraw¹ ciê¿kiej rêki kultu, która postawi³a miejscowe ma³py do pionu.}
{408} {} {[Science 100] Na ile jesteœ pewien, ¿e spo³eczeñstwo jest gotowe na takie innowacje?}
{409} {} {Du¿o o tym myœla³em......}