{100} {} {Widzisz obiekt testu.}

{101} {} {Widzisz zrozpaczon¹ osobê. W milczeniu patrzy w górê.}
{102} {} {Widzisz kobietê z potarganymi w³osami i czerwonymi oczami. Odwróci³a siê do œciany.}
{103} {} {Widzisz wariata. Siada na pod³odze i ko³ysze siê, œciskaj¹c g³owê.}

{111} {} {Uh-uh-uh...}
{112} {} {Nie chcê ciê s³uchaæ! Wynoœ siê, przeklêty kultysto!}
{113} {} {Moja g³owa! S³yszê tyle myœli... Twoje myœli... s¹ okropne!}