{110} {} {Ta bomba mo¿e byæ bardzo niebezpieczna, ale brakuje jej niektórych czêœci.}
{111} {} {Bomba jest gotowa do detonacji.}
{112} {} {Pomyœlnie umieszczono bezpieczniki.}
{113} {} {Bomba jest gotowa do detonacji. U¿yj umiejêtnoœci "pu³apki", aby j¹ aktywowaæ.}
{114} {} {Cholera, to najwiêksza bomba, jak¹ kiedykolwiek widzia³eœ.}
{115} {} {To nie jest konieczne. Historia przebiega ju¿ zgodnie z po¿¹danym scenariuszem.}

{120} {} {Widzisz g³owicê nuklearn¹ o niskiej wydajnoæci. Chocia¿ nie jest ukoñczona, nadal mo¿na j¹ wysadziæ.}
{121} {} {Widzisz bombê, nie ma bezpieczników, wiêc na razie jest bezpieczna.}
{122} {} {Pomyœlnie aktywowano licznik atomowy.}
{123} {} {Pomyœlnie dezaktywowano licznik atomowy.}
{124} {} {Nie ma sensu naprawiaæ g³owicy.}
{125} {} {Nie mo¿na dezaktywowaæ licznika czasu.}

{505} {} {Pozosta³o }
{506} {} { sekund do wybuchu.}
