{100} {} {Widzisz komputer Doradcy.}
{101} {} {Widzisz potê¿ny komputer z gniazdem na kartê dostêpu.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Koniec sesji.}
{202} {} {Wstecz.}

{210} {} {Anuluj alarm.}
{211} {} {Alarm wy³¹czony.}
{212} {} {Wy³¹cz pu³apki w korytarzu.}
{213} {} {Pu³apki dezaktywowane.}

{220} {} {Sabota¿ w Flagpool.}
{221} {} {(Agenci z Flagpool donosz¹ o sabota¿u w kopalni uranu. Przypuszczalnie sabota¿u dokonali wiêŸniowie. W ka¿dym razie powinniœmy ponownie rozwa¿yæ nasz¹ politykê wobec tej kolonii i metody pana Fabera.)}

{230} {} {Stary raport o zamachu stanu w Phoenix.}
{231} {} {(Doradca opisuje szczegó³y przewrotu, który wydarzy³ siê kilka lat temu w Phoenix. Zapisy wskazuj¹, ¿e trzecia si³a ustanowi³a w mieœcie w³adze kultu Ognia, umieszczaj¹c przy niej ludzi, których potrzebowa³a. I bazê rekonstrukcyjn¹ by zapewniæ Sztabowi Generalnemu podstawowe zasoby. Innymi s³owy, kult Ognia jest marionetk¹ w czyjejœ grze...)}
{232} {} {Raport finansowy.}
{233} {} {Dziêki naszej systematycznej pracy w Phoenix, nowa waluta kapsli do butelek po¿yczona z Centrum mocno siê ugruntowa³a. Poniewa¿ jednak mieszkañcy nie byli przyzwyczajeni do waluty jako takiej, zaszczepienie w spo³eczeñstwie tego pomys³u i ustabilizowanie stawki kapsli zajê³o kilka lat. Za³¹czam do raportu statystyki i analizy procesów finansowych w mieœcie oraz perspektyw rozwoju waluty kapsli w przysz³oœci.}

{240} {} {Raport statusu kultu.}
{241} {} {...Wniosek 1. Zgodnie z oczekiwaniami, kult Ognia wzorowany na Dzieciach Katedry przyniós³ dobre wyniki. Uchwyci³ prawie wszystkie dziedziny ¿ycia w mieœcie i mocno ugruntowa³ swoj¹ pozycjê. Ludnoœæ Phoenix pozostaje lojalna wobec wyznawców ognia lub siê ich boi. W ten sposób mo¿emy elastycznie zmieniaæ lokaln¹ spo³ecznoœæ wed³ug w³asnego uznania za pomoc¹ si³ Wyznawców Ognia. Chocia¿ powstañcy ukrywaj¹cy siê w kana³ach wci¹¿ sprawiaj¹ k³opoty, to jednak nie stanowi¹ wiêkszego zagro¿enia dla naszego planu.}
{242} {} {Czytaj wiêcej.}
{243} {} {Wniosek 2. Udaje nam siê pozostaæ incognito, ograniczaj¹c siê tylko do w¹skiego krêgu wybranych osób. Przywódca sekty jest gotów wype³niaæ nasze instrukcje bez pytania, niezale¿nie od w³asnych ambicji. Uœwiadomi³ sobie swoj¹ marionetkow¹ rolê i jest gotów siê z ni¹ liczyæ, ale nie jest œwiadomy naszych planów. Przypuszczalnie ta relacja bêdzie trwa³a przez nastêpne 3-4 lata, po czym warto bêdzie wyeliminowaæ Aarona i zainstalowaæ na jego miejsce now¹ osobê.}
{244} {} {Czytaj wiêcej.}
{245} {} {Wniosek 3. Wierzê, ¿e kult jest gotowy do ekspansji. Rozpoczynamy ekspansjê idei Swiêtego Ognia do San Brahmin w celu zorganizowania tam nowej kolonii surowcowej i transportowej.}

{250} {} {Raport poszukiwania G.E.C.K..}
{251} {} {Wci¹¿ brakuje nam informacji na temat obecnoœci G.E.C.K, ale poszukiwania trwaj¹. Za³¹czam raporty z wyprawy.}
{252} {} {Ekspedycja do Krypty 26.}
{253} {} {Ekspedycja do Krypty 26 nie powiod³a siê. Schron zosta³ zniszczony przez uderzenie nuklearne. Wykopaliska nie s¹ mo¿liwe.}
{254} {} {Ekspedycja do Krypty 27.}
{255} {} {Ekspedycja do Krypty 27 nie by³a w stanie potwierdziæ obecnoœci G.E.C.K.. Obecnie trwaj¹ d³ugotrwa³e wykopaliska. Potwierdzono, ¿e Krypta jest spl¹drowana i jest w z³ym stanie. Czêœæ sprzêtu zosta³a wywieziona konwojem do Tu-San, lista w za³¹czniku. Za³¹czam równie¿ kopie raportów z wyprawy.}
{256} {} {Uwaga.}
{257} {} {Istniej¹ dowody na to, ¿e populacja Phoenix sk³ada siê w du¿ej mierze z potomków mieszkañców Krypty 27. Istnieje równie¿ legenda o walce ich przodków, którzy poszli swoimi drogami. Mo¿na przypuszczaæ, ¿e jedna z grup imigrantów zabra³a ze sob¹ G.E.C.K.. Tê hipotezê nale¿y sprawdziæ, jeœli nie znajdziemy urz¹dzenia.}
{258} {} {Wyszukaj wspó³rzêdne Krypty 27.}
{259} {} {(Wprowadzasz wspó³rzêdne do swojego Pip-Boya)}

{260} {} {Raport z projektu Bomba Nuklearna.}
{261} {} {W tej chwili projekt jest ukoñczony w 92%. Oczekujemy nowych elementów mechanicznych od warsztatów Tu-San. Postêp jest hamowany przez niedobór personelu naukowego i powoln¹ produkcjê uranu w kopalniach Flagpool. Czciciele ognia wci¹¿ nie maj¹ pojêcia o prawdziwym kliencie i celu bomby.}