{100} {} {Widzisz konsolê.}
{101} {} {Widzisz konsolê bloku wiêziennego. Mo¿na za jej pomoc¹ sterowaæ polami si³owymi.}
{102} {} {Pola si³owe bloku wiêziennego s¹ wy³¹czone.}
{103} {} {Poziom dostêpu nie jest wystarczaj¹co wysoki.}

{200} {} {WprowadŸ polecenie.}
{201} {} {Wy³¹cz pole si³owe nr 1.}
{202} {} {Aktywuj pole si³owe nr 1.}
{203} {} {Wy³¹cz pole si³owe nr 2.}
{204} {} {Aktywuj pole si³owe nr 2.}
{205} {} {Wy³¹cz pole si³owe nr 3.}
{206} {} {Aktywuj pole si³owe nr 3.}
{207} {} {Wstecz.}
{208} {} {Zakoñcz sesjê.}
