{100} {} {Widzisz komputer laboratoryjny.}
{101} {} {Widzisz komputer laboratoryjny.}

#Dialog
{200} {} {Proszê wydaæ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}

{210} {} {Kopiuj dane geograficzne.}
{211} {} {Dane zosta³y pomyœlnie wprowadzone do sekcji map twojego Pip-Boya.}

{220} {} {Informacje o Krypcie 25.}
{221} {} {Numer Krypty - 25. Rozpoczêcie budowy - marzec 2064. Zakoñczenie budowy - styczeñ 2068. Wykonawca budowy: Vault-Tec. Cel - ochrona ludnoœci cywilnej podczas ataku nuklearnego. Szacunkowa liczba mieszkañców - 450. Czas trwania zamkniêcia - 15 lat.}
{222} {} {Historia Krypty 25.}
{223} {} {Podczas Wielkiej Wojny w 2077 roku otwarto Kryptê dla zwyk³ych obywateli Phoenix. Jednak bliskoœæ i nag³oœæ ataków nuklearnych zmusi³a pracowników Krypty do uszczelnienia drzwi pancernych bez czekania na wiêkszoœæ populacji. Tym samym tylko 12% planowanym mieszkañcom uda³o siê dostaæ do œrodka.}
{224} {} {Dalej.}
{225} {} {Nadwy¿ka zasobów i przestrzeni pozwoli³a ocala³ym na szczêœliwe i beztroskie ¿ycie bez wychodzenia na powierzchniê. Otwarcia i kolonizacji schronu dokona³a wyprawa Ulissesa Granta w 2162 roku.}
{226} {} {Charakterystyka mieszkañców.}
{227} {} {Populacja Krypty by³a w doskona³ym zdrowiu fizycznym, ale s³abej kondycji. Ludnoœæ nie jest przystosowana do ciê¿kiej pracy fizycznej. Zdrowie psychiczne pozosta³o ogólnie dobre, chocia¿ wielu cierpia³o na fobie wobec œwiata zewnêtrznego.}

{230} {} {Eksperymenty medyczne.}
{231} {} {Wyznawcy ognia przeprowadzaj¹ ró¿ne eksperymenty medyczne dziêki dobrze zachowanemu wyposa¿eniu Krypty.}
{232} {} {Projekty w trakcie opracowywania.}
{233} {} {Poprawa odpornoœci na promieniowanie; zwiêkszenie skutecznoœci bojowej stra¿ników œrodkami chemicznymi; program antywirusowy dla choroby pustkowi.}
{234} {} {Zawieszone projekty.}
{235} {} {Standardowe szczepienia Med-Tec (z powodu braku surowców); Kontrola umys³u na odleg³oœæ (z powodu braku sprzêtu).}

{240} {} {Projekt produkcji ¿ywnoœci.}
{241} {} {Wyznawcy ognia prowadz¹ ró¿ne badania, aby rozwi¹zaæ problem ¿ywnoœciowy w Phoenix. S¹ to eksperymenty na roœlinach (projekt zosta³ przeniesiony do dzia³u Casa Nueva), na fermach pieczarek i mikrobiologicznych, produkcja nowych przetwórców ¿ywnoœci w Tu-San, badania nad technologi¹ G.E.C.K..}
{242} {} {Co to jest G.E.C.K.?}
{243} {} {Garden of Eden Creation Kit to staro¿ytna technologia odbudowy Ziemi po uderzeniu nuklearnym. Technologia by³a zbyt z³o¿ona, aby mo¿na j¹ by³o odtworzyæ w laboratorium Krypty 25. W poszukiwaniu dzia³aj¹cego G.E.C.K., Obserwatorzy wys³ali ekspedycje do innych Krypt.}
{244} {} {Ekspedycja do Krypty 26.}
{245} {} {Krypta zosta³a zniszczona przez atak nuklearny, G.E.C.K. nie przetrwa³.}
{246} {} {Ekspedycja do Krypty 27.}
{247} {} {Wykopaliska s¹ obecnie prowadzone pod kierownictwem Arthura Carringtona. Wspó³rzêdne schronienia s¹ do³¹czone. Obecnoœæ G.E.C.K. w Krypcie nie zosta³a potwierdzona.}

{250} {} {Projekt bomby atomowej.}
{251} {} {Wykonanie bomby uranowej Baby Phoenix przy u¿yciu surowców z Flagpool. Kurator: profesor Zach Zimmer. Zakoñczenie: 92%.}
{252} {} {Wy³¹cz pole si³owe w sekcji atomowej.}
{253} {} {Pole si³owe dezaktywowane.}

{260} {} {Raporty o dostawach uranu i niewolników.}
{261} {} {(Opisano tutaj typow¹ rutynê kwartaln¹. Uran z Flagpool i niewolnicy z ca³ego regionu s¹ czêœciowo wykorzystywani przez kult wed³ug w³asnego uznania, a czêœciowo konwojowani na po³udnie do Tu-San)}
{262} {} {Poszukaj informacji o niewolnikach z Villi.}
{263} {} {(Znajdujesz informacje o kilku wiêŸniach z Villi. Niestety, zostali ju¿ wys³ani do Tu-San.)}