{102} {} {Nape³niono pojemnik z syntetycznymi surowcami.}

{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {SprawdŸ, czy nie ma materia³u syntetycznego.}

{210} {} {Wk³ad z tworzywa sztucznego jest pusty.}
{211} {} {Wk³ad z tworzywa sztucznego pe³ny w }
{212} {} {%.}
{213} {} {Wykonaj kombinezon Krypty (koszt 25% materia³u).}
{214} {} {Wykonaj szatê wyznawców ognia (50% kosztu materia³ów).}
{215} {} {Gotowe.}