{100} {} {Widzisz outsidera.}
{101} {} {Widzisz cz³owieka w zniszczonym ubraniu.}
{102} {} {Powodzenia. Wkrótce opuszczê akwedukt. Spróbujê znaleŸæ miejsce do ¿ycia w górnym biegu Kolorado.}
{103} {} {Co by³o... w tej wodzie...}
{104} {} {Ahh...}

#Dialog
{200} {} {Ech, czeœæ?}
{201} {} {Jestem tu od niedawna. Szukam informacji.}
{202} {} {Ja te¿... œwietnie. Jestem tu od niedawna. I nie mam szczêœcia do znajomych.}
{203} {} {Czy coœ siê sta³o?}
{204} {} {Przyszed³em z dwoma przyjació³mi, ale zniknêli, a miejscowi nie chc¹ siê ze mn¹ zadawaæ. Teraz siedzê przy ognisku, ³owiê ryby i myœlê o przysz³oœci.}
{205} {} {Smutna historia. Przykro mi.}
{206} {} {Nieufnoœæ miejscowych jest zrozumia³a.}

{210} {} {Czego chcesz?}
{211} {} {Nic. Bywaj.}
{212} {} {Jak twoje poszukiwanie?}
{213} {} {Przepraszam, ale niczego jeszcze siê jeszcze nie dowiedzia³em.}
{214} {} {Czeœæ.}
{215} {} {Do widzenia.}

{220} {} {A co z Rangersami? Czy nie mog¹ znaleŸæ Twojej grupy?}
{221} {} {Rozmawia³em z Garthem, on jest tu kimœ w rodzaju szeryfa. Ale wydaje siê, ¿e nic nie robi. A co on sam mo¿e zrobiæ? Sam przeprowadzi³em ju¿ wywiady z mieszkañcami, nikt nic nie wie.}
{222} {} {Sk¹d jesteœ ty i twoja grupa?}
{223} {} {Uciekliœmy z ma³ej wioski daleko st¹d, kiedy ¿ycie sta³o siê nie do zniesienia. Powiedziano nam, ¿e Stra¿nicy s¹ gotowi przyj¹æ wszystkich pod swoj¹ ochronê. Wygl¹da jednak na to, ¿e nie jesteœmy tu mile widziani.}
{224} {} {Poszukam twoich ludzi i jeœli siê czegoœ dowiem, dam ci znaæ.}
{225} {} {Dziêki. Powiedz mi wszystko, czego siê dowiesz.}
{226} {} {Do widzenia. Do zobaczenia.}

{230} {} {Uda³o mi siê znaleŸæ twoich przyjació³... na dnie akweduktu.}
{231} {} {Nie ¿yj¹, co? Cholera... Teraz rozumiem, dlaczego Garth zabrania wchodzenia do tej staro¿ytnej budowli. Z pewnoœci¹ nie jesteœmy pierwszymi, których on i jego poplecznicy zabili. Przeklêci Stra¿nicy...}
{232} {} {Co zamierzasz teraz zrobiæ?}
{233} {} {Chcia³bym siê zemœciæ na tym draniu, ¿eby historia siê nie powtórzy³a. Ale to tylko uczyni mnie wrogiem publicznym. W ka¿dym razie nie mogê tu zostaæ.}
{234} {} {A co z raportem do bazy? Wydaje mi siê, ¿e tam nikt nic nie wie.}
{235} {} {Nie pozwalaj¹ mi zobaczyæ dowódcy, ju¿ próbowa³em. Mo¿esz ty to zrobiæ? Jeœli nie zatrzymasz Gartha, bêdzie on nadal eliminowa³ wszystkich niechcianych.}
{236} {} {Spróbujê skontaktowaæ siê z genera³em. Nie bêdzie to jednak ³atwe.}
{237} {} {Jesteœ wspania³¹ osob¹. Dziêkujê Ci.}
{238} {} {Czekaj, ch³opcze.}
{239} {} {IdŸ do diab³a, jestem ca³y w gównie przez ciebie.}
{240} {} {Oczywiœcie, zapomnij. Po prostu st¹d wyjdê, a Garth pozostanie bezkarny... Tak. Tak bêdzie lepiej.}
{241} {} {Tylko nie graj mi na uczuciach! Adios, ch³opcze.}
{242} {} {Mo¿e po prostu zabijemy Gartha? Bêdzie to ³atwiejsze i przyjemniejsze.}
{243} {} {Zabiæ Stra¿nika i znaleŸæ siê na liœcie przestêpców? Do diab³a, nie chcê uciekaæ przed Stra¿nikami do koñca ¿ycia. Lepiej, jeœli po prostu st¹d wyjadê.}
{244} {} {Có¿, mi³ej podró¿y, ch³opcze.}

{250} {} {Stra¿nik Garth dosta³ to, na co zas³u¿y³. Twoi przyjaciele zostali pomszczeni.}
{251} {} {Tak... chocia¿ to ich nie przywróci. Wiesz, w³aœciwie jesteœmy przyjació³mi raczej z nieszczêœcia. Po drodze wiele siê wydarzy³o. Musieliœmy rabowaæ podró¿ników i ma³e osady. Dopiero tutaj poczuliœmy siê czêœci¹ czegoœ i mogliœmy wieœæ normalne ¿ycie. Nawet pomimo nieufnoœci miejscowych. Ale ten Stra¿nik wszystko zrujnowa³.}
{252} {} {Hmm. Szkoda, ¿e tak siê sta³o.}
{253} {} {By³ ograniczony w swoich w¹tpliwoœciach co do twojego gangu.}
{254} {} {Dziêki za wszystko. WeŸ te kule. Szczerze mówi¹c, ukrad³em je Stra¿nikom, uczciwie jest daæ ci je w nagrodê. I czas, ¿ebym ruszy³ w drogê. Nie bêdzie tu dla mnie miejsca do ¿ycia.}
{255} {} {Bon voyage.}