{100} {} {Widzisz osadnika.}
{101} {} {Widzisz typowego obywatela Akweduktu.}

{200} {} {Czy nie jest ju¿ za póŸno na wizytê?}
{201} {} {Po prostu...}
{202} {} {Wynoœ siê! OdejdŸ!}
{203} {} {Ok, stary. Porozmawiamy po po³udniu.}

{210} {} {Huh? Nie mam czasu na rozmowê. Powinieneœ porozmawiaæ z Garthem lub innymi lokalnymi w³óczêgami.}
{211} {} {Huh? Nie mam czasu na rozmowê. ZnajdŸ kogoœ, kto nie ma nic do roboty.}
{212} {} {Nigdy bym nie pomyœla³, ¿e Garth sta³ za tymi wszystkimi znikniêciami. Teraz rozumiem, dlaczego zabroni³ schodziæ do katakumb akweduktu. Ale z drugiej strony, kto bêdzie nas teraz chroni³ przed niechcianymi wspó³lokatorami?}
{213} {} {Witaj Stra¿niku. Jak siê masz?}
{214} {} {Do widzenia.}

{220} {} {Co robisz?}
{221} {} {Przygotowujê siê na wielk¹ wyprawê na ryby nad zalewem. Wiesz, to k³opotliwa sprawa.}
{222} {} {Kto zbudowa³ ten akwedukt?}
{223} {} {Szczerze, nie wiem. Mo¿e to byli sami Rangersi. W ka¿dym razie konstrukcje te stoj¹ tu od niepamiêtnych czasów.}
{224} {} {Co myœlisz o Garthu?}
{225} {} {Dobry cz³owiek, twardy i nieprzekupny. Stoi za naszym ludem jak góra i wielokrotnie pomaga³ w ochronie przed bandytami, rabusiami i zwierzêtami. Mieszka w domu naprzeciwko.}
{226} {} {Jak sobie radzisz w tych okolicach pod ochron¹ Stra¿ników?}
{227} {} {Wiedziemy tu wspania³e ¿ycie. Stra¿nicy chroni¹ nas przed bandytami i bestiami, a my p³acimy im za to czêœci¹ naszego jedzenia. Nie mam ¿adnych skarg na Stra¿ników.}
{228} {} {Co wiesz o zaginiêciach?}
{229} {} {Oczywiœcie to przez bestie. Wzd³u¿ doliny rzeki ¿yj¹ wilki i paskudne kretoszczury. Osoby postronne czêsto nie zdaj¹ sobie sprawy z tego niebezpieczeñstwa.}
{230} {} {Mówi¹, ¿e masz tu epidemie.}
{231} {} {Tak, niespodziewanie kilka osób zachorowa³o na gor¹czkê. Niektórzy wyzdrowieli, a niektórzy nadal cierpi¹ na intensywn¹ gor¹czkê. W chatce po drugiej stronie ulicy jeden z nich wci¹¿ walczy.}

{240} {} {Przys³a³a mnie spo³ecznoœæ Garage City. Maj¹ spore problemy z jedzeniem.}
{241} {} {Hmm. Mówi¹, ¿e to miasto jest pe³ne specjalistów od ¿elaza. Potrzebujemy czêœci przynajmniej do naprawy ³odzi. Ale mówi¹ te¿, ¿e mieszkañcy nie s¹ specjalnie przyjaŸnie nastawieni do Rangersów. Problem g³odu musi byæ naprawdê przera¿aj¹cy, jeœli s¹ gotowi siê „poddaæ”.}
{242} {} {Zgadzasz siê?}
{243} {} {Nie uda³o mi siê jeszcze przekonaæ Stra¿ników, by zgodzili siê na handel. Ale ten biznes pachnie zbyt du¿ym zyskiem, raczej nie odmówi¹. Tak, wys³a³bym karawanê suszonych ryb do tego obrzydliwego i œmierdz¹cego miasta.}
{244} {} {W Garage City ludzie g³oduj¹, a ty ju¿ zacierasz rêce w oczekiwaniu na korzyœci. Pomyœl o tym.}
{245} {} {Ok, przeka¿ê zgodê Garage City.}