{100} {} {Widzisz Keela.}
{101} {} {Widzisz faceta w skórzanej kurtce. Bawi siê swoj¹ w³óczni¹.}
{102} {} {Wszystkim bêdzie lepiej, jeœli odejdziesz.}
{103} {} {Uch... chyba przesadzi³em...}

{110} {} {Czego chcesz, co?}
{111} {} {Nie krzywdŸ miejscowych.}
{112} {} {Nie znam ciê.}
{113} {} {IdŸ, dok¹d idziesz.}
{114} {} {W Akwedukcie mieszkaj¹ tylko normalni ludzie.}
{115} {} {Myœlê, ¿e nie znajdziesz tu miejsca do spania.}
{116} {} {Z³odziejom odcina siê tu rêce. To tak przy okazji.}

#Dialog
{200} {} {Czekaj. Co Ty tutaj robisz?}
{201} {} {Nie twoja sprawa.}
{202} {} {Mylisz siê. I s³ono zap³acisz za ten b³¹d...}
{203} {} {Hej, zatrzymaj...}
{204} {} {Tylko spróbuj.}
{205} {} {Poni¿ej s¹ zw³oki ludzi. Wiesz o tym cokolwiek?}
{206} {} {A tak. To musz¹ byæ idioci, którym zabroniono wchodziæ do akweduktu. Nie s³uchali, tak jak ty.}
{207} {} {Zostali zabici. I nie przez bestie, ale przez cz³owieka.}
{208} {} {Ooh, widzê ¿e jesteœ mistrzem zgadywania. Co zamierzasz teraz zrobiæ?}
{209} {} {Zabijê wszystkich zaanga¿owanych. I wygl¹da na to, ¿e jesteœ jednym z nich.}
{210} {} {Garth ostrzega³, ¿e jesteœ niebezpieczny. No dalej, nieznajomy, spróbuj.}
{1210} {} {Garth ostrzega³, ¿e jesteœ niebezpieczna. No dalej, nieznajoma, spróbuj.}
{211} {} {Hmm...}
{212} {} {W³aœciwie jestem tu przez przypadek. Pozwolisz mi wyjœæ i zapomnieæ o wszystkim?}
{213} {} {Czy naprawdê jesteœ takim naiwnym g³upcem? Garth rozkaza³ ciê zabiæ, jeœli coœ wywêszysz. Przykro mi, to nic osobistego...}
{1213} {} {Czy naprawdê jesteœ takim naiwnym g³upcem? Garth rozkaza³ ciê zabiæ, jeœli coœ wywêszysz. Przykro mi, to nic osobistego...}
{214} {} {Czekaj, nie chcê walczyæ...}
{215} {} {Nie zostawiasz mi wyboru.}
{216} {} {Naprawdê liczysz, ¿e nie poradzê sobie z jedn¹ w³óczni¹?}
{217} {} {Ta w³ócznia nie raz uratowa³a mi ¿ycie. Chcesz to sprawdziæ?}
{218} {} {Och, to bêdzie interesuj¹ce. Rozpocznijmy przedstawienie...}
{219} {} {W takim razie powinieneœ wiedzieæ, ¿e moja lokalizacja jest znana g³ównej siedzibie Stra¿ników. Nikt tak ³atwo tego nie odpuœci. Chcesz problemów?}
{220} {} {Nie... Nie chcê problemów. Ale bêd¹, gdy Garth siê o tym dowie.}
{221} {} {Mogê to zatrzymaæ. Garth przekroczy³ liniê, której Stra¿nik nie mo¿e przekroczyæ. Nie rozumiesz?}
{222} {} {Kurwa. Nie ma sensu z tob¹ rozmawiaæ. Niech bitwa zadecyduje o tej sprawie.}
{223} {} {Teraz rozumiem, ¿e stwarzasz wielkie zagro¿enie dla naszego spokojnego miasta. Nie bez powodu Garth za³atwi³ wszystkie te odpady z pustkowi. Nie potrzebujemy ludzi takich jak ty. IdŸ do diab³a, ty...}
{224} {} {Szkoda, ¿e tego nie zrobiliœmy...}
{225} {} {Wiêc Garth stoi za tym wszystkim? Musimy go powstrzymaæ. Przekroczy³ liniê, której Stra¿nik nie mo¿e przekroczyæ. Czy ty to rozumiesz?}
{226} {} {Garth wariuje. Jest zbyt podejrzliwy. Najpierw pozby³ siê tych, którzy nie stwarzali du¿ych problemów. A teraz - nowych przybyszów, których nie lubi³. Zgadzam siê, to zasz³o za daleko. Mam nadziejê, ¿e wiesz, co robiæ.}
{227} {} {Dziêki, zrozumiem to. Jesteœ dobrym cz³owiekiem.}
{228} {} {Jednak nie ufam ci. Lepiej by³oby ciê teraz wyeliminowaæ...}
{229} {} {Muszê powiedzieæ wszystko w Kwaterze G³ównej Rangersów.}
{230} {} {Garth kaza³ mi ciê zabiæ, jeœli coœ wywêszysz. Przykro mi. Nic osobistego...}
{231} {} {Zamierzasz zabiæ Stra¿nika?}
{232} {} {Nie mam wyboru. Garth rozkaza³ ciê zatrzymaæ. Jeœli tego nie zrobiê to bêdzie Ÿle dla nas wszystkich.}
{233} {} {Có¿. Jesteœ po prostu g³upcem. I umrzesz g³upcem...}
{234} {} {Naprawdê zamierzasz zabiæ kobietê? Jesteœ okrutny!}
{235} {} {Cholera, nie podniosê rêki przeciwko kobiecie. Ale co mi zosta³o? Garth nie wybacza b³êdów, a ty nie powinnaœ mieszaæ siê w ten biznes...}
{236} {} {No dalej, zwierzaku, zaryzykuj i zrób co musisz.}

{240} {} {Co do... S³uchaj, nie chcê z tob¹ walczyæ. Ale Garth kaza³ ci przestaæ.}
{241} {} {Dobrze. Twoja w³ócznia nie mo¿e przebiæ pancerza wspomaganego. Mi³o s³yszeæ g³os rozs¹dku.}
{242} {} {Co zamierzasz zrobiæ? Zamierzasz nas wszystkich zabiæ, czy przekazaæ w³adzom?}
{243} {} {O tak. I bêdziesz pierwszy...}
{244} {} {Najpierw powiedz mi, co siê sta³o. Poni¿ej s¹ zw³oki ludzi. I nie zostali zabici przez bestie.}
{245} {} {Garth pozbywa siê obcych, których uwa¿a, ¿e nie warto tu mieæ. Na pocz¹tku rozwi¹zywa³ takie prawdziwe problemy. Ale teraz coœ w nim pêk³o i ka¿dego, kto wzbudzi podejrzenia, traktuje no¿em.}
{246} {} {Co za obrzydliwa historia. Uwolniê œwiat od ludzi takich jak ten Garth i ty...}
{247} {} {Masz coœ na niego? Pos³uchaj, musimy go powstrzymaæ.}
{248} {} {Robiê dla niego tylko brudn¹ robotê. Mam nadziejê, ¿e wiesz, co robiæ.}
{249} {} {Usi¹dŸ tutaj i nie wychylaj siê. Twoje szczêœcie, jeœli proces Rangersów jest sprawiedliwy.}
{250} {} {Wiem. Zabijê i ciebie i jego. Ty bêdziesz pierwszy.}

{260} {} {Czekaj, brzydalu. Widaæ, ¿e kochasz ka¿de szambo. Co Ty tutaj robisz?}
{1260} {} {Czekaj, brzydalu. Widaæ, ¿e kochasz ka¿de szambo. Co Ty tutaj robisz?}