{100} {} {Widzisz dziecko.}
{101} {} {Widzisz miejscowe dziecko. Pachnie ryb¹ i b³otem.}

{110} {} {Ranger Garth zabija ludzi takich jak ty.}
{111} {} {Nie dotykaj mnie.}
{112} {} {Z jakiej dziury pochodzisz, co?}
{113} {} {Mówisz jakoœ dziwnie.}
{114} {} {}
{115} {} {}
{116} {} {}
{117} {} {}
{118} {} {* ziewa *}
{119} {} {Zzz}

{120} {} {D³ugo tu jesteœ?}
{121} {} {Sk¹d jesteœ?}
{122} {} {Chcesz siê pobawiæ?}
{123} {} {Znasz jakieœ ciekawe miejsca w okolicy?}
{124} {} {Na dnie zatoki ¿yje potwór.}
{125} {} {Jeœli bêdziesz p³ywaæ w tej wodzie, urosn¹ ci rogi.}
{126} {} {Masz coœ smacznego?}
{127} {} {Ha, ta ryba jest zgni³a.}
{128} {} {Szukam czegoœ po¿ytecznego.}
{129} {} {}

{130} {} {To siê nazywa „motocykl”, co?}
{131} {} {Wow, czy to naprawdê mo¿e jeŸdziæ?}
{132} {} {Wiêc te¿ dowodzisz star¹ technologi¹, jak stary Rufus?}
{133} {} {Umiesz jeŸdziæ na tym motocyklu?}
{134} {} {Czy ten motor wie, jak ³owiæ ryby lub przewidywaæ pogodê?}
{135} {} {Myœlê, ¿e Rangersi te¿ powinni mieæ w³asne motory.}
{136} {} {Sk¹d masz motocykl?}