{100} {} {Widzisz dziecko.}
{101} {} {Widzisz miejscowe dziecko. Pachnie ryb¹ i b³otem.}
{102} {} {Dziêki, panie! To mi siê bardzo przyda.}
{1102} {} {Dziêki, pani! To mi siê bardzo przyda.}
{103} {} {Dziêki, panie. Ale mam ju¿ parê sanda³ów.}
{1103} {} {Dziêki, pani. Ale mam ju¿ parê sanda³ów.}
{104} {} {To by³o bardzo honorowe z twojej strony.}

{200} {} {Widzia³em ich! Powiedzia³em wszystko! To prawda! Och... Kim jesteœ? Te¿ kosmit¹?}
{201} {} {Kogo widzia³eœ?}
{202} {} {Kogo nazwa³eœ kosmit¹, ma³a rybko?}
{203} {} {Potwory! Mieszkaj¹ w akwedukcie i wype³zaj¹ noc¹. Sam to widzia³em! Teraz jest jasne, dlaczego nie wolno zchodziæ do akweduktu. Tam musi byæ ca³a masa tych potworów.}
{204} {} {Hmm.}
{205} {} {K³amiesz.}
{206} {} {Mówi³em ci, ¿e je widzia³em! S¹ ³yse i obrzydliwe, i wydaj¹ dziwne odg³osy. A jeœli wynurz¹ siê i nas zaatakuj¹? CO WTEDY?}
{207} {} {Uspokój siê, nic siê nie stanie, jeœli sam do nich nie pójdziesz.}
{208} {} {Zgadza siê. O czym myœl¹ w³adze lokalne?}
{209} {} {Có¿... naprawdê nie wiem. Mo¿e Garth ma plan. Jest twardy. Widzia³em nawet, jak sam schodzi³ do akweduktu. Garth niczego siê nie boi. Bêdzie nas chroni³ przed wrogami!}
{210} {} {Swoj¹ drog¹, co TY robi³eœ przy akwedukcie?}
{211} {} {Có¿... To jest... Szed³em. Ale nie mo¿na tam chodziæ, wiêc zosta³em ukarany i zmuszony do sortowania sieci alg. Och, s¹ takie brudne.}
{212} {} {Czy znalaz³eœ coœ interesuj¹cego?}
{213} {} {Nie. Chocia¿... Czy potrzebujesz kul? Znalaz³em je w pobli¿u akweduktu. Prawdopodobnie jeden z ³owców je upuœci³. Mogê wymieniæ je na coœ po¿ytecznego.}
{214} {} {Bêdê pamietaæ.}
{215} {} {Nie, te naboje s¹ prawdopodobnie i tak zbyt wilgotne by ich u¿ywaæ.}
{216} {} {S¹dz¹c po twoich bosych stopach, bêdziesz potrzebowaæ butów.}

{220} {} {Widzia³em ich! Powiedzia³em to samo! To prawda!}
{221} {} {Wierzê ci. Czeœæ.}

{230} {} {Czy to dlatego chodzisz boso?}
{231} {} {No tak. Kiedy zobaczy³em te potwory, natychmiast tu pobieg³em. Pobieg³em tak szybko, ¿e nie zauwa¿y³em, jak podar³em sanda³y. Teraz muszê poszukaæ innych butów.}
{232} {} {Mhm, znalaz³eœ coœ interesuj¹cego spaceruj¹c obok akweduktu?}