{100} {} {Widzisz osadnika.}
{101} {} {Widzisz typowego obywatela Akweduktu.}

{110} {} {Muszê odpocz¹æ.}
{111} {} {Musimy jutro rano sprawdziæ sieci.}
{112} {} {Hr-rr.}
{113} {} {Za póŸno na rozmowê.}
{114} {} {Co siê dzieje?}
{115} {} {Dlaczego do cholery budzisz ludzi w œrodku nocy?}
{116} {} {Znowu budzisz mnie w œrodku nocy...}
{117} {} {}
{118} {} {}
{119} {} {}

{120} {} {Wszyscy tutaj ju¿ o tobie wiedz¹. WyjdŸ.}
{121} {} {Nie ma tu miejsca dla kogoœ takiego jak ty.}
{122} {} {Wiemy, jak¹ jesteœ osob¹. Nie pasujesz tutaj.}
{123} {} {Wynoœ siê st¹d.}
{124} {} {Wynoœ siê, zanim Stra¿nicy wci¹gn¹ ciê na drzewo.}
{125} {} {Garth rozwali ci ³eb, jeœli bêdziesz przeszkadzaæ miejscowym.}
{126} {} {}
{127} {} {}
{128} {} {}
{129} {} {}

{130} {} {Witamy w akwedukcie.}
{131} {} {Mam nadziejê, ¿e zostaniesz tutaj.}
{132} {} {Hej, czeœæ.}
{133} {} {Mi³o ciê widzieæ.}
{134} {} {Chcesz zostaæ na noc?}
{135} {} {Mam trochê wolnego miejsca, nie wstydŸ siê.}
{136} {} {Czy przys³ali ciê Stra¿nicy?}
{137} {} {Osoby takie jak ty s¹ tutaj doceniane.}
{138} {} {Czy mo¿esz mi pomóc oczyœciæ sieci?}
{139} {} {Potrzebujemy tutaj ludzi takich jak Ty.}

{140} {} {Przepraszam, nowi ludzie s¹ zawsze podejrzani.}
{141} {} {Czego chcesz?}
{142} {} {S³uchaj, nic nie wiem i nic nie mam. Jasne?}
{143} {} {Lepiej mnie zostaw.}
{144} {} {Dzisiaj by³ ciê¿ki dzieñ, porozmawiamy póŸniej.}
{145} {} {Muszê ca³y dzieñ przechodziæ przez sieci.}
{146} {} {Zapach? Pochodzi z ryb i z wody. Jesteœmy do tego przyzwyczajeni.}
{147} {} {Potwór z Arizony mieszka gdzieœ na dnie Kolorado.}
{148} {} {Nie odchodŸ daleko, potwór z Arizony ¿yje w tej wodzie.}
{149} {} {Nie mogê znaleŸæ haczyka.}