{100} {} {Widzisz Ranger Agathê.}
{101} {} {Widzisz Stra¿nika-Weterana w zbroi bojowej.}
{102} {} {Swietna zbroja. Jestem prawie zazdrosna.}

# Pierwszy dialog
{200} {} {Cywilu, lepiej nie w³ócz siê po bazie bezczynnie. Masz pytanie? Skontaktuj siê z centrum informacyjnym. To jest ten barak przy drodze.}
{201} {} {Wiem.}
{202} {} {Spocznij, zwiadowco. Mi³o ciê widzieæ w naszej cytadeli. Zapraszam do zadawania pytañ.}
{203} {} {Dziêki, kapitanie.}
{204} {} {Uwaga, Stra¿niku! Skontaktuj siê ze mn¹ zgodnie ze statutem lub przejdŸ na wszystkie cztery strony. Nie mam czasu na takiego ¿ó³todzioba jak ty.}
{205} {} {Wygl¹da na to, ¿e moja reputacja ciê wkurza. Porozmawiamy?}
{206} {} {(Widzisz siln¹ kobietê w zbroi bojowej. Jej surowy wojskowy wygl¹d jest podkreœlony przez krótk¹, stoj¹c¹ fryzurê i powa¿ny g³os)}
{207} {} {Czy mogê siê z tob¹ skontaktowaæ?}

# Powtarzajacy siê dialog
{210} {} {Czego chcesz, wêdrowcze?}
{1210} {} {Czego chcesz, wêdrowcze?}
{211} {} {Czego chcesz, zwiadowco?}
{212} {} {Do widzenia.}

{213} {} {Och... (przygl¹da siê twojemu wygl¹dowi z przera¿eniem) Czy... szukasz czegoœ? Uwa¿aj, aby nikogo tu nie zaraziæ.}
{214} {} {Nie musisz siê tym martwiæ.}

{220} {} {Wiêc to ty podekscytowa³eœ kadetów swoim motocyklem? Sk¹d to masz?}
{1220} {} {Wiêc to ty podekscytowa³aœ kadetów swoim motocyklem? Sk¹d to masz?}
{221} {} {To moje trofeum.}
{222} {} {Przedmiot zdobyty krwi¹ w bitwie zas³uguje na szacunek. (z dum¹ poprawia swoj¹ zbrojê)}
{223} {} {Powinienem siê spodziewaæ, ¿e ci siê spodoba.}
{224} {} {Prezent.}
{225} {} {Có¿, skoro tak mówisz, mo¿na w to uwierzyæ.}
{226} {} {Tak.}
{227} {} {Czy mog³abyœ siê ze mn¹ przejechaæ, kochanie?}

#Pytania
{230} {} {Odpowiedz na kilka pytañ na swój temat.}
{231} {} {Nazywam siê Agatha, jestem prze³o¿onym zespo³u szkoleniowego.}
{232} {} {}
{233} {} {}
{234} {} {Wygl¹da na to, ¿e Wojownicy s¹ dla ciebie jak du¿a rodzina, a kadeci jak dzieci.}
{235} {} {Mo¿na tak powiedzieæ. Ale moje osobiste motywy nie maj¹ znaczenia, jeœli do tego siê to sprowadza.}
{236} {} {Pozwól, ¿e zadam jeszcze kilka pytañ.}
{237} {} {Sk¹d masz tê zbrojê bojow¹?}
{238} {} {Trofeum zdobyte podczas jednej z operacji bojowych. Musia³am j¹ przemalowaæ, ¿eby nie wziêto mnie za obcego.}
{239} {} {Co oznaczaj¹ te paski?}
{240} {} {S³u¿ba weterana, synu. Kiedy Stra¿nik wymierza sprawiedliwoœæ na Pustkowiach wystarczaj¹co d³ugo i wystarczaj¹co skutecznie, otrzymuje takie insygnia. Ja mam ju¿ wieloletnie doœwiadczenie.}
{241} {} {Co tu robisz?}
{242} {} {Ostatnio prowadzi³am kurs dla kadetów na m³odego ¿o³nierza.}
{243} {} {Weterani szkol¹ siê z nowymi?}
{244} {} {Strzelanie mamy ju¿ we krwi. Czas przekazaæ tê umiejêtnoœci m³odym.}
{245} {} {Dlaczego ogoli³aœ wszystkich kadetów na ³yso?}
{246} {} {Zebyœ mia³ o co pytaæ. I st³umiæ nadmiern¹ sk³onnoœæ m³odych ludzi do samouwielbienia.}
{247} {} {Psychologiczne t³umienie osobowoœci? Sprytnie.}
{248} {} {Nie t³umienie. Tylko zaszczepienie odpornoœci i samokontroli. Jest to równie¿ dobre dla higieny.}
{249} {} {Ok, nie bêdê siê k³óciæ.}

#Trening
{250} {} {Czy mogê wzi¹æ udzia³ w szkoleniu?}
{251} {} {Mo¿e od razu chcesz miniguna? Uczymy tylko naszych w³asnych kadetów. Nie pamiêtam, ¿ebyœ znalaz³ siê na ich liœcie.}
{252} {} {Pójdê wiêc.}
{253} {} {Nie tylko mo¿esz, ale tak¿e musisz. To prawda, ostrzegano mnie o twoim specjalnym statusie. Bêdziemy musieli zrobiæ krótki kurs dla m³odego Wojownika.}
{254} {} {Myœlê, ¿e jestem gotowy na kurs.}
{255} {} {Swietnie, ale od³ó¿my to szkolenie, mam teraz inne obowi¹zki.}
{256} {} {Zobaczmy. Podstawowa umiejêtnoœæ przetrwania to pierwsza rzecz, któr¹ ka¿dy tropiciel musi opanowaæ.}
{257} {} {Ok.}
{258} {} {Dalej s¹ umiejêtnoœci zwi¹zane z broni¹. Poruszymy trochê temat ka¿dego gatunku, ale ka¿dy tropiciel ma osobiste preferencje co do broni. Co wybierasz?}
{259} {} {}
{260} {} {Strzelanie z rewolwerów (lekkiej broni).}
{261} {} {Ciê¿ka broñ snajperska.}
{262} {} {Broñ miotana.}
{263} {} {Walka za pomoc¹ improwizowanych œrodków (walka wrêcz).}
{264} {} {Walka na no¿e (broñ bia³a).}
{265} {} {Ok, Stra¿niku! Biegnij na plac apelowy! Zobaczmy, jak szybko bêdziesz mieæ doœæ.}
{266} {} {Tak jest!}

# Historia osobista
{270} {} {Jak zosta³aœ Stra¿nikiem?}
{271} {} {Jak zosta³aœ Stra¿nikiem?}
{272} {} {Nie jestem ju¿ ma³¹ dziewczynk¹, która opowiada ³adne bajki, teraz zosta³a tylko brutalna prawda.}
{273} {} {Ok, rozumiem, nie ma problemu.}
{1273} {} {Ok, rozumiem, nie ma problemu.}
{274} {} {W takim razie chcê wiedzieæ.}
{275} {} {Czy naprawdê Ciê to interesuje? To stara historia. By³am dzieckiem, kiedy bandyci zaatakowali nasz obóz...}
{276} {} {Kontynuuj.}
{277} {} {Uch, nie teraz, porozmawiajmy innym razem.}
{278} {} {Uda³o mi siê ukryæ w ruinach i przeczekaæ oblê¿enie. Kiedy bandyci zakoñczyli swoje sprawy, nikt nie pozosta³ przy ¿yciu.}
{279} {} {Wow, to smutna historia.}
{280} {} {Dobrze jest siedzieæ w ciemnym k¹cie, kiedy nie mo¿esz nic zrobiæ.}
{281} {} {Na pocz¹tku by³am zdezorientowana. A potem siê zdenerwowa³am i obieca³am, ¿e pomszcze swoj¹ rodzinê.}
{282} {} {Czy uda³o siê?}
{283} {} {Zemsta na ca³ym gangu? O cholera.}
{284} {} {Posz³am na pustkowia i doskonali³am swoje umiejêtnoœci, szuka³am broni i zapasów, bada³am okolice i ostatecznie zabi³am wszystkich bandytów w ich legowisku, jednego po drugim, g³ównie za pomoc¹ pu³apek w³asnej roboty. Zajê³o mi to du¿o czasu, ale zrobi³am to.}
{285} {} {Niesamowite jest niszczenie gangu za pomoc¹ samych pu³apek i sztuczek.}
{286} {} {Pf, pu³apki s¹ dla s³abeuszy. Jednak by³aœ ma³a...}
{287} {} {Ale po ca³ym tym cierpieniu zda³am sobie sprawê, ¿e morderstwo pozostaje morderstwem. Sonora nie potrzebuje cz³owieka ze strzelb¹, ale prawa i porz¹dku. I tylko Wojownicy podzielali te same pogl¹dy. Po historii z bandytami bez zbêdnych ceregieli zabrali mnie do kadetów.}
{288} {} {Niez³a historia.}
{289} {} {Znajoma historia. Mój znajomy równie¿ ukrywa³ siê przed porywaczami. Spo³ecznoœæ mu tego nie wybaczy³a.}

#Cadet Presley
{300} {} {Dlaczego nie pozwalasz kadetowi Presleyowi wyruszyæ na misjê?}
{301} {} {Nawet jeœli chce trzymaæ karabin w d³oniach, potrzebuje niewiele arogancji, ¿eby go straciæ. Dotyczy to wielu kadetów.}
{302} {} {Wiêc jest zbyt kapryœny?}
{303} {} {Raczej ambitny i niecierpliwy. Tacy Stra¿nicy nie wytrzymuj¹ d³ugo i zwykle koñczy siê to bardzo Ÿle.}
{304} {} {Czemu mu nie odpuœcisz?}
{305} {} {I jeszcze czego? Nie mo¿esz robiæ Wojowników z nastolatków. Jeœli nie poradzi sobie nawet z tak¹ presj¹ i zasadami, nie bêdzie w stanie byæ pe³noprawnym Stra¿nikiem.}
{306} {} {Dlaczego nie pozwolisz mu siê sprawdziæ?}
{307} {} {Pozwoli³abym mu odejœæ, ¿eby w koñcu siê obudzi³ i otworzy³ oczy na œwiat. Ale nie mogê zmieniæ zdania na oczach pozosta³ych kadetów, ¿eby nie straciæ reputacji. Rozumiesz?}
{308} {} {Wiesz lepiej, jak wychowywaæ kadetów. Muszê iœæ.}
{309} {} {Wiêc pozwól mu iœæ ze mn¹ pod pretekstem konwoju. Chêtnie pomogê.}
{310} {} {Nie wiem, dlaczego chcesz siê tym zaj¹æ. Ale mo¿e to dobry pomys³. Przydzielê Presleya do twojej eskorty i zarz¹dzê zwrot sprzêtu.}
{311} {} {Dobrze, uczyni go to szczêœliwym.}
{312} {} {Tak po prostu.}
{313} {} {Gdzie jest kadet Presley? Jesteœ ostatni¹ osob¹, z która by³ widziany.}
{1313} {} {Gdzie jest kadet Presley? Jesteœ ostatni¹ osob¹, z która by³ widziany.}
{314} {} {Zgin¹³ na s³u¿bie.}
{315} {} {Cholera! Dlaczego zaufa³am takiemu idiocie! Wynoœ siê, inaczej nie mogê rêczyæ za siebie!}
{1315} {} {Cholera! Dlaczego zaufa³am takiej idiotce! Wynoœ siê, inaczej nie mogê rêczyæ za siebie!}
{316} {} {Uch...}

{320} {} {Czy wiesz, ¿e kwatermistrzowi brakujuje broni z magazynu?}
{321} {} {Tak. I oczywiœcie próbujesz rozgryŸæ t¹ sprawê, prawda? Ale wiesz co, nadszed³ czas, aby ten œmieciarz uporz¹dkowa³ rzeczy w swoich ciemnych, zakurzonych szafach. Poniewa¿ nie wierzê, ¿e moi kadeci mogliby cokolwiek ukraœæ.}
{322} {} {[Dalej.]}
{323} {} {I nie pozwolê nikomu ich winiæ. Rozumiesz to? Teraz muszê kontynuowaæ szkolenie.}
{324} {} {Oczywiœcie, nie ma problemu.}
{325} {} {No có¿.}