{100} {} {Widzisz kobietê.}
{101} {} {Widzisz kobietê w œrednim wieku. Jest wyczerpana d³ug¹ podró¿¹.}
{102} {} {Niech szczêœcie bêdzie z tob¹.}
{103} {} {Dranie!!! Co byœcie wszyscy zdechli!}
{104} {} {To koniec... Zostaw mnie, niech wilki mnie po¿r¹.}

# Dialog na mapie stra¿ników
{200} {} {Hej, ty! Natychmiast wezwij genera³a!}
{201} {} {Kobieto, przestañ krzyczeæ, dobrze ciê s³ychaæ.}
{202} {} {Coœ mylisz, jestem tu mimochodem.}
{203} {} {Tak, oczywiœcie, powiedz mi te¿, ¿e nie s³u¿ysz przeklêtym Rangersom! Na tych ziemiach nawet kojoty przytulaj¹ siê do silniejszych.}
{204} {} {Czy Rangersi jakoœ ciê zdenerwowali?}
{205} {} {Niew³aœciwe s³owo! I nie zostawiê tego tak po prostu. Jeœli genera³ nie przyjdzie tu odpowiedzieæ, sama wywalczê sobie drogê do niego.}
{206} {} {Znowu ty? Jeœli nie chcesz pomóc, lepiej zniknij mi z oczu.}
{207} {} {Zostañ tutaj, porozmawiam ze Stra¿nikami.}
{208} {} {Powiedz mi, co siê sta³o.}
{209} {} {Ci „orêdownicy prawa” stracili mojego mê¿a i zostawili mnie z dzieckiem na pustyni. W cudowny sposób uda³o nam siê tu dostaæ i przetrwaæ.}
{210} {} {Czy by³ winny?}
{211} {} {Winny? Tak, wszyscy na pustkowiach s¹ winni rozmaitych okrucieñstw, jeœli przestrzegasz g³upiego prawa, które tak ceni¹ Stra¿nicy. Ale to nie znaczy, ¿e teraz musimy wykonaæ egzekucje na wszystkich z rzêdu!}
{212} {} {Uch, rozumiem, co masz na myœli.}
{213} {} {Dlaczego potrzebujesz genera³a?}
{214} {} {Chcê mu spojrzeæ w oczy. Mo¿e nie wiedzieæ, co robi¹ jego poplecznicy, ale nadal ka¿ê mu odpowiadaæ za ich b³êdy i wyp³aciæ mi odszkodowanie.}
{215} {} {Odwa¿na decyzja.}
{216} {} {Czy to wszystko, o co chcia³eœ zapytaæ?}
{217} {} {Czy to Twoje dziecko?}
{218} {} {Tak. Jak mo¿esz myœleæ inaczej?}
{219} {} {Po prostu by³em ciekawy. Zapomnij.}

{220} {} {Nie mo¿esz tu zostaæ. Stra¿nicy nie chc¹ ciê chroniæ, a twoja reputacja nie pozwoli ci osiedliæ siê w s¹siednich osadach.}
{221} {} {Wiem! Ale gdzie powinniœmy teraz iœæ? Dooko³a pustynia, nie prze¿yjemy kolejnej takiej wyprawy. Mogê jednak spróbowaæ pojechaæ do Kalifornii... To jedyny sposób. Ale Stra¿nicy zablokowali jedyn¹ przeprawê przez rzekê!}
{222} {} {Mówi¹, ¿e w dole rzeki jest przejœcie. Ale to nie jest bezpieczne miejsce.}
{223} {} {Dok³adnie. Nie mam nawet pistoletu do ochrony przed wilkami i kretoszczurami. Nie mogê dostaæ siê na prom z dzieckiem bez pomocy.}
{224} {} {Bêdê ci towarzyszyæ. Przygotuj siê do wyprawy.}
{225} {} {Bêdê ci towarzyszyæ. Ale nie teraz.}

{226} {} {Stra¿nicy nie ¿yj¹.}
{227} {} {Rozumiem, ale to niczego nie zmienia. Nadal nie mo¿emy dostaæ siê do genera³a. Tama jest równie¿ pe³na Stra¿ników. Nie bêdziemy mogli nawet zbli¿yæ siê do cytadeli po drugiej stronie tamy. Albo zostaniemy ostrzelani przez snajperów, albo z³api¹ nas patrole.}
{228} {} {Genera³ nie ¿yje.}
{229} {} {Na pewno? To nie jest jakaœ ich sztuczka? Chocia¿ s³ysza³am ju¿ tê wiadomoœæ. Wygl¹da na to, ¿e naprawdê wyzion¹³ ducha. Wspaniale. Czujê siê lepiej. Ale nie wiem, co mam teraz zrobiæ.}

{230} {} {Hej podró¿niku. Ty te¿ próbujesz uciec z tego piek³a, prawda?}
{1230} {} {Hej, podró¿niku. Ty te¿ próbujesz uciec z tego piek³a, prawda?}
{231} {} {O czym ty mówisz?}
{232} {} {Prawdopodobnie.}
{233} {} {Wojownicy zrujnowali ¿ycie naszej rodziny. Nie chcê wchodziæ w szczegó³y. W koñcu dostali ju¿ to, na co zas³u¿yli, patrz¹c na tê tamê.}
{234} {} {[Dalej.]}
{235} {} {Hmm, nie wygl¹dasz na niebezpieczn¹ osobê. Musimy trzymaæ siê razem. Czy mo¿esz mi pomóc dostaæ siê na drug¹ stronê? W dole rzeki jest prom, ale bojê siê pójœæ tam bez opieki. Podobno w tych miejscach s¹ wilki.}
{236} {} {Ok, bêdê ci towarzyszyæ. Wychodzimy, teraz.}
{237} {} {Nie mogê ci teraz pomóc. Mo¿e póŸniej.}
{238} {} {Zmieni³eœ zdanie? ChodŸ ze mn¹. Po co ci te zdewastowane ziemie? W Kalifornii mo¿esz zapomnieæ o przesz³oœci i zacz¹æ wszystko od nowa.}
{1238} {} {Jednak zmieni³aœ zdanie? ChodŸ ze mn¹. Po co ci te zdewastowane ziemie? W Kalifornii mo¿esz zapomnieæ o przesz³oœci i zacz¹æ wszystko od nowa.}
{239} {} {[Dalej.]}
{240} {} {Wiesz, ja te¿ jestem w konflikcie z Rangersami.}
{241} {} {Czy to powinno sprawiæ, ¿e poczujê siê lepiej? Hmm. Pos³uchaj, skoro p³yniemy na tej samej ³odzi, powinniœmy pomagaæ sobie nawzajem, by prze¿yæ.}

# Na mapie promu
{300} {} {Porozmawiamy, kiedy dotrzemy na prom. Teraz mo¿emy przyci¹gn¹æ wilki naszym g³osem.}
{301} {} {Masz racjê, od³ó¿my na razie rozmowê.}
{302} {} {Rozumiem.}

{303} {} {Nie podoba mi siê sposób, w jaki patrzysz na moje dziecko. Nie próbuj go straszyæ, bo inaczej nie zobaczysz ju¿ niczego do koñca ¿ycia.}
{304} {} {Nic takiego nie przysz³o mi do g³owy!}
{305} {} {Gro¿enie mi nie le¿y w twoim najlepszym interesie, kobieto.}

{310} {} {Jak masz na imiê kobieto?}
{311} {} {Nazywam siê Cecilia, a to jest mój syn.}
{312} {} {Twój syn chyba nie odziedziczy³ twoich cech.}
{313} {} {Poniewa¿ jest adoptowany. Znalaz³am go w ruinach i nie mog³am przejœæ obok.}
{314} {} {Czy twój m¹¿ naprawdê by³ przestêpc¹?}
{315} {} {Nie pyta³am, sk¹d bierze jedzenie i sk¹d bierze kapsle. Ale by³o oczywiste, ¿e okrada³ podró¿ników i rolników. W ten sposób chroni³ rodzinê. Musieliœmy jakoœ przetrwaæ. Gorzej by³o w Phoenix, by³ zmuszony do wykonania znacznie brudniejszej pracy.}
{316} {} {Uciek³aœ z Phoenix?}
{317} {} {Tak... Wielkie miasto. Wiele osób, ma³o zasobów. Na pustkowiach jesteœ szczery z losem, ale w mieœcie zawsze musisz byæ po czyjejœ stronie i spe³niaæ czyjeœ kaprysy.}
{318} {} {Teraz nienawidzisz Rangersów?}
{319} {} {Oczywiœcie.}
{320} {} {Staraj¹ siê, aby historie takie jak Twoja nie mia³y miejsca.}
{321} {} {Ale siê sta³a. Z ich winy. Nie mo¿na tego naprawiæ.}
{322} {} {Moja wioska te¿ by tego nie pochwali³a.}
{323} {} {Hmm, w naszej Villi ka¿dy ch³op równie¿ jest poni¿ej wspólnoty i spe³nia czyjeœ kaprysy. Ale to nie to samo.}
{324} {} {To godne pochwa³y.}
{325} {} {Powinienem by³ ostrzec z wyprzedzeniem.}

{330} {} {Prom jest gotowy do wyp³yniêcia. WejdŸ na platformê, ja ciê przeprawiê.}
{331} {} {Jestem ci niezmiernie wdziêczna. Nie wszyscy by nam pomogli, zw³aszcza na ziemiach Stra¿ników. Ale co ciê tu trzyma? Pojedziesz z nami do Kalifornii?}
{332} {} {Jeszcze nie mogê. Mam zobowi¹zania wobec rodziny i domu.}
{333} {} {Rozumiem. Nieczêsto trafia siê na tak z¿yte wspólnoty, ¿e ktoœ chce zostaæ i sp³aciæ d³ug. Powodzenia. Dziêki za wszystko.}
{334} {} {[Dalej.]}
{335} {} {Przepraszam, ale nie mam ci jak podziêkowaæ. Ale jeœli zdarzy ci siê byæ w Phoenix, powiedz o mnie barmanowi w kasynie, mo¿e da ci zni¿kê. A teraz do widzenia.}
{336} {} {[Wyœlij rodzinê na drug¹ stronê]}