{100} {} {Widzisz dziecko.}
{101} {} {Widzisz chude dziecko o s³abej woli. Wygl¹da na to, ¿e wiele przeszed³.}

{103} {} {Nienawidzê ciê!}
{104} {} {Zostaw mnie! Nie dotykaj! IdŸ st¹d!}
{105} {} {Wygl¹da na to, ¿e bardzo przestraszy³eœ tego dzieciaka.}

{106} {} {Mama mówi, ¿e wkrótce pójdziemy do nieba.}
{107} {} {Chcê jeœæ.}
{108} {} {Chcê iœæ do domu.}
{109} {} {Nienawidzê Rangersów.}