{100} {} {Widzisz genera³a Rangersów.}
{101} {} {Widzisz silnego, siwego starca, który widzia³ ¿ycie we wszystkich jego postaciach.}
{102} {} {Przyzwyczai³em siê do rozmowy z prawdziwymi ludŸmi, a nie robotami. Rozumiesz?}
{103} {} {Zegnaj Rangersie. Twoje idea³y okaza³y siê... nierealne.}
{104} {} {Przepraszam, ale ta pani musi siê och³odziæ.}
{105} {} {Mi³o widzieæ ciê zdrowego. Ale nie mam teraz czasu na rozmowê - z³o zasiane przez Bractwo wci¹¿ b³yszczy na pustkowiu.}

# Pierwszy dialog
{200} {} {Powiedziano mi, ¿e jakiœ ch³op potrzebuje spotkania ze mn¹ w wa¿nej sprawie. Ale to zwiadowcy i ambasadorzy zwykle zajmuj¹ siê kontaktami zewnêtrznymi. Mam wiêc nadziejê, ¿e to naprawdê coœ waznego.}
{1200} {} {Powiedziano mi, ¿e jakaœ ch³opka potrzebuje spotkania ze mn¹ w wa¿nej sprawie. Ale to zwiadowcy i ambasadorzy zwykle zajmuj¹ siê kontaktami zewnêtrznymi. Mam wiêc nadziejê, ¿e to naprawdê coœ waznego.}
{201} {} {[Dalej.]}
{202} {} {Wiêc dlaczego tu jesteœ?}
{203} {} {Wiesz, teraz zdajê sobie sprawê, ¿e nie mam tu nic do roboty. To by³ b³¹d. Odejdê, a Ty o mnie zapomnisz.}
{204} {} {Ten ¿art nie brzmi œmiesznie.}
{205} {} {Mówiê powa¿nie. Przepraszam, ¿e przeszkadzam.}
{206} {} {Wiesz, mam do ciebie wiele pytañ.}

# Powtarzajacy siê dialog
{210} {} {S³ucham.}
{211} {} {Do widzenia.}
{212} {} {Niebiosa, s¹dz¹c po twoim wygl¹dzie, wiele wynios³eœ z bezlitosnego pustkowia. Przykro mi.}
{213} {} {Dziêki, generale, za mi³e s³owa. Wiêkszoœæ by mnie po prostu przegoni³a.}
{214} {} {Nie potrzebujê litoœci. Spójrz na siebie, staruszku.}
{215} {} {Raport, Stra¿niku.}

# Rodzina przestepcza
{220} {} {Pewna wœciek³a kobieta za¿¹da³a spotkania.}
{221} {} {Tak, zosta³em poinformowany. Nieskoñczenie wspó³czujê takim ludziom, ale nic nie da siê zrobiæ. Rodziny przestêpców zawsze by³y piêtnowane, nawet w Starym Swiecie.}
{222} {} {Musi istnieæ sposób na rozwi¹zanie konfliktu.}
{223} {} {Moje wyjœcie niczego nie zmieni. Ta kobieta zawsze bêdzie nienawidziæ Rangersów, bez wzglêdu na to, ile dobrego dla niej zrobimy. W s¹siednich osadach miejscowi nie dadz¹ jej ¿yc, jeœli dowiedz¹ siê o mrocznej przesz³oœci jej mê¿a.}
{224} {} {Kontynuuj.}
{225} {} {Masz ciekawy punkt widzenia.}
{226} {} {Obawiam siê, ¿e jedynym wyjœciem dla tej rodziny jest opuszczenie ziem Sonory i udanie siê na wschód do Kalifornii, aby zacz¹æ od nowa.}
{227} {} {Spróbujê j¹ do tego przekonaæ.}
{228} {} {Prawdopodobnie nienajgorszy pomys³.}

# Lone Ranger w Flagpool
{230} {} {Co Ranger Keruk robi w Flagpool?}
{231} {} {(wzdycha) Wiedzia³em ¿e bêd¹ problemy. Sztab generalny by³ przeciwny sabota¿owi w Flagpool, ale jeden Stra¿nik mia³ osobiste ambicje ponad statutem. Trudno go za to winiæ.}
{232} {} {Usprawiedliwiasz go?}
{233} {} {Keruk doœwiadczy³ zniewolenia jego osady w przesz³oœci. NajwyraŸniej znalaz³ sposób w Flagpool, aby odzyskaæ równowagê po tym wydarzeniu. Pozwoliliœmy mu odejœæ, aby móg³ zrozumieæ w³asne ¿ycie i znaleŸæ spokój ducha.}
{234} {} {Zamierzasz go stamt¹d wyci¹gn¹æ?}
{235} {} {Zawrócic jednego z naszych najlepszych strzelców? Musi byæ ku temu naprawdê dobry powód.}
{236} {} {Myœlê, ¿e masz racjê, generale. Nie powinieneœ go stamt¹d wyci¹gaæ, dopóki sam nie zechce.}
{237} {} {Nie wierzê w³asnym uszom! Czy tak mówi genera³? To wszystko, odchodzê st¹d.}
{238} {} {On mœci siê na ka¿dym. Jego dzia³ania szkodz¹ nawet zwyk³ym pokojowym kolonistom.}
{239} {} {Nie obchodz¹ mnie jego problemy. Po prostu go stamt¹d wyci¹gnij.}
{240} {} {To wszystko zmienia. Wygl¹da na to, ¿e sytuacja zasz³a za daleko.}
{241} {} {Jesteœ genera³em. Nie sprzeciwi siê twojemu rozkazowi.}
{242} {} {Najprawdopodobniej. Przeka¿ mu rozkaz powrotu do bazy, jeœli znajdziesz siê w pobli¿u. Utrzymuje ciszê radiow¹ i z jakiegoœ powodu unika pozosta³ych Stra¿ników.}
{243} {} {Tak jest!}
{244} {} {Tylko jeœli bêdê w pobli¿u.}

#Syuz Villas
{250} {} {Czasy s¹ ciê¿kie w mojej rodzinnej wiosce. Potrzebujemy pomocy Rangersów.}
{251} {} {Ciê¿kie czasy... To mo¿na powiedzieæ o prawie ka¿dej osadzie w Arizonie i Kalifornii. Ale w przeciwieñstwie do zwyk³ych ludzi mamy mo¿liwoœæ walki o prawa ludzi na pustkowiu.}
{252} {} {[Dalej.]}
{253} {} {Utrzymanie porz¹dku wymaga znacznych inwestycji w szkolenie zwiadowców, wyposa¿enie patroli i zasobów, rozpoznania i operacji bojowych. Nie ka¿dy mo¿e zainwestowaæ w taki sojusz, ale staramy siê ka¿demu odpowiadaæ.}
{254} {} {Myœlê, ¿e Villa nie bêdzie mia³a problemu z zaopatrzeniem ciê w ¿ywnoœæ i ceramikê.}
{255} {} {Wiesz, naprawdê nie mamy nic do zaoferowania. Wygl¹da na to, ¿e ten zwi¹zek nie wypali.}
{256} {} {Wiêc bierzecie coœ za swoj¹ ochronê?}
{257} {} {Oczywiœcie. To rodzaj podatku od bezpieczeñstwa - normalna praktyka w Starym Swiecie.}
{258} {} {A jeœli ludnoœæ nie ma z czego p³aciæ podatku?}
{259} {} {Wiemy, jak skorzystaæ na ka¿dej wspó³pracy. Niektórzy mog¹ budowaæ mieszkania, inni uprawiaæ roœliny, a jeszcze inni s¹ dobrymi kadetami. Przy odpowiednim podejœciu ka¿dy mo¿e byæ przydatny dla spo³eczeñstwa.}

{260} {} {Villa... Wojownicy zawsze szanowali wasz¹ niezale¿noœæ. Ale wy zawsze trzymaliœcie siê siê z dala od reszty œwiata. Kiedy potrzebowaliœmy jedzenia w chudych latach, odpêdzaliœcie nas. A teraz to wy prosicie o pomoc. Powiedz mi, kto ciê do nas wys³a³?}
{261} {} {Rada spo³ecznoœci zdecydowa³a, ¿e nadszed³ czas, aby zawrzeæ sojusz.}
{262} {} {Nikt. Wielu ch³opów zosta³o zniewolonych i zabranych do Flagpool.}
{263} {} {Nikt. Wielu ch³opów zosta³o zniewolonych i zabranych do innego miasta.}
{264} {} {Jestem tutaj bez zgody spo³ecznoœci.}

{270} {} {Ah tak... Có¿, sojusz z Vill¹ by³by bardzo pomocny, poniewa¿ potrzebujemy teraz jedzenia bardziej ni¿ kiedykolwiek. Ale obawiam siê, ¿e arogancja twoich krewnych zepsuje krew naszych ¿o³nierzy.}
{271} {} {Trudno siê z tym nie zgodziæ. Czy jesteœ gotowy, aby nam pomóc?}
{272} {} {Nie obchodz¹ mnie twoi Wojownicy. Interesuje mnie tylko uratowanie Villi.}
{273} {} {Obawiam siê, ¿e to nie jest najlepszy czas na to. Na froncie po³udniowo-wschodnim s¹ du¿e problemy, wszystkie nasze si³y rzuci³y siê w tym kierunku.}
{274} {} {Problemy to moje ma³e hobby, generale.}
{275} {} {Porozmawiaj z Komandorem Helfordem. Mo¿e przeznaczy ludzi na pomoc w Villi. A potem omówimy warunki umowy... jeœli Twoja spo³ecznoœæ naprawdê tego chce.}
{276} {} {Dziêki, generale. Porozmawiam z Helfordem.}
{277} {} {Jeszcze nie. Teraz bêdziesz musia³ byæ nasz¹ praw¹ rêka w negocjacjach z ch³opami. Twoim zadaniem jest przekonanie ich o naszej ¿yczliwoœci i potrzebie sojuszu.}
{278} {} {Zaden problem.}
{279} {} {Obieca³eœ pomóc. Dlatego niektórzy wieœniacy nadal s¹ w niewoli.}

{280} {} {Komandor Helford zatwierdzi³ moj¹ proœbê o ochronê Villi.}
{281} {} {(przytakuje g³ow¹ i chwilê siê zastanawia) Czasy siê zmieniaj¹...}
{282} {} {Uch, co?}
{283} {} {[Pos³uchaj]}
{284} {} {Wczeœniej wieœniacy szukali izolacji i odpêdzali Stra¿ników. Ale czasy siê zmieniaj¹. I zmieniasz siê wraz z nimi, nie chc¹c. Myœlê, ¿e czas zapomnieæ o ró¿nicach z przesz³oœci.}
{285} {} {Wiêc jesteœ gotowy na sojusz?}
{286} {} {Wydam rozkazy komandorowi Helfordowi, aby zebra³ eskadrê i przeniós³ j¹ do twojej doliny. Porozmawiaj z nim o szczegó³ach. Teraz bêdziesz musia³ byæ nasz¹ praw¹ rêk¹ w negocjacjach z ch³opami. Kiedy Twoja spo³ecznoœæ bêdzie gotowa, oficjalnie podpiszemy umowê.}
{287} {} {Dziêki, Ogólne}
{288} {} {Niestety, kilku naszych ludzi nadal jest przetrzymywanych w niewoli w innym mieœcie.}
{289} {} {Czy mówisz o kopalniach Flagpool? Znamy tê sytuacjê i od dawna próbujemy j¹ naprawiæ. Có¿, myœlê, ¿e mo¿emy wykupiæ niektórych twoich ludzi z niewoli. Twoi companeros tribales wkrótce wróc¹ do domu.}
{290} {} {Sk¹d tyle o nas wiesz?}
{291} {} {Zbieramy informacje o ka¿dej osadzie na pustkowiach. To czêœæ naszej pracy. Poza tym lider Twojej spo³ecznoœci ju¿ raz nas odwiedzi³... Jak mia³ na imiê? Andy... nie, Andres Tejada.}
{292} {} {To mój ojciec! Nie wiedzia³em, ¿e odchodzi³ tak daleko od spo³ecznoœci.}
{1292} {} {To mój ojciec! Nie wiedzia³am, ¿e odchodzi³ tak daleko od spo³ecznoœci.}
{293} {} {Tak. Niestety, te negocjacje do niczego nie doprowadzi³y.}

{294} {} {Villa jest gotowa zawrzeæ z tob¹ sojusz.}
{295} {} {Bardzo dobrze. Oœwiadczam, ¿e od dziœ nasz uk³ad jest kompletny. Wróæ do Villi i œwiêtuj ten dzieñ z ca³¹ swoj¹ spo³ecznoœci¹.}
{296} {} {Ok.}
{297} {} {Najpierw zakoñcz misjê. Wtedy porozmawiamy.}
{298} {} {Dobrze.}

#Jackals
{300} {} {Porozmawiajmy o Szakalach.}
{301} {} {Szakale s¹ jednym z bol¹cych odcisków na ciele tej ziemi. O czym konkretnie chcia³eœ porozmawiaæ?}
{302} {} {Znam lokalizacjê ich g³ównej bazy. Uda³o mi siê nawet obejrzeæ j¹ od wewn¹trz.}
{303} {} {Bardzo w¹tpliwe, ale intryguj¹ce stwierdzenie. Nikomu jeszcze nie uda³o siê znaleŸæ tego miejsca, a do tego wydostaæ siê stamt¹d ¿ywym.}
{304} {} {A co z uratowanym Stra¿nikiem?}
{305} {} {Czy to twoja zas³uga? Có¿, Stra¿nik Jackson nie by³ jeszcze zbyt doœwiadczony - w drodze powrotnej zgubi³ siê i b³¹ka³ po pustyni przez d³ugi czas, a¿ znalaz³ jedn¹ z naszych opuszczonych placówek. Nigdy nie poznaliœmy dok³adnych wspó³rzêdnych od niego, a przeczesywanie ca³ego niebezpiecznego obszaru w poszukiwaniu ich nor by³o zbyt ryzykowne.}
{306} {} {Okazuje siê, ¿e nawet komandosowi zale¿y przede wszystkim na przetrwaniu...}
{307} {} {Zaufaj mi. Jestem dla Ciebie jedynym Ÿród³em informacji.}
{308} {} {Wiêc gdzie jest ta baza?}
{309} {} {Na granicy pustyn Mojave i Sonora, na pó³noc od Villi.}
{310} {} {Muszê sprawdziæ mapy. Poczekaj chwilê.}
{311} {} {Tak, to brzmi jak prawda. Myœlê, ¿e powinniœmy tam przeprowadziæ rekonesans. A kiedy baza zostanie znaleziona... zniszczymy j¹.}
{312} {} {Swietny plan. Szakale nie zas³uguj¹ na swoje miejsce w s³oñcu. Zniszczê je wszystkie!}
{313} {} {Ok. W tej operacji przyda siê nam przewodnik. Udzia³ pozwoli ci na zbieranie trefeów. Zgadzasz siê nam pomóc?}
{1313} {} {Ok. W tej operacji przyda siê nam przewodnik. Udzia³ pozwoli ci na zbieranie trefeów. Zgadzasz siê nam pomóc?}
{314} {} {Tak.}
{315} {} {Nie.}
{316} {} {Wiêc muszê... zabijaæ?}
{317} {} {Podoba mi siê twoja postawa. We wskazanym przez Ciebie miejscu bêdzie czeka³ oddzia³. IdŸ tam natychmiast.}
{1317} {} {Podoba mi siê twoja postawa. We wskazanym przez Ciebie miejscu bêdzie czeka³ oddzia³. IdŸ tam natychmiast.}
{318} {} {Podró¿ nie jest ³atwa. Czy mo¿esz mi to w jakiœ sposób u³atwiæ?}
{319} {} {Tak siê stanie, generale!}
{320} {} {Skontaktuj siê z patrolami. Zabior¹ ciê do oddzia³u.}
{321} {} {Przykro to s³yszeæ. Có¿, jak zwykle wszystko zrobimy sami. Dziêki za informacje, mo¿esz iœæ.}
{322} {} {Zmieniam zdanie! Pozwól mi uczestniczyæ w ataku.}
{323} {} {Do widzenia.}
{324} {} {Mo¿esz po prostu tam staæ i patrzeæ... Patrzeæ, jak gin¹ twoi wybawcy i obroñcy. Albo mo¿esz chwyciæ za broñ i przynajmniej im w czymœ pomóc. No to zgadzasz siê?}
{1324} {} {Mo¿esz po prostu tam staæ i patrzeæ... Patrzeæ, jak gin¹ twoi wybawcy i obroñcy. Albo mo¿esz chwyciæ za broñ i przynajmniej im w czymœ pomóc. No to zgadzasz siê?}
{325} {} {Có¿, wiesz lepiej, co robiæ dalej.}
{326} {} {Ok. Wiêc sami sobie z tym poradzimy. Dziêki za informacje.}
{327} {} {Mi³o siê przydaæ.}
{1327} {} {Mi³o siê przydaæ.}

{330} {} {Nie œpiesz siê. Szakale s¹ sk³onne zawrzeæ sojusz z obcymi, jeœli to rozwi¹¿e ich problem z g³odem.}
{331} {} {Co? Ci dzicy ju¿ wypili tyle krwi ze Stra¿ników i okolicznych osad, ¿e negocjacje s¹ wykluczone!}
{332} {} {Myœlê, ¿e warto spróbowaæ z nimi negocjowaæ. Prowadz¹ tak agresywny tryb ¿ycia tylko z powodu powszechnego g³odu.}
{333} {} {Hmm. W takim razie, jeœli ci to nie przeszkadza, wyjaœnij mi, jakie s¹ zalety sojuszu z dzikimi kanibalami?}
{334} {} {S¹ zdezorganizowani i rozproszeni po pustkowiu. Niszcz¹c g³ówn¹ bazê, tylko zdenerwujesz pozosta³e klany. Ten spór bêdzie trwa³ przez pokolenia.}
{335} {} {Myœl o walce z dzikusami jest bardziej irytuj¹ca ni¿ przera¿aj¹ca. Có¿, spróbujemy dyplomacji. Byæ mo¿e takie podejœcie zjednoczy i uspokoi klany Szakali. Dziêki za informacje. Mo¿esz iœæ.}
{336} {} {W porz¹dku, generale. Wrócê do Szakali i porozmawiam o zbli¿aj¹cych siê negocjacjach.}
{1336} {} {W porz¹dku, generale. Wrócê do Szakali i porozmawiam o zbli¿aj¹cych siê negocjacjach.}
{337} {} {Rzeczywiœcie - ostatni raz próbowali mnie zabiæ i po¿reæ. Nie s¹dzê, ¿ebym móg³ siê z nimi ponownie dogadaæ.}
{338} {} {Nie. Te szakale nie zas³uguj¹ na swoje miejsce w s³oñcu. Trzeba je wszystkie wybiæ!}

{340} {} {Chcê zg³osiæ zbrodnie Stra¿nika Gartha.}
{341} {} {Stra¿nika akweduktu? Umieœciliœmy go tam w celu emerytury. Jakie zbrodnie pope³ni³?}
{342} {} {Liczne zabójstwa uchodŸców motywowane nieufnosci¹ do obcych. Wrzuci³ ich cia³a do akweduktu.}
{343} {} {Czy mo¿esz je pokazaæ? W takim wypadku czeka nas wielka próba. Zabierzemy Gartha do aresztu. Dziêki za informacje... chocia¿ s¹ one przyt³aczaj¹ce. Szczególnie w tak trudnym czasie.}
{344} {} {Tak, rozumiem... Do widzenia, generale.}

# Tytul Ranger
{350} {} {Chcê do³aczyæ do Waszych szeregów.}
{351} {} {Chwalebny zapa³. Ale na tytu³ Rangersa trzeba sobie zapracowaæ. Wielu kadetów szkoli siê i bierze udzia³ w misjach przez lata, aby zdobyæ odznakê. Jakie zas³ugi mo¿esz wymieniæ?}
{352} {} {Nie mam nic do powiedzenia.}
{353} {} {Tak myœla³em. Do³¹cz do korpusu kadetów i s³u¿ przez kilka lat na rzecz naszej misji.}
{354} {} {Pomyœlê o tym.}
{355} {} {Pozwól mi poœwiêciæ wiêcej twojego czasu, generale.}
{356} {} {Czy jest szybszy sposób?}
{357} {} {Hmm. Porozmawiaj z dowódc¹ Helfordem, od dawna szuka³ rekrutów do zadañ specjalnych.}
{358} {} {Pomyœlê o tym.}
{359} {} {Tak, to jest powa¿ne osi¹gniêcie. Ale to nie wystarczy do rangi Stra¿nika.}
{360} {} {Zniszczy³em plemiê Szakali.}
{1360} {} {Zniszczy³am plemiê Szakali.}
{361} {} {Z moj¹ pomoc¹ zawar³eœ sojusz z Szakalami.}
{362} {} {Dziêki mnie handel niewolnikami w Flagpool to przesz³oœæ.}
{363} {} {Uwolni³em niewolników w Flagpool.}
{1363} {} {Uwolni³am niewolników w Flagpool.}
{364} {} {Uda³o mi siê rozwi¹zaæ konflikt w San Brahmin na korzyœæ Stra¿ników.}
{365} {} {Zniszczy³em Katedrê Ognia w Phoenix.}
{1365} {} {Zniszczy³am Katedrê Ognia w Phoenix.}
{366} {} {Zniszczy³em Bractwo Stali.}
{1366} {} {Zniszczy³am Bractwo Stali.}
{367} {} {Dziêki mnie ekspansja Blacharzy zosta³a zatrzymana.}
{368} {} {Z moj¹ pomoc¹ Partia Wyzwolenia wypêdzi³a Aarona.}
{369} {} {[CHIT: Zas³uguje na ten tytu³, generale]}
{370} {} {Có¿, taka lista budzi zaufanie. Pozwól mi rzuciæ okiem na raport z twoich dzia³añ... Tak, nasi zwiadowcy zbieraj¹ informacje o niektórych „promieniuj¹cych” osobowoœciach. Nie martw siê, to tylko czêœæ rutynowych dzia³añ.}
{371} {} {Hmm. W porz¹dku...}
{372} {} {Wygl¹da na to, ¿e twoja reputacja na Pustkowiach zosta³a zrujnowana przez twoje dzia³ania. Wielu uwa¿a ciê za... niewystarczaj¹co przyzwoit¹ osobê.}
{373} {} {Sam rozumiesz tamtejsz¹ moralnoœæ. Nie zadowolisz wszystkich.}
{374} {} {Czy Stra¿nicy naprawdê bior¹ pod uwagê opinie brudnych krêtaczy? Nie rozœmieszaj mnie.}
{375} {} {Niektórzy Stra¿nicy negatywnie oceniaj¹ twoj¹ osobowoœæ. Nie chcê przez to powiedzieæ, ¿e jest to powa¿ne wykroczenie, ale czasami pos³uchanie innych nie zaszkodzi.}
{376} {} {Z czasem pomyœl¹ o mnie lepiej.}
{377} {} {Ja te¿ nie jestem zadowolony z niektórych Stra¿ników. Ale nie biegnê od razu z raportem do genera³a. A to dziwki...}
{378} {} {Mówi siê o twoim po³¹czeniu z bandytami miejskimi. Czasami powinieneœ trzymaæ siê z daleka od niektórych typów.}
{379} {} {To nie s¹ Ÿli ludzie, zaufaj mi, generale.}
{380} {} {Kto jest tym z³ym? JA? Niech odwa¿¹ mi siê powiedzieæ to osobiœcie.}
{381} {} {Mówi¹, ¿e jesteœ cz³onkiem Wyznawców Ognia. To nie jest najlepsza rekomendacja.}
{382} {} {Wojownicy potrzebuj¹ w³asnego cz³owieka w tym koœciele.}
{383} {} {To smutne, ¿e nie zgadzasz siê z nasz¹ wiar¹. Powinieneœ pokutowaæ przed Swiêtym Ogniem.}
{384} {} {Tutaj jest napisane, ¿e jesteœ czêœci¹ kontrowersyjnej organizacji o nazwie Bractwo Stali.}
{385} {} {Tak. Kiedyœ wyda³o mi siê, ¿e to dobry pomys³. Ale nie teraz.}
{386} {} {O tak. A Stra¿nicy powinni traktowaæ tê „organizacjê” z ca³ym szacunkiem.}
{387} {} {Jak mo¿esz sobie wyobraziæ, przy takich rekomendacjach nie mogê ciê przyj¹æ w nasze szeregi. Musisz zdobyæ wiêksze zaufanie.}
{388} {} {Nie ma problemu, generale, nic nie zniszczy mojej pewnoœci siebie.}
{389} {} {I tak nie chcê tu nawet wracaæ.}
{390} {} {Hmm. Takie sytuacje s¹ wyj¹tkowe. Tylko nielicznym uda³o siê zdobyæ odznakê, omijaj¹c wieloletnie ciê¿kie treningi. Ale cieszê siê, ¿e uda³o Ci siê awansowaæ do rangi Rangersa.}
{391} {} {Wiêc mogê dostaæ odznakê?}
{392} {} {To dla mnie zaszczyt. Zawsze stawiam na swoim.}
{393} {} {Czy jesteœ gotowy przyj¹æ ten ciê¿ar? Przysiêgnij, ¿e bêdziesz przestrzegaæ Prawa i Porz¹dku i nie splamisz honoru Rangersów.}
{1393} {} {Czy jesteœ gotowa przyj¹æ ten ciê¿ar? Przysiêgnij, ¿e bêdziesz przestrzegaæ Prawa i Porz¹dku i nie splamisz honoru Rangersów.}
{394} {} {Przysiêgam!}
{395} {} {Swietnie. Noœ t¹ odznakê z dum¹. I porozmawiaj z kwatermistrzem, on da Ci podstawowe wyposa¿enie. W miêdzyczasie przygotujê dokumenty do rejestracji.}
{396} {} {Dziêki, generale!}

#Pytania
{400} {} {Czy mogê zadaæ kilka pytañ?}
{401} {} {Staraj siê tego nie przeci¹gaæ. Mam ma³o czasu na bezczynne gadanie.}
{402} {} {Masz racjê, doœæ gadania.}
{403} {} {Pozwól, ¿e zadam ci inne pytanie.}

{410} {} {Jak zosta³eœ Rangersem?}
{411} {} {Przeszed³em wszystkie kamienie milowe w rozwoju Stra¿nika i uczciwie awansowa³em do stopnia genera³a.}
{412} {} {Prawdopodobnie du¿o podrózowa³eœ, prawda?}
{413} {} {O tak, by³em w ró¿nych czêœciach po³udniowego zachodu, w tym w Los Angeles, Las Vegas i Phoenix. Wszêdzie te same problemy - g³ód, dewastacja i bezprawie.}

{420} {} {Czy mo¿esz mi opowiedzieæ o tym miejscu?}
{421} {} {To g³ówna baza Rangersów w Arizonie. Elektrownia s³u¿y jako cytadela, a tama to twierdza. Jak ju¿ wiesz, na zewn¹trz znajduje siê centrum informacyjne i poligon.}
{422} {} {Wiêc s¹ inne placówki?}
{423} {} {Tak. Istnieje kilka takich du¿ych fortów w Nevadzie i Kalifornii. Utrzymujemy z nimi kontakt, ale ka¿dy ma swoje w³asne zasady i podstawy.}
{424} {} {Jaka jest misja Stra¿ników?}
{425} {} {Wprowadzamy Prawo i Porz¹dek do tego chaotycznego œwiata. Przede wszystkim oznacza to ochronê osad i tras karawan przed bandytami i mutantami. Ale obrona to tylko pierwsza rzecz.}
{426} {} {[Dalej.]}
{427} {} {Mieszkañcy, którzy do nas do³¹czaj¹, s¹ zobowi¹zani do przestrzegania prawa, p³acenia podatków i wykonywania po¿ytecznej pracy. Takiej jak uprawa roœlin lub polowanie.}
{428} {} {Dlaczego tama wody Kolorado?}
{429} {} {(wzdycha kpi¹co) Ta tama jest tu od dawna. Wykorzystuje ciœnienie wody do wytwarzania pr¹du... Mam nadziejê, ¿e wiesz, co to jest. W³aœnie odrestaurowaliœmy tamê i zamieniliœmy j¹ w fort do ochrony przed wrogami i z³¹ pogod¹.}
{430} {} {Ale wybraliœcie jedyne miejsce, w którym mo¿na przekroczyæ rzekê Kolorado w promieniu wielu mil.}
{431} {} {Punkty kontrolne chroni¹ tamê i elektrowniê przed g³upimi plebejuszami. To wyj¹tkowy element wyposa¿enia, który jest krytyczny dla nas i dla okolicznych krain. Aby przeprawiæ siê przez rzekê, w dole rzeki p³ywa prom w bardzo rozs¹dnych cenach.}
{432} {} {O jakim prawie mówi³eœ, generale?}
{433} {} {Proste prawa dla ka¿dego zamo¿nego spo³eczeñstwa. Nie zabijaj, chyba ze jest to absolutnie konieczne. Nie bierz cudzych rzeczy bez pytania. Dzia³aj dla dobra swojej spo³ecznoœci. Istnieje zestaw podobnych zasad. Niestety, wielu na Pustkowiach nie potrafi czytaæ, wiêc musimy wyjaœniaæ w prostszym i bardziej zrozumia³ym jêzyku.}
{434} {} {Relacje miedzyludzkie s¹ znacznie wa¿niejsze ni¿ jakiekolwiek prawa.}
{435} {} {(wzdycha ze zmêczenia) Jak powiedzieli w Starym Swiecie, prawo jest surowe, ale takie jest. Ludzie nie mogli wymyœliæ nic lepszego na samoorganizacjê i dyscyplinê. Odrzucenie Prawa prowadzi do chaosu. Nauczyliœmy siê tego dobrze przez ostatnie sto lat.}
{436} {} {Wspomnia³eœ o Starym Swiecie. Ale on od dawna jest w ruinie.}
{437} {} {Tak. Apokalipsa j¹drowa by³a owocem dumy i g³upoty. Teraz za to p³acimy. Ale ka¿dy pope³nia b³êdy. Pytanie tylko, jakie wnioski mo¿emy z nich wyci¹gn¹æ.}
{438} {} {Chcê tylko powiedzieæ, ¿e wszystko zaczyna siê od ziemi. Pozostaje zgodziæ siê z liderem. Nied³ugo do tego dojdê.}

#Holodisk Ulysses Grant
{450} {} {Prawdopodobnie bêdziesz zainteresowany tym raportem z katedry.}
{451} {} {Z Katedry Swiêtego Ognia w Phoenix? Ciekawe. Sk¹d masz ten holodysk?}
{452} {} {Uda³o mi siê zdobyæ zaufanie doradcy. Poprosi³ o zabranie tego raportu do bazy wojskowej w Puerto Penasco.}
{453} {} {Chocia¿ ta informacja jest trochê spóŸniona, dziêkujê za pomoc.}
{454} {} {Nie ma za co.}
{455} {} {No có¿. Ca³kiem ciekawe. Sprawdzamy tê bazê ju¿ od dawna i wiemy, ¿e Katedra jest z ni¹ w jakiœ sposób zwi¹zana. Ten tajny raport wyjaœnia trochê sytuacjê... Nie rozumiem, dlaczego nam to dajesz?}
{456} {} {Powiedzmy, ¿e jestem... rozczarowany ide¹ Swiêtego Ognia.}
{1456} {} {Powiedzmy, ¿e jestem... rozczarowana ide¹ Swiêtego Ognia.}
{457} {} {Mam osobiste sprawy w tej katedrze. Patronowali ³owcom niewolników, którzy schwytali moj¹ rodzinê.}
{458} {} {Có¿, to brzmi przekonuj¹co. Dziêkujê za pomoc, te informacje mog¹ byæ bardzo cenne.}
{459} {} {Nie ma za co.}

# San Brahmin - quest
{460} {} {O tak. Mam nadziejê, ¿e na ten sojusz nie jest za póŸno. To trudny czas i bêdziemy potrzebowaæ wsparcia. Ale tak d³ugo, jak Twoja spo³ecznoœæ bêdzie siê rozwijaæ i zbieraæ nowe plony, mo¿e siê to zmieniæ.}
{461} {} {O czym ty mówisz?}
{462} {} {Tragedia nie dotknê³a tylko twojej spokojnej ma³ej spo³ecznoœci. Prawdziwe zagro¿enie rozprzestrzenia siê w ca³ej po³udniowej Arizonie. Stra¿nicy ju¿ próbuj¹ ochroniæ miasto San Brahmin przed najeŸdŸcami.}
{463} {} {Ale nie mieliœmy zamiaru braæ udzia³u w wojnie.}
{464} {} {Niewa¿ne, jak bardzo starasz siê pozostaæ odizolowanym od reszty œwiata, ten œwiat ju¿ wie o Villi. A jeœli San Brahmin upadnie, twoja spokojna spo³ecznoœæ mo¿e byæ nastêpna.}
{465} {} {Cholera, musimy coœ z tym zrobiæ.}
{466} {} {Muszê ciê prosiæ o jedn¹ prost¹ przys³ugê, kiedy my jesteœmy zajêci Vill¹. Zanieœ moje instrukcje do Agenta Oscara w San Brahmin. Pomaga lokalnym si³om oporu. Zrób to dla dobra naszego sojuszu.}
{467} {} {Praca wydaje siê ³atwa. Czy mogê iœæ, generale?}
{468} {} {Wygl¹da na to, ¿e bêdê musia³ siê z tym uporaæ, zanim zagro¿enie dotrze do Villi. Do zobaczenia, generale.}
{469} {} {Uwa¿nie s³ucham. Jakie s¹ wiadomoœci z San Brahmin?}

{470} {} {Muszê z tob¹ porozmawiaæ o sytuacji w San Brahmin.}
{471} {} {Przepraszam, nie uda³o mi siê jeszcze dostarczyæ twoich instrukcji.}
{472} {} {Wiêc poœpiesz siê. Im bardziej jesteœmy nieaktywni, tym silniejszy jest nasz wróg.}
{473} {} {Dobrze, generale.}
{474} {} {[CHIT: Gotowe!]}
{475} {} {Misjonarze opuœcili San Brahmin. To dobra wiadomoœæ. Ale nie mo¿emy zapominaæ, ¿e mog¹ wróciæ. To by³ wspania³y moment na zawarcie sojuszu z wodzem plemienia. Ta chwila minê³a.}
{476} {} {[Dalej.]}
{477} {} {Hmm. Tego najbardziej siê obawia³em. Oddzia³ misyjny w San Brahmin dzia³a³ na polecenie Phoenix. NajwyraŸniej marzenia Aarona o imperium nie by³y dalekie od rzeczywistoœci.}
{478} {} {Jak powstrzymamy tego W³adcê Phoenix?}
{479} {} {To nie bêdzie ³atwe. Ale znam grupê rebeliantów w Phoenix, która równie¿ walczy przeciwko Aaronowi i jego koœcio³owi. Spróbuj siê z nimi skontaktowaæ i zaoferowaæ nasz¹ pomoc. Proszê, poniewa¿ Stra¿nicy ciê¿ko pracuj¹ nawet w zat³oczonym œrodowisku miejskim.}
{480} {} {Czy mogê dowiedzieæ siê wiêcej o celu mojej misji?}
{481} {} {Musieliœmy zaanga¿owaæ siê w kilka lokalnych konfliktów, aby zapobiec rozprzestrzenianiu siê „czerwonej plagi” z Phoenix. Sytuacja jest powa¿na i wymaga szybkiego rozwi¹zania.}
{482} {} {[Dalej.]}
{483} {} {JedŸ do San Brahmin i znajdŸ tam Rangersa Oscara. Nadzoruje miejscowych w walce z najeŸdŸcami. Zanieœ mu raport i, jeœli to konieczne, pomó¿ w rozwi¹zaniu konfliktu.}
{484} {} {Zrozumia³em, Generale.}
{1484} {} {Zrozumiano, generale.}
{485} {} {Wygl¹da na to, ¿e bêdê musia³ siê zaanga¿owaæ w twoj¹ wojnê. Mam nadziejê, ¿e warto.}
{486} {} {Po prostu zawieŸæ raport? Brzmi ³atwo.}
{487} {} {Ranger Oscar zgin¹³ w walce w obronie wolnoœci plemienia.}
{488} {} {Smutna wiadomoœæ. Ale by³ œwiadomy ryzyka, które podejmowa³. Oscara zawsze bêdziemy pamietaæ jako bohatera.}
{489} {} {Przykro mi.}
{490} {} {Stra¿nik Oscar uciek³ z San Brahmin. Sytuacja jest doœæ z³a.}
{491} {} {Jestem œwiadomy jego pora¿ki. I nie winiê go. Oscar zrobi³, co móg³.}
{492} {} {Przykro mi.}
{493} {} {Ranger Oscar zakoñczy³ swoj¹ misjê w San Brahmin. Sytuacja tam bardzo siê zmieni³a.}
{494} {} {Nie s³ysza³em jeszcze jego pe³nego raportu. Ale jestem pewien, ¿e macie du¿o do opowiedzenia.}
{495} {} {Oczywiœcie.}
{496} {} {Wiêc jak to siê skoñczy³o w San Brahmin? Czekam na pe³ny raport...}
{497} {} {[raport]}
{498} {} {Dobra robota. Dziêki nam plemiê uchroni³o sw¹ wolnoœæ. To zwyciêstwo poka¿e wszystkim innym, jak przydatni s¹ Rangersi. Nie wspominaj¹c ju¿ o bardzo potrzebnych dostawach miêsa braminów.}
{499} {} {[Dalej.]}

# Phoenix - ukonczenie zadania
{500} {} {Muszê z tob¹ porozmawiaæ o Phoenix.}
{501} {} {S³ucham uwa¿nie. Jakie s¹ wiadomoœci?}
{502} {} {Przepraszam, wci¹¿ to samo.}
{503} {} {Jak mogê znaleŸæ tych powstanców?}
{504} {} {O ile wiem, ukrywaj¹ siê w podziemnej komunikacji i transmituj¹ zaszyfrowan¹ transmisjê radiow¹. Mo¿na te¿ tam wypytaæ wokó³ ludzi, wœród miejscowych na pewno znajd¹ siê ich zwolennicy. Ale uwa¿aj kogo pytasz.}
{505} {} {Dziêki, to mo¿e mi pomóc.}
{506} {} {Dlaczego tak wa¿ne jest pozbycie siê Aarona i jego koœcio³a?}
{507} {} {Kult to tylko marionetka w rêkach Aarona, lokalnego w³adcy. Stara siê stworzyæ imperium, wiêc prowadzi agresywn¹ politykê i fizycznie eksterminuje sprzeciw.}
{508} {} {[Dalej.]}
{509} {} {Wiêc musimy jak najszybciej znaleŸæ tych buntowników. Jak to zrobiæ?}
{510} {} {Ale dlaczego tak wa¿ne jest pozbycie siê Koœcio³a Ognia w Phoenix?}
{511} {} {Katedra Swiêtego Ognia w Phoenix zosta³a zniszczona.}
{512} {} {(westchnienie ulgi) S³ysza³em tê wiadomoœæ. Dobra robota. Co najmniej o jednego wroga mniej.}
{513} {} {[Dalej.]}
{514} {} {Post¹pi³eœ s³usznie, stosuj¹c ekstremalne œrodki. Kto wie, jakie tajemnice skrywano w komnatach swi¹tyni? I ile k³opotów mog³y przynieœæ nieprzygotowanym ludziom naszych czasów.}
{1514} {} {Post¹pi³aœ s³usznie, stosuj¹c ekstremalne œrodki. Kto wie, jakie tajemnice skrywano w komnatach swi¹tyni? I ile k³opotów mog³y przynieœæ nieprzygotowanym ludziom naszych czasów.}
{515} {} {[Dalej.]}
{516} {} {Ale obawiam siê, ¿e czeka nas jeszcze trudniejszy test. Odpocznij trochê, ja muszê zebraæ dowódcow polowych. Spotkamy siê w sali konferencyjnej, ty te¿ musisz tam byæ.}
{517} {} {Wrócê póŸniej, generale.}
{518} {} {Aaron, W³adca Phoenix, nie ¿yje.}
{519} {} {(westchnienie ulgi) S³ysza³em tê wiadomoœæ. Dobra robota. Co najmniej o jednego wroga mniej.}
{520} {} {[Dalej.]}
{521} {} {Bez w³adcy miasto padnie ofiar¹ walk. Gubernatorzy Aarona rozpoczn¹ miêdzy sob¹ walkê o tron, ludnoœæ cywilna „przypomni sobie” dawne krzywdy ze strony koœcio³a, a rebelianci bêd¹ mogli dzia³aæ bardziej otwarcie i zdecydowanie. To bêdzie trudny okres dla miasta, ale uwa¿am, ¿e tak bêdzie najlepiej.}
{522} {} {[Dalej.]}
{523} {} {To za jego spraw¹ niewolnictwo, szkodliwe przedwojenne technologie i narkotyki wróci³y do Arizony. Nasz œwiat jest ju¿ zbyt kruchy, aby pozwalaæ rz¹dziæ tyranom.}
{524} {} {Rozumiem.}
{525} {} {Co za zbieg okolicznoœci - jestem stamt¹d!}
{526} {} {Partia Wyzwolenia prowadzona przez Marcosa szturmem zdoby³a katedrê. Lord Phoenix nie ¿yje.}

# Okno dialogowe
{550} {} {Nie zamierzam przytulaæ wê¿a. Udowodnij, ¿e mo¿na Ci zaufaæ. Wtedy porozmawiamy. Wiesz, gdzie jest wyjœcie.}
{551} {} {Tak, generale, wiem.}
{552} {} {Pope³niasz du¿y b³¹d, generale. Zobaczysz.}
{553} {} {Oto nasza najwiêksza pora¿ka. Wiêc jesteœ tutaj, aby przywróciæ sprawiedliwoœæ? O nie, jesteœ tu dla w³asnych egoistycznych celów.}
{554} {} {Dlaczego pozbawiono mnie rangi?}
{555} {} {Przy dwóch frontach niemo¿liwe jest utrzymanie lojalnoœci. Konflikt jest nieunikniony. Jeœli zdecydujesz siê stan¹æ po stronie kolonisty, który podporz¹dkowuje sobie po³udniow¹ Arizonê, nie bêdziesz mieæ miejsca wœród Rangersów.}
{556} {} {Zawsze istnia³a przepaœæ miêdzy religi¹ a prawem. W takiej sytuacji nie da siê zachowaæ porozumienia, konflikt jest nieunikniony. Jeœli wybierzesz œcie¿kê kultysty, nie bêdziesz mieæ miejsca wœród Stra¿ników.}
{557} {} {Oczywiœcie twoje dzia³ania s¹ sprzeczne z zasadami prawa i porz¹dku. Mo¿esz je Ÿle interpretowaæ, ale to nie pozbawia ciê odpowiedzialnoœci. Nie mo¿emy pozwoliæ, aby osoba taka jak ty nosi³a odznakê Stra¿nika.}
{558} {} {[Dalej.]}
{559} {} {IdŸ w pokoju. Z szacunku do Twoich zas³ug z przesz³oœci odbieramy Ci jedynie tytu³. W innych okolicznoœciach kar¹ za zdradê by³aby egzekucja.}
{560} {} {Rozumiem, generale. Nie otrzymasz ode mnie wiêcej wiadomoœci.}
{561} {} {Naucz siê wybaczaæ, generale. Bêdziesz tego kiedyœ potrzebowaæ.}
{562} {} {Wiemy, co tu robisz. IdŸ st¹d. Wartownik wyprowadzi ciê na zewn¹trz.}
{563} {} {[Opuœæ pokój]}

{570} {} {Co za niespodziewana wizyta. Myœla³em, ¿e twój koœció³ nienawidzi naszej organizacji.}
{571} {} {Czy nie mo¿emy ¿yæ w pokoju?}
{572} {} {Tylko jeœli postawimy barykadê z rowem radioaktywnej cieczy na granicy.}
{573} {} {[Dalej.]}
{574} {} {Twój koœció³ narzuca innym swoje wypaczone wizje i karze tych, którzy siê z nimi nie zgadzaj¹. Twój przywódca pod flag¹ koœcio³a tworzy imperium i rozwija niewolnictwo. Nie mamy ochoty na negocjacje z wê¿em. IdŸ i powiedz o tym swojemu przeorowi. To koñczy twoj¹ wizytê.}
{575} {} {[Opuœæ pokój]}
{576} {} {A oto ambasador dobrej woli z samego Bractwa Stali. Masz zamiar zaproponowaæ nam porozumienie o zawieszeniu broni? A mo¿e jest to ¿¹danie poddania siê?}
{577} {} {Nie wiem, co masz na myœli. Jestem tu z w³asnej inicjatywy.}
{578} {} {Mo¿e. W ka¿dym razie nie mo¿emy pozwoliæ ci przebywaæ w naszej bazie. Wartownik wska¿e ci drogê na zewn¹trz.}
{579} {} {[Opuœæ pokój]}
{580} {} {Jeœli nie chcesz negocjowaæ z Bractwem, zetrzemy twoj¹ tamê z powierzchni ziemi.}
{581} {} {Te groŸby tylko dowodz¹ wrogoœci Bractwa Stali. S³u¿by wojskowe s³u¿¹ wojnie, a nie tworzeniu nowego œwiata. Wasze Bractwo powinno nauczyæ siê ¿yæ w pokoju. Teraz idŸ i powiedz o tym swojemu genera³owi. To koñczy twoj¹ wizytê.}
{582} {} {[Opuœæ pokój]}

{590} {} {Czy wszyscy ju¿ s¹? Zacznijmy wiêc.}
{591} {} {[Dalej.]}
{592} {} {Jak wiecie, nasz nowy sojusznik, }
{1592} {} {Jak wiecie, nasz nowy sojusznik, }
{593} {} { z Villi, uwolni³ pustkowia od ciemiê¿yciela Aarona. Raporty o upadku kultu nap³ywaj¹ z ca³ego stanu. Ta walka wkrótce przejdzie do historii.}
{1593} {} { z Villi, uwolni³a pustkowia od ciemiê¿yciela Aarona. Raporty o upadku kultu nap³ywaj¹ z ca³ego stanu. Ta walka wkrótce przejdzie do historii.}
{594} {} {[Dalej.]}
{595} {} {Ale to jeszcze nie koniec. Jak siê spodziewaliœmy, Aaron by³ tylko czêœci¹ wiêkszej gry. Blacharze pomogli mu z broni¹ i sprzêtem za tani uran.}
{596} {} {[Dalej.]}
{597} {} {Jeszcze bardziej interesuj¹ce by³o jednak to, ¿e w umowie by³a strona trzecia. W przeciwnym razie Aaron i Blacharze nie byliby w stanie uzgodniæ wspó³pracy, a sam Aaron nigdy nie doszed³by do w³adzy.}
{598} {} {[Dalej.]}
{599} {} {Niemal nic nie wiemy o tej tajemniczej organizacji. Ma ona siedzibê w starym porcie Puerto Penasco i prowadzi agresywn¹ politykê wojskow¹.}
{600} {} {[Dalej.]}
{601} {} {Wiemy na pewno, ¿e ruda uranu z Flagpool jest transportowana do Blacharzy, a gotowe baterie uranowe s¹ wysy³ane g³ównie do placówki w Puerto.}
{602} {} {[Dalej.]}
{603} {} {Innymi s³owy, ta organizacja zdecydowa³a siê przej¹æ po³udniow¹ Arizonê, aby zdobyæ lokalne zasoby tani¹ si³¹ robocz¹. Powierzyli swoim wasalom kontrolê nad osadami, tak jak to by³o w przypadku Casa Grande. Wzbudzaj¹ rewolucje, jak to by³o w przypadku San Brahmin. Przejmuj¹ zasoby i u¿ywaj¹ do tego niewolników. A my nawet nie wiemy, z kim mamy do czynienia.}
{604} {} {[Dalej.]}
{605} {} {, teraz rozumiesz, ¿e Twoja Villa nie mo¿e staæ z boku? Jeœli ta armia nadal bêdzie zniewalaæ po³udniow¹ Arizonê, Villa, podobnie jak wszystkie inne ma³e osady, straci wolnoœæ. Najlepszym sposobem unikniêcia tego jest sprzymierzenie siê z Rangersami i dzia³anie jako zjednoczony front przeciwko najeŸdŸcy.}
{606} {} {Czego teraz ode mnie chcesz?}
{607} {} {JedŸ do Puerto Penasco i znajdŸ s³abe punkty przeciwnika. Naszym zwiadowcom nie uda³o siê jeszcze znaleŸæ ¿adnych cennych informacji - ta baza wojskowa jest zbyt daleko i jest zbyt dobrze zorganizowana.}
{608} {} {Wiêc jak ja mam to zrobiæ?}
{609} {} {Jesteœ ch³opem. Bêdziesz mniej podejrzany. Poza tym masz dobry powód - zniewolenie Villi. Powodzenia.}
{1609} {} {Jesteœ ch³opk¹. Bêdziesz mniej podejrzana. Poza tym masz dobry powód - zniewolenie Villi. Powodzenia.}
{610} {} {Puœæ mnie, generale.}
{611} {} {Myœlê, ¿e to samobójstwo. Umywam rêce, generale.}
{612} {} {Pomyœl o wszystkim, co tu powiedziano. Byæ mo¿e nawet twoje wsparcie nie wystarczy, aby wygraæ tê wojnê.}
{613} {} {Masz racjê, generale. Spróbujê dowiedzieæ siê wiêcej o tej tajemniczej organizacji.}
{614} {} {Szukaj g³upców. Wracam do domu, czeka na mnie moja rodzinna Villa, generale.}

{620} {} {Uda³o mi siê zinfiltrowaæ bazê Bractwa Stali.}
{621} {} {Dobra wiadomoœæ. Czego siê dowiedzia³eœ? Jakie s¹ ich s³abe punkty?}
{622} {} {Nie znam jeszcze ich s³aboœci. S¹ zbyt dobrze zorganizowani i chronieni.}
{623} {} {Przykro mi to s³yszeæ. Ale wierzê, ¿e odniesiesz sukces. Kontynuuj misjê.}
{624} {} {Puœæ mnie, generale.}
{625} {} {Czy mogê poœwiêciæ Ci jeszcze minutê?}
{626} {} {Ich statek jest pe³en materia³ów wybuchowych. Ale jeszcze nie wiem, jak siê do tego zabraæ.}
{627} {} {Swietny pomys³. Jeœli znajdziesz sposób, by wysadziæ w powietrze ca³y ich statek, zetrze to Bractwo z mapy Arizony. Ich wasale i ma³e posterunki pozostan¹ bezradne. Spróbuj to zrobiæ. Wierzê, ¿e odniesiesz sukces.}
{628} {} {Wiesz, zosta³em zwolniony tylko dlatego, ¿e zaproponowano mi podobne zadanie.}
{629} {} {W ten sposób... Wiêc co zdecydowa³eœ? Po czyjej jesteœ stronie?}
{1629} {} {W ten sposób... Wiêc co zdecydowa³aœ? Po czyjej jesteœ stronie?}
{630} {} {Pañskiej oczywiœcie, generale.}
{631} {} {Wiêc b¹dŸ mi³y - wykorzystaj zaufanie, które zdoby³eœ, aby zniszczyæ naszego wspólnego wroga.}
{632} {} {Czy mogê iœæ, generale?}
{633} {} {Nie mo¿esz sobie z nimi poradziæ, generale. Przyznaj siê do swojej pora¿ki.}
{634} {} {Przyznaæ siê do pora¿ki po jednej wiadomoœci? Szkoda, ¿e tak siê to skoñczy³o. Teraz nie mogê pozwoliæ ci odejœæ, dopóki nie otrzymamy wszystkich odpowiedzi. Nie powinieneœ by³ walczyæ z Rangersami.}
{635} {} {Nie, generale. Wyjdê st¹d. I nikt mnie nie zatrzyma.}
{636} {} {Nie jesteœmy ju¿ sojusznikami. Wiêc wycofaj siê, staruszku. Nie zastraszysz mnie.}
{637} {} {Uda³o mi siê zinfiltrowaæ statek Bractwa Stali i zdetonowaæ torpedy. Ich baza jest ca³kowicie zniszczona.}
{638} {} {Nie s³ysza³em tak dobrych wiadomoœci od lat! Wypêdzaj¹c Bractwo, uratowaliœmy nasze ojczyste ziemie dla siebie i naszych potomków. Czy mog³o byæ lepiej?}
{639} {} {Oczywiœcie.}
{640} {} {Wci¹¿ mamy du¿o do zrobienia, aby wykorzeniæ resztki z³a zasianego przez Bractwo. Twoja misja dobieg³a jednak koñca. Proponujê, abyœ zosta³ Rangersem i s³u¿y³ w swojej rodzinnej Villi.}
{641} {} {Dziêki, generale. Ale chcê zachowaæ moj¹ wolnoœæ i wolnoœæ mojej wioski.}
{642} {} {No to idŸ do swojej rodziny w Villi i przeka¿ im dobr¹ nowinê.}
{643} {} {Dobrze by³o s³u¿yæ, generale.}
{1643} {} {Dobrze by³o s³u¿yæ, generale.}
{644} {} {By³bym zaszczycony zostaj¹c Stra¿nikiem.}
{645} {} {Od teraz jesteœ jednym ze Stra¿ników. Przestrzegaj Prawa i Porz¹dku w swojej ojczyŸnie. Teraz wróæ do Villi i przeka¿ swojej rodzinie dobre wieœci.}
{1645} {} {Od teraz jesteœ jednym ze Stra¿ników. Przestrzegaj Prawa i Porz¹dku w swojej ojczyŸnie. Teraz wróæ do Villi i przeka¿ swojej rodzinie dobre wieœci.}
{646} {} {Dobrze by³o s³u¿yæ, generale.}
{1646} {} {Dobrze by³o s³u¿yæ, generale}
{647} {} {Wci¹¿ mamy du¿o do zrobienia, aby wykorzeniæ pozosta³oœci z³a zasianego przez Bractwo. Twoja misja jednak dobieg³a koñca. Wróæ do Villi i przeka¿ rodzinie dobre wieœci.}
{648} {} {Dlaczego nie zaatakowaæ tego fortu ca³ym oddzia³em Stra¿ników?}
{649} {} {Nasz przeciwnik jest silny i dobrze zorganizowany. W otwartej walce z nim nie mamy szans. W takim przypadku mówimy: jeœli chcesz pokonaæ siln¹ bestiê, okalecz jej nogi i wykoñcz j¹ z dystansu.}
{650} {} {Chcê porozmawiaæ o naszym nowym wrogu.}
{651} {} {Oczywiœcie. Coœ nowego?}
{652} {} {Jeszcze nie.}
{653} {} {Co wiesz o bazie w Puerto?}
{654} {} {Niewiele. Stary statek pojawi³ siê w porcie kilka lat temu. Nie ma wstêpu do œrodka, obwód jest dobrze strze¿ony. Zwiadowcom ciê¿ko jest dostaæ siê tam przez pustyniê, poza tym wszystkie nasze si³y skierowaliœmy w innym kierunku. Bêdziesz musia³ sam dowiedzieæ siê szczegó³ów.}
{655} {} {Nie rozumiem, jak taka zamkniêta organizacja mog³a przej¹æ tak wiele osad?}
{656} {} {Poprzez dobr¹ politykê i dobry sprzêt techniczny. Wojsko z Puerto nie bierze udzia³u w morderczych wojnach w Arizonie. Ale skutecznie je prowokuje. A kiedy cichnie strzelanina, ludzie, których potrzebuj¹, staj¹ na czele osad - marionetki takie jak Aaron.}
{657} {} {Co jest nie tak z t¹ trzeci¹ si³¹?}
{658} {} {Nios¹ swój œwiatopogl¹d za pomoc¹ przymusu, co jest niedopuszczalne. Z powodu prowadzonej polityki osady trac¹ swoj¹ suwerennoœæ i popadaj¹ w niewolê. I w koñcu spo³eczeñstwo nie jest gotowe na ich postêpowe idee.}
{659} {} {Rozumiem. Cofnijmy siê trochê.}