{100} {} {Widzisz kadeta.}
{101} {} {Widzisz jednego z rekrutów.}

{110} {} {Mówi¹, ¿e jest to ³atwiejsze w walce ni¿ na treningu.}
{111} {} {Kapitan Agatha to bestia, a nie cz³owiek.}
{112} {} {Podziwiam Komandora Helforda.}
{113} {} {Podobno genera³ ma w³osy na ca³ym ciele, dlatego nosi prochowiec.}
{114} {} {Zastanawiam siê, co jest w Kalifornii?}
{115} {} {Uwielbiam porê na lunch.}
{116} {} {Po opowieœciach o potworach nie czujê siê senny.}
{117} {} {Te æwiczenia kiedyœ siê skoñcz¹.}
{118} {} {Jak dot¹d podoba mi siê tu.}
{119} {} {Ty te¿ chcesz zostaæ kadetem?}