{100} {} {Widzisz kadeta.}
{101} {} {Oto kadet. Dziœ s³u¿y w kuchni.}
{102} {} {Nie ma Ciê na liœcie do racji ¿ywnoœciowych.}

{200} {} {Przestañ... Cywil? Co Ty tutaj robisz?}
{201} {} {Patrzê na ciebie. Rozumiesz?}
{202} {} {Uh... To s¹ pokoje obs³ugi. IdŸ st¹d.}
{203} {} {Spróbuj mnie wyrzuciæ, frajerze.}
{204} {} {Oczywiœcie, nie chcê problemów.}
{205} {} {Nie martw siê, mam poœwiadczenie bezpieczeñstwa.}
{206} {} {Nie powinieneœ tego wiedzieæ. Ale mam pozwolenie, spokojnie.}

{210} {} {Jestem dzisiaj kucharzem. Ale nie obs³ugujemy osób z zewn¹trz.}
{211} {} {Wiêc nie mam tu nic do roboty. Czeœæ.}
{212} {} {Jestem dzisiaj kucharzem. Ale nie ma Ciê na liœcie do racji ¿ywnoœciowych.}

{220} {} {Kto jest twoim prze³o¿onym, kadecie?}
{221} {} {Kapitan Agatha. A co?}
{222} {} {Jak ci siê podoba jej szkolenie?}
{223} {} {Strasznie mêcz¹ce. Ale przyda mi siê na tej ja³owej pustyni. Jedyn¹ zniewag¹ jest to, ¿e nam, kadetom, nie wolno strzelaæ z powa¿nej broni. Marzy³em o tym od samego pocz¹tku. A nawet otrzymawszy odznakê, bêdziemy musieli oszczêdzaæ amunicjê. Szkoda.}
{224} {} {Jeszcze trochê postrzelasz. W³aœciwie to nie jest taka wielka sprawa.}
{225} {} {Myœla³eœ, ¿e jesteœ w bajce? Naiwiak.}
{226} {} {Nic, chcia³em tylko porozmawiaæ. Czeœæ.}
{227} {} {Czy ona jest dobrym dowódc¹?}
{228} {} {Oczywiœcie. Dba o swoich kadetów jak o w³asne dzieci. Cieszê siê, ¿e to ona szkoli nasz oddzia³.}
{229} {} {Masz szczêœcie, ¿e j¹ masz. Bywaj.}

{230} {} {Wiêc kwatermistrz straci³ broñ po waszym treningu, co?}
{231} {} {Ale... Oddaliœmy broñ.}
{232} {} {A potem po cichu j¹ zabraliœcie, co? Albo podrobiliœcie podpis w papierach? Mów.}
{233} {} {Naprawdê ciê¿ko to rozwi¹zaæ, jesteœ wolny, kadecie.}
{234} {} {Co... Um... Ugh... S³uchaj. Powiedzia³em im, ¿e to z³y pomys³.}
{235} {} {Ok. Powiesz mi teraz jak by³o.}
{236} {} {Aha. Wiêc przyznajesz siê.}
{237} {} {Po treningu *po¿yczyliœmy* broñ razem z pude³kiem amunicji. Chcieliœmy poæwiczyæ trochê strzelanie. W przeciwnym razie jak mamy zostaæ dobrymi Stra¿nikami?}
{238} {} {I mia³eœ nadziejê, ¿e pozostanie to niezauwa¿one?}
{239} {} {Naprawdê chcieliœmy oddaæ broñ. Ale strza³y przyci¹gnê³y radskorpiony. Musieliœmy uciekaæ, a pistolet pozosta³ na pustyni. Teraz nie da siê po niego wróciæ bez wzbudzania podejrzeñ. Ponadto kwatermistrz, na nieszczêœcie, rozpocz¹³ ponown¹ inwentaryzacjê.}
{240} {} {Có¿, rozumiem ciê. Chocia¿ teraz inni bêd¹ s¹dzeni za to.}
{241} {} {Co za ciekawa wymówka. Ciekawe, co Stra¿nicy ci zrobi¹ za takie przestêpstwo?}
{242} {} {Wiesz, innym nie spodoba siê, jeœli siê przyznam. Ale coœ trzeba zrobiæ. Jesteœ now¹ osob¹ w bazie. Mo¿e mo¿emy siê dogadaæ?}
{243} {} {Podejœcie biznesowe, podoba mi siê to. Co sugerujesz?}
{244} {} {Dam ci resztê amunicji, jeœli zwrócisz mi broñ. Znajdê sposób, ¿eby dyskretnie zwróciæ j¹ do magazynu i ochroniæ nasze ty³ki. Broñ le¿y pod du¿ym kaktusem przed farm¹. Co ty na to?}
{245} {} {Niez³a umowa. Przemyœlê Twoj¹ propozycjê.}
{246} {} {Nie zamierzam kryæ drobnych z³odziei. Mi³ego dnia, kadecie.}
{247} {} {Nie martw siê, to zostanie miêdzy nami.}
{248} {} {Um... Pos³uchaj. Powiedzia³em im, ¿e to z³y pomys³. Nie pos³uchali mnie.}
{249} {} {Przypomnij mi, gdzie jest broñ?}

{250} {} {To jest to! Dziêkujê, ratujesz nasze ty³ki. Teraz ch³opaki i ja bêdziemy bardziej ostro¿ni. Tak, a tutaj jest amunicja, zgodnie z ustaleniami. }
{251} {} {Bywaj.}
{252} {} {Musia³eœ podlizaæ siê kwatermistrzowi, co? Teraz ka¿dy kadet bêdzie wiedzia³, ¿e najlepiej siê z tob¹ nie zadawaæ.}
{253} {} {Przepraszam, nie mia³em wyboru.}
{254} {} {Sam to schrzani³eœ. Obwiniaæ mo¿esz tylko siebie.}
{255} {} {Czy to jest broñ, o której rozmawialiœmy?}
