{100} {} {Widzisz kadeta Burka.}
{101} {} {Widzisz chudego i niedoœwiadczonego kadeta. Nic dziwnego, ¿e zosta³ umieszczony w tym miejscu.}

{200} {} {(przed tob¹ stoi m³ody mê¿czyzna z chud¹ szyj¹; patrz¹c na ciebie nie mo¿e skupiæ wzroku i co minutê robi krótki, napiêty uœmiech) Czeœæ! Jak mogê pomóc?}
{201} {} {Co to za miejsce?}
{202} {} {To jest centrum informacyjne... a raczej to jest recepcja, a raczej... (prostuje siê) Rozmawiamy tutaj o interesach z obcymi, sir!}
{1202} {} {To jest centrum informacyjne... a raczej to jest recepcja, a raczej... (prostuje siê) Rozmawiamy tutaj o interesach z obcymi, proszê pani!}

{203} {} {Kim jesteœmy „my”?}
{204} {} {(zdezorientowany) Stra¿nicy... To znaczy Rangersi... (prostuje siê) Kadet Burke do us³ug! Jeœli szukasz starszego stopniem Stra¿nika, musisz umówiæ siê na spotkanie.}
{205} {} {Kto jest za tymi drzwiami?}
{206} {} {Dowódca polowy Helford... Ale spotkanie jeszcze nie jest umówione, wiêc nie mogê...}
{207} {} {Swietnie, mo¿e on mo¿e mi pomóc.}
{208} {} {Hej, czekaj!}
{209} {} {[wyjdŸ]}

{210} {} {Potrzebujê twojego szefa.}
{211} {} {Teraz? O nie, nie mo¿esz iœæ do genera³a.}
{212} {} {Kogo mogê zobaczyæ?}
{213} {} {Dowódca polowy Helford jest za tymi drzwiami... Ale musisz siê umówiæ, nie mo¿esz tam wejœæ...}
{214} {} {Swietnie, mo¿e on mo¿e mi pomóc.}
{215} {} {Hej, czekaj!}
{216} {} {[wyjdŸ]}

{220} {} {Tylko nie sprawiaj mi k³opotów.}
{221} {} {Nie zrobiê tego.}
{222} {} {Czeœæ, gratulacje z powodu twojego awansu. Ja muszê tu jeszcze s³u¿yæ latami, a¿ do rangi Stra¿nika.}
{223} {} {Do widzenia.}