{100} {} {Widzisz Helforda.}
{101} {} {Widzisz jednego z dowódców polowych.}
{102} {} {Uratowanie Jasona poprawi³o twoj¹ reputacjê wœród Rangersów.}

# Pierwszy dialog
{200} {} {(rzuca ci szybkie spojrzenie i wraca do studiowania raportów) Rozmawiasz z dowódc¹ polowym. Nazywam siê Helford. Mam za du¿o pracy, ¿eby traciæ czas na drobiazgi.}
{201} {} {Spêdzisz kilka minut z biednym Campesino?}
{202} {} {Nie jestem tu po bezczynn¹ rozmowê, dowódco.}

# Powtarzajacy siê dialog
{210} {} {Co mogê dla ciebie zrobiæ?}
{211} {} {Do widzenia.}
{212} {} {Ok, nie kontynuuj.}
{213} {} {Czy mo¿esz odpowiedzieæ na pytanie?}
{214} {} {Pozwól mi.}
{215} {} {Kolejne pytanie.}

#Pytania
{220} {} {Jak zosta³eœ Rangersem?}
{221} {} {Uczy³em siê od najm³odszych lat i du¿o æwiczy³em na pustyni. S³u¿ ze mn¹ - a mo¿e te¿ zostaniesz dowódc¹ polowym.}
{222} {} {Co to za miejsce?}
{223} {} {To jest g³ówna baza Rangersów. Centrum dowodzenia znajduje siê wewn¹trz elektrowni, tutaj szkolimy naszych i spotykamy „goœci”.}
{224} {} {O jakich „goœciach” mówimy?}
{225} {} {Handlarze i negocjatorzy. Jeœli jeszcze nie wiesz, jesteœmy w trakcie porz¹dkowania tego regionu. A to wymaga sojuszników.}
{226} {} {Nie wiem zbyt wiele o Rangersach. Powiesz mi wiêcej?}
{227} {} {Stra¿nicy to elitarni wojownicy i mistrzowie przetrwania na pustyni. Te umiejêtnoœci pozwalaj¹ nam broniæ prawa i przywracaæ porz¹dek na Pustkowiach. Przywrócenie Prawa z powrotem na te ziemie to nasza g³ówna misja.}
{228} {} {Czy robicie to za darmo?}
{229} {} {Nasz patronat jest opodatkowany i podlega ograniczeniom. Jeœli ludzie odmawiaj¹ zaakceptowania Prawa i innych naszych warunków, odmawiamy im pomocy.}
{230} {} {Co to za warunki?}
{231} {} {Ma³y zestaw prostych zasad i zakazów, których nale¿y œciœle przestrzegaæ. Ci, którzy ra¿¹co naruszaj¹ Prawo, zostan¹ ukarani. Czêsto œmiertelne.}

#Ranger at Jackals
{233} {} {W ka¿dym razie dziêki za opiekê. Ci dzicy wypili za du¿o krwi naszych braci. Bardzo siê cieszê, ¿e zap³acili za to ¿yciem.}
{234} {} {To nie jest ju¿ wymagane. Znalezliœmy szcz¹tki patrolu w jaskini Szakali na pó³nocy. Znasz to miejsce.}
{235} {} {Co za niespodzianka. Przykro to s³yszeæ.}
{236} {} {Jak znaleŸæ zaginiony patrol?}
{237} {} {Najprawdopodobniej bêdzie mo¿liwe wyœledzenie ich wspó³rzêdnych za pomoc¹ radia, jeœli nadal dzia³a. Byæ mo¿e w pobliskich osadach s³yszano coœ o patroluj¹cych. Mo¿esz te¿ po prostu udaæ siê w to miejsce i na œlepo szukaæ œladów Stra¿ników poœrodku pustyni.}
{238} {} {To drugie nie jest dobre, ale przynajmniej to zawsze coœ.}

{239} {} {Co dziwne, Szakale s¹ gotowe do zawarcia sojuszu.}
{240} {} {To wykluczone! Szakale s¹ przebieg³e i agresywne, nie maj¹ sk³onnoœci do dialogu. Jeœli chc¹ sojuszu, to prawdopodobnie jest to sztuczka w celu osi¹gniêcia zysku, nic wiêcej. Jestem pewien, ¿e genera³ w pe³ni siê ze mn¹ zgodzi.}
{241} {} {Stra¿nicy z Pó³nocnego patrolu nie ¿yj¹. Szakale ich dopad³y.}
{242} {} {Cholera... Mia³em przeczucie, ¿e tak bêdzie. Ci dzicy ju¿ za du¿o nam napsuli krwi. Ale dziêki za pomoc. Przeœlê raport z dochodzenia do genera³a.}
{243} {} {Nie ma za co.}
{244} {} {Stra¿nik z pó³nocnego patrolu wróci³. To prawda.}
{245} {} {Zosta³em ju¿ o tym poinformowany. Dobra robota, Stra¿niku. Tak trzymaj.}
{246} {} {Zosta³em ju¿ o tym poinformowany. Niez³a robota, ch³opie. Widzê, ¿e masz szczêœcie, którego nam czasami brakuje. Tak trzymaj.}
{1246} {} {Zosta³em ju¿ o tym poinformowany. Swietna robota, kobieto. Widzê, ¿e masz szczêœcie, którego nam czasami brakuje. Tak trzymaj.}
{247} {} {Nie ma za co.}
{248} {} {Co myœlisz o Szakalach?}
{249} {} {Szakale to jeden z najbardziej obrzydliwych gangów na Pustkowiu. Sta³y siê tak dzikie, ¿e nawet ich dzieci nie mo¿na odró¿niæ od szczeni¹t. Serce mi pêka, gdy widzê, jak ca³y naród wiedzie takie ¿ycie. Kanibalizm, œmieszny kult, wrogoœæ wobec wszystkich obcych, nawet s¹siednich klanów - czy mo¿na upaœæ ni¿ej?}

# Rodzina przestepcza
{250} {} {Co powiesz na usprawiedliwienie zamordowania mê¿a tej kobiety?}
{251} {} {Och, ciebie te¿ zaczepi³a? Pos³uchaj, jej m¹¿ by³ przestêpc¹. By³ zaanga¿owany w rabunki rolników i ataki na podró¿ników. Za to wszystko zosta³ sprawiedliwie stracony zgodnie z prawem. Nikt by nie pomyœla³, ¿e ma rodzinê.}
{252} {} {[Dalej.]}
{253} {} {Dla ciebie to tylko kolejna niepewna historia. Dla mnie te¿, szczerze mówi¹c. Nie masz pojêcia, jakie g³upoty mo¿e zrobiæ wœciek³a kobieta. Musimy coœ z tym zrobiæ.}
{254} {} {[Dalej.]}
{255} {} {Hmm... Tobie mo¿e siê udaæ znaleŸæ z ni¹ wspólny jêzyk. Bez obrazy, ale wygl¹dasz bardziej jak wieœniak ni¿ nasz zwiadowca, co oznacza, ¿e mo¿esz zdobyæ jej zaufanie z wielkim sukcesem.}
{256} {} {Co mam zrobiæ?}
{257} {} {Po prostu wyt³umacz jej, ¿e nie jest ju¿ mile widziana na tych ziemiach. By³oby lepiej dla wszystkich, gdyby ona i jej potomstwo wyjechali w inne miejsce.}
{258} {} {Ok, spróbujê.}
{259} {} {Nie mam zamiaru zajmowaæ siê problemami innych ludzi.}
{260} {} {Widzê, ¿e jakoœ poradzi³eœ sobie z t¹ spraw¹. Dobra robota. Proszê, weŸ ode mnie trochê amunicji jako wyraz wdziêcznoœci.}
{261} {} {Nie ma za co.}
{262} {} {Zaczekaj chwilê. Zg³oszono mi bardzo tragiczne wydarzenie. PrzewoŸnik zosta³ znaleziony martwy, a ostatnio ty i uchodŸcy byliœcie widziani na przejœciu. Niezwyk³y zbieg okolicznoœci, prawda?}
{263} {} {Ja, uh, nie mam z tym nic wspólnego.}
{264} {} {Mam nadziejê, ¿e tak w³aœnie jest. Poniewa¿ prêdzej czy póŸniej nasi ludzie dojd¹ do sedna prawdy. I wiesz jak bardzo szanujemy Prawo, tym bardziej blisko naszej cytadeli.}
{265} {} {Oczywiœcie, uh, prawdopodobnie znajdziecie winnego. Có¿, muszê ju¿ iœæ...}

# Szpieg farmy
{270} {} {Chcê zg³osiæ szpiega. Ukrywa siê w domu przy starej drodze...}
{271} {} {...Dziêki za cynk. Wyœlemy tam zwiadowców i spróbujemy go zaskoczyæ. Czas z³paæ tego drania.}
{272} {} {Sukcesu w operacji.}
{273} {} {Czy wiesz, ¿e u kwatermistrza brakuje jednego egzeplarza broni?}
{274} {} {Nie, nie zosta³em o tym poinformowany. Mam lepsze rzeczy do roboty ni¿ niañczenie kwatermistrza.}
{275} {} {Rozumiem.}

# Zatrzymaj dialog
{280} {} {Cholera... Wygl¹dasz jak te ghule z po³udnia. Nie chcê powiedzieæ nic z³ego, ale powinieneœ uwa¿aæ, gdy pojawiasz siê wsród ludzi.}
{281} {} {Wiem. To nie pierwszy raz.}

{282} {} {I nadal masz odwagê przyjœæ tutaj po tym, co zrobi³eœ?}
{283} {} {Sprzeda³ mi kiepski produkt.}
{284} {} {I jesteœ gotów za to zabiæ cz³owieka? Do diab³a, czy kiedykolwiek przysz³o ci do g³owy, ¿e kara powinna byæ adekwatna do przestêpstwa?}
{1284} {} {I jesteœ gotowa za to zabiæ cz³owieka? Do diab³a, czy kiedykolwiek przysz³o ci do g³owy, ¿e kara powinna byæ adekwatna do przestêpstwa?}
{285} {} {Nie.}
{286} {} {Jest mi nieskoñczenie przykro z powodu tego, co zrobi³em.}
{287} {} {Jego stra¿nik zaatakowa³ pierwszy.}
{288} {} {Masz na myœli jego syna idioto? Czêsto dopuszcza³ siê pewnych niew³aœciwych dzia³añ, ale jak dot¹d nie dochodzi³o do ¿adnych walk. Có¿, bêdê musia³ uwierzyæ w tê historiê. Ale czy nie mog³eœ po prostu uciec?}
{289} {} {Co ja mam z tym wspólnego?}
{290} {} {Masz na myœli, ¿e akurat tam by³eœ? I ¿e nie masz nic wspólnego ze œmierci¹ kupca? Do diab³a, trudno by³oby udowodniæ, ¿e jest inaczej bez œwiadków.}
{1290} {} {Masz na myœli, ¿e akurat tam by³aœ? I ¿e nie masz nic wspólnego ze œmierci¹ kupca? Do diab³a, trudno by³oby udowodniæ, ¿e jest inaczej bez œwiadków.}
{291} {} {Tak by³o, dowódco.}
{292} {} {(krêci g³ow¹) Wieœniacy... Czego jeszcze mo¿na siê po was spodziewaæ? Masz szczêœcie, ¿e nikt nie widzia³ samej zbrodni, a reputacja Flicka by³a równie tandetna jak jego towary, mo¿esz iœæ. Ale nie zapominaj, ¿e zawsze pilnujemy porz¹dku.}
{293} {} {Cokolwiek powiesz, dowódco.}
{294} {} {Tak by³oby lepiej. Na razie wierzê ci, ale nie zapominaj, ¿e zawsze pilnujemy porz¹dku. Teraz mo¿esz ju¿ iœæ.}
{295} {} {Dziêki, dowódco.}
{296} {} {Uch...}
{297} {} {Ok, najpierw chcê us³yszeæ co siê sta³o miêdzy tob¹ a Flickiem.}

# Villa Defense
{300} {} {Jestem tutaj w imieniu Villi. Potrzebujemy pomocy Rangersów.}
{301} {} {Proszê o pomoc w uwolnieniu ch³opów Villi z niewoli.}
{302} {} {Mieszkañcy Villi nadal potrzebuj¹ pomocy.}
{303} {} {(spogl¹da na swoje raporty, marszcz¹c brwi) Czy Villa jest oaz¹, w której jakimœ cudem na œrodku pustyni roœnie kukurydza? Wspó³czujê wam. Teraz wielu jest trudno. Czerwona plaga z Phoenix rozprzestrzenia siê po ca³ej Arizonie, zniewalaj¹c ludnoœæ i przejmuj¹c zasoby.}
{304} {} {Pamiêtam nasz¹ rozmowê o Villi.}
{305} {} {Wiêc mo¿esz pomóc?}

{306} {} {Przepraszam, brakuje nam Stra¿ników. Rzuciliœmy wszystkie nasze si³y w inne strony.}
{307} {} {Przepraszam.}
{308} {} {Zadnych z was korzyœci, Rangersi.}
{309} {} {}
{310} {} {Najpierw postêpuj zgodnie z moimi instrukcjami, zgodnie z ustaleniami. Do tego czasu nie bêdê móg³ przyj¹æ ciê do genera³a, a tym bardziej przywo³aæ ludzi z innych misji.}
{311} {} {Rozwi¹za³em wszystkie twoje sprawy.}
{1311} {} {Rozwi¹za³am wszystkie twoje sprawy.}
{312} {} {Rzeczywiœcie. Szczerze mówi¹c, nie spodziewa³em siê tego i dawa³em ci te zadania tylko po to, ¿eby Ciê zniechêciæ. Mi³o jest zobaczyæ ¿e jednak Ci zale¿y.}
{313} {} {[Dalej.]}
{314} {} {Ale jeœli chodzi o sytuacjê Villi, decyzja nale¿y do genera³a. IdŸ prosto do niego, powiem Stra¿nikom, ¿eby ciê przepuœcili. Teraz wszystko zale¿y od tego, jak siê z nim dogadasz.}
{315} {} {Dziêkujê, dowódco.}
{316} {} {Ok. Ale jeœli to wszystko posz³o na marne, zrujnujê wasz¹ reputacjê.}

{320} {} {Genera³ obieca³ pomóc ludziom z Villi.}
{321} {} {Cholera, jak uda³o ci siê przekonaæ tego starca?! Mamy lepsze rzeczy do roboty ni¿ ratowanie skór kilku aroganckich ch³opów. Zawsze widzieliœcie nas jako z³odziei. Ale - rozkaz to rozkaz. Villa jest teraz pod niezawodn¹ ochron¹.}
{322} {} {Szczerze mówi¹c, nie jestem zadowolony z tej umowy. Wy, wieœniacy, zawsze uwa¿aliœcie nas za z³odziei. A kiedy sytuacja jest krytyczna, próbujecie nas wykorzystaæ. Ale nie martw siê, dotrzymujemy s³owa - Villa jest teraz pod niezawodn¹ ochron¹. Naprawdê mam nadziejê, ¿e ten sojusz nie oka¿e siê bezczynn¹ paplanin¹.}
{323} {} {Rozumiem ciê, dowódco. Mam nadziejê, ¿e mimo wszystko bêdziemy wspó³pracowaæ.}
{324} {} {Bior¹c pod uwagê takie nastawienie, nie jest zaskoczeniem, ¿e Rangersi maj¹ wielu wrogów. Do widzenia... "amigo".}

# Zadania tematyczne
{330} {} {Mo¿e mogê jakoœ pomóc?}
{331} {} {Zwykle to * my * komuœ pomagamy... ale teraz by³bym wdziêczny za ka¿d¹ pomoc. Nawet od prostego ch³opa.}
{1331} {} {Zwykle to * my * komuœ pomagamy... ale teraz by³bym wdziêczny za ka¿d¹ pomoc. Nawet od prostej ch³opki.}
{332} {} {Co trzeba zrobiæ?}

{333} {} {Porozmawiaj z oficerem ³¹cznikowym w radiostacji, potrzebowa³a sprzêtu. Wróæ do mnie, gdy uporasz siê z tym problemem.}
{334} {} {Brzmi ³atwo, zrobiê to.}
{335} {} {Pewnie d³ugo to zajmie. Ale wygl¹da na to, ¿e nie mam wyboru.}

{336} {} {To nie wszystko. Niedaleko na po³udniu znajduje siê obóz Quartz. Niedawno osiedli³a siê tam grupa wysiedleñców, ale zwiadowcy donosz¹, ¿e wszyscy zniknêli bez œladu. Dowiedz siê, co siê tam wydarzy³o. Nawiasem mówi¹c, kartograf by³ zainteresowany tym miejscem, z nim te¿ porozmawiaj.}
{337} {} {Zajmê siê t¹ mroczn¹ histori¹.}
{338} {} {Innymi s³owy, dajesz mi coœ, czego sam nie mo¿esz rozwi¹zaæ.}

{340} {} {I jeszcze jedna proœba. Straciliœmy jeden z naszych zespo³ów rozpoznawczych na pustyni Mojave na pó³nocy. Nie mamy jeszcze nikogo do wys³ania na akcjê ratunkow¹. Spróbuj dowiedzieæ siê, co siê sta³o ze Stra¿nikami w tamtym regionie.}
{341} {} {Zrobi siê, dowódco.}
{342} {} {Zajmê siê tym jeœli bêdê akurat w pobli¿u.}

{343} {} {Swietnie, czekam na wyniki. Jesteœ wolny.}
{344} {} {[wyjdŸ]}

{350} {} {Mam informacje dotycz¹ce zadañ.}
{351} {} {Raport.}
{352} {} {Szczerze, to nie ma nic do zg³oszenia.}

{353} {} {Radio nie dzia³a. I to nie moja wina.}
{354} {} {(zirytowany) Ju¿ wiem. Jesteœ bezu¿yteczny! (zbiera siê w sobie) Dobra... Oczywiœcie wiem, ¿e to nie twoja wina, w twoim najlepszym interesie le¿a³o pomóc Stra¿nikom.}
{355} {} {Przykro mi, ¿e tak siê sta³o.}
{356} {} {Tylko na mnie nie krzycz.}
{357} {} {Czy mogê zapytaæ o naprawê radia?}
{358} {} {Porozmawiaj o tym z oficerem ³¹cznikowym. Mnie interesuje tylko wynik.}
{359} {} {Ok, porozmawiam z ni¹.}
{360} {} {Ze stacj¹ radiow¹ jest ju¿ wszystko w porz¹dku. Uda³o mi siê j¹ zmodyfikowaæ.}
{361} {} {Dobra robota. Poszerzenie strefy nadawania pomo¿e naszym ludziom w bitwie i czasie pokoju. I to jest to, czego tak bardzo nam brakowa³o. Ale zosta³em te¿ poinformowany o pewnych komplikacjach.}
{362} {} {Racja. Ktoœ przekazywa³ rozmowy Stra¿ników na wschód.}
{363} {} {Wiêc ktoœ szpiegowa³ w naszych transmisjach? Nic dziwnego. Nasza walka z przestêpczoœci¹ polega na odrzuceniu wielu wp³ywowych organizacji na wschodzie. Jedyne dziwne jest to, ¿e ktoœ inny opanowa³ technologiê nadawania fal radiowych. To nie jest umiejêtnoœæ zwyk³ego gangu z pustkowi. Dziêki za pomoc. Twoje informacje mog¹ byæ przydatne w przysz³oœci.}
{364} {} {Mi³o siê przydaæ.}
{1364} {} {Mi³o siê przydaæ.}
{365} {} {Najwa¿niejsze jest to, ¿e pomaga to naszemu sojuszowi.}

{370} {} {Wiem, co siê sta³o w Quartz.}
{371} {} {Wiêc mów, do diab³a, co?}
{372} {} {Miejscowi w niem¹dry sposób napromieniowali okolice i oszaleli.}
{373} {} {Ta holotaœma zawiera wszystkie informacje.}
{374} {} {Uch, nie mam pojêcia.}
{375} {} {(wzdycha) Idioci... Oto przyk³ad tego, jak bezmyœlny podziw dla technologii staro¿ytnych rujnuje ludzi. O czym oni myœleli? Ze mog¹ tak po prostu uruchomiæ tê star¹ technologiê i wszystko bêdzie dobrze? Informacje o niej zaginê³y wiele pokoleñ temu! Nic dziwnego, ¿e ci idioci tak drogo zap³acili za swoj¹ pró¿noœæ.}
{376} {} {I tak by do tego dosz³o.}
{377} {} {Tym lepiej, ¿e nikt nie dostanie teraz tej relikwii.}
{378} {} {Mo¿e tak. I tak da³eœ z siebie wszystko. Umieœcimy znaki ostrzegawcze na ca³ym obwodzie i zaalarmujemy wszystkich funkcjonariuszy patroluj¹cych pobliskie tereny. Dziêkujê za pomoc.}
{1378} {} {Mo¿e tak. I tak da³aœ z siebie wszystko. Umieœcimy znaki ostrzegawcze na ca³ym obwodzie i zaalarmujemy wszystkich funkcjonariuszy patroluj¹cych pobliskie tereny. Dziêkujê za pomoc.}
{379} {} {Nie ma za co.}
{380} {} {Ok.}

{390} {} {Chcê zg³osiæ zbrodnie Stra¿nika Gartha.}
{391} {} {Kolejny... Regularnie mam do czynienia z oszczerstwami wobec Stra¿ników. Ponadto Ranger Garth zawsze by³ wzorem dla innych. Generalnie nie mam czasu na te bzdury, wynoœ siê st¹d.}
{392} {} {Hm...}
{393} {} {Mimo to William Garth okaza³ siê kryminalist¹. Kto by pomyœla³? Tyle nagród i rekomendacji... Wiesz, spokojne ¿ycie zrujnowa³o tego Wojownika. Po przejœciu na emeryturê zacz¹³ postrzegac ka¿dego nieznajomego jako potencjalnego wroga. Bojê siê wyobraziæ sobie, co siê ze mn¹ stanie w takich warunkach.}
{394} {} {Wszyscy mamy swoje problemy. W porz¹dku, dowódco.}
{395} {} {Jego historia bêdzie pouczaj¹ca dla reszty Wojowników. I dla ciebie te¿, dowódco.}

# Dodatkowe zadania
{400} {} {Chcê dalej pomagaæ Rangersom.}
{401} {} {Chwalebny zapa³. Naprawdê potrzebujemy dodatkowych par nóg, r¹k i oczu.}
{402} {} {Dobrze, pójdê coœ zrobiæ.}
{403} {} {Przepraszam. Mo¿e s¹ inne zadania?}

{410} {} {Mogê pomóc w rozpoznaniu dalekiego terenu.}
{411} {} {To by³oby bardzo pomocne. Straciliœmy jedn¹ z naszych grup rozpoznawczych na pó³nocy, na pustyni Mojave. Nie mamy jeszcze nikogo do wys³ania na akcjê ratunkow¹. Spróbuj dowiedzieæ siê, co siê sta³o ze Stra¿nikami w tamtym rejonie.}
{412} {} {Zrobiê co w mojej mocy.}
{413} {} {Có¿, jeœli bêdê w pobli¿u, spróbujê.}
{414} {} {Swietnie, czekam na raport.}
{415} {} {Czy jest wiêcej misji?}
{416} {} {[wyjdŸ]}

{420} {} {Czy potrzebujesz kogoœ do pomocy?}
{421} {} {Jest jedna rzecz, specjalnie dla ciebie. Czekaliœmy na grupê uchodŸców ze wschodu. Ale zwiadowcy twierdz¹, ¿e zjechali z trasy i udali siê w kierunku Garage City. Prawdopodobnie bêdziesz w pobli¿u, wiêc zajrzyj tam i dowiedz siê, co spowodowa³o zmianê trasy.}
{422} {} {Oczywiœcie, znajdê tych ludzi i wyci¹gnê z nich prawdê.}

{430} {} {Uda³o mi siê znaleŸæ uchodŸców w Garage City. Niestety zmarli ju¿ przed moim przybyciem.}
{431} {} {Cholera. Co siê sta³o?}
{432} {} {Zostali zabici jak psy. Miejscowi nie lubi¹ obcych.}
{433} {} {Có¿, mo¿na powiedzieæ, ¿e byli w niew³aœciwym miejscu o niew³aœciwej porze.}
{434} {} {Nie mam pojêcia.}
{435} {} {Ech. Nawet padlino¿ercy w naszych czasach s¹ gotowi pope³niaæ przestêpstwa z powodu swojej nienawiœci do obcych. Jak widaæ, ten œwiat potrzebuje pewnej rêki, aby trzymaæ ludzi za lini¹ przestêpcz¹.}
{436} {} {[Dalej.]}
{437} {} {Dziêkujê za pomoc. Oszczêdzasz nam wiele niepotrzebnej pracy.}
{438} {} {Nie ma za co.}
{439} {} {To nie dla ciebie, ale dla bezpieczeñstwa Villi.}
{440} {} {Uda³o mi siê znaleŸæ uchodŸców w Garage City. Byli zastraszani w imieniu Stra¿ników.}
{441} {} {Wiêc ktoœ podszywa³ siê pod Stra¿nika?}
{442} {} {Dok³adnie. Oto odznaka tego z³oczyñcy. Nie bêdzie ju¿ przeszkadza³.}
{443} {} {Ile to sztuczek wykorzystuj¹ przestêpcy, aby osi¹gn¹æ swój cel... Z pewnoœci¹ mia³ wiele wymówek dla swojej nieprawoœci.}
{444} {} {[Dalej.]}
{445} {} {To nie pierwszy raz, kiedy ktoœ sabotuje nasz¹ reputacjê. Na wschodzie si³y stoj¹ w gardle naszych dzia³añ. Ale œwiat siê zmienia - wczeœniej przestêpcy byli zaanga¿owani w przetrwanie, teraz s¹ organizowani i sponsorowani przez klientów. Ale to nic - poradzimy sobie i z t¹ spraw¹.}

{450} {} {Planuje tu zostaæ. Masz zadania bli¿ej bazy?}
{451} {} {Powiedziano nam o epidemii w Akwedukcie, jednej ze spo³ecznoœci na wybrze¿u Kolorado. Udaj siê tam i zobacz, jak mo¿emy pomóc.}
{452} {} {Zrobi siê, dowódco.}

{453} {} {Wiem, co spowodowa³o epidemiê - napromieniowane towary Flicka.}
{454} {} {Flick sprzedawa³ radioaktywne produkty? Ju¿ wczeœniej kr¹¿y³y takie plotki, ale nikt nie móg³ udowodniæ jego oszustwa.}
{455} {} {Oczywiœcie nie bêdzie ju¿ przeszkadza³ nikomu poza d¿d¿ownicami.}
{456} {} {Tak, wiem o jego œmierci. Sprawiedliwoœæ znalaz³a go przed nami. Dziêki za pomoc, ale sami mogliœmy to rozwi¹zaæ.}
{457} {} {Proszê.}
{458} {} {Do widzenia.}
{459} {} {Teraz nie bêdzie móg³ siê wydostaæ.}
{460} {} {Dobrze. Ale Flick ju¿ wyruszy³ na pustyniê. Poœpiesz siê, zanim zajdzie za daleko. Musisz odebraæ wszystkie jego napromieniowane towary... w jakikolwiek sposób.}
{461} {} {Zrobi siê!}
{462} {} {Och, iœæ i znowu sma¿yæ siê na tym pustkowiu...}
{463} {} {Koniec problemów z Flickem. Teraz handluje w piekle.}
{464} {} {Czyli on... Flick nie ¿yje? Do diab³a, nie spodziewa³em siê, ¿e podejmiesz tak ekstremalne kroki. Jednak nie chcê wiedzieæ nic wiêcej o tej historii. Dziêki za pozbycie siê tego problemu.}
{465} {} {Do widzenia.}
{466} {} {Flick zosta³ bez swoich *specjalnych* towarów. Na d³ugo zapamiêta tê lekcjê.}
{467} {} {Dobra robota! Flick to sukinsyn, ale jest te¿ niezast¹pionym handlarzem. Dobrze, ¿e uratowa³ ¿ycie i straci³ tylko swój dobytek. Niestety nie mamy nagrody za t¹ przys³ugê, wiêc weŸ czêœæ moich zapasów. (daje Ci dwie u¿ywki i antidotum) mo¿esz to sprzedaæ komuœ innemu, jeœli tego nie potrzebujesz.}
{468} {} {Cieszê siê, ¿e mog³em pomóc.}
{1468} {} {Cieszê siê, ¿e mog³am pomóc.}
{469} {} {Niewiele, ale lepsze to ni¿ nic.}