{100} {} {Widzisz pacjenta.}
{101} {} {Widzisz chorego. Drêczy go pragnienie i dreszcze.}
{102} {} {Badanie wykaza³o, ¿e pacjent cierpi z powodu choroby popromiennej.}
{103} {} {Pacjent jest gotowy do badania.}

{210} {} {(przed sob¹ widzisz chorego wieœniaka; drêczy go pragnienie, zimny pot, dreszcze i zadyszka)}
{211} {} {[ulecz chorobê]}
{212} {} {Jak siê czujesz, kolego?}
{213} {} {Khe, khe... Wracam do normalnoœci. Wczoraj by³o naprawdê Ÿle, myœla³em, ¿e nie prze¿yjê.}
{214} {} {Jak myœlisz, co spowodowa³o chorobê?}
{215} {} {Nic nie przychodzi mi do g³owy. Jad³em te same ryby co zwykle, chodzi³em w te same miejsca, co poprzednio.}
{216} {} {Czy mog³eœ zostaæ zara¿ony przez kogoœ innego?}
{217} {} {Prawdopodobnie... khe, khe... Ale wtedy inni te¿ zostaliby zara¿eni.}
{218} {} {Muszê znaæ przyczynê choroby. Czy mogê ciê zbadaæ?}
{219} {} {Ok. Zdj¹æ ubranie?}
{220} {} {Tak...}
{221} {} {Rozumiem.}
{222} {} {Wygl¹da na to, ¿e cierpisz z powodu du¿ej dawki promieniowania.}
{223} {} {Co? Ale jak? Nie ma tu ¿adnych potê¿nych Ÿróde³ promieniowania.}
{224} {} {Wiêc promieniowanie przysz³o z zewn¹trz. Co ostatnio jad³eœ?}
{225} {} {Tylko ryby i chleb, które s¹ rozprowadzane w spo³ecznoœci... Nie, czekaj, kupi³em te¿ Nuka Colê od Flicka. Myœlisz, ¿e kilka butelek mog³oby mnie naprowieniowaæ?}
{226} {} {Niewykluczone. Powinienem to sprawdziæ...}