{100} {} {Widzisz Starego Rufusa.}
{101} {} {Widzisz opiekuna tamy - nieogolonego, ¿ylastego staruszka w roboczym kombinezonie.}

# Pierwszy dialog
{200} {} {(widzisz siwego, nieogolonego mê¿czyznê po piêædziesi¹tce; brudne ubranie robocze zdradza jego zawód) He? Przepraszam, jestem trochê g³uchy. Pracuj przez tyle lat wœród tych ha³aœliwych sprzêtów, a ty te¿ stracisz s³uch.}
{201} {} {Bêdê pamietaæ.}
{202} {} {Kim jesteœ? Nie pamiêtam ciê, ale znam tu wszystkich. Rekruci zwykle nie s¹ wpuszczani na stacjê, a karawanami zajmuje siê kwatermistrz. Wiêc...}
{203} {} {Jestem tu w interesach.}
{204} {} {Tak. W interesach. Niech tak bêdzie. Najwa¿niejsze, ¿eby nie przeszkadzaæ innym interesom.}
{205} {} {Co robisz, staruszku?}
{206} {} {Wiêc nie bêdê siê wtr¹caæ.}

# Powtarzajacy siê dialog
{210} {} {Mów g³oœniej, dlaczego mamroczesz?}
{211} {} {Zegnam siê.}
{212} {} {Mam jeszcze jedno pytanie.}
{213} {} {Kolejne pytanie.}

#Zapytania
{220} {} {Kim jesteœ?}
{221} {} {Nazywam siê Rufus. Jestem opiekunem tamy. Upewniam siê, ¿e nic siê tutaj nie rozpadnie.}
{222} {} {Jak¹ masz rangê, Rufusie?}
{223} {} {Nie mam rangi. Pracujê tutaj, a nie s³u¿ê.}
{224} {} {Jak d³ugo zajmujesz urz¹d?}
{225} {} {Pozwól, ¿e pomyœlê, ju¿ chyba od trzydziestu lat. Nikt tutaj nie liczy lat.}
{226} {} {Dlaczego Stra¿nicy osiedlili siê na tej tamie?}
{227} {} {Jest ku temu wiele powodów: jest to forteca nie do zdobycia dla wrogów, ochrona przed burzami piaskowymi, obfite Ÿród³o wody i nieskoñczona energia. Mo¿na powiedzieæ, ¿e sta³o siê to tak historycznie.}
{228} {} {Jestem opiekunem tamy. Upewniam siê, ¿e nic siê tutaj nie rozpadnie.}
{229} {} {Wiêc co robisz, Rufusie?}

{230} {} {Czy akwedukt te¿ jest czêœci¹ elektrowni?}
{232} {} {Nie, nie, stacja dzia³a bez akweduktu. Ale akwedukt nie by³by w stanie pe³niæ swoich funkcji bez naszej tamy. Jednak nadal nie dzia³a.}
{231} {} {Co siê z nim dzieje?}
{233} {} {Czas zebra³ swoje ¿niwo. Pompy od dawna nie dzia³aj¹ i nie mo¿na ich naprawiæ. Ponadto zmniejszy³ siê przep³yw wody w rzece. Ale nawet gdyby akwedukt dzia³a³, by³by bezu¿yteczny. Przecie¿ na jego drodze nie ma ju¿ plantacji i osad, które czerpa³yby korzyœci z tej wody.}
{234} {} {Niesamowita struktura. Kto to wszystko zbudowa³?}
{235} {} {Ludzie w przesz³oœci byli bardzo m¹drzy. Nikt ¿yj¹cy dzisiaj nie by³by do tego zdolny.}
{236} {} {Czy zapomnia³eœ ju¿, ¿e sami siebie zniszczyli?}
{237} {} {Tak... Ale to nie zmienia faktu, ¿e stworzyli akwedukt do nawadniania pustynnych krain.}

# Pierwsze zadanie
{250} {} {Czy istnieje jakieœ ryzyko?}
{251} {} {Och, ta starsza pani widzia³a lepsze czasy! Na przyk³ad ten kontroler nie chce w ¿aden sposób dzia³aæ. I nigdzie nie ma zamiennika - ca³e wyposa¿enie jest tutaj jedyne w swoim rodzaju.}
{252} {} {Wiêc to nie dzia³a? Mo¿e uda mi siê to naprawiæ?}
{253} {} {Gdzie idziesz! Tutaj same umiejêtnoœci nie wystarcz¹. Jednak du¿o podró¿ujesz, prawda? Jeœli znajdziesz czêœci ze sprzêtu elektronicznego, przynieœ je tutaj, mo¿e za ich pomoc¹ uda siê to naprawiæ.}
{254} {} {Zobaczê, co da siê zrobiæ.}
{255} {} {Obawiam siê, ¿e to naprawdê nie jest moja specjalnoœæ. Ale mogê znaleŸæ czêœci.}
{256} {} {To dobrze. W miêdzyczasie gdy ty udajesz bohatera, myœlê, ¿e ja zabiorê siê do pracy. Nie obraŸ siê.}
{257} {} {Uch, nie, muszê wiedzieæ wiêcej.}
{258} {} {W takim razie porozmawiamy póŸniej.}

{260} {} {Porozmawiamy o tym zepsutym kontrolerze?}
{261} {} {Huh? Co ty kombinujesz?}
{1261} {} {Huh? Co ty kombinujesz?}
{262} {} {Tak, bez w¹tpienia.}

{263} {} {Co to za problem poszukaæ czêœci elektronicznych?}
{264} {} {Myœlisz, ¿e nie szukaliœmy? Wszystkie patrole i handlarze siê za tym rozgl¹daj¹. Ale gdzie na wsi mamy znaleŸæ elektronikê? A do du¿ych miast jest daleko i drogo w sprowadzeniu jej. I jest tam sporo innych chêtnych.}
{265} {} {Do czego s³u¿y ten kontroler?}
{266} {} {Spójrz na tê wielk¹ rzecz na œrodku pokoju. Wewn¹trz znajduje siê œmig³o zanurzone w rzece Kolorado. Obraca siê i wytwarza pr¹d... Wiesz, co to jest „pr¹d”?}
{267} {} {Chyba siê domyœlam...}
{268} {} {Poprzez kontroler pr¹d jest kierowany do transformatorów mocy na zewn¹trz, a nastêpnie do linii energetycznych. Ale teraz nic tam nie dzia³a - zosta³y tylko go³e i bezu¿yteczne przewody.}
{269} {} {Muszê wiedzieæ wiêcej.}

{270} {} {Uda³o mi siê naprawiæ sprzêt.}
{271} {} {Nie rób sobie ¿artów - Rangersi czasami maj¹ problemy z humorem. Szczególnie w temacie tej tamy.}
{272} {} {Ale to dzia³a. Spójrz.}

{273} {} {Zobaczmy... Swiêty Bo¿e, to naprawdê dzia³a!}
{274} {} {Nie pracujê za darmo, wiesz?}
{275} {} {Tak... oczywiœcie. Oto pakiet baterii nuklearnych za twoj¹ pracê. Jeœli nie s¹ ci potrzebne, wymieñ je w najbli¿szym mieœcie na coœ po¿ytecznego.}
{276} {} {Nie ma za co.}
{277} {} {Stra¿nicy nie zapominaj¹ o swoich przyjacio³ach. Oto pakiet baterii nuklearnych za twoj¹ pracê. Jeœli nie s¹ ci potrzebne, wymieñ je w najbli¿szym mieœcie na coœ po¿ytecznego.}
{278} {} {[Dalej.]}
{279} {} {Dziêki. Szkoda, ¿e nie mo¿esz mnie zast¹piæ na tym stanowisku po przejœciu na emeryturê. Teraz zostaw mnie na chwilê z tym dzieckiem. Potrzebuje dodatkowej opieki.}
{280} {} {Ok, wrócê póŸniej... kiedy o¿ywisz to ¿elazo.}
{281} {} {Tylko nie przesadzaj, staruszku. Przewody mog¹ zareagowaæ na Twoje pieszczoty pr¹dem.}
{282} {} {}
{283} {} {Gdzie mogê znaleŸæ czêœci elektroniczne?}
{284} {} {Najbli¿sze znane mi miejsce to Garage City. Tak, tylko ju¿ wys³aliœmy tam kogoœ do tego zadania.}

# Drugie zadanie
{300} {} {Jak stacja dzia³a po naprawiê?}
{301} {} {Swietnie! Remont stacji nie zagra¿a nadchodz¹cym latom. Chcia³bym, ¿ebyœ móg³ mnie zast¹piæ w tym miejscu po przejœciu na emeryturê.}
{302} {} {Wiêc jesteœ jedyn¹ osob¹ obs³uguj¹c¹ tamê?}
{303} {} {(wzdycha) Czasami s³ucham ha³asu jednostek hydraulicznych. Ich rotacja, skrzypi¹ca od rdzy, przypomina mi minione lata.}
{304} {} {Chyba potrzebujesz zmiany.}
{305} {} {Zgadza siê, kolego. Ta stacja potrzebuje nowego dozorcy - m³odego cz³owieka obdarzonego umiejêtnoœciami technicznymi, a takich w naszych czasach szukaæ ze œwiec¹.}
{1305} {} {Zgadza siê, kole¿anko. Ta stacja potrzebuje nowego dozorcy - m³odego cz³owieka obdarzonego umiejêtnoœciami technicznymi, a takich w naszych czasach szukaæ ze œwiec¹.}
{306} {} {Czy masz kogoœ konkretnego na myœli?}
{307} {} {Ludzie z karawany mówili o jednym takim m³odym talencie. Mieszka w Garage City i cierpi na marnowanie czasu. Chcia³bym na niego spojrzeæ i przygotowaæ go do zast¹pienia mnie. Problem polega na tym, ¿e miejscowa ludnoœæ nie darzy Stra¿ników sympati¹, wiesz? I bez tego nie mo¿emy po prostu przyjœæ i odebraæ dziecka, potrzebujemy, ¿eby sam chcia³.}
{308} {} {Przyjmê tê pracê.}
{309} {} {Kto szuka czegokolwiek w tym œmietniku... za³atwiê ci tego dzieciaka.}
{310} {} {Có¿, wygl¹da na to, ¿e bêdziesz musia³ znaleŸæ zamiennika gdzieœ indziej. Czeœæ, staruszku.}
{311} {} {To w³aœnie jest determinacja! To ona odró¿nia zielonych od starych ludzi. Zgoda. Bêdê czekaæ na Twój powrót.}
{312} {} {Do widzenia.}

{320} {} {Z³e wieœci - ten facet z Garage City zgin¹³ w drodze.}
{321} {} {Przykro mi z powodu goœcia, by³by niezwykle przydatny dla Stra¿ników w przysz³oœci... Có¿, teraz muszê wspó³pracowaæ z lokalnymi ch³opakami, chocia¿ wœród nich nie ma ani jednego mi³oœnika technologii. Nie mam dla ciebie wiêcej zadañ. Dziêkujê za twoj¹ przys³ugê.}
{322} {} {Nie dostanê nic za swoj¹ pracê?}
{323} {} {Twoja praca by³a bezu¿yteczna. IdŸ gdzieœ i nie zawracaj sobie ju¿ g³owy prac¹.}
{324} {} {A wiêc to wszystko...}

{330} {} {Oto ten utalentowany facet, którego szuka³eœ.}
{331} {} {Witaj synu! Tutaj, u Rangersów, na pewno ci siê spodoba. Widzê to w moich oczach. Ale najpierw nie zaszkodzi ciê trochê umyæ...}
{332} {} {Ahem...}
{333} {} {...A ty wyœwiadczy³eœ Rangersom wspania³¹ przys³ugê, sprowadzaj¹c tego goœcia. Wpadnij do kwatermistrza, aby znaleŸæ nagrodê dla siebie.}
{1333} {} {...A ty wyœwiadczy³aœ Rangersom wspania³¹ przys³ugê, sprowadzaj¹c tego goœcia. Wpadnij do kwatermistrza, aby znaleŸæ nagrodê dla siebie.}
{334} {} {Swietnie, czekaj na mnie nagrodo! Ju¿ nadchodzê.}