{100} {} {Widzisz kupca Flicka.}
{101} {} {Widzisz Flicka, wêdrownego kupca.}
{102} {} {Koniec z Nuka Col¹... serio.}
{103} {} {Kupiec straci³ szkodliwy towar. Pozostaje zg³osiæ sukces dowódcy Helfordowi.}

# Rozpocznij dialog
{200} {} {Hej podró¿niku, potrzebujesz kilku przydatnych rzeczy na podró¿? Mogê dostaæ wszystko... Ale czekaj, sprzeda³em ca³y towar tym Stra¿nikom. Hik.}
{201} {} {Wiêc jesteœ sprzedawc¹?}
{202} {} {Nazywam siê Flick. Wymieniam ka¿dy drobiazg na ziemiach Rangersów. Czego szukasz? Powiedz mi, mo¿e wiem, sk¹d to wzi¹æ?}
{203} {} {Pewnie nie masz tego, czego potrzebujê. Trudno, Flick.}

{210} {} {Czego szukasz? Powiedz mi, mo¿e wiem, sk¹d to wzi¹æ?}
{211} {} {Do zobaczenia.}
{212} {} {Zmieñmy temat.}

#Pytania
{220} {} {Czym handlujesz, Flick?}
{221} {} {Mogê handlowaæ tym, czym siê handluje - jedzeniem, ubraniami, sprzêtem gospodarstwa domowego. Ale teraz nie zosta³o mi nic poza kapslami.}
{222} {} {Co to za historia z kapslami?}
{223} {} {Nie wiesz? W du¿ym mieœcie na wschodzie ktoœ pomyœla³ o u¿yciu kapsli jako waluty. To znaczy do wymiany na towary. Dziwny pomys³, ale wygodny! Jedynym problemem jest to, ¿e Stra¿nicy nie uznaj¹ kapsli i odmawiaj¹ handlu nimi.}
{224} {} {Czy to uczciwe?}
{225} {} {Có¿, myœlê, ¿e ta waluta jest spekulacyjna. W koñcu nigdy nie znasz prawdziwej wartoœci kapsli. A wymiana barterowa jest uczciwa i nie podlega tam ¿adnej „inflacji”. Jednak wielu z ludzi ju¿ teraz handluje kapslami, któregoœ dnia Stra¿nicy bêd¹ zmuszeni siê zmieniæ.}
{226} {} {Jak ciekawie. Porozmawiajmy trochê wiêcej, nie œpieszysz siê, prawda?}
{227} {} {Dbam o moich krewnych, nie o walutê. Bywaj.}

{230} {} {Sk¹d masz tego bramina?}
{231} {} {Kupi³em od farmerów w pobliskim mieœcie. Zwierze by³o drogie, ale zwróci³o siê w mgnieniu oka.}
{232} {} {Wierzê. Ale doœæ o braminach.}
{233} {} {Rozumiem. Czeœæ.}
{234} {} {By³em w San Brahmin. Maj¹ tam bardzo wysokie ceny za takie zwierzêta.}
{235} {} {Coœ sugerujesz? Hej, nie ukrad³em tego giganta! Ale nie wiem, sk¹d wzi¹³ go sprzedawca.}
{236} {} {Tak. Pewnie. Co jeszcze ciekawego mo¿esz mi powiedzieæ?}
{237} {} {Uch, nie chcê wiedzieæ nic wiêcej. Do widzenia.}

{240} {} {Nie boisz siê wêdrowaæ po pustyni?}
{241} {} {To s¹ ziemie Stra¿ników - najbezpieczniejsze miejsca, jakie znam.}
{242} {} {Nie podoba mi siê sposób, w jaki patrzy na mnie twój ma³y ochroniarz.}
{243} {} {Wiêc prawdopodobnie odpowiesz na kilka dodatkowych pytañ.}
{244} {} {Muszê ju¿ ruszaæ w drogê. Pa, Flick.}
{245} {} {(wzdycha) To jest mój syn. Jest trochê niedorozwiniêty, wiêc nie przeszkadzaj mu.}
{246} {} {Nie zamierzam. Lepiej pomêczê ciê kilkoma nowymi pytaniami.}
{247} {} {Powinieneœ by³ mnie od razu ostrzec. Chyba jednak pójdê dalej... drug¹ stron¹ drogi.}

{250} {} {Czy by³eœ kiedyœ w Quartz?}
{251} {} {Zajrza³em tam dok³adnie raz. Miejscowi okazali siê tak biedni i wrogo nastawieni do obcych, ¿e nie chcê ju¿ z nimi handlowaæ.}
{252} {} {Tak bardzo s¹ nieprzyjaŸni? Bêdê o tym pamietaæ.}

{260} {} {Muszê siê dostaæ do Genera³a Rangersów.}
{261} {} {Có¿, niebardzo mogê ci w tym pomóc. Ale wiesz co, nie wpuszcz¹ ciê do tamy bez dobrego powodu. ZaprzyjaŸnij siê ze Stra¿nikami, mo¿e to pomo¿e. Dlaczego potrzebujesz genera³a?}
{262} {} {Tak, chcia³em ciê zobaczyæ.}
{263} {} {Hmmm. Tak jak mówisz.}
{264} {} {Hmmm. (zastanawia siê, ocenia perspektywy) Cholera, za daleko i niebezpiecznie... Uh, to znaczy, nie mogê ci pomóc.}
{265} {} {Handlarze niewolnikami porwali moich ludzi. Mam nadziejê, ¿e Stra¿nicy pomog¹ mi ich odzyskaæ.}
{266} {} {W¹tpiê, kolego. Ale porozmawiaj z dowódc¹ w centrum informacyjnym. Gdzie znajduje siê ta twoja wioska?}
{267} {} {To jest... daleko st¹d.}
{268} {} {Hmmm. DOBRZE.}
{269} {} {Pó³noc. To miejsce nazywa siê Villa.}

{270} {} {Hej, pamiêtam ciê. Wêszy³eœ tutaj, zanim tama zosta³a zmyta przez wody Kolorado.}
{271} {} {Tak. Co tu robisz po tym wypadku?}
{272} {} {Wojownicy maj¹ teraz du¿e k³opoty i pachnie tu chaosem. Ale wiesz co - w ca³ym tym ba³aganie moje us³ugi i towary s¹ nadal doceniane. Tylko muszê teraz... trochê zmieniæ asortyment.}
{273} {} {Na przyk³ad sprzedajesz broñ, alkohol i narkotyki?}
{274} {} {Nie mów o tym tutaj, mog¹ nas pods³uchiwaæ. Ale dopóki Stra¿nicy nie odzyskaj¹ kontroli nad swoimi ziemiami, stwarza to wspania³e perspektywy dla wczeœniej niechcianych interesów. Mam ³eb, co?}
{275} {} {Rób, co chcesz.}
{276} {} {Twój interes prêdzej czy póŸniej zakoñczy siê. A nasza rozmowa koñczy siê w³aœnie teraz.}

# Dialog na mapie drogowej
{300} {} {Czego chcesz? Przys³ali ciê Rangersi?}
{301} {} {S³yszê w twoich s³owach nutê zdenerwowania. Wiesz, ¿e ju¿ Ciê szukaj¹?}
{302} {} {Tak, wiem. Ale najpierw udowodnij, ¿e to napromieniowana cola spowodowa³a epidemiê! Mój towar by³ * bezpieczny *. Rozumiesz?}
{303} {} {Wszyscy tak mówi¹. Co powiesz na sprawdzenie za pomoc¹ licznika?}
{304} {} {Co... Cholera, zostaw moje towary. OdejdŸ ode mnie!}
{305} {} {...}

{310} {} {Zostaw mnie. Nie oddam mojego towaru.}
{311} {} {Ok.}
{312} {} {Mogê odkupiæ ca³¹ napromieniowan¹ Nuka Colê.}
{313} {} {Dostaniesz za to du¿o kapsli. Ale zawsze chêtnie wymieniam œmieci na coœ po¿ytecznego. Poka¿, co masz.}
{314} {} {[Dalej.]}
{315} {} {Do zobaczenia.}
{316} {} {Dasz mi ca³¹ napromienion¹ colê. Bez negocjacji.}
{317} {} {Tylko spróbuj!}
{318} {} {[Atak]}
{319} {} {Powinieneœ by³ mnie pos³uchaæ.}