{100} {} {Widzisz stra¿nika Flicka.}
{101} {} {Widzisz g³upiego ch³opca.}

{110} {} {Porozmawiaj z Flickiem, on wie wszystko.}
{111} {} {Flick jest sprytny, zmienia niepotrzebne na konieczne.}
{112} {} {Potrzebujesz przydatnych przedmiotów? Flick ma wszystko.}
{113} {} {Ja tylko strzegê towaru, dobrze?}
{114} {} {Masz wodê ognist¹?}
{115} {} {Kiedy Flick robi bo-bo, p³aczê.}
{116} {} {Nie próbuj okradaæ w³aœciciela.}
{117} {} {Wykrêcam rêce tym, którzy okradaj¹ Flicka.}
{118} {} {Bêdê ciê pilnowaæ.}
{119} {} {Chcesz dostaæ w³óczni¹?}
{120} {} {Mistrz mówi, ¿e czas iœæ.}