{100} {} {Widzisz ¿onê rolnika.}
{101} {} {Widzisz ¿onê rolnika, zajêt¹ swoj¹ zwyk³¹ dzia³alnoœci¹ rolnicz¹.}

# Losowe repliki
{110} {} {* Spiewa *}
{111} {} {Wiatr siê wzmaga.}
{112} {} {Jak zacznie siê burza piaskowa mo¿emy tylko czekaæ na jej koniec.}
{113} {} {W tym sezonie zbiory znowu bêd¹ kiepskie.}
{114} {} {Chcia³abym, ¿eby ci ch³opi z pó³nocy podzielili siê nasionami.}
{115} {} {Jestem taka zmêczona...}
{116} {} {Bêdziemy musieli znaleŸæ nowego psa.}
{117} {} {Te radskorpiony to prawdziwe bestie.}
{118} {} {Ostatnio coraz wiêcej tu podró¿ników.}
{119} {} {To nasza ziemia.}

{120} {} {Nic, Stra¿nicy nas ochroni¹.}
{121} {} {Mam nadziejê, ¿e nie bêdzie ju¿ dziœ kolejnych goœci.}
{122} {} {Nie wiem, co byœmy zrobili bez Rangersów.}
{123} {} {Dopóki Stra¿nicy s¹ w pobli¿u, mo¿esz spaæ spokojnie.}
{124} {} {Stra¿nicy znaj¹ siê na rzeczy.}

{125} {} {Kto nas teraz ochroni?}
{126} {} {Bez Rangersów bêdziemy ³atwym celem dla bandytów.}
{127} {} {Nie opuszczê ziemi, w która zainwestowa³am ca³e ¿ycie!}
{128} {} {Ktokolwiek zniszczy³ tamê, zabi³ wszystkich osadników w okolicy.}
{129} {} {Jaki drañ odwa¿y³ siê pope³niæ takie okrucieñstwo?}

{130} {} {Hrrrr}
{131} {} {* ziewa *}
{132} {} {...Wstanê jutro wczeœnie...}
{133} {} {...Jestem taka zmêczona...}
{134} {} {Zzz}
{135} {} {* Chrapie *}

#Dialog
{200} {} {Och, mamy goœci! Chyba nie widzia³am ciê wczeœniej. Jak masz na imiê?}
{201} {} {.}
{202} {} {Cz³owiek z Pustkowii.}
{203} {} {Có¿, mi³o ciê poznaæ, }
{204} {} {. Ale jeœli potrzebujesz zakwaterowania lub jedzenia, skontaktuj siê ze Stra¿nikami. Ich osada znajduje siê przy drodze, zaledwie kilka godzin marszu.}
{205} {} {Có¿, mi³o ciê poznaæ... cz³owieku o dziwnym imieniu.}
{206} {} {To dlaczego tu mieszkasz?}
{207} {} {Wygl¹da na to, ¿e po prostu próbujesz mnie wyrzuciæ.}
{208} {} {Dlaczego jesteœ taki niegrzeczny? Mamy spokojn¹ farmê. A jeœli zamierzasz byæ awanturniczy, pamiêtaj, ¿e to terytorium Rangersów. A oni nie lubi¹ awanturników...}
{209} {} {Ok, okej, rozumiem.}
{210} {} {To dobrze.}
{211} {} {Ale dlaczego mieszkacie w takiej izolacji?}
{212} {} {Zadne plony nie rosn¹ na ska³ach. Poza tym nie lubimy zat³oczonych miejsc.}
{213} {} {Czy mogê prosiæ ciê o wodê?}
{214} {} {Rozumiem. Có¿, nie bêdê ju¿ odwraca³ Twojej uwagi od prac domowych.}
{215} {} {O wszystkich sprawach w domu decyduje m¹¿. Porozmawiaj z nim.}

{220} {} {Och, pamiêtam ciê.}
{221} {} {Do widzenia.}
{222} {} {Powinnieneœ siê st¹d wydostaæ, zanim Stra¿nicy Ciê znajd¹. A zrobi¹ to.}
{1222} {} {Powinnaœ siê st¹d wydostaæ, zanim stra¿nicy Ciê znajd¹. A zrobi¹ to.}
{223} {} {SiedŸ spokojnie, staruszko.}
{224} {} {Przepraszam, nie bêdê ci wiêcej przeszkadzaæ.}