{100} {} {Widzisz farmera.}
{101} {} {Widzisz typowego rolnika prowadz¹cego swoj¹ zwyk³¹ pokojow¹ dzia³alnoœæ.}

# Pierwszy dialog
{200} {} {Wynoœ siê st¹d i nie wracaj! Nie ma tu nic, co mog³oby zepsuæ ¿ycie spokojnym ludziom. A gdy tylko ziemia ciê poch³onie...}
{201} {} {Nie podniecaj siê tak staruszku.}
{202} {} {Nie sprawiê ci k³opotów.}

{210} {} {(Przed tob¹ stoi rolnik w kraciastej koszuli, postrzêpionych roboczych spodniach i dziurawej czapce; kiedy siê zbli¿asz, chwyta grabie w d³onie i mru¿¹c oczy patrzy na ciebie od stóp do g³ów; wydaje siê, ¿e nie przepada za d³ugimi rozmowami.)}
{211} {} {Przepraszam, ¿e przeszkadzam. Szukam najbli¿szej osady.}
{212} {} {Hej staruszku, gdzie jest najbli¿szy bar? Pilnie potrzebujê drinka.}
{213} {} {Jesteœ nowy w tym obszarze? Có¿, witaj na ziemiach Rangersów. Jeœli potrzebujesz zakwaterowania lub ochrony, idŸ dalej drog¹ - tam Stra¿nicy za³o¿yli swoj¹ cytadelê, tu¿ przy starej tamie.}
{214} {} {Czy mogê zadaæ kilka pytañ?}
{215} {} {Dziêki, zaraz tam pójdê.}
{216} {} {W¹tpiê, czy znajdziesz tutaj to, czego szukasz. Wzd³u¿ drogi, tu¿ przy starej tamie, znajduje siê baza Stra¿ników. I nie spodoba im siê, jeœli pojawisz siê tam z tym samym pytaniem.}

{220} {} {Có¿, co powiesz?}
{221} {} {Nie ci¹gnij za ogon iguany, pytaj.}
{222} {} {To ciekawe. Coœ jeszcze?}
{223} {} {Wydaje siê, ¿e radzisz sobie ca³kiem nieŸle. Porozmawiajmy o czymœ innym.}
{224} {} {Przepraszam, ale muszê siê przygotowaæ do podró¿y.}
{225} {} {}
{226} {} {Tak, przywitaj siê. Wszystkiego najlepszego.}

{227} {} {Znowu? Hmm... twoje oczy s¹ zamglone. Jak tych szalonych kultystów ze wschodu. Czy ty przypadkiem nie czcisz starych rzeczy i oznak radioaktywnoœci? Jeœli tak, pamiêtaj, ¿e Stra¿nicy ich nie lubi¹.}
{228} {} {Dziêki za ostrze¿enie, ale nie jestem radioaktywnym wyznawc¹.}
{229} {} {Nie œmiej siê z prawdziwej wiary, bezwartoœciowy atomie! Inaczej ja bêdê siê œmiaæ z twojego grobu.}

#Zapytania
{230} {} {Opowiedz mi o sobie i swojej farmie.}
{231} {} {Co tu powiedzieæ? Uprawiamy roœliny tak daleko, jak to tylko mo¿liwe, a Stra¿nicy chroni¹ nas przed wrogami i pomagaj¹ nam, jak tylko mog¹.}
{232} {} {Jak d³ugo tu mieszkasz?}
{233} {} {Mieszkamy na tych ziemiach od kilkunastu zim. Gdyby nie Rangersi, nikt nie przetrwa³by tu tak d³ugo.}
{234} {} {Kto oprócz Ciebie mieszka w tej okolicy?}
{235} {} {Przy drodze Stra¿nicy za³o¿yli swoj¹ twierdze na starej tamie. Jest to najwiêksza osada rozproszona po pojedynczych rodzinach, farmach, posterunkach i sezonowych obozach myœliwych.}
{236} {} {Kto mieszka w chacie po drugiej stronie ulicy?}
{237} {} {Nikt tam nie mieszka od czasu, gdy poprzedni w³aœciciel zmar³ od trucizny radskorpiona.}
{238} {} {Dlaczego roœliny wysychaj¹?}
{239} {} {Poniewa¿ susza uniemo¿liwia sadzonkom wzrost. By³oby lepiej, gdybyœmy mieli dzia³aj¹cy system irygacyjny.}

{240} {} {Czy tutaj jest bezpiecznie?}
{241} {} {Obecnie nigdzie nie jest bezpiecznie. Ale w porównaniu z innymi miejscami, o których s³ysza³em, to jest chyba najbardziej spokojne. Bandytów prawie nie ma - odstraszaj¹ ich Stra¿nicy. Z mutantów tylko radskorpiony, ale s¹ z nimi problemy. Szczególnie w porze suchej, kiedy migruj¹ z po³udnia.}
{242} {} {Opowiedz mi o Radskorpionach.}
{243} {} {Ogromne stworzenia w nieprzeniknionych skorupach. Im dalej na po³udnie, w pustyniê, tym s¹ wiêksze i bardziej niebezpieczne. W szczególnie gor¹cych porach roku przenosz¹ siê tutaj, wtedy lepiej nie wychodziæ na ulicê. Zw³aszcza w nocy, gdy budzi siê ich instynkt ³owiecki.}
{244} {} {Czy znasz ich s³abe strony?}
{245} {} {Có¿, ich najbardziej czu³ym miejscem jest brzuch, ale dostanie siê tam jest bardzo trudne. Mo¿esz spróbowaæ z³amaæ im ³apy, a nastêpnie dobiæ stwora z daleka. Ale najbardziej niezawodnym lekarstwem na nie jest ogieñ. Podpal to stworzenie, a bêdzie siê paliæ jaœniej ni¿ s³oñcê.}
{246} {} {Wygl¹da na to, ¿e na drodze by³a masakra?}
{247} {} {Tak. Stra¿nicy tropili tego szpiega w ca³ej dolinie przez kilka dni. A by³ w szopie naprzeciwko nas. Czy mo¿esz to sobie wyobraziæ? Teraz wrogowie bêd¹ wiedzieæ, kto jest w³aœcicielem tych ziem!}

{250} {} {Opowiedz mi o tych Rangersach.}
{251} {} {Czy nie jesteœ jednym z nich? Wiêc nie powiem ci nic nowego. Zapytaj innych Stra¿ników w cytadeli.}
{252} {} {Mam do ciebie inne pytania.}
{253} {} {Doœæ tej bezsensownej rozmowy.}
{254} {} {Powiem ci coœ - oni s¹ obroñcami i stra¿nikami tych ziem. Jedynymi, którzy s¹ gotowi oddaæ ¿ycie za sprawiedliwoœæ i prawo w naszym trudnym œwiecie.}
{255} {} {Czy to Twoi patroni?}
{256} {} {Dok³adnie. P³acimy im podatek od naszych plonów, a oni chroni¹ nas przed bandytami i mutantami. Dzia³a to w bardzo prosty sposób.}
{257} {} {A co, jeœli nie chcesz dzieliæ siê z Rangersami?}
{258} {} {Pustkowia s¹ ogromne. Nie lubisz Stra¿ników - idŸ gdzie indziej. Ale powiem ci coœ - s¹ lepsi ni¿ ktokolwiek inny.}
{259} {} {Czujê, ¿e czegoœ mi nie mówisz. Jak naprawdê siê sprawy maj¹?}
{260} {} {Tak jak powiedzia³em. Stra¿nicy przynosz¹ sprawiedliwoœæ i prawo pustkowiom. I p³acimy za to podatek. To sprawiedliwe, prawda?}
{261} {} {Hmm...}
{262} {} {Chocia¿ Stra¿nicy nas chroni¹, sami potem pij¹ krew. Danie im czêœci zbiorów, które wyros³y przy takiej pracy, jest jak oddanie dziecka. Ale gdyby nie by³o Stra¿ników, byliby bandyci, którzy zabraliby wszystko. Musisz p³aciæ tak czy inaczej, nadal nie ma wyboru.}
{263} {} {A wiêc to tak...}
{264} {} {Muszê dostaæ siê do przywódcy Stra¿ników. Jak to zrobiæ?}
{265} {} {Có¿, tak po prostu nie wpuszcz¹ ciê do genera³a. Zwykle siedzi wewn¹trz tamy, a wejœcie do niej jest solidnie chronione. Jeœli chcesz wejœæ do œrodka, musisz znaleŸæ naprawdê dobry powód.}

{266} {} {Mieszkañcy Garage City pilnie potrzebuj¹ jedzenia.}
{267} {} {Wygl¹da na to, ¿e to ta osada zbieraczy, z któr¹ Rangersi mieli k³opoty. Nic dziwnego, ¿e doprowadzili siê do tego stanu.}
{268} {} {Móg³byœ wymieniæ z nimi swoje plony w zamian za maszyny i us³ugi naprawcze.}
{269} {} {Dobrze. Byæ mo¿e pozostali farmerzy równie¿ byliby zadowoleni z posiadania sprzêtu przydatnego w gospodarstwie. Myœlê, ¿e i Stra¿nicy bêd¹ mieli w³asny interes w tym biznesie. Zobaczmy co siê stanie.}
{270} {} {Ok, przeka¿ê zgodê mieszkañcom Garage City.}

# Podaj wodê
{288} {} {Wynoœ siê st¹d, uprzejmie proszê.}
{289} {} {Cokolwiek powiesz. Nie chcia³bym sprawiaæ k³opotów.}
{290} {} {Mo¿esz podzieliæ siê czyst¹ wod¹?}
{291} {} {Dlaczego mielibyœmy dzieliæ siê z tob¹ zapasami? A co jeœli jesteœ wrogiem Rangersów lub zbieg³ym bandyt¹? Poka¿ siê najpierw od dobrej strony, a zobaczymy.}
{292} {} {W porz¹dku. A czy przynajmniej mogê liczyæ na odpowiedzi na moje pytania?}
{293} {} {Bêdê pamietaæ, gdy tylko nadarzy siê okazja...}
{294} {} {Masz, pij tyle, ile chcesz. Nie œpiesz siê, zwiadowco, nie zabraknie ci wody.}
{295} {} {Dziêkujê...}
{296} {} {Nie jestem bandyt¹, wrêcz przeciwnie - to moja karawana zosta³a spl¹drowana.}
{297} {} {Trudno by³o przejœæ przez pustyniê? Wypij trochê. Ale wiêcej nie damy, zapytaj Stra¿ników.}
{298} {} {No, weŸ kilka ³yków dla dobrego goœcia.}
{1298} {} {No, weŸ kilka ³yków dla dobrego goœcia.}
{299} {} {Hmm, w porz¹dku, dziêkujê. Trzymaj siê.}

# Naprawa zbiornika
{300} {} {Czy Stra¿nicy nie mog¹ naprawiæ zbiornika na wodê?}
{301} {} {Wojownicy to twardzi faceci, ale technika nie jest ich mocn¹ stron¹. W ca³ej osadzie nie znajdziesz osoby, która pomog³aby naprawiæ zbiornik na wodê. Musimy wiêc pracowaæ rêkoma, co jest szczególnie trudne w naszym wieku.}
{302} {} {Mogê to naprawiæ.}
{303} {} {Naprawdê? By³oby wspaniale! Jeœli mo¿esz to zrobiæ, podzielimy siê jedzeniem i wod¹, nie mamy nic innego do zaoferowania.}
{304} {} {Pomyœlê o tym.}
{305} {} {Zbiornik na wodê ju¿ nie przecieka.}
{306} {} {Naprawdê... jesteœ prawdziwym mistrzem! Pos³uchaj, powinieneœ odwiedziæ Rangersów, potrzebuj¹ takich ludzi jak ty.}
{1306} {} {Naprawdê... jesteœ prawdziw¹ rzemieœlniczk¹! Pos³uchaj, powinnaœ odwiedziæ Rangersów, potrzebuj¹ takich ludzi jak ty.}
{307} {} {Um. W³aœciwie liczy³em na nagrodê.}
{1307} {} {Um. W³aœciwie liczy³am na nagrodê.}
{308} {} {Có¿, oto, co mogê ci za to daæ - czysta woda i kilka mutoowoców. Przepraszam za tak ma³o, ale z powodu suszy i przeciekaj¹cego zbiornika zbiory s¹ ledwo wystarczaj¹ce.}
{309} {} {Dziêki za to.}
{310} {} {Uwa¿aj na siebie.}
{311} {} {Do widzenia.}
{312} {} {Nie pracowa³em dla resztek. Daj mi resztê swoich zapasów albo zniszczê ten cholerny zbiornik.}
{1312} {} {Nie pracowa³am dla resztek. Oddaj resztê zapasów albo wysadzê ten cholerny zbiornik.}
{313} {} {Ok, nie ekscytuj siê, dostaniesz wiêcej jedzenia i wody. Ale to wszystko, co nam zosta³o. WeŸ to i odejdŸ w spokoju.}
{314} {} {Nawzajem starcze.}
{315} {} {Ok. I nie jest mi potrzebna ¿adna nagroda.}
{316} {} {Naprawdê nie weŸmiesz niczego w zamian? To dziwne, ale jestem ci bardzo wdziêczny. Dbaj o siebie.}
{317} {} {Do widzenia.}

# Znalezienie psa
{350} {} {Wygl¹da na to, ¿e sta³o siê coœ z³ego.}
{351} {} {Zgadza siê. Nasz pies znikn¹³ i coœ wyraŸnie zjada nasze plony. Myœlê, ¿e to radskorpiony. Jeœli zauwa¿ysz jakiegoœ psa, daj mi znaæ.}
{352} {} {Zdecydowanie.}
{353} {} {Znalaz³em szcz¹tki twojego psa. Zosta³ zabity.}
{1353} {} {Znalaz³am szcz¹tki twojego psa. Zosta³ zabity.}
{354} {} {O czym ty mówisz?! Kto móg³ to zrobiæ?!}
{355} {} {To by³ bandyta, który ucieka³ przed Stra¿nikami. Pies uniemo¿liwia³ mu kradzie¿ jedzenia z Twojego ogrodu.}
{356} {} {Jeszcze nie wiem. Mo¿e coœ siê wyjaœni póŸniej.}
{357} {} {Wiêc to on pustoszy³ nasz¹ farmê! Jeœli w pobli¿u zacz¹³ dzia³aæ bandyta, to Ÿle. Pos³uchaj, idŸ do Stra¿ników, opowiedz im o tym i poœpiesz siê!}
{358} {} {W³aœciwie to idê w innym kierunku. Bêdziesz musia³ sam to rozgryŸæ.}
{359} {} {Na pewno dam im znaæ, kiedy tam dotrê.}
{360} {} {Spokojnie - ten bandyta to ju¿ przesz³oœæ.}