{100} {} {Widzisz uciekiniera.}
{101} {} {Widzisz wyczerpanego m³odego cz³owieka w brudnej kurtce. Wygl¹da na to, ¿e Ÿle sobie radzi.}
{102} {} {Co... co mi dajesz...}
{103} {} {...O ty... cholera...}
{104} {} {Wygl¹da na to, ¿e Stra¿nicy w koñcu dopadli szpiega. Jego martwe cia³o na drodze bêdzie przestrog¹ dla reszty najemników.}
{105} {} {Zawdziêczam Ci ¿ycie, doktorze.}
{106} {} {Do zobaczenia w Swi¹tyni Ognia.}

# Pierwszy dialog
{200} {} {(w mroku ledwo mo¿na dostrzec jakiœ ruch; po chwili jednak dostrzegasz zmêczonego m³odego cz³owieka w brudnej kurtce, siedzi na starym materacu) Stój! Kim jesteœ? I czego tutaj szukasz?}
{201} {} {Podró¿ujê. Ten dom wydawa³ mi siê doskona³ym miejscem do spania.}
{202} {} {Jak widzisz, to miejsce jest ju¿ zajête.}
{203} {} {Prawdopodobnie nie powinno mnie tu byæ. Ok, pójdê sobie...}
{204} {} {Czekaj! Masz trochê wody? Pomocy, jestem kompletnie wyczerpany!}
{205} {} {Moje zapasy te¿ s¹ wyczerpane. Gdzie jest najbli¿sze Ÿród³o wody?}
{206} {} {Rolnicy po drugiej stronie ulicy maj¹ studnie. Ale te suki nie podziel¹ siê nawet kropl¹, dopóki nie oddasz im wszystkiego, co masz... S³uchaj, pomó¿ mi odzyskaæ si³y! Mam wiele kontaktów, pomogê Ci w przysz³oœci.}
{207} {} {Rozwi¹zujê w³asne problemy. Takie jest prawo Pustkowi.}
{208} {} {Poczekaj tutaj, wrócê wkrótce z czyst¹ wod¹...}
{209} {} {Oczywiœcie, proszê bardzo.}
{210} {} {(Trzês¹cymi siê rêkoma chwyta butelkê i ³apczywie wypija z niej wodê; kiedy jest pe³ny, zdejmuje kurtkê i przep³ukuje sczernia³¹ ranê wod¹, jêcz¹c jak pies z bólu.)}
{211} {} {Ju¿ lepiej?}
{212} {} {Ratujesz mnie... ale nie na d³ugo.}
{213} {} {Wygl¹da na to, ¿e nie poci¹gniesz d³ugo z tak¹ ran¹. Pójdê do Rangersów po pomoc...}
{214} {} {NIE! Te dranie mi nie pomog¹. To przez nich wpad³em w ten syf! Tak jak ty, w³aœnie podró¿owa³em w poszukiwaniu nowego miejsca do ¿ycia. Stra¿nicy wziêli mnie za bandytê i nie chc¹c tego wyjaœniæ, po prostu zaczêli do mnie strzelaæ. Mia³em szczêœcie, ¿e prze¿y³em i no¿em wyci¹gn¹³em kulê, ale ta rana mnie wykoñczy!}
{215} {} {Trudna sprawa...}
{216} {} {Zrób coœ! Umrê bez ciebie!}
{217} {} {Dobra, rozepnij marynarkê i przygotuj siê do badania. Zajmie siê teraz tob¹ prawdziwy lekarz.}
{218} {} {Ale ja nie jestem lekarzem.}
{219} {} {Wiêc idŸ do Stra¿ników i weŸ od nich lekarstwa. Umre bez tego!}
{220} {} {Wytrzymaj jeszcze trochê, poœpieszê siê.}
{221} {} {Sam rozwi¹zuj w³asne problemy.}
{222} {} {Uleczê twoje rany.}
{223} {} {Masz trochê wody?}
{1223} {} {Masz trochê wody?}
{224} {} {Masz, czysta woda.}
{225} {} {Jeszcze nie, b¹dŸ cierpliwy.}
{226} {} {Wiêc dlaczego, do diab³a, tu tkwisz? Ruszaj siê!}
{227} {} {Nie zamierzam dzieliæ siê z tob¹ swoimi zapasami. Przetrwaj najlepiej, jak potrafisz.}
{228} {} {Pieprzony kretoszczurze! Zabiorê wszystkie Twoje rzeczy!}
{229} {} {Whoa-whoa, zabierz to...}

{250} {} {Lubisz patrzeæ jak cierpiê?}
{251} {} {Pracujê nad Twoim problemem...}
{252} {} {Mo¿e tak. Pamiêtaj, od kogo zale¿y Twoje ¿ycie.}
{253} {} {Szczerze, nie spodziewa³em siê pomocy. To jest... bardzo szlachetne z twojej strony. Mo¿e muszê przemyœleæ coœ w moim stosunku do ludzi.}
{254} {} {Wygl¹da na to, ¿e potrzebujesz te¿ dobrego zastrzyku dialogu. Porozmawiamy?}
{255} {} {Myœlê, ¿e to koñczy moj¹ misjê. Z przyjemnoœci¹ zostanê.}
{256} {} {U¿yj umiejêtnoœci medycznych, leków lub narkotyków, aby uleczyæ nieznajomego.}

# Powtarzajacy siê dialog
{300} {} {Czeœæ.}
{301} {} {Wrócê wkrótce.}

{310} {} {Co tu jesz?}
{311} {} {Wszystko, co znajdê na pustyni - jaszczurki, owoce roœlinne, larwy. Wybór nie jest bogaty, ale nie jest mi obcy.}
{312} {} {A rolnicy mówi¹ ¿e ktoœ kradnie ich owoce z ogrodu.}
{313} {} {(pauza) Muszê prze¿yæ. Nie obchodzi mnie, co myœl¹ o tym inni.}
{314} {} {Hmm...}
{315} {} {Rozumiem.}
{316} {} {Wiêc co sprowadza ciê na ziemie Rangersów?}
{317} {} {Pog³oski o Stra¿nikach i ich sprawiedliwoœci. Plotki s¹ jednak fa³szywe i przesadzone. Jeœli chcesz uzyskaæ wsparcie tych wojowników - najpierw oddaj im wszystko, co masz. A potem MOZE ci pomog¹.}

{320} {} {Spotka³eœ mo¿e psa rolnika?}
{321} {} {Widzia³em jednego z nich, ale nie wiem, gdzie uciek³. Rolnicy powinni lepiej go karmiæ.}
{322} {} {Rozumiem.}
{323} {} {Czy zabi³eœ psa rolników?}
{324} {} {Czy to takie oczywiste? W takim razie nie ma sensu temu zaprzeczaæ. Potrzebowa³em jedzenia, a ta cholera trzyma³a mnie z dala od plantacji. Poza tym prawie zdradzi³a rolnikom moj¹ obecnoœæ! Coœ trzeba by³o zdecydowaæ.}
{325} {} {Doœæ ryzykowna decyzja...}
{326} {} {Hej! Rozumiesz, ¿e rozmowa o tym nie le¿y w twoim interesie? Rozumiesz?}
{327} {} {Uch, oczywiœcie nie ma problemu.}

{330} {} {A teraz, czy mo¿esz mi powiedziea, co siê naprawdê wydarzy³o?}
{331} {} {Znam kilku ludzi z Phoenix, którzy potrzebuj¹ szyfru z radia Stra¿ników. Obiecali dobrze zap³aciæ.}
{332} {} {Czyli odnios³eœ obra¿enia podczas szukania informacji?}
{333} {} {Czasami musisz zaryzykowaæ, by zdobyæ kapsle. Próbowa³em w³amaæ siê do radiostacji w nocy, ale ktoœ zacz¹³ do mnie strzelaæ. Od tego czasu chowam siê w tej piwnicy i nic nie mogê zrobiæ... Hej, chcesz ze mn¹ zarobiæ?}
{334} {} {Kim s¹ ludzie, którzy potrzebuj¹ szyfru?}
{335} {} {Powiedzia³bym, ale wtedy móg³bym straciæ szansê na zarobek. Rozumiesz?}
{336} {} {Masz pomys³, jak znaleŸæ ten kod?}
{337} {} {Stacja radiowa Stra¿ników ma wszystkie informacje. I prawie niemo¿liwe jest przekonanie kogoœ do udostêpnienia go.}
{338} {} {Musz¹ byæ inni najemnicy.}
{339} {} {Mo¿e. Ale ja o tym nic nie wiem.}
{340} {} {Przemyœlê twoj¹ propozycjê.}
{341} {} {Niech zgadnê - pracujesz dla czcicieli ognia, prawda? W takim razie mam z³¹ wiadomoœæ - Swi¹tynia Ognia zosta³a zniszczona.}
{342} {} {To niemo¿liwe! Czy masz pojêcie, co to oznacza?! Nie tylko straci³em kapsle, ale ca³e pustkowiê upadnie! Teraz zdecydowanie nie powinienem wracaæ do Phoenix... Powinienem iœæ w góry i karmiæ siê padlin¹, a¿ opadnie kurz... Zapomnij o kodzie, ju¿ go nie potrzebujê.}
{343} {} {Dok³adnie, nie masz tu nic innego do roboty.}
{344} {} {Dlaczego nie odchodzisz? Stra¿nicy prawdopodobnie ciê szukaj¹.}
{345} {} {Nie mam wyboru. Jeœli nie dostanê szyfru, to klienci mnie zabij¹... a jeœli nie oni, to lichwiarze, którym jestem winien kapsle.}
{346} {} {Kolejne pytanie na ten sam temat.}
{347} {} {Czego chcesz?}
{348} {} {Porozmawiajmy o szyfrze.}
{349} {} {Opowiedz mi wieej o tej sytuacji.}
{350} {} {Znam szyfr.}
{351} {} {Tak? Co to za szyfr?}
{352} {} {Nie tak szybko. Co za to dostanê?}
{353} {} {Górê kapsli. Schowa³em je w bezpiecznym miejscu. Ale najpierw muszê siê dowiedzieæ, czy mówisz prawdê.}
{354} {} {Oto kod.}
{355} {} {Nic ci nie powiem!}
{356} {} {To by³o sprytne posuniêcie, prawda? Teraz czciciele ognia dadz¹ mi sporo kapsli. Bed¹ * zmuszeni * przyj¹æ mnie w swoje szeregi! Do³¹czê do elity Phoenix, rozumiesz?!}
{357} {} {Brzmi œwietnie. Jeœli znajdê siê w Phoenix, czy pomo¿esz mi te¿ wejœæ do tej elity?}
{358} {} {Nie potrzebujesz ¿adnych kapsli, prawda? Potrzebujemy ludzi z pomys³em. Tak czy inaczej, do zobaczenia. Muszê iœæ.}
{359} {} {Do zobaczenia!}
{360} {} {Interesuj¹ mnie tylko moje kapsle.}
{361} {} {Tak... Dostaniesz je teraz! (przygotowuje siê do ataku)}
{362} {} {Hej, nie tak siê umawialiœmy!}
{363} {} {Ty sukinsynu!}
{364} {} {Mam lepszy pomys³. Po prostu siê zamknij... na zawsze!}
{365} {} {Hej, a co z moimi kapslami?!}
{366} {} {Swi¹tynia Ognia potrzebuje nowej krwi. Ale ty, ¿a³osny atomie, nie jesteœ godzien inicjacji!}
{367} {} {Nie bêdê tolerowaæ ekspansji tej religii. Giñ!}
{368} {} {Wiêc ty i ja staniemy siê braæmi w wierze?}
{1368} {} {Wiêc ty i ja zostaniemy krewnymi w wierze?}
{369} {} {Nie wierzê, ¿e naprawdê jesteœ ze œwi¹tyni. Jednak... twoja wiedza medyczna... Có¿, do zobaczenia. Muszê iœæ.}
{370} {} {Do zobaczenia... obcy.}