{100} {} {Widzisz Williama Garth.}
{101} {} {Widzisz Rangersa Weterana.}
{102} {} {Nie zapomnij, kto tu jest prawdziw¹ w³adz¹.}
{103} {} {A czyje zw³oki tu le¿¹, co œwiniaku?}
{104} {} {Jeœli to jakiœ podstêp, s³ono za to zap³acisz.}

{200} {} {M? Nie pamiêtam, ¿ebyœmy siê kiedykolwiek spotkali. Witamy w akwedukcie. Co Ciê do nas sprowadza?}
{201} {} {Mam tu interesy.}
{202} {} {Cokolwiek powiesz. Ale upewnij siê, ¿e twoje „interesy” nie stan¹ siê moimi. Nie podoba mi siê, gdy nowicjusze próbuj¹ narzuciæ nowe zasady.}
{203} {} {Kim w³aœciwie jesteœ?}
{204} {} {Rozpoznajesz gwiazdê Rangersa? Niedawno otrzyma³em ten tytu³.}
{1204} {} {Rozpoznajesz gwiazdê Rangersa? Niedawno otrzyma³am ten tytu³.}
{205} {} {Gratulujemy awansu. Czuj siê jak w domu, wszyscy tu s¹ rodzin¹.}
{206} {} {A ty...}
{207} {} {Moja wioska potrzebowa³a pomocy Stra¿ników.}
{208} {} {Wiêc skontaktuj siê z osob¹ dy¿urn¹ w Centrum Informacji. Tutaj nikt nie mo¿e Ci pomóc w tej sprawie.}
{209} {} {Co tutaj robisz?}
{210} {} {William Garth, by³y dowódca polowy, a obecnie emerytowany Ranger. Po d³ugiej s³u¿bie przeszed³em na emeryturê - lata zbieraj¹ swoje ¿niwo. Czasami myle siê z miejscowym szeryfem, ale nie jest to do koñca nieprawda. W centrali p³ac¹ mi „emeryturê” za utrzymanie porz¹dku w akwedukcie.}
{211} {} {Poniewa¿ masz du¿o wolnego czasu, czy mo¿esz odpowiedzieæ na kilka pytañ?}
{212} {} {Mi³o ciê poznaæ, ale muszê ju¿ iœæ.}

{220} {} {Co myœlisz?}
{221} {} {Mów, nie wstydŸ siê.}
{222} {} {Mów.}
{223} {} {S³ucham.}
{224} {} {Co chcesz wiedzieæ?}
{229} {} {Do zobaczenia, Stra¿niku.}

{230} {} {Mówi¹, ¿e masz tu epidemiê.}
{231} {} {Kilka osób zachorowa³o na gor¹czkê. S¹ w trakcie leczenia, ale nie mogliœmy ustaliæ przyczyny choroby.}
{232} {} {Jakie s¹ objawy?}
{233} {} {Porozmawiaj z chorymi, œpi¹ w swoich chatach.}
{234} {} {Ok, zrobiê to.}

{250} {} {Opowiedz mi o tym miejscu.}
{251} {} {Mieszka tu kilka spokojnych rodzin. Rzeka dostarcza nam po¿ywienia i wody, a baza Stra¿ników zapewnia ochronê przed ró¿nymi zagro¿eniami.}
{252} {} {Dziêkujê za odpowiedŸ.}
{253} {} {Czy mogê tu zostaæ na noc?}
{254} {} {Nie mam nic przeciwko, jeœli prosisz o pozwolenie. Ale wiedz, ¿e miejscowi nie ufaj¹ nowym.}
{255} {} {Czy jest tu dla mnie praca?}
{256} {} {Nie s¹dzê. Porozmawiaj z mieszkañcami.}
{257} {} {Zastanawiam siê, co to za wielka zrujnowana budowla po drugiej stronie ulicy?}
{258} {} {To jest akwedukt. Sztuczna rzeka zbudowana przez mieszkañców Starego Swiata. Rozci¹ga siê na setki mil w ca³ej Arizonie. Imponuj¹ce, prawda? Ale nie powinieneœ tam iœæ - to niebezpieczne.}
{259} {} {Czy Stra¿nicy nie s¹ przeciwni cywilom w pobli¿u ich bazy?}
{260} {} {Oczywiœcie, bycie tak blisko wioski jest trochê niewygodne. Ale z drugiej strony Stra¿nicy mog¹ natychmiast zareagowaæ w razie potrzeby.}

#quest - brakujacy mieszkañcy
{300} {} {Mówi¹, ¿e znikaj¹ tu ludzie, to prawda?}
{301} {} {Kto tak mówi?}
{302} {} {Ten uchodŸca przy ognisku.}
{303} {} {Po prostu odpowiedz na pytanie.}
{304} {} {Czasami pojawiaj¹ siê tu nowicjusze, tacy jak ty, ale siê nie dogaduj¹ z miejsowymi. To normalne. Potem id¹, gdziekolwiek ich nogi ponios¹. Czasami Stra¿nicy znajduj¹ ich szcz¹tki w lesie, gdzie jest wiele wilków.}
{305} {} {Wygl¹dasz na szeryfa. Mo¿esz poszukaæ tych zaginionych?}
{306} {} {Moim zadaniem jest utrzymanie porz¹dku w akwedukcie, a nie poza nim. Ponadto zagineli przybysze. To znaczy nielokalni. Jeœli chcesz ich znaleŸæ, poszukaj ich samodzielnie.}
{307} {} {Rozumiem. Nie ma problemu. Do widzenia, Stra¿niku.}
{308} {} {Jesteœ okropnym szeryfem. Rozwi¹¿ê to bez ciebie.}

{310} {} {W akwedukcie s¹ zw³oki. Jesteœ w to wyraŸnie zaanga¿owany.}
{311} {} {Cholera, powiedzia³em Keelowi, ¿eby ciê powstrzyma³. Gdzie jest ten idiota?}
{312} {} {Jakby to uj¹æ, wygl¹da na to, ¿e nie jest w stanie teraz wykonywaæ twoich rozkazów.}
{313} {} {Coœ siê nie uda³o. I nie bêdziesz w stanie mnie ju¿ uciszyæ.}
{314} {} {Kim ty do diab³a jesteœ, ¿eby tu sobie wpadaæ i rujnowaæ nam ¿ycie? Czy wys³ali ciê ci kultyœci? A mo¿e szukasz miejsca na napad bandytów? A mo¿e jesteœ po prostu kolejnym z³odziejem szukaj¹cym ryb. Wy, ludzie z zewn¹trz, przysparzacie samych k³opotów tej pokojowej spo³ecznoœci. Ja po prostu wype³niam swój obowi¹zek, aby chroniæ akwedukt przed problemami.}
{315} {} {Nie. Jesteœ po prostu paranoikiem. I musisz zostaæ powstrzymany.}
{316} {} {Wiêc to wszystko. Wychodzê z tego pokoju, a ty mnie NIE dotykasz. I twoje szczêœcie, jeœli nie zdecydujê siê opowiedzieæ o tym, co siê sta³o.}
{317} {} {Zaufaj mi, jestem po twojej stronie. A jeœli Twój asystent zawiedzie, mogê pomóc.}
{318} {} {Wiêc udowodnij swoje oddanie sprawie Stra¿ników - wyeliminuj ostatniego uchodŸcê. Nie obchodzi mnie, jak to zrobisz - kul¹ czy przebieg³oœci¹. Teraz jest zagro¿eniem dla mnie i innych mieszkañców.}
{319} {} {Ok, zrobiê to.}
{320} {} {Nie, to za du¿o. Zabijê ciê.}
{321} {} {Dlaczego? Czy ju¿ nie ma zbyt wielu zgonów?}
{322} {} {Czy wiesz coœ o tych ludziach? Oczywiœcie, ¿e nie. Przybyli z daleka. Jeden z nich mia³ znak autostrady - gangu z g³ównej drogi. Byæ mo¿e to tylko moje spekulacje, nie wystarcz¹ do uczciwego procesu. Ale mi to wystarczy, ¿ebym zacz¹³ dzia³aæ.}
{323} {} {Zobaczmy, kim jesteœ.}
{324} {} {Do widzenia.}
{325} {} {Jako Stra¿nik musisz mnie zrozumieæ. Akwedukt to ma³a, spokojna spo³ecznoœæ rybaków i zbieraczy. Niezweryfikowani osadnicy mog¹ zniszczyæ kruch¹ równowagê tej osady. Sekciarze, bandyci, z³odzieje - kogokolwiek nie przyniesie nam pustkowiê. Po prostu wype³niam swój obowi¹zek, aby chroniæ akwedukt przed problemami.}
{1325} {} {Jako Stra¿nik musisz mnie zrozumieæ. Akwedukt to ma³a, spokojna spo³ecznoœæ rybaków i zbieraczy. Niezweryfikowani osadnicy mog¹ zniszczyæ kruch¹ równowagê tej osady. Sekciarze, bandyci, z³odzieje - kogokolwiek nie przyniesie nam pustkowiê. Po prostu wype³niam swój obowi¹zek, aby chroniæ akwedukt przed problemami.}

{330} {} {Pozby³em siê uchodŸcy.}
{1330} {} {Pozby³am siê uchodŸcy.}
{331} {} {Dobra robota. Robisz to lepiej ni¿ ten miêkki Keel. Myœlê, ¿e ty i ja bêdziemy od teraz pracowaæ razem. WeŸ kilka kul na przysz³oœæ. Mam nadziejê, ¿e nie ma potrzeby, aby rozwodziæ siê nad tajemnic¹ milczenia?}
{332} {} {Nie ma problemu, Williamie. Nikt nic nie widzia³.}
{333} {} {To... s¹ zw³oki przy akwedukcie. Ech, powinieneœ rzuciæ okiem.}
{334} {} {Cholera, w ogóle tego nie potrzebujê. Poka¿ to miejsce.}
{335} {} {Jest tam...}