{100} {} {Widzisz starego cz³owieka.}
{101} {} {Widzisz wychudzonego mê¿czyznê. Jego skóra jest poczernia³a od ci¹g³ej pracy na s³oñcu.}

# Odpowiedzi po dialogu
{110} {} {Myœlê, ¿e to wystarczy zapomnienia.}
{111} {} {Muszê wracaæ na farmê.}
{112} {} {Dziêki za mo¿liwoœæ zabrania g³osu.}
{113} {} {Umar³y poczeka, ale ¿niwa uschn¹.}
{114} {} {Mam nadziejê, ¿e wybaczysz mi ten sentymentalizm.}

#Dialog
{200} {} {(Widzisz starego zamyœlonego mê¿czyznê stoj¹cego przed grobem)}
{201} {} {[Dalej.]}

{210} {} {Czego ode mnie chcesz?}
{211} {} {Niewa¿ne.}
{212} {} {Rozumiem.}
{213} {} {.}

{220} {} {Kim jesteœ, staruszku?}
{221} {} {Staruszku? Heh, mam ledwie czterdzieœci lat, a ju¿ wygl¹dam jak skamienia³a staro¿ytnoœæ, prawda? Jestem rolnikiem. Uprawiam plony w odleg³oœci dwóch mil.}
{222} {} {Wiêc nie jesteœ Stra¿nikiem?}
{223} {} {Nie gadaj bzdur. Jakim mogê byæ Stra¿nikiem w moim wieku z tymi brudnymi rêkoma? Moim zadaniem jest pilnowanie farmy, a nie œciganie bandytów.}
{224} {} {Po drodze natkn¹³em siê na jedn¹ farmê.}
{225} {} {W okolicy jest kilka farm i rancza. Stra¿nicy os³aniaj¹ naszych braci, ale bior¹ za to swój procent zbiorów... Czasami zostawiaj¹ nam ¿a³osne okruchy, którymi mo¿emy ¿yæ... Ale z biegiem czasu sytuacja siê poprawia. Ziemia odbudowuje siê z roku na rok po Wielkim Zanieczyszczeniu.}
{226} {} {Zanieczyszczeniu?}
{227} {} {Genera³ rozmawia³ kiedyœ przy fili¿ance zio³owej herbaty. Kiedy sto lat temu spad³y bomby atomowe, ziemie te by³y pokryte chmurami radioaktywnego popio³u. Chmury nadci¹ga³y z zachodu, wschodu i po³udnia, w zale¿noœci od tego, gdzie wia³ wiatr. W tamtych latach wszêdzie by³o Ÿle. Mówi¹, ¿e ziemia by³a ja³owa od pokoleñ. Tylko kaktusy zdo³a³y utrzymaæ swój cykl ¿ycia dziêki g³êbokim korzeniom. Dopiero teraz ziemia zaczê³a siê regenerowaæ.}

{230} {} {Co tutaj robisz?}
{231} {} {Co mo¿e robiæ smutny staruszek na cmentarzu? Oczywiœcie wspominam sobie dawne czasy. Oto grób mojego syna. Napis na krzy¿u jest prawie zamazany, ale wci¹¿ mam wystarczaj¹co du¿o powodów, by nie zapomnieæ jego imienia i lokalizacji grobu.}
{232} {} {Powiedz mi, jak umar³?}
{233} {} {M³odzi ludzie s¹ niecierpliwi. Praca na plantacji jest dla nich zbyt wyczerpuj¹ca. Ale ziemia daje swoje owoce tylko tym, którzy przez wiele lat gorliwie pracowali. Tak samo jest z moim Jakubem. Poszed³ do Rangersów, ¿eby nie bawiæ siê w ziemi. Pierwsza potyczka z najeŸdŸcami podczas patrolu zabra³a jego ¿ycie.}
{234} {} {Teraz nienawidzisz Rangersów?}
{235} {} {Odpêdzam takie myœli. Rangersi maj¹ szczytny cel - porz¹dek na pustkowiach. Tak, czasem ktoœ umiera. Nie mo¿esz zadowoliæ wszystkich. Jeœli pomo¿esz jednemu, skrzywdzisz drugiego. To jest prawdziwe oblicze sprawiedliwoœci.}

{240} {} {Czyje to groby?}
{241} {} {Stra¿nicy grzebi¹ tu swoich braci zgodnie ze star¹ tradycj¹ - grzebi¹ ich w ziemi. W grobie umieszcza siê nabój, zwykle kaliber rewolwerowy. Jeœli nie ma takiego, ka¿dy inny siê nada. A jeœli i tego nie ma, wk³ada siê tylko ³uskê lub kulê. Chc¹ przez to powiedzieæ, ¿e nawet po œmierci nikt nie zapomina o tych którzy s³u¿yli przed nimi.}