{100} {} {Widzisz Henrego.}
{101} {} {Widzisz kwatermistrza Rangersów.}
{102} {} {Uch, co jest? Zatrzymaæ siê! Bo strzelê!}

# Pierwszy dialog
{200} {} {Cholera, nie wiem, gdzie do diab³a jest... Och, myœla³em, ¿e to znowu inspektor.}
{201} {} {Nie, zdecydowanie nie jestem inspektorem.}
{202} {} {Nastêpnym razem mogê siê obraziæ.}
{203} {} {Hmm, nowa twarz. Co za niespodzianka. Nazywam siê Henry i jestem handlarzem i kwatermistrzem w tej bazie. Mamy tutaj trudn¹ rutynê. Jeœli chcesz siê ustatkowaæ, musisz jej przestrzegaæ.}
{204} {} {Nie lubiê, gdy ktoœ mi rozkazuje.}
{205} {} {Zaden problem.}

{206} {} {Zaczekaj chwilê, mamy gor¹c¹ dyskusjê na temat najnowszych wiadomoœci. Jakiœ drañ kopie groby Rangersów na cmentarzu. Nie wiesz nic o tym?}
{207} {} {Ja? Ech, nie, proszê pana.}
{208} {} {Przepraszam. Wojownicy postanowili zrzuciæ siê na karabin temu, kto znajdzie i zastrzeli³ sukinsyna. Miej to na uwadze.}
{209} {} {Uch, oczywiœcie proszê pana.}

# Powtarzajacy siê dialog
{210} {} {Wiêc czego chcesz?}
{211} {} {Na razie nic.}
{212} {} {Doœæ, porozmawiajmy o czymœ bardziej u¿ytecznym.}
{213} {} {Wci¹¿ ciekawi mnie twoja historia.}

{220} {} {Opowiedz mi o sobie.}
{221} {} {Czy naprawdê Ciê to interesuje?}
{222} {} {Co tu robisz?}
{223} {} {Jestem handlarzem i kwatermistrzem w tej bazie.}
{224} {} {Czy handlujesz z osobami z zewn¹trz?}
{225} {} {Dowództwo nie lubi swobodnego handlu z samotnymi podró¿nikami. Posiadamy niezawodne karawany. Jednak z powodu ca³ego tego ba³aganu w San Brahmin handel zacz¹³ podupadaæ.}
{226} {} {Opowiedz mi o zamieszaniu w handlu.}
{227} {} {San Brahmin to miasto na wschodzie. Prowadzimy handel wyrobami skórzanymi i miêsem z lokalnymi pasterzami. Chronimy równie¿ ich szlaki handlowe i pastwiska. Ale w mieœcie dosz³o do konfliktu. Nie wiadomo, jak to siê skoñczy.}
{228} {} {Mam du¿¹ sieæ sprzeda¿y. Nie powinieneœ rezygnowaæ z tak dochodowego partnera.}
{229} {} {Ok, zobaczmy, co siê stanie.}
{230} {} {Dziêki.}
{231} {} {W¹tpiê, ¿eby twój biznes przyniós³ korzyœci Rangersom.}
{232} {} {Jak sobie ¿yczysz...}
{233} {} {}
{234} {} {Sk¹d jesteœ?}
{235} {} {Moja rodzina czêsto zmienia³a miejsce zamieszkania, wiêc najdok³adniejsza odpowiedŸ na twoje pytanie brzmi: pochodzê z zachodu.}
{236} {} {Opowiedz mi o tych ziemiach.}
{237} {} {Po³udniowa Kalifornia? Czyste piek³o w porównaniu z tym regionem. Miasta le¿¹ w gruzach, ziemia jest ja³owa, a wœród ludnoœci kwitnie kanibalizm. Ale ma te¿ znacznie wiêksz¹ populacjê ni¿ Arizona.}
{238} {} {Jak zosta³eœ Stra¿nikiem?}
{239} {} {Samo pustkowiê sprawi³o, ¿e poczu³em siê nim, kiedy zosta³em oddzielony od mojej rodziny podczas podró¿y. Prze¿y³em tylko dziêki Rangersom, którzy akurat byli w pobli¿u. Od tego czasu pracujê na siebie. Ale moje umiejêtnoœci wystarczy³y tylko na to stanowisko.}

#Lesniczy
{250} {} {Myœlê, ¿e powinieneœ mnie zarejestrowaæ w swoim rejestrze. Jestem nowicjuszem.}
{251} {} {S³ysza³em ju¿ o twoim przyjêciu, Stra¿niku. Masz godn¹ pozazdroszczenia sprawê. Wielu od lat trenuje, aby zdobyæ ten tytu³, a Tobie uda³o siê go zdobyæ w tak krótkim czasie.}
{252} {} {[Dalej.]}
{253} {} {Ok, jeœli czegoœ potrzebujesz, powiedz, nie wstydŸ siê. Dam ci ³ó¿ko, ale uwa¿aj na swój sprzêt. Oto twoja skórzana zbroja i butelka podró¿na. Teraz - któr¹ broñ wolisz?}
{254} {} {[Karabin myœliwski z amunicj¹]}
{255} {} {[Pistolet sygna³owy z amunicj¹]}
{256} {} {[No¿e do rzucania, 5 sztuk]}
{257} {} {Odbierz to i podpisz tu. Pamiêtaj, ¿e wszystko to jest w jednym egzemplarzu.}
{258} {} {Dziêki, zajmê siê tym sprzêtem.}
{259} {} {Wiem to bez ciebie, m¹dralo. Wrócê tu wkrótce.}

{270} {} {Wiesz, ¿e Rufus wys³a³ mnie tu po nagrodê?}
{271} {} {Tak, wiem. Oto lista, po prostu coœ wybierz.}
{272} {} {Innym razem.}
{273} {} {Stymulanty (3 szt.)}
{274} {} {Naboje kalibru 0,44 (35 szt.)}
{275} {} {Naboje karabinowe (20 szt.)}
{276} {} {Skórzana zbroja.}
{277} {} {}
{278} {} {Proszê bardzo.}
{279} {} {Dziêki.}

{280} {} {Idê do Puerto na zwiad.}
{281} {} {W takim razie powodzenia. Stra¿nicy na linii frontu s¹ ostatnio niespokojni. Nowy wróg okaza³ siê trudnym orzechem do zgryzienia.}
{282} {} {Zgadza siê.}
{283} {} {Prowadzimy propagandê w osadach, a nawet p³acimy dodatkowo za ka¿dego zabitego ¿o³nierza wroga. Musisz to tylko udowodniæ.}
{284} {} {Jak to udowodniæ?}
{285} {} {To ³atwe. Ka¿dy ma nieœmiertelnik z osobistym numerem i nazwiskiem. Przynieœ taki medalik, a otrzymasz kapsle. Zwykle nie mamy do czynienia z kapslami, ale inaczej trudno by³oby zainteresowaæ zwyk³ych mieszkañców pustkowia.}
{286} {} {Zapamiêtam to. Bywaj.}
{287} {} {Mam nieœmertelnik Bractwa Stali.}
{288} {} {Im wiêcej najeŸdŸców upadnie, tym swobodniejsze bêdzie powietrze w Arizonie. Twoja nagroda to 10 kapsli za ka¿dy jeden.}
{289} {} {Lepsze to ni¿ nic. Oto dowód.}
{290} {} {Zadne kapsle nie s¹ mi potrzebne. Zachowaj je dla kogoœ innego.}
{291} {} {Ka¿dy taki nieœmiertelnik wzmacnia ducha walki szeregowych i pilnuj¹cych Stra¿ników. Dziêkujê Ci. Powodzenia na pustkowiu.}
{292} {} {Do zobaczenia ponownie.}
{293} {} {Czekaj, to nie wszystko.}

# Zagubione zadanie
{300} {} {O pracy. Brakuje Ci czegoœ?}
{301} {} {Tak... Faktura mówi, ¿e powinienem mieæ tu pistolet Colt 6520 i pude³ko nabojów. Ale tak nie jest.}
{302} {} {Ok, nie bêdê przeszkadzaæ w twoich poszukiwaniach.}
{303} {} {B³¹d we wpisach?}
{304} {} {W¹tpiê, bym wpisa³ pistolet, którego tu nie mia³em. Nie chcê nawet myœleæ, ¿e ktoœ z moich ludzi móg³by dopuœciæ siê kradzie¿y. Ale to jedyne wyjaœnienie.}
{305} {} {Mogê go poszukaæ. Kto by³ ostatni¹ osob¹, która u¿y³a tego pistoletu?}
{306} {} {Ta broñ musia³a gdzieœ spaœæ. Szukaj dalej.}
{307} {} {Tak, musisz mieæ tu zamkniête kieszenie. Mo¿e powinienem jeszcze raz sprawdziæ swoje rzeczy.}
{308} {} {Kapitan Agatha przydzieli³a swojej grupie ten pistolet do szkolenia ogólnego. Ale potem wróci³ ca³y i zdrowy. Jeœli, oczywiœcie, wierzyæ zapisom.}
{309} {} {Wygl¹da na to, ¿e warto porozmawiaæ z ni¹ i jej kadetami. Czeœæ.}
{310} {} {Oczywiœcie porozmawiam z nimi. Ale pamiêtaj, ¿e ty te¿ jesteœ podejrzany.}
{311} {} {Pamiêtasz, jak rozmawialiœmy o zagubionej broni?}
{312} {} {Co wiesz?}
{313} {} {Nic. Brak potencjalnych podejrzach. Absolutnie nic.}
{314} {} {Przypomnij mi, czego dok³adnie brakuje w magazynie?}
{315} {} {Pistolet Colt 6520 z pe³n¹ amunicj¹. Ta sztuka by³a u¿ywana g³ównie do celów szkoleniowych.}
{316} {} {Dziêki, poszukam dalej.}
{317} {} {Powiedz mi jeszcze raz, kto ostatni wzi¹³ broñ?}
{318} {} {Kadeci kapitan Agathy. U¿ywali go do treningu, a nastêpnie zwrócili ca³y i zdrowy.}

{320} {} {Oto brakujacy pistolet. Zosta³ skradziony przez kadetów Agathy, chcieli poæwiczyæ strzelanie.}
{321} {} {Och, nareszcie. Gdzie by³?}
{322} {} {Zosta³ zabrany przez kadetów Agathy, chcieli poæwiczyæ strzelanie.}
{323} {} {Cholerne szczury... Nie ujdzie im to na sucho. Zas³ugujesz na kilka kul, które by³y przeznaczone dla tych kadetów. Dziêki za pomoc.}
{324} {} {Cieszê siê, ¿e mog³em pomóc.}
{1324} {} {Mi³o móc Ci pomóc.}
{325} {} {To nie by³o tego warte.}
{326} {} {Zosta³ na strzelnicy. Wygl¹da na to, ¿e coœ pomiesza³eœ w swoich rzeczach.}
{327} {} {Cholera. Teraz muszê zg³osiæ siê do dowódcy. Ale dziêki za pomoc. Powiem innym, mam nadziejê, ¿e pomo¿e ci to zdobyæ trochê szacunku w bazie.}

#Relikt
{350} {} {Mam tu coœ interesuj¹cego. Spójrz na tê odznakê.}
{351} {} {To zdecydowanie nie jest nasza dzisiejsza odznaka. Hmm... Ale wygl¹da na to, ¿e jest autentyczna! To bardzo rzadkie znalezisko.}
{352} {} {Wygl¹da na to, ¿e spowa¿nia³eœ. Czy to coœ wa¿nego?}
{353} {} {Te insygnia przypominaj¹ nam o naszych korzeniach i dowodz¹, ¿e jesteœmy Stra¿nikami lokalnych tradycji. Oczywiœcie, ¿e jest to coœ wa¿nego.}
{354} {} {Chcesz to odkupiæ?}
{355} {} {Oczywiœcie. Takie rzeczy podnosz¹ morale Stra¿ników. Dam ci pude³ko naboi za t¹ odznakê.}
{356} {} {Ta odznaka za pude³ko nabojów karabinowych.}
{357} {} {Daj mi odznakê. Oto naboje.}
{358} {} {To by³o tego warte.}
{359} {} {Myœlê, ¿e wezmê naboje do rewolweru.}
{360} {} {Daj mi odznakê. Oto pude³ko nabojów kalibru rewolweru.}
{361} {} {Ta wymiana mi odpowiada.}
{362} {} {Potrzebujê ma³ego kalibru jak 0,22 do æwiczeñ.}
{363} {} {Mam du¿o tego do wydania. Oto pude³ko.}
{364} {} {Dobra oferta.}
{365} {} {Potrzebujê amunicji do flar.}
{366} {} {No, odznaka, mam ca³e pude³ko tych nabojów, ale nie s¹ one zbyt przydatne.}
{367} {} {Niez³a umowa.}
{368} {} {WeŸ to za darmo. I tak tego nie potrzebujê.}
{369} {} {Tak po prostu mi to oddajesz? Dziêkujê Ci. Nie zapomnê ci tego.}
{370} {} {WeŸ to, nie musisz dziêkowaæ.}
{371} {} {A mo¿e dasz mi poæwiczyæ na strzelnicy? Bardzo chcê poæwiczyæ z broni¹ paln¹.}
{372} {} {Jasna sprawa. Mam tu amunicjê i broñ specjalnie do takich celów. Powodzenia na strzelnicy.}
{373} {} {Dziêki...}
{374} {} {Kwatermistrz obni¿y³ koszt swoich towarów o 10%.}