{100} {} {Widzisz bandytê.}
{101} {} {Widzisz osobê, która wcale nie wygl¹da na Stra¿nika.}
{102} {} {Wynoœ siê, zanim ciê zastrzelê.}

# Pierwszy dialog
{200} {} {Stop. Jesteœ w krainie Stra¿ników i nie podobasz mi siê, co tu robisz?}
{201} {} {O czym ty mówisz? Ta ziemia jest niczyja. Tylko bandyci bior¹ to co wspólne dla siebie.}
{202} {} {Ciekawy punkt widzenia. I ca³kowicie bez znaczenia. Ale zada³em pytanie - CO tutaj robisz?}
{203} {} {Mogê ciê szukaæ. Podobno okradasz podró¿ników w przebraniu Stra¿nika.}
{204} {} {Jestem Stra¿nikiem, oto moja odznaka. I nikogo nie okradam. Zdarza siê, ¿e biore coœ jako zap³atê za przekroczenie granicy. To moja praca. Nawiasem mówi¹c, ty te¿ musisz zap³aciæ.}
{205} {} {Czy to twoje terytorium? K³amiesz. Udowodnij to.}
{206} {} {Jesteœ zwyk³ym bandyt¹.}

{210} {} {Przegrza³ ci siê mózg na tej pustyni? Nie mo¿esz niczego ¿¹daæ. Daj wszystko, co masz i mo¿esz iœæ dalej.}
{211} {} {Ok, oddam wszystko, tylko mnie nie bij.}
{212} {} {A teraz wynoœ siê, ¿ebym ciê tu wiêcej nie widzia³.}
{213} {} {Cokolwiek powiesz...}
{214} {} {Hej, oddaj mi moje rzeczy! Natychmiast.}
{215} {} {Nic ci nie dam.}
{216} {} {W takim razie... Ch³opaki, wiecie, co robiæ...}
{217} {} {Wszyscy staæ!}
{218} {} {Ok, oddam wszystko. Proszê, weŸ to...}
{219} {} {Te rzeczy s¹ strasznie radioaktywne. Chcesz siê o tym przekonaæ na swoim zdrowiu?}
{220} {} {Nie oszukasz mnie tak ³atwo. Ostatnie ostrze¿enie albo nie ¿yjesz.}
{221} {} {Ok. Tylko uwa¿aj na te rzeczy. S¹ strasznie radioaktywne.}
{222} {} {Zabierz to idioto! Dlaczego, do diab³a, nosisz te rzeczy ze sob¹?}
{223} {} {Specjalnie na tak¹ okazjê.}
{224} {} {To z pewnego powodu.}
{225} {} {Nie. Po pierwsze, chcê wiedzieæ, kim NAPRAWDE jesteœ. Stra¿nik nie z³ama³by prawa.}
{226} {} {Nie jesteœ Stra¿nikiem. Prawdziwy Stra¿nik nie z³ama³by prawa.}

{230} {} {Reprezentujê PRAWO. W³adza jest w moich rêkach, a ty kim jesteœ? Lepiej b¹dŸ pos³uszny!}
{231} {} {Cholera...}
{232} {} {Jeœli jesteœ Stra¿nikiem, to nie jesteœ wart swojej odznaki. Pozbawiam ciê twojej rangi. Oddaj mi odznakê.}
{233} {} {Stra¿nik, który ³amie prawo, zostaje pozbawiony swojej rangi. Oddaj mi odznakê.}

{240} {} {Ha, Prawo i Porz¹dek. Te s³owa s¹ puste i nic nie znacz¹. Stra¿nicy przybyli na te ziemie, og³osili je swoj¹ w³asnoœci¹ i na³o¿yli swój *podatek*. Tylko dlatego, ¿e mogli. A dlaczego my mamy byæ gorsi? Jeœli oni kradn¹, to my te¿ bêdziemy kraœæ.}
{241} {} {W zamian wieœniacy otrzymuj¹ ochronê. A poza tym zawsze mo¿esz udaæ siê w inne miejsce.}
{242} {} {Czy wiêc Stra¿nicy nie broni¹ swoich ziem?}
{243} {} {Ludzie s¹ dla nich tylko Ÿród³em jedzenia. Rozumiesz? Nikt nie ryzykowa³by w³asnej skóry dla dobra innych. Wiem to. Stra¿nicy obiecali nam ochronê przed bandytami. I gdzie byli, kiedy rabusie zaatakowali moj¹ wioskê?}
{244} {} {Mo¿e po prostu nie zd¹¿yli na czas?}
{245} {} {Czy to powinno sprawiæ, ¿e poczujê siê lepiej? Pobrali od nas podatek za ochronê na dwa lata. Byliœmy niedo¿ywieni, ale ich to nie obchodzi³o. Ponadto zabrali wszystkie najlepsze bronie. Gdyby nie to, mo¿e sami odparlibyœmy napastników.}
{246} {} {Co za smutna historia. Prawdopodobnie jesteœ teraz bardzo z³y.}
{247} {} {Oczywiœcie. I nie myœl, ¿e teraz pozwolê ci tak po prostu odejœæ. Oddaj wszystkie swoje rzeczy. I ubrania te¿.}
{248} {} {Nie mam z tym nic wspólnego. Zostaw mnie.}
{249} {} {Niew³aœciwe postêpowanie innych ludzi nie mo¿e byæ wymówk¹. Oddaj mi swoj¹ odznakê, a zlitujê siê nad twoim nêdznym ¿yciem.}
{250} {} {To okropne. Ale musisz im wybaczyæ.}
{251} {} {Czy ty bierzesz mnie za idiotê? Zdejmij swoje rzeczy. Powoli, abym widzia³.}
{252} {} {To okropne. Dobrze ciê rozumiem, poniewa¿ moja wioska równie¿ zosta³a zniszczona przez handlarzy niewolników.}
{253} {} {Myœlê, ¿e coœ o tym s³ysza³em. Oznacza to, ¿e oboje jesteœmy wyjêci spod prawa.}
{254} {} {Dok³adnie. I nikt nie zauwa¿y, jeœli ciê za³atwiê. Po¿egnaj siê z ¿yciem, frajerze...}
{255} {} {B³agam - nie potrzeba niepotrzebnych ofiar wœród ludnoœci cywilnej. Nikt tu nie jest winny. Mœcisz siê na niew³aœciwych ludziach.}
{256} {} {WIEM. Ale co powinniœmy zrobiæ? Jesteœmy poza prawem, nie mamy dok¹d pójœæ.}
{257} {} {Co powiesz na znalezienie zwierzyny ³ownej lub ochronê karawan? Zawsze mo¿esz znaleŸæ legaln¹ drogê.}
{258} {} {Kurwa gadanie. Takiego przestêpcy nie da siê przekonaæ...}
{259} {} {Du¿o o tym rozmawialiœmy w gangu. Takie ¿ycie mog³o by siê udaæ. Na tych pustkowiach jest niewielu ludzi, a ryzyko roœnie. Czas coœ zdecydowaæ. Odznaka? Tak, weŸ to. I tak jest bezu¿yteczna.}
{260} {} {To bardzo m¹dra decyzja. Dziêkujê Ci.}
{261} {} {Wynoœ siê, zanim ciê zastrzelê.}
{262} {} {Ju¿ wychodzê...}

{300} {} {Znowu ty? Nie rozumiesz za pierwszym razem?}
{301} {} {Nie ma tu nic do rozumienia. Jesteœ zwyk³ym z³odziejem, a ja prowadzê z takimi krótki dialog.}
{302} {} {Nie masz prawa do tej ziemi i nie mo¿esz mi powiedzieæ, gdzie mam iœæ.}
{303} {} {Naprawdê jesteœ Stra¿nikiem?}