{100} {} {Widzisz bandytê.}
{101} {} {Widzisz osobê, która wcale nie wygl¹da na Stra¿nika.}

{110} {} {PodejdŸ bli¿ej, jeœli siê odwa¿ysz.}
{111} {} {W ogóle siê nie boisz?}
{112} {} {Powinieneœ siê nas baæ.}
{113} {} {Zrozum - to jest NASZE terytorium.}
{114} {} {Dziœ jest dobry dzieñ. Nie musimy œcigaæ nowej ofiary.}
{115} {} {Poka¿ mi wszystko co masz wartoœciowego.}
{116} {} {* ugniata piêœci z uœmiechem *}
{117} {} {Szukasz k³opotów, co?}
{118} {} {Módl siê, ¿eby dowódca zlitowa³ siê nad tob¹.}
{119} {} {Co robisz na naszej ziemi?}