{100} {} {Widzisz przewoŸnika.}
{101} {} {Widzisz ³ysiej¹cego rudzielca z wykrzywion¹ twarz¹.}
{102} {} {Och, wiesz, jak zadowoliæ starego ch³opa.}

# Pierwszy dialog
{200} {} {Hej, co robisz w tych dzikich miejscach?}
{201} {} {Mogê ciê szukaæ.}
{202} {} {Có¿, jestem Joe. Mieszkam tu. I strzegê tego promu. Chcesz przejœæ na drug¹ stronê? Nie ma problemu, tylko to przejœcie nie jest za nic, rozumiesz.}
{1202} {} {Có¿, jestem Joe. Mieszkam tu. I strzegê tego promu. Chcesz przejœæ na drug¹ stronê? Nie ma problemu, tylko to przejœcie nie jest za nic, sama rozumiesz.}
{203} {} {Przemyœlê Twoj¹ propozycjê.}

# Powtarzajacy siê dialog
{210} {} {Zdrowia.}
{211} {} {Do widzenia.}

{220} {} {Jak tam ¿ycie w tych dzikich miejscach?}
{221} {} {Nie narzekam. Miejsca te wcale nie s¹ tak g³uche. Kilka razy dziennie ktoœ siê tu pojawi - teraz Stra¿nicy, potem rybacy, potem przypadkowi podró¿nicy. Ka¿dy podzieli siê czymœ za przeprawê. Mam doœæ na ¿ycie.}
{222} {} {[Dalej.]}
{223} {} {Oczywiœcie czasami nawiedzaj¹ je wilki i kretoszczury, ale przez lata nauczy³em siê z nimi dogadywaæ. Nawiasem mówi¹c, zastawiam sid³a w lesie, wiêc nie zjezd¿aj ze szlaku, nie chcê ciê wyci¹gaæ potem z w³asnych pu³apek.}

{224} {} {Opowiedz mi o promie.}
{225} {} {Rangersi zaoferowali, a ja zbudowa³em. Od tamtej pory tu mieszkam. Ka¿dy, kto potrzebuje przejœæ na drug¹ stronê, mo¿e na mnie liczyæ.}
{226} {} {Dlaczego ktoœ mia³by przejœæ na drug¹ stronê?}
{227} {} {W wiêkszoœci przypadków patrole Rangersów tego potrzebuj¹. Ale nawet bez nich jest wystarczaj¹co du¿o chêtnych. Wielu ucieka na inne ziemie w nadziei na znalezienie czystszego miejsca do ¿ycia. Ale powiem ci coœ - gdziekolwiek uciekasz, jest tam to samo gówno.}
{228} {} {Czy Rangersom nie przeszkadza, ¿e pobierasz op³atê?}
{229} {} {Nie, bo p³acê od nich podatek. Oznacza to, ¿e raz w miesi¹cu oddaje wszystkie wartoœciowe nadwy¿ki - skóry, miêso, znaleziska podró¿ników. Czasami sam nie rozumiem niektórych rzeczy które mi oddaj¹, ale Stra¿nicy je rozumiej¹.}

{230} {} {Jak katastrofa tamy wp³ynê³a na Twój biznes?}
{231} {} {Kiedy nast¹pi³ zrzut wody, wszystko tutaj zosta³o zalane. Nadal nie wyci¹gn¹³em ca³ego brudu z tej chaty! Nie wiem, kto móg³ coœ takiego zaaran¿owaæ. Ale teraz pracujê tylko dla siebie - czyli prom przynosi mi wiêksze zyski.}
{232} {} {Ciekawe. Powiedz mi wiêcej.}
{233} {} {W tej chwili chcia³em z tob¹ wiêcej porozmawiaæ.}

{250} {} {Ta rodzina musi przejœæ na drug¹ stronê.}
{251} {} {No to musisz zap³aciæ. Nie jest drogo, ale jeœli nie zap³acisz, nie bêdziesz móg³ uruchomiæ wyci¹garki, poniewa¿ zawsze trzymam przy sobie r¹czkê do mechanizmu.}
{252} {} {Zobaczmy, ile jest warta.}
{253} {} {Proszê ciê w imieniu Stra¿ników.}
{254} {} {Cholera, kolejny zmarnowany dzieñ... Trzymaj t¹ r¹czkê. Ale sam sobie pokrêæ.}
{1254} {} {Cholera, kolejny zmarnowany dzieñ... Trzymaj t¹ r¹czkê. Ale sam sobie pokrêæ.}
{255} {} {Dziêki.}
{256} {} {Jasne...}
{257} {} {Czekaj, muszê zapytaæ j¹ o gotówkê.}
{258} {} {Po prostu siê zamknij i wspó³pracuj. W przeciwnym razie otrzymasz coœ, czego nie chcesz otrzymywaæ.}
{259} {} {No dalej, poka¿ co potrafisz, brudasie! Udusi³em wilki moimi rêkoma, czym s¹ twoje puste groŸby dla mnie?}
{260} {} {Wystarczy!}
{261} {} {Nie lubiê siê targowaæ, wiesz.}
{262} {} {[Dalej.]}