{100} {} {Widzisz wartownika.}
{101} {} {Widzisz Stra¿nika na posterunku. Strze¿e wejœcia do tamy.}

# Przejœcie do œrodka
{110} {} {Porozmawiaj z Jackiem, jeœli chcesz siê przy³¹czyæ.}
{111} {} {To Jack decyduje, czy wpuœciæ typów takich jak ty.}
{112} {} {Chcesz siê przy³¹czyæ? Powiedz o tym Jackowi.}
{113} {} {Nie mam rozkazu, aby ciê wpuœciæ.}
{114} {} {Wynoœ siê st¹d, to nie jest strefa spacerowa.}

{115} {} {WejdŸ i nie przeszkadzaj mi.}
{116} {} {Dali ci przepustkê, czego jeszcze potrzebujesz?}
{117} {} {Nie obs³ugujemy turystów.}
{118} {} {Jeœli chcesz sprawdziæ tamê, idŸ i sprawdŸ j¹.}
{119} {} {Nie rozpraszaj wartownika na s³u¿bie.}

# Tytul Ranger
{120} {} {Nie wa¿ siê rozpraszaæ mnie poczt¹.}
{121} {} {Potrzebujesz porady? Wynoœ siê st¹d i nie zwlekaj.}
{122} {} {Ludzie tacy jak ty mog¹ siê wiele nauczyæ od Stra¿ników.}
{123} {} {Nie lubiê bezczynnych gapiów zataczaj¹cych mi siê tutaj.}
{124} {} {Jeœli zostaniesz kadetem, dowódca da ci wycisk.}

{125} {} {Gratulujê do³¹czenia, zwiadowco.}
{126} {} {Byæ mo¿e dosta³eœ odznakê, ale musisz osobno zas³u¿yæ na mój szacunek.}
{127} {} {Bêdê ciê pilnowa³... Stra¿niku.}
{128} {} {Utrzymaj porz¹dek na pustkowiach.}
{129} {} {Mam nadziejê, ¿e teraz czujesz siê odpowiedzialny za Pustkowia.}

# Szaty
{130} {} {Wynoœ siê st¹d, przeklêty kultysto!}
{131} {} {Wygl¹dasz jak chodz¹cy cel w tej szacie.}

{132} {} {Nigdy nie widzia³em œmieszniejszej zbroi.}
{133} {} {Kto pozwoli³ ci dotkn¹æ znaków drogowych?}

{134} {} {Wiesz, w tym niebieskim kombinezonie jesteœ ³atwym celem na szarej pustyni.}
{135} {} {Masz œmieszne ubrania.}

{136} {} {Hej, kto da³ ci tê zbrojê? Odpowiedz natychmiast!}
{137} {} {Witaj Ran... Hej, nie pamiêtam, ¿ebyœ zosta³ zapisany do naszych szeregów!}

{138} {} {Co to jest? Zdejmij to natychmiast!}
{139} {} {Kadeci otrzymuj¹ doskona³e stroje ze skóry braminów.}

#Reputacja
{140} {} {OdejdŸ ode mnie.}
{141} {} {Nie bêdê z tob¹ rozmawiaæ.}
{142} {} {Masz coœ do powiedzenia?}
{143} {} {Nie powinieneœ pozostawaæ w tej osadzie.}

{144} {} {Nasze kule przynosz¹ mi³osierdzie.}
{145} {} {Czeœæ.}
{146} {} {Nie wyg³upiaj siê, jeœli chcesz zachowaæ swoj¹ reputacjê.}

{147} {} {Mi³o ciê widzieæ.}
{148} {} {Jak siê masz?}
{149} {} {Mi³ej podró¿y.}