{100} {} {Widzisz Stra¿nika Jacka.}
{101} {} {Widzisz Stra¿nika na posterunku. Strze¿e wejœcia do tamy.}
{102} {} {Hej, hej, wynoœ siê z t¹ cholern¹ puszk¹! Nie ¿artujê!}
{103} {} {Nie negocjujemy z sekciarzami wszelkich warstw. OdejdŸ!}

# Pierwszy dialog
{200} {} {(Zbli¿aj¹c siê do wartowników, zauwa¿asz, jak podnosz¹ broñ i zmieniaj¹ wyrazy twarzy.) Czekaj, obcy nie maj¹ tu wstêpu.}
{201} {} {Co tam jest?}
{202} {} {Tam, co? Za * tymi * drzwiami? Znajduje siê tam g³ówna siedziba Rangersów.}
{203} {} {Ach, to wszystko. Wiêc nie muszê tam iœæ.}
{204} {} {Wiêc nie ma siê czym chybotaæ.}
{205} {} {Ok.}
{206} {} {Czekaj, jaki masz interes w bazie?}
{207} {} {Niewa¿ne.}
{208} {} {Muszê tylko porozmawiaæ z twoim dowódc¹.}
{209} {} {No có¿. Nie ka¿demu kadetowi wolno zejœæ na dó³. A jeszcze mniej Tobie. Masz przepustkê?}
{210} {} {Zaraz tego po¿a³ujesz.}
{211} {} {Ok, nie ma problemu.}
{212} {} {Hej, to jest bardzo wa¿ne.}
{213} {} {Jeœli którykolwiek ze Stra¿ników ciê poleci, mo¿esz byæ w stanie wejœæ do œrodka. Podaj teraz wa¿niejszy powód. Albo siê wynoœ.}
{214} {} {Ok, mo¿esz przejœæ. Pamiêtaj jednak, ¿e bêdziemy pod¹¿aæ za ka¿dym Twoim krokiem. IdŸ do genera³a i nigdzie nie wêsz. Trzymaj broñ w kaburze.}
{215} {} {Nie trzeba nic dodawaæ.}
{216} {} {Dziêki, Stra¿niku.}
{217} {} {Muszê porozmawiaæ z twoim dowódc¹.}
{218} {} {Twój kwatermistrz bêdzie zainteresowany moimi towarami.}
{219} {} {Po¿a³ujesz, jeœli bêdziesz sprawiaæ problemy. OdejdŸ.}

{220} {} {Nie chodŸ po bazie w tej szmacie. Wielu mo¿e wzi¹æ ciê za sabota¿ystê.}
{221} {} {Dlaczego?}
{222} {} {Wiesz dlaczego. To jest p³aszcz Wyznawców Ognia i nie lubimy tych goœci. Wszêdzie siê pchaj¹ z tym swoim koœcio³em. To niedopuszczalne.}
{223} {} {Rozumiem.}
{224} {} {To jest facet, na którego czeka³ Stary Rufus? Brawo za sprowadzenie go. Niech przyniesie korzyœci Pustkowiom. Dla takich rzemieœlników jak on nie ma miejsca na œmietnisku.}
{1224} {} {To jest facet, na którego czeka³ Stary Rufus? Brawo za sprowadzenie go. Niech przyniesie korzyœci Pustkowiom. Dla takich rzemieœlników jak on nie ma miejsca na œmietnisku.}
{225} {} {To ju¿ nie moja sprawa. Mo¿esz to rozwi¹zaæ beze mnie.}
{226} {} {Dobrze, ¿e znaleŸliœmy wspólny jêzyk.}
{227} {} {Hej, czy jesteœ zmêczony ¿yciem?! Co do diab³a sta³o siê z Flickiem?}
{228} {} {Byliœcie z nim jakoœ powi¹zani?}
{229} {} {My? Po³owa bazy myœla³a, ¿e jest suk¹. Ale to nie jest powód do zabijania kupca! Okej, nie wiem, co siê tam wydarzy³o. Wyjaœni to komisja. A jeœli jesteœ w to w jakiœ sposób zaanga¿owany, nie oczekuj od Stra¿ników niczego dobrego.}
{1229} {} {My? Po³owa bazy myœla³a, ¿e jest suk¹. Ale to nie jest powód do zabijania kupca! Okej, nie wiem, co siê tam wydarzy³o. Wyjaœni to komisja. A jeœli jesteœ w to w jakiœ sposób zaanga¿owana, nie oczekuj od Stra¿ników niczego dobrego.}

{230} {} {Komandor Helford zagwarantowa³ mi przepustkê.}
{231} {} {Genera³a mo¿e zainteresowaæ historia Keruka z Flagpool.}
{232} {} {Pomog³em Stra¿nikowi w San Brahmin.}
{1232} {} {Pomog³am Stra¿nikowi w San Brahmin.}
{233} {} {Mam informacje od szpiega w Tu-San.}
{234} {} {Baza powinna byæ œwiadoma moich powi¹zañ z rebeliantami Phoenix.}
{235} {} {Mam bardzo wa¿ne informacje. Dotyczy to Bractwa Stali.}
{236} {} {Hej, tylko przechodzê.}
{237} {} {Mam raport prosto z katedry w Phoenix.}

# Powtarzajacy siê dialog
{250} {} {Czeœæ.}
{251} {} {Do widzenia.}

{260} {} {Chcê zg³osiæ zbieg³ego szpiega ukrywaj¹cego siê w chacie na starej drodze...}
{261} {} {...Dziêki za cynk. Wyœlemy tam zwiadowców i spróbujemy zaskoczyæ drania.}
{262} {} {}
{263} {} {Sukcesu w operacji.}

{270} {} {Czy mogê przejœæ na drug¹ stronê?}
{271} {} {To decyzja dowódców. Cywile nie maj¹ wstêpu na zaporê. Jeœli chcesz przejœæ na drug¹ stronê, proponujê nauczyæ siê p³ywaæ.}
{272} {} {Gdzie jest najbli¿szy prom?}
{273} {} {Piêtnaœcie mil w dó³ rzeki jest prom.}
{274} {} {Wiêc okupujecie jedyne przejœcie na drug¹ stronê?}
{275} {} {Tak. I to jest nasze prawo. Jakiœ problem?}
{276} {} {Uch, nie, ¿aden.}
{277} {} {Tak. To niesprawiedliwe.}
{278} {} {Wiêc masz problem.}
{279} {} {W ten sposób...}
{280} {} {Dlaczego nie pozwolisz tej kobiecie zobaczyæ genera³a?}
{281} {} {Genera³ jest zbyt zajêty.}
{282} {} {Naprawdê? Wydaje mi siê, ¿e po prostu nie chce odpowiadaæ za wystêpki swoich ¿o³nierzy.}
{283} {} {Co to za bzdury? Ta kobieta ¿y³a z przestêpc¹ i dosta³a to, na co zas³u¿y³a. Jeœli chcesz jej pomóc, to lepiej zabierz j¹ z dala od bazy, zanim w koñcu stracê panowanie nad sob¹.}
{284} {} {Ok, chodŸmy.}