{100} {} {Widzisz kadeta Presleya.}
{101} {} {Widzisz jednego z rekrutów.}
{102} {} {Spoczywaj w pokoju, kadecie Presley.}
{103} {} {Hej kadecie, nie wa¿ siê umieraæ!}
{104} {} {Powodzenia na drodze.}
{105} {} {Chata Miltona jest przed nami, ale musimy znaleŸæ wejœcie do jaskini.}
{106} {} {Masz k³opoty z rodzin¹ Milton?}

# Pierwszy dialog
{200} {} {(Przed tob¹ stoi m³ody kadet z bardzo niezadowolonym spojrzeniem; siedzi w pozycji oczekiwania i od czasu do czasu kopie œmieci pod stopami, aby z³agodziæ napiêcie.)}
{201} {} {Dlaczego nie jesteœ w szeregach?}
{202} {} {Komendant Agatha zgani³a mnie za bycie nieuczciwym. Co ciê to obchodzi?}
{203} {} {Jesteœ upartym ¿o³nierzem, prawda?}
{204} {} {Cholera, jestem po prostu zmêczony tym bezcelowym æwiczeniem! Chcê * prawdziwych * misji w terenie, a nie strzelaæ do kojotów na trasach karawan.}
{205} {} {Wygl¹da na to, ¿e masz du¿e ambicje, ch³opcze.}
{206} {} {Mo¿e tak. Ale uwa¿am, ¿e nie ma sensu czekaæ kolejne trzy lata przed pierwszym testem. Jeœli Komendant Agatha nie zwróci mojego sprzêtu i nie zwolni mnie do pracy, pójdê tam tylko z jedn¹ w³óczni¹.}
{207} {} {Jest jak jest. W miêdzyczasie porozmawiam z twoim dowódc¹.}
{208} {} {Jesteœ tylko narcystycznym typkiem. Czeœæ, frajerze.}
{209} {} {Nie b¹dŸ dla mnie niegrzeczny, ¿ó³tog³owy.}

# Powtarzajacy siê dialog
{210} {} {Czego chcesz?}
{211} {} {Nic. Bywaj.}

{220} {} {Dlaczego wzi¹³eœ karabin z magazynu?}
{221} {} {Broñ wojskowa jest wydawana tylko na misje i szkolenia. Ponadto musisz oszczêdzaæ naboje. Chcia³em zabraæ karabin i udaæ siê do jaskini Gyers Wash. Ale kwatermistrz szybko wyczu³ mój plan.}
{222} {} {Co jest takiego wa¿nego w tej jaskini?}
{223} {} {Miejscowi mówi¹, ¿e w jaskini s¹ gryzonie i bardzo ich denerwuj¹. Ale wszyscy Stra¿nicy s¹ zajêci, a dowódcy odmawiaj¹ wys³ania kadetów, myœl¹, ¿e nie jesteœmy gotowi.}
{224} {} {[Dalej.]}
{225} {} {Chcia³em samemu poradziæ sobie z problemem, ¿eby móc utrzeæ nosy wszystkim staruszkom w paskach. Powinniœmy coœ robiæ, a nie trz¹œæ siê na si³owni!}
{226} {} {Twoje oddanie jest godne podziwu.}
{227} {} {Myœlê, ¿e chcia³eœ siê tylko pokazaæ.}
{228} {} {Co powiedzia³eœ o jaskini Gyers Wash?}

{230} {} {Czy dogadujesz siê z innymi kadetami?}
{231} {} {Z ka¿dym jest inaczej. Niektórzy mnie wkurzaj¹, staram siê ich ignorowaæ.}
{232} {} {Rozumiem.}
{233} {} {Szczerze, czy kiedykolwiek zabi³eœ... cz³owieka?}
{234} {} {Jeszcze nie. W najlepszym przypadku kadeci s¹ wysy³ani do strzelania do wilków. Ale zabije tych œmieci jak ka¿dy Stra¿nik.}
{235} {} {Nawet o tym nie pomyœla³em.}

#Zadanie
{300} {} {O tym wypadzie. Mo¿emy to zrobiæ razem.}
{301} {} {Powa¿nie? Ale dlaczego chcesz ryzykowaæ?}
{302} {} {Ja te¿ chcê wzi¹æ udzia³ w nalocie. Bêdzie fajnie.}
{303} {} {Zgadza siê. Nie wolno nam strzelaæ z powa¿nej broni i mamy oszczêdzaæ amunicjê, a strzelanie z pneumatyki ma sens tylko do martwych celów.}
{304} {} {Chcê pomóc Rangersom w ich trudnym interesie.}
{305} {} {Szukasz przyjació³ wœród naszych ludzi? Sprytnie. Ka¿dy na pustkowiu potrzebuje silnego patrona.}
{306} {} {Agatha poprosi³a mnie o towarzyszenie Ci.}
{307} {} {Naprawdê? Myœlisz, ¿e potrzebujê mentora, aby strzelaæ do zwyk³ych gryzoni? Chocia¿... partner nie zaszkodzi... Tak, a œwiadek jest potrzebny, na wszelki wypadek.}
{308} {} {Wiêc?}
{309} {} {Ok! Ale nie mogê tam pójœæ bez broni.}
{310} {} {Papier na wydanie broni jest ju¿ na biurku kwatermistrza. Nie dziêkuj.}
{311} {} {Co?! Jak ci siê to uda³o?! Super, idê teraz do magazynu. Ty te¿ przygotuj siê na wypad. Spotkamy siê na zewn¹trz, niedaleko centrum informacyjnego.}
{312} {} {Do zobaczenia.}

{320} {} {Jestem gotowy do drogi. A ty?}
{321} {} {Poczekaj trochê d³u¿ej.}
{322} {} {Czego mo¿emy siê spodziewaæ?}
{323} {} {W jaskini bêdzie ciemno, powinieneœ zaopatrzyæ siê w kilka rac. I najprawdopodobniej jest pe³na kretoszczurów. Same s¹ s³abe, ale zbiorowo mog¹ stanowiæ problem. Najlepsz¹ broni¹ przeciwko takiemu t³umowi jest strzelba. Jednak nie mam pojêcia, sk¹d j¹ wzi¹æ.}
{324} {} {Warto to rozwa¿yæ.}
{325} {} {W takim razie ruszajmy siê.}
{326} {} {Dlaczego wróciliœmy? O czymœ zapomnia³eœ?}
{1326} {} {Dlaczego wróciliœmy? O czymœ zapomnia³aœ?}
{327} {} {Nie martw siê, to nie potrwa d³ugo.}
{328} {} {Ok, ale przejdŸmy do rzeczy.}
{329} {} {Ok.}
{330} {} {Taki t³um? To nie jest najlepsza taktyka dla ciasnych jaskiñ. Poza tym tak bardzo odstraszymy zwierzêta. Ktoœ bêdzie musia³ zostaæ w tyle.}
{331} {} {Porozmawiam o tym z moim partnerem.}
{332} {} {Pos³uchaj, co do tej sprawy z rodzin¹ Miltonów. Umówmy siê, ¿e nie mamy z tym nic wspólnego, dobrze? Nie powinienem by³ iœæ na tê cholern¹ wyprawê. Nie s¹dzê, ¿eby g³owa kretoszczura by³a tego warta. Do widzenia.}
{333} {} {Zegnaj kadecie Presley.}
{334} {} {Dlaczego... dlaczego on to zrobi³?}
{335} {} {Wszystko w porz¹dku?}
{336} {} {Nie wiem... Ten bandyta... Mia³ broñ, móg³ znaleŸæ inny sposób na prze¿ycie. Ale zaatakowa³ bezbronn¹ rodzinê. Dlaczego to zrobi³?}
{337} {} {Nie zna³ innego sposobu.}
{338} {} {Nie jestem lepszy, prawda? Teraz rozumiem, dlaczego potrzebne by³o ca³e to szkolenie w bazie. I dlaczego nie wolno nam wykonywaæ wa¿nych zadañ. Teraz powa¿nie potraktujê s³owa weteranów.}
{339} {} {Ta wycieczka uczyni³a ciê trochê m¹drzejszym. Do widzenia, kadecie.}
{340} {} {Zapamiêtaj g³ówn¹ lekcjê pustkowi - zabij, albo sam zostaniesz zabity. Muszê teraz wróciæ na pustyniê.}
{341} {} {To by³a œwietna operacja, prawda? Poka¿ê g³owê innym w jadalni. Powodzenia na drodze.}
{342} {} {Zegnaj kadecie Presley.}

{350} {} {Uwa¿aj.}
{351} {} {PrzejdŸmy dalej.}
{352} {} {Wiêc jakie jest nasze zadanie?}
{353} {} {ZnaleŸæ i wykoñczyæ Nat-Aani. Tak mieszkañcy nazwali najwiêkszego i najniebezpieczniejszego szczura w tej jaskini.}
{354} {} {Co oznacza ta nazwa?}
{355} {} {Tylko to, ¿e jest liderem stada. Oznacza to, ¿e jest najsilniejszym i najbardziej okrutnym ze swoich dzikich braci.}
{356} {} {Co wiesz o rodzinie Miltonów?}
{357} {} {Czy serio ciê to obchodzi? Có¿, to zwykli mieszkañcy o niskich dochodach, ¿yj¹ g³ównie ze zbieractwa i rybo³ówstwa. Nie mam o nich nic wiêcej do powiedzenia.}
{358} {} {Nie rozmawiajmy ju¿ o tym.}
{359} {} {Co do cholery sta³o siê z Miltonami? Nigdy nie wydawali siê wrogo nastawieni.}

{360} {} {Zrobiliœmy to! Odetnê g³owê tej œwini i poka¿ê staruszkom w bazie. Teraz dowiedz¹ siê, ¿e jestem gotowy na powa¿ne misjê!}
{361} {} {Czy w³aœnie dlatego poszed³eœ na polowanie?}
{362} {} {Oczywiœcie. Dlaczego jeszcze mia³bym pomagaæ tym ludziom? S¹ ma³o przydatni, nagrody nie dadz¹, a reputacjê ju¿ mamy wystarczaj¹co dobr¹. Ale maj¹c takie osi¹gniêcie, mam prawo do przynajmniej podwójnej porcji. Ha!}
{363} {} {Hmm. WyjdŸmy.}

{364} {} {Co?! Czy to jakiœ ¿art? Nie liczy³em na walkê z bandyt¹, kiedy tu szed³em!}
{365} {} {O co chodzi, kadecie? Przed chwil¹ cieszy³eœ siê jak œwir, kiedy odci¹³eœ g³owê kretoszczurowi.}
{366} {} {Ale to co innego! Och, cholera, co za z³y czas... Co mam teraz zrobiæ?}
{367} {} {Musimy dzia³aæ teraz. Czekaj¹c na pomoc, bêdzie mia³ czas na ucieczkê lub przygotowanie siê do oblê¿enia. Ktoœ na pewno umrze.}
{368} {} {Racja. Teraz mamy szansê. Nie spodziewa siê, ¿e siê pojawimy i jest zajêty innymi sprawami. Ale b¹dŸmy ostro¿ni - cz³owiek nie jest besti¹, jest m¹drzejszy.}
{369} {} {ChodŸmy.}
{370} {} {Nie mo¿emy przeciwstawiæ siê bandycie ze strzelb¹. Musimy uciec do bazy.}
{371} {} {Dobrze. Ale w tym czasie dok³adnie siê przygotuje i prawdopodobnie kogoœ zabije. Lepiej chodŸmy st¹d i nikomu o tym nie mówmy.}
{372} {} {ChodŸmy.}