{100} {} {Widzisz Rangersa.}
{101} {} {Widzisz szeregowego Stra¿nika.}
{102} {} {To jest tymczasowy oddzia³ izolacyjny, nie powinno tu byæ nikogo z zewn¹trz.}

# Plywajace repliki
{110} {} {Dopóki nie wyeliminujemy Szakali, droga na pó³noc jest zamkniêta.}
{111} {} {Chcia³bym postawiæ kufel piwa temu, który uwolni³ nas od Szakali.}
{112} {} {Nie mogê uwierzyæ, ¿e znosimy te Szakale!}

{113} {} {Mówi¹, ¿e na pó³nocy poœrodku ja³owej pustyni s¹ zielone plantacje.}
{114} {} {Cholera, nawet wieœniacy z Villi ugieli siê pod naszym wrogiem.}
{115} {} {Ci ch³opi z pó³nocy ¿¹daj¹ zbyt wiele za swoje plony.}

{116} {} {Pasterze w San Brahmin nie przetrwaj¹ bez Rangersów.}
{117} {} {Ci pasterze w San Brahmin bêd¹ ¿a³owaæ, ¿e zdradzili nasz sojusz.}
{118} {} {Czerwone zagro¿enie prawie przejê³o San Brahmin, ale nic siê nie sta³o.}

{119} {} {Flagpool zap³aci kiedyœ za niewolnictwo.}
{120} {} {Dopóki Flagpool nie jest zaanga¿owane w niewolnictwo, nie obchodzi mnie, co siê tam dzieje.}
{121} {} {Flagpool siê powiêksza. To niedobrze.}

{122} {} {Czciciele ognia musz¹ zostaæ powstrzymani, zanim ostatecznie spal¹ te ziemie.}
{123} {} {Kult ognia zosta³ pokonany w³asn¹ broni¹.}
{124} {} {Ci przeklêci kultyœci przejmuj¹ kolejne ziemie.}

{125} {} {Co to za tajemnicze „zagro¿enie z po³udnia”?}
{126} {} {Bractwo Stali dosta³o to, na co zas³u¿y³o. Nie ma potrzeby wchodzenia na obce ziemie.}
{127} {} {Ale czy mo¿emy przeciwstawiæ siê Bractwu Stali?}

{128} {} {Zapora Parkera by³a wytworem m¹droœci mieszkañców Starego Swiata.}
{129} {} {Cholera, zamiast tego utworzenie nowej bazy nie bêdzie ³atwe.}
{130} {} {Stary Rufus zrobi³ coœ w elektrowni.}

{131} {} {Ten ch³op ma wspania³e perspektywy.}
{132} {} {Czy wszyscy mieszkañcy Villi to sami wspaniali ludzie?}

{133} {} {Musimy mieæ oko na tego ch³opa.}
{134} {} {Musimy lepiej poznaæ tego ch³opa.}

{135} {} {Ten ch³op wygl¹da podejrzanie.}
{136} {} {Nie lubiê tego ch³opa.}

{137} {} {Pewnego dnia zmienimy Pustkowia.}
{138} {} {Mówi¹, ¿e ktoœ zabi³ przewoŸnika.}
{139} {} {Ktoœ kopa³ groby naszych braci. I nie wygl¹da to na mutanty z pustkowia.}

{140} {} {Cisza i spokój w akwedukcie.}
{141} {} {Trudno by³o sobie wyobraziæ, ¿e to Garth sta³ za zaginiêciami.}
{142} {} {William Garth nadal jest paranoikiem.}

# Uwagi dotycz¹ce odpowiedzi
{150} {} {Wojownicy s¹ lojalni wobec swoich idei. Do ostatniego oddechu.}
{151} {} {Nasze kule trafiaj¹, zawsze.}
{152} {} {Pewnego dnia zmienimy Pustkowia.}
{153} {} {By³oby wspaniale mieæ samochód na chodzie...}
{154} {} {Najwy¿szy czas zaj¹æ siê tymi krwio¿erczymi Szakalami.}
{155} {} {Czerwone zagro¿enie roœnie na wschodzie.}
{156} {} {Uwa¿aj na pustkowiach.}
{157} {} {Jesteœ tutaj w pe³ni chroniony.}
{158} {} {Nie pytaj mnie o nic.}
{159} {} {By³byœ dobrym Stra¿nikiem.}
{160} {} {Najbardziej przera¿aj¹ce potwory na pustyni pojawiaj¹ siê w nocy.}
{161} {} {Powodzenia.}

{170} {} {Szukasz k³opotów?}
{171} {} {Nasze kule nie chybiaj¹, pamiêtaj.}
{172} {} {Jesteœ na czas - potrzebujemy ¿ywych celów na strzelnicy.}
{173} {} {Nie wybierasz siê czasem na wycieczkê?}
{174} {} {O czym myœlisz?}
{175} {} {Hmm, wygl¹dasz podejrzanie.}
{176} {} {Nie pytaj mnie o nic.}
{177} {} {Nikt ciê tutaj nie ochroni.}
{178} {} {Zmienimy pustkowiê.}
{179} {} {Jakiœ problem?}

{180} {} {Mi³o ciê poznaæ, Rangersie.}
{181} {} {Przepraszam, ale nie mogê Ciê eskortowaæ do bazy.}
{182} {} {Ulepszasz Pustkowia.}
{183} {} {Cieszymy siê, ¿e jesteœ po naszej stronie.}
{184} {} {Wpadnij do naszej bazy.}
{185} {} {Uwa¿aj na siebie, zwiadowco.}
{186} {} {Nie mogê siê doczekaæ, a¿ us³yszê twoje historie o nowych ziemiach.}
{187} {} {By³oby wspaniale mieæ samochód na chodzie...}
{188} {} {Pewnego dnia zmienimy Pustkowia.}
{189} {} {Nie daj siê oszukaæ innym.}