{100} {} {Widzisz Rangersa Agathê.}
{101} {} {Widzisz Stra¿nika weterana w zbroi bojowej.}
{102} {} {Stra¿nik ciê ignoruje. Lepiej trochê poczekaæ.}
{103} {} {Nie chcê ciê widzieæ.}
{104} {} {Agatha ciê ignoruje.}

# Scena ze sporu z genera³em:
{110} {} {To szaleñstwo!}
{111} {} {Wiesz, ilu naszych ludzi zosta³o zabitych przez Szakale?!}
{112} {} {Te szumowiny musz¹ zostaæ zniszczone!}
{113} {} {Ka¿dy jeden szczeniak!}
{114} {} {A ty... zawierasz z nimi sojusz!}
{115} {} {To obrzydliwe!}
{116} {} {Mo¿esz mnie skarciæ tyle, ile chcesz za z³amanie ³añcucha dowodzenia...}
{117} {} {Ale inni Rangersi zgadzaj¹ siê ze mn¹ - to nie w porz¹dku!}
{118} {} {Zaden sojusz nie zmieni tych dzikusów...}
{119} {} {...i na pewno nie zwróci martwych Rangersów.}
{120} {} {I nie zostawiê tego tak ³atwo!}

{200} {} {Hej! To Twoja wina! Szakale od lat terroryzuj¹ ziemie na pó³nocy. Wielu znakomitych Rangersów zginê³o z powodu ich sztuczek. Nie zamierzam tolerowaæ tego bluŸnierczego sojuszu z dzikusami. Teraz zniknij!}
{201} {} {Naucz siê wybaczaæ. Mo¿e zmienisz zdanie, gdy zobaczysz prawdziwe perspektywy tego uk³adu.}
{202} {} {Twojemu mózgowi bojowemu brakuje zmarszczek, by doceniæ ten rozejm. Pozostañ w ciemnoœci, kobieto.}