{100} {} {Widzisz kartografa.}
{101} {} {Widzisz Rangersa w zwyk³ym ubraniu z du¿ymi okularami na nosie. Wygl¹da na to, ¿e ci¹g³a praca o zmroku os³abi³a jego wzrok.}

{200} {} {(Widzisz s³abo widz¹cego Stra¿nika; jego mundur wisi na nim jak na wieszaku, a okulary z wymiennymi soczewkami pozwalaj¹ mu widzieæ; kiedy ciê dostrzega, poprawia soczewki i krzywi siê, spogl¹daj¹c na twoj¹ twarz) He? Kto Ciê wpuœci³? Mog¹ tu wchodziæ tylko Rangersi.}
{201} {} {Nie martw siê, wolno mi.}

{210} {} {Czeœæ.}
{211} {} {Do widzenia.}
{212} {} {Cofnijmy siê trochê.}
{213} {} {Hej?}

#Pytania
{220} {} {Co tutaj robisz?}
{221} {} {Moim zadaniem jest tworzenie nowych map Pustkowi. Sprawa jest ¿mudna i bardzo pracoch³onna.}
{222} {} {Co jest nie tak ze starymi mapami?}
{223} {} {S¹ przestarza³e. Oczywiœcie rzeŸba prawie siê nie zmieni³a od czasów Wielkiej Wojny, ale niektóre jeziora i rzeki wysch³y, pojawi³y siê obszary radioaktywne i powsta³y nowe osady. Obecnie tylko Rangersi i karawany znaj¹ szczegó³owo geografiê otoczenia. Ale nawet nasze patrole czasami potrzebuj¹ precyzyjnych wspó³rzêdnych. A nikt obecnie nie tworzy nowych map... Nikt oprócz mnie.}
{224} {} {Co wskazujesz na tych mapach?}
{225} {} {Wszystko, czego nasz brat bêdzie potrzebowa³ w drodze: osady, farmy, posterunki, obszary radioaktywne, oazy. Wszelkie informacje kartograficzne mog¹ byæ przydatne w centrum dowodzenia.}
{226} {} {Czy mogê przestudiowaæ twoje mapy?}
{227} {} {Tylko za zgod¹ prze³o¿onego dowódcy.}
{228} {} {Tak, oczywiœcie. Nie mamy ¿adnych tajemnic wœród naszych.}
{229} {} {Czy oprócz tworzenia map masz inne obowi¹zki?}
{230} {} {Zostajê rzucony na ka¿d¹ pracê, która wymaga czytania i pisania.}
{231} {} {Wiêc czy to dlatego nobisz te gogle?}
{232} {} {Zartujesz sobie ze mnie? Od lat tworzê mapy i teksty o zmierzchu. Dlatego bez okularów prawie nic nie widzê... Do diab³a, wiesz, jeœli zmusz¹ mnie do opuszczenia bazy, to bêdzie to ostatni dzieñ w moim ¿yciu.}
{233} {} {Dlaczego nadal tu jesteœ?}
{234} {} {Chocia¿ centrum dowodzenia zosta³o zniszczone, nie zmienia to moich obowi¹zków.}

#Kwarc
{250} {} {Komandor Helford wys³a³ mnie do Quartz.}
{251} {} {Naprawdê? Prawdopodobnie dowódca nie ma wystarczaj¹cej liczby ludzi... d³ugo prosi³em go o wykonanie tam pomiarów geodezyjnych.}
{252} {} {No, zapomnij.}
{253} {} {Co mo¿esz mi powiedzieæ o tym miejscu?}
{254} {} {S¹ to stare ruiny staro¿ytnego miasta. (wskazuje na mapê) Przez d³ugi czas po Wielkiej Wojnie pozostawa³y radioaktywne. W po³¹czeniu z gor¹cym pustynnym klimatem miejsce to skutecznie odstraszy³o osadników i podró¿ników. Dopiero niedawno poziom promieniowania spad³ do akceptowalnego poziomu. Dlatego do niedawna nie przywi¹zywaliœmy do tych ruin zbytniej uwagi.}
{255} {} {Muszê dowiedzieæ siê wiêcej o Quartz.}
{256} {} {Nie musisz kontynuowaæ.}
{257} {} {Dlaczego Quartz by³o radioaktywne?}
{258} {} {Promieniowanie przynios³y tam burze z zachodu, z Kalifornii. Ziemie te zosta³y mocno zniszczone przez wybuchy nuklearne podczas Wielkiej Wojny.}
{259} {} {Jakie niebezpieczeñstwa mog¹ na mnie tam czekaæ?}
{260} {} {Pozosta³oœci radioaktywnoœci, radskorpiony, zawalenia siê zniszczonych budynków... Ogólnie Quartz by³o do tej pory doœæ spokojnym miejscem.}
{261} {} {Jakie pomiary nale¿y wykonaæ?}
{262} {} {Obawiam siê, ¿e to za du¿o pracy dla jednej osoby: rzeŸba terenu, obszary promieniowania, stan s¹siedztwa, roœlinnoœæ...}
{263} {} {Mój Pip-Boy ma wbudowany czujnik mapy.}
{264} {} {Naprawdê? Wow, wiêc jesteœ prawdziwym darem niebios dla mojej pracy. Poka¿ê ci pozycje obserwacyjne. Twoim zadaniem jest po prostu udaæ siê tam i zapisaæ dane.}
{265} {} {Wszystko jasne. Wrócê, kiedy skoñczê.}
{266} {} {Nie zamierzam traciæ czasu na ¿adne mapy. Ale muszê dowiedzieæ siê wiêcej o Quartz.}
{267} {} {Swietnie! Wyœwiadczysz olbrzymi¹ przys³ugê wszystkim Rangersom.}
{268} {} {Ok, ale wci¹¿ mam pytania dotycz¹ce Quartz.}
{269} {} {Do zobaczenia.}
{270} {} {Oto pomiary Quartz, których potrzebowa³eœ.}
{271} {} {Niesamowite! Wiêcej danych, ni¿ siê spodziewa³em! Ta rzecz na twojej d³oni po prostu czyni cuda. Mo¿esz przejrzeæ moje mapy w nagrodê. Dziêkujê Ci.}
{272} {} {Mi³o mi pomóc Rangersom, proszê.}
{1272} {} {Proszê, jestem szczêœliwa mog¹c pomóc Rangersom.}
{273} {} {Lepsza by³aby amunicja, ale podnoszenie reputacji te¿ jest dobre.}
{274} {} {Dlaczego potrzebujesz map tej dziury?}
{275} {} {Nie potrzebujemy ich teraz, ale musimy byæ przygotowani na wszystko. Stare ruiny mog¹ ukrywaæ gniazda mutantów lub obozy bandytów. W koñcu Quartz to brama do Kalifornii. Na razie mog¹ zostaæ zapiêczetowane przez pustyniê, ale to tylko kwestia czasu.}