{100} {} {Widzisz operatora radiowego.}
{101} {} {Widzisz osobê o bystrych oczach.}

{200} {} {Czeœæ.}
{201} {} {Do widzenia.}

{210} {} {O co chodzi?}
{211} {} {Do widzenia.}

{220} {} {Opowiedz mi o sobie.}
{221} {} {Oficer Liaison Jane.}
{222} {} {Jak zosta³aœ Rangersem?}
{223} {} {Po prostu siê sta³o.}
{224} {} {Uh, to wiele wyjaœnia.}
{225} {} {Jakieœ inne g³upie pytania?}
{226} {} {Tak.}
{227} {} {Nie.}
{228} {} {}
{229} {} {Zmieñmy temat.}

{230} {} {Co to za miejsce?}
{231} {} {To jest stacja radiowa. Stacja radiowa. Nie myl tego z promieniowaniem... Cholera, wygl¹da na to, ¿e bêdê musia³a to d³ugo wyjaœniaæ. Krótko mówi¹c, u¿ywamy tego sprzêtu do zdalnej komunikacji z naszymi patrolami.}
{232} {} {To zaskakuj¹ce, ¿e ca³a ta technika nadal dzia³a.}
{233} {} {Tak. Dzia³a. I utrzymuje siê „na powierzchni” tylko dziêki relacjom zewnêtrznym. Czêœci zamienne pozyskujemy z karawan handlowych, a energiê z tamy.}
{234} {} {Niewiele pustkowi ma technologiê Starego Swiata.}
{235} {} {Zgadza siê. Technologia to koniecznoœæ, a nie luksus. Wielu nawet boi siê takich miejsc. Ale w naszym przypadku wiedza o tej technice by³a przekazywana z pokolenia na pokolenie i zapisywana na holodyskach. Dla nas to tak¿e w pewnym sensie relikt.}
{236} {} {Gdzie jest ca³a za³oga? Prawie nikogo tu nie ma.}
{237} {} {Mam doœæ gadania przez radio. Co wiêcej, nie zamierzam tutaj tolerowaæ obcych.}
{238} {} {Czy chcia³abyæ gdzieœ siê zrelaksowaæ?}
{239} {} {Na przyk³ad? Nie mam nic przeciwko strzelaniu do kojotów, ale to nie twoja sprawa.}
{240} {} {Wydajesz siê byæ z³a na ludzi.}
{241} {} {Mo¿e tak. Wszêdzie wokó³ s¹ idioci. Kiedy nastêpny kadet stwarza problemy lub nastêpny sier¿ant kwestionuje po cichu rozkazy dowódcy, mimowolnie rozczarowywujê siê ludŸmi.}
{242} {} {Co to za pole z krzy¿ykami w pobli¿u stacji?}
{243} {} {To cmentarz. Pochowani s¹ tam Rangersi i ich bliscy. Mam nadziejê, ¿e nie zamierzasz bezczeœciæ grobów, bo inaczej bêdzie to ostatni b³¹d twojego krótkiego ¿ycia.}
{244} {} {Czy mogê zadaæ kolejne pytanie dotycz¹ce tej... stacji radiowej?}

{250} {} {Potrzebujê kodów radiowych.}
{251} {} {To jest informacja zastrze¿ona, zwykli ludzie nie powinni o niej wiedzieæ.}
{252} {} {Jestem Rangersem.}
{253} {} {Ok, zapomnij.}
{254} {} {All right then, keep your secrets.}
{255} {} {W takim razie przepraszam. Oto kody i szyfry g³ównych czêstotliwoœci komunikacyjnych. Nie pokazuj ich nikomu poza pozosta³ymi Rangersami.}
{256} {} {Dziêki, oficerze.}
{257} {} {Wiem to i bez ciebie.}

{260} {} {Tama jest zniszczona. Dlaczego wci¹¿ tu jesteœ?}
{261} {} {W tym trudnym czasie moja praca jest szczególnie wa¿na. Dowództwo poszukuje nowej siedziby i bez komunikacji zdalnej bêdzie niewidome w swoich poszukiwaniach.}
{262} {} {[Dalej.]}
{263} {} {To i tak nie potrwa d³ugo, poniewa¿ generatory zapasowe maj¹ ograniczone zasoby. Kiedy siê wyczerpi¹ lub siê zepsuj¹, radio stanie siê bezu¿yteczne. Jednak ze szczytu jest dobry widok na dolinê.}
{264} {} {Rozumiem.}

{270} {} {Mówi¹, ¿e to dziêki tobie odkryto szpiega ukrywaj¹cego siê za farmerami? Dobra robota.}
{271} {} {Mi³o by³o pomóc.}
{1271} {} {Mi³o by³o pomóc.}
{272} {} {Drobnostka.}
{273} {} {Wiêc to dziêki tobie Jason wydosta³ siê ze szponów Szakali? Dobra robota. Myœleliœmy, ¿e straciliœmy wszystkich na tym patrolu.}
{274} {} {Mi³o by³o siê przydaæ.}
{1274} {} {Mi³o by³o siê przydaæ.}
{275} {} {Nie ma za co.}

# Zadanie tematyczne
{278} {} {Naprawdê?}
{279} {} {Rzecz w tym, ¿e po³owa wzmacniaczy sygna³u od dawna nie dzia³a. Musz¹ zostaæ naprawione lub wymienione. Wtedy po³¹czenie bêdzie wystarczaj¹co dobre, aby kontrolowaæ terytorium a¿ do Phoenix... Có¿, a przynajmniej do San Brahmin.}
{280} {} {Przysy³a mnie komandor Helford.}
{281} {} {Swietnie. Stacja wymaga naprawy, a Helford wysy³a mi tu kogoœ takiego! Czy masz pojêcie, jak dzia³a stacja radiowa?}
{282} {} {Ogarnê to. Co siê dzieje?}
{283} {} {Teraz nasi ludzie maj¹ du¿o pracy na froncie wschodnim i po³udniowo-wschodnim. Ale komunikacji radiowej brakuje tak¿e niektórych placówkach. Chocia¿ mog³oby byæ inaczej.}
{284} {} {Gdzie jest zepsuty sprzêt?}
{285} {} {ZejdŸ na zaplecze pod anten¹. Obawiam siê, ¿e nie wystarcz¹ puszki i widelce, aby to naprawiæ. Zbieracze mog¹ mieæ przydatne czêœci w Garage City, ale nie lubi¹ Rangersów. Czy mo¿esz nam pomóc w rozwi¹zaniu tego problemu?}
{286} {} {Pójdê zobaczyæ, co to jest...}
{287} {} {Zaczekaj chwilê. Pewnie idziesz do Garage City po czêœci, prawda? Jest jeszcze jedna proœba. Straciliœmy patrol w tej okolicy. Spróbuj dowiedzieæ siê, co siê z nimi sta³o. Nasza komunikacja tam nie dociera, ale jeœli bêdziesz w pobli¿u radia bêd¹ w stanie wykryæ swoje sygna³y. Jeœli mo¿esz to zrobiæ, Rangersi bêd¹ ci wdziêczni.}
{288} {} {Na pewno coœ znajdê.}
{289} {} {Nie mogê nic obiecaæ.}
{290} {} {Nadajnik dzia³a.}
{291} {} {Zród³o echa zniszczone. To by³ przekaŸnik szpiegowski.}
{292} {} {Przypomnij mi, co mam zrobiæ.}
{293} {} {Mimo wszystko jest ci ciê¿ko, prawda? ZnajdŸ Ÿród³o, które „odbija” nasze audycje. Aby to zrobiæ, udaj siê na pustkowia na wschód od naszej bazy. Pamiêtaj, ¿eby monitorowaæ sygna³ radiowy, aby zlokalizowaæ Ÿród³o.}
{294} {} {Swietnie. Zobaczmy, co z tego wysz³o...}
{295} {} {[Dalej.]}
{296} {} {Super! Teraz mo¿emy rozszerzyæ nasz¹ kontrolê nad terytorium... Poczekaj chwilê. S³yszysz to?}
{297} {} {Echo? Czy jest coœ, co powiela Twój sygna³?}
{298} {} {Wygl¹da na... Sygna³, bardzo niski, kieruje siê na wschód. Wczeœniej nie mogliœmy tego wykryæ. To mo¿e byæ nowy b³¹d sprzêtowy, ale... S³uchaj, musimy dok³adnie wiedzieæ, co to jest. Nie nale¿y ignorowaæ tej sprawy.}
{299} {} {[Dalej.]}
{300} {} {IdŸ w stronê sygna³u na wchód i dowiedz siê, co powoduje echo radiowe. Dam ci krótkofalówkê, ¿eby go znaleŸæ.}
{301} {} {Ech, a ju¿ wydawa³o mi siê, ¿e zadanie zosta³o wykonane...}

{302} {} {Co za niespodzianka! Wydawa³o mi siê, ¿e tylko my posiadamy technologiê tak potê¿nych transmisji radiowych. Natychmiast zg³oœ wyniki operacji kapitanowi Helfordowi.}
{303} {} {[Dalej.]}
{304} {} {I masz zadatki na kadeta. Poinformuj dowódcê Helforda o wynikach operacji.}
{305} {} {Tak jest!}