{100} {} {Widzisz Stra¿nika Jasona.}
{101} {} {Widzisz swojego starego przyjaciela z nor Szakali. Wygl¹da na to, ¿e siê obija.}

{200} {} {Wiêc ju¿ siê poznaliœmy. Jak widzisz, z twoj¹ pomoc¹ wci¹¿ ¿yjê i nawet mogê utrzymaæ broñ.}
{201} {} {Wygl¹dasz trochê lepiej od czasu naszego ostatniego spotkania.}
{202} {} {Droga by³a trudna, ale jesteœmy przygotowani na takie trudnoœci. S³uchaj, potrzebujemy ludzi takich jak ty. Do³¹cz do Rangersów! To prawda, sama moja rekomendacja nie wystarczy do akceptacji. Ale powiedzia³em komandorowi Helfordowi o twoim wyczynie. Porozmawiaj z nim.}
{203} {} {Przemyœlê Twoj¹ propozycjê.}
{204} {} {Droga by³a trudna, ale jesteœmy przygotowani na takie trudnoœci. Poniewa¿ jednak widzia³em ciê na liœcie rekrutów, nie muszê Ci przecie¿ o tym mówiæ. Gratulacje z powodu akceptacji, Stra¿niku. U¿yj swojej pozycji, aby przynieœæ korzyœci innym.}
{205} {} {Dziêkujê Rangersie Jason za mi³e powitanie. Ale muszê iœæ.}
{206} {} {Du¿o s³ów, ale ¿adnego porz¹dnego karabinu w nagrodê... Trudno, do zobaczenia.}

{210} {} {Cieszê siê, ¿e wpad³es do nas.}
{211} {} {Do zobaczenia.}
{212} {} {Co myœlisz o sojuszu Rangersów i Szakali?}
{213} {} {Po tym, co przeszed³em, wydaje mi siê to absurdalnym koszmarem. Co kombinuje centrum dowodzenia?! Dobra, ja mam wykonywaæ rozkazy, a nie je omawiaæ.}
{214} {} {Rozumiem.}