{100} {} {Widzisz Rangersa.}
{101} {} {Widzisz Rangersa w pustynnym ubraniu. Pokazuje ci znak powitalny.}
{102} {} {Tak, bêdê go potrzebowaæ.}

# Pierwszy dialog
{200} {} {Hej podró¿niku, zwolnij! W tych stronach rzadko spotyka siê ludzi. Mo¿esz mi powiedzieæ, co tu robisz?}
{1200} {} {Hej podró¿niku, zwolnij! W tych stronach rzadko spotyka siê ludzi. Mo¿esz mi powiedzieæ, co tu robisz?}
{201} {} {Jestem na misji od dowódcy Helforda.}
{202} {} {W sumie nie jestem zaskoczony. Kapitan od dawna mówi³, ¿e brakuje mu ludzi. Lepiej uwa¿aj, to miejsce nie jest bezpieczne.}
{203} {} {Ranger kartograf za¿¹da³ pomiarów.}
{204} {} {Najwy¿szy czas, aby to zrobiæ. Ale teraz jest tu zbyt niebezpiecznie, aby robiæ pomiary dla kartografa.}
{205} {} {Szukam staro¿ytnych artefaktow.}
{206} {} {Poszukiwacz relikwii, co? Droga w poszukiwaniu zysku zaprowadzi³a ciê daleko. Ale to nie jest najlepsze miejsce do ich szukania, zaufaj mi. Wszystko, co cenne, dawno przepad³o, a przeszukiwanie tutejszych ruin sta³o siê niebezpieczne.}
{207} {} {To nie twoja sprawa.}
{208} {} {Ok. Powiedzmy. Pamiêtaj jednak, ¿e te ruiny s¹ zbyt niebezpieczne. Jeœli wpadniesz w k³opoty, nie proœ mnie ani innych Rangersów o pomoc.}
{209} {} {Dlaczego to miejsce jest niebezpieczne?}
{210} {} {Promieniowanie t³a ostatnio wzros³o. Miejscowi oszaleli i teraz atakuj¹ ka¿dego, kogo spotkaj¹. B¹dŸ czujny. Ostrzeg³em Ciê, ale rób, co chcesz.}
{211} {} {Dziêki za ostrze¿enie.}
{212} {} {Po prostu próbujesz mnie przestraszyæ. Lepiej odejdŸ.}
{213} {} {Przemyœlê to. Szczêœcia.}

# Powtarzajacy siê dialog
{220} {} {Tak?}
{221} {} {Do widzenia.}
{222} {} {Cofnijmy siê trochê.}
{223} {} {Wygl¹da na to, ¿e to by³ ostatni. Niech Bóg pozwoli odpocz¹æ ich duszom.}

{230} {} {Czy zostali tu jacyœ mieszkañcy?}
{231} {} {Jestem tutaj na proœbê komandora Helforda. Gdzie jest obóz dla uchodzców?}
{232} {} {Miejscowi nie s¹ ju¿ ludŸmi. S¹ szaleni, nie rozumiej¹ mowy i atakuj¹ ka¿dego, kogo spotkaj¹. Ich obóz znajduje siê na parkingu karawan naprzeciw stacji benzynowej. IdŸ ulic¹, a nastêpnie skrêæ w lewo.}
{233} {} {Kim oni s¹?}
{234} {} {To zwykli uchodŸcy ze wschodu. Przyjechali tutaj z nadziej¹ na rozpoczêcie nowego ¿ycia, ale znaleŸli tylko cierpienie. Jeœli ich spotkasz, lepiej od razu ich zastrzeliæ, ¿eby nie cierpieli i nie stwarzali problemów innym.}
{235} {} {Dlaczego oszaleli?}
{236} {} {Nie wiem, ale myœlê, ¿e to z powodu promieniowania.}
{237} {} {Miejscowi nie s¹ ju¿ ludŸmi. S¹ szaleni, nie rozumiej¹ mowy i atakuj¹ ka¿dego, kogo spotkaj¹. Ich obóz znajduje siê na parkingu karawan.}

{240} {} {Dlaczego tutaj jest tak radioaktywnie?}
{241} {} {Te¿ chcia³bym wiedzieæ. Po Wielkiej Wojnie by³o tu wysokie promieniowanie t³a z powodu wiatrów z Kalifornii. Ale z biegiem czasu poziom promieniowania wróci³ do normy. Z pewnoœci¹ miejscowi siê do tego przyczynili. Byæ mo¿e znaleŸli coœ, czego nie powinni byli znaleŸæ.}

{250} {} {Kim jesteœ?}
{251} {} {Jestem Rangersem. Moim zadaniem jest postawienie ostrze¿eñ przed promieniowaniem i, jeœli to mo¿liwe, zastrzelenie wszystkich Szaleñców. Potem wrócê do s³u¿by na wschodzie.}
{252} {} {Jesteœ tutaj sam?}
{253} {} {Tak. Wielu Rangersów zosta³o wys³anych na wschód, ale kilka patroli wys³ano w tym kierunku. Jednak nie zawsze by³o tu tak t³oczno.}
{254} {} {Potrzebujê eskorty. Pójdziesz ze mn¹?}
{255} {} {To zbyt niebezpieczne. Nasza dwójka przyci¹ga wiêcej uwagi, a moje umiejêtnoœci s¹ bardziej przydatne na pustkowiach ni¿ w mieœcie.}
{256} {} {Nie wyjdê z tego ¿ywy bez twojej ochrony.}
{257} {} {Ja te¿ jestem Rangersem. Razem ³atwiej bêdzie nam pozbyæ siê tych Szaleñców.}
{258} {} {Nie broniê ludzi takich jak ty.}
{259} {} {Brzmisz, jakbyœ postrzega³ mnie jako zbieg³ego przestêpcê.}
{260} {} {Po prostu zostaw te ruiny, jeœli nie masz si³y do walki.}
{261} {} {Nie, dopóki nie otrzymam od ciebie wszystkich odpowiedzi, których potrzebujê.}
{262} {} {Dok³adnie tak zrobiê. Bywaj.}
{263} {} {(z niedowierzaniem) Ok. Ale nie zapominaj o promieniowaniu.}
{264} {} {Smia³o!}
{265} {} {ChodŸmy.}