{100} {} {Widzisz z³ot¹ raczkê.}
{101} {} {Widzisz pospolitego mieszkañca pustkowi.}

# Pierwszy dialog
{200} {} {(przed tob¹ stoi m³ody mê¿czyzna w brudnych ubraniach; patrzy na ciebie ze znu¿eniem) Czego chcesz?}
{201} {} {Czy nie jesteœ zwiadowc¹?}
{202} {} {Oczywiœcie, ¿e nie. Sram na tych Rangersów. Ale zapewniaj¹ ochronê naszej spo³ecznoœci. Pracujê jako z³ota r¹czka.}
{203} {} {Rozumiem. Có¿, nie bêdê ciê rozpraszaæ.}

# Powtarzajacy siê dialog
{210} {} {Znowu?}
{211} {} {Do widzenia.}
{212} {} {Czy mo¿esz odmówiæ œwiadczenia us³ug?}
{213} {} {Ma³o prawdopodobne. Jeœli Stra¿nicy siê zdenerwuj¹, odbior¹ nam wszystkie nasze zapasy i przestan¹ chroniæ nas przed bandytami i mutantami. Dlatego musimy spe³niaæ wszystkie ich zachcianki, a lista jest doœæ d³uga.}
{214} {} {Opowiedz mi o swojej spo³ecznoœci.}
{215} {} {Mieszkamy w pobli¿u akweduktu na wybrze¿u Kolorado. Zyjemy na rybach i drobnej zwierzynie. Nie wiem, co jeszcze mam ci powiedzieæ.}
{216} {} {Co myœlisz o Rangersach?}
{217} {} {W razie potrzeby bêd¹ jedyn¹ nadziej¹ na zbawienie. Ale przez resztê czasu paso¿ytuj¹ tylko na naszej spo³ecznoœci, zabieraj¹c nasz po³ów i zmuszaj¹c nas do pracy na swoj¹ korzyœæ.}
{218} {} {Czy znasz sposób na zinfiltrowanie ich bazy?}
{219} {} {Nie. Nie maj¹ tam wycieczek dla turystów. Musisz wyœwiadczyæ Rangersom dobr¹ przys³ugê lub mieæ jakiœ naprawdê dobry powód.}