{100} {} {Widzisz Stra¿nika Starka.}
{101} {} {Widzisz Stra¿nika w œrednim wieku.}
{102} {} {Dziêki doktorze. Myœla³em, ¿e pozostanê kulawy na ca³e ¿ycie.}

# Pierwszy dialog
{200} {} {(Znudzony Stra¿nik o¿ywa, gdy w jadalni pojawia siê nieznajomy; zaprasza ciê do sto³u) Czeœæ nieznajomy! Nie widzia³em ciê tu wczeœniej. Sk¹d pochodzisz?}
{1200} {} {(Znudzony Stra¿nik o¿ywa, gdy w jadalni pojawia siê nieznajoma; zaprasza ciê do sto³u) Czeœæ, nieznajoma! Nie widzia³em ciê tu wczeœniej. Sk¹d pochodzisz?}
{201} {} {Z wioski na pó³noc. Nazywamy j¹ Villa.}
{202} {} {Có¿, patrolowa³em w innych kierunkach. Ale s³ysza³em coœ o Villi. Czy chodzi o to miejsce, gdzie uprawia siê plony na œrodku ja³owej pustyni? Niesamowite. Myœla³em, ¿e to zwyk³e bzdury, które mo¿na us³yszeæ w jadalni.}
{203} {} {A ty...}
{204} {} {Nie twoja sprawa.}
{205} {} {Hej, nie wydaje mi siê, ¿ebym by³ dla ciebie niegrzeczny. Ale rozumiem twoje podejœcie. Jeœli nie chcesz, nie mów mi.}
{206} {} {Kim jesteœ?}
{207} {} {Jestem Stark, Ranger, jeœli to coœ dla ciebie znaczy.}
{208} {} {Czeœæ Stark. Masz chwilê na rozmowê?}
{209} {} {Czeœæ Stark. I pa.}

# Powtarzajacy siê dialog
{210} {} {S³ucham.}
{211} {} {Do widzenia.}
{212} {} {Kolejne pytanie.}

#Zapytania
{220} {} {Dlaczego mieszkasz tu¿ przy tamie?}
{221} {} {Dlaczego? To doskona³a fortyfikacja przeciwko wrogom i z³ej pogodzie. Nikt nawet nie pomyœla³by o wtargniêciu tutaj lub próbie szpiegowania.}
{222} {} {Czy to niebezpieczne miejsce?}
{223} {} {Ta tama pozostanie tutaj jeszcze przez kilka wieków. Tak przynajmniej twierdzi Stary Rufus. A co mog³oby siê tu staæ? To tylko kawa³ek betonu poœrodku gór.}
{224} {} {Kim jest ten Stary Rufus?}
{225} {} {Opiekunem tamy. Na tym stanowisku jest od kilkunastu lat. Chocia¿ wielu uwa¿a, ¿e jest tu na pró¿no. Wygl¹da na to, ¿e jest teraz w elektrowni.}
{226} {} {Czy to tutaj mieszkaj¹ wszyscy Rangersi z Arizony?}
{227} {} {Oczywiœcie, ¿e nie. To tylko baraki do tymczasowego pobytu. Mo¿esz tu dostaæ ³ó¿ko tylko na okreœlony czas lub z jakiegoœ powodu. Przez resztê czasu przebywamy na s³oñcu, jak przysta³o na prawdziwego Rangersa.}

{230} {} {Zastanawiam siê tylko, jak zostaæ kadetem?}
{231} {} {Có¿, s¹ ró¿ne sposoby. Zwykle potrzebujemy rekomendacji od kogoœ, z kim mamy dobre relacje - kupców, przywódców zaprzyjaŸnionych osad, innych Rangersów. A jeœli nie tak, to musisz pokazaæ siê w akcji.}
{232} {} {Jak d³ugo trwa szkolenie?}
{233} {} {Co najmniej piêæ lat, w zale¿noœci od kadeta. Decyzja o awansie musi wynikaæ z rzeczywistych zas³ug.}
{234} {} {Czy ty te¿ jesteœ kadetem?}
{235} {} {Ja? Nie? Nie. Ale muszê pomóc rosn¹æ zieleni. Mamy tu tak - nie mo¿esz byæ przydatny w terenie, pomagaj w bazie.}
{236} {} {Co powstrzymuje Ciê przed uczestnictwem w operacjach?}
{237} {} {Wiêc nie mo¿esz siê st¹d ruszyæ, prawda?}
{238} {} {(podnosi zabanda¿owan¹ nogê) Przeklête wilki. Zaatakowa³y mnie podczas patrolowania rzeki Kolorado. Opuœci³em gardê - a oto moja nagroda.}
{239} {} {Mo¿e mogê j¹ wyleczyæ?}
{240} {} {Jeœli zap³acisz, uzdrowie j¹.}
{241} {} {Och, to jest zdecydowanie problem. Mo¿e porozmawiajmy o czymœ bardziej pozytywnym?}
{242} {} {Powa¿nie? By³bym wdziêczny. Ale czy naprawdê wiesz, co robiæ?}
{243} {} {Poka¿ mi...}
{244} {} {U¿yj umiejêtnoœci medycznych lub leków, aby wyleczyæ obra¿enia.}

{250} {} {Prawdopodobnie taki doœwiadczony Stra¿nik zna wiele interesuj¹cych historii.}
{251} {} {Nigdy nie przegapiam okazji, by zapytaæ podró¿nych, co widzieli. To prawda, zazwyczaj wielu z nich k³amie w swoich opowieœciach.}

{270} {} {Wspomnia³eœ o wilkach. Jakie inne stworzenia wystêpuj¹ wzd³u¿ Kolorado?}
{271} {} {Och, to nie jest tylko pustynia, jest tu pe³no ró¿nych zwierz¹t.}
{272} {} {Na przyk³ad?}
{273} {} {Och, tak, dobrze.}
{274} {} {W zaroœlach mo¿na znaleŸæ rogate jaszczurki wielkoœci psa. Na pierwszy rzut oka nie jest tak silnym przeciwnikiem, ale jej kolce na ca³ym ciele uniemo¿liwiaj¹ zaatakowanie jej wrêcz. To tak¿e cholernie inteligentne stworzenie ze œwietnym kamuflarzem.}
{275} {} {Jakie to interesuj¹ce! Powiesz mi wiêcej?}
{276} {} {S³ysza³em podobne historie, nic specjalnego.}
{277} {} {Chcesz coœ bardziej przera¿aj¹cego? Jaskinie zamieszkuj¹ nietoperze buldo¿ki - prawdziwe demony. Czekaj¹ na ofiarê przy wejœciu i szybko wylatuj¹ na ni¹, nie pozwalaj¹c jej dojœæ do siebie. Jedno takie stworzenie mo¿e unieœæ cz³owieka w powietrze i wci¹gn¹æ go z powrotem do jaskini. Taka osoba nie ma szans na powrót.}
{278} {} {Powa¿nie? Moje ¿y³y ju¿ dr¿¹.}
{279} {} {Trudno w to uwierzyæ. I to s¹ wszyscy lokalni mieszkañcy?}
{280} {} {S¹ te¿ stonogi o d³ugosci do dwóch jardów miêdzy kamieniami Kolorado. Od ich ugryzienia œmieræ nastêpuje w ci¹gu jednej sekundy. Ich skorupy nie da siê przebiæ nawet no¿em, a szczêki maj¹ tak mocne, ¿e mog¹ przeci¹æ cz³owieka na pó³.}
{281} {} {Och, mamo! Nie mów mi, ¿e jest coœ gorszego!}
{282} {} {Ktoœ ma zbyt bujn¹ wyobrañniê. Nie mo¿esz tego zrozumieæ?}
{283} {} {Kr¹¿¹ równie¿ pog³oski o nieszczêœliwych, hipnotycznych motylach i pancernikach u¿ywaj¹cych starych maszyn jako muszli. Ale ja sam spotka³em tylko wilki, jaszczurki i gryzonie z dziwnymi prêgami.}
{284} {} {Dziêki za historie. To by³o bardzo... pouczaj¹ce.}
{285} {} {Zachowaj czujnoœæ.}
{286} {} {Porozmawiajmy wiêcej.}
{287} {} {Do zobaczenia, muszê ju¿ iœæ.}
{288} {} {Przez twoj¹ paplaninê boli mnie g³owa. Czy zawsze próbujesz zastraszyæ wszystkich nieznajomych?}
{289} {} {Có¿... S³ysza³em to wszystko od innych ludzi. Ale nie w¹tp, ¿e wokó³ jest wiele wrogich stworzeñ. Zachowaj czujnoœæ.}
{290} {} {Opowiedz mi o stworzeniach z rzeki Kolorado.}

# Impreza promocyjna
{310} {} {Hej, to nasza nowa * gwiazda * we w³asnej osobie!}
{311} {} {Tak, zdobycie odznaki nie by³o ³atwe. Ale sk¹d wiesz?}
{312} {} {Wieœci szybko rozchodz¹ siê po bazie. Ale wiesz co? Nie licz na prezent ode mnie. Reszta spêdza lata na zdobywaniu doœwiadczenia i zas³ug dla gwiazdy, a ty po prostu przyje¿dzasz i j¹ bierzesz!}
{313} {} {Wygl¹da na to, ¿e nie lubisz mnie od pierwszego spotkania. Ale nie obchodzi mnie to.}
{314} {} {Mam nadziejê, ¿e kiedyœ zmienisz swoje nastawienie.}
{315} {} {No có¿.}
{316} {} {Nie wydajesz siê byæ zajêty? Masz minutê?}
{317} {} {Chyba pójdê ju¿.}
{318} {} {Mi³ej zabawy. Dziœ jesteœ bohaterem.}
{1318} {} {Mi³ej zabawy. Dziœ jesteœ gwiazd¹.}

{320} {} {Zartujesz sobie ze mnie?}
{321} {} {Jak zgad³eœ? Mo¿e dlatego, ¿e nie odpalam fajerwerków na twoj¹ czeœæ? Trzeba przez wiele lat ciê¿ko pracowaæ na t¹ gwiazdê, a ty po prostu przychodzisz i j¹ bierzesz! Nie oczekuj ode mnie prezentu.}
{322} {} {Wieœci szybko rozchodz¹ siê po bazie. Cieszê siê z twojego powodu. Niewielu udaje siê zdobyæ odznakê na samym pocz¹tku s³u¿by. Raczej nikomu siê to nie udaje. Pozwól, ¿e zaopatrzê ciê z moich osobistych zapasów z okazji takiego œwiêta. Dobra robota!}
{323} {} {Dziêki, impreza na szczycie tamy jest tym, o czym zawsze marzy³em.}
{324} {} {Ta odznaka to nie zabawka. Ale myœlê, ¿e wezmê trochê owoców.}

{330} {} {Hej, czy w twoich opowieœciach jest choæ ziarno prawdy?}
{331} {} {Có¿... jest jedna historia, która na pewno nie jest fikcj¹. Opowiedzieæ?}
{332} {} {S³ucham.}
{333} {} {Innym razem.}
{334} {} {Prawdziwie gigantyczny radskorpion ¿yje na pustyni, wiêkszy ni¿ jakikolwiek znany radskorpion. Mówi¹, ¿e ten stwór po¿ar³ ju¿ kilka grup podró¿ników. Jeœli go znajdziesz i zabijesz, wyœwiadczysz œwiatu wielk¹ przys³ugê.}
{335} {} {Wiesz, nie chcê tego s³uchaæ.}
{336} {} {Czy nie wszystkie radskorpiony s¹ gigantami?}
{337} {} {Tak, ale ten chyba chodzi³ na si³owniê dla takich mutantów jak on!}
{338} {} {Dlaczego Stra¿nicy nie wyœledz¹ go i nie rzuc¹ siê na niego w grupie?}
{339} {} {To stworzenie czai siê na ja³owej pustyni, gdzie nawet doœwiadczony Ranger z trudem wytrzyma kilka dni. Wyczo³guje siê z pustyni na polowanie, a potem wraca. Aby spotkaæ takiego potwora, trzeba w pewnym sensie staæ siê jego ofiar¹.}
{340} {} {Ale dlaczego uwa¿asz, ¿e to prawda, a nie fikcja?}
{341} {} {Poniewa¿ widzia³em to na w³asne oczy. I nie jestem sam. Kiedyœ mieliœmy nieszczêœcie, ¿e polowaliœmy na pustyni miêdzy Quartz i San Brahmin. Dosz³o tam do powa¿nej masakry, ledwo stamt¹d uciekliœmy i od tego czasu zdecydowaliœmy, ¿e lepiej omijaæ tego skorpiona.}
{342} {} {Rozumiem, spróbujê go wytropiæ i zabiæ.}
{343} {} {Powa¿nie? Godna pochwa³y gorliwoœæ. Ale jeœli zostaniesz obiadem tego potwora, obwiniaj siebie.}
{344} {} {Bez obaw. Przyniosê ci pami¹tke.}
{345} {} {Och, wygl¹da na to, ¿e powinienem omijaæ tego potwora. Dziêki za ostrze¿enie.}
{346} {} {Dok³adnie.}
{347} {} {Powodzenia.}

{350} {} {Chcê zadaæ Ci kolejne pytanie dotycz¹ce tego legendarnego Radskorpiona.}
{351} {} {Ach, po tej historii nie chcesz wyjœæ na pustkowiê, prawda?}
{352} {} {Lepiej zmieñmy temat.}
{353} {} {Zabi³em tego radskorpiona.}
{1353} {} {Zabi³am tego radskorpiona.}
{354} {} {SERIO?! Ale oczywiœcie nie masz ¿adnego dowodu, prawda?}
{355} {} {Zw³oki mo¿na ³atwo znaleŸæ na œrodku pustyni. Wyœlijcie patrol, potwierdz¹.}
{356} {} {Hmm, to mo¿na za³atwiæ. Jeœli to prawda, dziêkujê w imieniu wszyskich Rangersów. Wyœwiadczy³eœ wielk¹ przys³ugê ca³emu Pustkowiu.}
{1356} {} {Hmm, to mo¿na za³atwiæ. Jeœli to prawda, dziêkujê w imieniu wszystkich Rangersów. Wyœwiadczy³aœ wielk¹ przys³ugê ca³emu Pustkowiu.}
{357} {} {Uwa¿am, ¿e za te us³ugi nale¿y mi zap³aciæ.}
{358} {} {Myœla³em, ¿e takie twierdzenia powinny byæ poparte dowodami. Czy nie jest tak?}
{359} {} {Ugh, jest ju¿ za póŸno na szukanie dowodow. Myœlê, ¿e wystarczy o tym wspomnieæ w kronikach.}
{360} {} {To mi wystarczy. Szczêœcia.}
{361} {} {Mogê ci tylko pokazaæ ten trzon w³óczni, który wystawa³ ze skorupy.}
{362} {} {Cholera! Pamiêtam go... Naprawdê uda³o ci siê pokonaæ tego potwora? Ale jak?}
{363} {} {Choæ by³ du¿y, to nie by³ wcale taki szybki.}
{364} {} {Nie ma godnej nagrody dla takich jak ty. Proszê, weŸ ode mnie kilka kul i ten stary rewolwer na dowód wdziêcznoœci. Nie bój siê, mam czym siê broniæ przed mutantami na pustyni. Dziêki raz jeszcze.}
{365} {} {Proszê.}