{100} {} {Widzisz bandytê.}
{101} {} {Widzisz niebezpiecznego przestêpcê trzymaj¹cego strzelbê. I zdecydowanie jest gotowy, aby kogoœ zastrzeliæ.}

{110} {} {SiedŸ cicho i siê nie ruszaj!}
{111} {} {Gdzie jest ta urocza suka?}
{112} {} {Jeœli dzieciak nie wróci, to na pewno kogoœ zastrzelê.}
{113} {} {Hej stary, chcesz siê napiæ?}
{114} {} {Gdzie trzymacie kapsle?}
{115} {} {Cholera, ci biedacy nie maj¹ nic do jedzenia!}
{116} {} {Suki, za kogo mnie macie?!}
{117} {} {Odetnê jej palce, jeœli twój kretyn nie wróci z jedzeniem.}
{118} {} {Palce tañcz¹ mi na haku.}
{119} {} {}

#Dialog
{200} {} {Stop! Rêce do góry, abym je móg³ zobaczyæ!}
{201} {} {Pora umieraæ.}
{202} {} {Jesteœ otoczony, poddaj siê, jeœli chcesz ¿yæ.}
{203} {} {(zastanawia siê przez chwilê) Pieprz siê!}
{204} {} {Ehh...}
{205} {} {(zastanawia siê przez chwilê, a potem odchodzi)}
{206} {} {Dalej, wynoœ siê st¹d.}
{207} {} {Twoi zak³adnicy uciekli. Poddaj siê lub zgiñ.}
{208} {} {Co... Nie zapomnij, kto tu ma broñ. A teraz opuszczê doline. Zamknij siê i zostañ tutaj. Jasne?}
{209} {} {Dalej, wynoœ siê st¹d.}