{100} {} {Widzisz dziecko.}
{101} {} {Widzisz dziecko Miltonów.}

#Dialog
{110} {} {Czeœæ. Czy przyszed³eœ, aby uwolniæ nas od gryzoni?}
{111} {} {Uratuj moich rodziców!}
{112} {} {Rangersi s¹ naprawdê fajni. Kiedy dorosnê, te¿ nim zostanê.}
{113} {} {To wszystko przez ciebie! IdŸ st¹d!}
{114} {} {To wszystko przez ciebie! IdŸ st¹d!}
{115} {} {Trzymaj siê z dala ode mnie!}
{116} {} {Dziêki za uratowanie nas przed tym okropnym potworem.}

{200} {} {Czekaj! Tam... tam... jest bandyta!}
{201} {} {Gdzie jest bandyta?}
{202} {} {Uspokój siê, nie rozumiem, co mówisz.}
{203} {} {Bandyta w naszej chacie! Ma broñ, zwi¹za³ mamê i tatê! Uratuj ich!}
{204} {} {Zostañ tutaj. Zobaczê, co da siê zrobiæ.}
{205} {} {Przesun siê, ma³a rybko, to zadanie dla profesjonalistów.}
{206} {} {Nie, ma³y, to by³ du¿y kretoszczur...}