{100} {} {Widzisz pani¹ Milton.}
{101} {} {Widzisz matkê rodziny Milton.}

#Dialog
{110} {} {Uwolnij nas od tych cholernych kretoszczurów!}
{111} {} {Zatrzymaj go, zanim kogoœ zastrzeli!}
{112} {} {Dziêkujemy za uratowanie nas. Gdyby nie ty, prawdopodobnie by nas zabi³.}
{113} {} {Dziêki za pomoc, teraz zostaw mnie, muszê pochowaæ mê¿a.}
{114} {} {Jaki z was po¿ytek, przeklêci Stra¿nicy?! Nie chcê was widzieæ!}
{115} {} {Trzymaj siê z dala ode mnie!}
{116} {} {Dziêkujê za pomoc. Mam nadziejê, ¿e duch Nat-Aani nie zemœci siê na nas.}