{100} {} {Widzisz pana Miltona.}
{101} {} {Widzisz ojca rodziny Milton.}

#Dialog
{110} {} {Nie mamy czym zap³aciæ, ale nie zostawisz nas samych z tymi kretoszczurami, prawda?}
{111} {} {Powstrzymajcie go, pomocy!}
{112} {} {Dziêkujemy za uratowanie nas. Teraz myœlê o was lepiej.}
{113} {} {Dziêki za pomoc, ale mojej ¿ony to nie zwróci.}
{114} {} {Jaki z was po¿ytek, przeklêci Stra¿nicy?! Wypad!}
{115} {} {Trzymaj siê ode mnie z dala!}
{116} {} {Czy Nat-Aani nie ¿yje? Uff, co za ulga!}