{200} {} {WprowadŸ polecenie.}
{201} {} {Koniec sesji.}
{202} {} {Wstecz.}

{210} {} {Sprawdzanie statusu stacji.}
{211} {} {Jednostka 1 - Aktywna. Jednostka hydrauliczna 2 - Aktywna. Jednostka hydrauliczna 3 - Zatrzymana. Sluzy opuszczone: 1,2,3,5. Sluzy podniesione: 4.}
{212} {} {Opuœæ œluzê 4. Bêdzie fajnie, gdy woda zaleje nadbudowê tamy.}
{213} {} {Uwaga! Wybrany tryb spowoduje ca³kowite zablokowanie tamy. Zmieni to re¿im hydrologiczny zbiornika. Czy potwierdzasz polecenie?}
{214} {} {Potwierdzam polecenie.}
{215} {} {Sluza 4 opuszczona. Uwaga! Wszystkie œluzy s¹ w dolnym po³o¿eniu.}
{216} {} {Czas st¹d wyjœæ...}
{217} {} {Co? Nie, nie, nie ma potrzeby opuszczania œluz! Anuluj polecenie.}