{100} {} {Widzisz komputer Rangersów.}
{101} {} {Widzisz komputer z dostêpem do wspólnego serwera.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Po³¹cz z serwerem.}
{204} {} {Dostêp do serwera centralnego.}
{205} {} {Swietnie.}

{210} {} {Pliki Rangersów.}
{211} {} {Wybierz katalog.}

{212} {} {Szakale.}
{213} {} {Szakale to plemiê dzikich kanibali mieszkaj¹cych na pustyni Mojave. Niewiele wiadomo o ich historii i porz¹dku wewnêtrznym, poniewa¿ plemiê zachowuje siê wyj¹tkowo wrogo wobec obcych.}
{214} {} {[Dalej.]}
{215} {} {Jest wiêcej ni¿ tuzin klanów, ka¿dy ma w³asne terytorium i w³asne zasady. Wszyscy praktykuj¹ kanibalizm.}
{216} {} {Aktualne zagro¿enie.}
{217} {} {Najwiêkszy klan Szakali wymiera, reszta stanowi pasywne lub opóŸnione zagro¿enie.}
{218} {} {Miêdzy Stra¿nikami i Szakalami zosta³ zawarty traktat pokojowy. Wszystkim Rangersom polecono unikaæ konfliktów z tym plemieniem, chyba ¿e jest to absolutnie konieczne.}
{219} {} {Szakale s¹ jednym z g³ównych zagro¿eñ dla podró¿ników miêdzy pó³noc¹ a po³udniem. S¹ zrêcznymi i przebieg³ymi ³apaczami ludzi, mog¹ byæ niebezpieczni nawet dla wyszkolonego Rangersa. Rada Starszych zadecydowa³a, ¿e plemiê powinno zostaæ zniszczone.}

{230} {} {Villa.}
{231} {} {Zamkniêta spo³ecznoœæ wiejska utrzymuj¹ca siê z rolnictwa na w³asne potrzeby. Stara siê unikaæ kontaktu z nieznajomymi i zachowuje neutralnoœæ w procesach zewnêtrznych.}
{232} {} {Aktualne zagro¿enie.}
{233} {} {Mieszkañcy Villi przeszli na stronê wroga, ale sami nie s¹ dla nas zagro¿eniem. Nale¿y unikaæ konfliktu z t¹ osad¹, ale nale¿y tak¿e do³o¿yæ starañ, aby zerwa³a wszelkie stosunki z Bractwem Stali.}
{234} {} {Miêdzy ch³opami Villi a Rangersami zosta³a podpisana umowa o wzajemnej pomocy.}
{235} {} {Mieszkañcy Villi maj¹ wielki potencja³ dla Stra¿ników, ale stanowczo odmawiaj¹ zawarcia sojuszu. Powinno siê d¹¿yæ do sojuszu z t¹ osad¹.}
{236} {} {Sytuacja w Villi.}
{237} {} {Wieœniacy z Villi odmówili wspó³pracy z nami, ale sami nie stanowi¹ zagro¿enia. Nale¿y unikaæ konfliktu z t¹ osad¹, ale nale¿y tak¿e do³o¿yæ starañ, aby zerwa³a przyjazne stosunki z naszymi wrogami.}

{250} {} {Czerwone zagro¿enie.}
{251} {} {Wyznawcy ognia to sekta czcz¹ca energiê j¹drow¹ i technologie Starego Swiata.}
{252} {} {Aktualne zagro¿enie.}
{253} {} {Sekta jest w stanie upadku i przeœladowañ. G³ówna baza wyznawców zosta³a zniszczona, prawdopodobnie przez podziemn¹ eksplozjê nuklearn¹. Szczegó³y zdarzenia nie s¹ znane. W tej chwili tylko pojedyñcze klany i oddzia³y stanowi¹ zagro¿enie, które mog¹ paso¿ytowaæ na wczeœniej przyjaznych osadach lub zaanga¿owaæ siê w otwarty bandytyzm.}
{254} {} {Sekta szybko rozszerza swoje wp³ywy w ca³ym regionie, w tym w po³udniowej Arizonie i na Pustkowiach Sonory. Rada Starszych nada³a priorytet ich zagro¿eniu.}
{255} {} {Prowadzenie operacji przeciwko czerwonemu zagro¿eniu.}
{256} {} {Sabota¿ w Flagpool (zawieszony), wsparcie dla walki w San Brahmin, wsparcie dla walki zbieg³ych niewolników w Tu-San.}
{257} {} {Sabota¿ w Flagpool.}
{258} {} {Kolonia jest mocno zaanga¿owana w niewolnicz¹ pracê i jest sponsorowana przez Koœció³ Swiêtego Ognia. Wszystkie operacje sabota¿owe w Flagpool s¹ tymczasowo zawieszone.}
{259} {} {Wspieranie walki w San Brahmin.}
{260} {} {Czcz¹ca ogieñ sekta aktywnie sponsoruje rewolucyjne nastroje w mieœcie San Brahmin w celu rozszerzenia swego imperium. Jesteœmy zmuszeni interweniowaæ w przebiegu wydarzeñ. Do San Brahmin zostali wys³ani konsultanci, aby pomóc lokalnym w³adzom walczyæ z imperium.}
{261} {} {Szpiegostwo w Phoenix.}
{262} {} {Kilku Rangersów prowadzi zwiad w Phoenix. Ich priorytetem jest teraz nawi¹zanie kontaktu z tajemnicz¹ grup¹ partyzantów walcz¹cych z kultem Ognia.}
{263} {} {Wspieranie zbieg³ych niewolników w Tu-San.}
{264} {} {Dzia³alnoœæ wyznawców techniki Tu-San stanowi szczególne zagro¿enie dla dobrobytu innych osad. Czciciele ognia Phoenix aktywnie wspó³pracuj¹ z nimi w celu uzyskania ró¿nych towarów i us³ug. Ze wzglêdu na oddalenie terenu trudno zapanowaæ nad sytuacj¹, dlatego wys³aliœmy szpiegów do pomocy zbieg³ym niewolnikom, którzy prowadz¹ tam dzia³ania sabota¿owe. }

{290} {} {Zagro¿enie z po³udnia.}
{291} {} {Zwiadowcy donosz¹ o zniszczeniu g³ównego fortu Bractwa Stali na po³udniu. Ten dzieñ przejdzie do historii Arizony jako dzieñ wolnoœci i niepodleg³oœci!}
{292} {} {Bractwo Stali to zamkniêta, zmilitaryzowana organizacja o imperialnych ambicjach. Praktykuje niewolnictwo, zmusza osadników do wspó³pracy wbrew ich woli, pochwala najazdy wojskowe i inne przestêpstwa. W tej chwili marionetkowo kontroluje znaczn¹ czêœæ osad w po³udniowej Arizonie, w tym miasto Phoenix. Naszym obowi¹zkiem jest zapobiegniêcie dalszemu rozprzestrzenieniu siê tej organizacji.}
{293} {} {Zwiadowcy donosz¹ o ma³o znanej tajemniczej organizacji na po³udniu. Ocena nie jest obecnie mo¿liwa z powodu braku ludzi i œrodków.}