{110} {} {Doskona³y plan... na samobójstwo.}
{111} {} {Nie mo¿na tego zrobiæ podczas walki.}
{112} {} {Stra¿nicy na posterunku zabraniaj¹ ci wejœæ do œrodka.}
{113} {} {Stra¿nicy pozwolili ci wejœæ do tamy, ale nie twoim kolegom z dru¿yny.}
{114} {} {[Sneak 120] Wszystkie twoje rozproszenia s¹ daremne.}
{115} {} {Stra¿nicy na posterunku nie pozwalaj¹ ci wejœæ w zbroi wspomaganej.}

{120} {} {Nie mo¿esz tego zrobiæ niezauwa¿enie. Bêdziesz musia³ negocjowaæ ze Stra¿nikami.}
{121} {} {To bezcelowe.}
{122} {} {Te drzwi nie s¹ niebezpieczne.}
{123} {} {Solidne metalowe drzwi. Pozostaje tylko chwaliæ mistrza, który je stworzy³.}
{124} {} {Nie wymaga naprawy.}
{125} {} {Nie potrzebuje naprawy. Tego samego nie mo¿na powiedzieæ o tamie za drzwiami.}