{110} {} {Awaria sprzêtu.}
{111} {} {Uda³o ci siê wy³¹czyæ nadajnik radiowy. Rangersi zostali bez kontaktu radiowego.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Nadajnik radiowy nie odpowiada.}

{210} {} {Kopiuj czêstotliwoœci i szyfry Rangersów. W ten sposób mo¿esz pods³uchiwaæ ich rozmowy radiowe.}
{211} {} {Czêstotliwoœci radiowe skopiowane.}