{110} {} {Widzisz wci¹gnik trzymaj¹cy wrota zapory stalowymi linami.}
{111} {} {Wci¹garka nie dzia³a. Trudno to naprawiæ.}
{112} {} {Ani rysy na mechanizmie.}
{113} {} {Mechanizm podnosz¹cy zosta³ rozerwany, a liny, teraz swobodnie wisz¹ce, œwiszcz¹ sobie w ciemnoœci. Po chwili na dole szybu s³ychaæ g³oœny trzask opadaj¹cej zapory.}
{114} {} {Wygl¹da na to, ¿e Rangersów czeka... niewielka powódŸ.}