{100} {} {Widzisz oficera Bell.}
{101} {} {Widzisz ¿o³nierza wygl¹daj¹cego na bardzo wychudzonego.}
{102} {} {Ten pacjent nie jest kontuzjowany. Dolega mu powa¿ny uraz psychiczny.}
{103} {} {To Ci trochê oczyœci g³owê, ¿o³nierzu...}
{104} {} {Przychodz¹ do mnie we œnie... Nie pozwól mi spaæ!}
{105} {} {Dziêki, czujê siê teraz du¿o lepiej. Wszystko wydaje mi siê tylko zwyk³ym koszmarem.}
{106} {} {Bell odmawia przyjêcia tego.}

# Plywajacy dialog (nie usuwaj problemów!)
{110} {} {}
{111} {} {Doktorze! Doktorze! Nie pozwól mi spaæ!}
{112} {} {Uspokój siê, Bell. Wszystko w porz¹dku. Czy znowu masz koszmary?}
{113} {} {Przychodz¹ do mnie w moich snach... Te oczy patrz¹ prosto w moj¹ duszê...}
{114} {} {Kto?}
{115} {} {Doktorze! Zabior¹ mnie do piek³a!}
{116} {} {Uspokój siê, Bell, staruszku. Nikt ciê nie zabierze, gdy bêdziesz spaæ. To tylko koszmar...}
{117} {} {Nie! Zdecydowanie istniej¹... Te g³osy w mojej g³owie... S³yszê je!}
{118} {} {Zbierz siê, ¿o³nierzu! Nie ma ¿adnych g³osów.}
{119} {} {Wiêc... czy to tylko ja? Przepraszam, doktorze...}
{120} {} {Dok³adnie, Bell. To tylko zaburzenie psychiczne. Musisz trochê odpocz¹æ.}
{121} {} {Doktorze, ju¿ to powiedzia³eœ, ale tabletki nasenne nie dzia³aj¹...}
{122} {} {Dam ci podwójn¹ dawkê. Wszystko bêdzie dobrze.}
{123} {} {Dziêki doktorze... Spróbujê zasn¹æ...}
{124} {} {To dobrze. Spij, Bell. Tym razem nikt nie bêdzie Ci przeszkadza³.}
{125} {} {* Hr-r-r *}
{126} {} {Ugh, w koñcu siê zamkn¹³.}
{127} {} {* Zzz *}
{128} {} {Có¿, d³ugo oczekiwana chwila spokoju...}
{129} {} {* N – n – n *}
{130} {} {}

{200} {} {Przychodz¹ do mnie we œnie... Nie pozwól mi spaæ!}
{201} {} {Kto? Kto przychodzi do Ciebie we œnie?}
{202} {} {One! Ogromne... przera¿aj¹ce...}
{203} {} {S³uchaj Bell, chcê pomóc. Opisz, kogo siê boisz.}
{204} {} {Zo³nierzu! WeŸ siê w garœæ!}
{205} {} {Straszne... p³on¹ce oczy w ciemnoœci... nic nie pamiêtam...}
{206} {} {Wygl¹da na to, ¿e zakopa³eœ swoje wspomnienia w swojej podœwiadomoœci.}
{207} {} {Przestañ p³akaæ jak baba.}
{208} {} {To ogromny cieñ. Z p³on¹cymi oczami. Przychodzi do mnie we œnie... Nie mogê siê ruszyæ... Ogl¹da... Ogromna...}
{209} {} {Co jeszcze widzisz w pobli¿u? Dawaj, przypomnij sobie.}
{210} {} {Kto ogl¹da? Gdzie patrzy? Niczego nie rozumiem!}
{211} {} {Wszêdzie wokó³ ciemnoœci... I szara pustynia... Nie, to nie jest szary piasek, to jest popió³... To jest piek³o! Próbujê biec, ale to nie dzia³a... To nie dzia³a!}
{212} {} {Pustynia popio³ów? Gdzie to mo¿e byæ?}
{213} {} {Masz urojenia. Nie ma takiej pustyni.}
{214} {} {Nie wiem! Nie wiem! Zostaw mnie!}
{215} {} {Uch, dobrze.}
{216} {} {Ok. Twoje marudzenie ju¿ zaczyna mnie nudziæ.}

{220} {} {Chcê spaæ... Ale nie pozwól mi spaæ! Inaczej przyjdzie po mnie... Tak, przyjdzie i zabierze mnie prosto do piek³a.}
{221} {} {Um, muszê wyjœæ. Bywaj.}

{230} {} {Bell, patrz. Oto g³owa stworzenia, którego tak siê boisz.}
{231} {} {Bell, wiem, kogo widzia³eœ w kamienio³omie. Ta rzecz jest martwa. Mieszkañcy Casa Nueva ju¿ tañcz¹ wokó³ jej grobu.}
{232} {} {Co... To jest... Ah, h-ha! Ona nie ¿yje! Nie ¿yje! A w œwietle dnia nie jest to takie straszne. Uff! Co za g³upiec! Tyle strachu przed jakimœ brzydkim mutantem. Ha ha!}
{233} {} {Tak. Wszystko skoñczone. Ju¿ nie przyjdzie do ciebie we œnie.}
{234} {} {Kto by w to w¹tpi³.}
{235} {} {Teraz pamiêtam wszystko. To stworzenie by³o tu¿ przede mn¹ podczas nocnej stra¿y w kamienio³omie. Spojrza³o mi prosto w oczy! By³em o krok od œmierci. Ale mia³em szczêœcie, zaatakowa³o mojego partnera... Myœlê, ¿e tak siê przestraszy³em, ¿e tê noc ukry³em g³êboko w mojej podœwiadomoœci.}
{236} {} {Có¿, ka¿dy móg³ siê przestraszyæ.}
{237} {} {Mnie to nie przestraszy³o.}
{238} {} {Ale teraz jestem wolny! Dziêkujê, zas³ugujesz na tytu³ paladyna bardziej ni¿ ja. Pozwól, ¿e podzielê siê z tob¹ kulami. Przynajmniej tyle mogê dla Ciebie zrobiæ.}
{239} {} {Uwa¿aj na siebie, ¿o³nierzu.}
{240} {} {Tak, zdecydowanie nie potrzebujesz kul. Powodzenia.}