{100} {} {Widzisz genera³a Dixona.}
{101} {} {Widzisz samego genera³a - niesamowicie pró¿nego i pewnego siebie wojownika.}
{102} {} {Nie mam teraz czasu na rozmowê.}
{103} {} {?}
{104} {} {Co ty robisz?! Ka¿da zbroja wspomagana jest w³asnoœci¹ Bractwa Stali. Natychmiast zwróæ j¹ kwatermistrzowi.}
{105} {} {Dziêki za pomoc z komandosami. Ale mam teraz du¿o do zrobienia. Skontaktuj siê z kimœ poni¿ej.}
{106} {} {Oficjalnie porzuci³eœ odznakê Stra¿nika.}
{107} {} {Oficjalnie do³¹czy³eœ do Zakonu Bractwa Stali.}
{108} {} {[Head test]}
{109} {} {[Usmiech]}
{110} {} {[Normal]}
{111} {} {[Boo]}
{112} {} {[Wyjœcie]}

# Pierwszy dialog
{200} {} {Cywil? Co Ty tutaj robisz?}
{201} {} {Ja... hm...}
{202} {} {Niszczê twój statek, idioto.}
{203} {} {Szczur na statku! Powiadomiæ wszystkich o alarmie!}
{204} {} {Kl¹twa...}
{205} {} {To ciê nie uratuje...}

{210} {} {Czy to kurwa jakiœ ¿art? Ktoœ dziœ otrzyma surow¹ reprymendê za przepuszczenie cywila. Ok, powiedz mi, kim jesteœ i czego chcesz?}
{211} {} {Jestem tu, ¿eby zniszczyæ twoj¹ paskudn¹ dru¿ynê kolonialn¹. Smieræ najeŸdŸcom!}
{212} {} {Puœæ mnie, generale.}
{213} {} {Ulysses Grant przesy³a Ci raport.}
{214} {} {Ach, w koñcu. Mówi¹, ¿e ostatnie wydarzenia w Phoenix powinny mnie zadowoliæ. Spójrzmy, kurierze, nie zawiedŸ mnie.}
{215} {} {W porz¹dku, generale.}
{216} {} {Zrobiê co w mojej mocy, generale.}
{217} {} {Ale zastanawiam siê te¿, dlaczego Ulysses wybra³ CIEBIE do zg³oszenia? To odpowiedzialne zadanie, nie powierzy³by tego prostemu oszustowi. Opowiedz mi o sobie, kim jesteœ i jak odnosisz siê do sekciarzy w Phoenix?}
{218} {} {Mam d³ug¹ historiê, generale. Pochodzê z wioski na pó³nocy. Pewnie o niej nie s³ysza³eœ.}
{219} {} {Wioska? Wiêc coœ uprawiasz, tak? A mo¿e polujesz i zbierasz?}
{220} {} {Uprawiamy ziemie i uprawiamy kukurydze. Jednak ostatnio pojawi³y siê problemy z kolonistami z Flagpool...}
{221} {} {Ach, wszystko jasne. Zosta³em ju¿ poinformowany, ¿e w kopalniach uranu brakuje ludzi. Có¿, koszty s¹ nieuniknione. To cholernie niesprawiedliwe, synu.}
{1221} {} {Ach, wszystko jasne. Zosta³em ju¿ poinformowany, ¿e w kopalniach uranu brakuje ludzi. Có¿, koszty s¹ nieuniknione. To cholernie niesprawiedliwe, pani.}
{222} {} {Racja, generale.}
{223} {} {Hard przys³a³ mnie z Tu-San. Oto jego rekomendacja.}
{224} {} {Hard musi mieæ naprawdê dobry powód do twojej rekomendacji. S³ysza³em, ¿e ostatnio zasz³y du¿e zmiany w Tu-San, prawda? Ale opowiedz mi o sobie, kim jesteœ i jak zdoby³eœ takie zaufanie wœród Blacharzy?}
{1224} {} {Hard musi mieæ naprawdê dobry powód do twojej rekomendacji. S³ysza³em, ¿e ostatnio zasz³y du¿e zmiany w Tu-San, prawda? Ale opowiedz mi o sobie, kim jesteœ i jak zdoby³aœ takie zaufanie wœród Blacharzy?}
{225} {} {Wys³ali mnie Rangersi. Chc¹ ciê powstrzymaæ, ale jestem zainteresowany wys³uchaniem obu stron.}
{226} {} {Ha, wiemy, ¿e Rangersi prowadz¹ zwiad. Ale szanujê twoj¹ odwagê i szczeroœæ. Powiedz mi, co Stra¿nicy obiecali ci tak cennego w zamian za nasze sekrety?}
{227} {} {W³aœciwie to obiecali wolnoœæ i ochronê dla mojej rodzinnej wioski.}
{228} {} {Jestem tutaj, poniewa¿ jesteœ odpowiedzialny za k³opoty mojej wioski. Z powodu twojego pragnienia energii, Kolonia Flagpool zniewala wioski takie jak moja.}
{229} {} {Domagam siê wolnoœci i niezale¿noœci dla mojej rodzinnej wioski.}
{230} {} {Pewnie marzysz o wolnoœci dla swojej wioski, co? Chcesz ¿eby bandyci nie przeszkadzali twojemu bratu i ¿eby kukurydza ros³a bez krwi i potu.}
{231} {} {Czy to mo¿liwe, generale?}
{232} {} {Oczywiœcie, generale.}
{233} {} {Bractwo Stali wie, jak zaprowadziæ wolnoœæ i sprawiedliwoœæ. Jesteœmy jedynymi, którzy zachowali m¹droœæ Starego Swiata.}
{234} {} {Trudno siê z tym k³óciæ.}
{235} {} {Naprawdê?}
{236} {} {Jeœli twoja wioska potrzebuje wolnoœci, do³¹cz do naszego Bractwa. Bêdziemy chroniæ Villê przed wrogami i pomagaæ technologi¹. W zamian oczywiœcie za niewielk¹ nadwy¿kê plonów. Ale ¿adne stworzenie w Arizonie nie odwa¿y siê naruszyæ Waszej œwiêtej wolnoœci.}
{237} {} {Ale prawie nic nie wiemy o twoim Bractwie.}
{238} {} {To wielkie s³owa, generale. Ale co to w³aœciwie za Bractwo?}
{239} {} {Bractwo Stali to staro¿ytny zakon. Gromadzimy i o¿ywiamy technologie i wiedze, które zosta³y utracone po Wielkiej Wojnie. D³ugo ukrywaliœmy siê w cieniu historii, badaj¹c sytuacjê i zbieraj¹c si³y. A teraz nadszed³ koniec naszej izolacji. Bractwo opuœci³o swój bunkier kilka lat temu. Nasi skrybowie znaj¹ szczegó³y.}
{240} {} {.......}
{241} {} {Tylko przechodzi³em obok i tak zastanawia³em siê, czy masz jak¹œ pracê?}
{242} {} {Nie rozmawiam z najemnikami. Na zewn¹trz znajduje siê specjalny wpis do tego. Teraz proszê ciê o natychmiastowe opuszczenie naszej fortecy.}
{243} {} {Sorry generale...}
{244} {} {Ok, spokojnie wychodzê.}
{245} {} {Jak zamierzasz zmieniæ Pustkowie?}
{246} {} {Ale co próbujesz osi¹gn¹æ dziêki swojej ekspansji?}
{247} {} {Pustkowia same musz¹ siê odrodziæ. My jesteœmy tylko opiekunami. Mamy do tego wiedzê i technologie, których nikt inny nie ma. Z pewnoœci¹ ludzie w twojej Villi nadal pracuj¹ rêcznie, prawda?}
{248} {} {[Pos³uchaj]}
{249} {} {WyobraŸ sobie, jak zmieni³aby siê wioska, gdybyœmy wprowadzili pompy wodne, generatory i nowe narzêdzia. Nie wspominaj¹c o lekarstwach i œrodkach przeciwko bandytom.}
{250} {} {Po prostu nas zajmiesz i ka¿esz nam pracowaæ dla dobra Bractwa. To nie jest wolnoœæ.}
{251} {} {W takim razie tracê czas, próbuj¹c byæ dla ciebie mi³ym. Twoja wioska bêdzie nam dostarcza³a po¿ywienie nawet wbrew w³asnej woli. Mia³eœ szansê wybraæ ³atw¹ œcie¿kê, ale tê szansê przegapi³eœ. Od³óz broñ i podnieœ rêce.}
{252} {} {Ech, nie, generale...}
{253} {} {Cholera. Nie mo¿esz zastraszyæ wolnych ch³opów.}
{254} {} {Brzmi niesamowicie. Porozmawiam ze starszymi.}
{255} {} {M¹dra decyzja, mi querido amigo. Jednak nawet za zgod¹ twojej spo³ecznoœci jest jedna istotna przeszkoda - Rangersi uniemo¿liwiaj¹ nam rozwój w kierunku pó³nocnym, a tak¿e sabotuj¹ œwiat wokó³ Phoenix. A my w³aœnie prowadzimy rekonesans na ich ziemiach, aby spacyfikowaæ tych samozwañczych bandytów.}
{256} {} {Wiêc musz¹ zostaæ wyeliminowani. Ich ziemie le¿¹ na mojej drodze.}
{257} {} {Uwielbiam byæ rozumiany za pierwszym razem. ZnajdŸ bazê Rangersów i przeprowadŸ tam rekonesans. O ile wiem, u¿ywaj¹ starej tamy jako fortu. Wystarczy jedno pêkniêcie, aby go zniszczyæ. Smia³o.}
{258} {} {Tak siê stanie, generale!}
{259} {} {Cokolwiek pan powie, panie Dixon.}

{260} {} {Wiêc wreszcie siê poznajemy, ty pieprzony draniu. Wiedzia³em, ¿e kiedyœ tu przyjdziesz. Tak, ca³a Arizona ju¿ ciê zna.}
{1260} {} {Wiêc wreszcie siê poznajemy, ty pieprzona suko. Wiedzia³em, ¿e kiedyœ tu przyjdziesz. Tak, ca³a Arizona ju¿ ciê zna.}
{261} {} {Wiêc wreszcie siê poznajemy, ty pieprzonym draniu. Wiedzia³em, ¿e kiedyœ tu przyjdziesz. Tak, ca³a Arizona ju¿ o tobie mówi.}
{1261} {} {Wiêc wreszcie siê poznajemy, ty pieprzona suko. Wiedzia³em, ¿e kiedyœ tu przyjdziesz. Tak, ca³a Arizona ju¿ o tobie mówi.}
{262} {} {Sk¹d o mnie wiesz?}
{263} {} {Naiwny rudzielec, czy naprawdê myœla³eœ, ¿e twoje wybryki pozostan¹ niezauwa¿one? Mamy wystarczaj¹co du¿o uszu na pustkowiach, aby poznaæ wszystkie najwa¿niejsze wydarzenia.}
{1263} {} {Naiwna ma³a dziewczynko, czy naprawdê myœla³aœ, ¿e twoje wybryki pozostan¹ niezauwa¿one? Mamy wystarczaj¹co du¿o uszu na pustkowiach, aby poznaæ wszystkie najwa¿niejsze wydarzenia.}
{264} {} {Co o tym myœlisz, generale?}
{265} {} {Nie obchodzi mnie to. Jestem tu, ¿eby wykoñczyæ ciebie i ca³y twój oddzia³.}
{266} {} {Bracie, czy masz pojêcie, ile pracy zajê³o zbudowanie kultu w Phoenix? Ca³a ta wspania³a praca mia³a na celu o¿ywienie miasta. A teraz jedyna okazja wypali³a siê w po¿arze nuklearnym z powodu garstki ch³opów. To tragedia dla ca³ej Arizony, do cholery!}
{267} {} {Kontynuuj.}
{268} {} {Wiesz, ile pracy w³o¿yliœmy w sojusz z Blacharzami? Nasi dyplomaci dokonali cudów w nawi¹zywaniu z nimi kontaktu. Tylko nadal trzeba by³o wytyczyæ bezpieczniejsze trasy karawan. Teraz wszystko w okolicy Tu-San wymrze z twojego powodu.}
{269} {} {Kontynuuj.}
{270} {} {Kopalnie Flagpool by³y krytycznym elementem w ca³ym systemie. Ruda uranu dostarcza energii, a bez niej ¿aden rozwój w Arizonie nie jest mo¿liwy. A teraz to Ÿród³o jest zamkniête na nadchodz¹ce dziesiêciolecia. Czy mo¿esz sobie wyobraziæ skalê tej tragedii?}
{271} {} {Kontynuuj.}
{272} {} {.....}
{273} {} {Kontynuuj.}
{274} {} {A teraz mam do ciebie pytanie - co próbujesz osi¹gn¹æ, sukinsynu?}
{1274} {} {A teraz mam do ciebie pytanie - co próbujesz osi¹gn¹æ, suko?}
{275} {} {Ca³y ten ruch postawi³ moj¹ rodzinê w trudnej sytuacji. Szukam wolnoœci dla mojej Villi.}
{276} {} {Mo¿e okaza³bym ci wspó³czucie próbuj¹c znaleŸæ kompromis, ale taka wspania³a praca, maj¹ca na celu ustanowienie procesów spo³ecznych, ekonomicznych i technologicznych w ca³ym stanie, idzie na marne przez kretoszczura z powodu jednej brudnej, opornej wioski!}
{277} {} {Tak, zgadza siê. Nie mo¿esz tak po prostu odebraæ nam naszej wolnoœci. Coœ ci siê nie podoba, generale?}
{278} {} {Pope³niasz przestêpstwo przeciwko miejscowej ludnoœci pod pozorem szlachetnych celów. Nawet nie zapyta³eœ nas o opinie.}
{279} {} {Gdyby gospodynie zarz¹dza³y polityk¹ przed wojn¹, œwiat nie móg³by prze¿yæ ani jednego dnia!}
{280} {} {Bzdury. Gospodynie domowe nie chcia³yby, aby œwiat siê spali³. Z powodu twojej ingerencji, Dixon, ca³a Arizona jest w ogniu.}
{281} {} {Mo¿esz mieæ racjê, generale.}
{282} {} {Có¿, mimo wszystkich swoich wybryków, muszê to przyznaæ. Nigdy bym siê nie spodziewa³, ¿e jeden wieœniak bêdzie w stanie wykonaæ tak z³o¿one przedsiêwziêcie. I wiesz, jestem gotów wybaczyæ ci te zbrodnie.}
{283} {} {Naprawdê?}
{284} {} {Och, jak "szlachetnie" z twojej strony.}
{285} {} {Twoja zbuntowana wioska otrzyma przebaczenie i immunitet od Bractwa. Ale ¿eby tak siê sta³o, konieczne jest wyeliminowanie naszego g³ównego konkurenta w Arizonie - Rangersów. Mówi¹, ¿e zbudowali fort w starej elektrowni wodnej. Zbadaj j¹ i znajdŸ sposób na zniszczenie ich tamy.}
{286} {} {Cholera. Stra¿nicy nas ochroni¹, a ty pójdziesz do piek³a.}
{287} {} {Przykro mi. Tak wiêc, zgodnie z prawami Starego Swiata, za twoje zbrodnie czeka ciê kara œmierci. Przygotuj siê, by zaakceptowaæ swój los, œcierwojadzie...}
{288} {} {IdŸ do diab³a.}
{289} {} {Ale ja nie jestem kryminalist¹...}
{1289} {} {Ale ja nie jestem kryminalist¹...}
{290} {} {Jeœli zostawisz nas w spokoju, spróbujê.}
{291} {} {Jako Wysoki Paladyn dotrzymam s³owa. Smia³o.}
{292} {} {Do widzenia.}
{293}{}{Dziwnie s³yszeæ to z ust osoby za to odpowiedzialnej.}
{294}{}{O czym ty do diab³a mówisz? Jesteœmy tylko koñcowymi nabywcami baterii j¹drowych. Robi¹ je Blacharze z Tu-San, a uran do nich sprowadzany jest z Flagpool. Ja te¿ nie jestem w nastroju, ¿e kierownictwo kolonii pad³o ofiar¹ ich chciwoœci. Ale musimy na to przymkn¹æ oko. Potrzebujemy tych baterii!}
{295}{}{Tak. Wygl¹da na to, ¿e wypad³eœ z biznesu. Powiesz coœ wiêcej?}
{296}{}{S³uchaj synu, nie jesteœmy handlarzami niewolników. Jesteœmy staro¿ytnym szlachetnym zakonem, którego celem jest utrzymanie porz¹dku na pustkowiach. A Kalifornia to teraz totalny ba³agan. W tej chwili trwa tam wojna z armi¹ supermutantów. Jeœli Bractwu nie uda siê powstrzymaæ tego zielonego zagro¿enia, to wkrótce dotrze do ciebie. Chcesz tego?}
{1296}{}{S³uchaj, kobieto, nie jesteœmy ³owcami niewolników. Jesteœmy staro¿ytnym szlachetnym zakonem, którego celem jest utrzymanie porz¹dku na pustkowiach. A Kalifornia to teraz totalny ba³agan. W tej chwili trwa tam wojna z armi¹ supermutantów. Jeœli Bractwu nie uda siê powstrzymaæ tego zielonego zagro¿enia, to wkrótce dotrze do ciebie. Chcesz tego?}
{297}{}{Oczywiœcie, ¿e nie, sir.}
{298}{}{Przestañ wciskaæ mi takie gówno. Jedyne zagro¿enie jakie widzê jest przede mn¹!}
{299}{}{}

# Powtarzajacy siê dialog
{300} {} {Raport.}
{301} {} {Puœæ mnie, generale.}

{310} {} {Mam dla ciebie raport od Ulysses Granta.}
{311} {} {Nie mog³em siê doczekaæ tej rozmowy przez d³ugi czas. ChodŸ tu.}
{312} {} {To jest to.}
{313} {} {W³aœciwie to taœma siê zepsu³a. Przepraszam.}
{314} {} {}
{315} {} {Dlaczego nie po³o¿ysz na piersi tabliczki z napisem „Debil”? Nie obchodzi mnie jak, ale wykonaj swoj¹ pracê i przynieœ mi ten raport!}
{1315} {} {Dlaczego nie po³o¿ysz na piersi tabliczki z napisem „Debil”? Nie obchodzi mnie jak, ale wykonaj swoj¹ pracê i przynieœ mi ten raport!}
{316} {} {Uch, w porz¹dku, generale.}
{317} {} {To by³ ¿art, generale. Holodysk jest sprawny.}
{318} {} {Myœlisz, ¿e to zabawne? Cholerne dzikusy! Pod moim dowództwem jest ca³a armia, a ty sobie ze mnie ¿artujesz? Módl siê, aby raport nie pogorszy³ sytuacji. W przeciwnym razie zedrê z ciebie skórê. Wiêc gdzie jest ten raport?}
{319} {} {To jest to, generale.}
{320} {} {Nie tak szybko. Obiecano mi nagrodê za tê pracê.}
{321} {} {Twoim zadaniem jest wykonanie swojej pracy i zamkniêcie buzi, dopóki nie odezwie siê do ciebie starszy stopniem. Wiêc b¹dŸ cicho! Gdzie jest ten raport?}
{322} {} {Wiêc. Mhm. Ciekawe. Dobre wieœci. Mówi równie¿ o twoich zas³ugach dla Rady. Ulysses nie zwróci³by na ciebie tak du¿ej uwagi bez dobrego powodu.}
{323} {} {Có¿, moje zadanie jest zakoñczone. Myœlê, ¿e czas ju¿ iœæ.}
{324} {} {Podró¿ przez pustyniê musia³a poch³on¹æ wiele twoich zapasów. Nie martw siê, zap³acimy za robotê. Skontaktuj siê z kwatermistrzem, nagrodzi ciê.}
{325} {} {Dziêki, Ogólne}
{326} {} {Z ciekawoœci - co tam by³o napisane?}
{327} {} {To niezbyt m¹dre z twojej strony, zadawaæ takie pytania. Jednak s¹dz¹c po raporcie, ju¿ du¿o wiesz.}
{328} {} {Valid.}
{329} {} {Po prostu wykonujê swoj¹ pracê. A co z p³atnoœci¹?}
{330} {} {Chcesz robiæ coœ dla kogoœ, ale ostatecznie i tak interesuje ciê zap³ata? Szkoda, ¿e wœród twoich interesów nie ma pojêcia honoru i sprawiedliwoœci. Ale dobrze wykonujesz swoj¹ pracê, co w Bractwie jest doceniane. Nie martw siê, zap³acimy. Skontaktuj siê z kwatermistrzem, nagrodzi ciê.}
{331} {} {Dziêki, Ogólne}

# Zapytania o BS
{350} {} {Opowiedz mi o Bractwie Stali.}
{351} {} {Rozmawiasz z genera³em, do cholery. Nie mam ani czasu, ani ochoty na takie rozmowy.}
{352} {} {}
{353} {} {Ok, spróbujê zapytaæ kogoœ innego.}
{354} {} {Generale Dixon, czy móg³byœ opowiedzieæ mi coœ o Bractwu?}
{355} {} {Jesteœmy zamkniêt¹ organizacj¹ z Kalifornii z przepisami wojskowymi i d³ug¹ histori¹.}
{356} {} {Wygl¹da na to, ¿e nie jesteœ st¹d.}
{357} {} {Wczeœniej Bractwo mieszka³o w podziemnym bunkrze i nie wychodzi³o stamt¹d niepotrzebnie. Tylko niewielu bohaterom uda³o siê dostaæ do œrodka. Nie wtr¹caliœmy siê w sprawy regionu, tylko handlowaliœmy i utrzymywaliœmy porz¹dek w naszej okolicy.}
{358} {} {Kontynuuj.}
{359} {} {To musia³o byæ strasznie nudne.}
{360} {} {Po wydarzeniach, o których prawdopodobnie nie wiesz, starsi w koñcu zdecydowali siê wyjœæ z dusznego lochu i rozpocz¹æ eksploracje okolicznych ziem.}
{361} {} {Rozumiem. Wiesz, mam jeszcze wiêcej pytañ dotycz¹cych Bractwa.}
{362} {} {Cieszysz siê, ¿e opuszczasz duszny bunkier, prawda? Wygl¹da na to, ¿e Bractwo potrzebuje œwie¿ego powietrza.}
{363} {} {Dziêkujê za poœwiêcony czas. Nie oœmielê siê ju¿ ciê zatrzymywaæ.}
{364} {} {Dlaczego zatrzymujesz siê w tym konkretnym porcie?}
{365} {} {To dobre miejsce na zbudowanie fortecy nie do zdobycia. Poza tym nie ma lepszego reaktora w okolicy ni¿ ten naszego niszczyciela.}
{366} {} {Rozumiem. Czy mo¿esz odpowiedzieæ na inne pytanie dotycz¹ce Bractwa?}

{367} {} {Dlaczego wtr¹casz siê w sprawy tego regionu?}
{368} {} {Technicznie potrzebujemy zasobów. Aby je zdobyæ, potrzebujemy si³y roboczej i dobrze funkcjonuj¹cej infrastruktury. Nie da siê tego wszystkiego zdobyæ w tak dzikiej krainie na w³asn¹ rêkê. Dlatego jest tylko jeden sposób - po³¹czyæ lokalnych dzikusów, ucz¹c ich, jak trzymaæ ³opatê prosto.}
{369} {} {Jest inna odpowiedŸ, prawda?}
{370} {} {Spójrz na swoje plemiona. S¹ wrogo nastawieni z powodu drobnych problemów. Za ¿a³osny ³yk wody s¹ gotowi poder¿n¹æ sobie gard³a. Miasto Phoenix jest obiektem zazdroœci dla wszystkich okolicznych osad, a same osady nienawidz¹ siê nawzajem jeszcze bardziej. Te ziemie potrzebuj¹ si³y, która mog³aby je zjednoczyæ i skierowaæ na w³aœciwe tory, tory odrodzenia.}
{371} {} {[Dalej.]}
{372} {} {Czy w tych krainach jest taka si¹a? Nie. Ale oto nadchodzimy. Oczywiœcie mamy swoje osobiste zainteresowania - przedwojenne zasoby i wiedzê. Wy, dzicy, i tak nie jesteœcie w stanie w³aœciwie wykorzystaæ tych z³ó¿ bezcennych ludzkich tworów.}
{373} {} {[Dalej.]}
{374} {} {Aby je zdobyæ, pchamy lokalne plemiona na œcie¿kê postêpu i zjednoczenia. A w zamian otrzymuj¹ doœwiadczenie, które tylko my mo¿emy daæ. Sprowadziliœmy na te ziemie ekonomiê, walutê, medycynê, a nawet pierwsz¹ szko³ê w ca³ej powojennej historii! Nawet jeœli jakieœ lokalne dzikusy nas nienawidz¹, to tylko my mo¿emy o¿ywiæ ziemie Arizony i doprowadziæ je do dobrobytu.}
{375} {} {To s¹ twoje s³owa, Dixon. Czy Sztab Generalny wie co tu siê dzieje?}
{376} {} {Ten fort jest nieco... poza w³adz¹ Sztabu Generalnego. Otrzyma³em „szerokie uprawnienia”, aby pomyœlnie ukoñczyæ g³ówn¹ misjê.}
{377} {} {Rozumiem. Czy mo¿esz odpowiedzieæ na inne pytanie dotycz¹ce Bractwa?}

{380} {} {Jakie s¹ Twoje globalne cele?}
{381} {} {OdpowiedŸ bêdzie mieszana. Od dziesiêcioleci tocz¹ siê spory miêdzy skrybami. Niektórzy uwa¿aj¹, ¿e powinniœmy skierowaæ nasz¹ energiê w kierunku odbudowy cywilizacji zgodnie z idea³ami Starego Swiata. Inni uwa¿aj¹, ¿e œwiat nie jest wart naszej wiedzy i technologii.}
{382} {} {[Dalej.]}
{383} {} {W ka¿dym razie dowództwo nie mia³o zamiaru wp³ywaæ na Arizonê. Tutaj zakon mia³ tylko nadziejê na uzupe³nienie zapasów materia³ów j¹drowych i uruchomienie kilku ocala³ych warsztatów. Wy³¹cznie do w³asnych celów wewnêtrznych. Ale wszystko okaza³o siê du¿o bardziej skomplikowane.}
{384} {} {Co masz na myœli?}
{385} {} {Oni nie rozumiej¹, ¿e nie mo¿na po prostu przyjœæ i zabraæ tego czego siê potrzebuje. Potrzebujemy r¹k do pracy, karawan, a nawet poczty. Potrzebujemy sprawnej infrastruktury i gospodarki! Nic z tego nie mia³o tu miejsca, dopóki moja dru¿yna nie wkroczy³a na te dzikie ziemie.}
{386} {} {Rozumiem. Czy mo¿esz odpowiedzieæ na inne pytanie dotycz¹ce Bractwa?}
{387} {} {Opowiedz mi o Kalifornii.}
{388} {} {Ziemie Kalifornii s¹ spustoszone przez wojnê i czas. Los Angeles leg³o w gruzach. Ale stopniowo cywilizacja powstaje z popio³ów.}

{400} {} {Muszê z tob¹ porozmawiaæ o Rangersach.}
{401} {} {Ci nowicjusze ci¹gle daj¹ o sobie znaæ i uniemo¿liwiaj¹ nam prace. Czy znasz ju¿ s³aboœci ich obrony?}
{402} {} {Nie, proszê pana. S¹ zbyt dobrze zorganizowani.}
{403} {} {Trudno oczekiwaæ czegokolwiek od prostego ch³opa. Ale jestem pewien, ¿e ci siê uda. Informuj mnie o postêpach.}
{1403} {} {Trudno oczekiwaæ czegokolwiek od prostej wieœniaczki. Ale jestem pewien, ¿e ci siê uda. Informuj mnie o postêpach.}
{404} {} {Puœæ mnie.}
{405} {} {Jak Stra¿nicy ciê niby powstrzymuj¹? Czy oni nie reprezentuj¹ prawa, tak jak Ty?}
{406} {} {Po pierwsze, postrzegaj¹ nas jako najeŸdŸców i zwracaj¹ ludnoœæ przeciwko nam. A to bezpoœrednio koliduje z naszymi planami. Po drugie, hamuj¹ rozwój postêpu, na przyk³ad sabotuj¹c prace karawan i obozów pracy. W koñcu zagarneli dla siebie ogromne ziemie i pobieraj¹ podatki od ludnoœci. Kim oni myœl¹, ¿e s¹?!}
{407} {} {Mo¿e maj¹ powód?}
{408} {} {Przypominaj¹ ci kogoœ, prawda?}
{409} {} {Um... W koñcu powstrzymuj¹ nas przed po³¹czeniem Kalifornii i Arizony. Co wiêcej, pokazali ju¿ swoj¹ pod³oœæ w bitwie pod Nogales, kiedy próbowali wpl¹taæ nas w k³opoty z Blacharzami i wypêdziæ nas z tego stanu. To wiêcej ni¿ wystarczaj¹co.}
{410} {} {Czy mogê iœæ, generale?}
{411} {} {Uda³o mi siê wysadziæ tamê Rangersów.}
{412} {} {Zosta³em ju¿ o tym poinformowany. Dobra robota. Z Twoj¹ pomoc¹ wypêdzimy tych najeŸdŸców z Arizony i przywrócimy porz¹dek na tych ziemiach, jak za dawnych dobrych czasów.}
{413} {} {A co z nasz¹ umow¹?}
{414} {} {Oczywiœcie Villa jest teraz pod nasz¹ ochron¹. Wyœlemy ambasadora do wioski, aby zawar³ sojusz.}
{415} {} {To dobre wieœci.}
{416} {} {Ponadto, w ramach s³u¿by w Stanach Zjednoczonych, zapraszam do zostania cz³onkiem Bractwa Stali. Zaden cywil nie mia³ wczeœniej takiego zaszczytu. Ale ja mam specjalne prawa i widzê w tobie wielki potencja³. Pomyœl o tym i daj mi znaæ o swojej decyzji. Mo¿esz odejœæ.}
{417} {} {Dziêkujê, generale Dixon.}

{420} {} {Chcê do³aczyæ do Bractwa.}
{421} {} {Uklêknij wiêc i wypowiedz swoje imiê.}
{422} {} {Jestem }
{423} {} { z Villi. I przysiêgam wiernoœæ Bractwu Stali.}
{424} {} {Wybierz swój przydzia³.}
{425} {} {Chcê zostaæ skryb¹ i nieœæ m¹droœæ Starego Swiata.}
{426} {} {Chcê zostaæ paladynem i przynieœæ œmieræ wrogom Bractwa.}
{427} {} {Chcê zostaæ rycerzem, aby nieœæ œwiat³o technologii.}
{428} {} {Chcê zostaæ zwiadowc¹, co przyniesie najwieksz¹ korzyœæ Bractwu.}
{429} {} {Niech tak bêdzie. }
{430} {} { z Villi. Od teraz jesteœ honorowym cz³onkiem Zakonu Bractwa Stali. Nie hañb naszego imienia i szanuj prawo. Pozostañ wierny, a¿ do œmierci.}
{431} {} {Przysiêgam lojalnoœæ!}
{432} {} {Chocia¿ obieca³em daæ ci rangê w zakonie, okaza³o siê, ¿e wœród naszych braci masz z³¹ opiniê. Bêdê musia³ od³o¿yæ œwiêcenie do czasu ponownego udowodnienia swojej wartoœci.}
{433} {} {Cholera. Reputacja to tylko ma³a rzecz...}
{434} {} {Tylko znakomita s³u¿ba mo¿e pozwoliæ Ci do nas do³aczyæ. A obecnie twoje dokonania nie s¹ tak imponuj¹ce.}
{435} {} {Zrobiê co w mojej mocy.}
{436} {} {Ok. Jeszcze o wszystkim us³yszysz, generale.}
{437} {} {Twoje zas³ugi dla Bractwa s¹ nieocenione. Jestem gotów przyj¹æ Ciê do naszego oddzia³u.}
{438} {} {[Dalej.]}