{100} {} {Widzisz karawaniarza.}
{101} {} {Widzisz mê¿czyznê w zakurzonym ubraniu. Wygl¹da na to, ¿e przeszed³ w nim wiele mil.}
{102} {} {Jestem za tob¹.}
{103} {} {Dziêki za pomoc, ¿o³nierzu.}

{200} {} {Hej! Jesteœ z Bractwa, prawda? No w koñcu, myœla³em ju¿, ¿e mnie zostawiliœcie.}
{201} {} {Jak œmiesz kwestionowaæ honor i walecznoœæ zakonu?}
{202} {} {W³aœciwie to z powodu twojego zamówienia wpakowa³em siê w ten ba³agan. Wiêc masz u mnie d³ug. A teraz zabierz mnie st¹d natychmiast w bezpieczne miejsce.}
{203} {} {Ok, chodŸmy. Poprowadzê ciê do punktu ewakuacji, z którego rozpoczeliœmy atak.}
{204} {} {Lepiej na razie siê nie wychylaj. Zamknij uszy i poczekaj, a¿ to wszystko siê skoñczy.}
{205} {} {Bractwo siê tob¹ zaopiekuje. Rozkazano mi eskortowaæ ciê w bezpieczne miejsce.}
{206} {} {Bardzo dobrze. Opieram siê na twoim doœwiadczeniu, ¿o³nierzu. Ale jeœli zacznie siê walka, bêdê ucieka³, gdzie tylko bêdê móg³.}
{207} {} {ChodŸmy. Paladyn Dobbs ¿¹da zabrania ciê w bezpieczne miejsce.}
{208} {} {Wiêc lepiej siedŸ tutaj, dopóki to wszystko siê nie skoñczy. Poczekaj na moje instrukcje.}
{209} {} {Schowaj siê tutaj i nie wychylaj siê. Muszê oceniæ sytuacjê.}
{210} {} {Gdzie s¹ twoi paladyni? Ju¿ czujê siê nieswojo.}
{211} {} {Jesteœmy. Paladyni zabior¹ ciê st¹d po zakoñczeniu operacji.}
{212} {} {Rozumiem. Dziêki za pomoc, ¿o³nierzu. Myœla³em, ¿e nigdy wiêcej nie odwiedzê ju¿ baru.}
{213} {} {Szczêœcia.}

{220} {} {Opowiedz mi o ataku.}
{221} {} {WieŸliœmy ³adunek dla Bractwa od Blacharzy. Bandyci jakoœ nas wytropili jeszcze przed noclegiem w Casa Nueva. Ale nie œpieszyli siê do ataku, najwyraŸniej zebrali ludzi z ca³ej pustyni. W rezultacie w po³owie drogi do Puerto zostaliœmy po prostu wciœniêci w róg i zmia¿d¿eni przez ogromny t³um. Nie by³o ¿adnej drogi ucieczki.}
{222} {} {Co by³o w ³adunku, który wieŸliœcie do Puerto?}
{223} {} {Jakaœ pieprzona elektronika. Nie mam wiedzy w tej dziedzinie. Ale Bractwo wymaga³o szczególnie ostro¿nego obchodzenia siê z pewnymi przedmiotami.}
{224} {} {Co wiesz o napastnikach?}
{225} {} {To lokalni wyrzutkowie. Ich akcent sugeruje, ¿e przybyli z po³udnia lub mieszkali tu jeszcze przed przybyciem Bractwa.}
{226} {} {Rozumiem. Na razie wystarczy tych pytañ.}