{100} {} {Widzisz Paladyna Dobbsa.}
{101} {} {Widzisz silnego, nieogolonego mê¿czyznê.}
{102} {} {Miej oko na ty³y, rekrucie.}
{103} {} {Wróæ do bazy i zdaj raport Paladynowi Lathamowi. Odmaszerowaæ.}
{104} {} {By³em zaszczycony, mog¹c z tob¹ walczyæ.}
{105} {} {Trybuna³ ju¿ czeka na Ciebie!}

{200} {} {Jak d³ugo mam na ciebie czekaæ, ¿o³nierzu? Jesteœ na s³u¿bie, a nie za wycieczce!}
{201} {} {Przepraszam sir! Ale muszê siê wysikaæ, sir! Wracam wkrótce, sir!}
{202} {} {Jezu, ale tu panuje burdel. Dam ci piêæ minut, rekrucie!}
{203} {} {Potwierdzam sir!}
{204} {} {Przyby³em do operacji. Czekam na dalsze instrukcje.}
{1204} {} {Przyby³am do operacji. Czekam na dalsze instrukcje.}
{205} {} {Wszyscy! Pos³uchajcie mnie! Przed nami obóz wroga. Naszym g³ównym celem jest uwolnienie karawany zak³adników. Potrzebujemy ka¿dego ¿ywego. Bandyci - zneutralizowaæ wszelkimi dostêpnymi œrodkami. Jakieœ pytania? Przejœæ na pozycje!}
{206} {} {Tak jest, sir.}
{207} {} {Pos³uchajcie mnie! Nadesz³a godzina chwalebnej bitwy! Tym razem przed nami jest dobrze ufortyfikowany fort wroga. Uwa¿ajcie, na obwodzie mog¹ byæ pu³apki, a wchodz¹c do ruin uwa¿ajcie na ty³y. Naszym g³ównym celem jest zdobycie informacji o lokalizacji bazy bandytów. Potem musimy zniszczyæ obóz. Jakieœ pytania? Naprzód!}
{208} {} {Zo³nierze! Nadszed³ czas, abyœcie stali siê prawdziwymi Amerykañskimi bohaterami! Przed nami g³ówna baza bandytów. D³ugo próbowalismy j¹ znaleŸæ, a¿ w koñcu siê uda³o. Czas wypaliæ stamt¹d ca³e to potomstwo kretoszczurów! Smia³o, bracia i siostry! Na chwa³ê Bractwa!}
{209} {} {Tak jest!}
{210} {} {...Czekaj. Jest dla ciebie osobne zadanie. ZnajdŸ ³adunek, który najeŸdŸcy zabrali z karawany.}
{211} {} {Przybywasz w sam¹ porê.}
{212} {} {Spodziewaliœmy siê ciebie.}

{220} {} {Raport.}
{221} {} {Zg³oœ sytuacjê.}
{222} {} {Co siê sta³o, rekrucie?}
{223} {} {Idê naprzód, sir.}
{224} {} {[CHIT: wykonalem zadanie]}
{225} {} {Teraz udaj siê do naszej bazy z raportem dla Paladyna Lathama. Mi³ej podró¿y.}
{226} {} {Do wykonania, Sir Dobbs.}

{230} {} {Potrzebujê wsparcia ogniowego. ChodŸ za mn¹...}
{231} {} {Pójdê sam, ¿eby nie zwracaæ na siebie uwagi. Poczekaj na sygna³.}
{1231} {} {Pójdê sama, ¿eby nie zwracaæ na siebie uwagi. Poczekaj na sygna³.}
{232} {} {Stop, rekrucie! Jak œmiesz opuszczaæ teren operacji bez pozwolenia? Czy ty w ogóle wykona³eœ swoje zadanie? Tak? Czekam na wyjaœnienia!}
{1232} {} {Stop, rekrucie! Jak œmiesz opuszczaæ teren operacji bez pozwolenia? Czy ty w ogóle wykona³aœ swoje zadanie? Tak? Czekam na wyjaœnienia!}
{233} {} {Nie, zawiod³em misjê. Przepraszam, panie paladyn...}
{1233} {} {Nie, zawiod³am misjê. Przepraszam, panie paladyn...}
{234} {} {Dezerter! Czeka Ciê Trybuna³! Ani kroku dalej!}
{235} {} {Cokolwiek powiesz, sir...}
{236} {} {Nie obchodzi mnie to.}

{240} {} {Przypomnij mi o mojej misji.}
{241} {} {Powinieneœ by³ uwa¿nie wys³uchaæ odprawy, rekrucie! Odszukaj zak³adnika i zabierz go w bezpieczne miejsce - do miejsca ewakuacji. To jest Twoje g³ówne zadanie, my zajmiemy siê reszt¹.}
{242} {} {ZnajdŸ lokalizacjê g³ównej bazy bandytów. Wydob¹dŸ z tych skurwieli informacje albo znajdŸ jak¹œ pieprzon¹ kartkê, ¿o³nierzu. ObudŸ swój pieprzony umys³!}
{243} {} {ZnajdŸ ³adunek, który bandyci ukradli z karawany. Wœród rzeczy powinien znajdowaæ siê cenny przedwojenny zabytek. Musimy zabraæ go z powrotem do bazy. Twój udzia³ w dzia³aniach czysto militarnych jest opcjonalny. Wszystko jasne? Powodzenia ¿o³nierzu.}
{244} {} {Rozumiem.}
{245} {} {Zak³adnik jest bezpieczny.}
{246} {} {Bardzo dobrze. Strata tak cennej karawany by³aby niewybaczalnym b³êdem.}
{247} {} {Mi³o siê przydaæ.}
{1247} {} {Mi³o siê przydaæ.}
{248} {} {Zak³adnik zmar³. Przepraszam pana.}
{249} {} {Zmar³? Cholera... Dobra, teraz nie mamy powodu, ¿eby byæ mi³ymi dla tych œmieci.}
{250} {} {Cokolwiek powiesz, sir...}
{251} {} {Uda³o mi siê dowiedzieæ, gdzie jest baza.}
{252} {} {NieŸle rekrucie. W³aœnie po to tu przyjecha³eœ.}
{253} {} {Uda³o mi siê zdobyæ swiêt¹ relikwiê. Oto ona, Sir Dobbs.}
{254} {} {Dobra robota, wojowniku!}