{100} {} {Widzisz Corwina.}
{101} {} {Widzisz pracownika kuchni. Nuci pod nosem g³upi¹ piosenkê o fasoli i... fasoli?}
{102} {} {To nie jest czas na rozmowy z miejscowymi.}
{103} {} {?}

# (Cook nuci s³owa z filmu „Dezerterow” z 1950 roku)
{110} {} {ˆ Fasola... fasola... fasola... fasola... ˆ}
{111} {} {ˆ Wszyscy w Morfleet s¹ przyjaŸni i silni. ˆ}
{112} {} {ˆ Poniewa¿ jedz¹ kotlety, makarony i pierogi... ˆ}
{113} {} {ˆ ...A Krainy jedz¹ œmieci. ˆ}
{114} {} {ˆ Morflot dostaje pstr¹ga pierwszej klasy. ˆ}
{115} {} {ˆ ...I wy³adunki - jedna fasola. ˆ}
{116} {} {ˆ Fasola... Fasola... Fasola... Fasola... ˆ}
{117} {} {ˆ A ta kie³basa jest twarda jak d³oñ paladyna. ˆ}
{118} {} {ˆ Morflot serwuje z serwetkami i sol¹... ˆ}
{119} {} {ˆ ...I jedna fasola na ³adowanie. Jedna fasola. ˆ}

{200} {} {Na-na-na... Lu-boo-doo... khe-khe-khe... Ugh.}
{201} {} {Hej.}
{202} {} {Ach! Co? Co? Nie strasz mnie tak.}
{203} {} {Co robisz?}
{204} {} {Ja? Spiewam...}
{205} {} {Czy to w³aœnie nazywasz œpiewaniem?}
{206} {} {Nie podoba ci siê?}
{207} {} {Naprawdê tego nie lubiê.}
{208} {} {Niestety nie mogê zmieniæ swojego g³osu... Kim jesteœ? Nie widzia³em ciê tu wczeœniej.}
{209} {} {Nie twoja sprawa, szeregowy. Pracuj dalej.}
{210} {} {Czy to wa¿ne? Najwa¿niejsze, ¿eby tobie siê podoba³o. Jestem tu tylko przelotnie.}
{211} {} {Dok³adnie. I kim jesteœ? Nie widzia³em ciê tu wczeœniej.}
{212} {} {Ostatnio s³u¿y³em w Bractwie.}
{213} {} {Och, gratulacje. Czy mogê kontynuowaæ pracê?}
{214} {} {Oczywiœcie kontynuuj, szeregowy.}
{215} {} {Cywil. Mam pozwolenie.}
{216} {} {Có¿, to nie moja sprawa. Ale w kuchni nie mog¹ przebywaæ ¿adne obce osoby.}
{217} {} {Oczywiœcie, zaraz wyjdê.}
{218} {} {Nie rozpraszaj nikogo.}
{219} {} {Do zobaczenia ponownie.}

{220} {} {Akolita Corwin, sir... Och, to ty.}
{221} {} {Czy naprawdê masz poœwiadczenie bezpieczeñstwa?}
{222} {} {Masz szczêœcie, mo¿esz iœæ na pustkowia, kiedy tylko chcesz. Ja czekam na urlop od stu lat.}
{223} {} {Na-na, na-na, boo-boo, boo-boo...}
{224} {} {Fasola... fasola... fasola... fasola...}
{225} {} {Wys³ali ciê ze szpitala? Nie lubiê tych wszystkich igie³.}
{226} {} {"Zyj, Corwin!", "Umyj siê, Corwin!", "Boo boo boo, Corwin". Wielcy szefowie...}

{229} {} {Hej... to znaczy... Akolita Corwin, sir!}
{1229} {} {Witam... mam na myœli... Akolita Corwin, proszê pani!}

{230} {} {Powiedziano mi, ¿e mogê tu zjeœæ obiad. Jestem nowicjuszem.}
{231} {} {Ach, witamy na statku. Oto twój lunch. Ale za dok³adkê musisz zap³aciæ. Takie zasady.}
{232} {} {Dziêkujê, nowicjuszu.}
{233} {} {Myœla³em, ¿e Bractwo bêdzie mia³o lepsze jedzenie ni¿ przydro¿na restauracja.}
{234} {} {Czy mogê kupiæ od ciebie jedzenie?}
{235} {} {Nie ma mowy. Bez zamówienia mogê sprzedaæ nadwy¿kê tylko pracownikom Bractwa.}
{236} {} {Przepraszam. NajwyraŸniej nic nie mo¿esz na to poradziæ.}
{237} {} {W³aœnie straci³eœ okazjê do wzbogacenia siê. Bywaj.}
{238} {} {Daj spokój, musisz mieæ jak¹œ nadwy¿kê nadwy¿ki.}
{239} {} {S³uchaj, ta sprawa mo¿e narobiæ nam k³opotów. Nie jesteœ nawet z Bractwa. Wynoœ siê st¹d, nie przeszkadzaj mi w gotowaniu.}
{240} {} {G³upcze, w³aœnie przegapi³eœ okazjê do wzbogacenia siê. Zegnam.}
{241} {} {}
{242} {} {Dawaj, nikt nie zauwa¿y, ¿e brakuje kilku misek zupy, a ty zarobisz kapsle.}
{243} {} {Wow, by³o warto. Nie mogê wiele kupiæ za moj¹ pensjê. Najwa¿niejsze jest to, ¿e nikt nie wie.}
{244} {} {Oczywiœcie. Ka¿dy bêdzie mia³ swój w³asny sekret, Corwin.}
{245} {} {W porz¹dku. Mam pozwolenie.}
{246} {} {Có¿, to inna sprawa.}
{247} {} {Dziêki.}

{250} {} {Jak siê nazywasz, szeregowy?}
{251} {} {Alvin Corwin. Obecnie kucharz.}
{252} {} {Praca w kuchni to wstyd dla paladyna.}
{253} {} {Nie, nie jestem paladynem. Nie zdecydowa³em siê jeszcze na przydzia³.}
{254} {} {Jesteœ paladynem czy skryb¹?}
{255} {} {Jestem kucharzem. Nie zdecydowa³em siê jeszcze na przydzia³.}
{256} {} {To dlaczego nie jesteœ w szkole?}
{257} {} {Mam karê. Opuœci³em poranne treningi, poniewa¿ ca³y ranek szuka³em sier¿anta.}
{258} {} {Oczywiœcie. Kto umieœci³by w kuchni dobrego ¿o³nierza?}
{259} {} {Zartujesz sobie ze mnie? Chcia³em poprosiæ o pozwolenie na urlop, wiêc ca³y ranek szuka³em sier¿anta, ale nigdzie go nie by³o.}
{260} {} {Co jest takiego trudnego w nauce?}
{261} {} {Potrzebujê trochê odpoczynku. Sto lat temu by³em na urlopie.}
{262} {} {Co za niesprawiedliwoœæ. Wiêc wpad³eœ w ten ba³agan nie z w³asnej winy?}
{263} {} {Dok³adnie. Pilnie potrzebujê urlopu, ale nikt nie móg³ podpisaæ petycji. Wiêc przebieg³em siê po ca³ym statku.}
{264} {} {A jeœli ja poproszê o urlop na l¹dzie dla Ciebie? Co za to dostanê?}
{265} {} {Potrafisz to zrobiæ? Och, w takim razie zap³acê prowiantem. Albo podzielê siê moimi kapslami.}
{266} {} {Rozumiem. Urlop masz ju¿ w kieszeni.}
{267} {} {W rzeczywistoœci, nie mam ¿adnych powi¹zañ ani uprawnieñ. Nie jestem pewien, czy mogê to za³atwiæ.}
{268} {} {Mogê zdobyæ dla ciebie ten urlop. A przynajmniej spróbujê.}
{269} {} {Potrafisz to zrobiæ? Jesteœ moj¹ ostatni¹ nadziej¹.}
{270} {} {Nadal mo¿esz spróbowaæ.}
{271} {} {Jeœli o tym pomyœlê, z trudem mogê to zrobiæ. Zegnaj.}
{272} {} {O karcie urlopowej.}
{273} {} {Uda³o siê?}
{274} {} {Nie, szczerze mówi¹c.}
{275} {} {Dlaczego potrzebujesz urlopu na l¹dzie? Wokó³ jest tylko pustynia.}
{276} {} {Nie, na zachodzie jest osada Casa Nueva. Nasi s¹ tam na patrolu, a czasem odpoczywaj¹. Fajne miejsce, du¿o ludzi, œwie¿e powietrze. Nie jak ten zardzewia³y statek. W po³udnie jest tak duszno, ¿e chcia³byœ nosiæ tylko majtki.}
{277} {} {Rozumiem. Có¿, z przyjemnoœci¹ zostanê.}
{278} {} {Myœlê, jak uzyskaæ urlop? Jakieœ pomys³y?}
{279} {} {Ale JAK mam ciê zwolniæ?}
{280} {} {Ale dlaczego mia³byœ iœæ na opuszczony brzeg?}
{281} {} {Gdybym wiedzia³, to zrobi³bym to sam dawno temu. Generalnie takie rozkazy mog¹ byæ podpisane tylko przez wy¿szych stopniem. Mo¿esz te¿ zdobyæ pozwolenie na misjê od jednej z jednostek. Ale niedoœwiadczeni ludzie, tacy jak ja, nieczêsto s¹ wysy³ani na takie *misje*.}
{282} {} {Rozkaz wydany. Masz wolne przez nastêpne cztery dni.}
{283} {} {Wow, co za wiadomoœæ! Nie ¿artujesz?}
{284} {} {To prawda. Chêtnie pomagam ludziom.}
{285} {} {Czemu od razu ¿art? Mówiê powa¿nie. Ale za wszystko trzeba zap³aciæ.}
{286} {} {Nie potrzebujê kapsli na pla¿y. Pozwolisz mi podzieliæ siê amunicj¹? I tak te przebijaj¹ce zbroje nigdy mi siê nie przyda³y.}
{287} {} {Dobrze, znajdê dla nich zastosowanie.}
{288} {} {Dziêki. Pójdê do sier¿anta, niech wybuchnie zazdroœæ.}
{289} {} {ChodŸ, mi³ej podró¿y.}

{300} {} {Co robisz szeregowy?}
{301} {} {Gotujê fasole, sir.}
{1301} {} {Gotujê fasole, proszê pani.}
{302} {} {Fasole? I to wszystko?}
{303} {} {No tak. Nowicjuszom nie daje siê dobrych racji. Paladyni jedz¹ najlepsze jedzenie.}
{304} {} {Czy to dlatego wszyscy tutaj wygl¹daj¹ na nieszczêœliwych?}
{305} {} {Maj¹ tylko to. I muszê to ugotowaæ. Oczywiœcie dostarcza siê nam ryby, miêso i m¹kê kukurydzian¹. Ale zdarzaj¹ siê przerwy w dostawach i czasami brakuje zapasów. Ech, chcia³bym usma¿yæ dobry stek.}
{306} {} {Có¿, chodzê w ró¿ne miejsca.}
{307} {} {Hej, mo¿esz dostaæ trochê kawy? Zrzucilibyœmy siê i zap³acilibyœmy za ka¿d¹ puszkê.}
{308} {} {Ok. Jeœli j¹ znajdê, przyniosê Ci.}
{309} {} {Ciê¿ko o to w tym czasach. Chyba nie znajdê nawet jednej puszki.}
{310} {} {Nie mogê ci pomóc. Bywaj.}
{311} {} {Zobacz, co mam. To puszka prawdziwej kawy.}
{312} {} {Super! Sprzedaj mi to. Mogê zap³aciæ }
{313} {} { kapsli na puszkê.}
{314} {} {Nie, nie. Ja te¿ tego chcê. Nie oddam tego.}
{315} {} {Dochodowa wymiana. W osadach za kawê p³aci siê mniej.}
{316} {} {Dziêki. Bêdzie wiêcej - przynieœ to prosto do mnie.}
{317} {} {Ok.}
{318} {} {WeŸ to za darmo. Chcê podziêkowaæ Bractwu Stali.}
{319} {} {Dziêki. Wszyscy nasi ludzie doceni¹ tê hojnoœæ.}
{320} {} {Proszê. Wszystko dla was.}
{321} {} {Robiê makaron, sir.}
{1321} {} {Robiê makaron, proszê pani.}
{322} {} {Makaron? I to wszystko?}