{100} {} {Widzisz Raymonda.}
{101} {} {Widzisz kwatermistrza Bractwa Stali. Przegl¹da listy przez du¿e okulary przymocowane do jego czo³a.}
{102} {} {To nie jest czas na rozmowy z miejscowymi.}
{103} {} {?}
{104} {} {Cholera, mówi³em ci ju¿ sto razy - nie wchodŸ do magazynu w zbroi wspomaganej! Jesteœ jak szpon œmierci w sklepie z ceramik¹.}

# Plywajace repliki
{110} {} {Listy amunicji nale¿y uzupe³niæ.}
{111} {} {Nastêpnym razem osobiœcie sprawiê, ¿e zmyjesz ten brud.}
{112} {} {Bractwo Stali docenia mój podpis.}
{113} {} {Ta rdza krêci mnie w nosie.}
{114} {} {Skutecznoœæ granatów jest mocno przesadzona.}
{115} {} {}
{116} {} {}
{117} {} {}
{118} {} {}
{119} {} {}

#Dialog
{200} {} {Och, nowa twarz na statku. To zawsze coœ interesuj¹cego. Czy mogê ci w czymœ pomóc?}
{201} {} {Nie dzisiaj. Mo¿e innym razem.}
{202} {} {Có¿, mo¿e. Powiedz mi, co to za miejsce?}
{203} {} {To jest g³ówny magazyn statku. A ja jestem jego kwatermistrzem. Nazywam siê Rycerz Raymond.}
{204} {} {Jestem zaszczycony mog¹c ciê poznaæ Rycerzu Raymond.}
{205} {} {Rozumiem.}
{206} {} {Och, tylko magazyn. Wydawa³o mi siê, ¿e bêdzie tu coœ interesuj¹cego.}

{210} {} {Wiêc w czym mogê pomóc?}
{211} {} {Wrócê póŸniej.}
{212} {} {Czy masz coœ przeciwko, jeœli zadam kilka pytañ?}
{213} {} {O czym? I czemu?}
{214} {} {Tak tylko z ciekawoœci.}
{215} {} {Jak mogê ci pomóc bracie?}
{1215} {} {Jak mogê ci pomóc, siostro?}

{220} {} {Mam tu taki medal. Wiesz cokolwiek o tym?}
{221} {} {Pozwól mi zobaczyæ... Operacja Anchorage? Oczywiœcie, by³o to jedno z najbardziej uderzaj¹cych zwyciêstw Stanów Zjednoczonych przed Wielk¹ Wojn¹. Si³y zbrojne Ameryki przyst¹pi³y do bitwy z czerwonymi najeŸdŸcami na Alasce. Co prawda, nie uchroni³o nas to przed bombardowaniem nuklearnym.}
{222} {} {Wygl¹da na to, ¿e to nie jest tylko historia dla ciebie.}
{223} {} {Bractwo Stali sk³ada siê z potomków wojska. W³¹cznie z tymi, którzy brali udzia³ w tej bitwie. U¿ywamy pancerza wspomaganego, który po raz pierwszy zosta³ u¿yty podczas operacji w Anchorage. S³uchaj, nie potrzebujesz tego medalu, prawda? Chcê go dostaæ dla historii. Czego chcesz zamiast tego?}
{224} {} {Jaki medal? Poka¿ mi.}
{225} {} {Przyniosê to póŸniej.}
{226} {} {350 kapsli.}
{227} {} {No oczywiœcie. Oto kapsle.}
{228} {} {Dziêki.}
{229} {} {WeŸ to za darmo. Chcê tylko pomóc Bractwu Stali w ich trudnym zadaniu.}
{230} {} {Myœlê, ¿e towarzysze broni to doceni¹. Dziêkujê Ci. Jeœli potrzebujesz któregoœ z moich produktów, mo¿esz liczyæ na niewielki rabat.}
{231} {} {To ca³kiem nieŸle. Bêdê o tym pamietaæ.}
{232} {} {Naprawdê potrzebujê podnieœæ swoje umiejêtnoœci strzelania z broni palnej. Przed nami ciê¿kie bitwy.}
{233} {} {Wiêc pomo¿e ci strzelanie na naszej strzelnicy z broni¹ treningow¹. Zgadzam siê na wszystko.}
{234} {} {Czego potrzebujesz...}
{235} {} {Kwatermistrz obni¿y³ koszt swoich towarów o 10%.}

{240} {} {Czy mo¿esz mi opowiedzieæ o Bractwie?}
{241} {} {Porozmawiaj o tym z uczonymi skrybami lub genera³em. Jeœli nie chc¹ rozmawiaæ, to z pewnoœci¹ ja te¿ nie powinienem.}
{242} {} {Ok. Znajdê kogoœ innego.}
{243} {} {Ok, czy mo¿emy porozmawiaæ o czymœ innym?}
{244} {} {Przypomnij mi, co to za miejsce?}
{245} {} {To jest g³ówny magazyn statku. A ja jestem jego kwatermistrzem. Nazywam siê Rycerz Raymond.}
{246} {} {Dziêki, teraz to sobie zapamiêtam.}
{247} {} {Co to za dziwne naboje 10 mm? To pierwszy raz, kiedy widzê takie.}
{248} {} {To jest nasz w³asny wynalazek. Pocisk w nich sk³ada siê ze szczególnie mocnego stopu i ma niezwyk³y, penetruj¹cy kszta³t. Doskona³y przeciwko dobrze chronionym wrogom. Chocia¿ tacy wrogowie s¹ rzadcy, lepiej mieæ przy sobie magazynek w rezerwie.}
{249} {} {Rozumiem.}

{250} {} {Czy mogê zobaczyæ, co masz?}
{251} {} {Oczywiœcie. Wszystkiego najlepszego.}
{252} {} {Chcesz handlowaæ? Bractwo nie jest zainteresowane jednorazowymi spontanicznymi wymianami. Preferujemy karawany sta³e. Ale jeœli twoje rzeczy s¹ dla nas przydatne, mogê coœ zaoferowaæ.}
{253} {} {Coœ? Potrzebujê naprawdê dobrej broni!}
{254} {} {Dowódcy uwa¿aj¹, ¿e dobra broñ i materia³y wybuchowe mog¹ byæ skierowane przeciwko nam. Przykro mi, ale bêdziesz musia³ zadowoliæ siê tym, co oferujê, dopóki nie zdobêdziesz wiêkszego zaufania.}
{255} {} {Jak zwykle siê na to zas³uguje?}
{256} {} {Oczywiœcie, biznes.}
{257} {} {Rozumiem.}
{258} {} {Ok, chodŸmy.}
{259} {} {O karawanach. Mogê te¿ zostaæ karawan¹.}
{260} {} {Mo¿e, ale potrzebujemy sta³ych dostawców.}
{261} {} {Nie dasz siê nabraæ...}
{262} {} {Mam wielu partnerów handlowych w ca³ej Arizonie. Mogê tu przyci¹gn¹æ wiele dobrych karawan.}
{263} {} {Serio tak jest? Có¿, uda³o ci siê mnie przekonaæ. Byæ mo¿e umieszczê Ciê na liœcie naszych dostawców.}
{264} {} {Dziêki.}
{265} {} {W porz¹dku. Mam pozwolenie od samego genera³a.}
{266} {} {Rzeczywiœcie. Poznajê to pismo, mo¿esz liczyæ na pe³ny asortyment.}
{267} {} {Dziêki.}
{268} {} {No dalej, Raymond. Wszyscy tutaj wiedz¹, ¿e mo¿na mi zaufaæ.}
{269} {} {Hmm... Ok, umieszczê Ciê na naszej liœcie dostawców.}
{270} {} {Dziêki.}
{271} {} {W porz¹dku. Mam pozwolenie od najwy¿szego urzêdnika.}
{272} {} {W porz¹dku. Mam pozwolenie od dowódcy patrolu.}
{273} {} {W³aœnie straciliœmy tam jednego z naszych ¿o³nierzy. Porozmawiaj o tym z szefem patroli przy wejœciu na statek.}
{274} {} {Dobrze.}
{275} {} {Znalaz³em ten nieœmiertelnik w ruinach Inferno.}

{280} {} {Natkn¹³em siê na nieœmiertelnik Bractwa Stali. Co z nim zrobiæ?}
{281} {} {Ka¿dy taki symbol mówi o upad³ym bracie lub siostrze. Smutny los. Powiedz mi, w jaki sposób wszed³e³ w posiadanie tego tokenu, a odkupiê go za 10 kapsli.}
{282} {} {Byæ mo¿e kapsle siê przydadz¹.}
{283} {} {WeŸ to za darmo. Nie chcê zarabiaæ na czyjejœ tragedii.}
{284} {} {Dziêki. Ka¿dy nieœmiertelnik jest dla nas wa¿ny.}
{285} {} {Rozumiem. Ale wci¹¿ mam pytania.}
{286} {} {Proszê.}
{287} {} {Genera³ Dixon obieca³ nagrodê za dostarczenie raportu.}

{288} {} {Tak, zgadza siê. Nakaz na twoje imiê zosta³ ju¿ wydany. Twoja nagroda wynosi 250 kapsli plus trzy œrodki pobudzaj¹ce i dwa antyrady. Odbierz i podpisz.}
{289} {} {Dziêki.}

{290} {} {Czy masz coœ z granatnikiem?}
{291} {} {Tak, jest jeden egzemplarz. Dos³ownie jeden. Oddam za }
{292} {} { kapsli.}
{293} {} {To na pewno zwiêkszy moje szanse na prze¿ycie. Biorê to. Oto kapsle.}
{294} {} {Jeszcze nie.}

{300} {} {Myœlê, ¿e powinienem dostaæ tutaj sprzêt.}
{301} {} {Dobrze. Witamy w Bractwie, debiutancie.}
{302} {} {Do czego mam prawo?}
{303} {} {Twój sprzêt ró¿ni siê w zale¿noœci od specyfikacji i rangi. Wszystko, co nie bêdzie nale¿a³o do zestawu us³ug, bêdziesz musia³ wykupiæ lub b³agaæ o okreœlone zadania. Oczywiœcie mój magazyn jest teraz dla Ciebie ca³kowicie otwarty, a ceny s¹ znacznie ni¿sze ni¿ w przypadku cywilów. Wiêc jakiego zestawu sprzêtu potrzebujesz?}
{304} {} {Czy mo¿emy od³o¿yæ ten problem na chwilê? Muszê coœ wyjaœniæ. PA.}
{305} {} {Pakiet skryby.}
{306} {} {Swietnie. Oto twoje rzeczy: pistolet laserowy z zapasem baterii, dekoder, licznik Geigera. Odbierz i podpisz.}
{307} {} {Pakiet Paladyna.}
{308} {} {Lubisz du¿e pistolety, prawda? M³odzi ludzie czêsto chc¹ zostaæ paladynami. Oto twoja broñ: LKM, skrzynka z amunicj¹ i zbroja bojowa. Odbierz i podpisz.}
{309} {} {Pakiet rycerski.}
{310} {} {Och, wiêc ty i ja robimy w tej samej bran¿y, bracie. Bardzo dobrze. Oto twój sprzêt: wkrêtak elektryczny, super m³ot i gumowe buty. Odbierz i podpisz.}
{311} {} {Zestaw zwiadowcy.}
{312} {} {M¹dry wybór, bior¹c pod uwagê, ¿e te¿ jesteœ z pustkowi... Och, przepraszam, nie chcê ciê uraziæ. Oto twój sprzêt: Wyrzutnia pocisków, Shock Gauntlet, Stealth Boy. Odbierz i podpisz.}
{313} {} {Dziêkujê Rycerzu Raymond.}
{314} {} {Czy to wszystko? Ok, to wystarczy.}

{320} {} {Wygl¹da na to, ¿e to tutaj muszê zwróciæ utracony pancerz wspomagany, tak?}
{321} {} {Och, ten, na który czekaliœmy? Czy on jest tutaj z tob¹?}
{322} {} {Jest w pobli¿u. Poczekaj, a¿ wejdê w nim na statek.}
{323} {} {Tak, jest. Zwracam to wam, prawowitym w³aœcicielom.}
{324} {} {Ach, spójrz, jak ten chrom lœni w œwietle lampy! Nie ma nic piêkniejszego wœród starych technologii ni¿ ta machina wojenna... Tak, i dziêkujê za pomoc. Bractwo docenia twój czyn.}
{325} {} {Niestety, bateria trochê siê wyczerpa³a w ruinach Inferno.}
{326} {} {Rozumiem. Nic z³ego. Uszkodzenie mo¿na naprawiæ, chocia¿ proces naprawy mo¿e zaj¹æ kilka tygodni.}
{327} {} {A jeœli bêdê potrzebowaæ ponownie tej zbroi?}
{328} {} {Z pewnoœci¹ jesteœmy wdziêczni za jej powrót. Ale ta zbroja jest w³asnoœci¹ Bractwa Stali. I nie masz do niej prawa. Jednak genera³ mo¿e wzi¹æ pod uwagê twoje zas³ugi i wydaæ pozwolenie. Porozmawiaj z nim. W miêdzyczasie muszê wykonaæ kilka napraw. Do diab³a, co za g³upiec zerwa³ tê czeœæ...}
{329} {} {Twoje imiê ju¿ dotar³o. Mo¿esz skorzystaæ ze swojego œwiêtego prawa do noszenia zbroi wspomaganej... KIEDY skoñczê j¹ naprawiaæ. Do diab³a, co za debil urwa³ tê czêœæ...}
{330} {} {Wpadnê za kilka tygodni.}
{331} {} {Chcê tylko wiedzieæ, czy mogê z niego skorzystaæ po zwróceniu?}
{332} {} {Co to za g³upie pytanie? To w³asnoœæ Bractwa Stali. Aby z niego korzystaæ, musisz mieæ pozwolenie lub byæ cz³onkiem naszego bractwa. Ale najpierw musisz ZWROCIC zbrojê do magazynu. Smia³o, nie traæ czasu.}
{333} {} {Tak jest. Oddajê j¹ prawowitym w³aœcicielom.}
{334} {} {Poczekaj, a¿ wejdê w niej na statek.}
{335} {} {Och, czy to ten, który zosta³ zabrany przez ruiny Inferno? W porz¹dku. ChodŸ, wyczo³gaj siê z tego, nie mogê siê doczekaæ jego sprawdzenia.}
{336} {} {To zajmie trochê czasu, mo¿e trochê porozmawiamy?}
{337} {} {Och, oczywiœcie, chêtnie pozbêdê siê tej pow³oki.}

{340} {} {Czy zakoñczy³eœ naprawê tego pancerza wspomaganego?}
{341} {} {Nie. To nie jest takie proste, jak siê wydaje.}
{342} {} {Ok.}
{343} {} {O tak. Wygl¹da jak nowy!}
{344} {} {Czy mogê go zabraæ?}
{345} {} {Potrzebujê tej zbroi do pewnych celów.}
{346} {} {Co to za g³upie pytanie? To w³asnoœæ Bractwa Stali. Aby z niej skorzystaæ, musisz mieæ pozwolenie lub byæ cz³onkiem naszego bractwa.}
{347} {} {Ok...}
{348} {} {Twoje imiê zosta³o ju¿ wys³ane, mo¿esz korzystaæ ze swojej œwiêtej mocy, aby nosiæ zbrojê wspomagan¹.}
{349} {} {Dziêki... Tak, teraz wygl¹da lepiej.}