{100} {} {Widzisz instruktora.}
{101} {} {Widzisz m³odszego paladyn. Przy ka¿dej okazji wykrzykuje komendy i dmucha w gwizdek.}

{200} {} {Cywil? Od³ó¿ rozmowy na bok!}
{201} {} {Cokolwiek powiesz.}
{202} {} {Czekaj. Co to za miejsce?}
{203} {} {Oczywiœcie to jest sala szkoleniowa! Po co masz g³owê, g³upku?}
{204} {} {Potrzebujesz g³owy, ¿eby uderzyæ, sir.}
{205} {} {Idiota! WyjdŸ na korytarz i nie wracaj!}
{1205} {} {Ty idioto! WyjdŸ na korytarz i nie wracaj!}
{206} {} {Cokolwiek powiesz, proszê pana...}
{207} {} {Och, rozumiem i szukam toalety...}
{208} {} {Wow, czy mogê wzi¹æ udzia³ w treningu?}
{209} {} {Czekaj, ja te¿ chcê trenowaæ.}
{210} {} {Idiota! To jest baza wojskowa, cywile w ogóle nie mog¹ siê tu pojawiaæ.}
{1210} {} {Ty idioto! To jest baza wojskowa i cywile w ogóle nie mog¹ siê tu pojawiaæ.}
{211} {} {Och, w takim razie idê. PA.}
{212} {} {Czy nie ma sposobu na obejœcie tych formalnoœci? Mam du¿o kapsli. Powiedzmy 500 sztuk.}
{213} {} {Hmm. W porz¹dku. Zobaczmy, kiedy bêdziesz mieæ doœæ, jaszczurko. Co chcesz poæwiczyæ?}
{214} {} {To jeszcze nie ma znaczenia. Najpierw zdobêdê kapsle.}
{215} {} {Strzelanie z ma³ej broni.}
{216} {} {Strzelanie z ciê¿kiej broni.}
{217} {} {Strzelanie z broni energetycznej.}
{218} {} {Techniki walki wrêcz.}
{219} {} {Techniki walki broni¹ bia³¹.}
{220} {} {Techniki rzucania granatami i ostrzami.}
{221} {} {Powinienem zrobiæ jedn¹ z sesji szkoleniowych. W koñcu jestem teraz paladynem Bractwa.}
{222} {} {Muszê zrobiæ jedn¹ z sesji szkoleniowych. Przecie¿ teraz jestem zwiadowc¹ Bractwa.}
{223} {} {Dla MNIE nadal jesteœ œmierdz¹cym frajerem, któremu nie mo¿na ufaæ z patykiem do mieszania gówna! A teraz stój spokojnie i wybierz swoj¹ specjalnoœæ, ¿o³nierzu!}
{1223} {} {Dla MNIE nadal jesteœ œmierdz¹c¹ szmat¹, której nie mo¿esz nawet zaufaæ z mopem! A teraz stój spokojnie i wybierz swoj¹ specjalnoœæ, ¿o³nierzu!}
{224} {} {Muszê skonsultowaæ siê z dowódc¹. Daj mi chwilê, sir.}
{225} {} {Nie jêcz, nie sikaj, nie wo³aj mamy! Mo¿esz ju¿ iœæ na liniê frontu. Odmaszerowaæ!}
{226} {} {Tak, proszê pana!}