{100} {} {Widzisz poszkodowanego.}
{101} {} {Widzisz ghula. Wygl¹da na to, ¿e bardzo go boli. Gdyby nie twój motor, biedak nie zosta³by ranny.}
{102} {} {Sk¹d masz prawo jazdy? Znalaz³eœ w paczce z chipsami?}
{1102} {} {Sk¹d masz prawo jazdy? Znalaz³aœ w paczce z chipsami?}
{103} {} {O cholera!}

{110} {} {O-o-o! Jak boli!}
{111} {} {Ups! Mój staw biodrowy!}
{112} {} {Czy ktoœ widzia³ mój woreczek ¿ó³ciowy?}
{113} {} {Mój krêgos³up! Mój krêgos³up!}
{114} {} {Lekarza...}
{115} {} {Czy ktoœ mo¿e mi pomóc?}
{116} {} {Dlaczego ci¹gle mi siê to przytrafia?}
{117} {} {Najpierw ciê¿arówka, potem pickup, a teraz motor...}
{118} {} {To staje siê norm¹...}
{119} {} {}

{200} {} {Och, jak to boli! Dlaczego ci¹gle jestem pod kolami?}
{201} {} {Och, przepraszam, wszystko w porz¹dku?}
{202} {} {W porz¹dku? Có¿... Kilka z³amanych krêgów, z³amane biodro, rozdarty pêcherz... Tak. Mam siê bardzo dobrze.}
{203} {} {Przepraszam, nie mia³em tego na myœli.}
{204} {} {Oczywiœcie, ¿e nie mia³eœ! Powiedzia³em tym dziwakom, ¿e potrzebne s¹ tutaj znaki drogowe. Ale nigdy nie s³uchaj¹! Jak wtedy, gdy przejecha³a mnie potê¿na ciê¿arówka Nuka-Coli. Zakrêtki do butelek by³y rozrzucone po ca³ej pustyni.}
{205} {} {To okropne.}
{206} {} {Wow! WyobraŸ sobie, ¿e ktoœ natkn¹³ siê na to na œrodku pustyni.}
{207} {} {Inaczej... Grrh! OU! Naprawdê nie chcê przerywaæ tej wspania³ej rozmowy, ale mimo to muszê jakoœ wstaæ. Pomo¿esz?}
{208} {} {Dobrze?}
{209} {} {Na pewno? Prawdopodobnie nie powinieneœ siê teraz ruszaæ...}
{210} {} {Och, nie martw siê. Wczeœniej czy póŸniej wszystko zroœnie siê samoistnie. Bêdzie w porz¹dku.}
{211} {} {Do widzenia.}
{212} {} {Ups...}
{213} {} {Co siê tak gapisz? Nie udzielisz mi pierwszej pomocy i oddychania usta-usta? W porz¹dku. Jakoœ wstanê bez ciebie.}
{214} {} {Dziêki Bogu. Wydawa³o mi siê, ¿e naprawdê Ÿle siê czujesz. Có¿, do zobaczenia póŸniej.}
{215} {} {Cholera, ledwo mogê siê ruszyæ! Nie, nie myœl, wcale nie jêczê. To nie jest najgorsza rzecz jaka mnie spotka³a. Jak wtedy, gdy przejecha³a mnie potê¿na ciê¿arówka Nuka-Coli. Zakrêtki do butelek by³y rozrzucone po ca³ej pustyni.}