{100} {} {Widzisz lekarza.}
{101} {} {Widzisz lekarza. Gdyby nie szata, nie by³byœ w stanie odró¿niæ go od zwyk³ego ¿o³nierza.}
{102} {} {Jeœli siê nie poœpieszê, to nie bêdê ju¿ potrzebowa³ lekarza.}
{103} {} {?}

{200} {} {(zaciera rêce, badaj¹c ciê uwa¿nie) Cywil? Nie pamiêtam kolejnoœci wszystkich rekrutów.}
{201} {} {Tak, nie s³u¿ê Bractwu.}
{202} {} {Mamy tu ambulatorium. I nie wolno mi s³u¿yæ cywilom bez odpowiedniego rozkazu.}
{203} {} {Przepraszam, ¿e przeszkadzam.}
{204} {} {Rozumiem. PA.}
{205} {} {Wiêc jesteœ rekrutem?}
{206} {} {Tak, jestem rekrutem. Nakaz rejestracji zosta³ ju¿ wystawiony.}
{207} {} {Ok. Bo inaczej wyrzuci³bym ciê ze szpitala. Cywile nie mog¹ tu wchodziæ.}
{208} {} {Potrzebujê tylko leczenia.}
{209} {} {Nie bêdziesz tego potrzebowaæ. I tak wychodzê.}

{210} {} {Co siê sta³o?}
{211} {} {Nic. Do zobaczenia doktorze.}
{212} {} {Czy coœ siê sta³o?}

{213} {} {Czy mogê zadaæ kilka pytañ?}
{214} {} {Nie. Stanowisko lekarza wojskowego nauczy³o mnie milczeæ w czasie pokoju. Z wyj¹tkiem oczywiœcie rozmów z wy¿szymi urzêdnikami. Musz¹ wiedzieæ wszystko o wszystkim.}
{215} {} {Ok doktorze, w takim przypadku poszukam innej osoby.}

{220} {} {Chcê porozmawiaæ o Akolicie Corwinie.}
{221} {} {A co z nim? Znowu ma k³opoty?}
{222} {} {On potrzebuje urlopu na l¹dzie.}
{223} {} {Co, znowu? Facet jest zbyt s³aby do tej pracy. Na pró¿no go zabrali ze sob¹. Powinien siedzieæ w bazie i czyœciæ broñ. Gdzie on w ogóle jest?}
{224} {} {Nawet nie wiem. Chcia³em tylko z kimœ o tym porozmawiaæ. PA.}
{225} {} {Myœla³em, ¿e mo¿esz podrasowaæ mu kartê zdrowia.}
{226} {} {Móg³bym. Ale dlaczego mia³bym to zrobiæ?}
{227} {} {Nie wiem. Przepraszam, ¿e rozpraszam ciê drobiazgami. Bywaj.}
{228} {} {Có¿, mogê dostaæ lekarstwa. Prawdopodobnie czegoœ Ci brakuje.}
{229} {} {Ok. Przynieœ piêæ u¿ywek lub jeden z wojskowych narkotyków, a wtedy twój przyjaciel dostanie ode mnie bilet.}
{230} {} {Przemyœlê tê propozycjê.}
{231} {} {Oto piêæ stymulantów.}
{232} {} {Mogê podzieliæ siê psycho.}
{233} {} {Mam wygrzew.}
{234} {} {Wystarczy. Dobry interes.}
{235} {} {Uszczêœliwiê akolitê.}

{240} {} {Czeœæ doktorku. Niedawno zosta³em przydzielony do jednostki rozpoznawczej Bractwa.}
{241} {} {Ok, œwietnie. To znaczy tyle, ¿e teraz mam wiêcej do roboty. Có¿, gratulujê awansu.}
{242} {} {Co jest nie tak ze zwiadowcami?}
{243} {} {Zwiadowcy s¹ najbardziej nara¿eni na promieniowanie i zatrucia. Dlatego najczêœciej spo¿ywasz leki, a nawet zabierasz je ze sob¹ w podró¿. A lekarstwa s¹ trudne do zdobycia w naszych warunkach. Szczególnie przeciw promieniowaniu.}
{244} {} {Dobra przestañ, czy nale¿y mi siê jakieœ lekarstwo?}
{245} {} {Antidotum, œrodek pobudzaj¹cy i coœ ekstra to zestaw przetrwania. U¿yj tego m¹drze lub jeszcze lepiej unikaj niebezpiecznych miejsc.}
{246} {} {Ok. Dziêki doktorze.}

{250} {} {Czy mo¿esz mnie wyleczyæ, doktorze?}
{251} {} {Nie wolno mi s³u¿yæ cywilom bez specjalnego rozkazu. W przeciwnym razie sami mo¿emy nie mieæ wystarczaj¹cej iloœci leków. Porozmawiaj z Wyznawcami Apokalipsy w Casa Nueva, ulecz¹ ka¿dego.}
{252} {} {Dziêki za wskazówki. Postaram siê nie umrzeæ, dopóki tam nie dotrê.}
{253} {} {Natychmiast sta³o siê dla mnie jasne, ¿e zwykli obywatele nic dla ciebie nie znacz¹. Zegnaj, doktorze.}
{254} {} {Lecz mnie, doktorze.}
{255} {} {Ju¿ dobrze. Lap teraz za karabin i wracaj na liniê frontu.}
{256} {} {Robi siê, doktorze!}
{257} {} {G³upi ¿art, m¹dry facet.}

{260} {} {Co to za krzyki, doktorze? Torturujesz kogoœ?}
{261} {} {Nie. To nasz dzielny ¿o³nierz, który oszala³. Powa¿ny przypadek z ostrym zaburzeniem psychicznym.}
{262} {} {Co mu dok³adnie dolega?}
{263} {} {Pacjent cierpi z powodu bezsennoœci i bólów g³owy. Twierdzi nawet, ¿e s³yszy g³osy w swojej g³owie... Dobra, chwileczkê. Nie mogê o tym rozmawiaæ z osobami z zewn¹trz. Chocia¿ sprawa jest naprawdê trudna.}
{264} {} {Mo¿e udaje?}
{265} {} {Co? Zeby ¿o³nierz Bractwa udawa³? Nie s¹dzê. Ale to nie jest wykluczone. Ostatnio wszyscy na naszym forcie zatêsknili za domem w Kalifornii.}
{266} {} {Jeœli nie mo¿esz sobie z tym poradziæ, ja spróbujê.}
{267} {} {Hmm, w innym przypadku da³bym ci lanie i wyrzuci³ za drzwi. Ale tego problemu nie da siê rozwi¹zaæ bez pomocy z zewn¹trz. Nie jestem psychologiem, ale co ty mo¿esz zrobiæ?}
{268} {} {Najpierw muszê porozmawiaæ z pacjentem. Daj mi piêæ minut, doktorze.}
{269} {} {Czy na pewno nie udaje?}
{270} {} {Co mu dolega?}
{271} {} {Prawdopodobnie samemu dowiesz siê, jak go wyleczyæ. Zegnaj, doktorze.}
{272} {} {Bell wydaje siê cierpieæ przez ciê¿k¹ traumê.}
{273} {} {Ju¿ to wiem. Ale co robiæ?}
{274} {} {Mówi³ o jakiejœ pustyni popio³ów. Co to znaczy?}
{275} {} {Hmm. Nawet ma to sens. W rzeczywistoœci choroba ujawni³a siê po jednym z wypadów na pustyniê. Porozmawiaj z jego towarzyszami w mesie, mo¿e oni potrafi¹ rozgryŸæ ten obraz.}
{276} {} {Dobra, do widzenia, doktorze.}
{277} {} {Bell uspokoi³ siê po twojej rozmowie. Nawet spa³ dobrze i jest wypoczêty. Co mu powiedzia³eœ?}
{1277} {} {Bell uspokoi³ siê po twojej rozmowie. Nawet spa³ dobrze i jest wypoczêty. Co mu powiedzia³aœ?}
{278} {} {Nic specjalnego. To tylko stara sztuczka psychoterapeutyczna.}
{279} {} {Oczywiœcie. Ciekawe. Chcia³bym móc tak potrafiæ, ale ja jestem bardziej od zranieñ i kontuzji. Wejœcie w podœwiadomoœæ jest dla mnie przera¿aj¹ce.}
{280} {} {Jeszcze nie wszystko stracone, doktorze.}
{281} {} {Zgadza siê. Lepiej pilnuj w³asnego nosa.}
{282} {} {Dziêki. Chcê równie¿ podzieliæ siê z tob¹ moim doœwiadczeniem medycznym. Proszê, weŸ w prezencie ten zestaw chirurgiczny i kilka œrodków pobudzaj¹cych.}
{283} {} {Dziêki doktorku. Zegnaj.}