{100}{}{Widzisz Paladyna Lathama.}
{101}{}{Widzisz krzepkiego, nieogolonego mê¿czyznê.}
{102}{}{Nie, nie teraz.}
{103}{}{?}

{200}{}{Zatrzymaj siê. Jest to teren zamkniêty, cywile nie maj¹ wstêpu do bazy.}
{201}{}{Cywile? Kim jesteœ, jak¹œ armi¹?}
{202}{}{Nie. Jesteœmy staro¿ytnym zakonem zwanym Bractwem Stali. Mimo, ¿e w bazie mamy dyscyplinê wojskow¹.}
{203}{}{Rozumiem. A ty kim jesteœ?}
{204}{}{To niesamowite. A z kim mam zaszczyt rozmawiaæ?}
{205}{}{Jestem Paladyn Latham, szef patrolu. Wiecej pytañ?}
{206}{}{Nie, proszê pana.}
{207}{}{Och, mam wiele pytañ. I mam nadziejê, ¿e na nie odpowiesz.}
{208}{}{Ok. A teraz powiedz mi, amigo, co ciê do nas sprowadza?}
{209}{}{Jestem z wioski na pó³nocy. Zaatakowali nas handlarze niewolników, a teraz próbujê ocaliæ wioskê...}
{210}{}{Jesteœ dok³adnie tym, czego potrzebujê. Moja wioska zosta³a zniewolona przez handlarzy niewolników i staram siê j¹ ocaliæ...}
{211}{}{Przepraszam, ale nie bêdê zawraca³ g³owy genera³owi jak¹œ wiosk¹. Po prostu nie mamy na to czasu.}
{212}{}{Nie, nie rozumiesz. To wy jesteœcie handlarzami niewolników. Zniszczê ca³y wasz zakon!}
{213}{}{Co siê dzieje? O co tyle zamieszania?}
{214}{}{Rozumiem. Widzê, ¿e mi tu nie pomog¹. Mogê odejœæ, paladynie?}
{215}{}{Znowu ty? Mówi³em ci - nie mamy czasu zajmowaæ siê twoj¹ wiosk¹. Przepraszam, ale nie mamy jeszcze na to czasu.}
{216}{}{Armia wroga nadci¹gaj¹ca z po³udnia, mutanty na zachodzie i ba³agan na wschodzie. Niedawno straciliœmy oddzia³ na pó³nocy i nie mo¿emy nawet wys³aæ tam ekipy ratunkowej.}
{217}{}{A jeœli ci pomogê, pozwolisz mi zobaczyæ genera³a?}
{218}{}{Mo¿esz pomóc? Ty nam? Haha, jakiœ ch³op chce pomóc Bractwu! S³yszeliœcie to? Dobra, zobaczmy, co siê stanie.}
{1218}{}{Mo¿esz pomóc? Ty nam? Haha, jakaœ wieœniaczka chce pomóc Bractwu! S³yszeliœcie to? Dobra, zobaczmy, co siê stanie.}
{219}{}{Wiêc co siê sta³o z oddzia³em?}
{220}{}{Na pó³nocy s¹ ruiny du¿ego miasta. Nazywamy je Inferno. Przez ruiny zbli¿a³ siê do nas konwój. Ale po³¹czenie zosta³o przerwane, teraz nic nie wiemy o losach oddzia³u.}
{221}{}{Rozumiem. Coœ jeszcze?}
{222}{}{IdŸ tam i dowiedz siê, co siê sta³o z naszymi braæmi. Ale b¹dŸ ostro¿ny, skrybowie mówi¹, ¿e s¹ tam miejsca o wysokim poziomie promieniowania.}
{223}{}{Dobrze. Zrobiê to.}
{224}{}{Zgoda. Ale nie myœl, ¿e nie wrócê, paladynie.}
{225}{}{M-mutanty... Ugh! Kiedy wy wszyscy spoczniecie?}
{226}{}{Daj mi minutê szefie, nie robiê nic z³ego.}
{227}{}{Och, to nie nast¹pi szybko, mój blady przyjacielu...}

{230}{}{Czego chcesz?}
{231}{}{Niczego. Do widzenia.}
{232}{}{Czego chcesz, wojowniku?}

{240}{}{Muszê dowiedzieæ siê wiêcej o Inferno.}
{241}{}{Nie mam zbyt wielu informacji. Skrybowie uwa¿aj¹ te ruiny za martwe i ostrzegaj¹ przed promieniowaniem w pobli¿u miejsca wybuchu nuklearnego.}
{242}{}{A co z konwojem?}
{243}{}{Kilku cz³onków Bractwa przewozi³o wa¿ny transport z Kalifornii. Powinni byli skontaktowaæ siê dawno temu.}
{244}{}{Dziêki, wystarczy.}
{245}{}{Rzeczywiœcie trochê informacji.}
{246}{}{Pozwól, ¿e poœwiêcê ci trochê wiêcej czasu, paladynie.}
{247}{}{Wiem, co siê sta³o w Inferno...}
{248}{}{...Skrybowie mieli racje - to PRZEKLETE miejsce. Dziêkujê Ci. Musisz porozmawiaæ z naszym genera³em.}
{249}{}{Samym genera³em?}
{250}{}{Bêdzie zainteresowany twoj¹ histori¹. Powiem stra¿nikom, ¿eby wpuœcili ciê na statek.}
{251}{}{Swietnie.}
{252}{}{To by³o tak od razu.}
{253}{}{Teraz zwolnij. Sk¹d wzi¹³eœ tê zbrojê wspomagan¹?}
{254}{}{To by³o okropne miejsce. Wiesz, na ulicach byli martwi ludzie, wszêdzie ruiny...}
{255}{}{Brzmi jak opis Inferno, przez które przeje¿dza³ nasz zagubiony konwój. Czy spotka³eœ ludzi, którzy nieœli tê zbrojê?}
{256}{}{Powiem ci, co wiem...}
{257}{}{Nic ci nie powiem. To jest moje trofeum i nie zrezygnujê z niego.}

{260}{}{Czy jest inny sposób, w jaki mogê pomóc Bractwu?}
{261}{}{Czy powiedzia³eœ coœ o armii wroga?}
{262}{}{Tak, do granicy meksykañskiej podobno zbli¿a siê armia wroga. Niewiele jeszcze wiemy o nowym wrogu. Nawet lokalizacja kwatery g³ównej wroga jest nam nieznana.}
{263}{}{Ale na po³udniu jest ogromna pustynia. Sk¹d mia³aby siê tam wzi¹æ baza wojskowa?}
{264}{}{To ta pustynia powstrzymuje armiê wroga przed zajêciem Arizony. Na zawsze ich nie zatrzyma.}
{265}{}{Mam nadziejê, ¿e poradzisz sobie z tym zagro¿eniem. Adios.}
{266}{}{Mogê siê dowiedzieæ. Zawsze chcia³em odwiedziæ te czêœci.}
{267}{}{Mogê zbadaæ po³udniowe ziemie, jeœli to pomo¿e.}
{268}{}{Wys³aliœmy kilku zwiadowców na po³udnie, ale ¿aden z nich nie wróci³. Nadal chcesz zaryzykowaæ? Wiêc idŸ przed siebie. Bractwo zap³aci za informacje o celach armii meksykañskiej.}
{269}{}{Wrócê, gdy czegoœ siê dowiem.}
{270}{}{W Hermosillo znajduje siê fort armii meksykañskiej...}
{271}{}{...Dobra robota! Twój zwiad da nam przewagê nad wrogiem, jeœli dojdzie do ofensywy.}
{272}{}{Hermosillo jest doœæ daleko na pustyni. W¹tpiê, ¿eby Meksykanie prêdko tu dotarli.}
{273}{}{Nie obchodzi mnie, dlaczego tego potrzebujesz. Po prostu quid pro quo.}
{274}{}{Proszê, to twoja nagroda. Cenimy dobrych zwiadowców.}
{275}{}{Dziêki.}
{276}{}{Ten koleœ twierdzi, ¿e jest ci winien zbawienie. Niczego nie zrozumia³em. Co mo¿esz mi powiedzieæ?}
{277}{}{Jack powiedzia³, ¿e potrzebujesz informacji o armii meksykañskiej.}
{278}{}{Wiêc uda³o ci siê tam pojechaæ? I czego siê dowiedzia³eœ?}
{1278}{}{Wiêc by³aœ tam? I czego siê dowiedzia³aœ?}
{279}{}{Szczerze, niczego, co by ci siê przyda³o. Jeœli wrócê tam ponownie, zdobêdê wiêcej informacji.}

{280}{}{Mam proœbê. Zabierz na nastêpny patrol akolitê Corvina.}
{281}{}{Corwina? Dlaczego akurat jego?}
{282}{}{Od dawna prosi o urlop na l¹dzie.}
{283}{}{Ach, o to chodzi. Nie, nie potrzebujemy balastu po drodze. Co wiêcej, s³owa takiego oszusta jak ty mnie nie przekonaj¹.}
{284}{}{Oszusta, tak? Dobra...}
{285}{}{Ach, o to chodzi. Nie, nie potrzebujemy balastu po drodze. A twój autorytet w tym miejscu niczego nie zmienia. Nie znam Ciê na tyle dobrze, by odpowiadaæ na Twoje proœby.}
{286}{}{Mogê to zrozumieæ...}
{287}{}{Ach, o to chodzi. Có¿, s³ucham próœb tych, którzy okazali siê godnymi wojownikami. Powiedz Corvinowi, ¿e zabiorê go na patrol do Casa Nueva i z powrotem. To nie jest urlop, ale wystarczy, ¿eby zaczerpn¹³ œwie¿ego powietrza.}
{288}{}{Dziêkujê, Paladynie Latham. Jesteœ bardzo pomocny.}
{289}{}{Tu jest holotaœma z danymi przechowywanymi na komputerze centrali. S¹ po hiszpañsku.}

{300}{}{Czy mogê zapytaæ, czym siê zajmujesz?}
{301}{}{Patrolowaniem terenu. Utrzymujemy porz¹dek w s¹siedztwie. Jakieœ pytania?}
{302}{}{Nie ma mowy, proszê pana.}
{303}{}{Tak, czy mogê ciê o coœ zapytaæ?}
{304}{}{Rozumiem. Ale wokó³ jest tylko pustynia. Jaki porz¹dek mo¿na tu utrzymywaæ?}
{305}{}{Czêsto chronimy trasy karawan. Na wybrze¿u s¹ pod nasz¹ opiek¹ wioski rybackie. Czasami proœby przychodz¹ z Casa Nueva. I tak, nawet w takiej dziczy s¹ bandyci. Zawsze b¹dŸ czujny.}
{306}{}{Zrozumia³em.}
{307}{}{Interesuj¹ce. Zabierzesz mnie na patrol?}
{308}{}{Wziêcie kogoœ z zewn¹trz na patrol jest zbyt ryzykowne. Nawet jeœli twoje intencje s¹ czyste.}
{309}{}{Ok. Mo¿e zmienisz zdanie, kiedy zrobiê coœ wa¿nego.}
{310}{}{Na pewno potrzebujesz doœwiadczonych najemników. Sam powiedzia³eœ, ¿e nie macie wystarczaj¹cej liczby osób.}
{311}{}{Tak, ale najwyraŸniej nie jesteœ odpowiedni¹ osob¹ do walki ramiê w ramiê z tob¹. Zacznij od czegoœ prostszego.}
{312}{}{Tak, ale... W sumie naprawdê nie mamy wystarczaj¹co du¿o ludzi na jedn¹ wielk¹ operacjê.}
{313}{}{Swietnie. Powiedz mi, co to za operacja.}
{314}{}{Zabierz mnie na patrol.}
{315}{}{Genera³ mówi³ o tobie. By³bym zadowolony, gdybyœ pomóg³ nam w jednej trudnej operacji.}
{316}{}{Oczywiœcie. Powiedz mi, o co chodzi.}
{317}{}{Czy jest inny sposób, w jaki mogê pomóc Bractwu?}
{318}{}{Po Hermosillo, jeszcze bardziej chcê pomóc Bractwu. Zabierzesz mnie na patrol?}
{319}{}{Tak, nie mamy wystarczaj¹co du¿o ludzi takich jak ty na jedn¹ wielk¹ operacjê.}
{320}{}{Swietnie. Uwa¿nie s³ucham.}
{321}{}{Ostatnio czêsto odwiedzaj¹ nas bandyci. Trzymali siê do tej pory g³ównych szlaków handlowych i lokalnych osad. Niedawno jednak obrabowali jedn¹ z naszych karawan, to Ÿle.}
{322}{}{Nie wiedz¹ jeszcze, z kim zadarli, Paladynie Latham.}
{323}{}{Musz¹ byæ silni, skoro potrafi¹ obrabowaæ karawanê Bractwa.}
{324}{}{Namierzyliœmy napastników w jednym z ich pustynnych obozów i chcemy ich odwiedziæ. Czas dorwaæ tych sukinsynów!}
{325}{}{Swietnie. Kiedy wyruszamy?}
{326}{}{IdŸ do punktu zbiórki, który zaznaczê na mapie. Tam spotka siê z tob¹ dowódca polowy Dobbs i na miejscu przeprowadzi odprawê. I przygotuj swój sprzêt przed wyjœciem. Powodzenia.}
{327}{}{Zrozumia³em. Ruszam natychmiast.}
{1327}{}{Zadanie jest jasne. Wyruszam natychmiast.}
{328}{}{Czy to w porz¹dku, jeœli trochê poczekaj¹? W porz¹dku.}
{329}{}{Zabierz mnie na patrol, Paladynie Latham.}

{330}{}{Oto mój raport z napadu na obóz bandytów...}
{331}{}{...Bardzo dobrze. Podobno by³ to tylko ma³y obóz polowy. Po ataku na karawanê bandyci rozdzielili siê. Druga grupa zabra³a towar do swojej g³ównej bazy. Uratowanie karawany to wa¿na misja, ale zdobycie skradzionego ³adunku jest jeszcze wa¿niejsze.}
{332}{}{Wiêc czeka mnie kolejna wyprawa?}
{333}{}{Nie wiemy, gdzie jest g³ówna baza bandytów. Ale podczas operacji pojawi³y siê informacje o du¿ej placówce na ruinach Kaborki. W ka¿dym razie ten posterunek musi zostaæ zniszczony. Mo¿emy tam równie¿ uzyskaæ informacje o lokalizacji g³ównej bazy.}
{334}{}{Wiêc jakie rozkazy, sir?}
{335}{}{IdŸ do komandora Dobbsa i przeka¿ moje nastêpne polecenie.}
{336}{}{Tak jest, Paladynie Latham.}
{337}{}{Jeœli nie ma innych tropów, warto zaryzykowaæ.}
{338}{}{Czy pyta³em ciê o opiniê? Ahem... Dobra, niewa¿ne. Naprawdê dobrze sobie radzisz. Bez Ciebie by³oby nam trochê trudniej.}
{339}{}{Wiêc jakie rozkazy, sir?}
{340}{}{...Wiêc obóz Kaborka zosta³ za³o¿ony tylko po to, by zaatakowaæ nasze trasy karawan. G³ówna baza bandytów znajduje siê w górach na wschodzie. Nic dziwnego, ¿e tyle czasu zajê³o nam jej znalezienie.}
{341}{}{Wiêc zamierzasz zaatakowaæ ich Sztab Generalny?}
{342}{}{Sztab Generalny? To tylko grupa wiejskich bandytów. Nazwij to legowiskiem lub po prostu dziur¹.}
{343}{}{Zrozumiano, sir.}
{344}{}{Daj dowódcy rozkaz wymarszu. Tym razem operacja bêdzie trudniejsza ni¿ poprzednie. Niech zbierze najlepszych. Ty te¿ zabierzesz swoj¹ najlepsz¹ broñ i zbrojê. Powodzenia ¿o³nierzu.}
{345}{}{Tak jest, Paladynie Latham.}
{346}{}{...Wiêc zlikwidowaliœmy ich g³ówny obóz. Bandyci zostali zniszczeni, przywódcy schwytani i skazani na œmieræ, ³upy wracaj¹ do zakonu. Gratulacje, wojowniku.}
{347}{}{Tak, pustkowia zapamietaj¹ to na d³ugo.}
{348}{}{To by³ wspania³y dzieñ zwyciêstwa! Wytêpiliœmy z³o na tych ziemiach i po raz kolejny pokazaliœmy œwiatu nasz¹ si³ê. Po pokonaniu bandytów drogi stan¹ siê bezpieczniejsze, a s³awa Bractwa rozprzestrzeni siê dalej na kontynent. Dziêkujê za pomoc.}
{349}{}{S³u¿ê Bractwu Stali!}
{350}{}{Chcê z³o¿yæ skargê. Usuniêto mnie z grupy zadaniowej!}
{351}{}{I s³usznie. Gdyby nie twoje wczeœniejsze zas³ugi, zosta³byœ stracony w najszerszym zakresie prawa. Teraz zrób najm¹drzejsz¹ rzecz, jak¹ mo¿esz i zniknij z naszej bazy.}
{352}{}{Tak, proszê pana.}
{353}{}{Gr!}
{354}{}{Mam z³e wieœci – komandor Dobbs zgin¹³ podczas operacji.}
{355}{}{To naprawdê z³e wieœci. To by³ nasz najlepszy dowódca polowy. Poza tym tylko on mia³ pe³ny obraz tego, co siê dzieje, bez niego pokonanie bandytów bêdzie znacznie trudniejsze.}
{356}{}{A co z operacj¹?}
{357}{}{Musimy wstrzymaæ operacjê i przegrupowaæ siê. Jeœli bêdziesz jeszcze potrzebny, damy znaæ. Do tego czasu mo¿esz odejœæ.}
{1357}{}{Musimy wstrzymaæ operacjê i przegrupowaæ siê. Jeœli bêdziesz jeszcze potrzebna, damy znaæ. Do tego czasu mo¿esz odejœæ.}
{358}{}{Tak jest, proszê pana.}

{360}{}{Potrzebujê sprzêtu, aby wzi¹æ udzia³ w nalocie.}
{361}{}{Twój sprzêt to twoja sprawa. Jedyne, co mogê zrobiæ, to uzyskaæ papier na towary kwatermistrza. Porozmawiaj z nim, mo¿e wymienisz swoj¹ broñ na coœ silniejszego.}
{362}{}{Dziêki.}