{100} {} {Widzisz Paula.}
{101} {} {Widzisz bardzo wychudzony mê¿czyznê.}

{200} {} {Mi³o ciê znowu widzieæ, przyjacielu. Pamiêtasz, jak ty i ja uciekaliœmy przed super mutantami? To by³o wspania³e.}
{1201} {} {Mi³o ciê znowu widzieæ, siostro. Pamiêtasz, jak ty i ja uciekaliœmy przed super mutantami? To by³o wspania³e.}
{201} {} {Tak, to by³y wspania³e czasy.}
{202} {} {Na dowód mojej wdziêcznoœci, masz tu trzy u¿ywki i ten pistolet laserowy na baterie. Powodzenia na pustkowiach.}
{203} {} {Dziêki. Powodzenia.}

{210} {} {Witamy na pok³adzie. Jak mogê ci pomóc?}
{211} {} {Nic, dziêki.}

{220} {} {Przypomnij mi, jak¹ masz rangê?}
{221} {} {Jestem Rycerz Paul. Wczeœniej by³em kierownikiem Dzia³u Badañ nad Broni¹ Energetyczn¹. Pózniej zosta³em wys³any w teren, aby pomóc paladynom. A potem z³apali mnie super mutanci.}
{222} {} {Czy mogê tu dostaæ broñ?}
{223} {} {Có¿, jeœli masz dobre kontakty, to czemu nie? Moja historia o tobie z pewnoœci¹ zwiêkszy³a twoj¹ reputacjê w szeregach Bractwa.}
{224} {} {Pracuj jak co dzieñ. Bywaj.}
{225} {} {Dziêki. Muszê iœæ.}
{226} {} {Muszê iœæ. Do widzenia.}
{227} {} {Dziêki, muszê ju¿ iœæ.}
{228} {} {Dziêki za informacje, proszê.}
{229} {} {}
{230} {} {Pomo¿esz mi uratowaæ moj¹ wioskê?}
{231} {} {Przepraszam, ale mam obowi¹zki w tym porcie. I mam ju¿ doœæ przygód.}
{232} {} {Czy masz jakieœ czêœci zamienne do mojego pancerza wspomaganego?}
{233} {} {Nie jestem w tym dobry. Daj zbrojê kwatermistrzowi, on mo¿e j¹ naprawiæ. Ale jeœli siê z nim nie dogadasz, nie odda tak ³atwo tej zbroi.}
{234} {} {Czy jest inna opcja?}
{235} {} {Mówi¹ ze Blacharze te¿ znaj¹ siê na technologii. Ale za tak¹ przys³ugê zedr¹ z ciebie fortunê.}
{236}{}{Spórz na ten karabin plazmowy. Czy mo¿na go jakoœ poprawiæ?}
{237}{}{To Winchester P94! Doskona³a broñ. Za ka¿dym razem podziwiam jego niezawodnoœæ i moc. Zawsze myœla³em, ¿e lepszy byæ nie mo¿e.}
{238}{}{Kontynuuj.}
{239}{}{Ale wiesz, by³ facet, który kiedyœ pokaza³ mi wyj¹tkowe ulepszenie swojego karabinu. Plazma w nim rozgrzewa³a siê szybciej niz zwykle. Myœlê, ¿e mogê zrobiæ to samo tutaj.}
{240}{}{Zrób to! Oto karabin.}
{241}{}{Nie, dziêkujê. Mo¿esz coœ zepsuæ...}
