{100} {} {Widzisz Christophera.}
{101} {} {Widzisz m³odego ¿o³nierza o bardzo smutnym i zamyœlonym spojrzeniu.}
{102} {} {Uwa¿aj na supermutantów, kolego.}

{200} {} {Czeœæ... uh... Nie wiedzia³em, ¿e na pok³adzie s¹ cywile... uh... Witamy na pok³adzie.}
{201} {} {Twoje myœli wydaj¹ siê byæ daleko st¹d.}
{202} {} {Dok³adnie. Dlaczego mamroczesz? Nie w sensie militarnym.}

{210} {} {Huh. Myœla³em o domu. M³odszy paladyn Christopher. Jak mogê s³u¿yæ?}
{211} {} {Przepraszam, ¿e przeszkadzam. Wyjdê.}
{212} {} {M³odszy Paladyn Christopher. Jak mogê s³u¿yæ?}

{220} {} {Mówi³eœ o domu. To daleko st¹d?}
{221} {} {Bunkier Lost Hills. Tam siê urodzi³em i wychowa³em. Jest w Kalifornii, daleko st¹d na pó³nocny zachód. Konwoje potrzebuj¹ w najlepszym przypadku miesi¹ca, aby pokonaæ tê odleg³oœæ. Ale zwykle du¿o wiêcej.}
{222} {} {Opowiedz mi o ¿yciu w bunkrze.}
{223} {} {Bunkier, mówisz? Cz³owiek rodzi siê, by ¿yæ pod s³oñcem, a nie w ciemnych piwnicach.}
{224} {} {Têskniê za uroczymi ciemnymi korytarzami i wisz¹cymi drutami. Tam w bunkrze mieliœmy wszystko, czego potrzebowaliœmy - po¿ywienie, energiê, a nawet rozrywkê. Tu jesteœmy wolni, ale ¿yjemy w strasznych warunkach.}
{225} {} {Nie lubisz Arizony?}
{226} {} {Zolnierz nie powinien narzekaæ na zmianê rozmieszczenia.}
{227} {} {Naga, dusz¹ca pustynia ci¹gn¹ca siê przez kilka mil od Phoenix? Nie, dziêkujê. Widzia³em ju¿ piaski w Kalifornii. Ale tam piaski by³y nasze w³asne, kochany. Tutaj wszystko jest obce. I pozostanie obce dla wiêkszoœci cz³onków Bractwa.}
{228} {} {Po prostu nie widzia³eœ ca³ego lokalnego piêkna.}
{229} {} {Wiêc w koñcu wyczo³ga³eœ siê ze swojego mrocznego lochu?}
{230} {} {Zosta³em wezwany do oddzia³u w³aœnie w momencie inicjacji. I gdy tylko otrzyma³em oficjalny tytu³, w tym czasie armia Mistrza zaczê³a zajmowaæ osady. Zosta³em rzucony do bitwy jak z nieba do piek³a.}
{231} {} {Czy bitwa by³a ciê¿ka?}
{232} {} {Czy Twoje nerwy nie s¹ zbyt s³abe, by s³u¿yæ?}
{233} {} {Gdyby nie szkolenie, nie móg³bym prze¿yæ w takich warunkach. Teraz jest ³atwiej. Najtrudniej by³o prze¿yæ utratê towarzyszy broni. Nadal mam to zdjêcie. Ca³a nasza eskadra przed wypadem do Nekropolis. Z siedmiu osób prze¿y³y tylko dwie - ja i dowódca.}
{234} {} {Kontynuuj.}
{235} {} {Nawet nie zaczynaj.}
{236} {} {Wyci¹gn¹³em go z ognia krzy¿owego super mutantów i zaci¹gn¹³em do œcieku w ostatniej chwili. Potem mutanci uderzyli rakiet¹ we w³az, a wyjœcie siê rozpad³o.}
{237} {} {Przykro mi.}
{238} {} {Po prostu mia³eœ szczêœcie.}
{239} {} {Tak przetrwaliœmy we dwoje. Ale inne grupy by³y zbyt zaanga¿owane w sprz¹tanie mutantów... Przepraszam, prawdopodobnie zmêczy³em ciê tymi historiami... W ka¿dym razie, nie jesteœ jednym z naszych, nie zrozumiesz... Ale ogólnie, dlaczego ja mówiê to Tobie? Dobra, powodzenia na pustyni czy cokolwiek tam robisz.}
{240} {} {Dziêki za historie. Czasami warto siê wygadaæ, nawet jeœli przed tob¹ stoi ktoœ obcy. Powodzenia, paladynie.}
{241} {} {Tak, nie rozumiem, jak ktoœ taki jak ty wci¹¿ ¿yje. Mam nadziejê, ¿e zabior¹ ciê z powrotem do ciemnego bunkra.}
