{100} {} {Widzisz paladyna.}
{101} {} {Krótkie w³osy, mocna zbroja, napompowane miêœnie - to paladyn Bractwa Stali.}

{200} {} {Zg³aszam sytuacjê: jest spokojnie.}
{201} {} {Jak s³u¿ba? Na razie jest tu cicho.}
{202} {} {Mi³o ciê widzieæ. Ale dlaczego nie jesteœ na patrolu?}
{203} {} {Chcesz iœæ na patrol? Porozmawiaj z Paladynem Lathamem.}
{204} {} {Zaden paladyn nie jest bardziej doœwiadczony ni¿ genera³ Dixon. Dlatego tu jest.}
{205} {} {Potrzebujemy ¿o³nierzy takich jak ty.}
{206} {} {Witamy w Bractwie.}
{207} {} {* Pozdrawia Ciê *}
{208} {} {}
{209} {} {}

{210} {} {IdŸ na pustkowia, dzikusie.}
{211} {} {Twoja ciekawoœæ mo¿e ciê drogo kosztowaæ.}
{212} {} {Nie spaceruj po bazie wojskowej, jakbyœ by³ u siebie w domu.}
{213} {} {Czy masz przepustkê? Twoje szczêœcie, ¿e j¹ masz...}
{214} {} {Daj mi powód, a wylecisz za burtê w mgnieniu oka.}
{215} {} {Moja taktyka jest prosta - uderz pierwszy zanim zostaniesz dŸgniêty w plecy.}
{216} {} {Jestem ciekawy, kto ciê wpuœci³?}
{217} {} {Czy cywile mog¹ teraz wêdrowaæ swobodnie po statku? Bar-rdak...}
{218} {} {Spocznij. Nie gryzê, dopóki nie dasz mi powodu.}
{219} {} {}

{220} {} {W naszym Bractwie mówi¹: „Dobry sojusznik to martwy sojusznik”.}
{221} {} {Czekaj, czy masz przepustkê? Có¿, poka¿ mi...}
{222} {} {Lepiej mnie nie wkurzaj, g³upi wieœniaku.}
{223} {} {Pojawiasz siê tutaj bez ostrze¿enia i domagasz siê odpowiedzi? Z twoj¹ g³ow¹ nie jest w porz¹dku.}
{224} {} {Zostañ tutaj i ani drgnij, dopóki nie dowiem siê, kim jesteœ i jak przedosta³eœ siê przez stra¿.}
{225} {} {No có¿, mamy tu szczura...}
{226} {} {Nie negocjujê z cywilami.}
{227} {} {Czy wartownik wie, ¿e jesteœ na statku?}
{228} {} {Co, osoba z zewn¹trz na pok³adzie? Dajê ci piêæ sekund na wyjaœnienia, w przeciwnym razie...}
{229} {} {Czy zdajesz sobie sprawê, ¿e jesteœ na okrêcie wojennym?}

{230} {} {Czy coœ siê sta³o?}
{231} {} {Musisz porozmawiaæ z naszym dowódc¹.}
{232} {} {To jest obszar zastrze¿ony. Nie mo¿esz tu byæ bez pozwolenia.}
{233} {} {Co doprowadzi³o ciê do Bractwa?}
{234} {} {Czy chcesz do³aczyæ do Bractwa?}
{235} {} {Zwykle nie przyjmujemy osób z zewn¹trz, ale by³y wyj¹tki.}
{236} {} {Sk¹d jesteœ?}
