{100} {} {Widzisz wartownika.}
{101} {} {Widzisz mê¿czyznê w zbroi wspomaganej. Wygl¹da imponuj¹co.}
{102} {} {To nie jest czas na rozmowy z miejscowymi.}
{103} {} {?}
{104} {} {Podejmujesz du¿e ryzyko, wracaj¹c tutaj.}
{105} {} {Pozdrowienia towarzyszu broni. Jak patrol?}

# Pierwszy dialog
{200} {} {Stój. Jaki jest cel twojej wizyty?}
{201} {} {Niewa¿ne, ju¿ wychodzê.}
{202} {} {Podró¿ujê wzd³u¿ wybrze¿a i oto jestem. Teraz mnie interesuje co to za miejsce?}
{203} {} {Lepiej nie wiedzieæ. IdŸ swoj¹ drog¹.}
{204} {} {Wygl¹dasz nieprzyjaŸnie.}
{205} {} {Czekaj... Na co siê do cholery gapisz? Nie potrzebujemy tutaj narkomanów. Wynoœ siê st¹d i nie wracaj. Dalej, ruszaj siê...}
{206} {} {Ugh... Uch...}
{207} {} {Zamkniête? Tak po prostu? Nie wiem.}
{208} {} {Ok. Mamy nieco przesuniête tutaj. Za ma³o rozumu, co? Nasi uczeni powinni wystawiæ ciê na próbê. Ale nie chcê siê w tym babraæ. (groŸnie) Wynoœ siê st¹d.}
{209} {} {Och, idŸ. Rozumiem to. Tak.}

# Powtarzajacy siê dialog
{210} {} {Mo¿esz przejœæ.}
{211} {} {Dziêki.}
{212} {} {Pozdrowienia towarzyszu broni.}
{1212} {} {Pozdrowienia siostro broni.}
{213} {} {Do zobaczenia bracie.}
{214} {} {(szyderczo ocenia twoj¹ zbrojê) WejdŸ. W kuchni brakuje pokrywki od rondla.}
{215} {} {Czy mogê wejœæ na pok³ad?}
{216} {} {Nadal pytasz? Oczywiœcie, wejdŸ, bracie.}
{1216} {} {Nadal pytasz? Oczywiœcie, wejdŸ siostro.}
{217} {} {Dziêkujê, bracie.}

{220} {} {Czy mogê zadaæ kilka pytañ?}
{221} {} {Nie wolno mi prowadziæ bezsensownych rozmów, zw³aszcza na temat naszego Bractwa.}
{222} {} {Rozumiem. Có¿, nie mo¿esz spieraæ siê z rozkazami. PA.}
{223} {} {Co tu robisz?}
{224} {} {Oczywiœcie strzegê przejœcia. Obcy nie mog¹ wejœæ na pok³ad bez pozwolenia. A ty go nie masz.}
{225} {} {Co tutaj robisz?}
{226} {} {Co to za miejsce?}
{227} {} {To jest nasz fort. Jeœli to wszystkie pytania, lepiej odejdŸ. Nie ma nic, co mog³oby odwracaæ uwagê wartowników na posterunku.}
{228} {} {Ok, wychodzê.}
{229} {} {Powiedz mi w takim razie, co to za miejsce?}
{230} {} {Jesteœcie super. Chcê siê do Was przy³¹czyæ.}
{231} {} {Nie licz na to.}
{232} {} {Ugh, powiedzia³, jak to przerwa³.}
{233} {} {Mo¿e masz dla mnie pracê?}
{234} {} {Nie s¹dzê. Ale porozmawiaj z szefem patrolu, mo¿e on coœ ma dla ciebie.}
{235} {} {Rozumiem, dziêki.}
{236} {} {Czekaj. Czy mogê zadaæ kilka pytañ?}

{240} {} {Muszê siê spotkaæ z twoim dowództwem, potrzebujê odpowiedzi.}
{241} {} {Na jakie pytanie?}
{242} {} {To osobista sprawa. Mogê iœæ?}
{243} {} {Nie.}
{244} {} {Przepraszam.}
{245} {} {I tak znajdê sposób, zobaczysz.}
{246} {} {Ok, mo¿esz przejœæ.}
{247} {} {Dziêki.}
{248} {} {Kiedy jesteœ w œrodku, trzymaj broñ w kaburze i nie rób nic g³upiego. Biuro genera³a jest na œrodkowym pok³adzie, magazyn na lewo od wejœcia. Zabrania siê wchodzenia do pozosta³ych przedzia³ów. Czy to jasne?}
{249} {} {Rozumiem.}

{250} {} {Przysy³a mnie Master Hard z Tu-San. Oto jego rekomendacja.}
{251} {} {Raport Ulyssesa Granta. Osobiœcie dla genera³a Dixona.}
{252} {} {Paladyn Latham da³ mi pozwolenie na spotkanie z genera³em.}
{253} {} {Genera³ Dixon czeka na mnie. Dotyczy to fortu w Hermosillo.}
{254} {} {Ten fort musi mieæ problemy ze zdobyciem niektórych rzeczy. A moja karawana jest akurat bezczynna.}
{255} {} {Mam du¿o œwietnych rzeczy do sprzedania. Zainteresowany?}
{256} {} {Nie, nie mamy do czynienia z samotnymi pielgrzymami.}
{257} {} {Przepraszam.}
{258} {} {Rozumiem. Ale powinieneœ wyczyœciæ swoj¹ zbrojê. Wygl¹dasz jak zardzewia³e wiadro.}
{259} {} {Paladyn Latham da³ mi pozwolenie na spotkanie z kwatermistrzem.}