{100} {} {Widzisz Maurê.}
{101} {} {Widzisz wysokiego skrybê Bractwa Stali.}
{102} {} {Nie mam teraz czasu na rozmowê.}
{103} {} {}

{110} {} {Ach, têskniê za wyk³adami Sophii.}
{111} {} {Czasami brakuje mi rad Vreji.}
{112} {} {Od dawna brakuje listów z Lost Hills.}
{113} {} {Bzdury. Eksperymenty w Casa Nueva s¹ bezpieczne.}
{114} {} {To nieludzkie, ale badania s¹ wa¿niejsze ni¿ ¿ycie jednego tubylca.}
{115} {} {}
{116} {} {}
{117} {} {}
{118} {} {}
{119} {} {}

# Pierwszy dialog
{200} {} {Stój. Czy masz pozwolenie na wejœcie na statek?}
{201} {} {Nie mam pozwolenia. Ja go nie potrzebujê. Rozumiesz?}
{202} {} {Jasne. Ciekawe. Zatrzymaj siê i ani drgnij. Teraz zawo³am paladynów... Przestañ, mówiê! Cholera...}
{203} {} {Ups...}
{204} {} {Tak, mam pozwolenie. Wszystko w porz¹dku.}
{205} {} {W takim razie czeœæ nieznajomy. Jestem Maura, wysoki skryba Bractwa Stali. Cywile nie s¹ tu czêsto wpuszczani. Co robisz na naszym statku?}
{1205} {} {W takim razie witaj nieznajoma. Jestem Maura, wysoki skryba Bractwa Stali. Cywile nie s¹ tu czêsto wpuszczani. Co robisz na naszym statku?}
{206} {} {Mam wa¿n¹ misjê.}
{207} {} {Ok. Niemniej jednak zapytam wartowników, dlaczego pozwolono ci przejœæ.}
{208} {} {Licze na twoj¹ lojalnoœæ, Skrybo Maura.}
{209} {} {Lepiej pilnuj swoich spraw, skrybo.}

# Powtarzajacy siê dialog
{210} {} {Witaj nieznajomy.}
{1210} {} {Pozdrowienia, nieznajoma.}
{211} {} {Pozdrowienia, bracie.}
{1211} {} {Pozdrowienia siostro.}
{212} {} {Do widzenia.}
{213} {} {Czy mogê zadaæ kilka pytañ?}
{214} {} {Hmm. Mo¿e coœ ci powiem.}
{215} {} {Zadnych wiêcej pytañ.}

#Zapytania
{220} {} {Po drodze wpad³em na wiêŸnia.}
{221} {} {Tak, u¿ywamy pracy wiêŸniów do odbudowy statku. Nie powinieneœ z nimi rozmawiaæ.}
{222} {} {Bardzo racjonalna decyzja.}
{223} {} {Mê¿czyzna pope³ni³ przestêpstwo i odsiaduje wyrok. Dosta³ drug¹ szansê. Niech bêdzie wdziêczny za nasze mi³osierdzie.}
{224} {} {Ale mówi, ¿e podniós³ tylko kilka kolb z ogromnej plantacji.}
{225} {} {Po pierwsze, to jest wymówka. Po drugie, przestêpcy zawsze staraj¹ siê umniejszyæ swoj¹ winê. Oczywiœcie nie przyznaje siê, ¿e kolb by³o wiêcej, ani ze rabunek mia³ miejsce równie¿ w kamienicach. Typowa sytuacja.}
{226} {} {Teraz rozumiem. Czy mo¿esz odpowiedzieæ na inne pytania?}
{227} {} {Albo to, albo sam ukryj swoje niewolnicze ambicje.}
{228} {} {Bzdury! Historia dobrze pokazuje, ¿e praca niewolnicza jest skuteczna tylko w krótkim okresie. Poza tym nie ma potrzeby uciekaæ siê do takich œrodków, gdy wokó³ jest tak wielu prawdziwych przestêpców. Schwytaj dowolnego z nich - i spraw, by przyniós³ korzyœci spoleczenstwu. Oto rozs¹dne podejœcie.}
{229} {} {Mo¿esz mieæ racjê.}
{230} {} {Có¿, powiedz mi wiêcej.}
{231} {} {Czy zak³adanie mu ko³nierza i zmuszanie go do pracy jest humanitarne?}
{232} {} {Humanitarne? Mê¿czyzna pope³ni³ zbrodnie, niech bêdzie wdziêczny za zachowanie bezwartoœciowego ¿ycia.}
{233} {} {Mówi, ¿e z ogromnej plantacji wzi¹³ tylko kilka kolb, ¿eby prze¿yæ.}
{234} {} {Czy mo¿esz mi powiedzieæ, kto jest kim na statku?}
{235} {} {Wiêc to nie ty stoisz za niewolnictwem w Arizonie?}
{236} {} {Oczywiœcie, ¿e nie. Wiem jednak, ¿e niektórzy z naszych sojuszników czasami nadu¿ywaj¹ swojej pozycji. To tylko zarzuty.}

{240} {} {Opowiedz mi o tym statku.}
{241} {} {Ten statek to niszczyciel Vockelgeising DD-1862. D³ugoœæ 130 jardów, szerokoœæ 13,6, zanurzenie 4,77... Ach, gdyby ta maszyna by³a w ruchu, rozwija³aby prêdkoœæ do 35 wêz³ów morskich.}
{242} {} {Brzmi fajnie. Co jeszcze mo¿esz mi powiedzieæ?}
{243} {} {Niszczyciel - co to znaczy?}
{244} {} {Ze na pok³adzie statku jest kilka cholernych torped nuklearnych, z których ka¿da mo¿e zniszczyæ ma³e miasto. Ka¿dy ¿o³nierz na statku marzy o takiej eksplozji. Ale na szczêœcie jak dot¹d nie by³o ku temu ¿adnego powodu.}
{245} {} {Czy ten statek mo¿e wyp³yn¹æ w morze?}
{246} {} {Nie teraz. Statek nie ma wystarczaj¹cej iloœci paliwa j¹drowego na d³ug¹ podró¿. Ponadto wymagane s¹ naprawy starego sprzêtu i obudowy. Wiedzieliœmy, ¿e jest to podró¿ w jedn¹ stronê, dopóki nie za³o¿yliœmy bazy w tym porcie.}
{247} {} {Dlaczego niektóre drzwi s¹ zamkniête?}
{248} {} {S¹ ku temu powody. Niektóre rzeczy na statku wymagaj¹ szczególnie delikatnej opieki. A nawet wœród naszych ludzi zdarzaj¹ siê b³êdy. Dlatego s¹ miejsca, do których dostêp ma tylko Wielki Paladyn Dixon.}
{249} {} {Rozumiem. Dziêki za odpowiedzi.}

{250} {} {Opowiedz mi o Bractwie Stali.}
{251} {} {Co dok³adnie chcesz wiedzieæ o naszym zakonie?}
{252} {} {Przestañ mówiæ o Bractwie. Ju¿ wiem wystarczaj¹co du¿o.}
{253} {} {Sk¹d siê wszyscy wziêliœcie?}
{254} {} {Pochodzimy z Kalifornii. Wczeœniej siedzieliœmy cicho w swoim bunkrze i nie wtr¹caliœmy siê w œwiatowe sprawy. Ale nadszed³ nasz czas. Przed tob¹ jest tylko jedna z naszych odleg³ych placówek.}
{255} {} {Opowiedz mi historie Bractwa.}
{256} {} {Có¿, genera³ Maxson zebra³ nas podczas Wielkiej Wojny i zaprowadzi³ do starej bazy wojskowej. Tam prze¿yliœmy najtrudniejsze chwilê. Minê³o kilka pokoleñ, a teraz jego potomek rz¹dzi naszymi szeregami.}
{257} {} {Jaka jest Wasza misja? Czego chcecie na koñcu?}
{258} {} {G³ównym celem naszego zakonu jest poszukiwanie i zachowywanie staro¿ytnych technologii, aby pewnego dnia przywróciæ porz¹dek na ziemiach niegdyœ wielkiego kraju. Jednak w zakonie istnieje wiele sporów na ten temat. D³ugo nie wa¿yliœmy siê rozpoczynaæ naszej „krucjaty”, dopiero ostatnie wydarzenia w Kalifornii zmusi³y nas do przemyœlenia naszej strategii i wyjœcia z cienia.}
{259} {} {Kraj? O jakim kraju mówisz?}
{260} {} {Stany Zjednoczone Ameryki.}
{261} {} {Co to za wydarzenie w Kalifornii, o którym wspomnia³aœ?}
{262} {} {Wielka historia Mistrza i jego armii. Chcesz poznaæ szczegó³y?}
{263} {} {Tak, powiedz mi.}
{264} {} {Ta historia mnie nie interesuje. Lepiej zmieniæ temat.}
{265} {} {Um, wrócmy trochê.}
{266} {} {Dziêki. Na tym koñczy siê rozmowa o Bractwie.}
{267} {} {Poniewa¿ ja równie¿ jestem teraz cz³onkiem Bractwa, chcê us³yszeæ szczer¹ odpowiedŸ. Co dowództwo NAPRAWDE stara siê osi¹gn¹æ?}
{268} {} {Tego nie powiedzia³am, ale naszym g³ównym celem w Arizonie jest zdobycie materia³u j¹drowego dla Sztabu Generalnego w Kalifornii. Sztab Generalny potrzebuje równie¿ innych zasobów. Bez nich porz¹dek potrwa jakiœ czas, ale wczeœniej czy póŸniej nasza izolacja dobiegnie koñca. A wtedy Bractwo bêdzie zmuszone do podjêcia drastycznych kroków, aby siê utrzymaæ.}
{269} {} {Wiêc zakon musi najpierw przetrwaæ tutaj, dlatego miejscowi maj¹ o to zadbaæ? O tak, teraz rozumiem.}

{270} {} {Twórca Supermutantów, uwa¿aj¹c siê za Boga, otworzy³ swój w³asny koœció³ i stworzy³ kult wokó³ swojej osoby. Jego sekta obejmowa³a wielu ludzi. Czêœæ z nich zosta³a wykorzystana jako materia³ do eksperymentów. Najbardziej udane okazy utworzy³y póŸniej osobist¹ armiê Mistrza.}
{271} {} {Armia supermutantów? Mistrz musia³ byæ sprytny jak diabli.}
{272} {} {I oczywiœcie nie chcieliœcie dzieliæ siê w³adz¹ z dyktatorem?}
{273} {} {Nasi zwiadowcy zbadali sytuacjê, wszyscy byliœmy zagro¿eni. Koœció³ zosta³ zniszczony. Armia zosta³a pokonana. Resztki armii osiedli³y siê na pustkowiu, ale nasze wojska szybko je znalaz³y i wymaza³y z historii.}
{274} {} {Wygl¹da na to, ¿e wiesz, jak prowadziæ wojnê. Pomyœl o tym, nikt we wspó³czesnej Arizonie ciê nie pokona.}
{275} {} {Arizona nie ma jeszcze takiego problemu. Masz szczêœcie, ¿e tu jesteœmy. Mamy jednak nieco inne cele.}
{276} {} {Wielkie dziêki za historie.}
{277} {} {Och œwietnie. Doskonale. Uh, pa.}
{278} {} {}
{279} {} {Nie wierzê w to. Bractwo musia³o upiêkszyæ swoje zas³ugi.}
{280} {} {Mówisz, ¿e k³amiê? Kiedy bêdziesz w Kalifornii, zapytaj miejscowych. Jednak wszyscy na Pustkowiu powiedz¹, ¿e to *on* zdetonowa³ bombê atomow¹. Mieszkaniec Krypty, który by³ tylko naszym najemnikiem.}
{281} {} {Naprawdê nie jest dobrym pomys³em wierzyæ plotkom.}
{282} {} {Dok³adnie. Twoje s³owa s¹ niczym innym jak tylko s³owami.}

{288} {} {Jakim on jest cz³owiekiem?}
{289} {} {Wielki Dixon. Wystarczy, ¿e pstryknie palcem, ¿eby obróciæ czyj¹œ wioskê w py³. To wszystko, co musisz wiedzieæ.}
{1289} {} {Wielki Dixon. Wystarczy, ¿e pstryknie palcem, ¿eby obróciæ czyj¹œ wioskê w py³. To wszystko, co musisz wiedzieæ.}
{290} {} {Czy mo¿esz mi opowiedzieæ o swoim dowódcy?}
{291} {} {Genera³ Dixon jest jednym z wysokich paladynów Bractwa. Jego doœwiadczenie wojskowe i polityczne jest przedmiotem zazdroœci ka¿dego wspó³czesnego w³adcy.}
{292} {} {Uch, rozumiem.}
{293} {} {Genera³ Dixon jest jednym z wysokich paladynów Bractwa. Tylko kilka osób w ca³ym zakonie ma tak du¿e doœwiadczenie w operacjach wojskowych i d³ugich wyprawach poza domem. Rada Bractwa mu ufa.}
{294} {} {A ty?}
{295} {} {Dziêki. Nie chcê wiedzieæ nic wiêcej.}
{296} {} {On jest wojownikiem, a ja jestem skryb¹. Z tego powodu czêsto nie znajdujemy u siebie zrozumienia. Dixon nie toleruje biurokracji i ma sk³onnoœæ do szybkiego rozwi¹zywania problemów. Latwiej mu chwyciæ za broñ ni¿ negocjowaæ.}
{297} {} {I Sztab Generalny ufa zagorza³emu wojownikowi?}
{298} {} {Rada Starszych tak naprawdê nie pochwala niektórych dzia³añ Dixona. Ale nasza placówka jest zbyt daleko od Sztabu Generalnego i zadanie jest zbyt z³o¿one, aby polegaæ na konwencjonalnych metodach. Dlatego genera³ jest wyposa¿ony w specjalne prawa, które daj¹ mu tak naprawdê woln¹ rêkê. Myœlê, ¿e jest to ca³kiem uzasadnione.}
{299} {} {Dziêki. To bardzo wiele wyjaœnia.}

{300} {} {Myœlê, ¿e teraz jestem pod twoim dowództwem. Ja te¿ jestem skryb¹.}
{301} {} {Cieszê siê, ¿e wybierasz oœwiecenie zamiast broni. Pozwól, ¿e ci pomogê w tym przedsiêwziêciu.}
{302} {} {S³ucham.}
{303} {} {Och, proszê.}
{304} {} {To analityczny neurolink Pip-Boya. Standardowy model, którego u¿ywaj¹ nasi skrybowie. U¿yj go, aby byæ bardziej uwa¿nym i m¹drzejszym.}
{305} {} {Dziêki, siostro Mauro. Wykorzystam ten cenny dar dla dobra Bractwa.}
{306} {} {Ok. Mo¿e gdzieœ siê przyda.}

# Wiara w b³êdy
{310} {} {Wiêc jesteœcie zwyk³ymi najeŸdŸcami.}
{311} {} {Nie rozumiem, dlaczego powinnam tego s³uchaæ. Czy powinnam wezwaæ paladynów, aby wyrzucili ciê ze statku?}
{312} {} {Przepraszam. Jestem trochê podekscytowany...}
{1312} {} {Przepraszam. Jestem trochê podekscytowana...}
{313} {} {Czy a¿ tak ciê to boli? Nie zmienisz tego poprzez moje wygnanie.}
{314} {} {Nie mo¿esz mnie zamkn¹æ! Tylko spróbuj - ugryzê wszystkich w gard³o!}
{315} {} {Innymi s³owy, przyszliœcie wzi¹æ to, co do was nie nale¿y.}
{316} {} {Lepiej uwa¿aj na to co mówisz. I nie, Bractwo tak nie uwa¿a. Dziêki wra¿liwej polityce Dixona Arizona dosta³a szansê rozwoju. Miejscowi dzicy maj¹ wykszta³cenie, medycynê i produkcjê na poziomie, którego nie by³o tu od prawie stu lat. Czy to nie cud?}
{317} {} {Mo¿e cud. A mo¿e mira¿?}
{318} {} {Trudno siê z tym k³óciæ. Wiem swoje, skrybo Mauro.}
{319} {} {Propaganda nie ma na mnie wp³ywu, skrybo. Z przyjemnoœci¹ zostajê.}
{320} {} {Nadal nie zamierzasz siê uspokoiæ? Lepiej siê uspokój, zanim wezwê paladynów.}
{321} {} {Przepraszam. Nie chcê mieæ k³opotów. PA.}
{322} {} {S³aba argumentacja, skrybo. Zegnam.}
{323} {} {Genera³ Dixon siê myli. Doskonale to rozumiesz.}
{324} {} {Mo¿e. Ale co TY masz na myœli, mówi¹c, ¿e siê myli?}
{325} {} {Dixon prowadzi nieludzk¹ grê. Poprzez swoich lokalnych wasali narzuca tyraniê, przejmuje zasoby, wykorzystuje technologie i praktykuje niewolnictwo.}
{326} {} {Nawet nie wiem, co powiedzieæ. Zostawmy to na jego sumieniu.}
{327} {} {Niby siê zgadzam. S¹ to jednak wszystko œrodki uzasadnione. Miejscowi stracili swoje korzenie ze Starym Swiatem. Stali siê dzicy i nieprzewidywalni. Min¹ wieki bez naszej interwencji, zanim oni sami bêd¹ mogli powróciæ do korzeni cywilizacji.}
{328} {} {Nie wiem, komu wierzyæ. Pozwól mi trochê pomyœleæ.}
{329} {} {By³em w wielu osadach. Wasz wp³yw na te ziemie nie jest tak jednoznaczny i majestatyczny, jak go przedstawiacie.}
{1329} {} {By³am w wielu osadach. Wasz wp³yw na te ziemie nie jest tak jednoznaczny i majestatyczny, jak go przedstawiacie.}
{330} {} {Naprawdê? Czy nasi poplecznicy z Phoenix nie zaprowadzili spokoju i porz¹dku w tym mieœcie? Czy nasza interwencja nie przedstawi³a Arizonie waluty kapsli? Czy trasy karawan Tu-San i kopalnie Flagpool nie zapewni³y wielu miejsc pracy?}
{331} {} {Tak jakby. Ale twoja ekspansja nie tyle daje ludziom wolnoœæ i rozwój, ile rodzi niewolnictwo i niszczy tradycje.}
{332} {} {Naprawdê nie mo¿esz siê z tym k³óciæ. Wiêc umywasz rêce.}
{333} {} {Hmm. Podaj przyk³ady miejsc, w których by³eœ.}
{334} {} {Na razie mo¿emy obejœæ siê bez tego. Nie chcê wchodziæ tak daleko w tê argumentacjê.}
{335} {} {Aaron, który si³¹ przej¹³ w³adzê w Phoenix, buduje imperium i wypala sprzeciw. Jaka to jest wolnoœæ?}
{336} {} {W San Brahmin wybuch³a prawdziwa wojna. Czy tego chcieliœcie?}
{337} {} {Blacharze Tu-San s¹ bardzo silni. Zabieraj¹ technologie innym i skazuj¹ ludzi na œmieræ w swoich Swiêtych Kopalniach.}
{338} {} {Casa Grande. OdwiedŸ lokalny cmentarz, aby zobaczyæ, jak technologia skaza³a ludnoœæ na krwawe wojny o wodê.}
{339} {} {Casa Nueva jest jak zagroda ze stadem braminów. Bez ciebie ci ludzie s¹ s³abi i bezradni.}
{340} {} {Có¿, ja te¿ w¹tpiê w nasz¹ drogê. Ale nie mog³am znaleŸæ rozwi¹zania, które zadowoli wszystkich.}
{341} {} {Naprawdê?}
{342} {} {Ta placówka da³a zbyt ma³o dobrego Arizonie. Nie mamy prawa paso¿ytowaæ na obcych ziemiach, zabieraæ zasoby miejscowym mieszkañcom i zmuszaæ ich do pracy dla w³asnej wielkoœci. Jest to sprzeczne z duchem i podstawami zakonu.}
{343} {} {Dok³adnie.}
{344} {} {I to nie tyle wina zakonu czy starszych, ile wynik ambicji Dixona. Ale nie mo¿na go ju¿ powstrzymaæ, a nowy genera³ prawie na pewno nie zmieni kursu.}
{345} {} {To bardzo dobrze, ¿e to widzisz. Ale myœlê, ¿e posuneliœmy siê za daleko w naszej rozmowie. Na tym zakoñczmy.}
{346} {} {Musimy powstrzymaæ to z³o. Pomó¿ mi.}
{347} {} {Przepraszam. Ale nic nie mogê zrobiæ, aby pomóc.}
{348} {} {Do widzenia, skrybo Mauro.}
{349} {} {Musimy powstrzymaæ to z³o. Pomó¿ mi. Twoje b³êdy doprowadzi³y do tego, ¿e moja w³asna Villa pad³a ofiar¹ ³owców niewolników.}
{350} {} {Przepraszam. WeŸ ten klucz. Wystrzeliwuje nuklearne torpedy w dolnej ³adowni statku. Ustaw kierunek i czas przed wybuchem, a nastêpnie biegnij jak najszybciej na pustyniê. Na ziemiach Sonory nie ma miejsca dla bractwa.}
{351} {} {Dziêkujê Skrybo Mauro.}
{352} {} {Podejmij dzia³anie, drogi przyjacielu.}