{100} {} {Widzisz skrybê.}
{101} {} {Widzisz zwyk³ego urzêdnika Bractwa Stali.}

{210} {} {Co tu robisz? Kto ciê wpuœci³?}
{211} {} {Nie rozpraszaj mnie, prowadzê wa¿ne badania.}
{212} {} {Witamy w Bractwie. Teraz zrób coœ po¿ytecznego.}
{213}{}{Chcesz porozmawiaæ o nauce?}
{214}{}{Czy twoje serce jest otwarte na fizykê kwantow¹?}
{215}{}{Czy akceptujesz nauki Izaaka, naszego Newtona, który przyj¹³ cios jab³kiem z naszej ignorancji, naszego nieporozumienia, i z naszych lêków?}