{100} {} {Widzisz Junga.}
{101} {} {Widzisz ch³opca w wieku oko³o piêciu lat.}
{102} {} {Kiedy dorosnê, te¿ za³o¿ê tak¹ zbrojê.}
{103} {} {Nie zbli¿aj siê! Bêdê siê broni³!}

{200} {} {Czeœæ, nie widzia³em ciê tu wczeœniej.}
{201} {} {I wiêcej mnie nie zobaczysz. Bywaj.}
{202} {} {Oczywiœcie, ¿e nie, g³uptasie. Jestem prosto z pustyni.}
{203} {} {Co, mieszkasz na pustyni? Jak dziwnie. Nie mieszka³bym tam. Jak masz na imiê?}
{204} {} {Najpierw przedstaw siebie, ignorancie.}
{205} {} {Nazywam siê }
{206} {} {. A ty?}
{207} {} {Czeœæ ch³opcze. Jak masz na imiê?}
{208} {} {Powiedz mi swoje imiê, dziecko.}
{209} {} {Nazywam siê Jung, proszê pana.}
{1209} {} {Nazywam siê Jung, proszê pani.}
{210} {} {Mi³o ciê poznaæ, Jung. Masz niezwyk³e imiê.}
{211} {} {Moi rodzice tak mnie nazwali. Nie wiem dlaczego.}
{212} {} {Jacy idioci nazwali ciê tym imieniem?}
{213} {} {Moi rodzice tak mnie nazwali. I nie s¹ idiotami. S¹ lepsi ni¿ ludzie z zewn¹trz, tacy jak ty.}
{214} {} {Swoj¹ drog¹, gdzie s¹ twoi rodzice?}
{215} {} {Gdzieœ tutaj. Paladyn Latham jest moim tat¹. A moja mama jest gdzieœ na brzegu. Prawdopodobnie pierze ubrania.}
{216} {} {Co, twoja mama pierze majtki innych paladynów?}
{217} {} {Ona nie jest paladynem. W ogóle nie ma rangi.}
{218} {} {Czy twoja mama te¿ jest paladynem?}
{219} {} {Nie, proszê pana. Ona nie ma rangi.}
{1219} {} {Nie, proszê pani. Ona nie ma rangi.}
{220} {} {Zaraz, wiêc jesteœ synem paladyna i ch³opki? Jak to mo¿liwe?}
{221} {} {Mój tata jest najlepszy! On mo¿e wszystko!}
{222} {} {Ciekawa moralnoœæ tutaj panuje.}

{250} {} {O, czeœæ.}
{251} {} {Jung jest gotowy na misjê!}
{252} {} {Czy naprawdê jesteœ z Bractwa?}
{253} {} {Jak¹ masz rangê?}
{254} {} {}
{255} {} {Do widzenia, m³odziencze.}

{260} {} {Przypomnij mi jeszcze raz, kim w ogóle jesteœ?}
{261} {} {Jestem Jung, mój tata jest paladynem, a moja mama jest wieœniaczk¹. Teraz to jasne?}
{262} {} {Rozumiem.}
{263} {} {Co robisz na tym statku?}
{264} {} {Có¿, wszystko. Ci¹gle otrzymujê jakieœ zadanie. Przynieœ to, przynieœ tamto.}
{265} {} {Rozumiem.}
{266} {} {Co teraz robisz?}
{267} {} {Szukam mojej bestii. Nie rozumiem, gdzie zniknê³a. Ma³a, z czterema nogami. Jeœli j¹ znajdziesz, zwróæ mi j¹, dobrze?}
{268} {} {Przepraszam, zdecydowanie nie mam teraz czasu na gry.}
{269} {} {Mogê jej poszukaæ. Jak myœlisz, gdzie ona mo¿e byæ?}
{270} {} {Có¿, biega³em po ca³ym statku. Nie wiem.}
{271} {} {Hmm. To trochê wyjaœnia.}
{272} {} {Czy to ta sama zabawka, której szuka³eœ?}
{273} {} {Tak! To ona!}
{274} {} {Proszê bardzo. I nie gub tego wiêcej.}
{275} {} {Dziêkujê panu...}
{1275} {} {Dziêkujê pani...}
{276} {} {Proszê.}
{277} {} {Zwykle na pustkowiu dostajemy zap³atê za nasz¹ pracê. Co mo¿esz mi daæ w zamian?}
{278} {} {(z wahaniem wyci¹ga kartê magnetyczn¹ z kieszeni)}
{279} {} {Magnetyczna karta do drzwi? I to wszystko? Dobra, daj mi to.}

{280}{}{Wynoœ sie st¹d. Wkrótce bêdzie tu bardzo gor¹co.}
{281}{}{O czym pan mówi, proszê pana?}
{1281}{}{O czym pani mówi, proszê pani?}
{282}{}{Nie marnuj czasu! Jeœli nie chcesz umrzeæ, radzê ci ukryæ siê w pobliskich ruinach.}
{283}{}{Tylko ¿artujê. Ha ha. Niewa¿ne.}
{284}{}{*szloch-szloch*}
{285}{}{Dz... dziêkujê...}