{100} {} {Widzisz s³ugê.}
{101} {} {Widzisz chudego Meksykanina. Nosi pasiast¹ koszulê i ko³nierz niewolnika, a w rêkach trzyma mop.}

{110} {} {Tak, proszê pana!}
{111} {} {Mi³o pomóc, senor!}
{112} {} {Czy ja ciê opóŸniam, senor?}
{113} {} {Przepraszam pana.}
{114} {} {Jak mówisz, senor.}

{1110} {} {Tak, proszê pani!}
{1111} {} {Mi³o pomóc, senora!}
{1112} {} {Czy ja ciê opóŸniam, senora?}
{1113} {} {Przepraszam, senora.}
{1114} {} {Cokolwiek powiesz, senora.}

{200} {} {Co mogê dla Pana zrobiæ, sir... Och, nie jesteœ z Bractwa. Wiêc lepiej ze mn¹ nie rozmawiaj, paladynom to siê nie podoba.}
{1200} {} {Co mogê dla Pani zrobiæ, senora... Och, nie jesteœ z Bractwa. Wiêc lepiej ze mn¹ nie rozmawiaj, paladynom siê to nie podoba.}
{201} {} {Dlaczego?}
{202} {} {Zawsze widz¹ spisek. A kiedy znajduj¹ powód, nak³adaj¹ karê, a nawet publiczn¹ ch³ostê. Obowi¹zuje tu prawdziwy re¿im. Jeden s³uga nawet zosta³ niedawno utopiony za kradzie¿ jedzenia Wielkiego Paladyna. Nie chcê byæ na jego miejscu.}
{203} {} {Rozumiem. Pójdê ju¿.}

{210} {} {(rozgl¹da siê) Hej, bêdziemy mieli k³opoty.}
{211} {} {Ok. Bywaj.}
{212} {} {Chcia³bym zapytaæ ciê o ten statek i Bractwo.}
{213} {} {Nie jesteœ z Bractwa. Ju¿ jestem zagro¿ony, odpowiadaj¹c na twoje pytania. A co mi z tego, co? Rozmowy tylko dra¿ni¹ mój ¿o³¹dek.}
{214} {} {Ok. Bywaj.}
{215} {} {Ostro¿nie, mog¹ nas pods³uchiwaæ.}
{216} {} {Lepiej nie wkurzaj paladynów. Bywaj.}
{217} {} {WyraŸnie nie rozumiesz swojego stanowiska. Wiêc powiedz mi!}
{218} {} {WyjdŸ albo zawo³am paladynów!}
{219} {} {Grr...}

{220} {} {Kim jesteœ? Nie jesteœ cz³onkiem Bractwa, prawda?}
{221} {} {Nie ma mowy, sir. Czy widzisz ko³nierz? Jestem wiêŸniem, oto mój numer.}
{1221} {} {Nie ma mowy, senora. Czy widzisz ko³nierz? Jestem wiêŸniem, oto mój numer.}
{222} {} {Rozumiem. Inne pytanie.}
{223} {} {Wiêzieñ? Ale dlaczego jesteœ przetrzymywany wbrew swojej woli?}
{224} {} {Wzi¹³em kilka kolb z plantacji... No i kilka owoców... w³aœciwie nie kilka, ale ca³¹ torbê... Ale potrzebowa³em czegoœ do jedzenia! Obecnie pracujê na statku do czasu odbycia kary.}
{225} {} {Czy wiele osób takich jak Ty odpracowywuje tutaj karê?}
{226} {} {Na statku jest tylko kilku s³u¿¹cych, reszta pracuje w innych miejscach - na plantacjach, w ruinach, w cementowni, buduje domy lub po prostu przewozi towary przez pustyniê. Mam wiêcej szczêœcia ni¿ oni.}
{227} {} {Co tu robisz?}
{228} {} {Na przyk³ad szorujê tê cholern¹ pod³ogê cztery razy dziennie! Albo noszê ró¿ne pude³ka. Kwatermistrz stale odbiera i wysy³a jakieœ paczki.}
{229} {} {Kto oprócz ciebie odbywa tu karê?}
{230} {} {Czy mo¿esz siê st¹d wydostaæ?}
{231} {} {Jeœli oddalê siê zbyt daleko od statku, ko³nierz eksploduje. To wynalazek skryb, ale nie bior¹ udzia³u w kontaktach z miejscowymi. Poza tym karmi¹ mnie tu, a na pustkowiach znów bêdê musia³ szukaæ dla siebie po¿ywienia. Wiesz, trudny wybór.}
{232} {} {Pos³uchaj mnie teraz. Albo przeka¿esz mi wszystkie znane Ci informacje, albo „przypadkowo” znajdziesz siê za burt¹.}
{233} {} {Czego chcesz? Nie rozumiesz, gdzie jesteœ?}
{234} {} {Potrzebujê informacji.}

{240} {} {Co wiesz o Bractwie Stali?}
{241} {} {Niewiele wiem, zakon nie lubi mówiæ o sobie. Wiem, ¿e to tylko placówka, a Sztab Generalny znajduje siê daleko na zachodzie. Poza tym s¹ to najsilniejsi ludzie w ca³ej Sonorze. Nawet Blacharze nie mog¹ siê z nimi równaæ.}
{242} {} {Rozumiem. Czyli lepiej z nich nie ¿artowaæ. Zmieñmy motyw.}
{243} {} {Kto tu rz¹dzi?}
{244} {} {Genera³ Dixon. Zwykle przebywa w swojej kabinie lub w mesie.}
{245} {} {Rozumiem. Doœæ o Bractwie.}

{250} {} {Znasz ka¿dy zak¹tek statku, prawda?}
{251} {} {Nie, nie mo¿na tu iœæ wszêdzie. Du¿o drzwi jest zamkniêtych na klucz. Zw³aszcza na ni¿szych poziomach i magazynach.}
{252} {} {Ok, to nie ma znaczenia.}
{253} {} {Co kryje siê na ni¿szych poziomach?}
{254} {} {Sk³ad torped. Mówi¹, ¿e przechowuj¹ tam materia³y wybuchowe. Jest tam równie¿ reaktor i szczury wielkoœci psa.}
{255} {} {Wow, warto to zobaczyæ.}
{256} {} {Kto ma klucze do drzwi?}
{257} {} {Wszyscy maj¹ ograniczony dostêp, tylko Wielki Paladyn ma klucze do wszystkich drzwi.}
{258} {} {Hmm. Wydaje siê, ¿e genera³ nie ufa w pe³ni nawet swoim ludziom.}