{100} {} {Widzisz Grahama.}
{101} {} {Widzisz jednego z Rycerzy Bractwa Stali.}
{102} {} {Czekaj. Poka¿ mi swoj¹ przepustkê.}

# Pierwszy dialog
{200} {} {Hej, Ty. Nawet jeœli dosta³eœ przepustkê, nie oznacza to, ¿e mo¿esz chodziæ po statku i odwracaæ uwagê ludzi od ich s³u¿by.}
{1200} {} {Hej, Ty. Nawet jeœli dosta³aœ przepustkê, nie oznacza to, ¿e mo¿esz chodziæ po statku i odwracaæ uwagê ludzi od ich s³u¿by.}
{201} {} {Przepraszam, ale by³em strasznie ciekawy. To miejsce jest takie niezwyk³e...}
{202} {} {Imponuj¹ce, prawda? Prawdziwy statek. Z ogromnym, dobrze wyszkolonym i uzbrojonym zespo³em. Powiedz mi, tubylcze, czy spotka³eœ coœ bardziej imponuj¹cego? Otó¿ to.}
{1202} {} {Imponuj¹ce, prawda? Prawdziwy statek. Z ogromnym, dobrze wyszkolonym i uzbrojonym zespo³em. Powiedz mi, tubylcze, czy spotka³aœ coœ bardziej imponuj¹cego? Otó¿ to.}
{203} {} {Odwracam uwagê ludzi? Po prostu siedzisz w jadalni i nic nie robisz.}
{204} {} {Ca³a ta baza dzia³a dziêki mnie i mojej s³u¿bie. Ale ty, dziki z pustyni, nie rozumiesz wielkoœci starych technologii. Powiedz mi, tubylcze, czy spotka³eœ coœ bardziej imponuj¹cego? Otó¿ to.}
{1204} {} {Ca³a ta baza dzia³a dziêki mnie i mojej s³u¿bie. Ale ty, dziki z pustyni, nie rozumiesz wielkoœci starych technologii. Powiedz mi, tubylcze, czy spotka³aœ coœ bardziej imponuj¹cego? Otó¿ to.}
{205} {} {Swoj¹ drog¹, kim jesteœ?}
{206} {} {Jestem Rycerz Graham. Odpowiadam za sprzêt pok³adowy. Robiê sobie teraz krótk¹ przerwê, wiêc zadawaj pytania, jeœli masz jakieœ.}
{207} {} {Mi³o ciê poznaæ, Rycerzu Graham.}
{208} {} {Ok.}
{209} {} {Teraz bêdê wiedzia³, kto jest odpowiedzialny za ca³y ten ba³agan na statku.}
{210} {} {Och, to nasz nowy bohater. Diabe³ z pustyni, przewy¿sza wszystkich weteranów razem wziêtych. NieŸle. Ale nie myœl, ¿e tak ³atwo zostaniesz przyjêty do Bractwa.}
{211} {} {Rozumiem twoje niezadowolenie. I zrobiê wszystko, aby bractwo mnie zaakceptowa³o.}
{212} {} {Wiêc pamiêtaj. Wielu przysiêga³o krwi¹, ¿e nie zdradz¹ naszego bractwa. Ci, którzy próbowali zap³acili za to ¿yciem w najbardziej przera¿aj¹cy sposób.}
{213} {} {Nie obchodzi mnie, co myœlisz. I opinia reszty. Jeœli komuœ nie podoba siê moja obecnoœæ, niech idzie do diab³a.}
{214} {} {Hmm. Chyba szukasz k³opotów. Zobaczmy, jak d³ugo to potrwa.}

# Powtarzajacy siê dialog
{220} {} {Hej, kolego. Nie spodziewasz siê, ¿e wype³nisz tu brzuch, prawda? A mo¿e szukasz Ÿród³a m¹droœci weterana? Powiedz mi bez ogródek, czego potrzebujesz?}
{1220} {} {Hej, kobieto. Nie spodziewasz siê, ¿e wype³nisz tu brzuch, prawda? A mo¿e szukasz Ÿród³a m¹droœci weterana? Powiedz mi bez ogródek, czego potrzebujesz?}
{221} {} {Hej ¿o³nierzu. Chcesz wype³niæ swój stracony czas jedzeniem lub porozmawiaæ z weteranem na temat s³u¿by?}
{222} {} {Ani jedno, ani drugie. Przygotowujê siê do wyjœcia.}
{223} {} {Ok. Ale jeœli potrzebujesz porady od weterana, zapytaj.}
{224} {} {Zegnaj Rycerzu Grahamie.}

{230} {} {Potrzebujê jedzenia.}
{231} {} {Spytaj kucharza. B¹dŸ dla niego mi³y, jeœli chcesz wiêcej.}
{232} {} {W³aœciwie to chcê porozmawiaæ.}
{233} {} {Dziêki. PA.}
{234} {} {W³aœciwie to chcê porozmawiaæ.}
{235} {} {Och, nawet nie wiem, od czego zacz¹æ. Tak wiele siê wydarzy³o.}
{236} {} {Dziêki za historie. Zegnaj rycerzu Graham.}

#Hazard
{250} {} {Zagramy w karty?}
{251} {} {Granie dla samej przyjemnoœci mnie nie interesuje. Co zamierzasz za³o¿yæ? Kapsle? Okej, dodam naboje 5 mm. Stawka wynosi 10 naboi po 25 kapsli.}
{252} {} {Nie dzisiaj.}
{253} {} {Ok. Akceptujê wyzwanie. Zagrajmy.}
{254} {} {Nie, chcê twoje RPI.}
{255} {} {Czy to nie jest za grube dla nieznajomego na pustyni? Ok, ale Twój zak³ad bêdzie wy¿szy - 50 kapsli.}
{256} {} {}
{257} {} {Wiêc zamierzasz graæ w gry zamiast s³u¿yæ? Nie zapomnij, gdzie jesteœ.}
{258} {} {Przepraszam, Rycerzu Graham.}
{259} {} {To by³o doœæ niegrzeczne.}
{260} {} {Ok, zacznijmy... Daj... Ty... Ja... Twój ruch.}
{261} {} {Kontynuuj...}
{262} {} {Poddajê siê.}
{263} {} {Co? Przegra³em z palantem z pustkowi? Cholera, dzisiaj zdecydowanie nie jest mój dzieñ...}
{1263} {} {Co? Przegra³em z dziewczyn¹ z pustkowi? Cholera, dzisiaj zdecydowanie nie jest mój dzieñ...}
{264} {} {Karta mi dziœ sprzyja, Rycerzu Graham.}
{265} {} {To powinno trochê os³abiæ twoj¹ arogancjê. Czeœæ, fra.. przegrany.}
{266} {} {Nawet w grach hazardowych Bractwo zawsze ma przewagê. TO by³o DO PRZEWIDZENIA.}
{267} {} {Nastêpnym razem wygram, Rycerzu Graham.}
{268} {} {Byæ mo¿e wygra³eœ grê, ale i tak przegrasz wojnê.}

{270} {} {Zagramy ponownie w karty?}
{271} {} {Jeœli nadal bêdê traciæ zapasy, zostanê tylko w brudnych gaciach. Jako Rycerz, mówiê stop hazardowi.}
{272} {} {Ok, cokolwiek powiesz...}

#Zapytania
{280} {} {Czyj to dzieciak biegaj¹cy po górnym pok³adzie?}
{281} {} {Ach, to jest Jung. Syn jednego z naszych paladynów. Nie zwracaj uwagi. Nie jesteœmy szczególnie zadowoleni z tej ma³py.}
{282} {} {Rozumiem. Na razie zapomnijmy o Jungu.}
{283} {} {Co jest nie tak z dzieckiem na statku?}
{284} {} {To jest g³ównie baza wojskowa. Dok³adniej, placówka. To nie jest miejsce na doczesne sprawy.}
{285} {} {Ojciec jest paladynem. A kim jest matka?}
{286} {} {S³uchaj, to nie twoja sprawa. Jasne? Dlaczego tak siê martwisz o czyj¹œ przesz³oœæ? Zadbaj o swój interes.}
{287} {} {Co to jest ma³pa?}
{288} {} {Um... nie wiem. To tylko stare wyra¿enie.}

{290} {} {Opowiedz mi o swoim Bractwie.}
{291} {} {Heh, co ignorant taki jak ty powinien wiedzieæ o Bractwie? Tylko tyle, ¿e na Pustkowiach nie ma wiêkszej mocy ni¿ my.}
{292} {} {Chêtnie uwierzê. Na tym koñczy siê rozmowa o Bractwie.}
{293} {} {Brzmi powa¿nie, ale tak naprawdê nie s³ysza³em o tobie w Arizonie.}
{294} {} {Ale jesteœmy dobrze znani w Kalifornii. Wiedz¹ i boj¹ siê, bo to my zniszczyliœmy Mistrza i ca³¹ jego armiê. Jak mo¿esz tego nie wiedzieæ? Dobry Bo¿e, dok¹d zmierza ten kraj...}
{295} {} {Nie bêdê siê k³óciæ. Ale co takiego zrobiliœcie, ¿e nale¿y siê was baæ?}
{296} {} {Mamy du¿o do zrobienia w Arizonie, ale zwykli ludzie nie wiedz¹ o nas zbyt wiele. Ale w Kalifornii ka¿dy kundel na Pustkowiu wie, ¿e to my zniszczyliœmy armiê Mistrza.}
{297} {} {Ok, to wszystko sprawia wra¿enie potêgi. Ale co doprowadzi³o Twój zakon do takiej chwa³y?}
{298} {} {Ostatnio odnieœliœmy wiele wspania³ych zwyciêstw. Czy wiesz coœ o Mistrzu? Plotki o tej wojnie napewno dotar³y nawet do Arizony.}
{299} {} {Kim jest ten Mistrz?}
{300} {} {Powiedz mi coœ wiêcej.}
{301} {} {Kiedy ju¿ zaczniesz, powiedz mi wiêcej.}
{302} {} {Mistrz by³ przeklêtym psychopat¹, którego zmutowany mózg da³ pocz¹tek idei uniwersalnej przemiany ludzi w mutantów. Myœla³, ¿e to uratuje ludzkoœæ przed wyginiêciem.}
{303} {} {Kontynuuj.}
{304} {} {Niez³y pomys³.}
{305} {} {Uda³o mu siê stworzyæ wokó³ siebie kult i zebraæ armiê super mutantów. Nikt na Pustkowiach nie móg³ siê równaæ z tak¹ moc¹. Nikt oprócz nas.}
{306} {} {Co zrobiliœcie?}
{307} {} {I oczywiœcie wam siê to nie podoba³o?}
{308} {} {To by³ rok wspania³ych bitew i wielkich zwyciêstw. Pokonaliœmy armiê Mistrza i zniszczyliœmy j¹ eksplozj¹ nuklearn¹. Do tej pory tu i ówdzie spotyka siê resztki jego s³ugusów, ale nie stanowi¹ ju¿ one poprzedniego zagro¿enia.}
{309} {} {Czy te¿ bra³eœ udzia³ w tej wojnie?}
{310} {} {Super. Chcia³bym zobaczyæ te bitwy.}
{311} {} {Och, jasne. Tutaj ka¿dy ma swoj¹ w³asn¹ historiê walki. Ja, na przyk³ad, broni³em siê w bitwie w Blasku Dnia. To by³a wspania³a rzeŸ.}
{312} {} {Musia³eœ to wszystko upiêkszyæ.}
{313} {} {Bractwo nigdy nie k³amie. Porozmawiaj z dowolnym rycerzem lub paladynem - tutaj wielu bra³o udzia³ w tych bitwach. Ja sam broni³em siê w bitwie o Blask Dnia.}
{314} {} {Czy mo¿esz mi powiedzieæ, jak by³o?}
{315} {} {Wygl¹da na to, ¿e nie mo¿na ciê ju¿ zatrzymaæ.}
{316} {} {Po klêsce super mutanci uciekli ze swojej bazy we wszystkich kierunkach. Najwiêksze grupy zdobywa³y po drodze ma³e osady. Z³omowo, Nekropolis, Blask Dnia, a nawet Hub zosta³y zaatakowane. Próbowaliœmy odpowiadaæ na proœby o pomoc.}
{317} {} {To bardzo szczytne, ¿e pomagasz zwyk³ym ludziom.}
{318} {} {Tak. Jakbyœcie robili to z dobroci serca.}
{319} {} {Dane wywiadowcze donosi³y, ¿e super mutanci za³o¿yli g³ówn¹ placówkê w Blasku dnia. Nasz oddzia³ mia³ ich zniszczyæ, ale zadanie nie by³o ³atwe. Wróg zorganizowa³ fort, a wokó³ fortu - z³o¿ony system pu³apek przeciwpiechotnych i okopów. W dodatku, chocia¿ miejscowi chcieli siê pozbyæ tych potworów, to oni te¿ nie byli z nas zadowoleni.}
{320} {} {Kontynuuj.}
{321} {} {Oczywiœcie. Kto lubi przebywaæ pomiedzy dwoma liniami ognia?}
{322} {} {Oblê¿enie trwa³o dwa tygodnie. Ze wzglêdu na oddalenie od g³ównej bazy nie mogliœmy liczyæ na zaopatrzenie i przygotowaliœmy siê najlepiej jak potrafiliœmy - zniszczyliœmy wrog¹ wêdzarniê, zatopiliœmy bunkry toksycznymi beczkami, a do wyworzenia gruzu wykorzystaliœmy miejscowych przestêpców. Super mutanty zosta³y odciête od œwiata zewnêtrznego i nie mog³y otrzymywaæ po¿ywienia.}
{323} {} {Czyli zag³odziliœcie ich na œmieræ?}
{324} {} {Czy myœlisz, ¿e to wspania³a bitwa?}
{325} {} {Pod koniec drugiego tygodnia super mutanci nie mieli wyboru. Czêœæ z nich podda³a siê, a druga próbowa³a wyrwaæ siê z oblê¿enia. Ostatnia bitwa by³a najbardziej brutalna i najtrudniejsza. Nasz dowódca wykaza³ siê niespotykanymi umiejêtnoœciami taktycznymi. Gdybyœmy na samym pocz¹tku podjêli siê oblê¿enia fortu, to teraz nie opowiada³bym tej historii.}
{326} {} {Wow, naprawdê jesteœcie obecnie najsilniejszymi, kogo mo¿na znaleŸæ.}
{327} {} {Tak, wydaje mi siê, ¿e umiecie walczyæ.}
{328} {} {Siedzenie pod oblê¿eniem nie jest szczególnie imponuj¹ce.}
{329} {} {Nie martw siê, synu. Zamienimy Arizonê w cywilizowane miejsce. Daj nam trochê czasu.}
{1329} {} {Nie martw siê, pani. Zamienimy Arizonê w cywilizowane miejsce. Daj nam trochê czasu.}
{330} {} {Och, œwietnie. Doskonale. Uh, pa.}
{331} {} {Bez w¹tpienia, po tym wszystkim, co s³ysza³em. Bardzo dziêkujê za te historie.}
{332} {} {Nie chcê, ¿eby coœ takiego wydarzy³o siê w Arizonie. Na szczêœcie s¹ tu dobrzy ludzie.}

{340} {} {Wiesz, co siê sta³o z Paladynem Bellem?}
{341} {} {Czego chcesz? Nawet go nie znasz, walczylismy ramiê w ramiê. Zostaw go, to nie twoja sprawa.}
{1341} {} {Czego chcesz? Nawet go nie znasz, walczylismy ramiê w ramiê. Zostaw go, to nie twoja sprawa.}
{342} {} {Próbujê go wyleczyæ. A do tego potrzebujê szczego³ów.}
{343} {} {Postrada³ rozum podczas twoich bitew, co?}
{344} {} {Co ty... Och, dobrze. S³uchaj, byliœmy z nim na ró¿nych patrolach. Ale rozum postrada³ dopiero niedawno. Do tego nigdy siê na nic nie skar¿y³, wiêc móg³ zostaæ zraniony wszêdzie.}
{345} {} {Mówi³ o jakiejœ pustyni popio³ów w piekle. Jak myœlisz, co to znaczy?}
{346} {} {Pustynia popio³ów? Nawet nie wiem... Chocia¿ jest jedno miejsce, obok Casa Nueva. Wydobywano tam cement, wiêc wszystko wokó³ jest szare.}
{347} {} {Czy mia³eœ tam misjê?}
{348} {} {Nie powiedzia³em ci tego, ale w pewnym momencie pracownicy kamienio³omu zaczêli znikaæ. Jeden po drugim. Zostaliœmy wys³ani, aby zaj¹æ siê tym problemem.}
{349} {} {Kontynuuj.}
{350} {} {ZnaleŸliœmy wypatroszone szcz¹tki ludzi, jakby ktoœ je rozerwa³ na strzêpy. Ale ani ¿adnego maniaka, ani bestii nigdy nie znaleziono. Bell te¿ by³ z nami. Wtedy po raz pierwszy poczuliœmy, ¿e coœ jest z nim nie tak.}
{351} {} {Wiêc kamienio³om obok Casa Nueva. To ju¿ jest coœ. Dziêki i do widzenia.}