{100} {} {Widzisz komputer skryby.}
{101} {} {Widzisz komputer z dostêpem do wspó³dzielonej sieci.}
{102} {} {Pomyœlnie skopiowano bibliotekê skryb.}
{103} {} {Ju¿ skopiowano bibliotekê na holodysk.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Dalej.}
{204} {} {Wróæ do menu g³ównego.}

{210} {} {Poszukiwania Krypt Vault-Tec.}
{211} {} {Wed³ug ostatnich doniesieñ krypty Vault-Tec o numerach 23-28 mog¹ znajdowaæ siê w pobli¿u Phoenix. Sztab Generalny Bractwa Stali nakaza³ znaleŸæ wszystkie te schrony, zbadaæ sytuacjê i wykorzystaæ dostêpne tam zasoby i sprzêt do samodzielnego utrzymania siê lub transportu do Sztabu Generalnego.}
{212} {} {Krypta 23.}
{213} {} {Lokalizacja nieznana. Krypta jest prawdopodobnie zniszczona lub znajduje siê w innym regionie.}
{214} {} {Krypta 24.}
{215} {} {Lokalizacja nieznana. Krypta jest prawdopodobnie zniszczona lub znajduje siê w innym regionie.}
{216} {} {Krypta 25.}
{217} {} {Krypta zosta³a znaleziona w Phoenix i jest w doskona³ym stanie. Obecnie znajduje siê pod kontrol¹ Bractwa Stali i s³u¿y jako podstawa Katedry Ognia. Czêœæ sprzêtu zosta³a zdemontowana i przewieziona do placówki w Puerto Penasco.}
{218} {} {Krypta 26.}
{219} {} {Pozosta³oœci Krypty znaleziono na zachód od Phoenix. Z powodu powa¿nych zniszczeñ, jakich dozna³a podczas bombardowania atomowego, schron wraz z wyposa¿eniem popad³ w kompletn¹ ruinê.}
{220} {} {Krypta 27.}
{221} {} {Lokalizacja Krypty jest znana. W tej chwili trwaj¹ poszukiwania i wykopywanie schronu przez si³y Katedry Ognia pod dowództwem paladyna Ulisses Granta.}
{222} {} {Krypta 28.}
{223} {} {Lokalizacja jeszcze nieznana. Krypta jest prawdopodobnie zniszczona lub znajduje siê w innym regionie.}

{230} {} {Rozwój magazynków nanostrukturalnych.}
{231} {} {Ze wzglêdu na brak amunicji przeciwpancernej i jej okresowe zapotrzebowanie rozpoczêto ograniczon¹ produkcjê nanostrukturalnych metalowych nabojów 10 mm.}
{232} {} {Kule s¹ wytwarzane przez osadê Blacharzy w Tu-San na podstawie standardowego kontraktu handlowego.}
{233} {} {}
{234} {} {Samowystarczalne jedzenie.}
{235} {} {Dziêki plantacjom Casa Nueva mogliœmy w pe³ni zaspokoiæ nasze potrzeby ¿ywieniowe. W tej chwili zbiory s¹ równie¿ eksportowane.}
{236} {} {Rozwój broni j¹drowej.}
{237} {} {Zgodnie z proœb¹ Sztabu Generalnego przechodzimy do produkcji broni j¹drowej. W tej chwili dokumentacja projektu zosta³a ukoñczona i trwa wydobycie wymaganej iloœci materia³u j¹drowego.}
{238} {} {Ze wzgledów bezpieczeñstwa, logistyki i oszczêdnoœci czasu ostateczna broñ jest sk³adana w Katedrze Ognia w Phoenix pod œcis³¹ kontrol¹ Bractwa Stali.}