{100} {} {Widzisz komputer dowodzenia.}
{101} {} {Widzisz komputer Wielkiego Paladyna.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Dalej.}
{204} {} {Wróæ do menu g³ównego.}

{210} {} {Akta szeregowego Corwina.}
{211} {} {Nazywa siê Alvin Corwin. Jest nowicjuszem. Kandydat na paladyna. Stan zdrowia normalny.}
{212} {} {W imieniu Paladina Dixona, wystaw urlop dla Corwina.}
{213} {} {Rozkaz przyjêty.}
{214} {} {Swietnie. Pójdê teraz uszczêœliwiæ Alvina.}

{220} {} {Otwórz wiadomoœci Dixona.}
{221} {} {"Wspó³czesny œwiat potrzebuje si³y. Rodzaj si³y, która podniesie go z kolan i uniesie ramiê, by zrobiæ krok naprzód. I tylko Bractwo Stali ma wszystko, czego potrzebuje. Ale zakon od dawna trzyma siê z daleka od spraw zewnêtrznych. Kiedy nad Kaliforni¹ czai³a siê groŸba zag³ady ze strony super mutantów, byliœmy tymi, którzy byli w stanie siê jej oprzeæ. Nie mo¿emy ju¿ siedzieæ w naszym bunkrze. Wojna jeszcze siê nie skoñczy³a. Nasi bracia i siostry w Lost Hills potrzebuj¹ technologii i zasobów Sonory. Wzmocnijmy nasz¹ stal, aby razem stawiæ czo³a wrogowi! ”}
{222} {} {Flaga misji narodowej.}
      # title - nawiazanie do filmu „Prison Rock” z 1955 roku
{223} {} {Nasze cele i zadania wymagaj¹ zdecydowanych dzia³añ w celu zjednoczenia i kontrolowania dzikiej przyrody by³ej Arizony. Tylko w ten sposób mo¿emy zbudowaæ potrzebn¹ nam infrastrukturê. W kluczowych miastach powinien powstaæ rz¹d przyjazny Bractwu Stali. Niezadowolenie z nowego rz¹du powinno zostaæ st³umione, a ludnoœæ reedukowana.}
{224} {} {Projekt Lame Duck.}
      # name to termin polityczny w Stanach Zjednoczonych
{225} {} {Konieczne jest jak najszybsze ustanowienie zjednoczonej w³adzy nad miastem Phoenix z pe³n¹ kontrol¹ Bractwa. W ramach tej nowej w³adzy trzeba zorganizowaæ ukryte cia³o doradcze i nadzorcze z cz³onkiem Bractwa Stali na czele.}
{226} {} {Operacja Wind of War.}
{227} {} {Konieczne jest zorganizowanie i umocnienie kolonii na terytorium miasta Nogales, aby kontrolowaæ granicê z Meksykiem. Wed³ug wywiadu osada znajduje siê pod presj¹ wrogiej armii meksykañskiej.}
{228} {} {Nasz g³ówny cel.}
{229} {} {Naszym g³ównym celem jest zapewnienie Sztabowi Generalnemu w Lost Hills zapasów energii j¹drowej i technologii, która przetrwa. Ze wzglêdu na oddalenie placówki w Puerto Penasco, Wysoki Paladyn Dixon otrzymuje specjalne uprawnienia i swobodê podejmowania decyzji.}

{240} {} {Przeczytaj dziennik Dixona.}
{241} {} {"...Sztab Generalny w Kalifornii nie wys³a³ mnie do Arizony, aby to miejsce rozkwit³o mi³oœci¹ i wolnoœci¹. Naszym celem jest zebranie staro¿ytnych technologii i innych zasobów, tak potrzebnych Bractwu w tych trudnych czasach. Miejscowi ludzie absolutnie nie rozumiej¹ swojej wartoœci i kryminalnie wydaj¹ to, co zosta³o z ery przedwojennej... "}
{242} {} {"...Cokolwiek ci skrybowie pisz¹ w swoich papierach, nie jesteœmy tu dla pokoju, ale dla wojny. Miejscowi nie chc¹ dobrowolnie oddaæ technologii i zasobów. Zdobycie Phoenix by³o krwawym przedsiêwziêciem tylko dlatego, ¿eby nie skoñczy³o siê gorzej. Jesteœmy * zmuszeni * zmusiæ ludnoœæ do pokoju, aby osi¹gn¹æ nasze cele... "}
{243} {} {"...Wiem, ¿e sztab generalny Lost Hills nie akceptuje tak drastycznych œrodków. Ale jak inaczej mo¿emy byæ samowystarczalni? Nasz g³ówny zasób, Ÿród³o energii j¹drowej, jest wydobywany daleko w kopalni Flagpool i transportowany do warsztatów Tu-San, a nastêpnie transportowany przez pustyniê do placówki i dalej do Lost Hills. Wymaga to du¿o pracy i decyzji. Na tych opuszczonych ziemiach, z dala od domu, nie mamy czasu na myœlenie o moralnoœci... "}
{244} {} {"...W Arizonie lokalna kultura jest zbyt silna. Wiele rodzin mieszka tu od pokoleñ i bardzo trudno jest prze³amaæ ich konserwatyzm. Spêdziliœmy kilka lat, aby osiedliæ siê w Phoenix przez kult Aarona. A i tak nadal dzia³aj¹ tam buntownicy. Blacharze z Tu-San s¹ po naszej stronie, ale nasz traktat mo¿e wygasn¹æ w ka¿dej chwili. Dlatego nie mamy prawa zwlekaæ. Musimy zabraæ WSZYSTKO, co nale¿y do nas, tu i teraz... ”}
{245} {} {Zamknij dziennik Dixona.}
{246} {} {Czytaj wiêcej.}
