{110} {} {Nie mo¿na anulowac salwy.}
{111} {} {Wczeœniej mia³o to sens. Ale nie teraz, kiedy jestem po stronie Bractwa.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}
{203} {} {Anuluj.}
{204} {} {Akceptuj.}
{205} {} {Zaakceptuj okreœlone parametry.}
{206} {} {Dalej.}

{210} {} {Ustaw parametry torpedy.}
{211} {} {Okreœl ustawienia.}
{212} {} {Odrzuæ wszystkie wprowadzone dane.}
{213} {} {Zatrzymaj wprowadzanie danych i zakoñcz sesjê.}
{214} {} {Przywrócono oryginalne ustawienia.}

{220} {} {K¹t widzenia AIM-US.}
{221} {} {K¹t widzenia MANUAL.}
{222} {} {Bie¿¹cy k¹t: }
{223} {} { stopni.}
{224} {} {+ 10 stopni.}
{225} {} {+ 1 stopieñ.}
{226} {} {- 1 stopieñ}
{227} {} {- 10 stopni.}
{228} {} {K¹t widzenia.}

{230} {} {Odleg³oœæ do celu.}
{231} {} {Szacowana odleg³oœæ: }
{232} {} { jardów.}
{233} {} {+ 100 jardów.}
{234} {} {+ 10 jardów.}
{235} {} {+ 1 jard}
{236} {} {- 1 jard}
{237} {} {- 10 jardów.}
{238} {} {- 100 jardów.}

{240} {} {Tryb salwy.}
{241} {} {Bie¿¹cy tryb: }
{242} {} {K¹t rozproszenia: }
{243} {} {Jedna torpeda.}
{244} {} {Dwie torpedy.}
{245} {} {Wszystkie torpedy.}
{246} {} {}
{247} {} {k¹t rozproszenia}
{248} {} {0,5 stopnia.}
{249} {} {1 stopieñ.}
{250} {} {1,5 stopnia.}
{251} {} {2 stopnie.}

{260} {} {Prêdkoœæ torpedy.}
{261} {} {Aktualna prêdkoœæ: }
{262} {} { wêz³ów.}
{263} {} {+ 5 wêz³ów.}
{264} {} {- 5 wêz³ów.}

{270} {} {G³êbokoœæ wybuchu.}
{271} {} {G³êbokoœæ wybuchu: }
{272} {} { jardy.}
{273} {} {+ 1 jard}
{274} {} {- 1 jard}

{280} {} {Typ bezpiecznika.}
{281} {} {Typ bezpiecznika: }
{282} {} {Niezdefiniowane.}
{283} {} {Kontakt.}
{284} {} {Magnetyczny.}
{285} {} {Timer.}

{290} {} {Ustaw licznik czasu, aby aktywowaæ torpedy.}
{291} {} {Czas do wybuchu: }
{292} {} { sekund.}
{293} {} {+ 10 sekund.}
{294} {} {- 10 sekund.}

{300} {} {Uruchom torpedy.}
{301} {} {Uwaga! Mechanizm otwierania luku nie odpowiada.}
{302} {} {Swietnie, wiêc nigdzie siê nie oddal¹. Aktywuj torpedy.}
{303} {} {O nie, nie, nie chcê tego robiæ. Anuluj, anuluj!}
{304} {} {Torpedy odbezpieczone. Odpalenie za... }
{305} {} { sekund.}
{306} {} {Ups, czas zejœæ z ton¹cego statku...}
{307} {} {Losowe naciskanie przycisków.}
{308} {} {Ups, wygl¹da na to, ¿e zaczê³o siê odliczanie...}