{110} {} {Widzisz torpedy o napêdzie atomowym.}
{111} {} {To musi byæ cholernie potê¿ne.}
{112} {} {Widzisz torpedy o napêdzie atomowym. I s¹ odbezpieczone. }
{113} {} {Czas siê st¹d wydostaæ...}
{114} {} {Wczeœniej mia³o to sens. Ale nie teraz, kiedy jestem po stronie Bractwa.}

{120} {} {To jest torpeda nuklearna. Gdzieœ w pobli¿u powinien znajdowaæ siê panel kontrolny przedzia³u torpedowego.}
{121} {} {Nie ma tu nic do naprawienia.}
{122} {} {To urz¹dzenie jest dla Ciebie zbyt skomplikowane. Torpedy mo¿na aktywowaæ na inne sposoby.}
{123} {} {Pomyœlnie aktywowano licznik torped.}
{124} {} {Pomyœlnie dezaktywowano licznik torped.}
{125} {} {Nie mo¿na dezaktywowaæ licznika czasu.}

{150} {} {Do wybuchu pozosta³o }
{151} {} { sekund.}
