{100} {} {Widzisz kwatermistrza.}
{101} {} {Widzisz Blacharza odpowiedzialnego za magazyn. Jego ogolon¹ g³owê przykrywa potê¿ny he³m.}
{102} {} {Pancerz wspomagany T51b... Zastanawiam siê, jak TOBIE uda³o siê okie³znaæ tak wyrafinowan¹ technikê?}

# Pierwszy dialog
{200} {} {(jakby ciê nie zauwa¿a³) Piêæ tysiêcy sto osiemdziesi¹t szeœæ... nie, to nie pasuje...}
{201} {} {Hej, co robisz?}
{202} {} {(nie podnosz¹c g³owy z nad listy) Jestem odpowiedzialny za magazyn i handel. Jeœli nie handlujesz, idŸ do naszego szefa, jest na górze.}
{203} {} {Rozumiem.}

# Powtarzajacy siê dialog
{210} {} {Tak?}
{211} {} {Niewa¿ne.}

{216} {} {Master Hard doda³ Ciê do naszej listy partnerów. Oznacza to, ¿e mo¿esz liczyæ na specjalne ceny w tym magazynie.}
{217} {} {Wspania³e wieœci.}
{218} {} {Master Hard uwa¿a, ¿e zas³ugujesz na lepsz¹ zni¿kê ni¿ zwykli partnerzy. Doceñ jego gest.}
{219} {} {Wiêc bêdzie jeszcze taniej? Wspaniale.}

{220} {} {Po co ci ca³y ten sprzêt?}
{221} {} {Pomaga nam w pracy. Wy, dzikusy z pustkowia, jesteœcie trudni do zrozumienia.}
{222} {} {Sk¹d to masz?}
{223} {} {Rozejrzyj siê - to miejsce jest wype³nione zaawansowan¹ technologi¹, o której wy, dzicy, nawet nie wiecie. Ujarzmiliœmy staro¿ytne technologie i korzystamy z nich wed³ug w³asnego uznania. Ten komputer to tylko jeden z naszych ma³ych projektów.}
{224} {} {Tak to jest.}

# O produkcie
{230} {} {Czym tu handlujesz?}
{231} {} {Tu-San zawsze by³o znane ze swojej technologii. Ale nie ka¿dy na ni¹ zas³uguje.}
{232} {} {Rozumiem.}
{233} {} {Czy przyjmujecie przedwojenne pieni¹dze?}

{240} {} {Nie, tylko kapsle.}
{241} {} {Dlaczego?}
{242} {} {Kapsle jako waluta s¹ obs³ugiwane przez Koœció³ Swiêtego Ognia w Phoenix. Chocia¿ nie podoba mi siê ten pomys³ z nieporêcznymi kapslami. Moglibyœmy robiæ nowe monety na naszych maszynach. I kiedyœ tak siê stanie.}
{243} {} {Kapsle jako waluta by³y obs³ugiwane przez Koœció³ Swiêtego Ognia w Phoenix. Chocia¿ koœció³ zosta³ zniszczony, kapsle pozostan¹ najbardziej wiarygodn¹ walut¹ przez wiele lat.}
{244} {} {Rozumiem.}
{245} {} {Sk¹d macie tak wiele makaronów w puszkach?}
{246} {} {Z niedawno znalezionych i otwartych magazynów wojskowych. Doskona³e racje wojskowe. Chocia¿ monotonia czasami gnêbi nawet nas, Blacharzy.}
{247} {} {Kluski sprawiaj¹, ¿e puchnê. Coœ jeszcze?}
{248} {} {Có¿... nie.}
{249} {} {Przepraszam.}
{250} {} {Có¿... jest coœ. Nie pytaj, sk¹d to mam, ale to najlepsze jedzenie, jakie mo¿na znaleŸæ. (pokazuje trzy pojemniki oznaczone „RPI”) Nie bêdzie to tanie.}
{251} {} {"Indywidualna dieta"? Brzmi dobrze, pomyœlê o twojej propozycji.}
{252} {} {Dasz zni¿kê cz³onkowi Bractwa Stali, prawda?}
{253} {} {Dasz zni¿kê Wyznawcy Ognia, prawda?}
{254} {} {Oczywiœcie. Nasi przyjaciele zas³uguj¹ na szacunek.}
{255} {} {Swietnie.}
{256} {} {Makaron... Czy nie ma nic lepszego?}

# Jeœli ZAX zniszczy³ wioskê:
{260} {} {Swiêty Amperze! Co Ty tutaj robisz?! Po inwazji robotów nie spodziewa³em siê, ¿e zobaczê kogoœ w Tu-San. Moi towarzysze zginêli, a mieszkañcy wioski uciekli z miasta. Nie s¹dzi³em, ¿e przyjedzie tu jakikolwiek podró¿nik.}
{261} {} {Dlaczego ty nie odchodzisz?}
{262} {} {Nie mam dok¹d pójœæ. Zna³em tylko Blacharzy. A bez technologii jeszcze bardziej nie bêdê w stanie przetrwaæ. Ale jest jeden pomys³ - spróbujê zrobiæ lataj¹c¹ platformê i polecê na niej do Kalifornii. Tam prawdopodobnie znajdzie zastosowanie.}
{263} {} {To wszystko. Pójdê ju¿.}
{264} {} {Jak prze¿y³eœ?}
{265} {} {Znam dobrze to miejsce. I mam sprzêt do oszukiwania robotów. Ale to tylko kwestia czasu a¿ mnie znajd¹.}
{266} {} {Czy nadal masz przedmioty do wymiany?}

# Poszukiwanie ogniwa energetycznego
{269} {} {Tymczasowo wstrzymaliœmy handel energi¹ do czasu wznowienia produkcji w kopalniach Flagpool. Poszukaj ogniw w innym miejscu.}
{270} {} {Potrzebujê ogniwa zasilaj¹cego do generatora.}
{271} {} {To jest zbyt cenna technologia, by daæ j¹ komukolwiek.}
{272} {} {Podaj swoj¹ cenê.}
{273} {} {Po wydarzeniach w Zakazanej Strefie zas³ugujê na zaufanie.}
{274} {} {Oto moja cena. (dodaje przedmiot do reszty towaru) Jeœli ci siê nie podoba, mo¿esz wyjœæ.}
{275} {} {Niech pomyœlê.}
{276} {} {W moim œrodowisku te elementy staj¹ siê nieistotne. Jestem gotów je sprzedaæ.}
{277} {} {Prawid³owe rozwi¹zanie.}
{278} {} {Powtarzam, ten przedmiot nie jest na sprzeda¿.}
{279} {} {ChodŸ...}

# Ujawnienie produktu
{280} {} {Mam rozleg³e kontakty w ca³ej Arizonie i prowadzenie interesów ze mn¹ jest korzystne.}
{281} {} {Mo¿e tak. Ale same s³owa nie wystarcz¹.}
{282} {} {Chcia³bym, ¿ebyœ móg³ dostrzec swój zysk.}
{283} {} {Ok, wystarczy. Przyjrzyj siê tym piêknym produktom technicznym i podaj cenê.}
{284} {} {Tak po prostu.}
{285} {} {Teraz, gdy Master Hard wypad³ z interesu, nie ma sensu trzymaæ ca³ego tego towaru.}
{286} {} {Po demonta¿u Master Harda nie mam innego wyjœcia, jak tylko handlowaæ ze wszystkimi. Oto wszystkie moje towary.}
{287} {} {Dobra decyzja.}
{288} {} {Master Hard da³ mi rozszerzone zezwolenie na handel.}
{289} {} {Czy mogê liczyæ na jakiœ „wartoœciowy” przedmiot?}
{290} {} {Nie. Jednak Master Hard mo¿e zdecydowaæ inaczej.}
{291} {} {Wiêc powinienem z nim porozmawiaæ.}
{292} {} {Nie s¹dzê.}
{293} {} {Ok.}
{294} {} {Potrzebujesz klientów bardziej ni¿ kiedykolwiek.}
{295} {} {Wspó³praca ze mn¹ siê op³aca.}

#Upgrades
{300} {} {Czy mo¿ecie naprawiæ mój sprzêt?}
{301} {} {Co dok³adnie? Technologia, broñ, zbroja? Pracujemy z technologi¹. Ale to bêdzie Ciê kosztowaæ spor¹ liczbê kapsli.}
{302} {} {Zapomnij.}
{303} {} {Mówiê o moim motorze.}
{304} {} {Hmm... nigdy nie majstrowa³em przy tej technice. Czêœci do motocykli s¹ tutaj rzadkie, s¹ tu g³ównie ciê¿kie wojskowe ciê¿arówki i samoloty.}
{305} {} {[Dalej.]}
{306} {} {Ale wiesz co, mogê spróbowaæ przyœpieszyæ motor za pomoc¹ czêœci do samolotu. Jednak bêdziesz musia³ najpiew zainstalowaæ mocne opony i wzmocniæ silnik, w przeciwnym razie mog¹ nie poradziæ sobie ze zwiêkszonym obci¹¿eniem.}
{307} {} {Czy potrafisz to zrobiæ?}
{308} {} {Mówiê ci - nie mam opon ani innych czêœci motocyklowych. Pomyœl o miejscach, w których s¹ stare gara¿e, prawdopodobnie bêdzie tam przynajmniej coœ przydatnego.}
{309} {} {Rozumiem. Wrócê, gdy wzmocniê swój motor.}
{310} {} {Wszystko gotowe. Mistrz w Garage City ulepszy³ zarówno opony, jak i uk³ad napêdowy. Opowiedz mi o tej modyfikacji z czêœci do samolotu.}
{311} {} {Samoloty u¿ywa³y najpotê¿niejszych uk³adów napêdowych, ale niektóre z tych czêœci mogê dostosowaæ do motocykla. Aby zapobiec przegrzaniu systemu, bêdziesz potrzebowaæ równie¿ dobrych rur wydechowych i termicznych. Poza tym kilka nowych modu³ów do komputera pok³adowego nie zaszkodzi... I byæ mo¿e lepszej jakoœci smar lotniczy.}
{312} {} {Brzmi dobrze.}
{313} {} {Szybko przeliczaj¹c, zwiêkszy³oby to prêdkoœæ maszyny o 40%. Ci¹gle zainteresowany? Wiêc przygotuj }
{314} {} { kapsli, poniewa¿ ta us³uga jest bardzo pracoch³onna.}
{315} {} {Oto kapsle. Montuj ten cholerny wzmacniacz!}
{316} {} {Nie staæ mnie jeszcze na taki luksus. Przez chwilê bêdê musia³ jeŸdziæ jeszcze z prêdkoœci¹ bramina.}
{317} {} {Jakoœ spodziewa³em siê takich sztuczek. Od was dzikusów z pustkowia nie mo¿na oczekiwaæ niczego wiêcej.}
{318} {} {Nie mia³em tego na myœli...}
{319} {} {Ta-dam! Twój motor zmieni³ siê nie do poznania. Pytasz czy jeszcze jeŸdzi? Cz³owieku, on za-pier-da-la!}
{320} {} {Brzmi zbyt skomplikowanie, drogo i niepraktycznie. Byæ mo¿e dam sobie radê bez tego.}

{330} {} {Mistrz Hard mówi³ o nagrodzie dla mnie.}
{331} {} {Dobrze. Nagroda to: metalowa zbroja, pistolet laserowy, gogle noktowizyjne. Korzystaj z tych darów m¹drze.}
{332} {} {Dobrze to wykorzystam.}
{333} {} {Dobrze. Oto lista dostêpnych nagród. Wybierz i zaznacz krzy¿ykiem.}
{334} {} {[Metalowa zbroja]}
{335} {} {[Pistolet plazmowy]}
{336} {} {[Zestaw medyczny: 3 stymulanty, 3 antidotum, 1 antyrad]}
{337} {} {[Stealth Boy i noktowizor]}
{338} {} {[Jednostka j¹drowa]}
{339} {} {[350 kapsli]}
{340} {} {M¹drze korzystaj z tych darów.}
{341} {} {Dobrze to wykorzystam.}

{350} {} {Muszê naprawiæ mój pancerz wspomagany.}
{351} {} {Doskona³y przyk³ad starej technologii. Przejrzê awarie obwodów logicznych w mojej sieci neuronowej, gdy tylko spojrzê na tê zbrojê. Tak, mamy mo¿liwoœæ naprawienia wszystkich jej uszkodzeñ. Ale bêdzie to kosztowaæ bardzo du¿¹ liczbê kapsli.}
{352} {} {Smia³o.}
{353} {} {Nie. Byæ mo¿e samo Bractwo naprawi to za darmo.}
{354} {} {Pomyœlê o tym. W ka¿dym razie muszê wydostaæ siê z tej pow³oki.}

#Relikt
{400} {} {Mam stary zegarek atomowy. Rzucisz okiem?}
{401} {} {Swiêty Amperze! Ten zegarek ma sto lat, a nadal pokazuje godzinê.}
{402} {} {Wygl¹da na to, ¿e ciê to krêci.}
{403} {} {Nasi przodkowie byli nieskoñczenie m¹drzy. A teraz zbieramy pozosta³oœci ich technologii i z wielkim trudem odtwarzamy to, co robili w ci¹gu kilku minut. Ten zegar jest jedn¹ z tych precyzyjnych technologii, których nie mo¿emy odtworzyæ.}
{404} {} {Oddam go za darmo na znak zbli¿aj¹cych siê umów. Nie odmówisz mi swoich us³ug, prawda?}
{405} {} {To rozs¹dne. Mo¿esz liczyæ na bardziej korzystne ceny, dzik... pustynny cz³owieku.}
{406} {} {Bardzo dobrze.}
{407} {} {Sprzedam ten zegarek za 350 kapsli.}
{408} {} {Brzmi rozs¹dnie. Oto kapsle. Mam nadziejê, ¿e to nie bêdzie nasza ostatnia wymiana.}
{409} {} {Swietnie.}
{410} {} {Wiedza za technologiê. Dam ci zegarek, jeœli dostanê w zamian specyfikacjê energetyczn¹.}
{411} {} {Có¿, to sprawiedliwe. Mam potrzebne informacje. Z ich pomoc¹ na pewno poprawisz swoje umiejêtnoœci. Chocia¿ wielu z nas nie lubi, gdy zwykli ludzie przyk³adaj¹ rêkê do wielkich staro¿ytnych technologii.}
{412} {} {To mi siê przyda. Do zobaczenia, Blacharzu.}
{413} {} {Mamy doskona³¹ pneumatyczn¹ piêœæ, której u¿ywamy do wybijania wszelkich bzdur z umys³ów osób postronnych. Nie widzê zegara wœród twoich œmieci, dzikusie pustyni.}
{414} {} {Jak to siê sta³o...}
{415} {} {Daj mi czas na przemyœlenie. Nie martw siê, zegarek nie zepsuje siê w tym czasie.}
{416} {} {Kwatermistrz obni¿y³ koszt swoich towarów o 10%.}