{100} {} {Widzisz Jeffa.}
{101} {} {Widzisz przywódcê zbieg³ego gangu niewolników.}
{102} {} {Wkrótce udamy siê na pó³noc i po drodze bêdziemy rozpowszechniaæ prawdê o Blacharzach.}

{200} {} {Wiêc, twoje przybycie zosta³o mi zg³oszone. Przyznajê, ¿e jestem zdezorientowany. Kim jesteœ i co tu robisz?}

{201} {} {W³aœciwie to szukam tylko skarbów w tych ruinach...}
{202} {} {Oczywiœcie. I mam uwierzyæ w te bzdury? Znasz nasz¹ lokalizacjê, z powodzeniem omijasz pu³apki, a jest to œrodek rozleg³ego terytorium le¿¹cego w ruinach. Ostatni raz pytam, co ty tu robisz, do cholery?}
{203} {} {Mówiê prawdê.}
{204} {} {Hmm... Wygl¹dasz jak doœwiadczony padlino¿erca, najwyraŸniej musia³eœ przejœæ ponad milê... Ok, uwierzê ci... tym razem.}
{1204} {} {Hmm... Wygl¹dasz jak doœwiadczony padlino¿erca, najwyraŸniej musia³aœ przejœæ ponad milê... Ok, uwierzê ci... tym razem.}
{205} {} {Dobrze, ¿e siê dogadaliœmy.}
{206} {} {W takim razie zobaczmy, co powiesz, kiedy zawiesimy ciê nad p³on¹c¹ beczk¹. Zatrzymaæ szpiega!}
{207} {} {Hej, spokojnie!}
{208} {} {}
{209} {} {}

{210} {} {Uciek³em z obozu pracy i potrzebujê pomocy.}
{1210} {} {Uciek³am z obozu pracy i potrzebujê pomocy.}
{211} {} {Wszyscy byliœmy kiedyœ niewolnikami Blacharzy. Ale uda³o nam siê uciec. A teraz naszym celem jest wymierzenie sprawiedliwoœci tym, którzy stawiaj¹ siê ponad nami. Myœlê, ¿e ty i ja bêdziemy pracowaæ teraz razem.}
{212} {} {Dobrze, ¿e znaleŸliœmy porozumienie.}

{220} {} {Jestem tutaj w imieniu Blacharzy. Badaj¹ atak na karawanê.}
{221} {} {Tak, to by³a nasza robota... Dok³adniej, nasze osi¹gniêcie. Przygotowania do tej operacji zajê³y ca³y miesi¹c, ale zrobiliœmy to. Teraz Blacharze zrozumiej¹, ¿e nie s¹ sami na Pustkowiu. A zaopatrzenie, które uzyskaliœmy, zostanie u¿yte w dobrej sprawiê naszej walki.}
{222} {} {Rozumiem.}
{223} {} {Rozumiesz, ¿e nie mogê teraz pozwoliæ ci odejœæ. Czy masz coœ do powiedzenia?}
{224} {} {Jestem tylko najemnikiem. Nie obchodzi mnie, kto dla kogo pracuje.}
{225} {} {Niewa¿ne. Poniewa¿... zaraz umrzesz!}
{226} {} {Nie walczymy o kapsle, ale o ideê - aby ocaliæ Pustkowia przed gnij¹cym „postêpem”. (pluje z pogard¹)}
{227} {} {[Dalej.]}
{228} {} {Ale zepsute rzeczy, takie jak ty, nie mog¹ zostaæ naprawione. Zabijcie go!}
{1228} {} {Ale zepsute rzeczy, takie jak ty, nie mog¹ zostaæ naprawione. Zabiæ j¹!}
{229} {} {Hej, spokojnie!}
{230} {} {Hmm... Móg³byœ byæ naszymi oczami i uszami za liniami wroga.}
{1230} {} {Hmm... Mog³abyœ byæ naszymi oczami i uszami za liniami wroga.}
{231} {} {Dobrze, ¿e znaleŸliœmy porozumienie.}

{240} {} {Na razie pozwolê ci pozostaæ w naszej kryjówce. Ale jeœli wydasz mi siê podejrzany, nie licz na drug¹ szansê.}
{241} {} {Ok, rozumiem.}

# Powtarzajacy siê dialog
{250} {} {To nasz najnowszy cz³onek ruchu oporu. Masz coœ do zg³oszenia?}
{251} {} {Na razie nic.}
{252} {} {Rozumiem. Zadnych wiêcej pytañ.}

{260} {} {Zastanawiam siê, sk¹d wszyscy pochodzicie?}
{261} {} {Ka¿dy z nas by³ kiedyœ niewolnikiem Blacharzy. Zostaliœmy wys³ani do Zakazanej Strefy, aby wydobyæ przydatne zasoby, ale niektórym uda³o siê uciec. Daleko st¹d nie da siê uciec, dlatego musieliœmy osiedliæ siê w tych ruinach i przetrwaæ na w³asn¹ rêkê.}
{262} {} {Jest tu coœ cennego?}
{263} {} {Staro¿ytne przedmioty technologiczne. Wiele z nich od dawna nie pracowa³o, a niektóre s¹ zbyt niebezpieczne, aby chocia¿ je dotkn¹æ. Dlatego niespokojny duch starych technologii sprzeciwi³ siê naszej obecnoœci i zacz¹³ niszczyæ wszystkich ludzi w Zakazanej Strefie, nawet jeœli nie s¹ tu z w³asnej woli.}
{264} {} {Jak uda³o ci siê uciec z Zakazanej Strefy?}
{265} {} {Ka¿dy ma swoj¹ historiê, ale g³ównie pomogli nam nasi poprzednicy. Jestem ostatni¹ osob¹ ze starego ruchu oporu.}
{266} {} {Dlaczego st¹d nie wyjdziecie?}
{267} {} {Jesteœmy jak ta stara krypta. Blacharze zniszczyli wszystko, co by³o nam drogie, ale staramy siê zachowaæ choæ trochê ¿ycia, do którego jesteœmy przyzwyczajeni. Jeœli nie dla nas, to dla naszych bliskich, którzy mogliby jeszcze przetrwaæ na pustkowiu.}
{268} {} {Kiedy mówisz o przetrwaniu, masz na myœli atakowanie podró¿ników?}
{269} {} {Te¿. Naszym najgorszym wrogom zapewniono wszystko, czego potrzebuj¹ od handlarzy pustkowi. Nie trzeba ich jednak zabijaæ - wystarczy odstraszyæ ich na tyle, ¿eby tu nie wracali.}

# Proba palenia niewolników z TuSan
{270} {} {Jak mogê pomóc Twojemu ruchowi oporu?}
{1270} {} {Jak mogê pomóc Twojemu ruchowi oporu?}
{271} {} {Potrzebujemy szpiega. Wróæ do obozu Blacharzy i znajdŸ nam informacje o pobliskich karawanach. Powinny znajdowaæ siê na komputerach w du¿ym hangarze. Jeœli mo¿esz to zrobiæ, nagrodzimy Ciê.}

{280} {} {Blacharze wypadli z interesu - ZAX wypêdzi³ ich z tego regionu. Na Ciebie te¿ ju¿ czas.}
{281} {} {Wiêc to prawda? Na pocz¹tku nie wierzy³em w donosy, ale teraz widzê, ¿e to prawda. Ten dzieñ bêdzie œwiêtem dla ca³ego pustkowia. Teraz musimy tylko wróciæ do domu i zacz¹æ ¿yæ od zera. Dziêki za pomoc.}
{282} {} {Nie ma za co.}

{283} {} {Hard nie ¿yje, Blacharze w zamêcie. Czy to nie czas, ¿ebyœ poszed³ do domu?}
{284} {} {Wiêc to prawda? Na pocz¹tku nie wierzy³em w donosy, ale teraz widzê, ¿e to prawda. Wci¹¿ trudno powiedzieæ, jak dotkliwe oka¿e siê to dla Blacharzy, ale na pewno szybko siê nie pozbieraj¹. Myœlê, ¿e teraz mo¿emy wróciæ do domu i zacz¹æ ¿ycie od nowa. Dziêki za pomoc.}
{285} {} {Nie ma za co.}

{286} {} {Blacharze przygotowuj¹ siê do ataku. Uciekaj, jeœli ¿ycie jest Ci cenne.}
{287} {} {Nie zamierzam uciekaæ z powodu w¹tpliwych plotek.}
{288} {} {No to to bêdzie twój problem.}

{289} {} {(Twoje s³owa zadzia³a³y. Niewolnicy zaraz opuszcz¹ Tu-San.)}
{290} {} {[wyjdŸ]}
{291} {} {Nie wytrzymasz w tej piwnicy, jeœli Blacharze przebij¹ siê przez barykady. A tym bardziej swoj¹ œmierci¹ niczego nie osi¹gniesz.}
{292} {} {Musimy walczyæ dalej! Blacharze nie mog¹ pozostaæ bezkarni.}
{293} {} {Jeœli chcesz ich za³atwiæ, najlepiej zrobiæ to pokojowo, podwa¿aj¹c ich umowy handlowe i reputacjê. Teraz jesteœ wyczerpany i bezsilny.}
{294} {} {To zale¿y od Ciebie.}
{295} {} {Byæ mo¿e... nasza sytuacja jest rozpaczliwa. Zadne jedzenie, ¿adne lekarstwa, nawet broñ z ostatniego konwoju nie daje nam przewagi. Porozmawiam z innymi, niech zdecyduj¹ wiêkszosci¹ g³osów.}
{296} {} {Dobry ruch...}
{297} {} {Blacharze przygotowuj¹ siê do ataku. Nie masz szans.}