{100} {} {Widzisz wartownika.}
{101} {} {Widzisz jednego ze zbieg³ych niewolników. Strze¿e wejœcia.}

{200} {} {Stop! Co za cholera? Jak uda³o ci siê przedrzeæ przez pu³apki?}
{201} {} {Mia³em mapê.}
{202} {} {Mia³em po prostu szczêœcie.}

{203} {} {Zartujesz sobie ze mnie? Okej... Czego do cholery tu szukasz?}
{1203} {} {Zartujesz sobie ze mnie? Okej... Czego do cholery tu szukasz?}
{204} {} {Nie wierzê w takie szczêœcie. Ale mimo to... Czego tu szukasz?}

{205} {} {Chcê porozmawiaæ z twoim szefem.}
{206} {} {Nie mamy szefa. Wszyscy jesteœmy tutaj równi. Czy ty te¿ jesteœ niewolnikiem? Albo masz doœæ Blacharzy? Dobra, idŸ do Jeffa, on odpowiada za nasz¹ taktykê. Zobaczmy, co ma do powiedzenia.}
{207} {} {Ok. Znajdê z nim coœ do omówienia.}
{208} {} {W³aœciwie to ju¿ wiem wszystko, czego potrzebowa³em. Teraz umrzesz.}
{1208} {} {W³aœciwie to ju¿ wiem wszystko, czego potrzebowa³am. Teraz umrzesz.}
{209} {} {Jedynym czego chcê jest wyeliminowanie twojej obecnoœci w tych ruinach.}

{210} {} {WejdŸ, ale nawet nie myœl o sprawianiu k³opotów.}
{211} {} {Ok.}
{212} {} {Do widzenia.}
{213} {} {Szpieg! Wszyscy do mnie!}
{214} {} {To posz³o na marne.}

{220} {} {Jak siê tu dosta³eœ?}
{221} {} {Zosta³em schwytany w Phoenix i sprzedany Blacharzom jako niewolnik. Nastêpnie zosta³em wys³any do Zakazanej Strefy, aby zebraæ stare rzeczy. Na szczêœcie dla mnie Jeff by³ tam i pomóg³ mi wyjœæ z pu³apki. Teraz jestem tutaj i pomagam tak bardzo, jak tylko mogê. Jestem doceniany za umiejêtnoœæ pos³ugiwania siê pu³apkami.}
{222} {} {Jasne, z³apany, co? Jakoœ w to w¹tpiê.}
{223} {} {Hej, czy widzia³eœ tych fanatyków nuklearnych? Nie uwa¿aj¹ ludzi na pustkowiach za ludzi. Jeœli chc¹ niewolników, nie ma znaczenia, kim jesteœ ani co robisz - po prostu za³oz¹ ci ko³nierz i koniec.}
{224} {} {Jak siê nauczy³eœ radziæ sobie z minami?}
{225} {} {Uch, Jeff mnie uczy³. Nie pyta³em, kto go nauczy³.}
{226} {} {Opowiedz mi o Jeffie.}
{227} {} {Powa¿ny cz³owiek, musisz siê tego trzymaæ. Gdyby nie on, wszyscy zginêlibyœmy w Zakazanej Strefie lub z g³odu. Czasami dokonuje cudów i znajduje zapasy w ruinach, w których nikt nie móg³ niczego znaleŸæ.}

#Majdan
{230} {} {Jak mogê siê st¹d wydostaæ bez spotkania z minami?}
{231} {} {Wycofaj siê. Nie powiem ci nic wiêcej.}
{232} {} {Ok.}
{233} {} {Musimy sobie ufaæ, siedzimy w tym razem.}
{234} {} {Ok, poka¿ê ci pola minowe. B¹dŸ ostro¿ny.}
{235} {} {Dziêki.}
{236} {} {Ju¿ wiesz za du¿o.}
{237} {} {Ok...}