{100} {} {Widzisz zbieg³ego niewolnika.}
{101} {} {Widzisz jednego ze zbieg³ych niewolników, którzy osiedlili siê w tych ruinach.}

{110} {} {Blacharze zap³ac¹ za wszystko.}
{111} {} {Blacharze oddzielili Ciê od rodziny? Rozumiem...}
{112} {} {Jeœli nienawidzisz Blacharzy, to jesteœ wœród swoich.}
{113} {} {Chcesz do nas do³aczyæ?}
{114} {} {Do³¹cz do nas. Potrzebujemy wiêcej sabota¿ystów kamikadze.}
{115} {} {Jakaœ broñ? A co z jedzeniem lub piciem?}
{116} {} {Na co siê gapisz?}
{117} {} {Nie mam pojêcia, czym jest Narodowy Bank Arizony.}
{118} {} {Pieni¹dze? Rozpalamy nimi ogniska. A co?}
{119} {} {Walka o wolnoœæ to wszystko, co nam pozostaje.}