{100} {} {Widzisz Master Harda.}
{101} {} {Widzisz lidera Blacharzy. Wydaje siê, ¿e ma wiêcej ¿elaza ni¿ faktycznego cia³a.}
{102} {} {PrzejdŸ do swojego wirtualnego œwiata!}

# Pierwszy dialog
{200} {} {(Widzisz kogoœ zrobionego w po³owie z ¿elaza i elektroniki; jego mechaniczny g³os brzmi, jakby pochodzi³ z innego œwiata) Cz³owiek z pustyni. Nie ma Ciê w mojej bazie danych, nie mogê Ciê zidendyfikowaæ. Powiedz, kim jesteœ.}
{201} {} {Jestem tylko cz³owiekiem z pustkowi. Szukam moich bliskich z Villi.}
{202} {} {Villa... Baza danych zawiera informacje o miejscowoœci o tej nazwie. Stamt¹d przyby³o kilku niewolników. Ale kim ty jesteœ, ¿eby tu wpadaæ i zadawaæ pytania?}
{203} {} {Có¿, jeœli siê nad tym zastanowiæ, to nikim.}
{204} {} {Bezpoœredni i stanowczy. Cenimy te cechy. Dlatego dam tobie, prymitywnemu stworzeniu z pustyni, mo¿liwoœæ wykazania siê... jako wolontariusz.}
{205} {} {Jestem jednym z Wyznawców Swiêtego Ognia.}
{206} {} {Niektórzy z naszych ministrów pochodz¹ z tego koœcio³a. Ale tutaj, gdzie œwiec¹ Dwa S³oñca, zasady s¹ inne ni¿ te, do których jesteœ przyzwyczajony. Mo¿esz zostaæ w naszym mieœcie, ale nie odwracaj uwagi moich ludzi od ich pracy.}
{207} {} {Jestem oficjalnym przedstawicielem Bractwa Stali.}
{208} {} {Szanujemy Bractwo Stali. Daliœcie nam Energiê i nauczyliœcie nas, jak korzystaæ z wielu zapomnianych technologii. Jak mo¿emy pomóc jednemu z naszych braci w metalu?}
{209} {} {W³aœciwie to chcê zobaczyæ moich krewnych. S¹ tutaj?}
{210} {} {(oblicza coœ ze swojej bazy danych) Mieszkañcy Villi... Twoja wizyta jest spóŸniona. Twoi wspó³plemieñcy s¹ ju¿ w Swietych Kopalniach w poszukiwaniu staro¿ytnych technologii.}
{211} {} {Mam kilka pytañ.}
{212} {} {Jadê do Puerto Penasco w imieniu Koœcio³a Swiêtego Ognia.}
{213} {} {Masz jak¹œ obsesjê. Musisz zostaæ zatrzymany, zanim wyœlesz ca³¹ populacjê pustkowi do Kopalni.}
{214} {} {Nie wiesz, z kim rozmawiasz, g³upcze. A teraz, zostaniesz zasymilowany...}
{1214} {} {Nie wiesz, z kim rozmawiasz, g³upia. A teraz, zostaniesz zasymilowana...}
{215} {} {O nie!}
{216} {} {O czym ty mówisz? Wychodzê i nawet nie próbuj mnie powstrzymaæ, wariujesz od tych kabli.}
{217} {} {Bêdê zadawa³ teraz pytania. A ty usi¹dziesz i odpowiesz.}

# Powtarzajacy siê dialog
{220} {} {Mów.}
{221} {} {Do zobaczenia.}

#Pytania
{230} {} {Mów.}
{231} {} {To wszystko. Wychodzê.}
{232} {} {Kolejne pytanie.}

{233} {} {Co tu robi by³y zwiadowca Bractwa Stali?}
{234} {} {Stalowi bogowie upadli. Ich Olimp zosta³ zniszczony przez wybuch nuklearny. Ale niektórym uda³o siê prze¿yæ. Pomimo utraty dawnej œwietnoœci, nadal posiadaj¹ unikalne umiejêtnoœci i wiedzê niedostêpne dla zwyk³ych œmiertelników. Laskawie udzielimy im schronienia. Ale na naszych warunkach.}
{235} {} {Innymi s³owy, chcesz wydobyæ z nich wszystkie przydatne informacje i wykorzystaæ je wed³ug w³asnego uznania?}
{236} {} {Jesteœmy narodem by³ych wojskowych, naszym powo³aniem jest o¿ywienie wielkoœci minionego œwiata poprzez technologiê. Nie zatrzymamy siê z powodu awarii cudzej placówki.}
{237} {} {Rozumiem. Czy mogê zadaæ inne pytania?}
{238} {} {Có¿, wygl¹da na to, ¿e jeden stalowy Bóg bêdzie mia³ trudne ¿ycie dla zwyk³ego œmiertelnika.}

{240} {} {Jak mogê uratowaæ moich wspó³plemieñców?}
{241} {} {Jedynym sposobem jest udanie siê do Zakazanej Strefy i znalezienie niewolników. Aby siê wycofaæ, bêdziesz musia³ wy³¹czyæ wewnêtrzne systemy ochrony. To mêka nawet dla Blacharzy. Szanse na prze¿ycie w Zakazanej Strefie s¹ nik³e. Porozmawiaj z instruktorem, gdy bêdziesz gotowy do wyruszenia.}
{242} {} {Dlaczego zakazana strefa jest dla ciebie taka wa¿na?}
{243} {} {Ludzie z minionej epoki gromadzili tam sprzêt wojskowy. Przez lata rozleg³e terytorium zape³ni³o siê najcenniejszymi z³o¿ami technologii, a centrum tego repozytorium - wiedz¹ i rysunkami technicznymi. Dziêki wolnemu dostêpowi do tego repozytorium moglibyœmy przywróciæ staro¿ytne technologie do ¿ycia. A wraz z nimi wielkoœæ Postêpu na Pustkowiach!}
{244} {} {Czy w ogóle wiesz, co z tym wszystkim zrobiæ?}
{245} {} {Bractwo Stali pomo¿e w m¹drym wykorzystaniu tych odkryæ dla dobra ca³ej ludzkoœci. My, jako s³udzy Postêpu, jesteœmy zobowi¹zani pomagaæ Bractwu.}
{246} {} {Co to za bractwo?}
{247} {} {Nie wiesz? Mo¿e nie musisz wiedzieæ, ale powiem ci. Bractwo Stali to jedna z jednostek wojskowych minionej epoki. Ma³y fragment przesz³oœci, który przyby³ na nasze ziemie, aby o¿ywiæ Stary Swiat. Godny cel, dla którego my, Blacharze, jesteœmy gotowi poœwiêciæ nasze ¿ycia. D¹¿ymy równie¿ do tego, aby Dwa S³oñca ponownie zaœwieci³y nad œwiatem.}
{248} {} {Dwa s³oñca? Wiem tylko o jednym.}
{249} {} {Zgadza siê, ¿a³osny cz³owieku z krwi i koœci. Znasz tylko s³oñcê, które œwieci na niebie i ogrzewa sadzonki kukurydzy. Ale nie znasz rozkoszy energii j¹drowej, która œwieci znacznie jaœniej.}
{250} {} {Swoj¹ drog¹, gdzie jest to Bractwo Stali?}
{251} {} {Nie zas³ugujesz na odpowiedŸ, obcy.}
{1251} {} {Nie zas³ugujesz na odpowiedŸ, obca.}
{252} {} {Zas³ugujesz na odpowiedŸ. IdŸ na zachód do Casa Nueva. A nad brzegiem Zatoki Kalifornijskiej znajdziesz Steel Port - to bastion Bractwa Stali.}
{253} {} {Kim jesteœ?}
{254} {} {Osoby postronne nazywaj¹ nas Blacharzami, poniewa¿ nasz¹ pasj¹ jest staro¿ytna technologia. Poœwiêciliœmy siê tej s³u¿bie, poœwiêcaj¹c nawet nasze œmiertelne ludzkie cia³a. Technologia bowiem uratuje œwiat i nie pozwoli mu ca³kowicie znikn¹æ. Ludzie bêd¹ ¿yæ, gdy dwa s³oñca bêd¹ œwieciæ, w przeciwnym razie zdegraduj¹ siê do poziomu dzikusów. Tym razem proces ten bêdzie nieodwracalny.}
{255} {} {Czy jesteœ w jakikolwiek sposób powi¹zany z Wyznawcami Ognia?}
{256} {} {Koœció³ zosta³ stworzony, aby nosiæ sztandar Postêpu, ale w bardziej zrozumia³ych dla zwyk³ych ludzi s³owach. Szanujemy i wspó³pracujemy z tymi zabawnymi ludŸmi w szatach, poniewa¿ ich wiara przybli¿a ma³ych ludzi do naszych wyobra¿eñ o œwiecie. Ale s¹ o jeden stopieñ ni¿ej od nas.}
{257} {} {Wiêc to tutaj przychodzi uran z Flagpool?}
{258} {} {Energia wymaga paliwa, a my potrzebujemy du¿o energii. Gdyby nie chciwoœæ prymitywnych stworzeñ z Phoenix i innych osad, dostawalibyœmy ca³y uran Flagpool.}
{259} {} {Co zrobisz teraz, gdy kopalnie uranu zosta³y spustoszone?}
{260} {} {Jak poprzednio, bêdziemy szukaæ pozosta³oœci przedwojennych zasobów. Zaufaliœmy Zakazanej Strefie, która wci¹¿ ma wiele zasobów i tajemnic.}
{261} {} {Czy posy³anie ludzi na œmieræ jest etyczne?}
{262} {} {Zycie na pustkowiach to przetrwanie. Pozwól wiêc tym dzikusom przetrwaæ w Zakazanej Strefie i tym samym przynieœæ korzyœci Postêpowi i ca³emu œwiatu. Kazde ¿ycie w naszych czasach nie jest cenniejsze ni¿ trybik w ogromnej maszynie.}
{263} {} {A jeœli niewolnikom uda siê wy³¹czyæ ochronê?}
{264} {} {Ka¿dy, kto przyniesie cenny artefakt z Zakazanej Strefy, nie mówi¹c ju¿ o wy³¹czeniu systemu obronnego, otrzyma wolnoœæ i zaszczyty. My, Blacharze, dotrzymujemy s³owa.}
{265} {} {Czy wiesz, ¿e Bractwo Stali ju¿ nie istnieje?}
{266} {} {To tylko drobna niedogodnoœæ dla Postêpu. Ich miejsce zajm¹ inni. Steel Port nie by³ g³ówn¹ baz¹ tej organizacji. Ich sztab generalny znajduje siê w Kalifornii i nadal dzia³a. Pewnego dnia Arizona ponownie poczuje ciê¿ar metalu Bractwa Stali.}
{267} {} {Teraz, gdy Swi¹tynia Ognia zosta³a zniszczona, jak myœlisz co siê stanie z ich wiar¹?}
{268} {} {Nie ma dla nas znaczenia wiara tego koœcio³a. Wa¿na jest jedna rzecz - z jej pomoc¹ Arizona dowiedzia³a siê o Postêpie. Pozostaje nam teraz wykorzystaæ tê okazjê i zaj¹æ wolne miejsce w Phoenix.}

{270} {} {Straci³eœ swoje cz³owieczeñstwo i sta³eœ siê bezdusznym robotem. Musisz zostaæ od³¹czony, cholerny dziwaku.}
{271} {} {Wiem tylko, ¿e ta energia zniszczy³a Stary Swiat. Czy zamierzasz zrobiæ to samo?}
{272} {} {Nie bêdziemy powtarzaæ b³êdów naszych przodków. Uczyliœmy na ich b³êdach i staliœmy siê m¹drzejsi. Technologia musi przywróciæ cywilizacjê.}
{273} {} {Nikt taki jak ty nie powinien mieæ dostêpu do klucza. Zniszcze ciê, zanim zniszczysz ca³y œwiat.}
{274} {} {Potrzebujê trochê czasu, ¿eby pomyœleæ o tym, co powiedzia³eœ. Do zobaczenia... mo¿e.}
{275} {} {Jak ciekawie. Chcia³bym dowiedzieæ siê wiêcej o Tobie i Twoich pomys³ach.}
{276} {} {Wiesz, masz racjê. Z powodu kilku b³êdów w przesz³oœci nie powinniœmy ograniczaæ siê w rozwoju.}
{277} {} {Dobrze, ¿e twój ma³y biologiczny mózg jest w stanie to zrozumieæ.}
{278} {} {Tak, ale mam jeszcze kilka pytañ.}

{300} {} {Zakazana Strefa jest teraz pod twoj¹ kontrol¹, Master Hard.}
{301} {} {ZAX nie dzia³a! Jego œwiête artefakty powróca¹ do nas, ludzi, dla których zosta³y stworzone. To wspania³y dzieñ dla ca³ego naszego narodu. Pocz¹tek nowej ery.}
{302} {} {Za³ó¿my, ¿e masz racjê. Ale co z moimi ludŸmi?}
{303} {} {Domagam siê uwolnienia mojego ludu z niewoli.}
{304} {} {Ty i Twoi ludzie zas³ugujecie na wolnoœæ. Mo¿esz iœæ. Ale wiedz, ¿e jesteœmy tylko czêœci¹ ca³ego mechanizmu. Tak jak ty. Któregoœ dnia Bractwo Stali zawita do waszych domów. Co zamierzasz zrobiæ? Poka¿ racjonalnoœæ i poddaj siê woli Postêpu. To jedyny sposób na przetrwanie w Nowym Swiecie.}
{305} {} {Przemyœlê twoj¹ propozycjê. Na razie muszê iœæ.}
{306} {} {Co ma z tym wspólnego Bractwo Stali?}
{307} {} {Jesteœmy tylko s³ugami tych Bogów. Rz¹dz¹ naszymi ziemiami w imiê Postêpu. Wykorzystuj¹ nasze zasoby i technologie, aby rozwijaæ ca³e Pustkowie. Historia niewoli Villi by³a tylko czêœci¹ tego procesu. Masz to szczêœcie, ¿e znalaz³eœ siê w centrum wielkiej zmiany.}
{308} {} {Twój punkt widzenia... zas³uguje na uwagê.}
{309} {} {Wciskaj te bzdury reszcie Blacharzy, ale nie mi.}

#Cody
{350} {} {Mówi¹, ¿e porwa³eœ Cody'ego z Casa Grande. To prawda?}
{351} {} {To oczywiste, ¿e przedstawili ci wygodn¹ dla siebie wersjê.}
{352} {} {Wiêc powiedz mi swoj¹ "oficjaln¹" wersjê.}
{353} {} {Jaki arogancki. Ale otrzymasz odpowiedŸ jako akt dobrej woli. Nie porwaliœmy Cody'ego, ale wykupiliœmy go z r¹k zbankrutowanych rodziców, którzy w tamtym czasie nie byli nawet w stanie go wy¿ywiæ.}
{354} {} {Czy naprawdê by³o tak Ÿle w Casa Grande?}
{355} {} {W tamtym czasie ta nêdzna osada pilnie potrzebowa³a naprawy pompy wodnej. Tylko my mogliœmy to naprawiæ. W ramach zap³aty ludnoœæ musia³a nam zap³aciæ tym co mia³a. Wœród towarów by³ Cody. Okaza³ siê byæ cenny dla naszego zespo³u.}
{356} {} {Dlaczego przyj¹³eœ dziecko jako zap³atê?}
{357} {} {Nasze spo³eczeñstwo zna technologiê, ale s¹ pewne problemy z porodami. Zabranie trzyletniego dziecka i jego reedukacja wed³ug w³asnych podstaw to jeden ze sposobów na utrzymanie naszej populacji. Takie dziecko otrzymuje tu godne ¿ycie i przyzwoit¹ przysz³oœæ.}
{358} {} {Nie s¹dzisz, ¿e jego prawdziwa historia pozostanie tajemnic¹ na zawsze, prawda?}
{359} {} {G³upi sentymentalizm. Od teraz Cody jest cz³onkiem naszego Kolektywu. Jest obcy œwiatu zewnêtrznemu.}
{360} {} {Tak, oczywiœcie. Wygl¹da na to, ¿e powinniœmy teraz zakoñczyæ tê rozmowê.}
{361} {} {Mylisz siê. Ma prawo decydowaæ o swoim losie. Udowodniê to.}

{368} {} {To potê¿ny argument. Zgadzamy siê na podpisanie umowy. Powiedz swojemu przywódcy, ¿e wyœlemy ambasadora do negocjacji.}
{369} {} {Puœæ mnie, Mistrzu.}
{370} {} {Jestem tutaj w imieniu Niebieskich Tarcz. Mamy ofertê.}
{371} {} {Co mog¹ nam zaoferowaæ dzikusy?}
{372} {} {Paliwo. Du¿o paliwa. W zamian ¿¹daj¹ uznania swojej niezale¿noœci i oficjalnego statusu handlowego.}
{373} {} {Paliwo bêdzie dobr¹ alternatyw¹ dla uranu w okresie jego niedoboru. Jednak Niebieskie Tarcze maj¹ reputacjê przestêpców. Nie chcemy ryzykowaæ kontaktu z tak niewiarygodnym dostawc¹.}
{374} {} {Ben bêdzie z³y, ale nic nie mo¿na na to poradziæ. Przeka¿ê mu twoj¹ odmowê.}
{375} {} {Czy mogê ciê jakoœ przekonaæ?}
{376} {} {Poka¿ mi, ¿e mo¿na ci zaufaæ. Wtedy porozmawiamy.}
{377} {} {Pomyœlê o tym.}
{378} {} {Moja reputacja wœród twoich ludzi jest naprawdê wysoka.}
{379} {} {Moja pomoc w Zakazanej Strefie jest dowodem naszej wiarygodnoœci.}

#Quests
{390} {} {Prawdopodobnie potrzebujecie kogoœ do zadañ specjalnych.}
{391} {} {Jesteœmy... zainteresowani.}
{392} {} {Wiêc co trzeba zrobiæ?}
{393} {} {Jedna z naszych karawan zosta³a zaatakowana. Nie mogliœmy zidendyfikowaæ napastników. Twoim zadaniem jest dowiedzieæ siê, kto zaatakowa³ karawanê. Porozmawiaj ze stra¿nikiem, wska¿e ci drogê do miejsca ataku.}
{394} {} {Wiêc muszê przejœæ kilka mil? Nie wydaje mi siê to zbyt trudne.}
{395} {} {Spodziewa³em siê czegoœ bardziej imponuj¹cego, ale niech bêdzie.}
{1395} {} {Spodziewa³am siê czegoœ bardziej imponuj¹cego, ale niech bêdzie.}
{396} {} {Po podjêciu decyzji poinformuj mnie o wynikach dochodzenia. Mo¿esz iœæ.}
{397} {} {Jestem w drodze.}

{400} {} {Dowiedzia³em siê, kto stoi za atakiem na karawanê - grupa zbieg³ych niewolników mieszkaj¹cych na Starym Mieœcie.}
{1400} {} {Dowiedzia³am siê, kto stoi za atakiem na karawanê - grupa zbieg³ych niewolników mieszkaj¹cych na Starym Mieœcie.}
{401} {} {Dobra robota. Potwierdzasz nasz¹ pierwotn¹ wersjê. Ci niewolnicy wielokrotnie dawali o sobie znaæ, ale dopiero teraz zaczêli wywieraæ namacalny nacisk na Tu-San.}
{402} {} {Co mam teraz zrobiæ?}
{403} {} {Ci przestêpcy atakuj¹ karawany i podró¿nych. Dostarcz im sprawiedliwoœæ Tu-San. Jako dowód - zwróæ skradzione nam produkty technologiczne.}
{404} {} {Dlaczego Twoi ludzie nie mog¹ tego zrobiæ?}
{405} {} {Zbiegli niewolnicy dopiero w Zakazanej Strefie nauczyli siê trzymaæ broñ, ale ju¿ pokazuj¹ taktyczne umiejêtnoœci walki rebeliantów. Trudno ich dostrzec wœród ruin, a ich pu³apki s¹ przebieg³e i niebezpieczne. Ponadto jesteœmy s³ugami technologii, a nie wojny.}
{406} {} {Jak mogê stawiæ czo³a ca³ej rzeszy wrogów?}
{407} {} {U¿yj swojego mózgu tam, gdzie technologia zawodzi.}
{408} {} {Co otrzymam za to zadanie?}
{409} {} {Mamy do zaoferowania wiêcej ni¿ tylko cenne przedmioty. Oferujemy nowy œwiat. Mo¿esz do niego wejœæ, staj¹c siê czêœci¹ Postêpu, albo zostaæ w tyle i przepaœæ.}
{410} {} {Gogle noktowizyjne pomog³yby mi w ruinach.}
{411} {} {(Otrzymujesz gogle) U¿ywaj tej technologii m¹drze.}
{412} {} {Ta technologia nie jest dla osób z zewn¹trz.}
{413} {} {Nie dostaniesz nic wiêcej. U¿yj tego, co masz.}
{414} {} {Rozwi¹¿ê ten problem, bez obaw.}
{415} {} {Nie interesuje mnie to. Mam wa¿niejsze rzeczy do zrobienia.}
{416} {} {Musimy porozmawiaæ o zbieg³ych niewolnikach.}

{420} {} {Zbiegli niewolnicy ju¿ ci nie gro¿¹.}
{421} {} {Bardzo dobrze. Wygl¹da na to, ¿e masz w sobie stal, któr¹ cenimy. Teraz przedstaw mi pe³ny raport.}
{422} {} {To by³o tak...}
{423} {} {...Jesteœmy zadowoleni z wyników. Nagrodê wrêczy kwatermistrz... Czekaj. Jest jeszcze jedno zadanie dla Ciebie.}
{424} {} {Powiedz mi o nim.}
{425} {} {Wykonuj¹c tê misjê, poprawiasz swoj¹ reputacjê u Blacharzy.}
{426} {} {Jeden z naszych delegatów uda³ siê do Casa Grande, ale nigdy nie wróci³. Nie mamy ¿adnych wiadomoœci od niego na ¿adnym z naszych kana³ów komunikacji. Musisz znaleŸæ naszego brata i dowiedzieæ siê, co siê sta³o.}
{427} {} {Moje nowe buty mog¹ nie przetrwaæ tej podró¿y. Mam nadziejê, ¿e bêdzie warto.}
{428} {} {Jestem w drodze.}
{429} {} {...Wynik jest zadowalaj¹cy. Nagrodê wrêczy kwatermistrz... Czekaj. Jest jeszcze jedno zadanie dla Ciebie.}

{430} {} {Uda³o mi siê znaleŸæ Blacharza w Casa Grande. Niestety nie ¿yje. Oto dowód - jego neurochip.}
{431} {} {Jaka jest przyczyna œmierci?}
{432} {} {Zosta³ zabity przez Rangersa.}
{433} {} {Rangersi... Nie spodziewaliœmy siê tylu problemów ze strony tej organizacji.}
{434} {} {Co masz na myœli przez „tylu”?}
{435} {} {Po twojej misji zbadaliœmy kryjówkê zbieg³ych niewolników na Starym Mieœcie. I tam znaleŸliœmy dowody na to, ¿e niewolnicy byli zaopatrywani i szkoleni przez Rangersów. Próbowali wiêc podkopaæ nasz¹ reputacjê i ekonomiê. W innych osadach rozpowszechniaj¹ o nas fa³szywe pog³oski. Ci Rangersi staj¹ siê prawdziwym zagro¿eniem.}
{436} {} {Co teraz?}
{437} {} {Przygotujemy siê do walki. Po wyeliminowaniu Bractwa Stali mo¿emy polegaæ tylko na sobie. Mo¿esz iœæ do domu. Od teraz Villa jest przez nas uznawana za neutraln¹ osadê.}
{438} {} {Cholera, jestem naprawdê zmêczony tymi podró¿ami. Bywaj, amigo.}
{439} {} {Udaj siê do Steel Port i zg³oœ do Bractwa Stali informacje o naszym konflikcie z Rangersami. Jeœli potrzebujesz pomocy, mo¿esz liczyæ na moj¹ rekomendacjê. Jeœli ten œwiat ma przysz³oœæ, znajdziesz j¹ tylko razem z Bractwem Stali. Czas na Wielkie Czyny.}
{440} {} {Bractwo Stali? Brzmi nieŸle. Jestem w drodze.}
{441} {} {Dziêkujê za zaufanie, panie Hard. Nie zawiodê wspania³ej idei Postêpu.}
{442} {} {Rozumiem, ale czy jest sposób na ³atwiejsze znalezienie Blacharza w obcym mieœcie?}
{443} {} {Radio mo¿e u³atwiæ poszukiwanie, wystarczy dopasowaæ czêstotliwoœæ do podskórnego chipa, ktory mia³ delegat.}