{100} {} {Widzisz Carlosa.}
{101} {} {Widzisz jednego z ch³opów Villi. Jednak sta³ siê w jakiœ sposób... inny.}
{102} {} {Mówi¹, ¿e prawdziwa nauka wraca do Casa Nueva. Jak przed Wielk¹ Wojn¹. Powinienem tam byæ.}
{103} {} {Wrócê do domu... aby uczyniæ go bardziej cywilizowanym.}
{104} {} {Nie mam innego wyboru, jak tylko podró¿owaæ. Mam nadziejê, ¿e zobaczê wiele nowych rzeczy.}
{105} {} {Jak... jak mo¿esz...}
{106} {} {Ty... to twoja wina...}

# Pierwszy dialog
{200} {} {? Ty... dlaczego tu jesteœ?}
{201} {} {Oczywiœcie, po to, ¿eby ocaliæ twój ty³ek, Carlos. ChodŸmy st¹d...}
{202} {} {Ocaliæ... ocaliæ od czego? Od zamieszkania wsród myszy i umieraj¹cymi uprawami? Od chorób, na które ch³opi nigdy nie znajd¹ lekarstwa? Od wrogów, przeciwko którym nie mieliœmy nawet prymitywnych karabinów? Nie widzê ocalenia. Widzê tylko w¹skie i ograniczone horyzonty garstki ch³opów.}
{203} {} {O czym ty mówisz?}
{204} {} {Jesteœmy dzikusami, amigo, zrozum to. Dzikusami, którzy ujrzeli œwiat³o elektryczne dopiero w niewoli. To by³o tak, jakbyœmy mieszkali w puszce, dopóki ktoœ jej nie otworzy³ i nie pokaza³ nam ogromnego œwiata wokó³ nas. Villa okaza³a siê tylko niewielk¹ jego czêœci¹, a nie centrum, jak wczeœniej s¹dzono.}
{205} {} {Zaczekaj chwilê...}
{206} {} {Tylko tutaj mog³em zrealizowaæ siebie i swoje talenty. Poniewa¿ moja pasja do technologii zosta³a zakazana w domu. Ukrywa³em to, ¿eby nie sprawiaæ problemów sobie i innym. Teraz mogê pod¹¿aæ za tym czego chce mój umys³, a nie za stadem. OdejdŸ, amigo. Zostaw mnie tutaj.}
{207} {} {Na razie ciê zostawiê. Ale nie myœl, ¿e tak ³atwo mo¿esz siê mnie pozbyæ.}
{208} {} {Nie s¹dzê, ¿ebym móg³ ciê zniechêciæ. Zegnaj, amigo.}

{210} {} {Czas Villi siê skoñczy³, proszê zrozum to.}
{211} {} {Ok, skoñcz ju¿.}

{230} {} {Czy mo¿esz mi wyjaœniæ, co siê tutaj dzieje?}
{231} {} {Blacharze próbuj¹ odkryæ pochówek staro¿ytnej technologii w Zakazanej Strefie. Potrzebuj¹ lokalnych technologii i zasobów, aby rozwijaæ i promowaæ ideê Postêpu. Ale obszar jest dobrze broniony. Oddzia³y niewolników i najemników s¹ tam wysy³ane co jakiœ czas, zwykle jednak nikt z nich nie wraca.}
{232} {} {Opowiedz mi o Blacharzach.}
{233} {} {To jest klan na wpó³ religijny ze star¹ histori¹. Chc¹ o¿ywiæ staro¿ytne technologie, które czcz¹, aby mog³y s³u¿yæ ludziom.}
{234} {} {Opowiedz mi o zakazanej strefie.}
{235} {} {To cmentarzysko staro¿ytnego sprzêtu, g³ównie wojskowego. Dlatego teren jest dobrze ufortyfikowany i strze¿ony przez roboty. Blacharze znaleŸli sposób na krótkie wy³¹czenie bariery mocy przy g³ównej bramie, ale to nie wystarczy. Jeœli masz zamiar wejœæ do œrodka, bêdziesz potrzebowaæ specjalnej broni przeciw robotom i sporo leków przeciwpromiennych.}
{236} {} {Kto z Villi oprócz ciebie jest tutaj?}
{237} {} {Twój ojciec i Gerardo. Zostali ju¿ jednak wys³ani do Zakazanej Strefy. Jeœli chcesz ich ocaliæ, to musisz za nimi pod¹¿yæ.}
{238} {} {Idê do zakazanej strefy. Carlos, naprawdê potrzebujê pomocy.}
{239} {} {Nie... nie mogê ci pomóc... Blacharze bacznie mi siê przygl¹daj¹ i kontroluj¹ swoje magazyny.}
{240} {} {Dziêki za odpowiedzi. Czas zacz¹æ.}
{241} {} {No dalej, Blacharze powinni byæ zainteresowani moim sukcesem!}
{242} {} {(rozgl¹da siê) Mogê ci coœ daæ. To s¹ granaty pulsacyjne. Podobno taka broñ mo¿e zabiæ robota za jednym zamachem. U¿ywaj ich w ostatecznoœci.}
{243} {} {Dziêki, Carlos. Bardzo mi pomog³eœ.}
{244} {} {Powróæmy do innych pytañ.}
{245} {} {To zbyt niebezpieczne. Przepraszam.}

#Energy cell
{250} {} {Potrzebujê ogniwa zasilaj¹cego do generatora. Czy mo¿esz pomóc mi to zdobyæ?}
{251} {} {Nie proœ mnie o nic! Blacharzom nie spodoba siê, jeœli przeka¿ê technologiê bez ich zgody.}
{252} {} {To jest bardzo wa¿ne. Pomó¿ mi!}
{253} {} {Nie, nie! Nie zamierzam ryzykowaæ swojego miejsca dla korzyœci garstki ludzi.}
{254} {} {Mówisz bolesne s³owa. Do zobaczenia.}
{255} {} {Pomyœl o tym, wiem co zrobiæ ¿eby nikt nie podejrzewa³...}
{256} {} {Proszê bardzo.}
{257} {} {(rozgl¹da siê) Jeœli zapytaj¹, nie mam z tym nic wspólnego.}
{258} {} {No dalej, amigo.}
{259} {} {Zobaczmy to...}

#Opieka
{300} {} {Wiêc zamierzasz wróciæ do Villi?}
{301} {} {Nawet nie pytaj. Dopóki mnie st¹d nie wyrzuc¹, nie opuszczê tego miejsca.}
{302} {} {Nie zrobiê tego. Z przyjemnoœci¹ zostanê.}
{303} {} {Jesteœ po prostu g³upcem. I pozostaniesz g³upcem.}
{304} {} {Robi siê tu niebezpiecznie. Blacharze zostali pokonani, terytorium znajduje siê pod kontrol¹ wrogiej maszyny. Jeœli tu zostaniesz, umrzesz.}
{305} {} {Od œmierci Master Harda miejscowi stali siê jeszcze bardziej nietolerancyjni wobec obcych. Nie widzisz tego?}
{306} {} {Czy s³ysza³eœ ju¿ wiadomoœci o swojej „zdradzie”?}
{307} {} {Wiêc to twoja zas³uga? Ugh... Wygl¹da na to, ¿e robi siê powa¿nie.}
{308} {} {Nie masz gdzie siê schowaæ. Mój ojciec jest zobowi¹zany zwróciæ ciê ¿ywego lub martwego.}
{309} {} {Przepraszam, ale to jedyny sposób, aby z tob¹ porozmawiaæ.}
{310} {} {To nie jest twój œwiat. Mój ojciec mówi to samo.}
{311} {} {To nie jest twój œwiat, amigo. Tutaj jesteœ tylko pracownikiem, a nie cz³onkiem spo³eczeñstwa.}
{312} {} {Na razie tak. Ale to siê zmieni. Pewnego dnia bêdê móg³ wejœæ w szeregi Blacharzy na równych prawach.}
{313} {} {Zobaczymy...}
{314} {} {Prawda. Blacharze s¹ nieufni wobec reszty Pustkowi, ich zaufanie mo¿na zdobyæ jedynie poprzez fanatyzm technologii. Wejœcie w ich szeregi na równi z innymi bêdzie bardzo trudne.}
{315} {} {Wróæ do Villi i podziel siê z nami swoj¹ wiedz¹ - to jest twoja droga.}
{316} {} {Wreszcie s³yszê g³os rozs¹dku w ca³ym tym delirium.}
{317} {} {}
{318} {} {Cholera... ju¿ podj¹³em decyzjê i nie masz pojêcia, jakie to by³o trudne. Ale wygl¹da na to, ¿e nie mam wyboru.}
{319} {} {Wiêc co zdecydowa³eœ?}

{320} {} {Po tym wszystkim nie mogê wróciæ do Villi. Nie zostanê tam przyjêty, a moja wiedza i umiejêtnoœci pozostan¹ bezu¿yteczne. Wiesz, jak uparci s¹ nasi krewni.}
{321} {} {A czy s¹ miejsca, w których twoje talenty zostan¹ docenione?}
{322} {} {Hmm. Phoenix? Nie, to kiepskie miejsce, w którym kapsle decyduj¹ za du¿o. To pozostaje Casa Nueva. Karawany nieraz opowiada³y o tej ma³ej osadzie. Mówi¹, ¿e istnieje tam prawdziwe laboratorium naukowe, w którym gromadz¹ siê najlepsze mózgi Arizony.}
{323} {} {Wiêc co ciê powstrzymuje przed pójœciem tam?}
{324} {} {To jest raczej zamkniêta spo³ecznoœc, mog¹ mnie nie zaakceptowaæ. Gdy ja tu próbujê rozpocz¹æ nowe ¿ycie, czy mo¿esz pójœæ do tamtejszych naukowców i porozmawiaæ o moim wakacie?}
{325} {} {Oczywiœcie, amigo. Zrobiê to z powodu naszej starej przyjaŸni.}
{326} {} {Dziêki, }
{327} {} {. Czekam na wieœci.}
{328} {} {Do zobaczenia.}
{329} {} {Nie, muszê wracaæ do domu. Sam rozwi¹¿ swój problem.}
{330} {} {Szkoda. Ale jeœli akurat bêdziesz w pobli¿u, powiedz o mnie jakiemuœ z naukowców, dobrze?}
{331} {} {Nie mogê nic obiecaæ.}
{332} {} {Oczywiœcie, ¿e tak.}

{340} {} {Ju¿ o tym rozmawialiœmy. Nie mogê wróciæ do domu.}
{341} {} {Jak sobie ¿yczysz. Bywaj.}
{342} {} {G³upcy siê nie zmieniaj¹. Do widzenia.}
{343} {} {Mam dobre wieœci. Wyznawcy Apokalipsy zgodzili siê przyj¹æ Ciê z ca³¹ Twoj¹ wiedz¹ i umiejêtnoœciami.}
{344} {} {To œwietna wiadomoœæ. Nie martw siê o mnie, znajdê drogê. Dziêkujê Ci za wszystko.}
{345} {} {Najwa¿niejsze jest to, ¿e nie pracujesz dla tych cholernych Blacharzy. Dobra, czas siê zbieraæ.}
{346} {} {Mo¿e kiedyœ te¿ opuszczê wioskê na sta³e, tak jak ty. Do widzenia.}
{347} {} {Przepraszam, Wyznawcy Apokalipsy prze¿ywaj¹ obecnie kryzys. Nie mo¿esz do nich do³aczyæ.}
{348} {} {Serio jest a¿ tak Ÿle? S³ysza³em ju¿ plotki od ludzi z karawany. Wygl¹da na to, ¿e nie mam ju¿ innego wyboru. Bêdê musia³ wyruszyæ w podró¿. Tylko nie wiem gdzie dok³adnie. Mo¿e na wschód do Kalifornii. Albo na po³udnie do Nowego Meksyku. Ale na pewno nie bêdê sta³ w miejscu.}
{349} {} {Niez³y pomys³.}
{350} {} {Do widzenia }
{351} {} {. Dziêki za wszystko.}