{100} {} {Widzisz Cody'ego.}
{101} {} {Widzisz ³yse dziecko w luŸnych ubraniach. Jego rêce nie pamietaj¹ odpoczynku od pracy.}
{102} {} {Zrobiê wszystko, aby uczyniæ œwiat lepszym miejscem.}

# Pierwszy dialog
{200} {} {(Widzisz ³yse dziecko w luŸnych ubraniach. Ignoruje Ciê.)}
{201} {} {Hej, gdzie s¹ twoi rodzice, dzieciaku?}
{202} {} {(rozgl¹da siê z obaw¹ i wraca do pracy, narzekaj¹c pod nosem) Nie... nie mam rodziców.}
{203} {} {Jak to? Chcesz powiedzieæ, ¿e zosta³eœ stworzony przez tokarkê?}
{204} {} {Przepraszam, nie chcia³em ciê uraziæ. Ale jak tu trafi³eœ?}
{205} {} {[cisza]}
{206} {} {Moi rodzice zginêli podczas wojny w Casa Grande, a ja zosta³em sam na ulicy. Ale Blacharze uratowali mnie od g³odu. Od tamtej pory ¿yjê tutaj.}
{207} {} {Hmm. To bardzo szlachetne z ich strony.}
{208} {} {Osoby z zewn¹trz nie powinny wtr¹caæ siê w nasze interesy.}
{209} {} {Bior¹c pod uwagê reputacjê Blacharzy, ta historia brzmi raczej w¹tpliwie. Nie widzisz tego?}
{210} {} {(odwraca wzrok) Sk¹d wiesz, co siê tam wydarzy³o? Jesteœ nieznajomym. Niczego nie rozumiesz. Lepiej odejdŸ.}
{211} {} {Dobra dzieciaku, cokolwiek powiesz.}
{212} {} {Gdybyœmy byli na pustkowiu, nie powiedzia³byœ mi tego. Twoje szczêœcie, ¿e jesteœmy tutaj.}

{220} {} {Jak siê nazywasz, dzieciaku?}
{221} {} {Na razie nazywam siê Cody, jak poprzednio. Ale kiedy zostanê wyœwiêcony na Blacharza, otrzymam swój w³asny identyfikator, a stare imiê bêdzie ju¿ przesz³oœci¹.}
{222} {} {Rozumiem.}
{223} {} {Czy jesteœ dobrze traktowany przez Blacharzy?}
{224} {} {Ca³kiem. Karmi¹ mnie, odziewaj¹ i daj¹ mi prace tylko wtedy, gdy mogê im siê przydaæ. Tutaj nikt nikogo nie obra¿a. Ale jeœli z³amiesz zasady lub spróbujesz kogoœ skrzywdziæ, kara bêdzie bardzo nieprzyjemna.}
{225} {} {Rozumiem.}
{226} {} {Czy masz tutaj przyjació³?}
{227} {} {Oczywiœcie. Nikt nie zabrania komunikowania siê ze sob¹, a nawet bawienia siê. To prawda, niektóre gry s¹ zabronione, poniewa¿ Pan Hard twierdzi, ¿e przeszkadzaj¹ one w prawid³owym rozwoju mózgu i odwracaj¹ uwagê od wa¿nych rzeczy.}
{228} {} {Rozumiem.}

# Powtarzajacy siê dialog
{250} {} {OdejdŸ. Nie wolno mi rozmawiaæ z nieznajomymi.}
{251} {} {Udawaj, ¿e mnie tu nie ma.}
{252} {} {Przy okazji, jeœli chcesz, mogê wpaœæ do Casa Grande i poprosiæ o parê...}
{253} {} {Nie chcê! To jest teraz mój dom, a Blacharze traktuj¹ mnie bardzo dobrze. Bêdê mia³ przez ciebie k³opoty. Zostaw mnie! (odwraca siê ze strachu i odchodzi)}
{254} {} {Och, przepraszam...}
{255} {} {No dalej, dzieciaku, wyrzuæ z siebie ca³e gówno, które dosta³eœ z lokalnego wychowania.}

{260} {} {Myœlê, ¿e powinieneœ to wiedzieæ. Blacharze ciê nie uratowali, ale przyjêli ciê jako zap³atê za naprawê stacji wodnej.}
{261} {} {Bzdury! Jesteœ obcy, sk¹d mo¿esz to wiedzieæ?}
{1261} {} {Bzdury! Jesteœ obca, sk¹d mo¿esz to wiedzieæ?}
{262} {} {Znalaz³em twoich rodziców w Casa Grande.}
{1262} {} {Znalaz³am twoich rodziców w Casa Grande.}
{263} {} {Czy oni... czy oni ¿yj¹? Ale... Dlaczego pozostali ok³amywali mnie przez ca³y ten czas?}
{264} {} {Myœlê, ¿e Blacharze próbowali zablokowaæ wspomnienia, które mog³yby przeszkodziæ ci w asymilacji do Kolektywu.}
{265} {} {Wiesz, czasami doroœli k³ami¹. Na przyk³ad, aby wykorzystaæ kogoœ do osobistych korzyœci.}
{266} {} {(skruszony) Wiêc rodzice mnie sprzedali, a moja nowa rodzina przez lata trzyma³a mnie w k³amstwie? Nie wiem, co teraz myœleæ.}
{267} {} {To zale¿y od ciebie, Cody.}
{268} {} {Dziêkujê za otwarcie oczu. Teraz muszê dok³adnie przemyœleæ to wszystko.}
{1268} {} {Dziêkujê za otwarcie oczu. Teraz muszê dok³adnie przemyœleæ to wszystko.}
{269} {} {Oczywiœcie. Mam nadziejê, ¿e dojdziesz do w³aœciwych wniosków. Zegnaj ch³opcze.}
{270} {} {Co jest, œwiat rozpada siê na twoich oczach? Tak, Blacharze okazali siê przebieg³ymi i podstêpnymi dupkami, prawda?}
{271} {} {Nie myœl, ¿e nienawidzê teraz tego miejsca. Ale teraz nie dam siê tak ³atwo oszukaæ.}
{272} {} {Podoba mi siê twój sposób myœlenia. Nie pozwól Blacharzom zrobiæ z siebie kolejnej bezmózgiej pó³maszyny.}
{273} {} {W ka¿dym razie, dali ci du¿o lepsze ¿ycie ni¿ slumsy Casa Grande. Zaufaj mi, w tej dziurze nie czeka³o ciê nic dobrego.}
{274} {} {Blacharze s¹ generalnie nielubiani. Jeœli ty, nieznajomy z pustkowia, chwalisz Tu-San, to mogê tylko wierzyæ, ¿e to naprawdê lepszy dom dla mnie.}
{275} {} {Dok³adnie. Niech Tu-San bêdzie wzorem dla ca³ego pustkowia, ch³opcze.}
{276} {} {S³uchaj, czy na pewno twoi rodzice nie ¿yj¹?}
{277} {} {Pan Hard mi o tym powiedzia³. Wierzê mu.}
{278} {} {Wygl¹da na to, ¿e muszê z nim o czymœ porozmawiaæ...}
