{100} {} {Widzisz kupca Clarka.}
{101} {} {Widzisz menad¿era karawany. Jego ciemna skóra œwiadczy o niezliczonych milach podró¿y pod pal¹cym s³oñcem.}
{102} {} {Mi³ej podró¿y.}
{103} {} {Jesteœmy. W dalszej czêœci drogi znajduje siê fort Bractwa Stali.}

{200} {} {Czego chcesz?}
{201} {} {Mo¿e pogadamy? Chcia³bym mieæ kilka kontaktów w obcym mieœcie.}
{202} {} {Wiêc nie masz szczêœcia. Zajmujê siê karawan¹ i mam specjaln¹ umowê z Blacharzami, nie potrzebujê dodatkowych znajomych. Chocia¿ ciê rozumiem - sam by³em obcy w tym mieœcie, kiedy tu przyjecha³em.}
{203} {} {Wygl¹da na to, ¿e masz o coœ zapytaæ.}

{210} {} {Czego chcesz?}
{211} {} {Nic.}
{212} {} {Chcia³bym jeszcze porozmawiaæ.}

{220} {} {Co robisz?}
{221} {} {Przewo¿ê ³adunki przez pustyniê. Blacharze ufaj¹ mi w tej bran¿y jak nikomu innemu.}
{222} {} {Przewozisz ³adunki przez pustyniê? Kto ich tam potrzebuje?}
{223} {} {Brzmi nieprawdopodobnie, ale rzeczywiscie jest kilka miejsc na pustyni, gdzie czekaj¹ na nasz ³adunek. I p³ac¹ za to doskona³ymi kapslami.}
{224} {} {Czy tam te¿ niewolnicy to gor¹cy towar?}
{225} {} {Ju¿ nie. Wczeœniej byli tam t³umnie pêdzeni z Phoenix, aby oczyœciæ ruiny i zbudowaæ osady. Ale teraz nie ma takiej potrzeby. Jednak ostatnio niewolnicy stali siê popularni na pó³nocy.}
{226} {} {To Phoenix - gdzie to jest?}
{227} {} {Naprawdê nie wiesz? Och, wiêc du¿o przegapi³eœ. To du¿e miasto na pó³nocy. JedŸ wzd³u¿ 10. autostrady federalnej, na pewno go nie przegapisz.}
{1227} {} {Naprawdê nie wiesz? Och, wiêc du¿o przegapi³aœ. To du¿e miasto na pó³nocy. JedŸ wzd³u¿ 10. autostrady federalnej, na pewno go nie przegapisz.}
{228} {} {Dziêki.}

{230} {} {Wiêc kim naprawdê s¹ Blacharze?}
{231} {} {Coœ jak kult, czcz¹ technologie i postêp. Ich najwiêkszym marzeniem jest zdobycie cia³ robotów i przes³anie do nich swoich œwiadomoœci. Brzmi fantastycznie, prawda? Ju¿ wszczepiaj¹ sobie jakieœ gruczo³y. A z ich umiejêtnoœciami technicznymi nikt w ca³ej Sonorze nie mo¿e siê równaæ.}
{232} {} {Jakie s¹ ich nastêpne plany?}
{233} {} {Nie wiem, ja tylko przewo¿ê towary. Ale Blacharze najwyraŸniej planuj¹ coœ du¿ego.}
{234} {} {Dlaczego tak myœlisz?}
{235} {} {Kupuj¹ du¿o rudy uranu i niewolników. Musz¹ odzyskaæ utracone stare technologie, a to jest obarczone powa¿nymi inwestycjami w Phoenix lub gdzieœ indziej. O tak, ju¿ wyczuwam zysk mojej karawany na nadchodz¹ce lata.}
{236} {} {Nie widzia³eœ, jak Bractwo wylecia³o w powietrze?}
{237} {} {Có¿, teraz prawie nic nie zosta³o. Ale po drodze wci¹¿ s¹ plantacje Casa Nueva. Jednak jak d³ugo bêdzie mia³a doœæ si³y, by przetrwaæ bez ochrony Bractwa Stali? Wczeœniej czy póŸniej osada bêdzie pos³uszna woli Blacharzy lub stanie siê pusta.}
{238} {} {Wygl¹da na to, ¿e ¿ycie tam siê pogorszy. Zmienimy temat?}

{240} {} {Czy trudno jest przewoziæ ³adunek przez pustkowiê?}
{241} {} {Jesteœmy w tym mistrzami. Musisz siê dostosowaæ i czekaæ na pory roku najbardziej odpowiednie do podró¿y.}
{242} {} {Jakie niebezpieczeñstwa czekaj¹ na Pustkowiach Sonory?}
{243} {} {Oczywiœcie przede wszystkim to odwodnienie i brak jedzenia. W Casa Grande wodê zamawiamy z wyprzedzeniem. To wystarczy, ¿eby dostaæ siê do zatoki. A tam ju¿ morska woda jest odsalana.}
{244} {} {A co z bandytami?}
{245} {} {Nikt nie prze¿yje na takich piaskach oprócz Radskorpionów. Wygl¹da na to, ¿e opiekowa³y siê Sonor¹, aby wyhodowaæ swoje potomstwo. Ale prawie nigdy nie spotkaliœmy bandytów. W tych miejscach ludzie s¹ rzadkoœci¹.}
{246} {} {Twoja historia tylko podsyca moj¹ ciekawoœæ. Powiedz mi wiêcej.}
{247} {} {Dziêki za informacje. Muszê przygotowaæ siê do podró¿y.}

{300} {} {Muszê dostaæ siê do Steel Port.}
{301} {} {Steel Port? S³yszê o tym po raz pierwszy.}
{302} {} {Mo¿esz mi zaufaæ.}
{303} {} {Nie martw siê, do³¹czam do Bractwa Stali.}
{304} {} {Nie martw siê, jestem jednym z wyznawców ognia.}
{305} {} {Przepraszam. Ale mo¿e wiesz o innych rzeczach.}
{306} {} {Zaufaj mi, ¿adna karawana tam teraz nie jedzie. Coœ posz³o nie tak z Bractwem Stali, w wyniku czego ich statek eksplodowa³ jak cholerny ¿uk bombowy. Teraz zamiast statku jest tam radioaktywny lejek i nie ma tam ani jednej ¿ywej duszy.}
{307} {} {Wow... to niespodzianka.}
{308} {} {Nie s¹dzê.}

{310} {} {Ok, widzê, ¿e jesteœ swój. Musimy byæ ostro¿ni, poniewa¿ Bractwo ma wielu wrogów.}
{311} {} {Wiêc mogê jechaæ z twoj¹ karawan¹?}
{312} {} {Przygotuj siê o 6 rano, nie spóŸnij siê. Zabierz ze sob¹ nie wiêcej ni¿ 150 funtów ³adunku. Pamiêtaj, zatrzymamy siê w Casa Nueva. To jedyna osada na drodze do Bractwa.}
{313} {} {Mogê iœæ.}
{314} {} {Bêdê o wyznaczonej godzinie.}
{315} {} {Nikt nie bêdzie nosi³ twoich rzeczy! Ogranicz dodatkowy ³adunek albo odjedziemy bez Ciebie.}
{316} {} {To bêd¹ moje problemy.}
{317} {} {Cokolwiek powiesz.}
{318} {} {Dobra, przygotuj siê na ciê¿k¹ wêdrówkê przez pustkowia.}
{319} {} {[Zacznij podró¿]}
{320} {} {Mo¿e tak. Albo mo¿e nie.}
{321} {} {Ok, jeszcze raz spojrzê na mój plecak.}
{322} {} {Zap³acê 1000 kapsli za eskortê.}
{323} {} {Na pewno masz tyle kapsli?}
{324} {} {Pozwól mi policzyæ ...}

# Inne lokalizacjê
{400} {} {Spêdzimy noc w tej osadzie. Masz trochê czasu, ¿eby siê rozejrzeæ. Nie zasypiaj wyjazdu karawany, w przeciwnym razie odjedziemy bez Ciebie.}
{401} {} {Co mo¿esz mi powiedzieæ o tej osadzie?}
{402} {} {Casa Nueva to kwitn¹ca oaza poœrodku pustyni. To najlepsze miejsce, jakie znam. Ale warunki tutaj s¹ doœæ trudne. Zachowaj szczególn¹ ostro¿noœæ i szacunek w stosunku do miejscowej ludnoœci.}
{403} {} {Do zobaczenia.}
{404} {} {[Poczekaj, a¿ karawana odjedzie]}
{405} {} {WyjdŸ beze mnie, spóŸniê siê.}
{406} {} {Jak sobie ¿yczysz. Pamiêtaj jednak, ¿e podró¿ przez ja³owe pustkowia Sonory nie jest ³atwa, nawet w grupie z karawan¹.}
{407} {} {Rozumiem, pa.}