{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz stra¿nika karawany. Odpoczywa po mêcz¹cej podró¿y.}

{110} {} {Swietnie.}
{111} {} {Daj mi trochê odpocz¹æ.}
{112} {} {Chcesz podró¿owaæ z nami?}
{113} {} {Droga miêdzy Phoenix i Tu-San jest gor¹ca.}
{114} {} {Burze piaskowe s¹ czasami bardziej niebezpieczne ni¿ najeŸdŸcy.}
{115} {} {Mamy niebezpieczn¹ pracê.}
{116} {} {Porozmawiaj z szefem, ja tylko strzegê ³adunku.}
{117} {} {Na twoim miejscu trzyma³bym siê z daleka od Blacharzy.}
{118} {} {Potrzebujesz porady? Nie idŸ do lokalnego lekarza.}
{119} {} {Poœpiesz siê, aby wróciæ do Phoenix.}
{120} {} {Blacharze nie lubi¹ obcych i staraj¹ siê unikaæ niepotrzebnych rozmów.}
{121} {} {Ci Blacharze mnie przera¿aj¹ - s¹ jak roboty.}