{100} {} {Widzisz ch³opa.}
{101} {} {Widzisz ch³opa o doœæ zwyczajnym wygl¹dzie. Dziwnie jest go widzieæ w ca³ym tym t³umie.}
{102} {} {Dziêkujê za pomoc. Nie zapomnimy o tym i opowiemy wszystkim o Twoim wyczynie.}

{200} {} {Hej, nie jesteœ miejscowy, prawda? Tacy ludzie s¹ natychmiast widoczni. Dam ci darmow¹ radê - nie zadzieraj z tymi typami. Nie ceni¹ obcych.}
{201} {} {A ty...}
{202} {} {Kolejna ofiara ich z³ej wiary, jeœli chcesz wiedzieæ. Blacharze odmawiaj¹ sprzeda¿y ogniw do generatora w mojej osadzie. A wiesz dlaczego? Poniewa¿ nazwali nas niegodnymi starej technologii!}
{203} {} {Opowiedz mi wiêcej o tym problemie.}
{204} {} {To nie moja sprawa. Do widzenia.}

{210} {} {Co chcesz wiedzieæ?}
{211} {} {Nic wiêcej. Czeœæ.}
{212} {} {Muszê iœæ.}
{213} {} {Powiedz mi wiêcej.}

{220} {} {Opowiedz mi o swojej osadzie.}
{221} {} {To tylko ma³a wiejska spo³ecznoœæ. Niedawno zepsu³ siê nasz generator - a to jedyne Ÿród³o pr¹du w ca³ej dolinie. Musia³em zwróciæ siê o pomoc do Blacharzy, ale uwa¿aj¹, ¿e jesteœmy mali i s³abo rozwiniêci.}
{222} {} {Czy ten generator jest dla Ciebie tak wa¿ny?}
{223} {} {Ca³a nasza spo³ecznoœæ by³a na tym oparta! Pompa wodna, oœwietlenie, komunikacja radiowa - bez tego nasza dolina ponownie zamieni siê w pustyniê i stanie siê niezdatna do zamieszkania.}

{230} {} {Nigdzie indziej nie mo¿na zdobyæ ogniw zasilaj¹cych?}
{231} {} {Blacharze s¹ * jedynymi * którzy je robi¹ w dzisiejszych czasach. A przedwojenne przedmioty sta³y siê trudne do znalezienia. Przecie¿ okolica od dawna jest pustoszona przez tych tech-fanatyków.}
{232} {} {Czy próbowa³eœ szukaæ w Phoenix?}
{233} {} {Zartujesz? Jesteœmy osiad³ymi ludŸmi, pokonanie takiego dystansu bêdzie du¿ym wyzwaniem. Ponadto Du¿e Miasto równie¿ kupuje baterie od Blacharzy. Ceny s¹ tam znacznie wy¿sze.}

{240} {} {Dlaczego Blacharze nie chc¹ z tob¹ handlowaæ?}
{241} {} {Uwa¿aj¹ nas za niegodnych ich technologii. Uwa¿a siê, ¿e zmarnujemy ich cenny zasób. Ale to kompletna bzdura - potrzebujemy ogniw do przetrwania, co mo¿e byæ wa¿niejsze?!}

{250} {} {Co zamierzasz teraz zrobiæ?}
{251} {} {Pilnie potrzebujemy ogniw... S³uchaj, jesteœ ch³opem, tak jak my, prawda? Widzê to. Nie schowasz siê za tym ca³ym ubraniem i zbroj¹, twoje oczy i rêce zdradzaj¹ to, co robisz. Musimy siê trzymaæ razem, amigo. Pomó¿ nam, a my pomo¿emy Tobie.}
{1251} {} {Pilnie potrzebujemy ogniw... S³uchaj, jesteœ ch³opk¹, tak jak my, prawda? Widzê to. Nie schowasz siê za tym ca³ym ubraniem i zbroj¹, twoje oczy i rêce zdradzaj¹ to, co robisz. Musimy siê trzymaæ razem, seniora. Pomó¿ nam, a my pomo¿emy Tobie.}
{252} {} {Dlaczego mam ci pomóc?}
{253} {} {Mam wielu znajomych wœród karawan, mogê negocjowaæ z nimi eskortê i poprawiê twoj¹ reputacjê. A tak¿e te przedwojenne pieni¹dze. Wygl¹da na to, ¿e nie s¹ ju¿ u¿ywane, ale mo¿e znajdziesz dla nich zastosowanie.}
{254} {} {Przemyœlê Twoj¹ ofertê.}
{255} {} {Z kim mogê porozmawiaæ o tych ogniwach energetycznych?}
{256} {} {S¹ w magazynie w tym du¿ym hangarze, a kwatermistrz jest odpowiedzialny za magazyn. Ale w¹tpiê, ¿eby zmieni³ swoje nastawienie.}
{257} {} {Zobaczymy.}
{258} {} {Innymi s³owy sugerujesz, ¿eby okraœæ Blacharzy?}
{259} {} {Tak jakby oni tego nie robili. Ale uratujesz ca³¹ osadê i zaprzyjaŸnisz siê z uczciwymi ludŸmi. Co o tym myœlisz, amigo?}

{260} {} {Nigdy nie myœla³em, ¿e zobaczê tu kogoœ innego!}
{261} {} {Co tutaj robisz?}
{262} {} {Potrzebujê ogniw zasilaj¹cych do generatora. S¹ w magazynie w hangarze, ale nie mogê siê tam dostaæ niezauwa¿ony. Wygl¹da na to, ¿e w³aœnie stamt¹d przyby³eœ i wygl¹da na to, ¿e roboty ciê nie dotykaj¹. Czy mo¿esz je za³atwiæ?}
{263} {} {Zobaczê, co bêdê móg³ zrobiæ.}
{264} {} {Sam rozwi¹¿ swój problem. Ja ju¿ zdecydowa³em.}
{265} {} {Pomyœl, ¿e mnie tu ju¿ nie ma.}

{300} {} {Oto ogniwo zasilaj¹ce do generatora.}
{301} {} {Niesamowite! Jak ci siê to uda³o? Jednak nie chcê wiedzieæ. Pora, ¿ebym siê st¹d wydosta³, póki mogê. Dziêkujê, amigo, nasza spo³ecznoœæ upad³aby bez Ciebie.}
{302} {} {Hej, nie zapomnia³eœ o czymœ?}
{303} {} {Przepraszam, ale oszuka³em Ciê - nie mam przyjació³ wœród karawan. Ale nadal opowiem wszystkim znajomym o twoim wyczynie. Jeœli chcesz, chodŸmy razem do Casa Grande, tak jest bezpieczniej. Zdecyduj teraz, nie bêdê czekaæ.}
{304} {} {ChodŸmy wiêc.}
{305} {} {Nie, tutaj nasze œcie¿ki siê rozchodz¹. Szczêœcia.}
{306} {} {No to idziesz ze mn¹? Droga do Casa Grande jest trudna, bezpieczniej bêdzie Ci podró¿owaæ ze mn¹.}