{100} {} {Widzisz pacjenta.}
{101} {} {Widzisz chorego Blacharza. Cierpi na powik³ania pooperacyjne.}
{102} {} {Jak wyleczy³a mnie medycyna prymitywna? To nielogiczne!}
{104} {} {Dlaczego... Nie jestem jeszcze... zdigitalizowany...}
{105} {} {Mój... biomatrix... dzia³a nieprawid³owo...}

{110} {} {Rozbierz mnie.}
{111} {} {Doktorze, czy bêdê dezaktywowany?}
{112} {} {Za³ujê tylko, ¿e nie doczeka³em digitalizacji mojej to¿samoœci.}
{113} {} {Czas poœwiêciæ siê Postêpowi.}
{114} {} {Coœ posz³o nie tak z moim biomatrixem.}

{115} {} {Dziêki za poprawê mojego stanu.}
{116} {} {Kiedy by³em na skraju, du¿o przemyœla³em.}
{117} {} {Muszê przemyœleæ moje algorytmy.}
{118} {} {Teraz ju¿ nie wierzê, ¿e Postêp jest wart mojego poœwiêcenia.}
{119} {} {Z moim biomatrixem jest ju¿ wszystko w porz¹dku.}