{100} {} {Widzisz Blacharza.}
{101} {} {Widzisz jednego ze zwyk³ych mieszkañców Tu-San.}

# Plywajace repliki
{110} {} {Bogowie stali s¹ Ÿli z powodu naszej powolnoœci.}
{111} {} {Dlaczego Bogowie zamilkli? Zapomnieli o nas?}
{112} {} {Bogowie staj¹ siê zadowoleni.}

{113} {} {Casa Nueva mo¿e ograniczaæ zapasy ¿ywnoœci.}
{114} {} {Obiecano nam wiêcej jedzenia z Casa Nueva.}
{115} {} {Z Casa Nueva dochodz¹ niepokoj¹ce pog³oski, teraz nie jest tam bezpiecznie.}

{116} {} {Bandyci okradli kolejn¹ karawanê z Phoenix.}
{117} {} {Kr¹¿¹ pog³oski, ¿e Niebieskie Tarcze zosta³y ostatecznie zdetronizowane.}
{118} {} {Niebieskie Tarcze staj¹ siê silniejsze. Teraz trzeba siê z nimi liczyæ.}

{119} {} {Ci czciciele ognia zawsze wydawali mi siê œmieszni.}
{120} {} {Wyznawcy ognia dostali to, o czym marzyli.}
{121} {} {Bezczelni czciciele ognia próbuj¹ nam mówiæ, co mamy robiæ.}

{122} {} {Ten uran z Flagpool to za ma³o.}
{123} {} {Musimy oszczêdzaæ energiê, dopóki kopalnie Flagpool nie wróc¹ na w³aœciwe tory.}
{124} {} {Nie ma potrzeby oszczêdzania energii dziêki rezerwom uranu z Flagpool.}

{125} {} {Dostêp do zakazanej strefy zmieni³by ca³e nasze ¿ycie.}
{126} {} {Musimy odejœæ, zanim ZAX w koñcu wyzwoli na nas swój gniew.}
{127} {} {Wstêp do zakazanej strefy zmieni nasze ¿ycie.}

{128} {} {Po ostatniej operacji Master Hard sta³ siê niewra¿liwy.}
{129} {} {Kolejna wizyta u Doktora Jonesa mo¿e byæ ostatni¹.}
{130} {} {Znaj swoje miejsce w Kolektywie.}

{131} {} {Pamiêtaj, aby przed jedzeniem pomodliæ siê do Boga technologii.}
{132} {} {Módlcie siê do Bogów ze stali za to, kim jesteœmy.}
{133} {} {Moje stawy wymagaj¹ czyszczenia.}