{100} {} {Widzisz Blacharza.}
{101} {} {Widzisz mieszkañca Tu-San. Wygl¹da na bardziej cywilizowanego ni¿ inni mieszkañcy.}
{102} {} {Zdoby³eœ przychylnoœæ miejscowej ludnoœci.}

# Pierwszy dialog
{200} {} {(widzisz ³ys¹ kobietê ze wzmacniaczem optycznym pod lewym okiem) Kolejny dzikus z pustkowi z prymitywn¹ ide¹ Postêpu. W tym przypadku nasza rozmowa jest nieistotna. IdŸ st¹d.}
{201} {} {Jakoœ prze¿yjê.}
{202} {} {Myœlê, ¿e du¿o tracisz.}
{203} {} {Mój pomys³ na Postêp bêdzie dla ciebie zaskoczeniem.}
{204} {} {Moje cz³onkostwo w Bractwie Stali mo¿e zmieniæ twoje zdanie.}
{205} {} {Po wszystkich moich wysi³kach nale¿y mi siê wiêksze zaufania.}

{206} {} {Moje dane sugeruj¹ inaczej.}
{207} {} {Ok.}
{208} {} {(pauza) Niech bêdzie.}
{209} {} {Ok, uh, ju¿ siê zaczeliœmy.}

# Powtarzajacy siê dialog
{210} {} {Co chcesz wiedzieæ?}
{211} {} {Prawdopodobnie nic wiêcej. PA.}
{212} {} {Pozwól, ¿e zadam ci inne pytanie.}

{213} {} {Dlaczego nie chcesz ze mn¹ rozmawiaæ?}
{214} {} {Osoby z zewn¹trz o niskim tempie rozwoju nie zas³uguj¹ na nasze zaufanie. Zyski handlowe s¹ wyj¹tkiem, zw³aszcza w przypadku ¿ywnoœci. Czy masz coœ do jedzenia?}
{215} {} {Sprawdzê w mojej torbie, mo¿e mam.}
{216} {} {Nic ode mnie nie dostaniesz.}
{217} {} {Mój prezent w postaci jedzenia zas³uguje na kilka odpowiedzi.}

#Pytania
{220} {} {Czy mo¿esz mi powiedzieæ, dlaczego Blacharze kupuj¹ niewolników?}
{221} {} {Potrzebujemy si³y roboczej, aby robiæ postêpy. Bez niewolników proces by³by znacznie wolniejszy i mniej wydajny. Któregoœ dnia zast¹pimy niewolników robotami, ale zajmie to du¿o czasu i energii, których teraz tak bardzo nam brakuje.}
{222} {} {Opowiedz mi o postêpach.}
{223} {} {D¹¿ymy do technologicznej i cywilizacyjnej doskona³oœci, tak jak to by³o przed Wielk¹ Wojn¹. W naszych czasach Postêp jest niezbêdny do przetrwania ludzkoœci jako gatunku.}
{224} {} {}
{225} {} {}
{226} {} {Czy wiesz coœ o niewolnikach z Villi?}
{227} {} {Nie. Powinieneœ to omówiæ z Master Hardem, naszym liderem.}
{228} {} {I zgadzasz siê z t¹ nieludzk¹ praktyk¹?}
{229} {} {Etyczny aspekt sprawy nie ma znaczenia. Postêp jest wart poœwiêcenia, da ludziom wiêcej ni¿ garstke prymitywnych ludzi z pustkowia.}

{230} {} {Co robisz?}
{231} {} {Pomagam robotnikom w hangarze. Przygotowujê sk³adniki od¿ywcze i utrzymujê porz¹dek w kompleksie mieszkaniowym.}
{232} {} {Wiêc Blacharze maj¹ rodziny?}
{233} {} {Rodzina... Wielu Blacharzy mia³o rodziny. Ale to nie ma teraz znaczenia.}
{234} {} {Dlaczego?}
{235} {} {Przyjmujemu dzieci z pustkowi i uczymy je, aby s³u¿y³y naszej spo³ecznoœci. Osobowoœæ nie ma znaczenia. Rodzina nie jest potrzebna.}
{236} {} {Niektórzy Blacharze ró¿ni¹ siê od innych.}
{237} {} {Nasze spo³eczeñstwo jest podzielone na poziomy. Ka¿dy poziom ma w³asny zestaw wiedzy i technologii. Na przyk³ad tylko najlepsi cz³onkowie zespo³u mog¹ wykonywaæ skomplikowane i kosztowne zabiegi implantacji.}

{240} {} {Dlaczego jesteœcie tacy nieufni wobec obcych?}
{241} {} {Zaufanie nie ma znaczenia. Szybkoœci¹ rozwoju przewy¿szamy prawie wszystkich mieszkañców Pustkowia. W takiej sytuacji osoby z zewn¹trz mog¹ byæ przydatne g³ównie jako niewolnicy, w niektórych przypadkach jako partnerzy handlowi.}
{242} {} {Nadal macie po³¹czenia zewnêtrzne.}
{243} {} {Racja... Do niedawna byliœmy zamkniêt¹ spo³ecznoœci¹ i nikomu nie pozwalaliœmy na kontakt z nami.}
{244} {} {Co siê zmieni³o?}
{245} {} {Niedobory ¿ywnoœci, obliczenia matematyczne perspektyw i kontakt z jedn¹ wysoko rozwiniêt¹ spo³ecznoœci¹ zmieni³y nasze podejœcie. Ale nie mogê rozmawiaæ o tym z osobami z zewn¹trz.}
{246} {} {Ciekawy punkt widzenia.}