{100} {} {Widzisz Abla.}
{101} {} {Widzisz przedstawiciela Koœcio³a Swiêtego Ognia.}

# Pierwszy dialog
{200} {} {Jesteœ tu w interesach? Wiêc musisz zobaczyæ siê z Master Hardem. Mo¿na go znaleŸæ w warsztacie.}
{201} {} {Dziêki.}
{202} {} {Chcia³bym ciê poznaæ.}
{203} {} {Zbyt to uprzejme, ¿eby by³o prawdziwe. Nazywam siê Abel, jestem jednym z Wyznawców Ognia, jeœli to ci coœ mówi. Przestañ marnowaæ mój czas.}
{204} {} {Co robisz?}
{205} {} {Widzê, ¿e nie mo¿esz tak ³atwo odpuœciæ. Koœció³ potrzebuje us³ug Blacharzy, jak ka¿da wspó³czesna spo³ecznoœæ. Polecono mi monitorowaæ realizacjê zamówieñ.}
{206} {} {Czy Blacharze rzeczywiœcie s¹ tacy dobrzy?}
{207} {} {S¹ najlepsi w tym, co robi¹. Byæ mo¿e ju¿ spotka³eœ ich wynalazki. Broñ pneumatyczna, urz¹dzenia komputerowe, a nawet protezy i proste implanty. Na szczêœcie Blacharze nie s¹ na tyle g³upi, by dzieliæ siê z ka¿dym. Niechêtnie dziel¹ siê wiedz¹ i technologi¹. Nasz koœció³ by³ zaszczycony, mog¹c znaleŸæ z nimi wspólny jêzyk.}
{208} {} {Rozumiem. Có¿, przyjrzê siê temu wszystkiemu w akcji. PA.}
{209} {} {Mówi¹c proœciej, s¹ to ludzie, którzy lubi¹ w³adzê w tym regionie. Wszystkiego najlepszego.}

# Powtarzajacy siê dialog
{210} {} {Znowu?}
{211} {} {Zapomnij.}
{212} {} {Jak mogê pomóc, bracie?}
{1212} {} {Jak mogê pomóc, siostro?}
{213} {} {Dziêki, coœ wymyœlê.}
{214} {} {Doœæ informacji na dziœ.}
{215} {} {Marnujê tylko czas na rozmowê z tob¹.}
{216} {} {Nie ma problemu, w³aœnie wychodzê.}

{220} {} {Opowiedz mi o swoim koœciele.}
{221} {} {To jest za d³ugi temat na rozmowê tutaj. Lepiej odwiedŸ nasz¹ Swi¹tyniê w Phoenix i dowiedz siê bezpoœrednio z kazañ.}
{222} {} {Dobrze.}

{230} {} {W³aœciwie to ja te¿ jestem zwolennikiem ognia.}
{231} {} {Naprawdê? To bardzo wiele zmienia. Witamy w Tu-San, bracie. Razem bêdziemy wychwalaæ Swiêty Ogieñ.}
{1231} {} {Naprawdê? To bardzo wiele zmienia. Witamy w Tu-San, siostro. Razem bêdziemy wychwalaæ Swiêty Ogieñ.}
{232} {} {Widzê, ¿e teraz jesteœ bardziej przychylny. Czy mo¿esz odpowiedzieæ na kilka pytañ?}
{233} {} {Rozumiem.}
{234} {} {Dziêkujê za odpowiedŸ. Teraz czas na mnie.}

{240} {} {Co naprawdê robi koœció³ w Tu-San?}
{241} {} {Jak powiedzia³em, koœció³ potrzebuje technologii i wiedzy. To jedna z naszych g³ównych prawd - Swiêty Ogieñ spali³ star¹ cywilizacjê, aby na jej miejscu zbudowaæ now¹. Blacharze s¹ budowniczymi tej nowej cywilizacji. Ich umiejêtnoœci produkcyjne i technologia s¹ niezbêdne do przetrwania i rozwoju. Niestety, wielu na pustkowiach nie rozumie idei Postêpu, boj¹ siê zmieniæ skostnia³y sposób ¿ycia.}
{242} {} {Jakie zamówienia realizuj¹ obecnie Blacharze?}
{243} {} {Najwa¿niejsze zamówienie to baterie energetyczne. Bez nich ¿adna powa¿na technika nie jest cenniejsza ni¿ sterta œmieci. Wytwarzaj¹ te¿ broñ i naprawiaj¹ star¹ elektronikê.}
{244} {} {Sk¹d Blacharze znaj¹ siê na technologii?}
{245} {} {Ich umiejêtnoœci by³y przekazywane z pokolenia na pokolenie. Otrzymali jak¹œ dokumentacjê za poœrednictwem naszego koœcio³a lub kupili j¹ od karawan.}
{246} {} {Nie g³osisz nauk w tym mieœcie?}
{247} {} {Koœció³ chce siê rozwijaæ, ale w Tu-San wystarczy mieæ jednego ambasadora. Blacharze nie we wszystkim podzielaj¹ nasz¹ wiarê, ale ich zrozumienie wystarczy do wspólnych osi¹gniêæ.}
{248} {} {Coœ mi mówi, ¿e s¹ rozkazy, o których wola³byœ milczeæ.}
{249} {} {Teraz rozumiem, dlaczego koœció³ ciê przyj¹³. Tak, istnieje kilka specjalnych technologii, o których zwykli œmiertelnicy nie powinni wiedzieæ. Mo¿e to zak³óciæ równowagê si³ lub wywo³aæ fale protestów publicznych.}
{250} {} {Nie ma niczego niezwyk³ego w historii, ¿e niby pokojowa technologia by³a u¿ywana jako broñ. Nawet jeœli krzywda przewa¿a³a nad korzyœciami.}
{251} {} {Jeœli ktokolwiek mo¿e zrobiæ postêp w tym regionie, jesteœmy to my, s³udzy Swiêtego Ognia. Zyliœmy z t¹ myœl¹ i nie zamierzamy z niej rezygnowaæ. Zaufaj mi, koœció³ robi wszystko, aby Sonora sta³a siê zamo¿nym rajem.}

{260} {} {Blacharze zniewolili kilku moich znajomych. Czy mo¿na ich jakoœ uwolniæ?}
{261} {} {Ale po co? Nie s¹dzê, ¿eby twoi znajomi byli tak cenni poza niewol¹. S³u¿enie Postêpowi to wielki zaszczyt i korzyœæ dla ca³ej ludzkoœci. W ka¿dym razie wiêkszoœæ niewolników zosta³a ju¿ wys³ana do Zakazanej Strefy. Bêdziesz musia³ siê tam udaæ i samemu ocaliæ swoich przyjació³.}
{262} {} {PóŸniej poszukam rozwi¹zania, porozmawiajmy teraz o innych tematach.}
{263} {} {Myœlê, ¿e musi byæ inny sposób, aby ich uwolniæ. Bywaj.}

Kult wroga #GG
{300} {} {To znowu ty? Wynoœ siê z tego miasta, zanim wezwê stra¿ników.}
{301} {} {Czekaj, sk¹d w tobie tyle wrogoœci?}
{302} {} {Nie mów moim jêzykiem, atomowy ignoranto! Wyznawcy Ognia maj¹ dobr¹ sieæ informatorów, zosta³em ju¿ poinformowany o twoim wygnaniu. IdŸ st¹d!}
{303} {} {Spokojnie...}

{310} {} {Stop. Kto Ciê przys³a³?}
{311} {} {Nikt. Dlaczego jesteœ taki zdenerwowany?}
{312} {} {Mam powody. I nie powinieneœ w ogóle pokazywaæ siê w tym mieœcie. To bardzo podejrzane, ¿e wróg Koœcio³a Ognia nagle z³o¿y³ wizytê Blacharzom. Wygl¹da na to, ¿e grasz w swoj¹ grê pod naszymi nosami.}
{313} {} {Wiêc Koœció³ Ognia jest teraz w nie³asce?}
{314} {} {Koœció³ by³ g³ównym motorem postêpu w po³udniowej Arizonie. Teraz, gdy g³ówna œwi¹tynia zosta³a zniszczona, bêdzie trzeba wiele wysi³ku, aby odzyskaæ dawn¹ wielkoœæ i zaufanie. Ale Blacharze s³u¿¹ nam ju¿ prawie dziesiêæ lat. Nie bêd¹ oszukiwaæ swoich klientów z powodu jednego nieporozumienia.}
{315} {} {Ale dlaczego jesteœ taki zdenerwowany? Wygl¹da na to, ¿e Blacharze nie s¹ ju¿ tak ulegli, prawda?}
{316} {} {Myœleliœmy o nich jak o maszynach roboczych. Teraz, gdy poczuli wolnoœæ i wy¿szoœæ, mogli pokazaæ swoj¹ prawdziw¹ twarz. A teraz przestañ szydziæ, nikczemny atomie. ZejdŸ mi z oczu.}
{317} {} {Wiesz, nie muszê wychodziæ z Tu-San. Czeœæ.}
{318} {} {Cieszê siê, ¿e mogê zostaæ, mizantropie...}
{319} {} {Daj spokój, nie jest tak Ÿle...}
{320} {} {Zostaw mnie, demonie rozszczepienia atomu!}
{321} {} {Co ty...}