{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz Blacharza pilnuj¹cego wejœcia do osady.}
{102} {} {Mo¿esz przejœæ. Ale bêdziemy mieæ ciê na oku.}
{103} {} {Zakaz wstêpu bez pozwolenia!}
{104} {} {(chowa jedzenie i rozgl¹da siê) Mo¿esz iœæ, ale nie rób nic g³upiego.}

# Scena przerywnikowa przy bramie
{110} {} {Coœ siê dzieje przy g³ównej bramie.}
{111} {} {Wpuœæ mnie natychmiast! Hard ma mnie wys³uchaæ!}
{112} {} {Twoje ma³e plemiê za du¿o myœli o sobie. OdejdŸ.}
{113} {} {Jak œmiesz! Od lat polegacie na naszych dostawach, nie mo¿ecie nas tak po prostu zignorowaæ!}
{114} {} {Teraz Zakazana Strefa daje nam wszystko. Nie jesteœ ju¿ potrzebny. OdejdŸ, zanim u¿yjê si³y.}
{115} {} {Cholera!}
{116} {} {}
{117} {} {}
{118} {} {}
{119} {} {}

# Podstawowy dialog
{200} {} {Staæ. To zamkniêty obszar. Podaj cel swojej wizyty.}
{201} {} {Nie, ju¿ wychodzê.}
{202} {} {Rozumiem.}

{210} {} {Nie jesteœmy tym zainteresowani. IdŸ st¹d.}
{211} {} {Wpuœæ mnie, przeklêty cyborgu!}
{212} {} {Ok, spokojnie wyjdê. Ale mo¿e wrócê.}
{213} {} {OdejdŸ. W przeciwnym razie moc Postêpu zrówna ciê z ziemi¹.}
{214} {} {Przekonamy siê o tym...}
{215} {} {Mo¿esz przejœæ. Bêd¹c w œrodku - schowaj broñ i nie wpadaj w k³opoty. Nie rozmawiaj z niewolnikami. Nie wchodŸ do zakazanej strefy bez pozwolenia. IdŸ prosto do hangaru i porozmawiaj z naszym przywódc¹, to Master Hard. To wszystko.}
{216} {} {Doœæ surowe zasady. Postaram siê nie stwarzaæ problemów.}
{217} {} {Nie trzeba nic dodawaæ. Wszystko jest jasne. A teraz zejdŸ z drogi.}
{218} {} {Mój motor wymaga serwisu.}

{220} {} {Szukam moich krewnych.}
{221} {} {Mo¿e tu s¹. A mo¿e nie. Gromadzimy ludzi do pracy z ca³ego pustkowia, naprawdê potrzebujemy r¹k do pracy. Jeœli chcesz znaleŸæ krewnych, musisz udaæ siê do warsztatu.}
{222} {} {Rozumiem.}

{223} {} {Jestem tutaj, aby handlowaæ.}
{224} {} {Potrzebujemy zapasów. Master Hard bêdzie zainteresowany nowymi dostawami.}
{225} {} {Swietnie, liczê dostaæ dobr¹ ofertê.}

{226} {} {Szukam technologicznego oœwiecenia.}
{227} {} {Od stu lat ³¹czy nas jeden kabel zasilaj¹cy. Kim jesteœ, aby szukaæ u nas oœwiecenia? Jednak czasy siê zmieni³y. Mo¿e Master Hard z tob¹ porozmawia.}
{228} {} {Dobrze, porozmawiam z nim.}

{229} {} {Potrzebujê konserwacji. Na pocz¹tek dwieœcie kapsli.}
{230} {} {Kochamy pracê i kochamy technologie. Twój problem stanie siê naszym problemem, jeœli bêdziesz w stanie zap³aciæ.}
{231} {} {Myœlê, ¿e znajdê odpowiedni¹ iloœæ kapsli.}

{232} {} {Jestem tylko pokojowym g³osicielem Swiêtego Ognia. Wpuœæ mnie na noc, hojny Blacharzu!}
{1232} {} {Jestem tylko pokojowym g³osicielem Swiêtego Ognia. Wpuœæ mnie na noc, hojny Blacharzu!}
{233} {} {Koœció³ Swiêtego Ognia jest naszym niezawodnym partnerem od kilku lat. Witamy ciê w Tu-San, ministrze.}
{1233} {} {Koœció³ Swiêtego Ognia jest naszym niezawodnym partnerem od kilku lat. Witamy ciê w Tu-San, ministrze.}
{234} {} {Mi³o to s³yszeæ.}

{235} {} {Jestem z Bractwa Stali.}
{236} {} {K³aniamy siê wielkoœci Bractwa. Twoja technologia jest doskona³a.}
{237} {} {To prawda.}

{238} {} {Widzisz tê szatê? Jestem wyznawc¹ ognia, mamy dobre stosunki z waszymi ludŸmi.}
{239} {} {Po upadku swojej cytadeli ryzykujesz samotnym pojawieniem siê tutaj. OdejdŸ i nie sprawiaj nam ¿adnych k³opotów.}
{240} {} {Cholera...}

{241} {} {Jestem w drodze z Katedry Ognia do Steel Port. Powiedziano mi, ¿e po drodze znajdê nocleg.}
{242} {} {Doceniamy to, co robi Koœció³ Swiêtego Ognia. Mo¿esz wejœæ.}
{243} {} {Dziêki.}
{244} {} {Jestem tutaj, aby handlowaæ. Ten zegarek atomowy jest jedyny w swoim rodzaju i jest mój.}

# Powtarzajacy siê dialog
{250} {} {Mo¿esz przejœæ. Ale bêdziemy mieæ ciê na oku.}
{251} {} {Oczywiœcie, uh, nie ma problemu.}
{252} {} {Hard nakaza³ dochodzenie w sprawie ataku na karawanê.}
{253} {} {To bardzo dziwne, ¿e Master Hard zaufa³ obcemu. Ale mogê tylko byæ pos³uszny.}
{254} {} {Daj mi trochê czasu, zanim wyruszê w drogê.}
{255} {} {Jak myœlisz, kto móg³ zaatakowaæ karawanê?}
{256} {} {Wczeœniej nikt nie odwa¿y³ siê wchodziæ na nasze ziemie, z wyj¹tkiem bandytów z autostrad i rzadkich z³odziei z pó³nocy. Kiedy Tu-San otworzy³o siê na œwiat, ustanowiliœmy wiele po³¹czeñ zewnêtrznych, co mog³o przyci¹gn¹æ jeszcze wiêcej bandytów. Potraktujmy to jako koszt postêpu.}
{257} {} {Co mówi¹ same karawany?}
{258} {} {Atak by³ nag³y - bandyci czekali na karawanê przez kilka dni, ukrywaj¹c siê w starym budynku przy autostradzie. Interesowa³ ich tylko ³adunek, pozwolili karawaniarzom ujœæ z ¿yciem.}
{259} {} {Czy jest w tym coœ niezwyk³ego?}
{260} {} {Niektórzy bandyci u¿ywali broni energetycznej. Uwa¿amy, ¿e zosta³a wydobyta w Zakazanej Strefie.}
{261} {} {Poka¿ mi miejsce ataku.}
{262} {} {To stara kawiarnia miêdzystanowa oddalona o kilka mil.}
{263} {} {[PrzejdŸ do miejsca ataku]}
{264} {} {I schowaj broñ, albo bêdziesz mia³ k³opoty.}
{265} {} {Ok.}

{270} {} {Dlaczego powiesiliœcie tego cz³owieka na s³upie?}
{271} {} {Wyznawcy ognia byli g³upi i niegodni naszej technologii. Cia³o tego nikczemnego cz³owieka bêdzie przyk³adem dla innych.}
{272} {} {Ok. Najwy¿szy czas, aby ci sekciarze zniknêli z naszego œwiata.}
{273} {} {Czy nie uwa¿asz, ¿e to zbyt gwa³towne? Ale w sumie to twoja sprawa.}