{110} {} {Twój osobisty asystent jest do Twojej dyspozycji.}
{111} {} {Przepraszam, nie mogê nic zrobiæ, aby ci pomóc.}
{112} {} {Proszê, utrzymuj hangar w czystoœci... Zrobi³em, co mog³em.}
{113} {} {Nie ma Ciê na liœcie naszych pracowników... niestety.}
{114} {} {Proszê opuœciæ hangar, jeœli nie masz oficjalnego pozwolenia.}
{115} {} {Nie jestem zaprogramowany do wykonywania twoich rozkazów. Przykro mi.}
{116} {} {Proszê podaæ cel swojej wizyty.}