{100} {} {Widzisz Romeo Six.}
{101} {} {Widzisz jednego z Blacharzy. Wygl¹da bardzo m³odo, prawie na nastolatka.}
{102} {} {U¿yj umiejêtnoœci chirurgii, aby usun¹æ implant.}
{103} {} {Postêpuj¹c zgodnie z instrukcjami majsterkowicza, jesteœ w stanie usun¹æ chip z jego cia³a.}
{104} {} {Obcy? Tutaj? Mo¿e powinienem jeszcze raz sprawdziæ moj¹ broñ...}

# Pierwszy dialog
{200} {} {(To nastoletni Blacharz z szeroko otwartymi oczami, przygl¹daj¹cy siê z zainteresowaniem twojej osobie) Cz³owieku z pustkowi, powinieneœ wiedzieæ, ¿e w Tu-San nie lubi siê obcych. Lepiej nie testuj naszej cierpliwoœci.}
{201} {} {}
{202} {} {Hej ch³opcze, chcê tylko porozmawiaæ.}
{203} {} {OdejdŸ. Nie wolno mi z tob¹ rozmawiaæ. (odwraca siê i oddala od Ciebie)}
{204} {} {To nie by³o zbyt mi³e...}
{1204} {} {Phi. Co za chamskie traktowanie kobiet...}
{205} {} {W twoich s³owach wyczuwam wahanie. Czy jesteœ tu samotny?}
{206} {} {(pauza ze zdziwieniem) Kolektyw uwa¿a, ¿e interakcja z niedorozwiniêtymi osobami z zewn¹trz jest bezcelowa... dopóki nie przynosi to korzyœci.}
{207} {} {Kolektyw tak uwa¿a. A Ty co myœlisz?}
{208} {} {Hej, kogo nazwa³eœ niedorozwiniêtym?}
{209} {} {Typowa brutalna reakcja. Nawet jeœli w twojej wiosce jest generator, a w³adze u¿ywaj¹ broni laserowej, nadal jesteœcie dzikusami.}
{210} {} {Jeœli nasza komunikacja jest „bezcelowa”, to dlaczego i tak ze mn¹ rozmawia³eœ? Czy masz jakieœ w¹tpliwoœci?}
{211} {} {Wiêcej tu nie przyjdê. Do widzenia...}

{212} {} {Czy sugerujesz, ¿ebym opuœci³ to miejsce?}
{213} {} {Kolektyw uwa¿a Ciê za destrukcyjny element i sugeruje unikanie kontaktu.}
{214} {} {Tak, tutaj nie jest ³atwo zdobyæ zaufanie. Do widzenia, Blacharzu.}
{215} {} {Kto tu jest destrukcyjny? Zapamiêtaj, ¿e nastêpnym razem nie bêdê tego tolerowa³.}
{216} {} {(waha siê) Najpierw... Porozmawiaj najpierw z Master Hardem.}
{217} {} {Dobrze, zapamiêtam.}
{218} {} {Tak... Nie...}
{219} {} {Nie?}

# Dialog przy toalecie
{220} {} {Nie mogê teraz mówiæ. Spotkajmy siê o 22:00 na ty³ach hotelu.}
{221} {} {Ok.}
{222} {} {To nie jest w³aœciwe miejsce. Spotkajmy siê na ty³ach hotelu.}
{223} {} {Ok.}
{224} {} {Nie us³ysz¹ nas tutaj.}
{225} {} {Wygl¹da na to, ¿e ostatnio waha³eœ siê przed swoim Kolektywem. Czy coœ ciê drêczy?}
{226} {} {Martwisz siê? Myœlê, ¿e tak. Kolektyw uczy, ¿e nasza przesz³oœæ jest nieistotna, musimy o niej zapomnieæ i ¿yæ przysz³oœci¹ ze wzglêdu na Postêp. Ale nie mogê po prostu zrezygnowaæ z... dzieciñstwa.}
{227} {} {Dzieciñstwa? Wiêc nie jesteœ st¹d?}

{228} {} {Tu-San by³o kiedyœ zamkniête dla obcych. Ale kiedy liczba ludnoœci zmala³a, Kolektyw musia³ odbudowaæ populacjê za pomoc¹ dzieci z innych osad. Zosta³em przyjêty i reedukowany w wieku piêciu lat. Od tamtej pory nie widzia³em swojej rodziny.}
{229} {} {Du¿o podró¿ujê i mogê poszukaæ sladów twoich krewnych.}

{230} {} {Naprawdê mo¿esz to zrobiæ? Dobrze... Ale w moich aktach jest napisane, ¿e krewni zginêli podczas wojny w Casa Grande. Porozmawiaj z mieszkañcami. Chcê tylko wiedzieæ, co siê sta³o w dniu, w którym zostaliœmy rozdzieleni.}
{231} {} {Dlaczego nie zapytaæ bezpoœrednio innych Blacharzy?}
{232} {} {Kolektyw nie toleruje tych, którzy zak³ócaj¹ porz¹dek. Odmowa zastosowania siê do opinii wiêkszoœci grozi surowymi karami. Takie sytuacje ju¿ mia³y miejsce. Nie chcê samemu sprawdzaæ cierpliwoœci Kolektywu.}
{233} {} {}
{234} {} {}
{235} {} {Byæ mo¿e mogê pomóc, ale podró¿ do innego miasta nie jest tania.}
{236} {} {Mogê zdobyæ czêœæ naszej technologii, jeœli jesteœ zainteresowany. Ale nie licz na du¿e zapasy, mam niski poziom dostêpu do magazynu.}
{237} {} {Ok, poszukam twoich rodziców.}
{238} {} {(uœmiecha siê) Swietnie! To znaczy... (i przestaje) By³bym wdziêczny... Teraz lepiej siê rozejdŸmy, zanim wzbudzimy podejrzenia. I nie mów nikomu o naszej rozmowie.}
{239} {} {Zaden problem.}
{240} {} {W³aœciwie, nigdzie nie jadê, tak mi przykro.}
{241} {} {Trudno... Ale jeœli znajdziesz siê w Casa Grande, pamiêtaj o mojej proœbie. Teraz lepiej pójdŸmy w³asnymi drogami. I jak coœ, ta rozmowa nie mia³a miejsca.}
{242} {} {Zaden problem.}

{250} {} {(zaskoczony) Ja? Có¿... mo¿emy porozmawiaæ na osobnoœci?}
{251} {} {Nie widzê w tym nic z³ego.}
{252} {} {No có¿, teraz potrzebujesz czegoœ, co?}
{253} {} {(rozgl¹da siê) Czy mo¿emy porozmawiaæ na osobnoœci?}

{260} {} {PrzyjdŸ do ³azienki za hotelem o 22:00.}
{261} {} {Zgoda.}
{1261} {} {Och, umówiæ siê z Blacharzem? Brzmi intryguj¹co. Przyjdê.}
{262} {} {Chyba nie chcê... umawiaæ siê na randkê.}

# Dialog z otwartym zadaniem
{300} {} {Czy masz dla mnie jakieœ informacje?}
{301} {} {Wrócê, gdy siê czegoœ dowiem.}

# Quest - rodzina zmar³a
{302} {} {Uda³o mi siê znaleŸæ twoj¹ rodzinê, ale okaza³o siê, ¿e nie ¿yj¹. Nie pytaj, Blacharze nie maj¹ z tym nic wspólnego.}
{303} {} {Tego nale¿a³o siê spodziewaæ... NajwyraŸniej Kolektyw mia³ racjê - nie mo¿esz trzymaæ siê przesz³oœci. Przecie¿ nie wiadomo nawet, czy po tylu latach roz³¹ki uda³oby nam siê dojœæ do porozumienia. Teraz, dziêki tobie, wreszcie mogê pozbyæ siê tej starej drzazgi. W przysz³oœci nie pozwolê, by uczucia zaw³adnê³y moim umys³em.}
{304} {} {Có¿, to zale¿y od ciebie.}

# Quest - GG za³o¿y³ rodzinê
{310} {} {Twoja rodzina nadal mieszka w Casa Grande.}
{311} {} {Czyli moja dawna rodzina nadal ¿yje? Niesamowite! Powiedz mi wszystko, co wiesz!}
{312} {} {Nie s¹dzê, ¿e spodoba ci siê ich historia. Wed³ug nich Blacharze po prostu zabrali ciê podczas nalotu.}
{313} {} {Wiêc moi bracia w metalu przez ca³y ten czas mnie oszukiwali?! Tego zawsze siê obawia³em... Wiesz, Master Hard nie bêdzie chcia³, ¿ebym zag³êbia³ siê w przesz³oœæ. Zw³aszcza po tym, czego siê dowiedzia³em...}
{314} {} {Moja czêœæ umowy zosta³a wykonana, w reszcie sam siê zorientuj.}
{315} {} {Nie, nie. Muszê uzyskaæ dowód Twoich s³ów, w przeciwnym razie umowa zostanie anulowana.}
{316} {} {Ok. Czego chcesz?}
{317} {} {Niech zgadnê. Chcesz wróciæ do swojej rodziny?}
{318} {} {Nie mogê d³u¿ej pozostaæ w Tu-San, dopóki ca³kowicie nie zrozumiem tej historii. Muszê siê spotkaæ i porozmawiaæ z moj¹ rodzin¹. Ale Master Hard nie pozwoli mi odejœæ dobrowolnie.}
{319} {} {Porozmawiam z Hardem, mo¿e pozwoli twojej rodzinie przyjechaæ do Tu-San.}
{320} {} {Nawet ja nie bêdê w stanie go przekonaæ. A Ty tym bardziej.}
{321} {} {Spróbujê. Czekaj na wiadomoœci.}

{322} {} {Musisz uciekaæ.}
{323} {} {Ok, pomogê ci uciec. Co mam zrobiæ?}
{324} {} {Mogê poprosiæ o pomoc karawanê, ale najpierw muszê pozbyæ siê chipa. Ka¿dy Blacharz ma taki chip wszyty pod skór¹ na szyi. Przesy³a moje dane o lokalizacji. Pomó¿ mi to usun¹æ! Sam tego nie zrobiê.}
{325} {} {Ok, spróbujmy...}

{326} {} {Wiêc co mam zrobiæ?}
{1326} {} {Wiêc co mam zrobiæ?}
{327} {} {Poczekaj trochê d³u¿ej.}
{328} {} {Ale wtedy czeka ciê surowa kara ze strony w³asnego ludu.}
{329} {} {By³em tu obcy od samego pocz¹tku... Wydaje mi siê, ¿e teraz przemawiaj¹ przeze mnie emocje, ale wola³bym poœwiêciæ moj¹ niepewn¹ pozycjê w Tu-San i wróciæ do rodziny.}

# Quest - Hard by³ przekonany
{330} {} {Hard zgodzi³ siê na spotkanie twojej rodziny w Tu-San. Nie musisz ju¿ walczyæ z Kolektywem.}
{331} {} {Jak sobie z tym poradzi³eœ?! Trudno dyskutowaæ z Master Hardem nawet nale¿¹c do jego w¹skiego krêgu powierników. A Ty nie jesteœ nawet jednym z Blacharzy. Niesamowite... To znaczy, jestem ci wdziêczny. Z twoj¹ pomoc¹ wreszcie bêdê móg³ uporaæ siê ze star¹ drzazg¹. To bardzo wa¿ne dla mnie.}
{332} {} {Có¿, myœlê, ¿e uda³o nam siê rozwiaz¹æ ten problem.}

{335} {} {Twój chip nie jest ju¿ problemem. Mo¿esz opuœciæ Tu-San.}
{336} {} {Swietnie. Z Master Hardem nie móg³bym siê dogadaæ. Ale z twoj¹ pomoc¹ w koñcu bêdê móg³ uporaæ siê ze star¹ drzazg¹.}
{337} {} {Có¿, mi³ej podró¿y.}

{340} {} {Myœlê, ¿e powinieneœ to wiedzieæ. Blacharze ciê nie zabrali si³¹, ale zabrali jako zap³atê za pomoc w naprawiê stacji wodnej.}
{341} {} {Zosta³em... sprzedany przez moich rodziców?! To wielka ró¿nica... Wiesz, panu Hard nie spodoba siê, jeœli bêdê dalej rozkopywaæ przesz³oœæ. Zw³aszcza po tym, czego siê dowiedzia³em. W ka¿dym razie dziêki Tobie mogê pozbyæ siê tej starej drzazgi.}
{342} {} {Dok³adnie. Czas zakoñczyæ tê historiê i przejœæ dalej.}
{343} {} {To zale¿y od Ciebie.}

# Ostateczny dialog
{400} {} {Dziêki za pomoc.}
{401} {} {Proszê.}

{410} {} {Obieca³eœ, ¿e przyniesiesz coœ dla mnie.}
{411} {} {Wiem. Czego potrzebujesz?}
{412} {} {Daj mi czas na przemyœlenie.}
{413} {} {Proszê bardzo. Ale od teraz nasza umowa jest uwa¿ana za zakoñczon¹.}
{414} {} {Przepraszam, ale umowa to umowa. Szczêœcia.}

{420} {} {Chcia³bym dostaæ kapsle.}
{421} {} {Potrzebujê baterii j¹drowych.}
{422} {} {Pneumatyczna Piêœæ, z której s³yn¹ Blacharze.}
{423} {} {Jeden z twoich pneumatycznych odpowiedników.}
{424} {} {Czy mo¿esz za³atwiæ noktowizor?}
{425} {} {Pistolet laserowy to najlepszy prezent.}
{426} {} {Naprawdê potrzebujê materia³ów wybuchowych.}

{430} {} {Czy mogê dostaæ ogniwo zasilaj¹ce do generatora?}
{431} {} {O nie, te ogniwa to najcenniejsza rzecz, jak¹ tworzymy. Ich produkcja i utylizacja planowane s¹ ju¿ na nadchodz¹cy rok.}
{432} {} {Rozumiem.}
