{100} {} {Widzisz lekarza.}
{101} {} {Widzisz Doktora Jonesa. Wygl¹da bardziej jak mechanik ni¿ lekarz.}
{102} {} {Operacja siê powiod³a.}

# Plywajace repliki (nie usuwaj pustych wierszy)
{110} {} {Naprawianie ludzi jest trudniejsze ni¿ naprawianie sprzêtu.}
{111} {} {No ja pierdolê, powinno wyjœæ inaczej.}
{112} {} {Liczba kontuzji ostatnio wzros³a.}
{113} {} {Utracê jeszcze kilku pacjentów - i zdecydowanie wyœl¹ mnie na przegl¹d techniczny.}
{114} {} {}
{115} {} {}
{116} {} {}
{117} {} {}
{118} {} {}
{119} {} {}

# Pierwszy dialog
{200} {} {Ach, œwie¿e miêso. Usi¹dŸ tam. (bezceremonialnie wskazuje na brudny stó³ operacyjny) Co mam naprawiæ?}
{201} {} {Nie jestem ze z³omu, ¿eby mnie * naprawiæ *.}
{202} {} {Ok, rozumiem. Wiêc jesteœ wykonany ze szczególnie delikatnego stopu? W takim razie proponujê amputacjê - najskuteczniejszy sposób.}
{203} {} {Hej, nie jestem taki!}
{204} {} {Naprawdê? (dopasowuje dziwne okulary ze œwiec¹cymi soczewkami i szuka czegoœ pod Twoj¹ klatk¹ piersiow¹)}
{205} {} {Uch, doktorze... mo¿emy najpierw porozmawiaæ?}
{206} {} {Czekaj, doktorze, wrócê wkrótce...}
{207} {} {Ale opaski uciskowe siê skoñczy³y, wiêc bêdziesz musia³ cierpieæ.}

{210} {} {Co, wracasz do mnie?}
{211} {} {Niew³aœciwe drzwi, doktorze.}
{212} {} {Przestañ mówiæ.}
{213} {} {Kolejne pytanie.}

#Leczenie
{220} {} {Potrzebujê leczenia.}
{221} {} {Muszê ciê rozczarowaæ - leczê tylko moich towarzyszy i tych, których poleca mi nasz przywódca.}
{222} {} {To niedobrze.}
{223} {} {Masz kapsle? Poka¿ mi, co siê zepsu³o.}
{224} {} {Nic.}
{225} {} {Po prostu wylecz moje rany, doktorze.}
{226} {} {}
{227} {} {Koszt leczenia wyniesie }
{228} {} { kapsli.}
{229} {} {Ok, doktorze, oto kapsle.}
{230} {} {Wiesz doktorze, bêdzie lepiej, jeœli to prze¿yjê.}
{231} {} {To bêdzie musia³o poczekaæ. Teraz wa¿niejsze jest, ¿ebym siê czegoœ nauczy³.}
{232} {} {Wszystko w porz¹dku.}
{233} {} {Dziêki doktorze.}
{234} {} {Nastêpnym razem znajdê inn¹ klinikê. Zegnam.}
{235} {} { kapsli.}

{250} {} {Czy mo¿esz mi wszczepiæ jeden z tych swoich implantów?}
{251} {} {(marszcz¹c brwi) Master Hard zgodzi³ siê na pomoc lekarsk¹ dla ciebie. Ale wydawanie najcenniejszych implantów na pustynnego dzikusa jest bez sensu.}
{252} {} {Czy s¹ dla Ciebie a¿ takie wa¿ne?}
{253} {} {Nie ka¿dy Blacharz mo¿e mieæ zainstalowany nowy implant. Wymaga to dobrego powodu i mo¿liwoœci organizmu. Niektórzy czekaj¹ na swoj¹ kolej kilka lat.}
{254} {} {Master Hard myœli, ¿e jestem godny. Myœlê, ¿e nie bêdzie mia³ nic przeciwko jednej operacji.}
{255} {} {Mo¿e tak. Wybierz rodzaj implantu. Jego koszt to }
{256} {} {Nie teraz. Muszê siê przygotowaæ do takiej operacji.}
{257} {} {O nie, ten implant jest dla ciebie przeciwwskazany.}
{258} {} {Przepraszam. Mo¿e spróbuj innego?}
{259} {} {Mo¿e od³ó¿my operacjê na jakiœ czas.}
{260} {} {[Si³a +1]}
{261} {} {[Percepcja +1]}
{262} {} {[Wytrzyma³oœæ +1]}
{263} {} {[Charyzma +1]}
{264} {} {[Inteligencja +1]}
{265} {} {[Zrêcznoœæ +1]}
{266} {} {[Szczêœcie +1]}
{267} {} {Swietnie. }
{268} {} { kapsli i mo¿emy zacz¹æ. Po operacji adaptacja zajmie równie¿ dwa dni.}
{269} {} {Oto kapsle. Zaczynaj, doktorze.}

#Pytania
{300} {} {Dlaczego tu jest tak brudno?}
{301} {} {(rozgl¹da siê ze zdziwieniem) Naprawdê?}
{302} {} {Doktorze, bojê siê zapytaæ, ale... ilu z twoich pacjentów prze¿y³o operacje?}
{303} {} {Czekaj, w³¹czê analizator statystyk... Rozumiem. 58 procent.}
{304} {} {To jest... nieco ponad po³owa.}
{305} {} {To nie jest miejsce na lekkie zadrapania. Wiêkszoœæ pacjentów ma powa¿ne obra¿enia. Na drugim miejscu jest pora¿enie pr¹dem. A potem - promieniowanie, problemy z oddychaniem, pogorszenie wzroku, biegunka...}
{306} {} {Uch, rozumiem, doktorze. Nie kontynuuj...}

{310} {} {Opowiedz mi o klinice.}
{311} {} {To jest szpital, a nie bar.}
{312} {} {Jak zosta³eœ lekarzem?}
{313} {} {Mój poprzednik próbowa³ wszepiæ sobie neuroimplant, ¿eby poprawiæ swoje umiejêtnoœci medyczne. Coœ posz³o nie tak i zmar³ na krwotok mózgu. Moi bracia potrzebowali nowego lekarza, wiêc wys³ano mnie na studia z Wyznawcami Apokalipsy. Od tego czasu s³u¿ê tutaj.}
{314} {} {Sk¹d masz lekarstwa?}
{315} {} {Te stare przedwojenne leki przywo¿¹ g³ównie karawany z Phoenix. A nowe pochodz¹ z ma³ego laboratorium w Casa Nueva. Maj¹ tam w³asn¹ produkcjê.}
{316} {} {Kim s¹ ci Wyznawcy Apokalipsy?}
{317} {} {Nazwa³bym ich fanatykami maj¹cymi obsesjê na punkcie wiedzy Starego Swiata. Jednak wiedza bez technologii jest bezu¿yteczna.}

{320} {} {Dlaczego Blacharze wszczepiaj¹ sobie elektronikê?}
{321} {} {Cia³o ludzkie jest kruche i wra¿liwe. Zamieniaj¹c jego czêœci na elektronikê, staramy siê chroniæ siebie, staæ siê silniejszymi, m¹drzejszymi i bardziej odpornymi. Marzeniem ka¿dego Blacharza jest osi¹gniêcie pe³nej cybernacji i cyfryzacji osobowoœci. Ale na chwilê obecn¹ jest to niestety nieosi¹galny idea³.}

{330} {} {Co siê sta³o z tym pacjentem?}
{331} {} {Jest powa¿nie ranny. Aby go uratowaæ, próbowa³em za³o¿yæ mu parê implantów i protezy. Ale delikatne ludzkie cia³o odrzuca technologie. Nie mo¿e przetrwaæ bez implantów, a z nimi te¿ umrze. Ironia losu.}
{332} {} {Czy mo¿na go wyleczyæ?}
{333} {} {W sensie naprawiæ go? Obawiam siê, ¿e siê nie da. Bêdzie musia³ zostaæ „zdemontowany”.}
{334} {} {Czy mogê spróbowaæ mu pomóc?}
{335} {} {Jeœli nasza nowoczesna medycyna nie mo¿e go wyleczyæ, twoje dzikie rytua³y niewiele tu pomog¹. Ale nie mam nic przeciwko interwencji w tak beznadziejnej sytuacji.}
{336} {} {Zobaczmy, co mog¹ moje "rytua³y", doktorze.}
{337} {} {Porozmawiajmy o czymœ mniej pesymistycznym.}