{100} {} {Widzisz karczmarza.}
{101} {} {Widzisz w³aœciciela zajazdu. Leniwie drapie siê po brzuchu, siedz¹c ciê¿ko na fotelu starego pilota.}
{102} {} {Szybko zamknij drzwi! Te roboty s¹ wszêdzie!}

# Pierwszy dialog
{200} {} {(niechêtnie odwraca siê w twoj¹ stronê) Wszystkie pokoje s¹ zajête.}
{201} {} {Ale po³owa kluczy wisi nad blatem...}
{202} {} {S¹ zarezerwowane. Te numery nie s¹ na sprzeda¿. Jeœli chcesz spêdziæ gdzieœ noc, radzê zapukaæ do innych drzwi.}
{203} {} {Nie s¹dzê, ¿eby mnie tam powitali.}
{204} {} {To nie moja sprawa.}
{205} {} {Uch, dobrze...}

{210} {} {Mówi³em, ¿e wszystkie pokoje s¹ zajête.}
{211} {} {Myœlê, ¿e po prostu unikasz obcych.}
{212} {} {Pamiêtam.}

{213} {} {Myœlê, ¿e niektórzy ludzie robi¹ za du¿o wszystkiego.}
{214} {} {Grm...}

{215} {} {(nachyla siê do ciebie) Blacharze obawiaj¹ siê szpiegostwa i nie chc¹ rozg³osu dla swoich planów, wiêc muszê uwa¿aæ na obcych.}
{216} {} {Dobrze, ¿e jesteœ tu na stra¿y.}
{217} {} {Jako wyznawca ognia czujê siê ura¿ony twoimi us³ugami!}
{218} {} {Myœlê, ¿e Bractwo Stali nie zaakceptuje takiego stosunku od swoich podw³adnych.}
{219} {} {No dalej, sk¹d tyle nieufnoœci?}
{220} {} {Nie ma Ciê w swoim mieœcie.}
{221} {} {Oczywiœcie...}

# Powtarzajacy siê dialog
{250} {} {Co mogê dla ciebie zrobiæ?}
{251} {} {Dziêki, jakoœ sobie poradzê.}
{252} {} {Do widzenia.}

{260} {} {Powiedz mi, co siê tutaj dzieje?}
{261} {} {Blacharze próbuj¹ otworzyæ cmentarz sprzêtu wojskowego. Narazie brak postepów, ale to tylko kwestia czasu.}
{262} {} {Blacharze otworzyli cmentarz sprzêtu wojskowego. Wygl¹da na to, ¿e czeka nas du¿o pracy.}
{263} {} {Czy wiesz coœ o niewolnikach z Villi?}
{264} {} {Nie. Nie wiem. Zapytaj w hangarze, przetrzymywani s¹ tam niewolnicy.}
{265} {} {Jak sobie radzisz w tym miejscu?}
{266} {} {Przyjecha³em tu kilka lat temu, kiedy Blacharze otworzyli szlak handlowy z Phoenix. Potrzebowali hotelu do pracy z karawanami i zorganizowa³em go dla nich. Gdyby nie Blacharze, nie do¿y³bym do mojego wieku. Z pewnoœci¹ le¿a³bym teraz gdzieœ na pustkowiu, grzej¹c swoje koœci w s³oñcu.}