{100} {} {Widzisz Blacharza.}
{101} {} {Widzisz jednego z Blacharzy.}

{200} {} {(Po d³ugiej podró¿y opuszczon¹ autostrad¹ zostajesz zabrany do osady Blacharzy. Stajesz w szeregu z reszt¹ niewolników, wyczerpany czekaniem w pal¹cym s³oñcu)}
{201} {} {[Dalej.]}
{202} {} {(Jeden z Blacharzy bada ciê i sprawdza dane na tablecie) Ty. Te¿ z Villi? Wys³aæ do instruktora, niech odeœle go po swoich krewnych... A teraz nastêpny...}
{203} {} {[Dalej.]}

{210} {} {Jestem zajêty.}
{211} {} {Cokolwiek powiesz.}
