{100} {} {Widzisz instruktora.}
{101} {} {Widzisz jednego z Blacharzy odpowiedzialnego za szkolenie niewolników.}

{200} {} {(zwraca siê do ca³ej grupy) Pos³uchajcie mnie, zardzewia³e ko³a zêbate! Zostaliœcie przywiezieni do tego miasta, aby wasze nieistotne istnienie nabra³o przynajmniej jakiegoœ znaczenia!}
{201} {} {[Dalej.]}
{202} {} {Macie wielki zaszczyt uczestniczyæ w wydobywaniu staro¿ytnej technologii z Zakazanej Strefy. To miejsce zachowuje technologie z czasów przedwojennych. Ale jest problem - niezawodny system bezpieczeñstwa nie pozwala nam wejœæ i wyjœæ poza granicê. Musicie dostaæ siê do centrum kontroli i wy³¹czyæ ochronê. Dajemy pe³n¹ wolnoœæ tym, którzy to zrobi¹.}
{203} {} {[Dalej.]}
{204} {} {Jakieœ pytania?}
{205} {} {Tak.}
{206} {} {Nie ma mowy.}
{207} {} {Wiêc bierzcie swoje szmaty i biegnijcie na plac apelowy! Ka¿dy, kto ucieknie z Zakazanej Strefy przed koñcem misji, zostanie trwale zdemontowany.}
{208} {} {Wygl¹da na to, ¿e to bêdzie ciê¿ka próba...}
{209} {} {Zadnych wiêcej pytañ.}

{210} {} {Myœlisz, ¿e mo¿esz zrobiæ wszystko? Mów szybciej, szmato!}
{211} {} {Czy mogê dostaæ swoje rzeczy, jeœli ukoñczê misjê?}
{212} {} {Odbierzesz je w pude³ku od kwatermistrza. Ale nie miej nadziei, ¿e ci siê uda.}
{213} {} {Czy mój ojciec, ma na imiê Andres, równie¿ jest w Zakazanej Strefie?}
{214} {} {Nie mam pojêcia, o kim mówisz. W Strefie zniknê³o ju¿ tyle ludzkich œmieci, ¿e nie widzê powodu, by zapamiêtywaæ przynajmniej jednego z nich.}
{215} {} {Czego mo¿emy siê spodziewaæ w Zakazanej Strefie?}
{216} {} {Wrogich robotów, pu³apek elektromagnetycznych i zwiêkszonego promieniowania. Obwód jest odgrodzony barier¹ si³ow¹, wiêc nie mo¿ecie siê wydostaæ bez walki.}
{217} {} {Czy dadz¹ nam jak¹œ broñ?}
{218} {} {U¿yj tego, co znajdziesz w Witrynie.}
{219} {} {Daj mi kastety.}
{220} {} {Daj mi prymitywny pistolet.}
{221} {} {Daj mi przynajmniej œrodek pobudzaj¹cy.}
{222} {} {Daj mi trochê granatów przeciw robotom.}
{223} {} {Mam doœæ twojego marudzenia, szmato! Nie dostaniesz ¿adnej broni.}
{224} {} {Mam doœæ twojego marudzenia, szmato! WeŸ to i zamknij siê.}
{225} {} {Kolejne pytanie.}

{230} {} {Masz wyniki? Zg³oœ siê osobiœcie do naszego lidera.}
{231} {} {Ok.}
{232} {} {Co? Najemnik ochotnikiem do Zakazanej Strefy?}
{233} {} {Tak, ja te¿ wezmê udzia³.}
{234} {} {Nie, tylko przechodzê obok.}
{235} {} {Zadawaj swoje g³upie pytania, ochotniku.}
{236} {} {Porozmawiaj z naszym szefem, mam do czynienia tylko z niewolnikami.}
{237} {} {Ok.}
{238} {} {Wielki ZAX pokonany! Teraz bêdziemy mieæ naprawdê du¿o pracy. Czas wiêc poszukaæ nowych niewolników.}
{239} {} {Mam nadziejê, ¿e tym razem poradzicie sobie beze mnie... Uh, pa.}
