{100}{}{Widzisz swojego ojca.}
{101}{}{Widzisz Andresa, swojego ojca.}
{102}{}{Twój ojciec nie ¿yje.}
{103}{}{Otrzymujesz }
{104}{}{ doœwiadczenia za uwolnienie cz³onków rodziny.}
{105}{}{To za moje nie³atwe dzieciñstwo, ojcze.}
{106}{}{Zegnaj. Nie potrzebujê ju¿ wskazówek mojego ojca.}

#Pierwszy dialog
{200}{}{?!}
{201}{}{Witaj ojcze.}
{202}{}{Jak nas znalaz³eœ?}
{203}{}{Có¿, musia³em przejœæ przez pustyniê...}
{204}{}{Nie rozumiesz sytuacji, w której siê znajdujemy?! Twoje miejsce nie powinno byæ tutaj, ale w domu!}
{205}{}{Villa jest stopniowo odnawiana. Uda³o mi siê uratowaæ tych, którzy byli w Flagpool w niewoli.}
{206}{}{Rozumiem... Teraz widzê, ¿e myli³em siê, myœl¹c, ¿e jesteœ dzieckiem. Wygl¹da na to, ¿e ca³a ta historia zapewni³a ci wiele ¿yciowego doœwiadczenia. W takim razie cieszê siê, ¿e tu jesteœ.}
{207}{}{Pomyœla³em, ¿e m¹drzej by³oby uratowaæ przywódcê Villi, a potem pozosta³ych.}
{208}{}{Uwa¿asz, ¿e to ma sens?! Villa mo¿e ¿yæ beze mnie. A komu potrzebny jest przywódca w opuszczonej osadzie?! Powinieneœ by³ udaæ siê do Flagpool, gdzie przetrzymywani s¹ nasi ludzie. Twoja Madre te¿ tam jest.}
{209}{}{Ok. Zajmê siê tym póŸniej. Masz pomys³, jak siê st¹d wydostaæ?}
{210}{}{Zrobilibyœmy to dawno temu, gdyby nie ta przeklêt¹ bariera. Nie da siê przez ni¹ przejœæ. Jedynym wyjœciem jest zakradniêcie siê do bunkra centrum kontroli i wy³¹czenie tego, co tam jest.}
{211}{}{Wiêc mo¿e to zróbmy?}
{212}{}{Latwo powiedzieæ. Na tym obszarze roi siê od robotów i pu³apek. A co jest w bunkrze, nikt w ogóle nie wie. Najpierw przeprowadŸ rekonesans, znajdŸ sprzêt i innych ludzi. Próbowaliœmy równie¿ stworzyæ broñ przeciwko robotom. Ale nasz technik zgin¹³ podczas szukania odpowiednich czêœci, a ja tego nie rozumiem.}
{213}{}{Nie ma problemu, ojcze. Znajdê drogê.}
{214}{}{Gdybym tylko móg³ ci podziêkowaæ. Musimy siê st¹d wydostaæ.}
{215}{}{Rozwi¹¿ê to bez twojego przewodnictwa. Usi¹dŸ i poczekaj na moje instrukcje.}
{216}{}{Pa-adre-e, tak d³ugo ciê szukam!}
{1216}{}{Pa-adre-e, tak d³ugo ciê szukam!}

#Powtarzany dialog
{220}{}{Mów, }
{221}{}{.}
{222}{}{Zaraz wracam.}

{230}{}{Omówmy plan raz jeszcze.}
{231}{}{Nasz plan to omin¹æ roboty, zinfiltrowaæ bunkier i cokolwiek to jest, przej¹æ nad tym kontrolê. A potem wynosimy siê z tego przeklêtego miejsca z powrotem do Villi.}
{232}{}{Rozumiem.}

{233}{}{Gdzie mogê zdobyæ broñ?}
{234}{}{Zginê³o tu wielu niewolników i najemników. Poszukaj cia³, mo¿e jedno z nich ma jeszcze broñ. Widzia³em te¿ coœ, co wygl¹da³o jak broñ w pobli¿u du¿ego samolotu. Ale nie wiem, jak tego u¿yæ.}
{235}{}{Czy s¹ tu inni niewolnicy?}
{236}{}{Niedaleko bunkra znajduje siê obóz ocala³ych. Ale nie chcia³ z nami wspó³pracowaæ. Wygl¹da na to, ¿e coœ jest z nimi nie tak. I wygl¹daj¹ raczej... chorowicie.}
{237}{}{Jak mogê omin¹æ roboty?}
{238}{}{Te stworzenia s¹ m¹drzejsze od kretoszczurów. Chowaj¹ siê w ciemnych zakamarkach lub w piasku, w których ich nie widaæ od razu. Ale s³ychaæ je z odleg³oœci dziesiêciu metrów. Wydaj¹ siê te¿ reagowaæ na ruch. Jeœli poruszasz siê powoli lub stoisz z ty³u, mog¹ ciê nie wykryæ.}
{239}{}{}

{240}{}{Co to za miejsce?}
{241}{}{Z tego co wiem to cmentarzysko dawno zapomnianej technologii. Blacharze chc¹ je o¿ywiæ. Nie chcia³bym, ¿eby tak siê sta³o. Ci g³upcy nie rozumiej¹ niebezpieczeñstw staro¿ytnej technologii!}
{242}{}{Sk¹d wiesz, ¿e te technologie s¹ niebezpieczne?}
{243}{}{Przodkowie nauczyli nas baæ siê starej technologii. Mówili, ¿e jest niewiarygodna i niebezpieczna. I jest. Czy natkn¹³eœ siê ju¿ na rzeczy, które mog¹ eksplodowaæ w Twoich rêkach lub zaszkodziæ zdrowiu niewidzialnym promieniowaniem? S³ysza³em historie o wymieraniu ca³ych populacji z powodu nadmiernego polegania na technologii. A w niew³aœciwych rêkach stare rzeczy staj¹ siê broni¹.}
{244}{}{Znajome historie...}
{245}{}{Pamiêtaj Flagpool. Pamiêtaj, jak ³atwo banda g³upich bandytów zniewolila ca³¹ osadê tylko dziêki swojej broni i obro¿om elektrycznym. Ca³y ten sprzêt musi zostaæ zniszczony! Wszystko bez wyj¹tku!}
{246}{}{Warto to przemyœleæ...}
{247}{}{A co z twoj¹ broni¹? Przyda³aby mi siê.}
{248}{}{Chcesz pozostawiæ staruszka bezbronnego? (gorzki chichot) Ok, jedyn¹ nadziej¹, jaka nam pozosta³a, jesteœ ty.}
{249}{}{Dziêki za broñ, ojcze.}

{250}{}{Opowiedz mi o nalocie na Villê.}
{251}{}{Zostawmy tê rozmowê, dopóki nie wrócimy do domu. Krótko mówi¹c, najeŸdŸcy zaatakowali nas pod koniec dnia pracy, kiedy nasi ludzie wracali z plantacji i byli zmêczeni. Uda³o mi siê utrzymaæ liniê w ratuszu, ale w koñcu wszyscy zostaliœmy z³apani, zwi¹zani i zabrani do miasta Flagpool. Wiêkszoœæ zosta³a do pracy w miejscowej kopalni, a tylko najlepsi zostali wys³ani tutaj.}
{252}{}{Czy by³eœ w Phoenix?}
{253}{}{Tak, zabrano nas do koœcio³a prowadzonego przez kult. Ludzie tam s¹ obrzydliwi, pozbawieni wspó³czucia i dewauluj¹cy ludzkie ¿ycie. Badali nas szczegó³owo, jak jakieœ szczury - pobierali krew do analizy, torturowali nas i pytali o Villê. Niestety koœció³ jest teraz dobrze œwiadomy istnienia naszego domu.}
{254}{}{Wiecej pytañ.}
{255}{}{Dlaczego zosta³eœ wys³any do Tu-San?}
{256}{}{Bêd¹c liderem Villi, wiele siê nauczy³em. Dlatego ze wszystkich naszych mieszkañców zosta³em uznany za najlepszego kandydata do tej pracy.}

#Wtajemniczenie na impreze
{260}{}{ChodŸmy razem. Potrzebujê twojego doœwiadczenia.}
{261}{}{Pomogê ci dostaæ siê do bunkra. Ale bêdziesz musia³ zejœæ sam na dó³.}
{262}{}{Rozumiem.}
{263}{}{Dlaczego?}
{264}{}{W ten sposób bêdziesz mia³ wiêksz¹ szansê na pozostanie niewykrytym. Poza tym wsród tych wszystkich technologii bêdê nieprzydatny. Twoja podró¿ przez Sonorê da³a ci znacznie wiêcej wiedzy i doœwiadczenia w tej kwestii.}
{1264}{}{W ten sposób bêdziesz mia³a wiêksz¹ szansê pozostaæ w ukryciu. Poza tym wsród tych wszystkich technologii bêdê nieprzydatny. Twoja podró¿ przez Sonorê da³a ci znacznie wiêcej wiedzy i doœwiadczenia w tej kwestii.}
{265}{}{Hmm. Zobaczmy, co mogê zrobiæ.}
{266}{}{Pójdê sam.}
{1266}{}{Pójdê sama.}
{267}{}{Bêdê pilnowaæ wejœcia do bunkra. Powodzenia.}
{268}{}{[IdŸ]}

#Ukonczenie zadania ratunkowego
{300}{}{Hard zwróci³ ci wolnoœæ. Mo¿esz odejœæ.}
{301}{}{To dobrze. Ale *jak* mamy siê st¹d wydostaæ?}
{302}{}{Hmm. Niech pomyœlê.}
{303}{}{Bariera wy³¹czona, mo¿emy teraz uciec z Tu-San.}
{304}{}{Dobra robota, }
{305}{}{. Niestety, to tylko œrodek tymczasowy. Teraz Blacharze bêd¹ mieli dostêp do starej technologii, Bóg jeden wie, ile teraz sprawi¹ wszystkim k³opotów. Przynajmniej mamy czas na przygotowanie.}
{306}{}{[Dalej]}
{307}{}{Dobra robota, }
{308}{}{. Nie tylko uzyskaliœmy dostêp do wolnoœci, ale tak¿e pozbawiliœmy Blacharzy tych starych technologii. Tylko Bóg jeden wie, ile k³opotów spowodowaliby na pustkowiu, ujarzmiaj¹c te technologie w bunkrze.}
{309}{}{Odpocznê jeszcze trochê i pójdê do domu. Spotkajmy siê w Villi.}
{310}{}{Pa, ojcze.}
{311}{}{W miêdzyczasie znajdŸ Carlosa i spróbuj z nim porozmawiaæ. Blacharze namieszali mu we ³bie, wype³niaj¹c mu g³owê nonsensem. W razie niepowodzenia... Trzeba go wyeliminowaæ. Rozumiesz? Mo¿e proszê o zbyt wiele, ale wyobraŸ sobie, jakie niebezpieczeñstwo stanowi on teraz dla ca³ej Villi.}
{312}{}{Rozumiem, ojcze. Zaufaj mi.}
{313}{}{Zabiæ swojego krewnego? Na pewno tego nie zrobiê. Ale warto z nim porozmawiaæ.}