{100} {} {Widzisz administratora.}
{101} {} {Widzisz mê¿czyznê w œrednim wieku. Ze sposobu, w jaki mówi i siê porusza, dostrzegasz, ¿e ma obsesjê na punkcie ³adu i porz¹dku.}

#Dialog
{200} {} {WejdŸ wêdrowcze. Mam tu porz¹dek i ksiêgowoœæ, wiêc nie ruszaj niczego.}
{1200} {} {WejdŸ wêdrowcze. Mam tu porz¹dek i ksiêgowoœæ, wiêc nie ruszaj niczego.}
{201} {} {Do widzenia.}
{202} {} {Wracasz do mnie? Wspaniale. Jak mogê pomóc?}
{203} {} {Muszê wys³aæ paczkê do Phoenix.}
{204} {} {Muszê wys³aæ paczkê do Flagpool.}
{205} {} {Muszê wys³aæ paczkê do Puerto.}

# Wysy³anie paczki
{210} {} {Po to tu jestem. Cena przesy³ki wyniesie }
{211} {} { kapsli. Nie wiêcej, nie mniej. Umieœæ rzeczy w tej szufladzie pod œcian¹. Po dokonaniu p³atnoœci zabierzemy je do miejsca docelowego.}
{212} {} {Oto kasa, paczka mo¿e zostaæ wys³ana.}
{213} {} {Nie teraz.}

{214} {} {Nie, nie, to nie wystarczy.}
{215} {} {Mo¿emy wiêc o czymœ porozmawiaæ?}
{216} {} {Wrócê, kiedy bêdê mia³ interes.}
{217} {} {Teraz dokonam inwentaryzacji i zarejestrujê dane. Jest to wymagane przez protokó³. Tutaj... Dziêkujemy za wybranie naszej firmy. Przesy³ka bêdzie czeka³a w wybranej osadzie w biurze Sonora Express.}
{218} {} {Swietnie.}

{220} {} {Jako cz³onek Bractwa Stali, czy mogê spodziewaæ siê specjalnych cen?}
{221} {} {Zdecydowanie tak. Mamy specjalne umowy z Bractwem.}
{222} {} {Swietnie. Po prostu œwietnie.}
{223} {} {Ach, to znowu ty... Ale muszê ci tylko powiedzieæ, ¿e zni¿ka na nasze us³ugi zosta³a anulowana. I nie oburzaj siê. To jest decyzja kierownictwa, nie mam z tym nic wspólnego.}
{224} {} {Co za szkoda...}

# Pierwszy dialog
{230} {} {Jak mogê pomóc?}
{231} {} {Wyjaœnij mi, co to za miejsce?}
{232} {} {Regionalne biuro firmy kurierskiej Sonora Express. Zajmujemy siê ró¿nymi rodzajami dostaw.}
{233} {} {A jak du¿a jest Wasza sieæ karawan?}
{234} {} {Mamy kilka placówek w ró¿nych osadach. Nasza g³ówna siedziba znajduje siê w Phoenix. Stamt¹d trasy rozchodz¹ siê do najbli¿szych osad.}
{235} {} {Rozumiem. Bêdê o tym pamietaæ na przysz³oœæ.}
