{101} {} {Widzisz ocala³ego zwiadowcê Bractwa Stali.}
{102} {} {Pewnego dnia Bractwo Stali powróci do Arizony. To tylko kwestia czasu.}

{200} {} {(nieznajomy patrzy ostro¿nie w twoj¹ twarz, przechodz¹c obok) Hmm, chyba gdzieœ ciê widzia³em.}
{201} {} {Mo¿e. Nie jesteœ miejscowy, prawda?}
{202} {} {Tak. Ty te¿ nie. Dwóch nieznajomych w niegoœcinnym mieœcie. Wygl¹da na to, ¿e œwiat jest ma³y.}
{203} {} {Zgadza siê. Ale mam tu interes. Nie masz nic przeciwko?}
{204} {} {Nie. Naprzód.}
{205} {} {Do widzenia.}
{206} {} {}
{207} {} {}
{208} {} {(kiwa g³ow¹ na powitanie)}
{1208} {} {Witam.}
{209} {} {[Witam, witam.]}
{1209} {} {Jesteœ taki mi³y.}

{210} {} {Ach, pamiêtam. To ciebie widzia³em na krótko przed wybuchem w Steel Port. Ciekawy zbieg okolicznoœci, prawda?}
{211} {} {Wybuch? Hej, nie mam z tym nic wspólnego.}
{212} {} {Czy ktoœ ciê wini?}
{213} {} {Nie, proszê pana. Nikt.}
{214} {} {Wiêc dlaczego siê tak denerwujesz? Nie martw siê, nadal nie wierzê, ¿e cz³owiek taki jak ty móg³by przejœæ przez wszystkie zabezpieczenia statku i odpaliæ torpedy. Nie wszyscy pracownicy bazy mieli do nich dostêp.}
{215} {} {Uff, dobrze. Wydawa³o mi siê ju¿, ¿e coœ podejrzewasz. Do widzenia, mi³ego dnia.}
{216} {} {A co jeœli powiem, ¿e eksplozja to moja wina?}
{217} {} {Ka¿dy mo¿e teraz tak mówiæ. Nigdy bym nie uwierzy³, ¿e jakiœ dzikus móg³ przedrzeæ siê przez dobrze strze¿on¹ ³adowniê i wystrzeliæ torpedy. Sk¹d niby mia³byœ takie umiejêtnoœci i wiedzê, wieœniaku?}
{1217} {} {Ka¿dy mo¿e teraz tak mówiæ. Nigdy bym nie uwierzy³, ¿e jakiœ dzikus móg³ przedrzeæ siê przez dobrze strze¿on¹ ³adowniê i wystrzeliæ torpedy. Sk¹d niby mia³abyœ takie umiejêtnoœci i wiedzê, wieœniaczko?}
{218} {} {Rzeczywiœcie brzmi nieprawdopodobnie. Tak jak w starych komiksach. Mam nadziejê, ¿e Twoje podejrzenia zosta³y rozwiane?}
{219} {} {Chyba. Ale pójdê za tob¹ k¹tem oka.}
{220} {} {To nie jest konieczne. Do widzenia.}
{221} {} {Powinieneœ byæ cicho po tych wszystkich wydarzeniach. Wasze Bractwo jest teraz czêœci¹ historii. PogódŸ siê z tym.}
{222} {} {To prawda. Jednak Puerto Penasco by³o tylko placówk¹ z dala od g³ównej bazy. Mo¿emy tu wróciæ.}
{223} {} {Ale to nie nast¹pi szybko. I do tego czasu nie bêdziecie tu mile widziani. Lepiej pomyœl o swoim losie, ¿o³nierzu.}
{224} {} {Wydawa³o siê, ¿e to najbezpieczniejszy i najm¹drzejszy pomys³, ¿eby siê tu udaæ. Okej, ju¿ mnie tu nie zobaczysz. Zegnaj nieznajomy.}
{1224} {} {Wydawa³o siê, ¿e to najbezpieczniejszy i najm¹drzejszy pomys³, ¿eby siê tu udaæ. Okej, ju¿ mnie tu nie zobaczysz. Zegnaj nieznajoma.}
{225} {} {Do widzenia, zwiadowco Bractwa Stali.}
{226} {} {Dalej, wynoœ siê st¹d.}
