{100}{}{Widzisz niewolnika.}
{101}{}{Widzisz jednego z lokalnych niewolników. Nadal wydaje siê nie rozumieæ, gdzie jest i co siê dzieje.}

{110}{}{Blacharze chc¹, abyœmy wy³¹czyli roboty. Ale jak do diab³a to zrobiæ?!}
{111}{}{Cholerni bandyci! Z³apali mnie i wrzucili do tego piek³a.}
{112}{}{Wiele ludzi tu zginê³o. I my prawdopodobnie nie bêdziemy ostatnimi.}
{113}{}{Wci¹¿ ¿yjemy dziêki Andresowi. Ale to nie potrwa d³ugo.}
