{100} {} {Widzisz niewolnika.}
{101} {} {Widzisz przymusowego robotnika. Jest wychudzony przez ci¹g³¹ pracê, ale wci¹¿ stoi.}

{102} {} {Szukasz znajomych? Wygl¹da na to, ¿e zostali ju¿ wys³ani do Zakazanej Strefy.}

{110} {} {Proszê, zabij mnie! Nie mogê ju¿ znieœæ tej udrêki...}
{111} {} {Nie wolno mi rozmawiaæ z obcymi.}
{112} {} {Jesteœmy tylko materia³em eksploatacyjnym dla Blacharzy.}
{113} {} {By³em kiedyœ w gangu, ale zosta³em schwytany i wys³any tutaj.}
{114} {} {Têskniê za swoim gangiem.}
{115} {} {Kiedy by³em w gangu, nigdy nie myœla³em o swoich ofiarach.}
{116} {} {Ci Blacharze maj¹ obsesjê na punkcie staro¿ytnej technologii.}
{117} {} {Ukryj swój komputer albo Blacharze zabior¹ go si³¹.}
{118} {} {Zakazana Strefa to pewna œmieræ.}
{119} {} {Masz coœ do jedzenia?}