{100}{}{Widzisz Gerardo.}
{101}{}{Widzisz jednego ze zniewolonych ch³opów z Villi.}

#Pierwszy dialog
{200}{}{?! Co ty tu robisz?! Myœla³em, ¿e najeŸdŸcy Ciê nie znaleŸli...}
{201}{}{Nie, Gerardo, nie znaleŸli. Dlatego jestem tutaj, aby ciê uratowaæ.}
{202}{}{Ach, amigo, wiesz, zawsze dodawa³eœ otuchy. Ale uwierz mi, st¹d nie ma wyjœcia. Ziemia tutaj jest przesi¹kniêta œmierci¹! Zginiemy, amigo, i nikt nas nawet nie pochowa.}
{203}{}{Gdzie jest mój ojciec?}
{204}{}{Powinien ju¿ byæ w starym hangarze na œrodku cmentarzyska. Zbieraj¹ siê tam wszyscy ocaleni. IdŸ na pó³noc, nie przegapisz.}
{205}{}{Dobrze. Do zobaczenia.}
{206}{}{A co z tob¹?}
{207}{}{Twój ojciec kaza³ mi tu siedzieæ i kierowaæ nowych ludzi do hangaru. Nie martw siê, wœród tych kontenerów jestem wzglêdnie bezpieczny.}
{208}{}{Rozumiem. Do zobaczenia Gerardo.}

{210}{}{Dziêki Bogu, ¿e wróci³eœ!}
{1210}{}{Dziêki Bogu, ¿e wróci³aœ!}
{211}{}{ChodŸ.}
{212}{}{Bariera zosta³a wy³¹czona i roboty nas nie rusz¹. Wracamy do Villi.}
{213}{}{I zrobi³eœ to wszystko sam? Zaprawdê, oto prawdziwy lider Villi! Chocia¿, coœ siê w tobie zmieni³o, amigo... Dobra, spotkajmy siê w domu! Oczywiœcie jeœli tam dotrzemy.}
{214}{}{ChodŸ.}
{215}{}{Co teraz?}

{220}{}{ChodŸ ze mn¹, potrzebujê pomocy w walce.}
{221}{}{Co ty, amigo! Prowadzisz mnie na œmieræ! Z nasz¹ broni¹ przeciwko robotom jesteœmy bezsilni. Lepiej usi¹dŸ wygodnie i poczekaj, a¿ ktoœ otworzy bramê.}
{222}{}{Nie poznaje ciê, Gerardo. Pamiêtasz, ¿e zawsze to Ty by³eœ t¹ ostr¹ papryk¹ w naszej wiosce?}
{223}{}{Ja... ¿yjê tylko dziêki twojemu ojcu. Villa i ten œwiat s¹ zupe³nie inne. Nie jestem na to gotowy. Przepraszam. Nawet jeœli wrócê do Villi, nie bêdê móg³ ¿yæ jak wczeœniej.}
{224}{}{Gerardo, to nie czas na za³amywanie siê. Wstawaj, Twoja rodzina Ciê potrzebuje!}
{225}{}{Ok, amigo... Ale nie wejdê do tego przeklêtego bunkra! ChodŸmy do wejœcia, ale potem radŸ sobie beze mnie.}
{226}{}{Có¿, niech bêdzie.}
{227}{}{Nie... tu jestem teraz potrzebny. Ojciec Andres na mnie liczy.}
{228}{}{Rozumiem.}
{229}{}{Powinniœmy siê rozdzieliæ. Zostañ tam, gdzie jesteœ, dopóki nie wrócê.}
{230}{}{Cokolwiek powiesz, amigo...}
{231}{}{Ok.}