{100} {} {Widzisz ocala³ego.}
{101} {} {Widzisz brudnego i wychudzonego mê¿czyznê. Jego dziki wygl¹d œwiadczy o nieszczególnie dobrych intencjach.}

# Pierwszy dialog
{200} {} {Hej, ty! PodejdŸ bli¿ej - nie jesteœ robotem, prawda? Wynoœ siê, zanim rozwalê ci mózg!}
{201} {} {Porozmawiajmy!}
{202} {} {S³yszê od zw³ok!}

{203} {} {Nie kupujê tych sztuczek! OdejdŸ!}
{204} {} {S³uchaj, nie mo¿emy przetrwaæ sami. Po³¹czmy si³y, dobrze?}
{205} {} {W takim razie bêdê musia³ ciê zabiæ, ¿eby zdobyæ broñ.}
{206} {} {Ok, s³uchaj, odchodzê, nie ma problemu.}
{207} {} {Sk¹d mam wiedzieæ, ¿e to nie jest jakiœ podstêp?}
{208} {} {Wydaje siê, ¿e nie ufasz ludziom. Ale teraz nie ma to znaczenia, potrzebujemy siebie nawzajem.}

{209} {} {Cholera, chcê siê st¹d wydostaæ! Zjednoczmy siê. Ale bêdê trzymaæ siê z daleka od Ciebie.}
{210} {} {Có¿, to ju¿ coœ.}
{211} {} {Przyjrzyj mi siê bli¿ej. Czy jeden ghul jest wrogiem innego ghula?}
{212} {} {Potrzebujemy siebie nawzajem. To oczywiste.}
{213} {} {Dobra, g³adki. Ale czujê siê dobrze samemu.}
{1213}{}{Dobra, g³adki. Ale czujê siê dobrze samemu.}

# Dialog po inicjacji
{220} {} {Czego chcesz?}
{221} {} {Nic.}

{230} {} {Opowiedz mi o sobie.}
{231} {} {Nic ci nie powiem.}
{232} {} {Uch, dobrze.}
{233} {} {Podaj mi przynajmniej swoje imiê.}
{234} {} {Nazywam siê Raoul.}
{235} {} {Sk¹d jesteœ?}
{236} {} {Z Inferno, to miasto ghuli na zachodzie. W swoim ¿yciu odwiedzi³em wiele miejsc w Meksyku i Kalifornii. S³ysza³eœ kiedyœ o Hermosillo? Urodzi³em siê tam.}
{237} {} {Miasto w Meksyku? Musisz mieæ bogat¹ przesz³oœæ.}
{238} {} {Sto lat podró¿y. I oto jestem, zagro¿ony œmierci¹ w piaskach. Nie spodziewa³em siê kolejnego zgonu.}
{239} {} {Sto lat? Jak mo¿esz tak d³ugo ¿yæ?}
{240} {} {Przyjrzyj mi siê bli¿ej. Sta³em siê taki po wybuchach nuklearnych. To nie s¹ oparzenia, to jest coœ innego. Ale to sprawia, ¿e ¿yjê d³u¿ej. Nie wiem, co by³oby lepsze: umrzeæ wtedy czy teraz.}
{241} {} {Wiêc jesteœ cz³owiekiem z czasów staro¿ytnych!}
{242} {} {Tak... Stary Swiat by³ inny. Ludzie ¿yli wœród technologii, a miasta zachwyca³y ich przepychem... Ale wiesz co? Tak naprawdê nic siê nie zmieni³o. Ludzie wci¹¿ walcz¹ o ¿a³osne resztki zasobów. A w przypadku starych technologii to tylko kwestia skali.}
{243} {} {Ciekawy punkt widzenia.}
{244} {} {Dlaczego Blacharze wys³ali tu... ghula?}
{245} {} {Poniewa¿ ¿yj¹c przez tyle lat, wiem o wiele wiêcej ni¿ jakakolwiek osoba o g³adkiej skórze. Dodaj do tego odpornoœæ na promieniowanie - jestem idealnym kandydatem do otwierania starych baz. Ale prawda jest taka, ¿e nie mam zielonego pojêcia, jak wy³¹czyæ system bezpieczeñstwa tego cmentarzyska!}
{246} {} {Rozumiem.}
{247} {} {Doœæ tych bezu¿ytecznych pytañ.}
{248} {} {Wiesz coœ o upiorach z Inferno?}
{249} {} {Widzisz, ja... nie pasowa³em do ich grupy. Nadal jestem na tyle œwiadom, ¿eby nie wpaœæ w sza³. Ale tamtych ghuli nie da siê naprawiæ.}

# Przesylka
{250} {} {ChodŸ ze mn¹.}
{251} {} {Tylko trzymaj siê z dala od gor¹ca. I pamiêtaj - nie wejdê do bunkra.}
{252} {} {Zobaczymy...}
{253} {} {Poczekaj tutaj, poszukam czegoœ.}
{254} {} {Nie próbuj mnie oszukiwaæ.}
{255} {} {Oczywiœcie...}

{260} {} {Opowiedz mi o tym miejscu.}
{261} {} {To stary cmentarz s³u¿¹cy do konserwacji sprzêtu wojskowego. Obwód jest otoczony zapor¹ energetyczn¹ i polami minowymi. Wszêdzie s¹ wrogie roboty i s¹ kontrolowane przez system komputerowy w opuszczonym podziemnym bunkrze.}
{262} {} {Czego mo¿na siê spodziewaæ w bunkrze?}
{263} {} {Najprawdopodobniej wiêcej robotów i jakiegoœ du¿ego komputera. W¹tpiê, czy s¹ tam jeszcze ludzie. Jeœli masz zamiar tam zejœæ, dobrze siê przygotuj.}