{100} {} {Widzisz Blacharza.}
{101} {} {Widzisz cz³owieka w brudnym kombinezonie. Jego ³ys¹ g³owê spowijaj¹ przewody i czujniki.}

{110} {} {Bêdziemy musieli to rozebraæ.}
{111} {} {Te czêœci mo¿na sprzedaæ plebsu w Phoenix.}
{112} {} {To wiadro powinno ju¿ dawno trafiæ na z³omowisko.}
{113} {} {Te œmieci s¹ bezu¿yteczne.}
{114} {} {Jestem pe³en wspó³czucia dla tej kupki z³omu.}
{115} {} {I te œmieci by³y kiedyœ arcydzie³em technologii...}
{116} {} {Nie mogê siê doczekaæ, a¿ zobaczê technologie z Zakazanej Strefy.}
{117} {} {Potrzebny jest mi nowy konwerter plazmy.}
{118} {} {Nadejdzie czas, kiedy samoloty znów pojawi¹ siê nad nami.}
{119} {} {Czy s³yszysz to b³ogie westchnienie mechanizmu t³oka?}

{120} {} {Co mówi¹ Stalowi Bogowie?}
{121} {} {Stalowi Bogowie obiecali nam nowe plany w zamian za ogniwa energetyczne.}
{122} {} {Te czêœci musz¹ byæ pilnie wys³ane do Steel Port.}
{123} {} {Stalowi Bogowie chc¹ wywy¿szyæ nasz lud.}
{124} {} {}
{125} {} {Nawet Bogowie staj¹ siê bezsilni w obliczu rozszczepienia atomu.}
{126} {} {Nigdy nie pozwolilibyœmy na to, co sta³o siê w Steel Port.}
{127} {} {Stalowi Bogowie nie byli tak sprytni, jak myœleliœmy.}
{128} {} {}
{129} {} {}

{130} {} {Kiedy nadejdzie nowa dostawa rudy uranu?}
{131} {} {Tworz¹c ogniwa energetyczne o¿ywiamy cywilizacje.}
{132} {} {Powinniœmy ograniczyæ dystrybucjê baterii.}
{133} {} {Ile mamy rudy uranu?}
{134} {} {}
{135} {} {Bêdziemy musieli oszczêdzaæ energiê, dopóki Flagpool ponownie nie uruchomi kopalni.}
{136} {} {Dopóki Flagpool nie odbuduje kopalni, nie bêdziemy w stanie produkowaæ ogniw energetycznych.}
{137} {} {Ludzie z karawany mówi¹, ¿e kopalnia Flagpool jest nieaktywna.}
{138} {} {Jak ma³o zosta³o rudy uranu?}
{139} {} {Bez kopalni Flagpool nie mo¿emy produkowaæ baterii.}

{140} {} {Czego chc¹ w Katedrze Ognia?}
{141} {} {Ci czciciele ognia w ogóle nie rozumiej¹ technologii.}
{142} {} {Im bardziej ambasador katedry siê tu zadomawia, tym trudniej jest mi pracowaæ.}
{143} {} {Powiedz ambasadorowi katedry, aby odebra³ swoje bezwartoœciowe zamówienia.}
{144} {} {Jeœli Katedra chce to zrobiæ, niech najpierw znajd¹ plany.}

{145} {} {Tak bardzo, jak wyœmiewaliœmy czcicieli ognia, potrzebowaliœmy ich.}
{146} {} {Bez Koœcio³a Ognia znacznie trudniej bêdzie uzyskaæ materia³ j¹drowy.}
{147} {} {Wartoœæ kapsli dramatycznie spad³a po wybuchu w katedrze.}
{148} {} {Potrzebujemy nowych partnerów. Katedra Ognia to ju¿ przesz³oœæ.}
{149} {} {Tak siê dzieje, gdy technologia wpada w niepowo³ane rêce.}
