{100} {} {Widzisz Blacharza.}
{101} {} {Widzisz jednego z Blacharzy. Starannie czyœci swój pistolet laserowy.}

{200} {} {(Patrzysz, jak Blacharz upiera siê przy czyszczeniu swojego pistoletu laserowego, ignoruj¹c ciê.)}
{201} {} {Od jak dawna to robisz?}
{202} {} {(Podnosi g³owê, ¿eby na ciebie spojrzeæ, jego spojrzenie wyra¿a ca³kowit¹ obojêtnoœæ). Technologia laserowa to moja specjalnoœæ. Robiê to przez ca³e ¿ycie.}
{203} {} {Wiêc niektórzy Blacharze s¹ bardziej wyspecjalizowani w sprawach ró¿nych technologii od innych?}
{204} {} {To najskuteczniejszy sposób na utrzymanie produktywnoœci.}
{205} {} {A jeœli jeden ze specjalistów odejdzie?}
{206} {} {Dla ka¿dego z nas jest duplikat. Jeœli zostanie zdemontowany, zawsze mo¿na go wymieniæ.}
{207} {} {Rozumiem.}
{208} {} {Có¿, nie bêdê ci przeszkadzaæ.}
{209} {} {Lepiej go nie rozpraszaæ...}

{210} {} {Czego chcesz, Cz³owieku z pustkowi?}
{211} {} {Czego chcesz?}
{212} {} {Na razie nic.}

{220} {} {Te¿ chcê poznaæ sztukê technologii laserowej.}
{221} {} {Nie dzielimy siê wiedz¹ i umiejêtnoœciami z pierwsz¹ spotkan¹ osob¹. Najpierw zdob¹dŸ nasze zaufanie.}
{222} {} {Daj mi czas na przemyœlenie.}
{223} {} {A co z wymian¹?}
{224} {} {Mo¿e. Potrzebujê czêœci elektronicznych, których w naszej okolicy jest tak ma³o. Przynieœ 5 jednostek, a wtedy zrobiê dla ciebie wyj¹tek.}
{225} {} {Nawet Master Hard powierza mi kilka spraw.}
{226} {} {To prawda. Ten zaszczyt przypada tylko nielicznym.}
{227} {} {Wiele osób w tym mieœcie mi ufa.}
{228} {} {Mo¿e. Ale „wielu” nie oznacza ca³ego Kolektywu. Mogê jednak zmieniæ zdanie za ma³y prezent - przywieŸ ze sob¹ kilka czêœci elektronicznych, to wystarczy na moj¹ lojalnoœæ.}
{229} {} {Oto 2 elementy czêœci elektronicznych.}
{230} {} {Oto 5 czêœci elektronicznych.}
{231} {} {Moglibyœmy wymieniæ nasze umiejêtnoœci.}
{232} {} {To jest... w porz¹dku.}
{233} {} {To jest... niedopuszczalne. Nie mo¿emy siê niczego nauczyæ od mieszkañców wioski.}

{240} {} {Bardzo dobrze. Teraz widzê, ¿e mogê robiæ z tob¹ interesy.}
{241} {} {A mo¿e ma³y kurs wprowadzaj¹cy?}
{242} {} {Znasz podstawy mechaniki kwantowej? Wiêc nie traæmy czasu...}
{243} {} {[Dalej.]}
{244} {} {Blacharz okaza³ siê wymagaj¹cym nauczycielem. Ale naprawdê wiele ciê nauczy³.}