{100} {} {Widzisz robo-oko.}
{101} {} {Widzisz robota.}
{102} {} {* Ciii *}
{103} {} {W odpowiedzi otrzymujesz tylko statyczny syk z g³oœnika.}

{110} {} {Myœlê, ¿e siê rozumiemy.}

{200} {} {(robo-oko otrzymuje wiadomoœæ od ZAX-a) Dziêkujê za pomoc. Jak widaæ, zlikwidowa³em ju¿ tê nielegaln¹ osadê. Ale tobie i twoim wspó³plemieñcom pozwolê odejœæ pod jednym warunkiem - nigdy nie wrócicie na te ziemie.}
{201} {} {Brzmi dobrze.}
{202} {} {Liczê na twoj¹ lojalnoœæ. Pozwól, ¿e dam ci nagrodê. Wed³ug moich informacji Blacharze podlegali wp³ywowej organizacji zwanej Bractwem Stali. To ta organizacja jest odpowiedzialna za rozwój niewolnictwa w Sonorze. Musisz znaleŸæ sposób, aby zlikwidowaæ g³ówn¹ bazê Bractwa Stali, aby zmniejszyæ dalsze zagro¿enie dla Villi.}
{203} {} {Masz na myœli, ¿e Bractwo Stali nie przestanie dzia³aæ nawet po pora¿ce w Tu-San? W takim razie gdzie mogê znaleŸæ tê bazê?}
{204} {} {Kieruj siê na zachód do starego portu w Zatoce Kalifornijskiej. Najbezpieczniejsza trasa prowadzi przez miasto Casa Nueva. Podobnie jak Ty jestem zainteresowany wyeliminowaniem tego zagro¿enia, ale nie liczê na dalsz¹ wspó³pracê. Moje mo¿liwoœci s¹ ograniczone do tego miejsca.}
{205} {} {Ok ZAX, dziêki za pomoc.}
{206} {} {Nie jestem twoim robotem, rozwi¹¿ê to bez twoich instrukcji.}
