{110} {} {To cia³o powinno zostaæ dok³adnie zbadane.}
{111} {} {Nie ma teraz sensu przeszkadzaæ zmar³ym.}
{112} {} {Nie mo¿na tego zrobiæ podczas walki.}

{200} {} {Ten cz³owiek zgin¹³ od rany postrza³owej podczas nalotu. Wygl¹da na to, ¿e by³ jednym z napastników, chocia¿ nie mo¿na tego stwierdziæ po jego wygl¹dzie.}
{201} {} {[Dalej.]}
{202} {} {W jego kieszeni znajdujesz pobie¿ny szkic uk³adu Starego Miasta, pokazuj¹cy bezpieczn¹ trasê. Mo¿na przypuszczaæ, ¿e w tym miejscu znajduje siê obóz bandytów.}
{203} {} {[IdŸ do Starego Miasta]}
{204} {} {[Zostaw zw³oki w spokoju]}
