{100} {} {Widzisz komputer Harda.}
{101} {} {Widzisz osobisty komputer Master Harda. Jest w doskona³ym stanie.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}

{210} {} {Raporty dostarczenia niewolników.}
{211} {} {(Blacharze uwielbiaj¹ liczby i ksiêgowoœæ. Szczegó³owe statystyki dotycz¹ce niewolników - ich pochodzenia, zatrudnienia, przyczyn œmierci. Po³owa niewolników zosta³a wys³ana do Zakazanej Strefy, ich los jest nieznany.)}
{212} {} {Informacje o niewolnikach pochodz¹cych z Villi.}
{213} {} {(Znajdujesz informacje o dwóch niewolnikach. Carlos pracuje w hangarze, a twój ojciec zosta³ wys³any do Zakazanej Strefy. Bêdziesz musia³ iœæ tam sam, ¿eby go znaleŸæ.)}
{214} {} {Informacje o niewolnikach z Phoenix.}
{215} {} {(G³ównym Ÿród³em niewolników dla Blacharzy jest Koœció³ Swiêtego Ognia w Phoenix. Wprowadzasz wspó³rzêdne do swojego Pip-Boya.)}
{216} {} {Raporty handlowe.}
{217} {} {(Blacharze aktywnie handluj¹ z kilkoma osadami, gdzie wymieniaj¹ przedmioty technologiczne i œwiadcz¹ us³ugi naprawcze. G³ówne kontrakty: Koœció³ Swiêtego Ognia w Phoenix (niewolnicy, odzie¿, jedzenie), kolonia Flagpool (niewolnicy, uran), Casa Nueva (jedzenie), Casa Grande (czysta woda).}
{218} {} {Instrukcje Sztabu Generalnego.}
{219} {} {(Przywódca Blacharzy otrzymuje bezpoœrednie instrukcje od Bractwa Stali w Puerto Penasco. Bractwo nie anga¿uje siê w wewnêtrzne sprawy lokalnych mieszkañców, ale reguluje czêœæ produkcji i politykê zagraniczn¹. W szczególnosci Bractwo zobowi¹zuje siê do spe³nienia wa¿nych ¿¹dañ Koœcio³a Swiêtego Ognia w Phoenix. Ostatni taki kontrakt dotyczy³ czêœci do bomby atomowej.)}

{220} {} {Akta Cody'ego.}
{221} {} {(Cody by³ jednym z dzieci, które Blacharze nabyli w zewnêtrznych osadach i zreedukowali na podstawie w³asnego prawa. Rodzice przekazali Cody'ego jako zap³atê za naprawê stacji wodnej w Casa Grande. Jednak na potrzeby lepszej asymilacji dziecka w ramach Kolektywu, jego oficjalna historia zosta³a trochê „uproszczona”.)}

{230} {} {Pozyskiwanie czêœci z... Garage City?}
{231} {} {(Jak siê okazuje, Blacharze otrzymali od Wyznawców ognia tê sam¹ czêœæ, któr¹ da³eœ karawanom w Garage City. Zosta³a wys³ana tutaj do masowej reprodukcji.)}
{232} {} {Akta Carlosa.}
{233} {} {(Co dziwne, pomimo ca³ej swojej izolacji, Blacharze pokochali i zaakceptowali Carlosa za jego talenty i zainteresowania technologiczne.)}
{234} {} {No có¿, poprawmy trochê dokumentacjê tutaj... a potem tutaj... Mam nadziejê, ¿e to wytr¹ci Carlosa z dumy.}
{235} {} {(Sabotujesz akta. Teraz wed³ug nich Blacharze prawdopodobnie maj¹ podejrzenia co do tego nowicjusza z pustkowi.)}
{236} {} {Swietnie, to sprawi, ¿e Carlos opuœci Tu-San.}
