{100} {} {Widzisz obiekt testowy.}
{101} {} {Widzisz postaæ do okrutnych eksperymentów. Mo¿esz siê z ni¹ dobrze bawiæ.}
{110} {} {Ok, okej, wyluzuj.}

# Repliki plywajace
{120} {} {Dobry dzieñ na œmieræ.}
{121} {} {Czy ten œwiat nie jest piêkny?}
{122} {} {}
{123} {} {}
{124} {} {}
{125} {} {}
{126} {} {}
{127} {} {}
{128} {} {}
{129} {} {}

#Dialog
{200} {} {Chwa³a Bractwu Stali!}
{201} {} {Nienawidzê Bractwa. Ciebie te¿ nienawidzê.}
{202} {} {Uch, tak, oczywiœcie.}
{203} {} {Jestem teraz twoim dowódc¹. Rozkazujê ci do³¹czyæ do oddzia³u.}
{204} {} {Jakieœ wskazówki, proszê pana?}
{205} {} {Spocznij, ¿o³nierzu.}

{206} {} {Intelekt 2}
{207} {} {Intelekt 4}
{208} {} {Intelekt 5}
{209} {} {Intelekt 6}
{210} {} {Intelekt 8}

{211} {} {Nie rozumiem... przyjacielu}
{212} {} {Czy ty bierzesz mnie za g³upca? Mówiê do Ciebie!}
{213} {} {Zostañ tutaj, a pomyœlê o odpowiedzi.}
{214} {} {Bractwo? S³yszê po raz pierwszy.}
{215} {} {Opowiedz mi o Bractwie.}
