{101} {} {Widzisz prowizoryczny warsztat.}
{102} {} {Uda³o ci siê stworzyæ 20 sztuk amunicji sygna³owej, u¿ywaj¹c starej pirotechniki.}
{110} {} {Ten stó³ warsztatowy zawiera elementy do monta¿u baterii j¹drowych.}
{111} {} {Wszystkie komponenty zosta³y zu¿yte. Nie ma tu ju¿ nic innego do roboty.}
{112} {} {Uda³o ci siê stworzyæ 8 sztuk baterii mikrordzeniowych.}
{113} {} {Uda³o ci siê stworzyæ 16 sztuk baterii mikrordzeniowych.}
{114} {} {Uda³o ci siê stworzyæ 20 sztuk baterii mikrordzeniowych.}
