{100} {} {Widzisz terminal alarmowy.}
{101} {} {Widzisz komputer oznaczony jako „Zarz¹dzanie awaryjne”.}
{102} {} {ZAX przej¹³ kontrolê nad systemem, teraz nie mo¿na zainicjowaæ zarz¹dzania awaryjnego.}
{103} {} {Terminal nie dzia³a.}
{104} {} {Pierwszy port zosta³ pod³¹czony. WprowadŸ drug¹ kartê dostêpu.}
{105} {} {Drugi port zosta³ pod³¹czony.}

#Dialog
{200} {} {WprowadŸ polecenie.}
{201} {} {Zakoñcz sesjê.}
{202} {} {Wstecz.}

{210} {} {Zainicjuj protokó³ awaryjny.}
{211} {} {Uwaga! Protokó³ awaryjny wyzwoli serie eksplozji pulsacyjnych, które zniszcz¹ ca³y sprzêt elektroniczny w bunkrze. Ta procedura jest nieodwracalna i jest dozwolona tylko w nag³ych wypadkach.}
{212} {} {Kto by pomyœla³?}
{213} {} {Ok.}
{214} {} {Na pewno chcesz uruchomiæ protokó³ awaryjny?}
{215} {} {Nie, anuluj eksplozje.}
{216} {} {Tak, zainicjuj awaryjne eksplozje.}
{217} {} {Ze wzgledów bezpieczeñstwa wy³¹cz ten terminal i zabierz karty dostêpu.}
{218} {} {Uruchamiam protokó³ awaryjny...}
{219} {} {No dalej, zrób to, cholerny z³omie!}