{100} {} {Widzisz babciê Adonsiê.}
{101} {} {Widzisz kobietê, któr¹ dobrze znasz - twoj¹ babciê. Pali fajkê i mru¿y oczy.}
{102} {} {Do widzenia babciu. Mam nadziejê, ¿e nikt nie pozna prawdziwej przyczyny Twojej œmierci.}
{103} {} {Jaki demon zwróci³ ciê przeciwko nam? Wypêdz go! Opamiêtaj siê!}

# Pierwszy dialog
{210} {} {(zaci¹ga siê, a potem wydycha czarny dym, gdy patrzy na ciebie). Tutaj jesteœ. Mia³eœ szczêœcie, ¿e by³eœ poza domem w najczarniejszej godzinie. A mo¿e to i lepiej... //Spolszczenie autorstwa Cassar/Ski//}
{211} {} {Babciu Adonsiu, nie mamy teraz czasu na rozmowê. Powiedz mi, co siê dzieje.}
{212} {} {Przestañ be³kotaæ, staruszko. Powiedz mi lepiej co siê sta³o.}
{213} {} {Co siê sta³o? Co siê dzieje?}
{214} {} {M? Zaczynasz mówiæ jak doros³y. To napawa optymizmem.}
{215} {} {Nadal nie mo¿esz uspokoiæ swoich nerwów? Chocia¿ mo¿e ci to pomóc w przysz³oœci.}
{216} {} {Martwisz siê, co? Nie najlepsza pora, gdy musisz podj¹æ decyzjê. Musisz dzia³aæ.}
{217} {} {Wiêc co siê sta³o?}

{218} {} {Kiedy ciê nie by³o, przyszli ludzie z zewn¹trz. Zli ludzie. Oko³o dziesiêciu osób i wszyscy z broni¹. Nasi ludzie nie mogli sobie z nimi poradziæ.}
{219} {} {Kontynuuj.}
{220} {} {Obcy zabrali wszystkich zdolnych do pracy. Zostawili tylko osoby starsze i dzieci. Teraz Villa jest w twoich rêkach, ty tu rz¹dzisz. I musisz coœ z tym zrobiæ.}
{221} {} {Co mogê zrobiæ sam?}
{222} {} {A jak myœlisz? Uwolnij naszych mê¿czyzn i kobiety. S¹ wœród nich twoi rodzice. Oni te¿ wpadli w szpony tych bandytów.}
{223} {} {To nie bêdzie ³atwe...}
{224} {} {(kiwa g³ow¹) Racja. Dlatego powiem Ci, chocia¿ twojemu padre to nie spodoba siê strasznie. Na dole, w piwnicach pod ratuszem, znajduje siê sekretne pomieszczenie z rodzinnymi relikwiami. Wie o tym tylko kilka osób. ZejdŸ na dó³, znajdŸ je i zabierz wszystko, co ci siê przyda w drodze. I zrób to teraz, czas nagli.}
{225} {} {Dziêki babciu. Teraz ka¿dy drobiazg mi pomo¿e.}
{226} {} {Czy to wszystko? Cholera, ¿adnej pomocy od ciebie. Dobrze, rozejrzê siê po piwnicy taty.}
{227} {} {Ok, spróbujê znaleŸæ te stare rzeczy.}
{228} {} {Uwa¿aj. W piwnicach jest pe³no szczurów i ciemno jak w rzyci bramina. Proszê, weŸ zapalniczkê, chocia¿ bêdê za ni¹ têskni³a. A kiedy znajdziesz sekretne rzeczy, idŸ prosto na plac i znajdŸ tam Jose. Powie Ci wiêcej.}
{229} {} {Zanim pójdê, muszê ciê o coœ zapytaæ.}
{1229} {} {Zanim pójdê na dó³, muszê ciê o coœ zapytaæ.}
{230} {} {Pójdê natychmiast.}

{231} {} {Dlaczego nadal tu jesteœ?}
{232} {} {Zanim wyjdê, muszê ciê o coœ zapytaæ.}
{1232} {} {Zanim wyjdê, muszê ciê o coœ zapytaæ.}
{233} {} {Rzeczywiœcie, muszê iœæ.}
{234} {} {Wykona³eœ dobr¹ robotê, sprowadzaj¹c naszych ludzi z powrotem. Doskona³a robota.}
{1234} {} {Wykona³aœ dobr¹ robotê, sprowadzaj¹c naszych ludzi z powrotem. Doskona³a robota.}
{235} {} {Mam pytania.}
{236} {} {Muszê iœæ.}
{237} {} {Có¿, to mój obowi¹zek. Dam z siebie wszystko.}
{238} {} {Uwolnij naszych mê¿czyzn i kobiety. Twoi rodzice równie¿ wpadli w szpony najeŸdŸców.}
{239} {} {Myœla³em, ¿e jesteœ m¹drzejsza. Jak mam niby samemu daæ sobie radê z ca³ym oddzia³em najeŸdŸców?}

#Zapytania
{240} {} {ZnajdŸ Jose na placu, powie ci wiêcej.}
{241} {} {Jak dosz³o do ataku obcych?}
{242} {} {Czy ktoœ nie ¿yje?}
{243} {} {Co z moimi rodzicami?}
{244} {} {Ten sekretny pokój w piwnicach rodzi pytania.}
{245} {} {Co mam zrobiæ, gdy znajdê te staro¿ytne rzeczy?}
{246} {} {Ok, wychodzê.}
{247} {} {Kolejne pytanie.}
{248} {} {Twoi rodzice te¿ s¹ wœród porwanych. Czy ci siê to podoba, czy nie, musisz ich uratowaæ, nawet samemu. Krew za krew i ramiê w ramiê - tak nauczyli nas nasi przodkowie. Pozostanie tutaj skazuje nasz¹ spo³ecznoœæ na zag³adê.}

{250} {} {Zaatakowali nas w najbardziej nieoczekiwanym momencie. Wszystkich sprawnych ludzi zwi¹zano i rano zabrano na wschód. Jose wie wiêcej, zapytaj go.}
{251} {} {Tak, w ratuszu by³a ca³a masakra. Kilku zosta³o zabitych, a inni okaleczeni. Jeœli masz s³abe nerwy, lepiej tam nie idŸ.}
{252} {} {Twój padre i madre równie¿ zostali zabrani. Poœpiesz siê, mo¿e uda Ci siê ich uratowaæ.}
{253} {} {Oczywiœcie. Tylko starzy ludzie wiedzieli o sekretnej komnacie Za³o¿yciela. Zawiera naprawdê stare rzeczy i wiedzê, o której wszyscy w Villi nie powinni wiedzieæ. Mimo to ojciec zabiera³ Ciê tam gdy by³eœ ma³y, kiedy tylko uzna³ to za stosowne.}
{254} {} {Oczywiœcie g³upie. Najpierw znajdŸ Jose i zapytaj o nalot. Nastêpnie pod¹¿aj za najeŸdŸcami. }
{1254} {} {Oczywiœcie g³upie. Najpierw znajdŸ Jose i zapytaj o nalot. Nastêpnie pod¹¿aj za najeŸdŸcami. }
{255} {} {Ale starzy ludzie zawsze uczyli nas, abyœmy nie u¿ywali staro¿ytnych rzeczy. Czy te zasady zosta³y naruszone nawet przez Za³o¿yciela?}
{256} {} {Nie wyci¹gaj pochopnych wniosków. Zasady zosta³y ustalone, aby chroniæ nas przed niebezpieczenstwami starych rzeczy. Ale nie wszystkie z nich s¹ naprawdê niebezpieczne, niektóre s¹ nawet przydatne.}
{257} {} {Mo¿e gdybyœmy wiedzieli wiêcej o staro¿ytnych rzeczach, bylibyœmy gotowi obroniæ siê przed najeŸdŸcami.}
{258} {} {(zaci¹ga siê w zamyœleniu i wydmuchuje czarny dym) Za³o¿yciel tak nie myœla³. Powiedzia³, ¿e mamy siê skupiæ na uprawie ziemi. Tylko w ten sposób mogliœmy przetrwaæ w trudnych czasach. I dobrze nam siê ¿y³o bez tych starych technologii. Czy ¿y³oby nam siê z nimi lepiej? Nie wiem. Nikt nie wie.}
{259} {} {Babciu Adonsiu, czy zna³aœ Za³o¿yciela?}
{260} {} {Och, to by³o tak dawno, ¿e nawet nie pamiêtam jego twarzy. Pamiêtam w¹sy, ale ¿adnej twarzy. Ale to ju¿ przesz³oœæ, nie przejmuj siê. Masz wa¿niejsze rzeczy na g³owie.}

{261} {} {Babciu, czy wiesz, ¿e Za³o¿yciel zdradzi³ swoj¹ Kryptê?}
{262} {} {Dlaczego pytasz? Czy ojciec pokaza³ ci swoje notatki? Có¿, brzemiê Felixa by³o ciê¿kie, a jego sumienie gnêbi³o go nawet w nocnych koszmarach. Nie do ciebie nale¿y os¹dzanie go. Da³ ¿ycie temu miejscu, choæ kosztem wielu innych. Doceñ to.}
{263} {} {Nie myœl o tym teraz. S¹ wa¿niejsze rzeczy, które musisz zrobiæ.}

# Po zakoñczeniu fabuly
{300} {} {Nie powinieneœ wracaæ do Villi po wszystkim, co zrobi³eœ.}
{1300} {} {Nie powinnaœ wracaæ do Villi po wszystkim, co zrobi³aœ.}
{301} {} {Och, daj spokój. Jakbyœcie wszyscy byli tutaj tacy prawi.}
{302} {} {Pustkowia otworzy³y mi oczy na œwiat. Zyjecie niew³aœciwie.}
{303} {} {To nie ty decydujesz, jak bêdziemy ¿yæ! Villa przetrwa³a dziêki tradycjom i fundamentom, które ustanowi³ Za³o¿yciel. Zadne Pustkowia nie mog¹ nam narzuciæ innej œcie¿ki.}
{304} {} {?}
{305} {} {Jesteœ hipokryt¹, który ukrywa swoj¹ g³upotê przed œwiatem zewnêtrznym! OdejdŸ i nie wracaj. Przeklinam ciê, }
{306} {} { !}
{307} {} {Spokojnie babciu.}
{308} {} {Wszyscy jesteœcie tutaj hipokrytami. Nie zamierzam robiæ ani kroku dalej w tym ba³aganie.}
{309} {} {Sam Za³o¿yciel Villi ostrzeg³ nas, ¿ebyœmy trzymali siê razem. Ale teraz jest ju¿ za póŸno. Tej zarazy nie mo¿na powstrzymaæ, dopóki ¿yje pamiêæ o Tobie.}
{310} {} {Swoj¹ drog¹, co siê sta³o z Za³o¿ycielem?}

{320} {} {Jestem z ciebie dumna }
{321} {} {.}
{322} {} {Naprawdê?}
{323} {} {Mi³o to s³yszeæ.}
{324} {} {Przeszed³eœ d³ug¹ drogê, i pozosta³eœ wierny swojemu domu i swojej rodzinie. Teraz mogê przejœæ na emeryturê, wiedz¹c, ¿e Villa jest w dobrych rêkach.}
{1324} {} {Przeszed³aœ d³ug¹ drogê, i pozosta³aœ wierna swojemu domu i swojej rodzinie. Teraz mogê przejœæ na emeryturê, wiedz¹c, ¿e Villa jest w dobrych rêkach.}
{325} {} {Jak mog³aœ we mnie w¹tpiæ?}
{326} {} {Dziêki za mi³e s³owa, babciu.}
{327} {} {Starzy ludzie wiedz¹ trochê wiêcej ni¿ reszta. Znaliœmy zarówno zewnêtrzne miasta, jak i technologie Starego Swiata. I wiedzieliœmy to, ¿e tylko powszechne nieszczêœcie mo¿e zjednoczyæ ludzi.}
{328} {} {Nie bez tego.}
{329} {} {Te wyk³ady... znowu...}
{330} {} {Wtedy zaczynaj¹ siê konflikty i rozpad rodziny. Byæ mo¿e historia z nalotem by³a bardzo pomocna - przypomnia³a nam, ¿e powinniœmy trzymaæ siê razem. Za³o¿yciel Villi dobrze to rozumia³ i zapisa³ to w swoim przemówieniu do potomków.}
{331} {} {Swoj¹ drog¹, co siê z nim sta³o?}

{340} {} {Wiêc }
{341} {} {, jesteœ tutaj. Jak na pocz¹tku œcie¿ki. Ale coœ siê w tobie zmieni³o, prawda?}
{342} {} {Och, daj spokój. Jakbyœcie wszyscy byli tutaj tacy prawi.}
{343} {} {Pustkowia zmieni³y nas wszystkich. Mo¿na to zmieniæ.}
{344} {} {Do tej pory Villa przetrwa³a zgodnie z zasadami i tradycjami, które ustanowi³ Za³o¿yciel. Zadne Pustkowia nie mog¹ nam narzuciæ innej œcie¿ki. Powinieneœ wiêcej s³uchaæ opinii swojej rodziny.}
{345} {} {Nie bêdê siê z tob¹ k³óciæ. Moje decyzje zosta³y ju¿ podjête.}
{346} {} {Mo¿esz mieæ racjê. Wiêc co teraz?}
{347} {} {Sam Za³o¿yciel Villi ostrzeg³ nas, ¿ebyœmy trzymali siê razem. Ale teraz jest za póŸno - nalot na Villê móg³ zebraæ i podzieliæ spo³ecznoœæ. Twoja interwencja mo¿e wywo³aæ niezgodê.}
{348} {} {Swoj¹ drog¹, co siê sta³o z Za³o¿ycielem? Z jakiegoœ powodu nie znam ca³ej historii.}

{350} {} {Zmar³ przedwczeœnie z ciê¿kiej pracy na polach i na placach budowy. Nie zakopaliœmy go w ziemi zgodnie z tradycj¹. Zamiast tego wnieœliœmy go do jaskini i otoczyliœmy ceglanym sarkofagiem. Jego krypta jest nadal dobrze zachowana.}
{351} {} {Nigdy tam nie by³em. Czy mo¿esz mi pokazaæ tê kryptê?}
{1351} {} {Nigdy tam nie by³am. Czy mo¿esz mi pokazaæ tê kryptê?}
{352} {} {Ciekawe. Myœlê, ¿e czas ju¿ iœæ. Do widzenia, babciu.}
{353} {} {Ok. Byæ mo¿e wizyta w jego krypcie poruszy twoj¹ zagubion¹ duszê.}
{354} {} {Ok. Myœlê, ¿e zas³ugujesz na wizytê w tej œwi¹tyni.}
{355} {} {Ok. Byæ mo¿e wizyta w jego krypcie otworzy Ci oczy.}
{356} {} {No dalej. Chcê ju¿ wyjœæ.}
{357} {} {Teraz nie czas. Pójdê tam, gdy bêdê mia³ wiêcej wolnego czasu.}

{360} {} {Zamknij za sob¹ drzwi, jeœli masz zamiar wyjœæ.}
{361} {} {Ju¿ wychodzê. Do widzenia, babciu.}
{362} {} {Chcê zobaczyæ kryptê Za³o¿yciela. Mo¿esz mnie tam zabraæ?}