{100} {} {Widzisz najeŸdŸcê.}
{101} {} {Widzisz outsidera. NajwyraŸniej nie jest z nim dobrze.}
{102} {} {Otrzymujesz }
{103} {} { doœwiadczenia za pokojowe rozwi¹zanie konfliktu.}
{104} {} {}
{105} {} {NajeŸdŸca spokojnie opuszcza Villê.}
{106} {} {Moje pierwsze zabójstwo... Dziwne uczucie.}

# Plywajace repliki
{110} {} {* Oddycha ciê¿ko *}
{111} {} {* Kaszle *}
{112} {} {Hrrrr...}
{113} {} {Cholera...}
{114} {} {Dlaczego siê w to zaanga¿owa³em?}
{115} {} {Co ja tu do cholery robiê?}
{116} {} {Jak siê st¹d wydostaæ?}
{117} {} {Nie poddam siê tak ³atwo.}
{118} {} {Kiedy przyjd¹ z pomoc¹?}
{119} {} {To wszystko? Wiêc tak skoñczê swoje ¿ycie?}

{120} {} {Pomyœl, czego ode mnie chcesz. Nie obchodzi mnie to.}
{121} {} {Nie wrócê, nie musisz siê dr¿eæ ze strachu.}
{122} {} {Rozmowa dobieg³a koñca. Nie denerwuj mnie.}

# Rozpocznij dialog
{200} {} {(Widzisz przed sob¹ nieznajomego w podartych, brudnych ubraniach; wygl¹da jakby by³ ranny i wyczerpany) Hej, ty... * Khe-khe * Po¿egnaj siê z ¿yciem, redneck!}
{201} {} {Hej spokojnie, nie chcê ciê skrzywdziæ.}
{202} {} {Rzucasz siê? Wygl¹da na to, ¿e bêdê musia³ siê broniæ.}
{203} {} {Zamknij siê... (wzdycha) By³em zamkniêty w tej piwnicy przez 24 godziny. Myœlisz, ¿e tak to zostawiê? * Khe-khe * Wszyscy za to zap³acicie. Rozwalê Twoj¹ Villê!}
{204} {} {Nie zostawiasz mi wyboru. Bêdziemy musieli ciê uspokoiæ si³¹.}
{205} {} {IdŸ do diab³a!}
{206} {} {Hej, hej, czekaj...}
{207} {} {Zacznijmy zabawê...}
{208} {} {S³uchaj, nie ma sensu walczyæ...}
{209} {} {S³uchaj, nie ma sensu, ¿ebyœmy walczyli. Spokojnie. Najgorsze minê³o.}
{210} {} {Nie wygl¹dasz dobrze. Mogê ciê uzdrowiæ.}
{211} {} {Nie zamierzasz tak walczyæ, prawda? Mogê pomóc, jeœli siê uspokoisz.}
{212} {} {Niepolecam. Pu³apki s¹ wszêdzie.}
{213} {} {Pu³apki s¹ wszêdzie dooko³a. Nie mo¿esz wyjœæ beze mnie. Tylko ja znam jedyne wyjœcie.}
{214} {} {Zamierzasz zaatakowaæ bezbronn¹ kobietê? Ca³kowicie oszala³eœ?}
{215} {} {(rozgl¹da siê, odzyskuje przytomnoœæ) Masz racjê...  Ok, wyprowadzisz mnie st¹d. Ale nie próbuj mnie oszukaæ. Jeden fa³szywy ruch - i nie ¿yjesz.}
{216} {} {Ok, ok... Czy mo¿esz mi powiedzieæ, co siê tutaj sta³o?}

{220} {} {Czy to jakaœ sztuczka? Wykrwawiam siê tutaj. Ruszaj siê szybciej i zabierz mnie na górê.}
{221} {} {Ok, odejdŸ. Za tym stojakiem jest tajne wyjœcie z piwnicy. Wyjœcie na górê znajdziesz dalej.}
{222} {} {I naprawdê myœlisz, ¿e pozwolê ci odejœæ po tym, co us³ysza³em? Jesteœ zbyt niebezpieczny dla Villi.}
{223} {} {Tajne wyjœcie? Sprytnie... Cholera, zabi³bym ciê, ale nie jestem teraz w najlepszej formie. Muszê oszczêdzaæ si³y. Wiêc ¿yj.. narazie.}
{224} {} {Uch, dobrze. Poradzimy sobie bez po¿egnalnego uœcisku.}
{225} {} {IdŸ ju¿. Przestañ marnowaæ mój czas.}
{226} {} {Tak, mo¿esz to wzi¹æ. (rzuca ci stary klucz zabrany twojemu ojcu przez bandytów) I tak nie ma tam nic wartoœciowego.}
{227} {} {Hmm...}

#O mnie
{250} {} {Kim w³aœciwie jesteœ?}
{251} {} {Nie twoja psia sprawa.}
{252} {} {Rzeczywiœcie. To by³o bezcelowe pytanie.}
{253} {} {Przepraszam. Pytam tylko dlatego, bo po raz pierwszy rozmawiam z nieznajomym.}
{254} {} {Zastanawiam siê tylko, jak doszed³eœ do tej chwili w ¿yciu.}
{255} {} {Jestem zwyk³ym najemnikiem. Rozumiesz? Bez domu, bez rodziny, bez imienia.}
{256} {} {Och, przepraszam. Czy trudno jest dorastaæ bez krewnych i domu?}
{257} {} {Czy jesteœ taki dziki przez pustkowia? Oto nasza Villa - jedna wielka rodzina.}
{258} {} {Nie wiem... Nie wiem, co to znaczy ¿yæ w tak wielkiej rodzinie jak ty. Prawdopodobnie nie móg³bym tak zyæ. Nie móg³bym siê dzieliæ i ufaæ komuœ innemu takiemu jak ja... Cholera, lepiej zamknij siê, zanim wybijê ci zêby.}
{259} {} {Dlaczego jesteœ taki z³y?}
{260} {} {Ooh, to ciê denerwuje, prawda?}
{261} {} {Nie rozumiesz. Zy³em od dziecka na œmietnisku w du¿ym mieœcie. Typowa historia. Tam, sk¹d pochodzê, nikt nie ceni ludzi. Populacja jest zbyt du¿a i brakuje pracy dla ka¿dego. Ktoœ znika i nikomu to nie robi ró¿nicy.}
{262} {} {Jeœli poza Vill¹ jest rzeczywiœcie tak Ÿle, mo¿esz zostaæ zrozumiany. Ale tylko trochê.}
{263} {} {Musia³em walczyæ o swoje miejsce. A ty w³aœnie uciek³eœ od problemu.}
{264} {} {Nie potrzebujê twojej litoœci. Lepiej zabierz mnie na zewn¹trz.}
{265} {} {Czekaj. Najpierw odpowiedz na jeszcze jedno pytanie.}
{266} {} {Myœlisz, ¿e to takie proste, co? Oczywiœcie, bo jesteœ tu, a nie tam. Lepiej siê zamknij i zabierz mnie na zewn¹trz.}
{267} {} {Czekaj. Odpowiedz na jeszcze jedno pytanie.}

{270} {} {Dlaczego zaanga¿owa³eœ siê w ten nalot?}
{271} {} {Poniewa¿ muszê zarabiaæ na jedzenie. Rozumiesz? Innej pracy nie by³o, a w obozie akurat zbierano oddzia³. Chcia³em tylko zdobyæ ma³e zapasy na tym nalocie, a potem odejœæ. I co? Jestem tutaj. W pieprzonej piwnicy.}
{272} {} {Naprawdê nie by³o innej pracy? To przykre.}
{273} {} {Mo¿e po prostu nie chcia³eœ uczciwie pracowaæ?}
{274} {} {To nie jest praca, to jest ciê¿ka harówa. Jesteœ u¿ywany jak pionek. Jestem ponad to! Te¿ chcê normalnie ¿yæ.}
{275} {} {Co robi³eœ wczeœniej?}
{276} {} {Nikt nie odrzuci³by wartoœciowego pracownika. Wiêc nie jestem takim.}
{277} {} {Nikt siê o ciebie nie troszczy. Przetrwaj, jak potrafisz. Pracowa³em w ró¿nych miejscach, od z³otej r¹czki w barze po handlarza niewolników najeŸdŸców. Muszê jakoœ zarabiaæ na jedzenie.}
{278} {} {Widzê, ¿e nie podoba ci siê to pytanie. Chcesz o tym porozmawiaæ?}
{279} {} {Nie chcê.}
{280} {} {Có¿, masz prawo.}
{281} {} {Moim zdaniem jest to tylko typowa wymówka. Taka jest moja opinia.}
{282} {} {W takim razie wsadŸ sobie swoj¹ opiniê g³êboko w dupê.}
{283} {} {Hej, to by³o niegrzeczne.}
{284} {} {Sta³eœ siê z³ym cz³owiekiem, ¿eby dopasowaæ siê do otoczenia, prawda?}
{285} {} {Cholera, to jest coœ. Mo¿e po prostu zadajê siê z niew³aœciwymi ludŸmi, wybieram z³e miejsca? A mo¿e powinienem usi¹œæ i pomyœleæ... Nie, zamknij siê. Nie zapomnij, kto tu rz¹dzi.}
{286} {} {Oczywiœcie, teraz to ty tu jesteœ szefem.}

#O nalocie
{290} {} {Powiedz mi, co siê tutaj sta³o?}
{291} {} {Masz na myœli osuniêcie siê ziemi? (pluje) G³upia historia.}
{292} {} {Jak znalaz³eœ siê w tej pu³apce?}
{293} {} {Oczywiœcie tylko g³upiec wpada w coœ takiego.}
{294} {} {Wiêc powiesz mi kiedy indziej.}
{295} {} {Dorwa³em jednego z twoich, a ten powiedzia³ mi o tym miejscu. Myœla³em, ¿e jest tu coœ cennego. Zszed³em pierwszy, ale wpad³em w pu³apkê. Z ty³u zagrzmia³ wybuch, zawali³ siê sufit. Zemdla³em. To wszystko, co pamiêtam.}
{296} {} {Hmm, to musia³a byæ jedna z pu³apek mojego ojca. Zorganizowa³ to na wypadek, gdyby Villa zosta³a przejêta przez osoby postronne.}
{297} {} {Myœla³eœ, ¿e to bêdzie takie proste? Mój ojciec przewidzia³ mo¿liwoœæ zdobycia Villi.}
{298} {} {Wygl¹da na to, ¿e nie doceniliœmy przebieg³oœci twojego ludu. Ile jeszcze sztuczek i tajemnic kryje siê w tym lochu, co?}
{299} {} {Czy próbowa³eœ wyjœæ lub wezwaæ pomoc?}
{300} {} {Tak, ale nikt nie odpowiada³. Te skurwysyny musia³y mnie porzuciæ. Sam nie mog³em wyjœæ z piwnicy - droga w górê zosta³a zniszczona, a innego wyjœcia nie ma. To znaczy... skoro tu jesteœ, to gdzieœ jednak jest wyjœcie, prawda?}
{301} {} {Uch, tak, ale najpierw muszê coœ wymyœliæ.}
{302} {} {Czy znalaz³eœ coœ interesuj¹cego w tych piwnicach?}
{303} {} {Nie ma tu nic, dla czego warto ryzykowaæ swoj¹ skórê. Chocia¿ dziwnie jest zobaczyæ staro¿ytn¹ technologiê w takiej dziurze. Po co Ci ona?}
{304} {} {O jakiej technologii mówisz?}
{305} {} {Technologia? Masz urojenia. Technologia staro¿ytnych jest zakazana w Villi.}
{306} {} {Nie wiesz? Dawno zapomniane przedmioty w s¹siednim pokoju. S¹ tak stare i zgni³e, ¿e nie mo¿na ich nawet rozebraæ na z³om. Nie zdziwi³bym siê, gdybyœ potajemnie wielbi³ te kawa³ki ¿elaza.}
{307} {} {Bzdury. Dlaczego ojciec ukrywa³by przed nami przedmioty zabronione?}
{308} {} {Mówisz, ¿e to zwyk³e œmieci? Musia³eœ coœ pomyliæ.}
{309} {} {Sk¹d mam wiedzieæ? Ty tu mieszkasz. Ale jeœli mój przywódca ukrywa³by coœ, czego sam zabrania, przesta³bym mu ufaæ.}
{310} {} {Musia³ mieæ jakiœ wa¿ny powód. Ale nie o to teraz chodzi.}
{311} {} {Nie wa¿ siê Ÿle mówiæ o moim ojcu. Jasne?}
{312} {} {Nie wiem. Moj¹ specjalnoœci¹ nie jest rozumienie sprzêtu, tylko dawanie w mordê.}
{313} {} {Ojciec musia³ mieæ wa¿ny powód. Ale nie o to teraz chodzi.}
{314} {} {Tak. Nawiasem mówi¹c, moje te¿.}
{315} {} {Niczego innego nie mo¿na oczekiwaæ od barbarzyñcy. Ok, wystarczy ju¿ o tym.}

{320} {} {Co wiesz o wydarzeniach na piêtrze? Zanim tu spad³eœ.}
{321} {} {Niewiele. Widzia³em tylko pocz¹tek nalotu.}
{322} {} {Dlaczego w ogóle nas zaatakowa³eœ? Chcia³eœ zabraæ nasze zbiory?}
{323} {} {Cholerni barbarzyñcy. Czy jesteœ zdolny tylko do rabunku, czy mo¿e masz z tego jak¹œ inn¹ korzyœæ?}
{324} {} {G³upi wieœniaku, ty... (drwi z ciebie, ale potem gorzko odchrz¹kuje) Nie masz nawet najmniejszego pojêcia o œwiecie zewnêtrznym, prawda? Twoi wspó³plemieñcy zostali zabrani do pracy w kopalni. Chocia¿ nie s¹dzê, ¿e wiesz, co to jest.}
{1324} {} {G³upia wieœniaczko, ty... (drwi z ciebie, ale potem gorzko odchrz¹kuje) Nie masz nawet najmniejszego pojêcia o œwiecie zewnêtrznym, prawda? Twoi wspó³plemieñcy zostali zabrani do pracy w kopalni. Chocia¿ nie s¹dzê, ¿e wiesz, co to jest.}
{325} {} {[Pos³uchaj]}
{326} {} {Ok, lepiej siê zamknij, w przeciwnym razie...}
{327} {} {Bêd¹ teraz skuci i zmuszani do pracy pod ziemi¹. Ci, którzy odmówi¹ pos³uszeñstwa, zostan¹ surowo ukarani. Skorzystaj z tego, ci ludzie nigdy nie wróc¹ do Villi. A niektórzy nawet nie zobacz¹ ju¿ wiêcej œwiat³a s³onecznego.}
{328} {} {Nie rozumiem, jak mog³eœ zrobiæ coœ takiego? Muszê przez takich jak ty teraz uratowaæ moich ludzi!}
{329} {} {Szkoda, ¿e mnie tu nie by³o podczas nalotu. Wszyscy poszlibyœcie do piachu.}
{330} {} {Otwórz oczy, dzikusie. Jeden karabin wystarczy, by rzuciæ ciê na kolana. Co zrobisz sam przeciwko ca³ej bandzie uzbrojonych najemników? (pluje) Zbyt d³ugo mieszkasz w swoich Ogrodach Edenu i nie masz pojêcia, jak okrutny jest œwiat poza nimi.}
{1330} {} {Otwórz oczy, dzikusie. Jeden karabin wystarczy, by rzuciæ ciê na kolana. Co zrobisz sam przeciwko ca³ej bandzie uzbrojonych najemników? (pluje) Zbyt d³ugo mieszkasz w swoich Ogrodach Edenu i nie masz pojêcia, jak okrutny jest œwiat poza nimi.}
{331} {} {Wygl¹da na to, ¿e nie lubisz tego miejsca.}
{332} {} {Nie wa¿ siê tak mówiæ o Villi. To miejsce jest piêkne.}
{333} {} {Nie masz pojêcia, co musia³em robiæ by przetrwaæ. Mieszka³em na ulicy, walczy³em o jedzenie, okrada³em przechodniów, a nawet zabija³em. Jak wszyscy na pustkowiu... Wszyscy oprócz waszej "Villi".}
{334} {} {[Dalej.]}
{335} {} {Jesteœ jedyn¹ osob¹, która je i pije tyle, ile chce. Jesteœ czysty, pulchny i patrzysz na ludzi z Pustkowia, jakby byli œmieciami. Jesteœ dla mnie obrzydliwy. Ca³a twoja kwitn¹ca Villa jest dla mnie jak gula w gardle.}
{336} {} {Tak, nie mam pojêcia, przez co przeszed³eœ. I nie chcê sobie tego nawet wyobra¿aæ.}
{337} {} {Czy to kolejne twoje usprawiedliwienie? Ale z ciebie sukinsyn.}