{100} {} {Widzisz Chrisa.}
{101} {} {Widzisz jednego z ch³opów. Jego spojrzenie zdradza spore zdziwienie.}

{200} {} {(odwraca wzrok) Och... Myœla³em, ¿e te¿ zosta³eœ zabrany przez tych bandytów. Dobrze, ¿e przynajmniej ktoœ zosta³.}
{201} {} {Do widzenia.}
{202} {} {Opowiedz mi o nalocie.}
{203} {} {Dlaczego rabusie ciê nie zabrali?}
{204} {} {Ci rabusie pojawili siê nieoczekiwanie. Otoczyli nas ze wszystkich stron i wpêdzili naszych ludzi w pu³apkê. Niektórzy ukryli siê w swoich domach, ale i tak ich wyci¹gnêli.}
{205} {} {Zdecydowali, ¿e mnie nie potrzebuj¹. Prawdopodobnie by³em dla nich za s³aby.}
{206} {} {Coœ krêcisz, Chris.}
{207} {} {(odwraca wzrok) Po prostu... schowa³em siê w piwnicy... i siedzia³em tam, a¿ by³o po wszystkim.}
{208} {} {I patrzy³eœ stamt¹d, jak twoi wspó³plemieñcy byli bici i wi¹zani? Ty draniu!}
{209} {} {Chris, zdecydowanie jesteœ tchórzem.}
{210} {} {Aha. Có¿, trudno ciê o to winiæ.}
{211} {} {Co jeszcze mog³em zrobiæ?! Iœæ prosto w ich rêce?! Nie wiem, jak walczyæ... Nigdy nie wiedzia³em, jak... mog³em tylko obserwowaæ.}
{212} {} {Ciekawe co zrobi¹ z tob¹ nasi ludzie, gdy wróc¹ do Villi. Do tego czasu ciê zostawiê.}
{213} {} {Wiem! Ale co mog³em zrobiæ? Nie umiem walczyæ, nie mia³em broni, by³em sam przeciwko tuzinowi nieznajomych! Latwo ci mówiæ - nie by³o ciê tutaj. A teraz to ja muszê z tym ¿yæ...}
{214} {} {Naprawdê tak myœlisz? Tak, oczywiœcie, ale ciebie tu nie by³o... to ma³a pociecha. I tak zostawi³em swoich ludzi. A teraz muszê z tym ¿yæ.}
{215} {} {Kontynuuj.}
{216} {} {Najtrudniej by³o ukryæ siê w ratuszu - tam by³a prawdziwa masakra.}