{100} {} {Widzisz Chrisa.}
{101} {} {Widzisz jednego z ch³opów. Jego spojrzenie zdradza spore zdziwienie.}

{110} {} {Plecak Chrisa jest pe³en prowiantu.}
{111} {} {Dziêki, wystarczy... mam nadziejê.}
{112} {} {(}
{113} {} {from}
{114} {} {) Plecak Chrisa jest pe³en prowiantu, ale nie wystarczy na podró¿.}
{115} {} {Dziêki. Przynajmniej nie umrê z g³odu.}

{200} {} {? To ty... Nic dziwnego, podejrzewa³em, ¿e to ty, nowy bohater Villi, zostaniesz wys³any na poszukiwania. Teraz widz¹ ciê jako lidera. Prawdopodobnie nie chcesz straciæ swojego specjalnego statusu, prawda?}
{201} {} {Dlaczego uciek³eœ ze spo³ecznoœci?}
{202} {} {Chc¹ mnie straciæ. Wiesz przecie¿. Dlaczego pojawiaj¹ siê te niepotrzebne pytania?}
{203} {} {Muszê wiedzieæ na pewno.}
{204} {} {Lepiej tu zostañ. Poczekaj na mój powrót.}

{210} {} {Jeœli to mój ostatni dzieñ, wola³bym spêdziæ go z tob¹.}
{211} {} {Jeœli to mój ostatni dzieñ, wola³bym go spêdziæ na dnie studni ni¿ obok ciebie.}
{212} {} {Nigdzie nie odchodŸ, wrócê wkrótce.}
{213} {} {Myœlê, ¿e przegapi³em coœ w tej historii. Powiedz mi wiêcej.}
{214} {} {Ok. I tak nie ma poœpiechu.}
{215} {} {Powiedz mi wiêcej.}

{220} {} {Dlaczego jesteœ na siebie z³y?}
{221} {} {Tak jak ty unikn¹³em najeŸdŸców. Ale tylko dlatego, poniewa¿ ukry³em siê przed nimi w piwnicach. Teraz mieszkañcy nie mog¹ mi tego wybaczyæ i uwa¿aj¹ mnie za zdrajcê. Zdrajcy w Villi nigdy nie byli lubiani.}
{222} {} {Jaki rodzaj egzekucji przygotowuj¹?}
{223} {} {Nie wiem dok³adnie, ale ktoœ szepta³ o ukamienowaniu. Robili tak w przesz³oœci. A teraz, po ca³ej tej historii, mog¹ wymyœliæ coœ gorszego.}
{224} {} {Co wiesz o tym miejscu?}
{225} {} {To staro¿ytne ruiny jakiejœ osady. Nasi przodkowie zabrali st¹d ceg³y do budowy swoich domów. Reszta zosta³a zniszczona przez czas. Jak widaæ, prawie nic nie zosta³o...}
{226} {} {[Dalej.]}
{227} {} {Zabawne. Villa istnieje dziêki tym ruinom. Teraz utrzymuj¹ mnie przy ¿yciu. Ale nikt nie wie nic o ich przesz³oœci i ludziach, którzy tu mieszkali. Byæ mo¿e w innych miastach z innym stylem ¿ycia, nie takim jak w Villi, znajdê swoje miejsce.}
{228} {} {Co zamierzasz teraz zrobiæ?}
{229} {} {Nie wiem. Nie mogê siê tu d³ugo ukrywaæ i nie mam dok¹d uciekaæ. S³ysza³em o Rangersach i padlino¿ercach z s¹siedniego miasta. Ale ¿eby tam pojechaæ, potrzebujê zapasów. (gorzki uœmiech) Ale nie mogê wróciæ do Villi.}
{230} {} {Jeœli przyniosê ci trochê prowiantu, opuœciæ te miejsca. Ale nigdy nie wrócisz.}
{231} {} {Wiem! Byæ mo¿e zawsze tego chcia³em, ale ba³em siê przyznaæ. Wiêkszoœæ naszych ludzi nawet nie próbowa³a dowiedzieæ siê niczego o œwiecie zewnêtrznym. Zyli swoim stylem ¿ycia przez dziesiêciolecia i s¹ gotowi rzucaæ kamieniami przy ka¿dej zmianie... Chcê siê uwolniæ, amigo. Daj mi szansê!}
{232} {} {Ok, przyniosê ci trochê prowiantu na podró¿. Zaczekaj tutaj.}
{233} {} {Nie. Moja reputacja jest dla mnie zbyt wa¿na. A poza tym i tak zas³ugujesz na karê. Przygotuj siê, wracamy do spo³ecznoœci.}
{234} {} {Najpierw muszê poznaæ szczegó³y tej historii.}
{1234} {} {Przede wszystkim, to muszê poznaæ szczegó³y tej historii.}
{235} {} {Aby daæ Chrisowi zapasy jedzenia, u¿yj ich na postaci.}
{236} {} {Masz teraz doœæ prowiantu, aby uciec do najbli¿szego miasta.}
{237} {} {Mam nadziejê, ¿e tak. WyjdŸmy na œwie¿e powietrze. Przed wyjœciem chcê siê rozejrzeæ po raz ostatni.}
{238} {} {ChodŸmy.}
{239} {} {Eskortuj Chrisa na plac Villi.}

#GG zabiera Chrisa z miejsca:
{240} {} {Porozmawiamy na zewn¹trz?}
{241} {} {ChodŸ.}
{242} {} {Nie martw siê o mnie, znajdê swoj¹ drogê.}
{243} {} {Cokolwiek powiesz.}
{244} {} {OdprowadŸ Chrisa do ruin, a potem wróæ do Villi.}
{245} {} {No dalej, rób co musisz!}
{1245} {} {No, zrób co musisz!}
{246} {} {Lepiej siê zamknij.}
{247} {} {S³uchaj, ja te¿ nie jestem w nastroju na tê decyzjê.}