{102} {} {Nie naciskaj!}

# Repliki - reputacja> 5
{110} {} {Ochronisz nas, prawda?}
{111} {} {Zabij tych najeŸdŸców! Zabiæ ich wszystkich!}
{112} {} {Nie chcê tu z powrotem najeŸdŸców.}
{113} {} {Wszyscy obcy s¹ Ÿli.}
{114} {} {Chcê zobaczyæ moj¹ mamê!}
# Repliki - reputacja <-5
{115} {} {Przera¿asz mnie bardziej od tych najeŸdŸców.}
{116} {} {OdejdŸ ode mnie! Jesteœ jak bandyta.}
{117} {} {Powiedziano mi, ¿ebym z tob¹ nie rozmawia³.}
{118} {} {Wszyscy z zewn¹trz s¹ ³obuzami. Tak mówi¹ doroœli.}
{119} {} {Chcê zobaczyæ moj¹ mamê!}
# Responses - reputacja od -5 do 5
{120} {} {Jeœli obcy wróc¹, czy ktoœ nas ochroni?}
{121} {} {To by³o przera¿aj¹ce! Wci¹¿ siê trzêsê...}
{122} {} {Obawiam siê, ¿e rabusie znowu przyjd¹.}
{123} {} {Dlaczego osoby z zewn¹trz s¹ takie z³e?}
{124} {} {Chcê zobaczyæ moj¹ mamê!}
{125} {} {Chcesz siê pobawiæ?}
