{100} {} {Widzisz ch³opa.}
{101} {} {Widzisz jednego ze swoich wspó³plemieñców.}
{102} {} {Kiedyœ te¿ ciê popchnê.}
{103} {} {}

# Plywajace repliki
{110} {} {Ktoœ musi wypêdziæ Szakale z pustyni.}
{111} {} {Chcia³bym zobaczyæ, jak te Szakale by³y pêdzone przez pustyniê.}
{112} {} {S³ysza³eœ wieœci o Szakalach? Teraz nikomu nie mo¿na ufaæ. Nawet Rangersom...}

{113} {} {Nie mam nadziei, ¿e po tym, co zrobili, dogadam siê z padlino¿ercami.}
{114} {} {Teraz dranie z Garage City bêd¹ wiedzieæ, jak pomóc naszym wrogom.}
{115} {} {Nie s¹dzê, ¿ebym kiedykolwiek wybaczy³ padlino¿ercom.}

{116} {} {Przyda³aby siê pomoc Rangersów.}
{117} {} {Cholera, nawet Rangersi nie mog¹ sami siê broniæ.}
{118} {} {Rangersi to twardziele. Ale trzeba siê z nimi dzieliæ.}

{119} {} {Nasi wrogowie w Flagpool pewnego dnia dostan¹ za swoje!}
{120} {} {Mówi¹, ¿e we Flagpool jest naprawdê Ÿle. Zaœpiewajmy o tym, amigos!}
{121} {} {Nasza wolnoœæ skoñczy siê, jeœli Flagpool siê rozwinie.}

{122} {} {Karawany przynosz¹ z³e wieœci z po³udniowego wschodu.}
{123} {} {Coœ siê dzieje na po³udniowym wschodzie. Mam nadziejê, ¿e to nas nie dotyczy.}
{124} {} {Wygl¹da na to, ¿e na po³udniowym wschodzie wybuch³a wojna.}

{125} {} {Za³ujê, ¿e Senor Andres wróci³ z niewoli.}
{126} {} {Naszemu nowemu liderowi brakuje dojrza³oêci do przewodzenia spo³ecznoœci.}
{127} {} {Nasz przywódca nie powinien zaprzeczaæ.}

{128} {} {Ktoœ musi uratowaæ Senore Mariê z niewoli.}
{129} {} {Po œmierci Senory Marii bêdzie ciê¿ko.}
{130} {} {Chwa³a niebiosom, Senora Maria te¿ wróci³a do Villi!}

{131} {} {Chwa³a naszemu wybawcy!}
{132} {} {Senor Andres wychowa³ prawdziwego bohatera.}
{133} {} {Senor Andres jest bardzo obiecuj¹cy.}

{134} {} {Cicho! Ten drañ, Senor Andres coœ knuje.}
{135} {} {Senor Andres wychowa³ diab³a.}
{136} {} {W z³ych czasach potrzebujemy silnego lidera.}

{1131} {} {Chwa³a naszemu wybawcy!}
{1132} {} {Senor Andres wychowa³ prawdziw¹ bohaterkê.}
{1133} {} {Andres jest bardzo obiecuj¹cy.}

{1134} {} {Cicho! Ten maniak Senor Andres coœ knuje.}
{1135} {} {Senor Andres wychowa³ diab³a.}
{1136} {} {W z³ych czasach potrzebujemy silnego lidera.}

# Uwagi dotycz¹ce odpowiedzi
{200} {} {Tutaj jesteœ zawsze mile widziany.}
{201} {} {Dziêki za uratowanie nas, bohaterze.}
{202} {} {Jesteœ przyk³adem dla nas wszystkich.}

{210} {} {Mam du¿o do zrobienia, przepraszam.}
{211} {} {Odbudowujemy wioskê, a Ty co robisz?}
{212} {} {Mo¿e mo¿esz przestaæ nas zaczepiaæ i zabraæ siê do pracy?}

{220} {} {Tylko odwa¿ siê tym straszyæ dzieci.}
{221} {} {Trzymaj siê z dala ode mnie!}
{222} {} {Przestraszysz kogoœ t¹ rzecz¹.}
{223} {} {Strasz naszych wrogów tym kawa³kiem ¿elaza, nie nas.}
{224} {} {Jak œmiesz chodziæ po Villi w tej zbroi?}
{225} {} {Czy ta zbroja odstraszy naszych wrogów?}
{226} {} {Nie jest Ci w tym gor¹co?}
{227} {} {Pomó¿ nam lepiej oczyœciæ plantacje.}
{228} {} {Jeœli ta zbroja jest naprawdê tak potê¿na, u¿yj jej do naprawy domów.}
{229} {} {Uwa¿aj na siebie, chodz¹ca beczu³ko! Mieszkaj¹ tu ludzie.}