{100} {} {Widzisz ch³opa.}
{101} {} {Widzisz jednego z ch³opów. Uwa¿nie analizuje osadê.}

{110} {} {Hej, czy ktoœ widzia³ Chrisa?}
{111} {} {Jeœli ktoœ widzia³ Chrisa, niech mi powie.}
{112} {} {Jeœli Chris nie wróci sam, po¿a³uje i tego.}
{113} {} {Hej, ty! Czy mo¿esz mi powiedzieæ, gdzie ukrywa siê Chris?}
{114} {} {Ten ma³y w¹¿ uszed³ zbyt wiele na sucho.}
{115} {} {Wiedzia³em, ¿e Chris zostanie zdmuchniêty.}

{200} {} {Witam naszego wybawcê! Jak siê masz?}
{1200} {} {Witam naszego zbawiciela! Jak siê masz?}
{201} {} {Swietnie. Bywaj.}
{202} {} {Czekaj! Mo¿e du¿o proszê, ale znowu potrzebujemy Twojej pomocy.}
{203} {} {Jakiego rodzaju?}
{204} {} {Tu chodzi o twojego starego przyjaciela Chrisa. Czy wiesz, ¿e ten ma³y w¹¿ ukrywa³ siê w piwnicach podczas nalotu? Podczas gdy my walczyliœmy z najeŸdŸcami i znosiliœmy upokorzenie - ten zdrajca nawet nie zamierza³ nam pomóc!}
{205} {} {Wiêc uciek³?}
{206} {} {Na to wygl¹da. Z pewnoœci¹ ukrywa siê jak ostatnio. ZnajdŸ go i przyprowadŸ z powrotem. Musi odpowiedzieæ przed Rad¹ Wspólnoty. To bardzo wa¿ne.}
{207} {} {Nie jestem tym zainteresowany. Ale jeœli go spotkam, dam ci znaæ, gdzie go szukaæ.}
{208} {} {Poszukam go.}

{210} {} {Czy znalaz³eœ ju¿ Chrisa? By³oby lepiej, gdyby wróci³ i odpowiedzia³ przed Rad¹.}
{211} {} {Jeszcze go nie spotka³em.}
{212} {} {Jak myœlisz, gdzie mo¿e siê ukrywaæ?}
{213} {} {Na pewno nie uciek³ na pustkowia - nie mia³ doœæ ducha i nie by³o innej drogi ucieczki. Przeszukaliœmy piwnice, ale go tam nie znaleŸliœmy. Pozostaje pomyœleæ, ¿e ktoœ go ukrywa, ale kto? Przyjaciele, s¹siedzi i jego m³odszy brat siê nie przyznaj¹.}
{214} {} {Do zobaczenia.}

{220} {} {Chris nie ¿yje. Jego cia³o le¿y w pobliskich ruinach, gdzie siê ukry³.}
{221} {} {Co za wstyd. Lepiej gdyby ka¿dy widzia³ jak umiera. Ale i tak bêdzie to lekcja dla wszystkich innych. Dziêkujemy za wysi³ek, spo³ecznoœæ to docenia.}
{222} {} {Nie ma za co.}
{223} {} {Z twoj¹ pomoc¹ Chris wróci³ do Villi i wkrótce zostanie ukarany za zdradê. Dziêkujemy, spo³ecznoœæ docenia Twoje wysi³ki.}
{224} {} {Nie ma za co.}
{225} {} {Nawiasem mówi¹c, znaleŸliœmy przy nim te zakazane przedmioty. Zdecyduj, co z nimi zrobiæ, nie potrzebujemy obcych technologii. (wrêcza ci stare naboje ró¿nych kalibrów)}
{226} {} {Dobrze, ja... poddam je recyklingowi.}
{227} {} {Pewnie nie ma sensu czekaæ na Chrisa. Prawda?}
{228} {} {Racja. Opuœci³ dolinê i ju¿ tu nie wróci.}
{229} {} {Niech tak bêdzie. Samo jego istnienie mo¿e naruszyæ porz¹dek we wspólnocie. Im dalej jest, tym lepiej.}
{230} {} {Wiêc moja praca jest skoñczona. Z przyjemnoœci¹ zostanê tu jeszcze chwilê.}