{100} {} {Widzisz ch³opa.}
{101} {} {Widzisz mieszkañca Villi.}
{102} {} {Wygl¹da na to, ¿e ktoœ czeka na ciebie przy wyjœciu!}
{103} {} {Umówmy siê - ta rozmowa nie mia³a miejsca.}
{104} {} {Cholera! Ty... Kim jesteœ?}
{105} {} {Mi³o ciê widzieæ.}

{200} {} {Jak idzie poszukiwanie?}
{201} {} {Swietnie. Bywaj.}
{202} {} {Có¿... Szczerze mówi¹c, ja te¿ nie jestem w nastroju na decyzjê Rady. Ale ta historia pos³u¿y jako przyk³ad dla reszty. To najlepsze rozwi¹zanie dla ka¿dego.}
{203} {} {Naprawdê mam tak¹ nadziejê.}
{204} {} {IdŸ do diab³a ze swoimi wymówkami!}

{210} {} {(wychodz¹c z budynku nagle wpadasz na starego znajomego; wygl¹da na to, ¿e specjalnie na ciebie czeka³) No có¿. Mieliœmy wielu zdrajców, a teraz i Ty! Co Ty do cholery robisz? Czy chcesz z³amaæ ca³y nasz styl ¿ycia z powodu jednego zdradzieckiego i sfrustrowanego tchórza?}
{211} {} {Spo³ecznoœæ siê myli. Zabijanie w³asnego ludu to droga do zniszczenia stylu ¿ycia.}

{212} {} {Mo¿e tak... nie wiem! Wszyscy siê zmieniliœmy po tym nalocie. Przed nim ¿yliœmy w pokoju i nikt nie zamierza³ rzucaæ kamieniami w s¹siada. Tylko w dawnych czasach, gdy Villa by³a przebudowywana...}
{213} {} {[Dalej.]}
{214} {} {To tutaj przodkowie zabrali materia³ do budowy domów. I mówi¹, ¿e wtedy ¿ycie by³o napiête, sasiad móg³ okraœæ s¹siada. Prze¿yliœmy ten horror i staliœmy siê du¿¹, z¿yt¹ rodzin¹. Wszystko zmieni³o siê po nalocie.}
{215} {} {W takim razie musisz zrozumieæ, ¿e to nie jest opcja. Puœæ Chrisa.}
{216} {} {Nie mogê! On... powinien byæ przyk³adem... spo³ecznoœæ tak zdecydowa³a...}
{217} {} {Boisz siê. Boisz siê, ¿e Villa siê zmieni.}
{218} {} {Tak! Chris... Przepraszam.}
{219} {} {Ugh, wygl¹da na to, ¿e rozwi¹zaliœmy ten problem.}
{220} {} {Wiêc rób, co musisz. Nie bêdê ci przeszkadzaæ.}
{1220} {} {Wiêc zrób, co musisz. Nie bêdê ci przeszkadzaæ.}
{221} {} {Nie obchodzi mnie, co zdecydowa³a spo³ecznoœæ. Chris bêdzie wolny.}
{222} {} {Spo³ecznoœæ nie wybaczy ci tego. (pluje na twoje stopy i odchodzi)}
{223} {} {No dalej, wracaj do stada, g³upcze...}
{224} {} {Po prostu puœæ Chrisa.}

{230} {} {Wszystko Ÿle zrozumia³eœ - zabieram go na egzekucjê.}
{231} {} {Naprawdê? To dlaczego ma plecak pe³en prowiantu?}
{232} {} {To s¹ moje rzeczy. Niech poniesie je jako karê.}
{233} {} {Hmm... Tak, powinien byæ przyk³adem. Nic osobistego, Chris. Spo³ecznoœæ zdecydowa³a. ChodŸmy na egzekucjê.}
{234} {} {[Wróæ do Villi]}

{240} {} {Myœl, co chcesz. Wiem co robiê.}
{241} {} {Hmm. Ludzie mówi¹ o tobie. I jak siê okaza³o, nie na pró¿no.}
{242} {} {Hmm. Ludzie mówi¹ o tobie. Ale nikt nie spodziewa³ siê TEGO!}
{243} {} {Cholera, nie chcê byæ wyrzutkiem w mojej ojczyŸnie. Ok, zabierz go na egzekucjê, nie bêdê ci przeszkadza³.}
{244} {} {Nie obchodzi mnie, co myœli spo³ecznoœæ. Chris bêdzie wolny.}