{100} {} {Widzisz nianiê.}
{101} {} {Widzisz Anitê, jedn¹ z wielu ciotek. Wygl¹da na to, ¿e jest bardzo spiêta.}
{102} {} {Mo¿e grzeczniej?}
{103} {} {Dodajesz now¹ misjê do swojego Pip-Boya.}
{104} {} {Wynoœ siê st¹d, ¿elazny dziwaku! Nie dotykaj dzieci!}

{200} {} {Mi³o ciê widzieæ.}
{201} {} {Najpierw najeŸdŸcy, teraz ty.}
{202} {} {Nic, do widzenia.}
{203} {} {Rozumiem. PA.}
{204} {} {}
{205} {} {}
{206} {} {? Och, jakie masz szczêœcie. NajeŸdŸcy porwali po³owê wioski.}
{207} {} {Nie martw siê, zrobiê co w mojej mocy, aby j¹ odzyskaæ.}
{208} {} {Wiem.}
{209} {} {Rozumiem to i bez ciebie, lepiej powiedz coœ po¿ytecznego.}

{210} {} {Opowiedz mi o nalocie.}
{211} {} {Nie chcê pamietaæ tego horroru! Nieznajomi weszli w t³um, bili naszych mê¿ów, wywa¿ali drzwi i okna... Nie mog³am nawet uciec ze strachu! Dzieci nadal nie mog¹ dojœæ do siebie.}
{212} {} {Jak siê maj¹ dzieci?}
{213} {} {Nadal s¹ w szoku. Muszê siê nimi opiekowaæ, chocia¿ mi wsparcie te¿ by nie zaszkodzi³o... To straszne!}
{214} {} {Czy jest coœ, w czym mogê ci pomóc?}
{215} {} {Tak, chyba... Eden by³ tak przera¿ony po stracie rodziców, ¿e uciek³ i teraz gdzieœ siê ukrywa. Nie mogê zostawiæ reszty dzieciaków, ¿eby go szukaæ. Poszukaj go, dobrze?}
{216} {} {Gdzie mam zacz¹æ szukaæ?}
{217} {} {Mo¿e byæ wszêdzie!}
{218} {} {Czy nadal ma gdzieœ swoj¹ ulubion¹ kryjówkê?}
{219} {} {Có¿, pamiêtam, ¿e za³o¿y³ swoj¹ "bazê" w jakiejœ chacie na plantacji.}
{220} {} {Zobaczê, co mogê zrobiæ.}
{221} {} {Opowiedz mi jeszcze raz o Edenie.}
{222} {} {Eden by³ tak przera¿ony po stracie rodziców, ¿e uciek³ i teraz gdzieœ siê ukrywa. Obawiam siê, ¿e mo¿e mieæ wiêcej k³opotów.}
{223} {} {Z³e wieœci - Eden odszed³.}
{224} {} {(mdleje) Ach... Domyœlam siê, ¿e by³o za póŸno... to wszystko moja wina... gdybym mog³a go powstrzymaæ na czas...}
{225} {} {Zrobiliœmy, co mogliœmy.}
{226} {} {Jak widzisz, Eden wróci³.}
{227} {} {Umar³by bez twojej pomocy! Teraz moja kolej, aby siê nim zaj¹æ. (ze ³zami w oczach) Dziêkujê bardzo!}
{228} {} {W porz¹dku, wszyscy jesteœmy rodzin¹.}
{229} {} {Wola³bym kawa³ek soczystego miêsa, ale wystarczy mi tylko „dziekuje”.}
{1229} {} {Wola³abym kawa³ek soczystego miêsa, ale bêdê musia³a zadowoliæ siê tylko „dziekuje”.}
{230} {} {Ach, to nie wszystko. Popatrz, mam coœ dla ciebie. Dzieci to znalaz³y, wygl¹da na to, ¿e jeden z bandytów to upuœci³.}
{1230} {} {Ach, to nie wszystko. Popatrz, mam coœ dla ciebie. Dzieci to znalaz³y, wygl¹da na to, ¿e jeden z porywaczy to upuœci³.}
{231} {} {Wygl¹da na dosyæ cenne. Tak, mo¿e mi siê przydaæ.}
{232} {} {Dobrze, ¿e ciê mamy... A tak, dzieciaki to znalaz³y, wygl¹da na to, ¿e jeden z bandytów to upuœci³. WeŸ to, mo¿e ci to pomo¿e.}
{233} {} {Nadal maj¹ koszmary. Próbujê im pomóc, podczas gdy inni s¹ zajêci odbudow¹ wioski. Chocia¿ czasami samo wsparcie i mi by nie zaszkodzi³o. To siê nie mo¿e powtórzyæ!}