{100} {} {Widzisz ch³opa.}
{101} {} {Widzisz jednego ze swoich wspó³plemieñców, któremu uda³o siê powróciæ z Flagpool.}
{102} {} {Hej, czy twoja samoocena wzros³a po twoich wyczynach?}
{103} {} {Trzymaj siê z dala, kawa³ku ¿elaza! Mogê stan¹æ w obronie w³asnej!}

{110} {} {Co za ba³agan!}
{111} {} {Trudno bêdzie to naprawiæ bez czêœci.}
{112} {} {Gdyby tylko bohaterskie postacie nie przychodzi³y do nas.}
{113} {} {Wydaje mi siê, ¿e ktoœ kopie w mojej piwnicy.}
{114} {} {Lepiej zamknê piwnicê.}
{115} {} {Bêdziemy musieli zmieniæ drzwi.}
{116} {} {Cholerni najeŸdŸcy, odpowiedz¹ za wszystko!}
{117} {} {Gdybym prowadzi³ Villê, to nigdy by siê nie wydarzy³o!}
{118} {} {Gdzie by³o grono starszych?}
{119} {} {Nigdy wiêcej nie zaufam osobom z zewn¹trz.}

{200} {} {Czeœæ. Dziêki za uratowanie mojego ty³ka. Teraz, jeœli pozwolisz, zajmê siê napraw¹ mojego domu.}
{201} {} {Do widzenia.}
{202} {} {Przepraszam, by³em w twojej piwnicy i wzi¹³em trochê zapasów.}
{1202} {} {Przepraszam, by³am w twojej piwnicy i wziê³am trochê zapasów.}
{203} {} {Wiêc to ty. Zag³êbianie siê w rzeczy innych ludzi nie jest z Twojej strony zbyt mi³e. Nie mo¿esz tego zrozumieæ?}
{204} {} {To by³o mi potrzebne, ¿eby ciê uratowaæ.}
{205} {} {Nie rozpêdzaj siê! Bez wzglêdu na to, jakim jesteœ bohaterem i jakich dokona³eœ wyczynów, nie mo¿esz tak po prostu okradaæ ludzi. Rozumiesz to?}
{1205} {} {Nie rozpêdzaj siê! Bez wzglêdu na to, jak¹ jesteœ bohaterk¹ i bez wzglêdu na to, jakich czynów dokona³aœ, nie mo¿esz tak po prostu okradaæ ludzi. Rozumiesz?}
{206} {} {Rusz siê.}
{207} {} {Rozumiem.}
{208} {} {Mam jeszcze du¿o do zrobienia. Czy jest coœ, w czym mogê pomóc?}
{209} {} {Mam kilka rzeczy w mojej piwnicy. ZejdŸ na dó³ i zobacz, co ci siê przyda. Wejœcie do piwnicy przykryte jest skrzyniami w spi¿arni.}
{210} {} {Dziêkujê.}
