{101} {} {Widzisz swojego wspó³plemieñca. Jego cia³o to jedna ci¹g³a rana. }
{102} {} {Widzisz wspó³plemieñca. Po zabiegu dochodzi do siebie.}
{103} {} {Nie mo¿esz sam leczyæ takich ran. Musisz poszukaæ lekarstw.}
{104} {} {Tutaj wymagana jest operacja.}

{105} {} {Dziêki, amigo. Czujê siê o wiele lepiej.}
{106} {} {Dziêki, amigo. Czujê siê o wiele lepiej.}
{107} {} {Uh, dziêki, amigo. Czujê siê o wiele lepiej. Ale i tak nie ufam tej starej chemii.}
{108} {} {Medycyna obcych jest lepsza ni¿ nasze ok³ady. Nie mo¿esz siê z tym k³óciæ!}

{110} {} {Bandyci... myœlê, ¿e z³amali mi ¿ebro...}

{200} {} {Pozdrowienia dla naszego zbawiciela!}
{201} {} {Do widzenia.}
{202} {} {Podczas leczenia nie ufa³eœ przedwojennej medycynie. Dlaczego?}
{203} {} {Przodkowie zawsze uczyli nas, aby nie ufaæ rzeczom Starego Swiata. Powiedzieli, ¿e te rzeczy s¹ przeklête przez duchy i s¹ niebezpieczne. A teraz jedna z nich uratowa³a mi ¿ycie. Tak sobie myœlê, czy ja te¿ nie bêdê teraz przeklêty?}
{204} {} {Ca³e szczêœcie nadal ¿yjesz. Odpocznij teraz.}
{205} {} {Ten obcy z pewnoœci¹ zna siê na rzeczy. Ale przodkowie zawsze nauczali, ¿e nie mo¿na ufaæ rzeczom i tradycjom Starego Swiata. Teraz wszyscy pomyœl¹, ¿e jestem przeklêty przez duchy!}
{206} {} {Ca³e szczêœcie nadal ¿yjesz. Odpocznij teraz.}
{207} {} {Jak siê czujesz po zabiegu?}
{208} {} {Myœla³em, ¿e umrê. Ale teraz wszystko jest w porz¹dku. Robisz cuda. Przecie¿ w Villi rzadko prze¿ywa³y osoby ze z³amaniami. Jak mogliœmy wczeœniej nie zauwa¿yæ, ¿e masz taki dar?}
{209} {} {Najwa¿niejsze, ¿e ¿yjesz. Odpocznij teraz.}

{210} {} {Co wiesz o œwiecie poza Vill¹?}
{211} {} {Niewiele. Przez ca³e ¿ycie nie wyszed³em poza nasz¹ pustyniê. I wcale tego nie ¿a³ujê. Porozmawiaj z Jose, on coœ wie, bo nierzadko robi interesy z nieznajomymi.}
{212} {} {Wyruszam na wyprawê. Jak mo¿esz mi pomóc?}
{213} {} {Jak widzisz, jestem ma³o przydatny. Ale mogê Ci to daæ (wyjmuje garœæ nabojów ró¿nych kalibrów). Jeden z najeŸdŸców upuœci³ to podczas ataku, a ja to schowa³em. Mam nadziejê, ¿e ci siê to przyda.}
{214} {} {Dziêki.}
{215} {} {Czy znasz tych, którzy byli poza Vill¹?}
{216} {} {Co ty! Kto przy zdrowych zmys³ach opuœci³by swój dom i poszed³ na parn¹ pustyniê?}
{217} {} {Có¿, tak, muszê popracowaæ nad czymœ. Czeœæ.}