{100} {} {Widzisz Edena.}
{101} {} {Widzisz ch³opca o imieniu Eden. Wydaje siê dziki i przestraszony.}
{102} {} {* cicho kiwa g³ow¹ *}
{103} {} {Eden wróci³ do Villi.}

{200} {} {(Patrzy na ciebie ze strachem, nic nie mówi¹c)}
{201} {} {Hej, czy nie wiesz, ¿e spacerowanie tu samemu jest niebezpieczne?}
{202} {} {(wci¹¿ siê na ciebie gapi)}
{203} {} {S³uchaj, teraz wszystkim jest ciê¿ko. Ale razem wszystko prze¿yjemy. Dalej - chodŸmy do wioski.}
{204} {} {Nie martw siê, zajmê siê tob¹.}
{205} {} {Wiêc stój tutaj i czekaj sobie, ma³y. Ja wychodzê.}
{206} {} {Tu jest zbyt niebezpiecznie. Wrócimy do Villi?}
{207} {} {Hej, mam tutaj soczystego mutaowoca. Prawdopodobnie jesteœ g³odny, prawda?}
{208} {} {Zostañ tutaj, wrócê wkrótce.}
{209} {} {Ups, wygl¹da na to, ¿e wypad³ mi z kieszeni. Zostañ tutaj, wrócê wkrótce.}

{210} {} {(cicho krêci g³ow¹ i odsuwa siê od ciebie)}
{211} {} {Ach! (Wygl¹da na to, ¿e Eden jest teraz gotowy, aby za tob¹ iœæ)}
{212} {} {Dobrze, chodŸ za mn¹.}
