{100} {} {Widzisz Jose.}
{101} {} {Widzisz swojego wuja. Jak zawsze portretuje pogodn¹, dobroduszn¹ osobê, ale teraz nie wygl¹da za dobrze.}
{102} {} {Dzisiaj nie jest twój dzieñ, Jose.}
{103} {} {Dodajesz now¹ misjê do swojego Pip-Boya.}
{104} {} {Santo cielo! Dlaczego tak mnie straszysz? Na tak¹ zbrojê nie ma miejsca w spokojnej Villi.}
{105} {} {Jesteœ opêtany przez demony pustyni. Opuœæ wioskê. Zostaw nas w spokoju.}
{1105} {} {Jesteœ opêtana przez demony pustyni. Opuœæ wioskê. Zostaw nas w spokoju.}

# Pierwszy dialog
{200} {} {Ech, drogi amigo, jak siê cieszê, ¿e przynajmniej ciebie cholerny los zostawi³ z nami! Ay-yay-yay, cholerni najeŸdŸcy. Twoje szczêœcie, ¿e ciê tu nie by³o.}
{201} {} {Wujku Jose, opowiedz mi o nalocie.}
{202} {} {Ech, te diab³y przysz³y w t³umie, kiedy nikt nie by³ gotowy. Ktoœ zosta³ natychmiast zwi¹zany, a komuœ innemu uda³o siê ukryæ w swoim domu. Twój ojciec i mê¿czyŸni schronili siê w ratuszu. Wyci¹gnê³a ich dopiero burza o³owiu. Strzelanina nie by³a ¿artem. Umarli wci¹¿ tam le¿¹, nie ma nikogo, kto by ich pochowa³.}
{203} {} {Powiedz mi wiêcej.}
{204} {} {A potem wszyscy zostali zaprowadzeni na plac. Ka¿dy by³ oceniany jako worek kukurydzy. Silniejszych zabrano osobno, resztê zagoniono do domu i zamkniêto.}
{205} {} {Co sta³o siê póŸniej?}

{206} {} {NajeŸdŸcy nie spali w nocy - grabili Villê, jedli i pili jakby mia³o nie byæ jutra. A rano zabrali nasz lud i udali siê na pustkowiê, na wschód. Od tego czasu jest tu cicho i spokojnie. Siedzimy i li¿emy nasze rany.}
{207} {} {Kim byli ci rabusie?}
{208} {} {Mówisz, ¿e poszli na wschód. Gdzie dok³adniej?}
{209} {} {Dlaczego porywacze zabrali naszych ludzi?}
{210} {} {No có¿, myœlê, ¿e czas bym to rozwi¹za³.}
{211} {} {Wszelaki mot³och z pustkowi. Jednego pozna³em, by³ z Garage City, ale o wiêkszoœci z nich nawet nie s³ysza³em.}
{212} {} {Wiem tylko o Garage City w tym kierunku. Porywacze prawdopodobnie bêd¹ tam siê zatrzymywaæ na noc.}
{213} {} {To, czego stary Jose nie wie, to ich plany. Ale wiesz co, wygl¹da na to, ¿e bêd¹ jeszcze dzia³aæ. Ale nie wiem, gdzie i dlaczego.}
{214} {} {A moi rodzice?}
{215} {} {Przykro mi, ich te¿ zabrali. I twojego padre. I madre te¿. Zostali tylko starcy i dzieci.}
{216} {} {Zostaw swój g³upi optymizm. Muszê wiedzieæ, co siê tutaj sta³o.}
{217} {} {To okropne!}

{220} {} {To s¹ s³owa prawdziwego Valiente Guerrero! Co zamierzasz teraz zrobiæ? Zaczniesz œcigaæ najeŸdŸców? S¹ ju¿ daleko.}
{221} {} {Jakie rady mo¿esz mi daæ?}
{222} {} {Najpierw opowiedz mi jeszcze raz o nalocie.}
{223} {} {Có¿, najpierw sprawdŸ Garage City. To okropne miejsce, ale porywacze na pewno tam zajrz¹. Zapytaj miejscowych, s¹ gadatliwi, jeœli wiesz jak pytaæ.}
{224} {} {Czy mo¿esz mi pomóc?}
{225} {} {Uwa¿aj na tych ludzi, oni sprzedadz¹ nawet w³asn¹ matkê dla zysku. Tutaj, zabierz te owoce na drogê i trochê m¹ki kukurydzianej. Mog¹ uratowaæ Ci ¿ycie.}
{226} {} {Dziêki Jose.}
{227} {} {Nie ma za co. Ci porywacze zabrali wszystko, co mogli znaleŸæ. Dajê Ci nasze ostatnie zapasy. Wykorzystaj je m¹drze.}
{228} {} {Czy to wszystko? Ale z ciebie chytrus.}
{229} {} {Hej, najeŸdŸcy zabrali wszystko, co mogli znaleŸæ. Dajê Ci nasze ostatnie zapasy. Wykorzystaj je m¹drze.}
{230} {} {Ma³o, Jose. Potrzeba mi wiêcej.}
{231} {} {Czy zamierzasz zabraæ wszystko i zostawiæ drogiego wujka bez jakiegokolwiek jedzenia? Do-obra, trzymaj. Ale nie mogê daæ nic wiêcej. Ci porywacze zabrali wszystko, co mogli znaleŸæ.}
{232} {} {Ci bandyci zabrali wszystko, co mogli znaleŸæ. Dajê Ci ostatnie zapasy. Wykorzystaj je m¹drze.}
{233} {} {Dobra, bêdê musia³ sam o siebie zadbaæ i ocaliæ nasz lud. Adios, wujku Jose!}
{234} {} {Rozumiem.}

{240} {} {Chwa³a niebiosom, wróci³eœ i przyprowadzi³eœ innych ze sob¹!}
{1240} {} {Chwa³a niebiosom, wróci³aœ i przyprowadzi³aœ innych ze sob¹!}
{241} {} {Tak, to by³a trudna podró¿. Wiesz, poza Vill¹ jest ogromny œwiat. Zawsze na pytania o niego zbywano mnie cisz¹.}
{242} {} {Ty te¿ lepiej b¹dŸ cicho, amigo. Obcy maj¹ swoj¹ prawdê, a my swoj¹. I nie zrozumiemy siê nawzajem. Dlatego ¿yjemy w izolacji od reszty. Aby nikt nas nie zszarga³, nikt nie narzuca³ nam w³asnych regu³. Wiesz ju¿, co zrobi³ ten nalot. Ta historia nie mo¿e siê powtórzyæ, prawda?}
{243} {} {Pomyœlê o twoich s³owach, Jose.}

# Powtarzajacy siê dialog
{250} {} {Mi³o ciê widzieæ, amigo.}
{251} {} {Amigo, nie chodŸ tu bezczynnie. Zajmij siê czymœ, co?}
{252} {} {Muszê iœæ.}

{253} {} {Jest kilka pytañ... Nie, wiele pytañ.}
{254} {} {Pytaj o cokolwiek.}
{255} {} {Co wiesz o œwiecie poza Vill¹?}
{256} {} {Czy interesowa³eœ siê kiedyœ piwnicami Villi?}
{257} {} {Czy chcesz iœæ ze mn¹?}
{258} {} {}
{259} {} {Kolejne pytanie.}

{260} {} {Dzikie miejsca na pustyni. Na pó³nocy s¹ kanibalistyczne dzikusy, na wschodzie znajduje siê wysypisko œmieci, jest jeszcze kilka ma³ych wiosek i obozów Rangersów. Kr¹¿y te¿ plotka o jakimœ du¿ym mieœcie, ale ja sam nigdy nie by³em dalej ni¿ Garage City.}
{261} {} {Dlaczego nazywasz otoczenie dzikim?}
{262} {} {Od lat staramy siê nie spotykaæ z nieznajomymi. Tylko wtedy, gdy los nas do tego zmusza przechodzimy do handlu. Nieznajomym nie mo¿na ufaæ, zwykle nie maj¹ ani rodzin, ani domów. Czy z takimi mo¿na siê przyjaŸniæ? Nie, to zwyk³e dzikusy. Wiêc twój ojciec odpêdza³ wszystkich nieznajomych.}
{263} {} {Wygl¹da na to, ¿e wiedza Villi o otaczaj¹cym j¹ œwiecie jest powa¿nie ograniczona. Nie mo¿na tego zmieniæ?}
{264} {} {Czy nie masz doœæ bandytów? A dzikie kanibale? A rabusie? Nie, nie bez powodu odgradzamy siê od obcych. Przecie¿ tam, na pustkowiach, ludzie nie ¿yj¹ tylko staraj¹ siê prze¿yæ. Prze¿ycie to nie ¿ycie.}
{265} {} {Opowiedz mi o dzikusach z pó³nocy.}
{266} {} {Szakale, jak je nazywamy. S¹ tak dzicy, ¿e nie znaj¹ nawet ludzkiego jêzyka. Mówi¹ te¿, ¿e wszyscy s¹ kanibalami. Na szczêœcie nie podchodz¹ do nas, ale padlino¿ercy z s¹siedniego miasteczka czêsto o nich rozmawiali. Lepiej trzymaj siê z dala od tych dzikusów.}
{267} {} {Kim s¹ Rangersi?}
{268} {} {Twardzi i pewni siebie. Mówi¹, ¿e chroni¹ nas przed z³oczyñcami, ale kto wie czego chc¹ naprawdê? Czasem przychodz¹, ¿eby siê pokazaæ, ale my sobie poradzimy bez ich pomocy... wiesz, teraz taka pomoc by nam siê jednak bardzo przyda³a.}
{269} {} {Jeœli ty nie by³eœ daleko poza Vill¹, to kto?}
{270} {} {Na przyk³ad twój wujek Miguel. Kiedyœ pok³óci³ siê z twoim ojcem i opuœci³ Villê. Nie s³ysza³em o nim od lat.}
{271} {} {Dlaczego siê pok³ócili?}
{272} {} {Spierali siê o to, jak Villa postêpuje z nieznajomymi. Jeden uwa¿a³, ¿e trzeba ich odpêdzaæ, a drugi proponowa³ robiæ z nimi interesy. Nigdy nie znaleŸli wspólnego jêzyka w tej kwestii. Chocia¿ wczeœniej obaj siê raczej dogadywali.}

{273} {} {Opowiedz mi o s¹siednim mieœcie.}
{274} {} {Garage City? Z³e miasto i Ÿli ludzie.}
{275} {} {Jacy ludzie tam mieszkaj¹?}
{276} {} {Scavengers, albo po prostu padlino¿ercy. Nazywaj¹ siebie tak. Spaceruj¹ po ruinach w poszukiwaniu czegoœ cennego. Uwa¿aj na nich - wszyscy s¹ oszustami i bandytami.}
{277} {} {Gdzie móg³ pójœæ Miguel?}
{278} {} {Pamiêtam, ¿e chcia³ odwiedziæ to du¿e miasto, o którym tyle siê mówi. Ale obawiam siê, ¿e w piaskach znalaz³ tylko œmieræ.}
{279} {} {Sk¹d wiesz o Garage City?}
{280} {} {Hej, jestem g³ównym handlarzem z nieznajomymi w Villi. Kto powinien wiedzieæ lepiej ode mnie? Czasami przyje¿d¿aj¹ stamt¹d karawany, zamienimy kilka s³ów i siê rozchodzimy.}
{281} {} {Jak wygl¹da relacja miêdzy Vill¹ a Garage City?}
{282} {} {Ojciec jeszcze ci nie powiedzia³, prawda? Mieszkaj¹ tam Ÿli ludzie. Ale czasem musimy z nimi handlowaæ. Dajemy im jedzenie, a oni daj¹ nam narzêdzia i pomagaj¹ w naprawach. Na tym koñczy siê ca³a nasza „relacja”.}
{283} {} {Wygl¹da na to, ¿e nie lubisz tego miasta.}
{284} {} {Znasz starego Jose - ktoœ jest dla mnie dobry - ja dla niego te¿. A ci g³ównie handluj¹ nieuczciwie, czasem chc¹ kraœæ i s¹ strasznie wulgarni. Do tego ich opinie o nas nie s¹ lepsze. Po prostu zazdroszcz¹ nam, ¿e ¿yjemy lepiej od nich.}
{285} {} {}
{286} {} {}
{287} {} {(krêci g³ow¹ ze smutkiem) Eh-eh, amigo, jak to cholerne pustkowiê ciê zmieni³o, jak ty wygl¹dasz?! Nie boli ciê to? Có¿, pewnie tak. Najwa¿niejsze, ¿eby siê nie martwiæ - wszyscy jesteœmy tej samej krwi, damy radê.}
{288} {} {Dziêki Jose. Jakoœ siê pogodzê z t¹ skór¹.}
{289} {} {Masz problem, g³adkoskóry? Nie potrzebujê twojej litoœci, wiêc lepiej siê zamknij.}

{290} {} {O czym ty mówisz? Przechowujemy tam zbo¿e. Ach, babcia Adonsia pewnie szepta³a ci do ucha te swoje ró¿ne historie, co? Hehe, zapomnij, nic tam nie ma.}
{291} {} {Wiêc jak wyjaœnisz ten kombinezon i komputer w rêkawie?}
{292} {} {Hmm? Znalaz³eœ to pod ratuszem? W takim razie porozmawiaj ze swoim ojcem. Jose nic nie wie.}
{1292} {} {Hmm? Znalaz³aœ to pod ratuszem? W takim razie porozmawiaj ze swoim ojcem. Jose nic nie wie.}
{293} {} {Wujku Jose, zdecydowanie k³amiesz.}
{294} {} {Hej amigo, doœæ tego! Jestem tylko kupcem z obola³¹ nog¹, nie mówi¹ mi o tajemnicach. Tak, wiem, ¿e ojciec trzyma³ tajemnice w piwnicy. I ¿e te rodzinne pami¹tki by³y tam przechowywane, ale to nie moja sprawa, rozumiesz?}
{295} {} {Poszed³bym z tob¹ wszêdzie, ale przez strza³ê w kolano... Sam rozumiesz, nie z³oœæ siê, sam sobie z tym poradzisz. Wierzê w Ciebie. Ty i ja jesteœmy tej samej krwi, hej!}
{296} {} {Jose, nie udawaj.}
{297} {} {He?}
{298} {} {Có¿, tyle siê wydarzy³o... Niewa¿ne, zapomnij o tym.}
{299} {} {Nie musisz zgrywaæ wiecznego optymisty. Ludzie umierali, inni zostali zmuszeni do niewolnictwa, Villa zosta³a zdruzgotana... Przestañ udawaæ, ¿e nic ci nie jest.}
{300} {} {(przez dr¿¹ce usta) Amigo... dlaczego jesteœ taki...}
{301} {} {A teraz p³acz...}
{302} {} {W porz¹dku, wujku, po prostu daj upust swoim uczuciom, nie trzymaj ich w œrodku...}
{303} {} {O czym ty mówisz?}

#Tasks
{310} {} {Czy jest coœ, co mogê zrobiæ, zanim pójdê na pustkowia?}
{311} {} {Chcesz pomóc w odbudowie Villi? Jakoœ sobie poradzimy, Twoje zadanie jest wa¿niejsze.}
{312} {} {Coœ jeszcze?}
{313} {} {Na plantacjach rozgoœci³o siê paru nieznajomych bez naszego pozwolenia. By³oby mi³o siê ich pozbyæ.}
{314} {} {Wiêcej?}
{315} {} {NajeŸdŸcy równie¿ zepsuli stacjê meteorologiczn¹. Nale¿y j¹ naprawiæ. Na pewno w s¹siednim mieœcie bêd¹ czêœci zamienne.}
{316} {} {Czy to wszystko?}
{317} {} {Nie mam innych zadañ dla Ciebie.}
{318} {} {Szabrownicy z plantacji nie s¹ ju¿ problemem.}
{319} {} {Uda³o ci siê! Przera¿aj¹ce jest nawet wyobra¿anie sobie, jak ta historia zakoñczy³aby siê bez twojej interwencji. Dobrze, ¿e Villa ciê ma.}
{320} {} {Do widzenia.}
{321} {} {Stacja meteorologiczna zosta³a naprawiona.}
{322} {} {Dobra wiadomoœæ! Nie moglibyœmy dokonaæ naprawy bez Ciebie. Dziêkujê Ci.}
{323} {} {Do widzenia.}

#Hazard
{350} {} {Wujku Jose, wiem, ¿e lubisz hazard. Mo¿e partyjkê koœci?}
{351} {} {Koœci? Co ty wygadujesz! Musisz ocaliæ naszych ludzi! Kiedy wróc¹ do Villi, wtedy z przyjemnoœci¹ rzucê koœæmi przy stole do gry.}
{352} {} {W takim razie chwilowo zapomnijmy o grach i porozmawiajmy o czymœ innym.}
{353} {} {Masz ca³kowit¹ racjê, muszê siê poœpieszyæ.}
{354} {} {Nie mów mi, co mam robiæ. Jednak i tak nie chcia³em w nic graæ.}
{355} {} {Koœci? Co ty wygadujesz! Z drugiej strony, jeœli pomyœlê o koœciach... po powrocie naszych ludzi, przyda³oby mi siê trochê odprê¿enia. Ale pamiêtaj - nie poddam siê.}
{356} {} {Ok, wyjmij planszê i roz³ó¿ koœci...}
{357} {} {Zabawa z tob¹ to tylko marnowanie czasu. Porozmawiajmy.}
{358} {} {Wiesz, to nie jest najlepszy czas. Wrócê, ¿eby zagraæ póŸniej.}
{359} {} {Udaje ci siê pokonaæ jednego z najlepszych graczy Villi i awansujesz.}
{360} {} {}
{361} {} {Przegrywasz. Na pewni nie jest to pierwszy ani ostatni raz.}