{110} {} {Zli ludzie nie wróc¹? Prawda?}
{111} {} {. ... .}
{112} {} {Twoje przybycie w pancerzu wspomaganym zaalarmowa³o lokaln¹ ludnoœæ.}

{200} {} {(dziewczyna patrzy na twoj¹ ¿elazn¹ zbrojê z odrêtwieniem, nie wiedz¹c, czy podziwiaæ ten widok, czy krzyczeæ z przera¿enia)}
{201} {} {Witaj dziecko. Od teraz Wielki Zelazny Obroñca stanie siê waszym obroñc¹. A Ÿli ludzie nie odwa¿¹ siê tu wiêcej wtr¹caæ.}
{202} {} {(jej oczy rozszerzaj¹ siê z podziwu, potem ucieka, by porozmawiaæ o Wielkim Zelaznym Obroñcy)}
{203} {} {Nie bój siê ju¿, dziecko. Jesteœ w dobrych rêkach.}
{204} {} {Tak, uciekaj, powiedz wszystkim co widzia³aœ, ma³a p³otko.}
{205} {} {[Ignoruj i idŸ dalej]}

{210} {} {Na co siê gapisz? Zmia¿d¿ê ka¿dego, kto popatrzy siê na mnie niew³aœciwie!}
{211} {} {Ah-ah! El Diablo! El Diablo!}
{212} {} {Ech, m³ode pokolenie sta³o siê takie kapryœne...}
{213} {} {}
{214} {} {[Zignoruj i idŸ dalej]}