{100} {} {Widzisz marudera.}
{101} {} {Widzisz kogoœ z zewn¹trz przeszukuj¹cego okolicê w poszukiwaniu cennych przedmiotów.}

{110} {} {Wychodzimy. Nawet nie myœl o gonieniu nas.}
{111} {} {Wychodzimy, tym razem. Ale nastêpnym...}
{112} {} {To wszystko, czego chcieliœmy.}
{113} {} {Nie mamy tu nic innego do roboty.}

{200} {} {Hej! Czy jesteœ st¹d? W takim razie powinieneœ wiedzieæ, gdzie s¹ klucze do tego hangaru.}
{1200} {} {Hej! Czy jesteœ st¹d? W takim razie powinnaœ wiedzieæ, gdzie s¹ klucze do tego hangaru.}
{201} {} {Co ci zale¿y na tym hangarze?}
{202} {} {Wiemy, ¿e jest tam du¿o m¹ki kukurydzianej. I to jedyny hangar, który nie zosta³ spl¹drowany. Wiêc szybko znajdŸ klucze, przynieœ nam trochê m¹ki, a potem wyjdziemy st¹d, nikomu nie przeszkadzaj¹c.}
{203} {} {Czy ta m¹ka kukurydziana jest dla Ciebie naprawdê taka cenna?}
{204} {} {Nie wiesz nic o klêsce g³odu na Pustkowiu? Wœród ja³owych terenów tylko Ty mo¿esz uprawiaæ roœliny. Mówi¹, ¿e zap³adniasz ziemie ludzk¹ krwi¹. Ale wiesz co - nie obchodzi mnie to. Daj nam tylko m¹kê i odejdziemy. Jasne?}
{205} {} {Wiêc nie bra³eœ udzia³u w nalocie?}
{206} {} {Nie. S³yszeliœmy o nalocie i przyszliœmy zabraæ to, co po nim zosta³o. Nie nale¿y marnowaæ zapasów o których zapomniano.}
{207} {} {Jeœli dam ci ca³¹ m¹kê z tego hangaru, odejdziecie?}
{208} {} {Dajê ci s³owo. Dziesiêæ worków nam wystarczy, wiêcej ju¿ nie zabierzemy.}
{209} {} {Wiêc to Was szukaj¹ do zlinczowania? Na placu rozdawane s¹ ju¿ wid³y.}
{210} {} {Blefujesz. We wsi pozosta³y tylko dzieci i starcy. Kogo powinniœmy siê baæ?}
{211} {} {Tak, starzy ludzie i dzieci. Ale kiedy s¹ w t³umie spokojnie dadz¹ wam radê.}
{212} {} {Cholera! Mówi³em ci, ¿e przyjd¹ po nas. Lepiej wynoœmy siê st¹d...}
{213} {} {Oto 10 worków kukurydzy. Czy to wystarczy, abyœcie poszli z Villi?}
{214} {} {Jasne. Nie chcê, ¿eby szed³ za nami t³um prostaków. Lepiej wynoœmy siê st¹d...}
{215} {} {Daj mi czas, ¿eby to rozgryŸæ. Wrócê.}
{216} {} {Poœpiesz siê...}
{217} {} {Maruderzy spokojnie opuszczaj¹ Villê.}
{218} {} {Przynieœ nam trochê m¹ki, a potem wyjdziemy st¹d nikomu nie przeszkadzaj¹c.}
{219} {} {Nie ¿artujê.}
{220} {} {Wynoœ siê st¹d!}
{221} {} {Zobaczmy, jak to siê skoñczy...}
{222} {} {Ok, rozumiem.}
{223} {} {Villa jest teraz pod ochron¹ Rangersów. Sporo ryzykujesz.}
{224} {} {Rangersi? Tutaj? Niedobrze. Lepiej szybko siê st¹d wynoœmy...}
{225} {} {Tak, powinieneœ siê poœpieszyæ.}
{226} {} {Wynoœ siê. I nie wracaj.}
