{100} {} {Widzisz swoj¹ Madre.}
{101} {} {Widzisz kobietê, któr¹ dobrze znasz, a co wiêcej, swoj¹ matkê.}
{102} {} {Do widzenia mamo. Teraz zajmê siê sob¹.}
{103} {} {Twoja madre wróci³a do Villi.}
{104} {} {Kolejny! Wynoœ siê st¹d! Przestañ straszyæ ludzi.}
{105} {} {}
{106} {} {Oto nasz bohater. Kochamy Ciê.}
{1106} {} {Oto nasza bohaterka. Kochamy Ciê.}
{107} {} {Proszê, idŸ i nie wracaj. Nikt tutaj nie ¿yczy ci krzywdy.}
{108} {} {Uwa¿aj. Kochamy Ciê.}

# Pierwszy dialog
{200} {} {Oto nasz bohater. Ca³a Villa zawdziêcza Ci nasze uratowanie. To by³ prawdziwy wyczyn.}
{1200} {} {Oto nasza bohaterka. Ca³a Villa zawdziêcza Ci nasze uratowanie. To by³ prawdziwy wyczyn.}
{201} {} {Jak dotar³aœ do Villi?}
{202} {} {Droga nie by³a krótka. I by³a bardzo trudna. Uratowa³a nas jednoœæ i solidarnoœæ, w tym mieszkañcy Villi zawsze ró¿nili siê od dzikich.}
{203} {} {Chyba.}
{204} {} {O mój Bo¿e! Co ci zrobi³y te przeklête pustkowia? Twoja skóra jest jak... spalona! Jak siê czujesz? Mo¿esz mówiæ? Ugh, nie wiem, co o tym myœleæ. Wygl¹da na to, ¿e zostaniesz w tej skórze na zawsze. Przykro mi. Ale nie martw siê - na pewno znajdziemy lekarstwo na tê chorobê.}
{205} {} {Ach to, ju¿ przyzwyczajam siê do mojego nowego cia³a.}

# Drugi dialog
{210} {} {Co mogê dla ciebie zrobiæ?}
{211} {} {Nic specjalnego.}
{212} {} {Czy coœ siê sta³o?}

{220} {} {Czy mogê zadaæ delikatne pytanie?}
{221} {} {Oczywiœcie, poniewa¿ mogê byæ z tob¹ szczera?}
{222} {} {Dlaczego reszta œwiata zosta³a ukryta przed wieœniakami? Uda³o mi siê odwiedziæ ró¿ne niezwyk³e miejsca i by³o to... nieoczekiwane doœwiadczenie.}
{223} {} {Ach! Spójrz na Villê. Kiedy Za³o¿yciel sprowadzi³ tu ludzi, by³o to pustkowiê bez ¿ycia. Nasi przodkowie poœwiêcili ca³e swoje ¿ycie, aby przynajmniej coœ jadalnego mog³o tu wyrosn¹æ. Uda³o im siê tylko dziêki wierze w przymierza Za³o¿yciela: pracujcie dla dobra wspólnoty, dzielcie siê tym, co zdobyliœcie ze wszystkimi i nie wpuszczajcie obcych.}
{224} {} {[Pos³uchaj]}
{225} {} {Powiedz mi, czy jest wiele miejsc na zewn¹trz Villi, gdzie kwitn¹ ogrody i ludzie dbaj¹ o siebie nawzajem? W takim razie nie mo¿emy siê niczego nauczyæ od „reszty œwiata”.}
{226} {} {Ale œwiat siê zmienia. Czy uwa¿asz, ¿e Villa nie potrzebuje zmian?}
{227} {} {Jakie zmiany mog³yby tu nast¹piæ? Uprawiaj zbiory i dziel siê nimi z dos³ownie wszystkimi - to jedyna zmiana, jaka mo¿e nast¹piæ w naszej spo³ecznoœci. Oczywiœcie czasami potrzebujemy rzeczy z zewn¹trz, ale zawsze mo¿na je wymieniæ na nasze owoce. Nie zape³niaj g³owy niepotrzebnymi myœlami. Swiat zewnêtrzny zb³¹dzi³ i pod¹¿a z³¹ œcie¿k¹. Któregoœ dnia skoñczy nad przepaœci¹.}
{228} {} {Pomyœlê o twoich s³owach.}
{229} {} {Ok, zapomnij.}
{230} {} {Wiesz, spo³ecznoœæ zamierza ukaraæ Chrisa za tchórzostwo.}
{231} {} {Próbowa³am przekonaæ Radê do z³agodzenia wyroku, ale prawo jest nade mn¹. Oczywiœcie ludzie musz¹ odreagowaæ i zdecydowali siê u¿yæ Chrisa jako celu. Mo¿e tak bêdzie lepiej. W ka¿dym razie nie zaprzeczaj opinii wiêkszoœci.}
{232} {} {Ciekawe, ¿e ciê spotka³em. Czy chcesz mi powiedzieæ wiêcej?}

#Quests
{250} {} {Co jeszcze mogê zrobiæ dla Villi?}
{251} {} {Twój ojciec nadal nie wróci³ z niewoli. Obawiam siê, ¿e ktoœ bêdzie musia³ go poszukaæ. Poza tob¹ nie ma ochotników.}
{252} {} {Co siê z nim sta³o po przybyciu do Flagpool?}
{253} {} {By³ przes³uchiwany przez d³ugi czas, a nastêpnie zabrany do du¿ego miasta zwanego Phoenix. Nie wiem nic wiêcej.}
{254} {} {Zajmê siê tym.}
{255} {} {Zapytaj innych ch³opów. Ka¿dy tutaj potrzebuje pomocy - s³owem lub czynem.}
{256} {} {Ok.}
{257} {} {Padre zmar³. Nie czekaj na niego.}
{258} {} {(wzdycha) Nie mogê uwierzyæ... By³ silnym przywódc¹, ca³a spo³ecznoœæ go uwielbia³a... Czy jesteœ tego pewien? Tym bardziej nie powinniœmy traciæ czasu.}
{259} {} {O czym ty mówisz?}
{260} {} {IdŸ do ratusza. Musisz zebraæ starszych i zdecydowaæ, co dalej. Jesteœ teraz naszym liderem. Podejmuj decyzje ostro¿nie... Ja muszê siê po³o¿yæ. Nie martw siê o mnie.}
{261} {} {Ok, przyjdê.}
{262} {} {Spotka³eœ Sancho i Hugo? Wygl¹da na to, ¿e pozostali w Flagpool, o ile nie zginêli, próbuj¹c uciec.}
{263} {} {Ok.}
{264} {} {Czy mo¿emy jeszcze porozmawiaæ przed rozstaniem?}
{265} {} {Czy mo¿emy jeszcze porozmawiaæ?}

{270} {} {Rada chce wysadziæ kopalniê Flagpool. Jak ci siê podoba ten pomys³?}
{271} {} {Proszê, uwa¿aj na siebie. Nie chcê pozwoliæ ci udaæ siê na tak niebezpieczn¹ misjê. Ale ta kopalnia musi zostaæ zatrzymana. W przeciwnym razie rêce w³aœcicieli niewolników ponownie siêgn¹ do naszej wioski. A my nie mamy si³y, by z tym walczyæ.}
{272} {} {Rozumiem.}
{273} {} {Rada postanowi³a zniszczyæ fabrykê w Garage City. Co o tym myœlisz?}
{274} {} {Padlino¿ercy ju¿ pokazali swoj¹ przekupn¹ naturê. Nie mo¿na im ufaæ, nie darz¹ nas ciep³ymi, s¹siedzkimi uczuciami. Kiedy uruchomi¹ fabrykê, nap³ynie tam strumieñ nowej si³y roboczej. Nie mo¿emy na to pozwoliæ, jeœli chcemy zachowaæ nasz styl ¿ycia i spokojne ¿ycie.}
{275} {} {Rozumiem.}
{276} {} {Co s¹dzisz o sojuszu z Rangersami?}
{277} {} {Potrzebujemy sojuszników i nie ma lepszych kandydatów ni¿ Rangersi. Ale obawiam siê, ¿e bêd¹ ingerowaæ w nasze wewnêtrzne sprawy. Nie mo¿emy na to pozwoliæ. Niech wezm¹ po¿ywienie i ochroni¹ nas przed bandytami. Niech nie dzieje siê nic wiêcej.}
{278} {} {Twoje w¹tpliwoœci s¹ zrozumia³e, Madre.}
{279} {} {Co s¹dzisz o sojuszu z Bractwem Stali?}
{280} {} {Nie mamy wyboru, prawda? Có¿, najwa¿niejsze jest to, ¿ebyœmy prze¿yli. Utrzymanie ludzi przy ¿yciu w takiej sytuacji to nasze g³ówne zadanie.}
{281} {} {Dobra odpowiedŸ, madre.}
{282} {} {Na pewno nie bêdê przeszkadza³.}
{283} {} {Otrzymujesz sta³¹ premiê do szczêœcia.}

{290} {} {Jak by³aœ traktowana w kolonii?}
{291} {} {Tamtejsi ludzie zmusili mnie do pracy, ale potraktowano mnie protekcjonalnie, poniewa¿ jestem kobiet¹. Tego samego nie mo¿na powiedzieæ o mê¿czyznach. Czasami u¿ywali ich z ekstremalnym okrucieñstwem. Jednak oni te¿ nie chcieli straciæ si³y roboczej, wiêc zajmowali siê g³ównie zastraszaniem niewolników.}
{292} {} {A co ze zwyk³ymi mieszkañcami miasta?}
{293} {} {Koloniœci próbowali ze mn¹ nie rozmawiaæ. Myœlê, ¿e oni sami nie s¹ w szczególnie dobrej sytuacji z powodu wysokich podatków. Nic dziwnego, ¿e nawet rodzinny wisiorek, odziedziczony po mojej babci, zosta³ mi odebrany. Chocia¿ nie ma to ¿adnej wartoœci dla kolonistów.}
{294} {} {Dlaczego ktoœ mia³by chcieæ Twojego wisiorka?}
{295} {} {Có¿, powiedzia³, ¿e dostanie za niego „³adne kapsle” od barmana. W¹tpiê, czy by³ wart przynajmniej pó³tora kapsla.}
{296} {} {Przykro mi to s³yszeæ. Mam nadziejê, ¿e stra¿nik dostanie to, na co zas³uguje.}
{297} {} {To tylko rodzinny wisiorek. Mo¿esz o tym zapomnieæ.}
{298} {} {Oto twój wisiorek.}
{299} {} {Ach, dziêki! Szczerze mówi¹c, nie warto by³o ryzykowaæ. A jednak dobrze siê spisa³eœ, zachowa³eœ kawa³ek historii naszej rodziny. Za³ó¿ ten wisiorek. Jest teraz twój. Niech przyniesie ci szczêœcie na szlaku.}