{100} {} {Widzisz wujka Miguela.}
{101} {} {Widzisz, jak twój wujek przyje¿dza z Phoenix.}
{102} {} {Nigdy ciê nie lubi³em... wujku.}
{103} {} {Wujek Miguel wróci³ do Villi.}
{104} {} {Zgadza siê, przyjecha³em pokazaæ wszystkim zaawansowan¹ technologiê. Bêd¹ TACY szczêœliwi...}
{105} {} {Wiêc to jest ta legendarna zbroja wspomagana? Fiu fiu.}

# Pierwszy dialog
{200} {} {Witaj drogi siostrzeñcu. Myœlê, ¿e teraz rozumiem, dlaczego tak bardzo cenisz to miejsce. Jest tu spokojnie, nie jak w wielkim, dusznym mieœcie.}
{1200} {} {Witaj droga siostrzenico. Myœlê, ¿e teraz rozumiem, dlaczego tak bardzo cenisz to miejsce. Jest tu spokojnie, nie jak w wielkim, dusznym mieœcie.}
{201} {} {Wygl¹da³o na to, ¿e gardzisz Vill¹ ca³ym sob¹. Co siê zmieni³o?}
{202} {} {Co ty, doceniam Villê! To wspania³e miejsce i wspaniali ludzie. Chcia³em tylko pokazaæ im, ¿e ich ma³y œwiat jest skazany na zag³adê.}
{203} {} {To dlaczego wróci³eœ?}
{204} {} {Có¿, Phoenix to ju¿ nie to samo. Po pewnym wydarzeniu zaczê³a siê tam prawie wojna domowa. Potem zda³em sobie sprawê, ¿e... myli³em siê w czymœ.}
{205} {} {W czymœ? Tak, zdecydowanie siê w czymœ pomyli³eœ, wujku Miguel. Bywaj.}

{210} {} {Witaj drogi siostrzeñcu.}
{1210} {} {Witaj droga siostrzenico.}
{211} {} {Do widzenia, wujku Miguel.}
