{100} {} {Widzisz brata Chrisa.}
{101} {} {Widzisz ch³opca - to brat Chrisa.}
{102} {} {Jak to kontrolujesz? Ona jest trochê przera¿aj¹ca...}

{200} {} {Czeœæ.}
{201} {} {Do widzenia.}
{202} {} {Co robisz?}
{203} {} {Pomagam w odbudowie domu po nalocie.}
{204} {} {Czy zauwa¿y³eœ coœ niezwyk³ego?}
{205} {} {Tylko te dziwne rzeczy, które wyrzucili najeŸdŸcy. (pokazuje zu¿yte naboje i pare ca³ych nabojów 10 mm)}
{206} {} {Wezmê to. To i tak œmieci.}
{207} {} {Nie, nic.}

{210} {} {Czeœæ, tylko przechodzê...}
{211} {} {Bardziej jakbyœ niós³ komuœ jedzenie.}
{212} {} {Nie k³amiesz? Okej, tym razem w to uwierzê.}
{213} {} {To jedzenie jest dla mnie.}
{214} {} {[SledŸ dok¹d idzie]}
{215} {} {Nie martw siê, wierzê ci.}
{216} {} {Czy wiesz, gdzie jest twój brat Chris?}
{217} {} {Nie. Nie wiem.}
{218} {} {Ok. Bêdê kontynuowaæ poszukiwanie.}
