{100} {} {Widzisz starca Hidalgo.}
{101} {} {Widzisz jednego ze starszych Villi.}
{102} {} {Jesteœ naszym bohaterem i wybawc¹. Kochamy Ciê i doceniamy.}
{1102} {} {Jesteœ nasz¹ bohaterk¹ i zbawicielem. Kochamy Ciê i doceniamy.}
{103} {} {Wszystkim bêdzie lepiej, jeœli opuœcisz Villê. I ju¿ nigdy tu nie wrócisz.}
{104} {} {Ukochany syn Andresa i Marii. Nie zapomnij o swoich korzeniach.}
{1104} {} {Ukochana córka Andresa i Marii. Nie zapomnij o swoich korzeniach.}
{105} {} {Co to za ¿art? Przepadnij, stalowy demonie!}

# Pierwszy dialog
{200} {} {(Przed tob¹ siedzi starzec Hidalgo; jak zwykle prze¿uwa coœ na wpó³ zasypiaj¹c)}
{201} {} {Um. Stary cz³owieku, chcia³eœ mnie zobaczyæ?}
{202} {} {Ach, }
{203} {} {... Ho-sho... co... hm... tutaj...}
{204} {} {S³uchaj, jeœli przestaniesz ¿uæ tytoñ, byæ mo¿e coœ zrozumiem.}
{205} {} {(pluje i wyciera siê koœcist¹ d³oni¹) Mówiê... Spo³ecznoœæ chce ciê widzieæ na spotkaniu. Zdecydowaliœmy, ¿e Ty te¿ powinieneœ wyraziæ swoj¹ opiniê.}
{206} {} {Jakie spotkanie?}
{207} {} {Spo³ecznoœæ musi zdecydowaæ, co dalej. Przecie¿ problemy nie koñcz¹ siê na uratowaniu naszych ludzi.}
{208} {} {Kiedy jest to spotkanie?}
{209} {} {Wieczorem, kiedy wszyscy skoñcz¹ swoje sprawy i zbior¹ siê w holu. Starzy ludzie nie lubi¹ siê œpieszyæ, wiêc pamiêtaj, ¿e zajmie to ca³y wieczór.}
{210} {} {Bêdê od pocz¹tku. Do zobaczenia.}
{211} {} {Ok, bêdê od pocz¹tku.}
{212} {} {Bêdzie mi ³atwiej tu poczekaæ. Czy mam roz³o¿yæ koœci, ¿eby zabiæ czas?}
{213} {} {Poczekam tutaj. Nie mam siê gdzie œpieszyæ.}

{220} {} {, pamiêtasz o spotkaniu?}
{221} {} {Tak, bêdê na czas.}
{222} {} {Jest ju¿ wieczór. Czas zacz¹æ.}
{223} {} {Poczekam tutaj. Czy mamy roz³o¿yæ koœci, ¿eby zabiæ czas?}
{224} {} {Zaczekam tutaj.}
{225} {} {SpóŸni³eœ siê. Wszyscy od dawna œpi¹.}
{226} {} {Hrrr... hruk... khr-khr-khr...}
{227} {} {Starzec œpi. Nie ma sensu go teraz budziæ...}

{230} {} {Spotkanie siê zaczyna.}
{231} {} {Spotkanie zakoñczone.}
{232} {} {Czy wszyscy s¹ tutaj? W porz¹dku. Musimy us³yszeæ wszystkich.}
{233} {} {}

# Pierwsze spotkanie
{250} {} {Jak wszyscy widzieliœmy, nadchodz¹ ciê¿kie czasy.}
{251} {} {[Dalej.]}
{252} {} {Istnieje ¿ycie poza dolin¹, o którego istnieniu nigdy nie wiedzieliœmy. Osoby postronne równie¿ s³ysza³y o nas i naszych plantacjach. Nie teraz, to póŸniej przybêd¹ tu najróŸniejsi rabusie i handlarze, aby zabraæ nasze owoce.}
{253} {} {[Dalej.]}
{254} {} {Musimy siê przygotowaæ na ich przybycie. Pamiêtajcie, jak ³atwo rabusie w³amali siê do wioski i wziêli wszystkich do niewoli. Nawet senor Andres nie by³ w stanie odeprzeæ ataku w ratuszu. (sale wype³nia ryk oburzenia)}
{255} {} {[Dalej.]}
{256} {} {Cisza. Wszyscy jesteœmy spiêci. Ale jeszcze nie wszystko stracone. Wróciliœmy z niewoli, nasze domy przetrwa³y, a plantacje wkrótce dadz¹ nowe plony. Mamy jeszcze trochê czasu.}
{257} {} {[Dalej.]}
{258} {} {(G³os z publicznoœci: „Stary cz³owieku, co mo¿emy zrobiæ? Pierwsi bandyci wycisn¹ nas jak dojrza³y mutaowoc.”) Wiem, wiem... Cicho! Nie wszystko jest stracone. }
{259} {} {, wyjdŸ do nas. PodejdŸ bli¿ej, usi¹dŸ tutaj...}
{260} {} {[PrzejdŸ do przodu]}
{261} {} {To jest nasz wybawca. }
{1261} {} {To jest nasz wybawca. }
{262} {} {Pomóg³ wam wszystkim wyjœæ z niewoli. Pomo¿e tak¿e chroniæ nasze rodziny przed nieznajomymi...}
{1262} {} {Pomog³a wam wszystkim wyjœæ z niewoli. Pomo¿e tak¿e chroniæ nasze rodziny przed nieznajomymi...}
{263} {} {Czeœæ wszystkim. Co tam?}
{264} {} {Mi³o was wszystkich widzieæ.}
{1264} {} {Mi³o was wszystkich widzieæ.}
{265} {} {}
{266} {} {(z t³umu dochodz¹ okrzyki niezadowolenia i jeden z ch³opów wstaje: „Hej, staruszku, nie zachwalaj dzieciaka. Sami byœmy wyszli z tego ba³aganu. Nie bêdê k³amaæ jeœli powiem, ¿e ca³a spo³ecznoœæ uwa¿a go za niegodnego spadkobiercê. A ta historia niczego nie zmienia. ”) Do diab³a! Wiem, ¿e wielu z was nie lubi }
{1266} {} {(z t³umu dochodz¹ okrzyki niezadowolenia i jeden z ch³opów wstaje: „Hej, staruszku, nie zachwalaj dziewczyny. Sami byœmy wyszli z tego ba³aganu. Nie bêdê k³amaæ jeœli powiem, ¿e ca³a spo³ecznoœæ uwa¿a j¹ za niegodn¹ spadkobierczyniê. A ta historia niczego nie zmienia. ”) Do diab³a! Wiem, ¿e wielu z was nie lubi }
{267} {} {. Ale co byœmy zrobili bez jego interwencji? Ale nie o tym teraz mówimy.}
{1267} {} {. Ale co byœmy zrobili bez jej interwencji? Ale nie o tym teraz mówimy.}
{268} {} {Nie przejmuj siê nimi. Zawsze mi zazdroœcili.}
{269} {} {W porz¹dku, staruszku. Nie rozmawiajmy o mnie, dobrze?}
{270} {} {(Na widowni s³ychaæ wiwaty i jeden z ch³opów wstaje: „Nie wiem jak pozostali, ale ja jestem ci wdziêczny }
{271} {} {. Wielu uwa¿a ciê za godnego spadkobiercê swojego ojca. ”) S³yszysz, }
{1271} {} {. Wiele osób uwa¿a ciê za godn¹ spadkobierczyniê swojego ojca. ”) S³yszysz, }
{272} {} {? Doceñ zaufanie, którym ciê obdarzono.}
{273} {} {Rozumiem. Mo¿esz na mnie polegaæ.}
{274} {} {Jasne. Na pewno o wszystko zadbam.}
{275} {} {(Z t³umu s³ychaæ sceptyczne okrzyki i jeden z ch³opów wstaje: „Hej, staruszku. Oczywiœcie jesteœmy wdziêczni, ale wiesz, nie mamy teraz czasu zabawê w bohatera.}
{276} {} { zrobi³, co musia³. Mo¿e nie bêdziemy o tym teraz rozmawiaæ? ”) Masz racjê. Ale nie zapominaj, kto wyci¹gn¹³ ciê z niewoli.}
{1276} {} { zrobi³a, co musia³a zrobiæ. Mo¿e nie bêdziemy o tym teraz rozmawiaæ? ”) Masz racjê. Ale nie zapominaj, kto wyci¹gn¹³ ciê z niewoli.}
{277} {} {Przyjaciele, kontynuujmy.}
{278} {} {Oczywiœcie nie powinieneœ oczekiwaæ innego nastawienia.}

{280} {} {Faktem jest, ¿e niewolnictwo i podró¿owanie przez pustyniê os³abi³o zdrowie Senora Andresa. Nie bêdzie móg³ odejœæ daleko od Villi, i tak ledwo jest w stanie pomóc w odbudowie wioski. }
{281} {} {, musisz wykonaæ czêœæ jego obowi¹zków. Czas wzi¹æ na siebie odpowiedzialnoœæ, któr¹ kiedyœ dzier¿y³ twój ojciec.}
{282} {} {Oczywiœcie. Przygotowywa³em siê do tego przez ca³e ¿ycie.}
{1282} {} {Oczywiœcie. Przygotowywa³am siê do tego przez ca³e ¿ycie.}
{283} {} {To ¿art? Hej tato, co siê dzieje?}
{284} {} {Muszê te¿ podzieliæ siê wiadomoœciami. Senor Andres, padre waszego zbawiciela, zgin¹³ podczas swojej wêdrówki niewolników. (Oznajmia g³oœno) Jego honorowe miejsce, zgodnie z regu³ami wspólnoty, zajmuje jego bezpoœredni potomek. }
{285} {} {, jesteœ teraz naszym liderem.}
{286} {} {Oczywiœcie. Przygotowywa³em siê do tego przez ca³e ¿ycie.}
{1286} {} {Oczywiœcie. Przygotowywa³am siê do tego przez ca³e ¿ycie.}
{287} {} {Wow. Brzmi nieŸle.}

{290} {} {Twoja madre by³aby z ciebie dumna. Szkoda, ¿e nie ma jej ju¿ z nami. (wszyscy zamieraj¹ w d³ugiej ciszy)}
{291} {} {Rozchmurzcie siê, przyjaciele. Ona by tego nie chcia³a.}
{292} {} {Jeœli ju¿, to nie moja wina. Pamiêtajcie.}
{293} {} {Twoja madre ju¿ zgodzi³a siê na przekazanie w³adzy. Obecnie odbudowuje wioskê, wiêc to ty, }
{294} {} {, musisz zadbaæ o resztê.}
{295} {} {Poradzê sobie.}
{296} {} {W koñcu jestem traktowany powa¿nie.}

{300} {} {(starzec Pablo wstaje z miejsca) Jest za wczeœnie, ¿eby dzieciak pokierowa³ Vill¹! Nie rozœmieszaj ludzi, Hidalgo! (jakiœ ch³op wstaje) A co z najazdami? Powiedz mi, jak walczyæ z handlarzami niewolników! (inny ch³op wo³a za nim) Czy s³ysza³eœ, co siê dzieje z tymi padlino¿ercami z s¹siedniego miasta? To koniec naszego ca³ego spokojnego ¿ycia!}
{1300} {} {(starzec Pablo wstaje z miejsca) Jest zaa wczeœnie, ¿eby dzieciak pokierowa³ Vill¹! Nie rozœmieszaj ludzi, Hidalgo! (jakiœ ch³op wstaje) A co z najazdami? Powiedz mi, jak walczyæ z handlarzami niewolników! (inny ch³op wo³a za nim) Czy s³ysza³eœ, co siê dzieje z tymi padlino¿ercami z s¹siedniego miasta? To koniec naszego ca³ego spokojnego ¿ycia!}
{301} {} {Przyjaciele, spokojnie!}
{302} {} {Co za ho³ota...}
{303} {} {(pokój wype³nia huk dyskusji, Hidalgo robi uspokajaj¹cy gest) Cisza! Przestañcie ha³asowaæ! Zaraz to omówimy, ale porozmawiajmy na spokojnie. }
{304} {} {, proszê, twoja kolej, aby zabraæ g³os.}
{305} {} {Stary Pablo nie ufa nikomu jak zwykle. Bêdê musia³ odpowiedzieæ na jego s³owa.}
{306} {} {O handlarzach niewolników. To jest najwa¿niejsza sprawa.}
{307} {} {Garage City to brudne miasto. Ale jaki jest problem z padlino¿ercami?}

{310} {} {"Hej Pablo, czy ocalenie wioski nie jest dla ciebie wystarczaj¹ce? Czego wiêcej chcesz?" - "B¹dŸ cicho, Hidalgo. Pozwól mu odpowiedzieæ. W koñcu prowadzenie Villi i ucieczka przed w³aœcicielami niewolników to nie to samo."}
{311} {} {Czym jeszcze nas zaskoczysz?}
{312} {} {Wystarczy uwolnienie, by mi zaufaæ. Najwy¿szy czas, abyœcie starcy zrobili miejsce m³odym.}
{313} {} {Stary Pablo, twoje narzekanie dzia³a mi na nerwy. Powiedzia³em ju¿ wszystko.}
{1313} {} {Stary Pablo, twoje narzekanie dzia³a mi na nerwy. Powiedzia³am ju¿ wszystko.}
{314} {} {Wystarczy.}
{315} {} {To jest to, o czym mówiê - niecierpliwoœæ! M³odzi ludzie nie wiedz¹, co to znaczy prowadziæ spo³ecznoœæ. Nie znaj¹ zakazów i nie znaj¹ historii. Jak mo¿emy ufaæ takiemu cz³owiekowi? (ogólne oburzenie)}
{316} {} {[Dalej.]}
{317} {} {Ale i tak ka¿dy zdecyduje jak uwa¿a. Wyrazi³em swoj¹ opiniê.}
{318} {} {Hmmmm... Có¿, teraz widzê, kto jest przede mn¹. Cenisz naszych ludzi i cenisz nasz¹ wioskê. Chyba mogê ci zaufaæ. Ale tylko jeœli s³uchasz starych ludzi. (zwracaj¹c siê do publicznoœci) Zgadzam siê! (sala zaczyna ha³asowaæ z radoœci)}
{319} {} {[Dalej.]}
{320} {} {Kiedy ciê nie by³o, naprawi³em stacjê meteorologiczn¹, któr¹ zniszczyli najeŸdŸcy.}
{1320} {} {Kiedy ciê nie by³o, naprawi³am stacjê meteorologiczn¹, któr¹ zniszczyli najeŸdŸcy.}
{321} {} {Co co? Och, stacja pogodowa... Czy to by³o coœ, co trzeba by³o zrobiæ, kiedy nasi ludzie mieli k³opoty? Stacja jest jednak bardzo wa¿na. Zw³aszcza teraz, gdy mamy tak ma³o ¿ywnoœci.}
{322} {} {Jose zdecydowanie nie móg³ znieœæ swojej chorej nogi.}
{323} {} {Có¿, wypêdzi³em te¿ maruderów. Próbowali zabraæ ostatnie resztki plonów.}
{1323} {} {Có¿, wypêdzi³am te¿ maruderów. Próbowali zabraæ ostatnie resztki plonów.}
{324} {} {I zrobili to, prawda? Zabra³eœ m¹kê z hangaru i odda³eœ im j¹. (ogólne oburzenie)}
{1324} {} {I zrobili to, prawda? Zabra³aœ m¹kê z hangaru i odda³aœ im j¹. (ogólne oburzenie)}
{325} {} {Ale odeszli i nikogo nie skrzywdzili. I to jest najwa¿niejsze!}
{326} {} {Tak. I to by³a najm¹drzejsza decyzja.}
{327} {} {To dobrze. Musimy teraz uratowaæ ka¿de ziarno. Ale maruderzy i tak nie ukradliby zbyt wiele. I sami byœmy ich wypêdzili, ale póŸniej.}
{328} {} {To nic wiêcej ni¿ twoje spekulacje.}
{329} {} {No có¿. Po wszystkim i tak otworzyliby hangar i zabrali wszystko, co tam jest. Podziêkujcie, niewdziêcznicy.}
{330} {} {Leczy³em rannych po nalocie.}
{1330} {} {Leczy³am rannych po nalocie.}
{331} {} {Wiemy, co to by³o za leczenie. W koñcu wiesz i wszyscy wiedz¹, ¿e sam Za³o¿yciel surowo zabroni³ tych staro¿ytnych leków. S¹ niebezpieczne, po³owa z nich to trucizna. A jeœli nie, to ludzie, których wyleczy³eœ, mog¹ zostaæ przeklêci. To by³o bardzo bezmyœlne z twojej strony. Chocia¿ z drugiej strony ci ludzie nadal ¿yj¹, a to wa¿ne.}
{332} {} {To by³ wymuszony œrodek, ¿ycie ludzi jest cenniejsze.}
{333} {} {Pieprzyæ twoje spleœnia³e tabu!}
{334} {} {Dziêki tobie ludzie ¿yj¹. I bêd¹ mogli naprawiæ wioskê. Dziêkujê Ci. Ale przede wszystkim trzeba by³o zaj¹æ siê tymi, którzy popadli w niewolê.}
{335} {} {Jak widaæ, uda³o mi siê wykonaæ dwa zadania.}
{336} {} {Nie mo¿na ciê zadowoliæ, staruszku.}
{337} {} {Ch³opiec Eden prawie wpad³ w k³opoty. Ledwo uda³o mi siê go wydostaæ z plantacji pe³nej kojotów.}
{338} {} {Znamy tê historiê. To by³o dosyæ odwa¿ne. Nie mam nic do powiedzenia. Jednak nie s¹dzê, ¿eby naprawdê potrzebowa³ pomocy. Przez jakiœ czas ¿y³by na liœciach kukurydzy, a potem sam wróci³by do wioski z g³odu. Dziecko nie jest g³upcem.}
{339} {} {Nie s¹dzê.}
{340} {} {To s¹ tylko bezsensowne domys³y jakiegoœ starca.}

{350} {} {(inny g³os z publicznoœci) Czekaj, staruszku. Nie omówiliœmy jeszcze historii z Chrisem. Ten zdrajca zas³uguje na ch³ostê. Ale nigdzie go nie ma.}
{351} {} {Chris móg³ uciec. Kto wie, komu bêdzie opowiada³ o nas na Pustkowiu.}
{352} {} {Um, pos³uchaj...}
{353} {} {Dobrze. To Ÿle. Jak mo¿esz daæ sobie tyle luzu }
{354} {} {? Jeœli ktoœ jest winny, musi zostaæ ukarany. Twoja miêkkoœæ nie jest najlepsz¹ cech¹ przywódcy. Jak siê usprawiedliwiasz, }
{355} {} {?}
{356} {} {Dzia³a³em w dobrej wierzê.}
{1356} {} {Dzia³a³am w dobrej wierzê.}
{357} {} {Tutaj mamy mniej wiêcej to samo. Twoje osobiste dziwactwa zagra¿aj¹ naszej wiosce. (ogólne oburzenie)}
{358} {} {ChodŸ...}
{359} {} {Nie wierzê, ¿e zamierzaliœcie ukamienowaæ rodaka.}
{360} {} {Krewni i bliscy powinni byæ odpowiedzialni za siebie nawzajem. W tym miejscu zas³ugujesz na ch³ostê za swój stosunek do Chrisa. Hañba i wstyd.}
{361} {} {(publicznoœæ cichnie, jest trochê zdezorientowana) Có¿... To dyskusyjne. Chyba lepiej narazie to zostawiæ.}
{362} {} {Dok³adnie.}
{363} {} {(inny g³os z publicznoœci) Czekaj, staruszku. W obronie chcê dodaæ, jak }
{364} {} { odda³ nam Chrisa. Chris by³ zdrajc¹, zas³uguje na ch³ostê. Gdyby nie }
{1364} {} { odda³a nam Chrisa. Chris by³ zdrajc¹, zas³uguje na ch³ostê. Gdyby nie }
{365} {} {, móg³ uciec. A kto wie komu by o nas jeszcze powiedzia³.}
{366} {} {[Dalej.]}
{367} {} {Racja. Swiêta prawda. Przywódca nie mo¿e pokazaæ miêkkoœci. Jeœli ktoœ jest winny, musi zostaæ ukarany.}
{368} {} {[Dalej.]}

{370} {} {(inny g³os z publicznoœci) Pozwól mi! A co z tym okropnym ¿elaznym kawa³kiem, który }
{371} {} { ca³y czas nosi i straszy dzieci? Nie potrzebujemy tego!}
{372} {} {To jest zbroja wspomagana. I bardzo jej potrzebujê.}
{373} {} {(Starzec Hidalgo budzi siê na wpó³ zasypiaj¹c i przerywa rozmowê) Maj¹ racje, }
{374} {} {. Za³o¿yciel zapisa³ równie¿, ¿e nie nale¿y u¿ywaæ starych technologii. Przecie¿ to z ich powodu przed stu laty wydarzy³a siê Wielka Wojna. Dlatego zawsze unikaliœmy starej techniki. A ty przynosisz to wszystko tutaj i proponujesz zaakceptowaæ to, jakby nic siê nie sta³o.}
{375} {} {Nie da siê Was zadowoliæ.}
{376} {} {Ta technika nie raz uratowa³a mi ¿ycie. Mo¿e uratowaæ te¿ Villê.}
{377} {} {Hmm... Có¿, jeœli siê nad tym zastanowiæ, mo¿e tak byæ... Ale mimo wszystko - nie strasz naszych ludzi. Ostatnio mamy tego doœæ.}
{378} {} {Ok...}
{379} {} {Co jest nie tak ze starymi technologiami, jeœli chroni¹ ¿ycie? To jakieœ bzdury.}
{380} {} {Za³o¿yciel wiedzia³, co mówi! Czy uwa¿asz, ¿e jesteœ m¹drzejszy od swoich przodków? (na auli rozlega siê krzyk: „Ooh-ooh”)}
{381} {} {Nie mo¿na Was zadowoliæ.}
{382} {} {(inny g³os z publicznoœci) Pozwól mi! A co z tym okropnym ¿elaznym pojadem, którym }
{383} {} { jeŸdzi przez pustyniê, wzbijaj¹c kurz i strasz¹c dzieci? Nie potrzebujemy tego!}
{384} {} {Motocykl? Bez niego podró¿owanie na du¿e odleg³oœci by³oby znacznie trudniejsze.}
{385} {} {(Hidalgo wstaje i gestykuluje) Kto jeszcze chce rozmawiaæ o naszym bohaterze? Nie ma wiêcej komentarzy? Wiêc podnieœcie rêce Ci, którzy zgadzaj¹ siê wyznaczyæ }
{1385} {} {(Hidalgo wstaje i gestykuluje) Kto jeszcze chce rozmawiaæ o naszej bohaterce? Nie ma wiêcej komentarzy? Wiêc podnieœcie rêce Ci, którzy zgadzaj¹ siê wyznaczyæ }
{386} {} { g³ow¹ wioski.}
{387} {} {Hmm. Ciekawe.}
{388} {} {Zartujesz sobie ze mnie?}
{389} {} {Wiêkszoœæ g³osów by³a za. Gratulacje, }
{390} {} {. }
{391} {} {Wow, jak kamieñ z serca...}
{392} {} {Czy mog³o byæ inaczej? W³aœnie.}
{393} {} {Mniej ni¿ po³owa. Dobrze, }
{394} {} { bêdziesz musia³ postaraæ siê trochê wiêcej, aby zdobyæ zaufanie. Jednak zgodnie z zaleceniami Za³o¿yciela, Villa powinna byæ prowadzona przez jego bezpoœredniego potomka. Czy Ci siê to podoba, czy nie. Odroczenie tego nie zmieni.}
{395} {} {To nic. Nie œpieszy mi siê.}
{396} {} {Jakim ty jesteœ skostnia³ym zrzêd¹..}

{400} {} {Wydaje siê, ¿e omówiliœmy wszystkie wa¿ne pytania. Czas siê czymœ zaj¹æ.}
{401} {} {Tak, racja. Bêdziemy czekaæ na Twój powrót. Powodzenia, }
{402} {} {. I niech wiatry wiej¹ w Twoje plecy.}
{403} {} {[Opuœæ spotkanie]}

{410} {} {(twoja madre wstaje) Kiedy pracowa³am w garnizonie, zdarzy³o mi siê pods³uchiwaæ rozmowy najemników. Powiedzieli, ¿e liczba niewolników tylko wzroœnie. Nie ma pewnoœci, ¿e ju¿ po nas nie przyjd¹.}
{411} {} {(jeden z ch³opów wstaje) Kiedy pracowa³em w kopalniach Flagpool, zdarzy³o mi siê pods³uchiwaæ rozmowy najemników. Powiedzieli, ¿e liczba niewolników tylko wzroœnie. Nie ma pewnoœci, ¿e ju¿ po nas nie przyjd¹.}
{412} {} {[Dalej.]}
{413} {} {(jakiœ ch³op wstaje)}
{414} {} {(Sancho wstaje)}
{415} {} {Masz racjê. Kopalnia ci¹gle potrzebuje nowej si³y roboczej. Dopóki ta kopalnia dzia³a nie mo¿emy czuæ siê bezpiecznie. Proponujê j¹ zniszczyæ.}
{416} {} {Zniszczyæ kopalniê? Jak zamierzasz to zrobiæ?}
{417} {} {W kopalniach u¿ywaliœmy czegoœ, co nazywa siê „materia³ami wybuchowymi”. Wybucha w taki sposób, ¿e niszczy wszystko dooko³a. W magazynach powinno byæ wystarczaj¹co du¿o tej substancji, aby wype³niæ przejœcie wewn¹trz kopalni.}
{418} {} {Jesteœ szalony. Wracaæ tam w celu sabota¿u? To zbyt niebezpieczne.}
{419} {} {(Hidalgo przestaje ¿uæ tytoñ) Masz jakieœ lepsze pomys³y? Lepiej przemyœl i og³oœ swoj¹ decyzjê na nastêpnym spotkaniu. Ale nie przeci¹gaj tego.}
{420} {} {Ok.}
{421} {} {Podoba mi siê ten pomys³. Wysadzê tê kopalniê.}
{422} {} {(wszyscy wiwatuj¹) Hurra! WysadŸ w powietrze t¹ przeklet¹ kopalniê! Zrób to!}
{423} {} {Zgoda.}
{424} {} {Daj mi czas na przemyœlenie. Mo¿e uda mi siê znaleŸæ kompromis z w³aœcicielem kopalni.}
{425} {} {(publicznoœæ patrzy na siebie z niedowierzaniem) Czy naprawdê zamierasz tak zrobiæ? Hmm, pustkowia da³y ci du¿o doœwiadczenia. Ale jak dot¹d rada trzyma siê propozycji z eksplozj¹. Mam nadziejê, ¿e podejmiesz w³aœciw¹ decyzjê.}
{426} {} {Ok.}
{427} {} {(Hugo wstaje)}

{430} {} {S³yszeliœmy plotki od handlarzy, ¿e padlino¿ercy w Garage City próbuj¹ odbudowaæ starozytn¹ fabrykê i rozpocz¹æ tam produkcjê ró¿nego wyposa¿enia. WyobraŸ sobie, co to oznacza dla naszego skromnego miasta!}
{431} {} {[Dalej.]}
{432} {} {Jose, powiedz im. (Jose wstaje) Tak, oczywiœcie...}
{433} {} {Bêdziemy punktem na trasach karawan. Bêd¹ tu t³umy poszukuj¹cych pracy. Razem z nimi do doliny przyjd¹ z³odzieje, broñ i alkohol. Nie bêdziemy w stanie oprzeæ siê takim zmianom, zostaniemy po prostu poch³oniêci.}
{434} {} {Sugerujesz, abyœmy wstrzymali tamtejsz¹ produkcjê? Ale jak?}
{435} {} {Podobno maj¹ tam maszyny od tego, to je trzeba zniszczyæ. Tylko nie wiem jak to zrobiæ. Ale ci, którzy wrócili z Flagpool, mówi¹ o czymœ, co nazywa siê „materia³ami wybuchowymi”. Mo¿e ta rzecz jest w stanie zniszczyæ maszyny, tak jak niszczy kamienie. Nie ma potrzeby niszczenia ca³ej fabryki.}
{436} {} {Mam zbyt dobre stosunki z padlino¿ercami. Nie chcia³bym wypowiadaæ im wojny.}
{437} {} {Nie chcê wypowiadaæ wojny padlino¿ercom. To nasi s¹siedzi!}
{438} {} {Oni s¹ zdrajcami! S³u¿yli najeŸdŸcom, którzy nas zniewolili. Jak mo¿emy mieæ dobre relacje z takimi draniami? W ka¿dym razie nie mo¿emy pozwoliæ na rozwój fabryki. Jeœli masz inny pomys³, zrób coœ. Ale nikt tutaj nie zaakceptuje tych œmieci.}
{439} {} {Rozumiem.}
{440} {} {Padlino¿ercy zas³uguj¹ na ch³ostê za swoj¹ zdradê. Zniszczê ich cholern¹ fabrykê.}
{441} {} {(wszyscy wiwatuj¹) Hurra! Zniszcz j¹! Daj im to na co zas³uguj¹!}
{442} {} {Mo¿ecie na mnie polegaæ.}
{443} {} {Chcesz pozbawiæ ludzi legalnego rozwoju. Spróbujê znaleŸæ kompromis.}
{444} {} {Negocjowaæ z padlino¿ercami? S¹ pod³ymi handlarzami i urodzonymi oszustami. Rada nie aprobuje takiego sojuszu.}
{445} {} {Ok, przyjrzê siê ró¿nym opcjom.}

{450} {} {Hej staruszku. Pragnê poinformowaæ, ¿e kopalnia Flagpool zosta³a zniszczona.}
{451} {} {M? Och... Wiêc to zrobi³eœ? W porz¹dku. Có¿, miejmy nadziejê, ¿e wszystko bêdzie dobrze.}
{452} {} {Pozostaje tylko sprawa z fabryk¹ w Garage City...}
{453} {} {Chcê tylko poinformowaæ, ¿e kopalnia Flagpool nie jest ju¿ problemem. Teraz u¿ywaj¹ robota i zmniejszaj¹ liczbê niewolników.}
{454} {} {Robota, mówisz? Czyli maszynê z czasów staro¿ytnych? Och, to niedobrze. Kto wie, jak d³ugo bêdzie pracowaæ i czy Faber ma jeszcze jakiœ pomys³? Ale fakt, ¿e nie potrzebuje ju¿ niewolników, jest dobry.}
{455} {} {Teraz zajmê siê fabryk¹ Garage City...}
{456} {} {Mam wiadomoœæ - maszyna w fabryce Garage City zosta³a zniszczona.}
{457} {} {M? Ach... Dobra wiadomoœæ. Nie ma potrzeby niepokoiæ starego demona. Bez fabryki bêdzie nam lepiej.}
{458} {} {Pozostaje poradziæ sobie z kopalni¹ w Flagpool...}
{459} {} {Nie musimy niszczyæ maszyn w Garage City. Lider fabryki oferuje korzystne warunki do renowacji Villi.}
{460} {} {Och... O czym ty mówisz? Sugerujesz sojusz z padlino¿ercami? Wielu ludziom siê to nie spodoba. Z drugiej strony ich praca by³aby bardzo przydatna i bardzo pomog³aby ca³ej Villi.}
{461} {} {Teraz zajmê siê kopalni¹ w Flagpool...}
{462} {} {Wiêc oba problemy s¹ rozwi¹zane. Czas zwolac now¹ naradê.}
{463} {} {(Myœli przez d³ugi czas, odwzajemniaj¹c skinieniem g³ow¹) Ok... Ale teraz bêdziesz rozmawiaæ tylko ze starszymi.}
{464} {} {No dobrze...}
{465} {} {}
{466} {} {, dziêkujemy za pozbycie siê naszych wrogów. Stary Hidalgo powiedzia³ nam, ¿e Garage City i Flagpool ju¿ nam nie zagra¿aj¹. A to nasi najbli¿si, a zatem najgroŸniejsi wrogowie.}
{467} {} {Wiêc mamy teraz du¿o czasu.}
{468} {} {O nie. Obawiam siê, ¿e tak nie jest. Ty, twój ojciec i kilku innych starszych byliœcie ju¿ daleko od domu. Wiemy, jaki jest œwiat wokó³ nas. Bez patronów jesteœmy ³atw¹ ofiar¹ wszelkich bandytów.}
{469} {} {Wiêc musimy znaleŸæ sojuszników. Lub staæ siê wystarczaj¹co silni, by siê im oprzeæ.}
{470} {} {Jak mo¿esz sobie wyobraziæ, nasze ch³opskie zwyczaje uniemo¿liwiaj¹ nam nawet dotykanie starej technologii. Wiemy, jak pracowaæ, ale nie umiemy walczyæ. Potrzebujemy patrona. Jedynymi, którzy mog¹ staæ siê takimi, s¹ Rangersi. IdŸ do nich i negocjuj z genera³em Mossmanem, aby bronili Villi w zamian za zapasy.}
{471} {} {Niech tak bêdzie. Spe³niê wolê Rady.}
{472} {} {Nie podoba mi siê pomys³ sojuszników.}
{473} {} {Taka jest wola Rady. Liczymy na Ciebie.}
{474} {} {Mo¿ecie na mnie polegaæ.}
{475} {} {Módlcie siê, aby wasza wola nie zmieni³a siê w nasz¹ s³aboœæ. Szczêœcia.}
{476} {} {S³uchamy Ciê, }
{477} {} {. Powiedz nam, jak maj¹ siê sprawy z naszymi wrogami?}

{480} {} {Czy rozmawia³eœ ju¿ z genera³em Rangersów? Jaka jest jego odpowiedŸ?}
{1480} {} {Czy rozmawia³aœ ju¿ z genera³em Rangersów? Jaka jest jego odpowiedŸ?}
{481} {} {Nie uda³o mi siê go jeszcze zobaczyæ. Ale nie tracê nadziei, ¿e to zrobiê.}
{482} {} {Niedawno odwiedzi³ nas ambasador z Bractwa Stali. Jego arogancja przeszkadza³a wszystkim mieszkañcom wioski. Chcielibyœmy us³yszeæ od Ciebie osobiœcie, co to wszystko oznacza?}
{483} {} {Szukaliœcie sprzymierzeñca-patrona. Oto jest. Lepszego nie ma na tych ziemiach.}
{484} {} {Wiemy o Bractwie Stali. Twój ojciec dowiedzia³ siê o nim, kiedy by³ w niewoli. Powiedzia³ te¿, ¿e gdyby nie Bractwo, nie by³oby kolonii Flagpool, kultu Ognia ani ciê¿kiej pracy w Tu-San. Teraz sprowadzasz tê bestiê na nasze ziemie i sprawiasz, ¿e pracujemy dla niej?}
{485} {} {Zeby bestia nas nie po¿ar³a, pozostaje tylko zaprzyjaŸniæ siê z ni¹. Dopóki regularnie p³acimy ¿niwami, jesteœmy bezpieczni. Ponadto pomog¹ nam w wyposa¿eniu i bezpieczeñstwie.}
{486} {} {(bolesna cisza) Jesteœ teraz liderem spo³ecznoœci. To od ciebie zale¿y, gdzie j¹ zabierzesz. Jeœli tak widzisz przysz³oœæ Villi, niech tak bêdzie. Nie mo¿emy siê oprzeæ Twojej woli. Nie bêdziemy w stanie.}
{487} {} {Utknêliœcie w przesz³oœci. Najwy¿szy czas, aby Villa siê zmieni³a. A zjednoczenie z Bractwem bêdzie dobrym pocz¹tkiem. Najwa¿niejsze, ¿eby nie przegapiæ okazji. A teraz muszê odpocz¹æ i przemyœleæ ca³¹ tê historiê. Por desgracia, tengo que irme.}
{488} {} {Wiêc niedawno przyby³ do nas ambasador Rangersów. Czy to nie twoja sprawka?}
{489} {} {Tak. Rangersi s¹ gotowi do zawarcia sojuszu w celu ochrony Villi.}
{490} {} {Daj mi chwilê. Przed tak wa¿nym wydarzeniem muszê zebraæ myœli...}
{491} {} {Rangersi udaj¹, ¿e siê o nas troszcz¹. Chocia¿ w rzeczywistoœci zajmuj¹ siê tylko odbieraniem ¿ywnoœci. Nie pozwolimy im wyjœæ poza zakres umowy.}
{492} {} {Podczas gdy jesteœmy pod ich ochron¹, musimy wzmocniæ nasz¹ pozycjê, wzmocniæ nasz¹ si³ê, aby samodzielnie odeprzeæ wrogów.}
{493} {} {(Milcz¹ca zgoda) Przysz³oœæ nale¿y do Ciebie i przysz³ych pokoleñ. Jesteœ liderem Villi, decydujesz, gdzie j¹ poprowadziæ. My, starzy ludzie, nie mamy ju¿ zbyt wiele czasu. Ale cieszymy siê, ¿e Villa jest w dobrych rêkach.}
{494} {} {Najwa¿niejsze, ¿eby nie zostaæ zmanipulowanym. A teraz muszê odpocz¹æ i przemyœleæ ca³¹ tê historiê. Por desgracia, tengo que irme.}
{495} {} {Rangersi nie mog¹ sprzymierzyæ siê z nami. Zostali pokonani.}
{496} {} {Mam problem z Rangersami. Wydaje siê, ¿e w ogóle chc¹ mnie zabiæ.}
{497} {} {Wiêc jesteœmy skazani. Nie mo¿emy sami broniæ siê przed wrogami.}
{498} {} {Ale Flagpool i Garage City...}
{499} {} {Wiesz bardzo dobrze, ¿e byli tylko peryferiami wiêkszego procesu. Ci, którzy kontroluj¹ losy Sonory, nadal siedz¹ daleko na po³udniu. I nie bêd¹ tam siedzieæ po wsze czasy.}
{500} {} {O kim mówisz?}
{501} {} {Twój ojciec powiedzia³ mi, ¿e Blacharze i czciciele ognia byli marionetkami Bractwa Stali. ZnajdŸ to Bractwo i powstrzymaj je, zanim bêdzie za póŸno. Do tego czasu nie wracaj do Villi.}
{502} {} {Ok. Wychodzê.}
{503} {} {Garstka starych ludzi. Jesteœcie po prostu szaleni.}
{504} {} {Czy mówisz o Bractwie Stali?}
{505} {} {Blacharze i czciciele ognia byli marionetkami Bractwa Stali. ZnajdŸ to Bractwo i powstrzymaj je, zanim bêdzie za póŸno. Do tego czasu nie wracaj do Villi.}
{506} {} {Zniszczy³em statek Bractwa Stali. Ich w³adza tutaj dobieg³a koñca.}
{1506} {} {Zniszczy³am statek Bractwa Stali. Ich w³adza tutaj dobieg³a koñca.}
{507} {} {Naprawdê, jesteœ patronem naszych ziem! Bez Bractwa Stali i Rangersów wielkie miasta bêd¹ pogr¹¿one w walkach i nie bêd¹ mog³y siê rozwijaæ.}
{1507} {} {Naprawdê, jesteœ patronk¹ naszych ziem! Bez Bractwa Stali i Rangersów wielkie miasta bêd¹ pogr¹¿one w walkach i nie bêd¹ mog³y siê rozwijaæ.}
{508} {} {To jest szansa dla nas, aby stan¹æ na nogi i staæ siê silniejszymi, aby w przysz³oœci móc walczyæ z naszymi wrogami.}
{509} {} {Teraz widzimy, ¿e Villa jest w dobrych rêkach. Jesteœ prawdziwym liderem, przysz³oœæ naszych ludzi nale¿y do Ciebie.}
{510} {} {Najwa¿niejsze, ¿eby nie zostaæ zmanipulowanym. A teraz muszê przejœæ na emeryturê i przemyœleæ ca³¹ tê historiê. Por desgracia, tengo que irme.}
{511} {} {Szkoda. Jeœli Rangersi s¹ teraz naszymi wrogami, bêdziemy musieli poszukaæ innego sojusznika. Z kim tam walczyli, wiesz?}
{512} {} {Ok. Spróbujê znaleŸæ innego sojusznika.}
{513} {} {Byæ mo¿e uda mi siê sabotowaæ ich tamê, ¿eby przynajmniej chwilowo byli zajêci czymœ innym.}