{102} {} {To dla ciebie za moje trudne dzieciñstwo, ojcze!}
{103} {} {Do widzenia. Nie potrzebujê ju¿ wskazówek mojego ojca.}
{104} {} {Czy z twoj¹ g³ow¹ wszystko w porz¹dku? Udaj siê na pustkowia i zakop g³êboko ten... „s³oik”.}
{105} {} {Twój ojciec wróci³ do Villi.}
{106} {} {Jestem z ciebie dumny, synu.}
{1106} {} {Jestem z ciebie dumny, córko.}
{107} {} {Od teraz nie mam syna. Jesteœ mi obcy.}
{1107} {} {Od teraz nie mam córki. Jesteœ mi obca.}
{108} {} {Jeœli chcesz wyjœæ, wyjdŸ. Ale nie próbuj zabraæ pozosta³ych.}

# Pierwszy dialog
{200} {} {Twój powrót uszczêœliwi³ ca³¹ Villê. Jestem z Ciebie dumny.}
{201} {} {To... dobrze to s³yszeæ.}
{206} {} {Co ci siê sta³o?}
{207} {} {Masz na myœli moj¹ skórê? Drobnostka.}
{208} {} {Naprawdê mam nadziejê, ¿e to nie jest zaraŸliwe. Uwierz mi - aby chroniæ spo³ecznoœæ, jestem gotów poœwiêciæ nawet ukochan¹ osobê. Doœæ o tym na razie.}
{209} {} {Dziêki za szczeroœæ... padre.}

# Powtarzajacy siê dialog
{210} {} {Mów, s³ucham ciê.}
{211} {} {Niewa¿ne, lepiej ju¿ pójdê.}
{212} {} {Wiêcej?}

{220} {} {Padre, dlaczego zawsze ¿yliœmy w izolacji od reszty œwiata?}
{221} {} {Nadmierny kontakt z obcymi nie przyniesie nam korzyœci. To jest wiedza, któr¹ pozostawi³ nam w spadku Za³o¿yciel. I nauczyliœmy siê tego dobrze podczas nalotu. Zapamiêtaj osady odwiedzone na swojej drodze. Ludzie s¹ podzieleni i nie mog¹ ¿yæ razem w pokoju i harmonii, tak jak my.}
{222} {} {[Dalej.]}

{228} {} {Domagam siê wyjaœnienia - dlaczego, do diab³a, obcy w bia³ym fartuchu b³¹ka siê po naszym placu i gapi siê na nasze domy?}
{229} {} {Arthur Carrington jest naukowcem. Pomyœla³em, ¿e jego pomoc bêdzie przydatna w odbudowie Villi po nalocie.}
{230} {} {Pomoc od kogoœ, kto umie czytaæ i liczyæ, ale nie potrafi trzymaæ ³opaty?}
{231} {} {Jest trochê s³aby, prawda, ale wie du¿o wiêcej o œwiecie zewnêtrznym ni¿ ty i ja. Zna te¿ stare technologie. Z jej pomoc¹...}
{232} {} {Nie wierzê w³asnym uszom! Czy podró¿ przez pustyniê ca³kowicie przyæmi³a twój umys³? Zyjemy od pokoleñ w izolacji od reszty œwiata, a ty przyprowadzasz tu nieznajomego i oferujesz przyjêcie starych technologii? Módl siê, aby twoja decyzja nie by³a pomy³k¹. Bêdê bacznie obserwowa³ tego nieznajomego. I Ciebie te¿.}
{233} {} {Nie po¿a³ujesz.}
{234} {} {Wiesz, spo³ecznoœæ zamierza ukaraæ Chrisa za tchórzostwo.}
{235} {} {Villa zawsze kierowa³a siê opini¹ wiêkszoœci. Takie jest tu prawo. Tylko dziêki temu prze¿yliœmy na œrodku pustyni. Historia Chrisa bêdzie doskona³ym przyk³adem tego, jak wa¿ne jest pod¹¿anie za wszystkimi.}
{236} {} {}
{237} {} {}
{238} {} {Dlatego zrezygnowaliœmy z kontaktu z obcymi, aby nie zszargali naszego kruchego œwiata swoim egoizmem. Wpuszczaj¹c nieznajomych do spo³ecznoœci, dostaniemy tylko niezgodê. Wiêc trzymaj buziê na k³ódkê, kiedy rozmawiasz o takich rzeczach z reszt¹ Villi.}
{239} {} {Rozumiem.}

{240} {} {Potrzebujê zapasów i niezawodnej broni do mojej misji.}
{241} {} {(znacz¹co kiwa g³ow¹) Zgadzam siê. Myœlê, ¿e czas daæ ci kilka naszych relikwii. W moim gabinecie na drugim piêtrze jest sejf. Przechowuje siê w nim cenne stare rzeczy. WeŸ to, co ci siê przyda. Kod do sejfu to 2093. To rok, w którym Za³o¿yciel przyby³ na te ziemie i wychodowa³ pierwsze k³osy.}
{242} {} {Ta historia jest na zawsze w moim sercu. Nie zgubiê rodzinnych pami¹tek i bêdê walczyæ o nasz¹ wolnoœæ.}
{243} {} {Dziêki.}

#Quests
{250} {} {Czy jest jeszcze coœ, w czym mogê Ci pomóc?}
{251} {} {Nasi przyjaciele nadal s¹ przetrzymywani przez kolonistów w Flagpool. Villa za bardzo mnie teraz potrzebuje i nie mogê opuœciæ osady, ¿eby ich uratowaæ. Bêdziesz musia³ to zrobiæ samemu.}
{252} {} {Ok, zajmê siê tym.}
{253} {} {Zwariowa³eœ?! Samo wyzwolenie ciê z Tu-San by³o bardzo pracoch³onne, a teraz Flagpool...}
{254} {} {Nie mamy wyboru! Jako przysz³y przywódca spo³ecznoœci ponosisz odpowiedzialnoœæ za tych ludzi. Rób to, co MUSISZ zrobiæ!}
{1254} {} {Nie mamy wyboru! Jako przysz³y przywódca spo³ecznoœci ponosisz odpowiedzialnoœæ za tych ludzi. Rób to, co MUSISZ zrobiæ!}
{255} {} {Twoja madre nigdy nie wróci³a z Flagpool. Obawiam siê, ¿e wci¹¿ jest w szponach najemników. Uratuj j¹ za wszelk¹ cenê!}
{256} {} {Mo¿esz na mnie polegaæ, ojcze.}
{257} {} {Madre zmar³a. Nie czekaj na ni¹.}
{258} {} {Porozmawiaj z ludŸmi. Mo¿e nie znam ca³ej sytuacji w Villi.}
{259} {} {Ok.}
{260} {} {(bierze g³êboki oddech, zamykaj¹c oczy) Maria... Czy jesteœ tego pewien? Có¿, lepiej, aby reszta z nas jeszcze nie wiedzia³a, takie wiadomoœci mog¹ dodatkowo pogorszyæ ¿ycie naszych ludzi.}
{261} {} {Co teraz zrobimy?}
{262} {} {Przed nami du¿o pracy. NajeŸdŸcy spl¹drowali osadê, do piwnic dosta³y siê szczury, pod nasz¹ nieobecnoœæ plantacje popad³y w ruinê, ale co najwa¿niejsze, musimy byæ przygotowani na nowe konfrontacje z zagro¿eniem zewnêtrznym.}
{263} {} {[Dalej.]}
{264} {} {Ca³a spo³ecznoœæ musi zdecydowaæ o tej kwestii. Zbieramy siê w ratuszu, przyjdŸ i ty. Twoje doœwiadczenia z podró¿y bêd¹ szczególnie pomocne przy podejmowaniu decyzji. Nie spóŸnij siê.}
{265} {} {Ok, przyjdê.}
{266} {} {Porozmawiaj z ludŸmi na ziemi, mo¿e nie znam ca³ej sytuacji w Villi. I nie zapomnij o spotkaniu spo³ecznoœci. Twoje s³owo bêdzie szczególnie wa¿ne przy podejmowaniu decyzji.}
{267} {} {Ok, przyjdê.}

{270} {} {Rada chce wysadziæ kopalniê Flagpool. Jak ci siê podoba ten pomys³?}
{271} {} {To bardzo ryzykowne, ale trzeba to zrobiæ. I nikt inny tylko ty sobie z tym poradzisz. Jeœli zostawisz kopalniê tak¹, jaka jest, to niewolnictwo tylko siê rozszerzy i pewnego dnia znowu nas zaatakuj¹. Nie jesteœmy wystarczaj¹co silni, aby stawiæ czo³a temu problemowi.}
{272} {} {Rozumiem.}
{273} {} {Rada postanowi³a zniszczyæ fabrykê w Garage City. Co o tym myœlisz?}
{274} {} {Padlino¿ercy zas³uguj¹ na taki los. Ju¿ raz nas zdradzili, zapewniaj¹c najeŸdŸcom wszystko, czego potrzebowali do napadu. Teraz zdecydowali siê uruchomiæ star¹ fabrykê. Jeœli tak siê stanie, wiele stracimy. Stracimy prywatnoœæ, spokojne ¿ycie i nasz styl ¿ycia, który rozwija siê od dziesiêcioleci. Pieprzyæ tê fabrykê!}
{275} {} {Rozumiem.}
{276} {} {Co s¹dzisz o sojuszu z Rangersami?}
{277} {} {Rangersi maj¹ swoje w³asne cele i nie wszystkie s¹ zbie¿ne z naszymi. Ale potrzebujemy sojuszników, aby wzmocniæ nasze si³y. I nie ma nikogo lepszego ni¿ Rangersi. Mo¿emy mieæ tylko nadziejê, ¿e nie bêd¹ ingerowaæ w nasze sprawy wewnêtrzne, ograniczaj¹c siê jedynie do ochrony w zamian za ¿ywnoœæ.}
{278} {} {Mo¿esz mieæ racjê, ojcze.}
{279} {} {Co s¹dzisz o sojuszu z Bractwem Stali?}
{280} {} {Wygl¹da na to, ¿e nie mamy wyboru, prawda? Có¿, jeœli nie mo¿emy pokonaæ wroga, pozostaje tylko uczyniæ go naszym przyjacielem.}
{281} {} {Dobra odpowiedŸ, ojcze.}

# Tlo Villi
{300} {} {Znam Przymierza Za³o¿yciela.}
{301} {} {Có¿, myœla³em, ¿e jest za wczeœnie, ¿ebyœ wiedzia³ o takich rzeczach. Reszta mieszkañców te¿ nie powinna ich czytaæ - nie ma potrzeby obci¹¿ania g³owy pytaniami godnymi tylko liderów. A ty, jako przysz³y przywódca spo³ecznoœci, powinieneœ traktowaæ te Przymierza z nale¿yt¹ starannoœci¹ i szacunkiem.}
{302} {} {Czy ca³kowicie zgadzasz siê z tym tekstem?}
{303} {} {Oczywiœcie. Przestrzegaliœmy Przymierzy przez wszystkie te pokolenia i musimy postêpowaæ zgodnie z nimi w przysz³oœci. Za³o¿yciel by³ m¹drym cz³owiekiem, a jego m¹droœæ wyp³ywa³a z trudnych doœwiadczeñ ¿yciowych. Doœwiadczenie, którego nikt z nas nie ma. Jeœli ka¿e nam porzuciæ star¹ technologiê, to ma to sens i tak siê stanie. Jeœli powie, ¿eby uprawiaæ kukurydzê, bêdziemy w tym mocni. Jeœli uwa¿a ingerencjê reszty œwiata w nasze sprawy za niedopuszczaln¹, to historia najazdu tylko to potwierdza.}
{304} {} {Rozumiem.}
{305} {} {By³em w Krypcie 27. Nigdy o tym nie wspomina³eœ.}
{306} {} {O czym ty mówisz?! To samo schronienie, z którego pochodzili nasi przodkowie?}
{307} {} {Dok³adnie. Jak powiedzia³ Za³o¿yciel, to prawdziwa skarbnica starych technologii...}
{308} {} {Zamknij siê! Za³o¿yciel opuœci³ Kryptê. I ju¿ wiesz dlaczego. Nie mieszaj przesz³oœci. Zapomnij o wszystkim, co mo¿na tam zobaczyæ i us³yszeæ.}
{1308} {} {Zamknij siê! Za³o¿yciel opuœci³ Kryptê. I ju¿ wiesz dlaczego. Nie mieszaj przesz³oœci. Zapomnij o wszystkim, co mo¿na tam zobaczyæ i us³yszeæ.}
{309} {} {Dlaczego tak bardzo boisz siê przesz³oœci?}

{310} {} {Za³o¿yciel uwa¿a³, ¿e spo³ecznoœæ powinna porzuciæ technologiê i wykonywaæ wy³¹cznie pracê fizyczn¹. Dlatego stara³ siê nie mówiæ o Krypcie i jej technologii.}
{311} {} {Ale to nie jedyny problem, wiesz? Ukrad³ pewnego rodzaju Generator i tym samym skaza³ wszystkich tam na cierpienie.}
{312} {} {(w nerwach) To nie ma znaczenia! Uratowa³ swój lud! (uspokajaj¹c siê) Trudne czasy wymaga³y trudnych decyzji. Za³o¿yciel ¿y³ z tym ciê¿arem do koñca swoich dni. Ale to on stworzy³ Villê i da³ ¿ycie tej pustyni. A jeœli ktoœ uzna ten czyn za przestêpstwo, osobiœcie jestem gotów wyrwaæ mu jêzyk.}
{313} {} {Ale ojcze...}
{314} {} {Rozumiem. Wiêcej o tym nie us³yszysz.}

{315} {} {Wystarczy! Z nikim o tym nie rozmawiaj. Ch³opi nie bêd¹ w stanie zrozumieæ, a starsi i ja absolutnie nie chcemy nic wiedzieæ.}
{316} {} {Cokolwiek powiesz, ojcze.}
{317} {} {Có¿, pomyœlê o twoich s³owach.}
{318} {} {Dziêki. Z nikim o tym nie rozmawiaj. Ch³opi nie bêd¹ w stanie zrozumieæ, a starsi i ja absolutnie nie chcemy nic wiedzieæ.}