{100} {} {Widzisz ambasadora.}
{101} {} {Widzisz oficjalnego ambasadora Rangersów.}
{102} {} {Nasz sojusz dobieg³ koñca, ambasadorze.}
{103} {} {Jesteœcie pod nasz¹ ochron¹.}

# Pierwszy dialog
{200} {} {Witaj Guerrero. Mamy sojusz, pamiêtasz? Jesteœmy najlepszymi z najlepszych. Mo¿esz siê teraz zrelaksowaæ i wróciæ do pracy jak zwykle. My Rangersi bêdziemy dbaæ o porz¹dek w Villi i wokó³ niej.}
{201} {} {Myœla³em, ¿e zostanie tu wys³anych wiêcej Stra¿ników.}
{1201} {} {Myœla³am, ¿e zostanie tu wys³anych wiêcej Stra¿ników.}
{202} {} {Nie martw siê, nie jestem sama. Reszta patroluje i eksploruje okolice. W razie potrzeby zawsze mogê ich wezwaæ przez radio.}
{203} {} {Dziêkujê za s³u¿bê, ambasadorze. Muszê iœæ.}
{204} {} {Ok. Ale jeœli k³amiesz, nasz uk³ad siê skoñczy.}

{210} {} {Czeœæ.}
{211} {} {Muszê iœæ.}
