{100} {} {Widzisz ambasadora.}
{101} {} {Widzisz oficjalnego ambasadora Bractwa Stali.}
{102} {} {Nasz sojusz dobieg³ koñca, ambasadorze.}
{103} {} {Jesteœcie pod nasz¹ ochron¹.}

# Pierwszy dialog
{200} {} {Pozdrowienia. Jestem ambasadorem Bractwa Stali. Wiêc uda³o ci siê wci¹gn¹æ swoje plemiê do sojuszu z nami? Dobra robota. Nasza wspó³praca przyniesie wszystkim wiele korzyœci.}
{201} {} {Jesteœ tutaj sam?}
{202} {} {Nie martw siê, mój oddzia³ rozbi³ obóz w pobli¿u pustkowi. Myœleliœmy, ¿e nasza obecnoœæ mo¿e... wp³ywaæ niekorzystnie na miejscowych. W razie potrzeby zawsze mogê wezwaæ ich przez radio.}
{203} {} {Dziêkujê za s³u¿bê, ambasadorze. Muszê iœæ.}
{204} {} {Ok. Ale jeœli k³amiesz, nasz uk³ad siê skoñczy.}

{210} {} {Czeœæ.}
{211} {} {Muszê iœæ.}
