{100} {} {Widzisz Starszego Asystenta.}
{101} {} {Widzisz robota z serii „Starszy Asystent”.}

# Pierwszy dialog
{200} {} {Ach, wreszcie! Dawno nie widzia³em twarzy ¿ywych ludzi. Dziesi¹tki lat samotnoœci nie mijaj¹ bez œladu nawet na po³¹czeniach neuronowych... Kim jesteœ? Opowiesz mi o sobie?}
{201} {} {Jestem }
{202} {} { z Villi. Ale kim... lub czym ty jesteœ?}
{203} {} {Lo siento, mi joven descendiente. Technicznie jestem maszyn¹ z dawnych czasów. Ale co wa¿niejsze, jestem osob¹ Felixa Tejady, twojego bezpoœredniego przodka. Nie martw siê, potomku. Kiedyœ na ca³ym kontynencie by³o du¿o takich robotów.}
{204} {} {To jest coœ niesamowitego.}
{205} {} {Musisz mieæ du¿o pytañ. Mogê na nie odpowiedzieæ, a nastêpnie mo¿esz odpowiedzieæ na moje pytania.}
{206} {} {Naprawdê mam do pana kilka pytañ, panie Robot.}
{207} {} {Muszê siê najpierw rozejrzeæ. Porozmawiajmy póŸniej.}

{210} {} {Ach! Jak mi³o znowu widzieæ œwiat³o s³oñca.}
{211} {} {Mi³o ciê widzieæ, potomku. Pozwól, ¿e przyjrzê siê bli¿ej twojej twarzy.}
{212} {} {Zakoñcz tryb czatu.}
{213} {} {Odpowiedz na kilka pytañ, robocie.}
{214} {} {Co chcesz wiedzieæ, mój drogi potomku?}
{215} {} {To by³y wszystkie pytania.}
{216} {} {Kolejne pytanie.}
{217} {} {Oczekujê na instrukcje.}
{218} {} {Jak smutno... Powiedzia³em nadzorcy, ¿e nie mo¿esz ju¿ mieszkaæ w Krypcie.}
{219} {} {Coraz bardziej zdumiewa mnie gotowoœæ ludzi do wchodzenia w ka¿d¹ dziurê w poszukiwaniu k³opotów. Dlatego tu jesteœmy, prawda?}

{220} {} {Dlaczego siê tu ukrywasz?}
{221} {} {Sam poprosi³em o ukrycie wszystkich starych technologii przed innymi. Kiedy sprowadzi³em moj¹ spo³ecznoœæ do Ziemi Obiecanej, przedmioty ze Starego Swiata pomog³y nam przetrwaæ. Ale czas mija³, a technologie zaczê³y zawodziæ.}
{222} {} {Kontynuuj.}
{223} {} {Nie potrafiliœmy wszystkiego naprawiæ, nie mogliœmy znaleŸæ zamienników ani Ÿróde³ energii. Niezbêdne czêœci nale¿a³oby zdobyæ w niebezpiecznych, napromieniowanych ruinach, a to mia³oby smutny wp³yw na zdrowie mieszkañców. Ponadto z biegiem czasu ludzie tracili wiedzê o Starym Swiecie, a ignorancja prowadzi do smutnych b³êdów.}
{224} {} {S³ucham.}
{225} {} {Postanowi³em chroniæ przysz³ych potomków przed niew³aœciwymi krokami i zakaza³em wszelkich technologii elektronicznych. Patrz¹c na ciebie, teraz rozumiem, ¿e ta decyzja uratowa³a ¿ycie spo³ecznoœci.}
{226} {} {Ciekawy tok myœlenia.}
{227} {} {Co to za miejsce?}
{228} {} {To tutaj? Wygl¹da na to, ¿e przed wojn¹ znajdowa³o siê tu nielegalne sk³adowisko odpadów paliw. Albo po prostu jakiœ bunkier. Tutaj przynajmniej udawa³o nam siê ukrywaæ przed burzami piaskowymi, dopóki Villa nie zakwit³a bujnym kwiatem.}
{229} {} {Rozumiem.}
{230} {} {Powiedz mi, jak powsta³a Villa?}
{231} {} {To d³uga i smutna historia... Szczerze mówi¹c, sam nie wiem wszystkiego. Felix musia³ niechêtnie rozmawiaæ o czymkolwiek. Ale jedno jest jasne - ma to coœ wspólnego z Krypt¹ 27 w pobli¿u Phoenix.}
{232} {} {Ciekawe.}

{233} {} {Jak mam do ciebie mówiæ? Jesteœ... tylko robotem.}
{234} {} {Mów mi Felix, kochany. Czy to dla ciebie a¿ tak ekscytuj¹ce? Có¿, masz racjê. W takim razie Starszy Asystent to pseudonim, który nada³ mi twój przodek.}
{235} {} {Nazwê ciê po prostu robotem.}
{236} {} {Ok, bêdziesz wiêc teraz moim Asystentem.}
{237} {} {Cokolwiek powiesz, dziadku Felix.}

{240} {} {Czy chcia³byœ ze mn¹ podró¿owaæ?}
{241} {} {Oczywiœcie, drogi potomku! Czas rozprostowaæ te stare koœci. Mam nadziejê, ¿e nie biegasz za szybko?}
{242} {} {ChodŸmy, dziadku!}
{243} {} {Asystent jest gotowy, aby pod¹¿aæ za swoim mistrzem.}
{244} {} {PójdŸ za mn¹, robocie.}
{245} {} {Zostañ tutaj i czekaj na dalsze instrukcje.}
{246} {} {Dziadek zaczeka. Nie martw siê o mnie, kochany.}
{247} {} {B¹dŸ mi³y i nie sikaj w spodnie, staruszku.}
{248} {} {Polecenie zaakceptowane. Pozostajê na tym stanowisku do czasu otrzymania dalszych instrukcji.}
{249} {} {Zaczekaj na mnie, robocie.}
{250} {} {Prze³¹cz do trybu protoko³u dialogu.}
{251} {} {W³¹cz spersonalizowany tryb dialogu.}
{252} {} {Personalizacja mowy jest wy³¹czona.}
{253} {} {Tak jest lepiej.}
{254} {} {Whoop, ch³opcze! Co sprawi³o, ¿e wróci³eœ? Ruszamy dalej?}
{1254} {} {Whoop, kochanie! Co sprawi³o, ¿e wróci³aœ? Ruszamy dalej?}
{255} {} {Witaj z powrotem, dziadku.}
{256} {} {Natychmiast usuñ broñ.}