{100} {} {Widzisz Arthura Carringtona.}
{101} {} {Widzisz archeologa z Krypty 27.}

# Pierwszy dialog
{200} {} {Mi³o ciê znowu widzieæ. Muszê ci podziêkowaæ za ten zaszczyt. Twoja Villa otwiera nowe oblicza dla mojej pracy badawczej. I ju¿ jestem zdumiony nowymi odkryciami! Sposób, w jaki radzisz sobie bez zaawansowanych technologii, jest zdumiewaj¹cy dla ka¿dego. Chocia¿ niektóre technologie powinny zostaæ przywrócone do u¿ytku.}
{201} {} {Mo¿e tak.}
{210} {} {Tak, tak?}
{211} {} {Nic. Bywaj.}
{212} {} {Doœæ o tym.}

{220} {} {Jak siê tu czujesz?}
{221} {} {Szczerze, twoi wspó³plemieñcy nie s¹ zadowoleni z obcych. Dzieci œmiej¹ siê z mojej szczup³ej sylwetki, a doroœli unikaj¹ rozmowy. Jesteœ jedynym powodem powstrzymywania ich niezadowolenia. Ale z drugiej strony widzê zainteresowanie. Zainteresowanie tym, co kiedyœ by³o tematem tabu dla Twojej spo³ecznoœci.}
{222} {} {Jak myœlisz, jakie technologie warto przywróciæ?}
{223} {} {Praca fizyczna jest ¿mudna i nieefektywna. Wed³ug moich obliczeñ sam akwedukt zwiêkszy plony o 250% i zmniejszy zasoby pracy o 40%. Niestety naczelnik nie chce mnie s³uchaæ.}
{224} {} {Do tej pory Villa radzi³a sobie bez zaawansowanych technologii.}
{225} {} {Tak, ale jakim kosztem? Choroby, okresowe nieurodzaje, ryzyko obra¿eñ i trudne warunki pracy organizmu to tylko mniejsze problemy, których moglibyœcie unikn¹æ stosuj¹c proste przedwojenne technologie, takie jak pompa czy oœwietlenie elektryczne.}
{226} {} {Czy uwa¿asz, ¿e Villa powinna siê zmieniæ?}
{227} {} {To jest pytanie bez odpowiedzi. Od ciebie zale¿y, czy i jak bêdziesz ¿yæ. Ale któregoœ dnia p³omienie cywilizacji ponownie zapal¹ siê na po³udniu. Czy bêdziesz wtedy w stanie oprzeæ siê takiej walce? W¹tpiê. Nie mog³eœ nawet obroniæ siê przed garstk¹ najemników z prymitywnymi karabinami.}
{230} {} {Jeden z ch³opów le¿y teraz w gor¹cym delirium. Czy mo¿esz go wyleczyæ?}
{231} {} {Bêdê musia³ zrobiæ lekarstwo. Myœlê, ¿e mogê pomóc. Pamiêtaj jednak, ¿e twoi wspó³plemieñcy maj¹ negatywny stosunek do przedwojennej medycyny.}
{232} {} {Nie mamy czasu na myœlenie o takich rzeczach. Wylecz go!}
{233} {} {Spróbujê sam go wyleczyæ.}
{234} {} {Mamy uszkodzon¹ stacjê meteorologiczn¹. Czy mo¿esz to naprawiæ?}
{235} {} {Oczywiœcie. Meteorologia to jedna z moich ulubionych nauk.}
{236} {} {Wiêc zrób to.}
{237} {} {Spróbujê najpiew to naprawiæ bez twojej pomocy.}
