{100} {} {Widzisz Arthura Carringtona.}
{101} {} {Widzisz archeologa w podartej, brudnej szacie. Pomimo swojego nêdznego wygl¹du pozostaje silny.}
{102} {} {Chcia³eœ w³amaæ siê do kryjówki? Wiêc zostañ tu NA ZAWSZE!}

{110} {} {Móg³bym osiedliæ siê tutaj na sta³e.}
{111} {} {Zachowane przedwojenne laboratorium? Niesamowite! Dlaczego wczeœniej nie wiedzia³em o tym miejscu?}
{112} {} {Ciekawe, czy ta elektrownia nadal dzia³a?}
{113} {} {Swiêci Swiêci! Ci barbarzyñcy osiedlili siê w elektrowni jak pluskwy w starym hotelu.}
{114} {} {Nie mogê uwierzyæ w³asnym oczom - ca³a dolina jest wype³niona najcenniejszymi staro¿ytnymi technologiami!}
{115} {} {To wygl¹da na œrodek miejsca pochówku. Z pewnoœci¹ automatyka dzia³a od czasów wojny.}
{116} {} {Ci ludzie nie tylko czytaj¹ ksi¹¿ki. Kim oni s¹?}

# Przed ucieczka (w pomieszczeniu reaktora)
{200} {} {Spodziewa³em siê ekipy ratunkowej z Phoenix, ale kim TY jesteœ?}
{201} {} {Jestem ch³opem z Villi. Moi przodkowie maj¹ coœ wspólnego z tym miejscem. Jestem tutaj, aby dowiedzieæ siê wiêcej.}
{1201} {} {Jestem ch³opk¹ z Villi. Moi przodkowie maj¹ coœ wspólnego z tym miejscem. Jestem tutaj, aby dowiedzieæ siê wiêcej.}
{202} {} {To imponuj¹ce, ¿e uda³o ci siê dotrzeæ tak daleko. Wiesz, s³ysza³em o tej historii z Vill¹. Ale jeœli chcesz poznaæ szczego³³y, pomó¿ mi dokoñczyæ moje sprawy w tym skarbcu.}
{203} {} {Jaki masz tu interes?}
{204} {} {Wiêc to z tob¹ rozmawia³em przez interkom. Twoja praca jest imponuj¹ca. Szkoda, ¿e wczeœniej na siebie nie wpadliœmy.}
{205} {} {Iœæ tak daleko, ¿eby zawróciæ? Nie, nie.}
{206} {} {Dok³adnie tak myœla³em, kiedy rozpocz¹³em ostatni¹ wyprawê. Jak widaæ, to by³ b³¹d.}
{207} {} {Powiedz mi, co siê sta³o.}
{208} {} {Myœlê, ¿e to nie jest odpowiedni moment na rozmowê. Powiem ci wszystko, ale najpierw musisz dokoñczyæ to, co zacz¹³eœ.}
{209} {} {O czym ty mówisz?}
{210} {} {To nie jest czas na rozmowy. Spakuj swoje rzeczy, wychodzimy.}
{211} {} {Ca³kowicie siê zgadzam. Ale najpierw musisz dokoñczyæ to, co zacz¹³eœ.}
{212} {} {Muszê w³amaæ siê na stanowisko dozorcy. Pokój ten znajduje siê o jeden poziom wy¿ej. IdŸ tam. Nie powinniœmy traciæ czasu. A tak, nazywam siê Arthur Carrington. Mi³o ciê poznaæ.}
{213} {} {Czy to naprawdê konieczne...}
{214} {} {Ok. Ale nie wyg³upiaj siê.}
# Przed ucieczka (na stanowisku dozorcy)
{220} {} {Cholera! Czy to serio wszystko?}
{221} {} {Co siê sta³o? Wygl¹dasz na przygnêbionego...}
{222} {} {Hej, mówisz do siebie? W³aœciwie to ja te¿ chcê wiedzieæ.}
{223} {} {Protokó³ zero.}
{224} {} {Protokó³... co?}
{225} {} {Jaki do cholery protokó³?}
{226} {} {Podejrzewa³em, ¿e tak siê to skoñczy³o. D³ugie lata wiêzienia wytr¹ci³y nadzorcê z równowagi i uruchomi³ ³añcuch procedur maj¹cych na celu zniszczenie schronu. Tak zwany „protokó³ zero”.}
{227} {} {Ale czêœæ technologii nadal dzia³a.}
{228} {} {Wygl¹da na to, ¿e jego plany nie odnios³y wiêkszego sukcesu ni¿ twoje.}
{229} {} {Tak, zgadza siê. Podobno mieszkañcy opierali siê dzia³aniom dozorcy i potrafili przerwaæ niektóre procedury. Uratowali ¿ycie, ale skazali siê na wiele lat cierpienia, staj¹c siê... duchami.}
{230} {} {Myœlê, ¿e cierpieli du¿o wczeœniej.}
{231} {} {Jeœli tu zostaniemy, bêdziemy jednymi z nich.}
{232} {} {Tak... oczywiœcie... S³uchaj, muszê wydostaæ siê na powierzchniê. Wygl¹da na to, ¿e nie zosta³o tu nic wartoœciowego. Nie widzê sensu nara¿ania siê na dalsze niebezpieczeñstwo. Razem mamy wiêksze szanse na przebicie siê. Pomo¿esz mi?}
{233} {} {ChodŸ. Najpierw zabiorê ciê na powierzchniê.}
{234} {} {Bardzo dobrze. Ty dowodzisz, szefie. Nie jestem dobry w sprawach militarnych, ale bêdê mieæ oko na ty³y.}
{235} {} {Smia³o.}

# Podczas ucieczki
{250} {} {Nie zwlekaj tutaj.}
{251} {} {PrzejdŸmy dalej.}

{260} {} {Co mo¿esz mi powiedzieæ o tym pokoju?}
{261} {} {To jest poziom reaktora. Kiedyœ reaktor przegrza³ siê i spowodowa³ spontaniczn¹ eksplozjê, niszcz¹c czêœæ poziomu. Na szczêœcie ska³a chroni nas przed silnym promieniowaniem.}
{262} {} {To jest poziom us³ug. Tu znajdowa³o siê centrum zarz¹dzania Krypt¹ i ró¿ne s³u¿by wsparcia. Chcia³bym zobaczyæ ca³y ten blask postêpu technicznego w jego pierwotnej formie.}
{263} {} {To centrum edukacyjne. Biblioteka jest w formie elektronicznej. Niesamowita pomys³owoœæ naszych przodków.}
{264} {} {To jest sala rozrywkowa. Ale wygl¹da na to, ¿e przez przeludnienie nie urz¹dzano tu imprez, ale dos³ownie ¿yto.}
{265} {} {To jest stanowisko nadzorcy, mo¿na by rzec, lokalnego menad¿era. Z tego miejsca mo¿na monitorowaæ wszystkie systemy azylu. Teraz jednak nic tu nie dzia³a - wygl¹da na to, ¿e dozorca zniszczy³ sprzêt awaryjnym impulsem eksplozji.}
{266} {} {To jest jeden z poziomów mieszkalnych. Poza sypialniami nie ma tu nic istotnego.}
{267} {} {Kolejne pytanie.}

{270} {} {Uratowa³eœ mnie. Bez Ciebie móg³bym zostaæ tam na zawsze i staæ siê jednym z tych duchów. Wiesz, teraz zacz¹³em patrzeæ trochê inaczej na ludzkie ¿ycie.}
{1270} {} {Uratowa³aœ mnie. Bez Ciebie móg³bym zostaæ tam na zawsze i staæ siê jednym z tych duchów. Wiesz, teraz zacz¹³em patrzeæ trochê inaczej na ludzkie ¿ycie.}
{271} {} {Tak czy inaczej, teraz mo¿esz pomagaæ ¿yj¹cym.}
{272} {} {Tylko "trochê"? Wygl¹da na to, ¿e ¿ycie niczego ciê nie uczy, naukowcu.}
{273} {} {Jak mo¿esz sobie wyobraziæ, nie mogê Ciê teraz nagrodziæ. Ale kiedy bêdê w Phoenix, na pewno opowiem o tobie swoim przyjacio³om w Katedrze Ognia. Powinieneœ tam zajrzeæ. Ale samemu trudno bêdzie mi dostaæ siê do Phoenix. Mo¿e pójdziemy tam razem?}
{274} {} {Oczywiœcie, chodŸmy do Phoenix. Dlaczego nie?}
{275} {} {Dziêki. Znowu mnie ratujesz. Jeœli chcesz, mogê coœ nieœæ. Chcia³bym zobaczyæ po drodze kilka ciekawych miejsc.}
{276} {} {Swietnie. ChodŸ, Arthur.}
{277} {} {Nie próbuj uciekaæ beze mnie.}
{278} {} {Chêtnie przyjmê ciê do zespo³u. A co z odpowiadaniem na pytania?}
{279} {} {S³ysza³em, ¿e w katedrze by³ problem. Powinniœmy siê poœpieszyæ.}
{1279} {} {S³ysza³am, ¿e by³ problem w katedrze. Powinniœmy siê poœpieszyæ.}
{280} {} {W³aœciwie to nie jest mi to po drodze. I nie s¹dzê, ¿eby w najbli¿szym czasie Phoenix by³o moim celem podró¿y.}
{281} {} {W porz¹dku. Zabierz mnie do najbli¿szej osady, a potem sam znajdê drogê. Jeœli chcesz, mogê coœ nieœæ. Uwielbiam te¿ zwiedzaæ po drodze ciekawe miejsca.}
{282} {} {Mogê Ciê przyj¹æ do zespo³u. ChodŸ, Arthur.}
{283} {} {Wiêc bêdziesz nosiæ wszystkie moje rzeczy. I nie jêcz. Naprzód!}
{284} {} {Witamy w zespole. Czy mo¿emy teraz porozmawiaæ?}

# Po ucieczce
{300} {} {Jak siê masz szefie?}
{301} {} {Ok, spójrzmy na te równania... Och, czy czegoœ mi brakuje?}
{302} {} {Nigdy nie ma wystarczaj¹cej liczby odpowiedzi.}
{303} {} {Chcesz ponownie uzyskaæ m¹dr¹ radê?}
{304} {} {Czy jesteœmy ju¿ w Phoenix?}
{305} {} {Hej szefie, twoja trasa nie wydaje siê byæ wystarczaj¹co dok³adna.}
{306} {} {Czego chcesz?}
{307} {} {Moje plany zosta³y udaremnione dawno temu.}
{308} {} {Nie mam nic przeciwko rozmowie. Ale czy mo¿emy j¹ trochê wzbogaciæ ³acin¹?}
{309} {} {PrzejdŸmy dalej, Arthur.}

{310} {} {Coœ mi nie pasuje. Wydaje siê, ¿e to konsekwencje zatrucia.}
{311} {} {Pozwól mi... Teraz pochyl siê... Teraz to... Czy teraz jest lepiej?}
{312} {} {Tak... Dziêki doktorze.}

#Zapytania
{320} {} {Mam do ciebie wiele pytañ.}
{321} {} {Och, oczywiœcie. Mam mnóstwo odpowiedzi.}
{322} {} {Oczywiœcie. Odpowiem na wszelkie pytania.}
{323} {} {Te odpowiedzi s¹ wystarczaj¹ce.}
{333} {} {Kolejne pytanie.}
{334} {} {Gdzie jest miasto Phoenix?}
{335} {} {Naprawdê nie wiesz? To dziwne... Trzymaj Pip-Boya, poka¿ê Ci to miasto na mapie.}
{336} {} {Dziêki.}

{350} {} {Opowiedz mi o sobie.}
{351} {} {Nie przedstawi³em siê jeszcze? Arthur Carrington, lider wyprawy. Do pewnego stopnia jestem wolnym naukowcem, jeœli wolisz.}
{352} {} {Gdzie zdoby³eœ wykszta³cenie?}
{353} {} {Moi rodzice nauczyli mnie podstaw pisania i obs³ugi komputera. To rzadkoœæ w naszej okolicy, wiêc wielu ludzi w Phoenix korzysta³o z moich us³ug. Kiedy kult czcicieli ognia sta³ siê g³ow¹ miasta, otrzyma³em nowe mo¿liwoœci pobierania nauk, o których wczeœniej mog³em tylko pomarzyæ.}
{354} {} {Kim byli twoi rodzice?}
{355} {} {Myœlê, ¿e byli potomkami tych, którzy opuœcili Kryptê. Chocia¿ nie mówili o tym bezpoœrednio.}
{356} {} {Dlaczego wybra³eœ siê na ekspedycjê?}
{357} {} {Ludzie z Katedry Ognia szukali ludzi do zwiadu. Ich zainteresowania by³y zbyt... materialistyczne. Potrzebowali tylko rzeczy praktycznych - takich jak stary sprzêt, Ÿród³a energii, broñ. Jako naukowiec spojrza³em na rzeczy szerzej. Krypta mog³aby nam wiele powiedzieæ o Starym Swiecie i pomóc w rozwoju Nowego. Nie nale¿y tak lekkomyœlnie rzucaæ staro¿ytnymi relikwiami.}

{360} {} {Opowiedz mi, co siê sta³o z wypraw¹.}
{361} {} {Niezbyt przyjemny temat do omówienia. Po zejœciu do Krypty podzieliliœmy siê na dwie grupy. Zadaniem pierwszej by³o monitorowanie generatora zapasowego, a drugiej zejœcie ze mn¹ do pomieszczenia reaktora g³ównego. Po podziale sprawy nie potoczy³y siê zgodnie z planem.}
{362} {} {Co siê sta³o z Twoj¹ grup¹?}
{363} {} {Zeszliœmy do poziomu reaktora i zaczêliœmy sprawdzaæ pomieszczenia. Ale w jednym z nich by³a pu³apka. Eksplozja zabi³a moich podw³adnych, a mnie og³uszy³a. Kiedy siê obudzi³em, winda zosta³a podniesiona, odciêto pr¹d, a pierwsza grupa nie dawa³a znaku ¿ycia.}
{364} {} {Co siê sta³o z pierwsz¹ grup¹?}
{365} {} {Grupa zosta³a najprawdopodobniej zaatakowana przez duchy. Prawdopodobnie wiesz wiêcej ni¿ ja. W ka¿dym razie generator nie móg³by sam pracowaæ na sucho. Oczywiœcie jeden z duchów wyci¹gn¹³ stamt¹d ogniwa energetyczne i tym samym zostawi³ mnie w pu³apce.}
{366} {} {Zbada³em cia³a ludzi z twojej grupy. Jeden z nich mia³ ranê postrza³ow¹ g³owy. Co mi o tym powiesz?}
{1366} {} {Zbada³am cia³a ludzi z twojej grupy. Jeden z nich mia³ ranê postrza³ow¹ g³owy. Co mi o tym powiesz?}
{367} {} {Dlaczego musisz wtykaæ nos w nie swoje sprawy? Tak, nie tylko ja prze¿y³em. Drugi cz³onek wyprawy zosta³ kontuzjowany, ale opieka nad nim wymaga³aby wszystkich moich œrodków. Nie mog³em sobie na to pozwoliæ.}
{368} {} {Wygl¹da bardziej na to, ¿e dla bezpieczeñstwa zosta³eœ z ty³u i pozwoli³eœ swoim ludziom robiæ za *zabezpieczenie*.}
{369} {} {Ostro¿noœæ pozwoli³a mi do¿yæ mego wieku. Dopiero tutaj, w Krypcie, zap³ci³em cenê za swoj¹ ambicjê. Musia³em jednak dzia³aæ zdecydowanie, bo ekspedycja by³a zagro¿ona - w ka¿dej chwili kult móg³ przestaæ mnie finansowaæ lub wys³aæ dla mnie zastêpstwo. Nie mog³em straciæ pracy mojego ¿ycia!}

{370} {} {Co wiesz o duchach?}
{371} {} {Niezwyk³a forma ghulifikacji. Jest to spowodowane wieloma czynnikami, które mia³y miejsce po uruchomieniu „protoko³u zero”: truj¹ce gazy i wirusy w powietrzu, stosowanie masek przeciwgazowych, promieniowanie, przyjmowanie niektórych leków i wiele innych. }
{372} {} {Czy zauwa¿y³eœ, ¿e ja te¿ taki jestem?}
{1372} {} {Czy zauwa¿y³eœ, ¿e ja te¿ taka jestem?}
{373} {} {Tak, i prawie rozpozna³em ciê jako ducha, kiedy ciê zobaczy³em. Gratulacje, czeka Ciê d³ugie ¿ycie.}

{380} {} {Obieca³eœ opowiedzieæ mi o zwi¹zku Krypty i Villi.}
{381} {} {Przepraszam, sk³ama³em, ¿eby daæ ci powód do ratowania mnie. Nie wiem nic o Villi ani o tym, jak siê tam dosta³y rzeczy z Krypty. Najprawdopodobniej dawno temu ktoœ opuœci³ Kryptê, a potem jego dobytek trafi³ do ciebie. To jest jedna z opcji.}
{382} {} {[Dalej.]}
{383} {} {Jeœli chcesz siê czegoœ dowiedzieæ to musisz zejœæ na dó³ i poszukaæ czegoœ, co da Ci odpowiedŸ. Tutaj, weŸ kartê dostêpu, otworzy zamkniête drzwi.}
{384} {} {Nie powinieneœ by³ mnie ok³amywaæ. To jest pierwsze i ostatnie ostrze¿enie.}
{385} {} {Dziêki przynajmniej za to. Muszê zobaczyæ, co tam jest.}
{386} {} {Wracasz do tego przeklêtego miejsca? Och, to bêdzie mêka.}

{390} {} {Co zamierzasz teraz zrobiæ?}
{391} {} {Zrobiê du¿y raport i spróbujê wydobyæ wiêcej zasobów dla kultu, aby dokoñczyæ ekspedycjê. Potrzebujê niezawodnego stra¿nika, który oczyœci Kryptê pe³n¹ duchów i now¹ grupê niewolników.}
{392} {} {Rozumiem. Rób co chcesz.}
{393} {} {Ty i twoja ambicja zabiliœcie wielu ludzi. Naprawdê chcesz kontynuowaæ?}
{394} {} {Choæ brzmi to okrutnie, ¿ycie najemników i niewolników by³o mniej warte ni¿ dziedzictwo staro¿ytnoœci. Pomyœl tylko, jakie perspektywy otworz¹ siê, jeœli wrócimy do Phoenix z dawno zapomnian¹ technologi¹!}
{395} {} {Czy technologia pomog³a lokalnym duchom?}
{396} {} {Nie, nie pomog³a. I co z tego, co? To nic innego jak g³upota jednej konkretnej osoby w Krypcie ich zabi³a - dozorcy.}
{397} {} {Ok. Tak jak mówisz.}
{398} {} {Technologia nie uratowa³a mieszkañców Krypty. Wrêcz przeciwnie, skaza³a ich na wieczne cierpienia.}
{399} {} {Co przez to rozumiesz?}
{400} {} {Technologia nie uratuje zgni³ego spo³eczeñstwa. Ale wywo³a wojny wokó³ staro¿ytnych artefaktów.}
{401} {} {Hmm... Nie myœla³em o tym. Spo³eczeñstwo Phoenix przechodzi reformacjê poprzez kult Ognia. Wprowadzenie staro¿ytnej technologii by³o bardzo korzystne, ale jednoczeœnie podzieli³o populacjê... Mo¿e powinienem przeczytaæ wiêcej ksi¹¿ek o socjologii?}
{402} {} {Tak tylko g³oœno myœlê. Zapomnij.}
{403} {} {To koñczy nasz¹ rozmowê. Bywaj.}
{404} {} {Dobrze, ¿e doszliœmy do porozumienia. A teraz odpowiedz mi na inne pytania.}

# PRZESYLKA
{450} {} {Potrzebujê ciê. ChodŸ ze mn¹.}
{451} {} {Nie, szefie. Zbyt wiele osób. To uniemo¿liwia mi skupienie siê na myœleniu o moim wielkim planie.}
{452} {} {To Ÿle.}
{453} {} {Czas siê rozstaæ.}
{454} {} {Czy zostawisz mnie w takim stanie po wszystkich naszych przygodach? W porz¹dku. Zostanê tu przez chwilê i bêdê czytaæ moje pisma, dopóki nie zmienisz zdania.}
{455} {} {Bywaj.}
{456} {} {Mo¿esz zdj¹æ zbrojê.}
{457} {} {Dziêki, szefie. Jest tu strasznie duszno.}
{458} {} {To wszystko.}
{459} {} {Ukryj swoj¹ broñ.}
{460} {} {Hmm. Cokolwiek powiesz, szefie.}
{461} {} {To wszystko.}
{462} {} {Mogê wróciæ po ciebie póŸniej.}
{463} {} {Dotarliœmy do Phoenix. Wiesz, gdyby w mojej wyprawie byli tacy ludzie jak ty, nie zawiód³bym.}
{464} {} {Co zamierzasz teraz zrobiæ?}
{465} {} {Mam du¿o do zrobienia. Najpierw muszê spotkaæ siê z klientem i zdaæ raport z wyników. To zajmie kilka dni. Do tego czasu proszê mi nie przeszkadzaæ.}
{466} {} {Ok. Do zobaczenia za... dwa dni.}
{467} {} {Witaj mój Zbawicielu.}
{468} {} {Do widzenia, Arthurze.}

{470} {} {Oto mój wybawca. Cieszê siê, ¿e ciê widzê.}
{1470} {} {Oto mój wybawca. Cieszê siê, ¿e ciê widzê.}
{471} {} {Jak tam raport? Nie jesteœ chyba zbyt szczêœliwy.}
{472} {} {Ju¿ nikt nie chce wyników mojej wielomiesiêcznej pracy. Swi¹tynia Ognia zosta³a zniszczona. Nie wiem, co siê tam sta³o, ale czciciele ognia s¹ teraz na wygnaniu i nikt nie potrzebuje ju¿ naukowca takiego jak ja.}
{473} {} {Na pewno?}
{474} {} {Mam pewn¹ informacjê. W katedrze natkn¹³em siê na sk¹pe doniesienia o mieœcie uczonych gdzieœ na po³udniu, ale to trochê ma³o. Chcê tam pojechaæ, aby w koñcu znaleŸæ szczêœcie. Jeœli zmierzasz w tym kierunku, daj mi znaæ.}
{475} {} {To musi byæ trudna œcie¿ka. Pomyœlê o tym.}
{476} {} {A tak przy okazji, uda³o mi siê z³apaæ w laboratorium antyrady i u¿ywki. Potraktuj to jako wyraz wdziêcznoœci za moje uratowanie.}
{477} {} {Do zobaczenia.}
{480} {} {Czy to jest to miejsce, o którym wspomnia³eœ?}
{481} {} {Na to wygl¹da! Miasto nauki i postêpu. Prawdziwy cud na œrodku pustyni. Nawet powietrze tutaj pachnie inaczej. W³aœnie tego potrzebujê do moich badañ.}
{482} {} {Wiêc czas siê po¿egnaæ?}
{483} {} {Tak, sprawdŸ nasze plecaki, czy mam tam jakieœ twoje rzeczy. Ja idê do Wyznawców Apokalipsy dowiedzieæ siê wiêcej.}
{484} {} {[Dalej.]}
{485} {} {Mi³o ciê widzieæ. Nigdy nie myœla³em, ¿e cz³owiek z pustkowia nauczy mnie najwa¿niejszej rzeczy - doceniaæ ¿ycie ludzi. Wczeœniej stawia³em wszystko ponad chwa³ê nauki. Czas zrobiæ coœ naprawdê po¿ytecznego.}
{486} {} {Do widzenia Arthurze.}
{487} {} {Klient by³ bardzo niezadowolony z wyników mojej wielomiesiêcznej pracy. Zosta³em skarcony za marnotrawstwo i nieefektywnoœæ, a nawet zaproponowano, ¿e spalê siê na stosie. Ale sk¹d mog³em wiedzieæ, ¿e te „duchy” bêd¹ w schronie? Sk¹d mog³em wiedzieæ, ¿e sama Krypta jest w takim stanie? Wydatki na wyprawê nie zosta³y uzasadnione. Tak mi powiedzieli. Pieprzone kapsle! Wygl¹da na to, ¿e moja kariera naukowa tutaj siê skoñczy³a.}