{100} {} {Widzisz terminal biblioteczny.}
{101} {} {Widzisz terminal z dostêpem do biblioteki elektronicznej. Niestety obecnie nie dzia³a.}

{110} {} {Widzisz terminal z dostêpem do biblioteki elektronicznej. Niestety obecnie nie dzia³a.}
{111} {} {Za pomoc¹ tego terminala mo¿esz uzyskaæ dostêp do elektronicznej biblioteki Krypty.}
{112} {} {Uda³o Ci siê przywróciæ terminal biblioteczny do ¿ycia.}
{113} {} {Terminal biblioteczny jest wy³¹czony. Aby go uruchomiæ, musisz przywróciæ zasilanie.}