{102} {} {* Syczenie *}
{103} {} {Interkom jest niezwykle trudny do obs³ugi podczas walki.}

# Pierwszy dialog
{200} {} {(z interkomu dochodzi s³aby, ale uspokajaj¹cy g³os) Witaj! Czy mnie s³yszysz? Z kim mam kontakt?}
{201} {} {Halo? Czy to mówi?}
{202} {} {Huh? Mówisz do mnie z pude³ka? Chyba pójdê sobie dalej.}
{203} {} {Cholera. Spodziewa³em siê pomocy z Phoenix... Ale tak mo¿e byæ lepiej. Powiedz mi, wêdrowcze, dlaczego tu jesteœ? Szukasz czegoœ?}
{1203} {} {Cholera. Spodziewa³em siê pomocy z Phoenix... Ale tak mo¿e byæ lepiej. Powiedz mi, wêdrowcze, dlaczego tu jesteœ? Szukasz czegoœ?}
{204} {} {Myœla³em, ¿e w tym miejscu znajdê historiê moich ludzi. Villa mia³a przedmioty z Krypty 27. To prawdopodobnie to samo miejsce.}
{205} {} {Villa... Tak, wiem o czym mówisz. Wiem, jak ci pomóc.}
{206} {} {Swietnie! Powiedz mi, gdzie mam iœæ?}
{207} {} {Nie œpiesz siê. Pomó¿ mi najpierw. Utkn¹³em na ni¿szym poziomie i nie wyjdê st¹d sam. Wszystko, co musisz zrobiæ, to znaleŸæ generator zapasowy na poziomie mieszkalnym i uruchomiæ go.}
{208} {} {Najpiew odpowiedz, mam kilka pytañ.}
{209} {} {Ok, spróbujê.}

# Drugi dialog
{210} {} {Dobrze, ¿e wci¹¿ tu jesteœ. Ale poœpiesz siê, zanim siê uduszê.}
{211} {} {Mam mnóstwo pytañ.}
{212} {} {Koniec komunikacji.}
{213} {} {Kolejne pytanie.}

{214} {} {Swietnie. Skorzystaj z interkomu, aby siê ze mn¹ skontaktowaæ, jeœli to konieczne.}
{215} {} {Do nastêpnego razu.}
{216} {} {Interkom nie odpowiada.}
{217} {} {[wyjdŸ]}

# Odpowiedzi
{220} {} {Pytaj.}
{221} {} {Kim jesteœ?}
{222} {} {Arthur Carrington, lider wyprawy. Badaliœmy tê kryjówkê pod k¹tem przydatnych zasobów. Prawdopodobnie natkn¹³eœ siê ju¿ na nasze rzeczy w pobli¿u tunelu.}
{223} {} {Jak d³ugo mo¿esz pozostaæ w pu³apce?}
{224} {} {Trudno powiedzieæ. Mam zapasy ¿ywnoœci i wody. Problem z powietrzem zosta³ rozwi¹zany, ale nie na d³ugo.}
{225} {} {Dlaczego interkom dzia³a, jeœli w Krypcie nie ma zasilania?}
{226} {} {Staro¿ytni in¿ynierowie byli sprytni. Po³¹czyli interkomy z komponentami konwencjonalnej krótkofalówki i zaopatrzyli je w baterie o d³ugiej ¿ywotnoœci. Jak widaæ dobrze zrobili.}
{227} {} {Co muszê wiedzieæ przed zejœciem do bunkra?}
{228} {} {Jest tu strasznie ciemno bez œwiat³a. Powietrze jest zatrute, ale maska przeciwgazowa rozwi¹¿e ten problem. I weŸ swoj¹ broñ... na wszelki wypadek.}
{229} {} {Dlaczego broñ?}
{230} {} {Sugerujê tylko, ¿ebyœ by³ ostro¿ny. To stara Krypta. Ja sam nie znam wszystkich jej tajemnic.}
{231} {} {Nic mi nie powiedzia³eœ o tych okropnych ludziach w maskach gazowych!}
{232} {} {Ludziach? To cienie przesz³oœci. Obudziliœmy ich, kiedy zeszliœmy na dó³. A¿ trudno uwierzyæ, ¿e wci¹¿ ¿yj¹... jeœli w ogóle mo¿na ich uwa¿aæ za ¿ywych.}
{233} {} {Wiêc wiedzia³eœ!}
{234} {} {Przepraszam, powinienem ciê ostrzec, ale wtedy móg³bym straciæ jedyn¹ nadziejê na ratunek. Nie rozumiesz?}

#Ratunek
{240} {} {Wiêc co muszê zrobiæ?}
{241} {} {ZnajdŸ generator zapasowy na poziomie mieszkalnym i uruchom go. Jeœli potrzebna bêdzie zapasowa bateria lub ogniwo, mo¿e znajdowaæ siê w magazynie na ni¿szym poziomie.}
{242} {} {Widzê, ¿e uda³o ci siê uruchomiæ generator. Teraz znajdŸ system wentylacji gdzieœ na tym samym poziomie i spróbuj go uruchomiæ. Powinno to oczyœciæ powietrze ze szkodliwych gazów.}
{243} {} {Czy powietrze jest ju¿ oczyszczone? Doskonale! ZejdŸ na ni¿szy poziom i znajdŸ drug¹ windê w centrum sterowania. Bêdê tam na ciebie czekaæ. Jeœli coœ siê stanie po drodze, skontaktuj siê ze mn¹ przez interkom.}
{244} {} {Mamy problem. W drodze do windy zebra³ siê t³um oszala³ych ludzi!}
{245} {} {Mamy problem. W drodze do windy zebra³ siê t³um duchów.}
{246} {} {To s¹ prawdziwe duchy. Musisz z nimi bardzo uwa¿aæ. Nie powinniœmy teraz ryzykowaæ, lepiej nie anga¿owaæ siê w walkê.}
{247} {} {Mo¿e odwróciæ ich uwagê?}
{248} {} {Te¿ o tym myœla³em... Rozejrzyj siê po s¹siednich pokojach i spróbuj odpaliæ tam jakiœ stary sprzêt, który narobi du¿o ha³asu. I staraj siê nie daæ zobaczyæ duchom.}
{249} {} {Ok.}