{100}{}{Widzisz Jose Solisa.}
{101}{}{Widzisz przed sob¹ ghula w przedwojennym kostiumie. Wygl¹da znacznie schludniej i czyœciej ni¿ inne ghule.}
{102}{}{Wygl¹da na to, ¿e jesteœ tu nowy. Czy zechcia³byœ postawiæ mi drinka i opowiedzieæ coœ o sobie?}
{103}{}{Moje marzenia o „Mariachi Jose Solisie” siê skoñczy³y.}
{104}{}{„Mariachi Jose Solis” wraca do akcji!}
{105}{}{Nie przeszkadzaj mi, jestem zajêty prób¹. Cii! Ciiii!}

{200}{}{Witaj, cz³owieku. S³ysza³em, ¿e w mieœcie pojawi³ siê normalny, ale myœla³em, ¿e to kolejny g³upi ¿art starców. A teraz tu stoisz, oœlepiaj¹c bia³¹ skór¹ i sprawiaj¹c, ¿e przypominam sobie dawne czasy. A tak przy okazji, nazywam siê Jose Solis. A ty?}
{201}{}{Jestem }
{202}{}{.}
{203}{}{Cholera, mi³o mi ciê poznaæ, }
{204}{}{. Jak podoba Ci siê nasz ma³y zak¹tek piek³a? Ju¿ siê nudzisz?}
{205}{}{Jestem }
{206}{}{. Zapamiêtaj to imiê, ghulu.}
{207}{}{OK, OK, }
{208}{}{. Widzê, ¿e nie podoba ci siê tutaj. Czy nie mam racji?}
{209}{}{Dobrze. Mo¿esz ¿yæ.}
{210}{}{Dziwnie to s³yszeæ od normalnego. Wygl¹da na to, ¿e chcesz mnie owin¹æ sobie wokó³ palca. OK. To czego tu chcesz?}
{211}{}{Trochê tu nudno.}
{212}{}{Zgadza siê! Te¿ chcê trochê wstrz¹sn¹æ tym miejscem. Wiêc czego tu szukasz?}
{213}{}{Niewa¿ne. Tylko siê rozgl¹dam. Do widzenia.}
{214}{}{Czy mogê zadaæ Ci kilka pytañ?}
{215}{}{Witaj, przyjacielu w nieszczêœciu! S³ysza³em, ¿e w mieœcie jest nowy, ale nie z Nekropolis. Niesamowita sprawa. A tak przy okazji, nazywam siê Jose Solis. A ty?}
{1215}{}{Witam, piêkna damo! S³ysza³em, ¿e w mieœcie jest nowa, ale nie z Nekropolis. Wiesz, jak zaskoczyæ starszego mê¿czyznê. A tak przy okazji, nazywam siê Jose Solis. A ty?}
{216}{}{Tak, chyba. To nawet lepsze ni¿ Nekropolis. Ale to dopiero pocz¹tek! Któregoœ dnia przywrócimy miastu jego pierwotn¹ postaæ – wszyscy wtedy strac¹ g³owy ze szczêœcia. Jak mogê Ci pomóc?}
{217}{}{Zgadza siê! Te¿ chcê trochê wstrz¹sn¹æ tym miejscem. Wiêc jak mogê Ci pomóc?}

{220}{}{Witaj, przyjacielu w nieszczêœciu!}
{1220}{}{Witam, kochanie!}
{221}{}{Pozdrowienia, }
{222}{}{.}
{223}{}{Jak mogê Ci pomóc, }
{224}{}{?}
{225}{}{Znam ciê, }
{226}{}{. Jesteœ jedynie problemem. Zrób coœ m¹drego i mi nie przeszkadzaj.}
{227}{}{Witam, Panie Normalny.}
{1227}{}{Witam, Pani Normalna.}
{228}{}{Pozdrowienia, }
{229}{}{. Mam nadziejê, ¿e jesteœ na tyle m¹dry, aby nie sprawiaæ tutaj k³opotów.}
{230}{}{Prawdopodobnie powinienem ju¿ iœæ.}
{231}{}{No có¿, dziêki za rozmowê. Ostatni normalni nie chcieli z nami rozmawiaæ, tylko odrazu przywitali nas ze wszystkich luf. Bardzo nietowarzyscy goœcie.}
{232}{}{Do widzenia.}

{240}{}{Oczywiœcie.}
{241}{}{Tylko jeœli w koñcu mnie po tym zostawisz.}
{242}{}{Co tu siê dzieje?}
{243}{}{Nic specjalnego. Zwyk³e, rutynowe ¿ycie w du¿ym mieœcie.}
{244}{}{Hmm. OK.}

{250}{}{Podoba Ci siê tutaj?}
{251}{}{Ladne miasto. Dobry klimat, dobrzy ludzie. Ale wiesz, San Diego s³ynê³o kiedyœ ze swojego ¿ycia kulturalnego. Teraz s³ychaæ tu tylko licznik Geigera.}
{252}{}{Tak, te¿ wola³bym us³yszeæ kogoœ na ¿ywo.}
{253}{}{Zartujesz? Ruiny te maj¹ setki lat. Nie ma tu nawet z kim pogadaæ.}
{254}{}{Wiêc uœmiechnij siê, kochanie. Przed tob¹ stoi sam Jose Solis! Mój zespó³ by³ znany w ca³ej Baja California. To by³ dobry czas. Graliœmy akurat koncert w Bakersfield, kiedy na miasto spad³y bomby. Cudem prze¿y³em. W³aœnie myœlê o powrocie do mojego starego rzemios³a.}
{255}{}{Co ciê powstrzymuje?}
{256}{}{No có¿, najpierw potrzebujê nowych strun do gitary. Jest teraz w moim pokoju. A znalezienie ich wœród tych ruin nie jest takie proste.}
{257}{}{Znajdê te struny. Dla mnie nie ma niczego, czego nie mo¿na znaleŸæ w starych miastach.}
{258}{}{Dziêkujê, senor! Razem przypomnimy Blasku dawne czasy.}
{1258}{}{Dziêkujê, senorita! Razem przypomnimy Blasku dawne czasy.}
{259}{}{Do widzenia.}
{260}{}{Czy mo¿esz mi zap³aciæ za tê pracê?}
{261}{}{Szczerze mówi¹c, nie mam teraz ¿adnych kapsli. A co powiesz na udzia³ w pierwszych tantiemach?}
{262}{}{Zajmujê siê interesami. Znajdê te twoje struny.}
{263}{}{Nie potrzebujê kapsli ani dodatkowych k³opotów.}
{264}{}{Przykro mi, to nie dla mnie. Do widzenia.}
{265}{}{Czy wiesz, gdzie mogê znaleŸæ struny do gitary?}
{266}{}{Zwiedzi³em ju¿ wszystkie tutejsze ruiny, nie ma tu nic. Pozostaje odwiedziæ Tijuane. Kiedyœ znajdowa³o siê tam muzeum mariachi i kilka œwietnych scen, na których odbywa³y siê wystêpy. Ale teraz s¹ tam tylko t³umy robotów i mutantów.}
{267}{}{W takim razie Tijuana. Wszystko jasne.}
{268}{}{Wyprobówa³eœ ju¿ nowe struny do gitary?}
{269}{}{Och, brzmi¹ œwietnie! Poza tym moja sztywna skóra jest na nie odporniejsza. Dziêkujê, mój g³adkoskóry amigo.}
{270}{}{Rozumiem. Kiedy nastêpny wystêp?}
{271}{}{Nie œpiesz siê tak! Nie przygotowa³em siê jeszcze nale¿ycie. A co najwa¿niejsze, nie mogê wyst¹piæ bez moich ukochanych towarzyszy!}
{272}{}{Wiêc oni te¿ s¹ tutaj, w Blasku?}
{273}{}{Fernando, trêbacz, pracuje przy tamie, a Senorita Beatriz pracuje w jad³odajni w po³udniowym obozie. Na pewno bêdziesz przechodziæ obok i mi ich przyprowadzisz, prawda?}
{274}{}{OK. Dlaczego nie?}
{275}{}{Jeœli przyprowadzê twoich towarzyszy, co za to dostanê?}
{276}{}{Zajmujê siê interesami. Przyprowadzê twoich towarzyszy.}
{277}{}{Nie mogê siê doczekaæ!}
{278}{}{Do widzenia.}
{279}{}{Gdzie mogê znaleŸæ Fernando?}
{280}{}{Fernando pracuje przy zaporze Bonita.}
{281}{}{Gdzie mogê znaleŸæ Beatrice?}
{282}{}{Senorita Beatrice pracuje w restauracji w San Ysidro.}
{283}{}{Rozumiem. Mam inne pytania.}
{284}{}{Do widzenia.}
{285}{}{Fernando i Beatrice ju¿ tu s¹.}
{286}{}{Swietnie! Mam z nimi o czym rozmawiaæ. PrzyjdŸ na nasz pierwszy koncert w ci¹gu dnia.}
{287}{}{OK. Udanej próby.}
{288}{}{Fernando ju¿ tu jest. Ale Beatrice nie ¿yje.}
{289}{}{Biedna Beatrice! W koñcu poczu³a siê wyczerpana tym ¿yciem. Jestem nawet trochê zazdrosny...}
{290}{}{Beatrice ju¿ tu jest. Ale Fernando nie ¿yje.}
{291}{}{Biedny Fernando! W koñcu poczu³ siê wyczerpany tym ¿yciem. Jestem nawet trochê zazdrosny...}
{292}{}{Biada mi! Mój sen wymyka mi siê z r¹k jak popió³ miêdzy palcami... S³uchaj, a co z hologramem? Wiem, ¿e jest taki w centrum handlowym Chula Vista. Mo¿e on zast¹pi mi brakuj¹cych cz³onków? Przyniesiesz modu³ holograficzny? Prawdopodobnie uda mi siê go ponownie skonfigurowaæ do moich celów.}
{293}{}{Naprawdê? OK, trzeba bêdzie poszukaæ tej rzeczy, bo inaczej i ty siê zabijesz.}
{294}{}{Mam modu³ holograficzny. Jest tutaj.}
{295}{}{Fernando i Beatrice nie ¿yj¹.}
{296}{}{Fernando i Beatrice nie ¿yj¹. Bardzo mi przykro.}
{297}{}{Swietnie! Potrzebujê czasu, ¿eby siê przygotowaæ. PrzyjdŸ na nasz pierwszy koncert w ci¹gu dnia.}
{298}{}{OK. Udanej próby.}
{299}{}{To stary }
{1299}{}{To moja bogini inspiracji, }
{300}{}{! To tak, jakbyœ zabra³ mnie z powrotem do roku 2077. Ju¿ dawno nie by³em taki szczêœliwy. Swoj¹ drog¹, nieŸle zarobiliœmy na tym wystêpie. Oto twój udzia³, 1000 kapsli. Dziêkujê za pomoc, partnerze.}
{1300}{}{! To tak, jakbyœ zabra³a mnie z powrotem do roku 2077. Ju¿ dawno nie by³em taki szczêœliwy. Swoj¹ drog¹, nieŸle zarobiliœmy na tym wystêpie. Oto twój udzia³, 1000 kapsli. Dziêkujê za pomoc, senora.}
{301}{}{Powodzenia, Jose.}
{302}{}{! To tak, jakbyœ zabra³ mnie z powrotem do roku 2077. Ju¿ dawno nie by³em taki szczêœliwy. Swoj¹ drog¹, nieŸle zarobiliœmy na tym wystêpie. Oto twój udzia³, 1000 kapsli. A ode mnie osobiœcie - ta piêkna, stuletnia whisky. Dziêkujê za pomoc, partnerze.}
{1302}{}{! To tak, jakbyœ zabra³a mnie z powrotem do roku 2077. Ju¿ dawno nie by³em taki szczêœliwy. Swoj¹ drog¹, nieŸle zarobiliœmy na tym wystêpie. Oto twój udzia³, 1000 kapsli. A ode mnie osobiœcie - ta piêkna, stuletnia whisky. Dziêkujê za pomoc, senora.}
{303}{}{Jak nazwiesz swoj zespó³?}
{304}{}{Hmm, potrzebujê czegoœ romantycznego. Mo¿e „Ostatni oddech”? Albo „Mi³oœæ w piekle”? A mo¿e „Poca³uj zanim umrzesz”? A co z...}
{305}{}{Myœlê, ¿e ³atwiej by³oby nazwaæ j¹ twoim imieniem.}
{306}{}{Mariachi de Jose Solis? Ale¿ oczywiœcie!}
{307}{}{To mi³o...}
{308}{}{Przy okazji, jak nazywa siê ten zespó³?}