{100}{}{Widzisz Beatrice.}
{101}{}{Przed sob¹ widzisz ghula w niegdyœ piêknej sukience.}
{102}{}{}
{103}{}{Widzisz tego przystojnego faceta za lad¹? Robi œwietne jajka... Och, mam nadziejê, ¿e mnie dobrze rozumiesz.}
{104}{}{Hej, co siê sta³o z Jose? Nie móg³ nas tak po prostu zostawiæ na tej scenie!}
{105}{}{Tak siê cieszê! Niesamowicie!}

{200}{}{Witaj przystojniaku. Zaintrygowa³eœ wszystkich swoj¹ obecnoœci¹. Jak siê masz?}
{1200}{}{Witaj. Zaintrygowa³aœ wszystkich swoj¹ obecnoœci¹. Czego potrzebujesz?}
{201}{}{Czeœæ.}
{202}{}{Kim jesteœ?}
{203}{}{Kim jestem? Jestem Beatrice Aguirre! Moje nazwisko widnia³o kiedyœ na wszystkich billboardach w Kalifornii. Ach, jaka szkoda, ¿e czasy siê zmieni³y.}
{204}{}{Co tu robisz?}
{205}{}{Ta laska w barze obieca³a mi drinka. To jedyna pociecha w moim cholernym ¿yciu.}
{206}{}{Przysy³a mnie Jose Solis. Próbuje przywróciæ do ¿ycia swój zespó³ mariachi.}
{207}{}{Wiêc stary zacz¹³ dzia³aæ? To ja rozumiem! OK, wchodzê w to. Zastanawiam siê, jak to wszystko siê skoñczy.}
{208}{}{Dam ci znaæ jak przyjdzie odpowiednia pora. Do widzenia.}
{209}{}{Chcê ciê zabraæ prosto na Stare Miasto. Mo¿esz ju¿ iœæ?}
{210}{}{ChodŸmy! Poznajmy nasze przeznaczenie!}
{211}{}{Tak, chodŸmy.}
{212}{}{Nie mogê siê doczekaæ, kiedy znów znajdê siê na scenie! Pomo¿esz mi dostaæ siê na Stare Miasto?}
{213}{}{Tak, chodŸmy.}
{214}{}{Nie teraz.}
{215}{}{Nie mogê siê doczekaæ, kiedy znów znajdê siê na scenie!}
{216}{}{Porozmawiamy o tym, Beatrice. Ale póŸniej.}
{217}{}{ChodŸ ze mn¹. Scena na Starym Mieœcie czeka na Ciebie.}
{218}{}{Poczekaj tu na mnie. Nied³ugo wrócê.}
{219}{}{Dziêkujê za pomoc. Zaœpiewam dla ciebie smutn¹ piosenkê.}
{220}{}{Powodzenia na scenie.}
