{100}{}{Widzisz Geoffreya.}
{101}{}{Widzisz ghula w starej pi¿amie. Spokojnie popija koktajl.}
{102}{}{Nie mogê zabroniæ ci tu byæ. Ale zabraniam ci siê na mnie patrzeæ.}
{103}{}{G³adkoskórzy to wielcy rasiœci. Czy siê mylê?}
{104}{}{Prawo? Nie s¹dzê, ¿e spodoba³oby ci siê tu w „rz¹dach prawa”.}

{200}{}{Hej, witaj, truposzu. Sk¹d jesteœ?}
{201}{}{Dziêki za drinka, kolego. Sk¹d jesteœ?}
{1201}{}{Dziêki za drinka, kole¿anko. Sk¹d jesteœ?}
{202}{}{Witaj, kolego. Sk¹d jesteœ?}
{1202}{}{Witaj, kole¿anko. Sk¹d jesteœ?}
{203}{}{Jestem z Arizony.}
{204}{}{Arizona! Nie s¹dzi³em, ¿e tam te¿ s¹ ghule. NajwyraŸniej nie byliœmy jedynymi dotkniêtymi t¹ plag¹ sto lat temu.}
{205}{}{My?}
{206}{}{Arizona! Nie s¹dzi³em, ¿e tam te¿ s¹ ludzie. Chocia¿ trochê dziwnie jest mówiæ o nas „ludzie”.}
{207}{}{Nas?}
{208}{}{Nekropolis. Przeczekaliœmy atak nuklearny w lokalnym schronie, ale w rezultacie zamieniliœmy siê w ghule. Farciarze umarli i poszli do nieba. To mój ulubiony ¿art.}
{209}{}{Dlaczego jesteœ tutaj, a nie w Nekropolis?}
{210}{}{Nie znasz tej historii, prawda? Och, to wydarzy³o siê kilka lat temu. Krótko mówi¹c, z powodu jednego pieprzonego mutanta, który stworzy³ inne mutanty, normalni ludzie chwycili za broñ przeciwko WSZYSTKIM mutantom. To zmusi³o nas do migracji... i to dalekiej. A teraz jesteœmy tutaj. Nie wysz³o tak Ÿle.}
{211}{}{Innymi s³owy, po prostu uciek³eœ od problemów?}
{212}{}{Myœl, co chcesz. To i tak nie ma znaczenia.}
{213}{}{To rozs¹dne. W ten sposób pokazujesz, ¿e nie chcesz walczyæ z normalnymi ludŸmi.}
{214}{}{Dziêki za mi³e s³owa, kolego.}
{1214}{}{Dziêki za mi³e s³owa, kole¿anko.}
{215}{}{Wygl¹da na to, ¿e podoba Ci siê tutaj?}
{216}{}{W Nekropolis kopaliœmy w³asne groby. A tu ¿yjemy normalnie. Ja na przyk³ad siedzê w barze i popijam White Russian -  mo¿e byæ coœ lepszego?}
{217}{}{[S³uchaj]}
{218}{}{Nawiasem mówi¹c, mieszka³em tu przed wojn¹. Mi³e wspomnienia. Od tego czasu minê³o jednak ca³e stulecie. Znów tu jestem, a z domu nie zosta³o nic. Najbardziej szkoda mi dywanu. Nadawa³ tonu ca³emu pomieszczeniu.}
{219}{}{Powinieneœ przejœæ na coœ s³abszego. Mo¿e o¿ywi to resztki twojego mózgu, które wydaj¹ siê byæ ca³kowicie zepsute.}
{220}{}{Nie wiem, co ci zrobi³em, g³adka twarzo. Musisz zmieniæ zdanie na temat tego miejsca.}
{221}{}{Mo¿e. Do widzenia.}
{222}{}{To takie smutne. Chyba nie zrozumiem, jak to jest ¿yæ w ruinach przez sto lat.}
{223}{}{Wiêc niewiele w ¿yciu stracisz. Mam nadziejê, ¿e ci siê tutaj spodoba.}
{1223}{}{Wiêc niewiele w ¿yciu stracisz. Mam nadziejê, ¿e ci siê tutaj spodoba.}
{224}{}{Mo¿e. Do widzenia.}
{225}{}{Nie wiem, co ci zrobi³em. Musisz zmieniæ zdanie na temat tego miejsca.}

{230}{}{Wiesz, ta ziemia nale¿a³a kiedyœ do Meksykanów. A potem przyszli Amerykanie i j¹ zabrali. Ale wojna zatar³a granice. Teraz ta ziemia nale¿y do mutantów bez rasy i narodowoœci.}
{231}{}{Nie mo¿na siê z tym k³óciæ.}

{250}{}{Napisz „Arizona” w kurzu na barze.}
{251}{}{Nek-kokol?}
{252}{}{[WyraŸ wstrêt do tchórzostwa ghuli]}
{253}{}{[Poka¿ przychylnoœæ]}
{254}{}{Dlaczego?}
{255}{}{[Przy³ó¿ palec do skroni]}
{256}{}{[Poklep po ramieniu]}
{257}{}{[WyjdŸ]}
{258}{}{Czeœæ!}
