{100}{}{Widzisz Czarnego Poszukiwacza.}
{101}{}{Widzisz mê¿czyznê ubranego w specjalny strój przeznaczony do przemierzania ruin.}
{102}{}{Konkurencja? Lepiej wybierz obszar, którego nie sprawdzam. Tylko ostrzegam.}
{103}{}{Ty! Kto nie jest z nami, jest przeciwko nam! Broñ siê!}
{104}{}{OK, OK, podekscytowaliœmy siê. Przepraszam.}
{105}{}{S³u¿ dobrze! To my tu jesteœmy prawdziw¹ si³¹!}

{200}{}{Ty! Kto nie jest z nami, jest przeciwko nam! Broñ siê!}
{201}{}{Tak! A teraz ty dostaniesz ode mnie!}
{202}{}{Przestañcie! Nie pozwolê wam wpaœæ w amok w barze z ghulami.}
{203}{}{Tak? A co zamierzasz zrobiæ, KUPO GOWNA?}
{204}{}{Wyci¹gnê pistolet i zastrzelê pierwszego, który wykona nag³y ruch.}
{205}{}{Pf-ha-ha-ha! Ghule! Wow! Bêdzie strzelaæ! U-ha-ha! Dobra, ch³opaki, uciekajmy st¹d. Ci klauni nie mog¹ siê z nami równaæ.}
{206}{}{Wynoœ siê st¹d.}
{207}{}{Poczekam, a¿ wyjdziesz.}
{208}{}{Co powiedzia³eœ, draniu? Wepchnê ci te s³owa z powrotem do gard³a razem z zêbami!}
{209}{}{[Wyrzuæ w powietrze garœæ kapsli. Niech je zbior¹ zamiast walczyæ.]}