{100}{}{Widzisz Fernando.}
{101}{}{Przed tob¹ stoi ghul w starym garniturze. Z jego twarzy zwisaj¹ siwe meksykañskie w¹sy.}
{102}{}{Witam. Roboty nie pozwalaj¹ wejœæ na stacjê. Chroni¹ j¹ jak w³asn¹ matkê.}
{103}{}{Witam. Co ja tutaj robiê? Jak widzisz, nic.}
{104}{}{Co siê dzieje? Dlaczego koncert zosta³ odwo³any?}
{105}{}{Hej, czeœæ, kolego!}
{1105}{}{Wyrazy szacunku, senorita!}

{110}{}{Jesteœmy za daleko. Stare Miasto jest po drugiej stronie.}
{111}{}{Czy to legendarna Stacja Duchów?}
{112}{}{Stacja o¿ywa, a wraz z ni¹ miasto. A to wszystko dziêki Tobie.}
{113}{}{Mam nadziejê, ¿e Bonita wkrótce wróci do zdrowia.}
{114}{}{Uwa¿aj! W okolicy czêsto mo¿na spotkaæ roboty Stra¿y Granicznej.}
{115}{}{Przed tob¹ bedzie urwisko prowadz¹ce do rzeki Otey.}
{116}{}{Jeœli masz zamiar iœæ przez most, to lepiej patrz uwa¿nie gdzie stawiasz kroki.}
{117}{}{Uwierzysz, ¿e w te miejsca w weekendy gromadzi³o siê mnóstwo ludzi? A teraz ani duszy.}
{118}{}{Trakt rzeczny Auteuy. Kiedyœ by³o tu piêknie.}
{119}{}{Ten du¿y budynek to szpital wojskowy. Dawno ju¿ spl¹drowany.}
{120}{}{}
{121}{}{Nie mam ochoty tam iœæ.}
{122}{}{Jesteœmy blisko epicentrum eksplozji. Nie powinieneœ tu zostawaæ.}
{123}{}{Dzielnica W³oska - przed wojn¹ s³ynê³a z kawiarni... a tak¿e bandytów i alfonsów.}
{124}{}{Idziemy przez park? Jest tu mniej promieniowania, ale za to wiêcej wszelkiego rodzaju ¿ywych stworzeñ.}

{200}{}{Do us³ug, senor.}
{1200}{}{Do us³ug, senorita.}
{201}{}{Czeœæ.}
{202}{}{Kim jesteœ?}
{203}{}{Nazywam siê Fernando.}
{204}{}{Co tu robisz?}
{205}{}{Jeszcze nic, jak widzisz.}
{206}{}{Przysy³a mnie Jose Solis. Próbuje przywróciæ do ¿ycia swój zespó³ mariachi.}
{207}{}{Dobry pomys³. Nie przeszkadza mi to. Kiedy wystêpujemy?}
{208}{}{Jeszcze nie wiem. Poczekaj chwilê.}
{209}{}{ChodŸmy natychmiast. Zabiorê ciê prosto na Stare Miasto.}
{210}{}{Bêdzie mi trudno przejœæ samotnie przez ruiny. Mam nadziejê, ¿e znasz drogê?}
{211}{}{Tak, chodŸmy.}
{212}{}{Nie mam nic przeciwko powrotowi na scenê, tak jak kiedyœ. Odprowadzisz mnie na Stare Miasto?}
{213}{}{Tak, chodŸmy.}
{214}{}{Nie, nie teraz.}
{215}{}{Tak?}
{216}{}{Nic. Nie zwracaj uwagi.}
{217}{}{ChodŸ ze mn¹. Scena na Starym Mieœcie czeka na Ciebie.}
{218}{}{Poczekaj tu na mnie. Nied³ugo wrócê.}
{219}{}{Dziêkujê za pomoc, kolego. Zagram marsz ¿a³obny na twoj¹ czeœæ.}
{1219}{}{Dziêkujê za pomoc, senorita. Zagram marsz ¿a³obny na twoj¹ czeœæ.}
{220}{}{Jasne. Cieszê siê.}