{100}{}{Widzisz Senora Gustavo.}
{101}{}{Widzisz Senora Gustavo, menad¿era San Ysidro.}
{102}{}{Tutaj to ja stanowiê prawo!}
{103}{}{Ghule potrzebuj¹ kontaktu radiowego? Pomó¿ im, a bêd¹ ciê szanowaæ.}
{104}{}{Spotkamy siê na molo.}

#Pierwsze spotkanie
{200}{}{Gustavo Obanel Vallejo do us³ug. Jestem menad¿erem San Isidro. A teraz do diab³a z uprzejmoœciami. Chcê znaæ powód, dla którego zak³ócasz nasze ¿ycie pozagrobowe.}
{1200}{}{Gustavo Obanel Vallejo do us³ug. Jestem menad¿erem San Isidro. A teraz do diab³a z uprzejmoœciami. Chcê znaæ powód, dla którego zak³ócasz nasze ¿ycie pozagrobowe.}
#Gustavo Aubanel Vallejo do Twojej dyspozycji. Jestem menad¿erem San Isidro. A teraz do diab³a z uprzejmoœciami. Chcê znaæ powód, dla którego zak³ócasz nasze ¿ycie pozagrobowe. Nie tolerujemy tutaj rasistow o g³adkiej skórze. Nasza rasa wystarczajaco wycierpiala przez ciebie. Dlatego wyjasnij jasno i bez klamstw – dlaczego mamy tolerowaæ Twoja obecnosc?
{201}{}{Przeklête ghule. Jestem tu, ¿eby zarobiæ na ¿ycie. Powiedziano mi, ¿e mo¿na tu nieŸle zarobiæ.}
{202}{}{Szczera odpowiedŸ. Z ludŸmi takimi jak Ty mo¿na negocjowaæ. Zaczynam ciê lubiæ.}
{203}{}{Wszystko zale¿y od warunków umowy, partnerze.}
{204}{}{W³aœciwie to szukam lepszego miejsca do ¿ycia. W tej chwili w mojej ojczyŸnie jest bardzo Ÿle.}
{205}{}{Uciekasz od k³opotów, tak? Jakoœ nie robi to na mnie wra¿enia, g³adki. Ale jeœli chcesz, mo¿esz siê przydaæ.}
{1205}{}{Uciekasz od k³opotów, tak? Jakoœ nie robi to na mnie wra¿enia, g³adka skóro. Ale jeœli chcesz, mo¿esz siê przydaæ.}
{206}{}{Ok. Co masz dla mnie?}
{207}{}{Nie jestem rasist¹. Kocham ghule i chcia³bym wœród nich ¿yæ.}
{1207}{}{Nie jestem rasist¹. Uwielbiam was, ghule i chcia³abym z wami mieszkaæ.}
{208}{}{Twoja skóra jest tak œliska, ¿e jakoœ ci nie wierzê. Nie bêdê tolerowaæ wiêcej k³amstw. Ale dam ci jedn¹ szansê. Jeœli to zrobisz, ghule beda ciê kochaæ do koñca swoich dni.}
{209}{}{Hej, próbujê tylko byæ przyjacielski!}
{1209}{}{Hej, próbujê tylko byæ przyjacielska!}
{210}{}{Gustavo Obanel Vallejo, do us³ug. Jestem menad¿erem San Isidro. Cieszê siê, ¿e ciê widzê w naszym obozie, bracie. Tutaj znajdziesz wieczny odpoczynek.}
{1210}{}{Gustavo Obanel Vallejo, do us³ug. Jestem menad¿erem San Isidro. Cieszê siê, ¿e ciê widzê w naszym obozie, siostro. Tutaj znajdziesz wieczny odpoczynek.}
{211}{}{Dziêkujê bracie. Co wiêc mam robiæ w tym piêknym mieœcie?}
{212}{}{Blask Dnia jeszcze nie zab³ysn¹³. Mo¿esz udaæ siê na stacjê i pomóc naszym pracownikom w przywróceniu pr¹du do miasta. Hojnie ciê za to wynagrodzê i pozwolê ci pozostaæ w San Ysidro do koñca twoich dni.}
{213}{}{Blask Dnia jeszcze nie zab³ysn¹³. Mo¿esz udaæ siê na stacjê i pomóc naszym pracownikom w przywróceniu pr¹du do miasta. Miasto bêdzie Ci wdziêczne a¿ do ostatnich dni.}
{214}{}{Zgadzam siê.}
{215}{}{To dla mnie za du¿o k³opotów.}
{216}{}{Za du¿o gadasz, cz³owieku. Wracaj na nuklearne pustkowia! Nie potrzebujemy ciê.}
{217}{}{Ups...}
{218}{}{Po incydencie na granicy przeprowadzimy z Tob¹ krótk¹ rozmowê. Czego potrzebujesz?}
{219}{}{Jakim incydencie? Ja nic nie wiem!}
{220}{}{Moi lojalni s³udzy strzegli wejœcia. A teraz wieje tam tylko wiatr. I nagle zjawiasz siê TY. Co powiesz na swoj¹ obronê?}
{221}{}{To tylko zbieg okolicznoœci. Wejœcie by³o otwarte, wiêc po prostu wszed³em.}
{1221}{}{To tylko zbieg okolicznoœci. Wejœcie by³o otwarte, wiêc po prostu wszed³am.}
{222}{}{Hmm, jeœli odkryjê, ¿e k³amiesz, osobiœcie zedrê z ciebie twoj¹ œlisk¹ skórê i posypiê twoje krwawi¹ce miêso radioaktywnym popio³em. Poczujesz ca³y ból, jakiego ghule doœwiadczaj¹ ka¿dego dnia swojego ¿ycia.}
{223}{}{Wierzê w ka¿de twoje s³owo. Ale kim ty jesteœ?}
{224}{}{Ten ghul mi grozi³. Po prostu siê broni³em.}
{1224}{}{Ten ghul mi grozi³. Po prostu siê broni³am.}
{225}{}{By³ lojalnym s³ug¹ Promieniowania. Broni³ naszego miasta przed normalnymi. Myœlisz, ¿e to ciê t³umaczy?}
{226}{}{Nie masz prawa stawiaæ granic. Pustkowie jest dla wszystkich, nie tylko dla ciebie.}
{227}{}{Chcemy po prostu ¿yæ jak normalni ludzie. Bez wojen. Bez wspania³ych misji ocalenia ludzkoœci. Byæ mo¿e tego nie rozumiesz. Ale skoro tu jesteœ, nie masz wielkiego wyboru – zrehabilituj siê lub... umrzyj.}
{228}{}{Wybieram œmieræ. Twoj¹ œmieræ!}
{229}{}{Próbujemy negocjowaæ? Swoj¹ drog¹, jeszcze siê nie przedstawiliœmy.}
{230}{}{Nie przypominam sobie, ¿eby ostrzegano mnie o twoim przybyciu. Jak uda³o ci siê przejœæ przez granicê?}
{231}{}{No có¿, po prostu przeszed³em przez bramê.}
{232}{}{I wierni s³udzy Blasku ciê nie powstrzymali? Wygl¹da na to, ¿e ktoœ dostanie po g³owie.}
{233}{}{Zdecydowanie nie ja. Wiêc... ty tu rz¹dzisz?}
{234}{}{Musisz pracowaæ, ¿eby móc tu mieszkaæ. Nawet mutant taki jak ty powinien to zrozumieæ. I bez ciebie mamy doœæ darmozjadów.}
{235}{}{Rozumiem...}
{236}{}{Masz pomys³ jak naprawiæ radio?}

#Powtarzany dialog
{250}{}{Mów, g³adkoskóry.}
{1250}{}{Mów, g³adkoskóra.}
{251}{}{Zegnaj, senior Gustavo.}
{252}{}{Co porabiasz, g³adkoskóry?}
{1252}{}{Co robisz, g³adka buzio?}
{253}{}{Patrzcie kogo tu mamy. G³adki pysk, a¿ prosi siê o porz¹dny oklep. Nie martw siê, zachowam twoj¹ skórê do przeszczepu. W miêdzyczasie powiesz mi wszystko co chcê wiedzieæ.}
{254}{}{Usi¹dŸ, amigo. Mam nadziejê, ¿e ghule z Blasku ciê zaakceptuj¹.}
{255}{}{Usi¹dŸ, amigo. Jak podoba Ci siê Blask Dnia? Wszystko w porz¹dku? Powiedz mi, jeœli jest jakiœ problem.}
{256}{}{Usi¹dŸ, amigo. Powiedz mi co ciê trapi. Mo¿e mogê ci pomóc.}
{257}{}{Usi¹dŸ. Myœlê, ¿e najwy¿szy czas porozmawiaæ.}

{260}{}{Przypomnij mi, czego ode mnie chcia³eœ?}
{261}{}{Czy ja mówiê po rosyjsku? (wzdycha ze zmêczenia) }
{262}{}{Elektrownia dzia³a.}
{263}{}{Blask znów œwieci! Energia elektryczna wróci³a do San Ysidro i Starego Miasta. Swietnie siê spisa³eœ, amigo. Pozwól, ¿e ciê przytulê i podziêkujê. Tu jest 1000 kapsli.}
{1263}{}{Blask znów œwieci! Energia elektryczna wróci³a do San Ysidro i Starego Miasta. Wykona³aœ œwietn¹ robotê. Pozwól, ¿e ciê przytulê i podziêkujê. Tu jest 1000 kapsli.}
{264}{}{Dziêkujê.}
{265}{}{NieŸle.}
{266}{}{Jestem ci te¿ winien przeprosiny. Da³em ci to zadanie w oczekiwaniu, ¿e zabij¹ ciê roboty lub promieniowanie. A w Blasku bêdzie jednego g³adkiego mniej. Ale by³em w b³êdzie. Mo¿esz pozostaæ w naszym mieœcie tak d³ugo, jak chcesz.}
{267}{}{Rozumiem i nie mam ci tego za z³e.}
{268}{}{Nie spodziewaj siê, ¿e po tym uœcisnê ci rêkê.}
{1268}{}{Nie spodziewaj siê, ¿e ciê po tym przytulê.}
{269}{}{Teraz, gdy mamy ju¿ pr¹d, musimy naprawiæ zepsute radio. Jest w pokoju obok. To zadanie w sam raz dla Ciebie.}
{270}{}{Nie jest zbyt zniszczone? Jesteœ pewien, ¿e da siê to naprawiæ?}
{271}{}{Naprawiæ? Nie. Potrzebuja wymiany. Wiem, ¿e centrum patrolowe dzia³a w podobny sposób. Zap³acê, jeœli przyniesiesz stamt¹d potrzebne czêœci.}
{272}{}{Dobrze. Postaram siê.}
{273}{}{Kiedy bêdê mieœ na to ochotê, spróbujê. Do tego czasu nie chcê tego robiæ. Do widzenia.}
{274}{}{Radio dzia³a. Dok³adniej, trzeba by³o wymieniæ kilka elementów na nowe z biura Stra¿y Granicznej.}
{275}{}{Kolejna wspania³a wiadomoœæ w tym spalonym œwiecie! Coraz bardziej ciê lubie, g³adka skóro. Jesteœ taki sam jak ja, kiedy by³em m³odszy.}
{1275}{}{Kolejna wspania³a wiadomoœæ w tym spalonym œwiecie! Coraz bardziej ciê lubie, g³adka skóro. Jesteœ taka sama jak ja, kiedy by³em m³odszy.}
{276}{}{Kolejna wspania³a wiadomoœæ w tym spalonym œwiecie!}
{277}{}{Wiesz, nie najprzyjemniejsze porównanie.}
{278}{}{Zadnych uœcisków, dobrze?}
{279}{}{Nie marnujmy czasu. Oto 500 kapsli za tê robotê. Teraz proszê ciê o zaniesienie tego holodysku burmistrzowi Butlerowi na Starym Mieœcie. To bardzo wa¿ne.}
{280}{}{I to wszystko? Po moich przesz³ych czynach bêdzie to bu³k¹ z mas³em.}
{281}{}{Przed nami ponure ruiny San Diego. Kryje siê w nich wiele niebezpieczeñstw. Uwa¿aj na siebie. I poproœ Edwarda o zapasy na drogê.}
{282}{}{OK, do zobaczenia póŸniej.}
{283}{}{Daj mi broñ, jeœli chcesz, ¿ebym prze¿y³ w drodze do Starego Miasta.}
{284}{}{Hmm, to ma sens. W jakiej broni jesteœ najbardziej bieg³y?}
{285}{}{[WeŸ }
{286}{}{]}
{287}{}{Proszê, nie umieraj po drodze.}
{1287}{}{Proszê, nie umieraj po drodze.}
{288}{}{Spróbujê...}
{289}{}{Spróbujê, bez obaw.}
{290}{}{Dlaczego to dla ciebie takie wa¿ne?}
{291}{}{Potrzebujemy tej stacji radiowej. Obszary promieniowania s¹ rozdarte przez nieprzeniknione ruiny, a promieniowanie zak³óca zwyk³e s³abe walkie-talkie. Sta³a komunikacja zmieni ca³e miasto. Zrób wszystko, co w Twojej mocy, dla nas wszystkich.}
{292}{}{Co jest na tej p³ycie?}
{293}{}{Po pierwsze, dane do transmisji radiowych, abyœmy mogli komunikowaæ siê na odleg³oœæ. A po drugie... Po drugie, kilka ostrze¿eñ dla mojego brata, ¿eby nie pope³nia³ du¿ych b³êdów.}


{296}{}{Jak dostaæ siê do elektrowni?}
{297}{}{S¹ dwa sposoby. Mo¿na jechaæ prosto autostrad¹ miêdzystanow¹ 805, a nastêpnie skrêciæ na wschód od znaku. Ale szlak jest patrolowany przez roboty wojskowe. Mniej niebezpieczna œcie¿ka wiedzie przez toksyczne bagna Chula Vista.}
{298}{}{OK, spróbujê to ogarn¹æ.}

#pytania
{300}{}{Czy mogê zadaæ kilka pytañ?}
{301}{}{Amigo, zawsze chêtnie Ciê wys³ucham i odpowiem na Twoje pytania. Ale teraz masz wa¿niejsze sprawy na g³owie. Wiesz co robiæ.}
{302}{}{Bêdzie lepiej, jeœli zajmiesz siê swoimi sprawami. Wiesz co mam na myœli.}
{303}{}{Zadnych rozmów. Nie jestem nawet pewien, czy warto z tob¹ rozmawiaæ.}
{304}{}{Rozumiem. Porozmawiamy kiedy indziej.}
{305}{}{Myœlê, ¿e po prostu nie chcesz mnie widzieæ. Do widzenia.}
{306}{}{Amigo, zawsze chêtnie Ciê wys³ucham i odpowiem na Twoje pytania. }
{307}{}{OK, do zobaczenia wkrótce.}

{310}{}{Chcê dowiedzieæ siê o tobie wiêcej.}
{311}{}{Kim jestem? Dziwne pytanie. Kiedyœ by³em lekarzem. Ale wojna uniewa¿ni³a moj¹ licencjê. Teraz, jak widaæ, prowadzê ma³e miasteczko. Wszystkiego mo¿na siê nauczyæ, jeœli ma siê czas.}
{312}{}{Przy okazji, o tym mieœcie. Nie rozumiem, gdzie w takim razie jest Blask Dnia? Co to jest?}
{313}{}{Jest w naszych sercach. Blask jest marzeniem upiorów. Marzeniem o mieœcie, w którym bezpiecznie do¿yjemy staroœci. A San Isidro jest jedn¹ z jego dzielnic. Chroni nas tutaj stary mur graniczny.}
{314}{}{Wiêc twoim celem jest zbudowanie Blasku?}
{315}{}{Miasto Ghuli jest moim celem. Chcemy po prostu ¿yæ jak normalni ludzie. Bez przeœladowania. Bez wojen. Zadnych wielkich misji ocalenia ludzkoœci.}
{316}{}{Rozumiem.}
{317}{}{Stare Miasto te¿ siêga po ten raj?}
{318}{}{Wygl¹da na to, ¿e Stare Miasto podziela Twoje marzenie.}
{319}{}{Stare Miasto pope³nia b³¹d. Jest zbyt blisko szlaku karawan, aby pozbyæ siê zepsutego wp³ywu normalniaków z pó³nocnych miast.}
{320}{}{Jak dostanê siê na Stare Miasto?}
{321}{}{IdŸ na pó³noc. Mo¿na przejœæ prosto przez mola, do najbardziej radioaktywnego piek³a. Mo¿na te¿ pospacerowaæ po ruinach przedmieœcia, zapewniaj¹c sobie nowe i nie zawsze mile widziane spotkania.}
{322}{}{Rozumiem.}
{323}{}{Co to jest Blask Dnia? Gdzie to siê znajduje?}
{324}{}{Jakie miasto próbujesz zbudowaæ?}
{325}{}{To bêdzie takie samo miasto, jakie by³o sto lat temu. Zbieramy wszystko, co pozosta³o ze Starego Swiata. Nikt siê tu nami nie interesuje, wiêc mo¿emy odpocz¹æ i ¿yæ w spokoju.}
{326}{}{Opowiedz mi o sobie.}

{350}{}{Da³em holodysk Butlerowi. Twoja wiadomoœæ go nie przekona³a.}
{1350}{}{Da³am holodysk Butlerowi. Twoja wiadomoœæ go nie przekona³a.}
{351}{}{Nic dziwnego. John i ja k³ócimy siê o Blask Dnia. O to, jak powinno wygl¹daæ miasto upiorów. Przywi¹zuje zbyt du¿¹ wagê do normalnych ludzi i zupe³nie zapomnia³, ¿e jesteœmy ludŸmi Starego Swiata. Mo¿emy o¿ywiæ miasto, zbudowaæ je na nowo! Tak, ghule s¹ s³abe, ale mamy pozosta³oœci starych maszyn i energii. Za pomoc¹ technologii mo¿emy stworzyæ sobie wszystkie niezbêdne warunki do ¿ycia nawet poœród spalonych ruin.}
{352}{}{Nawiasem mówi¹c, po przeczytaniu holodysku poprosi³ mnie o pomoc w zdobyciu chipów z fabryki samolotów.}
{353}{}{Co za ba³agan! Ta fabryka nadal mo¿e przys³u¿yæ siê nam, ghulom. Nie oddawaj chipów Staremu Miastu, oddaj je mnie. Nasz technik wykorzysta to do naprawy robotów i przy ich pomocy odbudujemy miasto. Da nam to w przysz³oœci wiêcej korzyœci ni¿ g³upi handel z karawanami.}
{354}{}{Zastanowiê siê nad tym.}
{355}{}{Dobrze. Bywaj.}
{356}{}{Wiedzia³em, ¿e to powiesz, wiêc zabra³em te chipy ze sob¹. S¹ tutaj.}
{1356}{}{Wiedzia³am, ¿e to powiesz, wiêc zabra³em te chipy ze sob¹. S¹ tutaj.}
{357}{}{Dziêkujê. Oto 1000 kapsli za tê robotê. Fabryka bardzo nam pomo¿e, nie mo¿emy jej oddaæ. Myœlê, ¿e powinieneœ osobiœcie powiedzieæ Johnowi, ¿e Fabryka jest pod moj¹ kontrol¹ i ¿e nie dam mu chipów.}
{358}{}{OK.}
{359}{}{Oto chipy, które Butler chcia³ sprzedaæ. Ale nie sprzeda.}
{360}{}{W takim razie mam dla ciebie z³¹ wiadomoœæ – Butler wzi¹³ ju¿ chipy i przygotowuje siê do ich sprzeda¿y.}
{361}{}{To naprawde z³a wiadomoœæ. Myœlê, ¿e powinieneœ mieæ oko na Butlera. Daj mi znaæ, jeœli dowiesz siê, co dok³adnie planuje.}
{362}{}{Dobrze.}
{363}{}{Mam dla ciebie z³¹ wiadomoœæ - Butler wzi¹³ ju¿ chipy i przygotowuje siê do ich sprzeda¿y.}
{364}{}{Tak i jeszcze jedno. Daj mi znaæ, co planuje Butler, jeœli siê dowiesz.}
{365}{}{Dobrze.}

{370}{}{Butler zamierza otworzyæ bazê wojskow¹ na wyspie przy pomocy kodów dos...}
{371}{}{Pope³nia b³¹d! Wiêkszoœæ znalezisk sprzeda ludziom! A to spowoduje du¿¹ redystrybucje osiedli ludzkich. Gdy tylko wojna z supermutantami dobiegnie koñca, walki o stare technologie rozpoczn¹ siê na nowo. Normalni nie wiedz¹, jak postêpowaæ z dziedzictwem Starego Swiata. Poza tym mog¹ to wykorzystaæ przeciwko nam. Technologia powinna pozostaæ z upiorami! Potrzebujemy jej bardziej. I wiemy lepiej, jak z niej korzystaæ.}
{372}{}{Co zamierzasz zrobiæ?}
{373}{}{Butler nie ust¹pi. Powinniœmy wyl¹dowaæ tam pierwsi i zabraæ wszystko dla siebie. Wyœlê zespó³ na molo, ¿eby w³aœciwie zareagowali. Skorzystaj z radia, a potem ty te¿ idŸ na molo.}
{374}{}{OK.}