{100}{}{Widzisz Johna D. Butlera.}
{101}{}{Widzisz ghula w znoszonym garniturze.}
{102}{}{Idziesz do bazy wojskowej? Szeregowy Kucha te¿ tego chce!}

#Znajomy
{200}{}{Witam. Wygl¹da na to, ¿e nigdy wczeœniej siê nie spotkaliœmy. Jestem John Butler, wybrany burmistrz Blasku. Kim jesteœ?}
{201}{}{Mi³o ciê poznaæ, Butler. Jestem }
{202}{}{, ofiara przypadkowej mutacji na pustkowiach.}
{203}{}{Nie podlizuj mi siê, mutancie.}
{204}{}{(wzdycha) Nigdy nie myœla³em, ¿e jeden mutant oskar¿y innego mutanta o bycie mutantem.}
{205}{}{To siê nie zdarza na pustkowiach.}
{206}{}{*Cisza* Jestem John Butler. Rz¹dzê tym miastem... A raczej tym, co z niego zosta³o. I cieszê siê, ¿e w moim mieœcie widzê g³adkoskórych, którzy zachowuj¹ siê przyzwoicie. *Strzela palcami*}
{207}{}{Nigdy nie przysz³oby mi do g³owy, ¿e to ja jestem tutaj chuliganem.}
{208}{}{Ludzie i supermutanci wypêdzili nas z naszych domów. Prawdopodobnie znasz ju¿ tê historiê. Ale to nie powód, aby nienawidziæ wszystkich wokó³. Wrêcz przeciwnie, chcê udowodniæ ludziom, ¿e ghule to te¿ ludzie... *Strzela dalej*}
{209}{}{Próbujesz mnie oszukaæ? Myœla³em, ¿e ghule nienawidz¹ normalnych ludzi.}
{210}{}{Przeprowadziliœmy siê tutaj, poniewa¿ ludzie i supermutanci wypêdzili nas z naszych domów. Ale to nie powód, aby nienawidziæ wszystkich wokó³. Wrêcz przeciwnie, chcê udowodniæ ludziom, ¿e ghule to te¿ ludzie... *Strzela dalej*}
{211}{}{Gry s³owne nie s¹ twoj¹ mocn¹ stron¹, John.}
{212}{}{Zgadza siê. Ten wojownik ma problemy z poczuciem humoru. Starych nawyków nie da siê zmieniæ nawet po stu latach. Wiêc jak mogê Ci pomóc?}
{213}{}{W tej chwili prawdopodobnie niczego nie potrzebujê.}
{214}{}{To bardzo szlachetne z twojej strony.}
{215}{}{Mniejsza z nami, starymi. Prze¿yliœmy wiele wojen i bitew, nasz los to przesz³oœæ. Wa¿niejsze jest to, co stanie siê z twoim pokoleniem... Uch, wiêc jak mogê ci pomóc?}
{216}{}{Chcia³em ciê tylko poznaæ. Ale ju¿ czas, ¿ebym odszed³.}
{1216}{}{Chcia³am ciê tylko poznaæ. Ale ju¿ czas, ¿ebym odesz³a.}

{220}{}{To nasz stary kumpel, Kucha. Ktoœ z nim jest? Zabójcza wiadomoœæ! Jak w¹¿ i królik, zaprzyjaŸnili siê. Cieszê siê z Twojego szczêœcia.}
{1220}{}{To nasz stary kumpel, Kucha. Ktoœ z nim jest? Zabójcza wiadomoœæ! Jak w¹¿ i królik, zaprzyjaŸnili siê. Cieszê siê z Twojego szczêœcia. Szkoda, ¿e nie mamy koœcio³a, w którym moglibyœmy przeprowadziæ œlub.}
{221}{}{Kucha jest moim ochroniarzem.}
{222}{}{Jestem dowódc¹ steru. Bez mojego rozkazu nie mo¿na tu nawet sikaæ.}

#Powtarzany dialog
{230}{}{OK. Jak mogê ci pomóc?}
{231}{}{Witaj g³adkoskóry. Masz jakieœ pytanie?}
{1231}{}{Witaj g³adkoskóra. Masz jakieœ pytanie?}
{232}{}{Witam, m³oda ofiaro mutacji. Jak mogê ci pomóc?}
{233}{}{Czeœæ, John. Tylko przechodzê obok. Do widzenia.}
{234}{}{Szkoda, ¿e niewiele rozmawialiœmy. Jeœli coœ bêdzie potrzebne, zawsze tu jestem... *Do mnie!*}
{235}{}{Czeœæ.}
{236}{}{Czego chcesz?}
{237}{}{Czas na ¿arty siê skoñczy³. Czas zabraæ siê do pracy.}

{240}{}{Powiedz mi, jak tu wszyscy trafiliœcie?}
{241}{}{Mieszkaliœmy na pó³nocy, w miasteczku zwanym Nekropolis. Ale przybyli supermutanci. A po nich ludzie. Walczyli miêdzy sob¹, a o nas zapomnieli... *Cel! Pal!* Kiedy opad³ kurz, normalni zdecydowali, ¿e od teraz ghuli te¿ nie lubi¹. Postanowiliœmy znaleŸæ sobie nowy dom.}
{242}{}{Jakie miasto próbujesz zbudowaæ?}
{243}{}{Po prostu normalne, funkcjonuj¹ce miasto. Z handlem i gospodark¹, hotelami i kasynami, drogami i drapaczami chmur. I tak, aby by³o wystarczaj¹co du¿o miejsca dla wszystkich - ghuli, ludzi i mutantów. *Spokojnie, ¿o³nierze!*}
{244}{}{Dziêkujê za odpowiedŸ. Musze iœæ.}
{245}{}{Mogê ci pomóc?}
{246}{}{Naprawdê chcesz mi pomóc? Gdyby nie te stare oczy, chyba bym siê rozp³aka³. Popytaj w okolicy, na pewno ktoœ bêdzie potrzebowa³ pomocy.}
{247}{}{Tak zrobiê. Do widzenia.}
{248}{}{Czy mogê ci w czymœ jeszcze pomóc?}
{249}{}{Opowiedz mi o sobie.}
{250}{}{Ju¿ mówi³em. Nazywam siê John Butler. Jestem burmistrzem Blasku... có¿, przysz³ego Blasku.}
{251}{}{Czy San Ysidro nale¿y do ciebie?}
{252}{}{To jedna z dzielnic przysz³ego Blasku. W ruinach znajduje siê kilka obozów ghuli. Najwiêksze z nich to Stare Miasto i San Isidro. Ka¿de z nich jest zarz¹dzane przez w³asnego administratora. *Bo¿e b³ogos³aw Amerykê!*}

#Zadania fabularne
{259}{}{Szybko! Dobrze, ¿e stacja radiowa dzia³a. W³aœnie skontaktowa³a siê z nami karawana. Ch³opaki wpadli w zasadzkê na pi¹tej autostradzie. Ghule s¹ zbyt powolne i s³abe. Ca³a nadzieja w Tobie. No dalej, pomó¿ swoim braciom w trudnych chwilach. *Naprzód-marsz!*}
{260}{}{Ju¿ biegnê!}
{261}{}{Jak zwykle wszystko ja. OK, zrobiê to.}
{262}{}{Karawana jest na skrzy¿owaniu dróg. IdŸ prosto na pó³noc g³ówn¹ autostrad¹.}
{263}{}{Karawaniarze - czy oni ¿yj¹?}
{264}{}{Nie mia³em jeszcze okazji ich zobaczyæ. Wrócê, kiedy siê dowiem.}
{265}{}{Pan Rutger mówi³ o twoim wyczynie. My, ghule, mo¿emy jedynie zyskaæ na uratowaniu karawany. Potrzebujemy rzeczy z pó³nocy, a "Truckers" to najbardziej niezawodna firma oferuj¹ca karawany. Wiêc dziêkujê }
{266}{}{.}
{267}{}{, g³adkoskóry.}
{268}{}{Nie ma problemu.}
{269}{}{Widzê po twoich oczach, ¿e twoja misja siê nie powiod³a. Có¿, Rutger by³ najlepszym dostawc¹. Bez niego i jego firmy handel z ludŸmi bêdzie trudniejszy. Gustavo na pewno bêdzie z tego powodu zadowolony, jeœli to us³yszy. Nie chce dzieliæ siê z g³adkimi znaleziskami Starego Swiata.}
{270}{}{Na to w³aœnie liczy³em.}
{271}{}{Przykro mi, ¿e tak siê sta³o. Da³em z siebie wszystko.}
{1271}{}{Przykro mi, ¿e tak siê sta³o. Da³am z siebie wszystko.}
{272}{}{Teraz mam coœ do sprawdzenia i przemyœlenia. Na razie mo¿esz odpocz¹æ.}
{273}{}{OK.}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
{279}{}{}

#Zadania fabularne
{300}{}{Gustavo poprosi³ mnie, ¿ebym da³ ci tê p³ytê.}
{301}{}{ChodŸ tutaj. Zobaczymy, co ten truposz wbi³ sobie do g³owy... Hmm. Tak, to pora¿aj¹ca wiadomoœæ! Blask ma teraz zasilanie i ³¹cznoœæ radiow¹. Zupe³nie jak za starych, dobrych czasów. Czy mog³o by byæ lepiej? *Wszyscy naprzód! Wszyscy na wojne!*}
{302}{}{[Dalej]}
{303}{}{O tak, Gustavo znowu chce zerwaæ kontakty z G³adkoskórymi. Ten staruszek nic nie rozumie. *Cel! Pal!* Widzisz, Gustavo chce chroniæ miasto przed obcymi. Ja myœlê, ¿e to g³upie. Potrzebujemy rzeczy i jedzenia z Hub. A Hub potrzebuje lœni¹cej technologii. Powiedz mi, nie podzielasz jego zdania, prawda?}
{304}{}{Raczej nie.}
{305}{}{Nie obchodzi mnie, który z was zap³aci mi za pracê.}
{306}{}{Swietnie. W takim razie mam dla Ciebie kilka ma³ych i ³atwych zadañ.}
{307}{}{S³ucham.}
{308}{}{A co jeœli podzielam?}
{309}{}{To by³oby przykre. I bardzo g³upie.}
{310}{}{Nie jestem przekonany. Wracam do San Ysidro.}
{311}{}{OK. Przekona³eœ mnie. Co mam zrobiæ?}
{312}{}{To by³oby przykre. I bardzo g³upie. Powiedz mi, nie obchodzi Ciê, kto p³aci za pracê, prawda? Ja te¿ potrzebujê twoich us³ug.}
{313}{}{Co trzeba zrobiæ?}

{320}{}{Poszukiwacze obecnie rozbieraj¹ star¹ fabrykê samolotów. Nie przeszkadza mi, ¿e to robi¹. Ale dzia³aj¹ bez Pieczêci Seta i zmuszaj¹ tak¿e inne ghule do pracy. A co najwa¿niejsze, elektronika z tej fabryki jest nam potrzebna dla najbli¿szej karawany. *Atak!* IdŸ do fabryki. Powiedz Poszukiwaczom, ¿e dam im Pieczêæ Seta, jeœli oddadz¹ chipy z fabryki. I nie mów ani s³owa Gustavo!}
{321}{}{Co to jest Pieczêæ Seta?}
{322}{}{Jest to swego rodzaju prawo kopalniane w San Diego i okolicach. Oczywiœcie w zamian za udzia³ w zyskach. Rodzaj podatku. *Nie poddawaj siê!* Jeœli Poszukiwacze zabior¹ wszystko dla siebie, dla naszego miasta nie pozostanie nic.}
{323}{}{Rozumiem. Spróbujê z nimi porozmawiaæ.}
{324}{}{Musimy porozmawiaæ o sytuacji z Poszukiwaczami w fabrycê.}
{325}{}{I jak, czy plan wydobycia jest ju¿ ukoñczony?}
{326}{}{Nie, niestety.}
{327}{}{Chcê tylko jeszcze raz zapytaæ, czym jest Pieczêæ Seta?}
{328}{}{Ach, teraz rozumiem.}
{329}{}{Tak siê sk³ada, ¿e wszyscy Poszukiwacze w zginêli.}
{330}{}{Wszyscy nie ¿yj¹? Swiêci œwiêci! A co z chipami? Uda³o Ci siê je zabraæ?}
{331}{}{Nie ma za co.}
{332}{}{Czy dostanê coœ za próbê?}
{333}{}{Mam wszystkie chipy, s¹ tutaj.}
{334}{}{Dobra robota. *Nie braæ jeñców!*}
{335}{}{Oto twoja nagroda. Ale nie œpiesz siê w wizyt¹ w barze. Mamy tu problem.}
{336}{}{Dziêkujê. Co siê sta³o?}
{337}{}{Nie. A to konieczne?}
{338}{}{Oni byli g³ównym ogniwem pracuj¹cym! Poniewa¿ Poszukiwacze zawiedli, ca³a nadzieja w tobie. Przynieœ te cholerne chipsy.}
{339}{}{OK.}
{340}{}{Tak. S¹ tutaj.}
{341}{}{Tylko czêœæ.}
{342}{}{To one s¹ najwa¿niejsze! Poniewa¿ Poszukiwacze zawiedli, ca³a nadzieja w tobie. Zbierz pozosta³e chipy.}
{343}{}{Zak³ad jest teraz pod kontrol¹ Gustavo. Nie zobaczysz chipów.}
{344}{}{Co, Gustavo mnie wyprzedzi³? To zabójcza wiadomoœæ! Ale teraz pojawi³ siê wiêkszy problem. Musimy od³o¿yæ to na bok.}
{345}{}{Co siê sta³o?}
{346}{}{Gdzie jest fabryka samolotów?}
{347}{}{IdŸ na Trasê 805. ZnajdŸ tam Szpital Paradise Valley. Fabryka bêdzie na wschodzie.}
{348}{}{Rozumiem.}
{349}{}{}

{350}{}{Wiêc przemyœla³em to i podj¹³em decyzjê! Widzisz, pan Rutger mia³ cenny kontrakt z Hub na wymianê technologii z bazy wojskowej Coronado. To OGROMNY zysk dla miasta. Mo¿emy o¿ywiæ ruiny. Marzenie o Blasku Dnia siê spe³ni! *Viva, Ameryka!*}
{351}{}{Z bazy wojskowej? Powa¿nie?}
{352}{}{Nie mo¿emy tam teraz wejœæ ze wzglêdu na stare zabawki wojskowe. Oto kody dostêpu. Trzeba je przes³aæ ³¹czem radiowym, tym które jest w San Ysidro. Nie mamy ¿adnego innego tak potê¿nego Ÿród³a sygna³u. Gdy to zrobisz, podejdŸ na molo, tam bêdzie czekaæ eskorta. I nie mów o tym Gustavo!}
{353}{}{[OdejdŸ]}
