{100}{}{Widzisz Edwarda.}
{101}{}{Widzisz w³aœciciela lokalnego lokalu gastronomicznego. Ma na sobie niegdyœ bia³y fartuch i czapkê.}
{102}{}{Nie jestem zainteresowany.}

{200}{}{Czeœæ... O rany!}
{201}{}{Dok³adnie. Czy to nie jest normalne?}
{202}{}{Uh, wyglada na to, ¿e tu nie pasujê. Do widzenia...}
{203}{}{Nie zrozum mnie Ÿle, ale... Nie wiesz, ¿e to jest miasto umar³ych? Podnosimy nawet ceny dla normalnych, ¿eby tu nie zostawali.}
{204}{}{Wiem. Nie martw siê, nie bêdê przeszkadzaæ.}
{205}{}{Po prostu przynieœ mi drinka, ty pieprzony rasisto.}
{206}{}{Jak mówisz.}
{207}{}{Sprytnie. Jak masz na imiê?}
{208}{}{Edward, proszê pana.}
{1208}{}{Edward, proszê pani.}
{209}{}{OK, Edwardzie. Poka¿ mi, co masz na lunch.}
{210}{}{Oto menu, a oto dania na wynos.}
{211}{}{Dziêkujê.}
{212}{}{Czego chcesz, przyjacielu?}
{1212}{}{Czego chcesz, przyjació³ko?}
{213}{}{Czego chcesz, g³adka buzio?}
{214}{}{Prawdopodobnie nie chcê niczego.}
{215}{}{Poka¿ mi menu.}
{216}{}{WejdŸ, nie wstydŸ siê. Wszyscy tutaj s¹ swoi! Nie tolerujemy tu ¿adnych normalnych i mamy dla nich podwójne ceny. Ale dla mutantów drzwi s¹ zawsze otwarte.}
{217}{}{Dziêkujê za ciep³e powitanie. Jestem }
{218}{}{. Jak masz na imiê?}
{219}{}{Jeszcze nie zdecydowa³em siê na zostanie w tym klubie. Kim jesteœ?}
{1219}{}{Jeszcze nie zdecydowa³am siê na zostanie w tym klubie. Kim jesteœ?}

{220}{}{Porozmawiamy, Ed?}
{221}{}{Jak, co?}
{222}{}{Doœæ gadania. Muszê iœæ w interesach.}
{223}{}{Czy to menu przedwojenne?}
{224}{}{Do rzeczy. To, co przybywa z karawanami z pó³nocy, przewa¿nie zostaje na Starym Mieœcie. My dostajemy tylko okruszki. Dlatego czêsto gotujê z produktów przedwojennych. Ale my, ghule, kochamy to jeszcze bardziej. Ach, nostalgia! Do pe³nej gamy smaków brakuje tylko jednego elementu – starej, dobrej kawy. Czy mo¿e istnieæ kawiarnia bez kawy?}
{225}{}{To cholernie niesprawiedliwe, Ed. Mogê poszukaæ dla ciebie kawy w ruinach.}
{226}{}{Mam doœæ twojego marudzenia. Jestem tu po przekaskê, a nie po nostalgiczne wspominki.}
{227}{}{Serio zaryzykujesz dla puszki kawy? Zap³acê potrójn¹ cenê za ka¿d¹ puszkê!}
{228}{}{Zgadza siê. Przyniosê ci kawê, jeœli j¹ znajdê.}
{229}{}{Z drugiej strony wycieczka w ruinach nie by³a moim planem. Ale zrobiê notatkê w Pip-Boyu.}
{230}{}{Masz wielkie szczêœcie. Mam akurat jeden pe³ny s³oik.}
{231}{}{Mam puszkê kawy do twojej kawiarni.}
{232}{}{(otwiera, w¹cha, smakuje) Có¿ za bogaty smak! Ca³kiem nieŸle radzê sobie z tym menu. Oto Twoja zap³ata - }
{233}{}{ kapsli. Przynieœ wiêcej, jeœli znajdziesz.}
{234}{}{Koniecznie.}
{235}{}{G³adki, Ÿle trafi³eœ. Nie obs³ugujemy tutaj takich ludzi jak ty.}
{1235}{}{G³adka, Ÿle trafi³aœ. Nie obs³ugujemy tutaj takich ludzi jak ty.}
{236}{}{Tylko coæ zamówiê i wychodzê.}
{237}{}{No có¿, przepraszam... Mo¿emy to zakoñczyæ? Zap³acê potrójn¹ cenê za ka¿d¹ butelkê.}

{240}{}{Dziêki za pr¹d, }
{241}{}{! To musia³o byæ bardzo niebezpieczne zadanie, prawda? Proszê, weŸ leki na chorobê popromienn¹. Myœlê, ¿e to najlepszy sposób, w jaki mogê ci podziêkowaæ.}
{242}{}{Dziêki, Ed. Na pewno bêdê tego potrzebowaæ.}
{243}{}{Razem? OK, chodŸmy, ale o to w³aœnie chodzi.}
{244}{}{O tak, nadal mo¿esz dostaæ zni¿kê. Normalnie ludzie p³ac¹ tu wiêcej.}
{245}{}{Chcia³em tylko coœ zamówiæ. Poka¿ mi menu.}
{246}{}{To œwietnie. Ale teraz bardziej ni¿ jedzenia potrzebujê informacji.}
{247}{}{Dziêki za pr¹d,}
{248}{}{! To musia³o byæ bardzo niebezpieczne zadanie, prawda? Masz, napij siê i zjedz lunch na mój koszt. Nastêpnym razem dam ci zni¿kê.}
{249}{}{}
{250}{}{Senor Gustavo powiedzia³, ¿e masz coœ dla mnie.}
{251}{}{Dam ci Antyrad, RadX, Antidotum i Stimpacka. Ale darmowy ser jest tylko w pu³apce na myszy. Za przekroczenie ruin San Diego trzeba nieraz s³ono zap³aciæ. Mam nadziejê, ¿e dasz radê. Powodzenia przyjacielu.}
{1251}{}{Dam ci Antyrad, RadX, Antidotum i Stimpacka. Ale darmowy ser jest tylko w pu³apce na myszy. Za przekroczenie ruin San Diego trzeba nieraz s³ono zap³aciæ. Mam nadziejê, ¿e dasz radê. Powodzenia, przyjació³ko.}
{252}{}{Potrzebujê wiêcej. Poka¿ mi, co masz na sprzeda¿?}
{253}{}{Dziêki, Ed. Do zobaczenia.}

{260}{}{Muszê wymieniæ trochê starych pieniêdzy na kapsle.}
{261}{}{Wymieniê te pieni¹dze na }
{262}{}{ kapsli. Umowa stoi?}
{263}{}{Za ma³o. Przepraszam, ¿e przeszkadzam.}
{264}{}{Nie rób tego. Lepiej daj mi coœ do jedzenia.}
{265}{}{[Wymieñ 1 dolar]}
{266}{}{[Wymieñ 2 dolary]}
{267}{}{[Wymieñ 3 dolary]}
{268}{}{[Wymieñ 4 dolary]}
{269}{}{[Wymieñ 5 dolarów]}
{270}{}{[Wymieñ 10 dolarów]}
{271}{}{[Wymieñ WSZYSTKIE dostêpne dolary]}
{272}{}{Co to jest, dziura w kieszeni? Dzieje siê.}
{273}{}{Tak, to jest...}
{274}{}{Proszê.}
{275}{}{Dziêkujê.}
{276}{}{[Wymieñ pieni¹dze na kapsle.]}
{277}{}{[Odmów i wyjdŸ.]}

{280}{}{Masz dla mnie jak¹œ pracê?}
{281}{}{Nie mogê ci zaoferowaæ niczego powa¿nego. Ale mo¿esz zanieœæ jedzenie pracownikom przy tamie.}
{282}{}{Niewa¿ne. Nie chcê robiæ czegoœ takiego.}
{283}{}{Dobrze. Daj mi paczkê.}
{284}{}{Masz tutaj piêæ pude³ek z obiadem dla piêciu osób. Daj ka¿demu z nich. I trzeba to zrobiæ w jeden dzieñ. Na pewno zrobisz to szybciej ni¿ inne ghule. Tak, i uwa¿aj, ¿eby nie zjeœæ niczego po drodze. W przeciwnym razie ghule przy tamie bêd¹ BARDZO nieweso³e.}
{285}{}{OK.}
{286}{}{Wszyscy klienci przy tamie otrzymali swoje zamówienia.}
{287}{}{Dziêkujê bardzo. Oto twoja zap³ata.}
{288}{}{Czeœæ.}
{289}{}{Dziêkujê bardzo. Oto twoja zap³ata. Aha, a tak przy okazji, mam tu resztki jedzenia. Masz, zabierz je ze sob¹.}
{290}{}{Dziêkujê.}
{291}{}{Tak, czym jeszcze mo¿esz mnie wynagrodziæ, jeœli nie takimi przedmiotami? Czeœæ.}

{292}{}{Czy wiesz, kto jest w³aœcicielem filmu „G³êbokie gard³o”?}
{293}{}{Wiem. To Raymond. Ale nigdy nie rozstanie siê ze swoim ulubionym filmem. Chocia¿ wydaje mi siê, ¿e ceni sobie samo pude³ko z p³yt¹, a samego filmu nawet nie widzia³. Ostrzegam – nie zabieraj mu p³yty, oszaleje ze wœciek³oœci i bêdzie ka¿demu zawraca³ g³owê.}
{294}{}{Dziêkujê za ostrze¿enie.}

{295}{}{Hej, Ed, wiesz, widzia³em w ruinach robota kuchennego z twoim imieniem na papierze firmowym.}
{296}{}{W koñcu! Mia³ mi to za³atwiæ robot-pos³aniec, ale coœ mu siê sta³o. Wiadomo, ten procesor jest bezcenny! Umieramy tutaj bez odpowiedniego jedzenia. Procesor by³by dobrym rozwi¹zaniem tego problemu. Wiêc mówisz, ¿e to masz?}
{297}{}{Nie, uh, zostawi³em to tam, gdzie znalaz³em. Przepraszam.}
{298}{}{Przepraszam. Szkoda. Potrzebujemy tego procesora! Proszê, przynieœ to. Dam ci 200 kapsli.}
{299}{}{No có¿, jeœli bêdê w poblizu.}
{300}{}{Dobrze.}
{301}{}{Tak, jest tutaj, trzymaj.}
{302}{}{Och, ratujesz nas! Hej, ch³opaki, spójrzcie, ten g³adkoskóry typ wykona³ dla nas œwietn¹ robotê. Podziêkujcie mu!}
{303}{}{Cieszê siê, ¿e mogê pomóc.}
{304}{}{Cholera, DeSanti dalby mi wiêcej... Och, to coœ innego, niewa¿ne. Ech, czeœæ.}