{100}{}{Widzisz barmana.}
{101}{}{Widzisz zwyczajnego barmana... mo¿na by tak powiedzieæ, gdyby nie by³ ghulem.}
{102}{}{Znowu te pijackie bójki! Zatrzymajcie ich! Zniszcz¹ mój bar!}

{210}{}{Czego chcesz, worku koœci?}
{211}{}{Niczego. Do widzenia.}
{212}{}{Chcê piæ i jeœæ. Co masz?}

{220}{}{Czy Steve Morgan tu jest?}
{221}{}{W³aœnie wyszed³. Po co ci ten chodz¹cy trup?}
{222}{}{Mam z nim „sprawê”. Chodzi o kuriera.}
{223}{}{Nie najlepszy wybór. Od wojny drêczy go ¿¹dza zysku, a nie staæ go nawet na nowy samochód. Hehe, ¿artujê. W ka¿dym razie powiedzia³, ¿e wraca do Hub. Dopiero rozmawialiœmy, siedzia³ na tym samym krzeœle co ty.}
{224}{}{Kiedy wróci? Ju¿ jest w drodze? Postaram siê go dogoniæ na szlaku...}
{225}{}{Powinienem by³ mi to powiedzieæ odrazu, idioto!}
{226}{}{Co tu robi¹ Czarni Poszukiwacze?}
{227}{}{Mój bar jest otwarty dla ka¿dego, kto p³aci. Butler te¿ nie ma nic przeciwko ludziom w mieœcie. Próbuje nawi¹zaæ handel z Hub. Dopóki Poszukiwacze nie sprawiaj¹ problemów, tolerujemy ich.}
{228}{}{Rozumiem.}

{230}{}{Masz coœ mocniejszego od starego piwa?}
{231}{}{Dobry trunek sta³ siê rzadkoœci¹. To, co zostaje znalezione w ruinach, jest zwykle sprzedawane karawanom z pó³nocy, a w barze zostaje ca³y alkohol.}
{232}{}{Przepraszam. Mia³em nadziejê na dobrego drinka...}
{233}{}{Mogê przeszukaæ dla ciebie ruiny.}
{234}{}{Przynieœ co znajdziesz, chêtnie zap³acê potrójn¹ cenê.}
{235}{}{Dobra. Przyniosê ci ka¿dy mocny alkohol, jaki znajdê w ruinach.}
{236}{}{Masz wielkie szczêœcie. Tak siê sk³ada, ¿e mam przy sobie butelkê przedwojennej whisky.}
{237}{}{(Otwiera butelkê, w¹cha, smakuje.) Doskona³a jakoœæ! Ten napój jest wart swojej ceny. Oto twoja kasa - }
{238}{}{ kapsli. Przynieœ mi wiêcej, jeœli znajdziesz.}
{239}{}{Koniecznie.}
{240}{}{Mam butelkê przedwojennej whisky do twojego baru.}

{241}{}{Kucha i ja szukamy jego dru¿yny. Mo¿e coœ s³ysza³eœ?}
{242}{}{S³ysza³em, ¿e supermutanci rozbili obóz w Balboa Park. Nie s¹ agresywne, wrêcz przeciwnie. To mo¿e byæ jednostka, której szukasz.}
{243}{}{Rozumiem. Dziêkujê.}

{260}{}{Chcê wymieniæ dolary na kapsle.}
{261}{}{Nie ma problemu. Dzisiaj kurs wynosi }
{262}{}{ kapsli.}
{263}{}{Nie dzisiaj. Lepiej poczekam na zmianê kursu.}
{264}{}{Innym razem. Lepiej pozwól mi zobaczyæ twoje menu.}
{265}{}{[Wymieñ 1 dolara]}
{266}{}{[Wymieñ 2 dolary]}
{267}{}{[Wymieñ 3 dolary]}
{268}{}{[Wymieñ 4 dolary]}
{269}{}{[Wymieñ 5 dolarów]}
{270}{}{[Wymieñ 10 dolarów]}
{271}{}{[Wymieñ WSZYSTKIE dostêpne dolary]}
{272}{}{Co to jest, dziura w kieszeni? Dzieje siê...}
{273}{}{Tak, to jest...}
{274}{}{Proszê.}
{275}{}{Dziêkujê.}

{280}{}{Chcê wynaj¹æ pokój, ¿eby odpocz¹æ.}
{281}{}{To bêdzie Ciê kosztowaæ }
{282}{}{ kapsli.}
{283}{}{Dlaczego tak du¿o?}
{284}{}{Bo jesteœ g³adki.}
{1284}{}{Bo jesteœ g³adka.}
{285}{}{To rasism!}
{286}{}{Jeœli ci siê to nie podoba, to œpij na zewn¹trz.}
{287}{}{OK, zap³acê za jedn¹ noc.}
{288}{}{Niewa¿ne, dziêkujê.}
{289}{}{Nie mogê nic na to poradziæ. Wszystkie pokoje s¹, hmm, zajête.}
{290}{}{Naprawdê? Nie k³amiesz mnie?}
{291}{}{To denerwuj¹ce.}
{292}{}{Gdybyœmy mieli wolne pokoje, wola³bym je daæ supermutantom ni¿ tobie.}
{293}{}{Bêdê o tym pamiêtaæ, zielony.}
{294}{}{W sumie to i tak niczego nie chcia³em. Zapomnij o tym.}
{295}{}{Nie masz wystarczaj¹cej iloœci kapsli na nasze us³ugi. Najpierw idŸ coœ zarobiæ.}
{296}{}{OK.}
