{100}{}{Widzisz Szalonego Gonzo.}
{101}{}{Widzisz œwiec¹cego ghula o dzikim spojrzeniu. Wydaje siê wrogi.}
{102}{}{Szalony Gonzo nie reaguje na ciebie.}
{103}{}{Arrr!}
{104}{}{To wina zmar³ego. Kucha nie ma z tym nic wspólnego.}

{200}{}{Rrr... c-cz³owiek... ghul... strach...}
{201}{}{Jestem przyjacielem, chcê ci pomóc.}
{202}{}{...przyjaciel... mi³oœæ... ¿ycie...}
{203}{}{Tak, tak, twoi przyjaciele-ghule martwi¹ siê o ciebie. ChodŸmy do nich, oni siê tob¹ zaopiekuj¹.}
{204}{}{Gonzo... chce... przyjació³...}
{205}{}{ChodŸmy ju¿, zanim zmienisz zdanie.}
{206}{}{Nie, nie, zaraz. Poczekaj tu chwilê.}
{207}{}{Ach, zwariowa³eœ! Bojê siê ciebie!}
{208}{}{Zycie. I œmieræ. Twoja œmieræ!}