{100}{}{Widzisz Roya.}
{101}{}{Widzisz przywódcê Czarnych Poszukiwaczy.}
{102}{}{Pozdrowienia.}

{200}{}{Hej, stój! To jest nasz teren kopalniany. Nie potrzebujemy ciê tutaj. OdejdŸ st¹d.}
{1200}{}{Stój! To jest nasz teren kopalniany. Nie potrzebujemy ciê tutaj. OdejdŸ st¹d.}
{201}{}{OK.}
{202}{}{Dlaczego mam ciê s³uchaæ?}
{203}{}{Szukasz œmierci, czy postrada³eœ zmys³y? S³uchaj dobrze. To jest NASZE terytorium. ZnajdŸ sobie inn¹ fabrykê i rób tam, co chcesz. Ale tutaj nie przychodŸ.}
{204}{}{OK.}
{205}{}{Na pustkowiu co twoje to i moje. To proste.}
{206}{}{Dok¹d ty idziesz? Nie boisz siê? WyjdŸ st¹d!}
{1206}{}{Dok¹d ty idziesz? Nie boisz siê? WyjdŸ st¹d!}
{207}{}{Przestañ! To jest nasz te... Cholera, supermutant! Wszyscy do broni!}
{208}{}{O nie, nie, czekaj...}
{209}{}{OK. To twoja wina, idioto...}

{210}{}{Wiem, co siê tutaj dzieje. Pracujesz bez pozwolenia Starego Miasta. A poza tym zniewalasz ghule.}
{211}{}{Tak. I co?}
{212}{}{Nic. Ciekawi mnie tylko, jak to siê sta³o.}
{213}{}{Powinieneœ wypuœciæ ghule.}
{214}{}{Wspó³czujesz tym upiorom? Ich czas ju¿ dawno min¹³. Niech chocia¿ teraz zrobi¹ coœ dobrego.}
{215}{}{Po co ci te ghule?}
{216}{}{Bo nie jesteœmy ze stali. Widzisz to? Nie mamy wystarczaj¹cej ochrony, aby pracowaæ w tak toksycznym obszarze. A ghule mog¹ tam pracowaæ godzinami bez szkody dla zdrowia. Wiêc niech pracuj¹ i przynosz¹ korzyœci ludziom.}
{217}{}{Rozumiem.}
{218}{}{Dlaczego odmawiasz przyjêcia Pieczêci Seta?}
{219}{}{Bogactwa Dawnych Czasów nale¿¹ do tego, kto je znajdzie. Tak jest wszêdzie. I tak jest sprawiedliwie. Mamy do nich takie same prawa jak ghule. Do diab³a, to nasze bogactwa!}
{220}{}{Czego tu w ogóle szukasz?}
{221}{}{Wszystko, co przydatne, jest na sprzeda¿ w Hub. Ale najbardziej smakowitym k¹skiem s¹ tutaj chipy. Na pó³nocy s¹ goœcie, którzy dobrze za nie zap³ac¹.}
{222}{}{Teraz chcê wiedzieæ, co ciê obchodz¹ ghule i nasza fabryka?}
{223}{}{Niewa¿ne. Czy mogê po prostu odejœæ?}
{224}{}{Powinieneœ wypuœciæ ghule.}
{225}{}{Wspó³czujesz tym upiorom? Ich czas ju¿ dawno min¹³. Niech chocia¿ teraz zrobi¹ coœ dobrego. A mo¿e chcesz pracowaæ zamiast nich, co?}
{226}{}{Cholera. Po prostu za³adujê broñ i zastrzelê was wszystkich.}
{227}{}{Uch, nie, ta praca nie jest dla mnie.}
{228}{}{Wiêc wypierdalaj z naszego terytorium!}
{229}{}{OK.}
{230}{}{Co za swietny pomys³. Co trzeba zrobiæ, abyœ wypuœci³ ghule?}
{231}{}{Co za niespodzianka! OK, przynieœ mi 10 chipów. To wystarczy, aby im odpuœciæ. A potem pójdziemy handlowaæ na pó³noc.}
{232}{}{Rozumiem.}
{233}{}{Robisz siê bezczelny. Bêdzie ³atwiej wszystkich was st¹d po prostu wykopaæ!}
{234}{}{Nadal czekam na chipy. No dalej, zaskocz mnie!}
{235}{}{Pieprz siê!}
{236}{}{Naprawdê siê staram. Wkrótce bêd¹ u twoich stóp.}
{237}{}{Oto jeden chip.}
{238}{}{Oto chipy, }
{239}{}{ szt.}
{240}{}{To w³aœnie to, czego mi trzeba. Pozosta³o }
{241}{}{ szt. No dalej, ruszaj siê.}
{242}{}{Ostatni? Ho-ho, jesteœ szybszy od tych trupów. Swietnie. Teraz mo¿esz pójœæ pobawiæ siê ze swoimi zielonoskórymi przyjació³mi czy co tam chcesz. Nie mamy tu nic innego do roboty. W „Sokole Maltañskim” czekaj¹ na nas brzêcz¹ce kapsle i kobiety! Hej, bracia, pora ruszaæ!}
{243}{}{Myœlê, ¿e nikt tutaj nie bêdzie za wami têskni³.}
{244}{}{Czeœæ.}
{245}{}{Uch! Myœla³em, ¿e jesteœ kolejnym ghulem. A ty jesteœ po prostu dziwakiem. Nie potrzebujemy tu takich jak ty. OdejdŸ st¹d.}

{250}{}{Przys³a³ mnie burmistrz Starego Miasta.}
{251}{}{Tak? I czego chce?}
{252}{}{Niczego. Musia³em tylko zobaczyæ, co tu robisz.}
{253}{}{Mia³ jak¹œ ofertê. Ale zapomnia³em jak¹. To nie ma znaczenia, bo i tak mia³em zamiar was wszystkich zabiæ!}
{1253}{}{Mia³ jak¹œ ofertê. Ale zapomnia³am jak¹. To nie ma znaczenia, bo i tak mia³am zamiar was wszystkich zabiæ!}
{254}{}{Ma ofertê. Otrzymasz od niego Pieczêæ Seta i rozpoczniecie wspó³pracê. Ale musisz znaleŸæ dla niego chipy z tej fabryki i w jak najkrótszym czasie uwolniæ ghule.}
{255}{}{Wiêc te chipy s¹ wa¿ne nawet dla ghuli, tak? Ha, tak, trafiliœmy na kopalniê z³ota! OK, Pieczêæ Setha to wielka sprawa, jeœli siê nad tym zastanowiæ. Nie bêdziemy musieli dŸwigaæ daleko ton rzeczy, nie bêdziemy nêkani i w ogóle – staniemy siê teraz wa¿nymi osobami w mieœcie, prawda? Jest tylko jedno „ale”.}
{256}{}{O co chodzi?}
{257}{}{Ta fabryka to jedna pieprzona nora kretoszczurów! Jest tu pe³no szlamu i miejsc o wysokim poziomie promieniowania. Poza tym nie rozumiem nic z tej technologii. Dlatego to ghule pracuj¹ - nie przejmuj¹ siê promieniowaniem i doskonale wiedz¹ co znajduj¹. Dlatego jeœli „wielkiemu szefowi” bêdzie zale¿a³o na szybkiej realizacji kontraktu, ktoœ bêdzie musia³ popracowaæ w strefie zagro¿enia.}
{258}{}{Chyba tylko ja mogê to przyœpieszyæ.}
{259}{}{Swietnie. Przynieœ mi 10 chipów.}
{260}{}{Dobra.}
{261}{}{Naprawdê myœlisz, ¿e znajdê je i ci tak po prostu dam? Precz st¹d!}
{262}{}{Ostatni? Ho-ho, jesteœ szybszy od tych trupów. Swietnie. Teraz mo¿esz pójœæ pobawiæ siê ze swoimi zielonoskórymi przyjació³mi czy co tam chcesz. Nie mamy tu nic innego do roboty.W „Sokole Maltañskim” czekaj¹ na nas brzêcz¹ce kapsle i kobiety! Hej, bracia, pora ruszaæ!}
{263}{}{Ostatni? Ho-ho, jesteœ szybszy od tych trupów. Doskonale. Na Starym Mieœcie czekaj¹ na nas brzêcz¹ce kapsle i drinki. Hej, bracia, pora ruszaæ!}
{264}{}{Gotowe. Czas wróciæ na Stare Miasto.}
{265}{}{Nie b¹dŸ arogancki. Teraz ghule s¹ tutaj panami. Bêdziesz dla nich pracowaæ i przestrzegaæ ich zasad.}
