{100}{}{Widzisz ghula.}
{101}{}{Widzisz przed sob¹ ghula. Ma na sobie obro¿ê z wbudowanym paralizatorem.}
{102}{}{Wypuszczasz nas? Bo¿e b³ogos³aw! Na tej ziemi wci¹¿ s¹ dobrzy ludzie.}

{110}{}{Z³apali nas i zmuszaj¹ do zbierania tych rzeczy.}
{111}{}{Nie bij nas, cz³owieku. Staramy siê jak mo¿emy.}
{112}{}{Jeden z nas oszala³. Lepiej trzymaj siê od niego z daleka.}
{113}{}{Ci Poszukiwacze nawet nie wiedz¹, do czego to s³u¿y.}

{120}{}{Ka¿¹ nam pracowaæ.}
{121}{}{Ciebie te¿ dopadli? Masz pecha, przyjacielu.}
{122}{}{Jeden z nas oszala³. Lepiej trzymaj siê od niego z daleka.}
{123}{}{Ci Poszukiwacze nawet nie wiedz¹, do czego to s³u¿y.}
