{100}{}{Widzisz stra¿nika karawany.}
{101}{}{Widzisz jednego ze stra¿ników karawany.}
{102}{}{Cicho! W tej chwili najwa¿niejsze jest trzymanie siê z dala od oczu tych cholernych mutantów.}
{103}{}{Uch! Teraz mo¿na odpocz¹æ.}
{104}{}{OK, idê do ciebie. Wiesz, jak wydostaæ siê st¹d niezauwa¿onym, prawda?}
{105}{}{Tak, dobry pomys³. Musimy znaleŸæ siê ni¿ej ni¿ trawa, ¿eby unikn¹æ problemów.}
{106}{}{Kierowca karawany jest bezpieczny.}
{107}{}{Co oni mog¹ zrobiæ? Jeszcze trochê i walnê ich w twarz!}

{110}{}{Dziêkujemy za ratunek.}
{111}{}{Te supermutanty dawno by nas za³atwi³y, gdyby nie ty.}
{112}{}{To by³o wielkie szczêœcie ¿e ciê spotkaliœmy.}
{113}{}{Droga powrotna nie bêdzie ³atwiejsza.}
{114}{}{Tak siê zastanawiam, czy jest tu bar?}

{120}{}{Rutger przepad³. Kto bêdzie teraz negocjowa³ z ghulami?}
{121}{}{Bez Rutgera podró¿ powrotna bêdzie szczególnie trudna.}
{122}{}{Ze wzglêdu na œmieræ Rutgera mo¿emy w ogóle nie otrzymaæ zap³aty.}

{130}{}{Po eksplozji na wyspie sta³o siê jasne, ¿e ju¿ NIC nie da siê st¹d wynieœæ.}
{131}{}{Gustavo próbuje nas wypêdziæ z miasta. Tak, on jest szalony!}
{132}{}{Butler dotar³ do bazy wojskowej. Ju¿ nied³ugo bêdziemy p³ywaæ w kapslach!}
{133}{}{}
{134}{}{Ghule biegaj¹ jak mrówki po napalmie. Pierwszy raz widzê coœ takiego. Dla naszego portfela to nic dobrego.}
