{100}{}{Widzisz Raymonda, autystycznego ghula.}
{101}{}{Widzisz jednego z ghuli. Ci¹gle liczy i przesuwa rzeczy.}
{102}{}{Ghul z radoœci¹ bierze twoje pude³ko i dodaje je do swojej kolekcji.}
{103}{}{To jest moje pude³ko, Bern!}
{104}{}{Pud³a! Pud³a! Pud³a!}
{105}{}{Bardzo zdenerwowa³eœ ghula, zabieraj¹c holodysk. Nikt w San Ysidro ci tego nie wybaczy.}
{106}{}{ODDAJ MOJE PUDELKO!}
{107}{}{Oddajesz holodysk w³aœcicielowi. Twoja reputacja zosta³a przywrócona.}
{108}{}{To jest MOJE pude³ko!}

{110}{}{Gard³o! Gard³o! Gard³o!}
{111}{}{Ci ludzie bêd¹ tu ca³y dzieñ, Bern!}
{112}{}{To niezaplanowana wizyta, Bern!}
{113}{}{To nie jest weekendowa wizyta, Bern!}
{114}{}{82! 82! 82 wyka³aczki!}
{115}{}{Jedna wyka³aczka, dwie wyka³aczki, trzy wyka³aczki...}
{116}{}{Piêæ. Trzy. Piêæ. Dziewiêæ. Dwa. Szeœæ. Dwa.}
{117}{}{Jedno pude³ko, dwa pude³ka, trzy pude³ka...}
{118}{}{Pud³a, pud³a, pud³a...}
{119}{}{Oddaj mi moje pude³ka!}