{100}{}{Widzisz wêdruj¹cego ghula.}
{101}{}{Widzisz przed sob¹ jednego z ghuli. Na jego wykrzywionej twarzy widaæ przebieg³y wyraz.}
{102}{}{Hej, mo¿esz mnie podrzuciæ do Hub?}
{103}{}{Czeœæ.}

{200}{}{Hej, co za niespodzianka! Nie s¹dzi³em, ¿e s¹ tu czystokrwiœci. Mi³o mi ciê poznaæ. Jestem Bradley. Mo¿e powinienem pokazaæ ci drogê?}
{201}{}{Bradley, widzia³eœ Steve’a Morgana?}
{202}{}{Nie. Dlaczego go szukasz?}
{203}{}{Ma coœ czego chc¹ Truckersi.}
{204}{}{Nawet nie wiem, jak ci pomóc. Steve boi siê czystej krwi i ukrywa siê przed nimi. Mogê siê jednak z nim skontaktowaæ, jeœli chcesz, i poprowadziæ mediacje.}
{205}{}{Dziêki, Bradley. By³bym wdziêczny, gdybyœ dowiedzia³ siê, czego chce za swój przedmiot.}
{1205}{}{Dziêki, Bradley. By³abym wdziêczna, gdybyœ dowiedzia³ siê, czego chce za swój przedmiot.}
{206}{}{(odchodzi i za chwilê wraca) Znalaz³em Steve'a. Potrzebuje 1000 kapsli na sterownik paliwa. I co ty na to?}
{207}{}{Nie mam tyle.}
{208}{}{No to nie bêdzie ¿adnej umowy. Do widzenia.}
{209}{}{[OdejdŸ]}
{210}{}{Hej, czekaj, akurat mam 1000 kapsli. Teraz przynieœ towar.}
{211}{}{To w³aœnie rozumiem – cz³owiek interesu! Có¿, wszystkiego najlepszego, partnerze.}
{212}{}{Do widzenia.}
{213}{}{Teraz oddaj kapsle, kretynie.}
{214}{}{Nie k³amiesz? Powiedziano mi, ¿e Steve Morgan poszed³ t¹ drog¹.}
{215}{}{Nie, nie jestem Steve Morgan. Dlaczego go szukasz?}
{216}{}{Nie próbuj ze mn¹ tych numerów. Powiedz mi, do cholery, czy ty jesteœ Steve Morgan?}
{217}{}{To nie ja, to nie ja!}
{218}{}{K³amiesz, suko!}
{219}{}{Przepraszam. Gdzie w takim razie jest Morgan?}
{220}{}{Nie zabijaj mnie! OK, wzi¹³em sterownik paliwa. Ci karawaniarze nie p³ac¹ zbyt wiele. Spodziewa³em siê, ¿e sprzedam to coœ w Hub za du¿o pieniêdzy... Hej, a co powiesz na to? Ja ci sprzedam kontroler za 800 kapsli, a ty odsprzedasz go Truckersom, pasuje ci to?}
{221}{}{Ale oni p³ac¹ o po³owê mniej.}
{222}{}{Cholera racja. Ale zrozum, ¿e to mój przedmiot i to ja ustalam cenê, nie oni. To jak, zamierzasz to kupiæ?}
{223}{}{Nie.}
{224}{}{No to nici z umowy. Do widzenia.}
{225}{}{[OdejdŸ]}
{226}{}{Czekaj, zmieni³em zdanie. Oto 800 kapsli. Teraz przynieœ towar.}
{227}{}{Jeœli nie chcesz oddaæ kontrolera po dobroci, to wezmê go si³¹...}
{228}{}{Tak. Oto 800 kapsli.}
{229}{}{Tak. Oto 1000 kapsli.}
{230}{}{Morgan nadal chce sprzedaæ kontroler za 1000 kapsli. To jak, deal?}
{231}{}{Warunki siê nie zmieni³y: 800 kapsli i kontroler jest Twój. Zamierzasz go kupiæ?}
