{100}{}{Widzisz ob³¹kanego nieumar³ego.}
{101}{}{Widzisz jednego z ghuli. Mamrocze coœ niezrozumiale.}

{110}{}{Jestem cz³owiekiem bez serca. Bez serca! Wiesz dlaczego? Wiesz?}
{111}{}{W moim sercu jest potwór. Zjad³ serce. Odszed³.}
{112}{}{Nie mamy du¿o czasu.}
{113}{}{Mamy ostatni¹ szansê.}
{114}{}{Gdzie jest moja skrobaczka do czaszki?}
{115}{}{Wszyscy coœ straciliœmy. Wszyscy jesteœmy zgubieni.}
{116}{}{Zaœpiewaj coœ na po¿egnanie.}
{117}{}{Chcê tylko zobaczyæ œwiat³o.}
{118}{}{Spoczywaj w pokoju, cz³owieku.}
{119}{}{Witaj w piekle, kochanie.}
{120}{}{*mamrocze*}
