{100}{}{Widzisz ghula.}
{101}{}{Widzisz jednego z upiorów.}

{102}{}{Bez muzyki jest tu trochê nudno. No nie?}
{103}{}{Hej, dziêki za muzykê!}

{110}{}{Znasz Taliusa?}
{111}{}{No có¿, on nie jest taki jak my chocia¿ jest mutantem.}
{112}{}{Talius g³osi s³owo Bo¿e.}
{113}{}{Ja te¿ wierzy³em w Boga i chodzi³em do koœcio³a w weekendy.}
{114}{}{Ale po latach nieœmiertelnoœci ju¿ w nikogo nie wierzê.}
{115}{}{Nie pozwól, ¿eby inni wdarli siê do twojej duszy.}