{200}{}{Hej, szeregowy Kucha! Czy on jest normalny?}
{201}{}{Kucha jest moim podw³adnym. I ty te¿ powinieneœ mnie s³uchaæ.}
{202}{}{Grr! Banda zdrajców! Smieræ normalnym!}
{203}{}{Czekaj...}
{204}{}{Kucha i ja jesteœmy przyjació³mi. Zaskoczony, zielony?}
{205}{}{Kucha przyjaŸni siê z normalnym? Ho-ho-ho, nie wierzê! Jesteœ jego giermkiem. Hej, zaskoczy³eœ mnie. Zostaw niewolnika na boku i pomó¿ nam wydostaæ ludzi z tej twierdzy.}
{206}{}{Nie wa¿ siê mnie poni¿aæ, zielona istoto!}
{207}{}{Jesteœ zbyt gadatliwy, niewolniku. Wyrwe ci jêzyk!}
{208}{}{No có¿.}
{209}{}{Kucha, wyjaœnij, ¿e nie jestem niewolnikiem i ¿e powinni zostawiæ ludzi w spokoju.}
{210}{}{Banda normalnych? To nie jest dobre! Kucha znowu nas wszystkich zdenerwowa³. Banda zdrajców! Smieræ normalnym!}
{211}{}{Czekaj...}
{212}{}{Zyj dalej, normalny. Masz dziœ szczêœcie.}
{213}{}{Mistrz patrzy na mnie z nieba. Nie zhañbiê jego imienia!}
{214}{}{Wiêc puszczasz mnie, co? Dziêkujê.}
