{100}{}{Widzisz Rutgera.}
{101}{}{Widzisz przywódcê oddzia³u Truckerów.}
{102}{}{Cicho! Pogadamy w obozie.}
{103}{}{Rutger dotar³ do obozu karawan.}
{104}{}{Trzymaj siê z daleka, mutancie! Zabije ciê, kurwa!}

{200}{}{Spodziewa³em siê zobaczyæ tutaj kogokolwiek, ale nie normaln¹ osobê.}
{201}{}{Ghule wys³a³y mnie na pomoc.}
{202}{}{Mutanci czekali na nas w zasadzce. Na szczêœcie w porê je zauwa¿yliœmy i okopaliœmy siê w tych magazynach. Nie s¹ na tyle g³upie by nas tu od razu zaatakowaæ, ale to kwestia czasu. Mo¿esz nas st¹d wyprowadziæ?}
{203}{}{Myœlê, ¿e mogê. W koñcu uda³o mi siê tu dotrzeæ.}
{204}{}{Swietnie. Wiêc chodŸmy, jeden za drugim. Najpierw wyprowadŸ moich podw³adnych.}
{205}{}{OK.}
{206}{}{Odwrócê uwagê mutantów, a ty wyprowadzisz stra¿ników. Razem obronimy siê przed supermutantami.}
{207}{}{OK.}
{208}{}{Jesteœ sam, prawda? W takim razie wynoœmy siê st¹d!}
{209}{}{ChodŸmy.}
{210}{}{Wychodzenie st¹d teraz nie jest bezpieczne. Musisz trochê poczekaæ.}
{211}{}{Widzia³em, jak mutanty odchodz¹ autostrad¹. Ale to mo¿e byæ pu³apka. Najpierw spróbuj wydostaæ moich podw³adnych.}
{212}{}{Nie s¹dzê, ¿e mo¿emy st¹d wyjœæ niezauwa¿eni. Mo¿e pierwsi zaatakujemy wroga?}
{213}{}{Nie mogê nara¿aæ moich ludzi. U¿yjmy sprytu. Najpierw wyprowadŸ stra¿ników.}
{214}{}{Wkrótce bêdzie tu wiêcej ludzi ni¿ ghuli. Wygl¹da na to, ¿e potrzebujesz pomocy, prawda?}
