{100}{}{Widzisz œlepego ghula.}
{101}{}{Widzisz jednego z ghuli, siedzi na wózku inwalidzkim.}

{110}{}{Kim jesteœ? Przedstaw siê.}
{111}{}{Pozwól mi dotkn¹æ twojej twarzy.}
{112}{}{Wiêc jesteœ normalny? Nie dotykaj mnie!}
{113}{}{Proszê, nie rób mi krzywdy!}
{114}{}{Zostaw Blask w spokoju!}

{120}{}{Kim jesteœ? Przedstaw siê.}
{121}{}{Znam wszystkie ghule w tym piekle. Ale ciebie akurat nie znam.}
{122}{}{Nie ¿yjesz. Ja te¿ jestem martwy. Dlaczego jeszcze siê nie spotkaliœmy?}
{123}{}{Pozostanê na zawsze w ciemnoœci.}
{124}{}{Powiedz mi, jak wygl¹da Blask?}