{100}{}{Widzisz Rutgera.}
{101}{}{Widzisz przywódcê oddzia³u Truckerów.}

{200}{}{Jesteœmy szczêœliwi, ¿e ciê mamy. Brak mi s³ów, ¿eby wyraziæ wdziêcznoœæ za uratowanie nam ty³ków. Tutaj, w nagrode weŸ karabin maszynowy. Jak mogê Ci teraz pomóc?}
{1200}{}{Mamy szczêœcie, ¿e ciê mamy. Brak mi s³ów, ¿eby wyraziæ wdziêcznoœæ za uratowanie nam ty³ków. Tutaj, w nagrode weŸ karabin maszynowy. Jak mogê Ci teraz pomóc?}
{201}{}{Najpierw porozmawiajmy.}
{202}{}{Wygl¹da na to, ¿e przewozi³eœ jakiœ towar. Mogê spojrzeæ?}
{203}{}{Ten przedmiot by³ przeznaczony dla ghuli, ale nie byli zainteresowani... }
{204}{}{[Handel]}
{205}{}{Och, tak przy okazji, myœla³em o kupieniu kilku rzeczy od ghuli. Ale nie chc¹ ich oddaæ, albo chc¹ za nie za du¿o. Zap³acê ci, jeœli znajdziesz je dla mnie w ruinach.}
{206}{}{Dobrze. Jakich rzeczy potrzebujesz?}
{207}{}{Nie, nie bêdê szukaæ jakichœ starych artefaktów.}
{208}{}{Czego jeszcze potrzebujesz?}
{209}{}{To wszystko. Zegnaj, Rutgerze.}
{210}{}{Chcê ciê zapytaæ o coœ innego.}
{211}{}{Muszê jeszcze raz przyjrzeæ siê twoim towarom.}
{212}{}{Szukam tych rzeczy: 1) chip wodny, 2) p³ytka drukuj¹ca, 3) p³ytka diagnostyczna, 4) sterownik paliwa, 5) plany latacza.}
{213}{}{Przyniosê ci to, jeœli znajdê. Do widzenia.}
{214}{}{Porozmawiajmy o tych starych rzeczach, których szukasz.}
{215}{}{Znalaz³eœ coœ?}
{216}{}{Jeszcze nie. Jeœli coæ znajdê, przyniosê. Do widzenia.}
{217}{}{Po co ci te wszystkie stare artefakty?}
{218}{}{Mój szef Butch w Hub bêdzie strasznie niezadowolony, jeœli wrócê z pustymi rêkami. A Hub potrzebuje wielu ró¿nych rzeczy. I nie tylko ono. Ca³a Kalifornia ¿yje dziêki staro¿ytnej technologii. Z biegiem czasu staje siê coraz trudniej dostêpna.}
{219}{}{Rozumiem.}
{220}{}{Gdzie mogê znaleŸæ chip wodny?}
{221}{}{Z tego co wiem Krypty Vault-Tec korzysta³y z takiej technologii. I wiem, ¿e w okolicach San Diego by³a jedna taka Krypta. Ale nie mam jej dok³adnych wspó³rzêdnych.}
{222}{}{Gdzie mogê znaleŸæ p³ytkê drukuj¹c¹?}
{223}{}{Tê technikê mo¿na znaleŸæ tylko w starych drukarkach. Mieszkañcy Hub chc¹ drukowaæ w³asne pieni¹dze i musz¹ do tego uruchomiæ prasê drukarsk¹. I to jest ta czêœæ, której nie maj¹.}
{224}{}{Gdzie mogê znaleŸæ p³ytkê diagnostyczn¹?}
{225}{}{To jest czêœæ autodoktora. Takie coœ stosowano kiedyœ w du¿ych szpitalach.}
{226}{}{Gdzie mogê znaleŸæ sterownik paliwa?}
{227}{}{Zabawna sprawa. Kupiec po drugiej stronie mówi, ¿e niedawno przywieziono mu takie coœ z innego obozu. Ale nie mo¿e tego znaleŸæ. Stary pierdziel musia³ to zgubiæ wœród tych wszystkich œmieci.}
{228}{}{Gdzie mogê znaleŸæ plany latacza?}
{229}{}{Wiesz o bazie wojskowej na wyspie Coronado? A lotnisku wojskowym? Zosta³y rozbite na strzêpy przez eksplozje nuklearne. Ale ghule mówi¹, ¿e istnia³a tu tak¿e fabryka serwisuj¹ca sprzêt wojskowy. Mo¿e tam jest coœ takiego? Swoj¹ drog¹, nie mam pojecia, co to jest ten „latacz”.}
{230}{}{Mam }
{231}{}{.}
{232}{}{Swietna robota! Oto twoje 400 kapsli. Zabiorê to do Centrum.}
{233}{}{Dziêki za wszystko.}
{234}{}{Zakoñczy³eœ kontrakt z Truckerami. Dobra robota!}
{235}{}{Dobrze ciê widzieæ.}
{236}{}{Czeœæ.}
{237}{}{[Kontynuuj rozmowê]}
{238}{}{Dobrze ciê widzieæ... Ciebie, ale nie twojego zmutowanego przyjaciela.}
{239}{}{Wygl¹da na to, ¿e nie jesteœmy ju¿ mile widziani w Blasku. Wkrótce opuœcimy to miejsce.}

{240}{}{Sk¹d przyby³a twoja karawana?}
{241}{}{Jesteœmy z Hub. Znajduje siê tam nasze g³ówne biuro.}
{242}{}{Opowiedz mi o Hub.}
{243}{}{To najwiêksze miasto w Kalifornii. Centrum waluty kapsli i handlu. G³ówny dostawca czystej wody. Ma tam swoj¹ siedzibê wiêkszoœæ ludzi i firm. Ale jest te¿ wiêcej problemów.}
{244}{}{Rozumiem.}
{245}{}{Phoenix równie¿ u¿ywa kapsli.}
{246}{}{W Phoenix te¿? Hm! W Hub waluta kapsli jest wspierana od wielu lat. Ktos musia³ przenieœæ ten pomys³ na wschód. Jacy ludzie mogliby przekroczyæ toksyczn¹ przepaœæ miêdzy Arizon¹ a Kaliforni¹? To bardzo interesuj¹ce!}
{247}{}{Wróæmy...}
{248}{}{Co to za firma?}
{249}{}{Z jakiej firmy jesteœ?}
{250}{}{Jesteœmy firm¹ zajmuj¹c¹ siê handlem w Hub. Przewozimy towary z jednej osady do drugiej.}
{251}{}{Co to za Hub, mo¿esz mi o tym opowiedzieæ?}
{252}{}{To musi byæ ciê¿ka praca?}
{253}{}{Bardzo. Przez jakiœ czas cierpieliœmy z powodu najazdów supermutantów i wszelkiego rodzaju œmieci. Wiele ludzi i braminów ginê³o, dopóki jeden cz³owiek tego nie powstrzyma³. Mieszkaniec Krypty, tak go wszyscy nazywali.}
{254}{}{Sk¹d wziê³y siê supermutanty?}
{255}{}{Te sukinsyny rabowa³y karawany i porywa³y ludzi, by zmieniæ ich w takich dziwaków jak oni. W Hub nikt o nich nawet nie wiedzia³. I wtedy jedna osoba ujawni³a ten sekret. Wszyscy byli przera¿eni.}
{256}{}{No dalej.}
{257}{}{Znam tê historiê. Nie musisz kontynuowaæ.}
{258}{}{Wtedy ten tajemniczy przybysz i ch³opaki z Bractwa Stali ruszyli na ich gniazdo. Ale czêœæ zielonej armii prze¿y³a i rozproszy³a siê po pustkowiach.}
{259}{}{Dziêki za te historie, Rutger. Nic o tym nie wiedzia³em.}
{1259}{}{Dziêki za te historie, Rutger. Nic o tym nie wiedzia³am.}
{260}{}{Dziêki za te historie, Rutger. Nawet Inferno mi o tym nie powiedzia³o.}
{261}{}{Mówi¹c o supermutantach. Wiesz sk¹d pochodz¹?}
{262}{}{O którym biurze mówi³eœ?}
{263}{}{Niektóre osady niefortunnie stanê³y im na drodze. Dlatego w ostatnich latach ludzie walcz¹ z mutantami. Nic dziwnego, ¿e czêœæ zielonych drani znalaz³a siê tutaj, z dala od ludzkich siedzib.}
{264}{}{Co siê sta³o z tym Mieszkañcem Krypty?}
{265}{}{Nie wiem. Po tym wszystkim po prostu wyparowa³. Od tego czasu nikt o nim nie s³ysza³.}
{266}{}{Butler obiecuje du¿e zamówienia. Zachowuje siê jakby trafi³ na ¿y³ê z³ota.}
