{100}{}{Widzisz ghula.}
{101}{}{Widzisz zwyk³ego ghula.}

{102}{}{Och, dziêki, przychodzisz w sam¹ porê.}
{103}{}{To jedzenie jest zimne! OK, nic nie mo¿na z tym zrobiæ. ChodŸ tu.}
{104}{}{Lubisz rozdawaæ jedzenie, prawda? Dziêkujê.}
{105}{}{W³aœnie tego mi trzeba!}
{106}{}{Dziêkujê. Ale nie mam na napiwek.}
{107}{}{(}
{108}{}{) Klient otrzyma³ swoje zamówienie.}
{109}{}{Ten klient otrzyma³ ju¿ swoje zamówienie.}

{110}{}{Och, mamo, to cz³owiek!}
{111}{}{G³adka skóra w Blasku? Nie mogê uwierzyæ w³asnym oczom!}
{112}{}{Co robi tu ten normalny?}
{113}{}{Nie mamy jeszcze doœæ g³adkich twarzy.}
{114}{}{G³adkoskórzy dopadli nas nawet tutaj.}

{115}{}{Temu normalnemu mo¿na zaufaæ.}
{116}{}{Cz³owiek w Blasku? Wariat!}
{117}{}{Normalni pope³nili b³¹d. Potrzebuj¹ czasu, ¿eby to zrozumieæ.}
{118}{}{Byæ mo¿e nie wszystkie g³adkie twarze s¹ z³e.}
{119}{}{Chcemy po prostu ¿yæ z dala od g³adkich twarzy.}

{120}{}{G³adkie twarze znalaz³y nas nawet tutaj.}
{121}{}{Zgadnij, ile mam lat?}
{122}{}{Blask Dnia to cudowne miasto.}
{123}{}{Szkoda, ¿e Harolda nie ma z nami. Pojecha³ na pó³noc.}
{124}{}{Nie ruszaj siê! Straci³em rozum... Haha, to mój ulubiony ¿art.}
{125}{}{Nadal brakuje mi Nekropolis.}
{126}{}{Nekropolis jest teraz bardziej martwe ni¿ kiedykolwiek.}
{127}{}{Wci¹¿ dr¿ê, kiedy przypominam sobie spojrzenie Setha.}
{128}{}{Gdzie s¹ moje w³osy? Pozby³em siê ich w 2077 roku. Hahaha!}
{129}{}{Czasami widzê jak przez mg³ê sytuacje z mojego poprzedniego ¿ycia.}

{130}{}{Kazdy, kto móg³, rzuci³ siê na wyspe Coronado.}
{131}{}{Ghule dawno nie by³y tak aktywne!}
{132}{}{Ten, który otworzy³ nam drogê do Coronado, jest naszym bohaterem.}
{133}{}{Koronado jest teraz nasze!}
{134}{}{Zajmijmy siê teraz Coronado!}

{135}{}{Ech, takie mia³em plany co do Coronado...}
{136}{}{Coronado mog³o nam pomóc. Szkoda.}
{137}{}{Z wyspy Coronado nic nie zosta³o.}
{138}{}{Na wyspie wybuch³a stara bomba. Zastanawiam siê tylko czy sama, czy z pomoc¹ kogoœ innego?}
{139}{}{Mia³em szczêœcie, ¿e nie by³em na molo w czasie eksplozji.}

{150}{}{Zatrzymaj siê, szefie! Stojê spokojnie!}
{151}{}{Wyrazy szacunku, funkcjonariuszu.}
{152}{}{Jestem obywatelem przestrzegaj¹cym prawa.}
{153}{}{Mi³o jest widzieæ resztki prawa na pustkowiach... Och, to nie twoja odznaka!}
{154}{}{Musisz mieæ ze sto lat s³u¿by, co?}
{155}{}{Inni te¿ bawili siê w ten sposób prawem. A na koniec zagrali w trzeci œwiat.}
{156}{}{Czy jestem aresztowany?}