{100}{}{Widzisz pana DeSanti.}
{101}{}{Widzisz przed sob¹ ghula w przedwojennym garniturze i fedorze. Na jego twarzy widaæ d³ug¹ bliznê.}
{102}{}{Widzisz Alberta De Santi.}

{200}{}{Trafi³eœ we w³aœciwe miejsce, dzieciaku. Jestem Albert De Santi. A to jest mój obiekt, Hotel i Sanatorium La Pensione.}
{1200}{}{Trafi³aœ we w³aœciwe miejscu, kochanie. Jestem Albert De Santi. A to jest mój obiekt, Hotel i Sanatorium La Pensione.}
{201}{}{[Dalej]}
{202}{}{Tutaj mo¿esz zapomnieæ o trudnej rzeczywistoœci. Masa¿e, filmy retro, sterylne k¹piele, opalanie radiacyjne, wykwintne dania ze szczurów, przygotowywane na zamówienie na ka¿d¹ zachciankê - powiedz mi, czego chcesz?}
{203}{}{Naprawdê? Otworzy³eœ sanatorium poœrodku spalonych ruin? Tutaj?}
{204}{}{Spokojnie, dzieciaku. To najbezpieczniejsze miejsce... No, mo¿e poza tymi szaleñcami po drugiej stronie ulicy. Wygl¹da na to, ¿e na razie nie przeszkadzaj¹ im ghule, ale to tylko kwestia czasu.}
{1204}{}{Odprê¿ siê, kochanie. To najbezpieczniejsze miejsce... No, mo¿e poza tymi szaleñcami po drugiej stronie ulicy. Wygl¹da na to, ¿e na razie nie przeszkadzaj¹ im ghule, ale to tylko kwestia czasu.}
{205}{}{OK. Bêdê o tym pamiêtaæ.}

{210}{}{O czym myœlisz, dzieciaku?}
{1210}{}{O czym myœlisz, maleñka?}
{211}{}{Niewa¿ne. Do zobaczenia.}
{212}{}{Do zobaczenia póŸniej, panie DeSanti.}
{213}{}{Do zobaczenia póŸniej, panie DeSanti.}
{214}{}{Ssss, ach! Uwielbiam zapach kapsli przed snem. OK, kochanie, naprawdê zas³ugujesz na po³owê.}
{215}{}{(potrz¹saj¹c torebk¹ z kapslami) Ach! Uwielbiam s³uchaæ brzêku kapsli podczas kolacji. OK, kochanie, naprawdê zas³ugujesz na po³owê.}

#Zadania
{220}{}{Próbowa³eœ pozbyæ siê szaleñców z s¹siedniego budynku?}
{221}{}{Zap³acê po 100 kapsli za sztukê. Zrób to, a pieni¹dze bêd¹ Twoje.}
{222}{}{Nie jest ci ich ¿al? S¹ twoimi braæmi.}
{223}{}{Pamiêtaj, ch³opcze, w tym biznesie nale¿y wiedzieæ tylko jedn¹ rzecz: strzelaj pierwszy, strzelaj do wrogów, strzelaj zawsze. W ten sposób przetrwasz.}
{1223}{}{Kochanie, w tym biznesie nale¿y wiedzieæ tylko jedn¹ rzecz: strzelaj pierwszy, strzelaj do wrogów, strzelaj zawsze. W ten sposób przetrwasz.}
{224}{}{Rozumiem. Po prostu szukam sposobu na zarobienie pieniêdzy. Uznaj, ¿e to ju¿ zrobione.}
{225}{}{Nie. Nie zrobiê tego.}
{226}{}{Wszyscy szaleñcy zostali wyeliminowani.}
{227}{}{WeŸ to, kochanie. Latwe pieni¹dze. Po prostu weŸ.}
{1227}{}{WeŸ to, kochanie. Latwe pieni¹dze. Po prostu weŸ.}
{228}{}{Podoba mi siê pana podejœcie do biznesu, panie DeSanti. Mogê nadal dla ciebie pracowaæ. Mo¿e trzeba wyeliminowaæ kogoœ jeszcze?}
{229}{}{Jest jeszcze jedna k³opotliwa osoba. Znasz Derricka? Kryje siê tu¿ za drzwiami i zabiera mi czêœæ wp³ywów ze sprzeda¿y. Nie lubiê tego! Zrób coœ z tym.}
{230}{}{OK.}
{231}{}{Derrick nie bêdzie ci ju¿ przeszkadza³. Dosta³ trochê o³owiu.}
{232}{}{Co za szkoda! Oczywiœcie nie wiesz, kto to zrobi³, prawda? (mruga i wrêcza ci 100 kapsli) Bêdziemy musieli trochê posprz¹taæ ten syf przy wejœciu.}
{233}{}{[WyjdŸ]}
{234}{}{Derrick postanowi³ ponownie przemyœleæ swoje plany na przysz³oœæ. Jest gotowy dla ciebie pracowaæ.}
{235}{}{Dobra robota, dzieciaku. Chyba warto za to dop³aciæ. (mruga i wrêcza ci 150 kapsli)}
{1235}{}{Swietna robota, kochanie. Chyba warto za to dop³aciæ. (mruga i wrêcza ci 150 kapsli)}
{236}{}{[WyjdŸ]}
{237}{}{Czy jesteœ pewien, ¿e zabijanie szaleñców to dobry pomys³?}
{238}{}{OK, cokolwiek chcesz.}
{239}{}{Przypomnij mi, co Derrick ci zrobi³?}
{240}{}{Wisia³ przy drzwiach wejœciowych i zabiera³ mi czêœæ dochodów ze sprzeda¿y. Nie lubiê tego! Zrób coœ z tym.}
{241}{}{OK.}
{242}{}{Masz jeszcze coœ do roboty?}
{243}{}{Jedno bezwartoœciowe cia³o uciek³o na Stare Miasto nie p³ac¹c mi ani kapsla za us³ugi.}
{244}{}{Jak nazywa siê to cia³o?}
{245}{}{Ma na imiê Kurt. Jest mi winien 300 kapsli. Wytrz¹œnij je z niego, a po³owa bêdzie twoja.}
{246}{}{OK.}
{247}{}{Oto kapsle, które Kurt jest winien - dok³adnie 300.}
{248}{}{Ssss, ach! Uwielbiam zapach kapsli o poranku. OK, kochanie, naprawdê zas³ugujesz na po³owê.}
{249}{}{No có¿, oczywiœcie.}

{250}{}{Wygl¹da na to, ¿e siê rozpadasz. Potrzebujesz pracownika?}
{251}{}{Jest coœ. Trudno jest sobie z tym poradziæ w pojedynkê. Naprawdê potrzebujê au pair.}
{252}{}{Mogê pracowaæ za rozs¹dn¹ stawkê.}
{253}{}{Przykro mi, nie mogê ci w tym pomóc.}
{254}{}{Jest jeden kandydat. Przynajmniej nie trzeba mu p³aciæ. Jest w spi¿arni naprzeciwko. Nazywa siê Pan R¹czka. Wystarczy postawiæ go na nogi i przypisaæ program administratora. Zap³acê 300 kapsli za tê robotê.}
{255}{}{OK, zrobiê to.}
{256}{}{Wiêc bierz siê do pracy, dzieciaku. Z³om mo¿na znaleŸæ wszêdzie, ale programu szuka³bym na Starym Mieœcie.}
{1256}{}{Wiêc bierz siê do pracy, kochanie. Z³om mo¿na znaleŸæ wszêdzie, ale programu szuka³bym na Starym Mieœcie.}
{257}{}{OK.}
{258}{}{Uda³o mi siê uruchomiæ robota. Ale gdzie mogê zdobyæ do niego program?}
{259}{}{Program administratora. Zacz¹³bym szukaæ na Starym Mieœcie.}
{260}{}{Myœlê, ¿e stanowisko administratora jest ju¿ zajête.}
{261}{}{Dobra robota, dzieciaku. Oto twoja nagroda. Przy okazji, mam dla ciebie wiêcej zadañ.}
{1261}{}{Kochanie, œwietna robota. Oto twoja nagroda. Przy okazji, mam dla ciebie wiêcej zadañ.}
{262}{}{Co to jest?}
{263}{}{Rozumiem.}
{264}{}{Nie jestem zainteresowany. Nie chcê naprawiaæ kolejnych starych urz¹dzeñ.}
{265}{}{Jeden z klientów zamówi³ stary, kultowy film, "G³êbokie Gard³o". Jak to mo¿liwe, ¿e o tym nie s³ysza³eœ? Co za zacofanie! Krótko mówi¹c, ma to ktoœ w San Ysidro. Zdob¹dŸ to dla mnie, a ja podzielê siê czêœci¹ pieniêdzy.}
{1265}{}{Jeden z klientów zamówi³ stary, kultowy film, "G³êbokie Gard³o". Jak to mo¿liwe, ¿e o tym nie s³ysza³aœ? Jaka szkoda! Krótko mówi¹c, ma to ktoœ w San Ysidro. Zdob¹dŸ to dla mnie, a ja podzielê siê czêœci¹ pieniêdzy.}
{266}{}{Dobrze.}
{267}{}{Gdzie mówisz, ¿e mo¿na znaleŸæ ten film?}
{268}{}{Niektóre ghule w San Ysidro to maj¹. Nie jestem pewien.}
{269}{}{Rozumiem.}
{270}{}{Oto film, którego szuka³eœ.}
{271}{}{Uwielbiam stare klasyki. Ale nie radzê tego ogl¹daæ. Jesteœ na to za m³ody, kochany. Po prostu weŸ swoje pieni¹dze i zapomnij.}
{1271}{}{Uwielbiam star¹ klasykê. Ale nie radzê tego ogl¹daæ. Jesteœ na to za m³oda, kochanie. Po prostu weŸ swoje pieni¹dze i zapomnij.}
{272}{}{OK.}
{273}{}{Jest jeszcze jedno zadanie. Zap³ata za nie bêdzie dobra – a¿ 500 kapsli. Ale pamiêtaj, kochanie, nie zawiedŸ.}
{274}{}{Powiedz mi, co mam zrobiæ.}
{275}{}{Poczekaj. Ani s³owa! Mówisz o powa¿nych sprawach. Odmawiam.}
{276}{}{Gdzieœ w drodze do San Ysidro zgubi³ siê robot kurierski z wa¿n¹ czêœci¹. Potrzebujê tej czêœci. Przynieœ to j¹. No dalej, rusz ty³ek, kochanie.}
{1276}{}{Gdzieœ w drodze do San Ysidro zgubi³ siê robot kurierski z wa¿n¹ czêœci¹. Potrzebujê tej czêœci. Przynieœ to j¹. No dalej, rusz ty³ek, kochanie.}
{277}{}{[WyjdŸ]}
{278}{}{Jak chcesz, dzieciaku. OK, idŸ na spacer. Ju¿ Ciê nie potrzebujê.}
{1278}{}{Jak chcesz, kochanie. OK, idŸ na spacer. Ju¿ Ciê nie potrzebujê.}
{279}{}{[WyjdŸ]}
{280}{}{Czy mo¿esz mi powiedzieæ dok³adnie, gdzie jest robot kurierski?}
{281}{}{Gdzieœ w drodze do San Ysidro. Prawdopodobnie gdzieœ na autostradzie.}
{282}{}{Rozumiem.}
{283}{}{Oto czêœæ, której szuka³eœ.}
{284}{}{Padre! Nigdy wczeœniej nie mia³em tak sprytnego dzieciaka w gangu... hm, mam na myœli, w zespole. Oto twoja nagroda. I nie s¹dzê, ¿ebym mia³ jakieœ nowe zadania. Mo¿esz odpocz¹æ, kochanie.}
{1284}{}{Madre! Od razu wiedzia³em, ¿e nas nie zawiedziesz, kochanie. Oto twoja nagroda. I chyba nie mam ju¿ wiêcej zadañ.}
{285}{}{[WyjdŸ]}
{1285}{}{Wiêc pójdê gdzieœ indziej spêdziæ czas. Bywaj, partnerze.}
{286}{}{Nawiasem mówi¹c, dlaczego ta czêœæ jest podpisana jako w³asnoœæ Eda?}
{287}{}{Nie zadawaj zbyt wielu pytañ, dzieciaku. P³acê ci za to.}
{1287}{}{Nie zadawaj zbyt wielu pytañ, kochanie. P³acê ci za to.}
{288}{}{[WyjdŸ]}
{289}{}{Hej, kochanie, coœ Ÿle zrozumia³eœ? Powiedziano mi, ¿e da³eœ tê czêœæ San Ysidro. Co to do cholery znaczy?}
{1289}{}{Hej, kochanie, coœ Ÿle zrozumia³aœ? Powiedziano mi, ¿e da³aœ tê czêœæ San Ysidro. Co to do cholery znaczy?}
{290}{}{To nie pañska sprawa, proszê pana.}
{291}{}{Jeœli siê nad tym zastanowiæ, to prawda. Ale wiesz co? Pracujesz DLA MNIE. Cholera, naprawdê mnie zdenerwowa³eœ, kochanie. Nie chcê ciê widzieæ. Wyjœæ!}
{1291}{}{Jeœli siê nad tym zastanowiæ, to prawda. Ale wiesz co? Pracujesz DLA MNIE. Cholera, naprawdê mnie zdenerwowa³aœ, kochanie. Nie chcê ciê widzieæ. Wyjœæ!}
{292}{}{[WyjdŸ]}
{293}{}{Teraz przejdzmy do naprawdê powa¿nych rzeczy. W poblizu osiedlil siê obóz Czarnych Poszukiwaczy. Oni przeczesuja MOJE ruiny i nie zaplaca podatku. Musza dla mnie pracowaæ, a jeœli nie chc¹, to niech opuszcza moja ziemie! IdŸ i rozpraw siê z nimi.}
{294}{}{Zrobi siê.}
{295}{}{Odmawiam. Twoje bandyckie ambicje nie by³y czêœci¹ moich planów. Nie mam zamiaru byæ wspólnikiem w tych podejrzanych intrygach.}
{296}{}{Nie musisz mnie denerwowaæ. Myœla³em, ¿e jesteœmy przyjació³mi. Ale w dzisiejszych czasach trudno jest znaleŸæ przyjació³. Na koniec dam ci jedn¹ radê: wyjdŸ i uwa¿aj na siebie.}
{297}{}{Odmawiam zajmowania siê twoimi problemami.}
{298}{}{Problem rozwi¹zany.}
{299}{}{Ponownie mnie nie zawodzisz.}

#Uslugi
{300}{}{Chcê siê zrelaksowaæ.}
{301}{}{Przykro mi, ch³opcze, ale moje us³ugi nie s¹ dla g³adkoskórych.}
{1301}{}{Przykro mi, kochanie, ale moje us³ugi nie s¹ dla g³adkoskórych.}
{302}{}{Szkoda.}
{303}{}{Nic, a nic? Ale moje kapsle a¿ prosz¹ siê o wydanie.}
{304}{}{Daj spokój, po prostu nienawidzisz g³adkoskórych, prawda?}
{305}{}{To tylko interesy, dzieciaku. Nie jest w moim najlepszym interesie, ¿eby klient by³ g³adki. Ale poniewa¿ jestem taki wra¿liwy, mogê powiedzieæ moim przyjacio³om-ghulom, ¿e masz dobr¹ g³adk¹ skórê. To bêdzie kosztowaæ }
{1305}{}{To tylko interesy, kochanie. Nie jest w moim najlepszym interesie, ¿eby klient by³ g³adki. Ale poniewa¿ jestem taki wra¿liwy, mogê powiedzieæ moim przyjacio³om-ghulom, ¿e masz dobr¹ g³adk¹ skórê. To bêdzie kosztowaæ }
{306}{}{Nie rób tego. Wolê uczciwe zdobyæ reputacjê.}
{307}{}{Deal.}
{308}{}{Czekam na kapsle, kochanie. Reputacja kosztuje.}
{1308}{}{Czekam na kapsle, kochanie. Reputacja kosztuje.}
{309}{}{OK.}
{310}{}{(szybko liczy kapsle) Mam gadane, wymyœlê dla Ciebie œwietn¹ i wiarygodn¹ historiê. Wszystkie ghule bêd¹ zachwycone.}
{311}{}{Liczê na ciebie.}
{312}{}{Tylko mnie nie oszukuj. Nie lubiê tego.}
{313}{}{ kapsli. Deal?}

{320}{}{Na pocz¹tek sugerujê, abyœ wzi¹³ lecznicz¹ k¹piel z moj¹ urocz¹ opiekunk¹. A jeœli masz czas i pieni¹dze, mogê zaoferowaæ dobry wypoczynek w hotelu z mo¿liwoœci¹ ogl¹dania filmów, muzyki i zabiegów medycznych. Us³uga specjalnie dla mutantów i ghuli!}
{321}{}{Myœlê, ¿e na razie wystarczy mi zwyk³a k¹piel. Ile to kosztuje?}
{322}{}{ kapsli.}
{323}{}{Dobrze. Oto kapsle.}
{324}{}{Zastanowiê siê nad tym. Ile kosztuje pe³ny pakiet wypoczynkowy?}
{325}{}{Mo¿e innym razem.}
{326}{}{Interesowa³aby mnie druga opcja.}
{327}{}{Za }
{328}{}{ kapsli, zorganizujemy pe³en zakres zabiegów, od k¹pieli uranowych i masa¿y po medytacje i palenie grzybów. Zwyk³y ghul zrzuca wtedy brud, który zgromadzi³ przez te wszystkie lata.}
{329}{}{Podoba mi siê to! Oto kapsle, nale¿ê do was.}
{330}{}{Nie mam tyle pieniêdzy. Ale k¹piel te¿ mo¿e byæ przyjemna.}
{331}{}{Za takie pieni¹dze wymagam najlepszej jakoœci! Poœpiesz siê.}
{1331}{}{Za takie pieni¹dze wymagam najlepszej jakoœci! Poœpiesz siê.}
{332}{}{Leczenie dobrze ci zrobi³o. Twoja wytrzyma³oœæ wzros³a.}
{333}{}{Zabiegi lecznicze przywróci³y ci zdrowie. Nawet jeœli spodziewa³eœ siê czegoœ wiêcej.}

{350}{}{Mam dla ciebie jeszcze jedno, ostatnie zadanie. Istnieje supermutant o imieniu Flowers. Teraz jego samotne, bezwartoœciowe cia³o depcze ziemie gdzieœ na autostradzie 805. w poszukiwaniu swojego przeznaczenia. PrzyprowadŸ go do mnie. Powiedz mu, ¿e siê nim zaopiekujê, jeœli bêdzie dla mnie pracowa³.}
{351}{}{OK.}
{352}{}{Flowers ju¿ tu jest.}
{353}{}{Ju¿ tu jest, kochanie! Flowers bêdzie doskona³¹ ochron¹ dla mojego dobytku. Nie mam ju¿ dla ciebie pracy. Oto Twoja ostatnia zap³ata. Gratulujê przejœcia na emeryturê.}
{354}{}{[WyjdŸ]}
{355}{}{Flowers nie ¿yje.}
{356}{}{Cholernie z³e wieœci. A ja nie lubiê z³ych wieœci. Zdenerwowa³em siê, kochanie. WyjdŸ. Nie mam ju¿ dla ciebie pracy.}
{357}{}{[WyjdŸ]}
{358}{}{Flowers nie chcia³ dla ciebie pracowaæ. Zosta³ Poszukiwaczem.}
