{100}{}{Widzisz Franka.}
{101}{}{Widzisz ghula w garniturze i kapeluszu, zupe³nie jak za starych, dobrych czasów.}
{102}{}{Dziêkujê, przyjacielu. Bez Ciebie ta historia mog³aby zakoñczyæ siê bardzo Ÿle.}
{103}{}{Nie dotykaj mnie, g³adka buzio! Jestem na krawêdzi.}
{104}{}{Przepraszam, ale jestem zbyt podekscytowany, ¿eby teraz rozmawiaæ.}

{110}{}{Jane, jeœli go nie znajdziemy, przestanê piæ. Obiecujê.}
{111}{}{Przygotuj siê na najgorsze, Jane.}
{112}{}{Pewnego dnia i tak by siê to sta³o.}
{113}{}{Nie p³acz. Bo ja te¿ bêdê p³akaæ.}