{100}{}{Widzisz Jane.}
{101}{}{Widzisz przed sob¹ ghula w zwyk³ym przedwojennym stroju.}
{102}{}{Dziêkujê za uratowanie Donovana. Przygotowaliœmy siê ju¿ na najgorsze.}
{103}{}{Przepraszam, jestem teraz zbyt podekscytowana.}

{200}{}{(Jane) ...Frank, czujê, jakby coœ mu siê sta³o. Wróci³by dawno temu... Och, jesteœmy pods³uchiwani.}
{1200}{}{(Frank) ...Mówiê ci, Jane, on ma k³opoty! Inaczej ju¿ dawno by wróci³... Hej, pods³uchujesz nas, G³adka BuŸko?}
{201}{}{Co siê sta³o?}
{202}{}{(Frank) Nie twoja sprawa, cz³owieku. To nasza martwa sprawa.}
{203}{}{[Dalej]}
{204}{}{(Jane) Och, przepraszam, Frank, jest teraz strasznie zdenerwowany.}
{205}{}{Rozumiem... no to co siê sta³o?}
{206}{}{Wybacz mi. A teraz powiedz mi, co tu siê do cholery sta³o.}
{207}{}{(Jane) Zgubiliœmy naszego przyjaciela Donovana. Poszed³ do San Ysidro i nie wróci³. A w San Ysidro te¿ go nikt nie widzia³.}
{208}{}{[Dalej]}
{209}{}{(Frank) Jane, po co ty mu to mówisz, do cholery? I tak mamy ju¿ doœæ problemów przez te g³adkie twarze. Nie zdziwi³bym siê, gdyby Donovan by³ ofiar¹ Poszukiwaczy.}
{210}{}{[Dalej]}
{211}{}{(Jane) Frank, potrzebujemy pomocy, czy to nie oczywiste?}
{212}{}{[Dalej]}
{213}{}{(Frank) Hmm, s³uchaj, g³adka twarzo, nie masz innych zajêæ? Albo nam pomó¿, albo idŸ gdzieœ i nie przeszkadzaj. Nie chcê zadawaæ siê z ludŸmi. Jasne? Ale przyda³aby nam siê pomoc.}
{214}{}{Pomogê wam. Czy Ci siê to podoba, czy nie. Chcê tylko pokazaæ, ¿e nie wszyscy ludzie s¹ Ÿli.}
{215}{}{(Jane) Och, to wspaniale! Widzisz, Frank, zawsze mo¿na siê dogadaæ. Dziêkujê. Bêdziemy czekaæ na wiadomoœæ od Ciebie.}
{216}{}{OK. Do zobaczenia.}
{217}{}{Naprawdê nie obchodz¹ mnie wasze problemy. Poœpiesz siê.}
{218}{}{(Frank) Hej, hej, hej, nie œpiesz siê tak! Na wszelki wypadek pamiêtaj, ¿e nasz przyjaciel Donovan przebywa w ruinach gdzieœ w drodze do San Ysidro. Jeœli go spotkasz... có¿, przynajmniej przypomnij mu o nas, dobrze?}
{219}{}{OK. Do zobaczenia.}
{220}{}{(Jane) ...Frank, czujê, ¿e coœ mu siê sta³o. Wróci³by dawno temu... Och, jesteœmy pods³uchiwani.}
{221}{}{[Dalej]}
{222}{}{(Frank) Hmm. Nie pamiêtam twojej twarzy. Ale i tak mi³o ciê widzieæ. Czy mo¿esz poœwiêciæ nam trochê czasu?}
{223}{}{Czego ode mnie chcesz?}
{224}{}{(Jane) Straciliœmy naszego przyjaciela Donovana. Poszed³ do San Ysidro i nie wróci³. W San Ysidro te¿ go nikt nie widzia³.}
{225}{}{Niech zgadnê - prosisz mnie, ¿ebym go znalaz³?}
{226}{}{Jesteœ m¹dry jak na ghula. W ka¿dym razie potrzebujemy pomocy. Donovan jest teraz gdzieœ w ruinach w drodze do San Ysidro. Jeœli go spotkasz... có¿, postaraj siê nie zostawiaæ go w k³opotach, dobrze?}
{227}{}{OK. Do zobaczenia.}

{230}{}{Masz jakieœ wieœci o naszym przyjacielu?}
{231}{}{Jeszcze nie. Bêdê szukaæ dalej.}
{232}{}{Jak myœlisz, gdzie on mo¿e byæ?}
{233}{}{Uda³ siê do San Ysidro. Ale tam nie dotar³ i nie wróci³. Wiêc mo¿e byæ gdzieœ po drodze.}
{234}{}{Mo¿e w³aœnie znalaz³ skrzynkê piwa i postanowi³ sam j¹ otworzyæ?}
{235}{}{Rozumiem. Bêdê szukaæ dalej.}
{236}{}{O czym ty mówisz? Donovan by³ mózgiem naszej skromnej firmy. ...........}
{237}{}{Mam z³e wieœci. Znalaz³em cia³o Donovana. Donovan nie ¿yje.}
{238}{}{Dlaczego nikt mi nie powiedzia³, ¿e Donovan jest niski? Nic dziwnego, ¿e tak trudno by³o go znaleŸæ.}
{239}{}{(Jane) O Bo¿e, Donovan, obudŸ siê! (Frank) Donovan, znowu ty i te twoje ¿arty! Przestañ siê wyg³upiaæ!}
{240}{}{Em. Jesteœcie g³upi? On jest martwy. Martwy martwy.}
{241}{}{Bêdziecie musieli zaakceptowaæ prawdê. Cia³o zosta³o rozdarte na pó³. To nie do pogodzenia z ¿yciem.}
{242}{}{S³uchaj, musimy go tylko zabraæ do lekarza. ZnajdŸ Taliusa w San Ysidro. Postawi Donovana na nogi. My nie zrobimy tego tak szybko jak ty.}
{243}{}{Chyba zwariowaliœcie! Mo¿e chocia¿ ten Talius wyjaœni wam, ¿e nie da siê o¿ywiæ umar³ych.}
{244}{}{Mówisz powa¿nie? OK, mam nadziejê, ¿e to ciê trochê uspokoi.}
{245}{}{Nie marnuj czasu! Zabierz Donovana do Taliusa.}
{246}{}{OK, OK.}
