{100}{}{Widzisz Donovana.}
{101}{}{Widzisz robota, wewn¹trz którego funkcjonuje mózg Donovana.}

{110}{}{Teraz jestem robotem. To takie niezwyk³e. I super!}
{111}{}{W tym ciele czujê siê o wiele lepiej!}
{112}{}{Czujê siê, jakbym by³ o sto lat m³odszy.}
{113}{}{Nigdy nie czu³em siê tak dobrze jak teraz.}
{114}{}{Myœlê, ¿e wszystkie ghule powinny tego spróbowaæ.}
{115}{}{Wy ¿a³osni ludzie, nie macie pojêcia, jak bardzo jesteœcie delikatni!}
{116}{}{DeSanti próbowa³ mnie zabiæ. Podziêkujê mu za to.}
{117}{}{}
{118}{}{}
{119}{}{}