{100}{}{Widzisz Izaaka.}
{101}{}{Widzisz przed sob¹ ghula w znoszonym ubraniu roboczym.}
{102}{}{Znowu bêdê musia³ wszystko zrobiæ sam...}
{1102}{}{Znowu bêdê musia³ wszystko zrobiæ sam...}
{103}{}{Swietna robota... jak na g³adkiego.}
{104}{}{To maszynownia. Mam nadziejê, ¿e tutaj wszystko bêdzie dzia³aæ, bo inaczej stacja nie bêdzie ju¿ do niczego potrzebna.}
{105}{}{Jesteœmy blisko. OdprowadŸ mnie do konsoli w sterowni.}

{200}{}{Nie s¹dzi³em, ¿e zobaczê tu normalniaka. Musisz mieæ promieniowanie w dupie?}
{201}{}{Nowy i prosto do piek³a? To w³aœnie rozumiem! Ale uwa¿aj, jest tu bardzo niebezpiecznie.}
{1201}{}{Nowy i prosto do piek³a? To w³aœnie rozumiem! Ale uwa¿aj, jest tu bardzo niebezpiecznie.}
{202}{}{Senor Gustavo mnie przys³a³. Jak mogê ci pomóc?}
{203}{}{Co tu robisz?}
{204}{}{Próbujemy tutaj dokonaæ niemo¿liwego, zmusiæ tamê do wytwarzania pr¹du. To w³aœnie z góry zosta³o przejête przez roboty wojskowe podczas wojny nuklearnej. Nikogo nie wpuszcz¹.}
{205}{}{Dok¹d chcesz iœæ?}
{206}{}{Muszê siê dostaæ do centrum kontroli. Jest gdzieœ pod ziemi¹. Spróbuj znaleŸæ bezpieczny sposób. W przeciwnym razie nie jestem jeszcze gotowy, aby staæ siê czêœci¹ lokalnej cudownej przyrody.}
{207}{}{Dobrze. Ale najpierw spróbujê przejœæ sam.}
{208}{}{Wiêc chodŸ ze mn¹. Wiem, jak omin¹æ roboty.}
{209}{}{Najpierw powiedz mi, co to za miejsce?}
{210}{}{To jest tama Bonita. Zosta³a zaprojektowana do magazynowania wody. Elektrowniê wybudowano tu ju¿ w czasach kryzysu, gdy zabrak³o paliwa p³ynnego. Jej moc ledwo wystarcza na potrzeby Blasku. Ale w mieœcie nie ma ¿adnej innej stacji, która przetrwa³a.}
{211}{}{Muszê siê dostaæ do centrum kontroli. Wygl¹da na to, ¿e jesteœmy na dobrej drodze.}
{212}{}{To centrum kontroli. Wygl¹da na to, ¿e nie by³o czyszczone od d³u¿szego czasu. Nic, jesteœmy do tego przyzwyczajeni... A to najwyraŸniej jest panel sterowania? Poczekaj chwilê... I... Gotowe. Hmm. Stacja jest zamkniêta. Trzeba bêdzie popracowaæ rêcznie.}
{213}{}{Co mam zrobiæ?}
{214}{}{Musimy uruchomiæ drug¹ turbinê w maszynowni. Mo¿e to wymagaæ wiele wysi³ku.}
{215}{}{Rozumiem.}
{216}{}{To maszynownia. Ale teraz musimy dostaæ siê do centrum kontroli.}
{217}{}{Poczekaj tutaj.}
{218}{}{Pod¹¿aj za mn¹.}

{220}{}{Ta tama pozostanie ¿a³osnym kawa³kiem betonu, dopóki nie sprawimy, ¿e bêdzie dzia³aæ dla Blasku.}
{221}{}{Tylko nie mów mi, ¿e siê tu zgubi³eœ.}
{1221}{}{Tylko nie mów mi, ¿e siê tu zgubi³aœ.}
{222}{}{Poczekaj chwilê. Nied³ugo wrócê.}
{223}{}{Co mam teraz zrobiæ?}
{224}{}{Gotowe, druga turbina znów siê krêci.}
{225}{}{Hm, jeœli turbina pracuje, dlaczego dalej nie wytwarza pr¹du? Prawdopodobnie nast¹pi³a przerwa w dostawie pr¹du. Przyjrzyj siê dobrze ca³emu ³añcuchowi od turbiny do prze³¹cznika.}
{226}{}{Zartujesz...}
{227}{}{Dobrze.}
{228}{}{Wygl¹da na to, ¿e nie ma ju¿ przerwy w sieci.}
{229}{}{Rzeczywiœcie... zamierzam w³¹czyæ podstacjê... Cholera, podstacja nie odpowiada. Prawdopodobnie te¿ zosta³a zapieczêtowana. Trzeba bêdzie tam pójœæ i j¹ uruchomiæ. Pamiêtaj: energiê musimy skierowaæ wy³¹cznie na linie energetyczne w San Ysidro i na Starym Mieœcie. Pozosta³e obwody musz¹ zostaæ wy³¹czone.}
{230}{}{Tak jest!}
{231}{}{Myœlê, ¿e to ja tutaj wykonujê ca³a pracê...}
{232}{}{Bonito! S³yszysz te piêkne trzaski w transformatorach i szum w przewodach? Tak dawno czegoœ takiego nie s³ysza³em... Dziêkujê, amigo. Mam nadziejê, ¿e Gustavo dobrze ciê wynagrodzi. Proszê, weŸ licznik Geigera. Bêdziesz go potrzebowaæ w drodze do San Ysidro.}
{233}{}{Zegnaj, Izaak.}
{234}{}{Ale miêdzy elektrowni¹ a dzielnicami mieszkalnymi rozci¹gaj¹ siê nieprzeniknione ruiny...}
{235}{}{Masz to! Nawet jeœli nie jesteœ z naszego wieku. Choæ jesteœmy ghulami, uruchomiliœmy ju¿ kilka dzia³aj¹cych robotów i przygotowaliœmy linie energetyczne. Reszta nie zajmie d³ugo.}