{100}{}{Widzisz Pecka.}
{101}{}{Widzisz ghula ze skrêconym krêgos³upem. Jego g³owa jest gêsto poroœniêta ma³ymi œwiec¹cymi grzybami.}
{102}{}{Nie ma problemu, proszê pana. Jak tylko skoñczê sprz¹taæ, wyjdê st¹d.}

{120}{}{Czujê siê jak milion.}
{121}{}{Jestem Peck. Paxtera. Chcesz ze mn¹ spaæ?}
{122}{}{Czy wiesz, ile mam kapsli? Nie mam kapsli. I jestem szczêœliwy!}
{123}{}{Wczeœniej nie mia³em ¿adnych pieniêdzy. Teraz nikt nie ma pieniêdzy.}
{124}{}{Zyjê jak gwiazda programu telewizyjnego.}
{125}{}{To najlepsze miejsce na œwiecie. Whoo-hoo!}
{126}{}{Peck musi za¿yæ lekarstwo. *Mniam, mniam* Bueee...}
{127}{}{Gliniarze! To gliniarze! Nie... To tylko wiatr...}
{128}{}{Wszystko w porz¹dku, u mnie wszystko w porz¹dku... wygl¹da na to.}
{129}{}{Bez obcych Blask nie jest Blaskiem.}
{130}{}{Nie jestem bezdomny. Jestem wolny od domu!}
{131}{}{Nie biorê narkotyków. Mój mózg je produkuje.}
{132}{}{Swiêty makaron!}

{200}{}{Wow, bracie! Nie sikaj tutaj, jesteœ na mojej prywatnej posesji. Dobra... nie przeszkadza mi, ¿e tu jesteœ. Ale b¹dŸ œwiadomy.}
{201}{}{Naprawdê? Mieszkasz w kana³ach?}
{202}{}{Tak, jestem bezdomny. I co? Ale ¿yje bogato! Mieszkam w najbardziej malowniczym miejscu Blasku. Sechesh?}
{203}{}{Próbowa³eœ zamieszkaæ z innymi w mieœcie?}
{204}{}{Po co? Dobrze mi tutaj. Du¿o jedzenia, ¿adnych przepisów, których trzeba przestrzegaæ, cisza i spokój.}
{205}{}{Bojê siê zapytaæ, ale co tu jesz?}
{206}{}{Nic dziwnego, ¿e jesteœ ca³y w grzybach. Widzia³eœ siê chocia¿ w lustrze?}
{207}{}{W dolinie coœ tam roœnie. Mam doœæ. Masz, chcesz trochê grzybów?}
{208}{}{No dalej. O co byœ poprosi³ w zamian?}
{209}{}{Nie rób tego. Nie interesuje mnie to.}
{210}{}{Lokalny klimat jest zbyt wilgotny. Nie inaczej by³o w Nekropolis. Ale nie trzeba daleko jechaæ, ¿eby dostaæ lekarstwo. Te¿ chcesz?}
{211}{}{Zobaczysz, wrócisz po kolejn¹ dawkê.}
{212}{}{Tak.}

{220}{}{Hej, jak siê masz?}
{221}{}{Co siê dzieje, bracie?}
{1221}{}{Jak siê masz, siostro?}
{222}{}{Co siê dzieje, dzieciaku, zgubi³eœ siê w okolicy?}
{1222}{}{Co jest, kochanie, zgubi³aœ siê w mojej okolicy?}
{223}{}{No dalej.}
{224}{}{Potrzebujê wiêcej tych œwiec¹cych grzybów.}

{230}{}{Jak siê st¹d wydostaæ?}
{231}{}{Najbli¿szy most jest zniszczony, bracie. To pech, prawda? IdŸ do centrum handlowego, stamt¹d skrêæ na autostrady federalne. I jesteœ wolny!}
{232}{}{OK, pójdê ju¿. Mi³ego pobytu.}
{233}{}{Zap³acê ci 300 kapsli, jeœli zabierzesz mnie do San Ysidro.}
{234}{}{Rozumiem, co masz na myœli. Rozumiem. Peck zna wszystkie lokalne szlaki i niebezpieczne miejsca. Beze mnie nie przejdziesz przez dolinê.}
{235}{}{Wiêc prowadŸ. Masz tu }
{236}{}{ kapsli.}
{237}{}{Nie teraz. PóŸniej.}
{238}{}{Muszê siê dostaæ do elektrowni. Zaprowadzisz mnie za 500 kapsli?}
{239}{}{Zap³acê 1500 kapsli, jeœli poprowadzisz mnie bezpiecznymi œcie¿kami na Stare Miasto.}
