{100}{}{Widzisz Phila.}
{101}{}{Widzisz przed sob¹ starszego ghula w okularach. Buja siê lekko na krzeœle w przód i w ty³.}

{200}{}{Hej, jak¹ postaci¹ z ksi¹¿ki jesteœ, kochanie? Nie pamiêtam, ¿ebym o tobie czyta³.}
{201}{}{O czym ty mówisz, stary pierdlu?}
{202}{}{Ach, przepraszam, przepraszam! Odlecia³em. A tak przy okazji, jestem Phil. Trochê ze mnie naukowiec, ¿e tak powiem.}
{203}{}{Mi³o ciê poznaæ, Phil. W dzisiejszych czasach rzadko mo¿na spotkaæ wykszta³conych ludzi.}
{204}{}{Witam bibliofilu.}
{205}{}{Jestem cz³owiekiem, a nie postaci¹.}
{206}{}{Mhm? (patrzy na ciebie przez okulary) Sk¹d ta pewnoœæ? No có¿, nadal nie da siê tego udowodniæ ani obaliæ. A tak przy okazji, jestem Phil. Trochê ze mnie naukowiec, ¿e tak powiem.}
{207}{}{Hm. To prawdopodobnie powieœæ o bohaterach czy coœ.}
{208}{}{Och, lubiê, kiedy ludzie potrafi¹ siê z siebie œmiaæ. Nie tak jak te wszystkie ponure typy za œcian¹. Wraz z budow¹ ich miasta stali siê tak powa¿ni, jak nie byli przez ca³e ¿ycie. A tak przy okazji, jestem Phil. Trochê ze mnie naukowiec, ¿e tak powiem.}
{209}{}{}

{210}{}{Czy mogê ci w czymœ pomóc?}
{211}{}{Nie, nic.}
{212}{}{Hej, jak¹ postaci¹ z ksi¹¿ki jesteœ, kochanie? Nie pamiêtam, ¿ebym o tobie czyta³.}
{213}{}{Ach, przepraszam, przepraszam! Nie mo¿na ju¿ pomarzyæ.}
{214}{}{Wygl¹da na to, ¿e jesteœ ca³kowicie poch³oniêty literatur¹.}
{215}{}{Och, lubiê, kiedy ludzie potrafi¹ siê z siebie œmiaæ. Nie tak jak te wszystkie ponure typy za œcian¹. Wraz z budow¹ ich miasta stali siê tak powa¿ni, jak nie byli przez ca³e ¿ycie.}
{216}{}{To naturalne.}
{217}{}{Mhm? (patrzy na ciebie przez okulary) Sk¹d taka pewnoœæ siebie? No có¿, nadal nie da siê tego udowodniæ ani obaliæ. Bo¿e, co za przeciêtnoœæ!}
{218}{}{Zycie jest nudne, jeœli nie sprawiasz sobie przyjemnoœci.}
{219}{}{Nie mo¿na siê z tym k³óciæ.}

{220}{}{Kim jesteœ?}
{221}{}{Jestem Phil. Trochê taki naukowiec, ¿e tak powiem. Mózg tego miasta, jeœli wolisz.}
{222}{}{Naprawdê?}
{223}{}{No có¿, pomaga³em we wszystkim, co wymaga przedwojennej wiedzy, od starych, zwyk³ych podrêczników po programy dla robotów Pan R¹czka.}
{224}{}{Rozumiem.}
{225}{}{Jestem te¿ mistrzem œwiata w szachach. Nikt, nawet przebiegli komuniœci, nie byli w stanie mnie pokonaæ. Ale to by³y prze¿ycia... nie na ca³e ¿ycie, ale na œmieræ!}
{226}{}{Ciekawe.}
{227}{}{Co powiesz na partiê szachów? Na pewno ciê pokonam i pobijê rekord œwiata.}
{228}{}{Co powiesz na partiê szachów? Pokonam ciê i pobijê rekord œwiata.}
{229}{}{Ty? Nie rozœmieszaj tego staruszka! Nie masz ani jednej szansy. Tylko mnie uda³o siê pokonaæ sztuczn¹ inteligencjê ZAX. A co dopiero ciebie.}
{230}{}{Nadal chcê spróbowaæ.}
{231}{}{Strata czasu.}
{232}{}{Wiêc zapomnij o tym. Zrobiê coœ innego.}
{233}{}{Ju¿ popelni³eœ b³¹d, mówi¹c, ¿e nie mam szans. Zawsze s¹ szanse. Wyzywam Ciê na pojedynek.}
{234}{}{Och, a¿ poczu³em napiêcie, jak w dobrej powieœci. Dam ci jedn¹ szansê. Tylko jedn¹. Jeœli mnie pokonasz, zyskasz dostêp do mojej biblioteki.}
{235}{}{Muszê przygotowaæ siê na grê. Do zobaczenia.}
{236}{}{Jestem gotowy do walki na szachownicy. Zaczynajmy!}
{1236}{}{Jestem gotowa do walki na szachownicy. Zaczynajmy!}
{237}{}{NieŸle. Ca³kiem nieŸle jak na amatora. Jednak nadal potrzebujesz du¿o wiêcej praktyki, aby mnie pokonaæ.}
{238}{}{No có¿, nie uda³o siê.}
{239}{}{Czy powinniœmy zmieniæ temat?}
{240}{}{Zosta³em pokonany? Niemo¿liwe!}
{241}{}{Chcesz zagraæ w szachy?}
{242}{}{Czy teraz widzisz, ¿e nie powinieneœ lekcewa¿yæ swoich przeciwników?}
{243}{}{To musia³ byæ przypadek. Przepraszam, ¿e pobi³em twój rekord œwiata.}
{1243}{}{To musia³ byæ przypadek. Przepraszam, ¿e pobi³am twój rekord œwiata.}
{244}{}{Nie rozumiem, jak coœ takiego mog³o siê wydarzyæ. Przecie¿ przez 90 lat uczy³em siê WSZYSTKICH mo¿liwych ruchów w szachach. Ale ten twój ruch... Dlaczego tego nie przewidzia³em? Prawdopodobnie bez rywali po prostu wyszed³em z wprawy. Dlatego wa¿ne jest, aby mieæ przeciwnika! Zdecydowanie powinniœmy siê od siebie uczyæ.}
{245}{}{Przy okazji, jasne. Czy pozwolisz mi teraz przeczytaæ twoj¹ bibliotekê?}

{250}{}{Co jest do roboty w tym mieœcie?}
{251}{}{Daj mi pomyœleæ. Oczywiœcie, prezydent miasta ma pewne zadania. Próbuje przywróciæ miasto do ¿ycia, a tak¿e uporaæ siê z nap³ywem obcych z pó³nocy. Reszta te¿ ma problemy. Ka¿dy ma swoje.}
{252}{}{Nie mo¿esz byæ bardziej szczegó³owy?}
{253}{}{Przykro mi, ale ostatnio uzale¿ni³em siê od piêknej powieœci i w ogóle nie œledzi³em miasta.}
{254}{}{Rozumiem.}
{255}{}{Co czytasz?}
{256}{}{W tej chwili czytam jak¹œ star¹ ksi¹¿kê o konkwistadorach po hiszpañsku. Nudna. Nie moje klimaty.}
{257}{}{Potrzebujesz konkretnej ksi¹¿ki? Mogê poszukaæ.}
{258}{}{No có¿, niewa¿ne. Czytaj dalej.}
{259}{}{Och, jest jedna! Tu¿ przed wojn¹ w San Diego zapowiedziano now¹ ksi¹¿kê Mortimera. Ciekawi mnie, jakie bzdury móg³ pisaæ o tym piêknym mieœcie.}
{260}{}{Gdzie mogê to znaleŸæ?}
{261}{}{Chyba gdzieœ w ruinach. Nie wiem dok³adnie.}
{262}{}{OK, poszukam jej.}
{263}{}{Wiêc poszukaj jej sobie sam. Mam lepsze rzeczy do roboty.}
{264}{}{Masz szczêœcie. Mam akurat tê ksi¹¿kê.}
{265}{}{Znalaz³em now¹ ksi¹¿kê Mortimera.}
{1265}{}{Znalaz³am now¹ ksi¹¿kê Mortimera.}
{266}{}{Nowa ksi¹¿ka! Oj, dawno nie czu³em takiego zachwytu przed najnowszym wydaniem. Zobaczmy, co Mortimer wymyœli³ sensacyjnego na temat San Diego... Aha, pewnie czekasz na jak¹œ zap³atê. Oto 100 kapsli. A teraz idŸ, idŸ, i nie zawracaj mi g³owy!}
{267}{}{Czeœæ.}

{270}{}{W tej chwili czytam star¹ ksi¹¿kê o konkwistadorach po hiszpañsku. Nudna. Nie moje klimaty.}
{271}{}{Czytam teraz ksi¹¿kê telefoniczn¹ miasta Vancouver. Bardzo monotonna narracja.}
{272}{}{W tej chwili czytam historie o ostatnich wojnach naftowych. Wiesz, wtedy wszystkie stany zajmowa³y nasze tankowce. Dobrze, ¿e to ju¿ koniec.}
{273}{}{W tej chwili czytam zbiór przepisów dotycz¹cych lotów sterowcem. Smiejesz siê? Có¿, pewnego dnia ktoœ ponownie wzniesie je w niebo. Zaufaj mi.}
{274}{}{W tej chwili czytam historiê o tym, jak komuniœci przejêli USA i zbudowali tu pañstwo totalitarne. Jak na razie wygl¹da ca³kiem nieŸle.}

{280}{}{Potrzebujê programu dla Pana R¹czki.}
{281}{}{To proste. Ale jestem teraz bardzo zajêty t¹ piêkna ksi¹¿k¹. Nie mogê siê oderwaæ!}
{282}{}{A co jeœli przyniosê ci wiêcej ksi¹¿ek?}
{283}{}{Wiêcej ksi¹¿ek?! Tak! Przynieœ mi piêæ ocala³ych ksi¹¿ek, a zrobiê ten program. Bez obaw.}
{284}{}{Dobrze.}
{285}{}{Mam akurat kilka ksi¹¿ek. Tutaj s¹.}
{286}{}{Ach, nowe dodatki! No có¿, nie ma co, trzeba oderwaæ siê od czytania. Zrobiê ci teraz ten program. Co mam dok³adnie zrobiæ?}
{287}{}{Oprogramowanie do zarz¹dzania hotelem...}
{288}{}{Mo¿e móg³byœ po prostu pomóc dobremu cz³owiekowi?}
{289}{}{Na pewno pomogê DOBREJ osobie, JESLI tak¹ zobaczê.}
{290}{}{Aha!}
{291}{}{Ja na pewno nie jestem wzorem do naœladowania. Niestety.}
{292}{}{Zapomnij o tym. Mam ksi¹¿ki. Tutaj s¹.}
{293}{}{Cz³owieku, co to za egoizm? Wszyscy siedzimy w tym razem. No dalej, pomó¿ mi z tym pieprzonym programem!}
