{100}{}{Widzisz ghula.}
{101}{}{Widzisz paskudnie wygl¹daj¹cego ghula z jednym okiem. Jego zêby s¹ zacisniête w szerokim uœmiechu.}
{102}{}{Witaj nieznajomy.}
{1102}{}{Witaj nieznajoma.}
{103}{}{PodejdŸ bli¿ej, nie bój siê. Chcê tylko „dotkn¹æ” Twojej miekkiej, g³adkiej skóry...}
{104}{}{Uciekaj, normalny, uciekaj! Jeœli ciê z³apiê, ugotujê na obiad.}
{105}{}{Naprawdê nie ma tu nic specjalnego. Ciesz siê ¿yciem pozagrobowym.}

{200}{}{Hej, ty bezczelna buŸko. ChodŸ tu. Masz kapsle?}
{201}{}{Tak.}
{202}{}{Daj mi tutaj 10 kapsli. I ¿yj.}
{203}{}{OK, oto 10 kapsli. Dla ghli wszystko.}
{204}{}{Uwa¿aj na jêzyk. Nie mam ochoty na ¿adne gierki. A teraz zniknij.}
{205}{}{Cokolwiek powiesz...}
{206}{}{Oto 10 kapsli.}
{207}{}{Dobry ch³opiec... Widzê, ¿e jesteœ bogaty. Daj mi jeszcze 10 kapsli.}
{208}{}{Oto kolejne 10 kapsli. Czy teraz jesteœ zadowolony?}
{209}{}{To wszystko. Czy teraz jesteœ zadowolony?}
{210}{}{Wystarczy. Kocham takich typów jak ty. Szkoda, ¿e nie mam ju¿ takiej si³y napêdowej jak dawniej. Po co ja z tob¹ rozmawiam? Spadaj.}
{211}{}{IdŸ do diab³a.}
{212}{}{Nie zapominaj, ¿e jesteœ nikim w tym mieœcie. Lepiej zniknij.}
{213}{}{Z wielk¹ przyjemnoœci¹.}
{214}{}{OK, to wszystko, ale to mniej ni¿ 10.}
{215}{}{Wystarczy. A teraz wynoœ siê st¹d, póki czujê siê dobrze.}
{216}{}{Nie.}
{217}{}{Nie wierzê w to. Poka¿, co masz w plecaku.}
{218}{}{Masz, spójrz.}
{219}{}{Tak myœla³em. Z g³adkich ust s³ychaæ tylko k³amstwa. W ramach kary za oszukiwanie mnie zabieram WSZYSTKIE kapsle. A teraz zniknij.}
{220}{}{Cokolwiek powiesz...}
{221}{}{Oddawaj mi moje kapsle, draniu!}
{222}{}{Tutaj, spójrz.}
{223}{}{Uch! Jesteœ do niczego. ZejdŸ z mojej ulicy.}
{224}{}{Z wielk¹ przyjemnoœci¹.}
{225}{}{Tylko dotknij moje rzeczy, a stracisz ostatnie palce.}
{226}{}{[Uciekaj przed ¿ebrakiem]}
{227}{}{[PrzejdŸ obok]}
{228}{}{Czekaj! Mówiê do ciebie, cholerny kretynie.}
{229}{}{[Ignoruj]}
{230}{}{Czego chcesz?}
{231}{}{OK, mam kapsle. Ile potrzebujesz?}
{232}{}{Ale ja nie mam kapsli.}
{233}{}{IdŸ do diab³a.}
{234}{}{Dlaczego mia³bym daæ ci kapsle?}
{235}{}{To cena za to, ¿e muszê znosiæ twoj¹ brzydk¹ g³adk¹ twarz w moim piêknym mieœcie. No dalej, kapsle, szybko.}

{250}{}{Mój szacunek, senor! Pierwszy raz w mieœcie? Pokaza³bym ci wszystkie zabytki. Za jedyne 10 kapsli.}
{1250}{}{Mój szacunek, senora! Pierwszy raz w mieœcie? Pokaza³bym ci wszystkie zabytki. Za jedyne 10 kapsli.}
{251}{}{OK, oto 10 kapsli.}
{252}{}{Przykro mi, amigo, jestem bez grosza. Mo¿e innym razem.}
{253}{}{Mucho gracias... A tak, tam jest kolej jednoszynowa, a to granica z Meksykiem. Na pó³nocy znajduje siê kolejny obóz Ghuli. To wszystko. Papa...}
{254}{}{Hej! Nic mi nie powiedzia³eœ, pieprzony oszust!}
{255}{}{To by³a... nawet ciekawa wycieczka edukacyjna. Dziêkujê.}
{256}{}{Czeœæ.}
{257}{}{Czeœæ.}
