{100}{}{Widzisz Kuchê.}
{101}{}{Widzisz supermutanta. Ma na sobie he³m wojskowy i spodnie z kamufla¿em.}

{102}{}{Nie wa¿ siê dotykaæ Mrocznych, normalny!}
{103}{}{Nie wybaczê ci tego, normalny!}
{104}{}{Moi bracia, jestem z wami!}
{105}{}{Czy moi bracia s¹ tutaj? Hoho, wiêc wiesz, po której stronie jestem.}
{106}{}{Nie wa¿ siê dotykaæ Mrocznych!}
{107}{}{Nie wybaczê ci tego!}
{108}{}{Moi bracia, jestem z wami!}
{109}{}{Widzê moich towarzyszy broni. Lepiej ich nie wkurzaæ.}

{110}{}{Mistrz mia³ racjê – wszyscy powinniœcie siê nawróciæ!}
{111}{}{Czeœæ.}
{112}{}{[do³¹cz do oddzia³u]}
{113}{}{[usuñ z oddzia³u]}
{114}{}{[usuñ broñ]}
{115}{}{Czeœæ.}
{116}{}{Zgadza siê. Nie trzeba walczyæ. Kucha to potwierdza.}
{117}{}{}
{118}{}{}
{119}{}{}

{150}{}{Tutaj ¿yj¹ umarli. Nie lubi¹ obcych. Ale nie zaatakuj¹.}
{151}{}{Najwiêkszy obóz ghuli. Normalni te¿ tu s¹.}
{152}{}{Serce ruin. To miejsce jest s³abo znane.}
{153}{}{Kucha jeszcze nie papa.}
{154}{}{Widzisz wyspê? By³a tam baza wojskowa. Ale jest zepsuta.}
{155}{}{}
{156}{}{Jeœli spotkasz dzikie bestie, nie bój siê, Kucha ciê ochroni.}
{157}{}{Kucha nie mo¿e tego zrobiæ. Kucha jest za du¿y.}
{158}{}{Nie traktujesz dobrze ghuli. Kucha nie jest ju¿ w twoim zespole.}
{159}{}{Ta osoba opuœci twoj¹ grupê, dopóki nie naprawisz swojej reputacji.}

#Pierwszy dialog
{200}{}{Cz³owiek wœród upiorów? Podejrzane!}
{201}{}{Nie, ja... niewa¿ne. Tylko mnie nie dotykaj, wielkoludzie. Zgoda?}
{202}{}{Nawet cz³owiek beszta Kucha. Ghule te¿ nie chc¹ widzieæ Kucha. Nikt nie potrzebuje Kucha!}
{203}{}{Wow, wow, uspokój siê! Nie chcê, ¿ebyœ by³ z³y. Po prostu myœla³em, ¿e ghule nie dogaduj¹ siê z ludŸmi takimi jak ty.}
{204}{}{Ludzie te¿ nie s¹ tu mile widziani. Kuchê wyrzucono z oddzia³u. Ghule powiedzia³y, ¿e zaopiekuj¹ siê Kucha, jeœli bêdzie dobry i pomocny. Kucha próbuje. Ale nadal go nie lubi¹.}
{205}{}{Kto ciê potrzebuje, góro zielonego miêsa?}
{206}{}{Kilka osób zosta³o wyrzuconych z oddzia³u. Ghule powiedzia³y, ¿e zaopiekuj¹ siê Kucha, jeœli bêdzie pomaga³ w kopalni i bêdzie siê dobrze zachowywa³. Kucha próbuje. Ale nadal go nie lubi¹.}
{207}{}{To smutne. Ale i typowe. }
{208}{}{Na co liczy³eœ, pa³o? Powinieneœ by³ zachowaæ porz¹dek, kiedy by³eœ w oddziale.}
{209}{}{Jeszcze trochê, a Kucha bêdzie szanowany. Upiory bêd¹ wiedzieæ, jaki jestem dobry. Pomogê ghulom, nawet jeœli tego nie chc¹.}
{210}{}{Swietnie. Ja te¿ pomagam ghulom. Mo¿e po³¹czymy si³y? Bêdziesz mnie chroniæ na drodze, a ja pomogê ci zdobyæ szacunek.}
{211}{}{Mam tu sprawê do za³atwienia. A Ty co tutaj robisz? Czy mutanty i ghule to to samo?}
{212}{}{Ghule nigdy ciê nie zaakceptuj¹. Zapomnij o nich, pomó¿ mi. Potrzebujê twoich miêœni.}
{213}{}{To bardzo szlachetne z twojej strony. Powodzenia. Nadszed³ czas, abym poszed³ dalej.}
{214}{}{IdŸ, cz³owieku. Nie dotknê ciê, dopóki ty nie dotkniesz upiorów.}
{215}{}{Czeœæ, Kucha.}
{216}{}{Mo¿e po³¹czymy si³y? Potrzebujê twoich miêœni na drodze. Pomogê Ci zdobyæ szacunek.}
{217}{}{Mutant i cz³owiek w tym samym sk³adzie? Ho ho, to zabawne. Ale jeœli Kucha siê przyda, bêdzie szczêœliwy.}
{218}{}{ChodŸ ze mn¹. Razem stworzymy œwietny zespó³.}
{219}{}{Swietnie. Wrócê, gdy bêdê potrzebowaæ twojej pomocy.}
{220}{}{Czego chcesz, zmutowany bracie?}
{1220}{}{Czego chcesz, siostro?}
{221}{}{Nic od ciebie nie chcê. Tylko mnie nie dotykaj, wielkoludzie. Zgoda?}
{222}{}{I ty nie ufasz Kucha? Ghule nie chc¹ widzieæ Kucha. Nikt nie potrzebuje Kucha!}
{223}{}{Co tu robisz? Jak znalaz³eœ siê wœród upiorów?}
{224}{}{To jest to! Wiesz, moglibyœmy sobie pomóc: bêdziesz mnie chroniæ na drodze, a ja pomogê ci zdobyæ szacunek. Umowa?}
{225}{}{Jeœli Kucha przyda siê ghulom, bêdzie szczêœliwy.}
{226}{}{Potrzebujê ciê. ChodŸ ze mn¹.}
{227}{}{Szeregowy Kucha spróbuje!}
{228}{}{Spokojnie, ¿o³nierzu.}
{229}{}{Szeregowy Kucha, jesteœ wolny.}
{230}{}{Przepraszam. Kucha chcia³ pomóc. Ale nie zapomnij o szeregowy Kucha.}
{231}{}{Do zobaczenia póŸniej.}
{232}{}{Od³ó¿ broñ. Nie potrzebujesz jej teraz.}
{233}{}{Muszê wyj¹æ broñ z r¹k!}
{234}{}{Dobry ch³opak.}

{240}{}{Czekam na rozkazy, dowódco.}
{241}{}{Spokojnie.}
{242}{}{Kapitanie! Szeregowy Kucha jest gotowy do pomocy, Kapitanie!}

{250}{}{Pójdziesz ze mn¹ na Pustkowia Sonory? Przyda³aby mi siê twoja ochrona.}
{251}{}{Wyjœæ do ludzi? Nie? Nie. Ludzie nie przyjm¹.}
{252}{}{OK, cokolwiek powiesz.}
{253}{}{Twoi bracia oblegaj¹ karawanê. Czy mo¿esz ich od tego odwieœæ?}
{254}{}{Nie, oni nie bêd¹ s³uchaæ Kucha. Wyrzucili Kucha ze sk³adu. Kucha nie jest dla nich dobry. Ale Kucha nie pozwala ci zabiæ dawnych towarzyszy!}
{255}{}{Rozumiem.}

{260}{}{Opowiedz mi o sobie.}
{261}{}{Szeregowy Kucha. I co?}
{262}{}{OK. Nie rozmawiajmy o tym.}
{263}{}{Kucha... to imiê czy pseudonim?}
{264}{}{To... uh... zupe³nie zapomnia³em! Kucha nie jest prawdziwym imieniem. To jest sygna³ wywo³awczy radia. Nie pamiêtam imienia. Wszystko przed Wtajemniczeniem zostaje zapomniane.}
{265}{}{Pamiêtasz kim by³eœ przed mutacj¹?}
{266}{}{Zgadza siê. Ale Kucha nie chce pamiêtaæ. Za³oœni ludzie. Chodz¹cy w swoich drobnych problemach. Mistrz próbowa³ naprawiæ ludzi. Ale nie mia³ czasu, aby dokoñczyæ swoj¹ pracê.}
{267}{}{Mi mo¿esz powiedzieæ. Z pewnoœci¹ jego wspomnienia przynajmniej czasami Ciê drêcz¹. Nie mo¿esz tak po prostu wzi¹æ i skreœliæ starego ¿ycia.}
{268}{}{Myœlisz, ¿e dlatego Kucha jest taki g³upi? Czy dlatego gada do siebie w nocy? Kucha nie lubi pamiêtaæ. Ze by³ cz³owiek, on ..................}
{269}{}{[Zachêcaj]}
{270}{}{[Wyœmiewaj]}
{271}{}{Jak dosta³eœ siê do Blasku?}
{272}{}{Wraz z dru¿yna. Szliœmy d³u¿sz¹ chwilê przez pustyniê. Sciga³ nas oddzia³ Bractwa Stali. Och, nienawidzê Bractwa! Zabili wielu towarzyszy broni i wypêdzili nas na pustkowia. Nie by³o sensu wracaæ. Zdecydowaliœmy siê wyjechaæ.}
{273}{}{[Dalej]}
{274}{}{Po drodze spotkaliœmy kilka ghuli, one opowiedzia³y nam o Blasku Dnia. Oni tak¿e uciekli przed cz³owiekami. Ludzie nienawidz¹ wszystkich.}
{275}{}{Dlaczego nie jesteœ ze swoim oddzia³em?}
{276}{}{To by³ g³odny czas. Kucha by³ tak g³odny, ¿e zjad³ ca³y zapas. Zawstydzony. Za to zosta³ wyrzucony z oddzia³u. I nie zobaczy³ ju¿ dru¿yny.}
{277}{}{Czy wiesz, gdzie jest teraz twój oddzia³?}
{278}{}{Gdzieœ w ruinach. Kucha dowie siê, jeœli pods³ucha przez krótkofalówkê.}
{279}{}{Teraz wiemy, gdzie jest twój oddzia³. Czy chcia³byœ spotkaæ swoich towarzyszy?}
{280}{}{Za wielu têskni. Ale oni nie potrzebuj¹ Kuchy.}
{281}{}{Nie martw siê o to. Zajmê siê tym. ChodŸmy.}
{282}{}{S³ysza³eœ? Twój kapitan ma k³opoty.}
{283}{}{Du¿o wœciek³oœci! Pieprzeni ludzie sprawili ju¿ tyle k³opotów! Zap³ac¹!}
{284}{}{Wiêc chcesz uratowaæ kapitana z niewoli, mimo ze zosta³eœ wygnany z dru¿yny?}
{285}{}{Kucha jest sk³onny podj¹æ ryzyko. ChodŸmy! Do przodu!}
{286}{}{OK. Jak powiesz.}
{287}{}{OK. Jeœli nie chcesz, nie bêdziemy z nimi zadzieraæ.}
{288}{}{Mam walkie-talkie, ale ze wzglêdu na du¿e promieniowanie, bez dzia³aj¹cego radia na nic siê nie przyda.}
{289}{}{Mam radio. Spróbujemy?}
{290}{}{Nie ma sensu. Wysokie promieniowanie wszystko zak³óca. Potrzebujesz mocnej anteny. Mo¿e ghule to maj¹?}
{291}{}{Wiêc dlatego radio nie dzia³a! OK, mo¿e uda nam siê znaleŸæ przekaŸnik.}
{292}{}{(Kucha dostraja czêstotliwoœæ i uwa¿nie przys³uchuje siê rozmowie. Wszystkie ¿y³y na jego twarzy nabrzmiewaj¹ od skupienia. W koñcu mówi: „S¹ w Balboa Park”).}
{293}{}{Dobrze. ChodŸmy wiêc do parku.}
{294}{}{W San Ysidro by³a stacja radiowa. Spróbujmy siê tam czegoœ dowiedzieæ.}
{295}{}{Tutaj jest stacja radiowa. Spróbujemy?}
{296}{}{Nie ma sensu. To nie dzia³a.}
{297}{}{Rzeczywiœcie. Nie dzia³a.}
{298}{}{Nic nie s³yszê! Musimy dostaæ siê do wy¿ej.}
{299}{}{OK.}

{300}{}{Jest tutaj! Przeklêci paladyni trzymaj¹ tu kapitana.}
{301}{}{Jaki masz plan?}
{302}{}{Plan? Kucha nie potrzebuje planu! Kucha jest silniejszy ni¿ jakikolwiek paladyn. Skopie im ty³ki. To ca³y plan.}
{303}{}{Dobry plan. Niezawodny jak zegar atomowy. No dalej, Kucha! Skop ty³ki tym draniom!}
{304}{}{Nie, Kucha, nie mo¿esz zabijaæ paladynów. To niebezpieczne i niew³aœciwe. Musimy uratowaæ kapitana bez u¿ycia przemocy. Rozumiesz mnie?}
{305}{}{Grr! Cholerni ludzie! Kucha chce walczyæ! Kucha nie zamierza ukrywaæ siê w cieniu!}
{306}{}{Jeœli siê nad tym zastanowiæ, twój pomys³ jest najprostszy i najbardziej niezawodny. No dalej, Kucha! Skop tych drani!}
{307}{}{Nie ma mowy! W otwartej walce mamy niewielkie szanse. Najpierw zróbmy rekonesans.}
{308}{}{Jeœli Kucha zobaczy paladyna, nie bêdzie siê powstrzymywa³. Zrozum dowódca.}
{309}{}{OK. Rozumiem.}
{310}{}{Wiesz, bêdzie lepiej, jeœli najpierw zrobiê zwiad, a ty zaczekasz tutaj. To jest rozkaz, Kucha.}
{311}{}{Kucha dziêkuje za uratowanie kapitana. Nie da³by sobie rady sam, bez ciebie. Dziêkujê.}
{312}{}{Mutant mówi „dziekujê”? To coœ nowego!}
{313}{}{Za wczeœnie, ¿eby dziêkowaæ. Nie spotkaliœmy siê jeszcze z twoim oddzia³em.}
{314}{}{Tak. Kucha powinien ponownie spotkaæ siê z oddzia³em.}
{315}{}{Wiêc chodŸmy do obozu. Dalej.}
{316}{}{No i co siê dzieje z kapitanem?}
{317}{}{B¹dŸ silny, Kucha. Kapitana ju¿ nie ma. I twojego oddzia³u te¿.}
{318}{}{BRACTWO! NIENAWIDZEEE! NIENAWIDZEEEEE!}
{319}{}{Myœlê, ¿e najlepiej bêdzie, jeœli na razie zostawiê ciê w spokoju.}
{320}{}{B¹dŸ silny, Kucha. Kapitana ju¿ nie ma.}
{321}{}{Co teraz zrobisz bez swojego oddzia³u?}
{322}{}{Kucha bêdzie ciê¿ko pracowa³ w kopalniach ghuli. Ghule potrzebuj¹ jego miêœni. Ghule nie bêd¹ ¿a³owaæ, ¿e go zatrudni³y! Tak. Kucha bêdzie przydatny. Bêdzie szczêœliwy, jeœli bêdzie przydatny. Tego w³aœnie chce Kucha.}
{323}{}{Rozumiem. Có¿, mam nadziejê, ¿e zostaniesz ze mn¹, zanim wrócê do Sonory.}
{324}{}{Oddzia³ jest gotowy na ponowne przyjêcie ciê.}
{325}{}{Bracia z zespo³u wybaczyli Kucha? To przynosi radoœæ Kucha! Ale Kucha obieca³ ju¿ pomoc ghulom. Ale czy bêdzie w stanie zdobyæ zaufanie, jeœli pewnego dnia nie bêdzie móg³ im pomóc? Powiedz mi, co teraz robiæ? Jaki jest najlepszy wybór dla Kucha?}
{326}{}{Myœlê, ¿e powinieneœ odejœæ z dru¿yn¹. Tylko wœród swoich mo¿esz byæ naprawdê szczêœliwy. A ghulom nie jesteœ nic winny.}
{327}{}{Powinieneœ zostaæ z ghulami i pomóc im odbudowaæ miasto. Twoja si³a bardzo im pomo¿e. A Twoja dru¿yna ju¿ raz Ciê odrzuci³a, mo¿e odrzuciæ Ciê ponownie. Poza tym nikt nie wie, co siê z nimi stanie po drodze.}
{328}{}{Kucha zrobi wszystko, ¿eby ju¿ nigdy wiêcej nie straciæ zaufania! Ten zespó³ nie bêdzie ¿a³owa³, ¿e zabra³ go ze sob¹. Tak. Wiêc Kucha bêdzie spokojny wœród swoich. Skorzysta i bêdzie szczêœliwy. Tego w³aœnie chce Kucha.}
{329}{}{Cieszê siê, ¿e rozwi¹zaliœmy Twój problem. Mam nadziejê, ¿e zostaniesz przy mnie, zanim twój oddzia³ opuœci Blask.}
