{100}{}{Widzisz Czarnego Poszukiwacza.}
{101}{}{Widzisz jednego z lokalnych Poszukiwaczy. Chocia¿ bardziej przypomina bandytê.}
{102}{}{Kolejny obrzydliwy ghul. Jak mnie denerwujesz!}
{103}{}{Kogo my tu mamy? Ulubieniec upiorów czy wolny Poszukiwacz? Tak czy inaczej, nie wyjdziesz st¹d...}
{104}{}{Wynoœ siê st¹d, póki mam dobry humor.}

{110}{}{Nie potrzebujemy konkurencji!}
{111}{}{Wynoœ siê z naszych ruin!}
{112}{}{Wszystko, co jest w Blasku, bêdzie nasze!}
{113}{}{Nawet nie myœl o sprawdzaniu tych ruin bez mojej zgody!}

{120}{}{Nienawidzê mutantów!}
{121}{}{Nienawidzê ghuli!}
{122}{}{Wszystkie te supermutanty i ghule s¹ wybrykiem natury.}
{123}{}{Supermutanci zrujnowali ¿ycie wielu osób. Nie mo¿na im wspó³czuæ.}
{124}{}{Jesteœ ulubieñcem mutantów? No to zastrzele ciê na miejscu!}
{125}{}{Te ghule uniemo¿liwiaj¹ nam sprawdzenie ruin.}
{126}{}{Przeklête ghule!}
{127}{}{Nie ma litoœci dla mutantów!}
{128}{}{}
{129}{}{}

{130}{}{Hej, ty ghule miêso! Jak chcesz umrzeæ?}
{131}{}{Wy, ghule, uniemo¿liwiacie nam zbieranie zasobów z ruin.}
{132}{}{Wszyscy jesteœcie dla mnie tacy sami. Zarówno ghule, jak i supermutanty to to samo gówno.}
{133}{}{Spójrz na swoj¹ brzydk¹ twarz, ghulu.}
{134}{}{Nie k³óæ siê ze mn¹, dziwaku.}
{135}{}{Powiedz, œmieciu, gdzie trzymasz swoje najcenniejsze rzeczy?}
{136}{}{Pytam po raz ostatni, gdzie s¹ kapsle?}
{137}{}{}
{138}{}{}
{139}{}{}

{140}{}{Idioci! Jak mogliœcie zgubiæ jakiegoœ œmierdz¹cego ghula?}
{141}{}{Gdzie jest ten ghul? Gdzie on jest, pytam?!}
{142}{}{Banda kretynów, nawet nie potraficie upilnowaæ zw³ok!}
{143}{}{Ten ghul jest m¹drzejszy ni¿ myœla³em...}
{144}{}{Wygl¹da na to, ¿e ghul nie by³ sam...}
{145}{}{Jeœli ten ghul wezwie swoich kumpli z San Ysidro...}
{146}{}{Cholera, ten ghul powie wszystkim, ¿e tu jesteœmy.}
{147}{}{Musimy siê st¹d wydostaæ, zanim ten ghul powie wszystkim innym.}
{148}{}{Uciek³ mi spod samego nosa...}
{149}{}{Musimy siê wydostaæ. Dajê ka¿demu godzinê na przygotowanie siê!}
