{100}{}{Widzisz Pana Pielêgniarza.}
{101}{}{Widzisz robota medycznego z serii Mister Nurse.}
{102}{}{Weo! Weo! Droga dla sanitariusza!}

{200}{}{Naprawdê mi przykro, ¿e nie mog³em uratowaæ tych ludzi!}
{201}{}{Proszê pana, przebywanie tutaj nie jest dla pana bezpieczne.}
{202}{}{Proszê pana, jeœli zachoruje pan na chorobê popromienn¹, nie bêdê móg³ panu pomóc.}
{203}{}{Proszê pana, wykrywam podwy¿szony poziom promieniowania. Lepiej opuœciæ to miejsce.}
{204}{}{Robiê, co w mojej mocy. Ale tych ludzi nie mo¿na przywróciæ do ¿ycia.}
{205}{}{Przykro mi, proszê pana, ale nie mogê uleczyæ tych ludzi.}
{206}{}{Jest tu tak wielu okaleczonych, zupe³nie jakby przed chwil¹ wybuch³a wojna.}
{207}{}{Czy znasz któregoœ z tych pacjentów?}
{208}{}{}
{209}{}{Ups, wygl¹da na to, ¿e pomyli³em drzwi.}

{1200}{}{Przykro mi, ¿e nie uda³o mi siê uratowaæ tych ludzi!}
{1201}{}{Proszê pani, przebywanie tutaj nie jest dla pani bezpieczne.}
{1202}{}{Proszê pani, jeœli dostanie pani choroby popromiennej, nie bêdê móg³ pani pomóc.}
{1203}{}{Proszê pani, wykrywam podwy¿szony poziom promieniowania. Lepiej opuœciæ to miejsce.}
{1204}{}{Robie, co mogê. Ale tych ludzi nie mo¿na przywróciæ do ¿ycia.}
{1205}{}{Przykro mi, proszê pani, ale nie mogê uleczyæ tych ludzi.}
{1206}{}{Jest tu tak wielu okaleczonych, zupe³nie jakby przed chwil¹ wybuch³a wojna.}
{1207}{}{Czy znasz któregoœ z tych pacjentów?}
{1208}{}{}
{1209}{}{Ups, wygl¹da na to, ¿e pomyli³em drzwi.}

{210}{}{Mam z³amanie. Pomó¿ mi, doktorze!}
{211}{}{Och, to niedobrze. Potrzebujesz pilnej hospitalizacji. Proszê, po³ó¿ siê, postaram siê ci pomóc.}
{212}{}{[Postêpuj zgodnie z instrukcjami pielêgniarza]}
{213}{}{Wszystko w porz¹dku. Na przysz³oœæ b¹dŸ bardziej ostro¿ny.}
{214}{}{Dziêkujê.}
{215}{}{Potrafisz leczyæ?}
{216}{}{Oczywiœcie. Jestem asystentem robota medycznego. Ale w tej chwili moje mo¿liwoœci s¹ ograniczone ze wzglêdu na brak leków. Czy mogê Ci jakoœ pomóc?}
{217}{}{Nie, nie dzisiaj.}
{218}{}{Nie ma mowy! Nie powierzê swojego ¿ycia ¿adnemu bezdusznemu kawa³kowi ¿elaza.}
{219}{}{Szeregowy Kucha ma powa¿n¹ kontuzjê. Czy mo¿esz j¹ uleczyæ?}
{220}{}{Szeregowy Kucha, gotowe.}
{221}{}{Dziêki.}
