{100}{}{Widzisz trupa.}
{101}{}{Widzisz zwyk³ego ghula.}
{102}{}{Zzz...}

{110}{}{Och...}
{111}{}{Ach...}
{112}{}{To boli...}
{113}{}{Nadal boli...}

{200}{}{Hej, stary, pomó¿ mi! Jestem ranny i chyba z³ama³em kilka koœci. Te stare domy s¹ w op³alanym stanie...}
{201}{}{Hej, ty, pomó¿ mi! Jestem ranny i chyba z³ama³em kilka koœci. Te stare domy s¹ w op³alanym stanie...}
{202}{}{O mój Bo¿e! Nie ruszaj siê, zaraz ci pomogê!}
{203}{}{Spadaj. Nie mam zamiaru brudziæ sobie r¹k takim dziwakiem.}
{204}{}{Nie pomogê ci. Ale zabiorê twoje rzeczy i zostawiê ciê na œmieræ. A tak przy okazji, nikt inny ciê tutaj nie us³yszy.}
{205}{}{O nie! NIE! Nie! Nie...}
{206}{}{Do zobaczenia w tamtym œwiecie. Mo¿e.}
{207}{}{Zartujê, staruszku! Poczekaj chwilê, wkrótce ciê wyleczê.}
{208}{}{Nie spodziewa³em siê, ¿e ktoœ mi pomo¿e, zw³aszcza w sercu radioaktywnych ruin. Dziêkujê przyjacielu.}
{209}{}{Nie ma za co. Swoj¹ droga, co tu robi³eœ?}
{210}{}{Nie zapomnij powiedzieæ o tym innym ghulom. Jak w ogóle siê tu znalaz³eœ?}
{211}{}{Przeszukiwa³em ruiny. Ale pod³ogi tutaj by³y doœæ marne. St¹paj ostro¿nie, przyjacielu. Aha, i to nie jest g³ówne niebezpieczeñstwo. Z okna widzia³em stworzenie. Ogromne, straszne, z pazurami jak szable. Nie wpadnij w jego szpony. A teraz powodzenia. Spróbujê pokustykaæ do najbli¿szego obozu.}
{212}{}{Dziêkujê za ostrze¿enie. Do widzenia.}
{213}{}{Nie pamiêtam twojej twarzy. Nie spotkaliœmy siê w Nekropolis, prawda? Dziwna sprawa. Ale tak czy inaczej, dziêkujê przyjacielu. Bez ciebie nie by³bym w stanie nawet otworzyæ drzwi wejœciowych.}
{1213}{}{Nie pamiêtam twojej twarzy. Nie spotkaliœmy siê w Nekropolis, prawda? Dziwna sprawa. Ale tak czy inaczej, dziêkujê przyjacielu. Bez ciebie nie by³bym w stanie nawet otworzyæ drzwi wejœciowych.}
