{100}{}{Widzisz Zeraha.}
{101}{}{Widzisz zwyk³ego ghula. Jest trochê posiniaczony po spotkaniu z Czarnymi Poszukiwaczami.}
{102}{}{Zzz...}
{103}{}{Daj mi spokój!}
{104}{}{Jak powiedzia³ Zerah, w skrzynce pocztowej by³y przedwojenne pieni¹dze, }
{105}{}{szt.}
{106}{}{Twoja diagnoza: to cia³o nie ¿yje.}
{107}{}{Dobry pomys³.}

{200}{}{Kim ty jesteœ?}
{201}{}{Och, bracie, pomó¿ mi. Ci bandyci nie pozwol¹ mi ¿yæ.}
{1201}{}{Och, siostro, pomó¿ mi. Ci bandyci nie pozwol¹ mi ¿yæ.}
{202}{}{Zaraz ciê rozwi¹¿ê... A teraz wynoœmy siê st¹d. Tylko b¹dŸ cicho!}
{203}{}{Widzê, ¿e masz k³opoty. Pomogê, jeœli powiesz mi, gdzie s¹ kapsle.}
{204}{}{Powiem ci! Tylko mnie st¹d wyci¹gnij.}
{205}{}{Nie zale¿y mi na tobie. Po³o¿ siê i b¹dŸ cicho.}
{206}{}{Hej ch³opaki! Tu jest!}
{207}{}{Och, ty suko...}
{208}{}{Zamknij siê!}

{210}{}{Dziêkujê, bracie. Po raz kolejny udowadniasz, ¿e normalnym nie mo¿na ufaæ.}
{1210}{}{Dziêkujê, siostro. Po raz kolejny udowadniasz, ¿e normalnym nie mo¿na ufaæ.}
{211}{}{Dziêki, ¿e uratowa³eœ mi ty³ek. Nie s¹dzi³em, ¿e ktokolwiek z g³adkich bêdzie siê mn¹ przejmowaæ.}
{212}{}{Czego chcieli od ciebie ci bandyci?}
{213}{}{To zwykli Czarni Poszukiwacze. Ale nie chc¹ sami ryzykowaæ w ruinach, wiêc okradaj¹ tych, którzy to robi¹. Tyle ¿e ja nic nie mam, nawet ¿adnej skrzynki z cennymi przedmiotami.}
{214}{}{Najwa¿niejsze, ¿ebyœ by³ bezpieczny. Od tej chwili uwa¿aj na siebie.}
{215}{}{Czujê, ¿e k³amiesz. Powiedz mi, gdzie masz swoj¹ skrytkê!}
{216}{}{OK, OK, uspokój siê! Kiedy gonili mnie Poszukiwacze, wrzuci³em wszystko do skrzynki pocztowej przy wejœciu do szpitala. Ale to wszystko, co mia³em.}
{217}{}{Sprawdzê to. Módl siê, ¿eby tam coœ by³o.}
{218}{}{Mo¿esz odejœæ.}
{219}{}{Cicho! Bo nas us³ysz¹! Najpierw wyjdŸmy na zewn¹trz.}
{220}{}{OK.}
{221}{}{Nie martw siê. Wszyscy bandyci ju¿ nie ¿yj¹.}
