{100}{}{Widzisz ghula stró¿a.}
{101}{}{Widzisz przed sob¹ ghula ubranego w zbrojê bojow¹.}
{102}{}{Nie tolerujemy konkurencji. WyjdŸ st¹d!}
{103}{}{Gdybyœ rzeczywiœcie by³ funkcjonariuszem patrolu, nie mia³byœ tutaj ¿adnej w³adzy.}
{104}{}{Czy pozwolono ci tu byæ?}
{105}{}{Nadchodz¹ du¿e zmiany.}

{200}{}{Wyjaœnijmy sobie coœ, dziwacy i g³adcy ludzie nie s¹ tu mile widziani. Ale jeœli bêdziesz siê dobrze zachowywaæ, nie dostaniesz po g³owie. Jasne? Oby. No dalej, powiedz mi, czego potrzebujesz?}
{201}{}{Witaj, bracie. Czy zosta³eœ dobrze przyjêty w San Ysidro? Potrzebujesz czegoœ?}
{1201}{}{Witaj, siostro. Czy zosta³eœ dobrze przyjêta w San Ysidro? Potrzebujesz czegoœ?}
{202}{}{Chcê tylko zadaæ kilka pytañ na temat Blasku Dnia.}
{203}{}{Czego chcesz?}
{204}{}{Niewa¿ne. Do widzenia.}
{205}{}{Pytaj.}
{206}{}{Muszê ju¿ iœæ. Dziêkujê za Twój czas.}
{207}{}{Rozumiem. Zapytam ciê jeszcze o jedn¹ rzecz, dobrze?}
{208}{}{}
{209}{}{}
{210}{}{Opowiesz mi o sobie?}
{211}{}{Emerytowany sier¿ant Robert Newsom. Przed wojn¹ dba³em o porz¹dek na ulicach Bakersfield, a teraz pilnujê porz¹dku w Blasku Dnia. Kocham moj¹ pracê. I nie pozwolê, ¿eby ktokolwiek zachowywa³ siê nieodpowiednio na mojej warcie.}
{212}{}{Co myœlisz o Gustavo?}
{213}{}{Swietnie pasuje na burmistrza. Ghule go szanuj¹. Przynajmniej tutaj, w San Ysidro. Jednak nie wszyscy na Starym Mieœcie s¹ tak rozs¹dni.}
{214}{}{Kto rz¹dzi Starym Miastem?}
{215}{}{John Butler. By³y wojskowy. Dlatego jego g³owa jest pe³na zamieszania. Zgromadzi³ wokó³ siebie nie tylko ghule, ale tak¿e supermutantów i normalnych. Ka¿dy czegoœ od niego chce.}
{216}{}{Jaki jest zwi¹zek miêdzy Gustavo i Butlerem?}
{217}{}{Ostatnio mieli wiele nieporozumieñ. Ale jestem pewien, ¿e to nie zrujnuje ich przyjaŸni.}
{218}{}{}
{219}{}{}
{220}{}{Opowiedz mi o okolicy.}
{221}{}{San Ysidro i Stare Miasto to g³ówne osady ghuli. Pomiêdzy nimi le¿¹ radioaktywne ruiny i spalone parki. Czêsto mo¿na w nich spotkaæ Czarnych Poszukiwaczy i potwory.}
{222}{}{[Dalej]}
{223}{}{Wiêkszoœæ ataków nuklearnych uderzy³a w bazê wojskow¹ i obszar przemys³owy. Dotkliwie ucierpia³o tak¿e centrum San Diego. Zniszczenia, wysokie promieniowanie, szkielety – to w³aœnie znajdziesz na ruinach. Wszêdzie pe³no robotów wojskowych. Rozproszy³y siê po w³¹czeniu syren w bazie wojskowej.}
{224}{}{Powiedz mi, jak dostaæ siê do Chula Vista?}
{225}{}{Musisz przejœæ przez dolinê Otey. Ocala³ tylko jeden most, ale zosta³ on przejêty przez roboty i zaminowany. Idziesz wiêc tam lub prosto przez dolinê. Ale w dolinie ¿yje wiele strasznych stworzeñ.}
{226}{}{Powiedz mi, jak dostaæ siê do tamy Bonita?}
{227}{}{IdŸ autostrad¹ miêdzystanow¹ 805 do znaku. Nastêpnie skrêæ w prawo.}
{228}{}{Powiedz mi, jak dostaæ siê na Stare Miasto?}
{229}{}{Bêdzie bardzo trudno dostaæ siê tam prosto przez ruiny. Naj³atwiej jest pójœæ na trasê 805 i udaæ siê do Balboa Park. Uwa¿aj na potwory w parku. IdŸ w lewo do Little Italy. A potem na pó³noc.}
{230}{}{Jakie s¹ twoje relacje z Czarnymi Poszukiwaczami?}
{231}{}{To bandyci. Zbieraj¹ fragmenty Starego Swiata, czêsto nawet nie rozumiej¹c, do czego s³u¿¹. A potem sprzedaj¹ to karawanom. Ghulom zostaj¹ jedynie okruchy. Gustavo próbuje wypêdziæ ich z naszych ruin, ale Butler chce ich okie³znaæ, rozdaj¹c Pieczêæ Seta najbardziej pos³usznym.}
{232}{}{A co z supermutantami?}
{233}{}{Supermutanty? To by³a Armia Mistrza, zosta³a podzielona na wiele czêœci i rozproszona po ruinach. Takich grup w okolicy jest wiele. Niektóre z nich s¹ agresywne, inne wspó³pracuj¹ z nami, inne dzia³aj¹ samotnie. Osamotnione, zagubione dusze.}

{241}{}{Kucha i ja szukamy jego dru¿yny. Mo¿e o nim s³ysza³eœ?}
{242}{}{S³ysza³em, ¿e supermutanci rozbili obóz w Balboa Park. Nie s¹ agresywne, wrêcz przeciwnie. To mo¿e byæ jednostka, której szukasz.}
{243}{}{Rozumiem. Dziêkujê.}
