{100}{}{Widzisz Falika.}
{101}{}{Widzisz zwyk³ego ghula.}
{102}{}{Pods³ucha³eœ zeznania trupa.}
{103}{}{Nie przeszkadzaj w mojej modlitwie!}
{104}{}{Przepraszam, ¿e na pocz¹tku by³em dla ciebie taki niemi³y.}

{105}{}{Hej, nie pods³uchuj!}
{106}{}{W³aœnie jestem w trakcie modlitwy. Za³atw swoje sprawy szybko.}
{107}{}{Przeszkadzasz w mojej modlitwie, stary!}
{108}{}{Pods³uchujesz?}

{110}{}{Padre, wiesz, jak zachowaæ œmierteln¹ ciszê, prawda?}
{111}{}{Czy mogê opowiedzieæ Ci moj¹ historiê?}
{112}{}{Pos³uchaj mnie, padre.}
{113}{}{Mój przyjaciel Zerach, choæ by³ ju¿ trupem, teraz jest dos³ownie trupem.}
{114}{}{No có¿, to niezupe³nie moja wina...}
{115}{}{Ale go zostawi³em.}
{116}{}{By³o to w szpitalu, pali³o siê.}
{117}{}{Zerach i ja szukaliœmy ratunku, kiedy natknêliœmy siê na tych Poszukiwaczy.}
{118}{}{Wci¹¿ dostajê gêsiej skórki! A ja przecie¿ nie mam skóry.}
{119}{}{Zerah zosta³ schwytany i zabity przez Poszukiwaczy. A ja ukry³em siê i uciek³em.}
{120}{}{Powiedz mi, padre, czy Bóg mi wybaczy?}

{200}{}{(Falik modli siê ¿arliwie.)}
{201}{}{Przypadkowo pods³ucha³em twoj¹ spowiedŸ.}
{1201}{}{Przypadkowo pods³ucha³am twoj¹ spowiedŸ.}
{202}{}{[Zostaw go.]}
{203}{}{Ty! Tylko odwa¿ siê komuœ powiedzieæ!}
{204}{}{Nie winiê ciê. Rozumiem ciê. Zachowa³eœ siê m¹drze.}
{205}{}{Och, przyjacielu, proszê, nie mów nikomu!}
{206}{}{Naprawdê? Oh dziêkujê. Ale Zeraha to nie przywróci.}
{207}{}{Jesteœ pewien, ¿e nie ¿yje?}
{208}{}{Taki kretyn jak ty nie zas³uguje na moj¹ uwagê. Ty ¿a³osny tchórzu i s³abeuszu, jak mo¿na zostawiæ przyjaciela w potrzebie!}
{209}{}{Latwo ci mówiæ! Nie by³o Ciê tam! Nawet nie znasz Zeraha. Co ciê to obchodzi?}
{210}{}{Jesteœ pewien, ¿e nie ¿yje?}
{211}{}{Nie mo¿e byæ inaczej! Jego cia³o prawdopodobnie nadal znajduje siê w szpitalu. Ale nie mam odwagi tam pójœæ, ¿eby go zabraæ i pochowaæ.}
{212}{}{Mogê to zrobiæ. Oczywiœcie nie bez powodu.}
{213}{}{OK, poszukam jego cia³a. Twoja historia mnie poruszy³a.}
{214}{}{Nie potrzebujê twojej pomocy! Lepiej mnie zostaw i nie dotykaj mnie wiêcej.}
{215}{}{Nie martw siê. Bywaj.}
{216}{}{By³bym wdziêczny.}
{217}{}{Nie martw siê. Bywaj.}

{220}{}{(Falik wci¹¿ ¿arliwie siê modli.)}
{221}{}{[Zostaw go.]}
{222}{}{Zerah rzeczywiœcie nie ¿yje. Jego cia³o le¿y w szpitalu.}
{223}{}{(pauza) Aha. Wiedzia³em. Niepotrzebnie da³eœ mi nadziejê. Ale przynajmniej teraz mam pewnoœæ.}
{224}{}{Zycie to taka suka. Poœpiesz siê.}
{225}{}{Przykro mi.}
{226}{}{Zerah ¿yje. Poszukiwacze z³apali go i torturowali. Ale uda³o mi siê wyci¹gn¹æ go z k³opotów.}
{227}{}{ON ZYJE?! Dobry Bo¿e, moje modlitwy zosta³y wys³uchane! Niebiosa mi ciê zes³a³y.}
{228}{}{Nie, nie. Bóg nie ma z tym nic wspólnego.}
{229}{}{Niech i tak bêdzie, jeœli chcesz.}
{230}{}{Czy mogê ciê prosiæ o jeszcze jedn¹ przys³ugê? Czy mo¿esz mi pomóc zawrzeæ z nim pokój? ZnajdŸ go i powiedz, ¿e chce prosiæ go o przebaczenie!}
{231}{}{}
