{100}{}{Widzisz ghula.}
{101}{}{Widzisz jednego z ghuli. Wygl¹da wyj¹tkowo nêdznie.}

{102}{}{Witam. Sk¹d siê tu wzi¹³ taki przystojniak?}
{1102}{}{Witam. Sk¹d siê tu wziê¹a taka piêkna kobieta?}
{103}{}{Witam, przyjacielu. Uwa¿aj na ruiny.}
{1103}{}{Czeœæ dziewczyno. Uwa¿aj na ruiny.}
{104}{}{Uratuj mnie przed tymi g³upimi mutantami!}
{105}{}{Ostatni raz by³em w takiej sytuacji przed wojn¹. Wtedy bandyci, teraz mutanci, niewiele siê zmieni³o.}
{106}{}{Ugh, myœla³em, ¿e ju¿ nie ¿yjê. Tutaj, jako nagrodê przyjmij œrodek pobudzaj¹cy i s³owa wdziêcznoœci. Dziêkujê przyjacielu.}
{1106}{}{Ugh, myœla³em, ¿e ju¿ nie ¿yjê. Tutaj, jako nagrodê przyjmij œrodek pobudzaj¹cy i s³owa wdziêcznoœci. Dziêkujê dziewczyno.}

{110}{}{Nie dotykaj mnie, jesteœmy tej samej krwi!}
{111}{}{Nikomu nie powiem, ¿e ciê widzia³em. Serio.}
{112}{}{Nie w twarz! Zosta³ mi tylko jeden z¹b...}
{113}{}{Daj mi spokój!}
{114}{}{Nie mam co jeœæ!}
{115}{}{Niech ktoœ pomo¿e!}
{116}{}{Czego ode mnie chcesz?}
{117}{}{Mówiê ci, nie mam jedzenia.}
{118}{}{Mo¿e powinieneœ zapolowaæ na pustkowiach, co?}
{119}{}{Ej, zostañmy przyjació³mi, co?}