{102}{}{Jestem dzisiaj mi³y. Ale nie wchodŸ mi wiêcej w drogê.}
{103}{}{Smieræ normalnym!}
{104}{}{Uratuj mnie przed tymi g³upimi mutantami!}
{105}{}{Ostatni raz by³em tak naciskany przed wojn¹. Wtedy mafia, teraz mutanci, niewiele siê zmieni³o.}
{106}{}{Ugh, myœla³em, ¿e jestem trupem. Tutaj, jako nagrode przyjmij œrodek pobudzaj¹cy i s³owa wdziêcznoœci. Dziêkujê przyjacielu.}
{107}{}{}
{108}{}{}
{109}{}{}

{200}{}{Kogo my tu mamy? ChodŸ tu, cz³owieku! Bêdziesz moim s³odkim poczêstunkiem...}
{201}{}{Najpierw mnie z³ap, idioto.}
{202}{}{Proszê, nie dotykaj mnie!}
{203}{}{Moi bracia te¿ prosili, kiedy normalni ich zabijali. UMIERAJ, SUKO!}
{204}{}{Przestañ, szumowino!}
{205}{}{Nie...}
{206}{}{S³uchaj, próbujê pomóc ghulom. Zlituj siê nade mn¹, nie jestem twoim wrogiem!}
{207}{}{Ty? Pomóc? Ghulom? Ha ha ha, dobre sobie! Nie wiedzia³em, ¿e tacy g³upcy wci¹¿ ¿yj¹.}
{1207}{}{Ty? Pomóc? Ghulom? Ha ha ha, dobre sobie! Nie wiedzia³em, ¿e tacy g³upcy wci¹¿ ¿yj¹.}
{208}{}{Proszê, wypuœæ mnie i tego ghula. Nikt ci tu nie grozi.}
{209}{}{Po co ja w ogóle siê odzywam? Pora umieraæ!}
{210}{}{Och, szkoda w ogóle ubrudziæ sobie rêce. Nie wchodŸ mi wiêcej w drogê.}
{211}{}{Uch, ju¿ mnie tu nie ma...}
{212}{}{Kolejny trup. Mamy szczêœcie, ¿e mo¿emy dzisiaj iœæ na ca³oœæ. Dobry czas.}
{213}{}{Wygl¹dasz na wielkiego i groŸnego, ale nie masz mózgu.}
{214}{}{Proszê nas nie dotykaæ! Jesteœmy tej samej krwi!}
{215}{}{Nie musimy byæ dla siebie wrogami. Oboje jesteœmy mutantami. Mo¿e zostaniemy przyjació³mi?}
{216}{}{Co powiedzia³eœ? Zamknij gêbê! Nie jesteœmy brudnymi mutantami, jesteœmy czystej krwi ¿o³nierzami Mistrza!}
{217}{}{Wygl¹da na to, ¿e go wkurzy³em...}
{1217}{}{Wygl¹da na to, ¿e go wkurzy³am...}
{218}{}{Hmm, to prawda. Ludzie nienawidz¹ nas za to. Ale to wszystko, co nas ³¹czy. Nie jesteœmy padlino¿ercami tak jak ty. Jesteœmy rasowymi ¿o³nierzami Mistrza! Ja i inni. Pamiêtaj o tym, mieszañcu.}
{219}{}{Tak, dobrze. Zapamiêtam to.}
{220}{}{Kucha? Nie s¹dzi³em, ¿e jesteœ z nimi.}
{221}{}{Tak, postanowiliœmy po³¹czyæ si³y. To Ÿle?}
{222}{}{Normalni i Mroczni razem – nigdy o tym nie s³ysza³em. Ale jeœli Kucha jest z tob¹, nie bêdê siê wtr¹caæ.}
{223}{}{To dobrze.}