{100}{}{Widzisz ghula marudera.}
{101}{}{Widzisz przed sob¹ ghula. Dok³adnie sprawdza teren.}
{102}{}{Hej, kolego, masz ognia? Wokó³ pe³no œmieci, ale ¿adnego ognia...}
{1102}{}{Hej dziewczyno, masz ognia? Wokó³ pe³no œmieci, ale ¿adnego ognia...}
{103}{}{Ogieñ! Och!}
{104}{}{Byæ mo¿e wystarczy Ci jedna zapalniczka.}

{200}{}{P³omienie spad³y z nieba! Widzisz to? Wszystko wokó³ p³onie. Wszystko! Nawet ska³y p³on¹!}
{201}{}{Masz urojenia. ObudŸ siê!}
{202}{}{Zwariowa³em? Nie? Nie. P³omieñ Wielkiej Wojny wci¹¿ p³onie. P³onie w moim sercu. I za ka¿dym razem, gdy o nim wspominam, gdy widzê najmniejsz¹ iskrê. Nie mo¿na o tym zapomnieæ. Dlatego chcê jeszcze raz... przypomnieæ sobie... Spójrz, p³onie! Jak piêknie p³onie!}
{203}{}{Tak, widzê, ¿e masz do tego s³aboœæ. Chcesz podzieliæ siê paliwem z innymi?}
{204}{}{Ogieñ jest naprawdê hipnotyzuj¹cy.}
{205}{}{Czy ty te¿ lubisz OGIEN? Tak, P³omieñ Wielkiej Wojny jeszcze nie wygas³. P³onie w moim sercu. I za ka¿dym razem, gdy o nim wspominam, gdy widzê najmniejsz¹ iskrê. Nie mo¿na o tym zapomnieæ. Wiêc chcê jeszcze raz... przypomnieæ sobie... Spójrz, p³onie! Jak piêknie p³onie!}
{206}{}{Teraz stworzê swój w³asny p³omieñ!}
{207}{}{No pewnie.}
{208}{}{W³aœciwie to chcê tylko rozpaliæ ogieñ. Masz jakieœ paliwo?}
{209}{}{Byæ mo¿e odsunê siê, podczas gdy ty bêdziesz bawiæ siê ogniem. Do widzenia.}
{210}{}{Lubisz patrzeæ na p³omienie?}
{211}{}{Zdecydowanie potrzebujesz ognia. Ka¿dy go potrzebuje.}
{212}{}{Ogieñ oczyszcza. Zabiera wszystko, co posiadasz. Tworzy pustkê. Czy to nie niesamowite?}
{213}{}{Czy ci siê to podoba, czy nie, wezmê ca³e twoje paliwo.}