{100}{}{Widzisz Ruperta.}
{101}{}{Widzisz ghula w przedwojennym garniturze.}
{102}{}{Widzisz ghula.}
{103}{}{Gdyby nie DeSanti, ju¿ dawno bylibyœmy razem.}
{104}{}{Hej, czeœæ. Dobrze wygl¹dasz jak na ghula.}
{105}{}{Uch! Nie mogê siê przyzwyczaiæ do tych brzydkich, g³adkich twarzy.}
{106}{}{Uch!}
{107}{}{Wiesz, jak zepsuæ zabawê.}

{200}{}{Hej, czeœæ. Dobrze wygl¹dasz jak na ghula.}
{201}{}{Nie jestem ghulem.}
{202}{}{No to masz szczêœcie. Ja te¿ mam szczêœcie. Za ka¿dym razem coraz wiêcej!}
{203}{}{No có¿, to...}
{204}{}{Och, gdybym tylko zawsze mia³ tyle szczêœcia! Myœla³em, ¿e moja staroœæ bêdzie bardzo smutna, a tu czujê siê m³odo jak nigdy dot¹d! I to jest œwietna zabawa!}
{205}{}{W³aœciwie...}
{206}{}{Cieszê siê...}
{207}{}{A teraz przepraszam, tatuœ potrzebuje nowej pary butów. Och, tak! Stawiam na czerwony!}
{208}{}{Nie bêdê siê wtr¹caæ.}
{209}{}{Uwa¿aj, staruszku, nie przegraj duszy.}

{220}{}{Przestañ be³kotaæ, mam kartê!}
{221}{}{Nie zwracaj uwagi.}
{222}{}{Powiedz mi, staruszku, jak masz na imiê?}
{223}{}{Nazywam siê najszczêœliwszy sukinsyn na œwiecie!}
{224}{}{Mówiê powa¿nie.}
{225}{}{S³uchaj, nie b¹dŸ taki nudny. Nadal nie zamierzam siê z tob¹ przyjaŸniæ. Nazwij mnie starym, jeœli chcesz. Nie obchodzi mnie to.}
{226}{}{OK. Jak mówisz, stary.}
{227}{}{Masz na imiê Rupert, prawda?}
{228}{}{Khe-khe-khe! Nie wiem o czym mówisz. Pierwszy raz s³yszê to imiê.}
{229}{}{Mo¿e powinienem zapytaæ administratora? Albo zajrzeæ do rejestru goœci?}
{230}{}{Naprawdê? Có¿, w takim razie przepraszam, ¿e ciê niepokojê.}
{231}{}{Czego ty w ogóle chcesz? Kto Ciê przys³a³?}
{232}{}{Pani Judy. Poszukuje swojego zaginionego mê¿a. I wygl¹da na to, ¿e przegrywa on ca³¹ swoj¹ fortunê.}
{233}{}{(wzdycha) S³uchaj, kolego. Myœlisz, ¿e spêdza³bym tu czas, gdybym chcia³ ponownie po³¹czyæ siê z Judy?}
{234}{}{Trochê mnie to nie obchodzi.}
{235}{}{Wiêc jaki masz powód ku takiemu zachowaniu?}
{236}{}{Jesteœ mê¿czyzn¹, powinieneœ zrozumieæ, jak to jest, gdy twoja ¿ona ma ciê na oku przez 80 lat z rzêdu!}
{1236}{}{Jesteœ kobiet¹, nie rozumiesz, jak to jest, gdy twoja ¿ona ma ciê na oku przez 80 lat z rzêdu!}
{237}{}{[S³uchaj]}
{238}{}{Czujê siê tu dobrze. Robiê co chcê - pijê, ogl¹dam filmy, gram w ruletkê! Wiesz, Judy nigdy nie pozwala³a mi graæ w tê cholern¹ ruletkê. A ja zawsze chcia³em.}
{239}{}{Wiesz, ¿e to nie jest prawdziwa gra, prawda?}
{240}{}{No có¿, tak. Ale to nie ma znaczenia – liczy siê to, ¿e w koñcu zacz¹³em w to graæ!}
{241}{}{Nie bêdzie zbyt szczêœliwa, jeœli dowie siê, ¿e ukrywa³eœ siê przed ni¹, kiedy ciê szuka³a.}
{242}{}{Wiem. S³uchaj, powiedz jej, ¿e nie ¿yjê, co? Dla ciebie to nic, ale ja bêdê móg³ jeszcze trochê po¿yæ bez jej ca³kowitego nadzoru.}
{243}{}{OK. Dlaczego nie?}
{244}{}{Naprawdê to zrobisz? Och, mam dzisiaj mnóstwo szczêœcia! SZCZESCIA!}
{245}{}{OK, ok.}
{246}{}{Nie. Musisz j¹ zobaczyæ. Przecie¿ to twoja najbli¿sza osoba. Niew³aœciwie jest ukrywaæ siê przed ni¹ do koñca ¿ycia.}
{247}{}{Musisz mi psuæ zabawê? (wzdycha) OK. Masz racjê. Pewnie i tak dowiedzia³aby siê od ciebie prawdy.}
{248}{}{Tak. IdŸ i porozmawiaj z ni¹. Mieszka w San Ysidro.}

{250}{}{Zgodnie z twoj¹ proœb¹, powiedzia³em jej, ¿e nie ¿yjesz. I wiesz co siê sta³o? Jej serce nie wytrzyma³o i pêk³o!}
{1250}{}{Zgodnie z twoj¹ proœb¹, powiedzia³am jej, ¿e nie ¿yjesz. I wiesz co siê sta³o? Jej serce nie wytrzyma³o i pêk³o!}
{251}{}{Jak... nie mo¿e byæ... Nie spodziewa³em siê tego... Och... ugh...}
{252}{}{Nie mów mi, ¿e ty te¿...}
