{100}{}{Widzisz Judy.}
{101}{}{Widzisz przed sob¹ ghula w przedwojennym stroju.}
{102}{}{Ach!}
{103}{}{Teraz wiem, co Rupert robi³ przez ca³y ten czas. Ale... tym razem mu wybaczê.}

{200}{}{Witaj nieznajomy. W Blasku pojawia siê coraz wiêcej nowych twarzy.}
{1200}{}{Witaj nieznajoma. W Blasku pojawia siê coraz wiêcej nowych twarzy.}
{201}{}{Zgadza siê. Do widzenia.}
{202}{}{Kim jesteœ?}
{203}{}{Nazywam siê Babcia Judy. Przyby³am z Nekropolis jak reszta ghuli.}
{204}{}{Rozumiem. Czeœæ, babciu.}
{205}{}{Co tu robisz, Judy?}
{206}{}{Ka¿dego dnia odwiedzam Gustavo, aby zapytaæ o nowo przyby³ych lub zmar³ych. W koñcu to prawdziwy ratusz. Jeœli mam gdzieœ szukaæ ludzi, to w³aœnie tutaj.}
{207}{}{Co myœlisz o Gustavo?}
{208}{}{Och, to taka s³odka m³oda mewa! Bardziej troszczy siê o swoich ni¿ o siebie. Nigdy nie mieliœmy ich doœæ.}
{209}{}{Kogo szukasz?}
{210}{}{Mój m¹¿ Rupert i ja rozdzieliliœmy siê podczas podró¿y. Teraz nie mogê go znaleŸæ. Chocia¿ Cabbot na Starym Mieœcie twierdzi, ¿e go widzia³.}
{211}{}{Przykro mi to s³yszeæ. Do widzenia.}
{212}{}{Pomogê ci go znaleŸæ.}
{213}{}{Jesteœ taki s³odki! Przyjmê ka¿d¹ pomoc.}
{1213}{}{Jesteœ taka s³odka! Przyjmê ka¿d¹ pomoc.}
{214}{}{W takim razie zacznê od Starego Miasta. Zegnaj, Judy.}
{215}{}{Powiedz mi jeszcze raz, kiedy ostatni raz widzia³aœ swojego mê¿a?}
{216}{}{Mam na imiê Judy. Mo¿esz do mnie mówiæ babciu, kochanie. Przyby³am z Nekropolis jak reszta ghuli.}
{217}{}{B¹dŸ silna, babciu. Twój m¹¿ Rupert zgin¹³ w walce w Dzielnicy W³oskiej.}
{218}{}{Ach! Nie! (³apie siê za serce) Och!}
{219}{}{Hej, jesteœ chora?}

{220}{}{Witaj nieznajomy.}
{1220}{}{Witaj nieznajoma.}
{221}{}{Czeœæ, babciu.}