{200}{}{Witaj }
{1200}{}{Witaj }
{201}{}{! Nie bój siê, ten robot s³u¿y jako pos³aniec. Przynosi ci wa¿n¹ wiadomoœæ.}
{202}{}{Co to za wiadomoœæ?}
{203}{}{"Drogi amigo, wiem o twoich wyczynach na pustyni Sonora. Niezale¿nie od celu i kierunku, twoje doœwiadczenie jest bezcenne."}
{204}{}{[S³uchaj]}
{205}{}{"W ruinach San Diego tworzy siê teraz historia. Powinieneœ tam byæ. Miejscowe ghule nie ufaj¹ ludziom. Sa podzielone i s³abe. Dlatego mog¹ pope³niæ du¿y b³¹d. Potrzebuj¹ bohatera."}
{206}{}{[S³uchaj]}
{207}{}{"Karawana z miasta ghuli zatrzyma siê na obrze¿ach Inferno. Otrzymasz specjalne pozwolenie na swobodne zwiedzanie ruin wokó³ Starego Miasta."}
{208}{}{[S³uchaj]}
{209}{}{"Kiedy bêdziesz na Starym Mieœcie, zatrzymaj siê w sklepie ze œmieciami i zdob¹dŸ zaszyfrowan¹ holotaœmê ze wskazówkami. Liczê na twoj¹ pomoc i... powodzenia."}
{210}{}{[Odtwórz nagranie ponownie]}
{211}{}{[Zakoñcz nagranie]}
{212}{}{Oho???}