{100}{}{Widzisz ghula marudera.}
{101}{}{Widzisz ghula. Przygl¹da siê uwa¿nie niektórym przedmiotom.}

{200}{}{Hej, stój, trzymaj siê z daleka! To s¹ moje rzeczy, znalaz³em je pierwszy!}
{201}{}{By³y twoje, bêd¹ moje.}
{202}{}{OK, cokolwiek powiesz. To twoje rzeczy.}
{203}{}{Hmm, rzadko widuje siê tu normalnych ludzi... To znaczy, obecnie jest to rzadkoœæ. Kiedyœ tymi ulicami chodzi³y ca³e t³umy. Dooko³a wci¹¿ wystaj¹ koœci z piasku.}
{204}{}{Co tu robisz?}
{205}{}{Przeszukujê te ruiny w poszukiwaniu kosztownoœci. Wczeœniej Poszukiwacze rzadko tu zagl¹dali ze wzglêdu na roboty Stra¿y Granicznej. Ale ktoœ wyœwiadczy³ nam wielk¹ przys³ugê wy³¹czaj¹ac je.}
{206}{}{W takim razie powodzenia. Do widzenia.}
{207}{}{Znalaz³eœ ju¿ coœ wartosciowego?}
{208}{}{Tak, spójrz tutaj...}
{209}{}{[Handel]}
{210}{}{Witam. Potrzebujesz czegoœ z ruin? Mogê poszukaæ. Oddam prawie jak prezent. Dam ci te¿ zni¿kê.}
{211}{}{Nie dzisiaj, senor.}
{212}{}{Poka¿ mi, co masz...}
{213}{}{Wróæ jeszcze. Mo¿e za kilka dni znajdê coœ innego, przydatnego.}
{214}{}{Do widzenia.}
{215}{}{Hej, wyœwiadcz mi przys³ugê i nie dotykaj moich rzeczy. Jasne? Ja je znalaz³em!}
{216}{}{Hmm, wiêc nie jestem teraz sam w tych ruinach... Kiedyœ tymi ulicami spacerowa³y t³umy ludzi. Dooko³a wci¹¿ wystaj¹ koœci z piasku.}