{100}{}{Widzisz najemnika.}
{101}{}{Widzisz jednego z tych Czarnych Poszukiwaczy, którzy wykonaj¹ ka¿d¹ pracê, aby zarobiæ na ¿ycie.}

{110}{}{Pan DeSanti dobrze zap³aci za twoj¹ g³owê.}
{111}{}{Nie powinieneœ by³ obra¿aæ pana DeSanti!}
{112}{}{Ten, kto wystêpuje przeciwko DeSantiemu, nie ¿yje d³ugo.}
{113}{}{Pan DeSanti jest z ciebie bardzo niezadowolony!}
{114}{}{Nic osobistego. Po prostu ktoœ mi kaza³.}
