{100}{}{Widzisz Supermutanta.}
{101}{}{Widzisz supermutanta w sprzêcie bojowym.}
{102}{}{My, Mroczni, pozostaniemy wierni Mistrzowi i jego idea³om. Nawet jeœli normalni zostawi¹ nas w spokoju.}

{200}{}{Hej, stary, schowaj broñ. Nie tkniemy ciê, dopóki nas nie zaatakujesz.}
{201}{}{Hej, kolego, nie martw siê. Nie zrobimy ci krzywdy, jeœli nas nie zaatakujesz.}
{202}{}{Sk¹d taka ¿yczliwoœæ?}
{203}{}{Dlaczego mia³bym ci zaufaæ?}
{204}{}{Jesteœmy po prostu zmêczeni wojn¹. Niech ludzie przestan¹ nas przeœladowaæ! Tylko o to prosimy.}
{205}{}{Rozumiem. No có¿, do widzenia.}
{206}{}{Nie gap siê, stary. Nie lubiê, kiedy siê na mnie gapi¹.}
{207}{}{Dobra.}
{208}{}{}
{209}{}{}

{210}{}{Powiedz mi, czy to prawda, ¿e wyrzuci³eœ Kuchê ze swojego oddzia³u?}
{211}{}{Kucha? Nawet nie chcemy o nim s³yszeæ. Zdrajca! Straci³ lojalnoœæ wobec dru¿yny. Nie ma usprawiedliwienia.}
{212}{}{Chce siê odkupiæ.}
{213}{}{Nie wierzê w to. G³upiec. Nie nadaje siê nawet do noszenia karabinu maszynowego. Szkoda, ¿e kapitana nie ma z nami, ¿eby go ponownie ukaraæ...}
{214}{}{Co siê sta³o z kapitanem?}
{215}{}{Wziêty do niewoli przez ludzi z Bractwa Stali. Obecnie jest torturowany w centrum patrolowym w poblizu San Ysidro.}
{216}{}{Wiêc dlaczego tu stoisz, zamiast go ratowaæ?}
{217}{}{To pu³apka, ty g³upi cz³owieku! Zolnierze Bractwa chc¹ nas wszystkich z³apaæ. Sam kapitan na koniec powiedzia³: nie ratujcie mnie.}
{218}{}{Wy g³upcy! Na waszym miejscu zrobi³bym wszystko, ¿eby wydostaæ kapitana. ChodŸmy, Kucha, z dala od tych frajerów.}
{1218}{}{Wy g³upcy! Na waszym miejscu zrobi³abym wszystko, ¿eby wydostaæ kapitana. ChodŸmy, Kucha, z dala od tych frajerów.}
{219}{}{Rozumiem. Rozkaz to rozkaz. ChodŸ, Kucha, musimy porozmawiaæ twarz¹ w twarz.}
{220}{}{Wy g³upcy! Na waszym miejscu zrobi³bym wszystko, ¿eby wydostaæ kapitana. Narazie, frajerzy.}
{1220}{}{Wy g³upcy! Na waszym miejscu zrobi³abym wszystko, ¿eby wydostaæ kapitana. Narazie, frajerzy.}
{221}{}{Rozumiem. Rozkaz to rozkaz.}
{222}{}{Twój kapitan nie ¿yje. Nie uda³o mi siê go uratowaæ z r¹k Bractwa Stali.}
{223}{}{Tego mo¿na by³o siê spodziewaæ.}
{224}{}{Co zrobisz bez kapitana?}
{225}{}{To wszystko? Zadnych gniewnych przemówieñ i gard³owych ryków? Czy ty w ogóle wiesz, jak przetrwaæ bez kapitana?}
{226}{}{Wasz kapitan zosta³ uratowany. Nie dziêkujcie.}
{227}{}{Nie poproszono ciê o to, a ty i tak pomagasz Mrocznym. Naprawdê myœlisz, ¿e w ten sposób mo¿na pogodziæ ludzi i mutantów? To niemo¿liwe. Ale i tak jesteœmy ci wdziêczni. Szkoda, ¿e nie mogê pokazaæ ciê Mistrzowi.}
{228}{}{Co teraz zrobisz?}
{229}{}{Masz jakieœ dalsze plany? A mo¿e po prostu zostaniesz w œrodku p³on¹cego parku?}
{230}{}{Chcemy jechaæ na wschód. Gdzie o nas nie wiedz¹. Trzymaæ siê z daleka od Bractwa i reszty Kalifornii.}
{231}{}{Co ciê przed tym powstrzymuje, teraz, gdy kapitan jest z tob¹?}
{232}{}{Co ciê przed tym powstrzymuje, skoro kapitana ju¿ nie ma?}
{233}{}{No to powodzenia w podró¿y.}
{234}{}{Zgadza siê. Nic, co mog³oby zepsuæ nastrój normalnym ludziom. Mam nadziejê, ¿e tam bêdzie lepiej.}
{235}{}{A co z Kuch¹? Zabierzesz go ze sob¹?}
{236}{}{Jeœli chce, niech wróci do dru¿yny.}
{237}{}{Dobrze.}
