{100}{}{Widzisz Dowódcê Mrocznych.}
{101}{}{Widzisz mrocznego supermutant.}
{102}{}{Nie podziêkujê ci. Ale zas³ugujesz na szacunek. Do zobaczenia póŸniej, dziwna istoto.}
{103}{}{Kucha taki szczêœliwy! Taki szczêœliwy!}

{200}{}{Zostaw mnie w spokoju, cz³owieku! Czekaj... nie jesteœ z Bractwa?}
{201}{}{S³uchaj, nie ma czasu na wyjaœnienia, ale chcê ciê uwolniæ. Po prostu pod¹¿aj za mn¹ i nie pokazuj siê paladynom.}
{202}{}{SiedŸ spokojnie, wielkoludzie, dopóki nie dam ci sygna³u.}
{203}{}{Co? Dziwne. Widzia³em wszystko, ale coœ takiego widzê po raz pierwszy.}
{204}{}{Nie mam pojêcia, o co ci chodzi, stary. Ale nie próbuj mnie oszukaæ.}
{205}{}{Porozmawiamy, kiedy bêdziemy bezpieczni. ChodŸmy.}
{206}{}{Znów jesteœ wolny.}
{207}{}{Wyjaœnij mi, co to do cholery ma znaczyæ? Dlaczego pomagasz Mrocznym? Kto Ciê przys³a³?}
{208}{}{Kucha. Chcia³ pomóc swojemu oddzia³owi i odkupiæ winê.}
{209}{}{Kucha? Hoho, widaæ nawet taki wojownik jak on mo¿e czasami uratowaæ ¿ycie. Jestem serio zaskoczony. Teraz rozumiem. Kucha widzia³ w Tobie silnego dowódcê. Nie przeszkadza mi to. Niech Kucha sam wybierze, z kim chce zostaæ – z tob¹ czy z nami. Ja tymczasem wracam do obozu. Do zobaczenia, dziwna istoto.}
{210}{}{Ok, do zobaczenia wkrótce.}