{100}{}{Widzisz paladyna.}
{101}{}{Widzisz paladyna Bractwa Stali.}
{102}{}{Witam, bracie.}
{1102}{}{Witam, siostro.}

{110}{}{Co tu siê do cholery dzieje?}
{111}{}{Cholerny alarm!}
{112}{}{Co to za ha³as do cholery?}
{113}{}{Hmm, dziwne.}
{114}{}{He? Fa³szywy alarm?}
{115}{}{Pieprzony alarm!}

{120}{}{Cholerna technologia!}
{121}{}{Przestañ ju¿ dzwoniæ!}
{122}{}{Jak mogê to wy³¹czyæ?}
{123}{}{Szkoda, ¿e w pobli¿u nie ma rycerzy...}
{124}{}{Jak to dzia³a?}
{125}{}{Latwiej to zdetonowaæ ni¿ wy³¹czyæ, na Boga!}

{130}{}{Dziwne. Dlaczego to zadzia³a³o?}
{131}{}{Wreszcie, syrena ju¿ nie zadzwoni.}
{132}{}{Jestem zaskoczony, ¿e alarm nadal dzia³a.}
{133}{}{Myœlê, ¿e ju¿ to na pewno wy³¹czy³em.}

{200}{}{Stój! To miejsce jest zastrze¿one. Musisz odejœæ. Natychmiast.}
{201}{}{Dobrze, dobrze, ju¿ odchodzê.}
{202}{}{Spróbuj tylko mnie ruszyæ, g³upku!}
{203}{}{Ja te¿ jestem z Bractwa Stali. Skryba }
{204}{}{Ja te¿ jestem z Bractwa Stali. Rycerz }
{205}{}{Ja te¿ jestem z Bractwa Stali. Paladyn }
{206}{}{Ja te¿ jestem z Bractwa Stali. Zwiadowca }
{207}{}{. Oddzia³ Sonora.}
{208}{}{Mi³o ciê poznaæ, bracie. W takim razie jesteœ tutaj pod nasz¹ ochron¹.}
{1208}{}{Mi³o ciê poznaæ, siostro. W takim razie jesteœ tutaj pod nasz¹ ochron¹.}
{209}{}{Czy mogê zapytaæ, co tu robisz?}
{210}{}{Mamy ma³¹ misjê. Schwytaliœmy kapitana supermutantów i teraz go przes³uchujemy. A kiedy skonczymy, zabijemy go. Nie ma siê czym martwiæ, jest dobrze strze¿ony.}
{211}{}{Och, to wspaniale. Gratulacje.}
{212}{}{Przestañ! Jeszcze raz ostrzegam – nie mo¿esz tu przebywaæ. OdejdŸ. Natychmiast.}
{213}{}{Nie denerwuj mnie. To ostatnie ostrze¿enie. TY. TUTAJ. NIE MASZ WSTEPU.}
{214}{}{Doœæ! Takich kretynów jak ty nie da siê uratowaæ. Czeka Ciê kara!}
{215}{}{Och, to bêdzie bola³o...}
{216}{}{Jasne, ju¿ sobie to wyobra¿am!}
{217}{}{Wiem, kogo tu trzymasz. I wiem, gdzie jest jego oddzia³.}
{218}{}{Wiêc powiedz mi! Ka¿da informacja bêdzie dla nas cenna.}
{219}{}{Oddzia³ rozbi³ obóz w Balboa Park.}
{220}{}{Z supermutantami prowadzimy krótki dialog. Sa z³em, które nale¿y wykorzeniæ. Dziêki za informacje. Doceniamy twoj¹ pomoc.}
{221}{}{Proszê bardzo.}
{222}{}{Co zrobisz z tymi supermutantami?}
{223}{}{Z supermutantami prowadzimy krótki dialog. Sa z³em, które nale¿y wykorzeniæ. No to gdzie one s¹?}
{224}{}{Co? Cholerni fanatycy! Nie pozwolê wam zabijaæ supermutantów!}
{225}{}{Wkrótce wyœlemy tam oddzia³, który zajmie siê tym zielonym zagro¿eniem. Dziêki za informacje. Doceniamy twoj¹ pomoc.}
