{100}{}{Widzisz Rycerza Jerrego.}
{101}{}{Widzisz przed sob¹ Rycerza Bractwa Stali. Wygl¹da na nieŸle poturbowanego.}

{200}{}{Cicho! Przy wejœciu czai³ siê mutant. Zabije nas, jeœli nas zobaczy. Poza tym jestem ranny i nie mogê walczyæ. Jesteœ moj¹ ostatni¹ nadziej¹.}
{201}{}{Mutant znikn¹³? Dziêkujê, bracie! A teraz muszê opatrzyæ rany. Masz mo¿e apteczkê?}
{1201}{}{Mutant znikn¹³? Dziêki siostro! A teraz muszê opatrzyæ rany. Masz mo¿e apteczkê?}
{202}{}{Mutant nie ¿yje? Dziêkujê, bracie! A teraz muszê opatrzyæ rany. Masz mo¿e apteczkê?}
{1202}{}{Mutant nie ¿yje? Dziêki siostro! A teraz muszê opatrzyæ rany. Masz mo¿e apteczkê?}
{203}{}{Robiê, co mogê. Przestañ mi tu marudziæ!}
{204}{}{Zrobiê co w mojej mocy.}
{205}{}{Dziêkujê za pomoc. Teraz mogê walczyæ jak przedtem. Nie mam jednak za du¿o amunicji. Gdzie jest ten mutant? Pewnie czeka przy wejœciu.}
{206}{}{Rozwalmy go!}
{207}{}{Lepiej trzymaj g³owê nisko, ¿eby stare rany siê nie otworzy³y. Zostañ tu, dopóki siê z nim nie rozprawiê.}
{208}{}{Niebezpieczeñstwo minê³o. Tego brutala ju¿ nie ma.}
{209}{}{Ten brutal ju¿ nikogo nie skrzywdzi. Mo¿emy wyjœæ z ukrycia.}
{210}{}{O nie! Tutaj jest! Ostro¿nie!}
{211}{}{Nie strzelaj! To jest Kucha, mój partner.}
{212}{}{Co... Doceniam ratunek, ale to ju¿ za du¿o! Mutanty s¹ z³e! Zniszczy³y ca³e osady ludzkie. Co do cholery ten drañ z tob¹ robi?}
{213}{}{On jest nieszkodliwy. Nie powinieneœ nienawidziæ wszystkich mutantów z powodu z³ego postêpowania jednej konkretnej grupy.}
{214}{}{Ja te¿ nie wiem, po co mi to potrzebne. Ale mnie chroni i nosi ró¿ne rzeczy. Po prostu go nie dotykaj, dobrze?}
{215}{}{Kim jesteœ? Wiesz, zna³em jednego mieszkañca Krypty. Próbowa³ pomóc swoim braciom i siostrom. A kiedy pomóg³, zosta³ po prostu wyrzucony. Dobroæ bez broni pod rêk¹ zawsze koñczy siê czymœ smutnym.}
{1215}{}{Kim jesteœ? Wiesz, zna³em jednego mieszkañca Krypty. Próbowa³ pomóc swoim braciom i siostrom. A kiedy pomóg³, zosta³ po prostu wyrzucony. Dobroæ bez broni pod rêk¹ zawsze koñczy siê czymœ smutnym.}
{216}{}{Mo¿e i tak.}
{217}{}{Kto to wie?}
{218}{}{Och, szeœæ lat temu bylibyœmy jak ty na pierwszej linii frontu – ilu braci mo¿na by³o uratowaæ przed supermutantami!}
{219}{}{Ja w tym czasie pracowa³em na plantacjach i nie wiedzia³em o ¿adnej wojnie z supermutantami. Dlatego kocham ¿ycie na wsi.}
{220}{}{Wystarczaj¹co, ¿eby ciê uratowaæ.}
{221}{}{OK, teraz muszê iœæ dalej. Dziêkujê, bracie.}
{222}{}{Nawiasem mówi¹c, co tu robi Bractwo?}
{223}{}{Kiedy starsi dowiedzieli siê, ¿e mutanci poœpieszyli do San Diego, przydzielono mnie z oddzia³em do zwiadu. Nawet nie przypuszcza³em, ¿e takie piek³o jak tu w ogóle istnieje. Promieniowanie, potwory, supermutanty, ghule, roboty – czego tu nie ma! Muszê powiedzieæ o tym dowódcy. Nie mo¿na pozwoliæ, ¿eby zwykli ludzie te¿ tu przychodzili.}
{224}{}{Rozumiem. No có¿, udanej podró¿y. Nie daj siê ponownie z³apaæ mutantom.}
{225}{}{Jeszcze raz dziêkujê.}
