{102}{}{Co jeszcze?}
{103}{}{Zabijê ka¿dego z Bractwa Stali, kogo znajdê!}
{104}{}{Nienawidzê Bractwa! Nienawidzê go!}

{110}{}{Hej, psie, rzuæ broñ i wyjdŸ!}
{111}{}{Nie zrobiê ci krzywdy. Chcê tylko porozmawiaæ.}
{112}{}{Powiedz wszystko, co masz do powiedzenia.}
{113}{}{Wiesz, ilu z nas zosta³o zabitych przez psy z Lost Hills?}
{114}{}{Zabraliœcie nam nasz dom. Odebraliœcie nam naszego boga.}
{115}{}{Myœlisz, ¿e po tym mo¿emy siê dogadaæ?}
{116}{}{Och, jestem TAK wœciek³y. Ale wyœwiadczê ci przys³ugê - zabijê ciê szybko. Nic nie poczujesz.}
{117}{}{Zgadzasz siê?}
{118}{}{Dlaczego cierpisz? Dlaczego siê opierasz? Wybawiê ciê z twojego nieszczêœcia.}
{119}{}{Za nami by³ Bóg. A za tob¹ s¹ tylko jacyœ genera³owie. Za³oœni mali ludzie, jak nisko upadliœcie!}

{200}{}{Hej, ghulu, b¹dŸ ostro¿ny. Gdzieœ tam jest pies Bractwa Stali. Uwa¿aj, ¿eby nie daæ siê trafiæ jego kulom.}
{201}{}{Och, rozumiem. W takim razie poœpieszê siê, zanim zrobi siê tu gor¹co.}
{202}{}{Nie wa¿ siê atakowaæ Bractwa! Nie pozwolê ci na to!}
{203}{}{Hej, w³aœnie widzia³em, jak ucieka³ na molo! Niepotrzebnie tu czekasz, ju¿ go tu nie ma.}
{204}{}{Co... Wow, zaraz go dogoniê! Nie ucieknie!}
{205}{}{Poœpiesz siê, wielkoludzie!}
{206}{}{Ha ha, ty g³upku! Latwiej ciê oszukaæ ni¿ dziecko! Co ty na to?}
{207}{}{Kucha? Co tu robisz? Hej, wzi¹³eœ cz³owieka jako niewolnika? Dobrze. A ja tu próbujê wyci¹gn¹æ psa z Bractwa Stali. Ukry³ siê w kawiarni. Mo¿esz mi pomóc sobie z nim poradziæ?}
{208}{}{Kucha, uciekajmy st¹d. To nie nasza sprawa.}
{209}{}{Kucha, powiedz mu, ¿e wojna siê skoñczy³a. Przestañ walczyæ. Zostaw tê osobê w spokoju.}
{210}{}{Kucha i cz³owiek partnerami? Nie s³ysza³em o czymœ takim. Mo¿e rzeczywiœcie dosz³o do rozejmu? OK, Kucha, wierzê ci.}
{211}{}{To dobrze. IdŸ swoj¹ drog¹.}
{212}{}{Ach! WeŸ swój ostatni oddech, g³upi ludzie!}
{213}{}{Nie przed tob¹, œmierdzielu!}
{214}{}{Czekaj, porozmawiajmy!}
{215}{}{Czekaj! Ty i ja nie mamy po co walczyæ. Nie chcê ciê skrzywdziæ.}
{216}{}{Nigdy nie wybaczê tego, co ludzie nam zrobili!}
{217}{}{Przykro mi, ale rozumiesz...}
{218}{}{Nie powinieneœ...}
{219}{}{Ghulom siê to nie spodoba. W koñcu buduj¹ miasto dla wszystkich. Ludzie i mutanci mog¹ ¿yæ razem w Blasku Dnia. Nie chcesz d³ugo oczekiwanego pokoju?}
{220}{}{Ghule s¹ nieostro¿ne! Kiedyœ zap³ac¹. Ludzie ich zdradz¹!}
{221}{}{Zaopiekuj siê nimi. Nie pozwól ludziom sterowaæ upiorami. W koñcu ludzi zawsze bêdzie wiêcej. Sama walka tego nie zmieni.}
{222}{}{Brzmi nieŸle. Nie myœla³em o tym. Iœæ do miasta i co? Zaoferowaæ siê jako stra¿nik? Hmm... To dobry pomys³! Nie pozwolê, ¿eby ghulom sta³a siê krzywda, nie, nie!}
{223}{}{To dobrze. Widzisz? Zawsze mo¿na siê dogadaæ.}
{224}{}{Muszê siê z tob¹ zgodziæ w tej kwestii. No to walczymy dalej, g³upku?}
