{200}{}{Waaaah, dawno nie spa³am tak dobrze.}
{201}{}{Co tu robisz?}
{202}{}{Co ty do cholery robisz w lodówce? Myœla³em, ¿e ktoœ ukry³ tu zw³oki!}
{1202}{}{Co ty do cholery robisz w lodówce? Myœla³am, ¿e ktoœ ukry³ tu zw³oki!}
{203}{}{Ukry³am siê przed mutantami, a potem zasnê³am. Ile czasu minê³o? Prawdopodobnie tylko kilka tygodni. OK, idê spaæ na mieœcie.}
{204}{}{Nienormalna.}
{205}{}{Trzymaj siê, dziwna istoto.}
{206}{}{Chcê spaæ...}