{100}{}{Widzisz ghula.}
{101}{}{Widzisz zwyk³ego ghul.}

{200}{}{Hej synu, chcesz ¿eby ci opowiedzieæ inspiruj¹c¹ historiê?}
{1200}{}{Hej, proszê pani, czy chcia³aby pani us³yszeæ inspiruj¹c¹ historiê?}
{201}{}{Pewnie chcesz, Ale nie za darmo, nie?}
{1201}{}{Pewnie chcesz. Ale nie za darmo, nie?}
{202}{}{Nie, có¿, jeœli chcesz coœ us³yszeæ, opowiem ci, ale przy szklance piwa.}
{1202}{}{Nie, có¿, jeœli chcesz coœ us³yszeæ, opowiem ci, ale przy szklance piwa.}

{210}{}{Mieszka³em w kana³ach po tym, jak spad³y bomby. Zywi³em siê wod¹ z ka³u¿ i szczurami. Nie powinienem by³ tego robiæ.}
{211}{}{Set by³ naszym przywódc¹. Trzyma³ wszystkie ghule ¿elazn¹ piêœci¹. Na szczêœcie nie ma go ju¿ z nami.}
{212}{}{Tu¿ przed Wielk¹ Wojn¹ na planecie zabrak³o ropy. I tu pojawia siê zasadnicze pytanie – o co walczyli w czasie wojny?}
{213}{}{Na pó³nocy znajduje siê kilka wiêkszych osad. Ale to nic w porównaniu z tym, jak wygl¹da³y miasta przed wojn¹.}
{214}{}{Mistrz i jego supermutanci stanowili powa¿n¹ si³ê. Próbowali zmia¿d¿yæ ludzi i ghule. Dobrze, ¿e ich zniszczono. Ale nie do koñca!}
{215}{}{Ugh... chyba za du¿o wypi³em... koniec rozmowy...}
