{100}{}{Widzisz ghula.}
{101}{}{Widzisz ghula w zbroi bojowej i he³mie.}

{200}{}{John mówi³ o tobie. Powiedzia³, ¿e jesteœ m¹drym dzieciakiem. Ale jak zamierzasz szturmowaæ wyspê z tak¹ ³adn¹, g³adk¹ twarz¹?}
{201}{}{Dobre pytanie. Muszê o tym pomyœleæ.}
{202}{}{Nie twoja sprawa, kurwa.}
{203}{}{John mówi³ o tobie. Powiedzia³, ¿e jesteœ m¹drym dzieciakiem. Mam nadziejê, ¿e rozumiesz ryzyko, które czeka na ciebie na wyspie?}
{204}{}{Dobre pytanie. Mo¿e jednak powinniœmy przygotowaæ siê do l¹dowania.}
{205}{}{Zapomnia³em ciê zapytaæ.}
{206}{}{John mówi³ o tobie, ale nie spodziewa³em siê zobaczyæ tutaj ludzi Gustavo. Co siê dzieje?}
{207}{}{Tak, brakuje mu ludzi. Gustavo bêdzie odpowiedzialny za operacje.}
{208}{}{Gustavo bêdzie zarz¹dza³ tym wszystkim. Czy to jasne?}

{210}{}{OK. Plan jest taki. Mamy transponder. Roboty nie bêd¹ atakowaæ, gdy bêdziemy w jego obszarze dzia³ania. Pozostaje zwodowaæ ³ódŸ, aby pop³yn¹æ na wyspê. A potem – zale¿y od sytuacji.}
{211}{}{Potrzebujê czasu, ¿eby siê przygotowaæ. Poczekaj chwilê.}
{212}{}{Dobrze. Jaki jest mój cel na wyspie?}

{220}{}{Czy ta baza nie jest aby zniszczona? Co mam zabraæ?}
{221}{}{Ca³a wyspa by³a usiana eksplozjami nuklearnymi. Tamtejsza ziemia jest nadal ja³owa. Ale podziemne poziomy czêœciowo przetrwa³y. To stamt¹d przychodz¹ roboty i tam je naprawiaj¹. Baza ta jest jedn¹ z najwiêkszych w przedwojennej Ameryce. Nawet po tych wszystkich eksplozjach powinno byæ wiele cennych reliktów.}
{222}{}{Musi tam panowaæ potworne promieniowanie.}
{223}{}{Zgadza siê. Dlatego mog¹ tam przebywaæ tylko ghule i roboty. Tak, to na nasz¹ korzyœæ. Ale musisz siê dobrze przygotowaæ, aby siê nie usma¿yæ.}
{224}{}{Co dotychczas powstrzymywa³o was przed wyl¹dowaniem tam?}
{225}{}{Dzia³a Wyspy Coronado. Czêœæ z nich przetrwa³a pod tarczami podczas bombardowañ. Rozci¹gaj¹ siê wzd³u¿ ca³ej linii brzegowej i nie pozwalaj¹ na zbli¿enie siê do brzegu. Sporo tam do tego betonowych fortyfikacji, gruzu w wodzie, podwodnych min i patroluj¹cych robotów. Nie mieliœmy te¿ transpondera, który niedawno zmontowaliœmy w nowej fabrycê. Swoj¹ drog¹, dobra robota.}
{226}{}{Jaki jest mój cel na wyspie?}
{227}{}{Twoim, ma³y, g³adki, jedynym celem jest wy³¹czenie systemu bezpieczeñstwa, aby roboty i dzia³a przesta³y do wszystkich strzelaæ. A potem zastanowimy siê, co i jak wywieŸæ z wyspy.}

{250}{}{Ach! Czujesz to piêkne œwie¿e powietrze?}
{251}{}{Czujê tylko zapach radioaktywnego py³u ze spalonej ziemi.}
{252}{}{No có¿, ka¿dy ma inny gust. Nie zapomnij - Twoim celem jest wy³¹czenie systemu bezpieczeñstwa. Wtedy zajmiemy siê reszt¹. Tylko niczego nie dotykaj – wci¹¿ jest tu mnóstwo niebezpiecznych zabawek, które mog¹ zamieniæ ciê w garœæ ¿aru.}
{253}{}{Rozumiem, wszystko jasne.}
{1253}{}{Rozumiem, wszystko jasne.}
{254}{}{Dobrze.}
{255}{}{Twoim celem jest wy³¹czenie systemu bezpieczeñstwa. Wtedy zajmiemy siê reszt¹. Tylko niczego nie dotykaj – wci¹¿ jest tu mnóstwo niebezpiecznych zabawek, które mog¹ zamieniæ ciê w garœæ ¿aru.}
{256}{}{System bezpieczeñstwa wy³¹czony. Baza jest teraz otwarta dla ka¿dego.}
{257}{}{Swietna robota! My zajmiemy siê reszt¹. Ty mo¿esz wróciæ na kontynent.}
{258}{}{OK.}
{259}{}{A tak przy okazji, co zamierzacie zrobiæ z lokalnymi znaleziskami?}
{260}{}{Zabierzemy je, oczywiœcie. Wszystko, co mo¿e siê przydaæ, od amunicji po elektronikê, zostanie przeznaczone na wyposa¿enie Blasku lub na sprzeda¿.}
{261}{}{Wiêc niektóre z tych niebezpiecznych zabawek trafi¹ w ludzkie rêce?}
{262}{}{Oczywiœcie. Jakiœ problem?}
{263}{}{Nie, ¿adnego.}
{264}{}{G³upcy! Te rzeczy w niew³aœciwych rêkach spowoduj¹ katastrofê! Nie pozwolê wam niczego st¹d zabraæ.}
{265}{}{Wszystko, co mo¿e siê przydaæ, od amunicji po elektronikê, zostanie przeznaczone na wyposa¿enie Blasku Dnia.}
{266}{}{Rozumiem.}
