{100}{}{Widzisz Tobiasa.}
{101}{}{Widzisz przed sob¹ ghula w mundurze i nakryciu g³owy Stra¿y Granicznej. Jego twarz jest zniekszta³cona, a spojrzenie przeszywaj¹ce.}
{104}{}{Dziêkujê. Zawsze czu³em, ¿e czegoœ tu brakuje.}
{105}{}{Tobias przypina odznakê do swojego munduru. Zauwa¿asz œlady uœmiechu na jego zniekszta³conej twarzy.}
{106}{}{Tobias ju¿ nosi tê odznakê.}

{200}{}{[Nie dasz tu rady. To miejsce tylko dla ghuli.]}
{201}{}{[OK, wychodzê]}
{202}{}{[Przejdê si³¹]}
{203}{}{[Daj mi zadanie do zaliczenia]}
{204}{}{[Zniszcz robota w Tijuanie]}
{205}{}{[OK]}
{206}{}{[Robot zneutralizowany]}

{210}{}{Cz³owieku, nie pasujesz tutaj. OdejdŸ.}
{211}{}{Nie masz prawa mnie zatrzymywaæ.}
{212}{}{(podnosi lufê) Nie przejdziesz, dopóki siê nie zgodzê.}
{213}{}{Dam sobie radê. ZejdŸ mi z drogi, dziwaku!}
{214}{}{Dobra, dobra, nie chcê tam a¿ tak bardzo iœæ...}
{215}{}{Dlaczego nie chcesz mnie wpuœciæ?}
{216}{}{W mieœcie ghuli nie ma miejsca dla ludzi. Sam nas wpêdzi³eœ w te ruiny.}
{217}{}{S³uchaj, przeby³em d³ug¹ drogê. Mo¿e moglibyœmy siê dogadaæ?}
{1217}{}{S³uchaj, przeby³am d³ug¹ drogê. Mo¿e moglibyœmy siê dogadaæ?}
{218}{}{Rozumiem, czyli mam odejœæ. Przepraszam, ¿e przeszkadzam.}
{219}{}{Hm. Móg³bym ciê przepuœciæ, jeœli wyœwiadczysz nam, ghulom przys³ugê.}
{220}{}{Jak¹ przys³ugê?}
{221}{}{Ogromny robot wojskowy przemierza ruiny Tijuany od czasów wojny. Przez niego nie mo¿emy swobodnie eksplorowaæ tego terenu. Zniszcz go, a przepuszczê ciê przez granicê.}
{222}{}{Wolê zniszczyæ ciebie. To znacznie ³atwiejsze.}
{223}{}{Zgadzam siê. Zrobiê to.}
{224}{}{Robot by³ ostatnio widziany w pobli¿u Areny. Ustawiliœmy tam nawet pu³apki elektromagnetyczne, ale bezskutecznie.}
{225}{}{Rozumiem. Bêdê o tym pamiêtaæ.}
{226}{}{Jestem po spotkaniu z robotem. Nie stanowi ju¿ dla nikogo zagro¿enia.}
{227}{}{Nie mam myœli samobójczych! Lepiej wrócê do Sonory...}
{228}{}{Nie przekroczysz granicy, dopóki ci nie pozwolê.}
{229}{}{Robot zniszczony.}
{230}{}{Musisz mieæ naprawdê dobry powód, ¿eby przyjechaæ do miasta. No dobra. Witamy w Blasku Dnia.}
{231}{}{Dziêkujê za ciep³e powitanie.}
{232}{}{Powinieneœ by³ mnie od razu przepuœciæ. Tylko marnujê z tob¹ czas.}
{233}{}{Witam, bracie. Pierwszy raz w Blasku Dnia?}
{1233}{}{Witam, siostro. Pierwszy raz w Blasku Dnia?}
{234}{}{Tak. Wpuœcisz mnie do œrodka?}
{235}{}{Oczywiœcie! Ale musisz przejœæ przez kontrolê. Takie mamy tu zasady, przykro mi.}
{236}{}{Rozumiem.}
{237}{}{Wiesz, jednak zmieni³em zdanie. Do widzenia!}
{1237}{}{Wiesz, jednak zmieni³am zdanie. Do widzenia!}
{238}{}{Dobrze. Jak masz na imiê i sk¹d pochodzisz?}
{239}{}{Jestem }
{240}{}{ z po³udniowej Arizony.}
{241}{}{Poka¿ mi plecak. Czy masz tu jakieœ przedmioty zabronione?}
{242}{}{Zale¿y od tego, co jest tu zabronione...}
{243}{}{Zartowa³em! Mo¿esz iœæ do obozu.}
{244}{}{Naprawdê?}
{245}{}{Witamy w Blasku Dnia!}
{246}{}{Dziêkujê.}
{247}{}{Karany za nielegalne przekroczenie granicy? Dobra, skoro i tak ju¿ tu jesteœ, muszê to zaakceptowaæ. Nie przeszkadzaj ghulom.}
{248}{}{Nie ma problemu.}
{249}{}{Nie spodziewa³em siê tego. Dziêkujê. Blask Dnia czeka.}
{250}{}{Mo¿esz wejœæ.}
{251}{}{Do widzenia.}
{252}{}{Mo¿esz wejœæ. Ja bym ciê nie wpuœci³, ale ktoœ w obozie ma inne zdanie.}
{253}{}{Zostane tu trochê d³u¿ej. Mo¿e potrzebujesz pomocy?}
