{100}{}{Widzisz Ralpha.}
{101}{}{Widzisz ghula, którego ju¿ znasz. Nadal ma na sobie znoszone ubranie robocze z przedwojennym symbolem.}
{102}{}{Zastanawiam siê, jak sobie radz¹ ch³opaki z elektrowni?}

{200}{}{Co za spotkanie! To na pewno sprawka anio³a Pulsu Elektromagnetycznego, który ponownie nas zjednoczy³.}
{201}{}{Ralph? Co Ty tutaj robisz? Mia³eœ jechaæ do Teksasu, prawda?}
{202}{}{Na jakiœ czas zatrzyma³em siê w Phoenix. W lokalnych kana³ach s¹ doœæ grube szczury. Wtedy do miasta przyby³ ponury ghul i opowiedzia³ o Blasku Dnia. Uœwiadomi³ mi, ¿e lepiej byæ blisko swoich, ni¿ samotnie gin¹æ w piasku. Co Ty tutaj robisz?}
{203}{}{Szukam nowych przygód... prawdopodobnie.}
{204}{}{Hmm? Nie wiem co powiedzieæ. Jesteœ dziwn¹ osob¹. Mo¿e nie radzisz sobie dobrze w domu? Ale tu te¿ trudno bêdzie ci siê tu dogadaæ - wszêdzie pe³no promieniowania i œladów Starego Swiata. }
{205}{}{Wiem.}
{206}{}{Masz, potraktuj te leki to jako dowód wdziêcznoœci za pomoc w elektrowni. Przydadz¹ ci siê.}
{207}{}{Dziêki, Ralph. Do widzenia.}
{208}{}{Chcesz mnie w ten sposób przeprosiæ za to, co zrobi³eœ? OK, niech tak bêdzie, przyjmê to. Zegnaj, Ralph.}
{209}{}{W takim razie powodzenia. Opowiem innym o twojej pomocy. Myœlê, ¿e powinni wiedzieæ, bo wygl¹da na to, ¿e nie jesteœ tu dobrze traktowany.}
{210}{}{Dziêki, Ralph. By³bym naprawdê wdziêczny.}
{211}{}{Nie rób tego. Jestem zadowolony ze swojej reputacji. Do widzenia.}

{220}{}{Elektrownia by³a naprawdê dobrym miejscem. Zastanawiam siê, jak tam siê teraz sprawy maj¹?}
{221}{}{Nie wiem.}