{100}{}{Widzisz oficera.}
{101}{}{Widzisz robota z doœæ zu¿yt¹ plakietk¹ z boku. Wygl¹da na to, ¿e reprezentuje tu jak¹œ w³adzê.}
{102}{}{B¹dŸ czujny, obywatelu. Droga nie jest bezpieczna.}

{110}{}{Staæ! Lamiesz przepisy ruchu drogowego.}
{111}{}{Lamiesz prawo, id¹c autostrad¹.}
{112}{}{Nie wolno Ci wychodziæ z pojazdu na autostradzie.}
{113}{}{Jesteœ aresztowany. ZejdŸ z jezdni i po³ó¿ siê twarz¹ do ziemi.}
{114}{}{Pójdziesz ze mn¹ na komisariat.}
{115}{}{Poddaj siê. Nie unikniesz sprawiedliwoœci.}
{116}{}{Nie chcê ciê skrzywdziæ. Ale stwarzasz zagro¿enie.}
{117}{}{Mój program chce, ¿ebyœ przesta³.}
{118}{}{Wszelkie roszczenia mo¿na sk³adaæ u prawnika.}
{119}{}{Nie pozwolê ci odejœæ, dopóki nie zap³acisz kary.}
{120}{}{Moim obowi¹zkiem jest ciê zatrzymaæ, zanim spowodujesz wypadek drogowy.}
