{100}{}{Widzisz Derricka.}
{101}{}{Widzisz przed sob¹ ghula. Uwa¿nie obserwuje id¹cych ulic¹.}
{102}{}{Mój interes upad³ po œmierci DeSantiego.}
{103}{}{OK! OK! Bêdê dla niego pracowaæ. Tylko nie dotykaj mojego biednego, delikatnego cia³a!}
{104}{}{Derrick nie ma zamiaru ju¿ walczyæ.}

{200}{}{Witaj, g³adka twarz. Gdzie idziesz?}
{201}{}{Nie twoja sprawa.}
{202}{}{OK, cokolwiek powiesz.}
{203}{}{Pozdrowienia.}
{204}{}{Mo¿e Stare Miasto, mo¿e lokal po drugiej stronie ulicy, mo¿e nigdzie. Po co pytasz?}
{205}{}{Dlaczego pytasz?}
{206}{}{Mogê ciê podwieŸæ. A mo¿e wybierasz siê do sanatorium? Ale to tylko dla ghuli. Dlatego nie radzê Ci iœæ tam z g³adk¹ twarz¹. I tak nie ma tam nic do roboty. A ja za nisk¹ cenê mogê ogarn¹æ ka¿dy rodzaj relaksu. Skontaktuj siê ze mn¹, nie zawiedziesz siê.}
{207}{}{OK, zobaczmy, co masz.}
{208}{}{Mogê ciê podwieŸæ. A mo¿e wybierasz siê do sanatorium? To tylko dla ghuli. Ale pamiêtaj, ¿e tam ceny s¹ tak wysokie, jak pisk mojej zmar³ej ¿ony. Za nisk¹ cenê mogê ogarn¹æ ka¿dy rodzaj relaksu. Skontaktuj siê ze mn¹, nie zawiedziesz siê.}
{209}{}{Hm. Bêdê pamiêtaæ.}
{210}{}{Witam, kundelku. Gdzie idziesz?}
{211}{}{Wrócisz po wiêcej.}
{212}{}{Tak. Do widzenia.}
{213}{}{Bardzo w to w¹tpiê.}
{214}{}{Co powiesz na „Mogê ciê podwieŸæ?}

{220}{}{Ach, to znowu ty. Czego chcesz tym razem?}
{221}{}{Tak, nic specjalnego. Do widzenia.}
{222}{}{Poka¿ mi, co potrafisz.}
{223}{}{Niewa¿ne. Pozwól mi zobaczyæ, co tu sprzedajesz.}

{230}{}{No có¿, Derrick. DeSanti jest niezadowolony, ¿e przechwytujesz jego klientów.}
{231}{}{Ta ziemia jest niczyja. Chcê tu handlowaæ i bêdê to robiæ.}
{232}{}{Nie boisz siê, ¿e ta ziemia stanie siê twoim grobem?}
{233}{}{Nadal mam szacunek dla bandytów ze Starego Zachodu. Spotykali siê w uczciwej walce. A DeSanti by³ tylko ma³¹ rybk¹ w œrodowisku gangów Bakersfield. I tak pozosta³o. Nie bêdzie mnie zastrasza³.}
{234}{}{Och, OK. Nie chcê z nim zadzieraæ.}
{235}{}{Za du¿o mówisz, Derrick. Bêdziesz musia³ wzi¹æ lekcje.}
{236}{}{Bêdziesz tego ¿a³owaæ. Pewnego dnia.}
{237}{}{Masz wybór – umrzeæ lub pracowaæ dla DeSanti. Czekam wiêc na odpowiedŸ. Raz...}
{238}{}{Hej, hej, nie bêdziesz odwala³ brudnej roboty dla jakiegoœ bandyty, prawda?}
{239}{}{Nie zamierzam. To by³ taki ¿art. Zegnaj, Derrick.}
{240}{}{Nie obchodzi mnie to, dopóki on p³aci. Dobra, marnujê z tob¹ tylko czas. Pora z tob¹ skoñczyæ!}
{241}{}{Dwa...}
{242}{}{Wow wow wow, DeSanti naprawdê tego chce? Powa¿nie? Pieprzyæ to!}
{243}{}{Trzy!}
{244}{}{OK! OK! Bêdê dla niego pracowaæ. Tylko nie dotykaj mojego biednego, delikatnego cia³a!}
{245}{}{Za póŸno, Derrick. Jestem tob¹ zmêczony. Bêdê musia³ ciê ukaraæ!}
{246}{}{Swietnie. I nie próbuj niczego g³upiego. DeSanti jest teraz szefem.}

{250}{}{Powiedzia³eœ, ¿e „mo¿esz mnie podwieŸæ”.}
{251}{}{Co prawda od d³ugiego czasu nie mam samochodu, ale znam inne szybkie i bezpieczne sposoby. Dok¹d chcesz iœæ?}
{252}{}{[San Ysidro za }
{253}{}{[Zapora Bonita za }
{254}{}{ kapsli]}
{255}{}{Byæ mo¿e pójdê sam.}
{256}{}{Za ma³o, co? Szkoda.}
{257}{}{Tak, bêdziesz musia³ iœæ pieszo.}
{258}{}{Czekaj, muszê siê jeszcze czegoœ dowiedzieæ.}
{259}{}{[Chula Vista za }
