{100}{}{Widzisz Czarnego Poszukiwacza.}
{101}{}{Widzisz przed sob¹ Czarnego Poszukiwacza.}
{102}{}{To jest nasz obszar. Wynoœ siê st¹d.}
{103}{}{Wspó³pracujemy z DeSantim. Jeœli bêdziesz czegoœ potrzebowaæ, porozmawiaj z nim.}

{200}{}{To jest nasz obszar. Wynoœ siê st¹d.}
{201}{}{Przepraszam. Ju¿ odchodzê.}
{202}{}{A co jeœli odmówiê? Potrafisz tylko zastraszaæ?}
{203}{}{To nie jest twój obszar. To jest teren pana DeSanti.}
{204}{}{Co robisz? Kto to jest? Kolejny ghul? Dlaczego mam siê z nim liczyæ?}
{205}{}{Pracujesz tu nielegalnie, prawda? DeSanti da ci Pieczêæ Setha pod warunkiem, ¿e bêdziesz dla niego pracowaæ.}
{206}{}{Nie potrzebujê ¿adnej Pieczêci Setha! Inaczej ju¿ dawno bym j¹ mia³. Rozumiesz?}
{207}{}{Wygl¹da na to, ¿e nie ma sensu z tob¹ rozmawiaæ. Rozumiesz tylko brutalna si³ê...}
{208}{}{[WyjdŸ]}