{100}{}{Widzisz Kurta.}
{101}{}{Widzisz zwyk³ego ghul.}
{102}{}{Nie mam ¿adnych kapsli! NIC! NIC!}
{103}{}{OK! OK! Oto kapsle. Tylko nie bij mnie ju¿ wiêcej!}
{104}{}{OK! OK! Oto wszystkie moje kapsle. Wiêcej ju¿ nie mam!}
{105}{}{Kurt siê poddaje.}
{106}{}{Och, czego ode mnie chcesz?}
{107}{}{Co za idiota!}

{200}{}{Jestem dziœ po prostu pe³en energii! Dawno nie mia³em takiego odpoczynku... Och, czego ode mnie chcesz?}
{201}{}{Kim jesteœ?}
{202}{}{Nazywam siê Kurt. I co?}
{203}{}{Szukam ciê. Masz d³ug u pana DeSanti.}
{204}{}{Pan jest bardzo z³y, prawda? I co mnie to?! Nie zamierzam p³aciæ za jego okropne us³ugi w tym obskurnym pokoju. I w ogóle - ghul zabieraj¹cy pieni¹dze innemu ghulowi to wstyd! Co on sobie myœli? Budujemy tu komunizm! Nie widaæ?}
{205}{}{Nie zagaduj mnie tutaj. Dawaj kapsle!}
{206}{}{Pan DeSanti nie zostawi ciê w spokoju.}
{207}{}{Nie zap³acê! Jeœli chcesz to zap³aæ za mnie!}
{208}{}{W takim razie wezmê kapsle si³¹. Gdzie masz kieszenie?}
{209}{}{OK, no to ja zap³acê.}
