{100}{}{Widzisz Flowersa.}
{101}{}{Widzisz potê¿nego supermutanta.}
{102}{}{Jestem g³odny!}
{103}{}{Witamy w... ech, zapomnia³em nazwy.}
{104}{}{Prawda. Ghule i mutanty mog¹ siê dogadaæ.}
{105}{}{Mniam, mniam... To nie wystarczy!}
{106}{}{Teraz jestem ju¿ pe³ny!}

{200}{}{Ty! Nie bój siê mnie... PodejdŸ bli¿ej... Nie zjem ciê... Arch! Mam ciê, g³upia mysz! Ehh, uciek³a...}
{201}{}{Kogo tam ³apiesz, wielkoludzie?}
{202}{}{Jestem g³odny! Hej, masz jedzenie? Hmm, wygl¹dasz... nie! Nie mogê ciê zjeœæ! Ghule mnie wtedy nie zaakceptuj¹.}
{203}{}{Jesteœ Flowers? Pan DeSanti oferuje ci pracê. Jeœli siê zgodzisz, bêdziesz mia³ jedzenie.}
{204}{}{Jestem g³odny! Najpierw jedzenie, potem rozmowa!}
{205}{}{OK.}
{206}{}{Mniam, mniam, mniam... To nie wystarczy!}
{207}{}{Chcesz wiêcej? Wiêc idŸ pracowaæ dla Pana DeSanti.}
{208}{}{IdŸ do DeSanti. DeSanti musi byæ dobrym ghulem. Iœæ!}
{209}{}{Myœlê, ¿e znajdziesz drogê. Spotkajmy siê w Dzielnicy W³oskiej.}
