{100}{}{Widzisz opiekunkê.}
{101}{}{Widzisz kobietê w starym szlafroku.}

{110}{}{Mogê pomasowaæ Twoje plecy, króliczku. Ale najpierw zap³aæ administratorowi.}
{111}{}{Chcesz pop³ywaæ? Umyjê WSZYSTKIE czêœci Twojego cia³a.}
{112}{}{Mamy tu wodê radonow¹, k¹piel radonow¹, k¹piel z hydromasa¿em uranowym i prysznic plutonowy. Wybierz to, co lubisz najbardziej.}
{113}{}{Dobra k¹piel kosztuje. A moja czu³oœæ jest warta jeszcze wiêcej.}
{114}{}{Dziêki mnie zapomnisz o wszystkich swoich problemach, króliczku.}
{115}{}{No dalej, zdejmij spodnie. Wiem, gdzie dotykaæ, a gdzie nie.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
