{100}{}{Widzisz Cabbota, handlarza ghuli.}
{101}{}{Widzisz lokalnego sprzedawcê.}
{102}{}{Nie pomagam zdrajcom. Wynoœ siê z mojego sklepu.}
{103}{}{S³uchaj, jeœli nie podoba ci siê nasze miasto, to wracaj na swoje pustkowia, kretynie.}

{200}{}{Witam, cz³owieku. Jestem Cabbot, a to jest mój sklep. Jeœli bêdziesz czegoœ potrzebowaæ, po prostu mi powiedz.}
{201}{}{Witaj Cabbot. Co sprzedajesz?}
{202}{}{Mam znaleziska z ca³ego Blasku. Co prawda czêœæ z nich jest natychmiast zabierana przez karawany na pó³noc.}
{203}{}{Dlaczego?}
{204}{}{Tutaj, na Starym Mieœcie, wierzymy, ¿e powinniœmy pomóc ludziom odbudowaæ cywilizacjê przy u¿yciu starych rzeczy i wiedzy... No, tak mówi Butler. Osobiœcie kierujê siê wy³¹cznie zyskiem. Jestem kupcem. Zawsze tak by³o.}
{205}{}{Zobaczmy, jakie œmieci ci przynieœli tym razem...}
{206}{}{Chcê obejrzeæ te wszystkie przedwojenne relikty. Poka¿ mi swój asortyment...}
{207}{}{Przykro mi, ale na rabaty nie masz co liczyæ. Ceny dla Ciebie bêd¹ takie same jak dla innych g³adkoskórych.}
{208}{}{OK, cokolwiek powiesz...}
{209}{}{Mam specjalne ceny dla mutantów i ghuli. S¹ bardziej... powiedzmy... demokratyczne. Nie myœl, ¿e jestem rasist¹, ale tutaj mamy dwojaki stosunek do ludzi. A ja ci go sprzedam za rozs¹dn¹ cenê.}
{210}{}{Och, dziêki kolego.}
{211}{}{Najlepsze rzeczy znalezione w ruinach wielkiego miasta s¹ tutaj!}
{212}{}{Do widzenia.}
{213}{}{Czy mogê zadaæ ci kilka pytañ?}

{220}{}{Czego szukasz, przyjacielu?}
{1220}{}{Czego szukasz, przyjació³ko?}
{221}{}{Czego chcesz, maleñka?}
{222}{}{Co tym razem?}
{223}{}{Do widzenia.}
{224}{}{Muszê coœ kupiæ.}

{230}{}{Nadal nie znalaz³eœ sterownika paliwa dla Rutgera?}
{231}{}{Na pewno tu by³! Przeszuka³em wszystkie skrzynki, ale nie mog³em go znaleŸæ.}
{232}{}{Kto jeszcze go mia³?}
{233}{}{Hmm... kurier Steve Morgan mi go przyniós³. A potem poszed³ przewaliæ kapsle w barze. Nie widzia³em go od tego czasu.}
{234}{}{Spróbujê go tam znaleŸæ. Do widzenia.}

{240}{}{Szukam ghula o imieniu Rupert. Wiesz gdzie on jest?}
{241}{}{Rupert? Przyby³ do Blasku miesi¹c temu. Nie widzia³em go od tego czasu.}
{242}{}{OK, zapomnij.}
{243}{}{Z kim jeszcze rozmawia³, zanim znikn¹³?}
{244}{}{Nie wiem.}
{245}{}{Gdzie poszed³?}
{246}{}{Nie wiem.}
{247}{}{Czy powiedzia³ chocia¿, co zamierza zrobiæ?}
{248}{}{Nie. Chocia¿... Powiedzia³, ¿e jest zmêczony i chce odpocz¹æ.}
{249}{}{I co mu powiedzia³eœ?}
{250}{}{Powiedzia³em mu o salonie w hotelu La Pensione. Nie widzia³em go od tego czasu.}
{251}{}{To ten w Dzielnicy W³oskiej, tak? Ok, dziêki.}

{260}{}{Czy wiesz, gdzie mogê zdobyæ jakiœ program dla Pana R¹czki?}
{261}{}{Zapytaj o to Phila w bibliotece. Ma du¿y mózg, mo¿e coœ wymyœli.}
{262}{}{Dziêkujê.}

{270}{}{Ktoœ tu zostawi³ mi zaszyfrowan¹ holotaœmê.}
{271}{}{Ktoœ, mówisz? Nawet nie znasz jego imienia?}
{272}{}{Niestety, ale nie przedstawi³ mi siê.}
{273}{}{Rozumiem. Rzeczywiœcie mam tu jeden holodysk. Daj mi swojego Pip-Boya. Spróbujmy za³adowaæ do niego t¹ holotaœmê.}
{274}{}{[Dalej]}
{275}{}{(Wk³adasz holodysk i rozpoczynasz proces deszyfrowania. Okazuje siê, ¿e nagranie jest zaszyfrowane specjalnie pod Twojego Pip-Boya.)}
{276}{}{[Przeczytaj wpis]}
{277}{}{"Przykro mi, ¿e ciê nie spotka³em. Mam du¿o do zrobienia. Ale poradzisz sobie beze mnie."}
{278}{}{[Dalej]}
{279}{}{"Pomiêdzy Gustavo i Butlerem panuje spór co do przysz³oœci Blasku Dnia. I szczerze mówi¹c, nie wiem, który z nich ma racjê. Najwa¿niejsze jest, aby ludziom nie sta³a siê krzywda. Blask Dnia to nie tylko ruiny. Pe³no tam przedwojennych rzeczy... niektóre z nich s¹ niezwykle niebezpieczne i nie mo¿na pozwoliæ, aby wpad³y w niepowo³ane rêce.}
{280}{}{[Dalej]}
{281}{}{"Oprócz ludzi i ghuli istnieje jeszcze inna si³a, która po¿¹da tych zasobów. Bractwo Stali. Zamknêli siê w starej kopalni. Spróbuj siê z nimi skontaktowaæ i zdecyduj, czy im na to pozwoliæ, czy nie. ZnajdŸ ich, mo¿e ci siê uda za pomoc¹ walkie-talkie lub stacji radiowej. Oto czêstotliwoœæ i szyfr, którego u¿ywaj¹."}
{282}{}{[Dalej]}
{283}{}{"Jeszcze jedno. Schowa³em swoje rzeczy w Balboa Park w starym kominie obok podstacji kolei jednoszynowej. Myœlê, ¿e potrzebujesz ich bardziej. Do zobaczenia."}
{284}{}{[Wyci¹gnij holodysk]}
{285}{}{[Przeczytaj ponownie]}
