{100}{}{Widzisz mechanicznego ghula.}
{101}{}{Widzisz przed sob¹ ghula w zniszczonym mundurze roboczym. Zamiast jednego oka ma coœ, co wygl¹da jak wbudowana soczewka.}
{102}{}{Przepraszam. Obs³ugiwane s¹ tu tylko ghule i ich przyjaciele.}
{103}{}{Nie bêdê obs³ugiwa³ takiego os³a jak ty. Wypad.}
{104}{}{Na mnie to nie zadzia³a. Ale wygl¹da fajnie.}

{200}{}{To jest warsztat i sklep z narzêdziami. Szef mówi, ¿e mo¿esz zostaæ. Ale nadal bêdê mieæ ciê na oku.}
{201}{}{Zobaczysz, ¿e niepotrzebnie.}
{202}{}{Tak siê nie rozmawia z klientami.}
{203}{}{To wszystko, co mam. Jeœli potrzebujesz wiêcej z³omu, udaj siê na Stare Miasto.}
{204}{}{Czeœæ.}
{205}{}{Czekaj, mam coœ innego do omówienia.}
{206}{}{Witaj, skórko! Cieszê siê, ¿e ciê widzê. Jest to warsztat i sklep z narzêdziami. WejdŸ, wybierz co chcesz. Mam du¿¹ zni¿kê dla ghuli i mutantów.}
{207}{}{To dobrze.}
{208}{}{Muszê jeszcze raz przyjrzeæ siê przedmiotom na ladzie.}
{209}{}{}

{210}{}{Witaj, skórko. Jak siê masz?}
{211}{}{Witaj, zielone stworzenie. Jakich czêœci potrzebujesz tym razem?}
{212}{}{Czeœæ, ty cholerny mutancie. Przykro mi, ale nie ma ju¿ dodatkowych r¹k i nóg. Haha, ¿art.}
{213}{}{Witam, dziwaku. Jak siê dziœ czujesz?}
{214}{}{Potrzebujesz czêœci? No to wybierz coœ szybko i wyjdŸ.}
{215}{}{Potrzebujesz czêœci?}
{216}{}{Powiedz, czego szukasz. Nie wstydŸ siê.}
{217}{}{Muszê kupiæ kilka rzeczy.}
{218}{}{Czeœæ.}

{220}{}{Ghul z prêtem zbrojeniowym w g³owie prosi³ mnie, ¿ebym to naprawi³.}
{221}{}{To wszystko? OK, chodŸ tutaj...}
{222}{}{Proszê.}
{223}{}{Nie, chcê sam spróbowaæ...}
{1223}{}{Nie, chcê sama spróbowaæ...}
{224}{}{Och, nie podoba mi siê, jak do mnie mówisz. No ale musisz mi pomóc. Zabierz to tutaj...}
{225}{}{Gotowe. Uwa¿aj, ¿eby nie zepsuæ tego po drodze.}
{226}{}{OK. Dziêkujê.}
{227}{}{Wiem to i bez ciebie!}

{230}{}{Mam tu stary holodysk. Czy mo¿esz zrobiæ dla mnie jego kopiê?}
{231}{}{Ach, sumienie drêczy, co? Oczywiœcie, ukraœæ coœ osobie z autyzmem, a potem chodziæ po okolicy bez wyrzutów – tylko kompletna szumowina potrtafi coœ takiego. Ale dlaczego mam ci pomóc, zamiast zwróciæ p³ytê prawowitemu w³aœcicielowi?}
{232}{}{Potrzebujê tej kopii, ¿eby zwróciæ mu orygina³. Rozumiesz?}
{233}{}{Och, niech bêdzie. Dobra. Zrobiê kopiê za }
{234}{}{ kapsli. Kapsle z góry.}
{235}{}{Poczekaj chwilê, pójdê po kapsle.}
{236}{}{Ok, zrób to. Oto kapsle i dysk.}
{237}{}{Otrzymujesz kopiê holodysku.}

{250}{}{Muszê ulepszyæ moj¹ broñ.}
{251}{}{Najpierw mi j¹ poka¿.}
{252}{}{Nie mam teraz nic wartoœciowego.}
{253}{}{[}
{254}{}{ za }
{255}{}{]}
{256}{}{Gotowe. Czy jest coœ jeszcze w czym mogê pomóc?}
{257}{}{Nie. Dziêkujê.}
{258}{}{Tak. Byæ mo¿e.}
{259}{}{B¹dŸmy szczerzy, nie staæ ciê na to, prawda?}
{260}{}{Ups.}
