{100}{}{Widzisz ojca Taliusa.}
{101}{}{Widzisz mutanta w wytartej koszuli i kapeluszu. Nosi krzy¿ na szyi.}
{102}{}{Widzisz przed sob¹ Taliusa, cz³onka Wyznawców.}
{103}{}{Podaruj to komuœ, kto naprawdê na to zas³uguje.}
{104}{}{Fernando zosta³ w mieœcie.}
{105}{}{Beatrice zosta³a w mieœcie.}

#Pierwsze spotkanie
{200}{}{Witam, bracie. Nazywam siê Talius. I cieszê siê, ¿e ciê widzê w Blasku. Potrzebujesz pomocy?}
{1200}{}{Witam, siostro. Nazywam siê Talius. I cieszê siê, ¿e ciê widzê w Blasku. Potrzebujesz pomocy?}
{201}{}{Nie jesteœ moim bratem. Czy ty w ogóle widzia³eœ siebie w lustrze?}
{202}{}{Widzê, ¿e ty te¿ nie jesteœ zbyt m¹dry. By³em kiedyœ taki sam. Ale uczenie siê od innych uczyni³o mnie m¹drzejszym.}
{203}{}{Boli Ciê czaszka?}
{204}{}{Wiesz, to czasami siê zdarza. Czasami trzeba przeci¹æ dodatkowe zwoje przez tê dziurê w... Ach, wygl¹da na to, ¿e mówisz o czymœ innym. Przepraszam. Od czasu do czasu siê zapominam. A wiêc... potrzebujesz pomocy?}
{205}{}{Przepraszam, chce tylko powiedzieæ, ¿e jest miêdzy nami wiele ró¿nic. To nic rasistowskiego.}
{206}{}{Tak, chyba. Wiêc potrzebujesz mojej pomocy?}
{207}{}{Tylko wpad³em, ¿eby obejrzeæ sobie to miejsce.}
{1207}{}{Tylko wpad³am, ¿eby obejrzeæ sobie to miejsce.}
{208}{}{Dziêkujê za mi³e powitanie. Nie spodziewa³em siê tego us³yszeæ w takim miejscu.}
{209}{}{Rozumiem. Ghule s¹ podejrzliwe w stosunku do normalnych. Prze¿y³y zbyt wiele ataków. Ale poka¿ swoj¹ dobr¹ stronê, a ghule uciesza siê, ¿e ciê widz¹.}
{210}{}{Mam tak¹ nadziejê. Dlaczego jesteœ taki przyjacielski?}
{211}{}{To by³ sarkazm, idioto! Nigdy nie zaprzyjaŸniê siê z takimi dziwakami jak ty.}
{212}{}{Przykro mi to s³yszeæ. Mam nadziejê, ¿e z czasem zmienisz zdanie. Mo¿e potrzebujesz pomocy?}

{220}{}{Witam, bracie. Potrzebujesz pomocy?}
{1220}{}{Witam, siostro. Potrzebujesz pomocy?}
{221}{}{Nie, nie. Przepraszam, ¿e przeszkadzam.}
{222}{}{Co chcesz wiedzieæ?}
{223}{}{Nic wiêcej. Dziêkujê za poœwiêcenie mi czasu.}
{224}{}{Du¿o, ale ty nic nie wiesz. Do widzenia.}
{225}{}{Wkrótce w Blasku nadejd¹ wielkie zmiany. A potem zmiany dosiêgn¹ reszty œwiata. To zarówno przera¿aj¹ce, jak i inspiruj¹ce... Potrzebujesz pomocy?}

#O obserwujacych
{230}{}{Oto Kaplica Wyznawców Apokalipsy. Pomagam tutaj ghulom poznaæ nasze nauki.}
{231}{}{Przepraszam, ¿e przeszkadzam. Ale chcê zmieniæ temat.}
{232}{}{Znam kilku Obserwatorów. Spotkaliœmy siê w Casa Nueva.}
{233}{}{Wiêc wiesz wystarczaj¹co du¿o. Wyznawcy Apokalipsy, Obserwatorzy to ¿yczliwi ludzie. Chc¹ zaprowadziæ pokój w tej przeklêtej krainie.}
{234}{}{Gdzie jest reszta Obserwatorów?}
{235}{}{Jestem tu sam. Tylko ghule i mutanty mog¹ ¿yæ wœród tych napromieniowanych ruin. A prawie wszyscy Obserwatorzy to zwykli ludzie. Ich g³ówna siedziba znajduje siê w innym mieœcie.}
{236}{}{Jak zosta³eœ Obserwatorem, skoro jesteœ... no... ghulem?}
{237}{}{Uwierzysz mi, jeœli ci powiem, ¿e mam inn¹ naturê? Wyznawcy uratowali mnie przed przemian¹ w okropne zwierzê, gdy le¿a³em nieprzytomny pod wp³ywem mutagenu. Potem pozwolili mi do³¹czyæ do swojej organizacji. S¹ dobrymi ludŸmi.}
{238}{}{Rozumiem.}
{239}{}{Czego uczycie?}
{240}{}{Wyznawcy Apokalipsy chc¹ zaprowadziæ pokój w tej przeklêtej krainie. G³osz¹ altruizm i niestosowanie przemocy. Wykorzystuj¹ przedwojenn¹ wiedzê do poprawy ¿ycia ludzi. Ale co najwa¿niejsze, nie pozwol¹ ludziom powtórzyæ b³êdu z roku 2077.}
{241}{}{Opowiedz mi o swojej wierze.}
{242}{}{Twoje s³owa o Wyznawcach poruszy³y mnie do g³êbi. Chcê przekazaæ darowiznê.}
{243}{}{To szlachetne z twojej strony. Ile kapsli mo¿esz przekazaæ na nasze potrzeby?}
{244}{}{W tej chwili nic. To znaczy, zrobiê to w przysz³oœci.}
{245}{}{100 kapsli.}
{246}{}{200 kapsli.}
{247}{}{300 kapsli.}
{248}{}{400 kapsli}
{249}{}{500 kapsli.}
{250}{}{Dziêkujê. Mi³ego dnia!}
{251}{}{Nie ma za co.}
{252}{}{Odczuwam ulgê. Ale chcê z tob¹ jeszcze chwilê porozmawiaæ, ojcze Taliusie.}

#O mnie
{260}{}{Przypomnij mi, jak masz na imiê?}
{261}{}{Jestem Talius.}
{262}{}{W porz¹dku, Taliusie.}
{263}{}{Sk¹d jesteœ, Taliusie?}
{264}{}{Mój dom jest daleko, w starej Krypcie 13.}
{265}{}{Znam kilka Krypt, ale o 13 pierwszy raz s³yszê.}
{266}{}{Nigdy o niej nie s³ysza³em.}
{1266}{}{Nigdy o niej nie s³ysza³am.}
{267}{}{Oczywiœcie. Takich Krypt by³o wiele. I wiele z nich obecnie ju¿ nie dzia³a.}
{268}{}{Czy inne ghule te¿ przyby³y z Krypty 13?}
{269}{}{To nie ma znaczenia. Zmieñmy temat.}
{270}{}{Wiêkszoœæ z nich pochodzi z Krypty 12, pod miastem Nekropolis. By³em tam i szuka³em czêœci do mojej Krypty. Ale zmutowa³em.}
{271}{}{Wiêc nie jesteœ ghulem?}
{272}{}{Smutna historia. Musimy zmieniæ temat.}
{273}{}{Mutantem. Naukowcy Mistrza takim mnie stworzyli. Chcieli zamieniæ mnie w supermutanta, ale coœ posz³o nie tak.}
{274}{}{Mutantem. Naukowcy Mistrza takim mnie stworzyli. Chcieli zamieniæ mnie w supermutanta, ale coœ posz³o nie tak. Wygl¹da na to, ¿e tobie przydarzy³o siê coœ podobnego.}
{275}{}{To naprawdê okropne. Szkoda, ¿e nie mogê zrobiæ nic, ¿eby ci pomóc.}
{1275}{}{To naprawdê okropne. Szkoda, ¿e nie mogê zrobiæ nic, ¿eby ci pomóc.}
{276}{}{Dziêkujê za mi³e s³owa. Wiesz, kiedyœ by³em ateist¹. Ale po tym jak los uczyni³ mnie nieœmiertelnym, mimowolnie uwierzy³em w Bo¿y plan. Mo¿e to tylko test?}
{277}{}{Myœlê, ¿e to z³e byæ takim. Ale nic nie da siê zrobiæ.}
{278}{}{Wiesz, kiedyœ by³em ateist¹. Ale po tym jak los uczyni³ mnie nieœmiertelnym, mimowolnie uwierzy³em w Bo¿y plan. Mo¿e to tylko test?}
{279}{}{Porozmawiamy o czymœ innym?}
{280}{}{Powodzenia, Ojcze Taliusie.}

#Skrypt24
{290}{}{Pamiêtam nasz¹ rozmowê o Kryptach. Czy Blask te¿ tak¹ ma?}
{291}{}{Byæ mo¿e. Dlaczego pytasz?}
{292}{}{Tak tylko. Nie zwracaj uwagi.}
{293}{}{No có¿, natkn¹³em siê na coœ takiego. Myœlê, ¿e ma to coœ wspólnego z Kryptami.}
{294}{}{Manierka z Krypty 24... Relikt z czasów staro¿ytnych. Sk¹d to masz?}
{295}{}{By³a przy jednym ze szkieletów w kombinezonie. Myœlê, ¿e szkielet le¿a³ w gruzach przez wiele dziesiêcioleci.}
{296}{}{Mo¿e by³ to jeden z Obserwatorów, których Wyznawcy wys³ali na zwiad. W tych trudnych czasach zginê³o wielu dobrych ludzi.}
{297}{}{Wyznawcy te¿ opuœcili Kryptê?}
{298}{}{Ci, którzy byli ich przodkami. Reszta urodzi³a siê ju¿ po opuszczeniu Krypty lub do³¹czy³a z zewn¹trz.}
{299}{}{Co siê sta³o z t¹ Krypt¹?}
{300}{}{Nie znam ca³ej historii. Krypta jest ju¿ i tak bezu¿yteczna. Ludzie zabrali stamt¹d wszystko, co mia³o wartoœæ. Ponadto w tych miejscach mo¿na spotkaæ straszne stworzenia. Nie polecam tam chodziæ.}
{301}{}{Podejmê ryzyko. Ze wzglêdu na historiê. Poka¿ mi drogê.}
{302}{}{Krypta zaczeka. Nie mam ochoty na ¿adne niebezpieczne przygody.}
{303}{}{Jest w œrodku Otay Park. Trudno j¹ znaleŸæ, wiêc wyznaczê trasê w twoim Pip-Boyu.}
{304}{}{[IdŸ.]}
{305}{}{Nie teraz. Muszê siê przygotowaæ do wyjœcia.}
{306}{}{Podejmê ryzyko. Na pewno nie wszystko zosta³o stamt¹d zabrane. Poka¿ mi drogê.}
{307}{}{Czy to nie zbyt bezczelnie z twojej strony tak po prostu chcieæ tam wejœæ? Wszystko tutaj nale¿y do ghuli. Wielu nie podoba siê sama twoja obecnoœæ. Poka¿ê Ci Kryptê, ale w zamian liczê na dobry datek. Powiedzmy 1000 kapsli.}
{308}{}{Nie mogê teraz wydaæ tak du¿o. Zostawmy to na potem, dobrze?}
{309}{}{Dobrze. Oto 1000 kapsli. Poka¿ mi drogê.}
{310}{}{W zamian bêdziesz bezpieczny, kretynie. To najlepsze, na co mo¿esz liczyæ.}
{311}{}{Muszê wracaæ do Krypty 24. Natychmiast.}
{312}{}{Pomó¿ mi dostaæ siê do Krypty 24.}

#Szaleniec
{320}{}{Czy mogê coœ zrobiæ, ¿eby pomóc ludziom?}
{321}{}{Nasze dusze potrzebuj¹ ocalenia, z reszt¹ sobie poradzimy. Niedawno poinformowano mnie o kolejnej ofierze szaleñstwa: nasz przyjaciel Gonzo wpadl w sza³ i uciek³ do ruin Chula Vista. W tym stanie jest niebezpieczny. Trzeba go zatrzymaæ.}
{322}{}{Czy mo¿emy coœ zrobiæ bez zabijania go?}
{323}{}{Prosisz, ¿ebym go ZABIL?}
{324}{}{(wzdycha) Czy któryœ z ghuli podniesie rêkê na swojego towarzysza? Nie s¹dzê. Wiele ghuli potêpi to. Ale na szaleñstwo nie ma lekarstwa. Jedyne, co mo¿emy zrobiæ, to unikn¹æ niepotrzebnych ofiar.}
{325}{}{Po prostu odetnê mu g³owê, nie ma sprawy.}
{326}{}{Widzia³em to ju¿ wczeœniej w Inferno. Takie szaleñstwo mo¿e powstrzymaæ jedynie œmieræ.}
{327}{}{Nie mo¿esz tak po prostu zabijaæ innych! Ale jeœli nie da siê inaczej, Gonzo bêdzie musia³ zostaæ wys³any do przodków. Ale pamiêtaj, ¿e Gonzo jest naszym bratem. Ghule ¿y³y z nim przez wiele lat w Nekropolis. Oka¿ trochê wspó³czucia.}
{328}{}{Czy mo¿na chocia¿ na chwilê przywróciæ mu zdrowie psychiczne?}
{329}{}{W niektórych przypadkach pomagaj¹ leki, w innych wspomnienia przesz³oœci. Byæ mo¿e nic nie pomo¿e. Ale wszelkie rozwi¹zania s¹ tymczasowe.}
{330}{}{Wymyœlê coœ.}
{331}{}{Niech Bóg ci pomo¿e.}
{332}{}{Wrócê.}
{333}{}{Mam jeszcze kilka pytañ.}
{334}{}{Jeœli nawet ty nie potrafisz poradziæ sobie ze swoimi braæmi, to ja tym bardziej. Przykro mi.}
{335}{}{Rozumiem. W takim razie po prostu unikaj Gonzo, jeœli znajdziesz go w ruinach.}
{336}{}{Przypomnij mi, gdzie mogê znaleŸæ tego Gonzo?}
{337}{}{Ostatnio by³ widziany w starej dzielnicy handlowej, w ruinach Chula Vista. Ten obszar znajduje siê na pó³nocy.}
{338}{}{Rozumiem.}
{339}{}{}
{340}{}{Gonzo nie ¿yje. Nie pozostawi³ mi wyboru!}
{341}{}{Przynajmniej teraz jego dusza odpocznie. (wzdycha) OK. Nie mam do ciebie pretensji. Jestem z³y tylko na siebie, ¿e nie mogê pomóc szaleñcom. Niestety wszystkie ghule prêdzej czy póŸniej tak skoñcz¹. Na szaleñstwo nie ma lekarstwa.}
{342}{}{Nie obwiniaj siê. Zycie toczy siê dalej.}
{343}{}{By³ zagro¿eniem dla spo³eczeñstwa. Sam to wiesz.}
{344}{}{Dziêkujê za mi³e s³owa.}
{345}{}{Zmieñmy temat.}
{346}{}{Gonzo nie stanowi ju¿ zagro¿enia, prawda?}
{347}{}{Dziêkujê. Szalony Gonzo jest bezpiecznie zamkniêty za kratkami. Oczywiœcie wszystkie ghule prêdzej czy póŸniej tak skoñcz¹. Na szaleñstwo nie ma lekarstwa. Pozostaje tylko zamkn¹æ Gonzo, aby unikn¹æ niepotrzebnych ofiar. Jeœli potrzebujesz uzdrowienia dla swojego umys³u i cia³a, postaram siê ci pomóc.}
{348}{}{Nie zamykaj mnie za kratkami!}
{349}{}{Bêdê o tym pamiêtaæ.}

#Leczenie
{350}{}{Potrafisz leczyæ choroby?}
{351}{}{Wyznawcy nauczyli mnie najprostszych zabiegów medycznych. Ale leki s¹ tutaj bardzo drogie i rzadkie. Co ciê boli?}
{352}{}{Potrzebujê leczenia.}
{353}{}{Nic. Pytam z ciekawoœci.}
{354}{}{ kapsli]}
{355}{}{[Leczenie drobnych urazów za }
{356}{}{[Leczenie powa¿nych urazów za }
{357}{}{[Leczenie choroby popromiennej za }
{358}{}{[Leczenie trucizny za }
{359}{}{Wszystko w porz¹dku.}
{360}{}{Dziêkujê.}
{361}{}{[Leczenie Kuchy za }
{362}{}{Nic mu siê nie sta³o.}

#Donovan
{380}{}{Mam tak¹ sprawê, ojcze. To jest Donovan. I nie ¿yje.}
{381}{}{Naprawdê?}
{382}{}{Ale jego przyjaciele nie mog¹ w to uwierzyæ. Co mam teraz zrobiæ?}
{383}{}{Martwy, mówisz? Donovan? Daj spokój, oczywiœcie, ¿e ¿yje!}
{384}{}{Ty te¿? Czy wy wszyscy jesteœcie szaleni?}
{385}{}{Tutaj, spójrz. Nie oddycha. I brakuje mu po³owy cia³a. To trup.}
{386}{}{Daj go tutaj. Zaraz siê nim zajmê. To tylko...}
{387}{}{Tylko co?}
{388}{}{Obawiam siê, ¿e bez kilku przedmiotów nie bêdê w stanie mu pomóc. Wiesz gdzie jest szpital? Potrzebujê stamt¹d trzech fiolek bio¿elu. I jeszcze ewentualnie czêœci zamiennych.}
{389}{}{Niewa¿ne. Zajmê siê swoimi sprawami.}
{390}{}{No có¿, ty wiesz lepiej. Spróbujê zdobyæ czêœci i bio¿el.}
{391}{}{Mam to, czego potrzebujesz.}
{392}{}{Swietnie! Dobra, nie marnujmy czasu – przejdŸmy do operacji.}
{393}{}{No có¿...}
{394}{}{(Operacja trwa kilka godzin. Czekasz na zewn¹trz. W koñcu wychodzi Talius i g³oœno mówi: „Donovan ¿yje!”)}
{395}{}{Wow, Talius, czynisz cuda!}
{396}{}{Tak. Bo ci uwierzê. Serio. Zegnaj, szarlatanie Taliusie.}
{397}{}{Chodzi o Donovana.}
