{100}{}{Widzisz nieznajomego.}
{101}{}{Widzisz mê¿czyznê w niebieskim kombinezonie.}

#Przerywniki filmowe
{110}{}{ }
{111}{}{Kim jesteœ?}
{112}{}{Nie twoja sprawa. Butler zadaje tu pytania. A teraz wynoœ siê st¹d.}
{113}{}{Najemnicy. Oczywiœcie. Butler nie ust¹pi tak ³atwo.}
{114}{}{Nie jest jeszcze za póŸno. Coronado nale¿y do ghuli z San Ysidro. Ty tu nie pasujesz.}
{115}{}{Uch! Tylko na darmo ³apiemy promieniowanie. Zabierzcie ich z molo, ch³opaki!}

{122}{}{Nie twoja sprawa. Nie pozwolimy nikomu dop³yn¹æ na wyspê bez naszej zgody.}
{123}{}{Eh, czarni poszukiwacze? No jasne, ka¿dy chce skarbu Coronado.}
{124}{}{Ale Coronado nale¿y do WSZYSTKICH! San Ysidro te¿ ma do niego prawo!}
{125}{}{Uch! Tylko na darmo ³apiemy promieniowanie. Zabraæ ich st¹d!}
{126}{}{Ale Coronado nale¿y do Blasku! Wynoœ siê z naszej ziemi, g³upku!}

#Ostateczny dialog
{200}{}{Hej, hej! Wszystko w porz¹dku? ZbudŸ siê!}
{201}{}{Co... Co siê sta³o?}
{202}{}{Zemdla³eœ po eksplozji. Ale wszystko wydaje siê w porz¹dku. Ba³em siê, ¿e nie dosta³eœ mojego zaproszenia.}
{1202}{}{Zemdla³aœ po eksplozji. Ale wszystko wydaje siê w porz¹dku. Ba³em siê, ¿e nie dosta³aœ mojego zaproszenia.}
{203}{}{By³a walka. Ktoœ rzuci³ chyba granatem i przez to straci³eœ przytomnoœæ. Ale wszystko wydaje siê w porz¹dku. Ba³em siê, ¿e nie dosta³eœ mojego zaproszenia.}
{1203}{}{By³a walka. Ktoœ rzuci³ chyba granatem i przez to straci³aœ przytomnoœæ. Ale wszystko wydaje siê w porz¹dku. Ba³em siê, ¿e nie dosta³aœ mojego zaproszenia.}
{204}{}{Kim ty jesteœ?}
{205}{}{Byæ mo¿e o mnie s³ysza³eœ. Ale to nie ma znaczenia. Cieszê siê, ¿e uda³o ci siê ukoñczyæ tê misjê.}
{1205}{}{Byæ mo¿e o mnie s³ysza³aœ. Ale to nie ma znaczenia. Cieszê siê, ¿e uda³o ci siê ukoñczyæ tê misjê.}
{206}{}{Myœlisz, ¿e podj¹³em w³aœciw¹ decyzjê?}
{1206}{}{Myœlisz, ¿e podjê³am w³aœciw¹ decyzjê?}
{207}{}{Nie zamierzam oceniaæ twojego wyboru. Zrobi³eœ, co uzna³eœ za stosowne.}
{1207}{}{Nie zamierzam oceniaæ twojego wyboru. Zrobi³aœ, co uzna³aœ za stosowne.}
{208}{}{[S³uchaj]}
{209}{}{}

{210}{}{Oczywiœcie, ghule bêd¹ strasznie zdenerwowane tym, ¿e nie dostan¹ technologii Starego Swiata.}
{211}{}{Mog³yby one wiele zrobiæ dla œwiata. Ale mog¹ te¿ wpaœæ w niepowo³ane rêce.}
{212}{}{Kto wie, mo¿e ta eksplozja uratowa³a œwiat przed kolejn¹ katastrof¹. Albo odwrotnie – to w³aœnie rzeczy z tej bazy zabraknie, aby cywilizacja wróci³a na w³aœciwe tory historii. Tak czy inaczej, bazy ju¿ nie ma. Tak samo jak starego konfliktu pomiêdzy ghulami.}

{220}{}{Oczywiœcie, wœród ghuli wybuchnie konflikt o prawa do technologii Starego Swiata.}
{221}{}{Gustavo spróbujê wzi¹æ wszystko dla siebie i wykorzystaæ to do rozwoju San Ysidro. Nie bêdzie dzieliæ siê z osiedlami ludzkimi, które równie¿ pilnie potrzebuj¹ przedwojennych techonologii. Butler bêdzie próbowa³ go powstrzymaæ.}
{222}{}{W koñcu Gustavo bêdzie silniejszy, przeci¹gnie wiêkszoœæ ghuli na swoj¹ stronê. A wtedy Blask Dnia rozpocznie swoje zwyk³e, nudne, spokojne ¿ycie, odcinaj¹c siê od reszty œwiata. Tak, jak chcia³o tego wiele ghuli.}
{223}{}{Gustavo spróbuje przej¹æ wszystko dla siebie i wykorzystaæ to do rozwoju San Ysidro. I nie podzieli siê tym z osadami ludzkimi, choæ i one pilnie potrzebuj¹ przedwojennych techonologii.}
{224}{}{Blask Dnia przywyknie do swojego ma³ego, ksenofobicznego, zamkniêtego trybu ¿ycia. Tak, jak chcia³o tego wiele ghuli.}

{230}{}{Oczywiœcie, wœród ghuli wybuchnie konflikt o prawa do technologii Starego Swiata.}
{231}{}{Butler zacznie intensywnie handlowaæ z osadami ludzkimi na pó³nocy. Dla niektórych z nich przedwojenne technologie bêd¹ zbawieniem, dla innych katastrof¹. San Ysidro dostanie okruszki, które zamieni¹ je w slumsy.}
{232}{}{Zasoby bêd¹ stopniowo siê wyczerpywaæ. Ale dziêki handlowi Blask Dnia przetrwa i bêdzie wiód³ swoje zwyk³e, ponure i spokojne ¿ycie. Tak, jak chcia³o tego wiele ghuli.}

{240}{}{Oczywiœcie, ghule bêd¹ strasznie zdenerwowane tym, ¿e fragmenty Starego Swiata nie s¹ ich.}
{241}{}{Bractwo Stali nie pozwoli nikomu zbli¿yæ siê do tej kopalni z³ota. Zakon zabierze dla siebie wszystko, co wartoœciowe i przetransportuje to do g³ównej bazy.}
{242}{}{Ghule zostan¹ z okruchami, przez co z czasem ludzie o nich zapomn¹. A wtedy Blask Dnia powróci do swojego zwyk³ego, nudnego ¿ycia.}

{250}{}{Oczywiœcie, wœród ghuli wybuchnie wielki konflikt o prawa do technologii Starego Swiata.}
{251}{}{Bez przywódców znalezienie równowagi si³ i interesów zajmie im du¿o czasu. Bêdzie to okres chaosu i zamêtu. W tym na pó³nocy, w osadach ludzkich.}
{252}{}{Niektóre przedwojenne technologie trafi¹ w dobre rêce, inne w z³e. Ghule dostan¹ najmniej. Ale s¹ do tego przyzwyczajone. Blask Dnia bêdzie tym, czym Nekropolis by³o przed odejœciem ghuli. NajwyraŸniej taki ju¿ ich los.}

{260}{}{No có¿. Moje sprawy tutaj dobieg³y koñca. Prawdopodobnie twoje te¿. Mi³o by³o ciê zobaczyæ. Zegnaj, amigo.}
{261}{}{Zegnaj nieznajomy.}
