{100}{}{Widzisz starego ghula.}
{101}{}{Widzisz przed sob¹ samotnego ghula. Gdyby nie jego przera¿aj¹co niszczej¹cy wygl¹d, wygl¹da³by ca³kiem przyjaŸnie.}
{102}{}{Stra¿ Graniczna ciê szuka. Nie pomogê ci.}
{103}{}{Jak dowiedzia³eœ siê o tajnym przejœciu? Nawet Tobias o nim nie wiedzia³!}
{1103}{}{Jak dowiedzia³eœ siê o tajnym przejœciu? Nawet Tobias o nim nie wiedzia³!}

#Znajomy
{200}{}{(Na pocz¹tku wygl¹da jak pomarszczone cia³o martwej osoby siedz¹cej na krzeœle. Jednak gdy siê zbli¿asz, cia³o powoli podnosi g³owê i mówi ochryp³ym g³osem) Dlaczego tu jesteœ, cz³owieku? }
{201}{}{Szukam sposobu, ¿eby dostaæ siê do Blasku Dnia.}
{202}{}{Nasze miasto jest otwarte tylko dla ghuli. Zywi nie maj¹ tam nic do roboty.}
{203}{}{Och, w takim razie naprawdê nie powinienem tam iœæ. Do widzenia.}
{204}{}{Nadal chcê siê tam dostaæ.}
{205}{}{Nie bêdê ciê od tego odwodziæ. Ale Tobias raczej nie przepuœci ciê przez granicê.}
{206}{}{W takim razie spróbujê go przekonaæ. Zegnaj, starcze.}
{207}{}{Czy istnieje inna droga?}
{208}{}{Wszystkie inne drogi s¹ niezwykle niebezpieczne. Ale nie ma potrzeby posuwaæ siê tak daleko. Znam jeden skrót. Mogê to zrobiæ, ale nie za darmo. Ile masz kapsli?}
{209}{}{Kapsli?}
{210}{}{A wiêc sugerujesz coœ, co jest oczywiœcie nielegalne. Nie mam zamiaru posuwaæ siê TAK daleko. Do widzenia.}
{211}{}{Kapsle! Kapsle! Wykorzystano je w Hub, aby zast¹piæ przedwojenne pieni¹dze. Ile masz kapsli od butelek?}
{212}{}{Nie mam ¿adnych kapsli.}
{213}{}{Nie mam ¿adnych kapsli.}
{214}{}{K³amiesz. Wiem, ¿e masz przy sobie kapsle. Sk¹d? (wskazuje na skroñ) Mam rentgena. Hehe, ¿art.}
{1214}{}{K³amiesz. Wiem, ¿e masz przy sobie kapsle. Sk¹d? (wskazuje na skroñ) Mam rentgena. Hehe, ¿art.}
#Uwaga: W³aœciwie to nie jest wizja rentgenowska, tylko przewodnik ghuli studiowal GG i jego rzeczy, spiac na jednym z parkingow.
{215}{}{Masz urojenia, staruszku. Lepiej ju¿ st¹d wyjdê.}
{216}{}{OK, oto wszystkie moje kapsle. A teraz zabierz mnie do miasta!}
{217}{}{A teraz - pochyl g³owê... Nie martw siê, zdejmê tê torbê, kiedy wyjdziemy na miasto. Zaufaj mi. Hehe, nie jesteœ pierwsz¹ osob¹, któr¹ zabieram przez granicê.}
{1217}{}{A teraz - pochyl g³owê... Nie martw siê, zdejmê tê torbê, kiedy wyjdziemy na miasto. Zaufaj mi. Hehe, nie jesteœ pierwsz¹ osob¹, któr¹ zabieram przez granicê.}
{218}{}{Uch... OK. Ale b¹dŸ ostro¿ny.}
{219}{}{Nie próbuj mnie oszukaæ, staruszku.}
{220}{}{Tak. G³upot¹ jest przekraczanie granicy bez pieniêdzy. I co ja mam teraz z tob¹ zrobiæ? OK, przynieœ mi trzy puszki starego, dobrego meksykañskiego piwa. Nadal mo¿na je znaleŸæ w ruinach na Revolution Avenue.}
{221}{}{Mam nadziejê, ¿e naprawdê tam s¹.}
{222}{}{A co z napromieniowan¹ Nuka-Col¹? W ruinach natkn¹³em siê na piêæ ca³ych butelek.}
{223}{}{Mam piêæ butelek nienapromieniowanej Nuka Coli. Mo¿e byæ?}
{224}{}{Oto trzy puszki starego piwa.}
{225}{}{Deal. Wygl¹da na to, ¿e nie ma ju¿ nic wiêcej do odebrania.}
{226}{}{No to zabierzesz mnie do miasta?}
{227}{}{Masz to, o co prosi³em?}
{228}{}{Nie. Mam poszukaæ jeszcze raz? Dobra, spróbujê jeszcze raz przejœæ siê przez ruiny.}
{1228}{}{Nie. Mam poszukaæ jeszcze raz? Dobra, spróbujê jeszcze raz przejœæ siê przez ruiny.}
{229}{}{}
{230}{}{Nadal nie mo¿esz przekroczyæ granicy, prawda? Znam jeden skrót. Mogê ci go pokazaæ, ale nie za darmo. Ile masz kapsli?}
{231}{}{Wychodzisz ju¿ z Blasku Dnia? Có¿, naprawdê powinieneœ.}
{232}{}{Czeœæ.}
{233}{}{(Widzisz starszego mê¿czyznê siedz¹cego na krzeœle; powoli podnosi g³owê, ods³aniaj¹c swoj¹ zniekszta³con¹ twarz; ochryp³ym przeci¹ganiem wo³a do ciebie) Ach, œwie¿a krew! Cieszê siê, ¿e ciê widzê w naszym martwym królestwie. Jeœli bêdziesz musia³ przekroczyæ granicê, porozmawiaj z Tobiasem, chêtnie ciê przepuœci.}
{234}{}{Tak zrobiê. Do widzenia.}
{235}{}{Kim jest Tobias?}
{236}{}{Tobias jest stra¿nikiem bram. Mo¿na powiedzieæ, ¿e jest ³¹cznikiem pomiêdzy œwiatem ¿ywych i umar³ych.}