{102}{}{Widzisz emiter, ten jest pozbawiony zasilania.}
{103}{}{Widzisz emiter, ten jest teraz bezu¿yteczny.}
{104}{}{Widzisz emiter, ten jest powa¿nie uszkodzony.}
{105}{}{Uda³o ci siê rozwi¹zaæ problem. Emiter jest ponownie gotowy do u¿ycia.}
{106}{}{Emiter uszkodzony!}
{107}{}{Potê¿ny impuls wnika w ziemiê i rozprzestrzenia siê, uszkadzaj¹c ca³¹ elektronikê na swojej drodze.}
{108}{}{Emiter uszkodzony.}
{109}{}{Emiter jest ju¿ na³adowany.}
{110}{}{Ladujesz bateriê nadajnika.}
{111}{}{Ten emiter przepali³ siê pod w³asnym napiêciem po ostatnim u¿yciu.}
