{100}{}{Widzisz automat do gier.}
{101}{}{Widzisz automat typu arcade. Ponadczasowa klasyka.}
{102}{}{Musisz zap³aciæ, aby rozpocz¹æ grê. Aktualny zapis: }
{103}{}{ (Nieznane).}
{104}{}{ (}
{105}{}{).}

{200}{}{"Twój statek kosmiczny zmierza do centrum galaktyki. Uwa¿aj! Przed tob¹ gromada asteroid! Unikaj ich w górê i w dó³ lub wypuszczaj pociski plazmowe w celu ich zniszczenia. Im d³u¿ej wytrzymasz, tym wiêcej punktów zdobêdziesz!"}
{201}{}{Dalej!}
{202}{}{Przeczytaj zasady.}
{203}{}{Odmów i weŸ pieni¹dze.}
{204}{}{Odmów.}

{210}{}{Steruj statkiem kosmicznym ( }
{211}{}{), aby unikn¹æ uderzenia w asteroidy (}
{212}{}{). Zderzenie z asteroid¹ zabiera jedno ¿ycie. Mo¿esz omin¹æ asteroidê w górê lub w dó³, ale tylko w promieniu trzech linii.}
{213}{}{}
{214}{}{Mo¿esz tak¿e zbieraæ punkty podczas lotu (}
{215}{}{) i ³adunki plazmowe (}
{216}{}{). Jeden ³adunek niszczy jedn¹ przeszkodê, a superpocisk niszczy ca³a liniê przed tob¹. Powodzenia w zachowaniu ¿ycia (}
{217}{}{).}
{218}{}{Zamknij pomoc.}
{219}{}{Dalej.}

#nie usuwaj spacji w wierszach!
{220}{}{-|>  }
{221}{}{ [X] }
{222}{}{ -o- }
{223}{}{ -z- }
{224}{}{ ---}
{225}{}{ -Y-}
{226}{}{) }
{227}{}{ -Z-}
{228}{}{(}

{230}{}{W górê}
{231}{}{Dalej.}
{232}{}{W dó³.}
{233}{}{-W górê-}
{234}{}{-W dó³-}
{235}{}{Pocisk! (}
{236}{}{-Pocisk-}
{237}{}{Superpocisk!}
{238}{}{)}
{239}{}{Eksplozja! (}

{240}{}{Pauza.}
{241}{}{Gra zosta³a zatrzymana. Zycia: }
{242}{}{. Oplaty: }
{243}{}{. Punkty: }
{244}{}{. Twój rekord: }
{245}{}{.}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{-Eksplozja-}

{250}{}{Wznów grê.}
{251}{}{Zakoñcz grê.}
{252}{}{Czy na pewno chcesz zakoñczyæ grê i straciæ zgromadzone punkty (}
{253}{}{)?}
{254}{}{Wróæ i graj dalej.}
{255}{}{Tak. Zakoñcz grê.}
{256}{}{Przegrywasz!}
{257}{}{G³upia gra! Nie zagram w to ponownie.}
{258}{}{OK. Nastêpnym razem wytrzymam d³u¿ej.}
{259}{}{}

{260}{}{}
{261}{}{Odmów. Nie chce ¿adnej z tych nagród.}
{262}{}{Si³a +1.}
{263}{}{Percepcja +1.}
{264}{}{Wytrzyma³oœæ +1.}
{265}{}{Charyzma +1.}
{266}{}{Intelekt +1.}
{267}{}{Zrêcznoœæ +1.}
{268}{}{Szczêœcie +1.}
{269}{}{Hazard +20.}
{270}{}{"Zwyciêstwo! Pobijasz swój w³asny rekord. Czy chcesz kontynuowaæ?"}
{271}{}{Tak.}
{272}{}{Nie.}
{273}{}{W³¹cz tryb przetrwania.}
{274}{}{Wy³¹cz tryb przetrwania.}
{275}{}{}
{276}{}{"Zwyciestwo! Pobijasz rekord i zostajesz niekwestionowanym mistrzem."}
{277}{}{Swietnie!}
{278}{}{Wreszcie.}
{279}{}{"Odbierz kupon z nagrod¹."}
{280}{}{"Teraz mo¿esz graæ na tej maszynie za darmo. Ale to nie wszystko. Jeœli gra jest dla Ciebie zbyt ³atwa, mo¿esz spróbowaæ trybu przetrwania. Powodzenia w kosmosie!"}
{281}{}{Dobrze.}
{282}{}{Co dalej?}
{283}{}{W trybie przetrwania przejœcia linii (w górê i w dó³) licza siê jako krok lotu. Dlatego musisz zapamiêtaæ stan rzeczy na liniach i przemyœleæ swoje ruchy z wyprzedzeniem.}
{284}{}{Przeczytaj wiêcej.}
{285}{}{Rozumiem.}
{286}{}{Ale na pocz¹tku dostajesz dwa razy wiêcej ¿yæ i salw, œcie¿ka jest widoczna 2 kroki dalej, a wybuchowa salwa niszczy zarówno asteroidê z przodu, jak i na s¹siednich pasach.}
{287}{}{Dodatkowo zyskujesz 1 punkt za ka¿dy etap gry. Mo¿esz wymieniæ swoje punkty.}
{288}{}{}
{289}{}{}

{290}{}{Wymieñ punkty.}
{291}{}{Masz }
{292}{}{ punktów.}
{293}{}{Wznów grê.}
{294}{}{1 salwa za }
{295}{}{1 supersalwa za }
{296}{}{1 ¿ycie za }
{297}{}{.}
{298}{}{Mo¿liwoœæ poznania tras do nastêpnej tury za }
