{100}{}{Widzisz komputer podstacji.}
{101}{}{Widzisz komputer steruj¹cy podstacj¹.}
{102}{}{Komputer siê nie w³¹cza.}
{103}{}{Prawdopodobnie nie dociera tu energia.}

{200}{}{System dzia³a normalnie. Wpisz polecenie.}
{201}{}{Zostaw komputer w spokoju.}
{202}{}{Stan elektrowni?}
{203}{}{Elektrownia nie odpowiada.}
{204}{}{Stan stacji?}
{205}{}{Podstacja nie odpowiada.}
{206}{}{Wstecz.}
{207}{}{W³¹cz œwiat³a na terenie stacji.}
{208}{}{W³¹cz œwiat³a.}
{209}{}{W³¹cz oœwietlenie wewnêtrzne wokó³ stacji.}
{210}{}{Swiat³a wewnêtrzne w³¹czone.}
{211}{}{Anuluj syrenê generaln¹.}
{212}{}{Syrena generalna odwo³ana.}
{213}{}{Anuluj alarm bojowy.}
{214}{}{Uwaga! Tryb ostrzegania zosta³ anulowany. Wszystkie roboty bezpieczeñstwa otrzymuj¹ polecenie przyjêcia programu pokojowego.}
{215}{}{Wyœlij roboty naprawcze, ¿eby naprawi³y sieæ kolejki jednoszynowej.}
{216}{}{Zasilanie przywrócone.}
