{110}{}{Tu potrzeba brutalnej si³y.}
{111}{}{Ten zawór jest zamkniêty. Nie masz doœæ si³y by obróciæ go nawet o kilka stopni.}
{112}{}{Uderzenie w rurê wyda³o g³oœny dŸwiêk. Mo¿e teraz uda siê przekrêciæ ten cholerny zawór.}
{113}{}{Jeszcze tylko trochê!}
{114}{}{Musisz siê bardziej postaraæ!}
{115}{}{Wygl¹da na to, ¿e zawór przekrêci³ siê o pó³ ca³a.}
{116}{}{Wygl¹da na to, ¿e zawór zaczyna ci ulegaæ.}
{117}{}{Zawór otwarty.}
{118}{}{Uch!}
{119}{}{Uch!}
{120}{}{Ach!}