{200}{}{Wpisz polecenie.}
{201}{}{Zakoñcz sesjê.}
{202}{}{Wstecz.}
{203}{}{Dalej.}
{204}{}{Ten system jest dla ciebie zbyt skomplikowany.}
{205}{}{By³oby mi³o znaleŸæ podrêcznik...albo instrukcjê.}
{206}{}{To tu nie pomo¿e. Tutaj potrzebna jest wiedza.}
{207}{}{Teraz wiesz, co robiæ.}
{208}{}{Hej, to nie jest takie trudne!}
{209}{}{Ta technika jest zbyt skomplikowana. Tutaj trzeba wiedzieæ co robiæ i lepiej siê przyjrzeæ.}

{210}{}{Sprawdzanie stanu systemu.}
{211}{}{Stan pierwszej turbiny.}
{212}{}{Turbina 1: brak sygna³u.}
{213}{}{Turbina 1: aktywna.}
{214}{}{Stan drugiej turbiny.}
{215}{}{Turbina 2: brak sygna³u.}
{216}{}{Turbina 2: aktywna.}
{217}{}{Sprawdzanie podstacji.}
{218}{}{Podstacja: nie odpowiada. }
{219}{}{Podstacja: sprawna. }
{220}{}{Skieruj zasilanie do podstacji.}
{221}{}{Gotowe.}
{222}{}{Podstacja nie odpowiada.}
{223}{}{W³¹cz œwiat³a w maszynowni.}
{224}{}{Wy³¹cz œwiat³a w maszynowni.}
{225}{}{W³¹cz oœwietlenie w centrum sterowania.}
{226}{}{Wy³¹cz œwiat³a w centrum sterowania.}
{227}{}{Otwórz drzwi do magazynu.}
