{100}{}{Widzisz wy³¹cznik bezpieczników.}
{101}{}{Zgodnie z instrukcj¹ ten wy³¹cznik jest w jakiœ sposób powi¹zany w przesy³anie pr¹du do podstacji.}
{110}{}{Przesuwasz dŸwigniê, ale nic siê nie dzieje.}
{111}{}{Teraz nie ma takiej potrzeby.}
{112}{}{Prze³¹czasz prze³¹cznik. Rozbrzmiewa echo utrzymuj¹cego siê szumu, który s³ychaæ teraz w wiêkszoœci przewodów.}
{113}{}{Prze³¹czasz prze³¹cznik. Tablica obok niego zapala siê i pojawia siê napis „przerwanie obwodu”.}