{100}{}{Widzisz punkt zbiórki, mo¿na st¹d wyruszyæ do Sonory.}
{101}{}{Za pomoc¹ tego oto punktu mo¿esz wróciæ na Pustkowia Sonory.}

{110}{}{To miejsce zbiórki.}
{111}{}{[Poczekaj na przewodnika i wróæ na Pustkowia Sonory.]}
{112}{}{[Wróæ samotnie na Pustkowia Sonory.]}
{113}{}{[Pozostañ w Blasku Dnia. Sonora zaczeka.]}
{114}{}{Na pewno? Nie wrócisz tu.}
{115}{}{Tak, chcê wróciæ.}
{116}{}{Nie, zostajê w Blasku.}
{117}{}{Mo¿esz zabraæ ze sob¹ maksymalnie 100 funtów ³adunku.}
{118}{}{[IdŸ samodzielnie do Blasku Dnia.]}
{119}{}{[Pozostañ na pustkowiach Sonory.]}