{100}{}{Teraz mo¿esz zejœæ w ciemnoœæ.}
{101}{}{Trudno powiedzieæ, dlaczego nie ma tu schodów. Ale ich nie ma.}
{102}{}{Nie mo¿na naprawiæ czegoœ, czego nie ma. Ale mo¿na to wymieniæ.}
{103}{}{Za kratami widoczny jest g³êboki szyb wentylacyjny.}
{104}{}{Nie ma tu nic do naprawy. Wrêcz przeciwnie, otwór w kratce mo¿e siê przydaæ.}
{105}{}{Tego mostu nie da siê naprawiæ. Ale mo¿na by zejœæ po odpowiednio przymocowanej linie.}
{106}{}{Nie mo¿esz tu nic zrobiæ go³ymi rêkami.}
{107}{}{Mo¿esz teraz zejœæ na dó³.}
{108}{}{Mo¿esz tu zejœæ za pomoc¹ wystarczaj¹co d³ugiej i mocnej liny.}