{100}{}{Widzisz maszynê drukarsk¹.}
{101}{}{Widzisz komputer pod³¹czony do prasy drukarskiej.}
{102}{}{Czytanie artyku³ów z ubieg³ego stulecia wzbogaci³o ciê o nowe doœwiadczenia.}

#Dialog
{200}{}{Dostêp przyznany. Wpisz polecenie.}
{201}{}{Zakoñcz sesjê.}
{202}{}{Wstecz.}
{203}{}{Dalej.}
{204}{}{Wróæ do menu g³ównego.}
{205}{}{Anuluj.}

{210}{}{Przeczytaj nag³ówki ostatnich artyku³ów.}
{211}{}{Artyku³y prasowe.}
{212}{}{Wiadomoœci biznesowe.}
{213}{}{"Meksyk otrzyma³ now¹ partiê robotów Mr. Handy. Przypominamy, ¿e roboty te okaza³y siê nieocenione po ostatnich du¿ych trzêsieniach ziemi."}
{214}{}{Wiadomoœci gospodarcze.}
{215}{}{"Trzeci cud gospodarczy w Meksyku. Po aneksji Meksyku znajduje siê tu siedziba ogromnej liczby amerykañskich ga³êzi przemys³u. Srodowisko uleg³o pogorszeniu, ale kraj zacz¹³ siê bogaciæ."}
{216}{}{Wiadomoœci bran¿owe.}
{217}{}{"Na Morzu Cartesa koñczy siê ropa. Wiele platform wiertniczych zosta³o ju¿ zamkniêtych. Pozosta³e platformy bêd¹ dzia³aæ jeszcze przez oko³o dziesiêæ lat, wypompowuj¹c resztê czarnego z³ota."}
{218}{}{Opinia eksperta.}
{219}{}{„Czy Meksyk stoi w obliczu wojny nuklearnej? Opinie ekspertów.”}
{220}{}{„Oczywiœcie Stany Zjednoczone nie grozi³yby Meksykowi broni¹ nuklearn¹. Ale sam Meksyk ma te¿ innych s¹siadów, którzy marz¹ o przejêciu jego zasobów i wód.”}
{221}{}{"Po aneksji Stany umieœci³y w Meksyku wiele fabryk i strategicznych instalacji. Pewne jest, ¿e wrogowie USA bêd¹ chcieli je wyeliminowaæ w przypadku wojny. I to bêdzie nie tyle cios w USA, co w Meksykanów.”}
{222}{}{Zapisy policyjne.}
{223}{}{„Meksyk nabywa od Stanów Zjednoczonych lekki pancerz wspomagany do celów operacji specjalnych w obszarze swoich granic l¹dowych.”}
{224}{}{Raporty kryminalne.}
{225}{}{"Wczeœniej zdelegalizowana partia sympatyzuj¹ca z Chinami i Zwi¹zkiem Radzieckim zosta³a zlikwidowana w Meksyku. S¹ ofiary wœród ludnoœci cywilnej."}
{226}{}{Plakat.}
{227}{}{"Nie przegap tego! Niezapomniany wystêp legendarnego zespo³u Mariachi Jose Solisa czeka na Ciebiê! Ju¿ w tê niedzielê!"}
