{110}{}{Z wentylacji dochodzi jakiœ ha³as. Coœ musi przeszkadzaæ wentylacji.}
{111}{}{Wentylacja w koñcu odpuœci³a. Spoczywaj w pokoju, dziecko rewolucji przemys³owej.}
{112}{}{Zeskrobujesz mnóstwo toksycznego popio³u z otworu wentylacyjnego. Dziêki temu wentylator przesta³ wydawaæ przera¿aj¹ce dŸwiêki.}
{120}{}{*ssh-sh-sh*}
{121}{}{*syksyk*}
{122}{}{*wrwrwr*}
{123}{}{*rrrr*}
{124}{}{*hrrr*}