{100}{}{Widzisz podstacjê.}
{101}{}{Widzisz podstacjê elektryczn¹. Biegn¹ od niej przewody w stronê kolei jednoszynowej.}
{102}{}{Widzisz podstacjê elektryczn¹. Niestety nie masz pojêcia, po co to tu jest.}
{103}{}{Wygl¹da na to, ¿e jest to ta sama podstacja, która ma zasilaæ kolej jednoszynow¹.}
{104}{}{Do kolei jednoszynowej znów dociera pr¹d.}
{105}{}{Przywrócono zasilanie kolei jednoszynowej.}
{106}{}{Podstacja nie dzia³a. Brakuje jej pr¹du z elektrowni.}