{100}{}{Widziesz Stanleya.}
{101}{}{Widzisz okropnie koœcistego ghula w brudnych, zniszczonych szatach. Z jego g³owy wystaje kawa³ek prêta zbrojeniowego.}
{102}{}{Witaj, bia³y. Nie wygl¹dasz ju¿ jak prawdziwy duch.}

{200}{}{Aaah, nie zabieraj mnie, ja wci¹¿ chcê ¿yæ!}
{201}{}{O czym ty mówisz?}
{202}{}{O czym ty do cholery mówisz?!}
{203}{}{Och, mamusiu, ty jesteœ cz³owiekiem?! Uff, pomyli³em ciê z duchem. Dlaczego mnie straszysz?}
{204}{}{O to samo mogê ciê zapytaæ. Chodzisz tu ca³y czarny w ciemnoœci, tylko oczy ci œwiec¹!}
{205}{}{Wybacz, bia³og³owy, ale tak siê ba³em! Wiesz, na tych stacjach jest tak samotnie. Kiedyœ kr¹¿y³y pog³oski o pojeŸdzie widmo, który zabiera³ dusze ludzi do piek³a. Teraz nie ma znaczenia czy w to wierzysz. Ju¿ jesteœmy w piekle.}
{206}{}{Przepraszam, to przez przypadek. Ja te¿ nie spodziewa³em siê, ¿e kogoœ tu spotkam.}
{1206}{}{Przepraszam, to przez przypadek. Ja te¿ nie spodziewa³am siê, ¿e kogoœ tu spotkam.}
{207}{}{Te stacjê by³y kiedyœ pe³ne ludzi. Teraz jest tu naprawdê pusto. Poci¹g widmo musia³ ju¿ zabraæ wszystkich do piek³a. Nie wierzysz? Racja, ju¿ jesteœmy w piekle.}
{208}{}{Wiêc, co ty tu w ogóle robisz?}
{209}{}{Moi bracia poprosili mnie o przygotowanie Niebieskiej Linii do startu. Pracowa³em kiedyœ w metrze, wiêc mogê coœ tu zrobiæ. Ale nie wszystko.}
{210}{}{Czego potrzebujesz do uruchomienia tego metra?}
{211}{}{Po pierwsze, nie mamy jeszcze pr¹du. Zdaje siê, ¿e mo¿na go "dostaæ" tylko przy elektrowni wodnej Bonita, a ona od czasów wojny jest dobrze strze¿ona. I trzeba nie tylko uruchomiæ stacjê, ale tak¿e skierowaæ pr¹d do podstacji kolei jednoszynowej.}
{212}{}{A po drugie?}
{213}{}{Po drugie, musimy naprawiæ liniê jednoszynow¹. Zrobi¹ to za nas Panowie R¹czka gdy uruchomimy energiê. W tym celu zdemontuj¹ czêœæ starych linii. Ale automatykê zajezdni bêdziemy musieli naprawiæ sami. I tutaj nie mogê obejœæ siê bez doœwiadczonego specjalisty w dziedzinie elektroniki. To coœ jest w sterowni. Mo¿e technik z San Ysidro potrafi to naprawiæ, jeœli to dla ciebie za ciê¿kie. Pomo¿esz mi?}
{214}{}{Oczywiœcie. Bo wtedy ja te¿ bêdê móg³ skorzystaæ z kolei jednoszynowej.}
{215}{}{Zrobiê wszystko, ¿eby u³atwiæ wam ¿ycie.}
{216}{}{Swietnie! Pomó¿ mi, a ja podzielê siê czêœci¹ honorarium, które obieca³a mi administracja miasta.}
{217}{}{Dobrze. Do zobaczenia.}
{218}{}{Zanim zacznê, zadam ci kilka pytañ.}

{220}{}{Co powiesz?}
{221}{}{Na co siê gapisz, bia³y?}
{1221}{}{Na co siê gapisz, blada panno?}
{222}{}{Hej, to mój blady brat! Jak siê masz?}
{1222}{}{Hej, to moja blada siostra! Wszystko w porz¹dku?}
{223}{}{Czeœæ. Do zobaczenia.}

{230}{}{Co to jest kolej jednoszynowa?}
{231}{}{Naprawdê nie wiesz? Cholera! Dawno, dawno temu po tych szynach jeŸdzi³y poci¹gi. Ale by³o fajnie. Pomó¿ mi naprawiæ liniê, a zobaczysz to na w³asne oczy.}
{232}{}{Rozumiem.}
{233}{}{Co muszê zrobiæ, ¿eby ten poci¹g pojecha³?}
{234}{}{Musimy najpierw w³¹czyæ podstacjê Niebieskiej Linii. Brak tu pr¹du. A potem naprawiæ elektronikê w sterowni. Jeœli nie masz umiejêtnoœci, zanieœ sprzêt do technika w San Ysidro.}
{235}{}{OK.}
{236}{}{Nie przeszkadza ci to coœ w twojej g³owie?}
{237}{}{Coœ? Aha, mówisz o prêcie. Wystaje z tej g³owy od stu lat. Jest w porz¹dku, jestem do tego przyzwyczajony. Ale lepiej go nie wyci¹gaæ.}
{238}{}{OK. Tak jak mówisz.}
{239}{}{To cud! Szczerze mówi¹c myœla³em, ¿e nic nie bêdzie dzia³aæ. To tak niesamowite, ¿e nie mogê w to uwierzyæ. Przywracasz mi nadziejê w ludzi. Mo¿e jeszcze nie wszystko dla was stracone.}
{240}{}{Mo¿e.}
{241}{}{Nie robiê tego dla ciebie.}
{242}{}{Chyba powinienem podzieliæ siê z tob¹ zap³at¹ - oto 1000 kapsli. I dziêki... przyjacielu.}
{1242}{}{Chyba powinienem podzieliæ siê z tob¹ zap³at¹ - oto 1000 kapsli. I dziêkujê... przyjació³ko.}
{243}{}{Nie ma za co... przyjacielu.}
{244}{}{Chyba powinienem podzieliæ siê z tob¹ zap³at¹ - oto 1000 kapsli. I dziêkujê... partnerze.}
{245}{}{Nie ma za co... partnerze.}
{246}{}{Chyba powinienem podzieliæ siê z tob¹ zap³at¹ - oto 500 kapsli. I dziêkujê... partnerze.}
{247}{}{To wszystko? Ok, ale nie jesteœ ju¿ moim „partnerem”.}
