{100}{}{Te drzwi nie mog¹ byæ zamkniête.}
{101}{}{Linia jednoszynowa nie ma pr¹du. Tramwaj nigdzie nie pojedzie.}
{102}{}{Tramwaj z jakiegoœ powodu sam nie jedzie. Coœ musia³o siê zepsuæ.}
{103}{}{Po prawie stu latach kolej jednoszynowa znów dzia³a!}
{104}{}{Kolej jednoszynowa dzia³a.}

{110}{}{"Kolej metra San Diego przesy³a pozdrowienia. Usi¹dŸ wygodnie i poczekaj na swój odjazd."}
{111}{}{[WyjdŸ z tramwaju]}
{112}{}{[Wysi¹dŸ na stacji San Ysidro]}
{113}{}{[Wysi¹dŸ na stacji Chula Vista Center]}
{114}{}{[Wysi¹dŸ na stacji Broadway]}
{115}{}{[Wysi¹dŸ na stacji Old City]}