{110}{}{Widzisz radio, nadal jest w³¹czone.}
{111}{}{Widzisz radio, ostatnio by³o wy³¹czone.}
{112}{}{Ten sprzêt nie wymaga naprawy. Ale bez anteny jest bezu¿yteczny. Na razie go zostaw.}
{113}{}{Zdobywasz wzmacniacz i inne czêœci potrzebne w San Ysidro.}
{114}{}{Wyposa¿enie tego radia dzia³a. Ale z jakiegoœ powodu sygna³ nie jest transmitowany.}
{115}{}{To nie ma sensu. Radio ma problemy z nadawaniem.}