{110}{}{Widzisz dzia³aj¹c¹ stacjê radiow¹. Dzia³a dziêki Tobie.}
{111}{}{Ten sprzêt dzia³a na pe³nych obrotach.}
{112}{}{To radio jest u¿ywane przez ghule do komunikowania siê z reszt¹ Blasku.}
{113}{}{Ten sprzêt nie wymaga naprawy.}
{114}{}{Dajesz sygna³ wszystkim robotom granicznym San Ysidro, aby siê usunê³y.}
{115}{}{Zg³aszasz nowy transponder do bazy wojskowej. System daje pozwolenie na zejœcie na l¹d.}
{116}{}{Brak zasilania.}