{110}{}{Ten sprzêt nie dzia³a.}
{111}{}{Ten sprzêt dzia³a na pe³nych obrotach.}
{112}{}{Wymieniasz uszkodzone czêœci. Stacja radiowa znów dzia³a.}
{113}{}{To nie zast¹pi zniszczonych czêœci.}
{114}{}{To radio jest nieczynne.}
{115}{}{ Nie masz pojêcia, ile k³opotów zaoszczêdzi nam to radio. Dziêkujê.}
{116}{}{ Kucha jest wiêkszy i ma mniej rozumu. Kucha nigdy nie by³by w stanie tego naprawiæ.}