{200}{}{Stacja jest gotowa do pracy. Pobierz materia³y robocze i przypisz program przetwarzania.}
{201}{}{Wy³¹cz stacjê.}
{202}{}{Wstecz.}
{203}{}{Tê broñ nale¿y od³o¿yæ.}

{210}{}{Potrzebne materia³y: }
{211}{}{, }
{212}{}{.}
{213}{}{Za³aduj materia³y i uruchom program.}
{214}{}{Program zosta³ zamkniêty. Wyjmij produkt z tacy.}
{215}{}{Wy³¹cz stacjê.}
{216}{}{Wróæ do listy ogólnej.}
{217}{}{Anuluj i wróæ do listy ogólnej.}
{218}{}{Za ma³o materia³ów.}
{219}{}{Wróæ do ostatniej sekcji.}
{220}{}{Otrzymano: }
{221}{}{, }
{222}{}{ szt.}
{223}{}{Sekcja napraw.}
{224}{}{Sekcja chemii.}
{225}{}{Sekcja amunicji.}
{226}{}{}

{250}{}{Domowe kapsle do butelek.}
{251}{}{Domowej roboty antyrady.}
{252}{}{Domowej roboty stymulanty.}
{253}{}{Domowej roboty antidotum.}
{254}{}{Paliwo do miotacza ognia.}
{255}{}{Bomba zapalaj¹ca.}
{256}{}{Granat pulsacyjny.}

{260}{}{Przekszta³æ materia³ we flary.}
{261}{}{Wzmocnij zwyk³¹ amunicjê sygna³ow¹ do poziomu 1 (2 do 1).}
{262}{}{Wzmocnij normalne flary sygna³owe do poziomu 2 (3 do 1).}
{263}{}{Wzmocnij amunicjê sygnalizacyjn¹ poz. 1 do poz. 2 (2 do 1).}
{264}{}{Zamieñ nabój œrutowy na nabój kulowy.}
{265}{}{Zamieñ nabój kulowy na nabój œrutowy.}

{270}{}{Usuñ brud z plakietki patrolu.}
{271}{}{Wymieñ kryszta³ pistoletu laserowego.}
{272}{}{Napraw modu³ steruj¹cy kolejk¹ jednoszynow¹.}

