{110}{}{Automat wydaje towary wy³¹cznie za pieni¹dze.}
{111}{}{Ten automat zosta³ ju¿ zhakowany.}
{112}{}{}
{113}{}{Zamek jest zbyt skomplikowany.}
{114}{}{Zastosowano wytrych. Teraz ³atwiej bêdzie ci wy³amaæ ten zamek.}
{115}{}{Zamek ma ju¿ maksymaln¹ liczbê wytrychów.}
{116}{}{Dekoder elektroniczny nie nadaje siê do otwierania zamków mechanicznych.}
{117}{}{Otwierasz automat z towarami. Czas zobaczyæ, co zosta³o w œrodku.}
{118}{}{Teraz, gdy maszyna jest otwarta, to nie ma sensu.}
{119}{}{Kupujesz: }
{120}{}{W automacie nie ma ju¿ zapasów.}
{121}{}{ szt.}
{122}{}{Nie potrafisz omin¹æ zabezpieczeñ automatu.}