{100}{}{Widzisz firmowy komputer.}
{101}{}{Widzisz komputer po³¹czony z baz¹ danych Krypty.}
{102}{}{Przestudiowanie historii Krypty zwiêkszy³o twoje doœwiadczenie.}

#Dialog
{200}{}{Dostêp przyznany. Wpisz polecenie.}
{201}{}{Zakoñcz sesjê.}
{202}{}{Wstecz.}
{203}{}{Dalej.}
{204}{}{Wróæ do menu g³ównego.}
{205}{}{Anuluj.}

{210}{}{Przeczytaj raporty bezpieczeñstwa.}
{211}{}{Wybierz okres raportowania.}
{212}{}{Luty 2131.}
{213}{}{"Zebraliœmy najnowsze dane od grup zwiadowczych."}
{214}{}{"Zespó³ Alfa wys³any do centrum San Diego nie ma ³¹cznoœci. Ostatnia wiadomoœæ dotyczy³a wysokiego poziomu promieniowania i rozleg³ego zniszczenia œrodowiska miejskiego."}
{215}{}{"Zespó³ Beta badaj¹cy wybrze¿a wróci³ wczeœniej, nawet nie zbada³ wyznaczonej po³owy. Zg³oszono wysoki poziom promieniowania i rozleg³e zniszczenia. Wszystkie mosty na wyspê Coronado zniszczone, wszystkie statki wojskowe i cywilne na nabrze¿ach zatopione lub powa¿nie uszkodzone. Wysoka aktywnoœæ robotów wzd³u¿ brzegu, pochodz¹ prawdopodobnie z bazy wojskowej. Cz³onkowie grupy zachorowali na chorobê popromienn¹."}
{216}{}{"Zespó³ Gamma badaj¹cy po³udniowe regiony powróci³ z niewielk¹ iloœci¹ przydatnych przedmiotów i przedwojennych zapasów. Zg³oszono umiarkowane uszkodzenia i zwiêkszone promieniowanie."}
{217}{}{"Zespó³ Delta badaj¹cy obszar wschodni donosi o zmniejszonym promieniowaniu w g³êbi l¹du i niewielkich zniszczeniach. Znaleziono zwierzêta o nietypowym kszta³cie i rozmiarze. Czêœæ zespo³u zginê³a."}
{218}{}{"Zadnej z grup nie uda³o siê znaleŸæ ¿ywych ludzi ani dowodów na ich niedawn¹ obecnoœæ."}
{219}{}{Wróæ do listy ogólnej.}
{220}{}{Kwiecieñ 2131.}
{221}{}{"Zespó³ Zeta wróci³ z oœrodka naukowego West-Tek. Z ca³ej grupy prze¿y³a jedna osoba. Osoba, która prze¿y³a, zg³asza niezwykle wysoki poziom promieniowania i zniszczeñ w kompleksie. Znaleziono nieznane nam roboty stra¿nicze i zwierzêta o nietypowej budowie."}
{222}{}{"Badanie lekarskie wykaza³o, ¿e zwiadowca cierpi na ciê¿k¹ chorobê popromienn¹ oraz niezwyk³e mutacje i oczekuje siê, ¿e wkrótce umrze. Dalsze badanie kompleksu West-Tek nie jest zalecane."}
{223}{}{Maj 2132.}
{224}{}{"Zespó³ Epsilon wróci³ z Los Angeles. Zespó³ donosi o szeregu ma³ych spo³ecznoœci i obozów, z których najwiêkszy nazywa siê Adytum. Jest domem dla ocala³ych z wojny nuklearnej w ró¿nych miejscach na po³udniu Kalifornii. Ci ludzie ¿yj¹, zbieraj¹c przedwojenne przedmioty z ruin, a nastêpnie handluj¹c nimi.”}
{225}{}{"Doniesiono tak¿e o du¿ym mieœcie zwanym Hub na pó³noc od Adytum, ale niewiele o nim wiadomo."}
{226}{}{"Zwiadowcy dochodz¹ do sprzecznych wniosków na temat miejscowej ludnoœci. Czêœæ grup boi siê obcych, czêœæ wykazuje chêæ po³¹czenia siê z nimi w jedn¹ osadê. Prawdopodobnie wielu zwiadowców prze¿ywa szok kulturowy." }