{110}{}{    }
{111}{}{Odbiór, bracie.}
{112}{}{Uda³o im siê. Ghule rzeczywiœcie uruchomi³y elektrowniê.}
{113}{}{Wy idioci! Teraz mamy mniej czasu na przygotowania.}
{114}{}{Mo¿e weŸmiemy tamê? Pozostawianie takiej w³adzy w ich rêkach nie jest dobrym pomys³em...}
{115}{}{Nie, to tylko odwróci nasz¹ uwagê od g³ównego celu.}
{116}{}{Poza tym ghule potrzebuj¹ stacji dla miasta. Nie s¹dzê, ¿eby mieli j¹ wykorzystaæ do zrobienia czegoœ z³ego.}
{117}{}{Musimy dzia³aæ proaktywnie. Wracamy do bazy. Wszystko wymaga omówienia.}