{100} {} {Widzisz Alejo.}
{101} {} {Widzisz pó³nagiego mê¿czyznê o szalonym wygl¹dzie. Macha groŸnie maczet¹.}

{110} {} {Umrzyj, stworzenie!}
{111} {} {Viper!}
{112} {} {Zosta³em porwany! Zosta³em porwany!}
{113} {} {Alex! Czasy! Moskwa!}
{114} {} {Bêdziesz raportowaæ bezpoœrednio do mnie.}
{115} {} {To bêdzie moja odpowiedŸ dla drani.}
{116} {} {Chodzi³em tutaj, zbiera³em jedzenie, nikogo nie dotyka³em.}
{117} {} {Obserwuj¹ mnie!}
{118} {} {Co, meksykañskie szumowiny zabra³y wózek?}
{119} {} {Zamieszki i œmieræ! Zamieszki i œmieræ!}
{120} {} {Nakarmiê ciê granatnikiem.}
{121} {} {Wt! Murda!}
{122} {} {Ma³py tu spaceruj¹, tam jest ma³pa.}
{123} {} {Proszê, pedale!}
{124} {} {Ooh!}
{125} {} {Kocham zwierzêta.}
