{100} {} {Widzisz zwiadowcê.}
{101} {} {Widzisz zwiadowcê Bractwa Stali.}

{110} {} {Co robisz na tej pustyni?}
{111} {} {Najbli¿sze miasto jest na pó³nocnym wschodzie.}
{112} {} {Te ziemie s¹ pod ochron¹ Bractwa.}
{113} {} {Nie bêdziemy Ciê ruszaæ, dopóki akceptujesz nasze warunki.}

{120} {} {Witaj z powrotem, bracie.}
{121} {} {Jak droga, bracie?}
{122} {} {Co nowego na pustkowiach, bracie?}
{123} {} {Przepraszam, ale nie mo¿emy eskortowaæ ciê do bazy.}

{1120} {} {Witamy z powrotem, siostro.}
{1121} {} {Jak droga, siostro?}
{1122} {} {Co nowego na pustkowiach, siostro?}
{1123} {} {Przepraszam, ale nie mo¿emy eskortowaæ ciê do bazy.}