# Normalne losowe liniê
# Wa¿ne: zostaw repliki ze spacjami!
{110} {} {Moo-oo}
{111} {} {M-mu-oo}
{112} {} {* prycha *}
{113} {} {Moo-oo-oo-oo}
{114} {} {}
{115} {} {}
{116} {} {}
{117} {} {}
{118} {} {}
{119} {} {}

# Repliki z niska inteligencja
{120} {} {* prycha *}
{121} {} {* Hee-hee *}
{122} {} {Hej stary.}
{123} {} {Co dwie g³owy to nie jedna.}
{124} {} {S³yszysz nas?}
{125} {} {Czyta w naszych myœlach.}
{126} {} {Czy on nas pods³uchuje?}
{127} {} {Znamy Twoje myœli.}
{128} {} {Myœlê, ¿e jest na haju.}
{129} {} {Nie bêdê z nim rozmawiaæ.}
{130} {} {Jeœli nas s³yszy, to Ÿle.}
{131} {} {Puœæ go.}
{132} {} {On mo¿e powiedzieæ innym.}
{133} {} {Nikt mu nie uwierzy.}
{134} {} {Dobra, zignoruj go.}
{135} {} {Kolejny w³óczêga.}
{136} {} {Czy on jest niebezpieczny?}
{137} {} {Hej, zamknij siê.}
{138} {} {On nas nie s³yszy.}
{139} {} {To niebezpieczne, przestañ.}
{140} {} {Lepiej przestañ myœleæ.}
{141} {} {Przepraszam za tego cz³owieka.}
{142} {} {Ludzie s¹ tacy delikatni.}
{143} {} {Ludzie s¹ tacy szaleni.}
{144} {} {Nie rozumiem, dlaczego ludzie s¹ wrogo nastawieni.}
{145} {} {Brak kontaktu z tym stworzeniem.}
{146} {} {Mog¹ nas pods³uchiwaæ.}
{147} {} {Myœli, ¿e sobie to wyobra¿a.}
{148} {} {G³upia osoba.}
{149} {} {Myœlê o wiecznoœci.}
{150} {} {Ha! To stworzenie ma frustruj¹co nisk¹ inteligencjê.}
{151} {} {Wygl¹da na to, ¿e to biedne stworzenie zosta³o poddane lobotomii.}

{1120} {} {* prycha *}
{1121} {} {* Hee-hee *}
{1122} {} {Hej stary.}
{1123} {} {Co dwie g³owy to nie jedna.}
{1124} {} {S³yszysz nas?}
{1125} {} {Czyta w naszych myœlach.}
{1126} {} {Czy ona nas pods³uchuje?}
{1127} {} {Znamy Twoje myœli.}
{1128} {} {Myœlê, ¿e jest naæpana.}
{1129} {} {Nie bêdê z ni¹ rozmawiaæ.}
{1130} {} {Jeœli nas s³yszy, to Ÿle.}
{1131} {} {PrzejdŸmy dalej.}
{1132} {} {Ona mo¿e powiedzieæ innym.}
{1133} {} {Nikt jej nie uwierzy.}
{1134} {} {Dobra, zignoruj j¹.}
{1135} {} {Kolejny w³óczêga.}
{1136} {} {Ona nie jest niebezpieczna?}
{1137} {} {Hej, zamknij siê.}
{1138} {} {Ona nas nie s³yszy.}
{1139} {} {To niebezpieczne, przestañ.}
{1140} {} {Lepiej przestañ myœleæ.}
{1141} {} {Przepraszam za tego ma³ego cz³owieka.}
{1142} {} {Ludzie s¹ tacy delikatni.}
{1143} {} {Ludzie s¹ tacy szaleni.}
{1144} {} {Nie rozumiem, dlaczego ludzie s¹ wrogo nastawieni.}
{1145} {} {Brak kontaktu z tym stworzeniem.}
{1146} {} {Mog¹ nas pods³uchiwaæ.}
{1147} {} {Myœli, ¿e sobie to wyobra¿a.}
{1148} {} {G³upie ludzkie dziecko.}
{1149} {} {Myœlê o wiecznoœci.}
{1150} {} {Ha! To stworzenie ma frustruj¹co nisk¹ inteligencjê.}
{1151} {} {Wygl¹da na to, ¿e to biedne stworzenie zosta³o poddane lobotomii.}
