{100} {} {Widzisz kanibala.}
{101} {} {Widzisz dziwn¹ osobê. Uœmiecha siê ³akomie, patrz¹c na ciebie.}

{110} {} {Twoje cia³o mo¿e wykarmiæ ca³¹ moj¹ rodzinê.}
{111} {} {Twoje poœladki bêd¹ œwietnym stekiem.}
{112} {} {Bêdziesz moim obiadem.}
{113} {} {Podziel siê swoim miêsem z g³oduj¹cymi!}
{114} {} {Mogê prze¿yæ na twoim soczystym miêsie miesi¹cami.}
{115} {} {Zjem twoje nerki jako ostatnie. A oczy i mózg bêd¹ pierwsze.}
{116} {} {Czy masz pojêcie, ile osób mog³oby karmiæ siê Twoim miêsem?}
{117} {} {Przepraszam, ale mam zamiar zrobiæ sobie z ciebie przek¹skê. Nic osobistego.}
{118} {} {Nic osobistego. Po prostu naprawdê chcê jeœæ.}
{119} {} {Nie bój siê, nie ugryzê... dopóki dobrze ciê nie upiekê nad ogniem.}