{100} {} {Widzisz stra¿nika.}
{101} {} {Widzisz jednego ze stra¿ników karawany.}

{110} {} {Mam nadziejê, ¿e po drodze nie spotkamy nikogo innego.}
{111} {} {By³oby wspaniale dostaæ kapsle zaraz po zakoñczeniu podró¿y.}
{112} {} {Miejmy nadziejê, ¿e bar bêdzie nadal otwarty, kiedy przyjedziemy.}
{113} {} {By³oby mi³o dostaæ wreszcie trochê prawdziwego jedzenia.}
{114} {} {Ta podró¿ by³a wyczerpuj¹ca.}
{115} {} {Braminy s¹ strasznie wolne pod obci¹¿eniem.}