{100} {} {Widzisz kupca.}
{101} {} {Widzisz przywódcê karawany.}
{102} {} {Schowaj broñ, jeœli naprawdê masz pokojowe zamiary.}

{200} {} {Witaj podró¿niku. Ostatnio coraz trudniej jest przedostaæ siê z miejsca na miejsce bez wpadania w zasadzkê.}
{1200} {} {Witaj podró¿niku. Ostatnio coraz trudniej jest przedostaæ siê z miejsca na miejsce bez wpadania w zasadzkê.}
{201} {} {Hmm. Kr¹¿¹ plotki o cz³owieku o twoim wygl¹dzie. Z³e plotki.}
{202} {} {Dziêki Bogu, ¿e jesteœ z nami! Cieszê siê, ¿e nasze œcie¿ki siê skrzy¿owa³y. Jak mogê siê przydaæ tak szanowanej osobie?}
{203} {} {Tylko przechodzê.}
{204} {} {Muszê uzupe³niæ zapasy. Czy zosta³y ci jakieœ towary?}
{205} {} {Uwielbiam ubiæ dobry interes. Spójrz, wybierz sobie coœ.}
{206} {} {No có¿...}
{207} {} {Mi³ej podró¿y.}
{208} {} {Dziêki.}

{210} {} {Co mogê dla ciebie zrobiæ?}
{211} {} {Do widzenia.}
