{100} {} {Widzisz rolnika.}
{101} {} {Widzisz mê¿czyznê ze znoszonymi ubraniami. Niesie torbê z rzeczami.}
{102} {} {Najpierw od³ó¿ broñ. DOBRZE?}

{200} {} {Witaj podró¿niku. Widzê, ¿e jesteœ gotowy do rozmowy i nie machasz broni¹, jak niektórzy. Jak mogê ci pomóc?}
{1200} {} {Witaj podró¿niku. Widzê, ¿e jesteœ gotowa do rozmowy i nie machasz broni¹, jak niektórzy. Jak mogê ci pomóc?}
{201} {} {Prawdopodobnie nijak. Bywaj.}
{202} {} {Gdzie idziesz?}
{203} {} {Idê do najbli¿szej osady handlowej. Towary z mojej farmy s¹ tam bardzo po¿¹dane.}
{204} {} {Co sprzedajesz?}
{205} {} {Mam nadwy¿kê plonów. Chcê to wymieniæ na coœ po¿ytecznego, czego nie mogê zrobiæ samodzielnie.}
{206} {} {Mo¿e mo¿emy pohandlowaæ tutaj?}
{207} {} {Dlaczego nie? Bêdzie mi ³atwiej.}
{208} {} {Mo¿e innym razem.}
{209} {} {Zobaczmy, co masz.}

{210} {} {Có¿, œwietnie. Ju¿ czas, ¿ebyœmy wyruszyli dalej.}
{211} {} {Do widzenia.}
{212} {} {Hmm, gdzieœ ciê widzia³em... Hej! Szukaj¹ ciê Rangersi, prawda? Nie wiem, jaki masz z nimi problem i nie chcê wiedzieæ. Po prostu idŸ w³asn¹ drog¹.}
{213} {} {Do widzenia.}
{214} {} {Tylko b¹dŸ dla mnie surowy...}
{215} {} {Hmm, gdzieœ ciê widzia³em... Hej! Szukaj¹ ciê Rangersi, prawda? Nie martw siê, nie wydam ciê. Mnie te¿ szukaj¹, hahaha.}
{216} {} {Dobrze. Gdzie idziesz?}