{100} {} {Widzisz pustelnika.}
{101} {} {Widzisz zaroœniêtego mê¿czyznê w brudnych szmatach. Zastanawiasz siê, ile lat siê nie my³?}
{102} {} {Grozisz mi? Wah!}

{200} {} {Hmm... dawno z nikim nie rozmawia³em. Jêzyk jest ciê¿ki.}
{201} {} {Ja te¿ nie chcê z nikim rozmawiaæ. Proponujê siê rozejœæ.}

{210} {} {To by³a dobra rozmowa. Teraz odejdŸ. Jestem zmêczony.}
{211} {} {Mówienie przyprawia mnie o ból g³owy. IdŸ st¹d.}
{212} {} {Ju¿ dzisiaj rozmawia³em. Doœæ.}
{213} {} {Do widzenia.}

{220} {} {Dlaczego jesteœ pustelnikiem?}
{221} {} {Chcesz byæ. Jeden. Sam.}
{222} {} {Nadal - czy s¹ tu jakieœ osady?}
{223} {} {Hermosillo tam jest. (pokazuje rêk¹) Nie idŸ. Niebezpieczne.}
{224} {} {Tu-San tam jest. (pokazuje rêk¹) Nie idŸ. Niebezpieczne.}
{225} {} {Mo¿e masz coœ do handlu?}
{226} {} {Ok, oto co mam.}
{227} {} {Powinnienem chyba wyjœæ.}
{228} {} {Santa Ana tam jest, (pokazuje rêk¹) ³adne miejsce.}
