{100} {} {Widzisz cywila.}
{101} {} {Widzisz brudnego, wychudzonego cz≥owieka.}

{110} {} {° Por favor, no nos ataquen!}
{111} {} {°No queremos problemas!}
{112} {} {Estamos buscando un nuevo hogar.}
{113} {} {øYa hemos llegado?}
{114} {} {Quiero dormir.}
{115} {} {Tü eres aventurero, øNie?}
{116} {} {Ya estamos hartos de estos tiranos y guerrilleros.}
{117} {} {Hay bandidos por todas partes.}
{118} {} {°Dêjanos en paz!}
{119} {} {No tenemos nada de valor.}

{210} {} {Nie zamierzasz nas zaatakowaÊ, prawda?}
{211} {} {Chcemy tylko spokojnego øycia.}
{212} {} {Szukamy nowego domu, aby zaczπÊ od nowa.}
{213} {} {Czy juø tam jesteúmy?}
{214} {} {ChcÍ spaÊ.}
{215} {} {Jestes poszukiwaczem przygÛd, prawda?}
{216} {} {Mamy doúÊ tych tyranÛw i wojownikÛw.}
{217} {} {Cholerni bandyci sπ wszÍdzie.}
{218} {} {Zostaw nas w spokoju!}
{219} {} {Nie mamy nic do zrabowania.}