{100} {} {Widzisz podró¿nika.}
{101} {} {Widzisz starszego mê¿czyznê w brudnej, znoszonej kurtce z manierk¹ na pasku. Ostro¿nie patrzy w twoj¹ stronê.}

{200} {} {Nie zbli¿aj siê. Mój pies ma s³abe nerwy. Sk¹d pochodzisz?}
{201} {} {Pochodzê z wioski w pó³nocnej Arizonie. Wyrzucili mnie Ÿli ludzie. A ty?}
{202} {} {Jestem z po³udniowej Kalifornii. Tylko podró¿ujê.}
{203} {} {Czy masz coœ przeciwko, jeœli zadam kilka pytañ?}
{204} {} {Rozumiem. Na tej podstawie siê rozejdziemy, ka¿dy we w³asnym kierunku.}

{210} {} {Chcesz siê czegoœ dowiedzieæ? W porz¹dku, mów.}
{211} {} {Chyba powinienem ju¿ iœæ.}
{212} {} {Ostro¿nie na tych ziemiach. Czêsto widywa³em tu dzikie upiory i ogromne szczury. Powodzenia.}
{213} {} {Do widzenia.}

{220} {} {Gdzie idziesz?}
{221} {} {Nigdzie konkretnie. Chcê tylko zobaczyæ œwiat. Z pewnoœci¹ jest miejsce, które nie zosta³o jeszcze zepsute przez wojnê ani ludzk¹ chciwoœæ. Có¿, jeœli czegoœ takiego nie ma, bêdê musia³ wróciæ i zbudowaæ nowy dom.}
{222} {} {Jakieœ wiadomoœci z Kalifornii?}
{223} {} {W ostatnich latach nie by³o spokojnie. Armia super mutantów zosta³a pokonana, ghule z Nekropolis migruj¹ na po³udnie, a w Hub rozpoczê³a siê nowa runda wojen handlowych. Coraz wiêcej ludzi wyje¿d¿a w poszukiwaniu nowych miejsc do ¿ycia, poniewa¿ obszar Los Angeles jest przepe³niony.}
{224} {} {Dlaczego potrzebujesz psa?}
{225} {} {Spotka³em go na drodze. Na pocz¹tku myœla³em o upieczeniu go na ogniu. Ale potem okaza³o siê, ¿e pies bardzo siê przydaje po drodze, odstrasza bandziorów.}
{226} {} {A mo¿e wymiana?}
{227} {} {Ok. Zobaczê, co masz.}
{228} {} {Czy znasz najbli¿sze osady?}
{229} {} {Powiedziano mi, ¿e wschód to ja³owe pustkowia. Jestem nawet zaskoczony, ¿e ciê spotka³em. S³ysza³em jednak równie¿, ¿e ziemie Rangersów rozci¹gaj¹ siê na pó³nocny wschód. Ich s³awa jest znana nawet w Kalifornii.}
{230} {} {Coœ jeszcze?}
{231} {} {Ostrzegano mnie tak¿e o ruinach Inferno. Mówi¹, ¿e to bardzo niebezpieczne miejsce, w którym zwyk³ego cz³owieka czeka tylko œmieræ. Pomyœl trzy razy, zanim zdecydujesz siê tam udaæ.}