{100} {} {Widzisz padlinozercê.}
{101} {} {Widzisz mê¿czyznê w brudnych ubraniach. Zgina siê pod ciê¿arem plecaka pe³nego ró¿nych œmieci.}
{102} {} {Hej, sk¹d te groŸby? Ja ci nie gro¿ê, prawda?}

{200} {} {Ok, ale trzymaj rêce w zasiêgu wzroku. Bandyci ostatnio czêsto nawiedzaj¹ te ziemie. Czego potrzebujesz?}
{201} {} {Dlaczego pytasz?}
{202} {} {Tylko przechodzê.}
{203} {} {Có¿, d³ugo szuka³em przydatnych rzeczy w tych ruinach. Jeœli czegoœ potrzebujesz, spróbujê to znaleŸæ. Na razie oto, co mam.}
{204} {} {Rozumiem. Mo¿e wrócê do Ciebie.}
{205} {} {Hmm, gdzieœ ciê widzia³em... Hej! Szukaj¹ ciê w Phoenix, prawda? Nie martw siê, nikomu o Tobie nie powiem. Ktoœ te¿ mnie tam szuka.}
{206} {} {To dobrze. Co robisz w tak okropnym miejscu?}

{210} {} {Potrzebujesz czegoœ? Mo¿e to mam, mam wiele ró¿nych rzeczy.}
{211} {} {Muszê iœæ.}