{100} {} {Widzisz zwiadowcÍ.}
{101} {} {Widzisz øo≥nierza w typowej wojskowej zbroi.}

{110} {} {°El intruso!}
{111} {} {°Veo al intruso!}
{112} {} {Eres gringo, øNo?}
{113} {} {°Bienvenido a Mêxico!}
{114} {} {øQuê se te perdiÉ aquö?}
{115} {} {øVienes del norte?}
{116} {} {Esto es Nuevo Mêxico.}
{117} {} {°Esta es nuestra tierra!}
{118} {} {°Guarda tus armas!}
{119} {} {No nos caen bien los gringos.}
{120} {} {øQuiên eres?}

{210} {} {Intruz!}
{211} {} {WidzÍ intruza!}
{212} {} {Czy jesteú Amerykaninem?}
{213} {} {Witamy w Meksyku.}
{214} {} {Czego szukasz?}
{215} {} {Przybywasz z pÛ≥nocy?}
{216} {} {To jest Nowy Meksyk.}
{217} {} {To nasza ziemia!}
{218} {} {Schowaj broÒ.}
{219} {} {Nie potrzebujemy tutaj obcych.}
{220} {} {Kim jesteú?}