{110} {} {Czy mam opowiedzieæ panu ¿art, panie McClellan?}
{111} {} {Dzieñ dobry pani McClellan.}
{112} {} {Ktoœ taki jak ty zabi³ pani¹ McClellan!}
{113} {} {Wynoœ siê z domu rodziny McClellan!}
{114} {} {Ocal siebie, panie McClellan! IdŸ do piwnicy i zabierz dzieci!}
{115} {} {Nie pozwolê obra¿aæ moich panów!}
{116} {} {Nikt nie mo¿e przerywaæ porannego spaceru psa mojego pana.}
{117} {} {Widzê z³odzieja! Mistrzu, nie wychodŸ z pokoju i zamknij drzwi!}
{118} {} {Nie powinieneœ by³ porywaæ psa mojego pana!}
{119} {} {Bo¿e, ten oœlepiaj¹cy b³ysk... Panie McClellan? Coœ jest z Panem nie tak? Panie McClellan!}
{120} {} {Nie mogê skrzywdziæ cz³onków rodziny McClellan. Ale ty nie jesteœ z tej rodziny.}
{121} {} {Zosta³em zaprogramowany do wykonywania tylko rozkazów rodziny McClellan.}
{122} {} {Muszê dbaæ o swoje bezpieczeñstwo, poniewa¿ jestem w³asnoœci¹ rodziny McClellan.}
{123} {} {Bêdzie dziœ padaæ, b¹dŸ cicho.}
{124} {} {Twoja krew bêdzie œwietnym lubrykantem, plebejuszu!}
{125} {} {Aktywacja protoko³u Deep Clean.}
{126} {} {Umieœciæ t¹ czaszkê naczelnego obok twoich trofeów, panie McClellan?}
{127} {} {Podaæ intruzowi czosnek lub sos musztardowy, pani McClellan?}
{128} {} {Bêdziesz musia³ zap³aciæ grzywnê, intruzie.}
