{100} {} {Widzisz upiora.}

{110} {} {Ile masz lat?}
{111} {} {Przeszliœmy d³ug¹ drogê z Nekropolis do Centrum, a potem z Centrum do San Diego... I oto jesteœmy.}
{112} {} {W San Diego s¹ teraz tylko super mutanty i upiory.}
{113} {} {Na pó³nocnym zachodzie jest sta³e pasmo promieniowania.}
{114} {} {Nie mo¿esz pojechaæ t¹ tras¹ do Kalifornii z powodu gór, mutantów i promieniowania.}
{115} {} {Czy to te¿ nie siedzi spokojnie?}
{116} {} {Cholerni rasiœci w³aœnie wyrzucili nas z naszych domów.}
{117} {} {Têskniê za zwêglonymi ruinami mojego rodzinnego Nekropolis.}
{118} {} {Wy te¿ u¿ywacie tu kapsli? Dziwny zbieg okolicznoœci.}
{119} {} {Z jakiegoœ powodu Mistrz wyhodowa³ lataj¹ce robaki i skrzy¿owa³ ludzi z psami.}
{120} {} {Mistrz zosta³ obalony, a jego armia zniszczona.}
{121} {} {Nie wiem, kim by³ ten Wêdrowiec, ale mia³ cholerne szczêœcie.}
{122} {} {Mieszkaniec Krypty dba³ tylko o siebie.}
{123} {} {Gdyby jeden g³adkoskóry nie zniszczy³ katedry, nie ucieklibyœmy tutaj.}
{124} {} {Czy wiesz coœ o Przybyszu z Krypty?}
{125} {} {Wêdrujemy tam, gdzie ponios¹ nas nasze oczy.}
{126} {} {Skoñczy³o nam siê miejsce w San Diego.}
{127} {} {Blask dnia jest na pó³nocnym zachodzie, ale nie mo¿esz siê tam dostaæ.}
{128} {} {Czy widzia³eœ te brzydkie gigantyczne robaki?}
{129} {} {}

{130} {} {Przepraszam, g³adki, ale nie mo¿esz z nami iœæ.}
{131} {} {Nigdy nie myœla³em, ¿e zobaczê tu coœ normalnego.}
{132} {} {Hej, g³adki, nie lubimy tutaj rasistów. To tak przy okazji.}
{133} {} {Wy normalni zawsze jesteœcie tacy nieszczêœliwi. Odprê¿ siê i ciesz siê ¿yciem.}
{134} {} {Nie potrzebujemy g³adkich do zespo³u. Wiesz, mamy tu wyj¹tkow¹ atmosferê.}

{150} {} {Przepraszam, mój zgni³y przyjacielu, ale nie mo¿esz iœæ z nami.}
{151} {} {Nigdy bym nie pomyœla³, ¿e zobaczê tu takiego dziwaka jak ja.}
{152} {} {Ci normalni s¹ rasistami. Nie mo¿esz tego zrozumieæ?}
{153} {} {Czy ty te¿ jesteœ odpêdzany przez normalnych? To jest nam tak znajome.}
{154} {} {Zabralibyœmy ciê ze sob¹, ale nie wiemy, dok¹d siê udaæ.}
