{110} {} {Jesteœ obrzydliwy!}
{111} {} {Jesteœ gorszy ni¿ zwierzê.}
{112} {} {Pomszczê wszystkie dzieci, które zginê³y z twojej rêki.}
{113} {} {Zemsta za dzieci jest nieunikniona.}
{114} {} {S³yszysz jêki dzieci, które zabi³eœ, psycholu?}
{115} {} {Myœlisz, ¿e mo¿esz po prostu chodziæ i zabijaæ dzieci, co?}
{116} {} {Bestio, pamiêtaj o tych bezradnych dzieciach!}
{117} {} {Dzieci... Jak œmiesz dotykaæ te niewinne stworzenia?}
{118} {} {Zabijê ka¿dego, kto zabija dzieci.}
{119} {} {Nawet jeœli te zgony dzieci by³y przypadkowe, umrzesz.}
