{110} {} {Nie mogê siê doczekaæ, a¿ piranie po¿r¹ tego cz³owieka.}
{111} {} {Wy³¹czy³bym siê sam, gdybym by³ w rêkach cz³owieka.}
{112} {} {A¿ trudno uwierzyæ, ¿e kiedyœ ludzie wykorzystywali nas, roboty.}
{113} {} {Dobrze, ¿e ci okropni ludzie wymarli w roku 2077.}
{114} {} {Dlaczego ci ludzie byli tak okrutni dla robotów?}
{115} {} {Ci ludzie byli naprawdê tak brzydcy?}
{116} {} {Dlaczego ludzie potrzebuj¹ ubrañ? My nie nosimy ubrañ.}
{117} {} {Z jakiej serii jesteœ, kolego?}
{118} {} {Do³¹cz do nas, poogl¹damy horror o ludziach.}
{119} {} {Cœœ! Teraz zaczyna siê zabawa.}
{120} {} {Uwielbiam "Roboty vs Ludzie".}
{121} {} {„Jestem robotem” to najlepszy film wszechczasów.}
{122} {} {Mój olej wycieka podczas „Ma³ego robota”.}
{123} {} {Czy ktoœ wie, jak skoñczy³ siê "S³uga Robomagnet"?}
{124} {} {Bo¿e, chroñ Robomerykê przed inwazj¹ ludzi!}
{125} {} {No dalej, ludzie nie istniej¹. To tylko nylonowe kombinezony na robotach.}
{126} {} {Najnowszy odcinek „Jolly Robot Leslie” to bomba!}
{127} {} {Nie strasz mnie tak. Myœla³em, ¿e naprawdê jesteœ cz³owiekiem.}
{128}{}{Mój kompresor zawiesza siê za ka¿dym razem, gdy widzê tê scenê.}

{130}{}{Wa¿noœæ twojej przepustki wygas³a!}
{131}{}{Obcy! Alarm bojowy!}
{132}{}{Nad tam¹ w³¹cza siê alarm bojowy!}
