{110} {} {O nie, unikam ludzi od 90 lat. Twoja obecnoœæ koñczy moj¹ misjê. Nie mam ju¿ ¿adnego powodu, dla którego mia³bym istnieæ.}
{111} {} {Jestem Shybot. Moim celem jest „unikanie ludzi”. Okres pomyœlnego dzia³ania - 90 lat.}

{120} {} {Jestem Shybot. Moim celem jest unikanie ludzi.}
{121} {} {Cel pomyœlnie wykonywany przez 90 lat.}
{122} {} {Twoja obecnoœæ koñczy moj¹ misjê. To niedopuszczalne.}
{123} {} {Nikt nie powinien wiedzieæ, ¿e moja misja siê nie powiod³a.}
{124} {} {Wyma¿ê ciê z mojej pamiêci.}
{125} {} {Z powodzeniem unikam ludzi przez 90 lat. Dlaczego przerywasz mi zadanie?}
{126} {} {Jesteœ przeszkod¹ dla mojego g³ównego celu.}
{127} {} {Ju¿ nie ma sensu uciekaæ.}
{128} {} {Jestem zmêczony uciekaniem przed ludŸmi.}
{129} {} {Chcê siê do ciebie zbli¿yæ. Ale jest to dla mnie zabronione.}