{100} {} {Widzisz myœliwego.}
{101} {} {Widzisz mê¿czyznê z gest¹ brod¹. Wydaje siê doœæ wyczerpany po polowaniu.}
{102} {} {Od³ó¿my razem nasz¹ broñ, dobrze?}

{200} {} {Witaj nieznajomy. Rzadko widujê podró¿ników na tych ziemiach. Na pocz¹tku myœla³em, ¿e widzê zwierzê.}
{1200} {} {Witaj nieznajoma. Rzadko widujê podró¿ników na tych ziemiach. Na pocz¹tku myœla³em, ¿e widzê zwierzê.}
{201} {} {Wiêc jesteœ myœliwym?}
{202} {} {Zgadza siê. Nie ma tu du¿o zwierzyny, ale dla mnie jest doœæ, by wy¿ywiæ siê i handlowaæ w du¿ym mieœcie.}
{203} {} {Co to za miasto?}
{204} {} {Flagpool? To du¿a kolonia wokó³ starej kopalni. Zosta³a za³o¿ona kilka lat temu i w tym czasie ruiny zmieni³y siê nie do poznania. JedŸ g³ówn¹ drog¹, nie przegapisz.}
{205} {} {Dziêki. A co z miêsem?}
{206} {} {Czy mogê dostaæ trochê miêsa na podró¿?}
{207} {} {W³aœnie wysuszy³em œwie¿e miêso. Mogê wymieniæ na coœ po¿ytecznego.}
{208} {} {Mo¿e innym razem.}
{209} {} {W³aœnie mia³em uzupe³niæ zapasy.}
{210} {} {Ok, muszê wyruszyæ w trasê, zanim miêso siê zepsuje.}
{211} {} {Do zobaczenia.}
{212} {} {Hej, czy ludzie z garnizonu nie szukali ciê czasem? Wygl¹da na to, ¿e s¹ na ciebie naprawdê Ÿli. Uwa¿aj na nich tam. Nie obchodzi mnie to, ale jeœli zobacz¹ mnie z tob¹, bêd¹ problemy ze sprzeda¿¹ miêsa.}
{213} {} {Czekaj. Chcê kupiæ twoje suszone miêso.}
