{110} {} {Jak widaæ jest to zabite deskami. Mo¿na to otworzyæ tylko brutaln¹ si³¹.}
{111} {} {Brakuje Ci si³y, by tego u¿yæ.}
{112} {} {Uda³o ci siê otworzyæ wieko pude³ka.}

{120} {} {W³aœnie otwierasz trochê szuflady. Spróbuj mocniej.}
{121} {} {Jeszcze trochê i gotowe!}
{122} {} {No dalej! Prawie otwarte.}
{123} {} {Prawie... No dalej, rekrucie, zrób to!}
{124} {} {To nie wystarczy³o, musisz spróbowaæ trochê mocniej.}
{125} {} {Prawie gotowe! Popróbuj jeszcze trochê.}