{100} {} {Nie mo¿na tego zrobiæ podczas walki.}
{101} {} {Ten przedmiot ma byæ u¿ywany z rêki.}
{102} {} {Sciany jaskini zak³ócaj¹ sygna³ radiowy.}
{103} {} {Coœ zak³óca sygna³ radiowy. To prawdopodobnie sztuczka ZAX.}

{210} {} {Z g³oœnika s³ychaæ delikatne trzaski.}
{211} {} {Pos³uchaj wspólnej czêstotliwoœci.}
{212} {} {Pos³uchaj czêstotliwoœci najemników Fabera.}
{213} {} {Pos³uchaj czêstotliwoœci Rangersów.}
{214} {} {Pos³uchaj czêstotliwoœci Czcicieli Ognia.}
{215} {} {Pos³uchaj czêstotliwoœci Ruchu Oporu.}
{216} {} {Pos³uchaj czêstotliwoœci Blacharzy.}
{217} {} {Pos³uchaj czêstotliwoœci Bractwa Stali.}
{218} {} {Pos³uchaj czêstotliwoœci alarmowej Krypty 27.}
{219} {} {Wy³¹cz.}

# Wspolna czêstotliwoœæ
{230} {} {S³ychaæ tylko bia³y szum.}
{231} {} {WyjdŸ.}
{232} {} {NajwyraŸniej jestem zbyt daleko od obszaru negocjacji na tej czêstotliwoœci.}
{233} {} {Przeszukaj wszystkie czêstotliwoœci.}
{234} {} {...pomocy! Szakale nas uwiêzi³y, pilnie potrzebujemy pomocy!}
{235} {} {S³yszê ciê. Gdzie jesteœ?}
{236} {} {Cholera, w koñcu! Pos³uchaj, Szakale nas uwiêzi³y. Nie mo¿emy siê st¹d wydostaæ. Pomó¿ nam, nie pozostaniemy d³u¿ni. Oto wspó³rzêdne na pó³noc od Garage City... Uwa¿aj i przyprowadŸ wiêcej ludzi... Cholera, te œwiry ju¿ tu s¹... (sygna³ znikn¹³)}
{237} {} {Zaczekaj, nieznajomy. Kimkolwiek jesteœ.}
{238} {} {Zaczekaj, Rangersie. Pomoc jest w drodze.}
{239} {} {S³yszê ciê. Dowódca Helford wys³a³ mnie do pomocy. Gdzie jesteœ?}

#Rangers
{240} {} {(S³yszysz nudn¹ rozmowê. Nic ciekawego.)}
{241} {} {"...widzia³em ich raz w Garage City." - "Mogli zgin¹æ w drodze. Zw³aszcza bior¹c pod uwagê, ¿e wœród uchodŸców by³y dzieci." - "A dlaczego nie mog¹ siedzieæ w Vegas?" "Nie wiem. Mówi¹, ¿e miêdzy klanami tocz¹ siê ca³e wojny, a kanibalizm kwitnie. Musielibyœmy uporaæ siê z naszymi problemami." - "Zgadza siê. Wiêc mo¿e to dobrze, ¿e zgubili siê na pustyni. Mniej gêb do wykarmienia w bazie." - "Upewnij siê, ¿e cywile ciê nie s³ysz¹." - "Wiem wiem..."}
{242} {} {"...racja ju¿ nie wpadnie ci do gard³a. Kiedy normalne miêso w koñcu dotrze do bazy?" „Mówi¹, ¿e problemy w San Brahmin pogorszy³y siê. Dopóki sytuacja nie zostanie rozwi¹zana, zadowalaj siê tym, co masz”. - "Cholera, wiêc dalej bêdê g³odowa³..."}
{243} {} {* shhhh * "...i zepchn¹³ ich do ruin Igie³. Oblê¿enie trwa³o trzy dni, dopóki nie poddali siê z g³odu." - "Wow, trzy dni na s³oñcu to coœ." - „Tak. Ale bandyci okazali siê go³odupcami. Nie mogliœmy zabraæ ze sob¹ niczego cennego...” - * psz-sz-sz * - „Wiêc przestañ zaœmiecaæ powietrze! - * psh-sh-sh * - "Jak mówisz, nie jestem przyzwyczajony do odmawiania kobietom." - * psz-sz-sz * - "Zartujesz, g³upku, a ja pomogê ci zmniejszyæ racje na tydzieñ."}
{244} {} {* shhhh * "...przygotowuj¹ siê do wyjœcia. Co robiæ? Halo." - "Puœæ ich. Nie potrzebujemy niepotrzebnych problemów przez kilku ³otrów."}
{245} {} {"...wyœlij do modliszki!" - "Uspokój siê, sier¿ancie. Poinformujê ch³opaków, aby przechwycili karawanê i zabrali skradzione towary. Od teraz zachowaj ostro¿noœæ w kontaktach z niezweryfikowanymi kupcami."}
{246} {} {"...za ma³o jedzenia. Nie wiem, czy powinienem im pomóc. Racje te¿ siê koñcz¹." - "Wiêc zatrzymaj je dla siebie. Najbli¿sza placówka jest za daleko, nie powinieneœ ryzykowaæ..."}
{247} {} "{...zosta³ sam, ale uciek³ na pustkowiê." - "Pozwólcie mu uciekaæ. Powiem najbli¿szym patrolom, przechwyc¹ go." - "Dziêkujê. Ale jakoœ nadrobiê dystans." - "Rangersie, nie próbuj go œcigaæ na pustyni!" - "Kurwa, i tak to zrobiê." - "(pauza) Jak chcecie. Ale jeszcze jedna taka akcja, a poinformujê dowódcê."}
{248} {} {* shhhh * - "Bravo, odpowiedz!" - * sh-sh-sh * - "Grupa Bravo, odpowiedz! ...Cholera..."}
{249} {} {* sh-sh-sh *}

{250} {} {...Nie mogê zostaæ! Kto móg³ to zrobiæ?! - Rangersi maj¹ wielu wrogów. Ale jeœli tama zosta³a zniszczona od wewn¹trz, oznacza to, ¿e zrobi³ to jeden z nich. Mówi¹, ¿e wczeœniej w tamie widziano jakiegoœ nowicjusza. Stra¿nicy zostali przes³uchani w najszerszym zakresie. Nie zobacz¹ ju¿ swojej odznaki.}
{251} {} {...w bazie, koniecznie sprawdŸ to. Ten goœæ to œwietny mechanik. - Nie lubiê bawiæ siê z nastolatkami. Najwa¿niejsze, ¿e pilnujê tamy, bo inaczej stary Rufus wkrótce siê ugnie, a co dalej?}
{252} {} {...ja te¿ to zauwa¿y³em. Co siê sta³o? - Wygl¹da na to, ¿e sygnaliœci wynajêli jakiegoœ ch³opa do naprawy anteny. Teraz krótkofalówka dzia³a lepiej i na wiêksz¹ odleg³oœæ. - Ch³op? Co za zwrot akcji. Gdy go spotkamy, kupimy mu kawê z pustkowia.}
{253} {} {...ten zbieg zosta³ z³apany. Suka ukrywa³a siê w piwnicy w pobli¿u rolników na Route 95. - Tu¿ pod naszym nosem? I nie mogliœmy go z³apaæ tak d³ugo? - Doskona³y szpieg, przyda³by siê nam. Mówi¹, ¿e z³apali go nawet nie Rangersi, ale jakiœ ³otr. - Có¿, przynajmniej jakiœ po¿ytek z tych obcych. - Nie trzeba mówiæ...}

{260} {} {Ranger}
{261} {} {W kontakcie. Jestem na pustyni w pobli¿u bazy. Pilnie potrzebujê wsparcia w zakresie zaopatrzenia.}
{262} {} {* shhhh * Witamy, debiutancie. Czy wiesz o mieœcie Quartz na po³udniu? ZnajdŸ ruiny naprzeciwko baru. Z naszymi zapasami zeszli do tajnej piwnicy. Mam nadziejê, ¿e to pomo¿e.}
{263} {} {Dziêki Rangersie.}
{264} {} {Poszukaj Ÿród³a przekaŸnika rozmów Stra¿ników.}
{265} {} {Nie mo¿esz z³apaæ tego zjawiska. NajwyraŸniej Ÿród³o jest zbyt daleko.}
{266} {} {Zród³o jest nadal zbyt daleko. Warto wróciæ do bazy Rangersów i wyruszyæ od niej œciœle na wschód.}
{267} {} {Wygl¹da na to, ¿e uda³o ci siê wykryæ Ÿród³o echa radiowego! Pozostaje je znaleŸæ na œrodku pustyni.}
{268} {} {PrzejdŸ do lokalizacji.}
{269} {} {}
{270} {} {Hej Rangersi, czy ktoœ widzia³ tego legendarnego giganta Radskorpiona?}
{271} {} {Witaj, debiutancie. Ostatni raz by³ widziany na tych wspó³rzêdnych. Masz zamiar polowaæ? Uwa¿aj, lepiej nie natkn¹æ siê na takiego stwora bez granatnika.}
{272} {} {[PrzejdŸ do otrzymanych wspó³rzêdnych]}
{273} {} {Zrozumiano, Rangersie. Bez odbioru.}
{1273} {} {Rozumiem, Rangersie. Bez odbioru.}
{274} {} {Bêdê o tym pamietaæ. Do nastêpnego razu.}

#Motel
{290} {} {S³uchaj wszystkich czêstotliwoœci.}
{291} {} {S³yszysz delikatny sygna³ pomocy.}
{292} {} {[Pos³uchaj]}
{293} {} {[Ignoruj]}
{294} {} {...Ktokolwiek! Pomocy! Jestem w jakimœ starym motelu na po³udniowy zachód od Phoenix. Zablokowali wszystkie wyjœcia, nie mogê uciec. Proszê pomó¿...}
{295} {} {[Dalej.]}
{296} {} {Wszyscy inni ju¿ zginêli od pu³apek. Zosta³em sam... Ktoœ nadchodzi... Czego chcesz? IdŸ st¹d! O mój Bo¿e! Nie dotykaj mnie, dziwaku! Nie! Nie rób! A-ah-ah!}
{297} {} {Stary motel na po³udniowy zachód? Och, to nie bêdzie przyjemny spacer...}

# Krypta 27
{300} {} {Czêstotliwoœæ alarmowa wysy³a sygna³ o niebezpieczeñstwie.}
{301} {} {Oczywiœcie jestem za daleko od Krypty. Warto wróciæ do Phoenix i wypróbowaæ ró¿ne miejsca.}
{302} {} {To nie ma sensu. Wiem ju¿, gdzie jest Krypta.}
{303} {} {Sygna³ jest silniejszy w tym kierunku. Szukam dalej...}
{304} {} {Sygna³ jest coraz silniejszy.}
{305} {} {Tak! Wygl¹da na to, ¿e ciê znalaz³em.}
{1305} {} {Tak! Wygl¹da na to, ¿e ciê znalaz³am.}
{306}{}{PrzejdŸ do Krypty 24.}

#Flagpool
{310} {} {(S³yszysz rozmawiaj¹cych najemników. Nic ciekawego, tylko zwyk³a sprzeczka.)}
{320} {} {Wszystkie posterunki! Zostaliœmy zaatakowani! Ca³y t³um dzikusów! Potrzebne wsparcie! Wszyscy... A-ah-ah!}
{321} {} {Zrozumiano. Wysy³am oddzia³ z garnizonu. Czekaj...}
{322} {} {(Tak, opró¿nij garnizon, idioto, to wszystko, czego potrzebujê)}
{323} {} {SledŸ sygna³ zaginionego Blacharza.}
{324} {} {Brak identyfikowalnego sygna³u.}
{325} {} {Mo¿e jestem po prostu za daleko od niego. Muszê wróciæ do centrum Casa Grande.}
{326} {} {Odbierasz s³aby sygna³ od Blacharza.}
{327} {} {Dobra, œwietnie, jest gdzieœ w mieœcie. Wydaje siê, ¿e sygna³ pochodzi ze wschodu.}
{328} {} {Sygna³ z implantu jest wyraŸnie s³yszalny.}
{329} {} {Wiêc jest gdzieœ tutaj. On lub jego cia³o.}

#Pieklo
{350} {} {Oddzia³ Bractwa Stali, proszê o odpowiedŸ. Czy ktoœ mnie s³yszy?}
{351} {} {(W odpowiedzi pojawia siê tylko „bia³y szum”)}
{352} {} {Powtarzam. Oddzia³ Bractwa Stali, mówi cz³onek ekipy ratunkowej. Odbiór.}
{353} {} {Wygl¹da na to, ¿e mnie nie s³ysz¹. Od³o¿ê s³uchawkê.}
{354} {} {Tu Paladyn Barkley... Mi³o mi to s³yszeæ, towarzyszu. Jesteœmy w powa¿nych tarapatach. Jestem ranny, utraci³em ³¹cznoœæ z oddzia³em. Proszê o piln¹ pomoc.}
{355} {} {Zrozumiano. Gdzie jesteœ, Paladynie Barkley?}
{1355} {} {Zrozumiano. Gdzie jesteœ, Paladynie Barkley?}
{356} {} {Miejsce... W³az w pobli¿u zniszczonego supermarketu. Na powierzchni jest wiele mutantów, uwa¿aj.}
{357} {} {Wyruszam na pozycjê. Zostañ tam gdzie jesteœ. Bez odbioru.}
{358} {} {Hej, czy ktoœ mnie s³yszy? Odbiór?}
{359} {} {(nikt siê nie kontaktuje)}
{360} {} {Powtarzam. Czy ktoœ mnie s³yszy? Czy na tym cmentarzu nadal ¿yj¹ ludzie?}
{361} {} {Ok. Od³o¿ê s³uchawkê.}
{362} {} {Tu Barkley... Tak, przynajmniej jeden wci¹¿ ¿yje. Pos³uchaj mnie uwa¿nie, towarzyszu. Jestem kontuzjowany, potrzebujê pilnej pomocy.}
{363} {} {Gdzie jesteœ, Barkley?}
{364} {} {Kana³ pod zniszczonym supermarketem. PodejdŸ prosto do mnie, nie zwlekaj. I uwa¿aj, te mutanty, s¹ wszêdzie.}
{365} {} {Zaczekaj, Barkley. Idê.}
{366} {} {Yyy mutanty? To Ÿle.}

{370} {} {[Szukaj sygna³u]}
{371} {} {(Uwa¿nie sprawdzasz czêstotliwoœci, obracaj¹c radio we wszystkich kierunkach, a¿ w koñcu us³yszysz dŸwiêk z g³oœnika.)}
{372} {} {[Odtwórz dalej]}
{373} {} {[Ignoruj]}
{374} {} {(stara muzyka przenika przez g³oœny bia³y szum)}
{375} {} {[Odtwarzaj muzykê do koñca]}
{376} {} {...Hej, podró¿niku! Masz doœæ drogi? Pustynia po drodze ciê zmêczy³a? W takim razie odpocznij w Centrum!}
{377} {} {[Dalej.]}
{378} {} {Tutaj znajdziesz wszystko, czego potrzebujesz do wypoczynku: bary, hotele, ogromny targ... i oczywiœcie niezapomniana kawiarnia Sokó³ Maltañski! W naszej kawiarni mo¿na odpocz¹æ i zapomnieæ o szponach œmierci i bandytach z autostrad.}
{379} {} {Chcesz siê odœwie¿yæ? Mamy zapasy nuklearnej coli! A dla tych, którzy kochaj¹ coœ gor¹cego, zawsze bêdziemy mieli kieliszek legendarnego rumu Hub.}
{380} {} {Hej, a co z automatami do gry? O tak kochanie, mamy je! A jest ich bardzo niewiele we wspó³czesnej Kalifornii. Nie przegap tej okazji!}
{381} {} {I oczywiœcie nasze panie * zawsze * zajm¹ siê * drogimi klientami, którzy byli zbyt samotni w drodze. OdwiedŸ Soko³a Maltañskiego! Hub czeka na Ciebie! (muzyka zaczyna lecieæ od nowa)}
{382} {} {Ech, to za daleko. Poza tym zmierzam w zupe³nie innym kierunku...}
{383} {} {Zdobywasz doœwiadczenie za zlokalizowanie sygna³u radiowego z Kalifornii.}

{390}{}{[S³uchaj]}
{391}{}{"Bracia i siostry! Tu Rycerz Jerry. Zosta³em zaatakowany! Supermutanci przygwoŸdzili mnie w starej kawiarni w National City. Jestem ranny. Proszê o pomoc!"}
{392}{}{Ju¿ idê, bracie. Trzymaj siê z ca³ych si³!}
{393}{}{I dobrze, ¿elazny diable! Mam nadziejê, ¿e nikt ci nie pomo¿e.}
{394}{}{Uh, jakiœ ha³as, nic nie s³ysza³em, koniec.}
{1394}{}{Uh, jakiœ ha³as, nic nie s³ysza³am, koniec.}
{395}{}{Poczekaj, zaraz bêdê.}
{396}{}{Halo? Tutaj yyy... }
{397}{}{Zg³asza siê Rycerz }
{398}{}{Zg³asza siê Paladyn }
{399}{}{Zg³asza siê Zwiadowca }
{400}{}{. Czy ktoœ mnie s³yszy? Jestem w ruinach Blasku Dnia. Potrzebujê pomocy z zaopatrzeniem.}
{401}{}{Zg³asza siê kadet }
{402}{}{Witaj, }
{403}{}{. Tu Jerry z oddzia³u zwiadowczego. Dotrzyj do molo nr 9. Schowa³em tam trochê zapasów. Mam nadziejê, ¿e ci pomog¹.}
{404}{}{Dziêkujê, bracie Jerry. Bez odbioru.}
{405}{}{Wysokie promieniowanie t³a na wyspie Coronado powoduje zbyt wiele zak³óceñ.}
{406}{}{Prawdopodobnie muszê opuœciæ wyspê, ¿eby mieæ normalne po³¹czenie.}
{407}{}{Ska³y blokuj¹ s³aby sygna³ radia.}
{408}{}{Chyba bêdzie trzeba wróciæ na powierzchniê.}