# Do kontenerow
{100} {} {Hej, od³ó¿ to szybko!}
{101} {} {Dotknij to raz jeszcze, a zap³acisz.}
{102} {} {Rêce precz!}
{103} {} {Nie wiem, czego szukasz, ale tego tu nie ma. Rozumiesz?}
{104} {} {Tylko dotknij tego ponownie, a bêdziesz mieæ problemy.}
{105} {} {Nie dotykaj tego.}
{106} {} {Nie mów mi, ¿e „tylko szukasz swoich kluczy”.}
{107} {} {Wynoœ siê stamt¹d!}
{108} {} {Wiesz, nie jest dobrze okradaæ kogoœ innego.}

{109} {robots} {* Przeslij plakietke *}

# Do drzwi
{110} {} {Nie mo¿esz tam iœæ.}
{111} {} {Hej, ty! Co tam robisz?}
{112} {} {Nie mów mi, ¿e „tylko szukasz swoich kluczy”.}
{113} {} {Wynoœ siê stamt¹d, szybko!}
{114} {} {Tylko spróbuj, a bêdziesz mieæ problemy.}
{115} {} {Nie rób tego.}
{116} {} {Nawet o tym nie myœl. To nie jest zamkniête bez powodu.}
{117} {} {Wynoœ siê stamt¹d!}
{118} {} {Zostaw to w spokoju albo podejmê wyj¹tkowe dzia³anie na twojej dupie.}

{119} {robots} {* Przeslij plakietke *}

# Odpowiedzi podczas ataku na GG
{120} {people} {Koniec z ostrze¿eniami!}
{121} {roboty} {Wykryto intruza!}

{122} {} {W³aœcicielowi nie podoba siê, ¿e dotykasz jego rzeczy.}
{123} {} {W³aœciciel ciê nie wpuœci.}
{124} {} {Robot pilnuje tego magazynu.}
{125} {} {Robot strze¿e tego miejsca.}

{126} {} { nie pozwol¹ ci dotykaæ tych rzeczy.}
{127} {} { nie pozwol¹ ci dotykaæ tych rzeczy.}
{128} {} { nie pozwala ci wejœæ.}
{129} {} { nie pozwala ci wejœæ.}

{130} {} {No toques la puerta.}
