{101} {} {Widzisz maszynê idealn¹ do przygotowywania napojów alkoholowych.}
{102} {} {Widzisz maszynê idealn¹ do przygotowywania napojów alkoholowych. Ale najpierw musisz j¹ nape³niæ sk³adnikami.}
{103} {} {Uwarzenie alkoholu w bitwie bêdzie zbyt trudne.}

{110} {} {Aby zrobiæ tequilê, musisz nape³niæ maszynê surowcami.}
{111} {} {Okaza³o siê, ¿e nie jest to tak ³atwe, jak myœlisz. Najpierw musisz nauczyæ siê przepisu.}
{112} {} {Nape³niasz maszynê. U¿yj nauk œcis³ych, aby zrobiæ tequilê.}
{113} {} {Maszyna jest ju¿ w pe³ni na³adowana. Wiêcej surowców nie trzeba.}
{114} {} {Ten surowiec nale¿y wlaæ bezpoœrednio do pojemnika maszyny.}
{115} {} {Tequila z Pustkowi jest gotowa i czeka na butelkowanie.}
{116} {} {Otrzymujesz }
{117} {} { sztuk butelek tequili.}
{118} {} {Brakuje czegoœ.}

{120} {} {Maszyna jest w dobrym stanie i nie wymaga ¿adnych napraw.}
{121} {} {Zamkniêcie tych wszystkich butelek by³oby szczytem in¿ynierii. Dlaczego tylko ty na to wpad³eœ?}
{122} {} {Maszyna zniszczona. To wielka strata dla lokalnego siedliska pijañstwa.}
{123} {} {Ups...}