{110}{}{Automat sprzedaj¹cy wydaje towary tylko za pieni¹dze. O ile oczywiœcie nie zamierzasz tego obejœæ.}
{111}{}{Ten automat zosta³ ju¿ zhakowany.}
{112}{}{}
{113}{}{Zamek jest zbyt skomplikowany.}
{114}{}{U¿ywasz wytrych. Teraz ³atwiej bêdzie Ci otworzyæ ten zamek.}
{115}{}{Zamek ma ju¿ maksymaln¹ liczbê wytrychów.}
{116}{}{Dekoder elektroniczny nie nadaje siê do otwierania zamków mechanicznych.}
{117}{}{Otwierasz automat z towarami. Czas zobaczyæ, co zosta³o w œrodku.}
{118}{}{Teraz, gdy maszyna jest otwarta, nie ma to sensu.}
{119}{}{Otrzymujesz baterie.}
{120}{}{Automat sprzedaj¹cy jest niedostêpny.}
{121}{}{}
{122}{}{Nie mo¿esz obejœæ zabezpieczeñ automatu.}
