{108} {} {Aktualny stan: }
{109} {} {%.}
{110} {} {Przejœcie zablokowane, mo¿esz zniszczyæ tê przeszkodê m³otem kowalskim lub materia³ami wybuchowymi.}
{111} {} {Brakuje ci si³y. Spróbuj czegoœ mocniejszego.}
{112} {} {U¿ywaj¹c brutalnej si³y, usuwasz przeszkodê i torujesz sobie drogê.}
{113} {} {Eksplozja rozbija przeszkodê na ma³e kawa³ki.}
{114} {} {Wygl¹da na to, ¿e potrzebna jest ciê¿sza broñ.}
{115} {} {Uderzenie niszczy przeszkodê na wiele czêœci.}
{116} {} {Przeszkoda zniszczona w stopniu }
{117} {} {%.}
{118} {} {-}
{119} {} {%}
{120} {} {W tym przypadku pomo¿e tylko brutalna si³a.}
{121} {} {Trudno to podpaliæ zapalniczk¹.}
{122} {} {Poszukaj mocniejszego narzêdzia.}
{123} {} {Budowlanka najwyraŸniej nie jest Twoj¹ mocn¹ stron¹.}