{110} {} {Przechowywana jest tutaj cenna wiedza przedwojenna. Badanie jej nie bêdzie zbyteczne.}
{111} {} {Wydaje siê, ¿e nie jesteœ w stanie opanowaæ tak z³o¿onych informacji.}
{112} {} {To jest poza twoim zrozumieniem.}
{113} {} {Spêdzasz ca³y dzieñ na eksplorowaniu tego magazynu przedwojennej wiedzy. Teraz wiele sta³o siê jaœniejsze.}
{114} {} {Przeszukujesz wpisy i ale nie znajdujesz nic nowego.}
{115} {} {Terminal biblioteczny jest otwarty.}

{121} {} {Kaznodziei nie spodoba siê, jeœli bêdziesz studiowaæ pisma œwiête bez jego pozwolenia.}
{122} {} {Terminal biblioteczny wymaga karty dostêpu.}
{123} {} {Czytanie e-booków w obecnoœci gazu dusz¹cego jest œmiertelne.}
{124} {} {Obserwatorom nie spodoba siê, jeœli bêdziesz zag³êbiaæ siê w ich dane bez pozwolenia.}
{125} {} {Bractwo Stali nie da³o ci pozwolenia na przegl¹danie tej bazy danych.}
{126} {} {Lokalnym kultystom nie spodoba siê, jeœli bêdziesz przegl¹daæ ich ksi¹¿ki bez pozwolenia.}