{110} {} {Automat wydaje napój tylko za pieni¹dze. Chyba, ¿e zamierzasz to obejœæ.}
{111} {} {Ta maszyna zosta³a ju¿ zhakowana.}
{112} {} {}
{113} {} {Zamek jest za trudny.}
{114} {} {Wytrych zainstalowany. Teraz ³atwiej bêdzie Ci otworzyæ ten zamek.}
{115} {} {Zamek ma ju¿ maksymaln¹ liczbê wytrychów.}
{116} {} {Dekoder elektroniczny nie pomo¿e w otwieraniu zamków mechanicznych.}
{117} {} {Otwierasz automat z napojami. Czas zobaczyæ, co zosta³o w œrodku.}
{118} {} {Teraz, gdy automat jest otwarty, nie ma to sensu.}
{119} {} {Otrzymujesz butelkê ciep³ej, wygazowanej Nuka Coli.}
{120} {} {W automacie skoñczy³y siê napoje.}
{121} {} {}
{122} {} {Nie mo¿esz obejœæ mechanizmu obronnego maszyny.}