#Genera³
{110} {} {Musisz zamkn¹æ drzwi przed zablokowaniem k³ódki.}
{111} {} {Zamykasz zamek.}
{112} {} {Otwierasz zamek.}
{113} {} {Bêdzie to zbyt trudne w walce.}
{114} {} {Zamek zablokowany.}
{115} {} {Ani œladu po drzwiach.}
{116} {} {Eksplozja nawet nie porysowa³a drzwi.}
{117} {} {Musisz zamkn¹æ drzwi przed zablokowaniem zamka.}

# Spróbuj otworzyæ
{120} {} {Odkrywasz, ¿e }
{121} {} { s¹ wyposa¿one w niebezpieczn¹ pu³apkê.}
{122} {} {Odkrywasz, ¿e }
{123} {} { by³y wyposa¿one w pu³apkê!}
{124} {} { by³a wyposa¿ona w pu³apkê!}

# Umiejetnosci
{130} {} {Ta umiejêtnoœæ jest tutaj bezu¿yteczna.}
{131} {} {zablokowane.}
{132} {} {ma zamek o poziomie trudnoœci }
{133} {} {.}
{134} {} {Dobrym pomys³em mo¿e byæ sprawdzenie pu³apek.}
{135} {} {Próba w³amania nie powiod³a siê. Spróbuj ponownie.}
{136} {} {}
{137} {} {Próba hakowania nie powiod³a siê.}
{138} {} {Maj¹c tak niskie umiejêtnoœci, nic nie zdzia³asz.}
{139} {} {Ten zamek jest zbyt skomplikowany.}

# Zepsuty zamek
{140} {} {Niestety, ten zamek zosta³ uszkodzony fizycznie. I to na zawsze.}
{141} {} {Ten zamek jest ju¿ zepsuty.}
{142} {} {Nie ma sensu otwieraæ zamka.}
{143} {} {Tej blokady nie mo¿na z³amaæ brutaln¹ si³¹.}
{144} {} {Potrzeba * bardzo * du¿ej si³y, aby wy³amaæ ten zamek.}
{145} {} {Brutaln¹ si³¹ wy³amujesz zamek. Nikt inny nie mo¿e go ju¿ zamkn¹æ.}
{148} {} { jest zabezpieczony pu³apk¹!}
{149} {} {Broni nale¿y u¿ywaæ w trybie walki.}
# U¿yj trybu walki, aby z³amaæ te blokade.

#Majdan
{150} {} {Nie mo¿esz zlokalizowaæ pu³apki.}
{151} {} {}
{152} {} {}
{153} {} {Znajdujesz pu³apkê, ale nie mo¿esz jej rozbroiæ.}
{154} {} {To by³ b³¹d! Byæ mo¿e w przysz³ym razie nie pozwolisz na to.}
{155} {} {Uda³o ci siê rozbroiæ pu³apkê prymitywów.}
{156} {} {Uda³o ci siê rozbroiæ pu³apkê starym nabojem kal. 12.}
{157} {} {Uda³o ci siê rozbroiæ pu³apkê z granatem od³amkowym.}
{158} {} {Uda³o ci siê rozbroiæ elektroniczn¹ pu³apkê.}
{159} {} {Pomyœlnie uda³o ci siê wy³¹czyæ alarm.}

# Przedmiotow
{160} {} {To prawie nie pomaga z zepsutym zamkiem.}
{161} {} {Wytrych zainstalowany. Teraz ³atwiej bêdzie Ci otworzyæ ten zamek.}
{162} {} {Zamek ma ju¿ maksymaln¹ liczbê wytrychów.}
{163} {} {Dekoder elektroniczny nie pomo¿e w otwieraniu zamków mechanicznych.}
{164} {} {Ten zamek wymaga innego klucza.}
{165} {} {Ten klucz jest nieprawid³owy. Trudno bêdzie znaleŸæ klucz do tego zamka.}
{166} {} {Wybuch rozrywa drzwi na kawa³ki.}
{167} {} {Ten wytrych nie pomo¿e w ³amaniu zamków elektronicznych.}
{168} {} {Jeden dekoder jest ju¿ zainstalowany.}
{169} {} {Dekoder zainstalowany. Teraz ³atwiej bêdzie Ci otworzyæ ten zamek.}
{170} {} {Lopata tutaj nie zadzia³a.}
{171} {} {Ten klucz jest nieprawid³owy.}