#Szczegolowy opis
{101} {} {Widzisz zwyk³y automat do gry.}
{102} {} {Widzisz dziwny samochód.}
{103} {} {Widzisz automat do gry.}
{104} {} {Widzisz b³yszcz¹cy automat do gry.}
{105} {} {Widzisz b³yszcz¹cy automat do gry.}

# Interakcja, uzycie umiejêtnoœci i przedmiotów
{110} {} {Hakowanie tej maszyny nic nie da.}
{111} {} {Ta fajna maszyna wydaje dŸwiêki i œwieci. W Villi takich nie ma.}
{112} {} {Ta konkretna maszyna nie wymaga naprawy.}
{113} {} {To bêdzie bardzo niewygodne podczas walki.}
{114} {} {Ta maszyna wymaga specjalnego ¿etonu do gry.}
{115} {} {W tej maszynie skoñczy³y siê ¿etony. Bêdzie trzeba do niej wróciæ po do³adowaniu.}
{116} {} {Nie masz pojêcia, co z tym zrobiæ.}
{117} {} {W³ó¿ kostkê do gry.}
{118} {} {Twój zak³ad: }
{119} {} {.}
{120} {} {Niestety, maszyna nie mo¿e przyj¹æ wiêcej zak³adów z powodu braku w³asnych ¿etonów.}
{121} {} {Osi¹gniêto maksymalny zak³ad (20 ¿etonów).}
{122} {} {Te tokeny nie s¹ odpowiednie dla tej maszyny.}
{123} {} {}
{124} {} {}

# Zwroty powyzej GG, gdy przegrywasz i nie masz ¿etonów w kieszeni
{125} {} {Hej, to rozbój w bia³y dzieñ!}
{126} {} {To by³ mój ostatni ¿eton...}
{127} {} {To nie bêdzie ³atwe do odzyskania.}
{128} {} {Cholera! Ta maszyna zjad³a moje ostatnie ¿etony!}
{129} {} {Cholera! Nie mam pieniêdzy!}

# Repliki nad maszyna
{130} {} {* Ding *}
{131} {} {* Ding *}
{132} {} {* Bz-z-z *}
{133} {} {* Tr-r-r *}
{134} {} {* Graj ze mn¹ *}
{135} {} {* Hej, czeœæ *}
{136} {} {* Polubisz mnie *}
{137} {} {* Dryñ *}
{138} {} {* Ding-dong *}
{139} {} {* Kurwa *}
{140} {} {}
{141} {} {}
{142} {} {}
{143} {} {}
{144} {} {}
{145} {} {}
{146} {} {}
{147} {} {}
{148} {} {}
{149} {} {}

# Repliki podczas gry
{150} {} {Przegrywasz.}
{151} {} {Przegrywasz. Musisz sobie z tym poradziæ.}
{152} {} {Twój zak³ad wygas³.}
{153} {} {Wydaje siê, ¿e automat z ciebie kpi. Przegrywasz.}
{154} {} {Przegrywasz. Dzisiaj zdecydowanie nie jest twój dzieñ.}

{155} {} {Wygrywasz }
{156} {} { ¿etony.}
{157} {} { ¿etonów.}
{158} {} { ¿etonów. Dobra gra!}
{159} {} { JACKPOT!}

# Nazwy bebnow
{160} {} {URAN}
{161} {} {PLUTONIUM}
{162} {} {RADIUM}
{163} {} {POLONY}
{164} {} {RADON}
{165} {} {BERILLIUM}
{166} {} {MERCURY}
{167} {} {TELLURUS}
{168} {} {TORIUM}
{169} {} {LEAD}

{170} {} {-}
{171} {} {ATOM}
{172} {} {BOMB}
{173} {} {CHMURA}
{174} {} {KOWBOJ}
{175} {} {SIEDEM}
{176} {} {GUN}
{177} {} {PROWADZACY}
{178} {} {}
{179} {} {}