{110} {} {Ta umiejêtnoœæ nie ma tutaj zastosowania.}
{111} {} {Trudno jest wykopaæ dziurê w walce.}
{112} {} {Nie mo¿esz nawet podnieœæ takiej ³opaty.}
{114} {} {Musisz ciê¿ko pracowaæ, ¿eby zajrzeæ do œrodka.}
{115} {} {Ktoœ niedbale pochowa³ tu psa. I ten ktoœ najwyraŸniej siê œpieszy³.}
{116} {} {Nie mo¿esz tak po prostu zakopaæ tej dziury.}
{117} {} {Podczas kopania grób nagle zacz¹³ siê kruszyæ i przeniós³ ciê do podziemnej pustki.}
{118} {} {Co do diab³a...}
{119} {} {Ay-yay-yay...}
{120} {} {Czeluœæ jest doœæ g³êboka.}