{110} {} {Do korzystania z pu³apki wymagane s¹ umiejêtnoœci.}
{111} {} {Um! Te iguany nie by³y wystarczaj¹co zwinne i wkrótce trafi¹ do czyjegoœ ¿o³¹dka.}
{112} {} {- z takimi umiejêtnoœciami ta pu³apka bêdzie bardziej bezu¿yteczna ni¿ œmieci.}
{113} {} {Zwierzyna siê skoñczy³a, ta pu³apka jest teraz bezu¿yteczna.}
{114} {} {Dwie pu³apki w jednym miejscu? To strata czasu.}
{115} {} {Uda³o ci siê zastawiæ pu³apkê.}
{116} {} {To dobry pomys³, ale nie wiesz jak to zrobiæ.}