{110} {} {Nie uda³o ci siê nauczyæ jeszcze niczego nowego. Warto zbadaæ sprawê bardziej metodycznie.}
{111} {} {?}
{112} {} {Analiza systemu nie jest twoj¹ mocn¹ stron¹.}
{113} {} {Tego nie mo¿na naprawiæ.}
{114} {} {Do badania tego obiektu nale¿y u¿yæ nauk œcis³ych.}
{115} {} {Co TO tu robi?}

# 20 linii jest przydzielonych do jednej lokalizacji.
# Dla ka¿dego obiektu tworzone s¹ 2 sasiednie liniê:
# - pierwsza pod-wiadomoœæ w logu
# - drugi pod replika nad GG (jeœli nie jest potrzebny, wstaw w nim spacje, w przeciwnym razie GG powie Error)

#Villa
{200} {} {Widzisz stary fotel po³o¿niczy. Urodzi³eœ siê w nim.}
{201} {} {Niezbyt przyjemne wspomnienia}
{202} {} {Ta staro¿ytna technika nie dzia³a, poniewa¿ jest zardzewia³a od wilgoci.}
{203} {} {Nie dzia³a. I nie zadzia³a.}
{204} {} {Widzisz komputer tak stary, ¿e jego czêœci s¹ ju¿ ca³kowicie zardzewia³e. Nie by³ u¿ywany przez co najmniej czterdzieœci lat. Nie jest to zaskakuj¹ce dla Villi.}
{205} {} {Ojciec nigdy mi o tym nie powiedzia³...}
{206} {} {Dochodzisz do wniosku, ¿e symbol przedstawia skrzydlat¹ istotê wylatuj¹c¹ z ognia. Ale nie widaæ dok³adnie co to.}
{207} {} {Na pewno zostawili to obcy, którzy tu byli.}
{208} {} {Jedno z osi¹gniêæ lokalnej in¿ynierii. Od dzieciñstwa nie wolno by³o siê z nim widywaæ, poniewa¿ wszystkie wakaty zosta³y zajête.}
{209} {} {Wygl¹da na to, ¿e czêœæ naszej ceramiki zosta³a sprzedana s¹siednim osadom.}

#Jackals
{210} {} {}
{211} {} {}
{212} {} {}
{213} {} {}
{214} {} {Widzisz prawdopodobnie atomowy silnik odrzutowy. Ta technologia jest zbyt skomplikowana dla wspó³czesnego œwiata.}
{215} {} {To zajmie BARDZO du¿o pracy, aby samo ruszy³o.}
{216} {} {Ten sprzêt kontrolowa³ dostarczanie z³o¿onej mieszaniny gazów do œrodka. Niedawno zosta³ automatycznie wy³¹czony przez wewnêtrzny zegar.}
{217} {} {Wow, musieli spaæ od dziesiêcioleci.}
{218} {} {Ta struktura desek i czaszek prawdopodobnie reprezentuje coœ z czasów przedwojennych. Na kawa³ku skóry widzisz cyfrê 15.}
{219} {} {Echo staro¿ytnoœci, które straci³o na znaczeniu.}

#Flagpool
{220} {} {Wygl¹da na to, ¿e czasami przeprowadza siê tu operacje, a piwnica zag³usza krzyki chorych.}
{221} {} {I to bez zasad higieny...}
{222} {} {Informacje na budce nie odpowiadaj¹ rzeczywistoœci. Wygl¹da na to, ¿e pochodzi to z czasów przedwojennych.}
{223} {} {Ten element jest starszy ni¿ kolonia.}
{224} {} {Dostrzegasz staro¿ytny plakat zachêcaj¹cy kobiety do ciê¿kiej pracy na wojnie.}
{225} {} {W Villi pracuj¹ i bez ¿adnej wojny czy zachêty.}
{226} {} {Napis brzmi „Muzeum Pó³nocnej Arizony”. Pod podpisem: „Muzeum, sklep i biblioteka”.}
{227} {} {Nie wiem co to jest to „muzeum”.}
{228} {} {Patrz¹c z zainteresowaniem na staro¿ytny eksponat, nieoczekiwanie znajdujesz u jego stóp zapomniany granat.}
{229} {} {Sk¹d to siê tu wziê³o?}

# San Brahmin
{230} {} {Ten eksponat budzi jednoczeœnie podziw i strach.}
{231} {} {Dobrze, ¿e na œwiecie nie ma ju¿ takich potworów... prawdopodobnie.}
{232} {} {S¹ tu napisane tytu³y ró¿nych filmów. Nigdy ich nie widzia³eœ. W ogóle nie widzia³eœ ¿adnych filmów.}
{233} {} { }

#Phoenix
{240} {} {Dostrzegasz ukryte kamery CCTV, pozwalaj¹ Aaronowi mieæ oko na katedrê.}
{241} {} {Wygl¹da na to, ¿e Lord Phoenix ma obsesjê na punkcie bezpieczeñstwa i kontroli.}
{242} {} {Po przejrzeniu statystyk wygranych dochodzisz do pewnych wniosków. Teraz twoja gra w ruletkê bêdzie skuteczniejsza o 15%.}
{243} {} {Hej, czasami mo¿esz skorzystaæ z zu¿ycia czêœci.}
{244} {} {Poznajesz przepis na Tequilê Pustkowi.}
{245} {} {Teraz jest dla mnie jasne, dlaczego nikt oprócz kasyna tego nie robi.}
{246} {} {Znasz ju¿ przepis na Tequilê Pustkowi.}
{247} {} {Mam doœæ tych numerów.}
{248} {} {Ten pos¹g nie ma ¿adnych podpisów. Mo¿esz siê tylko domyœlaæ, dlaczego umieœcili to tutaj.}
{249} {} {Wygl¹da ca³kiem... stosownie. Dla tych ruin.}

# Tu-San, Krypta 27
{250} {} {Ten komputer zosta³ zbudowany przez Blacharzy z ró¿nych komponentów. O dziwo, dzia³a œwietnie.}
{251} {} {Wygl¹da na to, ¿e Blacharze radz¹ sobie ca³kiem nieŸle.}
{252} {} {Sczernia³e sztabki z³ota. Mówi¹, ¿e kiedyœ mia³y wysok¹ wartoœæ, ale teraz nikt nie zap³aci za nie nawet jednego kapsla.}
{253} {} {To z³oto ju¿ dawno straci³o na wartoœci.}
{254} {} {Znajdujesz dane niewolników wœród zleceñ p³atniczych. Przewa¿nie s¹ transportowani do Tu-San.}
{255} {} {Mo¿e muszê pojechaæ do Tu-San i tam poszukaæ niewolników?}
{256} {} {Na odwrocie obrazu znajdujesz ledwo czytelny kod.}
{257} {} {Hmm, co oznaczaj¹ te liczby?}
{258} {} {Ci najemnicy zostali zabici przez gwa³town¹ eksplozjê. Dostrzegasz jednak, ¿e jeden z nich zosta³ równie¿ postrzelony w g³owê pociskiem 10mm.}
{259} {} {Nie powinienem na to patrzeæ zbyt d³ugo.}

#Rangers, Quartzsite
{260} {} {Ten staro¿ytny znak wskazuje odleg³oœæ do tamy. U góry znajduje siê napis: „Ranger Territory”.}
{261} {} {Dalej po drodze jest Parker Dam - twierdza Rangersów.}
{262} {} {Przygl¹dasz siê uwa¿nie mapom Rangersów. Podró¿owanie po okolicy bêdzie teraz znacznie ³atwiejsze.}
{263} {} {Wow, kartograf nie traci³ czasu.}
{264} {} {Kartograf nie pozwala ci przekopaæ siê przez swoje dokumenty.}
{265} {} {   }
{266} {} {Rangersi polegaj¹ bardziej na sobie ni¿ na technologii. Nawet z tego rodzaju technologi¹ tu¿ pod nosem.}
{267} {} {Ten komputer nie by³ u¿ywany przez d³ugi czas.}
{268} {} {"Ostrze¿enie! Obszar chroniony. Wszystkie osoby na tym obszarze podlegaj¹ federalnej ustawie o ochronie tej witryny."}
{269} {} {Ten znak prawdopodobnie przetrwa³ z czasów przedwojennych.}
{270} {} {Widzisz zaimprowizowany „reaktor”, który miejscowi bezskutecznie próbowali zmontowaæ. Awaria przerodzi³a siê w wypadek i napromieniowanie terenu.}
{271} {} {Wiêc to siê tutaj wydarzy³o.}
{272} {} {Informacje dla odwiedzaj¹cych: „Quartzsite, za³o¿one w 1879, wysokoœæ 879”.}
{273} {} {W przesz³oœci musia³o byæ du¿o ludzi przeje¿dzaj¹cych przez to miasto.}
{274} {} {"Parker Dam, za³o¿ona w 1934-1938, odnowiona w 2055."}
{275} {} {To * bardzo * stary budynek, bez w¹tpienia.}
{276} {} {Stary znak drogowy. Na górze widaæ Znak Rangersów.}
{277} {} {Ten znak oznacza, ¿e wioska jest pod ochron¹ Rangersów.}
{278} {} {}
{279} {} {}

# Inne lokalizacjê
{280} {} {"Pomnik ofiar aneksji i zamieszek granicznych 2051r."}
{281} {} {Wiêc Stany Zjednoczone zaanektowa³y Meksyk?}
{282} {} {Zabezpieczenia wy³¹czone.}
{283} {} {I jak ci siê to podoba, zardzewia³a puszko?}
{284} {} {"Uwaga podró¿niku! Alkohol, narkotyki i swobodne noszenie broni s¹ tu zabronione. Za kradzie¿ plonów - kara œmierci. W nocy obowi¹zuje godzina policyjna."}
{285} {} {Sporo zasad do zapamiêtania.}
{286} {} {Logowanie goœcia koñczy siê w 2077.}
{287} {} {Nic ciekawego.}
{288} {} {To zdjêcie ma ponad sto lat. Zaskakuj¹ce jest, ¿e w ogóle przetrwa³o.}
{289} {} {Czy ta rêka jest narysowana?}

#Puerto
{290} {} {Czêstotliwoœci radiowe Bractwa Stali skopiowane.}
{291} {} {Swietnie, teraz mogê pods³uchiwaæ patrole Bractwa.}
{292} {} {Ta drabina prowadzi w dó³. Co za niespodzianka.}
{293} {} {?}
{294} {} {Przygl¹dasz siê uwa¿nie mapom Bractwa Stali. Podró¿owanie po okolicy bêdzie teraz znacznie ³atwiejsze.}
{295} {} {Zwiadowcy Bractwa nie dostaj¹ swoich racji za nic.}
{296} {} {Bezskutecznie próbujesz znaleŸæ Villê. Ale jesteœ zdumiony skal¹ kontynentu.}
{297} {} {Czy œwiat naprawdê jest taki du¿y?}
{298} {} {Ten indeks powitalny jest dwujêzyczny, hiszpañski i angielski.}
{299} {} {Te ruiny musia³y byæ kiedyœ ³adnym miejscem...}

{300} {} {Ten sprzêt s³u¿y do po³¹czeñ miejscowej ludnoœci z Puerto Penasco.}
{301} {} {Standardowy nadajnik radiowy.}
{302} {} {Ten sprzêt by³ kiedyœ u¿ywany do po³¹czeñ mieszkañców z Puerto Penasco.}
{303} {} {Standardowy nadajnik radiowy.}

#Blysk Dnia
{310}{}{W tej sali odbywa³y siê spotkania religijne.}
{311}{}{"...I bêdziemy siê nazywaæ Wyznawcami Apokalipsy. Aby oczyœciæ œwiat z grzechów naszych przodków."}
{312}{}{W tej sali odbywa³y siê konferencje naukowe.}
{313}{}{"...Musimy wykorzystaæ nasz¹ wiedzê, aby odbudowaæ cywilizacjê po wojnie nuklearnej."}
{314}{}{Trasa nr 8 prowadzi na pó³noc do Starego Miasta. Trasa nr 805 prowadzi na wschód do tamy.}
{315}{}{Te znaki wskazuj¹, ¿e zaraz bêdzie rozwidlenie dróg.}
{316}{}{Wœród œmieci znajdujesz kartkê papieru z szeœcioma liczbami, postanawiasz je zapamiêtaæ.}
{317}{}{Wygl¹da to jak jakiœ kod.}
{318}{}{To pierwszy raz, kiedy widzisz telewizor w akcji. Widok jest raczej... rozczarowuj¹cy.}
{319}{}{I ludzie w przesz³oœci z jakiegoœ powodu ogl¹dali ten ha³as?}