{102} {} {To nie ma sensu.}
{103} {} {Mo¿na to podpaliæ, aby oœwietliæ teren.}

{110} {} {Zapalasz lampê. Jej s³abe œwiat³o ledwo przenika przez ciemnoœæ piwnic.}
{111} {} {Widzisz lampê zawieraj¹c¹ jeszcze trochê oleju. Pozostaje tylko podpaliæ go, by oœwietliæ piwnicê.}
{112} {} {Widzisz lampê, s³abo oœwietla piwnicê.}
{113} {} {W tej lampie skoñczy³ siê olej.}
{114} {} {Ogieñ i dym odstraszaj¹ lokalne kojoty.}