{110} {} {Automat wydaje towary tylko za pieni¹dze. Chyba, ¿e oczywiœcie zamierzasz go zhakowaæ.}
{111} {} {Ten automat sprzedaj¹cy zosta³ ju¿ zhakowany.}
{112} {} {}
{113} {} {Zamek jest za trudny.}
{114} {} {Wytrychy zainstalowane. Teraz ³atwiej bêdzie Ci otworzyæ ten zamek.}
{115} {} {Zamek ma ju¿ maksymaln¹ liczbê wytrychów.}
{116} {} {Dekoder elektroniczny nie pomo¿e w otwarciu zamka mechanicznego.}
{117} {} {Otwierasz automat z towarami. Czas zobaczyæ, co zosta³o w œrodku.}
{118} {} {Teraz, gdy automat jest otwarty, nie ma to sensu.}
{119} {} {Otrzymujesz mentaty.}
{120} {} {W automacie skoñczy³ siê towar.}
{121} {} {}
{122} {} {Nie potrafisz obejœæ mechanizmu obronnego automatu.}