{101} {} {Widzisz automat z gazetami. Ca³ym swym wygl¹dem przypomina minion¹ epokê.}
{102} {} {Automat z gazetami zosta³ ju¿ otwarty.}
{103} {} {Pokrywa automatu z gazetami jest szczelnie zamkniêta i nie daje siê otworzyæ.}
{104} {} {Zamek nie nadaje siê do u¿ycia, jest zatarty z powodu brudu i rdzy.}
{105} {} {Otwierasz pokrywê automatu z gazetami. Teraz wszystko, co tu le¿y, nale¿y do Ciebie.}
{106} {} {Mam dzisiaj cholerne szczêœcie.}