{110} {} {Emiter jest uszkodzony i nie dzia³a. Nie mo¿na tego naprawiæ w obecnej sytuacji.}
{111} {} {Ta umiejêtnoœæ nie pomo¿e tutaj.}
{112} {} {Emiter jest ponownie dostrojony do innej czêstotliwoœci.}
{113} {} {Masz problem ze zrozumieniem systemu emitera. Mo¿e to wina twoich umiejêtnoœci, a mo¿e to coœ innego.}
{114} {} {Pole si³owe w³¹czone.}
{115} {} {Pole si³owe wy³¹czone.}
{116} {} {Bêdzie to zbyt trudne podczas walki.}
{117} {} {Dekoder pod³¹czony. Teraz ³atwiej bêdzie ci zhakowaæ ten system.}
{118} {} {Nie ma gdzie pod³¹czyæ drugiego dekodera.}
{119} {} {Nie mo¿esz ponownie wyregulowaæ emitera mocy.}