{110} {} { - kolejna przeszkoda. Maj¹c wiêksz¹ si³ê lub materia³y wybuchowe, da³oby siê usun¹æ tê przeszkodê.}
{111} {} {Brakuje ci si³y, by rozebraæ tê górê kamieni.}
{112} {} {U¿ywaj¹c brutalnej si³y, usuwasz przeszkodê i torujesz sobie drogê.}
{113} {} {Eksplozja wyrzuca kamienie we wszystkich kierunkach.}
{114} {} {Wygl¹da na to, ¿e potrzebna jest ciê¿sza broñ.}
{115} {} {Nie mo¿na kopaæ podczas walki.}
{116} {} {Tutaj potrzebny jest specjalny sprzêt.}