{110} {} {Wygl¹da to jak }
{111} {} { - niestety nie dzia³a, ale nadal mo¿na to naprawiæ.}
{112} {} {To }
{113} {} {, dzia³a. I bêdzie dzia³aæ przez jakiœ czas.}
{114} {} {Ju¿ naprawiono obiekt o nazwie }
{115} {} {.}
{116} {} {Pomyœlnie naprawiasz obiekt }
{117} {} {. Teraz przez chwilê bêdzie zapewniaæ stabilne œwiat³o.}
{118} {} {Naprawa nie powiod³a siê. Mo¿e powinieneœ poprawiæ swoje umiejêtnoœci naprawy.}
{119} {} {Pope³niasz b³¹d. Spróbuj ponownie.}
{120} {} { - obiekt teraz ju¿ ca³kowicie niesprawny z powodu twojej niekompetencji.}
