{110} {} {Zbierane s¹ tutaj komponenty z ró¿nych rodzajów amunicji. Dziêki zaawansowanym umiejêtnoœciom mo¿esz zrobiæ z nich coœ po¿ytecznego.}
{111} {} {Zosta³y tylko bezu¿yteczne œmieci.}
{112} {} {Dziêki tej umiejêtnoœci po prostu zmarnujesz materia³y.}
{113} {} {Amunicja zosta³a stworzona i znajduje siê w twoim plecaku.}
{114} {} {Uda³o Ci siê stworzyæ: }
{115} {} {.}
{116} {} {Tworzysz trochê paliwa.}

{200} {} {Zbierane s¹ tutaj komponenty z ró¿nych rodzajów amunicji. Musisz wybraæ, poniewa¿ masz ograniczone zapasy o³owiu i prochu.}
{201} {} {Nie teraz.}
{202} {} {Inne.}
{203} {} {Wstecz.}
{204} {} {.}
{205} {} {Jest wystarczaj¹co du¿o komponentów dla }
{206} {} {szt. (bior¹c pod uwagê twoje obecne umiejêtnoœci naprawy).}
{207} {} {Tego potrzebujê. A teraz przejdŸmy do rzeczy!}
{208} {} {Nie teraz.}