{110} {} {To mini laboratorium jest wype³nione ró¿nymi elementami. Potrzeba wiedzy, aby zrobiæ z nich coœ po¿ytecznego.}
{111} {} {To mini laboratorium jest puste i ju¿ bezu¿yteczne.}
{112} {} {Zaczynasz ¿a³owaæ ma³ej iloœci czasu  poœwiêconego na podrêczniki do chemii.}
{113} {} {Po wielu przygotowaniach uda³o ci siê stworzyæ jeden stymulant.}
{114} {} {Po wielu przygotowaniach uda³o ci siê stworzyæ dwa stymulanty.}
{115} {} {Po d³ugich przygotowaniach uda³o ci siê stworzyæ trzy stymulanty.}
{116} {} {Uda³o ci siê stworzyæ trochê paliwa.}
