{100} {} {Jeden-dwa, sprawdŸ nr 1.}
{101} {} {Raz, dwa, sprawdŸ nr 2.}
{102} {} {Jeden-dwa, sprawdŸ nr 3.}

{110} {} {Ten magazyn zbo¿a zosta³ ograbiony do czysta.}
{111} {} {Ratusz zosta³ zniszczony i spl¹drowany. Slady walki s¹ widoczne wszêdzie wokó³.}
{112} {} {To jedyny zachowany budynek - cichy œwiadek staro¿ytnoœci. Wygl¹da na to, ¿e ktoœ niedawno tu by³.}
{113} {} {Budynek punktu kontrolnego, zosta³ spl¹drowany przez niewolników.}
{114} {} {S¹dz¹c po licznych œladach, bandyci spêdzili tu kilka dni czekaj¹c na karawanê.}
{115} {} {Ta chata wygl¹da na opuszczon¹, ale dostrzegasz na pod³odze kilka kropel krwi.}
{116} {} {Ta chata wydaje siê byæ opuszczona dawno temu.}
{117} {} {Dawno opuszczony i ograbiony zak³ad alkoholowy. Ktoœ tu urz¹dzi³ ³ó¿ko.}
{118} {} {Stary zniszczony dom. Nie da siê tu mieszkaæ.}
{119} {} {Budynek jest pe³en œladów. Wydaje siê, ¿e mieszkañcy spêdzili tu du¿o czasu.}
{120} {} {Chata przywódcy spo³ecznoœci. W³aœciciel utrzymywa³ porz¹dek nawet w tym chaosie.}
{121} {} {Wejœcie do klubu zwraca na ciebie du¿¹ uwagê. Odwiedzaj¹cy oceniaj¹ Ciê z uwag¹ i wkrótce potem wracaj¹ do swoich spraw.}
{122} {} {Ten duszny barak jest wype³niony zapachem rdzy i gumy.}
{123} {} {W tej bibliotece panuj¹ cisza i spokój.}
{124} {} {Prywatne biuro Phoenix Sovereign, wyró¿nia siê wyrafinowaniem i luksusem.}
{125} {} {W tym ciemnym, dusznym pokoju panuje ba³agan.}
{126} {} {To twój apartament. Wreszcie mo¿esz odpocz¹æ po wyczerpuj¹cej podró¿y.}
{127} {} {To pakiet. Wygl¹da imponuj¹co na tle otaczaj¹cej beznadziejnoœci.}
{128} {} {Droga przed tob¹ urywa siê w gruzach zrujnowanych budynków.}
{129} {} {Ugh, ta rodzina na pewno mia³a coœ do ukrycia.}
{130} {} {To by³a przepompownia. Miejscowi zabrali st¹d wszystko, co mo¿na by³o wykorzystaæ w ¿yciu codziennym.}
{131} {} {To miejsce okropnie œmierdzi.}
{132} {} {Ludzie z karawany za³o¿yli swój barak w tym starym budynku. Jest w nim duszno, g³oœno i œmierdzi potem.}
{133} {} {Bar jest od dawna opuszczony i spl¹drowany. Wygl¹da na to, ¿e dawno temu mia³a tu miejsce strzelanina.}
{134} {} {Ten budynek jest od dawna opuszczony. Wygl¹da na to, ¿e kiedyœ by³o tu k¹pielisko, ale teraz nie ma tu ani kropli wody.}
{135} {} {Ten du¿y dom wyró¿nia siê bogat¹ dekoracj¹ i wzgledn¹ czystoœci¹.}
{136} {} {Droga przed tob¹ koñczy siê nieprzejezdnymi ruinami. Bêdzie trzeba znaleŸæ inn¹ drogê.}
{137} {} {Przed sob¹ widzisz wysoki budynek z oœwietlonymi oknami. Przed nim wêdruje ca³y t³um dzikich upiorów.}
{138} {} {Tabliczka przy wejœciu g³osi: „Otwarte! Noszenie broni w kasynie jest zabronione”.}
{139} {} {Ten supermarket zosta³ zniszczony przez falê uderzeniow¹. Wielu jego goœci zginê³o na miejscu.}
{140} {} {Ten sklep mocno oberwa³ podczasz wybuchu. Jego œciany chyba zaraz siê rozpadn¹.}
{141} {} {Dalszy po³udniowy wschód to szczególnie zrujnowane dzielnice. Wygl¹da na to, ¿e znajdowa³o siê tam epicentrum wybuchu j¹drowego. Nic nie przetrwa³o.}
{142} {} {Ten budynek biurowy zosta³ niedawno opuszczony. Robotnicy w poœpiechu wyrzucali swoje rzeczy.}
{143} {} {To miejsce jest sterylne. Nie potrafisz przyzwyczaiæ siê do tego zapachu, ale to dlatego, ¿e jest ci nowy.}
{144} {} {Dawny budynek hotelu od dawna jest opuszczony. Wygl¹da na to, ¿e ktoœ wyniós³ st¹d wszystko, co cenne, w tym meble.}
{145} {} {Wnêtrze restauracji jest ciemne i obskórne. Lepiej uwa¿nie patrzeæ pod nogi.}
{146} {} {W piwnicy brzydko pachnie... moczem i starymi szmatami.}
{147} {} {Wygl¹da na to, ¿e ktoœ samemu wykopa³ ten staro¿ytny kana³ œciekowy.}
{148} {} {Te pojemniki na pewno nie s¹ szczelne. Wylewa siê z nich do morza ropa, a jej opary mog¹ wybuchn¹æ od byle iskier.}
{149} {} {Wokó³ latarni morskiej widaæ wiele œladów bosych ludzkich stóp.}
{150}{}{Droga dalej na pó³noc ginie w piasku.}
{151}{}{T¹ drog¹ uda³o ci siê tu przybyæ z Sonory. Aby wróciæ, poczekaj w punkcie zbiórki.}
{152}{}{Dalsza droga jest zablokowana przez zawalone budynki.}