# Wiadomosci powitalne w dzienniku przy pierwszym wejœciu na mapê
# Numer jest zdefiniowany jako 100 + numer karty przez MAPS.TXT
# Jeœli wiadomoœæ nie jest potrzebna, pozostaw liniê pusta (bez znaków i spacji).
# Nie usuwaj pustych linii pomiedzy 100-150! W przeciwnym razie podczas gry w dzienniku pojawi siê b³¹d.
{100} {} {}
{101} {} {}
{102} {} {}
{103} {} {}
{104} {} {}
{105} {} {}
{106} {} {}
{107} {} {}
{108} {} {}
{109} {} {}
{110} {} {}
{111} {} {}
{112} {} {}
{113} {} {}
{114} {} {}
{115} {} {}
{116} {} {}
{117} {} {}
{118} {} {}
{119} {} {}
{120} {} {}
{121} {} {Po d³ugiej podró¿y wracasz do swojej rodzinnej wioski. Ale zamiast przywitaæ ciê z otwartymi ramionami, Villa wita ciê ponur¹ cisz¹.}
{122} {} {}
{123} {} {Schodzisz do piwnicy. Smierdzi tu wilgoci¹ i odchodami szczurów.}
{124} {} {}
{125} {} {Przybywasz do Kolonii Flagpool. Jest tu zaskakuj¹co t³oczno.}
{126} {} {Wchodzisz na teren garnizonu i zak³adu karnego kolonistów. Swoich wspó³plemieñców znajdziesz najpewniej za kratkami.}
{127} {} {}
{128} {} {Ruiny starego miasta. Przygnêbiaj¹cy widok tych ruin nie budzi zaufania.}
{129} {} {Jesteœ u bram Garage City. Rdz¹ i gum¹ od tej osady czuæ na milê.}
{130} {} {}
{131} {} {}
{132} {} {Droga do obozu nomadów zosta³a nieoczekiwanie zablokowana przez jednostkê wojskow¹.}
{133} {} {Uda³o ci siê dostaæ do obozu plemiennego schowanego wœród wydm.}
{134} {} {Docierasz w okolice wybiegów. Utrzymuj¹cy siê tu zapach byd³a mo¿na wyczuæ z odleg³oœci mili.}
{135} {} {Przybywasz do osady Blacharzy. Za bram¹ widoczne s¹ niezwyk³e budynki, chyba z samolotów.}
{136} {} {}
{137} {} {}
{138} {} {Ten bunkier wydaje siê byæ opuszczony od stu lat.}
{139} {} {Widzisz przed sob¹ stare ruiny. Wilgotne powietrze sugeruje, ¿e za nimi musi byæ morze.}
{140} {} {Jesteœ na ma³ej przystani.}
{141} {} {Po raz pierwszy w ¿yciu jesteœ na pok³adzie niszczyciela.}
{142} {} {}
{143} {} {Droga prowadzi do tamy. Bastion Rangersów na pewno jest na jej szczycie.}
{144} {} {}
{145} {} {}
{146} {} {Docierasz do wielkiego miasta po³o¿onego wœród staro¿ytnych ruin. Jego ponure ulice witaj¹ ciê gêstym smogiem.}
{147} {} {}
{148} {} {Te slumsy wygl¹daj¹ na niebezpieczne. Lepiej mieæ siê na bacznoœci.}
{149} {} {Nad miastem wznosi siê ozdobny budynek. A przed nim, t³um ludzi b³¹kaj¹cych siê bez celu.}
{150} {} {}
{151} {} {}
{152} {} {}
{153} {} {}
{154} {} {}
{155} {} {To miejsce jest otoczone nieprzejezdnymi ruinami. Nic dziwnego, ¿e trudno je znaleŸæ.}
{156} {} {Wnêtrze tego miejsca wydaje siê byæ puste. Jakby zabrano st¹d wszystko, co po¿yteczne, i to bardzo dawno temu.}
{157} {} {Przybywasz do ma³ego miasteczka Casa Grande, po³o¿onego na œrodku tras wielu karawan.}
{158} {} {}
{159} {} {}
{160} {} {To miejsce... pamiêta wszystkie okropnoœci Wielkiej Wojny.}
{161} {} {Widzisz zwêglone ruiny niegdyœ du¿ego miasta. Jego ulice s¹ teraz zalane niebezpiecznymi stworzeniami.}
{162} {} {}
{163} {} {}
{164} {} {Znajdujesz ma³e miasteczko otoczone zielonymi plantacjami. W tej oazie toczy siê ¿ycie.}
{165} {} {Na œrodku pustyni odkrywasz ogromn¹ plantacjê. Krajobraz tak Ci znany, a jednoczeœnie tak obcy...}
{166} {} {}
{167} {} {Opuszczony szlak prowadzi do kryjówki bandytów. Wygl¹da na to, ¿e nikt tu na Ciebie nie czeka.}
{168} {} {To miejsce wygl¹da na opuszczone, ale mimo wszystko czujesz niepokój.}
{169} {} {Co za smutny widok. Przez nastêpne sto lat to miejsce bêdzie niezdatne do zamieszkania.}
{170} {} {Wchodzisz do kopalni uranu.}
{171} {} {Na poboczu drogi, niczym duch, pojawia siê samotny motel.}
{172} {} {Stara wysoka latarnia morska na brzegu kusi okazjonalnych podró¿ników.}
{173} {} {}
{174} {} {}
{175} {} {}
{176} {} {Twoje kroki odbijaj¹ siê echem w ciszy katedry.}
{177} {} {Wygl¹da to na cmentarz dawno zapomnianej technologii.}
{178} {} {}
{179} {} {Wchodzisz do staro¿ytnych ruin. Od bardzo dawna nikt tu nie mieszka.}
{180} {} {Brzegi Kolorado poroœniête s¹ ciernist¹ roœlinnosci¹, która mo¿e kryæ ró¿norodn¹ zwierzynê.}
{181} {} {}
{182} {} {Czas nie by³ ³askawy dla tego miejsca - zrujnowane budynki zawali³y siê, a burze piaskowe pokry³y ruiny warstw¹ piasku.}
{183} {} {}
{184} {} {}
{185} {} {}
{186} {} {}
{187} {} {}
{188} {} {Zaczynasz ju¿ odczuwaæ desperacjê, szukaj¹c ludzkich osad, kiedy nagle pojawia siê przed tob¹ ma³e ranczo.}
{189} {} {Pustynia zamienia siê w zniszczone parterowe bloki. Wygl¹da na to, ¿e osiedli³ siê tu garnizon wojskowy.}
{190} {} {Po miniêciu starych kwater wspinasz siê do fortu na wzgórzu Cerro de la Campana.}
{191} {} {Na pozór ta stara szko³a wygl¹da na zrujnowan¹ i opuszczon¹. Lepiej jednak zachowaæ czujnoœæ.}
{192} {} {}
{193} {} {}
{194} {} {Wygl¹da na to, ¿e stra¿nicy okresowo obserwuj¹ tê przepompowniê. Przynajmniej dzia³a.}
{195} {} {Przed sob¹ widzisz ocala³y budynek z oœwietlonymi oknami. Przed nim natomiast b³¹ka siê ca³a gromada rozpruwaczy.}
{196} {} {}
{197} {} {}
{198} {} {}
{199} {} {}
{200} {} {}
{201} {} {To miejsce wydaje siê zupe³nie ciche. Ale jednoczeœnie czujesz panuj¹ce tu niesamowite napiêcie.}
{202} {} {}
{203} {} {}
{204} {} {}
{205} {} {}
{206} {} {}
{207} {} {}
{208} {} {}
{209} {} {}
{210} {} {Budynek magazynu zosta³ powa¿nie uszkodzony przez falê uderzeniow¹. Wiêkszoœæ towarów prawdopodobnie uleg³a zniszczeniu.}
{211} {} {}
{212} {} {Wygl¹da na to, ¿e ten kamienio³om zosta³ nagle zamkniêty.}
{213} {} {}
{214} {} {}
{215} {} {}
{216} {} {}
{217} {} {}
{218} {} {}
{219} {} {}
{220} {} {Wydajesz siê byæ na przyjêciu przez przypadek.}
{221} {} {Widzisz staro¿ytny pomnik. Wygl¹da na to, ¿e jest tu od dziesiêcioleci lub d³u¿ej.}
{222} {} {Widzisz stary cmentarz. Tak stary, ¿e jest ca³kowicie poroœniêty pustynnymi roœlinami.}
{223} {} {}
{224} {} {}
{225} {} {}
{226} {} {}
{227} {} {}
{228} {} {}
{229} {} {}
{230} {} {}
{231} {} {}
{232} {} {}
{233} {} {}
{234} {} {}
{235} {} {}
{236} {} {}
{237} {} {}
{238} {} {}
{239} {} {}
{240} {} {Schodzisz do jaskini. Bez znajomoœci dok³adnych wspó³rzêdnych, nigdy nie uda³oby ci siê znaleŸæ tego miejsca.}
{241} {} {}
{242} {} {}
{243} {} {}
{244} {} {Wkraczasz w obszar radioaktywny. Tyk-tyk.}
{245} {} {}
{246} {} {}
{247} {} {}
{248} {} {Wkraczasz w obszar radioaktywny. Tyk-tyk.}
{249} {} {}
{250} {} {To ja³owe pustkowiê.}

{500} {} {Otrzymujesz }
{501} {} { doœwiadczenia za przetrwanie w piwnicach Villi.}
{502} {} {WiêŸniowie uciekli z zak³adu karnego!}
{503} {} {Otrzymujesz }
{504} {} { PD za zniszczenie Katedry Swiêtego Ognia.}
{505} {} {Pozosta³o }
{506} {} { sekund do wybuchu.}
{507} {} {Otrzymujesz }
{508} {} { PD za zniszczenie Cytadeli Rangersów.}
{509} {} { PD za zniszczenie fortu Bractwa Stali.}
{510} {} {Uda³o ci siê nielegalnie zinfiltrowaæ kwaterê g³ówn¹ Bractwa Stali, omijaj¹c wartowników na przejœciu.}
{511} {} {Teraz najwa¿niejsze to siê nie poparzyæ.}
{512}{}{Otrzymujesz }
{513}{}{ doœwiadczenia za przekroczenie granicy.}
{514}{}{ doœwiadczenia za pomyœlne dotarcie do wyspy Coronado.}
{515}{}{ doœwiadczenia za ostateczne zniszczenie wyspy Coronado.}
{516}{}{ doœwiadczenia za uwolnienie wyspy Coronado spod kontroli wojskowej.}