{110} {} {Pu³apka!}
{111} {} {Znajdujesz pu³apkê.}
{112} {} { wpada w pu³apkê.}
{113} {} {Twoje umiejêtnoœci uchroni³y ciê przed niebezpieczn¹ pu³apk¹.}
{114} {} {}
{115} {} {Ta pu³apka wydaje siê zbyt niebezpieczna.}
{116} {} {Pu³apka zosta³a pomyœlnie rozbrojona.}
{117} {} {Boisz siê, ¿e nie bêdziesz w stanie prawid³owo ustawiæ pu³apki.}
{118} {} {Pu³apka ustawiona.}
{119} {} {Ta pu³apka jest obecnie bezpieczna.}
{120} {} {Ta pu³apka jest zbyt niebezpieczna. Najpierw trzeba j¹ zneutralizowaæ.}
{121} {} {Skrêcasz emiter.}
{122} {} {Nie uda³o ci siê skrêciæ emitera.}
{123} {} {Mo¿na tu zastawiæ fajn¹ pu³apkê.}
{124}{}{To mo¿e byæ ca³kiem niez³a pu³apka.}
