{100} {} {Masz ma³y wypadek, ale prze¿yjesz.}
{101} {} {Góry próbuj¹ ciê powstrzymaæ. Ale z powodzeniem omijasz spadaj¹ce kamienie.}
{110} {} {Przechodzisz przez napromieniowane ziemie i otrzymujesz zwiêkszon¹ dawkê promieniowania.}
{120} {} {Nie udaje ci siê umkn¹æ burzy piaskowej!}
{130} {} {Na pró¿no próbujesz znaleŸæ wodê.}
{131} {} {Po wyczerpuj¹cych poszukiwaniach nareszcie znajdujesz trochê wody.}
{132} {} {Uda³o Ci siê utrzymaæ nawodnienie dziêki w³asnemu zaopatrzeniu w wodê.}
{133} {} {Uda³o ci siê utrzymaæ nawodnienie dziêki zapasom z Manierki.}
{134} {} {Wygl¹da na to, ¿e ostatnio mia³ tu miejsce wypadek. Kolejny dzieñ na pustkowiach...}
